### ISSUE TITLE
json account import not woking in Mac Big Sur

### ISSUE THREAD

**Issue by latetot** [MetaMask/metamask-extension#10008]
**Describe the bug**
Unable to import json account file in Mac Big Sur.  Screen becomes dark and unable to select files from file manager.  Using version 8.1.5 - confirmed in both Chrome and Brave browsers

**Steps to reproduce (REQUIRED)**
Account import- json

**Expected behavior**
Should be able to select file and import

**Screenshots**

**Browser details (please complete the following information):**
metamask 8.1.5
chrome / brave latest

**Comment by tmashuang** [comment]
Not able to reproduce on macOS Big Sur 11.0.1/Chrome 87.0.4280.88
