### ISSUE TITLE
Contract interaction transaction history is gone

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#10005]
**Describe the bug**
"Contract Interaction" events seem to have disappeared from account history.
Following a recent MetaMask forced update (not sure which one), even after interacting with contracts and confirming dozens/hundreds of transactions without having done an account reset, the account history still shows this:
![image](https://user-images.githubusercontent.com/563406/101212519-d8edb600-3646-11eb-9244-5e7b6b581240.png)

After confirming one transaction, if I leave the MetaMask popup open (continuing to show this view) while the dapp initiates another transaction, there is also nothing in this list showing the unconfirmed transaction that I can click on to get to the confirmation screen.  I have to click outside of the popup to close it, then click on the toolbar icon to re-open the popup to see the transaction confirmation request.

Note: If I send Ether from this account, I see that transaction in the account history, but additional contract interactions still don't show up.

**Steps to reproduce**
With modern MetaMask, interact with a Dapp and confirm a transaction which is subsequently mined.  In my testing, this was on a private network that I was consistently connected to when observing the issue.

**Expected behavior**
I expected a "Contract Interaction" entry to appear in the Activity/transactions history list.   Further, if there is a pending/unconfirmed transaction, I expect that to be there too so I can click on it and confirm the transaction.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: N/A
 - Browser: Chrome 86.0.4240.183 (Official Build) (64-bit)
 - MetaMask Version: 8.1.5

**Comment by wbt** [comment]
After a couple days, possibly with a triggering event of changing networks/accounts away and back again, the bug disappeared and the contract interactions are showing up in the list again. I still think there's a bug here, so this should stay open, but I agree with the N02 tag.

**Comment by danfinlay** [comment]
> Following a recent MetaMask forced update 
FYI, you can turn off automatic updates in Chrome.

Thanks for the report, it seems likely this was related to the migration logic from v8 to v9, and we did fix some of that logic in more recent updates.

I'm going to close this issue until anyone else ever encounters it, it seems like it may have been very isolated.
