### ISSUE TITLE
Mainnet gas price estimates used in send flow on non-Mainnet networks

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#10003]
**Describe the bug**
In the Send flow, the ETH Gas Station "standard" price is used as the default gas price, even when not on Mainnet.

**Steps to reproduce (REQUIRED)**

1. Switch to some network other than Mainnet (e.g. Ropsten)
2. Click "Send" on the Home page
3. Select one of your accounts
4. See that the gas price matches the "standard" price on ETH Gas Station

**Expected behavior**
The default gas price should be determined by `eth_gasPrice`, as it is for transactions that are sent by dapps via `eth_sendTransaction`.

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
 - MetaMask Version: v8.1.6

(Originally reported [here](https://github.com/MetaMask/metamask-extension/issues/3912#issuecomment-727091074) by @d10r in #3912 - thanks!)

**Comment by Gudahtt** [comment]
Note that we've replaced ETH Gas Station since I created this issue, but the problem is still present. The new gas API estimates are now shown instead of the `eth_gasPrice` estimates.

**Comment by brad-decker** [comment]
@kevinho reported this issue again in #10416 specifically for huboichain
