### ISSUE TITLE
Fetch swaps quote refresh time from the API

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#10010]
Currently, the swaps quote refresh time is hard coded to 60 seconds. We want to update this so that the refresh time is retrieved from an api endpoint. We will have to collaborate with the metaswap api team to successfully complete this task.

**Comment by cloudonshore** [comment]
Endpoint is now here: https://api.metaswap.codefi.network/quoteRefreshRate

Response is the number of seconds to wait before fetching new quotes
```
{
  "seconds": 30
}
```
