### ISSUE TITLE
Create library for dapp e2e testing on release candidates

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10029]
We know there are tools that allow e2e testing with MetaMask (link needed, please add here)

As a dapp developer, I'd like to be able to subscribe my test suite to our release candidate infrastructure so that:
- On every new release candidate, my dapp's test suite runs.
- If my test suite fails on an RC, it replies on that release candidate (on GitHub) with a link to the failure reason, as well as emailing the dapp maintainer/opening an issue.

This would both be a great way for dapp devs to keep their dapps compatible, and a good way for MetaMask to decentralize its integration testing to be more sensitive to the wider ecosystem, and could also help communications around any planned breaking changes (for participating dapps).

**Comment by tmashuang** [comment]
Related to #6040 #6041

**Comment by Gudahtt** [comment]
Lots of great ideas here! I think this is mostly captured by #5805 though, so I'm going to close this as a duplicate. Maybe anything here not represented in #5805 could be transferred over.
