### ISSUE TITLE
window.ethereum is now missing from all pages on Firefox

### ISSUE THREAD

**Issue by enolan** [MetaMask/metamask-extension#10023]
**Describe the bug**
`window.web3` is no longer there, on any page. This breaks, well, everything.

**Steps to reproduce (REQUIRED)**

1. Open a new tab.
2. Open the JS console.
3. Type `window.ethereum`
4. See `undefined`

**Expected behavior**
There should be an EIP-1193 provider there.

**Browser details (please complete the following information):**
 - OS: Linux, NixOS
 - Hardware Wallet: N/A
 - Browser: Firefox 83.0
 - MetaMask Version: 8.1.6

**Additional context (Error Messages, etc.)**
MetaMask 8.1.6 made it to AMO sometime today, this is probably a regression with that version.

**Comment by johansten** [comment]
Same here. Can't do anything.
MacOS 11.0.1, FF 83.0, MM 8.1.6

**Comment by danfinlay** [comment]
We've identified the issue as a weird behavior in how Firefox handles loading a zipped extension vs an unzipped extension (so we did not catch it in dev or testing). We're reverting the change that triggered this behavior now, we will then report the issue to Firefox and make a longer term fix.

**Comment by danfinlay** [comment]
Will be fixed in 8.1.7, which you can get an early copy of [here](https://github.com/MetaMask/metamask-extension/pull/10020#issuecomment-741527009) and then fully [here](https://github.com/MetaMask/metamask-extension/releases)
