### ISSUE TITLE
Crash recovery leads popup number to be incorrect

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#10022]
**Describe the bug**
After recovery from a crash, the number shown on the Metamask icon has an off-by-one error.

**Steps to reproduce**
These are the steps I followed but I can't claim they're easy to follow/reproduce:
 -   OS: Windows 10, low on free memory
 -   Hardware Wallet: N/A
 -   Browser: Chrome 86.0.4240.183 (Official Build) (64-bit)
 -   MetaMask Version: 8.1.5

A dapp triggered a set of 18 transactions, which must be individually confirmed because #4050 is not implemented.  After 17 successful confirmations, MetaMask crashed.  The separate popup windows report as Not Responding to Windows (but can be closed with the X button in the upper right); clicking on the popup with its "1 [transaction pending]" indicator produced nothing.  Trying to Inspect Popup produced nothing.  
On loading a dapp page in a different tab, the dapp crashed, presumably in one of the lines where it tries to initialize MetaMask, and used its normal interface hang reporting.  Switching to another tab, Metamask's crash completely crashed Chrome.

On restarting Chrome, the "1 [transaction pending]" indicator remained visible on the MetaMask icon.  Clicking on the MetaMask icon produced a login dialogue as is typical after restarting the browser. After entering the password, the dialogue was dismissed **and the [1] disappeared**.  However, the transaction remained pending.  Guessing and clicking the MetaMask icon to get the popup, I could see the confirmation dialogue, and confirm the transaction.  

**Expected behavior**
The numeric indicator of pending transactions should still be present if there is a pending transaction, even after user login; user login should not count for this purpose as approving a pending transaction.

**Comment by Gudahtt** [comment]
This reproduction looks pretty challenging! We should at least audit the logic for this badge number though, even if we can't repro this. The badge number logic is fairly concise.

**Comment by wbt** [comment]
If there hasn't been anything specific to fix this, it's probably still an issue.

**Comment by wbt** [comment]
If there hasn't been anything specific to fix this, it's probably still an issue.

**Comment by wbt** [comment]
If there hasn't been anything specific to fix this, it's probably still an issue.
