### ISSUE TITLE
Cannot see advanced gas chart on token allowance txs

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#10031]
**Describe the bug**
User reports only being able to manually edit the gas gwei and gas limit numbers but is unable to see the chart on token allowance txs.

![image](https://user-images.githubusercontent.com/16330048/101681423-bb926080-3a27-11eb-96d1-8fe30cc40bdf.png)

**Expected behavior**
User should see the chart like any other advanced gas modification.

ticket # 69604

**Comment by Gudahtt** [comment]
This chart was intentionally removed in https://github.com/MetaMask/metamask-extension/pull/9867 as part of replacing our use of  ETH Gas Station with the MetaSwaps gas API. We no longer have access to the gas prediction data that we used to generate the chart.
