### ISSUE TITLE
invalid project id

### ISSUE THREAD

**Issue by gpersoon** [MetaMask/metamask-extension#10042]
**Describe the bug**
Dapp didn't work and developer console showed error : invalid project id

**Steps to reproduce (REQUIRED)**
Seen after metamask 8.1.6 was installed
Load a dapp that interacts with Metamask and obverse the developer console.

**Expected behavior**
The dapp would work without any error messages.

**Browser details (please complete the following information):**
 - Windows 10
- Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- Metamask 8.1.6

**Additional context (Error Messages, etc.)**
After a few reloads of the Dapp the error messages was gone and could not be reproduced.

**Comment by Gudahtt** [comment]
Thanks for the report @gpersoon!

I saw this once today too :thinking: But then it never happened again.

**Comment by Gudahtt** [comment]
I suspect that Infura mistakenly returns this error sometimes when under high load, even when given a valid project ID. We'll investigate this further. Maybe we can roll this up into a general "can't connect to network" error, and handle this in the UI like any other network error.
