### ISSUE TITLE
`ETH` displays multiple times in the swaps `Swap To` dropdown list

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#10049]
**Describe the bug**
The "swap to" dropdown list on the swaps page displays "ETH" 3 times.  Their data structures appear to be very much the same:

<img width="1077" alt="ETHs" src="https://user-images.githubusercontent.com/46655/101853854-02668000-3b26-11eb-84b7-70d1ada17405.png">

After walking the release tags down to swaps' introduction, it appears this bug existed when swaps launched.

@danjm and I tracked down to the following lines in `ui/app/hooks/useTokensToSearch.js`'s `useTokensToSearch` function:

* `tokensToSearch = [memoizedEthToken, ...swapsTokens]`
* `owned: singleToken ? [] : [memoizedEthToken],`

There is no risk of loss in funds, as the three items are the same.  We should, however, fix this ASAP so that there's no confusion to the user.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Click the "Swaps" button
2. For the "Swap from" dropdown, choose any item except "ETH"
3. For the "Send to" dropdown, type "ETH"

**Expected behavior**
See only one item, not three

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: None
 - Browser: Firefox Nightly
 - MetaMask Version: Started in Swaps' launch, 8.1.0, and up until current develop (8.1.8)

**Comment by darkwing** [comment]
@danjm's proposal is https://gist.github.com/darkwing/a2638dca8140836052e0e18e325b5860, which will be a good place to start.

**Comment by darkwing** [comment]
@danjm's proposal here is very close, knocking down the `ETH` display count from 3 down to 2.  The last `ETH` item is coming from the following conditional:

https://gist.github.com/darkwing/a2638dca8140836052e0e18e325b5860#file-ui-app-hooks-usetokenstosearch-js-diff-L31-L36

I'm hoping to talk to Dan to understand what `singleToken` represents, and why we're using some of the other conditionals for these lists.

**Comment by danjm** [comment]
closed by https://github.com/MetaMask/metamask-extension/pull/10650
