### ISSUE TITLE
`eth_getProof` returns `method does not exist` when backing client supports it.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#10068]
**Describe the bug**
When attempting to issue an `eth_getProof` method call from an application via `window.ethereum.request(...)` the following error is returned:
```json
{
  "code": -32601,
  "message": "The method 'eth_getProof' does not exist / is not available.",
  "data": {
    "method": "eth_getProof",
    "params": [],
    "jsonrpc": "2.0",
    "id": 2890872336,
    "origin": "http://localhost:8080",
    "tabId": 43
  },
}
```

Debugging the extension shows that the request is not forwarded along to the backing Ethereum client.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Open a page with MM hooked up and enabled.
2. Open a browser console.
3. `window.ethereum.request({method:'eth_getProof', params:[]}).then(console.log).catch(console.error)`

**Expected behavior**
An error about incorrect parameters is returned (for the above repro case) or a proof is returned (for an actual proof request).

**Browser details (please complete the following information):**
 - OS: Windows
 - Hardware Wallet: N/A
 - Browser: Firefox
 - MetaMask Version: 8.0.9

**Additional context (Error Messages, etc.)**
This method is necessary for doing censorship resistant price feed oracles from Uniswap without needing to have some centralized or incentivized maintenance mechanism.  For example: https://github.com/Keydonix/uniswap-oracle/

**Comment by zimmah** [comment]
Agreed, this method would be really handy. Infura already supports it, which is why I use infura as a workaround currently.

Would be nice if MetaMask supports it too.
