### ISSUE TITLE
Ledger no longer being detected

### ISSUE THREAD

**Issue by maxsam4** [MetaMask/metamask-extension#10067]
**Describe the bug**
I am unable to sign transactions with my ledger on Chrome. It is connected to metamask but nothing happens when I try to sign a transaction. When I go back to "Connect a hardware wallet", it keeps circling but never finds the ledger device.

It used to work fine (I have the ledger device connected in metamask) till it just stopped working one day.

It still works fine on Firefox.

**Steps to reproduce (REQUIRED)**
Try connecting a ledger device on metamask on google chrome?

**Expected behavior**
The ledger device is detected and works properly.

**Screenshots**
![Screenshot from 2020-12-12 10-20-19](https://user-images.githubusercontent.com/7436022/101975677-3cd63700-3c64-11eb-830b-7fb17c1a3003.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Hardware Wallet: Ledger nano S: firmware version 1.61, Ethereum app version: 1.6.2
 - Browser: Google chrome Version 87.0.4280.88 (Official Build) (64-bit)
 - MetaMask Version: 8.1.6

**Comment by tmashuang** [comment]
Try refreshing the page and/or disable and reenable the extension. There might be a cached pending ledger request that did not timeout correctly.

**Comment by maxsam4** [comment]
> Try refreshing the page and/or disable and reenable the extension. There might be a cached pending ledger request that did not timeout correctly.

Tried both, multiple times. Didn't help.

**Comment by sobertram** [comment]
Same issue here. Current ledger firmware is 1.6.1 on nano s device and Ledger live reports this as latest and up to date. Ether app is 1.6.2. I am on windows.
Google Chrome is up to date
Version 87.0.4280.88 (Official Build) (64-bit)
MetaMask Version
8.1.9

This was working about a month or so ago. I am not sure if it's also because I am doing transactions on goerli but this is the same network when it was working for me previously.

**Comment by maxsam4** [comment]
FYI, for me, the problem was the [NoScript](https://chrome.google.com/webstore/detail/noscript/doojmbjmlfjjnbmnoijecmcbfeoakpjm) plugin. 

IDK why but it was blocking metamask's background page from accessing the [ledger bridge](https://metamask.github.io/eth-ledger-bridge-keyring/bundle.js). The URL was opening fine in a normal tab in the browser but still being blocked when being accessed via metamask. Disabling the plugin fixed the issue. IDK what exactly caused this weird behavior though.
