### ISSUE TITLE
Transaction shows up on blockchain but not in app

### ISSUE THREAD

**Issue by DISC30** [MetaMask/metamask-extension#10076]
**Describe the bug**
Hay there metamask shows that I added funds on December 8 (https://etherscan.io/tx/0x6b696531904ed38f82fb4120e20b071917688a9f0aeafb4a7d063a35fee82c58) but says my wallet has no funds:
![wallet discrepancy](https://user-images.githubusercontent.com/48271670/102173121-3e854200-3e92-11eb-81bb-e1e8689c2886.png)

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Metamask wallet
2. Click on Request Funds
3. Go to other wallet
4. Send funds to Metamask wallet address

**Expected behavior**
I expect that the amount of funds received (0.021164ETH) gets added to the previous amount of funds in the wallet (0ETH).

**Screenshots**
![wallet discrepancy2](https://user-images.githubusercontent.com/48271670/102173358-be131100-3e92-11eb-8762-4370ad8f1298.png)

**Browser details (please complete the following information):**
 - OS: Linux
 - Hardware Wallet: none
 - Browser: Brave 1.11.101
 - MetaMask Version: 8.1.8

**Additional context (Error Messages, etc.)**

**Comment by brad-decker** [comment]
Hi @DISC30, thanks for reporting. could you help me out with your steps to reproduce? There's an item that says "click on Request Funds" could you be more explicit about where in the wallet interface you are clicking?

**Comment by DISC30** [comment]
Ah I meant click Buy and then Show Account (and send funds to that account):
![wallet discrepancy3](https://user-images.githubusercontent.com/48271670/102288258-0d5d4e00-3f34-11eb-8037-b8ca94d0119b.png)

**Comment by brad-decker** [comment]
It'd be helpful for us to get a look at your state logs. [Submit a ticket](https://metamask.zendesk.com/hc/en-us/requests/new), referencing this issue and [include your state logs in the attachments](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue)

**Comment by Gudahtt** [comment]
@DISC30 can you still reproduce this bug on the latest version of MetaMask? We saw that some users were getting their Infura requests blocked, and that might have caused this. We've made a configuration change that addressed that issue.

**Comment by DISC30** [comment]
That did the trick, works now! Thaaaaanks

**Comment by Gudahtt** [comment]
Thanks for the update!
