### ISSUE TITLE
Extraneous lockdowns?

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#10082]
Apparently due to merge of #9568, the browser console displays the following notices upon every pageload one or more times, from lockdown.js:2516:

> Removing intrinsics.Promise.any
> Removing intrinsics.Reflect.@@toStringTag
> Removing intrinsics.%StringPrototype%.replaceAll

**Steps to reproduce (REQUIRED)**
1. In a MetaMask-enabled browser, load a Web page.  It doesn't really matter which.  You don't have to be logged in to MetaMask and the page you are on doesn't have to have anything to do with web3/blockchains.
2. Open the browser console.
3. Observe the messages.

**Expected behavior**
Without knowing the rationale for excluding these three from the whitelist or the impact on developers (e.g. will Promise.any() just no longer work on any site?) it's hard to say what the expected behavior is.  Why are those left off the whitelist?
Having an additional log explaining why these are off or what the impact is might be useful.

**Screenshots**
Sample of logs when visiting metamask.io (which also show #8167):
![image](https://user-images.githubusercontent.com/563406/102280807-d23f2880-3efb-11eb-9176-3dc95799fe7f.png)

**Browser details:**
 - OS: Windows 10
 - Hardware Wallet: N/A
 - Browser: 87.0.4280.88 (Official Build) (64-bit)
 - MetaMask Version: 8.1.8

**Comment by Gudahtt** [comment]
Thanks for the report! This was fixed by #10040, which is included in v8.1.9.

Note that apart from polluting the console, this lockdown has no impact upon sites. The lockdown only affects the contentscript environment, which shares a console with the page but has its own execution environment and set of globals and so on.

**Comment by wbt** [comment]
Thanks!  I had delayed reporting on this figuring surely someone would notice that probably with a better root cause ID and fix, but couldn't find the dupe due to lack of matching keywords in the discussion (and initially, also GitHub's default of including is:issue in the search criteria).
