### ISSUE TITLE
Background errors not serialized correctly when sent to UI

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#10090]
**Describe the bug**
When an error occurs in the background, it's not serialized correctly when sent to the UI. The error arrives as a plain object with its `stack` missing, so the resulting Sentry reports are difficult to debug.

**Expected behavior**
The error should still have a type of `Error` and should retain its `stack` when sent from the background to the UI.

**Comment by Gudahtt** [comment]
The error is being serialized like this by `dnode`. @rekmarks investigated this and might have a solution but it'd involve forking `dnode` and various other libraries that it depends upon, and we're not especially eager to maintain a fork of all of that stuff.

We could also consider replacing `dnode` with an alternative, like `capnode` or `capTP`.

**Comment by danjm** [comment]
More context for metamask devs [here](https://consensys.slack.com/archives/GTQAGKY5V/p1607659669487600)

**Comment by seaona** [comment]
Looks like this error is still appearing on Sentry and it has a huge amount of occurrence:

![image](https://user-images.githubusercontent.com/54408225/176206470-55848d96-0d46-4af8-bec2-726273db7da6.png)

I've been able to reproduce it by adding Matic nework with this RPC `https://rpc-mainnet.matic.network` and waiting. It usually throws a lot of errors. If you wait a little bit, you can see this error logged in your Sentry project.

**Comment by kumavis** [comment]
still very active with high occurance

**Comment by Gudahtt** [comment]
Which error is still occurring? This issue was meant to fix a serialization problem that was obscuring some of our Sentry reports, it wasn't addressing a particular error. It looks like many have been linked here.

**Comment by legobeat** [comment]
Is this related to https://github.com/MetaMask/rpc-errors/issues/131?
