### ISSUE TITLE
Notifications.html stuck with unconfirmed transactions - Metamask gets locked and pinned to the notification screen

### ISSUE THREAD

**Issue by raul782** [MetaMask/metamask-extension#10095]
**Describe the bug**
If you submit a transaction and the gas is high so you don't have enough funds. the notifications screen/popup with the pending transaction prevents you to access any other screen in metamask. Essentially you get locked, and can't use metamask anymore, not even accessing a different dapp, switching accounts or networks.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1- You do a contract interaction with $0 eth and if initially, you don't have enough funds. The transaction will be kept pending
2- If you try a few more times, the next transactions will still be pending, any individual or group rejection click event from the notification screen hangs indefinitely
3- You no longer can reset your account, since Settings and any other screen gets hidden away. The notifications popup always gets in front and there is no way to get rid of this.
4- If you try to hit home.html manually, you are forced to the following anchor route: moz-extension://...../home.html#confirm-transaction/12345678/token-method

**Expected behavior**
I should be able to reject transactions with insufficient funds or low gas fees. I shouldn't be locked out to access other screens. This has gotten worse with the latest updates. At least before, you could switch accounts.

**Screenshots**
![Screen Shot 2020-12-16 at 23 28 08](https://user-images.githubusercontent.com/181557/102444321-eb78cf80-3ff6-11eb-9ad3-ae0d20054752.png)

**Browser details (please complete the following information):**
 - OS: macOS Catalina
 - Hardware Wallet: No
 - Browser: Firefox Browser 84.0 (64bits)
 - MetaMask Version: 8.1.8

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment]
Thanks for the report!

I have so far been unsuccessful in reproducing this problem. Whenever I trigger a contract interaction from a dapp, the "Reject" button works (both when rejecting individual transactions, and when rejecting a group).

Are there any errors in the console when you attempt to reject the transaction? Or are there any errors in the background console when you attempt the reject? (You can check the background console by navigating to "Add-Ons", clicking the gear menu to the right of "Manage Your Extensions", clicking "Debug Add-ons", then clicking the "Inspect" button next to MetaMask.)

**Comment by raul782** [comment]
Hi @Gudahtt ,
So incredible, the error went away after enabling debugging. The notifications screen stopped blocking home and I was able to reject all transactions. I'm back to business. Thanks a lot

**Comment by Gudahtt** [comment]
Great to hear! Thanks for the update. Please let us know if you see this happen again.
