### ISSUE TITLE
Missing SLP

### ISSUE THREAD

**Issue by BottmDwellrZ** [MetaMask/metamask-extension#10108]
I deposited over 5,000 SLP from some of my sub accounts to my main account on my metamask. I saw the slp there at one point, but then I looked again later and it was gone. Said that it was deposited to an address. I am really confused and scared I am going to lose all of that SLP. Please help! Here is the address it was deposited to. I have checked it is not one of my accounts: 0xf07301925b5ADD4E9698E160e193650210918866

**Comment by Gudahtt** [comment]
Please contact support here: https://metamask.zendesk.com/hc/en-us/requests/new
They can help you troubleshoot and find out what happened.
