### ISSUE TITLE
Nothing returns or throws when ledger is trying to send eth_getEncryptionPublicKey

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#10111]
**Describe the bug**
When making a request to hardware connected wallet like Ledger, for `eth_getEncryptionPublicKey` method, nothing returns. 
I'd expect to receive an exception or at least something from such request.

**Steps to reproduce (REQUIRED)**
```js
try {

const callParamsForKey = {
        method: 'eth_getEncryptionPublicKey',
        params: [ethAccount]
      }

await window.ethereum.request(callParamsForKey)
} catch(e) {}
```

**Expected behavior**
Exception should be thrown if not supported

**Browser details (please complete the following information):**
 - OS: OSX
 - Hardware Wallet: Ledger Nano S Firmware version 1.6.0
 - Browser: Version 87.0.4280.88 (Official Build) (x86_64)
 - MetaMask Version: 8.1.9

**Comment by rstormsf** [comment]
@Gudahtt just open app.tornado.cash/mining click setup account

**Comment by anthonymartin** [comment]
I can confirm this behavior as well

**Comment by rstormsf** [comment]
any update on this? @Gudahtt

**Comment by tmashuang** [comment]
Do they support the `eth_getEncryptionPublicKey` method?

**Comment by rstormsf** [comment]
@tmashuang they don't support it, but it should give an error from metamask

**Comment by dmcxx** [comment]
@Gudahtt demo implementation is done [here](https://github.com/miguelmota/metamask-encryption-example/blob/master/public/main.js) + [live demo](https://lab.miguelmota.com/metamask-encryption-example/public/).

As you can test it, with HW wallets, the prompt is displayed, but after it doesn't anything neither throws any error.

**Comment by firnprotocol** [comment]
hi all. can the resolution https://github.com/MetaMask/metamask-extension/pull/10326 be re-visited, now that [_Ledger supports this feature_](https://github.com/LedgerHQ/app-ethereum/issues/189)? I can also create a new issue. thanks all.

**Comment by pepawel** [comment]
> hi all. can the resolution #10326 be re-visited, now that [_Ledger supports this feature_](https://github.com/LedgerHQ/app-ethereum/issues/189)? I can also create a new issue. thanks all.

+1 because it will allow to use some great dapps in a secure way using Metamask + Ledger.

**Comment by jacquesvcritien** [comment]
+1, is there an update on this please?
