### ISSUE TITLE
MetaMask - RPC Error: execution reverted {code: -32000, message: "execution reverted"

### ISSUE THREAD

**Issue by an-ivannikov** [MetaMask/metamask-extension#10122]
**Bug Description**
I am trying to understand better the uniswap logic for development.
I have a problem like this,
I deploy new instances of contracts and change the `UniswapV2Router02` and `UniswapV2Factory.sol` addresses in the `uniswap-interface`

After that, part of the interface does not work. In particular, when adding liquidity, Metamask issues such an error
`MetaMask - RPC Error: execution reverted {code: -32000, message: "execution reverted"}`

Nothing has changed in the code, only the addresses of contracts with the same code as the original contracts.

I am developing in ropsten.

**Expected Behavior**
I expect metamask to handle the contract access without any problems, since only the contract address has been changed.

**Comment by brad-decker** [comment]
@an-ivannikov are you seeing this message in response to a provider call or in the background process of MetaMask?

**Comment by an-ivannikov** [comment]
I saw this in the developer panel in chrome browser, in the console.

I think that if we deploy the contracts code and replace the router and factory addresses in the interface, then the interface should work.

But I am getting error from metamask.

**Comment by an-ivannikov** [comment]
Perhaps I missed some point ... but what if the contracts code is not changed and is just posted to a different address ...
As I understand it, the transaction is not even sent to the blockchain.

**Comment by hoangvuong-689cloud** [comment]
Hi @an-ivannikov , 

I am trying to deploy Uniswap on Ropsten and have the same issue. 

Guideline: https://blockchain.news/wiki/how-to-build-an-uniswap-exchange

Can you give me some advice to solve that issue?

Thanks.

**Comment by an-ivannikov** [comment]
Thank you, I have already solved this problem)
Yes I can

**Comment by hoangvuong-689cloud** [comment]
Hi @an-ivannikov ,

What is the key to solving this problem? I think this issue happens when I deploy UniswapV2Router02 at another address

**Comment by an-ivannikov** [comment]
The problem is that you first need to compile the uniswap-v2-core contracts

Next, you need to get INIT_CODE_HASH from the bytecode of the UniswapV2Pair.sol contract

Next you need
1) Replace it in Line # 24 for `uniswap-v2-periphery / contracts / libraries / UniswapV2Library.sol`.
2) Replace it in `INIT_CODE_HASH` for` uniswap-sdk / src / constants.ts`.

Next you need
1) compile the uniswap-v2-periphery code

Next you need
1) deploy ValueswapV2Factory and ValueswapV2Router02
2) replace the corresponding addresses

**Comment by Jackie-Zhong** [comment]
hi,buddy:
did you have solved your problem like this?please help.i can't understand why the problem happen.
MetaMask - RPC Error: execution reverted {code: -32000, message: "execution reverted"}

**Comment by an-ivannikov** [comment]
Calculate and replace PERMIT_TYPEHASH

bytes32 public constant PERMIT_TYPEHASH = 0x6e71edae12b1b97f4d1f60370fef10105fa2faae0126114a169c64845d6126c9;

**Comment by Jackie-Zhong** [comment]
> 0x6e71edae12b1b97f4d1f60370fef10105fa2faae0126114a169c64845d6126c9
i am sorry to bother you again...
could you please tell me how to calculate the PERMIT_TYPEHASH?do you have relevant tutorials or articles to refer to?

**Comment by Harsh8055git** [comment]
i am deploying on rinkeby and getting the same error, any solution

**Comment by kelvinink** [comment]
Wow, thanks dude

**Comment by isofttechn** [comment]
> **Bug Description** I am trying to understand better the uniswap logic for development. I have a problem like this, I deploy new instances of contracts and change the `UniswapV2Router02` and `UniswapV2Factory.sol` addresses in the `uniswap-interface`
> 
> After that, part of the interface does not work. In particular, when adding liquidity, Metamask issues such an error `MetaMask - RPC Error: execution reverted {code: -32000, message: "execution reverted"}`
> 
> Nothing has changed in the code, only the addresses of contracts with the same code as the original contracts.
> 
> I am developing in ropsten.
> 
> **Expected Behavior** I expect metamask to handle the contract access without any problems, since only the contract address has been changed.

I am getting exact same error.
Whenever I tried to buy my token, the rinkeby ether get taken while the while the token is not been assigned to the account.
