### ISSUE TITLE
Transactions reverted by chain reorganization still exist in Activity tab

### ISSUE THREAD

**Issue by darcher-framework** [MetaMask/metamask-extension#10120]
**Describe the bug**
The bug resides on the transaction histories shown by MetaMask in Activity tab. 
Due to the existence of chain reorganization, a mined transaction can still be reverted to pending transaction pool. 
But MetaMask is not aware of such transaction revert and the transaction still has the status "successful". 
This results in inconsistencies between what MetaMask shows to users and what the Ethereum world state really is on chain and may cause trouble to users since they see incorrect transaction histories. 

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Using private chain cluster
2. Send a transaction using MetaMask
3. Mine block such that the transaction is executed. MetaMask showing the transaction succeeds now. 
4. Make chain reorganization happen, where imported side chain does not contain the transaction.
5. The transaction will be put back to transaction pool
6. Optionally we can drop the transaction by sending another one with same nonce but higher price 
7. MetaMask still shows the transaction is successful in Activity tab. 

**Expected behavior**
When transaction is reverted due to chain reorganization, the record in Activity tab should also be updated showing the transaction is back to pending state. 

**Browser details (please complete the following information):**
 - OS: MacOS
 - Browser: Chome 87
 - MetaMask Version: 8.0.10

**Comment by Gudahtt** [comment]
We don't currently detect chain reorganizations (we have an issue tracking that feature here: https://github.com/MetaMask/eth-block-tracker/issues/30 ). As such, we can't easily know when to check whether the status of a transaction has changed. Once our block tracker supports detecting chain reorganization, we should be able to support it here in the extension as well.

In the meantime, we should at least indicate to the user somehow that we don't know for sure whether any given transaction has succeeded. I'll bring this up with the design team for consideration in future designs.
