### ISSUE TITLE
Unable to install modules due to node version conflicts

### ISSUE THREAD

**Issue by alex-miller-0** [MetaMask/metamask-extension#10138]
**Describe the bug**
I can't seem to install modules with `yarn` due to two different dependencies requiring conflicting versions of node to install.

**Steps to reproduce (REQUIRED)**

I am using the current tip of `develop`: `47fd9bf45d77572cc697ce1a48bfb9675b37e4fc`

When using node `10.18.1`:

```
[3/5] 🚚  Fetching packages...
error orbit-db-store@3.5.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.18.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Switching to node `12.14.1`:

```
[1/5] 🔍  Validating package.json...
error metamask-crx@0.0.0: The engine "node" is incompatible with this module. Expected version "^10.18.1". Got "12.14.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I can remove the engine restriction in `package.json` and switch to `"node": "^12.14.1"`, but trying to install with node 12 still fails due to a different dependency:

```
[3/5] 🚚  Fetching packages...
error sesify@4.2.2: The engine "node" is incompatible with this module. Expected version "^10.15.1". Got "12.14.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Expected behavior**

`yarn` should successfully install node modules.

**Comment by alex-miller-0** [comment]
Seems something was cached on my system. It is working now. Sorry about that.

**Comment by Sentrycs** [comment]
I am having exactly the same problem. I did run yarn cache clean, but no success. Any suggestions?

**Comment by alex-miller-0** [comment]
@Sentrycs I'm pretty sure I had to re-clone the repo, unfortunately.

**Comment by Sentrycs** [comment]
@alex-miller-0 What OS did you use?

**Comment by alex-miller-0** [comment]
Mac OS (Catalina)
