### ISSUE TITLE
Getting logs in mobile metamask

### ISSUE THREAD

**Issue by kottackalsulvin** [MetaMask/metamask-extension#10141]
Hi,
I need to debug and test my dapp  in mobile metamask browser. I already sync metamask wallet in mobile using metamask extention. 

How can I get the console log in mobile metamask browser because my mobile metamask is forcefully shutting down while am using ipfs in dapp?

**Comment by Gudahtt** [comment]
I'd recommend asking this question on the Developer Questions section of our community forum. I'm not sure how best to answer this question; this repository is for the MetaMask browser extension, not the mobile app.
