### ISSUE TITLE
Add "account details" to hamburger menu in asset view

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10148]
Given I am on the assets page/view
When I click on the hamburger menu
Then I want to see the 'Account detail" link as one of the options
So that I can send funds to that account

NOTE: on ETH assets view add hamburger menu, include "View on Etherscan" and "Account details" links

**Comment by BboyAkers** [comment]
I can take this one! 🙂

**Comment by danjm** [comment]
Let's break this one into two tasks (and perhaps resolve in two PRs):
 
- [ ] Add the "Account Detail" link to the hamburger menu on the tokens page
- [ ] Add the hamburger menu to the ETH token page with the two items as noted above

**Comment by danjm** [comment]
**For the "Add the "Account Detail" link to the hamburger menu on the tokens page" task:**

Currently, when on the main asset view, there is a "Account Details" option available in the hamburger menu. However, when on 
a token specific view, that is not in the menu. This is shown here:


https://user-images.githubusercontent.com/7499938/116116815-21f5e380-a696-11eb-8782-dee7f246c8d2.mp4

This task is to ensure the "Account Details" option, as it appears in the menu on the main asset screen, also appears in the menu when in a token specific view.

The code that adds this to the main asset screen menu is on line 81 of `metamask-extension/ui/app/components/app/menu-bar/account-options-menu.js`

The code responsible for the items in the menu on the token specific view are the `Menu` and `MenuItem` components of `metamask-extension/ui/app/pages/asset/components/token-options.js`

**Comment by danjm** [comment]
To test this manually, you will need tokens on a test net. Here is an easy way to get such tokens:

(1) [Import the metamask testing seed phrase](https://metamask.zendesk.com/hc/en-us/articles/360015289612-How-to-restore-your-MetaMask-account-from-seed-phrase): `phrase upgrade clock rough situate wedding elder clever doctor stamp excess tent`
(2) Switch to the Ropsten Test Network
(3) Click the "hamburger"/"meatbal" menu and click "View on Etherscan"
(4) On etherscan, open the token list of the account, select a token, and then copy its address
(5) Use the "Add token" functionality of MetaMask to add the token whose address you've just copied to MetaMask

Steps 2-5 are shown in this video:


https://user-images.githubusercontent.com/7499938/116118419-db08ed80-a697-11eb-973e-f2a3d67148f1.mp4

**Comment by adonesky1** [comment]
@danjm, forgive me if this is a bit naive but for the eth page menu, where should the user land when they click 'View on Etherscan'? etherscan.io/txs?
