### ISSUE TITLE
Add instructions on how to pin MetaMask to browser after onboarding

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10144]
Given... I'm on a Chromium browser
When.. I finish onboarding
Then... I want to view a screen with instruction on how to pin MetaMask to my browser bar

Design: https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=1525%3A15800

**Comment by RasenGUY** [comment]
it sais file not found

**Comment by brad-decker** [comment]
This work is complete, if not live it will be soon.
