### ISSUE TITLE
Loading Tokens...

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [MetaMask/metamask-extension#10153]
I don't know if this was caused by a Firefox nightly update, but the extensions seems to be having problems loading tokens when I add them.

 Go to "add Tokens" type "USDC" confirm.
Now the main tab will just show "Loading Tokens..."

ff 85.0b3 (64-bit)

**Comment by brad-decker** [comment]
@hp8wvvvgnj6asjm7 thanks for the report, could you let us know what version of the extension you're currently using?

**Comment by tmashuang** [comment]
This is fixed with the recent change in how we managed allowing urls in our network calls. On a side note this behavior was introduced in Firefox versions >85, on version <84 this should be fine.
