### ISSUE TITLE
Hide tokens with 0 balance

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10165]
As someone who sold all of a token, I'd like my tokens with 0 balances to be auto-hidden, so that they don't clutter my view.

**description**

after a token's entire balance is emptied, that token has a 0 balance but is still being shown in the user's wallet by default. Instead, the tokens with 0 balances should be removed from the list until they have a balance again.

**Comment by Gudahtt** [comment]
This sounds like it could be confusing as well, if a token disappears unexpectedly.
