### ISSUE TITLE
Incorrect Rounding Down of Balance

### ISSUE THREAD

**Issue by jmahlers** [MetaMask/metamask-extension#10167]
**Describe the bug**
0.0048 WBTC is rounded to 0.004 WBTC in the display. This is a non-trivial difference. The extension also displays $161.29 USD rather than the actual ~$190 ish that the correct amount converts to. So it is using the incorrectly rounded number during the conversion.

It is both rounding incorrectly (rounding to 0.004 rather than 0.005) but also with way too few decimal points. From what I can tell if you add a WBTC contract address as a custom token, it should use 8 decimal places. The 0.0008 WBTC rounding error is roughly $30.

**Steps to reproduce (REQUIRED)**

Transfer some amount of WBTC (or presumably other currencies), see incorrect rounding in extension on main page and when you click on the token details.
Verify that the actual amount differs from this.

**Expected behavior**
Either allow the user to pick the decimal place to round at or at least round at enough decimal places that the displayed error doesn't matter.

**Screenshots**
![image](https://user-images.githubusercontent.com/49463671/104082375-55058b80-51fb-11eb-997d-d4cde9989fa6.png)
If you manually lookup the address on etherscan or attempt a transaction and hit max, the correct amount is shown.
![image](https://user-images.githubusercontent.com/49463671/104082396-7797a480-51fb-11eb-826e-685786fc8abb.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Wallet: Metamask
 - Browser: Version 87.0.4280.88 (Official Build) (64-bit)
 - MetaMask Version: Recently installed MetaMask, I am on 8.1.11.

**Additional context (Error Messages, etc.)**
At one point there was a "There was a problem with your balance" message here but it disappeared.
![image](https://user-images.githubusercontent.com/49463671/104082512-63a07280-51fc-11eb-92c2-1151d7dffe71.png)

On mobile, the bug is not present. Instead, the total is displayed as 0.00479 WBTC with a correctly calculated USD amount also

**Comment by Gudahtt** [comment]
Related: #8884 #10167 #5180 #9932
