### ISSUE TITLE
Wrong balance and getGasPrice for custom networks

### ISSUE THREAD

**Issue by helderjnpinto** [MetaMask/metamask-extension#10177]
**Describe the bug**
Wrong balance in local testnet and also getGasPrice is the not as json rpc.
referent with issue #7263 [https://github.com/MetaMask/metamask-extension/issues/7263](issue 7263)

**Steps to reproduce (REQUIRED)**
Running Besu client with some accounts with balance, connect to local network

**Expected behavior**
Get right balance
Get right gas price for custom networks by using jsonrpc

**Screenshots**

Get Balance
![image](https://user-images.githubusercontent.com/12281088/104308248-46072d80-54c8-11eb-927f-f67358938bbe.png)

Get gasPrice
![image](https://user-images.githubusercontent.com/12281088/104308854-30dece80-54c9-11eb-83d2-227743147db3.png)

**Browser details (please complete the following information):**
 - Ubuntu 20
 - Browser: Version 87.0.4280.141 (Official Build) (64-bit)
 - MetaMask Version: [8.1.11]

**Comment by Gudahtt** [comment]
Thanks for the report! This is a dupliucate of #10003; I'd suggest following that issue for further updates.

**Comment by helderjnpinto** [comment]
@Gudahtt Hi this problem persists after merge of issue #10003 you can test with our Hyperledger Besu fork in public mint Here is the rpc: https://rpc.tst.publicmint.io:8545/

**Comment by helderjnpinto** [comment]
![image](https://user-images.githubusercontent.com/12281088/110307081-706ff580-7ff6-11eb-93e9-1e6bdd28dd24.png)

**Comment by Gudahtt** [comment]
Thanks @helderjnpinto; I'll re-open this. The original issue reported _two_ problems, the one we fixed was related to gas price. I'm not aware of any recent changes to how balance is queried.

Could you share additional details? In particular, it'd be great to know the network settings (Settings -> Networks -> PublicMint-TST).

**Comment by helderjnpinto** [comment]
@Gudahtt here is the network settings: 
- Name: PublicMint Testing network
- RPC: https://rpc.tst.publicmint.io:8545/
- ChainID: 2019
- Symbol: USD
- Explorer: https://explorer.tst.publicmint.io/

Correct eth_getBalance
```
curl --location --request POST 'https://rpc.tst.publicmint.io:8545/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getBalance",
    "params": [
        "0x8717eD44cEB53f15dB9CF1bEc75a037A70232AC8",
        "latest"
    ],
    "id": 1
}'
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : "899950000000000000000"
}%   

Explorer balance: https://explorer.tst.publicmint.io/address/0x8717eD44cEB53f15dB9CF1bEc75a037A70232AC8/transactions


```

**Comment by helderjnpinto** [comment]
@Gudahtt I found wrong value give-me 96716388000000000000 i'm try to find here is this source. 

But this balance is em WEI and not have convertion rate. 
PublicMint treats ETH units as if it were a USD ERC20 with 18 decimal places or like normal Ethereum balance.
Just need to show ETH balance like in ethereum mainnet but with Label USD / MINT.

Also is not hex value, so resuming: 

- is not hex, is WEI units.
- not have convertion rate
- value = "96716388000000000000" is wrong needs to be "899950000000000000000"

Here is the printscreen of debug in chrome.

![12cbc70a0e0740d9b2f1bd219237911a](https://user-images.githubusercontent.com/12281088/110354969-a500a300-8030-11eb-9343-d699a5f6deb3.png)

**Comment by helderjnpinto** [comment]
@Gudahtt sorry for this issue i investigated more and maybe is only my fork of besu, https://besu.hyperledger.org/en/1.4.4/Reference/API-Methods/#eth_getbalance in documentation needs to respond a hex value not WEI value.

Thanks for reopening this case i will close.
