### ISSUE TITLE
Mitigate CSS transition lag Chromium bug on macOS external monitors

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#10173]
There is a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=971701) that causes extreme lag in CSS transitions on external monitors on macOS. There don't seem to be any great workarounds, other than manually forcing the page to re-draw on an interval or avoiding CSS transitions altogether.

This issue is meant to consolidate efforts to mitigate or workaround this issue, since it has been brought up many times as different symptoms have been reported. I'll mark it as "blocked" for now, unless someone comes up with a viable mitigation at least.

Related issues:
* #8324
* #10202

**Comment by igorbarbashin** [comment]
I've solved it in Dapper waller like this:
Add an empty div in the root of the component tree and add the following css:

```
.emptySpinningDiv {
    position: fixed;
    top: 0;
    right: 0;
    width: 1px;
    height: 1px;
    background-color: hsla(0,0%,100%,.01);
    -webkit-animation-name: m1gXI_NeUKew7DjKnCm2u;
    animation-name: m1gXI_NeUKew7DjKnCm2u;
    -webkit-animation-duration: 2s;
    animation-duration: 2s;
    -webkit-animation-iteration-count: infinite;
    animation-iteration-count: infinite;
    -webkit-animation-timing-function: linear;
    animation-timing-function: linear;
}
```

It creates and empty invisible spinning div that forces chrome to keep refreshing the screen.

I can add a pull-request, but let me know if you prefer a different way to fix it

**Comment by Gudahtt** [comment]
Thanks for the suggestion @igorbarbashin, that sounds promising! Please feel free to submit that as a PR if you're willing.

**Comment by igorbarbashin** [comment]
I'll add it as a pseudo-element to the `.app` class, so we don't have to add to the html

**Comment by igorbarbashin** [comment]
The fix is ready. @Gudahtt will you add me as a contributor so I could push the branch, or should I fork and PR?

**Comment by Gudahtt** [comment]
Fork and PR would be great!

**Comment by dan437** [comment]
I've gotten the same issue. When I move my Chrome browser to my notebook's screen, it's suddenly very fast.

**Comment by igorbarbashin** [comment]
@Gudahtt the fix is ready
https://github.com/MetaMask/metamask-extension/pull/10724

**Comment by RED29** [comment]
same issue, searching for couple hours, but eventually found this by searching on "lag". Its indeed very slow om external display and instant on the main screen.

**Comment by RED29** [comment]
@Gudahtt and @igorbarbashin  thanks for writing this down!
