### ISSUE TITLE
EnsIpfsResolver - the resolver for name "....eth" is not standard

### ISSUE THREAD

**Issue by gpersoon** [MetaMask/metamask-extension#10185]
**Describe the bug**
Resolving an ENS name in the Metamask address bar shows a misleading error message internally, this might make troubleshooting more difficult.

**Steps to reproduce (REQUIRED)**
Select mainnet in metamask
Enter notpresent.eth/  in the address bar   (note, this is a random name that isn't registered on ENS)
Check the developer console of the background page
The developer console shows the error:
```js
initSentry.js:8 Error: EnsIpfsResolver - the resolver for name "notpresent.eth" is not standard, it should either supports contenthash() or content()
  at r.default (background.js:1)
  at async a.includes.tabId (background.js:1)
```

**Expected behavior**
I would have expected the following error:
```JS
EnsIpfsResolver - no resolver found for name "notpresent.eth"
```

**Screenshots**
-

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Version 87.0.4280.141 (Official Build) (64-bit)
 - MetaMask Version: 8.1.11

**Additional context (Error Messages, etc.)**
Looking at the source & checking with debugger:
https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/ens-ipfs/resolver.js#L24
```JS
 const resolverAddress = resolverLookupResult[0]
  if (hexValueIsEmpty(resolverAddress)) {
    throw new Error(`EnsIpfsResolver - no resolver found for name "${name}"`)
  }
```
The value of resolverAddress:
```JS
resolverAddress = "0x0000000000000000000000000000000000000000"
```

However the function hexValueIsEmpty doesn't match for this value
https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/ens-ipfs/resolver.js#L61
```JS
function hexValueIsEmpty(value) {
  return [
    undefined,
    null,
    '0x',
    '0x0',
    '0x0000000000000000000000000000000000000000000000000000000000000000',
  ].includes(value)
}
```

**Comment by Gudahtt** [comment]
I was able to reproduce this on production on both Chrome and Firefox.
