### ISSUE TITLE
'Show Hex Data' field ignored for token sends

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#10194]
**Describe the bug**
If the "Show Hex Data" advanced setting is enabled, the "Hex data" field will still appear in the token send flow but it will be completely ineffectual. Any contents submitted will not appear in the final transaction data.

**Steps to reproduce (REQUIRED)**

1. Enable "Show Hex Data" in the advanced settings
2. Initiate a token send
3. Enter anything in the "Hex data" field
4. See that on the confirmation page, in the 'Data' tab, the hex data entered will not be shown.

**Expected behavior**
The "Hex data" field should not be shown for token sends. The data sent with a token send needs to reflect the operation taking place.

I'm not sure whether arbitrary data can be added to a token send without breaking it, but if it can, then that would be an OK solution too.

**Comment by hmalik88** [comment]
Hi @Gudahtt , I'm having trouble reproducing this issue. I enabled hex data and was able to add data to the field and be able to see it on the confirmation page (etherscan also confirmed that the data was sent). Can you please advise if I'm missing a step or am misunderstanding the issue?
