### ISSUE TITLE
Metamask Extension stopped fully implementing EventEmitter API

### ISSUE THREAD

**Issue by StanislavBreadless** [MetaMask/metamask-extension#10196]
Up until recently everything was fine, but MetaMask Firefox extension stopped supporting `.off` function. (`window.ethereum.off` is equal to `undefined`), despite the fact that:

- The method used to be supported.
- The [metamask docs](https://docs.metamask.io/guide/ethereum-provider.html#events) says the provider supports `EventEmitter` API which [does](https://nodejs.org/dist/latest-v14.x/docs/api/events.html#events_emitter_off_eventname_listener) support the functionality. 

**Steps to reproduce (REQUIRED)**

1. Open any dapp in your browser, e.g. [https://uniswap.org/](https://uniswap.org/).
2. Open developer console.
3. Type in `ethereum.on`, it returns some function. Type-in `ethereum.off`, it returns undefined.

**Expected behavior**
`ethereum.off` should be as specified in the `EventEmitter` API

**Screenshots**
![image](https://user-images.githubusercontent.com/52464764/104748331-46b6f280-575a-11eb-82de-42aeeca0d023.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox, 84.0.2 (64-bit).
 - MetaMask Version: 9.0.1

**Comment by Gudahtt** [comment]
Thanks for the report! I was able to reproduce this problem as well.

**Comment by joekim** [comment]
Is there a work-around for cleaning up the event emitter?

**Comment by Gudahtt** [comment]
Yep! The workaround is to call `removeListener` to remove specific listeners, or to call `removeAllListeners` to remove all of them.

**Comment by vandan** [comment]
Need to determine which version of EventEmitter (and update documentation link for that specific version) OR upgrade to a more recent version and add the link for that specific version as well (**not** the generic link https://nodejs.org/api/events.html)
