### ISSUE TITLE
UI lags popup mode

### ISSUE THREAD

**Issue by kevinho** [MetaMask/metamask-extension#10202]
**Describe the bug**

When using the chrome extension in popup mode, the UI  freezes. When I try to input something, the UI is not refresh until about 3s latter.

When I use extension in expand mode, it's all OK.

**Steps to reproduce (REQUIRED)**
1. Open chrome,
2. Click metamask icon on topright, to bring up the panel.
3. Input  number in text field
4. UI lags

**Expected behavior**
smooth, instant response

**Screenshots**
![out](https://user-images.githubusercontent.com/546824/104810179-1a6ca600-582e-11eb-970e-c88f268290ed.gif)

**Browser details (please complete the following information):**
 - OS: OSX 10.15.7
 - Browser: Chrome Version 87.0.4280.141 (Official Build) (64-bit)
 - MetaMask Version:8.1.11

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment]
Thanks for the report! This sounds like a known bug that affects Chrome on macOS when using an external monitor. We don't have a workaround right now, so I'd suggest either moving the window to the primary monitor or using a different browser. See here for details: #10173. Also please feel free to star [the issue on the Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=971701), so they are further incentivized to fix it! Our hands are tied until this is addressed by them unfortunately.

Let me know if the problems persist on the primary monitor, in case I've misidentified this.
