### ISSUE TITLE
Opera extension has stopped work.

### ISSUE THREAD

**Issue by nem1131** [MetaMask/metamask-extension#10205]
Hello! A few days ago my metamask extension in opera browser has stopped working and still doesn't work. It is very early version 3.14.1. unfortunately i have no seed phrase, so it is very important for me to know if this version has stopped working forever. And is there a way to get the seed phrase without connection to network? For now the extension is trying to connect to main ethereum network or another network that i can choose forever. I have the same extension on another pc and it has the same problem, so the issue is not connected with pc or network. Also i have another metamask account in chrome browser and it works normally. Thank you for help.

**Comment by Gudahtt** [comment]
Unfortunately that version uses an Infura API endpoint that has been deprecated for years, and they finally took it offline recently. We have no way to restore functionality.

I'd suggest you contact support here: https://metamask.zendesk.com/hc/en-us/requests/new. They may be able to help you restore your seed phrase from disk, using [this guide](https://metamask.zendesk.com/hc/en-us/articles/360018766351). Though no promises - we don't officially support Opera, nor to we guarantee the ability to restore from disk. The only safe way to use MetaMask is to backup your seed phrase, so please make sure to do that in the future! In the meantime, hopefully support is able to help you.

**Comment by nem1131** [comment]
> Unfortunately that version uses an Infura API endpoint that has been deprecated for years, and they finally took it offline recently. We have no way to restore functionality.
> 
> I'd suggest you contact support here: https://metamask.zendesk.com/hc/en-us/requests/new. They may be able to help you restore your seed phrase from disk, using [this guide](https://metamask.zendesk.com/hc/en-us/articles/360018766351). Though no promises - we don't officially support Opera, nor to we guarantee the ability to restore from disk. The only safe way to use MetaMask is to backup your seed phrase, so please make sure to do that in the future! In the meantime, hopefully support is able to help you.

Could you please help me to restore seed phrase from disk? I found the '0000003.txt' file in extension folder but there is no word 'vault' in this file. and when i'm trying to enter command

 'chrome.storage.local.get('data', result => {
 var vault = result.data.KeyringController.vault
 console.log(vault)
})'

  to console in browser i get 

'Error handling response: TypeError: Cannot read property 'KeyringController' of undefined
    at <anonymous>:2:29'

message.

**Comment by nem1131** [comment]
> Unfortunately that version uses an Infura API endpoint that has been deprecated for years, and they finally took it offline recently. We have no way to restore functionality.
> 
> I'd suggest you contact support here: https://metamask.zendesk.com/hc/en-us/requests/new. They may be able to help you restore your seed phrase from disk, using [this guide](https://metamask.zendesk.com/hc/en-us/articles/360018766351). Though no promises - we don't officially support Opera, nor to we guarantee the ability to restore from disk. The only safe way to use MetaMask is to backup your seed phrase, so please make sure to do that in the future! In the meantime, hopefully support is able to help you.

Thank you very much for your help! I redtored the seed phrase from the disk while support don't tell me about that opportunity.

**Comment by Entitie** [comment]
Hello, nem1131. I faced the same problem. What method did you use? In which files did you look for the information you needed?
