### ISSUE TITLE
web3.js: Promise not resolving on second transaction in sequence in v9.0.1

### ISSUE THREAD

**Issue by bocai-h** [MetaMask/metamask-extension#10216]
Promise not resolving on second transaction in sequence in v9.0.1, but in 8.1.11, it worked will.

I have a sequence of two contract calls (one to approve transfer of tokens, one to collect those tokens) which I'd like to present to the user in order. I'm able to display and confirm both; however, the promise associated with the second call never resolves, even though the transaction completes, so the application is unable to handle the results of these calls.

If I wait long enough "Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!" appears on console. Note that this error is incorrect: The transaction has been mined by that point, and I can see that this is the case in MetaMask.

**Comment by abdulsamijay** [comment]
I have been facing a similar issue on v9.0.1. I try to initiate a transaction using metamask but it takes forever to return a hash. This is not a problem on v8.1.11. The application is unable to handle the results.

**Comment by DanialAnsari** [comment]
Hi I am block chain developer and am facing the same issue. Here @bocai-h is stating problem on the second transaction however I am facing this problem in all kinds of transaction which requires some sort of action upon it's execution. For e.g in one my dapps when transaction is initiated we start a loader which needs to be stopped once the transaction has been confirmed but for some reason in the new metamask version the action we perform on confirmation is being executed. Also when we open metamask  in our dapp we get a warning  stating window.web3 api has been removed.

**Comment by Gudahtt** [comment]
Thanks for the report! What browser are you using (including version)? How are you initiating these transactions? I did try initiating an approve call and a transfer at the same time, and I didn't experience the same problem (the second transaction did resolve correctly). Could you try to provide a minimal example?

>Also when we open metamask in our dapp we get a warning stating window.web3 api has been removed.

v9 included the removal of our injected `web3` instance. You'll have to start bringing in your own convenience library from here on out. Please read [our migration guide](https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3) for further details.

**Comment by jacksonng77** [comment]
I wish to confirm this. Promises are not resolving, and events that are watched are also not firing. My browser is Chrome.

I also noted that even if I installed the legacy browser along with v9.0.1, events are still not firing.

**Comment by sidlovskyy** [comment]
I also can confirm this. Seems like even Uniswap is not working with 9.0.1

**Comment by rekmarks** [comment]
Can someone please share a relevant snippet of code that used to work but does not work any longer?

**Comment by jacksonng77** [comment]
> Can someone please share a relevant snippet of code that used to work but does not work any longer?

_Here you are. Other than 'transactionhash', none of the rest fires anymore._

SomeContract.methods.someCalls(x).send({
  from: accountaddress,
  value: $("#price").val()*1000000000000000000,
  gasPrice: web3.eth.gasPrice       	    
})
.on('transactionHash', (hash) => {
   console.log("a");
})
.on('receipt', (receipt) => {
   console.log("b");
})
.on('confirmation', (confirmationNumber, receipt) => {
  console.log("c");
})
.on('error', console.error);

**Comment by rekmarks** [comment]
Thank you, @jacksonng77! I see that you're using `web3.js`. I will refer you to my comment from #10215:

> The events you are trying to listen for depend on subscriptions via the `eth_subscribe` JSON-RPC method, which are currently broken in `web3@1.x`. It's up to `web3` to fix this problem, which we notified them of this past July. Please see this issue for details: https://github.com/ChainSafe/web3.js/issues/3651

Is anyone _not_ using `web3.js`?

**Comment by jacksonng77** [comment]
> Thank you, @jacksonng77! I see that you're using `web3.js`. I will refer you to my comment from #10215:
> 
> > The events you are trying to listen for depend on subscriptions via the `eth_subscribe` JSON-RPC method, which are currently broken in `web3@1.x`. It's up to `web3` to fix this problem, which we notified them of this past July. Please see this issue for details: [ChainSafe/web3.js#3651](https://github.com/ChainSafe/web3.js/issues/3651)
> 
> Is anyone _not_ using `web3.js`?

I am embarrassed to say this, but I am if that helps, this is an old piece of code that stopped function, and it uses web3.js@1.0.0-beta.34.

**Comment by rekmarks** [comment]
> I am embarrassed to say this, but I am if that helps, this is an old piece of code that stopped function, and it uses web3.js@1.0.0-beta.34.

No worries @jacksonng77. The problem unfortunately persists in the latest `1.x` version (`web3@1.3.1`), so given your use of `1.0.0-betaX`, we can assume that all version of `web3@1.x` are affected by this issue.

**Comment by sidlovskyy** [comment]
> Thank you, @jacksonng77! I see that you're using `web3.js`. I will refer you to my comment from #10215:
> 
> > The events you are trying to listen for depend on subscriptions via the `eth_subscribe` JSON-RPC method, which are currently broken in `web3@1.x`. It's up to `web3` to fix this problem, which we notified them of this past July. Please see this issue for details: [ChainSafe/web3.js#3651](https://github.com/ChainSafe/web3.js/issues/3651)
> 
> Is anyone _not_ using `web3.js`?

I believe most of the projects use web3.js which means they stop working well for the latest metamask. As I mentioned it's not working on UniSwap. We are using the latest web3. I think there will be a lot of issues with this.

**Comment by rekmarks** [comment]
I agree, @sidlovskyy, which is why we notified `web3.js` about this issue half a year ago. When we learned yesterday that they hadn't fixed it, I opened [a PR](https://github.com/ChainSafe/web3.js/pull/3864) that should resolve it for them.

At the end of the day, we are responsible for being compatible with [the JavaScript provider specification](https://eips.ethereum.org/EIPS/eip-1193), not for maintaining `web3.js` support. If you are dissatisfied with your developer experience in this matter, you should raise your concerns on the `web3.js` repository.

Meanwhile, if you are looking for an immediate solution, I have been told by other users that they've had success using [`patch-package`](https://www.npmjs.com/package/patch-package) with the PR I linked at the beginning of this comment.

**Comment by GregTheGreek** [comment]
There was a miscommunication on our end whether this had been fixed or not, an emergency patch is being issued.

**Comment by rekmarks** [comment]
FYI: `web3.js` is pushing a new version ASAP, which you should update to as soon as it's available. That will be the best (and probably fastest) solution to the problems reported in this issue.

Nevertheless, MetaMask is pausing the rollout of v9 on Chrome until we have a patch ready that restores functionality for current users of `web3@1.x`. We'll submit that patch to extension stores today, and it will likely ship in the next few days.

**Comment by Gudahtt** [comment]
This was fixed in #10219, and will be released in v9.0.2.

**Comment by DanialAnsari** [comment]
> This was fixed in #10219, and will be released in v9.0.2.

Can you give an estimate of when can we expect this version to be released?

**Comment by rekmarks** [comment]
@DanialAnsari, v9.0.2 is live on Firefox as of ~8 hours ago, and will roll out on Chrome when they've finished reviewing it. Hopefully by the end of this week, but Monday at the latest, assuming the process proceeds normally.

**Comment by crosstec** [comment]
> This was fixed in #10219, and will be released in v9.0.2.

will we need to update web3 in our dapps or is waiting for v9.0.2 enough?

**Comment by rekmarks** [comment]
@crosstec you can just wait for 9.0.2 to fix issue, but you may be affected by our other breaking provider changes as described in #8077 and our docs (see that issue for links). As far as we know, `web3@1.x` should be fine once this is fixed, however.

We still recommend that everyone updates to `web3@1.3.2` once that ships (today, I believe).

**Comment by GregTheGreek** [comment]
Web3@1.3.2 is shipping today. The RC is going up momentarily, but we've been testing the tagged commit for the last 24 hours and all things look smooth.

**Comment by GregTheGreek** [comment]
Release-Candidate has been shipped under `npm install --save web3@1.3.1-rc.2`

Please expect the full version within the next hour or so.

**Comment by GregTheGreek** [comment]
We just shipped version `1.3.2`! 

You can install the update with npm latest tag `npm install --save web@1.3.2`

**Comment by crosstec** [comment]
anyone having a web3.min.js plus map for 1.3.2 available already? NPM keeps telling me version doesn't exist.
thx

**Comment by crosstec** [comment]
hm, still having the same issue with 1.3.2 on 9.0.1, shouldn't it fix it there, too?

**Comment by rekmarks** [comment]
@crosstec, does your site work on Firefox?

**Comment by crosstec** [comment]
> @crosstec, does your site work on Firefox?

yes

**Comment by GregTheGreek** [comment]
Are you using the lastest build on npm or from the `./dist/` directory on github?

**Comment by crosstec** [comment]
> Are you using the lastest build on npm or from the `./dist/` directory on github?

using from /dist/, the version at jsdelivr

**Comment by GregTheGreek** [comment]
Are you using the jsdeliver from npm or github?

**Comment by mdtanrikulu** [comment]
> We just shipped version `1.3.2`!
> 
> You can install the update with npm latest tag `npm install --save web@1.3.2`

little typo fix `npm install --save web3@1.3.2` or `yarn add web3@1.3.2` for yarn fans.

**Comment by crosstec** [comment]
> Are you using the jsdeliver from npm or github?

This one (don't need it for node, just for client inclusion):
https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.3.2/dist/

**Comment by GregTheGreek** [comment]
ok thank you!

We are pulling 1.3.2 and re-releasing it under 1.3.3, with no changes except for the `./dist` folder is updated. NPM installs currently work, only if you are using requiring `./dist` you'd run into this problem.

**Comment by GregTheGreek** [comment]
We have just release `v1.3.3` which addresses the out-dated `dist` folder.

**Comment by rekmarks** [comment]
MetaMask `9.0.3` is now live on Chrome and Firefox. (`9.0.2` was briefly live on both stores, but we shipped another patch for an unrelated issue.) With that, this issue is now resolved on our end, as well as `web3.js`'s.

We still recommend that everyone updates to `web3@^1.3.3` ASAP. We may remove the deprecated event that it listens to at some point in the future.

Thank you to all for your patience and assistance in resolving this matter. Thanks to @GregTheGreek and ChainSafe for being great communicators throughout. Enjoy the bull market responsibly this weekend! 🚀

**Comment by GregTheGreek** [comment]
Beers all around 🥰

**Comment by crosstec** [comment]
> ok thank you!
> 
> We are pulling 1.3.2 and re-releasing it under 1.3.3, with no changes except for the `./dist` folder is updated. NPM installs currently work, only if you are using requiring `./dist` you'd run into this problem.

thank you, works with MM 9.0.3 and 1.3.3 now smoothly
