### ISSUE TITLE
Replacement Transaction Underpriced

### ISSUE THREAD

**Issue by frankgvos** [MetaMask/metamask-extension#10210]
I am not able to get test ethers from Ropsten faucet. It either shows some error or the transaction hash is not available on ropsten etherscan.

**Steps to reproduce (REQUIRED)**

1. Go to metamask extension
2. Click on buy and then click on add ethers from faucet
3. If the screen gives a TxHash, then it is not available on etherscan. If no TxHash is shown, then It gives "Replacement Transaction Underpriced" error

**Expected behavior**
Test ethers should have been credited to account.

**Screenshots**
![Screenshot from 2021-01-19 08-56-20](https://user-images.githubusercontent.com/77089409/104984484-c849a180-5a34-11eb-85ee-fe5b27cbd728.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Brave Browser Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)
 - MetaMask Version: v8.1.11

**Additional context (Error Messages, etc.)**
I have tried resetting my account and even reinstalled the metamask extension. But none of the methods work.

**Comment by tmashuang** [comment]
Seems that the faucet account could be potentially out of sync with the nonce, which is generally what the `replacement transaction underpriced` error signifies. Regardless issues should be migrated over to https://github.com/MetaMask/eth-faucet/ since that is where the site repository is.

**Comment by tmashuang** [comment]
I've opened the issue on the appropriate repository, https://github.com/MetaMask/eth-faucet/issues/26. Closing.
