### ISSUE TITLE
Yarn Dist bug

### ISSUE THREAD

**Issue by Sentrycs** [MetaMask/metamask-extension#10217]
![Screenshot 2021-01-20 150442](https://user-images.githubusercontent.com/42841002/105179094-894d4600-5b31-11eb-8ad2-3e63e7d014a7.jpg)
OS=Windows 10
Node 10.16.0
Yarn 1.22.10

**Comment by Gudahtt** [comment]
Could you please post on the [Developer Questions topic of our Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics/360001751291-Developer-Questions) instead? As mentioned in [the last issue you opened about this](https://github.com/MetaMask/metamask-extension/issues/10211), we'd rather use GitHub just for product bugs and enhancements.

**Comment by Sentrycs** [comment]
I've posted there two posts  2 hours ago,  but so far nobody paid attention.

**Comment by Gudahtt** [comment]
I don't see any new posts :thinking: Also you'll need to be a little more patient than that. I'm sorry but we don't have the resources to help everyone so quickly. We have _a lot_ of people contacting us asking for help.

**Comment by Sentrycs** [comment]
You do not see my post because it is pending approval:
![Uploading Screenshot 2021-01-21 083829 Metamask Support.png…]()

**Comment by Sentrycs** [comment]
And now it disappeared from your  Developer Questions topic of our Community Forum.
