### ISSUE TITLE
Add "recovery phrase" video to onboarding and update copy throughout

### ISSUE THREAD

**Issue by rachelcope** [MetaMask/metamask-extension#10244]
#Description
As a user, I want to have more education and understanding what the recovery phrase is and the risks involved

#Situation
GIVEN: I am onboarding into MetaMask
THEN: I want to be able to watch a video to understand what the recovery phrase is and the risks involved

#Acceptance Criteria
- Embed new video
- Update copy throughout the onboarding flow (as shown in figma)

[Figma designs](https://www.figma.com/file/EN7BT81mLsy0iq0rsGSa3N/Seed-phrase-security?node-id=0%3A1)

**Comment by danfinlay** [comment]
[thread with video links](https://consensys.slack.com/archives/GETEW1V4M/p1614883099150700?thread_ts=1611290013.016000&cid=GETEW1V4M)
