### ISSUE TITLE
Sorry! I tried to rebase this on `develop` to fix a conflict, and accidentally pushed `develop` directly to your fork :facepalm: And now I can't fix it because this PR auto-closed, and that means I longer have permission to push to your branch.

### ISSUE THREAD

**Issue by MrBond34** [MetaMask/metamask-extension#10245]
Sorry! I tried to rebase this on `develop` to fix a conflict, and accidentally pushed `develop` directly to your fork :facepalm: And now I can't fix it because this PR auto-closed, and that means I longer have permission to push to your branch.

Please feel free to resubmit this, and I'll do my best to find someone to review it. My apologies for the delay! We really appreciate the contribution. I've pushed up a copy of your branch here: https://github.com/MetaMask/metamask-extension/tree/update-es-es419-translations

_Originally posted by @Gudahtt in https://github.com/MetaMask/metamask-extension/issues/10073#issuecomment-765101826_

**Comment by Gudahtt** [comment]
What were you trying to communicate by creating this issue? :thinking:
