### ISSUE TITLE
Sending eth_decrypt throws "Cannot read property 'name' of undefined" error

### ISSUE THREAD

**Issue by nikdementev** [MetaMask/metamask-extension#10247]
**Describe the bug**
After upgrading metamask to version 9, the `eth_decrypt` method returns an error: `Message: Cannot read property 'name' of undefined.
`
**Steps to reproduce (REQUIRED)**

I have built a small [demo application](http://test.dementev.tech/) to demo the error, with the code published here. The implementation code is in the [App.js](https://github.com/nikdementev/issue/blob/main/src/App.js) file. 

1. **Click** to connect account
2. Enter text message.
3. **Click** encrypt message
4. **Click** decrypt message

I expected metamask to decode the message.

error message
![image](https://user-images.githubusercontent.com/17093843/105476503-c3ddec80-5cb1-11eb-82d4-2a3616bbcbf3.png)

### encrypt message

` const encryptionPublicKey = await provider.request({
      method: 'eth_getEncryptionPublicKey',
      params: [address]
    })`

`const encryptedMessage = bufferToHex(
      Buffer.from(
        JSON.stringify(
          encrypt(
            encryptionPublicKey,
            { data: message },
            'x25519-xsalsa20-poly1305'
          )
        ),
        'utf8'
      )
    );`

### decrypt message
`await provider.request({
      method: 'eth_decrypt',
      params: [encryptedMessage, address]
    })`

**Browser details (please complete the following information):**
 - OS: Mac BigSure 11.1 (20C69)
 - Browser: Version 87.0.4280.141 (Official Build) (x86_64)
 - MetaMask Version: 9.0.1

On metamask version 8, it worked, but after the update it stopped

**Comment by dan1kov** [comment]
I have the same problem

**Comment by Pasha8914** [comment]
Same trouble!(

**Comment by rstormsf** [comment]
@danfinlay @Gudahtt P1 bug, our users can't recover account in new metamask. This feature worked fine in metamask v8.1.1
Please fix it asap. (need it for tornado users)

**Comment by danfinlay** [comment]
Escalating. Users aren't able to recover accounts?

**Comment by rstormsf** [comment]
@dan1kov tornado uses encrypted onchain private key that could be decrypted with their metamask public's key.

**Comment by danfinlay** [comment]
We have a fix on the way in [version 9.0.3](https://github.com/MetaMask/metamask-extension/pull/10253/files)

**Comment by danfinlay** [comment]
You can manually install the fixed version now [on our releases page](https://github.com/MetaMask/metamask-extension/releases/tag/v9.0.3) if you need it urgently.

The fix should be live on Firefox _very soon_.
The fix will be live on Edge _at some random point we don't control_.
Chrome will be the problem: Chrome has a slow review process, and its queue does not allow us to replace queued candidates. It is likely Tornado Cash will be broken for Chrome over the weekend, and Tornado Cash users will need to use Firefox or a custom build from the above releases page until then.

[Here is a guide to adding a custom build of MetaMask to your browser](https://metamask.zendesk.com/hc/en-us/articles/360016336611-Revert-Back-to-Earlier-Version-or-Add-Custom-Build-to-Chrome)

**Comment by danfinlay** [comment]
Great news, Chrome approved incredibly fast, so it looks like this issue should be resolved for everyone except maybe Edge users already!
