### ISSUE TITLE
On connect/account select, a selected account can be not shown

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10279]
Repro:
- Have many accounts, and have a later one currently selected.
- Visit a dapp, click "connect"

Notice that no visible account is selected. The user is able to click "Agree" without seeing what they're agreeing to.

Possible fixes:
- sort any selected address to the top
- Pin the confirm button to the bottom of the scrollable area.
- Do not pre-select any accounts by default

**Comment by Gudahtt** [comment]
Closing as a duplicate. This was already added, by you! #8903
