### ISSUE TITLE
Speed Up and Cancel buttons disappear after cancelled

### ISSUE THREAD

**Issue by 0xmichalis** [MetaMask/metamask-extension#10277]
**Describe the bug**
The Speed Up and Cancel buttons for an in-flight transaction are disappearing from Metamask after they are cancelled for a transaction.

**Steps to reproduce (REQUIRED)**

1. Speed Up an in-flight transaction
2. Click Cancel in Trezor page that asks user to Proceed to sign the new transaction
3. Speed Up button is not showing up in Metamask anymore

**Expected behavior**
Speed Up button shows up in the in-flight transaction even if the action to speed up the transaction has been cancelled in the past.

**Browser details (please complete the following information):**
 - OS: Linux
 - Hardware Wallet: Trezor (firmware version 1.9.3)
 - Browser: Firefox 84.0.2 (64-bit)
 - MetaMask Version: 9.0.3

**Comment by tmashuang** [comment]
Related to #9053

**Comment by danfinlay** [comment]
Closing as a duplicate of #9053

**Comment by danjm** [comment]
Not sure that this is a strict duplicate of an existing issue. Probably related to https://github.com/MetaMask/metamask-extension/issues/10512 and the explanation provided in https://github.com/MetaMask/metamask-extension/issues/10512#issuecomment-785287919

The case of disappearing buttons here could be specifically related to hardware wallet usage
