### ISSUE TITLE
Faulty description of TX after replacing

### ISSUE THREAD

**Issue by llllllffffff** [MetaMask/metamask-extension#10275]
**Describe the bug**
I had one TX pending, changed it into a completely different via nonces but in the activity tab it resembles the first one.

**Steps to reproduce (REQUIRED)**

1. Approve TX with low gas fee
2. replace this TX with same nonce
3. after confirmation, click 'activity' tab
4. shows description of initial TX

**Expected behavior**
Display what actually happended in the TX.

**Screenshots**
--Activity tab--
![image](https://user-images.githubusercontent.com/77065337/105619074-3f918380-5def-11eb-8e7c-17a618e7d53e.png)
--first TX--
![image](https://user-images.githubusercontent.com/77065337/105619161-3fde4e80-5df0-11eb-8aad-460816d10582.png)
--Etherscan of TX--
![image](https://user-images.githubusercontent.com/77065337/105619143-14f3fa80-5df0-11eb-9564-4f0d62f8be99.png)

**Browser details (please complete the following information):**
 - Windows 10, 20H2
 - Brave V1.19.86

**Comment by Gudahtt** [comment]
Related to #9053
