### ISSUE TITLE
Added tokens got removed automatically in Chrome Extension 

### ISSUE THREAD

**Issue by chetanyachopra** [MetaMask/metamask-extension#10280]
subject: Tokens other than ETH are removed auto ... i need to add them manually after some time in chrome Extension.

Issue: 
After every 3-4 days more tokens other thanETH are removed auto .. i need to add them manually everytime although amount of them i hold is there but it's just that i need to add them manually everytime to view the details

Browser details
 - OS: Windows
 - Browser: Chrome Version 87.0.4280.141 (Official Build) (64-bit)
 - MetaMask Version: 9.0.3

**Comment by Gudahtt** [comment]
Thanks for the report! Unfortunately I was unable to reproduce this - I am not seeing this behaviour locally.

Can you share more details about this behaviour? e.g. are you using an imported account or a hardware wallet account? What are the tokens that keep disappearing, and do you have a non-zero balance?

I'd encourage you to [submit a support request](https://metamask.zendesk.com/hc/en-us/requests/new) with state logs as well - that would greatly help with our efforts to investigate this problem.
