### ISSUE TITLE
Ungoogled chromium - the list of additional tokens can't load - "loading tokens" msg all the time. 

### ISSUE THREAD

**Issue by testoviron33** [MetaMask/metamask-extension#10282]
In ungoogled chromium the list on metamask shows only the main ETH token and not any other, and there is also the info on the list that the list is loading, but it's forever like that.
I don't know if you know and if that might have to do with this problem, but in order to add a extension to ungoogled chromium, the .crx file needs to be downloaded and dropped on the extension tab and installed this way.
Beside that, all functionality seems to be working fine.
I noticed this problems some weeks ago.

Win 8.1 64bit
Metamask 9.0.3
(ungoogled) Chromium 87.0.4280.67 (64bit)

**Comment by Gudahtt** [comment]
Thanks for the report! It sounds like it's having trouble connecting to Infura. There are a few different things that could cause that. You might learn more by checking the console logs of the `background` process of the extension.

>I don't know if you know and if that might have to do with this problem, but in order to add a extension to ungoogled chromium, the .crx file needs to be downloaded and dropped on the extension tab and installed this way.

Where are you getting the `.crx` file that you're installing this way?

**Comment by testoviron33** [comment]
My deep apologies for late response.
The .crx is obviously both from official chrome store.

This is the console err:
`initSentry.js:1 Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN
initSentry.js:8 Removing intrinsics.Promise.any
initSentry.js:8 Removing intrinsics.Reflect.@@toStringTag
initSentry.js:8 Removing intrinsics.%StringPrototype%.replaceAll
initSentry.js:8 Translator - Unable to find value of key "assets" for locale "pl"
(anonymous) @ initSentry.js:8
initSentry.js:8 Translator - Unable to find value of key "activity" for locale "pl"
(anonymous) @ initSentry.js:8
initSentry.js:8 Translator - Unable to find value of key "buy" for locale "pl"
(anonymous) @ initSentry.js:8
initSentry.js:8 Translator - Unable to find value of key "swap" for locale "pl"
(anonymous) @ initSentry.js:8
initSentry.js:8 Translator - Unable to find value of key "onlyAvailableOnMainnet" for locale "pl"
(anonymous) @ initSentry.js:8
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/ui-libs.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/initSentry.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/ui.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
`

**Comment by Gudahtt** [comment]
>The .crx is obviously both from official chrome store.

Ah good! I was worried there for a second :sweat_smile:. Lots of phishers out there with fake extensions.

Thanks for the console logs! Unfortunately none of those are useful in this case - these are all normal log messages. It looks like these are from one of the MetaMask windows though, which wasn't what I was referring to. Our requests to Infura are all made in the _background_ process, which you can access by going to "Manage Extensions", then clicking "Details" on the MetaMask extension, then under "Inspect Views" click "background page". If there are any Infura errors, they would be there. And for additional information on why they failed, you'd have to look in the Network tab rather than the console (you need to have it open when the error occurs).

**Comment by testoviron33** [comment]
@Gudahtt Thanks for very precise and kind answer and again apologies for late reply. I am horrible at replying sometimes...
I wasn't sure how I could post the result so I made a screenshots:
![bg1](https://user-images.githubusercontent.com/76965786/107119138-dea18b00-6885-11eb-92db-437233a41391.jpg)
![network1](https://user-images.githubusercontent.com/76965786/107119141-e103e500-6885-11eb-8b41-0d89ab464d86.jpg)

**Comment by Gudahtt** [comment]
Thanks for the reply! From the look of those background logs, every _second_ request to Infura is failing :thinking: 

That would hint that the token balance update calls are failing, while the `eth_blockNumber` calls are working fine. So likely everything is working _except_ tokens.

Something about the tokens you have locally must be breaking the token call we're making, or perhaps it's causing the token balance contract we use to fail. :thinking: 

This is definitely a bug, and not something I've seen before. At this point it would be most helpful if you could send us state logs via a support request. You can submit a support request here: https://metamask.zendesk.com/hc/en-us/requests/new
And here are instructions in downloading state logs: https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue

Thanks!

**Comment by iamveritas** [comment]
@testoviron33 did you manage to figure out this problem?
I am facing it now... and I remember facing it in the past, and after long searches I vaguely remember there's a setting in chrome that is blocking metamask to fully function... but I can't remember this setting for the life of me now :(
I am stuck with this still.

**Comment by test1101111** [comment]
> @testoviron33 did you manage to figure out this problem?

Yo, I am using chromium and I have the same problem probably, so it's not just ungoogled chromium it seems.

**Comment by iamveritas** [comment]
make sure in chrome you allow access to all websites to the metamask extension.
you write click on the metamask icon on the chrome bar and then "This can read and change site data" and then select "On All Sites" -- I really do not like this setting though...
this fixed it for me @test1101111

**Comment by test1101111** [comment]
> make sure in chrome you allow access to all websites to the metamask extension.
> you write click on the metamask icon on the chrome bar and then "This can read and change site data" and then select "On All Sites" -- I really do not like this setting though...
> this fixed it for me @test1101111

Apologies for the late reply and thanks for suggestion. That fixed the thing and yeah, that's sad thing that we can't have thi setting for metamask being activated only when we tell so.

**Comment by testoviron33** [comment]
> @testoviron33 did you manage to figure out this problem?

Yes, it fixed also the problem in my case! Many thanks! Me also apologies for being in a cave holiday for so long :D
I think we can close the issue.
