### ISSUE TITLE
Link to transaction details in the block explorer always link to etherscan.io

### ISSUE THREAD

**Issue by drgorb** [MetaMask/metamask-extension#10299]
## Bug Description

In the transaction history, every TX has a link to the block explorer
![image](https://user-images.githubusercontent.com/26613/106060627-93a0ae80-60f4-11eb-835c-47e732572011.png)
This link is to `etherscan.io` even on custom network for which a custom block explorer has been configured.

**Steps to reproduce**

1. Add a custom network with a custom block explorer to the settings. E.g.
![image](https://user-images.githubusercontent.com/26613/106060952-ff831700-60f4-11eb-86d9-db845569407c.png)
1. Send some token amount to an arbitrary address and wait for the transaction to be mined
2. Open the `Activity Tab` and click on the transaction you just sent
3. In the `Activity Log` section click on one of the 3 links for the transaction 

**Expected behavior**
The block explorer which was configured in the Network definition should be opened in a new tab with the transaction

**Screenshots**
## Network definition
![image](https://user-images.githubusercontent.com/26613/106060627-93a0ae80-60f4-11eb-835c-47e732572011.png)

## Activity Log
![image](https://user-images.githubusercontent.com/26613/106061492-bc757380-60f5-11eb-8c77-72f2eaa78395.png)

**Browser details (please complete the following information):**
 - OS: Mac OS Big Sur
 - Hardware Wallet: No
 - Browser: Brave 1.19.86 & FireFox & Chrome
 - MetaMask Version: 9.03

**Comment by Gudahtt** [comment]
Thanks for the report! We're aware of this problem, and we are tracking it under #10041. I'm going to close this as a duplicate.
