### ISSUE TITLE
personal_sign dies with"Must provide an ethereum address" when message length is 42 characters

### ISSUE THREAD

**Issue by joshlang** [MetaMask/metamask-extension#10297]
When the message to be signed is 42 characters long, `personal_sign` does with the phrase `Must provide an ethereum address`.

Repo: `ethereum.request({ method: "personal_sign", params: [ethereum.selectedAddress, "zzzzzxxxxxzzzzzxxxxxzzzzzxxxxxzzzzzxxxxx12"] })`

Add or remove a character from the message to be signed, and it works perfectly.  But 42 characters and it does.

(It probably sees "oh, 42 characters, it must be another signer address" or something).

**Comment by joshlang** [comment]
btw, the official docs say the params[] order is [message, address, password], although other docs say [address, message] - regardless, it's a weird edgecase.

**Comment by danfinlay** [comment]
Could you clarify what you're referring to as the "official docs"? I'm guessing the geth docs?

We may be able to improve our duck-typing here, this may be caused because we currently allow those params in either order (for bad historical reasons).

It could be nice to keep metrics on how many dapps rely on the less common param order (just log the length of the params, see if we could safely break the param order indepedence).

**Comment by Gudahtt** [comment]
I was able to reproduce this using the code snippet provided.

**Comment by joshlang** [comment]
It was probably the geth docs.  I could go searching again if you'd really like me to.  But it sounds to me like it's irrelevant, given that you're trying to support flexibility in your inputs ... which is cool

Probably just a `/^0x[0-9a-f]{40}$/i` to see if it's address-ish .. not sure if you support ens though.

**Comment by joshlang** [comment]
https://geth.ethereum.org/docs/rpc/ns-personal#personal_sign says:
`{"method": "personal_sign", "params": [message, account, password]}`

https://web3js.readthedocs.io/en/v1.2.11/web3-eth-personal.html#sign says:
`web3.eth.personal.sign(dataToSign, address, password [, callback])`

**Comment by danjm** [comment]
To trace the code that handles personal sign, start here: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js#L2560-L2578
