### ISSUE TITLE
Sender and destination missing from pop-out transaction confirmation screen.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#10313]
**Describe the bug**
When you use the MetaMask pop-out feature to put MM in a separate window, transaction confirmations do not show the sender or destination nor let you copy the sender or destination's address.

**Steps to reproduce (REQUIRED)**
1. Pop-out MetaMask into its own tab.
2. Initiate a transaction via a dapp.
3. Notice the pending transaction in the pop-out activity list.
4. Click on the pending transaction.
5. Try to view or copy the sender or the destination of the transaction you are signing.
6. Notice that you cannot do either.

**Expected behavior**
I can see and copy the sender and destination addresses for a contract call.

**Screenshots**
![image](https://user-images.githubusercontent.com/886059/106276935-426af900-6273-11eb-99f4-8edd5e95257e.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Hardware Wallet: N/A
 - Browser: Firefox 84.0.2
 - MetaMask Version: 8.1.11

**Additional context (Error Messages, etc.)**
I can see both the sender and destination in the plugin pop-up.  This problem is only present in the pop-out window.

**Comment by Gudahtt** [comment]
Thanks for the report! This is already being tracked here: https://github.com/MetaMask/metamask-extension/issues/9920
We're prioritizing this bug next week - I'm expecting we'll ship a fix in v9.0.5.
