### ISSUE TITLE
Signing with Hardware Wallet using MetaMask Extension Error

### ISSUE THREAD

**Issue by JeremyNau** [MetaMask/metamask-extension#10323]
**Describe the bug**
While using Ledger with the MetaMask extension, I am unable to sign a transaction. Upon signing with MetaMask, I am prompted with this message:

![image](https://user-images.githubusercontent.com/55710632/106392206-aee61500-63a5-11eb-84ea-6cb31da21e5b.png)

I proceed to sign all the verifier on my physical Ledger device.

I then am prompted with the same message in a recursive loop and unable to finalize the transaction.

![image](https://user-images.githubusercontent.com/55710632/106392223-c02f2180-63a5-11eb-8541-c45700c3f998.png)

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Connect Ledger Hardware wallet ETH address to MetaMask
2. Initiate and sign a transaction in MetaMask
3. Verifier the selectors on physical device
4. Observe recursive error message

**Screenshots**

![image](https://user-images.githubusercontent.com/55710632/106392281-f2408380-63a5-11eb-8a2f-8ffa57f977ce.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Hardware Wallet: Ledger Nano S
 - Browser: Brave & Chrome

**Comment by danfinlay** [comment]
Windows has unreliable support for the U2F protocol as is currently used by our hardware wallet support. We have some new integrations coming soon that should make this more reliable. You can try other troubleshooting steps on this support article: https://metamask.zendesk.com/hc/en-us/articles/360020394612-How-to-connect-a-Trezor-or-Ledger-Hardware-Wallet
