### ISSUE TITLE
Where does metamask store its extension data? 

### ISSUE THREAD

**Issue by creezytong** [MetaMask/metamask-extension#10322]
On version 8, I was able to see this in the corresponding folder for Brave's extension data. ie:

`/Users/user/Library/Application Support/BraveSoftware/Brave-Browser/Profile 1/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn`

But after updating the app the .ldb files are gone? Where are they stored? I've searched my mac for every folder with the extension id as a name, and there are no .ldb files in any of those folders. 

I lost my HD with my seed and I know for sure the .ldb files contain the KeyringController data. I just can't see the folder with the files for Brave anywhere? Not even for a new wallet I retrieved that I had a seed for?

**Comment by danfinlay** [comment]
This is a question for Brave @ryanml.

We have guides for other browsers [here](https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data), please let us know when you find out, and we'll add the answer to that guide.
