### ISSUE TITLE
[Onboarding] Add link to Twitter at the end of onboarding

### ISSUE THREAD

**Issue by rachelcope** [MetaMask/metamask-extension#10348]
#Description
As a new user, I want to be able to follow MetaMask on Twitter, so that I can stay up to date on the latest information

#Situation
**GIVEN:** A new user onboards to MetaMask
**WHEN:** They are finished with onboarding
**THEN:** They should see a link to Twitter so that they can follow the official twitter account

This was discussed with the Marketing team as a good way to maintain communication with new MM users

**Comment by mwood77** [comment]
Hey all, I'd like to pick this up.

Anything you'd like me to do first, like designs?

**Comment by rachelcope** [comment]
Designs are ready. But dependent on the implementation of new onboarding designs. 

cc @ryanml @yanrong-chen

https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=173%3A1179

**Comment by empeje** [comment]
Hi @rachelcope, has this issue has been resolved? I'm new to the Eth community and currently work on the ConsenSys Bootcamp, and I am interested in contributing.

**Comment by Gudahtt** [comment]
This is still open! Please feel free to submit a PR. Here is a screenshot of the latest design for this:

![follow-on-twitter](https://user-images.githubusercontent.com/2459287/140331847-670cc303-5f55-40cd-939b-3357f3001177.png)
(please ignore that black vertical line through the middle - that is a mistake)

The addition is on the bottom, the "Follow us on Twitter" text.

**Comment by empeje** [comment]
Thanks, @Gudahtt, I'll pick up this issue.

**Comment by empeje** [comment]
Hi @Gudahtt I have run a test in my local machine, turned out it is already implemented. The only minor difference is in the copy

```diff
+ Recovery Phrase safe and secret, it's your responsibility!
- Recovery Phrase safe and secret -- it’s your responsibility!
```
<img width="1327" alt="Captura de Pantalla 2021-11-07 a la(s) 17 40 51" src="https://user-images.githubusercontent.com/11813607/140641664-9db63b5d-1e8b-4fb0-85b0-a9f4a986e326.png">

Any other thing that I can work on?
