### ISSUE TITLE
Remove "My Wallet Account" section in Settings > Contacts

### ISSUE THREAD

**Issue by rachelcope** [MetaMask/metamask-extension#10342]
**Description**
Remove "My Wallet Account" section in Settings > Contacts

As a user, I don't want to see a list of my accounts under my Contact settings. I believe this is a result of the Settings > [Contact page designs](https://github.com/MetaMask/metamask-extension/issues/7069) not being fully implemented.

For now that section should be removed. 

**Steps to replicate**
1. Go to 'Settings'
2. Click on 'Contact'

**Comment by bschorchit** [comment]
Closing as this has been fixed [here](https://github.com/MetaMask/metamask-extension/pull/10680)
