### ISSUE TITLE
Approve Confirmation design improvements

### ISSUE THREAD

**Issue by rachelcope** [MetaMask/metamask-extension#10345]
#Overview
Improve the Approve Confirmation designs

* ~~**Copy "To" contract address** As a user, I want to be able to copy / expand the contract address in ‘To:’ on Approve screen~~ (This will be handled as part of https://github.com/MetaMask/metamask-extension/issues/12351)
* **Remove "Https://" from origin** Remove "Https://" from the header and subheader (this is handles as a part of https://github.com/MetaMask/metamask-extension/pull/12360)
* **Update designs/components** Update header components to the updated transaction confirmation components

**Comment by JSRossiter** [comment]
I think it would be a big improvement if the Approve Confirmation screen respected "Advanced gas controls" and "Customize transaction nonce" settings. Many users (myself included) set the gas manually for every transaction and this currently takes several clicks for approves. There is no current way to customize the nonce for an approval transaction.

**Comment by kevinghim** [comment]
Related  [Remove "Https://" from origin Remove "Https://" from the header and subheader](https://www.notion.so/Remove-Https-from-origin-Remove-Https-from-the-header-and-subheader-818810f0780c4fd0b35e4c62690381e1)
