### ISSUE TITLE
Removed web3 API notification trigger?

### ISSUE THREAD

**Issue by juhah** [MetaMask/metamask-extension#10356]
Metamask 9 adds a notification if the removed web3 API is used

![Screenshot 2021-02-03 at 15 32 28](https://user-images.githubusercontent.com/1064982/106754367-90964880-6635-11eb-977d-810966990a4c.png)

This was added in https://github.com/MetaMask/metamask-extension/pull/10039 if I understand correctly.

I would like to ask what is the condition that actually triggers this notification? Is it if I try to access `window.web3` or `window.web3.currentProvider`? In our app, I do a check for the provider in this manner:

```js
if (typeof ethereum !== 'undefined') {
    return ethereum
} else if (typeof web3 !== 'undefined') {
    return web3.currentProvider
} else {
   throw new Error(...)
}
```

If I remove mentions of `window.web3`, I still get that notification... is it just cached in the store or how can I be sure that the notification condition doesn't happen? Thanks!

**Comment by Gudahtt** [comment]
We show that notification if any property of our injected `window.web3` shim is accessed, _other than_ `currentProvider`. So the code shown is not responsible for that notification being shown. There must be something else accessing `window.web3` on your site.

It might be used in a library you're using perhaps? If you can't find any references to `web3` used directly in your code, that'd be my guess. I would suggest searching again for references to `web3` in your codebase, and maybe sharing your dependencies (including exact versions) so we can help find the culprit.

For reference, the code for creating this shim is here: https://github.com/MetaMask/inpage-provider/blob/main/src/shimWeb3.ts

**Comment by juhah** [comment]
@Gudahtt Thanks for the clarification. It might indeed be an external lib. I don't get any logged warnings or errors to console, though, if I inspect the extension in the Chrome developer popup. Or do I need to enable more logging somewhere?

We are using the Web3 lib version `1.0.0-beta.55`, the wrapped instance is always used in the code. Only the setup accesses the Metamask provider. That shouldn't touch the shim, right?

```js
const getMetamaskProvider = () => {
    if (typeof ethereum !== 'undefined') {
        return ethereum
    } else if (typeof web3 !== 'undefined') {
        return web3.currentProvider
    } else {
       throw new Error(...)
    }
}

// ...

const web3 = new Web3(getMetamaskProvider())
```

**Comment by juhah** [comment]
Ok, it looks like this is in fact caused by that version of `Web3`. The `ProviderDetector` accesses `window.web3. currentProvider` here: https://github.com/ChainSafe/web3.js/blob/3e4427940be4aa897d33c3ecb559d8cec9179e2b/packages/web3-providers/src/detectors/ProviderDetector.js#L46

This gives me an error twice, once a warning and the second is an error because the logged condition is fulfilled in the first branch:
![Screenshot 2021-02-04 at 10 22 47](https://user-images.githubusercontent.com/1064982/106865139-73b05280-66d3-11eb-929e-9d501c5355ff.png)

I'll look into another version of Web3 but an issue for Metamask might be that a second call to access `web3.currentProvider` should be a no-op and not trigger an error?

**Comment by Gudahtt** [comment]
Oh, great find! Yes that is definitely a bug. You're right, the popup shouldn't be showing up at all for your site. We'll aim to fix this in the next release.

**Comment by juhah** [comment]
Great, thanks for helping me figure it out!

**Comment by elliotaplant** [comment]
Will metamask give this warning even if you import your own version of Web3?
Could you provide an example for how to use the library Web3 with metamask as the provider?
And is this warning pop-up cached? I could not remove the pop-up even after stripping the page down to bare HTML with no JS (and definitely no web3)

Thanks!
