### ISSUE TITLE
Attempting to connect Trezor to metamask gives error "Manifest not set. Read more at https://github.com/trezor/connect/blob/develop/docs/index.md"

### ISSUE THREAD

**Issue by Earlz** [MetaMask/metamask-extension#10359]
**Describe the bug**
I get a seemingly developer oriented error upon trying to pair my Trezor with metamask "Manifest not set. Read more at https://github.com/trezor/connect/blob/develop/docs/index.md ". Restarting chrome, changing USB ports, etc does not resolve the issue. 

**Steps to reproduce (REQUIRED)**

The first time I tried to pair the device, this worked differently, it opened the trezor website but would not load, just continual spinning circle. I restarted the browser and tried again and now I can only get the manifest not set error. I have no problem using the device with Trezor connect nor through the Trezor web wallet. 

The Trezor device was just setup an hour ago and is using latest firmware etc, also using latest chrome on Mac OSX (x86)

**Expected behavior**

I expected it to simply pair and see the account list as documented in tutorial etc

**Browser details (please complete the following information):**
 - OS: OSX 11.01, x86
 - Hardware Wallet: Trezor Model T, firmware version 2.3.4
 - Browser: Chrome 88.0.4324.96 (Official Build) (x86_64)
 - MetaMask Version: 9.04

**Comment by tmashuang** [comment]
Related to #10372.

**Comment by darkwing** [comment]
It's bizarre to see this error as we're definitely providing a manifest:

https://github.com/MetaMask/eth-trezor-keyring/blob/master/index.js#L28

**Comment by darkwing** [comment]
We've recently updated our Trezor libraries -- please try with an updated version of MetaMask (9.2.0) and let us know if you still see the issue.  If so, I'd love a screenshot or video.  Thank you!

**Comment by Earlz** [comment]
I'm still having this issue. For reference, I plug the wallet in, unlock the wallet, then walk through these steps:

1. Unlock metamask wallet (I have an existing software wallet account)
2. Push metamask button
3. Goto option for "connect hardware wallet"
4. choose Trezor option
5. Push connect

At this point, the trezor wallet page opens in a new page and says "connecting" with a spinning circle, but never completes even after waiting about 10 minutes. If I refresh the page, nothing happens and it continues trying to connect and never succeeding. If I close the tab and try to repeat the wallet connect procedure, I still get the same manifest error. If I close chrome and reopen, it allows me to try connecting again, but still does not work, due to the trezor page never properly connecting. However, for reference the trezor browser wallet works fine with no problem. I used developer mode to force updating to Metamask 9.2.0 but saw no difference in the process

Some screenshots for reference: https://imgur.com/a/EfyZpxl

**Comment by Earlz** [comment]
For reference, I have the same behavior even when my Trezor is not connected to my computer

**Comment by Ethycs** [comment]
I'm also having this error

**Comment by HOneyHOrde** [comment]
Me Three... :(  It works fine with the Trezor suite, Exodus, MEW and everything else ive tried, except for metamask. after I click to connect it says "Looking for your Trezor" with the spinning circle and keeps it up.

**Comment by cyphunk** [comment]
Same error when with metamask in Brave, but not in Google chrome.

**Comment by w7xx** [comment]
Same here.. Can't connect my Trezor to Metamask. I'm running on Brave

**Comment by Liferocka** [comment]
Same.. Any resolve?

**Comment by Liferocka** [comment]
Any resolve? Pleaseeeee?

**Comment by cyphunk** [comment]
> Any resolve? Pleaseeeee?

I dont use metamask often but I believe I got this working eventually in Chrome, not brave. I also dont remember if I got it working by starting the daemon bin manually, or by starting trezor suite. Try both, all, in different combinations.

**Comment by lawloretienne** [comment]
So i just resolved this by restarting my computer which closed everything out and then when i logged back on my metamask was logged out and i had to log back in again, then i was able to successfully connect the hardware wallet to metamask.

**Comment by seaona** [comment]
I am getting this same error on 10.12.4 @danjm. Here are the repro steps:
1. Unlock Metamask
2. Import a Hardware wallet account
3. Be sure you have active a Trezor account
4. Lock Metamask
5. Click "Forgot Password"
6. Restore the Wallet
7. Import a Hardware wallet account -- this will trigger the error

https://user-images.githubusercontent.com/54408225/161814018-c1c2d9ad-566a-4cad-aed2-66a17c44810c.mp4
