### ISSUE TITLE
0 eth confirmed transaction

### ISSUE THREAD

**Issue by josecobi** [MetaMask/metamask-extension#10371]
Hi i was trying to send  $20 worth of eth from my metamask account to another address. The transaction is confirmed but sent 0 eth and they charged me fees. I chose the slowest transaction so I clould pay less fees.

I did the transaction from my linux mint laptop.
Firefox browser.
Metamax extension for firefox
![Screenshot_20210204-052220_MetaMask](https://user-images.githubusercontent.com/58313777/106880262-25d32480-66aa-11eb-8680-900b0255aee9.jpg)
![Screenshot_20210204-053200_MetaMask](https://user-images.githubusercontent.com/58313777/106880448-5fa42b00-66aa-11eb-8b67-bcdc5a4f7903.jpg)

**Comment by Gudahtt** [comment]
Those screenshots are of MetaMask mobile, not of the browser extension. Please [contact support](https://metamask.zendesk.com/hc/en-us/requests/new), and they can help you further. Thanks!
