### ISSUE TITLE
Ensure stream-middleware can tolerate an unknown response ID without dying

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10377]
Trying out [secret finance](), a dapp that combines connections with MetaMask and the Cosmos Keplr wallet.

It seems that they use some of the same internal tooling we built for MetaMask, which means that there's a little cross-talk that seems to be causing a hard failure.

```
inpage.js:1 Error: StreamMiddleware - Unknown response id "2402462468"
    at g._handleDisconnect (inpage.js:1)
    at g._handleStreamDisconnect (inpage.js:1)
    at inpage.js:17
    at t (inpage.js:17)
    at f.<anonymous> (inpage.js:17)
    at f.t (inpage.js:17)
    at f.m (inpage.js:8)
    at d (inpage.js:8)
    at f.s.emit (inpage.js:8)
    at inpage.js:17
```

Proposal: We should not throw an error if there is an unknown response ID, we should just silently ignore it.

**Comment by dAskyacc** [comment]
I was pitted by this bug, the boss asked me to solve it, and DAPP gave a prompt. I couldn't distinguish by judging ethereum !== (await detectEthereumProvider()). Shit same TRON extension

**Comment by isloux** [comment]
I'm also interested to find out. I have a similar issue when trying the template-snap from Metamask Snaps.

**Comment by davidlee1435** [comment]
i also had this issue while trying out metamask snaps

**Comment by alexbakers** [comment]
This error occurs if you have 2 versions of Metamask installed.

<img width="150" alt="image" src="https://user-images.githubusercontent.com/98721968/200203007-0df00a5a-21a8-4f2a-8df0-93830482dcbd.png">

**Comment by shin101004** [comment]
i also had this issue while trying out getBalance methods in the erc20 contract.

i dont know why the above error happened only metamask app browser in iOS/android devices. 

react 18+
web3js 1.7.5
node 18+
sepolia network

my dapp process is
1. connect metamask
-> changeNetwork to sepolia
-> connect wallet
2. call getBalance methods in useEffect
-> Stream error occurred

**Comment by DonChaarly** [comment]
this happends to me in react when I have this code from the documentation inside of a functional component that change when set a new state:
```
const MMSDK = new MetaMaskSDK({
  openDeeplink: (link) => {
    Linking.openURL(link); // Use React Native Linking method or your favourite way of opening deeplinks
  },
  timer: BackgroundTimer, // To keep the app alive once it goes to background
  dappMetadata: {
    name: 'My App', // The name of your application
    url: 'https://myapp.com', // The url of your website
  },
});

const ethereum = MMSDK.getProvider();
```

to fix it, you have to move the code outside from the functinal component

**Comment by kylekaplan** [comment]
> this happends to me in react when I have this code from the documentation inside of a functional component that change when set a new state:
> 
> ```js
> const MMSDK = new MetaMaskSDK({
>   openDeeplink: (link) => {
>     Linking.openURL(link); // Use React Native Linking method or your favourite way of opening deeplinks
>   },
>   timer: BackgroundTimer, // To keep the app alive once it goes to background
>   dappMetadata: {
>     name: 'My App', // The name of your application
>     url: 'https://myapp.com', // The url of your website
>   },
> });
> 
> const ethereum = MMSDK.getProvider();
> ```
> 
> to fix it, you have to move the code outside from the functinal component

Working on react-native app, not only does `new MetaMaskSDK` need to be outside of functional component, but I also had to remove it from all other files (only one MetaMaskSDK initialization in entire project).

**Comment by andreahaku** [comment]
@kylekaplan @DonChaarly yes, confirmed, you need to initialise the MM SDK only once and outside of functional components. We'll clarify this better in the documentation. But I can already tell you that we are working on react/react native hooks that will make this even easier to handle.
