### ISSUE TITLE
Wrong Currency Symbol when using Custom Network

### ISSUE THREAD

**Issue by DimmOFF** [MetaMask/metamask-extension#10389]
**Description:**
When using a custom network, each time after login it shows 'ETH' Currency Symbol instead of what was configured in network settings. 

**Steps to reproduce:**
1. Add new Network:
 Network Name: Expanse
 New RPC URL: https://node.expanse.tech/
 Chain ID: 2
 Currency Symbol (optional): EXP
 Block Explorer URL (optional): https://explorer.expanse.tech/
2. Go to the main. 
  **Actual Result:** 'EXP' is used as Currency Symbol. It is ok. 
3. Close and Reopen Chrome.
4. Log in to an account. 
 **Actual behavior:** 'ETH' Currency Symbol is used despite the selected Expanse network.
 **Expected behavior:** 'EXP' Currency Symbol is used.

**Browser details:**
OS: Windows 10
Browser Chrome 88.0.4324.146
MetaMask Version 9.0.4

**Screenshots**
![1](https://user-images.githubusercontent.com/2872443/107114878-d4759180-6871-11eb-9242-5845ea14a75b.JPG)
![2](https://user-images.githubusercontent.com/2872443/107114879-d50e2800-6871-11eb-857c-dc3699d6792c.JPG)

**Comment by Gudahtt** [comment]
Thanks for the report!

I was unable to reproduce this using v9.0.4. "EXP" does show up on the main page, unlike what you've shown here.

Could you [submit a support ticket](https://metamask.zendesk.com/hc/en-us/requests/new) and [include state logs](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue)? That would help us a great deal in investigating this problem.

**Comment by DimmOFF** [comment]
@Gudahtt submitted request with state logs. 
If needed I can record a video. The issue is reproduced after reopen Chrome and Log in to an account. Expanse network must be already be selected.

**Comment by Gudahtt** [comment]
Ah, sorry I followed the reproduction steps incorrectly. When I disable then re-enable the extension before checking the home page, I see the problem exactly as you've shown here. Thanks for the help!
