### ISSUE TITLE
Error: unsupoported chain id , using Trezor and BSC Binance Smart Chain on MetaMask

### ISSUE THREAD

**Issue by randymetamask** [MetaMask/metamask-extension#10394]
**Describe the bug**
From this other comment https://github.com/MetaMask/metamask-extension/issues/8349#issuecomment-774109323 and case number 84018:

_tried to swap in the BSCX swap for the BSCX token._

_when unlocking the Trezor T with my passphrase, I was unable to complete the operation, showing **"Error: unsupoported chain id"**_

_transfer the same BNB and BUSD to the Official Binance Smart Chain wallet same error appeared on MetaMask._

_The tokens are frozen in my MetaMask wallet with Trezor. Does the Binance Smart Chain wallet on MetaMask+Trezor does not support passphrase?_

**Browser details (please complete the following information):**
 - Hardware Wallet: Trezor T
 - MetaMask Version: 9.0.4

**Additional context**

@stx233 do you know if using the Binance Chain wallet mentioned in this Binance help page https://docs.binance.org/smart-chain/wallet/binance.html could be a workaround for Binance Smart Chain users who want to use Trezor T?

**Comment by randymetamask** [comment]
This user in Reddit suggested a workaround for Trezor T users using different networks on MetaMask:

spectre_mandica:
_Trezor firmware v2.3.3 won't let you sign transactions that are on a different derivation path than the original one of the chain that the coins are supposed to be at._
_To be able to use Metamask / Nifty + Trezor on xDai or other chains you would need to downgrade the Trezor firmware to v2.3 and it then works fine. Only works on Model T and not Trezor One._

@matejcik @yohaaan @prusnak do you know if is this issue is still present in version 2.3.4 of the Trezor T firmware?

**Comment by prusnak** [comment]
This will be fixed in Firmware 2.3.5 released on Wednesday (10th of February)

**Comment by randymetamask** [comment]
Thanks for the info @prusnak . We'll make sure to test it ourselves later this week and update this issue.

**Comment by prusnak** [comment]
https://github.com/MetaMask/metamask-extension/issues/8349#issuecomment-776934284 mentions that FW 2.3.5 released today fixes the issue

**Comment by darkwing** [comment]
Excellent, thank you so much @prusnak !

**Comment by ChooChooCC** [comment]
> This will be fixed in Firmware 2.3.5 released on Wednesday (10th of February)

I had the  same issue when I was using 2.3.4, I downgraded to 2.3.0 and it fixed the issue. However, I waited for 2.3.5 to come out and I upgraded from 2.3.0 to 2.3.5 and the issue re-appear again. Basically the pop up window for me to sign never showed up. I am downgrading this back to 2.3.0 for now.
