### ISSUE TITLE
'Forbidden key path' error when submitting new transaction using Custom Network with Trezor Model T

### ISSUE THREAD

**Issue by DimmOFF** [MetaMask/metamask-extension#10390]
**Description:**
Cannot use custom network with Trezor Model T. 'Forbidden key path' error is shown when sending some tokens. 
Note: Issue is not reproduced with Trezor One 

**Steps to reproduce:**
1. Add new Network:
 _Network Name:_ Expanse
 _New RPC URL:_ https://node.expanse.tech/
 _Chain ID:_ 2
 _Currency Symbol (optional):_ EXP
 _Block Explorer URL (optional):_ https://explorer.expanse.tech/
2. Import account from Trezor Model T with some EXP. Note: I will send you a small portion of EXP to reproduce the issue if needed.  
3. Try to send some amount of EXP. 
**Actual behavior:** 'Forbidden key path' error message is shown.
 **Expected behavior:** Transaction is submitted successfully without any issues.

**Browser details:**
 - OS: Windows 10
 - Hardware Wallet: Trezor Model T. Firmware version 2.3.4
 - Browser Chrome 88.0.4324.146
 - MetaMask Version 9.0.4

**Screenshots**
![1](https://user-images.githubusercontent.com/2872443/107115469-97ab9980-6875-11eb-9636-6c1dbef449c6.png)

**Comment by DimmOFF** [comment]
The issue is not actual for Trezor Model T. Firmware version 2.3.5

**Comment by gg2001** [comment]
Is this fixed? I'm having the same problem

**Comment by DimmOFF** [comment]
Check if your Trezor firmware is up to date. 
It stopped to be reproduced after version 2.3.5 released

**Comment by gg2001** [comment]
Nope. I've been on 2.3.6 and still getting the error

**Comment by chompomonim** [comment]
Same problem here. Just upgraded trezor firmware into newest version, still getting the error.

**Comment by acarlton** [comment]
I'm also experiencing this error on 2.3.6

**Comment by DaigaroCota** [comment]
Similar error on Rinkeby. Firmware 2.4.1

**Comment by c6y** [comment]
Same error here on Rinkeby. Firmware 2.4.1: Metamask 10.1.0

**Comment by danjm** [comment]
This is still an issue

**Comment by GalaxyLittlepaws** [comment]
Same issue.
Browser details:

OS: Windows 10
Hardware Wallet: Trezor Model T. Firmware version 2.4.2
Browser: Brave Version 1.31.91
MetaMask Version: 10.5.1

**Comment by GalaxyLittlepaws** [comment]
An update to my earlier comment: when I change the "Safety checks" setting in Trezor Suite to "Prompt", I am able to make the transaction (at least on the Rinkeby testnet it worked).

**Comment by ryanchamp-ICE** [comment]
> An update to my earlier comment: when I change the "Safety checks" setting in Trezor Suite to "Prompt", I am able to make the transaction (at least on the Rinkeby testnet it worked). I did change it back right after for safety.

This worked for me as well. I was just trying to move some test ETH on Rinkeby to another wallet and ran into a wall with this error but this got me unstuck. Thanks @GalaxyLittlepaws!

**Comment by 8f9d530a** [comment]
> An update to my earlier comment: when I change the "Safety checks" setting in Trezor Suite to "Prompt", I am able to make the transaction (at least on the Rinkeby testnet it worked). I did change it back right after for safety.

Works with WanMask after I updating Trezor

**Comment by dectf** [comment]
> An update to my earlier comment: when I change the "Safety checks" setting in Trezor Suite to "Prompt", I am able to make the transaction (at least on the Rinkeby testnet it worked). I did change it back right after for safety.

saved my day

**Comment by poonsak58** [comment]
> An update to my earlier comment: when I change the "Safety checks" setting in Trezor Suite to "Prompt", I am able to make the transaction (at least on the Rinkeby testnet it worked). I did change it back right after for safety.

save my life.

**Comment by seaona** [comment]
I confirm the issue is fixed when you change the settings on Trezor Suite to `Prompt`.
Should we add some note on the UI for explaining this extra step when performing a Trezor tx? @AlexJupiter @georgewrmarshall 

![image](https://user-images.githubusercontent.com/54408225/175043876-6d1af55e-4d9c-4afe-92c7-079da0751c1e.png)

![image](https://user-images.githubusercontent.com/54408225/175043943-989ca920-637e-4077-8987-55ac7532b649.png)

**Comment by LaManoDeDiosS** [comment]
I have the solution for that error if you like to contact me by mail carnao.net1@gmail.com
