### ISSUE TITLE
Multiple transactions in queue and 1 stuck in pending...help please

### ISSUE THREAD

**Issue by noobcrypto123** [MetaMask/metamask-extension#10401]
using brave browser, IOS latest software and metamask wallet.

I will try to explain what happened the best I can, forgive me if i dont use the correct words.

I swapped ETH for SNOW on 1 inch last night and the transaction went through as expected.  Then there was a second transactions that was pending that never went through and was and still is stuck in pending.  this transaction is nounce 36.  I then tried to stake my snow and saw that those transactions were also not going through since nounce 36 was still pending.  I tried to increase the gas fees and cancel and those just went into the queue as well.  

I then tried to recreate another transaction using the nounce 36 number to replace the one stuck in pending.  Well now I have 14 transaction stuck in the queue and when i try to look at them at ether scan the current one in pending does not have a hash number, it says its invalid on etherscan.  

Here is my public address 0xcDB31a38ccD12B8F3393b9236539268aA45cE718.

At this point I cant even use my wallet and the last transaction that says pending has no transaction on etherscan.

I would be grateful for any help anyone could offer

**Comment by noobcrypto123** [comment]
![IMG_0813](https://user-images.githubusercontent.com/78745859/107242112-a58a2780-69f9-11eb-83ab-31072e415514.jpeg)

**Comment by noobcrypto123** [comment]
I reset the metmask and it cleared the pending transaction in the mask but they still show up in etherscan.....

**Comment by noobcrypto123** [comment]
after reseting metamask I tried to send 0 eth to myself with nounce 36 and while metmask says its pending in the activity screen clicking on the hash says its invalid.....

**Comment by Gudahtt** [comment]
I took a look at your address on Etherscan, and it looks like the problem has been resolved! Sorry we couldn't be of any help.

In the future, I'd suggest contacting our support instead of making a GitHub issue. This repo is for tracking bugs and enhancements, not for helping with issues like this. You can make a support request here: https://metamask.zendesk.com/hc/en-us/requests/new
