### ISSUE TITLE
Tokens moved to a random? account, instead of send to delegation

### ISSUE THREAD

**Issue by mdm3z** [MetaMask/metamask-extension#10412]
I have intended to transfer Matic tokens for delegation using https://wallet.matic.network/staking/.

I have connected Metamask to that website and carefully followed required steps. It was shown to me that token were send to delegation. Next day when I tried to check status it wad like I have never send them anything. I did contacted support, giving them transaction ID but they claim that it is manual transfer which I have done by myself or that my keys have been stolen, both impossible.

If You take a look at transaction https://etherscan.io/tx/0xb350ee1443f8e9e005262bb652771e9e3e74bc0f5be7bfe91c6ba5668a0d25dd
You will see that there was 47,642.000000000001048576 tokens transfered to account

https://etherscan.io/address/0xb237bcde6b341f2ebb31a1743d5e7975c35a8293

Which I have never used and have no access to

 After a bit o research i concluded that this dot after 47,642 makes system to think that it has been only 0.000000000001048576 tokens to be transfered
which makes my delegation fail to reach minimum required and therefore entire ammont has been transfered to an account of origins unknown to me.
Take a look:
47,642.000000000001048576
47,642000000000001048576

That makes a difference isn't it?

I have managed to speak with one of the users on Reddit with the same problem.
He claimed that he also delegated tokens and they have been send to a different account instead.
His transactions appears to have the same glitch, where decimals has been put worngly causing system to see wrong number.
I will quote
od MacGregoreyev przez /r/Metamask wysłane 1 dzień temu
Hi,Here is the TX :https://etherscan.io/tx/0x70c35eeb2652c7f754826f22d5f685160bd0bad36bb285dc2acfba4400618134
Support told me I sent tokens to address 0x67b1419e1e45ae247ac84d4bc94bd6b529c667d1But as far as I remember I clicked the Delegate button.
Finally he recomended to follow the official delegation guide for Matic Tokens : https://docs.matic.network/docs/validate/delegator

Of course there is no solution under this link.
Now if You tak a look at this transaction https://etherscan.io/tx/0x70c35eeb2652c7f754826f22d5f685160bd0bad36bb285dc2acfba4400618134
You can see the same pattern.
He delegated
7,841.827247480832054943
not
7,841827247480832054943
which again caused a glitch resulting in tokens being moved to an account unknown to him
0x67b1419e1e45ae247ac84d4bc94bd6b529c667d

Just like in my case.

Can You please take a second look at it? Support claim that I have done that transfer but I never had access to that account and never interacted with it in any way:( 

Is there a way that to fix it and get my tokens back?

**Comment by tmashuang** [comment]
If all the things described in this issue are correct, this is not a MetaMask issue. Without knowing about the inner workings of the Matic Contract, this seems to be a parsing issue on the Matic Contract side and it is not tolerant of all values. The decimal is placed at the 18th place which is the token's decimal precision.

**Comment by mdm3z** [comment]
Hi. Is it possible that token bounced back to my account but since I am
using multicoin wallet, it has not come to the main wallet but to a new
subwale which metamask do not see?
Transfering was suppose to happened between Ethereum and Matic L1 networks
, so could it be, that token has been converted to a readable in their
network but did not came back as ERC-20 thats why it jumped to a separate
account?
It has been more than a month since that happened and Matic support do not
believe in any other verion than me sending ir personally and thaforcing
them to give it back twice.
I cant seem tany other 90
Any further help will be apriciated, thanks

czw., 11 lut 2021 o 18:48 Thomas Huang <notifications@github.com>
napisał(a):

**Comment by tmashuang** [comment]
> Is it possible that token bounced back to my account but since I am using multicoin wallet, it has not come to the main wallet but to a new subwale which metamask do not see?

I dont understand what you mean. Is this a feature of the Matic Contract? MetaMask queries token balances of tokens, if MetaMask and block explorers are not associated tokens to you then, most likely, no tokens have "bounced back".
