### ISSUE TITLE
No response form Infura

### ISSUE THREAD

**Issue by aminlatifi** [MetaMask/metamask-extension#10419]
**Describe the bug**
MetaMask cannot fetch network info or make a transaction

**Screenshots**
I see this message in the browser console
```
Uncaught (in promise) Error: missing response (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":708,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={}, url="https://mainnet.infura.io/v3/03f1a9a53dee4bd5a7d3dde58ce26442", code=SERVER_ERROR, version=web/5.0.2)
    makeError index.js:166
    throwError index.js:175
    m index.js:136
    a index.js:6
index.js:166:22
```
![image](https://user-images.githubusercontent.com/5684607/107607162-b0d59100-6c4d-11eb-9d47-3e2f55d9997c.png)

**Browser details (please complete the following information):**
 - OS: MacOS Big Sur
 - Hardware Wallet: Macbook Pro
 - Browser: Firefox 85.0.2
 - MetaMask Version: 9.0.5

**Comment by tmashuang** [comment]
This infura api is not the one we use. Can u provide any additional information for reproduction?

**Comment by jacobcantele** [comment]
Hi @aminlatifi , since we haven't heard back from you and this isn't our official Infura endpoint, I'm going to close this issue for now. Please feel free to share any additional information and I can re-open.
