### ISSUE TITLE
Error Gasprice in custom network

### ISSUE THREAD

**Issue by kevinho** [MetaMask/metamask-extension#10416]
**Describe the bug**
I am using metamask via custom network. The gasprice in the transaction panel is different with the eth_gasprice json-rpc response of the target rpc.

**Steps to reproduce (REQUIRED)**

1. setup custom network, rpc is https://http-mainnet-node.huobichain.com
2. send native token, check the gasprice
3. about 200Gwei (which is similar with the current eth mainnet gasprice)
4. the rpc response

```
curl --location --request POST 'https://http-mainnet-node.huobichain.com' \
--header 'Content-Type: application/json' \
--data-raw '{"jsonrpc":"2.0","id":3,"method":"eth_gasPrice","params":[]}
'
```

```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": "0x3b9aca00"
}
```

which is 1GWei

**Expected behavior**

get gasprice from custom network rpc

**Screenshots**
![matamask](https://user-images.githubusercontent.com/546824/107484263-25142400-6bbd-11eb-917d-7357f790017c.png)

**Browser details (please complete the following information):**
 - OS: OSX 10.15.7
 - Hardware Wallet:
 - Browser: Chrome Version 88.0.4324.146 (Official Build) (64-bit)
 - MetaMask Version: 9.0.4

**Additional context (Error Messages, etc.)**

**Comment by kevinho** [comment]
When review the code, 

the gasprice is fetched by https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/ducks/gas/gas.duck.js#L100

and cached to local.


it's set to a static url "https://api.metaswap.codefi.network/gasPrices", other than the custom rpc provider.

**Comment by brad-decker** [comment]
@kevinho this issue has been reported on #10003, closing as duplicate but will link your issue there.
