### ISSUE TITLE
Order Cancelation Interrupted

### ISSUE THREAD

**Issue by orvz1** [MetaMask/metamask-extension#10417]
macOS Catalina V 10.13.7  
MetaMask Version
9.0.4
Size
27.4 MB

I cancelled multiple orders on Uniswap due to high gas fees and had to cancel multiple times.

One order seems stuck on cancelation mode and I am unable to make anymore trades.

I increased speed of cancelation multiple times.

Transaction ID: 0xed6d9e0d3221d3db39b659bebb286dfa0b63334e91b2c3b31edbbd14d3bb72d4

![Screen Shot 2021-02-10 at 11 59 46 AM](https://user-images.githubusercontent.com/78877869/107564696-980aa400-6b97-11eb-86ee-2d89c664b867.png)
![Screen Shot 2021-02-10 at 11 59 53 AM](https://user-images.githubusercontent.com/78877869/107564713-9b059480-6b97-11eb-8af5-51b251bb7bdf.png)

**Comment by tmashuang** [comment]
Seems that the gas price depicted is lower than the average tx in the tx pool. You can view recommended gas prices from other sources such as https://ethgasstation.info/ or https://etherscan.io/gastracker.

**Comment by orvz1** [comment]
Is it possible to edit the gas so I can get the cancellation through?
