### ISSUE TITLE
qubcoins.world and MetaMask problem. Need help.

### ISSUE THREAD

**Issue by githubDen777** [MetaMask/metamask-extension#10427]
**qubcoins.world and MetaMask problem. Need help.**

Can not withdraw or unstake my coins.

https://etherscan.io/tx/0x913d14fdf605188ad51fb408b190070c830c36f000ce4e4d13b5bc0d1ede8c14

https://ibb.co/NnXh9YH
https://ibb.co/4pwyFJT
https://ibb.co/ZdQS2F4
https://ibb.co/fQ8JxFd

Help please!

**Will pay 200 USDT who will help me with my problem.**

**Comment by githubDen777** [comment]
Who could help?

**Comment by Gudahtt** [comment]
Could you please make a support request? You can submit one here: https://metamask.zendesk.com/hc/en-us/requests/new
Our support team will do their best to help you out.

**Comment by githubDen777** [comment]
No one answer, who could help for 300 USDT?

**Comment by githubDen777** [comment]
Still actual!!

**Comment by githubDen777** [comment]
any one?

**Comment by githubDen777** [comment]
Will pay 300 USDT who will help me with my problem.

https://ibb.co/VvJbCVB
https://ibb.co/2PcStJB
https://ibb.co/ByD4M0f
https://ibb.co/4TgZLGR
https://ibb.co/qMV13LJ
