### ISSUE TITLE
Uses mainnet for custom network gas price

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#10425]
If you enter a custom network it will use ETH mainnet for gas price estimation. I suspect the issue also happens for testnets. Instead it should default to `eth_gasPrice` jsonrpc. Since mainnet gas price is so high this behavior wastes a lot of gas on prod networks like ETC and BSC, but also on testnets like Rinkeby and Kovan.

**Comment by tmashuang** [comment]
Duplicate of #10003.
