### ISSUE TITLE
Metamask Ledger-connected account can't process any transaction on Binance Smart Chain

### ISSUE THREAD

**Issue by Vytautas5** [MetaMask/metamask-extension#10446]
Please reopen ticket #10132. The problem is not solved, many people met the same problem after issue was closed.

**Comment by leanec** [comment]
Same problem. When I do a transaction with Metamask, Ledger is not prompted to Approve Transaction, so the transaction inside MetaMask is just "pending forever"

**Comment by jacobcantele** [comment]
@Vytautas5 and @leanec , please review the support steps and solutions posted in that previous ticket. If you believe that those steps don't resolve the issue, we can revisit, but this is an issue on the Ledger side that we've provided a work around for. I'll close this issue for now, but please feel free to share move info an I can re-open the original issue.
