### ISSUE TITLE
Understand where to get support

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#10458]
As a MetaMask Extension user, I'd like to better understand what the official support channels for MetaMask are and understand that fake support channels contain scams, so that my funds will be more secure.

**description**

Telegram scams seem to be growing as one of the primary scam vectors with the rise of new more sophisticated and official-looking MetaMask channels.

One user in particular shared concern that he didn't know where to find support, so he went looking on Telegram. One way we could reduce scams is by making the official support in the extension more prominent and accessible.

We could also add language around only seek support from official support channels to avoid scams to the onboarding journey.

Needs designs.

**Comment by rachelcope** [comment]
Hi @Nanopollinator - unfortunately, you have to have the full 12-word seed phrase (recovery phrase) in order to be able to restore your wallet.

**Comment by rachelcope** [comment]
Here are two initial ways to help make the official MetaMask support link more prominent:

1) Update information architecture/navigation of MetaMask home to include Support links in the top nav
Follow IA/nav discussions [here](https://www.figma.com/file/n7kfyjuFP6QzgAv1tIphuC/Website-IA?node-id=41%3A26) 
cc @cjeria

2) Until we've redesigned the navigation in extension, I proposed that we update the copy/link in the Accounts/Settings menu. 

- Update menu name -> “Support”
- Update icon to chat icon
- Link directly to [support page](https://metamask.zendesk.com/hc/en-us)

[Figma](https://www.figma.com/file/0G8qHtt9ZHMFD8ZP2MstAZ/Account-menu?node-id=7%3A8)

![image](https://user-images.githubusercontent.com/7483074/110529047-02026480-80d6-11eb-9d18-ecfb4892ba53.png)

**Comment by danfinlay** [comment]
I think that proposal is a clear and easy improvement over the status quo, but it's still somewhat tucked away behind an unlabeled menu that some people might not even realize is a menu.

I think it might be worth having a support link available directly on the main account screen, AND on the lock/onboarding screens (since those are screens that are often visible to users who are locked out of accounts).

**Comment by rachelcope** [comment]
@danfinlay That's a good point. I don't think we have real estate for a fixed link on the main account screen (max height is 600%) - until we redesign the navigation. But we could add a footer link under Add Tokens

![image](https://user-images.githubusercontent.com/7483074/110549244-0424ed00-80ef-11eb-8b87-0217a45c7432.png)

**Comment by rachelcope** [comment]
Updated lock screen: 

[Figma](https://www.figma.com/file/dGBIYsYMTWsr8h4NaAT7Pl/Welcome-Screen?node-id=1%3A2)

![image](https://user-images.githubusercontent.com/7483074/110550777-86161580-80f1-11eb-9cf7-88f9d12fe1ee.png)

**Comment by Nanopollinator** [comment]
Hi Rachel,
Thanks so much. Fortunately I wrote the seed elsewhere and it included the
12th word.
I managed to sign into my account but I'm unable to connect from Coinbase
to Meta mask; it says on my mac screen, something like this account is not
recognized. I installed this meta mask extension in 2017 and I read on
reddit lately that I may need to remove the extension and re add. My
concern is I have also red on reddit that funds have or might disappear:)
I'm not tech savvy so I can barely navigate all this.
Do you have any suggestions?

Thanks!
Deirdre

**Comment by danfinlay** [comment]
@Nanopollinator please seek support on [our support website](https://metamask.zendesk.com/hc/en-us) where you can submit an issue. Our GitHub isn't the place to seek support.

**Comment by danfinlay** [comment]
I think those additions look great @rachelcope, thanks for putting them together. I think a dev might ask whether the support link is part of a scrollable section or something, I assume it's fixed at the bottom of the window, since we don't want it hidden when a user first opens the view.

**Comment by rachelcope** [comment]
agree 100%. yep, i think this is ready to go!
