### ISSUE TITLE
Metamask transactions pending...

### ISSUE THREAD

**Issue by bghll** [MetaMask/metamask-extension#10457]
I have 4 transactions pending and I have tried to cancel all of them and then also cancel the latest one with a transaction with a custom nonce matching the latest pending one, and I'm not sure what to do...

Thanks for your help!

**Comment by tmashuang** [comment]
I deleted your state logs for privacy concerns. Your transaction with a nonce of 100 is lower than what the average. You can view common gas prices https://etherscan.io/gastracker and https://ethgasstation.info/. As the issue with "Cancelling" a tx it should be the earliest nonce, not the latest. I am going to close this ticket as there is not technical bug here.
