### ISSUE TITLE
[Crash] when multiple eth_getEncryptionPublicKey called

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#10462]
1. Go to https://lab.miguelmota.com/metamask-encryption-example/public/
2. Click on encrypt, but don't provide public key
3. Click on encrypt second time
4. Click cancel in metamask

**Expected behavior**
Should not crash

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Chrome 88
 - MetaMask Version: 9.0.5

![2021-02-16 11 48 26](https://user-images.githubusercontent.com/9360827/108114115-3e99ed80-704d-11eb-8954-6eec30ddfb4a.gif)

**Comment by Gudahtt** [comment]
Thanks for the report! I was able to reproduce this on Chrome with v9.0.5.

**Comment by danjm** [comment]
This is potentially, but not necessarily, related to  https://github.com/MetaMask/metamask-extension/pull/10326 or https://github.com/MetaMask/metamask-extension/pull/10330, which were shipped in the most recent release.

**Comment by tmashuang** [comment]
Seems that this is closing related to #10231 and resolved by #10350.

**Comment by tmashuang** [comment]
Fixed by #10350
