### ISSUE TITLE
Always Pending Unable to trade

### ISSUE THREAD

**Issue by iDerekLi** [MetaMask/metamask-extension#10474]
Always Pending Unable to trade

<img width="371" alt="WX20210218-195423@2x" src="https://user-images.githubusercontent.com/24502299/108353813-86726d80-7223-11eb-8052-0261de32db0e.png">

**Comment by Gudahtt** [comment]
Sorry you're having issues, but we don't have enough information to help you further, and we don't use this repository for helping with issues like this.

Please contact support by submitting a support request here: https://metamask.zendesk.com/hc/en-us/requests/new
Thanks!
