### ISSUE TITLE
Custom RPC : The endpoint returned a different chain ID: 0

### ISSUE THREAD

**Issue by Myu-Unix** [MetaMask/metamask-extension#10482]
**Describe the bug**

Setting up a custom RPC to point to a Geth 1.9.25 full client (in sync with Ethereum mainnet) yield "The endpoint returned a different chain ID: 0"

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Metamask 9.0.5 -> Custom RPC -> Fill the required fields
2. At field "Client ID", I have set : 1 (Ethereum Mainnet)
3. Error : The endpoint returned a different chain ID: 0

**Expected behavior**

It should work since Geth is in sync. **Somehow it works with a light client but not the full**

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Debian Linux 10.8
 - Hardware Wallet: N/A
 - Browser: Firefox 85.0.2
 - MetaMask Version: 9.0.5

**Comment by tmashuang** [comment]
What are the geth version and command-line options?

**Comment by Gudahtt** [comment]
Possibly related to #9683, if the node doesn't support `eth_chainId`. Support of that methods is currently required for all custom networks.

**Comment by se1k0** [comment]
i have the same problem

Geth VERSION:
1.9.25-stable-e7872729

command-line options:
geth --ropsten --networkid 3 --syncmode fast --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --rpcapi admin,eth,net,web3,personal --cache=2048 --rpccorsdomain "*" --bootnodes "enode://6332792c4a00e3e4ee0926ed89e0d27ef985424d97b6a45bf0f23e51f0dcb5e66b875777506458aea7af6f9e4ffb69f43f3778ee73c81ed9d34c51c4b16b0b0f@52.232.243.152:30303,enode://94c15d1b9e2fe7ce56e458b9a3b672ef11894ddedd0c6f247e0f1d3487f52b66208fb4aeb8179fce6e3a749ea93ed147c37976d67af557508d199d9594c35f09@192.81.208.223:30303"
