### ISSUE TITLE
Collectibles - Icon of _tokenURI (metadata) does not change

### ISSUE THREAD

**Issue by coin77** [MetaMask/metamask-extension#10480]
I added a customised ERC721 collectible to my iOS Metamask wallet. The ERC721 contains a set of status which can change over time. After adding the collectible, the correct icon from the metadata (_tokenURI) shows up. However, once the _tokenURI changes, the icon under "Collectibles" in Metamask does not change.

**Comment by Gudahtt** [comment]
We do not yet have support for collectibles in the MetaMask extension. I'm guessing you're using MetaMask mobile?

Please make an issue here instead: https://github.com/MetaMask/metamask-mobile Thanks!
