### ISSUE TITLE
ERC20 Approval Dialog does not allow setting a custom nonce

### ISSUE THREAD

**Issue by lucasvo** [MetaMask/metamask-extension#10492]
I need to overwrite a transaction with an approval transaction but the extension does not allow me to set a custom nonce becuse the approval dialog doesn't give that option even when the custom nonce setting is enabled.

**Comment by gigilove2001** [comment]
I’m sorry I am very new to this, I didn’t know where the first one went .
What Can I do do ?

**Comment by Gudahtt** [comment]
Thanks for the report! This is a duplicate of #10129 - please follow that issue for updates.
