### ISSUE TITLE
Uncaught TypeError: this.state.work.methods.createWork is not a function

### ISSUE THREAD

**Issue by Heba-blockchain** [MetaMask/metamask-extension#10502]
**Describe the bug**
I am trying to call the public variable "workCount" from a smart contract using web3 

**Steps to reproduce**
const work = new web3.eth.Contract(ABI,Address)
const workCount = await work.methods.workCount().call()

**Expected behavior**
I am expecting this two line of code to return workCount value

Actual behavior: 
The following error is showing to me once i run the application.
Uncaught TypeError: this.state.work.methods.createWork is not a function

**if I change it the code to the following:**
const workCount = await work.methods.workCount.call()

**this error is showing up:**
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined

**Comment by tmashuang** [comment]
What are the packages and their versions and versions being used?

**Comment by Heba-blockchain** [comment]
> What are the packages and their versions and versions being used?

  "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^12.7.0",
    "bootstrap": "^4.6.0",
    "react": "^17.0.1",
    "react-bootstrap": "^1.4.3",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.2",
    "solc": "^0.8.1",
    "uuid": "^8.3.2",
    "uuidv4": "^6.2.6",
    "web-vitals": "^1.1.0",
    "web3": "^1.3.4"

**Comment by Gudahtt** [comment]
Thanks for the report! It sounds like your issue relates to `web3`, your contract, or relates to some other bug in your code. Unfortunately we aren't able to help debug this sort of thing - this repository is just for tracking bugs and enhancements to MetaMask itself.

I'd suggest asking in our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics) or in the [Ethereum stackexchange](https://ethereum.stackexchange.com/) instead. Sorry we weren't able to help!
