### ISSUE TITLE
Speed up button disappeared after replacement transaction underpriced

### ISSUE THREAD

**Issue by blueberry6401** [MetaMask/metamask-extension#10512]
**Steps to reproduce (REQUIRED)**
1. Send a transaction with a low gas
2. Click "Speed up"
3. Use a little higher or equal gas fee.
4. Got Error -31000: replacement transaction underpriced
5. The Speed up button disappeared

**Expected behavior**
That speed up button should still be there! Speed up is just a transaction with the same nonce, is there any reason to hide it? Everytime like that, I have to make another transaction with the same nonce.

**Screenshots**
![image](https://user-images.githubusercontent.com/7337535/108994389-4fda9e00-76ce-11eb-99fd-80bbe4fe19fe.png)

**Browser details (please complete the following information):**
 - OS: Mac 11.2.1
 - Browser: Chrome / Edge 88.0.705.63
 - MetaMask Version: 9.0.3

**Comment by tmashuang** [comment]
Related #9053. Where the steps to reproduce doesn't clearly state the root cause, it is that the sped up tx that error with `replacement transaction underpriced` will prevent further interaction of the original tx.

**Comment by admazzola** [comment]
This issue still happens to me
