### ISSUE TITLE
Custom Token added appears in all custom RPC Network 

### ISSUE THREAD

**Issue by replayfactory** [MetaMask/metamask-extension#10518]
**Describe the bug**
Custom Token added on a custom RPC Network appears in all custom RPC Network

**Steps to reproduce**

1. Add Custom Network RPC
   _name: xDAI Network
   url: https://rpc.xdaichain.com
   chainId: 0x64
   symbol: DAI
   explorer: https://blockscout.com/poa/xdai_

2. Add Custom Network RPC
   _name: Binance Smart Chain
   url: https://bsc-dataseed.binance.org
   chainId: 0x38
   symbol: BNB
   explorer: https://bscscan.com_

3. Select xDAI Network

4. Add a Custom Token
    _token symbol: USDC
    token contract address: 0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83_

5. Switch to Binance Smart Chaine Network

6. Token USDC still appear in list

**Expected behavior**
Custom token should only appear on the RPC network they were created

**Browser details**
 - OS: Windows 10
 - Browser: Version 1.20.108 Chromium: 88.0.4324.182 (Build officiel) (64 bits)
 - MetaMask Version: 9.0.5

**Comment by Gudahtt** [comment]
Thanks for the report! There is a fix already underway for this problem: #10510
