### ISSUE TITLE
Notifications use etherscan instead of chain's block explorer

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#10516]
If you use a custom network such as ETC and your transaction confirms, the popup transaction confirmation will send you to etherscan instead of the appropriate block explorer.

Whereas the link in the transaction list view is correct.

**Comment by Gudahtt** [comment]
Thanks for the report! This was actually fixed quite recently, and will be included in the release that we're preparing right now (v9.1.0). You can see more details here: #5631

Unfortunately the notifications still won't use the custom block explorer if it is specified (instead the notification will not link to any block explorer at all for custom networks), but that is covered under #7864 and is also being actively worked on! Please follow that issue for further updates.
