### ISSUE TITLE
ENS resolution not working with IPNS

### ISSUE THREAD

**Issue by SamueleA** [MetaMask/metamask-extension#10522]
**Describe the bug**
ENS to IPNS name resolution doesn't work properly.
For example, trying to go to uniswap through ENS, which uses IPNS, with metamask won't work: uniswap.eth/ Instead, after a long load, metamask redirects to https://app.ens.domains/name/uniswap.eth instead of redirecting with the contentHash.
The contentHash is indeed properly set up because https://uniswap.eth.link resolves properly.

**Steps to reproduce**

1. Unlock metamask and have mainnet selected.
2. Type uniswap.eth/ in the browser search bar and press enter.
3. After a few seconds of loading, metamask redirects to https://app.ens.domains/name/uniswap.eth

**Expected behavior**
Instead of redirecting to https://app.ens.domains/name/uniswap.eth, metamask should redirect based on the IPNS contentHash such as [address].ipns.dweb.link.

**Screenshots**
![Peek 2021-02-25 13-50](https://user-images.githubusercontent.com/26363061/109202130-a1d40000-7770-11eb-87b4-c75a1699b417.gif)

**Browser details:**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Version 88.0.4324.182 (Official Build) (64-bit) 
 - MetaMask Version: 9.0.5

**Additional context**
The uniswap example is using dnsLink so the ENS app is redirecting to https://app-uniswap-org.ipns.dweb.link/ instead of [public-key].ipfs.dweb.link. That being said the same bug occurs when not using dnsLink. EG: samuelea.eth which on the ENS app resolves to https://k51qzi5uqu5dioykj9txcgydfd7rfuhm7jjdutk5p20uyv8vg9xmbts62yyh6t.ipns.dweb.link/ , but with Metamask resolved to https://app.ens.domains/name/samuelea.eth

Furthermore, I see there is a now closed ticket about this issue: https://github.com/MetaMask/metamask-extension/issues/9037
However, the problem with IPNS and metamask still persists.

**Comment by shaileshahuja** [comment]
Hi this is not working for me too! Any update?

**Comment by gerbz** [comment]
Instead of redirecting to `[address].ipns.dweb.link` I recommend redirecting to `https://uniswap-eth.ipns.dweb.link/` which preserves the ENS domain in the URL.  See #9353
