### ISSUE TITLE
Custom Nonce Setting transfers from mainnet when you switch to a custom network, and gwei estimate also transfers to custom network as well

### ISSUE THREAD

**Issue by AlexHerman1** [MetaMask/metamask-extension#10541]
User experienced this when testing Expanse network. ticket # 90274. 

**Steps to reproduce**

1. Set Custom nonce in eth mainnet
2. Using same account, switch to custom network
3. Nonce will default to setting from mainnet, resulting in stuck txn in the custom network
4. Gas estimate when trying to send a token also transfers from mainnet, resulting in far higher gas fees than needed being the default.

**Expected behavior**
1. Nonce setting should not carry over from mainnet, and should default back to a default setting
2. Gas estimates should not carry over from mainnet for send txns on custom networks

**Screenshots**
![unnamed_attachment_1](https://user-images.githubusercontent.com/38788573/109566561-0b764600-7ab2-11eb-8dae-4e07229768c4.png)

**Browser details:**
 - OS: Windows 10 Pro 20H2
 - Browser: Firefox 86.0 release channel, non-ESR, non-beta channel, updates automatically
 - MetaMask Version: 9.0.5

**Comment by tmashuang** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/10539
> I believe this is fixed by #10528. This also happens on ETC. I believe this issue is caused by grouping txs by net_version, which the PR fixes by grouping by chain id and falling back to net version. There is no migration unfortunately so the txs in history will need to be cleared via Resetting Account as mentioned as a workaround. The PR is included in v9.1.0, I'll comeback to this once it is released.

**Comment by tmashuang** [comment]
Related to #10541.
> I believe this is fixed by #10528. This also happens on ETC. I believe this issue is caused by grouping txs by net_version, which the PR fixes by grouping by chain id and falling back to net version. There is no migration unfortunately so the txs in history will need to be cleared via Resetting Account as mentioned as a workaround. The PR is included in v9.1.0, I'll comeback to this once it is released.
