### ISSUE TITLE
Prevent or warn when sending zero token transactions

### ISSUE THREAD

**Issue by dcts** [MetaMask/metamask-extension#10565]
**Describe the bug**
Sending zero token amounts should not be allowed, or at least there should be a warning alert. Currently it is possible to send zero amounts to other accounts and the UI is not designed to make it obvious, resulting in transactions that are zero but still pay gas fees. 

**Steps to reproduce (REQUIRED)**
1. Open metamask
2. Click on any token with a nonzero balance (e.g. USDT or USDC...)
3. click "send"
4. input target recipient address
5. press send (default value is 0 and no prompt appears warning about sending a zero balance)

**Expected behavior**
The interface should indicate that a zero balance is currently selected. See example:
![Bildschirmfoto vom 2021-03-03 08-14-07](https://user-images.githubusercontent.com/44790691/109767848-716ce580-7bf8-11eb-805b-55cece0eb828.png)

**Browser details (please complete the following information):**
 - OS: Linux Ubuntu 20.4
 - Brave
 - MetaMask Version: 9.0.5

**Comment by dcts** [comment]
Maybe another error like in this [PR](https://github.com/MetaMask/metamask-extension/commit/3c6cdef0747542215b928d9781d3ed1ff3e43d2a) could be a solve? If you think thats reasonable let me know and I can implement this and create a PR.

**Comment by brad-decker** [comment]
@dcts -- at first glance, I like the idea of this error. We'll discuss this with the UX team. There's a legitimate use case for sending 0 ETH to your own account when using the custom nonce feature, to effectively supersede a prior transaction with the same nonce that might have been sent in error. However, to do the same with a token transfer, you'd still send 0 ETH to yourself with the same nonce, so it may make sense to warn users when sending 0 erc20 tokens.

**Comment by sahar-fehri** [comment]
Will close this because a fix was merged : https://github.com/MetaMask/metamask-extension/pull/21091
