### ISSUE TITLE
Stuck in Welcome Back screen. Can't login (Chrome)

### ISSUE THREAD

**Issue by beaverpark** [MetaMask/metamask-extension#10564]
**Describe the bug**
- In my desktop, I can't log in to metamask at the "Welcome Back" screen. 
  - Whenever I type in my password, the screen changes for 0.5 sec as if it will show me the account page and it goes back to the "Welcome Back" page.
  - Whenever I click the metamask extension icon on chrome, it always opens up popup window for 0.5 sec and then the popup disappears and it opens the entire "Welcome Back" screen.
- I know my password is correct because when I type in wrong password, it does tell me "Incorrect Password".
- When I click the "Restore account?" or "Import using account seed phrase" buttons, nothing happens. The screen just resets at the "Welcome Back" page (like the Fox looks to the front again).
- This issue only happens in the last case:
  - laptop (mac) + chrome = works fine
  - desktop (windows) + firefox = works fine
  - desktop (windows) + chrome = **doesn't work** 

**Steps to reproduce (REQUIRED)**
- Url that I am stuck: `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html#initialize/unlock`
- I don't have much other info. I am literally just stuck at the login phase.

**Expected behavior**
- I expect to be able to login successfully and see my account page.

**Screenshots**
- Screen that I am stuck:
![metamask](https://user-images.githubusercontent.com/14043568/109753150-b9b3e580-7baf-11eb-95fc-906297017078.PNG)

**Browser details (please complete the following information):**
- OS: Windows
- Chrome version: Version 89.0.4389.72 (I had same issue with older versions)
- Metamask version: Tried both 9.0.5 and 9.1.0

**Additional context (Error Messages, etc.)**

**Comment by tmashuang** [comment]
Can you open up the developer console and see what errors throwing?

**Comment by beaverpark** [comment]
Sure. Here's the screenshot.
![metamask_error](https://user-images.githubusercontent.com/14043568/110047033-2bf50900-7d1b-11eb-8d25-10717a68cfb1.PNG)

**Comment by tmashuang** [comment]
Is this for the UI? What about for the background?

**Comment by beaverpark** [comment]
Yeah this is for the UI. Can you clarify what you mean by background?
Like **Background Fetch** in **Application** tab?

**Comment by tmashuang** [comment]
For chrome extensions there are two types of processes that can be inspected, UI and Background. To view the background enable `Developer Mode` in the extension list and click the background page in `inspect views background page`. Then try to enter the password to see if any errors are throwing.

**Comment by beaverpark** [comment]
Got it. I am able to open up a separate background page window. But after I open that, when you say enter password, do you mean entering it into the normal window and see if any logs show up in the background page window? 
If that's the case, no background logs show up even after typing password into the normal window. All I see is `Starting background-devtools`.

**Comment by beaverpark** [comment]
^Sorry disregard my previous comment. I was looking at the wrong background page.
This is the background page log I see when I open it.
![metamask_background_page](https://user-images.githubusercontent.com/14043568/110217994-3a5f3400-7e85-11eb-9f61-befa5ec39d65.PNG)

Regarding "trying to enter password" though, do you mean entering it into the normal window and seeing if any log appears in the background page?

**Comment by tmashuang** [comment]
> do you mean entering it into the normal window and seeing if any log appears in the background page?

I mean entering it as you normally would to unlock the extension. 

Can you expand on those errors, as they might be relevant errors being thrown. You should omit any personal information, like your account address, on those errors.

**Comment by danjm** [comment]
@beaverpark Are you still experiencing this issue?

**Comment by beaverpark** [comment]
Hi @danjm  I m no longer having this issue. Thank you.
