### ISSUE TITLE
So yesterday both firefox and metamask got updates, now metamask shows just a blank pop-up window....

### ISSUE THREAD

**Issue by NinjaTurtle007** [MetaMask/metamask-extension#10566]
Not sure which caused it, because both firefox got update from 85 to 86 and the metamask extension. (Ubuntu here)

So, now when i click on metamask i get just a blank white pop-up window.

I see it's known issue here, but no solution so far?

So if there is no solution yet let us know please at least how to access the metamask in it's own tab (extended mode) before entering the password? You can easily get to extended mode once you are logged in, but i can't log-in now, so how to access it before that?

**Comment by tmashuang** [comment]
As there is no particularity new information provided in this issue I am going to close this as a duplicate https://github.com/MetaMask/metamask-extension/issues/9196 and https://github.com/MetaMask/metamask-extension/issues/4894.

**Comment by NinjaTurtle007** [comment]
yes that's why im asking here for at least a way to access metamask expanded version without logg-in in in the pop-up (that doesn't work) first to access it.
I haven't saved the local extension URL, so asking how to find it now when the pop-up doesn't work.

**Comment by tmashuang** [comment]
> yes that's why im asking here for at least a way to access metamask expanded version without logg-in in in the pop-up (that doesn't work) first to access it.

You would need to get the addon uuid from `about:debugging#/runtime/this-firefox` and navigate to `moz-extension://UUID/home.html`. Although if the popup is white screen then navigating to the expanded version will also be white screen.
