### ISSUE TITLE
Error Approving Token

### ISSUE THREAD

**Issue by forwhomthebelltolls** [MetaMask/metamask-extension#10569]
I'm trying to exchange two ERC20 tokens on Uniswap. When I click "Approve", Metamask appears and tells me there's a transaction fee. When I click "Confirm", the Metamask window closes and nothing else happens. The fee isn't take and the "Swap" button does not become available. Later on, I get the following error:

"Transaction NaN failed! Error: Transaction found as "approved" during boot - possibly stuck during signing"

I am using a Ledger Nano S. I have set contract data to allowed in the Ethereum app. I have tried many time in both Brave and Firefox with the same result each time. I can't think of what else to do. Please can someone offer some suggestions? I'm using MetaMask 9.0.5 and Windows 10.

**Comment by brad-decker** [comment]
@forwhomthebelltolls when you click approve, do you get the prompt to confirm the transaction on your Ledger?

**Comment by forwhomthebelltolls** [comment]
No, I don't. I've tried with and without the Ethereum app open.

**Comment by forwhomthebelltolls** [comment]
Weirdly, it's working today. Thanks for the help.

**Comment by AlexJupiter** [comment]
Closing due to the problem seemingly being solved and author not responding to latest question.
