### ISSUE TITLE
Network blocks web3 calls via metamask

### ISSUE THREAD

**Issue by VexyCats** [MetaMask/metamask-extension#10571]
**Describe the bug**

This is an odd one - with it happening to only 0.1% of our users. But for some reason - their network is blocking (I think) web3 calls. Any call to contracts to fetch data from the chain - is not fired. There is no error message, there is no error thrown in the code, it just doesn't go through - as if it was blocked. 

**Steps to reproduce (REQUIRED)**

I wish I could reproduce it - then maybe I could help fix it. 

It only happens to a very small number of users - but whenever our dapp is calling the blockchain - the calls just don't happen. No error, no nothing. Code just stops executing after the call or during the call. 

User has no extensions but metamask. Using latest chrome, American ISP. May or may not be using a VPN - have disabled and try with  and without it on - but still doesn't work. 

Connects wallet to dapp - dapp tries to call the blockchain to fetch simple info - code stops. Nothing happens, nothing is thrown as an error, nothing is returned as a response. Just hangs. 

We do use infura if there is no web3 connection, but after they've connected we should be using their metamask web3 as a provider 

**Expected behavior**
Fetch data from the blockchain, ie: token name. 

**Browser details (please complete the following information):**
 Chrome, metamask, windows. 

I think this is a network issue - but can someone shed some light onto what might be causing this? Like is there a firewall setting that can block web3/RPC calls via metamask? 

Does a VPN do this? ISPs?

**Comment by brad-decker** [comment]
@VexyCats, blocked network requests could be viewable in developer tools. If using chrome in manage extensions one can inspect the background process and look at the network tab to see if any network requests are blocked.

Some questions: 
1. Is this happening on mainnet? 
2. You listed Chrome/MM/windows -- is this consistent with all cases? 
3. Which Dapp(s) is(are) experiencing this issue?

**Comment by VexyCats** [comment]
Thanks @brad-decker 


1. Yes mainnet 
2. Yes except some cases it has persisted upon different PCs on the same network, or using different browsers like opera.
3. Mintable.app 

I don't think its viewable in the dev tools for the site - but I did not look at the network for the background processes. 

I suspect since it persists across computers and browsers for only a few number of users - that it is actually a network/firewall/router issue on their local network. But I'm wondering why???

**Comment by Nanopollinator** [comment]
I'm not a tech person but I think you're talking about the problem I'm having. I'm unable to connect my metamask with my exchange.
Any help would be appreciated.

**Comment by vandan** [comment]
Closing until an example with detailed reproduction steps can be provided.
