### ISSUE TITLE
RPC Error: Request of type 'wallet_requestPermissions' already pending for origin

### ISSUE THREAD

**Issue by ashish-mehta** [MetaMask/metamask-extension#10584]
1) Goto https://docs.metamask.io/guide/getting-started.html#connecting-to-metamask
2) Make sure you are logged out from metamask
3) Enable ethereum
4) Close the metamask window without logging in
5) Open console in developer tools f12
6) Click the enable ethereum again
7) One can see the errors: MetaMask - RPC Error: Request of type 'wallet_requestPermissions' already pending for origin https://docs.metamask.io. 

What to do in this situation?

_Originally posted by @ashish-mehta in https://github.com/MetaMask/metamask-extension/issues/7710#issuecomment-777375323_

**Comment by Gudahtt** [comment]
The request is still pending in this scenario I think? So the user can click on the MetaMask icon in the toolbar and confirm or deny the request.

This problem seems similar to #10085, which we have a planned UX improvement to address: #10302

**Comment by namnm** [comment]
This happens in a case like: 
1. User click on button
2. Call method `eth_requestAccounts`
3. User not click on `Next` or `Cancel`, but click outsite of the popup (they may try to go back to the page)
4. So now the popup is in background, the button stuck in loading state forever. If refresh the browser, the button can be clicked, but it will rejects with the error `Request of type 'wallet_requestPermissions' already pending for origin`. This only works after user manually open the extension via MetaMask icon toolbar and click `Next` or `Cancel` to resolve it from there

Is there anyway to cancel/close the popup programmatically? So that we can use timeout to check and close the pop up from our code?

**Comment by chisqrd** [comment]
is there a workaround in the meantime? i ran into the same situation while trying to deposit some funds into polygon.curve.fi and the interface is coming back with an "Returned error: execution reverted" error. On the console, I can see the following:

MetaMask - RPC Error: Request of type 'wallet_requestPermissions' already pending for origin https://polygon.curve.fi. Please wait.

**Comment by jkirkpatrick** [comment]
Any update? It's been 5 months... I've seen how this built-in behavior of MetaMask causes extremely high levels of attrition and frustration of users on our site

**Comment by Gudahtt** [comment]
This was addressed in #12643

**Comment by ThePrimeagen** [comment]
This same error seems to happen if you do the following actions.

1.  request auth to metamask
2.  Refresh the website which will re-request the auth (but the window is still open elsewhere) which cases the the same error as above.
3. accountsChanged callback will not get called back _UNLESS_ repeating calls to the contract (its extremely odd)

Best work around I have come up with is `await ethereum.request({method: "eth_accounts"})` and wait for the return result to be an array.

```
export async function waitForAccount(): Promise<void> {
    while (true) {
        try {
            const accounts = await getEthereum().request({method: 'eth_accounts'});
            if (accounts.length > 0) {
                break;
            }
        } catch (e) { }
    }
}
```

**Comment by heheiscool** [comment]
> This same error seems to happen if you do the following actions.
> 
> 1. request auth to metamask
> 2. Refresh the website which will re-request the auth (but the meta mask window is still open from previous call) which cases the the same error as above (request in flight).
> 
> There is some interesting side effects from this. event `accountsChanged` will not get called _UNLESS_ repeating calls to the contract (its extremely odd, a while true loop calling eth_accounts will make it work)
> 
> Best work around I have come up with is `await ethereum.request({method: "eth_accounts"})` and wait for the return result to be an array. here is the code

Is a good idea!

**Comment by ProductOfAmerica** [comment]
I found this solution to work perfectly for me, removing the errors:


```ts
'use client';

import {useEffect, useState} from 'react';

export default function ConnectWallet() {
    const [account, setAccount] = useState(null);
    const [isMetaMaskInstalled, setIsMetaMaskInstalled] = useState(false);
    const [isConnecting, setIsConnecting] = useState(false);

    // Check if MetaMask is installed
    useEffect(() => {
        if (typeof window !== 'undefined' && typeof window.ethereum !== 'undefined') {
            setIsMetaMaskInstalled(true);
        }
    }, []);

    // Attempt to connect to MetaMask
    useEffect(() => {
        const connectWallet = async () => {
            if (!isMetaMaskInstalled) return;

            setIsConnecting(true);
            try {
                await window.ethereum.request({method: 'eth_requestAccounts'});
                const accounts = await window.ethereum.request({method: 'eth_accounts'});
                setAccount(accounts[0]);
            } catch (error) {
                console.error("Failed to connect to MetaMask:", error);
                // Handle errors here
            } finally {
                setIsConnecting(false);
            }
        };

        connectWallet();
    }, [isMetaMaskInstalled]);

    return (
        <div>
            {isConnecting ? 'Connecting...' : account ? `Connected: ${account}` : 'Not connected'}
        </div>
    );
}
```

**Comment by Hexi1997** [comment]
same
