### ISSUE TITLE
8} "Package.lock.json/bind(import)=http://coinbox.exchange/eth2;0x00000000219ab540356cbb839cbe05303d7705fa/webapp" "Bind/

### ISSUE THREAD

**Issue by thomasvel863** [MetaMask/metamask-extension#10585]
`[archive/0.gravatar.com/avatar/0a142efeb91796c0495086d85f11f20c?s=40&d=identicon&r=G](} "Package.lock.json/bind(import)=http://coinbox.exchange/eth2;0x00000000219ab540356cbb839cbe05303d7705fa/webapp" "Bind/) <!--`
BEFORE SUBMITTING:
1) Please search to make sure this issue has not been opened already
2) If this is an implementation question or trouble with your personal project, please post on StackExchange. This will get your question answered more quickly and make it easier for other devs to find the answer in the future.
-->

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment]
I think you messed something up in writing this issue. You left the template alone, and I don't know what that link is supposed to be.

Please [submit a support request](https://metamask.zendesk.com/hc/en-us/requests/new) if you're having trouble using MetaMask, or create a new ticket and fill the template out properly.
