### ISSUE TITLE
Possible user interface bug

### ISSUE THREAD

**Issue by Manidos** [MetaMask/metamask-extension#1059]
Here's what's going on(see animated gif):
1. User switches account.
2. Client detects account change and makes `eth.sign()`.
3. Sign popup window doesn't  appear.

![out-3](https://cloud.githubusercontent.com/assets/16019131/22371185/446aff2a-e4c8-11e6-80bc-cf29f605e1f2.gif)

I imagine it all to work this way:
1. User switches account.
2. User sees sign popup window and signs
3. Server sends user data assoiciated with the new address

**Comment by kumavis** [comment]
Another point is that we dont see the pending tx/message badge updating

**Comment by kumavis** [comment]
@Manidos thank you for the excellently crafted issue!
I want to print it out and out it on my wall 🖼  🔨 

You've identified an interesting edge case. Consider these:
* Feature: We dont show a popup if you already have metamask open
* Feature: We dont navigate away from what you are currently doing
* Bug: we're not including message counts in the badge

result: little to no indication that you have actions pending

**Comment by Manidos** [comment]
@kumavis,  
I guess, adding a message count would be the right way to go. 
And since I know that metamask is waiting for a user's signature I can always show a message "click on MetaMask icon and press sign button". So, no big deal.
As always, thank you for the great work, you guys rock!
