### ISSUE TITLE
eth_sendTransaction does not work properly in Ungoogled-Chromium

### ISSUE THREAD

**Issue by lf94** [MetaMask/metamask-extension#10592]
**Describe the bug**

In Ungoogled-chromium, running `ethereum.request({ method: 'eth_sendTransaction', params: [ ... ]})` results in MetaMask never resolving the promise. In regular Google Chrome, this is not the case. I get the regular prompt. This is obviously very weird. 

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go get Ungoogled-Chromium for your platform
2. Go into extensions
3. Enable developer mode
4. Build the latest `dist` on `devel` branch
5. Load the built extension
6. Go to https://docs.metamask.io/guide/sending-transactions.html#example and try it.
7. Open console and try a request there too.

**Expected behavior**

It should prompt you to make a payment, like in Google Chrome.

**Screenshots**

N/A

**Browser details (please complete the following information):**
 - OS: Debian Bullseye
 - Hardware Wallet: N/A
 - Browser: Version 88.0.4324.182 (Developer Build, ungoogled-chromium) built on Debian n/a/testing/unstable, running on Debian bullseye/testing (64-bit)
 - MetaMask Version: `devel` branch on 2021-03-04.

**Additional context (Error Messages, etc.)**

N/A

**Comment by tmashuang** [comment]
If Ungoogled-chromium, a project based off of the Chromium project, is not producing the same result as Chromium then I suggest that the issue should be resolved by Ungoogled-chromium fixing it on their end.
