### ISSUE TITLE
I cannot use the wallet_addEthereumChain method

### ISSUE THREAD

**Issue by liangzai927** [MetaMask/metamask-extension#10596]
![image](https://user-images.githubusercontent.com/48548032/110120230-bd39ad80-7df7-11eb-95a9-b1c96b11b7cd.png)
![image](https://user-images.githubusercontent.com/48548032/110120367-ec501f00-7df7-11eb-8f60-de13684e1b94.png)
This error is prompted when I use the wallet_addEthereumChain method. Is the method I used wrong? How can I solve it? Thank you

**Comment by brad-decker** [comment]
Hi @liangzai927 ! I think the only thing you need to do is provide Params as an array with a single object in it. The object you provided looks correct at first glance!

**Comment by liangzai927** [comment]
Thank you I solved this problem after wrapping with an array. I think the document should be modified.
