### ISSUE TITLE
Add ETH uri support

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1060]
not finalized but worth considering
```
 ethereum:<address>[?value=<value>][?gas=<suggestedGas>][?bytecode=<bytecode>]
```
https://github.com/ethereum/EIPs/issues/67

btc also has one https://www.iana.org/assignments/uri-schemes/prov/bitcoin
and we could send via shapeshift

**Comment by breebeck** [comment]
not fixing this is shit
