### ISSUE TITLE
MetaMask popup visual overflow bug

### ISSUE THREAD

**Issue by Chef-Chungus** [MetaMask/metamask-extension#10609]
**Describe the bug**
Visual overflow occuring in metamask popup when prompting a user to switch network or add new custom network

**Steps to reproduce (REQUIRED)**
PancakeSwap is using the `switch to network` and `add custom network` API on the website for MetaMask browser extension, when these appear, the dialogue doesn't fit inside its' container

**Expected behavior**
No overflow of content

**Screenshots**
![image](https://user-images.githubusercontent.com/71833681/110422208-409e1c00-80e2-11eb-8bed-d2440c7e2dc4.png)

**Browser details (please complete the following information):**
- Chrome 
- MacOS

**Comment by tmashuang** [comment]
Is there a visual alteration to the native resolution either in the browser or OS?
