### ISSUE TITLE
Migrate off 3box

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10608]
3box is being deprecated in favor of [Ceramic Network](https://ceramic.network/). We're only using 3box in an experimental "backup account metadata" feature, but it will become non-functional some time around the end of Q2 2021.

We should move off it. A few options:
- Remove the feature entirely, since it's basically tucked away as an experimental feature.
- Migrate to Ceramic
- Migrate to [Web Native File System](https://github.com/fission-suite/webnative#web-native-file-system), a similar personally-encrypted store on IPFS, but without blockchain checkpointing.

**Comment by danjm** [comment]
Another option is just to allow local backup of data... to the users own file system

**Comment by mcmire** [comment]
One point for removing `3box` is that it seems to be (partially) causing this error that a tiny subset of users see periodically: https://sentry.io/organizations/metamask/issues/2083194222/?project=273505 (some investigation here https://github.com/MetaMask/metamask-extension/issues/7350). `borc` is being used in `js-ipld-cbor`, which is being used by an outdated upstream dependency of `3box`: https://github.com/ipld/js-ipld-dag-cbor/blob/master/src/util.js

**Comment by Gudahtt** [comment]
This was completed in #14571
