### ISSUE TITLE
Nested dependency repo no longer exists -- extension cannot build from scratch

### ISSUE THREAD

**Issue by alex-miller-0** [MetaMask/metamask-extension#10620]
**Describe the bug**

I am unable to build this project without a `yarn.lock` due to a missing dependency:

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/hugomrdias/pull-ws.git
Directory: /<myPath>/metamask-extension
Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

Indeed, this repo is either no longer public or no longer exists: https://github.com/hugomrdias/pull-ws

This is a nested dependency, required by:

```
libp2p-websockets@^0.12.2, libp2p-websockets@~0.12.2:
  version "0.12.2"
  resolved "https://registry.yarnpkg.com/libp2p-websockets/-/libp2p-websockets-0.12.2.tgz#eecf25564cbe6b0e9017bb411c2a8abec8c9f29b"
  integrity sha512-K/Jg/fWFfP5NyiLx01EJcoAcYQO00RSHpZfPQDR3May6ABvOseAjq45SrUDdDCW5mCS0502Vz1VjRrZdOXw8zQ==
  dependencies:
    class-is "^1.1.0"
    debug "^4.1.1"
    interface-connection "~0.3.2"
    mafmt "^6.0.4"
    multiaddr-to-uri "^4.0.1"
    pull-ws hugomrdias/pull-ws#fix/bundle-size
 ```

Which is itself required by `ipfs`, among other things. I stopped digging through the `yarn.lock` file at this point but it looks like ipfs is itself a dependency.

Interestingly, this error was only encountered when I removed my `yarn.lock` file. When I pasted in the one from this repo (via github), yarn seems to skip the error -- the defunct repo is definitely in the `yarn.lock` file I pasted

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Remove `yarn.lock`
2. `yarn` (edit: I see the docs say to run `yarn setup` instead -- this command leads to the same error)
3. No `yarn.lock` file is created and modules are not installed. Above error is printed.

**Expected behavior**

New `yarn.lock` file should be created and modules should be installed.

Since I am able to build with the `yarn.lock` file (i.e from cloned source), this issue isn't a big deal, but I thought it may be useful for you going forward as you may run into it.

**Comment by jacobcantele** [comment]
The yarn.lock file is required here. This is expected behavior.
