### ISSUE TITLE
Integrate PhishFort list into eth-phishing-detect

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10629]
We've been doing work with PhishFort to take down phishing URLs. They have a list we could keep merged into our phishing detection list also, to further enhance it. This card represents the initiative to complete that effort, coordinating with PhishFort, and getting their work continuously integrated into our list.

**Comment by korn101** [comment]
Following and ready to make any provisions the MetaMask team might require from our side at PhishFort. Excited to bring a safer web3 to all!

**Comment by korn101** [comment]
As per email convo to Seth & Jacob:

> We have two avenues to go down with the blacklist integration. Namely:
> 
> 1. Modifying the MetaMask PhishingController to consume from our list as well, and combining both lists into one blacklist on the controller. As far as I can tell this would directly influence and integrate with all other projects that are using your controller (including MM browser and mobile) and automatically come into effect on the next deployment - correct me if I'm wrong on that. Or alternatively,
> 2. Extend your PhishingController in the same way Brave did here, this would make using the PhishFort blacklist optional for projects that use your controllers and doesn't risk any kind of integration woes that might come about from any changes we make in point 1 above but this means that your own implementations (plugin and mobile) would have to import it.
> 
> We would prefer to opt for option 1, but we understand there might be knock-on effects we don't fully understand. It is entirely your choice, please consult with your team and let us know the best way forward. This issue is yet to be assigned. 
> 
> When you have discussed the options above with your core dev team, could you please put us in touch with someone that can help talk us through the integration and act as a point of contact for our devs? 
> 
> Thanks
>

**Comment by korn101** [comment]
PR opened on controllers repo, pending review and comments: https://github.com/MetaMask/controllers/pull/715

**Comment by holantonela** [comment]
Controllers have been updated.
