### ISSUE TITLE
addEthereumChain Remove 'May not specify default MetaMask chain' error

### ISSUE THREAD

**Issue by RomanG11** [MetaMask/metamask-extension#10623]
I'm trying to make something like change network chain request. Everything works correctly, but only with new network IDs.I don't understand the reason why you did this check. If you could remove this, many developers will thank you.

if (CHAIN_ID_TO_NETWORK_ID_MAP[_chainId]) {
    return end(
      ethErrors.rpc.invalidParams({
        message: `May not specify default MetaMask chain.`,
      }),
    );
  }

**Comment by Gudahtt** [comment]
Thanks for the feedback! We are tracking this request here: https://github.com/MetaMask/metamask-extension/issues/10597
I'll close this as a duplicate. Please subscribe to the other issue for updates.
