### ISSUE TITLE
Warn users on custom network form when chain_id matches known one

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10632]
As a user who wants to not get phished,

If I try to enter a custom network with a chainID that is equal to a known one (or one I already have entered), I should get a warning, something like:

- This chain ID is currently used by the _____ network. Transactions sent on this provider will be valid transactions on that network also. If you do not intend to be adding a new connection for that same network, do not add this provider.

**Comment by danfinlay** [comment]
@rachelcope to sanity-check the proposed copy.

**Comment by danjm** [comment]
@danfinlay Is this just meant to apply to the custom network form, or does this also need to be supported when adding a custom network via the api

**Comment by adonesky1** [comment]
@danfinlay ^ I'd assume the answer to @danjm 's question is yes?
