### ISSUE TITLE
eth_sendTransaction does not work properly in Firefox 86 on Ubuntu

### ISSUE THREAD

**Issue by lf94** [MetaMask/metamask-extension#10631]
It looks like https://github.com/MetaMask/metamask-extension/issues/10592 was not isolated to Ungoogle-Chromium.

I don't have any other information as this was given by a third party, but it might be worth looking into!

**Comment by tmashuang** [comment]
> I don't have any other information as this was given by a third party, but it might be worth looking into!

Will do will reopen when more information is found.
