### ISSUE TITLE
Clean Import from Seed Phrase Creates Second Account + Account Not Marked as Imported

### ISSUE THREAD

**Issue by adraffy** [MetaMask/metamask-extension#10637]
**Describe the bug**
"No, I already have a seed phrase" creates an additional account.

For reference, importing after "Yes, let’s get set up!" works completely differently.

**Steps to reproduce (REQUIRED)**
1. install Metamask for Firefox
2. "No, I already have a seed phrase"
3. Enter seed phrase
4. Proper Account 1  + new account "Account 2" of unknown address

**Expected behavior**
"No, I already have a seed phrase" shouldn't create a dummy account.

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser:  Firefox Browser 86.0 
 - MetaMask Version: 9.1.1

**Comment by tmashuang** [comment]
Imported accounts are not part of the 12 word mnemonic hd tree and cannot be backed up with that method. Imported accounts are backed up by the way they are import either via private key or json file.
