### ISSUE TITLE
Transaction Keeps pending

### ISSUE THREAD

**Issue by asuib515** [MetaMask/metamask-extension#10649]
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

Hello. I was swapping to TELCOIN over a week ago and it is still "pending". My transaction is 0xc434cb7e0e948cb3430ad3a42d0c08a57dc172b0537fda246d695dcb3fbdebce

Also meta mask is now telling me I am not connected to the network

**Comment by tmashuang** [comment]
Can you provide any additional information on this issue?

**Comment by asuib515** [comment]
Yes so I made 3 swaps. All for telcoin. Two of them went through. one of
them was stuck on pending and then has now been dropped as you pointed out.
I included the transaction number for the swap in the initial email. No
etherium has returned. I was having network issues so I uninstalled
metamask and reinstalled. It connected me to the network but now depending
swap is completely gone. It's disappeared. A couple hundred dollars worth

**Comment by asuib515** [comment]
Hello hello

**Comment by tmashuang** [comment]
> Two of them went through. one of
them was stuck on pending and then has now been dropped as you pointed out.
I included the transaction number for the swap in the initial email. No
etherium has returned.

Did the value of the `dropped` transaction get removed from your balance?

> I was having network issues so I uninstalled
metamask and reinstalled. It connected me to the network but now depending
swap is completely gone.

When you reinstall applications usually the data is lost from the previous session.

**Comment by asuib515** [comment]
Yes. When I initiated the swap the value was removed. In was pending for
days, then became dropped and the value never came back.

**Comment by tmashuang** [comment]
Is your balance of `0.005941531141544506` incorrect in the application?

**Comment by asuib515** [comment]
That is what it shows in my account. But it should be more considering I
had a dropped swap that didn't go through.

If you look at the attachments. I spent 447.64 for eth on transak. After
fees. If you look at my swaps. One swap was 111.8425 in ETH to TEL. The
second one was 164.83793 in ETH to tell. As you can see that doesn't come
close to the amount I had before the swaps. I had a third swap that was
dropped and it didn't come back. I will attach the swap screenshot as well.

**Comment by tmashuang** [comment]
> That is what it shows in my account. But it should be more considering I
had a dropped swap that didn't go through.

That's not how dropped transactions work. The value of `dropped` transactions aren't taken in those transactions, if the balance is correct this is not an issue.

> If you look at the attachments.

I don't see any of these attachments you are referring to.

> If you look at my swaps. One swap was 111.8425 in ETH to TEL. The
second one was 164.83793 in ETH to tell.

I believe there is some type of misinformation going on since the address in question has never had more than 1 ETH as a balance

**Comment by asuib515** [comment]
I bought a little less the 500 dollars worth of ETH. You can see that. You
can also see the two swaps for TEL and how much I swapped. You can also see
there would have been a left over amount. But I swapped tha as well. I
included the transaction number for the swap. It was pending then dropped.
So when you look at the numbers you should see I should have that amount in
eth because the swap was dropped.

Transactions show I bought a little less then 500 dollars worth of eth. Did
two swaps. The third was dropped. You can see the transaction with the
transaction I included. Where would it have gone. If somehow there's
Misinformationv please let me know. Because I had almost 500 worth of eth
and now I have less then 300 worth of Telcoin......

**Comment by tmashuang** [comment]
Is your balance of `63,642.13` of Telcoin not correct?

**Comment by asuib515** [comment]
It would have been more but one of my transactions dropped and the ETH
never came back. Someone from Metamask told me to contact uniswap.

**Comment by tmashuang** [comment]
If your ETH balance and TEL token balance is correct in the block explorer and within the application, are you saying that the consensus algorithm used to determine those values in the blockchain is incorrect?

**Comment by asuib515** [comment]
I'm not saying it's incorrect. I'm it would be more of the third one was
completed. Look at the amount of of money I deposited for ETH. Look at the
amount of eth I swapped. You don't see that their should be a remainder?
That remainder was used for another swap.
