### ISSUE TITLE
Allow dismissing seed backup reminder

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10660]
<img width="341" alt="Screen Shot 2021-03-16 at 12 44 25 PM" src="https://user-images.githubusercontent.com/542863/111381289-bebe6d80-8662-11eb-8cd2-8074b01fd80e.png">

Our current seed backup reminder is useful for some users, but others want to just be left alone, they know what they're doing (maybe they're using a hardware wallet as their primary account).

We might want to provide a dismiss button, (maybe with some extra friction, really making sure the user knows what they're doing), to allow skipping this for longer periods of time, or MAYBE even indefinitely.

**Comment by danjm** [comment]
Note for developers: this happens after selecting the "Remind me later" option on the seed phrase backup screen during onboarding. You have to have eth in a mainnet address for this to happen.

**Comment by danjm** [comment]
If a flag needs to be added, use the `appState` controller

**Comment by danjm** [comment]
Instead of editing the button, lets add a toggle in settings

**Comment by adonesky1** [comment]
@danjm @rachelcope are we thinking that this toggle should live in the advanced settings?

**Comment by adonesky1** [comment]
> If a flag needs to be added, use the `appState` controller

@danjm would it not make sense to have the flag on the preferencesController?
