### ISSUE TITLE
GoChain Network  and assets went missing after reinstallation of Metamask mobile and browser extension

### ISSUE THREAD

**Issue by VechainCowboy** [MetaMask/metamask-extension#10667]
Will<!--
BEFORE SUBMITTING:
1) Please search to make sure this issue has not been opened already
2) If this is an implementation question or trouble with your personal project, please post on StackExchange. This will get your question answered more quickly and make it easier for other devs to find the answer in the future.

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by tmashuang** [comment]
Any additional information?

**Comment by jacobcantele** [comment]
Hi friend, it sounds like you reimported from your seed phrase. You'll need to re-add your custom network (Go Chain) and any custom tokens in order to see those assets. Please seek support on our support community, community.metamask.io rather than reporting a bug here.
