### ISSUE TITLE
Incorrect gas estimation when sending ETH to fallback function of contract

### ISSUE THREAD

**Issue by junderw** [MetaMask/metamask-extension#10668]
**Describe the bug**
When sending ETH to a proxy contract that forwards the ETH through two other accounts (using two CALLs), the gas estimation does not budge from 21000 and users are getting out of gas errors.

Running the following:
```js
await web3.eth.estimateGas({ to: '0x4634661e21759e093a5731d48435C82bb97c53a4', value: '10000000000000000' })
```
or
```js
await (async function() {
    const { ethereum } = window;

    if (ethereum.chainId !== '0x1') throw new Error('Must be mainnet');

    const method = 'eth_estimateGas';
    const params = [
        {
            to: '0x4634661e21759e093a5731d48435C82bb97c53a4',
            value: '0xde0b6b3a7640000', // 1 ETH
        }
    ];
    const gasHex = await ethereum.request({ method, params });

    const gasInt = parseInt(gasHex.replace(/^0x/, ''), 16);

    return gasInt // returns 40872
})();
```
... gives a result of 40872. This should be automatically used, but it is not.

**Steps to reproduce (REQUIRED)**

1. Attempt to send >= 0.001 ETH to 0x4634661e21759e093a5731d48435C82bb97c53a4
2. Wait a few seconds, notice the gas is still 21000
3. Click send to see the confirmation screen, it is still 21000
4. DO NOT ACTUALLY SEND. :-)

**Expected behavior**
The gas limit should automatically be set to 40872

**Browser details (please complete the following information):**
 - OS: Linux
 - Hardware Wallet: None
 - Browser: Chromium 89.0.4389.82 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 （64 bit)
 - MetaMask Version: 9.2.0

**Comment by tmashuang** [comment]
Web3 provider has been remove please refer to [MetaMask Docs Ethereum Provide API](https://docs.metamask.io/guide/ethereum-provider.html#ethereum-provider-api). If your contract requires that much gas then within the transaction parameters you can set the `gas` as such.

**Comment by junderw** [comment]
FYI Ran this with mainnet selected on a metamask installed profile... still got the 40872 answer.

```js
await (async function() {
    const { ethereum } = window;

    if (ethereum.chainId !== '0x1') throw new Error('Must be mainnet');

    const method = 'eth_estimateGas';
    const params = [
        {
            to: '0x4634661e21759e093a5731d48435C82bb97c53a4',
            value: '0xde0b6b3a7640000', // 1 ETH
        }
    ];
    const gasHex = await ethereum.request({ method, params });

    const gasInt = parseInt(gasHex.slice(2), 16);

    return gasInt // returns 40872
})();
```

**Comment by junderw** [comment]
Looking here, it should throw an error if you add hex data to a non-contract address.

So to check whether this code is being run (aka, it's incorrectly being seen as SENT_ETH type.)

If I do:
1. write 0x01 in hex data field
2. Then delete hex data field

Then the gas limit used is 61308

But if I add `data: '0x01'` to the estimation code above, I get an error that EVM reverted.

So it looks like whenever sending ETH with empty data field, the extension will never run estimateGas against it, even if the address has EVM code living on it.

https://github.com/MetaMask/metamask-extension/blob/76a2a9bb8b6ea04025328d36404ac3b59121dfc8/app/scripts/controllers/transactions/index.js#L341-L377

**Comment by junderw** [comment]
From a cursory glance of the code, it should work. It checks the type of tx by looking at whether code exists or not.

If it exists, then it should run estimateGas...

But it's not.

I think maybe this has something to do with the frontend code calling something lazily?...

**Comment by junderw** [comment]
I wonder if this will be affected by any planned switch to use `eth_createAccessList` post-Berlin.

**Comment by junderw** [comment]
bump ?

**Comment by junderw** [comment]
FYI after Berlin the estimate is `46632`

**Comment by junderw** [comment]
Will the underlying API for Metamask support eth_createAccessList?

**Comment by junderw** [comment]
Hi @danjm thanks for the tags.

Just wondering what info is needed?

**Comment by christsim** [comment]
I'm having a very similar issue using the chrome extension.  Not sure if it's related or if i need to create a new issue. 

It works fine using the ios or android application.  When metamask (v9.8.2) tried to estimate the gas for sending eth to the following contract:
Failed TX: https://rinkeby.etherscan.io/tx/0xb71878c6dd2b80cec167130761e34ff939363df044a0ce58e1c8ec46334e663b
Successful TX: https://rinkeby.etherscan.io/tx/0x7de57ed16f213ff5d629ad084648c07073f57e5e0fe0311a84c1515dc6259120

Metamask estimated 34261, while it should estimate something greater than 40828
![image](https://user-images.githubusercontent.com/28301107/126911706-1b7f6ed4-6776-4ee6-b3f5-1d222b82d954.png)
