### ISSUE TITLE
ETH contract approval makes extension stuck in loading screen

### ISSUE THREAD

**Issue by sryavuz** [MetaMask/metamask-extension#10679]
**Describe the bug**
Metamask extension gets stuck when ETH contract is being approved in BSC network. The loading wheel appears and never goes away.
Also it gives another error when the ETH is being sent and does not calculate the value.
After the extension becomes unusable; closing and opening, restarting the browser, disabling, and enabling doesn't work. Only way to make extension work is, disable/enable and before entering the password, changing the network. When I switch to Ethereum network and enter the password, extension opens normally. I can switch to BSC too. However, the problem happens when I try to approve ETH again.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to https://pancakeswap.finance/ and buy some ETH.
2. Select ETH as `from` token
3. Click Approve ETH
4. Metamask stucks.

**Expected behavior**
Confirm/Reject screen should appear and the user should be able to approve or reject the transaction.

**Screenshots**
<img width="360" alt="metamask_error_1" src="https://user-images.githubusercontent.com/1132534/111840434-71195d80-890d-11eb-9f92-ad495c91e9b5.png">
![metamask_error_2](https://user-images.githubusercontent.com/1132534/111840488-82626a00-890d-11eb-9075-22859d45cbe8.jpg)

**Browser details (please complete the following information):**
 - OS:  MacOS Catalina 10.15.7
 - Browser: Chrome Version 89.0.4389.90 (Official Build) (x86_64)
 - MetaMask Version: 9.2.0

**Additional context (Error Messages, etc.)**
Console errors upon restarting Metamask:
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/ui.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```
and
```
ui.js:81 Uncaught (in promise) Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32602,"message":"invalid argument 0: hex string has length 0, want 40 for common.Address"}}}'
at ui.js:81
```

Console Error messages when trying to send ETH to another address:
```
"[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"gas required exceeds allowance (28500000) or always failing transaction"}}}'"
```

**Comment by Worldstar441** [comment]
Im using Chrome and having the same issue

**Comment by vanities** [comment]
Firefox Nightly: `88.0a1 (2021-03-21) (64-bit)` on MacOS and having this issue as well.

**Comment by WoeOm** [comment]
Ropsten Uniswap - Add Liquidity - approve ERC20 token having the same issue.

macos - metamask v9.2.0

**Comment by wenshenjun** [comment]
Same issue, any idea?

**Comment by ricardo-iov** [comment]
Yes, I'm having the same issue since last week

**Comment by WoeOm** [comment]
> Ropsten Uniswap - Add Liquidity - approve ERC20 token having the same issue.
> 
> macos - metamask v9.2.0
> 
> Mainnet is fine.


Ropsten Uniswap - Add Liquidity - approve ERC20 token having the same issue.

https://etherscan.io/token/0x9469d013805bffb7d3debe5e7839237e535ec483.  approve RING having same issue in Mainnet

**Comment by danjm** [comment]
this was resolved with v9.2.1

**Comment by brunoe90** [comment]
I have the v9.3.0 and the problem continues. Same as the OP :

Go to https://pancakeswap.finance/ and buy some ETH.
Select ETH as from token
Click Approve ETH
Metamask stucks.

I use google chrome. The chrome developer console show this when you approve a Swap:

MetaMask - RPC Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}' {code: -32603, message: "Error: [ethjs-query] while formatting outputs from…e":-32000,"message":"transaction underpriced"}}}'"}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17
async function (async)
_processRequest @ inpage.js:17
_handle @ inpage.js:17
handle @ inpage.js:17
_rpcRequest @ inpage.js:1
(anonymous) @ inpage.js:1
request @ inpage.js:1
(anonymous) @ web3-provider.ts:73
value @ web3-provider.ts:125
(anonymous) @ json-rpc-provider.ts:188
Promise.then (async)
value @ json-rpc-provider.ts:177
value @ json-rpc-provider.ts:249
(anonymous) @ index.ts:341
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
o @ 3.6cfd7b4b.chunk.js:2
Promise.then (async)
u @ 3.6cfd7b4b.chunk.js:2
(anonymous) @ 3.6cfd7b4b.chunk.js:2
C @ 3.6cfd7b4b.chunk.js:2
(anonymous) @ 3.6cfd7b4b.chunk.js:2
(anonymous) @ useApproveCallback.ts:83
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
Je @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Or @ react-dom.production.min.js:100
Sr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Fe @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Lr @ react-dom.production.min.js:105
Yt @ react-dom.production.min.js:75
$t @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ji @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Wt @ react-dom.production.min.js:73
useApproveCallback.ts:93 Failed to approve token {code: -32603, message: "Error: [ethjs-query] while formatting outputs from…e":-32000,"message":"transaction underpriced"}}}'", stack: "Error: Error: [ethjs-query] while formatting outpu…e":-32000,"message":"transaction underpriced"}}}'"}

**Comment by Garito** [comment]
Any advance with that?
It doesn't work at all in several networks (I've tested ropsten, rinkeby and binance test net)
This makes a lot of dapps useless...
