### ISSUE TITLE
eth_requestAccounts returns an address with all lowercase; MetaMask expects otherwise.

### ISSUE THREAD

**Issue by lf94** [MetaMask/metamask-extension#10671]
**Describe the bug**
When trying to send a transaction using the first address given from MetaMask, it says the address is invalid.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Generate an address with lower and uppercase letters in MetaMask.
2. Use eth_requestAccounts to get the first account
3. Use this account for eth_sendTransaction
4. MetaMask says it's not a valid Ethereum address

**Expected behavior**

MetaMask should return the address with no modifications, as it is shown in the UI.

**Screenshots**

![1616094813](https://user-images.githubusercontent.com/547923/111686010-f104d200-87fe-11eb-980b-440ae8107b4d.png)

**Browser details (please complete the following information):**
 - OS: Debian Bullseye
 - Hardware Wallet: N/A
 - Browser: Firefox 78.7.0esr (64-bit)
 - MetaMask Version: 9.2.0

**Additional context (Error Messages, etc.)**
This was related to the two other issues I opened a couple weeks ago which were closed. I decided to put some time aside today to really track down the issue. I would rather someone familiar with the MetaMask codebase to submit a PR than myself.

Issues caused by this which I opened:
* https://github.com/MetaMask/metamask-extension/issues/10592
* https://github.com/MetaMask/metamask-extension/issues/10631

**Comment by tmashuang** [comment]
Error actually states  `Invalid parameters: must provide an Ethereum address.`, which describes a missing parameter. How are you constructing the `eth_sendTransactions` request parameters?

**Comment by lf94** [comment]
`request({ method: 'eth_sendTransaction', params: [{ from, to, amount }] })` where from and to are the addresses and amount is a hex string.

**Comment by tmashuang** [comment]
> Is there a reason for me to have written the steps to reproduce?

Yes, because it is required to speed up, prevent friction, in the initial debugging processes of the issue.

>  Are you asking because it's been tried?

Depends on the your definition of "tried". The initial reproduction steps were so broad that it can be interpreted and implemented in a number of ways.

> request({ method: 'eth_sendTransaction', params: [{ from, to, amount }] }) where from and to are the addresses as hex strings and amount is a hex string too.

I am getting the error `Uncaught ReferenceError: request is not defined` in my developer console when trying to reproduce your snippet. I don't believe `amount` is a valid parameter for `eth_sendTransaction`. Please refer to [MM Docs Sending Transactions](https://docs.metamask.io/guide/sending-transactions.html#sending-transactions).

This snippet seems to work.
```
from = ethereum.selectedAddress
to = ethereum.selectedAddress
value = '0x5af3107a4000'
await ethereum.request({
	method: 'eth_sendTransaction',
	params: [{from, to, value}]
})
```

**Comment by lf94** [comment]
I thought as a maintainer you were familiar with the API. Yes you can call `request` on the `ethereum` or `web3.currentProvider` objects on the `window` object.

You did not follow the steps. You need to use `eth_requestAccounts` to get the first account.

**Comment by tmashuang** [comment]
> You did not follow the steps. You need to use eth_requestAccounts to get the first account.

Can you provide the snippet you are using for this? And how you are setting the from address?

**Comment by lf94** [comment]
I'm presuming your example works because `selectedAddress` is not manipulated, whereas `accounts[0]` is.

Since you've shown using the former works, and that I'd have to wait for a merge for proper behavior when the latter is used, and wait for people to update, I'll use the former. Feel free to close this issue if you think this case is intended behavior.

I'm setting the `from` address using the account returned by `eth_requestAccounts`. I've said this in the instructions.

**Comment by steveDL** [comment]
Was there any update here I am struggling with this same issue as  `eth_requestAccounts ` returns only lowercase?

**Comment by tcrognon** [comment]
This shouldn't be closed. This issue is that `await ethereum.request({ method: "eth_requestAccounts" })` lowercases the addresses before returning them. Why doesn't it return the mixed-case, EIP-55 formatted address shown in the MetaMask UI? That's the safe format.

**Comment by rbeer** [comment]
Seeing one thing in the Matamask UI and having another returned is indeed very confusing. Just spent about an hour, thinking that this was done in my code.

**Comment by swenceslao** [comment]
> Seeing one thing in the Matamask UI and having another returned is indeed very confusing. Just spent about an hour, thinking that this was done in my code.
> 
> The `web3.eth.getAccounts();` suggestion throws a deprecation error, pointing to https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3.
> 
> If you really want to use the mixed-case "checksum address", your library should have a util function to convert any address to such a checksum address, e.g. [with ethers.js](https://docs.ethers.io/v5/api/utils/address/#utils-getAddress):
> 
> ```js
> const { utils } = require('ethers');
> const address = '0x63c4393693af799109df135be8afb8044ba0a581';
> utils.getAddress(address);
> '0x63c4393693aF799109Df135be8afb8044BA0A581'
> ```
> 
> Here is the standard implementation: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md#implementation

This worked for me. Cheers.

**Comment by ChristopherTrimboli** [comment]
Thanks, I had this issue too, fixed using ethers. 
Issue should not be closed I feel.

`await ethereum.request({ method: "eth_requestAccounts" })`  is still lowercase for me... I thought checksums were spec? why remove the checksum? I see 0 benefit to doing so and just creates bugs / confusion. Now we need to import another library just to have normal ETH spec? Please elaborate why this is implemented like such.

**Comment by mrcesc0** [comment]
Is there any news on "eth_requestAccounts"? Why should I install another library only to get the the correct address? :(

**Comment by Sengulair** [comment]
Any updates on lowercase letters?
