### ISSUE TITLE
Tx dropped in etherscan and pending in Metamask extension without gas refund

### ISSUE THREAD

**Issue by CPerezz** [MetaMask/metamask-extension#10686]
**Describe the bug**
A transaction that has been `dropped` is still marked as `Pending` in the extension.

**Expected behavior**
I would expect that either there's an update in the logs of the transaction so that it can be seen that is dropped. Or I simply get the gas refunded and I can do the tx again.

**Browser details (please complete the following information):**
 - Browser: Mozilla Firefox 83.0b1 
 - MetaMask Version: 9.2.0

As a user, I'm I supposed to do anything here? Just wait? I would appreciate that when this happens there's a bit more feedback for the user other than just the Tx still pending. And also, if the extension is aware of this `drop`, I would also show something in the logs.

If is helpful, here is the TxHash: 0xe119e645e144c9971f609c1e84178dbeffd81be1fbd7014a647551135bdff85a

Thanks for your time and work.

**Comment by tmashuang** [comment]
Seems that these type of phenomenons where the transaction was recognized by some nodes and "forgotten", when `eth_getTransactionByHash` returns `null` with a valid tx hash, by other nodes. I don't know if we account for these types of situations and transition those transactions from a `pending` state, or continuously wait for a response (which seems to be the case that is described in this issue). 

As for the gas refund, this is not a fee wallets take, it is provided to the miners.

**Comment by CPerezz** [comment]
Thanks for the reply @tmashuang .

Just to completely understand, what should I do as a user to not cause any extra malfunction to the wallet status? Ie. Nonces don't get crazy or any similar thing?

Am I supposed to just wait and the tx at some point will be executed? Will speed it up help on any sense? Since while the ETH spent on fees doesn't appear on my wallet, the tokens that I transacted are still there. So TBH is a bit confusing to understand which is the status of this entire operation.

**Comment by tmashuang** [comment]
If the transaction is still pending within the application, but the nodes have forgotten the tx, I would suggest to `Reset Account` within `Settings > Advanced`. The `Reset Account` feature will clear the entire local transaction list and recalculate the appropriate nonce from the network, which in your case should be the correct one without the `dropped` transaction.

**Comment by JODIN1727** [comment]
How to resolve the issue!? Kindly advise

**Comment by mmiguerodriguez** [comment]
> How to resolve the issue!? Kindly advise

Replace the transaction with a new one with the same nonce as the Dropped (& not replaced) transaction

This should change to a higher severity, since users end up having pending transactions with higher nonce that will never be mined due to not having mined a transaction with lower nonce (which is the one that was Dropped & NOT Replaced.

@danjm

**Comment by CPerezz** [comment]
Hope to see a solution to this landing soon. I solved my problems. But have the feeling that can be a really complex issue to solve for newcomers that don't use GH or don't know much about the tech they're using.

Thanks for your work anyway, I highly appreciate it!

**Comment by mmiguerodriguez** [comment]
> Hope to see a solution to this landing soon. I solved my problems. But have the feeling that can be a really complex issue to solve for newcomers that don't use GH or don't know much about the tech they're using.
> 
> Thanks for your work anyway, I highly appreciate it!

It is actually complex for someone to explain what is happening, and how to fix it. For someone expecting a behaviour of sending transactions and having this issue in which transactions get stuck is really frustrating. 

Being a developer helps you understand what's happening, but for a regular blockchain user this needs to be fixed.
Hoping for an answer of the devs or if someone is able to investigate and make a PR would be cool.

**Comment by CPerezz** [comment]
I'm not sure this was ever addressed. Should this remain closed @tmashuang ?
