### ISSUE TITLE
ETH logo displays in all alternative networks for the default token.  

### ISSUE THREAD

**Issue by AlexHerman1** [MetaMask/metamask-extension#10693]
<img width="361" alt="Screen Shot 2021-03-22 at 1 27 41 PM" src="https://user-images.githubusercontent.com/38788573/112032216-87dcd180-8b12-11eb-9d8a-e1e30f3101a1.png">
<img width="359" alt="Screen Shot 2021-03-22 at 1 27 29 PM" src="https://user-images.githubusercontent.com/38788573/112032218-88756800-8b12-11eb-85bb-46760521329c.png">

This leads to a lot of user confusion and tickets in regards to usability of custom/alternative networks.

**Comment by shesmu** [comment]
Looks like this issue is resolved. At least for BNB https://github.com/MetaMask/metamask-extension/commit/b2f6aa9f655e5e54556154d5815eebcf3d7cd24b

**Comment by jacobcantele** [comment]
Indeed, this issue was already  resolved.
