### ISSUE TITLE
'Recipient address is invalid' error when resolving ENS name set to a valid Ethereum address

### ISSUE THREAD

**Issue by makoto** [MetaMask/metamask-extension#10691]
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Metamask, select "Mainnet"
2. Click on 'Send', type "deathbeach.eth", and pick the address which comes up.

**Expected behavior**

There should be no error message, but instead, it shows `Recipient address is invalid`.
However, if you copy&paste the resolved address (0x28efaf6cab2b5b848778647c95bf256ce3ba3b8d) then it does not show any error.

<img width="355" alt="Screenshot 2021-03-22 at 16 01 21" src="https://user-images.githubusercontent.com/2630/112020046-f37d6980-8b27-11eb-9179-bb64f1485ea8.png">

**Screenshots**

<img width="258" alt="Screenshot 2021-03-22 at 15 30 13" src="https://user-images.githubusercontent.com/2630/112020065-f8421d80-8b27-11eb-9fae-e5bced2e1139.png">

**Browser details (please complete the following information):**
 - OS: [e.g. OS X]
 - Browser: Version 89.0.4389.90 
 - MetaMask Version: 9.2.0

**Additional context (Error Messages, etc.)**

I am a Dev at ENS team and this is based on the report raised by our user and I was able to replicate the same issue.

**Comment by tmashuang** [comment]
Is this an intermittent issue, does this happen after retrying multiple times? I was not able to reproduce.

![image](https://user-images.githubusercontent.com/13376180/112025783-c06cb300-8af2-11eb-8ff5-44f29decbd20.png)
