### ISSUE TITLE
How to disconnect metamask

### ISSUE THREAD

**Issue by liangzai927** [MetaMask/metamask-extension#10697]
![metamask](https://user-images.githubusercontent.com/48548032/112089349-6d672e80-8bcc-11eb-95c5-4824efc992f9.gif)

How can I realize the disconnection operation in the animation?

**Comment by tmashuang** [comment]
> Duplicate of #8990, #8990 (comment) is a potential workaround. If there is an additional scenario that is not captured within the discussion in that issue, feel free at reference that issue in a new issue and describe the additional need/use case for this particular feature.

This is the same issue as #10685 which is also opened by @liangzai927. Please cease duplicating issues.
