### ISSUE TITLE
Wallet Extension Not Loading

### ISSUE THREAD

**Issue by cb1629966** [MetaMask/metamask-extension#10696]
**Describe the bug**
When clicking on the MetaMask extension symbol the typical pop-up occurs, but remains blank. The sign-in page does not show, nor does the wallet page. This issue has been mentioned before, but a significant amount of time has passed since, and supposedly that occurrence has been resolved.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Add extension to Firefox browser. (Firefox 86.0.1 64-bit)
2. Click extension icon (fox face)
3. Wait for popup
5. Attempt to restart browser
6. Repeat steps 2 & 3
7. See error remaining 

**Expected behavior**
Typically upon clicking the icon, the popup would occur and show a landing page where your wallet password is requested. Unfortunately there currently is no show of such a page.

**Screenshots**
Photo can be found on this Google Doc: https://docs.google.com/document/d/12EgrtauyUwdmO3NKBDwmB5SxCh4NYFjll5MntXWQzMM/edit?usp=sharing

**Browser details (please complete the following information):**
 - OS: Windows10
 - Hardware Wallet: Web Wallet
 - Browser: Firefox 86.0.1 64-bit
 - MetaMask Version: Pull #10606

**Additional context (Error Messages, etc.)**
This all occurred after Restoring Previous Session on Firefox; I have closed and restarted Firefox since though. I am next going to try restarting the entire computer and hope this is resolved with that action. However, even if this does the trick, I still am submitting this issue for the benefit of others who may not be able to resolve.

**Comment by tmashuang** [comment]
> This issue has been mentioned before, but a significant amount of time has passed since, and supposedly that occurrence has been resolved.

Which issue are you referring to? There are a number of open issues regarding white/blank screens such as #4894 and #9196 since root cause is still undetermined.

**Comment by cb1629966** [comment]
Idk I just saw one but it was from over a year ago.

**Comment by cb1629966** [comment]
Thanks. I assume you solved (or offered a previous solution) for the issue
beforehand, and didn't just close it without having put forth any effort
for those experiencing such an issue, right? Cuz to close it without any
solution would be very unhelpful and dick-ish....

**Comment by tmashuang** [comment]
This is not the reason I closed it. There is no additional information you've provided in your issue that differs from #4894 and #9196. If those issues are open then the issue hasn't been resolved.

**Comment by cb1629966** [comment]
Oh. I wasn't aware those issues were recent and applicable. Thank you then.

**Comment by cb1629966** [comment]
Hey man, can you check out my comment? I just added a comment to #9196
after you closed my Issue, but now I am having even more trouble (after
uninstalling and reinstalling the MetaMask add-on in Firefox). Here is a
link to the Issue, and mine is like the last comment now....

https://github.com/MetaMask/metamask-extension/issues/9196

Thanks for all your help....
