### ISSUE TITLE
Infinite spinner with certain transactions

### ISSUE THREAD

**Issue by everettwho** [MetaMask/metamask-extension#10705]
**Describe the bug**
In some cases, requesting confirmation for transactions results in an infinite spinner in the wallet. Enabling + disabling the extension doesn't clear the issue, and neither does restarting the browser. The wallet has to be re-imported to clear the spinner.

Screenshot:
![image](https://user-images.githubusercontent.com/6676379/112271808-9e7d4880-8c38-11eb-8291-04b647cfdc2d.png)

**Steps to reproduce (REQUIRED)**
The app is in closed alpha so it'll be difficult to provide exact reproduction steps. I did notice in the DevTools, there are a lot of errors like this: `error: {code: -32000, message: "execution reverted"}`. 

Screenshot: 
![image](https://user-images.githubusercontent.com/6676379/112271974-d2586e00-8c38-11eb-807b-32b290e06eee.png)

I can provide access to the alpha if that's helpful for reproducing the error.

**Expected behavior**
Based on the errors, I'm assuming there might be something wrong with the transaction I'm sending. However, I haven't encountered this issue on any other wallets, including MetaMask Mobile. The transaction works without any problems or infinite spinners.

**Browser details (please complete the following information):**
 - OS: macOS 11.2.3
 - Hardware Wallet: N/A
 - Browser: Brave Browser (Version 1.22.67 Chromium: 89.0.4389.90 (Official Build) (x86_64))
 - MetaMask Version: 9.2.0

**Comment by gradlman** [comment]
Same bug here. macOS 11.2.3, Firefox, MetaMask 9.2.0, Ledger connected: it is impossible to sign certain transactions (seems to be only contract allowances for me).
The state can be reset if you keep a tab open with the wallet before trying to sign and then change the network in this tab, thus cancelling all pending tx. Otherwise it is in a deadlock with the infinite spinner blocking all interactions in the small window.

**Comment by r-czajkowski** [comment]
I'm pretty sure this bug is related to these changes https://github.com/MetaMask/metamask-extension/pull/10606. I ran into this issue as well. The problem is in this [condition](https://github.com/MetaMask/metamask-extension/blob/1b6bb53556ebbad29dfbee1d8b456511095aba97/ui/app/pages/confirm-approve/confirm-approve.js#L91) so it always renders loading screen if the ERC20 token does not contain ERC20 details.

**Comment by evanworley** [comment]
I'm getting the same issue, both when trying to perform a transaction and also when logging into the metamask extension with the Binance Smart Chain network selected. I can work around the log in issue by switching to a different network, logging in, and then switching back to Binance Smart Chain, but I do not yet have a workaround for the transaction infinite spinner.

Also @everettwho I've been able to clear the spinner by disabling and then reenabling the extension, not re-importing the wallet. That is a lot faster. Does it work for you?

**Comment by danjm** [comment]
@evanworley when you see it on transactions, is it only contract allowance/approval transactions? Or are you seeing an infinite spinner when any type of transaction is attempted?

**Comment by danjm** [comment]
@everettwho Same question as above, does this only happen with contract allowance/approval transactions as others are experiencing, or is this happening to you when any transaction is attempted?

**Comment by evanworley** [comment]
@danjm I'm not sure to be honest. I'm a bit of a crypto newb, and I only tried allowance/approval transactions so far.

**Comment by danjm** [comment]
Okay, thanks.

**Comment by Turinnash** [comment]
Same here. I can log in to my Metamask, but the lil' loading window,do not want to disappear. I see all of my coins on Pencakeswap, but can't trade. Can't buy, can't sell. The circle is spinning for eternety. This thing made me a few hundred $ minus ~since noon. Thanks god, I didn't hear my wife to put thousands today....

**Comment by tmashuang** [comment]
A workaround to get around the loading screen is to disable/enable the extension, before entering the password switch networks, enter password, and switch to the preferred network.

**Comment by everettwho** [comment]
@evanworley Unfortunately disabling then reenabling the extension doesn't work for me,  I get prompted for my wallet password but it goes straight back to the infinite spinner afterwards 😢

@danjm It looks like it's only allowance transactions for us. We don't have a wide variety of transactions on the app, but amongst those I've tested it's only the allowance transactions that are causing the issue.

**Comment by danjm** [comment]
There is a fix to this that will be in the next release, which will begin to roll out on Monday.

In the meantime, there is a more convoluted workaround that should work for all cases of this bug.

A screen capture of this workaround is here: https://streamable.com/u690to

A step-by-step explanation:

1. Enter "chrome://extensions" in your chrome url address bar and go to that page
2. copy the "ID" under the MetaMask entry on the chrome://extensions page
3. Open another tab, and go to "chrome-extension://YOUR_EXTENSION_ID_HERE/home.html", where you replace "YOUR_EXTENSION_ID_HERE" with the metamask extension id you copied from the "chrome://extensions" page. Once you go to this url, you'll see the loading spinner in the browser window and notice that some text like "#confirm-transaction/7824837598493745983/approve" is appended to the url, but that number will be different
4. Open another new tab and go to https://metamask.github.io/test-dapp/
5. Click "Connect", a popup window will open. Click "Next" and then "Connect"
6. Still on the https://metamask.github.io/test-dapp/ page, scroll down a bit, and click "Send". A popup window will open, but you'll just see the loading screen, that's okay.
7. Go back to the browser tab where the "chrome-extension://YOUR_EXTENSION_ID_HERE/home.html#confirm-transaction/######/approve" page is open (the one opened in step 3)
8. Right click in the browser window and select "Inspect"
9. A new pane will open in your browser window. Click the "Console" tab
10. In the console, type "logState(true)" (this is case sensitive). This will copy a bunch of text to your clipboard
11. Open a text editor and paste the copied test
12. Search for "unapprovedTxs" in the copied text. Under that, you should see a number that is the same number as the one between "confirm-transaction" and "approve" in the browser tab you opened in step 3 and mentioned in step 7. Right under that number will be an indented line "id: #" where # is that same number from the browser url. You'll see that number again a few lines further on, indented under "history"
13. Keep going down line by line in the text file until you find the next number that is enclosed in quotes and at the same indention of the first number under "unapprovedTxs". This number will likewise have an "id: #" line under it. Copy this number
14. Go back to the browser tab where the "chrome-extension://YOUR_EXTENSION_ID_HERE/home.html#confirm-transaction/######/approve" page is open (the one opened in step 3)
15. Replace "######/approve" with the number copied in step 13
16. You should now see a different transaction confirmation. If you scroll to the bottom, you should be able to click "Reject 2 Transactions". Click that, and then the "Reject All" button in the box that pops up. This should successfully return you to the home screen of MetaMask, and the loading screen should be gone.

All of the above steps are shown in this video https://streamable.com/u690to
