### ISSUE TITLE
Balance not updating

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#10708]
**Describe the bug**
Some users are reporting recently that their balance is not updating correctly. Their account shows as having a balance of zero, yet external sources such as Etherscan show a non-zero balance

**Steps to reproduce (REQUIRED)**
Still to be determined

**Expected behavior**
The balance in the wallet should be accurate

**Browser details (please complete the following information):**
 - OS: TBD
 - Browser: TBD
 - MetaMask Version: v9.0.2

**Additional context (Error Messages, etc.)**
* [Related community post](https://community.consensys.net/t/account-balance-not-displaying-correctly/150)

**Comment by Gudahtt** [comment]
We've gotten a few screenshots of background process logs from uses affected, and it shows that Infura requests are consistently failing due to CORs errors.

**Comment by AlexHerman1** [comment]
case #'s so far:

104421, 105640, 101435, 107996, 105687, 100239

**Comment by Gudahtt** [comment]
Possibly caused by Chrome's "site permissions" option. If any option other than "On all sites" is selected, Chrome seems to block network requests from our background process.

**Comment by AlexHerman1** [comment]
confirming that this is caused by chrome's site permissions option. that said, it should prompt the correct messaging "balance may be out of sync", with the orange text and the asterisk.

**Comment by danjm** [comment]
@AlexHerman1 Do you know if there have been any reports of this in the past 3 months or so?

**Comment by AlexHerman1** [comment]
yes this is ongoing, with the cause generally being site permissions as mentioned above @danjm

**Comment by Gudahtt** [comment]
The users that have followed up have all reported this as fixed when the Chrome site permissions were set to "On all sites". I'll close this, as it's not a bug with our wallet, but rather a bug with Chrome's site permissions setting.
