### ISSUE TITLE
Distinguish between Infura/Local/Other Testnets

### ISSUE THREAD

**Issue by nandinicbit1981** [MetaMask/metamask-extension#1071]
<img width="1920" alt="screen shot 2017-01-30 at 5 15 38 pm 3" src="https://cloud.githubusercontent.com/assets/18360441/22448672/e0b175be-e70f-11e6-9de4-fc91224772c8.png">
<img width="1920" alt="screen shot 2017-01-30 at 5 15 32 pm 3" src="https://cloud.githubusercontent.com/assets/18360441/22448679/f0448f8e-e70f-11e6-9f2e-02ada2a8037b.png">

Even though i am selecting local test net , the text in the red shows it as ropsten Testnet

**Comment by kumavis** [comment]
> nandini.parimi [5:20 PM] 
i am running it with geth —testnet

**Comment by kumavis** [comment]
I think we should actually redesign this to indicate:
* network version / name
* rpc provider type / endpoint

so it can tell you that you are on ropsten via localhost

**Comment by Zanibas** [comment]
So maybe something like
"Ropsten/Infura"
"Ropsten/Custom"
"Main Net/Infura"

etc etc?

**Comment by flyswatter** [comment]
Is this really a bug?  Your "local test net" is in fact connecting to the ropsten test net.  This is not the same as deploying your own private chain.

**Comment by Zanibas** [comment]
Need design to figure out how to implement this properly.
