### ISSUE TITLE
-32000 RPC Error when deploying test smart contract on MyEtherWallet 

### ISSUE THREAD

**Issue by rashad-xo** [MetaMask/metamask-extension#10715]
**Describe the bug**
When trying to submit a sample smart contract ([from this Vyper example](https://vyper.readthedocs.io/en/stable/vyper-by-example.html)) I'm receiving an ambiguous error `"execution reverted"`. I'm using MyEthereWallet (MEW) to "Deploy a Contract" using a MetaMask wallet set to the Ropsten Test Network. I've pasted the bytecode, the ABI JSON, and other metadata. I click "Sign Contract", it seems to work properly (in the MEW UI), but then in the console I see the below error:

```text
Uncaught (in promise) 
Object { code: -32000, message: "execution reverted" }
```

I have seen [this Zendesk error ticket](https://metamask.zendesk.com/hc/en-us/community/posts/360076669731-RPC-Error-execution-reverted) and I'm wondering if the two are similar.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Open your browser's Developer tools and go to the console
2. Go to MyEtherWallet
2. Sign into your MetaMask wallet (obviously you should have the MetaMask extension)
    - **IMPORTANT** make sure your MetaMask wallet is set to the "Ropsten Test Network"
3. Go to "Contracts" on the left-hand side of MEW UI
4. Click "Deploy Contract"
5. Enter the below for the bytecode input
```text
0x606061026b61014039602061026b60c03960c05160a01c1561002057600080fd5b61014051600055610160516001556001546101805181818301101561004457600080fd5b80820190509050600255600254421061005c57600080fd5b61025356600436101561000d576101ec565b600035601c52600051631998aeef8114156100855760015442101561003157600080fd5b600254421061003f57600080fd5b600454341161004d57600080fd5b600660035460e05260c052604060c020805460045481818301101561007157600080fd5b808201905090508155503360035534600455005b341561009057600080fd5b633ccfd60b8114156100db5760063360e05260c052604060c0205461014052600060063360e05260c052604060c02055600060006000600061014051336000f16100d957600080fd5b005b63fe67a54b811415610124576002544210156100f657600080fd5b6005541561010357600080fd5b600160055560006000600060006004546000546000f161012257600080fd5b005b6338af3eed81141561013c5760005460005260206000f35b634f245ef78114156101545760015460005260206000f35b632a24f46c81141561016c5760025460005260206000f35b6391f901578114156101845760035460005260206000f35b63d57bde7981141561019c5760045460005260206000f35b6312fa6feb8114156101b45760055460005260206000f35b6326b387bb8114156101ea5760043560a01c156101d057600080fd5b600660043560e05260c052604060c0205460005260206000f35b505b60006000fd5b61006161025303610061600039610061610253036000f3
```

6. Enter the below for the ABI JSON input
```json
[{"stateMutability": "nonpayable", "type": "constructor", "inputs": [{"name": "_beneficiary", "type": "address"}, {"name": "_auction_start", "type": "uint256"}, {"name": "_bidding_time", "type": "uint256"}], "outputs": []}, {"stateMutability": "payable", "type": "function", "name": "bid", "inputs": [], "outputs": [], "gas": 110645}, {"stateMutability": "nonpayable", "type": "function", "name": "withdraw", "inputs": [], "outputs": [], "gas": 56121}, {"stateMutability": "nonpayable", "type": "function", "name": "endAuction", "inputs": [], "outputs": [], "gas": 73506}, {"stateMutability": "view", "type": "function", "name": "beneficiary", "inputs": [], "outputs": [{"name": "", "type": "address"}], "gas": 1178}, {"stateMutability": "view", "type": "function", "name": "auctionStart", "inputs": [], "outputs": [{"name": "", "type": "uint256"}], "gas": 1208}, {"stateMutability": "view", "type": "function", "name": "auctionEnd", "inputs": [], "outputs": [{"name": "", "type": "uint256"}], "gas": 1238}, {"stateMutability": "view", "type": "function", "name": "highestBidder", "inputs": [], "outputs": [{"name": "", "type": "address"}], "gas": 1268}, {"stateMutability": "view", "type": "function", "name": "highestBid", "inputs": [], "outputs": [{"name": "", "type": "uint256"}], "gas": 1298}, {"stateMutability": "view", "type": "function", "name": "ended", "inputs": [], "outputs": [{"name": "", "type": "bool"}], "gas": 1328}, {"stateMutability": "view", "type": "function", "name": "pendingReturns", "inputs": [{"name": "arg0", "type": "address"}], "outputs": [{"name": "", "type": "uint256"}], "gas": 1573}]
```
7. Enter an Ether wallet address into the "_beneficiary (address):" input
8. Enter "1616632333" into the "_auction_start (uint256):" input
9. Enter "10" into the "_bidding_time (uint256):" input
10. Give the contract a name 
11. Click "Sign Transaction"

**Expected behavior**
I'm not sure what should happen exactly. But I'm led to believe that I've entered all inputs appropriately, so I should not be seeing the referenced error.

**Screenshots**
![Screen Shot 2021-03-24 at 5 44 22 PM](https://user-images.githubusercontent.com/17253182/112401866-aab0e680-8cc8-11eb-9572-d0e12070d3ac.png)

**Browser details (please complete the following information):**
 - OS: Mac OS
 - Hardware Wallet: N/A
 - Browser: Firefox 86.0.1 (64-bit)
 - MetaMask Version: 9.2.0

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment]
Thanks for the report! It looks like the contract you tried to deploy has failed, and the dapp didn't display this failure message. This doesn't appear to be a MetaMask bug, but rather a problem with this dapp or the specific contract you're truing to deploy.

I'd recommend asking for help in our [Community forum](https://community.metamask.io/), or on the [Ethereum StackExchange](https://ethereum.stackexchange.com/).
