### ISSUE TITLE
Favicon not displaying in Firefox

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/metamask-extension#10710]
**Describe the bug**
The favicon doesn't appear to display in Firefox anymore and I just get the default

**Expected behavior**
I should see my beloved fox head like I do in Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/675259/112375913-353e1980-8cba-11eb-8226-a615a348c932.png)

**Comment by Gudahtt** [comment]
I was able to reproduce this problem as well. No favicon on Firefox.
