### ISSUE TITLE
Ledger unable to connect outputting TypeError with null 'getAdress' property

### ISSUE THREAD

**Issue by manoelpqueiroz** [MetaMask/metamask-extension#10729]
**Describe the bug**
Ledger Nano X is connected, Ethereum app is updated and running, contract data is allowed and udev rules are set, but MetaMask returns a `TypeError: Cannot read property 'getAddress' of null` when trying to connect.

Trezor connects and works just fine, having even sent transactions through MetaMask recently. Ledger also works when interacting through its Ledger Live AppImage.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to **Accounts**
2. Click on **Connect Hardware Wallet**
3. Select **Ledger**
4. Click on **Connect**

**Screenshots**
![image](https://user-images.githubusercontent.com/23669137/112555567-38630380-8da7-11eb-9f10-62dd5231fd7f.png)

**Browser details (please complete the following information):**
 - OS: Arch Linux running kernel v5.11.9
 - Hardware Wallet: Ledger Nano X firmware v1.2.4-5
 - Browser: Firefox 87.0-1
 - MetaMask Version: 9.2.0

**Comment by dpazdan** [comment]
Functionality and support is known to be limited on certain Linux distros.
