### ISSUE TITLE
Cannot execute yarn setup normally

### ISSUE THREAD

**Issue by lienpeng-390** [MetaMask/metamask-extension#10736]
**Describe the bug**
This is error message when I run yarn setup.
It is found that the execution of yarn allow-scripts has timed out.

![image](https://user-images.githubusercontent.com/64118305/112591891-005bcf00-8e40-11eb-96d6-79cffddf4475.png)

**Context details:**
OS: macOS Catalina 10.15.7
node: v14.15.1
yarn: 1.22.10

**Comment by lienpeng-390** [comment]
I changed geckodriver to false in allowScripts and found that the execution of electron also timed out

**Comment by lienpeng-390** [comment]
![image](https://user-images.githubusercontent.com/64118305/112593295-3e59f280-8e42-11eb-9a9a-ed76aa4fcf9a.png)
I changed'geckodriver' to false in'allowScripts' and found that it still failed to execute until'electron'

**Comment by xuliangying** [comment]
I also encountered this problem. Seeking a solution

**Comment by Gudahtt** [comment]
This was due to GitHub downtime. That postinstall step downloads a file from GitHub. The API is back up now
