### ISSUE TITLE
Add LavaMoat for the extension webapp

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#10730]
currently lavamoat is integrated in the build system. this is a tracking issue for this effort.

supporting PRs:

:volcano:  current primary lavamoat PRs: :volcano: 
- [x] [background](https://github.com/MetaMask/metamask-extension/pull/12566)
- [ ] ui

other relevant PRs
- [x] [supporting build sys refactor](https://github.com/MetaMask/metamask-extension/pull/10718)
- [x] [update ses](https://github.com/MetaMask/metamask-extension/pull/10663)
- [x] [Add per-build type LavaMoat policies](https://github.com/MetaMask/metamask-extension/pull/12702)

**Comment by brad-decker** [comment]
@kumavis @naugtur is this done?

**Comment by Gudahtt** [comment]
This was completed in #12242
