### ISSUE TITLE
Update currency conversion is incorrectly showing the current time.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#10741]
**Describe the bug**
The updated time for the currency conversion in settings is incorrectly always showing the current time.

**Steps to reproduce (REQUIRED)**
I blocked the specific network request within the developer console, but this can be achieved by going to the `Currency Conversion` setting and turning off the PC wifi. After waiting a about minute for the `Updated` text to update to the current time even though all network requests have been stopped.

**Expected behavior**
The last `conversionDate` should be applied to the text correctly.

**Comment by danjm** [comment]
Note that recreating this requires explicitly blocking https://min-api.cryptocompare.com/ via the network tab in dev tools.

The "Updated" date should only show the date of the last successful update of the currency conversion rate.
