### ISSUE TITLE
Break e2e tests into small pieces that use fixtures

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#10754]
Currently we have two ways of setting up state for running e2e tests. The first way is to install the extension with an empty/initial state as part of the e2e test run, and then have the e2e test take the steps to set app state to whatever is necessary for each test. This requires going through the onboarding flow in each e2e test, and sometimes taking other actions (e.g. creating transactions). The second way is with fixtures: we specify in json files what we need the state to be at the beginning of the test.

Corresponding to this are two ways of testing features: one that tests multiple features and distinct user flows, all as part of the same e2e test run; the other that tests a specific user feature or UX flow.

We should migrate all tests to both of these second ways.

Tests that currently follow the second way (i.e. using fixtures to set state and testing features / UX flows in isolation) include:

- metamask-extension/test/e2e/tests/localization.spec.js
- metamask-extension/test/e2e/tests/personal-sign.spec.js
- metamask-extension/test/e2e/tests/simple-send.spec.js
- metamask-extension/test/e2e/metrics.spec.js

Tests that need to be migrated to this pattern include:

- [x] address-book.spec.js
- [x] incremental-security.spec.js
- [x] from-import-ui.spec.js
- [x] metamask-responsive-ui.spec.js
- [x] permissions.spec.js
- [x] ethereum-on.spec.js
- [ ] metamask-ui.spec.js
- [x] send-edit.spec.js
- [x] threebox.spec.js
- [x] metrics.spec.js
- [x] signature-request.spec.js

**Comment by NiranjanaBinoy** [comment]
`metrics.spec.js` is already migrated to use fixtures.

**Comment by Gudahtt** [comment]
My advice when you get to `metamask-ui.spec.js` would be to break off tests from the _end_ one-by-one, rather than splitting up the file all at once. That would be a lot more manageable, because that test suite is _huge_. It's the only one too big for a single PR I think.

**Comment by danjm** [comment]
Remaining work covered in https://github.com/MetaMask/metamask-extension/issues/11136
