### ISSUE TITLE
Run e2e tests in parallel

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#10759]
To speed up our e2e tests, we want them running in parallel on CI.

Each e2e test suite can be run independently. We'll need to decide how to group them together (e.g. 1 test suite per job, multiple per job, etc.)

We should probably use separate jobs for each run, to avoid running out of memory (unless we can demonstrate that this is not likely to be a problem).

**Comment by PeterYinusa** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/16417
