### ISSUE TITLE
Transaction error resulting in eth taken but not refunded

### ISSUE THREAD

**Issue by Monster1984** [MetaMask/metamask-extension#10766]
I am using Google Chrome with the metamask extension. 11 days ago I purchased some products on a website, however, one of the items I tried to purchase sold out during the transaction (I have attached the etherscan and transaction logs). I have been going back and forth with metamask support and they keep telling me to try to restore my account using a new device and my 12 word seed phrase. I believe the issue is elsewhere, upon looking at the transaction, it appears that the eth was sent out but never refunded, I can assure that the eth did in fact leave my wallet. Is there anything I can do and where is the missing ethereum?

Thank you for any suggestions or advice as this is beyond my scope.

![etherscan issue](https://user-images.githubusercontent.com/81442516/112917865-965a5880-90d1-11eb-97a6-0ceb0cd0c4e1.png)
![etherscan issue2](https://user-images.githubusercontent.com/81442516/112917886-9fe3c080-90d1-11eb-9a82-8d6c9c289673.png)

**Comment by Monster1984** [comment]
![balance1](https://user-images.githubusercontent.com/81442516/112918275-868f4400-90d2-11eb-9770-360b6ee4489c.png)

This was my initial balance that is a little cleaner to look at, as the transaction history is only up to when I noticed the funds weren't refunded.

**Comment by tmashuang** [comment]
If the balance is incorrect can you post your state logs, and background and ui console errors?

**Comment by tmashuang** [comment]
Closing this issue. There is no follow up with the information requested and the notion of "refunds" is not something that can be provided due to the nature of blockchains. If the contract interaction failed, then the value wasn't taken, but the gas is.
