### ISSUE TITLE
got `remotedev: command not found` error  while `yarn devtools:redux` and `yarn start:dev` 

### ISSUE THREAD

**Issue by wk3368** [MetaMask/metamask-extension#10770]
**Describe the bug**
after `git pull`  for the latest version,  both `yarn devtools:redux` and `yarn start:dev` will got following error:

yarn run v1.22.10
$ remotedev --hostname=localhost --port=8000
/bin/sh: remotedev: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
there should be no error for while running these 2 commands.

**Screenshots**
<img width="1102" alt="WX20210330-215407@2x" src="https://user-images.githubusercontent.com/171268/113000555-83638900-91a2-11eb-9cac-5887f04dace0.png">

**Browser details (please complete the following information):**
 - OS: [e.g. OS X]

**Additional context (Error Messages, etc.)**
I have checked the git log and found this bug is imported by this commit:
https://github.com/MetaMask/metamask-extension/commit/ff86465a24d9754a62647e58700b6f43786173c8

-    "remotedev-server": "^0.3.1",

I suggest to add the following line in the README.md:

-  Install dependency first: `npm i -g remotedev-server`
before this line:
- React DevTools will open in a separate window; no browser extension is required

**Comment by Gudahtt** [comment]
Sorry about that! I will update the README instructions accordingly.
