### ISSUE TITLE
Refactor ethereum-on.spec.js to follow pattern in metamask-extension/test/e2e/tests

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#10771]
This is part of https://github.com/MetaMask/metamask-extension/issues/10754, and is the to-do item for the ethereum-on.spec.js

`metamask-extension/test/e2e/tests/personal-sign.spec.js` can be used an example

 Only the `has the ganache network id within the dapp` and below tests need to be included.

**Comment by Az111z** [comment]
> This is part of #10754, and is the to-do item for the ethereum-on.spec.js
> 
> `metamask-extension/test/e2e/tests/personal-sign.spec.js` can be used an example
> 
> Only the `has the ganache network id within the dapp` and below tests need to be included.

0x9cacd5b1ecc5800cfa3b60b24e9f6eb66a9da53
