### ISSUE TITLE
Display error when doing ERC20 Batch Transactions

### ISSUE THREAD

**Issue by H34D** [MetaMask/metamask-extension#10783]
**Describe the bug**
When signing more than one transaction with the batch transaction feature the token Symbol and amount of tokens to transfer will not be displayed properly. When i go forth and back with the little arrows on top the right information is displayed. I think its not limited to ERC20 tho.

<img width="407" alt="Screenshot 2021-03-31 at 16 14 20" src="https://user-images.githubusercontent.com/13647606/113159453-e6a1f980-923c-11eb-9d20-40563ed71c6f.png">

**Steps to reproduce (REQUIRED)**

When using this kind of batch transactions

```
var batch = web3.createBatch();
batch.add(myContractInstance.doSomething(arg1, arg2, {from: account, gas: 4000000}));
batch.add(myContractInstance.doSomethingElse(arg1, arg2, {from: account, gas: 4000000}));
batch.add(myContractInstance.doSomethingElseEntirely(arg1, arg2, {from: account, gas: 4000000}));
batch.execute();
```

and the accept / reject window opens. 

**Expected behavior**
I see the details of all transaction in the batch properly.

**Screenshots**

First tx is displayed properly:
<img width="422" alt="Screenshot 2021-03-31 at 16 14 09" src="https://user-images.githubusercontent.com/13647606/113159909-45677300-923d-11eb-8b7d-096dca5cb8cc.png">

Second is not displayed properly:
<img width="407" alt="Screenshot 2021-03-31 at 16 14 20" src="https://user-images.githubusercontent.com/13647606/113159914-4698a000-923d-11eb-944c-893f0354eeba.png">

When i go forth and back with arrows its shown properly:
<img width="411" alt="Screenshot 2021-03-31 at 16 14 38" src="https://user-images.githubusercontent.com/13647606/113159916-47313680-923d-11eb-9926-9e7129c9c38c.png">

**Browser details (please complete the following information):**
 - OS: MacOS
 - Hardware Wallet: nothing
 - Browser: All chrome
 - MetaMask Version: 9.2.0

**Comment by tmashuang** [comment]
Details missing that prevents reproduction are a `web3` version, the contract used for the transactions, and a dapp that uses those details.

**Comment by H34D** [comment]
It can be reproduced with any ERC20 Transfer operation. ie. with: https://rinkeby.etherscan.io/token/0xc778417e063141139fce010982780140aa0cd5ab

Web3 version 1.3.4

**Comment by EHaracic** [comment]
Not able to reproduce reported issue. 

One scenario when we were able to have an issue (not sure if it is the same issue) is the transaction with unknown token, Example is shown on the screenshots below. 
The batch transaction with 3 transfers of the WETH token
1. The list of assets (note: there is no WETH)
![image](https://user-images.githubusercontent.com/49436614/140485730-def31445-84f5-459e-9c35-60af8948d751.png)
2. Created batch transaction with 3 transfers of WETH's. The number is wrongly interpreted.
![image](https://user-images.githubusercontent.com/49436614/140494628-c1b0d11b-83fa-4df6-a995-267560feea68.png)
![image](https://user-images.githubusercontent.com/49436614/140494671-84755018-65b7-4cf1-8559-78f45abb6a08.png)

Screenshots below shown when the WETH token is the asset of the account.
![image](https://user-images.githubusercontent.com/49436614/140494993-a4841182-8da7-4ca9-acf0-55ebbd2a52b7.png)


![image](https://user-images.githubusercontent.com/49436614/140494931-fcdb4265-70fe-4eff-a5b3-300e24776738.png)

**Comment by H34D** [comment]
I don't have access to the original code anymore. Therefore i am not able to reproduce it anymore as well. Please close this issue if you like.
