### ISSUE TITLE
No Keyring for expected amount

### ISSUE THREAD

**Issue by gregmcgolf** [MetaMask/metamask-extension#10799]
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
I expected the transaction to send the tokens to another address

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]
MetaMask V2.0.1(49)
**Additional context (Error Messages, etc.)**
This issue was researched earlier, then closed, but I still have the issue on my mobile Samsung phone, even though it is supposedly fixed. It obviously isn't for me. I have metamask installed on the phone, but I get this error message when I try to send tokens to another address in my metamask wallet.

**Comment by tmashuang** [comment]
Insufficient issue template. Among the sparse information provided mentions a mobile device, this repository is for MetaMask on the browser extension platform.

**Comment by gregmcgolf** [comment]
Wow, I am a newbie here and get hammered. I stand to lose nearly 10K USD if I can't figure out this issue.
