### ISSUE TITLE
Token transaction is not presented (balance is 0)

### ISSUE THREAD

**Issue by codelano** [MetaMask/metamask-extension#10818]
**Describe the bug**
Transaction of received tokens are missing on Metamask extension wallet even contract address is added to the wallet.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Transaction of token TSTBv7 was made from address: 0xeb2138aba0c9821a17dd81d31efd2e91de07e1d2 to these address:
- 0x15f2be912936ef09e2c931b4b5aeb8973d39f8f5 (visible on wallet)
- 0x0000000000000000000000000000000000000000 (burned)
- 0x9def8c013eb590aff09c8c76f9a74a3055faa177 (not presented on wallet)
2. Transaction id: https://ropsten.etherscan.io/tx/0xf3316c497fd47ee79be57be7b91cb96cc0414003a155d8ff8bc83b3a090594c9
3. Metamask does not display tokens for 0x9def8c013eb590aff09c8c76f9a74a3055faa177 address (token contract is added)

**Expected behavior**
200,000 TSTBv7 tokens are visible on Metamask wallet

**Actual behavior**
0 TSTBv7 tokens are visible on Metamask wallet

--

**Screenshots**
![image](https://user-images.githubusercontent.com/15995240/113493305-d14ff800-94e6-11eb-93ef-784d871e65e6.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: Chrome and Edge
 - MetaMask Version: 9.0.3

**Additional context (Error Messages, etc.)**
Network: Reproduced on Ropsten and Ganache
Part of smart contract that I use for this transaction:

```
  function transfer(address to, uint256 value) public returns (bool) {
    require(value <= _balances[msg.sender]);
    require(to != address(0));

    uint256 tokensToBurn = findOnePercent(value);
    uint256 tokensToStack = findOnePercent(value);
    uint256 tokenstoDeduct = tokensToBurn.add(tokensToStack);
    uint256 tokensToTransfer = value.sub(tokenstoDeduct);

    _balances[msg.sender] = _balances[msg.sender].sub(value);
    _balances[to] = _balances[to].add(tokensToTransfer);

    _totalSupply = _totalSupply.sub(tokenstoDeduct);

    emit Transfer(msg.sender, to, tokensToTransfer);
    emit Transfer(msg.sender, address(0), tokensToBurn);
    emit Transfer(msg.sender, address(BOUNTY_ADDRESS), tokensToStack); // this part sends to address MetaMask fails to recognize
    return true;
  }
```

**Comment by codelano** [comment]
Does anyone cares about bugs in this extension :D

**Comment by danjm** [comment]
Are you seeing any error messages related to balance in the developer console?

And does the balanceOf implementation for this contract follow the erc-20 token standard?

**Comment by codelano** [comment]
> Are you seeing any error messages related to balance in the developer console?
> 
> And does the balanceOf implementation for this contract follow the erc-20 token standard?
I believe it follows erc-20 standard:
```
  function balanceOf(address owner) public view returns (uint256) {
    return _balances[owner];
  }
```
Dev console does not show any logs
![image](https://user-images.githubusercontent.com/15995240/114073352-dd9fd080-98ab-11eb-83f6-7491fad8dc44.png)
