### ISSUE TITLE
Show contract data destructured properly

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#10811]
I think there was a misunderstanding when we first implemented this feature. The intended goal of showing the call data in more detail was not to see the method's input types in a destructured way, but instead should be a place to see *the input parameters themselves* in a destructured way.

Consider this prompt:
<img width="382" alt="Screen Shot 2021-04-02 at 12 38 17 PM" src="https://user-images.githubusercontent.com/542863/113448235-4cfb5900-93b0-11eb-814b-2fd9e8f053c3.png">

The user wants to see up to three things:
- The method name
- An address (0x288...)
- A boolean value (true)

We correctly show the method name, that's great!

But then we really drop the ball. We show the data representing the types of the hex data below it, but we don't actually destructure that data. I've known about this for a long time, I think a lot of us did, but somehow we haven't just cleaned up this view and improved it.

This issue is to do the smallest change to make this actually useful:

Instead of showing the JSON of the method signature, we should show the destructured parameters. At most, we should show a prefix of that parameter's type for clarity. This would result in the JSON field instead showing:
```
address: 0x2....
boolean: true
```
This should be a really small/easy thing to do, and it brings some value to this view.

Later on we can add more rich rendering of types (like we really would ideally render our standard "account component" that shows nicknames, or reverse-resolved ENS names wherever an address is seen).

**Comment by danfinlay** [comment]
For showing parameter names, related to https://github.com/MetaMask/metamask-extension/issues/7274

**Comment by rachelcope** [comment]
Here are the designs for the MVP of this issue. It is ready for development.

[Figma designs](https://www.figma.com/file/Flqm2U9DLBtcsZSt72CNWG/contract-data?node-id=77%3A0)
