### ISSUE TITLE
Cannot unlock Ledger address from page 2 and above on first position

### ISSUE THREAD

**Issue by daraosn** [MetaMask/metamask-extension#10815]
When navigating through the ledger addresses, after click on NEXT> button the first address will always be disabled/locked and cannot interact with it nor select it:

![image](https://user-images.githubusercontent.com/1020989/113466357-bf7e3e80-946d-11eb-9856-626b2cd132d5.png)

**Comment by tmashuang** [comment]
The description does not describe the title of this issue. Is there an expectation of what the grey check marked address is that isn't being met, or an issue with the navigation through the multiple addresses page?

**Comment by daraosn** [comment]
@tmashuang in simple terms: when I click on "NEXT >" page button, the first check box is always greyed out and I cannot click it or select it. I want to be able to select that address. Hope it's clearer now.

**Comment by daraosn** [comment]
Nevermind, I reinstalled the extension and now it works fine.
