### ISSUE TITLE
Corrupted CSS resources in Firefox Extension

### ISSUE THREAD

**Issue by zbraniecki** [MetaMask/metamask-extension#10821]
Hi,

I'm a Mozilla employee working on the Firefox Platform. I'm doing research of the network errors reported by Gecko in search for a cause of a problem known as Yellow Screen of Death.

During our research we installed a probe that collects all network errors and enabled in on release. One of the results is a very high volume of `NS_ERROR_CORRUPTED_CONTENT` events coming from Meta Translate extension.

I reported the bug in our system as https://bugzilla.mozilla.org/show_bug.cgi?id=1702936 .

Let me know if you saw something that can be related to this issue, maybe your users reported issues that could be caused by such bug?

It may also be that some version of your extension used in the wild has those three files corrupted somehow? Our research is quantitative and I'm just reporting what we see, without understanding why we see it, so any hypothesis or remedy will require further analysis which you may want to conduct in cooperation with Mozilla WebExtensions team.

I'm reporting it because this is by far the largest contributor of errors out of all extensions that we see and may be an indicator of a problem your users experience in the wild.

**Comment by Rob--W** [comment]
@zbraniecki This repo is the MetaMask extension, the bug is about the MateTranslate extension. The following files are affected, but don't appear in this repository:
- `res/styles/ui_components/contextMenu.css`
- `res/styles/pages/common/main.css`
- `res/styles/pages/internal/content.css`

**Comment by zbraniecki** [comment]
Ouch, good call. I don't see an analogous repository for the translate extension tho. Maybe the MetaMask team will move it to the correct location

**Comment by Rob--W** [comment]
I don't think that the MetaMask team is even affiliated with the extension that you're investigating.

**Comment by zbraniecki** [comment]
agh. closing then!
