### ISSUE TITLE
empty wallet

### ISSUE THREAD

**Issue by vienasdutrys7** [MetaMask/metamask-extension#10832]
Hello i restore my metamask wallet with 12 phrases, and i got empty wallet, i try to add tokens, but anyway its empty, i dont have private key.. I just checked my eth address its difirent from my restored wallet, i check it on bscscan.. What i need to do to get back my old eth adress?

**Comment by Hasony3** [comment]
Hello, I have the same problem. Have you solve it. I would appreciate if you help. Thank you

**Comment by vienasdutrys7** [comment]
Hello, yes i fixed it becouse i have another adress and just restore private key and got it

**Comment by Hasony3** [comment]
im happy for you, I have the address also but how did you restore it, on which site, or what are the steps you did.

thank you

**Comment by Hasony3** [comment]
I promise like a real man if you help me return my funds ill send to your address a gift that youll like

**Comment by danjm** [comment]
@Hasony3 Please contact metamask support: support@metamask.io, or https://community.metamask.io/

**Comment by vienasdutrys7** [comment]
@Hasony you know your 12 seed phrases, or private key?

**Comment by Hasony3** [comment]
@vienasdutrys7 Yes I know my 12 seed phrases only but I don't know the private key.

**Comment by vienasdutrys7** [comment]
If you dont insert anyone account in your metamask account you just can go add account, or add, and i think you get your adress with coins

**Comment by Hasony3** [comment]
No I didn't insert anyone account. I had 2 accounts, the coins are on the second one. I reinstalled my Metamask and added several accounts but no coins appear. I copied the address of the transfer of the blockchain and added it on private key to import account. It succeeded and showed (imported) but no coins. I imported several accounts but no coins.

**Comment by Hasony3** [comment]
![Screenshot_2021-04-09-07-32-51-448_io metamask](https://user-images.githubusercontent.com/77076364/114128798-db6a6000-9905-11eb-9111-606fa5768d63.jpg)

**Comment by vienasdutrys7** [comment]
adress is correct?

**Comment by Hasony3** [comment]
No another address... I even don't know what are these imported addresses
