### ISSUE TITLE
The app shows ETH icon while network is BSC

### ISSUE THREAD

**Issue by jinhduong** [MetaMask/metamask-extension#10830]
It looks like a very small issue but if it can be fixed the UX will be very good.

**Comment by danjm** [comment]
This is addressed in the v9.3.0 release, which is in the process of being rolled out to all users.

**Comment by mqklin** [comment]
@danjm is there a way to add an icon for our own sidechain network? `iconUrls` is ignored for some reason

**Comment by 0ximDean** [comment]
@danjm is there a way to add an icon for our own sidechain network? iconUrls is ignored for some reason
