### ISSUE TITLE
Forever pending swap blocking whole wallet

### ISSUE THREAD

**Issue by Mousegg** [MetaMask/metamask-extension#10843]
Hello,

My last transaction a couple of days ago is still pending in metamask and blocks all other transactions. So i cant use the wallet.

See the screenshot.

![スクリーンショット (5)](https://user-images.githubusercontent.com/82116087/113915856-90eec380-97df-11eb-9f04-c660513bb437.png)
![スクリーンショット (6)](https://user-images.githubusercontent.com/82116087/113915876-977d3b00-97df-11eb-8496-78fb8a95bea1.png)

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by danjm** [comment]
Hello,

You should be able to speed up or cancel this transaciton using the method described here: https://metamask.zendesk.com/hc/en-us/articles/360015489251-How-to-Speed-Up-or-Cancel-a-Pending-Transaction

If that does not work, feel free to comment further on this issue.
