### ISSUE TITLE
User balance isn't enough - gas limit is set to maximum

### ISSUE THREAD

**Issue by VexyCats** [MetaMask/metamask-extension#10862]
**Describe the bug**

If a user is submitting a transaction to a smart contract - and the gas fee + amount for transaction is over their balance, metamask will max out the gas limit showing them a gas fee of multiple thousands of dollars.

![image](https://user-images.githubusercontent.com/17414704/114129436-26e63380-9931-11eb-8eef-8a4fad345ffe.png)

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to mintable.app/art/item/Hidden-Dreams-What-we-create-in-our-minds-between-two-lines/Z9EjpX6Mu-wQJHB
2. Use a wallet with no balance
3. Click buy now

**Expected behavior**
Should display an accurate gas price

**Comment by VexyCats** [comment]
Any idea why this happens?

**Comment by danjm** [comment]
We thought we fixed a very similar sounding bug with https://github.com/MetaMask/metamask-extension/issues/9967

More investigation will be needed

**Comment by ulope** [comment]
Still an issue

**Comment by bschorchit** [comment]
Closing in favor of: https://github.com/MetaMask/metamask-extension/issues/19692
