### ISSUE TITLE
MetaMask not showing BUSD

### ISSUE THREAD

**Issue by LilFatFrank** [MetaMask/metamask-extension#10864]
I swapped my bnb to busd and connected my metamask wallet with binance smart chain
Tried to get into an FCFS IDO for oction but it didn't go through

when I connect my wallet with bscpad, I see busd and bnb balance both in bscpad, but I don't see it on my metamask wallet. My metamask wallet only shows bnb.

can someone please help here?

**Comment by itboy79** [comment]
click ADD TOKEN
then CUSTOM TOKEN
paste contract for BUSD [0xe9e7cea3dedca5984780bafc599bd69add087d56](https://bscscan.com/token/0xe9e7cea3dedca5984780bafc599bd69add087d56?a=0x08ea6e53b8f2464144439981655d9ca1d8098178)

**Comment by danjm** [comment]
@LilFatFrank  Please try the above solution. Let us know if it does not work

Thansk @itboy79  for sharing that solution
