### ISSUE TITLE
No way to unsubscribe to EventEmitters

### ISSUE THREAD

**Issue by ErnoW** [MetaMask/metamask-extension#10873]
**Describe the bug**
There is no way to remove subscriptions to Metamask events. 

**Steps to reproduce (REQUIRED)**
1. Add a new eventListener via 
```js
const handleAccountsChanged = (accounts) => {
  // Handle the new accounts, or lack thereof.
  // "accounts" will always be an array, but it can be empty.
}
ethereum.on('accountsChanged', handleAccountsChanged);
```

2. If I want to remove this eventListener, there is currently no way to do so.

The documentation (https://docs.metamask.io/guide/ethereum-provider.html#events) references to the NodeJs EventEmitter implementation (https://nodejs.org/api/events.html), which provides a `.off` method to remove eventListeners.
However, this is not exposed for usage, when I call 
```js
ethereum.off('accountsChanged', handleAccountsChanged);
```
I get 
```
TypeError: window.ethereum.off is not a function
```

**Expected behavior**
I would expect a way to remove event listeners, (via the `.off` functionality or another way if that is preferred)

**Browser details (please complete the following information):**
 - OS: MacOs BigSur
 - Hardware Wallet: -
 - Browser: Safari Version 14.0.3 (16610.4.3.1.7), Brave Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (arm64)
 - MetaMask Version: 9.3.0

**Additional context (Error Messages, etc.)**
I am using React as a framework, where I want to update eventListener callbacks dynamically, depending on the state. The best practice for this is to use an useEffect, and subscribe to a new eventListener and remove the old subscription.

Adding a fix for this will probably add a better user experience and performance to React apps (and probably other apps) that integrate with MetaMask.

> Note: not sure if this counts as a bug or feature request, but the "Request a new feature" redirects to an unexisting page.

**Comment by Nikita-Polyakov** [comment]
@ErnoW Hi! I had the same problem, and after research ethereum prototype i found the solution in spec:
`ethereum.removeListener('accountsChanged', handleAccountsChanged)`
You can find example here:
https://eips.ethereum.org/EIPS/eip-1193#appendix-ii-examples

**Comment by danjm** [comment]
@ErnoW Please try the above solution. Let us know if it does not work

Thansk @Nikita-Polyakov for sharing that solution
