### ISSUE TITLE
Hide zero balances

### ISSUE THREAD

**Issue by 2ge** [MetaMask/metamask-extension#10879]
Hi,

it would be nice to have option to hide zero balances of tokens. I know there is possibility to hide them, but if one have 100 tokens, it is quite a lot of work...

Thanks for exceptional app.

**Comment by darkwing** [comment]
Hello @2ge !  You can presently do this by going to "Settings > General" and clicking this toggle:

<img width="386" alt="HideZero" src="https://user-images.githubusercontent.com/46655/114583241-0545be80-9c47-11eb-87d3-c4ec82fb74e1.png">
