### ISSUE TITLE
Ledger Nano: Metamask Address does not correspond to Ledger and can't move funds

### ISSUE THREAD

**Issue by itboy79** [MetaMask/metamask-extension#10875]
**Describe the bug**

**Steps to reproduce (REQUIRED)**
 We have not been able to reproduce this issue reliably, but here are the steps we took to encounter it in the first place:

1. Connect a ledger nano, unlock it, and navigate to the Ethereum app on the Ledger
2. In Metamask, select "Connect Hardware Wallet" from the accounts menu
3. Select Ledger and Connect
4. Select an account and click "Unlock"
5. Click the copy button next to the address to copy the wallet address.
6. Send ETH to that address.
7. Reboot, disconnect the ledger, come back later.
8. Reconnect the ledger nano, unlock it, etc.
9. Attempt to send a transaction from the Metamask account.
10. Approve on ledger
11. Transaction sent

Then

1. Connect a ledger nano, unlock it, and navigate to the Ethereum app on the Ledger
2. In Metamask, select "Connect Hardware Wallet" from the accounts menu
3. Select Ledger and Connect
4. Select another account (first was already flagged) and click "Unlock"
5. Click the copy button next to the address to copy the wallet address.
6. Send ETH to that address.
7. Reboot, disconnect the ledger, come back later.
8. Reconnect the ledger nano, unlock it, etc.
9. Attempt to send a transaction from the Metamask account.
10. Get an error similar to the effects of #[6011](https://github.com/MetaMask/metamask-extension/issues/6011) - Metamask is sending from a different address than the attached ledger and[ #6012](https://github.com/MetaMask/metamask-extension/issues/6012) Ledger Nano: Metamask Address does not correspond to Ledger 

12. If you attempt to import another account from the ledger, the original address is not available.
13

**Expected behavior**
 If I connect an account from a ledger nano, I expect that account / address to exist on the ledger nano and/or that I can have control of it.

**Browser details (please complete the following information):**
* OS: MacOS 11.2.3
* Browser Firefox
* MetaMask Version 587
*

**Additional context**
 I'm not certain how this happened. My understanding is that when a ledger is connected, Metamask asks it for a list of addresses, and those addresses are provided by the nano without any proof that it can sign messages with it. I suspect that some kind of interference (static electricity, gamma rays, a butterfly flapping its wings in China, etc.) caused the initial transmission of the address to be sent incorrectly, but it's hard to say for sure.
Ledger Live does not allow a user to connect an account without first confirming the address by clicking a button on the ledger (I'm not sure how this works under the hood, but I have the impression it's signing a message). It strikes me that this could have been avoided if metamask had required the user to sign a message before considering the account connected. 

Since I sent my coins to this random address generated by Metamask, I’m no longer able to access.
Can you please explain what happened and please give me access to my coins?ered more quickly and make it easier for other devs to find the answer in the future.

**any way to bypass ledger auth or export seedphrase of wallet?**

**Comment by crypt012** [comment]
I encountered a very similar issue (#6012) today. This is very worrying. I hope I'll be able to get my ETH back...

**Comment by itboy79** [comment]
It’s not closed!

MetaMask version 9.3.0

**Comment by crypt012** [comment]
@tmashuang this is not closed nor solved. It's the first time we have such a post with MetaMask 9.3.0

**Comment by Heineseeki** [comment]
I have the same issue today. Anything we can do?

**Comment by crypt012** [comment]
I submitted both a ledger & metamask ticket. Still unsolved. I got basic replies from both of them, but they may investigate (I hope so). Best you can do is to open support tickets, and talk about it everywhere... This is a verry worrying issue.

**Comment by crypt012** [comment]
Any update ? @tmashuang this has never been solved, you closed it without posting a single message...
My funds are still stuck

**Comment by tmashuang** [comment]
This issue is a copy of https://github.com/MetaMask/metamask-extension/issues/6012, as that issue still remains open.

**Comment by crypt012** [comment]
> This issue is a copy of #6012, as that issue still remains open.

Thanks for your reply. Yes it's very similar but not the same version of MM. 
Btw, #6012 has been opened for more than 2 and a half year... even if it got "sev1-high" label. I hope we will soon find a solution to this issue. I'm worried never to retrieve my money.

**Comment by itboy79** [comment]
@tmashuang I solved this issue. 
actually it’s not a MetaMask bug but a Ledger one. To recover access to “wrong” address user have to enable extended account search in ledger live allow  to browse through erroneous accounts, BUT you can’t control them in Metamask even if you see them in your browser extension. 
You have to use Mycrypto tool in order to move funds back to legit account.

**Comment by crypt012** [comment]
> @tmashuang I solved this issue.
> actually it’s not a MetaMask bug but a Ledger one. To recover access to “wrong” address user have to enable extended account search in ledger live allow to browse through erroneous accounts, BUT you can’t control them in Metamask even if you see them in your browser extension.
> You have to use Mycrypto tool in order to move funds back to legit account.

Thanks for this info. I enabled extended account search in ledger live, and then try to "add account" but I got nothing new... How did you find your account with weird derivation path ?

**Comment by itboy79** [comment]
> > @tmashuang I solved this issue.
> > actually it’s not a MetaMask bug but a Ledger one. To recover access to “wrong” address user have to enable extended account search in ledger live allow to browse through erroneous accounts, BUT you can’t control them in Metamask even if you see them in your browser extension.
> > You have to use Mycrypto tool in order to move funds back to legit account.
> 
> Thanks for this info. I enabled extended account search in ledger live, and then try to "add account" but I got nothing new... How did you find your account with weird derivation path ?

Connect Ledger through Mycrypto and search the address from there

**Comment by crypt012** [comment]
> > > @tmashuang I solved this issue.
> > > actually it’s not a MetaMask bug but a Ledger one. To recover access to “wrong” address user have to enable extended account search in ledger live allow to browse through erroneous accounts, BUT you can’t control them in Metamask even if you see them in your browser extension.
> > > You have to use Mycrypto tool in order to move funds back to legit account.
> > 
> > 
> > Thanks for this info. I enabled extended account search in ledger live, and then try to "add account" but I got nothing new... How did you find your account with weird derivation path ?
> 
> Connect Ledger through Mycrypto and search the address from there

I tried that but I only see accounts from mains derivation paths, nothing exotic...

**Comment by prejudicedad** [comment]
Im struggling with this same issue right now and really stressed about it. I tried using MyCrypto tool to FindETH and scanned for addresses with ETH after linking my Ledger, but to no avail. It did not find any ETH addresses with funds! This really sucks bc I know the address and can view it on Etherscan. If anyone can help I am willing to pay them! Thanks.

**Comment by crypt012** [comment]
> Im struggling with this same issue right now and really stressed about it. I tried using MyCrypto tool to FindETH and scanned for addresses with ETH after linking my Ledger, but to no avail. It did not find any ETH addresses with funds! This really sucks bc I know the address and can view it on Etherscan. If anyone can help I am willing to pay them! Thanks.

Hello, 
Did you try the following custom path using MEW : m/44'/60'/0'/4/0 ?

**Comment by prejudicedad** [comment]
> > Im struggling with this same issue right now and really stressed about it. I tried using MyCrypto tool to FindETH and scanned for addresses with ETH after linking my Ledger, but to no avail. It did not find any ETH addresses with funds! This really sucks bc I know the address and can view it on Etherscan. If anyone can help I am willing to pay them! Thanks.
> 
> Hello, Did you try the following custom path using MEW : m/44'/60'/0'/4/0 ?

My issues is with MM and Ledger, not sure if that makes a difference. I know the pubhlic wallet address its just no being recognize by my Ledger or picked up when I try to "connect hardware wallet". I tried to input that derivation path into MyCrypto - FindETH - add custom derivation path and the format seems incorrect. Any advice?

**Comment by KOOLMOLL** [comment]
> **Describe the bug**
> 
> **Steps to reproduce (REQUIRED)**
>  We have not been able to reproduce this issue reliably, but here are the steps we took to encounter it in the first place:
> 
> 1. Connect a ledger nano, unlock it, and navigate to the Ethereum app on the Ledger
> 2. In Metamask, select "Connect Hardware Wallet" from the accounts menu
> 3. Select Ledger and Connect
> 4. Select an account and click "Unlock"
> 5. Click the copy button next to the address to copy the wallet address.
> 6. Send ETH to that address.
> 7. Reboot, disconnect the ledger, come back later.
> 8. Reconnect the ledger nano, unlock it, etc.
> 9. Attempt to send a transaction from the Metamask account.
> 10. Approve on ledger
> 11. Transaction sent
> 
> Then
> 
> 1. Connect a ledger nano, unlock it, and navigate to the Ethereum app on the Ledger
> 2. In Metamask, select "Connect Hardware Wallet" from the accounts menu
> 3. Select Ledger and Connect
> 4. Select another account (first was already flagged) and click "Unlock"
> 5. Click the copy button next to the address to copy the wallet address.
> 6. Send ETH to that address.
> 7. Reboot, disconnect the ledger, come back later.
> 8. Reconnect the ledger nano, unlock it, etc.
> 9. Attempt to send a transaction from the Metamask account.
> 10. Get an error similar to the effects of #[6011](https://github.com/MetaMask/metamask-extension/issues/6011) - Metamask is sending from a different address than the attached ledger and[ #6012](https://github.com/MetaMask/metamask-extension/issues/6012) Ledger Nano: Metamask Address does not correspond to Ledger 
> 
> 12. If you attempt to import another account from the ledger, the original address is not available.
> 13
> 
> 
> **Expected behavior**
>  If I connect an account from a ledger nano, I expect that account / address to exist on the ledger nano and/or that I can have control of it.
> 
> 
> **Browser details (please complete the following information):**
> * OS: MacOS 11.2.3
> * Browser Firefox
> * MetaMask Version 9.3.0
> *
> 
> 
> **Additional context**
>  I'm not certain how this happened. My understanding is that when a ledger is connected, Metamask asks it for a list of addresses, and those addresses are provided by the nano without any proof that it can sign messages with it. I suspect that some kind of interference (static electricity, gamma rays, a butterfly flapping its wings in China, etc.) caused the initial transmission of the address to be sent incorrectly, but it's hard to say for sure.
> Ledger Live does not allow a user to connect an account without first confirming the address by clicking a button on the ledger (I'm not sure how this works under the hood, but I have the impression it's signing a message). It strikes me that this could have been avoided if metamask had required the user to sign a message before considering the account connected. 
> 
> 
> 
> Since I sent my coins to this random address generated by Metamask, I’m no longer able to access.
> Can you please explain what happened and please give me access to my coins?ered more quickly and make it easier for other devs to find the answer in the future.
> 
> **any way to bypass ledger auth or export seedphrase of wallet?**
> 
> 
> 
>

**Comment by KOOLMOLL** [comment]
> > **Describe the bug**
> > 
> > **Steps to reproduce (REQUIRED)**
> >  We have not been able to reproduce this issue reliably, but here are the steps we took to encounter it in the first place:
> > 
> > 1. Connect a ledger nano, unlock it, and navigate to the Ethereum app on the Ledger
> > 2. In Metamask, select "Connect Hardware Wallet" from the accounts menu
> > 3. Select Ledger and Connect
> > 4. Select an account and click "Unlock"
> > 5. Click the copy button next to the address to copy the wallet address.
> > 6. Send ETH to that address.
> > 7. Reboot, disconnect the ledger, come back later.
> > 8. Reconnect the ledger nano, unlock it, etc.
> > 9. Attempt to send a transaction from the Metamask account.
> > 10. Approve on ledger
> > 11. Transaction sent
> > 
> > Then
> > 
> > 1. Connect a ledger nano, unlock it, and navigate to the Ethereum app on the Ledger
> > 2. In Metamask, select "Connect Hardware Wallet" from the accounts menu
> > 3. Select Ledger and Connect
> > 4. Select another account (first was already flagged) and click "Unlock"
> > 5. Click the copy button next to the address to copy the wallet address.
> > 6. Send ETH to that address.
> > 7. Reboot, disconnect the ledger, come back later.
> > 8. Reconnect the ledger nano, unlock it, etc.
> > 9. Attempt to send a transaction from the Metamask account.
> > 10. Get an error similar to the effects of #[6011](https://github.com/MetaMask/metamask-extension/issues/6011) - Metamask is sending from a different address than the attached ledger and[ #6012](https://github.com/MetaMask/metamask-extension/issues/6012) Ledger Nano: Metamask Address does not correspond to Ledger 
> > 
> > 12. If you attempt to import another account from the ledger, the original address is not available.
> > 13
> > 
> > 
> > **Expected behavior**
> >  If I connect an account from a ledger nano, I expect that account / address to exist on the ledger nano and/or that I can have control of it.
> > 
> > 
> > **Browser details (please complete the following information):**
> > * OS: MacOS 11.2.3
> > * Browser Firefox
> > * MetaMask Version 9.3.0
> > *
> > 
> > 
> > **Additional context**
> >  I'm not certain how this happened. My understanding is that when a ledger is connected, Metamask asks it for a list of addresses, and those addresses are provided by the nano without any proof that it can sign messages with it. I suspect that some kind of interference (static electricity, gamma rays, a butterfly flapping its wings in China, etc.) caused the initial transmission of the address to be sent incorrectly, but it's hard to say for sure.
> > Ledger Live does not allow a user to connect an account without first confirming the address by clicking a button on the ledger (I'm not sure how this works under the hood, but I have the impression it's signing a message). It strikes me that this could have been avoided if metamask had required the user to sign a message before considering the account connected. 
> > 
> > 
> > 
> > Since I sent my coins to this random address generated by Metamask, I’m no longer able to access.
> > Can you please explain what happened and please give me access to my coins?ered more quickly and make it easier for other devs to find the answer in the future.
> > 
> > **any way to bypass ledger auth or export seedphrase of wallet?**
> > 
> > 
> > 
> > 
> 
>

**Comment by drnick30** [comment]
Did you have a passphrase enabled on the ledger?

**Comment by crypt012** [comment]
> > > Im struggling with this same issue right now and really stressed about it. I tried using MyCrypto tool to FindETH and scanned for addresses with ETH after linking my Ledger, but to no avail. It did not find any ETH addresses with funds! This really sucks bc I know the address and can view it on Etherscan. If anyone can help I am willing to pay them! Thanks.
> > 
> > 
> > Hello, Did you try the following custom path using MEW : m/44'/60'/0'/4/0 ?
> 
> My issues is with MM and Ledger, not sure if that makes a difference. I know the pubhlic wallet address its just no being recognize by my Ledger or picked up when I try to "connect hardware wallet". I tried to input that derivation path into MyCrypto - FindETH - add custom derivation path and the format seems incorrect. Any advice?

Try to connect your ledger to myetherwallet, and choose custom path m/44'/60'/0'/4/0

**Comment by prejudicedad** [comment]
That path doesn't work for some reason it gives me an error - "Cannot read properties of undefined (reading 'then')

**Comment by prejudicedad** [comment]
> Did you have a passphrase enabled on the ledger?
> […](#)
> On Jan 20, 2022, at 3:14 AM, prejudicedad ***@***.***> wrote: ﻿ Im struggling with this same issue right now and really stressed about it. I tried using MyCrypto tool to FindETH and scanned for addresses with ETH after linking my Ledger, but to no avail. It did not find any ETH addresses with funds! This really sucks bc I know the address and can view it on Etherscan. If anyone can help I am willing to pay them! Thanks. Hello, Did you try the following custom path using MEW : m/44'/60'/0'/4/0 ? My issues is with MM and Ledger, not sure if that makes a difference. I know the pubhlic wallet address its just no being recognize by my Ledger or picked up when I try to "connect hardware wallet". I tried to input that derivation path into MyCrypto - FindETH - add custom derivation path and the format seems incorrect. Any advice? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

How do I enable the pass phrase on my ledger I thought this was done automatically by default.

**Comment by drnick30** [comment]
No, it’s not done by default.

**Comment by vlindersteen** [comment]
> > > > @tmashuang I solved this issue.
> > > > actually it’s not a MetaMask bug but a Ledger one. To recover access to “wrong” address user have to enable extended account search in ledger live allow to browse through erroneous accounts, BUT you can’t control them in Metamask even if you see them in your browser extension.
> > > > You have to use Mycrypto tool in order to move funds back to legit account.
> > > 
> > > 
> > > Thanks for this info. I enabled extended account search in ledger live, and then try to "add account" but I got nothing new... How did you find your account with weird derivation path ?
> > 
> > 
> > Connect Ledger through Mycrypto and search the address from there
> 
> I tried that but I only see accounts from mains derivation paths, nothing exotic...
> 
> Edit : I found it and was able to move my funds ! Thank you so much !

Please tell us how you did it!

The custom path you said is not working for me either.

**Comment by RusseII** [comment]
@drnick30 @prejudicedad were you able to figure this out? I had this issue as well and was able to recover the funds https://github.com/MetaMask/metamask-extension/issues/6012#issuecomment-2362336404
