### ISSUE TITLE
Ledger with Metamask: Accounts unexpectedly unavailable. Please report this bug.

### ISSUE THREAD

**Issue by swaylock** [MetaMask/metamask-extension#10880]
**Describe the bug**
As of yesterday, when attempting to connect to several dapps to Ledger accounts imported into metamask I get the following error:

`inpage.js:1 MetaMask - RPC Error: Accounts unexpectedly unavailable. Please report this bug. {code: -32603, message: "Accounts unexpectedly unavailable. Please report this bug."}`

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Open and login to connected ledger device
2. In metamask click "Connect Hardware wallet"
3. Choose ledger account
4. Add to Metamask.
5. Visit dapp, eg. https://app.bancor.network/
6. Click connect wallet on bancor
7. Choose metamask from wallet options
8. In metamask, Select ledger ETH account added in previous steps.
9. In metamask, Click next
10. In metamask click connect.
11. View error message in browser dev tools console.

**Expected behavior**

Connect ledger account to app via metamask.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: OSX, 
 - Hardware Wallet: Ledger 1.2.4-5, Ethereum App Version 1.6.4
 - Browser: Brave browser, Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)
 - MetaMask Version: 9.3.0

**Additional context (Error Messages, etc.)**

This problem is happening on more than one site. Problem is just when trying to connect ledger account to dapp via metamask.

**Comment by swaylock** [comment]
I fixed this by removing re-connecting the hardware accounts.

**Comment by bradwbradw** [comment]
I've seen this error using Trezor, while troubleshooting https://github.com/MetaMask/metamask-extension/issues/10896
