### ISSUE TITLE
MetaMask Pop-up Window Always Unexpectedly Closes Right Before Entering PIN on Hardware Wallet

### ISSUE THREAD

**Issue by faxotherapy** [MetaMask/metamask-extension#10896]
**Describe the bug**
After clicking the Confirm button from MM extension, a pop-up window usually opens to allow me entering my Trezor PIN. Unfortunately, the pop-up window, for unknown reasons to me, unexpectedly and immediately closes before allowing me to enter my PIN. This is new, I never encountered such issue. In an attempt to isolate issue, I disabled pop-up blocking feature of Firefox, but problem persists. In fact, even though with enabled pop-up blocking feature of Firefox, MetaMask always opened a pop-up window.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Approve/Swap on, e.g., Uniswap
2. Click on Confirm button in MM extension

A new browser window should open (instead of a tab even tough tab function has been activated in Firefox), but closes immediately preventing me from entering PIN on hardware wallet.

**Expected behavior**
In the old days, before ver. 1.9.3, everything worked fine. Pop-up window remains open.

**Screenshots**

![MM-Trezor-Issue](https://user-images.githubusercontent.com/6538008/115117718-ed986e00-9f97-11eb-9ac5-d59d79a08177.gif)

**Browser details (please complete the following information):**
 - OS: MacOS 10.14.6
 - Hardware Wallet: Trezor 1.9.4
 - Browser: Firefox 87
 - MetaMask Version: 9.4.0

**Additional context (Error Messages, etc.)**

The issue seems to appear when Trezor has not yet been “logged in” with PIN before interacting with MM.

**Comment by bradwbradw** [comment]
This is happening to me all the time now too, I basically can't interact with any dapps at all through my Trezor :(

**Comment by bradwbradw** [comment]
I just noticed there's an issue at trezor-connect too: https://github.com/trezor/connect/issues/784

**Comment by onetwoitsthewu** [comment]
having the similar issues as well as other errors including "unable to claim interface" and "device was disconnected." other times the pop up window just shows "loading" forever. any updates on this? all of my crypto are effectively stuck on my trezor right now as i can't do anything with my funds.

**Comment by HeroHann** [comment]
The issue is still not resolved.
I opened an issue with Trezor: https://github.com/trezor/trezor-firmware/issues/1762
Answer: Metamask uses the wrong derivation path for testnet. Seems Metamask needs to fix this.

This issue is open for some time. Any ETA on it? With this state no Trezor user can test the Rinkeby Swap Feature on Metamask with the Trezor.

In relation to this see also: https://github.com/trezor/connect/issues/784

**Comment by MrSavvyCoins** [comment]
After also suffering with the phantom disappearing Approval window for months, I've come to terms with needing to import the wallet back into my old Chrome browser. I've failed to escape our Google overlords.

**Comment by GaylordTuring** [comment]
I can report that I have the very same problem using my Ledger. It works to send ETH or tokens, but when interacting with a smart contract in some more advanced way, the pop-up window just closes itself.

**Comment by meckin** [comment]
I don't have this issue with ledger, but with Trezor its extremely annoying. Often need to restart browser a handful of times. It seems to happen when Trezor goes to sleep and wakes up.

**Comment by meckin** [comment]
Any update from the MM team?

**Comment by anomtttt** [comment]
> I'm getting "Popup error: Unable to establish connection with iframe" using a trezor model T and metamask on arch linux firefox.

I can't take credit for this, I found the answer on another forum. The solution ..... use MS Edge and install the Metamask extension . Solved my problem. Meta really need to sort their sh8t out.

**Comment by BreakStacks** [comment]
Wow guys! Last version Tor Browser is worked Metamask + Trezor :D

11.0 (based on Mozilla Firefox 91.3.0esr) (64-bit)

**Comment by MrSavvyCoins** [comment]
Same for me! I was VERY surprised.

**Comment by theorbital** [comment]
I have tried chrome as well as microsoft edge and the pop up window is still automatically closing on me and I am unable to complete my transaction.

**Comment by darkwing** [comment]
I was able to reproduce this with no special steps on Mac:

1. I added a new account on my Trezor Model T
2. Tried sample send to myself
3. Window pops up very briefly, then closes before I can take any action. 

The background console shows the following error:
<img width="1124" alt="FKP" src="https://user-images.githubusercontent.com/46655/162483714-26090cff-3dc8-4d89-bb89-a03d91fa0c10.png">

**Comment by ss18ping** [comment]
Are there any updates on the issue? I've been experiencing this for years now with the Trezor One, read this and similar threads two years ago, but nothing seems to have changed. This happens regularly on weak machines with 8GB of RAM (Macbooks for example), if the network is congested or there is some other load on the computer, the Trezor popup opens and immediately closes. Some solution is needed so that the Trezor window simply does not close before all the data is loaded. This happens regardless of which browser is used and which extensions are installed, it's a matter of memory usage and load on the computer. I waited for several years that the problem would somehow be solved, but nothing has changed. Too bad everything is still the same.

**Comment by AlexJupiter** [comment]
Are people still experiencing this issue?

**Comment by sime** [comment]
@AlexJupiter related thread on Trezor: https://github.com/trezor/connect/issues/784

**Comment by aspiers** [comment]
In my case I finally traced it to MetaMask's restricted site access preventing the Trezor popup from opening:

https://github.com/MetaMask/metamask-extension/issues/17607#issuecomment-1552131562

**Comment by plasmacorral** [comment]
Freshly reported in issue #19476 impacting both Chrome and Brave

**Comment by lostintime101** [comment]
The browser window closing unexpectedly issue still happens almost every time I use my Trezor with MM. 
The only way I can get it to work is to restart the computer, then it will work for the first transaction, possibly a second transaction also if I'm lucky, after that, the same popup disappearing continues. The only thing I've found that helps is a full restart. 
I'm using the latest version of MM and Trezor app/firmware, MM extension is set to "all sites", Brave chromium is up to date, ad blockers turned off. 
It's really frustrating.

**Comment by jonatascm** [comment]
Is there any update on this issue? It still happens when you use trezor and chrome.

**Comment by Hannsek** [comment]
Trezor Connect was updated and the issue is fixed. Metamask, however, has to manually update [npm package](https://www.npmjs.com/package/@trezor/connect) otherwise it won't work. :/

**Comment by mkingp** [comment]
I just started having this issue today on Chrome and Edge. 

Even though I have already updated the Metamask Chrome Extension, Trezor Suite. 

I have also tried setting the Metamask Extension's setting to Connect to All Sites. It didn't work. 

Basically can't do any transaction with my Trezor now, as it is surprisingly hard to find a Metamask alternative that supports Trezor.
