### ISSUE TITLE
metamask hungarian firefox extension wrong translation

### ISSUE THREAD

**Issue by bobalazs** [MetaMask/metamask-extension#10904]
explorer url letiltása (nem kötelező)
incorrectly translated. 
does not mean explorer block, but 
block as in "'forbid to do"

**Comment by Gudahtt** [comment]
Thanks for the report! That message is located here: https://github.com/MetaMask/metamask-extension/blob/develop/app/_locales/hu/messages.json#L704

Do you have any suggestions on what a better translation would be?
