### ISSUE TITLE
Allow hiding ETH-like tokens

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#10901]
Consider the below image. The asset is "ETH", and we're not showing the three-dot menu in the upper-right corner to enable hiding the asset. All good? No! It's not native ETH, but a token named ETH. I'm gonna bet our logic for hiding/showing the menu is too naive to handle this case. We should fix it.

The user that reported this also says that resetting their account does not hide or remove this asset.

<img width=351 src="https://user-images.githubusercontent.com/25517051/115312181-bb1c7b80-a125-11eb-9b44-a2a0eedf3aac.png"/>

**Comment by gigamesh** [comment]
Also, resetting the account (Advanced -> Reset Account) doesn't remove it. I have to completely reinstall.

**Comment by danjm** [comment]
Related to https://github.com/MetaMask/metamask-extension/pull/10938

**Comment by adonesky1** [comment]
@danjm @rekmarks I wasn't able to reproduce this issue on my [branch](https://github.com/MetaMask/metamask-extension/pull/10938) (the related branch highlighted by Dan above) that is currently in PR review. I think this can be closed once that PR has been merged.

![Screen Shot 2021-04-27 at 3 27 34 PM](https://user-images.githubusercontent.com/34557516/116308718-78822100-a76d-11eb-8fa0-bbb4f859549a.png)
![Screen Shot 2021-04-27 at 3 27 24 PM](https://user-images.githubusercontent.com/34557516/116308735-7b7d1180-a76d-11eb-8260-eaf35b504e80.png)

**Comment by adonesky1** [comment]
@danjm @rekmarks I've just doubled checked this and confirmed that this is no longer happening. I'm going to close this issue.
