### ISSUE TITLE
Can't proceed with gas limit set to 300000 or 300001

### ISSUE THREAD

**Issue by d10r** [MetaMask/metamask-extension#10919]
I struggle to find words for this, please look for yourself.

https://user-images.githubusercontent.com/5479136/115932808-f99b9880-a48d-11eb-9400-b6507ae35db2.mp4

Metamask 9.4.0, connected to Kovan, in Chrome on Linux

**Comment by jackaldridge** [comment]
So it looks like the `gasLimit` [here](https://github.com/MetaMask/metamask-extension/blob/bc24d9e696560780c13c94a39393cd8b6bf16147/ui/pages/send/send-footer/send-footer.component.js#L116) is mostly being represented as a hexadecimal string without the `'0x'` prefix. I'm getting the prefix on the first render and unprefixed every one after that.

When it gets compared to the numeric literal `5208` the type coercion means it'll often end up as `NaN` and the comparison will be false (no error). But... if the unprefixed hexadecimal string is coercible to a number _and_ it's low enough, this comparison will be true.`300000` is `'493e0'` in unprefixed hexadecimal form, so `493` after type coercion.

I'll put up a PR for this now.

**Comment by danjm** [comment]
Fixed with https://github.com/MetaMask/metamask-extension/pull/10965
