### ISSUE TITLE
Could  not change nonce when approving  with  “Customize transaction nonce” setting is on

### ISSUE THREAD

**Issue by wanshan1024** [MetaMask/metamask-extension#10910]
**Describe the bug**
Could  not change nonce when approving  with  “Customize transaction nonce”  setting is on.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to  Settings -> Advanced ,  
2. Set  “Customize transaction nonce” to ON.
3. Try to approve in a dapp.
4.  Could not find the custom nonce input.

**Expected behavior**
Display custom nonce input.

**Browser details (please complete the following information):**
 - OS: OS X
 - MetaMask Version:  8.1.11

**Comment by brad-decker** [comment]
this is resolved by #10595, which while not yet released, soon will be. :D
