### ISSUE TITLE
Metamask Firefox white/blank screen. Please help

### ISSUE THREAD

**Issue by KabelMouse** [MetaMask/metamask-extension#10918]
I really don't know why this happened. This happened to me today when I wanted to open Metamask.
I forgot to back up the seed phrase. I followed the instructions from here [https://metamask.zendesk.com/hc/en-us/articles/360018766351](https://metamask.zendesk.com/hc/en-us/articles/360018766351) but it didn't work.

Please help me. I have about $6,000 in my account. I am very frustrated with this problem.

**Screenshots**
[https://i.imgur.com/axAO64X.jpg](https://i.imgur.com/axAO64X.jpg)

**Browser details:**
 - OS: Windows
 - Browser: Firefox Browser 88.0 (64-bit)
 - MetaMask Version: 9.4.0

**Additional context**
I'll give $500 to anyone who can help me get my Metamask wallet back.

**Comment by danjm** [comment]
possibly related to https://github.com/MetaMask/metamask-extension/issues/9196

**Comment by danjm** [comment]
Can you check if there is an error message in the dev console of the extension. Do do so, follow this example:


https://user-images.githubusercontent.com/7499938/116287008-77032980-a76a-11eb-9a89-0203c69245bb.mp4

**Comment by KabelMouse** [comment]
Dev console error message
[Dev Console Error](https://i.imgur.com/2ditQ2a.png)

Vault data inside file located at C:\Users\XXXX\AppData\Roaming\Mozilla\Firefox\Profiles\XXXXXXX.default-release\storage\default\moz-extension+++XXXXX-XXXXX-XXXXX-XXXX-XXX^userContextId=XXXXXX\idb\3647222921wleabcEoxlt-eengsairo.sqlite
[Vault Data](https://i.imgur.com/OrwdgzP.png)

I opened the file using the EmEditor application. Open it as a hexadecimal binary and decode it to ISO-8859-1 using Python. Because it can't decode to UTF-8.

Firefox is closed. But my storage addons still have files like 3619119340leogcaarlof.sqlite-shm and 3619119340leogcaarlof.sqlite-wal
Which should not be there when Firefox is closed. I did tests with several new wallets.
So I thought, Metamask looks like it crashes before all processes stop properly.

This issue has occurred for some users using Firefox. Please provide an easy way for Firefox users to get their data Vault as easily as Chrome.

> Can you check if there is an error message in the dev console of the extension. Do do so, follow this example:
> 
>  Peek.2021-04-27.15-08.mp4

Dev console error message
[Dev Console Error](https://i.imgur.com/2ditQ2a.png)

Vault data inside file located at C:\Users\XXXX\AppData\Roaming\Mozilla\Firefox\Profiles\XXXXXXX.default-release\storage\default\moz-extension+++XXXXX-XXXXX-XXXXX-XXXX-XXX^userContextId=XXXXXX\idb\3647222921wleabcEoxlt-eengsairo.sqlite
[Vault Data](https://i.imgur.com/OrwdgzP.png)

I opened the file using the EmEditor application. Open it as a hexadecimal binary and decode it to ISO-8859-1 using Python. Because it can't decode to UTF-8.

Firefox is closed. But my storage addons still have files like 3619119340leogcaarlof.sqlite-shm and 3619119340leogcaarlof.sqlite-wal
Which should not be there when Firefox is closed. I did tests with several new wallets.
So I thought, Metamask looks like it crashes before all processes stop properly.

This issue has occurred for some users using Firefox. Please provide an easy way for Firefox users to get their data Vault as easily as Chrome.

**Comment by KabelMouse** [comment]
My problem is resolved. I hired Freelancer to convert some of the weird characters in the screenshot above.
But I'm afraid something like this will happen again to me or other users who forget to save their seed phrase.

**Comment by jonathan-s** [comment]
For anyone that stumbles upon this by searching have a look at https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data
