### ISSUE TITLE
Transaction errors are not shown

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1091]
In our `sendTx` UI action, if the RPC throws an error, like an `insufficient implicit gas` error (easily reproduced by setting a low gas limit from the transaction params), the UI transitions to an empty view, and does not seem to show an error.

**Comment by Zanibas** [comment]
Can we revisit this issue since our UI has changed so much for our gas params? Can we still reproduce these issues?

**Comment by flyswatter** [comment]
Related to #1254.

**Comment by Zanibas** [comment]
It seems we don't use sendTx anymore...shall we remove it from the codebase?

**Comment by flyswatter** [comment]
That's big if true. And yes, always remove dead code.

**Comment by flyswatter** [comment]
Related to #1662

**Comment by flyswatter** [comment]
I investigated this a bit, because I think we should fix this asap. I got re-acquainted with why our architecture isn't friendly to fixing this bug at the moment.

There are really two problems at play, one is simple (and I'm fixing), the other is a bit deeper, and requires some harder work.

Step 1 is that in case of error, we don't do anything, and so we see a spinner forever.
https://github.com/MetaMask/metamask-extension/blob/master/ui/app/actions.js#L430

To understand the second problem, you should refer to this line of our transaction manager:
https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/controllers/transactions.js#L252

There you can see that if submitting a transaction fails, we set the tx as failed, and then return an error. The problem is that some errors are actually validation issues, where we actually want to just go back to editing the tx, and warn the user what was wrong.

A couple things I know these errors can be:

- Nonce is too low
- Gas limit is too high

Gas limits are a good validation, but nonce being too low isn't even something we have UI for, so in that case, we might want to, I don't know, detect it and adjust our nonce logic? Up for some discussion. No doubt there are a variety of possible errors here, different for different clients, which should be handled specifically.

That's a harder problem, so we can leave it for a longer term, may not even be worth doing. Maybe it's fine to fail a tx that fails a server-side validation, and leave the message in the failed tx message field.

Fixed this in a PR coming soon.

Also, confirmed we can remove `sendTx` from actions.
