### ISSUE TITLE
Missing language messages

### ISSUE THREAD

**Issue by sdwillbrand** [MetaMask/metamask-extension#10922]
**Describe the bug**
The MetaMask Extension is missing some translation for the german language

**Screenshots**
![MetaMask](https://user-images.githubusercontent.com/44726085/115970567-75a3e800-a543-11eb-8444-24af33a99788.PNG)
![MetaMask_2](https://user-images.githubusercontent.com/44726085/115970569-7a689c00-a543-11eb-8766-41a198d49522.PNG)

Buy -> Kaufen
Swap -> Tauschen
Assests -> Vermögen
Activity -> Aktivitäten

**Comment by countersoda** [comment]
I want to add the fixture for this issue but I am not able to publish my branch. Could somebody help me?

**Comment by mcmire** [comment]
It looks like all of the words listed here have been translated except for "Swap". That remains untranslated for some reason.
