### ISSUE TITLE
wrong address in metamask from ledger

### ISSUE THREAD

**Issue by itboy79** [MetaMask/metamask-extension#10928]
Describe the bug

Steps to reproduce (REQUIRED)
 We have not been able to reproduce this issue reliably, but here are the steps we took to encounter it in the first place:

Connect a ledger nano, unlock it, and navigate to the Ethereum app on the Ledger
In Metamask, select "Connect Hardware Wallet" from the accounts menu
Select Ledger and Connect
Select an account and click "Unlock"
Click the copy button next to the address to copy the wallet address.
Send ETH to that address (on BSC).
Reboot, disconnect the ledger, come back later.
Reconnect the ledger nano, unlock it, etc.
Attempt to send a transaction from the Metamask account.
Approve on ledger
Transaction sent
Then

Connect a ledger nano, unlock it, and navigate to the Ethereum app on the Ledger

In Metamask, select "Connect Hardware Wallet" from the accounts menu

Select Ledger and Connect

Select another account (first was already flagged) and click "Unlock"

Click the copy button next to the address to copy the wallet address.

Send BTCB to that address (on BSC).

Reboot, disconnect the ledger, come back later.

Reconnect the ledger nano, unlock it, etc.

Attempt to send a transaction from the Metamask account.

Get an error similar to the effects of #6011 - Metamask is sending from a different address than the attached ledger and #6012 Ledger Nano: Metamask Address does not correspond to Ledger

If you attempt to import another account from the ledger, the original address is not available.

Expected behavior
 If I connect an account from a ledger nano, I expect that account / address to exist on the ledger nano and/or that I can have control of it.

Browser details (please complete the following information):

OS: MacOS 11.2.3
Browser Firefox
MetaMask Version 9.3.0
Additional context
 I'm not certain how this happened. My understanding is that when a ledger is connected, Metamask asks it for a list of addresses, and those addresses are provided by the nano without any proof that it can sign messages with it. I suspect that some kind of bug caused the initial transmission of the address to be sent incorrectly, but it's hard to say for sure.
Ledger Live does not allow a user to connect an account without first confirming the address by clicking a button on the ledger (I'm not sure how this works under the hood, but I have the impression it's signing a message). It strikes me that this could have been avoided if metamask had required the user to sign a message before considering the account connected.

Since I sent my coins to this random address generated by Metamask, I’m no longer able to access.
Can you please explain what happened and please give me access to my coins?

any way to bypass ledger auth or export seedphrase of wallet?

**Comment by itboy79** [comment]
@tmashuang this bug is still open! I cannot have access to my tokens. Metamask version is the last

**Comment by ApacheSub** [comment]
@itboy79 Do you think this tool would be able to help? https://github.com/ApacheSub/bsc_recoverfunds_extension

I released it for users who had similar thing happen to them on Binance Smart Chain and the Binance Chain Wallet extension. In that case the extension generated addresses that you couldn't spend from as is. It turns out it used a different derivation path.
