### ISSUE TITLE
Metamask showing Connecting to Binance Smart chain

### ISSUE THREAD

**Issue by Macoinx** [MetaMask/metamask-extension#10920]
Guys, I am trying to use metamask and starting from this evening I cant access to BSC.
Metamaks is just showing " Connecting to Smart chain" , after a while it shows an error " oops somthign went wrong".

I really dont know what to do. Thanks for the help.

![image](https://user-images.githubusercontent.com/83096763/115934027-69128780-a490-11eb-966c-a5bb9dc573c9.png)
![image](https://user-images.githubusercontent.com/83096763/115934080-86475600-a490-11eb-8dc1-5a7a05dbb165.png)

**Comment by nhoclove9x** [comment]
me too, i cant change eth network to bsc

**Comment by Macoinx** [comment]
Put this RPC https://bsc-dataseed.binance.org/

**Comment by nhoclove9x** [comment]
> Put this RPC https://bsc-dataseed.binance.org/

It's worked. Thanks bro
