### ISSUE TITLE
Metamask security - stolen funds

### ISSUE THREAD

**Issue by alainaemmanuel** [MetaMask/metamask-extension#10926]
Hello Metamask ,
I think that there is a security gap in your extension. I've not been able to use the extension on my laptop without using my seed phrase each time. 

Yesterday someone was able to steal all of my crypto funds because of this. 

Whilst connecting metamask to a site, I was prompted to share my seed phrase and was not suspicious as it's the only way for me to use metamask.  

Within seconds my account had been emptied (~$25K at the time), and transferred it to theirs. There was no feature I could use to cancel the transactions or even to trace their movements if the crypto is moved elsewhere.

Please could someone support?  I would be grateful if i could get my funds back! Thank you in advanced. 

My previous address: 0x17A80f42398f295720A550e46c2011BC7b4160EE 

Thief's ETH address: 0xB81E062eb44eABc104A75E3D397610ee64fdD9c8 

Everything sitting in the wallet right now is mine and is now worth ~$30.7K. This is all my savings in crypto over the past 5 years.

**Comment by danjm** [comment]
It looks like you might have used a phishing site and your seed phrase has been compromised. This article can shed more light on this situation https://medium.com/metamask/rotten-seed-phrases-a-new-scam-targeting-crypto-users-b414f9ef292e

You can open a ticket to share more information via https://metamask.zendesk.com/hc/en-us/requests/new

**Comment by alainaemmanuel** [comment]
Hi Dan,

Thank you for your fast response and for the article.

This scam transaction took place on my mobile, using the metamask which I
downloaded from Google play. I've also checked my PC and am certain that I
downloaded from the correct metamask site.

The scammer moved all my crypto to his account except anything being
staked/in a liquidity pool. When he did this there was nothing I could do
at the time to stop the transfer.

1. Is it possible to get my funds back at all from them or is there anyone
who can support in doing this?

2. How do I get my staked crypto across to a new wallet if the scammer
still has access to my private keys? The other day I sent some ETH across
*before* attempting to move the crypto. They noticed and nicked the ETH
too.

The article says to send your crypto across and then send your ETH.  I'll
try this later tonight, but I'm worried that this will highlight the assets
they've missed. Eg if there's a delay in the ETH transfer to the wallet.

3. Is there any platform to report them and their ETH account? Maybe a team
who can monitor their movements and can flag it to an exchange if they try
to sell?

4. Is there any way to have stopped the transfer using metamask?  I keep
wondering.


Thanks again for all your help.

Alaina
