### ISSUE TITLE
Unclear "Confirmed" screen when trying to cancel a transaction

### ISSUE THREAD

**Issue by samajammin** [MetaMask/metamask-extension#10927]
**Describe the bug**

I have a transaction that has been "Pending" for >24 hours:

![Image 2021-04-25 at 12 03 40 PM](https://user-images.githubusercontent.com/8097623/116006081-a37a4280-a5be-11eb-924c-f3cad11961c6.jpg)

If I click to "Cancel" & click "Yes, let's try it"
![Image 2021-04-25 at 12 03 19 PM](https://user-images.githubusercontent.com/8097623/116006093-aaa15080-a5be-11eb-9a5f-c5fa273e220f.jpg)

This "Confirmed" screen pops up:
![Image 2021-04-25 at 12 03 23 PM](https://user-images.githubusercontent.com/8097623/116006118-c147a780-a5be-11eb-9c60-828652a2071b.jpg)
Clicking "Ok" takes me back to my wallet with no change to my transaction history. I'm unable to speed up or cancel this transaction. I tried to create a new transaction but it is stuck as "Queued".

What does "Your initial transaction was confirmed by the network" mean?
Does that mean my pending transaction has gone through? In that case, the bug here is that the transaction still displays as "Pending" on my "Activity" tab. I suspect the transaction hasn't gone through, as no transaction shows up for my address's activity in Etherscan.

**Steps to reproduce (REQUIRED)**
See above.

**Expected behavior**

I expect to be able to "cancel" my transaction but I am stuck in this loop. I also expect to be able to create a new transaction (to replace my last pending transaction) but it is stuck in "Queued".

**Screenshots**
See above.

**Browser details (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser: Brave v 1.21.77
 - MetaMask Version: 9.4.0

**Comment by samajammin** [comment]
It seems all txs I create in MetaMask now show as "pending" & don't create a tx hash. Wouldn't a tx hash be generated when creating a tx?

I tried selecting settings --> advanced --> reset account as some GH issues recommended. Tried again afterwards but every tx is added to my "queue". Not sure why it's in "queue" as I don't have any history / record of any other txs.

Any guidance appreciated 🙏

**Comment by danjm** [comment]
This is a strange state that your metamask is in. Can you confirm that there are no pending transactions in the account on etherscan?

And for us to best help you, it would be good to see your state logs. Can you submit a request to support via https://metamask.zendesk.com/hc/en-us/requests/new and then we can communicate with you there.
