### ISSUE TITLE
EIP712 request auto-fails unless expanded view is open

### ISSUE THREAD

**Issue by alex-miller-0** [MetaMask/metamask-extension#10931]
### Describe the bug

We have added EIP712 support to the GridPlus Lattice and have enabled support on our MetaMask fork, which is branched off v9.4.0 and contains only basic changes to allow Lattice support (see [diff](https://github.com/MetaMask/metamask-extension/compare/v9.4.0...GridPlus:fork/9.4.0)).

When testing EIP712 using https://trade.dydx.exchange I am running into a very strange issue that appears to come from the extension. I have not been able to debug because it is related to some event firing and I'm not an expert in how MetaMask drives events, but there is a good chance this is a bug coming from MetaMask itself.

**Summary:** 
* **Under normal circumstances, the EIP712 message is auto-rejected but the request is still sent to my hardware wallet.**
* **When the EIP712 approval box is blocked from automatically popping up (i.e. when the MM expanded view is also open), the signing process works correctly.**

### To Replicate

When clicking on `Create Account` under normal circumstances, the approval box pops up as I would expect:

![image](https://user-images.githubusercontent.com/7378490/116140131-8156f200-a69c-11eb-9c66-9381e0ec3362.png)

After clicking `Sign`, an error is immediately thrown:

![image](https://user-images.githubusercontent.com/7378490/116140218-a0ee1a80-a69c-11eb-946e-962f81ca7e47.png)

The error text is:

> MetaMask Message Signature: User denied message signature.

which gets thrown in `addUnapprovedMessageAsync` (`typed-message-manager.js`)

But here's the weird thing: **the request still goes through to my Lattice**. I can sign it and the response is unhandled because this error has already been thrown.

Even weirder: I can actually get the process to work, but I have to **open MetaMask in an expanded view** and have that window visible. This seems to block the approval box from popping up, meaning I have to click on my extension icon and I see a badge:

![image](https://user-images.githubusercontent.com/7378490/116140420-ee6a8780-a69c-11eb-8e76-11c15dd3b690.png)

When I click `Sign` here, the request goes through to my Lattice, I sign it, and the app accepts the signature. Here's the result, which we expect to fail because dydx wants an account with >0 ETH and my dev account is broke:

![image](https://user-images.githubusercontent.com/7378490/116140550-1823ae80-a69d-11eb-9e7e-25a293f2269f.png)

Another strange thing is that *this works fine when I use the default MetaMask wallet.*

It seems like this is specifically related to calling `signTypedData` using a hardware wallet. Looking again at our fork's [diff](https://github.com/MetaMask/metamask-extension/compare/v9.4.0...GridPlus:fork/9.4.0), I don't see anything we are doing differently than Ledger/Trezor which would cause this behavior, but I'm not an expert in the MetaMask code base so perhaps I'm missing something.

I figured I would drop this here because I'm not aware of any hardware wallets successfully implementing EIP712 and using it via MetaMask so perhaps there's dragons in here. If I can help please let me know.

**Browser details (please complete the following information):**
 - OS: macOS
 - Hardware Wallet: Lattice (via fork)
 - Browser: 90.0.4430.85 (Official Build) (arm64)
 - MetaMask Version: 9.4.0

**Comment by alex-miller-0** [comment]
The problem is coming from `metamask-controller.js`: `cancelTypedMessage` is firing ~100ms after approving the transaction in the pop-up box. This actually *does* happen for the native MetaMask wallet as well, but because that signature is generated so quickly, it is of no consequence. Since sending the message to a hardware wallet has a longer latency, those requests are impacted by this issue.

I'm guessing there is an event firing somewhere else in the system and that there is a name collision with the typedMsg cancel event.

I was able to resolve the issue by simply blocking these events in `rejectMsg`. I've tested and this works correctly, meaning I can still manually cancel the transaction and also signatures now work.

`typed-message-manager.js`:

```
  rejectMsg(msgId) {
    const msg = this.getMsg(msgId);
    if (!msg) {
      throw new Error(
        `TypedMessageManager - Message not found for id: "${msgId}".`,
      );
    }
    if (msg.status !== 'approved') {
      console.log('manager: rejectMsg', msgId)
      this._setMsgStatus(msgId, 'rejected');
    }
  }
```

**Comment by alex-miller-0** [comment]
This is still an issue in 9.5.9 and appears to be affecting Ledger users as well: 
![image](https://user-images.githubusercontent.com/7378490/121594340-8f6d9180-ca02-11eb-8e27-e4a1a0e33f74.png)

Just trying to be a good citizen here. It does not affect us, as I have patched our fork with the above code.

Probably worth looking into, as I suspect it prevents EIP712 signing on all hardware wallets.

**Comment by danfinlay** [comment]
Thanks for highlighting this, getting this prioritized sooner.
