### ISSUE TITLE
Source map warnings in console

### ISSUE THREAD

**Issue by probablykasper** [MetaMask/metamask-extension#10940]
**Describe the bug**
When opening the console on any webpage, Metamask source map warnings show up:
![image](https://user-images.githubusercontent.com/11315492/116325610-d4c36000-a7c2-11eb-8514-5a4d1b5de5ff.png)

I believe this was supposed to be fixed by #10695

**Browser details**
 - OS: macOS 10.15.7
 - Browser: Brave 1.23.73
 - MetaMask Version: 9.4.0

**Comment by tmashuang** [comment]
https://github.com/MetaMask/metamask-extension/compare/v9.4.0...HEAD
