### ISSUE TITLE
Removal Error on Custom Token Entry

### ISSUE THREAD

**Issue by akissz** [MetaMask/metamask-extension#10950]
The plugin hides/removes custom token entries if you do a quote and click cancel. Including when the wallet has value in the custom entry.
The plugin does not remove non-custom entries if you do a quote and click cancel.
Seems like a bug, please make it so custom entries are not hidden/removed when you do this canceling of a quote.

**Comment by danjm** [comment]
@dan437 this appears to be a swaps bug, worthy of investigation
