### ISSUE TITLE
Can't add token with a Symbol longer than 6 charachters

### ISSUE THREAD

**Issue by jamiehewitt15** [MetaMask/metamask-extension#10973]
**Describe the bug**
When attempting to add a token that has a symbol length of more than 6 characters I am getting the following error message in the console:
```
MetaMask - RPC Error: Invalid symbol "QUICRA-0": longer than 6 characters. 
```

**Steps to reproduce**
Steps to reproduce the error:

1. Go to https://market-git-issue-549-token-length-oceanprotocol.vercel.app/asset/did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38 
2. Click 'Connect Wallet' and select metamask
2. Once metamask is connected, click on 'ADD QUICRA-0 TO WALLET'
3. Open the console

**Expected behavior**
To my understanding it should be possible to add custom tokens with symbols up to 12 characters long. 
This was implemented here: https://github.com/MetaMask/metamask-extension/pull/5816
And appears to still be implemented here: https://github.com/MetaMask/metamask-extension/blob/bc24d9e696560780c13c94a39393cd8b6bf16147/ui/pages/add-token/add-token.component.js#L206

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox Browser 88.0 (64-bit)]
 - MetaMask Version 9.4.0

**Comment by jamiehewitt15** [comment]
I'm also experiencing the same issue on Chrome with MetaMask Version 9.4.0

**Comment by tmashuang** [comment]
Closed, https://github.com/MetaMask/metamask-extension/pull/10670 has been merged.

**Comment by jamiehewitt15** [comment]
@tmashuang I'm using Metamask 9.4.0 (which is the latest) and it's still giving me the `Invalid symbol "QUICRA-0": longer than 6 characters.` error. Do you know when #10670 will be released?
