### ISSUE TITLE
[Feature] More interactive web3 API for listing tokens

### ISSUE THREAD

**Issue by DaniellMesquita** [MetaMask/metamask-extension#10975]
SUSHI can't detect when an token has been already added; this is an missing web3 API.

![Screenshot from 2021-05-03 13-43-52](https://user-images.githubusercontent.com/6765277/116905693-b374d080-ac15-11eb-8cd6-f4bc7db093f3.png)

**Comment by tmashuang** [comment]
You can post feature request on the forum, [Community Forum](https://community.metamask.io/c/feature-requests-ideas/13).
