### ISSUE TITLE
MM + Hardware Wallet Funds Locked

### ISSUE THREAD

**Issue by walkingbackward** [MetaMask/metamask-extension#11002]
Issue:

All Uniswap V2 users are stuck; unable to approve and move funds with metamask and hard wallets.

Is there a pull request that is being worked on to fix this ongoing issue ( ref issue #10240 )? It would be good to have some clarity on the status on this bug.

https://github.com/MetaMask/metamask-extension/issues/10240

**Comment by danjm** [comment]
#10240 is being worked on. Closing as a duplicate.
