### ISSUE TITLE
Transaction Nan Failed : Error while formatting outputs from RPC

### ISSUE THREAD

**Issue by Guiguizbar** [MetaMask/metamask-extension#11027]
Hi community,

I have been trying for a day to solve a problem but I didn't find the solution yet, so I require your help.

Here is my problem:
I have a permanent probleme with the quantity max of gaz in the transactions, it doesn't set itself automactically anymore. And i can't make any transaction anymore, even with setting it myself.

It always says : 
Transaction NaN failed! Error: [ethjs-query] while formatting outputs from RPC '{"Value":{"code:-32603,"data":{"code":-32000 

![1 PB metamask](https://user-images.githubusercontent.com/83974994/117699568-4b019280-b1c5-11eb-9ff5-0250af88b2c7.png)

I Hope you can help me ! Thanks in advance :)

**Comment by danjm** [comment]
Is this transaction one you are creating from MetaMask? Or is this intiated by a dapp? If so, are you able to share the dapp, or give extra information about what you were doing when you hit this error.
