### ISSUE TITLE
Error loading token balance

### ISSUE THREAD

**Issue by KipGod** [MetaMask/metamask-extension#11020]
So I transferred DAI from Ethereum mainnet to FTM mainnet but I got this error and I can't use the tokens even though I see the transactions and the balance correctly on Etherscan. 
![metamask error](https://user-images.githubusercontent.com/50038443/117593544-17156700-b10a-11eb-84d3-6e718da73e34.JPG)

**Comment by danjm** [comment]
This is a common problem with tokens on the fantom network. We may not be able to do anything about this, but it does deserve investigation to check that our method of fetching balances is appropriate for all custom networks.

It is possible that this just is a problem with the rpc provider.

**Comment by keybreak** [comment]
I see this on Binance chain all the time as well, it's insufferable...
Makes it very hard to work in some key moments when you need to swap very quickly.

**Comment by keybreak** [comment]
@sahar-fehri 
Yep, it seems to work!
Sorry for being to late for the party, and thank you! :+1:
