### ISSUE TITLE
Bug of new version which caused by can't find the zh_CN locale

### ISSUE THREAD

**Issue by Ryan2128** [MetaMask/metamask-extension#11033]
Reproduce steps: 
1. just login wallet
2. open wallet

Result:

![image](https://user-images.githubusercontent.com/33176053/117746486-16cab800-b23f-11eb-8c25-a905b4b34208.png)

![image](https://user-images.githubusercontent.com/33176053/117746549-2a761e80-b23f-11eb-8c7e-be4a86d60792.png)

Expect:
If it is not a bug, how should I avoid the error?

**Comment by tmashuang** [comment]
I'm guessing the preset language was zh_CN before the update?

**Comment by oscnet** [comment]
same issue...

**Comment by Ryan2128** [comment]
> I'm guessing the preset language was zh_CN before the update, missing this in the reproduction?

Do you know how to clear the default language?

**Comment by tmashuang** [comment]
Full list of language codes, https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry. Effected language s codes are `zh_CN`, `pt_PT`, `pt_BR`, `es_419`

**Comment by jianhun** [comment]
set https://chrome.google.com/ language to Engilsh, and reinstall, it worked

**Comment by tmashuang** [comment]
> The language used in my browser settings is always English.

When you navigate to your browser's preferred language list, in this url, `chrome://settings/?search=language`. Move `English` to the top of the list.

**Comment by Ryan2128** [comment]
> set https://chrome.google.com/ language to Engilsh, and reinstall, it worked

I tried it, but no effect.

**Comment by vorg-san** [comment]
I tried changing the language and reinstalling metamask extension, but it didn't work.

Then i tried changing the language, uninstall extension, restart pc, install extension and IT DID WORK.

**Comment by Ryan2128** [comment]
> I tried changing the language and reinstalling metamask extension, but it didn't work.
> 
> Then i tried changing the language, uninstall extension, restart pc, install extension and **IT DID WORK** .

OK, I'll try, I just now reinsalled chrome and extension.

**Comment by Ryan2128** [comment]
Still not work.😭

**Comment by vorg-san** [comment]
> Still not work.😭

Did you reboot the computer between uninstall and install of the extension? I did not need to uninstall chrome.

**Comment by Bit-Bag** [comment]
no other way to fix ti ? if I don't remember the seed.

**Comment by Bit-Bag** [comment]
> same issue.Tossing all morning.It can be used only after 9.4 is manually installed.

reintall will clean the data?

**Comment by Ryan2128** [comment]
> > Still not work.😭
> 
> Did you reboot the computer between uninstall and install of the extension? I did not need to uninstall chrome.

YES, uninstall first, reboot pc, then install, still not work.

**Comment by Ryan2128** [comment]
1. setting
2. Security & Privacy
3. Reveal Seed Phrase

**Comment by skevmn** [comment]
> > 如何安装v9.4.0？我找不到
> 
> [关联](https://github.com/MetaMask/metamask-extension/releases/tag/v9.4.0)

Thanks I'll try again

**Comment by skevmn** [comment]
> ![image](https://user-images.githubusercontent.com/33176053/117771546-ce27f480-b268-11eb-8ff8-3e396c42c753.png)
> 
> Download the file of you exploerer, and install it. You can search how to install local package.

Thank you very much, it works!

**Comment by jcoinas** [comment]
Facing same issue but different locale

Translator - Unable to find value of key "errorPagePopupMessage" for locale "pt_PT"

**Comment by mathps16** [comment]
First I changed my language settings and it worked. I used my seed phrase to recover my account, but it's empty. I have tried to uninstall, reboot my computer, install the version 9.4.0 and still the same. like a new wallet. Don't know what to do.

**Comment by jcoinas** [comment]
For when a new release?
