### ISSUE TITLE
Connecting Trezor T I get: "Popup error: Unable to establish connection with iframe"

### ISSUE THREAD

**Issue by francesco-cadei** [MetaMask/metamask-extension#11042]
![image](https://user-images.githubusercontent.com/25520099/117799743-b8a7d000-b252-11eb-937f-08baa9947d68.png)

 - OS: Debian 10
 - Hardware Wallet: Trezor T (Firmware 2.3.6)
 - Browser: Firefox (78.10.0esr 64-bit)
 - MetaMask Version: 9.4.0

I can connect to other wallets (like Daedalus) without problems.

**Comment by francesco-cadei** [comment]
I have this problem only with metamask, trezor bridge is 2.0.27 linux-64bit (deb).

**Comment by mgillman** [comment]
I can reproduce. Having the same issue. Works fine on Chrome, but fails on FIrefox.

MacOS 12.0.1
Firefox 94
Trezor Bridge 2.0.27
