### ISSUE TITLE
personal_sign should show plain text even when length is 32 characters

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#11050]
[Reported by Austin Griffith on Twitter](https://twitter.com/austingriffith/status/1392176606974595073)

Currently if `personal_sign` is invoked with a message that is exactly 32 characters in length, the challenge is presented as hex to the user.

I don't remember the historical reason for this behavior, but it seems nonsensical from a consumer perspective.

We should:
- Verify there's no good reason for this
- Assuming there isn't, remove the special behavior.

**Comment by vandan** [comment]
relates to #10297 and #3931

**Comment by vandan** [comment]
Appears to be resolved. Unable to reproduce with the latest version of the Extension.
