### ISSUE TITLE
error load metamask (Incorrect locale...)

### ISSUE THREAD

**Issue by gonzaluz** [MetaMask/metamask-extension#11059]
Hello 
i have a problem with metamask 

![error](https://user-images.githubusercontent.com/58921497/117917888-04409500-b2b8-11eb-9235-a51ba261ae8c.JPG)

Alguien conoce el error?
alguna ayuda?

**Comment by tmashuang** [comment]
Duplicate of #11047, #11045, #11038, #11033, and #11055

Fixed by #11036

**Comment by tigerShrimp21** [comment]
@tmashuang I still have this issue on 0.9.5. Restarted the browser and same issue. What is the updated version number?

**Comment by jcoinas** [comment]
@tigerShrimp21  9.5.1 it is already available

@tmashuang  when will version 9.5.1 added to chrome store? Or only 9.6 will?

**Comment by rtmazd** [comment]
same
