### ISSUE TITLE
Error while sending FTM on FTM network 

### ISSUE THREAD

**Issue by pienrojpp** [MetaMask/metamask-extension#11057]
Hi, 

I got an error in FTM network when trying to send my FTM to my saving wallet. 
The error is shown as in the images below

Message: This method only supports 0x-prefixed hex strings but input was: FTM

On the other network is fine tho. 

Thank you very much.

![photo_2021-05-12_09-12-17](https://user-images.githubusercontent.com/48373850/117908795-47742580-b303-11eb-9d79-f2b6f84a44ad.jpg)

**Comment by tmashuang** [comment]
Fixed by #11048

**Comment by pienrojpp** [comment]
I still got the error when transferring

**Comment by pienrojpp** [comment]
> Fixed by #11048

Thx. But I still got the error when transferring
