### ISSUE TITLE
**Message: This method only supports 0x-prefixed hex strings but input was: [chain Currency Symbol]**

### ISSUE THREAD

**Issue by Luigy-Lemon** [MetaMask/metamask-extension#11067]
**Describe the bug**
When you are on a custom chain (aka every single sidechains) and you input an address in the send input box... it is throwing an error
**Message: This method only supports 0x-prefixed hex strings but input was: xDAI**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Custom Network
2. Click on Send
3. Paste Ethereum Address

**Expected behavior**
It should just work like it used to before this update

**Screenshots**
![image](https://user-images.githubusercontent.com/35468346/118045039-51cc0900-b36f-11eb-80bb-cb663e5acff4.png)

**Browser details (please complete the following information):**
 - OS: Any
 - Browser: Brave
 - MetaMask Version: 9.5.1
**Additional context (Error Messages, etc.)**

**Comment by blackboxtrading** [comment]
When can we fix this? It is really serious...

**Comment by blackboxtrading** [comment]
Is it fixed? I am still having the same problem. Do I need to upgrade or
anything?

**Comment by brandoncurtis** [comment]
@blackboxtrading a fix has been merged: https://github.com/MetaMask/metamask-extension/pull/11071

but this issue won't be fixed for users until a new release containing this fix is tagged and pushed to the extension store, and you upgrade to it :heavy_check_mark:

**Comment by blackboxtrading** [comment]
when can you push the fix to the store? The bug came at such a bad time...

**Comment by Luigy-Lemon** [comment]
It would be nice if we could opt-out of upgrading to "beta" versions. I don't like to be pushed an update without warning... specially one that isn't a stable and tested version.

**Comment by tmashuang** [comment]
> It would be nice if we could opt-out of upgrading to "beta" versions. I don't like to be pushed an update without warning... specially one that isn't a stable and tested version.

In Firefox, you can turn automatic updates off. Chrome doesn't seem to have this feature. 
![image](https://user-images.githubusercontent.com/13376180/118063313-b2e2e500-b34d-11eb-9c25-2e59b9840d8a.png)

**Comment by brandoncurtis** [comment]
@Luigy-Lemon @tmashuang here you go: https://stackoverflow.com/questions/27657617/how-to-disable-google-chrome-extension-autoupdate

always good to have a browser profile where auto-updating of key stuff is disabled so you don't get screwed by broken updates

**Comment by brandoncurtis** [comment]
@blackboxtrading this was tagged an hour ago: https://github.com/MetaMask/metamask-extension/releases/tag/v9.5.2

 so whenever v9.5.2 shows up in the app store (currently v9.5.1) you should be good.  not sure what the delay will be.
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

**Comment by blackboxtrading** [comment]
I see, so we are just waiting for chrome webstore to pick up the latest
build?

**Comment by a0903l22** [comment]
workaround
go to setting > network> hecochain (ht-mainet)
set networkname as 0xnet
set Currency Symbol as 0x
the name does not matter, feel safe to change it
this is how i test transfer between my accounts:
https://hecoinfo.com/tx/0xacdc015b6fd7bc6a430c2434592453b9723edbb20800f796bc94f57afa30c548

**Comment by blackboxtrading** [comment]
Very interesting! Thanks! I hope the update is picked up soon!

**Comment by blackboxtrading** [comment]
Update still not picked up by Web store.  I tried to load unpacked, but
after installing the extension, I did not get a metamask icon on my chrome
address bar, how to fix that?

Thanks

**Comment by brandoncurtis** [comment]
I'd recommend using the current app version and @a0903l22's workaround.  important part is changing the affected network's currency symbol to `0x`.  tried it and it worked for me :tada:

**Comment by blackboxtrading** [comment]
Yes, that is a very smart work around!

**Comment by Gondee** [comment]
> **workaround**
> go to setting > network> hecochain (ht-mainet)
> set networkname as 0xnet
> set Currency Symbol as 0x
> the name does not matter, feel safe to change it
> this is how i test transfer between my accounts:
> https://hecoinfo.com/tx/0xacdc015b6fd7bc6a430c2434592453b9723edbb20800f796bc94f57afa30c548

Changing symbol to 0x was all that was needed to work around this on MATIC. Thanks!
