### ISSUE TITLE
Login Button Color Change From Orange to Blue

### ISSUE THREAD

**Issue by orthogitable** [MetaMask/metamask-extension#11070]
Users of the Chrome extension are reporting a change to the color of the login button from the familiar orange to blue as of version 9.5.0. 

This unannounced and undocumented change to the UI is raising community concern of a potential malware infestation and is in need of official confirmation by MetaMask. 

Changes such as this need to be announced by MetaMask and included in ChangeLogs.

Or, if this is not an official change, a security alert should be issued immediately. 

-------------------

Chromium Version 90.0.4430.93 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)  
MetaMask Extension Versions 9.5.0 & 9.5.1

**Comment by ChristBKK** [comment]
yes I have that too including an error afterwards.
MetaMask encountered an error

**Comment by Skyge** [comment]
I had the same problem.

**Comment by Wetitpig** [comment]
> Users of the Chrome extension are reporting a change to the color of the login button from the familiar orange to blue as of version 9.5.0.
> 
> This unannounced and undocumented change to the UI is raising community concern of a potential malware infestation and is in need of official confirmation by MetaMask.
> 
> Changes such as this need to be announced by MetaMask and included in ChangeLogs.
> 
> Or, if this is not an official change, a security alert should be issued immediately.
> 
> Chromium Version 90.0.4430.93 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
> MetaMask Extension Versions 9.5.0 & 9.5.1

Apparently the colour of the button was [changed](https://github.com/MetaMask/metamask-extension/blob/333206ccb14eff9e23e15f9d470b174ee46c126e/ui/app/pages/unlock-page/index.scss) in commit `333206c`.

Nevertheless I do agree on the need to make this colour change clear. The comments of the commit was really long and could not feature this change which could seem suspicious.

**Comment by geometry-slash** [comment]
Also strongly agree this auto-update was confusing. In fact, I was browsing and connected to many sites with metamask on FF, when I visited a new site the new look Login box popped up asking me to login (the auto-update apparently logs you out .. )

I actually called over my friend to my screen to point out what I thought was a phishing pop-up from a malicious site! Until I realized it was actually the real Metamask. 

Auto-update behaviour which logs you out and then changes the UI drastically and asks to re-login while you are using it!, is definitely not something I would expect here.

**Comment by PatrickAlphaC** [comment]
Here to also voice my discontent with this change. 

In an industry where security is so essential, if you hand out your password or private key, you hand out your funds. I freaked out seeing a different color and thought perhaps someone broke into my house and installed some weird metamask like with https://cryptobriefing.com/easyfi-hacked-over-80-million-metamask-attack/

Which... the hacker would be pretty dumb to swap the color of the button.

**Comment by brad-decker** [comment]
Hey everyone. We hear you. Thank you for raising your concerns. For what it's worth hackers who attempt to use our brand to steal funds go to great lengths to match our styles so as to more easily convince users to enter valuable secrets. In addition, the change that was made now puts the color of the button in line with every other button in the UI. The orange button color is long-standing design debt that was recently paid off.

This was an intentional change, but as always be vigilant.

**Comment by rekmarks** [comment]
Regarding the suddenness of the update, we unfortunately have no control over how the browser applies updates after we publish them. However, we hear your feedback on this, and will take steps to ensure that changes like this are verifiable on e.g. https://metamask.io in the future.

**Comment by bohica89** [comment]
YES! PLEASE SEND THE JUICY UPDATE OUR WAY NOM NOM NOM UPDATES!

**Comment by orthogitable** [comment]
Thank you for the clarification.

**Comment by orthogitable** [comment]
OK, it's been a week and there have been no new comments so I guess it's time to close this issue.
