### ISSUE TITLE
Chrome Page Zoom affects 'swapping on mobile is here' popup - thus removing access to the home page in extension

### ISSUE THREAD

**Issue by DannnyJH** [MetaMask/metamask-extension#11098]
**Describe the bug**
I have Chrome 'Page zoom' set to 125%, which made me unable to close the pop-up in the Chrome extension:
![1](https://user-images.githubusercontent.com/44665221/118241169-209d2700-b49c-11eb-8051-4ef109b28602.png)

As a user, before I found out that is was page-zoom affecting this visual bug, I could access the MetaMask extension by clicking the 'add coin' button at the bottom of the pop-up:
![2](https://user-images.githubusercontent.com/44665221/118241307-49252100-b49c-11eb-99b1-34d80033de65.png)

However, the home page was locked to the pop-up-box (as at 125% page zoom you're unable to close it), so when clicking the MetaMask homepage button, the pop-up would reappear.

Generally:
Chrome Page Zoom enlargens the content in the Chrome MetaMask extension, which makes the new pop-up so large, that the x for closing the popup is not shown. This makes it impossible to close the popup, without changing the CSS top margin of the pop-up.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to 'Chrome'
2. Go to 'Chrome settings'
3. Change 'Page zoom' to 125 % under Appearance
4. Open MetaMask extension and login to see the pop-up as shown in the first image.

**Browser details (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Version 90.0.4430.212 (Official Build) (64-bit)]
 - MetaMask Version: [9.5.2]

**Comment by BboyAkers** [comment]
I can dig into this!
