### ISSUE TITLE
required package not in whitelist: package "@gulp-sourcemaps\map-sources

### ISSUE THREAD

**Issue by 18673227300** [MetaMask/metamask-extension#11095]
![image](https://user-images.githubusercontent.com/31278398/118218399-e5a1f000-b4a9-11eb-8e6b-c4fb69bf5655.png)

**Comment by darkwing** [comment]
Do you still have this issue after running `yarn setup`?

**Comment by Jiaming-Liu** [comment]
same here. yes. trying to compile 9.8.4

**Comment by Gudahtt** [comment]
Thanks for the report! This is a duplcate if #10748. Please follow that issue for updates.
