### ISSUE TITLE
Error: "new BigNumber() not a base 16 number: undefined"

### ISSUE THREAD

**Issue by miguelmota** [MetaMask/metamask-extension#11096]
**Describe the bug**

```
    Message: new BigNumber() not a base 16 number: undefined
    Code: BigNumber Error
```

**Steps to reproduce (REQUIRED)**

1. Try to make transaction using xDai network

**Expected behavior**
No error

**Screenshots**

![Screenshot from 2021-05-13 21-14-29](https://user-images.githubusercontent.com/168240/118220727-26a9ee00-b431-11eb-8c3c-606d7a3fe1f5.png)

**Browser details (please complete the following information):**
 - OS: Arch linux 64-bit
 - Browser: Firefox 88
 - MetaMask Version: 9.5.2

Let me know if you need more details. Thanks

**Comment by danjm** [comment]
@miguelmota Is this still an issue?

**Comment by miguelmota** [comment]
@danjm I haven't encountered this error anymore
