### ISSUE TITLE
ETH Transfer Funds (from exchange to metamask

### ISSUE THREAD

**Issue by sralchemy** [MetaMask/metamask-extension#11113]
Just wanna ask if whats wrong with metamask account because I transferred .020 ETH from an exchange to metamask but only displaying .001ETH refer to pic 1 

![metamask_report_01](https://user-images.githubusercontent.com/72777129/118490678-ca0c4300-b750-11eb-88ba-f70743a4a235.PNG)

and then when I click the amount below refer to pic 2 

![metamask_report_02](https://user-images.githubusercontent.com/72777129/118490747-d85a5f00-b750-11eb-8276-1c7b571a0390.PNG)

then you can see the received amount of ETH which is .020ETH

Hope someone can give me an answer. Thank you

**Comment by bhumit070** [comment]
the ammount is 0.02 and you are saying 0.2 I am confused 😅

**Comment by sralchemy** [comment]
> the ammount is 0.02 and you are saying 0.2 I am confused 😅 ,
> can you confirm your transaction on etherscan

the amount is .020
and yes the transaction on etherscan is saying completed
but reflecting on my account is only .001ETH as you can see on picture #2

**Comment by darkwing** [comment]
Hello @sralchemy.  Please contact our support team to resolve your specific issue.  Thank you!  https://support.metamask.io
