### ISSUE TITLE
"Replacement transaction underpriced"

### ISSUE THREAD

**Issue by uberubert** [MetaMask/metamask-extension#11128]
**Describe the bug**
Starting a transaction results in the error "Replacement transaction underpriced". This happens both when trying to approve a token from pancakeswap and when trying to send tokens from the wallet to another account

**Steps to reproduce (REQUIRED)**
1. Open my wallet
2. Click a token and "send"
3. Fill a valid recipient address and press confirm (leaving gas price at 5, not touching nonce)
4. The error pops up immediately and no tokens are transferred. No transaction is created

**Expected behavior**
A transaction should be created. This transaction should eventually be resolved.

**Screenshots**
Screenshot 1 - just sending a few bake for the test to another account I just created:
![image](https://user-images.githubusercontent.com/2908847/118686483-5461af00-b804-11eb-9d52-f2b7bed78851.png)

Screenshot 2 - The error after pressing "Confirm":
![image](https://user-images.githubusercontent.com/2908847/118686648-79562200-b804-11eb-9e50-8510bdb3b462.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox v88.0.1 and Edge v90.0.818.62  (same behaviour in both)
 - MetaMask Version: v.9.5.2

**Additional context (Error Messages, etc.)**
This started happening a few days ago and I'm unable to initiate any transactions for the time being.
I've tried resetting the account with no change in behaviour. I've tried setting a custom nonce but that only resulted in transactions that don't exist on bscscan. I've tried other browsers, incognito mode, clearing cookies.
I have no idea what I could've done to introduce this problem as I've just been using the wallet and swapping on pancake without doing anything out of the ordinary.

**Comment by Gredys** [comment]
Same happened few times for me on local eth network.
What I have done to reproduce this issue:
 - Sent some ETH from one of nodes account to opened account in chrome (let say this will be named CA1 and for example 10 ETH)
 - Then I sent some ETH to other account of firefox (FA1 and for example 2 ETH)
 - First transaction was fine, all events fired correctly and logs were ok too
 - After repeating process of sending ETH between CA1 and FA1 accounts (from one to each other) I got stuck transaction
 - After trying to cancel or `push` transaction from MM - I got same message on MM UI and in nodes logs
Basicaly nodes were telling that transaction is already known and thus leading to `stuck transaction`.
Canceling transaction or pushing it will lead to `replacement transcation is underpriced` and `already known` errors on nodes logs. And including `replacement transcation is underpriced` in MM as excepcted.

May share more information if needed.
