### ISSUE TITLE
Icon shiba not displayed in extension when i did reset and recovery account

### ISSUE THREAD

**Issue by Baukaalm** [MetaMask/metamask-extension#11129]
<img width="1011" alt="Screen Shot 2021-05-18 at 22 47 10" src="https://user-images.githubusercontent.com/11878817/118691885-555a0700-b82b-11eb-92fd-512d674193c5.png">

fail URL in WalletOverview component
 http://etherscan.io?a=0x278fb04c826269651b5d7781bf07c273c3ec5422/token/images/shibatoken_32.png

**Comment by jacobcantele** [comment]
Hi @Baukaalm , I'm confused by your screenshot, it appears your wallet is showing those tokens. However, it sounds like you need to re-add SHIBA as a custom token. This is not a bug. Our support community at community.metamask.io can help you if you still need help.
