### ISSUE TITLE
Incorrect fee in USD when using wallet_addEthereumChain nativeCurrency as xDai

### ISSUE THREAD

**Issue by miguelmota** [MetaMask/metamask-extension#11138]
**Describe the bug**
Incorrect gas estimation cost is displayed when using XDAI as native currency

**Steps to reproduce (REQUIRED)**

1. 
```js
window.ethereum.request({
  id: 1,
  jsonrpc: '2.0',
  method: 'wallet_addEthereumChain',
  params: [
    {
      chainId: '100',
      chainName: 'xDai',
      rpcUrls: ['https://rpc.xdaichain.com'],
      blockExplorerUrls: [
        'https://blockscout.com/xdai/mainnet'
      ],
      nativeCurrency = {
        name: 'xDAI',
        symbol: 'XDAI',
        decimals: 18
      }
    }
  ]
})
```
2. trigger an approval tx 

**Expected behavior**
Correct gas estimation cost in USD when XDAI is native currency

**Screenshots**
![DeepinScreenshot_select-area_20210519141158](https://user-images.githubusercontent.com/168240/118885122-35b6f300-b8ac-11eb-87ed-601ac85bd840.png)

**Browser details (please complete the following information):**
 - OS: Arch
 - Browser: Firefox
 - MetaMask Version: 9.5.3

**Additional context (Error Messages, etc.)**

**Comment by shanejonas** [comment]
Looks like we refactored this UI and this might not be applicable anymore. Please try again and let use know if its still an issue.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/364566/178853538-c6f5effa-a724-49aa-8960-55f4b0ab9ca4.png">
