### ISSUE TITLE
Mobile wallet browser stuck message makes it unusable

### ISSUE THREAD

**Issue by hdadr** [MetaMask/metamask-extension#11141]
**Describe the bug**
Submitted tx and the shown message stuck on the browser. See attached image. 
![IMG_20210520_121855](https://user-images.githubusercontent.com/22738075/118962703-f220bf80-b965-11eb-9350-da9bdd43eb32.jpg)

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

Don't remember how it happened. I opened metamask after sometime and it is there.

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by diegoxter** [comment]
I'm having the same exact issue, it just started out of nowhere. I'm using Opera Fantom so it's a chain agnostic bug
![Screenshot_2021-05-20-08-37-16-579_io metamask](https://user-images.githubusercontent.com/785242/118972164-a1e63500-b946-11eb-90e9-daa2f9318729.jpg)

**Comment by danjm** [comment]
Hi, can you please submit this issue in our mobile repo? Thank-you

### https://github.com/MetaMask/metamask-mobile

**Comment by danjm** [comment]
Actually, I've copied it over there https://github.com/MetaMask/metamask-mobile/issues/2704
