### ISSUE TITLE
Fix leading zero when clicking value field on Send screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#11146]
When clicking in the value field of the `SEND` screen, there is a leading zero that should go away, and interferes with simply entering correct values. Would be better to just have more-normal input behavior, as this zero can make it harder to read the number that is input, and looks weird.

**Comment by kdm5126** [comment]
https://user-images.githubusercontent.com/27504011/119708818-87222d80-be2a-11eb-8fab-c44c5f323a35.mov

Thanks for posting the issue. This occurs from the advanced settings screen after deleting the gas estimation.

**Comment by kdm5126** [comment]
https://user-images.githubusercontent.com/27504011/119710074-efbdda00-be2b-11eb-87a3-6cd678f8e187.mov

This happens in advanced settings as well !

Thanks for posting the issue!
