### ISSUE TITLE
Onboarding redesign

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#11143]
This is a ticket to cover the work in this figma: https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=73%3A2

We are going to do this work in at least 5 stages:

- [x] 1. Redesign of existing functionality to storybook (in progress)
- [ ] 2. Redesigns of existing functionality merged and shipped
- [ ] 3. Add Import from mobile feature
- [x] 4. Add privacy control feature
- [ ] 5. Add hardware wallet onboard feature

cc @ryanml

**Comment by danjm** [comment]
The latest designs are here: https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=1525%3A14906

**Comment by danjm** [comment]
Before continuing work on this, a dev should:

- document current state of all work related to this ticket
- organize this work into pieces that can be completed and merged in isolation
- create github tickets for each of those pieces and reference them here

**Comment by danjm** [comment]
Further details are here https://www.notion.so/New-Extension-onboarding-v2-9e017a2c83e24cc3a2ecf2c561b1868a

**Comment by adonesky1** [comment]
Step 2 currently represented by https://github.com/MetaMask/metamask-extension/issues/12183

**Comment by PeterYinusa** [comment]
Created a ticket for the Backup Secret Recovery Phrase notice #12625

**Comment by kevinghim** [comment]
All old onboarding flow needs to be removed
