### ISSUE TITLE
Ugly font in MetaMask extension for Firefox

### ISSUE THREAD

**Issue by hardcore-sushi** [MetaMask/metamask-extension#11154]
**Describe the bug**
Font is ugly in MetaMask extension for Firefox on Linux, both in the pop-up and in the full screen pages.

**Steps to reproduce**
1. Install Debian testing.
2. Install Firefox-ESR.
3. Install MetaMask from the official Mozilla add-ons page: https://addons.mozilla.org/en-US/firefox/addon/ether-metamask

**Expected behavior**
The font should not be that ugly.

**Screenshots**
![Popup of MetaMask with ugly font](https://matrix.underworld.fr/_matrix/media/r0/download/matrix.underworld.fr/DpDNOtgoANwMrrIkDwMMnADv)

**Browser details:**
 - OS: Debian testing 5.10.28-1 (2021-04-09) x86_64 GNU/Linux, Kernel 5.10.0-6-amd64
 - Browser: Firefox 78.10.0esr
 - MetaMask Version: 9.5.3

**Additional context**
When I remove the "Euclid" font from the "font-family" property in the Firefox style editor, the font looks good.

**Comment by darkwing** [comment]
Looks like Euclid was implemented in 8.1.0.  Thank you for letting us know, @hardcore-sushi !
