### ISSUE TITLE
Indicate Infura in Network Menu

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1115]
Maybe with a cool logo.  Because Infura Pride.

**Comment by Zanibas** [comment]
Could we get a clarification on the specific specs for this?

**Comment by flyswatter** [comment]
This isn't fully thought out yet, needs design.

The thought is that some of our menu items actually refer to connecting to Infura, so maybe we want to indicate the Infura brand there?  Maybe as the network indicator?

I'm not sure I agree with this, I like simplicity here a lot.  Maybe the Infura name could be in the network menu.  This issue for now is for that consideration.

**Comment by Zanibas** [comment]
Related to #1072

**Comment by chafey** [comment]
related to this - the RPC URL in settings should be populated with the infura URL so it is more obvious that metamask is using it
