### ISSUE TITLE
Crypto Lost kid

### ISSUE THREAD

**Issue by atsc89** [MetaMask/metamask-extension#11155]
I transferred out my eth from binance but picked the wrong network, it went into BeP20. It was supposed to be going to ERC20. How should I retrieve the ETh? Contacted the receiving party but they just said I sent to wrong network

**Comment by brad-decker** [comment]
@atsc89 sorry to hear about this, our support team is the best place to get help with this kind of issue. Please open a ticket via https://metamask.zendesk.com/hc/en-us
