### ISSUE TITLE
Cannot clear the "MetaMask encountered an error" view

### ISSUE THREAD

**Issue by MitchellCash** [MetaMask/metamask-extension#11168]
**Describe the bug**

When MetaMask encounters an error it shows a big warning view with the error text. This is super helpful and assisted solving the error for me, however, as far as I can tell there is no way that I can clear the error message and my MetaMask browser extension is just stuck showing me that I previously had an error.

There should be a way to clear this error because it seems I can't use MetaMask anymore without removing the extension and re-adding it to hopefully clear the error.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Create a transaction via the web3 API that is malformed
2. MetaMask displays the error message inside the extension view
3. There is no way to clear the error message from view and it continue to persist indefinitely

**Expected behavior**
I can clear the error message from view when I am done with it.

**Screenshots**

_Just so it's clear this bug report is not to do with the error being shown, I solved that error, it is to do with not being able to clear the error message from view_

![image](https://user-images.githubusercontent.com/8009243/119368140-967a6d00-bcaa-11eb-8a13-c0e8c7907660.png)

**Browser details (please complete the following information):**
 - OS: macOS
 - Hardware Wallet: N/A
 - Browser: Firefox Browser 88.0.1 (64-bit)
 - MetaMask Version: 9.5.4

**Comment by danjm** [comment]
As a first improvement, we could add a button to download state logs here.

**Comment by bdm123** [comment]
I'm running into this issue now where I only see the error screen and can no longer use my metamask on firefox. I've had MM installed on this browser for over a year now and haven't kept track of version updates, but it appears there was a version update (10.6.2) applied just today. Restarting the browser and disabling/re-enabling the extension does not clear the error view. 

@MitchellCash @danjm - Is there a manual/technical workaround to workaround/fix this? I don't want to reinstall MM and risk losing access to my wallets. Any alternative suggestions? 

Version
10.6.2
Last Updated
November 23, 2021

Thank you.

**Comment by MitchellCash** [comment]
@bdm123 unfortunately I had to uninstall and reinstall the browser extension entirely. Not the answer you're hoping for, I know. Like you said though, **do not do this** if you don't have secure backups of your accounts inside MetaMask. Not a great outcome. Hopefully we can get this looked into as while errors might be rare, it makes the extension entirely unusable and have to be uninstalled.
