### ISSUE TITLE
Use BTCRelay to accept bitcoin deposits to fund accounts

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1116]
We should work with Joseph Chow to make this happen.  Currently we lose a ton of commission fees to third parties like Shapeshift and Coinbase (we get a sliver of their cuts).

**Comment by flyswatter** [comment]
What I mean is we could use BTCRelay to detect when someone sent BTC to an account we manage, and we could simply fund their ethereum account on our end.

A better version would be to make a smart contract that automatically pays out.
The BTC sent to our account could include metadata for what ether address to fund.
Our smart-contract would need a price feed, which we could keep fudged slightly above market price (for our markup), and it could immediately pay out when BTCRelay detected the transaction.

Curious what the latency on this funding mechanism would be.

**Comment by electrotechno** [comment]
an updates on this?

**Comment by danfinlay** [comment]
No. BTCRelay is not actively maintained, this was an idea, but is not being actively pursued. If there is an update on this, you will see it here.
