### ISSUE TITLE
Request a new feature link on github page doesn't work

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#11177]
https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests

<img width="1167" alt="Screen Shot 2021-05-25 at 1 11 37 PM" src="https://user-images.githubusercontent.com/3885055/119539965-dac54600-bd5a-11eb-8ac8-e4502816116d.png">

<img width="1188" alt="Screen Shot 2021-05-25 at 1 11 43 PM" src="https://user-images.githubusercontent.com/3885055/119539952-d6992880-bd5a-11eb-9500-d0818a23be8b.png">

**Comment by darkwing** [comment]
Thank you for the report @jennypollack !  The correct URL should be https://community.metamask.io/c/feature-requests-ideas/13, we'll get that fixed up.
