### ISSUE TITLE
Sync not matching up across platforms

### ISSUE THREAD

**Issue by Treeto** [MetaMask/metamask-extension#11187]
Individual Metamask wallet on variety of platforms is not syncing.....  
While on exact same wallet address, Metamask will display slightly different currency balances when signed in on different platforms.
Or, another example, after adding a new token to the token list on one platform the token will not show up on another platform.

**Comment by bschorchit** [comment]
We currently don't support syncing between platforms unfortunately. Balances should be accurate and reflect the current state on the blockchain though. Let us know if that is not the case.
