### ISSUE TITLE
Feature Request Link on Github is 404

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#11193]
[404](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests)

**Comment by wjmelements** [comment]
<img width="491" alt="Screen Shot 2021-05-27 at 6 21 07 PM" src="https://user-images.githubusercontent.com/799573/119915896-502a4580-bf18-11eb-9ca2-602756e818c6.png">

**Comment by Gudahtt** [comment]
Thanks for the report! This was fixed in #11217
