### ISSUE TITLE
Seed phrase invalid 

### ISSUE THREAD

**Issue by mathew17771** [MetaMask/metamask-extension#11204]
Hey, 
I got logged out of my metamask today and it said my password was incorrect and that I had to login with seed phrase, when I entered my seed phrase it said that it was wrong. But I am 100% sure it’s right and have multiple backups aswell. Moreover I’ve tried the eliminating spaces method aswell please give me a reply as soon as possible

**Comment by yener84** [comment]
to worry about the same problem

**Comment by richardsonn09** [comment]
@mathew17771 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
