### ISSUE TITLE
web3_sha3 RPC method unauthorized, looking for alternatives

### ISSUE THREAD

**Issue by Destrian** [MetaMask/metamask-extension#11228]
Can anyone help me with this?
const hash = await ethereum.request({ method: 'web3_sha3', params: [message] });
i get "Unauthorized method: web3_sha3" in the response
This is on a simple html and js webpage, i can access the other methods like eth_requestAccounts and eth_accounts but not this one

**Comment by darkwing** [comment]
Hello @Destrian !  Please ask your questions on the community forum.  Thank you!

https://community.metamask.io/c/developer-questions/11
