### ISSUE TITLE
A cripto não aparece no metamask 

### ISSUE THREAD

**Issue by Eduardojofre** [MetaMask/metamask-extension#11230]
Eu fiz uma transferência da rede binance smart chain para o metamask e o dinheiro saiu da binance e não entrou no metamask, já estou tentando resolver mas não tem nenhum telefone de contato com a metamask, tenho fotos de que transferiu mesmo mas não aparace meus BNB na metamask, quero meu dinheiro.

**Comment by darkwing** [comment]
Google Translation:

> ## Crypto does not appear in metamask
> I made a transfer from binance smart chain network to metamask and the money left binance and didn't go into metamask, I'm already trying to solve it but I don't have any contact phone with metamask, I have photos of it transferred but my BNB don't show at metamask, I want my money.

**Comment by darkwing** [comment]
Hello @Eduardojofre !  Please contact support with regard to this issue:  http://support.metamask.io/
