### ISSUE TITLE
Ledger doesn't connect

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#11234]
**Describe the bug**
Ledger doesn't connect
**Steps to reproduce (REQUIRED)**

1. Connect Hardware wallet, Select Ledger

**Screenshots**
![image](https://user-images.githubusercontent.com/9360827/120775528-20f77380-c4d8-11eb-8a13-e4c69229f125.png)

**Browser details (please complete the following information):**
 - OS: OSX
 - Hardware Wallet: Ledger Nano S Firmware version 1.6.0
 - Browser: 
 - MetaMask Version: 9.5.9

**Comment by darkwing** [comment]
Thank you for the report, @rstormsf.  What browser and version are you using?  Do you also get this error with Ledger Live turned on (a toggle in Settings > Advanced)?  Do you receive that error in other browsers?  Do you also get the error if you restart the browser?

**Comment by dpazdan** [comment]
Cannot proceed with investigating issue without further information provided.
