### ISSUE TITLE
Cannot cancel a chain change requested by wallet_addEthereumChain

### ISSUE THREAD

**Issue by djtjc** [MetaMask/metamask-extension#11235]
**Describe the bug**
In a multi-chain dApp, when a user clicks 'connect wallet' we first try to change their Metamask network if their wallet is not using the expected chain ID. When the user confirms, everything works. However, the 'cancel' button in the confirmation dialog does not appear to do anything and blocks the extension.

**Steps to reproduce (REQUIRED)**
1. Create a button with a click handler like so:
```
window.ethereum.request({
  method: 'wallet_addEthereumChain',
  params: networkSettings // eg ethereum
})
```
2. Set the Metamask extension to use a different chain ID (eg BSC).
3. Open the page and click the button
4. When the Metamask extension opens the confirmation dialog, click 'cancel' in the dialog.
5. Nothing will happen.

**Expected behavior**
Clicking cancel should close the dialog, cancel the pending transaction and return an error to the calling code.

**Browser details (please complete the following information):**
- macOS 10.14.6
- Firefox 90.0b1 (64-bit)
- MetaMask 9.5.5

**Comment by MalayTripathi** [comment]
Hello @djtjc, Could you send the params you use to switch to Ethereum Network..? I am building a multi-chain dapp which has Ethereum and BSC. When I switch to BSC, it does it perfectly using wallet_addEthereumChain but when I want to switch back to Ethereum, Metamask is not prompting me to switch the network.

**Comment by djtjc** [comment]
@MalayTripathi `wallet_addEthereumChain` does not work for default chains, as described in [the docs](https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods). That is expected behavior.

**Comment by brad-decker** [comment]
@MalayTripathi `wallet_switchEthereumChain` is what you're looking for to switch to one of the default networks like Mainnet.

**Comment by brad-decker** [comment]
Related to #11214 #11383

**Comment by adonesky1** [comment]
Closing this issue because we will use duplicate #11383 for reference
