### ISSUE TITLE
metamask app webview: ethereum is not defined when access auth()->user property in laravel

### ISSUE THREAD

**Issue by keanwalker** [MetaMask/metamask-extension#11243]
Hi, i have developed a web application with laravel. it is working 100% fine in desktop browser with metamask extension. however when i open the web in metamask mobile app webview, ethereum extension will not be injected into my web whenever i access property of auth()->user, such as user name. without accessing it, on JS level ethereum is found. 

I tried few days to find out the reason, but can't find a solution. it is a bug of metamask webview?

**Comment by loida24** [comment]
Same to me

**Comment by darkwing** [comment]
This is a mobile issue; I've moved this issue to the MetaMask Mobile repository.

**Comment by jimrubenstein** [comment]
A link, for anyone who wants to follow this issue:

https://github.com/MetaMask/metamask-mobile/issues/2802
