### ISSUE TITLE
sass.bridgeJson is not a function

### ISSUE THREAD

**Issue by zhanghaiduo** [MetaMask/metamask-extension#11256]
**Describe the bug**
Development
1. yarn
2. yarn start 

sass.render(sass.bridgeJson(opts), sass.bridgeFn(callback));
TypeError: sass.bridgeJson is not a function

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. yarn
2. yarn start 
3. See error

**Expected behavior**
Error during development and runtime

**Browser details (please complete the following information):**
 - OS: [OS X]

**Comment by danfinlay** [comment]
I also just hit this, on a branch that hadn't had this problem for several builds, and it just started after I made a new component with a storybook. That's the biggest thing I changed since the last successful build.

**Comment by danfinlay** [comment]
This function is shimmed by a patch-package script we have in `patches/sass+1.32.4.patch`. It's used in `development/build/sass-compiler.js`.

**Comment by danfinlay** [comment]
Need to run `yarn setup` to fix this, that applies the patches.

**Comment by zhanghaiduo** [comment]
thank!
