### ISSUE TITLE
When Metamask is installed, it's automatically closing browser window popup

### ISSUE THREAD

**Issue by jejopl** [MetaMask/metamask-extension#11261]
**Describe the bug**
I'm having issue while I'm trying to login on engine.presearch.org. Normally, when I click on "register or login" on top right corner, it opens a popup window and ask me for my username and password. When Metamask extension is installed, Firefox is automatically closing the popup window after a second and I can't login to my account.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to [engine.presearch.org](https://engine.presearch.org)
2. Click on register or login
3. See error

**Expected behavior**
The popup window should not be closed automatically. When it's happening it's not allowing me to login.

It works fine when you disable metamask.
Also, I have this issue only in Firefox. It works fine on Brave

**Screenshots**
![image](https://user-images.githubusercontent.com/32012330/121371326-c2018680-c93d-11eb-993b-c970ef20dc40.png)
![image](https://user-images.githubusercontent.com/32012330/121371395-ce85df00-c93d-11eb-9131-98c95949c009.png)

**Browser details (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Firefox Browser 89.0 (64-bit)
 - MetaMask Version: 9.5.9

**Comment by darkwing** [comment]
Odd, I'm also seeing this in Brave, so it's not specific to Firefox.

**Comment by jejopl** [comment]
@darkwing hmm, I thought that it was working, but I've checked again and you're right. Not working on brave now as well
