### ISSUE TITLE
Unable to Send Tokens on Polygon Network

### ISSUE THREAD

**Issue by faxotherapy** [MetaMask/metamask-extension#11277]
**Describe the bug**
I'm unable to send tokens (my case: DAI) from address controlled by Trezor to another address controlled by MM. On Polygon. The issue also appears even though we don't use Trezor.

Also, MM on Polygon appears:
- To be out of sync (show zero balance while it's not).
- It's also a nightmare to add a token to MM, because after adding the token address, the other fields do not automatically fill in.
- It takes ages to load my tokens (e.g. : DAI, MATIC, etc.)

In fact, **MM is bearly usable with Polygon.**

**Steps to reproduce (REQUIRED)**
Test: on Polygon, send DAI (or any other token) to another MetaMask address on Polygon.

However, restarting the browser temporarily fixes the issue.

**Expected behavior**
I was hoping my DAI would have been sent to the other address.

**Screenshots**

<img width="382" alt="ethjs-query" src="https://user-images.githubusercontent.com/6538008/121689408-79240c00-cabc-11eb-828e-d947ff7a2cfa.png">

**Browser details (please complete the following information):**
 - OS: MacOS Mojave
 - Hardware Wallet: 1.9.4
 - Browser: Firefox 89
 - MetaMask Version: 9.5.9

**Comment by darkwing** [comment]
@faxotherapy Has this been an intermittent error or do you continually experience this issue hour-to-hour, day-to-day?  Have you even been able to send on Polygon?

**Comment by faxotherapy** [comment]
Thanks for your reply, it happens every day. After discussing this issue on other communities, it seems that Polygon nodes are regularly flooded with new users. In order to solve, at least temporarily, this issue I must input another [RPC URL](https://docs.matic.network/docs/develop/network-details/network/).

**Comment by jacobcantele** [comment]
Hi @faxotherapy , you are indeed correct. This is an issue with the public Polygon RPC endpoint, and it is beyond the scope of anything we can control from the MetaMask side. Fortunately, I believe these endpoints are improving and we're hearing less of these issues in the last couple of weeks.
