### ISSUE TITLE
Dismissing the "Welcome Back" popup leaves Promise unresolved.

### ISSUE THREAD

**Issue by gxxcastillo** [MetaMask/metamask-extension#11280]
Dismissing the MetaMask "Welcome Back" popup that asks for a password results in the call to `ethereum.request({method: 'eth_requestAccounts'});` never being resolved.

### To reproduce

1. Make sure you have metamask installed and that you have already provided your seed phrase
2. disable then enable the metamask plugin (this forces MetaMask to ask for your password when attempting to re-connect)
3. Call the following function from within your browser console

```
async function connect() {
  console.log('connecting...')

  try {
    window.mmResponse = await ethereum.request({method: 'eth_requestAccounts'});
  } catch (error) {
    console.log('fails: ', error);
  }
  
  console.log('all done: ', window.mmResponse);
}
```

4. Confirm that the the MetaMask "Welcome Back" popup is displayed.
5. Dismiss the popup by clicking the `x` on the popup window
6. Confirm that the request to `ethereum.request()` stays unresolved.  Calling `connect()` again results in a `RPC Error: Request of type 'wallet_requestPermissions' already pending` error.

**Comment by microHoffman** [comment]
Hello, please @gxxcastillo did you find any workaround, how can we handle this case, when user closes the metamask popup during `window.ethereum.request({ method: 'eth_requestAccounts' })`? Because right now, as you pointed out, nothing will happen and promise stays unresolved/unrejected :/.

Also, is there any update on this from metamask team? I saw a lot of the issues pointing to this same problem. Thank you for your information and help.

**Comment by gxxcastillo** [comment]
@microHoffman I actually haven't followed up ever since reporting it and at this point I'm just dealing with it.  It does look like @darkwing triaged it back on June 14th, however, I'm not sure what their backlog is like and if / when they would get to it.

**Comment by taylorjdawson** [comment]
@gxxcastillo 
How are you "just dealing with it"? any workarounds?

**Comment by EHaracic** [comment]
AC:
- On closing the popup (by clicking the X button or outside of the popup) the request should be rejected (Promise resolved)

**Comment by baixiaoyu2997** [comment]
i think maybe have other way, as mentioned in the documentation:
```
Under the hood, it calls wallet_requestPermissions for the eth_accounts permission. Since eth_accounts is currently the only permission, this method is all you need for now.
```
try coding  like this:
```
ethereum.request({
              method: 'wallet_requestPermissions',
              params: [{ eth_accounts: {} }],
            })
```

**Comment by EHaracic** [comment]
Pending Consensys: we need more information how to reproduce and fix the issue.

**Comment by yairans-starkware** [comment]
Hi, any update on this issue?

**Comment by xinnanyemm** [comment]
Please note that `label:team-dapp-api` has been replaced by `label:team-devex` . Thanks.

**Comment by vandan** [comment]
Leaving this closed as we were no longer able to repro the issue in the latest version here: https://docs.metamask.io/wallet/reference/eth_requestaccounts/
