### ISSUE TITLE
Unable to load balance 

### ISSUE THREAD

**Issue by djack99587** [MetaMask/metamask-extension#11287]
Seems like wallet won’t connect properly to polygon network and I am getting unable to load balance message or just showing zero balance for my tokens.

**Comment by darkwing** [comment]
I'm also having issues loading balance; a quick look at the background process shows loads of 429 errors:

<img width="701" alt="429" src="https://user-images.githubusercontent.com/46655/121944054-d49e0600-cd17-11eb-944b-d382cd58300e.png">

**Comment by darkwing** [comment]
Hello @djack99587 , are you still experiencing this issue?  Our testing seemed to find that the issue could be Polygon's servers being under stress.

**Comment by djack99587** [comment]
Yes thank you ! My other problem is that MetaMask will not allow me to import my trust wallet . Any idea why ? When I add my private key it tells me the private key is not valid . I tried importing to other wallets and it worked but for some reason I can’t import to MetaMask . I already have a MetaMask account and I’m trying to also import my trust wallet to MetaMask. Can u please help ?

**Comment by MistrSmith** [comment]
Right Network ? 😆

**Comment by bschorchit** [comment]
> Yes thank you ! My other problem is that MetaMask will not allow me to import my trust wallet . Any idea why ? When I add my private key it tells me the private key is not valid . I tried importing to other wallets and it worked but for some reason I can’t import to MetaMask . I already have a MetaMask account and I’m trying to also import my trust wallet to MetaMask. Can u please help ?
> […](#)
> Sent from my iPhone
> On Jun 17, 2021, at 11:32 AM, David Walsh ***@***.***> wrote: ﻿ Hello @djack99587 , are you still experiencing this issue? Our testing seemed to find that the issue could be Polygon's servers being under stress. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Please use the MetaMask support link within the app for this.
