### ISSUE TITLE
deeplinks (https://metamask.app.link) not opening metamask

### ISSUE THREAD

**Issue by Rotemy** [MetaMask/metamask-extension#11283]
Hello,

I'm using MetaMask Chrome Extension and trying to setup a payment deeplink in a webpage using https://metamask.github.io/metamask-deeplinks/.

On mobile it is working great, but on desktop the chrome extension does not open.

Example of a deeplink that is working on mobile but not on desktop: https://metamask.app.link/send/pay-uspace.eth@1

**Comment by bschorchit** [comment]
This is currently supported on mobile only.
