### ISSUE TITLE
MetaMask wallet was changed between vessions of chrome addon.

### ISSUE THREAD

**Issue by adrian97gl** [MetaMask/metamask-extension#11284]
Hello, after uninstall the Chrome MetaMask and reinstall again. I had an issue with my wallet, this wallet was changed and I lost all my wallet crypto.

OLD WALLET: 0x1eb6c5c9d6ed94863dc261ce4b38cebb5b91757d
NEW WALLET: 0xcD006e2BfE32DDB04D649632B1b1DD68C56488Ae

How can I handle this and to recovery my income ? 

 - OS: OSX
 - Hardware Wallet: 
 - Browser: Chrome Version 91.0.4472.77
 - MetaMask Version: ( From 31 march )

**Comment by darkwing** [comment]
Please reach out to our support team for assistance with your wallet.  You can contact them by submitting a request on support.metamask.io
