### ISSUE TITLE
Breaking `eth_signTypedData` change in `9.6.0`.

### ISSUE THREAD

**Issue by nlordell** [MetaMask/metamask-extension#11308]
**Describe the bug**
9.6.0 introduced a breaking change with https://github.com/MetaMask/metamask-extension/pull/11012 where string `chainId`s are no longer supported (but were supported as prior to this release).

Specifically the issue stems from the fact that:

```
> assert.equal(1, "1")
undefined
> assert.strict.equal(1, "1")
Uncaught AssertionError
```

**Steps to reproduce**
Use `eth_signTypedData` to sign a message where the chain ID is specified as a string instead of a number. The popular Ethers.js does this when generating a payload for `eth_signTypedData`:

- **With Ethers.js**
  ```js
  const { chainId } = await provider.getNetwork();
  const signature = await signer._signTypedData(
    { chainId },
    { Foo: [{ name: "foo", type: "string" }] },
    { foo: "bar" },
  );
  ```
- **With the injected provider directly**
  ```js
  await ethereum.request({
    method: "eth_signTypedData_v4",
    params: [
      accountAddress,
      JSON.stringify({
        types: {
          Foo: [{ name: "foo", type: "string" }],
          EIP712Domain: [{ name: "chainId", type: "uint256" }],
        },
        domain: { chainId: chainId.toString() },
        primaryType: "Foo",
        message: { foo: "bar" },
      }),
    ],
  });
  ```

The above code worked in versions prior to `9.6.0`.

**Expected behavior**

I expect the `chainId` to support values as strings as it did in previous versions. This would be required in order to properly support `uint256` chain IDs which cannot correctly be represented with JavaScript numbers:
```
> JSON.parse('{"chainId":9007199254740993}').chainId
9007199254740992
```

Furthermore, I think there is a larger problem with the EIP itself. Specifically, it doesn’t go into much detail about the JSON representation of the `message` or `domain` object and the supported Solidity primitive values.

Specifically for the `chainId` in the [EIP JSON RPC sample request](https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc) it uses `"chainId": 1` as a number (which is what MetaMask was changed to enforce). However, as previously mentioned, this has issues WRT correctly representing `uint256` chain IDs since JavaScript numbers just can't represent all 256-bit integers.

This also raises the larger question of what values should be accepted for Solidity primitives? For example, what is an acceptable encoding for a `uint32` message field? Are all `100`, `1e2`, `"100"`, `"0x64"` acceptable? Or should they be treated like [`QUANTITIES`](https://eth.wiki/json-rpc/API#hex-value-encoding) so only "0x64" is valid (what I would lean towards for consistency with other JSON RPC methods)? Currently, MetaMask for example, seems to accept both hexadecimal and decimal strings for integers. This also makes it quite weird that message fields accept multiple formats (numbers, decimal and hexidecimal strings) while `chainId` strictly requires a JavaScript number.

**Browser details (please complete the following information):**
 - OS: Fedora 34
 - Browser: Firefox 89
 - MetaMask Version: 9.6.0

**Additional context**

For additional discussion about this issue see comments in the Ledger sign typed data issue #10240:
- https://github.com/MetaMask/metamask-extension/issues/10240#issuecomment-856808423
- https://github.com/MetaMask/metamask-extension/issues/10240#issuecomment-861568240

**Comment by danfinlay** [comment]
Thanks for the detailed report.

I think we can quickly fix the first/smaller regression, and from here we can have the larger conversation about acceptable types for the method.

**Comment by nlordell** [comment]
> we can have the larger conversation about acceptable types for the method.

Sounds good. I also tried to bring this up directly in the [EIP-712 discussion](https://ethereum-magicians.org/t/eip-712-eth-signtypeddata-as-a-standard-for-machine-verifiable-and-human-readable-typed-data-signing/397/27?u=nlordell) without much success.

Personally I think the EIP specification has some abiguity WRT how the JSON for `eth_signTypedData` should look like that should be addressed - loosy-goosy formats tend to be hard to work with, and I would advocate for a more precise specification (like what exists for other Ethereum JSON-RPC methods).

**Comment by alfetopito** [comment]
Quick question guys, how long until this (super fast BTW) hotfix is released?
