### ISSUE TITLE
Connecting to a new network throws "endpoint returned a different chain ID" even when entering the same value

### ISSUE THREAD

**Issue by joshuafernandes** [MetaMask/metamask-extension#11325]
**Describe the bug**
When attempting to connect to an Infura endpoint for a new network, and entering the chainId, metamask throws an error saying the chainId is different even though the value of the chainId entered is the same.

![image](https://user-images.githubusercontent.com/3722503/122238216-4dad8100-cf03-11eb-9b63-b34dc4f0cfeb.png)

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to 'Networks -> New Network'
2. Set the RPC Url to https://palm-mainnet.infura.io/v3/6071ae03c33343bba487b780a9851329
3. Set the chainId to 11297108109
4. Attempt to save the network 
5. Error is thrown 

**Expected behavior**
The chainId entered is the same and should work. The error thrown isn't clear as I'm entering the same value it requires but it says "The endpoint returned a different chain ID"

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [Linux - Ubuntu 20.04]
 - Hardware Wallet: [n/a]
 - Browser: [e.g. Chrome Version Version 90.0.4430.212 (Official Build) (64-bit)]
 - MetaMask Version: [e.g. 9.6.0, 9.6.1]

**Comment by danjm** [comment]
This was fixed by #11325
