### ISSUE TITLE
Metamask extension disappeared from pc while off... 

### ISSUE THREAD

**Issue by XRPLoneRidersCoronel** [MetaMask/metamask-extension#11324]
Hello

I had a problem with MM on pc windows edge.
Went on vacation for 5 days, get back home, turn on pc, MM ext gone from sidebar
Reinstall MM ext, put seed but two eth accounts don show up even when i create new accounts
One of the accounts is backed on mobile phone so im good there
But the other with a lot of NFTs in it is gone and don´t show up... this account is visible on Rarible having the NFTs in it.
How can i solve this issue?
I have the file "nbk bla bla bla" but as a crx extension removed from pc and backed up on pen
Already sent help ticket to MM support but still waiting
I urgently need to solve this because for the time being i heva to import new MM ext to link my FTM Defi account and get busy but worried about never being able to get my hands on the NFTs (107 of them)

Thanks for all the help
Cheers

**Comment by darkwing** [comment]
Hello @XRPLoneRidersCoronel , please contact our support team http://support.metamask.io/ for help with this issue.

**Comment by XRPLoneRidersCoronel** [comment]
Hello DarkWing... i already did but you were faster answering... ive been waiting for like Monday and no answer yet... Thanks anway
