### ISSUE TITLE
Break dist files into smaller chunks

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#11333]
The firefox extension submission has an automated review process that fails if files are >1MB in size.
https://github.com/mozilla/addons/issues/1328

Ideally for at least our Firefox build we would distribute more, smaller files.

**Comment by danfinlay** [comment]
Unfortunately it seems like Firefox is getting less reliable to submit to their store, we may really need to do this sooner. @danjm

**Comment by Gudahtt** [comment]
This was fixed in #11080, which updated our build system to automatically factor out common code between our bundles and split each bundle into chunks based on size.
