### ISSUE TITLE
Improve warning text for eth_sign

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#11337]
I know, some people would have us simply remove support for `eth_sign`. I'll leave that debate out of this issue.

While we support it, we should ensure its warning text is as useful as possible. The current text is correct, but also diluted with multiple messages, making it less impactful than it could be.

![image](https://user-images.githubusercontent.com/542863/122436229-8114fd80-cf4d-11eb-94cc-c9730e6d7337.png)

In [an EIP 3074 environment](https://ethereum-magicians.org/t/a-case-for-a-simpler-alternative-to-eip-3074/6493), a blind signature can sign over total control of an account with even greater certainty.
- We do fortunately already disclaim this signature could hand over control of the account
- If EIP 3074 approaches, we should probably add an additional, even more grave warning, with extra friction, for any signature with an EIP 3074 `0x03` prefix.

Multiple phases we could do here.
- [x] Improve this warning text
- [x] Add some padding to the sides of this text.
- [ ] Move this confirmation to our new more consistent confirmation format.
- [ ] Add more friction to this confirmation ("are you sure? This can give full control of your account to this site.")

This is basically a very advanced method that we should imagine "nobody but expert devs who really know what they're doing" should be using these days. You could consider this a step in the direction of deprection, but rather than breaking dapps that are relying on it, we're just making this antipattern more painfully visible to users.

Proposed copy
> We are unable to estimate the result of this signature. This signature could potentially perform any operation on your account's behalf, including granting complete control of your account and all of its assets to the requesting site. Only sign this message if you know what you're doing or completely trust the requesting site.

**Comment by sambacha** [comment]
Can you at least add it to your documentation that it is still supported? https://metamask.github.io/api-playground/api-documentation/

**Comment by sambacha** [comment]
> I created a design mock up with a new warning message. I think the warning is much clearer to the average user. Let me know what you all think. Thanks!
> 
> 
> 
> ![metamask-signature-warning](https://user-images.githubusercontent.com/975553/188517713-6ff343b2-9076-453a-8848-5636b2969eaf.jpg)

Bro this design is beyond useless its misleading.

**Comment by sambacha** [comment]
> @sambacha
> 
> I disagree, signature requests have been contributing to many recent thefts. The problem is that the current warning is not clear enough that signing a request can lead to a theft of a users assets. As it is designed, it is easy to overlook the warning.
> 
> The current message is:
> 
> > "Signing this message can be dangerous. This signature could potentially perform any operation on your account's behalf, including granting complete control of your account and all of its assets to the requesting site. Only sign this message if you know what you're doing or completely trust the requesting site."
> 
> The message is too long and the way it is written is confusing.
> 
> My version is:
> 
> > "WARNING: Only sign this request if you completely trust the requesting site. Signing this request could potentially allow the requesting site to take complete control of your account and all of its assets."
> 
> I believe my version will help warn users of the risks.

Your solution does not solve existing dapps who rely on the method - without first solving the needed use of that method people will ignore it because people are using it for legit reasons. Ergo, it does not actually solve anything.

**Comment by brad-decker** [comment]
The issue was closed in #12034

**Comment by brad-decker** [comment]
The portion of this that includes updating test copy was done in #12034

**Comment by holantonela** [comment]
I must consider this ticket closed after we introduce https://github.com/MetaMask/metamask-extension/issues/15932.

Also, [we are disabling `eth_sign` by default making it optional](https://github.com/MetaMask/metamask-extension/pull/17308) for users to recieve `eth_sign` messages.

Please, re-open if you consider there is a remaining work on it.
