### ISSUE TITLE
Resolve ENS names sent as recipients our injected provider

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1133]
This is optional, and probably controversial.  This will be a place to discuss the merits and concerns about offering this functionality.

**Comment by whymarrh** [comment]
Can we close this in light of #7163?

**Comment by danfinlay** [comment]
Instead, I will redefine this issue to reflect the ability to send via our provider to ens names. I still think it's a kinda interesting feature. `ethers.js` provides it natively, so maybe it's not needed?

**Comment by whymarrh** [comment]
I think this might be best done at a layer before our provider the way ethers.js does

**Comment by danfinlay** [comment]
Yeah, I agree, ethers.js has kinda proven this can live in user-space... Any other arguments for this living in the provider layer, @arachnid?

**Comment by Gudahtt** [comment]
For now I'll close this as something that is better handled in libraries like `ethers`, rather than in the provider itself.

**Comment by Arachnid** [comment]
Sorry, I somehow missed Dan's update on this way back in 2019.

I would argue that doing this at the provider layer is a superior option to doing it in a library, as that ensures it works across all client libraries. Just as the OS does name resolution for calls to `socket` etc, so should the RPC layer handle name resolution for Ethereum.
