### ISSUE TITLE
error Command failed.  unable to access 'https://github.com/ethereumjs/ethereumjs-abi.git/': Failed to connect to github.com port 443: Operation timed out

### ISSUE THREAD

**Issue by keepresolve** [MetaMask/metamask-extension#11348]
I can download the project separately but can not download with `yarn run setup`
![image](https://user-images.githubusercontent.com/29271171/122589404-cabb3080-d092-11eb-99fd-2a6151a7aa2a.png)
![image](https://user-images.githubusercontent.com/29271171/122589790-46b57880-d093-11eb-8355-74d7e32a6218.png)

**Comment by SpokieKid** [comment]
Hi, did OP solve this issue? Having the same one.

**Comment by xff1024** [comment]
> I can download the project separately but can not download with `yarn run setup` ![image](https://user-images.githubusercontent.com/29271171/122589404-cabb3080-d092-11eb-99fd-2a6151a7aa2a.png) ![image](https://user-images.githubusercontent.com/29271171/122589790-46b57880-d093-11eb-8355-74d7e32a6218.png)

Did you solve this problem?
