### ISSUE TITLE
Ledger + Chrome + OSX broken in 9.6.1

### ISSUE THREAD

**Issue by Kampe** [MetaMask/metamask-extension#11342]
Attempting to use ledger using latest MM 9.6.1 never prompts user for signing.

**Comment by darkwing** [comment]
Are you using the Ledger Live bridge? Which browser and which version?

**Comment by rrecuero** [comment]
Same for me. I cannot get anything to work without Ledger Live. With Ledger Live, signing under the new EIP doesn't work

**Comment by Kampe** [comment]
No, using just raw metamask and chrome + ledger

**Comment by lucasvo** [comment]
I can confirm this

**Comment by darkwing** [comment]
Chrome no longer supports U2F so Ledger Live is the next option.  We'll be release WebHID support for Chrome very shortly.
