### ISSUE TITLE
My token value in metamask was gone

### ISSUE THREAD

**Issue by Dtjandra73** [MetaMask/metamask-extension#11355]
On june 18, i have 34 usdc in my metamask wallet and suddenly on june 19, i saw again , i shocked because my usdc token become 0.69 usdc. And i have checked polygonscan, and i didnt find anything about the suspicious transaction, so i need help from metamask support center for my real problem, please check it.

**Comment by darkwing** [comment]
Hello @Dtjandra73 , please contact our support team at https://support.metamask.io for help.
