### ISSUE TITLE
Pesky MetaMask Window Remains Stuck on Firefox Forever

### ISSUE THREAD

**Issue by faxotherapy** [MetaMask/metamask-extension#11353]
**Describe the bug**
The problem appeared because I wanted to cancel adding a new network while visiting a DeFi site. So, I pressed the Cancel button in MM. Unfortunately, clicking the Cancel button did not work. So, I quitted Firefox and relaunched it. Unfortunately, Firefox now always reopens a second window tied to MM. This second window cannot be closed. So, it seems I'll get this second window forever attached to Firefox. It's impossible to close this second window since there's no frame around it.

This pesky Cancel button never works anyway. Please, refer to a [prevous issue](https://github.com/MetaMask/metamask-extension/issues/11214) that I reported.

**Steps to reproduce**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Visit rampdefi.com
2. When asked to add Binance smart chain, click Cancel in MM
3. Clicking on Cancel button produces nothing
4. Quit Firefox and restard.

**Expected behavior**
The Cancel button should work while there's no second window permanently stuck on Firefox at every Firefox launch.

**Screenshots**
![MM_Window_Stuck](https://user-images.githubusercontent.com/6538008/122658442-408fcc80-d165-11eb-98de-89f375cec07c.gif)

**Browser details (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Firefox 89.0.1
 - MetaMask Version: 9.6.1

**Comment by darkwing** [comment]
I could reproduce and it appears to be the same as https://github.com/MetaMask/metamask-extension/issues/11214 ; closing this as a duplicate.  Thank you for the extra details @faxotherapy !
