### ISSUE TITLE
GasPrice is not safely destructured from txParams in confirm-transaction.js

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#11350]
**Describe the bug**
While working on another issue I found that occasionally in a send token flow I got this error:

<img width="1169" alt="Screen Shot 2021-06-18 at 3 36 06 PM" src="https://user-images.githubusercontent.com/34557516/122613905-38dc0500-d04b-11eb-9a4d-48f7b9bc07a4.png">

upon further digging I found that it was introduced by [a PR](https://github.com/MetaMask/metamask-extension/pull/11239) I merged a few days. Here to clean my mess!

**Steps to reproduce (REQUIRED)**

1. Attempt to send a token with a gas price of 0
2. (sometimes) this error will pop

**Expected behavior**
- This error should not occur

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Chrome 91
 - MetaMask Version: 9.6.1

**Comment by darkwing** [comment]
Marking as high priority as I've also seen this and we should fix it ASAP since it was introduced recently.

**Comment by adonesky1** [comment]
@darkwing agreed. Just added you as a reviewer on the PR to fix: https://github.com/MetaMask/metamask-extension/pull/11351
