### ISSUE TITLE
Add-On Button Not Showing In Firefox

### ISSUE THREAD

**Issue by AdamSHurwitz** [MetaMask/metamask-extension#11365]
### Issue
The MetaMask add-on icon/button is not showing in the Firefox browser UI after installation and configuration, and is unable to be opened via the default extension shortcut "shift + option + M".

The icon/button and shortcut work as expected in an alternate Firefox browser instance launched with a different Firefox profile.

### Steps To Reproduce
1. Download MetaMask add-on and select "Add" when prompted with permissions: [https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/][1]
2. Set up a new wallet: Select "Get Started" > "Create a Wallet" > "I agree" > Enter password > "Next" > Reveal "Secret Backup Phrase" > Confirm "Secret Backup Phrase" > "All Done"
3. The add-on icon/button is not showing in the Firefox menu bar or overflow menu.

https://user-images.githubusercontent.com/3938076/123136670-31d53e00-d421-11eb-8a17-69e51a3dbe54.mp4

### Attempted Solutions
- Allow "Run in Private Windows" and attempt opening in a private window
- Remove add-on, clear all browser cookies and cache, and re-install add-on
- Disable ad blockers, e.g., uBlock and Firefox Enhanced Tracking Protection prior to installation
- Disable all add-ons prior to installation
- Restart Firefox browser
- Restart computer

### Configuration
- OS: macOS Big Sur 11.4
- Firefox version: 89.0.2 (64-bit)
- MetaMask add-on version: 9.6.1

[1]: https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/

**Comment by darkwing** [comment]
I was able to reproduce this.  Oddly enough, when I right click to Customize the toolbar, the addon is certainly there to be added:

<img width="1263" alt="Customize" src="https://user-images.githubusercontent.com/46655/123177939-d8363900-d44b-11eb-8f53-da7675ad7671.png">

I've reached out to the AMO team (https://twitter.com/davidwalshblog/status/1407835034376097793) and will file a bug report if I don't hear from them.

**Comment by AdamSHurwitz** [comment]
Wow, thank you @darkwing!! 🙏🏻 My add-on is back as expected! 

Dave from the support team was also helpful in resolving this via Reddit [here][1]. I don't know if he has escalated the issue to a bug.

[1]:https://www.reddit.com/r/Metamask/comments/o6g0i7/bug_metamask_addon_button_not_showing_in_firefox/h2tmu58?utm_source=share&utm_medium=web2x&context=3
