### ISSUE TITLE
Function wallet_watchAsset not working as expected in Firefox.

### ISSUE THREAD

**Issue by jgarciaIOB** [MetaMask/metamask-extension#11377]
Hi,

**Describe the bug**
With Firefox, when you try to add a token to a network with `wallet_watchAsset`, it does not wait for the promise to be solved. Looks like it is returning if the token already exists in the network or not but without waiting for the promise to be solved by the user ('Cancel' or 'Add Token').
It works fine in Chrome, Brave and Edge.

**Steps to reproduce**
1. Open Firefox
2. Go to a page with ethereum connected
3. Paste this code in the console (https://docs.metamask.io/guide/rpc-api.html#example-5):
```
ethereum.request({
  method: 'wallet_watchAsset',
  params: {
    type: 'ERC20',
    options: {
      address: '0xb60e8dd61c5d32be8058bb8eb970870f07233155',
      symbol: 'FOO',
      decimals: 18,
      image: 'https://foo.io/token-image.svg',
    },
  },
})
  .then((success) => {
    if (success) {
      console.log('FOO successfully added to wallet!')
    } else {
      throw new Error('Something went wrong.')
    }
  })
  .catch(console.error)
```
4. As you can see, it solves the promise before you click on accept or cancel the add token proccess.

**Expected behavior**
It should wait the user interaction to solve the promise (Add the token or cancel the proccess). It works fine in the other browsers.

**Screenshots**
When you try to add the token the first time:
![imagen](https://user-images.githubusercontent.com/85491102/123284007-3296ce80-d50c-11eb-8d83-e17fd5de65b7.png)

When the token is already added:
![imagen](https://user-images.githubusercontent.com/85491102/123284072-3f1b2700-d50c-11eb-8f39-394cd2be3fa9.png)

**Browser details:**
 - OS: Ubuntu 20.04.2 LTS / Ubuntu 18.04.5 LTS
 - Browser: Firefox 89.0.1 64bits
 - MetaMask Version: 9.6.1

**Comment by hbarcelos** [comment]
I'm facing this issue too, but contrary to the author, I'm experiencing the promise being resolved even if the user clicks on "Cancel" in every browser:

- OS: Manjaro Linux (5.11.22-2-MANJARO)
- Firefox: 90.0b4 / MetaMask: 9.7.1
- Chrome: 92.0.4515.80 beta / MetaMask: 9.7.1

**Comment by kevinghim** [comment]
Possibly related to #11383

**Comment by danjm** [comment]
See acceptance criteria here https://github.com/MetaMask/metamask-extension/issues/12416#issuecomment-965096575

**Comment by EHaracic** [comment]
Acceptance criteria:

The method should return a promise that resolves once the user clicks confirm in the popup
If the user clicks cancel, the promise should resolve with a rejection/error

**Comment by VSaric** [comment]
We are waiting for Consensys MetaMask team for further explanation about this issue, as agreed with @danjm.

**Comment by adonesky1** [comment]
@VSaric What is the current state of this issue? Do you know what specific "further explanation" you require?

**Comment by david0xd** [comment]
Hey @adonesky1 we had some debugging sessions with @danjm and our team alone while trying to resolve this problem. But, we didn't manage to chase and catch this bug successfully. So, it was left for @danjm to consult with the main MM team about the issue and provide us more information on the flow and architecture around this feature. That's why this is in status of 'Pending Consensys'.

**Comment by mikezotovdev** [comment]
@david0xd so you can't reproduce the issue or have some other difficulties? Here is a test case for reproducing: https://github.com/MetaMask/metamask-extension/issues/13169

**Comment by mikezotovdev** [comment]
Hey guys, any updates for that bug? Really need that fix! 💯

**Comment by danjm** [comment]
We should have a better understanding of this error by early next week. And maybe a fix merged by the end of next week. So a solution might be in prod in 2.5 weeks.

**Comment by conradocanas** [comment]
Hey folks, any new about this issue? Thank you!

**Comment by jacob-abe** [comment]
Yes please this seems like an obvious disruption to many people's user flow

**Comment by AbdulRaheem-kryptomind** [comment]
Any Update on that bug ?
