### ISSUE TITLE
Keyring problem android 11

### ISSUE THREAD

**Issue by filzek** [MetaMask/metamask-extension#11371]
Erh and bnb problem when using it 
![Screenshot_20210623-234201_MetaMask](https://user-images.githubusercontent.com/29267027/123194789-6f67b480-d47d-11eb-875a-e287c2ba8f56.jpg)

**Comment by jacobcantele** [comment]
Hi friend,

Would you mind re-opening this issue on the MetaMask Mobile repository? This repo is for the MetaMask browser extension.

https://github.com/MetaMask/metamask-mobile/issues
