### ISSUE TITLE
window opened by `wallet_switchEthereumChain` does not respond to input

### ISSUE THREAD

**Issue by JFrankfurt** [MetaMask/metamask-extension#11383]
**Describe the bug**
*Occasionally* when I try to switch networks both action buttons do nothing. 

**Steps to reproduce (REQUIRED)**
Unable to reliably reproduce

**Expected behavior**
Cancel should dismiss the window
Confirm should switch networks

**Screenshots**

https://user-images.githubusercontent.com/5773490/123332510-95896500-d50e-11eb-8490-23c8b88c47da.mov

**Browser details (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Firefox 89.0.1 (64-bit)
 - MetaMask Version: 9.6.1

**Additional context (Error Messages, etc.)**
![image](https://user-images.githubusercontent.com/5773490/123332691-d7b2a680-d50e-11eb-936b-39b6872e3957.png)

**Comment by brad-decker** [comment]
@shanejonas -- Do you think the logs are related to this issue at all? Anyway of knowing. We've had a few (possibly) related issues:

#11344 #11214

**Comment by adonesky1** [comment]
Closed known duplicates, this ticket will serve as the hub for discussing/resolving the issue with `wallet_switchEthereumChain` on Firefox.

**Comment by danfinlay** [comment]
I was able to reproduce locally. I noticed two significant looking errors in the background script before this problem occurs:
> Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). lockdown.js:2105:39

on first load of both `background.js` and `ui.js`, suggesting Mozilla has a CSP incompatability with our lockdown script.

When the addChain confirmation appears, I see a ton of these errors in the background:
> Unchecked lastError value: Error: sender.tab is undefined

And then upon clicking cancel, I get the:
> Error: PortDuplexStream - disconnected

Could a failed lockdown result in us having sender.tab undefined when loading the addEthereumChain request, resulting in an uncaught error and crash upon interacting with that confirmation?

**Comment by danfinlay** [comment]
The `sender.tab` errors were coming from other extensions, and disabling them did not fix the issue.

**Comment by danfinlay** [comment]
Top current theory:
Firefox sends a CORS preflight when requesting chainid.network. This causes a 405 error from that server, which seems to trigger some kind of “database cannot be mutated” error from indexedb, from localforage, from our caching strategy.
Note
getAlert triggers fetchWithCache
We aren’t sure why this failure results in breaking the stream, but uncaught errors can sometimes cause this (ideally they wouldn’t/shouldn’t, but it’s a decen theory)

We should:
Get a cors-friendly endpoint for this data
Be resilient to errors from this endpoint

**Comment by Sigri44** [comment]
Same error with last firefox version and last metamask version.

**Comment by joachimneu** [comment]
Same error with the dialog "Allow this site to add a network?": Cancel button does not work; "Uncaught (in promise) Error: write after end" in lockdown.js:4906:17.

**Comment by astanciu** [comment]
Any updates on this? It's becoming a problem when you have multiple tabs competing to switch to their own network. Currently only way to unblock this is to accept the network switch, but this risks cancelling pending transactions.

> Unable to reliably reproduce

I can reproduce this every time:
1. Switch network to Polygon
2. open yearn.finance

MetaMask pops up to prompt for the switch and cannot be cancelled.

**Comment by daniaoren** [comment]
Is there any work arounds on Firefox?

**Comment by dvdblk** [comment]
Literally happens to me every day for the past 3 months. Any updates?

If I accidentally click 'Cancel' I have to restart Firefox to get Metamask responding again.

**Comment by chironjit** [comment]
Hey all, came here to write about this issue - we've encountered this issue quite a bit and don't have a solution for it. Its especially problematic, and breaks often on sites that track different network and allows users to request to change the network (for example from Ethereum testnet to Ethereum mainnet). 

The only way to get rid of it is to close the dialog box, but then Metamask has the same issue if we try again.

**Comment by josh-davis-vicinft** [comment]
This happens a lot if you have multiple tabs open that want to be connected to different networks.

Only way I know to avoid is: before going to another site that uses MetaMask, close any other tabs that are connected to MetaMask and switch to the account and network that the new site is going to want to use.

If you find yourself in the state where MetaMask stops working, go into your browser plugin settings, disable MetaMask, enable it again, and login again.

**Comment by ape-dev-cs** [comment]
I encounter this almost daily. It'd be great to get an update.

**Comment by klaypigeon** [comment]
This is still an issue on FireFox. I experience it every day.
