### ISSUE TITLE
Unable to send ETH with decimal values of more than 6 places

### ISSUE THREAD

**Issue by chirag64** [MetaMask/metamask-extension#11420]
**Describe the bug**
When sending ETH to an address, Metamask tries to round up values after 6 decimal places.

**Steps to reproduce (REQUIRED)**

1. Go to Metamask dashboard when logged in
2. Click on `Send` for ETH
3. Enter any target address to send ETH to
4. In the `Amount` field, try typing the value `1.2345678`. Notice how the value has removed the `7` and is now `1.234568`.
5. Click on 'Next'. Notice how the value is still `1.234568`.

**Expected behavior**
After typing the value `1.2345678`, we would expect to see the same value in the input field as well as on the Confirmation screen when we click Next

**Screenshots**
![image](https://user-images.githubusercontent.com/591424/123850849-22ca2080-d938-11eb-9fbe-cc6c31353ac1.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome Canary Version 93.0.4558.0 (Official Build) (64-bit)
 - MetaMask Version: Dev build from lavamoat-dev-optional branch

**Comment by EHaracic** [comment]
**@danjm how many decimal places should we use, 8 places or  more?** 
this issue  is related to the issue: #10167

**Comment by bschorchit** [comment]
Closing this as it has been fixed with: https://github.com/MetaMask/metamask-extension/pull/12437
