### ISSUE TITLE
Can't click the setting button when there are 4 accounts on Chrome

### ISSUE THREAD

**Issue by jasonzhouu** [MetaMask/metamask-extension#11456]
**Describe the bug**
The popup is too short to click the setting button.

**Steps to reproduce**

1. create 4 accounts
2. click avatar to find setting button

**Expected behavior**
Click the setting button

**Screenshots**

On Chrome, can't click setting button:

![image](https://user-images.githubusercontent.com/19926174/124393109-7f0fb480-dd2b-11eb-8be2-0b0ff71f348f.png)

But on Firefox, it's totally fine:

![image](https://user-images.githubusercontent.com/19926174/124393339-9b602100-dd2c-11eb-8a95-ec66ed7db288.png)

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Google Chrome 91.0.4472.114
 - MetaMask Version: 9.6.1

Similiar issue: https://github.com/MetaMask/metamask-extension/issues/11440

**Comment by ryanml** [comment]
Hi @jasonzhouu - are you able to check this on the latest version `9.7.1`? I wasn't able to reproduce this, thanks!

**Comment by danjm** [comment]
This could be a screen resolution issue. We might be able to reproduce at different zoom levels within the browser.

**Comment by jasonzhouu** [comment]
@ryanml Hi, after upgraded to `9.7.1`, problem still exist here.

**Comment by jasonzhouu** [comment]
Fixed after setting chrome's page zoom back to 100%.
