### ISSUE TITLE
Submit 9.7.1 to Chrome Webstore

### ISSUE THREAD

**Issue by jhauraw** [MetaMask/metamask-extension#11461]
Has 9.7.1 been submitted to Chrome webstore. Still hasn't shown up and I can't speed up any transactions.

**Comment by Danhkaka** [comment]
.

**Comment by jhauraw** [comment]
Thank you!

**Comment by ryanml** [comment]
Hi @jhauraw - thanks for the submission. Just a bit ago we rolled out `9.7.1` to all Chrome users, updates should be finished catching soon if they aren't already. I will close this issue, feel free to file any related followups 👍
