### ISSUE TITLE
Metamask Extension 

### ISSUE THREAD

**Issue by emilianogr2002** [MetaMask/metamask-extension#11468]
Since installing MetaMask (and TronLink) as a Chrome extension, whenever I conduct a transaction both MetaMask and TronLink will always open in a new window instead of staying on the site. I have looked through the Chrome settings but haven’t been able to figure out how to resolve the issue. Thanks for looking this over. any suggestions are appreciated.

**Comment by emilianogr2002** [comment]
<img width="1440" alt="Captura de Pantalla 2021-07-07 a la(s) 0 49 48" src="https://user-images.githubusercontent.com/87057716/124706677-50c1de80-debd-11eb-8a6d-f99dd4b938d5.png">

**Comment by danjm** [comment]
When conducting a transaction on a site like pancake swap, MetaMask is supposed to open a confirmation in a new window, although it should just be a popup that takes up part of the screen.

Is the problem that it is opening in a full screen window?

**Comment by emilianogr2002** [comment]
Thank you for your reply!
I see videos that MetaMask extension pops up and it doesn’t opens in another window like my case.
This is how it should be
[cid:C26B6DCD-C4A4-4A82-9A48-813F5866F278][cid:E7238EA6-A0B4-4D29-96F6-41FFF1B3019F-L0-001]

There you can see it opens in the same window.
And mine it opens in another one.
[cid:C5991CD6-C3D2-4710-A32E-DEA5D0B303C2-L0-001]

Is there any way to fix this?
Thank you
On 8 Jul 2021, at 5:58, Dan J Miller ***@***.***> wrote:

﻿

When conducting a transaction on a site like pancake swap, MetaMask is supposed to open a confirmation in a new window, although it should just be a popup that takes up part of the screen.

Is the problem that it is opening in a full screen window?
