### ISSUE TITLE
Metamask v9.7.1 display invalid chain info

### ISSUE THREAD

**Issue by suraneti** [MetaMask/metamask-extension#11469]
**Describe the bug**
Display invalid custom network information, coinbase symbol, and logo.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Add some custom networks.
2. Switch from official network to custom network.
3. Metamask will display a coinbase symbol and logo from the previous network.

**Expected behavior**
Display valid info of current network.

**Screenshots**
<img width="359" alt="Screen Shot 2564-07-07 at 15 04 41" src="https://user-images.githubusercontent.com/26770227/124723391-36c3e280-df35-11eb-9498-db25cdd88dda.png">

**Browser details (please complete the following information):**
 - OS: [OS X]
 - Browser: [Brave, Google Chrome]
 - MetaMask Version: [v.9.7.1]

**Additional context (Error Messages, etc.)**
This bug only occurred on v9.7.1, I've tested on v9.6.1 it works correctly.

**Comment by EHaracic** [comment]
@danjm I am not able to reproduce the issue. It seems it has been resolved. Please find below the screenshots:
1. I am on the main network:
![image](https://user-images.githubusercontent.com/49436614/137918893-426481e2-e7de-4bb7-b21e-38f153cb0343.png)

2. I switched to the custom network:
![image](https://user-images.githubusercontent.com/49436614/137919002-55816c35-fb2b-4b98-99a4-e9533ff79483.png)
