### ISSUE TITLE
Reinstalling MM - lost access to wallet 

### ISSUE THREAD

**Issue by CryptoLimbo** [MetaMask/metamask-extension#11478]
- OS: Mac, OS 10.14
- Browser: chrome

I inadvertently removed the MM extension.
I reinstalled it, entered my (correct!) 12 word seed phrase, but I only found a new, empty address. 
Adding accounts didn't help. 

I did a search of my cache, but it only brings up my ledger address that I also used on MM, as well as the newly created address. I can use those with the metamask vault decryptor, generating that seed and a private key, but I haven't found the older wallet in cache: does it disappear along with reinstalling MM?
And if not, in what folder could it be found? 

Sadly I'm faced with a sizeable amount of crypto, currently in limbo. Thank you for your time!

**Comment by Rachelmorgan6** [comment]
Hi, you should try reaching out to the support team via WhatsApp, had the same problems but it’s been fixed by the Metamask support team, you’ll have to text them through their number on WhatsApp +1 562-473-3934, they replied me instantly and fixed all my issues

**Comment by kevinghim** [comment]
MetaMask Support team does not have a WhatApp. If you contact that number,
it'll lead to a phishing attempt. Please do not contact that WhatsApp
number. All MetaMask support queries should be done at MetaMask Support
https://metamask.zendesk.com/hc/en-us.

**Comment by darkwing** [comment]
Hello @CryptoLimbo , please open a support ticket at http://support.metamask.io/ for help with this issue.

**Comment by CryptoLimbo** [comment]
Hi David,

I did try that before ever posting on here. I was hoping those who might
read my message were more knowledgeable than the support desk.

Op do 15 jul. 2021 16:53 schreef David Walsh ***@***.***>:

**Comment by jacobcantele** [comment]
Removed scammer comment.
