### ISSUE TITLE
Issue when sending a transaction to certain contracts on 9.7.1

### ISSUE THREAD

**Issue by Miglekk** [MetaMask/metamask-extension#11471]
Hey. Recently with the 9.7.1 update I noticed that when you try to send a transaction to some contracts, you aren't able to click the "next" button on the extension.
I'm using the chrome extension on Brave.

For example, i'm trying to send a BNB amount to a contract on this screeenshot on Binance Smart Chain, but I can't click on the next button to confirm my transaction. It is greyed out. I downloaded the 9.6.1 update and installed it and it is working as intended. The next screenshots are a comparison of what happens when I try to send a transaction to the same exact address on 9.7.1 and 9.6.1. 
It is in portuguese. "Próximo" means next. 
![image](https://user-images.githubusercontent.com/82135231/124794362-4e936a80-df25-11eb-9ce9-04bf7ee64e6f.png)
![image](https://user-images.githubusercontent.com/82135231/124794428-636ffe00-df25-11eb-9427-ed97c91c7e32.png)

**Comment by danjm** [comment]
Thanks @Miglekk would you be able to share the full contract address you are trying to send to? (Or, if you prefer, you could do so through our private support channel: https://metamask.zendesk.com/hc/en-us/requests/new)

**Comment by danjm** [comment]
Seems to be the same problem as the one reported here: https://www.reddit.com/r/Metamask/comments/ofqlev/cant_send_funds/

**Comment by danjm** [comment]
This is a bug that will be fixed soon. Here is a workaround for this issue:

1. If you don't have any custom tokens on the network that you are trying to send from, add a custom token. This can be any token and you don't need to have any balance in the token.
2. When you go into the send flow you will see the greyed out button. **Before entering anything in the amount field**: use the "Asset" dropdown and select a token other than the primary currency for the network. Now you will notice that the "Next" button is no longer greyed out.
3. Now use the "Asset" dropdown to switch back to the currency you are trying to send.
4. Enter the amount you want to send
5. You should be able to click "Next"

A video of this work around is here:


https://user-images.githubusercontent.com/7499938/124955592-bb743680-dff1-11eb-8865-969ba41ad2cd.mp4

**Comment by IgoresVer** [comment]
Y-I-P-P-E-E-E !!!!!!!!!!

**Comment by FairApe** [comment]
> Thanks @Miglekk would you be able to share the full contract address you are trying to send to? (Or, if you prefer, you could do so through our private support channel: https://metamask.zendesk.com/hc/en-us/requests/new)

hey, don't know if you still need it, but the address is 0xEF2F2EB4d6143B2dCa8ba701f89Fbf45C416BeF0
It is a presale address from dxsale.app, so any other presales address from there should give the same issue

**Comment by danjm** [comment]
This was addressed by v9.8.4

**Comment by isabellewei** [comment]
Encountered the same issue recently using 11.4.1, with the workaround still working as well
