### ISSUE TITLE
Sent Tokens from Binance via Ether Network to Metamask, but Tokens are not showing 

### ISSUE THREAD

**Issue by sebastianhuth** [MetaMask/metamask-extension#11499]
Hi there!

I transferred ERC 20 Tokens from Binance via Ethereum Network to the mobile metamask wallet. Before this transaction I added the new token and the transaction shows as "success" on Etherscan. Unfortunately, the Tokens do not show in my account. I reset the account and still, no tokens are showing. Does anyone know what to do?
Thank you for your help

**Comment by Rachelmorgan6** [comment]
Hi Sebastian
I had the same issue transferring tokens from my wallet but it’s been fixed by the Metamask support team, you’ll need to text them through their number on WhatsApp +1 562-473-3934, they replied me instantly and fixed all my issues

**Comment by sebastianhuth** [comment]
Thank you Rachel!!!!

**Comment by kevinghim** [comment]
MetaMask Support team does not have a WhatApp. If you contact that number,
it'll lead to a phishing attempt. Please do not contact that WhatsApp
number. All MetaMask support queries should be done at MetaMask Support
https://metamask.zendesk.com/hc/en-us.

**Comment by sebastianhuth** [comment]
Thank you Kevin!

**Comment by darkwing** [comment]
Hello @sebastianhuth, please open a support ticket at http://support.metamask.io/ for help with this issue
