### ISSUE TITLE
Transaction showing as confirmed but it actually failed

### ISSUE THREAD

**Issue by MobiusX75** [MetaMask/metamask-extension#11504]
Fail with error 'UniswapV2Router: EXCESSIVE_INPUT_AMOUNT'

Transaction Hash
0x3db0bd3f938e01e134e63386f00cfd7dfd7bf2a306973a88bb01d7ad032cbace

**Comment by darkwing** [comment]
Hello @MobiusX75 , please open a support ticket at http://support.metamask.io/ to help with this issue.
