### ISSUE TITLE
Closing the popup should dismiss the signature

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1152]
This is requested by `@manidos` on slack.

They said:
> rejection of the current transaction when popup is closed works for me. I need this feature, because when I prompt a user to sign something I hide the target button and when popup is closed by the user I have no way to detect it and show the button again. So, yeah, it would be awesome if clicking on close rejected the transaction.

**Comment by flyswatter** [comment]
This should also reject pending transactions.  Requested once in the past, but more recent by Hadrien Charlanes.

**Comment by flyswatter** [comment]
We probably don't want to move too fast on this, since we're currently in a UI design phase, and may be replacing the popup pattern entirely, so factor in the likelihood that we get rid of popups before exerting too much effort on this.

**Comment by whymarrh** [comment]
Closing in favour of #3124
