### ISSUE TITLE
Cancelling the "Allow this site to switch to the network" prompt doesn't do anything.

### ISSUE THREAD

**Issue by chuacw** [MetaMask/metamask-extension#11544]
**Describe the bug**
Cancelling a "Allow this site to switch to the network" doesn't work.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to www.featured.market
2. Click cancel when the Metamask extension comes up, prompting to switch network.
3. The pending request remains.

**Expected behavior**
The request to switch the network is cancelled.

**Screenshots**

![image](https://user-images.githubusercontent.com/1757930/125940413-5710bcb0-1050-4926-8d05-477dca86c56d.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Hardware Wallet: None
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
 - MetaMask Version: 9.8.0

**Additional context (Error Messages, etc.)**
No additional errors or messages.

**Comment by danjm** [comment]
Thanks for the report. This bug is being tracked here: https://github.com/MetaMask/metamask-extension/issues/11544

**Comment by dpazdan** [comment]
Also experiencing this.

**Comment by danjm** [comment]
@chuacw @dpazdan Are you still experiencing this?

**Comment by chuacw** [comment]
@danjm Yes, not fixed.
Clicking cancel or switch network still does nothing. The dialog still remains on screen as well.

**Comment by justBanks** [comment]
Wow. Still nothing. So this means I can't use the extension ever again?

**Comment by glenneroo** [comment]
Also having this issue with https://suigeneris.network/ - closed the tab 20 minutes ago but MetaMask only shows this dialog when opening with no way to close it. I don't want to switch networks because I just transferred some ETH over and waiting for the transaction to finish, but I see this warning "Switching networks will cancel all pending confirmations" so now I don't know what to do.

**Comment by bschorchit** [comment]
> Also having this issue with https://suigeneris.network/ - closed the tab 20 minutes ago but MetaMask only shows this dialog when opening with no way to close it. I don't want to switch networks because I just transferred some ETH over and waiting for the transaction to finish, but I see this warning "Switching networks will cancel all pending confirmations" so now I don't know what to do.

The "pending confirmations" that this warning mentions are any transaction that you might not have yet signed and submitted. It will not affect already submitted transaction or any incoming transaction, @glenneroo . But thank you for bringing this confusion up. We'll look into reviewing this copy.

**Comment by bschorchit** [comment]
Closing as this seems to be fixed on 10.12.3. Let us know if this is not the case.
