### ISSUE TITLE
Can't transfer USDC on xDai

### ISSUE THREAD

**Issue by KimiWu123** [MetaMask/metamask-extension#11558]
**Describe the bug**
can not transfer ERC20 token on xDai

**Steps to reproduce (REQUIRED)**
1. Switch network to xDai
2. click `transfer` and  select USDC (or other non-native tokens) as asset
3. when changed the number of the `Amount`, the `Next` button is disabled

**Expected behavior**
should be able to transfer to another account.

**Screenshots**
![Screen_Shot_2021-07-19_at_11 11 19_AM](https://user-images.githubusercontent.com/19582168/126097620-313c27e6-7a62-454f-86f2-fdd371aceab0.png)

**Browser details (please complete the following information):**
 - OS: Mac OSX
 - Hardware Wallet: na
 - Browser: Chrome 91.0.4472.114
 - MetaMask Version: 9.8.0

**Additional context (Error Messages, etc.)**
none

**Comment by amitOodles** [comment]
Facing a similar issue on my Metamask as well on Firefox, once i have entered the amount the Next button is getting disabled.

**Comment by amitOodles** [comment]
@danjm @darkwing @KimiWu123 
Regarding my issue, i am talking about normal account to account transactions not being sent on custom networks.

**Comment by TtheBC01** [comment]
Also having this problem just trying to transfer between accounts on Hardhat.
![metamask_bug](https://user-images.githubusercontent.com/6946868/126570212-1ae3b97c-b50e-4487-b7a0-3781166ccf69.gif)

OS: Windows 10
Browser: Chrome
Metamask version: 9.8.1
