### ISSUE TITLE
MetaMask Extension Account Recovery

### ISSUE THREAD

**Issue by kingarchilles** [MetaMask/metamask-extension#11557]
Hi admin please someone help me! Its for my brothers hospital bills.

I logged in to MetaMask like a normal day.
Used my password, used my log in 12 words seed phrase.

However when i logged in the wallet address provided me is 0xf9A9d3025ab51C35209E8f848E7178395f1EcD9a(New one).

In which I already deposited ETH there on the wallet 0xfD3a8D90467fb869Ff49DCfD32Df8C1E9774B78a(Old one) because that is my main account.

Until now i can't see my account 0xfD3a8D90467fb869Ff49DCfD32Df8C1E9774B78a(Old one)  under my metamask.
I humbly ask if how can I recover my Old account please? The recovery seed phrase is the same.

I am very new to this forum so I humbly apologize if there's rules here that I missed.

**Comment by danjm** [comment]
Please submit a support request via our form here: https://metamask.zendesk.com/hc/en-us/requests/new

**Comment by kingarchilles** [comment]
Hi I hope you’re safe & sound.



I want to report an unauthorize transaction. Basically I sent ETH to my
Ronin wallet address

*“ **ronin:0788fbfe21bbe3b7d33d1828a0f89773cd774031**”* 4 days ago which is
successful, base on the etherscan transaction. I checked my ronin wallet
under activities to check if my ETH is there it states that it was
successful. However, after an hour my ETH under my Ronin wallet just got
transferred without my permission to an unknown address which is not seen
in the activities under my ronin wallet and view explorer tab.



My Metamask wallet: *0xf9A9d3025ab51C35209E8f848E7178395f1EcD9a*



My Ronin wallet: *ronin:0788fbfe21bbe3b7d33d1828a0f89773cd774031*



Unknown Address*: **0xf30431d4e31e6e54d9338eb8f54da5eceadc4cb4*





On the other hand, here is the official receipt of the metamask EtherScan
that it was successfully transferred to my Ronin wallet address:


[image: image.png]


[image: image.png]







The etherscan states that it was successful.



However, below is the unknown transaction which is not seen under my
activities in my Ronin wallet and view in Explorer tab. Please see
screenshot below:




[image: image.png]



[image: image.png]




Transaction Hash:
0x6a05e85436630bb23548398cbc9a030e82a4bafb2ab21922d91f5dfaf889bf09



The last screenshot states that, from my Ronin Wallet sending to *Unknown
address** (*0xf30431d4e31e6e54d9338eb8f54da5eceadc4cb4
<https://etherscan.io/address/0xf30431d4e31e6e54d9338eb8f54da5eceadc4cb4>)

 which is totally not visible under my activities on my Ronin Wallet
address and view in Explorer tab.


[image: image.png]



[image: image.png]




Please settle this case as soon as possible. Or if it’s okay to talk to you
on phone maybe I can ask for your contact number for this to be clearly
explained.



Please email me right away:



Email: ***@***.***

Phone: 0917-398-1183

**Comment by monikatern** [comment]
@kingarchilles If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
