### ISSUE TITLE
the method wallet_switchEthereumChain can work well in browse,but why it's not work in metamask mobile?

### ISSUE THREAD

**Issue by ibwei** [MetaMask/metamask-extension#11559]
All things goes well in browse
but in metamask mobile,when i click switch network,i got this error,so what's wrong with my code?
![IMG_5587](https://user-images.githubusercontent.com/25237993/126129174-cf0648f3-1548-4c6c-a4ec-43e880aad9a4.jpg)

**Comment by KBKUN024** [comment]
请问你的这个问题解决了吗，我正好也碰到这个问题。就是wallet_switchEthereumChain这个方法在电脑端是可以正常使用的，但是在metamask手机app上，它有一个自带的浏览器，在那个浏览器里就不能使用这个方法，点击按钮啥反应也没有。

**Comment by ibwei** [comment]
> 请问你的这个问题解决了吗，我正好也碰到这个问题。就是wallet_switchEthereumChain这个方法在电脑端是可以正常使用的，但是在metamask手机app上，它有一个自带的浏览器，在那个浏览器里就不能使用这个方法，点击按钮啥反应也没有。

switch 网络在 metamask 移动端不存在，直接用添加那个功能就好了。

**Comment by KBKUN024** [comment]
> > 请问你的这个问题解决了吗，我正好也碰到这个问题。就是wallet_switchEthereumChain这个方法在电脑端是可以正常使用的，但是在metamask手机app上，它有一个自带的浏览器，在那个浏览器里就不能使用这个方法，点击按钮啥反应也没有。
> 
> switch 网络在 metamask 移动端不存在，直接用添加那个功能就好了。

你是指"wallet_addEthereumChain"吗？

**Comment by KBKUN024** [comment]
你说的添加的功能是指：自己手动添加吗？

**Comment by KBKUN024** [comment]
我们可以加个微信或者qq探讨一下吗，我的qq：944412796 微信：KB944412796

**Comment by KBKUN024** [comment]
> > 请问你的这个问题解决了吗，我正好也碰到这个问题。就是wallet_switchEthereumChain这个方法在电脑端是可以正常使用的，但是在metamask手机app上，它有一个自带的浏览器，在那个浏览器里就不能使用这个方法，点击按钮啥反应也没有。
> 
> switch 网络在 metamask 移动端不存在，直接用添加那个功能就好了。

其实是可以实现的，我给你看一个dapp，链接：https://flux.01.finance/?chain=okexchain ，你用metamask打开，这个dapp上可以选择一个主网，然后你手动将自己metamask的主网改成和他不一样，然后就会跳出一个界面叫你切换主网的，然后它就可以在移动端切换。其实我很奇怪，metamask的switchNetwork的api就这一个啊，难道还有其他的方法？

**Comment by emadhamad171** [comment]
> > > 请问你的这个问题解决了吗，我正好也碰到这个问题。就是wallet_switchEthereumChain这个方法在电脑端是可以正常使用的，但是在metamask手机app上，它有一个自带的浏览器，在那个浏览器里就不能使用这个方法，点击按钮啥反应也没有。
> > 
> > 
> > switch 网络在 metamask 移动端不存在，直接用添加那个功能就好了。
> 
> 其实是可以实现的，我给你看一个dapp，链接：https://flux.01.finance/?chain=okexchain ，你用metamask打开，这个dapp上可以选择一个主网，然后你手动将自己metamask的主网改成和他不一样，然后就会跳出一个界面叫你切换主网的，然后它就可以在移动端切换。其实我很奇怪，metamask的switchNetwork的api就这一个啊，难道还有其他的方法？

Hello, can you help me, i am trying to use wallet_switchEthereumChain or wallet_addEthereumChain both of them just opens the app and nothing happens after, how you made it work, thanks

**Comment by danjm** [comment]
Please open a ticket in the mobile repo https://github.com/MetaMask/metamask-mobile
