### ISSUE TITLE
Metamask installation improperly required to view documentation

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#11560]
**Describe the bug**
Attempting to view documentation requires the user to have MetaMask installed, when documentation should be viewable without the extension.

**Steps to reproduce (REQUIRED)**
1. In a browser WITHOUT MetaMask installed, visit https://metamask.github.io/api-playground/api-documentation/

**Actual behavior**
Content is not scrollable and fixed under this popover, which does not present any option to proceed with reading the documentation without installing Metamask: 
![image](https://user-images.githubusercontent.com/563406/126202367-8084f4ae-b0ac-49ea-a210-a17e74976765.png)

**Expected behavior**
An informational message like "Interactive features require installing MetaMask" instead of a warning symbol and clear command "Install MetaMask for your platform and refresh the page" followed by options including a "Proceed without" button which allows one to read the contents of the page.

Due to the privacy implications of MetaMask detection, it is perfectly reasonable that a person might not want to install MetaMask on their primary browser used for reading documentation etc.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: N/A
 - Browser: FF 89.0.2 (64-bit)
 - MetaMask Version: N/A

**Comment by BboyAkers** [comment]
I can take up this one! 🙂

**Comment by BboyAkers** [comment]
I have a PR up for this https://github.com/MetaMask/api-playground/pull/29 🙂

**Comment by shanejonas** [comment]
Fixed in https://github.com/MetaMask/api-playground/pull/29
