### ISSUE TITLE
Sending dpet token

### ISSUE THREAD

**Issue by cym-dev** [MetaMask/metamask-extension#11562]
**Describe the bug**
I will send dpet token to him but they not recieve that i open his acc too but dpet token is still 0 my transaction is successful but they not recieve the token

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.
I want know why they did not recieve the token can i refund that

**Screenshots**
![Screenshot_2021-07-20-10-16-35-80_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/78855120/126252587-66dbdf91-3103-4151-9586-c113ab753e68.jpg)

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows] android
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)] kiwi browser
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by cym-dev** [comment]
Please help mee

**Comment by danjm** [comment]
Please submit a support request via our form here: https://metamask.zendesk.com/hc/en-us/requests/new
