### ISSUE TITLE
Cannot submit transactions that send ETH to some contracts on 9.8.0

### ISSUE THREAD

**Issue by sirasistant** [MetaMask/metamask-extension#11579]
**Describe the bug**
The "Next" button is disabled when trying to send transactions with value to some contracts. This does not happen when sending to every contract, and does not happen when sending to external accounts (non-contract).

**Steps to reproduce (REQUIRED)**
1. Unlock your metamask wallet
2. Go to 'Send'
2. Set this contract 0x30b84DC1A46C58E0BcfE6AA9f74042dFf159277a as target (as example)
3. Set a non-zero amount (eg. 0.001 ETH)
4. The "Next" button is disabled

**Expected behavior**
The "Next" button should not be disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/5372114/126483994-aa316ca4-e09c-47b1-8d9d-faad057865a9.png)

**Browser details (please complete the following information):**
 - OS: Linux & Mac (haven't tested on Windows)
 - Hardware Wallet: none
 - Browser: Chrome & Opera & Firefox 
 - MetaMask Version: 9.8.0

**Additional context (Error Messages, etc.)**
If you enable advanced gas controls in settings and click on advanced settings and save the same gasLimit and gasPrice, then, the Next button is enabled.

**Comment by sirasistant** [comment]
This contract is a Proxy contract (entry point of a POA bridge), and in the past metamask had issues with gas estimation when sending ETH to it, metamask assumed it was an External account and set a gas limit to 21k (base TX gas) like it didn't call eth_estimategas. We just informed users about the correct gas limit to set, but this bug blocks users from sending transactions altogether.

**Comment by danjm** [comment]
Thank you for the report and the reproduction steps, we are investigating
