### ISSUE TITLE
Can not remove Testnets

### ISSUE THREAD

**Issue by TyrionLionstar** [MetaMask/metamask-extension#11599]
**Describe the bug**
Can not remove testnets. Very annoying.

**Steps to reproduce (REQUIRED)**
1. Click on Metamask extension
2. Click on Account picture
3. Click on Settings
4. Click on Networks
5. Click on one of the four testnets
6. "Delete" button is missing

**Expected behavior**
I expect to be able to delete the testnets, as they are not used by 99% of Metamask users. Thank you!

**Comment by luptak** [comment]
I wholeheartedly agree with this, just let us remove/hide them please. :)

**Comment by Egregius2k** [comment]
Such a pernicious recurring issue! Greatly hinders usability.

**Comment by tomasz90** [comment]
I sometiemes use them, but feature to hide them should be included... For instance kovan network is not useble at all, since there is no working faucet...

**Comment by jalavosus** [comment]
Can this actually happen? Having several testnets just sitting around doing nothing is more than slightly annoying, and being able to remove them would be extremely helpful.

**Comment by paulrberg** [comment]
With the advent of Polygon, BSC, and Fantom, the list of networks in MetaMask has become rather congested:

<img width="294" alt="Capture d’écran 2021-09-11 à 20 50 10" src="https://user-images.githubusercontent.com/8782666/132956789-8d1dd1be-12d5-4f8d-86a8-843c7c74e6d8.png">

It would be great if we could:

1. Opt-in to delete the Ethereum testnets, but be able to later re-add them.
2. Sort the networks (at least alphabetically if not otherwise).

**Comment by danjm** [comment]
This will be addressed by https://github.com/MetaMask/metamask-extension/issues/11473

**Comment by paulrberg** [comment]
Looks like this has been added in v10.6.0 🎉

<img width="313" alt="Capture d’écran 2021-11-20 à 10 25 25" src="https://user-images.githubusercontent.com/8782666/142719777-81aaf4a5-8faf-48b4-9b74-9eb59bb50726.png">

**Comment by TyrionLionstar** [comment]
Thank you for adding this feature!
It's almost perfect.
![image](https://user-images.githubusercontent.com/83534870/143089769-7d23ce7f-6760-4202-9725-7f3acaf9765f.png)
It seems to reserve the space of the testnets. Maybe can remove the spacing with another update.

**Comment by marcbluersky** [comment]
hi Guys, I don't see the Test network even if they are in my list. On my smartphone, I see them. It's weird. Do you know why ? 

![image](https://user-images.githubusercontent.com/95524651/144704358-82a4f0e3-4b33-48d8-b83b-bcc76693ac0c.png)

![image](https://user-images.githubusercontent.com/95524651/144704370-72cdc998-64df-4682-816d-8e08ea066650.png)

**Comment by danjm** [comment]
@marcbluersky you might have clicked the dismiss button here:

![Screenshot from 2022-01-06 11-15-09](https://user-images.githubusercontent.com/7499938/148400741-d21a974f-b04b-405a-a60a-4b32a8833f23.png)

You can go into advanced settings and toggle display of the test networks on:

![Screenshot from 2022-01-06 11-16-26](https://user-images.githubusercontent.com/7499938/148400920-3cd1955b-119c-421a-8ece-730e7c1839d3.png)

**Comment by danjm** [comment]
I created this ticket to address the one additional UI annoyance that was mentioned above https://github.com/MetaMask/metamask-extension/issues/13231

**Comment by theklos** [comment]
Hi. It seems the iOS app still doesn’t have the ability to disable test networks. Is this in the works still @danjm ? Thanks.
