### ISSUE TITLE
invalid opcode: opcode 0xa9 not defined

### ISSUE THREAD

**Issue by shikhars371** [MetaMask/metamask-extension#11609]
when i am using metmask on chrome extention for transactions, it working totally fine, but on mobile metmask browser when i am opening my application and doing the transaction its throwing the error - " Warning! Error encountered during contract execution [invalid opcode: opcode 0xa9 not defined] "   --- here is the trnasaction hash link https://bscscan.com/tx/0x89e8640d8c3c50859e411ee70269a361d540858e02f643ce1e6dc7bc80de3499

can you please help me out?

**Comment by danjm** [comment]
@shikhars371 If you are still experiencing an issue, please contact metamask support
