### ISSUE TITLE
Bug - For ERC721 NFT tokens

### ISSUE THREAD

**Issue by SayaGT** [MetaMask/metamask-extension#11611]
**Describe the bug**
For ERC721 NFT tokens, when "approving", we are taking the "Token ID" as the amount. 

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to '[this link on Etherscan](https://etherscan.io/address/0xf619e90052965e4c366c0c62af0f90216f35a5d8#writeContract)'
2. Click on 'Connect to Web3'
3. Click on 'approve'
4. Add your 'to' & 'tokenID' (Use a ERC721 token that you own)
5. Click 'write'

**Expected behavior**
The amount should always be shown as "1 (NFT name)". And we should add new field to show the "Token ID".

**Screenshots**
See attached screenshots.
![ERC721-Wrong Amount-2](https://user-images.githubusercontent.com/87030673/126983796-5e95e7e2-1074-4c59-8560-31f61d7ca0b9.jpeg)
![ERC721-Wrong Amount-1](https://user-images.githubusercontent.com/87030673/126983801-5c10a61a-5552-492c-9399-6f7325791f23.jpeg)

**Browser details (please complete the following information):**
 - OS: [macOS Big Sur (Version 11.1]
 - Browser: [Chrome Version 91.0.4472.164 (Official Build) (x86_64)]
 - MetaMask Version: [9.8.2]

**Additional context**
In the screenshots,
- it should say "Amount: 1 Tes" ('Tes' is the name of the NFT collection and '2' is the Token ID)
- it should say "Amount: 1 QOTI" ('QOTI' is the name of the NFT collection and '3164' is the Token ID)

**Comment by danjm** [comment]
@adonesky1 This relates to work you currently have in progress. Can you advise on this question:

> How to determine approval for NFT token (in comparison with approval for other token types)?

**Comment by adonesky1** [comment]
I will address this as part of https://github.com/MetaMask/metamask-extension/pull/13048

**Comment by danjm** [comment]
@adonesky1 I think this is unblocked now. Can you advice on: How to determine approval for NFT token (in comparison with approval for other token types)? (On the approve screen)

**Comment by adonesky1** [comment]
@danjm yes. I have a [WIP PR](https://github.com/MetaMask/metamask-extension/pull/13131) for this that I am hoping to get back to ASAP!
