### ISSUE TITLE
EIP-1559 - Odd Edit Bug in Edit Gas Popover

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#11639]
With a transaction that's hanging, I tried a cancel, and saw a bit of weirdness:

https://user-images.githubusercontent.com/46655/127212679-ae74031e-8eb1-41e6-af3f-e302c80458d5.mp4

A few things:

1.  For some reason the old form displays for a bit, then the new form fields display -- it should stay one or the other
2. The gas price value looks ... odd

**Comment by darkwing** [comment]
Seeing the following in `advanced-gas-controls.component.js`:

- The `gasEstimate` type is alternating between `fee-market` and `eth_gasPrice`
- The `gasPrice` is being passed in as: `1.3e-8`

**Comment by darkwing** [comment]
The `showFeeMarketFields` variable was introduced a few weeks ago, and this hasn't been happing that long, so it's a side effect of something else.

**Comment by danjm** [comment]
This is due to the bug on the gas estimates api. Once that is fixed, it will go away
