### ISSUE TITLE
Add Infuranet support

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1164]
While Ropsten is getting wrecked, Infura has created a new consortium test net, we should add it as a default provider:

https://infuranet.infura.io/

More details:
https://consensys.quip.com/tVWtAcGPeyyi

**Comment by flyswatter** [comment]
Oh apparently this isn't public-ready yet, but I'll leave this open as a placeholder for when it is.

**Comment by flyswatter** [comment]
We need to know the network ID before we can do this.

**Comment by Zanibas** [comment]
The network ID is 5810, but they're not ready yet. Still need fauceting/other features.
