### ISSUE TITLE
EIP-1559 - Learn more links

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#11648]
**Steps to reproduce - Scenario 1**

1. Login to the extension
2. Click the Send button on the Home page
3. Select a recipient on the Add Recipient page
4. Click the Max amount button on the Send page, then click Next
5. Click the Estimate gas fee tool tip
6. Click the `Learn more about gas fees` link

**Steps to reproduce - Scenario 2**
1. Login to the extension
2. Click the Send button on the Home page
3. Select a recipient on the Add Recipient page
4. Click the Max amount button on the Send page, then click Next
5. Click the `Edit` link in the Estimate gas fee section
6. Click the `How should I choose?` link

**Expected behavior**
Link opens in a new tab in both the popup and expanded view
Links to an article and not the extension

**Screenshots**
https://user-images.githubusercontent.com/53189696/127330970-503f6966-e01e-4781-a3a5-2b2cea573241.mov

**Comment by ryanml** [comment]
This was closed via: https://github.com/MetaMask/metamask-extension/pull/11650
