### ISSUE TITLE
EIP-1559 - Switch/add some network checks to account checks

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#11678]
After https://github.com/MetaMask/metamask-extension/pull/11596 is merged, we need to audit the usage of EIP1559 network checks, and either replace or add to that check with checking that the user's account will allow for 1559 transactions/fields.  Neither hardware wallet presently supports them.

**Comment by adonesky1** [comment]
Addressed by https://github.com/MetaMask/metamask-extension/pull/11716
