### ISSUE TITLE
MetaMask - RPC Error: Expected 0x-prefixed, unpadded, non-zero hexadecimal string 'chainId'. Received: 43113

### ISSUE THREAD

**Issue by zarifpour** [MetaMask/metamask-extension#11670]
I would like to make it easy for users to add a network to MetaMask.

This is a working example I found online:

    const addNetwork = () => {
        const params = [{
            chainId: '0x1e',
            chainName: 'RSK Mainnet',
            nativeCurrency: {
                name: 'RSK BTC',
                symbol: 'RBTC',
                decimals: 18
            },
            rpcUrls: ['https://public-node.rsk.co'],
            blockExplorerUrls: ['https://explorer.rsk.co']
        }]
    
        window.ethereum.request({ method: 'wallet_addEthereumChain', params })
            .then(() => console.log('Success'))
            .catch((error) => console.log("Error: " + error.message))
    }

However, in my case, I would like to add Avalanche (AVAX), more specifically the FUJI C-Chain. The chain ID for FUJI, or even Mainnet, does not begin with '0x', but it begins with '4311'.

    const addNetwork = () => {
        const params = [{
            chainId: '43113',
            chainName: 'Avalanche FUJI C-Chain',
            nativeCurrency: {
                symbol: 'AVAX',
                decimals: 18
            },
            rpcUrls: ['https://api.avax-test.network/ext/bc/C/rpc'],
            blockExplorerUrls: ['https://cchain.explorer.avax-test.network']
        }]
    
        window.ethereum.request({ method: 'wallet_addEthereumChain', params })
            .then(() => console.log('Success'))
            .catch((error) => console.log("Error: " + error.message))
    }

When I run this code I get the error: "RPC Error: Expected 0x-prefixed..."

Why aren't these networks supported?

Not sure if this was intended or if it is bug... anyway, please advise.

**Comment by zarifpour** [comment]
I also tried the implementation in AVAX docs... https://docs.avax.network/build/tutorials/smart-contracts/add-avalanche-to-metamask-programmatically. Still getting an RPC Error with the same message.

**Comment by zarifpour** [comment]
Working on Mainnet: I had to convert the `chainId` from `43114` to its hex representation `0xa86a` However, still not supporting adding Avalanche Testnet.

    export const AVALANCHE_TESTNET_PARAMS = [{
        chainId: '0xa869', // 43113 in Decimal
        chainName: 'Avalanche Testnet C-Chain',
        nativeCurrency: {
            name: 'Avalanche',
            symbol: 'AVAX',
            decimals: 18
        },
        rpcUrls: ['https://api.avax-test.network/ext/bc/C/rpc'],
        blockExplorerUrls: ['https://cchain.explorer.avax-test.network/']
    }]

    const addAvaxTestnet = () => {
        injected.getProvider().then(provider => {
            provider
                .request({
                    method: 'wallet_addEthereumChain',
                    params: [AVALANCHE_TESTNET_PARAMS]
                })
                .catch((error) => {
                    console.log(error)
                })
        })
    }

This is the error message: `MetaMask - RPC Error: Received unexpected keys on object parameter. Unsupported keys:`

**Comment by liran319** [comment]
According to docs, rpcUrls should be a url string, not a array

**Comment by naftalimurgor** [comment]
Hi,
Has anyone been able to resolve this issue yet? Kindly share any pointers to external source docs etc. I'm experiencing similar issue with Polygon(formerly Matic ) while trying to connect using Metamaks following this:     https://eips.ethereum.org/EIPS/eip-3085
Any help is appreciated. Thanks everyone

**Comment by jacobc-eth** [comment]
Hi friends, developer support is typically best directed to the Ethereum StackExchange. @zarifpour you're current that you need to use the hex value, not the decimal value. This is definitely not a MetaMask bug.

For reference, chainlist.org has a working implementation for the Avalanche testnet. You can see how they structure their implementation here:

https://github.com/antonnell/networklist-org

**Comment by zarifpour** [comment]
Yeah, I'm familiar with chainlist, however I failed to replicate their implementation. Not sure why it's still not working on my end, but I will revisit this when I get back to working on the project. Thanks for the reply.
