### ISSUE TITLE
Extension sends random cached addressed instead of the one entered

### ISSUE THREAD

**Issue by roromi13** [MetaMask/metamask-extension#11677]
**Describe the bug**
1. Used the send function from my wallet to my other wallet
2. Transfer address was checked 2-3 times and was deemed to be correct
3. Wallet history show it was sent to the correct address but opening the linked block explorer transaction, it was sent to a different account

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Metamask extension
2. Click on send
3. Enter recipient
4. Click on Next
5. Click on Confirm

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/83640918/127571472-c478a1f4-7e68-4e9c-96bc-bd46a359b6d2.png)
Failed to save the expanded view of this transaction but all values were consistent including the nonceswith the block explorer except the address

Block explorer: https://bscscan.com/tx/0x9766e7d7f6724b82c41a72f289d6bbb08c5adc8607c37447250371cdb6c9f12a

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: NA
 - Browser: Chrome
 - MetaMask Version: 9.8.2

**Additional context (Error Messages, etc.)**
Most likely it is related to how the extension handles the caching or idk. Luckily, I knew the owner of the wallet and had my little funds sent back to me. I suspect it is closely related to the "Contacts" feature of the extension

**Comment by danjm** [comment]
Thanks for the report. Can you privately submit your state logs via a customer support ticket?

To download your state logs:
(1) Go to "Settings" in MetaMask
(2) Click "Advanced"
(3) Click "Download state logs"

To submit a support ticket, go to https://consensys.zendesk.com/agent/dashboard, and select "MetaMask Extension" in the first drop you see. In the ticket, just copy a link to this github issue, and attach the state logs json file that you downloaded.

This will help us debug this issue

**Comment by roromi13** [comment]
Not sure if it is still available in state logs, I'll be sending it now

**Comment by roromi13** [comment]
I'm getting access denied in zendesk. Sent it to your gmail instead

**Comment by dpazdan** [comment]
@roromi13 I highly recommend scanning the device for possible clipboard malware. 

You can determine if this is the cause by copying another address, and paste it to see if it changes every time to a random address (a malware address)

**Comment by roromi13** [comment]
> @roromi13 I highly recommend scanning the device for possible clipboard malware.
> 
> You can determine if this is the cause by copying another address, and paste it to see if it changes every time to a random address (a malware address).
@dpazdan 

You just assumed directly without reading the whole thing. I am aware of the clipboard malware and that is not the case. I did review the address since these stuff are rampant thus it is impossible not to notice that. Also the address is from my friend inwhich I was able to retrieve the funds easily. If you see the activity tab, the right address is pasted there. Even if it is expanded, it would still have the right address but what is submitted in the chain is different as what is seen in the etherscan. I sent the MM logs to danjm, you should find something there. 

I think the problem lies with your the feature "contacts" and that it is bug since that is the only area which the address was stored and may have pulled the data there randomly.



Related to the issue:
This "contacts" feature of yours in MM randomly records addresses of protocols/contracts/pools they have indirectly interacted with. (e.g using sushiswap to trade token X to token Y, sometimes records the pool XY to the contacts)

I am a support myself and see these things happen from time to time. I though some were just idiots but I have seen experienced users having sent their tokens to trustless contract addresses or pools (whom no one benefits) even if both their activity tab (expanded) shows the correct address, I think MM randomly pulls and send to addresses "contacts" instead of the input given when the user submitted the transaction.

**Comment by adonesky1** [comment]
@roromi13 I'm very sorry to hear that you've experienced this issue though relieved that you were able to recover your funds. We definitely want to take this seriously and I will begin investigating promptly - I have your state logs here to dig into. Just want to clarify, since you brought up the contact list and stated that the funds ended up being sent to your friend, it sounds like the "random cached address" was one that was in your contact list? Just want to make sure because I'm not seeing that address in your statelogs as a contact? Did you remove them from your contacts?

**Comment by adonesky1** [comment]
Also just to clarify when you say:

> Used the send function from my wallet to my other wallet

Do you mean transfer between accounts in Metamask like this?
<img width="474" alt="Screen Shot 2021-10-18 at 4 54 06 PM" src="https://user-images.githubusercontent.com/34557516/137812071-60ecd1e2-30a5-4240-917a-327848908a00.png">
I'm assuming so because the highlighted address (you wanted to target right?) in the image you provided is another account in your metamask wallet.

**Comment by roromi13** [comment]
I did remove him from contacts after this issue, not sure if the logs would
have covered that. And yes, I used the transfer address. I'm pretty certain
it has something to do with the contact list. Why not just remove it
entirely? Also it seems that it randomly saves addresses users do not
intend to as long as they had interaction with it. That + this bug I am
experiencing I think is the reason why many users are supposedly sending
tokens to permissionless contracts randomly when no one benefits from it.

**Comment by adonesky1** [comment]
Or are you talking about recently interacted with addresses, as shown here: 

<img width="482" alt="Screen Shot 2021-10-18 at 5 08 16 PM" src="https://user-images.githubusercontent.com/34557516/137813332-2dd519aa-ca91-44af-94f3-709fcf19bf87.png">

**Comment by adonesky1** [comment]
Ok thanks for the context @roromi13 I will investigate further and get back to you!
