### ISSUE TITLE
EIP-1559 - Speed up and Cancel transaction gas estimates

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#11671]
**Steps to reproduce**

1. Login to the extension
2. Click the Network drop down, Select `Rinkeby Test Network`
3. Click the Swap button on the Home page
4. Enter a amount to swap from
5. Select a token to swap to
5. Click Review Swap
6. Click the Edit link in the Estimate gas fee section, take note of the gas estimate
7. Click Submit, then click Swap
8. Click View in activity
9. Click Speed Up or Cancel, take note of the gas estimate

**Expected behavior**
The gas estimate is 10% more than the initial transaction

**Screenshots**
https://user-images.githubusercontent.com/53189696/127499946-3e8e80da-142e-47d0-b919-35df8edae909.mov

**Comment by danjm** [comment]
Closed by #11701
