### ISSUE TITLE
Snaps Custom Confirmation

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#11686]
We want to allow snaps to show custom confirmations to the user. This will allow snap devs to ask for user consent before taking certain actions, such as signing.

This custom confirmation can be very limited to start with, with just a custom title, maybe a custom subtitle, a custom text area, and "Confirm" / "Reject" buttons (or something similar). All custom text areas should be specified by the snap.

We should make it clear that the confirmation is coming from the snap, not from MetaMask. We don't know what it happens if the user confirms, whether the text is accurate, or how high or low risk the action being confirmed might be. All we know is that it's internal to the snap.

**Comment by Gudahtt** [comment]
This is blocked by #11626

**Comment by holantonela** [comment]
I've worked on a first iteration for this task. Happy to learn what we want to allow devs to do here!

https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/?node-id=336%3A6342

**Comment by holantonela** [comment]
Final UI here

https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/Snaps-MVP?node-id=336%3A6344

**Comment by rekmarks** [comment]
We will still need to tweak some parameter / `requestData` parsing when we bump the `skunkworks` packages, but this is in essence completed.
