### ISSUE TITLE
Snaps Installation UI

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#11682]
We should allow dapps to request permission to use snaps when requesting permissions or connecting. If the user doesn't have the snap installed yet, this should initiate the snap install process. We will need to download the snap manifest and present the user with enough information to decide whether or not to install the snap. This should include:

- [x] The snap name
- [x] The snap author
- [x] The place the snap was downloaded from
- [x] The snap description
- [x] The permissions the snap requires
        [ ] This should include detailed description of what each permission is, and why it might matter to a user
- [x] The reason I'm being asked to install the snap (e.g. the dapp that asked permission to use the snap).

This UI should be incorporated into the connect flow, so that the dapp is completely ready to use after the connection process.

As a user, I want to be notified of the following snaps errors:
- When a snap fails to install
  - This will probably be because the snap crashed immediately when MetaMask tried to run it, but it could be for other reasons, so a generic "failed to install" error with a more detailed / verbose error message somehow accessible would be helpful.

https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/Flask-MVP?node-id=336%3A9134

**Comment by Gudahtt** [comment]
This is blocked by #11626

**Comment by holantonela** [comment]
After our permissions discussion, I consolidated the last version here, ready for review:

https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/?node-id=336%3A6342

Converting the requirement's list in a to-do here too.

**Comment by holantonela** [comment]
`The reason I'm being asked to install the snap (e.g. the dapp that asked permission to use the snap).` is it ok to think about this requirement as an step in the connect flow where "the site wants to connect with snap" ? For a reference view flow "Add Snap - Site permissions"

**Comment by holantonela** [comment]
` The place the snap was downloaded from` is this a URL? How we want to show it?

**Comment by Gudahtt** [comment]
>is it ok to think about this requirement as a step in the connect flow where "the site wants to connect with snap" ?

Yes - definitely. I think that would fulfill the requirement anyway. I guess we'll see if users are confused or not :sweat_smile:. We can spell it out for them if it becomes an issue.

>is this a URL? How we want to show it?

See [my comment on the other issue](https://github.com/MetaMask/metamask-extension/issues/11681#issuecomment-896833014).

**Comment by holantonela** [comment]
Final UI here

https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/Snaps-MVP?node-id=336%3A6344
