### ISSUE TITLE
EIP-1559 - unknown processing time

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#11683]
**Steps to reproduce**

1. Login to the extension
2. Click the Send button on the Home page
3. Select a recipient on the Add Recipient page
4. Click the Max amount button on the Send page, then click Next
5. Click the Edit link in the Estimate gas fee section
6. Select the Low radio button
7. Enter 0 in the Max fee input

**Expected behavior**
Gas timing estimate `Likely in X seconds` is NOT displayed
Gas timing estimate `Unknown processing time` is displayed

**Screenshots**
<img width="364" alt="gas estimates" src="https://user-images.githubusercontent.com/53189696/127651205-fdbd13f0-731d-4386-8d1e-87b86b0daf6b.png">

**Comment by darkwing** [comment]
Fixed with https://github.com/MetaMask/metamask-extension/pull/11668
