### ISSUE TITLE
Matic mainnet transaction history not showing

### ISSUE THREAD

**Issue by TheEndlessNexus** [MetaMask/metamask-extension#11688]
**Bug Description**
The Matic mainnet transactions using MetaMask aren’t showing up in the MetaMask transaction history. The Ethereum mainnet transactions show up fine on MetaMask, but nothing on Matic. They all show up correctly with my correct wallet on Polygonscan, but not on MetaMask. Just checking if this is just me or happening to others. Thank you!

**Steps to Reproduce**

- Open MetaMask browser extension
- Switch to Matic Mainnet 
- Click activity tab or click settings -> advanced -> download state logs

**Expected Behavior**
There should be a full history on Metamask using the Matic Mainnet.

**Comment by darkwing** [comment]
Were these transaction you received/sent via MetaMask, or another wallet?

**Comment by TheEndlessNexus** [comment]
I sent them via MetaMask. For some reason my Ethereum transactions are
showing up on MetaMask, but not my Polygon ones.

The only transaction I sent via MetaMask that I need a confirmation of is
this one
https://polygonscan.com/tx/0x4e440de068108f035d26a72e60ca3a7e4ac7bf7d47f57138f5b5e34ed34a5a15

**Comment by batienergy** [comment]
Same thing happening with me

**Comment by bschorchit** [comment]
Were the transactions send in the same MetaMask instance? Or in different ones (e.g. transaction sent on mobile and activity checked on extension)

**Comment by bschorchit** [comment]
Closing as no response
