### ISSUE TITLE
Snap Settings Page

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#11681]
We need a settings page for snaps. This page should list all snaps.

For each snap, it should display:

- [x] The snap name
- [x] The snap author
- [x] The place the snap was downloaded from
- [x] The snap install date
- [x] The snap description
- [x] All permissions that the snap has
- [x] Whether or not the snap is currently running
- [x] Whether or not the snap is currently enabled
- [x] Some way to enable/disable the snap.

**Comment by Gudahtt** [comment]
This is blocked by #11626

**Comment by holantonela** [comment]
I've been cleaning our past week's exploration for this task. Linking here the last version. For mind clarity, I'm converting the requirements in a to-do list and marking what is done. 

https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/?node-id=336%3A6342

**Comment by holantonela** [comment]
`The place the snap was downloaded from` is a url? How we want to show it? Which format?

**Comment by holantonela** [comment]
` The snap description` can we show a short and a long description? Cropping text randomly is risky and we need a short version for smaller views in 360px popup views.

**Comment by Gudahtt** [comment]
>`The place the snap was downloaded from` is a url? How we want to show it? Which format?

Yes, it will be a URL of some sort.

Elsewhere in the extension (e.g. on our confirmation screens), we show just the origin of the URL. And for the most common protocol (HTTPS), we omit the scheme as well, leaving just the domain name. That same approach can probably work here too?

Our goal here is to establish who we're asking the user to trust. The owner of an original typically controls the sites hosted on the origin, so that's the best we can do for now.

As a secondary concern, it might be useful for developers and advanced users to see the full download URL somewhere. But this is not what the bullet point in the description was meant for. We can leave this out for now, or leave it hidden somewhere (e.g. a tooltip, an href target, etc.). Or we could add that later as part of a 'dev mode' feature. Something like that.

>` The snap description` can we show a short and a long description? Cropping text randomly is risky and we need a short version for smaller views in 360px popup views.

Good idea! Yes, we can do that.

**Comment by holantonela** [comment]
Final UI here

https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/Snaps-MVP?node-id=336%3A6344
