### ISSUE TITLE
EIP-1559 - Remove suggested gas fee label after the transaction has been updated

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#11692]
**Steps to reproduce**

1. Login to the extension
2. Navigate to test dapp `https://andrepimenta.github.io/eth_sendTransaction`
3. Connect to MM
4. Click `Send transaction with suggested EIP1559 GAS`
5. Click the `Edit` back button
6. Update the Send amount from 0.0001 to 0.0002 , click Next

**Expected behavior**

The label `andrepimenta.github.io suggested gas fee` does not appear after editing the send transaction

**Screenshots**

<img width="357" alt="dapp suggested gas fee" src="https://user-images.githubusercontent.com/53189696/127702905-3015001e-ad36-4c19-9728-63e954ff6eb7.png">

**Comment by danjm** [comment]
Fixed with send slice refactor
