### ISSUE TITLE
Add dapp integration tests

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1170]
We do not currently have tests that test the interaction between a web Dapp and metamask itself all in one integration.

This seems well within our abilities, with a lot of the work we've done on Mascara, so we should make it a priority soon.

**Comment by whymarrh** [comment]
The e2e tests now include tests that interact with locally hosted dapps. #5488 is exploring how we can better structure the tests to facilitate more types of dapps in the future.
