### ISSUE TITLE
EIP-1559 - gas limit is not populated when selecting a recommended radio options after  updating its value

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#11705]
**Steps to reproduce**

1. Login to the extension
2. Click the Send button on the Home page
3. Select a recipient on the Add Recipient page
4. Click the Max amount button on the Send page, then click Next
5. Click the Edit link in the Estimate gas fee section
6. `Clear` the Gas Limit, Max priority fee and Max fee fields
7. Click any of the recommended gas options e.g. Low, Medium High

**Expected behavior**
The Gas Limit, Max priority fee and Max fee are all populated with the recommended values

**Screenshots**

https://user-images.githubusercontent.com/53189696/127737404-8349af41-946a-4dd8-a8c9-c8796770daa6.mov

**Comment by darkwing** [comment]
@danjm Didn't we discuss this yesterday, in that there's no relationship between gasLimit and the radio buttons?

**Comment by PeterYinusa** [comment]
Can no longer be reproduced
