### ISSUE TITLE
Is there a way to add a ERC-721 to metamask similar to how you can add ERC-20s via button click?

### ISSUE THREAD

**Issue by VexyCats** [MetaMask/metamask-extension#11704]
There is a new API to add tokens via a function, so that sites can have a button to show "add to metamask"

Is there a similar feature for adding ERC-721s? 

I cannot find this in the documentation.  Only for ERC20s https://docs.metamask.io/guide/registering-your-token.html#code-free-example

If not....why not? We should have this 100%.

**Comment by VexyCats** [comment]
If there is not, and we add the feature and make a PR - what are the chances the team will review, and approve it and add it? Is this something that we should spend some time on to help get 721s UX to a better level? 

@NiranjanaBinoy  @holantonela @danfinlay

**Comment by bschorchit** [comment]
We don't have it yet. The best way to do it would be to extend the wallet_watchAsset methods to also work for ERC-721 and ERC-1155. 
We would be happy to review a community contribution for this. Regarding time to review it, it would depend on the current team focus and priorities at the time the PR is submitted.
