### ISSUE TITLE
He tenido problemas para restaurar las direcciones incluso la app se reinicia sola borrando toda la información y los activo y aparte no me deja conectar en Etherscam en su navegador ni en el de Walletconnect

### ISSUE THREAD

**Issue by DausAdy** [MetaMask/metamask-extension#11717]
He tenido problemas para restaurar las direcciones incluso la app se reinicia sola borrando toda la información y los activo y aparte no me deja conectar en Etherscam en su navegador ni en el de Walletconnect 
Más sin embargo guarto todas mi claves en drive o en Office

_Originally posted by @DausAdy in https://github.com/MetaMask/metamask-extension/issues/3127#issuecomment-883980052_

**Comment by darkwing** [comment]
Translation: 

> I have had problems restoring the addresses, even the app restarts itself, deleting all the information and activating them, and apart from that, it does not allow me to connect to Etherscam in your browser or in Walletconnect.
More however I save all my keys in drive or in Office

**Comment by bschorchit** [comment]
Please user the MetaMask support link within the app so the team can help you with this.
