### ISSUE TITLE
EIP-1559 - BigNumber Error on long values

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#11747]
I tried making some wild numbers and am seeing the following:

https://user-images.githubusercontent.com/46655/128115737-2f0227e3-fb32-4bb6-9a00-abab33305278.mp4

Maybe we should have a minimum precision?  Could depend on custom network or not?

**Comment by danjm** [comment]
We can limit precision of maxFeePerGas, maxPriorityFeePerGas and gasPrice to 9 decimal places

**Comment by darkwing** [comment]
Fixed this a few days ago.
