### ISSUE TITLE
MetaMask Browser on IOS hangs up while loading Aragon

### ISSUE THREAD

**Issue by GurakG** [MetaMask/metamask-extension#11752]
IOS version 14.5.1
iPhone 12
Metamask 2-3.0.0

Description:
When trying to access https://client.aragon.org/#/aragoninterimcouncil/0x5988e9f019015884ca8a9653a88f6fdb05524175/ metamask gets stuck "fetching the data". 
Other browsers on IOS load the page fine. No problems occurring on computers either. 

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by dpazdan** [comment]
This is related to MetaMask mobile, please resubmit at https://github.com/MetaMask/metamask-mobile/issues/new/choose
