### ISSUE TITLE
Ensure transaction parameters from dapps are valid hex

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#11780]
See metamask-extension/app/scripts/controllers/transactions/lib/util.js

**Comment by david0xd** [comment]
Hi @danjm, can you please provide more information on this?
Are we verifying here the custom user input from the UI or the whole transaction parameter data internally?
_I'm considering this function as the target to validate the HEX: validateTxParams(txParams, eip1559Compatibility = true)._
I'm interested from where I can trigger the action (test-dapp) so we can later see the bad parameter inputs?
If you can provide a screenshot if this can be validated from the UI, it will also be very useful.

**Comment by vandan** [comment]
@hilvmason Can you confirm if any support is needed from the dapp API team to close this issue?
If not, can you remove the "area-api" label? Thank you!
