### ISSUE TITLE
Dapp with metamask not working for 2 days recently

### ISSUE THREAD

**Issue by RichGao** [MetaMask/metamask-extension#11791]
I've developed Dapp using web3 with metamask at 2021-08-02. While developing that, it works perfectly on my local. But after london-hard fork,my dapp doesn't work with metamask. Could anyone support me for this issue? And apologize my poor English.
Thanks

**Comment by adonesky1** [comment]
@RichGao Could you specify what is not working? Are you seeing errors in your browser console?

**Comment by RichGao** [comment]
@adonesky1  Thanks for your contact.
From 2021-08-08, my Dapp works with Metamask perfectly again. Sorry
