### ISSUE TITLE
Metamask Network Switch Window Freeze (Firefox + Ledger Nano S)

### ISSUE THREAD

**Issue by JMF8** [MetaMask/metamask-extension#11799]
### **Describe the bug**
I just switched from Brave to Firefox because I was having issues connecting my Ledger. Everything seems to be working but whenever Metamask detects a change in networks (ie. from Binance Smart Chain to Matic) via a website, it freezes on the "Allow this site to switch network?" message. I can't get out of it unless I quit Firefox and relaunch it. It may work a few times but if I am going back and forth between different networks it will quickly freeze up requiring me to quit/restart Firefox. I'm also on the latest versions of both Metamask as well as Firefox. Any ideas?

### **Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Open Firefox browser on Mac
2. Plug in Ledger hardware wallet
3. Set network to Matic Network 
4. Go to a Binance Smart Chain network DEX (Venus Finance for example)
5. Metamask will alert you with a popup asking "Allow this site to switch network?"
6. Nothing happens with you click the "Cancel" or "Switch Network" buttons. The window freezes on this message.

### **Expected behavior**
This automatic network change detection my Metamask will work fine for 1 or 2 network switches but it will eventually freeze up. Both the "Cancel" and "Switch Network" buttons don't work when clicked on. It requires me to quit and then restart Firefox to get out of this window. 

### **Screenshots**
![image](https://user-images.githubusercontent.com/88684518/128764748-8328c013-c400-4b7b-838a-4f5862e3a420.png)

### **Browser details (please complete the following information):**
 - OS: macOS Big Sur 11.5.1
 - Hardware Wallet: Ledger Nano S (Firmware 2.0.0
 - Browser: Firefox 90.0.2 (64-bit)
 - MetaMask Version: Metamask 9.8.4

**Comment by linuxtopia** [comment]
Same with me on Firefox and POP OS.

When I use any network rather than that website try to connect my metamsk with different network what gets stuck on these buttons.

Especially cancel no working and I have to click extension icon to pass that freezing. 

Made me sick!

**Comment by jkcdarunday** [comment]
Same here on Linux. No ledger wallet involved. Not sure if I should file as a separate error since this one has already been labeled with area-hardware and hardware-ledger.

**Comment by rrodriguezreche** [comment]
I confirm this happens too without a hardware wallet

**Comment by imsys** [comment]
For me, it only freezes when I click on "Cancel", if I accept the switch it works fine. If I go to inspect element, I get the "Error: PortDuplexStream - disconnected" when I click on Cancel.

![Selection_260](https://user-images.githubusercontent.com/911254/134003081-1b6d6e4e-8487-40d8-8621-8c9af2dd3094.png)

**Comment by domy-os** [comment]
Same here, completely fresh installation.

OS: Fedora Linux 35 (KDE Plasma) x86_64
Kernel: 5.15.5-200.fc35.x86_64
DE: Plasma 5.23.3

Browser: Mozilla Firefox 94.0 (64-bit)
MetaMask 10.6.4

**Comment by imsys** [comment]
Idk if it was a browser update, or a MetaMask update, but it is not freezing anymore! :) 🎉🎉🎉
Firefox 95.0.1 (64-bit)
MetaMask: 10.8.1

Now, when clicking on cancel, it just do nothing, but I can close metamask dialog window by clicking on the topbar X without any freezing.

The error I gets a similar, but in a different line.

![Screenshot_20211231_172424](https://user-images.githubusercontent.com/911254/147838245-f0154ba7-0246-4bec-be01-f6eeee854fe6.png)

**Comment by stoplion** [comment]
Still a prob Jan 2022

**Comment by jbshirk** [comment]
Still a problem. Firefox. Metamask wants to authorize app.solarbeam.io but I don't even have that bridge app open. It's never one of the options to remove, either. Neither approve nor deny do anything.
