### ISSUE TITLE
EIP-1559 - Estimate gas fee tooltip network name

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#11801]
**Steps to reproduce**

1. Login to the extension
2. Switch networks from `Ethereum Mainnet` to `Binance Smart Chain Mainnet`
3. Click the Send button on the Home page
4. Select a recipient on the Add Recipient page
5. Click the Max amount button on the Send page, then click Next
6. Hover over the `Estimate gas fee` tooltip

**Expected behavior**

The network name changes from `Ethereum` to `Binance` e.g.
Gas fees are paid to crypto miners who process transactions on the `Binance` network. MetaMask does not profit from gas fees.

**Comment by darkwing** [comment]
@jakehaugen Can we use `this network` or `Ethereum-based` networks for this tooltip?  I'd prefer not to shoehorn `${currentNetworkName}` here.

**Comment by jakehaugen** [comment]
In mobile we set the pattern that on Mainnet we say "the Ethereum network" and for every other network we say "the network". I'd propose this but open to suggestions.
