### ISSUE TITLE
EIP-1559 - Misleading tooltip message when providing EIP-1559 gas values

### ISSUE THREAD

**Issue by gabrocheleau** [MetaMask/metamask-extension#11803]
**Describe the bug**
When submitting a transaction to MetaMask with pre-populated `maxFeePerGas` and  `maxPriorityFeePerGas` values, MetaMask displays this [tooltip warning](https://github.com/MetaMask/metamask-extension/blob/e6543a83effce673c22397f828f410dff74bace9/app/_locales/en/messages.json#L2517-L2519) : "This gas fee suggestion is using legacy gas estimation which may be inaccurate." 

This is not accurate, since we're providing an estimate with EIP-1559 values, and not the legacy `gasPrice`. Our provided values do get correctly populated inside MetaMask though.

**Steps to reproduce**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Initialize a transaction with values for `maxFeePerGas` and `maxPriorityFeePerGas` and no value for `gasPrice`. 
2. See the warning tooltip with message "This gas fee suggestion is using legacy gas estimation which may be inaccurate."

**Expected behavior**
No warning, or a warning message that simply mentions that the website has already provided values for gas (without saying that it is using "legacy gas estimation").

**Screenshots**
![image](https://user-images.githubusercontent.com/18757482/128914028-a6062225-0db4-4671-bfd4-33ff6926adb1.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Brave Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (64-bit)
 - MetaMask Version: 10.0.0

**Comment by jpuri** [comment]
It appears issue is fixed in latest code. https://github.com/MetaMask/metamask-extension/blob/develop/app/_locales/en/messages.json#L2607

**Comment by gabrocheleau** [comment]
Indeed, thanks for closing!
