### ISSUE TITLE
Unable to connect to Ledger on M1 mac mini

### ISSUE THREAD

**Issue by doovers** [MetaMask/metamask-extension#11836]
**Describe the bug**
Everything has been working perfectly for months without issue until today when I tried to interact with my ledger through metamask and it didn't work. Typically when I confirm the transaction it will prompt me to confirm on the ledger but this time it didn't. Instead metamask behaved as if I had approved on the device and started to process the transaction. The transaction subsequently failed. I tried a few times with the same result. I then removed the hardware wallet account from metamask with the intention of re-adding it but now I can't. When I try to connect, I get `Internal JSON-RPC error`.

**Steps to reproduce**

1. Connect a hardware wallet
2. Select Ledger and continue
3. See `Internal JSON-RPC error`

**Expected behavior**
The wallet is connected.

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: Ledger Nano S Firmware version 2.0.0
 - Browser: Brave Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (arm64)
 - MetaMask Version: 9.8.4

**Additional context (Error Messages, etc.)**

Things I've tried:
- Restarting computer (same issue)
- Switching cables and ports (same issue)
- Using Chrome instead of Brave (same issue)
- Ledger Live bridge (gets stuck in loop trying to open ethereum app)
- Using another (non M1) laptop with same Metamask and Brave browser versions (WORKS!!)
- Connecting Phantom Solana app (WORKS!!)

**Comment by vying1** [comment]
This error (Internal JSON-RPC error) also occurs on Chromebook (no Ledger Live).  Windows works fine (also Chrome without Ledger Live).

**Comment by darkwing** [comment]
I believe this is related: https://github.com/MetaMask/eth-ledger-bridge-keyring/issues/89

**Comment by dpazdan** [comment]
Please note we will be deprecating the ledger live bridge and implementing webhid support. This will likely resolve your issue. In the meantime please use Firefox with MetaMask + Ledger. Refer to: #11978, thanks!

**Comment by awigen** [comment]
Make sure your ledger is unlocked (pin). That resolved the "Internal JSON-RPC error" issue for me.

**Comment by darkwing** [comment]
@doovers Could you provide an update as to whether this works at the moment?  If not, does toggling off and on the Ledger Live setting have an effect?  As @dpazdan mentioned, we'll be supporting WebHID very soon, to help remedy this issue.
