### ISSUE TITLE
"Edit priority" is not allowing edit of max fee

### ISSUE THREAD

**Issue by ethosdev** [MetaMask/metamask-extension#11834]
v10.0.1 in Firefox only has "Edit priority". There is no way to edit the "max fee".
I turned on all the advanced options I could find.

"Edit priority" is also confusing: am I editing the "max priority fee" or was I editing the "max fee"?

**Comment by danjm** [comment]
Thanks for the report @ethosdev Can you share a screenshot of what you are seeing? And what network are you on?

On mainnet I see I can edit both "Max Fee" and "Max Priority Fee"
![Screenshot from 2021-08-13 16-11-55](https://user-images.githubusercontent.com/7499938/129404660-b7d6b644-ff5f-4f17-a908-b2998b96e240.png)

Are you seeing something different?
