### ISSUE TITLE
Upgrading to 10.0 for EIP1559 support breaks xDai Network Signing

### ISSUE THREAD

**Issue by JHGrove3** [MetaMask/metamask-extension#11847]
**Describe the bug**

I'm trying to stake xNODE on the xDai network.

The website is 
https://app.dappnode.io/

Prior to the Version 10 upgrade I would be given a signing request, which I would confirm. Then I would be given a transaction to confirm to stake the xNode tokens.

After upgrading to Metamask 10.0.1 the signature request does not work. Metamask starts to show the pop-up for the signature, then almost immediately closes the pop-up.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to https://app.dappnode.io/  -- you must already have an account there with some xNODE tokens
2. Click on "Stake xNODE Tokens"
3. Type in the number of tokens you want to stake, then click "Deposit xNODE Tokens"
4. The Metamask pop-up appears for a moment, but then disappears again without showing anything.

**Expected behavior**
I was supposed to get a signature request, followed by a transaction to approve

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: None
 - Browser: Firefox Browser 91.0 (64-bit)
 - MetaMask Version: 10.0.1

**Additional context (Error Messages, etc.)**
Other users have confirmed the same problem

Rolling back to an earlier version of Metamask fixes the problem.

**Comment by JHGrove3** [comment]
I don't know whether this is related to / similar to the problem in this bug report:

Upgrading to 10.0 for EIP1599 support breaks Polygon dApps
https://github.com/MetaMask/metamask-extension/issues/11814

**Comment by mgarciate** [comment]
I checked that signing failed in Metamask with chains that have a chainId greater than 9, being 100 for xDai. Trying to sign on xDai returns the following error:
MetaMask - RPC Error: Provided chainId "256" must match the active chainId "100"
being 0x100 (hex) equal to 256 

After reviewing the latest commits from this repository, the bug could come from the following added lines:
https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/lib/typed-message-manager.js#L206

Modified in the following commit:
https://github.com/MetaMask/metamask-extension/commit/23f0270af2fcc2474cdb385f805ce7c0f6d8ed80#diff-3b96a08beb7729ba16e4feedd44f4fda17dbfe8dcf126a466ed712f05c5d5190R207

So I think this is a Metamask bug with all chain having a chainId >= 10. This is the reason why it works properly on Mainnet, Goerli, Rinkeby, ...

**Comment by xiaohanzhu** [comment]
The 10.0.x build treat chainid 101 as 257 and '101' as 257. breaks all chains with chainid >10

**Comment by Pol-Lanski** [comment]
Supporting @mgarciate and @xiaohanzhu 's claims with some screenshots

https://user-images.githubusercontent.com/19168735/130236012-8548a200-96db-49f0-b481-c0a66bdd2191.mov

This video shows the actual user experience. 

This is what the console shows:
<img width="640" alt="Screenshot 2021-08-20 at 14 54 59" src="https://user-images.githubusercontent.com/19168735/130236442-38916816-c500-404b-9102-f6a511a16a6e.png">

**Comment by marcovan123** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> I'm trying to stake xNODE on the xDai network.
> 
> The website is
> https://app.dappnode.io/
> 
> Prior to the Version 10 upgrade I would be given a signing request, which I would confirm. Then I would be given a transaction to confirm to stake the xNode tokens.
> 
> After upgrading to Metamask 10.0.1 the signature request does not work. Metamask starts to show the pop-up for the signature, then almost immediately closes the pop-up.
> 
> **Steps to reproduce (REQUIRED)**
> Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:
> 
> 1. Go to https://app.dappnode.io/  -- you must already have an account there with some xNODE tokens
> 2. Click on "Stake xNODE Tokens"
> 3. Type in the number of tokens you want to stake, then click "Deposit xNODE Tokens"
> 4. The Metamask pop-up appears for a moment, but then disappears again without showing anything.
> 
> **Expected behavior**
> I was supposed to get a signature request, followed by a transaction to approve
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Browser details (please complete the following information):**
> 
> * OS: Windows 10
> * Hardware Wallet: None
> * Browser: Firefox Browser 91.0 (64-bit)
> * MetaMask Version: 10.0.1
> 
> **Additional context (Error Messages, etc.)**
> Other users have confirmed the same problem
> 
> Rolling back to an earlier version of Metamask fixes the problem.

The problem is that xDai's chainID is 100 but chainID that is tranferred to the system is 256. Maybe I think the issue is belong to Node system because I can still harvest and claim rewards on xDai chain. Yesterday I also had the same problem as you.

I had deposited xNode on xDai chain succesfully before yesterday and I didn't upgrade Metamask at that time.

Someone recommends that the issue can be resolved after reinstalling Metamask with the old stable version like v9.8.4, but  it's so inconvenient for users to roll back Metamask and add lot of tokens on many chains again.

Plz help us to resolve this issue as soon as possible. Thank you very much!

**Comment by aminlatifi** [comment]
We have the same issue in signing permit message on Kovan
```
Provided chainId "66" must match the active chainId "42"
```
Network Id is 42 (decimal) but metamask assumes it's a hex number

**Comment by adonesky1** [comment]
@aminlatifi and @marcovan123 could you pull down this branch: https://github.com/MetaMask/metamask-extension/tree/revert-signtypeddata-validation and test if the issue is still happening for you?
