### ISSUE TITLE
Can’t sync MetaMask mobile account with browser

### ISSUE THREAD

**Issue by hugos** [MetaMask/metamask-extension#11840]
**Bug description**
When it comes to sync my mobile account with the browser it simply does not show my one and only account 1.

Even after typing the seed and password when I log in it gives me a complete different account, which apparently there's even a "bug bounty" for but every time I mention this on the forums I'm always ignored.

This bug has been mentioned by many and still has not been fix.

**Steps to reproduce**
Steps to reproduce this behavior: 

1. Create a mobile account first
2. Install MetaMask on your computer
3. Login to your account on the computer and you will see that your tokens are not there as it's not the same account, it will even have a different public address.

**Expected behavior**
The expected behaviour is to obviously have my accounts synced when I login and not show just a random account with none of my money there.

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit)
 - MetaMask Version: [e.g. 5.0.2]

**Comment by kevinghim** [comment]
This is not a bug but a feature request. Please share your idea here: https://community.metamask.io/c/feature-requests-ideas/13
