### ISSUE TITLE
Swap Router deducted tokens and never returned (on BEP20)

### ISSUE THREAD

**Issue by conradkwu** [MetaMask/metamask-extension#11843]
**Bug description**
Tokens swapped were deducted but never returned using Metamask Swap Router

Original transaction on Metamask Swap Router:
[bscscan.com/tx/0xaf5dc370ef4022026f35c6fffb293551a9370885e574aa1e876a1c9cf67d9848
](url)
Bscscan registered the transaction successfully and showed the tokens (acsBNB) were deducted, however as of today (10 days after the transaction), it was converted to some ACSI 5 days ago in an intermediate wallet address and still yet to convert to BNB or returned anything back to my original wallet.

Intermediate wallet address where tokens being held (not my wallet):
[bscscan.com/address/0xebb5e619fb9df1e25259c5482712b1c6c44e7e77
](url)

In other words, the tokens swapped are now gone missing and I have lost all for now. I understand acsBNB was not publicly traded but if so Swap should not have given me a quote in the first place? Or if it was eventually unsuccessful, Swap Router should just returned the original tokens (or any intermediate tokens) to me instead of holding them on its own? 

**Steps to reproduce**
Clicked Metamask Swap button (pop up dialog view)
Confirmed and agreed to the gas fees and expected receiving value
Received quotes (including Metamask fee) from the dialog
Confirmed to convert

**Expected behavior**
Receive the converted tokens if successful; returned the original tokens minus the fee if it unsuccessful

**Browser details (please complete the following information):**
Brave Release v1.27.108
Metamask Chrome Extenstion  9.8.4
Windows 10 Pro 21H1 19043.1165

Any insights and help are greatly appreciated.

**Comment by kevinghim** [comment]
Please file a support ticket on https://metamask.zendesk.com/hc/en-us/requests/new
