### ISSUE TITLE
Seed not searched upon security recovery phrase recovery

### ISSUE THREAD

**Issue by Velua** [MetaMask/metamask-extension#11842]
**Describe the bug**
When entering my Secret recovery phrase, only one of several addresses are imported from the phrase 

**Steps to reproduce (REQUIRED)**

1. Backup Secret Recovery phrase
2. Uninstall MetaMask (Chrome extension)
3. Re-install entering Secret Recovery phrase

**Expected behavior**
Instead of only one account/address showing up, I expected several as I have several accounts with ETH balances and TX history. 
I've been able to get around this by creating new accounts on MetaMask which eventually find them.

**Comment by kevinghim** [comment]
This is a good feature request. Please submitted it here: https://community.metamask.io/c/feature-requests-ideas/13
