### ISSUE TITLE
MetaMask says connected to Ethereum Mainnet but I get an error stating otherwise when I try to select it

### ISSUE THREAD

**Issue by zen8master** [MetaMask/metamask-extension#11841]
MetaMask says connected to Ethereum Mainnet but I get an error stating otherwise when I try to select it from the "connect wallet"
in the ethermine dashboard

Error Message:
Wrong Network Version
Open MetaMask and Switch to the Ethereum Mainnet Network in order to proceed.

and it once had coinbase wallet in it (scanned the coinbase image) but cant find it either

**Comment by kevinghim** [comment]
Please file a ticket on MetaMask Support: https://metamask.zendesk.com/hc/en-us/requests/new
