### ISSUE TITLE
Increase warning saliency on wallet sync screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#11861]
Phishers are now asking users to share their extension sync QR code, since it provides a less severe warning than our "secret recovery phrase reveal" screen.

Story (threading broken):
- https://twitter.com/Ape_NFTs/status/1427704710396620803
- https://twitter.com/Ape_NFTs/status/1427705408550998024?s=20
- https://twitter.com/Ape_NFTs/status/1427705527669346316?s=20
- https://twitter.com/Ape_NFTs/status/1427705883933425664?s=20
- https://twitter.com/Ape_NFTs/status/1427706077332873220?s=20
- https://twitter.com/Ape_NFTs/status/1427706478421544969?s=20
- https://twitter.com/Ape_NFTs/status/1427706755270815755?s=20

This is a good sign! It means phishers are finding it more difficult to get secret recovery phrases!

This also means we have inadequate text warnings on the QR sync screen.

![E9A-hL_VgAEqsKS](https://user-images.githubusercontent.com/542863/129788615-e847f253-41fe-4296-89f7-b673343f8ecf.png)
![E9A-iSSVEAApt4y](https://user-images.githubusercontent.com/542863/129788617-4bafa25f-6f7a-4159-9caf-e07049f086e5.png)

Some improvement ideas:
- On the "Sync with mobile" screen, the red text could say "Showing this code will allow migrating all of your accounts. Support staff will never ask for this, but phishers might."
- Saying "make sure nobody else is looking" on the screen that is sensitive is _too late_. Any warning like that should also be on the screen before.

**Comment by holantonela** [comment]
I really like the idea of having a pre-screen to detect shoulder surfing, but it does not solve the attempt of sharing the QR but some internet random. On the other hand, it can raise the awareness of which information the QR is decoding.

The PR seems to go with the first option. What if we use this opportunity to let users know what is going on? We can be explicit while informative. Also, we can reinforce the narrative of keeping the secret recovery phrase safe.

Something like: "`This QR contains your Secret Recovery Phrase. Anyone with access can steal all your accounts. Don't share.`"

Less patronizing option: "`This QR contains your Secret Recovery Phrase. Anyone with access can steal all your accounts. Share with someone you trust.`"

**Comment by danfinlay** [comment]
I addressed this [in another comment](https://github.com/MetaMask/metamask-extension/pull/11862#issuecomment-900591167). The QR code does not have the secret recovery phrase, it has a one-time session name and an encryption key that will be used to broadcast your secret recovery phrase to the other party.

Do you think it's worth conveying those technical details, and not just the basic "don't share"? Is that too patronizing? I'm afraid that if we get too technical, most users will skim and miss the important thing, which is "don't share!".

If I were designing this from scratch, I would not allow the QR code to freely "take" the accounts, ideally the QR would allow the recipient to *request* the account info, showing a final confirmation to the sender before proceeding. I'd love to take that more complete approach as a longer-term fix.

**Comment by holantonela** [comment]
Oh, I see. Also, it seems like the warning message will go here:` extension://home.html#mobile-sync`

I'm not sure if the current content style is less patronizing. For example, what lives [here](extension://home.html#seed) is a huge warning and _don't_.

`Support staff will never request this, but phishers would` itches me a little bit, it reduces the entire problem to one scenario.  

That said, "`Proceeding will show a code that allows exporting all of your accounts.`" seems appropriate to reduce complexity, and we can include "`Don't share.`" to match with other messaging.

> If I were designing this from scratch, I would not allow the QR code to freely "take" the accounts, ideally the QR would allow the recipient to request the account info, showing a final confirmation to the sender before proceeding. I'd love to take that more complete approach as a longer-term fix.

It's a good idea. In an interaction between devices, it makes quite sense. Not sure if solves the origin problem.

**Comment by danfinlay** [comment]
Good point, it's not all about phishing. I will replace the phishing part with a simpler "Don't share".

**Comment by ryanml** [comment]
Closed via: https://github.com/MetaMask/metamask-extension/pull/11862 - will be a part of the `10.0.2` release

**Comment by kevinghim** [comment]
Related to #11925
