### ISSUE TITLE
Remove the animations

### ISSUE THREAD

**Issue by lookfirst** [MetaMask/metamask-extension#11877]
**Describe the bug**
v10 added a number of loading animations where the form that I'm interacting with kind of 'pulses' before one can enter data. 

Remove the animations.

The pulsing is weird. It makes users wait before interacting with things. They also happen at weird times and even in the middle of entering data into a form. It isn't clear *why* they happen. Maybe something is loading?

If you want to show that something is loading, use a spinner. If you want the user to wait before entering data, disable the field. But don't do it while someone is typing or interacting with the form.

The less you make the user wait, the better. As someone who submits tens-hundreds of transactions a day, it is super annoying to have to be blocked on waiting for the interface to update before interacting with it. On a slow connection, this is only magnified even more.

**Steps to reproduce (REQUIRED)**
1. Use a site to create a new transaction.
2. Wait for dialog to appear... it pulses.
3. Edit the gas.
4. Things start to pulse again.

**Expected behavior**
If this is done so that gas estimation can be done more clearly, do that part as a separate process. For example, I enter in a new gas value and there is the same field as text that spins and updates. It doesn't cause the whole form to pulse. In other words, the form is static and the value of the form displayed elsewhere updates.

**Browser details (please complete the following information):**
 - OS: All
 - Hardware Wallet: None
 - Browser: All
 - MetaMask Version: 10

**Comment by lookfirst** [comment]
Related, but not enough removal imho. #11852

**Comment by kevinghim** [comment]
This should be improved on v10.0.2. The user can now click the edit button while the gas estimation update.

**Comment by lookfirst** [comment]
@kevinghim 
![2021-09-04 14-16-09](https://user-images.githubusercontent.com/85355/132108280-a091b5a4-f573-4a55-b4ef-d66bf1947390.png)
