### ISSUE TITLE
"Reccomended" UI not showing up on swaps

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#11882]
On edit gas screen, "recommended" UI not showing up on Swaps.
<img width="305" alt="Screen Shot 2021-08-13 at 9 10 20 AM" src="https://user-images.githubusercontent.com/6951929/129984596-7f4f1148-6137-445a-a06a-eb61c715bef1.png">

**Comment by jpuri** [comment]
Seems that this is no longer and issue.

**Comment by kevinghim** [comment]
This was fixed.
