### ISSUE TITLE
Error Ledger transaction EIP-1559

### ISSUE THREAD

**Issue by arintrongs** [MetaMask/metamask-extension#11891]
**Describe the bug**
I got the following error when submitting the transaction on ETH mainnet using Ledger account. (Hot wallet works normally)
`Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559`

The dApp site is using web3 version 1.5.2

**Steps to reproduce (REQUIRED)**
1. Choose ledger account
2. Send some transaction

**Screenshots**
<img width="605" alt="Screen Shot 2564-08-19 at 14 47 16" src="https://user-images.githubusercontent.com/12136171/130029245-4e15d822-a157-4cd6-bba6-0c92a6daecca.png">

**Browser details (please complete the following information):**
 - OS: OSX
 - Hardware Wallet: Ledger Nano S Firmware Version 2.0.0, Ethereum App version 1.9.2
 - Browser: Version 92.0.4515.159 (Official Build) (x86_64)
 - MetaMask Version: 10.0.2
 - web3 version : 1.5.2

**Comment by kevinghim** [comment]
We are currently working on hardware wallet support for EIP-1559. The support for Ledger will be coming in the next few releases.

In the meantime, you can successfully transact with your MetaMask extension or mobile account, or Ledger with extension v9.8.4.

**Comment by roadbuilder** [comment]
Brave browser still has the older built-in metamask that works with EIP-1559, as of right now they haven't updated yet

**Comment by BarBozz** [comment]
> We are currently working on hardware wallet support for EIP-1559. The support for Ledger will be coming in the next few releases.
> 
> In the meantime, you can successfully transact with your MetaMask extension or mobile account, or Ledger with extension v9.8.4.


Hi, 
i am experiencing the same error.

The ledger part is officially out since app version 1.9.2 and merged  https://github.com/LedgerHQ/app-ethereum/pull/157

**Comment by roadbuilder** [comment]
Same EIP-1559 error occurring with latest Trezor and Chrome browser.  Using Trezor with current Brave browser works because it seems to have the older Metamask

**Comment by stephen101** [comment]
Any ETA on this? We have a number of users on our platform that need to repay loans that can't because of this issue

**Comment by TalkCryptoToMeBaby** [comment]
Having this issue (I think) on Polygon network. ledger-mm bridge inexplicably stopped working (again) last night.

**Comment by alexreyes** [comment]
An ETA would be great. Also dealing with this issue at the moment.

**Comment by countcoby** [comment]
This is really ruining issue. People with hardware wallets can't use metamask with pure web3js implementations!

**Comment by otoroto** [comment]
> As a workaround, I used MEW via MetaMask + Ledger S, since MEW still sends legacy transactions (type 0)

could you explain better how you work with me, Metamask and ledger together?  I would be very grateful

**Comment by TalkCryptoToMeBaby** [comment]
I was getting this the "internal JSON-RPC error", I uninstalled and reinstalled MM to the latest version at the time (10.0.2) and was having issues again where the bridge would not open in ledger live so I could not interact with hardware accounts with MM. 

Turns out, after reinstall (and importing accounts using seed phrases) I forgot to re-enable "Use Ledger Live" option in advanced settings. Hit that switch and things are working again today. Dunno if that fixes the issue for others but it worked for me.

**Comment by artdgn** [comment]
Just wanted to add another workaround (if the bridge doesn't work for some reason) is that ledger live (desktop) supports WalletConnect for Ethereum (but not other EVM chains it seems).

**Comment by alexandresobolevski** [comment]
@kevinghim Any news on this? We (Zapper) had to turn off submitting EIP1559 gas parameters because any transaction to a hardware wallet connected through Metamask would fail with the above error. While it works when submitting to the hardware wallet directly.

> We are currently working on hardware wallet support for EIP-1559. The support for Ledger will be coming in the next few releases.

As a work around, is there is a way of know whether we're submitting to a Metamask hot wallet or a hardware wallet connected through Metamask?

**Comment by stephen101** [comment]
Also still experiencing this with our users (NFTfi), any word. Is there something we can do at a code level to work around? It's been nearly 20 days now with no response

**Comment by danjm** [comment]
This should be resolved in v10.1.0, which we are beginning to roll out today: https://github.com/MetaMask/metamask-extension/releases/tag/v10.1.0

**Comment by reneb71** [comment]
> This should be resolved in v10.1.0, which we are beginning to roll out today: https://github.com/MetaMask/metamask-extension/releases/tag/v10.1.0

Can confirm. It has been fixed in v10.1.0

**Comment by xnorly** [comment]
Well...I tried metamask 10.1 on chrome and brave, but after I clicked "Connect Hardware Wallet" I got the error
`We had trouble connecting to your ledger, try reviewing our hardware wallet connection guide and try again.`

**Comment by voldemarz** [comment]
After this fix can't trasnfer any token from Ledger HW wallets. Getting this https://github.com/MetaMask/metamask-extension/issues/10552
Details posted in the thread.

**Comment by alexandresobolevski** [comment]
@danjm It would be highly appreciated if we could get Trezor supported on EIP1559 as well https://github.com/MetaMask/metamask-extension/issues/12130

**Comment by Theybrooks** [comment]
It's November and Trezor users still have this problem. When will it be fixed for us?

**Comment by ibai93** [comment]
Just getting a bit dissapointed we are closing to December and still have this problem unsolved for Trezor. Is there any estimation for when this will be fixed?

**Comment by phutngo** [comment]
Another vote for fixing this ASAP please.

**Comment by tommycp3** [comment]
Yep another vote for fixing from me ASAP too, thanks :)
