### ISSUE TITLE
Receiving transaction payload with chainId set to 0

### ISSUE THREAD

**Issue by mortimr** [MetaMask/metamask-extension#11892]
**Describe the bug**
Since MM 10.0.2, the payload returned from Metamask is setting chainId to 0. In my setup (local mainnet fork with chainId set to 1), everything was working properly yesterday, but this change that probably occured in the last published version is triggering an error in `useDapp`, when the tool checks for the chainId.

**Steps to reproduce (REQUIRED)**
I'm not sure if the issue is happening on all network or what might be the reason behind it so I cannot provide a clear reproduction example.

**Expected behavior**
Chain ID is set to actual chain id.

**Screenshots**
![Screenshot 2021-08-19 at 10 42 43](https://user-images.githubusercontent.com/17824082/130037722-6862b329-98f1-4e1a-99a5-b88603b61ea0.png)

**Browser details (please complete the following information):**
 - OS: macOs
 - Hardware Wallet: none
 - Browser: Version 92.0.4515.159 (Official Build) (arm64)
 - MetaMask Version: 10.0.2

**Comment by mortimr** [comment]
Just tested versions `10.0.1` and `10.0.0` and the issue is there too. Version `9.8.4` works properly (sends back the proper chainId).

**Comment by vujevits** [comment]
getting the same error when using `rinkeby` in `useDapp`

**Comment by quantizations** [comment]
we are getting this same issue

**Comment by kennym** [comment]
Same issue after updating to v10.x.x - also tested in 10.0.1 and still breaks.

**Comment by mortimr** [comment]
In the meantime, here you can find a workaround ! https://github.com/EthWorks/useDApp/issues/289#issuecomment-901944570
