### ISSUE TITLE
SignTypedData error -- incorrect chainid

### ISSUE THREAD

**Issue by JTraversa** [MetaMask/metamask-extension#11894]
**Describe the bug**
When attempting to use signTypedData_v3 or v4, I am returned the error `MetaMask - RPC Error: Provided chainId "66" must match the active chainId "42"` 

(signed on Kovan(42), but reading chainId as OkEx Chain(66))

**Steps to reproduce**
Just attempt to sign a typed data object using signtypeddata
(https://swivel.exchange)

**Expected behavior**
The modal with the typed data pops up allowing me to sign the data.

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 92.0.4515.131
 - MetaMask Version: 10.0.2
 (did not happen pre 10.0.2)

**Other comments**
I've tested other deployments of ours which dont appear to have this issue. Perhaps it is an issue with ethers versioning (5.0.31)?

**Comment by JTraversa** [comment]
I've tried replicating outside of this app and haven't been able to.

We're rebuilding our app and releasing a new version next week, so this isn't necessarily a blocker for us as it isn't replicated in the new app. 

It is just definitely strange behavior, and after checking our signing methods, ethers, etc, its definitely a bug on the side of the metamask RPC.

**Comment by jknight** [comment]
I can reproduce this consistently on FF and Chrome. We are using ethers 5.4.4

**Comment by jknight** [comment]
Is this a duplicate of #11830 ?

**Comment by Pol-Lanski** [comment]
Same issue as https://github.com/MetaMask/metamask-extension/issues/11847

**Comment by jmagder** [comment]
I haven't been able to reproduce this but I have two team members who consistently reproduce this.

**Comment by jmagder** [comment]
I am able to reproduce this consistently.  The chainId is being treated as a hex number.  Even if I provide 01337. it gets interpreted as 0x1337.

**Comment by jmagder** [comment]
https://github.com/MetaMask/metamask-extension/pull/11900

**Comment by Gudahtt** [comment]
This should be fixed as of #11900, which will be included in the next release.
