### ISSUE TITLE
The method 'eth_feeHistory' does not exist / is not available. 

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#11905]
**Describe the bug**
The method 'eth_feeHistory' does not exist / is not available. 

**Steps to reproduce (REQUIRED)**

1. Go to any website
2. open developer console
3. execute the following

```js
await ethereum.request({method: "eth_feeHistory", params: [4, "latest", [25, 75]]});
```

**Expected behavior**
dapps should have access to the eth_feeHistory result

**Comment by danjm** [comment]
This will be addressed in v10.2.0: https://github.com/MetaMask/metamask-extension/pull/12185
