### ISSUE TITLE
Ledger + Meta bridge issue

### ISSUE THREAD

**Issue by thacryptokidd** [MetaMask/metamask-extension#11907]
When signing a 'typed message: hash' transaction hash prior to remove liquidity). Ledger bridge (ethereum bridge to) metamask automatically completes the bridge session and closes the websocket. Once doing so, it causes a transaction code error to remove the Liquidity tokens because the bridge is now closed and thus I can't remove my LP. I try manually opening the bridge after the fact, but the error in the transaction code prior to accepting on metamask still exists.

Please help!

**Browser details: Brave
 - OS: [Windows]
 - Hardware Wallet: Ledger Nano X Firmware version 1.3
 - Ledger live 2.32.2
 -  Metamask 10.02

**Comment by dpazdan** [comment]
Please note we will be deprecating the ledger live bridge and implementing webhid support. This will likely resolve your issue. In the meantime you can use MetaMask + Ledger with Firefox or Brave using our legacy method. Refer to: #11978, thanks!
