### ISSUE TITLE
Brave Browser + Ledger + Metamask: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE

### ISSUE THREAD

**Issue by mbrosparky100** [MetaMask/metamask-extension#11903]
Brave Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)

Following a recent update, my Ledger is no longer recognised when actioning a contract using a Ledger wallet on Metamask. It had worked seamlessly up until the update. This error is received: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE

It works fine on Firefox (91.0.1 64-bit), but no longer on Brave. Please investigate

**Comment by TalkCryptoToMeBaby** [comment]
I updated my mm extension to 10.0.2 and things started working again, then inexplicably started having the same issue last night. 

After confirming txn in mm, eth bridge in ledger live does not open so cannot sign using ledger device. 

incredibly annoying at best and liquidation causing at worst. I am not currently leveraged anywhere but imagine if I was and couldn't repay defi loans bc of this issue.

**Comment by fourteenminusone** [comment]
Same issue for me with the same configuration and versions of brave browser and metamask extension. Please investigate.

**Comment by darkwing** [comment]
Brave discontinued U2F support, as did Chrome.  If you re-toggle off and then on the Ledger Live setting, does the next transaction work as it should?

**Comment by jacobcantele** [comment]
Hi friend, we've launched a new Ledger integration in 10.5 based upon WebHID instead of the previous U2F and Ledger Live integrations. This issue should now be resolved!
