### ISSUE TITLE
Max Ammount is less than account balance

### ISSUE THREAD

**Issue by a35u** [MetaMask/metamask-extension#11908]
The max amount calculated is less than the account balance. This makes it impossible to empty an account. Even when you specify a gas limit and then go back and reselect the max amount to send it still uses the limit set with the previous gas estimation.

Max amount should be the total ETH balance.

**Comment by a35u** [comment]
![Balance](https://user-images.githubusercontent.com/84698319/130342070-2fef6348-e827-49d6-b6c4-5f5dc938f1bb.png)
![maxamount](https://user-images.githubusercontent.com/84698319/130342119-99774fc5-dd80-4a30-9c11-531a72835f0f.png)

**Comment by danjm** [comment]
Thanks @a35u

**Comment by Naografix** [comment]
Yup, really anoying, it's impossible to empty an account or to swap (uniswap) with high fees (for example when you click on MAX on Uniswap)
![image](https://user-images.githubusercontent.com/6979203/130515792-afe39c64-09a2-4945-974e-659016fb3650.png)

The old version did not have this problem
Is it possible to re-download it?

**Comment by danjm** [comment]
The max amount calculated leaves room for the max gas. We need to continue to do that, but one improvement we can make:

If the max gas is lower than what it was at the time that the transaction is created, than the amount submitted should increase.

Basically, on the confirmation screen, we need a max mode that sets the submitted amount to the balance - the max gas.
