### ISSUE TITLE
Attempt at adding FTM to etherium mainnet in MetaMask version 10.0.2 causes MetaMask to hang indefinitely

### ISSUE THREAD

**Issue by jakoblabs** [MetaMask/metamask-extension#11912]
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by dpazdan** [comment]
If it is crashing can you provide a screenshot of the error you are seeing?   Also provide any errors you see in your background logs, you can view those following steps here: https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-to-download-state-logs

**Comment by darkwing** [comment]
Closing as not enough detail and no follow up.
