### ISSUE TITLE
Kovan network Gas estimation fails

### ISSUE THREAD

**Issue by chaitanyapotti** [MetaMask/metamask-extension#11913]
**Describe the bug**
Gas estimation fails on kovan network

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:
Just try to initiate a transfer on kovan network

**Expected behavior**
Gas estimation to work with low, medium and high gas fees displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/1688380/130416020-bda29851-358a-4c12-851f-161035b97931.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 92.0.4515.159 (Official Build) (64-bit) (cohort: Stable)
 - MetaMask Version: 10.0.2

**Additional context (Error Messages, etc.)**
In the network tab for background.html, i see a 500 error for `suggestedGasFees`(https://gas-api.metaswap.codefi.network/networks/42/suggestedGasFees) endpoint with the following response:
```
{"error":"processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":90084,\\\"error\\\":{\\\"code\\\":-32602,\\\"message\\\":\\\"Invalid params: invalid type: integer `5`, expected a 0x-prefixed hex string with length between (0; 64].\\\"}}\", error={\"code\":-32602}, requestBody=\"{\\\"method\\\":\\\"eth_feeHistory\\\",\\\"params\\\":[5,\\\"latest\\\",[10,20,30]],\\\"id\\\":90084,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://kovan.infura.io/v3/9882544d7b8f441b8e5a6890b837f6e9\", code=SERVER_ERROR, version=web/5.4.0)"}
```

**Comment by bschorchit** [comment]
Closing as this has been fixed.
