### ISSUE TITLE
Balance hide

### ISSUE THREAD

**Issue by ryjm-glitch** [MetaMask/metamask-extension#11918]
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by ryjm-glitch** [comment]
I can’t see all my balance on BNB smartchain

**Comment by dpazdan** [comment]
It sounds like you will need to add custom tokens to your MetaMask.  Please submit a ticket to our support team at support.metamask.io, thanks!
