### ISSUE TITLE
Duplicate "Cancel" buttons in Metamask Extension Edit Screen Bring you Forward to Confirm Screen

### ISSUE THREAD

**Issue by AlexHerman1** [MetaMask/metamask-extension#11929]
**Describe the bug**
The two "cancel" buttons on Metamask extension "edit" screen do not cancel the transaction, they return you to the confirmation screen

**Steps to reproduce**

1. Go to Extension and enter a destination address and amount of funds to send
2. Click "next"
3. Click "edit"
4. Metamask returns to confirmation screen when clicking either "cancel" button

**Expected behavior**

Expect either "cancel" button to return you to Metamask home.  Recommend renaming one to "cancel edit" that is on the top right, and renaming bottom left button to "reject" to align it with the confirmation screen.

**Browser details (please complete the following information):**

 - OS: OS Big Sur 11.2.3
 - Browser: Chrome Version 92.0.4515.159 (Official Build) (arm64)
 - MetaMask Version: 10.0.2

**Comment by danjm** [comment]
Screen capture of current flow:


https://user-images.githubusercontent.com/7499938/132656460-46acfad4-8658-4975-b939-42ed0213cfa0.mp4

**Comment by danjm** [comment]
I agree with the above suggestion to rename the button in the top right to "Cancel Edit" (but only when editing a transaction) and rename the button in the bottom left to "Reject" (but only when editing a transaction)

**Comment by danjm** [comment]
The components for the send screen are all in the `ui/pages/send` directory

An example of code that applies certain copy, but only "when editing a transaction", can be seen in `ui/pages/send/send-header/send-header.component.js` (see line 32)
