### ISSUE TITLE
Error message state persists when password is incorrect

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#1192]
Will post a picture here. Reproduced by typing an incorrect password into the lock screen, or generating any error from either the lock screen or the first-time screen, and then visiting either settings, buy, lock again, QR code, forgotten password, import key. The only place it does NOT persist an error (correct behavior) is the send screen.

**Comment by linagee** [comment]
I've confirmed this is a bug.
Exact steps to replicate:
- Import Account
- Click "Import" on "Private Key" without entering anything
- Error in orange appears at the bottom: "Private key does not satisfy the curve requirements (ie. it is invalid)"
- Change the pulldown type to "JSON File"
- Error persists at the bottom

Expected: Error to clear when changing Import Type.

**Comment by linagee** [comment]
![screenshot_2017-03-17_19-10-55](https://cloud.githubusercontent.com/assets/636551/24067678/8a126830-0b45-11e7-85b1-0b2e3a067345.png)

**Comment by jctaillandier** [comment]
I saw this issue was closed but I have experienced the same !
