### ISSUE TITLE
Improve wording on Sync w/Mobile screen to better warn users.

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#11925]
**Describe the bug**
Users are getting tricked into screen sharing or copying their sync w/mobile QR code.   There is also a small typo in the existing warning.

Change the wording to something like:
Proceeding will display a secret QR code that allows access to your accounts.  Support staff will never ask you for it.
- Do not share it with anyone.
- Do not proceed if others are around.
- Do not proceed if you are in a screenshare session.
- Do not copy the QR code.

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/130802907-6c16b132-44be-4bf9-8a71-d15b16c0a0ca.png)

Also maybe move it from settings > advanced to settings > security & privacy.

Related to:
https://github.com/MetaMask/metamask-extension/pull/11862

**Comment by kevinghim** [comment]
Currently, the message the message below is shown at the same time the QR code is shown.
```⚠️ Proceeding will display a secret QR code that allows access to your accounts. Do not share it with anyone. Support staff will never ask your for it.```

The message above should be displayed before the QR code is shown.
