### ISSUE TITLE
Ropsten simple send gas limit was suggested at 20999

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#11934]
JakeH and I have each seen this.

Repro steps:
- On Ropsten, initiate a simple ether send from within the wallet.
- Click "edit" for gas params
- Notice "gas limit" has become `20999`, 1 less than the actual minimum!

Also, no warning is given explaining why these gas settings can't be saved.

**Comment by danjm** [comment]
This was almost definitely fixed by https://github.com/MetaMask/metamask-extension/pull/12279, and we have had no other reports of this since last august. Closing
