### ISSUE TITLE
Transfer smooth love potion ERC20 token from Metamask Trezor to Exchange results in error/failed transaction

### ISSUE THREAD

**Issue by mooglestiltzkin** [MetaMask/metamask-extension#11947]
Firstly i don't have a screenshot because i tried to advanced reset to see if that solved the issue but it didn't.

basically the situation is, Trezor is imported to metamask. So the SLP is residing in the Metamask Trezor wallet address.

Then click send, then send the slp to exchange.

Ok so the trezor is not yet plug in. So when first time errored, i thought maybe becauz i did not enter trezor beforehand and unlock it. I assumed i could do it after the fact.

So i tried again, but before i started, i unlock the trezor and also open up the trezor suite as well. Then tried again, but it didn't work. still error/failed transaction.

Tried a third time same. I had already incurred a heavy fee for failed transations. So at this point i just went to trezor suite and sent using that instead and it sent the SLP just fine. But this was by not using metamask to transfer the same SLP from the same address.....

So there is some sort of issue in metamask in regards to trezor which is causing this failure. Yes i was using chrome browser :/

marmaduke ungoogled
https://chromium.woolyss.com/

and if not mistaken i even tried the the normal one
https://www.google.com/chrome/

On the trezor i don't believe i got any prompt to sign anything. The metamask just simply errored and failed transaction and cost me a transaction fee.

**Comment by bleujj** [comment]
I will advise you to message trezorsuites.com for help. They helped me when I had issues with mine

**Comment by mooglestiltzkin** [comment]
funny cauz they said the fault is probly something to do with metamask. and here it's also the same story ^-^; ....

anyway like i said, since my recent test it seems to be working now.
