### ISSUE TITLE
Cancelled transaction also shows as received TX in activity 

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#11942]
**Describe the bug**
If a user has "Show incoming transactions" enabled, and then cancels a pending transaction, they will see two transactions in activity, the transaction replaced (shows cancelled) and a received tx.  This might be confusing to users as they do not realize our cancellation method is simply sending 0 ETH with higher gas and same nonce than the pending tx.

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/131014874-31315c29-4858-43b4-b162-7936b6227572.png)

**Comment by bschorchit** [comment]
Closing as this is not an issue anymore

**Comment by bschorchit** [comment]
This is still an issue
