### ISSUE TITLE
It always sign with ETH symbol, but my actual symbol is other coin.

### ISSUE THREAD

**Issue by jzhe886** [MetaMask/metamask-extension#11950]
It always sign with ETH symbol, but my actual symbol is other coin.

![image](https://user-images.githubusercontent.com/17755623/131110057-499d0bd2-472c-4e2d-b980-5deb4316fff8.png)

**Comment by imsys** [comment]
![Selection_231](https://user-images.githubusercontent.com/911254/133547752-5cfd4d6e-e050-4348-af4d-7a60ee5516ec.png)
Me too, I chose the Polygon Matic network, it should say 0.908191 MATIC, and not ETH.
This happens when I call web3.eth.personal.sign()

**Comment by bschorchit** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/12696
