### ISSUE TITLE
Increase friction to bypass estimated revert

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#11966]
Cross posted as https://github.com/MetaMask/metamask-mobile/issues/3077

[A twitter user comments](https://twitter.com/0xfoobar/status/1431805767003230209?s=21) that many new users are confused by having an estimated gas as well as a "transaction expected to fail" warning, because it implies that maybe this is what the transaction would cost to execute normally.

One possible improvement:
- If the transaction would revert/fail, hide the gas estimate info at first, as well as maybe disabling the confirm button.
- Need to still provide a way for pro users to override this. Something like "I want to submit this anyway", which would reveal the gas estimate and the confirm button.

This would need design, and then be a cross-product change.

Rating this as a sev2, but it's probably a high sev2, since it scares new users.

**Comment by kevinghim** [comment]
Possibly related to #10862

**Comment by danfinlay** [comment]
Related to and nicely paired with https://github.com/MetaMask/metamask-extension/issues/9419

**Comment by segun** [comment]
Design

![image](https://user-images.githubusercontent.com/44811/139866635-17b67dfb-bd75-49c9-8788-6cbf3e414515.png)
