### ISSUE TITLE
Transaction Underpriced when replacing pending transaction by nonce

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#11969]
When replacing by nonce, the only option seems to be to set custom nonce.
So, if I select a nonce that would replace another transaction in the Queue, the suggested gasPrice (max fee *and priority fee*) should be high enough that we don't get the Underpriced error.

**Comment by Claudio060320** [comment]
> When replacing by nonce, the only option seems to be to set custom nonce.
> So, if I select a nonce that would replace another transaction in the Queue, the suggested gasPrice (max fee _and priority fee_) should be high enough that we don't get the Underpriced error.

**Comment by kevinghim** [comment]
This should be fixed on v10.0.3 by #11936. Let us know if doesn't after you've updated to that version.
