### ISSUE TITLE
Cannot buy or remove a NFT from sale on Opensea using Metamask with Ledger Nano S in Chrome

### ISSUE THREAD

**Issue by Jcardshark** [MetaMask/metamask-extension#11977]
I recently set up a new metamask account using a ledger nano s. Everything works perfectly as far as I can tell except exactly when I want to buy a NFT on opensea, or remove a NFT from sale on opensea. I can transfer funds, place bids, lower prices, etc. 

When I try to buy or remove a NFT from sale, I get stuck in a "loop" where I am asked to verify the transaction details over and over. Normally I am shown a few screens then am asked to confirm the transaction. When I try to buy or remove a NFT from sale, I am shown the same sequence, but after I go through the few confirmations, I am told to continue confirming confirmations. I have gone through the process of "confirming" over 40 confirmations but am never shown the "Confirm and send" screen that indicates the final confirmation screen. 

Any help would be greatly appreciated. Thank you!

**Comment by dpazdan** [comment]
I think this is a support issue related to displaying all contract data (which then causes a timeout on the transaction).  Please contact Ledger or MetaMask support at support.metamask.io.  Thanks!
