### ISSUE TITLE
"Network Error" on firefox with ledger 10.0.3 and 10.0.2

### ISSUE THREAD

**Issue by artdgn** [MetaMask/metamask-extension#11973]
Transaction fails before ledger confirmation on multiple networks (Ethereum + BSC). Works on non-ledger accounts.

Error message in console:
```
Object { code: -32603, message: "Error: Error: Network Error", stack: "Error: Error: Error: Network Error" }
```

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to any dapp (uni / sushi), on firefox, connect with a ledger account.
2. Click on `swap`
3. Click confirm in metamask.
4. See error immediately.

**Browser details (please complete the following information):**
 - OS: linux
 - Hardware Wallet: ledger, latest firmware and Ethereum app
 - Browser: firefox
 - MetaMask Version: 10.0.3 & 10.0.2 (had the issue with 0.2, updated and the issue persisted)

**Comment by artdgn** [comment]
Same error when trying to load older MM versions (9.8)

**Comment by artdgn** [comment]
A temp workaround I found was to use the ledger live device bridge using brave/chrome. 

On linux, to start the bridge you need to follow this guide: https://www.gitmemory.com/issue/MetaMask/metamask-extension/11219/903916205.

**Comment by kevinghim** [comment]
Related to #11891. There will be a fix upcoming on the next release.

**Comment by dpazdan** [comment]
Please note we will be deprecating the ledger live bridge and implementing webhid support.  This will likely resolve your issue.  In the meantime continue to use your workaround.  Refer to: #11978, thanks!

**Comment by dpazdan** [comment]
Sorry I should be clearer, we might not deprecate but potentially offer multiple options.  Still to be determined, but progress is being made.  Thanks @artdgn

**Comment by mongstradamus** [comment]
> A temp workaround I found was to use the ledger live device bridge using brave/chrome.
> 
> On linux, to start the bridge you need to follow this guide: https://www.gitmemory.com/issue/MetaMask/metamask-extension/11219/903916205.

I have tried this fix as well but hasn't been successful with ledger live I have a new error that comes up "Failed error:ledger transport check timeout".

**Comment by artdgn** [comment]
@mongstradamus the two things I can think of is that the bridge is not open (does ledger live show a window saying "Ethereum bridge opened"?), or another possibility is that ledger live bridge mode is not enabled in metamask settings.

Also, if you're trying to use Ethereum (and not another EVM chain) ledger live supports WalletConnect, which is another possible workaround.

**Comment by mongstradamus** [comment]
> @mongstradamus the two things I can think of is that the bridge is not open (does ledger live show a window saying "Ethereum bridge opened"?), or another possibility is that ledger live bridge mode is not enabled in metamask settings.
> 
> Also, if you're trying to use Ethereum (and not another EVM chain) ledger live supports WalletConnect, which is another possible workaround.

The bridge opens up on ledger live, but it doesn't seem like its doing anything, it takes quite a long time for the transaction to finally fail. I have also made sure I have enabled in MM advanced settings to enable ledger live. I have even tried resetting my ledger and restoring from seed phrase.  

Another thing I noticed that was no issues sending crypto via metamask and ledger, it just seems like whenever transactions are involved it doesn't want to work.

**Comment by artdgn** [comment]
So sending works but contract calls don't? Of so maybe you need to enable
contract data in ethereum app settings on ledger itself,I think it's off by
default.

**Comment by mongstradamus** [comment]
I double and triple checked contract data is allowed. I am pretty stumped. I would probably be a little more upset if my aave loan was close to being liquidated luckily it is not. Am hoping eventually it will get fixed. I really hope all the coins tied up in defi will be recoverable.

**Comment by artdgn** [comment]
> Am hoping eventually it will get fixed. I really hope all the coins tied up in defi will be recoverable.

Metamask is just one way to send transactions using your ledger. There are more GUI based ways you can try that will allow you to send a transaction using your ledger. It might be a good idea to try those even if your transaction is not urgent right now, because another time it might be, and it is probably a good idea to have a backup way or two. 

1. Connect to the dApp (e.g. aave) with WalletConnect instead of with Metamask. Ledger live (for Ethereum accounts) supports that kind of connection already.
2. A more technically involved, but still mainly GUI based way is to use MyCrypto.com (https://app.mycrypto.com/) which is a GUI web based wallet that can connect to ledger not through Metamask. On that website you can interact with arbitrary contracts through `Tools / Interact with contracts`. To populate the data for the contract call you would need to get the contract address and call parameters, which you can get by using Metamask in the dApp (e.g. Aave). On the "confirm" dialog for the transaction in Metamask (which fails for you): you have the destination contract address in the top right corner), and the contract data on the 'DATA` tab: there is tells you the types and hex data for the

**Comment by mongstradamus** [comment]
I wanted to make a slight update to my MM and network error issues. I was able to figure it out for the most part it looked like it was an extension that was causing the problem , I think ad blocker possibly. I was able to do some transaction doing regular way, aka no ledger live, and was able to use ledger live as well with chrome and metamask. Hope this helps some people out there who were having issues.

**Comment by johansten** [comment]
> I wanted to make a slight update to my MM and network error issues. I was able to figure it out for the most part it looked like it was an extension that was causing the problem , I think ad blocker possibly. I was able to do some transaction doing regular way, aka no ledger live, and was able to use ledger live as well with chrome and metamask. Hope this helps some people out there who were having issues.

After five minutes of switching extensions on/off, I can confirm that at least for my case if I have uMatrix active, transactions get the network error, and never reach my Ledger.

Now.. uMatrix is not something I'm willing to keep off. Honestly, I'd rather switch wallet, as much as I love MM.

**Comment by Kashidaa** [comment]
> Now.. uMatrix is not something I'm willing to keep off. Honestly, I'd rather switch wallet, as much as I love MM.
> 
> (Edit: I've managed to get around it by adding a custom rule allowing https://cdn.live.ledger.com/plugins/ethereum.json to load)

I'm with you, I'd rather keep it on but I've got no idea how to add that custom rule, would you mind sharing how you did it?
Cheers!

**Comment by johansten** [comment]
> > Now.. uMatrix is not something I'm willing to keep off. Honestly, I'd rather switch wallet, as much as I love MM.
> > (Edit: I've managed to get around it by adding a custom rule allowing https://cdn.live.ledger.com/plugins/ethereum.json to load)
> 
> I'm with you, I'd rather keep it on but I've got no idea how to add that custom rule, would you mind sharing how you did it? Cheers!

1) Open "about:addons" in the browser, find uMatrix, open up the "..." menu, and select preferences.
2) Go to the "My rules" tab
3) On the right hand side, under "Temporary rules", add a line that says `metamask.github.io * * allow`, press "save", then "commit" to add as a permament rule

**Comment by cmroanirgo** [comment]
Can confirm that the work around cited by @johansten is valid. The ledger now responds to MetaMask. It'd be nice to be able to detect such things and prompt the user. Perhaps a test performed at the time the Ledger is being added to MetaMask?

As an aside, my Trezor *also* had similar issues, but because it pops up a secondary confirmation window, you can see uMatrix blocking the requests, so it was easier to figure out and add a rule.

I would suggest that the problem stems from MMask confirmation screen being an extension popup window. If it were a full blown tab, then users with uMatrix simply can't see that a critical aspect is being blocked. So, perhaps, an alternate solution would be to detect uMatrix users and warn them of potential issues...and provide remedies where possible.
