### ISSUE TITLE
"Continue at your own risk" button does not work

### ISSUE THREAD

**Issue by bxdym950** [MetaMask/metamask-extension#11971]
Dear manager,

Metamask protection appears when opening some sites. I was taking the risk. I can't access the site even though I took this risk for a week. What should I do. I am waiting for your help, please

![Metamask](https://user-images.githubusercontent.com/55433635/130316751-e6b00ce1-a7a3-4e5b-ac57-312f8eb1986b.jpg)

**Comment by Gudahtt** [comment]
This is a bug in the extension, so I have transferred this issue to the MetaMask extension repository. I have also improved the title.

**Comment by ryanml** [comment]
Note: This is due to the use of a factored build for the phishing detection assets, so we are getting a `phishing-detect-0.js` outputted in `dist/`, when just `phishing-detect.js` is expected per: https://github.com/MetaMask/metamask-extension/blob/develop/app/phishing.html#L8 - fix inbound. cc: @kumavis

**Comment by bxdym950** [comment]
Dear Sir,Thank you for the information you provided. I can easily log in from Metamask. However, you continue to be unable to access protected sites. Please I need help on what to do.


Bediî Menteş

Şemsettin Günaltay Cd.

Şakacı sk. 61/14 Erenköy

Kadıköy-ISTANBUL

***@***.***

05352944062

 

    31 Ağustos 2021 Salı 06:59:03 GMT+3 tarihinde, kumavis ***@***.***>şunu yazdı:  
 
 


Closed #11971 via #11972.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
