### ISSUE TITLE
Metamask - Gas Limit

### ISSUE THREAD

**Issue by iamsepia** [MetaMask/metamask-extension#11981]
Hola,

Hoy intentaba comprar por primera vez un token (Rubic) en Metamask. Problema? he visto muchos vídeos de youtube que explicaban cómo hacerlo y bla bla bla. Pero intento hacer una transacción, primero he probado de 300€, y en las opciones de gas limit me sale super alta (veo que en usuario de youtube es de 21000) y por lo tanto, cualquier transacción me sale por una burrada y no me deja bajarlo.

Disculpad soy nuevo en esto, espero que no haya infringido ninguna norma, un saludo os dejo las capturas.
![Csaptura](https://user-images.githubusercontent.com/89878292/131582981-e1671474-3c22-4ee0-ac5f-e53c9752627c.PNG)
![Casptura](https://user-images.githubusercontent.com/89878292/131582983-7bd3d60e-c4d9-41ad-8d72-0b5a9d175f50.PNG)

**Comment by bschorchit** [comment]
Please reach out to the support link within the MetaMask app so the team can help you on this.
