### ISSUE TITLE
Configuration should be per-domain

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#12]
There are some features that are currently plugin-wide, that should actually be configurable on a site-by-site basis.

Please add examples here so we can catch them under this issue:
- [ ] Current RPC
- [ ] Currently visible account

**Comment by flyswatter** [comment]
This might be more interestingly solved by a method for dapps to declare the network they prefer (which is complicated by the ETC fork).  We need to discuss that at some point.

**Comment by flyswatter** [comment]
I think this is blocked by #328, and we can discuss it after that's resolved.

**Comment by asymmetric** [comment]
I stumbled upon this issue while [reading this article](https://blog.hellobloom.io/using-an-in-browser-ethereum-wallet-heres-some-things-you-should-know-e01304b977e3).

Can the issue be worked on, or is it still blocked?

**Comment by danfinlay** [comment]
The important issue addressing concerns like that article is #714.

It's currently under progress, but we are working out a bit of our UX of how to address it (you can see where we're at there).

**Comment by bdresser** [comment]
Addressed in #714 and assorted issues
