### ISSUE TITLE
Alert users of necessary steps required prior to confirming tx with Ledger Live bridge

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#12014]
**Describe the bug**
The user of a ledger device on chrome must have everything open and ready to go prior to clicking confirm on MM otherwise it is prone to fail to send the approval request to the hardware device.

**Improvement request**
Add information on the confirmation screen until further improvements or options are made (webhid, etc.)

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/132055893-5a8e3c1a-a3eb-446a-bc39-acd78fa894d1.png)

**Comment by danfinlay** [comment]
"Plug in" should be two words :)

Otherwise great way to hold us over til a Ledger transport upgrade.

**Comment by dpazdan** [comment]
Prior to clicking confirm:
- Enable Use Ledger Live under Settings > Advanced
- Open and unlock Ledger Live App
- Plug in your Ledger Device and select the Ethereum app
