### ISSUE TITLE
Importing account on chrome extension with private key string parsing error

### ISSUE THREAD

**Issue by Snag9311** [MetaMask/metamask-extension#12015]
I created multiple accounts in a PC and tried to import those to another PC chrome extension.
Tried "Import accounts" with private keys and following error message appears:

"
Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given:
"

https://ethereum.stackexchange.com/questions/80205/cannot-convert-string-to-buffer-tobuffer-only-supports-0x-prefixed-hex-strings
this might help or idk.

![20210904_190353](https://user-images.githubusercontent.com/52437923/132090692-222d021c-8eb6-448c-99db-22eac998391e.png)

**Comment by AlexHerman1** [comment]
@bschorchit  we have pretty consistent reports of this, it is documented as "mm_bug_29". 

Steps to reproduce:
1. Navigate to "import account" menu/flow
2. Enter any string that is not a private key
3. Receive this return

Suggestion:
Simple Error language change such as "Im sorry, that wasn't the format we were expecting for an account private key. You can find more information about private keys here<link> (alternatively, suggest 64 chars starting with "0x").
