### ISSUE TITLE
wallet_watchAsset called multiple times shows a popup of all assets, but only adds the first one

### ISSUE THREAD

**Issue by gndelia** [MetaMask/metamask-extension#12024]
**Describe the bug**
Calling `wallet_watchAsset` multiple times (almost one after the another) shows the "Add suggested token" popup in Metamask with all the suggested assets (which is ok), but after the user approves the modal, only the first one is added to the wallet. All of the rest are ignored.

**Steps to reproduce (REQUIRED)**

Just call 

```
ethereum
    .request({
      method: 'wallet_watchAsset',
      params: {
        type: 'ERC20',
        options: { address, symbol, decimals, image }
      }
    })
```

multiple times one after the other. The popup will show all the assets, but will only add the first one upon user accepting it.

Here's a [fiddle](https://jsfiddle.net/q4uxma2L/) to reproduce it (you need to be connected first with Metamask) 

**Expected behavior**
All the assets should be added.

**Screenshots**
Here's a video using that fiddle with my local fork reproducing the problem

https://user-images.githubusercontent.com/352474/132253809-65d56f3a-d708-450a-a6c4-939e140a38f5.mov

Here VSP token is suggested to the user together with Link, but it is not added.

**Browser details (please complete the following information):**
 - OS: macOS Big Sur 11.5.2
 - Browser: Brave 1.28.106
 - MetaMask Version: 10.0.3

**Additional context (Error Messages, etc.)**
N/A

**Comment by danjm** [comment]
This was resolved with https://github.com/MetaMask/metamask-extension/pull/11552 and will be fixed in v10.2.0
