### ISSUE TITLE
Add padding to footer of custom network form when opened in popup

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12035]
If I open MetaMask in the popup view, and open the custom network form, there is no padding at the bottom. Padding should be added.

![Screenshot from 2021-09-08 07-05-08](https://user-images.githubusercontent.com/7499938/132485972-6d188446-3868-4807-b076-d34f36446e79.png)

To see this view:

https://user-images.githubusercontent.com/7499938/132486128-ecb04b53-1fb9-4f80-bb65-03320cfb02f4.mp4

**Comment by jpuri** [comment]
The issue has been fixed by PR https://github.com/MetaMask/metamask-extension/pull/12039
