### ISSUE TITLE
Transaction with `?` gasprice after failed bump, cannot modify any more

### ISSUE THREAD

**Issue by karalabe** [MetaMask/metamask-extension#12051]
After submitting a transaction with a certain gas price, Metamask offers the user the possibility to speed it up via increasing the gas price. The new gas price represents not just the 10% bump needed, but also tries to hone in on current network conditions via the basefee. This can however be overridden by the user. 

Yesterday while the basefee was swinging wildly I was trying to speed up a transaction by just a bit (10%, not the new basefee) so I manually edited the gas price of the proposed speedup tx. I "failed" at that, because I set it to 9.x%, getting the transaction rejected with "replacement underpriced". That would be fine, however now the pending transaction in metamask appears with a  base fee and priority fee of `?`, and there's no more speedup button, so I can't fix my error.

I'm unsure if this is some deliberate protection mechanism, but there's no way to resubmit the transaction even manually now. Cancellation still works, but I don't want to cancel, just resubmit with manually entered as prices.

**Comment by danjm** [comment]
Thanks for reporting this @karalabe 

There are a few different issues here that we need to address.

1. We should prevent users from submitting speed up or cancel transactions with fees < 10% above the fees of the transaction that they are attempting to replace
2. It is probable that MetaMask is showing the replacement / speed up transaction in a pending state when it should be shown as in a failed state (this is a bug). It is also possible that we are showing the replacement / speed up transaction and not showing the original transaction (another bug). I believe that if we fix the former issue, the latter will also go away. We are working on this and aiming to get a fix out next week.

Are you able to see either the original transaction or the attempted speed up transaction via etherscan (or other blockchain explorer)?

**Comment by brad-decker** [comment]
I'm beginning to dig into this and will attempt to see if i can tie it into #12001 and #10686

**Comment by brad-decker** [comment]
![image](https://user-images.githubusercontent.com/4448075/133336759-58890127-1e24-42d6-8947-38e6d3aa2679.png)

Is this where you are seeing the `?` at @karalabe. I'm asking because we get these values from the *block* the transaction is included in. Regardless of this issue I think its incorrect to lump *block* base fee into the same definition list as transaction fees @danjm @jakehaugen for this reason. We might consider a "block info" section. so that the distinction is evident.

**Comment by brad-decker** [comment]
Sorry, only the baseFee is block based, the priority fee is transaction based but is unknowable until we know the baseFee for the block.
