### ISSUE TITLE
Lose Tokens

### ISSUE THREAD

**Issue by FrancoGSL** [MetaMask/metamask-extension#12050]
I am in plants V undead, the token of the game is the pvu, I had accumulated in my wallet 6.75, I already made the claim in the game, now I do it to you, so you can investigate or see if it is a bug, and I can recover my coins in the game  mi Acount is 0xE6d9097b9875033956E0f35e92F6aaDf214b26ab

**Comment by danjm** [comment]
Please submit a ticket with our customer support https://metamask.zendesk.com/hc/en-us/requests/new
