### ISSUE TITLE
Gas Estimate API (way) overcalled - from activity log

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#12067]
**Describe the bug**
I introduced a nasty bug in [11936](https://github.com/MetaMask/metamask-extension/pull/11936), where the gas estimation API is called for transaction-list-item in a users activity log, ultimately way overcalling this API and resulting in the service hitting its rate limits.
 - Need to refactor useCancelTransaction and useRetryTransaction to still get the benefits of improved gasEstimation for users attempting to speedup or cancel transactions, without calling the API when the users has only checked the activity log.

**Comment by danjm** [comment]
Looks like there already was a ticket for this https://github.com/MetaMask/metamask-extension/issues/12002

**Comment by adonesky1** [comment]
Closed with merge of https://github.com/MetaMask/metamask-extension/pull/12069
