### ISSUE TITLE
[BUG] When sending to a smart contract address, modifying original send amount will result in a failed transaction

### ISSUE THREAD

**Issue by moracha** [MetaMask/metamask-extension#12072]
When using the Metamask extension for Chrome to send to a smart contract address, the gas limit can be reset unknowingly by the user by modifying the original send amount to something different. This changes the gas limit from 37581 to 21000, thus resulting in a transaction failure "Warning! Error encountered during contract execution [Out of gas]" after submitting. Quite disappointing to lose $10 this way, so I thought I'd submit a bug report about it at least so it can be fixed. Ideally, there should be some sort of warning or indicator confirming the gas limit total matches what one would need for a contract interaction on the final send page before one hits the "Confirm" button.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Using MM extension, start a new send to a smart contract recipient address
2. Enter an amount to send and hit "Next"
3. Click the "< Edit" button at the top left
4. Modify the send amount and hit "Next"
5. You'll now see the gas limit has been reset to the default 21000, which is not enough gas for any contract interaction

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: N/A
 - Browser: Chrome Version 93.0.4577.63 (Official Build) (64-bit)
 - MetaMask Version: 10.0.3

**Comment by danjm** [comment]
Thank you for this bug report.

**Comment by EHaracic** [comment]
AC:

- Proper calculation of the Gas Limit filed on the amount change
- On manually enter the Gas Limit when the amount is less then calculated gas limit to shown the warning message on the Confirmation screen

**Comment by danjm** [comment]
@EHaracic Note that I left a suggestion in https://github.com/MetaMask/metamask-extension/pull/12437 that I think might solve the "Proper calculation of the Gas Limit filed on the amount change" part of this ticket

**Comment by EHaracic** [comment]
@danjm you probably thought the #12072?

**Comment by igorms-cons** [comment]
Note that the suggestion from https://github.com/MetaMask/metamask-extension/issues/12602 wont fix this issue.
Thx
