### ISSUE TITLE
mainnet tokens autopopulate add token form fields when on custom networks

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12087]
1. Be on a custom network
2. Copy the mainnet address of a popular erc20 token contract
3. Go to the add token flow, paste the erc20 contract address
4. The decimal and symbol fields will populate with mainnet data and the user will be able to add the token

Instead, we should show the user the same warnings we show when they paste a non-contract address.

This might be resolved with our upcoming token detection improvements.

**Comment by dragana8** [comment]
Did a research on this but waiting on more info from @danjm.

**Comment by danjm** [comment]
Acceptance criteria:

- display "This is a mainnet token" error under the input field, same UI as current "Personal address detected. Input the token contract address." or "Invalid Addres" errors
- but do not disable the form in the case of this error (so use a "warning")
- fields should not autopopulate
- use the mainnet token list (`import contractMap from '@metamask/contract-metadata';`) to make this check
