### ISSUE TITLE
Handle case where manual gas limit > block gas limit

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1209]
Right now if you manually set the gas limit to a value greater than the block gas limit, to the user, the metamask popup simply goes blank.  There is no logic for handling this error.

This could be a simple form-side validation.

**Comment by kumavis** [comment]
it would be nice if we could just pass this through the same logic we use on the backend

**Comment by flyswatter** [comment]
This was fixed with client side form validation.
