### ISSUE TITLE
Advanced gas controls no longer has any effect

### ISSUE THREAD

**Issue by oo-00** [MetaMask/metamask-extension#12094]
In Settings, there is an option to show gas controls on the main send/confirmation screen. This option still exists but no longer works.

Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to 'Settings'
2. Click on 'Advanced'
3. Scroll down to 'Advanced gas controls'
4. Set true
5. Attempt transactions
6. See error/no effect

**Expected behavior**
Gas controls should appear on the main screen as described by the setting description.

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome/Brave
 - MetaMask Version: 10.0.3

**Comment by sambacha** [comment]
10.1.0 is the latest version can you see if your issue persists?

**Comment by danjm** [comment]
This will be resolved by some upcoming designs

**Comment by bschorchit** [comment]
Closing as no longer relevant
