### ISSUE TITLE
EIP-1559 events tracking: Edit button and Edit screen audit/implementation

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#12107]
Refer to [Notion Success Metrics](https://www.notion.so/EIP-1559-v2-330b809eb95048f9a45fa70c9f9b9303#3dea90b44d7e444ebd74190a2095fa75) for details.

**Background**
1. Better default recommendations: Are our users using our recommended gas settings? Some directional insights can be provided by:
a. Are users clicking on 1) `Confirm` button or 2) clicking on `Reject` or `Edit` buttons on the Transaction Confirmation screen? If users are confirming without editing, we can assume that our gas estimates are acceptable for most transaction use cases.
![Screen Shot 2021-09-13 at 4 38 28 PM](https://user-images.githubusercontent.com/6951929/133350097-3e83c3fb-1fa3-4ecd-9117-740a5c5882c6.png)

b. If the users are editing their transactions, are they selecting the default recommendation based on the transaction type (1)? Or are they customizing (2) the gas inputs? What we want to track is the acceptance rate for the default recommendation for regular transactions and Swaps transactions.
![Screen Shot 2021-09-13 at 4 56 36 PM](https://user-images.githubusercontent.com/6951929/133350116-365231d8-a3d2-4792-b256-2ec0e58f2c71.png)

c. Gas estimation accuracy: What's the difference in the estimated default to the user's manually changed Max Priority fee, Max fee, and Total gas_fees (in gwei)?
- Log where the confirmation happens in transaction screen or advanced option screen.

**Audit**
Send/Swaps screen
1. Verify that the `Clicked on Edit Gas` is is correctly associated with `Edit` in 1a, and in Swaps `Edit` 
2. Verify that the `Confirm` button is triggering with the `Transaction Approved` event in the Send screen as well as the Swaps screen
3. Verify that the `Reject` button is triggering with the `Transaction Rejected` event

**Edit screen**
4. Verify that `Gas Fee Changed` is triggering when users change from the default Medium in Send and High in Swaps
5. Verify that when users change priority from the default above, we're capturing the associated `gas price`
6. Verify that `Clicked Advanced Options` is triggering when user are clicking on the Advanced Options drop down
7. What event is `Save` button is associated with?

**Bonus**
- Capture the breadcrumb steps the user takes from the `Edit` button to the `Save` button

**Comment by brad-decker** [comment]
@kevinghim -- hoping to help brainstorm here and just share my knowledge of how the events line up currently.

https://github.com/MetaMask/metamask-extension/blob/d28e108aa943b73d6eb7560963d59af8cf6856aa/app/scripts/controllers/transactions/index.js#L57-L63

These are the 5 events that are currently tracked for transactions. These are events that are tracked from the controller level. When a user clicks on 1 (confirm) or 2 (reject) these trigger the events in the background controller for transactions.

So all Transactions will end up in one of those stages. I think this is a brilliant candidate for using the fragment system, which would allow us to tie together events from the UI and the background controller. So here's my suggestion: 

1. When a user is shown a transaction confirmation, which we know they will when a transaction is added to the queue, we create a fragment that will either result in a Transaction Approved or a Transaction rejected event. This fragment can be created in the controller and then modified from the UI.
2. When the user is shown the confirmation screen we get the fragment, and we can then append data to the fragment. Including any gas clicks/modifications. 
3. When the user clicks either 1, or 2, we can complete the fragment in the controller.

This should open the door for appending data to an unapproved transaction event from anywhere that touches it in the UI or background.

---

The save button is associated with updating the draft transaction, which could either be discarded if the user rejects or committed and used if the user approves, so all of these data points would ultimately end up on either the Approved or Rejected events.

**Comment by brad-decker** [comment]
cc'ing @ryanml as he implemented a lot of the current events for transactions.

**Comment by jpuri** [comment]
More details here: https://www.notion.so/EIP-1559-v2-330b809eb95048f9a45fa70c9f9b9303#3dea90b44d7e444ebd74190a2095fa75
