### ISSUE TITLE
EIP-1559 events tracking: Advanced Options audit/implementation

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#12108]
Refer to [Notion Success Metrics](https://www.notion.so/EIP-1559-v2-330b809eb95048f9a45fa70c9f9b9303#3dea90b44d7e444ebd74190a2095fa75) for details.

**Background**
2. Preparing for edge cases: When users have to change gas inputs, what are the circumstances behind that, and how do we provide speed and flexibility for our users to perform that task?
a. For users that are manually changing the `max priority fee` and `max fee`, what are they changing it to? 

![Screen Shot 2021-09-13 at 5 11 23 PM](https://user-images.githubusercontent.com/6951929/133350405-11b81a27-1511-4bd1-a228-a4465da27426.png)

b. What is the difference between our recommended default `max priority fee`, `max fee`, and total `gas_fees`? 
c. What type of users are manually changing the gas inputs? Which dapps are they using?
d. For users that need their transactions to be included quickly, how long are the manually changed gas inputs taking? Particularly, we want to track users from NFT buying sites (or similar) and make sure their high `max fee` transactions are going through quickly.

**Audit**
1. Verify that changes to `max priority fee` and `max fee` are correctly captured
2. Capture the difference between the original gas estimation and the final `Transaction Finalized` `gas fee`
3. Can we capture how long users are waiting to get their transaction included?
4. Can we know what the final state of the transaction is - confirmed, dropped or failed?
5. Can we know how many users speed up or cancel transactions?

Bonus
- Can we find out what users are doing using breadcrumbs during pending transactions?

**Comment by brad-decker** [comment]
> Verify that changes to max priority fee and max fee are correctly captured
@jpuri is working on tracking initial/approved amounts (so what is suggested versus what a tx is approved with)

> Capture the difference between the original gas estimation and the final Transaction Finalized gas fee
We have in complete data but @jpuri is working on adding these values (estimate used and the actual values) to all transactions we can build reports going forward.

> Can we capture how long users are waiting to get their transaction included?
[Transaction Inclusion Time in seconds](https://mixpanel.com/s/3PA7nn)

> Can we know what the final state of the transaction is - confirmed, dropped or failed?
[Transaction Finalized Status](https://mixpanel.com/s/2ThlFo)

> Can we know how many users speed up or cancel transactions?
[Users that speed up/cancel](https://mixpanel.com/s/26Dl48)
