### ISSUE TITLE
Missing Firefox Version 10.1.0

### ISSUE THREAD

**Issue by kierancassel** [MetaMask/metamask-extension#12116]
The Firefox extension hasn't been updated since 10.0.3.
Where is 10.1.0? Chrome has had the updated version for over a week. Still waiting for ledger eip 1559 support this is ridiculous, the wait has been extreme.

**Comment by christopherbecker** [comment]
My chrome didn't auto update to version 10.1.0, I had to manually update using developer mode.

**Comment by kierancassel** [comment]
I'm hesitant to update manually because previously it wipes all settings resetting custom RPC, currency etc.
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn < 10.1.0 on chrome web store
https://addons.mozilla.org/en-GB/firefox/addon/ether-metamask/ < 10.0.3 (last updated 30 Aug) on firefox browser add-ons
