### ISSUE TITLE
Why my site is blocked by this extension with Ethereum Phishing Detection Waning? upfinity.xyz is not related to dfinity.org

### ISSUE THREAD

**Issue by AllCoinLab** [MetaMask/metamask-extension#12138]
my site, www.upfinity.xyz gets always blocked by this metamask extension.
the reason it says that 'this domain was blocked for it similarity with dfinity.org'
this site is nothing to do with that phishing site.
and 2 days have passed. we are having serious loss by this issue.
how can i make it not to block my site? please make it fixed.

thank you.

**Comment by dpazdan** [comment]
Not sure how to transfer this issue, it should go under: https://github.com/MetaMask/eth-phishing-detect/issues

**Comment by AllCoinLab** [comment]
> Not sure how to transfer this issue, it should go under: https://github.com/MetaMask/eth-phishing-detect/issues

i already did but they don't resolve any issues for many weeks..
check opened issues date.
so i am uploading here.

**Comment by AllCoinLab** [comment]
@dpazdan who should I contact to make this fixed then?

**Comment by AllCoinLab** [comment]
by refering other issue,
sending help to @davidwgrossman also. thank you.
