### ISSUE TITLE
Clicking a suggested address closes the popup

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1213]
This UX is only keyboard friendly right now.  I wonder if this is just a flaw with extension popups.  Seems like a serious Chrome flaw to me.

**Comment by flyswatter** [comment]
I submitted this bug to Chrome, along with the #1136 issue, since they're both "popup unexpectedly closing" issues.

**Comment by flyswatter** [comment]
Fun new idea from @kumavis:  Why not just pop up a popup when clicking the fox?

I know, we lose the cute popup-ish thing.  But we gain actual window stability.

**Comment by Zanibas** [comment]
Hey, by 'clicking a suggested address', do you mean that when I type like "addr" and then click on an address corresponding to "Address 1" from the send screen, the popup closes?

If this is the case, I do not experience this behavior.

**Comment by Zanibas** [comment]
Could be, yet again, browsers implementing behavior differently for an HTML component.

**Comment by flyswatter** [comment]
> Hey, by 'clicking a suggested address', do you mean that when I type like "addr" and then click on an address corresponding to "Address 1" from the send screen, the popup closes?

Yup. Sounds like this one may be mac exclusive.
