### ISSUE TITLE
Wrong Logo

### ISSUE THREAD

**Issue by cryptoartsy** [MetaMask/metamask-extension#12143]
Hello. I'm the head of communications and community at Truebit.io It came to our attention that you are supporting TRU (Truebit) on the MetaMask swap. You are currently displaying the wrong logo for our token (See it in etherscan: https://etherscan.io/token/0xf65b5c5104c4fafd4b709d9d60a185eae063276c)

I'm attaching a screenshot of the wrong logo, as well as the file for the right logo:

Wrong Logo Screenshot:
https://p27.zdusercontent.com/attachment/2313093/m0tQkpV8rtKsMtlU026gaBhjR?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..sLKCIP358MWjM6AHZwYjnQ.Qmp4AWdjTkwNNP5EWV2glS_YolOpyJL9VEhnHzDjoHhmFq-zkvtiEOMU9Bq_GwIUPcHuEfE8mf-6JwrkbUytoWgVmFJIwL3Pxpj5cwFA2UsmphA_FJxgQkgt1b6GcYSewXBEegvc4u1xH2yQW7UZHE_jjvTZO-E_rLu9JJj0oK3kAsmrJAyj5fh-thCxk5P-bafbUJ_Brh-XMCKMsLIGY97O2vJ3NsJAvh-RF3xKVUUuRMXqDJnTyIgWcRgcCcLi-HCjRdWdnUBhwjemTOdi-nSVJScFk-jeLm8pT6d_cPc.7PiyQq8Bn1jpbu6ewoyHJQ

Correct Logo for you to fix the problem:
https://p27.zdusercontent.com/attachment/2313093/Rj6lzITfaAGp7LwU1d7ANKyTE?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..rtdvS773nmdD-nbKZw_wIA.1HHK9RjNdANV2qdRNmDQCjM8LZeA9h9DG-CwU9A7PeQPYV8z0yy2Y2A1H56GaQv4mfHYJfrStUFgoIKNAC6yK7FAEpAwhowz3CX-eAbmvN1Hxlqg41VlZTdI4r2yrhHMooFFpgqL8c-yt-p6b2edlI4nfmL5YtPScQzzLomgR33uI5Hx_jxGI7ipHr7rURQm5j_OuALy1gnCyYPRevLiCNbYXKapYg5dBOJ5lGxC2CVe125q7ylLaP0G2-Sh7wYiCiasBODCYjHw1khBsQgcJ_fcyj55F3uVe3sB1OoL3Lg.uCbWRapNanx_ZFagztgVrw

I am already aware of the information in this link: https://docs.metamask.io/guide/registering-your-token.html#registering-tokens-with-users However, we did not submit nor register our token to be listed in your swap. This was a decision you made. We are also not interested at the moment in registering it ourselves.

Can you please then help me out with fixing the problem since it was Metamask who decided to list it? not Truebit?

Thanks for your consideration,
Jessica Angel

**Comment by Gudahtt** [comment]
Thanks for the report! It looks like the correct logo is now shown. The aggregator we get this image from must have fixed the problem.

**Comment by AdamPetroff** [comment]
@Gudahtt Hi, I have the same problem. I created the following token: https://arbiscan.io/token/0xf0a479C9c3378638EC603b8B6B0d75903902550B and when I add it to my metamask, it shows an incorrect image. I'm not really sure where it's pulling that image from. The image I would like to show is this: https://s2.coinmarketcap.com/static/img/coins/64x64/23665.png . 

Can You help me to fix this?
Thanks

**Comment by AdamPetroff** [comment]
also, the token doesn't show the token price in dollars even though the token is present on CoinGecko. Can you update it as well?
