### ISSUE TITLE
Broken support of Ledger wallets ~12h ago

### ISSUE THREAD

**Issue by countcoby** [MetaMask/metamask-extension#12145]
Hello guys!

**Describe the bug**
You're breaking ledger nano x wallets today.
24 hours ago all was great but in one moment metamask + ledger get RPC error `{code: -32603, message: 'Error: [object Object]'}` on all operations on all sites.

**Steps to reproduce (REQUIRED)**

For example
1. Go to https://mint.sadgirlsbar.io/
2. Click on 'Connect walled button' (with connected hardware ledger account)
3. Push 'mint' button. And try to push 'confirm' button. You've got following error:

`inpage.js:1 MetaMask - RPC Error: Error: [object Object] 
{code: -32603, message: 'Error: [object Object]'}
code: -32603
message: "Error: [object Object]"
[[Prototype]]: Object`

**Expected behavior**
Metamask pass transaction to ledger as it does a day ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/89049360/133796708-90f86dc4-9e4e-4c72-a18a-3b12cb5bdade.png)

**Browser details (please complete the following information):**
 - OS: All desktop OSes, all tested metamask versions 10.1.0, 10.0.3, 10.0.2
 - Hardware Wallet: LEDGER NANO X with latest firmware and latest version Ledger Live 
 - Browser: Latest Chrome
 - MetaMask Version: 10.1.0, 10.0.3, 10.0.2

**Comment by danjm** [comment]
Thanks @countcoby

You likely need to re-enable the contract data setting, even if you had it enabled before. Updating the firmware causes that setting to revert to off.

**Comment by yashutanna** [comment]
re-enabling the contract data setting in the ethereum ledger app on the ledger worked.  

Thanks @danjm. I was pulling my hair for a bit there

**Comment by yashutanna** [comment]
might be worth logging a better error here though? [object Object] is not too useful.

**Comment by countcoby** [comment]
@danjm @yashutanna thanks, guys! It works! But this must be enabled contract data AND debug mode. It's doesn't work otherwise. But why?

**Comment by Cryptome2** [comment]
Same issue. I can't send tokens between my own accounts in Metamask on Ethereum mainnet.  'Error: [object Object]'  re-enabling the 2 settings as suggested above doesn't work for me.  Chrome browser extension on W10.

**Comment by yashutanna** [comment]
@Cryptome2 are you using the ledger live bridge? 

As of the latest chrome version MetaMask uses a bridge to connect to the ledger device. 

I'm typing this on my phone so the exact details may be a bit fuzzy, but go to settings > advanced > use ledger live and enable on MetaMask. That will open up the ledger live app for you to open the bridge while you are transacting.

**Comment by Cryptome2** [comment]
same error when I enable ledger live in MM

**Comment by IvanBoutin** [comment]
I have the same problem with when I try to stake Matic tokens :
[](https://wallet.polygon.technology/staking)
I have the Contract Data et Debug mode activated, I still have the error.

I Have the last firmware  version et the last version of the Ethereum App on my Ledger Nano X
My Metamask version is 10.1.0 on W10

**Comment by jironghuang** [comment]
> enabled contract data

This doesn't work for me.

I will rollback to 9.8.4. in the meantime.

**Comment by danjm** [comment]
For everyone experiencing this issue: make sure you enable contract data _after_ you update firmware and the ethereum app.

If you are still experiencing a problem after doing that, please post the exact error message you see here. If there is no error message, please describe what you do see (does nothing happen? or do you see an infinite spinner? or anything else unusual?).

Also, sharing your browser and exact device type can help diagnose.

**Comment by krampus4570** [comment]
I'm having the same issue. The problem started this morning, and as far as I know nothing had changed since my last successful transactions a week ago. It started with the first transaction I tried today- a swap on Matcha. I went on to try Uni, Sushi, and a deposit into Aave. Transactions all fail after confirming in Metamask before anything shows up on the Ledger.

 I did end up updating to the latest Eth app on Ledger, and reenabled smart contract data and debug mode after I ran into problems, but that has not fixed anything for me.

Ledger Nano X firmware 1.2.4-5
Ethereum App 1.8.6 ( upgraded from 1.6.4? IIRC)
Windows 10
Firefox 92.0
Metamask 10.1.0

Not sure if any of this is helpful, but it's what I pulled from the log after an attempted Aave deposit:

> Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:970
> Removing intrinsics.Object.hasOwn sentry-install.js:8:36389
> Removing intrinsics.%StringPrototype%.at sentry-install.js:8:36389
> unreachable code after return statement ui-3.js:7:238924
> unreachable code after return statement ui-3.js:7:239648
> unreachable code after return statement ui-3.js:7:243336
> unreachable code after return statement ui-3.js:7:238924
> Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:2105:39
> Uncaught (in promise) Error: Invalid tab ID: 95 undefined
> Error: Please use $(ref:runtime.getURL). common-0.js:1
>     _showNotification moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:1
> Error in RPC response:
>  
> Object { id: 471444324, jsonrpc: "2.0", error: {…} }
> sentry-install.js:8:36389
>     h moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/sentry-install.js:8
>     default moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/background-0.js:1
>     _runReturnHandlers moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/background-0.js:1
>     _runReturnHandlers moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/background-0.js:1
>     _processRequest moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/background-0.js:1
>     _handle moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/background-0.js:1
>     handle moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/background-0.js:1
>     write moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/background-0.js:1
>     y moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:25
>     u moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:25
>     write moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:25
>     h moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     h moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:8
>     emit moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:8
>     E moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     _ moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     push moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     _write moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     y moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:25
>     u moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:25
>     write moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:25
>     h moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     h moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:8
>     emit moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:8
>     E moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     _ moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     push moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-1.js:1
>     _onMessage moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:1
>     <anonymous> moz-extension://61c2fb89-50fd-491d-970b-7789b795910b/common-0.js:1
>

**Comment by danjm** [comment]
@krampus4570 You will need to install v1.3.0 of the firmware, and v1.9.2 (or higher) of the Ethereum App. Once these are updated, turn on the contract data setting. Comment here if it still does not work after that.

**Comment by krampus4570** [comment]
Thanks! I assumed my Ledger Live app was giving me the latest firmware and Eth app, but for some reason it would not. A fresh install resolved that issue, and now I'm good to go.

**Comment by danjm** [comment]
@jironghuang Are you using the Nano S or Nano X?

**Comment by danjm** [comment]
@IvanBoutin What is the exact error that you see?

**Comment by danjm** [comment]
@Cryptome2 Can you confirm that you see "Error: [object Object]" _and_ you have the contract data setting on? And can you share the firmware version and version of the ledger ethereum app that you have?

**Comment by danjm** [comment]
> But why do I need to enable debug mode?

That is strange @countcoby... we need to investigate that further.

**Comment by jironghuang** [comment]
@danjm I'm using nano s

**Comment by IvanBoutin** [comment]
@danjm
Error: [object [Object]
![2021-09-17 22_50_36-Polygon Web Wallet v2](https://user-images.githubusercontent.com/29662024/133951087-6029af64-8438-425e-9c71-cf0602df5205.png)

**Comment by IvanBoutin** [comment]
@danjm 
Error: [object Object]
![image](https://user-images.githubusercontent.com/29662024/133951186-7bdb09b3-45ed-4530-95e8-62a1fe97d3be.png)

**Comment by danjm** [comment]
@IvanBoutin Perhaps try this:
- disconnect your ledger
- close your browser
- turn the smart contract data setting off then on again
- open your browser
- connect your ledger again to metamask
- try on matic again

**Comment by Cryptome2** [comment]
> @Cryptome2 Can you confirm that you see "Error: [object Object]" _and_ you have the contract data setting on? And can you share the firmware version and version of the ledger ethereum app that you have?

yes, the error is "Error: [object Object]"
system:
W10-Chrome
Ledger Live 2.24.0
Firmware ledger Nano X;  1.2.4-4 (ledger live says 'Firmware is up to date')
Ethereum app: 1.5.0 (don't see a higher version in the LL catalog)

**Comment by danjm** [comment]
@Cryptome2 For ledger nano x, you need firmware 1.3.0 and ethereum app at least 1.9.4

You might have to reinstall ledger live to be able to update to those version. After you update, turn on the smart contract data settings again

**Comment by krampus4570** [comment]
@Cryptome2 Definitely reinstall Ledger Live. When I ran into issues, I took it for granted that Ledger Live auto updated like so many other apps nowadays that I never thought about it not being up-to-date and not allowing me to get the other latest updates.

**Comment by countcoby** [comment]
> > But why do I need to enable debug mode?
> 
> That is strange @countcoby... we need to investigate that further.

Thank you! Without debug mode, it doesn't work on Ledger Nano X. But with debug mode, it works, but I need to check all of the fields. It's too annoying.

**Comment by Cryptome2** [comment]
> @Cryptome2 For ledger nano x, you need firmware 1.3.0 and ethereum app at least 1.9.4
> 
> You might have to reinstall ledger live to be able to update to those version. After you update, turn on the smart contract data settings again

reinstalling Ledger Live  solved all problems (=> new firmware, => new apps)

**Comment by Cryptome2** [comment]
> @Cryptome2 Definitely reinstall Ledger Live. When I ran into issues, I took it for granted that Ledger Live auto updated like so many other apps nowadays that I never thought about it not being up-to-date and not allowing me to get the other latest updates.

thanks, solved

**Comment by Cryptome2** [comment]
> > > But why do I need to enable debug mode?
> > 
> > 
> > That is strange @countcoby... we need to investigate that further.
> 
> Thank you! Without debug mode, it doesn't work on Ledger Nano X. But with debug mode, it works, but I need to check all of the fields. It's too annoying.

it works for me without debug mode (see above)

**Comment by dpazdan** [comment]
related to https://github.com/MetaMask/metamask-extension/issues/12117

**Comment by EroticKlaxon** [comment]
This continues to be a huge problem. 

I made the mistake of upgrading Ledger Live and upgrading my Ledger firmware (and re-enabling smart contract data) and the only effect is that the previous workaround of downgrading Metamask to 9.8.4 **now no longer works**.

Luckily I happen to have an older Ledger on hand that I have **not yet upgraded**, and so I can still transact with that... for now.

This is not the first time a Metamask upgrade has messed me up, but it is definitely the worst of the bunch. I've spent hours troubleshooting this for myself and in supporting at least half a dozen other Ledger+Metamask users across Discord and Telegram. The handful of GitHub issues don't accurately reflect how much anguish is out there.

I appreciate the work the Metamask team is doing, and I would gladly donate funds to folks in an official Metamask testing capacity to buy a Ledger so these releases can be tested against a Ledger _prior to shipping_.

As it stands, between the gamble these releases represent, and the forced-upgrade behavior of (at least) Chrome and Brave browser extensions, the Ledger+Metamask combo presents a risk that I feel might rival smart contract risk.

OS: OSX 11.6
Browsers: Latest Brave and Firefox.

**Comment by IvanBoutin** [comment]
> @IvanBoutin Perhaps try this:
> 
> * disconnect your ledger
> * close your browser
> * turn the smart contract data setting off then on again
> * open your browser
> * connect your ledger again to metamask
> * try on matic again
> 
> Also double check your versions:
> 
> > You will need to install v1.3.0 of the firmware, and v1.9.2 (or higher) of the Ethereum App. Once these are updated, turn on the contract data setting. Comment here if it still does not work after that.

Ok, i had to download the last ledger live version to get the last firmware/app version. It worked after that...What a shit show...

**Comment by EroticKlaxon** [comment]
This issue should not have been closed. 

#12176 fixes the superficial part of this bug, that the error display is unhelpful, but the larger issue here is that Metamask is breaking Ledger transactions.
