### ISSUE TITLE
Metamask 10.1.0 + Firefox + Ledger Nano S not working

### ISSUE THREAD

**Issue by bingen** [MetaMask/metamask-extension#12142]
**Describe the bug**
Metamask 10.1.0 + Firefox (on linux) + Ledger Nano S not working. Metamask pops up, but when I confirm the transaction, it never reaches the ledger and almost immediately an error appears. Looking at Firefox console, it says “Error code: -32603” but not more meaningful info to me.

**Steps to reproduce (REQUIRED)**
Try to send any transaction in any dapp using Firefox, Metamask 10.1.0 and Ledger Nano S

**Expected behavior**
Ledger device should get the transaction to sign.

**Browser details (please complete the following information):**
 - OS: KDE Neon 20.04
 - Hardware Wallet: Ledger Nano S Firmware version 2.0.0
 - Browser: Firefox Browser 92.0 (64-bit)]
 - MetaMask Version: 10.1.0

**Additional context (Error Messages, etc.)**
Manually switching back to 10.0.3 made it work again.

**Comment by danjm** [comment]
@bingen You may need to manually turn on the smart contract data setting on the device. When updating to version 2.0.0, this setting would have been reset on the ledger device.

You can see other users who had similar problems here: https://github.com/MetaMask/metamask-extension/issues/12117#issuecomment-920387862

And they were resolved after fully updating firmware _and then_ updating their smart contract data settings

**Comment by bingen** [comment]
Hi,

I already had smart contract data setting enabled on the device. I haven’t upgraded device firmware recently, while Metamask extension was auto-updated today. Besides, as I said in the issue, downgrading to Metamask previous version made it work, so I’m pretty sure the problem is not device settings.

Thanks.

**Comment by bingen** [comment]
Actually, in that same issue you can see other people having the same problem (and also with contract data enabled):
https://github.com/MetaMask/metamask-extension/issues/12117#issuecomment-921030510
https://github.com/MetaMask/metamask-extension/issues/12117#issuecomment-921159246

**Comment by dpazdan** [comment]
Question for you, does the transaction immediately fail when you click confirm on the MetaMask confirmation screen?

**Comment by trakout** [comment]
I'm going through the same thing (Linux), and it does appear to immediately fail (with no on-device prompt or confirmation).

**Comment by danjm** [comment]
@bingen Thank you for clarifying. And thanks for also reporting @trakout

Does it happen for all transactions? Or just a specific dapp? If just a specific dapp, it would be helpful to know what dapp you are interacting with. You can share that here or privately via a support ticket https://metamask.zendesk.com/hc/en-us/requests/new

**Comment by trakout** [comment]
@danjm I haven't tested to see if it's contract specific - this was attempting to transfer ETH.

**Comment by danjm** [comment]
thanks, that helps

**Comment by danjm** [comment]
For others investigating: ETH transfers are successful on Ledger Nano X + v1.9.2 of the ledger ethereum app + MetaMask v10.1.0 + Linux (ubuntu)

**Comment by danjm** [comment]
@bingen @trakout If you open ledger live, and go to the manager section, what version of the ethereum app do you see?

For example, I see:

![Screenshot from 2021-09-17 18-29-03](https://user-images.githubusercontent.com/7499938/133852985-41476189-00d0-4438-8941-74cd1264acc6.png)

**Comment by danjm** [comment]
@tmashuang Was able to send an ethereum transaction with MetaMask v10.1.0 + firefox + Ledger Nano S + linux (ubuntu)

So something peculiar to certain devices or set ups is happening.

**Comment by trakout** [comment]
@danjm I'm running the Nano S on 2.0.0. Also worth noting that I can make a transfer using ledger live, so I don't think it would be udev rules etc.

**Comment by danjm** [comment]
Thanks for the extra info @trakout, we will continue to investigate

**Comment by ta2bss** [comment]
Did you try to;
Go to Settings on your Ledger device and Allow to Contract Data, if it's not allowed.

**Comment by spzjulien** [comment]
ledger live and ledger wallet nano x latest update Fw and eth app smart contract actived, firefox, wallet working, with brave latest version not working !!

to make it work i force to launch ledger live in bridge mode manually on linux to get it finnaly workin on Brave :
./ledger-live-desktop-2.33.1-linux-x86_64.AppImage ledgerlive://bridge?appName=Ethereum

i dont understand why such pain with Legder and metamask, i have zero issue with brave, phantom wallet and my ledger, why why i cry with metamask ???????

**Comment by bingen** [comment]
> If you open ledger live, and go to the manager section, what version of the ethereum app do you see?

Sorry @danjm  I missed this, I have 1.9.4

**Comment by bingen** [comment]
I just tried updating to last Metamask plugin version (1.5.1) and to last Ledger Etheruem app (1.9.11) and it worked for me. So thanks for fixing it!
Should I close the issue? It seems other users are still having it.

**Comment by AlexJupiter** [comment]
Is anyone still experiencing this issue after the recent updates to the MetaMask/Ledger integration (https://consensys.net/blog/metamask/metamask-and-ledger-integration-fixed/)? Otherwise I'll move towards closing this.
