### ISSUE TITLE
[BUG]: Configuring IPFS gateway with invalid URL

### ISSUE THREAD

**Issue by sambacha** [MetaMask/metamask-extension#12154]
**Describe the bug**
When configuring the setting, `IPFS Gateway` an invalid* URL is allowed. 

> *note: invalid in the sense that it is not a fqdn, hence can not resolve to an IP address

**Steps to reproduce (REQUIRED)**

Bug:
![](https://d.pr/i/gOJUYd.jpeg)

**Expected behavior**
Desired Behavior:
![](https://d.pr/i/11ZkIc.jpeg)

**Browser details (please complete the following information):**
 - OS: 10.15 OSX
 - Browser: latest chrome official release
 - MetaMask Version: 10.1.0

**Comment by Abopo30** [comment]
@metamaskbot

**Comment by bschorchit** [comment]
Closing as this doesn't seem to apply anymore
