### ISSUE TITLE
Cannot send small amounts

### ISSUE THREAD

**Issue by ilanolkies** [MetaMask/metamask-extension#12178]
**Describe the bug**
I'm trying to send 0.0000001 but the input gets cleared out

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to 'send'
2. Click on 'amount'
3. Set '0.000000' ![Screen Shot 2021-09-21 at 22 36 27](https://user-images.githubusercontent.com/36084092/134269822-d455ad8d-80cf-40c9-9662-76dd2bc7f8f0.png)
4. Then type '1' (as per setting '0.0000001') ![Screen Shot 2021-09-21 at 22 36 31](https://user-images.githubusercontent.com/36084092/134269826-0a612894-4553-400f-aa96-cdc97ac6aa8b.png)

**Expected behavior**
See the set amount

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Mac M1
 - Hardware Wallet: no
 - Browser: Chrome latest
 - MetaMask Version: 10.1.0

**Additional context (Error Messages, etc.)**
Using custom RPC

**Comment by bergeron** [comment]
Although I was able to send those small amounts on rootstock:

https://github.com/MetaMask/metamask-extension/assets/3500406/382cdb86-9c3b-402f-a64f-a42d2bbf9d17



This report did uncover a UI issue with the input box rendering small numbers, which has been fixed:
https://github.com/MetaMask/metamask-extension/pull/20666
