### ISSUE TITLE
Pending transactions froze all account features

### ISSUE THREAD

**Issue by daweth** [MetaMask/metamask-extension#12184]
**Describe the bug**
A list of pending and queued txns/contract interactions prevents any kind of action performed with the account 

**Steps to reproduce (May Vary)**
Not sure, Interact with any set of contracts on etherscan's write contract 

**Expected behavior**
I was calling a function on a contract to claim ether. I should have received the ether and the transaction should have gone through. However, it remained in the queue (and still is in the queue in my metamask extension) after almost a month. **Every new transaction I attempt using the wallet just adds new transactions in the queue, and the queue never moves forwards** I had to manually export the private key and use ethers wallet in order to withdraw my funds. Now, I cannot perform any transactions through the metamask extension, but when exporting my private key am able to. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46637826/134433231-5b8d5ba7-81ce-4f91-9e01-457ea4956a68.png)

**Browser details (please complete the following information):**
 - OS: Arch Linux 
 - Hardware Wallet: none
 - Browser: Brave Browser
 - MetaMask Version: 

**Additional context (Error Messages, etc.)**

**Comment by bschorchit** [comment]
Thank you for filling this bug. Does speeding up or canceling the transaction solves the issue?
