### ISSUE TITLE
Import Seed Phrase View

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#12193]
![Screen Shot 2021-10-05 at 11 07 16 AM](https://user-images.githubusercontent.com/34557516/136060878-80c60dac-3400-481d-8a1b-9f3cd7ff3733.png)

**Comment by kevinghim** [comment]
Related to [import seed phrase](https://www.notion.so/I-want-to-import-my-existing-wallet-by-inputing-or-scanning-a-seed-phrase-e9e7dbf43e584b27a10739000d128416) story in Notion.
