### ISSUE TITLE
Import Mobile Wallet View

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#12195]

**Comment by kevinghim** [comment]
Related to [Import MM wallet](https://www.notion.so/I-want-to-see-instructions-on-how-to-import-my-MetaMask-I-created-on-a-mobile-device-d1bcff9e04e749f6a49356920defce88) story in Notion.

**Comment by bschorchit** [comment]
Closing as this will be reviewed on https://github.com/MetaMask/metamask-extension/issues/14417
cc: @AlexJupiter
