### ISSUE TITLE
Set advanced Privacy Settings View

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#12196]
![Screen Shot 2021-09-28 at 12 02 10 PM](https://user-images.githubusercontent.com/34557516/135132573-6fd934ac-caa2-479a-8361-208681f3f390.png)

**Comment by kevinghim** [comment]
Related to [show incoming transactions](https://www.notion.so/Have-users-set-to-allow-Etherscan-show-incoming-transactions-e4eeae17a13040e0a47acdcaa52c093e), [phishing detection](https://www.notion.so/Have-users-use-jsDelivr-to-alert-them-on-phishing-detection-2eb319e3363a4b34b545100bf2640ff3), and [token detection](https://www.notion.so/Turn-on-token-detection-service-7261a63e589a44fca1f937d0a341ba8f) stories in Notion.

**Comment by kevinghim** [comment]
Sync with 3Box will be deprecated, correct @danjm ?
