### ISSUE TITLE
circleci.com build error

### ISSUE THREAD

**Issue by 0x00trust** [MetaMask/metamask-extension#12216]
circleci.com build error
![Screenshot 2021-09-26 at 09-18-09 Workflow - metamask-extension 1 bf189729-1bdf-4975-9e2b-6bf722b460b3`](https://user-images.githubusercontent.com/88810693/134790976-4c8c7e3a-e995-42d8-8f87-23b2f028d3ff.png)
![Screenshot 2021-09-26 at 09-19-19 Pipelines - trustwalletvn metamask-extension](https://user-images.githubusercontent.com/88810693/134790979-ecf133c2-79eb-4921-81de-218cec0cc918.png)

**Comment by mcmire** [comment]
Hey @trustwalletvn, can you give us a link to the failing build you're seeing? [This](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/12876/workflows/cabaf3ce-6572-4111-a5cf-dfe16fd80e06) is the latest build and it seems like it's passing.

**Comment by brad-decker** [comment]
The link is no longer valid, and the proper place for discussion about build failures is in the PR that has the failing build.
