### ISSUE TITLE
Firefox & Latest Ledger does not send transactions to device

### ISSUE THREAD

**Issue by lucasvo** [MetaMask/metamask-extension#12214]
I'm using the latest version of firefox and a ledger that I just updated today to trigger an ERC20 transfer. The UI shows the transaction going through but the ledger never actually asks me for confirmation. When trying to cancel the transaction it tells me the cancellation is pending and then renders the transaction list in a weird way:

<img width="419" alt="Screen Shot 2021-09-25 at 21 58 27" src="https://user-images.githubusercontent.com/31727/134784655-3b57ebe8-dd36-4a87-a811-bc48950ff73e.png">

**Comment by beckywal** [comment]
I can walk you through how to get this resolved, would send you a mail soon.

**Comment by johansten** [comment]
Same thing here.

**Comment by johansten** [comment]
Same thing with Ledger 1.9.7

**Comment by CallumGrindle** [comment]
Managed to fix this by selecting 'connect hardware wallet' again to try and force reconnect the ledger

**Comment by johansten** [comment]
Same thing again, but for 1.9.11
