### ISSUE TITLE
Offline for maintenance

### ISSUE THREAD

**Issue by Shaukat1550** [MetaMask/metamask-extension#12273]
Offline for maintenance
MetaMask Swaps is undergoing maintenance. Please check back later.
WHEN SWAP EVERY TIME METAMASK Says this no swap done plz solve this issue

**Comment by danjm** [comment]
This problem should be resolved. Please comment here if you are still experiencing the issue

**Comment by Shaukat1550** [comment]
hi sir how r u this problem still not solved plz solve my issue thnx 
![Screenshot_3](https://user-images.githubusercontent.com/91834608/135861374-6aa57e16-4089-4175-8aee-d58e0d885e15.png)
![Screenshot_4](https://user-images.githubusercontent.com/91834608/135861510-21769b28-e7e2-4e64-98bd-1bb642ce0598.png)

sir you can see that both screen shot still metamask offline status 
my ETH address is
0xCF4Ea9d84D1bB14D77deeC8D35B25b42adC4a646
sir i am thankful to you plz solve my problem as soon as possible

**Comment by Shaukat1550** [comment]
helo sir plz solve my issue its still not solved
