### ISSUE TITLE
Cannot edit the decimals field when adding some custom tokens

### ISSUE THREAD

**Issue by 0xTycoon** [MetaMask/metamask-extension#12288]
**Describe the bug**

Cannot edit the decimals field when adding some custom tokens. The decimal field is disabled from editing.
For example 0xbb9bc244d798123fde783fcc1c72d3bb8c189413
This is a token that does not have a decimals property.

(Under the ERC20 standard, the decimals property is optional, so this token conforms to the standard even though it's unusual)

Another related issue: if the token is added via web3js then it is impossible to send it, the send button is disabled even when there is a balance

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Add Token -> Custom Token tab
2. Enter 0xbb9bc244d798123fde783fcc1c72d3bb8c189413
3. The Decimals field will be disabled. This custom token requires 16 decimals.

**Expected behavior**
The decimals field should be editable

**Screenshots**
Wasn't able to take a screenshot since the damn window keeps closing...

**Browser details (please complete the following information):**
Linux, Firefox
MM v 10.1.0

**Additional context (Error Messages, etc.)**

**Comment by VSaric** [comment]
We put this ticket in `Pending Consensys` because we wait for some new findings and information from @adonesky1 about this ticket.

**Comment by arewers** [comment]
Hi all, any updates on this? I'm having the same issue in version 10.15.0 on Chrome.

Trying to add my contract and the decimal field greys out, I've tried editing it before adding the contract address but it changes back to 0 automatically and greys out the option.

**Comment by 0xTycoon** [comment]
> This behaviour happens when the call to symbol on the smart contract address fails.

Yup...

Please note that that the symbol() method is marked as optional in ERC20, so some contracts may not have it. In that case, the wallet should ask the user to enter it. Also the decimals() method is optional.

**Comment by amonsosanz** [comment]
I'm experiencing this issue with the [ERC-20 contract of eXRD](https://etherscan.io/address/0x6468e79A80C0eaB0F9A2B574c8d5bC374Af59414) and apparently, the symbol method is working.

I can read it from Etherscan:

<img width="300px" src="https://user-images.githubusercontent.com/15896177/201426058-081f602d-848c-407e-9e73-083cd77910e3.png" />
