### ISSUE TITLE
Design updates on the account details screen

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12292]
- Update the "close" icon
- ~~Display full address: remove auto selected state, change the BG color to UI1~~

![Screenshot from 2021-10-07 06-48-41](https://user-images.githubusercontent.com/7499938/136356664-597ae025-f1e5-4b79-be71-6eb5072d0a46.png)

Note: button updates have already happened, as has address truncation

**Comment by igorms-cons** [comment]
More changes implemented (figma):
![image](https://user-images.githubusercontent.com/89637087/137764511-e6005886-e563-45e0-8ad5-a0c16e20c8d8.png)

**Comment by igorms-cons** [comment]
The changes above were agreed by Alex Donesky & Dan Miller

**Comment by bschorchit** [comment]
Closing as this was fixed with https://github.com/MetaMask/metamask-extension/pull/12399
