### ISSUE TITLE
Design updates in the transaction details view

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12295]
![Screenshot from 2021-10-07 07-20-49](https://user-images.githubusercontent.com/7499938/136361957-33ceee7c-4dba-49a4-abbe-c188cd2f147f.png)

2 in the above list can be ignored as address truncation has been handled in a separate PR

To see this component, create and send a transaction. Then click on that transaction in the transaction activity list.

**Comment by Gudahtt** [comment]
@igorms-cons Can this issue be closed?
