### ISSUE TITLE
Update Icons on the Settings page

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12324]
![Screenshot from 2021-10-11 08-54-39](https://user-images.githubusercontent.com/7499938/136782338-d54be77f-5eac-4379-a0b4-6978322bf8fa.png)

**Comment by agileurbanite** [comment]
@danjm should this issue still be marked open?  I believe #12359 resolves this issue.  Please confirm as I'm looking for some good-first-issues to help contribute to this project.

**Comment by Gudahtt** [comment]
Curious that the color UI4 was used in #12359 rather than UI3 :thinking: Was that intentional @filipsekulic ?

**Comment by filipsekulic** [comment]
> Curious that the color UI4 was used in #12359 rather than UI3 thinking Was that intentional @filipsekulic ?

@Gudahtt 

If you go to Figma (https://www.figma.com/file/b1YjR0OG4RRQgEChYfwbey/UI-audit?node-id=142%3A1022), you will see it was updated there.

**Comment by Gudahtt** [comment]
Thanks for the clarification. So this issue can be closed?

**Comment by filipsekulic** [comment]
I suppose so, because it was merged, but I do not know if members of my team are authorized to do that (close an issue), or just the members of the MetaMask team can do so.

**Comment by Gudahtt** [comment]
Please feel free to close anything that you think has been completed! It actually closes automatically when the associated PR is merged if it's referenced in the right way (you need to say "Closes #___" or "Fixes #___" in the commit).

We can re-open anything we feel still has remaining work.

**Comment by filipsekulic** [comment]
Thank you! I will share your information with my team.
