### ISSUE TITLE
HW wallet rejected transaction shows as completed if a subsequent transaction is completed

### ISSUE THREAD

**Issue by jblachly** [MetaMask/metamask-extension#12340]
Metamask version 10.2.2 (latest)
Firefox (latest)
Ledger hw wallet latest firmware, latest Ethereum app

Description: When a transaction is rejected from HW wallet then followed by an approved one, metamask only shows the rejected transaction in the UI (name, description), but with the hash of the approved transaction.

**Steps to reproduce:**

1. Initiate a transaction Tx on a web3 enabled site
2. Confirm the transaction in metamask
3. Reject it from the hardware wallet
4. Initiate a token transfer from metamask
5. Approve transfer on HW wallet
   ( at this point, and possibly immediately after step 3 although I can't verify this, the prior rejected transaction shows as queued)

**Bug 1:** The transfer never shows as queued or pending

**Bug 2:** After the transfer completes, the rejected transaction now shows as a completed transaction; however its hash (and thus the link to Block explorer) is that of the successfully completed TRANSFER

**Expected behavior:**

1. The rejected transaction should show as rejected
2. The successful transaction should show up
3. Transactions in the transaction history should never have mixed data (description from one; hash from another)

**Comment by danjm** [comment]
I actually believe this is related to how we group transactions by nonce
