### ISSUE TITLE
Add copy to SRP import screen to warn users that there current wallet will be replaced

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12343]
When importing Secret Recovery Phrase, it replaces their current wallet, including the ETH/tokens that are in there. Include warning that importing a new SRP will remove the current wallet/assets

https://www.figma.com/file/b1YjR0OG4RRQgEChYfwbey/UI-audit?node-id=326%3A3566

(This screen is accessed by clicking "import using Secret Recovery Phrase" on the unlock screen)

**Comment by VSaric** [comment]
Closed by: #12400
