### ISSUE TITLE
Show account name when pasting a user's own account into the send flow

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12346]
1. Copy the address of one of your accounts
2. Switch accounts
3. Go into the send flow
4. Paste the address of the account you copied in step 1
5. You will see that the account name does not appear in the address bar of the send screen

Instead, the account name should appear, as it does when selecting the account via the "Transfer between my accounts" option in the send flow.

This is demonstrated in this screen capture

https://user-images.githubusercontent.com/7499938/137101106-19ef2833-7b49-4d14-a5f0-64e1978cbd1e.mp4

**Comment by igorms-cons** [comment]
Changes related to figma
![image](https://user-images.githubusercontent.com/89637087/138093674-5b2e34ce-881e-493c-842e-be3dcb50cf40.png)
