### ISSUE TITLE
can not get chainID

### ISSUE THREAD

**Issue by viponedream** [MetaMask/metamask-extension#12369]
Something is Wrong with metamask!!!

![QQ图片20211016203611](https://user-images.githubusercontent.com/16624529/137587687-c5bdd66e-6f83-4fa1-b30b-dfe4d187d37d.png)

ERROR shown above.

When i use pyppeteer to control chromium , load this extension , and add a network , it shows the error above. 
Any one know how to fix it. 
please. 
thank you all.

i try again and again ,  finally  i found , that's the problem of metamask.

i can only  add the network by click the toolsbars icon, and select mainnet,  curstom RPC, 

==========================================

**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by viponedream** [comment]
Yes, 
i just add the extension to chrome, it's all new. 
you can see it ,  it's the first chain i add.

![2222222222222](https://user-images.githubusercontent.com/16624529/137811254-4d9b3d6a-3e5a-4172-bc80-585ac799be20.png)

**Comment by Madeindreams** [comment]
Well it seems that it did not like my chain id of 9998. Changed it to a lower number and it went fine!

**Comment by Madeindreams** [comment]
@viponedream did you try to pass it the number as Hexadecimals value?
