### ISSUE TITLE
Feature request: undo send

### ISSUE THREAD

**Issue by rmerom** [MetaMask/metamask-extension#1236]
Wallets in a way are much like an email client. It's a way for people to communicate, only with money instead of text.

People make mistakes. And these mistakes can be very costly. While an email gone wrong can have bad consequences, sending a huge amount of ETH because of a momentary distraction or a "fat finger" can have a devastating effect for an individual.
Gmail has introduced [undo send](https://support.google.com/mail/answer/2819488?co=GENIE.Platform%3DDesktop&hl=en) a few years ago. Would Metamask consider adding something similar?

**Comment by Zanibas** [comment]
The way Gmail introduced their undo send is by a inherent limitation of their system--it takes about 6 seconds for the email to actually be sent.

We do not have any sorts of limitations like that--the limiting factor is when a miner processes our transaction. If we wanted to do an undo, we can't just do a "takeback" after we submit our tx to the system.

This would require us to manually hold a transaction in memory with a delay and then submit for processing on the network once the delay ends. However, this would already add waiting time to an already delayed transaction.

This isn't really an attractive solution for us currently, but we're willing to entertain discussion.

**Comment by rmerom** [comment]
Thank you Zanibas. As a gmail users, I can say that I'm happy to *opt-in* to this feature even while knowing I'll wait the extra few seconds. I would not have been happy if this was forced upon me.

The context of my question is a crowdsale that my team is running and in which we had a few participants who emailed us with pretty emotional messages after they either accidentally sent us money, or they mistakenly entered another digit. Yes, we can say "it's their fault", but a good UX should help fallible homo sapiens to makes less costly mistakes.

A good balance that you might want to consider is letting users define a threshold of ETH above which the undo send feature will kick in. Say, if I'm going to send anything about 10ETH, by default it would wait X seconds before sending while prominently showing an "undo" button. I'll definitely turn on this feature as another benefit of it would be that there'll be a kind of UX "heads up" before I send what I consider a big transaction.

**Comment by flyswatter** [comment]
I think adding a delay & cancel option is nice, and I even like the idea of making it automatically scale the delay based on the transfer size.

This gets a little more complicated when people are transferring valuable tokens, we need to integrate a token registry with a token price oracle to identify the approximate value of a given tx, and warn users accordingly.

Would be nice to have a designer like @VladTod chime in on what a possible wait-to-send and cancel feature might look like.

**Comment by danfinlay** [comment]
Another strategy [suggested by @MicahZoltu here](https://github.com/MetaMask/metamask-extension/issues/1668#issuecomment-347984835) is for the cancel button to suggest a transaction of zero value to the same account, but with higher gas price. This would allow someone to quickly send a transaction to race against and nullify another tx.

**Comment by MicahZoltu** [comment]
Note: The "send 0 to self" strategy is also what Parity uses for its "cancel" button.

**Comment by danfinlay** [comment]
Closing in favor of #2693
