### ISSUE TITLE
Investigate using normal browser popup for clicking MetaMask fox

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1240]
There are a number of issues we have because extension "popups" are just not very well supported, and the browser implementations are buggy.

#1213, #1136, now #1234, could all be alleviated by moving off using the extension popup for anything complicated, which is a lot of what we do now.

**Comment by Zanibas** [comment]
LastPass has an architecture that allows access to basic functions such as pass retrieval, but opens a new tab for the more complex stuff. I think this isn't an unreasonable thing, but it could potentially compromise our user flow if we move too many things to the tab.
