### ISSUE TITLE
Account details edit allows duplicate labels

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#12421]
When editing an account name, the use is allowed to repeat an account name that already exists.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Create multiple accounts
2. From the three-dot menu, click Account Details
3. Click the pen icon next to the account name
4. Type an account name that matches another existing account, then submit

**Expected behavior**
Prevent submission, show an error that says something to the effect of "This account name already exists"

**Screenshots**

https://user-images.githubusercontent.com/46655/138191673-1eb05cb2-b72e-405c-9a86-820b2aa96363.mp4

**Comment by EHaracic** [comment]
AC:
- On changing the account name - (Edit) we should check the name does not exist
- On creating a new account  (Create Account) we should check the name does not exist
