### ISSUE TITLE
Connecting to MetaMask from Chrome Extension.

### ISSUE THREAD

**Issue by anudit** [MetaMask/metamask-extension#12444]
When setting up an `MetaMaskInpageProvider` for a Chrome Extension injecting it from a Content Script using,
```js
import { initializeProvider } from '@metamask/providers';
import LocalMessageDuplexStream from 'post-message-stream';

const metamaskStream = new LocalMessageDuplexStream({
    name: 'metamask-inpage',
    target: 'metamask-contentscript',
});
let ethereumProvider = initializeProvider({
    connectionStream: metamaskStream,
});
const ethersProvider = new ethers.providers.Web3Provider(window.ethereum);
```

But, neither of the following actually resolve.
```js
let accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
let accounts = await window.ethereum.enable();
let accounts = await ethersProvider.listAccounts();
```
actually resolve.

I also occasionally get,
![image](https://user-images.githubusercontent.com/12015553/138498829-96961b8b-8153-44d9-be00-85458c0c24a5.png)

Here is the chrome extension code  : [anudit/convoextension](https://github.com/anudit/convoextension/blob/39694918078770d266c247cf06e71ac98e72a1e5/src/contexts/Web3Context.js#L164)

**Expected behavior**
Should connect to provider and list accounts.

**Browser details (please complete the following information):**
 - OS: Windows 11 Version 21H2 (Build 22000.258)
 - Browser: Brave | 1.32.77 Chromium: 95.0.4638.54 (Official Build) dev (64-bit)
 - MetaMask Version: 10.2.2

**Comment by DSKonstantin** [comment]
Any ideas?

**Comment by cardanative** [comment]
HI thanks for raising this up, I was wondering what was the best way to access metamask from another chrome extension. 
As you mention, in content-scripts, window.ethereum is not available...

**Comment by emorling** [comment]
Anyone solve this?

**Comment by rekmarks** [comment]
We have a separate package for connecting to extensions: https://github.com/MetaMask/extension-provider

@anudit does that package resolve your issue? Note that the example extension in that repository is broken, but the package itself should work.

**Comment by anudit** [comment]
Worked perfectly, Thanks @rekmarks !

**Comment by rekmarks** [comment]
Awesome. @DSKonstantin, @cardanative, and @emorling, that should be what you're looking for as well.

Since this is resolved, I will now close this issue.

**Comment by itissandeep98** [comment]
Hey, @rekmarks I am also trying to connect metamask from my extension and it's a basic HTML based extension

Can you clarify how can I use this in content_scripts?

**Comment by javaspeak** [comment]
> We have a separate package for connecting to extensions: https://github.com/MetaMask/extension-provider
> 
> @anudit does that package resolve your issue? Note that the example extension in that repository is broken, but the package itself should work.

Here we are in March 9th 2023 - the extension-provider has deprecated stuff in it.  What should we be using now to talk to metamask from another extension?

**Comment by raehat** [comment]
I want to access metamask flask instead of metamask from my chrome extension.
https://github.com/MetaMask/extension-provider works fine for metamask but not for metamask flask.
Can someone help me here?

**Comment by Myestery** [comment]
> > We have a separate package for connecting to extensions: https://github.com/MetaMask/extension-provider
> > @anudit does that package resolve your issue? Note that the example extension in that repository is broken, but the package itself should work.
> 
> Here we are in March 9th 2023 - the extension-provider has deprecated stuff in it. What should we be using now to talk to metamask from another extension?

I still have an issue with this in September 26 2023

**Comment by javaspeak** [comment]
I am also finding it hard to find example code for connecting a chrome extension to metamask.

Why is it so poorly documented?

**Comment by javaspeak** [comment]
I still have issues as well. 29th Sept 2023. HELP.
