### ISSUE TITLE
Create a Nickname popover

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12474]
See figma design here: https://www.figma.com/file/y3PPTfecP3jzH5QrlO1S9w/Transaction-Insight-Epic?node-id=4%3A273

This task is just to implement this component

![Screenshot from 2021-10-25 08-59-37](https://user-images.githubusercontent.com/7499938/138687435-92e5319e-152d-4c66-a856-ac7faf1b4334.png)

Do not yet add it to the app. Instead, add a storybook story that displays this component. We should probably add a button in the story that when clicked displays the popover.

This component should receive at least the following props:

- nickname (type: string)
- address (type: string)
- onclose (type: function)
- onadd (type: function)

For this, be sure to follow our popover pattern and utilize the `Popover` component (and not our older patterns that use `modal.js` or `modal.component.js`)

**Comment by EHaracic** [comment]
HI @danjm can you please confirm the component properties:

- address (type: string) - address for which we have an option to add a nickname, on the screen above we have a shorten and full address displayed??
- onclose (type: function)
- onadd (type: function)
