### ISSUE TITLE
"Invalid transaction params" for Trezor

### ISSUE THREAD

**Issue by AlphaSerpentis** [MetaMask/metamask-extension#12482]
**Describe the bug**
On certain dApps (such as Etherscan and Gnosis Safe), trying to send a mainnet transaction gets instantly rejected with `Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559`.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

Certain dApps don't throw this error, but this has affected notable dApps like Etherscan and Gnosis Safe. Tested using a Trezor Model One on Brave

1. Go to either Etherscan and Gnosis Safe
2. Craft any type of transaction to send to mainnet that wouldn't fail for whatever reason
3. You will be met with an error (either in console or frontend if it is caught) and no prompt to send the transaction

**Expected behavior**
Prompted a transaction confirmation to send.

**Browser details (please complete the following information):**
 - OS: Windows 10 Home
 - Hardware Wallet: (Trezor Model One) Trezor Firmware 1.10.3
 - Browser: Brave (1.31.87 - Chromium: 95.0.4638.54 (Official Build) 64-bit)
 - MetaMask Version: 10.3.0

**Additional context (Error Messages, etc.)**
Tested the same dApps against with Frame 0.5.0-beta.6 and 0.5.0-beta.7 with the same Trezor and same browser via their extension and works fine.

**Comment by hexnation** [comment]
Do you guys have any solutions for chrome metamask version with trezor 1?

**Comment by ibai93** [comment]
Just getting a bit dissapointed we are in November and still have this problem unsolved for Trezor. Is there any estimation for when this will be fixed?

**Comment by 0xSolus** [comment]
Here to report this same issue.

**Comment by rschaerer** [comment]
:question: Has anyone an idea where to start to help resolving this issue?

**Comment by rheeger** [comment]
Here to bump this issue. Please fix!

**Comment by thob** [comment]
second that

**Comment by rschaerer** [comment]
:information_source: trezor fixed https://github.com/trezor/trezor-firmware/issues/1834 with the most recent firmware 1.10.4 [8th December 2021].

:question: Can this drive this issue further?

**Comment by volkyeth** [comment]
Looks like this is fixed on [v10.8.0](https://github.com/MetaMask/metamask-extension/releases/tag/v10.8.0). I just managed to bridge some assets to Polygon with my Trezor One 🎉 

This version is not on Chrome Web Store yet, so you might have to enable developer mode on extensions and "load unpacked"

**Comment by AlexJupiter** [comment]
Closing as it seems this issue has been fixed in a previous release of MetaMask.
