### ISSUE TITLE
Create an "Add a Nickname" popover (also support edit)

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12528]
See figma design here: https://www.figma.com/file/y3PPTfecP3jzH5QrlO1S9w/Transaction-Insight-Epic?node-id=19%3A824

This task is just to implement this component

![Screenshot from 2021-10-29 07-17-13](https://user-images.githubusercontent.com/7499938/139414422-d4204776-a381-4a95-9e1a-6ad37fbda451.png)

Do not yet add it to the app. Instead, add a storybook story that displays this component. We should probably add a button in the story that when clicked displays the popover.

This component should receive at least the following props:

- nickname (type: string)
- address (type: string)
- onclose (type: function)
- onadd (type: function)
- memo (type: string)

For this, be sure to follow our popover pattern and utilize the `Popover` component (and not our older patterns that use `modal.js` or `modal.component.js`)

If a nickname is passed in, the component should be in edit mode:

![Screenshot from 2021-10-29 07-20-14](https://user-images.githubusercontent.com/7499938/139414647-66eb7999-6d59-4e86-bcce-7ac36867385e.png)

**Comment by danjm** [comment]
An example storybook file https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/ui/actionable-message/actionable-message.stories.js

**Comment by danjm** [comment]
Perhaps the component should be called `UpdateNickname`

**Comment by bschorchit** [comment]
Closing this as this has been fixed with: https://github.com/MetaMask/metamask-extension/pull/12644
