### ISSUE TITLE
Critical bug!! I can not send exact number of token!!

### ISSUE THREAD

**Issue by lolieatapple** [MetaMask/metamask-extension#12523]
**Describe the bug**
Critical bug!! I can not send exact number of token!!
It automatic add many decimals after my amount when I'm trying to input 1195.00556 in USDT transfer on bsc.
I'm using a service need I input exactly decimals. this but make me crazy.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. select bsc network;
2. select USDT;
3. select transfer;
4. input address;
5. input amount 1195.00556
6. issue happens;
7. even after I fix the amount, the next page is wrong, too;

**Expected behavior**
show exact amount I input.

**Screenshots**
![image](https://user-images.githubusercontent.com/54833180/139372481-c5894844-0412-46cb-bfde-c2b73325137b.png)

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: Ledger Nano S Firmware version 2.0.0
 - Browser: Chrome latest version
 - MetaMask Version: 10.3.0

**Comment by suspended** [comment]
I am facing this issue as well, seems like an issue with BN representation.

Example: I have 358.5938598 tokens - I want to send 358.59. However, Metamask changes the field to 358.58999999993785 tokens instead.

**Comment by TMCTG** [comment]
Myself and a bunch of other people are having the same issue sending BSC BEP-20 BUSD and BEP-20 USDT from the Metamask Browser Extension.
Whenever a number is typed after a decimal point in the Amount field, the number goes funky.
1.1 becomes 1.100000000000000089
5.6 becomes 5.599999999999999645

**Comment by mchinsomboon** [comment]
I have the same issue. I've tried on Brave, Firefox and Chrome, on a Mac Mini and Macbook Pro and also tried to startup in safe mode. Can't send non-whole numbers. I also tried to even insert in the decimal after typing the numbers, but once I hit the decimal, it goes haywire and inserts other digits.

**Comment by suspended** [comment]
I am using v10.6.1 and I still experience this issue. The UI now shows the correct number of tokens (ie. 4175.3800) but the wrong number is sent to the RPC in the backend (ie. 4175.380000000000109139)
