### ISSUE TITLE
Wallet on Ethereum Network showing not showing previous assets or transactions

### ISSUE THREAD

**Issue by aSimpleProgram** [MetaMask/metamask-extension#12548]
Hiya, I connected to shibaswab.com to stake my coins. Now the wallet is not showing up on my previous connections. All other networks working. Any ideas how to correct?

**Comment by aSimpleProgram** [comment]
I deleted and reinstalled. There's a bug when I install the Avalanche network! It there a way around this. Will a new account on the ethereum network help?

**Comment by darkwing** [comment]
Hello @aSimpleProgram.  Please use our official Support channel (http://support.metamask.io/) for help resolving your specific issue.  Thank you!
