### ISSUE TITLE
error does not display after signMessage

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1254]
in the view code below, if an error is encountered we call "displayWarning"
but only a blank screen is shown.

reproduce:
```js
web3.eth.sign(web3.eth.accounts[0], 'i am a string', console.log)
```

@Zanibas i think you made some changes here, maybe this is already fixed. this was caught on the published version.

```
function signMsg(msgData) {
  log.debug('action - signMsg');
  return function (dispatch) {
    dispatch(actions.showLoadingIndication());

    log.debug('actions calling background.signMessage');
    background.signMessage(msgData, function (err, newState) {
      log.debug('signMessage called back');
      dispatch(actions.updateMetamaskState(newState));
      dispatch(actions.hideLoadingIndication());

      if (err) log.error(err);
      if (err) return dispatch(actions.displayWarning(err.message));

      dispatch(actions.completedTx(msgData.metamaskId));
    });
  };
}
```

signMessage

**Comment by Zanibas** [comment]
The state of isLoading is updating correctly to be false, but the spinner isn't disappearing. Weird.

**Comment by flyswatter** [comment]
Those are two different UI bugs.

@Zanibas the spinner shows if the `state.appState.currentView.name === 'confTx'` but there are no txs to display.

The completely blank view is maybe similarly related to hard-coded routes that don't have state to populate them, but I think they're different parts of the UI.

**Comment by Zanibas** [comment]
Yeah, this seems to break when we approve the last message we have--queueing up two messages and approving the first properly displays the error and removes the loading indication.
