### ISSUE TITLE
Signing 1559 txs with Ledger on chains with a high chain_id can fail weirdly

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#12541]
Ledger [has published a fix](https://unpkg.com/browse/@ledgerhq/hw-app-eth@6.12.2/lib/Eth.js) in in[ hw-eth-app](https://www.npmjs.com/package/@ledgerhq/hw-app-eth) v6.12.2 (line 376), so we just need to update that module & QA for this fix.

**Comment by danjm** [comment]
was fixed with https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/127
