### ISSUE TITLE
Transaction and speedups not being sent

### ISSUE THREAD

**Issue by Philx0** [MetaMask/metamask-extension#12543]
### Description:
It often happens that eth transactions (speedups or new ones) are not sent to the node, no matter if the standard mainnet node or my own nodes are used. I don't know if the issue occurs on other chains. The issue has been present for many many months.

### Diagnosis:
Sometimes, everything is working fine, other times not.
When sending a tx at fee price (priority: x, max: y), the transaction is not sent. I confirmed this many times by querying my node with web3 for the tx as well as etherscan. When I send a speedup replacement tx using a sub-10% increase of gas fees (0 wei or more) the rpc should return a 'replacement tx underpriced error', which only happens if the initial tx and speedup tx were sent to the node.  This is how I now I can stop retrying. I might have to 'replace tx' 10 times before I get the rcp error indicating the tx was already sent before.

**Steps to reproduce**
0. (possibly, externally spam the metamask sentry url so you get a 429 too many request error? )
1. send a tx and check with web3 the tx was not sent
Most days the issue is very reproducible on my system.

**Browser details (please complete the following information):**
 - Win10
 - Browser: Version 95.0.4638.54 (Official Build) (64-bit)
 - Metamask verion: 10.3.0 on chrome, windows 10, settings:
    * memetic passphras+imported pks
    * Show Incoming Transactions: 1
    * Use Phishing Detection: 1
    * Participate in MetaMetrics: 0
    * metamask extension user data was recently wiped after an update or crash, so resetting it again won't help.
- my own geth eth nodes are behind a nginx server
- about one year ago metamask was freezing on my previous pc, also due to sentry I believe .

### **Additional context (Error Messages, etc.)**
devtool log:
I believe the issue occurs together with connection issues to sentry. (see screenshot) Metametrics are disabled.
Errors: 
 * https://sentry.io/[path_redacted] 429 (Too Many Requests)
 * header not found
 * stream.push() after EOF
 * Error: write after end

### **Screenshots**
![metaErrors](https://user-images.githubusercontent.com/32342766/139519623-c879c6c4-3b25-4e38-9654-067927b399a6.png)

possibly related:
https://github.com/MetaMask/metamask-extension/issues/7054#issuecomment-923691054

**Comment by djrosenbaum** [comment]
As a user, I can confirm I am having this issue at the moment. for whatever reason speed ups are not sending

**Comment by Philx0** [comment]
I tested different networks and the issue seems to only occur on ETH.
Btw I'm not sure why there are requests to sentry when metrics are disabled.

**Comment by Trickster4** [comment]
Speeding up transactions is not working at all with Ledger HW wallet connected. Transaction is being signed on the device, but nothing is being sent to the network.

**Comment by bschorchit** [comment]
Thank you for the report @Philx0, is this still happening?
