### ISSUE TITLE
Commas break token send value field

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#12554]
Reproduction steps:
- Click a token
- Click "send (symbol)"
- Enter a recipient
- Paste a number with a comma, like `1,304.53`.
- Notice the formatting is broken. The number is also interpreted as `0` if I click continue.

Example:
<img width="423" alt="Screen Shot 2021-11-01 at 4 41 44 PM" src="https://user-images.githubusercontent.com/542863/139756585-126bfaf3-c4c6-4d5a-87e4-993963e3c231.png">

Expected results:
Automatically sanitize the input string into a number, or at least show the number full width.

**Comment by EHaracic** [comment]
Not able to reproduce the issue.
Chrome, MM Extension 10.2.2

![image](https://user-images.githubusercontent.com/49436614/140482966-b76a8b95-578f-4824-b97f-c77f6912283b.png)

**Comment by danjm** [comment]
@danfinlay Any further details on how you reproduced this? Can you still reproduce it today?

**Comment by bschorchit** [comment]
I've tried to reproduce it and the value became 1.30453 instead of the expected 1304.53
Metamask version 10.6.1

<img width="346" alt="Screen Shot 2021-11-25 at 12 21 04" src="https://user-images.githubusercontent.com/34968356/143467147-39797139-df83-46b5-848c-eb728739abc8.png">

**Comment by EHaracic** [comment]
Still not able to reproduce.
MM version: 10.6.2. Browsers: MS Edge and Chrome. Screenshots from Edge and Chrome:

![image](https://user-images.githubusercontent.com/49436614/144022610-eebd1356-65d4-44b3-9832-d29bc044fe01.png)
![image](https://user-images.githubusercontent.com/49436614/144022880-0c872f61-ba4d-4c1a-9d56-24333173622f.png)

@bschorchit on which browser you have tested it ?

**Comment by bschorchit** [comment]
Brave Version 1.32.106 

Could this be due to some localization and using commas instead of periods as decimal point?

**Comment by bschorchit** [comment]
Brave Version 1.32.106, @EHaracic .

Could this be due to some localization and using commas instead of periods as decimal point?

**Comment by EHaracic** [comment]
@bschorchit I also think it is related to the localization. 

Do you know what is your decimal symbol, comma or point?

**Comment by bschorchit** [comment]
It's comma, @EHaracic .

**Comment by EHaracic** [comment]
@bschorchit can you please try to paste the string: 1.304,53

**Comment by bschorchit** [comment]
This is the result when pasting 1.304,53:
<img width="351" alt="Screen Shot 2021-12-01 at 10 18 56" src="https://user-images.githubusercontent.com/34968356/144241503-57d59959-2911-4940-8d74-c60fd3715700.png">
@EHaracic

**Comment by danjm** [comment]
We are not able to reproduce this
