### ISSUE TITLE
Connecting to local parity node shows "Custom Network"

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1255]
I thought I was on testrpc but instead sent real ether (to myself, thank goodness!)

Having a main-net local node selected should show *main network* in the top left in some way, even if it also indicates it's a local node.

**Comment by flyswatter** [comment]
@VladTod What should we show in the menu bar when a custom main-network is selected?

**Comment by VladTod** [comment]
We could use something like this. If i understood the problem correctly. 
![0a-custommainnet](https://cloud.githubusercontent.com/assets/13063928/24374176/8e4aee6e-133c-11e7-926a-762d72a49309.jpg)

**Comment by Zanibas** [comment]
the colors are confusing in this case--does the first icon mean I'm connected to main net and test net?

I think we could solve this issue by possibly integrating two icons--one to indicate the network itself, and two to indicate the network provider.

Network:
- Main
- Ropsten
- Kovan
- Infuranet
- Custom

Provider:
- Infura
- Self-hosted
- ???

**Comment by VladTod** [comment]
Well, the one with the red "main net" is supposed to caution you that you are on another network than the main one. This why the icon is made out of two diamond icons. It's still a main net icon, but it's a custom one. 

I'm not sure about adding the provider, this will weigh heavy on the UI. Also this is an option that it's more geared for developers than anyone else. And i think developers are not our main target. But i might be wrong. If they are let me know and w'll see from there.

In the meantime i'll think of another icon for custom.

**Comment by flyswatter** [comment]
It would be cool if this also indicated if a connection was via Infura, and maybe even via Parity vs Geth or other client.

(A lot of info for a small space!)

I don't think having two menu items is the solution, this wouldn't fit on the main account detail page.

**Comment by flyswatter** [comment]
Related to #1071
