### ISSUE TITLE
Implement reusable components for Flask

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#12574]
- [x] #12661
  - "Card" component to be used in Snap settings
  - [Figma](https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/Flask-MVP?node-id=336%3A7207)
  - Related UI feature issue: #11681 
- [x] #12668
  - It's possible that the connected status indicator on the home screen could be reused
    - <details><summary>Screenshot</summary><img src="https://user-images.githubusercontent.com/25517051/140186310-aaa33505-98b8-4ae9-8b7d-c3a1ab126cc0.png"></details>
  - [Figma](https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/Flask-MVP?node-id=336%3A7215)
  - Related UI feature issue: #11681
- [x] #12714
  - [Figma](https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/Flask-MVP?node-id=923%3A9658)
  - Related UI feature issue: #11682 
- [x] #12684
  - [Figma](https://www.figma.com/file/nBKUQx0btfQiqVf30UA6KD/Flask-MVP?node-id=336%3A6344)
  - Related UI feature issue: #11686

**Comment by holantonela** [comment]
We are saying Pill but it may be a variable of our existing `chip` [component](https://metamask.github.io/metamask-storybook/index.html?path=/story/ui-components-ui-chip-chip-stories-js--with-input).

**Comment by rekmarks** [comment]
This was done.
