### ISSUE TITLE
Refactor currency input component and ensure currency toggle persists between settings

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12601]
Replaces part of https://github.com/MetaMask/metamask-extension/issues/12347

### Here is an explanation of the currency settings part of that bug:

1. Turn on the "Show Conversion on Testnets" toggle in advanced settings
2. Go to the send flow
3. Enter an amount and then click the currency switcher
4. Click "Next"
5. On the Confirm screen click "Edit"
6. You will now be on the send screen, but the currency switcher setting will be back to the default

Instead, the currency preference should be what you switched it to originally

Here is a video demonstrating this (ignore parts of the video where hex data is edited):

https://user-images.githubusercontent.com/7499938/137171004-0ee806b1-7a0b-4f99-89c3-e7ebc4351430.mp4

### Notes on fixing this issue

Fixing this is annoyingly complicated because `currency-input.component.js` is convoluted, poorly designed and over-reliant on component state.

We should probably just write that component from scratch, and also use redux to store whether the user has switched the currency display or not.

So here are guidelines for creating a new `currency-input.js` component:

- name  it `currency-input.js`
- it should be a functional component
- the new component should have the exact same behaviour as the current one
- the new component should look exactly the same as the current one, you can copy css as necessary

- the component should receive the following properties:
`hexValue`, type: string, the value to display
`preferredCurrency`, type: string, the symbol of the users currently preferred currency (as set in general settings)
`secondaryCurrency`, type: string, the symbol of the currency that is not primary
`hideSecondary`, type: boolean, whether the conversion from the primary to secondary currency should be hidden and "No conversion rates available" shown instead
`featureSecondary`, type: boolean, whether the top, editable line in the component should be the secondary currency
`conversionRate`, type: number, the rate that can be used to convert the primary to secondary currency
`primarySuffix`, type: string, the suffix that can be shown in line with the primary currency
`secondarySuffix`, type: string, the suffix that can be shown in line with the secondary currency
`onChange`, type: function, a handler for the event of the input changing
`onPreferenceToggle`, type: function, a handler for when the switch/toggle icon is clicked

If the `primaryCurrency` is ETH and `featureSecondary` is false, it should look like:
![Screenshot from 2021-11-05 10-15-35](https://user-images.githubusercontent.com/7499938/140514512-40795ec2-9b0e-4290-a66b-75ffa500eead.png)
 
If the `primaryCurrency` is ETH and `featureSecondary` is true, it should look like:
![Screenshot from 2021-11-05 10-15-40](https://user-images.githubusercontent.com/7499938/140514584-16d34b55-57bd-4a9c-9abd-0706e9541c39.png)

If `hideSecondary` is true, it should look like:
![Screenshot from 2021-11-05 10-16-05](https://user-images.githubusercontent.com/7499938/140514636-d5268882-3525-49b0-b753-05d522cc1a72.png)

- the new component should continue to use the `UnitInput` and `CurrencyDisplay` components as the current component does

- outside this component, a `sendInputCurrencySwitched` property should be stored in redux. This can be done in the `appState` duck
- `sendInputCurrencySwitched` should be toggled when `onPreferenceToggle` is called
- the parent of the new CurrencyInput component should set `featureSecondary` to true if `(useNativeCurrencyAsPrimaryCurrency && sendInputCurrencySwitched) || (!useNativeCurrencyAsPrimaryCurrency && !sendInputCurrencySwitched)` (`useNativeCurrencyAsPrimaryCurrency` is available in state)
- if `featureSecondary` is true but `hideSecondary` is also true, `hideSecondary` should take precedence, and the component should act as if `featureSecondary` is false

**Comment by adonesky1** [comment]
> If hideSecondary is true, it should look like:
(https://github.com/MetaMask/metamask-extension/pull/12813/files#diff-bbcddae95cd7860df2cdc94f98aaecfd70da529ca7fcd1feea0bed8fd738f902R103)

Until this PR (https://github.com/MetaMask/metamask-extension/pull/12410) is merged we still don't show conversionRates on custom (non-testnet) networks if a user has `show fiat on testnets` set to false in preferences.

I feel like we shouldn't say `no conversion rate available` for this case. We should only show it if a conversionRate actually isn't available. Conversion rate can be selected for here: https://github.com/MetaMask/metamask-extension/blob/6d34d85f6ec56752a508f8a1d56e4e7b0669526d/ui/ducks/metamask/metamask.js#L264.

cc @danjm and @filipsekulic
