### ISSUE TITLE
Fix display of hex data when in edit mode on send screen

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#12602]
This replaces part of #12347

### Description of the hex data part of the bug described in that ticket

1. Turn on the "Show Hex Data" toggle in advanced settings
2. Go to the send flow
4. Enter some hex data
5. Click "Next"
6. On the Confirm screen click "Edit"
7. You will now be on the send screen, but the hex data field will be empty

Instead, the hex data field should contain the data you originally set.

Here is a video demonstrating this:

https://user-images.githubusercontent.com/7499938/137171004-0ee806b1-7a0b-4f99-89c3-e7ebc4351430.mp4

### Guidance on fixing this

1. - the hex data that was originally set will still be in state. It can be seen in the `unapprovedTxs` part of state
2. - `ducks/send.js` manages state on the send screen, when in edit mode if you inspect state, you can see a `"draftTransaction"` property which contains data about the transaction being edited
3. - it is possible that this bug is occuring because the `editTransaction` reducer in `ducks/send.js` does not properly set the transaction `data` value
4. - if that is not the case, the bug will still likely be related to the edit specific state management code in `ducks/send.js`

Note: it is possible that a fix according to 3 may also fix https://github.com/MetaMask/metamask-extension/issues/12072

**Comment by draven1099** [comment]
Sir, please help me with this on https://github.com/MetaMask/metamask-extension/issues/12612
