### ISSUE TITLE
Metamask Localhost 8545 not working with etherscan.io and chain ID 1

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-extension#12612]
![image](https://user-images.githubusercontent.com/93768661/140622238-7b26e881-3c7e-4d85-8976-1b016aae8931.png)

**Comment by draven1099** [comment]
please help, It only shows this
![image](https://user-images.githubusercontent.com/93768661/140622273-131ccf45-1fd8-4e17-941b-fcc75dc2d9bd.png)

**Comment by mgouw** [comment]
I also cannot add localhost 8545 back and have tried chainId 1337 and 5777.

**Comment by th0th1** [comment]
are you using firefox?  have you tried with another browser?

**Comment by draven1099** [comment]
I'm using google chrome ser
