### ISSUE TITLE
MM blank in FF 94

### ISSUE THREAD

**Issue by coderised** [MetaMask/metamask-extension#12617]
Metamask shows blank screen in FF 94.
You can see errors in attached image. On the left in my current metamask that is having issues. On the right in new metamask install on fresh user profile. Extension seems to get corrupted somehow.

![metameta](https://user-images.githubusercontent.com/4468367/140759965-64433a49-0c0b-4c46-8bd3-59d08472e52f.jpg)

**Comment by danjm** [comment]
Another instance of #4894, closing in favour of that issue
