### ISSUE TITLE
Received the token but there was a lot of decimals in it.

### ISSUE THREAD

**Issue by ejlocop** [MetaMask/metamask-extension#12620]
**Describe the bug**
so I bought the token via pancakeswap and I did receive 11,948,354.9679 amount of AXIN tokens, but when I checked the browser extension, it has a lot of decimals in it!

**Expected behavior**
should be able to receive the expected amount.

**Screenshots**
pancakeswap
![image](https://user-images.githubusercontent.com/12082880/140795823-99532949-d1d8-4c80-80c3-ed474d8d9bd6.png)

bscscan tx that says I received the token in my wallet
![image](https://user-images.githubusercontent.com/12082880/140795870-c0870ba3-60b8-4b7e-af5d-b4f8a2a7a9ad.png)

what I received in my wallet instead
![image](https://user-images.githubusercontent.com/12082880/140796109-765dd791-32be-4827-9693-d3eddf17fda7.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)
 - MetaMask Version: 10.3.0

**Comment by jacobcantele** [comment]
Could you please share a link to this account on bscscan?
