### ISSUE TITLE
Explore security enhancements made possible by SGX

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1262]
JS access to SGX processors is now possible, we should using it for security.

Uses include: Default to storing keys in secure enclave when available

https://www.npmjs.com/package/secureworker

**Comment by flyswatter** [comment]
Dreaming a bit here:

Within the SGX, you could generate un-exportable account keys with a limited range of signing permissions. This could be nice for when you're signing into a new Dapp for the first time.  At point of first login, you could connect a more secure signing method, like a hardware wallet, and use it to issue a new "persona contract" (like in uPort) where:

- That persona's keys can only be used to sign transactions to the newly designated Dapp.
- That persona's is still owned & recoverable by arbitrary means, like a key held in greater security.
- You could restrict what operations with the specified contract that persona could perform (in an exchange, you might prevent withdrawing to an account other than a more secure one you control).

These kinds of persona-based access permissions were already existing good ideas before the SGX, but before, those permissions would have had to live within a smart contract, greatly increasing the cost of deploying new personas.  Using the SGX, much cheaper, off-chain permissioned personas could be issued to peripheral signers.

**Comment by flyswatter** [comment]
Whoop.  Node.js only.  Not a browser technology.  Looks like we'd need to make MetaMask its own browser, or system extension, to leverage this.  The other Ethereum clients should try to beat us to this. :)

**Comment by kumavis** [comment]
Since there's no browser standard for SGX, this seems mostly dream phase. it would be really cool! Moving the milestone to future release.

**Comment by Gudahtt** [comment]
I'll close this for now since there is no browser standard, so we can't even experiment with this yet.
