### ISSUE TITLE
Metamask disappeared with $350 in transaction

### ISSUE THREAD

**Issue by 3viirgula14** [MetaMask/metamask-extension#12634]
I transferred value to another METAMASK portfolio. In this case, I transferred more than 89000 SPU, but in the other wallet only 83000 arrived. I checked the transaction, and it was divided into 3 parts in BSC Sca. The first part I received, however, the other two parts are still missing...

**Comment by Gudahtt** [comment]
Thanks for the report! Please submit a support request here: https://metamask.zendesk.com/hc/en-us/requests/new

Our support team can help investigate what went wrong.
