### ISSUE TITLE
error from contract returned as string not as object

### ISSUE THREAD

**Issue by MonarthS** [MetaMask/metamask-extension#12646]
Error thrown from contract returned as string, so can not parse specific error:

**contract error**

![image](https://user-images.githubusercontent.com/40236229/141130020-3e8be2c0-78b5-42f0-ab85-67c39a989e38.png)

- as you can see, actual error message from contract is **Unauthorized Access!**, but metamask returned it as string(message + json object).

**other errors**

![image](https://user-images.githubusercontent.com/40236229/141131105-be2997a2-eb14-4c2d-aafd-cadcceb51de8.png)

- other metamask errors are returned as object.

**Expected behavior**

- Should return error as object same as other metamask errors.

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome Version 95.0.4638.69 (Official Build) (x86_64)
 - MetaMask Version: 10.4.1

**Comment by BelfordZ** [comment]
@MonarthS Im having trouble reproducing this issue. From what I can tell, there is a related issue though - errors returned from smart contracts are returned as nested errors the error.message has the real json-rpc error inside of it. 

Any chance you could let me know if you are still running into this, and if so, how i might reproduce the output from the screenshot provided.

Thank you!

**Comment by BelfordZ** [comment]
followup questions:

1. What is sending `{value: { error... } }` ? are we wrapping with value?
2. When the error returned from rpc api is not formatted according to expectation, we could return a better result than wrapping the object in a string
