### ISSUE TITLE
Add ability to copy the "To" address in "Full transaction details"

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#12654]
Hi Frens!

**Describe the bug**
On the approve screen, even inside of full transaction details I am unable to get the full To address.

**Steps to reproduce (REQUIRED)**

1. Go to any "site" that wants you to approve a token.
2. Click on View full transaction details

**Expected behavior**
I am expecting to be able to copy the entire address that I'm approving, but all I get is a truncated value that I'm not able to copy. I would like to be able to copy this to view some additional details about the contract on etherscan for example. 

**Screenshots**
<img width="360" alt="why" src="https://user-images.githubusercontent.com/3885055/141200949-6840f8b5-a6d9-4e9d-ad57-83de927729fc.png">

**Browser details (please complete the following information):**
Firefox 10.4.1

**Comment by jacobcantele** [comment]
Hey Fren! 

I hope you are doing amazingly. This is good feedback. We have a major initiative for UX papercuts right now, so this comes at a perfect time.

**Comment by EHaracic** [comment]
The issue can be reproduced on the MM Testdapp, option:  Approve Tokens
![image](https://user-images.githubusercontent.com/49436614/142402682-91120449-f1a7-4d64-a16e-6f1ed253e093.png)

MM Extension screenshot:
![image](https://user-images.githubusercontent.com/49436614/142402814-246b76ad-64b2-48f7-ad57-c7a5983b90e3.png)

Acceptance criteria: 

- In the "View full transaction details" replace the "To" label with the existing address control (control with option to copy the address to the clipboard), e.g. 
![image](https://user-images.githubusercontent.com/49436614/142403206-6cf5b282-d5b3-4855-8905-1317773c1d22.png)

**Comment by dragana8** [comment]
Solved with https://github.com/MetaMask/metamask-extension/pull/12553
