### ISSUE TITLE
metamask can't find my trezor address

### ISSUE THREAD

**Issue by fili777** [MetaMask/metamask-extension#12670]
I linked a trezor wallet with MM, I deposited some funds, but when I tried to move this funds to another chain and it need to be confirmed by trezor, mozilla firefox got stuck, so I tried to install in google chrome MM, and find the trezor address, but MM cant find this address anymore, it looks like it is lost. 

i didn't use any passphrase, I try so search with mycrypto, findeth, page by page inside myetherwallet, but still lost with my funds. looks like there is a bug between trezor and metamask. 

it is not acceptable to lost funds because MM doesn't work properly with the HW that have been verified

**Comment by danjm** [comment]
closing in favour of https://github.com/MetaMask/metamask-extension/issues/12674
