### ISSUE TITLE
metamask address connection issue 

### ISSUE THREAD

**Issue by reilly110** [MetaMask/metamask-extension#12673]
hi 
issue 1.
  im trying to find solutions to 2 problems for a couple of months and coming up blank 
i am trying to connect my 4 metamask wallets with a ledger on the chrome extension - only 1 wallet has been successfully connected as i cant see other wallet addresses even though i look through 250 address in both options given 
i tried on firefox -doesnt work either -tried a completely fresh metamask with a trezor and ledger on firefox  -my wallet addresses dont show up 
this leads me to believe it is a metamask issue 

issue 2.
 my main wallet which i have successfully connected when i try to import it with secret phrase -this wallet does not show up with others  even thought i created the extra wallets option
i do not have any other secret phrases so im not sure if i imported this wallet separately (have no recollection of doing this)
what is best way to secure this wallet for the future 

thanks in advance

**Comment by danjm** [comment]
Hi,

Thanks for reporting this and sorry that you are experiencing this.

To make sure I understanding correctly, are you saying that when you connect your Ledger, the first address that appears is yours, but the other addresses that you would expect to be there are not?

**Comment by reilly110** [comment]
yes this is correct 1 wallet shows up but my others dont i expect to be there dont
