### ISSUE TITLE
Metamask missed my address

### ISSUE THREAD

**Issue by fili777** [MetaMask/metamask-extension#12674]
Good afternon dear team, i explain my case because i cant find a huge funds for me, and i feel a little bit desperate. 
i created an account in Metamask with Trezor, i send my funds from my account number 1 in Metamask(0x0c2d9758A4349ebB3Bea2fCaf510AAA2c9f56F62), to my account number 2  trezor (0x57d9E810C484E7bc4A7Ed256A4CDFF71196705b1) , and firefox got stuck when i had to confirm a withdraw with metamask and trezor. 
So, when i tried to import the account to google chrome, metamask couldnt find the account inside metamask using my trezor, (i didnt use any passphrase). im trying to find this address with a ledger, but doesnt work neither.  Even i cant find the address using crypto y findeth. 

i contacted with Trezor , and they told me to ask you about what derivation path Metamask was using in the original installation. 

i paste the message from TREZOR:

"Our automated testing says that derived Ethereum addresses do not change between firmware revisions, or at all. This would point to either (a) different seed, (b) different passphrase, or (c) different derivation path selected.
You might start by figuring out what derivation path Metamask was using in the original installation. Metamask doesn't report this, so maybe contact MM support(?) and ask how to extract this information? Then you can set up the same derivation path and find out if this gives the same result.
Also remember that when restoring firmware through Suite, passphrase is enabled by default.
This means that after restore, when reconnecting to Metamask, you will be prompted for a passphrase.
If you didn't use passphrase before, but enter something here, you'll get different addresses"

Here is the lost address:  0x57d9E810C484E7bc4A7Ed256A4CDFF71196705b1

The address is under the Avalanche chain, here we can check the balance: https://avascan.info/blockchain/c/address/0x57d9E810C484E7bc4A7Ed256A4CDFF71196705b1

i hope the Metamask can help me, because is the last chance i have, everyone is trying to tell me, they dont have anything to do, but it was not my mistake. 

Thank you very much.

**Comment by danjm** [comment]
Hi @fili777 

Thanks for reporting this issue and sorry for the trouble it has caused you.

Can you describe the steps you followed when you first created the `0x57d9E810C484E7bc4A7Ed256A4CDFF71196705b1` account?

**Comment by danjm** [comment]
Oh, I see your other issue here https://github.com/MetaMask/metamask-extension/issues/12670

**Comment by danjm** [comment]
> Can you describe the steps you followed when you first created the 0x57d9E810C484E7bc4A7Ed256A4CDFF71196705b1 account?

Some things you could describe:

- which model of Trezor were you using?
- which network were you on when you connected Trezor?
- which versions of MetaMask were you using?
- in both cases (when first on firefox and then later on chrome), did you just follow the standard "Connect Hardware Wallet" steps?

If there is any other information you can share, please do.

**Comment by fili777** [comment]
Archivo adjunto disponible hasta 18 dic 2021
> Some things you could describe:
> 
> which model of Trezor were you using? Im using trezor one
> which network were you on when you connected Trezor?  I was using Avalanche chain. 
> which versions of MetaMask were you using? 14.0 I think so, the older version before 15.0, the most new version. 
> in both cases (when first on firefox and then later on chrome), did you just follow the standard "Connect Hardware Wallet" steps? I used firefox first, but at the moment got stuck I tried to connect the trezor in metamask following the steps, but the address didn’t appear anymore. 

Here I send you the information with the transfer from my metamask account to my metamask-trezor account. 


https://avascan.info/blockchain/c/address/0x57d9E810C484E7bc4A7Ed256A4CDFF71196705b1 <https://avascan.info/blockchain/c/address/0x57d9E810C484E7bc4A7Ed256A4CDFF71196705b1>

Hacer clic para descargar
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAYyZJF-35emY2WqP3JfDLbdyadBCAdSy9A3nZ8fFcXwwWw8JSpD4JPUI%2F%24%7Bf%7D%3Fo%3DAtxXjYPEj8B92_OQcZGIsDrL2g5GuxF1d_jtMojXcyx5%26v%3D1%26x%3D3%26a%3DCAog5mpXS-OBFcGzOWS06I59S_mcV1dWkTlYxEfYEKuwXAwSeBCK6r6b0y8Yivq579wvIgEAKgkC6AMA_0oRfl1SBHJp0EJaBPgk9QhqJnHRjd_ZeVT_FpjR1gvSy1PNR8zLc_DUXI6iVcIbAHI7ArwrUPO7ciaje4QlX6bpaf9yYGtig-xWnl9G0SpA8w01TNT3h1hnKxz1L_rlNg%26e%3D1639837498%26fl%3D%26r%3D298B07D0-8DEC-4471-8F51-9FBBA755ED2C-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D6DBB2DE2-73E5-4590-9F7B-200814F77FFB%26p%3D41%26s%3Dkh9A7JRTvC0iwLtdUR8agMFFu9A&uk=hRVg1UKTUffv1eLR4-u6aQ&f=video_2021-11-12_17-18-00.mp4&sz=21232540>video_2021-11-12_17-18-00.mp4
21.2 MB

**Comment by Feliex13** [comment]
Hi, I have the same problem, I can't find my wallet, I don't know what to do

**Comment by werdnajoc** [comment]
I have the same problem, I can't find my wallet. HELP ME!!

**Comment by werdnajoc** [comment]
mindblowing that the industry's leading wallet still isn't working on supporting it :(
