### ISSUE TITLE
Users sending directly to bridge contracts after adding to address book on confirmation

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#12683]
We added the "add this address to your address book" feature to the confirmation screen to help users recognize when they are interacting with a contract that they've interacted with before. This was modeled after ideas from "pet names", and was also requested by users to help label contracts.

Apparently some users are adding entries for contracts they interact with, and later on the "send" screen when these contracts appear as recommended contracts, they assume they can simply send to those contracts for an automatic bridging, which is incorrect and can lead to loss.

We're already making the address-book recommendation subtler, or possibly hidden by default, since it's a somewhat alarming call to action in a context that doesn't _require_ action, but even then, the send screen will recommend these contracts as recipients. How should we manage that?

### Possible remediations:
- If an address book entry is added on a confirmation with txData (a contract call), flag it as a contract, and do not show it as a recommended recipient on the `send` screen.
- If an address book entry is added on a confirmation with txData (a contract call), flag it as a contract, and if a user tries to send to it, ask if they want to perform the same kind of action as they performed previously (we could even show a list of previously used function names, and make the parameters editable once we have shipped [tx-insight](https://consensys.net/blog/developers/10-consensys-projects-from-cypherpunk-2021/)).

Any other approach ideas?

**Comment by omnat** [comment]
> If an address book entry is added on a confirmation with txData (a contract call), flag it as a contract, and do not show it as a recommended recipient on the send screen.

This sounds good. 
Related conversation on how to flag and organize address book here https://www.figma.com/file/NI7m8KldyGDA1GanSY03fy?node-id=2099:11422#124845504

**Comment by danjm** [comment]
@bschorchit I am assigning to the PS team, but this will require some product and design attention to fully spec out

**Comment by EHaracic** [comment]
@danjm we move this issue to the PendingConsensys column until the pull request https://github.com/MetaMask/controllers/pull/828 will be approved and merged

**Comment by bschorchit** [comment]
There should be actually three possible values for the type property as per [this discussion on slack](https://consensys.slack.com/archives/G01PKA4QC3C/p1654538290317699?thread_ts=1654538051.599589&cid=G01PKA4QC3C): `Externally Owned Account`, `Contract` and `Unknown`.

The following can be better defined by @danjm:
- `Externally Owned Account` -> if get_code returns EOA and nonce > 0
- `Contract` -> if get_code returns contract 
- `Unknown` -> if get_code returns EOA and nonce = 0

Following the proposed solution in the original issue, the scope of this fix would be to `only` show `Externally Owned Account` type addresses as recommended recipients in the send flow. 

Do you think that's a good solution for this, @Gudahtt ? That would still make contract accounts not show up as recommended recipients on the send flow as we cannot differentiate contracts accounts from other contracts, but we're not blocking users from manually inputing it and following through with it. 

In a future iteration, we can explore how to also display contracts and unkown adress' types here, but that will likely require design + usability testing to be figured out (cc: @rachelcope for input here). I'll capture that as an user story for the address book epic we have.

**Comment by bschorchit** [comment]
### **Update** 
We had a quick call to go over this and here are the decisions:
 - To identify wether the contact is a contract, we'll both use Dan F.'s initial suggestion of checking for `txData` on the current and/or previous transactions and we'll also check for `get_code`. If both are true, we'll flag that address as a `contract` and `not` show it as a recommended recipient during the send flow. 

Reasoning behind this decision: by doing this, we will less likely flag smart contract accounts as contracts, which would prevent them from showing up as recommended recipients during the send flow.

@danjm and @Gudahtt, please correct me if I've captured something wrong here from our call.

**Comment by danfinlay** [comment]
Sorry, I just saw this again in my notifications. 

A lot of users are using contract accounts as accounts now, and we hope to make this more common. Are we meaning to to treat contract accounts as less recommended accounts to send to? is there another way to achieve the desired goal?

**Comment by Gudahtt** [comment]
Re-opening, as this has not been completed yet (some dependent code has been merged in core, but there are additional extension changes needed).

**Comment by Gudahtt** [comment]
>Are we meaning to to treat contract accounts as less recommended accounts to send to?

Could you elaborate? I thought we were going to do the opposite here, by attempting to treat contract accounts the same as externally owned accounts.

**Comment by danfinlay** [comment]
oh, then, I miss read. That’s what I think we should do, it’s just the only public comments here seem to imply that we are going to stop recommending sending to contract, which would mean treating contract accounts differently. It sounds like we aren’t doing that, it just isn’t well reflected in this thread.

**Comment by Gudahtt** [comment]
I think it was just confusingly worded, because we used the term "contract" in multiple ways (to mean "any contract" in some places, or to mean "non-account contract" in other places).

The most recent comment does describe a strategy for treating contract accounts as regular accounts:

>To identify wether the contact is a contract, we'll both use Dan F.'s initial suggestion of checking for `txData` on the current and/or previous transactions and we'll also check for `get_code`. If both are true, we'll flag that address as a `contract` and `not` show it as a recommended recipient during the send flow.

It's not a perfect solution, because it might miscategorize contract accounts that the user has made contract interactions with, or it might miscategorize non-account contracts that the user has mistakenly sent ETH to. But it was the best solution we had so far.

**Comment by danfinlay** [comment]
Oh I guess the benefit here is that even when sending to a contract account, you are unlikely to send TX data as a transaction to that contract account. Either you were sending either in which case you have no TX data, or you were sending another asset, in which case you are interacting with a different contract entirely. does this still properly handle the case where someone wants to send a token to a contract account address?

**Comment by Gudahtt** [comment]
Exactly. Yes, we can handle token sends as well.

The edge cases is that there might be some contract-accounts that have additional functionality that uses contract calls. If a user is making a contract call to a contract account, rather than a regular account interaction, we might categorize it as a non-account contract.
