### ISSUE TITLE
Send AVXA to Binance or Kucoin or AVALANCHE WALLET

### ISSUE THREAD

**Issue by guozilialulu** [MetaMask/metamask-extension#12680]
Can someone please advise me on how to send my 1.704 Avax Avalanche which is in my Metamask Smartchain…to my Binance or Kucaoin or to my Avalanche wallet…I cant move the Avax it anywhere. says insuficent ballance even if i try to swap it…can I move it from Metamask smartchain to Metamask Avalance Network? Any hep please as I have tried all parameters.
Thanks

**Comment by jacobcantele** [comment]
Hello, please direct your support requests to community.metamask.io or to the support link inside of your app. Github is not a support forum.
