### ISSUE TITLE
Display of current network causes confusing UX on switch custom network modal. 

### ISSUE THREAD

**Issue by jacobc-eth** [MetaMask/metamask-extension#12691]
While on Binance Smart Chain and being asked to switch my network to FAC Chain (the proprietary chain of Plants vs Undead), I was shown "Binance Smart Chain" at the top of the popup, making me believe that I was switching to BSC at first glance (I was trying to move quickly), but really I'm switching to FAC.

We should remove the current network from the top of this modal and replace with a pattern of

(Current Network) -> (New Network)

Both should be labelled, "Current" and "New"

Design feedback might be needed here.

![Screenshot from 2021-11-12 19-36-14](https://user-images.githubusercontent.com/10467486/141601412-22dd3188-13e8-4057-a7ab-adda10d5614e.png)

**Comment by EHaracic** [comment]
@jacobc-eth @danjm wee need designs for this issue

**Comment by EHaracic** [comment]
@bschorchit FYI we need the design for this issue

**Comment by bschorchit** [comment]
We have the new design ready: [Design file](https://www.figma.com/file/b1YjR0OG4RRQgEChYfwbey/UI-audit?node-id=1070%3A1995)

**Comment by EHaracic** [comment]
Figma design(s): 
Acceptance criteria:
- Redesign the current switch network page according to the Figma design.  
![image](https://user-images.githubusercontent.com/49436614/148776286-53c3dd37-aaae-4ff2-b513-3cd77e4237c7.png)
- If network icons are unavailable show the default network icon: 
https://www.figma.com/file/b1YjR0OG4RRQgEChYfwbey/UI-audit?node-id=1070%3A2103

**Comment by brad-decker** [comment]
@danjm @bschorchit @EHaracic this looks like an update to the switch network confirmation screen rather than a whole new page, this has been implemented using the templating system so it exists in ui/pages/confirmations/templates  -- if anyone needs a crash course in the templating system i am available.

**Comment by EHaracic** [comment]
Thanks @brad-decker we have defined it as the update (_"Redesign the current switch network page"_)
