### ISSUE TITLE
Metamask keeps crashing on Brave Browser - locale problem ?

### ISSUE THREAD

**Issue by bloodbee** [MetaMask/metamask-extension#12695]
**Describe the bug**
If the locale is set to french, the metamask extension keeps crashing - so does the browser - when a transaction is made.

**Steps to reproduce (REQUIRED)**

1. Install Brave browser.
2. Install the metamask extension.
3. Setup your account, and setup the locale to French.
4. Go to any DAPP and try to make a transaction.
5. Accept or reject the transaction - doesn't matter.
6. The metamask extension crashes.

**Expected behavior**
The transaction should be made and the browser shouldn't crash.

**Screenshots**
The error list ⬇️ 
https://user-images.githubusercontent.com/5961929/141614716-7feb96e3-e718-444c-bdc4-203a7237b82a.png
https://user-images.githubusercontent.com/5961929/141614725-fad17c41-15ff-4525-81ce-99c96ee45e9e.png
https://user-images.githubusercontent.com/5961929/141614734-86ee387c-104e-43aa-8269-3002a5cc7a6b.png
https://user-images.githubusercontent.com/5961929/141614746-6cec8a73-3519-4c6b-acc1-58f0793d4d70.png

The specific asm.js warning ⬇️ 
https://user-images.githubusercontent.com/5961929/141614626-5e283993-7dd7-46f0-accb-5bf204f03576.png

The specific Account tracker single call balance fetch error ⬇️ 
https://user-images.githubusercontent.com/5961929/141614819-89f77732-7476-4980-9444-bdfd3f987b1d.png

The specific uncaught (in promise) error ⬇️ 
https://user-images.githubusercontent.com/5961929/141614779-958e5f2f-d0fd-40aa-ae03-883d9409a24a.png

**Browser details (please complete the following information):**
 - OS: Mac OS Big Sur version 11.4
 - Hardware Wallet: None
 - Browser: Version 1.31.87 Chromium: 95.0.4638.54 (Build officiel) (x86_64)
 - MetaMask Version: 10.5.1

**Additional context (Error Messages, etc.)**
Tried with the **English locale**. It does the same.

**Edit:** 
Updated Brave to version 1.31.91 Chromium: 95.0.4638.69 (Build officiel) (x86_64), it keeps crashing

**Comment by danjm** [comment]
I'll note that this does not seem to be happening on chrome. We will have to investigate the issue on Brave directly.

**Comment by bloodbee** [comment]
> I'll note that this does not seem to be happening on chrome. We will have to investigate the issue on Brave directly.

True, I tried it on Chrome Browser and it works fine. Any other Brave's user here ?

**Comment by bloodbee** [comment]
Update :
The issue is fixed in the new brave version. V1.32.106

You can close the issue. Thanks.
