### ISSUE TITLE
Stale State when Switching between Blockchain Networks

### ISSUE THREAD

**Issue by gravelcycles** [MetaMask/metamask-extension#12715]
**Describe the bug**
When switching from 1 blockchain to another (i.e. from `Harmony` to `Arbitrum`), not all state updates. Most notably, the native currency does not update.

**Steps to reproduce (REQUIRED)**

1. Connect to an network whose native currency (used for gas) is not Ethereum. In this example, we will use Harmony
2. Go to https://gmx.io/earn
3. Click `Connect Wallet` and note that a `Switch to Arbitrum` blurb pops up in the bottom right corner. Click on it and switch networks in MM.
<img width="342" alt="Screen Shot 2021-11-15 at 5 36 33 PM" src="https://user-images.githubusercontent.com/1361444/141879890-6119e4d1-7178-4f5f-9921-f4584cfb5926.png">
4. Then try triggering some sort of dapp transaction and notice that the gas currency is still in `ONE` (the native currency of Harmony)

![image](https://user-images.githubusercontent.com/1361444/141880164-92ad3431-d503-4d2f-8fdb-c01bcdc23b97.png)

**Comment by danjm** [comment]
We believe this happens when there is an api error from at least one of the chains involved in the switching. I need to follow up and link this to related tickets
