### ISSUE TITLE
"replacement transaction underpriced"

### ISSUE THREAD

**Issue by IgoresVer** [MetaMask/metamask-extension#12728]
"code":-32000,"message":"replacement transaction underpriced"
getting the issue and error, can't replace a transaction, even with high gas fee.
The required GWEI fee is significantly higher than the current average gas price.
MetaMask Version 10.5.2

**Comment by danjm** [comment]
Would you be able to submit your state logs via our customer support channel?

Here is how you can download state logs: https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-to-download-state-logs

Here is the secure and private way to submit them to MetaMask support: https://metamask.zendesk.com/hc/en-us/requests/new

Then we will be able to investigate this problem effectively

**Comment by IgoresVer** [comment]
Please, tell me the version of the Netmask extension where it doesn't check the transaction price before sending, I will install it and never let it update.
Please, please, please.

**Comment by IgoresVer** [comment]
Dan J Miller, thank you for your advise.
