### ISSUE TITLE
MM not sending tx to ledger live

### ISSUE THREAD

**Issue by tomasz90** [MetaMask/metamask-extension#12744]
**Describtion**
MM not sending transaction to ledger live

**Steps to reproduce**

1. Open MM
2. Open chrome
3. Log in to MM
4. Put computer into sleep mode
5. Wake up computer
6. Go to MM
7. Try to sign any transaction using Ledger

**Expected behavior**
MM sends info to ledger live, then after opening bridge user can sign transaction

**Actual behavior**
MM is not sending tx to ledger live, user can't sing transation. Every time this happen user have to close and repopen chrome.
This is VERY frustrating issue.

**Browser details:**
Chrome, windows 11

**Comment by danjm** [comment]
Hi,

It is recommended that you switch to the WebHID connection method that was shipped with v10.5.0

You can read more here https://consensys.net/blog/metamask/metamask-and-ledger-integration-fixed/?utm_content=187109163&utm_medium=social&utm_source=twitter&hss_channel=tw-3278906401
