### ISSUE TITLE
Metamask infinite loading on transaction confirm

### ISSUE THREAD

**Issue by BrettRosen** [MetaMask/metamask-extension#12753]
Trying to delist an NFT on opensea with ledger wallet (need to sign 5 transactions for 5 price drops), metamask loads infinitely when confirming the first transaction and prompt never comes up to sign on ledger. 

Latest MM version, latest ledger firmware, tried multiple browsers, resetting browser cache, etc.

**Comment by ngthtung** [comment]
I have the same problem

**Comment by AlexJupiter** [comment]
Perhaps related to https://github.com/MetaMask/metamask-extension/issues/13665
