### ISSUE TITLE
Setting search feature - New Search component

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#12760]
User story:  As a user I want to search the settings menu to navigate it easily.
https://www.figma.com/file/BLQYdGJFyhvSf4JtxQQrQj/Search-Settings-Menu?node-id=1%3A3

Task:
Create the search component. Depending on the status the component will looks like:
![image](https://user-images.githubusercontent.com/49436614/142616115-75437155-465c-44c0-8876-5aeba50a20a2.png)
Pending:
![image](https://user-images.githubusercontent.com/49436614/142616989-19e8a7e3-f59f-499e-b562-d04eaa3568de.png)
 Term entered:
![image](https://user-images.githubusercontent.com/49436614/142617075-7648df7b-d9bf-4e15-a819-15ab982dbfb5.png)
No matching result:
![image](https://user-images.githubusercontent.com/49436614/142617118-715e27cc-a716-4249-922d-d545740d0cbd.png)

Task: Implement the search component in all  Settings pages (the header component of the settings component)

Popup view:
![image](https://user-images.githubusercontent.com/49436614/142633639-4287865a-0cc0-46cd-a608-711e8c25f520.png)

Full screen view:
![image](https://user-images.githubusercontent.com/49436614/142632300-76ab1700-65f7-4320-998e-e8fda710c394.png)

Acceptance criteria:
- On entering more than 3 characters in the search textbox, application should return the matching results.
- Search is performed on all settings menu items (names and/or description) by entered term. 
- The match is when the term is found in the menu item name in any place
- Results are return in the drop down as shown on the Figma screenshots
![image](https://user-images.githubusercontent.com/49436614/142616115-75437155-465c-44c0-8876-5aeba50a20a2.png)
- If there are no results the component will looks like:
![image](https://user-images.githubusercontent.com/49436614/142616859-ef9f2223-b4af-48d5-beb7-c1b4ae81dc13.png)
- Clicking on the menu item from the search result, the menu item will be opened.
![image](https://user-images.githubusercontent.com/49436614/142617463-80f943fd-1052-4849-9599-05360b09bb48.png) 
- User will be able to search again without switching the page:
![image](https://user-images.githubusercontent.com/49436614/142617617-03d8f277-a515-4318-a1fe-8955c7d54e61.png)
- On clicking the link: "_Request here_" a new form will be opened
- Search component should be shown on all Settings pages. Probably it is enough to implement it in the Header component.

**Comment by danjm** [comment]
We currently use 'fuse.js' for text based search functionality, it may be usable for this task

**Comment by danjm** [comment]
https://fusejs.io/

**Comment by david0xd** [comment]
Additional acceptance criteria:
- Ensure that new features are covered with unit tests
