### ISSUE TITLE
Setting search feature - Setting component UI updates

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#12761]
User story: As a user I want to search the settings menu to navigate it easily.

Task:
Change a Setting component design.
Settings component design should be changed according to the Figma design (https://www.figma.com/file/BLQYdGJFyhvSf4JtxQQrQj/Search-Settings-Menu?node-id=1%3A3) 

Old Settings component: 
![image](https://user-images.githubusercontent.com/49436614/142619441-32059e25-5396-49da-99ac-45636a7cd797.png)
New: Settings component: 
![image](https://user-images.githubusercontent.com/49436614/142619523-ce3c6882-42ae-451f-8409-dc2fb0a0f857.png)

Acceptance criteria:
- Icons is shown for every top level settings menu item
- The top level menu item description should be removed
- Design all elements according to the Figma designs

Open questions: 
- Should we show the top level menu description anywhere? E.g. to introduce the "info icon" and clicking on the icon the description will be shown in the info dialog.

**Comment by david0xd** [comment]
Descriptions for each menu item should be removed.
As @danjm stated:
`The new designs for Settings (search + redesign ) are approved by design for development. So those descriptions will be removed.`

**Comment by darkwing** [comment]
The icons and text don't seem aligned to my eyes -- they each look like they're on their own level, so to speak.  Could we check dimensions here?
<img width="378" alt="Alignment" src="https://user-images.githubusercontent.com/46655/152596801-f0358758-977b-47b5-8d99-69cd5c846683.png">

**Comment by dragana8** [comment]
@darkwing I've just updated icons according to Figma design updates. All dimensions are according to Figma now.
