### ISSUE TITLE
Funds discrepancy problem

### ISSUE THREAD

**Issue by arghya139** [MetaMask/metamask-extension#12775]
I am mining with minerstat on ethermine and get 0.005 Eth in metamask wallet when threshold reaches. 
Most recent one, yesterday, funds transferred to metamask but its not showing in the extension or the mobile app either. 
But if I open https://wallet.polygon.technology/wallet/ it is showing there, but when I try to transfer funds from there it is giving me error.
![a191bd7a00f474beada928bbb72a44aa](https://user-images.githubusercontent.com/33219231/142720581-14dc9f4f-c3a6-40b7-85d4-d0594aaaaa83.png)

**Comment by darkwing** [comment]
@arghya139 Could you provide the entire error message on the bottom by holding and dragging your mouse right on that screen?
