### ISSUE TITLE
ENS avatar not shown (should I pull request?) 

### ISSUE THREAD

**Issue by actuallymentor** [MetaMask/metamask-extension#12778]
**Describe the bug**

Accounts with an associated ENS avatar do not show avatars. 

**Steps to reproduce (REQUIRED)**

1. Open metamask
2. Account image is not ENS avatar

**Expected behavior**
Account image should display avatar of associated ENS domain. 

**Additional context (Error Messages, etc.)**

Let me know if a PR would be appreciated.

**Comment by darkwing** [comment]
@actuallymentor We're always open to pull requests :)

**Comment by actuallymentor** [comment]
Cool, thanks. I will close this issue and try to make some time!
