### ISSUE TITLE
Metamask not detecting correct network

### ISSUE THREAD

**Issue by jvnord** [MetaMask/metamask-extension#12774]
**Describe the bug**
Web3 provider returns a wrong network when connected to Avalanche C Chain mainnet. 

**Steps to reproduce (REQUIRED)**
web3 - 1.2.11 
web3Modal - ^1.9.2 
walletconnect/web3-provider - ^1.3.1

1. Select Avalanche C-Chain Mainnet network (https://support.avax.network/en/articles/4626956-how-do-i-set-up-metamask-on-avalanche)
2. In JS code, 
 `const provider = await this.web3Modal.connect();
  const web3 = new Web3(provider);
  const network = await this.web3.eth.net.getId();`
3. It returns Network id as **1** even though network id **43114** is selected in Metamask.
4. the Same issue is observed on remix when you connect to Avalanche C-Chain Mainnet. Network id is shown as 1 only.
5. If a user changes the network manually, it provides the correct network id on **chainChanged** event.

**Expected behavior**
It should return network id as 43114. 

**Screenshots**

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: NA
 - Browser: Brave (Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (arm64))
 - MetaMask Version: 10.5.2

**Additional context (Error Messages, etc.)**
I'm not able to figure out whether it's a metamask or web3modal issue. On network change, it provides correct network id and hence I think it could be a metamask issue.

**Comment by kuzudoli** [comment]
I have same problem. Polygon mainnet and testnet working fine but avalanche id not correct. I  checked with metamask network id request and it's showing 1 while connecting avalanche (fuji) testnet.
![image](https://user-images.githubusercontent.com/49621993/144706641-ec51d4f7-2482-4382-bc8c-1e47c1c5cd87.png)

**Comment by parutech** [comment]
Encountered the same issue. This is a huge problem since it breaks every website using MM for Avalanche transactions.

**Comment by jvnord** [comment]
`this.web3.eth.getChainId();`

Using getChainId instead of net.getId resolves the issue. I assumed that for avalache mainnet, network and chain id would be the same.
