### ISSUE TITLE
Metamask Extension can not change network to localhost (Version 10.6.0)

### ISSUE THREAD

**Issue by barhantas** [MetaMask/metamask-extension#12794]
**Describe the bug**
Metamask Extension can not change network to localhost (Version 10.6.0)

**Steps to reproduce (REQUIRED)**

1. Open metamask and try to change network to localhost:8545

**Expected behavior**
I should be able to change network to localhost. It was working with the old versions (ex. version 10.5.2)

**Screenshots**
![image](https://user-images.githubusercontent.com/13484299/142953437-632b3e67-3b6a-4f8b-a56b-65876a6c6878.png)
![image](https://user-images.githubusercontent.com/13484299/142953887-cc203608-a4b6-4bac-be1c-347a839fa9fa.png)

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Chrome Version 96.0.4664.55 (Official Build) (x86_64)
 - MetaMask Version: Version 10.6.0

**Additional context (Error Messages, etc.)**
AssertionError: Unknown Infura provider type "localhost".

**Comment by joejordan** [comment]
I have also experienced this issue on a fresh version of Chrome and installing MetaMask from the store (v10.6.1). I installed version 10.6.2 manually and the localhost network option began working again.

Looks like it was fixed in this PR: https://github.com/MetaMask/metamask-extension/pull/12786
