### ISSUE TITLE
Set up event tracking for Transaction Insights

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#12812]
Events tracking for Transaction Insights table: https://www.notion.so/8d2a097345fe4e8085631539967ac4df?v=30aac72e41d04908a2454411470b1925
 
### 1. Address created in addressbook

1. Goal: have users utilize and create nicknames in addressbook
    1. Clicked on unknown address - property of view: Settings, Send confirmation, Confirm screen, Approve screen
![Screen Shot 2021-11-22 at 7 39 15 PM](https://user-images.githubusercontent.com/6951929/143132002-fef02c05-77e1-4671-9308-96954c842a4f.png)
        
    2. Address edited - property of view: Settings, Send confirmation, Confirm screen, Approve screen
![Screen Shot 2021-11-22 at 7 39 23 PM](https://user-images.githubusercontent.com/6951929/143132105-92ebf9b0-7e24-4a9b-a1aa-87cfc5e44d42.png)
![Screen Shot 2021-11-22 at 7 39 42 PM](https://user-images.githubusercontent.com/6951929/143132116-c28074cb-33ab-405f-8e1a-ae02121026fd.png)

    3. Address created - property of view: Settings, Send confirmation, Confirm screen, Approve screen
![Screen Shot 2021-11-22 at 7 39 29 PM](https://user-images.githubusercontent.com/6951929/143132252-f2317023-be40-4589-8893-e2c2d492eb17.png)
 ![Screen Shot 2021-11-22 at 7 39 52 PM](https://user-images.githubusercontent.com/6951929/143132271-abe65234-1d53-4b60-a7a8-02b5a5cd38f6.png)

### 2. Interacted with Activity

1. Goal: have users gain insights about their transaction activity through the insights flow
    1. Clicked on `Activity` - property of view: Settings, Send confirmation, Confirm screen, Approve screen
![Screen Shot 2021-11-22 at 7 29 37 PM](https://user-images.githubusercontent.com/6951929/143132380-b9574523-d67d-4cfd-b6c9-7c4689a8a6fb.png)
        
    2. Clicked on `Activity log` - property of view: Settings, Send confirmation, Confirm screen, Approve screen
![Screen Shot 2021-11-22 at 7 29 56 PM](https://user-images.githubusercontent.com/6951929/143132488-0f2629e4-3d83-471c-8db6-41ae493ffd2e.png)
        
    3. Clicked on `Transaction data` - property of view: Settings, Send confirmation, Confirm screen, Approve screen. This should also apply to the tab view
![Screen Shot 2021-11-22 at 7 30 16 PM](https://user-images.githubusercontent.com/6951929/143132569-2b031a9a-1e0f-430c-af88-a19448c90f37.png)
       
    4. Clicked on `Hex` - property of view: Settings, Send confirmation, Confirm screen, Approve screen
![Screen Shot 2021-11-22 at 8 13 20 PM](https://user-images.githubusercontent.com/6951929/143132615-0ec9aebc-e6b3-4fae-bcad-07f7290434bc.png)

**Comment by brad-decker** [comment]
@kevinghim do you mind if I split these into two separate issues?

**Comment by bschorchit** [comment]
Closing as we'll be deprecating this feature soon
