### ISSUE TITLE
Automatically assemble all migration files

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1282]
Right now when we add a migration file, we have to manually add it to the migrations index file, which can result in [accidentally forgetting to include a migration](https://github.com/MetaMask/metamask-plugin/pull/1281).  We could eliminate this class of errors by automating this process.

**Comment by whymarrh** [comment]
Fixed by #7016, in a sense—we now have a test case to ensure that this doesn't happen
