### ISSUE TITLE
Update Portuguese (Brazilian) translation

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#12841]
**Describe the bug**
Currently when setting the extension language to Brazilian Portuguese parts of the copy continue in English. 

**Steps to reproduce**

1. Go to 'Settings'
2. Click on 'General'
3. Scroll down to 'Current Language'
4. Choose 'Português (Brazillian)' from the dropdown menu - ps: there's a typo here, should be "Brazilian" instead of "Brazillian", but maybe it would make more sense to change it to "Brasil" which is the country's name in Portuguese

- On approve screen: "Give this site permission to access your ETH?" and "By giving permission you're allowing the following contract to access your funds" is in english
-  On the reveal secret recovery phrase screen: "Secret Recovery Phrase" on top is in english
-  On confirm send transaction: "Estimates gas fee" and also the additional info is in english 
- On Custom Token screen: the warning on scams and security risks is in english
- On initial screen: "Account 1" and "Don't see your token? Refresh list or import tokens" remains in english
- On Import tokens screen: the token detection message is in english
-  On the 3 dot menu from the initial screen: "View account on Etherscan" is in english
- On Account Details screen: "View account on Etherscan" is in english

**Expected behavior**
Copy to be fully translated to Portuguese.

**Screenshots**

<img width="358" alt="Screen Shot 2021-11-24 at 19 09 29" src="https://user-images.githubusercontent.com/34968356/143320317-40eb345b-0dd6-4149-bb2d-f2bd6441f676.png">

<img width="358" alt="Screen Shot 2021-11-24 at 18 48 50" src="https://user-images.githubusercontent.com/34968356/143320421-b7f08fca-796f-4049-b289-e48d96529d4a.png">

<img width="352" alt="Screen Shot 2021-11-24 at 19 04 03" src="https://user-images.githubusercontent.com/34968356/143320401-6678b70b-fd8f-4cb8-b460-411294f42c8f.png">

<img width="354" alt="Screen Shot 2021-11-24 at 18 45 14" src="https://user-images.githubusercontent.com/34968356/143320464-03437538-bdf3-4a90-aa97-906a8be7dbcb.png">

**Browser details:**
 - MetaMask Version: 10.6.1

**Comment by darkwing** [comment]
Thank you for filing @bschorchit !  We'll be updating localizations very very soon!
