### ISSUE TITLE
EIP-2930 access lists not working via api

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#12871]
User Roman Storm says he can’t use access lists with sendTransaction. I swear we support this, any tips on using it?

Allows some gnosis safe users to send txs that are otherwise stuck: https://help.gnosis-safe.io/en/articles/5249851-why-can-t-i-transfer-eth-from-a-contract-into-a-safe

**Comment by rstormsf** [comment]
https://github.com/MetaMask/metamask-extension/issues/12869

**Comment by danfinlay** [comment]
Closing as a duplicate of #11863
