### ISSUE TITLE
No "post" botton in community.metamask.io

### ISSUE THREAD

**Issue by mahdi-ln** [MetaMask/metamask-extension#12878]
There is no "post" botton 
There was no other place to report it. I created my account today without any prior post

**Screenshots**
![image](https://user-images.githubusercontent.com/27496531/143777591-c7a602ac-a3f7-4aeb-aa3f-8e8c5d7d9df1.png)

**Browser details (please complete the following information):**
 - OS: Endeavour OS

**Comment by bschorchit** [comment]
We now show a banner to new users with the requirements needed to post.
