### ISSUE TITLE
Numbers in account names are mis-ordered

### ISSUE THREAD

**Issue by jacobc-eth** [MetaMask/metamask-extension#12885]
**Describe the bug**
When a user views the account list and has many accounts with numbers in them, the numbers are mis-ordered if the numbers exceed 10.

For example, a wallet with 12 accounts will appear like this:

Account 1
**_Account 10
Account 11
Account 12_**
Account 2
Account 3
Account 4
Account 5
Account 6

And so on.

The account list should recognize numbers correctly in this view and order them approprioately.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Have more than 10 accounts with number based suffixes
2. View the account list
3. See mis-ordered accounts.

**Comment by danjm** [comment]
closing in favour of https://github.com/MetaMask/metamask-extension/issues/12960
