### ISSUE TITLE
Create a new screen/page "Add network" in the modal and expanded view

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#12898]
US: As a user I want to be able to add a popular custom network from the custom network switcher modal.
Figma link: https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1%3A3

**Task: Create a new page: "Add network" with the list of predefined popular networks** 
![image](https://user-images.githubusercontent.com/49436614/144037803-4fa9ca19-467a-443e-b0f7-4e88fa1515e3.png)

Acceptance criteria:
- Networks should be listed in alphabetic order in the group
- List of popular  networks are grouped, e.g.  groups are "Custom networks", Test networks"
- Add buttons (will open another page in the flow: "Add network details/confirmation" https://github.com/MetaMask/metamask-extension/issues/12899). Replace Add word with the + icon
- Back button on the top will go back to previous page
- "Add a network manually" option will open existing page in a full view, the page is shown below:
![image](https://user-images.githubusercontent.com/49436614/144053907-98ce7761-68ad-456b-b3d8-eb02c74b94d1.png)

- "Only interact with entities you trust." Learn more link - Link takes you to an article explaining the risks involved in interacting with different networks
- List of the custom networks are from the json file, Dan will provide the json file =

**Task: Create a new page: "Add custom network" in the full screen view**
Figma link: https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1%3A3

Acceptance criteria:
- The page according to the figma design:
![image](https://user-images.githubusercontent.com/49436614/144059540-c6548cf8-46fb-420b-aca4-f166c7dd67ec.png)

- Networks should be listed in alphabetic order
- List of networks are grouped, e.g. groups are "Custom networks", Test networks"
- "+ button" will open another page in the flow as a modal window. The page is under development, https://github.com/MetaMask/metamask-extension/issues/12899 the mockup:
![image](https://user-images.githubusercontent.com/49436614/144438619-1a136d4f-762e-4399-b403-9ab64e623cd5.png)

- "Add a network manually" option will open existing page in a full view, page mockup:
![image](https://user-images.githubusercontent.com/49436614/144438138-5e0522bc-c376-4cf7-9572-0ae91e24b801.png)

**Comment by EHaracic** [comment]
**Open questions:**
- In the expanded view it is not clear the Next button  functionality
- Cancel button will close the "Add network" screen and return  to the list of networks?

**Comment by bschorchit** [comment]
Heey, as I mentioned in one of our calls, we were doing some minor design adjustments and user testing that resulted in two small changes for this page:

1. Update copy to "Add from a list of popular networks or add a network manually. Only interact with the entities you trust.";
2. Include new tool tip icon for all networks which RPC url doesn't belong to Infura as it's on this [final design file](https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1697%3A17291).

I've also added the list of all networks that are going to be included in this with their respective info on [Notion](https://www.notion.so/I-want-to-be-able-to-add-a-popular-custom-network-from-the-custom-network-switcher-modal-7f8c0ae131ea443694396bbf1a36aa1e). 

cc: @EHaracic

**Comment by EHaracic** [comment]
Based on the  latest inputs, additional acceptance criteria's: 

### Figma/Notion  link
Figma: https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1697%3A17291
Notion: https://www.notion.so/I-want-to-be-able-to-add-a-popular-custom-network-from-the-custom-network-switcher-modal-7f8c0ae131ea443694396bbf1a36aa1e

### Acceptance criteria
- Update text at he top of the screen to "**Add from a list of popular networks or add a network manually. Only interact with the entities you trust.**";
- Include new tool tip icon for all networks which RPC url doesn't belong to Infura as it's on this [final design file](https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1697%3A17291).

Figma screenshot:
![image](https://user-images.githubusercontent.com/49436614/154270808-82f65d25-b2d6-4fd1-84b0-b0a4ae0ebc51.png)
