### ISSUE TITLE
Invalid gas params do not disable the submit button

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#1289]
This used to be expected behavior but now reflects behavior where the button is always enabled.

**Comment by flyswatter** [comment]
I don't understand the issue body.  Could you describe the behavior and the desired behavior?

**Comment by flyswatter** [comment]
Pretty sure Kevin fixed this.

**Comment by tmashuang** [comment]
https://github.com/MetaMask/metamask-extension/blob/2489caddd4f42339a98cf0be767ad9cd003ad40c/ui/app/components/pending-tx.js#L324-L330
