### ISSUE TITLE
Metamask browser displays wrong svg colors

### ISSUE THREAD

**Issue by axmad22** [MetaMask/metamask-extension#12910]
SVG colors are wrong when using the browser in metamask on mobile with night-mode on , also some masking/clippings does not work.  Is this normal.

**Steps to reproduce (REQUIRED)**
Visit a site with svg using metamask mobile browser example cryptokitties

 - OS: Mobile pocophone f1 android 10 
 - Browser: Metamask mobile browser
 - MetaMask Version: 3.6.0

**Comment by danjm** [comment]
Thanks! Can you submit this in the mobile repo? https://github.com/MetaMask/metamask-mobile/issues

cc @mobularay
