### ISSUE TITLE
Ledger could not use after upgrade to v10.6.4

### ISSUE THREAD

**Issue by lolieatapple** [MetaMask/metamask-extension#12914]
**Describe the bug**
Ledger could not use any more after upgrade to v10.6.4

**Steps to reproduce (REQUIRED)**
Send any transaction with Ledger webHID mode.

**Expected behavior**
work.

**Screenshots**
![image](https://user-images.githubusercontent.com/54833180/144166019-7648dbd2-5962-4cb1-a877-49a4ea97286d.png)

**Browser details (please complete the following information):**
 - OS:  OS X
 - Hardware Wallet: Ledger Nano S Firmware version 2.0.0
 - Browser: Chrome Version 96.0.4664.55 (Official Build) (arm64)
 - MetaMask Version: 10.6.4

**Additional context (Error Messages, etc.)**

**Comment by lolieatapple** [comment]
I found a way to resovle it. Just switch to Ledger Live in setting and then switch back to webHID again.

**Comment by danjm** [comment]
Thanks for the report

**Comment by Tityz** [comment]
Bug

**Comment by essefff5** [comment]
> **Describe the bug** Ledger could not use any more after upgrade to v10.6.4
> 
> **Steps to reproduce (REQUIRED)** Send any transaction with Ledger webHID mode.
> 
> **Expected behavior** work.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/54833180/144166019-7648dbd2-5962-4cb1-a877-49a4ea97286d.png)
> 
> **Browser details (please complete the following information):**
> 
> * OS:  OS X
> * Hardware Wallet: Ledger Nano S Firmware version 2.0.0
> * Browser: Chrome Version 96.0.4664.55 (Official Build) (arm64)
> * MetaMask Version: 10.6.4
> 
> **Additional context (Error Messages, etc.)** Add any other context about the problem here.

hello, i am having this issue and cannot resolve.  i do not see where to add ledger live in settings and cannot open wallet in metamask either. please help if possible

**Comment by AlexJupiter** [comment]
@essefff5 you can change your preferred Ledger connection type by going to Settings > Advanced. Would you be able to try the solution suggested above and let me know if that works please? Thank you! ![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/5504ec40-0239-4169-a27a-2b5e65c885f0)
