### ISSUE TITLE
enable sharding of seed word

### ISSUE THREAD

**Issue by wanderer** [MetaMask/metamask-extension#1292]
using [Shamir's threshold secret sharing scheme](https://www.npmjs.com/package/secrets.js) it would be nice to be able to split my seed pharse in to N pieces. Then I could give those N pieces to trusted friends. In case of an unfortunate event, M (where M < N) of my friends could come together and resemble my seed with M pieces.

**Comment by flyswatter** [comment]
That's awesome. I just [tried real quick](https://runkit.com/58dc81915296900014c19274/58dc81915296900014c19275/branches/master), and it seems to work as advertised.  We could totally restore a vault with this.

One thing I haven't seen yet is a seed-to-mnemonic function, do you know of one?

**Comment by wanderer** [comment]
> seed-to-mnemonic?

@flyswatter isn't the seed a mnemonic?

**Comment by flyswatter** [comment]
The example I posted shows what we do to get the seed *from* the mnemonic. I don't actually know their relationship that well. It probably goes both ways easily, but I don't really know.  I'll check the source...

**Comment by flyswatter** [comment]
Nope, looks like there is a use of the `pbkdf2` hashing algorithm to derive the actual seed material from the mnemonic phrase.

https://github.com/bitcoinjs/bip39/blob/master/index.js#L23

**Comment by flyswatter** [comment]
This just means that while the multi-key system would be capable of recovering the vault, it would not be capable of recovering the original singular mnemonic.  Which is probably a good thing, now that I think about it?  Prevents reassembling the one true ring, in a way?

**Comment by flyswatter** [comment]
Meh, I don't actually see a huge benefit.  It's just a small downside.  Still a super cool export format.

**Comment by flyswatter** [comment]
The real question is:

Do we try to fit this into the current UI, or do we wait for the new UI, for which we are just now onboarding the new designer?

**Comment by leafcutterant** [comment]
Ian Coleman already created a tool ([shamir39](https://github.com/iancoleman/shamir39)) that takes a bip39 seed, and breaks it into N Shamir secrets which are *also* encoded as bip39 seeds and can have an arbitrary reconstruction threshold M. You can try it [here](https://iancoleman.io/shamir39/).

It's a very undervalued tool. And it's either something that Metamask shouldn't bother implementing, or it should because it would be cool to have another implementation of it which is geared towards secure and convenient consumer use.

**Comment by frankiebee** [comment]
> Hey, frankie!
>I think there is a super interesting moment in metamask where we could prototype something experimental and interesting during the metamask setup here at step 6 of the process....
>To be totally upfront we're shopping around for partners from the ethereum community that we can do some exploratory impactful experiements as part of our grant from the Ethereum Foundation. We're currently half way through and have hit all the milestones from 3 months and are in the process of setting up the milestones for the next 3 months.
>EF have expressed they are interested in these experiements and have declared that it's likely that they will actually be focusing their efforts/funding on scaling as a priority. This being the case we're hoping that some impactful experiements of integrations will help our case in proposing for some more funding.
>Specifically what I mean by integration here is an opportunity to figrue out if there are other ways of backing up the seed amongst peers using the dark crystal patterns / existing protocols...


ssb message id: %p2zJ7HnBaEC+ZA4NGdSUbLWIyEn1EJyYNZ4euOESKqM=.sha256

**Comment by frankiebee** [comment]
closing in favor of #6308
