### ISSUE TITLE
When connected HW is not the right one, no error is displayed and tx silently fails

### ISSUE THREAD

**Issue by KProjectOffical** [MetaMask/metamask-extension#12937]
**Describe the bug**

When connected HW, for instance Ledger Nano X or S, whatever, is not the right one, no error is displayed and tx silently fails.
If the imported Ledger account on Metamask is not matching the connected Ledger HW, TX fails without an error message and makes me wonder why.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Import a Ledger account from one HW, say Ledger A
2. Disconnect Ledger A
3. Connect another HW, say Ledger B
4. Try to approve a TX with the imported account.
5. nothing happens, not even an error message

**Expected behavior**
I would expect a message like "Account not found in the current connected Ledger" or something like that.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: macOS 11.6 (20G165)
 - Hardware Wallet: Ledger S or X latest Firmware 2.0.1
 - Browser: Chrome 96.0.4664.55 (Build officiel) (x86_64)
 - MetaMask Version: 10.6.4

**Comment by danjm** [comment]
Thanks for reporting this
