### ISSUE TITLE
The Version 10.6.4 ( Extension for Chrome and Firefox) export seed phrases Wrong

### ISSUE THREAD

**Issue by ssing2** [MetaMask/metamask-extension#12941]
**Describe the bug**
 I have severalaccounts in one extension, I export the seed phrase one by one, but  got the same  seed phrase !

**Steps to reproduce (REQUIRED)**

1. install the new version Chrome( version 96.0.4664.45 , 64-bit) , Metamask extension ( version: 10.6.4 ) ;
2. Create 5 accounts in the metamask extension;
3.  select the accounts one by one , Click  "Settings" ==> Security&Privacy ==> Reveal Secret Recovery Phrase ==>(enter password" ==>next , got the Seed phrase ;
4.  The first seed phrase of the 1st account is correct ;
     The seed phrase of  2nd -5th are the same as the 1st account.

**Expected behavior**
Each account should have his own seed phrase ? :) 

**Screenshots**
not needed

**Browser details (please complete the following information):**
 - OS: [ Windows]
 版本	Windows 10 家庭中文版
版本号	20H2
安装日期	‎2021-‎05-‎15
操作系统内部版本	19042.1348
序列号	INVALID
体验	Windows Feature Experience Pack 120.2212.3920.0

 - Browser: 
 [e.g. Chrome Version version 96.0.4664.45 , 64-bit , 
 - MetaMask Version: [10.6.4]

**Additional context (Error Messages, etc.)**
If you need more details, contact  ssing2011#126.com

**Comment by zorrosword** [comment]
One metamask extension instance has one seed phrase；
Each account should have his own private key；
Seed phrase is used to generate the private keys of all accounts.

**Comment by danjm** [comment]
@zorrosword Is correct. There is only one seed phrase that generates all your accounts. If you import that seed phrases into another wallet or another installation of MetaMask, you can create all the same accounts.

**Comment by ssing2** [comment]
Thnaks very much!

**Comment by cryptomc** [comment]
@zorrosword
Correct, except in the case of imported accounts. In that case they have their own seed phrase independent of the the seed phrase used for the main account
