### ISSUE TITLE
Implement Network specific insufficient currency warning

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#12965]
**User Story**
As a new user, I'd like to see a reminder letting me know that I am not holding any balance of the gas token for whichever respective network I'm in, and a link within that reminder explaining what gas fees are and how they work

Figma mockups: https://www.figma.com/file/BU5iPP4cSDp7bq3FUGaEKq/Insufficient-funds-warning?node-id=0%3A1

**Tasks:**
- Develop a network specific warning message component as shown on the mockup below
![image](https://user-images.githubusercontent.com/49436614/144613512-b0ea2f2c-0f17-4830-92c5-69df917057b4.png)
H**INT:** For the warning message, you can use this component: metamask-extension/ui/components/ui/actionable-message/actionable-message.js
- Implement a new warning message component on the MM extension screens: "Send flow / Confirmation" screen and "Give permissions" screens.  Hint: Give permission screen can be opened using the MM TestDapp option: "Approve token"
The screens with the new warning message are shown on the mockups below: 
![image](https://user-images.githubusercontent.com/49436614/144808992-4cce81d7-63f8-4d50-ad18-32f75241f937.png)

**Acceptance criteria**
- The warning message is network specific showing the network name and main token name depending on the current network. The two different messages for the Eth main net and MATIC networks are shown on the mockups below:
![image](https://user-images.githubusercontent.com/49436614/144619140-9673481e-b513-4767-a58f-8e0a29f316d3.png)
![image](https://user-images.githubusercontent.com/49436614/144619274-570bbd1d-0b19-4ee1-b65c-c7daff1a80f9.png)

- When users do not have enough ETH on **Ethereum network**, we prompt users to “Buy ETH” by providing a clickable link, On the mockup below (in the wanring message) the “Buy ETH” is clickable link :
![image](https://user-images.githubusercontent.com/49436614/144617950-113b52bb-0f40-4770-8db0-5edb56c353f6.png)
Note: There is no such option in the warning messages on other networks

-The new warning message will replace existing message: "Insufficient funds.", which is shown on the screenshot below:
![image](https://user-images.githubusercontent.com/49436614/144813295-4148ced8-2baa-4b19-b573-ef1203efdfd0.png)

- For the clickable link, let's see if we can just open the "Buy" modal, on this page
![image](https://user-images.githubusercontent.com/49436614/144847798-bd962871-478f-43b8-b2b0-93e16e9d7310.png)
You should just be able to use the same redux action that is used to open it on the main screen.

**Comment by danjm** [comment]
For the warning message, you can use this component: `metamask-extension/ui/components/ui/actionable-message/actionable-message.js`

**Comment by danjm** [comment]
For the clickable link, let's see if we can just open the "Buy" modal, on this page

**Comment by bschorchit** [comment]
> When users do not have enough ETH on Ethereum network, we prompt users to “Buy ETH” by providing a clickable link, On the mockup below (in the wanring message) the “Buy ETH” is clickable link 

If this is still being worked on, could we do it not only for Ethereum Mainnet, but for all networks where the "buy button" is enabled? With version 10.10.0 those are Ethereum Mainnet, Polygon, Avalanche, Celo and Fantom. 
cc: @EHaracic
