### ISSUE TITLE
Reduce EIP-1559 v2 gas fee refresh animation

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#12976]
This issue aims to reduce EIP-1559 gas fee refresh animation in order to unblock users from submitting transactions while fees are refreshing, and reduce anxiety caused by the frequent animation.

- [x] remove overall screen refresh animation from the transaction confirmation, gas edit, and advanced edit screens
- [x] just refresh  gas estimates. Refresh animation of the estimates should stay the same. from each of those screens (noted in red on the screenshots below)
- [x] remove disabling of `confirm` and `save` buttons while gas estimates are refreshed
![Screen Shot 2021-12-03 at 7 15 58 PM](https://user-images.githubusercontent.com/6951929/144688801-d842bf69-f558-43ab-92cd-8fa46ed0829e.png)

![Screen Shot 2021-12-03 at 7 13 51 PM](https://user-images.githubusercontent.com/6951929/144688805-5b7f1708-1f5f-47b9-87a7-ce37ae6807a2.png)

![Screen Shot 2021-12-03 at 7 14 01 PM](https://user-images.githubusercontent.com/6951929/144882880-e8b33aaf-ff0f-4a31-a66c-8ec9daf050cf.png)

**Comment by jpuri** [comment]
Hey @kevinghim : I think we should not update value sin inputs in advance gas modal when new estimates are fetched.

**Comment by jpuri** [comment]
Hi @kevinghim: I am wondering if this can cause bug:

> remove disabling of confirm and save buttons while gas estimates are refreshed

Consider scenario when user selected an estimate level and went ahead to confirm, but while he was confirming the estimate changes and he ends up creating transaction with new gas fee.

**Comment by kevinghim** [comment]
Per our standup today, we shouldn’t disable the submit button. The transaction might submit with the old values. Disable buttons only on confirm transaction.

> Hi @kevinghim: I am wondering if this can cause bug:
> 
> > remove disabling of confirm and save buttons while gas estimates are refreshed
> 
> Consider scenario when user selected an estimate level and went ahead to confirm, but while he was confirming the estimate changes and he ends up creating transaction with new gas fee.
> 
> One thing is that user can sense from blinking values that estimate is refreshing.
