### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#12979]
**Describe the bug**
During the building process with `yarn dist` I get 5 Warnings due to the use of "/" for division in .scss files. The issue is explained here:
https://github.com/twbs/bootstrap/issues/34051

**Steps to reproduce**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Clone the repo
2. Run `yarn setup`
2. Run `yarn dist`

**Expected behavior**
Clean build without errors and warnings.

**Screenshots**
Warning Example 1:
![image](https://user-images.githubusercontent.com/54408225/144705071-7f44b0d0-e6a3-4ad4-8e42-e07aa0fea58c.png)
Code affected (lines 6 & 7)
![image](https://user-images.githubusercontent.com/54408225/144705064-b7038274-fe1c-45ed-b8ba-d5d4d987ab5f.png)

Affected files & modules:
- node_modules/@fortawesome/fontawesome-free/scss/_variables.scss 12:25
- node_modules/@fortawesome/fontawesome-free/scss/_larger.scss 6:15
- node_modules/@fortawesome/fontawesome-free/scss/_larger.scss 7:17
- node_modules/@fortawesome/fontawesome-free/scss/_list.scss 6:16
- ui/css/utilities/_colors.scss

**Browser / OS details**
 - Building on Unix

**Comment by zorrosword** [comment]
same issue，how can these warnings be avoided？not only the code of metamask but also dependencies.

**Comment by seaona** [comment]
The suggested solution is to use `math.div(a, b)`. Unfortunately, I've tried to update all the divisions for the math.div method but seems that sass does not support it, so I'm getting errors.

I was reading about the issue and it seems it's not solved. Other projects overcome the issue using workarounds like this - see[ Bootstrap workaround](https://github.com/twbs/bootstrap/pull/34386/files#diff-de6111a37eb67d027961043ce738e80a3ac4ad61a6e7704d35cb3168369cba01):
![image](https://user-images.githubusercontent.com/54408225/144995196-3f8e304d-3c7c-4bf4-a11e-54b5b2af513b.png)

![image](https://user-images.githubusercontent.com/54408225/144995550-4040e61c-428a-4192-ad2c-226ed0e68d10.png)

But that's not really fixing the problem, just avoiding it.

**Comment by Gudahtt** [comment]
Thanks for the report! The multiplication workaround seems OK to me. I'm surprised to hear that Math.div doesn't work though :thinking: 

The bigger problem right now is the warnings from FontAwesome. There's a tracking issue for that here: https://github.com/FortAwesome/Font-Awesome/issues/18371
It seems that they have a solution, but they haven't backported it yet to the free package that we're using.
