### ISSUE TITLE
default test networks not showing on firefox

### ISSUE THREAD

**Issue by MonarthS** [MetaMask/metamask-extension#12982]
**Describe the bug**
default test network not showing on switch network popup on firefox. Also can't add any testnet, because it says chain id is already used.

**Steps to reproduce**
Open Metamask on firefox and try to switch network.

**Expected behavior**
Should show all test networks(default).

**Screenshots**
![image](https://user-images.githubusercontent.com/40236229/144843041-98dc3e7d-dd24-4cdd-ab38-5cfc7417bf77.png)

**Browser details:**
- OS: OS X 10.14.6
- Browser: Firefox Browser 71.0 (64-bit)
- MetaMask Version: 10.6.4

**Comment by danjm** [comment]
Go in to Settings > Advanced and turn on this setting:

![Screenshot from 2021-12-07 01-33-23](https://user-images.githubusercontent.com/7499938/144969642-323c4884-7ecc-4b5a-bdce-808eb1158c5f.png)

**Comment by danjm** [comment]
There should have been a link in the network dropdown that looked like this:

![Screenshot from 2021-12-07 01-33-12](https://user-images.githubusercontent.com/7499938/144969699-b2c6f84e-fbf8-4f26-82ec-622701f7d48e.png)

Did you dismiss it by any chance?

**Comment by MonarthS** [comment]
I didn't dismissed, but working fine with latest version(10.7.0).
