### ISSUE TITLE
Integrate into Brave

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1301]
Brave [wrote a blog post on integrating extensions](https://blog.brave.com/loading-chrome-extensions-in-brave/), it's fairly straightforward!

**Comment by flyswatter** [comment]
Blocked by Brave's lack of good extension debugging tools.

**Comment by flyswatter** [comment]
Brave has added an issue just for our extension, and is tracking each API that we use that they need to implement!  They even caught a deprecated API that we're calling!:

https://github.com/brave/browser-laptop/issues/8671

**Comment by bneiluj** [comment]
@danfinlay Any plan to integrate Metamask plugin into Brave extension UI for massive adoption ?

**Comment by danfinlay** [comment]
@bneiluj I'm not sure what you're asking, but we're actively working with Brave, exploring what might work. Not sure that guarantees "massive adoption".

**Comment by bneiluj** [comment]
@danfinlay A Metamask "Plug & Play" extension from Brave Extensions interface which is easier for people than cloning Brave’s browser-laptop repo and then get Metamask extension from the unique ID. 

<img width="1440" alt="screen shot 2017-10-08 at 11 35 14" src="https://user-images.githubusercontent.com/3680497/31331380-f3b832c0-acd9-11e7-8f08-5dcaf75ee47b.png">

**Comment by danfinlay** [comment]
@bneiluj I don't know if you saw above, but Brave is actively trying to do exactly this:

> brave/browser-laptop#8671

We're waiting for them to implement all the APIs that we use.

**Comment by bneiluj** [comment]
@danfinlay thanks a lot. 
Looks like Brave has just registered MetamaskID into their components: [https://github.com/brave/browser-laptop/commit/3cde4312973b52d36d7e914d689312cc52385cc7](https://github.com/brave/browser-laptop/commit/3cde4312973b52d36d7e914d689312cc52385cc7)

**Comment by danfinlay** [comment]
This has shipped, you just have to enable experimental extensions for the moment!

**Comment by jhabdas** [comment]
> This has shipped, you just have to enable experimental extensions for the moment!

Works on my machine without enabling experimental extensions. Brave v0.19.53

**Comment by pingram3541** [comment]
It's no where to be found in the Brave extensions.  How are we supposed to use MM w/ Brave again?

**Comment by danfinlay** [comment]
Either under "Extensions" in the "Preferences" section, or when visiting a Dapp that requests web3, it will be suggested automatically. You may have an outdated copy of Brave?

**Comment by pingram3541** [comment]
Yep that was it.  I installed via snap which I don't use very frequently and something in the sanp documentation led me to believe it updates apps automatically.  Then I got an error when trying to execute: `snap refresh brave` and was forced to restart the snapd service.

I was v18... and now v20... and I found the newly added MetaMask capability thank you!
