### ISSUE TITLE
Recipient select box closes pop-up

### ISSUE THREAD

**Issue by davebryson** [MetaMask/metamask-extension#1302]
Metamask 3.5.2
Google Chrome extension
OS X

Selecting a recipient from the "Recipient Address" drop select box (in the send view) closes the metamask pop-up.  I have to manually paste the address.

**Comment by Zanibas** [comment]
This is an OSX-specific issue, we're still investigating on how to proceed with this.

**Comment by flyswatter** [comment]
We need to report this to Chrome, then we can mark it blocked.

**Comment by Zanibas** [comment]
Submitted; now we wait.
https://bugs.chromium.org/p/chromium/issues/detail?id=721449#

**Comment by tmashuang** [comment]
Closing old issues, issue seems to be fixed.
