### ISSUE TITLE
Develop method for getting the network native/base token  symbol

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#13034]
**User Story**
As a user, I want to have an information about the network native token symbol and/or anme 

**Task(s)**
- Create a method which will return the network native/base token/currency symbol (and name) for given networkid

**Acceptance criteria**
- Method should be based on query the external json file: https://chainid.network/chains.json
- As reference use the code: ebec81d

**Comment by adonesky1** [comment]
@EHaracic before you start. working on this I have a PR that begins this work: https://github.com/MetaMask/metamask-extension/pull/12431

**Comment by EHaracic** [comment]
Thanks @adonesky1! We will wait for it.

**Comment by bschorchit** [comment]
@EHaracic do you remember what this method was going to be used for?

**Comment by EHaracic** [comment]
@bschorchit While  working on one of our issues, we have found that it will be useful for the users that we check the entered token symbol on the add networks screen by querying   the external json file: _https://chainid.network/chains.json_. for the proper token symbol. 

Since Alex D. did it on the issue: https://github.com/MetaMask/metamask-extension/pull/12431 we can close this issue.
