### ISSUE TITLE
Metamask doesn't show msg.value specified in Remix browser

### ISSUE THREAD

**Issue by davebryson** [MetaMask/metamask-extension#1303]
Metamask 3.5.2
Google Chrome extension
OS X

When calling a contract and specifying a msg.value (in wei) for that transaction through the Remix (solidity browser) interface, Metamask's transaction confirmation doesn't reflect that value.  It always shows `0`

**Comment by flyswatter** [comment]
Hi, sorry for the slow reply, could you be more specific? What lets you edit "msg.value"? Is a msg here the same as a tx?

**Comment by flyswatter** [comment]
Ok confirmed that sounds like what this is, we'll try to look at this sooner.

**Comment by anishmuthali** [comment]
I have the same issue. When trying to initiate a transfer between two accounts using a solidity contract, the ether value always shows up as 0. I'm using the default files that comes with webpack truffle and the default webpage that you get when you run `npm dev run`. I set the ether transfer value of 1 and try to transfer from one account to another on a test network. Not sure if these two issues are related, though. The transaction works, and the gas cost is deducted from my account, but the manually entered ether value is not reflected.
![image](https://user-images.githubusercontent.com/14606742/28378958-a9b88250-6ccf-11e7-8307-8f763f5b3218.png)
This is the code I have for sending the coin:
`function sendCoin(address receiver, uint amount) returns(bool sufficient) {
		if (balances[msg.sender] < amount) return false;
		balances[msg.sender] -= amount;
		balances[receiver] += amount;
		Transfer(msg.sender, receiver, amount);
		return true;
	}`
Transfer, in this case, is an event which is as follows:
`event Transfer(address indexed _from, address indexed _to, uint256 _value);`

**Comment by anishmuthali** [comment]
Here is my whole code:
```
pragma solidity ^0.4.4;

import "./ConvertLib.sol";

// This is just a simple example of a coin-like contract.
// It is not standards compatible and cannot be expected to talk to other
// coin/token contracts. If you want to create a standards-compliant
// token, see: https://github.com/ConsenSys/Tokens. Cheers!

contract MetaCoin {
	mapping (address => uint) balances;

	event Transfer(address indexed _from, address indexed _to, uint256 _value);

	function MetaCoin() {
		balances[tx.origin] = 10000;
	}

	function sendCoin(address receiver, uint amount) returns(bool sufficient) {
		if (balances[msg.sender] < amount) return false;
		balances[msg.sender] -= amount;
		balances[receiver] += amount;
		Transfer(msg.sender, receiver, amount);
		return true;
	}

	function getBalanceInEth(address addr) returns(uint){
		return ConvertLib.convert(getBalance(addr),2);
	}

	function getBalance(address addr) returns(uint) {
		return balances[addr];
	}
}
```

**Comment by kumavis** [comment]
@anishmuthali `value` in the metamask tx conf screen is ether value - it does not show any special token info yet

**Comment by kumavis** [comment]
@davebryson sounds like remix is failing to read your value information
we display the information that we get from the dapp

**Comment by thomasehlke** [comment]
I thought I was having a similar issue, but turns out I was just sending too small of an amount of Ether. As Metamask displays 6 decimals.

Try sending the value in 'finney' instead of 'wei', or increasing the amount sent.
