### ISSUE TITLE
Unable to install Metamask on Brave

### ISSUE THREAD

**Issue by blabno** [MetaMask/metamask-extension#13032]
**Describe the bug**
Unable to install Metamask extension from chrome webstore using Brave browse.

**Steps to reproduce (REQUIRED)**

1. Open Brave browser
2. Go to https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn
3. Click on `Add to Brave`
4. See error `Access denied.`

**Expected behavior**
Extension should get installed

**Screenshots**
![Desktop-screenshot](https://user-images.githubusercontent.com/431064/145391918-b166b644-b0a3-49b4-9dfa-24f91830ffce.png)

**Browser details (please complete the following information):**
 - OS: Linux
 - Hardware Wallet: none
 - Browser: Brave Version 1.25.62 Chromium: 90.0.4430.212 (Official Build) unknown (64-bit)
 - MetaMask Version:

**Comment by vitalwarley** [comment]
@blabno, I had the same problem until I updated to Brave Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit) -- latest release on Arch Linux.
