### ISSUE TITLE
Difference between number of coins in BSC and Metamask wallet

### ISSUE THREAD

**Issue by mareean3** [MetaMask/metamask-extension#13030]
The number of coins shown in my Metamask wallet are different from the number for the same account in BSCan.

Please see the wallet with 0x3Fc0d7804feb1683a82BC132187aDD52bf87Cf1c

![image](https://user-images.githubusercontent.com/58181824/145321287-f25ce393-3823-4467-9b43-b85bf8eb5af0.png)
![image](https://user-images.githubusercontent.com/58181824/145322069-43b86396-892c-4dda-b498-b96772998e6a.png)

Two different platforms and two different amounts.
Can you please help me?
Many thanks.

**Comment by darkwing** [comment]
Hello @mareean3.  Please contact support at http://support.metamask.io/ for help with your issue.
