### ISSUE TITLE
Metamask.metametamasks.cyou

### ISSUE THREAD

**Issue by Kpr0nis** [MetaMask/metamask-extension#13033]
I download brave to have all my crypto staff there cause I’m new to this whole thing.Amd when I try to dl metamask extension.A  similar metamask website ask for my phase.
In my history check the site was : metamask.metamasks.cyou
It was exactly the same with metamask.io 
So if it is a scam can I have a new phrase?

**Comment by danjm** [comment]
That site was a scam. That seed phrase was compromised

You can uninstall and reinstall metamask (do it directly from the chrome store) to generate a new seed phrase
