### ISSUE TITLE
Question metametrics??

### ISSUE THREAD

**Issue by zrock23** [MetaMask/metamask-extension#13052]
hello i have the following question, metamask displays / collects metrics from the endpoint link: http: // localhost: 8545.  And my question is is it possible to define data collection from endpoint link: http: // localhost: 8545 / metrics??
>node Geth v1.10.13

**Comment by brad-decker** [comment]
Could you provide anymore details about the behavior you are seeing versus what you would like to see? MetaMetrics is an internal metrics system only and does not collect metrics from the pages you visit in your browser.

**Comment by brad-decker** [comment]
I'm not sure I understand your question. If you have a question regarding MetaMetrics, I'd recommend opening up a support ticket to ask for details. We do not expose MetaMetrics for dapp developers, as its only for internal use.
