### ISSUE TITLE
NicknamePopover story: convert knobs and actions to controls / args

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13062]
**Describe the bug**
As part of a push to convert all stories that use deprecated `@storybook/addon-knobs` and `@storybook/addon-actions` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Convert `NicknamePopover` story in `ui/components/ui/nickname-popover/nickname-popover.stories.js` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Read the [MetaMask extension storybook documentation guidelines](https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page) to get a better understanding of writing stories. Providing MDX documentation although helpful, is a bonus and not a requirement for this issue.

To start storybook:
```
yarn storybook
```

**Requirements**
- [ ] Story has `argTypes` that align with component api / props
- [ ] All instances of `@storybook/addon-knobs` have been removed in favour of control args
- [ ] All instances of `@storybook/addon-actions` have been removed in favour of [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Any further improvements to the story interaction or documentation is a bonus

**Images**

<img width="1440" alt="Screen Shot 2021-12-12 at 5 46 51 PM" src="https://user-images.githubusercontent.com/8112138/145700685-71c249fd-94f4-4438-9841-722666faa92e.png">
<img width="1440" alt="Screen Shot 2021-12-12 at 5 47 12 PM" src="https://user-images.githubusercontent.com/8112138/145700690-e986649a-c0dc-4c8b-aec7-e941dca840e4.png">

**Comment by wiserdor** [comment]
would love to take this issue 🙏

**Comment by wiserdor** [comment]
@georgewrmarshall already created pr (:

**Comment by georgewrmarshall** [comment]
Apologies! Assigned thanks @wiserdor !
