### ISSUE TITLE
ContactListTab story: convert knobs and actions to controls / args

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13084]
**Describe the bug**
As part of a push to convert all stories that use deprecated `@storybook/addon-knobs` and `@storybook/addon-actions` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Convert `ContactListTab ` story in `ui/pages/settings/contact-list-tab/contact-list-tab.stories.js` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Read the [MetaMask extension storybook documentation guidelines](https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page) to get a better understanding of writing stories. Providing MDX documentation although helpful, is a bonus and not a requirement for this issue.

To start storybook:
```
yarn storybook
```

**Requirements**
- [ ] Story has `argTypes` that align with component api / props
- [ ] All instances of `@storybook/addon-knobs` have been removed in favour of control args
- [ ] All instances of `@storybook/addon-actions` have been removed in favour of [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Any further improvements to the story interaction or documentation is a bonus

**Images**

<img width="1440" alt="Screen Shot 2021-12-13 at 5 40 05 PM" src="https://user-images.githubusercontent.com/8112138/145753510-02257cbe-19ba-4a64-b1ea-0defabe181ea.png">
<img width="1440" alt="Screen Shot 2021-12-13 at 5 40 23 PM" src="https://user-images.githubusercontent.com/8112138/145753523-33acd062-cdc9-4a88-ad02-ee9eec12e55c.png">

**Comment by bschorchit** [comment]
Closing this as it was fixed with: https://github.com/MetaMask/metamask-extension/pull/13230
