### ISSUE TITLE
Only the primary network exists on the network, and other networks cannot be switched normally, which may be related to the style

### ISSUE THREAD

**Issue by DouYou-DianShuai** [MetaMask/metamask-extension#13095]
![Snipaste_2021-12-15_00-31-07](https://user-images.githubusercontent.com/65339064/146039397-fb2c6053-3f84-48d4-8423-ffbef74c38d8.png)

* 你好，我通过学习视频刚接触钱包，不知是否是一个问题。但是与教程里不符。自己反复在多台电脑上尝试后，依旧有问题，认为有可能是个错误。
> 问题版本：  MetaMask  10.8.0

**Comment by danjm** [comment]
see answer in https://github.com/MetaMask/metamask-extension/issues/13096
