### ISSUE TITLE
Network selection problem

### ISSUE THREAD

**Issue by DouYou-DianShuai** [MetaMask/metamask-extension#13096]
**Describe the bug**
When selecting a test network, the default test network cannot be selected properly.  

**Steps to reproduce (REQUIRED)**
 10.8.0

**Expected behavior**
You want the alternative test networks to display normally.

**Screenshots**
![Snipaste_2021-12-15_00-49-54](https://user-images.githubusercontent.com/65339064/146042607-37a77092-e0bc-4825-91ae-fd97ff185f0e.png)

**Browser details (please complete the following information):**
 - OS: [Windows 10 and 11]
 - MetaMask Version: [10.8.0]

**Additional context (Error Messages, etc.)**
不好意思，我刚接触这个，发现跟视频里所讲不符合。经过多个电脑尝试后问题依旧存在，就提出来了。如果只是个例或是耽误时间的话，请原谅我的打扰。
只是希望自己可以解决所遇到的问题，从而继续学习视频教程。

**Comment by danjm** [comment]
You should be able to fix this by turning on test networks in settings:


https://user-images.githubusercontent.com/7499938/146194228-8fbb6183-eec7-43a1-abfc-e3f211548dbf.mp4

**Comment by danjm** [comment]
Closing this based on the above fix. If it doesn't work, please comment here and I will reopen

**Comment by DouYou-DianShuai** [comment]
起作用了，非常感谢
