### ISSUE TITLE
There was an error with your transaction. Please try again. Opensea - Polygon

### ISSUE THREAD

**Issue by forexpiphunter** [MetaMask/metamask-extension#13103]
I'm getting an error message when I sign a transaction on Opensea to sell my NFT on the Polygon network

"There was an error with your transaction. Please try again." 

Metamask version:10.8.0
Trezor firmware version: 2.4.3

**Comment by danjm** [comment]
@forexpiphunter where do you see this error? can you share a screen shot?

**Comment by forexpiphunter** [comment]
I get this error message when I click on Unlock button [here](https://www.screencast.com/t/YkH3GSmZaR) and then it will show me this error [here](https://www.screencast.com/t/5tYvlJTtO)

**Comment by forexpiphunter** [comment]
Any update on this? I got a $22k NFT stuck on Polygon I can transfer or sell.

**Comment by MT00x** [comment]
Same here

**Comment by forexpiphunter** [comment]
@danjm any update on this? Any workaround for this issue?  I've tried to import my Trezor seed into the ledger but I can't find my eth address when adding hardware wallet to Metamask

**Comment by darkwing** [comment]
@forexpiphunter Is this something that had worked in the past?  If you open the `Developer Tools > Console` in your browser, do you see error details?

**Comment by MT00x** [comment]
> Is this something that had worked in the past?

Don't know, first time for me



> If you open the `Developer Tools > Console` in your browser, do you see error details?

inpage.js:1 MetaMask - RPC Error: MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray') {code: -32603, message: "MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray')", data: {…}}

![image](https://user-images.githubusercontent.com/10209506/146797899-5119bc18-2a08-4f1d-9300-3ff974a1787a.png)

**Comment by forexpiphunter** [comment]
> Is this something that had worked in the past? 
First time doing this

> If you open the `Developer Tools > Console` in your browser, do you see error details?

`inpage.js:1 MetaMask - RPC Error: MetaMask Message Signature: Error: Not supported on this device {code: -32603, message: 'MetaMask Message Signature: Error: Not supported on this device', data: {…}}code: -32603data: {originalError: {…}}message: "MetaMask Message Signature: Error: Not supported on this device"[[Prototype]]: Object`

**Comment by Jamby93** [comment]
> > Is this something that had worked in the past?
> 
> Don't know, first time for me
> 
> > If you open the `Developer Tools > Console` in your browser, do you see error details?
> 
> inpage.js:1 MetaMask - RPC Error: MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray') {code: -32603, message: "MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray')", data: {…}}
> 
> ![image](https://user-images.githubusercontent.com/10209506/146797899-5119bc18-2a08-4f1d-9300-3ff974a1787a.png)

I had exactly the same issue of @MT00x. That happens when trying to unlock USDC. 
OpenSea creates a signing request like this one:
`{"primaryType": "MetaTransaction", "types": {"EIP712Domain": [{"name": "name", "type": "string"}, {"name": "version", "type": "string"}, {"name": "verifyingContract", "type": "address"}, {"name": "salt", "type": "bytes32"}], "MetaTransaction": [{"name": "nonce", "type": "uint256"}, {"name": "from", "type": "address"}, {"name": "functionSignature", "type": "bytes"}]}, "domain": {"name": "USD Coin (PoS)", "version": "1", "verifyingContract": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174", "salt": "0x0000000000000000000000000000000000000000000000000000000000000089"}, "message": {"nonce": null, "from": "<REDACTED>", "functionSignature": "0x095ea7b3000000000000000000000000411b0bcf1b6ea88cb7229558c89994a2449c302cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}}`

The problem arise from the nonce parameter, which is of type uint256 but still with a value of null. The issue is actually in the ethereumjs-abi library, precisely [here](https://github.com/ethereumjs/ethereumjs-abi/blob/master/lib/index.js#L71) where the value is assumed to be not-nullable.

I was able to bypass this issue by opening a Developer tools inside the MetaMask extension, setting a breakpoint on line 19130 (might differ since is a pretty-print of the minified file), and patching the value of the field to be 0 instead of null. See below as an example.
![image](https://user-images.githubusercontent.com/13535384/147143188-4dab286a-602d-42a2-bf7f-aae5dbad2f32.png)

That made the signature goes flawlessly, USDC is now unlocked for me, and I was able to continue with the second signature and purchase.

**Comment by PAV8L** [comment]
sentry-install.js:1 
        
       TypeError: Cannot read properties of null (reading 'toArray')
  at f (common-1.js:30)
  at h (common-1.js:30)
  at Object.o.rawEncode (common-1.js:30)
  at Object.encodeData (background-1.js:1)
  at Object.hashStruct (background-1.js:1)
  at Object.sign (background-1.js:1)
  at Object.b [as signTypedData_v4] (background-1.js:1)
  at c.signTypedData_v4 (background-1.js:1)
  at c.signTypedData (background-1.js:1)
  at background-0.js:1
  at async ke.signTypedMessage (background-0.js:1)
(anonymous) @ sentry-install.js:1
(anonymous) @ common-2.js:37
await in (anonymous) (async)
(anonymous) @ common-3.js:10
dispatch @ ui-0.js:1
signTypedMessage @ ui-2.js:1
signAction @ ui-4.js:1
m @ ui-0.js:1
_ @ ui-0.js:1
(anonymous) @ ui-0.js:1
k @ ui-0.js:1
C @ ui-0.js:1
P @ ui-0.js:1
j @ ui-0.js:1
Sn @ ui-0.js:1
le @ ui-0.js:1
jn @ ui-0.js:1
An @ ui-0.js:1
Rn @ ui-0.js:1
n.unstable_runWithPriority @ ui-0.js:1
Ko @ ui-0.js:1
ue @ ui-0.js:1
On @ ui-0.js:1
a @ sentry-install.js:1
common-2.js:37 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toArray')
  at f (common-1.js:30)
  at h (common-1.js:30)
  at Object.o.rawEncode (common-1.js:30)
  at Object.encodeData (background-1.js:1)
  at Object.hashStruct (background-1.js:1)
  at Object.sign (background-1.js:1)
  at Object.b [as signTypedData_v4] (background-1.js:1)
  at c.signTypedData_v4 (background-1.js:1)
  at c.signTypedData (background-1.js:1)
  at background-0.js:1
  at async ke.signTypedMessage (background-0.js:1)

same issue with the above errors,,, any idea how i could fix this?
many thanks in advance

**Comment by PAV8L** [comment]
> > > Is this something that had worked in the past?
> > 
> > 
> > Don't know, first time for me
> > > If you open the `Developer Tools > Console` in your browser, do you see error details?
> > 
> > 
> > inpage.js:1 MetaMask - RPC Error: MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray') {code: -32603, message: "MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray')", data: {…}}
> > ![image](https://user-images.githubusercontent.com/10209506/146797899-5119bc18-2a08-4f1d-9300-3ff974a1787a.png)
> 
> I had exactly the same issue of @MT00x. That happens when trying to unlock USDC. OpenSea creates a signing request like this one: `{"primaryType": "MetaTransaction", "types": {"EIP712Domain": [{"name": "name", "type": "string"}, {"name": "version", "type": "string"}, {"name": "verifyingContract", "type": "address"}, {"name": "salt", "type": "bytes32"}], "MetaTransaction": [{"name": "nonce", "type": "uint256"}, {"name": "from", "type": "address"}, {"name": "functionSignature", "type": "bytes"}]}, "domain": {"name": "USD Coin (PoS)", "version": "1", "verifyingContract": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174", "salt": "0x0000000000000000000000000000000000000000000000000000000000000089"}, "message": {"nonce": null, "from": "<REDACTED>", "functionSignature": "0x095ea7b3000000000000000000000000411b0bcf1b6ea88cb7229558c89994a2449c302cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}}`
> 
> The problem arise from the nonce parameter, which is of type uint256 but still with a value of null. The issue is actually in the ethereumjs-abi library, precisely [here](https://github.com/ethereumjs/ethereumjs-abi/blob/master/lib/index.js#L71) where the value is assumed to be not-nullable.
> 
> I was able to bypass this issue by opening a Developer tools inside the MetaMask extension, setting a breakpoint on line 19130 (might differ since is a pretty-print of the minified file), and patching the value of the field to be 0 instead of null. See below as an example. ![image](https://user-images.githubusercontent.com/13535384/147143188-4dab286a-602d-42a2-bf7f-aae5dbad2f32.png)
> 
> That made the signature goes flawlessly, USDC is now unlocked for me, and I was able to continue with the second signature and purchase.

i dont know if you are able to help with the similar errors i am getting?

**Comment by leglinne** [comment]
> > Is this something that had worked in the past?
> > First time doing this
> 
> > If you open the `Developer Tools > Console` in your browser, do you see error details?
> 
> `inpage.js:1 MetaMask - RPC Error: MetaMask Message Signature: Error: Not supported on this device {code: -32603, message: 'MetaMask Message Signature: Error: Not supported on this device', data: {…}}code: -32603data: {originalError: {…}}message: "MetaMask Message Signature: Error: Not supported on this device"[[Prototype]]: Object`

I do have the same issue , not supported on this device, using the same specs. Latest trezor hardware and latest metamask, tried to downgrade, didn't help

**Comment by PAV8L** [comment]
this is the first time i am trying to use usdc i think thats why its doing to unlock the currency at first

**Comment by leglinne** [comment]
Eth on poly in my situation

**Comment by Jamby93** [comment]
> i dont know if you are able to help with the similar errors i am getting?

Yep, you problem seems to be the same as mine (which is different from the OP issue with Trezor). You should be able to debug Metamask extension with [the basic Chrome guide](https://developer.chrome.com/docs/extensions/mv3/tut_debugging/), find the "common-1.js" file, put the breakpoint, perform the signing transaction, and execute the  console command as I've done in the screenshot above. 
That of course need some basic knowledge of Developers Tools and debugging in general, which I'm afraid is a bit out of scope for this issue.

**Comment by PAV8L** [comment]
really aprpreciate your help, unfortunately this is way beyond my level of knowledge of developing, i will try to find someone who has more understanding and use your responses as a guidance. thanks so much

**Comment by PAV8L** [comment]
> > i dont know if you are able to help with the similar errors i am getting?
> 
> Yep, you problem seems to be the same as mine (which is different from the OP issue with Trezor). You should be able to debug Metamask extension with [the basic Chrome guide](https://developer.chrome.com/docs/extensions/mv3/tut_debugging/), find the "common-1.js" file, put the breakpoint, perform the signing transaction, and execute the console command as I've done in the screenshot above. That of course need some basic knowledge of Developers Tools and debugging in general, which I'm afraid is a bit out of scope for this issue.

where would you suggest i would put the breakpoint in the file?

**Comment by shin** [comment]
> > Is this something that had worked in the past?
> 
> Don't know, first time for me
> 
> > If you open the `Developer Tools > Console` in your browser, do you see error details?
> 
> inpage.js:1 MetaMask - RPC Error: MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray') {code: -32603, message: "MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray')", data: {…}}
> 
> ![image](https://user-images.githubusercontent.com/10209506/146797899-5119bc18-2a08-4f1d-9300-3ff974a1787a.png)

I got the same error code, but the message is "Metamask Message Signature Error: Not supported on this device".

<img width="728" alt="Screen Shot 2021-12-30 at 5 04 39" src="https://user-images.githubusercontent.com/27838193/147699464-a6e29379-514a-4b29-a44b-2ceef49b9928.png">

**Comment by dmitrii-laier** [comment]
@Jamby93 you saved my day!!! Respect!!!!!

**Comment by DrFalki** [comment]
I had the same issue. I´m using a ledger nano x with metamask. The fix for me was to change the rpc (advanced metamask settings) and to reset the account. Afterwards i could sign in my first attempt

**Comment by leglinne** [comment]
> I had the same issue. I´m using a ledger nano x with metamask. The fix for me was to change the rpc (advanced metamask settings) and to reset the account. Afterwards i could sign in my first attempt

What did you change In the RPC settings to be exact?

**Comment by DrFalki** [comment]
I change the rpc following this guide https://docs.dfyn.network/guides/changing-polygons-rpc-endpoint-on-metamask and changed from  https://polygon-rpc.com/ to https://matic-mainnet.chainstacklabs.com

**Comment by leglinne** [comment]
Tried the following, didn't help

**Comment by DrFalki** [comment]
> Tried the following, didn't help

Did you reset your account too?
<img width="337" alt="Bildschirmfoto 2022-01-05 um 20 36 56" src="https://user-images.githubusercontent.com/36811301/148278097-5307a914-2844-4974-b926-ee02fb37f3d3.png">

**Comment by leglinne** [comment]
Yep, I did it too

**Comment by uoii** [comment]
> I had the same issue. I´m using a ledger nano x with metamask. The fix for me was to change the rpc (advanced metamask settings) and to reset the account. Afterwards i could sign in my first attempt

It work to me at Mozilla Firefox browser. You maybe should wait several minute in a stuck Open Currency process until this properly done (successfully)

**Comment by mohamedmansour** [comment]
I am getting this issue on voting for a proposal here:
https://snapshot.org/#/ens.eth

```
'MetaMask Message Signature: Error: Not supported on this device'
```

Any idea how I can help debug it?

**Comment by dmitrii-laier** [comment]
Just uploaded a video with solution for this bug - There was an error with your transaction. Please try again. 
Voice Russian, but easy to understand all steps.

https://youtu.be/DRtcWh9GufA

**Comment by forexpiphunter** [comment]
Hi, @dmitrii-laier I just tried your steps, and when I placed NFT for sale, I still got the same error message when using Trezor. I did put a breakpoint, but when I try to click Unlock again and when Metamask windows come up, and I click to sign, it would just give me the same error message.

**Comment by dmitrii-laier** [comment]
@forexpiphunter are you making changes after one skipped breakpoint? Network Polygon?
I didn't test with trezor.

**Comment by forexpiphunter** [comment]
@dmitrii-laier In "watch" I add a "t" and retry the transaction again, but this is where the code break doesn't work, I will get the same error message.  Yes, It's Polygon with trezor

**Comment by dmitrii-laier** [comment]
> Hi, @dmitrii-laier I just tried your steps, and when I placed NFT for sale, I still got the same error message when using Trezor. I did put a breakpoint, but when I try to click Unlock again and when Metamask windows come up, and I click to sign, it would just give me the same error message.

Try to approve token with buy operation and after maybe sell operation will work.

**Comment by leglinne** [comment]
I will try to reproduce your solution and tell you if it works too

**Comment by leglinne** [comment]
Hi, solution provided didn't help

сб, 15 янв. 2022 г. в 13:22, DubManZ Dub ***@***.***>:

**Comment by Harikrishna1610** [comment]
![image](https://user-images.githubusercontent.com/12293582/150324638-1e6ec97f-13e9-4c40-b327-9195fb03759b.png)

Hi I'm getting cors error while i am trying to sign the message

**Comment by cristoforo** [comment]
> Just uploaded a video with solution for this bug - There was an error with your transaction. Please try again. Voice Russian, but easy to understand all steps.
> 
> https://youtu.be/DRtcWh9GufA

This worked for me
Metamask with Ledger Nano S

**Comment by Happy-Ferret** [comment]
> Just uploaded a video with solution for this bug - There was an error with your transaction. Please try again. Voice Russian, but easy to understand all steps.
> 
> https://youtu.be/DRtcWh9GufA

I tried this. Didn't work for me, unfortunately.

Metamask on Chrome.

**Comment by Goze24** [comment]
Guys u have to be connected to the network of the currency(e.x.eth polygon...) the nft ur looking to buy is to metamask

**Comment by apdwivedi1208** [comment]
I was also getting the same issue. Mine go solve after changing to o Etherium Mainnet instead of Matic Mainnet  in my  metamask wallet.

**Comment by forexpiphunter** [comment]
Guys, 
Why are we talking about Ethereum and Ledger?  This issue is happening only on Polygon network with Trezor using metamask

**Comment by Doahs75** [comment]
agree with @forexpiphunter the comments here moved away from the original problem.  The problem is that when using a Trezor with metamask on opensea and trying to transfer out a Polygon NFT when you click on SIgn in Metamask you will get an error "You declined the action in your wallet" and it does not bring up the trezor GUI but instead provides the error and does nothing.  This is  major problem as now Polygon NFT cannot be transfer out of the Trezor via metamask on Opensea.    I'm using the latest Trezor firmware 2.4.3 and the latest version of metamask 10.8.1. It works fine with ETH NFT but does not work for Polygon NFT.

**Comment by nNabakhteveli** [comment]
I don't know why but when I disabled all chrome extensions it worked

**Comment by dcsan** [comment]
this issue is about polygon network, not hardware wallets. this is a common error mainly when trying to use opensea
pages and pages of frustrated users
https://www.reddit.com/r/opensea/comments/oqgeit/unable_to_unlock_currency/

does anyone know if this is an 
- opensea bug, 
- metamask or 
- polygon network congestion

issue?

it seems to come and go

**Comment by leglinne** [comment]
I've contacted Trezor support, opensea support, and MM support team.
Throughout the process. Seems like this is the problem within metamask
itself. And Devs are not hasty at all to solve this issue. I've been put on
hold by their support team for almost 2 months now. No news

**Comment by kalyaskaq** [comment]
Maybe you still have this problem on version 10.9.3. I solved it like this.
Created a collection, specified payment using ETH DAY USDC in the settings           
After that I was able to put my NFTs on sale 
If you're interested, here's my collection: https://opensea.io/collection/dreaminjapan

**Comment by Jostino** [comment]
I'm having the same excat issue, followed the youtube video but I dont have that same code.
Any update?

**Comment by DMW-11** [comment]
Here's a simple fix that worked for me.
Firstly, my art was part of a collection which had 3 payment tokens USDC and DAI all on the polygon net.
I the error when trying to sign in to my metamask wallet.
So I went into my collection and removed the tokens USDC and DAI and was only left with Eth Polygon and went and tried again and it worked. Haven't had the issue since then, as someone mentioned, may have something to do with the USDC token

**Comment by King1Rossi** [comment]
This is what mine keeps saying can anyone help me with this 
![image](https://user-images.githubusercontent.com/100342535/155483016-0a3c08cc-a82a-470e-92b1-2ba4e1023e0a.png)

**Comment by ZelalemG** [comment]
Here is the fix that worked for me...
First check if your internet connection is good. Log out of your meta mask or any other wallet that was connected to open sea. Again log out out of open sea and login back.
Then try initiating your action from open sea, which will attempt to connect to meta mask or your wallet. Then you can unlock from there.
Hope this helps.

**Comment by kalyaskaq** [comment]
Maybe you still have this problem on version 10.9.3. I solved it like this.
Created a collection, specified payment using ETH DAY USDC in the settings
After that I was able to put my NFTs on sale
If you're interested, here's my collection: https://opensea.io/collection/fat-kittens

**Comment by King1Rossi** [comment]
@kalyaskaq Thanks that really helped i can post my nft's now

**Comment by Abhvir** [comment]
> I'm getting an error message when I sign a transaction on Opensea to sell my NFT on the Polygon network
> 
> "There was an error with your transaction. Please try again."
> 
> Metamask version:10.8.0 Trezor firmware version: 2.4.3

bro do one thing just refresh your funds in wallet under log out option
it works for me..... hope for u too

**Comment by ackvf** [comment]
It's still `null` when trying to Unlock USDC
![image](https://user-images.githubusercontent.com/2313018/155994842-ea74915f-4f23-4c3d-ac57-d32d7281920f.png)

So is this a Metamask issue or OpenSea issue? Who should we contact to have this fixed?

**Comment by rosnaib11** [comment]
Still having error when trying to unlock currency. Been waiting for this since last year of December! I can't list NFT in opensea jeez.

![image](https://user-images.githubusercontent.com/26837762/156406857-655e0efc-b899-4922-a277-91e6a0a03595.png)

**Comment by rosnaib11** [comment]
I think its working now

**Comment by cartovarc** [comment]
i have the same problem

MetaMask - RPC Error: MetaMask Message Signature: TypeError: Cannot read properties of null (reading 'toArray')

**Comment by evren320** [comment]
I had this error on brave browser, disabling "tracker and ad block" for the opensea page solved the problem.

**Comment by Mosillino1** [comment]
Hi 
Can anyone help me with "not well-formed currency" error on metamask?
When I try to sell, send and or buy etc. I face this error attached.

Please help me all my cryptos and tokens are in my metamask and I can not do anything with them.
![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164400338-02d3b84e-9788-4782-9f34-3465597a6f10.jpg)

**Comment by stefannebesnak** [comment]
```diff
- There was an error with your transaction. Please try again.
```

I have the same problem with Trezor connected to Metamask (latest updates) on Opensea/Matic. 

```diff
+ Ledger connected to Coinbase wallet fixed it
```

**Comment by dcsan** [comment]
people are commenting here on all kinds of unrelated stuff.

with regard to unlocking polgyon transactions
- make sure you have weth AND matic in your wallet
- if TX fails, opensea estimates the gas wrong, try bumping up the gas offer

**Comment by MattLong6** [comment]
![image](https://user-images.githubusercontent.com/71360466/178197616-b870bb51-9fee-4b7f-9a08-1fee94b54551.png)
I cannot approve my coins on Polygon with Metmask.

**Comment by DomDomPop** [comment]
> ![image](https://user-images.githubusercontent.com/71360466/178197616-b870bb51-9fee-4b7f-9a08-1fee94b54551.png) I cannot approve my coins on Polygon with Metmask.

I actually came here for the same exact thing. I was even gonna buy the Batman one too lol. I got it working with the instructions above and the help of the video in finding the correct breakpoint. I left the Batman one for you and got a different one, so if you want it, it's still there. 

For the current version (10.17.0) I put the breakpoint at line 6699 in common-2.js

**Comment by seaona** [comment]
I'm re-opening this ticket since this seems to be still an issue and might be related to[ this one](https://github.com/MetaMask/metamask-extension/issues/22771)

**Comment by itzfemzy3** [comment]
Why is my buyer experiencing this?
![Uploading 380153681_227933736966907_3154704483116381717_n.jpg…]()

**Comment by itzfemzy3** [comment]
why is my buyers experiencing this 
![380153681_227933736966907_3154704483116381717_n](https://github.com/MetaMask/metamask-extension/assets/102591286/9dba07d8-3504-4fa4-84a4-d352e88e048f)
