### ISSUE TITLE
'Customize transaction nonce' cannot setting be enabled

### ISSUE THREAD

**Issue by Augustyniak** [MetaMask/metamask-extension#13105]
**Describe the bug**
Customize transaction nonce setting cannot be enabled after the update to 10.8.0 version. It did work correctly in the previous version. 

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Open Metamask
2. Go to Settings > Advanced Settings
3. Click on "Customize transaction nonce" switch to enable the feature
4. Nothing happens - switch's state does not change (the feature stays disabled).

**Expected behavior**
"Customize transaction nonce" setting is enabled.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Mac os
 - Hardware Wallet: N/A
 - Browser: Chrome 96.0.4664.110, Firefox, Brave
 - MetaMask Version: 10.8.0

**Additional context (Error Messages, etc.)**
N/A

**Comment by krajniak** [comment]
Can confirm on 10.8.0 on macos on opera

**Comment by danjm** [comment]
Thanks for the report

**Comment by galangster** [comment]
Can also confirm on Brave browser extension on Windows 10.

**Comment by belougae** [comment]
metoo

**Comment by cleanunicorn** [comment]
Confirmed on Firefox on Linux

**Comment by edumar111** [comment]
continue la fix?

**Comment by edumar111** [comment]
I confirm the error still continues

**Comment by flymauntains** [comment]
If your account on the Sepolia testnet has many pending transactions and you cannot initiate new transactions due to a lack of balance for gas fees, how resolve this issue?
![Screenshot 2024-07-06 013951](https://github.com/MetaMask/metamask-extension/assets/172695995/0adc98c9-8d64-4eb1-ab17-8947018c938d)
