### ISSUE TITLE
MetaMask Internal JSON-RPC error

### ISSUE THREAD

**Issue by mikigang22** [MetaMask/metamask-extension#13116]
1. Friend greetings! I have a big problem, I operate all my accounts from my phone either binance, metamask etc ... and when making a transfer of my wallet to binance I jump an error "internal json-rpc" you would help me with that problem please:(

2. After that I tried to make the transaction from my pc but I threw an error and the transaction was not made and in the same way the gas was charged

**Comment by darkwing** [comment]
@mikigang22 Please use our official support channel, http://support.metamask.io/, for help with this issue.
