### ISSUE TITLE
Allow option to remove `Backup your seed phrase` nag

### ISSUE THREAD

**Issue by morkeltry** [MetaMask/metamask-extension#13129]
Whenever a new account is imported to metamask, the `Backup your Secret Recovery Phrase to keep your wallet and funds secure.` nag covers necessary parts of the popup UI.

I am aware this was a design choice.
This issue is requesting that that choice be reviewed, since it is a bad choice.

I'm not sure of the logic of the nag appearing for imported accounts, since if an account is _imported_ then, by definition, it has already been backed up somewhere.

If there is some kind of logic to it, it even then would be sensible to allow users to remove the nag without viewing and reentering the phrase.
Every time a user's seed phrase is show in cleartext, and especially when the phrase is reentered, is a vector for some kind of compromise.
IMHO, removing the nag, or moving it somewhere it can be ignored without affecting the extension's functionality should also be possible (even if discouraged/ inconvenient) where accounts were not imported, but were created in the extension instance.

It is a general UI principle that it is the user, not the app developer, should have ultimate control of the UI. While there are _partial_ exceptions to this (eg nags for security reasons), the reason it is a principle is that there will always be some kind of situation unforeseen by the app developer where their assumptions do not hold true.

This is a concrete example of exactly that - by attempting to prevent users from locking themselves out, but by doing it in a clumsy way, the extension is pushing the user into behaviour which is less safe than the alternative (remember that 'always keep your seed phrase private' part).

In the longer term, it may be worth considering a UX experience that treats instances of the metamask extension as instances that can be installed and removed, logged into and logged out of - so that this message can be displayed at more appropriate times than 'whenever a user wants to use metamask'.

**Comment by Gudahtt** [comment]
Thanks for the suggestion! This can already be disabled in our advanced settings. Navigate to 'Settings" by clicking on the account menu in the top-right of the screen, then click "Advanced", then scroll to the bottom. You should see an option titled "Dismiss Secret Recovery Phrase backup reminder".

**Comment by morkeltry** [comment]
Perfect, thankyou :+1: 
I was not aware of this setting (obviously) and maybe it's right that it should be non-obvious.
Prompting for backup of imported accounts still seems irrational, though, so hopefully this will be considered a s a feature request :)

**Comment by Gudahtt** [comment]
I'm sorry, I must have misunderstood the original issue. The account was imported you say? Do you mean that you imported the seed phrase for that wallet, or that you imported the specific account you were looking at at the time?

This reminder should only appear if you created a new seed phrase during onboarding.

**Comment by tadasgedgaudas** [comment]
This message is very annoying, It blocks access from functions like import token
