### ISSUE TITLE
Metamask on firefox cannot create transactions after update with Trezor

### ISSUE THREAD

**Issue by jooray** [MetaMask/metamask-extension#13124]
**Describe the bug**

I use metamask with Trezor T on Firefox, current version (released 14. 12. 2021).

When I want to sign transaction, I get:

Failed transaction Transaction 41 failed! Error: TypeError: can't define property "default": Function is not extensible

The same transaction works with Chromium and Metamask.

**Steps to reproduce (REQUIRED)**
Go to any website that requires to sign contract transaction, create a transaction, click confirm on the signing pop-up and you get the message.

**Expected behavior**
Transaction should be seen on Trezor screen for confirmation.

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: Trezor Firmware version 2.4.3
 - Browser:  Firefox Browser 71.0 95.0.1 (64-bit)
 - MetaMask Version: 10.8.0

**Comment by AlexJupiter** [comment]
@jooray thank you very much for the report. Is this a duplicate of the problem outlined in https://github.com/MetaMask/metamask-extension/issues/12967 ?
