### ISSUE TITLE
Error: User denied message signature when user click unlock metamask

### ISSUE THREAD

**Issue by zilincorp** [MetaMask/metamask-extension#13128]
When user click unlock, sometimes metamask return error MetaMask - RPC Error: MetaMask Message Signature: User denied message signature

I use reactjs, typescript ethers and @web3-react/core to sign message with metamask.

```
useEffect(() => {

    async function init() {
      const persistedWallet = window.localStorage.getItem("wallet");

      if(persistedWallet) {
        const { name: walletName, payload } = JSON.parse(persistedWallet);
        const connector = new WalletConnector({ walletName, library, payload });
        window.wallet = await connector.buildWallet();
      }

      if (withLogic === true) {
        if (!isFull(account) && isFull(prevAccount)) {
          dispatch(setAuth({checked: true, result: false}));
          deleteToken();
        }

        if (isFull(account) && !isFull(prevAccount) && window.wallet) {
          dispatch(finishAuth({ signFunc: window.wallet.sign.bind(window.wallet), account: account as "string | null | undefined"}));
        }
      }
    }
    init();
  }, [account, dispatch, prevAccount, withLogic, library]);

```

**Comment by zilincorp** [comment]
reinstalling Metamask plugin helps to get rid of the error

**Comment by Edgar-P-yan** [comment]
+1

**Comment by Gudahtt** [comment]
That error message indicates that the user has refused the signature. It could also mean that the user closed the popup window where the signature was presented to them.

The code snippet you have shared does not appear to be directly interacting with MetaMask, but rather it uses third-party libraries that I am unfamiliar with. I'd suggest sharing more context for the problem on the Ethereum StackOverflow or our [Community Forum](https://community.metamask.io/). If you want to make it as easy as possible for others to help you, try creating a minimal reproduction for this problem, and sharing the entire project along with your question on those other platforms.
