### ISSUE TITLE
Chrome console appears error information before user confirms the transaction.

### ISSUE THREAD

**Issue by marklee1972** [MetaMask/metamask-extension#13137]
1.Dapp trigger to sendTransaction. 
2.MetaMask extension pop on top. 
3.During it finish up ,

Chrome console would repeat show 3 times:

Error in event handler: TypeError: Cannot read properties of undefined (reading 'newValue')
    at chrome-extension://nnjjahlikiabnchcpehcpkdeckfgnohf/js/appConfig.js:1:964_

This error would not effect next action.
User can approve or deny sendTransaction and then code execute normally.

Windows 7
Chrome  96.0.4664.93
MetaMask Version 10.8.1
WEB3 @1.6.1
Network : localhost:8545

![2021-12-22_004008](https://user-images.githubusercontent.com/28388278/146967949-558a8630-d93b-4167-b871-06284e164f48.png)

**Comment by Gudahtt** [comment]
Thanks for the report! Unfortunately I was unable to reproduce this on our [test dapp](https://metamask.github.io/test-dapp/). I believe it is a bug with the dapp you are using, rather than a bug with MetaMask.

**Comment by marklee1972** [comment]
Hi Gudahtt
If you don't mind ,review my source code please.

It is simple load page and trigger sendTransaction on component mount. 

According my observes,the error would occur during metamask be wake up.
If metamask's status stayed at "Reject or Confirm" and then I reload Dapp page,the error couldn't occur.

```
`import Web3 from "web3";
import React, { Component } from 'react';
import ReactDOM from "react-dom";


class App extends React.Component {
  constructor(props) {
    super(props);
  }
  
  async componentWillMount() {
	  const account = "0x1d489c3F8Ed5Ee71325A847888B2157c9ac29c05";
	  const targetAddr = "0x1ce421937a6F59bF58FaafE316D23AaED690DA18";
    try {
		if (typeof window.ethereum !== 'undefined') {
			var web3 = new Web3(window.ethereum);
			await window.ethereum.enable();
			
			web3.eth.sendTransaction({
				from: account,
				to: targetAddr, 
				value: web3.utils.toWei("2", "ether"),
			}).on('transactionHash', function(hash){
				console.log(hash);
			}).on('receipt', function(receipt){
				console.log("receipt");
			}).on('confirmation', function(confirmationNumber, receipt){
				console.log("confirmation");
			}).on('error', console.error);
		}
    } catch(err) {
		console.log(err);
    }
  }
  
  render() {
    return (
		<div>
		Hello World!
		</div>
	);
  }
};


ReactDOM.render(
      <App />,
  document.getElementById("root")
);
```
`

**Comment by Gudahtt** [comment]
I do not think that snippet includes the source of this problem. There is no variable here called `newValue`, as shown in the error message.

What is the file `appConfig.js`? The problem seems to lie there.

**Comment by marklee1972** [comment]
Hi Gudahtt
It's a good question.
It seems like a temporary path that chrome-extendsions generated randomly.
I found it at this path,although it's not match the error message completely.

Error message:
_at chrome-extension://nnjjahlikiabnchcpehcpkdeckfgnohf/js/appConfig.js:1:964_
Real path:
_AppData\Local\Google\Chrome\User Data\Default\Extensions\nnjjahlikiabnchcpehcpkdeckfgnohf\5.6.8_0\js\appConfig.js_

I am sorry I have no enough ability to read and resolve it.

Can you give me a hand?


`var appConfig=function(){var e={dirType:"TITLE",fixedDir:"Fatkun",widthRange:null,heightRange:null,needRename:!1,renameRule:"pic_{NO001}.{EXT}",outputTextFormat:'<img src="{LINK}"/>',needBlobDomains:[],singleOutput:!0,autoConvertWebp:!0,enableShortkey:!0,shortKeyCurrent:"Z",shortKeyAll:"A",limitConcurrent:10,dragSelect:!0,dragDownload:!0,showUrl:!1,advancedMode:!0,unique:!0,enableContextmenu:!1,rememberFilter:!0,dragDownloadMode:"drag-to-filter-page",previewSize:"small",sortType:"default",showMore:!0,pagination:!1,recordPageInfo:!1};try{"nnjjahlikiabnchcpehcpkdeckfgnohf"==chrome.runtime.id&&(e.enableContextmenu=!0)}catch(e){}var n={defaultConfig:e},o="";return{init:function(t,r){chrome.storage.local.get("app_config",function(o){var r=o.app_config||{};for(var i in e)"outputTextFormat"!=i||r[i]?n[i]=void 0!==r[i]?r[i]:e[i]:n[i]=e[i];t(n)}),function(e){chrome.storage.onChanged.addListener(function(t){var r=t.app_config;if(newConfigStr=JSON.stringify(r.newValue),r&&o!=newConfigStr)for(var i in o=newConfigStr,r.newValue)n[i]!=r.newValue[i]&&(n[i]=r.newValue[i]);e&&e(n)})}(r)},getSyncConfig:function(e){return n},getAsyncConfig:function(){chrome.storage.local.get("app_config",function(e){cb(e.app_config)})},setConfig:function(o,t){for(var r in o)Object.keys(e).indexOf(r)>=0&&(n[r]=o[r]);chrome.storage.local.set({app_config:JSON.parse(JSON.stringify(n))},function(){t&&t(n)})},getDefaultConfig:function(){return e}}}();`

**Comment by Gudahtt** [comment]
It looks like that error is from this extension:.
https://chrome.google.com/webstore/detail/fatkun-batch-download-ima/nnjjahlikiabnchcpehcpkdeckfgnohf

**Comment by marklee1972** [comment]
Hi Gudahtt
Great~Bingo!
You caught it !
After I remove the extension,
the error disappear !
Thank you very much.
