### ISSUE TITLE
EIP-1559 V2: Small UI Tweaks

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#13143]
Based on Dec 22 stand up between @mcmire @jakehaugen @kevinghim 

- [x] Keep the `Network is busy. Gas prices are high and estimates are less accurate.` on the Transaction Confirm screen, but not on the Edit Gas fee screen on the V2 UI. It should appear below the transaction amount, but above the gas estimate and gas options button. — **assigned to @mcmire**
<img width="198" alt="Screen Shot 2021-12-22 at 11 33 46 AM" src="https://user-images.githubusercontent.com/6951929/147125344-d96fe80b-60f8-4826-9bf6-0e354331289a.png">

- [x] On the Network Status within the Edit Gas fee screen, indicate the basefee without any decimals, but keep the lower range priority fee decimal at a tenth, and no decimal places for the upper range. — assigned to @jpuri
<img width="337" alt="Screen Shot 2021-12-22 at 11 44 31 AM" src="https://user-images.githubusercontent.com/6951929/147126699-7e1d780b-8611-4623-8c93-50b30dab43c7.png">

- [x] Also, on the Edit Gas fee screen, replace the Advanced icon with the emoji gear ⚙️  — assigned to @jpuri 

- [x] #13195
<img width="276" alt="Screen Shot 2021-12-22 at 11 18 47 AM" src="https://user-images.githubusercontent.com/6951929/147127350-92374770-4478-4e1f-92dd-363858d99e8b.png">

- [x] When a dapp initiated swap happens, the `Give permission to access your [xxx]?` appears. We should replace the `Transaction fee. A fee is associated with this request.` copy (in red) with the normal gas option selection [Site suggested] modal from the Edit Gas fee screen (2nd image).   — assigned to @jpuri 
<img width="177" alt="Screen Shot 2021-12-22 at 11 26 05 AM" src="https://user-images.githubusercontent.com/6951929/147128094-f6f683d2-949c-4ba7-bb1b-e33538205c58.png">
<img width="414" alt="Screen Shot 2022-01-05 at 1 00 38 PM" src="https://user-images.githubusercontent.com/6951929/148289754-58b1716f-30c8-463c-9741-c4f001e01605.png">

- [x] Adjust the width of the network status area -- it's too short in the popup view.— assigned to @jpuri

**Comment by mcmire** [comment]
Also, the width of the network status area needs to be adjusted, as it's too short in the popup view.

**Comment by kevinghim** [comment]
> Also, the width of the network status area needs to be adjusted, as it's too short in the popup view.

Good call. I added that to the above list.

**Comment by Arsamin-info** [comment]
#3127 #12730 #12730 #7569 [Arsa min-info](@github)

**Comment by jpuri** [comment]
Feedbacks from @jakehaugen 

(1) When clicking “Save” from advanced it should automatically go back to the first screen (not force users to go “back” after saving).
(2) It currently say “10% Minimum” for the label on the first screen (blue link). Can we change it to “10% (minimum)“.
