### ISSUE TITLE
Resolve `.eth` domain names

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1315]
The idea of hijacking the URL bar is pretty appealing.

There's [talk of adding support for this to the WebExtension API](https://bugzilla.mozilla.org/show_bug.cgi?id=1343849#c2).

If this was added, we'd need to do a few things:

- Add a static site format to ENS
- Check when a new website `.ens` resolves to a static site format.
- Redirect to that site instead.

**Comment by flyswatter** [comment]
Worth noting that `ipfs` is having [a similar discussion](https://github.com/ipfs/in-web-browsers/issues/9).

**Comment by ramvi** [comment]
How is [ens-chrome-extension](https://github.com/cpacia/ens-chrome-extension) solving this? Worth taking a look at?

They're using a thin client instead of a third party node. Shouldn't change how URL bar is hijacked.

**Comment by danfinlay** [comment]
Looks like `ens-chrome-extension` does this by running a light client written in GO as a local process, and allowing the extension to access that.

If MetaMask wanted to provide this, we'd probably default to whatever provider the user has configured (with Infura as a fallback), and would need to consider what resource types we were able to support.

If we had an IPFS client built in, we could resolve IPFS hosted pages. If Swarm gets exposed over libp2p or webRTC, we should be able to resolve to Swarm pages.

**Comment by danfinlay** [comment]
We may also be able to cooperate with [portal.network](https://github.com/PortalNetwork/portal-network-browser-extension) on integrating their solution, which _I believe_ is an infura-like hosted resolver, but could probably be pointed at a user's own custom server, too.

**Comment by danfinlay** [comment]
The Gnosis team would like to see this issue's priority increase, because they have some urgent needs for it.

**Comment by Arachnid** [comment]
Please bear in mind that .eth won't be the only TLD, once we enable DNS integration. Ideally the protocol should be used to distinguish whether to resolve a standard website or some other service.

**Comment by schemata-nick** [comment]
Would be super excited for this one, especially in light of the recent DNS hack

**Comment by 26000** [comment]
Seems like this has been implemented in the latest version. But when i looked at Portal Network's website, it said something about its proprietary services, not a word about how to make my domain resolvable to my own IPFS website hash. Are there any docs? If not, they IMO should be added to @MetaMask/faq. I don't think we want yet another integration with a proprietary vendor-locked service, do we?

**Comment by bdresser** [comment]
@26000 some folks from Portal.network built the feature, so the splash page is sort of a shoutout. We're loading ENS data from the blockchain via Infura and IPFS content via Infura as well.

Read more on how the feature is implemented in MetaMask here: https://consensys.zendesk.com/hc/en-us/articles/360012782931.

And you can find some simple guides on how to host [here](https://gist.github.com/PhyrexTsai/cffcbfa1d752b9cf817d920dfcd1ec9f) or [here](https://gist.github.com/bitpshr/205b691082a26f70dc09f896cf972343).

**Comment by 26000** [comment]
@bdresser 
>oops
>You're not authorized to access this page

But the first link is what i needed, was looking for a hash converter. Thanks a lot!

**Comment by bdresser** [comment]
re-published the support article, you should be able to access now. 

closing this, released in 4.9.0!
