### ISSUE TITLE
GasModalPageContainer story: convert knobs and actions to controls / args

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13177]
**Describe the bug**
As part of a push to convert all stories that use deprecated `@storybook/addon-knobs` and `@storybook/addon-actions` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Convert `GasModalPageContainer` story in `ui/pages/swaps/swaps-gas-customization-modal/swaps-gas-customization-modal.stories.js` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Read the [MetaMask extension storybook documentation guidelines](https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page) to get a better understanding of writing stories. Providing MDX documentation although helpful, is a bonus and not a requirement for this issue.

To start storybook:
```
yarn storybook
```

**Requirements**
- [ ] Story has `argTypes` that align with component api / props
- [ ] All instances of `@storybook/addon-knobs` have been removed in favour of control args
- [ ] All instances of `@storybook/addon-actions` have been removed in favour of [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Any further improvements to the story interaction or documentation is a bonus

**Images**

<img width="1440" alt="Screen Shot 2021-12-28 at 8 20 25 AM" src="https://user-images.githubusercontent.com/8112138/147501143-499d387e-d53d-46ae-9318-64be89f65ab5.png">
<img width="1440" alt="Screen Shot 2021-12-28 at 8 20 48 AM" src="https://user-images.githubusercontent.com/8112138/147501181-7b5060d9-c6bb-4792-856d-5b2da419d83c.png">

**Comment by BoxedFruits** [comment]
hi! I would like to be assigned this issue. I have most of it done locally so will try to open the PR sometime this weekend after I look everything over with fresh eyes

**Comment by georgewrmarshall** [comment]
Hey @BoxedFruits, that's great! I have assigned you the issue looking forward to your PR
