### ISSUE TITLE
CountdownTimer story: convert knobs and actions to controls / args

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13172]
**Describe the bug**
As part of a push to convert all stories that use deprecated `@storybook/addon-knobs` and `@storybook/addon-actions` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Convert `CountdownTimer` story in `ui/pages/swaps/countdown-timer/countdown-timer.stories.js` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Read the [MetaMask extension storybook documentation guidelines](https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page) to get a better understanding of writing stories. Providing MDX documentation although helpful, is a bonus and not a requirement for this issue.

To start storybook:
```
yarn storybook
```

**Requirements**
- [ ] Story has `argTypes` that align with component api / props
- [ ] All instances of `@storybook/addon-knobs` have been removed in favour of control args
- [ ] All instances of `@storybook/addon-actions` have been removed in favour of [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)
- [ ] Remove unneeded stories in favour of one comprehensive story with all of the controls 
- [ ] Remove knobs that don't seem to do anything

**Images**
<img width="596" alt="Screen Shot 2021-12-28 at 8 01 35 AM" src="https://user-images.githubusercontent.com/8112138/147500242-4fe42d80-b11a-4be9-87c3-b2e67713af68.png">
<img width="1440" alt="Screen Shot 2021-12-28 at 8 06 27 AM" src="https://user-images.githubusercontent.com/8112138/147500294-7fcf0012-c8bf-48e0-8beb-5e1595ac4913.png">

**Comment by pietertolsma** [comment]
Hi, I would like to take on this issue!
