### ISSUE TITLE
FeeCard story: convert knobs and actions to controls / args

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13174]
**Describe the bug**
As part of a push to convert all stories that use deprecated `@storybook/addon-knobs` and `@storybook/addon-actions` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Convert `FeeCard ` story in `ui/pages/swaps/fee-card/fee-card.stories.js` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Read the [MetaMask extension storybook documentation guidelines](https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page) to get a better understanding of writing stories. Providing MDX documentation although helpful, is a bonus and not a requirement for this issue.

To start storybook:
```
yarn storybook
```

**Requirements**
- [ ] Story has `argTypes` that align with component api / props
- [ ] All instances of `@storybook/addon-knobs` have been removed in favour of control args
- [ ] All instances of `@storybook/addon-actions` have been removed in favour of [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Any further improvements to the story interaction or documentation is a bonus

**Images**

<img width="1440" alt="Screen Shot 2021-12-28 at 8 12 21 AM" src="https://user-images.githubusercontent.com/8112138/147500690-4f395943-d83a-4013-9781-52e68b878a45.png">
<img width="1440" alt="Screen Shot 2021-12-28 at 8 12 38 AM" src="https://user-images.githubusercontent.com/8112138/147500698-ed316444-b01a-4ba9-ac15-c571776fd0e7.png">

**Comment by Fastjur** [comment]
Secondly, could you please provide me with logical default values for the following props? They are not required props, I could also leave them blank by default.

- `smartTransactionsOptInStatus`
- `smartTransactionsEnabled`
- `supportsEIP1559V2`

**Comment by Fastjur** [comment]
Could you assign this issue to me? I have a PR open :)
