### ISSUE TITLE
ExchangeRateDisplay story: convert knobs and actions to controls / args

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13173]
**Describe the bug**
As part of a push to convert all stories that use deprecated `@storybook/addon-knobs` and `@storybook/addon-actions` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Convert `ExchangeRateDisplay ` story in `ui/pages/swaps/exchange-rate-display/exchange-rate-display.stories.js` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Read the [MetaMask extension storybook documentation guidelines](https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page) to get a better understanding of writing stories. Providing MDX documentation although helpful, is a bonus and not a requirement for this issue.

To start storybook:
```
yarn storybook
```

**Requirements**
- [ ] Story has `argTypes` that align with component api / props
- [ ] All instances of `@storybook/addon-knobs` have been removed in favour of control args
- [ ] All instances of `@storybook/addon-actions` have been removed in favour of [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Any further improvements to the story interaction or documentation is a bonus

**Images**
<img width="1433" alt="Screen Shot 2021-12-28 at 8 09 35 AM" src="https://user-images.githubusercontent.com/8112138/147500507-e553df8e-5071-4cbf-9584-1d16671222c6.png">
<img width="1440" alt="Screen Shot 2021-12-28 at 8 09 52 AM" src="https://user-images.githubusercontent.com/8112138/147500518-851b5d46-7d67-48e3-9cea-5e972047f115.png">

**Comment by Fastjur** [comment]
I'd like to pick this one up!

**Comment by pietertolsma** [comment]
Hi, I would like to take on this issue!

**Comment by pietertolsma** [comment]
This issue seems to have been fixed already. Can you close it?

**Comment by georgewrmarshall** [comment]
Thanks for the heads up @pietertolsma

**Comment by georgewrmarshall** [comment]
Completed in https://github.com/MetaMask/metamask-extension/pull/13660
