### ISSUE TITLE
SelectQuotePopover story: convert knobs and actions to controls / args

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13176]
**Describe the bug**
As part of a push to convert all stories that use deprecated `@storybook/addon-knobs` and `@storybook/addon-actions` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Convert `SelectQuotePopover` story in `ui/pages/swaps/select-quote-popover/select-quote-popover.stories.js` to use [controls](https://storybook.js.org/docs/react/essentials/controls) and [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Read the [MetaMask extension storybook documentation guidelines](https://metamask.github.io/metamask-storybook/?path=/story/getting-started-documentation-guidelines--page) to get a better understanding of writing stories. Providing MDX documentation although helpful, is a bonus and not a requirement for this issue.

To start storybook:
```
yarn storybook
```

**Requirements**
- [ ] Story has `argTypes` that align with component api / props
- [ ] All instances of `@storybook/addon-knobs` have been removed in favour of control args
- [ ] All instances of `@storybook/addon-actions` have been removed in favour of [action argType annotation](https://storybook.js.org/docs/react/essentials/actions#action-argtype-annotation)

Any further improvements to the story interaction or documentation is a bonus

**Images**

<img width="1440" alt="Screen Shot 2021-12-28 at 8 17 24 AM" src="https://user-images.githubusercontent.com/8112138/147500965-459c576d-de7b-4bf7-a362-00bbda225d41.png">
<img width="1413" alt="Screen Shot 2021-12-28 at 8 17 39 AM" src="https://user-images.githubusercontent.com/8112138/147500974-16a7e159-d92a-4d42-b09d-8f0c3620e57a.png">

**Comment by alexanderchao123** [comment]
@georgewrmarshall I'd like to work on this issue!

**Comment by georgewrmarshall** [comment]
Awesome! Assigned. Thanks @alexanderchao123, looking forward to your PR!

**Comment by georgewrmarshall** [comment]
Fixed https://github.com/MetaMask/metamask-extension/pull/15187
