### ISSUE TITLE
Money lost on metamask / pancakeswap

### ISSUE THREAD

**Issue by Monsieurmien** [MetaMask/metamask-extension#13171]
I transefered some BUSD on my metamask account.  I also transfered some BNB for the gass fee,  And I did a swap on pancake swap, from BUSD to BCOIN.
Everything was okay, but just after the confirmed transaction I did'nt receive anything and the account on my BCOIN and my BUSD on my metamask is at 0.
I really need your help 
transaction id : 0x088e79460f6b3fa68fa01a1f4c3b6e8f3fc64564194ee56d2829a51890dc82d6

Metamask account : 0xE2d28eC038Af863fe7d4bC781Cfc997838D8e04c

**Comment by adonesky1** [comment]
@Monsieurmien I'm not seeing the transaction hash you've provided on either Binance Smart Chain or Ethereum mainnet. Are you sure that the transaction went through?

**Comment by darkwing** [comment]
@Monsieurmien A more effective way of getting support would be through our official support channel:  http://support.metamask.io/
