### ISSUE TITLE
How the developer get hardware wallet status

### ISSUE THREAD

**Issue by myfocus** [MetaMask/metamask-extension#13185]
Hello, I am developing a Dapp. When the user imports the hardware wallet to connect to the Dapp through metamask, how do they know whether the current address is from the hardware wallet? Are there any parameters? window.ethereum?

**Comment by Josphefixit** [comment]
Contact this email josephlucas30bb@gmail.com

**Comment by Gudahtt** [comment]
At the moment there is no way for the dapp to know whether the account is from a hardware wallet or not.

Please feel free to suggest this as a feature in our community forum though! https://community.metamask.io/
