### ISSUE TITLE
MetaMask cannot connect to xDAI network on Firefox

### ISSUE THREAD

**Issue by aminlatifi** [MetaMask/metamask-extension#13187]
**Describe the bug**
Today I couldn't connect my MetaMask on Firefox to xDAI network. Even clearing its setting and trying to set it again was unsuccessful. 
**Screenshots**
![image](https://user-images.githubusercontent.com/5684607/147845180-bf7dd9ab-9d22-42a0-b75d-f911d9fdc03b.png)
**Browser details (please complete the following information):**
 - OS: MacOS
 - Hardware Wallet: No
 - Browser: Firefox 95.0.2
 - MetaMask Version: 10.8.1

**Comment by darkwing** [comment]
I just tested this and it worked with no problems; it could have been a momentary downtime or connection issue.  Could you please try again?

**Comment by aminlatifi** [comment]
> I just tested this and it worked with no problems; it could have been a momentary downtime or connection issue. Could you please try again?

I closed my firefox and reopened it, then it was solved!!!

**Comment by Gudahtt** [comment]
Great, thanks for following up!
