### ISSUE TITLE
Error from contract returned as string

### ISSUE THREAD

**Issue by mailbox01** [MetaMask/metamask-extension#13188]
**Describe the bug**

Metamask error is not coming in JSON /Object format on using try catch block 

**Steps to reproduce (REQUIRED)**

1) Cancel the transaction from Metamask 
2) Or Any exception from smartContract 

**Expected behavior**
Error Should be on JSON / Object format 
**Screenshots**
<img width="239" alt="image" src="https://user-images.githubusercontent.com/31744360/147847832-b04043e8-1c31-4b71-b185-d39a0d04d63d.png">
**Browser details (please complete the following information):**
 - OS: Windows 10 
 - Browser: Version 96.0.4664.110 (Official Build) (64-bit)
 - MetaMask Version: MetaMask 10.8.1

**Comment by Gudahtt** [comment]
It looks like user rejections are correctly returned to the dapp as Error objects with a `code` property that complies with [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193#provider-errors), as are contract errors.

The error message is what you're looking at. I agree that it's a bad error message and we should improve it, but the error itself is in the correct format.
