### ISSUE TITLE
Update toggle component for consistency style across products

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#13199]
**User Story**
As a user, I want to see consistent toggle style across products.

[User story on Notion](https://www.notion.so/As-a-user-I-want-to-see-consistent-toggle-style-across-products-a0bb6ff726bf424685979b7e01423bd8)
[Designs on Figma](https://www.figma.com/file/aWgwMrzdAuv9VuPdtst64uuw/MetaMask---Design-System)

**Steps to reproduce**
1. Go to "Settings" and check the toggle style

**Screenshots**

<img width="1714" alt="Screen Shot 2022-01-04 at 00 21 17" src="https://user-images.githubusercontent.com/34968356/148005357-e4d2f27e-3609-45e4-8957-790f64564a17.png">

**Task**
Choosing a design for the toggle and updating the component on extension and mobile.

**Success criteria**
Having a consistent toggle style across products.

**Comment by georgewrmarshall** [comment]
Closing in favour of https://github.com/MetaMask/metamask-extension/issues/20154
