### ISSUE TITLE
 Advanced Gas Fee Modal: Updating the trend arrows

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#13195]
- Update the down arrow to point from upper left to lower right.
- Add arrow for level trend, horizontal gray arrow.
- Remove the trend retaining when the trend is level

**Comment by arispoli16** [comment]
> * Update the down arrow to point from upper left to lower right.
> * Add arrow for level trend, horizontal gray arrow.
> * Remove the trend retaining when the trend is level

eip-1559v2
gas .01
