### ISSUE TITLE
Error: Unexpected message when using Trezor

### ISSUE THREAD

**Issue by Ankarrr** [MetaMask/metamask-extension#13213]
**Describe the bug**
Get "Error: Unexpected message" when trying to sign a transaction using Trezor

**Screenshots**
![截圖 2022-01-05 下午3 20 51](https://user-images.githubusercontent.com/8311552/148176605-c4d8735c-4b1c-44d0-aa7d-5ea84f6fccaf.png)

**Browser details (please complete the following information):**
 - Chrome
 - MetaMask Version: 10.8.1

**Comment by werdnajoc** [comment]
I have the same problem.

**Comment by darkwing** [comment]
@Ankarrr Could you tell us more about this transaction or provide steps to reproduce?
