### ISSUE TITLE
Warn users about the risks when exporting the SRP

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#13229]
**User Story**
As a user, I want know the risks when I’m exporting my seed phrase.

Warn the users about risks when revealing the seed phrase and remind them how to use it responsibly. Users own their SRP which gives them access to restore all their accounts and private keys. We want to advice users before they reveal the SRP.

Related GH
https://github.com/MetaMask/metamask-extension/issues/10466

Figma link: https://www.figma.com/file/8z4Csc3wlOIkUz2OP1eTZW/Secure-UX-Improvements?node-id=44%3A1574
Notion link: https://www.notion.so/Warn-me-about-risks-when-I-m-exporting-my-seed-phrase-f610550a8c464240a46880b06ebbdc42

## Acceptance **criteria**
1. Redesign of the first screen after you click ‘Reveal Secret Recovery Phrase’ is updated to reflect the new design
2. A modal ‘Keep your SRP safe’ is displayed after the user enters his password and clicks ‘next’
3. After the user holds to reveal a button on this modal, he has access to the SRP
4. A metric tracking system the meets the below described criteria is implemented.
5. Security tasks is implemented
6. Translations are implemented before release.

##
1. Update design of the "Reveal Secret Recovery Phrase" screen (Option: Settings/Security & Privacy/Reveal Secret Recovery Phrase). The new design according to the Figma mockup:
![image](https://user-images.githubusercontent.com/49436614/148515566-da323401-54b6-4fed-abeb-6f562e5cdd3d.png)
**Blue text on the mockup are links to the external web pages:**
Secret Recovery Phrase (SRP) link: https://metamask.zendesk.com/hc/en-us/articles/4404722782107-User-guide-Secret-Recovery-Phrase-password-and-private-keys
Non-custodial wallet link: https://metamask.zendesk.com/hc/en-us/articles/360059952212-MetaMask-is-a-non-custodial-wallet

**Buttons:** 
_Next button_ has same functionality as the current implementation (e.g. disabled/enabled status, check the password, etc.). If the password is OK, on click   will open the modal screen from the AC below (‘Keep your SRP safe’).
_Cancel button_   will close the option and return to the wallet (Assets screen)

2.  Develop a new modal screen with the "Hold to reveal" component on it, mockup below.
![image](https://user-images.githubusercontent.com/49436614/148519015-b6d573ef-11f9-4311-a069-4ce782680fb0.png)
_X button_ on the top right side will close the modal
"_But pishers might_" link: https://metamask.zendesk.com/hc/en-us/articles/4407169552667-Scammers-and-Phishers-Rugpulls-and-airdrop-scams
On holding the Reveal button "enough  time" (The time property of the component is 4 seconds ) the screen from the AC below will be shown

3. Redesign screen in the Reveal flow with tabs: Text and QR code, mockup of the redesigned screen is below.
![image](https://user-images.githubusercontent.com/49436614/148395422-077d709b-86ed-49ce-88f5-8bb8f0ff3083.png)

## **NOTE:** QR code tab:  Dan M. comment from Slack:
"There is an issue where you need to add a QR code. You should be able to use the QrView component, the same way that is used in ui/components/app/modals/account-details-modal/account-details-modal.component.js "
### The data property passed to that component will be the seed phrase

_Close button_ will close the option and return to the wallet (Assets screen)
_Copy to clipboard button_ will:

- Copy the SRP to clipboard, 
- Change the text on the button from 'Copy to clipboard' to '_Copied! It will be stored for one minute.!_'. 
![image](https://user-images.githubusercontent.com/49436614/148993389-53c7fabf-1022-447a-aac4-f3ca3617adf0.png)

Links from the mockup:
_Secret Recovery Phrase (SRP)_ link: https://metamask.zendesk.com/hc/en-us/articles/4404722782107-User-guide-Secret-Recovery-Phrase-password-and-private-keys
_Non-custodial wallet_ link: https://metamask.zendesk.com/hc/en-us/articles/360059952212-MetaMask-is-a-non-custodial-wallet

## **Important security tasks:**

1. We should hide/un-reveal the SRP after some time when the user reveals it on the full screen extension otherwise it might be left exposed for some time if the user doesn’t leave this screen and doesn’t close the tab. 
Instead of the above, we have agreed that on the tab lost focus event the MM extension screen (in the full screen view mode) will be redirected to the password screen in the flow.
We agreed that this feature will be implemented on the tab lost focus
2. We should clear the SRP from clipboard after **1 minute** when the user copies it, so the user doesn’t accidentally pastes it somewhere else. 
**Tech hints** from Dan M (Slack comment: https://consensys.slack.com/archives/C02GH833686/p1641832302036200?thread_ts=1641831030.033800&cid=C02GH833686).: 
- The method we use to clear the clipboard (clearClipboard in ui/helpers/utils.js) should still be for this purpose.
- As for the time elapsed mechanism... off the top of my head: a setTimeout call in the component , that only calls the clearClipboard method **if the current clip board matches the seed phrase**
_QR code tab_ will shown already implemented QR code which is currently disabled

## **Metrics**

Product managers and designers want to evaluate how efficient it was to warn users about risks, so we want to track the number of users that go through this flow and how they behave. Relevant metrics are:

![image](https://user-images.githubusercontent.com/49436614/150345602-c6d2ec8b-54af-41eb-a852-1c4bab0afe2e.png)
The metrics definition table is on the Notion!

**Comment by EHaracic** [comment]
@danjm will provide the metrics definition.

**Comment by tyuen** [comment]
How about saying: "Your Secret Recovery Phrase (SRP) allows anyone to control your wallet including withdrawing all funds."

**Comment by amerkadicE** [comment]
Blocked by [13260](https://github.com/MetaMask/metamask-extension/issues/13260)

**Comment by amerkadicE** [comment]
This is moved to testing/review without _clear clipboard after 1 minute_ feature as @danjm suggested.
Clearing the clipboard is not allowed by the browser API if a user does not focus on a tab.
UX for the copy button will be updated.

**Comment by amerkadicE** [comment]
Resolved with https://github.com/MetaMask/metamask-extension/pull/17232
