### ISSUE TITLE
Remove unnecessary space in network dropdown

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#13231]
If you hide the test networks in the dropdown, unnecessary empty space is shown in the dropdown.

![Screenshot from 2022-01-06 11-21-30](https://user-images.githubusercontent.com/7499938/148401718-0ae80ad4-5cf0-4747-a6be-7fb92db73446.png)

How to repro:

https://user-images.githubusercontent.com/7499938/148401738-821ac834-26e4-40c4-92d5-8b17c7b78f32.mp4

That space should not be present. Probably resolvable with some simple css

**Comment by Gtonizuka** [comment]
This was fixed on
https://github.com/MetaMask/metamask-extension/commit/b9093e2a4d6a18a4111429a76dc8da4c2aabcd1d#diff-aef718039acac30c40191fc19fda4052978b84f7321f49cbc93c220eac6fabe3

Closing this bug for now
