### ISSUE TITLE
How can I replace the old tx (can't find in the active list)?

### ISSUE THREAD

**Issue by thickforest** [MetaMask/metamask-extension#13259]
**Describe the bug**
A few days ago, I send a transaction using the mobile APP, but it has not been confirmed. Now the mobile APP has been uninstalled, I want to replace that transaction , How should I do? (I can only find the exact nonce id on https://etherscan.io)

**Browser details :**
 - MetaMask Version: 10.8.1

**Comment by darkwing** [comment]
Hello @thickforest.  To do what you're asking:

1.  Set a higher nonce than the transaction you want to replace
2. Ensure that your gas fee is at least 10% higher than the transaction you want to replace
