### ISSUE TITLE
Allow wallet_addEthereumChain for Ethereum networks 

### ISSUE THREAD

**Issue by kurushdubash** [MetaMask/metamask-extension#13269]
With [EIP-3085](https://eips.ethereum.org/EIPS/eip-3085), we're able to programmatically add new networks / chains to metamask which is a great experience for users versus having to manually add a custom RPC. 

However, [Metamask doesn't allow adding/updating chains programmatically](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js#L124) that have a chain id that corresponds to any of the default MetaMask chains (basically the Ethereum networks). Although adding a custom RPC will allow you to add an RPC with any of the default chain ids.

This would be really useful for allowing custom RPCs in a programmatic way or at the least be able to add duplicate Eth networks.

An example to validate:
```
const params = [{
    chainId: '0x1',
    chainName: 'Ethereum Mainnet (Localhost)',
    nativeCurrency: {
      name: 'Eth',
      symbol: 'Eth',
      decimals: 18
    },
    rpcUrls: ['https://localhost:8000'],
    blockExplorerUrls: ['https://etherscan.io/']
  }]

const args = { 
  method: 'wallet_addEthereumChain', 
  params: params
}
window.ethereum.request(args)
```

will result in 
```
MetaMask - RPC Error: May not specify default MetaMask chain. {code: -32602, message: 'May not specify default MetaMask chain.'}
```

_Note: I'm not able to create a feature request on community.metamask.io - there does not seem to be a way to post new topics._

**Comment by kurushdubash** [comment]
Any update on this?

**Comment by BrennerSpear** [comment]
+1!

**Comment by Mirado97** [comment]
+1

**Comment by the42** [comment]
Just so I understand correctly: With this limitation in place, it is essentially not possible to run a full/light node and connect to it right?

**Comment by kurushdubash** [comment]
Not programatically - you will have to manually configure the RPC through the Metamask UI.

**Comment by the42** [comment]
Because of #13168 and #13167 it is actually completely impossible for me to add any local network.

**Comment by AntonyHatchet** [comment]
Upvote!

**Comment by adonesky1** [comment]
This is resolved by https://github.com/MetaMask/metamask-extension/pull/16733
