### ISSUE TITLE
Make default icons the same on mobile and extension

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#13264]
### **User Story**
As a new user I want Blockies identicon as a default and identicon settings option to be changed as on the mobile device.

Context: Currently we offer two options (jazzicon and blockie) to use as account icon. On mobile the default is blockies while on extension the default is jazzicon. This might confuse new users that are comparing the same account on each platform. 

**Figma/Notion links:** 
**Figma**: https://www.figma.com/file/b1YjR0OG4RRQgEChYfwbey/UI-audit?node-id=1060%3A1897
**Notion**: https://www.notion.so/Make-default-account-icons-the-same-on-mobile-and-extension-jazzicon-or-blockie-4188ebb3412f4c849c89405331a695b8

### Acceptance Criteria:

1. All new users have Blockies as default
2. Existing users continue with their previously selected option
3. Settings page is updated to reflect the changes:
(MM Extension option: _Settings/General/Use blockies identicon-Account Identicon_)
 
    **New settings on Extension:**
    
![image](https://user-images.githubusercontent.com/49436614/148792311-786cad53-d1eb-4b32-932b-5d4d4b017d90.png)
    
    **Current settings on Extension:** 
    
![image](https://user-images.githubusercontent.com/49436614/148792583-0ff6366d-91ac-43dd-8b93-44c907b55efd.png)

Things to update

1. Update the name of the setting
2. Add description for the text
3. Display both identicons and make them clickable.

![image](https://user-images.githubusercontent.com/49436614/149142584-9bcf2b9c-541d-49f5-ae44-4ba0acc58d58.png)
### Note(s): 
- The icons on the option are generated dynamically based on the current account icons!

**Comment by bschorchit** [comment]
The first acceptance criteria listed here should be updated to "All new users have Jazzicon as default". I've just updated it on Notion as well.
