### ISSUE TITLE
Persist config encrypted to infura & serve over IPFS

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1326]
So that restoring from seed can also recover settings.

Maybe "save settings" is a tx that checks the hash in on-chain, maybe we save it locally.

Maybe work with other wallets to agree on an "account config standard", which can include address book, preferred fiat conversion, and other common features.

**Comment by frankiebee** [comment]
I would want something like this as option though not a default.

**Comment by danfinlay** [comment]
Closing in favor of #1459.
