### ISSUE TITLE
Develop "Hold to reveal" component

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#13260]
**User Story**
Develop "Hold to reveal" component/control 

**Figma link:** 
https://www.figma.com/file/8z4Csc3wlOIkUz2OP1eTZW/Secure-UX-Improvements?node-id=44%3A1387)

**Task(s)**
Develop "Hold to reveal" component, according to the Figma mockup

**Acceptance criteria**
- Develop "Hold to reveal" component, according to the Figma mockup below. Please see design and functionality on the link:
https://codepen.io/antonela/full/eYEKRxL.

![image](https://user-images.githubusercontent.com/49436614/148393997-9fb3a1b1-a3ae-41ac-9845-7e99ef5adf4e.png)

- The component will have two properties: Label, and Time in seconds.
- The component will have a callback mechanism to notify the parent component about the result (completion).

Notes: 
- We need to develop the unit tests for the component/control
- Consensys (Zoom meeting 10.02.2022) decided to develop the component in smaller size from the figma design

**Comment by darkwing** [comment]
@EHaracic Is this meant to be a mobile feature?

**Comment by EHaracic** [comment]
@darkwing both of them, it will be shared between the mobile and extension.
