### ISSUE TITLE
Fix block link explorer on custom networks

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#13262]
### **User Story**
As a user, given I am on a custom network, when I click the block explorer icon in Activity details, I want to go to the correct block explorer for that network - today if the block explorer field is not added correctly, it shows the wrong explorer and gives an error.

**Figma/Notion links link:** 
https://www.notion.so/Fix-block-explorer-link-on-custom-networks-738376e799864b71b76793a588034dd2

### **Steps to reproduce**

1. Add a custom network on MetaMask, but don’t add the “Block Explorer URL” or add a wrong “Block Explorer URL”
2. Go to the initial screen on MetaMask
3. Click on the three dot menu next to your account
4. Notice the “View Account on Etherscan” copy or the wrong link
5. Click on it and notice MetaMask opening up an error page

###  Task/Acceptance criteria 

1. If there’s no “Block Explore URL” for the custom network, show the text “Add a block explorer” instead of “View on Etherscan/Block Explorer” or “View Asset in Explorer” for accounts, assets and transactions on the respective menus. @filipsekulic found five places when we have the option for update (on the Notion we have a three places): 
- On the three dot  accounts menu: 
![image](https://user-images.githubusercontent.com/49436614/157210877-db9e4e30-d827-46d8-90ae-1448e5809d72.png)

- Account details - View on Etherscan
![image](https://user-images.githubusercontent.com/49436614/157212703-f3546552-05d4-4805-aa8e-26e888164dde.png)
![image](https://user-images.githubusercontent.com/49436614/157212886-61ed83b0-d58d-4d81-a9e3-40b4d281744a.png)

- On the three dot asset menu
![image](https://user-images.githubusercontent.com/49436614/157211065-006e7c65-6c13-421b-89cf-3f78a558f4b8.png)

- On the activity details:
![image](https://user-images.githubusercontent.com/49436614/157211381-31e697b1-abc8-4445-93c4-399a2b66483f.png)
![image](https://user-images.githubusercontent.com/49436614/157211515-52af32fd-4a4e-4dc8-a826-11a34f69404b.png)

- On the Send flow when a new account added
![image](https://user-images.githubusercontent.com/49436614/157211783-bbb847a8-2536-4802-9670-a669b9f37315.png)
![image](https://user-images.githubusercontent.com/49436614/157211917-d23d2f4e-44f8-4fd8-9813-c9236c74b06c.png)

2. Clicking on "Add a block explorer" should take the user to the Edit Network page for the current network (screenshot below).

<img width="1034" alt="Screen Shot 2022-02-02 at 01 01 27" src="https://user-images.githubusercontent.com/34968356/152091192-f4948845-4c29-473e-a27f-3868aa81f881.png">

### Notes
Acceptance criteria updated based on the Barbara comment: https://github.com/MetaMask/metamask-extension/issues/13262#issuecomment-1027552173

**Comment by bschorchit** [comment]
Task/Acceptance criteria should be updated to:

1. If there’s no “Block Explore URL” for the custom network, show the text “Add a block explorer” instead of “View on Etherscan/Block Explorer” or “View Asset in Explorer” for accounts, assets and transactions on the respective menus.

2. Clicking on "Add a block explorer" should take the user to the Edit Network page for the current network (screenshot below).

<img width="354" alt="Screen Shot 2022-02-02 at 00 59 36" src="https://user-images.githubusercontent.com/34968356/152091054-d24a32ce-f3ae-4060-ab5b-ead4ed56d00d.png">

**Comment by EHaracic** [comment]
Thanks @bschorchit

**Comment by EHaracic** [comment]
@bschorchit 

Should we use same icon at is now on the "View on Etherscan/Block Explorer” or “View Asset in Explorer” menu options.
![image](https://user-images.githubusercontent.com/49436614/152322175-4f38b124-4802-45bc-8c06-46dd90aed980.png)

**Comment by bschorchit** [comment]
> Should we use same icon at is now on the "View on Etherscan/Block Explorer” or “View Asset in Explorer” menu options or we need a new icon. If yes can you please provide the icon.

We should use the same icon, @EHaracic .
