### ISSUE TITLE
Add method to restore vault to new seed phrase

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1328]
For when:
- When a user loses their seed phrase & password and wants to start over.
- An advanced wants to restore a different vault.

**Comment by Zanibas** [comment]
We already do the second part through 'forgot password', and we used to be able to do the first, but we thought it'd be unnecessary for new users to want to just 'start over'.

Do we want to just redirect users back to the `new den` screen?

**Comment by danfinlay** [comment]
We do this via forgot password, like you said.
