### ISSUE TITLE
Add metrics related to transaction simulation failures

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#13286]
### Background
[Original issue content from Dan]
> When we estimate gas limit in the transaction controller, a `simulationFails` property is added to the txMeta if the gas estimation failed. We should add a metrics event to track when that happens.
> 
> We should also add a metrics event to track clicks of the "I will try anyways" button that is rendered if that failure happens:
> 
> <img src="https://user-images.githubusercontent.com/7499938/149153506-98db9429-2081-4be5-a535-36eed2a808f5.png" width="200" />
> 
> Finally, we should add an indication of whether the simulation had failed to the metrics event we capture upon confirmation/signing of a transaction.
> 

### Scope
1. Add a new boolean property to Transactions events named gas_estimation_failed and pass true value to it whenever `simulationFails` property is added to the txMeta
2. Append `gas_estimation_failed` within `ui_customizations` property of Transactions events whenever we display gas estimation failed warning. 
This will help us identify in which transactions we're failing to estimate gas and how the user is behaving. We don't need to specifically track clicking on the I will try anyways as we initially can defer that from the user submiting the transaction afterwards.

Question for the team: when the gas estimation fails, do we receive more information on it (e.g. a reason or error message)? If yes, it would be interesting to capture it as well within metrics.

**Comment by Gudahtt** [comment]
>When we estimate gas limit in the transaction controller, a simulationFails property is added to the txMeta if the gas estimation failed. We should add a metrics event to track when that happens.

Also this metric event should include the contract address, chain ID, and the gas settings used. That can help us guess which events are caused by insufficient gas, and which are caused by contracts that the simulation fails for.

**Comment by brad-decker** [comment]
Would it be sufficient @danjm and @Gudahtt to add a `simulation_failed` property to the other transaction events? 

so `Transaction Rejected -> segment by simulation_failed` shows how many people rejected transaction because of the warning
and
`Transaction Approved -> segment by simulation_failed` shows how many people ignored the warning.

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/13286?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by segun** [comment]
The i18n key is simulationErrorMessageV2
