### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AXCD1256** [MetaMask/metamask-extension#13294]
### Describe the bug

I am trying to stake Time on Wonderland as I did many times in the past. Once I press the Stake butto I get an "execution reverted" error message

### Steps to reproduce

1. In https://app.wonderland.money/#/stake
2.Connect Metamask Extension and log in 
2. Enter TIME amount to stake
3. Press STAKE TIME
4. Get "Execution Reverted" Error message

### Error messages or log output

```shell
{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32000,"message":"execution reverted"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"execution reverted\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923"}
```

### Version

10.8.1

### Browser

Brave

### Operating system

Windows

### Hardware wallet

Ledger

### Additional context

Same set up so far never had any issue.

**Comment by darkwing** [comment]
@AXCD1256 So this is something that's worked in the recent past but suddenly isn't working?  Could it be a balance issue?  Any more context you can provide?

**Comment by mqklin** [comment]
@AXCD1256 high chances this is not MetaMask problem, but Wonderland smart contracts problem. Maybe you have insufficient balance, or not allowed to complete an operation, or any different issue. You should ask Wonderland's devs about this.

**Comment by AXCD1256** [comment]
Thank you for your reply.

Yes, After checking I am ashamed to say that it is a simple balance
issue....(too bad ..)
Should I close my request ans how (soory I am new to Git Hub)

Il giorno gio 13 gen 2022 alle ore 14:05 David Walsh <
***@***.***> ha scritto:

**Comment by Gudahtt** [comment]
Thanks for the follow-up @AXCD1256 ! I have closed the ticket. In the future if you are unsure whether something is a bug or not, I'd recommend contacting our support team first instead.

**Comment by AXCD1256** [comment]
OK I will for sure do it!

Il giorno ven 14 gen 2022 alle ore 17:28 Mark Stacey <
***@***.***> ha scritto:
