### ISSUE TITLE
Show received transactions in transaction history

### ISSUE THREAD

**Issue by johnwhitton** [MetaMask/metamask-extension#133]
When looking at Transaction History for a specific account, do not see any incoming transactions

Steps to reproduce
1) Start MetaMask
2) Go to the First Accounts Detail
3) Copy the address 
4) Go to a faucet (e.g. https://zerogox.com/ethereum/wei_faucet) enter the address and send funds
5) Go back to Metamask and wait a few minutes (should see the Account has now been funded with 5 Ethereum)
6) Go into the account detail and click the Transactions drop down
7) No transactions is displayed

Speaking with @flyswatter this is because currently the transaction drop down only displays transactions sent from this account.

**Comment by frankiebee** [comment]
https://etherscan.io/apis has a awesome call for transactions for a given account

**Comment by flyswatter** [comment]
We are now considering #565 as part of this, to close this issue we should show incoming contract transactions as well.

**Comment by cjeria** [comment]
@whymarrh Here's the incoming TX design. Things that are differ from other TX's:

- Tx label should say "Deposit"
- remove the "-" minus sign from the value

and that should be it! Lemme know if you have any Q's

![image](https://user-images.githubusercontent.com/597770/51858900-fc45cc80-231c-11e9-8450-01071a3e0280.png)

Link to figma: https://www.figma.com/file/MjWpMvSd9QwZJf3gwDQ4EepH/MetaMask-Component-Library?node-id=416%3A99

**Comment by chikeichan** [comment]
- [ ] Filter selectedAddressTxList by both `from` and `to` values
- [ ] Implement UI to handle deposits
- [ ] Filter selectedAddressTxList by both `from` and `to` values (ERC20)
- [ ] Create and Test `tx-polling` background controller to get recent txs from etherscan
- [ ] Update/Merge transactions with recent txs

**Comment by bdresser** [comment]
This is supported in GABA! Once we migrate the transaction controller this will be easier.

**Comment by whymarrh** [comment]
Refs https://github.com/MetaMask/gaba/pull/33 in particular

**Comment by step21** [comment]
Is this now supported, especially also on mobile? Or will it be?

**Comment by whymarrh** [comment]
This is available on mobile, and is in the next extension release

**Comment by c0dehunter** [comment]
Interested in this too. I use Chrome extension and don't see received transactions in History. I need to always check this on Etherscan.

**Comment by sebastiantf** [comment]
> This is available on mobile, and is in the next extension release

Is it really available on MetaMask Mobile? Because I see the same txn history on both Chrome and Mobile with no internal txns shown.

Is this feature deployed right now? Hoping to see this implemented fast.

**Comment by whymarrh** [comment]
@sebastiantf this feature is available in the extension today. It is not enabled by default. You can enable it in settings, under _Security & Privacy_.

**Comment by sebastiantf** [comment]
I already have it enabled but still can't see the internal txns in my txn history on MetaMask.

This issue is about showing internal txns on MetaMask, right?

**Comment by whymarrh** [comment]
What are you calling "internal" transactions?

**Comment by sebastiantf** [comment]
On etherscan you can see the list of internal txns for a particular address. You can receive crypto by internal txns. But MetaMask txn history  doesn't show internal txns.

**Comment by whymarrh** [comment]
I don’t know what you’re referring to but,regardless, you seem to be having an issue. Can you open up a new issue with a description of what you currently see and what you’re expecting to see? Thanks.

**Comment by sebastiantf** [comment]
Ok @whymarrh

**Comment by Vikram710** [comment]
For getting incoming transaction currently meta mask is calling 
`let url = `${apiUrl}/api?module=account&action=txlist&address=${address}&tag=latest&page=1`;` i don't this this will list the erc20 token transfers ( incoming) 
is there any specific reason why we don't add 
`let url = `${apiUrl}/api?module=account&action=tokentx&address=${address}&tag=latest&page=1`;` which gives list of erc20 receives
