### ISSUE TITLE
[Bug]: When Editing a network's blockchain explorer link it would auto delete whatever I type.

### ISSUE THREAD

**Issue by federicosan** [MetaMask/metamask-extension#13308]
### Describe the bug

I am at the network configuration edit view on metamask extension on chrome, when I try to type the explorer for that network it will delete it right away after I type any character or paste any address. I had to click save really fast.

### Steps to reproduce

1.
Try editing on a mac book pro any blockchain explorer on any network.

### Version

10.8.1

### Browser

Chrome

### Operating system

MacOS

### Additional context

None

**Comment by ForestTigerKing** [comment]
@danjm   pr #13325 was closed，so I can't reply to your message，i reply it here.   I solve this problem, but e2e test keeps reporting errors，the e2e test  local environment was not built successfully, so it was difficult to troubleshoot problems, so i closed this pr temporarily.
