### ISSUE TITLE
[Bug]: EIP-1559 v2 Site Suggested gas fee bugs

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#13312]
### Describe the bug

Bugs that @jakehaugen uncovered during UI acceptance testing.

These two bugs pertain to "site suggested" gas fees. The latest build linked on [Slack](https://consensys.slack.com/archives/C021UN08FBJ/p1642010438018600) was used.

### Steps to reproduce

1. The site suggested price does not appear to be selected by default (at least on UniSwap, still going to “Market”).
2. The estimate in the “edit” dialog is showing 0 for everything. So, something not making it into the dialog.

![image (2)](https://user-images.githubusercontent.com/6951929/149417894-92b93d49-edf1-4961-b404-d146dc02ecfe.png)

### Version

10.8.2

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Test build

**Comment by jpuri** [comment]
@kevinghim : I am unable to replicate it in test-app, I need to check issue with uniswap specifically:
<img width="1438" alt="Screenshot 2022-01-14 at 12 10 55 PM" src="https://user-images.githubusercontent.com/2182307/149463244-d4483644-0296-4650-8a0b-219431cad84d.png">

**Comment by jpuri** [comment]
I looked into transaction coming from uniswap on rinkeby network and it appears that uniswap is not sending transaction params:

<img width="1436" alt="Screenshot 2022-01-14 at 12 29 59 PM" src="https://user-images.githubusercontent.com/2182307/149465380-f6691f6a-1214-4bde-9ad1-8d6c7849a8cc.png">
