### ISSUE TITLE
[Bug]: RPC errors

### ISSUE THREAD

**Issue by ColtraneNadler** [MetaMask/metamask-extension#13327]
### Describe the bug

RPC Error - Internal JSON-RPC Error (code: -32603)

randomly all requests to a web3 site will return this error. 
And therefore no data loads.

![img](https://i.imgur.com/4GS4Wjg.png)

### Steps to reproduce

1. Load site https://www.morpheusswap.app/

### Error messages or log output

```shell
MetaMask - RPC Error: Internal JSON-RPC error. 
{code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
code: -32603
data: {code: -32000, message: 'header not found'}
message: "Internal JSON-RPC error."
```
```


### Version

1

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

**Comment by darkwing** [comment]
This is usually a signal that Infura is under very heavy load.  Do you still get this error @ColtraneNadler ?
