### ISSUE TITLE
[Bug]: Update global link hover color

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13335]
**Description**
Hovering over a link or `<a>` tag that doesn't have any custom css turns orange rather than a variation of blue.

**Expected behaviour**
Link turns light blue(`--Blue-400` or `#1098fc`) instead of orange.

**Screenshots**
<img width="1440" alt="Screen Shot 2022-01-17 at 10 17 15 AM" src="https://user-images.githubusercontent.com/8112138/149812845-9ee0fe7f-3671-484e-b666-284364a88f2d.png">

**Comment by mradziwon** [comment]
Hi @georgewrmarshall, can I change it?

**Comment by georgewrmarshall** [comment]
@mradziwon I think @digiwand is going to take this one thanks!

**Comment by mradziwon** [comment]
Ok np, I wrote the comment at the same time as the task assignment. Maybe next time :)

**Comment by digiwand** [comment]
Hello 👋

I've updated the global link hover color, `a:hover` here https://github.com/MetaMask/metamask-extension/pull/13344, and I've noticed this impacts other links with the classes `.warning` or `.error`. How should we proceed with these instances? Should we use an orange color from our design system for these links with `.warning` or `.error`?

![MM Import Account hover on warning](https://user-images.githubusercontent.com/20778143/150021568-d2fe6657-0f39-4825-8207-491de2f4dc77.gif)


Also, do you have repo steps to get to the UI in the screenshot? I am not seeing that state in our codebase and I've been attempting to use NFT addresses to reach that state on the "Import Tokens" page.

**Comment by digiwand** [comment]
For documentation purposes:
The screenshot is referencing a new UI that has not been merged yet. see: https://github.com/MetaMask/metamask-extension/pull/13271

**Comment by georgewrmarshall** [comment]
@digiwand yes that's my bad! Apologies.

**Comment by digiwand** [comment]
@georgewrmarshall no apologies needed! just wanted to drop it in in case anyone else happens to be looking for it
