### ISSUE TITLE
Metamask doesn't display correc t balance from UNISWAP swap

### ISSUE THREAD

**Issue by Luzis** [MetaMask/metamask-extension#13338]
**Describe the bug**
Yesterday, I swapped 1.463117266158613 Ether
**https://etherscan.io/address/0x3823d6b8759c6941f8e92b839f40764b6249c015**
against 1,300 Polkabase (PBASE)
**https://etherscan.io/address/0x3823d6b8759c6941f8e92b839f40764b6249c015#tokentxns**
BUT my METAMASK wallet only shows me 900.682PBASE
![Metamask_PBASE](https://user-images.githubusercontent.com/79361122/108594032-d5311c00-7377-11eb-83ff-c2152cf8c17c.png)
Can somebody help me out.
Thanks

**Comment by bschorchit** [comment]
Please use the support link within MetaMask app for this.
