### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by jakehaugen** [MetaMask/metamask-extension#13346]
### Describe the bug

- [x] Proposing removing the orange highlight on the "High probability" copy. It seems too "warning" like? Instead, let's include that message in the the copy below: "High probability, even in volatile markets. Use Aggressive to cover..."  
<img width="384" alt="Screen Shot 2022-01-18 at 3 33 25 PM" src="https://user-images.githubusercontent.com/11967476/150029431-20971251-e8b9-4ce5-a429-0c87a17dbba0.png">

- [ ] Bell curve images not centered, will need to re-export with equal whitespace on either side to account for the text. @jakehaugen can help format and export when needed. 
<img width="772" alt="Screen Shot 2022-01-18 at 3 35 22 PM" src="https://user-images.githubusercontent.com/11967476/150029668-6ef2d607-ab6a-41fa-954b-9b477ee044c8.png">

- [x] Text color of time estimate between the "edit" screen and transaction screens should match (i.e. should be green in both places in screenshot).
<img width="1040" alt="Screen Shot 2022-01-18 at 3 37 25 PM" src="https://user-images.githubusercontent.com/11967476/150029908-42b89f90-db36-4347-b4e5-dd71e50beaac.png">

- [x] When you have “Advanced” on by default and click “Edit”, the back arrow closes the modal. This feels a bit unexpected, let's remove the back arrow and just  have the “X” icon to close.  
<img width="486" alt="Screen Shot 2022-01-18 at 3 40 41 PM" src="https://user-images.githubusercontent.com/11967476/150030286-8ec543dd-0292-4c45-8eed-b0d175ac1552.png">

- [x] Use same alert style for both messages (keep icon and left justified text)
![image](https://user-images.githubusercontent.com/11967476/150030395-46b4cbbd-2c38-4b3f-8293-496d4698c31a.png)

- [x] Let's remove the second sentence in the warning here. We already show the time estimate and the "last seen..." is not really telling the user anything new. So, warning will just say "Future transactions will queue after this one".
<img width="410" alt="Screen Shot 2022-01-18 at 3 43 14 PM" src="https://user-images.githubusercontent.com/11967476/150030589-18b985f0-65af-473a-9612-19e8d84d7f3b.png">

- [x] Copy change: "customise" to "customize"
<img width="427" alt="Screen Shot 2022-01-18 at 3 50 03 PM" src="https://user-images.githubusercontent.com/11967476/150031342-a8d0d8a0-2225-4973-9030-ef7195846130.png">

- [x] While on the "edit" screen, as prices update the values flash. There is a white background on the numbers that becomes visible on the selected item. Can we remove this? 
<img width="280" alt="Screen Shot 2022-01-18 at 3 51 29 PM" src="https://user-images.githubusercontent.com/11967476/150031501-1c28343c-7b03-4950-93b6-b0c24366ffa3.png">

- [x] Tooltip placement for “Aggressive” is off a bit. Is this due to having more content? Can we get this aligned the same way as all the other tooltips? 
<img width="318" alt="Screen Shot 2022-01-18 at 3 52 45 PM" src="https://user-images.githubusercontent.com/11967476/150031632-a326743f-7382-4550-8e4f-76d4f6bfd5a6.png">

- [x] Can we make the hit areas for "Base fee" and "Priority fee" be both the amount and label? Right now it's just he amount. 
<img width="483" alt="Screen Shot 2022-01-18 at 3 53 35 PM" src="https://user-images.githubusercontent.com/11967476/150031731-4cfc1466-f802-4d26-9c29-62e89f34b979.png">

- [x] Network status block should be aligned with the text above, not the "selected" box"
<img width="1196" alt="Screen Shot 2022-01-18 at 4 01 28 PM" src="https://user-images.githubusercontent.com/11967476/150032576-622bb486-17da-463b-8cd9-9b871ebe0f69.png">

- [x] In the designs, the thought was to anchor the “Network status” to the bottom of the modal to better separate gas options vs. network data. Is that possible without mudding up the code? If not, we can increase spacing slightly and size the background of the modal to fit. 
<img width="863" alt="Screen Shot 2022-01-18 at 5 03 47 PM" src="https://user-images.githubusercontent.com/11967476/150038485-8e139415-4bb3-46a3-8f8b-18ba2892aa16.png">

- [x] Max base fee shown in "Edit" screen tooltips (all three) should follow rounding logic and not show so many digits. 
![image](https://user-images.githubusercontent.com/11967476/150202444-f687b6f1-dc18-43de-9f22-6642e2ae2d16.png)

- [x] Fiat estimates in "Advanced" not working? 
![image](https://user-images.githubusercontent.com/11967476/150187784-25a182a2-6ded-48c1-b11b-e10ba8b5d743.png)

### Steps to reproduce

n/a

### Version

10.8.2

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

**Comment by jpuri** [comment]
Hey @jakehaugen : 
- can you plz provide the icons in mentioned in point-2 ?
- for the last point: `Max base fee should follow rounding logic and not show so many digits.` can you detail which screen is it ?

**Comment by jpuri** [comment]
Feedback from @mcmire 
> there's one more UI tweak i just noticed we could make — looks like on the advanced gas fee modal, for the base fee range and priority fee range, if the two sides of the range are the same then i think it'd be good if we just collapsed them. for instance, instead of showing 2 - 2 GWEI we just show 2 GWEI. i am not sure whether the same thing applies for the priority fee range on the edit gas modal, but we might want to check that as well.

**Comment by jpuri** [comment]
@jakehaugen :

#13: `Max base fee shown in "Edit" screen tooltips (all three) should follow rounding logic and not show so many digits.` I have done rounding of upto 4 decimal places.

#14: Fiat currency is visible if gwei value is large enough.
