### ISSUE TITLE
[Bug]: Won't send txs with Polygon EIP-1559

### ISSUE THREAD

**Issue by aglawson** [MetaMask/metamask-extension#13341]
### Describe the bug

Since Polygon pushed their new EIP-1559 upgrade, users trying to buy on our NFT site are getting this error: Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559.

### Steps to reproduce

![photo_2022-01-18 07 20 00](https://user-images.githubusercontent.com/36459896/149968574-3226501b-ff73-417d-b258-c1dc6cb9efb3.jpeg)

### Error messages or log output

```shell
Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559
```

### Version

10.8.1

### Browser

Microsoft Edge

### Operating system

MacOS

**Comment by am999999** [comment]
MacOS, MetaMask 10.8.1, Polygon, trying to stake some Orion token on https://app.orion.money/staking/ -> same error message

**Comment by danjm** [comment]
Thanks for the report. We will look into this, but It is possible that switching networks and switching back again will fix this problem.

**Comment by am999999** [comment]
Thx! Switching to Ethereum and back to Polygon resolved the issue! :-)

**Comment by rasoul369** [comment]
I tried three times but failed. He objected to me. Oh God, I saw the most
damage😔

در تاریخ چهارشنبه ۱۹ ژانویهٔ ۲۰۲۲،‏ ۱۹:۲۲ am999999 ***@***.***>
نوشت:

**Comment by aarrohan** [comment]
> 

Haha thanks it worked :)

**Comment by mworks-proj** [comment]
switching from polygon to eth mainnet back to polygon fixed the issue with my test.

**Comment by dima-brook** [comment]
Guys, you closed the issue, and switching between chains works, but how can we explain to all the users that they have to do it?

Is there a chance, you could fix this inside Metamask?

**Comment by Pasha8914** [comment]
WTF? Actual issue, but you closed it? 
@aglawson

**Comment by 0xVoushi** [comment]
It looks like the bug is not solved
or am I missing something? @aglawson @danjm
