### ISSUE TITLE
[Bug]:  Can't make any tx with ledger nano s. Fails before sending prompt to ledger

### ISSUE THREAD

**Issue by federicosan** [MetaMask/metamask-extension#13356]
### Describe the bug

It used to work fine o earlier versions. Connected my ledger using WEBHID, trying to do a tx send an error each time instantly, it sais failed transaction please enable blind ... but contract data is allowed so that's not it. 

Attached images from errors 
<img width="292" alt="Screen Shot 2022-01-20 at 00 04 01" src="https://user-images.githubusercontent.com/5906694/150264938-30bca425-9de6-4a2d-8465-bf9af24015e9.png">
<img width="308" alt="Screen Shot 2022-01-20 at 00 04 27" src="https://user-images.githubusercontent.com/5906694/150264972-befd68c2-385b-4ab0-ae50-638d7e36c5b3.png">
 

### Steps to reproduce

1. Make a transacction with metamas 10.8.1 and ledger nano 6 on chrome  Version 97.0.4692.71 ethereum app 1.7.0

### Error messages or log output

```shell
<img width="292" alt="Screen Shot 2022-01-20 at 00 04 01" src="https://user-images.githubusercontent.com/5906694/150264938-30bca425-9de6-4a2d-8465-bf9af24015e9.png">
<img width="308" alt="Screen Shot 2022-01-20 at 00 04 27" src="https://user-images.githubusercontent.com/5906694/150264972-befd68c2-385b-4ab0-ae50-638d7e36c5b3.png">
```

### Version

10.8.1

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

### Additional context

I just want to add that, the tx prompt shows when doing tx on ledger live without metamask, so this is a metamask only issue

**Comment by federicosan** [comment]
Update: tried with chrome latest version updated today, the same error. Version 97.0.4692.99 (Official Build) (x86_64)

**Comment by federicosan** [comment]
Update: Tried enabling contract data + debug data display +  account nonce display and still failing

**Comment by federicosan** [comment]
Update: same error with Brave browser.

**Comment by federicosan** [comment]
Update: firefox fails too, metamask version 10.8.1 as all the other browsers, it fails silently, chrome and brave send a notification with the enable blind signing (that by the way smart contracts are allowed using nano s)

**Comment by Reine77** [comment]
I have the exact same issue, but only when using avalanche c-chain. It works fine for fantom/harmony/eth. Ledger NANO S with metamask 10.8.1, latest ethereum app, WIndows 10

**Comment by darkwing** [comment]
@federicosan Could you tell us what network?

**Comment by Goochie** [comment]
I have the same issue on the polygon /matic network, tried different browsers with fresh install - ledger and eth app up to date ... this was working at the back end of last year ..

**Comment by Goochie** [comment]
Any update ?

**Comment by Goochie** [comment]
This is happening for me on Windows 10, mac - MM version 10.9.0 and on edge and brave

**Comment by Goochie** [comment]
@federicosan  @Reine77 have either of you found a solution ?

**Comment by Goochie** [comment]
FYI you can close this, issue was on ledgers end - just updated ...

**Comment by darkwing** [comment]
@Goochie Could you provide more information as to how this was a Ledger issue?  Any information would be very helpful!

**Comment by yvigeant** [comment]
I am also having the same issue, only on AVAX network. My ledger Nano S is up to date, I've tried Ledger Live and WebHID modes as well as Firefox. No transactions reach my ledger for approval. Using the Ledger Live mode, the bridge/socket prompt does show in Ledger Live, but I get no confirmation prompt on the ledger.

**Comment by yvigeant** [comment]
I tried on a different computer with WebHID and Ledger Live modes, and I'm getting the same message: Transaction 27 failed! Please enable Blind Signing or Contract data in the Ethereum app settings.
So I'm getting the same error on all combinations of 2 computers, 2 browsers and 2 connection modes, all on Avalanche-C Chain network.

I am not getting the same behavior on BSC Chain, everything works normally over there.

**Comment by yvigeant** [comment]
Ledger Live pushed me a new firmware version today that fixed the issue. The firmware doesn't seem to have been released today, so I'm guessing there was a synchronization issue between Ledger Live and their servers causing Ledger Live to show firmware was up to date even if it wasn't.

So solution for anyone getting this issue: check the latest firmware version manually on ledger's website and make sure you are using that version,

**Comment by FerCamposDev** [comment]
I receive the same problem in the goerly network transaction.
In my case i needed to enabled the blind mode in the ledger device
app => settings => blind signing => enabled
