### ISSUE TITLE
Add wallet_type parameter to transaction MetaMetrics events

### ISSUE THREAD

**Issue by brad-decker** [MetaMask/metamask-extension#13357]
We would like to be able to segment transactions by the wallet's type. This way we can see percentage of all transactions that are issued from a ledger, etc. To do this we need to modify the transaction controller event payload to include a 'wallet_type' parameter in properties. This wallet_type parameter should be populated with one of the following types based on the address of the from parameter ( we cannot assume that the transaction in question belongs to the currently selected wallet )

1. Ledger
2. Trezor
3. Lattice1
4. QR
5. Imported
6. ? -- 

Note that it might be best to record this value on the txMeta object, which would prevent having to get this value multiple times throughout the transaction lifecycle.

**Comment by AlexJupiter** [comment]
@brad-decker is it possible to split QR out into Keystone, AirGap, and any other QR partners we may have in the future?

**Comment by AlexJupiter** [comment]
@brad-decker I've defined an epic related to what would be good to accomplish here: https://www.notion.so/Collect-more-hardware-wallet-data-74f3735c25d5417883169d3d302b14b6

**Comment by bschorchit** [comment]
Could the property be `account_type` and the options be: the hardware devices you and Alex listed +` imported` (imported accounts using Private Key) + metamask (accounts created within MM)?
