### ISSUE TITLE
[Bug]: Checkbox to selected advance default gas is glitchy

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#13362]
### Describe the bug

Checking / un-checking of checkbox below looks buggy.

https://user-images.githubusercontent.com/2182307/150394420-3d8b33cd-81f9-49cf-81d8-4b7616f07e99.mov

### Steps to reproduce

1. Open advance gas editing modal
2. Try to check / uncheck default checkbox

### Version

10.8.2

### Browser

Chrome

### Operating system

Windows, MacOS, Linux

**Comment by rasoul369** [comment]
@mcmire please check
