### ISSUE TITLE
Replace uses of `updateTransaction` (from the tx controller) with less powerful methods for each specific state transition 

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#13386]
This is a follow up to this comment: https://github.com/MetaMask/metamask-extension/pull/13328#issuecomment-1019977808

Currently, the transaction controller has a `updateTransaction` method that can be called externally. This is ultimately called in the UI in at least three places: in the swaps approve transaction flow, in the send edit flow, and when editing the gas params from the confirm screen.

Because this method can overwrite the entire txMeta object, exposing it as a public method is a dangerous design flaw. We should make these updates safe by (as suggested in the first comment below) "exposing methods for each individual state transition"

To resolve this task, we should first document each use of `updateTransaction` and the state transition it needs to make happen. Once we have done that, we can specify a list of methods to be added, and start replacing the current calls to `updateTransaction` one by one.

**Comment by Gudahtt** [comment]
Rather than expose a generic "update transaction" method with additional safety checks, it would be better to expose methods for each individual state transition. That would be safer than having to imagine each possible state transition and add safety checks for each one.

**Comment by danjm** [comment]
@Gudahtt that is a good suggestion

**Comment by danjm** [comment]
For posterity, here is the initial proposal I put in the ticket description. But it has since been update in response to the first comment above:

> Here is my initial thinking:
> 
> rename updateTransaction in the transaction controller to _updateTransaction to indicate that we do not want it called externally
> create new method in the transaction controller called safeUpdateTransaction
> this method will eventually call this._updateTransaction, but only under specific conditions
> the first condition is that it will only call this._updateTransaction if the transactions current status is TRANSACTION_STATUSES.UNAPPROVED (see shared/constants/transaction.js)
> the method should accept and update a limited set of parameters. These should include all the properties of txParams, as well as the individual properties that we currently modify from the UI
> the method should only update txParams after a successful call to validateTxParams
> we may want to restrict the number of updates that can be made at one time, and perhaps group them, so that we can have a uniquely identifiable entry in the transaction history log for each update (this would require allowing a message param to be passed to _updateTransaction
> finally we need to consider certain updates that will need to be automatically applied to txMeta in response to an update, to keep the transaction internally consistent. An example of this is that if a transaction recipient changes, and therefore it's type changes (e.g. from a simple send to a token transfer), then we should change the type on the txMeta
> We may need to add more details to this ticket

**Comment by danjm** [comment]
@segun As a first step to planning out the work for this, can you find every case that the transaction controller `updateTransaction` method is called and make notes on:
- the file and function that calls it
- what user action or event triggers that call
- The specific transaction data that is being updated with the call.

(Keep in mind the `updateTransaction` method is exposed to the ui, so we need to trace its usage in both the `ui/` and `app/` directory)

Post the notes here

**Comment by segun** [comment]
File | Fields Updated | Line
-- | -- | --
ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-save/advanced-gas-fee-save.js | {      estimateUsed: PRIORITY_LEVELS.CUSTOM,      maxFeePerGas: decGWEIToHexWEI(maxFeePerGas),      maxPriorityFeePerGas: decGWEIToHexWEI(maxPriorityFeePerGas),      gasLimit,    } |  
ui/ducks/swaps/swaps.js | {            ...approveTxMeta,            estimatedBaseFee: decEstimatedBaseFee,            type: TRANSACTION_TYPES.SWAP_APPROVAL,            sourceTokenSymbol: sourceTokenInfo.symbol,          }, | 864
  | {          ...tradeTxMeta,          estimatedBaseFee: decEstimatedBaseFee,          sourceTokenSymbol: sourceTokenInfo.symbol,          destinationTokenSymbol: destinationTokenInfo.symbol,          type: TRANSACTION_TYPES.SWAP,          destinationTokenDecimals: destinationTokenInfo.decimals,          destinationTokenAddress: destinationTokenInfo.address,          swapMetaData,          swapTokenValue,          approvalTxId: finalApproveTxMeta?.id,        }, | 904
ui/hooks/gasFeeInput/useTransactionFunctions.js | updateTransaction({      estimateUsed: PRIORITY_LEVELS.TEN_PERCENT_INCREASED,      gasLimit,      maxFeePerGas: addTenPercentAndRound(maxFeePerGas),      maxPriorityFeePerGas: addTenPercentAndRound(maxPriorityFeePerGas),    }); | 118
  | updateTransaction({        estimateUsed: gasFeeEstimateToUse,        maxFeePerGas: decGWEIToHexWEI(suggestedMaxFeePerGas),        maxPriorityFeePerGas: decGWEIToHexWEI(suggestedMaxPriorityFeePerGas),      }); | 135
  | updateTransaction({      estimateUsed: PRIORITY_LEVELS.DAPP_SUGGESTED,      maxFeePerGas,      maxPriorityFeePerGas,    }); | 149
