### ISSUE TITLE
[Bug]: Replacement tx underpriced

### ISSUE THREAD

**Issue by sanchopansa** [MetaMask/metamask-extension#13395]
### Describe the bug

Since a few weeks I keep getting an RPC error:

```
Error: [ethjs-rpc] while formatting outputs from RPC '{"value":{"code":-32000, "message":"replacement transaction underpriced"}}
```

when trying to speed up or cancel an existing transaction. I saw the discussions in https://github.com/MetaMask/metamask-extension/issues/10519 and https://github.com/MetaMask/metamask-extension/issues/13001, and it appears that it might be an Infura problem, however, the issue I'm experience is slightly different from the two above because: this is a replacement tx and it fails even if I bump the new gas price by 100%+.

### Steps to reproduce

1.

### Error messages or log output

```shell
Error: [ethjs-rpc] while formatting outputs from RPC '{"value":{"code":-32000, "message":"replacement transaction underpriced"}}
```

### Version

10.8.1

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

Ledger

**Comment by Nana12345678910** [comment]
What does that mean? Do you think someone put it there on purpose?
