### ISSUE TITLE
Web3 Sometimes Injected Late

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1340]
On Slack, user `murbard` reports web3 is injecting after the document `load` event.

Opening this issue to ask him to comment more with system + browser versions, and hopefully even a page for reproducing the issue.

**Comment by flyswatter** [comment]
On [the chromium issue we believe is related](https://bugs.chromium.org/p/chromium/issues/detail?id=634381#c21) it was suggested that using `document.write` could allow synchronous injection of our inpage script, so we should try that next.

**Comment by flyswatter** [comment]
Nevermind, [a subsequent comment](https://bugs.chromium.org/p/chromium/issues/detail?id=634381#c23) says `document.write` has already been tried for this general use case to no avail.

**Comment by danfinlay** [comment]
A new commenter has pointed out some things we have not tried yet, and look likely to be the solution to this problem. Will be implementing, requires some changes to the build system.
