### ISSUE TITLE
Validate if existing wallet_addEthereumChain method can be reused for internal add network page/flow

### ISSUE THREAD

**Issue by brad-decker** [MetaMask/metamask-extension#13400]
### Background
In #12898 a new UI is suggested that lists popular custom networks and adds a convenient way for MetaMask users to add networks. However, in #13106 I noticed that there is a fair chunk of duplication with the existing addEthereumChain confirmation screen. I have discussed with @rachelcope and Sayalee (not sure what your github username is sorry!) and discussed the differences between the design in the figma file versus what would happen if we reused what we have.

### Requirements to validate
1. Hook up the work done for #12898 to trigger the `wallet_addEthereumChain` method and record what happens in the UI when this is done. We really want to understand where the user ends up after adding the network (if they remain on the add network page or if they are returned to homepage).
2. Discuss with design and determine next steps.

**Comment by danjm** [comment]
@brad-decker Why do we need to "trigger the wallet_addEthereumChain method "? Calling that from within the wallet seems unnecessary... and perhaps adds complexity that we do not want to maintain. Meanwhile, calling that method opens a notification window, which seems like a definitely not as good UX compared to the design for the in app modal.

Can't we just look at the new designs and compare to the existing add network designs that are live in prod, and then either use the existing components out of the box, or modify them so that they accomodate the differences of this specific case?

**Comment by danjm** [comment]
To move this forward, I think we should:
1. Get screenshots from the storybook added with the current PR, and compare to screenshots of the UI that is currently shown with wallet_addEthereumChain in prod
2. Ask designers to specificy which of each screenshot they want
3. Use the existing components within the new popover to implement the updated design specification

**Comment by brad-decker** [comment]
> @brad-decker Why do we need to "trigger the wallet_addEthereumChain method "? Calling that from within the wallet seems unnecessary... and perhaps adds complexity that we do not want to maintain. Meanwhile, calling that method opens a notification window, which seems like a definitely not as good UX compared to the design for the in app modal.

The thought here was to not add an internal method that does the same overall thing as the `wallet_addEthereumChain` method, which is to add an unapproved message to the queue that then triggers the page route to the proper confirmation. My primary goal here is to keep the pathways for performing the same action as minimal as possible. If we don't reuse this method, then a fair chunk of the code is going to have to be duplicated because the existing confirmation flow exists by pulling the message out of state. All of the functionality of approving that confirmation interacts with the approval controller.

Also, i'm not exactly convinced a new confirmation window would be opened. This is what i wanted to explore. If you are on the send flow, for example, a new unapproved transaction is added to state when you get done drafting your transaction. Then the confirmation flow kicks in and takes over your existing window. This is the primary question I wanted to pose to designers... instead of a popover, can we simply issue this command and reuse all of the existing code we have hooked up for this flow. It hinges a lot of upon what happens after the user approves the network addition. If the user is navigated back to the settings page then its likely okay. If they are taken to the homepage then that is another, untenable story.

If the answer is no, or if we simply do not want to call the wallet method from within the UI (I did not know this was a constraint we have, or how this differs from sending a transaction or other ethereum specific calls), then I will concede. I just  think our primary goals should be to minimize the amount of duplicated UI we have as well as background code that does, essentially, the same thing. 

Sorry for the delayed response @danjm!

**Comment by danjm** [comment]
So I think what we can do here is:

Create a `addCustomNetworks` method in the metamask controller and expose it to the UI. This method should receive the following params:
```
          chainId: _chainId,
          blockExplorerUrl: firstValidBlockExplorerUrl,
          chainName: _chainName,
          rpcUrl: firstValidRPCUrl,
          ticker,
```

The method should make the same call that is made here: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js#L235-L248

This method should be called when the plus buttons in the screen added here are clicked: https://github.com/MetaMask/metamask-extension/pull/13180

For the sake of verifying the UX of this, you can create a temporary branch that adds a button on the add network screen which submits the data for one of the popular networks on click. The UX of this button does not matter, the purpose of this is just to get a video screen capture of the way the screen shown after clicking the button looks and behaves.

Post that video screen capture below once you have it.

**Comment by danjm** [comment]
@brad-decker using the code changes here https://github.com/MetaMask/metamask-extension/compare/feat/add-custom-network-patch

 We can achieve this:
 
 

https://user-images.githubusercontent.com/7499938/157286963-d82228bd-78bc-455d-9a87-1d9c4a7d0f06.mp4

**Comment by danjm** [comment]
Whether we want to do this depends on how easy it will be customize the existing template based component. We need the design to look like this:

![Screenshot from 2022-03-08 13-27-19](https://user-images.githubusercontent.com/7499938/157287199-267bc8a4-b7c6-49eb-9d58-41b973c13add.png)

**Comment by brad-decker** [comment]
@danjm is it intentional for the two popups to have different copy? I mean the current version makes a reference to "do you want to allow this site to add" which doesn't make sense when launching from within MetaMask. However, we derive the origin and display it it might be pretty easy to customize the template such that a different string is used when the domain is detected as being the extension. That being said we'd need to confirm that the UX is appropriate and go from there.

**Comment by danjm** [comment]
okay, I will try to use the origin then

**Comment by bschorchit** [comment]
We should also remove the "The network details for this chainID do not match our records" warning whenever we're launching it from within MetaMask. @danjm @brad-decker 

Should I ping designers to review this?
Does this also works well when adding the network from within the pop up view? (I'm guessing yes, but just double checking)

**Comment by danjm** [comment]
@bschorchit I will create a fully working version that matches the designs, then I will capture screen shots for both the popup and full screen, then we can pass it by design

**Comment by danjm** [comment]
@bschorchit Here it is properly implemented. Can you get designers to review this?


https://user-images.githubusercontent.com/7499938/157517556-71487a4c-194f-4666-91ec-d90592754b6b.mp4

**Comment by bschorchit** [comment]
@danjm Rachel and Saya have reviewed this and Saya will share a Figma file with some adjustments needed. Can we also have a video for the pop up view for her to review?

**Comment by danjm** [comment]
Regarding the popup: current behaviour on the extension is to open in full screen mode when trying to add networks on the popup. Do we want to change that now?

**Comment by bschorchit** [comment]
Yes, that was included in[the design](https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1697%3A17291) and I think the PS team might have implemented that already too. 
The only reason to open full mode is because pop up closes and looses state when you're trying to copy and past info to the custom network form. As this flows doesn't require any copy and pasting, it should be available in pop up view as well.

cc: @SayaGT

**Comment by danjm** [comment]
@EHaracic @david0xd This branch has been updated with the code behind the most recent demo I posted above: https://github.com/MetaMask/metamask-extension/compare/feat/add-custom-network-patch
