### ISSUE TITLE
Ask to confirm when removing a Snap

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#13414]
We should prompt a confirm dialog when the user wants to remove a Snap.

**Comment by rekmarks** [comment]
@holantonela we do need your input on copy and just sign-off for this one, but I think we said that we'd just use the popover component in the same way that we did for key management permission confirmation, so I'm gonna ask @hivtushok to go ahead with that approach for now. The copy we can always tweak.

**Comment by rekmarks** [comment]
@hivtushok, this popover should appear in the "See Details" view of the snaps settings page when the user clicks "Remove Snap". Please use the following component on the `snaps` branch as a reference implementation: https://github.com/MetaMask/metamask-extension/blob/fa012e33c4bcce4e089778a1ec84c22dbf3ca846/ui/components/app/flask/snap-install-warning/snap-install-warning.js

The popover should look the same, but it should **not** have a checkbox, just "yes"/"no" buttons. For now, the prompt should be an English locale message, and it can read: `Are you sure you want to remove this snap?`

Feel free to add the corresponding Ukrainian locale message as well! :smile:

**Comment by holantonela** [comment]
Here is the Figma file for this UI 

https://www.figma.com/file/TecL0q96AzDxLJ5zPruuSh/Flask-UI?node-id=1%3A80

I'm using an existing component. You can replicate this behavior by going to `home.html#settings/advanced` and clicking on `Reset Account`. We need a similar confirm action modal here.

Happy to answer any question @hivtushok

PS: you should have access to Figma now

**Comment by hivtushok** [comment]
@rekmarks I see that there's no Ukrainian localization folder added yet. Should I add one with only a few keys for now?
