### ISSUE TITLE
Fix custom confirmation box scroll overflow / min-height

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#13415]
How it looks

![Screen Shot 2022-01-20 at 16 29 18](https://user-images.githubusercontent.com/87079938/151206402-2cc16f11-1ea3-4460-bd2e-dc13e250ea07.png)

How it should look

![Screen Shot 2022-01-20 at 16 29 11](https://user-images.githubusercontent.com/87079938/151206410-c04f5693-7530-41b4-b8e7-3ca8a62eef47.png)

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/13415?planning-poker) with ZenHub @Gudahtt @hmalik88 @ritave
