### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Steven4294** [MetaMask/metamask-extension#13426]
### Describe the bug

I created a metamask account, sent funds to the account, and then wiped my computer, losing my local storage (chrome vault) data. I also didn't write down my seed phrase either. Can I recover my account from my metamask ETH address and my account password?

### Steps to reproduce

1. Set up metamask account
2. wipe computer
3. remember password and eth address
4. dont write down seed phrase
5

### Version

1.0

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

**Comment by Gudahtt** [comment]
Please contact our support team in the future for these type of questions: https://metamask.zendesk.com/hc/en-us

In this case though I'm fairly certain that there is no way to recover the address. This is why we stress the importance of backing up the secret recovery phrase. As a last resort it can be recovered from disk if you know your password, but if your disk has been wiped, that may not be possible.

I don't know much about recovering deleted data from disk, that might be possible.
