### ISSUE TITLE
Cannot read properties of undefined (reading)

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#13425]
Notes from CS:

- this bug has 320 tickets in zendesk, with 75 created since Jan 1 2022, dating back to Sept 2021. It appears to iterate in a variety of different ways each with unique descriptors after “reading” such as reading ‘map’, reading ‘balance’, reading ‘type’, etc. many instances appear to occur upon launching the extension

- ZenDesk link: https://consensys.zendesk.com/agent/tickets/714360

Report attached here (from ZD link):

[https://app.zenhub.com/files/42009758/2d14d2e5-89ec-4e82-874b-c3bab9d4c423/download](https://app.zenhub.com/files/42009758/2d14d2e5-89ec-4e82-874b-c3bab9d4c423/download)

**Comment by Beasta** [comment]
i'm getting this as well - `Cannot read properties of undefined (reading 'map')`

**Comment by AlexHerman1** [comment]
@hilvmason  this is still popping up in our queues
