### ISSUE TITLE
Add new "Base Asset Received" MetaMetrics event to IncomingTransactionController

### ISSUE THREAD

**Issue by brad-decker** [MetaMask/metamask-extension#13420]
### Description
Product and business leaders would like to get a sense of how often MetaMask users receive transactions of the base asset for the network. Essentially this means tracking any received Ether, BNB, etc but not ERC-20, ERC-721, etc. To do this we will need to modify the IncomingTransactionController such that it gets access to the trackEvent method exposed by the MetaMetrics Controller. Once this has been done new code will need to be written that satisfies the requirements

#### Requirements
1. Only track the event for the base asset of the network the transaction occurred on. Keep in mind that the IncomingTransactionController keeps track of the last block it scanned for each network, but only scans the currently active network.
2. Track the event with the event name: "Base Asset Received"
3. Track the event category as "Transaction"
4. Track all properties described below

#### Properties (WIP)
1. asset_symbol

**Comment by brad-decker** [comment]
@jacobc-eth @kevinghim what details of the transaction do we want to track? 

We have traditionally tracked any data that occurs on chain under the anonymous user id to protect our users identity and to adhere to our stringent security and privacy code. I might suggest another way we could do that by rounding amounts, and/or buckets (above 0-10, 11-100, 101-1000) instead of literal values on anonymous events.

Thoughts?

**Comment by brad-decker** [comment]
Added a new issue blocking this one for creating the utility method for determining if the transaction is receiving the baseAsset

**Comment by bschorchit** [comment]
Closing as no longer relevant (feel free to disagree and re-open this)
