### ISSUE TITLE
Onboarding V2 Cleanup

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13440]
This is a collection of issues with the yet unreleased Onboarding V2 flow, raised by Mark Stacey. 

In order to enter the new onboarding flow to resolve these issues you will need to set the environment variable `ONBOARDING_V2=1` in your `.metamaskrc` file.

Original [figma designs](https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=1525%3A14906) for reference

[New figma designs](https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=2450%3A17243)!

**Comment by adonesky1** [comment]
I am still seeing this issue where the "lock screen" shows up briefly between the "create password" screen and the success screen:
https://user-images.githubusercontent.com/34557516/159287376-ee9ab478-8b84-461e-8adc-fe998b22caad.mov

cc @VSaric @EHaracic @dragana8

**Comment by kevinghim** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/11143
