### ISSUE TITLE
Overall CSS

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13441]
All screens in the Onboarding V2 flow require additional Design/CSS work to make them suitable for smaller and larger screens.*

For smaller screens we need designs that adapt to screen widths less than ~700 px:
![Screen Shot 2022-01-27 at 5 18 46 PM](https://user-images.githubusercontent.com/34557516/151459376-bc913580-de13-4c44-a3d4-910ac43a6867.png)

For larger (and perhaps all screen) sizes it seems that the gap between header and the card where the content is contained is a bit too much:
![Screen Shot 2022-01-27 at 5 20 55 PM](https://user-images.githubusercontent.com/34557516/151459790-dc5437e4-e62a-4b5a-817e-bf872a76935e.png)

*requires design input (cc @rachelcope)

**Comment by Gudahtt** [comment]
Regarding the larger screen padding, it's actually centered vertically. So it looks even worse than depicted on larger screens (mine is 1440p, so larger than that screenshot)

**Comment by EHaracic** [comment]
### Figma design(s)
NO Figma designs

### Acceptance criteria 

- All screens in the Onboarding V2 flow require additional Design/CSS work to make them suitable for smaller and larger screens. 
1. For smaller screens we need designs that adapt to screen widths less than ~700 px:

![image](https://user-images.githubusercontent.com/49436614/153228076-59698fc5-92c0-46fd-a2e6-8a22e7f062a8.png)

2. For larger screens: For larger (and perhaps all screen) sizes it seems that the gap between header and the card where the content is contained is a bit too much. 

### Discussion points and Notes
- Issue is blocked until we get the designs for screen below.
![image](https://user-images.githubusercontent.com/49436614/153228922-999c5d98-c4a8-4dea-9ba2-edafb0f5adf2.png)

**Comment by EHaracic** [comment]
Issue updated according to the new figma design for small and large screens (Slack link: https://consensys.slack.com/archives/C02GH833686/p1644608577042889?thread_ts=1644414302.716329&cid=C02GH833686)
