### ISSUE TITLE
Secure your wallet page

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13446]
- We should not vertically center the bulleted list. 

Figma file for reference: https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=1525%3A15961

needs design feedback:
cc @rachelcope

**Comment by EHaracic** [comment]
### Acceptance criteria: 
- The bulleted list should left aligned, Figma design is below. (Currently the list is vertically centered.
![image](https://user-images.githubusercontent.com/49436614/153197977-b77653c3-60d8-43fc-8f25-3d4b3313eb85.png)
