### ISSUE TITLE
Overall Onboarding Flow Issues

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13447]
- [ ] **Bug to investigate/fix**: Sometimes when I press "back", I end up on the wrong page. For example when I press "Back" on the "Secure your wallet" page, it drops me in the "import" flow.

- [ ] The progress bar text across many of the Onboarding screens should not be all caps:

 ![Screen Shot 2022-01-28 at 9 49 36 AM](https://user-images.githubusercontent.com/34557516/151578094-53e62a4c-eb0e-4c15-89c8-691d1e29036c.png)
![Screen Shot 2022-01-28 at 9 49 39 AM](https://user-images.githubusercontent.com/34557516/151578089-13dc285d-bebc-459f-8856-a37771cca8e7.png)

Should be normal casing: "Confirm secret recovery phrase" & "Create password"

- [ ] Enhance logic for the highlighting of progress bar.*

Mark's review: 
Page 1
![Screen Shot 2022-01-28 at 9 55 14 AM](https://user-images.githubusercontent.com/34557516/151579085-a6649b74-44b4-4bf1-844f-59bdf9beaa36.png)

Page 2
![Screen Shot 2022-01-28 at 9 55 44 AM](https://user-images.githubusercontent.com/34557516/151579093-e271ccdd-90fe-4255-893c-af43dad0d179.png)

> I didn't understand what the highlighting was meant to indicate. On the first page I wasn't sure whether it was telling me I was on page 1 or 2 - the bubble around "1" was highlighted, but so was the line between 1 and 2, so I thought it might have meant I had finished with page 1 and was working on page 2.
> Then on page 2, I immediately thought "Oh, I guess it's broken because it's definitely saying I'm on page 1 now".

*requires design input (cc @rachelcope)

**Comment by EHaracic** [comment]
Figma designs: https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=2450%3A17243

### Acceptance criteria
- The progress bar text shoud be Sentence case (Only first letter in the text is capital). Ccurrently, across many of the Onboarding the text is in all caps, example is shown below. 
![image](https://user-images.githubusercontent.com/49436614/153196751-3f3ffca7-42c8-4dc7-b241-2359490cf1d9.png)
- Enhance logic for the highlighting of progress bar according to the figma design below.
![image](https://user-images.githubusercontent.com/49436614/153197137-3f02bc64-ba94-4dea-9273-814637c48131.png)
