### ISSUE TITLE
Success page

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13444]
- [ ] "learn more" needs to be capitalized

- [ ] The "Done" button font is `0.875rems`, which is the standard font for our buttons.  The padding on the button is higher so the font looks smaller, perhaps the button should have less padding?*
   - Context: @Gudahtt  commented that the the font for the "done" button looked small.
   
Here are images of other buttons in the onboarding flow
![Screen Shot 2022-01-27 at 5 49 44 PM](https://user-images.githubusercontent.com/34557516/151462370-484b107b-9926-406c-bf51-8929573fb5a7.png)
![Screen Shot 2022-01-27 at 5 49 59 PM](https://user-images.githubusercontent.com/34557516/151462378-ec260bb0-72d2-4449-b120-05b16cff6ee3.png)
![Screen Shot 2022-01-27 at 5 49 50 PM](https://user-images.githubusercontent.com/34557516/151462437-3749a86f-6ff2-4984-903e-5292225d9489.png)

and the "done" button in context:
![Screen Shot 2022-01-27 at 5 50 09 PM](https://user-images.githubusercontent.com/34557516/151462405-cf447cd8-ebe6-4494-bd7a-d2b6182bc6fe.png)

*requires design input (cc @rachelcope)

**Comment by EHaracic** [comment]
### Acceptance criteria
-
