### ISSUE TITLE
Import SRP Page

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13442]
- [ ] "learn more" should be capitalized

- [ ]  Update "Learn More" link to a source that explains what the SRP is for,  rather than one about how to recover it from disk in case you lost it and your password.* 

- [ ]  Change the default behavior of the text area to blur the SRP the user inputs 

*requires design input (cc @rachelcope)

**Comment by SayaGT** [comment]
We can use [this link for learn more](https://metamask.zendesk.com/hc/en-us/articles/360060826432-What-is-a-Secret-Recovery-Phrase-and-how-to-keep-your-crypto-wallet-secure) which explains what SRP are and their significance.
