### ISSUE TITLE
Write down your SRP page

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13457]
- [ ]  The tip "Write down and store in multiple secret places" tip is there twice. Remove one instance.

- [ ] "Store in a bank vault" is redundant since we also say "Store in a safe-deposit box." remove it.*

- [ ] Should we keep "Save in a password manager" or have we decided that's not actually a safe tip?*

- [ ] There is no way to hide the SRP again after revealing, we should provide this option.*

*requires design input (cc @rachelcope)

**Comment by EHaracic** [comment]
### Acceptance criteria: 
- Change the tips according to the figma design: 
![image](https://user-images.githubusercontent.com/49436614/153198854-3bd72b33-f09a-4122-9638-8510eb8b3603.png)
- Change the icon on the image: 
![image](https://user-images.githubusercontent.com/49436614/153199230-bc9b6409-5d04-4ba2-9953-2f2128a1de9f.png)
**Old and new icons:**
![image](https://user-images.githubusercontent.com/49436614/153199085-c793c606-a54a-408c-91c1-45eb8571778f.png)
- Change the screen (Screen which is shown after clicking on the: "Reveal seed phrase button") according to the figma design: 
![image](https://user-images.githubusercontent.com/49436614/153199580-47b0fbe3-6458-4562-bc40-3a1a75ee8981.png)
