### ISSUE TITLE
[Bug]: Queued confirmations not being sent to ledger device for signing

### ISSUE THREAD

**Issue by brad-decker** [MetaMask/metamask-extension#13456]
### Describe the bug

When working with multi-step/tx processes it is easy to get the ledger device into an unusable state that requires the extension to need to be reloaded in order to continue.

### Steps to reproduce

1. Go to sushi swap on Polygon
2. Attempt a swap with a token you have not yet traded with (so that you must perform an approval tx)
3. When the approval confirmation is up, confirm it in metamask, and confirm that ledger asks you to sign (but don't sign yet)
4. Click the swap button in Sushi Swap so that the swap confirmation appears
5. Sign the original tx on your ledger.
6. Click confirm on the swap confirmation.
7. See that you never receive the prompt to sign on your ledger.
8. Perform any number of other transactions and see the ledger never shows the sign request.
9. Reload the extension from extension manager
10. Try a transaction and see ledger receives signing request

### Version

10.8.1

### Browser

Chrome, Brave

### Operating system

Linux

### Hardware wallet

Ledger

### Additional context

https://ledger.slack.com/files/U02JV8N57LM/F02NPEMTDQS/soft_lock.mp4

https://consensys.slack.com/archives/C02CYKAA8G1/p1642124072010200

These links will be unaccessible to all but our team, but the contents are a thread discussing various support tickets and videos of the bug occurring.

**Comment by hilvmason** [comment]
Additional context from Customer Success:
# “mm_bug_23” Ledger device:UNKNOWN_ERROR (0x650f)

- 45 tickets in zendesk, starting in late october early november. 
- I am not able to send tokens from my ledger that is connected to metamask. No error is displayed when I send a token but it does not get sent after the transaction. No token amount in tax fee is deducted.
In the settings however I see an error message EthQuery Rpc error ledger device . Unknown error 0x650f
- we have asked several users for clarification and logs

**Comment by danjm** [comment]
@brad-decker Is this a sev1 bug? It only affects ledger users, and there is a workaround, right?

**Comment by AlexHerman1** [comment]
this is continuing to show up and appears to be a blocker for some users to use ledger with MM at all
