### ISSUE TITLE
Update "Forgot Password?" copy

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#13474]
## **User Story**
[Notion story](https://www.notion.so/Quick-fix-for-Forgot-Password-flow-copy-42a3794f8fca446abf9ef3cc3225211f)

## **Steps to reproduce**

1. Go to unlock screen on MetaMask extension
2. Notice “Import using Secret Recovery Phrase” copy
3. Click on it
4. Notice the copy on the ‘Restore your Account’ screen

## **Screenshots**

Current screens that should have the copy updated:
 - Unlock screen:
![import-using-srp](https://user-images.githubusercontent.com/34968356/151845898-e8acce33-67ee-4bbd-b976-784df43b572b.png)

 - Restore your Account screen:
![image (1)](https://user-images.githubusercontent.com/34968356/151845970-6f72e027-0b75-4552-ba5a-509d749e103e.png)

## **Task**

1. Update the ‘Unlock’ screen copy from “Import using Secret Recovery Phrase” to “Forgot Password?”
2. Update the ‘Restore your Account’ screen copy:
    1. the title should be : “Forgot password?”
    2. the copy below the title should be: 
        
        “MetaMask cannot recover your password.
        
        To recover access to your wallet you will have to restore it using the Secret Recovery Phrase. This action will overwrite existing wallet data and cannot be undone. Make sure you’re using the correct Secret Recovery Phrase.
        
        If you restore a wallet using the Secret Recovery Phrase, only the wallet’s initial account will appear at first. You will need to [re-add any other accounts](https://metamask.zendesk.com/hc/en-us/articles/360015489271-How-to-add-missing-accounts-after-restoring-with-Secret-Recovery-Phrase) created using the SRP. 
        
        Additionally, any imported external account, or custom tokens that were added, will not appear. You will need to [re-import any such accounts](https://metamask.zendesk.com/hc/en-us/articles/360015489331-How-to-import-an-Account) using their Private Key(s), and [re-add any tokens](https://metamask.zendesk.com/hc/en-us/articles/360015489031-How-to-add-unlisted-tokens-custom-tokens-in-MetaMask) that are missing.”

**Comment by witee-star** [comment]
https://cyberbump.net/metamask-ronin-and-binance-wallet-password-recovery-using-btcrecover-lost-or-forgotten-password/
