### ISSUE TITLE
Improve "Known Contract Address" warning

### ISSUE THREAD

**Issue by cyanlink** [MetaMask/metamask-extension#13486]
### Describe the bug

Background: See [My reddit post](https://www.reddit.com/r/CryptoCurrency/comments/sgdxtg/psa_we_should_do_something_for_todays_half/
)
And [See this tweet](https://twitter.com/alex_kroeger/status/1487821077669552132?s=20&t=gzYlmQVEG7k5vw6PEphA3A)

TL;DR: Metamask should display a warning dialog whenever user try to send ERC-20 token to ANY Contract Address directly. Many other wallet software already added this feature e.g. rainbow.me, block wallet. 
The current ["known contract address" solution](https://metamask.zendesk.com/hc/en-us/articles/360020028092-What-is-the-known-contract-address-warning-) is far from enough to protect users. 

Here is my proposed warning text:

> WARNING
> The recipient address you typed in is a Contract address.
> Typically, if you want to give asset to a contract, you should use the dApp of the contract, usually in the form of a website, then follow the instructions there. NOT transferring it here.
> We do not know if the recipient contract can handle a direct token transfer like what you are trying to do, or not. Usually, if it is an DeFi contract, or a token contract, it does not have the ability.
> If that’s the case and you proceed, ALL ASSET SENT will be PERMANENTLY LOST, there is NO WAY to RECOVER.
> Are you sure you want to proceed?
> Cancel (In Big Red Button).
> I want to proceed anyway.
> Option 1: It’s my smart wallet. Mark it as my smart wallet address. Proceed.
> Option 2: I’m very sure this is what I want to do. Proceed.

Full article:
A man just lost 195 WETH, by sending it back to WETH contract address, thinking it would return him raw ETH. He was mislead by introductions on Binance Academy (see original post on r/ethereum). Three more victims showed up today, losing 0.1 0.05 0.03 WETH respectively, check WETH contract addresses’ own WETH holding.
Since ERC-20 standard does not provide a way to notify contracts when they receive token transfers, and it does not mandate the contract the ability to send tokens back out, people who bring the real world common sense may think it wrongly as “I sent it to the account get Wrapped token, now I send it back I should get raw token back”, result in permanent unrecoverable loss.
Vitalik pointed out that Smart, Self-Custodial Wallets are Smart Contracts too, so we cannot ban all transfers to Contract Address all together. I suggest Metamask on all platforms show a warning as shown above when user try to send any ERC-20 token to a Contract Address.
It might be the last chance before unrecoverable loss happens, for many users to realize that it is not the correct operation to do what they want to achieve.

### Steps to reproduce

The current "known contract address" solution at https://metamask.zendesk.com/hc/en-us/articles/360020028092-What-is-the-known-contract-address-warning- is far from enough to protect users. 
This mechanism must detect any contract address by querying ethereum backend, because you can't whitelist all of them.
The contract address of WETH9 token is 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 . You can all try it out to copy paste it into your Metamask wallet and there will be absolutely ZERO warning about it being a contract address.

### Version

10.8.1

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by cyanlink** [comment]
related #12642 , (I'm literally shocked why the team is not fixing it with top priority).

**Comment by AlexJupiter** [comment]
@cyanlink thanks for the detailed documentation here. This problem is actually being worked on over here: https://github.com/MetaMask/metamask-extension/pull/12983

**Comment by cyanlink** [comment]
> @cyanlink thanks for the detailed documentation here. This problem is actually being worked on over here: #12983

Sir are you from the MM dev team? they gave zero response to me (support community, support ticket reply via email) so far.

**Comment by AlexJupiter** [comment]
@cyanlink I'm a Product Manager at MetaMask. Apologies for the lack of response via other angles but hopefully you have a space for productive discussion in the linked PR now.
