### ISSUE TITLE
Consolidate README into the knowledge base

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#1349]
Our README is getting fairly bloated--it might be beneficial to convert some of it into a wiki, such as the instructions for creating/deleting notices and adding new networks.

**Comment by flyswatter** [comment]
Could also break these guides into their own markdown files, so they're still in version control.  They can be linked to like a normal webpage.

Or we just use the github wiki feature, either way.

**Comment by whymarrh** [comment]
Most of the content in the README has been factored out into the `docs/` directory
