### ISSUE TITLE
Let dapps request a specific version when a snap is installed

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#13499]
Dapps should be able to request to install a specific version or version range of a snap.

**Comment by rekmarks** [comment]
@holantonela I marked this as in need of designs, but before doing anything, we should review whether the version of the installed snap is adequately represented during installation. We probably want to display it on the dapp's permission request to install the snap, and I don't believe that we are at the moment.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/13499?planning-poker) with ZenHub @Gudahtt @shanejonas @FrederikBolding @hmalik88 @ritave @holantonela

**Comment by Gudahtt** [comment]
It's not entirely clear to me what work should be included here. The shunkworks changes needed will be handled in https://github.com/MetaMask/snaps-skunkworks/issues/222 presumably.

That leaves the RPC method changes (i.e. adding `version` as an optional property, presumably), and associated documentation. Presumably this also requires API changes to show this requested version during the install flow, and showing that in the list of site permissions on the snap settings page. 

What I'm less sure of is how to handle errors. If we can't find a version in the requested range, should we throw it back to the dapp without telling the user? If we tell the user, where should that error be shown?

The same error handling question applies for the case where there is an existing install with a different version (irrespective of whether we can find a matching version on npm).

**Comment by rekmarks** [comment]
@Gudahtt the error work certainly falls under this issue. I'm also uncertain of what do. I suppose for MVP purposes, we can just throw it back to the dapp without telling the user, as you suggested. Otherwise, we would have to display the error in the confirmation popup UI.

> Presumably this also requires UI changes to show this requested version during the install flow, and showing that in the list of site permissions on the snap settings page.

This seems to imply that the requested version should be a caveat. While the permission request for the snap will include the parameter specifying the snap's version, I'm not sure whether the version should be a caveat or not. I was thinking it could simply be a parameter during the request to use a snap that's thrown away afterwards.

**Comment by Gudahtt** [comment]
Throwing the error back to the dapp makes sense as an MVP! I can't imagine us _not_ doing that to be honest, so the real question is whether to return the error to the dapp or to _both_ return it and show the user. We can add a user-facing error later if we feel that it's appropriate.

**Comment by holantonela** [comment]
First WIP to review 📌

If the dapp requires a newer snap
https://www.figma.com/file/mKIkB5V0k2iYUpz7w7syGO/Untitled?node-id=1%3A1171

If the publisher has a new version
https://www.figma.com/file/mKIkB5V0k2iYUpz7w7syGO/Untitled?node-id=1%3A1388

For both scenarios:
- After the user updates, some dapps using an old version of the Snap will break. Should we add a notice about it? 
- If the user does not update, should we keep the pending update persistent? 
- If the user does not update, should the dapp give an error or show that error?

**Comment by FrederikBolding** [comment]
Doing a PR to add the version to the Snap install UI as discussed in the design sync. @rekmarks @holantonela 

Not sure if we should split this issue into more issues to make it clearer which parts of the UI is missing.

**Comment by FrederikBolding** [comment]
https://github.com/MetaMask/metamask-extension/pull/13931
