### ISSUE TITLE
[Bug]: Permissions request: account selection screen has odd overlaps

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#13506]
### Describe the bug

The permissions request UI is buggy when a user has many accounts.

### Steps to reproduce

1. Have a long list of accounts in MetaMask.  I recommend at least a dozen; demo observed with ~40. 
2. Visit https://metamask.github.io/test-dapp/
3. In the "Permissions Actions" box, click "Request Permissions." 
4. MetaMask opens with a screen labeled in the upper right "1 of 2" titled "Connect With MetaMask: Select the account(s) to use on this site."  There should be one scrollbar on the left. 
5. Select one account near the top of the list to connect with, and scroll down. 

Actual behavior: 
The text "Only connect with sites you trust. Learn more" overlaps the bottom of the box for the 8th account; the "Cancel" and "Next" buttons overlap the 9th and 10th accounts (making the 9th non-selectable; you can't connect with that one).  There are no buttons/text at the bottom of the list; you just have to know to look around the 9th/10th account for buttons to click to proceed.

Expected behavior: 
The text and buttons come after the last account in the list.

### Version

10.9.0

### Browser

Chrome

### Operating system

Windows

**Comment by mradziwon** [comment]
Assign this issue to me pls.

**Comment by mradziwon** [comment]
Screenshot of the current issue:
![Screenshot from 2022-02-05 13-11-18](https://user-images.githubusercontent.com/6785984/152641637-77e485d5-c383-4050-9cb0-4117e55325a2.png)

And after fix:
![Screenshot from 2022-02-05 13-12-07](https://user-images.githubusercontent.com/6785984/152641658-b38f5bc7-d961-4c64-a822-d4ea03f0d9f1.png)
![Screenshot from 2022-02-05 13-07-17](https://user-images.githubusercontent.com/6785984/152641675-76c1569c-eab4-4ea3-9278-9b003074314e.png)

**Comment by mradziwon** [comment]
I see someone already pushed fix. No need to assign me.
