### ISSUE TITLE
[Bug]: Polygon RPC appears to be down

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-extension#13505]
### Describe the bug

Switching to the Polygon network RPC, the loading spinner goes indefinitely until it fails, and trying again does not fix the issue. 

### Steps to reproduce

1. Open Extension
2. Switch to Polygon network RPC

### Version

10.8.1

### Browser

Chrome

### Operating system

Windows

**Comment by darkwing** [comment]
Thank you for filing @Montoya ; we should do a better job surfacing or more quickly showing connectivity problems.

**Comment by Montoya** [comment]
Update on this: my issue was that I was using an outdate RPC which appears to not be working anymore. After switching to the latest recommended RPC, the problem is gone. 

Unfortunately without any error messaging, I had to guess my way to this outcome.

**Comment by AlexJupiter** [comment]
Closing this issue as this improvement will be part of the custom networks epic.
