### ISSUE TITLE
Trying to Sign on BSC : Not supported on this device [Bug]: 

### ISSUE THREAD

**Issue by ziroxuc** [MetaMask/metamask-extension#13519]
### Describe the bug

I am using Trezor One connected with metamask and I am using the network BSC on the site https://nominex.io

When I am trying to reinvest I have to sign a contract but I got an error that says

MetaMask Message Signature: Error: Not supported on this device

<img width="738" alt="Screen Shot 2022-02-06 at 19 15 44" src="https://user-images.githubusercontent.com/5958657/152703715-b6832acc-1d29-479a-89bd-9d774cfe04f7.png">

<img width="418" alt="Screen Shot 2022-02-06 at 19 25 55" src="https://user-images.githubusercontent.com/5958657/152704285-4762ebf8-ea95-482c-b616-dbe6e12479e6.png">

### Steps to reproduce

1. Go to nominex.io
2. Click button reinvest 
3. Try to sign the contract

### Error messages or log output

```shell
Internal JSON-RPC protocol error

MetaMask Message Signature: Error: Not supported on this device
```

### Version

MetaMask 10.9.0

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

Trezor

### Additional context

This only happens when I try to sign this specific contract, the others functions works well, like swap, buy

**Comment by danjm** [comment]
Closed by https://github.com/MetaMask/metamask-extension/pull/13693
