### ISSUE TITLE
Begin tracking initial user traits

### ISSUE THREAD

**Issue by brad-decker** [MetaMask/metamask-extension#13528]
### Background

For a while now, (search identify, traits, in metamask-metametrics), we have discussed that we would like to start tracking traits using segment's identify method. our original decision to not use identify was in an effort to protect privacy, however we have since obscured user identity enough that we can start using properties without compromising user privacy. A good example would be tracking the number of accounts a user has. We achieve this same metric by attaching that property to various other unrelated events. We'd also like to track which settings the user has modified which could impact their user journey. 

This epic will contain issues that will lead to having an implementation of segment's identify method, as well as a few baseline traits tracked. From there we can add new issues to various other epics and features.

**Comment by sc0Vu** [comment]
Hi there,

I've found metamask added some tracking functionality in the recently release (segment.io/sentry.io).
Just wondering is there any to turn off this function in user settings?

Thanks
