### ISSUE TITLE
NFT UX Audit

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#13525]
Sweep through the recently added NFT features to ensure we're ready for release on the UX/UI front.

**Comment by SayaGT** [comment]
I have found couple of bugs and some UX issues. Listing them below with some design updates wherever necessary.

**1. NFT auto detection alert in NFT tab**
On chrome, I did not get the NFT detection alert when I first logged in. Auto detect NFT & OpenSea API settings were auto enabled. The alert only appeared after I manually turned the setting off. It worked fine on Firefox. 

**2. Bug in toggle setting**
I stress tested the toggles for OpenSea API & NFT token detection setting. After few clicks, NFT detection toggle remained enabled while the OpenSea API toggle was disabled. See img below
<img width="1887" alt="Screenshot 2022-02-08 at 13 07 03" src="https://user-images.githubusercontent.com/87030673/153004130-10cc7804-f35f-4ff5-8bfc-293b248bcb96.png">


3. The NFT's didn't auto load after turning the setting on. I had to manually import them. Refreshing didn't load them either.

**4. Trouble importing NFT**
I could not import my ENS (ERC721 token) in NFT tab. I kept getting an error (see screenshot below). This appears in my mobile wallet.
<img width="1580" alt="Screenshot 2022-02-08 at 13 33 14" src="https://user-images.githubusercontent.com/87030673/153002439-91cc014a-63d9-41f9-8aed-ed76943d6ec8.png">
![Mob_NFT](https://user-images.githubusercontent.com/87030673/153046520-231626b1-0b1b-4f88-9d02-2205978a3a46.jpg)

 
**5. We need to update the UX for the NFT token displayed in Assets tab.**
Currently if a user clicks on the token in the assets tab, a message is displayed asking user to import it as an NFT. This is confusing if a user has already added that NFT. We should update the message suggesting that NFT has already been imported and this token will disappear from the asset list. [See the Figma file](https://www.figma.com/file/8Xe22jEPgcElS5tWPw8AGM/NFTs-in-extension-(MVP)?node-id=1212%3A12893).

6. Alert/ Error messages look weird in the Extension pop up. Need to adjust the padding.
[See the design suggestions in Figma file](https://www.figma.com/file/8Xe22jEPgcElS5tWPw8AGM/NFTs-in-extension-(MVP)?node-id=1212%3A12894)

7. Import NFT error state - Updated UX & design
[See the Figma file here](https://www.figma.com/file/8Xe22jEPgcElS5tWPw8AGM/NFTs-in-extension-(MVP)?node-id=1212%3A12897)

**Comment by adonesky1** [comment]
Going through to reproduce these now!

**Comment by adonesky1** [comment]
https://github.com/MetaMask/metamask-extension/pull/13575 should fix #2

**Comment by adonesky1** [comment]
Number 3 is a live issue since [OpenSea has removed support](https://twitter.com/NadavAHollander/status/1489018802356563970) for querying their `/assets` endpoint without an api-key. We rely on this endpoint for auto-detection.

**Comment by adonesky1** [comment]
I'm not able to reproduce number 1. @SayaGT I think I'd like to send you a new build and have you try it again?

**Comment by adonesky1** [comment]
The ENS issue has to do with the fact that we do not handle large `tokenId`s properly. Will write up a ticket to address this!

**Comment by adonesky1** [comment]
Ticket for the ENS issue here: https://github.com/MetaMask/metamask-extension/issues/13581

**Comment by adonesky1** [comment]
I have separated out the UI issues into this ticket: https://github.com/MetaMask/metamask-extension/issues/13620

So that it can be easily delegated (probably to PS team).

**Comment by SaraCheikh** [comment]
From the last design review, these issues are currently solved.
