### ISSUE TITLE
Show conversion value and images for tokens on Optimism 

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#13546]
### Describe the bug

When viewing tokens on Optimism, I don't see any currency conversions or images for those tokens.

### Steps to reproduce

1. Switch to Optimism 
2. Check out your token list
3. What is it all worth !!????!! Also no img

![Screen Shot 2022-02-07 at 6 47 20 PM](https://user-images.githubusercontent.com/1016190/152908462-c7de3800-f845-4848-bf9a-2e418e30c8e4.png)

### Version

10.8.1

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
This happens to all custom networks. The general problem is that they seem to be treated as test networks, not displaying the conversion unless the setting for conversion on test networks is enabled.
https://github.com/MetaMask/metamask-extension/issues/16129

For a temporary workaround until this is fixed, you can go to Advanced Settings and activate Conversion on Testnets. This should enable the conversion on Optimism, as well as other custom networks  @bdresser  @bschorchit
