### ISSUE TITLE
Add snaps notifications

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#13553]
Once we added the ability for snaps to [create notifications](https://github.com/MetaMask/snaps-skunkworks/issues/230), we should implement these notifications in MetaMask.

We are likely to implement notifications that appear inside MetaMask itself, and for those we will need designs. These notifications should:
- be dismissable.
- appear on the home screen in the popup and/or the full screen UI.
- add to the notification badge count on the browser action icon.

The other option for notifications is to give snaps access to native browser notifications, if in an attenuated way. It's unclear if this is something we should or will pursue at this time.

**Comment by Montoya** [comment]
Curious to know what the user experience will be when the MetaMask popup / full UI is not in focus, whether using built-in or native browser notifications. Will the user see the notification or will they miss it? Also, if native browser notifications are used, will that require the user to make an extra step in order to give permissions in the native browser UI?

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps--Core-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/13553?planning-poker) with ZenHub @Gudahtt @hmalik88 @ritave

**Comment by rekmarks** [comment]
@Montoya, we'd make the notifications persist in the MetaMask UI until dismissed by the user, or perhaps timed out if we can convince ourselves that the user saw them (perhaps by the page that they're displayed on in our UI being active).

For the native browser notification, the extension already has that permission, so there will be no extra prompt.

**Comment by holantonela** [comment]
We will re-use existing MM components to allow developers to prompt notifications inside MM via Snaps.

Ideally, developers should be able to define:

1. **Style**: _Which type of notification is going to be triggered? Does it require user input?_
We have two types of notifications currently available:
a. [Popover](https://metamask.github.io/metamask-storybook/index.html?path=/docs/ui-components-ui-popover-popover-stories-js--default-story) 
b. [Actionable Message](https://metamask.github.io/metamask-storybook/index.html?path=/docs/ui-components-ui-actionable-message-actionable-message-stories-js--left-aligned)

2. **Type**: _What is the status of this notification?_
Each UI component has different available states, aka `type`. The Actionable Message can be Default, Warning, Success.

3. **Context**: Where is this notification going to be shown?
Developers will be able to define [where](https://github.com/MetaMask/metamask-extension/tree/develop/ui/pages) the notification should appear. I'd start with a few options. I'd leave Confirmation screens for a second iteration.
a. [Home](https://github.com/MetaMask/metamask-extension/tree/develop/ui/pages/home)
b. [Token Details](https://github.com/MetaMask/metamask-extension/tree/develop/ui/pages/token-details)

It will be the first batch of UI components we will expose to developers via Snaps! I expect that we can share feedback to the Design System team to help document their work on improving the consistency/flexibility of these components. 

Also, ideally, this implementation does not break (or can be easily fixed) after they re-shape this UI.

What do y'all think?

cc @georgewrmarshall @Akatori-Design

**Comment by holantonela** [comment]
Do we want to make explicit/visible that the notification is triggered by a Snap and not MM itself? A helper tooltip can make the job.

**Comment by holantonela** [comment]
Just to be clear, I'm not trying to create a new notification system. I'm just pointing on which components we could rely to make it more extensible and easy to maintain. 

If we want to attach this feature with our Home Notification System, we can do it! It will help also to iterate what we consider on the current implementation. Which component it is using @Gudahtt? Do we have documentation somewhere to understand which variables we can offer to developers?

**Comment by georgewrmarshall** [comment]
@holantonela regarding the notification components I think they need a bit of work before we can release them to the community. The api is quite messy. I'd like to clean it up or possibly deprecate it in favour of a new component. I think the Popover is in better shape but I would still like to have a look at the component api before giving it the green light.

**Comment by Gudahtt** [comment]
>Which component it is using @Gudahtt? Do we have documentation somewhere to understand which variables we can offer to developers?

There is no documentation for system notifications because it's an internal system. We have only used it ourselves 7 times. The exact details of what it can do today don't really matter, are subject to change, and would not be directly exposed via the snaps API anyway.

It is currently using its own component. It was built before the two components you referenced.

>It will be the first batch of UI components we will expose to developers via Snaps! 

>I think they need a bit of work before we can release them to the community. 

I did not think this issue involved custom UI. I had assumed that we would be treating this similarly to custom confirmations, i.e.it would be _our_ UI, just with custom contents defined by the snap. And perhaps other configurable options like buttons, actions, styles, etc. The snap authors will not be directly building UI with our components.

**Comment by holantonela** [comment]
> I did not think this issue involved custom UI. I had assumed that we would be treating this similarly to custom confirmations, i.e. it would be our UI, just with custom contents defined by the snap. And perhaps other configurable options like buttons, actions, styles, etc. The snap authors will not be directly building UI with our components.

Yeah. That is the point. When I said "expose" I meant "allow developers to push content in the UI component".

**Comment by holantonela** [comment]
After our Design Sync, we refined some of the requirements for this feature on `V1`

- Notifications are going to follow just one type of component (toast)
- Users should be able to identify that a notification is coming from a Snap
- Users should be able to read persistent notifications in a /notifications list kind of fashion
- Users should be able to discover that a notification has been triggered even if the MM UI is closed
- Buttons are not available
- Notifications should be able to stack or get paged

**Comment by holantonela** [comment]
WIP https://www.figma.com/file/2QWFaRYpa9SDZRCwFlW17j/Snap-Notifications?node-id=0%3A297

**Comment by holantonela** [comment]
Hi, the latest UI is here https://www.figma.com/file/2QWFaRYpa9SDZRCwFlW17j/Snap-Notifications?node-id=0%3A297

Update on design requirements:

- ~Notifications are going to follow just one type of component (toast)~
- Users should be able to identify that a notification is coming from a Snap  ✅ 
- Users should be able to read persistent notifications in a /notifications list kind of fashion  ✅ 
- Users should be able to discover that a notification has been triggered even if the MM UI is closed  ✅ 
- Buttons are not available but links are  ✅ 
- Notifications should be able to stack or get paged  ✅ 
- Notifications should be able to get accessed via a menu link  ✅

**Comment by holantonela** [comment]
Also, some thoughts about how notifications are marked as read

```
Notifications are marked as read if the user:
- interacts with the notification (click a link) 
- interacts with the notification list (scroll)
- click on `mark all as read` button
```

**Comment by FrederikBolding** [comment]
Closing via #14605
