### ISSUE TITLE
Move SearchIcon to icon folder and create story

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13563]
**Description**
Move `SearchIcon` component file from `ui/components/ui/search-icon/search-icon.component.js` to `ui/components/ui/icon/search-icon.component.js`

Add to icon stories `ui/components/ui/icon/icon.stories.js` under "Other Icons"

<img width="1440" alt="Screen Shot 2022-02-09 at 10 37 15 AM" src="https://user-images.githubusercontent.com/8112138/153096734-c23076e6-a4df-4955-801f-b4af4e38cda3.png">

**Comment by rockingrohit9639** [comment]
> 

I would like to work on this issue @georgewrmarshall

**Comment by georgewrmarshall** [comment]
Awesome @rockingrohit9639! I've assigned you the issue. Looking forward to your PR!
