### ISSUE TITLE
[Bug]: Enter the login password

### ISSUE THREAD

**Issue by elfecho** [MetaMask/metamask-extension#13586]
### Describe the bug

If the account is locked, will the login pop-up window pop up when you click Connect Wallet again?

### Steps to reproduce

1. Connect Wallet
2. Lock Wallet
3. Connect the wallet again

### Version

10.9.2

### Browser

Chrome

### Operating system

Windows

**Comment by darkwing** [comment]
If you lock the wallet, you will be asked for your password again when you re-open MetaMask.
