### ISSUE TITLE
[Bug]: Chrome - If a user locks their wallet and clicks 'Connect Wallet' on a dApp, no MetaMask password window pops up

### ISSUE THREAD

**Issue by addmorebass** [MetaMask/metamask-extension#13618]
### Describe the bug

If a user locks their MetaMask wallet, and clicks 'Connect Wallet' on a dApp, there is no pop up window.

There is only a notification that displays within the MetaMask extension (no pop up).

It would be much more user friendly if MetaMask popped up with the password window if a user clicked 'Connect Wallet' after locking their wallet.

### Steps to reproduce

1. Connect wallet to UniSwap
2. Lock wallet
3. Try connecting wallet again to Uniswap
4. No pop-up appears prompting the user to enter their MetaMask password. User has to be aware of the notification within the browser icon.

### Version

10.9.2

### Browser

Chrome

### Operating system

MacOS

**Comment by darkwing** [comment]
Closing as duplicate of https://github.com/MetaMask/metamask-extension/issues/13590

**Comment by addmorebass** [comment]
Let me know if you need any more info @rekmarks. Thanks.
