### ISSUE TITLE
[Bug]: How can I update the rpc url for an existed network

### ISSUE THREAD

**Issue by Taosome** [MetaMask/metamask-extension#13614]
### Describe the bug

If i have already added the polygon network, now i wanna add a new polygon network (with different rpc url). 
To do this, i got a problem. Metamask cannot update the network/rpc.
Is there any way to deal with this problem?

Help Me!!!
Thanks!!!

### Steps to reproduce

1. Add a network into metamask normally
2. Choose a same network with different rpc url
3. Keep adding
4. No error but it can't works successful

### Version

10.9.2

### Browser

Chrome

### Operating system

Windows

**Comment by Taosome** [comment]
Um~~~   whether an instance is exposed from metamask for users to transfer "updateAndSetCustomRpc" ?

**Comment by bschorchit** [comment]
Hey @Taosome, you can do that by clicking on network menu dropdown, clicking on `Add network` and filling in the form with new RPC URL (screenshot below)

<img width="1085" alt="Screen Shot 2022-02-14 at 17 16 48" src="https://user-images.githubusercontent.com/34968356/153939856-dd9f03cf-fd98-47d8-aad2-6b2b778b656a.png">
.

Does this answer your question?

**Comment by Taosome** [comment]
> 
Thanks  @bschorchit 
But I’m sorry. I didn't describe my question specifically. I want to achieve it through code(javascript) instead of UI.

**Comment by sambacha** [comment]
> > 
> 
> Thanks @bschorchit But I’m sorry. I didn't describe my question specifically. I want to achieve it through code(javascript) instead of UI.

you can not, this issue has been raised continuously

**Comment by Taosome** [comment]
> > > 
> > 
> > 
> > Thanks @bschorchit But I’m sorry. I didn't describe my question specifically. I want to achieve it through code(javascript) instead of UI.
> 
> you can not, this issue has been raised continuously

whatever, thanks

**Comment by vandan** [comment]
This is still an issue.

**Comment by shanejonas** [comment]
We don't support this yet via API.
