### ISSUE TITLE
Swap out javascript instances of color with theme context

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13632]
Dependencies: #13630
Related(Should also help solve): #13247

Description
Swap out current static hex values and other color references in the javascript for updated color design tokens imported from the `@metamask/design-tokens` library using the theme provider and react context.

This may have to be split into multiple PRs as there are a lot of instances of static hex values spread throughout the code base.

Technical Details
- Swap out any static hex values for the appropriate design tokens provided by the theme provider

**Comment by GuillaumeRx** [comment]
Not needed since css variables are interpreted in browser, using the vars to replace inline hex values will work

**Comment by georgewrmarshall** [comment]
Closing as to @GuillaumeRx's point it's not needed
