### ISSUE TITLE
Create theme provider for dark theme using context

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13630]
**Description**
Create a theme provider using react context for colors referenced from javascript files.

**Technical Details**
- Create a theme provider using react context
- Create unit tests to test theme provider is working
- Use the `@metamask/design-tokens` library to pass design tokens into the provider
- Document usage of the theme provider and how to use color inside of javascript files in storybook

**Comment by GuillaumeRx** [comment]
Not needed, see https://github.com/MetaMask/metamask-extension/issues/13632#issuecomment-1044944039

**Comment by georgewrmarshall** [comment]
Closing as to @GuillaumeRx's point it's not needed
