### ISSUE TITLE
[Bug]: Metamask crashes local mainnet fork node running on port 31337

### ISSUE THREAD

**Issue by regohiro** [MetaMask/metamask-extension#13638]
### Describe the bug

I have a local mainnet hardhat node running on port 31337. When I try to send a transaction on Metamask, I get the following error in the browser console:
```
Uncaught (in promise) Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"Received invalid block tag 24972989. Latest block number is 23964019"}}}'
```
On top of that, the node freezes (crashes) making it unable to call or send anymore transactions. 

I have:
- Reinstalled Metamask
- Reset all accounts in Metmask
- Restarted Hardhat node
- Updated and downgraded hardhat
but none of these solved the issue.

However, when I change the chainId from 31337 (or any chain id) to 1337 in the hardhat config and Metamask, I do not get this issue anymore. Also, I had no issue sending transaction from Hardhat CLI or ethers.js. 

## Hardhat configuration 
```
networks: {
  hardhat: {
    chainId: 31337,
    forking: {
      enabled: true,
      url: https://polygon-mainnet.g.alchemy.com/v2/...
      blockNumber: 23964019
    }
  }
},
```

## Metamask configuration
<img width="450" alt="Screen Shot 2022-02-15 at 23 06 34" src="https://user-images.githubusercontent.com/62818999/154078151-5295d8bf-856b-4d34-aaa1-f6cc8ecf9aea.png">

## Local node setup
1. Clone [this](https://github.com/regohiro/hh-node.git) repo and install dependencies
2. Fill .env file with rpc url and block number
3. Run `npx hardhat node`

## Metamask setup 
1. Use `test test test test test test test test test test test junk` for recovery key
2. Configure network under Settings > Networks and fill with the attached image above
3. Send a ETH transfer transaction between accounts

### Error messages or log output

```shell
Uncaught (in promise) Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"Received invalid block tag 24972989. Latest block number is 23964019"}}}'
```

### Version

10.9.2

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by gregegan** [comment]
Experiencing same issue - critical.

**Comment by aliveli186** [comment]
MetaMask v10.9.2 is buggy on Edge browser. However v10.9.2 works on Chrome.
If you're using Edge remove MetaMask and re-install with v10.7.1 (v10.9.2 no longer exists for Edge).
![image](https://user-images.githubusercontent.com/8914034/154170739-501a8661-ca16-490b-93b0-f8a898a99200.png)

**Comment by regohiro** [comment]
> Indeed it crashes hardhat. Use ganache meanwhile, it works.

But is this on chain id 1337? Or does ganache work with chain id other than 1337?

**Comment by egorFiNE** [comment]
> But is this on chain id 1337? 

I don't think the chainId has anything to do with the problem. As mentioned in the linked ticket, it seems that `eth_feeHistory` call with hardhat is the cause.

**Comment by NatPDeveloper** [comment]
> chainId: 31337,

I tried with 1337 but I had the same error.  Ganache-cli does work as said before.

```
eth_feeHistory

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/reportbug
```

**Comment by ajaykumargdr** [comment]
I'm still facing this issue while using different account than the one that is used while hardhat ignition deployment. Anybody got some fix on this issue?
