### ISSUE TITLE
Snaps Logo / Icon

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#13654]
We need an icon for Snaps. It will be used in small sizes in our UI or in big sizes in product/marketing material.

**Comment by Pandapip1** [comment]
How about this?
![snap-logo](https://user-images.githubusercontent.com/45835846/154528437-7fb77e68-59d4-46d8-8654-7d29d07af0a4.png)

**Comment by holantonela** [comment]
initial exploration
https://www.figma.com/file/Ao7LDD1p8cG5NIqJtUZbTC/Snap-Icon?node-id=0%3A53
