### ISSUE TITLE
[Bug]: Asking for trezor passphrase for every txn

### ISSUE THREAD

**Issue by blackboxtrading** [MetaMask/metamask-extension#13667]
### Describe the bug

From sometime yesterday, Metmask starts to ask for trezor passphrase for every txn. Previously I only need to input passphrase once when I connect  the device.

### Steps to reproduce

1. Trezor model T with latest firmware
2. Ubuntu + Chrome

### Version

10.9.3

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

Trezor

**Comment by AlexJupiter** [comment]
@blackboxtrading can you confirm your transactions are going through okay, even if there has been a change in your experience?

**Comment by Bleujj1** [comment]
@blackboxtrading . Have you tried synchronize and debug your wallet yet?
