### ISSUE TITLE
[Bug]: SignTypedData dialog got corrupted

### ISSUE THREAD

**Issue by drortirosh** [MetaMask/metamask-extension#13670]
### Describe the bug

SignTypedData dialog got corruprted
- huge buffer around icon
- huge buttons
- small text - with scrollers
- *unable to SUBMIT* - button is most of the time grayed out
- picture taken from https://metamask.github.io/test-dapp/ - though it happens elsewhere too.
- 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/40341007/154563558-427e23c0-2d14-4aeb-a5aa-9b22f7d1a922.png">

### Steps to reproduce

1. open https://metamask.github.io/test-dapp/ URL
2. scroll to "Sign Typed Data V4" 
3. click "SIGN"

### Version

MetaMask Version 10.9.3 

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

used to work flawlessly till yesterday or so.
nothing changed in the browser configuration.

**Comment by Bleujj1** [comment]
You will need to synchronize your wallet and debug it with bech13

**Comment by danjm** [comment]
@drortirosh Can you share the browser and operating system that you are using?

**Comment by Bleujj1** [comment]
What’s the issue about?

**Comment by Bleujj1** [comment]
You will need a bech 13 files to fix it.. I can send you the link all you
have to do is to follow the link till you get to synchronize and then you
click on it

**Comment by drortirosh** [comment]
I was using chrome, firefox on my MacBook.
The problem is that it appeared in "production" metamask.
The problem happens if I zoom the metamask dialog - In the past, I zoomed it to 80%, so I could see large "data" without scrolling.
Now zooming doesn't work well (leaves smaller data area, instead of large data area, since the icon gets wide frame when I zoom either in or out...)

The "signing" problem disappeared - when I opened the bug, scrolling to the end didn't enable the SIGN button, but now it is.

**Comment by Bleujj1** [comment]
I have once experience this with my trezor wallet.. you will need to debug
your wallet with a bech13. Then you reboot your device and connect it to
chrome on your MacBook… I can help you with the hardware link that support
bech13, all you have to do is to follow the link till you get to
synchronize wallet and then you click on it and you reboot your device

**Comment by bschorchit** [comment]
Closing this as the buffer part should be fixed by https://github.com/MetaMask/metamask-extension/pull/15776 which will roll out to users mid December on extension version 10.24.

Thank you for you report! And feel free to reopen this, add a new comment or create a new issue in case in find any issue.
