### ISSUE TITLE
[e2e] Refactor onboarding tests (metamask-ui.spec.js)

### ISSUE THREAD

**Issue by david0xd** [MetaMask/metamask-extension#13677]
e2e test suite refactoring as part of the https://github.com/MetaMask/metamask-extension/issues/11136

This ticket should cover two batches of the tests identified by describe block in the current code within `metamask-ui.spec.js` file:
1. Going through the first time flow
2. Import Secret Recovery Phrase

AC:
- Migrate e2e tests so that they use fixtures to set up test state, and test specific pieces of functionality in isolation.
- Separate onboarding (_Going through the first time flow_) tests into a new file `onboarding.spec.js`.
- The import test should live in `test/e2e/tests/from-import-ui.spec.js` along with the other import tests.

Notes:
- Currently each tests in the `metamask-ui.spec.js` depend on the previous one. When migrating the tests we’re moving away from this pattern by setting up the state of the extension using fixtures which live here `test/e2e/fixtures`.

**Comment by david0xd** [comment]
This one should wait a little bit more until we get more clarified situation with `Onboarding V2`.

**Comment by bschorchit** [comment]
> This one should wait a little bit more until we get more clarified situation with `Onboarding V2`.

Onboarding V2 is paused until MV3 work is completed. This ticket is not a priority at this time.
