### ISSUE TITLE
Implement Network specific insufficient currency warning - follow up

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#13680]
### Figma/Notion  link
Figma: https://www.figma.com/file/BU5iPP4cSDp7bq3FUGaEKq/Insufficient-funds-warning?node-id=0%3A1

### Acceptance criteria
-  Implement "Buy link", for all networks where the "buy button" is enabled? With version 10.10.0 those are Ethereum Mainnet, Polygon, Avalanche, Celo and Fantom. 
- "Buy link" text should be:  "Buy _**token**_" where the _**token**_ is the network main token name (Slack discussion link: https://consensys.slack.com/archives/C02GH833686/p1645195323020069?thread_ts=1645188421.589239&cid=C02GH833686)

## Note
In the previous version the "Buy link" was implemented just for the **Ethereum network**

 When users do not have enough ETH on **Ethereum network**, we prompt users to “Buy ETH” by providing a clickable link, On the mockup below is given ETH example - in the wanring message the “Buy ETH” is clickable link :
![image](https://user-images.githubusercontent.com/49436614/144617950-113b52bb-0f40-4770-8db0-5edb56c353f6.png)

### Open questions
- Tech questions: How to get a list of **_"all networks where the "buy button" is enabled"_**

### Test cases 
- Test using Testdapp options from the screenshot below: 
![image](https://user-images.githubusercontent.com/49436614/158195748-e12819ec-899a-4e03-a282-732c7b38ac26.png)

**Comment by AndreySttar** [comment]
E
