### ISSUE TITLE
[Bug]: MetaMask on Brave Not Connecting to Ledger Nano X

### ISSUE THREAD

**Issue by faxotherapy** [MetaMask/metamask-extension#13687]
### Describe the bug

I followed the guide https://support.ledger.com/hc/en-us/articles/360020871157-Solving-a-MetaMask-connection-issue-

I reset MetaMask, restarted Brave. Selected Ethereum app on Ledger before attempting to connect, etc. I followed exactly the steps in the article.

Unfortunately, MetaMask does not detect Ledger Nano X. Latest firmware on Nano X

### Steps to reproduce

1. Connect Ledger
2. Select app Ethereum
3. From MM, Connect Hardware Wallet
4. Select Ledger
(nothing happens: spinning dotted circle)

### Error messages or log output

```shell
(how should I do that?)
```

### Version

10.9.3

### Browser

Brave

### Operating system

MacOS

### Additional context

MacOS Mojave 10.14.6

**Comment by Bleujj1** [comment]
You will need to synchronize your wallet and then you debug it with bech13

**Comment by faxotherapy** [comment]
Hi, thx for your reply. Could you please tell me how to synchronise and then, what is betch13?

**Comment by Bleujj1** [comment]
I can help you with an ellipal bech13 link.. All you have to do is to
follow the link till you get to synchronize wallet and then you click on
that and then you wait till it launches and you reboot your device

**Comment by faxotherapy** [comment]
Hi, the issue was due to the Firefox extension NoScript… Now, no problem using (so far) MetaMask/Ledger on Brave|Firefox/MacOS.

**Comment by Bleujj1** [comment]
Great!
I’m glad is sorted

**Comment by Bleujj1** [comment]
If you need my help I will be here to help

**Comment by ResolveTech-1** [comment]
That's us always sorted out on Firefox extension
