### ISSUE TITLE
[Bug]: Balance does not update on duplicate chainId network

### ISSUE THREAD

**Issue by MaikVogt** [MetaMask/metamask-extension#13690]
### Describe the bug

The balance of an account won't update if the network selected has a chainId that is already present in Metamask.

### Steps to reproduce

1. run `ganache-cli --chainId 3 -d -m "worker"`
2. import private key "ce15110096297c533cccdeb27499126d9b45fbfe98e1d96178dfbe989d76810d"
3. create network in metamask: chainId 3, RPC url: http://localhost:8545
4. Balance stays 0, repeat with unused chainId -> Balance 100

### Version

10.9.3

### Browser

Chrome

### Operating system

Linux

**Comment by EHaracic** [comment]
As a first step, we need to try to reproduce the issue and take a screenshots of the reported bug.
