### ISSUE TITLE
Hello, I am trying to sell my NFT and after an error. Plz help!!!       There was an error with your transaction. Please try again.[Bug]: 

### ISSUE THREAD

**Issue by Julius22777** [MetaMask/metamask-extension#13777]
### Describe the bug

Hello, I am trying to sell my NFT and after an error. Plz help!!!       There was an error with your transaction. Please try again.[Bug]: 
They are sking to complete listing is should Submit a transaction with your wallet to trade with this currency. This only needs to be done once. 

### Steps to reproduce

1.

### Version

v4.1.1 (827)

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

### Additional context

Hello, I am trying to sell my NFT and after an error. Plz help!!!      
 There was an error with your transaction. Please try again.[Bug]:

**Comment by kevinghim** [comment]
Looks like you're using the MetaMask mobile app. Please file your bug [here](https://github.com/MetaMask/metamask-mobile).
