### ISSUE TITLE
[Bug]: Unable to approve transactions

### ISSUE THREAD

**Issue by A-Y-U-S-H-Y-A** [MetaMask/metamask-extension#13779]
### Describe the bug

Unable to approve transfers of NFT's on OpenSea. Approval always fails and the following is printed in the console

### Steps to reproduce

1.Installed the metamask extension(firefox) from the official site and during an opensea transfer of an NFT, the above error is thrown

### Error messages or log output

```shell
RRNLRequestError: Relay request for `traderRelayMetaTransactionMutation` failed by the following reasons:

1. [500] Error occurred while processing your request. Please try again later.

Error id: 486ee08e93f446feb0782713f91b3520
         relay(identity: $identity, clientSignature: $clientSig
         ^^^
    r RRNLError.js:20
    t RRNLError.js:14
    n RRNLError.js:42
    s createRequestError.js:24
    n createRequestError.js:44
    createRequestError createRequestError.js:110
    default fetchWithMiddleware.js:93
    promise callback*3u+V/t.default fetchWithMiddleware.js:91
    subscribe RelayNetworkLayer.js:59
    o RelayObservable.js:446
    a RelayObservable.js:582
    subscribe RelayObservable.js:279
    a RelayObservable.js:194
    a RelayObservable.js:582
    subscribe RelayObservable.js:279
    e OperationExecutor.js:148
    execute OperationExecutor.js:65
    v RelayModernEnvironment.js:387
    a RelayObservable.js:582
    subscribe RelayObservable.js:279
    exports commitMutation.js:91
    e graphql.tsx:220
    e graphql.tsx:219
    l runtime.js:63
    _invoke runtime.js:293
    P runtime.js:118
    Babel 4
    w graphql.tsx:211
    e trader.ts:101
    l runtime.js:63
    _invoke runtime.js:293
    P runtime.js:118
    Babel 6
    relayMetaTransaction trader.ts:76
    e ActionPanel.react.tsx:284
    l runtime.js:63
    _invoke runtime.js:293
    P runtime.js:118
    Babel 4
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    o helpers.js:73
```

### Version

10.10.1

### Browser

Firefox

### Operating system

Windows

**Comment by zachalam** [comment]
+1, also receiving this error

**Comment by danjm** [comment]
What network are you on when this is happening?

**Comment by tkeidar** [comment]
same here. it happens to me on Polygon

**Comment by A-Y-U-S-H-Y-A** [comment]
> What network are you on when this is happening?

The default network of ethereum mainnet

**Comment by arimed4000** [comment]
+1 getting this same bug.  Any update on the fix?

**Comment by A-Y-U-S-H-Y-A** [comment]
> @A-Y-U-S-H-Y-A is this happening on browsers other than Firefox? Would you also be able to provide a screenshot/recording at all?

I haven't tested for the same on other browsers. 
I wouldn't be able to provide a recording as the error is random. Will be posting a screenshot if I do encounter the same again

**Comment by A-Y-U-S-H-Y-A** [comment]
> @A-Y-U-S-H-Y-A is this happening on browsers other than Firefox? Would you also be able to provide a screenshot/recording at all?

![image](https://user-images.githubusercontent.com/72336361/158049217-5b027772-ee27-4bbb-b5c9-3803b0b15d3c.png)

**Comment by arimed4000** [comment]
I get this on chrome too.

**Comment by arimed4000** [comment]
@A-Y-U-S-H-Y-A 
The this error below happens to me on chrome/metamask when I go to transfer on opensea:
![Screenshot 2022-03-13 13 09 29 - Display 1](https://user-images.githubusercontent.com/60762281/158077286-842aafac-99fb-4af5-a6a7-0d0757944346.png)

**Comment by lyonsbp** [comment]
I also get this error on both Chrome and Edge. Any known workaround yet?

**Comment by SamyKn** [comment]
i have the same transferring Polygon NFTs
it's not a PC or browser issue , i have tried 4 different PCs with 4 different browsers and same error!
any help would be much appreciated

**Comment by sergiochil** [comment]
Having this issue right now. chrome+metamask+polygon on a mac.
Clean installed on Brave and got the same error. 
any help would be much appreciated !

**Comment by tarassh** [comment]
Any ideas how to fix it?

**Comment by sergiochil** [comment]
Yes!

It worked for me when I set the gas fee to maximum. Simple as that.

Em sex., 19 de ago. de 2022 às 02:01, tarassh ***@***.***>
escreveu:

**Comment by sergiochil** [comment]
Did it work?

Em sex., 19 de ago. de 2022 às 09:10, Sergio Chilvarguer <
***@***.***> escreveu:
