### ISSUE TITLE
MetaMask crashes when switching networks if hidden in Chrome Menu

### ISSUE THREAD

**Issue by anodium** [MetaMask/metamask-extension#1377]
When I switched from the Ropsten Test Network to the Ethereum Main Network, MetaMask restarted as expected, and asked me to decrypt my den. But, when I attempt to switch back to the Ropsten Test Network, MetaMask crashes, and the browser goes down along with it.

**Comment by anodium** [comment]
Further experimenting actually demonstrates that MetaMask crashes *only* when the MetaMask icon is hidden inside the Chrome Menu. When in the toolbar, it behaves as expected. Will be uploading a gif in a bit to demonstrate this.

**Comment by anodium** [comment]
Opening MetaMask and switching networks from the Toolbar:
![toolbar](https://cloud.githubusercontent.com/assets/10248424/25728664/89e93e0e-30fe-11e7-9ea1-7ee8d8df8ac1.gif)

Opening MetaMask and switching networks from the Chrome Menu:
![menu](https://cloud.githubusercontent.com/assets/10248424/25728692/b0db9fde-30fe-11e7-9312-75a5cc71bfdc.gif)

**Comment by flyswatter** [comment]
What OS are you on?  What Chrome version?

Looks like a chrome bug, we'll need to report to them with the OS.

**Comment by anodium** [comment]
From `chrome://version`:
Google Chrome: 58.0.3029.96 (Official Build) (64-bit)
Revision: 2a03c99a5f45c6d507af8eb2345ad68a565d1518-refs/branch-heads/3029@{#787}

From `uname -a`:
Linux 4.8.0-51-generic x86_64
Lubuntu 16.04

**Comment by tmashuang** [comment]
Seems to have been patched by Chrome. Will reopen if this is still an issue.
