### ISSUE TITLE
[Bug]: Currently unable to send ERC-20 tokens, it keeps loading forever when I click on "Send" button

### ISSUE THREAD

**Issue by ennie1005** [MetaMask/metamask-extension#13784]
### Describe the bug

Metamask extension: Currently unable to send ERC-20 tokens, it keeps loading forever when I click on "Send" button

### Steps to reproduce

1. Open Metamask wallet >> Choose Ropsten test network
2. Choose ERC-20 assets e.g. USDT
3. Click on "Send" button
Actual result: it keeps loading forever when I click on "Send" button. For ETH asset, it's working fine

### Version

10.10.1

### Browser

Chrome

### Operating system

MacOS

**Comment by kolchowik** [comment]
Hi, I'm experiencing the same situation. MetaMask is connected to our dev network, additionally dev console provides error: Unable to determine contract standard . It used to work, no changes on our end, what can be the cause?

**Comment by hdany** [comment]
Same issue on several machines. I've rolled back to 10.11.3 and it works perfectly, this is something introduced recently, present in version 10.12.4. Another post with the same issue
https://github.com/MetaMask/metamask-extension/issues/14187

**Comment by PascalDuval** [comment]
Same issue.

**Comment by FrederikBolding** [comment]
This might be related to https://github.com/MetaMask/metamask-extension/issues/14522

**Comment by bschorchit** [comment]
Closing this as we're tracking this issue in https://github.com/MetaMask/metamask-extension/issues/14522
