### ISSUE TITLE
Get secp256k1 added to browser crypto API

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1379]
The proposal & debate is on bugzilla here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1051509

My understanding is that we need highly credentialed cryptographers arguing the merit of this proposal.

**Comment by flyswatter** [comment]
This would reduce our bundle size, but this is only really security critical if running crypto in the same process as a site.  (Do sharedworkers do this?)

**Comment by Gudahtt** [comment]
Since this issue appears to be about adding a feature to _browsers_, not to this product, I'll close it here for now. I don't think this is a priority for us at the moment, and if it is, we can track it somewhere else.
