### ISSUE TITLE
Add borderRadius prop to Box component

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#13791]
# Description
Add a `borderRadius` prop to the `Box` component. Not sure if we allow any values or restrict to a certain few.

# Technical Details
- Add `borderRadius` prop to `Box` react component 
- Update controls in storybook
- Update MDX documentation 
- PropTypes have been updated and have a description of what `borderRadius` prop does

# Acceptance Criteria
- Box component can accept `borderRadius` prop and the `border-radius` css will update accordingly
- Ability to experiment with `borderRadius` prop in storybook using controls
- Documentation exists in the MDX about the `borderRadius` prop and it's valid values.

**Comment by georgewrmarshall** [comment]
@Akatori-Design any thoughts on whether we should restrict the `borderRadius` values to a certain few? e.g. `0, 4px, 8px, 50%` might be easier to not limit it...

**Comment by Akatori-Design** [comment]
Are you talking about the borderRadius tokens or the box component? If tokens, we can start by limiting to the options that we'll definitely need first, then we can add more as needed.

**Comment by georgewrmarshall** [comment]
Yup, the box component can limit the developer to a set of props so it's not used in correctly e.g. `6px` border radius or something like that. I'll set it to the above options to start with.

**Comment by georgewrmarshall** [comment]
This already exists turns out
