### ISSUE TITLE
Implement basic changes needed to run extension with Chrome Extension Version 3 - MV3

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#13794]
Implement the changes required to run extension with google chrome version MV3. This will include:

1. replacing background pages with service worker
2. changes in manifest.json

As a result of this excercise we will know how far is our current implementation compatible with MV3 and we should know exactly what more changes are needed to be able to support MV3 better.

**Comment by jpuri** [comment]
List of tasks I think we need to implement to migrate over to MV3:

[] changes in build to add service worker file to final build
[] fix live-reloading in chrome
[] refactor use of deprecated methods
[] do all changes needed in manifest.json
[] test how service worker shutting down in 5 mins effect extension and found work around for it
[] test use of iframe in MV3 - snaps, trezor and do required fixes

**Comment by jpuri** [comment]
![Screenshot 2022-03-04 at 11 40 27 PM](https://user-images.githubusercontent.com/2182307/156818709-e1c32009-2b88-447f-9b7b-0a996656a993.png)

**Comment by refi93** [comment]
regarding this comment in a related issue: https://github.com/MetaMask/metamask-extension/issues/6059#issuecomment-875747458 - how do you plan to store the password and keep the whole "metamask session" in the background? In Manifest V3 background scripts which provided a convenient way to store secrets in-memory are no longer available. Service workers are kind-of supposed to replace them but AFAIK they die after ~5 minutes: https://bugs.chromium.org/p/chromium/issues/detail?id=1152255

**Comment by rekmarks** [comment]
@refi93 Chrome is shipping a ~persistent in-memory storage API (`chrome.storage.session`) with [the following characteristics](https://bugs.chromium.org/p/chromium/issues/detail?id=1185226#c49) implemented in [this commit](https://chromium.googlesource.com/chromium/src/+/088b034da6072abc866fdb4ca0369c36db278563%5E%21/#F2). That's what we (and other extensions with secrets like password managers etc.) will use for secret storage during a browser session.

**Comment by adonesky1** [comment]
> All of the actions in test-app work as before

Really? Would this be blocked by https://github.com/MetaMask/metamask-extension/issues/13972?

**Comment by jpuri** [comment]
> > All of the actions in test-app work as before
> 
> Really? Would this be blocked by #13972?

Yep you are right these are broken, I did some testing using service worker but not updating version of extension to 3 and that is when it worked well. I will update my findings above. But yep if we can fix the provider thing other actions I expect will work well.

**Comment by jpuri** [comment]
Closing this issue as it is complete we will use the findings in following issue and implementing MV3.
