### ISSUE TITLE
[Bug]: Extension window doesn't open when account is locked

### ISSUE THREAD

**Issue by shoom3301** [MetaMask/metamask-extension#13811]
### Describe the bug

When Metamask account is locked and we try to request accounts, then Metamask extension window doesn't open.
Reproduces only with app.1inch.io domain.

To exclude the influence of the application code, you can simply open a tab with any of the links:
https://staging-app.1inch.io/assets/embedded-mode/index.html
https://app.1inch.io/assets/images/1inch.png
And just run code in the browser console:
window.ethereum.request({ method: 'eth_requestAccounts' })

If you try to do it on google.com domain, the extension window will open.

### Steps to reproduce

1. Lock Metamask account
2. Open tab https://app.1inch.io/assets/images/1inch.png
3. Run in the browser console: window.ethereum.request({ method: 'eth_requestAccounts' })

Expected:
Metamask extension window opens

Actual:
The Metamask extension icon only displays a request indicator

### Version

10.10.1

### Browser

Chrome

### Operating system

MacOS

### Additional context

https://user-images.githubusercontent.com/7122625/156364362-9011dc97-27f9-4d71-8d1c-901149c549d5.mov

**Comment by kevinghim** [comment]
Related to  #[#13590](https://github.com/MetaMask/metamask-extension/issues/13590) Follow that issue for resolution.
