### ISSUE TITLE
Terms & Conditions Agree Button Does Not Activate on Some TVs

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1383]
Reported by `jalt` in our slack.

They write:
`ok i solved this.  its about screen resolution or something.  I have a 27" and a 39" or something the latter being a TV monitor.  I JUST realized if i try to use my pluggins on chrome on my TV monitor the mouse pointer doesn't "sync" properly and the controls on the pluggin don't work, or rather they are way off sync.

All I did was move the browser to my smaller screen and it worked the first time and so did the scroll bar.`

Hoping they come back and suggest any specific monitor brand & system OS for reproducing this.

**Comment by JackTyler4444** [comment]
An Acer monitor with an Insignia TV.  I think the resolutions are both 1920 x 1080.  The key here I think is the setting in "Customize your display" for "Change the size of text, apps, and other items:"  I had it at 150% for my TV and when I put it to default/0 then the extensions are synced properly in relation to the mouse point/clicking.

**Comment by tmashuang** [comment]
Closing in favor of #2767. A workaround has been added by changing a chrome setting in the thread.
