### ISSUE TITLE
Please help me use vault-Decryptor because my wallet is blank

### ISSUE THREAD

**Issue by Jiaozishen** [MetaMask/metamask-extension#13852]
### Describe the bug

Please tell me where is the seed file of the wallet? I use Firefox and my wallet is blank when I click in. I need support
![image](https://user-images.githubusercontent.com/101066444/156979595-10f91b71-7868-43b9-b159-37068e059ada.png)
https://github.com/MetaMask/vault-decryptor,I want to use vault-Decryptor,Since the wallet is still stored on my local computer, does anyone know where the firefox wallet seed file is? Please help me ！！！！

### Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/101066444/156979892-4312bab3-b870-49e0-82ff-2577a387c4ea.png)

### Version

10.10.2

### Browser

Firefox

### Operating system

Windows

**Comment by danjm** [comment]
See convo here https://github.com/MetaMask/metamask-extension/issues/13850
