### ISSUE TITLE
Create a new screen/page "Add network" - Metrics - Follow up

### ISSUE THREAD

**Issue by EHaracic** [MetaMask/metamask-extension#13887]
### **User Story**
Implement a metrics mechanism on adding a new network options. 
 We need to update the Custom Network Added  event to include a source (string) property, which possible values will be “dApp" , “popular_network_list” and “custom_network_form”.

### Figma/Notion links

Figma: https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1697%3A17291
Notion: https://www.notion.so/I-want-to-be-able-to-add-a-popular-custom-network-from-the-custom-network-switcher-modal-7f8c0ae131ea443694396bbf1a36aa1e

### Acceptance criteria
As follow up metrics implementation update to issue: https://github.com/metamask/metamask-extension/issues/12898
1. Update the Custom Network Added  event to include 2 new possible values to the source (string) property: “popular_network_list” and “custom_network_form”.

- "dApp" already exists and should be used when the network was added after a dApp prompt the user to do so (e.g. [chainlist.org](http://chainlist.org/)).
- "popular_network_list" needs to be implemented and should be used when the user adds a network by using this new feature we’re now launching.
- "custom_network_form" needs to be implemented and should be used when the user adds a network by filling the add a network form.

2. The "Custom Network Added" event should be fired every time with the value for the "chain_id" property being the chain id for the network being added in hex. 

### Notes
- Metrics table is on the notion: https://www.notion.so/d5110e916f9f462cb1f3b271201eb073?v=0f4e996154a245e1afb8b279c61a68b5, screenshot below.
![image](https://user-images.githubusercontent.com/49436614/157434122-17af42a6-6806-4d03-ba86-d04bc4c7e6cf.png)

**Comment by bschorchit** [comment]
Hey @dragana8, just flagging to you that this ticket has now been unblocked as this PR: https://github.com/metamask/metamask-extension/issues/12903 has been merged.

**Comment by dragana8** [comment]
@bschorchit do you want someone to pick this up now? Or it can be picked up as soon as someone is available?

**Comment by bschorchit** [comment]
It can be picked when someone is available, @dragana8

**Comment by bschorchit** [comment]
@danjm should the PS team work on this when they have capacity or is someone else working on this? 
Just asking because you mentioned on Friday that you would maybe try to squeeze this in the next release so I just want to confirm if this should be in PS team backlog or not.
