### ISSUE TITLE
[Bug]: ERC20 balance displayed in Metamask has 18 leading zeros

### ISSUE THREAD

**Issue by marinojoey** [MetaMask/metamask-extension#13913]
### Describe the bug

When I import my custom token into metamask, the balance is reported as -1 x 10^18 when it should be 1. 
This is a Rinkeby ERC20. Etherscan reports the correct balance.

### Steps to reproduce

1. call the register function on https://rinkeby.etherscan.io/address/0x35E49d902301A1e9D081aFa6b404101cD37F6c8d#readProxyContract
2. import the custom token into metamask

### Version

10.10.2

### Browser

Chrome

### Operating system

MacOS

### Additional context

In my local environment it passes a pretty solid suite of tests that check for this, among other things.

**Comment by AlexJupiter** [comment]
Hi @marinojoey, thanks for the report, would you be able to provide a screenshot please?

**Comment by bschorchit** [comment]
Hey @marinojoey is this your transaction you sent to test it? If yes, it also shows 17 leading zeros for the amount of tokens transacted: https://rinkeby.etherscan.io/tx/0x730ad5b94a4bc329fa0ce87d5cb3c002b9b29d766672b1ef5fe22e342c0b9825
