### ISSUE TITLE
[Bug]: Transaction Popup Disapear But Request is not responded too

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#13929]
### Describe the bug

- app send a transaction request
- Metamask display the popup
- User approve
- app send a transaction request
- Metamask display the popup
- then at that point, the first transaction is confirmed, 
- Metmask notify the user 
- But it also close the current popup without responding to the app request

The app keep waiting for it without being able to know if it will ever be back

### Steps to reproduce

1. send a transaction request
2. approve it
3.  send a transaction request before the first get confirmed
4. keep the metamask popup open
5. when the first transaction is confirmed the popup is closed without any user recourse possible

### Version

10.10.2

### Browser

Chrome

### Operating system

Linux

**Comment by AlexJupiter** [comment]
@wighawag we just tried to reproduce this and we didn't encounter the same problem, would you be able to provide more information please? Perhaps a screen recording? Many thanks

**Comment by wighawag** [comment]
@AlexJupiter 
made a quick video : https://youtu.be/-kJMe8sClaY

Basically I 
- perform a tx
- confirm via Metamask
- once tx is broadcasted, I go make another tx
- this time I wait
- And as you can see in the video as soon as the confirmation notifcation comes up, the metamask popup is closed without any user intervention
- And worst, the application is not being given knowledge of that, so my app keeps waiting

**Comment by AlexJupiter** [comment]
@kevinghim @bschorchit we might want to take a closer look at this.

**Comment by evgeniy-bond** [comment]
@AlexJupiter any updates? We have the same problem.

**Comment by AlexJupiter** [comment]
@bschorchit any thoughts here at all? Perhaps it aligns with your transaction work.

**Comment by Nana12345678910** [comment]
[](https://coinapp.co/pdfs/SentinelX_NFC_User_Guide_07012021_Compressed.pdf)
