### ISSUE TITLE
[Bug]: Transaction Popup Remains Active but the app received an error

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#13928]
### Describe the bug

Perform a transaction request from an app

Metamask show a popup and we see Metamask calculating gasPrice

But then it respond to the app request with an error
`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"Internal JSON-RPC error.","code":-32603}}}'`

The transaction popup remains though

We can see that metamask failed to find a valid gasPrice, but we can manually set them up and confirm the transaction then

The issue thogh is that now the app cannot now about it as it failed earlier with the error response

### Steps to reproduce

1. make a transaction request and wait for a response
2. repeat until the response is the error above and see that the metamask popup is still open

### Error messages or log output

```shell
`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"Internal JSON-RPC error.","code":-32603}}}'`
```

### Version

10.10.2

### Browser

Chrome

### Operating system

Linux

**Comment by BelfordZ** [comment]
todo: needs exact code for reproduction
