### ISSUE TITLE
Snaps settings is not covered by settings search

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#13943]
The settings search feature introduced in #13214 does not cover the Snaps settings page.

**Comment by EHaracic** [comment]
The flask builds are documented here: 
https://github.com/MetaMask/metamask-extension/blob/develop/development/build/README.md

**Comment by danjm** [comment]
Apologies @EHaracic @amerkadicE, this was picked up and resolved by someone else https://github.com/MetaMask/metamask-extension/pull/14100
