### ISSUE TITLE
Add token list to token details page

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#13952]
Add the token list/aggregator to the token details page.

<img width="285" alt="Screen Shot 2022-03-14 at 10 15 19 PM" src="https://user-images.githubusercontent.com/43930900/158292409-205bd0ea-e1fe-48bc-879b-8e3eb4c40e32.png">

**Comment by popeda97** [comment]
> Add the token list/aggregator to the token details page.
> 
> <img alt="Screen Shot 2022-03-14 at 10 15 19 PM" width="285" src="https://user-images.githubusercontent.com/43930900/158292409-205bd0ea-e1fe-48bc-879b-8e3eb4c40e32.png">
