### ISSUE TITLE
[Bug]: I lost my wallet and I want to get him back

### ISSUE THREAD

**Issue by ZZS2017** [MetaMask/metamask-extension#13958]
### Describe the bug

My browser didn't work, then I restarted the browser, after the restart my metamask became the initial state, and then I clicked on new wallet. Now I can't find my old wallet, I haven't backed up the mnemonic phrase, I have tried to use the ldb file to restore my wallet, but the mnemonic phrase obtained is the mnemonic phrase of my newly created wallet, before Where does the ldb file exist? i want to get my wallet back

### Steps to reproduce

My browser didn't work, then I restarted the browser, after the restart my metamask became the initial state, and then I clicked on new wallet. Now I can't find my old wallet, I haven't backed up the mnemonic phrase, I have tried to use the ldb file to restore my wallet, but the mnemonic phrase obtained is the mnemonic phrase of my newly created wallet, before Where does the ldb file exist? i want to get my wallet back

### Version

10.11.0

### Browser

Chrome

### Operating system

Windows

**Comment by AlexJupiter** [comment]
Hi @ZZS2017 really sorry to hear about your problem here however that's not something we can help with her in GitHub. My recommendation is to get in touch with our official support here: https://metamask.zendesk.com/
