### ISSUE TITLE
MV3: fix injecting provider into DAPP

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#13972]
Connecting extension from DAPP fails with this error in MV3

![Screenshot 2022-03-14 at 11 53 59 AM](https://user-images.githubusercontent.com/2182307/158116656-e6a41c2b-86c3-4e75-bd75-739918552e19.png)

We need to find an appropriate solution for it and fix the issue. Solution may be:
1. appropriate change in manifest.json may fix the issue
2. we replace inline script injection with a file in src of script tag

**Comment by jpuri** [comment]
Issue is fixed in PR https://github.com/MetaMask/metamask-extension/pull/14396

**Comment by mib-hashflow** [comment]
It seems like the fix never got rolled out? Can you confirm this is fixed?

**Comment by jpuri** [comment]
Yes this fix is there in the latest code.
