### ISSUE TITLE
Consolidate permission design, icons, and copy

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#13995]
Snaps' permissions are displayed in our (1) install flow, (2) update flow, and (3) settings view. We need these to be coherent across these contexts and make sense both together & stand-alone.

**Current permissions**
The list of permissions available for Snaps right now is [here](https://github.com/MetaMask/metamask-extension/blob/8b9b9af13fabcef4882d4423e35acb4cd3aef4e9/ui/helpers/utils/permission.js).

**To-do**
- overview current permissions' copy and icons
- suggest design permission component to work cross-contexts
- suggest consolidated list of copy & icons

**Comment by rekmarks** [comment]
We may skip icons entirely, @eriknson is iterating.

**Comment by eriknson** [comment]
[Current figma](https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=1602%3A31332&t=AONK3369gmisFv40-1) with suggested permissions design.

**Comment by Montoya** [comment]
Will ask DS team if they can build a permissions component

**Comment by eriknson** [comment]
[Permissions in context](https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-features?node-id=163%3A25270&t=qZcHREmgMMkKrVyg-1), ready for review

**Comment by Montoya** [comment]
This is great.

**Comment by holantonela** [comment]
amazing work @eriknson!
