### ISSUE TITLE
sends massive amount of gas for function that would throw!

### ISSUE THREAD

**Issue by SCBuergel** [MetaMask/metamask-extension#1400]
Metamask just pointlessly cost me [$7 worth of gas](https://etherscan.io/tx/0x9c39a30efb5072e31cc6792a97080c0964900218b3c9d7d27949f7962520da9a) and I would not want others to blindly support the mining industry in the same way. This is fully my fault because I did not properly review the popup before clicking `confirm` but this could be handled better from Metamask as well to prevent this from happening.

Metamask seems to do a gas estimation and enter the required amount of gas. This is usually great but in case a function `throw`s it seems to insert the blockGasLimit amount of gas. That tx then sits around for a while until the block gas limit is raised sufficiently (in my case of the tx above it took about 30 minutes) and then a miner is happily including the tx in a block. This should not happen.

In case metamask expects a `throw`, it should not put the maximal (blockGasLimit) amount of gas but display a warning or - insert some default amount of gas, maybe 100k.

**Comment by kumavis** [comment]
@SCBuergel sorry that happened. its difficult to determine a throw via `eth_call`. We may need to move the tx simulation to the frontend for richer information.

**Comment by SCBuergel** [comment]
I think this is related: https://github.com/MetaMask/metamask-plugin/issues/1258
Anything that is over 500k gas should raise some alarm bells. In the rare cases that this is actually wanted the user knows what to do - likely an advanced user running a hellishly complex contract. But it would protect the 98% of us IMO.

**Comment by kumavis** [comment]
have to also consider contract deploys, which can cost a lot

> I think this is related: #1258

that refers to `gasPrice` not `gasLimit`, but the soft stop-gap is a good idea

> But it would protect the 98% of us IMO.

yeah, very true

**Comment by Zanibas** [comment]
Let's wrap this alongside the UI refactor

**Comment by kumavis** [comment]
We have a warning when throws are detected now
