### ISSUE TITLE
[Bug]: Onboarding V2 - Changing Language does not cause any effect

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14039]
### Describe the bug

**Problem**: on the onboarding v2 page, when I change the language nothing happens.

https://user-images.githubusercontent.com/54408225/158996783-7e71c3dc-1c6e-472d-b3d3-3d533ab431b7.mp4

### Steps to reproduce

1. Land on the Onboarding V2 page
2. Change language

### Version

V10.11.1

### Browser

Firefox

### Operating system

Linux

**Comment by bschorchit** [comment]
I think the language dropdown might not be working because we don't have translations for this flow merged still. I investigated it in crowdin and it seems that for PT(br) is still in proofreading phase. 

Tagging @hilvmason here to follow up on getting translations unblocked for this.

**Comment by darkwing** [comment]
This wasn't a bug -- this was a reflection that we didn't have any translation for the new strings.
