### ISSUE TITLE
Add loading state for balance display on main screen

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#14040]

**Comment by suchat932** [comment]
ต้องการให้แปลภาษาได้ขณะใช้งาน

**Comment by bschorchit** [comment]
Sharing [this design](https://www.figma.com/file/UniC0neIae4IxKENQMVdEg/Balance-switching-networks?node-id=0%3A1) for review. Does the copy correctly address what is happening in the background? @danjm @EHaracic 
![Screen Shot 2022-03-22 at 11 52 19](https://user-images.githubusercontent.com/34968356/159510517-3b8d8e8d-ed52-4d65-a77f-044183c4654c.png)

**Comment by bschorchit** [comment]
[Design update](https://www.figma.com/file/UniC0neIae4IxKENQMVdEg/Balance-switching-networks) from @SaraCheikh <3
@EHaracic

**Comment by SaraCheikh** [comment]
@EHaracic  please, note that I used a new loading spinner to illustrate the loading state because the one we are using currently in the product does not exist in design. For the build you can go with the one we are using in the rest of the product for consistency :)

**Comment by EHaracic** [comment]
@SaraCheikh @bschorchit 

Is is not clear should we use the info tooltip? On the Figma design there is no tooltip but on the previous design  there is (screenshots below) 

https://user-images.githubusercontent.com/34968356/159510517-3b8d8e8d-ed52-4d65-a77f-044183c4654c.png
![image](https://user-images.githubusercontent.com/49436614/168994940-c1752e86-0acc-4c5c-bb61-e1968b10565f.png)

**Comment by SaraCheikh** [comment]
The loading spinner would replace the balance and the info icon in this updated design, so there wouldn't be a tooltip @EHaracic

**Comment by VSaric** [comment]
Closed by: #14354
