### ISSUE TITLE
MV3: is extension service worker becomes inactive - it stops responsing

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#14049]
If service worker becomes in-active it is not possible to bring it back to life and have UI re-loaded. It requires re-installing extension for it to work again.

We need to debug this more and fix it. I found that service worker did not became inactive if extension UI was open but we need to test this also by keeping UI open for long period of time.

**Comment by adonesky1** [comment]
I'm seeing some interesting (and encouraging behavior) on the `mv3` branch. I'm seeing a new service worker spawn when one dies, with no interruption to the extension. Perhaps we can look together.
