### ISSUE TITLE
gas amount too high via remix

### ISSUE THREAD

**Issue by SCBuergel** [MetaMask/metamask-extension#1405]
I am deploying the following contract via Remix to the main net (via injected Metamask web3) and then interacting also via Remix:
```
pragma solidity ^0.4.8;

contract Bounty2 {
    mapping(bytes32 => bool) public validCode;
    
    address public owner;
    uint public myBalance;
    uint public numBeneficiaries;
    
    function Bounty2(uint _numBeneficiaries) {
        owner = msg.sender;
        numBeneficiaries = _numBeneficiaries;
    }
    
    function () payable {
        myBalance += msg.value;
    }
    
    modifier onlyOwner() {
        if (msg.sender != owner)
            throw;
        _;
    }
    
    function addCode(bytes32 code) onlyOwner {
        validCode[code] = true;
    }
    
    function codeValid(string plaintextCode) constant returns (bool) {
        return validCode[sha3(plaintextCode)];
    }
    
    function requestPayout(string plaintextCode) {
        if (validCode[sha3(plaintextCode)])
            msg.sender.send(myBalance / numBeneficiaries);
        else
            throw;
        validCode[sha3(plaintextCode)] = false;
    }
}
```

e.g. for the function call to `addCode` which executes correctly Metamask inserts the blockGasLimit amount of gas. This despite the fact that the function does not throw - that Is why I am submitting this as a new issue and not as a comment on https://github.com/MetaMask/metamask-plugin/issues/1400.

**Comment by kumavis** [comment]
@SCBuergel can you provide some example data for the addCode field formatted as remix wants it

**Comment by SCBuergel** [comment]
Sure: Try `"0x9c22ff5f21f0b81b113e63f7db6da94fedef11b2119b4088b89664fb9a3cb658"`
NB1: include the " quotes
NB2: the contract is deployed at 0xb96e6185eBE5D83ee2cCE9502c8f717C35591276 but you wont be able to test the `addCode` function since your address wont match the `onlyOwner` modifier.

**Comment by kumavis** [comment]
I can see that the gasLimit is specified by remix, not sure where it derives this value.
On rinkeby i saw it suggested `0x47d5ca` (4707786) which is 99.9% of the seemingly constant rinkeby block gas limit. that is dangerous for networks like mainnet where the gasLimit constantly fluxuates.

actual gas usage was 44347, so they are not really providing an accurate number. metamask will provide sane defaults if they skip their specified gas value

**Comment by kumavis** [comment]
that said, metamask should warn about how high this gasLimit is

**Comment by SCBuergel** [comment]
Ok good to know, I am missing sufficient insights into Remix to file an issue - maybe you could report this as an issue to them?

**Comment by SCBuergel** [comment]
Just to continue tracking this issue on the Remix side, [here](https://github.com/ethereum/remix/issues/506) is the issue.

**Comment by Zanibas** [comment]
This is fixed on our side. Finally got the time to check it. Reopen if this actually isn't the case.
