### ISSUE TITLE
Warnings for gasPrice and gasLimit

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#1411]
Encompasses discussion for #1400, #1209, #1408, some of #1407, #1405.

Centralized discussion to address these design points:

- Should we warn users of abnormal gas prices and limits? (I think we're in agreement here)
- How do we determine the threshold when we should show a warning? Applies to both price and limit.
- How should we display the warning? A separate confirmation page? A modal? Wait until our UI overhaul?
- Should users be able to disable these warnings?

**Comment by flyswatter** [comment]
I think we should list out the possible types of warnings, and then have a designer take a pass at them.

The warnings I'm aware of here:

- A very high gas limit that may be expensive
- A block-limit sized gas limit that may be an out of gas error.
- A gas price that is 30+ is "unusually high, and should be reserved for urgent transactions."
- A gas price that is < 20 Gwei "May take a few minutes to confirm".

Eventually these should also be based on live stats (eventually).

Also I'd like to mention that some of the bugs (#1408 and #1407) are not mere warning issues, these are bugs where the value is edited but not submitted with the TX, and those issues are higher priority.

**Comment by flyswatter** [comment]
Closing for smaller issues, since we've already done some of this, so we can propose specific changes.
