### ISSUE TITLE
[Bug]: Token amounts missing number formatting (000's commas)

### ISSUE THREAD

**Issue by worldlyjohn** [MetaMask/metamask-extension#14123]
### Describe the bug

Token amounts can be hard to read without number formatting.  The UI also chooses to use the CSS "..." instead of rounding to the nearest digit.

here are some examples:
| Type | Current Format | Better Format |
| --- | --- | ----------- |
| Comma separator, improve readability | 3523535 | 3,523,535  |
| Rounding | 1100.984587... | 1100.98459  |
| Precision, do we need more than 3 dec? | 1035.123456789... | 1035.123  |

### Steps to reproduce

1. Find a wallet with a token amount of >1000 units (or 1M units to hit the point home)
2. Observe lack of comma separator, rounding, etc as described above

### Version

10.11.1

### Browser

Chrome

### Operating system

MacOS

**Comment by worldlyjohn** [comment]
source file: https://github.com/archana-s/metamask-extension/blob/1257d8b72576767a007ab1f7434e274d86f8b0ef/ui/components/app/asset-list-item/asset-list-item.js#L115

When `primary` var (the token value number) is passed in, you should be able to create a computed method that converts this to a number.  Why not use JS [Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)?

You might be able to do something like the following (assumes no more than 3 decimals are required which seems directionally right):
```
primaryFormatted = 
Number(primary).toLocaleString(undefined, { maximumFractionDigits: 3 });
```

**Comment by bschorchit** [comment]
Closing this in favor of https://github.com/MetaMask/metamask-extension/issues/9024

Ps: This has also been added to the [papercuts epic on Notion](https://www.notion.so/Reduce-Papercuts-with-UX-Improvements-Q2-22-df8684b137e7445095c3b56f0af2f80e)
