### ISSUE TITLE
Please allow gasPrice values below 2GWei

### ISSUE THREAD

**Issue by alex-miller-0** [MetaMask/metamask-extension#1413]
I have sent several txns with <0.2GWei gas price in previous versions and am happy to wait longer for my txn to be mined. The 2GWei value is a minimum SAFE gas price, but it is certainly possible to use lower values.

I personally don't think there should be a lower limit at all, but I would at least like it to be something 1-2 orders of magnitude lower than 2GWei. 

Paying 2GWei makes me angry >:0

**Comment by flyswatter** [comment]
I respect that, and I think we can add this.  Fairly related to #1411, which is related to adding visual warnings related to gas for users.

The UX of gas is a difficult thing, I'm really glad EthGasStation is making gas UX a specialty, there's a lot of room for that.

The hard limit on 2 Gwei for right now is absolutely to help shore up an onslaught of users we've had who have submitted transactions that never get mined, getting their accounts into states that we don't have automated ways of fixing (yet).

I think we could easily reduce it to 1 Gwei in the short term, then get our hex-bn-input component tolerant of decimals somehow, maybe passing it a precision level, and then we can lower our limit even more once we have visual warnings for users who don't know the implications of what they're doing.

**Comment by A2be** [comment]
From a UX point of view, you might have a 2 GWei or 1 Gwei default lower limit, so as not to adversely impact the onslaught of new low-Ethereum-info users you expect, while still having an advanced option behind a menu pull down or something to facilitate the sort of transactions @alex-miller-0 is looking for.

**Comment by thisbejim** [comment]
SafeLow on [EthGasStation](http://ethgasstation.info/index.php) is 0.6 Gwei as of today, forcing a 2 Gwei lower limit is over paying by a lot at this point.

**Comment by Zanibas** [comment]
Closed by #1796
