### ISSUE TITLE
[Bug]: Transaction shows as confirmed in MetaMask but is still pending on Etherscan 

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-extension#14177]
### Describe the bug

I minted an NFT during a gas war and the transaction showed as being confirmed in MetaMask within about 10 seconds but on Etherscan it still showed as pending. It remained pending on Etherscan for about a minute. During this time, I was not able to speed up the transaction. 

### Steps to reproduce

1. Start a transaction (in this case, contract interaction)
2. Wait until receiving the "transaction confirmed" notification
3. Click the notification to open the transaction on Etherscan
4. Observe that transaction is still pending
5. Open extension window
6. Observe that transaction shows as confirmed and cannot be sped up or canceled 

### Error messages or log output

None

### Version

10.11.3

### Build type

No response

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

None

### Additional context

Here's a screenshot of the issue in action.
![image](https://user-images.githubusercontent.com/19909/159829877-7cf39a5d-4dac-445b-90d8-850a425e4cc1.png)

**Comment by digiwand** [comment]
Related to: https://github.com/MetaMask/metamask-extension/issues/12093
