### ISSUE TITLE
MV3: fix ledger keyring issue

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#14183]
Starting extension in MV3, this error can be seen in console:
<img width="564" alt="Screenshot 2022-03-24 at 10 21 31 AM" src="https://user-images.githubusercontent.com/2182307/159845964-8db3bacd-2abf-425a-a572-5d10282e848f.png">

This needs to be fixed.

An option to fix it could be using content script or move functionality to UI.

**Comment by danjm** [comment]
This was fixed by https://github.com/MetaMask/metamask-extension/pull/17354
