### ISSUE TITLE
MV3: remove use of deprecated MV2 methods [Deprecated]

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#14182]
Deprecated MV2 methods will no longer be supported in MV3. Remove occurrences of any such method in the codebase.

Reference: https://www.notion.so/Chrome-Extension-Version-MV3-Migration-19063a3ee9af46c48f18bf8e8f7aa546

This needs to be checked in all relevant MetaMask repos.

There are a number of APIs that have long been deprecated. Manifest V3 finally removes support for these deprecated APIs. 

**These include:**
- chrome.extension.sendRequest()
- chrome.extension.onRequest
- chrome.extension.onRequestExternal
- chrome.extension.lastError
- chrome.extension.getURL()
- chrome.extension.getExtensionTabs()
- chrome.tabs.Tab.selected
- chrome.tabs.sendRequest() 
- chrome.tabs.getSelected()
- chrome.tabs.getAllInWindow()
- chrome.tabs.onSelectionChanged
- chrome.tabs.onActiveChanged
- chrome.tabs.onHighlightChanged

https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#sunset-deprecated-apis

## Research and Audit

Researched by: @digiwand 

| Status | Method |Notes | Instances |  
| :---  | --- | --- | --- |
| ✅ | chrome.extension.sendRequest() | We should be okay because `chrome.extension.sendRequest` was deprecated in Chrome 58 and replaced by `chrome.runtime.sendRequest`. `chrome.runtime.sendRequest` appears to still work with MV3. Please refer to the extension docs below. <br><br>  See: <br> - https://developer.chrome.com/docs/extensions/reference/extension/#method-sendRequest <br> - https://developer.chrome.com/docs/extensions/reference/runtime/#method-sendRequest| I have not yet checked for `chrome.runtime.sendRequest` |
| ✅ | chrome.extension.onRequest | never supported by FireFox | | 
| ✅ | chrome.extension.onRequestExternal |  never supported by FireFox | | 
| ✅ | chrome.extension.lastError | We should be okay because `chrome.extension.lastError` was deprecated in Chrome 58 and replaced by `chrome.runtime.lastError`. `chrome.runtime.lastError` appears to still work with MV3. Please refer to the extension docs below. <br><br>  See: <br> - https://developer.chrome.com/docs/extensions/reference/extension/#property-lastError <br> - https://developer.chrome.com/docs/extensions/reference/runtime/#property-lastError | `browser.runtime.lastError` instances: <br>- `metamask-extension/app/scripts/detect-multiple-instances.js`<br>- `metamask-extension/node_modules/u2f-api/lib/google-u2f-api.js` <br> - `app/scripts/lib/local-store.js` <br> - `metamask-extension/app/scripts/lib/util.js`| 
| ✅  | chrome.extension.getURL() | We should be okay because `chrome.extension.getURL` was deprecated in Chrome 58 and replaced by `chrome.runtime.getURL`. `chrome.runtime.getURL` appears to still work with MV3. Please refer to the extension docs below. <br><br>  See: <br> - https://developer.chrome.com/docs/extensions/reference/extension/#method-getURL <br> - https://developer.chrome.com/docs/extensions/reference/runtime/#method-getURL <br>- https://bugs.chromium.org/p/chromium/issues/detail?id=528220 | `browser.runtime.getURL` instances: <br>- `metamask-extension/app/scripts/contentscript.js` <br>- `metamask-extension/app/scripts/platforms/extension.js`| 
| ✅  | chrome.extension.getExtensionTabs() | not found |
| ✅  | chrome.tabs.Tab.selected | not found |
| ✅  | chrome.tabs.sendRequest()  |  never supported by FireFox |
| ✅ | chrome.tabs.getSelected() |  never supported by FireFox  |
| ✅ | chrome.tabs.getAllInWindow() |  never supported by FireFox  |
| ✅  | chrome.tabs.onSelectionChanged | never supported by FireFox  |
| ✅ | chrome.tabs.onActiveChanged |  never supported by FireFox |
| ✅ | chrome.tabs.onHighlightChanged | not found |

The following methods are currently linted by our `addons-linter` npm package. They also appear to not be support by FireFox so they should be safe to remove. I have double-checked that there are no use-cases for these methods. See `metamask-extension/node_modules/addons-linter/dist/addons-linter.js` (file is subject to change) - Ariella
- extension.onRequest
- extension.onRequestExternal
- extension.sendRequest
- tabs.getAllInWindow
- tabs.getSelected
- tabs.onActiveChanged
- tabs.on selection changed
- tabs.sendRequest

I verified the polyfill library we are using, [mozilla/webextension-polyfill](https://sourcegraph.com/github.com/mozilla/webextension-polyfill), does not contain `[XYZ].extension`. It is using `[XYZ].runtime`. Shoutout to @adonesky1 for deprecating `extensionizer` for `webextension-polyfill` in preparation for MV3 a few months ago https://github.com/MetaMask/metamask-extension/pull/13960 ! 🥳 🎉

**Comment by digiwand** [comment]
I audited each method on the list and found no instances of these deprecated methods in our codebase or its node modules. For more information, please refer to the table in the description above. Should be no need for changes here.

**Comment by digiwand** [comment]
I audited each method on the list and found no instances of these deprecated methods in our `metamask-extension` codebase or its node modules. I also found no "extension.[xyz]" and "tabs.[xyz]" instances across all of our [MetaMask git codebases](https://github.com/MetaMask/). For more information, please refer to the table in the description above. Should be no need for changes here.

**Comment by darkwing** [comment]
I did a search for each of the se the other day and definitely saw some; for example, `lastError` is still used:

https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/util.js#L106

**Comment by digiwand** [comment]
@darkwing I have seen these cases you have mentioned and I have seen the [getURL instance found here](https://www.notion.so/Chrome-Extension-Version-MV3-Migration-19063a3ee9af46c48f18bf8e8f7aa546#96fbced9988244bab750f8036c1baf13). I thought this was okay because using `xyz.runtime.lastError` instead of `chrome.extension.lastError` has been said to be fine through their developer docs. I will double-check today to make sure we aren't getting any deprecation warnings and that our current use case does not call `chrome.extension.lastError`. 

In case anyone misses it since it's likely hidden on the table without scrolling, I have also listed incidences of `extensions.[method]` in the fourth column. 

Thanks for having an eye on this too 😊🙏

**Comment by digiwand** [comment]
Verified there should be no need for changes. Left an update in the description above 🙂 We clear to close this issue
