### ISSUE TITLE
[Bug]: Swaps page triggers a bunch of API console errors saying "invalid for property symbol"

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14243]
### Describe the bug

**Problem**: when I go to Swap page, I get an API error for each token on the console, saying `response to GET https://api2.metaswap.codefi.network/networks/1/tokens invalid for property symbol; value was: NAME_OF_TOKEN | type was:  string`
![image](https://user-images.githubusercontent.com/54408225/160593883-0473b9cd-43cb-419c-8bb2-7d2deec95124.png)

### Steps to reproduce

1. Unlock Metamask
2. Select Mainnet Network
3. Open the console
4. Click on Swap

### Error messages or log output

```shell
response to GET https://api2.metaswap.codefi.network/networks/1/tokens invalid for property symbol; value was: NAME_OF_TOKEN | type was:  string
```

### Version

10.12.0

### Browser

Firefox

### Operating system

Linux

**Comment by seaona** [comment]
@dan437 I'm still seeing the console errors. Has it the code fix been merged?

**Comment by dan437** [comment]
Not yet. In the PR I referred (https://github.com/MetaMask/metamask-extension/pull/11162) it needs to be decided about next steps, because this doesn't influence only Swaps, but other features in MetaMask as well.
