### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by blorange** [MetaMask/metamask-extension#1424]
Started receiving this error in the callback some of our web3 calls, notably `web3.eth.estimateGas()` and `contract.new()`. Haven't changed anything regarding the web3 object.

Estimate gas is working with a very small amount of data ('0xdeadbeef' for example), but when using a larger piece of bytecode I'm seeing this error.

Not sure whether something has changed in either MetaMask or Web3, but logging here in case you guys have any insight.

**Comment by flyswatter** [comment]
Could you check the response of the failed network request (network tab) of the background inspector?

https://github.com/#background-logs-chrome

**Comment by blorange** [comment]
Thanks @flyswatter 

```
POST https://ropsten.infura.io/metamask 500 ()
RpcSource.handleRequest @ background.js:66787
next @ background.js:59865
HookedWalletSubprovider.handleRequest @ background.js:67497
next @ background.js:59865
FilterSubprovider.handleRequest @ background.js:66915
next @ background.js:59865
(anonymous) @ background.js:66565
BlockCacheStrategy.hitCheck @ background.js:66687
BlockCacheProvider._handleRequest @ background.js:66563
(anonymous) @ background.js:66527

ethquery failure Object {method: "eth_estimateGas", params: Array(1)}
method: "eth_estimateGas"
params: Array(1)
  0: Objectdata: "<A very large bytecode string>"
  from: "0x9f3ae1d603320980bd7fd79eb6df981d8a2a0e24"
  gas: "0x249f00"
  gasPrice: "0x4a817c800"
  value: "0x0"

SyntaxError: Unexpected token < in JSON at position 0
background.js:3149 Error in RPC response:
<A (probably not very useful) stacktrace>
 ```

Hopefully that's what you're looking for, can take a screenshot instead if needed

**Comment by Zanibas** [comment]
This error is related to our conversion API usually, but since it's happening in a callback, probably not the case this time.

**Comment by blorange** [comment]
This only appears to be an issue on Ropsten, both Mainnet and Kovan are having no troubles.

**Comment by kumavis** [comment]
This happens when infura is shedding load -- we added a 5x retry in provider engine to reduce the occurrence of this

**Comment by macbem** [comment]
I'm getting this error in my Dapp, using MetaMask, right now. I haven't done any updates and suddenly, it started breaking because of this error. Any update on this, guys?

When I go into fallback mode and inject web3 on my own, using the HttpProvider with Infura mainnet nodes, everything works fine, so this is definitely a problem with MetaMask and/or your Infura node.

**Comment by kumavis** [comment]
@macbem yeah 0x ICO is straining our nodes - in this situation you can always use a ethereum node
