### ISSUE TITLE
[Bug]: Advanced Gas fees Title and Info icon grey colors have turned darker

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14268]
### Describe the bug

**Problem**: "Advance gas fee" title and info icons have changed their grey colour into darker (it's not a huge difference but you can notice it if you compare it with before).
![advanced-gas-fees](https://user-images.githubusercontent.com/54408225/160884499-ec7f8c57-56b2-4284-85b0-06a78ea6f070.png)

**Expected**: before, these grey colours were lighter

![advanced-gas-fees-before](https://user-images.githubusercontent.com/54408225/160884781-cc8b59bb-b5df-48af-86aa-ffcb6d5a596f.png)

### Steps to reproduce

1. Unlock Metamask
2. Click Send
3. Click Edit Fees
4. Go to Advanced Gas Fees

### Version

10.13.0

### Browser

Firefox

### Operating system

Linux

**Comment by georgewrmarshall** [comment]
Yup, that's correct. We've opted for a darker gray where icons can be interactive to improve accessibility for our visually impaired folks.

**Comment by seaona** [comment]
Oh I see, alright I close the issue then. Thank you both @georgewrmarshall @darkwing :)
