### ISSUE TITLE
[Bug]: "Edit priority fee" selected option is marked as a red dot

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14267]
### Describe the bug

**Problem**: "Edit priority fee" selected option is marked as a red dot 
![image](https://user-images.githubusercontent.com/54408225/160849373-7d88c918-7ba0-4bd5-bdc1-2b61b64759e3.png)

**Expected**: selected option is marked as a blue dot
![image](https://user-images.githubusercontent.com/54408225/160849394-3f02f294-181d-4487-8670-5ed140f42fd7.png)

### Steps to reproduce

1. Unlock Metamask
2. Click Send
3. Select Edit Fees

### Version

10.13.0

### Browser

Firefox

### Operating system

Linux

**Comment by georgewrmarshall** [comment]
@seaona on second look at this I think the update color is correct. We use primary colors for user selected colors

**Comment by seaona** [comment]
Alright I close this issue then. Thank you @georgewrmarshall
