### ISSUE TITLE
[Bug]: Reset account not clearing tx history "Receive" entries

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14294]
### Describe the bug

**Problem**: when I click on Reset Account, the transaction history is not cleared and I am still able to see all the "Receive" transactions.

https://user-images.githubusercontent.com/54408225/161031550-208d3964-5e98-48aa-b944-a62046490da8.mp4

### Steps to reproduce

1. Unlock Metamask
2. Send some transactions to Account2
3. Change to Account 2 (see tx Receive are there)
4. Go to Settings / Advanced
5. Click on Reset Account
6. Go to Transaction History

### Error messages or log output

```shell
n/a
```

### Version

10.12.2  10.13.0

### Browser

Firefox

### Operating system

Linux

**Comment by bschorchit** [comment]
Closing as we have updated the settings explanation to communicate that incoming transactions won't be affected by it.

![Screenshot 2023-07-24 at 20 21 49](https://github.com/MetaMask/metamask-extension/assets/34968356/2245ec4d-1524-4b4d-82d5-f3e8f81e52ee)
