### ISSUE TITLE
[Bug]:  Freezes during installation 

### ISSUE THREAD

**Issue by srameshr** [MetaMask/metamask-extension#14291]
### Describe the bug

![Screenshot 2022-03-31 at 8 09 07 AM](https://user-images.githubusercontent.com/8149408/160965316-d65271aa-70bc-4b04-81f8-83c6ec645d46.png)

Metamask extension just freezes here during the installation process and does not let me proceed further. Nothing is clickable on this page. I cant see the video play but just hear it. The next button does not work.

### Steps to reproduce

1. Install for chrome from https://metamask.io/download/
2. Go to "Set up new seed phrase"

### Version

Latest

### Browser

Chrome

### Operating system

MacOS

### Additional context

NA

**Comment by bschorchit** [comment]
@srameshr thank you for submitting this issue! Could provide any additional informatios so the team can attempt to reproduce it?
