### ISSUE TITLE
[Bug]: Message "View Account on Etherscan" even though it's taking me to another Blockchain Explorer

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14311]
### Describe the bug

**Problem**: when hovering the arrow button, on Import Accounts from HW, it appears a message saying "View Account on Etherscan" also for the networks that are not configured with Etherscan as the blockchain explorer.

https://user-images.githubusercontent.com/54408225/161124504-c049cd33-e3f0-4e26-a094-8dc8271a076c.mp4

### Steps to reproduce

1. Unlock Metamask
2. Setup xDai chain
3. Click Import from Hardware Wallet
4. Hover the arrow button
5. Click the arrow button

### Version

10.13.0

### Browser

Firefox

### Operating system

Linux

**Comment by AlexJupiter** [comment]
Thanks for raising this @seaona, adding this to our backlog to work on soon!

**Comment by vivek-consensys** [comment]
Able to replicate this issue. Please see below:

https://github.com/MetaMask/metamask-extension/assets/106310394/426fb309-1d57-4ccb-a907-7bf022c42189
