### ISSUE TITLE
[Bug]:  Password dots almost not visible on Dark Mode for Recovery Phrase

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14328]
### Describe the bug

**Problem**: on the Recovery Phrase screen, while using Dark Mode, the "dots" for the password are almost not visible

https://user-images.githubusercontent.com/54408225/161257230-a8a73156-b5da-4214-a3a8-36a368775924.mp4

**Expected**: something like the Unlock screen, where dots are white contrasting with the dark
![expected-pw](https://user-images.githubusercontent.com/54408225/161257261-595fbcc5-9a34-4ddd-b3e9-5b3dfba27756.png)

### Steps to reproduce

1. Unlock Metamask
2. Go to Settings // Experimental
3. Select Dark Mode
4. Go to Settings // Security
5. Click Recover Security Phrase
6. Unlock using Password

### Version

10.13.0

### Browser

Firefox

### Operating system

Linux

**Comment by GuillaumeRx** [comment]
Fixed in #14305
