### ISSUE TITLE
Clean up e2e fixture data

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14340]
Currently multiple tests are coupled to a single fixture data file. This becomes a problem if we update a fixture data file (e.g. test/e2e/fixtures/imported-account/state.json) multiple tests are affected. At the time of writing the `imported-account` fixture file is used in 10+ different specs.

AC:
- each spec has its own fixture data
- fixture data is stripped down and only consists of data need for the test

**Comment by JessePinkman48** [comment]
> Currently multiple tests are coupled to a single fixture data file. This becomes a problem if we update a fixture data file (e.g. test/e2e/fixtures/imported-account/state.json) multiple tests are affected. At the time of writing the `imported-account` fixture file is used in 10+ different specs.
> 
> AC:
> 
> * each spec has its own fixture data
> * fixture data is stripped down and only consists of data need for the test

**Comment by Gudahtt** [comment]
This comment is related: https://github.com/MetaMask/metamask-extension/issues/10694#issuecomment-1087915390
