### ISSUE TITLE
[Bug]: Speeding Up Transaction 

### ISSUE THREAD

**Issue by sirlupinwatson** [MetaMask/metamask-extension#14341]
### Describe the bug

Hi there! 

I am trying to speed up a transaction using the action button "Speed Up" and I am getting an error: 
I was able to speed it up with a 10% increase using the "Market Option" but still in a pending state. 

### Steps to reproduce

1. Automatically speed up the transaction using the action button "Speed Up" (This did not work)
2. Manually speed up the transaction using the market option with a 10% increase (Did work but is still pending)
![Metamask1](https://user-images.githubusercontent.com/55941045/161559135-4eec0143-8021-4efe-a01e-3f8c2df3cc31.png)

Enabled Enhanced Gas Fee UI (On)

### Version

10.11.3

### Browser

Firefox

### Operating system

Windows

**Comment by seaona** [comment]
Getting the same error on the last 10.13.0

**Comment by kevinghim** [comment]
Should be fixed via https://github.com/MetaMask/metamask-extension/pull/14355
