### ISSUE TITLE
[Bug]: Number of Accounts not correct on Segment

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14371]
### Describe the bug

**Problem**: with a fresh new Metamask wallet, we see that the number of accounts is not tracked correctly on Segment, when we introduce Hardware Wallet accounts.

https://user-images.githubusercontent.com/54408225/161935675-339c9e0f-4659-4df2-bf46-c895a2497873.mp4

### Steps to reproduce

1. Create a new MM wallet
2. Create a couple of regular accounts -- see that Segment is tracking the # of accounts correctly
3. Import Hardware Wallet
4. Add a couple of Hardware wallet accounts --  see that Segment is NOT tracking the # of accounts correctly anymore

### Version

10.12.4

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
@seaona It looks like that is segment, which is different from sentry. Segment is used for metrics tracking, sentry is a tool that tracks unhandled errors.

While not related to v10.12.4, you have uncovered a bug in our metrics code.

**Comment by seaona** [comment]
> 

oops! that's right, thank you @danjm  I've updated the references to Segment
