### ISSUE TITLE
[Bug]: Fake ABI will make metamask display function type even if tx is sent to an EOA. 

### ISSUE THREAD

**Issue by misirov** [MetaMask/metamask-extension#14384]
### Describe the bug

It is possible to create a fake ABI on ethersJS and make the user think he is executing a function, when actually it is just a transfer of funds to another EOA account.

### Steps to reproduce

0. SET ADDRESS TO ANOTHER EOA
const address = "0x123.."

1.CREATE ABI:
const ABI = [ "function buy(address, uint256)"]
![Inkedunknown](https://user-images.githubusercontent.com/47452703/162075249-aa15fa8d-9cae-4da4-ae23-7e7c94c5edba.jpg)

2. SEND TX, WILL DISPLAY FUNCTION TO USER
 var tx = await contract.buy(address, amount)

### Version

10.11.3

### Browser

Firefox

### Operating system

Windows

### Additional context

seen this in phishing campaigns

**Comment by Gudahtt** [comment]
Thanks for the report! This was already fixed in #13683, which is part of v10.12.4. This release is currently mid-rollout, so not all users have gotten the update. It should be rolling out to 100% of users soon.
