### ISSUE TITLE
[Bug]: Typo on "Wen" dark Mode prompt

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14387]
### Describe the bug

**Problem**: there is a typo on Dark mode initial prompt. Saying "Wen" instead of "When"
![image](https://user-images.githubusercontent.com/54408225/162181855-ddd024fb-1dbf-4f10-babf-b3ef73e8ff23.png)

### Steps to reproduce

1. Unlock Metamask

### Version

develop branch

### Browser

Chrome, Firefox

### Operating system

Linux

**Comment by FrederikBolding** [comment]
I assumed this was supposed to be a "wen moon?" joke 😅

**Comment by seaona** [comment]
ahhh alright that might be the case 😂
