### ISSUE TITLE
[Bug]: fishing campaign

### ISSUE THREAD

**Issue by muggenhor** [MetaMask/metamask-extension#14390]
### Describe the bug

I couldn't find any other point of contact, so reaching out here.

I've noticed a series of fishing attempts that look to be specifically targetting MetaMask users (aimed at an e-mail address leaked in the bitcoinforum leak):

They come with the subject line: "MetaMask - KYC verify your wallet in time!"
![Screenshot from 2022-04-07 14-29-06](https://user-images.githubusercontent.com/484066/162198952-8b0fd8d2-ba8e-439d-ae93-0ec541ebc9b7.png)

The blue button links to "https:// s {dot} id {slash} atemdivine" which immediately 301 redirects to "https:// mask <dash> users {dot} myddns {dot} me {slash} index {dot} php". That domain name (at time of writing) resolves to "2 {dot} 58 {dot} 149 {dot} 241" (only an A record, no AAAA record is present).

That page is clearly intended to gather and obtain recovery passphrases:
![Screenshot from 2022-04-07 14-34-07](https://user-images.githubusercontent.com/484066/162199825-d5dd80e2-e7ac-4e84-aad5-e87f16b579cb.png)

The WHOIS database tells me that this IP is controlled by "Serverion BV" a Dutch company (or subsidiary) that seems to do shared web hosting. I'm sending this information to their registered abuse e-mail too.

**Comment by kevinghim** [comment]
@muggenhor thanks for the report. I couldn't resolve any of the urls you posted. If you have any additional related sites, please let us know. We'll report them to our anti-phishing service partner.

**Comment by muggenhor** [comment]
Strange. The top-level link (`https://s.id/atemdivine`) does have a more indirect redirection path now. But the content is still the same.

**Comment by kevinghim** [comment]
@muggenhor thanks for your contribution. We've reported both the top-level link and the secret recovery phrase phishing site to our anti-phishing service partner.
