### ISSUE TITLE
Write tests for Infura network client

### ISSUE THREAD

**Issue by mcmire** [MetaMask/metamask-extension#14404]
As part of an effort to [merge the NetworkController that exists in this repo with the NetworkController that exists in the `controllers` repo](https://github.com/MetaMask/controllers/issues/753), we need to write tests for the JSON-RPC layer, and all of its custom behavior, that the NetworkController exposes.

We have two "network clients" that handle JSON-RPC network requests, one for Infura and one for custom networks. The custom network client tests are covered under issue #16041. This issue is for testing the network client that is specific to Infura.

**Comment by Gudahtt** [comment]
The remaining improvements to the Infura client tests are:

* Add tests for methods defined in the Ethereum spec that are not supported by Infura (follow-up from #15556)
* Add tests for multi-parameter methods to ensure we get a cache miss when any single parameter changes (follow-up from #15556)
* Update `eth-json-rpc-middleware` and fix any tests that cover the old broken behaviour where duplicate requests are sent.
* Add tests for `retry-on-empty` middleware

**Comment by Gudahtt** [comment]
Closing because the remaining work has been tracked in separate issues, referenced in the previous comment
