### ISSUE TITLE
Add the hold to reveal button before revealing an account’s private key

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-extension#14415]
On mobile we have a component that the user presses and holds to reveal their SRP after they've put in their correct password: 

![IMG_4571DA5FFD1A-1](https://user-images.githubusercontent.com/7900773/208415554-4997b268-60c1-4c6a-aa75-b5726135a5dd.jpeg)

The aim of this component is to make the user think before revealing their SRP and it's shown that at [about 10% of users actually drop off during this hold phase](https://mixpanel.com/s/3PIDjZ). However, this component is not implemented on extension, so we should do this.

The aim of this ticket is for parity between mobile and extension so the user journey and components should act exactly the same across both platforms.

Designs: https://www.figma.com/file/4LQje3epQz8g4xO8fRdauv/SRP-Reveal-Warning?node-id=44%3A1574&t=XfTI9qoKO5FuDnxj-1

Related Notion description:
https://www.notion.so/Add-the-hold-to-reveal-button-before-revealing-an-account-s-private-key-5dc7d0911c5a4ee7aaf99de59a0f2e73

**Comment by AlexJupiter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Key-Management-Team-62505028c3853700162f65e0/issues/MetaMask/metamask-extension/14415?planning-poker) with Zenhub @montelaidev @gantunesr @plasmacorral @olenapankina

**Comment by AlexJupiter** [comment]
@montelaidev any idea what happened to this? The PR says this was merged ages ago but I'm not seeing this implemented in the latest extension version.

**Comment by plasmacorral** [comment]
Add reveal UI to export private key flow (https://github.com/MetaMask/metamask-extension/pull/18170) was included in [release 10.32](https://github.com/MetaMask/metamask-extension/releases/tag/v10.32.0) which is being deployed right now.
