### ISSUE TITLE
Rename "reset account" to something more accurate

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#14418]
Maybe "Clear account transaction history for current network", since that's what it does.

**Comment by lightclient** [comment]
I'm bleeding everywhere from this UX paper cut. I thought "Reset Account" deleted my account. Look, I know it says in the small text above, but tbf I only briefly glanced at what jumped out at was "Secret Recovery Phrase" and I immediately assumed it mean I would have to reenter it.

**Comment by ElvirCe** [comment]
@bschorchit we will need final decision on the title but also the copy below it as it refers to the Reset Account title


![Image](https://user-images.githubusercontent.com/98470173/208868548-4cea0902-1006-44ee-b0ec-e1dcc5984e05.png)

**Comment by bschorchit** [comment]
Proposal (pending internal discussion):

`Clear activity and nonce for current account and network`
This will reset the nonce and erase data from the activity tab in your wallet for the current account and network. Balances won't be affected.
Button: `Clear activity and nonce`

**Comment by lightclient** [comment]
`Clear activity and nonce` makes much more sense than `Reset account` IMO.

**Comment by bschorchit** [comment]
Internal thread [here](https://consensys.slack.com/archives/G1L7H42BT/p1671673317727789). 
As it was confirmed in the thread that the proposed description correctly communicates what will happen, @coreyjanssen could you also give this copy a review?

**Comment by coreyjanssen** [comment]
@bschorchit I'm not able to access the internal thread referenced! But here's a quick copy review, based on my interpretation of the conversation in this thread. 

`Title` Clear activity tab data
This resets the nonce and erases data from the activity tab in your wallet. Only the current account and network will be affected. Your balances and incoming transactions won't change.
`Button` Clear activity tab data

**Comment by bschorchit** [comment]
Just gave you access to the thread, @coreyjanssen :)
This settings also clears the account's nonce (which is not necessarily related with the activity tab) so I'm not comfortable renaming the title and button to `Clear activity tab data`

Maybe `Clear activity and nonce data`?

**Comment by coreyjanssen** [comment]
Your edits make sense to me, and I'm good with the changes! My thinking is that most people don't understand what a nonce is, even if we do, so too many uses of it could confuse. But I like the compromise we've reached (which I've pasted here too for posterity). 

`Title` Clear activity and nonce data
This resets the account's nonce and erases data from the activity tab in your wallet. Only the current account and network will be affected. Your balances and incoming transactions won't change.
`Button` Clear activity tab data

**Comment by bschorchit** [comment]
Oh yes, there was some context missing on my side as well. This is a feature hidden under Settings > Advanced and is mostly used by devs/power users who know what nonce is. Most users won't be under Advanced settings or using this :)

**Comment by coreyjanssen** [comment]
Ah ok that makes a lot of sense then! Thanks for the deeper context. :)

**Comment by ElvirCe** [comment]
Final decision is: 
Title: Clear activity and nonce data
Copy: This resets the account's nonce and erases data from the activity tab in your wallet. Only the current account and network will be affected. Your balances and incoming transactions won't change.
Button: Clear activity tab data

**Comment by dzfjz** [comment]
Verified by QA
