### ISSUE TITLE
[Bug]: Metamask not displaying all the Ledger accounts available and displaying a repeated account

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14424]
### Describe the bug

**Problem**: seems that there is an incorrect behaviour on how Metamask is finding/displaying the Ledger available accounts, when importing more than 1 Ledger Addresses.
One address appears duplicated, while the other does no appear

Maybe this might cause other open issues related to Ledger (keyring not detected, wrong address etc) - to investigate

https://user-images.githubusercontent.com/54408225/162943441-65c2fe72-e5c9-4bd8-a672-023ff5438623.mp4

### Steps to reproduce

1. Unlock Metamask
2. Import a couple of Ledger accounts (more than 1)
3. Click on import Hardware Wallet again
4. See the available addresses on the list 

### Version

10.13.0

### Browser

Firefox

### Operating system

Linux

**Comment by Mosillino1** [comment]
Hi 
Can anyone help me with "not well-formed currency" error on metamask?
When I try to sell, send and or buy etc. I face this error attached.

Please help me all my cryptos and tokens are in my metamask and I can not do anything with them.
![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164400338-02d3b84e-9788-4782-9f34-3465597a6f10.jpg)
![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164402438-5c73c366-3cdf-4d48-9141-9f8f076e352f.jpg)

**Comment by anaamolnar** [comment]
@Mosillino1 Are you able to clear the error after restarting the App or clicking Try again? What currency conversion are you using?

**Comment by anaamolnar** [comment]
@Mosillino1 You should be able to clear the error after restarting the app. After that, please go to Settings->General and change the currency conversion to another currency such as USD or EUR.

**Comment by Gudahtt** [comment]
@Mosillino1 That error has nothing to do with this issue. This issue is about a bug on the extension, but you have posted about an error on MetaMask mobile. Please contact our support team here: https://metamask.zendesk.com/hc/en-us/

**Comment by Mosillino1** [comment]
Hi
How do I clear the error? I press try again but nothing happens. I have
USDC and ETH. I can not send them or do anything else. I wanted to
reinstall the app, but I thought a better idea to install it the app first
if I had the same assets and there was no problem with that, then I delete
previous one. But when I installed it on another device, I didn't have my
assets on the new app. I only have my assets on the previous, but I can't
do anything with them. When I try to send or swap I face this error. Please
help me with that.

**Comment by seaona** [comment]
This relates to https://github.com/MetaMask/metamask-extension/issues/6012
