### ISSUE TITLE
[Bug]: Metamask get's on a frozen state and does not trigger any Ledger tx signature

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14426]
### Describe the bug

**Problem**: when I remove a Ledger account, while having pending transaction to sign on Ledger, we get on a "wrong state" inside Metamask, where it's not possible to perform any other action with that account if we add it again.

https://user-images.githubusercontent.com/54408225/162975702-383328c3-d6eb-4ff3-a445-e2ae78e605c8.mp4

### Steps to reproduce

1. Import a Ledger account
2. Go to Dapp
3. Connect to Dapp with that Ledger account
4. Click Deploy a contract
5. Confirm tx on Metamask but do NOT confirm it on Ledger
6. Go to Metamask
7. Go to account details
8. Remove account
9. Go to Import Hardware Wallet Account
10. Accet the tx on Ledger
11. Import the same account
12. Try to perform a transaction

### Error messages or log output

```shell
Metamask get's loading indefinetly
```

### Version

10.13.0

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
The same happens if, instead of removing the Account (step 8), we lock Metamask with the tx confirmation pending on Ledger. Once Metamask is locked, we confirm it and unlock it again. This results in Metamask getting loading indefinitely and no tx is triggered on Ledger anymore

**Comment by Pasha8914** [comment]
Have same trouble

**Comment by bschorchit** [comment]
Is this related to https://github.com/MetaMask/metamask-extension/issues/9686 ?

**Comment by seaona** [comment]
@bschorchit from my point of view, it looks indeed related

**Comment by Mosillino1** [comment]
Hi 
Can anyone help me with "not well-formed currency" error on metamask?
When I try to sell, send and or buy etc. I face this error attached.

Please help me all my cryptos and tokens are in my metamask and I can not do anything with them.
![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164400338-02d3b84e-9788-4782-9f34-3465597a6f10.jpg)
![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164401941-224cfc58-ccb5-4333-ad74-6cade1aa3400.jpg)
![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164401999-9e419a6e-1a35-4cd0-abd8-c015090cddf1.jpg)
