### ISSUE TITLE
[Bug]: Metamask displays a Transaction with Ledger as a Contract Deployment

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14430]
### Describe the bug

**Problem**: after rejecting deploying a contract, when I perform a regular transaction using Ledger, I see that the transaction appears as a "Contract Deployment" on the activity logs

https://user-images.githubusercontent.com/54408225/163143417-4c80f425-c544-428c-9e70-df268fec26d4.mp4

 

### Steps to reproduce

1. Unlock Metamask
2. Import Ledger account
3. Go to Dapp
4. Click deploy contract, and when the tx is trigger on Ledger, cancel it on Ledger
5. Go to Metamask
6. Send ETH to another account
7. Check the activity logs

### Version

10.13.0

### Browser

Chrome

### Operating system

Linux

**Comment by Mosillino1** [comment]
Hi 
Can anyone help me with "not well-formed currency" error on metamask?
When I try to sell, send and or buy etc. I face this error attached.

Please help me all my cryptos and tokens are in my metamask and I can not do anything with them.
![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164400338-02d3b84e-9788-4782-9f34-3465597a6f10.jpg)
![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164401378-a531db9e-0ff5-4d31-bf0e-8fdf289fcf93.jpg)
