### ISSUE TITLE
[Bug]: specified gasPrice but also included maxPriorityFeePerGas

### ISSUE THREAD

**Issue by sosoxuc** [MetaMask/metamask-extension#14431]
### Describe the bug

I get an error on miannet:
code: -32602
message: "Invalid transaction params: specified gasPrice but also included maxPriorityFeePerGas, these cannot be mixed"

```
await uniswapContract.methods
          .approve(lpStakingAddress, lpAllowanceQty)
          .send({ from: account, maxPriorityFeePerGas: 50000000 });
```

### Steps to reproduce

Create JS code [example above]

### Version

10.12.3

### Browser

Chrome

### Operating system

Linux

**Comment by ahad1412** [comment]
Help Solution

![Image](https://github.com/user-attachments/assets/86c3a23e-2f7e-4957-aa4e-b2c011f5f766)
