### ISSUE TITLE
[Bug]: Transaction errors that cannot be resolved in the Metamask

### ISSUE THREAD

**Issue by sgh002400** [MetaMask/metamask-extension#14445]
### Describe the bug

1. Transactions in the Metamask are pending for 3 hours (estimated to be caused by too low Gwei).
2. Accelerated by increasing Gwei(approximately 60 or 70) to solve this problem, but no response / cancellation is the same.
3. Multiple attempts to resolve the problem occurred overlapped multiple transactions and pending (adjust nonce value x).
4. Refer to the metamask document and send a new transaction using the same nonce value as the transaction in the first pending state.(The nonce of the error transaction was 131)
5. Failed to send transaction.
6. I have reset my account.
7. Records erased, but still pending on etherscan. Pending when sending new transactions
8. Send transactions from mobile metamask after hearing that sending transactions from mobile will resolve them.(Automatically, the nonce was 131)
9. error : "replacement transaction underpriced"
10. In "MyEtherWallet" I sent 0 ETH from the wallet currently experiencing an error to the same wallet. (Automatically, the nonce was 131)
11. It's solved!

### Steps to reproduce

* Supplementary resources for bug reports
* The number below matches the bug description number

1. 
![image](https://user-images.githubusercontent.com/62228195/163435311-dd3bbd4c-c7ad-4e78-bcce-48a9028e1088.png)

2.
https://user-images.githubusercontent.com/62228195/163435577-53cb72b1-efb9-499d-bd06-e9c324aa890c.MOV

3. 
![image](https://user-images.githubusercontent.com/62228195/163435673-b2c542eb-8ee1-4b90-9e5c-9d267abbd78d.png)

5. 
![image](https://user-images.githubusercontent.com/62228195/163436484-6d3d9147-e247-4066-933f-38ade3e6f9e8.png)

9.
![image](https://user-images.githubusercontent.com/62228195/163437578-488f20ab-f059-47fc-9b10-03e66b70dc9e.png)

 

### Version

10.12.4

### Browser

Firefox

### Operating system

MacOS

**Comment by bschorchit** [comment]
This will be fixed by https://github.com/MetaMask/metamask-extension/pull/14355
