### ISSUE TITLE
[Bug]: Firefox freeze with play.dogedash.com in several times

### ISSUE THREAD

**Issue by jk-85** [MetaMask/metamask-extension#14457]
### Describe the bug

Have the newest firefox (99.0.1. 64 bit). Tried a portable one also, but on one of my windows 7 notebooks I get a firefox-freeze. I debugged it with visual studio 2022, see the log below. I think these last lines have to do something with it. Very strange that I have no other machines where this is happening, only one notebook.

### Steps to reproduce

1.

### Error messages or log output

```shell
[JavaScript Error: "FrameData missing for webextension@metamask.io page moz-extension://45c8c429-2d3e-4f57-9e42-022c394617b1/popup.html" {file: "resource://gre/modules/ExtensionPageChild.jsm" line: 434}]
initExtensionContext@resource://gre/modules/ExtensionPageChild.jsm:434:10
initExtensionDocument@resource://gre/modules/ExtensionProcessScript.jsm:322:26
```

### Version

10.12.4

### Browser

Firefox

### Operating system

Windows

**Comment by jk-85** [comment]
I found out firefox also crashes occasionally on this notebook even when I click at one entry on the upper main menu. So I don't know if it's really relativ with metamask.

**Comment by bschorchit** [comment]
Closing this issue for now. Let us know if you're able to reproduce it and it seems related with MetaMask. Thanks!
