### ISSUE TITLE
[Bug]: Cannot submit ledger transaction Gnosis Chain

### ISSUE THREAD

**Issue by Philogy** [MetaMask/metamask-extension#14458]
### Describe the bug

After initiating a transaction, setting the gas price and proceeding to 'next' the wallet loads for a while before coming back with the notification "Transaction X failed! Network Error". No information was displayed on my hardware wallet. Note that this only occurs when trying to initiate Gnosis Chain transactions but not on other chains such as the Ethereum mainnet.

### Steps to reproduce

1. Correctly configure ledger device (connect to device, setup udev rules, update firmware etc.)
2. Open Ethereum app on ledger and enable blind signing
3. Connect ledger to metamask
4. Add and switch to gnosis chain (data available on e.g. chainlist.org)
5. Initiate any transaction and proceed to 'next'

### Error messages or log output

```shell
Transaction X failed! Network Error
```

### Version

10.12.4

### Browser

Brave

### Operating system

Linux

### Hardware wallet

Ledger

**Comment by Philogy** [comment]
Note that generally sending transactions on Gnosis Chain via Metamask works for hot wallets stored in Metamask but not via ledger.

**Comment by holadiegocrypto** [comment]
Same problem, same configuration...
