### ISSUE TITLE
[Bug]: Metamask and Metamask FLASK ：Cannot be connected

### ISSUE THREAD

**Issue by tonny1010** [MetaMask/metamask-extension#14464]
### Describe the bug

When I install metamask and metamask flag on a browser at the same time, I open the uni website and the "connect a wallet" selection box will not pop up （If only one wallet plug-in is installed in the browser, this box will pop up）
For example, my wallet: 0xA8A298B39Ae80D6904A07973792f9ad7f85C4d4e
https://app.uniswap.org/#/swap?chain=mainnet
（browser ：Iridium 2021.12 ，64）
MetaMask 10.8.1 and  Metamask FLASK  10.8.2-flask.2

![image](https://user-images.githubusercontent.com/101445695/163806681-65036c8a-3bc2-4898-a714-18d987d36542.png)
![image](https://user-images.githubusercontent.com/101445695/163806697-59f55e23-2e0c-459d-8f5a-685bb33e2e33.png)

On other browsers, I didn't test whether it would be the same

### Steps to reproduce

1.
Open the website don't talk box

### Version

10.8.2-flask.2

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Windows, Other (please elaborate in the "Additional Context" section)

**Comment by FrederikBolding** [comment]
Hey there! It seems that you might be using both MetaMask and MetaMask Flask at the same time. That's not supported. Can you try and disable MetaMask Flask?

**Comment by kevinghim** [comment]
@tonny1010  Closing this for now. Let us know if there are any more issues beyond issues stemming form using both MetaMask and MetaMask Flask at the same time.
