### ISSUE TITLE
[Bug]: Metamask FLASK ： "Status view on block Explorer" cannot be opened

### ISSUE THREAD

**Issue by tonny1010** [MetaMask/metamask-extension#14462]
### Describe the bug

Metamask FLASK ： "Status view on block Explorer" cannot be opened
Click the "status view on block Explorer" of the poly network, swap or after sending successfully, and the correct page cannot be opened

For example, my wallet: 0x2db6a188ddf1115fe0ca52f72f21b6fa9969121b
Confirmed ：0xe6585be5dc4f423b0bfeb46c8fcd809cf31f0ab09a96196e8257bf3b5b9ecd72
Click "view on block Explorer" above to display: err_ FILE_ NOT_ FOUND
（browser ：Iridium 2021.12 ，64）

![image](https://user-images.githubusercontent.com/101445695/163804543-293d8eae-8860-49e2-9a0f-a7208a43cba7.png)
![image](https://user-images.githubusercontent.com/101445695/163804566-7c749c6d-23e6-483a-8db2-a752a9bca50e.png)

### Steps to reproduce

1.
Direct trading will reappear and be inevitable

### Version

10.8.2-flask.2

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Windows

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

**Comment by tonny1010** [comment]
On other browsers, I didn't test whether it would be the same

**Comment by bschorchit** [comment]
Can you check if you have a block explorer link set to this network? You can do this by going to Settings > Networks and then clicking on the network. Setting the correct block explorer link there should fix that.

**Comment by Mosillino1** [comment]
Hi 
Can anyone help me with "not well-formed currency" error on metamask?
When I try to sell, send and or buy etc. I face this error attached.

Please help me all my cryptos and tokens are in my metamask and I can not do anything with them.

![Screenshot-4221378](https://user-images.githubusercontent.com/104128100/164402296-e77b3422-01a0-49d6-8493-3ffcc3be6617.jpg)
