### ISSUE TITLE
[Bug]: When transaction fails with an error in contract, completely bullshit error message is shown

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14460]
### Describe the bug

See steps to reproduce

### Steps to reproduce

1. On the Ropsten test network, send a transaction to this address:
```
0xCd0da5FD7b1E68415Ef7cf306366eCAb15ab0992
```
with a value of `0.0005` ETH, and with this hex data:
```
0xc1a03b804e8666092a9dfab37074c648e740eef19530fa074ccb207e6ecb495239ab4bfd0c24396247abd45bf529bf0eca4126f4aeb9af42d8c0a771b2dde4aa3880fc46000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000003500000000000000000000000000000000000000000000000000000000625c803900000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000001a68747470733a2f2f73616e64736361702e65733f7265663d3533000000000000
```

The transaction will fail. I know that it fails because of a `require()` condition in the contract (which I wrote) that is not satisfied by the data. But let's assume I don't know that.

I can see in MetaMask that the transaction has failed.

Now, if the transaction had actually been sent to the blockchain, and recorded as a failed transaction, I would be able to see it on Etherscan, but that is not the case (the link to see it on Etherscan is greyed out). Also, if that was the case it would have taken a while and it didn't, it failed immediately. And I would have been charged the gas fees, which I wasn't.

So, I guess Metamask must have "simulated" the transaction on the local EVM and seen that it will fail and it hasn't even sent it to the block chain. Which is cool, but then:
A. I should be able to force Metamask to send the transaction anyway, pay for it, and have it actually fail and be recorded as failed on the block chain. I don't see such an option anywhere. There's a "retry" option which brings up a "speed up transaction" form where I can tinker with gas settings, and for some reason instead of a "confirm" button it has a "save" button. Anyway, if I try that the same will happen as before.
B. I should see the actual error message from the contract. Instead, I see this nonsensical error message:

Oh, actually, I see the error message on a kind of notification popup that shows up for a few seconds, but if I want to see the error message again a few minutes later, like right now, I cannot find it anywhere, and the only way to see the error message again so that I can copy and paste it, is to try sending the transaction from scratch again. This is an issue within the issue within the issue.

This is the error message from MetaMask:
> ...

Oh FUCK. I selected it in the popup and copied it, but it didn't get copied into the clipboard. I'm not sure whether this is MetaMask's or Chrome's fault. Please do tell me, because if it's Chrome I want to report it to them.

Ok so let me try for the third time and this time I'll take a screenshot.

Here:

![image](https://user-images.githubusercontent.com/13969584/163732866-264a2f02-d506-4357-a49e-a9ba9ee5be9c.png)

### Version

10.12.3

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I could reproduce it.
![Screen Shot 2022-04-18 at 15 14 07](https://user-images.githubusercontent.com/34968356/163854342-04dbebdf-e851-4b4a-82cf-2
![Screen Shot 2022-04-18 at 15 15 43](https://user-images.githubusercontent.com/34968356/163854400-ea8084d8-682e-4385-bf06-2dab2d1076db.png)
21fac3c23c9.png)

**Comment by bschorchit** [comment]
I could reproduce it. 
![Screen Shot 2022-04-18 at 15 14 07](https://user-images.githubusercontent.com/34968356/163854529-8af7457a-b567-4052-a6fc-b1c2a88e48f1.png)

![Screen Shot 2022-04-18 at 15 16 59](https://user-images.githubusercontent.com/34968356/163854589-f10881ac-2d43-4a5a-9375-cab5a7358b16.png)

**Comment by php4fan** [comment]
I think I forgot to mention, that if I send a transaction to the same contract, calling the same function, but with valid data that won't trigger an error inside the contract (all done the same way as in the reproduction scenario, but with different hex data), everything works as expected and the transaction is sent and succeeds.

On the other hand, if I try the same failing transaction on Remix (except that there I interact with the contract at a higher level, choosing the function to call and entering the unencoded values for each parameter, because Remix has a completely different unrelated bug that prevents me from sending a transaction with already-packed data; but I build the exact same transaction that I'm testing here), then the failure is handled as expected. Remix warns me that the transaction is going to fail, and it shows the actual error message from the contract; it also gives me the option to insist and actually send the transaction (via MetaMask), I confirm it in MetaMask and it goes through and it fails on-chain, all as expected. 

I'm not entirely sure if Remix has an "advantage" here in that it knows the source code of the contract.

**Comment by php4fan** [comment]
Hope this comment counts as "activity" so this doesn't get closed as "stale".

**Comment by php4fan** [comment]
Again this crap. Please reopen.
