### ISSUE TITLE
[Bug]: Heavy eth_feeHistory spam with multiple addresses

### ISSUE THREAD

**Issue by wizzard0** [MetaMask/metamask-extension#14473]
### Describe the bug

With many addresses and/or on networks with frequent blocks, MetaMask makes thousands of RPC requests, in particular `eth_feeHistory`, until hitting rate limits or becoming slow.

It seems that Metamask attempts to refresh each account for each block, as I observe at least as many requests as there are accounts.

**Expected Behavior**: 
1) Fee estimation happens only if I'm going to submit the transaction, 
2) and not multiplied by the number of accounts.
3) Balances get updated only for the currently selected account

**Workaround**: keep at most one address.

May be related to #13874, #13649 

Sometimes it does even more requests (in high thousands), maybe https://github.com/MetaMask/metamask-extension/issues/5159#issuecomment-428456161 but I have no hard evidence for this.

### Steps to reproduce

1. Create or import multiple accounts in MetaMask
2. (optional) use a network with frequent blocks (BSC, Harmony, etc)
3. Open Extensions > (check Developer mode) > Inspect views > background.html of Metamask, open Network tab
4. Click the fox and/or open Metamask in a tab via "..." > Expand view
5. Observe hundreds of RPC requests, most ofthen eth_feeHistory
6. If you keep the tab or popup open, soon you'll hit RPC rate limiting from your node provider %)

### Error messages or log output

```shell
See inspector screenshot below
```

### Version

v10.10.2 from Edge Addons website

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Microsoft Edge

### Operating system

MacOS

### Additional context

(pictured: inspector window after opening the popup)

<img width="668" alt="image" src="https://user-images.githubusercontent.com/424619/164010471-d55aebea-23fd-4443-8b0f-3d65f8497e74.png">

**Comment by kevinghim** [comment]
@mcmire FYI

**Comment by mcmire** [comment]
Hi @wizzard0,

Thanks for this report. It seems that you're experiencing a bug that is fixed in the Chrome and Firefox versions of MetaMask but not in Edge yet. We're admittedly a little behind in getting the Edge version up to date with the other browsers, but I've raised this internally and we're going to get that updated soon. In the meantime, I would advise using Chrome or Firefox. I'll report back when we have an update.

**Comment by mcmire** [comment]
Seems I forgot to update this issue as I promised. This problem was fixed in MetaMask 10.11.2, and Edge was updated some time between May 9th and May 16th. Let us know if you see this problem again!
