### ISSUE TITLE
[Bug]: Something about gas estimation has gone berserk

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14493]
### Describe the bug

Look at this **contract** creation on the Ropsten test network:
https://ropsten.etherscan.io/tx/0xdcd7889c38713e9003120ff53074e129c456f3cbf222af062141603793b62530

I deployed that contract using Remix. I am testing and have deployed dozens of slight variations of that contract (it's basically an OpenZeppelin ERC721 with very few extensions), and the **cost of deploying it** has always oscillated around **0.009 ETH**

Now I have gone to Remix, opened the exact same source code, compiled it for the Nth time, and went to Deploy it.
Now Metamask estimates a cost of **0.4-0.5 ETH to deploy the contract**. That's **2 orders of magnitude** above what it used to be, despite it being the exact same source code.

### Steps to reproduce

See above

I wanted to paste this screenshot below into "Error messages or log output" but this stupid thing won't let me so I'll paste it here:
![image](https://user-images.githubusercontent.com/13969584/164444125-9c01e708-3912-4d4a-91d8-dbd184058eeb.png)

### Version

10.12.4 (why is it so difficult to find)

### Browser

Chrome

### Operating system

Linux

**Comment by php4fan** [comment]
By manually editing the gass settings, it looks like the value that is seriously miscalculated is this one:

![image](https://user-images.githubusercontent.com/13969584/164447725-35e047c3-8a6b-4b46-860a-6c30072ae1f6.png)

(BTW, note that your own UI won't accept that many decimals, but you yourself generated that default value with that many decimals. That's a separate bug).

**Comment by php4fan** [comment]
Hmmmm it's starting to look like the gas prices have actually increased that much.... could it be??

**Comment by kevinghim** [comment]
@php4fan when a transaction is expected to fail, the gas estimates will be extremely high. Trying to execute it when it is expected to be expensive but fail, and is not recommended. If you upgrade to the latest Enhanced Gas UI, you'll see a button “try anyway.”, which can reveal the gas calculations with a red warning.

**Comment by php4fan** [comment]
This was not expected to fail at all (and it did not once I increased the gas fees). It was a contract deployment.

I'm not sure if you say it was expected to fail because you assumed this was somehow related to my other bug report, which it is not.

Anyway, I finally sent it with the suggested huge gas fees and it went through successfully, actually costing around the estimated amount. I guess that confirms that there was nothing wrong with the estimation and prices has just really rocketed, right?
