### ISSUE TITLE
Transactions 'stuck'

### ISSUE THREAD

**Issue by vs22** [MetaMask/metamask-extension#1450]
Hi, I tried to make multiple transactions today before the previous ones executed (it took 40 mins for the first to execute) and the last four are now 'stuck' and have been for almost four hours. They have three dots next to them and when I open any of them in Etherscan, it says "Unable to locate Transaction entry". 

The last two of these transactions were my attempts to then get my ether out of the wallet, but they just joined the end of the queue as expected. 

How do I 'unfreeze' my account/withdraw my ether from it?

Thanks in advance!

------------------------------------------------------------------------------------------------------
UPDATE: They're still stuck! Can someone please help me out here; it's quite a lot of ether for me. 

Thanks!

------------------------------------------------------------------------------------------------------
UPDATE 2: 

SOLVED!! In case anyone has similar problems, I simply logged into my MetaMask account on a different computer that wasn't still trying to execute these transactions (of course, it wouldn't even know about them) and then sent my Ether to a different wallet from there.

**Comment by aquiladev** [comment]
I have the same problem!

**Comment by Zanibas** [comment]
Sorry for the late reply, but could you give us the state logs? You can find a button for this in the info section of the dropdown menu!

Thank you very much!
