### ISSUE TITLE
[Bug]: Incorrect token standard on Token Added event

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14503]
### Describe the bug

Importing a ERC-1155/ERC-721 in the Import Custom Token flow triggers a `Token Added` event with the  property `token_standard: 'ERC20'`

### Steps to reproduce

1. Settings -> Security & Privacy -> Participate in MetaMetrics -> ON
2. Click `Import Tokens` on the overview page
3. Select the `Custom Token` tab
4. Enter a the Token Contract Address: `0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85`, Token Symbol `ENS-NFT`, Token Decimal `0`
5. Click `Add Custom Token`

### Version

10.14.0

### Browser

Chrome

### Operating system

MacOS

**Comment by GuillaumeRx** [comment]
The token standard parameter sent is using a hard coded `TOKEN_STANDARDS.ERC20`. The added token object do not contain the token standard. Should the `token_standard` parameter be removed ?
