### ISSUE TITLE
[Bug]: Metamask window appears off screen

### ISSUE THREAD

**Issue by Protey** [MetaMask/metamask-extension#14519]
### Describe the bug

Metamask window appears off screen

### Steps to reproduce

1.
connect metamask when prompted
when requesting payment of commission
and the like...

### Version

10.12.4

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Windows

### Additional context

Used Yandex browser
problem screenshot - ![ya browser](https://user-images.githubusercontent.com/6497045/165063167-ca929a3f-ae05-4869-8351-3dfd2a2fb3a1.png)

**Comment by Alisizer** [comment]
![image](https://user-images.githubusercontent.com/58936472/194840909-369f296b-00ea-4768-88cf-d456de790bd1.png)
I can confirm this behavior

**Comment by Protey** [comment]
Why the problem with the window position is still not solved, do as in the Opera browser, is it so difficult to add a couple of lines in the metamask project to make the metamask window appear in the Yandex browser in the correct position?!!!!

https://user-images.githubusercontent.com/6497045/204846137-198076b7-0d10-412a-8e19-94fac970d875.mp4

**Comment by icq66666057** [comment]
**I have the same problem**

**Comment by Lurikovich** [comment]
Такая же проблема
