### ISSUE TITLE
Incorrect token_standard property on Token Added MetaMetrics event

### ISSUE THREAD

**Issue by tohidshabanloo** [MetaMask/metamask-extension#14511]
### Describe the bug

Importing a ERC-1155/ERC-721 in the Import Custom Token flow triggers a Token Added event with the property token_standard: 'ERC20'

### Steps to reproduce

1.Settings -> Security & Privacy -> Participate in MetaMetrics -> ON
2.Click Import Tokens on the overview page
3.Select the Custom Token tab
4.Enter a the Token Contract Address: 0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85, Token Symbol ENS-NFT, Token Decimal 0
5.Click Add Custom Token

### Version

10.14.0

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by bschorchit** [comment]
Closing this as we're tracking this here: https://github.com/MetaMask/metamask-extension/issues/14503
