### ISSUE TITLE
Transaction Details

### ISSUE THREAD

**Issue by Je1952** [MetaMask/metamask-extension#14517]
https://tronscan.org/#/transaction/6a4c8807ec173877d05b8428966e7db4630c0bd233ae932bc220d182155503ed

**Comment by bschorchit** [comment]
Hey @Je1952, any MetaMask bug you're trying to report related to that transaction?

**Comment by bschorchit** [comment]
Closing this as this is not a bug report: https://github.com/MetaMask/metamask-extension/issues/14512#issuecomment-1108875571
