### ISSUE TITLE
[Bug]: Unable to determine Contract Standard (dForce)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14522]
### Describe the bug

**Problem**: I cannot send any dForce token as when I click Send I get the following error `Unable to determine contract standard` and Metamask get's loading indefinetly

![image](https://user-images.githubusercontent.com/54408225/165100018-da7b42bd-8246-482a-82ec-e2a71947247c.png)

**Note**: dForce is an ERC20 token
https://etherscan.io/token/0x431ad2ff6a9C365805eBaD47Ee021148d6f7DBe0?a=0x1c53dc20d1e36ed8359250de626acae36bd28a29#tokenInfo

### Steps to reproduce

1. Unlock Metamask
2. Import Asset dForce
3. Click Send dForce

### Version

10.14.0

### Browser

Firefox

### Operating system

Linux

**Comment by kdumovic** [comment]
Happens to me trying to interact with the DGD contract.

https://community.digix.global/#/

Can't seem to get Metamask working afterwards without removing the extension and setting everything back up from scratch. And then it just happens again....

**Comment by piirikas** [comment]
Possibly related to #14518 and #14459.

**Comment by FrederikBolding** [comment]
This should be solved via https://github.com/MetaMask/controllers/pull/830

**Comment by Skyge** [comment]
@FrederikBolding So have released a new version contains this fix?

**Comment by FrederikBolding** [comment]
@Skyge Not yet - It is still on the way!

**Comment by rstormsf** [comment]
@FrederikBolding any ETA on it?

**Comment by kevinghim** [comment]
The fix will be released with 10.19.0 which will start rolling out late next week.
