### ISSUE TITLE
[Bug]: "Theme" not found on Settings Search

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14542]
### Describe the bug

**Problem**: the functionality of Settings Search must include the new section "Theme" on the target search. At the moment, if we look for "Theme" no results are found.

![image](https://user-images.githubusercontent.com/54408225/165490046-3e37c68d-78c5-4ad0-aea2-b3fc6ccc1857.png)

### Steps to reproduce

1. Unlock Metamask
2. Go to Settings
3. Search for "Theme"

### Version

10.14.0

### Browser

Firefox

### Operating system

Linux

**Comment by danjm** [comment]
This will be resolved by https://github.com/MetaMask/metamask-extension/pull/14476

**Comment by seaona** [comment]
I see it fixed now.
