### ISSUE TITLE
[Bug]: Cannot connect to dapps when using MetaMask + local full node

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#14549]
### Describe the bug

When I try to connect to dapps using MetaMask + local full node, the dapp will reject my connection saying I am on the wrong network. But I am not on the wrong network, I am running a mainnet full node and trying to connect to the mainnet version of the dapp. This doesn't just happen with one dapp it happens with many dapps which makes me think it's a MetaMask problem, telling the dapps I am connecting with the wrong network when actually I am connecting on the correct network.

### Steps to reproduce

1. Configure MetaMask to use your local mainnet full node
2. Try to connect to a mainnet dapp
3. See "wrong network" errror

### Version

10.13.0

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Linux

### Additional context

this issue happens in every browser, whether I am using a hardware or software wallet

**Comment by seaona** [comment]
@john-light which are the dapps you've tried? I cannot repro the issue with my local node. I've tried:
- Compound
- Uniswap
- Opensea
- Balancer
and connection was working fine
