### ISSUE TITLE
[Bug]: "Authorization error" triggered that prevents connection to dapps

### ISSUE THREAD

**Issue by AlexHerman1** [MetaMask/metamask-extension#14552]
### Describe the bug

Users describe "Authorization error" being triggered in dapps that are already connected to their addresses/metamask in question.

Users report being unable to interact with these dapps, even after clearing cache/cookies and other basic troubleshooting steps.

**User descriptions:**

"Clear the cache and completely reinstall the browser, delete any remaining temporary files, and reboot.
I've done everything but can't solve it."

"I manually disconnected all the connected sites from metamask. When i try to connect again (Example: Pancakeswap) it is showing as Authorization Error Please authorize to access your account. Iam unable to connect all the sites which i used to connect previously without any trouble. My version is 10.13.0. Iam using Brave browser and Windows 7 PC. Kindly suggest a solution"

One user managed to fix with a reinstall
![C47362A5-4D63-4420-AD7B-EAAAACD4F20E_1_105_c](https://user-images.githubusercontent.com/38788573/165629831-d5e176cd-c578-44d9-afb0-be0700ecd880.jpeg)

### Steps to reproduce

We have not been able to reproduce, search in zendesk for tickets:

"Authorization error" order_by:created_at sort:desc

### Version

10.13.0

### Browser

Chrome

### Operating system

Windows

**Comment by TMakwana13** [comment]
I am facing same issue. If you could resolve it, guide me.
