### ISSUE TITLE
[Bug]: Show Conversion on test networks is not working

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14569]
### Describe the bug

**Problem**: when I activate the function "Show Conversion on Test Networks" I am expecting to see the conversion to FIAT. Even though, this does not happen anymore.

Now:
![image](https://user-images.githubusercontent.com/54408225/165934745-ba3f2ac6-73f1-47e8-8362-9c2a5ef51f99.png)

Before (expected):
![image](https://user-images.githubusercontent.com/54408225/165934815-6a2116f5-1a51-4833-a4c1-af39b27bdee8.png)

### Steps to reproduce

1. Unlock Metamask
2. Import Test Networks
3. Change to a Testnetwork (i.e. Rinkeby)
4. Go to Settings Advanced
5. Activate "Show Conversion on Test Networks"
6. Close Settings

### Version

10.15.0

### Browser

Chrome, Firefox

### Operating system

Linux

**Comment by FrederikBolding** [comment]
Testnet assets aren't supposed to be worth anything. Is there a reason we want to show a fiat value anyway?

**Comment by seaona** [comment]
@FrederikBolding I do not have the complete history behind this feature, but it seems that it is intended to be there, as there is the switch for activating/deactivating. In the case we don't want to display fiat values in test networks, the switch on Settings should be removed.

![image](https://user-images.githubusercontent.com/54408225/165943454-8ce0d25a-5a66-44e2-af4b-ef8d1db0dd87.png)

For context: the switch has always worked until v10.15.0. It is in this version, that behaviour changed and switch does not work anymore.

**Comment by adonesky1** [comment]
Ultimately we should aim to get rid of this preference altogether by insuring that custom networks have a valid currency ticker associated. We started work toward that [here](https://github.com/MetaMask/metamask-extension/pull/12431), but have been waiting to gather metrics on how many users have custom networks added with no currency ticker, before adding a requirement that users add a currency symbol before they can use those networks again.  @Gudahtt

**Comment by adonesky1** [comment]
@brad-decker sorry I know I've asked this elsewhere before but do we have those metrics (indicating how often users have custom networks with no currency ticker) yet?

**Comment by Gudahtt** [comment]
That toggle was added so that we could test our mainnet designs on testnets, including the currency conversions. That need still exists and is not solved by any of the changes you referenced @adonesky1.

**Comment by adonesky1** [comment]
ah ok yes. I suppose we should preserve that functionality then. I will work on a fix.

**Comment by adonesky1** [comment]
So we want testnet `ETH` to have a fiat conversion rate equal to real `ETH` still then? @danjm @Gudahtt

**Comment by Gudahtt** [comment]
Yes. Either that or remove the toggle, if we don't think it's worth the effort.

I would have thought the e2e tests relied on this as well :thinking: I guess not if this got past CI.

**Comment by seaona** [comment]
I can add an e2e test for that @Gudahtt

**Comment by adonesky1** [comment]
There are a few different ways to handle this and here's one: https://github.com/MetaMask/controllers/pull/816 @Gudahtt

**Comment by FrederikBolding** [comment]
Just to be clear, this is not shown by default to the user right?
