### ISSUE TITLE
FE <> BE communication

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#14575]
- Lazy loading state
    - Segmenting app more
    - Reducing state size

**Comment by jpuri** [comment]
Here is a document with analysis of how we can improve BE <> FE communication related performance issues: https://docs.google.com/document/d/1vlQoBFVNtC4WhBdWPFhIIRTb3vJY-8GnOt4Hcv9BSw8/edit?usp=sharing

**Comment by jpuri** [comment]
Closing it as it is duplicated by epic: https://app.zenhub.com/workspaces/manifest-v3-626c1e431e6881001e89e430/issues/metamask/metamask-extension/14880
