### ISSUE TITLE
Download / Parsing time (bundle load time measuring)

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#14573]

**Comment by adonesky1** [comment]
@Gudahtt Could you explain how you see this helping mitigate performance issues? And @kumavis did you say something about having tried improvements in this vain without success?

**Comment by adonesky1** [comment]
@kumavis going to add tracing of bundle loading times

**Comment by Gudahtt** [comment]
Download/parsing accounts for a substantial amount of the initial load time of the extension. We can definitely reduce this by reducing the bundle size.

kumavis was probably looking into ways to parallelize and pre-load/parse the bundles like they would be if they were included as `<script>` tags. No idea whether that's possible, but that could help a lot as well.
