### ISSUE TITLE
Measuring performance inside the service worker

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#14574]

**Comment by adonesky1** [comment]
@kumavis have you made any progress on this? Do we need to reach out to Chrome and ask whether there is any tooling on this?

**Comment by adonesky1** [comment]
Get a video showing the issue : can't get performance tracing in service worker.

@kumavis meeting with google rep again today to discuss.

**Comment by jpuri** [comment]
The video has been shared with google team:

https://user-images.githubusercontent.com/2182307/167418320-821fd56c-f046-4418-bdd5-c582893f0429.mov

**Comment by jpuri** [comment]
We have reply from google team, they are looking into fixing this issue, there s not much we can do about this.

**Comment by naugtur** [comment]
Here's a detailed instruction on what to do about it:
https://www.notion.so/Measurement-b75b7c8682e1422e81a91e6956b454c3

**Comment by jpuri** [comment]
Moving this to done.

**Comment by hilvmason** [comment]
@jpuri do you think we are OK to fully close this issue?
