### ISSUE TITLE
[Bug]: ERC-721 approve calls loading infinitely

### ISSUE THREAD

**Issue by binzydev** [MetaMask/metamask-extension#14589]
### Describe the bug

Calling approve() for ERC-721 tokens causes the UI to infinitely load. Our game requires these NFT tokens to sign up, so our sign up flow is broken right now. This was reported April 27th, but could have been happening before that. Our code for this hasn't changed, and even bscscan isn't working. I confirmed v10.8.0 works.

This results in total service loss for new accounts (for any Pancake forks)

### Steps to reproduce

1. Go to https://bscscan.com/address/0x4596E527eBA13A27cd02576d023695eAB0A6b210#writeContract
2. Use approve() with to=`0x2C51b570B11dA6c0852aADD059402E390a936B39` and tokenId=`19238` (you don't need to own the token, anybody can reproduce)
3. Notice it's stuck infinitely loading

![image](https://user-images.githubusercontent.com/79776344/166170927-0c379d71-40b4-4c0f-8abc-29b484e2cad3.png)

### Version

10.12.4

### Browser

Chrome

### Operating system

MacOS

**Comment by testermumatstudio** [comment]
same here

**Comment by Anastacia-43** [comment]
HI @binzydev have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SU[PPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by Anastacia-43** [comment]
HI @Jens05 have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by Anastacia-43** [comment]
HI @binzydev  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by kevinghim** [comment]
Might be related to https://github.com/MetaMask/metamask-extension/issues/14459

**Comment by bschorchit** [comment]
@binzydev is this still happening? I tested now on 10.13 with a couple of different ERC721 and wasn't able to reproduce. Could you send it over to `0x8e411796cBc6a40D47eF1B81c871C7E7Fe522839` , if this is still an issue?

**Comment by bschorchit** [comment]
I was able to reproduce it. 
Info for others trying to reproduce this, you don't need to own the token to test it.

**Comment by binzydev** [comment]
Thanks @bschorchit 

Can we get a severity increase? It's likely a simple fix, and it's a total loss of service for us and there must be others

**Comment by fanz-emirarditi** [comment]
> Thanks @bschorchit
> 
> Can we get a severity increase? It's likely a simple fix, and it's a total loss of service for us and there must be others

It also causes severe loss of service for our project. It used to work on versions prior to 10.12.4

**Comment by charles-packer** [comment]
same here, major blocker for my project.

**Comment by alex38160** [comment]
See here for example bypass of this problem => https://github.com/MetaMask/metamask-extension/issues/14518

**Comment by binzydev** [comment]
@hilvmason @danjm @Gudahtt This is `Sev1-high` fellas

**Comment by binzydev** [comment]
Point me in the right direction and I'll try to get a PR in, but I've never touched the codebase so I'm kind of lost. I don't see `supportsInterface` calls for ERC721Metadata or know where in code this loading indicator would get stuck (can it have a timeout where it gives an option to close it?)

**Comment by Skyge** [comment]
Meet the same error for some ERC20 tokens, I think these token are a little different, the type of symbol and name are `bytes` rather than `string`, like [MKR](https://etherscan.io/address/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2#readContract), [DF](https://etherscan.io/address/0x431ad2ff6a9c365805ebad47ee021148d6f7dbe0#readContract)
It's really urgent！

**Comment by kevinghim** [comment]
This will be fixed via https://github.com/MetaMask/controllers/pull/834
