### ISSUE TITLE
[Bug]: Spinner does not spin

### ISSUE THREAD

**Issue by significance** [MetaMask/metamask-extension#14587]
### Describe the bug

Spinner does not spin when adding an account.

### Steps to reproduce

1. Add an account
2. Watch Spinner
3. Spinner does not spin

![Screenshot 2022-05-01 at 09 54 49](https://user-images.githubusercontent.com/130104/166137335-ef0d0fc7-5a3e-4710-85d6-d043640ca39f.png)

### Version

10.13.0

### Browser

Chrome

### Operating system

MacOS

**Comment by DONOVAN7493** [comment]
HI @significance  I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [Metamask Support](https://metamaskzendesk.helpsconnect.live/#)
