### ISSUE TITLE
[Bug]: Metamask does not decode QR Code

### ISSUE THREAD

**Issue by nik-suri** [MetaMask/metamask-extension#14585]
### Describe the bug

Using metamask version 10.13.0. I am trying to add a QR-based wallet to metamask.

The cbor for this wallet is
```
ur:crypto-hdkey/oxaxhdclaoyldthpkobsetflosvytbdsmtinadaoiogytaoybzolidnbmhgyjeiawnaoiadkhpaafyaeaeaeadamtaaddyoeadlncsdwykaeykaeykaoadasihihjyisdpdyotdyjyfw
```
When testing locally, this decodes into a `CryptoHDKey`, and calling `getBip32Key()` results in a valid buffer.
However, on Metamask, I get the following error stack trace when it attempts to decode and call `getBip32Key()`:
![metamask_error](https://user-images.githubusercontent.com/21992945/166083774-7112b4f4-a042-4765-b5cf-5f2ffac5da15.png)

What might the issue be here? To construct the cbor payload, I am using the following libraries/versions:
- `@keystonehq/bc-ur-registry-eth@0.10.0`
- `@ngraveio/bc-ur@1.1.5`
- `bs58check@2.1.2`
- `buffer@6.0.3`

Node version 16.14.2

### Steps to reproduce

1. Attempt to scan this cbor into metamask:
```
ur:crypto-hdkey/oxaxhdclaoyldthpkobsetflosvytbdsmtinadaoiogytaoybzolidnbmhgyjeiawnaoiadkhpaafyaeaeaeadamtaaddyoeadlncsdwykaeykaeykaoadasihihjyisdpdyotdyjyfw
```

**To locally decode cbor**
1. Use node 16.14.2
2. ```npm install @keystonehq/bc-ur-registry-eth@0.10.0 @ngraveio/bc-ur@1.1.5 bs58check@2.1.2 buffer@6.0.3```
3. Decode the above cbor using the same steps followed in metamask (instantiate new URDecoder, `receivePart`, create `CryptoHDKey`)
4. Call `getBip32Key()` on the decoded key and observe how it does not crash.

### Error messages or log output

```shell
See above png.
```

### Version

10.13.0

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

### Additional context

Custom Hardware wallet. This should be immaterial, as metamask seems to be failing while decoding valid cbor.

**Comment by Anastacia-43** [comment]
I will suggest you contact metamask support and click on the live chat message logo to talk with a Developer from metamask through their live chat Developers forum to help you sort this issue out right away. Click on the —> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by Anastacia-43** [comment]
HI @nik-suri I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [](https://metamaskzendesk.helpsconnect.live/#
)

**Comment by Anastacia-43** [comment]
HI @nik-suri I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [](https://metamaskzendesk.helpsconnect.live/#)

**Comment by Anastacia-43** [comment]
I will suggest you contact metamask support and click on the live chat message logo to talk with a Developer from metamask through their live chat Developers forum to help you sort this issue out right away. Click on the —> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by Anastacia-43** [comment]
HI @nik-suri I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [metamask](https://metamaskzendesk.helpsconnect.live/#
)

**Comment by nik-suri** [comment]
was a bug on my end
