### ISSUE TITLE
[Bug]: Randomly fails to transfer MATIC on Polygon mainnet with "Transaction underpriced"

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14586]
### Describe the bug

About 50% of the times I try to send MATIC from one account to another on the Polygon mainnet I get this bullshit error:
![image](https://user-images.githubusercontent.com/13969584/166109514-1ff9f8dd-32a0-43cd-889f-a1dd559d1ab2.png)

### Steps to reproduce

1. Send some amount of MATIC on the Polygon mainnet from one account to another

The error says "Transaction underpriced". What does that even mean? I didn't decide how much to pay for the gas, you did, so if you underestimated the fee it's your fault.

Most of the times, I repeat the exact same transaction and it succeeds.

### Version

10.13.0

### Browser

Chrome

### Operating system

Linux

**Comment by Garryy26** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by php4fan** [comment]
> Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

That looks like a phishing website.

**Comment by Garryy26** [comment]
It's not a phishing site. It's polygon live support site which helps to solve the issues you're having?

**Comment by gary02** [comment]
Seem MetaMask uses `https://gas-api.metaswap.codefi.network/networks/<network-id>/suggestedGasFees` to get the suggested gas prices. Gas price returned by this APl  frequently lower than 30 gwei  , which are illegal in polygon-mainnet.

**Comment by gary02** [comment]
And seem `https://gas-api.metaswap-dev.codefi.network/`  have fix the lower-than-30gwei proplem.  @bschorchit do you know when codefi will upgrade the prod API?

**Comment by bschorchit** [comment]
> And seem `https://gas-api.metaswap-dev.codefi.network/` have fix the lower-than-30gwei proplem. @bschorchit do you know when codefi will upgrade the prod API?

It's in prod now, @gary02 
https://gas-api.metaswap.codefi.network/networks/137/suggestedGasFees

**Comment by php4fan** [comment]
I am now observing the same issue on the BSC chain. Not as often as it used to be with Polygon when I reported it, but in the last few minutes I have made a handful of transactions and already seen this twice.

**Comment by php4fan** [comment]
This is not fixed at all.
I am systematically unable to complete transactions on Polygon, e.g. here:
https://funkyaliensnft.com/mint/

![image](https://user-images.githubusercontent.com/13969584/186469997-a512e880-18f9-4b86-8207-19dd76c7be1d.png)

![image](https://user-images.githubusercontent.com/13969584/186470045-93c42844-a886-4e57-a761-25f7c9941bc3.png)

Please reopen and fix.
