### ISSUE TITLE
[Bug]: Metamask hangs indefinitely when I try to send txes 

### ISSUE THREAD

**Issue by phaymond** [MetaMask/metamask-extension#14595]
### Describe the bug

This is the same issue as [3881](https://github.com/MetaMask/metamask-extension/issues/3881). It just started happening to me last night. 

Context: 

1. I uninstalled MetaMask and reinstalled it. Same problem. 
2. I'm on Chrome Version 101.0.4951.41, MetaMask 10.13.0 and MacOS 12.3.1. 
3. This happens with my Ledger Nano X. Ethereum version 1.9.18. Blind Signing is enabled. 

What's odd is that MetaMask swap works but not regular transactions. Does anyone know how to solve this? 

### Steps to reproduce

1. Go to https://matcha.xyz/ or https://app.uniswap.org/#/swap?chain=mainnet. 
2. Connect your MetaMask wallet and Ledger Nano X. 
3. Try to make a trade. 
4. When making a token approval, MetaMask just hangs forever with a spinning wheel. 

### Version

10.13.0

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by phaymond** [comment]
My workaround is to use Firefox. Would be great if this was resolved.

**Comment by Donovan94** [comment]
HI @phaymond  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by phaymond** [comment]
Thanks! The link doesn't work.

[image: image.png]

**Comment by phaymond** [comment]
Thanks! It works for me now for some reason. Not sure what was happening
before.
