### ISSUE TITLE
[Bug]: Circle missing on +/- symbol, and details of icons after expansion not visible

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#14597]
### Describe the bug

Probably caused by the recent design system update. Two issues within Activity History:

1. The expand `+/-` symbol is missing/now displaying a circle
2. The details of the icons on expansion state is not visible

Light mode:
![Screen Shot 2022-05-02 at 12 17 12 PM](https://user-images.githubusercontent.com/6951929/166270687-37cb7229-fa9a-4996-9ff1-b34d86ba30dc.png)

Dark mode: 
![Screen Shot 2022-05-02 at 12 17 35 PM](https://user-images.githubusercontent.com/6951929/166270835-371f2b40-5db1-4c85-97b9-eecf6d307730.png)

cc: @geor

### Steps to reproduce

1. go to Activity History
2. expand on an item

### Version

10.13.0

### Browser

Chrome

### Operating system

MacOS

**Comment by Donovan94** [comment]
HI @kevinghim have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)
