### ISSUE TITLE
[Error]: isValidDomainName(input) when input is an empty string

### ISSUE THREAD

**Issue by zheli-1** [MetaMask/metamask-extension#14599]
### Describe the bug

 isValidDomainName(input) when input is an empty string
  at componentDidUpdate (ui/app/pages/send/send-content/add-recipient/ens-input.component.js:76:18)
  at action (ui/app/store/actions.js:1223:5)
  at call (ui/index.js:132:11)
  at apply (app/scripts/ui.js:147:22)
...
(43 additional frame(s) were not displayed)

### Steps to reproduce

1. discover by jest unit test invoking on Change function with an empty string

### Version

10.8.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Linux

**Comment by Donovan94** [comment]
HI @Jens05 have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#
)

**Comment by Donovan94** [comment]
HI @zheli-1  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)
