### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kingway87** [MetaMask/metamask-extension#14603]
### Describe the bug

On evmos chain , trezor and metamask cant process with any sign transaction to claim the airdrop 
voting , stacking all cant 
https://evmos.disperze.network/validators/evmosvaloper1sp9frqwep52chwavv3xd776myy8gyyvkv5uysl

MetaMask Message Signature: Error: Firmware error.

### Steps to reproduce

not sure how 

### Version

10.13

### Browser

Chrome

### Operating system

MacOS

**Comment by Eloise74** [comment]
HI @Kingway87 I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)
