### ISSUE TITLE
[Bug]: MetaMask cannot connect with dydx (https://trade.dydx.exchange) in chrome extension and mozilla extention

### ISSUE THREAD

**Issue by oeawFebe** [MetaMask/metamask-extension#14609]
### Describe the bug

When you connect to dydx, you can connect wallet with dydx but cannot deposit USDC (it says the wallet is out of sync). I have tried both infura and local geth node and they are syncing.

### Steps to reproduce

1.go to https://trade.dydx.exchange
2. Use the current chrome or mozilla extension version of MetaMask (Ubuntu 20.04).
3. connect wallet with MetaMask
4. try to deposit some USDC

### Error messages or log output

```shell
Your account is out of sync. Please reconnect your wallet and try again.
```

### Version

10.12.4

### Browser

Firefox

### Operating system

Linux

**Comment by SC4RECOIN** [comment]
Have the same issue but not limited to the metamask wallet so looks to be dYdX related.
Did you find the issue?
