### ISSUE TITLE
Gas limit fixed

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#1460]
Hi,

In metamask, the user is now able to change the gas limit. While this is seems nice for the user at first, it can cause its transaction to fail. Usually the dapp is better placed to know the proper gas limit than the user itself.

We encounter such issue live where players got failed transaction because they lowered the gas limit.

Could metamask make it harder for the user to change it or even better give a warning ?

**Comment by kumavis** [comment]
we're going to hide it under and advanced tab
