### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by okzekzek** [MetaMask/metamask-extension#14600]
### Describe the bug

Hello, wehn i put my secret prhase in metamask , did't let me confirm it..
Can you help me to resolve it. Thanks!

### Steps to reproduce

1.

### Version

10.13.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

### Additional context

Is the first time i tried to create my wallet

**Comment by Eloise74** [comment]
HI @okzekzek i suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. https://metamaskzendesk.helpsconnect.live/#

**Comment by bschorchit** [comment]
Please reach out to our support to get help with this: https://metamask.zendesk.com/hc/en-us/

Friendly reminder that we will never ask for your Secret Recovery Phrase. Do never share it.
