### ISSUE TITLE
[Bug]: Message copy on transaction screen doesn't behave properly when scrolling down 

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#14602]
### Describe the bug

See video below

### Steps to reproduce

1. Get requested a transaction with the warning message "Network is busy"
2. Scroll down the screen and notice how to copy stays on top of other components

### Version

10.14

### Browser

Brave

### Operating system

MacOS

### Additional context

https://user-images.githubusercontent.com/34968356/166461754-9f46b1ca-5334-427f-832d-31a14a979dae.mov

**Comment by Donovan94** [comment]
Hi @bschorchit  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> https://metamaskzendesk.helpsconnect.live/#
