### ISSUE TITLE
[Bug]: Ledger users cannot confirm a transaction while on the Data/Hex tab

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14632]
### Describe the bug

The `Confirm` button on the confirmation screen is disabled once the user switches to the `Data`/`Hex` tab.
The user has to switch back to the details tab in order to  confirm the transaction

https://user-images.githubusercontent.com/53189696/167123862-fecd27d0-d1db-4e62-8040-f1f1f5634b35.mov

### Steps to reproduce

1. Connect a Ledger hardware wallet
2. Navigate to https://app.uniswap.org/#/swap
3. Swap a token
4. Switch to either the `Data`/`Hex` tab

### Version

10.14.0

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by Anouk1973** [comment]
Is there anything left i put 250 euro in it

Op zo 31 dec. 2023 17:06 schreef github-actions[bot] <
***@***.***>:
