### ISSUE TITLE
Support for Ledger Nano X through Web Bluetooth API

### ISSUE THREAD

**Issue by anon238** [MetaMask/metamask-extension#14645]
### Describe the bug

I think it's time to support this. All major browsers on the latest version are already supporting this, but y'all still lacking development on this area. 

https://developers.ledger.com/docs/transport/web-bluetooth/

### Steps to reproduce

n/a

### Version

10.10.2

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Windows, MacOS, Linux

### Hardware wallet

Ledger

**Comment by AlexJupiter** [comment]
Hi @anon238 thanks for raising this, however this is very unlikely to happen anytime soon. Our WebHID integration is very stable and efficient for Ledger devices and offering a new bluetooth protocol for connecting a Ledger would be very labor intensive for us. Also, not all Ledger devices even have bluetooth connectivity. That said, we could welcome community contributions on this topic.

**Comment by anon238** [comment]
Very labor intensive for you? You made billions and you can’t even support the latest Ledger devices over Bluetooth. I hope some other company takes user feedback serious and will create this. If this dude can do it alone. Why couldn’t you that? Hire some real devs. 

https://github.com/fsjuhl/LedgerBluetoothBridgeExtension

**Comment by AlexJupiter** [comment]
Thanks for the link! And feel free to apply for the job openings on our website :). https://consensys.net/careers/

**Comment by tomasz90** [comment]
Why this was closed??? Ledger presented two new types of wallets both have bluetooth functionalities... Ledger is the leader of hardware wallets, this is really a shame that you don't want to implement bluetooth connection...
