### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lechatoxfu3039** [MetaMask/metamask-extension#14640]
### Describe the bug

Bonjour je suis sur mobile et je cherche une extension car je suis white liste et ça écris no Metamask,j ai 72h pour acheter le Nft a un prix intéressant. Help me plesae.

### Steps to reproduce

1.

### Error messages or log output

```shell
Please instal Metamask
```

### Version

Android

### Build type

Beta

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Ledger

### Additional context

Faut plus d outils pour les téléphones mobiles, on peut pas avoir notre pc toute la journée avec nous.

**Comment by bschorchit** [comment]
Hey @lechatoxfu3039, you can download MetaMask on your phone. 
Here's our [official website](https://metamask.io/). If you need any more help, reach out to support within your app or through the website link.
