### ISSUE TITLE
Hello i bought aragon tokens but can not see the on https://wallet.ethereum.org/contracts

### ISSUE THREAD

**Issue by greedmans** [MetaMask/metamask-extension#1466]
Hello i bought aragon tokens but can not see the on https://wallet.ethereum.org/contracts even if i enter the token adress, but three day ago i could see them.
But on https://etherscan.io there is everything normal and i can see that i have them. What to do?

**Comment by flyswatter** [comment]
You're on the main network? https://github.com/MetaMask/faq/blob/master/README.md

**Comment by greedmans** [comment]
yes

**Comment by flyswatter** [comment]
We need a lot more details about what happened.

 Did you buy the tokens with MetaMask? 

 Did you buy them with the same account that you are connecting to Ethereum wallet with? 

 Do you have the correct account selected in metamask? 

 Can you see the correct account address in the history in the Ethereum wallet app?

**Comment by greedmans** [comment]
Yes i bought Aragon with MetaMask.
Yes i bought them with the same account that are connecting to Ethereum wallet
Yes i have the correct acount selected in MetaMask
Yes i can see the correct acount adress in the history in the Ethereum wallet

**Comment by tmashuang** [comment]
Closing old issues. If displaying tokens is still an issue, please email support@metamask.io with your state logs to better understand your particular issue.
