### ISSUE TITLE
when clicking on your address, expand to see the entire address

### ISSUE THREAD

**Issue by wanderer** [MetaMask/metamask-extension#1467]
It would be nice to see the entire address, when clicking on it or selecting it.

**Comment by Zanibas** [comment]
This is deprecated now that we're on the new UI

**Comment by danfinlay** [comment]
(Fixed in new UI): 
![screen shot 2018-03-01 at 3 55 37 pm](https://user-images.githubusercontent.com/542863/36876271-073dea92-1d69-11e8-800b-02ec2c1fced6.png)
