### ISSUE TITLE
Snap "See details" can navigate to the wrong view

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/metamask-extension#14687]
I accidentally installed a snap with a hash fragment in the URL and when I navigate to "See details" for the snap it shows the wrong view.

I am not certain that the hash fragment is triggering the problem but have a hunch that is the issue, maybe `encodeURIComponent` is needed somewhere.

First screenshot shows the installed snap and the second shows the view I was presented with after clicking "See details":

<img width="357" alt="local-snap-with-hash-in-url" src="https://user-images.githubusercontent.com/238069/163136184-cadfec3b-f939-4582-a38d-4786a1040554.png">
<img width="348" alt="snap-view-after-clicking-see-details" src="https://user-images.githubusercontent.com/238069/163136341-23b8d8e4-6f28-4fb9-9a7f-8d97fa6b4a6d.png">

This meant I could not uninstall the snap which I worked around be uninstalling and re-installing Flask.

**Comment by FrederikBolding** [comment]
@rekmarks We do encode them, but we also `unescape` them 🤔 https://github.com/MetaMask/metamask-extension/blob/e0e466490e92038318bc10f789046cabaf02ca40/ui/pages/settings/flask/snaps-list-tab/snap-list-tab.js#L28

**Comment by rekmarks** [comment]
Uh, that seems... bad? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape

**Comment by rekmarks** [comment]
@tmpfs this issue is going to be closed when #14693 is merged. Whether your specific bug is reproducible or not, we were not encoding the params correctly. Thanks for the report!
