### ISSUE TITLE
[Bug]: Switching accounts when sending an ERC20 token results in erroneous send state

### ISSUE THREAD

**Issue by brad-decker** [MetaMask/metamask-extension#14684]
### Describe the bug

If you are attempting to send a ERC20 token that you have a balance of on one account, and you switch accounts to an account that does not have a balance for that token (or the amount you are attempting to send) metamask is put into an erroneous state. This is because the extraReducer that runs on account change does not consider the possibility that an asset has been set. It should be noted that the "asset" field correctly reflects being switched back to ETH (see screenshots) but the value field does not. We should default back to the native currency (replace the asset object in state) when a user switches accounts. 

![image](https://user-images.githubusercontent.com/4448075/167726480-32dae720-5bab-4f61-9a95-117dcd7fa6d0.png)
![image](https://user-images.githubusercontent.com/4448075/167726594-b566c530-8863-49d2-84cd-cf4fb566e835.png)
![image](https://user-images.githubusercontent.com/4448075/167726733-43742021-ec57-4efa-a487-935d0c13ad92.png)

### Steps to reproduce

1. Select an account with a balance of a specific token
2. intiate a send for some non zero amount of that token
3. before clicking next, switch to an account that has less than the specified amount of specified token
4. click next.
5. see a confirmation window that shows sending the specified amount of specified token, regardless of balance.
6. confirm transaction, see that it fails on chain.

### Version

10.14.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

Linux

### Additional context

Occurs on develop branch, built using yarn start.

**Comment by bschorchit** [comment]
We don't want this to be closed :)

**Comment by bschorchit** [comment]
Similar to what we have done with networks, should we not allow users to switch accounts during the send flow?

**Comment by brad-decker** [comment]
Closed by #21264
