### ISSUE TITLE
[Bug]: Can't confirm transaction with ledger

### ISSUE THREAD

**Issue by olivierlesnicki** [MetaMask/metamask-extension#14703]
### Describe the bug

I can't confirm transactions with my Ledger anymore.
As soon as I press confirm, the extensions closes and an error is logged in the console:
```
code: -32603
message: "Please enable Blind signing or Contract data in the Ethereum app Settings"
```
However, Blind Signing is correctly enabled in the Ethereum app Settings.

### Steps to reproduce

1. Launch a transaction in MM from a dApp with a Ledger account
2. Review the transaction and press confirm

### Error messages or log output

```shell
code: -32603
message: "Please enable Blind signing or Contract data in the Ethereum app Settings"
```

### Version

10.14.3

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by gickyDEV** [comment]
Talk to Ledgerwallet Support on the [Live support chat](ledger-community.com) so that your issue can be looked into.
