### ISSUE TITLE
[Bug]: Metamask fails at gas estimation when trying to mint from ERC721 contract.

### ISSUE THREAD

**Issue by mihirmohan38** [MetaMask/metamask-extension#14709]
### Describe the bug

![telegram-cloud-photo-size-5-6339309675664749291-y](https://user-images.githubusercontent.com/52306226/168426105-b03e6a79-8ccc-4c0d-b1ec-fff80b2ddb91.jpg)

Hi guys,
Metamask fails at estimating gas when trying to mint from ERC721 Contracts. See image above ( VeeFriends NFT). This only happens with contract calls that require me to send eth in the contract call. At the time of writing gas is also reasonably low.

However when I run the same contract calls on the metamask-mobile , everything works as it should. This suggests to me its an issue with the extenstion.

You could try minting from the Azuki Contract ( didn’t find any current minting contracts) to see the error for yourself. [Azuki: AZUKI Token | Address 0xed5af388653567af2f388e6224dc7c4b3241c544 | Etherscan](https://etherscan.io/address/0xed5af388653567af2f388e6224dc7c4b3241c544#writeContract)

Can the core team help us with this.

### Steps to reproduce

1. Go to any ERC-721 contract. Here is the Azuki one. AZUKI Token | Address 0xed5af388653567af2f388e6224dc7c4b3241c544 | Etherscan](https://etherscan.io/address/0xed5af388653567af2f388e6224dc7c4b3241c544#writeContract)
2. Connect your metamask wallet 
3. Trigger allowlistMint() should be the first, with any argument (we used "1")
4. You should see the misestimation error on your metamask wallet signing page. 

### Error messages or log output

```shell
The error message was the following : 
We were not able to estimate gas. There might be an error in the contract and this transaction may fail.
```

### Version

10.14.3

### Browser

Chrome, Firefox, Brave

### Operating system

MacOS

**Comment by bschorchit** [comment]
Hey @mihirmohan38, thank you for your report. 
did you used the same account when testing this in mobile and extension? I wonder if this was caused because your account on extension was not part of the allowlist so the minting transaction would fail when submitted.

**Comment by alexbabo55** [comment]
Hello,I have the same issue. I created smart contract one year ago, and that time everything was working great . Now I decided to open mint stage and we receive the same error in metamask .Please help to resolve this issue .Very important for us.
![metamask](https://user-images.githubusercontent.com/87041092/190889968-84d9778f-e926-4594-947f-6c74cffbc494.jpg)
