### ISSUE TITLE
[Bug]: estimateGas sending null data field

### ISSUE THREAD

**Issue by allenluce** [MetaMask/metamask-extension#14708]
### Describe the bug

I'm seeing MetaMask send this on the wire:

    {"id":1267948436364,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x348556a44e71a328dba71479d1d6521b780398c7","value":"0xa012317b000","gasPrice":"0x3b9aca00","data":null,"to":"0x8888888888888888888888888888888888888888"}]}

Which the (1.8.27-stable) geth instance I'm using replies with:

    {"jsonrpc":"2.0","id":1267948436364,"error":{"code":-32602,"message":"invalid argument 0: json: cannot unmarshal non-string into Go struct field CallArgs.data of type hexutil.Bytes"}}

I can reproduce this error by hand and solve it by removing the `"data":null,` portion of the call.

### Steps to reproduce

1. Set up a working account on an Ethereum network
2. Click "send" (no need to actually send anything)

### Version

10.14.3

### Browser

Chrome

### Operating system

MacOS

**Comment by allenluce** [comment]
FYI, this results in MetaMask not retrieving the gas estimate and (at least in my case) underestimating the amount necessary. This caused the minters to accept the transaction but not process it (in anticipation of another call being made to up the gas price). While the under-gassed transaction was in the queue other transactions with appropriate gas amounts queued up behind it but weren't processed. Geth gave no indication that there was a problem with the gas amount.

**Comment by bschorchit** [comment]
This is a great candidate issue for help with triage @PeterYinusa

**Comment by bschorchit** [comment]
@seaona @sleepytanya once one of you has a chance (no rush), could you help me confirm if this is still an issue? Ty!

**Comment by sleepytanya** [comment]
@bschorchit That's what I get:
<img width="1081" alt="Screenshot 2023-09-04 at 11 38 41 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/6fb66124-23b9-458b-a59e-9b90a17217d9">
Nothing about estimateGas.
