### ISSUE TITLE
[Bug]: unable to determine contract std shows infinite spinning wheel

### ISSUE THREAD

**Issue by worldlyjohn** [MetaMask/metamask-extension#14712]
### Describe the bug

During a dapp contractInteraction (token approval), I get this error.
I'm unclear if it has to do with the contract itself or sentry, but it looks like we aren't handling the sentry error properly (perhaps we should try/catch and continue rather than halt the app like this?

![image](https://user-images.githubusercontent.com/211638/168517852-4a0627d5-8995-4db6-a80f-4fa29c0038cb.png)

### Steps to reproduce

1.Have MKR in your wallet (`0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2`)
2. Go to Zerion's Maker page
3. Attempt to sell some MKR for ETH
4. Zerion button turns to "Approve"
5. Click "Approve"

I see the spinning wheel and it never shows the Txn Approval Screen

### Error messages or log output

![image](https://user-images.githubusercontent.com/211638/168517868-6cd39b53-06ca-43e2-974d-a3d0e7760e69.png)

### Version

10.14.3

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Related to: https://github.com/MetaMask/metamask-extension/issues/14187

**Comment by NinjaTurtle007** [comment]
Here are more people having it with some somewhat useful reports
https://community.metamask.io/t/i-cant-send-just-the-mkr-token/19753/16

**Comment by Ophelia36** [comment]
HI @worldlyjohn  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue if its a metamask related issue. click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. [CLICK HERE](https://livechatmetasupport.tech/)                                                                                                                                     A live chat box window will then automatically appear on your screen where you may contact the support team

**Comment by bschorchit** [comment]
Closing this as [the fix](https://github.com/MetaMask/controllers/pull/830) has been merged. This should be fixed for users in one of our next releases.

**Comment by bschorchit** [comment]
Reopening this as we still need to create a new controller version and update the controller version being used on extension.

**Comment by bschorchit** [comment]
This will be done with: https://github.com/MetaMask/metamask-extension/issues/14891

**Comment by NinjaTurtle007** [comment]
So when we can expect release of a version that allows you to send MKR token?

**Comment by bschorchit** [comment]
This will be fixed in extension release v10.19 @NinjaTurtle007 
Closing this here as we're tracking it already here: https://github.com/MetaMask/metamask-extension/issues/14187
