### ISSUE TITLE
Urgent: Conflicting Issue with Rabby Wallet Extension

### ISSUE THREAD

**Issue by faxotherapy** [MetaMask/metamask-extension#14737]
### Describe the bug

Since installing the add-on [Rabby](https://rabby.io/) wallet from CoinTool, MetaMask can no longer connect to any dApp. MetaMask no longer responds when clicking on the “Connect Wallet” button from any dApp website. MetaMask somewhat becomes a “dead” extension. This is because of the Rabby wallet extension. It tooked me 2 hours to find the culprit. After uninstalling Rabby, MetaMask now works. I have reinstalled Rabby, and again MetaMask no longer connect to any dApp!

### Steps to reproduce

1. Install Rabby wallet extension.
2. You'll find MetaMask can no longer connect to ANY dApp afterwards.

### Error messages or log output

There's no error message. Clicking on the “Connect Wallet” button from a dApp site outputs absolutely nothing!

### Version

10.14.5

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by bschorchit** [comment]
Hey @faxotherapy, thank you for your report! This a known issue that we don't have a fix for yet. I'm closing this ticket as we're tracking this issue here: https://github.com/MetaMask/metamask-extension/issues/13622

**Comment by vvvvvv1vvvvvv** [comment]
@faxotherapy You can easily switch back to MetaMask by Flip
<img width="415" alt="image" src="https://user-images.githubusercontent.com/86296331/183556826-35ae0019-2c46-4c1d-8e84-51f3f646435e.png">

**Comment by hanniabu** [comment]
This appears to only be available when logged in, which is really annoying because my only other option is to uninstall the extension and reinstall every time.
