### ISSUE TITLE
Re-add ability to edit (L2) gas fee on Optimism transactions

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#14735]
### Describe the bug

In the recent updates to transaction confirmation screens, MetaMask combined L1+L2 gas fees shown to the user (thank you!)

This solved a problem where editing gas for a standard EOA transaction would cause the transaction to fail. However, for many contract account transactions (like multisig transactions) Optimism users often have to adjust L2 gas fees. Removing the ability to edit gas means many users can no longer submit multisig transactions.

We’d like to add the EDIT button back to confirmation screen for transactions on Optimism. This should open the standard gas edit screen, and changing gas price or limit should allow the user to edit their L2 gas. This calculation is done in the exact same way as on L1.

That edited L2 gas is then added to the L1 gas you’re already estimating, and the total is shown to the user on the confirmation screen.

It’s up to you if you want to display specific text on the EDIT screen to tell the user they’re editing only the L2 portion of their gas, but to get this up quickly we’d recommend just re-using your existing gas edit component.

cc @smartcontracts

### Version

10.14.3

### Browser

Chrome

### Operating system

MacOS

**Comment by kevinghim** [comment]
@bschorchit can we have the PS team look into this?

Previously, Optimism had an edit gas button, but it's been removed.
![optimism gas edit](https://user-images.githubusercontent.com/6951929/169401525-f16234f8-32cf-4b02-ac44-6a2e2fff4422.png)
