### ISSUE TITLE
[Bug]: Must click on website away from sign transaction on nft sites, then go back to metmask to have sign not greyed out

### ISSUE THREAD

**Issue by surfinthetao** [MetaMask/metamask-extension#14744]
### Describe the bug

You go to sign a transaction on an nft website (ive had issue on 3) assume it can be with other sites too, but when you scroll down to finally sign the transaction it is greyed out. the only way to sign is to click within the webpage, or on desktop, something that will let you away from the metmask screen momentarily, then you will see a blue 1 or whatever it is to let you know theres a signature waiting to be signed. clicking on the fox again, you can see the sign field, and when you scroll down on your mouse a little more, whether or not youre actually at the bottom of the field, youre finally able to sign the transaction (its not greyed out. sometimes it will say signing transaction failed when you click away though. it appears trying to use the multi list feature on looks rare results in the signing failing, but individual ones work.

### Steps to reproduce

1. Go to sign a transaction like youre listing an nft for sale
2. scroll down to bottom of info before signing
3. click away from metamask pop up screen
4. return to metamask, finish scrolling down even though youre all the way down with your center button on your mouse
5. finally sign it and finish the transaction.

### Version

10.14.3

### Build type

Beta

### Browser

Chrome

### Operating system

Windows

**Comment by kevinghim** [comment]
Could be related to https://github.com/MetaMask/metamask-extension/issues/14666

**Comment by bschorchit** [comment]
Thank you for your report! I'm closing this as we're tracking this in the above mentioned issue. We have a fix in progress.
