### ISSUE TITLE
[Bug]: If you click 'Confirm' right before the gas refresh, the transaction screen refreshes even though the user clicks confirm

### ISSUE THREAD

**Issue by addmorebass** [MetaMask/metamask-extension#14742]
### Describe the bug

If you click 'Confirm' right before the gas refresh, there is no way for the user to know that the screen is refreshing. It appears that you have to click Confirm twice in this scenario.

Not sure on the best solution here team. Maybe a pop-up that informs the user that the gas price changed and to confirm if they want to move forward?

### Steps to reproduce

1. Perform an on chain transaction
2. Click Confirm right before the gas price refreshes
3. Transaction doesn't confirm and the user has to click Confirm a second time

### Version

10.14.3

### Browser

Chrome

### Operating system

MacOS

**Comment by Jaycat66** [comment]
I'm trying to figure it out
