### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LennyBPunkt** [MetaMask/metamask-extension#14759]
### Describe the bug

Maybe I found a bug: 0 amount was sent, but in MetaMask Extension it shows the right amount in history.

![image](https://user-images.githubusercontent.com/105984529/169659861-fd5346d0-a9a9-489a-a61d-0c65f8a72a49.png)

Here you see the amount 0: https://bscscan.com/tx/0xecff102a1e11f9aaab0f56c70d120246c14507a289326b6f4c7cf19aa8b75dda

### Steps to reproduce

1. I just tried it once

### Error messages or log output

```shell
no Error message
```

### Version

MetaMask-Version 10.14.6

### Browser

Chrome, Other (please elaborate in the "Additional Context" section)

### Operating system

Linux

### Additional context

Jusing Version 91.0.4650.0 (Offizieller Build) custom (64-Bit) of SRWare Iron

**Comment by LennyBPunkt** [comment]
Hi Barbara,

correct.

After submitting this issue, I tried it again, than it worked.

My suggestion is, the reason of 0 amount is related by changing the token right before sending in a special way, which I can't relay remember. It did this because I wanted to try sending multiple tokens in one transaction.

**Comment by bschorchit** [comment]
Thank you for the additional info, @LennyBPunkt ! We'll look into it.

**Comment by bschorchit** [comment]
@LennyBPunkt could you send your MetaMask state logs to our support team? That will help us troubleshoot this.
Here is more info on what are and how to get state logs: https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-to-download-state-logs

And you can click on the link within MetMask extension to reach out to support or use this link: https://metamask.zendesk.com/hc/en-us/ and click on "Start a conversation".

Thanks for the help!
cc: @AlexHerman1
