### ISSUE TITLE
[Bug]: JSON RPC "eth_accounts" method returns only the current selected address

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14753]
### Describe the bug

**Problem**: when I call the RPC method `eth_accounts` I am expecting to receive an array of my MM addresses, but I only get the current selected address instead.

I believe that is not okay, or at least that's my interpretation on the [RPC documentation](https://eth.wiki/json-rpc/API#eth_accounts) (could be wrong though).

### Steps to reproduce

1. Go to Metamask [API playground](https://metamask.github.io/api-playground/api-documentation/#eth_accounts) 
2. Click on eth_accounts / Try it Now
3. Paste the extension URL
4. Click Play button (Send request)

https://user-images.githubusercontent.com/54408225/169520385-776ee336-3ff8-4f32-8ac3-57172321c7dc.mp4

### Version

10.15.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
@rekmarks do you know if this behavior is intentional or indeed a bug? Asking it just to help triage this ticket.

**Comment by rekmarks** [comment]
This behavior is intentional. Closing in favor of #18515.
