### ISSUE TITLE
[Non-Prod Bug]:  GasTiming: should only accept string types

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#14764]
### Describe the bug

The GasTiming component should only accept its `maxFeePerGas` and `maxPriorityFeePerGas` params as string types.  Instead, it is currently accepting both number and string types. 

It is confirmed that it should only be accepting a string type based on this @typedef in `metamask-extension/ui/hooks/gasFeeInput/useGasFeeInputs.js`. 
```
/**
 * @typedef {Object} GasFeeInputReturnType
 * @property {DecGweiString} [maxFeePerGas] - the maxFeePerGas input value.
 * @property {DecGweiString} [maxPriorityFeePerGas] - the maxPriorityFeePerGas
 *  input value.
```

When GasTiming receives a number value it produces this warning in development: 
![image](https://user-images.githubusercontent.com/20778143/169933839-8ced9213-3095-41eb-b068-845d08fde3a2.png)

Something observed was this value starts as a string and then turns into a number type.
<img width="1680" alt="Screenshot 2022-05-12 at 8 06 41 PM" src="https://user-images.githubusercontent.com/20778143/168201814-e2ebb470-4f79-4332-bba7-1df97f788341.png">

### Steps to reproduce

1. Issue a transaction
2. Confirm GasTiming is working as expected
3. Observe the following errors shown in the screenshot above are not present with these changes

### Version

10.14.0

### Browser

Chrome

### Operating system

MacOS

### Additional context

This bug does not appear to affect production.

**Comment by digiwand** [comment]
See https://github.com/MetaMask/metamask-extension/pull/14837

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/14837
