### ISSUE TITLE
Sentry Error: Ledger device: UNKNOWN_ERROR 

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14766]
### Describe the bug

**Problem**: we are logging this Sentry error when Ledger is outside Ethereum app and we click on Connect a Hardware wallet.

**Context**: this is a Sentry issue that appears merged into [another issue](https://github.com/MetaMask/metamask-extension/issues/14471), but we have to work the fixes separate.

For this specific case, we should handle the error so it does not log on Sentry.

![image](https://user-images.githubusercontent.com/54408225/169993494-6c36f82e-b336-4bd9-b768-fd836c7dfe1d.png)

### Steps to reproduce

1. Connect Ledger
2. Unlock Ledger (stay outside Ethereum app)
3. Unlock MM
4. Go to Import Hardware Wallet
5. Click Connect Ledger

### Version

10.14.0

### Browser

Chrome

### Operating system

Linux

**Comment by luoquanquan** [comment]
same bug
