### ISSUE TITLE
[Bug]: Whitescreen on installation of Flask

### ISSUE THREAD

**Issue by bowensanders** [MetaMask/metamask-extension#14770]
### Describe the bug

When installing Flask, where the introduction to flask screen should, it shows a white screen instead. You can get to the correct screen on a reload. (see video below

Uploading Screen Recording 2022-05-24 at 9.08.40 AM.mov…

### Steps to reproduce

1. Remove any previous flask installation
2. Install local version of flask (unpacked)
3. watch the above event unfold

### Error messages or log output

```shell
from background.html: 
Setting up Sentry Remote Error Reporting for 'production-flask': SENTRY_DSN
sentry-install.js:1 Removing intrinsics.Object.hasOwn
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.findLast
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.findLastIndex
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLast
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
2sentry-install.js:1 missing dep: bn.js requested buffer
(anonymous) @ sentry-install.js:1
sentry-install.js:1 LavaMoat: ignoring write attempt to read-access global "XMLHttpRequest"
(anonymous) @ sentry-install.js:1
5sentry-install.js:1 missing dep: bn.js requested buffer
(anonymous) @ sentry-install.js:1
background-2.js:10 Invalid asm.js: Unexpected token
sentry-install.js:1 NetworkController - configureInfuraProvider mainnet
sentry-install.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 "update" listeners added. Use emitter.setMaxListeners() to increase limit.
(anonymous) @ sentry-install.js:1
sentry-install.js:1 MetaMask initialization complete.


From home.html:
Setting up Sentry Remote Error Reporting for 'production-flask': SENTRY_DSN
sentry-install.js:1 Removing intrinsics.Object.hasOwn
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.findLast
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.findLastIndex
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
sentry-install.js:1 Removing intrinsics.%StringPrototype%.at
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLast
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
home.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

### Version

10.14.7-flask.0

### Browser

Chrome

### Operating system

MacOS

**Comment by rekmarks** [comment]
@bowensanders was this for `yarn start` or `yarn dist`?

**Comment by bowensanders** [comment]
Well things have changed now, you get a new error page when installing the `yarn dist --build-type flask`

https://user-images.githubusercontent.com/27023908/174219566-e5ae0287-b5ca-4659-b864-e00a2c4ece8a.mov

which is unlike what you get when you install the regular metamask:

https://user-images.githubusercontent.com/27023908/174219604-f29ae652-2684-4266-89a6-058cee60f427.mov

and if you do a `yarn start --build-type flask` you actually have to show and then click the fox to get in, it doesn't just pop up

https://user-images.githubusercontent.com/27023908/174219691-0f2d9bed-dd7b-45e6-b06e-26ca6fcd82ee.mov

So this probably helps to confuse the issue more? 🤷

**Comment by bowensanders** [comment]
It looks like the whitescreen of death was fixed with this https://github.com/MetaMask/metamask-extension/pull/14972

though i'm not sure why flask isn't auto-starting the welcome purple screen

**Comment by rekmarks** [comment]
As @bowensanders mentioned, #14972 appears to have fixed this issue, which has not occurred on `develop` for a long time. Therefore, I will now close this issue.
