### ISSUE TITLE
[Bug]: metamask shows ether which I don’t own 

### ISSUE THREAD

**Issue by rajaathota72-fc** [MetaMask/metamask-extension#14775]
### Describe the bug

![CA537B88-5D78-486B-AA4F-3C689E6D720E](https://user-images.githubusercontent.com/57040106/170253028-57e6d260-8407-43b8-b497-7f32e5f78c2b.jpeg)
 It shows ether which I don’t own and we are planning to build a risk analysis tool to fetch token holdings and calculate risk and if this happens the risk evaluation would be wrong ! 

### Steps to reproduce

1.

### Version

10.14.6

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Hey @rajaathota72-fc , thank you for your report! Can you check if you're facing this same issue described here https://github.com/MetaMask/metamask-extension/issues/12495 ?
Thank you!
