### ISSUE TITLE
Visual bug of name the coin [Bug]: 

### ISSUE THREAD

**Issue by Antikrizisss** [MetaMask/metamask-extension#14776]
### Describe the bug

![изображение](https://user-images.githubusercontent.com/78258378/170273638-c8cdf84e-ed91-49f3-b93d-e64663390b1d.png)
Visually shows matic instead of BNB

### Steps to reproduce

1.
Log in on the corite . com
It was proposed switch on Smart Chain and I accept (previous was Polygon mainnet) and then my BNB visually shows as Matic
![изображение](https://user-images.githubusercontent.com/78258378/170274595-8d7ad0ed-0c9f-4c8a-ab53-b2323fed1ce0.png)

### Version

10.12.4

### Browser

Firefox

### Operating system

Windows

**Comment by bschorchit** [comment]
Thank you for the report @Antikrizisss! Could you share the network details (chain id, rpc url and symbol) for this network? 
You can find this info by going to Settings > Network > Smart Chain. Thank you! This is help us understand what might be happening.

**Comment by Antikrizisss** [comment]
Smart Chain
https://bsc-dataseed.binance.org/
56
BNB

**Comment by bschorchit** [comment]
Thanks, @Antikrizisss. We might have a fix for it (PR https://github.com/MetaMask/metamask-extension/pull/14354 ) being released in 10.17.0.

**Comment by bschorchit** [comment]
Closing as fixed
