### ISSUE TITLE
code: -32016, MetaMask doesn't Popup 

### ISSUE THREAD

**Issue by adeojoemmanuel** [MetaMask/metamask-extension#14797]
### Describe the bug

metamask doesnt popup and shows error 

``` MetaMask - RPC Error: The execution failed due to an exception. {code: -32016, message: 'The execution failed due to an exception.', data: 'Reverted'} ```

### Steps to reproduce

1.  after initializing web3 connection 
2. const transaction = await contract.stake(address, _amount.toBigNumber(), shouldRebase, claim);

### Error messages or log output

```shell
MetaMask - RPC Error: The execution failed due to an exception. {code: -32016, message: 'The execution failed due to an exception.', data: 'Reverted'}
```

### Version

10.14.6

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by BelfordZ** [comment]
looks like you are getting an error from the smart contract. Check the smart contract code, or make sure the parameters you are passing are of the correct types / values.
