### ISSUE TITLE
Display address as ERC-67

### ISSUE THREAD

**Issue by ligi** [MetaMask/metamask-extension#1479]
Currently when showing the barcode for the account metamask displays the raw hex string. But it would be good if context is supplied via e.g. ERC-67 (https://github.com/ethereum/EIPs/issues/67)

![metamask](https://cloud.githubusercontent.com/assets/111600/26375783/877ab0ec-400a-11e7-824d-8ee4d4bd5e85.png)

one concrete use-case. On android you would currently have to go in the app and then scan. This way we can use intent-filters to scan with any app and then redirect to the right one.
Also as it is in the same screen (let me know if I should open an new issue for this) - the clipboard button is quite prominent and gives no warning - but this is risky thing - the same thing applies for metamask usage on PC as this problem on android: https://github.com/walleth/walleth/issues/14

**Comment by ligi** [comment]
Just tried it out - is ERC-67 now - thanks!

**Comment by kumavis** [comment]
sorry we forgot to update this ticket
thanks for filing the issue!
