### ISSUE TITLE
[Bug]: Metamask browser add-on not working

### ISSUE THREAD

**Issue by Anon797** [MetaMask/metamask-extension#14806]
### Describe the bug

Metamask browser add-on not working properly. I now get no popup when I try to connect to any site. Also, the browser appears as if I don't have MM installed. 
Uniswap
![image](https://user-images.githubusercontent.com/35376902/171236074-bbeda62b-2583-415b-a26e-5c1f65738a97.png)
Zed Run - When I click switch network, nothing happens.
![image](https://user-images.githubusercontent.com/35376902/171236478-f7d3a715-213e-4228-bfab-bcbf79f2362e.png)

I have cleared the cache and history and restarted the browser. 

### Steps to reproduce

1. Go to uniswap app site (or any site to connect MM wallet)
2. click connect a wallet

### Version

10.14.6

### Browser

Chrome

### Operating system

Windows

**Comment by bitcoin10up** [comment]
Zerion - Something went wrong and the address could not be added
![image](https://user-images.githubusercontent.com/35376902/171254265-a05c92ac-9694-4911-b4e2-f6b58504570e.png)

**Comment by danjm** [comment]
Do you happen to have two instances of MetaMask installed?

**Comment by bitcoin10up** [comment]
> Do you happen to have two instances of MetaMask installed?

or not that I know of. How can you tell?
