### ISSUE TITLE
[Bug]: Warning - Failed prop type: Invalid prop min of type string supplied to TextField, expected number.

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14814]
### Describe the bug

**Problem**: when I activate the option Customize Transaction Nonce, and I'm on the confirmation screen of the transaction, the following Warning appears `Failed prop type: Invalid prop min of type string supplied to TextField, expected number.`

![image](https://user-images.githubusercontent.com/54408225/171352476-d0013568-a000-48b0-9ca2-f047f68b7eee.png)

### Steps to reproduce

1. Unlock Metamask
2. Click Settings // Advanced
3. Activate Customize Tx Nonce option
4. Click Send ETH
5. Introduce amount and receiver and go to next screen
6. Check console

### Version

10.14.6

### Browser

Firefox

### Operating system

Linux

**Comment by NamHuynhHoang** [comment]
Ban can cap nhat phien ban wer dung cau hinh duyet wer

Vào 14:39, T.4, 1 Th6, 2022 seaona ***@***.***> đã viết:

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/14837
