### ISSUE TITLE
[Bug]: Warning - Failed prop type: The prop to is marked as required in TransactionDecoding, but its value is undefined.

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14817]
### Describe the bug

**Problem**: when I deploy a Contract and click on the Contrat Deployment tx details, I see this one: `Failed prop type: The prop to is marked as required in TransactionDecoding, but its value is undefined`.

![image](https://user-images.githubusercontent.com/54408225/171354370-f5e9e2a6-dcb8-4874-a931-8b946d7141c8.png)

### Steps to reproduce

1. Unlock Metamask
2. Select Rinkeby Network
3. Go to [E2e Test Dapp](https://metamask.github.io/test-dapp/)
4. Connect Metamask
5. Click Deploy Contract and accept tx
6. Click on Tx details
7. Check the console

### Version

10.14.6

### Browser

Firefox

### Operating system

Linux

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/14837
