### ISSUE TITLE
[Bug]: Warning - Failed prop type: Invalid prop `maxFeePerGas` of type `number` supplied to `GasTiming`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14815]
### Describe the bug

**Problem**: on a failed tx, if I click retry having the Advanced Gas Controls and Enhanced Gas Fee UI enabled on Settings, I see the following Warning `Failed prop type: Invalid prop `maxFeePerGas` of type `number` supplied to `GasTiming` expected string`

https://user-images.githubusercontent.com/54408225/171352870-c203b135-707f-4408-a5de-9715cf308c2e.mp4

### Steps to reproduce

1. Unlock Metamask
2. Send a failed Tx
3. Click tx details
4. Click Retry tx button
5. Check console

### Version

10.14.6

### Browser

Firefox

### Operating system

Linux

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/14837
