### ISSUE TITLE
[Bug]: MetaMask.IO

### ISSUE THREAD

**Issue by TokensDL** [MetaMask/metamask-extension#14818]
### Describe the bug

0x00FeCC0C75cb5fa4B3c874DFFF8Ce99cfB7EEdb5

### Steps to reproduce

1.
0x00FeCC0C75cb5fa4B3c874DFFF8Ce99cfB7EEdb5

### Error messages or log output

```shell
trandailoc67@gmail.com
0x00FeCC0C75cb5fa4B3c874DFFF8Ce99cfB7EEdb5
```

### Version

NFT 1.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

Keystone

### Additional context

0x00FeCC0C75cb5fa4B3c874DFFF8Ce99cfB7EEdb5 context trandailoc67@gmail.com.vn

**Comment by TokensDL** [comment]
> ### Describe the bug
> 0x00FeCC0C75cb5fa4B3c874DFFF8Ce99cfB7EEdb5
> 
> ### Steps to reproduce
> 
> 0x00FeCC0C75cb5fa4B3c874DFFF8Ce99cfB7EEdb5
> 
> ### Error messages or log output
> ```shell
> trandailoc67@gmail.com
> 0x00FeCC0C75cb5fa4B3c874DFFF8Ce99cfB7EEdb5
> ```
> 
> ### Version
> NFT 1.0
> 
> ### Build type
> Other (please specify exactly where you obtained this build in "Additional Context" section)
> 
> ### Browser
> Other (please elaborate in the "Additional Context" section)
> 
> ### Operating system
> Other (please elaborate in the "Additional Context" section)
> 
> ### Hardware wallet
> Keystone
> 
> ### Additional context
> 0x00FeCC0C75cb5fa4B3c874DFFF8Ce99cfB7EEdb5 context [trandailoc67@gmail.com.vn](mailto:trandailoc67@gmail.com.vn)

**Comment by TokensDL** [comment]
Thanks You! Report

**Comment by TokensDL** [comment]
TokensDL IIME

**Comment by bschorchit** [comment]
Hey @TokensDL , do you have a bug to report?
