### ISSUE TITLE
[Bug]: Warning - Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14813]
### Describe the bug

**Problem**: when I try to send an ERC20 token (LINK), if I click on DATA on the confirmation page, a new Warning appears saying Each child in a list should have a unique "key" prop. You can use the following links for reproing this:

- Token Contract on Rinkeby: https://rinkeby.etherscan.io/token/0x01BE23585060835E02B77ef475b0Cc51aA1e0709
- LINK Faucet for Rinkeby: https://faucets.chain.link/

![image](https://user-images.githubusercontent.com/54408225/171351973-faf210f3-2cb3-4733-88fa-38f3ffaeac00.png)

### Steps to reproduce

1. Unlock Metamask
2. Import [LINK token ](https://rinkeby.etherscan.io/token/0x01BE23585060835E02B77ef475b0Cc51aA1e0709)
3. Ask for LINK token on the [faucet](https://faucets.chain.link/)
4. Click Send LINK
5. Click on the Data tab
6. Check console

### Version

10.14.6

### Browser

Firefox

### Operating system

Linux

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/14837
