### ISSUE TITLE
[Bug]: Warning - Failed prop type: The prop addNewNetwork is marked as required in NetworksFormSubheader, but its value is undefined.

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14816]
### Describe the bug

**Problem**: When I go to Settings / Networks, I see the warning` Failed prop type: The prop addNewNetwork is marked as required in NetworksFormSubheader, but its value is undefined`.

![image](https://user-images.githubusercontent.com/54408225/171353502-64a0d823-3335-43c8-ac1b-27f73aa89cd1.png)

### Steps to reproduce

1. Unlock Metamask
2. Go to Settings
3. Got to Networks
4. Check console

### Version

10.14.6

### Browser

Firefox

### Operating system

Linux

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/14837
