### ISSUE TITLE
[Bug]: Warning - Failed prop type: onRemove and onViewTokenDetails

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14825]
### Describe the bug

**Problem**: when initiating Metamask for the first time, and clicking on ETH asset, we trigger the following warnings:
- `Warning: Failed prop type: The prop onRemove is marked as required in AssetOptions, but its value is undefined`
- `Warning: Failed prop type: The prop onViewTokenDetails is marked as required in AssetOptions, but its value is undefined`

https://user-images.githubusercontent.com/54408225/171581467-bd9f2e3e-2ceb-4176-8f91-de2b47ce34fe.mp4

### Steps to reproduce

1. Import Metamask on your browser
2. Start a new Wallet
3. Click on ETH Asset
4. Check console

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/14837
