### ISSUE TITLE
[Bug]: Warning - Failed prop type: Invalid prop `maxPriorityFee` and `maxFee` of type `string` supplied to `AdvancedGasControls`, expected `number`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14828]
### Describe the bug

**Problem**: when opening advance gas fee edit screen we can see these 2 warning errors in the console:
- [Bug]: Warning - Failed prop type: Invalid prop `maxPriorityFee` of type `string` supplied to `AdvancedGasControls`, expected `number`
- [Bug]: Warning - Failed prop type: Invalid prop `maxFee` of type `string` supplied to `AdvancedGasControls`, expected `number`

https://user-images.githubusercontent.com/54408225/171584195-5f30eb06-db1c-4632-8f08-a45c4f306905.mp4

### Steps to reproduce

1. Unlock Metamask
2. Click Send ETH
3. Introduce amount and receiver address and proceed
4. Click Edit gas fees
5. Click Advanced Options
6. Check console

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/14837
