### ISSUE TITLE
[Bug]: When Language is not English, I land on the wrong tab when I've performed a tx

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14830]
### Describe the bug

**Problem**: when I have set a language which is not English, after performing a transaction I land in the Home page with the Assets tab open, while when I have English language selected, I land on the Activity tab so I can see the recent transaction performed.

https://user-images.githubusercontent.com/54408225/171588706-df4721c3-1d7f-4c65-bdc8-55831bbc63a3.mp4

Suggested Solution: when I'm using other languages, I should also land into the Home/Activity tab after performing a transaction, in the same way it is done when having English language selected.

### Steps to reproduce

1. Unlock Metamask
2. Go to Settings
3. Change language to another different than English
4. Perform a transaction
5. Notice that you land on the Home/Assets page instead of Home/Activity page

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
Some details on the cause of this:

The tab that is selected is based on the `defaultHomeActiveTabName` prop in `home.component.js`. If this prop, which is a string, matches the label of the tab, then that tab will be selected. You can see where this prop is passed to the Tabs component here: https://github.com/MetaMask/metamask-extension/blob/develop/ui/pages/home/home.component.js#L616

The `setDefaultHomeActiveTabName` action creator is called to set that prop. If that was ever called with a string that didn't match the current languages translation for "Activity", then the "Assets" tab would be selected by default.

Searching the codebase for "setDefaultHomeActiveTabName" shows a few places where the string `'Activity'` is passed to `setDefaultHomeActiveTabName`. Instead we should pass the translation of "Activity".

Our translation system works by putting a method `t()` on the context of our react components. So in class components, we can call `this.context.t('someString')` and as long as `'someString'` matches one of the keys in the file https://github.com/MetaMask/metamask-extension/blob/develop/app/_locales/en/messages.json, then `this.context.t('someString')` will return the translated version of that string for the users currently selected language. In functional components, we need to create the t method by using hooks: `const t = useContext(I18nContext);`

To fix this bugs, we need to find the instances of `setDefaultHomeActiveTabName('Activity')` and replace them with `setDefaultHomeActiveTabName(this.context.t('activity'))` / `setDefaultHomeActiveTabName(t('activity'))`
