### ISSUE TITLE
MV3: Make injection of inpage.js on dapps synchronous

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#14846]
In MV3 ethereum api injection is asynchronous and late. Se discussion here: https://github.com/MetaMask/metamask-extension/pull/14762#discussion_r880793784

We need to fix this to make it synchronous.

**Comment by darkwing** [comment]
Note: I did some quick research and the `web_accessible_resources` key of the manifest will need to become an array:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources#manifest_v3_syntax

**Comment by darkwing** [comment]
Per this comment: https://bugs.chromium.org/p/chromium/issues/detail?id=634381#c39, the `world` field has been added as of Chrome v102.  It was unclear to me if it's possible to add this new field via manifest.json, so I've asked here:

https://bugs.chromium.org/p/chromium/issues/detail?id=634381#c40

In the mean time, I have a branch that would implement that version instead: https://github.com/MetaMask/metamask-extension/tree/mv3-inject-sync-updated

**Comment by jpuri** [comment]
Hey @darkwing : the branch looks good. Does it works with MV3, I am asking as MV3 chrome support is broken and many things detailed in docs are obsolete.
