### ISSUE TITLE
[Bug]: TypeError: NetworkError when attempting to fetch resource._Last 30 Days: 18K (https://chainid.network/chains.json)

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#14852]
### Describe the bug

Sentry Issue: [METAMASK-4H74](https://sentry.io/organizations/metamask/issues/828905785/?referrer=github_integration)

This is a sibling issue of https://github.com/MetaMask/metamask-extension/issues/10557.

TypeError: NetworkError when attempting to fetch resource.
Last 30 Days: 17K

Specifically, this issue targets the NetworkError that happens from calling https://chainid.network/chains.json

<img width="1680" alt="Screenshot 2022-06-01 at 11 54 35 AM" src="https://user-images.githubusercontent.com/20778143/171913610-32841020-1ac1-4a1d-95f8-b53b6e4fcd17.png"> 

Example Event Links:
- https://sentry.io/organizations/metamask/issues/828905785/events/7e9b8a680456470a98e1fc6cc4750042/?project=273505&referrer=github_integration
- https://sentry.io/organizations/metamask/issues/828905785/events/db52b9c035a542a393902dfaf2a89e57/?project=273505&referrer=github_integration
- https://sentry.io/organizations/metamask/issues/828905785/events/oldest/?project=273505&referrer=github_integration

### Steps to reproduce

1. Open MM in FireFox
2. Open Networks dropdown
3. Click "Add Network"
4. Observe Browser console

### Version

10.14

### Browser

Firefox

### Operating system

MacOS

**Comment by aspiers** [comment]
Is this definitely fixed?  I see this in Chrome 113 with MetaMask 10.29.0:

![image](https://github.com/MetaMask/metamask-extension/assets/100738/4f97f597-a437-412d-961d-df2b2c757c9e)

I don't know if it's related, but at the same time [my MetaMask is completely unusable](https://github.com/MetaMask/metamask-extension/issues/19002#issuecomment-1544366925) :cry:
