### ISSUE TITLE
Onboarding V2 Metrics

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#14867]
We need to implement metrics tracking according to the schema below before releasing Onboarding V2
Onboarding v2 metrics definitions:
[Figma](https://www.figma.com/file/bhHrJDvh79zGE4LR6oc1gO/Extension-Mockup-with-MetaMetrics-Events-Overlay?node-id=354%3A7959)
[Unified metrics spreadsheet](https://docs.google.com/spreadsheets/d/1VlH6kp0syeb-XJILj5FRRnonk-XTILxJKCUvs1f9KqI/edit#gid=272971444)

**Comment by hilvmason** [comment]
@kevinghim can you please confirm that this is a blocker to releasing this work and closing the epic? thx

**Comment by hilvmason** [comment]
this issue requires refinement to get dev ready @danjm @adonesky1 @kevinghim

**Comment by kevinghim** [comment]
Closed via https://github.com/MetaMask/metamask-extension/pull/17090
