### ISSUE TITLE
[Bug]: Drag function on Secret Recovery Phrase Backup not working

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14862]
### Describe the bug

**Problem**:  I cannot drag successfully words for re-arranging the order of the Secret Recovery Phrase backup page.

See incorrect functionality (left side video) compared to the correct functionality (right side video)

https://user-images.githubusercontent.com/54408225/172146208-abf9fe7b-e81a-4741-b4fb-9f819ddc3ec1.mp4

**Note**: this is only happening on 10.15.0 with `yarn dist` build and **NOT** `yarn start`

### Steps to reproduce

1. Load MM 10.15.0
2. Create Account
3. Go to backup Seed Phrase
4. Add a couple of words
5. Try dragging words for re-arrangement

### Version

10.15.0

### Browser

Chrome, Firefox

### Operating system

Linux/Windows

**Comment by Ash1818** [comment]
Set to default new key
