### ISSUE TITLE
[Bug]: Cancelling or Speeding up Unconfirmed tx with Ledger causes to appear new tx entries undefined

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14876]
### Describe the bug

**Problem**: when I'm with a Ledger account and I have an unconfirmed tx (not signed on Ledger), everytime I try to Speed Up or Cancel the tx, I see a new tx entry appears with an undefined Tx Icon and Name 

https://user-images.githubusercontent.com/54408225/172341911-041f418f-4ac3-459a-ae6c-742e6881083c.mp4

 After a while, these tx's fail and they are also displayed without Icon/Name.

![grafik](https://user-images.githubusercontent.com/54408225/172362918-a901ffc1-3f3c-4ce0-b0d0-10382892989a.png)

### Steps to reproduce

1. Import a Ledger Account
2. Click Send ETH (i.e. on Rinkeby)
3. Don't confirm on Ledger (leave the tx prompt open) - MM will stay loading
4. Refresh Metamask (F5)
5. Lock Metamask
6. Unlock Metamask
7. Click Send ETH (on Rinkeby)
8. Don't confirm anything on Ledger - MM will stay loading
9. Refresh Metamask (F5)
10. Click Speed Up and Save - see new entry
11. Click Cancel and Save - see new entry
And now, everytime you click Cance/Speed Up a new tx entry will be generated with undefined Name and Icon

### Version

10.14.7

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
Some extra info on this bug: the part of undefined tx's types seems related to what we encountered with other Sentry errors on tx types (FYI @digiwand), but I think there is an extra bug on the flow itself (from the hardware wallet perspective @AlexJupiter ), as I'm not sure:
- whether it should be possible to generate a new Tx while having the first not confirmed on Ledger (this is only possible if I lock and unlock Metamask inbetween, if I don't do this step, I cannot generate a new Tx)
- whether new entries should be generated, instead of updating the current tx (as it's usually done with non-hardware wallet accounts)

**Comment by digiwand** [comment]
@seaona, is this still a bug? I am not seeing this on 10.15.0

**Comment by seaona** [comment]
@digiwand I believe it's still an issue. I'm seeing this on 10.16.0, following the exact repro steps. Both these grouping issue you are mentioning and the undefined types :/ mmm strange. I'm on Chrome+Linux.
Let me know if you cannot repro and I can assist

**Comment by seaona** [comment]
I've communicated this to HW team. Thank you v much @digiwand .
The issue @darkwing was mentioning about Ledger/Linux is another one, related to the new Hardware Connectivity flow: the connection pop-up appears inside MM notification view, which breaks the UI. This only happens in Linux and is not reproduceable in any other OS. So it looks like it's not related to this one

**Comment by woodydeck** [comment]
This is still a bug in 10.27.0. I get the Tx underpriced error, even going through the Tx flow on the device. It's the same for testnet and main. If it helps, the behavior my team tested is persistent across browsers, and even with Trust Wallet, which I assume is a fork of MetaMask.

Some of the facts:

1) Reseting the account doesn't solve the issue. You cannot transact if a Tx is stuck at all, it auto fails. You cannot cancel or resubmit the same Tx.

2) Initially speeding up prompts the proper dialogue, but the node never hits it.

3) We didn't experience this problem before the merge.

4) Going to MEW or MyCrypto allows us to cancel the stuck Tx with a custom nonce. This is the only way to recover!
