### ISSUE TITLE
[Bug]: Transaction decoding is not available for chainId 56

### ISSUE THREAD

**Issue by AlienegraGeek** [MetaMask/metamask-extension#14878]
### Describe the bug

I'm using Ehters 5.6 and Metamask-extension to send transaction on BSC

javascript code
`let providerBsc = new ethers.providers.Web3Provider(window.ethereum)`

![image](https://user-images.githubusercontent.com/33959579/172367011-9c1df662-4872-4472-9016-9ffbdf04caa7.png)
 

### Steps to reproduce

1.use Ehters 5.6 and Metamask-extension to send transaction

### Error messages or log output

```shell
Transaction decoding is not available for chainId 56
```

### Version

10.14.6

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Hey @AlienegraGeek , thank you for the report. This is not a bug. Our [transaction insights feature](https://metamask.zendesk.com/hc/en-us/articles/4412543412123-Transaction-Insight) is not available yet for this network, that's why we display this message.
