### ISSUE TITLE
[Bug]: Spend Limit Permission screen options only clickable on the dot (but not on the text option)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14883]
### Describe the bug

**Problem**: on the Spend Limit Permission screen, the 2 options for proposed or custom limit are not clickable on the text, and user must click on the dot for activating the desired option.

https://user-images.githubusercontent.com/54408225/172390722-86c649c7-3d29-4c26-9c2d-1fe1ae3150a9.mp4

**Solution**: we should aim for the same behavior as we have for example on the Settings page, where each option can be activated both by clicking the text or the dot.

### Steps to reproduce

1. Unlock Metamask
2. Change to Binance Chain (you can add it from [Chainlist](https://chainlist.org/))
3. Go to a vreified Binance Smart contract (i.e. [this](https://bscscan.com/address/0xf206ec6aac33806ce990826324c01f985302e28c#writeContract))
4. Click on approve method and introduce any address and amount
5. Check MM prompt

### Version

10.14.7

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This will be solved by this https://github.com/MetaMask/metamask-extension/issues/16623 which will make the new flow default (and the new flow doesn't have those dot options anymore)

**Comment by bschorchit** [comment]
Closing as no longer an issue
