### ISSUE TITLE
[Bug]: Error: No keyring found for the requested account. Error info: There are keyrings, but none match the address

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14897]
### Describe the bug

Using the `Forget this device` option causes issues if the Hardware device's account is still connected

### Steps to reproduce

1. Connect a hardware device
2. Add the account
3. Switch to the non hardware wallet account
4. Navigate the the connect hardware wallet screen
5. Forget the device
6. Navigate back to the extension home page
7. Switch back to the hardware wallet account
8. Attempt to send a transaction 
9. Attempt to remove the account

See video below for detail steps:
https://drive.google.com/file/d/17Bn0czB8yjjAlX9Ma45AmqtDSyh5mInB/view?usp=sharing

### Error messages or log output

```shell
`Attempt to send a transaction`
common-1.js:46 Uncaught (in promise) Error: No keyring found for the requested account. Error info: There are keyrings, but none match the address
  at common-1.js:46:38086
  at async Me.getAccountType (background-6.js:12:190873)
  at async K._buildEventFragmentProperties (background-2.js:1:350214)
  at async K._trackTransactionMetricsEvent (background-2.js:1:351968)

`Attempt to remove the account`
common-2.js:1 Uncaught (in promise) Error: No keyring found for the requested account. Error info: There are keyrings, but none match the address
  at common-1.js:46:38086
  at async Me.removeAccount (background-6.js:12:193880)
  at async s.<anonymous> (background-4.js:1:68290)
```

### Version

10.14.7

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger, Trezor

**Comment by kokoloko89** [comment]
Hi, this bug dont have solution?

**Comment by liubin595338764** [comment]
I encountered the same problem when using the Metamask app to make payments on an H5 website.

iPhone 11， ios:15.4.1, metamask app:v7.3.0(1144)
