### ISSUE TITLE
[Bug]: Error: 0x... can't be deleted cause it was not found

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14898]
### Describe the bug

Using the `Forget this device` option causes issues if the Hardware device's account is still connected

### Steps to reproduce

1. Connect a hardware device
2. Add the account
3. Switch to the non hardware wallet account
4. Navigate the the connect hardware wallet screen
5. Forget the device
6. Navigate back to the extension home page
7. Switch back to the hardware wallet account
8. Attempt to remove the account, `pressing the remove button twice`

See video below for detail steps:
https://drive.google.com/file/d/17Bn0czB8yjjAlX9Ma45AmqtDSyh5mInB/view?usp=sharing

### Error messages or log output

```shell
common-2.js:1 Uncaught (in promise) Error: 0xce5e17679d1d3a6babea43804b227a653b846dce can't be deleted cause it was not found
  at r.default.removeAddress (background-2.js:1:292819)
  at Me.removeAccount (background-6.js:12:193824)
  at s.<anonymous> (background-4.js:1:68307)
  at l (common-1.js:20:209306)
  at s.emit (common-1.js:20:212301)
  at w (common-7.js:1:19870)
  at v (common-7.js:1:19685)
  at b.push (common-7.js:1:20499)
  at t.exports._write (common-6.js:8:364063)
  at b (common-7.js:1:32915)
  at common-7.js:1:36099
  at y.write (common-7.js:1:36126)
  at e.exports.m (common-7.js:1:25070)
  at l (common-1.js:20:209306)
  at s.emit (common-1.js:20:212301)
  at w (common-7.js:1:19870)
  at v (common-7.js:1:19685)
  at b.push (common-7.js:1:20499)
  at e.exports._onMessage (common-3.js:10:14413)
  at common-3.js:10:14260
```

### Version

10.14.7

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger, Trezor

**Comment by seaona** [comment]
I encountered this in a different scenario, without using a hardware wallet.

**Repro:**
1. Create a new wallet
2. Do the onboarding
3. Log out
4. Click forgot password
5. Add another seed and proceed
6. See error in the background console

![Screenshot from 2023-10-18 10-29-28](https://github.com/MetaMask/metamask-extension/assets/54408225/ecbd3614-fa1e-4ded-a8a5-3c71a898ba31)

**Comment by dawnseeker8** [comment]
I have tested the latest Mobile extension version `11.7.5` and unable to replicate both issue described in this issue and in @seaona  comments. https://github.com/MetaMask/metamask-extension/issues/14898#issuecomment-1767951271

both case working fine without error, and account has successfully deleted in first `forget devices`

**Comment by angelcheung22** [comment]
@vivek-consensys  could you retry and see if can reproduce, it not pls help to close

**Comment by vivek-consensys** [comment]
unable to replicate, closing issue.
