### ISSUE TITLE
[Bug]: Previous button from Ledger Account List is active on first page (when there is no Previous page)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14896]
### Describe the bug

**Problem**: when we go to Import Ledger accounts, we now see that the PREV button is active when we are on the 1st page, and there is no previous page.

Clicking the button has no effect.

![grafik](https://user-images.githubusercontent.com/54408225/172596530-35d57d35-f7a1-48fe-bed3-6f4bf8ebd08e.png)

### Steps to reproduce

1. Unlock Metamask
2. Unfold Menu
3. Click Connect Hardware Wallet
4. Click Ledger and wait
5. See PREV button is active on the first page for the 3 types of HD Path

### Version

10.14.7

### Browser

Chrome, Firefox

### Operating system

Linux

**Comment by wiserdor** [comment]
@seaona i would love to take this one 🙏

**Comment by varunseth5788** [comment]
i would like to contribute to this issue.
or need any other help.
