### ISSUE TITLE
MV3: remove use of deprecated MV2 methods [Undocumented]

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#14908]
Deprecated MV2 methods will not longer be supported in MV3. Remove occurrences of any such method in codebase.

Reference: https://www.notion.so/Chrome-Extension-Version-MV3-Migration-19063a3ee9af46c48f18bf8e8f7aa546

This needs to be checked in all relevant metamask repos.

There are a number of APIs that have long been deprecated. Manifest V3 finally removes support for these deprecated APIs. 

**Undocumented:**

chrome.extension.sendMessage()
chrome.extension.connect()
chrome.extension.onConnect
chrome.extension.onMessage

https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#sunset-deprecated-apis

## Research and Audit

Researched and Audited by: @digiwand 

Related Issue: https://github.com/MetaMask/metamask-extension/issues/14182

I believe I understand why these methods are labeled as undocumented methods. The following methods were not documented in the `chrome.extension` API. It seems that MV3 has migrated from the `chrome.extension` API to the `chrome.runtime` API. It seems that we are on track using the `chrome.runtime` API instead of the `chrome.extension` API. I have found no instances of the following deprecated methods nor "chrome.extension" across our MetaMask repos. 

Ref:
- `chrome.extension` API: https://developer.chrome.com/docs/extensions/reference/extension/ (seems to be deprecated in MV3)
- `chrome.runtime` API: https://developer.chrome.com/docs/extensions/reference/runtime

The following methods have not been found in https://developer.chrome.com/docs/extensions/reference/extension/. 

| Status | Method |Notes | Instances |  
| :---  | --- | --- | --- |
| ✅ |chrome.extension.sendMessage() | No use of `chrome.extension.sendMessage()` in our codebase. Only `chrome.runtime.sendMessage()` which appears to be okay to use. The `sendMessage` is not found in the `chrome.extension` [API](https://developer.chrome.com/docs/extensions/reference/extension/). Also note that `chrome.extension.sendRequest` was deprecated in Chrome 58 and replaced by `chrome.runtime.sendMessage`.  Please refer to the extension doc below for `chrome.runtime.sendRequest`: <br> - https://developer.chrome.com/docs/extensions/reference/runtime/#method-sendMessage | None of `extension.sendMessage`. Instances of `chrome.runtime.sendMessage()`: <br> - `/app/scripts/detect-multiple-instances.js` | 
| ✅ | chrome.extension.connect() | only using `chrome.runtime.connect()`. Please see details above this table. | None of `extension.connect`. Numerous instances of `chrome.runtime.connect()` |
| ✅ | chrome.extension.onConnect | only using `chrome.runtime.onConnect()`. Please see details above this table. | chrome.extension.onConnect() | None of `extension.onConnect`. Instances of `chrome.runtime.onConnect()`: <br>- `/metamask-extension/-/blob/app/scripts/background.js  |
| ✅ | chrome.extension.onMessage | Please see explanation above | None of `extension.onMessage`. Only one instance of `extension.onMessageExternal` in `/metamask-extension/-/blob/app/scripts/metamask-controller.js`. |

See:
- https://developer.chrome.com/docs/extensions/reference/extension/#method-sendRequest
- https://developer.chrome.com/docs/extensions/reference/runtime/#method-sendMessage

**Comment by digiwand** [comment]
When I first examined this issue, I was confused about how to approach this because I couldn't find documentation on the related methods. Google searches did not help. Then after working on https://github.com/MetaMask/metamask-extension/issues/14182, I realized that these deprecated `chrome.extension` API methods, for the most part, have mirrored methods using the `chrome.runtime` API. We are using the `chrome.runtime` API and not the `chrome.extension` API so we shouldn't have anything to deprecate.
