### ISSUE TITLE
Remove Enhanced Gas UI from Experimental Flag

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#14925]
### Describe the bug

Remove Enhanced Gas UI from experimental flag by

- Enable Enhanced Gas (EIP-1559 v2) UI for transaction screens by default
- Removing it from the Settings > Experimental
- Remove Enhanced Gas UI alert that appears if the user is on EiP-1559 v1 UI

### Steps to reproduce

N/A

### Version

10.14.6

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
We might want to review and merge this PR https://github.com/MetaMask/metamask-extension/pull/14203 before removing the feature flag
