### ISSUE TITLE
[Bug]: Displayed Wrong native currency unit when connecting Rinkeby Testnet

### ISSUE THREAD

**Issue by robpark04** [MetaMask/metamask-extension#14921]
### Describe the bug

![image](https://user-images.githubusercontent.com/94480152/173122295-7a44669b-2ed5-44aa-b12d-fab8425f93df.png)

### Steps to reproduce

1.

### Version

10.14.6

### Browser

Chrome

### Operating system

Windows

**Comment by kevinghim** [comment]
Related #14664

**Comment by kevinghim** [comment]
Rinkby testnet has been deprecated.
