### ISSUE TITLE
Balance Tooltip is cutted off.

### ISSUE THREAD

**Issue by oancius** [MetaMask/metamask-extension#1492]
As you can see in the attached screenshot the tooltip that appears when hover over the account balance is cutted off in the left side because gets out of the container.

device: Chrome 58.0.3029.110, macOS Sierra, macbook pro 15" with 1440px*900px resolution.

![tooltip_cut](https://cloud.githubusercontent.com/assets/20577110/26422678/70a4b6f0-40d3-11e7-9316-3ca23ef5c142.png)

**Comment by flyswatter** [comment]
This should just be based on where your cursor is. If you moved your cursor further to the right, it would be visible.

We *could* make the balance fixed in position under the item here.

**Comment by oancius** [comment]
Yes, I know this, but it could be displayed under the balance in a fixed position exaclty like you said to avoid situations like this.  :)
