### ISSUE TITLE
[Bug]: Pending tx warning overlaps top menu

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#14932]
### Describe the bug

**Problem**: the Pending Transaction warning overlaps with the Details/Data menu, when we scroll down

![image](https://user-images.githubusercontent.com/54408225/173389122-26ffff35-cfeb-4649-9cb5-befe4302f1f1.png)

### Steps to reproduce

1. Open MM
2. Open [Test Dapp](https://metamask.github.io/test-dapp/)
3. Connect MM to Test Dapp
4. Click on Send EIP155 tx (do not perform any action on MM prompt)
5. Click on  Deploy Contract
6. Confirm Send EIP155 tx
7. Scroll down

https://user-images.githubusercontent.com/54408225/173389305-34992f10-36d8-4bcf-b3db-0dd81ebdc38c.mp4

### Version

10.16.0

### Browser

Chrome, Firefox

### Operating system

Linux

**Comment by bschorchit** [comment]
Related to: https://github.com/MetaMask/metamask-extension/issues/14602
