### ISSUE TITLE
[Bug]: 2 MetaMask Modals 1 Dapp 

### ISSUE THREAD

**Issue by sambacha** [MetaMask/metamask-extension#14957]
### Describe the bug

![](https://d.pr/i/PBBX9f.jpg)

### Steps to reproduce

1. Open Metamask on a dapp in chrome that is not fully maximized
2. Generate transaction signing request
3. Maximize browser window
4. now click metamask extension icon as the original modal window for signing cant be overlayed in maximized window
5.  When modal window pops up from clicking the icon, unmaximize the browser window
6. Now have 2 MetaMask modals requesting signature
7.  RACE

### Version

10.14.6

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Hey @sambacha, thank you for this report! I believe this is the intended behavior and not a bug though. You can achieve the same state without maximizing the browser window too. If you sign the request in either one of the modals the other one will disappear.
