### ISSUE TITLE
[Bug]: High CPU/memory usage on Xero website. https://go.xero.com/

### ISSUE THREAD

**Issue by LegsAJimbo** [MetaMask/metamask-extension#14969]
### Describe the bug

When browsing the https://go.xero.com/ website, high CPU (100%) and memory (1GB+) usage is encountered for that tab.

This issue also happens with the Ronin wallet extension.

I have also raised a ticket with Xero and referenced this specific bug report.

### Steps to reproduce

1.
Browse https://go.xero.com/ using a free demo account.

### Version

10.14.6

### Browser

Brave

### Operating system

Linux

**Comment by bschorchit** [comment]
Hey @LegsAJimbo, from your report this issue seems related to the website and not a MetaMask issue. Any reason you think it's a MetMask issue?
