### ISSUE TITLE
[Bug]: Ten second rpc timeout disrupts hw connectivity

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14968]
### Describe the bug

When connecting a hw wallet, if no response if returned within 10 seconds the `select an account` screen is not displayed

https://drive.google.com/file/d/1f44Y_T37ndes3b-6C4bIqsb7SC46E59C/view?usp=sharing

### Steps to reproduce

1. Open the account menu and select `connect hardware wallet`
2. Select a hw, click continue
3. Wait 10 seconds
4. Complete the process to connect the device

### Version

10.16.0

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger, Trezor, Keystone, GridPlus Lattice1

**Comment by seaona** [comment]
@PeterYinusa @segun can we close this issue now? Because of #14972 fix

**Comment by PeterYinusa** [comment]
Fixed by #14972
