### ISSUE TITLE
[Bug]: Can't delete a network that I added

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14979]
### Describe the bug

This: 
![image](https://user-images.githubusercontent.com/13969584/174404779-653529f4-7983-429b-a0d3-fa025fc213c7.png)

is a network that I added manually.
There's no "Delete" button.

The funny thing is that all the other networks that I added in the exact same way (plus the "localhost" one that I don't remember adding myself, but maybe I did), do have a Delete button.

### Steps to reproduce

1. go to Network -> Settings

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

**Comment by php4fan** [comment]
Oh I see, it's because it's the one I have currently selected.

Makes sense, but could be improved.
I think the sensible think to do is:
- show the Delete button like on any other network
- when I click to delete, show a confirmation prompt such as "This is your currently selected network. If you proceed, selection will be switched to <WhateverOtherNetwork>. Are you sure you wish to continue? Yes / No" (or Confirm/Cancel, Delete/Cancel or however you want to phrase it).

**Comment by vrde** [comment]
@php4fan thanks for reporting this issue, it helped me to understand why I wasn't able to delete the network.

An easy fix would be to just add a message "To delete this network, connect to another one" or smth like this.

**Comment by php4fan** [comment]
And again, please remove this idiocy of closing issues "because" they have not been fixed.
