### ISSUE TITLE
Create a "home" for Snaps in the UI

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#14976]
Currently, Snaps "live" in a subsection of app settings. This has worked until now, but we have some UI-related Snaps features in the pipeline which would be a poor fit for settings. In particular:
- https://github.com/MetaMask/snaps-skunkworks/issues/373
- https://github.com/MetaMask/snaps-skunkworks/issues/377
- https://github.com/MetaMask/snaps-skunkworks/issues/550

These features will require UI components that a user may visit during regular usage of their snaps, and aren't "settings" in any conventional sense of the word. Already, the "snap view" page that users must visit in order to interact with the "settings" of a particular snap contains information that isn't settings-related, such as manifest data and permissions.

Therefore, we need to answer the following design / UX questions:
- Where in the existing MetaMask UI can we create a "home" for Snaps where we can put features such as private key imports, and in the future, other stuff?
- Should the existing content of Snaps settings stay there, or should it move to the new Snaps area?
- How will this work with / be encompassed by the IA / nav redesign?

Once we've answered these questions, we can create the necessary wireframes.

**Comment by eriknson** [comment]
Here's two sketches of a home for Snaps in the [current UI](https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=381%3A12220) and in the first phase of the [redesigned UI](https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=273%3A8287)

**Comment by rekmarks** [comment]
The designs for the current UI are complete. We will create a separate ticket for the designed UI.
