### ISSUE TITLE
[Bug]: Network setting editor interface goes berserk

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14978]
### Describe the bug

see Steps to reproduce

### Steps to reproduce

1. Go to Settings -> Networks
2. Select a network that you have previously manually added, e.g. the BNB SmartChain Testnet
3. try to edit any parameter, e.g. the symbol, RPC URL, network id, etc.

Expected behaviour:
should allow me to change the settings however I like. If there's an error in my settings, either in real time as I modify them or when I try to save the changes, show me error messages.

Observed behavior:
At every keystroke of mine, initially the character I typed is added, or if I have hit backspace a character it is deleted. 
For a fraction of a second some error shows up next to the field I'm editing or next to other fields, probably a legitimate error message due to the changes I've made, but I don't have time to read what it is because:
almost immediately whatever change I have made gets undone, the error message that had flashed vanishes, and the button to save changes gets disabled again because all the settings are back to their original value.

It's batshit crazy, completely nonsensical behavior.

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

**Comment by php4fan** [comment]
Looks like this only happens if the network I'm trying to edit is the one that is currently selected (i.e. I'm connected to, not sure what the proper terminology is).
Kind of like https://github.com/MetaMask/metamask-extension/issues/14979 but more stupid and unjustifiable, and a completely unacceptable behavior in this case.

Either:
A. Let me edit it regardless, I don't really see why I shouldn't be able to, 
or, if there's a good reason:
B. Show all fields as disabled, don't allow me to edit it at all, and tell me why.

Allowing me to change all the settings and then undoing my changes between a fraction of a second and a few seconds later is stupid.

**Comment by bschorchit** [comment]
Hey @amerkadicE, do you know if this issue is be fixed with your PR: https://github.com/MetaMask/metamask-extension/pull/14370 ? Or is it a different one?

**Comment by amerkadicE** [comment]
Hi @bschorchit, It is the same issue. It is fixed with my PR.

**Comment by bschorchit** [comment]
Awesome! Then I'll close this ticket as we're tracking this issue here: https://github.com/MetaMask/metamask-extension/issues/13168
