### ISSUE TITLE
[Bug]: Ability to add a network with an empty name

### ISSUE THREAD

**Issue by YuriiOnyskiv** [MetaMask/metamask-extension#14973]
### Describe the bug

 Missing validation for inputs "Network name" and "Currency Symbol"

### Steps to reproduce

1. Click on the button "Add network"
2. For input "Network name" enter space
3. For input "New RPC URL" enter valid data(for e.g. "[https://polygon-rpc.com"](https://polygon-rpc.com%22/))
4. For input "Chain ID" enter valid data(for e.g. "137")
5. For input "Currency Symbol" enter space
6. Click on the button "Save"

### Version

10.14.6

### Browser

Chrome

### Operating system

Windows

### Additional context

![Screen1](https://user-images.githubusercontent.com/49688695/174159559-fe39b72f-8495-4c59-926f-e275517d11a6.png)
![Screen2](https://user-images.githubusercontent.com/49688695/174159563-f0eba284-11d9-42de-b3df-81908b1e6bdb.png)

**Comment by jilky** [comment]
LOL. nice find. this is hilarious.

**Comment by bschorchit** [comment]
Hey @YuriiOnyskiv, thank you for the report! This is intended to not block users from moving forward if they don't want to fill all the information there. As you can see, we provide feedback in the form that the currency symbol does not match the value we expected. 
I'll leave this open so we revisit it in the future.
