### ISSUE TITLE
[Bug]: Failing transaction won't show error messages from contract

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14985]
### Describe the bug

When you try to send a transaction to a method in a contract that will throw errors, MetaMask will detect that when trying to estimate gas fees, and will warn you that the transaction is likely going to fail, and offers the option to continue anyway (which is likely to be costly). So far so good.

But the issue is that it does not show the error message from the contract. This is stupidly frustrating because it gives you no clue about what's actually wrong with the transaction (unless you pay and execute it and then see the error messages in the blockchain, which would be stupidly expensive).

This happens at least on the **BNB Smart Chain**

### Steps to reproduce

1. Send a transaction to a contract that you know will fail.

For example:

Send a transaction on the BNB Smart Chain to the following smart contract address:

```
To:
0xf4BE4f05c35A82BD2369c0bFdcf3588dE07967aC

Value:
0.00001 BNB 

Hex data:
0x6f833aea000000000000000000000000000000000000000000000000000000000000001b7209901d7d4e1689f7902acc439b9405c0db164e5830c7490c49b8b2bc630446428c6c4720d323475486429c66d3c04a35cf5c9d31925cef5388e21adf9917c600000000000000000000000000000000000000000000000000000000000000cf0000000000000000000000000000000000000000000000000000000062ae1195
```

**Observed result:**
![image](https://user-images.githubusercontent.com/13969584/174451145-2702dbb3-2379-4222-b8b2-76fcf8a88074.png)

**Expected result:**

Like the above, plus the actual error message from the contract.

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

### Additional context

This is actually similar to #14460 but the behavior is slightly different.

Not sure if maybe it's the same issue but error handling has simply changed.

**Comment by bschorchit** [comment]
Related to: https://github.com/MetaMask/metamask-extension/issues/9419
Closing this issue as we are tracking this improvement request there.
