### ISSUE TITLE
[Bug]: "Transaction data" just shows a loading spinning icon forever when unfolded

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14989]
### Describe the bug

see steps to reproduce

### Steps to reproduce

1. Click on the fox icon
2. make sure you are logged in with an account that has made transactions
3. go to the Activity tab
4. click on one of the (successful) transactions in the list
5. click on "Transaction Data"

Expected:
- If there is no data to show, don't show a "+" button (or a "transaction data" menu item) in the first place
- If there is an issue loading the data, show an error message that explains exactly what went wrong loading the data. And that includes timeout.
- otherwise, after a few seconds at most, transaction data should appear.

What happens instead:

![image](https://user-images.githubusercontent.com/13969584/174474487-60a71e98-377f-46c6-9070-5ea4cacbaf56.png)

the spinning icon keeps spinning forever.

This is on the **BNB Smart Chain**.

UPDATE
==
I have retried now, and now I get this, which I believe is the expected result:
![image](https://user-images.githubusercontent.com/13969584/174474556-4604de84-c0fa-4d63-a839-6d4df51702c5.png)

This makes sense. Actually I'm not sure why you shouldn't be able to decode transactions for a chain that works exactly like Ethereum but I might be missing something. At least the behavior makes sense.
This appears immediately now, which makes sense too. If transaction data is not supported for a given chain ID, it should not require any time to know that, you know that from the beginning, there's no need to attempt anything and wait for it to fail. 

It looks like in some cases, randomly, you attempt to load data that you cannot possibly get in any way, for an unsupported chain. I'm speculating about the reason, but the behavior is obviously wrong.

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I can reproduce this in Rinkeby and Polygon.

**Comment by php4fan** [comment]
Closing issues because they have not been fixed is stupid.

**Comment by php4fan** [comment]
> This issue was closed because there has been no follow up activity in the last 45 days

Again this idiocy. Please reopen, kill the stupid bot, and fix the issue.

Or just announce that this project is dead so that people stop wasting their time with an unmaintained app.
