### ISSUE TITLE
[Bug]: Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14987]
### Describe the bug

see steps to reproduce

### Steps to reproduce

1. Make sure you have MetaMask installed and enabled
2. If you have Chrome already open, close it
3. Launch Chrome
4. Open the Console

The following error will show up, usually once, sometimes two or three times:

### Error messages or log output

```shell
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

### Additional context

I have no other extensions enabled. If I disable MetaMask, the error stops showing up when I launch Chrome.

Guys do you even test before releasing??

**Comment by BelfordZ** [comment]
@php4fan Thanks for the issue. Having troubles reproducing this.

Reproduction aside, is this blocking you in anyway? 

We test extensively before releasing. If you are interested, have a look at our e2e tests: https://github.com/MetaMask/metamask-extension/tree/develop/test/e2e

**Comment by php4fan** [comment]
Why are you closing this?

> is this blocking you in anyway?

Not that I know of (unless it's related to the cause of some of the other dozens of bugs), but it's not acceptable to have random bogus errors in the console. Imagine if every extension I install did that, and then I need to debug the errors in my own code.

**Comment by BelfordZ** [comment]
@php4fan Sorry for not making it more clear - I was not able to reproduce this issue *using latest*. I've installed the version you are using, and now see the error. 

Updating to latest will fix it.

We don't want to leave random errors in the console.

**Comment by php4fan** [comment]
Oh I see, sorry.

**Comment by php4fan** [comment]
By "latest" do you mean building from source?
I now have 10.16.1 and I'm still observing the issue.

**Comment by BelfordZ** [comment]
I was not able to reproduce this in 10.16.1 until after many many attempts. Seems to only happen on some pages (I could only get it to happen when the first tab opened was github). 

I am able to reproduce it 9/10 times now by:
1. disabling all other extensions
2. open chrome in profile "A" which has metamask installed
3. close / quit
4. open chrome in profile "B"
5. open console and be amazed

Digging deeper...

**Comment by BelfordZ** [comment]
@php4fan should be fixed once this all gets merged up and released. Sorry for the confusion and the incorrect closing of this issue, and thank you for taking the time to submit an issue.

**Comment by izogfif** [comment]
@BelfordZ So, any update on this?

**Comment by izogfif** [comment]
For what it's worth: I had the same error message when I tried to attach event listeners in service worker in onInstalled event handler. See "Don't" block in [documentation](https://developer.chrome.com/docs/extensions/mv3/service_workers/#listeners):

<pre>
chrome.runtime.onInstalled.addListener(() => {
  // ERROR! Events must be registered synchronously from the start of
  // the service worker.
  chrome.bookmarks.onCreated.addListener(() => {
    // do something
  });
});
</pre>

**Comment by seaona** [comment]
I believe there are multiple ways to reproduce this behaviour. Here are some solid steps for repro'ing in one way:

1. Load MM 
2. Click popup
3. While having the popup open, disable the extension
4. Enable back the extension
5. Check background console


https://user-images.githubusercontent.com/54408225/224311469-139c7894-464b-4846-892e-e2590258d5e8.mp4

cc @BelfordZ

**Comment by CyberpunkLucyKiwi** [comment]
Hi, guys, I find the same errors when integrate Metamask extension into Electron, by using

import { app, BrowserWindow, session } from 'electron';
import path from 'path';
...
  const ext = await session.defaultSession.loadExtension(
    path.join(__dirname, '../../extensions/ejbalbakoplchlghecdalmeeeajnimhm/10.28.3_0'),
    { allowFileAccess: true, }
  );

Metamask version are 10.28.3_0 and 10.30.1_0 and 10.29.0.0_0, all will result into errors, and Metamask popups with infinite loading and errors:
contentscript.js:1 Error: Could not establish connection. Receiving end does not exist. Resetting the streams.

I have checked with many possibilities, but no idea with it.       The Electron loading extension method has no problem, because I can use the same method for coinbase wallet extension, it's perfect for loading and popuping.

**Comment by a0m0rajab** [comment]
I got into the same error but at another extension, It was resolved when I refreshed the page and ignoring the cache: (CTRL+SHIFT+R)

**Comment by CyberpunkLucyKiwi** [comment]
> 

Oh, thanks for tips, I tried, but not work for me, even I set no-cache header when running electron dev mode.  This bug is really werid.

**Comment by CyberpunkLucyKiwi** [comment]
> I got into the same error but at another extension, It was resolved when I refreshed the page and ignoring the cache: (CTRL+SHIFT+R)

Oh, thanks for tips, I tried, but not work for me, even I set no-cache header when running electron dev mode. This bug is really werid.

**Comment by a0m0rajab** [comment]
This is related to sendMessage function, but not sure how to debug it or how to check it for this project. 
Here is the related functions: 
https://github.com/search?q=repo%3AMetaMask%2Fmetamask-extension%20sendmessage&type=code

**Comment by CyberpunkLucyKiwi** [comment]
Great clue, the next step is how to debug it, maybe try the source code of extension, not sure.

**Comment by php4fan** [comment]
Oh FFS again this idiocy. Stop closing issues "because" you don't fix them.
