### ISSUE TITLE
[Bug]: randomly fails to show popup; awaits eth_requestAccounts forever

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#14988]
### Describe the bug

This is my code (needs jQuery):

HTML 
==
```
<button id="my-button">Click here</button>
```

JavaScript
==
```
var metamaskCheckInterval = 0;
var metamaskFound = false;

$(function() {
    startMetamask();
});

function startMetamask() {
    var n = 0;
    metamaskCheckInterval = setInterval(
        function() {
            console.log("Checking for Metamask...");
            n += 1;
            if (window.ethereum) metamaskFound = true;
            if (n >= 30 || metamaskFound) {
                clearInterval(metamaskCheckInterval);
            }
            if (metamaskFound) initMetamask();
        },
        1000
    );
}

function initMetamask() {
    console.log("Metamask was found!");
    $("#my-button").on("click", async function() {
        console.log("Metamask button clicked");
        
        try {
            console.log("Awaiting eth_requestAccounts...");
            await ethereum.request({ method: 'eth_requestAccounts' });
            console.log("eth_requestAccounts returned");
        }
        catch (e) {
            console.log("Error with requestAccounts", e);
        }

        if (!ethereum.selectedAddress) {
            alert("An error occurred");
            return;
        }

        console.log(ethereum.selectedAddress);

}
```

### Steps to reproduce

1. Close Chrome
2. Open Chrome
3. visit the page with the example code
4. click on the button

It seems that if I do the above as quickly as possible, the chances of reproducing the issue increase.

The expected behavior is that:
- possibly (or always?) MetaMask's popup will show up and prompt me to insert the password, and/or to connect and/or whatever
- then my address will be logged to the console.

But at random times (and as I mentioned, seems to be more likely if I do steps 1-4 quicky immediately after opening Chrome), the MetaMask popup never shows up, and therefore the first `await` remains awaiting forever.

When this happens, if I reload the page, I think 100% of the time the issue will no longer reproduce.

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

### Additional context

This is ridiculous. I have been trying the most basic stuff straight out of the documentation tutorials and examples, I probably haven't written more than 100 lines of code, and I have already found like half a dozen bugs in one afternoon. Pathetic.

**Comment by BelfordZ** [comment]
The issue is that you are registering the click listener *after* you click the button. Heres another approach you can use:

```
var metamaskCheckInterval = 0;

$(function() {
    initMetamask();
});

function request(...args) {
  if (!window.ethereum) { 
    console.log("Checking for Metamask...");
    return setTimeout(() => request.apply(this, args), metamaskCheckInterval); 
  }
  return window.ethereum.request.apply(this, args);
}

function initMetamask() {
    console.log("Metamask was found!");
    $("#my-button").on("click", async function() {
        console.log("Metamask button clicked");
        
        try {
            console.log("Awaiting eth_requestAccounts...");
            await ethereum.request({ method: 'eth_requestAccounts' });
            console.log("eth_requestAccounts returned");
        } catch (e) {
            console.log("Error with requestAccounts", e);
        }

        console.log(ethereum.selectedAddress);
    });
}
```

Heres a codepen with your code, fixed up

https://codepen.io/BelfordZ/pen/WNMqJYQ

**Comment by php4fan** [comment]
And actually, the issue can be reproduced with your code too. It makes no significant difference.

Here's a slightly modified version to print the output into the html body instead of the console:
https://codepen.io/php4fan/pen/LYQKMoB

When it behaves as expected, you get:
```
Metamask button clicked
Awaiting eth_requestAccounts...
Metamask was found!
eth_requestAccounts returned
0xa3c9a7fd8de442578a65681732301ff0c9d7f61f
```
(the "metamask was found" message comes after "awaiting..." while in my original code it was intended to be the other way around but that's an issue in your code and it's not relevant)

But sometimes you get:
```
Metamask button clicked
Awaiting eth_requestAccounts...
Metamask was found!
```
and that's the bug.

Please reopen.

**Comment by jurosh** [comment]
Might be related to what I started to experience recently https://github.com/MetaMask/metamask-extension/issues/15105
