### ISSUE TITLE
#14994 is locked

### ISSUE THREAD

**Issue by du5** [MetaMask/metamask-extension#14999]
Google translates to:

```
This action will edit tokens already listed in your wallet and may be used to defraud you. Only pass this if you are sure you want to change the content of these tokens. Learn more about
```

Our English is:

```
This action will edit tokens that are already listed in your wallet, which can be used to phish you. Only approve if you are certain that you mean to change what these tokens represent. Learn more about
```

The changed verbiage: `can be used to deceive you` -> `Can be used to deceive you`

@du5 What's the reason for this change?

_最初由 darkwing 在 https://github.com/MetaMask/metamask-extension/pull/14994#pullrequestreview-1013770163 发布_

**Comment by bschorchit** [comment]
I've added your comment on the PR and I've asked for a translation review for this as well.
