### ISSUE TITLE
[Bug]: minor german translation mistake

### ISSUE THREAD

**Issue by SebSeb11** [MetaMask/metamask-extension#14996]
### Describe the bug

![1](https://user-images.githubusercontent.com/48764817/174827475-a28a509f-62fb-43b5-82a3-42d8a903fae7.PNG)

When Metamask is connected to a page it shows a green dot with its explanation "Connected".
The german translation "Verbinden" is wrong.

Connect -> verbinden
Connecting -> verbinden..., verbinde...,
Connected -> verbunden

### Steps to reproduce

1. Use Metamask in german
2. Go on a page that Metamask is connected to.
3. open Metamask extension

### Version

10.14.6

### Browser

Microsoft Edge

### Operating system

Windows

**Comment by ryanml** [comment]
Closed via: https://github.com/MetaMask/metamask-extension/pull/14997
