### ISSUE TITLE
[Bug]: Wallet Generated an already existing account with funds on our blockchain.  Um Can I get a response? 

### ISSUE THREAD

**Issue by malcolm-dane** [MetaMask/metamask-extension#14998]
### Describe the bug

Created a new account to test a new faucet contract. The new account generated with funds, thinking maybe it was some weird error I checked out block explorer and lo and behold it has funds in it. I checked our internal dev logs, our cloud faucet, and it wasn't one of ours. I see it has three transactions, but not sure what they are. In the middle of building analytics tool to figure this out. The odds of this happening , with funds in the account is like 1 in a 2 billion ^2 ish. 

0xE372DDfE444540c54336CBb3701c36774cC2831f

https://explorer.thenewmanagementinc.com/#/address/0xe372ddfe444540c54336cbb3701c36774cc2831f

This isn't a joke, promotion, etc. I have no idea how this is possible.

### Steps to reproduce

Not sure I generated the account, a new account, to check faucet contract, and the account generated with TNMIG. Thinking it was an error I restarted, still was there, then I checked our explorer and lo and behold it did exist. Not one of ours. I am in the midst of getting more information. 

### Error messages or log output

```shell
none
```

### Version

10.14.6

### Browser

Chrome

### Operating system

Linux

### Additional context

Yeah this might be a security vulnerability. I just didnt want to make a hackerone account. I felt it was important to immediately get this to you guys. This really shouldn't happen.

**Comment by malcolm-dane** [comment]
Um no one is going to respond to this?

**Comment by tayvano** [comment]
Hey Malcolm,

Can you walk us through exactly the steps you took to set up the new account in MetaMask? e.g. Did you import a loose key, import an existing secret recovery phrase, or do `+ Create Account` account within your existing MetaMask?

**Comment by bentobox19** [comment]
Hello @malcolm-dane 

1. Can you confirm 100% that you created the account using the `Create a Wallet` button?

2. If this was the case, Can you confirm this is the account you generated?

https://etherscan.io/address/0xE372DDfE444540c54336CBb3701c36774cC2831f

Thank you!

**Comment by malcolm-dane** [comment]
Yeah so, I never had this account, I don't know who's account this was on our blockchain, but while testing a faucet contract, that is time limited to 30 minutes, we needed a bunch of new accounts. I hit create account, and it generated an account prefunded, which shouldn't been. I don't know who owns the account, we soft launched, and have a meeting with some vcs friday, so we wanted to check everything, although we've been launched for about a month, and open to whomever wanders into our little blockchain. Anyways, I clicked create account, and it created an account that already existed, on our network, that had the currency in it. I've rolled out every possible end user causation. None of us own this account, none of us have the key, none of the VPS's have this account, but in the logs it was created by someone who wasn't us. So basically it shouldn't have happened, because none of us had this account prior. This account was created April,21 by some unknown.  

1. I'm not sure how you  generate accounts, but if it helps, the account name was account 6, I didn't add anything into the field, and the time was 10:35 ETC. I only mention that in case you are using time and name to generate entropy. In the meantim we have like 8 vps right now programmatically generating metamasks accounts, another engineer noticed that account he generated had some other monetized token in it, I haven't reviewed that yet to know if it's true, but I trust they are telling the truth, so far none with eth in them, so uh wtf?

**Comment by malcolm-dane** [comment]
Also it wasn't imported,it was derived, and when it generated it generated
with our currency. I'm not an idiot, and I know I didn't have that account
prior to generating it.

**Comment by bentobox19** [comment]
Hello @TheNewManagementInc 

Thank you for the information you provided

Any account generated with the `+ Create Account` button would derive from the SRP provided to the extension in a deterministic way.

If some other actor has access to the same SRP and add it on the MetaMask extension in a different computer, they would be able to derive the same account with this button.

**Comment by malcolm-dane** [comment]
That doesn't sound safe.

**Comment by bellwood420** [comment]
Coincidentally, I just encountered the same issue today.
I already reported it to MetaMask support (a ticket opened on ZenDesk) but I also would like to report here as well, since I think it is critical and surprised to see the same issue already reported most recently.

I created a new account from `+ Create Account` button. Name was `Account 5`.
After creating the account, I noticed that there were unknown 
 balances and transactions already existed on several networks(`Mainnet`, `Ropsten`, `Polygon`, `BSC`), which exactly did not belong to me.

I hope my case is really a real coincidence...

**Version**
10.16.1

**Browser**
Brave 1.40.109

**Operating system**
Windows 10 21H2

**Comment by danjm** [comment]
@bellwood420 What was the subject/description of your zendesk ticket? I would like to follow up to ask you more information there, but we should communicate about this via a more secure channel.

@malcolm-dane I will e-mail you at the address given in your github profile

**Comment by Smokefarmer** [comment]
Hello, I just encountered the same issue today.

I created a new account in my Metamask extension in the Brave browser with the button "Add a new  Account" and the auto generated name was Account 5.
After I created the account, I noticed that there were unknown tokens on multiple networks that I had never seen bevor.

Browser
Brave 1.62.162

Operating system
Windows 11 Pro 23H2
