### ISSUE TITLE
[Bug]: Sentry 429 (Too Many Requests)

### ISSUE THREAD

**Issue by remedcu** [MetaMask/metamask-extension#15000]
### Describe the bug

Whenever trying to make a transaction with either browser console or remix, it shows this error:

```
POST https://sentry.io/api/[SOME_VALUE]/store/?sentry_key=[SOME_VALUE]&sentry_version=7 429 (Too Many Requests)
```

### Steps to reproduce

1. Creating any write transaction calls through remix.

### Error messages or log output

```shell
POST https://sentry.io/api/[SOME_VALUE]/store/?sentry_key=[SOME_VALUE]&sentry_version=7 429 (Too Many Requests)
```
```


### Version

10.15.0

### Build type

_No response_

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

There are no errors on read transactions.

**Comment by Kamikozz** [comment]
Getting the same error. MacOS M1 pro max. Chrome. Click on the extension opens black screen with infinte loader
![image](https://user-images.githubusercontent.com/33129671/178154984-2caee0d1-dcac-4775-9fc3-2661abe8fdad.png)

DevTools shows 
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/33129671/178155007-07b56b5e-a4b8-473a-a993-42e59262809f.png">

POST https://sentry.io/api/273505/envelope/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7 returns 200
Then https://sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7 returns 429

**Comment by Ta-Tung** [comment]
I have the same trouble with Mac M1. Somebody have the solution to fix this 
![image](https://github.com/MetaMask/metamask-extension/assets/46585748/85372763-0463-4286-9463-1ebf0e9fe4d6)
