### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'map') 

### ISSUE THREAD

**Issue by Robbo333** [MetaMask/metamask-extension#15009]
### Describe the bug

I tried to purchase something on opensea but it prompted me to bridge to polygon.  Transaction seemed to go fine and says confirmed, but the transaction data kept saying "Cannot read properties of undefined (reading 'map')".  I didnt get the item and I can't see my funds anywhere

### Steps to reproduce

1. As above

### Error messages or log output

```shell
Cannot read properties of undefined (reading 'map')
```

### Version

Cant see settings

### Browser

Chrome

### Operating system

Windows

**Comment by bschorchit** [comment]
Hey @Robbo333 , thank you for this report! Have you added the Polygon network to MetaMask and also imported the Eth token on matic to MetaMask? This might be the reason you're not seeing the funds.
