### ISSUE TITLE
[Bug]: on test network of ropsten, request ether from faucet return 500 error but actually succeeded.

### ISSUE THREAD

**Issue by zheli-1** [MetaMask/metamask-extension#15014]
### Describe the bug

on the test network of ropsten, request ether return 500 error but actually succeeded.requested

### Steps to reproduce

1.click ropsten network and connect
2.click buy
3.request 1 ether from faucet

### Error messages or log output

```shell
Error: 500 {"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Request.eval [as _callback] (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Request.emit (events.js:315:20)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Request.emit (events.js:315:20)\\n at IncomingMessage.eval (/www/node_modules/request/request.js:1077:12)\\n at Object.onceWrapper (events.js:421:28)\\n at IncomingMessage.emit (events.js:327:22)\\n at endReadableNT (internal/streams/readable.js:1327:12)\"}}'"}
```

### Version

newest

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

Linux

### Additional context

I looked at the code, I assume it's the await for url function doesn't check the return states in 
/smart-contract-testing/metamask-extension/ui/store/actions.js of buyEth function.

**Comment by zheli-1** [comment]
![metamask-bug-0](https://user-images.githubusercontent.com/32209826/175130877-903bf169-9fff-4cba-b25c-4cd2e78d753e.png)

**Comment by zheli-1** [comment]
any feedback?

**Comment by bschorchit** [comment]
Related to: https://github.com/MetaMask/metamask-extension/issues/12016

**Comment by bschorchit** [comment]
Closing as Ropsten has been deprecated.
