### ISSUE TITLE
Removing multiple versions of modules from bundle

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15026]
Quite a few modules are included in bundle multiple times. For instance

1. bn.js
2. BigNumber.js
3. readable-stream.js
4. ethereumjs-util

https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/background-3.html

https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-2.html

We should remove this duplications from bundle.

**Comment by danjm** [comment]
I don't think we need this ticket as we also have #15531 #14889

I also don't think the effort of removing multiple ethereumjs-util instances is worth it, and not sure if it is possible
