### ISSUE TITLE
Evaluate and possible remove node-forge

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15028]
https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/background-6.html

node-forge is huge and can possibly be removed

**Comment by danjm** [comment]
This will be removed when we remove 3box. Closing because the remove 3box tickets make this redundant.
