### ISSUE TITLE
Evaluate and reduce IPFS module

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15025]
IPFS is increasing bundle size significantly, evaluate and reduce that

https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/background-4.html

https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/background-5.html

**Comment by danjm** [comment]
This will be removed when we remove 3box. Closing because the remove 3box tickets make this redundant
