### ISSUE TITLE
Remove UI related code from shared and background folders

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15020]
https://github.com/MetaMask/metamask-extension/tree/develop/shared

Here it is visible tha shared module includes store and action: https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-8.html

Refactor shared module to remove all references of UI.

**Comment by danjm** [comment]
`shared/constants/gas.js` and `shared/modules/transaction.utils.js` are the two places where we are importing constants from the `/ui` directory. Let's refactor this so that those constants are in the shared directory

**Comment by danjm** [comment]
We should also make the refactors needed so that we are not importing any code from the UI into files under the `app/` directory

**Comment by danjm** [comment]
Note: leave `import launchMetaMaskUi from '../../ui';` in `app/scripts/ui.js` alone
