### ISSUE TITLE
Evaluate and remove gunzip-maybe

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15027]
https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/background-4.html

gunzip-maybe is large and possibly not used and can be removed

**Comment by danjm** [comment]
Closed by https://github.com/MetaMask/metamask-extension/pull/15505
