### ISSUE TITLE
Reduce the bundle size due to @eth-optimism module

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15023]
@eth-optimism has huge bundle size addition. Check to reduce that:

https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-3.html

https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-4.html

**Comment by danjm** [comment]
This will be resolved by #15384
