### ISSUE TITLE
Remove libraries from bundle

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15033]
Following libraries are part of common bundle and can possibly be removed:

1. **diffie-hellman** https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-1.html

2. **browserify** https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-1.html

3. **aes.js** https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-1.html

4. **des.js** https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-1.html

5. **pubnub.min.js** https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-6.html

6. **luxon.js** https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-6.html

7. **tweetnacl** https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-7.html

8. **sha.js** https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-7.html

If required create a separate ticket for each of above dependency.

**Comment by mbappai** [comment]
Hello jpuri. I'd like to take on this issue. Can you please further elaborate on it?

**Comment by danjm** [comment]
closing in favour of https://github.com/metamask/metamask-extension/issues/14884
