### ISSUE TITLE
Remove redux-dev-toolkit

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15032]
Redux tool-kit is getting included in bundle and should be removed

https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-1.html

**Comment by brad-decker** [comment]
reduxjs/toolkit is a valid thing to be in our builds, we import 'createSlice' and 'createAsyncThunk' in the send slice, for example. Its not for debugging its for setting up redux with best practices.

**Comment by brad-decker** [comment]
@jpuri can we close this?
