### ISSUE TITLE
Remove cookiejar from bundle

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15031]
CookieJar is not required and can possible be removed from bundle

https://output.circle-artifacts.com/output/job/0b87725e-d9fa-4b1e-87c8-209ba5bb939a/artifacts/0/build-artifacts/source-map-explorer/common-1.html

**Comment by danjm** [comment]
After these https://github.com/MetaMask/metamask-extension/pull/14571, https://github.com/MetaMask/metamask-extension/pull/15384, this appears to only take up 3-4kb. Not worth trying to remove. Closing for now
