### ISSUE TITLE
[Bug]: Localhost network symbol appears as a question mark

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15046]
### Describe the bug

**Problem**: when I connect to my localhost (Ganache) instance, I see that on the Network symbol there is a question mark, while in  a previous release it was a black circle icon.

![image](https://user-images.githubusercontent.com/54408225/175549902-d79c2b60-024c-4107-8098-b32cdd8dd236.png)

Expected:

![image](https://user-images.githubusercontent.com/54408225/175549984-ada77908-1340-4b7d-95b1-e4b7bcca67fc.png)

### Steps to reproduce

1. Unlock Metamask
2. Initiate a local Ganache instance with a terminal
3. In Metamask activate Test Networks on Settings
4. Connect to Localhost
5. Check symbol

### Version

10.17.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
@SayaGT do you know what would be the correct symbol to display here?

**Comment by SayaGT** [comment]
@bschorchit We actually assign "?" to unknown networks. I guess localhost is being recognised as an unknown network. We could replace it with an "L" for Localhost. Here is the [Figma file](https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=2819%3A12624) with the logic.

**Comment by seaona** [comment]
mm what's interesting is that before 10.17.0 I was seeing a black dot for Localhost, whereas since 10.17.0 (or current develop) I see a question mark. So I was wondering if any recent change broke something @bschorchit @SayaGT
