### ISSUE TITLE
MV3: ensure phishing-detection page preload works (for sufficient offline support)

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#15049]

**Comment by hilvmason** [comment]
@danjm to write out specs here

**Comment by danjm** [comment]
- anyone on the mv3 branch may notice an error in the background console
- when the background first loads we create and iframe in the background pointed at phishing page, then we load it, then delete
- we could make that compatible with MV3 by moving it from the background to the UI
- currently runs when the background process starts, only needs to run once for the browser session
