### ISSUE TITLE
MV3: ensure that dapp requests sent during service worker restarts are properly handled

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#15052]

**Comment by danjm** [comment]
The solution for this may take inspiration https://github.com/MetaMask/metamask-extension/pull/15337

**Comment by danjm** [comment]
Blocked by https://github.com/MetaMask/metamask-extension/issues/14845

**Comment by hilvmason** [comment]
this issue requires further investigation for architecture -- once #15337 is merged, @Gudahtt @jpuri @naugtur should meet to discuss technical solution.

**Comment by jpuri** [comment]
Multiple PRs have been created to fix this issue:

1. https://github.com/MetaMask/json-rpc-middleware-stream/pull/27
2. https://github.com/MetaMask/providers/pull/223
3. https://github.com/MetaMask/metamask-extension/pull/15958

We need to update provider in metamask-extension once https://github.com/MetaMask/providers/pull/223 is merged.
