### ISSUE TITLE
[Bug]: Incorrectly assigning the 'estimatedBaseFee' field to 'maxFeePerGas'

### ISSUE THREAD

**Issue by zctocm** [MetaMask/metamask-extension#15059]
### The background
 There are two ways to get the estimated gas info in MetaMask, the first way is through the Gas API, and the other way is the calculation by the RPC: `eth_feeHistory`. The code:
![CleanShot 2022-06-28 at 14 07 23](https://user-images.githubusercontent.com/16474758/176105494-40b70955-3c0b-432e-a2ca-758e8319ac3f.png)

https://github.com/MetaMask/controllers/blob/d92bec08ec4f1994097e36b69c07bfe54c87270c/src/gas/determineGasFeeCalculations.ts#L77

Actually, I do not know how the Gas API is implemented, but I see the code in another way: calculation by the `eth_feeHistory`.
As a result, I think the `estimatedBaseFee` is the `baseFeePerGas` of block info.
![CleanShot 2022-06-28 at 14 14 01](https://user-images.githubusercontent.com/16474758/176106422-9b70c7df-e752-495a-9739-fd61441a0bc9.png)

https://github.com/MetaMask/controllers/blob/d92bec08ec4f1994097e36b69c07bfe54c87270c/src/gas/fetchGasEstimatesViaEthFeeHistory.ts#L37

### The implementation in UI
I think, the `Max Base Fee` in `Advanced gas fee` page is actually the `maxFeePerGas` in EIP1559, not the `baseFeePerGas` 
![CleanShot 2022-06-28 at 14 26 29](https://user-images.githubusercontent.com/16474758/176108462-5522b49d-1e09-4add-bdf9-bc1fea2dba37.png)

**And also in this page, the `current` value of `Max Base Fee` should be the `maxFeePerGas` after I read the code, but you assign a `baseFeePerGas` to it, I think it is absolutely wrong.** 

https://github.com/MetaMask/metamask-extension/blob/5290402181b92966fde89e0dba28dba941766a49/ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js#L131

The actual `baseFeePerGas` in MetaMask:
![CleanShot 2022-06-28 at 14 26 36](https://user-images.githubusercontent.com/16474758/176108360-7c038ccd-6ed4-4258-9759-78f5c90b6ad3.png)

### Steps to reproduce

![CleanShot 2022-06-28 at 14 26 29](https://user-images.githubusercontent.com/16474758/176108462-5522b49d-1e09-4add-bdf9-bc1fea2dba37.png)

### Version

10.15.1

### Browser

Chrome

### Operating system

MacOS

**Comment by zctocm** [comment]
@bschorchit hi, 21 days passed without any reply

**Comment by kevinghim** [comment]
@zctocm 

> I think, the Max Base Fee in Advanced gas fee page is actually the maxFeePerGas in EIP1559, not the baseFeePerGas

This is incorrect. `maxFeePerGas = baseFeePerGas + maxPriorityFeePerGas` The top box you highlighted in the second screenshot is `baseFeePerGas` The bottom box is `maxPriorityFeePerGas`

The second screenshot's red box you highlighted is actually a historic base fee based on the network's base 200 blocks. It's meant to indicate historic status of the network and it's trend, and not meant to indicate current base fee.

**Comment by zctocm** [comment]
@kevinghim Thanks for the response.
As you said, 
![image1](https://user-images.githubusercontent.com/16474758/179881220-cb36c1cd-492d-480b-93f5-59d1f6047507.png)

the 1 tag in image1 is the baseFeePerGas, and the 2 tag in image1 is the maxPriorityFeePerGas.
the value of `baseFee` is: 0.00041851 ETH
the value of `maxPriorityFee` is: 0.0001365 ETH

Calculated according to this formula: `maxFeePerGas = baseFeePerGas + maxPriorityFeePerGas`,
the max fee should be **0.00055501**.

------------------------------------------------

Then I close the `Advanced gas fee` page, and back to the main page:
![CleanShot 2022-07-20 at 10 17 01](https://user-images.githubusercontent.com/16474758/179881636-78c16194-6842-46c0-8ac3-ae1d1dd100e2.png)

the `Max Fee` shown in image2 is: **0.00041851** ETH

So, Why are the two values ​​different?
