### ISSUE TITLE
[Ext Nav] Create component: AvatarFavicon

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#15073]
### Description
Create a reusable UI component for `AvatarFavicon`

### References
Figma Link: TBC
[UI component guidelines](https://www.notion.so/UI-Components-5ccd2bf83eb8441892a0b72c0d8929e1)
[Styling guidelines](https://www.notion.so/Extension-Frontend-Engineering-Guide-b82ddb3e14004b5db3799a9b446294a9#49aa2ef7b7aa40178ff918043df71c34)
Testing guidelines: TBC

### Files needed
- `index.js`
- `index.scss`
- `avatar-favicon.js`
- `avatar-favicon.stories.js`
- `avatar-favicon.test.js`
- `README.mdx`

### Technical details
- [ ] Accepts an image
- [ ] Accepts a name prop
- [ ] Has a fallback for when there is no image url provided 

### Acceptance criteria
- [ ] Uses color, typography, shadows design tokens 
- [ ] Uses semantic html
- [ ] PropTypes have descriptions
- [ ] Has storybook story with controls
- [ ] Has documentation in MDX
- [ ] Has unit tests and 90% coverage
- [ ] Works in Chrome and Firefox
- [ ] Performance tested: no unnecessary re-renders or other performance concerns

**Comment by georgewrmarshall** [comment]
Reopening because after further discussion I think it would be useful to have an avatar specifically for the Favicon where the fall back is the world icon

**Comment by Smithbull001** [comment]
Close
