### ISSUE TITLE
Proposal: notification for when a dapp try's to access the MM address  

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#1508]
It may be a nice feature to let users know if and when a dapp is trying to get your account info
Locking is a nice thing but i forget to lock all the time so having a either sub provider or a proxy trap on web3 to throw up a notification when web3.eth.getAccounts or web3.eth.accounts is used would be nice. And maybe this could be toggled in settings if you dont like this behavior 
it could also help users understand that for dapps to get the address the account needs to be unlocked

**Comment by kumavis** [comment]
Yeah I'd like to turn this into a login flow / request address access flow

**Comment by willnwhite** [comment]
I'd prefer MetaMask to be locked for new websites, with access to the password manager to unlock. The simplest way to implement a login flow would be a message from the dapp on MetaMask's unlock screen.

**Comment by flyswatter** [comment]
@willnwhite That's already on our roadmap as #714.

**Comment by bdresser** [comment]
Addressed by EIP 1102
