### ISSUE TITLE
[Ext Nav] Create component: HeaderMenu

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#15097]
Possibly being redesign. DO NOT WORK ON THIS TICKET YET

### Description
Create a reusable UI component for `HeaderMenu`

### References
[Figma Link](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=9917%3A36917&t=F9rD1GozcS83Y5a3-1)
[UI component guidelines](https://www.notion.so/UI-Components-5ccd2bf83eb8441892a0b72c0d8929e1)
[Styling guidelines](https://www.notion.so/Extension-Frontend-Engineering-Guide-b82ddb3e14004b5db3799a9b446294a9#49aa2ef7b7aa40178ff918043df71c34)
Testing guidelines: TBC

### Files needed
- `index.js`
- `index.scss`
- `header-menu.js`
- `header-menu.stories.js`
- `header-menu.test.js`
- `README.mdx`

### Technical details
TBC

### Acceptance criteria
- [ ] Uses color, typography, shadows design tokens 
- [ ] Uses semantic html
- [ ] PropTypes have descriptions
- [ ] Has storybook story with controls
- [ ] Has documentation in MDX
- [ ] Has unit tests and 90% coverage
- [ ] Works in Chrome and Firefox
- [ ] Performance tested: no unnecessary re-renders or other performance concerns

**Comment by Akatori-Design** [comment]
Design is ready for this. 
https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=9917%3A36917&t=KVGndWCDUbCoktKO-4

Name is "Header Menu" to be more specific.
cc: @georgewrmarshall

**Comment by georgewrmarshall** [comment]
Thanks @Akatori-Design I've updated to "HeaderMenu" and updated Figma file link 🙏

**Comment by georgewrmarshall** [comment]
App component not going to be created by DS team
