### ISSUE TITLE
Create component: Popover

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#15096]
### Description
Create a reusable UI component for `Popover`

### References
[Popover Audit FigJam](https://www.figma.com/file/KP10I7OHiuUsGZ53xAgZTj/Popover-Audit?node-id=0%3A1&t=kGBSDbX9zf1MTbwO-1)
[Figma Link](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=10419%3A42608&t=LcCWHavjed6yjut9-1)
[UI component guidelines](https://www.notion.so/UI-Components-5ccd2bf83eb8441892a0b72c0d8929e1)
[Styling guidelines](https://www.notion.so/Extension-Frontend-Engineering-Guide-b82ddb3e14004b5db3799a9b446294a9#49aa2ef7b7aa40178ff918043df71c34)
Testing guidelines: TBC

### Files needed
- `index.js`
- `index.scss`
- `popover.js`
- `popover.stories.js`
- `popover.test.js`
- `README.mdx`

### Technical details
TBC

### Acceptance criteria
- [ ] Uses color, typography, shadows design tokens 
- [ ] Uses semantic html
- [ ] PropTypes have descriptions
- [ ] Has storybook story with controls
- [ ] Has documentation in MDX
- [ ] Has unit tests and 90% coverage
- [ ] Works in Chrome and Firefox
- [ ] Performance tested: no unnecessary re-renders or other performance concerns

**Comment by Akatori-Design** [comment]
In design, this has been renamed to "Pop Over" to distinguish from selector dropdown menus.

**Comment by georgewrmarshall** [comment]
@Akatori-Design Have updated ticket to "Popover" as per Figma file

**Comment by Akatori-Design** [comment]
cc: @garrettbear 
Can I squeeeeze in these style updates? 

- border radius : `16 `-->`8` (i think we briefly discussed this sometime ago for consistency but design wasn't updated)
- shadow : `Md` --> `Sm` ( per doc "Sm" is correct, idk why i had it as "Md")
- border color : `border.default` --> `border.muted` ( to make design team happy, but actually looks better this way in dark mode)

**Comment by georgewrmarshall** [comment]
Closed by https://github.com/MetaMask/metamask-extension/pull/18805
