### ISSUE TITLE
Metamask infinite loading after password entry

### ISSUE THREAD

**Issue by daniphilia** [MetaMask/metamask-extension#1510]
The only thing that fixed it was restoring the account with my seed phrase.
I was inputting the correct password.

**Comment by frankiebee** [comment]
How long have you had MetaMask installed for?

**Comment by flyswatter** [comment]
Yeah my guess is that he had an old light wallet based vault that we were unable to migrate. Would be nice to show the errors here.

**Comment by daniphilia** [comment]
Uh.. How would I check that? I've definitely had MetaMask installed for a few months.

**Comment by flyswatter** [comment]
We could've checked before you restored.  No we can only speculate.

Did you not use MetaMask for a period before the long spinner?

**Comment by Blindmikey** [comment]
I too am having this issue. Should I restore using seed phrase?

**Comment by flyswatter** [comment]
Yes @Blindmikey that is probably the thing to do in this case.
