### ISSUE TITLE
[Bug]: Metamask will not open Unlock modal after 'eth_requestAccounts' call

### ISSUE THREAD

**Issue by jurosh** [MetaMask/metamask-extension#15105]
### Describe the bug

Metamask stopped opening Unlock popup after following call `ethereum.request({ method: 'eth_requestAccounts' });`
After manual unlock of MetaMask and refreshing page `request` call works.

### Steps to reproduce

1. Open browser
2. Quickly open any site & have MetaMask in locked state
3. Run in console `ethereum.request({ method: 'eth_requestAccounts' });`
4. See nothing happening (MetaMask should open modal with Unlock screen)

### Error messages or log output

```shell
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
contentscript.js:1 MetaMask: Content script lost connection to "MetaMask Background Multiplex". undefined
contentscript.js:1 MetaMask: Muxed traffic for channel "metamask-provider" failed. undefined
contentscript.js:1 MetaMask: Content script lost connection to "MetaMask Background Legacy Multiplex". undefined
contentscript.js:1 MetaMask: Muxed traffic between channels "provider" and "metamask-provider" failed. undefined
contentscript.js:1 MetaMask: Muxed traffic for channel "publicConfig" failed. undefined
```

### Version

10.16.1

### Browser

Chrome

### Operating system

Linux

### Additional context

Seems like steps to repro (opening any website) must be done quickly after opening browser.

**Comment by vandan** [comment]
Could not reproduce on Chrome (MacOS). Needs reproduction with Chrome on Linux.

**Comment by schmanu** [comment]
I keep running into the same or a similar error and described a way to reproduce it quite reliably here:
https://github.com/safe-global/web-core/issues/1474

Currently I run into this bug on a daily basis. Luckily a simple page refresh fixes it but still it is quite confusing / annoying.

I can reproduce it with Chrome on MacOS. I was also able to reproduce it in different web3 dapps like curve.fi for instance.

**Comment by karen-forte** [comment]
I could realize that the issue happens when I'm already connected with some account.

https://user-images.githubusercontent.com/87494209/213234893-107ceb93-2bf4-4b61-ae60-3e0cc25559a8.mov

**Comment by fmoyaj** [comment]
Still experiencing this issue on a daily basis. Refreshing the website I am trying to connect to is the only thing that lets me connect
