### ISSUE TITLE
[Bug]: hex string '0x0xdc4787614754b7ac3a7a4faed00f3cbd6a7e96148b' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 46 bytes

### ISSUE THREAD

**Issue by mohammad-aliyari** [MetaMask/metamask-extension#15124]
### Describe the bug

Hi,
I have tried to deploy a token on XDC Mainnet, The transaction is successful on https://explorer.xinfin.network/ but Metamask got stuck on `pending` status. After checking the logs I found an error which I put in the proper box.

and also this is the link to check the transaction:

https://explorer.xinfin.network/tx/0xd9cb9d604cb3c4e5f5aeedd4913fbd348ccb8700a15aef7b87c13befa783c8f0

I think I can not get the confirmation on metamask. Also, I checked the article about increasing the Gas limit but it did not work.
Thanks in advance for your consideration.

### Steps to reproduce

1. Adding XDC Mainnnet with the following data:
 New RPC URL: https://rpc.xinfin.network
Chain ID: 50
Currency Symbol: XDC
Block Explorer URL(Optional): https://explorer.xinfin.network

2. Deploying a token through an application
3. Waiting for confirmation but get stuck on `pending`

### Error messages or log output

```shell
"warning": {
        "error": "[ethjs-query] while formatting outputs from RPC '{\"blockHash\":\"0xfd48d9c89a1cce266a8838364185a6a942a811c5931503d65711d9124119d29f\",\"blockNumber\":\"0x2cdf095\",\"contractAddress\":\"xdc4787614754b7ac3a7a4faed00f3cbd6a7e96148b\",\"cumulativeGasUsed\":\"0x32b620\",\"from\":\"xdc2ed9d53a104879a29c7fbf7dfbf4c6d32a87cc30\",\"gasUsed\":\"0x32b620\",\"logs\":[],\"logsBloom\":\"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"status\":\"0x1\",\"to\":null,\"transactionHash\":\"0xd9cb9d604cb3c4e5f5aeedd4913fbd348ccb8700a15aef7b87c13befa783c8f0\",\"transactionIndex\":\"0x1\"}' for method 'getTransactionReceipt' Error: [ethjs-format] hex string '0x0xdc4787614754b7ac3a7a4faed00f3cbd6a7e96148b' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 46 bytes",
        "message": "There was a problem loading this transaction."
      },
```

### Version

10.16.1

### Browser

Chrome

### Operating system

MacOS

**Comment by lukerQuant** [comment]
Looks like metamask is not used to XDC network's xdc prefix (XDC replaced 0x with xdc)

**Comment by gzliudan** [comment]
I will work on this problem from November.
