### ISSUE TITLE
Build changes for MV3 e2e tests

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15127]
1. create build for running e2e in MV3
2. create job to run e2e for MV3
3. modify metamask-extension/development/build/static.js to update statsMode in runtime-lavamoat.js when building MV3 in test mode

**Comment by segun** [comment]
Questions:

The benchmark scripts run using node...

`SELENIUM_BROWSER=chrome node test/e2e/benchmark.js`

how do we apply lavamoat to it.
