### ISSUE TITLE
[Bug]: Ethereum Integer Overflow "Gas Free" Minting RPC Backdoor

### ISSUE THREAD

**Issue by jilky** [MetaMask/metamask-extension#15132]
### Solidity Hacking: Integer Overflow
**Integer overflows and wraparounds** are featured on the [Most Common Weakness Enumeration (CWE) list](https://cwe.mitre.org/top25/archive/2022/2022_cwe_top25.html#cwe_top_25) of the **most common bugs, faults, or errors for hardware and software.** Integer overflows occur when a value exceeds the maximum value that a variable can contain, and integer overflows happen when a value becomes too small to fit. This results in an unsigned variable that constrains the maximum value that it can hold.  
### Integer Overflow in Ethereum
In Solidity, you can perform many different operations with numbers. This common issue is present in multiple [Ethereum](https://etherscan.io/), [Arbitrum](https://arbiscan.io/), [BNB Smart Chain](https://bscscan.com/), and [Polygon](https://polygonscan.com/) networks including Ethereum Test networks such as [Ropsten](https://ropsten.etherscan.io/), [Kovan](https://kovan.etherscan.io/), [Rinkeby](https://rinkeby.etherscan.io/), and[ Görli. ](https://goerli.etherscan.io/)

There are two types of integers in Solidity:
- **Uint: unsigned integers** - positive numbers ranging from 0 to 2 (2²⁵⁶ - 1) [UINT_MIN, UINT_MAX]. 
- **Int: signed integers** - both positive and negative numbers ranging from -2²⁵⁵ to (2²⁵⁵ - 1), [INT_MIN, INT_MAX].

![60e2b4ccbb7c493f9aa23e4e_1 v1Kp3-rqU1TKzxBqmASv_A](https://user-images.githubusercontent.com/17280090/176990294-fecc624d-0c9d-4a7c-8de5-eb70bd00fcc3.png)

### Steps to reproduce

1. Connect Metamask to Web3 (Etherscan, Bscscan, Polyscan) 
2. Edit the smart contract with #WriteProxyContract
3. For  ```batchTransfer``` type ```-1``` 
```

Attacker performs -1 request with ```mint, transfer, transferFrom, batchTransfer``` 


### Error messages or log output

```shell
POST / HTTP/2
Host: polygon-rpc.com
Content-Length: 452
Sec-Ch-Ua: " Not A;Brand";v="99", "Chromium";v="96"
Accept: application/json
Content-Type: application/json
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Sec-Ch-Ua-Platform: "Linux"
Origin: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn
Sec-Fetch-Site: none
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
{"id":6078673470407,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0x02f8b48189038506fda080818506fda08081840183e0c99424834bbec7e39ef42f4a75eaf8e5b6486d3f0e5780b844a9059cbb00000000000000000000000023bff60d74d558119d92d059b9dab91a63afa5a5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc001a069d447b8f1610cce3d397ec9c68e4a3d806df6824dde637e4c5c5fa226cb0126a037e42699e209b8d653332cfb41c80560a33cf4677ad1b02aa6f5c9b170fb37d5"]}
```

### Version

10.14.7

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

Ledger, Other (please elaborate in the "Additional Context" section)

### Using Integer Overflow to Perform an Attack on Ethereum Network (Related Issues)
![overflow](https://user-images.githubusercontent.com/17280090/176990443-16f50ec9-0cd5-4ab3-b674-4d5b3ceebbf2.png)
-

![beautychain](https://user-images.githubusercontent.com/17280090/176990576-8c476b2e-3578-429d-99da-9301bc802d97.png)
- [BeautyChain (BEC)](https://etherscan.io/tx/0xad89ff16fd1ebe3a0a7cf4ed282302c06626c1af33221ebe0d3a470aba4a660f) ```_value (uint256) -1 ```

**Comment by bschorchit** [comment]
Hey @jilky, thanks for submitting this, but team has already provided feedback for this through HackerOne. Reiterating it here:

> I agree that there exists some contracts on every EVM-based chain that are susceptible to {over,under}flow attacks, however this is not a security concern of the MetaMask product as we do not control those vulnerable smart contracts.
