### ISSUE TITLE
Update Transaction Finalized and Transaction Submitted events to have more relevant metrics for token allowances

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15149]
## Background
[User story on Notion](https://www.notion.so/Implement-and-update-metrics-events-related-to-token-allowances-48ec58b8365843c9a5bd0759cb4c648e)

Currently, on extension we track token allowances within `type` property of transactions events in MetaMetrics. But we don't know much about it other than the fact that the transaction was a token allowance. 
In contrast, on mobile we have more detailed information that help us understand the user mental model and behavior to continuously improve this experience for them. This update will allow us to gain this knowledge on extension as well. 

We want to release this update before we implement and release the work defined in https://github.com/MetaMask/MetaMask-planning/issues/151 , https://github.com/MetaMask/MetaMask-planning/issues/149 and https://github.com/MetaMask/MetaMask-planning/issues/150 so we have baseline metrics to compare against and evaluate if the improvements we made with those were indeed effective.

## Acceptance Criteria

The `type` property for `Transaction Finalized` and the `Transaction Submitted` events are now replaced by the below defined `transaction_type` property with the following values and additional properties:

**`transaction_type`** (string): *send, contract_interaction, cancel*

- if *transaction_type* = *send* or *contract_interaction*:
    
    **`transaction_speed_up`** (boolean): *true, false*
    

- if *transaction_type* = *contract_interaction*:
    
    **`transaction_contract_method`** (string): *name_of_contract_method_here*
    
    - if *transaction_contract_method* = *approve* **&** *token_standard = ERC20*:
      **transaction_approval_amount_type** (string): *custom | revoke | dapp_proposed*

        - if *transaction_approval_amount_type* = *custom* or *dapp_proposed*:
         **`transaction_approval_amount_vs_balance_ratio`** (number - [0.00, infinity)): *allowance_amount_in_relation_to_token_balance* - the allowance amount in relation to the balance for that specific token

        - if *transaction_approval_amount_type* = *custom*:
         **`transaction_approval_amount_vs_proposed_ratio`** (number - [0.00, infinity)): *allowance_amount_in_relation_to_dapp_proposed_value* - the allowance amount in relation to the dapp proposed amount for that specific token

**Comment by danjm** [comment]
@danjm to break this into 3 tickets:
- one for transaction type and contract method
- one for transaction speed up
- one more transaction approval amount

**Comment by bschorchit** [comment]
Closing in favor of:

- https://github.com/MetaMask/metamask-extension/issues/15151
- https://github.com/MetaMask/metamask-extension/issues/15152
- https://github.com/MetaMask/metamask-extension/issues/15150
