### ISSUE TITLE
[Bug]: MM no longer open signing popover interface

### ISSUE THREAD

**Issue by cesarenaldi** [MetaMask/metamask-extension#15142]
### Describe the bug

Starting from yesterday (Tue 5th July) MM pop-over stopped showing up as result of request from a DApp.

I can see the requests counter in the MM icon incrementing and if i click on the icon the pop-over shows up with my pending requests and I can complete the task.

But when I would normally see the pop-over appear on its own, it's no longer doing that.

### Steps to reproduce

Interact with any DApp for any operation that would normally show a pop-over interface (switch network, sign, etc.).

Very occasionally I see the pop-over showing up when interacting with a new DApp but it shortly stop working. Couldn't pin-point an exact scenario unfortunately.

Restarting the browser helps for the first 1-2 pop-over requests. Then same buggy behaviour.

### Error messages or log output

```shell
None.
```

### Version

10.16.1

### Browser

Brave

### Operating system

MacOS

**Comment by danjm** [comment]
@cesarenaldi Do you have another wallet extension installed? That can interfere with the MetaMask popup.

**Comment by cesarenaldi** [comment]
No, no changes on extensions nor the Brave Wallet (still not activated). Basically it just started this behaviour, also other colleagues notice it starting acting in this way since yesterday.

**Comment by danjm** [comment]
@cesarenaldi Could you open the background console of the extension, and then recreate the error you are seeing, and then report an error messages you see in the console?

To open the background console:
1. Go to brave://extensions
2. Toggle on "Developer Mode" in the top right corner
3. Click "background.html" for the metamask extension
4. Click the Console tab of "background.html"

Video demonstration attached


https://user-images.githubusercontent.com/7499938/177615487-01aa57a0-eb5e-4e08-84e6-d3eb7a59d123.mp4

**Comment by cesarenaldi** [comment]
After the very last browser restart it's not longer happening, used to take few tx signing to present itself.

Will keep an eye on it and close this issue in the coming days if cannot longer reproduce.

**Comment by cesarenaldi** [comment]
Closing this as cannot longer reproduce.
