### ISSUE TITLE
Add event tracking for Sign-in with Ethereum

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#15155]
### Describe the bug

We want to track at least three events:

- Signature Approved
- Signature Requested
- Signature Canceled

with these properties/values:

- account_type - [default, imported, undefined, hardware]
- account_hardware_type - [ledger, trezor, lattice, qr_code]
- chain_id - [0x1, ...]
- signature_type - [personal_sign, eth_signTypedData, eth_sign, encrypt, decrypt]
- url - full url
- validation_errors (list) - []

We possibly capture the validation error without a separate event. Imagine we want to know how often a validation event occurs (check Signature Requested), but also how often that deters someone from signing (eg check the Approved/Rejected for validation errors)

### Steps to reproduce

n/a

### Version

10.16.2

### Browser

Chrome

### Operating system

MacOS

**Comment by kevinghim** [comment]
Resolved via https://github.com/MetaMask/metamask-extension/pull/15120

**Comment by worldlyjohn** [comment]
updated event properties for the 3 events above:
- account_type (string): metamask, imported, hardware (see EVENT.ACCOUNT_TYPES)
- expiry_in_days
- chain_id (string): chain_id_in_hex_here
- signature_type (string): personal_sign, eth_signTypedData_v4, eth_sign, encrypt, decrypt
- source_domain (string): custom prop from source_url
- source_url (string): url with path but no query params
- ui_customizations (List): sign_in_with_ethereum

If `account_type=hardware` then add:
- account_hardware_type (string): ledger, trezor, lattice, QR Hardware (see DEVICE_NAMES from constants/hardware-wallets)
- account_hardware_version (string): hardware_version_here (e.g. S 1.1.0, X 1.1.0)

**Comment by worldlyjohn** [comment]
> > signature_type - [personal_sign, eth_signTypedData, eth_sign, encrypt, decrypt]
> 
> We can probably just track RPC method.

@kevinghim  We want to make sure the set of possible options matches the pattern we defined for `Signature Requested`. For example, if the RPC method returns personalSign as camelCase, but elsewhere it's personal_sign -- we just want uniformity/consistency.

> > url - full url
>
> Would domain work instead of full URL?

Sure. If using domain, please define for property `url_domain`

> > validation_errors (list) - []
>
> Does this mean error message?

Yes, but this can be disregarded.

**Comment by kevinghim** [comment]
@skgbafa please see below on implementation details:

For SIWE, re-use the same 3 events below and just modify/add properties to denote this is SIWE.  We have a new property called `ui_customizations` that takes an array of strings that's defined by ["sign_in_with_ethereum"]
- Signature Approved
- Signature Requested
- Signature Canceled

Example SIWE event for `Signature Requested`:

```Event Name:Signature Requested
Properties:
{
  account_type: "metamask",
  expiry_in_days: 365
  chain_id: "0x1",
  signature_type: "eth_signTypedData_v4",
  url_domain:  "opensea.io",
  url: "https://opensea.io/assets",
  ui_customizations: ["sign_in_with_ethereum"]     <=======
}```

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-extension/pull/16222 was merged
