### ISSUE TITLE
Truncate authorship pill

### ISSUE THREAD

**Issue by hmalik88** [MetaMask/metamask-extension#15162]
Truncate long authorship / origin names systematically across the product.

**Comment by eriknson** [comment]
Across MetaMask's authorship tags, I think we shouldn't include subdomains (_and https://_) to direct user focus towards what matters: the domain.

For the snaps specific authorship tags showing the npm source, I'm not 100% sure we can use the same component or if it alters enough to motivate introducing another one. TBD soon.

<img width="1920" alt="truncation" src="https://user-images.githubusercontent.com/34306844/200806128-e10e8464-4ba5-477d-a1b8-691ffb205718.png">

**Comment by Montoya** [comment]
Is this issue still relevant @eriknson?
