### ISSUE TITLE
Can not change the decimal of native token of custom network

### ISSUE THREAD

**Issue by jongrun** [MetaMask/metamask-extension#15168]
### Describe the bug

When adding a custom network, the metamask will divide the native token amount by 10^18 to get its user representation. This is proper for Ethereum and some other blockchains.  

But for some reason, the number of decimals may not always 18 for some custom network. For example, when the blockchain implement uses int64 as a type for balance, the max value is 2^63-1(+9,223,372,036,854,775,807), about 9*10^18. In this case, using 18 as the number of decimals is obviously inappropriate. Or, the native token is just designed with a smaller number of decimals, like 8.

Therefore, is it possible to support specifying decimals when adding a custom network. If not, what is the reason. Thanks for reading and looking forward to your reply.

### Steps to reproduce

1. Adding a custom network.
2. The metamask divides the native token amount by 10^18 to get its user representation. 

### Version

10.16.2

### Browser

Chrome

### Operating system

MacOS

### Additional context

Related issues: [Changing the metamask display decimal of native token](https://github.com/MetaMask/metamask-extension/issues/11262)
Related doc: [MetaMask does not yet support chains with native currencies that do not have 18 decimals, but may do so in the future.](https://docs.metamask.io/guide/rpc-api.html#unrestricted-methods)

**Comment by bschorchit** [comment]
Hey @jongrun, thank you for your report! Could you share 1-2 examples of such networks so we test it on our side too?

**Comment by jongrun** [comment]
@bschorchit I have not seen such networks by now. Such an example may be under development, as mentioned in [ issue#11262](https://github.com/MetaMask/metamask-extension/issues/11262). 

Meanwhile, the [Metamask Docs](https://docs.metamask.io/guide/rpc-api.html#unrestricted-methods) says that '**MetaMask does not yet support chains with native currencies that do not have 18 decimals, but may do so in the future**.' So I think Metamask has taken this into consideration, it just hasn't been scheduled to be implemented yet. I'm wondering if this feature could be considered on the agenda?

**Comment by heri16** [comment]
+1

**Comment by danjm** [comment]
We do not intend on supporting such networks in the near future. This is not the highest priority at this time, given that there are relatively few users on such networks. However, you are welcome to request this feature here https://community.metamask.io/c/feature-requests-ideas/13. We may return to this in the future if user demand increases.

**Comment by heri16** [comment]
@danjm would you be accepting PRs on this?
