### ISSUE TITLE
Fix fiat conversion rates

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1516]
Cryptonator seems to have broken their price API by incorporating a sort of redirect.

This might be the time to move off it to an infura-backed price API.

First priority is getting prices back online.

**Comment by maurycyp** [comment]
INFURA endpoint: https://api.infura.io/v1/ticker/ethusd

**Comment by Zanibas** [comment]
Fixed by #1552 but will incorporate INFURA or cryptonator as a backup API reference to provide redundancy.

**Comment by maurycyp** [comment]
Our pricing API is documented here http://docs.infura.apiary.io/ .
