### ISSUE TITLE
Cannot read full sending account details on personal_sign view

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#15171]
<img width="219" alt="Screen Shot 2022-07-10 at 10 30 04 AM" src="https://user-images.githubusercontent.com/542863/178155563-ae4eea38-fba0-47cd-9e9a-eb15e6d9a2be.png">

Reproduction steps:
- connect to a site using personal_sign with one account
- Switch to another account
- Have that site initiate a transaction with the former-selected (connected) account
- The warning for which account this is truncates the address in a way that makes it unreadable, and there is no way to view/copy the address either, so there is no way to be confident what account is signing unless you recognize the identicon.

**Comment by bschorchit** [comment]
This will be fixed by: https://github.com/MetaMask/metamask-extension/issues/15705

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-extension/pull/15776 was merged. This should roll out to users on extension version 10.24.
