### ISSUE TITLE
[Bug]: Full RPC endpoint in MetaMetrics event

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#15170]
### Describe the bug

If you add a JSON-RPC endpoint (new Network) that contains a secret like a password or access key, the full URL will be sent to segment.io.

Note: This is also a privacy issue as segment.io shouldn't be receiving details about what RPC endpoints the user is using.

----

Someone looking at a segment.io dashboard or raw data (which is an unknown set of people and potentially hackers) can gain access to paid and/or secret RPC endpoints and then use them to do nefarious things, which could result in the user being a plausible patsy for whatever it is the attacker did.

This is also a privacy issue, as the RPC a user is communicating with should not be exposed publicly unless the user agrees to it.

### Steps to reproduce

1. Add a new Network to MetaMask.
1. For the New RPC URL field set it to `https://example.com/secret-path?secretKey=superSecret`
1. Monitor the network traffic leaving MetaMask destined for segment.io.
1. Notice that the full URL is sent to segment.io.

### Version

10.16.2

### Browser

Brave

### Operating system

Windows

**Comment by MicahZoltu** [comment]
@danfinlay This is the other issue I was referring to (leaking secrets).

**Comment by danfinlay** [comment]
Ty. We could probably just log chainId. I wonder if the origin was letting us debug some kind of issue. Was your primary concern about a secret in the query string, or the whole url?

**Comment by MicahZoltu** [comment]
Both.

The secret leaking I would consider security critical.  You should never be sending user secrets for other services to your server, and definitely not into a data analytics platform where likely a large number of people have read access to them.

Separately, as a privacy concious user I don't want the RPC I use to be shared, especially if it is a private RPC (e.g., hosted on a VPS or something).  This is personally Identifiable Information for anyone running their own node on a remote host, and fingerprinting information for anyone who doesn't use Infura.

**Comment by danfinlay** [comment]
I agree. Maybe we can have a list of known public rpcs that we consider ok to log, and exclude the rest.

**Comment by MicahZoltu** [comment]
What value is provided to the user by logging what RPC they use?  I think this question should be asked, answered, and ideally publicly documented) anytime you are doing anything that could fingerprint or otherwise reduce the privacy of a user.  While I'm sure we won't all agree on what the right trade-off is between value-add and privacy-loss, I think the trade should at least be discussed directly and shared publicly.

A potential litmus test would be that if you think that telling Twitter about the decision to make the trade would result in outrage, it is a hint that maybe the trade isn't as good for the user as one would hope.  By *actually* telling Twitter about these tradeoffs, you can get feedback to help you better draw a line in the future that aligns with user demands and isn't as strongly influenced by internal company demands.

**Comment by danfinlay** [comment]
> What value is provided to the user by logging what RPC they use? I think this question should be asked, answered, and ideally publicly documented)

Yup, agreed, that will naturally be part of this work, I’m just taking the convo as far as we can have it before someone more informed steps in.
