### ISSUE TITLE
[Bug]: Wrong link for Edit Nonce on Approval Transaction

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15195]
### Describe the bug

**Problem**: when I'm on the Approval screen, if I have the Customize Nonce enabled I can click on Edit Nonce. There I see that the link "learn more" redirects me to an article for Speeding Up or Cancel a transaction, which is not related

https://user-images.githubusercontent.com/54408225/178471564-70364554-e881-4c40-b6ed-691ecb61a6fc.mp4

.

### Steps to reproduce

1. Unlock MM
2. Go to Settings/Advanced
3. Enable Customize Nonce
4. Go to [Test Dapp](https://metamask.github.io/test-dapp/)
5. Connect MM
6. Click Create Token and Accept Tx
7. Click Approve Tokens Without Gas
8. Click Edit Nonce
9. Click Learn More link

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
[Relevant slack thread](https://consensys.slack.com/archives/G8RSKCNCD/p1657892387365759?thread_ts=1657801224.476699&cid=G8RSKCNCD)
