### ISSUE TITLE
Please update metamask to the latest version in firefox addons

### ISSUE THREAD

**Issue by zed-wong** [MetaMask/metamask-extension#15200]
> Hi @htmnk, thank you for reporting this!
> 
> The fix has actually been released just 14 days ago with version `10.15.0`. I hope this is working for you now. https://github.com/MetaMask/metamask-extension/releases/tag/v10.15.0

Guys don't forget to update in the firefox store.

_Originally posted by @zed-wong in https://github.com/MetaMask/metamask-extension/issues/12416#issuecomment-1166436977_

It's still not updated, please just update it.

**Comment by bschorchit** [comment]
Heey @zed-wong, thank you for you report! We are having some issues with the firefox release submission that's why we don't have the latest releases there. We are actively working on fixing it. In the meantime, you can use the latest version in other browsers too.

**Comment by zed-wong** [comment]
Thanks!
