### ISSUE TITLE
Create a new token component

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#15215]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14122)

## Acceptance Criteria

1. We show the token icon, followed by the token symbol, followed by two clickable icons as per design
![Screen Shot 2022-07-13 at 15 47 21](https://user-images.githubusercontent.com/34968356/178808466-d65ccd1c-3435-46e6-b56a-179b7e99dee6.png)
2. By clicking in the first icon, the token contract address is copied to the clipboard
3. By clicking in the second icon, we open the token page on the block explorer
4. Both icons should have a h-over tooltip: 
First icon - "Copy icon" -> "Copy to clipboard"
Second icon "Open in block explorer icon" -> "Open in block explorer"

**Comment by EHaracic** [comment]
### Open questions:
- Should we have a tooltips on the icons?

**Comment by bschorchit** [comment]
Yes, we should have the tooltips.

**Comment by EHaracic** [comment]
@bschorchit 

Please check the tootip texts: 

First icon - "Copy icon" -> "Copy to clipboard"
Second icon  "Open in block explorer icon" -> "View account on the Etherscan"

**Comment by bschorchit** [comment]
Copy for tooltips should be: 
First icon - "Copy icon" -> "Copy to clipboard"
Second icon "Open in block explorer icon" -> "Open in block explorer"
