### ISSUE TITLE
Update "Token Allowance" screen

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#15211]
Update "Token Allowance" screen per new design

![Screen Shot 2022-07-13 at 18.11.52.png](https://images.zenhubusercontent.com/61e705ae78964374054c3ed0/d23e600a-b67f-46cd-8613-bd01553e8ab4)

## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14122)

## Acceptance Criteria

1. Copy update --> Title

Current copy: “Give permission to access your [token]?"
**NEW copy**: "Set a spending cap for your"

2. Copy update --> Confirm button

Current: "Confirm"
**NEW:** "Next"

3. Button functionality update

Clicking on the "Next" (previously Confirm) button will take user to the "Review Your Spending Cap" screen

4. The "Verify contract details" link is added to both token allowances screens (a.k.a Set spending cap & Review spending cap)
![Screen Shot 2022-07-13 at 16.25.46.png](https://images.zenhubusercontent.com/61e705ae78964374054c3ed0/0d20e7c7-5cf7-4398-b361-dea01f10fd0e)

5. Clicking on the link opens the `Contract details` modal
![Screen Shot 2022-07-13 at 15 52 23](https://user-images.githubusercontent.com/34968356/178809316-545c584b-b317-4916-9448-57cb22bc193c.png)

6. On the first token allowance screen (a.k.a. "Set a spending cap"), the navigation header should display `1 of 2` on the right side (1st screenshot).
![Screen Shot 2022-07-13 at 14 23 53](https://user-images.githubusercontent.com/34968356/178793702-8018afcd-ebec-4013-8ec4-8caa0b06144a.png)

**Comment by EHaracic** [comment]
### Acceptance Criteria
- Update "Token Allowance" screen per new design
![image](https://user-images.githubusercontent.com/49436614/181244437-4c9378cd-d000-4891-8399-fecc23f6b8b0.png)

**Comment by bschorchit** [comment]
Only comment on the above AC: let's continue to use "Reject" as the copy for the reject/cancel button. No changes needed there.

**Comment by bschorchit** [comment]
Just for easier visibility: this is currently blocked by https://github.com/metamask/metamask-extension/issues/15224 which in turn is blocked by https://github.com/MetaMask/metamask-extension/pull/15679

**Comment by filipsekulic** [comment]
Update from @bschorchit after today's meeting.

_Answering the question regarding the edit button on the custom spending cap screen:

If the user has clicked on “Use default” we can hide the “Edit” as long as the user can click on the input box and edit the value there. And once they edit the value we should show “Use default” as an option again._
