### ISSUE TITLE
Create review spending cap component

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#15212]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14202)

## Acceptance Criteria

1. TBD
2.

![Screen Shot 2022-07-13 at 16.19.29.png](https://images.zenhubusercontent.com/61e705ae78964374054c3ed0/38ac1f1b-2c42-42c6-acad-f7a78b2d339d)

2. Clicking on `edit`, takes the user back to the first token allowance screen (a.k.a. Set spending cap screen)

**Comment by EHaracic** [comment]
### Acceptance Criteria

**Comment by bschorchit** [comment]
Edits I have made to the AC comment above for awareness:

> Note on something that differs from design: the main copy for this screen should be "Review the spending cap for your" instead of "Review your spending cap".

**Comment by bschorchit** [comment]
Regarding the open questions:
1. Yes, that's intended.

2. I've updated the tool tip text to: "The contract might be able to spend all your token balance without further notice or consent. Protect yourself by customizing to a lower spending cap."

3. High amounts should be amounts higher than the current balance for that token
