### ISSUE TITLE
Update origin pill component to match the new design

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#15213]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14158)

This origin pill already exists and we currently show it when you a dapp requests you to switch from one network to the other.

## Acceptance Criteria

1. The component is updated to match the new design
![Screen Shot 2022-07-13 at 16 01 37](https://user-images.githubusercontent.com/34968356/178811224-e859441d-07d2-40ee-95e0-d03fd97c2591.png)

### Note:
The component is part of both screens: "Set spending cap" and "Review/Revoke spending cap:, image below
![image](https://user-images.githubusercontent.com/49436614/182326323-27e2c1ff-37ab-4cf5-92f1-f71ad82ff6ed.png)

**Comment by EHaracic** [comment]
@bschorchit 

Currently we have a different design on the switching network, see image below
![image](https://user-images.githubusercontent.com/49436614/180987494-6b90ec43-dfa0-4864-9907-752b7b68ad15.png)

@amerkadicE implemented a "two row" design on the ticket: 
[Display of current network causes confusing UX on switch custom network modal. #12691](https://github.com/MetaMask/metamask-extension/issues/12691)

**Comment by bschorchit** [comment]
You're correct. This PR https://github.com/MetaMask/metamask-extension/pull/15136 seems to have updated it though to a single row. It's not in prod right now, but it's part of the v10.19 release. I'll check with Saya on Monday which is the correct format we should use moving forward.

**Comment by bschorchit** [comment]
I've spoken with Saya and we should move forward with the **single row** version for this component. cc: @EHaracic
