### ISSUE TITLE
Add navigation header to token allowance screens 

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15221]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=1825%3A11818)

## Acceptance Criteria
On the first token allowance screen (a.k.a. "Set a spending cap"), the navigation header should display `1 of 2` on the right side (1st screenshot).
![Screen Shot 2022-07-13 at 14 23 53](https://user-images.githubusercontent.com/34968356/178793702-8018afcd-ebec-4013-8ec4-8caa0b06144a.png)
 
On the second token allowance screen (a.k.a. "Review the spending cap"), the navigation header should have a `< Back` button on the left side and display `2 of 2` on the right side (2nd screenshot).
![Screen Shot 2022-07-13 at 14 30 06](https://user-images.githubusercontent.com/34968356/178794872-9ad1aa8f-cb2a-4f38-95da-6a8c4e8e9ccd.png)

**Comment by hilvmason** [comment]
closing -- covered in #15211
