### ISSUE TITLE
Create a custom spending cap component

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15224]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=910%3A1321)

## Acceptance Criteria

1. It follows the input logic described in the Figma file

![Screen Shot 2022-07-13 at 15 40 44](https://user-images.githubusercontent.com/34968356/178807339-4e6571f3-b60a-4b4e-bd85-bf2e5bde8d46.png)

**Comment by EHaracic** [comment]
Input logic:

![image](https://user-images.githubusercontent.com/49436614/180970312-d9dcab71-7a2c-43b5-a11d-2df57025d0bf.png)

open questions: 
- Max is the label?

**Comment by bschorchit** [comment]
I made a small edit in your AC comment, highlighting it here just so you're aware:

> Tooltip text: "When you give a site a high spending cap, your tokens are inherently at risk. Protect yourself by customizing the spending cap." - this differs from copy in the design
