### ISSUE TITLE
Create a new contract details modal

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15226]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=910%3A1321)

## Acceptance Criteria

1. TBD
![Screen Shot 2022-07-13 at 15 52 23](https://user-images.githubusercontent.com/34968356/178809316-545c584b-b317-4916-9448-57cb22bc193c.png)

**Comment by EHaracic** [comment]
Updated screenshot:

**Comment by EHaracic** [comment]
Open questions: 

- Link to the article?

**Comment by bschorchit** [comment]
1. Could you add a screenshot of what the tool tips look like? I've tried to reproduce it, but was not able to. But yes, I think having a tool tip is a good idea. 

2. We're still working on getting this article ready. Let's remove having this sentence "Learn more..." as part of the scope until we have that article ready. We can add this sentence and the link to the article in a different ticket later.

**Comment by EHaracic** [comment]
@bschorchit 
Please find below the screenshots: 
![image](https://user-images.githubusercontent.com/49436614/181026977-f0282eed-45c8-494b-bdcf-8aa254f09c46.png)
![image](https://user-images.githubusercontent.com/49436614/181027269-e40a0e9e-d456-47e0-8ce7-456e66060081.png)

**Comment by bschorchit** [comment]
Thank you, Elvis! Let's keep the tooltips, great catch!

**Comment by bschorchit** [comment]
**Small update**
Copy for tooltips should be:
First icon - "Copy icon" -> "Copy to clipboard"
Second icon "Open in block explorer icon" -> "Open in block explorer"

Same as [here](https://github.com/MetaMask/metamask-extension/issues/15215#issuecomment-1198019132)
