### ISSUE TITLE
[Bug]: Known contract address warning not shown on dapp suggested transactions

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#15233]
### Describe the bug

The known contract address warning is not shown on dapp suggested transactions

Native Send
https://user-images.githubusercontent.com/53189696/178985354-ca826288-24f6-4379-b8e9-24d0800b991c.mov

ERC20 Token Send
https://user-images.githubusercontent.com/53189696/178988035-652e5dd7-a60b-4178-9ed5-75335071aae1.mov

### Steps to reproduce

Steps:
1. Trigger a `eth_sendTransaction` to a Known contract address from a dapp
or 
1. Trigger an erc20 `transfer` to a Known contract address from a dapp

Actual:
Native Send : We were not able to estimate gas. There might be an error in the contract and this transaction may fail.
ERC20 Token Send: No Warning

Expected:
Warning: you are about to send to a token contract which could result in a loss of funds. [Learn more](https://metamask.zendesk.com/hc/en-us/articles/360020028092-What-is-the-known-contract-address-warning-)

### Version

10.18.0

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
The known contract address warning is only currently meant to be shown on the Send screen, not on the confirmation screen. Have you ever seen it on the confirmation screen?

**Comment by PeterYinusa** [comment]
> The known contract address warning is only currently meant to be shown on the Send screen, not on the confirmation screen. Have you ever seen it on the confirmation screen?

It is shown on the Send screen. 
I have never seen it shown on the Confirmation screen.
I was just wondering if it should be shown on the confirmation screen for dapp suggested transactions as the Send screen is bypassed.

**Comment by danjm** [comment]
> wondering if it should be shown on the confirmation screen for dapp suggested transactions as the Send screen is bypassed.

For now we don't have any spec or requirement for it to be shown on the confirm screen. The bug fix in v10.18.0 is just to restore past behaviour that would show a warning message if the user unintentionally added a token contract to the recipient field on the send screen.

If we were to add any such warning on the confirmation screen, that would be a new requirement, needing new designs.

Should we have such a warning on the confirm screen? It would only be to protect users from dapps that mistakenly propose transactions to token contracts. We can expect those mistakes to be very rare, as they benefit no one and the dapp would be immediately to blame. We _could_ put a warning in such a case, but I don't think we have ever heard of that problem happening yet.

**Comment by PeterYinusa** [comment]
Sounds good to me, I'll remove this from milestone
