### ISSUE TITLE
UI - Show tooltip for "loose" key clarification

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1523]
> I had expected a tooltip, or link to help explain it.

![image](https://cloud.githubusercontent.com/assets/1474978/26655204/bc297418-460e-11e7-904e-e1b25967ff3f.png)

**Comment by flyswatter** [comment]
Maybe change `LOOSE` to `IMPORT`. Just one more letter.

**Comment by Zanibas** [comment]
This should be part of the UI refactor discussions.

**Comment by flyswatter** [comment]
It appears the "Loose" label was removed recently, closing this.

**Comment by kumavis** [comment]
we have an open ticket to re-add the "loose" babel
