### ISSUE TITLE
[Bug]: When Sending Max Amount and Enabling Enhanced Gas Fees I land on Home instead of on Tx Confirmation Screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15254]
### Describe the bug

**Problem**: when I am performing a Send and I use the Max value button, if I Enable Enhanced Gas Fees from the confirmation screen, I land at Home, instead of back on Confirmation screen. This leaves the tx unconfirmed.
The expected behaviour is to land back on the Confirmation screen, so I can finish submitting the transaction, in the same way it happens if the value of the Send is not the Max.

https://user-images.githubusercontent.com/54408225/179199345-88eef47e-6552-431f-b5df-677656dc5ab8.mp4

 

### Steps to reproduce

1. Unlock MM
2. Make sure you have Enhanced Gas Fees deactivated (from Experimental features)
3. Click Send
4. Introduce a receiver address
5. Click Max amount
6. Click Next
7. Click Enable Enhanced Gas Fees from the top notification
8. Enable the function and click close -- see that you land at Home page instead of back on the Confirmation screen

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This is probably no longer an issue as https://github.com/MetaMask/metamask-extension/pull/16446 has been merged

**Comment by bschorchit** [comment]
Update: https://github.com/MetaMask/metamask-extension/pull/16446 has been included in 10.25
