### ISSUE TITLE
[Bug]: Users have to click "down arrow" to enable "Sign" button

### ISSUE THREAD

**Issue by cvega-vhs** [MetaMask/metamask-extension#15267]
### Describe the bug

This may be a reoccurrence or duplicate of #14666: when a user is prompted to sign/approve a transaction with a very long message, the "Sign" button remains disabled unless the "down arrow" button is clicked.

Having to click the down arrow is confusing and not obvious to some users.

**Screenshot**
![image](https://user-images.githubusercontent.com/101071180/179486324-21015c06-dcd1-4ace-b1a3-1bc5c83f37ad.png)

**Video**
https://user-images.githubusercontent.com/101071180/179487306-eeaef312-f6a1-4eff-8c69-58c20d1a39c0.mp4

### Steps to reproduce

1. Trigger the metamask prompt to sign a transaction with a long message (e.g. using the "Signed Typed Data V4" sign button on the [Metamask test dapp](https://metamask.github.io/test-dapp/))
2. Manually scroll down the message section:
    2.1. via the scroll wheel
    2.2. via the arrow keys
    2.3. via using the mouse on the scroll bar on the right, and dragging it down as far as it will go
4. Click the "down arrow" button to finally enable the "Sign" button

### Version

10.17.0

### Browser

Chrome

### Operating system

Windows

### Additional context

The device this error is being experienced on has a display resolution of 2496x1664

**Comment by dokocat** [comment]
I see https://github.com/MetaMask/metamask-extension/pull/14745 fixed this but you still have to scroll to activate the sign button. The sign button should be active by default and the user should scroll if they want to. Its already like this on Metamask mobile, it should be the same on desktop.

**Comment by bschorchit** [comment]
Hey @dokocat, thank you for your input here. We request the user to scroll down in order to encourage them to read the full message before signing. It's unlikely, for our users own security, that we would want to make it easy for a user to agree to something they not have been shown. And it's very likely that mobile behavior will be updated in the near future to match extension's behavior.

Ps: closing the linked PR that fix this has been merged.

**Comment by addmorebass** [comment]
@bschorchit This is not working anymore when a user scrolls down. The sign button does not enable.

This is on Google Chrome.
