### ISSUE TITLE
[Bug]: Asset name goes outside Asset placeholder on pop-up view

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15268]
### Describe the bug

**Problem**: on the Send transaction & Edit Transaction screens, the Asset name goes outside its placeholder if it's too long and it's opened from the MM icon (pop-up view). See example with RinkebyTest asset:

![image](https://user-images.githubusercontent.com/54408225/179491750-f6d8ab1c-e796-40ed-b62c-08fc1d6235ec.png)

### Steps to reproduce

1. Unlock MM
2. Open MM from the Ico (popup view)
3. Set Rinkeby Network
4. Click Send
5. Select a recipient
6. Select RinkebyETH 

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by ElvirCe** [comment]
@seaona @bschorchit What would be the expected behavior here? If the number is huge should we introduce a vertical scroll like here: 
![Image](https://user-images.githubusercontent.com/98470173/209117553-7c3ef08d-2494-434a-9769-a0a81193ed2c.png)
Or any other way?

**Comment by bschorchit** [comment]
@holantonela could help us with the design question above?

**Comment by holantonela** [comment]
Yes. The entire screen is broken:

- The main `sendto` address does not fit in its container and it overlaps with the close (?) icon.
- The jazz icon at the left of the asset is wrong. We should have an assets icon.
- Long strings in Balance do not fit in that space.
- Long strings in Amount do not fit in that space. 
- Hex data seems a long-type form. We need more than two lines it.

Could we open a main ticket for that? It seems an opportunity to improve all these low-hanging fruits in this critical screen.
