### ISSUE TITLE
[Bug]: Actionable Message on Confirm Transaction view is over Tabs

### ISSUE THREAD

**Issue by ernestognw** [MetaMask/metamask-extension#15271]
### Describe the bug

When sending a transaction which gas estimation can't be calculated, the confirm page is showing an ActionableMessage component, which when scrolled down, it mixes with the page tabs.

<img width="337" alt="Captura de Pantalla 2022-07-18 a la(s) 14 05 16" src="https://user-images.githubusercontent.com/33379285/179510227-d57135a1-6f13-4603-9e28-7702f2fc9cf1.png">

### Steps to reproduce

1. Send any transaction that will revert, so gas estimation can't be set
2. Scroll down until you see the message conflicting with the tabs at the top

### Version

10.16.2

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Related to: https://github.com/MetaMask/metamask-extension/issues/14932 and https://github.com/MetaMask/metamask-extension/issues/14602
