### ISSUE TITLE
[Bug]: Hex Data related to ERC20 token Transfer is cached when editing a Tx and switching asset to ETH

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15274]
### Describe the bug

**Problem**: when I am sending an ERC20 token and I click on Edit a Tx, if I change the asset to ETH, I see that the HEx Data for performing that ERC20 token transfer is cached and will be send along with the ETH tx.

Furthermore, if the user does not have activated Hex Data field, they won't notice they are actually sending hex data along with that transaction.

I think the correct solution should be, if ERC20 token is selected on the Edit screen, then we need to clear the Hex Data related to the previous ERC20 token transfer.

https://user-images.githubusercontent.com/54408225/179533887-fece6512-da68-4107-af37-474ad5e84c1b.mp4

### Steps to reproduce

1. Unlock MM
2. Import any ERC20 token
3. Click send, on that ERC20 token
4. Add recipient
5. Click Next
6. Click Edit tx
7. Change Asset to ETH
8. See hex data
9. Click Next
10. See hex data

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
This should be fixed by https://github.com/MetaMask/metamask-extension/pull/15248

**Comment by bschorchit** [comment]
Closing as fixed with: https://github.com/MetaMask/metamask-extension/pull/15248
