### ISSUE TITLE
[Bug]: Unable to add network in Firefox

### ISSUE THREAD

**Issue by Zaphod101010** [MetaMask/metamask-extension#15294]
### Describe the bug

Adding a network results in a CORS error in FireFox.  UI shows "Could not fetch chain ID. Is your RPC URL correct?"

I found some other bugs reporting this, but they are closed.

### Steps to reproduce

1. Add a network in FireFox

### Error messages or log output

```shell
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://[myNodeURL] (Reason: CORS request did not succeed). Status code: (null).

Failed to fetch the chainList from chainid.network TypeError: NetworkError when attempting to fetch resource.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://chainid.network/chains.json. (Reason: CORS request did not succeed). Status code: (null).

POST https://sentry.io/api/273505/envelope/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7 [HTTP/1.1 429
```

### Version

10.14.7

### Browser

Firefox

### Operating system

MacOS

**Comment by officialsupport-ui** [comment]
Kindly get in touch to resolve this issue

**Comment by Zaphod101010** [comment]
To add some more error details...

Firefox sends an HTTP OPTIONS request to https://chainid.network/chains.json.
The server returns "HTTP/2 405 Method Not Allowed" and the error "CORS Missing Allow Origin".

Then Firefox sends an HTTP GET to https://chainid.network/chains.json, but shows the error NS_ERROR_DOM_BAD_URI

**Comment by PhiMarHal** [comment]
This issue is still a problem as of today.

**Comment by DaMandal0rian** [comment]
I'm also having same issue with adding a custom network, works fine with chrome and brave. Seems to be CORS issues but CORS is enabled on the rpc node

**Comment by DaMandal0rian** [comment]
@Zaphod101010 can you confirm if working with chrome?
