### ISSUE TITLE
Address Rinkeby, Ropsten and Kovan deprecation

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15295]
Infura is currently planning on deprecating their Rinkeby, Ropsten and Kovan RPC endpoints almost immediately after the Merge. Once that happens, users won't be able to use these default networks as is in MM. Rinkeby won't be formally demised until Q2/Q3 2023 so users might still want to use those in the meantime. [Relevant slack thread](https://consensys.slack.com/archives/C028DKZAC79/p1658322079187659?thread_ts=1658248554.164459&cid=C028DKZAC79)

[Updated] Therefore, we should:

- [ ] add a yellow dismissible warning on Rinkeby, Ropsten and Kovan saying `Due to the protocol changes of Ethereum: Rinkeby, Ropsten, Kovan test networks may not work as reliably and will be deprecated soon. Learn more` 
- [ ] EH: Show the message every time a user switches to one of the three test networks. If the user closes the message, we won't show it again until the user switches back to one of the three test networks again. If the user switches back to one of three test networks, we'll show them the message again even thought they might have closed it previously. If the user switches to a different network (that's not one of these three test networks), the warning should not be shown anymore too.
- [ ] Learn more is a link that should direct users to: https://blog.ethereum.org/2022/06/21/testnet-deprecation/
- [ ] We can use [this warning design](https://www.figma.com/file/UniC0neIae4IxKENQMVdEg/Balance-switching-networks?node-id=111%3A2027) for this (with the copy above). 
#### Note
The warning message component should have an x button and close the warning message when user clicks on it.
EH: Screenshot form the mobile version:
![image](https://user-images.githubusercontent.com/49436614/186111465-08b0ce5e-66f2-438c-bc2a-53e63adc529c.png)

In the future post merge, we will remove those networks from our default list.

### Open questions:
No open questions.
All questions answered in the comment:  https://github.com/MetaMask/metamask-extension/issues/15295#issuecomment-1224125505
cc @bschorchit 
- On the mobile screen (screenshot above) there is x button but on the Figma design (https://www.figma.com/file/UniC0neIae4IxKENQMVdEg/Balance-switching-networks?node-id=111%3A2027) we don't. 
**Should we have an x button and close the warning message only when user click on it?** 
- Once when user dismiss the message and switch to one of another 3 test networks should we show the message again, e.g.
 User switch to Kovan network, warning message is shown, user dismiss the message, user switch to Rinkeby network should we show the message? 
- In scenario when user dismiss the warning message, switch to some another network and switch again to same test network the message will not be shown?
- When user dismiss the warning message and leave the MM extension, when user open  the MM extension again the message will not be shown on switching to the same test network? 
- When user lock the MM extension and log in again the massage will be shown on switching to one of three test network?

**Comment by kevinghim** [comment]
I think the sequencing should be:
1. add [this warning](https://www.figma.com/file/UniC0neIae4IxKENQMVdEg/Balance-switching-networks?node-id=111%3A2027) directing users to update the network rpc url if they want to continue to use the network (this applies to all networks MM fails to connect to, not only these testnets);
2. remove the three networks from the default list for new users (they will still be able to add it as a custom network if they want to).
3. enable existing users to edit the rpc url for those three networks;
4. enable existing users to delete those three networks;

Do you agree @bschorchit ?

**Comment by bschorchit** [comment]
After discussing it in slack we have updated the scope for this. I'm updating this issue description accordingly. For reference, here's the [mobile PR](https://github.com/MetaMask/metamask-mobile/pull/4885) for this.

**Comment by kevinghim** [comment]
Another clarification. We should remove Ropsten, Kovan, and Rinkeby, but keep Georli, and add [Sepolia](https://sepolia.dev/)

**Comment by bschorchit** [comment]
> On the mobile screen (screenshot above) there is x button but on the Figma design (https://www.figma.com/file/UniC0neIae4IxKENQMVdEg/Balance-switching-networks?node-id=111%3A2027) we don't.
> Should we have an x button and close the warning message only when user click on it?

Yes, we should have an x button and close the warning message when user clicks on it. If the user switches to a different network (that's not one of these three test networks), the warning should not be shown anymore too.


> Once when user dismiss the message and switch to one of another 3 test networks should we show the message again, e.g. User switch to Kovan network, warning message is shown, user dismiss the message, user switch to Rinkeby network should we show the message?

> In scenario when user dismiss the warning message, switch to some another network and switch again to same test network the message will not be shown?

> When user dismiss the warning message and leave the MM extension, when user open the MM extension again the message will not be shown on switching to the same test network?

> When user lock the MM extension and log in again the massage will be shown on switching to one of three test network?

Trying to answer all the above: we should show the message every time a user switches to one of the three test networks. If the user closes the message, we won't show it again until the user switches back to one of the three test networks again. If the user switches back to one of three test networks, we'll show them the message again even thought they might have closed it previously.
Let me know if this definition is helpful ^ cc: @EHaracic

**Comment by bschorchit** [comment]
> Another clarification. We should remove Ropsten, Kovan, and Rinkeby, but keep Georli, and add [Sepolia](https://sepolia.dev/)

This should be a different ticket as removing and adding test networks is not part of the scope here. We want to have this message in prod for a time before we remove any test network.

**Comment by EHaracic** [comment]
Thanks @bschorchit it is clear now. I will update the initial comment with your answers.

**Comment by kevinghim** [comment]
@bschorchit couple more things.
- We should consider using  blue notification rather than the yellow because this is a notification, not an warning.
- Also, when should the message be triggered? Seems appropriate to have it on the add networks settings page
- We should also consider using “What’s New” to communicate the upcoming changes to testnet

**Comment by bschorchit** [comment]
> - We should consider using blue notification rather than the yellow because this is a notification, not an warning.

I think yellow still applies because it's indeed a warning on the reliability of the network as reported [here](https://consensys.slack.com/archives/GV90KPED9/p1660597601932709?thread_ts=1660590826.510249&cid=GV90KPED9). Wdyt?

> - Also, when should the message be triggered? Seems appropriate to have it on the add networks settings page

The message should be triggered when users switch to one of the affected test networks. Those networks are added by default on MM so users that are on the add networks settings page won't be looking for those networks specifically. I believe it's better to keep this warning in context for test network users.

> - We should also consider using “What’s New” to communicate the upcoming changes to testnet

That's a good point. I'll create a different ticket for it. If this goes on 10.19 we'll be already making two announcements on the what's new though (token detection and popular networks).

cc: @kevinghim

**Comment by bschorchit** [comment]
Created a ticket for the what's new [here](https://github.com/MetaMask/metamask-extension/issues/15693). cc: @kevinghim

**Comment by adnansahovic** [comment]
Hi @bschorchit, I made a pull request and I have two questions. When a user dismisses the warning message and leaves the MM extension, then a user opens the MM extension again will the message be shown again on the same test network? 
Current situation: 

https://user-images.githubusercontent.com/63151811/187747573-bc20aaa2-5474-4f88-9045-9665492cf484.mov

Also, should we show the warning message on the MetaMask Notification page(E2E Test Dapp...)?
<img width="358" alt="Screenshot 2022-08-31 at 12 00 39" src="https://user-images.githubusercontent.com/63151811/187793439-0ffd8cb8-3bb5-4c83-990c-7711696af98c.png">
