### ISSUE TITLE
Expand scroll area in account menu

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#15298]
### Description
The scroll area in the account menu when there are multiple accounts is very tight.

<img width="384" alt="Screen Shot 2022-07-20 at 9 45 29 AM" src="https://user-images.githubusercontent.com/8112138/180037791-bac7de31-f0f2-4ab2-bd4b-c3f4f8f6a578.png">

## Technical details
- Reduce padding around nav items
- Possibly reduce font size within reason

## Acceptance criteria 
- More accounts are visible No. TBC

**Comment by nnnnicholas** [comment]
Re: Acceptance criteria, I would love to see 4 or more accounts at a time here. 

Fwiw I have tons of vertical screen height that's unused. The MM pop-up could be taller, altogether.
<img width="449" alt="image" src="https://user-images.githubusercontent.com/1418561/180045198-8d8bb7cb-8087-43fa-a67d-5b7bb6d2c729.png">

**Comment by georgewrmarshall** [comment]
@nnnnicholas thanks for your comment! We are working on an improved navigation experience. I have increased it to show 3 accounts for the time being.
