### ISSUE TITLE
[Bug]: Capital Letters in Seed Phrase Do Not Trigger an Error

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-extension#15303]
### Describe the bug

When restoring from the seed phrase and capital letters are present in one or more words, there is no indication that the seed phrase is invalid. Clicking on the "Import" or "Restore" button causes the screen to load for an instant, but nothing happens.

https://user-images.githubusercontent.com/2859402/180076814-b9b381d0-8cb9-4abc-9b07-c0b887fb7352.mov

### Steps to reproduce

1. Fresh install of MetaMask
2. Choose to restore a wallet
3. Enter the seed phrase, capitalize one or more letters
4. Click on the Import button

### Error messages or log output

```shell
Uncaught (in promise) Error: Seed phrase is invalid.
  at t.exports.createNewVaultAndRestore (common-1.js:46:32713)
  at Pe.createNewVaultAndRestore (background-8.js:1:67771)
  at async s.<anonymous> (background-4.js:22:11417)
```

### Version

10.17.0

### Browser

Chrome, Brave

### Operating system

Windows, MacOS

**Comment by danjm** [comment]
This has been fixed on develop 
![Screenshot from 2022-11-16 14-58-07](https://user-images.githubusercontent.com/7499938/202263066-8a405faa-ba15-4959-b7f4-acc823cfb87a.png)

**Comment by AlexJupiter** [comment]
It looks like this has been fixed so we can close this issue.
