### ISSUE TITLE
Pending transaction states should be updated on Initialization

### ISSUE THREAD

**Issue by bneiluj** [MetaMask/metamask-extension#1531]
## Issue
Metamask keeps showing pending state for confirmed tx transactions

## Steps to Reproduce

1. Make a tx
2. Wait until the transaction is confirmed and mined (go to https://etherscan.io)
3. When tx is confirmed 
4. Open Metamask 
5. You can see that the transaction is still being displayed as `pending` 

## Expected Behavior

When  a transaction is confirmed I would expect metamask to show transaction number with the little icon
<img width="47" alt="screen shot 2017-06-02 at 19 13 10" src="https://cloud.githubusercontent.com/assets/3680497/26736714/953a6c62-47c7-11e7-8582-2730b2cad512.png">

## Actual Results

The transaction is shown as pending on metamask even if  https://etherscan.io shows the transaction as confirmed 

<img width="36" alt="screen shot 2017-06-02 at 19 14 03" src="https://cloud.githubusercontent.com/assets/3680497/26736733/abb4258c-47c7-11e7-9b0b-07450104bda4.png">

## Environment

MetaMask 3.7.3
Version 58.0.3029.110 (64-bit)

**Comment by bneiluj** [comment]
Restarting Chrome does fix the bug.

**Comment by flyswatter** [comment]
I think I figured this out.

Our [current resubmit logic](https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/controllers/transactions.js#L426) doesn't check if the tx has been mined yet.

Currently we only [check tx status](https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/controllers/transactions.js#L356) when [a new block is observed](https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/controllers/transactions.js#L28), which only happens while MetaMask is running in the background (or the blocktracker catches up, presumably).

I think this means if:

1. you submit a tx, and don't wait for it to confirm
2. Close your browser or computer
3. The tx is mined
4. When re-opening your computer, the `submitted` txs will never be recognized as `confirmed`.

Fix strategy options:

- Check txs for inclusion before each re-submit.
- Check `submitted` tx statuses when first initializing.

**Comment by bneiluj** [comment]
@flyswatter 
I agree but does it mean that `checkForTxInBlock` will then check for each tx sent through Metamask ... ? 😱

**Comment by flyswatter** [comment]
It currently does check for each pending tx sent through MetaMask, which should just be a few at most.

**Comment by bneiluj** [comment]
Ok - only pending tx which makes sense.

**Comment by aelbuni** [comment]
Any update on this problem ?

**Comment by danfinlay** [comment]
That sounds right @aelbuni, we need to add a state for discarding replaced transactions, and an occasional (not every block) check to identifying that state.

**Comment by callaloma** [comment]
@aelbuni that is exactly my problem atm. There is a pending tnx in Metamask that I previously cancelled by another tnx with the some nonce. In etherscan the original tnx isn't recorded anymore since it got cancelled. 
Restarting chrome, reset Metamask with lock did not do the trick. Is there a way out here?

**Comment by callaloma** [comment]
just wanted to give a quick update on how I solved this:

1) delete metamask extension from browser
2) reinstall metamask using seed phrase

**Comment by bneiluj** [comment]
@callaloma This is not a solution but a workaround. 

@danfinlay What about adding a "replaced" state in the `/lib/tx-state-manager.js` ?

**Comment by gocwick** [comment]
whatup with metamask? it keeps resetting and i have to keep importing my acct!!  wtf?

**Comment by danfinlay** [comment]
Hi @gocwick, that isn't related to this issue. It sounds like your browser is having some storage issues, most people don't have this result. Maybe try another browser, and see if you get the same problems.

**Comment by danfinlay** [comment]
If you have any other questions, you can submit them to support.metamask.io
