### ISSUE TITLE
[Bug]: Connect to account from a dapp screen not scrolling

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#15315]
### Describe the bug

I'm unable to scroll and select a specific account below the fold. When I start the scroll, it snaps back to the top

https://user-images.githubusercontent.com/6951929/180298975-23626d29-3494-4a00-8f2d-c4a5a8d9b653.mov

### Steps to reproduce

1. Go to Zapper.fi
2. Click on Connect Wallet
3. Use MetaMask to popup the extension screen
4. Scroll to an account below the fold

### Version

10.14.7

### Browser

Firefox

### Operating system

MacOS

**Comment by Thetoan1** [comment]
> ### Mô tả lỗi
> Tôi không thể cuộn và chọn một tài khoản cụ thể trong màn hình đầu tiên. Khi tôi bắt đầu cuộn, nó sẽ quay trở lại đầu trang
> 
>  Screen.Recording.2022-07-21.at.3.16.19.PM.mov 
> ### Các bước để tái tạo
> 1. Truy cập Zapper.fi
> 2. Nhấp vào Connect Wallet
> 3. Sử dụng MetaMask để bật lên màn hình tiện ích mở rộng
> 4. Cuộn đến tài khoản dưới màn hình đầu tiên
> 
> ### Thông báo lỗi hoặc đầu ra nhật ký
> _Không phản hồi_
> 
> ### Phiên bản
> 10.14.7
> 
> ### Loại xây dựng
> _Không phản hồi_
> 
> ### Trình duyệt
> Firefox
> 
> ### Hệ điều hành
> Hệ điều hành Mac
> 
> ### Ví phần cứng
> _Không phản hồi_
> 
> ### Bối cảnh bổ sung
> _Không phản hồi_

**Comment by php4fan** [comment]
This issue has existed forever. How long can it possibly take to fix it? Don't you realize it renders **Metamask completely ubusable** to anyone who uses more than four accounts?

**Comment by AdamGrausen** [comment]
When do you guys fix it. It's really a bad bug. I will look for another wallet only becourse of that. I have multiple accounts. Please fix.

**Comment by php4fan** [comment]
> When do you guys fix it. It's really a bad bug. I will look for another wallet only becourse of that. I have multiple accounts. Please fix.

There are bugs way more serious than this one that have been starving for months, some even years, it's pathetic.

**Comment by georgewrmarshall** [comment]
Closed by https://github.com/MetaMask/metamask-extension/pull/17075
