### ISSUE TITLE
[Bug]: When I change metamask accounts in chrome extension,then I excute signTypedV4 method,but confirmation not popup.

### ISSUE THREAD

**Issue by KBKUN024** [MetaMask/metamask-extension#15310]
### Describe the bug

I use metamask in my dapp,but when I need to change accounts,signTypedV4 method confirmation not popup,and only shows a number upon metamask extension icon. (The situation I expected is when I excute signTypedV4 method,there should have a external window to sign,but now I don't seen it.)

### Steps to reproduce

1. click chrome metamask extension
2. change account
3. my dapp excute signTypedV4 method
4. external window not display (or confirmation not popup)
5. only display a number upon metamask extension icon

### Error messages or log output

```shell
this is not a error,but it's a feature maybe I guess?
I can explain my assumtion:
when I click metamask extension,metamask detects that I'm entered metamask extension,so when I change account mannualy,the confirmation don't need to popup,because I'm already in metamask,I can click the number upon metamask icon and then sign the message.I don't know the assumtion is right or not,but it can make sense.
```

### Version

10.17.0

### Browser

Chrome

### Operating system

MacOS

### Additional context

https://user-images.githubusercontent.com/54589019/180253206-7cd8bf50-e2f3-41bf-b220-86d626e5e9a4.mp4

**Comment by KBKUN024** [comment]
anyone who can help me?

**Comment by officialsupport-ui** [comment]
Kindly get in touch to get this issue resolved

**Comment by KBKUN024** [comment]
Generally，how long will you take to resolve this issue？



发自我的iPhone


------------------ Original ------------------
From: officialsupport-ui ***@***.***&gt;
Date: Tue,Jul 26,2022 8:11 AM
To: MetaMask/metamask-extension ***@***.***&gt;
Cc: KBKUN024 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [MetaMask/metamask-extension] [Bug]: When I change metamaskaccounts in chrome extension,then I excute signTypedV4 method,but confirmationnot popup. (Issue #15310)





 
Kindly get in touch to get this issue resolved

**Comment by officialsupport-ui** [comment]
30mins to 1hr

**Comment by KBKUN024** [comment]
That's great！Thank you，I'm very appreciated!



发自我的iPhone


------------------ Original ------------------
From: officialsupport-ui ***@***.***&gt;
Date: Tue,Jul 26,2022 1:18 PM
To: MetaMask/metamask-extension ***@***.***&gt;
Cc: KBKUN024 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [MetaMask/metamask-extension] [Bug]: When I change metamaskaccounts in chrome extension,then I excute signTypedV4 method,but confirmationnot popup. (Issue #15310)





 
30mins to 1hr

**Comment by officialsupport-ui** [comment]
+4915510051762

You can send a Dm here t
On telegram

**Comment by KBKUN024** [comment]
Okay👌



发自我的iPhone


------------------ Original ------------------
From: officialsupport-ui ***@***.***&gt;
Date: Tue,Jul 26,2022 1:26 PM
To: MetaMask/metamask-extension ***@***.***&gt;
Cc: KBKUN024 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [MetaMask/metamask-extension] [Bug]: When I change metamaskaccounts in chrome extension,then I excute signTypedV4 method,but confirmationnot popup. (Issue #15310)





 
+4915510051762
 
You can send a Dm here t
 On telegram

**Comment by KBKUN024** [comment]
> +4915510051762
> 
> You can send a Dm here t On telegram

I'm already add you to a new friend,but I can only send a dm to you if we are mutual contacts

**Comment by officialsupport-ui** [comment]
Drop your contact here I will add you up

**Comment by KBKUN024** [comment]
+86 155 2441 5578



发自我的iPhone


------------------ Original ------------------
From: officialsupport-ui ***@***.***&gt;
Date: Tue,Jul 26,2022 2:40 PM
To: MetaMask/metamask-extension ***@***.***&gt;
Cc: KBKUN024 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [MetaMask/metamask-extension] [Bug]: When I change metamaskaccounts in chrome extension,then I excute signTypedV4 method,but confirmationnot popup. (Issue #15310)





 
Drop your contact here I will add you up

**Comment by bschorchit** [comment]
Hey @KBKUN024 , thank for submitting this issue. The team will look into it.
Please do not engage with @officialsupport-ui above as he is not part of the team and MetaMask does not use telegram as a channel to reach out to users.
If you need support from MetaMask team, you can use the link within your MetaMask app or extension to do so.

**Comment by brad-decker** [comment]
@KBKUN024 this person @officialsupport-ui is a scammer, we don't do support through telegram. Please disengage with them immediately and use our official support system https://metamask.zendesk.com/hc/en-us

**Comment by KBKUN024** [comment]
OK，thank you，he use telegram to contact with me，and offer me a link ，but I need to enter my metamask phrase in the site，so I think he maybe lie to me.



发自我的iPhone


------------------ Original ------------------
From: Bárbara Schorchit ***@***.***&gt;
Date: Tue,Jul 26,2022 9:36 PM
To: MetaMask/metamask-extension ***@***.***&gt;
Cc: KBKUN024 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [MetaMask/metamask-extension] [Bug]: When I change metamaskaccounts in chrome extension,then I excute signTypedV4 method,but confirmationnot popup. (Issue #15310)





 
Hey @KBKUN024 , thank for submitting this issue. The team will look into it.
 Please do not engage with @officialsupport-ui above as he is not part of the team and MetaMask does not use telegram as a channel to reach out to users.
 If you need support from MetaMask team, you can use the link within your MetaMask app or extension to do so.

**Comment by KBKUN024** [comment]
ok，thank you，I don't trust him，my account is safe，I‘m looking forward to metamask team to resolve this issue.



发自我的iPhone


------------------ Original ------------------
From: Brad Decker ***@***.***&gt;
Date: Tue,Jul 26,2022 9:36 PM
To: MetaMask/metamask-extension ***@***.***&gt;
Cc: KBKUN024 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [MetaMask/metamask-extension] [Bug]: When I change metamaskaccounts in chrome extension,then I excute signTypedV4 method,but confirmationnot popup. (Issue #15310)





 
@KBKUN024 this person @officialsupport-ui is a scammer, we don't do support through telegram. Please disengage with them immediately and use our official support system https://metamask.zendesk.com/hc/en-us
