### ISSUE TITLE
ENS Registrar Dapp sometimes not recognizing MetaMask Web3

### ISSUE THREAD

**Issue by crowdedconscious** [MetaMask/metamask-extension#1532]
Hey Everyone,

Any idea why I keep getting this on my Chrome browser? It's on and off. I have already won domains, claimed them, and set them up. Multiple bids on the market, but cannot reveal some of them because I keep getting this message at the bottom of my screen. Tried going back and forth between Ropsten and Main, turning extension off and back on, and have exited out of browser and restarted new - still no luck. 

I appreciate the help in advance!

**Comment by flyswatter** [comment]
This seems to be a bug in the ENS registrar dapp, and it's been reported to them:

https://github.com/ethereum/ens-registrar-dapp/issues/150

**Comment by bneiluj** [comment]
@crowdedconscious Refreshing the page often fixe this problem.

**Comment by crowdedconscious** [comment]
@bneiluj - I've done that a couple dozen times over the past hour and nothing :( that tactic was working for me the last couple weeks though! Thank you for your input :D

**Comment by crowdedconscious** [comment]
@flyswatter - thank you much for the resource! I was looking for it in the search and couldn't find the problem so I posted - you rock!

**Comment by crowdedconscious** [comment]
Urgh...left for a while, came back, and still having this problem. When I refresh, it shows my MetaMask working for a split second - shows the reveal button - and then switches back over to the yellow box saying my browser doesn't support.

**Comment by flyswatter** [comment]
I actually think that split-second of "looking like it works" is before the dapp's web3 check. The site stores in local storage that you've placed a bid, and so *it knows* you have the bid, it then just checks for web3 and fails (for whatever reason).

Again, this seems to be a problem with that web dapp, someone even reported they had the same issue with Mist.

ethereum/ens-registrar-dapp#150

**Comment by rstormsf** [comment]
@flyswatter I don't understand why metamask cannot recognize my ENS name (romanstorm.eth) what is wrong with it? It seems fine to me.

**Comment by tmashuang** [comment]
@rstormsf you need to set your resolver.

**Comment by rstormsf** [comment]
How? Where?

**Comment by tmashuang** [comment]
Closing old issue.
