### ISSUE TITLE
[GF UI] Create component: Card

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#15345]
### Description
Create a reusable UI component for `Card`

### References
[Figma component](https://www.figma.com/file/aTBlkFLwSzzAXqQG6uf3fV/1559-mobile-exploration-v3?node-id=341%3A3385)
[UI component guidelines](https://www.notion.so/UI-Components-5ccd2bf83eb8441892a0b72c0d8929e1)
[Styling guidelines](https://www.notion.so/Extension-Frontend-Engineering-Guide-b82ddb3e14004b5db3799a9b446294a9#49aa2ef7b7aa40178ff918043df71c34)
Testing guidelines: TBC

### Files needed
- `index.js`
- `card.scss`
- `card.js`
- `card.stories.js`
- `card.test.js`
- `README.mdx`

### Technical details
- TBC

### Acceptance criteria
- [ ] Uses color, typography, shadows design tokens 
- [ ] Uses semantic html
- [ ] PropTypes have descriptions
- [ ] Has storybook story with controls
- [ ] Has documentation in MDX
- [ ] Has unit tests and 90% coverage
- [ ] Works in Chrome and Firefox
- [ ] Performance tested: no unnecessary re-renders or other performance concerns

### Screenshots

<img width="330" alt="image" src="https://user-images.githubusercontent.com/10508597/180322857-cdec035d-eb34-4950-a760-dd2ededf0c5a.png">

**Comment by spiritanand** [comment]
Hey @georgewrmarshall can I work on creating this component?

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, This is an old ticket and the component may have been updated and in any case isn't going to be worked on by the DS team so I am going to close this ticket. I'll see if I can find a component that might be suitable as a good first issue and will release one if I do. Thanks!
