### ISSUE TITLE
[Bug]: ERC20 token Image broken

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15358]
### Describe the bug

**Problem:** when I Import an ERC20 token (LINK) I see that its image is broken now (in previous versions, it is loaded fine).

https://user-images.githubusercontent.com/54408225/181235733-5bfc5968-45c8-4e98-b2cd-6f7d775995d3.mp4

[**EDIT**] ~~Discovered a further strange behavior. When I add a token (MATIC) and symbol is loaded properly, if I change to another network and then back on the Network where I imported the token, the token image is not properly loaded anymore and now appears as a blocky~~  Separate issue for this one here: https://github.com/MetaMask/metamask-extension/issues/15593

### Steps to reproduce

1. Unlock Metamask
2. Select Rinkeby network
3. Click Import Token
4. Paste LINK token 0x01BE23585060835E02B77ef475b0Cc51aA1e0709
5. Accept and proceed -- see img is broken 

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
Is this only happening on Rinkeby? I don't see it happening on maintain. If everything is working on mainnet and this is just contained to ethereum test nets, I think we can ship without fixing this.

**Comment by seaona** [comment]
@danjm so far I could only see it on Rinkeby yes, so not a blocker.

For the second video, I've seen it's a different issue and this affects Mainnet - but it's on our current develop, so issue will be introduced in the next release, so I will open a separate ticket for 10.20.0
