### ISSUE TITLE
Create a "Revoke spending cap" screen

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15366]
## Resources
[Figma Design File](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14265)

## Acceptance Criteria
1. This screen should be displayed when the dapp proposed value is 0.
![Image](https://user-images.githubusercontent.com/34968356/181352139-ff1c9874-9ef0-466a-8f01-16b4da1bb97f.png)

**Comment by EHaracic** [comment]
Closing the issue as the "Revoke" functionality will be implemented on the issue: https://github.com/MetaMask/metamask-extension/issues/15220
