### ISSUE TITLE
Add "Send Max" button to send screen

### ISSUE THREAD

**Issue by Tectract** [MetaMask/metamask-extension#1537]
It's really difficult to send the FULL balance at any account out from metamask. I want to send all the money in this wallet out to another address, and leave it at zero balance. How can this be accomplished?

**Comment by Tectract** [comment]
There should just be a button for "send max amount"...

**Comment by flyswatter** [comment]
I agree, we've known we should do this for a while, but just haven't gotten to it yet. I'm surprised we didn't have an issue for this yet.

**Comment by Tectract** [comment]
My suggestion is to make the "upwards" arrow go to the "max" transaction amount if you long-click it, or something like that. 

Cheers!

**Comment by Zanibas** [comment]
Was encapsulated in https://github.com/MetaMask/hello/issues/25, but we'll close that one and keep this one open so that we're on the same repo.

**Comment by cjeria** [comment]
@flyswatter 

How about this UX? 

![send copy](https://user-images.githubusercontent.com/597770/29983594-83795818-8f0b-11e7-81dc-030342b480db.png)

**Comment by flyswatter** [comment]
Yeah, that works great.

**Comment by cjeria** [comment]
I know i'm suggesting removing the fiat <> crypto switcher for the max button, but I think this ux makes a lot of sense. @sdtsui thoughts?

**Comment by Zanibas** [comment]
Will ask Jacky about this.

**Comment by Zanibas** [comment]
@chikeichan

**Comment by cjeria** [comment]
![image](https://user-images.githubusercontent.com/597770/30442288-de889136-9930-11e7-9e7c-70ec6e7c703b.png)

**Comment by chikeichan** [comment]
@cjeria Yep this UX looks great. A couple questions:
 - How will it works for the send token screen?
 - What if the exchange rate of a token is unknown to us. We use ShapeShift API to get exchange rate, meaning that we won't have token rate if it is not traded on shapeshift.
- The `From:` input box seems too short for fitting both ETH and USD. It will overflow when ETH gets long, like `100.000001 ETH`. How should we account for this?
- In the `From:` input box, there is no USD amount on desktop mode, but there is USD amount on mobile view.

**Comment by cjeria** [comment]
@chikeichan @flyswatter Redesigned the from account dropdown component to accommodate for long balances.



![send funds screens](https://user-images.githubusercontent.com/597770/30460348-44118852-996b-11e7-8113-97ca31b6add9.png)

**Comment by flyswatter** [comment]
@cjeria I love it. That's by far my favorite account dropdown we've ever had. Is it scrollable? If there are accounts of different types, do we have headings for those sections?

**Comment by starrychloe** [comment]
I recommend making MAX a check box so whenever you change the gas price, the (disabled) AMOUNT field recalculates automatically.

**Comment by wbwvos** [comment]
So any idea on when this will be released? Thanks, it would be an awesome and helpful function!

**Comment by cray935** [comment]
Closed with "won't fix" or what you're doing ?

**Comment by danfinlay** [comment]
This feature is included in the New User Interface that we're rolling out soon. We're not going to add this to the current "old" UI. Look for the New UI option in the top right menu soon, and it'll start rolling out more aggressively from there!

**Comment by danfinlay** [comment]
(The new menu item is likely to ship out early next week, but may be a little buggy at first)

**Comment by cray935** [comment]
Ah cool, thank's for the reply :)

**Comment by Meshugah** [comment]
Is this feature out yet?

**Comment by tmashuang** [comment]
@Meshugah this is out in the Beta Version of MetaMask.
