### ISSUE TITLE
[Bug]: Metamask breaks Google Docs / Sheets documents

### ISSUE THREAD

**Issue by therealmarv** [MetaMask/metamask-extension#15374]
### Describe the bug

Google Docs / Sheets will not finish to load with a set up Metamask extension.
You will get "unable to load file" error in Google Docs
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1050582/181536641-be9be90c-d779-4526-b0e0-ef2baecd36ac.png">

### Steps to reproduce

1. Setup (and finish setup) Metamask with a new wallet (I've only tested with my existing wallets).
2. open Google Drive https://drive.google.com/
3. open an existing Google Docs or Google Sheets document.
4. it fails to load (and works again after deactivating Metamask)

Error from console (Google Docs document). It seems some variable `chainId` is read-only because of Metamask:
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/1050582/181545417-094ddb36-dc53-4b19-9f0c-15adfbf897d8.png">

### Error messages or log output

```shell
n.a., Metamask is locked during whole procedure
```

### Version

10.18.0

### Browser

Brave

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by bschorchit** [comment]
I was not able to reproduce this.

**Comment by SamusElderg** [comment]
+1 i am having the exact same issue, only started happening today first noticed the bug with version: [Version 10.18.0](https://github.com/MetaMask/metamask-extension/releases/tag/v10.18.0) however it might have happened with the previous version: [Version 10.17.0](https://github.com/MetaMask/metamask-extension/releases/tag/v10.17.0) or maybe even the 10.16.XX tree, I'm not 100% sure

![image](https://user-images.githubusercontent.com/26967164/182769096-c2359281-c700-43e7-9c54-b718dc3c7a68.png)

**Comment by therealmarv** [comment]
I noticed this issue with 1.17.0 !
I was hoping it should be gone with 1.18.0 but the same issue remained.

**Comment by dadaas** [comment]
MetaMask Version
10.18.0
Same error, we need fix fast.

**Comment by SamusElderg** [comment]
Hey all, this is a Brave issue, they have a pending PR to fix here: https://github.com/brave/brave-core/pull/14483
