### ISSUE TITLE
Add provider deprecation warnings for `eth_decrypt` and `eth_getEncryptionPublicKey`

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#15379]
The methods `eth_getEncryptionPublicKey` and `eth_decrypt` have been deprecated (see [this announcement](https://medium.com/metamask/metamask-api-method-deprecation-2b0564a84686) for details). We should add console warnings to the provider so that dapp developers can be informed of this deprecation.

**Comment by YVeselovskyi** [comment]
@Gudahtt Hello! Are there any alternative methods to encrypt data?

**Comment by Gudahtt** [comment]
There may be a way to use a signature as an encryption key, but I am not sure on the details of how or whether it would be cryptographically safe.

We hope to restore built-in encryption/decryption methods at some point. Ones we are more confident in.

**Comment by pavlovdog** [comment]
@Gudahtt since signature should include randomness, I don't think it's possible to use signature as a deterministic seed for key generation.

**Comment by pavlovdog** [comment]
Also, I don't see the deprecation warning in current documentation. Does it mean that it's not deprecated anymore?

https://docs.metamask.io/wallet/reference/eth_getencryptionpublickey/
https://docs.metamask.io/wallet/reference/eth_decrypt/
