### ISSUE TITLE
[Bug]:  How can I know which NFT(contract) I am approving in the new confirm panel?

### ISSUE THREAD

**Issue by chendatony31** [MetaMask/metamask-extension#15377]
### Describe the bug

Can not know which contract I am interacting with. That's terrible!

### Steps to reproduce

1. trigger `setApproveForAll` function of NFT contracts

### Version

10.18.0

### Browser

Chrome

### Operating system

MacOS

**Comment by chendatony31** [comment]
As an ERC-1155 NFT does not have a `name` or `symbol`.

**Comment by bschorchit** [comment]
Hey @chendatony31, if you click on the _NFT_ link it'll open the NFT contract on the block explorer so you can review which asset it's.

<img width="359" alt="Screen Shot 2022-07-28 at 16 11 37" src="https://user-images.githubusercontent.com/34968356/181619092-9e7afd65-5609-4cb1-9e83-002cd2221597.png">

**Comment by bschorchit** [comment]
Can you check if that's working for you?

**Comment by chendatony31** [comment]
Yeah, I see. I didn't config a block explorer. So the link opens popup.html itself in the browser. I think it should display the contract on the panel somewhere in the `transaction details`.
