### ISSUE TITLE
[Bug]: Multiple sign requests says "Reject 2 Transactions"

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/metamask-extension#15389]
### Describe the bug

Using a dapp and popping up multiple Sign messages says "Reject 2 Transactions".

They are not transactions, this is confusing. It should read something else, not sure what the text should be. maybe "Reject 2 Signs"

<img width="354" alt="image" src="https://user-images.githubusercontent.com/364566/181910857-f2ba003f-cad2-4134-8daf-f4ff2874256f.png">

### Steps to reproduce

1. Use the test dapp to pop up a sign message prompt and dont sign it
2. pop up the prompt again
3. see that it says "Reject 2 Transactions"

### Version

10.16.1

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Maybe "Reject 2 requests" ?
Also we should update the button's copy to also say "Reject" instead of "Cancel". So it matches the copy below in this case and it also matches this same button on transaction requests.

**Comment by bschorchit** [comment]
And also update replace "transactions" with "requests" here:
<img width="360" alt="Screen Shot 2022-08-02 at 19 57 29" src="https://user-images.githubusercontent.com/34968356/182487444-70c8e41f-1ec3-4a94-a550-072839480981.png">

**Comment by ElvirCe** [comment]
Summary of changes: 
1. Change "Reject 2 transactions" to "Reject 2 requests"
2. When clicked on the Reject 2 requests" link, also update the title to "Reject 2 requests" and the message to "You are about to batch reject 2 requests."
3. For both screens, change the "Cancel" button to "Reject"
