### ISSUE TITLE
[Bug]: Message: f.getNativeCurrency(...) is undefined 

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-extension#15397]
### Describe the bug

The extension auto-updated to 10.18.1, and, after trying to sign in, the following  error message appears: 

Message: f.getNativeCurrency(...) is undefined
Code: TypeError

Workaround: reinstalling the extension

### Steps to reproduce

1. Type the password and click unlock
2. The error message shows up

### Version

10.18.1

### Browser

Firefox

### Operating system

Windows, MacOS, Linux

**Comment by adonesky1** [comment]
I'm a bit unclear on the repro steps here. Do I need to simulate an auto-update?

**Comment by adonesky1** [comment]
@anaamolnar was there any more to that error message? I'm having trouble reproducing it...

**Comment by adonesky1** [comment]
Process I attempted to reproduce:
1. Build 10.14.7 and load in Firefox
2. Lock the app (not sure if this is considered a necessary step for the repro)
3. Build 10.18.1 in another directory
4. Copy contents of `dist/firefox` from 10.18.1 build
5. Paste into `/dist/firefox` of 10.14.7
6. Open MetaMask
7. Here I expect to see the error or the lock screen, but I see MM unlocked and working

cc @danjm @tmashuang

**Comment by anaamolnar** [comment]
@adonesky1 No, this is all I have

**Comment by danjm** [comment]
Closed by #15442 15425
