### ISSUE TITLE
[Bug]: Unable to start the extension on Firefox

### ISSUE THREAD

**Issue by tahamin26** [MetaMask/metamask-extension#15390]
### Describe the bug

Today, I am getting the following error constantly:

"MetaMask had trouble starting. This error could be intermittent, so try restarting the extension.

Still getting this message? Send us a bug report. "

### Steps to reproduce

1. Click on the Metamask icon on Firefox.

### Version

10.18.1

### Browser

Firefox

### Operating system

Linux

### Additional context

I am on Ubuntu 22.04.1 LTS. Firefox is installed via snap.

**Comment by tahamin26** [comment]
I have removed and reinstalled the extension. The machine had got frozen earlier so I suppose there happened a corruption in storage. The issue is fixed now.

**Comment by shmup** [comment]
@tahamin26 my friends computer shut off and this is the symptom now, same version. Question: when removing and reinstalling the extension, was the data preserved, or did you have to add the wallet again?

They're concerned because they never made a backup of the seed phrase.

**Comment by tahamin26** [comment]
@shmup The data was gone when I re-installed the extension. It was a fresh install and I had to enter the seed at first.

Your friend's position is tough. I would suggest to create a backup of the extension files (config,cache,everything) no matter what. I hope he can recover his wallet.

**Comment by shmup** [comment]
@tahamin26 yeah it woulda been rough, incredibly happy they were like "wait, I took a picture of this (lol) seed, but it's on an old phone" and then proceeded to find the ole, cracked but functional phone
