### ISSUE TITLE
[Bug]: Metamask stopped working on Firefox

### ISSUE THREAD

**Issue by sanchopansa** [MetaMask/metamask-extension#15391]
### Describe the bug

I'm trying to help a friend to recover funds from a MM software wallet (he doesn't have the seed phrase...). MM stopped working on Firefox/Ubuntu 20.04 for him several days ago after working without any issues prior to that. Currently, when opening the extension, we see an error: "MetaMask had trouble starting. This error could be intermittent, so try restarting the extension." and MM doesn't load at all. We tried restarting/re-enabling the extension, but that doesn't help. 

We also tried following this procedure to recover the wallet: https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data, however

```
chrome.storage.local.get('data', result => {
 var vault = result.data.KeyringController.vault
 console.log(vault)
})
```

returns undefined.

I have a couple of questions:
-- where can we find the vault file on Ubuntu/FF?
-- any idea what might be causing the issue and how to debug it?

Thank you!

### Steps to reproduce

1.

### Version

10.18.1

### Browser

Firefox

### Operating system

Linux

**Comment by shmup** [comment]
Same symptom with my friend. Their computer died and now they're getting this same behavior you mention.

It's the same situation here I think: https://github.com/MetaMask/metamask-extension/issues/15390

In that case, the person reinstalled the extension and all is well.

I'm curious if this is a fine method for us to do, worrying only because they do not have the seed phrase to restore in the case of it nuking everything (on an uninstall)

**Comment by shmup** [comment]
Here's what I'm exploring:

Inspecting the contents of the unzipped `.xpi` and considering files most recently modified, and.. I'm not sure really. Replacing with a fresh xpi's same file. Removing outright. Really just trying anything to salvage my buddy's situation.

**Comment by shmup** [comment]
I'm not sure about this localStorage and if it's not really emblematic of anything, being undefined. Could y'all tell me a bit about it?

![image](https://user-images.githubusercontent.com/118710/182259484-32627c73-571b-4706-9f6b-c36d03696d13.png)

**Comment by PeterYinusa** [comment]
Thanks for the report @sanchopansa!

Can you open the following url `about:debugging#/runtime/this-firefox` in Firefox, then click the `Inspect` button to the right of the MetaMask extension? Please let me know if any errors appear in the Console.

<img width="1011" alt="debugging" src="https://user-images.githubusercontent.com/53189696/182644509-aa3647e9-6451-4fa6-8ecd-9184313d1dad.png">

**Comment by ohioaschwar** [comment]
This happened for me in Firefox for Windows 10 as well.

Continually getting this message "MetaMask had trouble starting. This error could be intermittent, so try restarting the extension. "

Tried checking the console as @PeterYinusa described and can see several errors...

notably this one:
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

**Comment by limbo0** [comment]
I'm having the same issue as mentioned above.Unable to log in .Been a few days already.I uninstalled the extension and re installed the extension still same issue.Has anyone resolved it?

**Comment by arsenische** [comment]
Same story, ![image](https://user-images.githubusercontent.com/441555/183858876-48479ec9-7427-45fc-8dc4-5f3d2648c4c8.png)

**Comment by mtown-1** [comment]
@PeterYinusa and @sanchopansa 

same issue, inspect element not possible. Due to not starting . 

Any solution?  

Ty

**Comment by jonurban** [comment]
I'm seeing this bug as well, not seeing .d.a.t.a. in the sqlite hex either

**Comment by mtown-1** [comment]
@jonurban did you remove any cache data from your computer? if not DONT! also do you use firefox or chrome or brave? or any other? do you still have your seedphrase?

**Comment by jonurban** [comment]
I have a backup of all the cache data, I was using firefox...  I'm currently trying to parse all the directories I was able to recover and am going to to try to utilize this script against the recovery files : https://github.com/JesseBusman/FirefoxMetamaskWalletSeedRecovery

**Comment by jonurban** [comment]
I was able to find my secret phrase, so I abandoned this effort.  I did confirm before recovering that running : 
chrome.storage.local.get('data', result => {
 var vault = result.data.KeyringController.vault
 console.log(vault)
})

DOES NOT WORK for this issue, i also ran JesseBusman's script and that was unable to find the vault data as well.  I ran both of these solutions on a working metamask out of curiousity and they worked fine to recover the vault log.

Good luck to anyone still working on this, and remember to backup your secret phrase.

**Comment by miguelmota** [comment]
Seeing same on Firefox 103.0.2 on Archlinux. Restarting firefox and computer had no effect.

**Comment by miguelmota** [comment]
Has anyone found a solution to this problem that doesn't involve re-importing from scratch?

**Comment by gorbak25** [comment]
My metamask on firefox was also affected. The chrome version works fine.

**Comment by project-skyn** [comment]
> Same story, ![image](https://user-images.githubusercontent.com/441555/183858876-48479ec9-7427-45fc-8dc4-5f3d2648c4c8.png)

me too, i thinks problem is change Server RPC? i changed RPC server and got this error.

**Comment by PhiMarHal** [comment]
This showed up for me today. Firefox, Windows 10, originally on MM 10.18.1 then updated to 10.22.2 - without success.

**Comment by KeenanZain** [comment]
I have the same problem

**Comment by ercanhim89** [comment]
I have a solution. Telegram @ercnh

**Comment by JacquesM19** [comment]
I'm having the same issue on Firefox. Computer died and no my web extension is showing this same error message:

_"MetaMask had trouble starting. This error could be intermittent, so try restarting the extension."_

**Comment by abi207** [comment]
@PeterYinusa when I try to do this I have error messages in the console. Is there a way to fix this?

**Comment by bilogate** [comment]
Thanks @ercanhim89 . He has fixed my metamask.

**Comment by winter38** [comment]
Same problem on FF

**Comment by Hugo0** [comment]
Same problem on FF

![image](https://user-images.githubusercontent.com/12943235/210231759-6a823c44-f165-4398-864b-4202ffc69d99.png)

Can we get any help on this @danfinlay ?

**Comment by jacmos3** [comment]
Same error on a mac with firefox 108.0.2 after mac died. It's been one year at least that metamask sucks after the mac powers off in a bad way, and so far the only way I had to take to solve it, was by unistalling and reinstalling metamask plugin, but it is a really boring thing to do every time since I have many addressess to be imported from different seeds and I have tons of chains to add......... 
This time I will spend time to learn about other wallets because I cannot continue this way all the time

**Comment by JasoonS** [comment]
I have the exact same issue, I'm not sure if it was a power outage or what. But there seems to be no way to get metamask to start.

Additionally metamask EATS RAM (ie a big memory leak) like crazy unless it is disabled.

**Comment by caesarV3** [comment]
Same issue, MM stopped working on FF (everything is fine in Chrome), huge memory leakage with extension enabled.

**Comment by ThisGuyIsNotAJumpingBear** [comment]
Same issue here. After it shows that it has trouble with starting, it increasingly consumes CPU resources and memory until FF breaks. Restarting or re-installing MM doesn't work.

**Comment by BojanPi** [comment]
Same issue here, Linux Ubuntu 20.04, with memory leakage. 

Did anyone managed to resolve this?

**Comment by SpoonCreator** [comment]
Guys use this solution:
https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1065822358
increase or decrease the value. Helped me. The bug has existed for several years, the developers apparently do not consider this a problem.

**Comment by slmatthiesen** [comment]
Chiming in to say the solution @SpoonCreator shared worked for me! Thank you

**Comment by ozingi** [comment]
I had the same problem today when my PC was powered off, but thankfully I had backed up my keys

**Comment by ozingi** [comment]
@SpoonCreator Thank you!I https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1065822358 subtract 1 and I succeed

**Comment by fm-b** [comment]
Uncaught (in promise) Error: An unexpected error occurred

> Same problem on FF
> 
> ![image](https://user-images.githubusercontent.com/12943235/210231759-6a823c44-f165-4398-864b-4202ffc69d99.png)
> 
> Can we get any help on this @danfinlay ?

Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). [runtime-lavamoat.js:9409:14](moz-extension://9a737cc0-70f8-45fa-b378-274b57e92069/runtime-lavamoat.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). [runtime-lavamoat.js:8644:29](moz-extension://9a737cc0-70f8-45fa-b378-274b57e92069/runtime-lavamoat.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/273505/envelope/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.53.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 403.

Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). 4 [runtime-lavamoat.js:2192:40](moz-extension://9a737cc0-70f8-45fa-b378-274b57e92069/runtime-lavamoat.js)
Uncaught (in promise) Error: An unexpected error occurred
V

for me I had these errors in console
