### ISSUE TITLE
[Bug]: Incorrect Error Message on Hover tx Amount

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15395]
### Describe the bug

**Problem**: when I hover the Amount for a Send Tx I always see an error message saying: `Please enter a valid value. The two nearest values are ...`.
This should not appear, as values are correct and I can proceed with the tx.

https://user-images.githubusercontent.com/54408225/182129601-166119f1-8bb6-45c1-8b26-557acd75de5b.mp4

### Steps to reproduce

1. Unlock MM
2. Click Send
3. Introduce Recipient address
4. Introduce amount [Clarification] amount with decimals, like `0.002`
5. Hover the amount you just introduced
6. Check error message appearing on hover

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I'm not able to reproduce it. Has this maybe been fixed already?

**Comment by seaona** [comment]
@bschorchit I am still able to reproduce it. I've added a clarification on the repro steps to help in the reproduction process
