### ISSUE TITLE
Security:  Confirm Transaction window should show all relevant information

### ISSUE THREAD

**Issue by beether** [MetaMask/metamask-extension#1540]
Right now, it's not possible to tell the specifics of the transaction you are authorizing.  Beyond the ETH, gas, and gas price, you only see a truncated destination address and the data size.  It is trivial to make the transaction do something other than what the Dapp UI leads you to believe.

It would be nice if there were a way to:
a) See full destination address, and/or click a link to it (in the case of smart contract you may want to view the source)
b) See the data (eg: name of function and params being called)

A simple and acceptable solution would be having a "full details" button that would show a JSON blurb with all the TX details, just above the accept/reject buttons.

**Comment by ugmo04** [comment]
seeing transaction data would also be useful for DAO users to quickly compile a transaction data for a function call to be used in a DAO (or other multisig) proposal.

**Comment by beether** [comment]
Guys... this is a pretty critical thing to add, and it's damn easy.  Make the "Data included: X bytes" be clickable and show the data.  I reported this 6 months ago and all it gets is some colorful labels.

You don't think it's important for a user to see the method and params they are calling on a contract?  Don't you think they'd be at least interested in having the OPTION to view this data?

**Comment by qSlnz** [comment]
I agree please add this feature. Show datas should be a basic feature !

**Comment by bdresser** [comment]
This is now a feature on the new UI confirmation screen!
