### ISSUE TITLE
undefined error when trying to read draftTransaction.amount in validateSendState when cancelling from send flow

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#15401]
https://sentry.io/organizations/metamask/issues/3459007904/?project=273505

**Comment by PeterYinusa** [comment]
@danjm I'm able to reproduce this once I get into a weird state

https://user-images.githubusercontent.com/53189696/182389904-13cd867d-5b5a-4b76-b619-86ab6988ffea.mov

**Comment by danjm** [comment]
`draftTransaction` is undefined after the user clicks cancel/exit in the send flow, likely due to a race condition whereby `validateSendState` has been called within an async function after `resetSendState` has been called
