### ISSUE TITLE
[Bug]: Incorrect max amount displayed in send flow

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#15405]
### Describe the bug

Scenario A: Incorrect max amount displayed when switching networks
https://user-images.githubusercontent.com/53189696/182223277-c1831f0b-2ce7-43c2-8061-482b462a15af.mov

Scenario B : Incorrect max amount displayed when switching assets
https://user-images.githubusercontent.com/53189696/182223307-f510d6bb-e690-441d-8689-7f6da1c4e4c1.mov

### Steps to reproduce

Scenario A (see video above):
1. Click the send button on the home page
2. enter a recipient address
3. click the Max amount button
4. Switch networks

Scenario B (see video above):
1. Click the send button on the home page
2. enter a recipient address
3. click the Max amount button
4. Switch assets from Native currency to an ERC20

### Version

10.18.0

### Browser

Firefox

### Operating system

MacOS

**Comment by digiwand** [comment]
^ oops. please ignore this reference.
