### ISSUE TITLE
[Bug]: The Zero address does not pass input validation for Send and Contact but it does if it's added from a Dapp

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15404]
### Describe the bug

**Problem**: when I try to send to the 0 address I see that MM takes it as an invalid address. This also happens when I try to add a Contact with the 0 address. However, I can bypass this validations by injecting the 0 address from a dapp. Therefore I can send to 0 address as well as add it as a contact.

This is a missmatch and should be either addressed as we accept everywhere the 0 address (I would opt for that) or we don't.

https://user-images.githubusercontent.com/54408225/182210543-c0f54c96-2c13-4a29-b930-708ef2d934ec.mp4

 

### Steps to reproduce

1. Try to send a tx to the zero address `0x0000000000000000000000000000000000000000` - you won't be able
2. Try to add a contact with the zero address - you won't be able
3. Edit Test-Dapp repo and include the receipient for a SendEIPtx function, the zero address
4. Click the button for Send - see how it is possible
5. Now add this address directly from the MM popup - it's also possible

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/7154

**Comment by seaona** [comment]
this issue is still present
