### ISSUE TITLE
[Bug]: When I Cancel an Edit Send tx I Land at Home instead of Confirmation Screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15414]
### Describe the bug

**Problem**: when I cancel an Edit Send tx I Land on Home instead of Confirmation Screen.

Might be related to https://github.com/MetaMask/metamask-extension/issues/15254

https://user-images.githubusercontent.com/54408225/182386572-ef2151f4-81a2-43a1-977f-8051f839af37.mp4

### Steps to reproduce

Still need consistent steps to repro

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Closing as this seems to be fixed on 10.22.2 :)
