### ISSUE TITLE
[Bug]: eth_sendTransaction params not validated when coming from a Dapp causes MM crash. Error new BigNumber not a base 16 Number

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15410]
### Describe the bug

**Problem**: a Dapp can cause MM crash when passing incorrect params to `eth_sendTransaction`. MM should handle this cases and avoid that an external Dapp can crash it.
Affected params that should be validated and handled in case of wrong format:

- `maxFeePerGas`
- `maxPriorityFeePerGas`
- `nonce`

https://user-images.githubusercontent.com/54408225/182309909-4c45ac27-6e76-4e94-aa15-f2fddafdbeaa.mp4

### Steps to reproduce

1. Clone [Test Dapp repo](https://github.com/MetaMask/test-dapp)
2. Modify `sendEIP1559Button` function by changing the params value to a random string. I.e. ".abc."
  - `maxFeePerGas`
  - `maxPriorityFeePerGas`
  - `nonce`
3. Run test dapp `npm run start`
4. Go to localhost:9011 
5. Connect MM
6. Click on Send EIP1559 button - see how MM crashes on every param that you modify

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This might be related to https://github.com/MetaMask/metamask-extension/issues/11780 which we have an open (but stale) PR for https://github.com/MetaMask/metamask-extension/pull/12596

**Comment by bschorchit** [comment]
I think we should keep this one open :)

**Comment by vandan** [comment]
May need to confirm that this is still reproducible @tmashuang

**Comment by tmashuang** [comment]
Error stack trace page of the reproduction
```js
var transactionParameters = {
          from: ethereum.selectedAddress,
          to: ethereum.selectedAddress,
          value: '0x0',
          gasLimit: '0x5028',
          maxFeePerGas: '.abc',
          maxPriorityFeePerGas: '.abc',
        }

await ethereum.request({  
  method: 'eth_sendTransaction',  
  params: [transactionParameters],  
});

```
![image](https://github.com/MetaMask/metamask-extension/assets/13376180/9f8aaa9c-719e-47c0-8b75-b17c13d07776)

**Comment by seaona** [comment]
this is still repro
![Screenshot from 2024-02-29 11-11-22](https://github.com/MetaMask/metamask-extension/assets/54408225/ef676670-091f-409c-86ee-fb6fdd46e962)
