### ISSUE TITLE
Update threebox testcases to the new functionality (Backup & Restore Data) and eventually remove threebox.spec.js file

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15412]
Threebox functionality is being removed from MetaMask and it's being replaced by a function of Backup and Restore Data. For this reason, we need to update the testcases related to Threebox on the `threebox.spec.js` file, in order to test the new functionalities and remove the old assertions.

This issue could be split into 3 tasks:

- [x] Add Backup Data testcase - work started in PR for replacing 3box https://github.com/MetaMask/metamask-extension/pull/15243
- [x] Add Restore Data testcase https://github.com/MetaMask/metamask-extension/pull/16298
- [x] Remove `threebox.spec.js` file https://github.com/MetaMask/metamask-extension/pull/14571
- [x] Remove fixture `threebox-enabled` file https://github.com/MetaMask/metamask-extension/pull/14571
- [x] Remove threebox mock server https://github.com/MetaMask/metamask-extension/pull/14571
- [x] Add fixture for new testcases Backup and Restore Data (if needed)

See more info here: 
- https://github.com/MetaMask/metamask-extension/pull/14571
- https://github.com/MetaMask/metamask-extension/pull/15243

**Comment by PeterYinusa** [comment]
Threebox is no removed and we have tests for backup and restore
