### ISSUE TITLE
[Ext Nav] Create component: SheetHeader

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#15431]
> This component ticket relies on us using a bottom sheet pattern for extension. Currently this is descoped so we are using a dropdown component instead. This may still be the case so check before creating

### Description
Create a reusable UI component for `SheetHeader`

### References
[Figma component](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=9839%3A35294&t=KVGndWCDUbCoktKO-4)
[UI component guidelines](https://www.notion.so/UI-Components-5ccd2bf83eb8441892a0b72c0d8929e1)
[Styling guidelines](https://www.notion.so/Extension-Frontend-Engineering-Guide-b82ddb3e14004b5db3799a9b446294a9#49aa2ef7b7aa40178ff918043df71c34)
Testing guidelines: TBC
[Mobile issue #4228](https://github.com/metamask/metamask-mobile/issues/4228)

### Files needed
- `index.js`
- `index.scss`
- `sheet-header.js`
- `sheet-header.stories.js`
- `sheet-header.test.js`
- `README.mdx`

### Technical details
TBC

### Acceptance criteria
- [ ] Uses color, typography, shadows design tokens 
- [ ] Uses semantic html
- [ ] PropTypes have descriptions
- [ ] Has storybook story with controls
- [ ] Has documentation in MDX
- [ ] Has unit tests and 90% coverage
- [ ] Works in Chrome and Firefox
- [ ] Performance tested: no unnecessary re-renders or other performance concerns

## Screenshots
<img width="375" alt="Screen Shot 2022-08-02 at 4 23 36 PM" src="https://user-images.githubusercontent.com/8112138/182492962-cbf03f5e-36a0-4405-9605-7282eb317dea.png"><img width="375" alt="Screen Shot 2022-08-02 at 4 23 46 PM" src="https://user-images.githubusercontent.com/8112138/182492971-cf9ea2ff-d8c9-4b06-a9af-64e7c0591bbc.png">

**Comment by Akatori-Design** [comment]
I updated the Figma link since the old one was just a link to the cover page.
In design, Sheet Header is not a stand-alone component but a supporting child component (aka _base component), so linked to related the section in the Sheet guideline

**Comment by georgewrmarshall** [comment]
Not needed for extension currently
