### ISSUE TITLE
[Bug]: For certain Send values it is not possible to click Next

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15445]
### Describe the bug

**Problem**: observed strange behavior when I input different amounts on the Send screen, so for certain values (not always the sames) it is not possible to click Next button

https://user-images.githubusercontent.com/54408225/182602850-3a0d72a5-71e4-497a-a2c2-680bf7a75ade.mp4

No sure if this is exclusive to 10.18.0. Needs more investigation. Relevant info:
- so far reproduced on 10.18.X
- so far reproduced only with Send to Token Contract addresses
- ~~seems it might involve clicking Max amount in between steps~~

### Steps to reproduce

1. Click Send
2. Paste contract address
3. Try different amounts

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by cavalier-eth** [comment]
For a number of my wallets, I'm unable to send anything at all, not even eth. 
Clicking Refresh icon for exchange rate does nothing.
Have tried both Firefox and Chrome. 
![image](https://user-images.githubusercontent.com/91091124/183344791-79af0da9-6cf9-4248-ad3f-36cc0e16ad87.png)

The same wallets work fine on Ethereum mainnet.
![image](https://user-images.githubusercontent.com/91091124/183345034-56cf1a9c-3fe2-4bc6-b4d4-ed67eb30199c.png)
