### ISSUE TITLE
[Bug]: Regular Tx and Contract Interactions do not show the Enhanced Gas Fees option

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15443]
### Describe the bug

**Problem**: when I send a tx or interact with a contract I do not see the Enhanced Gas Fee option as before. See comparison between now `10.18.1` (first part of the video) and before `10.17.0` (last part of the video)

https://user-images.githubusercontent.com/54408225/182554906-e0226c22-4582-4daa-aba4-c970d6f5da11.mp4

 

### Steps to reproduce

Ensure  Enhanced Gas fees is OFF.

**Send Tx**
1. Unlock MM
2. Select a Test Network i.e. Ropsten
3. Send to another address
4. See confirmation screen

**Contract Interaction**
1. Unlock MM
2. Select a Test Network i.e. Ropsten
3. Go to a Dapp. I.e. [Compound](https://app.compound.finance/) 
4. Click DAI on Supply Markets column
5. Click Withdraw on the popup
6. Click Faucet
7. See MM popup

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
@seaona I am unable to reproduce this on 10.18.0, for both scenarios you mentioned.

Might you have already dismissed the "New Gas Experience" notification on the 10.18.0 installation where you tested this?

**Comment by seaona** [comment]
@danjm seems that is exactly what happened as I could not reproduce it again. Might have accidentally rejected on the 1st tx. I close this issue
