### ISSUE TITLE
[Bug]: Realtime RPC Provider Disconnect

### ISSUE THREAD

**Issue by superGru625** [MetaMask/metamask-extension#15474]
### Describe the bug

I can see the rpc provider disconnect real time when I use Metamask

### Steps to reproduce

1. Install MetaMask
2. Connect MetaMask using Web3 Provider
3. Contract method call
4. Check Bugs on the console log
5. Resolve to connect again

### Version

2.0

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

**Comment by kevinghim** [comment]
Hi @superGru625 thanks for the report. Which version of MetaMask are you using? We haven't had version 2.0 in a long time.
