### ISSUE TITLE
[Bug]:     Message: f.getNativeCurrency(...) is undefined      Code: TypeError 

### ISSUE THREAD

**Issue by sarahkirkworldwide** [MetaMask/metamask-extension#15471]
### Describe the bug

When I try to login on my Metmask extention on Fire. After I enter the password, this error message comes up:
    Message: f.getNativeCurrency(...) is undefined

    Code: TypeError
I saw someone else posted 3 days ago they had the same issue but the thread was closed, so I am hoping there is a simple solution. (I am not very tech savy). Thank any help!

### Steps to reproduce

1.
MetaMask Extention on Firefox.
Login page, enter email and password. 
Error message appears.
    Message: f.getNativeCurrency(...) is undefined

    Code: TypeError

### Error messages or log output

```shell
Message: f.getNativeCurrency(...) is undefined

    Code: TypeError
```

### Version

Latest, I checked for updates there was none.

### Browser

Firefox

### Operating system

Windows

### Additional context

A few weeks ago I try to add funds, it MetaMask brought up a page for Zilpay, I started the process, but when I got to the address stage, it only allowed me to enter a USA address. I do not have a USA address (I am English but my mobile number used is in Mexico as I live in Mexico). I had to stop the process halfway through as I couldnt go any further. I have tried disabling Zilpay from my extentions to see if it helped, but it did not. I am mentioning as maybe the error message is related?
Thank you for your help. I am not very technical, I use Metamask for crypto tokens. Any simplified advice of what to do I would be grateful for. Thank you for your help.

**Comment by danjm** [comment]
We will be shipping a fix soon, but in the meantime the only fix is to uninstall and re-install your metamask. If you do that, make sure your seed phrase is backed up

**Comment by sarahkirkworldwide** [comment]
That is great to hear. I am happy to wait for the fix soon. (I am to worried to attempt to uninstall and re-install your metamask, incase I lose all my tokens and/or can not get back in again!). Thank you for your time.

**Comment by sarahkirkworldwide** [comment]
Good afternoon, I have not been able to find my seedphrase. So I am hoping this bug is able to be fixed. Will I have do anything my end when you ship a fix, or will it just start working again when I try logging into Metamask? Do you have any ETA of how long it normally takes to resolve an issue like this? Thank you for your advice.

**Comment by sarahkirkworldwide** [comment]
I am still having the same issue. I have not been able to find my seed phrase so I am unable to re-install my metamask. I am still unable to login, the same error message shows. Is the issue still be worked on? Thank you for your time.

**Comment by bschorchit** [comment]
Are you still having this issue, @sarahkirkworldwide? And if yes are you on the latest update (v.10.18.3)?

**Comment by sarahkirkworldwide** [comment]
No the issue has been resolved. I'm so happy. I have my seed phrase now
too! Thanks for asking though. Kind regards, Sarah

**Comment by RealMehndi** [comment]
I'm having this issue and have no idea how to get my seed phrase.
