### ISSUE TITLE
Allow modification of default gas price

### ISSUE THREAD

**Issue by timgalebach** [MetaMask/metamask-extension#1548]
Related to #1413 but a bit different: it would be nice in the settings to have an option to set a default gwei price, rather than having to change from 20 every time.

**Comment by flyswatter** [comment]
What if gas price just rememberd the last value it was set to, as a default?

**Comment by timgalebach** [comment]
Yeah, that would be perfect.

**Comment by maryokhin** [comment]
@danfinlay is there a reason why Metamask doesn't try to guess the relevant gas price using the gas price used for the last block? Would still be more relevant than a default static value.

**Comment by danfinlay** [comment]
@maryokhin We don't use a default static value. We ask the backend client (geth, in our case) for *its* suggestion. Clearly that's proven inadequate, and we need a richer UI for selecting gas price, and we will make one.

**Comment by maryokhin** [comment]
@danfinlay right, ok. It was stuck at 40 for so long that I thought it was static 😄  Glad that something more dynamic is possible, think this make it vastly easier for regular, non blockchain savvy users out there (which we now have thanks to the kitty craze). Thanks for the reply 👍

**Comment by tmashuang** [comment]
Closing this seems to have been solved with https://github.com/MetaMask/metamask-extension/pull/2879.
