### ISSUE TITLE
[Bug]: Metamask Connect UI scroll keeps scrolling up on scroll down

### ISSUE THREAD

**Issue by D6** [MetaMask/metamask-extension#15486]
### Describe the bug

When the Metamask account connection UI pops up to choose what account you'd like to use on the site that supports Metamask, scrolling down will work but then scroll you up

### Steps to reproduce

1. Go on a site that supports Metamask connecting
2. Try scrolling down when the "Connect With Metamask" popup comes up
3. The scroll will keep going up, not allowing you to choose accounts under the top 4 accounts unless you maximize the popup resolution

![08-05-22 05-31 PM 414](https://user-images.githubusercontent.com/745222/183104629-acf05ce5-d1ce-4dcd-b688-e78efacb7ca7.gif)

### Version

10.18.0

### Browser

Chrome

### Operating system

Windows

**Comment by kevinghim** [comment]
Same as https://github.com/MetaMask/metamask-extension/issues/15315 closing this to track there
