### ISSUE TITLE
[Bug]: HTTP(S) URLs that looks like an ENS name get resolved through MetaMask

### ISSUE THREAD

**Issue by SamWilsn** [MetaMask/metamask-extension#15495]
### Describe the bug

I would expect all URLs that begin with `http` or `https` to be resolved with one of those protocols, but if I put `example.eth` in my `/etc/hosts` and try to navigate to it, I end up on the ENS dapp.

Only URLs that use the IPFS scheme should be resolved using the IPFS protocol.

This is especially important for ENS names that are both a valid [DNS name](https://facepng.art) and a valid [ENS name](https://app.ens.domains/name/facepng.art/details).

### Steps to reproduce

1. `sudo sh -c 'echo 93.184.216.34 example.eth >> /etc/hosts'`
2. Navigate to `https://example.eth` in a browser.
3. Get redirected to ENS.

### Version

10.18.1

### Browser

Firefox

### Operating system

Linux

### Additional context

https://twitter.com/_SamWilsn_/status/1555596847393247232

**Comment by ndevmetax** [comment]
> ### Describe the bug
> I would expect all URLs that begin with `http` or `https` to be resolved with one of those protocols, but if I put `example.eth` in my `/etc/hosts` and try to navigate to it, I end up on the ENS dapp.
> 
> Only URLs that use the IPFS scheme should be resolved using the IPFS protocol.
> 
> This is especially important for ENS names that are both a valid [DNS name](https://facepng.art) and a valid [ENS name](https://app.ens.domains/name/facepng.art/details).
> 
> ### Steps to reproduce
> 1. `sudo sh -c 'echo 93.184.216.34 example.eth >> /etc/hosts'`
> 2. Navigate to `https://example.eth` in a browser.
> 3. Get redirected to ENS.
> 
> ### Error messages or log output
> _No response_
> 
> ### Version
> 10.18.1
> 
> ### Build type
> _No response_
> 
> ### Browser
> Firefox
> 
> ### Operating system
> Linux
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> https://twitter.com/_SamWilsn_/status/1555596847393247232


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/
