### ISSUE TITLE
[Bug]: safeTransferFrom is displaying Token Name instead of Symbol

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15521]
### Describe the bug

**Problem**: when I am performing a safeTransferFrom operation I see that on the Send transaction view we are displaying the Token Name instead of the Token Symbol as we usually do.

https://user-images.githubusercontent.com/54408225/183862631-d3c0486c-d578-40ad-b752-9c6d69abd01a.mp4

### Steps to reproduce

1. Deploy an ERC721 token contract on [Remix](https://remix.ethereum.org/#code=Ly8gU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IE1JVApwcmFnbWEgc29saWRpdHkgXjAuOC40OwoKaW1wb3J0ICJAb3BlbnplcHBlbGluL2NvbnRyYWN0c0A0LjYuMC90b2tlbi9FUkM3MjEvRVJDNzIxLnNvbCI7CmltcG9ydCAiQG9wZW56ZXBwZWxpbi9jb250cmFjdHNANC42LjAvYWNjZXNzL093bmFibGUuc29sIjsKCmNvbnRyYWN0IE15VG9rZW4gaXMgRVJDNzIxLCBPd25hYmxlIHsKICAgIGNvbnN0cnVjdG9yKCkgRVJDNzIxKCJNeVRva2VuIiwgIk1USyIpIHt9CgogICAgZnVuY3Rpb24gc2FmZU1pbnQoYWRkcmVzcyB0bywgdWludDI1NiB0b2tlbklkKSBwdWJsaWMgb25seU93bmVyIHsKICAgICAgICBfc2FmZU1pbnQodG8sIHRva2VuSWQpOwogICAgfQp9Cg&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.7+commit.e28d00a7.js)
2. Safe Mint a token
3. Approve this token to another address
4. Change to this other address
5. safeTransferFrom the initial address -- see MM popup

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I believe this is intentional for ERC 721s as displaying the NFT name makes it easier for users to identify the asset than displaying the NFT symbol. I don't think it's a bug. Let me know if you disagree :)

**Comment by bschorchit** [comment]
Closing this for now. Feel free to open in case anyone disagrees on how we are curently doing this.
