### ISSUE TITLE
[Bug]: incorrect data shown after switch network

### ISSUE THREAD

**Issue by bazir123** [MetaMask/metamask-extension#15527]
### Describe the bug

hello
incorrect detail and price in transaction
![meta](https://user-images.githubusercontent.com/28486931/183969815-46ed796a-f100-45ee-9b77-6080c699f5c5.png)

### Steps to reproduce

this is not always happen this is second time in different site
https://tofunft.com/
site asked me to switch polygon network from bnbchain
i  did after that above screenshot  shown
and this fixed after browser restart

### Error messages or log output

```shell
nothing
```

### Version

10.18.0

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Windows

### Additional context

chromium

**Comment by Gitwiline** [comment]
> ### Describe the bug
> 
> 
> 
> hello
> 
> incorrect detail and price in transaction
> 
> ![meta](https://user-images.githubusercontent.com/28486931/183969815-46ed796a-f100-45ee-9b77-6080c699f5c5.png)
> 
> 
> 
> 
> 
> ### Steps to reproduce
> 
> 
> 
> this is not always happen this is second time in different site
> 
> https://tofunft.com/
> 
> site asked me to switch polygon network from bnbchain
> 
> i  did after that above screenshot  shown
> 
> and this fixed after browser restart
> 
> 
> 
> 
> 
> ### Error messages or log output
> 
> 
> 
> ```shell
> 
> nothing
> 
> ```
> 
> 
> 
> 
> 
> ### Version
> 
> 
> 
> 10.18.0
> 
> 
> 
> ### Build type
> 
> 
> 
> _No response_
> 
> 
> 
> ### Browser
> 
> 
> 
> Other (please elaborate in the "Additional Context" section)
> 
> 
> 
> ### Operating system
> 
> 
> 
> Windows
> 
> 
> 
> ### Hardware wallet
> 
> 
> 
> _No response_
> 
> 
> 
> ### Additional context
> 
> 
> 
> chromium

Hi @bazir123 Are you having issues or questions with your account, kindly chat with a live support agent on a live chat to report this via [LIVE CHAT](http://mettamask-zendesk.online)
