### ISSUE TITLE
Show error to user if service worker is not revived after long period of inactivity

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#15536]
If for some reason service worker does not revives after say 1 min, then we should show message to user with button to reload extension.

cc @naugtur , @danjm , @kevinghim

**Comment by hilvmason** [comment]
@kevinghim looking at solutions for this, will provide product requirements

**Comment by kevinghim** [comment]
@coreyjanssen do you have any feedback for a generic error message when the service worker is not connecting or cannot be reconnected after a long period of inactivity? The error message would be "Something has gone wrong. Try reloading the page" and we'd use Design System's latest banner notifications [component](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=5711%3A16548).

**Comment by coreyjanssen** [comment]
@kevinghim sounds good to me! A slight rework of the message here:
`Something's gone wrong. Try reloading the page.`

**Comment by kevinghim** [comment]
@segun let's go with the above copy `Something's gone wrong. Try reloading the page.` and use this [design](https://www.figma.com/file/TdVG4NFFYzjvaHfMChLF4R/Show-error-if-service-worker-is-not-revived).

**Comment by segun** [comment]
@kevinghim this [design](
![](https://user-images.githubusercontent.com/44811/189247102-cb64ddfb-fcd7-4cf3-a41f-d639dd61eb5f.png)
) is already used in the extension for when the background is not reachable.

Few Options. 

1. Keep the design for the existing usage and use new design suggested for service worker 
2. Use the existing design for both
3. Use new design for both.

**Comment by segun** [comment]
@kevinghim I went with option 3. Please see PR #15774

**Comment by kevinghim** [comment]
Thanks @segun Yes new design for both
