### ISSUE TITLE
[Bug]: Token Detection toggle is OFF by default even though on the What's New says it's ON by default 

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15546]
### Describe the bug

**Problem**: on the What's New notification, it is mentioned that Token Detection feature is ON by default, even though I see the feature is OFF by default. Either we need to correct the message or the default status.

https://user-images.githubusercontent.com/54408225/184072646-af3fd14b-02a2-4476-a443-cefa6f1896c7.mp4

### Steps to reproduce

1. Load MM for the first time
2. Unlock it
3. Click on Visit Settings from What's New Token Detection Message
4. See Token Detection is OFF by default

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
We want to correct the message. I've [added a comment](https://github.com/MetaMask/metamask-extension/issues/15544#issuecomment-1220048677) on the other issue mentioning this fix as well.
