### ISSUE TITLE
[Bug]: Token Detection What's New settings lands you at the bottom of settings page

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15545]
### Describe the bug

**Problem**: on the What's New message for Token Detection, when I click on settings I land at the bottom of Settings page instead of at the page level where Token Detection is.

https://user-images.githubusercontent.com/54408225/184072416-90955def-6ae7-4a43-b3bb-9e196a43f37d.mp4

### Steps to reproduce

1. Load MM for the first time
2. Unlock it
3. Click on Settings from the What's New message for Token Detection
4. See you land at the bottom of the page instead of on Token Detection page level

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Should we also use the same design pattern for both Add popular networks and Token Detection? I see one has a button with a CTA and the other one has a link to view in settings. 
cc: @rachelcope

**Comment by danjm** [comment]
@bschorchit The original designs of the what's new made an intentional decision to only show the blue button for the first item in the list.

**Comment by danjm** [comment]
@seaona I can't reproduce this issues or https://github.com/MetaMask/metamask-extension/issues/15547 on chrome and firefox on linux. But this might only be reproducible on certain screen sizes. I will try again later today with a larger screen size


https://user-images.githubusercontent.com/7499938/189901028-5953b3ed-37eb-42de-9339-8aff9d5a0bab.mp4

**Comment by seaona** [comment]
@danjm I cannot reproduce it neither under the same conditions. Might be that it was fixed already?

**Comment by danjm** [comment]
@seaona can we also close https://github.com/MetaMask/metamask-extension/issues/15547 ?

**Comment by seaona** [comment]
yup! I close it. Thank you @danjm
