### ISSUE TITLE
[Bug]: Token Detection date What's New looks not correct

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15544]
### Describe the bug

**Problem**: the date that appears on What's new for Token Detection message looks a bit outdated (4/18/2022)

![image](https://user-images.githubusercontent.com/54408225/184070715-3e8e8a22-9d83-491a-90b7-61cedb0eccbf.png)

### Steps to reproduce

1. Load MM for the first time
2. Unlock it
3. See What's new popup

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Another issue there is that we actually only detect tokens that are listed in at least 3 token lists.

**Comment by bschorchit** [comment]
The message should also say that Token detection is OFF by default and users can enable it in settings. As you also noted here https://github.com/MetaMask/metamask-extension/issues/15546 :)
