### ISSUE TITLE
[Bug]: No longer get dialog to connect to secondary accounts if you have another account that is connected

### ISSUE THREAD

**Issue by grahac** [MetaMask/metamask-extension#15554]
### Describe the bug

Not sure when this changed, but this is a bug affecting all users who like to access a DApp with multiple accounts (so... frequent!)

Basically, if you are connected to a site with Account 1 in your MM, and then you select Account 2 in your MM, it will only connect you in Account 1 and never bring up a dialog asking you to connect Account 2.  
 
This is a confusing user experience as people will not know how to connect a second wallet to any DApp site, and the DApps have no way to enable the popup.

If there is a JS solution, please put it here but it is happening across all sites now. 

### Steps to reproduce

1) Establish a MM with multiple accounts - all unconnected to the test DApp.
2) connect with one account to a DApp
3) In MM extension switch your account in MM to an account that is NOT connected to the DApp.
4) Log out and back into the DApp.  It connects you with the first account with a subtle red i.  Note: It never asked you to connect the second account.  In the past it I believe used to prompt you with the connect addresses screen to connect the second address.

### Version

10.18.0

### Browser

Chrome

### Operating system

Windows, MacOS

**Comment by bschorchit** [comment]
Do you also see this screen when switching to an account that is not connected to the dapp?

<img width="359" alt="Screen Shot 2022-08-18 at 20 23 41" src="https://user-images.githubusercontent.com/34968356/185511923-3206b9d2-17dd-45ce-95e5-7103a96899b2.png">

**Comment by grahac** [comment]
Nope. That's the problem.  It used to pop that up but no longer does.
