### ISSUE TITLE
[Bug]: Accounts show up multiple times in MetaMask UI

### ISSUE THREAD

**Issue by hiroshi-yamamoto-dublr** [MetaMask/metamask-extension#15578]
### Describe the bug

I am testing a dapp and need to frequently try connecting and disconnecting the dapp from MetaMask. MetaMask has a habit of including the same wallet multiple times in the list of connected accounts. Tapping on the three-dot menu for one of the accounts brings up the menu at least twice (but not necessarily once per copy of the account).

![image](https://user-images.githubusercontent.com/97215152/184556172-180301dd-ceb7-48fc-8cac-60b883730738.png)

### Steps to reproduce

Honestly I have no idea what triggers this. But MetaMask simply needs to de-duplicate this information.

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
we might have recently received another report, so re-opening

**Comment by gauthierpetetin** [comment]
Hi @hiroshi-yamamoto-dublr , do you still have this issue with latest version of Extension?
Otherwise, we'll close this issue.
