### ISSUE TITLE
[Bug]: Dark mode displays Token symbol and decimals in black text

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15590]
### Describe the bug

**Problem**: when I am on Dark Mode and I'm trying to import some custom tokens, I can see that the text `Token symbol` and `Token decimal` turns into black text once I've introduced the contract address.

Text should be white, so we can read it in dark mode.

![image](https://user-images.githubusercontent.com/54408225/184664355-266b639b-b9b2-4748-86ac-55a75ce884e3.png)

### Steps to reproduce

1. Unlock MM
2. Go to Settings and activate Dark mode
3. Go to Import Tokens
4. Click custom tokens
5. Add token address
6. Check text

https://user-images.githubusercontent.com/54408225/184664557-8fbf2569-d54e-4533-91af-222db553b73b.mp4

### Version

10.20.0

### Browser

Chrome

### Operating system

Linux

**Comment by georgewrmarshall** [comment]
Looks like this is no longer an issue?

<img width="467" alt="Screenshot 2023-05-10 at 11 37 43 AM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/e3fd1c73-872c-41eb-aa35-bc39f2d4d424">
