### ISSUE TITLE
Add in-app notification for deprecation of 3box

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#15595]

**Comment by hilvmason** [comment]
@kevinghim to please add further detail for when this is picked up

**Comment by kevinghim** [comment]
- Provide warning to existing users prior to deprecation
    - Needs copy
    - Use the yellow notification alert and dismissible
- Post deprecation
    - Copy: “3Box has been deprecated..” Involve Cory
    - Use the yellow notification alert and dismissible

**Comment by kevinghim** [comment]
let's use the What's New modal to say:
"3Box has been deprecated. Please go to Advanced Settings [link to Settings / Advanced] to backup and restore your MetaMask."

@coreyjanssen Can you please assist with the copy?

**Comment by coreyjanssen** [comment]
@kevinghim just for clarification, in the copy above, what does "restore your MetaMask" mean? Like restoring your wallet in general? Want to be sure I understand the direction while rewriting!

**Comment by danjm** [comment]
I think this might provide a bit more context to the user:

"We will be deprecating our 3Box data feature soon. To backup and restore your manually wallet, use the "Backup Now" button in advanced Settings [link to Settings / Advanced]."

**Comment by coreyjanssen** [comment]
Thanks @danjm! Made a few copy edits to your proposal, seen here. Thoughts @kevinghim? 

Pre-deprecation:
We're deprecating our 3Box data feature soon. To backup and restore your wallet manually, use the "backup now" button in Advanced Settings [link to Settings / Advanced].

Post-deprecation:
We've deprecated our 3Box data feature. To backup and restore your wallet manually, use the "backup now" button in Advanced Settings [link to Settings / Advanced].

**Comment by segun** [comment]
@coreyjanssen Please see #15763
