### ISSUE TITLE
trouble with my transactions

### ISSUE THREAD

**Issue by greg9762** [MetaMask/metamask-extension#1560]
I just set up my metamask acct and made 3 transactions and they said that they went through but when i checked my wallet nothing was in there? please help new to this

**Comment by tmashuang** [comment]
Can you provide your logs? https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by frankiebee** [comment]
@greg9762 Are you on Mainnet?
<img width="444" alt="screen shot 2017-06-07 at 2 42 38 pm" src="https://user-images.githubusercontent.com/11225267/26902892-ca58800c-4b8f-11e7-9af9-b5dabf898716.png">

**Comment by kumavis** [comment]
@greg9762 let us know if you are still having trouble with this
