### ISSUE TITLE
[Bug]: Import Tokens appears in Capital Letters for Spanish lang

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15615]
### Describe the bug

**Problem**: when I switch to Spanish, I see that Import token title appears all in capital letters, whereas in English it's not capitalized.

Spanish v:
![import-tokens-esp](https://user-images.githubusercontent.com/54408225/185087176-d518b57b-1997-4e20-8edd-e27f42e56f2c.png)

English v:
![import-tokens](https://user-images.githubusercontent.com/54408225/185087194-c2a47c77-c951-42cd-b564-10d986cf9841.png)

### Steps to reproduce

1. Unlock MM
2. Go to Settings
3. Change language to Spanish
4. Close Settings
5. Click on Importar tokens

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Why is MetaMask screaming at us in Spanish? hahaha 🤪

@SaraCheikh do you still have access to the spanish translation in crowdin? If yes, could you fix this? Thinking this might be the quickest way to fix it.

**Comment by SaraCheikh** [comment]
@bschorchit I still have access but when I type "agregar tokens" to make a suggestion, I don't see any translation using all capitals. Let me know if I should be looking somewhere else in crowdin to fix this. 

<img width="1713" alt="Screenshot 2022-08-19 at 13 06 04" src="https://user-images.githubusercontent.com/98161559/185605617-3d262f38-9458-4443-bce2-d09c20c28405.png">
