### ISSUE TITLE
 When you buy the name eth an error occurs

### ISSUE THREAD

**Issue by Rishat1980** [MetaMask/metamask-extension#1565]
(ENS-Registrar)  
 Warning! Error encountered during contract execution [Bad instruction]

**Comment by Rishat1980** [comment]
When you buy the name eth an error occurs

**Comment by tmashuang** [comment]
If you're getting an error revealing, one of the following is true:

- You never successfully bid
- You're trying to reveal too early
- The domain name is wrong
- The amount is wrong
- The secret phrase is wrong
- You already revealed

**Comment by Rishat1980** [comment]
YOU HAVE BID BUT THE AUCTION IS NOT OPEN

You open bids on an auction that isn't open. Either an error occurred opening the auction, or the auction ended without any bids. In either case, you must open the auction again to validate your bid.
You are willing to pay at most: 0.01 ether for this name. You are still the top bidder.

**Comment by Rishat1980** [comment]
Following the instructions, I open the auction and send 0.01 ETH

**Comment by tmashuang** [comment]
Can you send me the transaction hash/receipt?

**Comment by Rishat1980** [comment]
https://etherscan.io/tx/0xcca8baab07496238e7a98bf1fc98e0d91a06dd38cc27beeadf2545dd5c06e79d

this ?

**Comment by tmashuang** [comment]
Your bid transaction failed, so your bid was never placed - and you can't reveal a nonexistent bid.

**Comment by Rishat1980** [comment]
How to fix it and not allow it in the future?

**Comment by tmashuang** [comment]
Unfortunately, there's no good way to report errors from blockchain functions at present, so it's not really possible to tell which of those reasons it failed for, except by debugging the bytecode.
There is currently a similar issue on the ens-registrar:
https://github.com/ethereum/ens-registrar-dapp/issues/122
https://github.com/ethereum/ens-registrar-dapp/issues/155

**Comment by flyswatter** [comment]
In the future you just need to watch your bid transactions to make sure they go through. If they fail, you might want to try again, or you might want to report to the ENS Ðapp the issue you've hit.

**Comment by teatee808** [comment]
Same issue here. Do you guys know what do I need to do to recover the amount?
https://etherscan.io/tx/0x721908c78985b4db2855425152cee43636d52e3d2cba1750a1f6808bf00e1411

**Comment by tmashuang** [comment]
@teatee808 You can try sending the transaction again with a higher gas limit. The transaction value of 0.3 should not have been deducted, but the transaction fee has been deducted.

**Comment by teatee808** [comment]
The ICO to which i have sent is over and the amount has been deducted and I have not received nor the coins or eth back. Shouldn't the eth been refunded immediately? What other methods do I have to check this in metamask? The transaction time was quite long before issuing the cancel message. Thanks for the swift reply.

**Comment by tmashuang** [comment]
After looking over your transaction history it seems you sent multiple transactions for a similar amount that went through and your address was given ZRX tokens.  This issue can be taken to the proper channels, as it is not related to this issue. [https://support.metamask.io](https://support.metamask.io)

**Comment by teatee808** [comment]
@tmashuang cheers man! will try to solve it with support. Is your gut feeling telling there is still hope to recover the crazy amount of 0.3eth?
Thanks!
