### ISSUE TITLE
Noob here: Unable to locate Transaction entry

### ISSUE THREAD

**Issue by sharbel12g** [MetaMask/metamask-extension#1568]
Used MetaMask to send Ether to an ETH adres. MetaMask says transaction failed and ETH is not anymore in my wallet and is not received on the recipient adres. Is there any way to get my Ether back?

I also see the following message: Unable to locate Transaction entry

**Comment by tmashuang** [comment]
Is the transaction in the transaction history? If so, click on it and it should redirect you to etherscan where we can see the steps it took.

**Comment by sharbel92** [comment]
<img width="262" alt="account1" src="https://user-images.githubusercontent.com/18469433/26953081-a72df21e-4ca8-11e7-9154-b212711558de.png">

**Comment by frankiebee** [comment]
@sharbel12g im seeing a couple strang things from you image their if at all possible can you join are slack http://slack.metamask.io/ and dm your storage (guide for doing that https://github.com/MetaMask/faq/blob/master/LOGS.md#internal-storage-chrome) i am frankiep in slack

**Comment by sharbel12g** [comment]
I deleted the extension and downloaded it again. When I click on Ropsten Test Network I see I have 1 Ether. But after some research I figured out this is Test Ether?

**Comment by frankiebee** [comment]
ahh yes was just about to mention that

**Comment by sharbel12g** [comment]
Can u tell me more about the purpose of Test Ether?

**Comment by frankiebee** [comment]
as MetaMask is also a developer the test networks are for developers/user who want to experiment with Ethereum with out using real ether that has value. We provide 1 ether in the testnet to accounts to use to play with writing programs and try out applications on the testnet

**Comment by sharbel12g** [comment]
ahh that explains a lot. Thanks for the information!

**Comment by frankiebee** [comment]
No problem 😊

**Comment by flyswatter** [comment]
Addressed with #1586 and #1587.

**Comment by flyswatter** [comment]
The "gave up" error while having succeeded would happen if:

The tx got mined after the submission retry period.

**Comment by Sthom33** [comment]
Ive got the same problem. And I even lost the gas, while the transaction did not go through???? It says the transaction is not located. 

0xcc85ba803042839959ceb395724c73082af9dd71cc051c65201fbda108eeef9c

**Comment by tmashuang** [comment]
@Sthom33 if there is still an issue with your MetaMask please email support@metamask.io with your issue. Closing for now.
