### ISSUE TITLE
Create new "What's new" message about the merge

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15693]
We should create a "What's new" message about the merge. Something like:

"🐼 **The Ethereum Merge is here!** 
This is an exciting moment and we're here to say that nothing is changing on MetaMask and you can continue to use your wallet normally before and after the Merge. No action will be required from your side.

For test network users, just a heads up that we'll be removing the following test networks from our default list: Rinkeby, Ropsten and Kovan and adding Sepolia to that list soon! If you want to continue to use any of those networks, you'll be able to do so by adding them as a custom network. 
For all other users, it's always great to remember that test network tokens have no value.
Stay safe and happy Merge!"

Copy of course should be reviewed and changed by @coreyjanssen and marketing team.

**Comment by coreyjanssen** [comment]
working on this now - will update here with proposed copy soon!

**Comment by coreyjanssen** [comment]
Thoughts on this draft? Note that the 2nd to last paragraph is linking to a hypothetical article or blog post from MM about the Merge (working under the assumption that we'll have something of the sort). @bschorchit 

**The Ethereum Merge is here!** 

This is a big milestone for the Ethereum network, but nothing's changing on MetaMask. There's no action required from you, so keep using your wallet as usual. 

For test network users, a quick heads up. Kovan, Rinkeby, Ropsten, and Sepolia will no longer be on our default list. You can always add them as a custom network. (And don't forget that test network tokens have no value!)

Curious to learn more about the Merge? Check out this article for the basics. 

Stay safe and happy Merge!

**Comment by bschorchit** [comment]
I made a small edit just to fix an info there (Sepolia won't be removed from the default list, it'll be added to it - so I just removed the mention to it there).

**Comment by bschorchit** [comment]
We won't have a knowledge base article on the merge, but we can link to ethereum.org page about the merge: https://ethereum.org/en/upgrades/merge/

**Comment by coreyjanssen** [comment]
Awesome! Thanks @bschorchit!

**Comment by kevinghim** [comment]
@coreyjanssen thanks for the copy edits. I think we should simplify the copy because of space constraints, but also mention something about keeping our users safe from scams. Thoughts on the below:

The Ethereum Merge is here! There's no action required from you, so keep using your wallet as usual.

For test network users, Kovan, Rinkeby and Ropsten will no longer be on our default list, but you can always add them as a custom network. Please be aware of potential scams around the Merge. Never sign a contract if it looks suspicious. Learn more about the [Merge](https://ethereum.org/en/upgrades/merge/).

**Comment by coreyjanssen** [comment]
Updated the content here, based on the Slack convo re: test network users being notified separately/consolidation of copy. @kevinghim @bschorchit 

The Ethereum Merge is here! There's no action required from you, so keep using your wallet as usual. 

Be aware of potential scams around the Merge. Never sign a contract if it looks suspicious.

**Comment by bschorchit** [comment]
May I suggest removing the "never signed a contract if looks suspicious" part as it might be confusing to users - e.g. how can they know if a contract looks suspicious?

**Comment by coreyjanssen** [comment]
Ah, true!

The Ethereum Merge is here! There's no action required from you, so keep using your wallet as usual. Be aware of potential scams around the Merge.

**Comment by bschorchit** [comment]
Final copy:

**The Ethereum Merge is here!** 
There's no action required from you, so keep using your wallet as usual. Be aware of potential scams around the Merge.

**Comment by bschorchit** [comment]
And the order of messages in the What's new should be this one ([slack message](https://consensys.slack.com/archives/GTQAGKY5V/p1662766341945419?thread_ts=1662563846.116069&cid=GTQAGKY5V)):

The merge
Scam and security risk
Add popular networks
Token detection v2
Deprecating 3box
