### ISSUE TITLE
Improve Sentry debugging

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#15691]
We should make it easier to debug Sentry locally. Here is a list of current problems with Sentry debugging:

* We disable Sentry for development builds. We have been working around this by commenting out [this line](https://github.com/MetaMask/metamask-extension/blob/2a1c4a00f1aa66ddbf4b8a215cc2fae8a7dfecd4/app/scripts/lib/setupSentry.js#L75).
* The Sentry `debug` flag is only enabled for development builds. This flag enables logging that is useful for local testing, and it has been useful in production-like builds.
* We don't have reliable ways of producing errors for test purposes. Ideally we'd have a way of triggering an error in the background and the UI.
* It is inconvenient to have to check the network tab to confirm a Sentry error report is sent. It would be easier if this was logged, so that it's recorded even when we don't have dev tools open, or when we don't have the network tab open.

Instead of disabling Sentry in development altogether, maybe we could use `SENTRY_DSN_DEV` as indicating whether Sentry should be enabled or not. That way it can stay disabled by default, but there's an easy way of enabling it if we ever want to test Sentry. That gives us a way of enabling enhanced logging as well.

**Comment by davidmurdoch** [comment]
Maybe we can add an `ENABLE_SENTRY` env flag? In the webpack build I might propose adding a cli option `--sentry` that defaults to `true` when building for production.
