### ISSUE TITLE
[Bug]: wallet_addEthereumChain iconUrls is faild

### ISSUE THREAD

**Issue by darkdx** [MetaMask/metamask-extension#15707]
### Describe the bug

Q: wallet_addEthereumChain iconUrls is faild

![image](https://user-images.githubusercontent.com/88136242/186636884-0a221c95-3b24-427f-8e41-1cba213323d4.png)

![image](https://user-images.githubusercontent.com/88136242/186637580-1d3829fe-0080-4ff3-9c26-64bc4322d108.png)

how to solve this problem ?

### Steps to reproduce

as above

### Version

10.18.3

### Browser

Chrome

### Operating system

MacOS

**Comment by Holybasil** [comment]
same issue, did you find a solution?
