### ISSUE TITLE
Update secondary copy and remove the address component from SetApprovalForAll and NFT Approve screens

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15704]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14561)

## Acceptance Criteria
1. This should be done after this https://github.com/MetaMask/metamask-extension/issues/15697 is completed;
2. The secondary copy is updated to `This allows a third party to access and transfer the following NFTs without further notice until you revoke its access.` (currently is "By granting permission, you are allowing the following account to access your funds");
3. The below address component is not shown on this confirmation screen anymore. 
![Screen Shot 2022-08-24 at 18 29 49](https://user-images.githubusercontent.com/34968356/186540490-5b72d545-6575-4af3-88f2-d841abf32f23.png)

## Steps to Reproduce
1. Open the test dapp https://metamask.github.io/test-dapp/
4. Under the collectibles section, click on "Deploy"
5.  Wait for transaction to be confirmed and click on "Mint"
6. Wait for transaction to be confirmed and click on "Set Approval For All"

**Comment by dragana8** [comment]
@bschorchit Do we have to change the title, because on Figma it says "Allow access to your NFTs"? Also, currently, on Mainnet there is a warning "You do not have enough ETH.." and on design there is "Insufficient funds" warning (if user doesn't have funds). Which one should we show?

**Comment by bschorchit** [comment]
Nice questions!

> @bschorchit Do we have to change the title, because on Figma it says "Allow access to your NFTs"?

We should keep the title that was introduced here https://github.com/MetaMask/metamask-extension/issues/15698 . 

> Also, currently, on Mainnet there is a warning "You do not have enough ETH.." and on design there is "Insufficient funds" warning (if user doesn't have funds). Which one should we show?

We should keep the one that we currently have :)
