### ISSUE TITLE
Create "your NFTs may be at risk" modal

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15700]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14561)

## Acceptance Criteria
1. Total is the amount of NFTs the user currently owns from that collection;
2. The existing account component should be used;
3. The copy displayed reads: `You're granting access to **all your {NFTCollectionName} NFTs**, including any you might own in the future. The party on the other end can transfer these NFTs from your wallet at any time without asking you until you revoke this approval. **Proceed with caution.**` (Use the wording from AC and not from design)
4. Clicking on `Reject` rejects the transaction request (same behavior as clicking on "Reject" on the previous screen or in the current existing screen); (Use 'Reject" instead of Cancel from design)
5. Clicking on `Approve` submits the transaction (same behavior as clicking on Approve in the current existing screen).
<img width="553" alt="Screen Shot 2022-08-24 at 19 37 11" src="https://user-images.githubusercontent.com/34968356/186535718-4b544295-40f6-47b5-9af1-6e19faee0a50.png">

**Comment by bschorchit** [comment]
Update: this should be a center justified modal

**Comment by TUGonzalez** [comment]
Hello! as a dapp developer, how i prevent this message from happening? thank you
