### ISSUE TITLE
[FLASK] Write E2E tests for Snap management

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/metamask-extension#15719]
We should write E2E tests for Snap management features, i.e. enabling and disabling snaps, installing and removing snaps, updating snaps etc.

**Comment by bowensanders** [comment]
work is currently complete, waiting on snaps-monorepo 0.24.1 to be merged to develop.

**Comment by bowensanders** [comment]
#16113 replaced with #16228

**Comment by FrederikBolding** [comment]
Fixed in #16628
