### ISSUE TITLE
Create an awesome repo for collecting Dapps

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1573]
IPFS has [a great repo](https://github.com/ipfs/awesome-ipfs) for tracking cool apps using their stack, apparently [awesome is a thing](https://github.com/sindresorhus/awesome), and so we could just follow that format for making a repository for tracking Dapps in general.

We've really slacked on keeping a curated Dapp list, so this would be a nice thing to do in the meanwhile.

**Comment by johnhenry** [comment]
I started one here if anyone is interested: https://github.com/johnhenry/awesome-metamask/.
