### ISSUE TITLE
[Bug]: cannot send transactions on Optimism

### ISSUE THREAD

**Issue by alextes** [MetaMask/metamask-extension#15734]
### Describe the bug

This is with ETH but it happens with USDC too.
MeteMask does not let me set the gas, but does reject the transaction after I sign it in my ledger, apparently never sending it, perhaps the RPC immediately rejecting it, don't know, but I get an error notification which you can find in the screenshot below, complaining it cannot accept a 0 gas price transaction.

![Screenshot 2022-09-02 at 11 46 19](https://user-images.githubusercontent.com/2011351/188112951-4bb50e41-a671-4f3b-a63b-7a309fa4d452.png)

Some transactions do get through! So it seems the gas price is at times so low, some code somewhere feels it i zero, and cannot be submitted.

I'm a little confused. Still thinking something must be wrong with my system, or mayyyybe it's the gas conditions, still I'd be surprised to be the first to report this. I transact infrequently on Optimism.

### Steps to reproduce

1. Send ETH to a wallet on Optimism.

### Version

10.18.3

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by bschorchit** [comment]
Thank you for your report @alextes, a fix for this will released in v10.18.4.
[Slack thread](https://consensys.slack.com/archives/C01KXHPU3C6/p1661295918176439?thread_ts=1660673462.108519&cid=C01KXHPU3C6)

**Comment by bschorchit** [comment]
Closing as 10.18.4 has been released.
