### ISSUE TITLE
[Bug]: Loading MM screen is Light themed while being on Dark Mode

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15739]
### Describe the bug

**Problem**: when I refresh MetaMask while being in Dark Mode, the Loading screen is Light themed instead of Dark.

![dark-mode-loading-screen](https://user-images.githubusercontent.com/54408225/188476569-327593e1-5c16-484b-9066-cfac5cc7c698.gif)

![popup-light-loading](https://user-images.githubusercontent.com/54408225/188488522-2d31282e-1e8a-41df-9f30-d263f3fa9014.gif)

### Steps to reproduce

1. Unlock MM
2. Go to Settings // Experimental
3. Enable Dark Mode
4. Refresh page

### Version

10.18.4

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Possibly related to https://github.com/MetaMask/metamask-extension/issues/14642
