### ISSUE TITLE
Add NFT component to single NFT approval confirmation screen

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15753]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14482)

## Acceptance Criteria
1. When NFT approval confirmation screen is displayed it now shows the new NFT component with the relevant NFT info https://github.com/MetaMask/metamask-extension/issues/15702;

## Steps to Reproduce
1. Open the test dapp https://metamask.github.io/test-dapp/
3. Under the collectibles section, click on "Deploy"
4. Wait for transaction to be confirmed and click on "Mint"
5. Wait for transaction to be confirmed and click on "Approve" to get our NFT approval confirmation screen

**Comment by ElvirCe** [comment]
Blocked until #15751 gets completed with the new design.

**Comment by bschorchit** [comment]
If we hide the `View` button on the component (until https://github.com/MetaMask/metamask-extension/issues/15751 is available), would this be unblocked?

We would still have the edge cases for when we don't know the name and icon. We could fallback to the address and identicon in those cases.

The NFT feature will be released in 10.27 (https://github.com/MetaMask/metamask-extension/issues/17628) so more users will have the OpenSea API on and it'll be more common to have name and icons for those available as well.

Mainly checking if this would be an interesting option to pursue or if we should hold this off for longer. What do you think, @VSaric ?

**Comment by VSaric** [comment]
> If we hide the `View` button on the component (until #15751 is available), would this be unblocked?
> 
> We would still have the edge cases for when we don't know the name and icon. We could fallback to `This NFT` copy with a link to the block explorer (or to the address) and also fallback to the identicon in those cases.
> 
> The NFT feature will be released in 10.27 (#17628) so more users will have the OpenSea API on and it'll be more common to have name and icons for those available as well.
> 
> Mainly checking if this would be an interesting option to pursue or if we should hold this off for longer. What do you think, @VSaric ?

It sounds good to me @bschorchit, I can do it that way.

**Comment by bschorchit** [comment]
One update on my above comment (posting it here too just for easier tracking/visibility): for the icon we'll use the same fallback as the NFT feature: a circle with the first letter
<img width="437" alt="CircleLetter (1)" src="https://user-images.githubusercontent.com/34968356/224334918-2c6ded0d-0f3a-463c-8f05-bdc25b350f27.png">
