### ISSUE TITLE
Create the NFT component for setApprovalForAll

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15752]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14498)

## Acceptance Criteria
1. Icon displayed is the NFT collection icon
2. Copy under "Name of collection" is the NFT collection name
3. Copy under "Number of NFTs is: `All({Number}) + Future NFTs` - where {Number} is the number of NFTs from that collection that are owned by the user 
5. Clicking on "View" opens up the "View NFTs" modal: https://github.com/MetaMask/metamask-extension/issues/15751

<img width="517" alt="Screen Shot 2022-08-24 at 19 45 15" src="https://user-images.githubusercontent.com/34968356/186537605-c696b0a0-37f4-4654-a310-365cd80fe892.png">

**Comment by ElvirCe** [comment]
@bschorchit we are still blocked on this ticket as we are waiting for the solution for the two questions you asked on the Figma Design. 

Barbar's questions: 

1. Name of collection and icon are not always implemented in NFTs smart contracts, so we might not have those if OpenSea is off. We'll have the NFT symbol (e.g. BAYC) in these cases. How do we want to handle such cases?
2. For EIP 1155, we are not able to know if the user owns these NFTs and how many of those they own if OpenSea API is off. How would we handle such cases?

**Comment by bschorchit** [comment]
> 1. Name of collection and icon are not always implemented in NFTs smart contracts, so we might not have those if OpenSea is off. We'll have the NFT symbol (e.g. BAYC) in these cases. How do we want to handle such cases?

We should fallback to symbol, if not possible, fallback to `This collection` copy as we're doing in the title. For the icon, we should fallback to the identicon. 

> 2.For EIP 1155, we are not able to know if the user owns these NFTs and how many of those they own if OpenSea API is off. How would we handle such cases?

We should fallback to `All + Future NFTs`

**Comment by bschorchit** [comment]
Update on my above comment: for the icon we'll use the same fallback as the NFT feature: a circle with the first letter
<img width="437" alt="CircleLetter (1)" src="https://user-images.githubusercontent.com/34968356/224334918-2c6ded0d-0f3a-463c-8f05-bdc25b350f27.png">

the code is in the following file:  ui/components/app/nfts-items/nfts-items.js
