### ISSUE TITLE
Update the address component

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15780]
## Background
This component is used on the "to" address when you go to activity and click on a previous transaction (screenshot below). It might be used in other places too (The assigned developer should check in the code directly). We need to update the current logic for this component as described below. 
![Untitled](https://user-images.githubusercontent.com/34968356/186765431-3e3c4d73-59c2-4eb2-93d1-9215c0bdf52f.jpg)

## Acceptance Criteria
1. If the address exists in the user account list, then the account name is displayed (this should be the first thing checked, if it does exist in user account list we don't need to check the rest);
2. If the address exists in the user address book (contacts), then their nickname is displayed (this should be already existing logic for this component - this should be second thing checked);
3. If the address exists in the contract metadata list, then the contract's name is displayed (third thing checked);
4. If the address doesn't exist in address book or contract metadata, then the address is displayed;
5. Clicking on this component open the 'add/edit nickname' popup (1st screenshot below) or this tooltip (2nd screenshot below) if it's one of the user's accounts.
![Screen Shot 2022-08-25 at 17 46 43](https://user-images.githubusercontent.com/34968356/186765657-15e1e8a3-6a9d-4129-8e38-cb251f319d11.png)
![Screen Shot 2022-08-25 at 18 06 06](https://user-images.githubusercontent.com/34968356/186768919-b1f9a72b-5d5a-4a81-a430-f15c2a849122.png)

## Steps to Reproduce
1. Send a transaction;
2. Go to activity;
3. Click on the transaction to see the details;
4. Notice the component displayed for the address in that page.

**Comment by newlife08** [comment]
![image](https://user
