### ISSUE TITLE
Allow accepting of 0 priority fee on Arbitrum Network

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#15786]
## Background

Arbitrum will require accepting of [0 priority fee](https://consensys.slack.com/archives/C026U6QPYAC/p1660800748283659) for their Arbitrum Nova and Arbitrum One. In Arbitrum, transactions get through in a FIFO manner, so users don’t need to provide any priority fee. Also, the block base fee is low in typical non-congested L2 situations. [Gas API changes](https://consensys.slack.com/archives/C026U6QPYAC/p1662011192663949) to reflect this have been coded up, frontend changes need to follow suit to reflect the backend changes.

We should implement front-end logic to match the backend -- if network is Arbitrum, then remove the Max priority fee must be greater than 0 GWEI warning, and allow users to enter 0 as priority fee. 

## Acceptance Criteria

1. When the user changes the network to Arbitrum, set default max priority fee to 0
2. Remove the Max priority fee must be greater than 0 GWEI warning
3. Disable editing of max priority fee
4. Allow submitting of transaction of 0 max priority fee

**Comment by ElvirCe** [comment]
@bschorchit in order to do this ticket we will need to have some tokens on the Arbitrum Nova and Arbitrum One. Can you advise please on how to proceed and if there is a way to add some tokens.

**Comment by bschorchit** [comment]
Closing this in favor of https://github.com/MetaMask/metamask-extension/issues/16442 which will accomplish the same but for a wider range of networks
