### ISSUE TITLE
[Bug]: Token Detection `From token lists` displays always a dot

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15792]
### Describe the bug

**Problem**: when I click to Token Detected to see the details, I see that the `From token lists` always displays a dot.

![Screenshot from 2022-09-11 12-53-46](https://user-images.githubusercontent.com/54408225/189523675-16462fcc-96ce-4b41-96c3-11894b65c76e.png)

### Steps to reproduce

1. Unlock MM
2. Load Account (with some tokens)
3. Enable Token Detecion, from Advanced Settings
4. Wait until tokens are detected
5. Click "token detected" text
6. See token details

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
The token lists where those tokens are found should appear there.
