### ISSUE TITLE
点击“连接钱包”没有反应[Bug]: 

### ISSUE THREAD

**Issue by huoshan989** [MetaMask/metamask-extension#15791]
### Describe the bug

打开Chiainlist之后，小狐狸钱包可以顺利弹出填写密码项，填写完毕之后点击Chiainlist的连接钱包，就没有反应了，小狐狸钱包的网络连接显示已经连接上了Chiainlist了，实际chiainlist未接连钱包。

### Steps to reproduce

1.
打开Chiainlist之后，小狐狸钱包可以顺利弹出填写密码项，填写完毕之后点击Chiainlist的连接钱包，就没有反应了，小狐狸钱包的网络连接显示已经连接上了Chiainlist了，实际chiainlist未接连钱包。

### Version

10.18.4

### Browser

Chrome

### Operating system

Windows

**Comment by coarsehorse** [comment]
Dude, really? You know, there are a few people over there there that don't understand Chinese(no joke)

**Comment by bschorchit** [comment]
Seems a problem with Chainlist. Have you tried refreshing the website after connecting MetaMask to it?
