### ISSUE TITLE
[Bug]: Testnet tokens are not available (displayed as a white circle)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15808]
### Describe the bug

**Problem**: Testnet tokens are not available (displayed as a white circle), only when I click Send I can see a Blockies/Jazzicon img

![image](https://user-images.githubusercontent.com/54408225/189933146-7506930d-99ac-4756-9470-93df4fe13877.png)

![image](https://user-images.githubusercontent.com/54408225/189933181-e5f62de6-1b48-4f3d-88fa-5ce7075d1f9b.png)

### Steps to reproduce

1. Unlock MM
2. Change to a Testnet -- see token img is displayed as a white circle
3. Click Send
4. Select Recipient -- see token img is now displayed as Jazzicon or Blockie

### Version

10.18.4

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Ooh that's a good catch. We purposely made it so when we updated the testnets to not use the ETH icon and symbol, but I think we should indeed make it consistent throughout the app. I'll add it to the papercuts and ask designer for some input here.

**Comment by seaona** [comment]
thanks @bschorchit!! I believe when there is not token image we are expected to see a Jazzicon/Blockie icon (like we see in the Send screen above) instead of a white circle (but I might be mistaken).

**Comment by seaona** [comment]
Missmatch between images in different screens is still happening (some places displayed as jazzicon, some places as white circle)
