### ISSUE TITLE
Allowance pending

### ISSUE THREAD

**Issue by antranik01** [MetaMask/metamask-extension#1581]
Anyone know why in oasisdex when I go to make a buy of MKR for the first time, it tells me to set my allowance... so i set it and click change and it just says Pending like this and nothing is changing, my only option is to cancel it or wait... I've tried it a few times to no avail. 

This is the pop up that just says pending and I can only hit cancel. No matter how long I wait, nothing changes.

![image](https://user-images.githubusercontent.com/29369657/27023303-d2b71162-4f06-11e7-8520-f12dd0a5b30c.png)

I asked the slack makerdao chat and they said it's an issue with metamask and that I should try mist or parity. Well, I figured I'd let you guys know before I go to bed and maybe I won't have to make the switch cause the fox is too cute.  Anyway, hope that there's a fix for this... cheers!

**Comment by tmashuang** [comment]
Sometimes switching networks, reloading the extension, and restarting the browser helps fix these kinds of issues.

**Comment by flyswatter** [comment]
It could also help us debug this issue if you send a screenshot of your MetaMask account panel.

**Comment by tmashuang** [comment]
Closing old issues.
