### ISSUE TITLE
[Bug]: MV3 - Closed popup is displayed again after Service Worker re-connects

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15828]
### Describe the bug

**Problem**: when I unlock MM and see an informational popup (network deprecation), if I close the popup and Service Worker dies and re-connects, I can see that the popup is displayed again. I'm expecting that the state is preserved, and the popup does not appear again as it was already closed.

[network-popup.webm](https://user-images.githubusercontent.com/54408225/190124468-ac7c3342-af8d-4ff1-948e-83ad6150337e.webm)

### Steps to reproduce

See repro steps [here](https://github.com/MetaMask/metamask-extension/pull/15774#issuecomment-1245704820)

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
Looks like it's not MV3 related and it's an expected behavior. I close the issue. See more here:
https://github.com/MetaMask/metamask-extension/issues/15829

**Comment by danjm** [comment]
@seaona This is a really good find. And, in fact, it is MV3 related. Although it seems so similar to that other ticket you linked that its easy to conclude it is the same issue.

What is happening here, I believe, is a problem with non-persisted state being reset. If some UI is dependent on data stored in memory but not browser storage, then that UI will be interfered with by service worker restart. Another one that comes to mind is signature requests. If a service worker restarts while a signature request is open, it seems possible that the data might be wiped and the message will go away.

This specific ticket can remain closed, but we will want to investigate other areas where this might happen.

**Comment by seaona** [comment]
thank you! I was actually thinking on re-opening again, as I was not 100% convinced on the other ticket explaining this behaviour. 
I will start investigating more in that area for other functionalities @danjm
