### ISSUE TITLE
[Bug]: Zero-arg function calls shown as "Contract interaction" rather than function name

### ISSUE THREAD

**Issue by hiroshi-yamamoto-dublr** [MetaMask/metamask-extension#15837]
### Describe the bug

I have several functions registered with the Parity registry (verified by reading them back), as [required by MetaMask](https://docs.metamask.io/guide/registering-function-names.html) for resolving function names.

If the function takes one or more arguments (e.g. `sell(uint256,uint256)`, the function name correctly shows in the MetaMask history (e.g. as `Sell`).

However, if the function takes no arguments (e.g. `cancelOrder()`), the function name shows in the MetaMask history as `Contract interaction`. No attempt is made to show the function name (e.g. as `Cancel Order`).

There seems to be an issue in the function signature parser, which takes the function signature string returned by the Parity registry, which does not like `()` as the parameter list.

![image](https://user-images.githubusercontent.com/97215152/190359840-5f8e8332-c60d-4e28-a481-e1125e8dfede.png)

A StackExchange search indicates that others have run into the same problem.

### Steps to reproduce

1. Deploy a contract with a 1-param function and a 0-param function.
2. Register both function signatures using the Parity registry.
3. Call both functions through MetaMask.
4. Observe that the 0-param function is not named in the history.

### Version

10.18.0

### Browser

Chrome

### Operating system

Linux

**Comment by FrederikBolding** [comment]
Hi! Are your function signatures also registered with https://www.4byte.directory/ ? We recently had to disable fetching from the Parity registry because it was being griefed. It seems that those docs are out of date.

**Comment by hiroshi-yamamoto-dublr** [comment]
@FrederikBolding no, sorry, I didn't know about that service -- I was just following the MetaMask docs.

Thanks, I'll register there instead. Is this a permanent switch?

**Comment by hiroshi-yamamoto-dublr** [comment]
@FrederikBolding I have at least one 4byte.directory 4-byte function selector collision for my API, and 4byte.directory does not seem to allow alternatives to be registered for a given function selector, which means the first function name that is registered for a given function selector will forevermore be the only function name that will be shown by MetaMask for all different functions that have the same function selector.

Would it be possible for MetaMask just to pull the API for verified contracts directly from Etherscan?
