### ISSUE TITLE
[Bug]: Token Selected and Token Amount are not matching, when I change the selected account

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15836]
### Describe the bug

**Problem**: when I am in the process of performing a token tx, if I change the Selected Account for another account which does not have imported this token, I can see that the Token selected is ETH, while the amount is indicating ERC20 token (LINK).

Note: I can proceed with the tx (sending the Token, not ETH) and tx fails as expected, as I don't have funds for that token in that account.

[Screencast from 15-09-22 10:24:09.webm](https://user-images.githubusercontent.com/54408225/190354271-76f4ddc8-f32b-45d9-9e46-5f2e96cee620.webm)

### Steps to reproduce

1. Select a MM address which has an ERC20 Token
2. Click Send token
3. Add recipient
4. Change selected account for another one, which has not that Token imported
5. See how Token Selected and Token Amount is different

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by brad-decker** [comment]
Closed by #21264
