### ISSUE TITLE
[Bug]: I cannot change to Sepolia network - Unknown infura provider type sepolia

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15853]
### Describe the bug

**Problem**: I cannot change to Sepolia network - Unknown infura provider type sepolia

![image](https://user-images.githubusercontent.com/54408225/190478054-8ef832b9-7fc1-4e70-82de-fba648174090.png)

### Steps to reproduce

1. Load MM for the first time
2. Allow test networks
3. Change to Sepolia network

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by PeterYinusa** [comment]
I'm having issues with Sepolia test network:
- retrieving gas estimates
- sending transactions
- opening the block explorer 

https://user-images.githubusercontent.com/53189696/190708926-96728054-570e-4e83-b46c-0319c10d07d8.mov
