### ISSUE TITLE
[Bug]: Cannot send token with multiple interfaces

### ISSUE THREAD

**Issue by ninokeldishvili** [MetaMask/metamask-extension#15856]
### Describe the bug

I imported custom erc20 token (Network Polygon Mumbai) 
When I try to send the token, I get error in browser
![Metamask](https://user-images.githubusercontent.com/55360920/190591041-d9946d7e-0489-4710-aeba-6a710ba4a29a.gif)

### Steps to reproduce

1. Select network Polygon Mumbai
2. Import errc20 token of address "0x32b507c610EC9C4aD26984Fa1085636fc86c2470"
3. Click the imported token and try to send it 

**To make deposit and get tokens DEPOSITOR role is needed. Please provide account address so we will grant the role**

Transfers work on metamask mobile app but not on browser extension Version 10.18.4

### Error messages or log output

```shell
Uncaught (in promise) BigNumber Error: new BigNumber() not a number: undefined
  at ee (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:95160)
  at E (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:100640)
  at new J (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:93062)
  at O (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:150971)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:110701
  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:87840
  at async onClick (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:410066)




Uncaught (in promise) Error: Send slice initialized as collectible send with a collectible not currently owned by the select account
  at common-8.js:1:111202
```

### Version

10.18.4

### Browser

Chrome

### Operating system

Windows

**Comment by bschorchit** [comment]
Hey @ninokeldishvili, thanks for your report! I was not able to reproduce it using the WETH token on Polygon Mumbai. Could you share the token address that this happened with so we can try to reproduce it?

**Comment by ninokeldishvili** [comment]
Hello @bschorchit, you can try this address 0x32b507c610EC9C4aD26984Fa1085636fc86c2470
Also you may consider it implements both the ERC20 and ERC1155 interfaces. Thank you

**Comment by thedavidmeister** [comment]
the code for the 20/1155 is here - https://github.com/Gild-Lab/ethgild/blob/main/contracts/vault/ReceiptVault.sol

**Comment by ninokeldishvili** [comment]
Hey @bschorchit were you able to overview this issue? Please let me know if you need further information. Thanks

**Comment by dcatki** [comment]
@mcmire @makoto @bschorchit any progress on this? We are currently blocked from deploying quite an innovative ESG solution because MM isn't letting us transaction with our ERC20s.

**Comment by dcatki** [comment]
We will update the thread to make it easier for you to reproduce the issue

This effects all tokens that have multiple interfaces

Transfers work on metamask mobile but not desktop

**Comment by bschorchit** [comment]
Trying with the above contracts, one is no longer able to import it as a token, but might be able to do it as an NFT. I couldn't try as I don't own any. 

Let us know if this is still an issue.

**Comment by thedavidmeister** [comment]
@bschorchit it's been a year so the contracts were refactored into separate tokens

**Comment by salimtb** [comment]
Hello everyone,
in order to reproduce this bug I deployed a copy of this smart contract with the address "0x54d70266568e10f5e059927f6096f883a8b8fbb6" then I tested the send flow.
but so far i can't reproduce the bug ( see video below ) , can you please share more information ?

https://github.com/MetaMask/metamask-extension/assets/26223211/b4c497ec-e6a7-49df-a8fe-066fb3cee766
