### ISSUE TITLE
Create new modal component

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15855]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14708)
[Figma prototype with animation](https://www.figma.com/proto/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?page-id=3781%3A26973&node-id=3781%3A26974&viewport=138%2C336%2C0.63&scaling=min-zoom&starting-point-node-id=3781%3A26974)

## Acceptance Criteria
1. New modal component is created following the design;
2. Modal slides up when opened and slides out (down) when dismissed (see Figma prototype with animation above);
3. This modal can be used in different parts of the product to display different content as exemplified in the screenshot below.
<img width="603" alt="Screen Shot 2022-09-20 at 17 19 21" src="https://user-images.githubusercontent.com/34968356/191356650-501daf72-dc76-43c5-9472-1eb696865bac.png">

**Comment by amerkadicE** [comment]
We won't use the slide-up modal for now.

Reference: 
https://github.com/MetaMask/metamask-extension/pull/16038#issuecomment-1277135801
