### ISSUE TITLE
Current balance should account for pending transactions

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1586]
So you can't send a second tx that won't work b/c it sends more than you have.

**Comment by tmashuang** [comment]
We implemented this https://github.com/MetaMask/metamask-extension/pull/2094. But reverted the change https://github.com/MetaMask/metamask-extension/pull/2181. Another intensive to keep this issue open is to prevent ghost transactions. https://metamask.helpscoutdocs.com/article/37-ghost-accounts-ether-sending-away-whenever-funding-an-account. Closing for now.
