### ISSUE TITLE
[Bug]: Cannot delete a manually added network if it's using the same chainID than a pre-default one

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15876]
### Describe the bug

**Problem**: if I manually add custom networks that are using the same Chain ID than the pre-default ones, I cannot then delete them.
This can be the case if I want to have 2 different RPCs on the same network (i.e. pointing to my node and pointing to a public RPC). Then I won't be able to delete the one I added anymore.

[cannot-delete-custom-network.webm](https://user-images.githubusercontent.com/54408225/191018353-6553576b-65fc-4b50-975b-b4e44952353f.webm)

### Steps to reproduce

1. Go to Settings // Networks
2. Add manually a network with the same Chain ID than any of the predefault ones. I.e.
  - https://rpc.sepolia.org
  - 11155111
3. Save
4. Click on the Network to see the details -- see how no DELETE button is displayed 

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Rating it as sev3 as users are able to deleted it directly from the network list in popup. But yes, we should definitely allow them to delete from this page as well. Good catch!

**Comment by SvenMeyer** [comment]
An additional problem is, that a network can not be edited and saved if it has the same ChainID like an existing network.
- create network with a ChainID which already exists
- edit network (like add/update Blockexplorer URL)
- network can not be saved ("save" button is disabled)
