### ISSUE TITLE
[Bug]: Settings Search does not find manually added Custom Networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15874]
### Describe the bug

**Problem**: after adding some Custom Networks, if I want to search them on the Settings Search bar I can see that they are not found.

[search-not-update.webm](https://user-images.githubusercontent.com/54408225/191007573-52f8de17-095c-4078-8ad6-1bf1f752b60c.webm)

### Steps to reproduce

1. Enable Custom Network List from Experimental Settings
2. Add a custom network
3. Search for that network name on the Settings search bar 

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
@seaona Did we ever support this functionality? Or was this a stated requirement somewhere?

**Comment by seaona** [comment]
@danjm just checked on previous versions and indeed seems it was never supported to extend the search to "new items" on the state. Should I close the issue or is it something that we should expect within the Search func? Haven't seen any requirement specific for that though

**Comment by bschorchit** [comment]
I don't think we ever stated it anywhere, but I could see why it would be a user expectation as default networks can be found this way. Labelled this as an ux-papercut.

**Comment by ElvirCe** [comment]
@seaona @bschorchit @danjm the very top search field is meant to be used to search for settings and the one below the "Settings" title is for networks search. I tried both and in the one below that is meant for networks forks fine and displays all networks.
Should we still proceed and also make changes to the settings search? If yes, I am thinking then the search bar below "Settings" is maybe redundant and we can remove it totally.
