### ISSUE TITLE
[Bug]: Portfolio notification overlaps with Network deprecation warning

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15872]
### Describe the bug

**Problem**: when I open MM for the first time, if I open the popup view I can see that Portfolio notification is overlapping with the Network deprecation warning.

![Screenshot from 2022-09-17 09-48-44](https://user-images.githubusercontent.com/54408225/190846508-b9dd5643-28ba-46e0-aff3-22e762c80756.png)

### Steps to reproduce

1. Unlock MM for the first time
2. Open MM popup
3. See how warning are overlapping

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
I will add the fix to this into https://github.com/MetaMask/metamask-extension/pull/15869
