### ISSUE TITLE
Create in-app Terms of Use

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#15884]
### Background
As a legal requirement, we will require MetaMask users to agreed to the Terms of Use before using the app. That is, get explicit user acknowledgment of our Terms of Use, by viewing the entire Terms of Use, clicking to agree to the Terms of Use to accept and use the app.

### Designs
[Final designs ](https://www.figma.com/file/j3T1H0Xiuke9NhFJ3yOxBU/Updated-Terms-of-Use?node-id=87%3A5216)

https://user-images.githubusercontent.com/6951929/191633519-8d75bb44-905f-48a4-93b0-6a6131ab714f.mov

### Acceptance Criteria
1. Use the Terms of Use based off of the "What's New" modal. However, it shouldn't close by clicking outside of the modal area
2. Display the full Terms of Use to all existing users
3. For other users, display the Terms of Use before someone creates a wallet or imports a wallet (that is, before someone uses a seedphrase in MM)
4. Display once per wallet
5. If the user is onboarded through the onboarding screens and accepts the terms of use, we should not display the model to have the user accept the ToU again. 

**Other Major Requirement for Release**
- [ ] We must have translations for our 14 supported languages complete before requiring users accept these terms to proceed to their wallet. ([thread](https://consensys.slack.com/archives/C03NT9YEWPN/p1667853154237939))

**Comment by kevinghim** [comment]
Some additional context:

> Where is the copy?

[Terms of Use](https://consensys.net/terms-of-use/)

> Does this need to be translated?

Yes

**Comment by hilvmason** [comment]
@kevinghim -- are you able to give a hard deadline on when this needs to be in production? Or is this still considered highest non-MV3 priority?

**Comment by kevinghim** [comment]
@hilvmason there isn't a deadline per se, but needs to be implemented as soon as possible either when there's developer availability or as soon as MV3 is over.

**Comment by hilvmason** [comment]
we can proceed with this issue as is, update translations prior to releasing

**Comment by adonesky1** [comment]
Pending [slack conversation](https://consensys.slack.com/archives/C03NT9YEWPN/p1667853154237939) that doesn't block this work but will block release of this feature.

**Comment by kevinghim** [comment]
A question came up how to display the ToU during onboarding. We should use the modal to display the entire Terms of Use before we provide the user options to Import, Sync, or Create a new wallet.

If they accept the Terms, the user can proceed to choosing one of the three options. Then, during normal usage, we won't display the accepting the terms again.

**Comment by kevinghim** [comment]
Based on the latest conversation with legal, we'll proceed with the following:

- Translation not needed for now. We'll use English only.
- TOU can be sourced from Consensys [website](https://consensys.net/terms-of-use/) and display that in app as an iframe. This will prevent the multiple TOUs from being out of sync.

**Comment by kevinghim** [comment]
Additionally, we will create these events to determine compliance rates:

- ToU Displayed
- ToU Accepted

cc: @adonesky1

**Comment by kevinghim** [comment]
[Figma](https://www.figma.com/file/j3T1H0Xiuke9NhFJ3yOxBU/Updated-Terms-of-Use?node-id=335%3A4763&t=4DyovfoGrrfQd5PA-0)

**Comment by SaraCheikh** [comment]
@kevinghim @vthomas13 Here [Figma link for extension](https://www.figma.com/file/jjXQxv4lG2m1bHmc7D9w45/Updated-Terms-of-Use?node-id=901%3A3375&t=f0No20lJmQqk5Daj-1):
-TOU during onboarding before creating/importing a wallet.
-TOU in the pop up for existing users.

**Comment by kevinghim** [comment]
A decision was made to hardcode the entire contents of the ToU instead of using an iframe to source the contents from the [website](https://consensys.net/terms-of-use/). This is temporary, because we don't want to manage changes that might occur on the website to the extension popup. We will revisit implementing the ToU via an iframe in the future.

@vthomas13 can you let me know if the metrics have been implemented?

> Additionally, we will create these events to determine compliance rates:
> 
> ToU Displayed
> ToU Accepted

**Comment by vthomas13** [comment]
Currently, no. I didn't realize that was a story requirement, but I'll get it in ASAP
