### ISSUE TITLE
[Bug]: [MV3] Cannot Backup my data. Error: `cannot read properties of undefined 'createElement'`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15891]
### Describe the bug

**Problem**: when I click to Backup data, I am getting the following error, and nothing happens:

`common-7.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElement')
  at common-6.js:8:162927
  at Object.backupUserData (background-0.js:1:11120)`

![image](https://user-images.githubusercontent.com/54408225/191300634-e94784e4-5ba1-4bbc-a7e6-4a47e2245f6c.png)

### Steps to reproduce

1. Unlock MM
2. Go to Advanced Settings
3. Click Backup

### Version

[MV3 build] develop

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
I am guessing this will be fixed by https://github.com/MetaMask/metamask-extension/pull/15851

**Comment by seaona** [comment]
thank you @danjm. I will QA against this PR to confirm

**Comment by jpuri** [comment]
I tested this in latest code from develop today and it seems to be fixed already. cc @seaona

**Comment by segun** [comment]
@seaona guess we can close this now.
