### ISSUE TITLE
Integrate updated Eth Optimism package (with modules)

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#15896]
**External PR(s) for this issue:**
[feat(core): use ethers submodules #3363](https://github.com/ethereum-optimism/optimism/pull/3363)

Slack link: https://consensys.slack.com/archives/C01KXHPU3C6/p1663199469927819?thread_ts=1662579353.556779&cid=C01KXHPU3C6

**Comment by adonesky1** [comment]
Latest from Optimism team: https://github.com/ethereum-optimism/optimism/pull/3514

**Comment by adonesky1** [comment]
Replaced with: https://github.com/MetaMask/metamask-extension/issues/16565
