### ISSUE TITLE
[Bug]: [MV3] Deleting a network and terminating SW right after, makes the deleted network appear again

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15918]
### Describe the bug

**Problem**: after deleting a Network, if I terminate the service worker, I can see that the deleted network is back on the netowrk list.

[delete-network-terminate-sw.webm](https://user-images.githubusercontent.com/54408225/191487094-5283cefc-ecb3-40c3-838e-57384a506c25.webm)

### Steps to reproduce

1. Unlock MM
2. Show test networks
3. Delete localhost network -- see localhost is not there anymore
4. Terminate Service Worker
5. Check Networks on the drop-down menu -- see localhost is there again

### Version

[MV3 build] develop

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
This sounds like the sort of issue that should have been handled by https://github.com/MetaMask/metamask-extension/pull/15337

**Comment by adonesky1** [comment]
Having trouble reproducing this one...

https://user-images.githubusercontent.com/34557516/191799980-b63c016c-92c0-4df1-912e-6b70204849fd.mov
