### ISSUE TITLE
Get a new version of `eth-lattice-keyring` from the gridplus team with updated version of `ethereumjs/util`

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#15927]
Ongoing slack thread with gridplus team [here](https://consensys.slack.com/archives/C02AEN5PFFA/p1663080106781829?thread_ts=1663012055.971299&cid=C02AEN5PFFA)

**Comment by legobeat** [comment]
- Progress has been made: #27973 
- Further updating pending: #28008

**Comment by legobeat** [comment]
Resolved by #28008
