### ISSUE TITLE
[Bug]: [MV3] Some Dapp Interactions stop responding after SW terminates

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15922]
### Describe the bug

**Problem**: when I am using a Dapp and Service Worker is stopped, some Dapp interactions stop responding and depending on which one they vary on their behavior. First of all, all buttons of the Dapp continue to be enabled.

Then, when I use the following functions, nothing happens and MM is not triggered:
- Send Legacy tx
- Send EIP 1559 tx

When I use the following functions, dapp buttons are then disabled, and Connect button is enabled again:
- Deploy Contract
- Create Token
- Deploy Failing Contract
If I click on Connect button, MM is triggered, and I can unlock and connect to the Dapp again.

When I use the following function, nothing happens, but I see this message on the dapp frontend `Encryption key: Error: The requested account and/or method has not been authorized by the user.`
- `Get Encryption Key`
- `Sign`

[dapp-sw-interruptions.webm](https://user-images.githubusercontent.com/54408225/191493806-bb14de0d-8a7f-4e87-b4a9-2961f47b92ff.webm)

### Steps to reproduce

1. Unlock MM
2. Connect to Test Dapp
3. Terminate Service Worker
4. Click on Send Legacy tx -- nothing happens
5. Click on Send EIP 1559 tx -- nothing happens
6. Click on Deploy contract -- buttons are disabled, Connect button is enabled
7. Click Connect
8. Unlock MM
9. Terminate Serivce Worker
10. Click on Get Encryption Key / Sign -- nothing happens, but we see a frontend error

### Version

[MV3 build] develop

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
mmm that's an interesting question, as I was expecting that the service worker should re-start automatically, specially when I click to a Dapp button which triggers MetaMask @danjm maybe this assumption is not right though?

At the moment, for example when I am triggering these functions after terminating sw:  `Send Legacy tx /  Send EIP 1559` nothing happens (neither on MM nor on the Dapp).

**Comment by digiwand** [comment]
SW can stop running after different cases: 
- manually terminating
- dapp is not connected, and the browser deems the service worker as inactive 
- web store version is updated / installed 

The following epic has numerous tickets to fix this reported bug:
https://app.zenhub.com/workspace/o/metamask/metamask-extension/issues/15984

We have not fully implemented the

**Comment by digiwand** [comment]
SW can stop running after different cases: 
- manually terminating
- dapp is not connected, and the browser deems the service worker as inactive 
- web store version is updated / installed 

The following epic has numerous tickets that should fix this reported bug:
https://app.zenhub.com/workspace/o/metamask/metamask-extension/issues/15984

Interesting that some dapp methods are working while others are not. I'll keep an eye out for these methods. Thanks for the report!

**Comment by digiwand** [comment]
This may be fixed by:
#15986
#15052

**Comment by jpuri** [comment]
This should be fixed after we merge the PR https://github.com/MetaMask/metamask-extension/pull/16075

**Comment by seaona** [comment]
I close this issue as it's fixed by the PR mentioned above
