### ISSUE TITLE
[Bug]: [MV3] Get Encryption Key notification is cleared after SW is terminated

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#15920]
### Describe the bug

**Problem**: when I perform a Get Encryption Key from a Dapp, a MM notification window is opened. However, if I terminate SW and login again, this notification is cleared an I land to the home page.

[get-encryption-key-terminated.webm](https://user-images.githubusercontent.com/54408225/191489928-21f67590-2679-4f1b-8cad-e88836048728.webm)

Not 100% sure but I think we would expect I still can see the notification, as it happens when we are in the middle of a tx. See below:

[send-tx-sw-terminate.webm](https://user-images.githubusercontent.com/54408225/191490385-d29d768c-f61f-47c0-ad6c-200787a821b0.webm)

### Steps to reproduce

1. Unlock MM
2. Connect to Test Dapp
3. Click Get Encryptions Keys -- see MM notification and window
4. Terminate Service Worker
5. Login to MM again -- see you land on the Home page

### Version

[MV3 build] develop

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
This was resolved as of https://github.com/MetaMask/metamask-extension/pull/15558

But a new problem was revealed. I will create a ticket for that
