### ISSUE TITLE
Add a "Your funds may be at risk" friction modal to eth_sign signature's requests

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15932]
## Resources
[Figma Design file](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14561)

## Acceptance Criteria
1. Clicking `Sign` on eth_sign request does NOT sign the message, instead it displays this new modal;
2. Modal follows same design as https://github.com/MetaMask/metamask-extension/pull/16195;
3. Title on top of modal is: `Your funds may be at risk` instead of `Your NFTs may be at risk`;
4. `Total: <number>` part of the original modal is not displayed;
6. The copy displayed is: `Signing this message could be dangerous. You may be giving total control of your account and assets to the party on the other end of this message. That means they could drain your account at any time. Proceed with caution. Learn more.`;
7. Learn more link leads to https://consensys.net/blog/metamask/the-seal-of-approval-know-what-youre-consenting-to-with-permissions-and-approvals-in-metamask/  (we should consider a more specific article in the future);
8. Clicking on `Reject` rejects the signature request (same behavior as clicking on "Reject/Cancel" on the previous screen or in the current existing screen) (Use 'Reject" instead of Cancel from design);
9. Clicking on `Sign` signs and submits the message (same behavior as clicking on `Sign` in the current existing screen).
10. Remove the warning message in the Sign request pop up

## Steps to Reproduce
1. Open the test dapp https://metamask.github.io/test-dapp/
2. Under the Eth Sign section, click on "Sign"

**Comment by bschorchit** [comment]
@coreyjanssen could you help us improve the copy in this modal? I've just copied and paste the same message we currently display as a warning in the signature request page. Some notes from Dan on this copy are here: https://github.com/MetaMask/metamask-extension/issues/11337

**Comment by coreyjanssen** [comment]
@bschorchit thoughts on this as an option?

`Signing this message could be dangerous. You may be giving total control of your account and assets to the party on the other end of this message. That means they can drain your account at any time. Proceed with caution. Learn more.`

**Comment by bschorchit** [comment]
Thank you, Corey ❤️
I would only change the `can` to `could` on `That means they can drain your account at any time.` as below:

`Signing this message could be dangerous. You may be giving total control of your account and assets to the party on the other end of this message. That means they could drain your account at any time. Proceed with caution. Learn more.`

**Comment by coreyjanssen** [comment]
@bschorchit that works!!

**Comment by bschorchit** [comment]
This should be released at least 1 release after https://github.com/MetaMask/metamask-extension/issues/15945.

**Comment by bschorchit** [comment]
I've updated the above description to refer to this PR https://github.com/MetaMask/metamask-extension/pull/16195 as the design  pattern to be used here. Saya has already reviewed the design in that PR and gave a ✅

**Comment by amerkadicE** [comment]
Hi @bschorchit @SayaGT,
Can you confirm that the design is correct? 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/97883527/196366152-fc1ca7a5-ccb1-4783-b4aa-fbbe76942ee2.png">
