### ISSUE TITLE
[Bug]: 4, the uin256 value given by the types of signatures can also be signed by the String?

### ISSUE THREAD

**Issue by keepresolve** [MetaMask/metamask-extension#15953]
### Describe the bug

{
        "types": {
            "EIP712Domain": [{
                "name": "name",
                "type": "string"
            }, {
                "name": "version",
                "type": "string"
            }, {
                "name": "chainId",
                "type": "uint256"
            }],
            "Permit": [{
                "name": "owner",
                "type": "address"
            }, {
                "name": "value",
                "type": "uint256"
            }, {
                "name": "timestamp",
                "type": "uint256"
            }]
        },
        "domain": {
            "name": "KCC Beowulf",
            "version": "1",
            "chainId": 321
        },
        "primaryType": "Permit",
        "message": {
            "owner": "0xc82D88971c1cC94c1e0821aDD449a4655C98E2BA",
            "value": "Confirm your vote in your wallet",
            "timestamp": 1663842404253
        }
    }

### Steps to reproduce

1. success

### Error messages or log output

```shell
success
```

### Version

10.18.4

### Build type

Flask

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS, Linux

**Comment by bschorchit** [comment]
Hey @keepresolve, could you clarify your question?
