### ISSUE TITLE
Deprecate Rinkeby, Ropsten and Kovan

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#15957]
This is a follow up from https://github.com/MetaMask/metamask-extension/issues/15295.
The time has come for us to say goodbye to some of our beloved test networks 💔. [Infura will deprecate support to Rinkeby, Ropsten and Kovan on October 5th](https://blog.infura.io/post/deprecation-timeline-for-rinkeby-ropsten-and-kovan-testnets) so we should remove those networks from our default list around the same time. 

## Acceptance Criteria
1. Rinkeby, Ropsten and Kovan are not on MM default network lists anymore;
2. Users are able to add Rinkeby, Ropsten and Kovan to their MM through the custom network form;
3. Users are able to add Rinkeby, Ropsten and Kovan to their MM through the dapp API;
4. This is released in v10.20 or ahead of that in a hot fix release to match the timing with Infura's deprecation.

**Comment by bschorchit** [comment]
> Hey @bschorchit! What should become the new default network in place of Rinkeby?

Goerli and Sepolia will continue to be on the default test network list. Is that what you mean?

**Comment by ryanml** [comment]
@bschorchit see https://consensys.slack.com/archives/G1L7H42BT/p1664206917515079?thread_ts=1664206906.853299&cid=G1L7H42BT
