### ISSUE TITLE
ui - factor out QR code minimal component

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1595]
would be nice if qr code was just a component that generated the image based on a content string

**Comment by sage7will** [comment]
Hi @frankiebee, I'm a first time contributor, can I work on this issue?

**Comment by frankiebee** [comment]
@sage7will sorry for the miss leading label but we are trying to avoid to major ui changes right now. I'd recommend picking a different one.
Side note:
I'm adding a blocked label to this due to PR #1881

**Comment by sage7will** [comment]
Okay, I'll keep my work in a separate branch and will check back in when #1881 is completed. I took a quick look at the CR, and it wouldn't be too much work to fix up the conflicts.

**Comment by frankiebee** [comment]
yeahhhhh sorry another ui addition would over complicate that already complicated merge. But thanks for wanting to help @sage7will

**Comment by sage7will** [comment]
Oh I meant that after the review is completely finished and merged in, I'll pull it and fix up conflicts locally. I would definitely not want to get caught up in that merge haha.

**Comment by frankiebee** [comment]
😅 i meant sorry about not keeping are tags up to date.
