### ISSUE TITLE
[Bug]: Swap Transaction Item Doesn't Display Date

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#15963]
### Describe the bug

When looking at transactions in my ETH history, I don't see the date of a swap:

<img width="357" alt="SwapNoDate" src="https://user-images.githubusercontent.com/46655/192118003-0c5feecf-9e8e-4792-a29e-bb4ab8f5eb55.png">

Further, clicking the transaction item doesn't display the transaction info modal.

### Steps to reproduce

1. Complete a swap
2. Look at the transaction list for ETH

### Version

10.18.4

### Browser

Brave

### Operating system

MacOS

**Comment by suhasabhishek** [comment]
Can I look into this?
