### ISSUE TITLE
[Bug]: Well-known networks should be available out-of-the-box, or one-click to add

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#15964]
### Describe the bug

Well-known networks, such as BSC, Polygon, and the like, should be readily available out of the box, or at the very least, it should be easy to add them in one click (per network) by selecting them from a list from "Add Network" in Setting.

It is absolutely ridiculous that one has to look up, copy and paste the low-level parameters one by one for such well-known, well-established networks used by billions of people.

### Steps to reproduce

1. Go to Settings -> Networks -> Add network
2. try to add Polygon, or BSC, or one of those.

### Version

10.18.4

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
If you update your extension to v10.19 and go to `Settings` > `Experimental` and turn the `Show custom networks` list toggle on, will you see a list of popular networks with pre-filled details whenever you click to `Add a network`.

<img width="357" alt="Screen Shot 2022-09-27 at 23 31 20" src="https://user-images.githubusercontent.com/34968356/192674268-a4601371-7d33-4d9a-9799-1ab76efdd2ca.png">
