### ISSUE TITLE
[Bug]: MV3: "Could not establish connection. Receiving end does not exist." error

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#15970]
### Describe the bug

There have been various causes for this error. There will be multiple tickets that will fix this issue for our MV3 beta launch.

**1 of numerous causes for this error (Fixed by https://github.com/MetaMask/metamask-extension/pull/16075):** 
Currently, when the service worker terminates it produces this error, `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`, numerous times. Even 100+ times from a single service worker restart.

![image](https://user-images.githubusercontent.com/20778143/192312255-12f115b5-1f48-4c39-b74b-97221e445423.png)

![image](https://user-images.githubusercontent.com/20778143/191643977-09dc35b4-9a71-4dd5-82e4-ede2674a5940.png)

### Steps to reproduce

1. Start the extension using MV3
2. View dapp page
3. Inspect app-init.js service worker and terminate service worker
4. Observe error in console

### Error messages or log output

```shell
`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`
```

### Version

10.19.0

### Browser

Chrome

### Operating system

MacOS

**Comment by digiwand** [comment]
This may be fixed by:
#15986
#15052
#15975

**Comment by jpuri** [comment]
This should be fixed after the PR is merged https://github.com/MetaMask/metamask-extension/pull/16075

**Comment by digiwand** [comment]
I believe we have merged in the fixes for this issue
