### ISSUE TITLE
[Bug]: MV3: "Duplicate script ID 'inpage'" error

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#15971]
### Describe the bug

When the "app-init.js" service worker resets. It may add the"Duplicate script ID 'inpage'" since it attempts to inject the inpage script again.

### Steps to reproduce

1. Launch extension MV3
2. Open dapp
3. Inspect `app-init.js` service worker
4. Terminate `app-init.js` service worker
5. Observe error

### Version

10.19.x

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
Same as https://github.com/MetaMask/metamask-extension/issues/15965
