### ISSUE TITLE
[Bug]: Buy option on all test networks throws an error when I try it

### ISSUE THREAD

**Issue by mirjanaKukic** [MetaMask/metamask-extension#16017]
### Describe the bug

**Problem**: when I click on Buy button on all test networks it throws me an error in MM. It works on MainNet network.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/94608179/192783133-206d14e6-d258-4740-aece-779613b216ca.png">

https://user-images.githubusercontent.com/94608179/192783682-425cd64a-d0ea-4766-85b7-840be69425ff.mov

### Steps to reproduce

1. Unlock MetaMask
2. Try Buy option on all test networks

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I'm not able to reproduce this on v10.19. Do you know if there's any additional step that could be done to get this error?

https://user-images.githubusercontent.com/34968356/192909212-e6b122c0-e47e-4139-9fb4-5e9e1f673346.mov

**Comment by mirjanaKukic** [comment]
Hmm, I've checked it again this morning and have the same situation. I pulled latest changes from develop. Tried also both option: create a new wallet and import wallet. 
See below : 

https://user-images.githubusercontent.com/94608179/192991035-feacc7be-5ad0-4bb9-b056-606671fc4abb.mov

**Comment by bschorchit** [comment]
Thanks @mirjanaKukic ! I was using the version in prod so this is probably the difference. Something on the develop branch that have not yet made it to prod might have broken it.

**Comment by mirjanaKukic** [comment]
It was temporary issue on develop branch. It's working now so this one can be closed.

**Comment by bschorchit** [comment]
Oh that's good news, thanks Mirjana!

**Comment by seaona** [comment]
In case more investigation is needed, this issue is reproduceable in [this PR](https://github.com/MetaMask/metamask-extension/pull/15558) but not in the current develop, as @mirjanaKukic is mentioning.

[buy-testnet.webm](https://user-images.githubusercontent.com/54408225/193908960-3b1ab8fd-b774-495f-a8bd-552d47838b7e.webm)

**Comment by PeterYinusa** [comment]
Related: https://github.com/MetaMask/metamask-extension/issues/16080
