### ISSUE TITLE
havent recieved tokens or confirmation from Monaco ico

### ISSUE THREAD

**Issue by cryptobroker44** [MetaMask/metamask-extension#1602]
my address 0xb5a5653aed383baacbf6ec28f42c2dc26dbb07f2

**Comment by tmashuang** [comment]
@cryptobroker44 we have not yet implemented token view yet.
https://github.com/MetaMask/faq/blob/master/USERS.md#managing-tokens

**Comment by tmashuang** [comment]
Closing old issue.
