### ISSUE TITLE
No warning is shown on a Send transaction request when I don't have enough funds

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16028]
We usually show an insufficient funds warning whenever a dapp is requests a transaction and the user does not have enough funds to submit the transaction. This is not the case for when a dapp triggers a send transaction.

### Steps to Reproduce:
1. Open https://metamask.github.io/test-dapp/
2. Have no funds in your account
3. Change to a network that supports EIP 1559 (e.g. Rinkeby, Ethereum, Polygon)
4. Click on Send Legacy Transaction
5. Click on Send EIP 1559 Transaction
6. Change to a network that does not support EIP 1559 (e.g. BSC)
7. Click on Send 
8. Notice how the insufficient funds warning won't show up in any of those cases even though you don't have enough funds and you're not able to proceed with the transaction.

**Comment by mirjanaKukic** [comment]
https://user-images.githubusercontent.com/94608179/195562454-b67bea10-3729-4004-a2d6-ec52df4bdb15.mov
