### ISSUE TITLE
[Bug]: Could not make gas fee zero in the app. but in chrome extension its possible. we need the option for zero gas fee in the metamask app instead of 0.00001 default.

### ISSUE THREAD

**Issue by AstraGuild** [MetaMask/metamask-extension#16035]
### Describe the bug

In chrome you can make the gas price (GWEI) to zero. in the app it always make the zero into 0.00001. since we are developing a zero gas fee blockchain, can you adjust the app to accomodate our zero gas fee blockchain?

### Steps to reproduce
1. use the agvnetwork.org RPC for testing
Network Name :AGV Network Testnet
RPC URL :https://rpc-testnet.agvnetwork.org/rpc/
Chain Id :2833
Currency Symbol :AGV
Block explorer URL :https://testnet.agvnetwork.org/
2. get AGV toklen from the faucet at https://faucet.agvnetwork.org/
3. send native token to any address.
4. adjust Gas Prive (GWEI) to zero (0)
5. In Chrome extension, we can see that its possible to make it zero. which is good for us.
6. In Metamask app everytime you edit the gas price to zero (0) it will always set a default of 0.00001 which defeat the purpose of ou zero blockchain developement. 

### Error messages or log output

```shell
In chrome you can make the gas price (GWEI) to zero. in the app it always make the zero into 0.00001. since we are developing a zero gas fee blockchain, can you adjust the app to accomodate our zero gas fee blockchain?
```

### Version

10.18.4

### Browser

Chrome

### Operating system

Windows

### Additional context

In chrome you can make the gas price (GWEI) to zero. in the app it always make the zero into 0.00001. since we are developing a zero gas fee blockchain, can you adjust the app to accomodate our zero gas fee blockchain?

**Comment by PeterYinusa** [comment]
Issue moved to [MetaMask/metamask-mobile #5071](https://github.com/MetaMask/metamask-mobile/issues/5071) via [**Zenhub**](https://www.zenhub.com/)
