### ISSUE TITLE
Proposal: Autolock on idle

### ISSUE THREAD

**Issue by iczman** [MetaMask/metamask-extension#1604]
As a security measure, can you add a feature to autolock on idle after x minutes (maybe configurable) to secure the wallets? I am paranoid that if someone gets into my computer and I forgot to lock MetaMask the adversary can easily mess with my wallet.

**Comment by pgoli** [comment]
+1

**Comment by flyswatter** [comment]
Closing as a duplicate of #39, raising priority on.
