### ISSUE TITLE
Recover Account

### ISSUE THREAD

**Issue by chiragnahata** [MetaMask/metamask-extension#16056]
### Describe the bug

Hi I am having my secret 12 digit recovery phrase but when I used it on my new pc it showed cannot recover and it automatically created a new account but with no secret phrase same issue with mobile it is creating a new account so both of them are different. Please help its urgent

### Steps to reproduce

1. Recover Account

### Version

Latest

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

Windows

**Comment by chiragnahata** [comment]
Help please

**Comment by chiragnahata** [comment]
When will my promblem be fixed. Cannot use any and also all my nfts are lost becuase of this issue cannot log in back to my nft site. Please help

**Comment by plasmacorral** [comment]
Sorry for the long delay here but we need more information, please. 

It seems that you are suggesting that when you supply the same Secret Recovery Phrase in the browser you are seeing a different public address on computer than when you input that same Secret Recovery Phrase on the mobile client.  Am I understanding that correctly?  

Can you provide more details on the specific steps you are taking to help aid in reproduction?

What browser are you using?
What is the app version on your MetaMask browser extension?
What is the app version on your MetaMask mobile client?
What mobile device model?
What mobile OS version?

When you say:
 > it showed cannot recover and it automatically created a new account

Can you share a screenshot of the error or message you are seeing?

Was this public address originally generated with MetaMask, or another wallet that may use a different HD derivation path? 

Finally- Under no circumstances will any MetaMask team member EVER ask for these 12 words.  Do not share them with anyone, ever, or you risk any remaining assets being drained. If they are offering to help you but asking for these words, you are being scammed. NEVER SHARE YOUR SRP, PERIOD.

**Comment by plasmacorral** [comment]
Closing with out more information, please open a fresh issue if you can help further articulate on the concern.
