### ISSUE TITLE
[Bug]: Cannot Cancel a tx in Sepolia Network

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16051]
### Describe the bug

**Problem**: when I'm in Sepolia test network, if I try to Cancel a Send tx it apparently seems that the Cancel tx has gone through but later on if you see the tx and the details, you can see that tx was never Cancelled.

[cancel-sepolia.webm](https://user-images.githubusercontent.com/54408225/193464960-be573f8c-1d0b-4a18-bb87-5c0a357785c5.webm)

### Steps to reproduce

1. Unlock MM
2. Change to Sepolia Network
3. Click Send
4. Introduce Recipient, Amount and select a Slow tx
5. Confirm
6. Cancel tx and wait -- see that tx value is now 0 and there are no errors. Once tx is confirmed, you see again that tx has the value you introduced before and it has actually never been cancelled

### Version

10.20.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Is this only happening in Sepolia?

**Comment by seaona** [comment]
It's hard to say for sure, as there are many networks. So far I have only seen it on Sepolia, but we need to understand what's the root cause, in order to see if other networks might be impacted
