### ISSUE TITLE
[Bug]: The information box for SIWE with a bad domain has no left margin

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16067]
### Describe the bug

**Problem**: the information box when hovering a bad domain on SIWE has no left margin.

[siwe-no-margin.webm](https://user-images.githubusercontent.com/54408225/193795621-450a9486-ce79-4d61-a798-206be89da49f.webm)

### Steps to reproduce

1. Unlock MM (enable SIWE on envars)
2. Go to test dapp https://spruceid.github.io/test-dapp/
3. Connect MM
4. Click Sign in With Ethereum (Bad Domain)
5. Hover the information ticker

### Version

10.21.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Would this PR https://github.com/MetaMask/metamask-extension/pull/16019 fix this? cc: @holantonela

**Comment by bschorchit** [comment]
Ps: is SIWE included in 10.21? If yes, we might want to cherry pick the above PR and address this https://github.com/MetaMask/metamask-extension/issues/15155 as well. 
I'm asking as the version mentioned in the issue is 10.21 so not sure if it's related to the current rc.

**Comment by holantonela** [comment]
> Would this PR https://github.com/MetaMask/metamask-extension/pull/16019 fix this?

I'm not sure. I'll wait for the PR approval to check the build. Let's keep this one opened for now.

**Comment by holantonela** [comment]
With https://github.com/MetaMask/metamask-extension/issues/16295 this is not a problem anymore.
