### ISSUE TITLE
[Bug]: smart wallet addresses incorrectly detected as tokens

### ISSUE THREAD

**Issue by Ivshti** [MetaMask/metamask-extension#16076]
### Describe the bug

When you send ERC20 funds to Ambire (a smart wallet), you get a message saying **"Warning: you are about to send to a token contract which could result in a loss of funds."**

Judging by the nature of this bug, it is possible that other smart wallets are affected

### Steps to reproduce

1. Try to send ERC20 tokens to an Ambire address like 0xa07D75aacEFd11b425AF7181958F0F85c312f143 or 0x62d00bf1f291be434AC01b3Dc75fA84Af963370A
2. The warning will appear that you're sending to a token address

### Version

10.19.0

### Browser

Chrome

### Operating system

Linux

### Additional context

This is the Ambire Wallet contract: https://github.com/AmbireTech/wallet/blob/main/contracts/Identity.sol and each user is a minimal proxy using Identity.sol as a base.

It appears MetaMask uses heuristics for token detection, but Ambire does not respond to calls like `symbol()` or `decimals()`, so it's still unclear why it's detected as a token

Related to https://github.com/MetaMask/metamask-extension/pull/13588

**Comment by FrederikBolding** [comment]
I've tracked this bug down. Will propose a fix tomorrow.

**Comment by FrederikBolding** [comment]
This will be fixed when the next version of `@metamask/controllers` is published and included in the extension.

**Comment by bschorchit** [comment]
Closing as this has been fixed now :)
