### ISSUE TITLE
[Bug]: RPC Error - invariant violation keyring not created

### ISSUE THREAD

**Issue by arihantbansal** [MetaMask/metamask-extension#16088]
### Describe the bug

![image](https://user-images.githubusercontent.com/17180950/194066664-6e9a08ad-7021-40b3-a431-9244ed8c0332.png)

Whenever I try connecting to any dApp (eg, Uniswap, Perpetual Protocol, Superfluid) using Metamask/Injected Wallet, this error pops up in the console and no notification is shown.

### Steps to reproduce

1. Go to any dApp, for eg, Uniswap
2. Go to app, and click connect wallet
3. Check console logs

### Version

10.19.0

### Browser

Microsoft Edge

### Operating system

MacOS

**Comment by kevinfaveri** [comment]
Same for me, happening on all websites.

**Comment by jim4067** [comment]
This is happening to me too

**Comment by danjm** [comment]
thanks for reporting everyone. Is there any other information in the console?

**Comment by danjm** [comment]
also, does anyone experiencing this have another wallet extension installed? if so, do there error go away if you disable that extension?

**Comment by arihantbansal** [comment]
Yep, I had xNFT Backpack extension installed. On disabling it, the error went away and everything works smoothly now. Would love a fix so that I could use both extensions parallel.

**Comment by jim4067** [comment]
@arihantbansal It also went away for me when I removed backpack.

**Comment by ctrl-danny** [comment]
I also had this problem with metamask connecting to dapps and had backpack as well, error went away when I set backpack site access to "click extension" only
