### ISSUE TITLE
[Bug]: Adding a Custom Token no longer restores the Token symbol to Assets list

### ISSUE THREAD

**Issue by davidfavor** [MetaMask/metamask-extension#16085]
### Describe the bug

No way to show BSC USDT in Metamask anymore.

### Steps to reproduce

1. BSC USDT symbol has disappeared from Assets list.
2. Attempting to re-import USDT shows USDT greyed out.
3. Adding the CoinmarketCap BSC USDT contract as a Custom Token emits "Token has already been added", then disallows adding again, which use to restore the token to the Assets list.

### Version

10.19.0

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Hey @davidfavor, thank you for your report! Is only the symbol or icon that is missing or the whole token info (including your bsc usdt balance) is missing from the assets list?

**Comment by davidfavor** [comment]
Everything's missing + no way to restore the Token.

Work around is to visit a Swap Service which correctly shows USDT... and... trying to explain this to others having this problem... is confusing...

**Comment by davidfavor** [comment]
If useful, I can make a video showing the problem.

Let me know if you'd like me to do this (video), as maybe I'm just missing something simple.

**Comment by bschorchit** [comment]
A video would be very helpful, thank you!
