### ISSUE TITLE
[Bug]: Hardcoded ETH badge in NetworkAccountBalanceHeader component

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#16082]
### Describe the bug

ETH badge shown on networks that are not Ethereum

<img width="472" alt="RC nftapproval 15727" src="https://user-images.githubusercontent.com/53189696/193945668-ede0477f-172e-48eb-996c-aee722795c25.png">

### Steps to reproduce

1. login to the extension
2. Switch networks to a custom network (e.g. Fantom)
3. navigate to the test dapp
4. deploy collectibles
5. mint collectibles
6. set approval for all

### Version

10.21.0

### Browser

Chrome

### Operating system

MacOS

**Comment by SayaGT** [comment]
Ideally the badge would update based on the network. It would show respective icons and if the icons isn't available then it would display the first later of the network.
You can refer to the logic in this [Design System Figma file](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=9409%3A33897).
CC: @georgewrmarshall
