### ISSUE TITLE
Data from TokenListController gets cleared when the service worker restarts

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#16099]
In extension, since we allow users to opt-out of the dynamic toke list use via token detection toggle, we are using `preventPollingOnNetworkRestart` property with true value on `TokenListController` initiation to control polling on network restart/network change; this value is also controller via token detection toggle.

When the value is `true` the tokenList will not be fetched, and the existing data will be cleared.
When the value is false, the tokenList will be fetched for the current network and also will continue fetching on network change as well.

On service worker restart, if we have the token detection turned on, which means `preventPollingOnNetworkRestart` is false, it will get rest to `true` on the restart and will clear out the tokenList data available in state.

**Comment by segun** [comment]
There's a PR to fix this #15913, but as [this comment](https://github.com/MetaMask/metamask-extension/blob/330afadb824c4740d57126807bfbf9ecbe79dde3/app/scripts/metamask-controller.js#L1120) shows, we need a way to reset TokenListController state
