### ISSUE TITLE
[Bug]: High CPU usage on fanbox.cc

### ISSUE THREAD

**Issue by aozaki-kuro** [MetaMask/metamask-extension#16104]
### Describe the bug

The CPU usage bursted to approximately 100-110% when I opened fanbox.cc and left MetaMask extension on.
The CPU dropped to normal right after I disabled MetaMask extension.

### Steps to reproduce

1. Keep Metamask on
2. Open [fanbox.cc](https://fanbox.cc) (No login required)
3. Check the performance and see CPU bursted to 100%+, Edge Developer Tools indicated that there are something constantly compiling scripts.
4. Disable Metamask and CPU drops back to normal.

System: macOS Monterey 12.6 (arm64)
Browser: Microsoft Edge 106.0.1370.34 (arm64)
Extension: Metamask 10.19.0, installed from Chrome Extension Store

### Version

10.19.0

### Browser

Microsoft Edge

### Operating system

MacOS

**Comment by FrederikBolding** [comment]
It looks to me like `fanbox.cc` doesn't expect an extension to use the window `postMessage` and due to faulty error handling they continuously post error messages to `postMessage`. This may be a problem that has to be solved on their end.
