### ISSUE TITLE
Hello, i can be of help to this issue 

### ISSUE THREAD

**Issue by Smithbull001** [MetaMask/metamask-extension#16114]
Hello, 
I forgot to copy my private key when I changed computers.  The computer that had my metamask extension was restored to factory settings.  I do have my seed phrase and I also can see my account balance in etherscan.io.  I also was using a Ledger in connection with my metamask.  Please help.  Thank you

_Originally posted by @la719coaol in https://github.com/MetaMask/metamask-extension/discussions/15961_

**Comment by bschorchit** [comment]
Please reach out to support by clicking on MetaMask Support link within your MetaMask wallet or by going to https://metamask.zendesk.com/ .
