### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Smithbull001** [MetaMask/metamask-extension#16117]
### Describe the bug

I need my wallet as main and not patch and also need full access to it immediately 

### Steps to reproduce

1.my wallet change 
2.my wallet address changed

### Version

5.8.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

**Comment by bschorchit** [comment]
Please reach out to support by clicking on MetaMask Support link within your MetaMask wallet.
