### ISSUE TITLE
Replace direct dependency `ethers` with submodules in extension

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#16112]
Open PR here: https://github.com/MetaMask/metamask-extension/pull/15461

**Comment by danjm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Extension-Client-Team-63529dce65cbb100265a3842/issues/MetaMask/metamask-extension/16112?planning-poker) with Zenhub @brad-decker @DDDDDanica @pedronfigueiredo @PeterYinusa

**Comment by pedronfigueiredo** [comment]
Estimation blocked until #18804 gets resolved

**Comment by gauthierpetetin** [comment]
Closing this issue as it seems it's been fixed by this [PR](https://github.com/MetaMask/metamask-extension/pull/15461) + "ethers" npm package isn't imported in package.json anymore.
