### ISSUE TITLE
[Flask] The `snap_getBip32Entropy` permission is incomprehensible

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#16130]
With our current permission copy, almost none of our users will be able to understand the authority encompassed by the `snap_getBip32Entropy` permission. We should, minimally:

- [ ] Map BIP-32 nodes to their names, as we do with `wallet_getBip44Entropy`
- [x] Reconsider from first principles how to communicate the authority of these permissions

### Exhibit A, permission list:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/25517051/194780879-8b463d4e-e957-4fb7-ae06-3cde76543db4.png">

### Exhibit B, "Are you sure?" confirmation:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/25517051/194780903-6295c4d6-4c1c-4e7d-90cd-0850295f0618.png">

**Comment by kenhkan** [comment]
Closing because it has been addressed
