### ISSUE TITLE
[Bug]: MM is frozen and on re-load I see Service Worker log registered on non-MV3 build and `No keyring found for requested account` error appears

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16162]
### Describe the bug

**Problem**:  on an MV2 build, after interacting with a Dapp, MM icon stop responding and no pop up is open anymore. Extension is frozen and if I reload I see on the background console:
- service worker registered
- Error: no keyring found for the requested account

[sw-no-keyring.webm](https://user-images.githubusercontent.com/54408225/195102627-9cc25d73-2ed0-4aaf-85d2-3ee4f4c55c88.webm)

### Steps to reproduce

1. Load MM
2. Import an Account
3. Go to Test Dapp
4. Connect to Test Dapp
5. Click Create Token
6. Wait until tx is confirmed
7. Click on MM icon again for opening popup
8. Click on the tx details
9. Click on View tx on Etherscan
10. Change window back to Test Dapp
11. Click on MM icon again for opening popup -- MM does not open
12. Reload the extension -- Errors above are triggered

### Version

13.21.0

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
@seaona can you reproduce this consistently?

**Comment by seaona** [comment]
yes, but the issue was solved by removing `node_modules` and re-installing it again. I close the issue @danjm
