### ISSUE TITLE
[Bug]: Error in RPC Response: createLoggerMiddleware

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16163]
### Describe the bug

**Problem**: I am seeing the following error on the background console:
`Error in RPC Response: createLoggerMiddleware`

[rpc-middleware.webm](https://user-images.githubusercontent.com/54408225/195103900-7f73842f-83af-468c-a869-159f19c90a83.webm)

### Steps to reproduce

[needs further investigation on repro steps]

### Version

10.21.0

### Browser

Chrome

### Operating system

Linux

**Comment by rekmarks** [comment]
I think this is the logger middleware working as intended: https://github.com/MetaMask/metamask-extension/blob/68642ee47af11b726c3f0849837c26ddb3d74885/app/scripts/lib/createLoggerMiddleware.js

**Comment by Dinuz** [comment]
@rekmarks what are you implying? That the log.error will appear no matter what? How we can disable that behavior?

**Comment by seaona** [comment]
I cannot repro the freezing behaviour, so I remove the RC milestone and leave it as an open issue until more info is discovered.
Middleware log error seems unrelated and expected.

@Dinuz the log error will appear every time there is an error response coming from the JSON-RPC response. It indicates a problem with your RPC provider. Could you describe the network details where you are connected?
