### ISSUE TITLE
[Bug]: Metamask does not appear in the Connect Account popup

### ISSUE THREAD

**Issue by IBaixauli** [MetaMask/metamask-extension#16165]
### Describe the bug

MetaMask version 10.19.0
Chrome: 105.0.5195.127 (Build oficial) (64 bits)

When we enter in a Dapp and press the Connect Account button, Metamask does not appear among the wallets or options within the popup

Dapps proved: Aragon, Sushiswap, Uniswap, dappradar, Aave, etc.
![Captura de pantalla 2022-10-11 221357](https://user-images.githubusercontent.com/22479620/195190011-39b330a7-4b2a-4f78-b9cc-ec9705ad4ace.png)
![Captura de pantalla 2022-10-11 221539](https://user-images.githubusercontent.com/22479620/195190014-b0b54037-85d9-4830-9bdd-b5d14f9ff6d9.png)
![Captura de pantalla 2022-10-11 221654](https://user-images.githubusercontent.com/22479620/195190015-05047c07-a25a-4ae9-bbc9-a1108e287030.png)

### Steps to reproduce

1. Connect Wallet

### Version

10.19.0

### Browser

Chrome, Brave

### Operating system

Windows

**Comment by nenadV91** [comment]
I have the same issue on Chrome and Ubuntu OS
I have Metamask extension installed but I don't see it as an option in Uniswap suddenly 
![Screenshot from 2022-10-18 14-38-23](https://user-images.githubusercontent.com/34926005/196431551-6c9abe38-8cd3-4aff-94b5-cb90bee67c5e.png)

**Comment by IBaixauli** [comment]
> I have the same issue on Chrome and Ubuntu OS I have Metamask extension installed but I don't see it as an option in Uniswap suddenly ![Screenshot from 2022-10-18 14-38-23](https://user-images.githubusercontent.com/34926005/196431551-6c9abe38-8cd3-4aff-94b5-cb90bee67c5e.png)

I just discovered that the Google user you work with in Chrome may be related, but I haven't been able to definitively resolve the issue yet / Acabo de descubrir que el usuario de Google con el que trabajes en Chrome, puede tener alguna relación, pero todavía no he podido resolver el problema de forma definitiva

**Comment by IBaixauli** [comment]
I just uninstalled the Frame wallet and Metamask works correctly for me / Acabo de desinstalar el wallet Frame y Metamask ya me funciona correctamente

**Comment by nenadV91** [comment]
@IBaixauli Yes, uninstalling Frame wallet fixed the issue for me too.

**Comment by xinnanyemm** [comment]
Please note that `label:team-dapp-api` was removed. Thanks.

**Comment by vandan** [comment]
See https://eips.ethereum.org/EIPS/eip-6963 which MetaMask is now supporting.
