### ISSUE TITLE
[Bug]: RPC method wallet_getSnaps return emty o

### ISSUE THREAD

**Issue by BeroBurny** [MetaMask/metamask-extension#16176]
### Describe the bug

rpc method [wallet_getSnaps](https://docs.metamask.io/guide/snaps-rpc-api.html#wallet-getsnaps) returns empty object

![image](https://user-images.githubusercontent.com/6376047/195440793-e15ad677-5c07-430b-af10-ed0db61e14f5.png)

### Steps to reproduce

1. have any snap installed
2. run the RPC method `wallet_getSnaps`

you can run RPC command from a console

```ts
window.ethereum.request({
  method: "wallet_getSnaps",
}).then(console.warn);
```

### Version

10.20.0-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

Linux

**Comment by FrederikBolding** [comment]
@BeroBurny This should be fixed in `develop` and will also be fixed in the next Flask release! As of https://github.com/MetaMask/metamask-extension/commit/4eb8e508003e90d7c8009a74957cb4a378662ef4

**Comment by FrederikBolding** [comment]
@BeroBurny Can you confirm that this is fixed on your end?

**Comment by BeroBurny** [comment]
LGTM
