### ISSUE TITLE
[Bug]: Loading forever and froze interface when RPC is down

### ISSUE THREAD

**Issue by foufrix** [MetaMask/metamask-extension#16171]
### Describe the bug

![image](https://user-images.githubusercontent.com/16646581/195407219-679a4468-421d-47d6-8291-2a9823c6e0de.png)

When connecting to custom RPC (using gitpod) when RPC is not available, Metamask loads forever on this screen, and clicking on the cross is not working. 

### Steps to reproduce

1. Add a custom RPC working (locally or remotely with a service like gitpod)
2. Connect on this RPC, then close metamask
3. Shut down this RPC
4. reopen metamask
5. Metamask will load forever and stuck. Cross-to-exit is not working

### Version

10.20.0

### Browser

Brave

### Operating system

Windows, MacOS

**Comment by mirjanaKukic** [comment]
I'm not able to reproduce this bug, seems like now X button is working. Could you please try again? Thanks.

https://user-images.githubusercontent.com/94608179/209794945-5fee705a-ccf9-45dc-ae55-e446ec9c410b.mov

**Comment by ElvirCe** [comment]
@foufrix @bschorchit seems like this bug does not exist any longer. Could you please double check and advise.

**Comment by foufrix** [comment]
Hi, @ElvirCe & @mirjanaKukic just tried it out, and effectively I can confirm that it's gone. I'll close this issue 🥳
