### ISSUE TITLE
[Bug]: [MV3] e2e failure for Errors spec

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16211]
### Describe the bug

**Problem**: the e2e test case errors.spec.js is failing with the following error

![image](https://user-images.githubusercontent.com/54408225/195883559-6f00027d-0d28-4f4e-b368-f4031aef5f02.png)

### Steps to reproduce

1. Build mv3 test yarn build:test:mv3
2. Run errors test yarn test:e2e:single test/e2e/tests/errors.spec.js --browser=chrome

### Version

develop-oct14

### Browser

Chrome

### Operating system

Linux

**Comment by PeterYinusa** [comment]
The following error is thrown before the BigNumber error the test expects `'new BigNumber() not a base 16 number: 0x-de0b6b3a7640000'`
```
background-2.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElement')
  at d._setupIframe (background-2.js:1:195813)
  at new d (background-2.js:1:189626)
  at s.addNewKeyring (common-3.js:27:43158)
  at je.getKeyringForDevice (background-1.js:1:53109)
  at async je.setLedgerTransportPreference (background-1.js:1:71757)
```
