### ISSUE TITLE
XCAD logo issue

### ISSUE THREAD

**Issue by StefSerbia** [MetaMask/metamask-extension#16218]
### Describe the bug

XCAD logo should have white background,but it has black one.We  sent .svg without black background 2 months ago.I posted screenshots in "Steps to reproduce" so i think you will understand issue :) 

### Steps to reproduce

1.
![Screenshot_2](https://user-images.githubusercontent.com/74459359/196157332-005d3dc1-846e-484a-bbd6-7ad67e236982.png)
![Screenshot_3](https://user-images.githubusercontent.com/74459359/196157345-50221b55-d0df-418d-948a-a59e300fca4e.png)

### Version

10.20.0

### Browser

Chrome, Brave

### Operating system

Windows

**Comment by bschorchit** [comment]
Hey @StefSerbia, the logo is being fetched using our token detection feature so you need to have the logo updated in the token lists for it to be reflected in MetaMask. 
https://consensys.net/blog/metamask/how-to-use-metamasks-token-detection-feature/
