### ISSUE TITLE
[Bug]: Legitimate site blocked sun.eduzz.com

### ISSUE THREAD

**Issue by ffernandomoraes** [MetaMask/metamask-extension#16259]
### Describe the bug

https://sun.eduzz.com/

This is a online sales platform. Any one can sell digital goods. It's not a phishing site. Please remove this site from the block list because is affecting many legitime customers.

### Steps to reproduce

1. Access https://sun.eduzz.com/1636312 with the extension installed.

### Version

10.20.0

### Browser

Chrome

### Operating system

Windows, MacOS, Linux

**Comment by bschorchit** [comment]
Please open an issue in https://github.com/MetaMask/eth-phishing-detect for this
