### ISSUE TITLE
Wallet Tx Security Provider: add a new user property and a ui_customizations property

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16262]
## Background
[Epic on Notion](https://www.notion.so/Enable-MVP-support-for-tx-security-providers-954fef15373d4736b046566d20c93de1)
We want to update our metric scheme to capture the usage and efficacy of the new transactions security provider feature so we're able confidently iterate over and improve this feature.
As always, for anyone looking for more info on MetaMetrics, [here](https://medium.com/metamask/metametrics-a-refresher-on-metamasks-analytics-system-78d725cb9a75) is a good article.

## Tasks

1. Create a new user profile property (more info [here](https://help.mixpanel.com/hc/en-us/articles/115004501966#user-profile-properties)) called `security_provider`. This property should be a type list property (more info [here](https://help.mixpanel.com/hc/en-us/articles/115004547063-Properties-Supported-Data-Types#list)) and receive the value `opensea` if the user has enabled the transactions security provider feature under Settings > Experimental. Related ticket here https://github.com/MetaMask/metamask-extension/issues/16257.

2. If the user turns off the transactions security provider feature under Settings > Experimental, the user profile property `security_provider` should be updated to remove the `opensea` value from it.

3. Add a new property “ui_customizations” to `Transaction Approved`, `Transaction Rejected`, `Signature Approved` and `Signature Rejected` events.
This property should be a type list property (more info [here](https://help.mixpanel.com/hc/en-us/articles/115004547063-Properties-Supported-Data-Types#list)) and receive the value `flagged_as_malicious` when the transaction was flagged as malicious by the transaction security provider. Related ticket here https://github.com/MetaMask/metamask-extension/issues/16258 .

## Acceptance Criteria
1. This new properties are only collect for users that have opted in MetaMetrics.

**Comment by ElvirCe** [comment]
Waiting for #16281 to be merged before we can continue
