### ISSUE TITLE
[Bug]: "learn more" link from Connected account notification is broken

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16276]
### Describe the bug

**Problem**: "learn more" link from Connected account notification is broken

https://metamask.zendesk.com/hc/en-us/articles/360045129011-Intro-to-MetaMask-v8-extension

![image](https://user-images.githubusercontent.com/54408225/197830461-99da1419-94e6-4e71-a5a8-563a0f6cd285.png)

![image](https://user-images.githubusercontent.com/54408225/197830670-4d95893a-5d5f-4712-a697-42865e1772db.png)

### Steps to reproduce

1. Unlock MM
2. Connect to Test Dapp
3. Open MM popup
4. Click learn more from the Connected account notification

### Version

develop-oct25

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Is this a new copy that is being introduced in a coming release, @seaona ?

Currently in prod in v10.20 it looks like this for me:
<img width="363" alt="Screen Shot 2022-10-27 at 09 03 44" src="https://user-images.githubusercontent.com/34968356/198279456-33e7831d-d168-4034-82a1-446ad6b21795.png">

**Comment by bschorchit** [comment]
Oh wait, it seems I was doing a different thing. I've re-read and understood it's a notification that pops up. 

This could be a better 'Learn more' link for here: https://metamask.zendesk.com/hc/en-us/articles/4405506066331-User-guide-Dapps

Tagging @kevinghim in case he has more context around this.
