### ISSUE TITLE
Ensure MV3 works on Opera and Edge

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#16275]
@digiwand noticed buggy behaviour, in particular related to the service worker restart, on MV3 on Opera

We need to investigate and resolve

Also, we should check that this works on edge

--- 

Browser Support status for MV3 is being documented here: https://www.notion.so/Manifest-V3-5b35e49b12634c0b89563dea8a6afa33#5c17e481725741aa8c6898b92d157a36

**Comment by digiwand** [comment]
updated description to point to Browser Support notes I began documenting in Notion
https://www.notion.so/Manifest-V3-5b35e49b12634c0b89563dea8a6afa33#5c17e481725741aa8c6898b92d157a36

**Comment by segun** [comment]
Browser: Opera
Issue 2: If SW Restarts on Confirm Page, Confirm button is disabled and you get a continuous flashing of gas fees

https://user-images.githubusercontent.com/44811/200843715-af93f189-b985-4414-9cd0-a9ce421a27a7.mov
