### ISSUE TITLE
Notify users that we are dropping support for their current browser

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#16283]
We would like to notify users when we are planning to drop support for the browser they are currently using, so that users have at least once release to learn about this change and how it will impact them.

**Comment by Gudahtt** [comment]
The best way to do this is probably to utilize the home notification system, which you can see here: https://github.com/MetaMask/metamask-extension/blob/c519d3ef91ceb165498137f2c485c1696f43132b/ui/pages/home/home.component.js#L304-L551

We can add a new conditional notification that is only displayed for users of browsers that are planned to be deprecated soon. For now, we can use the range suggested in [this PR](https://github.com/MetaMask/metamask-extension/pull/12847), but this range will change over time.

For reference, here is the live Storybook page for the Home notification component: https://metamask.github.io/metamask-storybook/?path=/story/ui-components-app-home-notification-home-notification-stories-js--default-story

Open questions:
* Should we let the user dismiss this notification? If we do allow it to be dismissed, should this be a high-friction dismissal with an additional warning/confirmation step?
* What should the copy be for this warning?

**Comment by bschorchit** [comment]
When we were warning users about the deprecation of the test networks, we allowed the warning to be dismissible as it could get in the way of users doing important things, but the warning would re-appear once the user switched back to a test network that was going to be deprecated or closed and re-opened MM (annoying but hopefully effective). Maybe a similar approach could make sense here - for reference: https://github.com/MetaMask/metamask-extension/pull/15725

What happens to an user if they continue to use their current unsupported browser? Will they loose access to MM or will they be stuck at the last MM version that supports that browser?

**Comment by Gudahtt** [comment]
>What happens to an user if they continue to use their current unsupported browser? Will they loose access to MM or will they be stuck at the last MM version that supports that browser?

Great question! MetaMask will continue working, but they won't be able to update MetaMask until updating the browser first.

>we allowed the warning to be dismissible as it could get in the way of users doing important things, but the warning would re-appear once the user switched back to a test network that was going to be deprecated or closed and re-opened MM (annoying but hopefully effective).

Good example. I agree, a similar approach could work well here. It does make sense to allow the notice to be dismissed, but keep reminding the user about it.

I wonder what interval we could use here though, as it's not tied to any user action. Maybe once per day, or something like that?

**Comment by coreyjanssen** [comment]
Proposed copy:
Your browser is out of date
If you don't update your browser, you won't be able to get security patches and new features from MetaMask. 
[Button] Got it

**Comment by kevinghim** [comment]
> When/how often should we show the warning again after it is dismissed?
Had a discussion with @Gudahtt about alert intervals -- every other day would be appropriate as to not annoy users, but encourage them to update browser versions.
