### ISSUE TITLE
EthQuery failure on "eth_estimateGas"

### ISSUE THREAD

**Issue by travs** [MetaMask/metamask-extension#1628]
Trying to do send a transaction with MetaMask (MM) on the Kovan network.
Sometimes the transaction works fine through MM, other times it does not. 
Cannot seem to find a pattern.

The same transaction works fine in testrpc.

### Expected

Transaction to be sent successfully through MM.

### Actual

Receive in chrome console:
```
Error: Transaction execution error.
```

And in the background console:
```
ethquery failure
Object {method: "eth_estimateGas", params: Array(1)}
InternalError {message: "Transaction execution error.", code: -32603}

Error in RPC response:
 Object {message: "Transaction execution error.", code: -32000}
```

### Other information

Params to `eth_estimateGas` (from background console):
```
data
 : "0xf94ec495000000000000000000000000642cc820b0a9511975e2411461d3ed55c758b5ef0000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000de0b6b3a7640000",
from : "0x4144e17a116d78be38c42d580f40853a1fbfc63a",
gas : "0x442168",
gasPrice : "0x4a817c800",
to : "0x2bdf9f7e47192f7df8cc11941973430248d49b91",
value : "0x0"
```

Browsers (occurs on both):
- Chrome Version 59.0.3071.104 (Official Build) (64-bit)
- Chromium Version 59.0.3071.86 (Developer Build) (64-bit)

OS:
- Linux 4.11.3-1-ARCH w/ Gnome
- MacOS Sierra

This may even be something on the contract end, but I can't understand why the same transactions pass in testrpc then.
Let me know if you need any information.

**Comment by flyswatter** [comment]
Hi @travs, this is a fantastic bug report.

I've confirmed the bug is coming from our backend provider, and is accompanied by this error message:
`"Requires higher than upper limit of 1000000000000\"`

For one thing, we shouldn't be swallowing that error message, so we should fix that at the provider level.

I'll ask our provider folk at Infura if they understand why, this may be a provider limit, or maybe Kovan has an upper gas limit of 1000000000000 something?

Here's the JS reproduction code for others:

```javascript
web3.eth.estimateGas({
data:"0xf94ec495000000000000000000000000642cc820b0a9511975e2411461d3ed55c758b5ef0000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000de0b6b3a7640000",
from : "0x4144e17a116d78be38c42d580f40853a1fbfc63a",
gas : "0x442168",
gasPrice : "0x4a817c800",
to : "0x2bdf9f7e47192f7df8cc11941973430248d49b91",
value : "0x0"
}, console.log)
// null 23705
```

**Comment by kumavis** [comment]
Fixed here https://github.com/MetaMask/metamask-extension/pull/1883
