### ISSUE TITLE
[Bug]: After the web page connects to metamask, it can not jump to the next step

### ISSUE THREAD

**Issue by haoge0424** [MetaMask/metamask-extension#16297]
### Describe the bug

After the web page connects to metamask, it can not jump to the next step

### Steps to reproduce

1. open url  https://carv.io/home
2. login with wallet
3. In the new pop-up window, select the available program, metamask
4. Metamask pop-up window, after selecting an account, the web page displays Connecting to MetaMask...
5. But it's stuck all the time, and you can't jump like before. 
After attempting to uninstall the metamask plug-in, reinstall and the fault persists

### Error messages or log output

```shell
Approve Connection
Please approve the connection in your wallet and authorize access to continue.

Connecting...
Make sure to select all accounts that you want to grant access to.
```

### Version

10.20.0

### Browser

Chrome

### Operating system

Windows

**Comment by bschorchit** [comment]
Hey @haoge0424, after selecting the account, have you clicked on `Next` in the MetaMask popup and clicked on `Connect` on the following MetaMask screen (screenshot below)?
I was not able to reproduce this issue and connection flow seemed to work fine.  
<img width="363" alt="Screen Shot 2022-10-28 at 11 06 19" src="https://user-images.githubusercontent.com/34968356/198632651-5cd62a6c-a1b9-44ae-b0cf-8cf64fe66472.png">
