### ISSUE TITLE
Add personal_decryptMessage method

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1629]
People should be able to use their Ethereum addresses to send & receive encrypted messages.

`personal_decryptMessage(address, encryptedDataHex, callback)`

Opened on ProviderEngine here:
https://github.com/MetaMask/provider-engine/issues/168

Might also want to pair with a `personal_encryptMessage` or maybe `ethereum_encryptMessage`

`personal_encryptMessage(recipientPublicKeyHex, hexDataToEncrypt)`

**Comment by jennypollack** [comment]
closed via https://github.com/MetaMask/metamask-extension/pull/7831
