### ISSUE TITLE
Login screen blank?

### ISSUE THREAD

**Issue by markmcdonald51** [MetaMask/metamask-extension#1631]
Hi, 

Just looked thru the issue log and didnt see this problem.
I just clicked my metamask button and it comes up with a blank frame. This is the first time this has ever happened. I know my coins are ok because because the wallet shows up on etherscan.

Please advise.

Thanks in advance. This is an awesome project and I absolutely LOVE metamask --except for this [*small] problem.

Mark

![screenshot 2017-06-20 at 6 56 53 am](https://user-images.githubusercontent.com/39400/27330177-51ecd6ee-5586-11e7-90e2-98f9ca91d314.png)

**Comment by flyswatter** [comment]
I recommend right clicking to inspect this blank window and look for logs.

More types of logs if nothing is there:
https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by kumavis** [comment]
Let us know if you are still having trouble with this
