### ISSUE TITLE
[Bug]: Not able to create account in Ubuntu using V10.20.0

### ISSUE THREAD

**Issue by fribas84** [MetaMask/metamask-extension#16311]
### Describe the bug

When creating a new account, this is not being created and the an already created account is shown as duplicated:

![image](https://user-images.githubusercontent.com/36540317/198832313-29d8a382-1f5d-48ca-a728-82d845e22452.png)

Note: This wallet as imported

This also happens in Firefox

**Chrome version**: Version 107.0.5304.87 (Official Build) 
**OS**:
Linux fribas-XPS-15-9560 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
**MetaMask version**: 10.20.00

### Steps to reproduce

1. Import a Wallet from the recovery passphrase
2. Import several accounts using the private key
3. Try to create a new account

### Version

10.20.00

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
Thanks for the report @fribas84 . Is it possible by any chance, that on the Step 2, you are importing an account with a private key, which corresponds to the Account 2? So on step 3, when you create a new Account, the Account 2 is duplicated. See vid here:

https://user-images.githubusercontent.com/54408225/198891675-c9baf4ec-1f2c-43c3-815a-4fda4e67efe7.mp4

Could you reproduce this with previous MM versions as well?


Possibly related issue: https://github.com/MetaMask/metamask-extension/issues/14601
