### ISSUE TITLE
[Bug]: RPC ERRORS ALWAYS SHOW IN CONSOLE DESPITE CATCHING THEM IN TRY CATCH

### ISSUE THREAD

**Issue by Dinuz** [MetaMask/metamask-extension#16312]
### Describe the bug

Despite using the right error handling system (try/catch), and catching the error, Metamask still throw a duplicate error that I cannot intercept for the life of me. This shows a red error in console.
Would be incredible to understand how prevent the duplicate error (always an RPC error) to appear, and instead handling it with a more soft user experience.

### Steps to reproduce

1.Just try to run some connect code like the following:

```
try {
        const accounts = await ethereum.request({
          method: 'eth_requestAccounts',
        })
        console.log('Got it right bro')
} catch (error) {
        console.error(,'We got an issue: ', error)
}

```

2. Cancel the request (press cancel in the metamask extension)
3. You will get the error printed in the console (4001) as an object and you will get also MetaMask - RPC Error: User rejected the request. {code: 4001, message: 'User rejected the request.'} from inpage.js that show up in the console.

<img width="1419" alt="Screen Shot 2022-10-29 at 4 21 33 PM" src="https://user-images.githubusercontent.com/1139472/198851056-d86eb219-2534-4e6e-8a80-3686d57591a4.png">

I don't want to have duplicates, and I don't want to have the error showing up in console, what I can do?

### Version

10.20.0

### Browser

Chrome

### Operating system

MacOS

**Comment by xinnanyemm** [comment]
Please note that `label:team-dapp-api` has been replaced by `label:team-devex` . Thanks.

**Comment by vandan** [comment]
Needs reproduction @tmashuang

**Comment by tmashuang** [comment]
With the current version of the extension (v11.4.0) the errors are passed to the `catch` portion of the reproduction code.
