### ISSUE TITLE
[Bug]: [MV3] Networks are mixed up after terminating service worker, resuting mixing tx and networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16315]
### Describe the bug

**Problem**: when I am in the middle of a Send process, if I terminate the service worker and change networks, the transaction and networks are mixed up.

https://user-images.githubusercontent.com/54408225/198879521-691a11be-391e-424a-91eb-1c4ac40c44ae.mp4

### Steps to reproduce

1. Change to Goerli network
2. Click Send
3. Add recipient
4. Add amount
5. Terminate Service Worker
6. Change network to Sepolia
7. Click Continue -- see how network is changed but tx is sending GoerliETH
8. Click Send -- see how you are on the Sepolia Home page, but tx is displaying Goerli. Tx has been submitted to Sepolia

### Version

Tested on top of this PR https://github.com/MetaMask/metamask-extension/pull/15558

### Browser

Chrome

### Operating system

Linux

**Comment by adonesky1** [comment]
@seaona also having trouble reproducing this one on develop. Perhaps this is also blocked until #15558 is fixed/merged?

https://user-images.githubusercontent.com/34557516/200416629-08eddad4-59be-4dba-b8bf-5e3eb74be6e2.mov

**Comment by seaona** [comment]
I think so, we should wait for https://github.com/MetaMask/metamask-extension/pull/15558 so we can try to repro again the complete flow there @adonesky1

**Comment by adonesky1** [comment]
https://user-images.githubusercontent.com/34557516/201972584-6488a82f-57be-4cf6-be02-6554631e4e66.mov
