### ISSUE TITLE
[Bug]: [MV3] Error: `Attempting to use a Disconnected port object` and MM stays loading indefinetly

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16321]
### Describe the bug

**Problem**: when I terminate the service worker while using the MetaMask popup view, MetaMask enters on an indefinetly loading state and I get the following errors con the console:
- `Uncaught (in promise) Error: Attempting to use a disconnected port object`
- `Error: PortDuplexStream - disconnected   at PortDuplexStream._write`

![Screenshot from 2022-10-31 15-28-01](https://user-images.githubusercontent.com/54408225/199032428-2576670c-5a0e-4461-9197-48d8968e5231.png)

### Steps to reproduce

1. Load MM for the first time
2. Perform the onboarding process
3. Land at Home page
4. Close MM full width
5. Click on MM icon, for opening the popup view
6. Terminate the service worker
7. Click on MM icon again-- MM loads indefinitely and errors appear on the console

https://user-images.githubusercontent.com/54408225/199033458-be1a9298-dba1-4cf6-8111-58df82dd2f5f.mp4

### Version

Tested on top of this PR https://github.com/MetaMask/metamask-extension/pull/15558

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
Hey @seaona : I am not able to replicate the issue with latest code.

**Comment by jpuri** [comment]
After the latest changes in PR this particular issue is not replicating in the PR https://github.com/MetaMask/metamask-extension/pull/15558

**Comment by jpuri** [comment]
Fixed by merging: https://github.com/MetaMask/metamask-extension/pull/16393
