### ISSUE TITLE
Individual snap settings page crashes if a snap has no permissions

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#16333]
If you click "See Details" on a particular snap in the Snaps Settings page, the extension UI will crash if that snap has no permissions.

Error:
```
Message: Cannot read properties of undefined (reading 'permissions')

Code: TypeError

Stack:
TypeError: Cannot read properties of undefined (reading 'permissions')
  at n.getPermissions (...)
```

We should probably handle this case in the UI, but we could _conceivably_ ignore this problem if we instead enforce in the `SnapController` that every snap must have at least one permission.

**Comment by FrederikBolding** [comment]
https://github.com/MetaMask/snaps-monorepo/issues/899
