### ISSUE TITLE
[Bug]: Unable to list or transfer ERC721 - Uncaught (in promise) BigNumber Error: new BigNumber() not a number: undefined

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-extension#16334]
### Describe the bug

When trying to list or transfer a specific NFT on OpenSea. The MetaMask transaction approval screen freezes with a spinning circle.

https://user-images.githubusercontent.com/2859402/199108453-7ca1a459-953c-452a-a4d2-1964e2aeb571.mov

### Steps to reproduce

1. Initiate the transaction to list or transfer the NFT
2. Error

### Error messages or log output

```shell
Uncaught (in promise) BigNumber Error: new BigNumber() not a number: undefined
  at ee (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:93856)
  at x (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:99336)
  at new Y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:91758)
  at I (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:141474)
  at n.getAssetDetails (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:138574)
  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:324158
```

### Version

10.20.0

### Browser

Chrome, Firefox, Brave

### Operating system

MacOS

### Additional context

NFT contract: https://etherscan.io/address/0x586dae24dd99ac8a240cc475b052a9f737808073
This issue does not occur when using certain older versions of MetaMask, such as 10.16.1

**Comment by bschorchit** [comment]
I was able to reproduce it by going to https://etherscan.io/address/0x586dae24dd99ac8a240cc475b052a9f737808073#writeContract and calling the safeTransferFrom method.

**Comment by VSaric** [comment]
I was able to reproduce this issue @bschorchit, so I will take action on this! 😄

**Comment by bschorchit** [comment]
Hey @deshvin , it seems this is no longer an issue in version 10.21.1. Could you update your MetaMask and confirm it? Thank you!

**Comment by deshvin** [comment]
@bschorchit Confirmed resolved. Thank you all!
