### ISSUE TITLE
[Bug]: Custom Networks Aurora and Palm don't display fiat conversion

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16356]
### Describe the bug

**Problem**: custom networks Aurora and Palm don't display fiat conversion

![Screenshot from 2022-11-02 17-23-18](https://user-images.githubusercontent.com/54408225/199545007-b19171e8-d0be-4aa6-8ca6-1f7fd55ddb22.png)
![Screenshot from 2022-11-02 17-23-06](https://user-images.githubusercontent.com/54408225/199545014-f3e55329-9319-4166-bccc-cd6616152579.png)

### Steps to reproduce

1. Unlock MM
2. Go to Settings // Networks
3. Add Aurora and Palm networks
4. Switch to Aurora / Palm network -- see no fiat conversion is displayed

### Version

10.22.0

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
This appears to be an issue with the api we use to get the fiat prices.

`curl 'https://min-api.cryptocompare.com/data/price?fsym=AVAX&tsyms=USD'` returns `{"USD":14.57}`

but

`curl 'https://min-api.cryptocompare.com/data/price?fsym=AURORA%20ETH&tsyms=USD'` returns `{"Response":"Error","Message":"cccagg_or_exchange market does not exist for this coin pair (AURORA ETH-USD)","HasWarning":false,"Type":1,"RateLimit":{},"Data":{},"Cooldown":0}`

Same for Palm.

So we'd have to fix this either by talking to cryptocompare and see if they can fix it, or finding a new api to use.

@bschorchit Should this be blocking? Can we ship v10.22.0 with this know issue on these networks?

**Comment by bschorchit** [comment]
> @bschorchit Should this be blocking? Can we ship v10.22.0 with this know issue on these networks?
We should not block on this. Let's continue with 10.22 as is and work on a fix for a future release.

cc: @kevinghim as this might have some overlap with the work to not show fiat value/or warn users for custom networks that are test networks.
