### ISSUE TITLE
[Bug]: Can't import a JSON wallet with "" as a password (empty string)

### ISSUE THREAD

**Issue by Mouradif** [MetaMask/metamask-extension#16369]
### Describe the bug

When trying to import a JSON wallet (from `geth account new`), the button to confirm will be disabled as long as the password's length is 0.

### Steps to reproduce

1. With Geth, run `geth account new` then press ENTER twice (aka, no password)
2. Import the resulting JSON file on Metamask
3. Observe the "Import" button being disabled

### Version

10.20.0

### Build type

Extension from the Chrome store

### Browser

Chrome

### Operating system

MacOS (probably irrelevant)

**Comment by plasmacorral** [comment]
Closing this as https://github.com/MetaMask/metamask-extension/pull/19132 was merged
