### ISSUE TITLE
e2e Best practices [documentation]

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#16376]

**Comment by PeterYinusa** [comment]
[MM Extension E2E Test Guidelines](https://docs.google.com/document/d/1eQyeScSZQlzGLapef_8PANkU_ObNPJcuMCP040T2gfM/edit)

**Comment by brad-decker** [comment]
@PeterYinusa this document looks great.

**Comment by PeterYinusa** [comment]
All new work on this documentation will be captured in a new issue
