### ISSUE TITLE
[Bug]: there is a typo in the duplicate account import message

### ISSUE THREAD

**Issue by TimTinkers** [MetaMask/metamask-extension#16370]
### Describe the bug

![before](https://user-images.githubusercontent.com/2444641/199837420-80af577a-a9d7-4376-9f20-d98c95c1580b.png)

### Steps to reproduce

1. Import an account using a private key.
2. Attempt to import that same account again.
3. You will see this typo.

### Version

10.21.1

### Browser

Firefox

### Operating system

Windows

**Comment by TimTinkers** [comment]
This is a minor bug and I've submitted pull requests to fix it.

**Comment by HowardBraham** [comment]
Fixed with #15558
