### ISSUE TITLE
[Bug]: Tenderly should be fetching gasPrices, and not suggestedGasFees from eth_gasPrice

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#16389]
### Describe the bug

From the #metamask-tenderly Slack [thread](https://consensys.slack.com/archives/C03T3QM4UBY/p1666117261625869).

Some of our users are trying to connect MetaMask with our Fork RPC from Optimistic, but it seems that the connection with Metamask is hanging for about 20-30s before actually executing an action (click of whichever button). We’ve tried other networks and RPC providers and it seems to work. In order to gather more data we have tried to add the same Fork RPC to the Metamask Flask in order to catch the reason for the error and we caught one different behavior.
It seems like the rest of the RPCs are not fetching `suggestedGasFees`, but our RPC ends up using this one https://gas-api.metaswap.codefi.network/networks/10/suggestedGasFees which throws the following error: `"error": "Cannot read properties of undefined (reading 'getBlock')"` and rest of RPC request are just hanging in the meantime.

We have logic setup where if the transaction is legacy (non EIP-1559), we try the gas-API first at the `gasPrices` endpoint and fall back to the `eth_gasPrice` if it fails. So, for 'legacy' we'll hit legacyAPIEndpoint: `${gasApiBaseUrl}/networks/<chain_id>/gasPrices`,
For EIP-1559 API Endpoint: `${gasApiBaseUrl}/networks/<chain_id>/suggestedGasFees`

### Steps to reproduce

N/A

### Version

10.20.0

### Browser

Chrome

### Operating system

MacOS

**Comment by Riphal** [comment]
Hey @kevinghim, we discovered it was an error on our end and we deployed a fix.
So can you please check if everything is working now?
