### ISSUE TITLE
[Bug]: Introducing an EOA when adding a Custom Token causes MM load indefinetly

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16397]
### Describe the bug

**Problem**: when I want to import a custom token and I introduce an EOA address instead of a token address, makes MM stay loading indefinitely when I then try to Send that token. I also see the error:
`Unable to determine contract standard`

https://user-images.githubusercontent.com/54408225/200345618-ee63431b-473c-415f-b1fa-1a3cd145d45f.mp4

**Expected**: in the same way that we flag a personal address, when introducing any of our Account's address, we could flag all EOA addresses, when trying to import them as token contracts @bschorchit ?

![Screenshot from 2022-11-07 16-10-54](https://user-images.githubusercontent.com/54408225/200345787-6786c6a9-983a-4cab-bf09-284e63ab973d.png)

### Steps to reproduce

1. Select Mainnet network
2. Click Import Token
3. Click Add Custom Token
4. Paste an EOA address. It can be any, except the ones from your account. I.e. `0xeF09C75F9a32532685fD8029De2738F580B00394`
5. Click Import
6. Click Send -- MM stays loading indefinetly and we see the error on the console.log

### Version

10.22.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
oh interesting! We have had some discussions around flagging EOAs in other flows and I believe we're not able to tell with 100% accuracy that an address belongs to an EOA.
But there're probably things we can do to avoid getting in this loading forever state either in the form itself or in the send flow (in case there're valid use cases for adding tokens that we cannot determine the contract standard of).

**Comment by bschorchit** [comment]
This is still an issue on v. 10.35

**Comment by seaona** [comment]
This is still an issue. Now you can import the token but when click Send, MM stays loading indefinetly


![Screenshot from 2024-03-28 12-28-28](https://github.com/MetaMask/metamask-extension/assets/54408225/56bcfcd4-5098-419d-bd23-a7956df694eb)
