### ISSUE TITLE
Remove the extra space in the new signTypedData_v4 header

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16405]
## Background
https://github.com/MetaMask/metamask-extension/pull/16018#pullrequestreview-1170728506

## Screenshot
![image](https://user-images.githubusercontent.com/34968356/200428489-1dee1810-8155-4cec-8973-f194f3259f08.png)

**Comment by ElvirCe** [comment]
@bschorchit the spacing issue was already addressed with this ticket https://github.com/MetaMask/metamask-extension/issues/15705 and this PR https://github.com/MetaMask/metamask-extension/pull/15776 so we can close this one.

**Comment by bschorchit** [comment]
> @bschorchit the spacing issue was already addressed with this ticket https://github.com/MetaMask/metamask-extension/issues/15705 and this PR https://github.com/MetaMask/metamask-extension/pull/15776 so we can close this one. 

Ooh awesome!! Thanks @ElvirCe ! ❤️🚀
