### ISSUE TITLE
Skip the first token allowance screen if a dapp is proposing a spending cap of 0

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16428]
## Background
When a dapp is proposing the spending cap to be 0, we want to go directly to the second token allowance screen and have the copy say `Revoke the spending cap for your` instead of `Review the spending cap for your` . 

## Acceptance Criteria
1. When a dapp proposed value for the spending cap is zero, the user is sent directly to the second screen in the flow and the spending cap is kept as 0 and the title copy reads `Revoke the spending cap for your`.

## Steps to reproduce
1. Go to https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f#writeContract
2. Connect your wallet
3. Under approve input any address and 0 as the value
4. Click on write

## Reference

- [Previous ticket](https://github.com/MetaMask/metamask-extension/issues/15220)
- [Figma Design File](https://www.figma.com/file/n0xMnZqQz4w9Sfa3ZdhWUi/Consentful-experience-for-token-allowances?node-id=2007%3A14265)

![image](https://user-images.githubusercontent.com/34968356/200850701-64fdd440-227f-4876-ad81-b725c95cba1f.png)

**Comment by ElvirCe** [comment]
@bschorchit Please note that this functionality was covered with the ticket https://github.com/MetaMask/metamask-extension/issues/16234
I believe that we can close this ticket.

**Comment by ElvirCe** [comment]
@bschorchit Please ignore my previous comment as the ticket #16234 did not cover this flow. We will prepare the ticket and work on it based on the prioritization list.
