### ISSUE TITLE
Spending cap value inputed in a different token allowance request persist to others

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16429]
## Background
If multiple token allowance requests and the users inputs a number in the first request and then cancel the first request, the value inputted persists on the second token allowance screen. This shouldn't happen. Any new pending request should have an empty state in the custom spending cap field just like the first request originally had (before the user inputted a number). 

## Acceptance Criterias
1. All new token allowance requests are initially displayed with an empty value for the custom spending cap field (as in screenshot below).

## Steps to Reproduce
1. Go to https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f#writeContract
2. Connect your wallet
3. Under approve input any address and value
4. Click on write
5. On the MetaMask popup click on `Use default` or input a number in the spending cap field
6. Go back to the etherscan site and click on write again to create a new token allowance request
7. See the popup for the first request open up on MetaMask and click on `Reject`
8. See how the value you have inputted in the first requests is also being shown as if you had inputted it in the second request

## Screenshot
<img width="361" alt="Screen Shot 2022-11-23 at 10 27 19" src="https://user-images.githubusercontent.com/34968356/203558491-ebf20dba-db4d-4397-b049-a5298d0dbbc4.png">

**Comment by bschorchit** [comment]
@seaona for awareness, I caught this while testing

**Comment by seaona** [comment]
@bschorchit nice catch! I could repro following the steps. 
I have another question related to that. Is it okay to assume that the Spender address is always a contract? See the text `Contract requesting spending cap`.
I.e. below I am approving permissions to one of my addresses `0x07Be9763a718C0539017E2Ab6fC42853b4aEeb6B`, which is not a contract address.


![image](https://user-images.githubusercontent.com/54408225/201921672-736bc262-b8aa-48f9-8ee5-0f43f8517a0a.png)

**Comment by bschorchit** [comment]
Added a recording for this: 

https://user-images.githubusercontent.com/34968356/202453560-cc832002-ed53-4137-8933-df808a655a54.mov

**Comment by bschorchit** [comment]
> @bschorchit nice catch! I could repro following the steps. I have another question related to that. Is it okay to assume that the Spender address is always a contract? See the text `Contract requesting spending cap`. I.e. below I am approving permissions to one of my addresses `0x07Be9763a718C0539017E2Ab6fC42853b4aEeb6B`, which is not a contract address.
> 
> ![image](https://user-images.githubusercontent.com/54408225/201921672-736bc262-b8aa-48f9-8ee5-0f43f8517a0a.png)

Just for visibility, I've created a new ticket to work on this here https://github.com/MetaMask/metamask-extension/issues/16587
