### ISSUE TITLE
Update the What's New

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16444]
We should add a what's new content about the new Improved token allowance experience (and remove the other previous announcements)

The new content:

> **Improved token allowance experience**
> We have re-designed the token allowance flow to better empower you on your decisions. Enable it _here_ to be one of the firsts to try it out! 

^ here is a link that take users to Settings > Experimental > Improved token allowance experience.

**Comment by coreyjanssen** [comment]
Improved token allowance
We redesigned our token allowance feature to help you make more informed decisions. Try it out _here._

**Comment by bschorchit** [comment]
> Thoughts on this rewrite @bschorchit?
> 
> 
> 
> Improved token allowance
> 
> We redesigned our token allowance feature to help you make more informed decisions. Try it out _here._

I love the magic you do with words ❤️

**Comment by ElvirCe** [comment]
Final decision: 

**Improved token allowance experience**
We redesigned our token allowance feature to help you make more informed decisions. Try it out here.

Note: here is a link that take users to Settings > Experimental > Improved token allowance experience.

**Comment by bschorchit** [comment]
Actually, small change on copy (just changing the word `feature` to `confirmation`):

> Improved token allowance
> 
> We redesigned our token allowance confirmation to help you make more informed decisions. Try it out here.

cc: @adnansahovic

**Comment by seaona** [comment]
Ty for tagging @bschorchit !! I cherry-picked this commit to the RC branch
