### ISSUE TITLE
[Bug]: Cannot Add a Network with same chainId programmatically from a Dapp

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16467]
### Describe the bug

**Problem**: when I add a network with the same ChainId (i.e. flashbots) from a Dapp, I cannot do it, whereas it is possible to do from the MetaMask UI.
I see the error `MetaMask - RPC Error: May not specify default MetaMask chain. appears.`

https://user-images.githubusercontent.com/54408225/201384748-1381abcd-f96f-42c4-a77d-78a01db3d94d.mp4

### Steps to reproduce

1. Clone the [test-dapp](https://github.com/MetaMask/test-dapp/blob/main/src/index.js#L362) project and change the predefault network to Flashbots
```
      method: 'wallet_addEthereumChain',
      params: [
        {
          chainId: '0x1',
          rpcUrls: ['https://rpc.flashbots.net'],
          chainName: 'Flashbots',
          nativeCurrency: { name: 'TEST', decimals: 18, symbol: 'TEST' },
          blockExplorerUrls: null,
        },
```
2. Run the project `npm run start`
3. Connect MetaMask to the test dapp
4. Click Add Localhost 8546 -- check UI console and see the error

### Version

10.22.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
We might one to address this https://github.com/MetaMask/metamask-extension/issues/15909 before.

**Comment by adonesky1** [comment]
This is resolved by https://github.com/MetaMask/metamask-extension/pull/16733
