### ISSUE TITLE
Align Snaps connect, install, and update screens

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#16462]
The Snaps **connect**, **install**, and **update** screens should look great and be consistent.

**Comment by rekmarks** [comment]
Relevant Figma at the time of writing: https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=1602%3A30966

**Comment by rekmarks** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/16462?planning-poker) with Zenhub @eriknson

**Comment by kenhkan** [comment]
Next step: To finish this ticket (the design part), share the design with wider team, and then split up https://app.zenhub.com/workspaces/snaps-platform-615b3a7c08d2b20015eb6c4e/issues/metamask/snaps-monorepo/892 after the agreement.

**Comment by eriknson** [comment]
Here's the [suggested flows](https://www.figma.com/file/bu0wn08HxqroElntka765S/Install-flow?node-id=15%3A181&t=pxkVF7837VUAAY1k-1) for our install and connect flows respectively (all in one popup). Closing this and opening #1115 for the visual design part to unblock [#892](https://github.com/MetaMask/snaps-monorepo/issues/892).
