### ISSUE TITLE
Clean up Snaps settings page / screens

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#16463]
We should clean up the Snaps settings page and align it with our latest design patterns.

Related: #16462

**Comment by rekmarks** [comment]
Currently relevant Figma: https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=1880%3A32847

**Comment by rekmarks** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/16463?planning-poker) with Zenhub @eriknson

**Comment by eriknson** [comment]
Ready for review: https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-components?node-id=22%3A9055&t=rf0HDawwUO0wuk7n-1

**Comment by eriknson** [comment]
Settings design: https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-features?node-id=55%3A11895&t=BXJJ6gBIdAsILGhl-1

Permission component: https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-features?node-id=135%3A24230&t=BXJJ6gBIdAsILGhl-1

**Comment by eriknson** [comment]
Opening [#1170](https://github.com/MetaMask/snaps-monorepo/issues/1170) for implementation
