### ISSUE TITLE
[Bug]:  Binance testnet can't load

### ISSUE THREAD

**Issue by sl1taz** [MetaMask/metamask-extension#16468]
### Describe the bug

Since yesterday I can't use the binance testnet in metamask.
I've tested it on several different computers, several different internets and I get the same error.
I haven't found anything on the internet about it either.

<img width="362" alt="Screen Shot 2022-11-11 at 2 04 38 PM" src="https://user-images.githubusercontent.com/20157967/201392245-e36eb88d-50c1-4dd5-b81a-551bf71c20bb.png">

<img width="352" alt="Screen Shot 2022-11-11 at 2 04 51 PM" src="https://user-images.githubusercontent.com/20157967/201392251-858a5517-f068-4f76-a88e-bad88897364c.png">

### Steps to reproduce

1. Just add Binance Testnet chain on Metamask Wallet 
2. [Step to add network](https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain)

### Version

10.21.2

### Browser

Chrome

### Operating system

Windows, MacOS

**Comment by bschorchit** [comment]
Hey @sl1taz, this looks like an issue with the `rpc url` of the network you're trying to use. MetaMask is trying to connect to it, but it's not responding. You can go to `Settings` > `Network` > `Smart Chain Testnet` and change the `rpc url` for a new one.

**Comment by sl1taz** [comment]
@bschorchit Thank you for the advice. But somehow, after 3 days, it started working normally again.
