### ISSUE TITLE
Establish clear distinction between data coming from MetaMask itself and snaps

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#16460]
Establishing a clear distinction between data coming from MetaMask itself and from snaps is critical to ensure that snaps are safe to use, especially as snaps are more deeply integrated into to MetaMask UI.

This needs to be solved systemically via the design system, not on a case-by-case basis.

**Comment by rekmarks** [comment]
Relevant Figma at the time of writing: https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=1209%3A29490

**Comment by rekmarks** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/16460?planning-poker) with Zenhub @eriknson

**Comment by kenhkan** [comment]
Erik to split this ticket into smaller tickets.

**Comment by eriknson** [comment]
Split into #16997 and #16999.
