### ISSUE TITLE
[Bug]: SuggestedGasFees return a 500 response for Sepolia network

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16478]
### Describe the bug

**Problem**: gas api is returning a 500 error for `suggestedGasFees` for Sepolia network.

https://user-images.githubusercontent.com/54408225/201642715-4f58138f-9537-49b4-9a2f-aaaf804d2dfa.mp4

### Steps to reproduce

1. Unlock MM
2. Change network to Sepolia
3. Check background network requests

### Version

10.22.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I believe this happens because the gas api does not support Sepolia yet

**Comment by bschorchit** [comment]
I believe this has been fixed now that the gas api has added support for Sepolia
