### ISSUE TITLE
[Bug]: warning of a deceptive site ahead inside MM window/iframe

### ISSUE THREAD

**Issue by 1c4m3by** [MetaMask/metamask-extension#16499]
### Describe the bug

<img width="104" alt="image" src="https://user-images.githubusercontent.com/103007456/201801708-7ee8b599-cf60-476a-96f2-e4af7ed4f10f.png">

### Steps to reproduce

1.to reproduce 
it will require to be connected to a site which is blocklisted by metamask and then try hit **connected sites**

browser: Brave

MetaMask Version
10.21.2

### Version

10.21.2

### Browser

Brave

### Operating system

MacOS

**Comment by bschorchit** [comment]
How should we best handle this, @MetaEZ and @holantonela ? Besides fixing the bug, do we want to flag/censor the malicious url somehow in the connected sites?

**Comment by MetaEZ** [comment]
@bschorchit Hey, I do not understand the "do we want to flag/censor the malicious url somehow in the connected sites? "

The site is correctly flagged, the bug needs to be fixed as you can not really enter "connected sites" as the red warning fills up the window ( there is a workaround ) but its not relevant right now.

The block of the pages that contains malicious url should still continue on the main window ( browser ) and not affect the area where connected sites are shown in the metamask popup window, as we usually want to disconnect our wallets from connected sites.
<img width="267" alt="Screenshot 2022-11-21 at 22 41 32" src="https://user-images.githubusercontent.com/103007456/203163703-e550d2c8-3fbd-43b7-9fc1-fd10f7547143.png">

**Comment by MetaEZ** [comment]
https://user-images.githubusercontent.com/103007456/203164333-5c3f1747-e8ac-4c38-b16a-64424dd687e9.mov

@bschorchit

**Comment by bschorchit** [comment]
oh sorry, yes, I should have expressed myself better. I meant, once the bug is fixed and the user is able to visualize the lists of sites again. Do we want to call out in the UI (screenshot) that that url that is listed there has been flagged as amalicious url (e.g. have a warning under the url, replace the logo for a red warning sign) or should we list it normally just like any other url?

<img width="359" alt="Screen Shot 2022-11-21 at 18 47 40" src="https://user-images.githubusercontent.com/34968356/203164649-3597a344-6dda-4271-ac9d-4ab3b7470dfd.png">

**Comment by holantonela** [comment]
> Besides fixing the bug, do we want to flag/censor the malicious url somehow in the connected sites?

Yes, we should implement our Tag URL component which must be reactive to the protocol and the blocklists. Some work in progress [here](https://www.figma.com/file/UrgBhtvoCEZiYzjptgXAsL/Security-indicators-in-confirmation-screen?node-id=1%3A5&t=ankTHVTMIRX0sG2q-1) .

**Comment by MetaEZ** [comment]
I got a question that its not related to this topic, is it fine if i drop it here?

**Comment by MetaEZ** [comment]
<img width="1249" alt="Screenshot 2022-11-25 at 18 33 51" src="https://user-images.githubusercontent.com/103007456/204034236-af5f412b-5716-4db7-9347-e39b22cf3549.png">

@holantonela @bschorchit  another idea is to use etherscan for marked phishing address/contracts , as we can see here metamask doesnt say much about this. but actually this would had stolen all my eth

Idea would be either totally flag it or give a yellow/red warning that would say marked as phishing on etherscan etc ?

**Comment by bschorchit** [comment]
Was this mistakenly closed, @1c4m3by ?

**Comment by 1c4m3by** [comment]
> Was this mistakenly closed, @1c4m3by ?

There was no more response in here, also bug seems fixed ? I do not get the issue.

**Comment by dzfjz** [comment]
@1c4m3by Can you please provide detailed steps how to reproduce this, as I was not able to do it ?

**Comment by 1c4m3by** [comment]
@dzfjz you need to connect to a website that is flagged by metamask blocklist, and then you need to open metamask and click "connected sites"  and then the pop up should appear.
