### ISSUE TITLE
[Bug]: No conneted/Not connected button when on IPFS

### ISSUE THREAD

**Issue by sbuljac** [MetaMask/metamask-extension#16501]
### Describe the bug

When I load any dapp over IPFS, Metamask is not showing connected/not connected button, so user is not  able to switch accounts.

### Steps to reproduce

1. Use brave with IPFS companion plugin
2. Go to ipns://app.aave.com/
3. Connect the wallet on website
4. After you current account is connected try switching to another account
5. You can log out on Aave app but next time you click connect you will be connect with account that you used first time even after you switch to other account in Metamask and since there is no "connected/not connected" button you can't force connection.

### Version

10.21.2

### Browser

Brave

### Operating system

Windows

**Comment by Flores002** [comment]
Have you try to reauthentic your wallet first

**Comment by sbuljac** [comment]
Yes, I tried everything, I can connect with first account but I can switch to any other account.
