### ISSUE TITLE
Reposition beta lockup from top right to bottom right

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#16512]
## Background
We have a request from the Marketing branding team to reposition the beta lockup from top right to bottom right to distinguish it from the Flask brand. For context, here's the [thread](https://consensys.slack.com/archives/GETEW1V4M/p1667917451481379) about this. After a conversation with the brand marketing team, the `beta` color will remain the same blue, but the positioning will change from top right to bottom right.

## Design assets 
- metamask-beta-logo-horizontal-dark-1.svg is 272 (w) x 43 (h) px
- metamask-beta-logo-horizontal-dark.svg is 723 (w) x 114 (h) px
![metamask-beta-logo-horizontal-dark-1.svg](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/95bf8534-9037-4ab1-adcc-ae44e734cc44)
![metamask-beta-logo-horizontal-dark.svg](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/620b393f-d999-437b-ab70-2b1984afa433)

**Comment by DDDDDanica** [comment]
Done in this MR: 
https://github.com/MetaMask/metamask-extension/pull/16505
