### ISSUE TITLE
[Bug]: OSX Firefox Big Memory Leak

### ISSUE THREAD

**Issue by web3-person** [MetaMask/metamask-extension#16524]
### Describe the bug

Without the MetaMask extension enabled, Firefox uses a nominal amount of ram.
However as soon as I enable the MetaMask extension, Firefox starts slowly chewing up ram until it’s consumed all of it, and CPU usage goes towards 100% (see screenshots).
It takes about 15 minutes to claw up to use my full systems ram capacity (8gb).

I noticed about a month ago the Firefox far more CPU resources than usual, but didn’t think much of it as I’ve not been using Firefox much. however recently I started using it more and wanted to try to get to the bottom of it, so I tried disabled extensions one by one, and turns out its MetaMask with the memory leak.

Also the memory leak appears to be multiplied by how many tabs you have open….
Conversely if you have no web pages open (just settings pages etc), there is no memory leak.

### **NORMAL FIREFOX CPU/RAM USAGE (MetaMask extension DISABLED):**

<img width="869" alt="no mm cpu" src="https://user-images.githubusercontent.com/24273561/202171102-98007996-8edf-4e59-a085-87d9d3e1a83b.png">
<img width="796" alt="no mm ram" src="https://user-images.githubusercontent.com/24273561/202171116-b3cb1c76-3607-4e53-85e8-0e7f678a57d7.png">

.

### **RAM USAGE STARTS RAMPING UP (MetaMask extension ENABLED (approx T+00:05))**

<img width="869" alt="mid" src="https://user-images.githubusercontent.com/24273561/202171907-d1323216-2cae-430b-8208-2e21a98d4f6c.png">

.

### **FULL LEAK MODE (MetaMask extension ENABLED (approx T+00:15))**

<img width="869" alt="yes mm high cpu" src="https://user-images.githubusercontent.com/24273561/202172515-439eb5c2-99f4-484b-b0d0-2d8943ff180f.png">
<img width="869" alt="yes mm high ram" src="https://user-images.githubusercontent.com/24273561/202172557-85456d10-1be6-420e-9323-563a6285413f.png">

### Steps to reproduce

1. Have a MacBook Pro early 2015 13 inch with Monterey 12.6 (?)
2. Use latest Firefox: (Firefox 107.0 (20221110173214))
3. Install latest metamask extension: 10.21.2
4. voila (?)

### Version

10.21.2

### Browser

Firefox

### Operating system

MacOS

**Comment by bschorchit** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/16421 and https://github.com/MetaMask/metamask-extension/issues/16372

**Comment by brad-decker** [comment]
The below is copy and pasted from #16372 
---

### Describe the bug

my RAM usage kept increasing when I went on Firefox (v. 106.0.4 (64 bits) on Windows). 

![image](https://user-images.githubusercontent.com/28791624/199840359-8212cc9a-69e0-458e-9b45-8c0ec5617058.png)

I have only 3 tabs opened, https://support-mozilla, about-addons and github.

I desactivated all the extensions I had and the memory usage dropped to a normal usage. 

![image](https://user-images.githubusercontent.com/28791624/199841132-efa82c15-7cf4-425b-91e3-8259d33020e8.png)

Sometimes, it freezes my navigator when I use greedy apps like Youtube, Netflix etc.


### Steps to reproduce

1. Metamask version 10.21.1
2. Firefox version 106.0.4 (64 bits) on Windows
3. Install MetaMask and open Firefox. 
4. See memory usage increase. 


### Error messages or log output

_No response_

### Version

10.21.1

### Build type

_No response_

### Browser

Firefox

### Operating system

Windows

### Hardware wallet

_No response_

### Additional context

_No response_

**Comment by platocrat** [comment]
i experienced this bug today

very annoying bc i thought it was an issue with Mac OS Ventura
I even reinstalled Ventura. 

Luckily, i found out what the issue was afterwards bc reinstalling Ventura somehow broke MM in Firefox, which led me to MM support, which led to this GitHub issue

**Comment by dvartic** [comment]
I also happens on mine. Firefox 109, Metamask 10.22.2 running on Linux 6.1

Duplicate issue of https://github.com/MetaMask/metamask-extension/issues/17112 and https://github.com/MetaMask/metamask-extension/issues/17112

Memory leak is huge.

**Comment by ZeroXRa** [comment]
I have been getting this issue for the oast couple weeks, originaly assumed it was an issue with my PC but when i kill the Mozillafirefox procces using all of my ram, metamask is killed.
