### ISSUE TITLE
Transaction failed and still pending

### ISSUE THREAD

**Issue by Durfel** [MetaMask/metamask-extension#1652]
Hi there! I created MetaMask account to participate in Status IM ICO and transferred 1.01 ETH from Coinbase. When the block number hit according value I started contribution process, as per instruction gas price = 200 000, gwei = 50. However something went wrong, the transactions was marked as pending and on transaction number redirected to Eitherscan showed "Unable to locate Transaction entry". Then after a while transaction showed as failed with reason "Gave up submitting tx". After some time I decided to kick the ETH back to my account on Coinbase. The same thing happened - no transaction, however it's not showed as failed.
![capture3](https://user-images.githubusercontent.com/29608397/27396327-659ff9b0-56bb-11e7-9647-85854e4faca3.PNG)

What is strange is that when I look on the wallet on Eitherscan it shows me that the first transaction is pending.
![capture](https://user-images.githubusercontent.com/29608397/27396061-985b73da-56ba-11e7-8c85-50c593a2a7a7.PNG)
![capture2](https://user-images.githubusercontent.com/29608397/27396060-98593994-56ba-11e7-9494-a7a6aea93d57.PNG)

The transaction Hash is 0xe929d10b6bec6cfd63a5f57fae8669da64f763f9343dbd43e5ce04fecc5cbded.

Can someone explain to me what's happening for how long MetaMask would try to resubmit tx, and when I'll be able to put ETH to back to my Coinbase account, since I've already missed Status ICO.

Browser:  Chrome Version 58.0.3029.110 (64-bit)
MetaMask: Version 3.7.8

Thanks a lot!

**Comment by Zanibas** [comment]
Eventually the first transaction from your first address to the token sale should either fail or be 'forgotten' by the network. At that point (which is hard to say when that'll happen), you should be able to resubmit a transaction that kicks your funds back to Coinbase. In the best case the first transaction fails and the second one eventually goes through, in the likely case you could wait for the ultimate fate of those two transactions and then resubmit when the network is more stable.

We resubmit every 10 seconds up to 200 times until we mark it  as "giving up submitting tx". However, this does not necessarily mean that your transaction won't reach the network, it means we as a client have stopped attempting to push requests for submission. We will be working on better UI for this in the future.

**Comment by kumavis** [comment]
@Durfel let us know if you are still having issues sending transactions

**Comment by woodae** [comment]
hi i am facing the same problem

**Comment by woodae** [comment]
my transaction is forgetten by the network in etherscan. etherscan shows that i have the eth, but in metamask the transaction is still pending and eth has not been returned to my metamask

**Comment by Durfel** [comment]
@woodae As I understand my problem was due to unusually high transaction volumes of ETH, so my transactions were pending for a couple of days, and then got cancelled. After it happend and the volumes went down I tried to initiate transaction one more time and it was successful. I know this feeling is very frustraiting when your funds or tokens are stuck with MetaMask, but I think you'll be fine as well, just wait for a bit and initiate new transaction when the previous is cancelled.

**Comment by woodae** [comment]
@durfei Thank you for your help, was that a unique problem of metamask? are you still using it?

**Comment by Durfel** [comment]
@woodae I don't  know, to be honest. I used it once to participate in ICO, and this experience was quite unpleasant, as you can imagine. I haven't used it since.

**Comment by burkecolby** [comment]
Hi - I sent eth from coinbase to metamask chrome extension. Has been showing as pending for 65 minutes now. Any ideas what is happening ?
