### ISSUE TITLE
Transactions stuck pending - Unable to do anything

### ISSUE THREAD

**Issue by Helpplxlol** [MetaMask/metamask-extension#1654]
![metaerror](https://user-images.githubusercontent.com/29611528/27401387-ff15f5a0-56ba-11e7-913f-4dcc2cad8d73.png)

Wallet Address: 0x4FdDf7AbF8A8a4D771bD067E28AA185328B83Bd4

Many Thanks

**Comment by tmashuang** [comment]
https://github.com/MetaMask/faq/blob/master/USERS.md#slow-transactions

**Comment by johnmitre** [comment]
I have the same problem and I cant fixed, any suggest

**Comment by tmashuang** [comment]
Try 50+ Gwei gas price.
