### ISSUE TITLE
Get `eth-lattice-keyring` / Gridplus team to update `@ethereumjs/tx` & `@ethereumjs/common` to latest or atleast add `^` to enable dedupe

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#16542]
Ultimately we want to make sure that the subdependency `@etherumjs/util` is updated to `v8.0.0` or higher.

**Comment by danjm** [comment]
closing in favour of https://github.com/metamask/metamask-extension/issues/18030
