### ISSUE TITLE
Update `@ethereumjs/common` to `v3.0.1` or higher

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#16558]
Update in the following packages:

- [ ] "@metamask/controllers/@ethereumjs/common" 

- [ ] "@metamask/smart-transactions-controller/@metamask/controllers/@ethereumjs/common"
- [ ] "@ethereumjs/tx/@ethereumjs/common"
- [ ] "@metamask/rpc-methods/@metamask/controllers/@ethereumjs/common"

- [ ]  "@metamask/snap-controllers/@metamask/controllers/@ethereumjs/common"

This will remove 647kb of `genesisStates` no longer included in package bundle. As well as replace `ethereumjs-util` with `@ethereumjs/util` for the ultimate goal of updating `ethereum-cryptography` from v0.1.3 to v1.1.2 and thereby update `secp256k1` implementation to noble implementation.

**Comment by paulmillr** [comment]
@adonesky1 do you know if elliptic is no longer used to sign transactions? It's hard to say judging from the dependency tree. Seems like the noble switch had been done?
