### ISSUE TITLE
[Bug]: [MV3] Terminating the service worker and opening the popup breaks MM

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16554]
### Describe the bug

**Problem**: after terminating the service worker, if I try to use the MM popup again, it stays loading indefinitely and I see the errors
- `Attempting to use a disconnected port object`
- `PortDuplexStream - disconnected`

https://user-images.githubusercontent.com/54408225/202414029-95d54694-e625-4a51-b8ff-015b729f8f93.mp4

### Steps to reproduce

1. Unlock MM
2. Open MM popup
3. Terminate service worker
4. Try to interact with the popup again -- ~MM stays loading indefinitely~ and errors appear on the console

### Version

https://github.com/MetaMask/metamask-extension/pull/15558

### Browser

Chrome

### Operating system

Linux

**Comment by digiwand** [comment]
I am unable to reproduce this issue. @seaona are you still able to produce this issue on #15558?

**Comment by seaona** [comment]
@digiwand I am still able to reproduce this on develop. I've added a clarification on the repro steps. Let me know if this helps!

**Comment by seaona** [comment]
After discussing with @digiwand and investigating further, we decide to close the issue for 2 reasons:
- The UI breaking behaviour is not happening anymore
- The error of `PortDuplexStream - disconnected` only happens if trying to open the popup right after terminating the service worker and there is no indicator that this causes any functional effect
