### ISSUE TITLE
Remove `ethereumjs/common` genesisStates files

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#16560]
647kb to remove

Make sure we don't use these or use anything from this package that relies on these JSON files:
https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/blockchain/src/genesisStates

Possibly wrap @ethereumjs/common and remove these files and force resolve to the wrapper

**Comment by adonesky1** [comment]
Hey @cryptodev-2s did you have a PR open for this?

**Comment by FrederikBolding** [comment]
@adonesky1 Seems like this will be solved automatically with this: https://github.com/MetaMask/metamask-extension/issues/16558

Since the genesis states aren't part of the common package anymore.

**Comment by adonesky1** [comment]
@FrederikBolding yes you appear to be correct! Closing this in favor of #16558
