### ISSUE TITLE
Replace `@eth-optimism/contracts` package with local instantiation of gas price oracle contract.

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#16565]
Previous discussion with optimism team led to this now closed PR: https://github.com/ethereum-optimism/optimism/pull/3514

Ask them to complete work on that.

Plus modify entry point to allow us to use package without the unneeded `contracts` (289 kb)

**Comment by FrederikBolding** [comment]
I don't have the complete context for this, but since we only require the address and the ABI, both of which I assume to be unlikely to change - do we even need a module?`

Proposed basic implementation with no dependencies:
```
import buildUnserializedTransaction from './buildUnserializedTransaction';

const ORACLE_ADDRESS = '0x420000000000000000000000000000000000000F';
// Snippet of the ABI that we need
const ORACLE_ABI = [{ "inputs": [{ "internalType": "bytes", "name": "_data", "type": "bytes" }], "name": "getL1Fee", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }]

function buildOVMGasPriceOracleContract(eth) {
  return eth.contract(ORACLE_ABI).at(ORACLE_ADDRESS);
}

export default async function fetchEstimatedL1Fee(eth, txMeta) {
  const contract = buildOVMGasPriceOracleContract(eth);
  const serializedTransaction =
    buildUnserializedTransaction(txMeta).serialize();
  const result = await contract.getL1Fee(serializedTransaction);
  return result?.[0]?.toString(16);
}
```

**Comment by adonesky1** [comment]
@FrederikBolding we don't need the full ABI, just the part containing the method we call?

**Comment by FrederikBolding** [comment]
> @FrederikBolding we don't need the full ABI, just the part containing the method we call? I guess that makes sense, just haven't ever tried it... 😅

Yeah, we just need the ABI for the functions we call. Which in this case is just 1 function.

We could add the entire ABI if that seems more sustainable for the future - no strong opinion.
