### ISSUE TITLE
Investigate whether `babel-runtime` should be a dep (and included in the bundle)

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/metamask-extension#16562]
Currently `babel-runtime` is a direct dep of several controllers in `@metamask/controllers`

lets figure out whether this is a mistake and it can be made a devDep and removed from the bundle.

**Comment by mikesposito** [comment]
Closed in favor of [#16719](https://github.com/MetaMask/metamask-extension/issues/16719)
