### ISSUE TITLE
Replace contract with a different word that applies for both EOAs and contracts

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16587]
## Background 
Token allowances can be granted to any address (contracts and accounts (EOAs)) and we don't have an accurate method to identifying wether an address is a contract or EOA, so we should refer to those address using a more general world that applies to both cases. Right now we are always calling it contracts even if the spender is actually an EOA.
This applies for mobile as well.

## Brainstorm
Possible words to use (just kicking off the brainstorm):
- address
- spender
- third party
- stakeholder

Update: we should use third party

## Screenshots
Below are some screenshots of places where we referring to the addresses as contracts:
1. Ps: here Token contract should continue as Token contract
<img width="364" alt="Screenshot 2023-02-23 at 10 58 49" src="https://user-images.githubusercontent.com/34968356/220929118-24c0c42f-734e-4b9f-a692-038c9fc88eb0.png">

2.
<img width="364" alt="Screenshot 2023-02-23 at 10 58 40" src="https://user-images.githubusercontent.com/34968356/220929322-3bbe7dc0-4c5b-4c60-b4e5-1a6c5141df3c.png">

3.
<img width="365" alt="Screenshot 2023-02-23 at 10 58 23" src="https://user-images.githubusercontent.com/34968356/220929420-1c9980f0-6106-47b1-a844-0ba3b012fe61.png">

4.
<img width="364" alt="Screenshot 2023-02-23 at 10 58 13" src="https://user-images.githubusercontent.com/34968356/220929690-3d545be6-5b0b-45a7-8e8a-361c933f853a.png">

**Comment by coreyjanssen** [comment]
After reviewing the screenshots and considering the context, I think `third party ` is the most accurate and user-friendly option for replacing `contract`.

**Comment by bschorchit** [comment]
Thank you, Corey!

**Comment by dzfjz** [comment]
Verified by QA
