### ISSUE TITLE
Investigate whether to remove `ethereumjs-abi` in favor of `@metamask/abi-utils`

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/metamask-extension#16581]
The `ethereumjs-abi` includes `ethereumjs-util` in dependencies. We should see if we can substitute it with our own package `@metamask/abi-utils` across the dep tree

![Schermata 2022-11-18 alle 10.58.44.png](https://images.zenhubusercontent.com/631efe4c85d95ad5cc38a75b/ed5a7657-2b2b-44bf-8103-1fe052926d73)

**Comment by adonesky1** [comment]
Ok we definitely need to replace ethereumjs-abi with `@metamask/abi-utils` otherwise we can't remove old `ethereumjs-utils` which is required to fully replace `secp256k1` implementation with the noble implemenations.

**Comment by mikesposito** [comment]
> Ok we definitely need to replace ethereumjs-abi with `@metamask/abi-utils` otherwise we can't remove old (pre v8) `ethereumjs-utils` which is required to fully replace `secp256k1` implementation with the noble implemenations.

Besides the direct dependency in `metamask-crx`, this goes away after updating @metamask/eth-sig-util to latest (#15906)

**Comment by adonesky1** [comment]
Going to create a ticket to replace `ethereumjs-abi` with `@metamask/abi-utils` in `metamask-crx` since the other cases are covered by [an existing ticket](https://github.com/MetaMask/metamask-extension/issues/15906).
