### ISSUE TITLE
Feature - Add remove account button

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#1658]
@flyswatter 
I pretty much figured out how to add such button with all necessary hooks. 
I would add a button in Account-list-item.js view, then add action on the UI that would dispatch to background by passing `identity.address` and then need to figure out how to properly destoy the item.

My question is: which branch should I use?
Is there something similar going on in development? 
How do you enable Redux/React chrome debugging while in development for better Inspection for elements and watching for Redux store

**Comment by Zanibas** [comment]
It's fairly safe to use the master branch to make your changes. There currently isn't a long-running `dev` branch, so you should be able to work off of master and then make a PR from there! Fair warning though--right now we have set up our CI such that it does not run on outside PRs, so we'd have to close and resubmit under one of our names to get it merged in.

For Redux/React chrome debugging, if you run the `npm run dev` command, you should be able to see whenever an action is executed on the UI side and what effect it has on the state tree.

**Comment by rstormsf** [comment]
thanks! @Zanibas

**Comment by karelstriegel** [comment]
👍 +1 for this request

**Comment by nieldlr** [comment]
Just a friendly +1 on this feature. Is anyone currently working on this one?

cc @rstormsf @Zanibas @kumavis

**Comment by 21xhipster** [comment]
Simple, but very needed feature to start love using Metamask. Really. I do have 10+ accounts that I don't need anymore

**Comment by danfinlay** [comment]
Seed phrases always generate the same accounts in the same order, and so there is not really a concept of deleting accounts. We could hide them, though.

Can someone who wants this feature describe what you think would ideally happen when restoring your vault from your seed phrase after deleting accounts? We would not have the data for which accounts you had "deleted", so you would still re-generate the accounts in the same order.

**Comment by rstormsf** [comment]
I guess hide feature should be there. When restoring all accounts should be
there

**Comment by nieldlr** [comment]
@danfinlay in my use case I want to delete "loose" addresses, where I imported my own private key. So for generating accounts again from passphrase that's all smooth, it's more about removing unused "loose" addresess for me.

**Comment by danfinlay** [comment]
@nieldlr That's an easy one to satisfy, I'll open that as its own issue because it's so trivial. #2638

If we add "hide account", we probably need a way to reveal hidden accounts, so that's another reason seed phrase hiding is more complicated than it sounds.

I agree it's a valuable tool, because long term, people will probably go through many accounts, but we still need to refine how we identify "spent" accounts, and only re-generate accounts that the user still cares about.

**Comment by wordsandstuff** [comment]
I have an account that I dont want to have in metamask. I want to remove it so its not there and accessible. Reasonable ? Ideally I would like a session based account option that allows me to import an account and once the session is closed the account is removed. But a remove button will suffice until then.

**Comment by whyamiroot** [comment]
@rstormsf Hello, are you working on this feature? Would really love to see it, I'm tired of scrolling down loose accounts which I don't need any more

**Comment by danfinlay** [comment]
Raising priority on this because a lot of developers want it.

**Comment by freedomfryz** [comment]
Question about Imported accounts... Once an ether wallet is imported, is it retrieveable with the metamask wallet seed? I have an imported wallet I'd like removed from Metamask, but if restoring from seed restores that wallet, no dice...

**Comment by danfinlay** [comment]
@freedomfryz  For usage questions, please email support@metamask.io

The answer to your question: clicking "add account" re-generates accounts in the same order, but we currently still keep previous account nicknames, which can be confusing. We are fixing this soon in #3566.

I'm closing this issue because our new UI (Beta) has this feature already implemented, we don't plan to add it to the "old" UI.

**Comment by styledress** [comment]
Buy clubbing <a href="http://www.styledress.co.uk">sexy dresses online UK</a> at styledress.co.uk. We offer sexy club <a 

href="https://www.styledress.co.uk/maxi-dresses.html">maxi dresses online</a> for every occasion. Order your sexy clubbing dress today and avail 10% .

**Comment by 1blockologist** [comment]
Where is it implemented in the beta?  I just switched over to it and don't see it obviously in the mini popup GUI or in the web GUI

**Comment by danfinlay** [comment]
Oh I'm sorry, we added `remove token` to the new UI. We have not added `remove account` to the new UI.

**Comment by MoMannn** [comment]
+1

**Comment by bdresser** [comment]
@brunobar79's PR for Trezor support (#4625) also includes the ability to remove loose/imported accounts (as described in #2638) in the new UI. 

Leaving this open to discuss more sophisticated management of HD accounts, but lowering priority. As Dan mentions above, there are some UX issues to sort out and thoughts are welcome.

**Comment by bdresser** [comment]
Removing loose accounts was added in https://github.com/MetaMask/metamask-extension/pull/4625

More specific feature story for removing / archiving HD accounts is filed here #5078

**Comment by IHLight** [comment]
Remove accountand private keys from browser ?

**Comment by second2falcon** [comment]
Is there a remove/hide account for accounts NOT imported during the setup of MetaMask planned/coming? I have imported my Trezor Wallet but now I am here with 2 accounts.
