### ISSUE TITLE
Add Celo to the popular network feature

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16588]
### Background
Celo should be included in MetaMask's popular network list. [Slack thread](https://consensys.slack.com/archives/GV90KPED9/p1668610116178929)

### Resources
[Figma file for the add popular network feature](https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1697%3A17290)

Network info:
- chain ID: 42220
- rpc url: https://celo-mainnet.infura.io/v3/<API-KEY>
- network name: Celo Mainnet
- ticker: Celo
- block explorer url: https://celoscan.io
- icon: [file in drive](https://drive.google.com/file/d/1-hBewY9d2iTGDFa81QlLULU8YNwhXREy/view?usp=share_link)

### Acceptance criterias
- Users are able to add Celo network through the add popular network feature;
- No tooltip is shown for Celo in the network list screen of the 'add popular networks' feature;
- The network uses Infura's endpoint as we always want to use rpc endpoints that we know comply to our privacy policy.
- The Infura key should not be revealed to users when users review the details for the Celo network in Settings > Networks.

**Comment by Nanimustshine** [comment]
> ### Background
> Celo should be included in MetaMask's popular network list. [Slack thread](https://consensys.slack.com/archives/GV90KPED9/p1668610116178929)
> 
> ### Resources
> [Figma file for the add popular network feature](https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=1697%3A17290)
> 
> Network info:
> - chain ID: 42220
> - rpc url: https://celo-mainnet.infura.io/v3/<API-KEY>
> - network name: Celo Mainnet
> - ticker: Celo
> - block explorer url: https://celoscan.io
> - icon: [file in drive](https://drive.google.com/file/d/1-hBewY9d2iTGDFa81QlLULU8YNwhXREy/view?usp=share_link)
> 
> ### Acceptance criterias
> - Users are able to add Celo network through the add popular network feature;
> - No tooltip is shown for Celo in the network list screen of the 'add popular networks' feature;
> - The network uses Infura's endpoint as we always want to use rpc endpoints that we know comply to our privacy policy.
> - The Infura key should not be revealed to users when users review the details for the Celo network in Settings > Networks. 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
