### ISSUE TITLE
Ropsten faucet down?

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1659]
We have a user reporting a ropsten faucet failure.  Checkout & fix.

**Comment by shayanb** [comment]
Any updates? It seems like it might be still using the attacked ropsten network and not on the revived fork.

**Comment by Manidos** [comment]
It seems like there are no working Ropsten faucets at all. It would be nice to have at least one. I hope you have time and energy to get it up and running. Meanwile, you can ask for Ether [here ](https://www.reddit.com/r/ethdev/comments/61zdn8/if_you_need_some_ropsten_testnet_ethers/?utm_content=full_comments&utm_medium=user&utm_source=reddit&utm_name=frontpage).

**Comment by kumavis** [comment]
kept restarting it and it would go bad again
lazy fix: it auto restarts every ten minutes
