### ISSUE TITLE
[e2e] Custom RPC tests failures on MV3 build

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16598]
### Describe the bug

**Problem**: Custom RPC test are failing intermittently for mv3 build with the error:
`     ElementClickInterceptedError: element click intercepted: Element <div data-testid="network-display" class="network-display network-display--clickable chip chip--with-left-icon chip--with-right-icon chip--border-color-border-default chip--background-color-undefined chip--max-content" role="button" tabindex="0">...</div> is not clickable at point (864, 37). Other element would receive the click: <div class="loading-overlay">...</div>`

![image](https://user-images.githubusercontent.com/54408225/203031611-f3cb48ec-0a5b-4f41-91ed-f1672b8e9ada.png)

See failures:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/31077/workflows/bf722b93-e4b1-4ab8-b362-0bb43bbbdbfc/jobs/811230/artifacts

### Steps to reproduce

1. Build mv3 test `yarn build:test:mv3`
2. Run e2e test `yarn test:e2e:single test/e2e/tests/custom-rpc-history.spec.js --browser=chrome` 

### Version

develop

### Browser

Chrome

### Operating system

Linux

**Comment by Nanimustshine** [comment]
> ### Describe the bug
> 
> **Problem**: Custom RPC test are failing intermittently for mv3 build with the error:
> `     ElementClickInterceptedError: element click intercepted: Element <div data-testid="network-display" class="network-display network-display--clickable chip chip--with-left-icon chip--with-right-icon chip--border-color-border-default chip--background-color-undefined chip--max-content" role="button" tabindex="0">...</div> is not clickable at point (864, 37). Other element would receive the click: <div class="loading-overlay">...</div>`
> 
> ![image](https://user-images.githubusercontent.com/54408225/203031611-f3cb48ec-0a5b-4f41-91ed-f1672b8e9ada.png)
> 
> See failures:
> https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/31077/workflows/bf722b93-e4b1-4ab8-b362-0bb43bbbdbfc/jobs/811230/artifacts
> 
> ### Steps to reproduce
> 
> 1. Build mv3 test `yarn build:test:mv3`
> 2. Run e2e test `yarn test:e2e:single test/e2e/tests/custom-rpc-history.spec.js --browser=chrome` 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> develop
> 
> ### Build type
> 
> _No response_
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
