### ISSUE TITLE
[Bug]:  Cant send coins on the ethereum fork?

### ISSUE THREAD

**Issue by Toni-d-e-v** [MetaMask/metamask-extension#16593]
### Describe the bug

I have made ethereum fork and my custom wallet works, metamask mobile works, but ethereum extension does not.
When I try to send coins it wont let me!
![image](https://i.stack.imgur.com/IzHTL.png)
My custom rpc: https://rpc.avescoin.io
My network uses smaller minimum gas ( 11k instead of 21k ) but other wallets work!

### Steps to reproduce

1. Go to https://avescan.io 
2. Add network button
3.  Ask me to send you 2 AVS ( we are still on test net ! )
4. See for your self

### Error messages or log output

```shell
sentry-install.js:1          GET https://gas-api.metaswap.codefi.network/networks/33333
Only error
```

### Version

10.22.1

### Browser

Firefox

### Operating system

Linux

### Additional context

I have same problem on all my devices that uses chrome and firefox.

**Comment by Toni-d-e-v** [comment]
Wired thing is that erc20 tokens work and smart contract transactions :)

**Comment by Nanimustshine** [comment]
> ### Describe the bug
> 
> I have made ethereum fork and my custom wallet works, metamask mobile works, but ethereum extension does not.
> When I try to send coins it wont let me!
> ![image](https://i.stack.imgur.com/IzHTL.png)
> My custom rpc: https://rpc.avescoin.io
> My network uses smaller minimum gas ( 11k instead of 21k ) but other wallets work!
> 
> 
> ### Steps to reproduce
> 
> 1. Go to https://avescan.io 
> 2. Add network button
> 3.  Ask me to send you 2 AVS ( we are still on test net ! )
> 4. See for your self
> 
> 
> ### Error messages or log output
> 
> ```shell
> sentry-install.js:1          GET https://gas-api.metaswap.codefi.network/networks/33333
> Only error
> ```
> 
> 
> ### Version
> 
> 10.22.1
> 
> ### Build type
> 
> _No response_
> 
> ### Browser
> 
> Firefox
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> I have same problem on all my devices that uses chrome and firefox.

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by danjm** [comment]
@Toni-d-e-v I'm an engineer on the MetaMask team. Can you send a bit of the network currency to `0x5485f894f5EfA9262f46CbDA1261395550d0BC01` so that I can test and debug?

**Comment by backmen** [comment]
I sent you now. Best regards

**Comment by backmen** [comment]
When will Metamask , unock minimum gas fee on desktop extension? There is plenty Ethereum fork projects which have lower gas fee?

**Comment by backmen** [comment]
@danjm Can you help us, please?

**Comment by Toni-d-e-v** [comment]
Any updates?

**Comment by Toni-d-e-v** [comment]
@danjm 
Hi, this pull request is preventing coins from being sent from aves network as fee on aves is 11k insted of 21k
https://github.com/MetaMask/metamask-extension/pull/6625

**Comment by backmen** [comment]
Sorry, but its not normal error, you disable several projects with that update which are uselles..Why you not unlock min gas fee like you do in mobile version? @danjm Maybe metamask want to keep high gas price charges for some atractive coins?

**Comment by salimtb** [comment]
hey @Toni-d-e-v ,
can you pls send me some tokens for test to the following address:
`0x54e0019Ac5c1CfC859c6F486cE7CB2B9BFbf059A`

**Comment by salimtb** [comment]
hey @Toni-d-e-v ,
the fact that the gas limit is set to 21.000 is not related to keep high gas price charges for some tokens.
the gas limit for an Ether (ETH) transaction would need to be at least 21,000 for it to be considered a regular transaction.
according to the Ethereum White Paper , any transaction has a 'base fee' of 21,000 gas
