### ISSUE TITLE
Update `eth-json-rpc-filters` > `eth-json-rpc-middleware` to `^9.0.0`

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/metamask-extension#16608]

**Comment by Nanimustshine** [comment]
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
