### ISSUE TITLE
Border radius SM is missing from Box component

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#16607]
### Description
Previous update to the `borderRadius` prop missed the size `sm` I think it needs to be updated to the below

```
ui/css/design-system/attributes.scss

$border-radius: (
  xs: 2px,
  sm: 4px, // missing
  md: 6px,
  lg: 8px,
  xl: 12px,
  full: 50%,
  pill: 9999px,
  none: 0,
);
```

## Screenshots
<img width="1440" alt="Screen Shot 2022-11-21 at 8 38 09 AM" src="https://user-images.githubusercontent.com/8112138/203110798-f2891e22-a1a8-4777-bafd-15714a1bcbed.png">

**Comment by Nanimustshine** [comment]
> ### Description
> Previous update to the `borderRadius` prop missed the size `sm` I think it needs to be updated to the below
> 
> ```
> ui/css/design-system/attributes.scss
> 
> $border-radius: (
>   xs: 2px,
>   sm: 4px, // missing
>   md: 6px,
>   lg: 8px,
>   xl: 12px,
>   full: 50%,
>   pill: 9999px,
>   none: 0,
> );
> ```
> 
> ## Screenshots
> <img width="1440" alt="Screen Shot 2022-11-21 at 8 38 09 AM" src="https://user-images.githubusercontent.com/8112138/203110798-f2891e22-a1a8-4777-bafd-15714a1bcbed.png">
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
