### ISSUE TITLE
[e2e] Add Account flaky test on MV3 build

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16604]
### Describe the bug

**Problem**: on MV3 build, we have a flaky test on Add Account, which throws the following error

![image](https://user-images.githubusercontent.com/54408225/203067995-eeb032fc-7b90-4039-8c11-ee90eaa5b042.png)

### Steps to reproduce

1. Build the mv3 test environment `yarn build:test:mv3`
2. Run e2e flaky test `yarn test:e2e:single test/e2e/tests/add-account.spec.js --browser=chrome `

### Version

develop

### Browser

Chrome

### Operating system

Linux

**Comment by Nanimustshine** [comment]
> ### Describe the bug
> 
> **Problem**: on MV3 build, we have a flaky test on Add Account, which throws the following error
> 
> ![image](https://user-images.githubusercontent.com/54408225/203067995-eeb032fc-7b90-4039-8c11-ee90eaa5b042.png)
> 
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Build the mv3 test environment `yarn build:test:mv3`
> 2. Run e2e flaky test `yarn test:e2e:single test/e2e/tests/add-account.spec.js --browser=chrome `
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> develop
> 
> ### Build type
> 
> _No response_
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
