### ISSUE TITLE
[Bug]: ERC20 token with decimals=0 lead to infinite loading when clicking on send

### ISSUE THREAD

**Issue by MaikVogt** [MetaMask/metamask-extension#16601]
### Describe the bug

When clicking on send of an ERC20 token that has decimals=0 there will be an infinite loading spinner.

I double checked this behavior by deploying two minimal ERC20 tokens that only differ in decimals

Decimals=0 fails
[Contract Address 0x177d4311Afc0a58D4A7Cdb62aB8Ec4Be3dBF11B2 | PolygonScan](https://mumbai.polygonscan.com/address/0x177d4311Afc0a58D4A7Cdb62aB8Ec4Be3dBF11B2)

Decimals=8 works
[Contract Address 0xD49175eC8518575274a08535D1eF2F7Eb281F6fE | PolygonScan](https://mumbai.polygonscan.com/address/0xD49175eC8518575274a08535D1eF2F7Eb281F6fE)

### Steps to reproduce

1. create an ERC20 token with decimals=0
2. mint tokens to your wallet
3. import your custom token
4. click on send

### Error messages or log output

```shell
None in developer console
```

### Version

10.22.1

### Browser

Chrome

### Operating system

Linux

**Comment by Nanimustshine** [comment]
> ### Describe the bug
> 
> When clicking on send of an ERC20 token that has decimals=0 there will be an infinite loading spinner.
> 
> I double checked this behavior by deploying two minimal ERC20 tokens that only differ in decimals
> 
> Decimals=0 fails
> [Contract Address 0x177d4311Afc0a58D4A7Cdb62aB8Ec4Be3dBF11B2 | PolygonScan](https://mumbai.polygonscan.com/address/0x177d4311Afc0a58D4A7Cdb62aB8Ec4Be3dBF11B2)
> 
> Decimals=8 works
> [Contract Address 0xD49175eC8518575274a08535D1eF2F7Eb281F6fE | PolygonScan](https://mumbai.polygonscan.com/address/0xD49175eC8518575274a08535D1eF2F7Eb281F6fE)
> 
> ### Steps to reproduce
> 
> 1. create an ERC20 token with decimals=0
> 2. mint tokens to your wallet
> 3. import your custom token
> 4. click on send
> 
> ### Error messages or log output
> 
> ```shell
> None in developer console
> ```
> 
> 
> ### Version
> 
> 10.22.1
> 
> ### Build type
> 
> _No response_
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
This will be fixed by https://github.com/MetaMask/metamask-extension/pull/16547

**Comment by bschorchit** [comment]
Thank you for your report, @MaikVogt ! I'll close this issue so we track it on one single place here https://github.com/MetaMask/metamask-extension/issues/16596 . 
This will be fixed by https://github.com/MetaMask/metamask-extension/pull/16685 which will be release in version 10.23.
