### ISSUE TITLE
Add unit test and story to new components

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16609]
## Background
https://github.com/MetaMask/metamask-extension/pull/16018#pullrequestreview-1174267059

**Comment by Nanimustshine** [comment]
> ## Background
> https://github.com/MetaMask/metamask-extension/pull/16018#pullrequestreview-1174267059

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
