### ISSUE TITLE
Improve our phishing warning page

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16602]
## Background
The phishing warning page is the page users are displayed when they try to visit a malicious site that is on our phishing list. A new [design](https://www.figma.com/file/MKJnCnI8Xi2EVcRCNAHwOu/Improve-Phishing-Warning-Page?node-id=2%3A9&t=P2jLXBxUvqxA3A7d-0) for this page was created and a PR to implement it was started in phishing-warning repo (https://github.com/MetaMask/phishing-warning/pull/40), but not finalized. We should help get the PR (or a new one that implements to new design) ready for review.

Additionally, we should add some metrics to this page to help us understand the frequency of occurrence and usage of this phishing warning. We'll add 2 new events: `Phishing Page Displayed` and `External Link Clicked`. 

`Phishing Page Displayed` has the following properties:
> `url`: url that triggered the phishing warning page to be displayed

`External Link Clicked` has the following properties:
> `link_type`: phishing_detection
> `url`: url of the link the user clicked
> `location`: phishing_warning_page
> `category`: Navigation

## Acceptance criteria
1. [This PR](https://github.com/MetaMask/phishing-warning/pull/40) (or a new PR that implements the same new design for the phishing warning page) is ready for review.
2. Users can read the attribution to who flagged the domain, probably passed to that page with a query string.
3. For users who want to ignore the warning message, move them only to URIs with a specific protocol.
4. For users that have opted in for MetaMetrics, we fire an `Phishing Page Displayed` event whenever this phishing-warning page is loaded.
5. For users that have opted in for MetaMetrics, we fire an `External Link Clicked` event whenever the user clicks on one of the links in the phishing-warning page.
6. No events are fired for users that have opted out of MetaMetrics.

## Steps to reproduce
1. Go to a reported bad domain (some examples [here](https://github.com/MetaMask/eth-phishing-detect/pull/9813/files)) - be careful as those have been reported as malicious sites so you don't want to actually connect your MetaMask wallet or perform any transaction or signature on those websites
2. Notice the MetaMask phishing-warning page being displayed

**Comment by Nanimustshine** [comment]
> ## Background
> The phishing warning page is the page users are displayed when they try to visit a malicious site that is on our phishing list. A new [design](https://www.figma.com/file/MKJnCnI8Xi2EVcRCNAHwOu/Improve-Phishing-Warning-Page?node-id=2%3A9&t=P2jLXBxUvqxA3A7d-0) for this page was created and a PR to implement it was started in phishing-warning repo (https://github.com/MetaMask/phishing-warning/pull/40), but not finalized. We should help get the PR (or a new one that implements to new design) ready for review.
> 
> Additionally, we should add some metrics to this page to help us understand the frequency of occurrence and usage of this phishing warning. We'll add 2 new events: `TBD` and `External Link Clicked`. 
> 
> `TBD` has the following properties:
> > `url`: url that triggered the phishing warning page to be displayed
> 
> 
> `External Link Clicked` has the following properties:
> > `link_type`: learn_more | report_wrong_detection | continue_to_site | back_to_safety
> > `url`: url of the link the user clicked
> > `location`: phishing_warning_page
> > `chain_id`: chain id in hex
> > `category`: Navigation
> 
> ## Acceptance criteria
> 1. [This PR](https://github.com/MetaMask/phishing-warning/pull/40) (or a new PR that implements the same new design for the phishing warning page) is ready for review.
> 2. Users can read the attribution to who flagged the domain, probably passed to that page with a query string.
> 3. For users who want to ignore the warning message, move them only to URIs with a specific protocol.
> 4. For users that have opted in for MetaMetrics, we fire an `TBD` event whenever this phishing-warning page is loaded.
> 5. For users that have opted in for MetaMetrics, we fire an `External Link Clicked` event whenever the user clicks on one of the links in the phishing-warning page.
> 6. No events are fired for users that have opted out of MetaMetrics.
> 
> ## Steps to reproduce
> 1. Go to a reported bad domain (https://cryptoscamdb.org/scams)
> 2. Show the phishing-warning page
> 3. On the phishing-warning page, click on "Learn more"
> 4. On the phishing-warning page, click on "report a detection problem"
> 5. On the phishing-warning page, click on "continue to the site"
> 6. On the phishing-warning page, click on "Back to safety"

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
`External Link Clicked` is not part of this issues' scope anymore. I'll move it to a new issue.

**Comment by ElvirCe** [comment]
The Metrics part will be handled in ticket #17453

**Comment by bschorchit** [comment]
Closing as this https://github.com/MetaMask/phishing-warning/pull/52 has been merged
