### ISSUE TITLE
Update Chrome Beta Store with updated logo and copy

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#16614]
## Background 
The [Beta store page](https://chrome.google.com/webstore/detail/metamask-beta/pbbkamfgmaedccnfkmjcofcecjhfgldn) was created about a year ago, but hasn't been made public. It doesn't have any content, and is currently using an old logo which could cause confusion to users.
![Screenshot 2022-11-21 at 2.46.42 PM.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/96409ac7-d4b7-4b14-bbbc-93396e58a248)

## Proposed changes

- [ ] Update logo with the most recent [Beta logo ](https://www.figma.com/file/qn0DJn2Mfw036gdt2aYuZB/MV3-Beta?node-id=3352%3A4363&t=OhivTnuB7THBOa6w-0)
- [ ] Change `MetaMask BETA` to `MetaMask Beta`
- [ ] Create Beta page description with the following copy:
```
    Welcome to MetaMask Beta
Trusted by millions, MetaMask is a secure wallet making the world of web3 accessible to all.
    
    Beta Version Disclaimer
    
    This version allows you to test upcoming features before they’re released, which helps make MetaMask even better. As with all beta versions, there may be an increased risk of bugs. MetaMask Beta is subject to our standard Terms as well as our supplemental Beta Terms. 
    
    By proceeding, you accept and acknowledge these risks, our Terms, and Beta Terms.
```
Beta Terms / supplemental Beta Terms [link](https://consensys.net/beta-terms)
Standard Terms / Terms [link](https://consensys.net/terms-of-use/)

**Comment by kevinghim** [comment]
@coreyjanssen I used the same copy on the Chrome beta store page as the first screen on the [beta onboarding flow](https://www.figma.com/file/qn0DJn2Mfw036gdt2aYuZB/MV3-Beta?node-id=3735%3A7545&t=OhivTnuB7THBOa6w-0). Would that be ok?

**Comment by Nanimustshine** [comment]
> ## Background 
> The [Beta store page](https://chrome.google.com/webstore/detail/metamask-beta/pbbkamfgmaedccnfkmjcofcecjhfgldn) was created about a year ago, but hasn't been made public. It doesn't have any content, and is currently using an old logo which could cause confusion to users.
> ![Screenshot 2022-11-21 at 2.46.42 PM.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/96409ac7-d4b7-4b14-bbbc-93396e58a248)
> 
> ## Proposed changes
> 
> - [ ] Update logo with the most recent [Beta logo ](https://www.figma.com/file/qn0DJn2Mfw036gdt2aYuZB/MV3-Beta?node-id=3352%3A4363&t=OhivTnuB7THBOa6w-0)
> - [ ] Change `MetaMask BETA` to `MetaMask Beta`
> - [ ] Create Beta page description with the following copy:
> ```
>     Welcome to MetaMask Beta
> Trusted by millions, MetaMask is a secure wallet making the world of web3 accessible to all.
>     
>     Beta Version Disclaimer
>     
>     This version allows you to test upcoming features before they’re released, which helps make MetaMask even better. As with all beta versions, there may be an increased risk of bugs. MetaMask Beta is subject to our standard Terms as well as our supplemental Beta Terms. 
>     
>     By proceeding, you accept and acknowledge these risks, our Terms, and Beta Terms.
> ```
> Beta Terms / supplemental Beta Terms [link](https://consensys.net/beta-terms)
> Standard Terms / Terms [link](https://consensys.net/terms-of-use/)

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Gudahtt** [comment]
The text we used on the placeholder Beta store description is:

>This is the beta distribution of the MetaMask extension. Use this version to test upcoming features before they’re released. Your use and feedback helps us build the best version of MetaMask possible. As a Beta, there may be an increased risk of bugs. Please do not use this version unless you are willing to accept that risk.
>
>You can find the main / production version of MetaMask here: https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

Then we continued with the main extension store description from there.

Should we still include a link to the main extension? I was unsure about replacing that, otherwise the suggested copy looks good to me.

**Comment by kevinghim** [comment]
@Gudahtt I like the link to the production version. I've combined the place holder description with the version used on onboarding. Let me know what you think.

> Welcome to MetaMask Beta
> Trusted by millions, MetaMask is a secure wallet making the world of web3 accessible to all.
> 
>   
> This is the beta distribution of the MetaMask extension. Use this version to test upcoming features before they’re released. Your use and feedback helps us build the best version of MetaMask possible. As a Beta, there may be an increased risk of bugs. Please do not use this version unless you are willing to accept that risk.
> 
> MetaMask Beta is subject to our standard [Terms](https://consensys.net/terms-of-use/) as well as our supplemental [Beta Terms](https://consensys.net/beta-terms).  By proceeding, you accept and acknowledge these risks, our [Terms](https://consensys.net/terms-of-use/), and [Beta Terms](https://consensys.net/beta-terms).
> 
> You can find the main / production version of MetaMask here: https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

**Comment by kevinghim** [comment]
@mapachurro would you be able to do a quick review with the MetaMask beta store page copy above in Corey's absence?

**Comment by Gudahtt** [comment]
It looks like we can't embed links in this description. Would something like this work instead?

>Welcome to MetaMask Beta
>Trusted by millions, MetaMask is a secure wallet making the world of web3 accessible to all.
>
>This is the beta distribution of the MetaMask extension. Use this version to test upcoming features before they’re released. Your use and feedback helps us build the best version of MetaMask possible. As a Beta, there may be an increased risk of bugs. Please do not use this version unless you are willing to accept that risk.
>
>MetaMask Beta is subject to our standard Terms (https://consensys.net/terms-of-use/) as well as our supplemental Beta Terms (https://consensys.net/beta-terms). By proceeding, you accept and acknowledge these risks, our Terms, and our Beta Terms.
>
>You can find the main / production version of MetaMask here: https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

**Comment by Gudahtt** [comment]
^ I've used that description for now. We can adjusted it prior to the public beta if we still want to make changes. I'll leave this issue open for now, in case we get more feedback.

**Comment by hilvmason** [comment]
@Gudahtt looks like this is live! Good to close this issue? Thanks!

**Comment by Gudahtt** [comment]
This has been completed; the new beta description and logo are live.
