### ISSUE TITLE
[e2e] Setup MV3 specific tests introducing Service Worker re-start 

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16610]

**Comment by Nanimustshine** [comment]
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
