### ISSUE TITLE
Update `eth-json-rpc-filters` Node.js version to `>=14.0.0`

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/metamask-extension#16613]
The `eth-json-rpc-filters` package is still using Node.js v12. 
This makes the update of dep`eth-json-rpc-middleware` to `^9` not possible, as it requires Node.js `>=14.0.0`

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
