### ISSUE TITLE
Fix PropType error in Tag tests

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#16619]
### Description
Fix tag propType issue in unit tests

![Screen Shot 2022-11-21 at 8 26 30 PM](https://user-images.githubusercontent.com/8112138/203221438-8458ff0b-1c4c-4c1a-b008-3eef19a6bce0.png)

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
> ### Description
> Fix tag propType issue in unit tests
> 
> ![Screen Shot 2022-11-21 at 8 26 30 PM](https://user-images.githubusercontent.com/8112138/203221438-8458ff0b-1c4c-4c1a-b008-3eef19a6bce0.png)
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
