### ISSUE TITLE
Remove Confirm and Cancel events

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16617]
## Background
We should remove the `Confirm` and `Cancel` events mentioned [here](https://github.com/MetaMask/metamask-extension/pull/16225#discussion_r1019123767) as they are legacy events that are not used anymore.

## Acceptance Criteria
1. `Confirm` and `Cancel` events are not triggered anymore when signing eth_sign requests

**Comment by Nanimustshine** [comment]
> ## Background
> We should remove the `Confirm` and `Cancel` events mentioned [here](https://github.com/MetaMask/metamask-extension/pull/16225#discussion_r1019123767) as they are legacy events that are not used anymore.
> 
> ## Acceptance Criteria
> 1. `Confirm` and `Cancel` events are not triggered anymore when signing eth_sign requests

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
