### ISSUE TITLE
✨ Make the new Token Allowance flow default to all users

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16623]
## Background
We have released the new token allowance flow under Settings > Experimental first https://github.com/MetaMask/metamask-extension/issues/15367. Once we're comfortable with its performance, we should make it the default experience for all users. 

## Acceptance Criterias
1. The new token allowance flow is default for all users.
2. The `Improved token allowance experience` toggle in Settings > Experimental has been removed.

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
> ## Background
> We have released the new token allowance flow under Settings > Experimental first https://github.com/MetaMask/metamask-extension/issues/15367. Once we're comfortable with its performance, we should make it the default experience for all users. 
> 
> ## Acceptance Criterias
> 1. The new token allowance flow is default for all users.
> 2. The `Improved token allowance experience` toggle in Settings > Experimental has been removed.

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
