### ISSUE TITLE
[Bug]: Impossible to get the image of my token

### ISSUE THREAD

**Issue by imaxE-BISCUS** [MetaMask/metamask-extension#16626]
### Describe the bug

Hi,

I have a problem that I can’t solve for a while now and I hope I can find some help from this great community.

I am working on a project that have create a token (FeelingMeta). In my application I use the wallet_watchAsset function to add my token with a well defined image but my image never appears in the token list. I only have the default image.

What is really surprising with this problem is that the image is well present in other screens of MetaMask and I have no problem on the mobile application. I put you some captures to illustrate my problem.

If you have any ideas where this problem can come from, I’m interested because I’ve tried everything and I don’t have any more solutions for the moment :sweat_smile:
<img width="417" alt="Capture d’écran 2022-11-14 à 10 59 46" src="https://user-images.githubusercontent.com/22661960/203293285-97cb8a36-1570-4bae-a310-e5662a1e7b67.png">
<img width="358" alt="Capture d’écran 2022-11-14 à 10 59 35" src="https://user-images.githubusercontent.com/22661960/203293290-1adcf09e-cb3a-4a71-83eb-05fdf1f588ae.png">
<img width="357" alt="Capture d’écran 2022-11-14 à 10 59 21" src="https://user-images.githubusercontent.com/22661960/203293294-a44c49ac-d243-45fd-9301-10f47b737395.png">
![IMG_2DFDEFBCEF68-1](https://user-images.githubusercontent.com/22661960/203293320-ec90dde9-cc3a-4e8a-87ca-caf404977af8.jpeg)

### Steps to reproduce

1. You need to register to the FeelingMeta ICO (https://dashboard.feelingmeta.io/) which will trigger the addition of the token.

### Version

10.22.1

### Browser

Chrome, Firefox, Brave

### Operating system

Windows, MacOS, Linux

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
> ### Describe the bug
> 
> Hi,
> 
> I have a problem that I can’t solve for a while now and I hope I can find some help from this great community.
> 
> I am working on a project that have create a token (FeelingMeta). In my application I use the wallet_watchAsset function to add my token with a well defined image but my image never appears in the token list. I only have the default image.
> 
> What is really surprising with this problem is that the image is well present in other screens of MetaMask and I have no problem on the mobile application. I put you some captures to illustrate my problem.
> 
> If you have any ideas where this problem can come from, I’m interested because I’ve tried everything and I don’t have any more solutions for the moment :sweat_smile:
> <img width="417" alt="Capture d’écran 2022-11-14 à 10 59 46" src="https://user-images.githubusercontent.com/22661960/203293285-97cb8a36-1570-4bae-a310-e5662a1e7b67.png">
> <img width="358" alt="Capture d’écran 2022-11-14 à 10 59 35" src="https://user-images.githubusercontent.com/22661960/203293290-1adcf09e-cb3a-4a71-83eb-05fdf1f588ae.png">
> <img width="357" alt="Capture d’écran 2022-11-14 à 10 59 21" src="https://user-images.githubusercontent.com/22661960/203293294-a44c49ac-d243-45fd-9301-10f47b737395.png">
> ![IMG_2DFDEFBCEF68-1](https://user-images.githubusercontent.com/22661960/203293320-ec90dde9-cc3a-4e8a-87ca-caf404977af8.jpeg)
> 
> 
> ### Steps to reproduce
> 
> 1. You need to register to the FeelingMeta ICO (https://dashboard.feelingmeta.io/) which will trigger the addition of the token.
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.22.1
> 
> ### Build type
> 
> _No response_
> 
> ### Browser
> 
> Chrome, Firefox, Brave
> 
> ### Operating system
> 
> Windows, MacOS, Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
