### ISSUE TITLE
ERC1155 Tokens Balance

### ISSUE THREAD

**Issue by mhusnainee** [MetaMask/metamask-extension#16622]
### Describe the bug

MetaMask shows zero (incorrect) balance of ERC1155 tokens.
While ERC1155 smart contract's function "balanceOf" shows the exact (correct) amount of balance.

### Steps to reproduce

1.Mint ERC1155 Tokens with a specific token id
2. Import tokens into the MetaMask
3. MetaMask shows zero balance, which is incorrect

### Error messages or log output

```shell
There is no error message as it seems to be a bug
```

### Version

10.22.1

### Browser

Chrome

### Operating system

Windows

### Additional context

I think MetaMask doesn't support ERC1155 Tokens yet as ERC1155 requires two parameters(account address, token id) to query balance of a specific account.

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
> ### Describe the bug
> 
> MetaMask shows zero (incorrect) balance of ERC1155 tokens.
> While ERC1155 smart contract's function "balanceOf" shows the exact (correct) amount of balance.
> 
> ### Steps to reproduce
> 
> 1.Mint ERC1155 Tokens with a specific token id
> 2. Import tokens into the MetaMask
> 3. MetaMask shows zero balance, which is incorrect
> 
> 
> ### Error messages or log output
> 
> ```shell
> There is no error message as it seems to be a bug
> ```
> 
> 
> ### Version
> 
> 10.22.1
> 
> ### Build type
> 
> _No response_
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> I think MetaMask doesn't support ERC1155 Tokens yet as ERC1155 requires two parameters(account address, token id) to query balance of a specific account. 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
