### ISSUE TITLE
Wallet Tx Security Provider: Update UI for Transaction Security Check in Settings

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16625]
## Background
We have created a toggle for users to enable the transaction security check/transaction security provider under Settings > Experimental https://github.com/MetaMask/metamask-extension/issues/16257. New designs were created for it since and we should update the UI to reflect them. 

## Resources
[Figma file](https://www.figma.com/file/QSel2zV8K3jMPTCYeskOQJ/External---Support-for-tx-security-providers-(MVP)?node-id=4503%3A19754&t=YxMWgKUR7oib8jXu-0)

## Acceptance Criterias
1. The new design is implemented for transaction security provider toggle.

**Comment by bschorchit** [comment]
Pinging @coreyjanssen to confirm whether the copy for this has been reviewed already or any tweak is needed.
We'll also need a knowledge base article for the `Learn more` link that I'll follow up on.

![Image](https://user-images.githubusercontent.com/34968356/203342106-98022d4d-8992-4b34-a191-54c19e21e5d1.png)

**Comment by ElvirCe** [comment]
@bschorchit once we have confirmation fro the copy txt for the message is good to go and the link for the "Learn more" button we can move the ticket into "Ready for Development"

**Comment by coreyjanssen** [comment]
My only edit would be to the last sentence: 
"Be sure you understand the potential benefits, risks, and privacy concerns before enabling any provider."

**Comment by bschorchit** [comment]
New proposed copy: `We use third-party's APIs to detect and display risks involved in unsigned transaction and signature requests before you sign them. These services will have access to your unsigned transaction and signature requests, your account address, your IP address and your preferred language.`

I'm proposing this so it matched the copy updates being introduced here: https://github.com/MetaMask/metamask-extension/issues/16727

**Comment by bschorchit** [comment]
Also an open question: should this settings be added to both Experimental and Privacy settings? I think adding it to experimental only as it's something that is off by default is enough.

**Comment by ElvirCe** [comment]
@bschorchit please note that Filip started working on this ticket already. I will tell him to wait with the update of the content until we have the final one. 
I agree with you on the settings option and it can go only to the experimental settings. 

We also need the link to the link to the Learn more section.

**Comment by bschorchit** [comment]
Yes, sorry for changing things after work has started, but this is important in light of the other on going efforts. 

On the good side: with the new copy, a learn more link would not be needed, @ElvirCe. So we would be unblocked by that.

**Comment by bschorchit** [comment]
To further match the recent updates, would we then need to link out to an OpenSea privacy policy for this service? Where would this be included in the design? cc: @SayaGT @holantonela

**Comment by SayaGT** [comment]
@bschorchit we can keep the setting in experimental only but we can introduce the new pattern here of subcategorising the settings. Users will have an idea where to find them when we decide to move them out of the "Experimental" and it will help us sort the features based on the severity of privacy vs general. CC: @holantonela @coreyjanssen 

[Figma design here](https://www.figma.com/file/cAHj7i7USWsMkzDsePN7zy/Settings-%3E-Security-%26-Privacy?node-id=4212%3A4172&t=e8
<img width="276" alt="Screenshot 2022-12-06 at 15 27 46" src="https://user-images.githubusercontent.com/87030673/205953672-af63e326-1ce7-4cdd-b80c-97e7de17bb14.png">
NfiDZiRGS3jztT-1)

**Comment by ElvirCe** [comment]
Set to blocked, waiting for @bschorchit to advise regarding which toggle to use form the new design and the URL for the Privacy Policy

**Comment by bschorchit** [comment]
Proposed final design is [here](https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?node-id=4983%3A26784&t=H3PgEpqvjHPr1hnS-0) pending adjustment and review from @holantonela

**Comment by bschorchit** [comment]
Review and adjustment is done and design is final and ready [here](https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?node-id=4983%3A26784&t=pOyo5ilHQfIloSwK-0), @ElvirCe
