### ISSUE TITLE
IA Nav Redesign v1

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#16630]

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by hilvmason** [comment]
@kevinghim can this epic be closed? feeling that other project(s) will take this over :)
