### ISSUE TITLE
[Sentry] Error: External transaction nonce should not be in confirmed txs

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16632]
https://sentry.io/organizations/metamask/issues/3756067538/?referrer=github_plugin

```
Error: External transaction nonce should not be in confirmed txs
  at "stack": "Error: External transaction nonce should not be in confirmed txs\n    at new f ( (metamask/common-2.js:1:308766)\n    at i ()
  at r.validateConfirmedExternalTransaction (app/scripts/controllers/transactions/lib/util.js:298:27)
  at TransactionStateManager.addExternalTransaction (app/scripts/controllers/transactions/tx-state-manager.js:296:5)
  at TransactionController.confirmExternalTransaction (app/scripts/controllers/transactions/index.js:1647:31)
...
(3 additional frame(s) were not displayed)
```

**Comment by Nanimustshine** [comment]
> https://sentry.io/organizations/metamask/issues/3756067538/?referrer=github_plugin
> 
> ```
> Error: External transaction nonce should not be in confirmed txs
>   at "stack": "Error: External transaction nonce should not be in confirmed txs\n    at new f ( (metamask/common-2.js:1:308766)\n    at i ()
>   at r.validateConfirmedExternalTransaction (app/scripts/controllers/transactions/lib/util.js:298:27)
>   at TransactionStateManager.addExternalTransaction (app/scripts/controllers/transactions/tx-state-manager.js:296:5)
>   at TransactionController.confirmExternalTransaction (app/scripts/controllers/transactions/index.js:1647:31)
> ...
> (3 additional frame(s) were not displayed)
> ```

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by seaona** [comment]
**Repro steps:**
1. Select Mainnet
2. Perform a Swap with Smart Transaction enabled
3. Wait
4. Change networks to Goerli -- see error on the background console. This triggers the Sentry event

https://user-images.githubusercontent.com/54408225/203393062-093cd487-fd6f-49b6-befa-51711130e964.mp4
