### ISSUE TITLE
What's New for the transaction security provider

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16636]
## Background
We want to announce the new security provider feature to users. We should follow a similar design that was used for the Smart Transactions (screenshot).

## Acceptance Criterias
1. Clicking on `Enable security provider` should turn the feature on. 
2. There should have an `X` on top as the other What's new modals have so users are able to close it.

## Reference
[Design on figma](https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?node-id=4806%3A27316&t=r03VOmHXdcPZlRBn-0#322791664)

**Final Design:** 
![Image](https://user-images.githubusercontent.com/98470173/207835271-7c504668-4768-4d39-8b3f-bab102ccb87f.png)

**Comment by bschorchit** [comment]
We have the design for the what's new [here](https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?node-id=4806%3A27316&t=r03VOmHXdcPZlRBn-0#322791664)
cc: @filipsekulic

**Comment by ElvirCe** [comment]
@filipsekulic note to use the copy from the latest design Barbara provided above.
