### ISSUE TITLE
[FLASK] Expose transaction origin to Snaps with permission

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/metamask-extension#16631]
We added a permission caveat to expose the transaction origin to Snaps in MetaMask/snaps-monorepo#956. This is yet to be implemented in the extension.

**Comment by Nanimustshine** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Nanimustshine** [comment]
> We added a permission caveat to expose the transaction origin to Snaps in MetaMask/snaps-monorepo#956. This is yet to be implemented in the extension.

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
