### ISSUE TITLE
Seed words on a per-chain basis?

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#1664]
As brought up by `noman` on our Slack channel, it might be beneficial to ask users to import their seed phrases again or generate new ones when switching to a test network for the first time. It could reduce user confusion, especially when it comes to "where's my ether? oh, I sent it on the testnet". Then again, we default to main net anyways and most users won't need to visit the testnets anyways, so it could be a slight hassle for power users?

Requires discussion.

**Comment by noman-land** [comment]
It might be nice to match what geth does and store the mainnet and the testnet keystore files in separate buckets. Mist follows this rule as well.

**Comment by flyswatter** [comment]
This could also be mitigated with the MNID address format:
https://medium.com/uport/mnid-a-safer-way-of-encoding-blockchain-addresses-in-a-multi-chain-world-4222e7b62714
