### ISSUE TITLE
[Bug]: Error: Unable to determine contract standard

### ISSUE THREAD

**Issue by jfdelgad** [MetaMask/metamask-extension#16649]
### Describe the bug

For some tokens that are in fact ERC20 this error shows up which prevent any transfers of such tokens using metamask.
This was not a problem in the past with such tokens and appears that in May of 2022 [the same issue was reported](https://github.com/MetaMask/metamask-extension/issues/14187) and then [fixed](https://github.com/MetaMask/controllers/pull/830) but it is again an issue now.

The spinner just keeps running and the console show the error described in the title.
### Steps to reproduce

1. Trying to send ERC20 tokens that are behind a proxy

### Error messages or log output

```shell
Uncaught (in promise) Error: Unable to determine contract standard
  at g.<anonymous> (common-9.js:1:315966)
  at Generator.throw (<anonymous>)
  at s (common-9.js:1:312996)
sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7:1          Failed to load resource: the server responded with a status of 429 (Too Many Requests)
```

### Version

10.22.2

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/16596

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/16596
