### ISSUE TITLE
Update all network logos in Settings > Networks (WIP)

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#16647]
Dependency: https://github.com/MetaMask/design-tokens/issues/263

### Description
Update all network logo image assets and use the [AvatarNetwork](https://metamask.github.io/metamask-storybook/?path=/docs/ui-components-component-library-avatar-network-avatar-network-stories-js--default-story#avatarnetwork)  component

- Replace all token and network images with consistently named and formatted svgs https://github.com/MetaMask/design-tokens/issues/263
- All logos in the "Add a network" form should use the [AvatarNetwork](https://metamask.github.io/metamask-storybook/?path=/docs/ui-components-component-library-avatar-network-avatar-network-stories-js--default-story#avatarnetwork) component
- There may be some cross over into other components these should be updated as well. If any image instances are used to represent tokens use the [AvatarToken](https://metamask.github.io/metamask-storybook/?path=/docs/ui-components-component-library-avatar-token-avatar-token-stories-js--default-story#avatartoken) component

### Before

<img width="699" alt="Screen Shot 2022-11-22 at 4 47 57 PM" src="https://user-images.githubusercontent.com/8112138/203460523-a20bb915-4483-4aae-bc00-fad8ef28ad27.png">
<img width="727" alt="Screen Shot 2022-11-22 at 4 48 16 PM" src="https://user-images.githubusercontent.com/8112138/203460529-54a82a6e-cc3c-4864-bba5-cf907d398cb3.png">

### After

![Group 3](https://user-images.githubusercontent.com/8112138/203460611-0ae2f823-ac51-460f-b557-74ae498603cc.png)

![Group 4](https://user-images.githubusercontent.com/8112138/203460615-550bc0db-3c01-4402-91b0-f9a07400d7e3.png)

### Technical Details
- [ ] Replace `arbitrum.svg` in `app/images/arbitrum.svg` with `logo-arbitrum.svg` and update references to new image
- [ ] Replace `aurora.svg` in `app/images/aurora.png` with `logo-aurora.svg` and update references to new image
- [ ] Replace `avax.svg` in `app/images/avax.png` with `logo-avax.svg` and update references to new image
- [ ] Replace `black-eth-logo.svg` in `app/images/black-eth-logo.svg` with `logo-eth.svg` and update references to new image
- [ ] Replace `bnb.png` in `app/images/bnb.png` with `logo-bnb.svg` and update references to new image
- [ ] Remove `bsc-filled.svg` in `app/images/bnb.png` and update references to use `logo-bnb.svg`
- [ ] Replace `enslogo.svg` in `app/images/enslogo.svg` with `logo-ens.svg` and update references to new image
- [ ] Replace `enslogo.svg` in `app/images/enslogo.svg` with `logo-ens.svg` and update references to new image
- [ ] Remove `eth_badge.svg`. I could not find any instance of it?

![Screen Shot 2022-11-22 at 4 37 54 PM](https://user-images.githubusercontent.com/8112138/203448441-21c13bb2-bd56-44cb-9dbb-a458b51c0a5d.png)

- [ ] Remove `eth_logo.svg` in `app/images/eth_logo.svg` and update references to use `logo-eth.svg`
- [ ] Replace `fantom-opera.svg` in `app/images/fantom-opera.svg` with `logo-fantom-opera.svg` and update references to new image
- [ ] Replace `harmony-one.svg` in `app/images/harmony-one.svg` with `logo-harmony-one.svg` and update references to new image
- [ ] Replace `matic-token.png` in `app/images/matic-token.png` with `logo-polygon.svg` and update references to new image
- [ ] Replace `optimism.svg` in `app/images/optimism.svg` with `logo-optimism.svg` and update references to new image
- [ ] Replace `palm.svg` in `app/images/palm.svg` with `logo-palm.svg` and update references to new image

### Acceptance Criteria
- All old images have been removed and replaced with new `logo-` prefixed svgs
- All network logos use the `AvatarNetwork` component

**Comment by bschorchit** [comment]
Blocked by https://github.com/MetaMask/metamask-extension/pull/16663

**Comment by bschorchit** [comment]
The above PR has now been merged. But I think this ticket might still be blocked by the formatted svgs creation? Is that correct, @georgewrmarshall ?

**Comment by georgewrmarshall** [comment]
Hey @bschorchit, yes still blocked. I've created an issue and assigned to @Akatori-Design for the image assets https://github.com/MetaMask/design-tokens/issues/263

**Comment by georgewrmarshall** [comment]
Network images are looking 🔥 we can close this
<img width="717" alt="Screenshot 2023-07-21 at 12 43 37 PM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/216b4b06-5848-446b-b719-f5910d4f9725">
