### ISSUE TITLE
Enable ENS support for L2 networks

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#16644]
## Background 
Currently, MetaMask doesn’t support ENS resolution while a user is connected to an L2 network (Optimism, Arbitrum, etc.) Enabling ENS on L2s would prevent user error and decrease time needed to them  to go to ens.domains, translate the hex, copy, and paste it into the MetaMask recipient and then transfer.

## Acceptance criteria
- [ ] Use the ENS [library](https://docs.ens.domains/dapp-developer-guide/resolving-names) and ENS [registry deployment](https://docs.ens.domains/ens-deployments) to resolve and store EVM addresses include L2s
- [ ] When a user enters an EVM including L2s compatible address, it resolves to an ENS name (reserve resolution)

## Related tickets

- [Support for ENS wildcard and offchain resolution #14675](https://github.com/MetaMask/metamask-extension/pull/14675#top)

**Comment by web3-person** [comment]
Can confirm I personally find this quite annoying UX, please implement.

**Comment by kevinghim** [comment]
Could be resolved through https://github.com/MetaMask/specifications/issues/11

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/18648
