### ISSUE TITLE
Warn canceling pending confirmations when switching networks

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#16646]
## **User story**

As a user I want only to be warned about canceling pending confirmations when asked to switch networks if I do have any pending confirmations at the moment.

## User insights

[https://github.com/MetaMask/metamask-extension/issues/11544#issuecomment-1088232307](https://github.com/MetaMask/metamask-extension/issues/11544#issuecomment-1088232307)

## **Steps to reproduce**

1. Go to a dapp that will request MetaMask to switch networks
2. Notice the warning showing up even when you don’t have any pending confirmation

## **Screenshots**

![Screen Shot 2022-01-18 at 18.31.11.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/ca67c0d9-7617-4fb1-8fb7-bb8bffbf7975)

## Acceptance **criteria**

1. Only show the warning if the user has any pending confirmation.
2. Update the logic to show this warning only if the user has pending confirmations.

**Comment by ElvirCe** [comment]
One way to reproduce this is to go to https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#writeContract, connect to Web3 and choose MetaMask.
