### ISSUE TITLE
[Bug]: Some addresses are displayed as `New Contract` on the recipient for a simple Send

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16658]
### Describe the bug

**Problem**: sometimes some addresses are displayed as `New Contract` on the recipient for a simple Send.

- **Case 1**: try to perform a simple Send to this address 0x0000000000000000000000000000000000000001 and you'll see that the recipient is displayed as "New Contract"

https://user-images.githubusercontent.com/54408225/204510802-3a6c3818-bc49-4d66-8d69-b61b05e35f73.mp4

- **Case 2**: save a Contact on my Address Book, without specifying any name, and then proceed to perform a Send to that contact, I see that the address is resolved as a "New Contract".

https://user-images.githubusercontent.com/54408225/203600226-ae4e0211-30a1-434e-becd-5086b9cea9c1.mp4

### Steps to reproduce
1. Open MM
2. Click Settings
3. Click Address book
4. Click Add Contact
5. Introduce an EOA 0x4fF79526eA1d492a3dB2aa210d7318ff13F2012c (goerli)
6. Leave empty the name
7. Click Add
8. Close Settings
9. Click Send
10. Enter address from step 5
11. Click Next -- see how contact is resolved as New Contract

### Version

12.23.0

### Browser

Chrome

### Operating system

Linux

**Comment by ElvirCe** [comment]
@seaona @bschorchit what should be the expected behavior?

**Comment by bschorchit** [comment]
> Mmmm I am thinking maybe we should not be able to add a Contact with an empty name in the first place?

I agree we shouldn't allow users to add contacts with empty names

**Comment by bschorchit** [comment]
@ElvirCe could we do these 2 things here?
1. Disable the save button on the add contact form if no name is inputted.
2. Display the address (as any other regular address) and not "New Contract" for `0x0000000000000000000000000000000000000001`. 

For 2 we could also investigate wether this is happening to any other address besides the one mentioned here. I do think this makes sense to happen for contract deployments, but it shouldn't happen (as far as I know) for any other situation.

**Comment by bschorchit** [comment]
This is a bug introduced in 10.23

**Comment by ElvirCe** [comment]
Expected Behavior: 

1. Disable the save button on the add contact form if no name is inputted. 
- The "Username" field should include validation for: TBD 
2. Display the address (as any other regular address) and not "New Contract" for all addresses.
It is happening to any other address besides the one mentioned above and we need to fix this for all addresses. 
Also on the contract deployments this should be resolved.

**Comment by bschorchit** [comment]
This component should follow the existing address-display-fallback-logic we have (this should already exist here, but just want to make sure we don't remove it by accident). For reference, is the same logic described and implemented here: https://github.com/MetaMask/metamask-extension/issues/15780
