### ISSUE TITLE
[Bug]: [MV3] Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElement')

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16654]
### Describe the bug

Problem: when I unlock MM and land at Home page, I see the following error 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElement')

![image](https://user-images.githubusercontent.com/54408225/203567717-3ae8dec2-2b59-4645-ae83-d3febc56ab92.png)

This issue makes our [e2e test fail](https://github.com/MetaMask/metamask-extension/issues/16211) on MV3.

### Steps to reproduce

1. Start MV3 `yarn start:mv3`
2. Go over the Onboarding process
3. Land at Home page -- check UI console error

### Version

develop

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
This is fixed with #17354
