### ISSUE TITLE
[Bug]: MM popup keeps auto-scrolling to the top every some seconds

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16657]
### Describe the bug

**Problem**: if I try to connect to a Dapp and I open MM popup, if I scroll down to the list of address, MM auto-scrolls to the top every some seconds, worsening user experience.

https://user-images.githubusercontent.com/54408225/203592769-605cda87-80c3-4b8c-a5e1-94c99398c458.mp4

### Steps to reproduce

1. Go to a dapp https://spruceid.github.io/test-dapp/
2. Click Connect
3. Scroll down the list of address from the MM popup
4. Wait -- see how MM scrolls you back up
5. Scroll down again
6. Wait  -- see how MM scrolls you back up

### Version

10.23.0

### Browser

Chrome

### Operating system

Linux

**Comment by ElvirCe** [comment]
@seaona @bschorchit In the video you just wait but I also checked and when I for example click on any of the accounts at the bottom to check or uncheck them, the system auto scrolls to the top, should we just fix the waiting one or also if you click on an account at the bottom to not auto scroll to the top?

**Comment by bschorchit** [comment]
> @seaona @bschorchit In the video you just wait but I also checked and when I for example click on any of the accounts at the bottom to check or uncheck them, the system auto scrolls to the top, should we just fix the waiting one or also if you click on an account at the bottom to not auto scroll to the top?

Let's fix both. Thanks for catching that, @ElvirCe

**Comment by bschorchit** [comment]
Also, this is the ideal behavior for the connect screen (auto scrolling to the pre-selected one if there's one): https://github.com/MetaMask/metamask-extension/pull/13621 
We might have a regression here.

**Comment by bschorchit** [comment]
This also relates to https://github.com/MetaMask/metamask-extension/issues/15315
