### ISSUE TITLE
[Bug]: Send slice initialized as collectible send with a collectible not currently owned by the select account

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16656]
### Describe the bug

**Problem**: if I import an ERC1155 Token contract and click Send, I stay on the Home page and get the following error on the console `Send slice initialized as collectible send with a collectible not currently owned by the select account`

https://user-images.githubusercontent.com/54408225/203590011-ed0b6604-cf80-47ba-b760-681e59183bcd.mp4

### Steps to reproduce

1. Change to Goerli network
2. Click Import tokens
3. Add an ERC1155 token address. I.e. `0xf4910C763eD4e47A585E2D34baA9A4b611aE448C`
4. Enter any decima number. I.e. 0
5. Proceed
6. Click Send the imported token -- see how you stay in the same Home page and check UI console

### Version

10.23.0

### Browser

Chrome

### Operating system

Linux

### Additional context

Related issue https://github.com/MetaMask/metamask-extension/issues/16622

**Comment by bschorchit** [comment]
Just for visibility, sharing Dan M.'s message here so we go back to this ticket once we release nft support: 
`issues with erc1155 tokens will be resolved when we release nft support. Testable today with the COLLECTIBLES_V1 flag`

**Comment by bschorchit** [comment]
This has been fixed with the NFT feature
