### ISSUE TITLE
[Bug]: Error updating pending transactions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16675]
### Describe the bug

**Problem**: I performed a Send on Mumbai network, and the following error appeared on the background console `pending-tx-tracker.js:65 PendingTransactionTracker - Error updating pending transactions`

1st occurrence

https://user-images.githubusercontent.com/54408225/203780385-922fd819-f7e7-41c3-9798-25d308fc0538.mp4

2nd occurrence 

https://user-images.githubusercontent.com/54408225/203798466-549f562a-6dee-4746-bbf1-bcd7136f8ea3.mp4

### Steps to reproduce

[needs investigation]

### Version

https://github.com/MetaMask/metamask-extension/pull/16547

### Browser

Chrome

### Operating system

Linux

**Comment by Gudahtt** [comment]
The "header not found" error indicates that this is likely an intermittent network failure. A network failure during an attempted update to pending transactions is expected to result in this error. Maybe this is a case where we should be logging the event as a warning rather than an error.

**Comment by seaona** [comment]
thank you for the clarification @Gudahtt!  Do you think we can close the issue then? Or prefer to keep it open?

**Comment by Gudahtt** [comment]
We could leave it open as a low-sev bug, to improve the logging. We don't want errors in our console for normal scenarios.
