### ISSUE TITLE
MV3: Session e2e Test Cases

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#16689]
~~- [ ] Ensure user is kept logged in after service worker re-start~~

~~- [ ] Ensure user can continue performing actions with the full MM width after service worker re-start~~

~~- [ ] Ensure service worker is re-started after killing it~~

~~- [ ] Ensure popup view continues to work after service worker re-start~~

(Edit: the above items are handled by [the metrics e2e tests ](https://github.com/MetaMask/metamask-extension/pull/18347))

- [ ] Restart service worker multiple times and ensure a simple flow is still usable (e.g. simple send within full screen view)

- [ ] (maybe we should do this, maybe not) ensure MetaMask is locked when a browser session ends (e.g. after closing the browser or after turning off the extension)

**Comment by danjm** [comment]
first three action items above are covered by https://github.com/MetaMask/metamask-extension/pull/18347
