### ISSUE TITLE
[Bug]: Approve ERC721 token screen is displayed instead Improved Token Approve screen for an ERC20 token

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16687]
### Describe the bug

**Problem**: the Approve ERC721 token screen is displayed instead of the new Improved Token Approve screen for ERC20 tokens, when I've performed a Network change.

https://user-images.githubusercontent.com/54408225/204016026-beab6be1-cf6d-4b32-9b55-5eb19f46fec4.mp4

### Steps to reproduce
First steps based on https://github.com/MetaMask/metamask-extension/issues/16429 

1. Select Mainnet on MM     
2. Go to https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f#writeContract
3. Connect your wallet
4. Under approve input any address and value
5. Click on write
6.  On the MetaMask check that Improved Token Approval screen is displayed
7. Reject tx
8. Open MM
9. Select Sepolia network
10. Change back to Mainnet
11. On Etherscan click Write again
12. On the MetaMask check that Improved Token Approval screen is not displayed, instead an ERC721 token approval is displayed

### Version

13.23.0

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
This issue seems introduced by this PR https://github.com/MetaMask/metamask-extension/pull/16547

**Comment by bschorchit** [comment]
Was this fixed by https://github.com/MetaMask/metamask-extension/pull/16760 ? Or does it still need another fix/PR?

**Comment by Gudahtt** [comment]
Details here: https://github.com/MetaMask/metamask-extension/pull/16760#issuecomment-1333857211

Though I think this was fixed in a follow up PR

**Comment by Gudahtt** [comment]
Ah, here is the subsequent PR that resolves this issue: https://github.com/MetaMask/metamask-extension/pull/16765

**Comment by seaona** [comment]
ohhh thank you @Gudahtt. Then I propose to wait until this subsequent PR is merged to verify things are working fine before closing the issue

**Comment by danjm** [comment]
Closed once we merged https://github.com/MetaMask/metamask-extension/pull/16765
