### ISSUE TITLE
Allow users to add custom RPC during onboarding

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#16696]
Must be before any request to Infura. Should be part of the onboarding privacy screen:

![privacy-onboarding](https://user-images.githubusercontent.com/542863/204048790-2d0c62a1-3373-48cc-98b6-c4b823aa4314.jpg)

**Comment by quickchase** [comment]
Related: https://github.com/MetaMask/metamask-extension/issues/5788

**Comment by bobsummerwill** [comment]
“Show Incomming Transactions” typo, fyi!

Best wishes.
