### ISSUE TITLE
[Bug]: Starting X button do not terminate connection of network when not available eg localhost.

### ISSUE THREAD

**Issue by helderjnpinto** [MetaMask/metamask-extension#16698]
### Describe the bug

When i start metamask its locked and network is not available we need to wait until the switch button appears. Button X do not terminate to switch the network. 

[images here](https://postimg.cc/gallery/2ms4XL6)

### Steps to reproduce

1. connect metamask to avaliable localhost network
2. shutdow localhost network 
3. close browser or restart metamask plugin
4. when start metamask "locked" it trying to connect to localhost that not exist but the button X do not close or terminate this feature... we need to wait until show "switch network buttton or try again"

### Version

10.22.1

### Browser

Chrome, Other (please elaborate in the "Additional Context" section)

### Operating system

Linux

### Additional context

Linux tuf-15 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux

Version 107.0.5304.121 (Official Build) unknown (64-bit)

flatpak distribution

**Comment by danjm** [comment]
Slightly simpler reproduction steps are:

1. connect metamask to avaliable localhost network
2. lock metamask
3. close metamask
4. open metamask

You will see the network loading screen, but the 'x' in the top right won't do anything. What clicking the 'x' should do is switch the user to mainnet and close the network loading screen

**Comment by DDDDDanica** [comment]
At the version of 10.29.0, this issue is solved. 

https://user-images.githubusercontent.com/12678455/233968194-bfa0d615-30ac-4b41-86ef-8887dc8bf1c9.mov

**Comment by helderjnpinto** [comment]
Yes Finally, i confirmed. :tada: this issue is a pain for developers working as multiple networks.
