### ISSUE TITLE
[Bug]: Don't block deletion of default networks using Infura RPCs

### ISSUE THREAD

**Issue by flaflafla** [MetaMask/metamask-extension#16701]
### Describe the bug

I am unable to edit or delete networks using Infura RPC endpoints, which are included by default, eg the one labeled `Ethereum Mainnet` using `https://mainnet.infura.io/v3/` as its RPC url.

I would like to avoid accidentally sending network requests to an RPC provider I don't trust, in this case Infura, but as the UI stands I'm unable to adequately guard against this possibility. (As it happens, I've already slipped up.) I can add a new RPC, but in order to be sure I don't connect to the wrong network, I'd like to be able to:

- delete the networks that were included by default
- edit these networks, or
- set a network I add manually as a personal default

In an ideal world, I'd like to be able to do all three.

I can see how less-sophisticated users could accidentally delete or edit the Ethereum mainnet RPC, which would generate more support tickets and more work for the team. If, in light of that concern, the UI options I'm asking for need to go behind an `Advanced` toggle, so be it.

I'm happy to submit a PR to introduce these features myself, but I'd like to be reasonably sure it has a chance of getting merged before starting that work.

I'd also like to thank the MetaMask team for their work and dedication. I hope this issue will be received in the spirit I intended: a discussion of concrete steps to alleviate a problem experienced by users, not an attempt to point fingers or cast the team as surveillance-state villains.

### Steps to reproduce

1. Open the `Networks` dropdown
2. Click on `Ethereum Mainnet`
3. Attempt to edit the RPC url or delete the network

### Error messages or log output

```shell
N/A
```

### Version

10.22.1

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS, Linux

**Comment by DefiDebauchery** [comment]
Nearly a year later, no movement appears to have been done to improve user privacy.
