### ISSUE TITLE
Onboarding v2: Don't send network requests until onboarding is complete

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#16705]
Onboarding v2 introduces privacy settings options to the onboarding flow. These happen towards the end of the flow (see video below)

https://user-images.githubusercontent.com/7499938/204328922-163e7f20-2cc2-422d-afec-087de0918ef2.mp4

We want to further expand on that to allow the user to set a custom rpc during the flow https://github.com/MetaMask/metamask-extension/issues/16696

We should not send any network requests to any providers or any of the services that users opt out of, until the users have gotten passed that final screen and completed onboarding. (Of course, we should then only send network requests according to the users preferences).

The only requests we might send during onboarding are usage metrics or sentry errors, but only if the user opted in to metametrics at the beginning of the onboarding flow.

**Comment by kevinghim** [comment]
Related PR: https://github.com/MetaMask/metamask-extension/pull/16789
