### ISSUE TITLE
Allow adding networks with chain_id 1 via addCustomNetwork API

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#16712]
Today we disallow it (sorry if this is a duplicate)

So far we had disabled this because we were concerned about phishing potential, but we still allow adding a main-net network via settings, so this vector still existed.

I propose we add this method, and add our best copy to represent the risk. And any copy that would improve this case would probably be good for the generic addCustomNetwork case, so let's just review that copy @coreyjanssen . Should be something like:

- The network provider will be able to see and associate your accounts together.
- The network provider will be responsible for broadcasting your transactions, and their reliability.
- The network provider will be trusted to provide an accurate view of account balances and other on-chain state.

**Comment by vandan** [comment]
If we open this up via dapp API, then there's a risk of noisy network override requests constantly hitting wallet users when they navigate across dapps. @danfinlay would we consider adding a settings toggle that allows users to keep their network configuration for a given chainID locked - ignoring dapp-triggered recommendations to change the default network? (and keeping this locked by default for existing and added chains)

**Comment by bschorchit** [comment]
> If we open this up via dapp API, then there's a risk of noisy network override requests constantly hitting wallet users when they navigate across dapps. @danfinlay would we consider adding a settings toggle that allows users to keep their network configuration for a given chainID locked - ignoring dapp-triggered recommendations to change the default network? (and keeping this locked by default for existing and added chains). It adds a little friction to unlock, but would keep the frequency of override requests from dapps from getting out of hand.

But this is already possible for any network other than Ethereum. We would just be matching the pattern across the different chains which makes sense to me.
That being said, an user made a similar request in the past here https://github.com/MetaMask/metamask-extension/issues/15909#issuecomment-1253005204

**Comment by bschorchit** [comment]
Related issues: https://github.com/MetaMask/metamask-extension/issues/16467 https://github.com/MetaMask/metamask-extension/issues/15876 https://github.com/MetaMask/metamask-extension/issues/13269

**Comment by adonesky1** [comment]
@bschorchit @holantonela what do we think of adding additional friction for this case using a similar pattern as we used here for the `setApprovalForAll` flow:
![Screen Shot 2022-11-29 at 3 22 50 PM](https://user-images.githubusercontent.com/34557516/204650688-308f7b1a-95cb-479b-8052-14238753e464.png)


Currently we show warnings like this on the `addEthereumChain` pop up: 
![Screen Shot 2022-11-29 at 3 24 35 PM](https://user-images.githubusercontent.com/34557516/204651125-1a1f6ab7-ef07-4fcf-ba79-175c2cf835ad.png)

we could obviously add more for this case, but it seems like we may want to add even further friction since this is a potentially more consequential action.

**Comment by coreyjanssen** [comment]
Could someone clarify whether we need copy for this still, or if we're moving forward with the solution proposed by @adonesky1? and if we are, do we need copy for that solution? don't wanna let this fall through the cracks!

**Comment by adonesky1** [comment]
@coreyjanssen I think this ticket is currently waiting on feedback on my comment before copy input will be required 😃

**Comment by helpfulBro** [comment]
> @danfinlay would we consider adding a settings toggle that allows users to keep their network configuration for a given chainID locked - ignoring dapp-triggered recommendations to change the default network? (and keeping this locked by default for existing and added chains).
> It adds a little friction to unlock, but would keep the frequency of override requests from dapps from getting out of hand.

Being able to prevent dApps suggesting new RPCs is definitely needed these days.
As a user I'm constantly denying requests to add RPCs even though I'm already connected to that chain (via a different RPC).

Although unsure if the first custom RPC added should be locked (as users may get stuck with a non-working RPC) but having a toggle in the settings will improve quality of life for multi chain users.

**Comment by holantonela** [comment]
> Although unsure if the first custom RPC added should be locked (as users may get stuck with a non-working RPC) but having a toggle in the settings will improve quality of life for multi chain users

Agreed. We may want to have a general setting that allows/disable new RPC requests from dapps. This can be attached to the initiative of favorite sites/saved sites/allowlisted sites. Perhaps, local trusted sites may be able to jump this config (not sure how frequent this request is from dapps or if it is a one-time kinda flow) 

>  but it seems like we may want to add even further friction since this is a potentially more consequential action.

Agreed with @adonesky1 that we need more than our current warning. We can reuse the toast pattern for sure. We should iterate that component to make sure we have a cadence of warnings that can allow users to understand when is a real risk. The iteration may contain details about the new network. 

Can a dapp desired RPC be used only for one transaction without saving it in networks? Is there a use case for it? I'm hesitant to fill the network list with dapps custom requests. That may be where we are going, tho.
