### ISSUE TITLE
[Bug]: Improved Approval screen does not show updated balance if a tx is confirmed while screen is open

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16718]
### Describe the bug

**Problem**: if I have triggered the Approve function while I have a pending transaction, I will see that the Balance and max Spending Cap always refers to the balance I had prior that transaction is confirmed.
This means that once the transaction is confirmed, I have less balance in my account but I am still able to see the old balance and the max Spending Cap referring to that old balance.

https://user-images.githubusercontent.com/54408225/204507303-acedb53d-0cf8-41c3-95d2-ea5b66515dff.mp4

### Steps to reproduce

1. Go to test Dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Create Token
4. Accept transaction on MM
5. Click Add Token to the Wallet
6. Accept prompt on MM
7. Click Transfer tokens
8. Accept transaction on MM
9. Click Approve tokens (before transaction on step 8 has been confirmed)
10. See Balance and max spending cap
11. Wait until transaction of step 8 has been confirmed
12. See Balance and max spending cap is not updated

### Version

10.23.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Additional info: this applies to any confirmation (transaction and signatures) where we show the new header component, not only the token allowance one.
