### ISSUE TITLE
[Bug]: Gas estimate for Legacy transaction Edit screen does not match Confirmation screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16717]
### Describe the bug

**Problem**: with the new introduction of the Gas estimate on the Send/Edit screen, we are now able to see the estimate before reaching to the Confirmation screen. The issue is that for Legacy transactions the 2 estimates do not match. It seems that they are calculated differently, having non-coherent results for one screen and the other.

https://user-images.githubusercontent.com/54408225/204504949-fde29db5-7677-4521-bb0c-76fc210bc051.mp4

### Steps to reproduce

1. Open Test Dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Send EIP1559 transaction -- see Gas estimate
4. Click Edit -- see Gas estimate is the same as step 3
5. Reject the transaciton
6. Now click on Send Legacy transaction -- see Gas estimate
7. Click Edit -- see Gas estimate is different as step 6

### Version

develop 2680340e276671b4e282dd3fb84064ddf3e13b44

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
We should aim to solve this too when working on: https://github.com/MetaMask/metamask-extension/issues/17459

**Comment by bschorchit** [comment]
Closing this in favor of https://github.com/MetaMask/metamask-extension/issues/18420
