### ISSUE TITLE
Improve MetaMetrics onboarding copy specificity

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#16711]
Ensure the distinction between MetaMetrics and a provider are clearer. cc @coreyjanssen

**Comment by hilvmason** [comment]
@kevinghim another copy issue to please help with, and update ticket once done

**Comment by holantonela** [comment]
@SayaGT is working on this UI. We are using the [mobile content/layout](https://www.figma.com/file/4gkmBwSE9qkecCS69pwsG3/Onboarding-Redesign?node-id=584%3A32322&t=AITTRibW06CHlps7-4) as canonical. We can rewrite the specifics for extension if they exist.

Adding Saya and Corey to this ticket. Removing myself.

**Comment by coreyjanssen** [comment]
Thoughts on how this addresses the IP address issue @kevinghim @danfinlay? This format aligns with what Antonela linked above (canonical figma). 


**Help us improve MetaMask**
We would like to gather basic usage data to improve the usability of our product.  

When we gather metrics, it's always:

Anonymous
MetaMask only collects relevant data like your country, but not your specific location.  Your clicks and page views are anonymous.

Private
MetaMask never collects keys, transactions, your full IP address, or any personal information. However, RPC providers collect your IP address when you send a transaction, and Infura (link to privacy policy) is the default for MetaMask. You can change this to a third-party provider in settings. We will never sell your data for profit. Ever!

Optional 
You’re in control of whether to share your data. You can always change your preferences and delete your in-app usage data via settings at any time.

This data is aggregated and is therefore anonymous for the purposes of General Data Protection Regulation (EU) 2016/679. Please see our Privacy Policy.

**Comment by kevinghim** [comment]
I commented on this on the related issue https://github.com/MetaMask/metamask-extension/issues/16709

**Comment by coreyjanssen** [comment]
updated content here based on kevin's feedback from #16709 

**Help us improve MetaMask**
Gathering basic usage data and error reporting helps us improve the usability of MetaMask.

When we gather metrics, it's always:

**Anonymous**
MetaMask only collects relevant data like your country, but not your specific location.  Your clicks and page views are anonymous.

Private
MetaMask never collects keys, transactions, your full IP address, or any personal information. However, we link to third-party service providers who might collect this information. For example, RPC providers collect your IP address when you send a transaction. Infura _(link to privacy policy)_ is the default RPC for MetaMask. You can change this to another provider in settings. _(link settings to Settings > Network screen)_ **We will never sell your data for profit. Ever!**

**Optional** 
You’re in control of whether to share your data. You can always change your preferences and delete your extension usage data via settings at any time. _(link settings to screen coming soon here https://github.com/MetaMask/metamask-extension/issues/16709)_

This data is aggregated and is therefore anonymous for the purposes of General Data Protection Regulation (EU) 2016/679. Please see our Privacy Policy.

**Comment by coreyjanssen** [comment]
@darkwing updated content per the design sync feedback earlier today. this is the current iteration, but note that it hasn't been signed off on by legal to my knowledge so it still may change. 


**Help us improve MetaMask**
Gathering basic usage data and error reporting helps us improve the usability of MetaMask. **We will never sell your data for profit. Ever!**

When we gather metrics, it's always:

**Anonymous**
MetaMask only collects relevant data like your country, but not your specific location.  Your clicks and page views are anonymous.

**Private**
Your keys, transactions, full IP address, and any personal information are private. MetaMask doesn’t collect this information, but to enable certain features we use third-party service providers who might. For example, RPC providers collect your IP address when you send a transaction. Infura _(link to privacy policy)_ is the default RPC for MetaMask. You can change this to another provider in settings. _(link settings to Settings > Network screen)_ We will never sell your data for profit. Ever!

**Optional** 
You’re in control of whether to share your data. You can always change your preferences and delete your extension usage data via settings at any time. (link settings to screen coming soon here https://github.com/MetaMask/metamask-extension/issues/16709)

This data is aggregated and is therefore anonymous for the purposes of General Data Protection Regulation (EU) 2016/679. Please see our Privacy Policy.

**Comment by kevinghim** [comment]
We'll go with @coreyjanssen 's latest copy above.

**Comment by hilvmason** [comment]
thanks @kevinghim ! @brad-decker @danjm @pedronfigueiredo -- this is ready for assignment.

**Comment by kevinghim** [comment]
@darkwing final designs reflecting the copy approved by legal is [here](https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=3928%3A19996&t=GlaDUfaU4jUCVqLx-0). 

cc @coreyjanssen
