### ISSUE TITLE
Update copy on metametrics opt-in screen so that users know they are opting out of error reporting as well

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#16726]

**Comment by hilvmason** [comment]
@kevinghim can you please work through getting copy for this issue and update the ticket, we can move into ready for work. Thanks

**Comment by holantonela** [comment]
Related issue: https://github.com/MetaMask/metamask-extension/issues/3441

**Comment by kevinghim** [comment]
@coreyjanssen I like the copy. We should link "you can select another provider in settings" to the Settings > Network screen, and "change your preferences and delete your in-app usage data via settings" to this settings screen on issue being worked on https://github.com/MetaMask/metamask-extension/issues/16709

**Comment by kevinghim** [comment]
@coreyjanssen mentioning error reporting on the first line will do the trick.
