### ISSUE TITLE
Make currency conversion features optional / toggleable

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#16724]
We hit coingecko and cryptocompare APIs for these features. We can make that optional.

**Current Mobile copy:**
Show balance and token price checker
We use Coingecko API to display your balance and token price. [Privacy Policy]

**Comment by hilvmason** [comment]
@coreyjanssen we are looking for copy support on this issue, Mobile's copy is in the description if you can please help for extension?

**Comment by coreyjanssen** [comment]
@hilvmason sure! is there anything about this feature that isn't the same as in mobile? otherwise the copy from mobile should work well here, too!

**Comment by kevinghim** [comment]
[WIP designs](https://www.figma.com/file/4gkmBwSE9qkecCS69pwsG3/Onboarding-Redesign?node-id=1112%3A96011&t=YjymKMVjpdsLQJ5T-0) (from mobile)

![Screenshot 2022-11-29 at 6 49 00 PM](https://user-images.githubusercontent.com/6951929/204673565-aaf1db5b-0365-47b2-a174-2e0646cb264b.png)

**Comment by NiranjanaBinoy** [comment]
@danjm @holantonela and @SayaGT, what link should we add for the `Coingecko` and `Privacy Policy` links? Should we mention `CrytoCompare` along with `Coingecko` as we are using both to get the price?
