### ISSUE TITLE
Reorganize settings so that all privacy related settings are easily discoverable, understood and toggleable

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#16727]
Basically, what I have in mind is that all privacy related toggles should be next to each other in settings. More nuanced design consideration may be needed as well. We also may want one toggle that toggles all (e.g. "IP Protection Mode")

Note, at least some toggleable features with privacy implications are in the "Advanced" and not the "Security and Privacy" part of settings

**Comment by hilvmason** [comment]
@kevinghim can you please work with design team to ready this for development?

**Comment by holantonela** [comment]
[WIP] Content https://docs.google.com/document/d/1BPBCP2hUemknHpDYqEbnOxkNl5QG9HPA1PWnaqyUR4s/edit?usp=sharing

**Comment by segun** [comment]
Draft PR [here](https://github.com/MetaMask/metamask-extension/pull/16756) pending final design and copy/

**Comment by holantonela** [comment]
Final version approved [ref](https://consensys.slack.com/archives/G4V2HTG0Y/p1669925122091359?thread_ts=1669905463.648929&cid=G4V2HTG0Y)

https://www.figma.com/file/cAHj7i7USWsMkzDsePN7zy/Settings-%3E-Security-%26-Privacy?node-id=4013%3A38032&t=7roxmUZvYqcCSdTz-4

**Comment by segun** [comment]
@holantonela There are links in the design, but I'm not sure where to direct the link to. I've identified these links


```
export const ETHERSCAN_PRIVACY_LINK = 'https://etherscan.io/privacyPolicy';
export const CONSENSYS_PRIVACY_LINK = 'https://consensys.net/privacy-policy/';
export const COINGECKO_PRIVACY_LINK = 'https://www.coingecko.com/en/privacy';
export const CRYPO_COMPARE_PRIVACY_LINK =
  'https://www.cryptocompare.com/privacy-policy/';
export const AUTO_DETECT_TOKEN_LEARN_MORE_LINK =
  'https://consensys.net/privacy-policy/';
```

**Comment by holantonela** [comment]
Thank you @segun. I'm curious if we have any Legal advice on these. Checking offline and i'll back here.

**Comment by holantonela** [comment]
@kevinghim confirmed these links over [slack](https://consensys.slack.com/archives/GTQAGKY5V/p1670263985137589?thread_ts=1670238759.719839&cid=GTQAGKY5V).

**Comment by kevinghim** [comment]
@segun for `export const AUTO_DETECT_TOKEN_LEARN_MORE_LINK =` Can we use https://metamask.zendesk.com/hc/en-us/articles/360015489031-How-to-display-tokens-in-MetaMask
