### ISSUE TITLE
[Bug]: UI Freezes when trying to transfer tokens on a 0 decimals Smartcontract

### ISSUE THREAD

**Issue by rogerthedeveloper** [MetaMask/metamask-extension#16735]
### Describe the bug

0 Decimal ERC20 causes Metmask to get freeze when a plain transfer was intended
<img width="352" alt="imagen" src="https://user-images.githubusercontent.com/9954853/204686268-b56b6ee9-fa74-4046-a869-633d9fdfb6bb.png">

### Steps to reproduce

1. Use Goerli ETH Test Network
2. Import this test contract: 0x71e5AcA8937aB4AeA44452CEf0f5158DEd8F83a9
3. Try to send even you have 0 tokens
4. Bug appears as infinite looping

### Version

10.22.1

### Browser

Firefox

### Operating system

MacOS

**Comment by bschorchit** [comment]
Thank you for your report, @rogerthedeveloper ! We're tracking this issue here https://github.com/MetaMask/metamask-extension/issues/16596 so I'll close this one.
This will be fixed by https://github.com/MetaMask/metamask-extension/pull/16685 which will be release in version 10.23.
