### ISSUE TITLE
[Bug]: Gas Price is not saved when going back to Edit the transaction

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16741]
### Describe the bug

**Problem**: on BSC, if I want to perform a Send and change the Gas Price on the Confirmation screen, if I go back to Edit the transaction I will see that all the values are saved except the Gas Price, which displays always 10, no matter if I've changed it.

https://user-images.githubusercontent.com/54408225/204802583-66ca4c68-00e0-4e0f-9c19-fc77076038e6.mp4

### Steps to reproduce

1. Add Binance Smart Chain testnet https://chainlist.org/
2. Switch to BSC testnet
3. Click Send
4. Add recipient and amount
5. Click Next
6. Click Edit Gas
7. Change Gas Price and Limit
8. Save
9. Click Edit transaction -- see how all the values are preserved except the Gas Price

### Version

10.23.0

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This and https://github.com/MetaMask/metamask-extension/issues/16717 might related

**Comment by bschorchit** [comment]
This might not be an issue anymore for BSC as the network is now using EIP1559, but might still be an issue for other legacy networks.
Also possibly related with: https://github.com/MetaMask/metamask-extension/issues/18420
