### ISSUE TITLE
Consider resolving `snap_dialog` confirmations to `null` instead of rejecting it when closed

### ISSUE THREAD

**Issue by GuillaumeRx** [MetaMask/metamask-extension#16761]
RIght now extension rejects confirmations when the user close the confirmation by cllicking the window's close button. Probably due to this:

https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/background.js#L670

Change it so the `snap_dialog` resolves confirmations to `null` instead of rejecting the confirmation.

**Comment by kenhkan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/16761?planning-poker) with Zenhub @GuillaumeRx @ritave @FrederikBolding @hmalik88 @david0xd @Mrtenz
