### ISSUE TITLE
Create What's New for Privacy release

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#16771]
Create `What's New` for the new [Security & Privacy section](https://www.figma.com/file/cAHj7i7USWsMkzDsePN7zy/Settings-%3E-Security-%26-Privacy?node-id=4013%3A38032&t=IQotW0wvQHvxc6Dk-0). 

Suggested copy:
We have created detailed options for better privacy controls. With this update, we want to provide better transparency around how data is collected and clear sharing options. But, you’re ultimately control -- You can always change your preferences and delete your extension usage data via settings at any time by going to our Security & Privacy settings.

@coreyjanssen can you provide guidance on above?

**Comment by coreyjanssen** [comment]
Revised copy @kevinghim! 

This update provides more options so you can better control your own privacy. We've added more transparency about how data is collected and clearer options for sharing it. Change your preferences or delete extension usage data via Security & Privacy settings.
