### ISSUE TITLE
[Bug]: First time landing at Home Token Detection does not work and get `DetectTokensController single call balance fetch failed`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16774]
### Describe the bug

**Problem**: when I first land into Home page and set Mainnet, Token Detection is not working and if I click refresh I get the following error on the background console `detect-tokens.js:141 MetaMask - DetectTokensController single call balance fetch failed Error: call revert exceptio`

https://user-images.githubusercontent.com/54408225/205269774-e0937e60-4d41-4267-acd4-93003ea24d5f.mp4

### Steps to reproduce

1. Load MM
2. Import Wallet
3. Change to Mainnet
4. Click refresh -- no token is detected, background console shows error

### Version

develop 3deb8734ac1bd2c84b1b3ed368f9cbea5670da2d

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by kevinghim** [comment]
Related UX design: #16388
