### ISSUE TITLE
[Bug]: circular icons are too small and top-aligned

### ISSUE THREAD

**Issue by firnprotocol** [MetaMask/metamask-extension#16795]
### Describe the bug

beginning about a month ago, MetaMask began displaying certain circular icons incorrectly and unusually. the icon is too small, and is also aligned to the top of the circular window. the result is a "crescent-shaped" gap at the bottom. this appears both on the network switch prompt and on the signing prompt. two examples are shown below.

<img width="361" alt="Screen Shot 2022-12-03 at 1 35 32 PM" src="https://user-images.githubusercontent.com/93839494/205456624-5a331308-1d56-4401-87a4-af824d2c9eea.png">
<img width="360" alt="Screen Shot 2022-12-03 at 1 35 52 PM" src="https://user-images.githubusercontent.com/93839494/205456625-45ece10a-fd5a-42e0-a150-2ed115e9ade0.png">

### Steps to reproduce

1. go to any dapp, e.g., https://app.uniswap.org/#/swap.
2. trigger a chain switch (top-right dropdown).
3. the initial "connect wallet" prompt should also exhibit the error, i believe.

### Version

10.22.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by firnprotocol** [comment]
hello @bschorchit, any chance i could bump this? are you aware of / confirm the issue? thank you.

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> beginning about a month ago, MetaMask began displaying certain circular icons incorrectly and unusually. the icon is too small, and is also aligned to the top of the circular window. the result is a "crescent-shaped" gap at the bottom. this appears both on the network switch prompt and on the signing prompt. two examples are shown below.
> 
> <img width="361" alt="Screen Shot 2022-12-03 at 1 35 32 PM" src="https://user-images.githubusercontent.com/93839494/205456624-5a331308-1d56-4401-87a4-af824d2c9eea.png">
> <img width="360" alt="Screen Shot 2022-12-03 at 1 35 52 PM" src="https://user-images.githubusercontent.com/93839494/205456625-45ece10a-fd5a-42e0-a150-2ed115e9ade0.png">
> 
> 
> ### Steps to reproduce
> 
> 1. go to any dapp, e.g., https://app.uniswap.org/#/swap.
> 2. trigger a chain switch (top-right dropdown).
> 3. the initial "connect wallet" prompt should also exhibit the error, i believe.
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.22.2
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
