### ISSUE TITLE
[Bug]: Onboarding V2 navigation function on Install Complete page not working properly

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16803]
### Describe the bug

**Problem**: after performing the Onbaording V2 process, I see the `MetaMask install is complete screen`and the navigation for the 2 pages is not consistent, using the dots vs using the buttons.

https://user-images.githubusercontent.com/54408225/205688599-d1fe8fcc-c334-4657-9ef5-fbcb9c7995c5.mp4

### Steps to reproduce

1. Load MM for the first time
2. Go to the Create Wallet Onboarding process
3. When land on Install Complete, click the dot to navigate to next page
4. Click the Next button -- nothing happen, as you are already at the last page

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by SayaGT** [comment]
I think there is another issue here. 
1. When you click the dot to navigate to next page its supposed to show the "2nd" step which shows how to pin the extension. In the video it is overlapped with another screeen that shows the extension already pinned. See attached screenshot.

2. When you click next, it should show the screen which says "MetaMask install is complete!" with an image of MM extension showing up in extension bar. 

[Design link](https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=3931%3A20907&t=sLpJ3dNASnv7DL67-1)

<img width="448" alt="Screenshot 2022-12-05 at 19 27 06" src="https://user-images.githubusercontent.com/87030673/205725909-538aca08-f28a-4d12-9309-5a3833cc1650.png">

**Comment by jpuri** [comment]
@SayaGT : figma link above is not working, can you plz check.

**Comment by SayaGT** [comment]
Hey @jpuri you can find the design for smaller screens here. [Figma link](https://www.figma.com/file/iCOjL3k1BkQqpYHFUVVFUZ/Extension-Onboarding?node-id=2573%3A21264&t=VgDliLVP2c7ipipx-1)

**Comment by jpuri** [comment]
I have fixed the issue here https://github.com/MetaMask/metamask-extension/pull/16941

1. I have fixed image overlap by setting image with to `100%`, I have not done change for mobile width in this PR, I would prefer to take that as separate task - it is not regression.
2. I have synchronised dot menu and button as you can see in. recording below:


https://user-images.githubusercontent.com/2182307/207422678-52d604b3-6e39-4a85-a94d-b54f923ef5bd.mov
