### ISSUE TITLE
[Bug]: Setting Spanish locale breaks Privacy Policy links from Privacy Settings

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16837]
### Describe the bug

**Problem**: when I am performing the Onboarding V2 and I land into the Privacy Settings page, if I set the Language to Spanish I see that the 2 Privacy Policy links are broken.

https://user-images.githubusercontent.com/54408225/206194115-a4007355-4c50-41a0-82f0-b72efba4374d.mp4

### Steps to reproduce

1. Enable ONBOARDING_V2
2. Load MM for the first time
3. Go through the Onboarding Process
4. On the Privacy Settings page, set Spanish language

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
This bug has re-appeared again

**Comment by digiwand** [comment]
oops, forgot to link the fix. The subsequent fix for this was merged 3 weeks ago. Closing issue
