### ISSUE TITLE
[Bug]: Onboarding V2 Secret Recovery Phrase backup reminder does not show up

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16836]
### Describe the bug

**Problem**: the Secret Recovery Phrase backup reminder does not show up anymore, when the new account receives some ETH. 

https://user-images.githubusercontent.com/54408225/206171737-3a43d90f-ddc3-4673-ba79-adb1e3aa5f87.mp4

**Expected**:

![Screenshot from 2022-12-07 12-43-34](https://user-images.githubusercontent.com/54408225/206171794-eaf1c5db-a9b1-44b6-8992-27e0bbbd0547.png)

### Steps to reproduce

1. Go through the Onboarding V2 flow with Create new Wallet
2. Select Goerli network
3. From another MM extension, send some ETH to the new account
4. Wait until you receive the ETH -- see how no backup reminder is displayed

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by darkwing** [comment]
The issue is occurring because `seedPhraseBackedUp` is initialized to `null`, and is never set to `false`

<img width="1036" alt="NoBackup" src="https://user-images.githubusercontent.com/46655/206542755-196227f3-70de-4c9f-947d-b12d0c0bdcb6.png">
