### ISSUE TITLE
[Bug]: Broken image appear in the collectibles details view

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#16843]
### Describe the bug

https://user-images.githubusercontent.com/53189696/206219505-58d8f280-0a48-488f-a3e4-5abbec66519f.mov

### Steps to reproduce

1. Build the extension with NFTs enabled
2. Login to the extension
3. Import an NFT with an image hosted on IPFS
4. View the NFT details

Expected result:
Image loads from ipfs similar to on the overview page

Actual result:
Broken image appears on the NFT details page
`ERR_UNKNOWN_URL_SCHEME`

### Version

SHA 8885c54f13735ecc6128b74346e79fb4866f7f7d

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by SUPPORTTEAMHERR** [comment]
> ### Describe the bug
> 
> 
> https://user-images.githubusercontent.com/53189696/206219505-58d8f280-0a48-488f-a3e4-5abbec66519f.mov
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Build the extension with NFTs enabled
> 2. Login to the extension
> 3. Import an NFT with an image hosted on IPFS
> 4. View the NFT details
> 
> Expected result:
> Image loads from ipfs similar to on the overview page
> 
> Actual result:
> Broken image appears on the NFT details page
> `ERR_UNKNOWN_URL_SCHEME`
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> SHA 8885c54f13735ecc6128b74346e79fb4866f7f7d
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
