### ISSUE TITLE
[Bug]: Estimated Gas fee moves to above line depending on its length

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16844]
### Describe the bug

**Problem**: on the Send screen, the estimated gas fee value moves one line above depending on its length

https://user-images.githubusercontent.com/54408225/206219931-50482e88-8f19-4e13-8e7c-b31671add00c.mp4

### Steps to reproduce

1. Unlock MM
2. Click Send
3. Add a Recipient
4. Introduce amount -- observe that when fee updates, the line goes up if the length is too high

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by SUPPORTTEAMHERR** [comment]
> ### Describe the bug
> 
> **Problem**: on the Send screen, the estimated gas fee value moves one line above depending on its length
> 
> 
> https://user-images.githubusercontent.com/54408225/206219931-50482e88-8f19-4e13-8e7c-b31671add00c.mp4
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Unlock MM
> 2. Click Send
> 3. Add a Recipient
> 4. Introduce amount -- observe that when fee updates, the line goes up if the length is too high
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.24.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by jpuri** [comment]
I think this is appropriate behaviour to prevent text from overlapping. @seaona

**Comment by danjm** [comment]
I don't think this should be a blocker for v10.24.0, but designers should review it.

**Comment by bschorchit** [comment]
Comment from Jake [here](https://consensys.slack.com/archives/C021UN08FBJ/p1674093793290089?thread_ts=1674088851.995189&cid=C021UN08FBJ)

> Yeah, I'd call that a papercut. Looks like it’s wrapping backwards. If it wraps the bolded value should be inline with the label and the unbolded value below, pushing the max fee line down.
Also, in the mocks I had it so if it breaks it does not push down the content on the left.
https://www.figma.com/file/NXvUKcZ0Ocu1GPcT7VxRMx/1559---Gas-Controls---v1?node-id=646%3A641&t=Xt5dG68ySnh8zHxb-1
