### ISSUE TITLE
[Bug]: success toast appears even though the NFT is not owned by the user

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#16842]
### Describe the bug

https://user-images.githubusercontent.com/53189696/206218356-368a7e5f-b64b-4770-bcab-ca50be7e5d50.mov

### Steps to reproduce

1. Build the extension with the nft portfolio
2. login the extension
3. Click Import NFTs
4. Enter the contract address `0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D`
5. Enter the token ID `111111`
6. Click Add, `NFT can’t be added as the ownership details do not match. Make sure you have entered correct information.`
8. Update the token ID to `1`
9. Click Add

Expected result:
`NFT can’t be added as the ownership details do not match. Make sure you have entered correct information.`

Actual result:
`Collectible was successfully added!`

### Version

SHA 8885c54f13735ecc6128b74346e79fb4866f7f7d

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by SUPPORTTEAMHERR** [comment]
> ### Describe the bug
> 
> 
> https://user-images.githubusercontent.com/53189696/206218356-368a7e5f-b64b-4770-bcab-ca50be7e5d50.mov
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Build the extension with the nft portfolio
> 2. login the extension
> 3. Click Import NFTs
> 4. Enter the contract address `0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D`
> 5. Enter the token ID `111111`
> 6. Click Add, `NFT can’t be added as the ownership details do not match. Make sure you have entered correct information.`
> 8. Update the token ID to `1`
> 9. Click Add
> 
> Expected result:
> `NFT can’t be added as the ownership details do not match. Make sure you have entered correct information.`
> 
> Actual result:
> `Collectible was successfully added!`
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> SHA 8885c54f13735ecc6128b74346e79fb4866f7f7d
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> 
> https://user-images.githubusercontent.com/53189696/206218356-368a7e5f-b64b-4770-bcab-ca50be7e5d50.mov
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Build the extension with the nft portfolio
> 2. login the extension
> 3. Click Import NFTs
> 4. Enter the contract address `0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D`
> 5. Enter the token ID `111111`
> 6. Click Add, `NFT can’t be added as the ownership details do not match. Make sure you have entered correct information.`
> 8. Update the token ID to `1`
> 9. Click Add
> 
> Expected result:
> `NFT can’t be added as the ownership details do not match. Make sure you have entered correct information.`
> 
> Actual result:
> `Collectible was successfully added!`
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> SHA 8885c54f13735ecc6128b74346e79fb4866f7f7d
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
