### ISSUE TITLE
update 'eth-simple-keyring' to '^5' across the packages 

### ISSUE THREAD

**Issue by cryptodev-2s** [MetaMask/metamask-extension#16841]
We should update this package in the effort of updating/removing ethereumjs-wallet package
![Screenshot 2022-12-07 at 15.08.59.png](https://images.zenhubusercontent.com/631b3300e0d31b35d56f9b5c/477981d4-706f-437e-9330-f0de0a2ec877)
see [#16513](https://github.com/MetaMask/metamask-extension/issues/16513)

**Comment by adonesky1** [comment]
this will be addressed with the completion of https://github.com/MetaMask/metamask-extension/pull/17056
