### ISSUE TITLE
[Bug]: DetectedTokens getting reloaded after it is imported while switching accounts

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#16854]
### Describe the bug

After importing all the tokens from the Detected tokens, if we switch to a different account and return to the old account, we could see the tokens we have already imported as detected tokens. This behavior is observed after the latest assets-controller bump to 3.0.0 and can be reproduced in `optional-currency-conversion`.

### Steps to reproduce

1. For an account with tokens as the detected token, import all the tokens and make sure the detected tokens link disappears.
2. Now, switch to a different account and switch back to the previous account.
3. The detected tokens link will re-appear, and upon opening the pop up it will show the same list of tokens we just imported.

### Version

10.22.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by SUPPORTTEAMHERR** [comment]
> ### Describe the bug
> 
> After importing all the tokens from the Detected tokens, if we switch to a different account and return to the old account, we could see the tokens we have already imported as detected tokens. This behavior is observed after the latest assets-controller bump to 3.0.0 and can be reproduced in `optional-currency-conversion`.
> 
> ### Steps to reproduce
> 
> 1. For an account with tokens as the detected token, import all the tokens and make sure the detected tokens link disappears.
> 2. Now, switch to a different account and switch back to the previous account.
> 3. The detected tokens link will re-appear, and upon opening the pop up it will show the same list of tokens we just imported.
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.22.3
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
