### ISSUE TITLE
[Bug]: `getBalancesInSingleCall` in AssetsContractController throws an error when try to fetch balance for token detection right after onboarding 

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#16855]
### Describe the bug

This bug appeared while using onboarding v2 after bumping assets-controller to 3.0.0.  Currently, this bug can be reproduced in extension feature branch `optional-currency-conversion`

After importing the wallet with token detection turned ON vis privacy settings, the token detection is not happening automatically, and the following error appears on the console. The same error is thrown upon clicking `Refresh List` again.
<img width="786" alt="Screenshot 2022-12-07 at 6 16 24 PM" src="https://user-images.githubusercontent.com/43930900/206317778-31cc80fc-9add-4e59-a5f8-1c8b939fafa1.png">

But if we switch to do any other activity like switching between accounts or toggling token detection, the proper result will be displayed

### Steps to reproduce

1. Enable ONBOARDING_V2 in .metamaskrc. Build and load the application.
2. Import a wallet and enable token detection via privacy settings.
3. Change the network to Mainnet.
4. Check the console for the error.
5. Click the `Refresh List` and recheck the console to see the error displaying again.

### Version

10.22.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
It seems that the error is the same to this one https://github.com/MetaMask/metamask-extension/issues/16774 with regular onboarding

**Comment by SUPPORTTEAMHERR** [comment]
> It seems that the error is the same to this one https://github.com/MetaMask/metamask-extension/issues/16774 with regular onboarding

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by SUPPORTTEAMHERR** [comment]
> ### Describe the bug
> 
> This bug appeared while using onboarding v2 after bumping assets-controller to 3.0.0.  Currently, this bug can be reproduced in extension feature branch `optional-currency-conversion`
> 
> After importing the wallet with token detection turned ON vis privacy settings, the token detection is not happening automatically, and the following error appears on the console. The same error is thrown upon clicking `Refresh List` again.
> <img width="786" alt="Screenshot 2022-12-07 at 6 16 24 PM" src="https://user-images.githubusercontent.com/43930900/206317778-31cc80fc-9add-4e59-a5f8-1c8b939fafa1.png">
> 
> But if we switch to do any other activity like switching between accounts or toggling token detection, the proper result will be displayed
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Enable ONBOARDING_V2 in .metamaskrc. Build and load the application.
> 2. Import a wallet and enable token detection via privacy settings.
> 3. Change the network to Mainnet.
> 4. Check the console for the error.
> 5. Click the `Refresh List` and recheck the console to see the error displaying again.
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.22.3
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
