### ISSUE TITLE
[Bug]: MV3 possibility of DAPP requests being created twice

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#16861]
For MV3 we now have implementation in place to re-run DAPP actions if response is not received for first request. Whenever DAPP streams are resumes and extension background is ready (initially when extension is loaded and also after each service worker re-start) all the pending DAPP actions are replayed. This guarantees that actions that could not be completed due to service worker shutting down are re-executed.

For a DAPP request like submit a transaction or submit a request for signature, it is possible that request is submitted to background and an un-approved transaction is created but response for this could not be sent back to the DAPP before service worker dies. When service worker revives it will try to re-execute this request which can potentially result in 2 un-approved transactions being created in the extension.

We need to made these DAPP related actions also idempotent. This will require I think to figure out all such DAPP related actions which are not idempotent and re-factoring them to be idempotent probably using `request.id` already being passed with each request.

**Comment by jpuri** [comment]
I could replicate edge cases when request is sent multiple times as service worker restart and this filter is added to [filter](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/createDupeReqFilterMiddleware.js) out such requests. But it does not survive service worker restart.

**Comment by AQAqoma** [comment]
> For MV3 we now have implementation in place to re-run DAPP actions if response is not received for first request. Whenever DAPP streams are resumes and extension background is ready (initially when extension is loaded and also after each service worker re-start) all the pending DAPP actions are replayed. This guarantees that actions that could not be completed due to service worker shutting down are re-executed.
> 
> For a DAPP request like submit a transaction or submit a request for signature, it is possible that request is submitted to background and an un-approved transaction is created but response for this could not be sent back to the DAPP before service worker dies. When service worker revives it will try to re-execute this request which can potentially result in 2 un-approved transactions being created in the extension.
> 
> We need to made these DAPP related actions also idempotent. This will require I think to figure out all such DAPP related actions which are not idempotent and re-factoring them to be idempotent probably using `request.id` already being passed with each request.

**Comment by naugtur** [comment]
Where is the un-approved transaction stored while the worker is down?

High-level we have two options I see:
1. Make sure the un-approved transaction is destroyed along with the service worker
2. Create a simple mechanism that'd provide something like a transaction - creating an un-approved transaction assigns a random ID to it and returns in the response. Request to approve must contain ID (or IDs) to approve. Anything else that's in the un-approved storage gets ignored (or cleaned up?)

**Comment by jpuri** [comment]
I think the approach to make methods idempotent may be better. As I could figure out from code we need to make following methods idempotent:

- `processTransaction`
- `processEthSignMessage`
- `processTypedMessage`
- `processTypedMessageV3`
- `processTypedMessageV4`
- `processPersonalMessage`
- `processDecryptMessage`
- `processEncryptionPublicKey`

We can use request id and save it with the objects created in store. Thus if a request is seen again with same request id we can ensure that new request is not created.

**Comment by Gudahtt** [comment]
The same problem applies for any RPC method that generates a confirmation. That would include a few more than those listed,  e.g.  `wallet_addEthereumChain`, `wallet_switchEthereumChain`, `wallet_watchAsset`, `wallet_requestPermissions`, etc.

**Comment by Gudahtt** [comment]
I suspect all non-signing/decryption confirmations are handled by the approval controller.

**Comment by jpuri** [comment]
Closing the issue as all related tasks in the zenhub epic are completed.
