### ISSUE TITLE
Firefox file input closes popup

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1686]
Originally posted here:
https://github.com/MetaMask/faq/issues/38#issuecomment-311509910

**Comment by Zanibas** [comment]
Will write issue to Firefox

**Comment by Zanibas** [comment]
Awaiting a response from Mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1384684

**Comment by tmashuang** [comment]
Closing since there is a workaround by navigating to the extension url in a browser tab to import a file. 
There is no progress on the discussion thread above. 
Other related threads:
https://bugzilla.mozilla.org/show_bug.cgi?id=1292701
https://bugzilla.mozilla.org/show_bug.cgi?id=1411000
