### ISSUE TITLE
[Bug]: What's New button is displayed as link when there are 2 items, and as button when there is 1

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16874]
### Describe the bug

**Problem**: the button for `Security and Privacy Settings` from the What's new prompt is displayed as a link, and when the first item from the What's New is removed, it's then displayed as a Button.

https://user-images.githubusercontent.com/54408225/206544940-a5e7ac7b-7743-4c01-984b-755d485a597c.mp4

### Steps to reproduce

1. Load MM for the first time
2. Go through the Onboarding
3. Land at Home
4. Refresh the page -- see What's New prompt. Security and Privacy is displayed as a link
5. Click to first What's new item for Improved Token allowance
6. Close Settings -- see What's new prompt and Security and Privacy is now displayed as a button

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
This is actually intended. Design spec when we first implemented this feature was to only show the first item as a button and all other items as a link.

**Comment by seaona** [comment]
oh thank you @danjm !!
