### ISSUE TITLE
[FLASK] De-flake snaps E2E tests

### ISSUE THREAD

**Issue by bowensanders** [MetaMask/metamask-extension#16880]
Improvements to the snaps E2E tests need to be made to stop occasional CI failures.

**Comment by anasaboayham** [comment]
hello

**Comment by SUPPORTTEAMHERR** [comment]
> Improvements to the snaps E2E tests need to be made to stop occasional CI failures.

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
