### ISSUE TITLE
[Bug]: Race condition when I can Speed Up a tx after being Confirmed - only UI impact

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16893]
### Describe the bug

**Problem**: after submitting a Send tx, there is a race condition where I can Speed it up even though tx has been already confirmed. You can see the events on the tx details, that after tx is confirmed, tx is resubmitted.

This seems it does not created a 2nd tx but still was possible to perform on the UI without any error.

![image](https://user-images.githubusercontent.com/54408225/206754261-272af187-f24f-4f7d-9ba1-f7828e323d53.png)

### Steps to reproduce

Quite hard to repro, as the Speed up must be done in a small time window, but steps would be:
1. Send tx
2. Wait
3. Before tx is confirmed, speed it up

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by SUPPORTTEAMHERR** [comment]
> ### Describe the bug
> 
> **Problem**: after submitting a Send tx, there is a race condition where I can Speed it up even though tx has been already confirmed. You can see the events on the tx details, that after tx is confirmed, tx is resubmitted.
> 
> This seems it does not created a 2nd tx but still was possible to perform on the UI without any error.
> 
> ![image](https://user-images.githubusercontent.com/54408225/206754261-272af187-f24f-4f7d-9ba1-f7828e323d53.png)
> 
> 
> ### Steps to reproduce
> 
> Quite hard to repro, as the Speed up must be done in a small time window, but steps would be:
> 1. Send tx
> 2. Wait
> 3. Before tx is confirmed, speed it up
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.24.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
