### ISSUE TITLE
Remove special handling of estimateGas when in testing

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/metamask-extension#16896]
### Describe the bug

Specifically this
https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/network/createJsonRpcClient.js#L15

It doesn't seem to have any impact on tests succeeding or failing. Its quite old code now and doesn't seem to be used by anything anymore. 

If it surfaces as an issue in some testing, we should come up with a solution that does not require the implementation code to be significantly modified / mocked out entirely specifically in test settings. This makes our tests overall less useful in catching broken behaviour.

### Steps to reproduce

run the tests

### Version

latest

### Build type

None

### Browser

Chrome, Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by vandan** [comment]
We discovered the reasoning for this implementation. No specific issue caused by this behavior (not great practice for the long-term though).
