### ISSUE TITLE
In the Import Account -> Private Key screen, error messages are confusing and unhelpful

### ISSUE THREAD

**Issue by HowardBraham** [MetaMask/metamask-extension#16895]
There are three types of error messages you can get when on the Import Account -> Private Key screen, and all of them are confusing and unhelpful.  The third error message was reported by CS, but nobody has figured out how to reproduce it yet.

![image](https://user-images.githubusercontent.com/539738/206782352-d3ebce31-d90d-42e1-88e7-8ed789708598.png)

![image](https://user-images.githubusercontent.com/539738/206782243-f8a479fb-afd5-4249-b732-d65d0ea76152.png)

![METAMASK](https://user-images.githubusercontent.com/539738/206782702-2e1e1d3b-d55d-4fdc-ab86-5a707a959562.png)

**Comment by WalletSupportt** [comment]
> There are three types of error messages you can get when on the Import Account -> Private Key screen, and all of them are confusing and unhelpful.  The third error message was reported by CS, but nobody has figured out how to reproduce it yet.
> 
> ![image](https://user-images.githubusercontent.com/539738/206782352-d3ebce31-d90d-42e1-88e7-8ed789708598.png)
> 
> ![image](https://user-images.githubusercontent.com/539738/206782243-f8a479fb-afd5-4249-b732-d65d0ea76152.png)
> 
> ![METAMASK](https://user-images.githubusercontent.com/539738/206782702-2e1e1d3b-d55d-4fdc-ab86-5a707a959562.png)
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by AlexJupiter** [comment]
Sync with @holantonela needed and also cross-check with mobile.

**Comment by AlexJupiter** [comment]
Sync with @holantonela needed and also cross-check with mobile.
