### ISSUE TITLE
Use createScaffoldMiddleware in createJsonRpcClient

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/metamask-extension#16897]
### Describe the bug

createInfuraClient hard-codes the network and chainid via `createScaffoldMiddleware`, whereas createJsonRpcClient has its own code for chain id. 

specifically this: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/network/createJsonRpcClient.js#L40

should look more like: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/network/createInfuraClient.js#L45

### Steps to reproduce

theres no bug, its just best to make these 2 functions more aligned in how they function

### Version

latest

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by xinnanyemm** [comment]
Please note that `label:team-dapp-api` has been replaced by `label:team-devex` . Thanks.

**Comment by BelfordZ** [comment]
Things have changed quite a bit since this was created. I will close this issue in favor of a new one in the correct place:
https://github.com/MetaMask/core/issues/3778
