### ISSUE TITLE
[Bug]: Firefox dapp stops working without proper error message after extension is refreshed or reinstalled during a dapp session

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#16909]
### Describe the bug

Currently, when restarting or updating the extension during a dapp session, the dapp will stop working without proper error messages.

In FireFox, the following warning messages are shown during this incident.
![image](https://user-images.githubusercontent.com/20778143/207042383-e8079e41-d10e-42ab-a30c-47129ac56263.png)

When this incident occurs, we want to inform the user that they should restart the page in order for the dapp to work again. 

We have handled this incident for chromium based browsers (PR: https://github.com/MetaMask/metamask-extension/pull/16306). We would like to handle this for FireFox as well. 

### Steps to reproduce

1. Launch extension in FireFox
2. Open dapp
3. Open extension add-ons in FireFox
4. Reinstall or update the MetaMask extension
5. Observe that the dapp is no longer working
6. Observe error message does not provide 

### Version

10.23.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> Currently, when restarting or updating the extension during a dapp session, the dapp will stop working without proper error messages.
> 
> In FireFox, the following warning messages are shown during this incident.
> ![image](https://user-images.githubusercontent.com/20778143/207042383-e8079e41-d10e-42ab-a30c-47129ac56263.png)
> 
> When this incident occurs, we want to inform the user that they should restart the page in order for the dapp to work again. 
> 
> We have handled this incident for chromium based browsers (PR: https://github.com/MetaMask/metamask-extension/pull/16306). We would like to handle this for FireFox as well. 
> 
> 
> ### Steps to reproduce
> 
> 1. Launch extension in FireFox
> 2. Open dapp
> 3. Open extension add-ons in FireFox
> 4. Reinstall or update the MetaMask extension
> 5. Observe that the dapp is no longer working
> 6. Observe error message does not provide 
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.23.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Firefox
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
