### ISSUE TITLE
Add unit tests for token allowance

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16910]
It seems that currently token-allowance has 0% test coverage, we should create and add unit tests for it.

**Comment by FractosOiluj** [comment]
Hello. Sorry the dumb question but where can i learn how build and integrate unit tests for token allowance ?

**Comment by WalletSupportt** [comment]
> Hello. Sorry the dumb question but where can i learn how build and integrate unit tests for token allowance ?

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
