### ISSUE TITLE
github-actions bot locked and limited conversation to collaborators

### ISSUE THREAD

**Issue by EresDev** [MetaMask/metamask-extension#16914]
### Describe the bug

I have submitted a pull request https://github.com/MetaMask/metamask-extension/pull/16898
I was asked by @danjm to do it differently, but the GitHub action bot has locked the conversation and I can't even reply to him. And I don't see a way to unlock it. 
Please fix this. 

### Steps to reproduce

1. Go to https://github.com/MetaMask/metamask-extension/pull/16898
You will see 

![image](https://user-images.githubusercontent.com/11886219/207103531-7d4a0ab2-c0cd-4ee4-b653-7c0afb12839c.png)

And if you are not a contributor

![image](https://user-images.githubusercontent.com/11886219/207103593-85aea38d-4f40-4667-9670-95835ee4b666.png)

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by Gudahtt** [comment]
Sorry, we did not notice the PR was locked. It gets locked automatically upon close.

**Comment by zong-zhe** [comment]
Hi @Gudahtt 😄 This is a request for help, may I ask how do you disable this lock, I can't find effective documentation to solve this problem.
