### ISSUE TITLE
Add tests for methods defined in the Ethereum spec that are not supported by Infura

### ISSUE THREAD

**Issue by mcmire** [MetaMask/metamask-extension#16938]
This is a followup to #15556, where tests were added to exercise the RPC methods that are supported by middleware added via `eth-json-rpc-infura` (and consequently middleware listed in Infura's documentation). However, there are a number of RPC methods that, for some reason, are listed in the official Ethereum JSON-RPC API documentation that are _not_ supported by Infura, and we should make sure those aren't being handled specially.

(Context: https://github.com/MetaMask/metamask-extension/pull/15556#discussion_r967231963)

**Comment by WalletSupportt** [comment]
> This is a followup to #15556, where tests were added to exercise the RPC methods that are supported by middleware added via `eth-json-rpc-infura` (and consequently middleware listed in Infura's documentation). However, there are a number of RPC methods that, for some reason, are listed in the official Ethereum JSON-RPC API documentation that are _not_ supported by Infura, and we should make sure those aren't being handled specially.
> 
> (Context: https://github.com/MetaMask/metamask-extension/pull/15556#discussion_r967231963)

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
