### ISSUE TITLE
[Bug]: [MV3] When I stop the service worker I am logged out and I get the error `Uncaught (in promise) TypeError: Keyring is not a constructor`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16936]
### Describe the bug

**Problem**: when service worker is stopped, I am logged out from MetaMask.

https://user-images.githubusercontent.com/54408225/207333882-9da001dc-8c91-47c1-ad95-02ddbbf415c5.mp4

https://user-images.githubusercontent.com/54408225/207333912-61377b22-46cc-4459-9c86-fdb07a5b036d.mp4

When I log in again I see the error `Uncaught (in promise) TypeError: Keyring is not a constructor`

![image](https://user-images.githubusercontent.com/54408225/207357486-04c81674-0e19-4859-b3a0-0fd720cd8b72.png)

### Steps to reproduce

Procedure can be made both with popup and full view:

1. Start MV3 build `yarn start:mv3`
2. Onboard to MM
3. Land at Home page
4. Kill the service worker and wait -- you are logged out

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> **Problem**: when service worker is stopped, I am logged out from MetaMask.
> 
> https://user-images.githubusercontent.com/54408225/207333882-9da001dc-8c91-47c1-ad95-02ddbbf415c5.mp4
> 
> 
> https://user-images.githubusercontent.com/54408225/207333912-61377b22-46cc-4459-9c86-fdb07a5b036d.mp4
> 
> 
> When I log in again I see the error `Uncaught (in promise) TypeError: Keyring is not a constructor`
> 
> ![image](https://user-images.githubusercontent.com/54408225/207357486-04c81674-0e19-4859-b3a0-0fd720cd8b72.png)
> 
> ### Steps to reproduce
> 
> Procedure can be made both with popup and full view:
> 
> 1. Start MV3 build `yarn start:mv3`
> 2. Onboard to MM
> 3. Land at Home page
> 4. Kill the service worker and wait -- you are logged out
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.24.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by segun** [comment]
> This might be resolved by #16725

@danjm  This PR didn't resolve the issue.

**Comment by danjm** [comment]
This is now fixed on develop.

Fixed with #17354 and #15558

**Comment by seaona** [comment]
Was this issue resolved? I've double-checked again and I am still logged out after service worker re-start. The console error does not appear anymore but I am still logged out. Or maybe the bug re-surfaced? 

@danjm @pedronfigueiredo 

https://user-images.githubusercontent.com/54408225/221137100-987c4a61-5b12-425c-83c9-20979050535f.mp4
