### ISSUE TITLE
NetworkController API normalization: Replace EventEmitter with controller messenger

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#16945]
The network controller currently extends EventEmitter as a way of emitting network-related events. We should stop extending EventEmitter, instead using the controller messenger for emitting events.

This is part of [a larger effort to normalize the API of both network controllers](https://github.com/MetaMask/controllers/issues/971), to make them easier to merge.

**Comment by mcmire** [comment]
Moving this back to backlog as I need to get through another task before coming back to this.
