### ISSUE TITLE
[Bug]: Onboarding V2 - User skips `pin extension` tutorial and is taken to the import token screen during onboarding 

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#16957]
### Describe the bug

https://user-images.githubusercontent.com/53189696/207701737-85cb7745-23b1-4142-ba10-6235dd816a80.mov

The user does not get to go through the `pin extension step` of onboarding and lands straight in the import token flow

### Steps to reproduce

1. Install the extension with ONBOARDING_V2 enabled
2. Import an existing wallet
3. Enter the Advanced configuration modal
4. Add a custom network - Polygon
5. Proceed the final step of onboarding
6. Click the `Click here to manually add the tokens` link on the network switched model 

### Version

10.24

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jpuri** [comment]
This was an intermittent issue but its fixed in latest code.
