### ISSUE TITLE
Add New Contact, the Username field should be mandatory

### ISSUE THREAD

**Issue by ElvirCe** [MetaMask/metamask-extension#16954]
If the user want to save an address currently they go to Settings - Contacts - Add Contact and they can enter the address and save the contact. We want the field 'Username" to be mandatory so that if the user wants to save an address they also must enter a username for that address. 

**Acceptance Criteria:** 
- Disable the save button on the add contact form if the Username and Ethereum public address fields are empty. 
- The "Username" field should include validation for: Prevent users from setting usernames that are fully blank (only spaces like: or ). Use of special characters, letters and numbers are fine and also no need to set a min or max size for the username.
- Once both fields have been populated the "Save" button should be enabled and users can save the address 

![Image](https://user-images.githubusercontent.com/98470173/207623315-320b4124-b27d-42a9-8cc0-8e82134444c6.png)

**Comment by ElvirCe** [comment]
Open item: @bschorchit will check with the designers regarding the Username field validation rules and advise.

**Comment by bschorchit** [comment]
re: validation rule - we just want to prevent users from setting usernames that are fully blank (only spaces like: ` `  or `       `).  Use of special caracters and numbers are fine and also no need to set a min or max size for the username.

**Comment by bschorchit** [comment]
@georgewrmarshall is going to add more details here related to updating this to use a different component and ensuring accessibility of this form. These should slightly affect this ticket's acceptance criteria.

**Comment by georgewrmarshall** [comment]
I just tried replacing some of the components myself and think it might be out of the scope of this ticket. The `<DomainInput/>` component is used in other places so would warrant thorough testing. I'll create the tickets individually. Thanks for being open to the updates though 🙏
