### ISSUE TITLE
[Bug]: Interacting with a Verified Contract displays booleans variables as objects

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16950]
### Describe the bug

**Problem**: when I am interacting with a Verified Contract I can see that the boolean types are displayed as objects instead of displaying just the result. I.e. `{ result: { asBoolean: true } }`

![verified-contract-bool](https://user-images.githubusercontent.com/54408225/207580819-a24c64a6-b11a-4c9f-818b-6e88512acc9a.png)

### Steps to reproduce

1. Set Goerli network
2. Go to the contract https://goerli.etherscan.io/address/0xcf21e74221443eda1d3313b7b46b4650761aeeda#writeContract
3. Click on Write Contract
4. Click Connect for connecting MM
5. Click `checkBool`
6. Fill the values
7. Click Write
8. Click on the DATA tab from MetaMask prompt -- see boolean values

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This may be the same as https://github.com/MetaMask/metamask-extension/issues/14383

**Comment by seaona** [comment]
Update: booleans are now returning always `undefined`

![image](https://user-images.githubusercontent.com/54408225/213177026-79564b51-e3c6-478d-b7f7-5bde07aa687a.png)
