### ISSUE TITLE
[Bug]: Scrolling on the Account list turns the font into bold for some elements during some seconds, with Batch Accounts disabled

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16969]
### Describe the bug

**Problem**: when I scroll into my Account list, I can see that some text is transformed into bold during some seconds, while having Batch Accounts functionality disabled.

https://user-images.githubusercontent.com/54408225/207834816-c07d07f0-6abd-4d91-ad97-229386963cca.mp4

### Steps to reproduce

1. Unlock MM
2. Create several Accounts, so you can have a long list for scrolling
3. Go to Privacy Settings
4. Disable Batch Accounts
5. Log out from MM
6. Log in again
7. Open Account menu
8. Scroll -- see how some text is transformed in bold

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
@seaona : I am not able to replicate this, nor could I find bold style ever applied to account name in extension. I guess this issue is with with browser is handling scrolling in this case.

**Comment by darkwing** [comment]
That seems like an OS issue to be honest, shouldn't be a coding issue.
