### ISSUE TITLE
0 doesn't work for bounding box values for Box component

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#16976]
### Description
The value `0` doesn't work for box because there is a boolean check before running the `generateClassnames` function.

**Comment by WalletSupportt** [comment]
> ### Description
> The value `0` doesn't work for box because there is a boolean check before running the `generateClassnames` function.
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
