### ISSUE TITLE
[Bug]: Incoming Transactions not displayed on Goerli/Sepolia

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16972]
### Describe the bug

**Problem**: Incoming Transactions are not displayed on Goerli or Sepolia while having the feature enabled on Prviacy Settings. No matter if I refresh MM, login and logout etc.

This needs further investigation on the affectation (tested once on Mainnet and tx appeared). 

For now I include the issue in the 10.24.0 Milestone, until some more findings clarify whether is an issue and if it was introduced on 10.24.0.

https://user-images.githubusercontent.com/54408225/207849891-895b6f69-eeb5-44f6-8b0e-0ac5018a72a4.mp4

### Steps to reproduce

1. Unlock MM
2. Make sure Incoming Transactions functionality is enabled on Privacy Settings
3. Send ETH to another account
4. Change to the other account
5. Wait -- no Incoming Transaction is displayed
6. Refresh MM -- no Incoming Transaction is displayed
7. Logout and Login again -- no Incoming Transaction is displayed

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I think this feature has always been only available on Mainnet, no?

**Comment by seaona** [comment]
Sepolia and Goerli should be supported (verified on 10.23.0 I didn't have issues). I've noticed that after some refreshes **sometimes** the transaction appears, but most of the times not. I suspect it might have something to do with the "Batch Account" toggle introduced recently, but I am not 100% @bschorchit 

![image](https://user-images.githubusercontent.com/54408225/207875841-9c31b504-5f85-4281-bc0b-fd4ced0164fa.png)

**Comment by jpuri** [comment]
Hey @seaona : I tested an old commit `89ee4d4a4ea50d93fec2661dfc9febc86b750df2` and I could replicate this issue. I debugged this in code and this does not seems to be issue on metamask side.

Since it works well in mainnet confirms this. This might be issue with the etherscan api that we are using.

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> **Problem**: Incoming Transactions are not displayed on Goerli or Sepolia while having the feature enabled on Prviacy Settings. No matter if I refresh MM, login and logout etc.
> 
> This needs further investigation on the affectation (tested once on Mainnet and tx appeared). 
> 
> For now I include the issue in the 10.24.0 Milestone, until some more findings clarify whether is an issue and if it was introduced on 10.24.0.
> 
> https://user-images.githubusercontent.com/54408225/207849891-895b6f69-eeb5-44f6-8b0e-0ac5018a72a4.mp4
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Unlock MM
> 2. Make sure Incoming Transactions functionality is enabled on Privacy Settings
> 3. Send ETH to another account
> 4. Change to the other account
> 5. Wait -- no Incoming Transaction is displayed
> 6. Refresh MM -- no Incoming Transaction is displayed
> 7. Logout and Login again -- no Incoming Transaction is displayed
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.24.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by WalletSupportt** [comment]
> I think this feature has always been only available on Mainnet, no?

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by WalletSupportt** [comment]
> Sepolia and Goerli should be supported (verified on 10.23.0 I didn't have issues). I've noticed that after some refreshes **sometimes** the transaction appears, but most of the times not. I suspect it might have something to do with the "Batch Account" toggle introduced recently, but I am not 100% @bschorchit 
> 
> ![image](https://user-images.githubusercontent.com/54408225/207875841-9c31b504-5f85-4281-bc0b-fd4ced0164fa.png)
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by WalletSupportt** [comment]
> Hey @seaona : I tested an old commit `89ee4d4a4ea50d93fec2661dfc9febc86b750df2` and I could replicate this issue. I debugged this in code and this does not seems to be issue on metamask side.
> 
> Since it works well in mainnet confirms this. This might be issue with the etherscan api that we are using.
> 
> I face issue if I enable / disable batch account toggle.

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by seaona** [comment]
It seems that most of the times we are receiving empty responses from Etherscan:

https://user-images.githubusercontent.com/54408225/208481106-728e81f7-f60f-4b0e-be50-d747174efe41.mp4


On the other hand, when we receive a right response data, it takes roughly 20 seconds to render the data on MM. This seems a different issue though - but re-inforces the result of not seeing Incoming Transactions:

https://user-images.githubusercontent.com/54408225/208481124-d83ad9cb-903b-4b98-80c7-a1a9d7644880.mp4

**Comment by jpuri** [comment]
I could not replicate the issue of delayed rendering, it works well for me:


https://user-images.githubusercontent.com/2182307/208671980-c97a18f7-56db-4e8f-a74d-56a3e5e550df.mov
