### ISSUE TITLE
Make request to watch asset idempotent

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#16971]

**Comment by coolgye** [comment]
小狐狸这个会发币吗

**Comment by WalletSupportt** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by jpuri** [comment]
I found that it is highly unlikely that token can not be added to `TokenController.suggestedAssets` twice and thus it is not likely for token approval page to be show twice for watch token request.

Seems explicit code changes are not needed to fix this issue.
