### ISSUE TITLE
[Bug]: MM popup is not closed after completing Adding a Token action from MM full width

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16984]
### Describe the bug

**Problem**: when I am importing a token from a Dapp, if I accept the action within the MM full window, the popup remains open and I have to close it manually.

https://user-images.githubusercontent.com/54408225/208140235-a882094a-4f9a-4f38-b987-82e40f2d0eb8.mp4

I am expecting the same behaviour as when we do this with a transaction - popup is closed once the action is performed.

https://user-images.githubusercontent.com/54408225/208140588-391f555b-9591-40d2-beda-8e0a82985d24.mp4

### Steps to reproduce

0. Open MM full view on one tab
1. Go to test dapp https://metamask.github.io/test-dapp/ on another tab
2. Connect MM
3. Click Create Token
4. Accept MM tx
5. Click Add token to Wallet
6. Go to MM full width
7. Accept Add token there -- see MM popup remains open

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> **Problem**: when I am importing a token from a Dapp, if I accept the action within the MM full window, the popup remains open and I have to close it manually.
> 
> https://user-images.githubusercontent.com/54408225/208140235-a882094a-4f9a-4f38-b987-82e40f2d0eb8.mp4
> 
> I am expecting the same behaviour as when we do this with a transaction - popup is closed once the action is performed.
> 
> https://user-images.githubusercontent.com/54408225/208140588-391f555b-9591-40d2-beda-8e0a82985d24.mp4
> 
> 
> 
> ### Steps to reproduce
> 
> 0. Open MM full view on one tab
> 1. Go to test dapp https://metamask.github.io/test-dapp/ on another tab
> 2. Connect MM
> 3. Click Create Token
> 4. Accept MM tx
> 5. Click Add token to Wallet
> 6. Go to MM full width
> 7. Accept Add token there -- see MM popup remains open
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.24.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
