### ISSUE TITLE
Fix bug where phishing warning is not displayed when opening a reported site in all browsers

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#16989]
## Background
This is a bug @ElvirCe and I noticed when going over https://github.com/MetaMask/metamask-extension/issues/16602

## Acceptance criteria
1. Phishing warning page is displayed on all browser (chrome, brave, firefox and edge) when user tries to open a website that has been reported as phishing

## Steps to reproduce
1. Go to a reported bad domain (some examples [here](https://github.com/MetaMask/eth-phishing-detect/pull/9813/files)) - be careful as those have been reported as malicious sites so you don't want to actually connect your MetaMask wallet or perform any transaction or signature on those websites
2. Notice the MetaMask phishing-warning page being displayed in some but not all browsers (in my case, it was displayed in Brave, but not in Chrome)

**Comment by seaona** [comment]
@bschorchit in which version is this repro?

**Comment by danjm** [comment]
@bschorchit Does it work if you try the urls from this list with v10.23.1 on chrome? https://github.com/MetaMask/eth-phishing-detect/pull/9984

**Comment by danjm** [comment]
and if not, might you have the feature toggled off in chrome?

**Comment by bschorchit** [comment]
Ok, the MM I was using on Chrome was a dev build. I've re-tested with the prod build in Chrome (10.23.1) and it's working as expected :) My bad for the fake news here 😅

I'm still able to reproduce it on Firefox though.

https://user-images.githubusercontent.com/34968356/208727454-9a9f6a90-1b51-40a2-b39b-9dcc37fe54cd.mov

**Comment by PeterYinusa** [comment]
The Codefi team implemented a server side fix to ensure the access control headers (`access-control-allow-origin` and `access-control-expose-headers`) are returned when requesting the resources at [https://static.metafi.codefi.network/api/v1/lists/phishfort_hotlist.json](https://static.metafi.codefi.network/api/v1/lists/phishfort_hotlist.json).

A client side fix was also implemented here #17029
