### ISSUE TITLE
Can't cancel, fix or remove error: "There was a problem loading your token balances."

### ISSUE THREAD

**Issue by pinheadmz** [MetaMask/metamask-extension#1698]
I'm playing with the truffle webpack sample contract "MetaCoin" and tried to import that contract as a token into MetaMask. I think whats happening is, MetaCoin is not ERC20 so MetaMask errors out trying to load balances (see log below). Unfortunately there does not appear to be a way to _remove_ or attempt to fix a "broken token" from MetaMask. I'm stuck with this error... forever?

```
failed to load balance for token at 0xb694546b4030e31fb7f8c4e3d9e8eee89bf3fada
updateValue @ popup.js:25916
popup.js:81048 Error: [ethjs-rpc] rpc error with payload {"id":7101404402339,"jsonrpc":"2.0","params":[{"to":"0xb694546b4030e31fb7f8c4e3d9e8eee89bf3fada","data":"0x70a0823100000000000000000000000071471afa32e0fedfdb16e5cc3425af259a375893"},"latest"],"method":"eth_call"} null
    at popup.js:29232
    at popup.js:74170
TokenList.render @ popup.js:81048

popup.js:81048 Error: [ethjs-rpc] rpc error with payload {"id":6982397503581,"jsonrpc":"2.0","params":[{"to":"0xb694546b4030e31fb7f8c4e3d9e8eee89bf3fada","data":"0x70a0823100000000000000000000000071471afa32e0fedfdb16e5cc3425af259a375893"},"latest"],"method":"eth_call"} null
    at popup.js:29232
    at popup.js:74170
TokenList.render @ popup.js:81048
popup.js:29232 Uncaught (in promise) Error: [ethjs-rpc] rpc error with payload {"id":6982397503581,"jsonrpc":"2.0","params":[{"to":"0xb694546b4030e31fb7f8c4e3d9e8eee89bf3fada","data":"0x70a0823100000000000000000000000071471afa32e0fedfdb16e5cc3425af259a375893"},"latest"],"method":"eth_call"} null
    at popup.js:29232
    at popup.js:74170
```

**Comment by flyswatter** [comment]
I don't believe those errors are preventing the view from loading. That view ignores invalid tokens. You seem to be having other network issues, it may be Infura.

Have you tried with a local node, like testrpc?

**Comment by pinheadmz** [comment]
Sorry I should have included, I was only using testrpc with [`truffle init webpack`](https://github.com/trufflesuite/truffle-init-webpack) (the little demo example). The MetaCoin web UI worked fine and sent transactions on the test blockchain. I was just experimenting  with loading the MetaCoin contract into MetaMask but I don't think it works because the [MetaCoin contract ](https://github.com/trufflesuite/truffle-init-webpack/blob/master/contracts/MetaCoin.sol#L31) `getBalance`  doesn't match [the ERC20 specified](https://github.com/ethereum/EIPs/issues/20) `balanceOf`. And I only think that because of the console errors:

`popup.js:81048 Error: [ethjs-rpc] rpc error with payload {"id":7101404402339,"jsonrpc":"2.0","params":[{"to":"0xb694546b4030e31fb7f8c4e3d9e8eee89bf3fada","data":"0x70a0823100000000000000000000000071471afa32e0fedfdb16e5cc3425af259a375893"},"latest"],"method":"eth_call"} null
`


(see https://www.4byte.directory/signatures/?bytes4_signature=70a08231)

...either way, there is no way to clear the "problem loading" error or stop MetaMask from attempting the above call every time the view refreshes.

**Comment by rstormsf** [comment]
I can confirm the issue. The view is completely blocking the loading and I'm not able to view any other tokens

**Comment by rstormsf** [comment]
![screen shot 2017-06-29 at 5 18 48 pm](https://user-images.githubusercontent.com/9360827/27715892-31bde71c-5cef-11e7-92d8-c7589382697a.png)

**Comment by rstormsf** [comment]
error div takes the whole container's view, so no doubt it prevents to show other tokens

**Comment by kumavis** [comment]
@rstormsf you're having a different issue - seems like your local node is not responding (my guess is testrpc crashed per your other issue)

**Comment by kumavis** [comment]
im seeing the request go thru ok but maybe ethjs-rpc doesnt like the `0x` result - or theres a 5xx http error from infura shedding load

```
$ curl -d '{"id":7101404402339,"jsonrpc":"2.0","params":[{"to":"0xb694546b4030e31fb7f8c4e3d9e8eee89bf3fada","data":"0x70a0823100000000000000000000000071471afa32e0fedfdb16e5cc3425af259a375893"},"latest"],"method":"eth_call"}' https://mainnet.infura.io
{"jsonrpc":"2.0","id":7101404402339,"result":"0x"}
```

**Comment by Zanibas** [comment]
Need QA on this to affirm it's still an issue. @tmashuang ?

**Comment by okwme** [comment]
I still have this issue running testrpc which is otherwise running normally.
I added an incorrect contract address and all previous tokens are not visible.
no action available to add new token (or remove current broken token)

**Comment by drreen** [comment]
I have same issue on Firefox on macOS Sierra. Chrome works fine

**Comment by pizzamx** [comment]
same here with Chrome on Windows 10

**Comment by dimitar-petrov** [comment]
Guys, is there a work around for this issue.
I cannot list my tokens on both chrome and firefox.

**Comment by flyswatter** [comment]
This morning's issue is related to backend overload, and it will be fixed soon, but you can work around it by running a local node. https://consensyssupport.happyfox.com/staff/kb/article/2-using-a-local-node/

**Comment by fightfear** [comment]
I also have an issue. I just participated in an ICO and can't view any of my tokens now. I keep getting the following error:
_"There was a problem loading your token balances."_
Can you confirm that you are aware of this issue and let me know when it is likely to be resolved please? It's quite important for me to get access back ASAP, so I would really appreciate your help

**Comment by flyswatter** [comment]
I can confirm that. You can still check your token balance on Etherscan if you are concerned.

**Comment by fightfear** [comment]
Thank you for taking your time to reply

**Comment by flyswatter** [comment]
We've mitigated this for the time being by including a link to an alternate token viewing site when our token list is down.

**Comment by uworld66** [comment]
Doesn't do you much good to be able to check token balances on etherscan as you can not get to them. Cant move them or access them in any way shape or form.

**Comment by flyswatter** [comment]
Here's our current guide on managing tokens in MetaMask: http://metamask.consensyssupport.happyfox.com/kb/article/4-managing-tokens 

In it you will find instructions on sending tokens, which does not involve our token list at the moment.

**Comment by steven0610** [comment]
Here's also a problem,console log :Uncaught (in promise) Error: [ethjs-rpc] rpc error with payload {"id":7906040246739,"jsonrpc":"2.0","params":[{"from":"0x1ca663370c20706ba1ac04e47a946bceef7cd83a","to":"0x0bd7b04d7675a0a268910c2a3f7ac77eaf3d4e1b","value":"0xde0b6b3a7640000","gas":"0x6170d4","gasPrice":"0x4a817c800"}],"method":"eth_estimateGas"} Error: VM Exception while processing transaction: invalid JUMP at 2c16f120809957031c7b12a4533d41cf8f309bef58bb705f5c3b3c7680064f13.

The account has enough eth.

**Comment by liyuechun** [comment]
app.js:20756 Uncaught (in promise) Error: Error: [ethjs-rpc] rpc error with payload {"id":9205746185928,"jsonrpc":"2.0","params":["0xf902ac808504a817c80082abe094345ca3e014aaf5dca488057592ee47305d9b3e1080b90244a508b95500000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000

**Comment by rectsuly** [comment]
Uncaught (in promise) Error: Error: Error: [ethjs-rpc] rpc error with payload {"id":5119868008698,"jsonrpc":"2.0","params":["0xf8eb04843b9aca008301f75b94345ca3e014aaf5dca488057592ee47305d9b3e1080b8844ed3885e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002e516d536e34466670426d6a7169336a3544515254354566756a734562654e6e343870546754775962517a723144350000000000000000000000000000000000008222e1a0afe6f697af2cddfd404f0842cadca06dee5b9d5664fca3476f0566d461588b0ba00647e3df7a5d347ce1398916df08e89c000f5b4a1d498a68874d25a6721f0b71"],"method":"eth_sendRawTransaction"} Error: Error: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 4

**Comment by kennblvnp** [comment]
still happening

**Comment by kennblvnp** [comment]
@bdresser  Yeah, I just needed to dig deeper. I learned a lot and now I know how to get around that. You are right. Thanks! This isn't happening to me anymore.
