### ISSUE TITLE
[Bug]: Adding Multiple Tokens at once causes duplicated screens for already added token

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16986]
### Describe the bug

**Problem**: when I want to Add multiple tokens at the same time, I can see that the window presents the list of tokens together, and if I click `Add Token` (Token should be plural?) all tokens are added, but then a new window for adding a Token appears with the first token from the list (already added).

https://user-images.githubusercontent.com/54408225/208145726-f0f7665f-4e3c-4519-bd8f-84d8de0ffa64.mp4

### Steps to reproduce

0. On one tab, open MM full witdth
1. Click Add token from https://www.coingecko.com/en/coins/hipenguins
2. Cllick Add token from https://etherscan.io/token/0x75231f58b43240c9718dd58b4967c5114342a86c
3. Switch to MM full width -- 2 tokens are there
4. Click Add Token --2 tokens are added, a new window for Add Token is displayed with the first token (already added)

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> **Problem**: when I want to Add multiple tokens at the same time, I can see that the window presents the list of tokens together, and if I click `Add Token` (Token should be plural?) all tokens are added, but then a new window for adding a Token appears with the first token from the list (already added).
> 
> 
> https://user-images.githubusercontent.com/54408225/208145726-f0f7665f-4e3c-4519-bd8f-84d8de0ffa64.mp4
> 
> 
> 
> ### Steps to reproduce
> 
> 0. On one tab, open MM full witdth
> 1. Click Add token from https://www.coingecko.com/en/coins/hipenguins
> 2. Cllick Add token from https://etherscan.io/token/0x75231f58b43240c9718dd58b4967c5114342a86c
> 3. Switch to MM full width -- 2 tokens are there
> 4. Click Add Token --2 tokens are added, a new window for Add Token is displayed with the first token (already added)
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.24.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
