### ISSUE TITLE
Snaps delineator™

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#16999]
Component and pattern to delineate third party UI within MetaMask. To achieve this, we're introducing the **Snaps delineator™** to wrap third party UI within MetaMask consistently. Here's the [latest design](https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-components?node-id=17%3A7374&t=rf0HDawwUO0wuk7n-1).

Context by @rekmarks;
> Establishing a clear distinction between data coming from MetaMask itself and from snaps is critical to ensure that snaps are safe to use, especially as snaps are more deeply integrated into to MetaMask UI.
> 
> This needs to be solved systemically via the design system, not on a case-by-case basis.

**Comment by firnprotocol** [comment]
sorry if this is not the right place for this—but can I ask, are snaps still under development? is there a reasonable expectation that they'll eventually be merged into mainstream production metamask within a reasonable amount of time?

just hoping for clarity—i'm a developer interested in implementing a snap. thanks in advance.
