### ISSUE TITLE
Authorship component

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#16997]
Used for displaying the snaps’ authorship in a consistent way across our screens. Here's the current design.

Currently displayed during **installation**, **update**, **error**, and **custom dialog** screens coming from the snap. See how it would work in context [here](https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-components?node-id=8%3A5735&t=rf0HDawwUO0wuk7n-1).

**Comment by eriknson** [comment]
Latest design [here](https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-components?node-id=8%3A2097&t=rf0HDawwUO0wuk7n-1).

**Comment by Montoya** [comment]
Will talk to DS team and provide them an interface to build the component

**Comment by eriknson** [comment]
Review of [latest design](https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-features?node-id=145%3A29864&t=wZKNtj8aQw65CEH6-1) together with the DS team done.

**Comment by eriknson** [comment]
Design for this is [done](https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-features?node-id=55%3A14656&t=76MflkaKOJtdI5VK-1). 

Closing this issue in favor of a wider petname effort which will evolve this component going forward.
