### ISSUE TITLE
[Bug]: Token Detection is called before token list fetch when `Enhanced Token Detection` toggle is turned ON

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#16991]
### Describe the bug

When we turn on when `Enhanced Token Detection` toggle, the `detectNewToken()` function for token detection is called before the `fetchTokenList()` in TokenListController, this causes the token detection to happen on an empty list or the expired static list, which results in no token detection happening or tokens from the expired list getting detected.

### Steps to reproduce

1. In console place breakpoints in `detectNewToken()` and `fetchTokenList()`.
2. Now go to settings and search for `Enhanced Token Detection`, and toggle in ON.
3. The breakpoint in  `detectNewtoken()` will be hit first, and then the breakpoint in `fetchTokenList().` 

### Version

10.23.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by WalletSupportt** [comment]
> ### Describe the bug
> 
> When we turn on when `Enhanced Token Detection` toggle, the `detectNewToken()` function for token detection is called before the `fetchTokenList()` in TokenListController, this causes the token detection to happen on an empty list or the expired static list, which results in no token detection happening or tokens from the expired list getting detected.
> 
> ### Steps to reproduce
> 
> 1. In console place breakpoints in `detectNewToken()` and `fetchTokenList()`.
> 2. Now go to settings and search for `Enhanced Token Detection`, and toggle in ON.
> 3. The breakpoint in  `detectNewtoken()` will be hit first, and then the breakpoint in `fetchTokenList().` 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.23.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by seaona** [comment]
Is this the same/related to https://github.com/MetaMask/metamask-extension/issues/16774 @NiranjanaBinoy ?
