### ISSUE TITLE
[Bug]: Changing to Goerli network causes insufficient error despite having enough funds

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#17002]
### Describe the bug

After changing the network and with sufficient funds, I see the insufficient error and cannot send tokens. I am observing this on Goerli. It does not appear to happen with the Sepolia network
<img width="657" alt="Screen Shot 2022-12-20 at 04 01 11" src="https://user-images.githubusercontent.com/20778143/208523206-9295b378-5dc2-4bf5-bd6a-a63defad52cd.png">
<img width="647" alt="Screen Shot 2022-12-20 at 03 59 12" src="https://user-images.githubusercontent.com/20778143/208522913-83f06d29-296e-46dd-b29b-e963e26790f3.png">

### Steps to reproduce

prerequisite: have enough funds on Goerli for a transaction and gas fees

1. Log in to extension
2. Start with the Ethereum mainnet network
3. Click the Send button on the overview page
4. Get to the "Send" page
5. Change to Goerli Network
6. Observe insufficient error appears despite having sufficient funds

### Version

10.22.0 and possibly older versions

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jpuri** [comment]
If this is happening in only one of the network I suspect it can be issue with the api. @digiwand : can you try to replicate this in old commit may be `10.23.XX`.

**Comment by digiwand** [comment]
@jpuri, your suspicion has been proven right

The insufficient error does show for Goerli on even 10.22.x. I believe 2 and 3 are new to 10.24.x. I will investigate more to see if 2 or 3 are blockers. #1 appears to be a non-blocker to 10.24.x because it is an outstanding issue.

Thanks for the support here! 

<img width="659" alt="Screen Shot 2022-12-20 at 20 23 07" src="https://user-images.githubusercontent.com/20778143/208677574-186c7c41-56c0-456a-bda8-bed6366416f5.png">

<img width="649" alt="Screen Shot 2022-12-20 at 20 22 57" src="https://user-images.githubusercontent.com/20778143/208677561-304a74ba-2b19-4c48-8c86-d21d3496de6a.png">

**Comment by digiwand** [comment]
I have updated the issue to split the 3 reported issues.

Refer to the other 2 issues here:
- https://github.com/MetaMask/metamask-extension/issues/17012
- https://github.com/MetaMask/metamask-extension/issues/17013

**Comment by bschorchit** [comment]
Closing as not needed as this https://github.com/MetaMask/metamask-extension/pull/18086 has been merged
