### ISSUE TITLE
[Bug]: On the send token screen, the insufficient error may show when the error is 'gasPriceFetchFailed'

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#17012]
### Describe the bug

The insufficient error may show when the error is 'gasPriceFetchFailed'. This could be misleading.

### Steps to reproduce

1. Log in to the extension
2. Inspect the error values in `metamask-extension/ui/pages/send/gas-display/gas-display.js` 
3. Go to "Send" tokens page
4. Switch networks
5. Observe `gasPriceFetchFailed` may show the insufficient funds error

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jpuri** [comment]
@digiwand : I think [v10.24.0](https://github.com/MetaMask/metamask-extension/milestone/89) label can be removed here.

**Comment by digiwand** [comment]
@jpuri Thank you! agreed. I removed the v10.24.0 milestone from this issue

**Comment by bschorchit** [comment]
Closing as not needed as this https://github.com/MetaMask/metamask-extension/pull/18086 has been merged
