### ISSUE TITLE
Token page break testrpc node

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#1702]
```
testrpc -b 3 
```

Click Metamask
Navigate to Token's page

```
.../ethereumjs-testrpc/build/cli.node.js:61262
    db.get(key, {
      ^

TypeError: Cannot read property 'get' of undefined
```

It's not 100% reproducible. Sometimes it does not fail.

**Comment by tmashuang** [comment]
What version of ethereumjs-testrpc are you running? I am on 4.6.1 and not able to reproduce.

**Comment by kumavis** [comment]
@rstormsf did you open the issue on testrpc?

**Comment by rstormsf** [comment]
`EthereumJS TestRPC v4.0.0`

**Comment by Zanibas** [comment]
Could you clarify what you mean by "Token" page? Is this Toshi? An actual token?

**Comment by rstormsf** [comment]
@Zanibas  Metamask has new UI page called tokens
![screen shot 2017-07-03 at 4 53 23 pm](https://user-images.githubusercontent.com/9360827/27810519-29192936-6010-11e7-9162-ceae016903f9.png)

**Comment by flyswatter** [comment]
We call `eth_call` for known tokens, even on other networks, which we could improve, but calling `eth_call` for an unknown address shouldn't break TestRPC, so I think this is also a TestRPC bug.

**Comment by EdgarCloggs** [comment]
Not sure this belongs in metamask, I am hitting this as well. Seems to be happening when: testrpc has a -b <value> set. I have observed that it seems to happen less or not at all without -b. Most likely an issue with testrpcs automatic mining parameter. -b or --blocktime: Specify blocktime in seconds for automatic mining. Default is 0 and no auto-mining. 

```

eth_call
/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61262
    db.get(key, {
      ^
TypeError: Cannot read property 'get' of undefined
    at dbGet (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61262:7)

```
