### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jithendra-transfi** [MetaMask/metamask-extension#17038]
### Describe the bug

<img width="1085" alt="Screenshot 2022-12-22 at 1 48 54 PM" src="https://user-images.githubusercontent.com/115153023/209089446-7eb735ed-e030-4d25-a07c-e87a594d2059.png">
<img width="365" alt="Screenshot 2022-12-22 at 1 49 50 PM" src="https://user-images.githubusercontent.com/115153023/209089592-f89f5bce-a432-4cb9-bae1-9aab4d23fbe4.png">

Can anyone please explain me how to resolve this gulp-watch it's when open metamask just loading screen appears 

### Steps to reproduce

1. cloned from repo 
2. run yarn dist
3. open from chrome extension
4. 

### Version

latest

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

**Comment by EresDev** [comment]
After cloning, you need to install dependencies using command `yarn`. You should follow the steps given in https://github.com/MetaMask/metamask-extension#building-locally
