### ISSUE TITLE
Reduce e2e Test Flakiness

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#17047]
**Context:**
In order to achieve this result, we need to Test Insights into the e2e test runs. This allows us to capture the following test metrics in Circle-CI: Flaky Tests, Most Failed Tests and Slowest Tests.

**Comment by digiwand** [comment]
whoops, thought this was a regular issue until I opened Zenhub. It seems like a good place to relate following flakiness issues. will add here

**Comment by digiwand** [comment]
whoops, thought this was a regular issue until I opened Zenhub. It seems like a good place to relate following flakiness issues. will add new issues here

**Comment by gauthierpetetin** [comment]
Closing this epic in favour of this one: https://github.com/MetaMask/metamask-extension/issues/17755
