### ISSUE TITLE
Metamask extremely slow since last update

### ISSUE THREAD

**Issue by Lammie** [MetaMask/metamask-extension#17041]
### Describe the bug

Metamask has been updated last week and has been extremely slow for me ever since. I have only started noticing the problem after the most recent update. It is just extremely slow. Every single action takes forever. Granted, I have 10+ accounts in it. But I have had it that way for a long time and it was always fast. On another PC, chrome browser has 75+ accounts and its even worse. Takes forever to do stuff.

### Steps to reproduce
1.
Click on metamask extension (you probably should have 10+ accounts to replicate) and it takes like 45 to 60 seconds for it to pop-up and ask for password. Enter password, takes another 45-60 seconds to process and load accounts.
Try submitting a transaction from uniswap or zapper, again takes 45 to 60 seconds for the metamask pop-up to submit transaction.
2.
It's especially slow on Seaport transactions in particular since you need to scroll down the tx data all the way before being able to sign, this takes about 2 minutes now per transaction because MetaMask is so extremely laggy and slow. 

### Version

10.23.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Ledger

**Comment by Helpcenter101** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by brad-decker** [comment]
@Lammie thanks for the report. Could you try 10.23.2 which includes a fix for the slowness you are experiencing and let me know if this is resolved?
