### ISSUE TITLE
[Bug]: ETH Token not showing in my account in MetaMask

### ISSUE THREAD

**Issue by bjmontoya** [MetaMask/metamask-extension#17058]
### Describe the bug

I transferred ETH Tokens from my Ledger Nano to MetaMask.  After the transaction processed, the ETH tokens showed in MetaMask Account 1 for about 30 seconds.  Then they disappeared from the Account 1.  When I look at the account on Etherscan, I can see where the token was moved to my MetaMask Account private key.  Then I see a subsequent transaction where it was moved from my MetaMask Account to a different private key.  None of the ETH tokens show in my account.  Where exactly are they and how do I get them to show in my account?

### Steps to reproduce

1. I started MetaMask
2. I attached/connected my Ledger Nano to MetaMask
3. In MetaMask, I chose to transfer ETH tokens from my Ledger Nano to my Account 1
4. I saw the pending transfer, then after a few seconds, I got the message that it had completed
5. For a brief period, I saw the ETH tokens transferred in my MetaMask Account 1
6. Then the ETH tokens in MetaMask Account 1 dissapeared
7. I went into EtherScan for my account and saw the transfer out of my MetaMask Account to a different security key.  You will be able to see that security key that my ETH tokens were transfered to out of my MetaMask Account

### Error messages or log output

```shell
No error messages ever occured.  I only received conformation of the transfer.  I attached a copy of the conformations
```

### Version

I am using the extension add-on in Brave Browser

### Build type

None

### Browser

Brave

### Operating system

Windows

### Hardware wallet

Ledger

### Additional context

I never received any error messages

**Comment by Mehdi207-mp** [comment]
Thanks

**Comment by Helpcenter101** [comment]
> ### Describe the bug
> 
> I transferred ETH Tokens from my Ledger Nano to MetaMask.  After the transaction processed, the ETH tokens showed in MetaMask Account 1 for about 30 seconds.  Then they disappeared from the Account 1.  When I look at the account on Etherscan, I can see where the token was moved to my MetaMask Account private key.  Then I see a subsequent transaction where it was moved from my MetaMask Account to a different private key.  None of the ETH tokens show in my account.  Where exactly are they and how do I get them to show in my account?
> [TransactionConformation.pdf](https://github.com/MetaMask/metamask-extension/files/10290029/TransactionConformation.pdf)
> [Etherscan Detail.pdf](https://github.com/MetaMask/metamask-extension/files/10290044/Etherscan.Detail.pdf)
> 
> 
> ### Steps to reproduce
> 
> 1. I started MetaMask
> 2. I attached/connected my Ledger Nano to MetaMask
> 3. In MetaMask, I chose to transfer ETH tokens from my Ledger Nano to my Account 1
> 4. I saw the pending transfer, then after a few seconds, I got the message that it had completed
> 5. For a brief period, I saw the ETH tokens transferred in my MetaMask Account 1
> 6. Then the ETH tokens in MetaMask Account 1 dissapeared
> 7. I went into EtherScan for my account and saw the transfer out of my MetaMask Account to a different security key.  You will be able to see that security key that my ETH tokens were transfered to out of my MetaMask Account
> 
> 
> ### Error messages or log output
> 
> ```shell
> No error messages ever occured.  I only received conformation of the transfer.  I attached a copy of the conformations
> ```
> 
> 
> ### Version
> 
> I am using the extension add-on in Brave Browser
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Brave
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> Ledger
> 
> ### Additional context
> 
> I never received any error messages

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by brad-decker** [comment]
@bjmontoya sorry to hear about this, I am leaving this open for investigation but recommend that you create a ticket on our support site https://metamask.zendesk.com/hc/en-us -- I am deleting your attachments to protect you from scammers who may try to use your address to engineer an attack against you. You may provide your screenshots, and [state logs](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-to-download-state-logs), in the ticket and it will greatly help us dive into this and provide support. Thanks!

**Comment by bjmontoya** [comment]
Ok, thanksOn Jan 2, 2023, at 7:30 AM, Brad Decker ***@***.***> wrote:﻿
@bjmontoya sorry to hear about this, I am leaving this open for investigation but recommend that you create a ticket on our support site https://metamask.zendesk.com/hc/en-us -- I am deleting your attachments to protect you from scammers who may try to use your address to engineer an attack against you. You may provide your screenshots, and state logs, in the ticket and it will greatly help us dive into this and provide support. Thanks!

**Comment by hilvmason** [comment]
Before we close this issue, our engineers should review state logs with Customer Success to verify that this was not the result of a bug

**Comment by bjmontoya** [comment]
Can I get a link to this issue. I cannot find itOn Jan 9, 2023, at 11:32 AM, hilvmason ***@***.***> wrote:﻿
Before we close this issue, our engineers should review state logs with Customer Success to verify that this was not the result of a bug

**Comment by Mehdi207-mp** [comment]
Hello, you are fine. Thank you very much for taking care of my problem
seriously and I congratulate Metamask company for this strong support.
Thank you.

در تاریخ دوشنبه ۹ ژانویهٔ ۲۰۲۳،‏ ۲۳:۰۲ hilvmason ***@***.***>
نوشت:
