### ISSUE TITLE
[Bug]: Custom RPC does not work on Mainnet 

### ISSUE THREAD

**Issue by sambacha** [MetaMask/metamask-extension#17065]
### Describe the bug

Custom RPC does not work on Mainnet 

### Steps to reproduce

1. add Custom RPC for main net
2. api.securerpc.com 
3. no work

### Version

10.23.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Helpcenter101** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by brad-decker** [comment]
@sambacha sorry to hear you're having problems adding a custom RPC. Could you open a support ticket at https://metamask.zendesk.com/hc/en-us -- they can help walk through any issues with setting up the custom RPC properly and if a bug is found will open a more detailed ticket. Thank you!
