### ISSUE TITLE
[Bug]: yarn setup fails (sentry/cli error)

### ISSUE THREAD

**Issue by DeFiYaco** [MetaMask/metamask-extension#17060]
### Describe the bug

Yarn setup command cannot be executed successfully on my machine (M1 macbook pro) with node v16.
The repository was cleanly cloned and the official steps were followed. 

### Steps to reproduce

1. clone the repository
2. follow the official steps from the README and call yarn setup
3. Fails

### Error messages or log output

```shell
cmd: 'sh',
  args: [ '-c', 'node scripts/install.js' ],
  code: 1,
  signal: null,
  stdout: '',
  stderr: 'Error: spawn Unknown system error -86\n',
  event: 'install',
  script: 'node scripts/install.js',
  pkgid: '@sentry/cli@1.58.0',
```

### Version

v10.23.2

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Firefox

### Operating system

MacOS

**Comment by VSaric** [comment]
@ShardYaco We are recently [upgrade yarn to version 3](https://github.com/MetaMask/metamask-extension/pull/16232) on `develop`. You no longer need to run `yarn setup` just running `yarn` works thanks to the allow-scripts yarn plugin.

**Comment by thoth-seshat** [comment]
I couldn't get this working until I removed my yarn.lock file. 

node v16
yarn 3
fresh clone on develop

I was running into dependency conflicts with the current lock file.

**Comment by brad-decker** [comment]
You may need to try the following:
1. `rm -rf node_modules`
2. `rm -rf .yarn/cache`
3. `yarn install` (as opposed to yarn) at least once before using just `yarn` in the future. 

I believe the issue stems from the first run of our build system after switching from yarn1 to yarn3

**Comment by AboldUSER** [comment]
Ran into this issue today with a fresh clone from this github repo (git commit head: 54fa7808c129daad7f280b40d03f926d766887c0) and using WSL, Node 16.20.0, Yarn 3.2.4.

Had the following errors when running `yarn` or `yarn install` :
```
➤ YN0018: │ concat-stream@https://github.com/hugomrdias/concat-stream.git#commit=057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: The remote archive doesn't match the expected checksum
➤ YN0018: │ ethereumjs-abi@https://github.com/ethereumjs/ethereumjs-abi.git#commit=ee3994657fa7a427238e6ba92a84d0b529bbcde0: The remote archive doesn't match the expected checksum
```

First running `rm -rf node_modules` and `rm -rf .yarn/cache` still produced the same errors. 

Only got it to successfully install by deleting the yarn.lock file.... though when I run `yarn test:unit` I get an error about the packages mocha & yargs and when I run `yarn dist` I get an error about the package event-stream, not sure if this is related to me creating a new yarn lock file.

**Comment by surajgjadhav** [comment]
Hi, I am trying to setup MetaMask-extension repo (branch: develop) in local. But, getting following error when I am running Yarn to install dependencies:
![image](https://github.com/MetaMask/metamask-extension/assets/31582237/2423c0cf-81ae-4242-8d25-a53ae4292048)

System Info:
OS: Windows 10
Node Version: 16.20.0
npm Version: 8.19.4

Commands I tried:
1. yarn
2. yarn install

Please help
