### ISSUE TITLE
[Bug]: Unable to transact on Wemix network (mainnet and testnet) - Transaction Underpriced error

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-extension#17073]
### Describe the bug

When making a transaction on the Wemix network, an error occurs and the transaction fails.

<img width="438" alt="Screenshot 2022-12-28 at 14 41 22" src="https://user-images.githubusercontent.com/2859402/209875173-f581b6b8-b510-4dd0-9ff0-fba607fd8ec7.png">

### Steps to reproduce

Chain parameters: https://chainlist.org/?search=wemix&testnets=true
Testnet faucet: https://wallet.test.wemix.com/faucet

1. Initiate a transaction, such as sending tWEMIX to self
2. Select Confirm on the transaction confirmation screen
3. Error occurs

### Error messages or log output

```shell
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}'
```

### Version

10.23.2

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

### Additional context

Issue occurs on Wemix Testnet and Mainnet, mobile (Android & iOS) and extension.

Have tried modifying gas prices for transactions to no avail.

Tested in several MetaMask extension versions from 10.16.0 to 10.23.2, all had the same issue.

**Comment by Helpcenter101** [comment]
> ### Describe the bug
> 
> When making a transaction on the Wemix network, an error occurs and the transaction fails.
> 
> <img width="438" alt="Screenshot 2022-12-28 at 14 41 22" src="https://user-images.githubusercontent.com/2859402/209875173-f581b6b8-b510-4dd0-9ff0-fba607fd8ec7.png">
> 
> 
> ### Steps to reproduce
> 
> Chain parameters: https://chainlist.org/?search=wemix&testnets=true
> Testnet faucet: https://wallet.test.wemix.com/faucet
> 
> 1. Initiate a transaction, such as sending tWEMIX to self
> 2. Select Confirm on the transaction confirmation screen
> 3. Error occurs
> 
> 
> ### Error messages or log output
> 
> ```shell
> [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}'
> ```
> 
> 
> ### Version
> 
> 10.23.2
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome, Brave
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> Issue occurs on Wemix Testnet and Mainnet, mobile (Android & iOS) and extension.
> 
> Have tried modifying gas prices for transactions to no avail.
> 
> Tested in several MetaMask extension versions from 10.16.0 to 10.23.2, all had the same issue.

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Jozzq** [comment]
> ### Describe the bug
> 
> When making a transaction on the Wemix network, an error occurs and the transaction fails.
> 
> 
> 
> <img width="438" alt="Screenshot 2022-12-28 at 14 41 22" src="https://user-images.githubusercontent.com/2859402/209875173-f581b6b8-b510-4dd0-9ff0-fba607fd8ec7.png">
> 
> 
> 
> ### Steps to reproduce
> 
> Chain parameters: https://chainlist.org/?search=wemix&testnets=true
> 
> Testnet faucet: https://wallet.test.wemix.com/faucet
> 
> 
> 
> 1. Initiate a transaction, such as sending tWEMIX to self
> 
> 2. Select Confirm on the transaction confirmation screen
> 
> 3. Error occurs
> 
> 
> 
> ### Error messages or log output
> 
> ```shell
> [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}'
> ```
> 
> 
> ### Version
> 
> 10.23.2
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome, Brave
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> Issue occurs on Wemix Testnet and Mainnet, mobile (Android & iOS) and extension.
> 
> 
> 
> Have tried modifying gas prices for transactions to no avail.
> 
> 
> 
> Tested in several MetaMask extension versions from 10.16.0 to 10.23.2, all had the same issue.

We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n

**Comment by deshvin** [comment]
This can be resolved by changing gas settings for the transaction to:

Max base fee: 101
Priority fee: 100
Gas limit: 21000
