### ISSUE TITLE
[Bug]: sanction

### ISSUE THREAD

**Issue by FlokiBB** [MetaMask/metamask-extension#17074]
### Describe the bug

I can't send transactions for my location :|

### Steps to reproduce

1. born in the wrong place

### Version

latest

### Build type

Flask

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

Ledger

**Comment by FlokiBB** [comment]
I want to fork metamask and publish a community version of it to remove the data collection and sanction part from the code

**Comment by Helpcenter101** [comment]
> ### Describe the bug
> 
> I can't send transactions for my location :|
> 
> ### Steps to reproduce
> 
> 1. born in the wrong place
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> latest
> 
> ### Build type
> 
> Flask
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Linux
> 
> ### Hardware wallet
> 
> Ledger
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by brad-decker** [comment]
@FlokiBB there is no code in MetaMask that prevents users from any country from using the software, so the good news is that you may change your RPC provider to any RPC that will allow access to ethereum from your country. Once you have an RPC provider for mainnet ethereum you may follow this guide: https://metamask.zendesk.com/hc/en-us/articles/360043227612-How-to-add-a-custom-network-RPC on how to add a custom network.

You may also manage your own privacy in the settings of MetaMask. I am including the MetaMetrics tutorial here https://metamask.zendesk.com/hc/en-us/articles/6921789658523-How-to-manage-your-MetaMetrics-settings but you can also enable or disable other settings such as third party tools that we use to enhance the user experience (such as using the etherscan API to get incoming transactions, which can be disabled in privacy settings).

A new privacy centric onboarding flow is releasing soon :tm: that will give these options (including adding a custom RPC) upfront before landing in the MetaMask extension.

We cannot advise on *which* RPC providers will work for you in your country.
