### ISSUE TITLE
[Bug]: Received invalid network parameters

### ISSUE THREAD

**Issue by ivanbogaeb** [MetaMask/metamask-extension#17072]
### Describe the bug

I just saw this bug on my console as soon as Metamask fired up.

### Steps to reproduce

1. Open your browser.
2. Go to any website while Metamask is active.
3. Open your dev console.

### Error messages or log output

```shell
MetaMask: Received invalid network parameters. Please report this bug.
{chainId: '0x89', networkVersion: undefined}

chainId: "0x89"networkVersion: undefined[[Prototype]]: Object
_handleChainChanged @ inpage.js:1
_handleChainChanged @ inpage.js:1
(anonymous) @ inpage.js:1
i @ inpage.js:1
emit @ inpage.js:1
(anonymous) @ inpage.js:1
write @ inpage.js:1
w @ inpage.js:17
(anonymous) @ inpage.js:17
b.write @ inpage.js:17
g @ inpage.js:17
f @ inpage.js:8
s.emit @ inpage.js:8
_ @ inpage.js:17
v @ inpage.js:17
w.push @ inpage.js:17
_write @ inpage.js:1
w @ inpage.js:17
(anonymous) @ inpage.js:17
b.write @ inpage.js:17
g @ inpage.js:1
f @ inpage.js:8
s.emit @ inpage.js:8
_ @ inpage.js:1
v @ inpage.js:1
w.push @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
s.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
s.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
s.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
```

### Version

10.23.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Additional context

This happened while I was developing something for myself on localhost, nothing to do with Metamask, but this showed up anyways.

**Comment by Jozzq** [comment]
> ### Describe the bug
> 
> I just saw this bug on my console as soon as Metamask fired up.
> 
> ### Steps to reproduce
> 
> 1. Open your browser.
> 
> 2. Go to any website while Metamask is active.
> 
> 3. Open your dev console.
> 
> 
> 
> ### Error messages or log output
> 
> ```shell
> MetaMask: Received invalid network parameters. Please report this bug.
> 
> {chainId: '0x89', networkVersion: undefined}
> 
> 
> 
> chainId: "0x89"networkVersion: undefined[[Prototype]]: Object
> 
> _handleChainChanged @ inpage.js:1
> 
> _handleChainChanged @ inpage.js:1
> 
> (anonymous) @ inpage.js:1
> 
> i @ inpage.js:1
> 
> emit @ inpage.js:1
> 
> (anonymous) @ inpage.js:1
> 
> write @ inpage.js:1
> 
> w @ inpage.js:17
> 
> (anonymous) @ inpage.js:17
> 
> b.write @ inpage.js:17
> 
> g @ inpage.js:17
> 
> f @ inpage.js:8
> 
> s.emit @ inpage.js:8
> 
> _ @ inpage.js:17
> 
> v @ inpage.js:17
> 
> w.push @ inpage.js:17
> 
> _write @ inpage.js:1
> 
> w @ inpage.js:17
> 
> (anonymous) @ inpage.js:17
> 
> b.write @ inpage.js:17
> 
> g @ inpage.js:1
> 
> f @ inpage.js:8
> 
> s.emit @ inpage.js:8
> 
> _ @ inpage.js:1
> 
> v @ inpage.js:1
> 
> w.push @ inpage.js:1
> 
> _onData @ inpage.js:1
> 
> _onMessage @ inpage.js:1
> 
> postMessage (async)
> 
> _postMessage @ contentscript.js:1
> 
> _write @ contentscript.js:1
> 
> w @ contentscript.js:1
> 
> (anonymous) @ contentscript.js:1
> 
> y.write @ contentscript.js:1
> 
> g @ contentscript.js:17
> 
> d @ contentscript.js:8
> 
> s.emit @ contentscript.js:8
> 
> _ @ contentscript.js:17
> 
> v @ contentscript.js:17
> 
> w.push @ contentscript.js:17
> 
> _write @ contentscript.js:17
> 
> w @ contentscript.js:17
> 
> (anonymous) @ contentscript.js:17
> 
> y.write @ contentscript.js:17
> 
> g @ contentscript.js:17
> 
> d @ contentscript.js:8
> 
> s.emit @ contentscript.js:8
> 
> _ @ contentscript.js:17
> 
> v @ contentscript.js:17
> 
> w.push @ contentscript.js:17
> 
> _write @ contentscript.js:17
> 
> w @ contentscript.js:17
> 
> (anonymous) @ contentscript.js:17
> 
> y.write @ contentscript.js:17
> 
> g @ contentscript.js:17
> 
> d @ contentscript.js:8
> 
> s.emit @ contentscript.js:8
> 
> _ @ contentscript.js:17
> 
> v @ contentscript.js:17
> 
> w.push @ contentscript.js:17
> 
> _onMessage @ contentscript.js:8
> 
> (anonymous) @ contentscript.js:8
> ```
> 
> 
> ### Version
> 
> 10.23.2
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> This happened while I was developing something for myself on localhost, nothing to do with Metamask, but this showed up anyways.

We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n

**Comment by brad-decker** [comment]
@ivanbogaeb this happens when the chainId specified in the rpc settings does not match what is received for `eth_chainId` method. Can you confirm your chainId is configured properly for your client

**Comment by ivanbogaeb** [comment]
@brad-decker I think I didn't explain myself correctly!  I wasn't even working with Metamask to begin with, it activated on it's own on  my [http://localhost:3000](http://localhost:3000) for no reason, displaying that error message.

**Comment by brad-decker** [comment]
The way MetaMask works is that we inject the provider into your browser, this allows dapps to communicate with the client and suggest transactions, etc. One of the first things that the injection initialization does is validate the network parameters. I assume your MetaMask is currently on the  Polygon mainnet (0x89 is the chainId for that network). can you try changing networks to mainnet and tell me if the same thing happens?

**Comment by daramir** [comment]
Hi @brad-decker , I'm getting a similar error. The error logged in the browser is: 
> MetaMask: Received invalid network parameters. Please report this bug. {chainId: '0x1388', networkVersion: 5000}

> ...this happens when the chainId specified in the rpc settings does not match what is received for `eth_chainId` method. Can you confirm your chainId is configured properly for your client

However this does match the response of the `eth_chainId` method. Which for my current chain is:

```json
{
	"id": 1,
	"jsonrpc": "2.0",
	"method": "eth_chainId",
	"result": "0x1388"
}
```

**Comment by MarcusWentz** [comment]
I see this issue at chainId 8080 and 8081 as well:

https://github.com/Shardeum/shardeum-bug-reporting/issues/7

**Comment by MarcusWentz** [comment]
This issue seems exclusive to Metamask,
since I do not see this error with the Brave Wallet when interacting with smart contracts like Metamask.

**Comment by simone1999** [comment]
MetaMask seems to check networks beeing added with the config from chainlist.org (or a service they use in the background). The mentioned network was not available on ChainList.org at the time this error happens. Is it possible that all networks that are not available on chainlist generate this error?

**Comment by MarcusWentz** [comment]
Might be related to this:

https://github.com/Shardeum/shardeum-bug-reporting/issues/29

**Comment by ZhangTao1596** [comment]
> Might be related to these issues:
> 
> ethers.js `provider.getNetwork()` format wrong might be causing Golang `chainId` type error `client.NetworkID(context.Background())`
> 
> [Shardeum/shardeum-bug-reporting#29](https://github.com/Shardeum/shardeum-bug-reporting/issues/29)
> 
> RPC `net_version` returns `chainId` as type `number` instead of type `string`
> 
> [Shardeum/shardeum-bug-reporting#21](https://github.com/Shardeum/shardeum-bug-reporting/issues/21)
> 
> This issue looks fixed on Betanet 1.X after making the chainId type a string.

This is definitely the reason. In [ethereum RPC spec](https://ethereum.org/en/developers/docs/apis/json-rpc/#net_version) shows it shoud be 10 based number string. But metamask treat it as [quantity](https://ethereum.org/en/developers/docs/apis/json-rpc/#hex-encoding).
