### ISSUE TITLE
primaryType is not shown during signTyped - users are signing things almost blindly

### ISSUE THREAD

**Issue by vicnaum** [MetaMask/metamask-extension#17076]
### Describe the bug

PrimaryType isn't displayed when signing Typed data, instead it always shows a "Message" string and a bunch of parameters.

IMHO this goes against the primary goal of EIP712 - a more user-friendly way of signing messaging.
It's astonishing that for 3 years people were just signing things blindly!

**Example:**
If two functions have exact same parameters but do completely different things - there is no way to distinguish between a harmless signature (like setting a limit on something), and a really dangerous one (like permitForAll that potentially can lead to loss of all your tokens).
Even if parameters differ slightly - it's still hard for a non-technical user to see what exactly they sign.

**Real world example:**
Recently there was a loss of many Lens Protocol profiles from malicious websites that asked users for a signature, mimicking a login. If user could see they are signing "permitForAll" or "burnWithSig" - they wouldn't sign it.

**Current behavior:**
![telegram-cloud-photo-size-4-5870527322589870546-y](https://user-images.githubusercontent.com/5636644/210108213-dc511a4f-e98e-4e60-b609-51e5416656a6.jpg)

**Expected behavior:**
Before 2019 everything worked as expected, but in PR #6891 the `primaryType` was replaced with a "Message" string for a reason unknown to me (maybe @tshfx can explain more details about the reasoning of this).
The EIP712 example shows a screenshot with "Mail" as primaryType, so I assume that also confirm this behavior is the expected.

**Proposed solution:**
Display primaryType instead of "Message" (like "PermitForAll" in this case)
![image](https://user-images.githubusercontent.com/5636644/210108453-c2192133-ae1c-42c4-ad19-a056f64a33bf.png)

### Steps to reproduce

1. Sign any TypedData, look at the signature message window

### Version

10.23.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Helpcenter101** [comment]
> ### Describe the bug
> 
> PrimaryType isn't displayed when signing Typed data, instead it always shows a "Message" string and a bunch of parameters.
> 
> IMHO this goes against the primary goal of EIP712 - a more user-friendly way of signing messaging.
> It's astonishing that for 3 years people were just signing things blindly!
> 
> **Example:**
> If two functions have exact same parameters but do completely different things - there is no way to distinguish between a harmless signature (like setting a limit on something), and a really dangerous one (like permitForAll that potentially can lead to loss of all your tokens).
> Even if parameters differ slightly - it's still hard for a non-technical user to see what exactly they sign.
> 
> **Real world example:**
> Recently there was a loss of many Lens Protocol profiles from malicious websites that asked users for a signature, mimicking a login. If user could see they are signing "permitForAll" or "burnWithSig" - they wouldn't sign it.
> 
> **Current behavior:**
> ![telegram-cloud-photo-size-4-5870527322589870546-y](https://user-images.githubusercontent.com/5636644/210108213-dc511a4f-e98e-4e60-b609-51e5416656a6.jpg)
> 
> **Expected behavior:**
> Before 2019 everything worked as expected, but in PR #6891 the `primaryType` was replaced with a "Message" string for a reason unknown to me (maybe @tshfx can explain more details about the reasoning of this).
> The EIP712 example shows a screenshot with "Mail" as primaryType, so I assume that also confirm this behavior is the expected.
> 
> **Proposed solution:**
> Display primaryType instead of "Message" (like "PermitForAll" in this case)
> ![image](https://user-images.githubusercontent.com/5636644/210108453-c2192133-ae1c-42c4-ad19-a056f64a33bf.png)
> 
> ### Steps to reproduce
> 
> 1. Sign any TypedData, look at the signature message window
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.23.2
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Jozzq** [comment]
We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n

**Comment by Jozzq** [comment]
> ### Describe the bug
> 
> 
> 
> PrimaryType isn't displayed when signing Typed data, instead it always shows a "Message" string and a bunch of parameters.
> 
> 
> 
> IMHO this goes against the primary goal of EIP712 - a more user-friendly way of signing messaging.
> 
> It's astonishing that for 3 years people were just signing things blindly!
> 
> 
> 
> **Example:**
> 
> If two functions have exact same parameters but do completely different things - there is no way to distinguish between a harmless signature (like setting a limit on something), and a really dangerous one (like permitForAll that potentially can lead to loss of all your tokens).
> 
> Even if parameters differ slightly - it's still hard for a non-technical user to see what exactly they sign.
> 
> 
> 
> **Real world example:**
> 
> Recently there was a loss of many Lens Protocol profiles from malicious websites that asked users for a signature, mimicking a login. If user could see they are signing "permitForAll" or "burnWithSig" - they wouldn't sign it.
> 
> 
> 
> **Current behavior:**
> 
> ![telegram-cloud-photo-size-4-5870527322589870546-y](https://user-images.githubusercontent.com/5636644/210108213-dc511a4f-e98e-4e60-b609-51e5416656a6.jpg)
> 
> 
> 
> **Expected behavior:**
> 
> Before 2019 everything worked as expected, but in PR #6891 the `primaryType` was replaced with a "Message" string for a reason unknown to me (maybe @tshfx can explain more details about the reasoning of this).
> 
> The EIP712 example shows a screenshot with "Mail" as primaryType, so I assume that also confirm this behavior is the expected.
> 
> 
> 
> **Proposed solution:**
> 
> Display primaryType instead of "Message" (like "PermitForAll" in this case)
> 
> ![image](https://user-images.githubusercontent.com/5636644/210108453-c2192133-ae1c-42c4-ad19-a056f64a33bf.png)
> 
> 
> 
> ### Steps to reproduce
> 
> 
> 
> 1. Sign any TypedData, look at the signature message window
> 
> 
> 
> ### Error messages or log output
> 
> 
> 
> _No response_
> 
> 
> 
> ### Version
> 
> 
> 
> 10.23.2
> 
> 
> 
> ### Build type
> 
> 
> 
> None
> 
> 
> 
> ### Browser
> 
> 
> 
> Chrome
> 
> 
> 
> ### Operating system
> 
> 
> 
> MacOS
> 
> 
> 
> ### Hardware wallet
> 
> 
> 
> _No response_
> 
> 
> 
> ### Additional context
> 
> 
> 
> _No response_

We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n

**Comment by brad-decker** [comment]
Thanks for the suggestion/report @vicnaum -- I am going to circulate this with our team.
