### ISSUE TITLE
Manifest.json specifies "scripts/chromereload.js" as a dependency, but it's not in the source code

### ISSUE THREAD

**Issue by daniphilia** [MetaMask/metamask-extension#1709]

**Comment by kumavis** [comment]
here it is in the src https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/chromereload.js

but maybe missing from the build? how did you encounter this?

**Comment by kumavis** [comment]
@frankiebee

**Comment by Zanibas** [comment]
Checked our dists and it seems that we've removed the chromereload.js as a dependency when deploying our actual build.

It may be that our dev build was shipped one day, which is our bad, but should be fixed now.
