### ISSUE TITLE
Replace uses of deprecated `provider` property and `getProviderAndBlockTracker` method

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#17103]
Remove all uses of the deprecated provider property and the getProviderAndBlockTracker method. They should be deprecated as part of [#1045](https://github.com/MetaMask/core/issues/1045).

We can replace them by getting the complete collection of network clients, and using the one for the current selected network. We can get the current selected network state from the network controller.

**Comment by adonesky1** [comment]
Closing this because this is an intermediate step that would require re-introducing network controller state change listeners which doesn't actually help us move toward our goals. Instead we will move straight to refactoring controllers to get network clients dynamically.
