### ISSUE TITLE
Update story links in storybook documentation

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17110]
### Description
When https://github.com/MetaMask/metamask-extension/pull/17092 is merged it will change all storybook URLs and will essentially break any link references to those stories. We will need to update internal and external links. This ticket is to update all internal links inside of the repo.

A good start would be to search for `[(/docs` in `.mdx` files that point to component doc pages

![Screenshot 2023-01-09 at 12 19 04 PM](https://user-images.githubusercontent.com/8112138/211400452-01473586-a506-451c-84c4-f80d39cfe74d.png)

Then searching for `](/story` in `.mdx` files that point to component stort pages

![Screenshot 2023-01-09 at 12 20 32 PM](https://user-images.githubusercontent.com/8112138/211400610-847e7492-4380-4593-97a6-ab37771e52d0.png)

I would also do a vert broad search `](/` and scan for any links that point to storybook pages

### Technical Details
- Update all URLs to stories in `.mdx` files to use the new URLS

### Acceptance Criteria 
- All links to stories in MDX docs work

**Comment by georgewrmarshall** [comment]
I suppose this doesn't need to be completed because all of the old urls will remain the same @NidhiKJha? I just checked and the links are still working after https://github.com/MetaMask/metamask-extension/pull/17092 has been merged

**Comment by NidhiKJha** [comment]
@georgewrmarshall the links are changed for all the stories. But I had updated them in the same PR. So, we can close this.

**Comment by georgewrmarshall** [comment]
Right on! 🎸

**Comment by serverprogrammerhacker** [comment]
A lot of people are still falling for fake cyber experts and hackers even after being ripped off by fake cryptocurrency investors thinking they will be able to recover their money from those scammers and end up losing more, that was my story too. However, after almost given up, a cyber expert i met online out of the blue was able to give me hope on humanity again by helping me get my money back after a dubious crypto investment. He is indeed the best man for internet expertise services. Contact him on: (WIZESAFETYRECOVERY @ GMAIL COM)
