### ISSUE TITLE
[Bug]: Error in event handler: Error: StreamProvider - Unknown response id for response: [object Object]

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17154]
### Describe the bug

**Problem**: MM pop-up stays loading indefinitely and I see this error on the background console `Error in event handler: Error: StreamProvider - Unknown response id for response: [object Object]`

https://user-images.githubusercontent.com/54408225/212037420-1650019e-1510-4dbe-b4b5-cf32c4750abf.mp4

### Steps to reproduce

[investigating]
Possibly related to doing a non-conventional function call to a smart contract (modifying the ERC20 standard)

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by DimasikS12** [comment]
Hi! I have this problem too. Can you please tell me what is causing this error and how to solve it?

**Comment by Samclay8** [comment]
Also have this problem. Seems to only occur on chrome.

**Comment by danjm** [comment]
As a next step, this requires consistent repro steps.
