### ISSUE TITLE
[Bug]: Google Chrome page preload seems to be causing problems with MetaMask RPC calls

### ISSUE THREAD

**Issue by tmisirpash** [MetaMask/metamask-extension#17167]
### Describe the bug

I am working on an app that allows people to connect an injected wallet provider. After testing the wallet connection on several different browsers, I noticed a weird problem with Chrome -- occasionally, RPC calls such as `wallet_switchEthereumChain` would never resolve, even though the `detectEthereumProvider` function from @metamask/detect-provider detected a valid provider. I did some investigation and found that turning off Chrome's preload feature (enabled by default) made the problem go away. With preloading enabled, the problem also went away temporarily after I cleared my browser cache (likely because a clean cache means the preloading option doesn't know what urls you'll visit), but resurfaced after loading the site several times.

This problem may be related to (#14283).[](url)

### Steps to reproduce

With preloading enabled in Chrome, I ended up getting the wallet to consistently fail to connect by opening a fresh Chrome window, going to a website that was not my app, then opening my local development server in a second window.

### Version

10.23.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by danjm** [comment]
This was addressed with https://github.com/MetaMask/metamask-extension/pull/19727

Thanks for the original report @tmisirpash
