### ISSUE TITLE
Action Queue metrics

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#17197]
We only need one event: tracking when the action queue was utilized upon a service worker restart. Each event should record the names of the methods that were processed by the action queue.

**Comment by danjm** [comment]
![Screenshot from 2023-01-20 11-29-04](https://user-images.githubusercontent.com/7499938/213730057-24daff56-1d75-478c-9833-eb6d43fdda2e.png)

**Comment by kevinghim** [comment]
Per a thread with Pedro and John:

Event name: Service Worker Restarted
Properties: service_worker_action_queue–method (type: string)
