### ISSUE TITLE
[Bug]: Spend Limit amount from an Approve transaction points to ETH instead of the ERC20 token

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17228]
### Describe the bug

**Problem**: when you have performed an Approve transaction, if you check the transaction details you will see a field for `spend limit amount` which is pointing to the incorrect value (ETH) instead of the ERC20 token limit.

![spend-limit](https://user-images.githubusercontent.com/54408225/212482574-aa69e499-48b9-4bcb-ac6a-f2e3981fba2a.png)

### Steps to reproduce

1. Go to test dapp
2. Connect to test dapp
3. Click Create Token - accept on MM
4. Click Approve - accept on MM
5. Wait until tx is confirmed
6. Click on the tx, to see tx details
7. Check that `spend amount limit` indicates ETH and the ETH value you send along that call, instead of the ERC20 token where you made the approval and the token limit you set on the approval screen

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Good catch!
We could also:
1. Update title to "Approve token spending cap" instead of Approve Token spend limit.
2. Update the copy to `Spending cap` instead of `Spend limit amount`.
so it matches the copy in the token allowance request itself.

**Comment by bschorchit** [comment]
It's not only the token name but also the spend limit value that might be wrong.

**Comment by NiranjanaBinoy** [comment]
This issue occurs only when the token is not added to the wallet. I am attaching a recording of the behavior when we add the token to the wallet.

https://user-images.githubusercontent.com/43930900/214350089-4a38ebef-f831-4910-b8be-da0b508d011a.mov

This ticket can be solved in two ways:
1. The first and simplest will be to add the token to the wallet while performing a token approval or token transfer. 
2. Another solution will be to decode the txParam data in the <TransactionBreakdown/> component to get the opening cap amount, and then using the `to` address in txParam, we have to fetch the token details to get the token symbol to append to the spending cap to display in the Transaction details.

@bschorchit Is it desirable to add a Token to the wallet while approving or transferring it? @danjm mentioned this solution or additional feature came up in discussion once before, and it was deemed desirable at that point.

**Comment by bschorchit** [comment]
This is such an interesting finding, Niranjana! I was now trying it out and it seems that if hide a token that I had added in my wallet, this bug reappears - while the user expectation would be that their activity history remain correct. 

Is there a way we could preserve this information so it doesn't depend on the tokens the user have in the list at that moment in time? Would the 2. option do that?

**Comment by NiranjanaBinoy** [comment]
@bschorchit 
We can try to add a check for added tokens, detected tokens, tokensList, and custom tokens (hidden tokens should be covered in this because hidden tokens do not store any token details other than addresses), in the place where we are currently just checking for added tokens. It should probably fetch us the token details we need, but if we cannot get the token details from any of these means, what should be the fallback?

**Comment by bschorchit** [comment]
Right now we use the work `token` as a fallback on the activity title (see screenshots). We can use the same word as fallback for the spending cap part.

Screenshot 1 (with USDT added)
<img width="374" alt="Screenshot 2023-01-24 at 21 08 22" src="https://user-images.githubusercontent.com/34968356/214449498-001dc4fd-cd73-4fde-986c-1ed1e9d89c0a.png">

Screenshot 2 (with USDT hidden)
<img width="368" alt="Screenshot 2023-01-24 at 21 08 44" src="https://user-images.githubusercontent.com/34968356/214449561-8d231024-47a1-4bf7-ae30-24a07e37df48.png">

**Comment by bschorchit** [comment]
Does the above answer your question or did I missunderstood what exactly the fallback should be, @NiranjanaBinoy? Should the fallback also cover the spending cap **value** part?

**Comment by NiranjanaBinoy** [comment]
@bschorchit  we have a fallback for the transaction list part but for transaction details that pop up in the spending cap, we are displaying `0 Eth` or something when we cannot find token information. Do you mean we can use `5 tokens` or `1 token` as the spend cap when we cannot find the token information?

**Comment by bschorchit** [comment]
Yes :) @NiranjanaBinoy

**Comment by NiranjanaBinoy** [comment]
@bschorchit We will be able to get the token amount even if we don't have token information, but since we will not have `decimal` value, the token amount will not be accurate or too big. If a token TST has a decimal value of 4, then the token amount will be 5000, which we display as 5TST, but if we don't have token information, we will have to display 5000 tokens.

**Comment by seaona** [comment]
I agree, not having token decimals information might be a potential source of confusion, as per @NiranjanaBinoy 's comment :/ not sure what should be the solution here

**Comment by bschorchit** [comment]
Oh, I see! Let's either have `unknown` as the fallback for the spending cap or hide this line. Is there a preference from the design side @holantonela? 
For context, this should be an edge case for when we fail to get token information so we cannot display the correct spending cap in activity (see screenshot).

<img width="368" alt="Screenshot 2023-01-25 at 15 09 48" src="https://user-images.githubusercontent.com/34968356/214647070-7ca414af-182c-4634-a287-556a37c97ef8.png">

**Comment by holantonela** [comment]
In this case, i'd keep the `Spending cap` line. We'd say "None" or "Unknown", either would work. The 0 is confusing.

**Comment by bschorchit** [comment]
Let's move forward with `unknown` then. Thank you, Antonela ❤️
