### ISSUE TITLE
NFTs: Implement "Detection turned off" notification

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#17223]
### Describe the bug

The designs call for a notification to be shown if NFT detection is not on:

<img width="471" alt="NFTOffNotification" src="https://user-images.githubusercontent.com/46655/212419810-477575b0-6460-4f7b-886f-87d4d69a4d67.png">

This needs to be implemented.

### Steps to reproduce

N/A

### Version

10.23

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by vthomas13** [comment]
We decided to stop developing this system notification toast due to UX redundancies with the message from the blue informational banner
