### ISSUE TITLE
[Bug]: The logo is incorrectly displayed during the signature process

### ISSUE THREAD

**Issue by dogedefi** [MetaMask/metamask-extension#17229]
### Describe the bug

![image](https://user-images.githubusercontent.com/93388896/212605227-3733db45-d796-47c1-85c9-700933244c23.png)

### Steps to reproduce

1. choose an account and connect
2. sign

### Version

10.23.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by dogedefi** [comment]
I tried to solve this problem by having the img width and height set to 100%, and the parent div layout using flex and centering the content.

**Comment by danjm** [comment]
I believe this has been resolved. For example, see the correct website logo on the attached screenshot of a signature request on open.

Please open a new ticket if you are continuing to experience this problem
![Screenshot from 2023-07-25 01-32-02](https://github.com/MetaMask/metamask-extension/assets/7499938/4c38db1a-627a-4b36-b2cc-6de94272b8ea)
