### ISSUE TITLE
Refactor ui/components/app/signature-request/

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#17245]
Refactor https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/app/signature-request/signature-request.component.js component:

1. get rid of container component
2. make signature-request.component.js functional component
3. use selectors to query state and minimise the props it takes.
4. add test coverage

**Comment by spiritanand** [comment]
Hey @jpuri I would be interested in working on refactoring this code and adding tests. Could you elaborate on test coverage?

**Comment by bschorchit** [comment]
Update for visibility: Removing from sprint as we'll be prioritizing mobile refactoring this quarter
