### ISSUE TITLE
[Bug]: Token Detection does not return any Token

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17267]
### Describe the bug

**Problem**: I don't get any Token detected while having the feature toggle ON

https://user-images.githubusercontent.com/54408225/212972702-e2208216-e871-4dc4-a850-950c8a5888e9.mp4

### Steps to reproduce

1. Load MM
2. Enable Token Detection
3. Check Assets -- see no token is detected

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
I can no longer reproduce the issue with the same wallet. Might be that it was some network error/ slow network situation?

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by danjm** [comment]
Closing as the last comment on this said it was not reproducible, and we have not had similar reports in recent months.
