### ISSUE TITLE
[Bug]: Importing an Account from a JSON file is not possible from the Popup, as it closes when we select the file

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17275]
### Describe the bug

**Problem**: importing an Account from a JSON file is not possible from the Popup, as it closes when we select the file

https://user-images.githubusercontent.com/54408225/213158561-3e076323-e3c5-4948-999e-657ed8708230.mp4

### Steps to reproduce

1. Unlock MM
2. Open MM popup
3. Select Import Account
4. Select JSON file
5. Click Choose file
6. Select the JSON file from your computer -- see how MM popup closes and you cannot continue to import the account

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by montelaidev** [comment]
Just tested on ef5d171f544ec13db6d8310c54445b96ce543ca0 and i am able to import using the popup, but there are still performance issues identified from this ticket https://app.zenhub.com/workspaces/metamask-accounts-team-v2-64c91cbeaa9d1c00126621fd/issues/gh/metamask/metamask-extension/17274.

**Comment by montelaidev** [comment]
This is related to https://github.com/MetaMask/metamask-extension/issues/17274
