### ISSUE TITLE
[Ext Nav] Create component: Banner (Fox)

### ISSUE THREAD

**Issue by garrettbear** [MetaMask/metamask-extension#17282]
### Description
Create a reusable UI component for `Banner`

### References
[Banner Audit FigJam](https://www.figma.com/file/ZRc86y4pTE33gLMdrobHCJ/Banner-Audit?node-id=0%3A1&t=q7NU8vErEIBI97xs-1)
[Figma Link](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=5711%3A16577&t=KYVgXNrRrJ2xbtmq-1)
[UI component guidelines](https://www.notion.so/UI-Components-5ccd2bf83eb8441892a0b72c0d8929e1)
[Styling guidelines](https://www.notion.so/Extension-Frontend-Engineering-Guide-b82ddb3e14004b5db3799a9b446294a9#49aa2ef7b7aa40178ff918043df71c34)
Testing guidelines: TBC

### Files needed
- `index.js`
- `index.scss`
- `banner.js`
- `banner.stories.js`
- `banner.test.js`
- `README.mdx`

### Technical details
TBC

### Acceptance criteria
- [ ] Uses color, typography, shadows design tokens 
- [ ] Uses semantic html
- [ ] PropTypes have descriptions
- [ ] Has storybook story with controls
- [ ] Has documentation in MDX
- [ ] Has unit tests and 90% coverage
- [ ] Works in Chrome and Firefox
- [ ] Performance tested: no unnecessary re-renders or other performance concerns

**Comment by georgewrmarshall** [comment]
Duplicate: https://github.com/metamask/metamask-extension/issues/17554
