### ISSUE TITLE
[Bug]: ERC20 Amount not shown on the Send confirmation screen for hex data transactions sent from MM 

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17292]
### Describe the bug

ERC20 Amount not shown on the Send confirmation screen for hex data transactions sent from MM 

https://user-images.githubusercontent.com/53189696/213454444-5f1ef39f-7fbd-481d-9160-5045327c7ef9.mov

### Steps to reproduce

1. Request LINK on Goerli from the [faucet](https://faucets.chain.link/)
2. Navigate to the LINK contract on [Etherscan](https://goerli.etherscan.io/address/0x326c977e6efc84e512bb9c30f76e30c160ed06fb)
3. Click the Contract tab
4. Click Write Contract
5. Click Connect to Web3
6. Connect your MM wallet
7. Expand the Transfer function
8. Enter your public address e.g `0x56F2e03c8D30649818c022a9759CF43B240D08B3` and a value e.g. `1000000000000000000`
9. When the MM Notification pops up, click the HEX tab and copy the raw transaction data e.g. `0xa9059cbb00000000000000000000000056f2e03c8d30649818c022a9759cf43b240d08b30000000000000000000000000000000000000000000000000de0b6b3a7640000`
10. Switch back to the Details tab, here you will notice the method name `Transfer` and the amount `1 link`
11. Click Confirm
12. `1 Link` is  transferred
13. Now lets create the same transaction from inside MM
14. Open the account Menu, click the Settings open
15. Click the `Advanced Menu`, enable `Show Hex Data`
16. Click the `Send` button on the Overview page, to send Goreli ETH
17. Enter the Link contract address `0x326c977e6efc84e512bb9c30f76e30c160ed06fb`
18. Click `I Understand`
19. Paste the raw transaction data copied above into the Hex data field
20. Click `Next`

Actual result:
Method: Contract Interaction
Amount: N/A
Total: Goerli ETH gas

Expected result:
Method: Transfer
Amount: 1 Link
Total: 1 LINK + Goerli ETH gas

Notes:
If you Edit the transaction then return to the confirmation screen, the correct method name and amount is shown

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
