### ISSUE TITLE
Re-Center MetaMask Title

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1730]
![screen shot 2017-07-03 at 3 28 36 pm](https://user-images.githubusercontent.com/542863/27809436-5b5b8ec2-6004-11e7-98a1-1b04a6034f60.png)

I simplified our title's flex management to make it less of a nightmare, and part of that makes the title just flex between the other elements.

Opening this to postpone fixing that awful CSS. Maybe we just remove that title, or left-align it or something.

**Comment by kumavis** [comment]
we have the fox logo - prolly can drop the name
