### ISSUE TITLE
[Bug]: Chain ID error preventing users to edit the RPC URL for an existing network

### ISSUE THREAD

**Issue by firebomb1** [MetaMask/metamask-extension#17314]
### Describe the bug

When editing the RPC input field of an existing network in the Settings, MetaMask reports an error about the network ID already being used (even if no other Network than the one you are currently editing uses it).

It makes it impossible to edit the RPC if the current one needs to be changed. The workaround is to delete the network and add it again, which is not very convenient.

I think this might have been introduced by https://github.com/MetaMask/metamask-extension/pull/16452

### Steps to reproduce

1. Add a network.
2. Try to edit the RPC URL with a new valid one for that same network.
3. Notice the Error message preventing you to Save the changes.

## Example Screenshot for Polygon
Existing Network:
![image](https://user-images.githubusercontent.com/88804546/213688614-2ff23dba-ee9e-413e-ad35-69b53071d6d7.png)

After editing the RPC URL:
![image](https://user-images.githubusercontent.com/88804546/213688680-ab0b8594-0692-48eb-a017-c6314a9143d6.png)

(Note: The Save button is disabled too)

### Error messages or log output

```shell
This Chain ID is currently used by the <Network_name> network.
```

### Version

10.23.3

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by danjm** [comment]
Closed by #17541, should be released by v10.26.0

**Comment by adamazad** [comment]
Hi @danjm, what's the ETA for v10.26.0?

**Comment by danjm** [comment]
it will begin roll out next week
