### ISSUE TITLE
[Bug]: No Warning appears when a Dapp sets a really high Fees for a tx, potentially loosing all user funds

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17313]
### Describe the bug

**Problem**: when a Dapp triggers a transaction/contract interaction, it sets the proposed fees `maxFeePerGas` `maxPriorityFeePerGas` and `gasLimit`. MetaMask takes the values from the Dapp as they are and displayes `Site suggested` meaning that it's the Dapp who suggested the fees. Despite of that, if the Dapp sets a high value, user can loose all its money and there is no warning on MM side. 

![image](https://user-images.githubusercontent.com/54408225/213667658-8b2fd7fc-09e0-4d42-bd7d-7c8cc0ff1fc2.png)

https://user-images.githubusercontent.com/54408225/213667706-01f68b91-d8e7-4b4b-b5af-2e1c3006dfa9.mp4

### Steps to reproduce

1. Clone test dapp https://github.com/MetaMask/test-dapp
2. Set some high fee values on lines `637` and `638`
```
maxFeePerGas: '0x38D7EA4C68000',
maxPriorityFeePerGas: '0x38D7EA4C68000',
```
3. Start test dapp: `npm start`
4. Go to localhost:9011
5. Connect MM
6. Click Send EIP1559
7. See suggested fees and no warning

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
As a solution, whenever the fee is equal or higher than our market suggestion, we should use the same warning color for the aggressive gas pricing option (Thanks, Mariona, for this suggestion!).
Question for design: should the orange warning sign be a tool tip with further explanation?
![image (4)](https://user-images.githubusercontent.com/34968356/214091878-42432b93-d7f9-4748-9f90-62e661c50bf2.png)

**Comment by holantonela** [comment]
Yes, let's mark following the Aggressive option. Orange is OK. 

> Question for design: should the orange warning sign be a tool tip with further explanation?
Do we have tooltips in other warnings? If yes, then yes. Something like `The Dapp suggesting gas is too high compared with other options. Consider it carefully.` or whatever @coreyjanssen approves here.

**Comment by coreyjanssen** [comment]
How about this? 
`This gas fee is much higher than the other options available.`
