### ISSUE TITLE
[Bug]: Cannot speed up 0 priority fee transaction

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17353]
### Describe the bug

If you submit a transaction with 0 Priority Fee, when you attempt to speed up the transaction with the default (default: increase the gas by 10%), the Priority Fee remains at 0. Therefore the transaction is underpriced and the user gets the following error

https://user-images.githubusercontent.com/53189696/214100015-019288ae-fd6c-43eb-9d9d-fe6309cc6000.mov

### Steps to reproduce

1. Login
2. Click `Send` on the overview page
3. Enter an address
4. Leave the default amount etc, Click `Next`
5. Click the `Market`, to edit the gas fees
6. Click `Advanced`, to enter custom gas fees
7. Change the `Priority Fee` to `0`, Click `Save`
8. Click `Confirm` to submit the transaction
9. Wait for the `Speed Up` button to appear on the activity log, the click it
10. Accept the default, Click `Submit`

Expected result:
I would expect we default to the `Market - Priority Fee` when the user speeds up a transaction that had a Priority Fee of 0. Please confirm with the confirmation team

### Error messages or log output

```shell
Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32000,"message":"replacement transaction underpriced"}}
```

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
@filipsekulic can you take a look at this. Seems related to https://github.com/MetaMask/metamask-extension/pull/16651

**Comment by ElvirCe** [comment]
@bschorchit Can you please confirm that the Expected results are ok and that we can proceed with the fix?

**Comment by bschorchit** [comment]
I confirm it, @ElvirCe. ✅ Good suggestion, Peter!

**Comment by ElvirCe** [comment]
@bschorchit as discussed this will be handled by ticket #17547 so I will unassign this ticket from PS Team.
