### ISSUE TITLE
Add "<<" and ">>" icons

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17367]
Blocked by https://github.com/MetaMask/design-tokens/issues/283

### Description
Add `arrow-double-left` and `arrow-double-right` icons to the Icon component

### Technical Description
- Add provided svgs to the `app/images/icons`

### Acceptance Criteria 
- There are "<<" and ">>" icons

### References
- https://github.com/MetaMask/metamask-extension/pull/17093
- https://github.com/MetaMask/design-tokens/issues/283
- https://github.com/MetaMask/metamask-mobile/issues/5584

**Comment by Akatori-Design** [comment]
@garrettbear @georgewrmarshall 

Added two new icons in design
- `arrow-double-left`
- `arrow-double-right`

[*Figma link](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=4387%3A15247&t=CrexktlzsCWdyB7u-4)

[📎 Icons sprite file ](https://drive.google.com/file/d/18hcFlr49sE2n1lp2ybZZz-9x0YGXGowx/view?usp=share_link) (this sprite contains both icons above)

Reference
@georgewrmarshall 's guide for [Export icons as optimized svgs for code](https://www.notion.so/Export-icons-as-optimized-svgs-for-code-daf05f66cf2e44fc8306d48a3cbbb930)
I already went thru the guided steps and optimized, exported the sprite file, which is what u see above.

**Comment by georgewrmarshall** [comment]
@garrettbear you will have to extract the paths and create 2 new svgs
