### ISSUE TITLE
[Bug]: Insufficient balance Warning for paying fees points to the incorrect token

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17371]
### Describe the bug

**Problem**: when I don't have enough gas for paying fees, if I try to send a token in that network, I get a warning, saying I don't have enough of that Token for paying fees, instead of the protocol token (in this case ETH), which is the one used to pay gas. And it also recommends buying that token, instead of the protocol token (ETH).

![image](https://user-images.githubusercontent.com/54408225/214274358-8a2aa475-78f5-4291-b50e-54444e33873c.png)

https://user-images.githubusercontent.com/54408225/214274484-9cb6c1f0-d578-4bd4-998b-15ea52820dcf.mp4

### Steps to reproduce

1. Select an Account with no ETH and with a Token 
2. Click the Token
3. Click Send
4. Add recipient -- see how warning appears, and it mentions you don't have enough of that Token, instead of ETH

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by AlexHerman1** [comment]
ZD 998837 in the wild.
