### ISSUE TITLE
Reinstalled metamask and cannot recover account

### ISSUE THREAD

**Issue by jorge964** [MetaMask/metamask-extension#1737]
I don't have much hope but just in case....

I deleted the metamask chrome extension and then installed the newest version.  I went to enter my pass phrase and.... some how I only have 11 words and not 12!!! :( :(

Is it there a posibility that I can restore the previous installation from may be the chrome local storage files?

I see the following files that I think are related (in linux):
chrome-extension_pkedcjkdefgpdelpbcmbmeomcjbeemfm_0.localstorage
chrome-extension_pkedcjkdefgpdelpbcmbmeomcjbeemfm_0.localstorage-journal
chrome-extension_nkbihfbeogaeaoehlefnkodbefgpgknn_0.localstorage
chrome-extension_nkbihfbeogaeaoehlefnkodbefgpgknn_0.localstorage-journal

The EOS site seems to be trying to use nkbihfbeogaeaoehlefnkodbefgpgknn because I'm getting this error:
SyntaxError: Unexpected end of JSON input

Error: SyntaxError: Unexpected end of JSON input
    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8237:28386)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8238:28122
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8214:5
    at nrWrapper (https://eos.io/js/monitoring.js:1:11483)

Have I lost the ETH I sent or can it be recovered from the local storage files?

**Comment by AlexanderTserkovniy** [comment]
I have all 12 words and after pasting them it says just the seed phrase is incorrect. How is that possible?

**Comment by kumavis** [comment]
@jorge964 yes you may be able to recover from the chrome extension files or your 11 seed words (by using a program to guess the missing word)

**Comment by jorge964** [comment]
@kumavis I haven't been able to recover it from the chrome extension files. Do you (or anyone) know how to do it?

About that program to guess the 12th word having the other 11. Could you direct me to one that works?

**Comment by kumavis** [comment]
im not sure of one that exists but it could be created

**Comment by jorge964** [comment]
Any indea of how to create it? from what dictionary? I'm a programmer so I can do it myself and  make it available to the public ;)

**Comment by flyswatter** [comment]
The seed word module used is this:
https://www.npmjs.com/package/bip39

Good luck!  Share any progress!  Leaving open until we can document this recovery process.

**Comment by tmashuang** [comment]
Closing old issues.

**Comment by readyrod69** [comment]
I had to remove my metamask from chrome and redownload the newest version. Since I re-downloaded it I have been unable to log in. It says my seed phrase is invalid. How can that be? I have used it to recover in the past, and only am running into this issue now. Does anyone have any suggestions?

**Comment by readyrod69** [comment]
I had to re-download the metamask chrome extension and now I am unable to access my account which has thousands of dollars in it. It says my seed phrase is invalid when I try to recover my account, does anyone have any suggestions? I have recovered before without any issue
