### ISSUE TITLE
[Bug]: User cannot update the RPC url of an existing network

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17399]
### Describe the bug

You cannot update the RPC URL of an existing network
The form shows the update as a Warning and not an Error, however the changes cannot be saved as the button is disabled

https://user-images.githubusercontent.com/53189696/214433274-c67f8344-b62a-4e5b-8784-9774e61e2c40.mov

### Steps to reproduce

1. Login
2. Click the account menu
3. Click the `Settings` option
4. Click the `Networks` sub menu item
5. Select a custom network
6. Update the RPC URL

### Version

10.25

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
@PeterYinusa My guess is that this is also a bug in prod, probably pre-existing even v10.24.0, and so is not a release blocker

**Comment by danjm** [comment]
repro'd on v10.23.0
![Screenshot from 2023-01-25 08-53-25](https://user-images.githubusercontent.com/7499938/214562523-b0ff792e-86a7-4a69-8b1a-b7ee0e71d2fa.png)
