### ISSUE TITLE
[Bug]: Transaction Security check feature is not properly hidden behind a feature toggle

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17396]
### Describe the bug

The `Transaction Security check` feature is not properly hidden behind a feature toggle

<img width="1616" alt="transaction security" src="https://user-images.githubusercontent.com/53189696/214427556-5777c34a-1ca9-4952-8355-e3a645267d81.png">

### Steps to reproduce

1. Login
2. Open the account menu
3. Click `Settings`
4. Click `Experimental`
5. Enter `transaction security` in the search field

### Version

10.25

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
@filipsekulic is this something you can look into, seems related to https://github.com/MetaMask/metamask-extension/pull/16830

**Comment by filipsekulic** [comment]
> @filipsekulic is this something you can look into, seems related to #16830

@PeterYinusa 
I checked it from the `develop` branch and it seems to be working properly. 
Maybe you didn't set the feature flag `TRANSACTION_SECURITY_PROVIDER=1` within the `.metamaskrc`?

https://user-images.githubusercontent.com/92310504/214515452-d74cc525-b6ca-4847-8ea3-c34f1d5e323e.mov

**Comment by danjm** [comment]
@filipsekulic I think issue that Peter is pointing out is that if `TRANSACTION_SECURITY_PROVIDER=1` is not set, it is still possible to see it in the search results on settings
