### ISSUE TITLE
[Bug]: portfolio dapp popover overlaps multiple components

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17398]
### Describe the bug

Portfolio dapp tooltip overlaps the Account details modal 
<img width="1616" alt="portfolio 1" src="https://user-images.githubusercontent.com/53189696/214430275-64359c09-188f-4061-85a4-8e51be4b0707.png">

Portfolio dapp tooltip overlaps the switch network modal in the popover view
<img width="366" alt="portfolio 2" src="https://user-images.githubusercontent.com/53189696/214430280-aebe7c51-fe98-4b9b-a88a-cd5c76e02618.png">

### Steps to reproduce

Scenario 1:
1. Login
2. Click the ellipsis menu
3. Select account details

Scenario 2:
1. Login
4. Close the extension
5. Switch networks
6. Open the popup

### Version

10.25

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
@amerkadicE can you take a look at this, seems related to https://github.com/MetaMask/metamask-extension/pull/17084

**Comment by bschorchit** [comment]
I see this ticket is in review lane but I don't see the linked PR to it. Could you share the link for it, @amerkadicE @ElvirCe ?

**Comment by amerkadicE** [comment]
Done @bschorchit

**Comment by amerkadicE** [comment]
Resolved with [this PR](https://github.com/MetaMask/metamask-extension/pull/17722)
