### ISSUE TITLE
Issue receiving ETH

### ISSUE THREAD

**Issue by catchganu** [MetaMask/metamask-extension#1740]
Transferred some ETH yesterday and it is yet to be received in Metamask wallet. 

How long does it take. 

Transferred from coinspot.com.au to my metamask wallet , chrome browser used. 

Transaxtion status complete in coinspot.com.au. 

Please assist

**Comment by tmashuang** [comment]
Does your etherscan.io of your account reflect your updated balance?

**Comment by flyswatter** [comment]
Closing until we get some feedback. Feel free to open an issue on our support center:
http://metamask.consensyssupport.happyfox.com
