### ISSUE TITLE
[Bug]: Large SignTypedData_v4 messages are slow to load and choppy to interact with

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#17402]
### Describe the bug

See the original report from OpenSea [here](https://consensys.slack.com/archives/CN2H44RAM/p1674591647260549) and further discussion [here](https://consensys.slack.com/archives/C03ETQA9EPK/p1674593202131819).

### Steps to reproduce

Repro steps [here](https://consensys.slack.com/archives/CN2H44RAM/p1674591647260549)

### Version

10.24.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

It was suggested [here](https://consensys.slack.com/archives/C03ETQA9EPK/p1674594020085219?thread_ts=1674593202.131819&cid=C03ETQA9EPK) that doing more of the improvements done [here](https://github.com/MetaMask/metamask-extension/pull/17052) could be a possible solution to this issue.

**Comment by jpuri** [comment]
I tried to reproduce it using test data shared [here](https://consensys.slack.com/archives/CN2H44RAM/p1674591647260549). But it is fairly fast with latest V10.24.01 release downloaded from [here](https://github.com/MetaMask/metamask-extension/releases).


https://user-images.githubusercontent.com/2182307/214832905-148aff43-7f0e-4339-be4f-36d4651eb9b7.mov
