### ISSUE TITLE
[Bug]: Can't Import Custom Tokens using Local Network "ChainId 0x539 is not supported"

### ISSUE THREAD

**Issue by NightBus9** [MetaMask/metamask-extension#17414]
### Describe the bug

When I try to add a custom token in a local network (in my case using Ganache, chainId: 1337) it doesn't appear in the list after submitting. The console throws the following error: "ChainId 0x539 is not supported" 

### Steps to reproduce

- Connect to local network i.e. Ganache (localhost)
- Deploy a ERC20 token contract
- "Import Custom Token" (input contract address, Symbol)
- “Add custom token” 

### Error messages or log output

```shell
sentry-install.js:76 Error: TokenService Error: ChainId 0x539 is not supported
  at common-0.js:1:3113
  at Generator.next (<anonymous>)
  at s (common-0.js:1:2017)
```

### Version

10.24.1

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by oare** [comment]
Issue has already been raised here: https://community.metamask.io/t/error-tokenservice-error-chainid-0x539-is-not-supported/23451

**Comment by polus-arcticus** [comment]
> Issue has already been raised here: https://community.metamask.io/t/error-tokenservice-error-chainid-0x539-is-not-supported/23451

just highlighting rick121212's temporary work around from that thread
```Hi,

Thanks for the advice but this is a MetaMask problem, not a Hardhat problem. I fixed the issue by using the standard Hardhat chain ID 31337 which now works with MetaMask.
```

**Comment by handanyolak** [comment]
Same issue here.

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
