### ISSUE TITLE
[Bug]: Fiat Conversion is displayed while having the feature OFF for Binance Chain on the Approve screen for ERC20 and ERC721

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17428]
### Describe the bug

**Problem**: when I switch off the fiat conversion option under the Privacy Settings, I expect to see no fiat conversion. Despite that, I can still see one fiat conversion on the Approve screen, while using Binance Chain, both for ERC20 and ERC721 tokens.

Relates to https://github.com/MetaMask/metamask-extension/pull/16772

![image](https://user-images.githubusercontent.com/54408225/214821410-991049d0-aa85-44f1-aa12-c6c806bb138f.png)

### Steps to reproduce

Disable the Fiat conversion on Settings.

**For ERC721:**
1. Go to https://bscscan.com/token/0xADc466855ebe8d1402C5F7e6706Fccc3AEdB44a0#writeContract
2. Connect MM
3. Cliick Write Contract
4. Click Approve function
5. Add address and id (any number)
6. Click Write
7. See MM prompt and fees displayed in fiat

https://user-images.githubusercontent.com/54408225/214824513-29bd8a95-b8d1-4df5-b574-8d67f10735d1.mp4

**For ERC20:**
1. Go to https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8#writeContract
2. Connect MM
3. Cliick Write Contract
4. Click Approve function
5. Add address and amount (any number)
6. Click Write
7. See MM prompt and fees displayed in fiat

### Version

10.24.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by SaratAngajalaoffl** [comment]
I see that the setting disables fiat conversion only on the home screen, is this the intended outcome? If not can I work on it?
