### ISSUE TITLE
[Bug]: Switching from Binance chain to any other Network displays Token symbol and Picture from BNB

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17429]
### Describe the bug

**Problem**: when I am on Binance Chain, if I then switch to another network I can still see the Token symbol and picture from BNB

https://user-images.githubusercontent.com/54408225/214825089-c1922920-1a19-488c-aa11-f259a8af65ba.mp4

### Steps to reproduce

(Edit, added by danjm, copied from the comment below)
0. "Turn of the the following Privacy setting, Security & Privacy -> Transactions -> Show balance and token price checker"

1. Add Binance Chain network
2. Change to Binance Chain network
3. Now add Polygon network
4. Switch to Polygon network -- BNB symbol and picture are still displayed

Note: I have all Privacy features OFF (not sure if it's related)
Note2: the balances are correct for each network

### Version

10.24.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I have been seeing this more frequently happening to me as well.

**Comment by bschorchit** [comment]
The same just happened to me now.
I was in BNB, turned off the token balance and price checking toggle and then changed to Ethereum (screenshot). I then went to settings and turned the same toggle on, closed the settings and saw the token name and symbol being updated on the home screen.

![Screenshot 2023-01-26 at 17 18 36](https://user-images.githubusercontent.com/34968356/214942190-dcb6ac55-8d13-43b0-adeb-8c682ea81357.png)

**Comment by PeterYinusa** [comment]
Steps to repro:

1. Turn of the the following Privacy setting, `Security & Privacy` -> `Transactions` -> `Show balance and token price checker`
2. Following the steps [above](https://github.com/MetaMask/metamask-extension/issues/17429#issue-1557994680)

**Comment by seaona** [comment]
A couple of more findings - probably already figured it out:

This happens to any network - not exclusively to Binance:

https://user-images.githubusercontent.com/54408225/215042773-270c7023-0919-453d-b80c-bdbb76ca8cdb.mp4

I encountered The error `StreamProdiver - unknown response id for response [Object Object]` error, while making a tx and seeing the wrong network symbol. MM stayed loading indefinitely until I refreshed.
Not sure if this one is related to this, or do you think we open a separate bug for that? @PeterYinusa @danjm 

https://user-images.githubusercontent.com/54408225/215043263-62fd6afe-22da-4720-8311-c88d106c4e66.mp4

**Comment by seaona** [comment]
I think the bug I mentioned on the comment above it's not related to this issue. I found the repro steps and opened a separate issue here
https://github.com/MetaMask/metamask-extension/issues/17467

**Comment by seaona** [comment]
As @NiranjanaBinoy observed, this issue is now fixed by this PR https://github.com/MetaMask/metamask-extension/pull/17450
