### ISSUE TITLE
[Bug]: Optimism fee on Approve ERC20 Confirmation screen displayed with wrong alignment (on the left instead of right)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17426]
### Describe the bug

**Problem**: when I am on the Optimism network, if I try to approve an ERC20 token I can see how the fees value is displayed on the left instead of on the right.

Also, not sure how many decimals should we display in this value,as I believe it should be the same value as Gas fee right? @bschorchit @danjm 

![image](https://user-images.githubusercontent.com/54408225/214812716-0220caf1-0708-407d-b610-88c375a852c3.png)

### Steps to reproduce

1. Change to Optimism network
2. Go to Etherscan to interact with an ERC20 token https://optimistic.etherscan.io/token/0x94b008aa00579c1307b0ef2c499ad98a8ce58e58#writeContract
3. Click Connect MM
4. Accept MM
5. Click Approve and Add spender and amount
6. Click Write
7. Add any amount on MM
8. Click Next
9. See alignment for fees

### Version

10.24.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
✨ Acceptance criteria for the fix:
1. The alignment should be similar to what we have for the the same transaction on the old token allowance screen (screenshot)
2. The amount of decimals show for layer 2 gas fee should be same as we currently show for layer 1 gas fee - this is a new requirement as the old token allowance had the same issue

Screenshot:
![Screenshot 2023-01-26 at 10 08 52](https://user-images.githubusercontent.com/34968356/214899190-09ed19a7-3d39-4be7-a15d-5f3c08c61bd3.png)

**Comment by VSaric** [comment]
Hey @seaona and @bschorchit, I pull latest changes from `develop` and when I try to reproduce this issue I can't reproduce it because in the `background.html` console throws `Error: PollingBlockTracker - encountered an error while attempting to update latest block`.  The message is `project ID does not have access to optimism l2`. 

You can see that in the screencast below:

https://user-images.githubusercontent.com/92527393/223705433-f8febd71-8a30-408f-9153-38b136a63362.mov

Do you know maybe what is the problem with this? I will move this ticket in `Pending Consensys` and I will return to work into this issue when this error is fixed.

cc: @danjm

**Comment by bschorchit** [comment]
I believe the issue is with the Infura project ID that you're using. You need to use one that has Optimism L2 enabled for it. 
If try testing on the prod build of MM, you'll see this error not happening.

**Comment by bschorchit** [comment]
@danjm and/or @seaona might have a project ID (or know how to get one) for testing it in develop

**Comment by VSaric** [comment]
Yes @bschorchit, I also think the issue is with the Infura project ID. @danjm or @seaona could you send me on slack or comment here the Infura project ID for Optimism L2 if you have one? 
Thank you in advance!

**Comment by VSaric** [comment]
> ✨ Acceptance criteria for the fix:
> 
> 1. The alignment should be similar to what we have for the the same transaction on the old token allowance screen (screenshot)
> 2. The amount of decimals show for layer 2 gas fee should be same as we currently show for layer 1 gas fee - this is a new requirement as the old token allowance had the same issue
> 
> Screenshot: ![Screenshot 2023-01-26 at 10 08 52](https://user-images.githubusercontent.com/34968356/214899190-09ed19a7-3d39-4be7-a15d-5f3c08c61bd3.png)

Hey @bschorchit, can you explain me a bit further about this second point that you mentioned here?

**Comment by bschorchit** [comment]
We should use the same amount of decimals that are showing up for `Gas fee` and `Total `on the screenshot above
