### ISSUE TITLE
Make main site "Install Extension" link browser-aware

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1744]
Right now we only have "Install Chrome Plugin" on our main page. We should detect the browser, and show the appropriate install button.

**Comment by flyswatter** [comment]
Or even just having a Firefox addon link too. 
addons.mozilla.org/en-us/firefox/addon/ether-metamask

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/landing/pull/58.
