### ISSUE TITLE
[Bug]: For setApprovalForAll, the copy when revoking doesn't fully match the copy when giving allowance

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#17469]
### Describe the bug

We've updated the copy for setApprovalForAll when giving allowance recently, but we didn't update it for when revoking to match. 

Current copy when revoking:
1. `Revoke permission to access all of your <NFT>?`
2. `By revoking permission, the following account will no longer be able to access your <NFT>`

Suggested update when revoking (to be reviewed by @coreyjanssen):
1. `Revoke permission to access and transfer all of your <NFT>?`
2. `This revokes the permission for a third party to access and transfer all of your <NFT> without further notice.`

### Steps to reproduce

1. Go to https://etherscan.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#writeContract
2. Connect your wallet
3. Go to setApprovalForAll
4. Input any address and `false` for the approved(bool) parameter
5. Click write
6. See the MM popup and notice the red button

### Version

10.24.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Screenshot for when giving allowance:
![Screenshot 2023-01-27 at 13 00 10](https://user-images.githubusercontent.com/34968356/215131564-1d269eea-91c7-4a08-83b9-740cf27ac5a2.png)

Screenshot for when revoking allowance:
![Screenshot 2023-01-27 at 12 55 23](https://user-images.githubusercontent.com/34968356/215130935-6eaac355-2949-4ca1-ad84-202478499d0b.png)

**Comment by coreyjanssen** [comment]
@bschorchit's proposed copy looks good to me!
