### ISSUE TITLE
feature - calculate balance based on pending txs

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1746]
We should include all pending transactions (max cost) in the calculation of account balances.

not only for display, but for when checking for sufficient balance for the new transactions to be signed.

**Comment by flyswatter** [comment]
A user got burned by this recently, when this happened:

1. Tried to send a tx
2. The tx was re-submitting for a while
3. Some other tx resolved, and they had insufficient funds now.
4. The tx retry marks it as insufficient funds, and stops retrying.
5. Some incoming transfer raises their balance to sufficient.
6. One of the transmitted txs is now accepted by a miner and processed.

**Comment by flyswatter** [comment]
I now have a branch, `i1746-BalanceBasedOnPending` that is able to calculate a remaining balance from an account's balance and its pending transactions.

Question is, where should we apply it? I see three possibilities right now:

1. At the UI layer, always show a balance that accounts for pending transactions (and their max gas costs)
2. In the send form, disallow sending a tx that might exceed the balance, once accounting for pending transactiosn and their max gas costs.
3. In the transaction manager, move any transaction to a failed state if its cost would exceed the current account's balance, accounting for pending txs and their max gas costs.

**Comment by frankiebee** [comment]
i would assume that this dosent really apply to the transaction manager and is more about ethStore

**Comment by frankiebee** [comment]
as in failing a tx because of too low a balance isnt something we do now so i think we just provide a getBalance for the ui to use and continue the pattern of not allowing the user to approve

**Comment by flyswatter** [comment]
That would require `ethStore` to have access to the transaction manager, while right now it's mostly about caching chain state. Plus if we do it at the ethStore level, our logs will no longer reflect network state.

Since this data can be computed from the current state, I don't think it should be added to the state or used to replace any other state, I think it should just be computed where it's needed, to preserve a single source of truth.

**Comment by frankiebee** [comment]
i would imagine it would be coordinated in the metamask controller

**Comment by flyswatter** [comment]
So just for rejecting new txs, then? No validations on the form itself, even though we could?

**Comment by frankiebee** [comment]
i like 4

**Comment by frankiebee** [comment]
or turn off resubmit 😅

**Comment by kumavis** [comment]
I suggest we create a small obs-store (maybe wrapped in a small controller) that calculates an estimated balance based on the eth-store and the tx-controller

**Comment by danfinlay** [comment]
Re-opening this because we reverted the change. This feature would still save people money.
