### ISSUE TITLE
🏁 Remove SIWE feature flag

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#17461]
## Background
Follow up for when the feature is completed. These 2 issues need be closed to unblock this:

- [ ] https://github.com/MetaMask/metamask-extension/pull/16616
- [ ] https://github.com/MetaMask/metamask-extension/pull/16222

## Steps to Reproduce
1. Go to Metamask's [Test Dapp](https://metamask.github.io/test-dapp/) and scroll down to the Sign-In with Ethereum section. (If the dapp doesn't have this https://github.com/MetaMask/test-dapp/pull/164, [use this version](https://spruceid.github.io/test-dapp/)).

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
