### ISSUE TITLE
🏁 Remove transaction security provider feature flag

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#17460]
## Background
Follow up for when the feature is completed. These 3 issues need be closed to unblock this:

- [ ] https://github.com/MetaMask/metamask-extension/issues/16258
- [ ] https://github.com/MetaMask/metamask-extension/issues/16262
- [ ] https://github.com/MetaMask/metamask-extension/issues/16636

## Acceptance Criteria
1. The toggle is now visible to all users under Settings > Experimental
2. The What's new modal is displayed to users
3. When toggle is on, whenever the users receive transaction or signature request, data is shared with and received from the security provider and a warning is shown to the user if the security provider flagged the request as malicious.

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
Targeting this for 10.27 release which will be cut on Monday.

cc: @ElvirCe @filipsekulic
