### ISSUE TITLE
[Bug]: ethereum.request() error response is being pipe to a popup window

### ISSUE THREAD

**Issue by FidelVe** [MetaMask/metamask-extension#17479]
### Describe the bug

Browser: Brave
OS: Ubuntu

Im developing an application with React and have the following code:
```
async function someFunction(params) {
  try {
    const response = await window.ethereum.request({
      method: "eth_sendTransaction",
      params: [params]
    })
    return response;
  } catch (err) {
    return err;
  }
}
```

im expecting to catch anything, either the `ethereum.request` result on success or any error being thrown. 

the problem im seeing is that it appears that metamask is piping the error response to a popup window in the OS and because of this I dont get any return from my `someFunction` 
![photo_2023-01-28_17-46-38](https://user-images.githubusercontent.com/43641727/215292564-43019c4b-33ee-4272-a782-3db7b81c28dc.jpg)

when the error response gets send to the OS popup window I have nothing in my code to catch or return.

### Steps to reproduce

N/A

### Version

10.23.3

### Build type

None

### Browser

Brave

### Operating system

Linux

**Comment by CharlesBlaqk** [comment]
@FidelVe We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by xinnanyemm** [comment]
Please note that `label:team-dapp-api` has been replaced by `label:team-devex` . Thanks.
