### ISSUE TITLE
UX: Replace all FontAwesome Icons with New Icons

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#17475]
### Description
In an effort to reduce inconsistencies it would be great to replace all Fontawesome icons with their `<Icon>` or `<ButtonIcon>` component equivalent. This is a massive undertaking by itself and creating a single PR would be too large. Instead this issue should be broken up into multiple PRs. 

### Technical Details
- Search for Fontawesome icons in the codebase by searching `fa fa-` and swap it out for the `Icon` component equivalent

### Acceptance Criteria
- All Fontawesome icons have been replaced with their `Icon` equivalent
- PR contains a **minimum of 1 file** and a **maximum of 3 files**
- Add Before / After screenshots to your PR to ensure no visual regressions
- Reference this issue in the description of your PR
- All CI tests are passing jest, lint, e2e etc

PRs that don't meet the acceptance criteria may be closed.

### References
[`Icon` component documentation](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-icon--docs)
[`ButtonIcon` component documentation](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-buttonicon--docs)

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with running the extension locally, have knowledge of React, component props, Jest tests, linting, and Storybook, and want to contribute to improving the cohesiveness of UI in the extension

**Comment by ankit-jds** [comment]
Can you please assign this issue to me??

**Comment by georgewrmarshall** [comment]
I think this issue is probably quite large to hit in one PR but if it helps we could isolate the icons we currently have that we could swap out and pick one? This is pretty rough and I could break these up into separate issues but if anyone would like to create a PR to swap out any of these FontAwesome icons with the [Icon component](https://metamask.github.io/metamask-storybook/?path=/story/components-componentlibrary-icon--default-story) and `ICON_NAMES` object equivalent heres a good visual reference.

We still need to add the ones in red but there should be available replacements for anything that has an `ICON_NAMES` next to it

![Screenshot 2023-02-05 at 9 18 30 PM](https://user-images.githubusercontent.com/8112138/216889920-4cf66ff5-35c8-4bef-860b-b621cddd40e5.png)
![Screenshot 2023-02-05 at 9 18 37 PM](https://user-images.githubusercontent.com/8112138/216889922-3f8f3275-ae8d-48b1-b37b-770678f39f2f.png)
![Screenshot 2023-02-05 at 9 18 45 PM](https://user-images.githubusercontent.com/8112138/216889926-c8e83ece-2181-460a-83cd-d8b36a19c4c1.png)
![Screenshot 2023-02-05 at 9 18 57 PM](https://user-images.githubusercontent.com/8112138/216889927-08e7fcdd-1bb0-49b9-ac26-314e6614e709.png)
![Screenshot 2023-02-05 at 9 19 03 PM](https://user-images.githubusercontent.com/8112138/216889929-4c52916b-d93b-43dc-916c-98ce90a4adde.png)

**Comment by NidhiKJha** [comment]
Thanks, George! That's the idea, we are not going to add a single PR to update all the icons instead we will be creating multiple PRs to update each icon and then we are planning to update this issue accordingly.

**Comment by spiritanand** [comment]
Hey @NidhiKJha and @georgewrmarshall 

I would love to help you guys in replacing all the icons (one PR at a time)
Could you direct me to an issue that was created that looks to solve this?

**Comment by georgewrmarshall** [comment]
@spiritanand tagged you in https://github.com/MetaMask/metamask-extension/issues/17670

**Comment by moheet333** [comment]
Hi @darkwing  is the issue available to work on? new to open source here can you help me where to start?

**Comment by sambhavgupta0705** [comment]
Hey @NidhiKJha and @georgewrmarshall 
I would like to contribute to this issue:)

**Comment by georgewrmarshall** [comment]
Hi @VedanthB, Thanks for your contribution but I believe @NidhiKJha has a PR open for this task https://github.com/MetaMask/metamask-extension/pull/17539. If you would like to contribute to the extension code base you could help replace Typography with Text and submit a PR against this issue https://github.com/MetaMask/metamask-extension/issues/17670

**Comment by VedanthB** [comment]
> Hi @VedanthB, Thanks for your contribution but I believe @NidhiKJha has a PR open for this task #17539. If you would like to contribute to the extension code base you could help replace Typography with Text and submit a PR against this issue #17670

Hey @georgewrmarshall , I see that all the tasks have PRs raised for this issue #17670 but some have review comments that are not addressed , should I pick one of those ?

**Comment by georgewrmarshall** [comment]
Hey @VedanthB, this issue represents a task that can be broken up into multiple smaller PRs. Do a search for `<Typography` in the code base and pick a file that's not listed here. Comment on the issue and I can add it to the list that you are going to work on it

<img width="977" alt="Screenshot 2023-03-28 at 1 30 53 PM" src="https://user-images.githubusercontent.com/8112138/228359633-8d3d6c96-ec0d-441e-8ce0-dff9f5c7c2b0.png">

**Comment by RohanJacob23** [comment]
Hi @georgewrmarshall,
I have raised a PR to replace "fa-lock" icons, can you please review it.

**Comment by shyamtawli** [comment]
Hey, Is this is open?

**Comment by georgewrmarshall** [comment]
Hey @shyamtawli, yes it is. I've updated the issue description hope that helps

**Comment by iamenochlee** [comment]
is this still open? can i work on this? @georgewrmarshall

**Comment by georgewrmarshall** [comment]
Hey @iamenochlee, yes. The `ICON_NAMES` object has been deprecated in favour of the `IconName` enum but the name should be the same. Just the casing the is different

**Comment by AdeJulius46** [comment]
@georgewrmarshall    Single PR file ? can you please expantiate this is my first time working on an open source

**Comment by georgewrmarshall** [comment]
Hello @AdeJulius46,

Apologies for not being clearer earlier. To facilitate the review process and increase the likelihood of your PRs being merged, it's best to submit PRs that modify only a single file. This approach significantly simplifies the review process for our team.

Before submitting a PR, please ensure you have the extension running locally. This step is crucial as it enables you to provide the necessary before and after screencasts or screenshots, which are invaluable for our review process. Thank you for your contributions and understanding!

**Comment by ShivCharanSharma** [comment]
Hi @georgewrmarshall,

I've created a pull request https://github.com/MetaMask/metamask-extension/pull/26657 that addresses the following changes:

- Replaced the lock icon in the following
   - Setting tab bar.
   - Setting search bar option/suggestions.
   
Please let me know, if any further changes are needed or if there are any queries for the same.

Thank you

**Comment by georgewrmarshall** [comment]
Thank you for your contribution, @ShivCharanSharma! I'll review it shortly. In the meantime, I'm going to close this issue as we are re-evaluating our approach to icons.

**Comment by ShivCharanSharma** [comment]
> Thank you for your contribution, @ShivCharanSharma! I'll review it shortly. In the meantime, I'm going to close this issue as we are re-evaluating our approach to icons.

Thanks for informing @georgewrmarshall 

Meantime, I'll explore other existing issues in the repo. But yeah, if you would like to suggest any specific issue, it will be really appreciated 💯
