### ISSUE TITLE
[Bug]: Cannot send ETH to a Multisig `Unable to determine contract standard` and `Cannot convert string to buffer`errors appear

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17488]
### Describe the bug

**Problem**: when I try to send ETH to a multisig Gnosis Safe wallet, the transaction fails and I get the following errors:

- `Error: Unable to determine contract standard at AssetsContractController`
- `Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: 0xa021.8`

https://user-images.githubusercontent.com/54408225/215474800-9cd49f9b-a000-4807-a908-97e75fdf5f54.mp4

### Steps to reproduce

1. Select Goerli
2. Click Send
3. Add Multisig recipient address `0x0C1DD822d1Ddf78b0b702df7BF9fD0991D6255A1`
4. Add amount 0 -- see `Error: Unable to determine contract standard at AssetsContractController`
5. Click Next
6. Confirm tx -- tx fails with error `Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: 0xa021.8`

### Version

~10.24.1~ 10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I was not able to reproduce this on 10.24.1 following the repro steps. Maybe there's another step needed?
See my transaction to this address: https://goerli.etherscan.io/tx/0x9931c012b9f69ff3de48c4ac2aa151b42bd2589e15a0e98ab2dbd2230fd90772

**Comment by seaona** [comment]
@bschorchit I added the wrong address on the repro steps. Could you please try now with the new address on step 3? Sorry for the inconvenience!

**Comment by bschorchit** [comment]
I was not able to reproduce it on 10.24.1 in prod with the above repro steps. See my transaction here: https://goerli.etherscan.io/tx/0xc00f6b4de78aca362302d79972e661da0832bf088df8198bff771af5fd

Are you maybe in different dev build? Or did an additional step before? I see that you're on goerli but the native asset is being displayed as ETH.

**Comment by bschorchit** [comment]
Oh ops, sorry I deleted the previous comment to re-write it. I'll try again now :)

**Comment by bschorchit** [comment]
My transaction was successful (see [here](https://goerli.etherscan.io/tx/0x31358a622190cd2e15f21280bb41df13a59efca079b60ace259d5b7c3ff5222a)), but I did see the contract interaction confirmation screen and `Error: Unable to determine contract standard at AssetsContractController`.

**Comment by seaona** [comment]
Thank you for your feedback @bschorchit I've added a missing information piece - transaction does not go through when amount is 0. Could you try again with that?

This reveals that there are 2 separate issues. One for the Contract Standard, and the other, when we add amount 0.
If you confirm that you are seeing the error with amount 0, then I'll separate this into 2 different tickets as they seem different issues

**Comment by bschorchit** [comment]
I've now just re-tested it using the 10.24.1 dev build that @seaona shared with me and I was able to repro this issue.
My transactions failed locally and the console printed `Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: 0xa021.8`.

**Comment by bschorchit** [comment]
I've added the `regression-RC` label bug as this is likely a bug being introduced in 10.25 cc: @PeterYinusa

**Comment by PeterYinusa** [comment]
Thanks for highlighting this @bschorchit, I can repro this issue on develop but not on v10.25.0, I'll remove the RC label

**Comment by segun** [comment]
Some update on this issue:

First things first: can someone please send me some GoerliETH? I'm trying to fix this issue. ;)

Now this error is coming from @metamask/assets-controllers repo. The AssetContractController is only aware of 3 standards 
```
ERC721
ERC1155
ERC20
```
The contract created for multisig is none of these so the first error is thrown `Error: Unable to determine contract standard at AssetsContractController`.
It will be also difficult to check for this contract type as the multisig contract doesn't implement the ERC-165 interface. 

None of this should pose a problem though, as the UI code ignores exceptions thrown by this method and UI code should still work normally. 

I'm not able to proceed to send the transaction yet, I need some ETH to test that. 

My guess right now though is this: There's some code in the UI that didn't correctly handle this exception. I need to be able to debug/trace the send flow for multisig address to be able to confirm this for sure.

**Comment by segun** [comment]
More Info

This commit 3ff12d70e9a07d2efb35afde6577d95a8f77a0f5 seems to have introduced a bug on [this line ](https://github.com/MetaMask/metamask-extension/blob/3ff12d70e9a07d2efb35afde6577d95a8f77a0f5/ui/pages/send/send.utils.js#L66)

the toString() method on that line produces this hex value `a021.8`

@brad-decker can you please advice? I am not completely sure that that method does.

**Comment by seaona** [comment]
Another extra information in case it's useful.
I've noticed that if you try to Send to a Multisig address using the Test-Dapp, the transaction succeeds and the error does not appear. While if I then try to Send it using the Send flow from inside MetaMask, the tx fails immediately.

https://user-images.githubusercontent.com/54408225/216961417-0c727fa2-d7f9-4649-afa2-f7f7b283a93c.mp4

**Comment by jpuri** [comment]
Hey @segun : have you started with work on this task. If yes can you plz move it.

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by segun** [comment]
@seaona @bschorchit this could be closed now - fixed here https://github.com/MetaMask/metamask-extension/pull/17651

**Comment by bschorchit** [comment]
Awesome, Olu! Thanks!!
