### ISSUE TITLE
[Bug]: Metamask is blocking all IPFS urls, breaking OpenSea and other sites

### ISSUE THREAD

**Issue by robpolak** [MetaMask/metamask-extension#17480]
### Describe the bug

IPFS Urls getting blocked with this message:

https://metamask.github.io/phishing-warning/v1.2.1/#hostname=ipfs.io&href=https%3A%2F%2Fipfs.io%2Fipfs%2FQmSBnsELjNQbhLVbf6w7UMGFVT35UhK4DfePpDJwQVtxDN%2F1832&newIssueUrl=https%3A%2F%2Fgithub.com%2Fphishfort%2Fphishfort-lists%2Fissues%2Fnew

This domain is currently on the MetaMask domain warning list. This means that based on information available to us, MetaMask believes this domain could currently compromise your security and, as an added safety feature, MetaMask has restricted access to the site. To override this, please read the rest of this warning for instructions on how to continue at your own risk.

Broken NFT Page on OpenSea : https://opensea.io/assets/ethereum/0x59468516a8259058bad1ca5f8f4bff190d30e066/1832

created a phishfort ticket as well : https://github.com/phishfort/phishfort-lists/issues/332

### Steps to reproduce

1. Navigate to any IPFS data url : https://ipfs.io/ipfs/QmSBnsELjNQbhLVbf6w7UMGFVT35UhK4DfePpDJwQVtxDN/1832

### Version

10.23.3

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Ledger

**Comment by danjm** [comment]
@robpolak We believe this has been resolved, can you confirm?

**Comment by robpolak** [comment]
Fixed!  Thanks!
