### ISSUE TITLE
Create detailed document / plan for confirmation page frontend refactoring on extension

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#17483]
We need to prepare a detailed plan/roadmap for confirmation page refactoring on extension.

Here is documentation in progress: https://github.com/MetaMask/metamask-extension/tree/conf_structure_doc/refactoring

Ref: https://docs.google.com/document/d/1D6buCHOSSkj-hKSbcYUNDIEGlBhTki5oYsh-0trGJkg/edit?usp=sharing

Outcomes:
- Complete the documentation
- Discuss the plan with confirmations team and other more experienced devs from extension team also and get / incorporate their feedback
- Create epics + prioritised tasks in github for refactoring

**Comment by jpuri** [comment]
I created this PR: https://github.com/MetaMask/metamask-extension/pull/17742
I plan to discuss this in office hours this week.

**Comment by jpuri** [comment]
I created this PR: https://github.com/MetaMask/metamask-extension/pull/17742
I plan to discuss this in office hours this week.

**Comment by seaona** [comment]
might be that the link for Documentation in progress is broken?

**Comment by bschorchit** [comment]
Closing as all linked PRs have been merged.
