### ISSUE TITLE
Remove Flask code fences around Snap features

### ISSUE THREAD

**Issue by ritave** [MetaMask/metamask-extension#17489]
With Snaps coming into the main extension, Flask code fences need to be removed.

Code fences look like this:
```typescript
///: BEGIN:ONLY_INCLUDE_IN(flask)
(code here)
///: END:ONLY_INCLUDE_IN
```

There a few places that the fences need to stay in due to:
* localhost snaps being installable only in Flask
* Few permissions only allowable in Flask
* Allow list only existing in stable extension

**Comment by kenhkan** [comment]
From refinement: This is to be done after the release.

**Comment by kenhkan** [comment]
From business sync: This is irrelevant as it's handled by the extension team.
