### ISSUE TITLE
Setup a process for creating a new release candidate to address problems found during the beta

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17493]
Our desired RC process is this:

1. As per existing process, create a Version-v#.#.# branch, and push it to our github repo
2. CircleCI scripts recognize the pattern branch name, generate s "Version v#.#.# commit" and create a RC PR
3. QA happens on the RC PR
4. Once we approve the RC, we push a commit with the message/name "Version v#.#.#-beta.0" to the RC branch
5. CircleCI scripts recognize the commit name, triggering automated generation of a Prod beta build. This build is what gets submitted to chrome stores
6. If bugs are found in beta, we fix them and then cherry-pick the fixes into the RC branch. Once we have picked all the fixes we want to release, push a new "Version v#.#.#-beta.1" commit to the RC branch
7. Repeat step 6 until we are ready to finalize v#.#.#, then we add one more commit that updates the version to remove the beta modified from the version name.
8. Once the build on that commit is complete, we merge

Currently, steps 1 and 2 are already working, however we should modify them so that the version they bump package.json to is `#.#.#-alpha`, and the commit name should reflect this as well

We need to add automation for steps 4-7

The specific pieces we need are:

- [ ] if a commit with the name "Version v#.#.#-beta.#" is pushed, then a circleci job runs that creates a prod beta build and then posts that build to the RC branch via a MetaMask bot comment
- [ ] it would be good to have a local script for creating a beta commit. We should be able to do something like `yarn generate-beta-commit` and then the version in package.json in updated and a new commit is added
- [ ] if a commit with the name "Version v#.#.#" is pushed, then a circleci job runs that creates a prod main build and then posts that build to the RC branch via a MetaMask bot comment
- [ ] add a circleci job that only runs on branches with the name `Version-v#.#.#`, which will fail the build if the version number has not bee updated to `#.#.#`

See https://github.com/MetaMask/metamask-extension/issues/10757

**Comment by DDDDDanica** [comment]
A. generate-beta-commit in /development
=> get current version of package.json, if it’s not a beta version, -0; +1
=> Pass to yarn version to update package.json
=> Commit: git add, git commit -m xxx, 
=> Push 

B. Trigger cli to yarn build

**Comment by DDDDDanica** [comment]
https://github.com/MetaMask/metamask-extension/pull/17749
