### ISSUE TITLE
Trigger a "beta" build when a non-hotfix release candidate is ready to publish

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17494]
Our release automation scripts should recognize this scenario and trigger a "beta" build rather than a production build, using the beta release version (which is of the format X.Y.Z-beta.N, where X.Y.Z will be the final production version after it passes beta, and N is the beta build number, starting at 0)

**Comment by DDDDDanica** [comment]
Requirement breakdown:

- Create a release branch locally `git checkout -b Version-v10.25.0`
- Add a commit to trigger beta build `git commit -m "Version-v10.25.0-beta.0"`
- Push to release branch, trigger the creation of new PR, and start the automation process `git push`
- Include a new comment in the MR on behalf of bot, eg: "build for beta v10.25.0-beta.0" base on last commit #17272"
- Use the `prep-build-beta` script to initiate a prod data build, and post the downloadable version in the comment
