### ISSUE TITLE
[Bug]: SIWE Warnings display symbols miss-aligned

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17510]
### Describe the bug

**Problem**: when I am on the SIWE confirmation screen for a Bad Domain or Bad Account, I can see that the symbols from the warning are miss-aligned.

![SIWE1](https://user-images.githubusercontent.com/54408225/215792590-a7708c66-22e6-4037-bb7c-8618fa599f91.png)

![SIWE2](https://user-images.githubusercontent.com/54408225/215792607-74535c41-a13b-4838-b3d5-c728e01d7f2b.png)

**Expected**: I am expecting to see symbols alignes as we have in the rest of the screens. Example:

![warning](https://user-images.githubusercontent.com/54408225/215792842-7ea85de7-962a-42ca-968e-33c9330b57d5.png)

### Steps to reproduce

1. Go to https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Sign in With Ethereum (Bad Domain) -- see MM popup with miss-aligned symbol
4. Click Sign in With Ethereum (Bad Account) -- see MM popup with miss-aligned symbol

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
@holantonela tagging you as you have the most context on this. These warnings are probably being deprecated, right? With [the new PR](https://github.com/MetaMask/metamask-extension/pull/16616)? Or is it only the first one that is?

**Comment by holantonela** [comment]
yes, i think so. We decided to reject it if the sender domain does not match with the txn details without warning users (there is not a recovery flow for that warning).

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by holantonela** [comment]
After https://github.com/MetaMask/metamask-extension/pull/16616 merge we are not exposing this error to users anymore.
