### ISSUE TITLE
[Bug]: ERC20 Approve screen displays missleading copy, referring to a Contract, when it's an EOA

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17520]
### Describe the bug

**Problem**: when I am approving an ERC20 token, I can see that the previous field called `Granted to` which displayed the address to whom I am giving permissions, now displays `Contract requesting spending cap`.
That copy is miss-leading as in some cases I can approve to an EOA instead of a Contract. See example below:

https://user-images.githubusercontent.com/54408225/215833209-06388b26-980e-4b46-b516-a93e2b29e08b.mp4

### Steps to reproduce

1. Select Mainnet
2. Go to https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#writeProxyContract
3. Connect MM
4. Click Approve
5. Add a MM address
6. Add a value
7. Click Write
8. See MM prompt
9. Click Contract details -- see text copy

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/16587. A PR is up to address this here https://github.com/MetaMask/metamask-extension/pull/18101
