### ISSUE TITLE
Replace all fa-check icons with equivalent Icon component

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17526]
### Description
In an effort to replace all font-awesome icons with the new `Icon` component it would be great to replace all `fa-check` and `<IconCheck />` components with the `Icon` equivalent

One way to find all the `fa-check` icons would be to search "fa-check"

![Screenshot 2023-01-31 at 1 18 02 PM](https://user-images.githubusercontent.com/8112138/215885556-67dadd03-422b-4336-ac84-4ee438599206.png)

Same with `<IconCheck`

![Screenshot 2023-01-31 at 1 20 28 PM](https://user-images.githubusercontent.com/8112138/215885848-97a3115c-8345-4c14-aa85-a90c24dc95a7.png)

### Technical Details
- Replace all `fa-check` font awesome icons with `<Icon name={ICON_NAMES.CHECK} />`
- Replace all `<IconCheck` font awesome icons with `<Icon name={ICON_NAMES.CHECK} />`
- Use `import { Icon, ICON_NAMES } from '../../component-library'` path will be subject to change depending on where it is being imported from 

### Acceptance Criteria 
- All `fa-check` have been replaced with their `<Icon name={ICON_NAMES.CHECK} />` component equivalent
- All `<IconCheck />` have been replaced with their `<Icon name={ICON_NAMES.CHECK} />` component equivalent
- PR includes screenshot of before and after of all instances can do it in the code comments if it makes more sense

### References
- [**Icon component documentation in storybook**](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-icon--default-story#icon)

<img width="958" alt="Screenshot 2023-01-31 at 1 21 36 PM" src="https://user-images.githubusercontent.com/8112138/215886277-0c8c2524-3812-467a-a0bd-9e9dbe6c9de7.png">

**Comment by shyamtawli** [comment]
Hey @georgewrmarshall I like to work on this.

**Comment by georgewrmarshall** [comment]
Assigned. Thanks @spiritanand and thanks for your interest @shyamtawli I'll continue to keep updating "good first issues" with more tasks 🙏

**Comment by spiritanand** [comment]
@georgewrmarshall will my infura API key be my infura project ID in .metamaskrc file?

**Comment by georgewrmarshall** [comment]
Hey @spiritanand that's correct!

**Comment by spiritanand** [comment]
OK got that. I am having a tough time getting Metamask to run locally. Is there a way to build and test my code live rather than rebuilding it each time?

**Comment by spiritanand** [comment]
@georgewrmarshall do we have to change .snap files? I am guessing no, right…

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, answers to your questions below 

_do we have to change .snap files? I am guessing no, right…_
no, `.snap` files are jest snapshots they should update when you update snapshots during testing

_Moreover, how do we plan to purge the CSS for the now redundant fa-check class?_
Once all of the `fa-` have been removed we can remove font-awesome stylesheet

_Also, I am having difficulty in enabling live reloading for the project. I have to rebuild and load the package each time I make a change. Can you help me with that?_
Yes, the extension does not have the best hot reload I'm afraid even I don't know how to improve that experience, if there is a story(`.stories.js`) file for the component you are changing you could view it in storybook `yarn storybook`

**Comment by spiritanand** [comment]
@georgewrmarshall does that mean that we cannot hot reload most of the components in the extension, and we will have to rebuild and upload after each iteration?

**Comment by spiritanand** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/53999998/216600719-2db2c19b-3fc5-4363-9532-18ee05805a46.png">
Over here, after I changed the icon to `<Icon name={ICON_NAMES.check} className="editable-label__icon" />` I cannot see it anywhere, even though the code has successfully changed. Am I making a mistake, or is this a colour issue?

**Comment by spiritanand** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/53999998/216682468-655d46dc-df6b-4368-8b76-4bc5d356b6fd.png">
Before (font awesome <i/>)

<img width="301" alt="image" src="https://user-images.githubusercontent.com/53999998/216682532-6fd88a0e-70af-4d6a-ad7d-a83b197da2c5.png">
After (<Icon/> component used)

Am I going right?

**Comment by georgewrmarshall** [comment]
@spiritanand yes exactly, thats the expectation for this ticket :)

**Comment by spiritanand** [comment]
@georgewrmarshall do I need to ensure the colours stay the same? Because in the case below it is inheriting the default color.
<img width="355" alt="image" src="https://user-images.githubusercontent.com/53999998/216691987-0d1b6a98-9192-4e53-a956-530fcf1a93b6.png">

**Comment by spiritanand** [comment]
@georgewrmarshall there is a spacing issue in the metametrics.js file Icon component
<img width="359" alt="image" src="https://user-images.githubusercontent.com/53999998/216705357-3b7c129d-238c-409f-995b-99b99377a73b.png">
 

it is supposed to be like
<img width="391" alt="image" src="https://user-images.githubusercontent.com/53999998/216705402-df122598-6bae-4868-8eb6-07173e68c33b.png">

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, the Icon component should accept all [Box component props](https://metamask.github.io/metamask-storybook/?path=/docs/components-ui-box--default-story#props) is it possible to space using `marginRight`? e.g.

```jsx
<Icon name={ICON_NAMES.CHECK} marginRight={1} />
```

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, you should be able to view this component in storybook by running `yarn storybook` and going to the `PermissionsRedirect` story by searching it in the search bar. Here is the hosted version on Github pages https://metamask.github.io/metamask-storybook/?path=/story/pages-permissionsconnect-redirect-permissionsredirect--default-story

For Icon sizes you can use the `size` prop and the `ICON_SIZES` object https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-icon--size-story#size apologies the docs storybook area seems to be broken it should be directing to this story https://metamask.github.io/metamask-storybook/?path=/story/components-componentlibrary-icon--size-story

**Comment by spiritanand** [comment]
Permission redirect went
from 
<img width="356" alt="image" src="https://user-images.githubusercontent.com/53999998/217162201-cb2d5b70-9d6b-440f-aaba-90f9f5522cc8.png">

to
<img width="313" alt="image" src="https://user-images.githubusercontent.com/53999998/217162243-0a2cd6b5-04cd-433c-b54d-fa10ed8d8d00.png">

I found permission redirect and new account components and updated their code 👍.

However, I could not find a few components in the storybook as well as the live testing (from build) in my browser.

Those components are:-

-  ui/components/app/dropdowns/network-dropdown.js
-  ui/components/app/flask/update-snap-permission-list/update-snap-permission-list.js
- ui/components/ui/form-field/form-field.stories.js
- ui/pages/settings/networks-tab/networks-list-item/networks-list-item.js

What should I do to check if the code has been updated the right way for them?

**Comment by georgewrmarshall** [comment]
You could update the permission redirect with `ICON_NAMES.CONFIRMATION`

<img width="492" alt="Screenshot 2023-02-07 at 3 50 30 PM" src="https://user-images.githubusercontent.com/8112138/217393330-c6e6ace1-44a9-4da4-ad22-8c4c3c314a61.png">

Yup. We are missing some components in storybook which makes it harder to track down the visual update in the app. A bit of overhead but what I've done in the past iscreate a story for those components. It's pretty quick to get a story up and running if the component doesn't require redux state. You can use the documentation guidelines


<img width="1379" alt="Screenshot 2023-02-07 at 3 52 47 PM" src="https://user-images.githubusercontent.com/8112138/217393583-5809b820-2085-41c3-9bdb-a8ba2f8f335b.png">

**Comment by spiritanand** [comment]
Yup, @georgewrmarshall I figured it out. Everything is working as expected. I am pushing the code and creating a PR for you to review. Cheers 🎉
