### ISSUE TITLE
Add deprecation message to Button

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17549]
### Description
In an effort to improve new design system component adoption and to prevent further duplication of components from continuing to be used we could add a JS doc deprecation notice to the Button component in `ui/components/ui/button`. We may then be able to add an es-lint rule to highlight deprecated components in the code base in another issue.

Deprecation notice to add at the above the component of all icon files:

e.g. in `ui/components/ui/button/button.component.js`

```
const typeHash = {
  default: CLASSNAME_DEFAULT,
  primary: CLASSNAME_PRIMARY,
  secondary: CLASSNAME_SECONDARY,
  warning: 'btn-warning',
  danger: 'btn-danger',
  'danger-primary': 'btn-danger-primary',
  link: 'btn-link',
  inline: CLASSNAME_INLINE,
  raised: CLASSNAME_RAISED,
};

/**
 * @deprecated please use the <Button /> component in ./ui/components/component-library/button/button.js
 */

const Button = ({
  type,
  submit = false,
  large,
  children,
  icon,
  className,
  rounded = true,
  ...buttonProps
}) => {
```

In VS code we should see when hovering on the component

![Screenshot 2023-02-01 at 1 21 29 PM](https://user-images.githubusercontent.com/8112138/216166107-c4023020-c83d-45e1-a73e-f9d40d7ffbfc.png)

### Technical Details
- Add JS Doc deprecation notice to all button component in `ui/components/ui/button/button.component.js`
- Add deprecation notice to `ui/components/ui/button/button.stories.js`

### Acceptance Criteria
- There is a deprecation notice in button.js
- There is a deprecation notice in button story

**Comment by spiritanand** [comment]
Would like to help. Am intrigued to see how it is implemented…

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, thanks for your interest! This ticket may need a little more refinement. I'll assign once I have added more details. Thanks!

**Comment by georgewrmarshall** [comment]
This has been completed
