### ISSUE TITLE
Add deprecation eslint rule so deprecated components aren't allowed

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17550]
### Description
To prevent further tech debt and duplication of old components in the code base it would be beneficial to add an eslint rule to prevent any old components from being used in new PRs.

An example would be adding a deprecation notice to the old Button component and having that prevent it from being used in any new code

![Screenshot 2023-02-01 at 1 37 31 PM](https://user-images.githubusercontent.com/8112138/216169100-77522f04-c974-4ffb-8a6a-aa6e894e634d.png)

![Screenshot 2023-02-01 at 1 37 47 PM](https://user-images.githubusercontent.com/8112138/216169101-78b9146f-03fc-46ef-ad5d-fc7e7d675d00.png)

### Technical Details
- Prevent any new code from containing functions with JSDoc `@deprecated` before hem
- Showing a squiggly line underneath deprecated components would also be beneficial 

### Acceptance Criteria
- Deprecated functions and components are flagged during `yarn lint`

### Reference
- https://github.com/gund/eslint-plugin-deprecation#readme (not sure this will work on non typescript files)

**Comment by spiritanand** [comment]
Would like to help!

**Comment by georgewrmarshall** [comment]
Hoping the engineer working on this ticket may have an answer to help complete this ticket https://github.com/MetaMask/metamask-extension/issues/18498#issuecomment-1512644019

**Comment by georgewrmarshall** [comment]
Hey @dj-pundir, I see. It's only works for TypeScript files in my VS Code. Show Deprecated is turned on but there is no strikethrough. Are you using Babel Javascript as your language?

![Uploading Screenshot 2023-04-19 at 10.53.05 AM.png…]()

**Comment by dj-pundir** [comment]
Hey @georgewrmarshall have you turn that feature on on your VS Code?

![image](https://user-images.githubusercontent.com/61174028/232972582-a6fd50fb-5def-4ebe-8d3b-9023ecae7928.png)

Also i am using Babel Javascript as language and no external extension for this feature.

**Comment by dj-pundir** [comment]
And I understand we will not say individual to go and update his VSCode settings :) 
So we can update this setting via code as well. Please confirm if that's the case then we can go ahead and modify it. Thanks!!

**Comment by georgewrmarshall** [comment]
Yes, Show Deprecated is turned on.
<img width="711" alt="Screenshot 2023-04-19 at 3 54 46 PM" src="https://user-images.githubusercontent.com/8112138/232984795-6c3dbd3c-84d5-4f6c-94f8-74b7e0b2b846.png">

**Comment by dj-pundir** [comment]
Great!!

What about javascript.validate.enable setting?

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/61174028/232986162-2294387f-5e36-4c8f-b3bc-20bc86ba5747.png">

**Comment by georgewrmarshall** [comment]
Ahhh awesome! That was it!! Thanks so much 🙏 I'm wondering if it's worth adding that setting to the `.vscode/settings.json` in the repo?

**Comment by georgewrmarshall** [comment]
I think we can close this issue. Deprecated components are now shown with a strike through so I think this is sufficient to enable engineers to know not to use it
