### ISSUE TITLE
Add friction to SRP reveal

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-extension#17557]
# Description

Following the implementation on mobile, it's necessary to develop the "Reveal SRP Quiz" on extension.

> _Through user testing it’s been shown that users are ignoring the warnings around SRP safety when they go to reveal their SRP. As such, it’s assumed that users ignoring these warnings are contributing in some way to phishing fund loss incidents._

Design: https://www.figma.com/file/4LQje3epQz8g4xO8fRdauv/SRP-Reveal-Warning?node-id=4119%3A13076&t=NlcYAWjU62vsTcXf-1

# Technical Details

- All the views must use the specified DS components
- All the code has to be written in TypeScript and any new component must be a functional component

# Acceptance Criteria

- Epic metrics in place
- Multiple languages supported
- The quiz is developed according the defined UI/UX using the current extension DS

# References

- [Epic file (Mobile focused)](https://docs.google.com/document/d/1kzI0BiBT9-6LuEp19lfZu0RV7wnXLOX24zg0r4uxK0A/edit#)

**Comment by raulmono** [comment]
Here's the Figma file updated with the extension pop-up and full-screen versions. 

I'm waiting for a final review from the DS team.

https://www.figma.com/file/4LQje3epQz8g4xO8fRdauv/SRP-Reveal-Warning?node-id=3796%3A12214&t=3ebpd1Xdgqs6rgJM-1
