### ISSUE TITLE
Incorrect insufficient token messages on send screen

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17576]
> When trying to send BUSD by clicking on the token, then pressing send, the extension has a warning message that suggests BUSD is needed to pay the gas fees, not BNB.  The same message appears when choosing an amount of the token that exceeds what I have in my wallet.

![image (11)](https://user-images.githubusercontent.com/7499938/216424485-3d16331a-3991-4ace-9e56-7b28f05bacff.png)

**Comment by bschorchit** [comment]
@seaona reported it first 😜 https://github.com/MetaMask/metamask-extension/issues/17371

**Comment by bschorchit** [comment]
Closing this in favor of the above
