### ISSUE TITLE
[Ext] Update component: TextField

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17585]
### Description
Complete the updates needed to align `TextField` to the insight report

### Technical Details
TBC

### Acceptance Criteria 
- `TextField` meets the criteria set in the insight report

### References
- [FigJam Audit & Insight Report](https://www.figma.com/file/aGW8sk6X6Jf9ac0MRMD4kX/TextField-Audit?node-id=0%3A1&t=ULa7Q5OYfNcoF78F-1)

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/metamask-extension/17585?planning-poker) with Zenhub @Akatori-Design @garrettbear @georgewrmarshall
