### ISSUE TITLE
[Bug]: Vague Error Message when Connecting to Locked Ledger

### ISSUE THREAD

**Issue by andrewpeters9** [MetaMask/metamask-extension#17606]
### Describe the bug

Vague error message for connecting to Ledger devices that are locked.  

> 🔴 NOTE: this might seem trivial but is likely quite confusing for first-time Ledger users.

### Steps to reproduce

1. Ensure that your Ledger is locked (i.e., the Ledger screensaver is showing on the device)
2. Connect to your Ledger without first inserting your pin
![image](https://user-images.githubusercontent.com/36251325/216836787-0fcb6d67-0138-4290-a0ed-e783ba902164.png)

### Version

10.24.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by flexa-rob** [comment]
During testing with my Ledger Nano X, the device was returning error code `0x6b0c` when locked. So I'll make it detect either `0x5515` or `0x6b0c` and we can also add any new lock codes to the list later if need be

**Comment by vivek-consensys** [comment]
Unable to replicate this issue, no error codes are displayed. Error displays as 'Unknown Error'. 
@AlexJupiter what should be the expected error message?

https://github.com/MetaMask/metamask-extension/assets/106310394/dee47aff-aef0-458e-8171-cc3d1653e83c

**Comment by angelcheung22** [comment]
https://github.com/MetaMask/metamask-extension/pull/21038
