### ISSUE TITLE
[Bug]: outdated Firefox add-on

### ISSUE THREAD

**Issue by kremalicious** [MetaMask/metamask-extension#17604]
### Describe the bug

The Firefox add-on is constantly outdated as mentioned in last years, like #15200 or #14774.

As of this writing, there were ~7 releases~ 8 releases over last ~3 months~ 4 months not reflected in the Firefox release. Current version there is v10.22.2 and was put there in November 2022. Multiple releases were announced on the official Twitter account, yet Firefox users are left out of all that.

As the only open-source browser made by a truly open source company with a proven track record, it best reflects the ethics MetaMask is upholding too. Firefox should be the default platform to optimize for instead of concentrating on all those corporate surveillance browsers first.

Given that the actual release builds are always in sync, is there any way to better automate publishing on the respective store in the end? Could not find anything in the codebase after a quick scan so I assume this happens manually right now?

### Steps to reproduce

1. Go to https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/
2. See that it's outdated
3. Pray to spaghetti monster that it might get updated in some months.

### Version

10.22.2

### Build type

None

### Browser

Firefox

### Operating system

Windows, MacOS, Linux, Other (please elaborate in the "Additional Context" section)

**Comment by kremalicious** [comment]
No shipping of the latest 8 releases to Firefox users with recent `10.25.0` release

**Comment by FrederikBolding** [comment]
@kremalicious I can confirm that `10.25.0` has been submitted to Firefox on the 20th of February and is still pending review. The review process on Firefox sometimes requires a manual review by a Firefox engineer and previously we have had issues with them not being able to reproduce our builds locally. We've recently reviewed and updated the build instructions and expect an approval when they get to us in the review queue.

**Comment by kremalicious** [comment]
Thanks! Can confirm `10.25.0` [showed up for Firefox](https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/).

Now that `10.26.1` is out, and at time of writing it is available in Chrome Web Store but not Firefox Add-Ons, I guess this issue can be left open still. Albeit unclear how to close it, which is on my plate for making issue title too broad. If this delay is only caused by slow Mozilla reviews, then feel free to close

**Comment by kremalicious** [comment]
Latest `v10.28.3` was listed in Firefox add-ons in like 1 day after release so considering this here fixed. Thanks for everything going on in background to nudge the review teams
