### ISSUE TITLE
Get on the prism support list

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1760]
Get on the prism support list (2)

https://blog.prism.exchange/blog/which-wallets-are-compatible-with-prism/

**Comment by tmashuang** [comment]
Closing since Prism is closing down. [Prism Shutting Down].(https://info.shapeshift.io/blog/2018/09/11/prism-is-shutting-down/?utm_campaign=Prism%20Closure%20Second%20Email&utm_medium=email&utm_source=Net-Results&utm_content=Prism%20Closure%20%23%202)
