### ISSUE TITLE
[Bug]: Automatic Hardware Wallet Connection

### ISSUE THREAD

**Issue by andrewpeters9** [MetaMask/metamask-extension#17605]
### Describe the bug

Metamask (MV2) will optimistically (forcefully) connect to a previously connected hardware wallet. Meaning that there can be some difficulties for those who own multiple hardware wallets, e.g. a Trezor and a Ledger, and want both of them connected on MM.

### Steps to reproduce

1. Import a Ledger hardware wallet account 
![image](https://user-images.githubusercontent.com/36251325/216836307-afaeb9cf-96e7-4d97-8c90-f0b5ed594041.png)
2. Add 1-2 ledger accounts on the account select page
3. Attempt to connect to a Trezor device and you'll be forcefully taken to the Ledger account selection list

### Version

10.24.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger, Trezor

**Comment by CharlesBlaqk** [comment]
@andrewpeters9 We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
