### ISSUE TITLE
[Bug]: Infinite Hang on Trezor Connect Page

### ISSUE THREAD

**Issue by andrewpeters9** [MetaMask/metamask-extension#17607]
### Describe the bug

The Trezor Connect popup occasionally hangs indefinitely.

![image](https://user-images.githubusercontent.com/36251325/216837042-ae904fb1-2f49-47b4-b367-463b0a56da8c.png)

### Steps to reproduce

I'll update this with more information the next time I run into it. 

It seems that this typically happens when the Trezor hasn't been used for a few days.

### Version

10.24.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

**Comment by aspiers** [comment]
For me the connect page just disappears without ever triggering activity on my Trezor.  Used to work fine on 2 out of 3 machines, but broke in this way sometime within the last week or so.  Not sure if it's the same issue or related to this infinite hang.

**Comment by axelblaze88** [comment]
> For me the connect page just disappears without ever triggering activity on my Trezor. Used to work fine on 2 out of 3 machines, but broke in this way sometime within the last week or so. Not sure if it's the same issue or related to this infinite hang.

Same here. I cannot sign my transactions, and that's worrying because it's part of my job. I can't find a solution. Mine is Trezor Model One. Please, devs, fix it!

**Comment by aspiers** [comment]
I'm not yet 100% sure but in my case I think this *might* have been caused by changing MetaMask's site access away from "On all sites":

![image](https://github.com/MetaMask/metamask-extension/assets/100738/a1217859-0f31-49d0-964e-39ca8bfe42a1)

**Comment by aspiers** [comment]
I can now confirm that changing MetaMask's site access back to "On all sites" fixed the problem.  Another way to do it is to go to https://connect.trezor.io/ and then explicitly allow access to that site:

![image](https://github.com/MetaMask/metamask-extension/assets/100738/e8e2ee44-4fc7-4270-ada4-459c71e615d3)
