### ISSUE TITLE
Update Story Links in Storybook Documentation

### ISSUE THREAD

**Issue by NidhiKJha** [MetaMask/metamask-extension#17619]
When https://github.com/MetaMask/metamask-extension/pull/17518 was merged it changed some storybook URLs since the story name was changed and as a result, the link references to those stories are broken. We will need to update internal and external links. This ticket is to update all internal links inside of the repo.

- A good start would be to search for `[(/docs` in `.mdx` files that point to component doc pages
- Then search for `](/story` in `.mdx` files that point to component story pages
- I would also do a very broad search `](/` and scan for any links that point to storybook pages

### Technical Details
- Update all URLs to stories in `.mdx` files to use the new URLS

### Acceptance Criteria 
- All links to stories in MDX docs work

**Comment by georgewrmarshall** [comment]
I think most of the broken stories will be the ones that conflicted with the enum names e.g. `Size` `SizeStory` etc so may not be as many. We could try searching `Story` in all `.stories.js` files. I think that could work
