### ISSUE TITLE
Create component: Select

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17615]
### Description
Create a reusable UI component for `Select`

### References
[Picker which includes Select audit FigJam](https://www.figma.com/file/ARJUQovVqX6QkGgiIpPOD3/Picker-Audit?node-id=0%3A1&t=srUuLIOpFDUOvCrv-1)
[Figma component](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=9827%3A75939&t=bKHqWvUZzKeJ66jj-1)
[UI component guidelines](https://www.notion.so/UI-Components-5ccd2bf83eb8441892a0b72c0d8929e1)
[Styling guidelines](https://www.notion.so/Extension-Frontend-Engineering-Guide-b82ddb3e14004b5db3799a9b446294a9#49aa2ef7b7aa40178ff918043df71c34)
Testing guidelines: TBC

### Files needed
- `index.js`
- `index.scss`
- `select.js`
- `select.stories.js`
- `select.test.js`
- `README.mdx`

### Technical details
TBC

### Acceptance criteria
- [ ] Uses color, typography, shadows design tokens 
- [ ] Uses semantic html
- [ ] PropTypes have descriptions
- [ ] Has storybook story with controls
- [ ] Has documentation in MDX
- [ ] Has unit tests and 90% coverage
- [ ] Works in Chrome and Firefox
- [ ] Performance tested: no unnecessary re-renders or other performance concerns

**Comment by spiritanand** [comment]
Hey @georgewrmarshall  , I would love to work on designing this component. Can I be assigned?

PS – Please recheck the links in the description, they were broken for me.

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, Thanks for your interest. This is an internal ticket. I believe anything that isn't assigned in "good-first-issues" is available. May I suggest checking out https://github.com/MetaMask/metamask-extension/issues/17670 and contributing toward replacing Typography with Text

**Comment by spiritanand** [comment]
@georgewrmarshall contributors can only contribute to good first issues?

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, I don't think we provide enough information in our issues and have internal conventions and documentation that aren't published publicly that would make this issue not an appropriate one for external contributors I'm afraid.
