### ISSUE TITLE
[FLASK] Sort snap permissions based on weight

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/metamask-extension#17623]
Each permission a snap can request will have a certain "weight". We want to sort the snap permissions in the overview based on this weight. For example, key management permissions should be higher up in the list, than the dialog or notify permission.

The weights for each permission are described in Notion.

**Comment by eriknson** [comment]
Related document overviewing all of our permissions including a column with suggested weights: https://www.notion.so/bac3299d2c5241c599d2e5e7986e72f7?v=ef742a61bd844435b7171bd2e90b447e
