### ISSUE TITLE
NFT V1 -- Feature Flag Removal

### ISSUE THREAD

**Issue by hilvmason** [MetaMask/metamask-extension#17628]

**Comment by PeterYinusa** [comment]
We're just finishing up with some remaining e2e tests to cover ERC1155 functionality this sprint. I will circle back once complete

**Comment by SaraCheikh** [comment]
Design review is done

**Comment by PeterYinusa** [comment]
We're in a good place now in terms of testing, and happy to remove the flag:
- good unit test coverage of nfts
- good e2e test coverage of nfts
- manual testing has been performed on the nft feature
