### ISSUE TITLE
Create "What's New" for NFTs

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#17637]
## Background
We'll be releasing NFT support on extension. The auto detection of NFTs will be behind an experimental toggle. When the user goes to the NFT tab, they'll see a notice saying we have NFT support enabled on extension, but to use the auto-detection NFT feature, they'll need to enable that via settings. Once enabled, that toast banner will not appear.

## Acceptance Criteria
Create What's New with the following suggested copy: 
We have enabled NFT support on MetaMask Extension! To view your NFTs, you can manually add them, or turn on the NFT auto-detection feature through settings [link]. We currently only support ERC-721.

**Comment by kevinghim** [comment]
@coreyjanssen can you please assist with the copy above?

**Comment by SaraCheikh** [comment]
Hi Kevin and @coreyjanssen [here the Figma file ](https://www.figma.com/file/ibAUJLZMdkeTam4R8pYdDz/What's-new-NFT?node-id=1%3A8502&t=vRo7mYHv55u91awZ-1)for the design with two su suggested options. @kevinghim I can't edit the ticket to add the link, would you mind adding it?

**Comment by kevinghim** [comment]
From our discussion, we should provide an alternative dark mode screenshot for users have have dark mode or system mode turned on. Some of our users use dark mode for accessibility reasons and we should be mindful of them. Sara, can you account for this in your designs?

@darkwing & @vthomas13 can you consider logic with What's New to display appropriate image based on theme setting?

**Comment by SaraCheikh** [comment]
DM already accounted for in design. I'm not using a screenshot for design, so switching themes is enough. Will export both them both in SVG. 
<img width="509" alt="Screenshot 2023-02-08 at 17 17 05" src="https://user-images.githubusercontent.com/98161559/217587448-c2f85fed-c4cf-45e2-a05c-252f63e04f19.png">

**Comment by coreyjanssen** [comment]
@kevinghim updated the 2 options in the Figma - lmk what you think!
