### ISSUE TITLE
[Bug]: Silent Ledger Failures on Various Popups

### ISSUE THREAD

**Issue by andrewpeters9** [MetaMask/metamask-extension#17630]
### Describe the bug

Issue explained via story:
* User initiates a transaction with an unlocked Ledger
* Confirmation Modal pops up, and no warning is present because the Ledger is unlocked
* Ledger locks while the Confirmation is open (e.g. the user may be hesitating the confirmation for a bit, or may be playing around with fees etc.)
* User hits "Confirm" and the transaction fails silently as the Ledger is now locked
 
Issue is applicable to Confirmation modals for transactions, signing typed data, signing messages etc.

### Steps to reproduce

1. Initiate transaction with Ledger
2. While on the confirm screen, wait for the Ledger to lock
3. Confirm transaction and you'll receive no notice of the confirmation failing

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by flexa-rob** [comment]
Looks like it's the same `0x6b0c` (`0x5515`) error code as #17606 

![image](https://user-images.githubusercontent.com/82925669/217386335-36ab75da-5d6a-4eae-8fe8-fa3bbea77f89.png)

**Comment by flexa-rob** [comment]
It also appears that you can reproduce the same error by initiating the transfer while the ledger is locked.
