### ISSUE TITLE
[Bug]: MetaMask - RPC Error: Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559 

### ISSUE THREAD

**Issue by FirstAsAlways** [MetaMask/metamask-extension#17641]
### Describe the bug

MetaMask - RPC Error: Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559 

### Steps to reproduce

1.

### Version

10.22.2

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by kevinghim** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/13862

**Comment by CharlesBlaqk** [comment]
@FirstAsAlways We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
