### ISSUE TITLE
[Bug]: Korean typo in home.html#onboarding/welcome

### ISSUE THREAD

**Issue by htamop** [MetaMask/metamask-extension#17661]
### Describe the bug

There is a typo

![image](https://user-images.githubusercontent.com/24317470/217539156-af3c82bb-1b2e-48de-be94-e5bb6ad5750c.png)

The word '사용히세요.' should be fixed to '사용하세요.'

The text in English is ...
```json
"welcomeExploreDescription": {
    "message": "Store, send and spend crypto currencies and assets."
  },
```

![image](https://user-images.githubusercontent.com/24317470/217539911-9f3a0957-c345-42e9-ac21-0a0c9da4edf9.png)

### Steps to reproduce

1. Install the metamask in the Chrome browser in Korean mode.
2. Run metamask
3. You can see typo 사용히세요. 

### Version

10.24.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by CharlesBlaqk** [comment]
@htamop We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
