### ISSUE TITLE
Revise old metrics schema for Onboarding v2

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#17669]
## Background
When implementing metrics for extension's new onboarding flow, we didn't account for the previously implemented metrics prior to the new data schema. After the release of v10.24, we noticed a bunch of old metrics mixed in with the new schema. This ticket will remove the old onboarding metrics.

## Acceptance Criteria
Please remove the following:
- Remove: `Analytics Preferences Selected`
- ONBOARDING_WALLET_IMPORT_COMPLETE: Change `Wallet Imported` to `Wallet Created`
- ONBOARDING_WALLET_SECURITY_PHRASE_REVEALED: Change `Key Material Revealed` to `SRP Revealed`
- ACCOUNT_PASSWORD_CREATED: Change `Wallet Password Created` to `Account Password Created`

**Comment by CharlesBlaqk** [comment]
@kevinghim We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
