### ISSUE TITLE
[Bug]: Opensea Not connecting to my profile 

### ISSUE THREAD

**Issue by samlogic-ship** [MetaMask/metamask-extension#17682]
### Describe the bug

Everytime I try to connect to Opensea, it doesn't recognize that my MetaMask extension is already connected.
as such I cannot login into Opensea

- If I click on MetaMask, it redirects me to the MetaMask chrome extension page
- I have to refresh and click on profile a few times in order to finally get lucky  

https://user-images.githubusercontent.com/113727328/217771475-ead4c9d1-e0e4-42a2-a4f7-85a0f9b739f5.mov

### Steps to reproduce

1. Not an expert but do refer to the video above 

### Version

10.24.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by CharlesBlaqk** [comment]
@samlogic-ship We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by danjm** [comment]
@samlogic-ship are you still experiencing this? If so, do you have other wallets installed? (They could be interfering with MetaMask's connection to opensea)

**Comment by danjm** [comment]
Closing as this is not currently reproducible and we recently addressed some issues regarding dapp connections (e.g. https://github.com/MetaMask/metamask-extension/pull/19727)
