### ISSUE TITLE
[Bug]: uint256 field being rendered as address in signTypedData_v4

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#17711]
This was reported by OpenSea [here](https://consensys.slack.com/archives/CN2H44RAM/p1675986657331309).

It seems that if their "counter" field is a uint256 but if it's exactly 20 bytes it formats/shows as an address. The correct behavior would be to only render it as an address if that parameter is of type address.

## Screenshots
<img width="362" alt="Screenshot 2023-02-09 at 6 39 05 PM" src="https://user-images.githubusercontent.com/34968356/218106145-4b79c410-03a6-4007-9e5e-fc73b38ff842.png">

<img width="362" alt="Screenshot 2023-02-09 at 6 39 05 PM" src="https://user-images.githubusercontent.com/34968356/218106164-a1ed22d5-ed37-4cc6-8c3b-8ba6f24ca340.png">

**Comment by FrederikBolding** [comment]
I opened a PR that fixes this, https://github.com/MetaMask/metamask-extension/pull/17846
