### ISSUE TITLE
[Bug]: unhelpful error handling at private key import time

### ISSUE THREAD

**Issue by abourget** [MetaMask/metamask-extension#17719]
### Description

When importing a private key, if the length is not right, the error message is unhelpful and looks like this:

```
Cannot read properties of undefined (reading 'startsWith')
```

For posterity, the problem I encountered was that the export of a private key from the Gnosis Safe Android application was _invalid_. It trimmed zeroes at the beginning of the string, making the private key of an invalid length.

Adding a simple validation of length, and alerting that it is not of valid length would have gone a long way to avoid the multi-day hassles I went through.

### Steps to reproduce

1. Get a private key
2. Remove its first character
3. Try to import

### Version, Browser, OS

10.24.2, Chrome, Mac OS

**Comment by danjm** [comment]
@HowardBraham this might be related to some of the private key error messaging improvements you looked into recently

**Comment by HowardBraham** [comment]
@abourget You figured it out!  The screenshot is in this issue #16895 but nobody could figure out steps to reproduce this error.

**Comment by HowardBraham** [comment]
Fixed by #17763
