### ISSUE TITLE
[Bug]: Experimental tab in settings is empty

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#17714]
### Describe the bug

In account settings, the experimental tab is empty and has no content.

<img width="923" alt="Screenshot 2023-02-10 at 15 27 33" src="https://user-images.githubusercontent.com/105063779/218119572-37329293-9c9b-4b37-817d-9b549102aaf5.png">

### Steps to reproduce

1. Login and go to settings.
2. Go to the experimental tab and check if it's empty.

Expected:
In Experimental tab, we should have:
- Enable enhanced gas fee UI
- Transaction security check

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by ryanml** [comment]
@chloeYue - looks like all the settings in the tab are feature flag dependent now: https://github.com/MetaMask/metamask-extension/blob/develop/ui/pages/settings/experimental-tab/experimental-tab.component.js#L228

So until that changes, I think we can just do the same flag check and not render the entire tab
