### ISSUE TITLE
[Bug]: `TypError: Cannot destructure property 'msgParams' of 'txData' as it is undefined.` when calling GetEncryptionKey

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17747]
### Describe the bug

**Problem**: when I call the Get Encryption Key function I land on the MetaMask Error page and see the error `Cannot destructure property 'msgParams' of 'txData' as it is undefined.`

https://user-images.githubusercontent.com/54408225/218747227-35aa3eee-7af6-4183-996c-299c8f838406.mp4

### Steps to reproduce

1. Open MM full view
2. On a new browser tab, go to Test Dapp
3. Connect to Test Dapp
4. Click Get Encryption Keys
5. Open MM full view
6. Accept -- land on Error page

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Next step: check if we can easily identify the commit that introduced this regression

**Comment by seaona** [comment]
It looks like this issue was introduced by this PR

https://github.com/MetaMask/metamask-extension/commit/b5c1de900de7fc83e3238930f3c6ae2fe2ca486c

**Comment by bschorchit** [comment]
Moved this to our Ready for Dev for this sprint

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
