### ISSUE TITLE
[Bug]: Error when updating a tx cannot proceed to Confirmation screen - `Invariant failed: A state mutation was detected between dispatches, in the path 'metamask.unapprovedTxs.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17745]
### Describe the bug

**Problem**: when I am in the process of performing a Send tx, if I go back to Edit the tx, I can see the error `Invariant failed: A state mutation was detected between dispatches, in the path 'metamask.unapprovedTxs.` and I cannot proceed on the Confirmation screen.

This happens when updating any of these fields:
- tx recipient
- asset
- amount

https://user-images.githubusercontent.com/54408225/218739814-0d671a8c-53f1-46d3-8381-11fa28a53b4f.mp4

### Steps to reproduce

1. Click Send
2. Add recipient
3. Add amount
4. Go Next
5. Click Edit
6. Edit recipient amount or asset
7. Click Next -- error appears and cannot proceed

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Next step: check if we can easily identify the commit that introduced this regression

**Comment by seaona** [comment]
It looks like this issue was introduced by this PR. Not 100% sure how though, looking at the changes but the previous commit to this one it worked, and on this commit it started failing

https://github.com/MetaMask/metamask-extension/pull/17586

**Comment by brad-decker** [comment]
@seaona did you see this bug only in dev mode or using a RC? This *type* of bug talking about state mutation is from #17508 where I added typescript and used reduxjs/toolkit -- if you see it again its related to that but it can happen anywhere we mutate state in an action. It *should only happen in develop as a warning to engineers to not use mutation of state* but if its happening in prod, test or rc builds we need to explore.

**Comment by seaona** [comment]
thank you v much for clarifying this @brad-decker !! I've double checked and indeed it's only happening on develop builds but not on production or test builds.
The only thing to notice is that now on dev builds you will need to perform 2x clicks whenever this Error happens. The first click triggers the error and does nothing, the second click performs the action.
If you confirm this is okay we can close the issue.

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by brad-decker** [comment]
@seaona I don't think we should allow the behavior, no, but I wanted to make sure we weren't shipping this behavior as I took steps to prevent it from happening in test/prod. However its annoying enough in development to keep tracking these issues and the reason I kept it on in dev is because mutation during state updates is bad and we should resolve it. I fixed this specific instance in 17772
