### ISSUE TITLE
[Bug]: Hovering on Settings Navbar makes appear text over navbar option

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17744]
### Describe the bug

**Problem**: when I open Settings and hover over the last menu options, I can see some text overlapping the menu option

https://user-images.githubusercontent.com/54408225/218725552-e4d95e26-7035-48cd-b325-a6e726aa2af1.mp4

### Steps to reproduce

1. Open Settings
2. Hover on left menu options

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by darkwing** [comment]
Weird; I couldn't reproduce this on Mac.
