### ISSUE TITLE
[Bug]: LavaMoat scuttling security feature is not correctly activated

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#17743]
### Describe the bug

After PR #17276 get merged, when LavaMoat scuttling security feature activated, user still able to access the scuttled properties of the window object:

https://user-images.githubusercontent.com/105063779/218722918-9eaa6456-1f43-4146-ac22-8a1f62e580a1.mov

### Steps to reproduce

1. Login, open the console
2. Type `window.alert(1)` 
3. Check if alert window appears
Expected: alert window should not appear, throws an error of how `alert` is a scuttled property

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
@weizman @kumavis

**Comment by weizman** [comment]
I can't reproduce this on eb2efc1612e26bc5b8e3fe3833a1ac4f165c090b

**Comment by PeterYinusa** [comment]
I also cannot reproduce it on v10.26 353c9927b4b66d678d0907b20520af05c4dbf916
```
runtime-lavamoat.js:11200 Uncaught Error: LavaMoat - property "alert" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
  at get (runtime-lavamoat.js:11200:17)
  at <anonymous>:1:8
```

**Comment by chloeYue** [comment]
Closed this issue as we cannot reproduce.
