### ISSUE TITLE
[Bug]: Tperror `Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.` when approving 2 pending transactions triggered from a Dapp

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17746]
### Describe the bug

**Problem**: when I trigger more than one tx from a Dapp, and I confirm the first one, when I confirm the 2nd one, I land on the MetaMask error page with the error `Type Error: Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.`

https://user-images.githubusercontent.com/54408225/218745094-0f94649d-22b9-4ee5-93b1-8f376e23c73a.mp4

**Notice**: since the popup will close right after, an effective way to reproduce this is to trigger 3 transactions instead of 2, this way the popup will not close and you'll see the error. Another way is to confirm the 2 transactions from the MetaMask full view

![image](https://user-images.githubusercontent.com/54408225/218744992-8778ede9-19e6-4a18-9a6b-9ce488a2bbee.png)

### Steps to reproduce

1. Go to test-dapp
2. Connect to test-dapp
3. Click Deploly Contract -- do nothing on MM
4. Click Deploy Failing Contract -- do nothing on MM 
5. Click Deploy Multisig Contract
6. Confirm one tx on MM
7. Confirm a second tx on MM -- error appears and you land on the MM error page

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Next step: check if we can easily identify the commit that introduced this regression

**Comment by seaona** [comment]
It looks like this issue was introduced by this PR

https://github.com/MetaMask/metamask-extension/commit/b5c1de900de7fc83e3238930f3c6ae2fe2ca486c

**Comment by bschorchit** [comment]
Moved this to our Ready for Dev for this sprint

**Comment by digiwand** [comment]
commenting out the new `unconfirmedMessages` code added around 2 weeks ago (https://github.com/MetaMask/metamask-extension/pull/17093) seems to remove the issue. This issue may or may not be related to those changes. This needs more investigation.
