### ISSUE TITLE
Advance the logging controller work

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17751]
This is the PR https://github.com/MetaMask/core/pull/1089

We need this on the extension for a number of reasons. We should help advance this PR and get it merged so that teams can start using it.

**Comment by bschorchit** [comment]
For reference: this is the [original issue](https://github.com/MetaMask/metamask-extension/issues/13694) that prompted the creation of such controller.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
