### ISSUE TITLE
Fix Flaky test: deletes a custom RPC

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17757]
See: https://app.circleci.com/insights/github/MetaMask/metamask-extension/workflows/test_and_release/tests?branch=develop

Screenshot Date: 22 Feb 2023
<img width="1616" alt="deletes a custom RPC" src="https://user-images.githubusercontent.com/53189696/220715769-381ef4b1-e73d-4771-8332-848a6e5baabc.png">

**Comment by Mherjee18** [comment]
Hi

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
