### ISSUE TITLE
Provide the ability to deploy a contract before creating the fixtures

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17752]
Currently, the `withFixtures` method in the e2e tests allows you to deploy a smart contract as well as provide a test fixture as an option.

This issue is created so that we can improve the method, allowing us to deploy a smart contract ahead of creating the fixtures.

This will allow us to use the contracts that we deploy inside the fixture.

One benefit of this is that we will no longer need to go through the import flow to import a newly added token, whether it be an erc20, erc721 or erc1155

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by PeterYinusa** [comment]
Closed by #18107
