### ISSUE TITLE
[Bug]: previously confirmed transaction notification closes existing transaction confirmation pop-up

### ISSUE THREAD

**Issue by ccosmincc** [MetaMask/metamask-extension#17768]
### Describe the bug

I am implementing a wrap functionality of a non-native coin which involves confirming 2 transactions: the "approve" transaction, followed by the actual "wrap" transaction. So I trigger the "approve" transaction, Metamask pop-up shows up asking me to confirm it, I confirm, transaction is sent and I get back a successful response. After that I trigger the "wrap" transaction which again opens up the Metamask pop-up for me to confirm, but in the meanwhile I get a (Windows) notification from Metamask that the "approve" transaction was confirmed. When this happens, if my "wrap" pop-up is opened, it will automatically close, leaving me unable to confirm the "wrap" transaction.
The only way I could make it work is to wait for 1-2 confirmations after I get the "approve" transaction response, in an attempt to syncronize with the Metamask (Windows) notification, and only trigger the second "wrap" pop-up after the notification was already sent, but this is very fragile, as I don't know exactly when will this notification be sent, so sometimes it works, sometimes not.

### Steps to reproduce

1. Trigger "approve" transaction (will open Metamask approve pop-up)
2. Confirm "approve" transaction in Metamask pop-up opened in step 1
3. When receiving result from step 2, trigger "wrap" transaction (will open Metamask wrap pop-up)
4. Keep pop-up from step 3 opened until you get a (Windows) notification that the transaction from step 1 was confirmed
5. Pop-up from step 3 closes automatically without any way of bringing it back

Expected result: at step 5, the pop-up should not close when the (Windows) notification is shown

### Version

10.24.2

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
