### ISSUE TITLE
[Bug]: Error occurs on approve screen for Binance Chain when approving ERC721 token

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#17770]
### Describe the bug

When I switch off the `Show balance and token price checker` option under the Privacy Settings,  and i try to use Binance Chain to approve ERC721 token, error message occurs on Approve screen.

https://user-images.githubusercontent.com/105063779/219100366-59129aa8-5187-4950-8c32-1e6f51e3cb3e.mov

### Steps to reproduce

1. Go to https://bscscan.com/token/0xADc466855ebe8d1402C5F7e6706Fccc3AEdB44a0#writeContract
2. Connect MM
3. Click Write Contract
4. Click Approve function
5. Add address and tokenId (any number)
6. Click Write
7. Check the error message on approve screen

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by danjm** [comment]
this was fixed by https://github.com/MetaMask/metamask-extension/pull/17772
