### ISSUE TITLE
[Bug]: Sign In with Ethereum: User can sign a message with bad account or malformed message

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#17781]
### Describe the bug

Sign In with Ethereum: user can sign in with bad account even there's error message displayed in confirmation screen:

https://user-images.githubusercontent.com/105063779/219384194-398b1a40-eab9-4e4b-a1e9-8ea240d2c5e4.mov

Sign In with Ethereum: user can sign in with malformed message, and no notice message displayed in confirmation screen:

https://user-images.githubusercontent.com/105063779/219384432-1a823929-f926-4a3f-9ef5-1a39b81d7824.mov

### Steps to reproduce

1. Login to the extension
2. Navigate to the [test dapp](https://metamask.github.io/test-dapp/)
3. Click `Sign In With Ethereum (Bad Account)`, confirm by clicking `Sign-In` button in confirmation screen.
4. Check that user can sign in and no error message is displayed in background console.
**Expected**: User should not be able to sign in with bad account and error message should be displayed in console.

5. Click `Sign In With Ethereum (Malformed)`, check malformed message notification is not shown on confirmation screen.
**Expected**: Malformed message notification should be shown on confirmation screen.

6. Clicking `Sign-In` button on confirmation screen.
7. Check that user can sign in and no error message is displayed in background console.
**Expected**: User should not be able to sign in with malformed message and error message should be displayed in console.

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by skgbafa** [comment]
Hello! This is the expected behavior. If a message is not a SIWE message, we default to the regular EIP-191 sign view. The malformed SIWE example is to demonstrate this flow. The error here is in the SIWE message presented by the dapp and the extension correctly doesn't render the SIWE view, but the normal personal_sign view.

**Comment by chloeYue** [comment]
Thanks @skgbafa for your response ! 

- For the malformed SIWE, i got it now that it's the expected behaviour, just the displayed message in dapp and in extension should be SIWE view but not normal personal_sign view, then could we fix the displayed views for this issue ? Then it will not mislead users.

- For the sign in with bad account, i assume the current behaviour is not correct and need fix. Could you confirm? Thanks !

**Comment by danjm** [comment]
@skgbafa can you confirm that if the warnings about addresses not matching is shown, we should still allow the user to sign?

**Comment by skgbafa** [comment]
Hi @chloeYue! For the malformed message, the current behavior is correct. We should show the normal personal_sign view. The SIWE view should not be shown. Perhaps a clearer name for `malformed message` is `non-siwe message`. 

For the bad account, the current behavior is correct. A clearer name for `bad account` is `mismatched account signer`. There are multiple valid reasons to sign a message with a different signer, including signing in on behalf of a smart contract, like a Gnosis Safe multisig wallet.

**Comment by chloeYue** [comment]
Ok, i see. Thanks @skgbafa

**Comment by chloeYue** [comment]
Closed this issue as it's the expected behaviour.
