### ISSUE TITLE
Unhandled rejection Error: Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by D-Nice** [MetaMask/metamask-extension#1778]
A previously working Dapp, is now broken with metamask since a recent update it seems. The Dapp interaction still works just fine with the parity browser extension. Above error is returned, indicating an invalid number of arguments, when the function has not been changed, and as mentioned used to work just fine even with metamask. The function call is promisifed using bluebird, if that may cause any incompatibilities.

Another issue, the race condition seems to have become worse, and the `load` event listener is seemingly not sufficient enough. Before it was pretty consistently injecting metamask's web3, now, however, it only does successfully on initial page loads, but refreshing the page, causes it to not be injected in time.

Browser: Chrome Version 58.0.3029.110 (64-bit)

Issue has been replicated on Mac/Linux/Windows

**Comment by flyswatter** [comment]
We updated our version of web3 [15 days ago](https://github.com/MetaMask/metamask-extension/commit/f285fd5eb1b8706da7bdb694543b96b7bed819f1), does that correspond with the time you saw the bug appear?

**Comment by D-Nice** [comment]
Ironically, the last time it worked/was tested other than today, was ~14 days ago, June 30th, and the commit is June 29th. Is it fair to presume the user testing it was on the newest metamask version at that time then?

**Comment by flyswatter** [comment]
It's very possible they had the older version of web3 at that time, and maybe something broke on web3. In your console with Parity, if you type `web3.version`, what does it read? We're now on `0.19.0`.

**Comment by kumavis** [comment]
as a dapp dev, you should always use your own version of web3
```js
window.web3 = new Web3(web3.currentProvider);
```

**Comment by CurrencyTycoon** [comment]
I had the same problem with my app.

The following code was working before, but it broke with "Error: Invalid number of arguments to Solidity function"

```
contractAt.transfer($address.val(), web3.toWei(v, "ether"), function (err, result) {
                                if (err) {
                                    console.log(err);
                                    return;
                                }
                             
                            });

```

The error went away by adding `.toNumber()` on the end. For some reason it did not like BigNumber object passed any-more.

```

contractAt.transfer($address.val(), web3.toWei(v, "ether").toNumber(), function (err, result) {
                                if (err) {
                                    console.log(err);
                                    return;
                                }
                              

                            });

```

**Comment by D-Nice** [comment]
@CurrencyTycoon @kumavis Thanks, both of those are potential workarounds that seem to work. However, it appears this is a deeper bug in web3, which I will report there, where they have seemingly lost compatibility with BigNumber objects.
