### ISSUE TITLE
Get HappyFox HTTPS certificate working

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1780]
Right now using https on happyfox throws a cert error. We should make sure https works well, since we sometimes ask users to share account details that may be private enough to merit that encryption.

**Comment by Zanibas** [comment]
Blocked by waiting for support to get back to us.

**Comment by flyswatter** [comment]
Hey @kumavis I don't have permission to issue SSL certs on our DNS panel, could you get a cert issued for `support.metamask.io`, so I can send it to HappyFox?

**Comment by kumavis** [comment]
ive never done such a thing before, let me see

**Comment by kumavis** [comment]
So we had 2 options through dnsimple

- LetsEncrypt: we need to upgrade to the dnsimple $25/mo business plan for requesting certs for the `support.metamask.io` (why? not sure)
- Comodo: $20/yr (cartel yes but cheaper option of these two)

went with comodo, just got 1 year for now

**Comment by flyswatter** [comment]
I'd just pay the premium to not make a new account, personally. I'm happy to chip in towards it if you want to avoid expensing it.

**Comment by flyswatter** [comment]
Oh you got the Comodo, awesome, thanks!  I O U 1 Beer

++ BeerCoinBot

**Comment by kumavis** [comment]
SSL certs sent to @flyswatter
