### ISSUE TITLE
[Bug]: replacement transaction underpriced

### ISSUE THREAD

**Issue by biafffff** [MetaMask/metamask-extension#17803]
### Describe the bug

Signed a Tx on MM, but needed to speed it up. Did so. MM seems not to capture/index the new Tx (hash) and sends an error message, actually, the new Tx hits the chain (Ethereum). 

Issue: I'm not able to easily locate the new Tx and cannot monitor its execution on chain. 

![MM](https://user-images.githubusercontent.com/26275332/219649142-94a51ffe-1956-47ef-a1ca-15c594afc17f.png)

### Steps to reproduce

1. Sign a new Tx using MM
2. Speed it up
3. MM sends a failure message
4. Tx is executed

### Error messages or log output

```shell
Transaction XXX failed! [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32000, "message":"replacement transaction underpriced"}}'
```

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

### Additional context

Firmware version 1.11.2

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by biafffff** [comment]
Still unable to speed up a Transaction under execution. It seems like is no more possible to speed up stuck transaction with MetaMask
