### ISSUE TITLE
New header is not shown on SIWE screen

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#17812]
## Background 
A new signature screen has been introduced for SIWE in https://github.com/MetaMask/metamask-extension/issues/17461, but it's missing the new header that we included in all signature requests here https://github.com/MetaMask/metamask-extension/issues/15705 . We should replace the PermissionsConnectHeader usage on this custom signature screen with the new header

## Steps to Reproduce
1. Go to https://metamask.github.io/test-dapp/
2. Under Sign In With Ethereum, click on Sign In With Ethereum

## Screenshot
<img width="447" alt="Screenshot 2023-02-17 at 17 56 08" src="https://user-images.githubusercontent.com/34968356/219793922-7486a5fa-09e4-4a32-bdf3-542f8ee2f07d.png">

**Comment by danjm** [comment]
@bschorchit to confirm: this is an issue but not v10.26.0, correct? And we should fix it before v10.26.0 is released?

**Comment by bschorchit** [comment]
> @bschorchit to confirm: this is an issue but not v10.26.0, correct? And we should fix it before v10.26.0 is released?

I noticed it in a video recording of one of the SIWE bugs that @PeterYinusa reported for 10.26 so I think it's indeed happening in 10.26. 

I think the original design for SIWE was done before this new header was created so it the header was probably never part of the scope for SIWE.

I don't think it needs to be a release blocker (and therefore fixed before 10.26), it can be added in a subsequent release to preserve parity for all signatures screens.

**Comment by PeterYinusa** [comment]
Sounds good to me, looks related to this possible future enhancement https://github.com/MetaMask/metamask-extension/issues/17807

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by digiwand** [comment]
++ Thanks for adding this @bschorchit! 

The component shouldn't be using the PermissionConnectHeader nonetheless. Was just about to add a new ticket for this until I came across this one. Glad we're replacing this with the new reusable header 👍

**Comment by NiranjanaBinoy** [comment]
> We should get this PR #17994 (or a similar PR that achieves the same - reusing our existing header on SIWE screen) across the line 🚀

The above ticket is doing some cleanup along with the header changes. I plan to create 2 separate tickets: 1st one for the clean-up and 2nd one for the header changes. I will refer back to the previous ticket for all the valuable review comments. 

I hope this works @bschorchit @digiwand
