### ISSUE TITLE
MetaMask Filecoin Snap error: The method "wallet_enable" does not exist / is not available.

### ISSUE THREAD

**Issue by navFooh** [MetaMask/metamask-extension#17813]
### Describe the bug

I'm using the NPM package `@chainsafe/filsnap-adapter` to trigger the installation of the Filecoin snap in Metamask.
All checks successfully pass during `enableFilecoinSnap()` call, meaning:
- `hasMetaMask()` returns `true`
- `await isMetamaskSnapsSupported()` returns `true`

`await isSnapInstalled(snapId)` returns `false`, which is to be expected because the snap is not installed.

Then `await window.ethereum.request()` throws an error: `MetaMask - RPC Error: The method "wallet_enable" does not exist / is not available.`

### Steps to reproduce

```typescript
import { enableFilecoinSnap } from '@chainsafe/filsnap-adapter'

enableFilecoinSnap({
  network: 't',
  rpc: {
    token: '',
    url: 'https://api.node.glif.io/rpc/v1',
  },
}, 'npm:@chainsafe/filsnap')
```

### Error messages or log output

```shell
MetaMask - RPC Error: The method "wallet_enable" does not exist / is not available.
{
    "code": -32601,
    "message": "The method \"wallet_enable\" does not exist / is not available.",
    "data": {
        "origin": "http://localhost:3000"
    }
}
```

### Version

10.25.0-flask.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by piotr-roslaniec** [comment]
This is a result of a breaking change in the latest [MetaMask Flask release](https://github.com/MetaMask/snaps-monorepo/releases/tag/v0.29.0). `wallet_enable` has been replaced with [`wallet_installSnaps`](https://github.com/MetaMask/snaps-monorepo/commit/47e738f31286faaa1a0d19840dcded916555c706).

**Comment by navFooh** [comment]
Thanks for the information, it seems like the issue should be fixed in `@chainsafe/filsnap-adapter` then, will close the issue here.

**Comment by alinobrasil** [comment]
> This is a result of a breaking change in the latest [MetaMask Flask release](https://github.com/MetaMask/snaps-monorepo/releases/tag/v0.29.0). `wallet_enable` has been replaced with [`wallet_requestSnaps`](https://github.com/MetaMask/snaps-monorepo/commit/47e738f31286faaa1a0d19840dcded916555c706). See [docs](https://docs.metamask.io/guide/snaps-rpc-api.html#wallet-requestsnaps) for that method.
> 
> I border to use Filecoin Snap you will have to 1) ask the developers to bump their `@metamask/snaps-cli` version, or 2) manually build and install the previous MetaMask Flask release.

This and several other breaking changes are listed here: https://github.com/MetaMask/snaps-monorepo/discussions/1198
