### ISSUE TITLE
Create e2e test for the transaction security provider

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#17810]

**Comment by seaona** [comment]
We should verify that we cover the different cases of Opensea responses:
- Not Malicious
- Malicious
- Not Safe
- Request Not Verified

For that, we should mock the API response for this request:
 ```
https://eos9d7dmfj.execute-api.us-east-1.amazonaws.com/metamask/validate
```
with the different response bodies for each case. I.e.

```
{
"flagAsDangerous":1,
"reason":"Approval is to an unverified smart contract known for stealing NFTs in the past.",
"reason_header":"This could be a scam"
}
```

There is a good example of mocking a response API on the `phishing-detection.spec.js`.
cc @bschorchit

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
