### ISSUE TITLE
[Bug]: Add NFT toaster is displayed on Home screen when user remove an NFT

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#17825]
### Describe the bug

When user remove an NFT in NFT details page, add NFT notification toaster is displayed instead of remove NFT toaster.

https://user-images.githubusercontent.com/105063779/220123203-be724453-f2ba-4083-ab8e-2e06a240cf4e.mov

### Steps to reproduce

1. Import an NFT
2. Click into an NFT
3. From the 3-dot menu, choose "Remove item"
4. Check on homepage that add NFT toaster is displayed.
Expected: **Remove** NFT toaster should be displayed.

### Version

Develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by darkwing** [comment]
On it!

**Comment by darkwing** [comment]
Weird, I'm seeing this: 

<img width="446" alt="RemoveNFT" src="https://user-images.githubusercontent.com/46655/220673524-adbd4f95-c2cb-4f2d-b019-e5100eca4fd0.png">
