### ISSUE TITLE
e2e test for remove an ERC1155 NFT

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#17827]
Write an e2e test to cover the flow for removing an erc1155

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
