### ISSUE TITLE
[Bug]: Insufficient tokens warning not shown when sending from a dapp

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17824]
### Describe the bug

The insufficient tokens warning is not shown when sending an ERC20 token from a dapp.
The transaction will fail

https://user-images.githubusercontent.com/53189696/220108592-71ce95a9-62f2-44ee-b2c0-88f1b3b2c0fe.mov

### Steps to reproduce

1. log in to the extension
2. connect to the [test dapp](https://metamask.github.io/test-dapp/)
3. deploy the TST token (Send Tokens -> Create Token)
4. add the token to your wallet (Send Tokens -> Add Token To Wallet)
5. From MM, send 9.5 tokens to another address
6. Switch back to the test dapp
7. Attempt to transfer tokens (Send Tokens -> Transfer Tokens)

**Expected result:**
A warning is shown on the confirmation screen
```
You do not have enough TST in your account to pay for transaction fees on Goerli network. Buy TST or deposit from another account.

```
The confirm button is disabled

**Actual result:**
You can confirm the transaction even though you don't have 1.5 TST in your wallet
The transaction fails, see https://goerli.etherscan.io/tx/0x2cddb7cab9ed5dddc9f6684bed7ff73319543983a2cd1a71f937ada15495748b

### Version

10.26

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
I think this might be a regression-rc @PeterYinusa. I'm not able to reproduce it on 10.25 on prod.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
Closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/16743
