### ISSUE TITLE
[Bug]: No user feedback is given when changing the currency conversion

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17831]
### Describe the bug

When `Show balance and token price checker` is switched off, the user is not given any feedback when changing the `Currency conversion`. The field does not update and the user is not informed as to why

https://user-images.githubusercontent.com/53189696/220154207-749bf9d5-4d7f-4d17-abbb-6569b66f12f2.mov

### Steps to reproduce

1. log in to the extension
2. Click on the account icon to open the account menu, then click `Settings`
3. turn off `Show balance and token price checker`, `Security & privacy`  -> `Show balance and token price checker`
4. attempt to change the `currency conversion` dropdown

### Version

10.26

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
