### ISSUE TITLE
Ether in limbo, but visible in EtherDelta address, clashing with Metamask(?)

### ISSUE THREAD

**Issue by slavmart** [MetaMask/metamask-extension#1783]
Whilst logged-in to Metamask, I sent Ether from a exchange to the EtherDelta address, not MetaMask address.

A pop-up box came up that I should log out from Metamask, before transfering from EtherDelta. Upon doing so, EtherDelta does not react to double clicking in transfering the Ether to my Metamask address.

I can see the Ether in the EtherDelta Wallet address below, and it is not reacting to the 'transfer' button with the Metamask address and Ether amount written in the corressponding boxes.

Can anyone suggest how to rectify this?
and successfully transfer the Ether out?

Update: When I disable the Metamask extension, I am able to transfer within EtherDelta. Maybe clarification on where the Ether should be when using Metamask in terms of making orders. Currently have Ether in the EtherDelta address, but it does not react when I try to place an order.
Should the Ether be in the Metamask address?
and remain in the Metamask wallet or Etherdelta to make orders?

![metamask glitch](https://user-images.githubusercontent.com/30223929/28255339-fa0a8f4c-6af8-11e7-82b5-b8304a99d3bd.JPG)

**Comment by flyswatter** [comment]
Another way to get control of this EtherDelta ether:

1. Select that account.
2. Re-open that menu, and select "Export private key".
3. Back up that private key safely.
4. You can import that private key into MetaMask, using the top-right MetaMask menu "Import Account".

For other specific EtherDelta support, visit their support gitter:
https://gitter.im/etherdelta/etherdelta.github.io
