### ISSUE TITLE
[Bug]: LavaMoat - property "Image" of globalThis is inaccessible under scuttling mode. To learn more visit **

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17834]
### Describe the bug

I noticed the following Error is continually triggered and sent to Sentry when speeding up a transaction.

The video below shows the steps I carried out to produce the error. The error did not appear in the home or background console.

https://user-images.githubusercontent.com/53189696/220176241-1ba88963-9d81-4e9f-aedd-a085c82ac308.mov

### Steps to reproduce

1. Log in to the extension
2. Click the Send button on the overview page
3. Enter an address and an amount, then click Next
4. Click Confirm to confirm the transaction
5. Click the Speedup button on the corresponding transaction from the activity list
6. Select a gas option, then click submit
7. Check Sentry

### Error messages or log output

```shell
/LavaMoat/LavaMoat/pull/360. in Error: LavaMoat - property "Image" of globalThis is inaccessible under scuttling mode. To learn more visit
metamask/runtime-lavamoat.js in get at line 11200:17
extensions::imageUtil in loadImageDataForNonServiceWorker at line 72:13
extensions::imageUtil in loadImageData at line 113:5
extensions::imageUtil in Object.loadAllImages at line 134:5
extensions::notifications in replaceNotificationOptionURLs at line 89:13
extensions::notifications at line 116:5
metamask/common-3.js at line 3:176020
<anonymous> in new Promise
metamask/common-3.js in Proxy.<anonymous> at line 3:175700
metamask/common-3.js in Object.apply at line 3:175119
metamask/common-0.js in n.default._showNotification at line 99:63808
metamask/common-0.js in n.default._showFailedTransaction at line 99:63717
metamask/common-0.js in n.default.showTransactionNotification at line 99:62718
metamask/background-4.js in j.<anonymous> at line 1:23042
metamask/common-3.js in u at line 3:1222
metamask/common-3.js in a.emit at line 3:1758
metamask/common-3.js in u at line 3:1222
metamask/common-3.js in a.emit at line 3:1815
metamask/background-3.js in g._setTransactionStatus at line 1:275746
metamask/background-3.js in g.setTxStatusConfirmed at line 1:274677
metamask/background-3.js in j.confirmTransaction at line 1:122059
metamask/background-3.js in d.<anonymous> at line 1:125432
metamask/common-3.js in u at line 3:1222
metamask/common-3.js in a.emit at line 3:1758
metamask/background-3.js in d._checkPendingTx at line 1:266436
metamask/background-3.js in async d.updatePendingTxs at line 1:264762
metamask/background-3.js in async j._onLatestBlock at line 1:126703
```

### Version

10.26

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
@weizman @kumavis

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by weizman** [comment]
I think this should help https://github.com/weizman/metamask-extension/pull/7

**Comment by weizman** [comment]
https://github.com/MetaMask/metamask-extension/pull/17955

**Comment by PeterYinusa** [comment]
Sentry issue: [METAMASK-WQRZ](https://metamask.sentry.io/issues/4004450954/?referrer=github_plugin)

**Comment by matthewwalsh0** [comment]
This is causing #18235.

I had also created #18323 before finding this issue after searching for the methods from the stack trace, the only difference is I've updated the notification code to throw any errors in future so it won't fail silently.

**Comment by PeterYinusa** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/18323

**Comment by Shulepov** [comment]
During automation test started to get this error after upgrading to chrome 113:

property "Proxy" of globalThis is inaccessible under scuttling mode

**Comment by ponypick** [comment]
Automation test in chrome 113+:
LavaMoat - property "Proxy" of globalThis is inaccessible under scuttling mode

**Comment by ponypick** [comment]
Automation test on chrome 113+:
Error: LavaMoat - property "Proxy" of globalThis is inaccessible under scuttling mode
