### ISSUE TITLE
E2E Test insights v2

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17845]
Ensure that the e2e test report is uploaded to Circle CI on failed e2e test runs

Currently, when an e2e test job (e.g. `test-e2e-chrome`) fails,  the test report is not uploaded to Circle CI in the `Uploading test results` step.
From a quick glance, it looks like the `Merge JUnit report` step is not run when the preceding `test:e2e:chrome` step fails
As a result of this, right now we only have metrics on the slowest e2e tests and not the most failed or flaky tests.

See: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/37439/workflows/d46bd77d-867d-490f-bd71-f9df6199f878/jobs/1010658

```
Unable to save test results from /home/circleci/project/test/test-results/e2e.xml
Error error accessing path "/home/circleci/project/test/test-results/e2e.xml": stat /home/circleci/project/test/test-results/e2e.xml: no such file or directory
Found no test results, skipping
```

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
