### ISSUE TITLE
Fix outline on TextField

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17850]
### Description
Fix outline on on TextField and other input components

<img width="846" alt="Screenshot 2023-02-21 at 2 17 38 PM" src="https://user-images.githubusercontent.com/8112138/220460692-7b2910be-3579-4a13-97c8-efb69d464bca.png">

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
