### ISSUE TITLE
[Bug]: Metamask account suddenly gone! Can i still recover my funds?

### ISSUE THREAD

**Issue by vlindersteen** [MetaMask/metamask-extension#17864]
### Describe the bug

I transferred funds within my MetaMask from Account A → **Account B**. I’ve seen the funds (0.017 ETH + 1 NFT + $SDL tokens) arrive in **Account B**.

The next day when i opened my MetaMask, **Account B** is totally gone and nowhere to be found. (**0x12c951e8D4838420e01EB8a0E6eC2bDc44A83249** is the address)

I figured it might have to do something with these issues i found on Github: https://github.com/MetaMask/metamask-extension/issues/6012 and https://github.com/MetaMask/metamask-extension/issues/10875. The address is probably connected to my Ledger.

I also wrote about it on Metamask support forum: https://community.metamask.io/t/metamask-account-suddenly-gone-can-i-still-recover-my-funds/24484/1

I still don't have solution yet after searching for two days, hope anyone can help me out!

### Steps to reproduce

1.
I don't know?

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Ledger

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
