### ISSUE TITLE
Create component: CookieCutter

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17869]
### **Description**

Create `CookieCutter` component based on audit and insight report 

<img width="667" alt="Screenshot 2023-02-22 at 4 07 25 PM" src="https://user-images.githubusercontent.com/8112138/220783915-4d17543c-879c-4867-ab96-6b9ba000528a.png">

### **Technical Details**
- size: xs, sm, md, lg, xl
- children: any
- shape: circle, rectangle, hexagon
- className: string

Customizable Box props 
- backgroundColor: BackgroundColor
- borderColor: borderColor
- color: textColor

### **Acceptance Criteria**
- Component exists built to specifications outlined in insight report
 
### **References**

[FigJam](https://www.figma.com/file/pQa2vI7r08pHiqsAPTWdQ8/Avatar%2C-Token%2C-Network%2C-Icon%2C-Badge-Audit?node-id=607%3A123&t=fedx1fSP0xZPIvat-1)

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
