### ISSUE TITLE
[Bug]: Gas Estimation failure displays 2 duplicated Warnings

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17866]
### Describe the bug

**Problem**: when there is a Gas Estimation failure, there are 2 duplicated warnings displayed on the Confirmation screen, saying `We were not able to estimate Gas...`;

Issue was introduced in 10.25.0

![image](https://user-images.githubusercontent.com/54408225/220711338-7436efe1-7879-46a2-841d-6296be2795d7.png)

### Steps to reproduce

For a quick reproduction, we will use the incorrect behaviour (another bug is open for that), where when tx is going to fail, we display a huge amount of Gas and the warning unable to estimate gas.

https://user-images.githubusercontent.com/54408225/220713383-7cc42744-55db-4546-8562-ec516c3d9c45.mp4

1. Go to etherscan https://etherscan.io/address/0xe592427a0aece92de3edee1f18e0157c05861564/advanced#writeContract
2. Connect your MM acount
3. Click `selfPermit`
4. Fill it with values (0x, 0x for r and s)
5. Click Write
6. See MM prompt and 2 duplicated warnings

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by seaona** [comment]
This issue is still present

**Comment by pedronfigueiredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/17866?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by seaona** [comment]
This is what we see for EIP1559

<img width="561" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92e91088b99b1aebec0038730dacede282b73c39/Screenshot%20from%202024-03-27%2016-44-15.png" alt="Screenshot from 2024-03-27 16-44-15.png" />

**Comment by bschorchit** [comment]
We could/should also hide the gas component until the user clicks on `Proceed anyway`
