### ISSUE TITLE
[Bug]: Hovering any Address parsed on Signed Type Data screen does not display the pointer anymore

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17860]
### Describe the bug

**Problem**: when you hover an address that is parsed on any of the Signed Type Data screens, the pointer does not appear anymore.
This was not happening in 10.24.0 but it's happening on 10.25.0

https://user-images.githubusercontent.com/54408225/220685601-4cbc2e4f-8ff3-4c59-bb35-1e028e5d2b0e.mp4

### Steps to reproduce

1. Go to Test Dapp https://metamask.github.io/test-dapp/
2. Connect MetaMask
3. Click to any Sign type data
4. Hover any address -- see mouse is not a pointer anymore

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
