### ISSUE TITLE
[Bug]: Invariant failed: A state mutation was detected between dispatches on Decrypt request submit

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#17867]
### Describe the bug

Clicking "Decrypt" from "Decrypt Request" page causes an error and stops the user from completing the request. To bypass, the user must click "Decrypt" multiple times.

<img width="1538" alt="Screen Shot 2023-02-23 at 1 27 46 AM" src="https://user-images.githubusercontent.com/20778143/220739765-c4c4a959-73c9-45f3-bfb9-6f915d0fb05d.png">

Not exactly sure where this was introduced. It happened after v10.25.0 and before 92367dff792852464d3e95a3abf7d3d6857a0545 

### Steps to reproduce

1. Go to https://metamask.github.io/test-dapp/
2. Submit "Get Encryption Key"
3. Type a message and click "Encrypt"
4. Click "Decrypt". The popup should open. 
5. Open the transaction in full-page, home.html
6. Inspect console
7. Click "Decrypt" 
8. Observe the transaction is not completed and the error appears in console
9. To bypass this, double-click on "Decrypt" button

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
The invariant failed error is happening in several places. See [this issue comments](https://github.com/MetaMask/metamask-extension/issues/17745) for more context from @brad-decker

**Comment by digiwand** [comment]
Duplicate of https://github.com/MetaMask/metamask-extension/issues/17745

**Comment by brad-decker** [comment]
@digiwand I don't think this is a duplicate, as its pointing to a different action. Each case of this mutation we should fix separately.
