### ISSUE TITLE
Update LedgerInstructionField to use BannerAlert

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17873]
### Description
Currently the `LedgerInstructionField` is using the old banner style. Seeing it next to the new `BannerAlert` creates inconsistencies. It would be great to update it to use `BannerAlert` 

### Before
<img width="414" alt="Screenshot 2023-02-22 at 5 10 33 PM" src="https://user-images.githubusercontent.com/8112138/220794081-20c410ce-f8ca-4f02-a132-9e7108af1972.png">

### After

<img width="855" alt="Screenshot 2023-02-22 at 5 44 59 PM" src="https://user-images.githubusercontent.com/8112138/220796747-1e9185b7-dfe0-4d83-bd5e-7ee21bf03d0e.png">

### Technical Details
- Update `LedgerInstructionField` to use the [BannerAlert](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-banneralert--default-story#banneralert) component 
- Create a story in storybook using the below code

```
import React from 'react';
import LedgerInstructionField from '.';

export default {
  title: 'Components/App/LedgerInstructionField',
  argTypes: {
    showDataInstruction: {
      control: {
        type: 'boolean',
      },
    },
  },
};

export const DefaultStory = (args) => <LedgerInstructionField {...args} />;

DefaultStory.storyName = 'Default';
```

Rough JSX markup without local functions or conditionals, if you have a design contact I would suggest checking with them 🙇 

```
<Box display={DISPLAY.FLEX} flexDirection={FLEX_DIRECTION.COLUMN} gap={3}>
      <BannerAlert severity={SEVERITIES.DANGER}>
        Cannot connect to Ledger device. Please make sure your device is
        unlocked and Ethereum app is opened.
      </BannerAlert>
      <BannerAlert
        {...args}
        severity={SEVERITIES.INFO}
        actionButtonLabel="Close any other software connected to your device and then click here to refresh."
      >
        <Text>Prior to clicking confirm:</Text>
        <ul>
          <Text variant={TextVariant.bodySm} as="li">
            - Enable Use Ledger Live under Settings > Advanced
          </Text>
          <Text variant={TextVariant.bodySm} as="li">
            - Open and unlock Ledger Live App
          </Text>
          <Text variant={TextVariant.bodySm} as="li">
            - Plug in your Ledger device and select the Ethereum app
          </Text>
          <Text variant={TextVariant.bodySm} as="li">
            - Enable "smart contract data" or "blind signing" on your Ledger
            device
          </Text>
        </ul>
      </BannerAlert>
    </Box>
```

### Acceptance Criteria
- `LedgerInstructionField` looks similar to other notificaitons

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by georgewrmarshall** [comment]
@SaraCheikh could you please update this issue description with the BannerAlert design you suggested if it's different to the one I suggested?

**Comment by flexa-rob** [comment]
@georgewrmarshall - I noticed that the BannerAlert includes a close icon. Does this imply that the LedgerInstructionField should be dismissable?

**Comment by SaraCheikh** [comment]
Hi @georgewrmarshall I'm still unable to edit any ticket (billing issue). I addressed the mix of banners and their order in[ Bug 17630](https://github.com/MetaMask/metamask-extension/pull/17738). So the order of the banners would be the only thing missing in the description. You can add the link to the [Figma file](https://www.figma.com/file/C9K6IjSkZTZLdMSREV38NS/Bug-17630-silent-ledger-failures?node-id=0%3A1&t=d8d6TCfgLUeVArHj-1) with the designs that take as reference the screen shared in this ticket. @flexa-rob for the informationa BannerAlert,  If the information is crucial for the users to continue with that action, I would keep it non dismissible as how we have it currently, so without showing the close button. 
<img width="425" alt="Screenshot 2023-03-01 at 11 54 31" src="https://user-images.githubusercontent.com/98161559/222120098-1946db1a-604b-4d69-94de-a9a2095fae1e.png">
<img width="437" alt="Screenshot 2023-03-01 at 11 54 24" src="https://user-images.githubusercontent.com/98161559/222120106-bb5edc56-0bde-4d91-8bb5-b5d282c1901d.png">

**Comment by flexa-rob** [comment]
No worries @SaraCheikh  - done
