### ISSUE TITLE
Create component: BadgeNetwork

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17870]
# TBC DO NOT START WORK ON THIS YET

### **Description**

Create `BadgeNetwork` component based on audit and insight report 

### **Technical Details**

<img width="652" alt="Screenshot 2023-02-22 at 4 13 28 PM" src="https://user-images.githubusercontent.com/8112138/220784783-379ff796-a9a3-4712-b2d2-b3c95374e532.png">

### **Acceptance Criteria**
- Component exists built to specifications outlined in insight report
 
### **References**

[FigJam](https://www.figma.com/file/pQa2vI7r08pHiqsAPTWdQ8/Avatar%2C-Token%2C-Network%2C-Icon%2C-Badge-Audit?node-id=657%3A1292&t=fedx1fSP0xZPIvat-1)

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
