### ISSUE TITLE
Create component: BadgeStatus

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17871]
### **Description**

Create `BadgeStatus` component based on audit and insight report 

### **Technical Details**
<img width="662" alt="Screenshot 2023-02-22 at 4 19 44 PM" src="https://user-images.githubusercontent.com/8112138/220785564-71fc3165-c5a1-4557-9205-43a5f13571d2.png">

### **Acceptance Criteria**
- Component exists built to specifications outlined in insight report
 
### **References**

[FigJam](https://www.figma.com/file/pQa2vI7r08pHiqsAPTWdQ8/Avatar%2C-Token%2C-Network%2C-Icon%2C-Badge-Audit?node-id=657%3A1298&t=fedx1fSP0xZPIvat-1)

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Shubham0850** [comment]
@georgewrmarshall I'm new to Opersource contribution. I want to contribute here. 

😀 I want to work on this issue, But the FigJam link is not working !!

**Comment by georgewrmarshall** [comment]
Hey @Shubham0850, thanks for your interest. This issue is currently not ready to work on. May I suggest reading [this issue](https://github.com/MetaMask/metamask-extension/issues/17670) and submitting a PR agains it? https://github.com/MetaMask/metamask-extension/issues/17670

**Comment by Shubham0850** [comment]
Hi @georgewrmarshall thanks for the reply, I will checkout the above PR and try to work on it. 🙏

If you have some more suggestions of the PRs, That i can work on as a noob opensource contributers that would be great.😀
