### ISSUE TITLE
[Bug]: The current goerli "Buy" button sends users to a non-existent faucet

### ISSUE THREAD

**Issue by merlox** [MetaMask/metamask-extension#17884]
### Describe the bug

**Description**

Currently when you use the Goerli testnet and click on "Buy" you are redirected to https://goerli-faucet.slock.it/ which is instantly redirected to www.blockchains.com which is not a faucet at all. People want to get goerli ether like in the past but they can't.

What I'm proposing is to use the faucet that I've created https://bigoerlifaucet.com so that people are redirected to it when they want to request goerli ether from the faucet. The faucet has been updated with 10,000 goerli eth that I've gathered for this purpose. Plus I personally commit to guarantee that the faucet is at all times available and working smoothly via email and chat.

The faucet has been used hundreds of times already and is working smoothly.

**Before**

When you switch to Goerli on ethereum and click on "Buy" you're redirected to blockchains.com which is not a faucet at all, leaving people confused and frustrated when they need goerli for testing their dapps, participating in dapps and learning how to stake on ethereum.

**After**

When they click on "Buy" users are redirected to https://bigoelifaucet.com which has more than enough goerli and is self-sustaining. I personally commit to make sure the faucet is working smoothly and won't ever change the domain to another website (like slock it did).

### Steps to reproduce

1. Switch to the Goerli testnet
2. Click on "Buy"
3. Be redirected to www.blockchains.com

### Version

10.25.0

### Build type

None

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS, Linux

### Additional context

I'm always available for any adjustments you guys may need. It's a pleasure to help you guys.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
