### ISSUE TITLE
Create contract address blacklist API

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1788]
We should be able to add addresses to a blacklist and prevent metamask users from sending to it. 

Would be useful during scam-address takeovers like today's:
https://www.bloomberg.com/news/articles/2017-07-17/coindash-says-hacker-stole-7-million-at-initial-coin-offering

**Comment by kumavis** [comment]
we did it! thanks to infura and @409h and everyone contributing

**Comment by flyswatter** [comment]
This referred to Ethereum addresses, not web urls. We have a blacklist for those, too?

**Comment by 409H** [comment]
Yep, we have it over at https://github.com/MyEtherWallet/ethereum-lists
