### ISSUE TITLE
Investigate mv3 service worker restart behaviour

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17893]
The user is being logged out after service worker restart. This bug was not present on [266d7d9](https://github.com/MetaMask/metamask-extension/commit/266d7d93d5bd9c18e9bc2c942b6a5e67968a0fd3), but seems to be present as of [943453c](https://github.com/MetaMask/metamask-extension/commit/943453cfb2a5f7f54430d5d4890ca145ef296123)

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by danjm** [comment]
closed by https://github.com/MetaMask/metamask-extension/pull/18036
