### ISSUE TITLE
What's New: single item display

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#17899]
## Background
Currently, one of the few in-app communication tools, What's New, displays selected communication items all at once with only the top position rendering images. This is disadvantageous because when we have impactful news items such as NFTs and Security Provider releases, we want to have as much exposure and conversion as possible.

## Acceptance Criteria
Create alternative logic to display What's New:
- Show 1 What's New item at a time
- If the user has viewed that item, don't show it again
- On next unlock, show the second What's New item
- When all items are viewed in the queue, stop displaying What's New
- We should not have more than 3 items in the queue
- Target release v10.26.0

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by kevinghim** [comment]
Resolved via https://github.com/MetaMask/metamask-extension/pull/17653
