### ISSUE TITLE
[Bug]: Metamask keeps sending `eth_getBlockByNumber`

### ISSUE THREAD

**Issue by GiantBabyCorn** [MetaMask/metamask-extension#17906]
### Describe the bug

Metamask seems to keep sending `eth_getBlockByNumber` requests to networks which has been added, even though I'm not currently connected to the network.

### Steps to reproduce

1. Just Added some network, and wait for some minutes.

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Additional context

![image](https://user-images.githubusercontent.com/82532128/221334734-7a8dcfa6-6b04-4574-97d9-7e8c0c7850f8.png)

Above images shows how crazy that metamask keeps sending request.

![image](https://user-images.githubusercontent.com/82532128/221334798-a5295dd5-2900-4d27-a918-2b3f7be27228.png)

I was connected to the canto network when this screenshot was taken, and as you can see it still keeps sending requests to Ethereum, Optimistic, Cronos and other networks.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by xinnanyemm** [comment]
Please note that `label:team-dapp-api` has been replaced by `label:team-devex` . Thanks.

**Comment by vandan** [comment]
`team-devex` assessed that this does not appear to be API related.
Reassigning to `team-extension-platform`
