### ISSUE TITLE
Spike: bundle size reduction analysis and planning

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#17900]
Desired output: A set of github tickets which, when resolved, will result in achievement of our bundle size reduction goal (approximately 1.7 mb below current size)

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by danjm** [comment]
closed by https://github.com/MetaMask/metamask-extension/issues/18023
