### ISSUE TITLE
Update TransactionAlerts with BannerAlert

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#17921]
### Description
Replace `ActionableMessage` with `BannerAlert` in `ui/components/app/transaction-alerts/transaction-alerts.js`

## Before
<img width="634" alt="Screenshot 2023-02-27 at 6 04 02 PM" src="https://user-images.githubusercontent.com/8112138/221734100-5ff0636e-a4fb-4dd7-a1c5-38737694316a.png">

## After

TBC

### Technical Description
- Update `ActionableMessage` with `BannerAlert` https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-banneralert--default-story
- Update `Typography` with `Text`(If needed it probably wont be) https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-text--default-story

### Related
- https://github.com/MetaMask/metamask-extension/issues/17873
- https://github.com/MetaMask/metamask-extension/pull/17738

**Comment by OfficialSupportt** [comment]
@georgewrmarshall We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9
