### ISSUE TITLE
[Bug]: Account Details element miss-alignment

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17926]
### Describe the bug

**Problem**: when I am on a custom network and I click the 3 dots for checking the Account details, I can see how the `View Account in explorer` and the blockexplorer URL are miss-aligned.

This happens both with the full-view and the popup view.

This has been introduced in 10.25.0 Release

![image](https://user-images.githubusercontent.com/54408225/221841182-5633786a-caff-4d65-a3af-a94a1eb35b1c.png)

The expected result should be like in 10.24.0

![image](https://user-images.githubusercontent.com/54408225/221841633-36e4b036-b688-464e-9a02-72c64bc504bb.png)

### Steps to reproduce

1. Add custom network i.e. Optimism
2. Change to custom network
3. Click Account details

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by kevinghim** [comment]
Should be fixed through multichain v0.5 update
