### ISSUE TITLE
Very long menus should be scrollable

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1792]
Our MenuDroppo component that we use in many places should become scrollable since it now will be able to show accounts, a list of length we don't control.

**Comment by Zanibas** [comment]
Should not extend outside of current view

**Comment by sdtsui** [comment]
@zanibas this should be resolved and checked in to `NewUI`. (#1831)

**Comment by flyswatter** [comment]
I agree it is, thanks!
