### ISSUE TITLE
Replace the extension network controller with the shared network controller

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#17931]
Once all of the API normalization work has been completed, and once we've replaced `web3-provider-engine` on `@metamask/network-controller`, we should delete the extension network controller and replace it with `@metamask/network-controller`.

This issue is the final step of the "[Merge the two network controllers](https://github.com/metamask/core/issues/753)" epic.

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/metamask-extension/17931?planning-poker) with Zenhub @Gudahtt @mcmire @mikesposito
