### ISSUE TITLE
[Bug]: sentry-install 429 (Too Many Requests)

### ISSUE THREAD

**Issue by JeffWScott** [MetaMask/metamask-extension#17930]
### Describe the bug

Cannot send tokens on ETH Mainnet.  

When I inspect the extension console this is the error I see:
POST https://sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7 429 (Too Many Requests)  sentry-install.js:1          

I have tried WETH and USDC tokens, both of which I have sent multiple times before.

The network is Ethereum Mainnet

This is an output of the Chrome console:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/4855017/221893569-be40efc1-2641-4ea1-bc08-63a36f1c9484.png">

### Steps to reproduce

1. Login to Metamask
2. Click Assets
3. Click USDC
4. Click "Send"
5. Metamask just shows a loading spinner and never recovers

### Error messages or log output

```shell
From Chrome console:

sentry-install.js:1
POST https://sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7 429 (Too Many Requests)

sentry-install.js:76
SES_UNHANDLED_REJECTION: Error: Unable to determine contract standard
  at p.<anonymous> (common-4.js:10:404565)
  at Generator.throw (<anonymous>)
  at s (common-4.js:10:401514)
```

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
I believe this will be fixed by https://github.com/MetaMask/metamask-extension/pull/17891

**Comment by JeffWScott** [comment]
Thanks for the response Dan 👍👍

- Jeff Scott
________________________________

**Comment by danjm** [comment]
@JeffWScott While we are fixing this, I am looking into workarounds. If you close and reopen your browser, are you then able to send WETH or USDC?

**Comment by OfficialSupportt** [comment]
> ### Describe the bug
> 
> Cannot send tokens on ETH Mainnet.  
> 
> When I inspect the extension console this is the error I see:
> POST https://sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7 429 (Too Many Requests)  sentry-install.js:1          
> 
> I have tried WETH and USDC tokens, both of which I have sent multiple times before.
> 
> The network is Ethereum Mainnet
> 
> This is an output of the Chrome console:
> <img width="526" alt="image" src="https://user-images.githubusercontent.com/4855017/221893569-be40efc1-2641-4ea1-bc08-63a36f1c9484.png">
> 
> ### Steps to reproduce
> 
> 1. Login to Metamask
> 2. Click Assets
> 3. Click USDC
> 4. Click "Send"
> 5. Metamask just shows a loading spinner and never recovers
> 
> 
> 
> 
> 
> ### Error messages or log output
> 
> ```shell
> From Chrome console:
> 
> sentry-install.js:1
> POST https://sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7 429 (Too Many Requests)
> 
> sentry-install.js:76
> SES_UNHANDLED_REJECTION: Error: Unable to determine contract standard
>   at p.<anonymous> (common-4.js:10:404565)
>   at Generator.throw (<anonymous>)
>   at s (common-4.js:10:401514)
> ```
> 
> 
> ### Version
> 
> 10.25.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

@JeffWScott We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by devmanx** [comment]
I cannot call some contract functions on bsc testnet. I got POST https://sentry.io/api/273505/envelope/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.53.0 429 (Too Many Requests) error.
