### ISSUE TITLE
[Bug]: ETH balance not updating after Beacon Chain Withdrawals

### ISSUE THREAD

**Issue by timbeiko** [MetaMask/metamask-extension#17936]
### Describe the bug

When a withdrawal happens on the beacon chain, it increments the accounts' balance without a transaction, similar to how PoW rewards were handled. On MetaMask, these balance updates aren't reflected. See the following screenshot from Sepolia, where the MM balance is much lower than the balance [shown on Etherscan](https://sepolia.etherscan.io/address/0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134) (4M ETH): 

![photo_2023-02-27_20-49-15](https://user-images.githubusercontent.com/9390255/221992578-45bd536d-6a7c-4d72-ad1a-ab74849249ab.jpg)

### Steps to reproduce

1. Run a validator on a post-Shanghai network (currently Sepolia or [Zhejiang](https://zhejiang.ethpandaops.io/))
2. Wait until a partial or full withdrawal happens
3. Check balance -> withdrawn amount will not show on MetaMask

### Version

Latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

See https://eips.ethereum.org/EIPS/eip-4895 for the formal specification of withdrawals. Note the State Transition and Rationale sections.

**Comment by OfficialSupportt** [comment]
@timbeiko We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by atifnimran** [comment]
Ok

**Comment by danjm** [comment]
@timbeiko Have you heard of anyone else experiencing this problem?

**Comment by atifnimran** [comment]
Please help

**Comment by 404Git-404** [comment]
I have this issue, I can show 4 entries in the Beacon Chain for withdrawals that didn't make it to my MetaMask.  I would love to work with someone on this

**Comment by atifnimran** [comment]
Okey please help
