### ISSUE TITLE
[Bug]: Cannot Edit a Send NFT from inside MetaMask

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17948]
### Describe the bug

**Problem**: when I am performing an NFT Send from inside MetaMask, I cannot go back to edit the transaction once I reach the Confirm screen.

https://user-images.githubusercontent.com/54408225/222196586-50763093-a2d0-44f8-b1bb-86c63d0ccddf.mp4

### Steps to reproduce

1. Import an NFT
2. Click Send
3. Add Recipient
4. Proceed and land on the Confirm screen -- see no Edit is possible now

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by darkwing** [comment]
This is happening because `confirm-transaction-base.component.js` isn't being provided an `onEdit` prop
