### ISSUE TITLE
MV3: Service worker restart when popup is open Test cases

### ISSUE THREAD

**Issue by DDDDDanica** [MetaMask/metamask-extension#17946]
As a left over from https://github.com/MetaMask/metamask-extension/issues/17386, we want to add e2e tests for the flow as

- [ ] User triggers a new transaction

- [ ] Ensure there's a new pop up window

- [ ] Restart the service worker 

- [ ] Ensure there's only one window with same content persisting

- [ ] Submit the transaction, ensure it succeeds

**Comment by danjm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Extension-Client-Team-63529dce65cbb100265a3842/issues/MetaMask/metamask-extension/17946?planning-poker) with Zenhub @brad-decker @DDDDDanica @pedronfigueiredo @PeterYinusa
