### ISSUE TITLE
[Bug]: response header "redirect" seems to be not used properly

### ISSUE THREAD

**Issue by OctoD** [MetaMask/metamask-extension#17958]
### Describe the bug

I used to have a network configured with this rpc endpoint

songbird.towolabs.com

which now redirects to another one (with http status code 308) and adds a header called `redirect` with the proper new rpc endpoint.

Metamask is frozen since then, I had to add a fake entry in my `/etc/hosts` to unlock the wallet.

### Steps to reproduce

1. add a network with `songbird.towolabs.com/rpc` as rpc endpoint
2. enjoy having mm locked forever

### Version

10.22.2

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by OfficialSupportt** [comment]
@OctoD We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OctoD** [comment]
Hi, I tested and it seems to be working. Bear in mind that the old Rpc endpoint has been removed and the redirect does not exist any more.
