### ISSUE TITLE
[Bug]: UI/UX or improper data fetching

### ISSUE THREAD

**Issue by lexilie** [MetaMask/metamask-extension#17957]
### Describe the bug

On the metamask portfolio website my WETH asset shows a balance but on opening it shows a different balance. The primary balance shown on the interface is wrong.  I'm attaching the images for reference.
![image](https://user-images.githubusercontent.com/91874444/222393863-1eb02023-c698-4d7a-93dc-896191e8b48f.png)
![image](https://user-images.githubusercontent.com/91874444/222393959-e8c7ba93-2425-412a-b14e-bdbaa5b694f0.png)

### Steps to reproduce

1.
Just check the portfolio site. The issue is with WETH on polygon.

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by OfficialSupportt** [comment]
@lexilie We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by danjm** [comment]
Closing as this seems to be resolved. Please reopen a ticket or contact customer support if you continue to experience any issues
