### ISSUE TITLE
[Bug]: After submitting a transaction the pop-up modal does not close

### ISSUE THREAD

**Issue by helpfulBro** [MetaMask/metamask-extension#17953]
### Describe the bug

![image](https://user-images.githubusercontent.com/25915621/222343413-03ff8649-83dd-4fbf-8a25-dc7e5a8ca088.png)

### Steps to reproduce

1. After submit a transaction, or sign a message the modal does not close.

- Does not always happen, but often enough to reproduce.
- If using metamask in a tab, the same thing happens - stuck at the loader overlay as per the bug description
- Only started a few days ago, happens only on Brave.

### Version

10.25.0

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by Mobjaw** [comment]
Same with mine. Same version except with Chrome browser v110.0.5481.178 (Official Build) (64-bit). It not only happens after transactions, if you go into the Security and privacy settings and try to toggle any of the switches it'll happen about 90% of the time.

**Comment by OfficialSupportt** [comment]
@helpfulBro We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> Same with mine. Same version except with Chrome browser v110.0.5481.178 (Official Build) (64-bit). It not only happens after transactions, if you go into the Security and privacy settings and try to toggle any of the switches it'll happen about 90% of the time.

@Mobjaw We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by helpfulBro** [comment]
@OfficialSupportt find someone else to scam and contribute to improving others lives, not just your own.
