### ISSUE TITLE
[Bug]: Invariant failed: A state mutation was detected between dispatches on any type of Signature screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17962]
### Describe the bug

**Problem**: error `Invariant failed: A state mutation was detected` is triggered when we Sign any of the Signatures types.
This is related to the previous reported errors, happening on dev builds:
- https://github.com/MetaMask/metamask-extension/issues/17867
- https://github.com/MetaMask/metamask-extension/issues/17745

https://user-images.githubusercontent.com/54408225/222414830-a0621cb2-2f09-4b8b-8640-1788d6fc88b9.mp4

### Steps to reproduce

1. Go to test dapp
2. Click any signature
3. Open MetaMask console
4. Click Sign -- see error on the UI console

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by OGPoyraz** [comment]
This will be fixed here: https://github.com/MetaMask/metamask-extension/pull/19179
