### ISSUE TITLE
[Bug]: wrong currency when there is no ETH to send tokens

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#17963]
### Describe the bug

When trying to send tokens (i.e. USDC) with no (not enough) ETH to send the error message is wrong stating "not enough USDC to send" instead of "not enough ETH to send"

network : Arbitrum
browser : Chrome
Metamask : 10.25.0

### Steps to reproduce

1. try to send token (i.e. USDC) with no ETH in account

### Error messages or log output

```shell
Error message "There is not enough USDC to send tx ..."
```

### Version

v10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

none

![Metamask - low ETH display error - Screenshot from 2023-03-03 02-54-36](https://user-images.githubusercontent.com/25609/222482043-8b02a816-ee0d-476e-8477-f6a3d88a7c0f.png)

**Comment by OfficialSupportt** [comment]
@SvenMeyer We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by bschorchit** [comment]
Thank you for your report, @SvenMeyer . Closing as this issue is being tracked here https://github.com/MetaMask/metamask-extension/issues/17371
