### ISSUE TITLE
[Bug]: Ledger cannot interact with smart contracts anymore - sumit tx fails "network error"

### ISSUE THREAD

**Issue by blockchainguy2000** [MetaMask/metamask-extension#17964]
### Describe the bug

Starting today, I am unable to submit transactions that interact with smart contracts from my Ledger Nano S. Metamask reports an error "network error" before the Ledger pops up any confirmation (i.e. I don't get to the tx confirmation step on the Ledger). The transaction then appears as failed in the actions history list.

Sending ETH works though. Just any smart contract interaction fails.

I've tried several things to try to isolate or exclude problems:
1. Tried a backup Ledger device (restored from same seed): same issue
2. Updated both Ledgers to latest firmware: same issue
3. Tried to interact with contracts on other blockchains (e.g. Polygon): same issue
4. Connecting the Ledger through both HID and Ledger Live: same issue. In case of Ledger Live it prompts to open the bridge then as soon as I send the transaction in Metamask Ledger Live reports bridge was closed. Again, no prompt on the Ledger itself.
5. Tried on Windows and Mac: same issue
6. Tried on Chrome and Firefox (both up to date): same issue
7. Disabled and enabled Blind Signing again in the Ledger ethereum app: same issue
8. Removed the Ledger from Metamask and readded the account: same issue
9. Tried different ethereum mainnet rpc (quicknode): same issue

Interestingly, smart contract interactions from Ledger Live itself DO work. For example installing the 1inch app in Ledger Live and doing a swap in the 1inch web app *from within* Ledger Live works, the transaction gets submitted, Ledger prompts for confirmation, everything works. Trying to use 1inch from the browser fails, in fact as mentioned all smart contract interactions fail.

Given all of the above I think there is a high likelihood there is a bug in Metamask when it comes to submitting transactions that interact with smart contracts. As the issue reproduces independently of
- device
- OS 
- browser 
- blockchain / rpc provider
- BUT other apps ARE able to submit smart contract transactions (Ledger Live + 1Inch app),
...it points to the issue being with Metamask somehow.

### Steps to reproduce

1. Connect Ledger Nano S to metamask 
2. Try to interact with a smart contract (e.g. do a swap on uniswap/1inch, approve some token etc)

### Error messages or log output

```shell
Network Error
```

### Version

10.25.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows, MacOS

### Hardware wallet

Ledger

**Comment by JCosmicR** [comment]
Same issue with the Ledger Nano S+, starting today also.
Firmware, Ledger Live and Ethereum App all up-to-date

Was absolutely fine yesterday

**Comment by Howth88** [comment]
Same issue! Nearly went insane trying to figure out why.

**Comment by Jstone1809** [comment]
Same issue with the Ledger Nano S+ & Nano X, starting today also.
Tried multiple browsers & networks, still same error

**Comment by Beerbaron105** [comment]
Same issue.

Last successful transaction was two weeks ago. This morning all attempts to use uniswap, 1inch, and other defi exchanges failed with my typical setup using metamask and ledger. It's a network error. Tried multiple slippage, network fees.

There is some handshake error between ledger, or metamask, doubtful it's a defi exchange.

**Comment by invest4freee** [comment]
Have the same issue on all ledger devices, able to send but not conduct smart contract transactions

**Comment by Schnitzel2023** [comment]
Exactly the same issue. Ledger NANO and Metamask, tried all different browsers. Network error appears as soon as the Button is pressed and transaction isn´t signed off. Interaction with Ledger App directly works fine, also sending. But can´t interact with Defi Protocols at all. Very annoying....

**Comment by zxw018018** [comment]
Same problem here

**Comment by Jstone1809** [comment]
Its a problem with MetaMask, a workaround currently I'm using is just Ledger with TrustWallet

**Comment by esteban89** [comment]
same over here... ledger works with other wallets but stopped working with metamask when interacting with defi

**Comment by johnydeveth** [comment]
Same issue, ledger s plus + mac os + firefox/chrome/brave

**Comment by sirounces** [comment]
same errors for me this morning. I can send ETH no problem from my ledger, but i cannot send any ERC20 token. My other metamask hotwallets can send and receive ERC20 tokens without issue. This is limited to my ledger device. I can receive ERC20 tokens to my ledger address but cannot send the tokens back out. I only get "Transaction Failed: Network Error"

**Comment by danjm** [comment]
Hi everyone,

MetaMask engineer here. We are investigating.

What networks are you using when this is happening?

**Comment by Schnitzel2023** [comment]
> 

I have tried on three different chains, FTM, Arbitrum, BSC. The problem is everywhere...

**Comment by blockchainguy2000** [comment]
Confirm, every chain. See also original description, tried also different RPCs (e.g. quicknode), same issue.

**Comment by cthg0d** [comment]
> Hi everyone,
> 
> MetaMask engineer here. We are investigating.
> 
> What networks are you using when this is happening?

Hi @danjm. At the moment, all seems to be working for me. But I reproduced the issue before it was "fixed" out of nowhere.

As the few above me mentioned, it's for all EVM networks. I trace through the steps below and end up with a code chunk highlighting a Low level networking error chunk:
1. Attempt a tx interacting with a smart contract.
2. Get an instant failure within Metamask (the state where you can click on the retry button in the extension, and the explorer link is disabled because it hasn't been submitted yet). **No tx is sent to my Ledger to sign.**
3. Explore in devtools and find an error message with a link to https://metamask.github.io/eth-ledger-bridge-keyring/bundle.js line `20039`.
4. Discover good code comments:
<img width="557" alt="Screenshot 2023-03-02 at 11 45 09 AM" src="https://user-images.githubusercontent.com/110144971/222495401-990e0442-20aa-4b41-8173-926d90da9be3.png">

Hope this helps you.

**Comment by danjm** [comment]
thanks @cthg0d, that's helpful

**Comment by danjm** [comment]
We believe this has been fixed. Can some people comment to confirm?

**Comment by isSerge** [comment]
works for me now

**Comment by Lucatik** [comment]
For me too!

**Comment by xalexec** [comment]
> We believe this has been fixed. Can some people comment to confirm?

works for me now,can you tell me some details

**Comment by Schnitzel2023** [comment]
works for me too now. But I have to say the last days in general, for me personally MM was very laggy and had to close down and reopen it quite often in the browser, to sign off the transactions... Thanks for support!

**Comment by arcarda52** [comment]
Hİ, 
my problem is not solved.
All interact end with failure.

ledger-live-mob-3.16.0-( 66576)-2023-03-02-logs.json

**Comment by jkleiman** [comment]
Was happening to me too. Tried new cables, devices, browsers, laptops, same issues.

Now it's working ¯\_(ツ)_/¯ 

I have ordered a trezor as a backup

**Comment by arcarda52** [comment]
My problem is not in metamask, all operatıons gets fail. ( swap, sending, pancake liquidity remove etc.)
What should ı do?
Thks

**Comment by JCosmicR** [comment]
Great to hear it's been fixed. But do we know what caused this ?

**Comment by arcarda52** [comment]
> Hi everyone,
> 
> MetaMask engineer here. We are investigating.
> 
> What networks are you using when this is happening?

bab smart chain.  Problem is still goes on

**Comment by sirounces** [comment]
My Eth network transactions are now working again.  

Canto EVM still not operating correctly with metamask.  (i know this is an obscure one, but it was working up until today)

**Comment by buidragon** [comment]
Problem still occur. Not 100 percent but some chain still having problem connecting to MetaMask.

**Comment by buidragon** [comment]
has it been working for anyone?

**Comment by OfficialSupportt** [comment]
> Problem still occur. Not 100 percent but some chain still having problem connecting to MetaMask. 

@buidragon We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> My Eth network transactions are now working again.  
> 
> Canto EVM still not operating correctly with metamask.  (i know this is an obscure one, but it was working up until today)

@sirounces We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> > Hi everyone,
> > 
> > MetaMask engineer here. We are investigating.
> > 
> > What networks are you using when this is happening?
> 
> BNB smart chain.  Problem is still goes on

@arcarda52 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> My problem is not in metamask, all operatıons gets fail. ( swap, sending, pancake liquidity remove etc.)
> What should ı do?
> Thks
> 

@arcarda52 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> Confirm, every chain. See also original description, tried also different RPCs (e.g. quicknode), same issue.

@blockchainguy2000 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> > 
> 
> I have tried on three different chains, FTM, Arbitrum, BSC. The problem is everywhere...
> 

@Schnitzel2023 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> same errors for me this morning. I can send ETH no problem from my ledger, but i cannot send any ERC20 token. My other metamask hotwallets can send and receive ERC20 tokens without issue. This is limited to my ledger device. I can receive ERC20 tokens to my ledger address but cannot send the tokens back out. I only get "Transaction Failed: Network Error"
> 
> tried chrome/firefox/edge  All the same error when using a ledger

@sirounces We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> Same issue, ledger s plus + mac os + firefox/chrome/brave
> 

@johnydeveth We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> same over here... ledger works with other wallets but stopped working with metamask when interacting with defi

@esteban89 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> Same problem here

@zxw018018 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> Have the same issue on all ledger devices, able to send but not conduct smart contract transactions 

@invest4freee We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> Same issue.
> 
> Last successful transaction was two weeks ago. This morning all attempts to use uniswap, 1inch, and other defi exchanges failed with my typical setup using metamask and ledger. It's a network error. Tried multiple slippage, network fees.
> 
> There is some handshake error between ledger, or metamask, doubtful it's a defi exchange. 

@Beerbaron105 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> Same issue with the Ledger Nano S+ & Nano X, starting today also.
> Tried multiple browsers & networks, still same error

@Jstone1809 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> me too nano s and s plus 

@xalexec We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
> Same issue! Nearly went insane trying to figure out why. 

@Howth88 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by OfficialSupportt** [comment]
@blockchainguy2000 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9

**Comment by danjm** [comment]
@buidragon which chains are you having trouble with

**Comment by danjm** [comment]
There were some comments in this thread from a scam account. They have been removed. Remember to never give your private keys or secret recovery phrase to anyone. MetaMask support will never ask for it.

**Comment by blockchainguy2000** [comment]
@danjm can you please let us know what the issue was? Maybe a link to a commit fix?

**Comment by danjm** [comment]
the issue was a CORS issue on a ledger server. The ledger libraries we use to connect ledger to MetaMask send a network request to get contract metadata so the ledger can show a human-readable representation of the contract interaction (before it is signed). The failure of that network request was disrupting the sending of data from MetaMask to Ledger.

We need to make a further fix so that signing is possible regardless of whether the ledger servers are up or down, to prevent this sort of failure in the future, but fixing the CORS issue on the server side patches this problem for now.

**Comment by snowyberry** [comment]
Sadly the issue still persists with Firefox. Works fine for me on Edge/Chrome.

**Comment by isSerge** [comment]
I am also experiencing this issue again, trying to swap on Uni v3 on Arbitrum

**Comment by danjm** [comment]
@isSerge which browser are you using?

**Comment by isSerge** [comment]
> @isSerge which browser are you using?

I was using Brave, but now it seem to work

**Comment by ajb** [comment]
Still getting this error. 10.28.2

**Comment by olafswan** [comment]
Same error for me too...

**Comment by Karoskodev** [comment]
same error starting  from today

**Comment by MicahZoltu** [comment]
What is the status of this?  I shouldn't need to be able to access Ledger servers to use my ledger!

**Comment by vivek-consensys** [comment]
@MicahZoltu can you share the test-dapp that you are currently using for this? I am able to use my Ledger to interact with smart contracts without any issues.
