### ISSUE TITLE
[Bug]: When `eth_sign` is disabled we fire a `Signature Approved` event everytime we call the RPC method

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17974]
### Describe the bug

**Problem**: when `eth_sign` is disabled from Advanced settings, we fire a `Signature Approved` event everytime we call the RPC method. This should not be the case.

This issue was introduced in 10.25.0, by this PR https://github.com/MetaMask/metamask-extension/pull/17308

https://user-images.githubusercontent.com/54408225/222666667-07b91fba-798c-4daf-8f95-ab64391ba351.mp4

### Steps to reproduce

1. Open Segment or open background console for check the network requests to Segment
2. Disable the functionality of `eth_sign` from MetaMask Advanced Settings
3. On another window, go to test dapp
4. Connect to test dapp
5. Click Eth Sign
6. See how the `Signature Approved` event is fired

### Version

10.26.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by OfficialSupportt** [comment]
@seaona We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/LA7fG3N7FgvbzjPS9
