### ISSUE TITLE
[Bug]: Interacting with a smart contract on gnosis chain with Chrome can cause the metamask wallet UI for freeze and show the loading spinner

### ISSUE THREAD

**Issue by bark4mark** [MetaMask/metamask-extension#17982]
### Describe the bug

Interacting with a smart contract on gnosis chain with Chrome can cause the metamask wallet UI for freeze and show the loading spinner.

When I look at the console for metamask I can see it tries to call out to https://gas-api.metaswap.codefi.network/networks/100/suggestedGasFees to get gas information, however this request fails with a 500 error. The error is handled that everything still works fine, however if you try interact with multiple contract methods the failures build up and Chrome begins to block the HTTP request and not returning the response value.

The error returned by the request is as follows:

```
{
  "error": "Cannot read properties of undefined (reading 'getBlock')"
}
```
When chrome starts to throttle the requests, it gives an explanation and you can see there is no error message, it never resolves the response for the get request.

On mainnet this request successfully returns the information for gas prices as expected.

### Steps to reproduce

1.Ensure you are using Chrome with the latest version of the metamask extension ()
2. Navigate to https://app.hedgey.finance/ and connect your wallet
3. Navigate to Escrowless Token Swaps from the left hand menu
4. In the network dropdown at the top of the page choose gnosis chain
5. Fill in some details, any token value and address should be fine
6. Click Initiate swap and follow the wizard until metamask pops open for approval
7. Reject the approval and click initiate swap (may need to be done once or twice more)
8. Notice Metamask eventually just sticks on the loading screen. 

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Additional context

Once Chrome is throttling the request it's as if metamask becomes unresponsive most of the time and unusable until the browser is restarted.

This has only started happening quite recently, I feel since the last update.

I have recreated this issue on a few different computers and operating systems, always in Chromes with Gnosis. Firefox never throttles the extension but you can see the get request fail in the console.

**Comment by wizky1** [comment]
Screenshots or videos of the relevant information and request headers/responses will also be useful for our team to identify what may be happening.

**Comment by danjm** [comment]
probably a duplicate of https://github.com/MetaMask/metamask-extension/issues/17467
