### ISSUE TITLE
[Bug]: SIWE screen does not display Internet protocol on the domain

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17997]
### Describe the bug

**Problem**: SIWE screens do not display the internet protocol (http/https) on the domain header.

![image](https://user-images.githubusercontent.com/54408225/223092257-1275c4a0-7d58-4fe1-ab2a-1adbf6b0ac62.png)

**Expected**: display protocol, as well as we do in other signatures. See example below:

![image](https://user-images.githubusercontent.com/54408225/223092432-3e2bb733-eaa2-412d-ae75-5eea1718d811.png)

### Steps to reproduce

1. Go to https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Sign In With Ethereum -- see domain has no protocol http/https

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
I am also wondering, this error shows that we are using 2 different components for the same domain header. Could we re-use the same component in the different screens?

**Comment by bschorchit** [comment]
We should re-use this origin pill component: https://github.com/MetaMask/metamask-extension/pull/15603
