### ISSUE TITLE
[Bug]: Cannot proceed performing a Send ETH tx: `TypeError: Cannot read properties of undefined (reading 'userEditedGasLimit')` [Rare Case]

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18021]
### Describe the bug

**Problem**: when I was performing a Send ETH transaction on Goerli, I got into the error  `TypeError: Cannot read properties of undefined (reading 'userEditedGasLimit')` and could not proceed to the confirmation screen.
When I cancelled the tx and try again, MM worked normally again.

https://user-images.githubusercontent.com/54408225/223453618-c8bea44a-e51d-4b97-92ba-1f7f61565e00.mp4

### Steps to reproduce

The behaviour is not consistent:

1. Click Send
2. Add recipient
3. Click Confirm -- if you can proceed, try again

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Labelled it a sev3 for now as it's a rare case and re-starting the transaction works as a recovery path.
