### ISSUE TITLE
MetaMask opens an unwanted new tab when installed via Chrome extension synchronization.

### ISSUE THREAD

**Issue by interfect** [MetaMask/metamask-extension#1804]
When you first install MetaMask, it opens a tab explaining how to use it.

That's fine if the user actually did just install MetaMask on that browser. But MetaMask can also be installed into a Chrome instance because the user previously installed it on *another* Chrome instance, and Chrome has just installed it locally of its own accord, as part of Chrome's extension-syncing feature.

In that case, the new tab is an unwanted interruption, because the user hasn't just installed MetaMask; Chrome has. The user probably just opened their browser to go somewhere else, and doesn't want a MetaMask tab they've already seen on another device poping up over whatever tab they were trying to use.

When being installed via Chrome's extension synchronization system, that introductory page should not be displayed. If that's not possible, the new-install behavior should be made much less obtrusive, and in particular should *never* take the user away from a tab they might be using. Perhaps it should be a notification, or a tab that opens behind the current tab.

Browser: Chrome 59.0.3071.115
OS: Windows 7

**Comment by kumavis** [comment]
@interfect hello/
we're not aware of a way to detect when a user has installed the extension for the first time vs chrome's extension-sync

let us know if you find one!

**Comment by interfect** [comment]
In that case, I would suggest making the install behavior more appropriate
to either circumstance (maybe a Chrome desktop notification?). If a user
has two or more devices, the extension is going to be installed for them by
sync at least as much as it is installed manually. It doesn't make sense
for it to act like every install is a manual install and pop up a tab over
whatever else is going on in the browser.
