### ISSUE TITLE
Support web3 1.0 beta

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1806]
Web3 1.0 beta is now out and available for experimentation with.

This issue should represent a place to define what that support will mean for us, and then we can implement that plan.

http://web3js.readthedocs.io/en/1.0/web3.html

**Comment by kumavis** [comment]
part of the 1.0 is the acceptance that web3 is a good at being a library and not at being a standard -- so we should not inject web3 1.0

now we just need the ethereumProvider api finalized

**Comment by cmditch** [comment]
1. Metamask uses Infura
2. Web3 1.0 is deprecating HttpProvider for `web3.eth.subscribe` and other log/event related functions, and opting for Websockets instead.

I'm guessing Infura is coding up a solution for websockets? Or is Infura already supporting websockets?

I've been having trouble testing web3 1.0 event/log functions as TestRPC doesn't support websockets, Parity requires authentication, Infura doesn't seem to have support yet. 

Curious what setup you guys/gals use? Thanks!

**Comment by rstormsf** [comment]
also `web3.eth.accounts` is not an array of accounts.
`web3.eth.accounts.wallet` is what being used to load your current accounts

**Comment by cmditch** [comment]
@rstormsf Metamask might not tie into the web3 wallet functionality

I'm guessing they'll implement that themselves and still rely on `web3.eth.getAccounts` and `web3.eth.defaultAccount`

**Comment by danfinlay** [comment]
Closing as duplicate of #2350
