### ISSUE TITLE
Migrate components to TS: AvatarBase

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18063]
### Description
Migrate `AvatarBase` to TS

Use `BadgeWrapper` as an example of how the typescript files should look https://github.com/MetaMask/metamask-extension/tree/develop/ui/components/component-library/badge-wrapper

### Technical Details
- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` follow [TS conventions](https://www.notion.so/Use-TypeScript-9ec7bd8fc8cf4d82b81cd8943c4707cd?pvs=4#7e6410b21100455a9a08442108f19d78)
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation 

### Acceptance Criteria
- Component has been converted to TypeScript

**Comment by spiritanand** [comment]
Hey @georgewrmarshall, can I help you out with this?

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, sure you can take a crack at it if you like. Does this ticket have enough detail to complete the task? We would like to align our components with BadgeWrapper component. I've updated the description. Let me know if that makes sense?

**Comment by spiritanand** [comment]
I will get started. If I get stuck anywhere, I will post here.

**Comment by georgewrmarshall** [comment]
Hey @spiritanand, yes also convert it from an `object` to an `enum`. Assigned. Thank you

**Comment by spiritanand** [comment]
@georgewrmarshall will the following keys become small case like XS ⇒ xs and so on?
<img width="500" alt="image" src="https://user-images.githubusercontent.com/53999998/227981523-ddfa5bc0-ffd5-45be-8521-620699db0e52.png">

**Comment by spiritanand** [comment]
@georgewrmarshall what about the enum? Is it right the way it is? Or should I turn that into `PascalCase` as well?

**Comment by spiritanand** [comment]
@georgewrmarshall, in `avatar-base.stories.tsx` I am getting an error in the `Icon` component. The type of color should be an `IconColor`, not simply a `Color`. 

`TS2322: Type 'Color.infoDefault' is not assignable to type 'IconColor | undefined'`

<img width="862" alt="image" src="https://user-images.githubusercontent.com/53999998/228130126-49c8e093-3cac-4e44-b8b0-f2e500681b24.png">

Should I go ahead and update that as well?

**Comment by georgewrmarshall** [comment]
Yes, I've got a PR open to migrate the Icon component to TypeScript here https://github.com/MetaMask/metamask-extension/pull/18330

**Comment by spiritanand** [comment]
@georgewrmarshall I have created the PR to close this issue.
