### ISSUE TITLE
Bug: dapps can't send transaction with type `0x02`

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#18076]
See comments on #11824

![Screenshot from 2023-03-09 11-14-55](https://user-images.githubusercontent.com/7499938/224059883-c0ca4fed-40be-4def-851b-ce3f18e65b12.png)

**Comment by davidmurdoch** [comment]
`0x02` is a JSON-RPC DATA type, and `0x2` is a JSON-RPC `QUANTITY` type. I'm pretty sure the `type` field of a JSON-RPC Transaction (sent via `eth_sendTransaction`) is a `QUANTITY` and must be represented in its compact form (`0x2`).

**Comment by davidmurdoch** [comment]
Bad robot.
