### ISSUE TITLE
Track & record origins directing to malicious sites

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1807]
Since we're now enforcing a malicious site blacklist, we should also record the origins of these malicious sites.

Possible implementations:
- Black-list content script pings a recording server when forwarding to `phishing.html`.
- Since `/phishing.html` has analytics, we might be able to add some metadata to those page loads, like a query param with the origin.

**Comment by kumavis** [comment]
Ah thats interesting. We can capture `document.referrer` before redirecting to our phishing page. May be tricky to get google analytics to parse and display this info.

**Comment by kumavis** [comment]
we do this now~! and that data feeds back into our blacklist test suite :smile_cat:
