### ISSUE TITLE
i can't log in

### ISSUE THREAD

**Issue by vilasid** [MetaMask/metamask-extension#1808]

**Comment by vilasid** [comment]
i can't log in

**Comment by flyswatter** [comment]
Is your password failing to unlock MetaMask? If you remember your 12-word seed phrase, you can click "I forgot my password" and restore from the seed phrase.

**Comment by vilasid** [comment]
I didn't forget the passwords but I can't log in to network 


Sent from Yahoo Mail for iPhone


On Saturday, July 22, 2017, 11:25 PM, Dan Finlay <notifications@github.com> wrote:


Is your password failing to unlock MetaMask? If you remember your 12-word seed phrase, you can click "I forgot my password" and restore from the seed phrase.

**Comment by kumavis** [comment]
If you'd like us to help you, you'll need to explain clearly what you did and what you saw that made you think that you "can't log in to network"

**Comment by tmashuang** [comment]
Closing. Will reopen if this is still an issue.
