### ISSUE TITLE
Convert confirm-send-ether to functional component

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#18094]
Convert [confirm-send-ether](https://github.com/MetaMask/metamask-extension/tree/develop/ui/pages/confirm-send-ether) to functional component:

1. add unit test coverage
2. get rid of container component
3. make component functional

**Comment by bschorchit** [comment]
Update for visibility: Removing from sprint as we'll be prioritizing mobile refactoring this quarter
