### ISSUE TITLE
Lost acccess to account

### ISSUE THREAD

**Issue by nyuqiu** [MetaMask/metamask-extension#1810]
Hello, i created account in metamask to buy opus tokens, i forgot password and tried to create new one with seed phrases, but i have only 10 words instead 12, i dont think i didnt write 2 words, it was just generated like that. I was so frustrated and i add 2 other random words and i was able to change my password, but when i log in i dont see accounts with my tokens. If i remember my old password ill get acces or account is lost?

**Comment by flyswatter** [comment]
A full seed phrase is going to have 12 words, each word is important, you can't just make up 2 random words and have it recover your accounts.

You *could* potentially write a script to brute-force the remaining possible two words, although you don't know what position they'd be in.

This would involve some custom programming, but depending on how much value is at stake, might be worth your time.

I'm sorry, there's nothing else we can do to help.

**Comment by nyuqiu** [comment]
So it mean my account is still somewhere there with unchanged password and if i put correct password i get access?

**Comment by flyswatter** [comment]
The password is actually only used to locally encrypt your seed phrase. The seed phrase is all you need. If you can figure out the last two words, you should be able to recover the accounts.

**Comment by nyuqiu** [comment]
Thanks for help

**Comment by johnjames333** [comment]
@nyuqiu 
we have developed our own hardware for cracking Metamask wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by richardsonn09** [comment]
@nyuqiu 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
