### ISSUE TITLE
[Bug]: Confirm button remains disabled when I click `Proceed anyways` on Approve All and Revoke screens

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18100]
### Describe the bug

**Problem**: when there is a gas estimation error when I am performing a setApprovalForAll or revoke ERC721, if I click `I want to proceed anyway` I cannot proceed as the Confirm button remains disabled

Affected screens:
- setApprovalForAll 
- revoke

https://user-images.githubusercontent.com/54408225/224307643-c797ffda-62b6-4036-a0e0-024827d17b79.mp4

### Steps to reproduce

1. Select Goerli
2. Go to this contract https://goerli.etherscan.io/address/0xb5bedba7ff2b5a83c1ab1acdcf36b90c6b1ee2ff#writeContract
3. Connect MM
4. Click setApprovalForAll
5. (For Approve All screen) Add `0x07Be9763a718C0539017E2Ab6fC42853b4aEeb6B` and `true`
6. Click Write
7. Click Proceed anyways -- see button is still disabled
8. (For Revoke screen) Add `0x07Be9763a718C0539017E2Ab6fC42853b4aEeb6B` and `false`
6. Click Write
7. Click Proceed anyways -- see button is still disabled

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by filipsekulic** [comment]
Hey @seaona!
I tried to reproduce this issue, but without success. Maybe it was fixed in the meantime, because this issue was discovered in the previous version - 10.25.0.

https://user-images.githubusercontent.com/92310504/225055933-91f28ebc-908d-4d94-af38-126b83ef7b7b.mov

**Comment by filipsekulic** [comment]
Should I use my own hex address or the one you mentioned in the issue description in order to reproduce this bug?
I tried with the one you suggested, but couldn't reproduce the bug. On the other hand, when I used my own hex address, I could reproduce it.

**Comment by seaona** [comment]
I am still able to reproduce this issue in 10.28.X.

**More repro steps:**
1. Change to Optimism
2. Go to this contract https://optimistic.etherscan.io/token/0xc36442b4a4522e871399cd717abdd847ab11fe88#writeContract
3. Click Approve with some random data
4. Click Proceed on MetaMask -- see Approve button is always disabled

[proceed-anyways.webm](https://user-images.githubusercontent.com/54408225/232710698-86744866-e2cf-40d8-a790-d36cbf74e072.webm)
