### ISSUE TITLE
Phantom extension (23.3.0 version) blocks MetaMask injection at wndow.ethereum

### ISSUE THREAD

**Issue by alchimos** [MetaMask/metamask-extension#18113]
### Describe the bug

When both Phantom (v. 23.3.0 - released on march 10th) and Metamask (v. 10.25.0) extensions are installed, MetaMask does not inject its global API at window.ethereum. You can know MetaMask is installed only looking at the deprecated window.web3 and only if Coinbase wallet extesion is not present.

### Steps to reproduce

On Chrome (111.0.5563.64 version):

1. Install Phantom 23.3.0 version.
2. Install MetaMask version 10.25.0 version.
3. Reload page.
4. On Chrome console look for window.ethereum. You should get `undefined`.

### Error messages or log output

```shell
No errore message
```

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by altmshfkgudtjr** [comment]
It seems to be a bug that occurs in Phantom `23.3.0`,
as of now, it has been confirmed that Phantom `23.3.1` version has been distributed. If you use the version after updating it, you can see that window.ethereum is normally injected.

**Comment by alchimos** [comment]
Thanks @altmshfkgudtjr. 
Just moved to Phantom `23.3.1` and it's working great now.

**Comment by OlexBeatable** [comment]
Updating the version doesn't fix this bug. Regardless the window.ethereum if present, Phantom blocks interaction with metamask anyway. Looks like Phantom extension override the ethereum object
