### ISSUE TITLE
Sign transaction and broadcast later

### ISSUE THREAD

**Issue by thisbejim** [MetaMask/metamask-extension#1811]
Right now the sign method doesn't work and is [not expected to be fixed](https://github.com/MetaMask/metamask-extension/issues/1530#issuecomment-306320765).

How might one sign a transaction but broadcast it later with MetaMask in its current state today?

**Comment by flyswatter** [comment]
You would have to export your private key and sign it with another tool. MetaMask today doesn't support delayed signing & broadcasting. http://metamask.consensyssupport.happyfox.com/kb/article/18-exporting-a-metamask-account/
