### ISSUE TITLE
eth_estimateGas throws "Transaction execution error."

### ISSUE THREAD

**Issue by CurrencyTycoon** [MetaMask/metamask-extension#1812]
This looks similar to #1628 although it's happening when I try to call a function of my contract.

Browser: Chome 59.0.3071.115 running on GNU/Lunix Ubuntu 17.04
Metamask: 3.9.0 
Solidity contract source: https://etherscan.io/address/0x1aFdbFde88Bd0189cb0479d309b3794e99E3d53F#code

### Expected Behaviour

When I'm calling my contract's `closeLong()` function using web3, I would expect the MataMask dialog  to show where I can choose my gas and approve the transaction.

You can try here https://www.ethhodler.org/bancor/ and click "Sell BNT" to see what happens.

### Actual Behaviour:

Metamask does not pop up. After a second, the console for the extension shows the following error:

```
InternalError {message: "Transaction execution error.", code: -32603}
code
:
-32603
message
:
"Transaction execution error."

```

Further more, it seems that the background Metamask process goes into a loop and starts hitting the `https://mainnet.infura.io/metamask` servers hard over and over again (~240 requests per minute). This continues until I close the page.

I've checked to make sure the ABI is correct.

I've isolated the problem to just one line on the contract. It happens on line 175 on here https://etherscan.io/address/0x1aFdbFde88Bd0189cb0479d309b3794e99E3d53F#code (as you can see all other lines are commented out. What's funny is that the `long()` function calls the same code with different args, but it works OK)

Again, testing page is here https://www.ethhodler.org/bancor/ - the "Sell BNT" button is causing the problem.

Would be happy to put a 1 ETH bounty on this bug if it can be fixed, or someone knows the solution/workaround. Thanks.

**Comment by kumavis** [comment]
@CurrencyTycoon thanks for the detailed report
could you look in the background logs
https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome
in the network tab (open this first before attempting to reproduce the issue)
and look for a request that has that result "Transaction execution error."

if you find that request right click it in the list and select `copy as cURL` and communicate that to us here or in another channel (data may contain your eth address)

**Comment by flyswatter** [comment]
I suspect this is an error during the eth_estimateGas call.

**Comment by CurrencyTycoon** [comment]
Thanks for your replies guys! Yes, it sounds like it could be related to #1812. Here is the curl request:

```
curl 'https://mainnet.infura.io/metamask' -H 'origin: null' -H 'accept-encoding: gzip, deflate, br' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'authority: mainnet.infura.io' --data-binary '{"id":4960368400303930,"jsonrpc":"2.0","params":[{"from":"0xf5ec0ec4770802475dfa6381f1935d70b6217099","to":"0x1afdbfde88bd0189cb0479d309b3794e99e3d53f","value":"0x0","data":"0x24f82526","gas":"0x493e0","gasPrice":"0x4a817c800"}],"method":"eth_estimateGas"}' --compressed

```

Is there any way to bypass the `eth_estimateGas` call? I have tried to specify my own gas & gasPrice too, but no luck.

Also, as I mentioned, I've noticed that there are many hits going to `mainnet.infura.io` whenever I interact my app. For example, my app polls `web3.eth.getBlock` every second and then issues an event to the UI whenever the block changed, likewise, it checks to see if the network has changed. Today, I've noticed that these calls are going out via the JSONRPC to your servers, which must be sending you a lot of traffic! I was assuming that the calls to `web3.getBlock` would be cached by the extension itself. Is there a better pattern to poll for the next block?

**Comment by flyswatter** [comment]
Yeah, this is a pretty bad bug, thanks a ton for all the investigation, we'll be prioritizing it tomorrow morning and dealing with it soon.

**Comment by nadavhollander** [comment]
+1 on the above bug.  Payload that I'm seeing is pasted below, hope it's helpful!
` {"id":6305029270992,"jsonrpc":"2.0","params":[{"from":"0x2987aa227df48d4891b3fe667c7a0c463f8857b1","to":"0x79cb2e87efe965962b4761b15bfb8fdba5055adc","value":"0x0","data":"0x0cb719daafc779cdc0a764aba817773655671e3d1151d60b489502b9bc272378d571340b000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000594569be576f3081c68ffb107f17d4452f37fa0700000000000000000000000000000000000000000000000000000000000000010000000000000000000000223130303130303030303030303030303030303022","gas":"0x55730","gasPrice":"0x37e11d600"}],"method":"eth_estimateGas"}`
