### ISSUE TITLE
[Bug]: Sending an ERC721 throws error `Unable to determine Contract Standard`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18135]
### Describe the bug

**Problem**: when I am sending an ERC721 token I get the console error `Unable to determine contract standard`.

https://user-images.githubusercontent.com/54408225/224978257-0532eaba-73b5-4a95-b611-d7f3e1d8cad7.mp4

### Steps to reproduce

1. Go to test dapp https://metamask.github.io/test-dapp/
2. Deploy Collectibles
3. Mint a collectible
4. Add collectible to Wallet
5. Click NFT details
6. Send NFT
7. Confirm -- check MetaMask UI console

### Version

10.25.0 - NFT flag On

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
@seaona does this interfere with user experience in any way?

**Comment by seaona** [comment]
Nothing apparently, it seems it's only the console error @danjm
