### ISSUE TITLE
MetaMask dont see my Myst tokens from: 0xE7E01BABb53c98f8d84d05dFff64Ebb63ed37bF5

### ISSUE THREAD

**Issue by GringoPbSr** [MetaMask/metamask-extension#1813]
![mew mask](https://user-images.githubusercontent.com/21089641/28528924-667e0b40-708f-11e7-8808-c6aa3e688c2d.jpg)

**Comment by GringoPbSr** [comment]
0x9F1dD61498233CEb52F977246E0ab20453d6a5a6

**Comment by flyswatter** [comment]
Here's our current guide on managing tokens in MetaMask: http://metamask.consensyssupport.happyfox.com/kb/article/4-managing-tokens 

You probably need to add the myst token manually.

**Comment by GringoPbSr** [comment]
![myst](https://user-images.githubusercontent.com/21089641/28559762-3c9a4292-7118-11e7-9823-7e6980fc5077.jpg)
Yes I tried it, but it is not working.

**Comment by GringoPbSr** [comment]
I found also that etherscan.io and ethplorer.io did not see this token. Only MyEtherWallet catch it
![myst2](https://user-images.githubusercontent.com/21089641/28560086-8ae53a1e-7119-11e7-982b-f9cb238a59eb.jpg)
.

**Comment by GringoPbSr** [comment]
I also found that ethplorer.io and etherscan.io did not see it. Only MyEtherWallet catch it.
![myst2](https://user-images.githubusercontent.com/21089641/28560149-d41990e0-7119-11e7-91bd-ac6964f743ca.jpg)

**Comment by flyswatter** [comment]
> Yes I tried it, but it is not working.

MetaMask will currently only show a token if you have a balance. Is it possible you don't have any of these tokens yet?

**Comment by GringoPbSr** [comment]
Even etherdelta.github.io/#MYST-ETH using metamask see it: 
![myst3](https://user-images.githubusercontent.com/21089641/28562936-726d35ee-7124-11e7-8bb0-8834ccd6e822.jpg)

**Comment by kumavis** [comment]
When adding the token to metamask you need to insert the "Contract address"
of the token, not your address

Looks like MYST is 0xa645264c5603e96c3b0b078cdab68733794b0a71
https://ethplorer.io/address/0xa645264c5603e96c3b0b078cdab68733794b0a71

**Comment by GringoPbSr** [comment]
Yes I know. I tried add 0xE7E01BABb53c98f8d84d05dFff64Ebb63ed37bF5 several times, but it is not working. Actually I can transfer them without using metamask app, with exporting PK or using etherdelta transfer. But I wanted let you know, that there is a problem.

**Comment by GringoPbSr** [comment]
Yes it is working I must add this token address: 0xa645264c5603e96c3b0b078cdab68733794b0a71 like you said. Now it is showing the amount. But it is different like where I sent Eth during ICO.
