### ISSUE TITLE
[Bug]: NFT picture is not displayed after viewing its details on the MetaMask popup view

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18134]
### Describe the bug

**Problem**: NFT picture not displayed after clicking its details on the MetaMask popup view.

https://user-images.githubusercontent.com/54408225/224973876-a3ddb76a-f16b-4ffc-98a5-4e51056a90ee.mp4

### Steps to reproduce

1. Import an ERC1155
2. Open MM popup
3. Click NFT tab
4. Verify NT picture is there
5. Click the NFT to see details
6. Go back -- see how pic has disappeared an a gray square is displayed instead

### Version

10.25.0 - NFT flag On

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
Indeed the collection image also disappears. There are no errors on the console and it only happens with the popup. The full screen works fine. I see it every time I click on one of the NFTs and I go back

**Comment by darkwing** [comment]
Are these images URL's or data URIs?  Do we have a shareable SRP so I can try this out?  I'm unable to reproduce on Mac.

**Comment by seaona** [comment]
hi @darkwing you can do the same procedure as I did to get tokens:
1. Go to test dapp https://metamask.github.io/test-dapp/
2. Deploy ERC1155
3. Batch Mint token ids `1, 2, 3`
4. Import the NFTs using their token contract



This is the data reference used by the contract ipfs://bafybeidxfmwycgzcp4v2togflpqh2gnibuexjy4m4qqwxp7nh3jx5zlh4y/
