### ISSUE TITLE
[e2e] Update test-dapp to `v6.0.0` so we are able to Edit ERC20 decimals on TestDapp

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18143]

**Comment by bschorchit** [comment]
I believe this is done already, right? Should we close this issue?

**Comment by seaona** [comment]
This task has not been completed yet @bschorchit . The test-dapp was updated but this ticket aims to update the Test-dapp package version on the Extension repo and update the testcases in order to use the new test dapp version (some needed tweaks in order to work with the new version).

`"@metamask/test-dapp": "^5.6.0",`

we should use

`"@metamask/test-dapp": "^6.0.0",`

**Comment by bschorchit** [comment]
Oh, I see! Thanks for the info, Mariona 😊

**Comment by seaona** [comment]
The test-dapp was published this week, so we can now update the package. Since it is a fairly simple change, I've just created a PR for doing so, so we can unblock other tickets  relying on e2e testcases.
I've also modified the ticket title a bit, so the task is more clear

https://github.com/MetaMask/metamask-extension/pull/18844

**Comment by seaona** [comment]
Not sure why the PR is not appearing in the ticket :/ but in any case, PR is merged
