### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by QAAa00** [MetaMask/metamask-extension#18162]
### Describe the bug

usdt无法显示余额   usdt-bnb 一直是处理中
![image](https://user-images.githubusercontent.com/102711665/225226691-1d1eb5df-bf37-448f-a494-028f61f2acca.png)

### Steps to reproduce

1.
我用币安链充到钱包显示成功  但是钱包里的usdt无法发送也不无法交换
![微信图片_20230315143934](https://user-images.githubusercontent.com/102711665/225227135-39239d1d-04e1-4a4d-bab0-8e02554c2229.jpg)

### Version

6.1.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
This is a mobile bug report. If you are still experiencing issues, please contact support or open a github ticket at https://github.com/MetaMask/metamask-mobile/issues
