### ISSUE TITLE
[Bug]: Import Account without password

### ISSUE THREAD

**Issue by kyokai** [MetaMask/metamask-extension#18180]
### Describe the bug

not all JSON account files are password protected, currently cannot import an account without a password. Same as this older closed issue.
https://github.com/MetaMask/metamask-extension/issues/5681

### Steps to reproduce

1. Export Account as file, do not password protect
2. Click import account in metamask
3. Select exported file
4. Submit/ import button deactivated until password for file is entered

### Version

10.24 +

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by plasmacorral** [comment]
related to #16369
