### ISSUE TITLE
Sometimes tx approval window doesn't open

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1818]
From `@gis` on our slack:

> Hi,
>
> I've been having a problem recently where my EtherDelta order submissions don't register the way they used to. It used to be that when I clicked on a Buy/Sell order, I would be prompted to "Sign" as confirmation and the order would be placed. Now, nothing happens when I Buy/Sell an order. To get it to process, I have to click on the MetaMask extension, find the unsigned transaction in the list, click on it, then it will prompt me to Sign.
> 
> Is there any way to fix this? It happens both when I try to execute against an existing Buy/Sell order, or if I want to submit one of my own.

This was accompanied by a log:

```
SyntaxError: Unexpected token < in JSON at position 0
   at JSON.parse (<anonymous>)
   at asyncify (background.js:66871)
   at background.js:9413
   at background.js:9646
   at nextTask (background.js:65545)
   at next (background.js:65552)
   at background.js:9744
background.js:43123 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```

**Comment by Zanibas** [comment]
Could be infura shedding load and sending an HTML response. If the case, then we should handle that case gracefully (retry, catch, etc)

**Comment by kumavis** [comment]
I dont think we hit network when a tx is first added (i could be wrong), so it don't suspect that it would be affected by infura load shedding

**Comment by flyswatter** [comment]
We do for "estimate gas".
