### ISSUE TITLE
UX feedback -- more related to Oasis, but still somewhat related

### ISSUE THREAD

**Issue by sixside** [MetaMask/metamask-extension#1819]
I believe a lot of this feedback is Oasis specific, but there may (hopefully) be some nuggets that are valuable feedback to think of.

I know this is early stages and there's still much work to be done. But I thought I'd just document a 'less than ideal' user experience in the hopes that it will help move us all closer to a point where it's more user friendly for mass adoption. With that out of the way...

I was trying to use Oasis to buy some Maker (MKR). I am using the MetaMask Chrome extension. I started by trying to wrap ETH into W-ETH. I ran into a minor issue where I tried to wrap the max amount only to be informed in the MetaMask popup window that I didn't have enough gas for the transaction. So I went back to Oasis and subtracted the gas amount from the total amount of ETH and began the wrap. After a few seconds it completed. Ideally Oasis would have been able to pre-compute the required gas, and then tell the user "We will convert {desired_amount - required_gas} for you, ok? Y/n"

That was the first minor annoyance. Not a big deal really but what happened next compounded the problem...

Now that I had my W-ETH, I went to purchase MKT. It wasn't a ton of money (roughly $85 USD worth), but evidently that amount exceeded some pre-defined limit:

> You are trying to create a buy order above your defined allowance.

Okayy. So I need to change my limit. But guess what? Changing my limit ALSO requires gas! And now I don't have any ETH left (I already converted it all into W-ETH). Fine. I'll unwrap just enough of my W-ETH back into ETH to cover the gas cost required to raise my allowance level. BUT (and you probably know where this is going by now), Unwrapping my W-ETH costs gas!! So I basically boxed myself into a corner because of all these little gas fees of trying to execute various transactions.

Maybe it's an edge case and most people don't wrap 100% of their token. But regardless, I'm now essentially stuck. I'll have to send some more ETH into my wallet just to be able to buy MKR with my already wrapped W-ETH.

Again, please don't take this as a complaint. Just an observation to point out where some improvements could be made to the UX. 

I can see how it might be less of a problem with either of the two pieces (MetaMask & Oasis) and more a problem with inter-dapp communications. I would be curious just for my own personal knowledge: is there a mechanism available to dapp devs to query external smart contracts for its properties to pre-compute the gas required? I'm not sure if my understanding is correct, but I would presume that the Oasis dapp is somehow communicating with the MetaMask dapp, and if so, is there a way to ask other dapps 'what will this cost me?' so the originating dapp can use that figure?

**Comment by flyswatter** [comment]
Yes, they can estimate gas costs, but wouldn't that just box you into a corner tighter? The shift needed here was to leave a chunk of eth behind, not send more of your total.

The only time that really makes sense to send ALL of your ether is if you're abandoning that account, and we have an issue to add that switch:
#1537

Otherwise, I'm curious what you think could be improved here. Ether is the network token, we probably just need to emphasize that more early on and teach users about it?
