### ISSUE TITLE
[Bug]: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kaanbursa** [MetaMask/metamask-extension#18196]
### Describe the bug

I cannot load any site that has connect with metamask including metamask portfolio site. I have updated to latest version and I get this error:
RangeError: Maximum call stack size exceeded

### Steps to reproduce

1.

### Version

10.26.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
could you do the following:

1. Go to chrome://extensions
2. toggle on developer mode
3. under the metamask extension, click `background.html`
4. go to one of the sites where metamask crashes
5. screen shot any errors shown in the `background.html` window

**Comment by tonyxb** [comment]
![image](https://github.com/MetaMask/metamask-extension/assets/128413228/96ab0320-d995-4300-8cbe-0edbc65dadfb)
please help

**Comment by gauthierpetetin** [comment]
Other similar issues:
- https://github.com/MetaMask/metamask-extension/issues/3983
- https://github.com/MetaMask/metamask-extension/issues/3827
