### ISSUE TITLE
[Bug]: Cannot open MetaMask on Firefox v78

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#18190]
### Describe the bug

In this file https://github.com/MetaMask/metamask-extension/blob/Version-v10.28.0/babel.config.js#L8, we defined minimum firefox version should be v78, when i try to open the extension on firefox v78, i always get following error:

<img width="1435" alt="Screenshot 2023-03-16 at 13 13 51" src="https://user-images.githubusercontent.com/105063779/225617193-c22061b9-e164-44b8-b0b7-dbac193266c1.png">

Info: Test with Chrome V80 OK. 

### Steps to reproduce

1. Install firefox v78
2. Try to open extension and check the error 
Expected: extension should work on firefox v78

### Version

10.28.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
I typically get the old version of browsers here: [Chrome](https://www.slimjet.com/chrome/google-chrome-old-version.php) and [Firefox](https://ftp.mozilla.org/pub/firefox/releases/), incase this helps

**Comment by CrYptOGramps** [comment]
I am also having the same issue using MM ext on Firefox.  Still hunting for a solution other than remove and reinstall.  Cleaning caches and restart/update has no effect.  Just get the spinning wheel and a blank Metamask logo box until the temporary error message appears.  Very annoying.

**Comment by snd1** [comment]
> I am also having the same issue using MM ext on Firefox. Still hunting for a solution other than remove and reinstall. Cleaning caches and restart/update has no effect. Just get the spinning wheel and a blank Metamask logo box until the temporary error message appears. Very annoying.

Same here with metamask 10.25.0 and ff 102.8.0esr (64-Bit). Please fix this.
