### ISSUE TITLE
[Bug]: Opensea security provider - warning message dose not appear when user tries to send legacy/EIP1559 transaction

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#18216]
### Describe the bug

When the opensea security provider is enabled, user tries to send a legacy transaction or a EIP1559 transaction, warning message is not displayed.

https://user-images.githubusercontent.com/105063779/225887567-f29a875d-b382-4d47-a389-d673288cc106.mov

### Steps to reproduce

1. Enable Opensea security provider checker in extension settings experimental tab
2. Go to [test-dapp](https://metamask.github.io/test-dapp/)
3. Select one of the options:
SEND LEGACY TRANSACTION
SEND EIP 1559 TRANSACTION
Check that no warning message is displayed.

Expected: warning message should be displayed for both.

### Version

10.28.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
If the requests for Send and Send Legacy from the test-dapp are not mocked, they won't display a warning as the validate response returns a `0` for these specific requests. This is expected.

Whenever the `validate` message returns another value we should display the warning. You can use a proxy to mock the responses and you'll see that we do display the warnings for Send and Send Legacy, in case validate returns a different value than `0`


https://user-images.githubusercontent.com/54408225/225927609-0f75bc37-f281-4268-a338-9317d7ae32dc.mp4

**Comment by chloeYue** [comment]
Closed this issue as it's expected behaviour.
