### ISSUE TITLE
[Bug]: Metamask does not work on Firefox-Ubuntu

### ISSUE THREAD

**Issue by Themanhdh** [MetaMask/metamask-extension#18222]
### Describe the bug

The Firefox browser does not recognize Metamask, althought I have installed Metamask on this browser.

![1](https://user-images.githubusercontent.com/90931664/225929940-04c8688b-358b-4106-b0fc-45a4eb05e130.png)
![2](https://user-images.githubusercontent.com/90931664/225929954-af837976-d475-4636-9686-01698096d744.png)

### Steps to reproduce

1.check the compatible between metamask and ubuntu.

### Version

10.25.0

### Build type

None

### Browser

Firefox

### Operating system

Linux

**Comment by seaona** [comment]
@Themanhdh thanks for your report. Could you try disabling Phantom extension and see if it works?
It might be related to this https://github.com/MetaMask/metamask-extension/issues/18113

**Comment by Themanhdh** [comment]
Many thanks! It worked.
