### ISSUE TITLE
Chrome plugin transaction problems, firefox works (testrpc)

### ISSUE THREAD

**Issue by VogtAI** [MetaMask/metamask-extension#1822]
With Metamask for Chrome I cannot send any transactions using testrpc. Metamask for Firefox works fine.
The circle just keeps spinning...

I deactivated all other extentions. I use Ubuntu 16.04LTS and the newest version of testrpc.

**Comment by yuwiggin** [comment]
I had the same issue, MacOS , Chrome , testRPC v3.0.3,  metamask V3.9.1.

**Comment by VogtAI** [comment]
Does it work for you on the main ethereum network?

**Comment by Qkyrie** [comment]
Same problem here on both testrpc and Ropsten network.

**Comment by Zanibas** [comment]
These issues have been fixed in the latest pull requests--a new version is going out today that addresses most of these.

If they persist after the update, please re-open and let us know!
