### ISSUE TITLE
[Bug]: Token's image not show in main page

### ISSUE THREAD

**Issue by a3r0nz** [MetaMask/metamask-extension#18233]
### Describe the bug

I've followed this document: https://docs.metamask.io/guide/rpc-api.html#unrestricted-methods
but the image does not show on the main page, but in token show page shows correctly.

<img width="365" alt="Screen Shot 2566-03-19 at 09 50 37" src="https://user-images.githubusercontent.com/1370272/226150972-a24286b9-de60-4fa1-add4-97a3245dd4ee.png">

<img width="352" alt="Screen Shot 2566-03-19 at 09 50 55" src="https://user-images.githubusercontent.com/1370272/226150978-a8bbcbc1-b675-4d0b-a899-cdbba74e4b0b.png">

### Steps to reproduce

1. call wallet_watchAsset request

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sahar-fehri** [comment]
hey @a3r0nz ; i was not able to reproduce the issue; could you please send the params that you have tested with?
```
  address:
  symbol: 
  decimals: 
  image: 
```

PS: the image in the docs: https://foo.io/token-image.svg is a dead link in case you tried with that image 🙏
