### ISSUE TITLE
[Bug]: Metamask stuck after clicking confirm

### ISSUE THREAD

**Issue by AdamB2023** [MetaMask/metamask-extension#18234]
### Describe the bug

![image](https://user-images.githubusercontent.com/114318928/226342263-781acb54-0c7c-4866-8b0c-846e60cf85cb.png)

### Steps to reproduce

1. Confirm the transaction

### Version

10.26.1

### Build type

Chrome Web Store

### Browser

Chrome

### Operating system

Windows

### Additional context

The TX is confirmed, however the window stuck like this, need to close and reopen from extension.

**Comment by gregors** [comment]
seeing this in OSX as well

**Comment by seaona** [comment]
Thank you all for your comments and apologies for the inconvenience. This issue is fixed on the upcoming release `10.28.1`. You should be able to see it in the following days

**Comment by bschorchit** [comment]
Hey @AdamB2023 and @gregors, are you still experiencing this on versions 10.28.1 or 10.28.2?

**Comment by bschorchit** [comment]
Closing this for now as it seems to have been solved. Let us know if anyone comes across this issue again!

**Comment by Abbasjafri-syed** [comment]
@bschorchit look at this metamask is not popping up when try to conduct a txn else opening like when have to connect to a site
almost for every site

![image](https://github.com/MetaMask/metamask-extension/assets/101616115/7e64922c-106a-4a25-afc1-065b847b7121)

![image](https://github.com/MetaMask/metamask-extension/assets/101616115/bbeee1b9-5f75-4401-b623-e431a596cfc2)
