### ISSUE TITLE
[Bug]: PLEASE give the opportunity to set a nonce!

### ISSUE THREAD

**Issue by Ivan-dev-RED** [MetaMask/metamask-extension#18242]
### Describe the bug

Your ability to cancel or speed up transactions sometimes does not work correctly.
Our application can do this.
Since you are used by the majority, our users cannot cancel transactions through our app + your extension.

### Steps to reproduce

1.
sendTransaction

### Version

latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
duplicate of https://github.com/MetaMask/metamask-extension/issues/12907
