### ISSUE TITLE
[Bug]: zkEVM: Linea Goerli test network is displayed twice in the list of networks in settings

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#18277]
### Describe the bug

When show test networks is enabled for extension, we see the Linea Goerli test network is displayed twice in the list of networks in settings:

<img width="999" alt="Screenshot 2023-03-22 at 13 49 47" src="https://user-images.githubusercontent.com/105063779/226913060-837d2014-fafe-47bb-a982-28e2654814a2.png">

### Steps to reproduce

1. Login, enable show test networks. 
2. Go to settings, networks tab.
3. Check Linea Goerli test network is displayed twice in the list.

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
Merge conflict error, resolved in 403a8dbe38572d1c307644cd0d9699b070a6f156
