### ISSUE TITLE
[Bug]: signTypedData error when data's chainId is not added in the user's wallet

### ISSUE THREAD

**Issue by entrustgabri** [MetaMask/metamask-extension#18276]
### Describe the bug

When I send a eth_signTypedData_v4 request to a user which wallet doesn't have the chainId of the domain added in its wallet network list, the request's promise doesn't resolve (it doesn't finish in any error at all, which difficults the handleing). Everything is fine with other errors or when there are no errors and the message is displayed and can be signed by the user.

### Steps to reproduce

1. Open google chrome (Version 111.0.5563.110)
2. Have a Metamask wallet extension with only 1 account and 1 network (mainnet)
2. Execute some code that sends a eth_signTypedData_v4 with the data's domain chainId = 5 
3. Nothing happens, the metamask extension closes and no handler is executed, as if the promise hadn't resolved

Shouldn't the wallet resolve with a chainId not found (4902) error? 

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Additional context

The code I run:
```
 var params = [walletAddress, JSON.stringify(msgParams)];
    var method = "eth_signTypedData_v4";
    window.ethereum
      .request({
        method: method,
        params: params,
      })
      .then(onSigned, onError);
```
Both handlers have a console.log that can bee seen whit other types of error (like when I send a message to an account that has the goerli network but the current one is the mainnet) or when everything is fine and the message is displayed fine. 

I have also tried running the code on Brave and the same happend.

**Comment by vandan** [comment]
@entrustgabri we have some new eth_signTypedData_v4 usage docs that are soon to be released.
Please let us know if some of the [information here](https://metamask.github.io/mm-docs-v2/staging/wallet/how-to/sign-data#use-eth_signtypeddata_v4) helps resolve the issue you're seeing.

**Comment by vandan** [comment]
Looks like supplying a chainId that isn't in the wallet may not return the right error.
We should confirm that this issue is still reproducible @tmashuang

**Comment by tmashuang** [comment]
With the current version (11.2.0). if the `chainId` in the signature is mismatched with the selected network in MetaMask, it will result in the error with the provided reproduction.
![image](https://github.com/MetaMask/metamask-extension/assets/13376180/2ba0377a-ef46-4d49-9e4a-c5cfbc2207f7)
