### ISSUE TITLE
[Bug]: New spending cap max is max tokens held, not max tokens 

### ISSUE THREAD

**Issue by rileyg98** [MetaMask/metamask-extension#18295]
### Describe the bug

When approving a token for spend, the new spending cap defaults to a max of 0 when approving a token the wallet holds 0 tokens of. "Max" is generally understood by the community as to be the maximum number of tokens spendable, not the number held by the wallet. This results in a wasted approval if 0 tokens are approved because a user clicked max, assuming it would give the MAX_UINT256 approval. The "default" amount works as it is the requested approval amount by the dApp. 

### Steps to reproduce

1. Attempt to approve a token for spend which you hold zero tokens of

### Version

10.26.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by bschorchit** [comment]
That's an interesting feedback, thank you for sharing @rileyg98 !
