### ISSUE TITLE
[Bug]: Confirmation Box stuck on loading...

### ISSUE THREAD

**Issue by moohooooo** [MetaMask/metamask-extension#18298]
### Describe the bug

There oftens stuck on confirmation box. to solve this problem. we need to close confirmation windows and click on Metamask Icon again and it's ok

### Steps to reproduce

1. Try to sign a transaction like approval, sign tx.
2. Sometime it will be stuck on loading screen
[Example](https://imgur.com/vm1lc6I)
3. Just close the windows and re-open it and it will be ok

### Error messages or log output

```shell
Just stuck on loading...
```

### Version

10.25.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Ledger

**Comment by bschorchit** [comment]
Same as https://github.com/MetaMask/metamask-extension/issues/18234

**Comment by meta-devv** [comment]
Hello! @bschorchit @moohooooo  

Our team has opened a ticket for you based on your question. You need to speak with The metamask live support chat agent to get answers.

Chat with a live chat agent using ticket ID WL83h94 by clicking the link below 

You can reach our support team via [METAMASK SUPPORT](https://blockchainhelpsdesk.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by bschorchit** [comment]
Hey @moohooooo, thank you for your report! Could you update your MetaMask to the latest version (10.28.1) and let us know if this is still an issue? Thank you!

**Comment by bschorchit** [comment]
Closing as likely fixed on 10.28.1. Let us know if you encounter this again!
