### ISSUE TITLE
TransactionController is listening for network ID to change despite taking `onNetworkStateChange` option

### ISSUE THREAD

**Issue by mcmire** [MetaMask/metamask-extension#18291]
The name of the `onNetworkStateChange` option along with the way that it's used doesn't match what method is being used to listen to the network. Currently we configure TransactionController to listen for the network ID to change, and when this happens, it will refresh its state based on the current network. However, this is the only controller for which we use network ID to know when the network has changed; usually we either use the `networkDidChange` event or we listen for the whole NetworkController state to change. We should pick one of these that is more appropriate. We should probably also `onNetworkStateChange` if we are _not_ going to listen for the whole NetworkController state to change.

**Comment by MajorLift** [comment]
@shanejonas @mcmire Does https://github.com/MetaMask/core/pull/3643 partially or fully resolve this issue, now that `TransactionController` listens to `NetworkController:stateChange` via the messaging system?

**Comment by mcmire** [comment]
Yes, I think we can close this issue now.
