### ISSUE TITLE
NetworkController API normalization: Consolidate network controller stores

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#18303]
We currently use separate observable stores for different parts of the network controller state. As a step towards normalizing the API of this controller with the core network controller, we should consolidate this state into a single store.

This is part of [a larger effort to normalize the API of both network controllers](https://github.com/MetaMask/controllers/issues/971), to make them easier to merge.

### **Definition of Done**
- [ ] Whenever applies, any change unit tested, reviewed(approved) and documented(JSDOC at least)
- [ ]  We have changelog entries for any related changes
- [ ]  Any changed APIs have comprehensive inline documentation
- [ ]  Any changed public APIs are well covered by unit tests

**Other items**
- [ ]  If a planning/research ticket, then the plan has been reviewed and approved by at least 1 team members

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/metamask-extension/18303?planning-poker) with Zenhub @cryptodev-2s @mikesposito @Gudahtt
