### ISSUE TITLE
Migrate components to TS: ButtonIcon

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18327]
### Description
Migrate `ButtonIcon` component to TypeScript

### Technical Details
- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` follow [TS conventions](https://www.notion.so/Use-TypeScript-9ec7bd8fc8cf4d82b81cd8943c4707cd?pvs=4#7e6410b21100455a9a08442108f19d78)
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation 

### Acceptance Criteria
- Component has been converted to TypeScript

**Comment by xinnanyemm** [comment]
@georgewrmarshall please help to unblock this ticket. Thanks. cc @garrettbear

**Comment by georgewrmarshall** [comment]
@xinnanyemm @garrettbear I reviewed and suggested changes last night. Changes have been made. Approved
