### ISSUE TITLE
bid ok but didn't and cannot open 

### ISSUE THREAD

**Issue by nrhirsch** [MetaMask/metamask-extension#1832]
bid on domain, bid when thru but did not open auction.  clicked again on open auction and submitted thru metamask.  Metamask failed as it tried to do the same nonce as the bid nonce so it failed with nonce too low.  what to do?
Tried a few times.  got invalid transaction (red rectangle in lower right side of chrome screen).
expected it to open the auction in the first place when it took the bid:
https://etherscan.io/tx/0x565a0c60884cc7eae1c899d07ff1ba77ce6e4a5a051217e6acbec780eb68ae46
but it didn't.
SO: went into imToken on my iPhone and opened the auction successfully.  I'm good now but Metamask should have finished the job.
![screenshot 2017-07-26 15 47 23](https://user-images.githubusercontent.com/28511761/28641928-b302c736-721e-11e7-961f-15d616a7dafa.png)

------

**Comment by kumavis** [comment]
Thanks for the description

This should he resolved by the fixes made today, being published shortly

**Comment by comodoro** [comment]
Might I inquire in which version is this fixed? I encountered it recently in 3.9.6 and repeated the "Open auction" transaction several times because I did not notice the small red warning on Etherscan. Fortunately I use only 1 GWei gas because I am cheap;)

**Comment by comodoro** [comment]
It might be fixed in 3.9.7, because the same domain name that caused me problems in 3.9.6 went smoothly.

**Comment by tmashuang** [comment]
Closing old issue, will reopen if this is still an issue.
