### ISSUE TITLE
Add levenstein logic to blacklist

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1833]
@409H is having luck with a Levenstein distance check before blacklisting sites, allows blacklisting more combinations of sites.

Can refer to [his extension](https://github.com/409H/EtherAddressLookup) for implementation tips.

**Comment by 409H** [comment]
cc: @sogoiii - he did the implementation 🥇

**Comment by flyswatter** [comment]
If you published the logic to npm as a module we'd gladly pull from it.

**Comment by sogoiii** [comment]
@flyswatter  https://www.npmjs.com/package/fast-levenshtein here is one.

**Comment by sogoiii** [comment]
@flyswatter Ok, I added it myself. https://github.com/MetaMask/metamask-extension/pull/1836 just waiting to see if it passes auto tests.
