### ISSUE TITLE
[Bug]: Undefined amount when sending custom token

### ISSUE THREAD

**Issue by SoloMReal** [MetaMask/metamask-extension#18334]
### Describe the bug

When sending a custom token it shows as undefined sometimes but when you click on the history of what you send it still sends the correct amount. 

### Steps to reproduce

1. Add a custom token on the polygon network
2. send it

### Error messages or log output

```shell
none?
```

### Version

10.26.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
@SoloMReal can you share a screenshot to better illustrate the problem?

**Comment by bschorchit** [comment]
This could be related to https://github.com/MetaMask/metamask-extension/issues/17424

**Comment by wackerow** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/54227730/233760544-31182a71-4c1e-4e6d-8ddc-547203fa37f2.png">

+1, noticing the same. Using version `10.28.3` and getting this with DAI on Mainnet.

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/18334?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona
