### ISSUE TITLE
[Bug]: An internal JSON-RPC error occurred while calling the contract method.

### ISSUE THREAD

**Issue by pzxy** [MetaMask/metamask-extension#18345]
### Describe the bug

I am a developer for a blockchain and this is our address: https://github.com/telosprotocol/TOP-chain. Our chain is compatible with ETH. I am adding the revert function to the TOP chain using Remix and MetaMask tools. I have deployed the same contract on both TOP and Sepolia chains. The contract has a method that throws a revert(), which I intentionally did. When I call this method, it estimates the gas value, which means calling the eth_estimateGas interface. At this point, an error is returned, and an error message is displayed on Remix. The contract on TOP returns the following content:

{ "code": -32603, "message": "Internal JSON-RPC error.", "data": { "code": 3, "data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a6861732061616161612e00000000000000000000000000000000000000000000", "message": "execution reverted: has aaaaa." } }

However, the contract on Sepolia returns the following content:

{ "code": -32603, "message": "execution reverted: has aaaaa.", "data": { "originalError": { "code": 3, "data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a6861732061616161612e00000000000000000000000000000000000000000000", "message": "execution reverted: has aaaaa." } } }

I don't understand why an Internal JSON-RPC error occurs after TOP chain returns the information. I think MetaMask does something, but I am not sure.

It should be noted that the eth_estimateGas RPC interface can be returned normally. I think there may be other judgment conditions besides the eth_estimateGas interface, which eventually leads to the "Internal JSON-RPC error" error. However, I have not used JavaScript, so reading the source code is difficult and time-consuming. I want to know what reasons can cause the Internal JSON-RPC error error.

### Steps to reproduce

As long as a TOP chain is deployed and a revert occurs, this error can be reproduced. However, configuring an environment is difficult.

### Version

The current version is 10.23.2. I tried other versions from 2022, and the problem is the same.

### Build type

None

### Browser

Chrome, Microsoft Edge

### Operating system

Windows

### Additional context

TOP:
{"id":992710000,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x9e50ec94457a611a82288c92a5d4bc5ac1dfa8d5","to":"0x7ebdfab00a08235943dcb4f59f44898f492a238c","data":"0x2cc0e63e0000000000000000000000000000000000000000000000000000000000000002","value":"0x0"}]}
remix:
{
	"error": {
		"code": 3,
		"data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a6861732061616161612e00000000000000000000000000000000000000000000",
		"message": "execution reverted: has aaaaa."
	},
	"id": 992710000,
	"jsonrpc": "2.0"
}

ETH:
{"id":992683361,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x912ee24f30fd54e5b83bc181bb56a767b68ba086","to":"0xb39d598980d8fa5c545355d8fc5708115453f0a2","data":"0x2cc0e63e0000000000000000000000000000000000000000000000000000000000000002","value":"0x0"}]}
remix:
{
    "code": -32603,
    "message": "execution reverted: has aaaaa.",
    "data": {
        "originalError": {
            "code": 3,
            "data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a6861732061616161612e00000000000000000000000000000000000000000000",
            "message": "execution reverted: has aaaaa."
        }
    }
}

**Comment by pzxy** [comment]
If need more error information, email: wonkung@163.com

**Comment by BelfordZ** [comment]
Hey there @pzxy thank you for the issue!

Just to clarify: 
1. is this still an issue for you?
2. can you give me a bit more information on what specifically you were expecting vs what you received? Is the main problem that the error message is different across your chain vs. sepolia? 

Hope we can resolve this for you soon. Cheers
