### ISSUE TITLE
[Bug]: Improper parsing at "getCustomTxParamsData"

### ISSUE THREAD

**Issue by ne2030** [MetaMask/metamask-extension#18359]
### Describe the bug

I want to add custom extra data after the allocated length of transaction data. However, when I use Metamask to send the transaction, it throws an error message stating "Invalid token value; should be exactly 64 hex digits long (u256)".

Upon examining the code in the "getCustomTxParamsData" function, I found that it parses the transaction data using the String.prototype.split method to get the token value. Since my transaction data has extra data after the token value, it triggered an error during the validation check for the token value's length.

I also noticed that the transaction data is already parsed with the "parseStandardTokenTransactionData" function before the "split" logic is used. In my opinion, the "split" method should not be used to parse transaction data, and the already parsed data should be used for validation instead.

### Steps to reproduce

1. create allowance transaction data to ERC20 token (ex, USDT)
2. add extra data 
3. send transaction 

### Error messages or log output

```shell
Invalid token value; should be exactly 64 hex digits long (u256)
```

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gabspeck** [comment]
This error also began to happen last week or so when using the OpenSea seaport-js library to interact with the Seaport protocol, more specifically on the approval transaction to let Seaport handle ERC20 tokens on behalf of the user.
