### ISSUE TITLE
[Bug]: Collection name for ERC1155 displays incorrect value

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18362]
### Describe the bug

**Problem**: the collection name for ERC1155 is displaying an incorrect value (the name of the first NFT imported for that collection). We should display the collection name.

https://user-images.githubusercontent.com/54408225/228555134-6e5ae7b1-ceda-4764-82d8-d3a3f5793617.mp4

**Example**: on the [test dapp](https://metamask.github.io/test-dapp/), we are using the following contract with the collectio name `ERC1155`. This value should be expected as the Collection name for the NFTs we mint from the test-dapp

![image](https://user-images.githubusercontent.com/54408225/228553445-df18795a-a6d2-4536-b0ac-f1dbe3ff4bc5.png)

Here is what we see displayed on Opensea. The collection name here  is indeed `ERC1155` (screenshot provided by @PeterYinusa )

![image](https://user-images.githubusercontent.com/54408225/228557030-35d50838-38e1-44af-8845-3f520f572401.png)

### Steps to reproduce

1. Go to test dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Deploy ERC1155
4. Mint some NFTs
5. Import NFTs to MetaMask -- see collectio name takes the value of the first NFT that you imported (Rocks, Paper or Scissors)

### Version

10.26.2

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by darkwing** [comment]
I believe this is happening due to the information we're provided from the contract not being there (?) https://github.com/MetaMask/metamask-extension/blob/develop/ui/hooks/useNftsCollections.js#L44

**Comment by darkwing** [comment]
When we get a name via the API + autoimport, we are using it:
<img width="626" alt="contractname" src="https://user-images.githubusercontent.com/46655/228639515-c63d9ea5-3e17-4730-83a3-4676084322a8.png">

**Comment by darkwing** [comment]
The NFT contract data provided by the API when I mint from the test dapp is:

<img width="722" alt="NFTFromTestDapp" src="https://user-images.githubusercontent.com/46655/228644292-0aa27701-5433-411f-9070-9142f9eb54a8.png">

No name is provided and thus we use the name of the NFT.

**Comment by PeterYinusa** [comment]
Using the name of the NFT works in the case of an ERC721.
But an ERC1155 can represent multiple tokens, so we may end up showing the wrong name.
I'm not sure what the guidelines are here, just sharing my thoughts

**Comment by adonesky1** [comment]
Yeah so part of the problem here is that ERC1155s do not have a read function for `name`:
from [EIP1155](https://eips.ethereum.org/EIPS/eip-1155):
```
The name function (for human-readable asset names, on-chain) was removed from the standard to allow the Metadata JSON to be the definitive asset name and reduce duplication of data
```

So we need to read the collection name from the tokenURI and sometimes that data isn't available (because, for instance, it is hosted on IPFS and an IPFS gateway we're using is down)

**Comment by adonesky1** [comment]
So this creates a bit of a mismatch in our expectations because for 1155s the collection name lives in the JSON of the tokenURI where for 721s it lives as a getter `name()` function on the contract (at least for some 721s)

**Comment by adonesky1** [comment]
Basically we need to do some branching logic in the NFTController to get collection name differently based on the contract standard.
