### ISSUE TITLE
[Bug]: MetaMask extension window doesn't get triggered after clicking Connect Wallet until after a refresh

### ISSUE THREAD

**Issue by fmoyaj** [MetaMask/metamask-extension#18368]
### Describe the bug

MetaMask popup doesn't open after calling   ```ethereum.request({ method: 'eth_requestAccounts' })```
until after I refresh the page. Therefore, I can't connect to the dapp. Before refreshing, the ```request``` promise never resolves. After refreshing the page the ```request``` calls works as expected.

 This issue started happening after connecting and disconnecting to a dapp multiple times, and it seems to be domain/origin dependent. I access two different deployments of the same dapp with the exact same code at two different domains, one in development preview and the other one in production, and the ```request``` call doesn't resolve for the production deployment, which is the one that I have connected to hundreds of time for testing.

https://user-images.githubusercontent.com/60526175/228602788-118152dc-ec2d-4cb6-ad46-c0f8f0f9f268.mov

### Steps to reproduce

1. Open browser
2. Open any site
3. Run in console ```ethereum.request({ method: 'eth_requestAccounts' });```
4. See nothing happening (MetaMask should open modal with Unlock screen)

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

This bug is an issue for many users who have connected to a dapp through a specific domain several times. Related issues are described in #7221, #17339 , #17339 . Based on those issues, it seems like the bug cold be related to the extension's use of chrome's storage api to save dapp's origins/domains.

**Comment by danjm** [comment]
@fmoyaj can you reproduce this consistently? The repro steps you provided don't seem to result in the buggy behaviour. I guess the "connecting and disconnecting to a dapp multiple times" step is a part of the repro? If so, how many times do you have to do it to reproduce the bug?

And do you see any error messages in the developer console when this happens? Or just a pending/hanging request?

**Comment by fmoyaj** [comment]
Hey @danjm thanks for replying! "connecting and disconnecting to a dapp multiple times" is a part of the repro. I am a frontend developer and this behavior started occurring to me intermittently two months ago. I initially assumed that it might have been a problem with my extension, but it started occurring to other members of my team of regularly test our dapp in the last two weeks. I have connected/disconnected to the dapp approximately hundreds of times in the last few months. I don't see any error messages in the developer console when this happens, just a pending request. I set breakpoints in the execution of the dapp in the developer console and it seems like the execution of the promise never resolves because the function gets stuck executing  _runAllMiddleware, specifically postMessage.

I realized that this was an extension problem when I found that other users were experimenting the same issues with their MetaMask extensions and their dapps in similar circumstances. I am copying some of them below:

[ethereum.send never resolve when page is loaded on browser launch (chrome) · Issue #7221 · MetaMask/metamask-extension · GitHub](https://github.com/MetaMask/metamask-extension/issues/7221)

[Bug: Extension window doesn’t popup on request · Issue #13590 · MetaMask/metamask-extension · GitHub](https://github.com/MetaMask/metamask-extension/issues/13590)

[Bug: Metamask will not open Unlock modal after ‘eth_requestAccounts’ call · Issue #15105 · MetaMask/metamask-extension · GitHub](https://github.com/MetaMask/metamask-extension/issues/15105)

[Connecting to metamask after a fresh browser start · Issue #1474 · safe-global/web-core · GitHub](https://github.com/safe-global/web-core/issues/1474)

[Bug: eth_requestAccounts query returns nothing and shows no error · Issue #17339 · MetaMask/metamask-extension · GitHub](https://github.com/MetaMask/metamask-extension/issues/17339)

[Bug: Extension window doesn’t popup on request · Issue #13590 · MetaMask/metamask-extension · GitHub](https://github.com/MetaMask/metamask-extension/issues/13590)

**Comment by gmussi** [comment]
I am facing the same issue on several websites.

Metamask version: 10.33.1
Chrome version: Version 114.0.5735.199 (Official Build) (64-bit)
Windows 11 fully updated

**Comment by V-o-y-a-g-e-r00** [comment]
The problem is still relevant
Metamask version: 11.1.2
Chrome version: 118.0.5993.71
Windows 11 fully updated

**Comment by jiexi** [comment]
Hey there, @fmoyaj. Thank you for bringing this to our attention. Could you help us verify something by disabling preloading in your Chrome settings? This can achieved by:
1. Opening settings
2. Searching for "Preload"
3. Toggling the "Preload pages" setting to off

After you do this, are you still able to reproduce the bug you are seeing?

Thank you!
