### ISSUE TITLE
Add link to OpenSea's terms of service for the security provider feature

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#18374]
Replace `This service is experimental` under OpenSea (Beta) (see screenshot) with `This service is experimental. By enabling this feature, you agree to OpenSea's terms of use.` where terms of use is a link to http://opensea.io/securityproviderterms.

<img width="359" alt="Screenshot 2023-03-29 at 20 18 31" src="https://user-images.githubusercontent.com/34968356/228688993-6d5f69f6-a64f-47a3-9c09-423d55ede668.png">

**Comment by kevinghim** [comment]
Btw, http://opensea.io/securityproviderterms links to an NFT listing page called Manticore Games. @bschorchit
