### ISSUE TITLE
[Bug]: Token display error when using metamask

### ISSUE THREAD

**Issue by binhpham1510** [MetaMask/metamask-extension#18377]
### Describe the bug

When I open the metamask to see my polygon chain balance, I saw my matic token balance showing as ethereum token balance.

This is bug display ethereum: ![image](https://user-images.githubusercontent.com/129352682/228717574-dcf700ea-8ce7-43a2-b137-e4cd74f42a50.png)
And this is the real display as matic: 
![image](https://user-images.githubusercontent.com/129352682/228717676-87a1a2c8-8208-411f-b79f-76a8c4da97eb.png)

### Steps to reproduce

1. Sorry I have no idea to reproduce this display bug

### Version

10.27.0

### Build type

Beta

### Browser

Chrome

### Operating system

Windows

**Comment by sismato** [comment]
I had the same issue with ETH showing up as an amount for my Matic. Placed the issue with MetaMask support about the same time that the issue resolved. Don't know if they did anything or it resolved somehow itself.

**Comment by bergeron** [comment]
Here's an example.  When switching networks, the Matic balance is temporarily counted as ETH.  

https://github.com/MetaMask/metamask-extension/assets/3500406/afd5ed11-87ae-455b-bdf5-3581caee0eaf
