### ISSUE TITLE
[Bug]: 10.25.0 errors before login screen on Firefox 76.0.1 (yes I know it is old)

### ISSUE THREAD

**Issue by thebignaught** [MetaMask/metamask-extension#18387]
### Describe the bug

My firefox browser just updated automatically to 10.25.0 (I had opened it 1 day previous after a long hiatus and it did not update at that time from what I can tell; usually it exits out when I am trying to type in my password which I am guessing is it updating itself? This happened the second time). I have all my seeds so no issue there.

After opening the extension, it will show the loading fox head for a good 8-10 seconds before erroring with: Metamask had trouble starting, error could be intermittent etc etc.

Webconsole is giving a few errors: content security policies in script-src.js x3, 1 error coming from sentry-insall.js (involving ui-10 and runtime lavamoat), and a "No response from RPC" error in runtime-lavamoat.js.

Looking at the http requests to sentry.io fetch and beacon they all return an empty "{}" response.

I realize my browser is old (I dont use it for browsing, just metamasking). If a fix isnt possible I will just hop back to an older version. Is it possible the RPC is blocked by my network? (it is kind of a notorious subnet with a lot of ddos and spam crap coming from it). I have no idea if my version updated when I first opened it a day ago but it did indeed work then.

Thank you!

### Steps to reproduce

1. Have an old browser
2. ???
3. Don't profit

### Error messages or log output

```shell
Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src"). runtime-lavamoat.js:9042:14

Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src"). runtime-lavamoat.js:8322:29

Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src"). runtime-lavamoat.js:2669:4

Error@moz-extension://UUID/runtime-lavamoat.js:7522:17                sentry-install.js:76:13719
send/<@moz-extension://UUID/ui-10.js:1:258405
s@moz-extension://UUID/sentry-install.js:1:12302
    h moz-extension://UUID/sentry-install.js:76
    _ moz-extension://UUID/ui-10.js:26

Error: No response from RPC runtime-lavamoat.js:7522:17
```

### Version

10.25.0

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by DDDDDanica** [comment]
Hey @thebignaught thanks for reporting, i can reproduce it in even the latest version of firefox (111.01). The uninstall and install finally solve the issue when i try a few time. 
But in terms of the root cause, it could relate to https://github.com/MetaMask/metamask-extension/issues/18387. 
Can you try this fix for now also before we find the solution :
https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1012084136

Thanks !
