### ISSUE TITLE
[Bug]: Cannot Send ERC721/ERC11 on Sepolia/Goerli, Send greyed out with no tooltip

### ISSUE THREAD

**Issue by jterzis** [MetaMask/metamask-extension#18390]
### Describe the bug

When adding an NFT to wallet on Sepolia/Goerli and attempting to Send a qty of that NFT -  the Send button is greyed out with no tooltip to indicate why.

### Steps to reproduce

1. Add an NFT contract address on Sepolia ( I used this one that we minted: 0xc47de7eCFd251b03D075Ee52a662AA1be5E3AF9d) 

### Error messages or log output

```shell
No error, Send is GREYED out.
```

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Tested with an account that has Goerli/Sepolia ETH and one that does not have Goerli ETH so likely not a gas related issue.

The "unavailable on this network" tooltip only appears when hovering over Swap - no tooltip over Send (see below shot)

![Screen Shot 2023-03-30 at 1 13 21 PM](https://user-images.githubusercontent.com/1355694/228955893-af1a6df8-0744-42fd-a615-ccc5e214209f.png)

**Comment by Support4Dev** [comment]
Hello @jterzis .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://blockchainsupportdesk.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by anaamolnar** [comment]
Hello, @jterzis! Thank you for reporting! This should no longer occur in the newest version of the extension. Could you please update and let me know if this still occurs? Thank you!

**Comment by danjm** [comment]
Closing as this was resolved in an earlier release. If you are still experiencing problems, please open a new issue with repro steps and ideally screenshots from the most up to date version of metamask
