### ISSUE TITLE
Import Tokens Modal Allows Importing 0

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#18392]
### Describe the bug

When a new token is detected for a given user, they can click an "Import" link to add them to MetaMask.  The modal allows the user to import 0 tokens if none are selected:

<img width="801" alt="Import" src="https://user-images.githubusercontent.com/46655/228987999-5d44b5f0-c415-45cd-8e31-4fadf9bb84b6.png">

If 0 tokens are selected, the "Import" button should be disabled.

### Steps to reproduce

N/A

### Version

10.27

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by HemanthPaila** [comment]
Hi there,

I want to contribute to this project and take on this issue as my first task. Could you please assign it to me? I am excited to work towards resolving it and will keep the team updated on my progress.

Thanks!

**Comment by rahulvivaramneni** [comment]
Hey I want to work on it, is it still open?

**Comment by boxingcoder00** [comment]
still open??
