### ISSUE TITLE
Lost ETH to loading screen

### ISSUE THREAD

**Issue by Abohlund** [MetaMask/metamask-extension#1840]
I just tried to join the EOS ICO and used ur wallet to make the purchase.
I was doing an transaction when your wallet got stuck on a loading page.
I figured I should try rebooting ur program and when I did, my ETH was gone.
When I tried clicking the transaction replay, that page too never loaded.

Can you please help me retrieve my ETH or better yet, help me retrieve the public key I was generating at the EOS token distribution page.
![metamaskfailure](https://user-images.githubusercontent.com/30228939/28708147-764f2c2c-737b-11e7-9c75-4e670e044844.png)

**Comment by kumavis** [comment]
@Abohlund you closed the issue -- did you figure it out?

**Comment by Abohlund** [comment]
Hi,

yes it kinda resolved itself 😊

kind regards
Alexander

Den 28 juli 2017 18:17 skrev "kumavis" <notifications@github.com>:
