### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by surfinthetao** [MetaMask/metamask-extension#18406]
### Describe the bug

Edit: Even after fresh reinstall - but other extensions are floating as well, so it's not Metamask specific.

Windows 11. Chromium browsers Brave and Chrome, as well as Mozilla. Metamask appears to float on it's own disconnected. Also getting Metamask on top of itself, and white bars on edges of metamask. Happening on mutliple browsers. Maybe it's an accessibility setting with display. Not sure. Seemed to start last couple weeks. Primarily issue is happening on zk sync era when it's having difficulty, slow transactions happening. 

In addition, have to click on browser screen area inside website, then back on metamask to perform a button action within metmask. sometimes clicking inside website ( random area inside browser screen) then back on metamask, back  on screen again then metamask again will allow me to perform the button push inside metamask it appears ready to do. Maybe a memory issue with my system. Only happens on this system. Haven't tested others.

https://imgur.com/a/xHNoBm3   image of metamask spinning on top of , and apart from browser 
 
### Steps to reproduce

1. Make a swap on a variety of zk sync era websites or other things through memtamask like add liquidity etc. etc.

### Error messages or log output

```shell
10.27.0 brave
10.26.2 firefox
```

### Version

10.27.0 brave 10.26.2 firefox haven't reinstalled chrome yet

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome, Firefox, Brave

### Operating system

Windows

**Comment by Support4Dev** [comment]
Hello @surfinthetao .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://blockchainsupportsdesk.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by surfinthetao** [comment]
you tryin to scam me through github bro? lol

**Comment by Karlitos88** [comment]
Gracias no lo necesito pero le agradezco su interés por mi en particular será porqué no se complementa suya tiene que saber de los demas pues gracias preocuparse tanto y su humor negro pues tengo principios y valores de los que muchos carecen bueno me lo tomaré como mero hecho de se confundio si no pues podríamos tratar de solucionar tribunales mejor presentado pruebas  poder usted acusarme estafador

**Comment by mikedanjuma217** [comment]
Hello

**Comment by danjm** [comment]
@surfinthetao Are you still experiencing this problem?
