### ISSUE TITLE
[Bug]: Gas Limit value suggested from a Dapp is not respected, defaulting always to `21000`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18417]
### Describe the bug

**Problem**: when I start a transaction from a Dapp, if I've set a `gasLimit` value, I can see how it is not respected and it always defaults to `21000`.

This happens both to Legacy and EIP1159 transactions.

https://user-images.githubusercontent.com/54408225/229527219-f76a9035-32b1-4be2-b934-ad7293903056.mp4

### Steps to reproduce

1. Clone test dapp
2. Change line `865` and `882` `gasLimit` to another value (i.e. `0x5277` which is `21111`)
3. Start test dapp `yarn start`
4. Connect MM
5. Click Send Legacy // Send EIP1159
6. Click Edit Fees
7. Click Edit --- see how gasLimit is the same as always `21000`

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Possibly related with https://github.com/MetaMask/metamask-extension/issues/16593

And possibly caused by this: https://github.com/MetaMask/metamask-extension/pull/6625

**Comment by seaona** [comment]
this issue is still present

**Comment by bschorchit** [comment]
@seaona do you know if this (overriding the dapp proposed value for gas limit) also happens for other transaction types?

**Comment by bschorchit** [comment]
Potential solution: we should not use the dapp gas limit with it's below 21000, but use it if it's higher than that.
