### ISSUE TITLE
Metamask stuck loading after enterring password

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#1842]
While metamask seems to connect to the default ropsten node (red ropsten network showing up), 
I then click on metamask icon and I am asked to enter the password
Upon doing so (even if invalid password) Metamask show a loading wheel but never stop until I close it.
I thus cannot select any account

I tried setting a custom node but have same issue

I am on Windows 10 with chrome Version 59.0.3071.115 (Official Build) (64-bit)

I used a alternate chrome user , installed metamask and connected succefully. I locked and entered the password and on this profile it was a success.

**Comment by Zanibas** [comment]
Could you please paste the state logs here as well as any errors in the console? Thank you very much!

**Comment by wighawag** [comment]
hmm, unfortunately I did not save anything at that time but I think there were no error in the console

I cannot reproduce where I am now.

When the issue happen I was in a library and there might have been some network restriction but the thing was that it worked using an alternate chrome browser in the same environment

If I experienced it again, I ll save whatever I can do. How do we get state log ?

**Comment by kumavis** [comment]
state log export is now available in the top right drop down menu

**Comment by kumavis** [comment]
closing this until we have repro instructions as its a bit old now
