### ISSUE TITLE
[Bug]: Estimated Gas for Legacy txs coming from a dapp is not the same on the Edit screen than on the Send screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18420]
### Describe the bug

**Problem**: on Legacy transactions coming from the Dapp, they can suggest gas values and we see them displayed on the Send screen. The problem is that if we go to the Edit tx screen, we see a different gas estimation number, and if we go back to the Send screen we see the dapp gas values again.

The expected behaviour should be the same as we do with EIP1159 tx coming from a dapp, where if we go to Edit we see the same gas estimated as the Send screen. @bschorchit could you confirm?

https://user-images.githubusercontent.com/54408225/229530029-f5fe8b5c-7814-4c92-99e0-72d852b3f5d5.mp4

### Steps to reproduce

1. Go to test dapp
2. Click Send Legacy
3. Click Edit Gas
4. Check gas values
5. Now go to Edit tx
6. Check gas values -- see they are different from 4
7. Go to Send screen again
8. Check gas values -- see they are different from 6, and the same as 4

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I think with this https://github.com/MetaMask/metamask-extension/issues/17966 this won't be an issue anymore (as there will be no more gas info on the edit screen) - On a second thought, I'm not sure the edit screen if part of that scope actually but we can do a follow up if it's not for consistency across MM initiated and dapp proposed flows.
