### ISSUE TITLE
[Bug]: Estimated gas doesn't update if gas was suggested by dapp and user edits the transaction data

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#18436]
### Describe the bug

If a dapp sends a specific gas limit, we will use that (on any confirmation screen), but then if the user modifies the tx data , the estimate of required gas could change. This might result in failed transactions due to out of gas specifically with respect to approve transactions (because we don't let users edit tx data for confirmations proposed by dapps for other tx types).

We should recalculate gas limit estimates when approval amount is edited (whenever the users input a custom spending cap or go with `Max`). We likely only need to recalculate it once user lands in the second screen (where we display the gas info).

Relevant thread [here](https://consensys.slack.com/archives/GTQAGKY5V/p1680541523387319?thread_ts=1680214445.386919&cid=GTQAGKY5V) 

Update: we should also make sure we're updating our own estimations in this case as well (even if the dapp has not proposed custom gas parameters) - this might be what is happening here https://github.com/MetaMask/metamask-extension/issues/18341 ?

### Steps to reproduce

1.

### Version

10.27

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by jpuri** [comment]
@danjm , @bschorchit :

On approve flow we do not re-calculate the gas limit on change if amount to tokens, whether the limit is DAPP suggested or calculated by metamask.

Additionally I am not sure if the amount of token effect gas limit, gas limit depends on type of transaction as can be seen [here](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/index.js#L1080).
