### ISSUE TITLE
[Bug]: Linea test network not showing

### ISSUE THREAD

**Issue by miguelmota** [MetaMask/metamask-extension#18433]
### Describe the bug

Linea test network is not showing up

### Steps to reproduce

1. Go to network setings or search for linea network in settings
2. Observe linea test network is missing and clicking linea network in settings search does nothing
 
![DeepinScreenshot_select-area_20230403134703](https://user-images.githubusercontent.com/168240/229624078-aa7e50fa-e6cc-444e-8539-aaf49f6bf0df.png)

Using latest version
![DeepinScreenshot_select-area_20230403134936](https://user-images.githubusercontent.com/168240/229624465-87b0b956-e0aa-4220-aa3e-eca9c939a15f.png)

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
This is resolved since v10.33.0
