### ISSUE TITLE
MetaMask breaks bootstrap navbar drop downs in xWiki

### ISSUE THREAD

**Issue by Asimov4** [MetaMask/metamask-extension#1843]
*  Expected Behavior: I click on a navbar dropdown in xWiki and the dropdown appears.
  *  Actual Behavior: when the MetaMask extension is enabled, the dropdown does not appear. When it is disabled, the dropdown appears.
  *  Browser Used: Google Chrome
  *  Operating System Used: Windows 10

**Comment by tmashuang** [comment]
Closing. Will reopen if this is still an issue.
