### ISSUE TITLE
Refactor `ViewSnap` component to use `SnapController:disconnectOrigin` action

### ISSUE THREAD

**Issue by hmalik88** [MetaMask/metamask-extension#18451]
In order to reduce code duplication and for separation of concerns, https://github.com/MetaMask/snaps-monorepo/pull/1329 moved origin disconnect logic into the `SnapController`, these changes need to be incorporated into the extension.

**Comment by FrederikBolding** [comment]
@hmalik88 Perhaps this should wait until after the initial release? Refactoring will only add more code since `SnapController:disconnectOrigin` wont be available in the initial version of the stable release

**Comment by hmalik88** [comment]
Yeah sure, we can wait.

**Comment by kenhkan** [comment]
Putting back to the Product Backlog until we have the August v1 release

**Comment by FrederikBolding** [comment]
Not stale.
