### ISSUE TITLE
[Bug]: Periodical errors when using RPC gateways

### ISSUE THREAD

**Issue by andrew-webatix** [MetaMask/metamask-extension#18467]
### Describe the bug

In our application we are using [https://polygon-rpc.com](https://polygon-rpc.com) - RPC gateway that relies on globally distributed nodes. Sometimes that gateway switches from one node to another where the last block number is less than in previous node. If in this case we are trying to perform a call to some smart contract method (e.g. 'balanceOf' of the ERC20 token):

1. MetaMask will request the last block number from the first node (transparently of course) and get actual value;
2. Then RPC gateway may switch us to the different node with lesser height (last block number);
3. Which then lead to an error, as result of such a request will be '0x'. 

MetaMask itself do not treat '0x' as an error and successfully caches this value as a valid result of a call. We are using Ethers library in our application, which actually treat '0x' result as a BAD_DATA error. And this BAD_DATA can stay there for up to 20 seconds as MetaMask returns cached '0x' result all that time. Obviously our application stuck in such cases.

We suppose that more correct behavior of MetaMask in such situations is to treat '0x' response as an empty value error and perform several retries internally before throwing an actual error. In this case RPC gateway can get a chance to re-route following requests to more suitable node with correct height.

It looks like similar issues were faced already few years ago.. it was claimed to fix as a part of go-ethereum (that was related to Metamask), but have been returned after some major changes:

[Couldn't decode _____ from ABI: 0x](https://github.com/MetaMask/metamask-extension/issues/5588)
[Need to throw error when methods are called at future blocks](https://github.com/ethereum/go-ethereum/issues/18254)

Potentially this issue can be fixed with patches attached here: [patches.zip](https://github.com/MetaMask/metamask-extension/files/11160482/patches.zip)

### Steps to reproduce

Here is the test page which can reproduce the problem: [test.zip](https://github.com/MetaMask/metamask-extension/files/11160555/test.zip) It performs series of calls (3000 iterations, one per a second) to 'balanceOf' method of arbitrary ERC20 smart contract and address. In most cases it returns valid balance value. But from time to time an error messages can be noticed in DevTools / Console and this error stays there for about 20 seconds (cache lifetime?). Such an errors breaks our application. Test page can be started with use of a [simple static HTTP server](https://www.npmjs.com/package/http-server).
![errors-in-console](https://user-images.githubusercontent.com/41376915/230132798-31f907d0-4b69-4605-a244-ade36e3060b2.png)
![errors-result](https://user-images.githubusercontent.com/41376915/230132807-93d3aea9-ec54-484d-9ff4-80671b1a5b50.png)

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
@andrew-webatix Can you share the zip files in another form? For instance, could you post a github repo containing those files?

**Comment by andrew-webatix** [comment]
> @andrew-webatix Can you share the zip files in another form? For instance, could you post a github repo containing those files?

Sure. All files can be found here: https://github.com/andrew-webatix/metamask-issue-18467

**Comment by danjm** [comment]
thanks!
