### ISSUE TITLE
Fix changelog on the release page

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#18468]
<img width="1386" alt="Screenshot 2023-04-05 at 16 50 29" src="https://user-images.githubusercontent.com/13814744/230135072-773e96de-30e7-491f-b2e7-ed98d0445f9e.png">

For [10.28.1](https://github.com/MetaMask/metamask-extension/releases/tag/v10.28.1), the release page does not include the changelog.

The changelog should be included as in previous releases such as [10.27.0](https://github.com/MetaMask/metamask-extension/releases/tag/v10.27.0).

**Comment by Narcos101** [comment]
**Visible for me** 

![image](https://github.com/MetaMask/metamask-extension/assets/70684116/5624b8a9-77ff-49fb-87e7-65b7fa57843c)
