### ISSUE TITLE
[Bug]: Cannot close Toast Notification for NFT Added 

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18485]
### Describe the bug

**Problem**: after adding an NFT, I cannot close the Toast Notification by clicking on the cross sign.

https://user-images.githubusercontent.com/54408225/230401789-c0486a50-ec79-43af-b45f-b856be0bdd83.mp4

### Steps to reproduce

1. Import an NFT
2. See the toast notification of NFT imported successfully
3. Click the cross for closing it -- nothing happens

### Version

10.28.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by dswilson4** [comment]
@seaona I looked into the issue and the fix seemed quick: https://github.com/MetaMask/metamask-extension/pull/18504
