### ISSUE TITLE
Update knobs to controls in storybook: SnapsUIRenderer

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18497]
### Description
Currently there are a few storybook stories still using knobs in our storybook files `*.stories.js`. knobs have been deprecated in favour of controls. It would be great to migrate these last stories from knobs to controls.

This issue is to migrate the `ui/components/app/flask/snap-ui-renderer/snap-ui-renderer.stories.js` from knobs to controls

<img width="1440" alt="Screenshot 2023-04-06 at 4 32 07 PM" src="https://user-images.githubusercontent.com/8112138/230512158-73e3079e-e691-42ad-b00c-27a1988b672e.png">

### Requirements
If you would like to take on this issue please comment but before asking to take on this issue there are a few requirements that will help complete this task:
- Get storybook up and running `yarn storybook`
- Some knowledge of storybook is not required but would be beneficial for this task. [storybook docs here](https://storybook.js.org/)

### Technical Details
- Migrate knobs to controls

### Acceptance Criteria
- knobs have been migrated to controls for listed story
- Take Before / After screenshots of the knobs and new controls and attach to the PR
- Tag @georgewrmarshall, @garrettbear, or @NidhiKJha in the PR to review

**Comment by dswilson4** [comment]
@georgewrmarshall I'm interested in taking on this issue

**Comment by georgewrmarshall** [comment]
Hey @dswilson4, appreciate it! I've assigned you the issue. Looking forward to your PR

**Comment by NidhiKJha** [comment]
Closing this as https://github.com/MetaMask/metamask-extension/pull/18502 is merged
