### ISSUE TITLE
[Bug]: wallet_switchEthereumChain no longer working after update to 10.28.2 Chrome

### ISSUE THREAD

**Issue by tklindt** [MetaMask/metamask-extension#18509]
### Describe the bug

After the release of `10.28.2` `wallet_switchEthereumChain` is no longer working. Error in console is `{code: -32603, message: 'networkConfigurationId undefined does not match a configured networkConfiguration', data: {…}}`. `10.28.1` has an issue where user has to approve the function twice. Downgrading to `10.26.1` allowed the `wallet_switchEthereumChain` to function. (Did not try versions between 10.26.1 and 10.28.1) It appears that the issue only happens when switching to a chain other than Ethereum but can not confirm 100%

### Steps to reproduce

1. Ensure that extension version `10.28.2` is installed in Chrome Desktop. 
2. Visit a site which utilizes `wallet_switchEthereumChain`, trade.coinbook.app is an example.
3. Utilize Network dropdown on DAPP to select a chain to switch to. Metamask will open with correct chain swicth prompt. Error is logged after clicking Approve. 
4. Depending on DAPP configuration there may be a catch that calls `wallet_addEthereumChain` on error. 

### Error messages or log output

```shell
{code: -32603, message: 'networkConfigurationId undefined does not match a configured networkConfiguration', data: {…}}
```

### Version

10.28.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by simonmahns** [comment]
bump, this was an issue before version 10.28.2 that #18483 aimed to fix but did not successfully do so

**Comment by 0xnakato** [comment]
same here

**Comment by simonzg** [comment]
same issue identified both on MacOS and Windows

**Comment by sjunaiduk** [comment]
Metamask v10.28.2 on Chrome has created this bug. Hopefully a fix soon.

**Comment by qqqzhch** [comment]
Metamask v10.28.2 on Chrome  on MacOS Hopefully a fix soon.

**Comment by scotthconner** [comment]
Also running into this. It's broken existing dapp deployments as well?

**Comment by danjm** [comment]
If you are experiencing this, you can switch networks within MetaMask. Of course, we want to fix this properly so that you don't have to do that.

I am trying to understand the problem. Can someone who is experiencing this try the following:

1. Open MetaMask
2. Make sure you are on a network other than the one you are trying to switch to
3. Open the network dropdown and delete the network you are trying to switch to by clicking the "X" next to the network.
4. Go back to the dapp and refresh the page
5. Click whatever button prompts you to connect to the network. It should prompt you to add the network.
6. Confirm the addition of the network but DO NOT confirm switching to the network if you are shown that immediately, and click "Cancel" on the switch network prompt.
7. In the dapp, click the button that will again cause the switch network prompt. This time, confirm the switching of the network.

If someone can try that and report the results, it can help with the investigation of this bug.

Also, if someone can share any dapps where they are experiencing this bug, it can help with the investigation.

**Comment by 0xnakato** [comment]
> If you are experiencing this, you can switch networks within MetaMask. Of course, we want to fix this properly so that you don't have to do that.
> 
> I am trying to understand the problem. Can someone who is experiencing this try the following:
> 
> 1. Open MetaMask
> 2. Make sure you are on a network other than the one you are trying to switch to
> 3. Open the network dropdown and delete the network you are trying to switch to by clicking the "X" next to the network.
> 4. Go back to the dapp and refresh the page
> 5. Click whatever button prompts you to connect to the network. It should prompt you to add the network.
> 6. Confirm the addition of the network but DO NOT confirm switching to the network if you are shown that immediately, and click "Cancel" on the switch network prompt.
> 7. In the dapp, click the button that will again cause the switch network prompt. This time, confirm the switching of the network.
> 
> If someone can try that and report the results, it can help with the investigation of this bug.
> 
> Also, if someone can share any dapps where they are experiencing this bug, it can help with the investigation.

@danjm I can't even delete the network in step 3, the network is still there after confirming the deletion. Could it be a new issue?

Btw you can try our dapp experiencing the issue https://syncswap.xyz/

**Comment by danjm** [comment]
@0xnakato Ah, I see, you are right.

Well I understand the problem now and am working on a fix.

This bug will be experienced by anyone who added a network while on v10.27.0 or earlier, and are now on v10.28.1 or v10.28.2 and trying to confirm a dapp prompted switch to that network. This bug will not affect users who first added the network, via a dapp `wallet_addEthereumChain` request, while on v10.28.1 . This bug also won't affect users who added the network via the MetaMask UI in v10.28.1

The simplest work around is to open MetaMask and use the network switcher. But you will have to do that every time a dapp prompts you to switch to that network.

If you want to permanently fix the issue for a given network, you can open MetaMask, then open "Settings", then select the "Network" tab of settings and edit any field in any way. Save the change in the network form. Switching to this network from  dapp (or deleting it) will succeed. I have demo's this workaround in the attached video, which first shows the failure to switch and then shows the successful network switch after editing the rpc url in the network form by adding a trailing `/`

https://user-images.githubusercontent.com/7499938/230705576-177c2927-e3d7-4959-a211-d767953467a6.mp4

**Comment by 0xnakato** [comment]
@danjm Awesome! Thank you for the investigation, details and instructions! Really appreciate it and looking forward to the fix!

**Comment by mykcryptodev** [comment]
thank you @danjm I think your explanation probably saved me hours of fumbling this weekend <3

**Comment by RodeRickIsWatching** [comment]
Facing the same problem, and temporarily fixed by removing and readd the network. BTW will u fix it in this version? I think it may be a liitle complex for common users to understand why they need to remove and readd the network, and also how to do it. Thanks!

**Comment by mhmmdhajizade** [comment]
@danjm Thank you for explanation. This solution fixed the problem but is there any chance that this problem fix in next versions of metamask? It is gonna be big problem for apps that using metamask for connect wallet.

**Comment by Jason2d2** [comment]
This is still causing issues since 10.28.1. 
Have you tried switching to a custom network, Ganache? I am able to switch via dapp to a common network, like Sepola, but unable to switch to Localhost http://127.0.0.1:8545, chain id 1337.

**Comment by bifot** [comment]
same for me, and also on uniswap too

**Comment by Bot80926** [comment]
can't delete network successfully.  the only way to switch network is open metaMask and use network switcher :(

> @0xnakato Ah, I see, you are right.
> 
> Well I understand the problem now and am working on a fix.
> 
> This bug will be experienced by anyone who added a network while on v10.27.0 or earlier, and are now on v10.28.1 or v10.28.2 and trying to confirm a dapp prompted switch to that network. This bug will not affect users who first added the network, via a dapp `wallet_addEthereumChain` request, while on v10.28.1 . This bug also won't affect users who added the network via the MetaMask UI in v10.28.1
> 
> The simplest work around is to open MetaMask and use the network switcher. But you will have to do that every time a dapp prompts you to switch to that network.
> 
> If you want to permanently fix the issue for a given network, you can open MetaMask, then open "Settings", then select the "Network" tab of settings and edit any field in any way. Save the change in the network form. Switching to this network from dapp (or deleting it) will succeed. I have demo's this workaround in the attached video, which first shows the failure to switch and then shows the successful network switch after editing the rpc url in the network form by adding a trailing `/`

**Comment by iseekTo** [comment]
> 

@Bot80926  Yes, you are right, this is really a bad experience :(  

hope Metamask can fix it :)

**Comment by Holybasil** [comment]
waiting for a fix

**Comment by xl2412** [comment]
same for me, waiting for a fix

**Comment by zenland-dao** [comment]
Worked fine with Metamask Version 10.28.2 and Chrome Version 111.0.5563.65. Decided to update Chrome to 112.0.5615.50 - network switch stopped working. Tested on Zenland App

**Comment by luneShaoGM** [comment]
same for me

**Comment by egorbond31** [comment]
same, waiting for fix 🙏

**Comment by kuilaurence** [comment]
First remove the previously added network, then re-add it, and the network switching works again. It is speculated that this is related to a Chrome update.

**Comment by Sotatek-DungTran2** [comment]
Hi all with this issues , I solved with change method call wallet **_switchEthereumChain** to **wallet_addEthereumChain**.
And in config wallet_addEthereumChain you change property rpcUrls : ['rpc_url/']
Summary The metamask document recommend use wallet_addEthereumChain for switch network and with method wallet_addEthereumChain you can config all for network ( name , chainID , rpc )

**Comment by nmikhaylovskiy** [comment]
Hi 
I have same problem 

Wait for fix

**Comment by livingrockrises** [comment]
waiting for a fix

**Comment by LevanOzashvili** [comment]
same issue on multiple dapps. 
waiting for a fix.

**Comment by NicolasCastroGarcia** [comment]
Same issue here, waiting for a fix!

**Comment by Rcontre360** [comment]
Same here, waiting for a fix!

**Comment by paro-paro** [comment]
many dapps are broken! waiting for a fix!

**Comment by ablevargheseme** [comment]
waiting for a fix

**Comment by s0wcy** [comment]
Same issue, works when deleting the manually added network and using auto import.
Not UX friendly at all for our customers...

**Comment by daedboi** [comment]
Same issue here, this is delaying a new bridge integration into our dapp due to bad UX.

**Comment by petermazzocco** [comment]
I believe I'm experiencing the same issue as well, but I am fairly new to dApp development (1 year now).

I am trying to set up my connectWallet function for my dApp and am requiring users to switch to Mumbai (for now), the wallet pops up to switch but then throws the error:

`networkConfigurationId undefined does not match a configured networkConfiguration`

Hope it's just a small bug and you guys can get it figurd out :)

**Comment by timothycarambat** [comment]
Founder of [Mintplex](https://mintplex.xyz) here. We support 7 blockchains through our launchpad. This bug seems limited to only non-native metamask chains.

`wallet_switchEthereumChain` **does** work for any chains pre-loaded into metamask (Etherum, Goerli, Sepolia, Local) but any chains that are added after a clean install (Polygon, Optimism, BNB, etc etc) will not respond to `wallet_switchEthereumChain` anymore - has been the case since ~April 7th it appears.

**Comment by timothycarambat** [comment]
Was able to fix this by removing _all_ non-native networks from my current install of MetaMask and re-adding them by any means (chainlist, dAPP, explorer page), and now the wallet command work.

**Comment by danjm** [comment]
Thanks everyone for your input on this. We are going to try to have a fix published this week, hopefully within a day or two (but exact timelines can't be guaranteed).

See my previous comment for some notes on workarounds from a users perspective.

For dapp developers trying to avoid their users having to follow a workaround, you may find this approach mentioned above helpful https://github.com/MetaMask/metamask-extension/issues/18509#issuecomment-1501607666

**Comment by Jason2d2** [comment]
> Founder of [Mintplex](https://mintplex.xyz) here. We support 7 blockchains through our launchpad. This bug seems limited to only non-native metamask chains.
> 
> `wallet_switchEthereumChain` **does** work for any chains pre-loaded into metamask (Etherum, Goerli, Sepolia, Local) but any chains that have been added to wallet prior to ~April 7, 2023 (Polygon, Optimism, BNB, etc etc) will not respond to `wallet_switchEthereumChain` anymore.
> 
> This also is the case for `wallet_addEthereumChain` actions

Local 1337 does not work for me. I can use metamask to switch, but cannot call wallet_switchethereumchain.

**Comment by thelastinuit** [comment]
I have the same issue but only on Brave. Firefox and Chromes work just fine.

**Comment by HappySean2845** [comment]
Same issue here

**Comment by Davidonelove** [comment]
My own is showing me cloud error

**Comment by NBMSacha** [comment]
Same here.

**Comment by ugurcanomur** [comment]
same

**Comment by tklindt** [comment]
Thank you @danjm!

**Comment by simonmahns** [comment]
@danjm! beast!

**Comment by happy-cutman** [comment]
Chrome version 112.0.5615.50 issue is still here

**Comment by fachryadhitya** [comment]
> Chrome version 112.0.5615.50 issue is still here

same :(, did you find the fix?

**Comment by soumayaerradi** [comment]
Same issue here

<img width="836" alt="Screenshot 2023-04-12 at 09 48 37" src="https://user-images.githubusercontent.com/56691815/231393783-6e074af0-201e-477b-82e4-eb42db574c5b.png">

**Comment by sk-enya** [comment]
Facing same issue, waiting for fix to publish.

**Comment by tklindt** [comment]
I just manually installed 10.28.3 and all looks good now. The latest release is not available in Chrome Web Store quite yet, please wait for it to be released and currently installed extensions to be updated and then everything should work as expected.

**Comment by petermazzocco** [comment]
Seems to be working for me now. I followed a couple of the steps above:

1. Removed a network I was trying to force a switch over to.
2. My `connectWallet` function would manually add the network by running the `wallet_addEthereumChain` method. 
3. Now I can open up my dApp with a different chain, click Connect Wallet and it will ask to change to the proper chain and it works without error.

I am running version 10.28.2 btw.

**Comment by 3commascapital** [comment]
still seeing this. running 10.28.2 as well

**Comment by cawfree** [comment]
@petermazzocco Nice find! Though possibly a little complicated for average users to follow.

**Comment by danjm** [comment]
Thanks everyone for your patience. The fix for this has now been rolled out to all chrome/brave users v10.28.3

**Comment by jgomes79** [comment]
Me too.
Still getting this error: networkConfigurationId undefined does not match a configured networkConfiguration
Metamask 10.28.3

**Comment by ArthurGerbelot** [comment]
Ping! Still have the issue with 10.28.3 too !

**Comment by cnaize** [comment]
The same issue
```
Mac M1
macOS 13.3.1
Google Chrome 112.0.5615.137
MetaMask 10.28.3
```

**Comment by james-carr-siftware** [comment]
Still an issue

```
MetaMask 10.28.3
Chrome 112.0.5615.165
Ubuntu 22.04
```

**Comment by sgraphics** [comment]
Apparently its due to specifying capital casing for network id when calling wallet_switchEthereumChain. So instead of 0xAA36A7, use 0xaa36a7 for Sepolia.

This is definitely still a bug as many online documents explicitly advise to use the capital case version (e.g. https://docs.alchemy.com/docs/how-to-set-up-the-metamask-sdk). Also online dec-to-hex converters (such as https://www.rapidtables.com/convert/number/decimal-to-hex.html) report CAPITAL case versions for the conversion.

**Comment by sgraphics** [comment]
Apparently there is a fix: https://github.com/MetaMask/metamask-extension/commit/0ea765ebf6771cd70a922d74e68bbca56b31d1f7

**Comment by lxl8888** [comment]
> @0xnakato Ah, I see, you are right.
> 
> Well I understand the problem now and am working on a fix.
> 
> This bug will be experienced by anyone who added a network while on v10.27.0 or earlier, and are now on v10.28.1 or v10.28.2 and trying to confirm a dapp prompted switch to that network. This bug will not affect users who first added the network, via a dapp `wallet_addEthereumChain` request, while on v10.28.1 . This bug also won't affect users who added the network via the MetaMask UI in v10.28.1
> 
> The simplest work around is to open MetaMask and use the network switcher. But you will have to do that every time a dapp prompts you to switch to that network.
> 
> If you want to permanently fix the issue for a given network, you can open MetaMask, then open "Settings", then select the "Network" tab of settings and edit any field in any way. Save the change in the network form. Switching to this network from dapp (or deleting it) will succeed. I have demo's this workaround in the attached video, which first shows the failure to switch and then shows the successful network switch after editing the rpc url in the network form by adding a trailing `/`
> 
>  switchnetwork-workaround.mp4

I also encountered this problem on the metamask app version 7.17.0, and the two versions of the same two mobile phones, one is normal, the other will report this error  {code: -32603, message: 'networkConfigurationId undefined does not match a configured networkConfiguration', data: {…}} ！Looking forward to answer！

**Comment by KBPsystem777** [comment]
Looks like this is an issue when there are wallet that are also installed as an extension other than Metamask see -- https://stackoverflow.com/a/77457807
