### ISSUE TITLE
[Bug]: Chrome setApprovalForAll function fails in Metamask for some collections

### ISSUE THREAD

**Issue by defikintaro** [MetaMask/metamask-extension#18507]
### Describe the bug

In the recent chrome, I'm seeing the following error while calling the approval for all method. In mobile metamask, firefox and brave browser I'm not seeing this error.

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/84995585/230581537-abe4ad06-f60b-4b51-8705-5a9730af1564.png">

### Steps to reproduce

1. Open this particular collection in Avalanche https://opensea.io/assets/avalanche/0xbd7bd0b4650d324e3ea6f734faa3fc37d80b7d82/15221/sell
2. Try to give approval for the collection to be used by OpenSea contracts
3. Get the error

### Error messages or log output

```shell
MetaMask encountered an error
Try again by reloading the page, or contact support here.
Error details
Message: Invalid data; should be 'approve' method, but instead is 'setApprovalForAll'

Code: Error

Stack:
Error: Invalid data; should be 'approve' method, but instead is 'setApprovalForAll'
  at n.getCustomTxParamsData (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:255268)
  at j (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-9.js:1:255177)
  at ha (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:60036)
  at Cu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:104794)
  at Tl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90710)
  at gl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90635)
  at fl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:87983)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46441
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:417870)
  at $o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46150)
  at Zo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46386)
  at Jo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46321)
  at al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:84772)
  at Ra (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:63693)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:166749
```

### Version

10.27.0

### Build type

None

### Browser

Chrome Version 112.0.5615.49 (Official Build) (arm64)

### Operating system

Linux

### Additional context

Also it's working windows Chrome 111.0.5563.147 (Official Build) (64 bit) - Metamask 10.25.0

--EDIT--
metamask console errors:

WARNING: Missing strong random number source
runtime-lavamoat.js:11626 missing dep: @metamask/eth-token-tracker>ethjs>bn.js requested buffer
getRelativeModuleId @ runtime-lavamoat.js:11626
runtime-lavamoat.js:10628 failed to load decimals for token at 0xBD7bd0B4650D324e3eA6f734fAA3FC37d80b7D82
warn @ runtime-lavamoat.js:10628
sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7:1     Failed to load resource: the server responded with a status of 429 (Too Many Requests)
2runtime-lavamoat.js:7100 SES_UNHANDLED_REJECTION: BigNumber Error: new BigNumber() not a number: undefined
  at ee (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:99:72467)
  at E (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:99:77947)
  at new X (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:99:70369)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:3:260581)
  at n.getAssetDetails (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:86320)
  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:126149
handleRejection @ runtime-lavamoat.js:7100
sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7:1     Failed to load resource: the server responded with a status of 429 (Too Many Requests)

<img width="823" alt="Screenshot 2023-04-07 at 18 18 16" src="https://user-images.githubusercontent.com/84995585/230633794-e2d58170-9c68-401a-961c-13eab2ad5908.png">

**Comment by defikintaro** [comment]
It turns out a new feature makes new bugs for old people :) 
For other people who's like us may find this helpful, because of we added our NFT symbol to our Metamasks as an Asset with decimal 0, in the new versions of Metamask they're being treated as ERC20's. So if you remove them then add as NFTs with tokenId to your wallet it will solve the problem.
![image](https://user-images.githubusercontent.com/84995585/230678324-de9abd03-8914-4431-8005-3fd51db9eab3.png)

**Comment by michaelyu300** [comment]
Hello bro i have this issue how did u solve it without removing metmask?

**Comment by mvillere** [comment]
> )

Go to the Assets tab on the main page of Metamask, find the NFT listed under assets, click on it and it will ask if you want to remove it and move it to the NFT tab. Say yes.

The problem is you need to know the Token ID of at least one NFT you own from the collection, or else metamask will undo the removal. But, if you enter a Token ID that you own on the next screen and click ok, it will move that Asset over to the NFT tab, and then you will be able to buy or sell the NFT again w/o the error.

**Comment by michaelyu300** [comment]
fixed it by changing network weird.

**Comment by loupiote** [comment]
fixed it by doing this:

"Go to the Assets tab on the main page of Metamask, find the NFT listed under assets, click on it and it will ask if you want to remove it and move it to the NFT tab. Say yes."

I think MetaMask should offer to do that automatically when this situation is detected.

**Comment by Amesiak** [comment]
Hey all!
So I have a problem described above and solution presented here sounds reasonable, thanks for that.

Can anyone give me a hint how can I go to the Assets Tab when the error above doesn't allow me to do anything:
![image](https://github.com/MetaMask/metamask-extension/assets/6991351/973b2b83-5f68-488c-9c35-5a9c54843e21)

Thanks in advance,
Mike

**Comment by Amesiak** [comment]
Ok, I managed to overcome this issue, leaving it here might be helpful for anyone.
I just chose a page that uses another blockchain connection than one in which on error was caused. Then I was able to switch the network back to the one bugged and do the instruction above. Thank you!

**Comment by adamcsdances** [comment]
> Ok, I managed to overcome this issue, leaving it here might be helpful for anyone. I just chose a page that uses another blockchain connection than one in which on error was caused. Then I was able to switch the network back to the one bugged and do the instruction above. Thank you!

Hello Amesiak,  can you please help me out with a little more detail. Total nub here.  How do you "chose a page that uses another bockchain connection"?  
I opened a new tab then clicked my MM extension with no success.

**Comment by mvillere** [comment]
@

> > Ok, I managed to overcome this issue, leaving it here might be helpful for anyone. I just chose a page that uses another blockchain connection than one in which on error was caused. Then I was able to switch the network back to the one bugged and do the instruction above. Thank you!
> 
> Hello Amesiak, can you please help me out with a little more detail. Total nub here. How do you "chose a page that uses another bockchain connection"? I opened a new tab then clicked my MM extension with no success.

I think the suggestion is to go to a different website that has the network switch call embedded in it. This will typically happen on a polygon or base or optimism website.  An example is the sandbox collection on Opensea: https://opensea.io/collection/sandbox   If you click on any of those nfts, and click buy, it will trigger the network switcher. Just reject the transaction after it switches networks over.    They have some weird moonpay popup on there now, just ignore that.

I have not tested to see if this actually circumvents the error message, I can't reproduce the error on my instance of metamask anymore, so I dont know.

**Comment by Super-Genius** [comment]
This is very bad and shouldn't error out on hybrid EIP-2535 contracts that contain both ERC-20 AND ERC-1155 tokens, why are you even checking this and flagging it as an error?  I have to hide the ERC-20 token in order for it to work

**Comment by togamamora** [comment]
I am still having this issue today. Tried many times but failed. However, I can see that many people are able to list the same collection. But I cannot figure a way.

![image](https://github.com/MetaMask/metamask-extension/assets/37278708/86545e2e-10e9-4795-bf54-67a9cecef5b0)

Another user said that he could list the token after switching to rainbow wallet. Will Metamask have a fix since I do not like to have many extensions on my browser?

**Comment by Fast288** [comment]
i still have this issue, how can i solve it?

**Comment by Fast288** [comment]
hi, i still have this issue with forge token. ca: 0x73576a927cd93a578a9dfd61c75671d97c779da7
Can't list it on opensea.

**Comment by SmartLayer** [comment]
> hi, i still have this issue with forge token. ca: 0x73576a927cd93a578a9dfd61c75671d97c779da7 Can't list it on opensea.

@Fast288 I am curious if this issue exists for all ERC404 tokens or just yours. Do you happen to have a Pandora token by any chance to test listing it on opensea? Has anyone have this problems with other ERC404 tokens?

**Comment by Fast288** [comment]
Hi, i dont have any pandora to test.

**Comment by Fast288** [comment]
Easy solve:
i integrated my wallet into phantom wallet. it works now.

Bug is clearly in metamask.

**Comment by chiunhau** [comment]
Attempting to `setApprovalForAll` to any ERC404 tokens can reproduce this issue.

**Comment by StephenFiser** [comment]
Metamask is trying to be too clever here.

If we call a function on the front-end of a dapp, Metamask should not trigger an error if that function exists in the ABI. Makes no sense.

**Comment by bergeron** [comment]
Try the fix rolling out in MetaMask extension version 11.13.0 and report back any token addresses/IDs that still have issues

**Comment by Sweettea1987** [comment]
Hi i have this error and i solved by changing (security and privacy settings)  on metamask   , I'm not sure what exactly part , but i believe is  on section Network providers

**Comment by Sweettea1987** [comment]
Network details check, IPFS gateway, Show ENS domains in address bar has to be ON and also  Token autodetection
 
Autodetect tokens ON
Batch account ON . I hope its help to anyone
