### ISSUE TITLE
[Bug]: 10.27.0 LavaMoat scuttling prevents access to global on Firefox 76.0.1 console to manually retrieve keys/seeds

### ISSUE THREAD

**Issue by thebignaught** [MetaMask/metamask-extension#18505]
### Describe the bug

Following the instructions here for Firefox:
https://support.metamask.io/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data

Error is thrown in console:
`Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.`

It worked in 10.25.0. I realize this is not necessarily a bug but information would be needed if it is currently disableable as a safety option for users wallets.

Regards

### Steps to reproduce

As above

### Error messages or log output

```shell
As above
```

### Version

10.27.0

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by danjm** [comment]
@thebignaught firefox versions below 78 are no longer supported as of MetaMask v10.26.0

If you need to use a version of firefox below v78, you will have to manually install an older version. For security reasons, it is highly recommended that you use the most up to date browser versions
