### ISSUE TITLE
[Bug]: Support for Solidity custom error is broken

### ISSUE THREAD

**Issue by 0xnakato** [MetaMask/metamask-extension#18510]
### Describe the bug

After the recent upgrade, the support for Solidity custom error is broken. Previously, it could return the function selector of the custom error that caused the transaction to be reverted when estimating gas/submitting the transaction.

Currently, if the transaction was reverted with a string reason, the error is like
```
"Failed to submit transaction: cannot estimate gas : [THE STRING ERROR REASON]."
```

However, for custom errors, the reason is no longer provided.
```
"Failed to submit transaction: cannot estimate gas."
```

### Steps to reproduce

1.
Call a transaction that will be reverted with Solidity custom errors.

### Error messages or log output

```shell
{
    "code": -32603,
    "message": "Internal JSON-RPC error.",
    "data": {
        "code": 3,
        "message": "Failed to submit transaction: cannot estimate gas",
        "data": {
            "code": 104,
            "message": "cannot estimate gas"
        }
    }
}
```

### Version

10.28.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by bergarces** [comment]
Upon investigating the issue, it appears that the message itself comes from the RPC provider.

I cannot find any existing or previous code that attempts to extract selector of the error and attach it to the message part.

Do you know by any chance what RPC provider you were using when the error was being displayed?

**Comment by bschorchit** [comment]
Closing as lego's PR was merged
