### ISSUE TITLE
eth_accounts should return all permitted accounts

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#18515]
When we first shipped the permission system (i.e. `rpc-cap`, today known as the `PermissionController`), we made the conservative decision to make `eth_accounts` continue only returning the user's most recently selected permitted address.<sup>[1](#myfootnote1)</sup> It has always been possible for a dapp to see all of its permitted accounts by inspecting the return value of `wallet_getPermissions`, but many users have requested this behavior for `eth_accounts` over the years. We should evaluate whether this change will break any existing dapps and try to ship it.

**<a name="myfootnote1">1</a>:** Prior to the permission system, all addresses were implicitly permitted, and we always returned whichever one was selected in the UI.

**Acceptance Criteria**
Given: A dapp requests access a wallet user's accounts (by directly or indirectly calling eth_accounts)
When: The user permits the dapp to access more than one account AND the currently selected account is "A"
Then: The resulting array includes all permitted accounts with "A" as the first account in the array

**Non-functional Requirements:**
- [x] Consistent behavior of eth_accounts across Extension & Mobile
- [x] E2E Test Dapp should be updated to allow for multiple accounts in the result
- [x] Test against the top 10 Dapps
- [ ] We should coordinate developer communications around this change
- [ ] Release updated technical documentation once the change is released

NOTE: This change does not require a MIP because it fixes the existing spec

**Comment by jiexi** [comment]
Briefly tested connections on: uniswap, opensea, okx dapp, sushiswap, blur, oasis (doesn't seem to update to newly selected account unless refreshed, but looks this is a dapp bug), polygon zkevm bridge, convex
