### ISSUE TITLE
[Bug]:  MetaMask Extension for Chrome breaks xFinity.com

### ISSUE THREAD

**Issue by Almighty188** [MetaMask/metamask-extension#18511]
### Describe the bug

MetaMask Extension for Chrome breaks xFinity.com when enabled

### Steps to reproduce

1.goto xfinity.com and login
2. Account menu and top menu bar is missing items if extension enabled and works correctly if extension disabled

### Error messages or log output

```shell
There are none
```

### Version

10.28.2

### Build type

None

### Browser

Chrome, Microsoft Edge, Brave

### Operating system

Windows

### Additional context

This is what the website looks like without the extension enabled:
![image](https://user-images.githubusercontent.com/78993393/230692793-e048afbb-0739-4b5f-a4d4-1097fea5647d.png)

This is what it looks like with the extension enabled:
![image](https://user-images.githubusercontent.com/78993393/230692804-cc3afe6c-6081-40c6-94a9-52b8f37d5836.png)

**Comment by JABirchall** [comment]
I think this is an issue with chrome, becuase my lastpass has been doing the same thing.
