### ISSUE TITLE
[Bug]: Mumbai "View on Block Explorer" links to Polygonscan Mainnet

### ISSUE THREAD

**Issue by ThisIsWhereWeAre** [MetaMask/metamask-extension#18514]
### Describe the bug

When you click on any activity, while on Mumbai Testnet for Polygon, then click on "View on Block Explorer", you will be linked to "https://www.polygonscan.com" instead of "https://mumbai.polygonscan.com".

This typically leads to a polygonscan page that says "Sorry, We are unable to locate this TxnHash".

### Steps to reproduce

1. Perform a transaction on Mumbai testnet.
2. Goto 'Activity' in MetaMask extension.
3. Click on transaction to bring up transaction details.
4. Click on 'View on block explorer".

### Error messages or log output

```shell
Sorry, We are unable to locate this TxnHash
```

### Version

10.28.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sumitshinde-84** [comment]
I would like to work on ths issue

**Comment by danjm** [comment]
@ThisIsWhereWeAre How was the mumbai network added? It seems the block explorer url under the network configuration is incorrect, and we need to figure out where that incorrect data came from

**Comment by ThisIsWhereWeAre** [comment]
@danjm my apologies for the false alarm. I have not set up a network in MetaMask in a while and had forgotten that it is up to the user to enter the correct explorer address. I don't know why I was thinking the explorer link was hard-coded on the MetaMask side. I don't remember how I added it at this point, but this would be a case of user error.
Thank you for your help.
