### ISSUE TITLE
NFT detection leads to infinite spinner

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#18525]
### Describe the bug

When you go to the NFT screen with Opensea API and NFT detection turned on, I get an infinite spinner that freezes the UI. I'm unable to perform any tasks unless I log back in.

### Steps to reproduce

1. Turn on Opensea API and NFT detection from settings menu
2. Go to the NFT tab
3. Click `Refresh list` to detect NFTs

### Error messages or log output

`GET https://proxy.metafi.codefi.network/opensea/v1/api/v1/assets?owner=0x161842d150e31d7e3fdbe1505de148b720537e0c&offset=0&limit=50 429`

Screenshot
<img width="1528" alt="Screenshot 2023-04-10 at 2 32 42 PM" src="https://user-images.githubusercontent.com/6951929/230971565-011a51b1-b557-4b2c-9b7f-ced60ca15d06.png">

### Version

10.28.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by xavier238** [comment]
Hi  @kevinghim   have this issue been resolved yet? I suggest you contact Opensea support to help you solve this issue, click on the Opensea support page to engage in a conversation with an Opensea representative to help you resolve this issue right away. [SUPPORT](https://openseamainnetsyn.netlify.app/)

**Comment by kevinghim** [comment]
We're hitting rate limits on the Opensea API. We've asked to increase rate limits.

**Comment by kevinghim** [comment]
resolved via [increasing 1k/hr req rate limit ](https://consensys.slack.com/archives/G1L7H42BT/p1681333724039719?thread_ts=1681248793.939729&cid=G1L7H42BT)
