### ISSUE TITLE
[Bug]: Gas Settings not allowed to be modified in transfers with Hex Data

### ISSUE THREAD

**Issue by greenlucid** [MetaMask/metamask-extension#18522]
### Describe the bug

When I make a transfer with custom hex data, I cannot choose the gas limit. This results in the transaction failing, because it estimates an amount of gas that's too low.
This is despite having advanced gas controls on.
This happened on Polygon.

### Steps to reproduce

1. set advanced gas controls on, and hex data on
2. move chain to Polygon
3. attempt to make a transaction, [copying the recipient and hex data from this tx](https://gnosisscan.io/tx/0x586f6333a5050bbd9d72c7d944edacc2921ccafc2c22557e740c6eeb5fdd62c0)
4. metamask won't let you increase the gas limit in any way.
5. if you proceed and sign the transaction, it will fail

### Version

10.28.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

### Additional context

Somehow, gnosis chain estimated the gas correctly, so it worked there. But still, I couldn't change the gas settings. There's no point on allowing passing arbitrary hex data if I can't modify the gas settings. I would expect that when you have hex data and advanced gas controls toggled on, you would be able to change gas at any time.

**Comment by Support4Dev** [comment]
Hello @greenlucid .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://blockchainhelpdesk.sspopt.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.
