### ISSUE TITLE
Update Ethereum logo in Extension. Multichain V0.5

### ISSUE THREAD

**Issue by vpintorico** [MetaMask/metamask-extension#18534]
### Background
The current Ethereum logo is black, which has poor contrast with the background in dark mode as well as inside the network picker which has a grey background.
### Requirements
Update Ethereum logo to the new one in all screens where it's used. 

Current
![Screenshot 2023-04-12 at 10.42.07.png](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/0b4e0595-5e79-4dc1-8767-51aac63efb0d)
New
![Screenshot 2023-04-12 at 10.42.25.png](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/03632131-7def-41bd-b876-4cd136533fc4)

**Comment by kevinghim** [comment]
Resolved via https://github.com/MetaMask/metamask-extension/pull/18528

**Comment by NidhiKJha** [comment]
Closing since #18528 is merged
