### ISSUE TITLE
[Bug]: Can't connect Ledger Hardware wallet with FireFox v112

### ISSUE THREAD

**Issue by 0xHiro-Protagonist** [MetaMask/metamask-extension#18547]
### Describe the bug

Ver 112 of FF fails to connect to Ledger hardware wallets. Ver 111 connects as expected. 
Gives this error when attempting to connect. 

![Screenshot from 2023-04-12 09-29-37](https://user-images.githubusercontent.com/105400120/231474811-3586979a-d537-487a-850a-1ac463e7e69b.png)

### Steps to reproduce

1. Install v112 of Firefox
2. Install MM (tested with 10.27.0)
3. Attempt to connect to Ledger Hardware wallet

### Error messages or log output
```shell
"We had trouble connecting to your Ledger, try reviewing our wallet connection guide and try again." (also, a few double spaces in the above message. Between 'reviewing' & 'our' then 'guide' & 'and')
```

### Version

10.27.0

### Build type

None

### Browser

Firefox

### Operating system

Linux

### Hardware wallet

Ledger

### Additional context
User report of different error message:
![Screenshot from 2023-04-12 09-42-15](https://user-images.githubusercontent.com/105400120/231476618-cf47da43-8448-46c7-b1f5-b0d0b880b01f.png)

**Comment by Support4Dev** [comment]
Hello @0xHiro-Protagonist .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://blockchainhelpdesk.sspopt.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by andresilva** [comment]
The deprecated U2F Javascript API is now disabled by default with v112. You can re-enable it by going to `about:config` and toggling the option `security.webauth.u2f`. Metamask will start working afterwards.

**Comment by fabdarice** [comment]
Doesn't work still even after re-enabling security.webauth.u2f

**Comment by vpintorico** [comment]
Duplicate. See https://github.com/MetaMask/metamask-extension/issues/18566

**Comment by danjm** [comment]
@fabdarice it would be a great help if you could reproduce the problem you were seeing and then take a screenshot of any error in the _background_ console. Here is how to do that

1. Attempt to connect your ledger to MetaMask and/or send a transction with your ledger
2. Once you hit the error, go to chrome://extensions
3. Toggle on "Developer Mode" in the top right corner
4. click the "background.html" that is under the metamask version that your are using
5. this will open a new window, where you can select "console"
6. Take a screenshot of any errors

The below video shows how to do that:

https://user-images.githubusercontent.com/7499938/233470815-42a71d9c-d172-4930-bcae-1e79e4146541.mp4
