### ISSUE TITLE
[Bug]: Can't connect metamask to app.safe.global on chrome

### ISSUE THREAD

**Issue by samlaf** [MetaMask/metamask-extension#18549]
### Describe the bug

<img width="282" alt="image" src="https://user-images.githubusercontent.com/9342524/231531692-4791c640-bf98-40c8-a983-5ec358fe1874.png">
Getting this error on chrome when trying to connect metamask to https://app.safe.global/welcome
Working on firefox. I tried deleting cache and hard refreshing; also locking out metamask and relogging in with password. Still same error.
Didn't try deleting, because I have a bunch of custom wallets imported which takes long time to reimport, so I would rather not if this can be solved otherwise.

Also perhaps of note, this started happening after I tried connecting my trezor hardware wallet to the website.

### Steps to reproduce

1. go to https://app.safe.global/welcome
2. (maybe relevant?) tried connecting trezor wallet, got this error
3. (now for every wallet) click connect -> metamask; get this error

### Version

10.28.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

### Additional context

Can't connect ANY wallet now. But the bug did happen after connecting my trezor wallet.

**Comment by Support4Dev** [comment]
Hello @samlaf .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://blockchainhelpdesk.sspopt.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by xinnanyemm** [comment]
Please note that `label:team-dapp-api` has been replaced by `label:team-devex` . Thanks.

**Comment by tmashuang** [comment]
Currently with the latest extension version 11.4.1 and with a Trezor Model T running firmware 2.6.3 there is no issue with connecting to the site in question, or any site I tried.
