### ISSUE TITLE
[Bug]: SIWE does not show Ledger dialog

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18552]
### Describe the bug

The following dialog is not displayed on the SIWE confirmation screen

```
Prior to clicking confirm:
- Plug in your Ledger device and select the Ethereum app
- Enable "smart contract data" or "blind signing" on your Ledger device
```

https://user-images.githubusercontent.com/53189696/231578353-f828b9fc-428b-4cd1-a10d-db8621b0a8ce.mov

### Steps to reproduce

1. log in to the extension
2. connect a Ledger Hardware Wallet
3. navigate to the test dapp
4. Click Sign in with ethereum
Ethereum

### Version

10.29

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by digiwand** [comment]
This appears to be an issue since Sign-in With Ethereum was released since the original implementation did not support this message
