### ISSUE TITLE
[Bug]: Setting the gas limit lower than 21000 displays 1 warnings and 1 enforcement message

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18563]
### Describe the bug

**Problem**: whenever I set the gas limit lower than 21000 I get duplicated warnings/messages. I see a warning advising to set gas limit above 21000. This seems a recommendation, but at the same time, I see an input validation which errors and says value must be grater than 21000 and the button is disabled. Could we consolidate this messages so they are not duplicated/ indicating different things (one recommends, the other enforces)? 

Comes from [this conversation.](https://github.com/MetaMask/metamask-extension/pull/18217#issuecomment-1502549333)

![image](https://user-images.githubusercontent.com/54408225/231720512-6a767586-3824-4598-8b6f-35cdf6df0c5e.png)

### Steps to reproduce

1. Start a Send tx
2. Edit gas limit below 21000
3. See warning and input validations messages

### Version

10.28.2

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by plasmacorral** [comment]
Can confirm this is still valid in v10.35.1.  

User is unable to save advanced gas fee settings if gas limit is below 21000.  Screenshots from Optimism.   

If a user wants to offer an extremely high gas limit above 7920027, shouldn't the maximum value be dynamic based on the latest block for the RPC?  In the latest blocks, both Ethereum mainnet and Optimism have a max gas limit = 30,000,000. 

<div style="display: inline-block"> <img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/d7c4cd92-e6b5-4042-844b-9669d48add17"><img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/fc5302c1-4108-4ba1-ac4d-7fb12418f047"></div>
