### ISSUE TITLE
[Bug]: To parse non base32 or base58btc encoded CID multibase decoder must be provided

### ISSUE THREAD

**Issue by Dellybro** [MetaMask/metamask-extension#18564]
### Describe the bug

When using transferFrom on ERC721A i get a bug in metamask. I am unable to do anything with metamask until i remove it from chrome and then reinstall is

<img width="352" alt="Screenshot 2023-04-13 at 2 51 28 AM" src="https://user-images.githubusercontent.com/10732096/231723045-7c0ad768-f7ba-4d11-98b3-9cfa8b23e071.png">

### Steps to reproduce

1. Launch ERC721A, add a transferFrom override `override(ERC721A, IERC721A)` and then call transferFrom on a dApp.

### Error messages or log output

```
Message: To parse non base32 or base58btc encoded CID multibase decoder must be provided

Code: Error

Stack:
Error: To parse non base32 or base58btc encoded CID multibase decoder must be provided
  at r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:8:276992)
  at n.parse
  ```

### Version

latest

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

**Comment by Dellybro** [comment]
Anybody?

**Comment by gauthierpetetin** [comment]
Hello, is this still an issue?

**Comment by gauthierpetetin** [comment]
Hi @MetaMask/extension-platform , do you know if this is still an issue?

**Comment by hjetpoluru** [comment]
I am unable to reproduce the issue [Dellybro](https://github.com/Dellybro) could you please try and confirm.
