### ISSUE TITLE
[Bug]: Duplicate gas estimation error

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18573]
### Describe the bug

https://user-images.githubusercontent.com/53189696/231763826-eed1d19c-8929-4b51-a87a-8a6c42eaff60.mov

### Steps to reproduce

1. log in to the extension
2. navigate to the test dapp
3. connect to the dapp
4. deploy the failing contract
5. click send failing transaction

### Version

10.29

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
I think this might be the same as https://github.com/MetaMask/metamask-extension/issues/17866 which was introduced in `10.25.0`
