### ISSUE TITLE
[Bug]: Hold to reveal SRP button styling

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18572]
### Describe the bug

The button styling is off

https://user-images.githubusercontent.com/53189696/231761467-bdf1117a-f272-495b-81fb-ebfbccec0994.mov

### Steps to reproduce

1. log in to the extension
2. open the account menu
3. click settings
4. click security and privacy
5. click reveal secret recovery phrase
6. enter the password
7. click next

### Version

10.29

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by AlexJupiter** [comment]
This should fix this: https://github.com/MetaMask/metamask-extension/commit/f31596af246e4a2e538b34d15785f78035659bb7

**Comment by PeterYinusa** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/18496
