### ISSUE TITLE
Add friction to enable eth_sign

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#18586]
## Description
Following [#17308](https://github.com/MetaMask/metamask-extension/pull/17308) `eth_sign` has been disabled by default, but users can enable the confirmation method in Settings > Advanced. Enabling `eth_sign` puts the user at risk of [phishing scams](https://medium.com/chainlight/si-vis-pacem-para-bellum-exploring-metamask-phishing-4605425d80a7) that can result in loss of funds.

### Current
- When `eth_sign` is enabled and the user received an `eth_sign` signature request they are shown a _warning_ on the confirmation screen
- On the settings screen, the user is _informed_ that `eth_sign` makes for a phishing risk as it is an open-ended signing method. And to only sign this type of confirmation request if they can read what they are signing and trust the source
- When directed by a scammer to enable `eth_sign`, there are few obstacles or alarm bells for the user to do so (information only)

### Expected
- For both popup and fullscreens:
    - Changes to the Settings > Advanced screen
         - `eth_sign` toggle includes the copy "Recommended" when it's disabled and "not recommended" when its enabled. 
    - Addition of a modal with checkbox
         - Double opt in DS component
    - Addition of a a modal with a text input. 

##### 1. Open double opt-in modal with checkbox
- Given the user is on Settings > Advanced 
- And eth_sign is disabled
- When the user attempts to enable eth_sign
- Then the user is shown a modal with a double opt-in (checkbox + Enable button)

##### 2. Initial state of modal buttons
- Given the user selects eth_sign
- And a modal is presented
- When the checkbox in the modal is unchecked
- Then the `Enable` eth_sign button on this modal is inactive AND a `Cancel` button is active

##### 3. Check checkbox
- Given the user selects Enable eth_sign 
- And a modal is presented
- When the checkbox is checked
- Then the `Enable` button is active AND a `Cancel` button is active

##### 4. Enable eth_sign
- Given the checkbox on the double opt-in modal is checked
- When the user selects `Enable`
- Then the triple opt-in modal is shown

##### 5. Enter text to confirm
- Given the triple opt-in modal is shown, and text input field 
- When the user enters "I only sign what I understand"
- Then eth_sign is enabled

##### 6. Incorrect text
- Given the triple opt-in modal is shown, and text input field 
- When the user enters any text not matching "I only sign what I understand"
- The alert "This text is incorrect. Try again." is shown [go back to #5]

##### 6. Cancel and close modal
- Given the triple opt-in modal is shown
- When the user selects `Cancel`
- Then the modal is closed AND the toggle remains disabled

[Figma popup](https://www.figma.com/file/yb1yRlmbgeGhNiTJvapBTm/settings-eth_sign?node-id=0%3A1&t=cdMpoVnEIAtRj4gq-1)
[Figma Expanded screen](https://www.figma.com/file/yb1yRlmbgeGhNiTJvapBTm/settings-eth_sign?node-id=478-23682&t=uNjQS6kjGs2GE2fl-0)
[Prototype](https://www.figma.com/proto/yb1yRlmbgeGhNiTJvapBTm/settings-eth_sign?page-id=0%3A1&node-id=13-17610&viewport=-166%2C142%2C0.25&scaling=min-zoom&starting-point-node-id=13%3A17610)

**Comment by kevinghim** [comment]
Proposed analytics schema via @bschorchit for this (to match other existing schemas):

When user completes the flow to enable `eth_sign` toggle, we should fire the `Settings Updated` event with a `enable_eth_sign` boolean property with `true` as the value.

When user completes the flow to disable `eth_sign` toggle, we should fire the `Settings Updated` event with a `enable_eth_sign` boolean property with `false` as the value.

We should/could also create a `settings` list-type user property that contains the value `eth_sign` whenever users have this settings enabled in their wallet and does not contain it if they don't.

**Comment by NidhiKJha** [comment]
@kevinghim  I have completed the Eth_sign update and have added analytics as well. But I am not able to understand what you meant by this. 

`We should/could also create a settings list-type user property that contains the value eth_sign whenever users have this settings enabled in their wallet and does not contain it if they don't`
