### ISSUE TITLE
[Bug]: Metamask Flask Chrome extension Illegal invocation 10.28.2-flask.0

### ISSUE THREAD

**Issue by pragmatos** [MetaMask/metamask-extension#18590]
### Describe the bug

`Illegal invocation` when using `atob` & `btoa` in a snap

### Steps to reproduce

1. add `atob` or `btoa` in a snap
2.  call snap
<img width="622" alt="image" src="https://user-images.githubusercontent.com/15641426/231980988-18063c39-8f25-40cf-90ec-3793c03acfef.png">

### Version

10.28.2-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @pragmatos! This issue should be solved with the latest version of Flask according to [this Github thread](https://github.com/MetaMask/snaps-monorepo/issues/1345). I will go ahead and close this. Feel free to open it again if the issue continues to occur. Thank you!
