### ISSUE TITLE
If multiple accounts are connected and one that’s not selected is set as from on sendTransaction, it should still be possible.

### ISSUE THREAD

**Issue by vandan** [MetaMask/metamask-extension#18603]
Given: Multiple accounts are connected to a dapp
When: The dapp attempts a `sendTransaction` call with `from` address that is not the same as the currently selected address in MetaMask
Then: The sendTransaction call should pass through normally (not prevented due to the `from` address not matching the selected address)

**Comment by D1scoDancer** [comment]
Hi! It seems like this behavior might not be very obvious to users (from UI perspective)

**Comment by vandan** [comment]
The idea here was to allow dapps to make use of multiple accounts they may have permission to make calls with. Shelving this issue for now as it needs a more comprehensive design.
