### ISSUE TITLE
ethereumdev.kr is blacklist?

### ISSUE THREAD

**Issue by Nomadblock** [MetaMask/metamask-extension#1860]
![28960679-953812d8-793a-11e7-8f7e-425e35431f43](https://user-images.githubusercontent.com/30719758/28963738-2d818c90-7945-11e7-8de1-27bd77783837.png)

**Comment by Nomadblock** [comment]
I'm founder of Ethereumdev.kr

I have partnered with the founder of 'ethereumdev.io' to translate the contents of ethereumdev.io to provide services.
For Koreans, translated materials are needed because of language barriers.
Now I have plans to fill in our own content.
It is also not a profitable site.
Why is my website detected as blacklist in metamask?
Take care.
If you want, I can show the mail with ethereumdev.io.

**Comment by ropod7** [comment]
Dear MetaMask developers, please, update your syncronization EAL. A lot of hostnames are whitelisted! But not at you extension.

**Comment by Fukunaga42** [comment]
Same problem here with http://dether.io ....

**Comment by kumavis** [comment]
sorry about that, we pushed a new phishing detector last night with fuzzy match and since every app out there is named ether-something, we get a lot of false positives (these names were not explicity blacklisted). 

updating the whitelist now, will sync within 10 minutes

**Comment by kumavis** [comment]
https://dether.io 
http://ethereumdev.kr/
https://ethereumdev.io/
are all working now :+1:
