### ISSUE TITLE
Update SIWE confirmation page with domain binding UI

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#18622]
Following the security concerns around domain binding, we would like to better inform users if parts of the domain mismatch. 

If the port numbers do not match, we would like the user to easily identify this. Some port mismatches (explicitly declared or not) may be expected and non-malicious. 

cc: @naugtur @holantonela

(Needs design) 

Related links:
- Technical discussion and example domain binding scenarios: https://github.com/MetaMask/metamask-extension/issues/18188#issuecomment-1497120809
- [Notes from meeting(s)](https://docs.google.com/document/d/1yyn3YK9ogOKmRtgaP7g1emzUUzq3ViBZlA69-LzNzGQ/edit#)

**Comment by holantonela** [comment]
As I understand the previous discussion, has been decided to allow users to sign this request (no extra friction) but showing the warning banner. I'm attaching a UI that reflects that situation. It will be a similar behaviour we have right now with non matching addresses (bad account E2E).

![image](https://github.com/MetaMask/metamask-extension/assets/87079938/7dcfeb37-e4ec-419e-b653-1585ca369fc6)

[Figma link](https://www.figma.com/file/llV58Rh6Y3ZBPwTUkCTwfu/Sign-in-with-Ethereum?type=design&node-id=703-1530&t=0grBHzVySW73ww3Z-4)

**Comment by bschorchit** [comment]
I think the scope of this ticket is specific to the case of:
origin: http://app.uniswap.io:**5050**
URI: http://app.uniswap.io:**3000**

Where the difference is only on the port being used so, for this specific case, warning should be less intense, but the difference in port should be highlighted/warned somehow. No changes are being made to the other mismatch cases.

**Comment by bschorchit** [comment]
Closing this for now as we haven't seen a need to support less intense warnings for port mismatch. We can re-open this if the need arises.
