### ISSUE TITLE
Expanded snaps authorship component

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#18641]
To structure a snap's (growing set of) metadata, I propose an expanded authorship component.

Initially this will be used by the top of our settings to include;
- Install origin & version
- Enable / disable snap

Description will be separated and within our 3rd party content delineator.

Figma: https://www.figma.com/file/diidnCHx9FXj5LDiA5DZZr/Snaps-features?node-id=1031%3A44672&t=FWWTqxl08ZEk8rej-1

![expanded_authorship_separated.png](https://images.zenhubusercontent.com/6267f04f11d2b941f83b53a0/c231bc06-01f1-4947-8400-21cb7d37e693)

**Comment by kenhkan** [comment]
Pending team feedback and decision. Erik to bounce ideas with the team async. This one is otherwise ready to be worked on.

**Comment by kenhkan** [comment]
Pending team feedback and decision. Erik to bounce ideas with the team async. This one is otherwise ready to be worked on.
