### ISSUE TITLE
UX: Multichain: Long Network Names Cause Problems in App Header

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#18640]
### Describe the bug

When the network name is really long, like our current suggested name for BNB chain, the account name in the new header gets pushed and it's ugly UI.  We should implement a max-width on the picker to avoid this UI problem.

<img width="834" alt="SCR-20230418-iege" src="https://user-images.githubusercontent.com/46655/232801507-56b75e7e-bfd7-458a-a44b-fe5cb4935835.png">

In brief testing, `250px` looked good.

### Steps to reproduce

1.  Run the extension with `MULTICHAIN=1`
2. Add BNB chain from Settings > Network
3. See problem.

### Version

10.29

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by georgewrmarshall** [comment]
I think we could approach this on a case by case basis? I think by using a combination of CSS grid and min width we should be able to prioritize the account picker length over the network picker until the network picker reaches it's minimum width. Then the account picker could also truncate? Unfortunately we don't have any way to easily add css grid helpers so it would have to use custom CSS

**Comment by georgewrmarshall** [comment]
I was always of the opinion that our buttons and pickers should have a minimum width so the hit space is maintained and we don't end up with very small button sizes if the string length is small. e.g what should the PickerNetwork look like if only a single letter is added for a custom network?

**Comment by SaraCheikh** [comment]
Did some testing to have a max width in the account picker and 200px seems to work without truncating the name of the account picker too often @georgewrmarshall @darkwing 
<img width="612" alt="Screenshot 2023-04-21 at 10 09 12" src="https://user-images.githubusercontent.com/98161559/233582332-38040c71-d6bf-4958-b650-b415e0fa6f19.png">
