### ISSUE TITLE
Support ENS resolution on any EVM compatible chain (including L2s)

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#18648]
### Background
Currently ENS resolution is only supported on Ethereum mainnet. This issue addresses extending support for it for any EVM network supported by ENS.

### Acceptance Criterias
1. User facing functionality for ENS resolution that currently exists for Ethereum Mainnet is replicated for all ENS-supported EVM compatible chains in MM
2. When a network doesn't have ENS support, the `Network does not support ENS` warning is shown when the user tries to input an ENS name on a send flow
3. We should test this with Linea test network (once it has ENS support) and confirm it's working

### Repro Steps
1. Click on Send 
2. Input an ENS address such as `Vitalik.eth`
3. See ENS resolved to the correct registered address if you're on Ethereum Mainnet, Goerli or Sepolia or see the `Network does not support ENS` warning if you're on a different network

### References
- https://github.com/MetaMask/specifications/issues/11
- https://github.com/MetaMask/metamask-extension/pull/18035
- Dependency: https://github.com/MetaMask/core/issues/1044

**Comment by mozrt2** [comment]
Hi @bschorchit - I wanted to ask if there are any updates on this issue? It seems like a widely requested one (see for example [12990](https://github.com/MetaMask/metamask-extension/issues/12990)) and important for good L2 UX

**Comment by mirceanis** [comment]
This will be resolved by #26242
