### ISSUE TITLE
NetworkController: Before creating a new provider, remove all event listeners from the old one

### ISSUE THREAD

**Issue by mcmire** [MetaMask/metamask-extension#18647]
In the core version of NetworkController, when the network is switched but before a new provider is created for the new network, [the current provider is stopped](https://github.com/MetaMask/core/blob/c8c9f389589522bc6a5147aad8679cddbd8f3381/packages/network-controller/src/NetworkController.ts#L381). In this version of NetworkController, which uses SafeEventEmitterProvider, you can't call `stop` on the provider instance, but you can call `removeAllListeners`. We should do that here as well.

**Comment by Gudahtt** [comment]
Hmm, which event listeners would we be removing in this case? I'm wondering whether this would break things that rely on events being emitted even after switching networks.

The linked behavior in the core repository was implemented before we started using a provider proxy, which may explain why it never caused an issue there.

**Comment by mcmire** [comment]
Hmm, I guess my thought was that we would clean up listeners because they wouldn't be needed anymore if the provider is no longer in use. But you're right. That defeats the point of a provider proxy.

I did see a change in the `web3-provider-engine` replacement PR that changed `provider.stop()` to `provider.removeAllListeners()`, which is really where this ticket came from, but I suppose that means we should remove that as well. I'll point this out in that PR.
