### ISSUE TITLE
[Bug]: Failed to create and then recreated with two identical accounts

### ISSUE THREAD

**Issue by huazhuangnan** [MetaMask/metamask-extension#18681]
### Describe the bug

Failed to create and then recreated with two identical accounts
![image](https://user-images.githubusercontent.com/46070704/233332096-bae65f7b-d60e-4c6e-8bbb-ab093945805b.png)

### Steps to reproduce

1. Failed to create an account.
2. Continue to create successfully showing two identical accounts.

### Version

10.28.3

### Build type

None

### Browser

Chrome, Microsoft Edge

### Operating system

Windows

**Comment by danjm** [comment]
@huazhuangnan I see that you have a wallet connect account in between the two identical accounts. Can you describes the sequence of actions that led to the creation of all three accounts?

Did you create account 2, then import the wallet connect account, then try to create another account? Or did the wallet connect account already exist, and then you tried to create an account, and the other two were added at the same time? Or something else?

**Comment by huazhuangnan** [comment]
@danjm  I created one that failed and then created another that worked, after which I imported the previous account. When I opened the dapp website to use it, I found two identical accounts, and I couldn't click on the disconnect action.
