### ISSUE TITLE
My metamask password, and seed doesn't work 

### ISSUE THREAD

**Issue by Sandis71** [MetaMask/metamask-extension#1869]
I Use Ether delta and managed to send some ether from another website to the wrong etherdelta account wich didnt use metamask. Ether delta told me to delete metamask from my browser for me to do anything with my unconnected etherdelta transactions. I deleted metamask from my browser as etherdelta instructed. When i stil didn't manage to send the ether anywhere, I reinstalled metamask my password didnt work. When I tried changing the password using the seed, it said it was invalid. Please help. 

mvh Sander.

**Comment by tmashuang** [comment]
closing due to an already submitted support ticket.
