### ISSUE TITLE
Update Button prop name `type` to `variant` 

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18693]
### Description
Currently the prop to change the button style: PRIMARY, SECONDARY, LINK etc for the component-library `Button` component is called `type`. It would be more consistent with the rest of our components of this prop was renamed to `variant`

There should be only a few instances of the `Button` component from the `ui/components/component-library` folder so it should be ok to update all in one PR

<img width="305" alt="Screenshot 2023-04-21 at 1 30 26 AM" src="https://user-images.githubusercontent.com/8112138/233423044-c8b3e1b4-db56-40ce-8ea0-0e04ed9e0294.png">

### Technical Details
- Update const `BUTTON_TYPES` to `BUTTON_VARIANT`
- Update all instances of `type` prop to `variant` for the `Button` component
- Update all storybook stories and documentation
- Update all tests
- Update all instances of Button used in the code base

### Acceptance Criteria
- All instances of the `type` prop have been updated to `variant`
- All storybook stories and docs have been updated accordingly
- PR contains before/after screenshots of every instance of the Button that has been updated

**Comment by hakeemullahjan** [comment]
@georgewrmarshall I would love to take this. Please can you assign this to me?

**Comment by georgewrmarshall** [comment]
Hey @hakeemullahjan, thanks for your interest. Assigned. Looking forward to your PR. Thanks!

**Comment by madgbec** [comment]
Thank you which program do I start from

**Comment by hakeemullahjan** [comment]
#18774

**Comment by dhruvv173** [comment]
Hi @georgewrmarshall @hakeemullahjan, I'd like to assist to this issue

**Comment by georgewrmarshall** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/18774
