### ISSUE TITLE
[Bug]: Cannot switch to linea testnet network using "wallet_switchEthereumChain"

### ISSUE THREAD

**Issue by VGau** [MetaMask/metamask-extension#18709]
### Describe the bug

 I got the following error when I want to use the MM API `wallet_switchEthereumChain` endpoint to switch to linea testnet network.

![image](https://user-images.githubusercontent.com/85494462/233566530-3ac62e90-aee1-436b-b692-aa6feec26737.png)

### Steps to reproduce

1. Open this website : https://testnet.cashmere.exchange/swap
2. Connect your metamask wallet.
3. Select the Linea zkEVM testnet in the `from` dropdown.
4. Click on the `Switch network` button at the bottom of the page.

### Error messages or log output

```shell
MetaMask - RPC Error: networkConfigurationId undefined does not match a configured networkConfiguration Objectcode: -32603data: originalError: [[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()[[Prototype]]: Objectmessage: "networkConfigurationId undefined does not match a configured networkConfiguration"[[Prototype]]: Object
(anonymous)


Uncaught (in promise) SwitchChainError: Error switching chain
    at AY.switchChain
```

### Version

10.28.3

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by nfts2me** [comment]
We're also having this issue at https://nfts2me.com/

When switching to Linea blockchain, it does nothing.
It is the only blockchain that have this issue on Metamask.
It seems that Metamask handles Linea blockchain in a different way that the rest of blockchain.

To illustrate:
![telegram-cloud-photo-size-4-5922540823948410192-x](https://user-images.githubusercontent.com/109629895/233950607-a0fbc5e1-2687-4420-bca8-925c04a64b72.jpg)

After clicking on "Switch network", it doesn't switch on Metamask.
Unless the user manually changes it, it doesn't change. If the user manually changes it, it works fine.

All of the other networks are switching fine.

**Comment by walruzperil** [comment]
i still have same issue
After clicking on  switch button
![image](https://github.com/MetaMask/metamask-extension/assets/7361881/fffc48b9-4f1c-4e36-bd1e-50595cc022fc)
i  got this error
![image](https://github.com/MetaMask/metamask-extension/assets/7361881/8361af9c-30ca-45da-acca-72378a720388)
just trying switch to linea:

```
let ver = 59144;
if (window.ethereum.networkVersion !== ver) {
try {
       
        await window.ethereum.request({

          method: 'wallet_switchEthereumChain',
          params: [{ chainId: '0xE708'}], 
        });
      } catch (error) {
      
                    }
   
 }
```
i trying  connect to linea from another websites, its works. But on my website doesn't
how to fix it?
