### ISSUE TITLE
add HTTP auth for node providers

### ISSUE THREAD

**Issue by nysxah** [MetaMask/metamask-extension#1871]
dan suggested a feature request be opened to improve setting of custom nodes:

add HTTP auth or use with node providers such as quiknode.io -- where a user/pass is required to connect.

> https://quiknode.io/node/eb7e39aa-d876-4dd9-b9ee-92bb14fb8cb2/P1KLaV3YADT05PjJMGEZEw==
> 
> it uses http auth (user, pass)
> 
> for that node, user is the email addy
> 
> pass is "testing123"
> 
> i tried https://streamraise@gmail.com:testing123@kindly-awake-warthog.quiknode.io:443 in the custom field, even encoding the "@", but it never connects.

**Comment by gianlucaschoefer** [comment]
I would also really like to see this implemented.

**Comment by flyswatter** [comment]
The Quiknode has found they can get the results they wanted out of subdomains & paths, do you still see this as worth keeping open, @gianlucaschoefer?

**Comment by gianlucaschoefer** [comment]
@flyswatter currently not, no. Thanks.
