### ISSUE TITLE
Buy Screen - Use ShapeShift Shifty Button

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1872]
currently we have our own form which is a bit messy (especially because extension window limitations) - instead we should just use their Shifty button

below generated here https://info.shapeshift.io/tools/shifty-button

dont need to use this code, can really just navigate to the generated url

apiKey is correct but address needs to be programmatic
```js
<script>function shapeshift_click(a,e){e.preventDefault();var 
link=a.href;window.open(link,'1418115287605','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=0,left=0,top=0');return false;}</script> <a onclick="shapeshift_click(this, event);" href="https://shapeshift.io/shifty.html?destination=0x3AE39E89Dc7e736cCe53091057A45bF44B1A566c&amp;output=ETH&amp;apiKey=803d1f5df2ed1b1476e4b9e6bcd089e34d8874595dda6a23b67d93c56ea9cc2445e98a6748b219b2b6ad654d9f075f1f1db139abfa93158c04e825db122c14b6"><img src="https://shapeshift.io/images/shifty/xs_light_altcoins.png" class="ss-button"></a>
```

**Comment by kumavis** [comment]
in order to support existing shapeshift tx history feature we need https://github.com/Shapeshift-Public/Shifty/pull/9

**Comment by brandonrninefive** [comment]
Hello, I'd like to work on this!
