### ISSUE TITLE
Consider lowering the minimum gas price

### ISSUE THREAD

**Issue by thisbejim** [MetaMask/metamask-extension#1873]
Over at [ethgasstation](http://ethgasstation.info/index.php) the safelow gas price is currently 0.5 gwei which is half of metamask's current minimum. It would be quite useful for some services if we could lower the minimum.

**Comment by Zanibas** [comment]
Now that Infura is going to help maintain the gas station, we should consider an API that will dynamically change the minimum.

**Comment by thisbejim** [comment]
Added in https://github.com/MetaMask/metamask-extension/pull/2491
