### ISSUE TITLE
Keyring consolidation: Use `@metamask/keyring-controller` instead of `@metamask/eth-keyring-controller`

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/metamask-extension#18758]
This EPIC represents the last steps of the effort to consolidate keyring interactions between the two clients. This is taken out from changes proposed [here](https://github.com/metamask/core/issues/1103) 

In this last step, we should drop the use of `@metamask/eth-keyring-controller` in favor of `@metamask/keyring-controller`.

This is blocked by [EPIC  #1150](https://github.com/MetaMask/core/issues/1150).

**Comment by mcmire** [comment]
Is this epic complete now?

**Comment by mikesposito** [comment]
@mcmire yes! We can close this.
