### ISSUE TITLE
Keyring consolidation: Clear session storage on wallet lock

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/metamask-extension#18766]
This is part of the effort to consolidate keyring interactions between extension and mobile.
Originally proposed [here](https://github.com/metamask/core/issues/1103#issuecomment-1497403763).

For MV3 compatibility, on the extension `clearLoginArtifacts` is also called to remove login data from the browser session storage. When migrating to `@metamask/keyring-controller`, we should move `clearLoginArtifacts` to a `lock` event handler.

**Comment by Gudahtt** [comment]
Closed by #20341
