### ISSUE TITLE
[Bug]: Coinbase extension (3.16.2 version) blocks MetaMask injection at wndow.ethereum

### ISSUE THREAD

**Issue by Somnus007** [MetaMask/metamask-extension#18760]
### Describe the bug

When both Coinbase (v 3.16.2) and Metamask (v. 10.28.3) extensions are installed, the first time a page is opened (NOT RELOAD PAGE), MetaMask does not inject its global API at window.ethereum. `window.ethereum` is entirely from Coinbase at this moment. But if you reload this page, you will see both Metamask and Coinbase providers in `window.ethereum`

### Steps to reproduce

On Chrome (112.0.5615.137 version):

1. Install Coinbase (v 3.16.2)
2. Install MetaMask (v. 10.28.3)
3. open a new page, on Chrome console look for window.ethereum. You should get a `window.ethereum` which is entirely from Coinbase
4. Reload the page
5. On Chrome console look for window.ethereum again, you will see both Metamask and Coinbase providers in `window.ethereum` 

### Error messages or log output

```shell
No errore message
```

### Version

10.28.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by ahollenbach** [comment]
I have observed this as well on Brave, without Coinbase Wallet installed.

On the first page load, only the Brave provider is present, after refresh it's the MetaMask provider. For Brave, my "Default Ethereum wallet" preference is set to "Extension" (aka MetaMask). This only started happening recently (past week or two).

**Comment by anaamolnar** [comment]
Related to  #18157

**Comment by kevinghim** [comment]
We will probably consider [EIP-6963 Multi Injected Provider Discovery](https://github.com/ethereum/EIPs/pull/6963) in the near future to prevent provider injection collisions.

**Comment by vandan** [comment]
[Announced our plans to support EIP-6963](https://metamask.io/news/developers/improving-the-multi-wallet-user-experience-with-eip-6963/).

**Comment by vandan** [comment]
EIP-6963 Support is now available in v11.4.0 of our Chrome Browser Extension.
We recommend modifying your code to adopt EIP-6963.
WalletConnect has provided an example here: https://github.com/WalletConnect/EIP6963
