### ISSUE TITLE
After changing a password of MetaMask account - all money are gone

### ISSUE THREAD

**Issue by kobavadim** [MetaMask/metamask-extension#1878]
Windows
Chrome 

MetaMask Chrome extension  has logged me out, when i try to use password it says it's wrong. so i choose option to change my password. It asked for my 12 word secret phrase and when i entered it - it says there is no money on balance when i have a lot of them. Could you please advice me what to do?

Thanks in advance,
Vadim Koba

**Comment by tmashuang** [comment]
Is this still an issue?

**Comment by kobavadim** [comment]
Hello tmashuang, I forgot that my correct MetaMask wallet on laptop so i was messing around with another MetaMask account that doesn't have money on it. Just found out the correct one. So the issue can be closed. Thank you! And sorry for inconvinience
