### ISSUE TITLE
[Bug]: EOA's are referred to as contracts in multiple screens

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18806]
### Describe the bug

Related to https://github.com/MetaMask/metamask-extension/issues/16587 and https://github.com/MetaMask/metamask-extension/pull/18101

Should we be replacing `Contract requesting access` to `Third-party requesting access` in the following screens also:

ERC1155 Set Approval For All
<img width="472" alt="third party erc1155" src="https://user-images.githubusercontent.com/53189696/234353556-15c06661-6f84-4e11-9f84-d77c0be4b616.png">

ERC721 Set Approval For All
<img width="472" alt="third party erc721" src="https://user-images.githubusercontent.com/53189696/234353603-e005e332-9dbf-4d6d-a4fc-f656859246dd.png">

Signature request Signed Type Data V3
<img width="472" alt="third party signv3" src="https://user-images.githubusercontent.com/53189696/234353632-c57c38ba-60f4-4e10-adf4-f7489becdcaf.png">

Signature request Signed Type Data V3
<img width="472" alt="third party signv4" src="https://user-images.githubusercontent.com/53189696/234353654-93677a27-e97e-47b3-a8c1-6577f8f7229d.png">

Bringing them in line with:
ERC20 Token Allownace
<img width="472" alt="third party erc20" src="https://user-images.githubusercontent.com/53189696/234353709-27a0aaca-1732-477b-99e3-6aeec5305b77.png">

### Steps to reproduce

1. Log in to the extension
2. Navigate to the test dapp
3. Connect
4. Set Approval For All or Sign
5. Click verify third-party details

### Version

10.30

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
> @bschorchit Should this change be applied to all the screens listed above?

Yes, it should. Thank you for catching this, Peter!
