### ISSUE TITLE
[Bug]: Terms Modal scrolldown click does not disappear when at the bottom.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#18814]
### Describe the bug

The scroll-down click in the new updated Terms of Use modal does not disappear when being clicked, or when being at the bottom of the text field. 

https://user-images.githubusercontent.com/13376180/234426447-ba934e89-5c05-47f6-a5cc-5306630a70f5.mov

### Steps to reproduce

1. When updating from v10.29.3 to v10.30.0 the updated Terms of Use modal should pop up. 
2. Click the scroll-down button to reach the end of the text. 
3. Notice that the button is still present.

### Version

v10.30.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by kevinghim** [comment]
Fixed through https://github.com/MetaMask/metamask-extension/pull/18843
