### ISSUE TITLE
[Bug]: `accountsChanged` is being triggered even if 'eth_accounts' returns the same wallet.

### ISSUE THREAD

**Issue by SD170** [MetaMask/metamask-extension#18817]
### Describe the bug

Here in your [docs](https://docs.metamask.io/wallet/reference/provider-api/#accountschanged) it's clearly written 

> The provider emits this event when the return value of the [eth_accounts](https://metamask.github.io/api-playground/api-documentation/#eth_accounts) RPC method `changes`

.

Now I had a specific requirement of listening to the "accountsChanged" trigger. And I was also using
```
await window.ethereum.request({
    method: "eth_accounts"
});
```
to get the connected wallets (as it returns them after the wallet is connected for the first time).

Now for example:
If wallet A is connected, if I use `window.ethereum.request` it **should** return the same wallet A and not hit the `accountsChanged` event. But it's actually triggering `accountsChanged` event even when the wallet is the same.

It also emits the error.

> MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug. 

Which if I'm not wrong means only one thing. That `window.ethereum.request` is updating the accounts array even when the account is not updating. And thus triggering `accountsChanged` event.

### Steps to reproduce

1. In my case once the wallet is connected to the dApp, calling`window.ethereum.request` throws this error:

> MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug. 

### Error messages or log output

```shell
MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug.
```

### Version

10.28.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by xinnanyemm** [comment]
Please note that `label:team-dapp-api` has been replaced by `label:team-devex` . Thanks.
