### ISSUE TITLE
[Bug]: Closing a notification window does not reject signature requests

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#18828]
To repro:

1. Create a signature request (e.g. sign type data v4 on the test dapp)
2. Close the notification window using the window close button (**not** the "Reject" button)
3. An error will appear in the background console: `this._metricsEvent is not a function`. This is thrown from `SignController._cancelAbstractMessage`
4. If you open metamask again, the signature request will still be there. In the past, we automatically rejected signature requests on close of the notification window.

This can be seen in v10.29.0.

This was discovered via this sentry error: https://metamask.sentry.io/issues/4117470415/events/84529edd0f244dc49c8b4af984f38e59/

Screenshot of the most relevant sentry details:
![Screenshot from 2023-04-26 09-13-10](https://user-images.githubusercontent.com/7499938/234564736-654cba5b-ec3c-4823-b975-20c5f13715d6.png)

**Comment by danjm** [comment]
This may or may not be related to this sentry error: https://metamask.sentry.io/issues/4123897399/events/669287bd1da746f8a13690f069f9c091/

![Screenshot from 2023-04-26 09-15-20](https://user-images.githubusercontent.com/7499938/234565171-143ac9b8-663e-4737-b287-75e3c5930d47.png)

**Comment by OGPoyraz** [comment]
This is fixed in https://github.com/MetaMask/metamask-extension/pull/18318 and not happening in `develop` branch right now.

https://user-images.githubusercontent.com/7644512/234816094-ec6ce204-d155-41c8-9380-5aefeebe9054.mov
