### ISSUE TITLE
P0 ~ MetaMask lacks way to Create Separate Login for existing accounts

### ISSUE THREAD

**Issue by Loreneum** [MetaMask/metamask-extension#1888]
P0 ~ MetaMask lacks way to Create Separate Login for existing accounts

My friend **does not have a computer** and wants to open a MetaMask account. We, naturally, do not want to link accounts in any way. I discovered how to create a separate account on the same computer (create Person 2 in Chrome, add MetaMask ext in Person 2 instance, create new acct), but I didn't discover this until AFTER unwittingly linking our accounts using Civic Secure Identity. So now in MY MetaMask account, I have Account 1 linked with my personal info and Account 2 linked with his personal info, but access to BOTH ACCOUNTS only requires ONE PASSWORD or the SAME 12 WORDS <- NO BUENO! Now we need a way to PERMANENTLY separate our accounts!! MetaMask needs both a way to Sign Out AND Create Separate Logins for existing accounts!

**Comment by Loreneum** [comment]
please note that this is TWO issues caused by one. the real block is the inability to Sign Out #1887

**Comment by kumavis** [comment]
You can log out via "lock" under the menu in the top right

I agree managing multiple users could be more straightforward.

As you discovered, for multiple users, I reccomend using multiple chrome users to keep accounts seperate https://support.google.com/chrome/answer/2364824?co=GENIE.Platform%3DDesktop&hl=en

Now that you've created new vaults, you'll want to migrate your assets and registrations to new addresses to avoid leaking control of your existing accounts to each other via the seed phrase

**Comment by Loreneum** [comment]
LOCK DOES NOT SIGN OUT! When you click LOCK, it prompts you to enter your password again, IT DOES NOT SIGN YOU OUT OR GIVE THE OPPORTUNITY TO SIGN IN WITH A DIFFERENT ACCOUNT

**Comment by kumavis** [comment]
i will not work with anyone that uses all caps

**Comment by Loreneum** [comment]
does that change the fact that this is a serious bug that exists and needs to be addressed? lock does not sign out. how many other bugs are in the software because you've closed them due to not understanding them as well as you believe you do?

**Comment by frankiebee** [comment]
this is not a bug it is a feature request

**Comment by Loreneum** [comment]
hey! that makes sense!

**Comment by kumavis** [comment]
The feature request has been recorded here https://github.com/MetaMask/metamask-extension/issues/1889

**Comment by flyswatter** [comment]
This is also already captured in #714 (for the notion that different pages might want to sign in with different accounts, and allowing the user to select the desired account at log-in time.

This is also partly addressed in #731, which would allow importing multiple seed phrases, and requires design to distinguish them visually.

**Comment by kumavis** [comment]
@flyswatter i would say those two are only tangentially related
this is more about allowing two separate people to use metamask on the same machine
anyways please add any comment on #1889 instead

**Comment by flyswatter** [comment]
To repeat what I said in the other thread: Using chrome profiles this feature is added for free, without any additional "P0" work on our parts.

**Comment by Loreneum** [comment]
description edited for clarity
