### ISSUE TITLE
Migrate components to TS: ButtonSecondary

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18888]
### Description
Migrate `ButtonSecondary` component to TypeScript

Dependencies
- https://github.com/MetaMask/metamask-extension/issues/19239

### Technical Details

- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` (name and keys)
- Ensure enums use singular not plural e.g. `Size` not `Sizes`
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation

### Acceptance Criteria

- Component has been converted to TypeScript
- Stories, documentation and tests have been updated inside of the `component-name` folder
- Before/After screen cast of component stories in storybook to show no visual regression after migration

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with TypeScript and want to contribute to improving the stability of the extension

**Comment by shinopark** [comment]
Hi is this a beginner level issue?

**Comment by georgewrmarshall** [comment]
Hey @JohnPark24, I would consider this an intermediate level issue. To take on this task a contributor should have good knowledge of TypeScript, jest, storybook and be able to run the extension on their local. I would suggesting getting the extension up and running on your local first by following the readme https://github.com/MetaMask/metamask-extension#building-locally and then possibly contributing to https://github.com/MetaMask/metamask-extension/issues/17670 or https://github.com/MetaMask/metamask-extension/issues/18714

**Comment by georgewrmarshall** [comment]
Removing `good-first-issue` label until we close the `Box` dependency https://github.com/MetaMask/metamask-extension/issues/19239

**Comment by dhruvv173** [comment]
hello @georgewrmarshall can you assign this to me?
