### ISSUE TITLE
Migrate components to TS: Button

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#18890]
### Description
Migrate `Button` component to TypeScript

Dependencies
- https://github.com/MetaMask/metamask-extension/issues/19239
- #19067 
- #18889 
- #18887 
- https://github.com/MetaMask/metamask-extension/issues/18888

### Technical Details

- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` (name and keys)
- Ensure enums use singular not plural e.g. `Size` not `Sizes`
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation

### Acceptance Criteria

- Component has been converted to TypeScript
- Stories, documentation and tests have been updated inside of the `component-name` folder
- Before/After screen cast of component stories in storybook to show no visual regression after migration

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with TypeScript and want to contribute to improving the stability of the extension

**Comment by georgewrmarshall** [comment]
Hi @sumitshinde-84, https://github.com/MetaMask/metamask-extension/issues/18886 would be a dependency of this ticket I think this would be appropriate to take on first

**Comment by sumitshinde-84** [comment]
Hello @georgewrmarshall, I would like to take on the assigned issue as I have prior experience with the codebase and can contribute effectively. Additionally, please assign me the following related issues for a comprehensive approach: https://github.com/MetaMask/metamask-extension/issues/18882, https://github.com/MetaMask/metamask-extension/issues/18883, https://github.com/MetaMask/metamask-extension/issues/18884, https://github.com/MetaMask/metamask-extension/issues/18885, https://github.com/MetaMask/metamask-extension/issues/18886, https://github.com/MetaMask/metamask-extension/issues/18887, https://github.com/MetaMask/metamask-extension/issues/18888, https://github.com/MetaMask/metamask-extension/issues/18889, and https://github.com/MetaMask/metamask-extension/issues/18890. Thank you for your consideration.

**Comment by georgewrmarshall** [comment]
Removing `good-first-issue` label until we close the `Box` dependency https://github.com/MetaMask/metamask-extension/issues/19239

**Comment by dhruvv173** [comment]
hello @garrettbear if you have not started working on this can I work on it?

**Comment by georgewrmarshall** [comment]
Hey @dhruvv173, I'm going to assign you as @garrettbear and I will be away next week but will be able to support the following week. It has a dependency of https://github.com/MetaMask/metamask-extension/issues/18888 you should be able to use @garrettbear's PR for ButtonPrimary as a reference https://github.com/MetaMask/metamask-extension/pull/20390

**Comment by dhruvv173** [comment]
> Hey @dhruvv173, I'm going to assign you as @garrettbear and I will be away next week but will be able to support the following week. It has a dependency of #18888 which I would suggest you work on first. You should be able to use @garrettbear's PR for ButtonPrimary as a reference #20390

Sure, thank you for the update, I will work on that issue over the weekend.

**Comment by dhruvv173** [comment]
hey @georgewrmarshall can I work on this now?

**Comment by georgewrmarshall** [comment]
Hey @dhruvv173, I believe @garrettbear is working on this ticket but feel free to take a look at others. All the dependencies for https://github.com/MetaMask/metamask-extension/issues/19126 have been resolved. It might be a good one to take on. Thanks
