### ISSUE TITLE
[Bug]: Sending an ERC721 token from a Dapp does not display token id and the Edit screen is incorrect, if the token is not previously added on the Wallet

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18915]
### Describe the bug

**Problem**: whenever we are trying to send an ERC721 token from a dapp, we see 2 problems arise if the token is not previously added on the dapp:

- On the Send token screen, we do not see the token id
- If we click Edit, we see as if we were sending ETH - not a token

https://user-images.githubusercontent.com/54408225/235636645-b90fa125-753d-470f-bb04-4e50e75e2192.mp4

### Steps to reproduce

1. Go to test dapp
2. Click Deploy Collectibles and accept
3. Click Mint and accept
4. Click Transfer From -- see how no token id is shown
5. Click Edit -- see how no token is displayed, it looks like a regular send

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by MetamaskDevv** [comment]
Hello @seaona .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://blockchainhelpdesk.sspopt.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.
