### ISSUE TITLE
Keyring: Resetting a wallet

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18921]

**Comment by tmashuang** [comment]
How does one reset the wallet on the onboarding flow?

**Comment by PeterYinusa** [comment]
> How does one reset the wallet on the onboarding flow?

This task refers to the `Forgot Password` -> `Reset Wallet` flow.

I'll update the title from `Onboarding` to `Keyring`, so there's a better understanding of the task relating to the affected controller.
