### ISSUE TITLE
[Bug]: Buy button not disabled for ERC20 tokens in Sepolia

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18949]
### Describe the bug

**Problem**: whenever I import tokens on Sepolia network, I can see how the `Buy` button is not disabled.

https://user-images.githubusercontent.com/54408225/235675160-f88c3843-1307-405e-a472-c40f9472cee7.mp4

**Expected**: Buy button should be disabled as we do on Goerli, for ERC20 tokens? See:

![Screenshot from 2023-05-02 15-06-20](https://user-images.githubusercontent.com/54408225/235675326-41d4b6e8-4055-426f-81da-14f7507440dd.png)

Note: whenever fixing this, make sure it does not happen in other networks too

### Steps to reproduce

1. Select Sepolia network
2. Go to test dapp https://metamask.github.io/test-dapp/
3. Click Create Token and procced
4. Click Add Token to wallet and proceed
5. Go to MetaMask
6. Click the new added token
7. See Buy button is enabled

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by nikhilverma360** [comment]
Hey @seaona & @darkwing  , I have fixed the issue. Could you review Please?
