### ISSUE TITLE
[Bug]: networkConfigurationId undefined

### ISSUE THREAD

**Issue by kevoh1516** [MetaMask/metamask-extension#18954]
### Describe the bug

Same bug as #18509 which was supposedly fixed by 10.28.3 but I am still having this  issue as of 10.29.0. If I revert to 10.27.0 the issue goes away.

Seems to happen specifically when switching from Goerli to Sepolia for me. I can switch from Sepolia to Goerli just fine. Haven't tested with other networks. 

### Steps to reproduce

1.

### Version

10.29.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Linux

**Comment by sw-3** [comment]
I am still seeing the error when switching to Sepolia currently.  
I can switch to Hardat on localhost, Goerli, and Mumbai, with no issues.

When I select the Sepolia option in my dapp, it pops MetaMask and prompts me to allow to switch to Sepolia (so I know it recognizes the chainID correctly as Sepolia), and when I click "Switch Network" I get the following:

"networkConfigurationId undefined does not match a configured networkConfiguration"

Metamask version:  10.29.0
Chromium  Version 113.0.5672.63
OS Version:  Ubuntu 22.04

**Comment by alpinevm** [comment]
Still experiencing this strictly on Sepolia. 
Error is always:
"networkConfigurationId undefined does not match a configured networkConfiguration""

Metamask v10.32.0
Chrome Version 114.0.5735.106 (Official Build) (arm64)
OS Version: macOs Monterey 12.3 & macOs Ventura 13.0

**Comment by walruzperil** [comment]
any solutions?

**Comment by sgraphics** [comment]
Apparently its due to specifying capital casing for network id when calling wallet_switchEthereumChain. So instead of 0xAA36A7, use 0xaa36a7 for Sepolia.

This is definitely still a bug as many online documents explicitly advise to use the capital case version (e.g. https://docs.alchemy.com/docs/how-to-set-up-the-metamask-sdk). Also online dec-to-hex converters (such as https://www.rapidtables.com/convert/number/decimal-to-hex.html) report CAPITAL case versions for the conversion.

**Comment by sgraphics** [comment]
Apparently there is a fix incoming: https://github.com/MetaMask/metamask-extension/commit/0ea765ebf6771cd70a922d74e68bbca56b31d1f7

**Comment by Anouk1973** [comment]
I dont have a cleu of this all
I let me talk in to make a deposit from 250 and now i cant find noting and
afraid i am robt

Op za 30 dec. 2023 13:07 schreef github-actions[bot] <
***@***.***>:
