### ISSUE TITLE
[Bug]: Metamask not showing price in USD- GDCC

### ISSUE THREAD

**Issue by GDCC-COIN** [MetaMask/metamask-extension#18951]
### Describe the bug

Its not showing price of GDCC(GDCC Project) in USD on metamask extension. In process to find root cause of issue we have found its taking price from [CoinGecko](https://www.coingecko.com/en/coins/global-digital-cluster-co) and [Coinmarketcap](https://coinmarketcap.com/currencies/global-digital-cluster-coin/)  We are looking forward for help to find why this is happening and how we can resolve this ?

### Steps to reproduce

1.Connect pandoproject (mainnet) on metamask
2.This will show the GDCC price is USD which are not coming.
3.For correct price refer below link
Coingecko- https://www.coingecko.com/en/coins/global-digital-cluster-co
Coinmarketcap - https://coinmarketcap.com/currencies/global-digital-cluster-coin/
Our Explorer https://www.gdccscan.io/

Network name : GDCC MAINNET
New RPC URL : https://mainnet-rpc1.gdccoin.io/
Chain ID : 7777
Currency symbol : GDCC
Block explorer URL(Optional): https://www.gdccscan.io/

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by salimtb** [comment]
fixed
