### ISSUE TITLE
[Bug]: Same NFT can be added twice if using integer and hex value for the token id

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#18957]
### Describe the bug

**Problem**: I can add the same NFT twice if I add the id as an integer, and as a hex value.
Notice, for the NFT with the hex value id, we see always the hex value until the Send Confirmation screen, where we see it transformed as an integer.

https://user-images.githubusercontent.com/54408225/235699951-c17c35ef-cb08-4748-9bcf-e8bf39aa2d9c.mp4

### Steps to reproduce

1. Go to test dapp
2. Deploy Collectibles
3. Mint the NFT with id `577`
4. Go to wallet
5. Click Import NFT
6. Add token contract and id `577`
7. See token is added
8. Click Import Nft
9.  Add token contract and id `0x241`
10. See token is added, we have now 2 tokens which are the same

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by CodeMongerrr** [comment]
I want to work on this issue. Can you provide a head start, as where should I look into
