### ISSUE TITLE
Current account checkmark is not updating

### ISSUE THREAD

**Issue by phra** [MetaMask/metamask-extension#1895]
Hi,

i'm reporting an UI bug. when you switch account in metamask the checkmark in the dropdown menu is not updating.
as you can see in the screenshot `Account 2` is selected but the checkmark is on `Account 1` that was the previous one.

![screenshot from 2017-08-10 10-28-49](https://user-images.githubusercontent.com/984628/29161638-4cbf657a-7db7-11e7-9c67-860436462f97.png)

**Comment by sdtsui** [comment]
This should be fixed in #1899 and rolled out shortly.

/cc @Zanibas , in case we have a different process (i.e. don't close until it's in `master`).

**Comment by phra** [comment]
:rocket:
