### ISSUE TITLE
Screen shift when going from Send/Swap to wallet screen

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#18966]
## Bug Description
In fullscreen, when you go from Send or Swap back to main wallet screen, a subtle shift happens. (video attached).
https://images.zenhubusercontent.com/42009758/07a110f8-b704-4c3a-898b-04ffacc3984d/screen_recording_2023_05_02_at_1_18_00_pm.mov

**Comment by SaraCheikh** [comment]
@kevinghim I can see in your recording that the header and the logo change their position from one screen to another, but I can't reproduce it, the only problem to me is how the swap and screen look like a modal and they are too close to the the header, but that is a current problem we have too. 

https://images.zenhubusercontent.com/42009758/25098f1d-85f2-42ac-a830-f8b1b9a315b0/screen_recording_2023_05_03_at_11_43_59.mov
