### ISSUE TITLE
Usability regression in the new accout listing

### ISSUE THREAD

**Issue by miohtama** [MetaMask/metamask-extension#1896]
Expected Behavior: It is easy to identify account by its Ethereu address

Actual Behavior: The latest update made the account list very small, showing only the account names and missing the actual address. Now it is very hard to figure out which address belongs to which account. This causes issues for multi account users.

Browser Used: Chrome

Operating System Used: OSX

![image](https://user-images.githubusercontent.com/49922/29171297-ba1c0c40-7de4-11e7-8971-3b0de1445661.png)

**Comment by flyswatter** [comment]
It should be easy enough to have a few characters of the address on the right, maybe less bold.

**Comment by miohtama** [comment]
I usually use the four first characters to identify, then double check :)

**Comment by kumavis** [comment]
btw @miohtama remember you can change the label on your accounts
