### ISSUE TITLE
Infinite spinner when trying to connect to Arbitrum

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#18970]
## Bug description
After adding Arbitrum and trying to connect to it, I get an infinite spinner and eventually "Something went wrong" error message. 

![Screenshot 2023-05-02 at 1.09.45 PM.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/30f3ab4d-a08e-474f-80bc-05d51da62907)

![Screenshot 2023-05-02 at 1.09.52 PM.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/3a118ae6-d04a-42d5-9a68-c23fd54f828a)

This could be related to https://github.com/MetaMask/MetaMask-planning/issues/398

**Comment by SaraCheikh** [comment]
there is more issues related to network connection fail in this ticket: https://app.zenhub.com/workspaces/extension-client-team-63529dce65cbb100265a3842/issues/gh/metamask/metamask-extension/18984

**Comment by kevinghim** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/18984
