### ISSUE TITLE
Network connection fail UI fixes 

### ISSUE THREAD

**Issue by SaraCheikh** [MetaMask/metamask-extension#18984]
### Switch networks takes user to old Network List

- When a Network fails to connect, user is prompted to "try again" or switch network" this alst option takes them to the old placement and UI of the Network List

Build

https://images.zenhubusercontent.com/42009758/dcd6d8c8-5ab0-4c78-a521-8de6ab4e0efb/screen_recording_2023_05_03_at_12_00_24.mov

Design 

![Screenshot 2023-05-03 at 12.26.16.png](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/45bc25d1-4ec8-4b59-99a7-d30641fc9869)

-The alert message appears floating in the overlay. Suggestion is to update this error to use a Modal alert. 

Build
![Screenshot 2023-05-03 at 18.42.49.png](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/ecdd2779-cb1c-4b07-9599-934d1e5e82ca)

Design
![Screenshot 2023-05-03 at 18.42.44.png](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/9a7a7348-ae5b-40aa-942b-985df435c2bd)

### Linea Goerli Test network fails to connect

- When clicking on Linea, the modal disappears and the previous network remains connected instead of switching networks

https://images.zenhubusercontent.com/42009758/6f876065-1f8f-4a9f-a29a-834c542697e2/screen_recording_2023_05_03_at_12_34_08.mov

**Comment by kevinghim** [comment]
Consider making the "Something went wrong" into a popover.
