### ISSUE TITLE
[Bug]: LavaMoat - property "Proxy" of globalThis is inaccessible under scuttling mode

### ISSUE THREAD

**Issue by Chen120322** [MetaMask/metamask-extension#19018]
### Describe the bug

 Error: LavaMoat - property "Proxy" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360

### Steps to reproduce

1.
This occasionally occurs when unlocking your wallet

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello @Chen120322. Do you remember doing any other specific steps when this issue occurred? Could you send a screenshot of your console logs when this issue occurs? You can click right and then select 'Inspect' in the extension pop-up, then go to the Console tab, take a screenshot of the logs from there, and send it to us. Thank you!

**Comment by iAgonyii** [comment]
I'm having the same problem right now on versions 10.29.0 and 10.28.3. It only started happening today, potentially because of an update to Google Chrome?

I am using MetaMask in a browser profile controlled by Selenium, and whenever I try to locate an element within MetaMask the following error is thrown:

```
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.callFunctionOn threw exception: Error: LavaMoat - property "JSON" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
  at get (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11200:17)
```

**Comment by iAgonyii** [comment]
https://github.com/MetaMask/metamask-extension/issues/17834#issuecomment-1532875253
Same issue here

**Comment by Randersun** [comment]
I am having this problem as well

**Comment by wxhncepu** [comment]
Is there a solution? I have the same problem

**Comment by vighneshck** [comment]
Hi all,
I seem to have a very noob question...
I tried following the steps on https://stackoverflow.com/questions/76252205/runtime-callfunctionon-threw-exception-error-lavamoat-property-proxy-of-gl/76256257#76256257

But I am unable to find the index.js file in the root folder... could someone help me with this?

**Comment by brianonchain** [comment]
> Hi all, I seem to have a very noob question... I tried following the steps on https://stackoverflow.com/questions/76252205/runtime-callfunctionon-threw-exception-error-lavamoat-property-proxy-of-gl/76256257#76256257
> 
> But I am unable to find the index.js file in the root folder... could someone help me with this?

It's under development > build folder

**Comment by weizman** [comment]
Here's everything you need to know on why you see this error and how to address it 
https://github.com/LavaMoat/LavaMoat/pull/360#issuecomment-1547726986 cc @anaamolnar

**Comment by archanabaral** [comment]
i am still facing the same error while using MetaMask controlled by Selenium, and whenever I try to locate an element within MetaMask the following error is thrown: selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.callFunctionOn threw exception: Error: LavaMoat - property "Proxy" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.                                                                                                            at get (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/runtime-lavamoat.js:13190:11)

**Comment by hjetpoluru** [comment]
Unable to reproduce the issue with the Selenium automation tool. Could you please validate and let us know if this is still an issue. Due to the ticket was open for longer time, hence it has been stale and closing the ticket. If there are findings please reopen the ticket as needed.
