### ISSUE TITLE
Copy to Clipboard showing incorrect address in upgraded metamasks

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#1901]
Like it says. Need steps to reproduce though.

**Comment by sdtsui** [comment]
@Zanibas thanks for reporting.  

I can take a look this afternoon: does the incorrect copied address always stay the same?  Might be something else, but I was concerned about this when implementing.

For example, if a user has 3 accounts, and they try to copy the address from the 3rd, they only check the 1st account.

If that's an accurate description of the bug, I think it has to do with the 2nd half of an address check: it defaults to `accounts[0]`.

**Comment by Zanibas** [comment]
In this case, it seems the shown address is a token address?

**Comment by sdtsui** [comment]
@Zanibas any word on repro instructions? I remember trying this but getting pulled away to another meeting before updating. 

Here's the `.gif` again.

![extension-clipboard](https://user-images.githubusercontent.com/8230144/29283177-cfe9e90e-8125-11e7-83b9-8d9958a25f28.gif)

Shows 3 accounts (#1899 fixes the squishing + checkbox issues), each of them with correct "copy to clipboard" functionality.

**Comment by kumavis** [comment]
seems more likely to be user error or somehow copy failed and the clipboard was unmodified

**Comment by armstid** [comment]
Hey guys. Just wanted to let you know that it still does it. I emptied cache in Chrome. Deleted cookies. Ran a Java command to clear my clipboard. That address always comes back. My real question is, should I finally bid a fond farewell to all that beautiful and cheap DNT?

Thanks,

Ben
