### ISSUE TITLE
[Bug]: Other plugin injection

### ISSUE THREAD

**Issue by eliomain** [MetaMask/metamask-extension#19024]
### Describe the bug

How to solve the problem of mandatory injection of okx wallet by modifying window. ethereum, which causes metamask to fail to start normally

### Steps to reproduce

1.

### Version

new

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by eliomain** [comment]
Related to #14737

**Comment by anaamolnar** [comment]
Hello @eliomain, I am sorry to hear you are experiencing issues with our product. For a workaround for this issue, please read the [following knowledge base article](https://support.metamask.io/hc/en-us/articles/11907107168923)! Please let us know if the issue is still pending after doing so.
