### ISSUE TITLE
bug report when signing message

### ISSUE THREAD

**Issue by scott-lew-is** [MetaMask/metamask-extension#1903]
-Expected transaction options to complete display in pop-up window when submitting order on etherdelta
-Pop-up dialogue was wider than pop-up box
-Chrome
-Windows

-note: first day this has happened, has worked well in the past.

![image](https://user-images.githubusercontent.com/29188624/29230699-ae138c46-7ea9-11e7-834f-a46d186ff8cf.png)

**Comment by kumavis** [comment]
this screen is used by metamask's most popular dapp - bumping the priority
