### ISSUE TITLE
[Bug]:  Not sure how to describe it....

### ISSUE THREAD

**Issue by Offline-R503B** [MetaMask/metamask-extension#19031]
### Describe the bug

I expect my wallet to function and not corrupt and reset itself every few hours, seems to be the basic functionality of the the product or at least the intended so color me surprised that I've had this issue multiple times in a year.

### Steps to reproduce

1. Create an account and reopen the wallet 2 hours later, TADA money gone , wallet gone. (Uhhh you should save your phrase bla bla bla, Yeah sorry for expecting the product to work for longer than a day 😅 )

This stuff and the basic lack of any security and shoveling the responsibility to the user saying "uuhh self custody"), makes me wonder if there is any intention of making this a serious product or if this is just a hobby MIT project. 

### Version

All

### Build type

None

### Browser

Microsoft Edge

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello @Offline-R503B. Thanks for reaching out!  I am sorry to hear that. Do you remember doing anything specific before this happened?  Could you please provide more context about what "money gone, wallet gone" means? Do you no longer see the extension in your browser? What browser are you using your Metamask with? What Metamask version were you using? Thank you!

**Comment by Offline-R503B** [comment]
Edge, the extension resets itself. Latest.

**Comment by danjm** [comment]
@Offline-R503B would you able to capture and share a video of what happens when you try to open metamask?

**Comment by Offline-R503B** [comment]
> @Offline-R503B would you able to capture and share a video of what happens when you try to open metamask?

Not sure what is not clear in my report. No I wont be able to as I uninstalled and I do not plan to install again. Multiple times I lost money with this MIT hobby project.

And now the current news that you apparently can access it when you need it for tax purposes? Disgusting. Really baffled.
