### ISSUE TITLE
[Bug]: 小狐狸钱包 报错（批准 USDC 支出上限）（链 ID 324 不可使用交易解码）如果解决

### ISSUE THREAD

**Issue by fuyibin02** [MetaMask/metamask-extension#19043]
### Describe the bug

小狐狸钱包 报错（批准 USDC 支出上限）（链 ID 324 不可使用交易解码）如果解决

### Steps to reproduce

1.
![微信图片_20230508122829](https://user-images.githubusercontent.com/132870291/236734082-e61aad39-0aed-413d-8f88-d2e9cb11f22c.jpg)
![微信图片_20230508122837](https://user-images.githubusercontent.com/132870291/236734087-4486280f-89ee-470e-b297-02e25f2e1029.jpg)

### Version

MetaMask 版本 10.29.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Windows

**Comment by anaamolnar** [comment]
Closing in favor #19044.
