### ISSUE TITLE
Improve UI for transaction decoding feature for non-supported networks

### ISSUE THREAD

**Issue by fuyibin02** [MetaMask/metamask-extension#19044]
### Describe the bug

Fox Wallet reported an error (ap
![微信图片_20230508122829](https://user-images.githubusercontent.com/132870291/236734622-8e58c319-877a-474d-a072-49ad26c9cd80.jpg)
![微信图片_20230508122837](https://user-images.githubusercontent.com/132870291/236734630-51a5ab1c-2475-4c51-828b-f43f08041621.jpg)
proved USDC spending limit) (chain ID 324 cannot be decoded by transaction) if resolved

### Steps to reproduce

1.

### Version

MetaMask 版本 10.29.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Windows

**Comment by bschorchit** [comment]
Hey @fuyibin02, thank you for your report! Zksync network is not supported yet by our Transaction data feature. That's why you're seeing this error message there. 
I've marked this as a feature request to support more networks or improve the UI for non-supported networks.
