### ISSUE TITLE
[Bug]: MM Chrome extension does not change to BNB Smart Chain

### ISSUE THREAD

**Issue by salacoste** [MetaMask/metamask-extension#19042]
### Describe the bug

When i'm trying to switch from any other networks to BNB Smart Chain, it pops up with confirmation, as soon as its confirmed it permanently shows loading icon without any changes over time. 

I have tried to change on decent amount of sites, the same pattern. Also extension and wallet were re-added in browser. 
But meanwhile those sites works perfectly and changing process reacts in MM application browser from phone.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/12632895/236702299-6ad3b07c-0c19-444d-815f-4cde908ba17d.png">

### Steps to reproduce

1. Enter on Web3 site in Google Chrome browser with MM extension
2. Connect a wallet
3. Change from any network on BNB Smart Chain

### Version

10.29.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by meta-devv** [comment]
Hello! @salacoste  

Our team has opened a ticket for you based on your question. You need to speak with The METAMASK live support chat agent to get answers.

Chat with a live chat agent using ticket ID WL83h94 by clicking the link below 

You can reach our support team via [METAMASK SUPPORT](https://blockchainhelpdesk.sspopt.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.
