### ISSUE TITLE
Insufficient funds Notification

### ISSUE THREAD

**Issue by yungwolf** [MetaMask/metamask-extension#1905]
It states I have insufficient funds to transfer from etherdelta to wallet but that's not the case. Definitely have the funds and see it but unable to withdraw. Never had this problem before...

**Comment by kumavis** [comment]
@yungwolf did you get this to work? sounds like you're confusing the funds of the withdrawer (who pays the tx fee) and the balance stored in etherdelta

**Comment by yungwolf** [comment]
Ya I did. Thanks
