### ISSUE TITLE
[Bug]: Calling `eth_requestAccounts` hangs after the first rendering on a Chrome browser

### ISSUE THREAD

**Issue by AtelyPham** [MetaMask/metamask-extension#19112]
### Describe the bug

When a user first opens the app, I use `ethereum.request({ method: 'eth_requestAccounts' })` to trigger the Metamask wallet pop-up. This allows the user to enter their password and select the account they want to connect. However, I have encountered an issue where the call seems to hang indefinitely before eventually resolving. This forces me to do a hard reload of the browser to establish the connection.

This issue is not limited to the first use of the app. Even after a successful wallet connection, closing the tab and reopening the app may sometimes result in the same problem occurring again when attempting to connect the wallet.

<details>
<summary>I've attached videos to show the issue</summary>

https://github.com/MetaMask/metamask-extension/assets/60747384/e4dab0db-cc53-47dc-baff-a66a408fac80

https://github.com/MetaMask/metamask-extension/assets/60747384/0ed5f3c4-36d9-416c-be1c-136e45258669

</details>

### Steps to reproduce

1. Create a new Chrome account to simulate a fresh browser.
2. Install Metamask and create an account.
3. Clone the repository by visiting https://github.com/AtelyPham/metamask-request-accounts-test.
4. Run the repository by executing the command `npm install` and then `npm run dev`.
5. Visit http://localhost:3000 and click the `Connect Wallet` button to see the error.

### Error messages or log output

```shell
No error messages or log output in the console
```

### Version

10.30.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Ezeone38** [comment]
[type-bug](https://github.com/MetaMask/metamask-extension/labels/type-bug)

**Comment by yonigoldberg** [comment]
We noticed this issue as well

**Comment by jiexi** [comment]
Hey there, @AtelyPham. Thank you for bringing this to our attention. Could you help us verify something by disabling preloading in your Chrome settings? This can achieved by:
1. Opening settings
2. Searching for "Preload"
3. Toggling the "Preload pages" setting to off

After you do this, are you still able to reproduce the bug you are seeing?

Thank you!

**Comment by CWM2289** [comment]
Turned off preload and still an issue
