### ISSUE TITLE
Migrate components to TS: TextField

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#19127]
### Description
Migrate `TextField` component  in `ui/components/component-library` to TypeScript

Dependencies
- https://github.com/MetaMask/metamask-extension/issues/19239
- https://github.com/metamask/metamask-extension/issues/19122

### Technical Details

- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` (name and keys)
- Ensure enums use singular not plural e.g. `Size` not `Sizes`
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation

### Acceptance Criteria

- Component has been converted to TypeScript
- Stories, documentation and tests have been updated inside of the `component-name` folder
- Before/After screen cast of component stories in storybook to show no visual regression after migration

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with TypeScript and want to contribute to improving the stability of the extension

**Comment by ahmadniaz** [comment]
@georgewrmarshall I want to work on this. Can you please assign this to me?

**Comment by georgewrmarshall** [comment]
Hey @ahmadniaz, there is a dependency on completing this issue https://github.com/MetaMask/metamask-extension/issues/19122 I would suggest working on that first?

**Comment by georgewrmarshall** [comment]
Removing `good-first-issue` label until we close the `Box` dependency https://github.com/MetaMask/metamask-extension/issues/19239

**Comment by dhruvv173** [comment]
hey @georgewrmarshall I've been working on this issue but it seems to be a bit challenging for my knowledge of TS. I'm almost there, just need some assistance from you or @garrettbear if thats possible. Your expertise would be really valuable. Thank you!

**Comment by georgewrmarshall** [comment]
Hey @dhruvv173, this is a complex component so I commend you taking this on. If you'd like to push up a draft PR we would be happy to take a look.
