### ISSUE TITLE
Migrate components to TS: PickerNetwork

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#19124]
### Description
Migrate `PickerNetwork` component  in `ui/components/component-library` to TypeScript

Dependencies
- https://github.com/MetaMask/metamask-extension/issues/19239

### Technical Details

- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` (name and keys)
- Ensure enums use singular not plural e.g. `Size` not `Sizes`
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation

### Acceptance Criteria

- Component has been converted to TypeScript
- Stories, documentation and tests have been updated inside of the `component-name` folder
- Before/After screen cast of component stories in storybook to show no visual regression after migration

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with TypeScript and want to contribute to improving the stability of the extension

**Comment by dhruvv173** [comment]
Hey @georgewrmarshall 
Although I'm new to typescript I'd like to work on this issue. Could you help with assistance whenever possible for you?
Would appreciate it, thanks!

**Comment by surajgjadhav** [comment]
Hi,
if it is not assigned to anyone, can I take this up ?

**Comment by surajgjadhav** [comment]
Oh, seems it has dependency on Box component.
But you can assign it to me once your Box component PR is merged 👍  
Thanks :)

**Comment by georgewrmarshall** [comment]
Thanks @surajgjadhav I'll make sure to go through all these issues once Box has been merged

**Comment by georgewrmarshall** [comment]
Removing `good-first-issue` label until we close the `Box` dependency https://github.com/MetaMask/metamask-extension/issues/19239
