### ISSUE TITLE
Migrate components to TS: TextFieldSearch

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#19128]
### Description
Migrate `TextFieldSearch` component  in `ui/components/component-library` to TypeScript

Dependencies
- https://github.com/MetaMask/metamask-extension/issues/19239
- https://github.com/metamask/metamask-extension/issues/19122
- #19990 
- https://github.com/metamask/metamask-extension/issues/19127

### Technical Details

- Convert Objects in `SNAKE_CASE` to enums in `PascalCase` (name and keys)
- Ensure enums use singular not plural e.g. `Size` not `Sizes`
- Update file name from `component-name.contants.js` to `component-name.types.ts` and add types
- Update file name from `component-name.js` to `component-name.tsx` and add types
- Update file name from `component-name.test.js` to `component-name.test.tsx`
- Update file name from `component-name.stories.js` to `component-name.stories.tsx`
- Update all instances of component objects to enums
- Update all documentation

### Acceptance Criteria

- Component has been converted to TypeScript
- Stories, documentation and tests have been updated inside of the `component-name` folder
- Before/After screen cast of component stories in storybook to show no visual regression after migration

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with TypeScript and want to contribute to improving the stability of the extension

**Comment by nazrul7711** [comment]
hi @georgewrmarshall  i want to work on it

**Comment by georgewrmarshall** [comment]
Hey @nazrul7711, thanks for your interest this issue has a dependency on https://github.com/MetaMask/metamask-extension/issues/19122 to be completed first

**Comment by AliMora83** [comment]
Most interesting 🥳
I would like to help. Please assign this issue to me, I will wait on #19122 first. 👍🏼

**Comment by georgewrmarshall** [comment]
Removing `good-first-issue` label until we close the `Box` dependency https://github.com/MetaMask/metamask-extension/issues/19239
