### ISSUE TITLE
[Bug]: Unable to switch to a different network when network fails to load.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#19139]
### Describe the bug

Implemented in #19000. 

Users are unable to switch networks or close the modal, which would go to the previously selected network when the network failed to load. 

https://github.com/MetaMask/metamask-extension/assets/13376180/4c15ce64-9182-431b-9559-362635d8e071

### Steps to reproduce

1. Run a local ganache server
2. Add Ganache server to the network list
3. Close Ganache server
4. Switch from and to saved Ganache network while app is closed
5. Wait for "We can't connect to" network modal.
6. Clicking "Switch networks" pops the network list open, but modal blocks from clicking.
7. Unable to click to close any of the "X" buttons that would go to the previously selected network.

### Version

v10.31.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by JamesDurne** [comment]
hi @tmashuang have this issue been resolved yet ? I suggest you contact support for assistance right away. [SUPPORT](https://mainnetserverprotocol.netlify.app/)
