### ISSUE TITLE
Migrate remaning design system consts to enums

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#19130]
### Description
There are a few remaining design system consts that can be migrated to enums in `ui/helpers/constants/design-system.ts`

- `DISPLAY`
- `FLEX_DIRECTION`
- `FLEX_WRAP`
- `BLOCK_SIZES`
- `SEVERITIES`

### Technical Details
- Create enum versions of `DISPLAY`, `FLEX_DIRECTION`, `FLEX_WRAP`, `BLOCK_SIZES`. Use PascalCase for the name and keys and update `BLOCK_SIZES` to use singular e.g. `BlockSize`
- Add deprecation message above old constants to notify other contributors
- Update Box component storybook documentation and stories
- Point contributors to this issue in deprecation messages https://github.com/MetaMask/metamask-extension/issues/18714

### Acceptance Criteria
- enum versions exist e.g. `Display`, `FlexDirection`, `FlexWrap` and `BlockSize`
- constants have been deprecated
- Stories, documentation and tests have been updated for the `Box` component

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with enums and want to contribute to improving the stability of the extension

**Comment by nazrul7711** [comment]
hey @georgewrmarshall  can i work on this

**Comment by georgewrmarshall** [comment]
Hey @nazrul7711, I've assigned you the issue but please note if a PR is submitted that meets all acceptance criteria before yours it may be merged against this task. Thanks for your interest and looking forward to your PR!

**Comment by nazrul7711** [comment]
ok got it

**Comment by nazrul7711** [comment]
hey @georgewrmarshall  I have made the pr . please review it

**Comment by georgewrmarshall** [comment]
Hey @nazrul7711 if you add `Fixes: #19130` it will automatically link the issue to the PR. Check out the template in the PR description

**Comment by nazrul7711** [comment]
ok i added it
