### ISSUE TITLE
[Bug]: Changing an ERC20 Send to ETH Send, does not clear Hex Data on the UI Edit screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19140]
### Describe the bug

**Problem**: whenever I am performing an ERC20 Send, if I change the asset to ETH, I can see how the Hex Data field is not empty, and it's displaying the data for the previous ERC20 Send. This should not be the case, and Hex Data should be cleared whenever the asset is changed to ETH.

Notice in practice, this hex data is not submited to the network (which is good) but the UI displays it as if there were Hex Data on the Edit screen.

https://github.com/MetaMask/metamask-extension/assets/54408225/3b0bba4f-3ee5-4609-a092-3a920fa4b10a

### Steps to reproduce

1. Enable Hex Data from Advanced Settings
2. Import an ERC20 toekn
3. Click Send ERC20 token
4. Add recipient
5. Add amount and click Next
6. Click Edit
7. Change asset for ETH
8. See how Hex data is not empty - it should be

### Version

10.30.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by salimtb** [comment]
hey @seaona ,
thank you for reporting this bug, however I tried to reproduce on my side but I can't (watch the video below), am I missing something ?

https://github.com/MetaMask/metamask-extension/assets/26223211/ab9b426a-42bf-4f4d-8087-533381e595b2

**Comment by salimtb** [comment]
finally i was able to reproduce this bug, be sure to activate the Show hex data toggle from your settings
