### ISSUE TITLE
[Bug]: Removed Multi-transaction Support

### ISSUE THREAD

**Issue by beetle-dude** [MetaMask/metamask-extension#19162]
### Describe the bug

We run a high-traffic web3 gaming site and allow users to queue up multiple transactions at once so they don't have to wait until each transaction fully processes before approving the next one in the list. This transaction batching is present in quite a few areas of our game and the most recent update (10.30.2) appears to lock users down to a single pending transaction at a time. This is extremely limiting and has caused quite a few user complaints. If at all possible, it would be extremely beneficial to reinstate the previously functional behavior.

### Steps to reproduce

1. Attempt to queue two transactions at the same time (multiple clicks of a transactional button)
2. View the subsequent transactions fail with the following error message: _RPC Error: Request of type 'transaction' already pending for origin <>. Please wait._

![Screen Shot 2023-05-15 at 5 13 55 PM](https://github.com/MetaMask/metamask-extension/assets/91798136/ca9f4fae-fdf6-42c2-9d6c-522cd80b343a)

### Version

10.30.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Gudahtt** [comment]
Thanks for the report! We are preparing a new release now that will fix this issue.

**Comment by danjm** [comment]
@beetle-dude I believe there is a workaround for your users. It seems that this bug prevents our notification window from being refocused after subsequent clicks to create a transaction, and an error message is passed back to your dapp, but those transactions are still created. So the workaround is for the user to toggle to the open notification window, or click the fox in the top right corner of the browser.

See the attached video for an example

https://github.com/MetaMask/metamask-extension/assets/7499938/01484128-be7f-4cb1-b4a9-2cb39b0d0c0a

**Comment by beetle-dude** [comment]
@danjm excellent, really appreciate the quick turnaround and work-around info. I'll connect with our QA team to share the interim solution while we wait for the updated extension release 🙇
