### ISSUE TITLE
[Bug]: sometimes the connection doesn't work

### ISSUE THREAD

**Issue by almoapple** [MetaMask/metamask-extension#19165]
### Describe the bug

After I used uniswap to connect to MetaMask, then I closed the page and reopened the page, sometimes I couldn’t connect.
Then I execute the following code in the console:
const provide = new _ethers.providers.Web3Provider(window.ethereum)
provide.provider.request({ method: ‘eth_chainId’ }).then((data) => console.log(data))
I found that this request is still in pending. I speculate that there is a problem with the execution of js injected by MetaMask.
I also tried other web3 websites, and this problem also occurs.

[https://community.metamask.io/t/bug-about-connect-issue/25583](url)
you can see  some screen shot in this issue

### Steps to reproduce

1. connect to a web3 website，such as uniswap\gmx
2. close the website after connected
3. open a new label，visit the connected site. 
This problem is not inevitable, it takes multiple attempts. and do not open the console when open the site.

### Error messages or log output

```shell
no
```

### Version

10.30.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by smalljiucai** [comment]
https://github.com/MetaMask/json-rpc-middleware-stream/pull/47

The plugin [json-rpc-middleware-stream](https://github.com/MetaMask/json-rpc-middleware-stream) had fix this problem in 4.2.2, and when metamask-extension update to 4.2.2 from 4.2.1 ?
