### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#19183]
### Describe the bug

- Metamask is returning an integer when calling eth_getTransactionCount instead of a hex string
- Based on different case for the address, it return eith the cache result or not

![Screenshot_20230517_103110](https://github.com/MetaMask/metamask-extension/assets/790580/49f116d7-6f22-4896-a1c2-9a6fa505daaa)

### Steps to reproduce

1. call eth_getTransactionCount
2. eth_getTransactionCount with different case after relaunching a network, see : https://github.com/MetaMask/metamask-extension/issues/12211#issuecomment-1534956709

### Version

10.30.2

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by wighawag** [comment]
Seriously, your bot is not helping you

This issue definitely highlight some more important issue in your code base :(

**Comment by vandan** [comment]
[Related PR](https://github.com/MetaMask/metamask-extension/pull/14822) - the issue is that fixing this would result in a breaking API change.

**Comment by vandan** [comment]
Duplicated by https://github.com/MetaMask/metamask-extension/issues/5845
