### ISSUE TITLE
[Bug]: False Suspicious Report for Token ICO 

### ISSUE THREAD

**Issue by hollywoodxpepe** [MetaMask/metamask-extension#19195]
### Describe the bug

![wcw](https://github.com/MetaMask/metamask-extension/assets/133406094/cdfcfe45-d398-4674-ba98-d92447bd8436)

### Steps to reproduce

1. Was reported by community member,
2. https://hollywoodxpepe.com

### Version

10.30.4

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by bschorchit** [comment]
Hey @hollywoodxpepe , thank you for your report. This should have been fixed, let us know if it happens again. Ty!

**Comment by anaamolnar** [comment]
Hello, @hollywoodxpepe! Thanks for reporting! I am closing this issue as this has been fixed now. Please feel free to re-open this or open a new issue if this is not the case. Thank you!
