### ISSUE TITLE
ZRX Token sale Issues

### ISSUE THREAD

**Issue by g00per** [MetaMask/metamask-extension#1919]
I purchased some ZRX tokens this morning, but I got failed transaction alerts. One of the purchases went through and shows via etherscan. I can't add ZRX as a token, and when I go to myetherwallet to check, it continuously says loading for all coins. I only did a small test amount for this reason, but I'd like to purchase more if I know its working. 

![failed](https://user-images.githubusercontent.com/31047652/29333385-3661322a-81c9-11e7-8337-5ee5771303db.JPG)

**Comment by tmashuang** [comment]
Does the screenshot contradict what etherscan says the status of the transaction is? If not, what is the failed transaction say when hoving over the red "failed" text?

Sorry, our token list is a little brittle right now, and our backend is a bit overloaded with people like yourself trying to add their new 0x/ZRX tokens.

Try connecting to a local node, or just waiting a few hours until this traffic has relieved a bit.

**Comment by kumavis** [comment]
@g00per please send us state logs https://github.com/MetaMask/faq/blob/master/LOGS.md#ui-state-logs-chrome

**Comment by g00per** [comment]
Thank you for the quick response. It started to work eventually, even though the failed alerts still showed. I waited several hours just in case, but it just took a little longer. Thank you for the help

ab absurdo
