### ISSUE TITLE
[Bug]: the gas price is not updated when sending transaction

### ISSUE THREAD

**Issue by robinsdan** [MetaMask/metamask-extension#19221]
### Describe the bug

we send transaction using metamask on an no eip1559 network, it always failed with `underprice` error. 
we find out:
1. the gas price metamask provided is much lower than we get from the rpc node using `eth.gasPrice`;
2. the gas price metamask provided is not refreshed, seems it used a cached value;
3. If we clear all activity and nonce data from the advanced setting, and send transaction again, it will provide gas price the same as we get from rpc node using `eth.gasPrice`, and the transaction will send without `underprice` error.

### Steps to reproduce

1. see above

### Version

10.30.4

### Build type

None

### Browser

Microsoft Edge

### Operating system

Windows

**Comment by Sandeep-help** [comment]
Hello @robinsdan .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://blockchainhelpdesk.sspopt.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by anaamolnar** [comment]
Hello, @robinsdan! Thanks for reporting! Could you please let me know which network you are trying to perform the transaction on and are getting this result? Thank you!

**Comment by robinsdan** [comment]
@anaamolnar Goshen network is a layer2 project based on Ethereum, you can use the https://bridge.goshen.network/ to bridge some goerli  ETH to this network, and then try send some transactions.
