### ISSUE TITLE
T[Bug]: Transactions stuck in 'Pending' state when using MetaMask on Avalanche Fuji Testnet

### ISSUE THREAD

**Issue by tenax002** [MetaMask/metamask-extension#19223]
### Describe the bug

I am encountering an issue while using MetaMask to execute transactions on the Avalanche Fuji testnet. All transactions initiated from my application remain in a 'Pending' state and are not being submitted, resulting in the absence of a transaction hash. However, when I use the core wallet, transactions go through successfully.

I have performed the following steps to troubleshoot the problem:

Verified gas price: I ensured that I set an appropriate gas price for the transactions.
Sufficient funds: I confirmed that my account has enough funds to cover any transaction fees.
Despite these precautions, the transactions are still not getting submitted and remain stuck in the 'Pending' state.

Any assistance or guidance on resolving this issue would be greatly appreciated.

### Steps to reproduce

1. Place an approval transaction

### Version

10.30.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Sandeep-help** [comment]
Hello @tenax002 .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://blockchainhelpdesk.sspopt.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by anaamolnar** [comment]
Hello, @tenax002. Thanks for reporting! By application, could you tell me if you're referring to the Metamask mobile application versus the extension? Could you send a short screen recording of this, if it is not too much to ask? Thank you!

**Comment by anaamolnar** [comment]
Hello, @tenax002! It seems that you have other queued transactions. If the pending transactions are not present on the blockchain explorer and are just stuck locally, you will need to go to Settings->Advanced and click on **Clear activity tab data** to clear up your transaction queue. This is currently blocking your ability to perform any transactions. Please note that your activity history will disappear from the queue. 
After clearing up the queue, could you please try again with 'Market' gas and let me know if the issue continues to occur? Thank you!

**Comment by danjm** [comment]
@tenax002 Are you still experiencing problems with the application you are trying to integrate with MetaMask?
