### ISSUE TITLE
[Bug]: Transaction will automatically fail if using the default gas settings

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-extension#19224]
### Describe the bug

When initiating a transfer on Polygon, it will automatically default to "Advanced" gas settings with very low gas values (approx. 1.5 GWEI, default gas limit:21000). The transaction will automatically fail in the wallet due to low gas. The default settings in the send flow should be Market value and the more experienced users could choose Advanced values.

![gif123](https://github.com/MetaMask/metamask-extension/assets/82837486/9b5c61e9-1168-4576-91e6-ed2ee7571b17)

### Steps to reproduce

1. Go to Polygon Mainnet
2. Initiate a transfer to a different address
3. Click next to the second confirmation screen.
4. Gas settings will default to advanced
5. If you Confirm the transaction with the default "Advanced" gas, the transaction will fail instantly in the wallet.

### Version

10.30.4

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by bschorchit** [comment]
Possibly related with https://github.com/MetaMask/metamask-extension/issues/13800
