### ISSUE TITLE
Create TS version of Box component in component-library

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#19239]
### Description
Currently the `Box` component is still a javascript component that lives in the `ui/components/ui` folder. This isn't very intuitive for engineers using the `Box` component as they have to import from 2 different places. It also effects CSS of other components because the specificity of the current Box component CSS is higher than the `ui/components/app` components

It would make sense to create a new TypeScript version of the `Box` component and deprecated the old one. That way engineers can import every component from the `component-library` folder and styles from the `Box` component won't override styles from the `app` components

### Technical Details
- Build a TypeScript version of the `Box` component in the `component-library` folder

### Acceptance Criteria
- There is a TypeScript version of the `Box` component in the `component-library` folder

**Comment by spiritanand** [comment]
Hey @georgewrmarshall,
I would love to get my hands dirty in this `TS` transition. Please assign this to me :)
