### ISSUE TITLE
Transaction Failure not being caught properly

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#1923]
![2017-08-15 19 33 24](https://user-images.githubusercontent.com/1840057/29339829-fbdc852a-81d0-11e7-8e19-8b3d2f163bdd.png)

**Comment by kumavis** [comment]
i think that means it got an error for all 5 retries, and died with the error of the last retry
the json parse error is that infura delivers html on its load shedding

**Comment by kumavis** [comment]
on the call today we decided that we should catch the error and display a more contextual error like "failed to submit to network - please retry the tx again later"
