### ISSUE TITLE
[Bug]: ios app slowing and heating up my phone 

### ISSUE THREAD

**Issue by Samiful** [MetaMask/metamask-extension#19241]
### Describe the bug

Hello, i use an iphone X, the problem is every time i launch MetaMask, it begins normally but starts slowing down my phone and the phone heating up till the point it’s non-usable, and i shut everything down

The battery is drained really fast through this process, and what ever i do on my phone next is really slowed down from the normal use

### Steps to reproduce

1. Use iphone X
2. Install Metamask
3. Connect to multiple network
4. Add different wallets
5. Open multiple tabs and connect your wallet to

### Version

Metmask v6.3.0 (1095)

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

### Additional context

Iphone X (iOS app)

**Comment by georgewrmarshall** [comment]
Hi @Samiful, thanks for creating an issue but this is the MetaMask Extension code repository. Would you mind opening this issue on MetaMask Mobile repo https://github.com/MetaMask/metamask-mobile/issues. Thanks
