### ISSUE TITLE
[Bug]: Does not show current version before logging in

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#19249]
### Describe the bug

Let's assume there is a known security issue with a certain MetaMask version.
Currently I can not see the version which is currently installed unless I login.

### Steps to reproduce

1.Open Metamask Plugin - no version information visible
2. I need to login into a version which I do not know if I can trust it

### Version

10.30.4

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

Easy fix : just display the version at the bottom always / as soon as MM opens.

**Comment by thebinij** [comment]
Hi @SvenMeyer, I wonder why don't we just use manage extensions to the current version? 

https://github.com/MetaMask/metamask-extension/assets/93417120/7a5665a8-a8c3-48bd-a636-5f406b5cf850

**Comment by anaamolnar** [comment]
Hello, @SvenMeyer. Thanks for reaching out! You can see the current version you have installed by right-clicking on the Metamask pop-up and clicking on 'Manage extension'. I will go ahead and close this. Feel free to submit another ticket if you encounter any other issues.
