### ISSUE TITLE
Metamask Extension - make blockaid error / warning component configurable

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#19257]
## Background
As part of the [task](https://app.zenhub.com/workspaces/confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-planning/558) React component will be developed to show errors / warnings returned by blockaid.

As part of this task we will make the error / warnings messages configurable. The message will depend on the error string returned by blockaid:

### 🖌️ Warning main content:
The content of each warning should follow the logic below:

#### 1️⃣ Case 1: Blockaid's PPOM codename response is _raw_signature_farming_:
**[title]** This is a suspicious request
**[body copy]** If you approve this request, you might lose your assets. 

#### 2️⃣ Case 2: Blockaid's PPOM codename response is _approval_farming_ or _set_approval_for_all_farming_ or _permit_farming_:
**[title]** This is a deceptive request
**[body copy]** If you approve this request, a third party known for scams might take all your assets. 

#### 3️⃣ Case 3: Blockaid's PPOM codename response is _transfer_farming_ or _transfer_from_farming_ or _raw_native_token_transfer_:
**[title]** This is a deceptive request
**[body copy]** If you approve this request, a third party known for scams will take all your assets.  

#### 4️⃣ Case 4: Blockaid's PPOM codename response is _seaport_farming_:
**[title]** This is a deceptive request
**[body copy]** If you approve this request, a third party can steal your assets listed on OpenSea. 

#### 5️⃣ Case 5: Blockaid's PPOM codename response is _blur_farming_:
**[title]** This is a deceptive request
**[body copy]** If you approve this request, a third party can steal your assets listed on Blur. 

#### 6️⃣ Case 6: Blockaid's PPOM codename response is _unfair_trade_ or _other_:
**[title]** This is a deceptive request
**[body copy]** If you approve this request, you might lose your assets. 

### 🖌️ Warning secondary content:
In all cases above, the expandable part of both warnings should contain the following raw data provided by Blockaid's PPOM response: _reason_, _description_, _args_ (this should displayed within the description), _features_ and _score_.

Format:

> _reason_
> - _description_ + _args_
> - _features_
> - This has been rated a risk score of _score_.

Example:
<img width="244" alt="Screenshot 2023-05-05 at 09 16 04" src="https://user-images.githubusercontent.com/34968356/236455253-3cae2504-20a5-4e0d-9e66-a710f960ffaa.png">

## References
- [Figma file](https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?node-id=5485-37007)
- [Design issue discussion](https://github.com/metamask/metamask-planning/issues/396)
- [PPOM Validation schema and attack types](https://wobbly-nutmeg-8a5.notion.site/PPOM-Validation-Schema-Attack-Types-555e7f6a5b6c4b6caa9ced59561c8667)
- [Intro to component library for an extension engineer](https://www.notion.so/Extension-Engineer-8da34c7887fe4f2182305a5d576d199c?pvs=4)
- [BannerAlert docs](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-banneralert--default-story)

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/19257?planning-poker) with Zenhub @blackdevelopa @seaona @digiwand @jpuri

**Comment by bschorchit** [comment]
Refinement note: e2e tests are not part of the scope of this issue and will be covered in other issue (to be created)

**Comment by digiwand** [comment]
Had a blocker with the schema request and further discussion about supporting i18n. I can start on this today or tomorrow. 

We have discussed that the features list will not initially support i18n. We plan to add i18n support after MVP. [Slack thread](https://consensys.slack.com/archives/C04D224QTLM/p1688040762380539)

**Comment by digiwand** [comment]
Added a related question to [Design Issue discussion](https://github.com/metamask/metamask-planning/issues/396) here: https://github.com/metamask/metamask-planning/issues/396#issuecomment-1636095271
