### ISSUE TITLE
web3 deprecation notice is spammy

### ISSUE THREAD

**Issue by macbem** [MetaMask/metamask-extension#1926]
Could anyone provide me a bit more insight what I'll have to change in my Dapp using web3 w/ Metamask because of the deprecation?

If I understand the release notes correctly, I'd just have to remove all sync web3 calls (which, for now, are only `web3.eth.accounts` checks) from my Dapps, right? Correct me if I'm wrong please.

Also, it'd be nice to limit the warning to one appearance per page view - right now, my console is all lit up with this deprecation warning from Metamask.

**Comment by phra** [comment]
i'm trying to upgrade right now but after the migration i got this [error](https://github.com/ethereum/web3.js/issues/940):

![screenshot from 2017-08-16 14-05-22](https://user-images.githubusercontent.com/984628/29362394-20e418e0-828c-11e7-9f05-e0f4fd5ea9da.png)

**Comment by macbem** [comment]
You might want to try switching to another network and back to the network you were using.

**Comment by phra** [comment]
@macbem thanks for the suggestion but it's not working.

**Comment by kumavis** [comment]
@phra your error sounds like a legitimate issue but its unrelated to this one -- please open a new issue

**Comment by kumavis** [comment]
- should only show notice once per session
- should **only** show deprecation if dapp accesses something **besides** `web3.currentProvider`
