### ISSUE TITLE
Permissions and signature metrics e2e tests

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#19261]
Technical planning and ticket breakdown for https://github.com/MetaMask/metamask-extension/issues/17444

## Events to test

Permissions Approved
Signature Approved

(we should already have tests that do both actions)

## How do we test those events?

We can use the pattern used previously on `test/e2e/tests/metrics.spec.js` and `test/e2e/mv3/service-worker-restart.spec.js`

**Comment by danjm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Extension-Client-Team-63529dce65cbb100265a3842/issues/MetaMask/metamask-extension/19261?planning-poker) with Zenhub @DDDDDanica @PeterYinusa @pedronfigueiredo
