### ISSUE TITLE
[Bug]: Flagging contract as suspicious

### ISSUE THREAD

**Issue by toshiSat** [MetaMask/metamask-extension#19260]
### Describe the bug

Hey, I'm with Asymmetry Finance and our SafEth contract (https://etherscan.io/address/0x6732efaf6f39926346bef8b821a04b6361c4f3e5) is being flagged as suspicious.

Our website is here https://www.asymmetry.finance/

I was wondering what we could do to prevent that from happening.

Thanks!

### Steps to reproduce

1.  Try to stake through our app
2.  Some wallets will display `This has been flagged as potentially suspicious`

### Version

10.30.4

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by bschorchit** [comment]
We were not able to reproduce this. Could you confirm it's still happening, @toshiSat? 

![image (12)](https://github.com/MetaMask/metamask-extension/assets/34968356/67169c2b-66b7-439c-b33b-691e6c319630)

**Comment by bschorchit** [comment]
Closing as no response
