### ISSUE TITLE
Snap installed event metric e2e test

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#19262]
Add new file under `e2e/tests/metrics/` folder with the following tests

## Events to test

Snap Installed

## How do we test those events?

We can use the pattern used previously on `test/e2e/tests/metrics.spec.js` and `test/e2e/mv3/service-worker-restart.spec.js`

**Comment by danjm** [comment]
Another example https://github.com/MetaMask/metamask-extension/pull/19837

**Comment by tmashuang** [comment]
Issue with putting the test for `Snap Installation` is that it requires a flask build. Currently, everything under the `test/e2e/metrics` is using a dev/prod builds. Options would be to make an exception for one file (would have to do the same with future snap metrics tests), move the file under `snaps` dir / make a new `metrics` dir under snap, or make a `snaps` dir under `metrics`.
