### ISSUE TITLE
Wallet Created event metric e2e test

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#19266]
Add new file under `e2e/tests/metrics/` folder with the following tests

## Events to test

Wallet created

Onboarding test with the segment component. All parts of this test already exist.

## How do we test those events?

We can use the pattern used previously on `test/e2e/tests/metrics.spec.js` and `test/e2e/mv3/service-worker-restart.spec.js`

**Comment by danjm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Extension-Client-Team-63529dce65cbb100265a3842/issues/MetaMask/metamask-extension/19266?planning-poker) with Zenhub @DDDDDanica @pedronfigueiredo @PeterYinusa
