### ISSUE TITLE
Swaps event metric e2e test

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#19264]
Add new file under `e2e/tests/metrics/` folder with the following tests

## Events to test

Swap Completed

We already have tests for Swaps and already have tests for metrics. This test case can be produced as a combination of those two.

## How do we test those events?

We can use the pattern used previously on `test/e2e/tests/metrics.spec.js` and `test/e2e/mv3/service-worker-restart.spec.js`

**Comment by danjm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Extension-Client-Team-63529dce65cbb100265a3842/issues/MetaMask/metamask-extension/19264?planning-poker) with Zenhub @DDDDDanica @pedronfigueiredo @PeterYinusa
