### ISSUE TITLE
Missing accounts after vault recovery

### ISSUE THREAD

**Issue by davibicudo** [MetaMask/metamask-extension#1927]
Briefly describe the issue you've encountered
  *  Expected Behavior
That after recovering the Vault from my seed words, all my account would be there. I had two account created within Metamask, the original plus one created w/ the create account button, and another imported with the private key.
  *  Actual Behavior
Only the first, default account, was recovered from the seed. The other two were missing. Luckily one didn't had anything in it and for the other I still had the private key.
  *  Browser Used
Chrome - Version 60.0.3112.90 (Official Build) (64-bit)
  *  Operating System Used
macOS Sierra 10.12.6 (16G29)

**Comment by kumavis** [comment]
@davibicudo press the "+" button again, the same accounts will be created

**Comment by kumavis** [comment]
this is non obvious and we should auto detect previous accounts at least by ether balance

**Comment by frankiebee** [comment]
duplicate of #654

**Comment by Jamshd** [comment]
Dear sir

My second account is missing. I have pictures from my second account. Can you help me please? my email: jamarenovering@gmail.com

**Comment by tmashuang** [comment]
@Jamshd Assuming that this is after importing a seed phrase, try selecting 'Create Account' to repopulate the addresses in the order which it was created.

**Comment by Jamshd** [comment]
thanks a lot. I found it.

**Comment by gwensarah1** [comment]
Thanks for this, I almost got a heart attack😫
