### ISSUE TITLE
[Bug]: `{ name: TRPCClientError }` error during transaction or signing process 

### ISSUE THREAD

**Issue by parmesh-shiroya** [MetaMask/metamask-extension#19291]
### Describe the bug

Sometimes, users get the `{ name: TRPCClientError }` error when the site calls any method that opens the signing or transaction popup. It doesn't open metamask popup but it throws above mentioned error. error doesn't contain any stack trace or other detail. Just the 'name' key. It only happens sometimes for a few users. Sometimes restarting browser fix issue. And after few minutes it start to happen again. 

We use Wagmi: `0.12.13`.
All users were using Metamask and the Chromium base browser on a desktop.

### Steps to reproduce

it happen when the site initiates a signing or transaction. 
Don't have any exact steps that works every time.

### Error messages or log output

```shell
`{ name: TRPCClientError }`
```

### Version

10.30.4

### Build type

None

### Browser

Chrome, Brave

### Operating system

Windows, MacOS

**Comment by anaamolnar** [comment]
Hello, @parmesh-shiroya.Thanks for reporting! I will pass this on to the team.
