### ISSUE TITLE
there should maybe be a warning when sending ether to yourself

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#1929]
Very minor issue but thought to mention since it happened to me :

I was copy pasting my addresses and then I was thinking I was sending to another of my address. Not seeing any ether coming in the new I was thinking I did something wrong.

Then I realised the original account did not have its ether deducted (apart from the gas but this was not visible) and i could see the transaction in the list.

It turned out I was sending to the sender address :)

I guess an info explanning that you are sending to the same address could help users in that situation

**Comment by kumavis** [comment]
i send txs to myself a lot for QA and sanity checking that a private key works

**Comment by kumavis** [comment]
could still show warning tho :+1:

**Comment by vaibhavchellani** [comment]
@kumavis @wighawag @danfinlay if no one is working on this , can i ?

**Comment by vaibhavchellani** [comment]
@danfinlay how should i display the warning ,i have tried 
return "this.props.dispatch(displayWarning(message))" 
but its not working , showing an error statement would be wrong and also it would disable the send button .

**Comment by anticlimactic** [comment]
It seems this is incomplete. If no one is doing it I would be happy to take it.

**Comment by tmashuang** [comment]
@anticlimactic We have prevented users sending ETH in the New UI. I believe the Classic UI is still able to, which is when this issue was created.
