### ISSUE TITLE
Deprecation of `eth_sign`

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1930]
gradually deprecate `eth_sign`
- [x] include developer deprecation warning (link to `personal_sign` spec and `eth-sign-util`)
- [ ] disallow usage except for known domains e.g. etherdelta, admin.gnosis
- [ ] eventually remove completely

**Comment by Zanibas** [comment]
We will discuss this at our long term planning meet next Tuesday.

**Comment by flyswatter** [comment]
We might want to actually change the current behavior in favor of the `personal_sign` behavior, per [discussion here](https://github.com/ethereum/EIPs/pull/712).

**Comment by bdresser** [comment]
Work done in [this PR](https://github.com/MetaMask/metamask-extension/pull/4117), waiting to merge until EIP 712 is finalized

**Comment by bdresser** [comment]
[EIP 712](https://eips.ethereum.org/EIPS/eip-712) is merged! unblocked ~

**Comment by danfinlay** [comment]
Blocked by us actually implementing EIP 712 per spec.

**Comment by lazaridiscom** [comment]
> Blocked by us actually implementing EIP 712 per spec.

It seems this happened here: #4803

**Comment by danfinlay** [comment]
We have learned that adding a sufficient warning on the signature confirmation screen may have qualified as informed consent, and I would suggest this method no longer requires deprecation as long as we continue to adequately convey its gravity in the languages that we distribute under.

**Comment by lazaridiscom** [comment]
I understand, though I have the feeling here that the Eth Tool-Vendors should (as a whole) adopt the new standards, and deprecate-then-drop the older ones.

Just for the issue processing: doesn't #4803 implement EIP 712, and thus, shouldn't the `T13-blocked` label be removed here? Asking more because I like to understand the current status.

**Comment by danfinlay** [comment]
Correct. This is not blocked, I just am no longer sure it is necessary, as the signing method is in active use, as it's very useful for low-level development and prototyping.

**Comment by lazaridiscom** [comment]
> as the signing method is in active use, as it's very useful for low-level development and prototyping.

I remember a year ago some discussions to flag some functionality as "advanced", thus "power-users" (and developers) can activate it optionally within MM.

Possibly that would be the way to go, to deprecate/remove it for standard-users (default), and allow it only optionally (together with other advanced functionality, for those who need it / know what they are doing). Just thoughts.

**Comment by danfinlay** [comment]
That is one way of tucking it further away, but in my experience, this would just result in some applications instructing users to enable "developer mode". I think explicit warning is really the only tool we have to protect users, and we are already employing it. I'm not sure what we would gain by tucking it further away, other than friction, when we don't see any attacks successfully happening along this vector.

**Comment by jacobcantele** [comment]
Given the staleness and lack of need for this, I'm going to go ahead and close this issue.
