### ISSUE TITLE
[Bug]:  In 70% of cases, the network does not change.

### ISSUE THREAD

**Issue by Relobum** [MetaMask/metamask-extension#19307]
### Describe the bug

I promised myself that I would try to control myself and express my thoughts calmly, without resorting to insults.

In 2 years of using the extension, I encountered 2 problems, which not only are not solved with new patches - it's only getting worse.

1. When you change the network, about 70% of the time, in fact, it will not change. In this case, in the extension itself, in the header, the name of the network will change, but the network logo (under the wallet address) remains the same. When I try to make a transaction, it will try to be made in the "past" network, while the value of the billed gas will be enormously overestimated (up to $50,000 per transaction in the Ether network). Now let's think for a second who would be to blame if I accidentally executed a transaction with such an inflated gas... The question is rhetorical.

The problem is observed with all my friends (but with different chance of triggering), in all browsers, in all versions of the program for the last 4 months. Moreover, with each patch the chance of incorrect switching is getting higher. At this point, working with the extension is no longer possible in principle.

2. When you open any browser, a new, separate window opens with the Metamask extension. In other words, I just open a browser, and immediately a separate window pops up with an extension that I may not need at the moment. How do I fix it? I want to turn off the auto-open extension in a new window when I start the browser! If I need an extension, I will click on it personally!

The problem is observed in absolutely all browsers on which the Metamask extension is installed.

Please do not write off the above 2 bugs as problems with my browsers, PC, or anything else. The last time I wrote to your support team regarding another bug I encountered, it turned out that the problem was on YOUR side, even though your tech support assured me otherwise!!! AS IT WAS EVENTUALLY RESOLVED WITH THE NEXT PATCHES!!!!

- My device: a laptop running Windows 11 (licensed).
- Browsers in which problems are observed: Google Chrome, Brave, Mozilla Firefox, Ads Power (absolutely all their versions).

### Steps to reproduce

Described above.

### Version

All

### Build type

None

### Browser

Chrome, Firefox, Brave, Other (please elaborate in the "Additional Context" section)

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello, @Relobum. Thanks for reporting! Would you mind sharing a screen recording or screenshots illustrating the behavior you detailed in the report? Thank you!

**Comment by Relobum** [comment]
Hello.

A similar madness is happening (I attach screenshots).

Also, when I change the network incorrectly, just crazy gas values are automatically put up. The other day I was asked by default to pay a transaction on Polygon for 1 million 200 thousand dollars.

<img width="261" alt="Снимок экрана 2023-05-29 183020" src="https://github.com/MetaMask/metamask-extension/assets/112897978/60ff7698-49aa-4031-bf10-4196167031b5">
<img width="264" alt="Снимок экрана 2023-05-29 182909" src="https://github.com/MetaMask/metamask-extension/assets/112897978/d9956185-b416-40ab-9bc7-6b730ef1e4f8">
