### ISSUE TITLE
Avoid Clipboard Sniffing

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1931]
- remove all cases where we copy private keys or seed words to clipboard
- replace with file download
- show warning message about clipboard sniffing. something like: "Any website can read the content of your clipboard, even if it is in a background tab".

**Comment by kumavis** [comment]
de-escalating this bc webpages cant sniff the clipboard - you have to manually paste in
but apps and maybe extensions can freely read the clipboard

**Comment by sullof** [comment]
It is surprising that after so many years, MetaMask continues to automatically copy the private key to the clipboard when clicking the export field.
It is unsafe and prone to sniffing as you know. I would say that right now is the biggest weakness in the extension.
At least, let me select the key and copy it manually. This way, I can copy it partially, and type some part of it, reducing the risks. If you copy it as soon as I click the field, I can't do it. Which means, that I have to find another wallet, considering how often I need to transfer keys between the wallet and my dev environment.
You can also keep it by default, adding a setting somewhere that allows people to deactivate the automatic copy.
Can you please reopen this very serious issue?
