### ISSUE TITLE
stuck on "Connecting to Unknown Private Network"

### ISSUE THREAD

**Issue by miguelmota** [MetaMask/metamask-extension#1932]
<img width="354" alt="screen shot 2017-08-16 at 3 17 04 pm" src="https://user-images.githubusercontent.com/168240/29387709-250aaa9c-8296-11e7-9140-2b126ee6e12f.png">

keeps spinning forever, even though `testrpc` is running on localhost:8545

**Comment by miguelmota** [comment]
restarting chrome fixed the issue

**Comment by Oponn-1** [comment]
this is happening to me, and I already restarted chrome. I am trying the Truffle Pet Shop tutorial, have followed all instructions

**Comment by tuyen-vuduc** [comment]
Same here when getting started with PetShop tutorial.

**Comment by lonewoolf** [comment]
I still get an endless 'connecting to unknown private network' - any other ideas?

**Comment by IlijaLoncarevic** [comment]
@lonewoolf @Oponn-1 
- Just click on on top left menu and select **Custom RPC**
- In the **New RPC URL** insert the URL (**default**: http://127.0.0.1:7545)
- Click **Save** and click on the left arrow and insert the seed and password

**Comment by wangki** [comment]
In my case, 
set to custom rpc  "http://127.0.0.1:2545" -> bug
"http://127.0.0.1:2545/" adding slash at the end.  fixes the issue. 
at the same time i was opening ganache at the same port. in case it doesn't work.

**Comment by mimaraslan** [comment]
https://truffleframework.com/docs/advanced/truffle-with-metamask

**Comment by ashishKumarAgarwal** [comment]
I too faced a similar issue, in my case it got resolved when I switched to my personal network from my office network, somehow my office network was blocking this.

**Comment by mawenpeng** [comment]
I got similar issues due to offering more RPC APIs with "--rpcapi eth,web3,admin" when starting up my private eth node, which might violate security constraints of MetaMask.

**Comment by stefek99** [comment]
Wasted some time...

![image](https://user-images.githubusercontent.com/249703/50576100-b0c9fc80-0e0a-11e9-8689-70faa8b665a6.png)

Spinning button does not look like change of the network.

**Comment by bdresser** [comment]
@stefek99 this UI is fixed in https://github.com/MetaMask/metamask-extension/pull/5893, should be released shortly!
