### ISSUE TITLE
[Bug]: Cannot send ERC-20 Tokens with value less than 1

### ISSUE THREAD

**Issue by TechnicallyWeb3** [MetaMask/metamask-extension#19322]
### Describe the bug

I'm deploying a new contract, I have deployed on Mumbai Testnet to contract 0x9A23C6A618977B9EcA14a6303c9Ca7A5fa3B46D7 and I was able to mint tokens and transfer them using remix IDE through metamask. But when I went to transfer these tokens using metamask directly from the extension it seems to only allow me to start with a whole number but my token supply is low so all my token's holders will frequently transact 0.1 or less. MetaMask on the browser extension seems to not allow this even though I was able to inject the transaction from remix. Here's the transaction which was run through metamask, initiated by remix and unable to be done via the UI 0x391873a5c075d6523974a6f802fc813f2cf3e11a583f63664855e7da47ae86b3 The token I made has a max supply of 1 and 24 decimal places

### Steps to reproduce

1. Transact an ERC20 token (with 24 decimal places) in quantities lower than 1.
2. Happens on Chrome, Firefox including on Flask

### Error messages or log output

```shell
No error, but when I type 0.1, 0.01 or any value below 1 it reverts the value to 0
```

### Version

10.30.4

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows

**Comment by alokeutpal** [comment]
Slow

**Comment by TechnicallyWeb3** [comment]
> Slow

Could you point me to the right issue number? Tried a search. This works fine in brave.

**Comment by anaamolnar** [comment]
Hello, @TechnicallyWeb3. Thanks for reporting! I will pass this on to the team.

**Comment by alokeutpal** [comment]
Its real borring feature borring system
