### ISSUE TITLE
[Bug]: MS Defender detect Trojan:JS/Phish!MSR in MetaMask

### ISSUE THREAD

**Issue by fasolens** [MetaMask/metamask-extension#19323]
### Describe the bug

When I activated Microsoft Defender, it detects Trojan:JS/Phish!MSR in MetaMask extension for Chrome.
I removed the extension and tried re-install it. Defender blocked installation with the same waring.

### Steps to reproduce

1. Activate Microsoft Defender
2. Scan the drive
3. See the warning from Defender
4. 
![Zrzut ekranu 2023-05-29 131255](https://github.com/MetaMask/metamask-extension/assets/398144/192ef079-8e55-4137-a90e-d59950804345)
![Zrzut ekranu 2023-05-29 131307](https://github.com/MetaMask/metamask-extension/assets/398144/7ee94607-8c63-41b0-8156-be4b8ac15456)

### Version

10.30.4_0

### Build type

None

### Browser

Chrome, Other (please elaborate in the "Additional Context" section)

### Operating system

Windows

### Additional context

I use Vivaldi Browser (Chrome based) but also tested with Chrome.

**Comment by anaamolnar** [comment]
Hello, @fasolens. Thanks for reporting! The team is looking into the issue. I can assure you that this is a false positive, so there is no reason to worry. We will come back when we have more details.

**Comment by sazonovanton** [comment]
same

**Comment by Elephantdesign** [comment]
I have same alert 

<img width="347" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/88733930/eff8ac2e-1c8c-4859-a531-751cc9a81ade">

**Comment by wodyy666** [comment]
I just got the same alert from Defender.

Browser: Firefox 113.0.2 (64-bit)
MetaMask Extension: 10.30.4
OS: Windows 10

**Comment by misirov** [comment]
same here. Exactly the same alert

**Comment by danjm** [comment]
@sazonovanton @Elephantdesign @wodyy666 @misirov Are you seeing this alert when attempting to install the extension? Or do you already have the extension installed?

If you are attempting to install the extension, what url are you attempting to install from? https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn? Or a different website?

**Comment by danjm** [comment]
okay, thanks, that's helpful

**Comment by wodyy666** [comment]
@danjm I already had the extension installed and randomly got the alert while doing something else. I didn't even have the extension open (it was enabled but i haven't entered the password to use it yet). It probably got flagged during one of the background checks.

Unfortunately I can't exactly remember when and where I first installed it but I am pretty sure it was from a site that linked to the firefox add-on page. I did make sure that it is the correct extension by looking at the number of users and so far it worked without any issues.

I have uninstalled it for now and will wait until this issue is resolved before I set it up again.

**Comment by danjm** [comment]
Oh, to be clear, your extension is not at risk. This is a false positive. I was trying to sort out whether this was only effecting new installations, or existing installations as well.

I believe that re-installing from https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn will install v10.31.0, which is unaffected by this problem, and therefore resolve the problem.

**Comment by danjm** [comment]
If you have metamask installed and prefer to just update the version (instead of uninstall and re-install), you can manually update by following these instructions https://support.metamask.io/hc/en-us/articles/360060268452-How-to-update-the-version-of-MetaMask

**Comment by sazonovanton** [comment]
Extention was installed for a while. Was closed when alert appeared.

**Comment by wodyy666** [comment]
Just tried reinstalling it and got the windows defender alert again. I then checked to version to see that it was still 10.30.4. Is it possible that 10.31.0 is not available on firefox yet?

**Comment by trapke** [comment]
We had a user who installed the extension v10.30.4 on 2023/05/16. Today, a full virus scan was performed by Microsoft Defender for Endpoint, which reported this file. The file wasn't in use and the system started the scan automatically.
I've tried to reproduce it by copying the JS file onto my test machine which is also onboarded in Microsoft Defender for Endpoint and running a manual file scan on it. Nothing was found. That was kinda weird, but such things happened sometimes in the past and have been Microsofts fault.

**Comment by danjm** [comment]
>Just tried reinstalling it and got the windows defender alert again. I then checked to version to see that it was still 10.30.4. Is it possible that 10.31.0 is not available on firefox yet?

yes, sorry, v10.31.0 is not available on firefox yet
