### ISSUE TITLE
Add way to select popular tokens to `add token` screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1934]
Maybe a popular token tab with icons, maybe an auto-complete list, maybe auto-detect what we can on that screen, and show those somehow?

Might benefit from some design.

**Comment by kumavis** [comment]
bumping priority bc people are bananas for tokens

**Comment by cjeria** [comment]
In the add token flow, the first step is picking from a list of popular tokens. This is the screen @flyswatter @kumavis 

![image](https://user-images.githubusercontent.com/597770/29729622-c63db164-8991-11e7-99fe-317d48ec77d0.png)
