### ISSUE TITLE
Design audit: Header & footer

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#19351]
To align our screens with the redesign introduced by multichain, we're adopting a similar [header / footer facelift](https://www.figma.com/file/Wlwk0cTx6PQkNhiX7vN13e/Snaps-Platform-v1?type=design&node-id=30%3A16308&t=w5TpIuUyeFA1YRe3-1) for our snaps screens.

**For the authorship header,** we drop the border, make it `fixed` to the top, `full-width`, `16px` around content, and with a `md` drop-shadow.

**For the footer,** we make its container fixed to the bottom with `md` drop-shadow, `16px` around button(s), and the CTA disabled until the user has reviewed the full content of the screen (i.e. scrolled to the bottom). Scroll-down arrow button in the middle, `16px` from the bottom taking you down if you click on it (and then disappears).

![facelift.png](https://images.zenhubusercontent.com/6267f04f11d2b941f83b53a0/a5539558-33b9-4dfb-b2c3-92418e0a3891)

**Comment by eriknson** [comment]
Figma: https://www.figma.com/file/Wlwk0cTx6PQkNhiX7vN13e/Snaps-Platform-v1?type=design&node-id=1%3A1472&t=kYhmv6mIpKd3I5mV-1

**Comment by kenhkan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/19351?planning-poker) with Zenhub @FrederikBolding @ritave @Mrtenz @david0xd @GuillaumeRx @hmalik88
