### ISSUE TITLE
Loading indicator for "Refresh list" button on network selection screen

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#19393]
Is there a way in which the UI could change somehow on click, indicating a loading state on the "Refresh list" button so that the user can "feel" it's working?

![242581845-63697df1-2942-40ea-be51-e3b54c921d5c.png](https://images.zenhubusercontent.com/5c75618bd2f35e69f2b6ee08/124b26a9-3e5c-48a3-9ead-e9be4167eedb)

**Comment by kevinghim** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/16388
