### ISSUE TITLE
[Bug]: Metamask keeps crashing on Android 

### ISSUE THREAD

**Issue by louischidebe** [MetaMask/metamask-extension#19402]
### Describe the bug

Metamask keeps crashing on the Android app. It happens when I'm just about to log in.
![Screenshot_20230602-022907](https://github.com/MetaMask/metamask-extension/assets/135289885/075d7628-c65a-4315-be58-217b3c4416de)

### Steps to reproduce

1.
Open the app
Put fingerprint or enter password to try logging in
Metamask app crashes

### Error messages or log output

```shell
Metamask keeps stopping
```

### Version

6.6.0

### Build type

Flask

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

### Additional context

On the Metamask Android app
The problem occurs just after the log in screen.

**Comment by JaneJetson-Infiniverse** [comment]
The same is happening to me even after updating to 6.6.0 - it didn't auto-update. It actually doesn't even open, it's just a flash on the screen after I click to open. I get the same message that Metamask keeps stopping.

**Comment by JaneJetson-Infiniverse** [comment]
UPDATE: It turned out that I had to turn off my Surfshark VPN. Once I did that MM opened right away.

**Comment by imaksp** [comment]
For mobile app you need to create issue in this repo:
https://github.com/MetaMask/metamask-mobile/issues
