### ISSUE TITLE
[Bug]: Account and Network are editable in the middle of a transaction if I open the Settings view

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19439]
### Describe the bug

**Problem**: whenever I am in the middle of a transaction, it is not possible to change the Network or the selected Account, which is expected. However, if I open the Settings, then the Network and Account can be changed, leading to errors.

https://github.com/MetaMask/metamask-extension/assets/54408225/52bc4e50-03ab-4ca2-b5ba-548a8eb1b672

### Steps to reproduce

1. Start a transaction
2. Go to last Confirmation page
3. See how Network and Selected Account cannot be changed
4. Now open the Settings
5. See how Network and Selected Account can be edited
6. If you change the Network and close settings you land into the MetaMask encountered an error page

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by kevinghim** [comment]
During the transaction flow
- the account picker should not be disabled, but the network picker should be disabled.
- TBD: disabling setting on global menu

**Comment by kevinghim** [comment]
We will disable settings on global menu per this [thread](https://consensys.slack.com/archives/C04F4CZ2X36/p1686342850365479?thread_ts=1686242372.705099&cid=C04F4CZ2X36)
