### ISSUE TITLE
[Bug]: Metamask disabled in Firefox

### ISSUE THREAD

**Issue by andreujuanc** [MetaMask/metamask-extension#19436]
### Describe the bug

Hi!

Just in case this is not related to https://github.com/MetaMask/metamask-extension/issues/19323

![image](https://github.com/MetaMask/metamask-extension/assets/360052/90d1a0c5-4b07-4a14-8e3f-6b70825e1b9d)

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

### Steps to reproduce

1. Existing installation of Firefox + Metamask
2. On Friday extension got removed.
3. Very sad weekend.

### Version

10.30.4

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by mocoga33** [comment]
Got exactly the same issue . First noticed it 2-3 days ago. Any1 know how to fix this?

**Comment by andreujuanc** [comment]
@mocoga33 I restarted Firefox and the extension was not there anymore, So I went to the official metamask site and installed it from there again. All info was still there, so I did not have to re add my seed

**Comment by anaamolnar** [comment]
@andreujuanc Thanks for reporting! Do you remember anything specific you did before this happened? What does the 'More Information' section say? Are you experiencing this in multiple browsers or just Firefox? Thanks!

**Comment by anaamolnar** [comment]
Hey, @mocoga33. Do you remember anything specific you did before this happened?

**Comment by andreujuanc** [comment]
Hi @anaamolnar 
Nothing out of the ordinary. It just happened that last Friday the extension was not there. If you clicked that "more information" button, it would just take you here: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

Just Firefox. Latest version.

**Comment by anaamolnar** [comment]
Thanks, @andreujuanc. Do you remember getting any warnings from Windows Defender regarding the extension? This is probably related to the false positive you mentioned, but I think you should have seen a notification. Do you remember anything about that? Can you access Windows Defender and check any recent flags?

**Comment by andreujuanc** [comment]
I did not get any notifications :/ But after you mentioned it I went and check the logs, and yes, there was a false positive:
![image](https://github.com/MetaMask/metamask-extension/assets/360052/a715ff8c-6e5f-43e6-bc36-2b808f2e0ca5)

I thought it was something else because I did not get notified. 

Was there any official statement about this?

**Comment by mocoga33** [comment]
Yeah, I have exactly the same "Threat quarantined" message!
