### ISSUE TITLE
[Bug]: Problem selecting ropsten network (deprecated) by mistake, I can't reselect another network

### ISSUE THREAD

**Issue by sntgchns** [MetaMask/metamask-extension#19432]
### Describe the bug

The screen stays locked saying to change network

### Steps to reproduce

1. Switch to Ropsten's network and try to perform a network change
![image](https://github.com/MetaMask/metamask-extension/assets/86539574/fe33d775-1b41-4bb6-aa5d-43da6bc6b120)

### Error messages or log output

```shell
No error codes
```

### Version

10.31.0-flask.0

### Build type

Flask

### Browser

Microsoft Edge

### Operating system

Windows

### Additional context

Only described

**Comment by sntgchns** [comment]
The only way to skip the screen was inspecting and removing the html element to be able to select the new network

**Comment by anaamolnar** [comment]
Closing this in favor of #19564
