### ISSUE TITLE
ZRX tokens not showing up

### ISSUE THREAD

**Issue by vikram55** [MetaMask/metamask-extension#1943]
Hi, I purchased 39,441 ZRX but they are not showing in my metamask account. Initially the Tokens tab was showing an error with a link, but now it just shows no tokens. I can go to https://etherscan.io/token/ZRX and see that the tokens are still in my account 0x9902a8E02d1626D61B221906E36673B22801ffad

Please help.

**Comment by flyswatter** [comment]
You just need to manually add them to your token list.  Click "Add Token" and enter the ZRX address (`0xe41d2489571d322189246dafa5ebde1f4699f498`, I believe).
