### ISSUE TITLE
[Bug]: Clicking `Connected Sites` while on a Confirmation screen does nothing

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19437]
### Describe the bug

**Problem**: whenever we have initiated a transaction, if we click the option `Connected Sites` nothing happens.

https://github.com/MetaMask/metamask-extension/assets/54408225/38ba7eb6-027e-4c26-928f-2e4f73dc4ac5

### Steps to reproduce

1. Initiate a transaction
2. Click the 3 dots on the network menu
3. Click `Connected Sites` 
4. See nothing happens

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by kevinghim** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Extension-Client-Team-63529dce65cbb100265a3842/issues/MetaMask/metamask-extension/19437?planning-poker) with Zenhub @darkwing
