### ISSUE TITLE
[Bug]: Changing networks with a pending transaction lands me to Error page `Cannot read properties of undefined (reading 'chainId')`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19438]
### Describe the bug

**Problem**: whenever we are in the middle of a transaction, if I change networks I land into the MetaMask encountered an error page with the log `Cannot read properties of undefined (reading 'chainId')`

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/63447bd4-70c9-4bb0-a922-0ea5c4bc7266)

https://github.com/MetaMask/metamask-extension/assets/54408225/6b03bdfb-36f1-4ee7-a464-270df7af16f4

### Steps to reproduce

1. Initiate a Send transaction from a dapp
2. Open MM full view
3. Change networks
4. See error page

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This has been fixed as users are not able to switch networks in the middle of a transaction anymore.
