### ISSUE TITLE
[Bug]: Incorrect native token balances and rounding issues

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#19456]
### Describe the bug

https://github.com/MetaMask/metamask-extension/assets/53189696/c00e5624-6876-4194-951c-8b82c11e3037

### Steps to reproduce

1. See video above
2. Log in to the extension
3. check the balance on the token overview page (correct balance)
4. open the send flow
5. enter an address and an amount, and click next (correct amount)
6. check the amount on the send confirmation page (incorrect amount, expected 2.3 ETH, actual 2 ETH)
7. reject the confirmation
8. check the balance on the token overview page (incorrect balance, expected 10.2777 ETH, actual 10ETH)

Reloading the extension refreshes the balances to the correct state

### Version

10.32

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by salimtb** [comment]
hey @PeterYinusa ,
I can't reproduce the bug even if I follow the steps in the video, can you please provide me more informations ?

**Comment by PeterYinusa** [comment]
Hi @salimtb, this one is hard to reproduce. @danjm may be able to explain what we were seeing in more depth.  At the time we created this branch to aid debugging https://github.com/MetaMask/metamask-extension/compare/develop...bignumber-rc. I'll spend some time tomorrow to see if I can still reproduce it

**Comment by salimtb** [comment]
hey @PeterYinusa ,
any news about that one ?

**Comment by salimtb** [comment]
bug non reproductible
