### ISSUE TITLE
[Bug]: I get weird warnings on chrome browser

### ISSUE THREAD

**Issue by resilientboy** [MetaMask/metamask-extension#19455]
### Describe the bug

After latest chrome update metamask keeps giving warnings on developer screen on any webpage.
If i disable metamask extention it goes away.
I've uninstalled and reinstalled metamask, Reset chrome, nothing helped.
Warnings originate from files called 
lockdown-install.js
lockdown-run.js

![image](https://github.com/MetaMask/metamask-extension/assets/4083043/84e99f30-e846-4987-a2c4-156430fb4196)

### Steps to reproduce

1.I have no idea how to. I might be the only one even.

### Version

10.31.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello, @resilientboy. Thanks for reporting! I will pass this on to the team.

**Comment by jurosh** [comment]
This is super annoying.. Still happening with latest version `10.31.1`

**Comment by dsimmons** [comment]
Also seeing this (on Brave) :eyes: 

Would appreciate this getting resolved ASAP, as it's making my day-to-day development work more challenging (spamming the console)!

**Comment by Donzo** [comment]
I, too, am struggling with this error…

**Comment by resilientboy** [comment]
> Hello, @resilientboy. Thanks for reporting! I will pass this on to the team.



> 

Could've upped the severity though.
We developers need the console to check out our code and it keeps filling it with gibberish, making it very hard to develop anything.
