### ISSUE TITLE
Network Indicator should show where node is

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1948]
Currently if you run a local ropsten, the network indicator simply shows "Ropsten Network", which has confused a user.

Could be nice to indicate whether the current network is Infura, or a custom node, maybe with the icon.

Needs design.

**Comment by danjm** [comment]
Reopening as this issue still exists, but is more impactful than running a local ropsten, as it now also affects users who connect to ropsten with a custom rpc.

**Comment by danjm** [comment]
Removing the needs design label as, instead of a custom design for the non-infura ropsten, we should just show the appropriate item from the network dropdown in the network indicator.

**Comment by bdresser** [comment]
@danjm so you're staying - if the user defines a custom RPC network that points to a major testnet, we should show the user's custom-defined settings rather than over-write with the testnet's label? Sounds good to me.

**Comment by bdresser** [comment]
Closed via https://github.com/MetaMask/metamask-extension/pull/6495
