### ISSUE TITLE
Design audit: Warning modal

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#19490]
**Figma:** https://www.figma.com/file/Wlwk0cTx6PQkNhiX7vN13e/Snaps-Platform-v1?type=design&node-id=177%3A16851&t=kY4jMt2plPPUv0I8-1

- [ ] `48px` title icon
- [ ] `Heading-MD` / `18px` title
- [ ] `32px` margin between check list items
- [ ] `base` / `14px` font-size for list items
- [ ] `bold` -> `medium` font-weight for list items
- [ ] Update description copy to _Take a moment to review the permissions being requested. Only continue if you trust **Arbitrary Manager**._

**Comment by eriknson** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/metamask-extension/19490?planning-poker) with Zenhub @david0xd @FrederikBolding

**Comment by david0xd** [comment]
We agreed that 24px margins would be better. PR is updated according to that.
