### ISSUE TITLE
[Bug]: The contract address section shows the recipient address for ERC1155 Batch Transfers

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#19502]
### Describe the bug

The `contract address` section shows the `recipient address` for ERC1155 Batch Transfers

https://github.com/MetaMask/metamask-extension/assets/53189696/dd35acf1-a4b1-4429-88a6-c249bbe3e2f0

### Steps to reproduce

1. log in to the extension
2. navigate and connect to the test dapp
3. deploy the erc1155 contract and mint some tokens
4. click the batch transfer button
5. check the contract and recipient address shown on the confirmation screen

Actual result:
Contract Address: 0x2f318C334780961FB129D2a6c30D0763d9a5C970 (Dapp Contact 2)
Recipient: 0x2f318C334780961FB129D2a6c30D0763d9a5C970 (Dapp Contact 2)

Expected result:
Contract Address: 0xe3550132D67eBB132bfD7243f2f713BCC8A8bbE3 (Rock Paper Scissors)
Recipient: 0x2f318C334780961FB129D2a6c30D0763d9a5C970 (Dapp Contact 2)

### Version

10.32

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by chloeYue** [comment]
Fixed by #21042
