### ISSUE TITLE
[Bug]: We were not able to estimate gas. There might be an error in the contract and this transaction may fail.

### ISSUE THREAD

**Issue by bunthoeunstable** [MetaMask/metamask-extension#19509]
### Describe the bug

please team core help check in testnet this function work, but on mainnet We were not able to estimate gas. There might be an error in the contract and this transaction may fail.

https://etherscan.io/address/0x24288d6332f800282eE0538d044dcaA3A8786Aaf

### Steps to reproduce

1.
function minterMint(
            address to, 
            uint256 quantity,
            address payee,
            uint256 price
        ) external payable {
        
        require(maxSupply >= totalSupply() + quantity, "insufficent supply");
        require(!paused, "mint is paused");
        require(msg.value >= unitPrice * quantity, "insufficent balance");
        require(payeeAddress == payee, "invalid payee address");
        payable(payeeAddress).transfer(price);
        _mint(

### Error messages or log output

```shell
We were not able to estimate gas. There might be an error in the contract and this transaction may fail.
```

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by anaamolnar** [comment]
Hello, @bunthoeunstable. Thanks for reporting! I will pass this on to the team.

**Comment by bunthoeunstable** [comment]
> Hello, @bunthoeunstable. Thanks for reporting! I will pass this on to the team.

@anaamolnar i resolved it.
