### ISSUE TITLE
[Bug]: Cannot perform a Send if I have a pending Signature, MM crashes with error `Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19512]
### Describe the bug

**Problem**: whenever I trigger any Signature from a dapp, if I then trigger a Send and reject or accept that Send, MetaMask crashes with the error `Cannot destructure property 'balance' of 'accounts[fromAddress]' as it is undefined.`

https://github.com/MetaMask/metamask-extension/assets/54408225/2fc665cf-dbfe-4120-8fcc-6a6060df58d1

### Steps to reproduce

1. Go to test dapp
2. Trigger any type of signature
3. Do not accept it or reject it
4. Trigger a Send transaction
5. Go to the Send transaction in MM
6. Reject or Accept that transaction
7. See MetaMask crashes

### Version

10.31.1 production, also present in `10.29`but not on `10.27` (haven't digged further)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by dbrans** [comment]
This issue was fixed by commit https://github.com/MetaMask/metamask-extension/commit/a0e8ee14af00f9793349206909c44d7b68985c41

Parent commit, https://github.com/MetaMask/metamask-extension/commit/5d818bb2b3af140dfbe4bb20c95fb0496911e920, the issue was still happening.
