### ISSUE TITLE
[Bug]: REGRESSION Floods the console with warnings

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-extension#19524]
### Describe the bug

See below

### Steps to reproduce

1. Visit any website (e.g. https://google.com)

For some reason this stupid template doesn't allow markup, or pasted images, in the "Error messages or log output below, nor does it contain an "expected behavior" vs "observed behavior" sections, so I'll continue here.

Observed: the console is flooded with these warnings.

![image](https://github.com/MetaMask/metamask-extension/assets/13969584/db12ecb3-c6c2-4bf4-ab66-f47136721e56)

### Error messages or log output

```shell
Copying the trace of one of the warnings:

lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
isAllowedPropertyValue @ lockdown-install.js:1
isAllowedProperty @ lockdown-install.js:1
visitProperties @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
```

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Additional context

I'm switching it off. Pathetic. Don't you guys do the slightest bit of testing?

**Comment by mwawrusch** [comment]
Please give this a priority.

**Comment by kevinghim** [comment]
@php4fan @mwawrusch closing this issue to have it track on a similar issue here: https://github.com/MetaMask/metamask-extension/issues/19541

**Comment by php4fan** [comment]
> closing this issue to have it track on a similar issue here: https://github.com/MetaMask/metamask-extension/issues/19541

When you do that, please mark the issue as duplicate so that subscribers of the closed one get automatically subscribed to the other one
