### ISSUE TITLE
[Bug]: Error message in metamask extension cannot be closed and prevents the extension from working.

### ISSUE THREAD

**Issue by calmacfadden** [MetaMask/metamask-extension#19521]
### Describe the bug

I selected the Rinkyby network and i see the error "The current rpc url for this network has been deprecated."

The X to close the error does not work. 
There is a button called "Switch Networks" but selecting his opens the network selection list behind the error and keeps the error on the screen. 

The extension now cannot be used at all. 

### Steps to reproduce

1. Select a depreciated network. 
2. Get the popup saying "The current rpc url for this network has been deprecated."
3. You will no longer be able to use the extension. 

### Error messages or log output

```shell
"The current rpc url for this network has been deprecated."
```

### Version

Not able to check

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by danjm** [comment]
thanks for the report

closing in favour of https://github.com/MetaMask/metamask-extension/issues/19564
