### ISSUE TITLE
[Bug]: DEFI connection issues

### ISSUE THREAD

**Issue by carl339** [MetaMask/metamask-extension#19538]
### Describe the bug

When I'm try to connect appears error, only happen in chrome in defi page like uniswap or orbiter, I clean cookies and cache but appears the same issue. In Firefox works all fine but chrome not.

### Steps to reproduce

1.log in
2. When I'm try appears error

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by leotorenzo6** [comment]
> ### Describe the bug
> 
> When I'm try to connect appears error, only happen in chrome in defi page like uniswap or orbiter, I clean cookies and cache but appears the same issue. In Firefox works all fine but chrome not.
> 
> ### Steps to reproduce
> 
> 1.log in
> 2. When I'm try appears error
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.31.1
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

**Comment by leotorenzo6** [comment]
> ### Describe the bug
> 
> When I'm try to connect appears error, only happen in chrome in defi page like uniswap or orbiter, I clean cookies and cache but appears the same issue. In Firefox works all fine but chrome not.
> 
> ### Steps to reproduce
> 
> 1.log in
> 2. When I'm try appears error
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.31.1
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

**Comment by leotorenzo6** [comment]
> ### Describe the bug
> 
> When I'm try to connect appears error, only happen in chrome in defi page like uniswap or orbiter, I clean cookies and cache but appears the same issue. In Firefox works all fine but chrome not.
> 
> ### Steps to reproduce
> 
> 1.log in
> 2. When I'm try appears error
> 
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 10.31.1
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

```
```

**Comment by anaamolnar** [comment]
Hello, @carl339. Thanks for reporting! Could you please provide a screenshot of the error and tell me the steps you take specifically when connecting to the dapps? What are the dapps you encountered this issue with?  Do you have multiple wallets in the same browser? Thank you!

**Comment by carl339** [comment]
i send screenshot of the issue
![Screenshot_2](https://github.com/MetaMask/metamask-extension/assets/43270797/ad805fd1-5461-4a4f-acc7-1aa170c3090c)
![Screenshot_3](https://github.com/MetaMask/metamask-extension/assets/43270797/52afa18f-95e0-4df8-ad0f-2ded1b37c863)

**Comment by anaamolnar** [comment]
@carl339 Do you use multiple wallets in the same browser?
