### ISSUE TITLE
[Bug]: Decrypt request displays incomplete message

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19549]
### Describe the bug

**Problem**: whenever we are using the Encrypt/Decrypt function and we try to decrypt a long message, we can see how MM displays only the first part of the message.

https://github.com/MetaMask/metamask-extension/assets/54408225/d3e0b947-b072-41e4-ad37-2bf35e91b27f

### Steps to reproduce

1. Go to test dapp
2. Click Get Encryption Key and accept
3. Paste a long text in the input field
4. Click Encrypt
5. Click Decrypt
6. Click Decrypt Message in MM
7. See text is not complete

### Version

10.31.1 possibly old issue

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jase-b** [comment]
I can fix this! ✋
Making the decryption message box scrollable should do the trick.

**Comment by seaona** [comment]
This issue is still happening in prod 11.10
