### ISSUE TITLE
[Bug]: Copying addresses to clipboard is not working

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19548]
### Describe the bug

**Problem**: whenever I am using the function to copy to clipboard any address, I can see how they are actually not copied.

https://github.com/MetaMask/metamask-extension/assets/54408225/08dd8b7b-791c-446c-853e-4139face7c4b

### Steps to reproduce

1. Deploy a contract
2. Interact with the contract
3. Go to Activity tab
4. Click on the transaction
5. Click on the recipient
6. Click Copy to Clipboard
7. Paste the value somewhere else -- see how only an empty space is pasted

### Version

10.31.1 (older issue since a couple of releases at least)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by ryanml** [comment]
So what appears to be happening here in the video is that by the time you're pasting, a blank value has replaced the copied address in the clipboard.

In the hook used to handle clipboard copying, there is a default timeout of 3 seconds: https://github.com/MetaMask/metamask-extension/blob/develop/ui/hooks/useCopyToClipboard.js#L12

After the timeout, two things happen, 1) The clipboard is cleared 2) The copied state is set to `false`, so the clipboard icon transitions back to its original state. 

So, a higher timeout could be passed in here to keep the address copied longer. Maybe others have thoughts on the way to go here. cc: @brad-decker @darkwing

**Comment by kevinghim** [comment]
Resolves https://github.com/MetaMask/metamask-extension/pull/19948

**Comment by ralphprice** [comment]
I have the same problem. Also, there is no way to display the complete address to do a Ctrl-A Ctrl-C copy.

**Comment by VenomNFT** [comment]
Thought I've got crazy ,but I have the same issue now

**Comment by EmeraldGuy** [comment]
Why is this still an issues as of 18/07/2023?

**Comment by plasmacorral** [comment]
We have a [change](https://github.com/MetaMask/metamask-extension/pull/19948) to retain the public address of your selected account in the clipboard for 60 seconds after copying in v10.34 (instead of 3 seconds), which is available to Chrome users now and we hope to have available to Firefox users soon. 

We have another [change](https://github.com/MetaMask/metamask-extension/pull/20008) targeted for the v10.35 release which will expand the 60 second timer to _any_ addressed being copied.  That release is in test and we anticipate to have it available in the coming weeks.

**Comment by katpavan** [comment]
still happening to me

**Comment by brianonchain** [comment]
I'm still experiencing the same issue. Also, when you "create a new wallet" using a newly installed MetaMask, the "copy to clipboard" function to copy the 12-word secret recovery phrase also does not work properly.

**Comment by estarossa0** [comment]
Still having this issue on chrome all I am copying is a `whitespace`.
