### ISSUE TITLE
[Bug]: Extension is snappy and slower on dev build

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19542]
### Describe the bug

**Problem**: Extension is behaving way slower than usual and snappy in the `develop` branch using a dev build compared to the last release.

Notice the amount of time it takes for loading a dapp interaction (~13/14s), versus the current production version (~3/4s)

https://github.com/MetaMask/metamask-extension/assets/54408225/3c990a49-56d3-4d1a-ac4e-9b746f732541

- I've tried enabling/disabling all settings but it does not cause any effect on the behaviour, which is present all the time.
- I've seen that the same `develop` version works as usual if I create a `dist` build

### Steps to reproduce

1. Checkout develop
2. Start MM
3. Try a Dapp interaction 

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
@seaona can you still reproduce this?
