### ISSUE TITLE
[Bug]: sudden warning on OpenSea

### ISSUE THREAD

**Issue by nomartai** [MetaMask/metamask-extension#19551]
### Describe the bug

Hello, I was instructed by MetaMask support to submit a report here, with as many details as possible.

I recently opened a MetaMask wallet and connected it to OpenSea, and created, froze and listed for sale around 700 NFTs.
At one point (around the 500th one) in the moment of signing the contract in order to list for sale I got this warning:

![image](https://github.com/MetaMask/metamask-extension/assets/136100488/80e3040d-7b62-4430-b0be-374bf64a649f)

It happened twice, for 2 consecutive NFTs. I signed both of them...

Just in case I decided to contact OpenSea about it, asking them why this warning appeared just for these 2, to which they replied:

"We work closly with Metamask and if you are performing a multiple tasks, then a warning such as this will appear to make you aware of possible risks, they are there to assist if you are unsure and to check the actions before doing so. However as you explained your actions there is no need for concern."

But this didn't answer why the warning appeared all of a sudden and for 2 consecutive listings. To me it seemed strange anyway, so I contacted Metamask support who told me there's not much they could say because this warning comes from OpenSea's API, but they told me to ask here.

Also, the other thing is that before I got the warnings I had contacted OpenSea because of a strange item that appeared in my Offers section under Settings, of something called 'WEB3BOX Pass - Genesis Mystery Box' 

![WEB3BOX Pass](https://github.com/MetaMask/metamask-extension/assets/136100488/4880a5c3-5255-429d-90a7-b664129c72c7)

which they told me was a known scam and they removed it (something that for some reason I couldn't do myself). And it was right after this removal that I got the warnings, so I became afraid the two events were connected.

Anyway, I hope I've explained it well!

Thanks!!

### Steps to reproduce

1.

### Version

10.30.4

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by bschorchit** [comment]
Thank you for your report, @nomartai. I'm closing as this has been shared with OpenSea
