### ISSUE TITLE
[Bug]: Unable to close network switch prompt after selecting invalid network 

### ISSUE THREAD

**Issue by aLIEzsss4** [MetaMask/metamask-extension#19564]
### Describe the bug

<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/24380830/f0fed5e8-2451-4f8e-95b2-05218f6ae2a5">
<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/24380830/d401a52b-45ef-4a16-b8ab-2140d86dab81">
Refreshing the page did not solve the problem. This seems to be a UI bug in MetaMask - when trying to switch to an invalid network, the prompt cannot be closed normally, causing the interface to freeze. Please confirm and fix this issue.

### Steps to reproduce

1. Open MetaMask extension, Rinkeby test network selected by default
2. Try to switch network to invalid network "Unrelated Network" 
3. Network switch prompt pops up but cannot be closed, and no actual network switch happens
4. Interface freezes and unable to continue operating MetaMask

Refreshing the page did not solve the problem. This seems to be a UI bug in MetaMask - when trying to switch to an invalid network, the prompt cannot be closed normally, causing the interface to freeze. Please confirm and fix this issue.

### Version

latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Kdjdunh** [comment]
<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/132909403/86a58cf5-435e-46ae-86cb-c522797ab3f4">

**Comment by aLIEzsss4** [comment]
@Kdjdunh @calmacfadden 

Solve the problem that MetaMask UI froze when switching to deprecated networks.  

Reproduce the problem:
1. Switch the MetaMask network to Rinkeby or another deprecated network.  

Problem:
1. The UI layer freezes and cannot close prompts or use MetaMask. 

Solution steps:
1. Open the MetaMask developer tools and find the element with ID "popover-content". 
2. Delete that element. 
3. At this point, the stuck UI layer disappears, and you can normally close other prompts and use MetaMask.
4. The MetaMask network successfully switches back to the Ethereum main network. 

<img width="375" alt="Pasted Graphic 3" src="https://github.com/MetaMask/metamask-extension/assets/24380830/ae87283e-448b-44d8-b5de-2c46ca7070e6">
<img width="857" alt="Pasted Graphic 4" src="https://github.com/MetaMask/metamask-extension/assets/24380830/2043c9f4-dea0-49ee-90c0-a20984a8e1bc">
<img width="366" alt="Pasted Graphic 5" src="https://github.com/MetaMask/metamask-extension/assets/24380830/7acba1ae-b19c-403a-ba73-3b61826c1173">
<img width="371" alt="Pasted Graphic 6" src="https://github.com/MetaMask/metamask-extension/assets/24380830/075a00bd-8c5f-4611-accf-33af36bc8731">

**Comment by longfeiWan9** [comment]
That did not work for me. I could not close the window by clicking the X on top right corner. 
Need this to be fixed asap, please

**Comment by aLIEzsss4** [comment]
> That did not work for me. I could not close the window by clicking the X on top right corner. Need this to be fixed asap, please

You may be able to delete the other popup again through the developer tools.

**Comment by danjm** [comment]
@aLIEzsss4 what version of MetaMask are you using?

**Comment by danjm** [comment]
thanks everyone for reporting this, we have a fix in progress https://github.com/MetaMask/metamask-extension/issues/19564

**Comment by alfetopito** [comment]
Adding one more info.

The proposed solution (inspecting the extension and deleting the popup html) does not work in Firefox.
It's not possible to inspect the extension html.

I'm on Firefox 114.0.2 (64-bit) (MacOS)

**Comment by richard9219** [comment]
just fixed it using the same solution

**Comment by utunga** [comment]
> Adding one more info.
> 
> The proposed solution (inspecting the extension and deleting the popup html) does not work in Firefox. It's not possible to inspect the extension html.
> 
> I'm on Firefox 114.0.2 (64-bit) (MacOS)

Yup. I was on firefox and had to take my mac in to get fixed - where they were going to wipe it. I managed to properly backup my main accounts, but in the process of checking for other accounts I accidentally switched to Rinkeby - game over. No more access to any accounts - and I permanently lost access to a few more accounts which were important to me for access to various things - as a result.

**Comment by buluo987** [comment]
You can use TAB to select the network, I used this operation to solve this problem

**Comment by PeasantGit** [comment]
> 

Thx, this one worked like a charm. Made an account here just to say that. 
All other threads were closed with DevTools extension example as a solution, but it's not that much of solution for us who don't know how to even install it.

**Comment by anaamolnar** [comment]
Hey, @aLIEzsss4. This should be fixed in the latest version, therefore I will close this issue. If this continues to occur, feel free to open this issue again. Thank you!
