### ISSUE TITLE
[Bug]: Optimism Bedrock upgrade - issues with gas display for new EIP1559 transactions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19561]
### Describe the bug

**Problem**: the Optimism Bedrock upgrade, which adds support to EIP1559, happened on June 6th.
Now, we see some issues with the current gas displays

- whenever we send a transaction Optimism network we often display  `0` on any the suggested gas fees options. This seems to be a rounding issue - fees are so low in the L2 that we end up displaying a `0` for all the options

@bschorchit should we add decimals precision, so we actually display different values on each option?

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/b5587345-147d-4112-b501-0793e1ead6ad)

- we do not display a break down of L1 and L2 fees, like we do for Legacy tx's (see below pic). What should be the expected behavior here?

![Screenshot from 2023-06-11 10-56-50](https://github.com/MetaMask/metamask-extension/assets/54408225/6f4dd9e3-c3a1-4848-92dc-f2190574f76f)

### Steps to reproduce

1. Select Optimism network
2. Send EIP1559
3. Click Edit fees
4. See recommended fees are 0

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
From @holantonela (slack message [here](https://consensys.slack.com/archives/C04C0F6SSJH/p1686924726643949?thread_ts=1686648406.494659&cid=C04C0F6SSJH)):
My proposal is 
1. include an atom line in the Fee details toggle to support L2 fees 
2. move forward with this card component as defined in the [ticket](https://github.com/MetaMask/metamask-extension/issues/15223) 
3. we will iterate a bit based on our new work in footers (fee details will be in a popup most probably) but major data will be available with this update.
If the network avatar image is a problem for the implementation, let me know. We will figure it out.

[Figma here](https://www.figma.com/file/Yu779Mt44WwNQ1yNPD4A66/1559-Gas-Controls---v3?type=design&node-id=3505-22670&t=LmcBvOYS82oo7MMd-4)

**Comment by hilvmason** [comment]
@segun is Waiting for feedback from API team concerning the L2 gas fees
