### ISSUE TITLE
Deleted Metamask from extension and reinstalled  Do not have seed phrase.. 

### ISSUE THREAD

**Issue by lukeder** [MetaMask/metamask-extension#1958]
Metamask was not working with Etherdelta-all TXN kept failing.
 I  have the password and wallet address. I can still see my funds in etherdelta and I can not interact with them. Am I boned here. 
PS: I was layed off today. Seems almost fitting. Please help if possible thanks!

**Comment by kumavis** [comment]
if you deleted metamask AND you dont have your seed phrase, you're boned

have any hard disk backups from before you uninstalled?
sorry to hear about loss of job - but now you're free to get a job in crypto!
