### ISSUE TITLE
Remove unused CSS: ConnectedStatusIndicator

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#19587]
### Description
It seems that the styles for the `ConnectedStatusIndicator` component in `ui/components/app/connected-status-indicator/index.scss` is not being used and can be removed.

![Screenshot 2023-06-13 at 9 52 50 AM](https://github.com/MetaMask/metamask-extension/assets/8112138/b50c8ebd-0384-4794-97eb-ad4eb550d155)

### Technical Details
- Check that the className `connected-status-indicator` is not being used 
- Remove style sheet and all references from code base

### Acceptance Criteria
- Good explanation for checking if styles are being used in PR description
- Stylesheet and references to `ui/components/app/connected-status-indicator/index.scss` have been removed

### Difficulty: beginner
Good first issue for contributors that have experience with searching a codebase, sass and writing good PR descriptions

**Comment by shyamtawli** [comment]
I want to work on it. Assgin me

**Comment by georgewrmarshall** [comment]
Assigned thanks @shyamtawli

**Comment by shyamtawli** [comment]
Hey @jainex17 I am working on it.
