### ISSUE TITLE
[Bug]: In advanced gas fee controls MaxBaseFee is actually MaxFee

### ISSUE THREAD

**Issue by clostao** [MetaMask/metamask-extension#19599]
### Describe the bug

In the advanced gas fee controller it is display this:

<img width="327" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/49268919/30a86376-42fc-4bd6-bfd2-caaf1d525c5d">

As you can see two values have to be provided: 

* MaxBaseFee (PerGas): In lack of a better definition, it should be the maximum value you want to be charged for the base fee
* Priority Fee (PerGas): The tip for the validator

This two values summed would compose MaxFeePerGas since you set a maximum base fee and then a tip over that.

I guess this is the intended behaviour but naming is not correct.

In this code is crystal clear what is happening:

https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/app/advanced-gas-fee-popover/advanced-gas-fee-inputs/base-fee-input/base-fee-input.js#L99

### Steps to reproduce

1. Open MetaMask 
2. Start a transaction in an EIP1559-compatible blockchain 
3. Before confirming the transaction, click in Market

<img width="341" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/49268919/4d727e73-f0aa-42cf-b118-ea4bd001c938">

4. Select Advanced for setting up custom gas fee parameters
5. Set a custom MaxBaseFee and a PriorityFee
6. Confirm the transaction
7. Retrieve the summary of the transaction with `eth_getTransactionByHash` method:
8. Check that MaxFeePerGas is equal to MaxBaseFee and not to MaxBaseFee + PriorityFee

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @clostao. Thanks for reporting! I will pass this on to the team.
