### ISSUE TITLE
[Bug]: I can't operate when I switch the network to the abandoned network

### ISSUE THREAD

**Issue by wbh1328551759** [MetaMask/metamask-extension#19592]
### Describe the bug

When I switch my metamask to a defunct network, it prompts me that rpc is deprecated, but I click on the switch network and select the list of networks at the bottom of the popup, which prevents me from switching to a normal available network and causes my wallet to become unusable

### Steps to reproduce

1. Switch to a deprecated network, such as reposten
<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/48749219/c4883b0a-0806-4b0e-a2bd-123d40886516">

2. Click to switch network
<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/48749219/880b73d6-0843-4db4-b67c-8e3375e75616">

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @wbh1328551759. Thanks for your report! I am closing this in favor of #19564.
