### ISSUE TITLE
Transaction comes up as "undefined" or "noonce too low". 

### ISSUE THREAD

**Issue by Lunde89** [MetaMask/metamask-extension#1959]
Hello,

I'm currently trying to send funds to another account, but when i attempt to do so, it either says "Noonce too low", "Your node is running with pruning" or throws an empty transaction (see attached image). 

I've tried switching to a test-network and back again, to no avail. Can you help?

![image](https://user-images.githubusercontent.com/8688065/29615574-b6713b86-880e-11e7-80c5-c988920082f6.png)

**Comment by flyswatter** [comment]
We've published a fix for this as MetaMask v3.9.10, should auto-update soon. Once you're on that version, you should be able to send transactions again.

**Comment by tmashuang** [comment]
Closing old issue.
