### ISSUE TITLE
[Bug]: OpenSea not connecting...

### ISSUE THREAD

**Issue by Atahualp** [MetaMask/metamask-extension#19591]
### Describe the bug

When I click to connect my wallet it just opens MetaMask site to download.  MetaMask is already installed and logged in to.

### Steps to reproduce

1.  Click to connect wallet on OpenSea website.

### Version

Latest.  Tried a reinstall.

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by Atahualp** [comment]
Hey Ana,

I'm on Version 114.0.5735.134 (Official Build) (64-bit).  

Screenshots are pretty self-explanatory.  I click on MetaMask and just takes me to the MM website.  Let me know if there is anything else debug wise you need to see.

Thanks again for your help.

![mm](https://github.com/MetaMask/metamask-extension/assets/3523554/9af1ca4c-6f48-4558-9ac9-690edfcc6dfb)
![mm2](https://github.com/MetaMask/metamask-extension/assets/3523554/1d8001c4-10af-4f82-ab97-101442c2f481)

**Comment by anaamolnar** [comment]
Thanks, @Atahualp. Do you use multiple wallets in the same browser? Your issue seems related to this. https://support.metamask.io/hc/en-us/articles/11907107168923-I-can-t-connect-MetaMask-Extension-to-a-dapp-

**Comment by anaamolnar** [comment]
Thanks for letting me know. I will go ahead and close this.
