### ISSUE TITLE
[Bug]: didn't prevent the user from switching networks during the transaction sending process

### ISSUE THREAD

**Issue by Holybasil** [MetaMask/metamask-extension#19604]
### Describe the bug

I remember that before, when waiting for the current transaction to complete, if I switched networks, MetaMask would pop up a warning about the risk of the current operation, but now there is no warning.

Now here's my situation. after sending a transaction on network A, I immediately switch to network B, and obviously the transaction on network A will produce an unexpected error which is not caught by try-catch. When returning to network A, the entire website page is stuck and after a while, a browser prompt appears showing that the page has crashed.

I guess this is due to forcibly switching networks before the transaction is complete. I hope MetaMask can try to prevent users from switching network as it did before.

### Steps to reproduce

1. send a transaction on network A
2. switch to network B immediately
3. send a transaction on network B (optional)
4. switch back to network A
5. oops! the page is stuck and then crashes. :scream:

### Error messages or log output

```shell
"User rejected the request"
"User denied transaction signature"

Both of these errors have occurred.
```

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @Holybasil. Thanks for reporting! Could you please let me know what version of Metamask you are using? Would you mind sharing a screenshot of the error and browser prompt you receive? Thank you!

**Comment by Holybasil** [comment]
I tried again and the console didn't show errors. (perhaps it's because I didn't send the second transaction)

The entire website page becomes unresponsive and, after a while, a browser prompt appears indicating that the page has crashed.
I suspect there is an unexpected error with the "provider" when switching networks.

<img width="815" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/21138718/4a9abe4e-733e-41c6-8235-e31f1e943ac6">
