### ISSUE TITLE
Add the new shared header and origin pill to the wallet_watchAsset confirmation

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#19627]
### Background
We're currently missing the account, network and origin information on the wallet_watchAsset confirmation. We want to re-use the new components in this confirmation to display those.

### Task
We should re-use the new header component https://github.com/MetaMask/metamask-extension/pull/15614 and the new origin pill component https://github.com/MetaMask/metamask-extension/pull/15603 to the wallet_watchAsset confirmation.

The balance in the header should be the primary network token. 

### Repro Steps
1. Go to https://docs.metamask.io/openrpc-sidebar-support-two/wallet/reference/wallet_watchasset/
2. Click on “Send request”

**Comment by abdulmenan10** [comment]
Verfy

**Comment by jpuri** [comment]
@bschorchit : can you plz check if this looks correct:[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVVsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc9532c8d6374214516bfceb818f6e54669957ef/Screenshot%202023-08-22%20at%204.38.06%20PM.png)

**Comment by jpuri** [comment]
@bschorchit : I have done the update, please check:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWd1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b4551f2188e1a901c511ea3b08d000a99c2d2886/Screenshot%202023-08-23%20at%207.45.21%20PM.png)
