### ISSUE TITLE
[Bug]: stucked when I choose kovan network

### ISSUE THREAD

**Issue by afeiluo** [MetaMask/metamask-extension#19631]
### Describe the bug

![image](https://github.com/MetaMask/metamask-extension/assets/6848479/d061a7fb-59b8-412d-8c24-7b5c7c24743d)

### Steps to reproduce

1.
when I change network to kovan it stucked, I can do nothing with it , canot exit or close the popup

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @afeiluo. Thanks for reporting! I will be closing the issue in favor of this duplicate #19564
