### ISSUE TITLE
Nonce Error

### ISSUE THREAD

**Issue by JeremyRubin** [MetaMask/metamask-extension#1964]
Hi MetaMask Team,

First off this is a really cool project!

I'm having great difficulty getting the nonces to properly increment for transactions, leading to strings of failures.

see: https://github.com/MetaMask/metamask-extension/issues/1448

Definitely not addressed. I'm currently trying to get fresh nonces by: leaving nonce explicityly undefined and by loading the nonce using getTransactionCount.

**Comment by JeremyRubin** [comment]
oops: https://github.com/MetaMask/metamask-extension/issues/1959

**Comment by flyswatter** [comment]
Did you find this was fixed by version 2.9.10?

**Comment by JeremyRubin** [comment]
Not sure -- will check soon.
