### ISSUE TITLE
[Bug]: Storybook docs colors are not updated with Themes

### ISSUE THREAD

**Issue by NidhiKJha** [MetaMask/metamask-extension#19671]
### Describe the bug

In the storybook, When we switch themes, colors are updated for the story but not in the docs. If the color of the text is the default, it doesn't render properly for dark theme. 

https://github.com/MetaMask/metamask-extension/assets/39872794/db848288-9c78-45ec-9ffd-235459305f1a

### Steps to reproduce

1. Go to storybook
2. Check the docs in the Text

### Version

^7.0.11

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by georgewrmarshall** [comment]
Related https://github.com/hipstersmoothie/storybook-dark-mode/issues/180
