### ISSUE TITLE
Error replacement transaction underpriced 

### ISSUE THREAD

**Issue by pitieu** [MetaMask/metamask-extension#1967]
I have an error that makes me unable to do anything.
I use Metamask mostly for EtherDelta and try to buy or sell other coins but everything i try to do it fails. I get message "replacement transaction underpriced".

I tried changing to test server and back to main server but it didn't solve.
I also tried uninstall metamask and reinstall it and it didn't fix this.
I tried to up the gas price and it didn't help.

Has anyone the same error? Any way to solve this?

Have metamask 3.9.10. WIll the new auto update fix this ?

`
{"id":3730373011086,"jsonrpc":"2.0","params":["0xf8738201318501a....f27279a63bcff2a1"],"method":"eth_sendRawTransaction"} Error: replacement transaction underpriced`

**Comment by flyswatter** [comment]
Sorry, we broke this. Fixed in #1966, patch coming in the next hour or two.
