### ISSUE TITLE
[Bug]: Gas Component on Send tokens screen displays Total section when there is an input error

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19681]
### Describe the bug

**Problem**: whenever we are sending an ERC20 token, we can see how on the Send tokens screen, there is the gas section below and whenever we introduce more tokens that the ones we own we see an error, but we see how it appears a new gas section called Total, with  `0` amount of tokens and this changes whenever we add more value in the amount

https://github.com/MetaMask/metamask-extension/assets/54408225/543d6048-171a-4edb-86fb-3ef921932d2c

Either we never display the Total section or we display it always (if so, the amount of tokens and decimals should be correct) cc @bschorchit 

### Steps to reproduce

1. Import an ERC20 token
2. Click Send
3. Add recipient
4. Add amount greater than the balance you have
5. See how the Total section appears with wrong amount/decimals

### Version

10.25.0 possibly earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/19681?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @NiranjanaBinoy @seaona @segun
