### ISSUE TITLE
ether/delta (No Private key) in RED How to fix this?

### ISSUE THREAD

**Issue by Jerry-L-M** [MetaMask/metamask-extension#1968]

**Comment by pitieu** [comment]
Normally you only need to log in(enter password), in your Metamask account and select the appropriate account. 
The selected account should be the same as in Etherdelta. 

If that doesn't work you can try forget the account in Etherdelta and add it again.
If that doesn't work try closing and reopening your browser completely. (That fixes things sometimes for me)

**Comment by Jerry-L-M** [comment]
When I got to ether/delta I get this message: You are using MetaMask but you are not logged in. Please log in to MetaMask and refresh. I can't figure out how to login to metamask without creating a new account.
On my Metamask account above the buy-send tabs are 3 dots. It used to be 4 icons, which one was in the form of a key. When I clicked on the key my private key would come up. Now when I click on the 3 dots a list of four options appear. 1. View account on etherscan. 2. Shoe QR code 3. Copy address to clipboard. 4 Export private key.
Regardless of which option I select I can't change in the far right corner of the page that reads in RED----- ether/delta (no private key). Earlier this week I somehow did get it to change but I could not remember what steps I used to do so. Has anyone ever heard of such a situation? and how to fix it.

**Comment by DanDan87** [comment]
@Jerry-L-M I'm having the same exact issue as you with the same error... is there any way you could try and find out what you did to fix this... I will reward you duly with some tokens my friend if you can help me. (same offer goes to anyone else). 

Thanks.

**Comment by Jerry-L-M** [comment]
Dan,

My best recollection is that I went into my Metamask, clicked on the three block dots to the right of my account to find export private key. Click on export private key. Retype in your password and click submit, then it says Your private key (click to copy). Put your cursor on your private key and it will move. Then click. Next on the etherdelta address in your browser window cause the cursor to be at the end of the address then hold down the control key + V and it should paste your private key into the browser window, Then hit enter. Your Metamask account should turn from red to green.

Jerry


________________________________

**Comment by Jerry-L-M** [comment]
Did you receive my fix for your problem?



________________________________

**Comment by DanDan87** [comment]
Hey Jerry,

I tried a few different things like logging off MetaMask and refreshing and trying to export private keys from ED and also re-logging back into MM and refreshing ED... it's a very bizarre problem. 

For example, I have a few like .05 ETH in both my MM account and as well as my ED account that shows up in the top right BUT when I log off of MetaMask both account balances show 0 ETH in the top right. (Also the ED account that says "No Private Key" is also in red instead of yellow; not sure if this matters or not).

So I'm thinking that the ED account is definitely linked to MM somehow, since the account balance goes to 0 when I log off MM but for whatever reason even though I know my 12 word seed phrase it's still not letting me withdraw.... perhaps I'm still missing something here? 

If you can figure this out I'd give you $200... perhaps we could schedule a time to meet (online or w/e via the github chat room for etherdelta) after work since this issue is a bit complex? I appreciate your time and effort.

**Comment by DanDan87** [comment]
Also.... I want to add... I've withdrawn from this account before.

**Comment by Jerry-L-M** [comment]
Dan,

I'd be glad to help you. I know how to get the red "No private key" to turn green saying "Metamask." I live in the central time zone of the USA so that should give you a time line where we can help you get this problem solved.

Jerry


________________________________

**Comment by Jerry-L-M** [comment]
Dan,

If we could have a private conversation, I think it would be better for both of us. There are some instructions I provide that I think may need to remain private. Email me at fieldsofwhite@msn.com

I will provide detailed steps to correct your problem.

Jerry


________________________________

**Comment by seriousleisure** [comment]
Jerry, 
I sent you an email asking for help as well.

**Comment by Jerry-L-M** [comment]
Do you have a Metamask account?



________________________________

**Comment by Jerry-L-M** [comment]
OK,

First log in to your Metamask account, click on the three (3) lacks dots to the right of your account.

Click export private key.

You now have to confirm your password. After you have confirmed your password,

You will see a statement that says: Your private key (click to copy)

Below that will be part of your private key in orange. Click on that number that represents your private key.

Now go to your browser in etherDelta and paste your private key at the end of the address on etherdelta.

If you have done everything correct, etherdelta will refresh and the red "no private key" will turn to a green "metamask."

your now ready to access your tokens and use the etherdelta exchange. Let me know it this solves your problem.

Jerry



________________________________

**Comment by ACBennett** [comment]
Sometimes MetaMask just gets confused.  If you're on the correct account but it's still showing red in EtherDelta,  just change to a test network in MM and back to the Main Network.  It will force EtherDelta to reload and you'll be good to go.

**Comment by Crypto5Star** [comment]
Hi Jerry and everyone,
A little help is needed here. The Red Ether/Delta Private Key is gone and my MetaMask is up green but how do I get the ETH back from the Red Ether/Delta Private Key?

**Comment by Crypto5Star** [comment]
I put in my address and private key but my ETH isn't showing. Now what can I do?

**Comment by Jerry-L-M** [comment]
If you have more than one account, each account requires its on source of eth.


________________________________

**Comment by Gurt01** [comment]
Jerry,

What do you exactly mean with: Now go to your browser in etherDelta and paste your private key at the end of the address on etherdelta.?

Thanks

**Comment by remymedranda** [comment]
I'm having a crazy issue. I have 2 wallets. EtherDelta and Metamask. I purchased some Kin on ED wallet, and I'm trying to withdraw, but keep getting error to disable Metamask. IF i disable Metamask the transaction /balance history goes away for me ED wallet. The only way to get it to show my balance is while the MetaMask is open.... Can someone give me a hand to getting this solved?

**Comment by Jerry-L-M** [comment]
I have discovered an easier way. Go to Metamask and sign in again. Your provide your password and open your account. Then simply refresh etherdelta and you will be green.



________________________________

**Comment by remymedranda** [comment]
I got it to behave lol... after like 5 times of disabling, and reloading... NOW it shows my balance, and ED wallet green, not orange...

**Comment by Jerry-L-M** [comment]
Dan,

Did you get this problem solved?

Jerry


________________________________

**Comment by Jerry-L-M** [comment]
There are problems with ED right now. What I am hearing is to be able to withdraw or transfer it requires much more gas to make the transaction happen. I have heard one guy raise the gas from 4 to 26. To me that is ridiculous.


________________________________

**Comment by Jerry-L-M** [comment]
Just remember that you must open your Metamask account first and then refresh the etherdelta website to get your account to turn green.



________________________________

**Comment by remymedranda** [comment]
https://ethgasstation.info/

**Comment by tmashuang** [comment]
Closing old issue, https://metamask.helpscoutdocs.com/article/8-etherdelta-account-management-tips.
