### ISSUE TITLE
[Bug]: wallet closes when opening

### ISSUE THREAD

**Issue by koltigin** [MetaMask/metamask-extension#19696]
### Describe the bug

While making a transaction or pressing the mint button, the wallet seems to open, but suddenly it closes. When I press the button for the second time, the wallet opens. It's been like this for the past week. Annoying. I'm using chrome and brave browser on iOS and both have this issue.

### Steps to reproduce

1.The problem is as I wrote above.

### Version

10.32.0

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by HowardBraham** [comment]
If you could add more detailed steps, the sites you're testing on, or maybe a video, it would be very helpful.

**Comment by koltigin** [comment]
I'm trying to shoot it but I don't know when it will happen. Even on some mainnet sites, some processes freeze. I'm trying to deactivate the wallet and re-transaction.

**Comment by danjm** [comment]
> I'm using chrome and brave browser on iOS and both have this issue.

@koltigin Are you using these browsers on a mobile device?
