### ISSUE TITLE
{"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"message\":\"Internal Server Error\"}}[Bug]: 

### ISSUE THREAD

**Issue by TomWang1** [MetaMask/metamask-extension#19697]
### Describe the bug

Returned error: {"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"message\":\"Internal Server Error\"}}}'","id":4653223632683671}

### Steps to reproduce

1.
连接了arbitrum Goerli进行发币测试,
 errored: Returned error: {"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"message\":\"Internal Server Error\"}}}'","id":4653223632683613}

### Version

10.31.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @TomWang1. Thanks for reporting! Could you please provide more details about your issue, such as where you encounter this issue, on what dapp and what are the steps you took to produce this? Thank you!

**Comment by RutvikGujarati** [comment]
I am facing same error on polygon with 2 days .

# Returned error: {"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"transaction underpriced\"}}}'","id":5320817586457629}

this error was shows when i want to deploy smart contract.

**Comment by AndreAnselmo** [comment]
I am having the same problem, in the deployment of the smart contract (metaMask testnet):      "creation of  errored: Returned error": {"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"message\":\"Internal Server Error\"}}}'","id":5305674733413297}

**Comment by TomWang1** [comment]
> Hello, @TomWang1. Thanks for reporting! Could you please provide more details about your issue, such as where you encounter this issue, on what dapp and what are the steps you took to produce this? Thank you!

我是在https://remix.ethereum.org/   这上面进行发币操作遇到的

**Comment by TomWang1** [comment]
> 

You should raise the GAS fee to solve it,

**Comment by TomWang1** [comment]
> I am facing same error on polygon with 2 days .
> 
> Returned error: {"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}'","id":5320817586457629}
> 
> this error was shows when i want to deploy smart contract.

You should raise the GAS fee to solve it,

**Comment by TomWang1** [comment]
> I'm having the same problem, in deploying smart contract Remix Ethereum pragma solidity ^0.8.19; vs (metaMask testnet): "creation of errored: Returned error": {"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"Internal Server Error"}}}'","id":5305674733413297}
me too

**Comment by TomWang1** [comment]
> I'm having the same problem, in deploying smart contract Remix Ethereum pragma solidity ^0.8.19; vs (metaMask testnet): "creation of errored: Returned error": {"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"Internal Server Error"}}}'","id":5305674733413297}

me too

**Comment by danjm** [comment]
> 我是在https://remix.ethereum.org/ 这上面进行发币操作遇到的

> I encountered it when I issued coins on https://remix.ethereum.org/

**Comment by AndreAnselmo** [comment]
Estou tendo o mesmo problema, ao implantar o smart contract Remix Ethereum pragma solidity ^0.8.19; vs (metaMask testnet): "criação de errored: Returned error": {"jsonrpc":"2.0","error":"[ethjs-query] ao formatar saídas de RPC '{"value":{"code": -32603,"data":{"message":"Erro interno do servidor"}}}'","id":5305674733413297}
Eu o encontrei quando emiti moedas em https://remix.ethereum.org/

**Comment by vandan** [comment]
This issue is no longer reproducible. See [our notes](https://github.com/MetaMask/metamask-improvement-proposals/pull/36#issuecomment-1991790792) for the detail about why the issue is resolved.
