### ISSUE TITLE
[Bug]: Error: Invariant failed: A state mutation detected inside a dispatch  

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#19706]
### Describe the bug

Observed an error in Firefox 114, on ventura 13.4 with feature branch of PR 19283 testing commit https://github.com/MetaMask/metamask-extension/commit/d6771db503600db9ec8970ee8161cc71e4e2c1a7 built locally. This was not observed on Chrome, just firefox.

Videos:
Feature branch before merged to develop: https://recordit.co/AegOKk9Xtt
~Production v10.31.1 does not produce this error: http://recordit.co/HLO7VchHjB~
Debug build of v10.31.1 does show the issue and indicates that this is in production but error only presents on debug build: https://recordit.co/eI2EnnRQjt
Develop commit (prior to merging PR 19283) https://github.com/MetaMask/metamask-extension/commit/488f212d289467673b9859d25521f023ce7b312b DOES show this error: https://recordit.co/oFGklrxCTx

May have some relation to earlier report, but reproduction steps are different: https://github.com/MetaMask/metamask-extension/issues/19205

### Steps to reproduce

1) Use debug build and configure a new wallet
2) Access settings> Security and Privacy
3) Tap to reveal Secret Recovery Phrase
4) Complete the new quiz
5) Tap and hold CTA to reveal SRP
6) Observe error

### Error messages or log output

![Screenshot](https://github.com/MetaMask/metamask-extension/assets/32695229/05a994f0-2368-43d3-9c2c-7f69778054e2)

### Version

10.31.1

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Firefox

### Operating system

MacOS

### Additional context

Initially I was not seeing this on production in build 10.31.1, but on further review it can be reproduced on a debug build of 10.31.1.

**Comment by AlexJupiter** [comment]
This is low priority @HowardBraham will confirm if this still exists. If it doesn't and has been fixed we can close. If not we can keep in backlog for now and unassign @HowardBraham .

**Comment by HowardBraham** [comment]
When @AlexJupiter and I were discussing this, I said I think I may have fixed this, but I don't 100% remember.  Just researched it, and it's fixed by #20109.

**Comment by plasmacorral** [comment]
Can confirm that on both Chrome 116 and Firefox 116 on mac ventura 13.5 that this issue no longer appears in commit 6f1c4c42113bf7c7a3ee5b30cbb823a8f2be0127
