### ISSUE TITLE
[Bug]: The SRP reveal button does not always work when the user has the extension installed in the Kiwi mobile browser on their mobile device

### ISSUE THREAD

**Issue by tayvano** [MetaMask/metamask-extension#19711]
### Describe the bug

A video of the issue can be found here: https://twitter.com/Loligarg7/status/1671566739023482881

Essentially you tap to hold the button but nothing is ever revealed (thank goodness in this case 😅😅😅😅😅)

I'm guessing the handling for the event (onMouseUp??????????) that is being used to trigger the reveal in Chrome/FIrefox is not supported by Kiwi Browser or not handled in the same way given the mobile (touch) enivro

### Steps to reproduce

1. Go to settings to reveal your SRP
2. Press and hold the "hold to reveal SRP" button
3. The SRP is not revealed after the allotted time

### Version

unknown, relatively recent

### Browser / Operating system

MetaMask installed as Kiwi Browser Extension on Android devices

**Comment by tayvano** [comment]
**There's still a decent flow of support tickets coming in about this, including 2 from today.**

> I use the metamask extension on both Kiwi browser and Mises browser. I tried to reveal my seed phrase so that I can copy it out, but the reveal button doesn't work. Please how do I solve this?

We do not recommend using Metamask as an extension on your mobile, on a browser. You can download the Metamask mobile app here.

> I created the wallet via this extension. Does this mean my situation is hopeless?

No, you restore your wallet on your Metamask app and use it there: How to restore your MetaMask wallet from Secret Recovery Phrase

> I can't restore in the app because I am unavailable to gain access to the seed phrase from the extension sir

And you never saved your Secret Recovery Phrase (seedphrase)? 😅

> I did but lost it 🥺

I'm sorry to hear that! I can elevate this issue to our technical team so they can take a more in-depth look with you.

**Comment by tayvano** [comment]
This issue should be resolved with [#19847](https://github.com/MetaMask/metamask-extension/pull/19847) which should be included in the 10.35 release.

As of today (july 17), the latest release is 10.33.1. Most users should simply wait until the 10.35 release goes live.

Users who **do not** have another backup of their secret recovery phrase **SHOULD NOT** attempt to load 10.35 into Kiwi outside their normal flow.

Power users who **do** have a secondary backup of their current SRP or devs who wish to test the fix can attempt to load the 10.35 build into Kiwi from a zip or folder.

**Comment by Virtue958** [comment]
I am currently going through the same issue right now and I am in fears of losing my wallet with my assets in it because of no other backup with me

**Comment by odaisagod** [comment]
I am currently going through exactly the same issue, my SRP can't reveal on my mobile app, I've made ticket issue on https://metamask.zendesk.com/hc/requests/1171240 please solve it before 11 May 2024, because I have airdrop going on.
