### ISSUE TITLE
[Bug]: no pricing displayed for $CIC, native asset that represents the CIC Chain. 

### ISSUE THREAD

**Issue by DrEvil85** [MetaMask/metamask-extension#19729]
### Describe the bug

CIC chain is a hybrid layer 1 Blockchain that is EVM compatible. After adding the main-net details to metamask wallet via chain list or manually adding the network, the native asset that represents the CIC chain $CIC is shown. It displays the correct amount of coins however the pricing data is not correct. 

https://www.coingecko.com/en/coins/crazy-internet-coin

https://coinmarketcap.com/currencies/crazy-internet-coin/

https://chainlist.org/chain/1353

I've contacted Coingecko and they have refreshed the price data twice now. 

### Steps to reproduce

1. Go to settings on metamask
2. Select networks
3. Click on "Add Network" at the bottom
4. At the top, select custom network. 
5. Fill in the details using this info....
6. Network name - CIC Chain
7. RPC URL - https://xapi.cicscan.com
8. Chain ID - 1353
9. Symbol - CIC
10. Block Explorer URL - https://CICscan.com
11. Next Select "Add"

Once you've successfully added CIC chains network to metamask, if you hold any coins, it will display all your coins correctly. However the pricing data is wrong. It shows a 0 value. 

### Error messages or log output

```shell
No error data present
```

### Version

7.0.1

### Build type

None

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS

**Comment by hesterbruikman** [comment]
Adding other cases reported:
https://chainlist.org/chain/500
https://chainlist.org/chain/1116

**Comment by DrEvil85** [comment]
I'm not sure how, or whom to thank, but the pricingnis displaying correctly now.
