### ISSUE TITLE
Tx Controller - issues stuck in approved

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#1975]
its (somehow) possible for a tx to get stuck in approved. we should re-attempt to sign this , e.g. on startup

**Comment by kumavis** [comment]
also investigate how we might have missed catching an error and migrating to failed

**Comment by frankiebee** [comment]
i dont know... we've seen from user issues that an update could happen way after publish id rather focus on failing a tx that isnt signed then auto signing it

**Comment by danfinlay** [comment]
This was just fixed.
