### ISSUE TITLE
Verify `MetaMask: Bridge Router` contract on all Etherscan instances

### ISSUE THREAD

**Issue by pcaversaccio** [MetaMask/metamask-extension#19760]
### Describe the bug

I am really having a hard time understanding why MM cannot get his router verified after more than 250 days since it was deployed. If you consider yourself to be a crucial piece of Ethereum's infrastructure, lead by example, please! https://etherscan.io/address/0x82E0b8cDD80Af5930c4452c684E71c861148Ec8A#code

### Steps to reproduce

Go to https://etherscan.io/address/0x82E0b8cDD80Af5930c4452c684E71c861148Ec8A#code and check if the contract is verified :)

### Version

`10.31.1`

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello, @pcaversaccio. Thanks for your suggestion! I will pass it on to the team.

**Comment by pcaversaccio** [comment]
Ok, it got verified.
