### ISSUE TITLE
Metamask notification window disappears when confirming transaction with keystone pro

### ISSUE THREAD

**Issue by cacustr** [MetaMask/metamask-extension#19780]
### Describe the bug

When confirming a transaction the notification windows sometimes disappears, ie. when using uniswap/curve, but not using send (or swap with metamask for that matter). Clicking on the metamask icon brings back the window (it's annoying but no show stopper).

Confirmed as bug after talking to Zoe V on metamask support -> ticket 1053688.

Screenshot of disappearing window:
![Screenshot 2023-06-27 111123](https://github.com/MetaMask/metamask-extension/assets/137880858/c402d130-b468-4d85-a97a-ad2a97b2d373)

### Steps to reproduce

1.Go to uniswap.org
2.Initiate swap with a Keystone Pro HW wallet connected
3.Click 'Confirm' in the Notification window that appears
4. The window closes (might have to do it a few times before it happens)
5. Clicking on the metamask icon (pinned extension) brings back the window
 

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Hardware wallet

Keystone

**Comment by cacustr** [comment]
Video of bug (on macos, same problem there), with new chrome profile, and no other extensions:
https://github.com/MetaMask/metamask-extension/assets/137880858/09fb8444-6990-4dc4-a392-9ac64e563c29

**Comment by cacustr** [comment]
So, any update on this issue yet?

**Comment by plasmacorral** [comment]
@cacustr Thank you for your report and for following up, and I am sorry for the delay.  We have been able to reproduce the issue and it is in queue to be worked as resources become available.  As a Keystone user, I recognize that it is annoying but it may be tough to prioritize given the fact that transactions can still be completed with an extra click.

**Comment by HowardBraham** [comment]
Simplified method to reproduce:
1. Use any QR wallet (AirGap Vault is free)
2. Go to https://metamask.github.io/test-dapp/
3. Use any of the Sign methods (useful for testing because they do not require gas in your account)
4. Click 'Sign' in the Notification window that appears
5. The window closes
6. Clicking on the MetaMask icon (pinned extension) brings back the window

**Comment by cacustr** [comment]
Why would you close the issue? You have recognized it as a low priority bug....it has been 90 days and still no fix, but no reason to close??

**Comment by Suffuze** [comment]
Yes a very annoying bug indeed. Please fix!! Only even got a Keystone because you guys never added support for the NanoX even though you announced it 2 years ago.. Forshame
