### ISSUE TITLE
[Bug]: Polygon zkEVM network shows gas estimation error anytime trying to send a tx

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19786]
### Describe the bug

**Problem**: whenever we are using Polygon zkEVM or Polygon zkEVM Testnet, if we try to send a transaction we see a gas estimation error.
I've seen that no request is sent to the gas api (maybe chainId is not supported?) however we do receive the RPC responses successfully.

These networks are EVM compatible to Ethereum L1.

https://github.com/MetaMask/metamask-extension/assets/54408225/a79faf90-f27e-4c80-a3cf-4f33e3311542

### Steps to reproduce

1. Import Polygon zkEVM or Polygon zkEVM testnet 
2. Click Send
3. Add recipient
4. See gas error
5. Click Next
6. See gas error

### Version

10.33.0 - not happening on 10.32.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Gudahtt** [comment]
This might be fixed by https://github.com/MetaMask/metamask-extension/pull/19746

**Comment by seaona** [comment]
I confirm is fixed @Gudahtt  thank you!! I close the issue
