### ISSUE TITLE
[Bug]: Loading screen always displays in white background although theme is set to dark or system

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#19790]
### Describe the bug

When using a HW wallet account and clicking on the Swap button a loading screen is shown for less then a second. If in the setting I set the Theme to Dark or System(which is also dark)  the screen is always white. See the video

https://github.com/MetaMask/metamask-extension/assets/6082863/2e792592-4982-4dd5-9a3c-bc7b3fe2979c

### Steps to reproduce

1. Import a hardware wallet account 
2. Click on Swap

### Version

10.33.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

Ledger, Trezor

**Comment by seaona** [comment]
Same/similar as https://github.com/MetaMask/metamask-extension/issues/15739

**Comment by kevinghim** [comment]
@dan437 do you mind looking into this?
