### ISSUE TITLE
Condition of my account that says: Ether/Delta (No Private Key)

### ISSUE THREAD

**Issue by Jerry-L-M** [MetaMask/metamask-extension#1979]
When I got to ether/delta I get this message: You are using MetaMask but you are not logged in. Please log in to MetaMask and refresh. I can't figure out how to login to metamask without creating a new account.
On my Metamask account above the buy-send tabs are 3 dots. It used to be 4 icons, which one was in the form of a key. When I clicked on the key my private key would come up. Now when I click on the 3 dots a list of four options appear. 
1. View account on etherscan. 
2. Shoe QR code 
3. Copy address to clipboard. 
4 Export private key.
Regardless of which option I select I can't **change** the far right corner of the page that reads in RED----- ether/delta (no private key). Earlier this week I somehow did get it to change but I could not remember what steps I used to do so. Has anyone ever heard of such a situation? and how to fix it.

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by mannypanther** [comment]
I'm Having the exact same problem, someone please help

**Comment by flyswatter** [comment]
This is such a common problem with EtherDelta, I recently wrote a guide to it:
https://support.metamask.io/kb/article/21-etherdelta-account-management
