### ISSUE TITLE
[Bug]: Cannot change to Linea Goerli network: `Invalid Infura provider type linea-goerli`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19805]
### Describe the bug

**Problem:** whenever I try to change to Linea Goerli network, I can see how the network is not changed and I get the following console error `Invalid Infura provider type linea-goerli`.

I've checked if my Infura key was correct, and I could see how the same key is working fine for me in `master` or 10.33.0 branch but not in `develop` doing `yarn start`.

https://github.com/MetaMask/metamask-extension/assets/54408225/e3dee0e5-39d5-4598-a0fc-2994060bf71c

### Steps to reproduce

1. Open MM
2. Change to Linea Goerli network
3. See how network is not changed
4. See console error `Invalid Infura provider type linea-goerli`

### Version

seems to be working fine in 10.33.0 but not in develop

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by PeterYinusa** [comment]
See https://github.com/MetaMask/metamask-extension/issues/19906#issuecomment-1625093868
