### ISSUE TITLE
[Bug]: 'currentRpcUrlDeprecated' to can't open metamask

### ISSUE THREAD

**Issue by richard9219** [MetaMask/metamask-extension#19813]
### Describe the bug

1)I accidentally clicked on the abandoned network (rinkeby), It popups an error "currentRpcUrlDeprecated"(此网络的当前 RPC URL 已被弃用), then I switch to ethereum, It costs a lot time. 
2)Then I restart the google chrome, It's the same, and worse， the account is locked.
<img width="345" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/15854055/2a0c2ab1-d2aa-49ff-9b0d-5cbee6bcec41">
3) now, I can only do is switch the network, and It always failed
4) Unfortunately，I did not backup my seeds/account for the wallets.
5) As a suggestion, the currentRpcUrlDeprecated with a hint Pop-up for an unsed network(like rinkeby) is a very bad product design. 

### Steps to reproduce

1.clicked on the abandoned network (rinkeby)

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Closing this in favor of #19564
