### ISSUE TITLE
[Bug]: Loading Extension fails with Lavamoat package not in whitelist error

### ISSUE THREAD

**Issue by dhruvv173** [MetaMask/metamask-extension#19818]
### Describe the bug

Unable to use locally built application.
The `dev mode` build works fine but test build doesnt. This prevents me from running e2e tests locally.

- Windows 11
- Yarn 3.2.4
- Chrome 114.0.5735.199
- Node 16.20.0

### Steps to reproduce

1. Follow instructions in README to build a test app for e2e tests
2. Follow instructions to add build to chrome

### Error messages or log output

```shell
`LavaMoat - required package not in allowlist: package "@metamask/eth-trezor-keyring>@trezor/connect-web>@trezor/connect" requested "browserify>events" as "events"`
```

### Version

building on latest fork from develop

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

Windows

### Additional context

Saw similar issues reported by other users but couldnt find a concrete solution.

**Comment by anaamolnar** [comment]
Hey, @dhruvv173. Thanks for reporting! I will pass this on to the team.

**Comment by dhruvv173** [comment]
> Hey, @dhruvv173. Thanks for reporting! I will pass this on to the team.

thanks alot, appreciate it!
