### ISSUE TITLE
[Bug]: Error message in metamask extension cannot be closed and prevents the extnsion from working

### ISSUE THREAD

**Issue by meliknursan** [MetaMask/metamask-extension#19821]
### Describe the bug

when I change network to Rinkeby it stucked, I can do nothing with it , canot exit or close the popup

The X to close the error does not work.
There is a button called "Switch Networks" but selecting his opens the network selection list behind the error and keeps the error on the screen.

The extension now cannot be used at all.

**The proposed solution (inspecting the extension and deleting the popup html) does not work in Firefox.
It's not possible to inspect the extension html.**

![Screenshot_1](https://github.com/MetaMask/metamask-extension/assets/137908845/773514f4-169a-4834-97aa-df0272bae31f)
![Screenshot_2](https://github.com/MetaMask/metamask-extension/assets/137908845/96be045d-3ea6-4a8e-9b3c-d187f01ffb8a)

### Steps to reproduce

1. Select a depreciated network.
2. Get the popup saying "The current rpc url for this network has been deprecated."
3. You will no longer be able to use the extension.

### Version

10.31.1

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by perplexedpigmy** [comment]
Are there any news?  Workarounds? anything?
Looks like on chrome elements can be removed using devtools which may allow interacting with the extensions.
 Firefox is a different beast.

**Comment by meliknursan** [comment]
> I realized that re-installing may remove all

In Frifox, "popover-content" cannot be deleted because Metamask does not open in a new window. More precisely, it cannot be selected.

Let me tell you the solution I found. When you connect the wallet using the Syncswap site, a new window opens in Metamask. Press f12 on that window and follow the other steps exactly.

**Comment by meliknursan** [comment]
> Are there any news? Workarounds? Looks like on chrome extension elements can be removed using the devtools which may allow interacting with the extensions. Firefox is a different beast and this can't work for it. It will be great if anyone with good metamask knowledge can suggest a solution to get the extension working again.
> 
> It's a huge headache, all the wallets have to be re-imported/created, all network added, tokens re-imported for all networks, and all addresses added and verified. Maybe it will be easier for me just to update metmassk myself, than do all that...
> 
> **Update 1:** I realized that re-installing may remove all data, or the data may not be accessible.
> 
> This may be a workaround for firefox https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html#Debugging_popups
> 
> **Update 2:** With firefox it's slightly more involved but essentially it's the same workaround as described @ https://community.metamask.io/t/metamask-error-doesnt-go-away-and-prevents-me-using-the-extension/25909/10

In Frifox, "popover-content" cannot be deleted because Metamask does not open in a new window. More precisely, it cannot be selected.

Let me tell you the solution I found. When you connect the wallet using the Syncswap site, a new window opens in Metamask. Press f12 on that window and follow the other steps exactly.

**Comment by anaamolnar** [comment]
Hello @meliknursan, Thanks for your report. This should be fixed with the latest version of the extension, so I will close this issue. Feel free to open it again if the issue continues after updating. Thank you!
