### ISSUE TITLE
Fix flaky test Sign Typed Data Signature Request can initiate and confirm a Signature Request of Sign Typed Data

### ISSUE THREAD

**Issue by DDDDDanica** [MetaMask/metamask-extension#19823]
**Error message:**
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101352/workflows/fb633881-146a-4682-8fe3-d865fc6bc5f0/jobs/3773393

**Comment by pnarayanaswamy** [comment]
This one flaked not due to a test issue but an issue on the CI, subsequent re-run of the test passed and the test has not flaked for over 13 days.

```
Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /home/circleci/project/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,firefox,--output,json,--browser-path,/opt/firefox/firefox: request or response body error: error reading a body from connection: stream error received: unexpected internal error encountered
```

**Comment by pnarayanaswamy** [comment]
The tests however needed a small improvement that resulted in better execution times and are addressed in the PR https://github.com/MetaMask/metamask-extension/pull/27532
