### ISSUE TITLE
[Bug]: MetaMask Connect Button Intermittently Missing or Non-Responsive in Chrome

### ISSUE THREAD

**Issue by avalan4e57** [MetaMask/metamask-extension#19839]
### Describe the bug

There are two intermittent issues with the MetaMask extension on Chrome when interacting with various Web3 apps, and while using the MetaMask API:

1. Sometimes, the button to connect MetaMask is not present, as though MetaMask is not installed.
2. Other times, the button is present, but clicking on it does not open the MetaMask browser extension, and does not trigger the MetaMask API call `window.ethereum.request({ method: 'eth_requestAccounts' })`.

These issues can be reproduced across different Web3 apps, and also when using the basic MetaMask API. For example, on the Wagmi site at https://wagmi.sh/examples/connect-wallet. The issues do not always occur and it is unpredictable which of the two scenarios will occur. These issues do not occur in Firefox or Brave.

### Steps to reproduce

1. Open a new tab in Chrome (Version 114.0.5735.133 (Official Build) (arm64)).
2. Navigate to a site with a button to connect MetaMask, for instance, https://wagmi.sh/examples/connect-wallet.
3. Note whether the button is present, and if so, what happens when you click it.

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Refreshing the page usually fixes the issue. However, the issue frequently occurs when a web3 app is initially loaded in a new tab.

**Comment by geeksq** [comment]
having the same problem here on following browsers on M1 mac:

Chrome 114.0.5735.198 (Official Build) (arm64) on MacOS 13.4.1
Brave browser [Version 1.52.129 Chromium: 114.0.5735.198 (Official Build) (arm64)] as well. 

Both browsers are on Metamask 10.32.0 and sites affected include opensea.io and swap.cow.fi etc.
It's that bad, the Metamask popup supposed to present a button to sign approvals, but all I get is a spinning circle without any button.
<img width="472" alt="metamaskerr" src="https://github.com/MetaMask/metamask-extension/assets/110708165/b10f66ac-cb4d-4c4c-b2fb-70b47163f2f2">

Using the same M1 computer, with Firefox + Metamask 10.31.1 did not encounter such issues.

**Comment by geraldchen890806** [comment]
> having the same problem here on following browsers on M1 mac:
> 
> Chrome 114.0.5735.198 (Official Build) (arm64) on MacOS 13.4.1 Brave browser [Version 1.52.129 Chromium: 114.0.5735.198 (Official Build) (arm64)] as well.
> 
> Both browsers are on Metamask 10.32.0 and sites affected include opensea.io and swap.cow.fi etc. It's that bad, the Metamask popup supposed to present a button to sign approvals, but all I get is a spinning circle without any button. <img alt="metamaskerr" width="472" src="https://user-images.githubusercontent.com/110708165/250359936-b10f66ac-cb4d-4c4c-b2fb-70b47163f2f2.png">
> 
> Using the same M1 computer, with Firefox + Metamask 10.31.1 did not encounter such issues.

https://github.com/MetaMask/metamask-extension/issues/19826

**Comment by geraldchen890806** [comment]
> ### Describe the bug
> There are two intermittent issues with the MetaMask extension on Chrome when interacting with various Web3 apps, and while using the MetaMask API:
> 
> 1. Sometimes, the button to connect MetaMask is not present, as though MetaMask is not installed.
> 2. Other times, the button is present, but clicking on it does not open the MetaMask browser extension, and does not trigger the MetaMask API call `window.ethereum.request({ method: 'eth_requestAccounts' })`.
> 
> These issues can be reproduced across different Web3 apps, and also when using the basic MetaMask API. For example, on the Wagmi site at https://wagmi.sh/examples/connect-wallet. The issues do not always occur and it is unpredictable which of the two scenarios will occur. These issues do not occur in Firefox or Brave.
> 
> ### Steps to reproduce
> 1. Open a new tab in Chrome (Version 114.0.5735.133 (Official Build) (arm64)).
> 2. Navigate to a site with a button to connect MetaMask, for instance, https://wagmi.sh/examples/connect-wallet.
> 3. Note whether the button is present, and if so, what happens when you click it.
> 
> ### Error messages or log output
> _No response_
> 
> ### Version
> 10.32.0
> 
> ### Build type
> None
> 
> ### Browser
> Chrome
> 
> ### Operating system
> MacOS
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> Refreshing the page usually fixes the issue. However, the issue frequently occurs when a web3 app is initially loaded in a new tab.

I have the same issue, and it seems to occur more often when I open Chrome for the first time. I suspect it is related to Chrome's preloading. I hope it can be resolved.

**Comment by anaamolnar** [comment]
Hey, @avalan4e57. Thanks for reporting! Are you still getting this issue on 10.34.0? You should be able to update manually in Chrome to get this version. Please let me know. Thanks!

**Comment by jiexi** [comment]
Hi, @avalan4e57. Thanks for reporting this. I'm having difficulty reproducing this error.

If you're still experiencing this issue, could you help us verify something by disabling preloading in your Chrome settings? This can achieved by:
1. Opening chrome settings
2. Searching for "Preload"
3. Toggling the "Preload pages" setting to off

After you do this, are you still able to reproduce the bug you are seeing?

Thank you!

**Comment by jiexi** [comment]
> I have the same issue, and it seems to occur more often when I open Chrome for the first time. I suspect it is related to Chrome's preloading.
I hope it can be resolved.

@geraldchen890806 to confirm, is this comment in response to this issue or https://github.com/MetaMask/metamask-extension/issues/19826?
