### ISSUE TITLE
 Unable to connect/open Metamask 

### ISSUE THREAD

**Issue by mightypai** [MetaMask/metamask-extension#1983]
I am unable to connect to Main Ethereum Network or any network, when I click on the extension it just won't open, and it just tries to "connecting to Main Ethereum Network" ...
I don't know if it's due to to my internet connections or to he fact that I cleared my dns recently

Pls Help !

 *  Expected Behavior : to Connect
  *  Actual Behavior: just won't connect and won't open
  *  Browser Used: Chrome
  *  Operating System Used: Windows 10

**Comment by flyswatter** [comment]
When you click the top left spinner (the provider menu), which network is selected? Can you select a different network, and then switch back? Does that fix the problem?

If not, changing your DNS *might* create a problem here. You can also select "Custom RPC" in that menu and point at any other specific provider address, including custom ones.

**Comment by JesseBusman** [comment]
I still have this problem in version 3.10.9. I haven't been able to find a solid way to reproduce it yet, but it does happen regularly. Switching to a different network and back works.

**Comment by adevadeh** [comment]
I also can report that switching to a different network then back seems to work.

**Comment by bruciebruce** [comment]
Switching to Ropsten and back to either localhost:8545 and/or http://127.0.0.1:8545 **does not work** for me. Using -- Truffle v3.4.9 - a development framework for Ethereum.  Windows 10 Home Edition.

**Comment by danfinlay** [comment]
@bruciebrucie first of all, you’re not my local Bruce MacDonald, are you? I can’t imagine him doing a Truffle tutorial.

Are you getting the same spinner as everyone else in this thread? If not, it sounds like a different issue.

Sorry we will be slow to reply to most things over these holidays.

**Comment by bruciebruce** [comment]
Now why wouldn't he be doing a truffle tutorial?  What else is there to do?  I will follow up later with more details but basically I am under the assumption that metamask should 'invoke' from within the pet box app which it does not.  I am not getting a spinner.

**Comment by bruciebruce** [comment]
I an using Truffle v3.4.9 on Windows 10 Home Edition.  I tried this with Truffle 4.04 as well but with similar results.  Using latest Chrome w/ MM plugin.

**Comment by HGBG** [comment]
@bruciebruce  having the same issue. Have you found a solution to it?

**Comment by tawfeeqzaghlool** [comment]
I had the same issue, but I solve it in the following steps:
1- Choose Custom RPC.
2- Retype your localhost number ==> http://lcalhost<The number>.
3- Click back. you can see it is solved

**Comment by auser** [comment]
I'm still having this problem.

Solutions I've tried:

* Reinstalling metamask
* Reinstalling Ganache
* Resetting Chrome

Nothing seems to work... I'm not sure why it's not connecting... are there any debug logs or verbosity setting I can try to see if I can debug this? Any help would be awesome!

**Comment by tawfeeqzaghlool** [comment]
Describe the issue please...

**Comment by auser** [comment]
Of course. My apologies. 

Whenever I submit a transaction, meta mask shows the loading circle endlessly. It connects fine to the network before submitting a transaction, but whenever I submit one to the network, nothing. It just loads. Endlessly. 

This is kind of a blocking issue for me to use metamask in my app as I cannot actually ship a transaction. 

One caveat: I have been able to submit a single transaction in the past. 

These are all on a private network.

**Comment by tawfeeqzaghlool** [comment]
I understood now, listen, try to connect to private manually by doing these steps: 
1- Choose Custom RPC.
2- Retype your localhost number ==> http://lcalhost. 
3- Click back. you can see it is solved.
4- Don't uninstall chrome or metamask or even Ganache, 
in the end it seems like you manipulate the private host, got it?

**Comment by auser** [comment]
I have done this many times. I have changed the port on ganache several times too in hopes it would fix it, but nothing works unless I reset everything when it works a single time.

**Comment by auser** [comment]
... and then fails again as I described previously

**Comment by tawfeeqzaghlool** [comment]
I wish I can help more, but you have to think in these things to solve it: 
1- The host and the port number of the private localhost.
2- Match the number with the Ganache.

**Comment by johncrisostomo** [comment]
I am also having this issue, but with a PrivateNet that is hosted on a different computer. I know that it might be a MetaMask / protocol issue because Mist can connect to it (both on local computer and another computer on the network). 

When I tried to inspect the background page / logs from Chrome's development tools, it seems that MetaMask is still trying to connect to `http://localhost:7545` which is a different RPC address from where I want to connect. However, if I open Ganache and tried to connect to it, MetaMask works.

Any ideas will be highly appreciated. This is how I start my PrivateNet, btw:

```
geth --datadir gethdata --networkid 15 --rpcport 8888 --ipcdisable --rpc --rpcaddr 0.0.0.0 --rpcapi "admin,db,eth,debug,miner,personal,web3"
```

**Comment by DrShanti** [comment]
for mine; only blank screen appear, no network sign, no loading sign...
![00](https://user-images.githubusercontent.com/30644058/41808145-8bc184ba-7703-11e8-8831-6e198f0aef1b.png)

**Comment by danfinlay** [comment]
@DrShanti Please open a new issue or email support at support [at] metamask.io, so we can debug your issue individually. This issue is closed/old, and was probably a different bug.
