### ISSUE TITLE
Show warning message if user tries to add their own address as token

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#1984]
A common mistake, a good validation.

**Comment by flyswatter** [comment]
Could also detect if the address has code at it or not, and then link to a "what is a token address" article.

**Comment by Zanibas** [comment]
Will also improve wording to say "Token Contract Address"

**Comment by tmashuang** [comment]
Fixed, https://github.com/MetaMask/metamask-extension/pull/2048
