### ISSUE TITLE
[Bug]: UI ements is now too big cutting the warning popup

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19849]
### Describe the bug

**Problem**: whenever I try an eth_sign I can see how the warning is now too big, cutting it on the popup display. I can see how the MetaMask fox is bigger, as well as other elements in the UI (not sure if it's expected this).

[Screencast from 30-06-23 17:28:30.webm](https://github.com/MetaMask/metamask-extension/assets/54408225/4fb56238-99a3-4118-b6c8-d291b76237a8)

### Steps to reproduce

1. Go to test dapp
2. Click Eth Sign
3. Accept Signature
4. See warning is cut

### Version

`develop` not in 10.33.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by kevinghim** [comment]
This has been resolved through the latest update.
