### ISSUE TITLE
[Bug]: Metamask die when failed RPC specified in chosen network (Ropsten)

### ISSUE THREAD

**Issue by maslen4ik** [MetaMask/metamask-extension#19865]
### Describe the bug

![image](https://github.com/MetaMask/metamask-extension/assets/88964386/773c1114-df07-4a2d-a74c-3b5bda7e4b83)

Switching network to Ropsten network (added far ago) sent extension to dead loop and made it unusable anymore. Annoying popup window ask to switch network due to RPC error but pressing switch button do nothing, meanwhile there is no way to close popup window. Browser restart does not help. No way to pass popup window to get in settings or whatever.

Firefox Portable version 113.0.2
Windows 10 x64 LTSC build 17763

### Steps to reproduce

1. Add Ropsten network few year ago choosing among networks offered by Metamask networks.
2. Switch network to Ropsten.

### Error messages or log output

```shell
The current rpc url for this network has been deprecated.
```

### Version

no way to check

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by daweth** [comment]
Have the same issue, I can't use the extension anymore.

**Comment by daweth** [comment]
It's impossible to close the popup. Maybe someone can try fixing that as a start?

**Comment by daweth** [comment]
Looks like to be this function causing the issue.

https://github.com/MetaMask/metamask-extension/blob/c0483e118d4294e07b82a170937f0d57029a836b/ui/components/app/loading-network-screen/loading-network-screen.component.js#L76

the popover does not close when the X is clicked

**Comment by daweth** [comment]
@danjm  @ryanml  @darkwing 

Seems like you guys were closely involved in this ? Want to take a look?

**Comment by maslen4ik** [comment]
New version has released but this bug is still here and my metamask unusable.

**Comment by ChipSurfer1** [comment]
Hi, I have the same issue, is there a fix for this available? There is one here: https://community.metamask.io/t/metamask-error-doesnt-go-away-and-prevents-me-using-the-extension/25909/9 Unfortunately it did not work for me on FF.

**Comment by ChipSurfer1** [comment]
> Hi, I have the same issue, is there a fix for this available? There is one here: https://community.metamask.io/t/metamask-error-doesnt-go-away-and-prevents-me-using-the-extension/25909/9 Unfortunately it did not work for me on FF.

Managed to fix this after deleting some more elements, ty for the guides that were posted!

**Comment by daweth** [comment]
Nice find @ChipSurfer1 . Some good ol'fashioned inspect element to the rescue. If a translation is needed - you are simply deleting the div called "popover-content"

Make sure to change the network immediately after you delete that popover-element thing - will get another error if you touch anything else. @maslen4ik

**Comment by anaamolnar** [comment]
Hello. @maslen4ik This should be solved so I will go ahead and close this issue. Feel free to open it again if the issue keeps occurring. Thanks!

**Comment by daweth** [comment]
@anaamolnar  where exactly was this fixed? please link to the PR / commit
