### ISSUE TITLE
[Bug]: Set priority fee to 0 and max base fee to 0 when gas price is 0

### ISSUE THREAD

**Issue by bb111189** [MetaMask/metamask-extension#19863]
### Describe the bug

Since this PR https://github.com/MetaMask/metamask-extension/issues/16442, it is possible to use Metamask on the network where gas price is 0. 

However, it is still currently not user-friendly when user wish to perform a transaction on Metamask as Metamask automatically set max base fee and priority fee to non zero value

Suggestion: Automatically set the priority fee to 0 and the max base fee to 0 when the network gas price is 0

### Steps to reproduce

1. Connect to a network where gas price is set to 0
2. Perform any transaction 
3. Metamask displays the following
```
You do not have enough ZERO in your account to pay for transaction fees on AltLayer Zero Rollup network. Deposit ZERO from another account.
```
![image](https://github.com/MetaMask/metamask-extension/assets/4401980/1bf6b225-5be3-4a33-9274-772fc768ae73)

To work around the issue, user needs to manually go to market > Advanced
- Set max base fee to 0
- Set priority fee to 0
- Ignore the warnings
- Save
![image](https://github.com/MetaMask/metamask-extension/assets/4401980/15c0d398-6862-4ab2-baad-0295f4ff7dc5)

Finally, user can send 0 gas transaction
![image](https://github.com/MetaMask/metamask-extension/assets/4401980/9a5113fc-65d0-489b-8d0d-35ba9f46fc2c)

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS, Linux

### Additional context

If you need a zero gas network to test, you can use the following network.

Name: AltLayer Zero Rollup
RPC: https://zero.alt.technology/
Chain ID: 4000003
Symbol: ZERO
Explorer: https://zero-explorer.alt.technology/

**Comment by bschorchit** [comment]
Closing as this is likely a stale issue as it was not possible to connect to this rpc to test it. Please re-open if this is still an issue.
