### ISSUE TITLE
[Bug]: Binance Smart Chain Testnet displays EIP1559 UI with empty values

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19867]
### Describe the bug

**Problem**: whenever using Binance testnet, we can see how dapp interactions/transactions are displayed as if EIP1559 was supported but all values are empty.

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/d869afcf-288d-4aa4-b1c2-765c88741668)

I believe Binance testnet should behave in the same way as Binance network, where EIP1559 is not supported ? @bschorchit 

https://github.com/MetaMask/metamask-extension/assets/54408225/a125bb63-28f7-4fdc-8c90-4044e5b95830

### Steps to reproduce

1. Import Binance Testnet https://chainlist.org/?testnets=true&search=binan
2. Try a dapp interaction or a transaction
3. Click Edit Gas
4. See all values are empty, displaying EIP1559 screen

### Version

10.32.0 and possibly earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This is still an issue even now that BNB chain supports EIP 1559
