### ISSUE TITLE
[Bug]: Watch All NFTs does not display asset list sorted by id

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19875]
### Describe the bug

**Problem**: whenever we are using the functionality for watching all NFTs we can see how the token list is not sorted by id, making it difficult to check for long lists of assets.

https://github.com/MetaMask/metamask-extension/assets/54408225/17fa897b-8b1f-4cad-b33a-b663ff07c86f

### Steps to reproduce

1. Go to test dapp
2. Deploy an NFT contract
3. Mint several tokens ie. 20
4. Click Watch All
5. See how all tokens are un-ordered

### Version

10.34.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Chaitanyaprasad60** [comment]
I can work on this !! You want the API response itself in a sorted manner right?
Can you assign me this
