### ISSUE TITLE
[Bug]: The pop-up window that appears when voting on snapshot gets stuck and does not load the page

### ISSUE THREAD

**Issue by zmzimpl** [MetaMask/metamask-extension#19888]
### Describe the bug

When voting on snapshot gets stuck and does not load the page
![image](https://github.com/MetaMask/metamask-extension/assets/27490895/b926ab65-77a8-4ea4-a235-bd172c2949ec)

### Steps to reproduce

Just voting on the snapshot

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by MetaHydra** [comment]
I am also experiencing this issue on Brave with 10.33.0 - on Snapshot and other sites. OS is MAC OS Venture 13.4.1
I reverted back to Chrome with version 10.32.0 and was able to successfully vote
Happy to provide logs or whatever is needed

**Comment by anaamolnar** [comment]
Heu @zmzimpl, Thanks for reporting! Could you please update to 10.34.0 and let me know if you still experience the issue? Thank you!
