### ISSUE TITLE
[Bug]: Invalid array prop length: 1

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#19880]
### Describe the bug

The console is filled with the log statement `Invalid array prop length: 1` when navigating the extension

### Steps to reproduce

1. login the extension
2. open the settings menu
3. click experimental
4. enable both Opensea API and autodetect nft
5. check the background console

### Error messages or log output

```shell
Invalid array prop length: 1
```

### Version

10.34

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by salimtb** [comment]
hey @PeterYinusa ,
can you pls share the whole error message , i guess there's the file containing the error, for example you'll get something like this :
`Invalid array prop length: 1                              sentry-install.js:1`

is this related to sentry as well ?

**Comment by salimtb** [comment]
you just need to click on the setting button to see the error on the console, is that correct? 

https://github.com/MetaMask/metamask-extension/assets/26223211/769a4135-7b43-4b36-94c5-b46877fb9fa5

**Comment by PeterYinusa** [comment]
Hey @salimtb, it looks like you were able to reproduce the issue by just clicking on the Settings button. At the time of reporting it was appearing when toggling the setting. I think they are related

**Comment by salimtb** [comment]
hey @PeterYinusa ,
it's impossible to reproduce this bug locally
