### ISSUE TITLE
{"code":-32603,"message":"Internal JSON-RPC error.","stack":"construct@[native 

### ISSUE THREAD

**Issue by TomWang1** [MetaMask/metamask-extension#19885]
### Describe the bug

{"code":-32603,"message":"Internal JSON-RPC error.","stack":"construct@[native code]\no@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:58:331\nconstruct@[native code]\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:1872:161\no@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:1872:837\no@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:1876:134\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:3260:5245\nv@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:467:1571\nv@[native code]\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:467:3405\nvalue@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:3260:2699\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:3260:7436\nu@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:3260:458\nu@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:70:157\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:70:866\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:77:1475\nT@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:77:420\np@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:77:701\ncallReactNativeMicrotasks@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:77:2857\nvalue@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:37:2868\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:37:960\nvalue@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:37:2504\nvalue@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:37:919\nvalue@[native code]\nvalue@[native code]"}找文档图片文件@消息更多酷应用

### Steps to reproduce

1.
点击授权 然后预估GAS点击确认

### Error messages or log output

```shell
{"code":-32603,"message":"Internal JSON-RPC error.","stack":"construct@[native code]\no@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:58:331\nconstruct@[native code]\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:1872:161\no@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:1872:837\no@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:1876:134\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:3260:5245\nv@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:467:1571\nv@[native code]\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:467:3405\nvalue@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:3260:2699\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:3260:7436\nu@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:3260:458\nu@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:70:157\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:70:866\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:77:1475\nT@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:77:420\np@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:77:701\ncallReactNativeMicrotasks@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:77:2857\nvalue@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:37:2868\n@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:37:960\nvalue@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:37:2504\nvalue@/private/var/containers/Bundle/Application/110EA167-C398-46C1-9088-59E72D5EDC7C/MetaMask.app/main.jsbundle:37:919\nvalue@[native code]\nvalue@[native code]"}找文档图片文件@消息更多酷应用
```

### Version

v6.3.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

iPhone

**Comment by anaamolnar** [comment]
Hey @TomWang1, Thanks for reporting! This is the extension repository. Could you post this issue in the mobile repo if it still occurs? https://github.com/MetaMask/metamask-mobile/issues
Thank you!
