### ISSUE TITLE
Not able to Replace the Tx Nonce

### ISSUE THREAD

**Issue by danzee1** [MetaMask/metamask-extension#19887]
### Describe the bug

Dear Team,

I tried to replace the Tx Nonce for one of the pending Tx but MM not broadcasting it at all & just failing at it. 

### Steps to reproduce

1. Try to send 0.0000001 to my own wallet address while setting the high gas fees with a Tx Nonce of a Pending Tx
2. MM fails at broadcasting the tx.

### Error messages or log output

```shell
Fails
```

### Version

10.33.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Additional context

That Pending/Stuck Tx I am trying to replace and It has been pending from more than 24 hours.

**Comment by snwlprdgthb** [comment]
Hello @danzee1 

What network is this issue on? 
Have you checked the Nonce of the Stuck Transaction in the Block Explorer? 
Have you tried resetting your account (not wallet!) and then repeating the steps with the Nonce replacement?
https://support.metamask.io/hc/en-us/articles/360015488891-How-to-clear-your-account-activity-reset-account

**Comment by anaamolnar** [comment]
Hello, @danzee1! We are pleased to hear it! I will go ahead and close this issue. Feel free to reach out to Metamask Support if you experience any issues.
