### ISSUE TITLE
[Bug]: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode.

### ISSUE THREAD

**Issue by dievardump** [MetaMask/metamask-extension#19895]
### Describe the bug

For the third time, Metamask decided to stop working (infinite loading, and then "try to restart"...)

So I need to access my Vault data to use the decryptor etc...

Following this https://support.metamask.io/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data for Firefox.

However, this time, it doesn't work: I get the error

```
Uncaught Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
```

### Steps to reproduce

1. Trust Metamask to not bug
2. Open moz-extension://{your-extension-id}/home.html
3. F12
4. As stated in [the guide to retrieve vault data](https://support.metamask.io/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data)

```
chrome.storage.local.get('data', result => {
 var vault = result.data.KeyringController.vault
 console.log(vault)
}) 
```

### Error messages or log output

```shell
Uncaught Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
```

### Version

10.31.1

### Build type

None

### Browser

Firefox

### Operating system

Linux

### Additional context

I am trying to access the Vault because, for the third time in less than a year, Metamask just decided to get corrupted or whatever, and does not open anymore: infinite loader until some promise stops and I get a screen "try to restart Metamask"

**Comment by edcalderon** [comment]
same here

**Comment by genixg** [comment]
The same problem, guys
