### ISSUE TITLE
[Bug]: Chain native token confusion

### ISSUE THREAD

**Issue by MatthewShelby** [MetaMask/metamask-extension#19893]
### Describe the bug

I was connected to the BSC chain while metamask was displaying the native token as ETH, my balance was right but the USD was calculated based on ETH price while the balance was actually BNB.
This happened only on the Chrome extension but to show more detail I opened the portfolio page and then took screenshots.

![2023-07-06 12_12_15-](https://github.com/MetaMask/metamask-extension/assets/47936625/b4585f1f-823e-4935-8a76-e2c9718096b0)
![2023-07-06 12_16_21-](https://github.com/MetaMask/metamask-extension/assets/47936625/f348e800-23cb-4586-9e09-cfcc6d7164d4)
![2023-07-06 12_16_28-Window](https://github.com/MetaMask/metamask-extension/assets/47936625/7fac4f4e-15a7-470e-8c40-010d4610fe13)

### Steps to reproduce

1. I have no idea how it happened but I did lock and unlock my wallet and close and open but it didn't fix the issue,

### Version

10.32.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hey, @MatthewShelby. Thanks for reporting this! I apologize for my late reply. It seems you do not have Metamask permissions configured to'On All Sites'. Changing these settings will help solve your issue. For reference, you can check our support article here: https://support.metamask.io/hc/en-us/articles/360038139452-MetaMask-states-Balance-may-be-outdated-displays-in-orange-or-ETH-not-added-to-balance 

Feel free to open this again if you still experience the issue after following the steps above.  Thanks!
