### ISSUE TITLE
Network icons are not displaying

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#19905]
All icons except for mainnet are displaying with their first letter abbreviation.
![Screenshot 2023-07-06 at 3.29.01 PM.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/f21a64b9-cff1-4fc5-93db-2071d4b9c1a9)

**Comment by NidhiKJha** [comment]
Thanks for creating this issue Kevin but I am not able to reproduce this issue
![Screenshot 2023-07-07 at 7.57.29 PM.jpg](https://images.zenhubusercontent.com/62c8582ccefaf566af0f0264/8f5112ae-adfd-48d0-85e2-949fc63b6224)

**Comment by darkwing** [comment]
If this is reproducible, could you check the console to see if the image requests failed?  I think that component uses the network's first letter as a fallback for a bad request.

**Comment by kevinghim** [comment]
This seemed to have been resolved on v10.33.1.
