### ISSUE TITLE
Connected sites modal misaligned icons

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#19901]
Within the "Connected sites" modal, the sites icons are not centered vertically.
![Screenshot 2023-07-06 at 12.30.19 PM.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/a0b4d937-61df-49c9-8476-5764ceeab332)

**Comment by jase-b** [comment]
Hi, there! I'm happy to work on this issue for my first MM contribution. ✋
I think replacing the deprecated `SiteIcon` with `AvatarFavicon` fixes it.

**Comment by darkwing** [comment]
Sounds good @jase-b !  File a pull request when ready and we'll look right away!

**Comment by jase-b** [comment]
Which kind of border does the team prefer?

`border-default`:

![border-default](https://github.com/MetaMask/metamask-extension/assets/4392888/aa8a2604-0805-4655-bee3-25b416abb7c6)

`border-muted`:

![border-muted](https://github.com/MetaMask/metamask-extension/assets/4392888/acd821b4-75dd-44ae-b183-35fd2ccb1cbf)

**Comment by Bansalayush247** [comment]
I would like to do my first open source project can you help me with this

**Comment by NidhiKJha** [comment]
> Which type of icon border does the team prefer?
> 

@jase-b `border-muted` is the color we should use for the border here.

**Comment by jase-b** [comment]
> I would like to do my first open source project can you help me with this

@Bansalayush247 [Look for an open issue that's unassigned.](https://github.com/MetaMask/metamask-extension/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) When you find one you like, ask to be assigned to it. Or try to fix it locally first then ask for assignment.
