### ISSUE TITLE
[Bug]: After rejecting a batch of signatures, popup for Rejecting remains visible

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19913]
### Describe the bug

**Problem**: after rejecting a batch of signatures, I can see how on the MetaMask Home screen the popup for Rejecting them still remains visible. Clicking Reject has no further effect, after clicking Close, popup is then closed.

[reject-all.webm](https://github.com/MetaMask/metamask-extension/assets/54408225/fa6a360b-e424-4f5f-a3f5-13c1a13cf7cb)

### Steps to reproduce

To investigate. I was on a non stable network environment, which might have been the cause of this. It's hard to repro

### Version

current develop

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by OGPoyraz** [comment]
@sleepytanya I cannot reproduce this issue anymore, fyi

https://github.com/MetaMask/metamask-extension/assets/7644512/d2f9e8cc-6089-4799-9fa0-5417a034d590

**Comment by sleepytanya** [comment]
@OGPoyraz I don't it as well (Chrome, 11.7.1):

https://github.com/MetaMask/metamask-extension/assets/104780023/9510a3e4-ffd5-48d9-a897-bb1f654859be

**Comment by OGPoyraz** [comment]
Perfect, closing this then.
