### ISSUE TITLE
Web3 will be deprecated 

### ISSUE THREAD

**Issue by ftppro** [MetaMask/metamask-extension#1991]
Adding Web3 to a Javascript program displays the following message in the Chrome console:
"MetaMask: web3 will be deprecated in the near future in favor of the ethereumProvider"

Why should I use this extension to create a website, if it's going to be deprecated in the near future?

Also, it appears that the web3.eth.compile.solidity method has been deprecated. Is there any other way that contracts can be dynamically created client-side?

**Comment by cmditch** [comment]
The message is a little confusing. Click the link from the error message and read up on it. web3.js will no longer be injected by metamask, this will have to be provided by the dev. Metamask will provide a provider to plug into to your web3.js instance.

**Comment by ftppro** [comment]
My javascript code uses the following command to create the web3 object
(after the user has logged into their MetaMask account):
   window.web3 = new Web3(web3.currentProvider)
My javascript code then only uses that web3 object, and does not refer to
Web3.
Will I have to make any changes to my code when this deprecation occurs?

**Comment by cmditch** [comment]
According to the documentation (https://github.com/ethereum/mist/releases/tag/v0.9.0) what you have there will work.

**Comment by ftppro** [comment]
I received a conflicting answer on another post (
https://ethereum.stackexchange.com/questions/25651/what-is-the-metamask-workaround-if-web3-is-deprecated),
which indicated that I have to import the Web3 class, and include it with
my own code

Please confirm that I don't have to do anything other than have the user
logged into MetaMask, and create a web3 object in Javascript with the
following command: "window.web3 = new Web3(web3.currentProvider)". Confirm
that I don't have to import any other classes, or do anything else.

**Comment by Zanibas** [comment]
Closing, as related to #2014
