### ISSUE TITLE
[Bug]: Mixed behaviour while rejecting in batch signatures and encrypt/decrypt actions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#19928]
### Describe the bug

**Problem**: whenever I am performing several signatures in Batch, if I click on Encrypt/Decrypt I can see how the `Reject x transactions` is increased by one, however the navigator does not display that new transaction. Whenever I click Reject all, I can see how the Encrypt/Decrypt is not rejected in batch, but still pending in the wallet

https://github.com/MetaMask/metamask-extension/assets/54408225/55b2a047-4c61-444e-82a7-b54bc6068299

Not sure which solution should be here. If we consolidate all requests, or if we keep them separate. @bschorchit 
- In the former, we should make sure all requests are rejected and we display them in the nav. 
- In the latter, we should make sure that Reject x transactions displays the correct number and after rejecting a new MM popup is prompted with the new request. (I think this is how it's done whenever mixing tx's and signatures)

### Steps to reproduce

1. Go to test dapp
2. Connect MM
3. Click Personal Sign (do not accept or reject on MM)
4. Click Personal Sign (do not accept or reject on MM)
5. See how there are now 2 transactions in the nav and in the `Reject x transactions`
6. Click Encyrpt/Decrypt
7. See how there are still 2 transactions in the nav but 3 in the `Reject x transactions`
8. Click Reject transactions in batch
9. Open again the wallet
10. See how the Encrypt/Decrypt is still pending

### Version

10.33.0 possibly earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Labelling this a sev3 as encrypt/decrypt is [deprecated](https://medium.com/metamask/metamask-api-method-deprecation-2b0564a84686).

**Comment by seaona** [comment]
this issue is still present
