### ISSUE TITLE
[Bug]: Invalid data

### ISSUE THREAD

**Issue by aisthetes** [MetaMask/metamask-extension#19930]
### Describe the bug

I got error when try do "approve" function with data 0x095ea7b3000000000000000000000000(removed)0000000000000000000000000000000000000000000000008ac7230489e80000.
Zero code changed, early work perfectly.

### Steps to reproduce

Try to sign "approve" function with data 0x095ea7b3000000000000000000000000(removed)0000000000000000000000000000000000000000000000008ac7230489e80000.

Same in bscscan contract write function.

### Error messages or log output

```shell
MetaMask encountered an error
Try again by reloading the page, or contact support [here](https://metamask.zendesk.com/hc/en-us).
Error details
Message: Invalid data

Code: Error

Stack:
Error: Invalid data
  at n.getCustomTxParamsData (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:113860)
  at H (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-9.js:1:138135)
  at ps (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:297700)
  at No (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:342458)
  at _l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:328374)
  at vl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:328299)
  at dl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:325647)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:284105
  at i.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:356203)
  at Ki (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:283814)
  at Ji (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:284050)
  at Qi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:283985)
  at sl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:322436)
  at Cs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:301357)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:18216
```

### Version

10.30.4

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows, MacOS

**Comment by danjm** [comment]
@aisthetes Did you do create this transaction programmitcally, with javascript? Or did you add that custom data via the send flow within the wallet UI?

Could you provide screenshots of what you were trying to do?

Also, could you share the rest of the transaction paramaterers that were being used?

**Comment by aisthetes** [comment]
> @aisthetes Did you do create this transaction programmitcally, with javascript? Or did you add that custom data via the send flow within the wallet UI?
> 
> Could you provide screenshots of what you were trying to do?
> 
> Also, could you share the rest of the transaction paramaterers that were being used?

Data:
0x095ea7b3 - static name of contract approve function
e9e7CEA3DedcA5984780Bafc599bD69ADd087D56 - static contract address
8ac7230489e80000 - amount (only this generated)

from - my address
to - contract address

```
var transactionParams = {
	gasPrice: "0x12a05f200",
	gasLimit: "0x61a80",
	data: "0x095ea7b3000000000000000000000000e9e7CEA3DedcA5984780Bafc599bD69ADd087D560000000000000000000000000000000000000000000000008ac7230489e80000",
	from: from,
	to: to
};

ethereum.request({
		method: 'eth_sendTransaction',
		params: [transactionParams],
	})
	.then(async (txHash) => {
		console.error(txHash);
	})
	.catch((error) => {
		console.error(error);
	});
```

Use libraries:
"walletconnect": "^1.7.8",
"web3": "^4.0.2",
"web3modal": "*"

**Comment by ericDeCourcy** [comment]
I'm experiencing what i believe is the same issue: 

### **Describe the bug**
Upon clicking the "approve" button, metamask churns for a moment, and then throws the "Invalid Data" error and does not allow the user to broadcast an "approve" transaction.

### Steps to reproduce
1. Make sure metamask browser extension is installed
2. Navigate in a browser to the site [ericdecourcy.github.io](https://ericdecourcy.github.io/).
3. Click "Connect to Metamask"
4. You may need to add Fuse network to your metamask extension, or switch to fuse network. Accept both of these if prompted.
5. Click "Approve Dai"


### Error messages or log output
MetaMask encountered an error
Try again by reloading the page, or contact support [here](https://metamask.zendesk.com/hc/en-us).
Error details
Message: Invalid data

Code: Error

Stack:
Error: Invalid data
  at n.getCustomTxParamsData (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-8.js:1:140716)
  at $ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-10.js:1:336802)
  at va (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:60111)
  at Mu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:105038)
  at Al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90901)
  at Rl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90826)
  at El (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:88166)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46516
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:416038)
  at Jo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46225)
  at ti (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46461)
  at ei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46396)
  at bl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:84932)
  at Aa (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:63768)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-8.js:1:41376

### Version
10.35.1

### Build type
None

### Browser
Brave, Firefox

### Operating system
Ubuntu, Windows 

### Hardware wallet
No response

### Additional context
This error was NOT thrown when tested with Brave with an older version of metamask installed. Metamask version 10.32.1 did NOT throw an error, but within the same browser and OS environment, after updating to metamask 10.35.1, the error was thrown. This is in addition to a separate environment where metamask 10.35.0 was installed, in which the same error was thrown.

You can see that the "approve" transaction is constructed similarly to how @aisthetes is constructing his, check the [relevant source code](https://github.com/ericDeCourcy/ericDeCourcy.github.io/blob/0d03515bf7d45f217bab2513522d87636b49f13c/main.js#L249-L255) for the linked webpage in "Steps to Reproduce"

```
const transactionData = 
    '0x095ea7b3'                                                    // function signature
    + activePool.address.replace(/^0x/, '').padStart(64, '0')       // fake swap address
    + ''.padStart(64, 'f');                                         // max amount
  const transactionParams = activePool.getTransactionParams(transactionData);
  transactionParams['to'] = token.address;
  transactionParams['gas'] = '0x0186A0';
  
  const success = await ethRequest(transactionParams, statusElement, loggingKeyword);
```

```
async function ethRequest(params, statusElement, loggingKeyword) {
  try {
    const txHash = await ethereum.request({
      method: 'eth_sendTransaction',
      params: [params],
    });
    showSubmitted(statusElement, loggingKeyword);
    const success = await pollForStatus(txHash);
    if (success) {
      showSuccess(statusElement, loggingKeyword);
      return true;
    } else {
      throw new Error('Transaction reverted or blockchain polling timed out.');
    }
  } catch (error) {
    showError(statusElement, loggingKeyword, error);
    return false;
  }
}
```

**Comment by ericDeCourcy** [comment]
I've found a way around this issue. For what it's worth, i still think this bug should be resolved - metamask should not crash when passing in a manually constructed transaction.

**My solution**

1. Import ethersjs into your javascript file. For doing this on a static site you can add the following in your HTML file's `<head>`:
```
<script src="https://cdn.ethers.io/lib/ethers-5.2.umd.min.js"
        type="application/javascript">
	</script>
```

2. When you connect to metamask, do the following in your `.js` file:

```
provider = new ethers.providers.Web3Provider(window.ethereum);
      await provider.send("eth_requestAccounts", []);
      signer = provider.getSigner();
```

3. Do "approve" transactions like this:

```
const erc20Abi = [
    "function approve(address,uint)"
    // you can add other functions, separated by commas, here
  ];

  const myTokenContract = new ethers.Contract(myTokenAddress, erc20Abi, provider);

  const myTokenWithSigner = myTokenContract.connect(signer);

  const approveAttempt = await myTokenWithSigner.approve(spenderAddress, ethers.utils.parseUnits(amountToApprove, 18));
```
