### ISSUE TITLE
[Bug]: Can't connect with snap (TIMEOUT Error)

### ISSUE THREAD

**Issue by AZbang** [MetaMask/metamask-extension#19936]
### Describe the bug

If a request falls on https://acl.execution.metamask.io/latest/registry.json, then the connection to the snap will not happen, this is confusing. Turns out I needed to turn on the VPN because my ISP was blocking that domain.
You need to add error output so that it is clear why the connection cannot occur.

### Steps to reproduce

1. Try to somehow block the loading of the resource (https://acl.execution.metamask.io/latest/registry.json)
2. Try to connect any snap to Metamask Flask
3. Long loading and TIMEOUT Error

### Version

10.33.0-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

**Comment by AndreasGassmann** [comment]
By coincidence I had the same issue today. It was very confusing, I thought it was a breaking change in the Flask/Snaps API and was looking for breaking changes until I found this issue. Would be great to have a more detailed error message. And it may be worth investigating why that domain is blocked by two separate ISPs for no reason.

**Comment by FrederikBolding** [comment]
Hey all!

Some files from `execution.metamask.io` are required for Snaps execution. For Flask, the `registry.json` file should not be required, but if you are seeing that fail you might also be failing to fetch other required files.

We have an intermittent DNS failure on that domain and are investigating, meanwhile you can try a VPN or a different DNS server has you already mentioned yourself.

Sorry for the trouble!

**Comment by AZbang** [comment]
@FrederikBolding  thanks for the answer! I understand that no one is protected from network errors and this is normal. My ticket was more about the need to add error output in such a case so that people are informed to enable the VPN.
