### ISSUE TITLE
[Bug]: Decrypt will always return "DecryptMessage: User denied message decryption"

### ISSUE THREAD

**Issue by basarrcan** [MetaMask/metamask-extension#19934]
### Describe the bug

I tried reinstalling and using different browsers but result is all the same. I have a project that uses Metamask's "eth_getEncryptionPublicKey" and "eth_decrypt" rpc calls and it used to work as expected. But when I tried to use it recently decrypt functionality always return error with 'MetaMask DecryptMessage: User denied message decryption.' message. 

### Steps to reproduce

I guess just use eth_decrypt. 

### Version

10.33.0 & latest local build

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hey @basarrcan. Thanks for reporting! Is this issue present in 10.34.0 as well? You should be able to update manually to that version in Chrome. Thanks!

**Comment by tiendn** [comment]
<img width="413" alt="Screenshot 2023-08-17 at 10 23 36" src="https://github.com/MetaMask/metamask-extension/assets/15717476/23ed379e-d07a-4dd2-ab49-fb85b459a433">

I used Metamask extension on Brave ver 10.34.3 still have this issue.

**Comment by tiendn** [comment]
It seems I did wrong approach, do like this comment, then it works.
https://github.com/ethers-io/ethers.js/issues/4139#issuecomment-1615971987
