### ISSUE TITLE
Test networks appearing above show test network toggle

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#19945]
The test networks are appearing above the "show test network" toggle whereas, it should be appearing below the toggle.

Design:
![Screenshot 2023-07-10 at 3.58.37 PM.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/b0c2ee0b-a946-4983-a15e-7fde0e38961d)

Build:
![Screenshot 2023-07-10 at 3.59.47 PM.png](https://images.zenhubusercontent.com/6036e42864c943d3331c1f27/b96e3ccc-8033-449c-98b4-a2e8b88d067b)

**Comment by darkwing** [comment]
This was fixed by https://github.com/MetaMask/metamask-extension/pull/19812
