### ISSUE TITLE
[Bug]: Custom Networks with Reserved ChainID Should Be Removable in Network Menu 

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#19950]
### Describe the bug

When a custom RPC network, like Ganache running at chain ID 1, is in the network list, the network should be removable.  The network currently doesn't display as removable since `0x1` is in `UNREMOVABLE_CHAIN_IDS`.

<img width="513" alt="SCR-20230710-rknp" src="https://github.com/MetaMask/metamask-extension/assets/46655/9ee780cc-c6e7-4cf2-9ac6-2f93353481d5">

### Steps to reproduce

1.  Install  ganache CLI locally
2. Run `ganache --chain.chainId 1`
3. Add that localhost chain and RPC in the Add Network page
4. Open the Network picker
5. Hover over the new localhost chain
6. *You don't see the trash icon* --- but you should.

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Blocked by https://github.com/MetaMask/metamask-extension/pull/19947

**Comment by pratham-bhatnagar** [comment]
Can I work on this issue?
