### ISSUE TITLE
[Bug]: Severely downgraded usability since 10.33

### ISSUE THREAD

**Issue by PhiMarHal** [MetaMask/metamask-extension#19959]
### Describe the bug

The latest update is such an UX catastrophe it should qualify as a bug.

Account selection window is now limited to 2 accounts even in the expanded view.
Network selection window is limited to 3 networks even in the expanded view.
"view in Etherscan" button has been hidden behind 3 clicks, deep within the account selection panel.

Please consider some form of testing involving actual blockchain users before dropping these radical UX changes.

### Steps to reproduce

1. let Chrome update your Metamask extension
2. cry

### Version

10.33

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hey @PhiMarHal, Thanks for your feedback. I have relayed this information to my team.

**Comment by georgewrmarshall** [comment]
It appears that this issue can now be resolved. The following Pull Requests contribute towards the enhancement of the account and network selection window:

1. [PR #20745](https://github.com/MetaMask/metamask-extension/pull/20745)
2. [PR #20801](https://github.com/MetaMask/metamask-extension/pull/20801)

Additionally, the "View Ethercan" option has been conveniently relocated to the kebab menu, making it readily accessible with a single click.

<img width="476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTFLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cf7dceda346d8179b70eba4066056169fcbfc15/Screenshot%202024-02-10%20at%201.12.31%E2%80%AFPM.png" alt="Screenshot 2024-02-10 at 1.12.31 PM.png" />
