### ISSUE TITLE
Copy Address Button in Wallet overview

### ISSUE THREAD

**Issue by NidhiKJha** [MetaMask/metamask-extension#19958]
### Describe the bug

Once, we copy the address, after pasting it once if we try to paste again there is nothing to be pasted. 
Similarly, if I copy the address and then click anywhere (not pasting) and then try to paste the address it doesn't work

https://github.com/MetaMask/metamask-extension/assets/39872794/4e27aff9-2f71-4a63-9314-f72919bd8de3

### Steps to reproduce

1. copy the address using copy address button in the wallet overview
2. click anywhere in Metamask and then try to paste the address
3. check nothing is getting pasted

### Version

10.33

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Wholesomebruh** [comment]
Hi @NidhiKJha , It's more than this , after clicking on copy, a tick like icon appears there and till the time it's there user can paste the address but as soon as it disappear, address is not getting paste (no need to click anywhere).

https://github.com/MetaMask/metamask-extension/assets/109906215/6fb7ef1b-f979-43ba-8caf-59aae87daea6

**Comment by NidhiKJha** [comment]
Clo
