### ISSUE TITLE
[Bug]: MetaMask closes entire browser window when connecting to wallet

### ISSUE THREAD

**Issue by aungKhantPaing** [MetaMask/metamask-extension#19977]
### Describe the bug

Whenever I connect MetaMask with any dApp, it opens _chrome-extension://.../notification.html_ window instead of a popup. After a few seconds of loading, it closes the entire browser window (#7789) and rejected the wallet connection. I've tried some troubleshooting like re-opening the browser and re-installing the extension but doesn't help.

https://github.com/MetaMask/metamask-extension/assets/25960342/f773a7c4-0356-4dfe-825a-c8fa025fd9e3

All the extension permissions are also set to default. I didn't block the popup permission of the extension which is also restricted.

### Steps to reproduce

1. Connect MetaMask using any MetaMask-supported dApp. ([curve.fi](https://curve.fi) is used in the example video)

So far, I don't know how to reproduce this bug, but once it happens, it's impossible to connect any dApp with MetaMask, and as I said there is no way to troubleshoot this except re-installing the entire browser.

### Version

10.33.1

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hey, @aungKhantPaing Thanks for reporting! I will pass this on to the team.
