### ISSUE TITLE
Visually indicate that network status is a menu

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#1997]
![screen shot 2017-08-31 at 9 53 30 am](https://user-images.githubusercontent.com/542863/29935046-50ae93d2-8e32-11e7-84f6-0ac1c74e3c1d.png)

**Comment by cjeria** [comment]
Proposed design for network dropdown UI @flyswatter 
![image](https://user-images.githubusercontent.com/597770/29935357-5b9ea330-8e33-11e7-92c4-00b14d9f73bc.png)

**Comment by flyswatter** [comment]
Nice! That was fast!
