### ISSUE TITLE
Replace fox head loading screen when user is logged in

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#20017]
## Problem
When you open up the extension popup, there's small delay and for half a second the fox head loading screen appears before the wallet screen loads. The visual flicker that makes it feel a little jittery. We should investigate why this is happening. 

Reference: [Slack thread](https://consensys.slack.com/archives/GTQAGKY5V/p1689289026081309)
Reproduced screencap: https://images.zenhubusercontent.com/42009758/88806063-b72f-4985-8a9a-b7a22c2094dc/screen_recording_2023_07_13_at_7_07_47_pm.mov

## Possible solution
We could possibly introduce a different loading screen (faded, delayed, transparent etc.) when the user's already logged in.

**Comment by danfinlay** [comment]
I think the flicker is the brief loading indication. My original post:
> When I open the extension, it opens very snappily, but I see the fox head very briefly b/c it’s on the loading indicator, and it’s thrown up for any delay. This causes a visual flicker that makes it feel a little jittery even though things are working smooth. Maybe if the fox head faded in for the loading indication, it would only become very visible when that view was, and so be less intrusive when things are fast.

**Comment by kevinghim** [comment]
@SaraCheikh

**Comment by darkwing** [comment]
Ideas:

* Don't show the MetaMask image unless the app takes more than, say, 2 seconds to load
* Default the popup / notification HTML pages to have a background of the system preference, since it's the default for that setting and we don't get the specific user preference until React loads
