### ISSUE TITLE
[Bug]: New crappy UI causes insane browser lagg and slows it down.

### ISSUE THREAD

**Issue by Glass47** [MetaMask/metamask-extension#20034]
### Describe the bug

When having 30-40 wallets and trying to navigate through NEW horrible UI, it causes browser to slow down, whole browser becomes almost unresponsive because new ugly and non optimized UI isn't well optimized. It's impossible to navigate through wallets quickly. Before it was quick and easy, clicking on wallet username drop-down to see/select different wallets causes high unresponsiveness due optimization being so bad on new UI, please add option to revert from this worst and horrible/laggy ui to old one which was just fine, fast and optimized. Thank you for reading, and message for developer who worked on this, please next time before you push new ui, optimize it, do extensive tests of power-users. 

### Steps to reproduce

1. Have a wallet with new un-optimized and crappy UI.
2. Create 20-30-40 different wallets
3. Try navigating through them via drop-down, clicking it will cause browser to be unresponsive for couple seconds, clicking it multiple times extends the unresponsiveness.

### Error messages or log output

```shell
No error messages.
```

### Version

10.33.1

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Additional context

Give users option in settings to revert back to old UI so we can switch to more usable solution. The new ui is buggy, laggy, un-optimized, causes browser to slow down, just a generally VERY VERY poorly executed update with horrible optimization, it feels as if someone was about to get fired from Metamask dev team so he had to write some spaghetti code that isn't well optimized and pushed to every user without their consent NOR option to go back to old ui.

**Comment by alexis26** [comment]
Firefox too...
not xx wallet, just 3...

Can't use my wallet and my broswer when i'm connected...
we are not bêta-tester !! what are you doying ???

**Comment by naujokas2021** [comment]
You can install older version without losing all data from official Firefox addons website. Go to Metamask addon, find "[See all versions]"
Then find: Older versions Version 10.32.0 and Press [Download file] in lower right corner.

P.S I do not post any links for your safety.

![image](https://github.com/MetaMask/metamask-extension/assets/88821797/42169e0b-fb04-49a8-8a21-888976bbe527)

**Comment by CodeMongerrr** [comment]
I really wanted to know, Why? how did it every occur to someone to just destroy everything. Too much padding everywhere

**Comment by Glass47** [comment]
> You can install older version without losing all data from official Firefox addons website. Go to Metamask addon, find "[See all versions]" Then find: Older versions Version 10.32.0 and Press [Download file] in lower right corner.
> 
> P.S I do not post any links for your safety.
> 
> ![image](https://user-images.githubusercontent.com/88821797/253762370-42169e0b-fb04-49a8-8a21-888976bbe527.png)

Thank you for this, wasn't aware that it was possible to rollback without much hassle. For anyone else who wants to do the same they can by going to official Firefox extension website, finding official MetaMask extension and clicking "See all versions" then downloading the older one. Now my extension is working snappy and fast, no issues managing many wallets. Going to wait few months until developers fix the new ui which is currently UN-USABLE and UN-OPTIMIZED.
![image](https://github.com/MetaMask/metamask-extension/assets/55170107/853d8acc-d3f2-4916-ba3d-658cdb0acbaf)

**Comment by naujokas2021** [comment]
Issue is not solved as some sites do not allow to connect wallet via old version. While a new version is lagging out and crashing Firefox.

**Comment by Glass47** [comment]
> Issue is not solved as some sites do not allow to connect wallet via old version. While a new version is lagging out and crashing Firefox.

Reopened.

**Comment by danjm** [comment]
Thanks for the report everyone. The performance problems have been fixed in v10.34.0, which is currently rolling out on chrome and will roll out on firefox after Mozilla completes review of that version.

**Comment by danjm** [comment]
MetaMask v10.34.0 should now be available to all firefox users. Updating to that version should solve this issue.

I am closing as I believe this has been resolved, but please comment here or open a new issue if you continue to experience performance problems
