### ISSUE TITLE
Add clickjacking protection to Mascara

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2003]
> deploy proper Clickjacking protections by including the X-Frame-
 Options: DENY header. This approach signals the browser not to let any websites frame
 the site.

**Comment by kumavis** [comment]
this may affect our freedom in choosing a CDN since we must specify this header when served

**Comment by danfinlay** [comment]
@frankiebee may have added this. Moving to QA.

**Comment by tmashuang** [comment]
Fixed in #2412 mascara - set x-frame-options header to DENY.
