### ISSUE TITLE
[Bug]: Exporting Private Key & Slow Wallet List Scrolling

### ISSUE THREAD

**Issue by chongqiangchen** [MetaMask/metamask-extension#20041]
### Describe the bug

How can I find the option to export my private key, and why is scrolling through the wallet list so slow?

### Steps to reproduce

How can I find the option to export my private key, and why is scrolling through the wallet list so slow?

### Version

Latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by plasmacorral** [comment]
Option to present private key is available from the main wallet view with these steps:

1. Click the account menu where it says "Account 1" (or whatever account you have selected)
2. Click the 3 dots menu on the right
3. Select "Account details"
4. Click "Show Private key"
5. Enter password
6. Click "Confirm"

Two things to note here:

1. In the near future you may see an additional step 7 where you will need to "hold to reveal" a CTA to present the private key string.
2. At this time, if you attempt to copy the private key to the clipboard it will be purged in 3 seconds, so you will have to be ready to paste quick.  The team is working on a change to extend that to 60 seconds, and we hope to ship that in v10.35 with PR #20008

As for the mention of slow wallet scrolling, I will ask that you open a separate issue for that report.  Please make sure to provide more context than what you have shared above.  Detailed information about what specific steps you took are critical to help us reproduce and diagnose any concerns.  In this case, a video would be a welcome addition to help visualize what you are experiencing. Thank you for your first submission!
