### ISSUE TITLE
Metamask Add-on for Firefox SLOW to the point of unusable [Bug]: 

### ISSUE THREAD

**Issue by Tobe-wan-Kenobi** [MetaMask/metamask-extension#20040]
### Describe the bug

Even scrolling though my accounts the browser bogs down, takes forever to load the next few accounts and then does it again as I scroll through.

Trying to add or remove or anything at all slows everything down to the point you think it's frozen.

Not having these problems on Chrome. 

### Steps to reproduce

1.
Log in

### Version

10.33.1

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by kedazo** [comment]
It affects me as well on Firefox@Linux.. I have 20-30 accounts, opening the accounts lists takes minutes for me

**Comment by danjm** [comment]
Thanks for the report everyone. The performance problems have been fixed in v10.34.0, which is currently rolling out on chrome and will roll out on firefox after Mozilla completes review of that version.

**Comment by danjm** [comment]
MetaMask v10.34.0 should now be available to all firefox users. Updating to that version should solve this issue.

I am closing as I believe this has been resolved, but please comment here or open a new issue if you continue to experience performance problems
