### ISSUE TITLE
[Bug]: New version of Metamask 10.33.1 very slow and unresponsive

### ISSUE THREAD

**Issue by trigga777** [MetaMask/metamask-extension#20043]
### Describe the bug

My metamask recently updated to version 10.33.1 and has now become very slow and unresponsive. I have tried to check for further updates but i appear to have the latest version. The wallet is also slowing down my PC. I have a fast internet connection and my PC has no issues with viruses but this new update is terrible. The menus are really slow, lock up and some of my tokens are not showing. I am not able to use the new version of Metamask due to these issues. I am running on Firefox and have disabled then re-enabled the metamask add on several times but still have the same issues. Is Metamask aware of these issues generally and is there a fix?

### Steps to reproduce

1.

### Version

10.33.1

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by cauta** [comment]
i have the same issue, can not access wallet list

**Comment by Nytyr** [comment]
Same here. Totally unusable. It's impossible to change between accounts.

**Comment by danjm** [comment]
Thanks for the report everyone. The performance problems have been fixed in v10.34.0, which is currently rolling out on chrome and will roll out on firefox after Mozilla completes review of that version.

**Comment by danjm** [comment]
MetaMask v10.34.0 should now be available to all firefox users. Updating to that version should solve this issue.

I am closing as I believe this has been resolved, but please comment here or open a new issue if you continue to experience performance problems
