### ISSUE TITLE
[Bug]: Can't export private key

### ISSUE THREAD

**Issue by xiaoch05** [MetaMask/metamask-extension#20045]
### Describe the bug

when I export the private key, it shows the same Phrase for all of the account.

### Steps to reproduce

1. select an account and export the private key

### Version

10.33.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by plasmacorral** [comment]
Closing issue with no response to information request. Feel free to reopen/open a new report if you can address the clarifying questions above and provide more detail on the reproduction steps.  Thanks.
