### ISSUE TITLE
[Bug]: Can't switch between networks having the same chain ID

### ISSUE THREAD

**Issue by Trottoir** [MetaMask/metamask-extension#20046]
### Describe the bug

It's not possible to switch from 2 networks having the same chainID
These chains are both created through hardhat, so having the chainID 31337.

Before the Metamask update, I was able to switch between both easily, now when I try to switch, Metamask doesn't update the network and stays on the same one.

You can see on the following screenshot that it seems that both network are selected ( probably due to the same chainID)
<img width="385" alt="Sans titre 2" src="https://github.com/MetaMask/metamask-extension/assets/31350013/aa9630c2-a91e-420e-87f9-d44da880a38a">

### Steps to reproduce

1. Create a network N1 on a chainID : C
2. Create a network N2 on a chainID  : C
3. Register both networks in Metamask
4. Try to switch between N1 and N2

### Version

10.33.1

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by dvush** [comment]
This also affects the users of private RPCs such as [https://rpc.flashbots.net](https://rpc.flashbots.net).

I noticed that the last RPC that was selected from the dropdown is actually used even thought some other RPC can be displayed in the main UI as selected and all of them are "selected" in the dropdown menu at the same time.

**Comment by danjm** [comment]
This fixed in v10.34.0, which has begun to roll out on chrome. We are currently rolling that version out to chrome users. If you manually update your extension to v10.34.0, this issue will go away.

**Comment by kevinghim** [comment]
Fixed on v10.34.0
