### ISSUE TITLE
Move Enable Opensea API and audotedect NFTs into Security & Privacy settings

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#20062]
## Background
Enable Opensea API and autodetect NFTs from Experimental to Security & Privacy settings. While Enable Opensea API and autodetect NFTs was under the Experimental settings, we've made minor improvements and the amount of reported bugs have been minimal. Therefore, we're going to move this setting out of experimental and into Security and Privacy.

## Acceptance Criteria
Scenario: As a user on the Settings screen
- Given that the user is on the Security & Privacy settings screen
- When the user scrolls down to Enable Opensea API and autodetect NFTs toggles
- Then retain the same functionality to enable Opensea API and autodetecting of NFTs
- Update e2e tests and jest snapshots
- Update the settings ref for settings search

## Designs
For listing ordering of privacy settings, go [here](https://www.figma.com/file/Ek7QDiB3TgvDhjPtmh1zAT/Privacy-Epic-Security%26Privacy-settings?type=design&node-id=368-52616&mode=design&t=Cqhn5gwX1TPDYNL9-0).

**Comment by vthomas13** [comment]
[ ]- Move Opensea API setting from Experimental to Security & Privacy settings
[ ]- Move autodetect NFTs setting from Experimental to Security & Privacy settings
[ ]- Handle any resulting unit test changes
[ ]- Handle any resulting e2e changes, if needed
