### ISSUE TITLE
[Bug]: MetaMask isn't injected if location.pathname suffix is .pdf

### ISSUE THREAD

**Issue by wenty22** [MetaMask/metamask-extension#20089]
### Describe the bug

We have a storage server, when a user accesses a file, needs to connect metamask. However, we found when the file suffix is `.pdf`, the provider is not injected.

Then we looked at the code and found the `pdf` `xml` files are filtered.
https://github.com/MetaMask/metamask-extension/blob/fe3e960b62e65e3179e628cc0c1754d151507bfe/shared/modules/provider-injection.js#L38

And we want to know, what's the reason for this? Why suffixes like `mp3` `mp4` `png` aren't filtered?

Can this restriction be removed?

### Steps to reproduce

1. Access this link: https://gnfd-testnet-sp-3.bnbchain.org/view/articles/whale.pdf
2. Can't use metamask, the provider isn't injected

### Version

10.33.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @wenty22. Thanks for reporting! I will pass this on to the team.

**Comment by eligrey** [comment]
If I had to guess it's likely an instance of this extension simply not being coded to handle anything other than HTML document contexts. That would explain the filtering of .xml at least
