### ISSUE TITLE
[Bug]: Can't switch network to Linea

### ISSUE THREAD

**Issue by walruzperil** [MetaMask/metamask-extension#20084]
### Describe the bug

After clicking on switch button
![image](https://github.com/MetaMask/metamask-extension/assets/7361881/fffc48b9-4f1c-4e36-bd1e-50595cc022fc)
i  got this error
![image](https://github.com/MetaMask/metamask-extension/assets/7361881/8361af9c-30ca-45da-acca-72378a720388)
just trying switch to linea JS:

```
let ver = 59144;
if (window.ethereum.networkVersion !== ver) {
try {
       
        await window.ethereum.request({

          method: 'wallet_switchEthereumChain',
          params: [{ chainId: '0xE708'}], 
        });
      } catch (error) {
      
                    }
   
 }
```
this simple script perfect work with other networks, but not  with Linea... what missing?
i trying  connect to linea from another websites, its works. But on my website doesn't...

### Steps to reproduce

1. Connect to website
2. Switch network

### Error messages or log output

```shell
MetaMask - RPC Error: networkConfigurationId undefined does not match a configured networkConfiguration
```

### Version

10.33.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hey @walruzperil. Thanks for reporting! Could you please let me know if you still experience this after updating to 10.34.0? Thanks!

**Comment by walruzperil** [comment]
> 

in new version, error is the same...
![image](https://github.com/MetaMask/metamask-extension/assets/7361881/abe73c41-694b-445b-b915-661618ecc2fd)

**Comment by walruzperil** [comment]
has any solution been found?

**Comment by danjm** [comment]
@walruzperil Thanks for the report. I believe we now understand the bug and will make a patch for the next release.

In the meantime, I think that if you set the `'E'` in the chain id to lower case, the `wallet_switchEthereumChain` request should work.

Can you try the following and tell me if it works for you?

```
let ver = 59144;
if (window.ethereum.networkVersion !== ver) {
try {
       
        await window.ethereum.request({

          method: 'wallet_switchEthereumChain',
          params: [{ chainId: '0xe708'}], 
        });
      } catch (error) {
      
                    }
   
 }
```

**Comment by walruzperil** [comment]
> @walruzperil Thanks for the report. I believe we now understand the bug and will make a patch for the next release.
> 
> In the meantime, I think that if you set the `'E'` in the chain id to lower case, the `wallet_switchEthereumChain` request should work.
> 
> Can you try the following and tell me if it works for you?
> 
> ```
> let ver = 59144;
> if (window.ethereum.networkVersion !== ver) {
> try {
>        
>         await window.ethereum.request({
> 
>           method: 'wallet_switchEthereumChain',
>           params: [{ chainId: '0xe708'}], 
>         });
>       } catch (error) {
>       
>                     }
>    
>  }
> ```

Working! thanks
