### ISSUE TITLE
[Bug]: Polygon conversion amount inconsistent along the Send ERC20 flow with no units

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#20106]
### Describe the bug

**Problem:** whenever i am sending a transaction from Polygon network, I can see how on the confirmation screen there is a conversion value that I don't know what it is.
Furthermore, on the Asset screen, I see no conversion, only `ETH` below the value.

https://github.com/MetaMask/metamask-extension/assets/54408225/9499e3a7-4e04-491a-a3a3-cb10bd972fc9

### Steps to reproduce

1. Select Polygon
2. Import an ERC20 token
3. Click Send
4. Add recipient
5. Add amount -- see `ETH` below without any value
6. Click Next
7. See a converted value (not sure what it is as no Units are displayed)

### Version

10.33.1 prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Gawd71730** [comment]
Thanks

**Comment by Gawd71730** [comment]
Bug
