### ISSUE TITLE
Problem loading token balances.

### ISSUE THREAD

**Issue by uworld66** [MetaMask/metamask-extension#2010]
This is an on going issue

**Comment by uworld66** [comment]
"There was a problem loading your token balances" Why was this issue closed as it has not been resolved and certainly is not fixed. I can only view tokens via etherscan and can not access any of them through metamask. Nor can I clear the error.

**Comment by flyswatter** [comment]
It was affecting many people, we solved that problem. We could add a retry button for the more rare times this still happens.

In the meanwhile, you can click history and tokens again to retry.

**Comment by uworld66** [comment]
I do not see any place on metamask to bring up the history.
Where is this?
Brent
--------------------------------------------
On Sun, 9/3/17, Dan Finlay <notifications@github.com> wrote:

 Subject: Re: [MetaMask/metamask-extension] Problem loading token balances. (#2010)
 To: "MetaMask/metamask-extension" <metamask-extension@noreply.github.com>
 Cc: "uworld66" <uworld66@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, September 3, 2017, 12:45 PM
 
 It was affecting many people, we
 solved that problem. We could add a retry button for the
 more rare times this still happens.
 In the meanwhile, you can click history and tokens again
 to retry.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by uworld66** [comment]
I have no + to click on only the statement " Problem loading your token balances" I have had that statement displayed for several days now and nothing more will come up when I switch to tokens.
Brent
--------------------------------------------
On Sun, 9/3/17, Dan Finlay <notifications@github.com> wrote:

 Subject: Re: [MetaMask/metamask-extension] Problem loading token balances. (#2010)
 To: "MetaMask/metamask-extension" <metamask-extension@noreply.github.com>
 Cc: "uworld66" <uworld66@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, September 3, 2017, 12:45 PM
 
 It was affecting many people, we
 solved that problem. We could add a retry button for the
 more rare times this still happens.
 In the meanwhile, you can click history and tokens again
 to retry.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by flyswatter** [comment]
Sorry, not "history", but "Sent". You can retry loading token balances by clicking `Sent` and then `Tokens` again.

**Comment by lwinch2006** [comment]
@danfinlay Can you please hint which URL, IP, port and other usefull information that metamask uses to fetch token data.
I installed MetaMask on Firefox but get this "We had trouble loading your token balances." error. As I think because of my other addons like NoScript, uMatrix and maybe firewall. So I need to know which URLs, IPs, ports I should allow in the system.

**Comment by danfinlay** [comment]
Token view is not currently working on firefox. We need to debug why.

**Comment by frankventured** [comment]
Bump

**Comment by propercoil** [comment]
Token view is not working on chrome. Getting this error which doesn't seem to be updated in any way:

![screen shot 2018-01-27 at 22 40 17](https://user-images.githubusercontent.com/1096658/35476108-28a2f512-03b3-11e8-84ec-cf06a959bb44.png)

**Comment by scott-hornberger** [comment]
I intermittently have this problem. I solve it temporarily by uninstalling and reinstalling MetaMask. This is how I solve most problems in MetaMask. I think a lot of us would like a hard reset button when using MetaMask for development.

**Comment by danfinlay** [comment]
Our token view is buggy because it requests all your token balances at once, on switching to the token tab. The easy way to retry is to switch to "sent" and back to "tokens" again.

The long term solution will be to load the tokens individually, retry them individually, fail them individually.

**Comment by danfinlay** [comment]
Opened that issue as https://github.com/MetaMask/metamask-extension/issues/3243
