### ISSUE TITLE
[Bug]: Hold to reveal for Private key no longer present

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#20104]
### Describe the bug

Hold to reveal was introduced in v10.32 with PR #18170 , but it seems that with the introduction of PR #18903 the hold to reveal feature was lost for the private key (still present and functioning as expected for SRP).

### Steps to reproduce

1. Create/import an SRP
2. Complete setup and be at wallet view
3. Click the account menu at "Account 1"
4. Click the 3 dots menu
5. Select "Account details"
6. Select "Show Private key"
7. Enter password
8. Click "Confirm"
9. Note private key string presented instead of Hold to reveal

### Version

10.33.1

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

Ventura 13.4.1, observed on production build from stores.

**Comment by AlexJupiter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Accounts-Team-v2-64c91cbeaa9d1c00126621fd/issues/MetaMask/metamask-extension/20104?planning-poker) with Zenhub @plasmacorral @HowardBraham @gantunesr
