### ISSUE TITLE
[Bug]: Copy Address doesnt work in the latest extension update

### ISSUE THREAD

**Issue by AyiSoli** [MetaMask/metamask-extension#20116]
### Describe the bug

When copying an address from Metamask using the copy address button, the clipboard remains empty. The address is not copied at all. 

Only after multiple clicks, sometimes it copies the address. Sometimes it doesnt 

### Steps to reproduce

1. Open Metamask
2. Click copy address. 
3. Paste elsewhere.

### Version

10.33.1

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @AyiSoli. Thanks for reporting! This issue should be solved in 10.34.0, which is currently rolling out. It is, at the moment, only available in Chrome. You should be able to update manually from the browser by clicking right on the Metamask icon, clicking on 'Manage extension', enabling Developer mode from the top right, and Updating manually from the top left of the page. Could you please let me know if you still experience the issue after updating? Thank you!
