### ISSUE TITLE
[Bug]: `Minified React error..`when changing networks with a pending signature

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#20124]
### Describe the bug

**Problem**: whenever I have a pending signature, if I change networks from the MetaMask full view, MM breaks and I get the error `Minified React error..`
Whenever I refresh the home page, MM is frozen on a loop.

https://github.com/MetaMask/metamask-extension/assets/54408225/6c3544f2-6774-4309-8c13-d753feec86d0

### Steps to reproduce

1. Initiate a Signature from the test dapp
2. From the full view change networks
3. See error
4. Refresh MM home page
5. See MM is frozen in a loop

### Version

10.34.0 prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I believe pending requests should be rejected when the user switches network - this seems to be the behavior when user switches network via wallet_switchNetwork API method (we displaying a warning saying such).
