### ISSUE TITLE
Fix Close(X) Button in Nft-Details

### ISSUE THREAD

**Issue by allwin199** [MetaMask/metamask-extension#20126]
### Describe the bug

In the `NFT details` popup view, the `close(X)` button is not properly visible.

### Steps to reproduce

1. Go to the NFTs Tab
2. Go to any NFT detail in the popup view
3. Look at the top left.

### Version

10.34.0

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by darkwing** [comment]
This is a`<` "back" button, a la breadcrumbs.  This isn't meant to be a close button.

Thank you!
