### ISSUE TITLE
[Bug]: Extraneous "Error" word in error on token approval

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#20141]
### Describe the bug

When an error is shown in the token approval it is shown as "Error: Error Message". I believe that the beginning "Error" to be extraneous and should be omitted. If this was intended feel free to close.

![extraneous-error-in-error-message](https://github.com/MetaMask/metamask-extension/assets/13376180/900b2212-2b4a-4642-af80-e3ce0848ec41)

### Steps to reproduce

1. Initiate a token approval tx
2. Enter works for input to trigger error message 
3. See "Error: Enter Numbers Only" error message
4. Should be "Enter Number Only"

### Version

10.34.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Jones098** [comment]
Thanks for your support, and so sorry that have not replied for time now ,
have been little busy with work, and I will be needing your full support on
my metamask because I hardly see my wallet balance please help.
