### ISSUE TITLE
[Bug]: Two networks selected in network menu with the same chain id.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#20140]
### Describe the bug

While having two networks with the same chain id, such as two Ethereum mainnets, will show both networks selected under the network menu.

https://github.com/MetaMask/metamask-extension/assets/13376180/88996bdd-5b0f-4b66-a1dd-8b6f08900079

### Steps to reproduce

1. Add two networks with the same chain id, Ethereum/BNB/Matic/etc
2. Click the network menu
3. See that both networks with the same chain id are selected

### Version

10.35.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by darkwing** [comment]
@tmashuang Could you provide me the exact network settings I can add into my MM to reproduce this?

**Comment by tmashuang** [comment]
```
Network Name: Ethereum Alt
RPC URL: https://ethereum.publicnode.com
Chain Id: 1
```
