### ISSUE TITLE
[Bug]: Edit Network Panel appears over the accounts panel

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#20145]
### Describe the bug

When opening the account on a block explorer on a network that doesn't have a specified block explorer, the edit network panel appears below the account choice panel.

### Steps to reproduce

1. Switch to another network with no specified block explorer. For example you can add Gnosis chain using this snippet on the console.
```js
ethereum.request({
  method: 'wallet_addEthereumChain',
  params: [
    {
      chainId: '0x64',
      chainName: 'GnosisChain',
      rpcUrls: ['https://rpc.gnosischain.com'],
      nativeCurrency: {
        name: 'GnosisChain ETH',
        symbol: 'XDAI',
        decimals: 18,
      },
    },
  ],
});

```

2. Click the open block explorer link

https://github.com/MetaMask/metamask-extension/assets/13814744/f2ad6636-f4d2-4a2a-a2b0-470618ff0b6c

### Version

10.34.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by SamarthBagga** [comment]
@pedronfigueiredo , I am unable to reproduce this bug, seems like it has been fixed.
