### ISSUE TITLE
Make web3 deprecation notice more prescriptive

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2014]
The current notice mentions deprecation but does not describe any advised behavior. We should add the preferred usage to our developer guide, including how to import a web3 or ethjs module, and link to it in the notice.

**Comment by flyswatter** [comment]
I've added a draft for an article on this here:
https://github.com/MetaMask/faq/blob/master/detecting_metamask.md

**Comment by ftppro** [comment]
Please provide examples, as requested here:
https://ethereum.stackexchange.com/questions/25962/please-provide-example-for-web3-currentprovider
