### ISSUE TITLE
Update ModalHeader to use TS Box version

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20159]
Dependency: https://github.com/MetaMask/metamask-extension/issues/20158

### Description
Currently, the `ModalHeader` component is using the deprecated JavaScript version of the `Box` component as a base component. This is causing issues with the polymorphic `as` prop and blocking further TypeScript migration in the extension.

Here are some examples of components that are using new TypeScript `Box` type conventions
- [ui/components/component-library/text/text.tsx](https://github.com/MetaMask/metamask-extension/blob/edbc728014c7eca3a0327e8ae979d461d6f3f336/ui/components/component-library/text/text.tsx)
- [ui/components/component-library/avatar-base/avatar-base.tsx](https://github.com/MetaMask/metamask-extension/blob/edbc728014c7eca3a0327e8ae979d461d6f3f336/ui/components/component-library/avatar-base/avatar-base.tsx)

### Technical Details
- Update the `ModalHeader` component to use the TS version of the `Box` component 
- Migrate any constants to enums
- Update any deprecated constants to enums 

### Acceptance Criteria
- The `ModalHeader` component is using the TS version of the `Box` component 

### Difficulty: Intermediate
Good first issue for: External contributors who are familiar with TypeScript and want to contribute to improving the stability of the extension

**Comment by ka3lx** [comment]
@georgewrmarshall I'd like to work on this. Can you assign it to me?

**Comment by georgewrmarshall** [comment]
Hey @ka3lx, thanks for your interest in contributing to MetaMask! I've assigned you the issue and look forward to your PR. If a PR hasn't been submitted within a week I will unassign and release it back to the community. Feel free to still submit a PR against this issue but it will give other engineers a chance to contribute to this task. Thanks!

**Comment by georgewrmarshall** [comment]
Good call. This ticket has been compelted
