### ISSUE TITLE
bug to work with polygon-edge

### ISSUE THREAD

**Issue by polygomic** [MetaMask/metamask-extension#20169]
### Describe the bug

Polygon-edge is one of most used evm base blockchain.
Polygon-edge show estimated gas fee but all transaction got Transaction 4 failed! [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32600,"message":"invalid tx type"}}}' 

### Steps to reproduce

1.
when try to send transaction we got failed! [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32600,"message":"invalid tx type"}}}'  in Polygon-edge

### Error messages or log output

```shell
failed! [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32600,"message":"invalid tx type"}}}'
```

### Version

10.33.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Additional context

failed! [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32600,"message":"invalid tx type"}}}'

**Comment by danjm** [comment]
@polygomic could you give more info on how you hit this error? What were the specific steps you took? Could you give an example of the transaction data? Or a dapp where a transaction can be created that results in the error you are seeing?

**Comment by polygomic** [comment]
Polygon created supernet blockchain as polygon-edge at https://github.com/0xPolygon/polygon-edge
when use install this blockchain we could not do transaction with metamask
here is rpc url for test
rpcurl : http://185.128.137.244:28545
chainId : 4243
coin: Nexi
I created test account for you on blockchain and put 10 Nexi on it
the private key is : cba9c53fb60574464896da623fc4e835e74b3ac4c32c70e5e865f3785cad05c7
try to do a transaction.

**Comment by danjm** [comment]
@polygomic Thanks for the rpcurl and the private key

The `invalid tx type` error that you are seeing is coming from the network itself. Upon sending a transaction, the network returns that error.

I can see that error defined in their codebase here https://github.com/0xPolygon/polygon-edge/blob/develop/txpool/txpool.go#L59

I can see that error is returned here https://github.com/0xPolygon/polygon-edge/blob/bbbe3abe1b438ea205f39fedd02086d6c890e616/txpool/txpool.go#L599C22-L605

```
if tx.Type == types.DynamicFeeTx {
		// Reject dynamic fee tx if london hardfork is not enabled
		if !p.forks.London {
			metrics.IncrCounter([]string{txPoolMetrics, "invalid_tx_type"}, 1)

			return ErrInvalidTxType
		}
```

` types.DynamicFeeTx` is defined here https://github.com/0xPolygon/polygon-edge/blob/develop/types/transaction.go#L23 `DynamicFeeTx TxType = 0x02`

MetaMask sets a transaction type to `0x02` if there is a `baseFeePerGas` property in the response to `eth_getBlockByNumber`. This is the case for the network you have shared.

So perhaps either a london hardfork configuration needs to be turned on, or there is a bug causing `baseFeePerGas` to be in the `eth_getBlockByNumber` response when it should not be.

**Comment by danjm** [comment]
@polygomic I have commented in the issue you created in the polygon-edge repo. I am going to close this for now as I am pretty sure it is a problem on the polygomic side.

If further investigation reveals any issues with MetaMask's handling of this network or its transactions, feel free to comment here or open a new issue.
