### ISSUE TITLE
[Bug]: Token Price, Name, Ticker, or Icon is Displayed Incorrectly in the Token List

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-extension#20165]
### Describe the bug

The token price, name, ticker, or icon is incorrect (one, some, or all at once).

This confuses users who import a token manually or swap for a token, and in their token list is the wrong token name or the token's value is drastically different from what it actually is. This is not a token decimal issue but seems to be an issue with the queried token data.

Example
**Network**: BSC
**Token**: Baby Satoshi (SATS) 0xa1D04A189f8b6d5d64e8Fea7c38846AB6fa0F823
![sats](https://github.com/MetaMask/metamask-extension/assets/2859402/1816207f-82b0-4c32-9f1a-8ddcc33a283b)

MetaMask displays a value of 4¢ for 263 SATS, when the actual value (at the time of this post) is $127. All other information (name, ticker, and icon) is correct.

![Screenshot 2023-07-24 at 16 37 45](https://github.com/MetaMask/metamask-extension/assets/2859402/e179a8de-010d-4364-b0a3-c42c013a369d)
(Source: https://www.geckoterminal.com/bsc/pools/0x8678319c6876af75cd5bf5e5a720b9a6635d6522)

### Steps to reproduce

1. Manually import a token
2. The token information is incorrect.

### Version

10.34.0

### Build type

None

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS, Linux

**Comment by danjm** [comment]
Related https://github.com/MetaMask/metamask-extension/issues/18951

**Comment by deshvin** [comment]
**Network**: Ethereum
**Token**: Decentral Games (DG) 0x4b520c812e8430659fc9f12f6d0c39026c83588d
**Issue**: Shows as DeGate Token (DG) and the wrong token icon
![image](https://github.com/MetaMask/metamask-extension/assets/2859402/16469da6-d149-4502-a386-3cda7f799f8f)
![image](https://github.com/MetaMask/metamask-extension/assets/2859402/63cef568-3f29-4a59-a3c5-5abaedb77370)

**Comment by deshvin** [comment]
**Network**: Ethereum
**Token**: Pantos Token (PAN) 0x536381a8628dbcc8c70ac9a30a7258442eab4c92
**Issue**: Shows as Panvala Pan (PAN) 0xd56dac73a4d6766464b38ec6d91eb45ce7457c44
![ymail-tmp-2125307748855558305](https://github.com/MetaMask/metamask-extension/assets/2859402/6d6d5560-b9fa-4cb9-8852-06958364b42d)
![image](https://github.com/MetaMask/metamask-extension/assets/2859402/4a2900a5-edb2-409f-b724-7218601f8eec)

**Comment by deshvin** [comment]
**Network**: Ethereum
**Token**: Flow Protocol (FLOW)
**Issue**: The token price in the Asset List seems to be showing the price for [Flow](https://www.coingecko.com/en/coins/flow) (FLOW; the native token of the Flow blockchain)
![flow-price](https://github.com/MetaMask/metamask-extension/assets/2859402/5e8225ad-dcae-435d-ac52-5f2d48205157)
![Screenshot 2023-08-03 at 15 08 51](https://github.com/MetaMask/metamask-extension/assets/2859402/a57c8c18-19fd-4953-930b-8698ee65c098)

**Comment by Bullcoiner** [comment]
Network: ETH/BSC
Token: T.I.M.E. Dividend (TIME)
Contract ID: 0xd08481058399490B83a72676901d4e9dB70E75aC
Issue: the imported token instead shows up as ChronoBank TIME/Chrono.tech TIME 0x485d17A6f1B8780392d53D64751824253011A260

![image](https://github.com/MetaMask/metamask-extension/assets/145404283/abe6b695-3c1a-4c28-b37f-28dcb2322b16)
![image](https://github.com/MetaMask/metamask-extension/assets/145404283/abf83915-8d26-48a1-87ef-dd1beda68cd2)

**Comment by deshvin** [comment]
**Network**: Ethereum
**Token**: SushiSwap LP Token (SLP) (0x6a091a3406e0073c3cd6340122143009adac0eda)
**Issue**: Token shows as Smooth Love Potion (SLP) (0xCC8Fa225D80b9c7D42F96e9570156c65D6cAAa25)

![SLP](https://github.com/MetaMask/metamask-extension/assets/2859402/145d915d-1834-493e-8f3d-fef39cfe6203)

![SLP Info](https://github.com/MetaMask/metamask-extension/assets/2859402/5aad5975-653d-47c6-8d10-910052d160a9)

**Comment by salimtb** [comment]
fixed

**Comment by BTCLottery** [comment]
Network: Ethereum
Token: 0x4e114d405b9ba2f59524941733e505ae03fb1fb5
Issue: Token shows as JOYSO instead of Joystick (JOY) and logo is also wrong!

**Comment by Liberalite** [comment]
Network: Ethereum
Token: 0x4e114d405b9ba2f59524941733e505ae03fb1fb5
Issue: Token shows as JOYSO (JOY) instead of Joystick (JOY) and the logo is also wrong!
![Screenshot 2023-11-03 at 19 16 04](https://github.com/MetaMask/metamask-extension/assets/42842639/e1aea414-e4a9-413e-a775-7231ce883ce9)

**Comment by Liberalite** [comment]
Network: Ethereum
Token: 0x4e114d405b9ba2f59524941733e505ae03fb1fb5
Issue: Token shows as JOYSO (JOY) instead of Joystick (JOY) and the logo is also wrong!
![Screenshot 2023-11-03 at 19 16 04](https://github.com/MetaMask/metamask-extension/assets/42842639/e1aea414-e4a9-413e-a775-7231ce883ce9)

**Comment by ms1261** [comment]
Network: Ethereum
Token: 0xea1ea0972fa092dd463f2968f9bb51cc4c981d71
Issue: Token shows as **Modum** (MOD) instead of **Modefi** (MOD) and the logo is also wrong.
![github1](https://github.com/MetaMask/metamask-extension/assets/150184955/700f890d-cb05-41ec-9e3c-27b7fa8e6930)

**Comment by deshvin** [comment]
**Network**: Beam
**Token**: BEAM (native token)
**Issue**: The token price is incorrect; the wrong BEAM token is being queried.

- WRONG (https://www.coingecko.com/en/coins/beam | API id: beam)
- CORRECT (https://www.coingecko.com/en/coins/beam-2 | API id: beam-2)

![image](https://github.com/MetaMask/metamask-extension/assets/2859402/730c0ff4-6fc9-48a4-a285-05f0660b0d7a)

**Comment by deshvin** [comment]
@salimtb 
**Network Name**: Beam
**RPC**: https://subnets.avax.network/beam/mainnet/rpc
**Chain ID**: 4337
**Token Symbol**: Beam
**Explorer**: https://subnets.avax.network/beam

btw user has updated to 11.5.0 and confirmed the price is still incorrect on this network.

I checked a few of the ERC-20 tokens in this thread and they are all correct now on 11.5.0.

**Comment by salimtb** [comment]
hey @deshvin ,
eemm ok , the fix on this ticket was on the erc-20 only. 
just created a new [issue](https://github.com/MetaMask/metamask-extension/issues/21891) here for native network, will work on it asap.
thank you for the report , feel free to add any details you want on the issue link
