### ISSUE TITLE
Create What's New for Account Details being duplicated to main menu

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#20162]
## Background
Based on users not being able to find block explorer and account details, we've decided to duplicate that menu item from the Account selection screen and move it back to the global menu.

This [fix](https://github.com/MetaMask/metamask-extension/pull/20013) will be released with v10.36 which will release to users ~ Aug 17th.

## Acceptance criteria
Create a What's New this fix. I could resemble the [tweet](https://twitter.com/MetaMask/status/1683613442668908544) that was sent on Jul 24:

Copy:
Looking for your account details or the block explorer URL?
💡 Just click the global menu or account menu to find them! 

## Designs

![Screenshot 2023-07-27 at 19.06.19.png](https://images.zenhubusercontent.com/61ef00ec5db2d7c84498dc72/2c23afec-2101-481f-b931-a5a932b6386c)

[Figma](https://www.figma.com/file/ogXqmRQfMj8UiWg8LhAtR8/What's-new-Account-details?type=design&node-id=1203-25543&mode=design&t=nhWT1l77p8toZPsi-0)

**Comment by Billiej88** [comment]
> ## Background
> Based on users not being able to find block explorer and account details, we've decided to duplicate that menu item from the Account selection screen and move it back to the global menu.
> 
> This [fix](https://github.com/MetaMask/metamask-extension/pull/20013) will be released with v10.36 which will release to users ~ Aug 17th.
> 
> ## Acceptance criteria
> Create a What's New this fix. I could resemble the [tweet](https://twitter.com/MetaMask/status/1683613442668908544) that was sent on Jul 24:
> 
> Copy: Looking for your account details or the block explorer URL? 💡 Just click the global menu or account menu to find them!
> 
> ## Designs
> ![Screenshot 2023-07-27 at 19.06.19.png](https://camo.githubusercontent.com/f6b28e07060b29449838390377bd592ee1a0f13da470d0adf61ef090950e67c7/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631656630306563356462326437633834343938646337322f32633233616665632d323130312d343831662d623933312d613561393332623633383663)
> 
> [Figma](https://www.figma.com/file/ogXqmRQfMj8UiWg8LhAtR8/What's-new-Account-details?type=design&node-id=1203-25543&mode=design&t=nhWT1l77p8toZPsi-0)
