### ISSUE TITLE
Update ModalContent to use TS Box version

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20160]
### Description
Currently, the `ModalContent` component is using the deprecated JavaScript version of the `Box` component as a base component. This is causing issues with the polymorphic `as` prop and blocking further TypeScript migration in the extension.

Here are some examples of components that are using new TypeScript `Box` type conventions
- [ui/components/component-library/text/text.tsx](https://github.com/MetaMask/metamask-extension/blob/edbc728014c7eca3a0327e8ae979d461d6f3f336/ui/components/component-library/text/text.tsx)
- [ui/components/component-library/avatar-base/avatar-base.tsx](https://github.com/MetaMask/metamask-extension/blob/edbc728014c7eca3a0327e8ae979d461d6f3f336/ui/components/component-library/avatar-base/avatar-base.tsx)

### Technical Details
- Update the `ModalContent` component to use the TS version of the `Box` component 
- Migrate any constants to enums
- Update any deprecated constants to enums 

### Acceptance Criteria
- The `ModalContent` component is using the TS version of the `Box` component 

### Difficulty: Intermediate
Good first issue for: External contributors who are familiar with TypeScript and want to contribute to improving the stability of the extension

**Comment by dhruvv173** [comment]
hey @georgewrmarshall, this issue is similar to other migration issues, except in this one we just have to export types for props and component from `.types.ts` file and updating the `modal-content.tsx` file, right?
