### ISSUE TITLE
[Bug]: Balance and fiat display inverted from home screen and account list menu

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#20182]
### Describe the bug

When we display balance and its fiat conversion rate with the primary currency set to the network, we display the top as the primary currency and the bottom as the fiat conversion on the home screen. This is not the case on the account list menu, we show the fiat conversion on top and the primary currency on bottom. When toggling the primary currency fiat it switches them on both screens. **If this is intended, feel free to close.**

<img width="282" alt="home-screen-balance" src="https://github.com/MetaMask/metamask-extension/assets/13376180/b5774810-4d77-4eed-aec0-49844c33c3e8">
<img width="287" alt="account-list-balances" src="https://github.com/MetaMask/metamask-extension/assets/13376180/4ef1a2d9-910f-4966-bc54-c32fceefd93b">

### Steps to reproduce

1. Either on Ethereum mainnet, or on a test network with the "Show conversion on test network" setting enabled, have a balance on the network.
2. See the balance on the home screen to be primary currency on top and the conversion to fiat on bottom.
3. Click to bring up the account list menu, and see that the fiat currency is on top and the primary network currency to be on bottom.
4. Toggle the primary currency to Fiat, and see that the balance have switched on both views.

### Version

10.34.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by SaraCheikh** [comment]
@darkwing @kevinghim  wallet view, account list and token list should follow the currency preference of the user. Now only the total balance int he wallet view actually reflect the preference of the user. 

This would be the expected behaviour:

<img width="770" alt="Screenshot 2023-07-27 at 11 07 59" src="https://github.com/MetaMask/metamask-extension/assets/98161559/b5c0d739-b423-49e8-9345-bafb320177bd">

**Comment by kevinghim** [comment]
@SaraCheikh I agree. If the user selects ETH as their primary currency, then that should be on the top and fiat on the bottom for all screens where currencies are displayed. So we should fix this.
