### ISSUE TITLE
[Bug]: The authorization limit has been passed, but the user needs to fill it out themselves.

### ISSUE THREAD

**Issue by liubin595338764** [MetaMask/metamask-extension#20193]
### Describe the bug

**Describe the bug**
The authorization limit has been passed, but the user needs to fill it out themselves. The incoming authorization limit should be displayed directly in this location.

Excessive input actions are unfriendly to user experience.

<img width="420" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/5274428/6fa348e7-cdbf-4a8f-a592-5ba2c6da025a">

**Expected behavior**
The incoming authorization limit should be displayed directly in this location.

### Steps to reproduce

1.

### Version

10.34.0

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS

**Comment by bschorchit** [comment]
Hey @liubin595338764 thank you for your report. This will be addressed in the release v10.35 that should be rolling out to users towards the end of the month. As this has been addressed already, I'll close this issue for now. Please do open new ones with other issues you might encounter.

**Comment by liubin595338764** [comment]
@bschorchit Hi, I have already used the latest version of the Chrome extension (10.34.3), but this problem still exists;

The default value here is not the value passed in the code, but still requires manual input from the user.

<img width="360" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/5274428/618954d3-7636-45fd-abd7-b374338b7703">

**Comment by liubin595338764** [comment]
@anaamolnar This problem still exists, please reopen this bug.
