### ISSUE TITLE
Refactor `EncryptionPublicKeyController` to use `@metamask/keyring-controller`

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/metamask-extension#20206]
After closing https://github.com/MetaMask/core/issues/1556 `getEncryptionPublicKey` will be available also on  `@metamask/keyring-controller`, allowing us to drop `@metamask/eth-keyring-controller` usage completely from `EncryptionPublicKeyController`.

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/metamask-extension/20206?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @mikesposito @mcmire
