### ISSUE TITLE
[Ext] AvatarIcon Production Audit

### ISSUE THREAD

**Issue by garrettbear** [MetaMask/metamask-extension#20215]
AvatarIcon has been updated to TS. Let's review the code and improve it. Developers prefer using IconSize to adjust Avatars, so we should consider potential enhancements.

![Screenshot 2023-07-26 at 10.09.53 AM.png](https://images.zenhubusercontent.com/62cf3bd9170a05437d105fb8/a2c68226-8c97-443d-9466-15aeeb15808f)

**Comment by georgewrmarshall** [comment]
This is complete in #19107
