### ISSUE TITLE
[Bug]: User can't set a custom tx nonce on spending cap tx

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#20229]
### Describe the bug

Users might want to unstick their spending cap transactions, speed them up or cancel them.

#### Screenshots

<img width="320" src="https://github.com/MetaMask/metamask-extension/assets/13814744/7996098d-3297-4fa6-acac-065da64a70ed">

<br />

<img width="640" src="https://github.com/MetaMask/metamask-extension/assets/13814744/83be9ecb-aeb5-45bc-949d-8b276c185fdc">

<img width="640" src="https://github.com/MetaMask/metamask-extension/assets/13814744/f0f0c09a-ba3e-4523-9ed9-7c2ed2f520ef">

### Steps to reproduce

1. Enable tx nonce customisation on MetaMask on Settings > Advanced > Customise transaction nonce
2. Navigate to `https://app.uniswap.org/#/swap`
3. Try to spend a token you haven't swapped with before
4. The spending cap screen will come up, with no input field for editing the tx nonce.

### Version

10.34

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Closing as a duplicate of https://github.com/MetaMask/metamask-extension/issues/17505. The fix is included in the 10.35 release.
