### ISSUE TITLE
[EXT] External component library RAPID

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20222]
### Description
Currently, the design system architecture limits the ability for engineers working on project outside of the mobile and extension repos to use the component library components. Having an external component library brings several benefits to MetaMask as a whole. It would allow for standardized and reusable components, reducing the need for duplicative development efforts and promoting consistency of brand, trust and a consistent experience beyond just mobile and extension products.

### Current Design System Architecture
<img width="1023" alt="Screenshot 2023-07-26 at 4 08 44 PM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/4d1f87f6-a416-42e4-a72b-e195f80b4643">

### Future Design System Architecture
<img width="954" alt="Screenshot 2023-07-26 at 4 09 39 PM" src="https://github.com/MetaMask/metamask-extension/assets/8112138/e06cd930-2033-4f36-b91b-b9e2cd9c90a1">

**Comment by Ehsan129** [comment]
1299820

در تاریخ پنجشنبه ۲۷ ژوئیه ۲۰۲۳،‏ ۰۲:۳۹ George Marshall <
***@***.***> نوشت:
