### ISSUE TITLE
[Bug]: calling `wallet_requestPermissions` providing an address is ignored

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/metamask-extension#20237]
### Describe the bug

1. `wallet_requestPermission` is not respecting the caveats in the permissions approval screen that pops up. the approval UI screen should show the the addresses passed in pre selected the UI.

### Steps to reproduce

1. requestPermissions with an account that is not currently selected:
```
await window.ethereum.request({
  "method": "wallet_requestPermissions",
  "params": [
    {
      "eth_accounts": {
        "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266": true
      }
    }
  ]
});
```

or 

```
         await window.ethereum.request({
          method: 'wallet_requestPermissions',
          params: [
            {
              eth_accounts: {
                "caveats": [
                  {
                    "type": "restrictReturnedAccounts",
                    "value": [
                      "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
                     ]
                  }
                ]
              },
            },
          ],
        })
```

2. see that it is not pre selected in the approval UI

### Version

10.34.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by vandan** [comment]
You have to be on a different account to reproduce this issue.

**Comment by vandan** [comment]
May relate to this MIP: https://github.com/MetaMask/metamask-improvement-proposals/pull/24
