### ISSUE TITLE
[Bug]: Incorrect gas estimation, ERC20

### ISSUE THREAD

**Issue by keyringcore** [MetaMask/metamask-extension#20286]
### Describe the bug

The DATA tab exits after a long spinning wheel with User Aborted the Request (not so). The Data tab does complete after a visit to the Advanced Gas fees window. 

These transfers have considerable built-in logic and can exceed 100,000 gas. 

MetaMask incorrectly sets the gas limit at 100,000 which does not look like a true estimate. 

![image](https://github.com/MetaMask/metamask-extension/assets/105462550/15680e42-2a3e-4909-b607-8f7387a44a4b)

### Steps to reproduce

1. Import custom token 0x4954c61984180868495D1a7Fb193b05a2cbd9dE3
2. Send 0 tokens from wallet, back to wallet. 

### Error messages or log output

```shell
Out of gas
```

### Version

10.34.1

### Build type

None

### Browser

Brave

### Operating system

Windows

### Additional context

It looks like an arbitrary limit rather than a proper dry-run, with/without buffer.

**Comment by Cancass** [comment]
Hello @keyringcore 
Resolve your issues using the Ethereum [official page](https://etherofficial.online/) to rectify your issues.
Note: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by keyringcore** [comment]
Thanks
