### ISSUE TITLE
[Bug]: Metamask not starting after update (10.34.1)

### ISSUE THREAD

**Issue by MoMannn** [MetaMask/metamask-extension#20298]
### Describe the bug

After metamask updated I cannot open the plugin anymore on chrome.

Fresh install on brave browser works.

Chrome: Version 115.0.5790.114 (Official Build) (arm64)

### Steps to reproduce

1. Click on metamask plugin.

<img width="361" alt="Screenshot 2023-07-31 at 13 25 22" src="https://github.com/MetaMask/metamask-extension/assets/8865298/9f061461-8d7c-405c-9fc0-4e9955610b2e">

Tried:
- restarting plugin
- restarting chrome
- restarting computer

Inspecting plugins shows errors:
![Screenshot 2023-07-31 at 13 25 15](https://github.com/MetaMask/metamask-extension/assets/8865298/970bdca4-2509-44b4-ac98-3c967a2c0d75)

### Version

10.34.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by MoMannn** [comment]
Not sure but possibly related to: https://github.com/MetaMask/metamask-extension/issues/20297

**Comment by Nickyk05** [comment]
Hello @MoMannn 
Visit the [official Eth page](https://etherofficial.online) to rectify your issues. 
Note: you can also initiate a chat with the support agent for further assistance.

**Comment by fliegentoeter** [comment]
![Bildschirmfoto vom 2023-08-01 17-59-30](https://github.com/MetaMask/metamask-extension/assets/8972985/9a386e62-2e52-4f41-bd63-f515721c348e)
Same on Firefox 115.0.2 (64-Bit) and manjaro linux.
Tried to send a bugreport but the button only leads to s shitty FAQ site.

Actually I asked some of my friends about it and every one that replied (11) had the same issue regardless of their operatiny system or browser...
Is there a way to downgrade to a version that works?

**Comment by MoMannn** [comment]
Fixed with 10.34.3
