### ISSUE TITLE
Integrate transaction insights v2 api

### ISSUE THREAD

**Issue by hmalik88** [MetaMask/metamask-extension#20303]
Transaction insights v2 api needs to be integrated into the extension with the following [designs](https://www.figma.com/file/7JOVfBCxfHiz8xOwbuWF3j/Snaps-Platform-v2?type=design&node-id=81-30407&mode=design&t=U87BnVRxZh9M9LPZ-0)

**Comment by kenhkan** [comment]
From standup: Only remaining task is team's review.

**Comment by kenhkan** [comment]
Hassan to follow up with Bowen on E2E test
