### ISSUE TITLE
[Bug]: Unable to connect hardware wallet after having connected to two

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#20331]
### Describe the bug

I selected "add hardware wallet", but I saw the list of accounts I had just selected with the previous hardware wallet connection. I was unable to add a second hardware wallet until I restarted the browser.

### Steps to reproduce

1. Have the same SRP on two different hardware wallets: A (keystone) and B (trezor)
2. Connect accounts 1 & 2 on hww A.
3. "Forget" account hwwA account 1.
4. "Connect hardware wallet", select hww B. Select account 1.
5. "forget" account hwwB account 1.
6. Click "Connect hardware wallet"

### Error messages or log output

```shell
We see the account selection view from step 4, and are unable to select a new hardware wallet to connect.
```

### Version

10.33.0-flask.0

### Build type

Flask

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

### Additional context

Experiencing this bug involved a Trezor and a Keystone wallet. I'm not sure if the bug is particular to them, or some other way that the hardware wallet connection flow is stateful and is not reset upon successful connection.

**Comment by plasmacorral** [comment]
Just a note here that while feature QA testing PR 20998 in flask, I notice that if I attempt to add a QR wallet after adding Ledger I am not able to.  I expect that the camera permission should be requested to scan and bind the hardware wallet to MM.  Instead, I simply am shown a yellow spinning wheel `Looking for your qr hardware...`

Mac Sonoma 14.0
v11.1
Chrome 117

Reproduction steps:

1. Setup wallet
2. Add Ledger device
3. Attempt to add QR hardware
4. Observe being stuck at spinning wheel
![Screenshot 2023-09-29 at 4 08 38 PM](https://github.com/MetaMask/metamask-extension/assets/32695229/dc18aeca-a32d-45d9-840c-d430759202e6)

**Comment by vivek-consensys** [comment]
I am able to replicate this issue. See screen recording here:

https://github.com/MetaMask/metamask-extension/assets/106310394/6c92d660-dcd0-45b1-92c7-452c0dbe18da

**Comment by vivek-consensys** [comment]
Fixed by [PR 22851](https://github.com/MetaMask/metamask-extension/issues/22851). Attaching screen recording and closing the issue. Please reopen, if you are still facing the issue. 


https://github.com/user-attachments/assets/d8cc0a59-e2f6-48bc-929f-d760484bd9c2
