### ISSUE TITLE
RPC error with payload

### ISSUE THREAD

**Issue by yungwolf** [MetaMask/metamask-extension#2038]
So I am unable to transfer funds from ether delta into my wallet.I have enough funds for the transaction but overtime I click submit, an error comes up on metamask stating the transaction has failed. It writes " replacement transaction underpriced". Any help would be super appreciated. Is delta just not working for the past couple hours?>

**Comment by flyswatter** [comment]
I don't think this is an EtherDelta problem, I think there's some edge case that our new nonce tracker isn't handling right. It could help for more people to submit state logs for this situation (the one I have right now is a very long long, hard to analyze).

To submit logs for this, open a ticket on https://support.metamask.io and include logs:
https://support.metamask.io/kb/article/15-copying-state-logs

**Comment by flyswatter** [comment]
Had you recently sent another transaction on the same account from another device? MetaMask cannot account for rapid use between two devices.

**Comment by yungwolf** [comment]
Ya I guess I just needed to use more gas. All good now thanks

**Comment by ezguy** [comment]
hey I also had an issue when trasnfering ETH from metamask to my wallet. it failed and said "rpc error with payload" and erorr nonce too low and now I still havent got my funds for ETH? how do i get them back and what do those errors mean?

**Comment by danfinlay** [comment]
@ezguy please open a support ticket at support.metamask.io and we'll help you as soon as we can.

**Comment by bitcoinxyz** [comment]
I have deposit in my mask for trading in idex and ddex for some profit but i am unable to send any thing to my ddex or idex and even other wallet i mean unable to send ETH or token i even attached with myetherwallet with mask even unable to send. 
Its showing me rpc error unable transtion chrome even its says gas fee is to low i have increased it but didnt happen anything
for this risin i have lost my profit and time.
 is my account safe for this
 how do i cove this loss 
and when will i be able to send my eth 
is it will be use full next for transtion

**Comment by AisinGioroHanani** [comment]
Reset account in Metamask would solve it.

**Comment by jobinjohnym84** [comment]
Facing the same issue, while trying to buy ether via meta mask- ropsten network. Do we have a workaround please?
