### ISSUE TITLE
Transaction confirm pop-up should close after submitting/rejecting the transaction

### ISSUE THREAD

**Issue by pcppcp** [MetaMask/metamask-extension#2039]
## Problem:
We are using MM as a backend for our js app. Whenever app calls a contract, a MM will display a pop-up asking user to confirm the transaction.
After confirming or rejecting the transaction the pop up remains visible, and user must do Alt+F4 or click close button.
This leads to a terrible user experience, as after a while many annoying and  redundant pop-ups pollute the workspace, all of them displaying the same thing.

## Expected Behavior:
The tx popup should close automatically after tx confirm/reject. User can always check the tx status by opening the accounts window.

## Browser used:
Chromium Version 58.0.3029.96 (64-bit)

OS:
openSUSE 42.2

**Comment by flyswatter** [comment]
That's definitely strange, MetaMask does call the WebExtension API for closing the transaction approval window on confirmation or rejection, this may be a problem with openSUSE.

**Comment by pcppcp** [comment]
Thanks for confirming that it is an expected behaviour. My colleagues also confirmed that on their Ubuntu it works properly.

I've also tried most recent build of Chromium available, and I've also created a test user to test it with a fresh config of Chrome, but no luck with that. So it's maybe some weird OS/wm related bug (or feature :))
