### ISSUE TITLE
Snaps in Core - UI/UX refinement 

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#20398]
[DO NOT CLOSE]

This is a work in progress holder for all the required UI/UX refinement that we must consider or review before launching Snaps in Core.

- [x] #20399
- [x] #20400
- [x] #20401
- [x] #20402

**Comment by mustafaazad03** [comment]
Hi,
Is this issue is still open?? Can I contribute ??

**Comment by kenhkan** [comment]
@holantonela We should be complete with this list. Can you confirm that the ticket can be closed? If not, what remains that needs Snaps team's attention?
