### ISSUE TITLE
[Bug]: Permissions modal is hard limited at about 4 lines and does not expand or scroll even if there are more permissions 

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-extension#20405]
### Describe the bug

In the following section: 

<img width="386" alt="Screenshot 2023-08-04 at 1 45 13 PM" src="https://github.com/MetaMask/metamask-extension/assets/19909/a67bb3d5-784e-422b-bef8-9c2482ad6f57">

That list is about 9 lines long but it is cut off after 4 lines and there is no way to scroll or expand it

### Steps to reproduce

1. Use Flask
2. Go to https://metamask.github.io/test-snaps/latest/
3. Connect and install at least 5 snaps on that page
4. Open the extension
5. Click on the globe icon
6. Expand the permissions section
7. Observe that the content overflows the section and you cannot view all of it

### Version

10.33.0-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

**Comment by mustafaazad03** [comment]
Hi,
Can I work on this ??
