### ISSUE TITLE
Update connection state UI for dapps connected via Snaps (without accounts involved)

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#20400]
Right now, when the dapp is connected to MetaMask via a snap the Connection indicator shows a non-connection indicator (grey badge). This is a problem because the dapp **is** connected to MM via the snap, as explicitly shown in Settings. 

**Proposed solution**
We rely on the same UI pattern indicator. The connection indicator shows a green dot.

**Comment by holantonela** [comment]
https://www.figma.com/file/7lZVyuTGlkLqv81k6G4Pfz/Snaps-in-Core-fixes?type=design&node-id=106%3A8952&mode=design&t=H3w3xQHtYNPxaWX1-1

**Comment by kevinghim** [comment]
@SaraCheikh can you have the issue design ready?

**Comment by SaraCheikh** [comment]
@Kevin Ghim ***@***.***> apologies, I can't login to Github
yet (2F authentication issues) that's why i asked Antonela to paste the
design link

**Comment by kevinghim** [comment]
Will be resolved through https://github.com/MetaMask/metamask-extension/issues/20792
