### ISSUE TITLE
Update connection state UI for dapps connected with Accounts via Snaps

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#20401]
Right now, when the dapp is connected to MetaMask via a snap the Connection indicator shows a non-connection indicator (grey badge). This problem is because the dapp is connected to MM via the snap, as shown in Settings. Unlike #20400, the snap account should be shown in the connection menu. 

**Proposed solution**
We rely on the same UI pattern indicator. The connection indicator shows a green dot. The account should show up in the list and shows as "connected"

**Comment by kevinghim** [comment]
Will be resolved through https://github.com/MetaMask/metamask-extension/issues/20792
