### ISSUE TITLE
[Bug]: Error: LavaMoat - property "Proxy" of globalThis is inaccessible under scuttling mode

### ISSUE THREAD

**Issue by henzycuong1** [MetaMask/metamask-extension#20414]
### Describe the bug

I got `Message: unknown error: Runtime.callFunctionOn threw exception: Error: LavaMoat - property "Proxy" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.` when using selenium and chrome version 115. Can someone help me fix it

### Steps to reproduce

1.

### Error messages or log output

```shell
Message: unknown error: Runtime.callFunctionOn threw exception: Error: LavaMoat - property "Proxy" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
  at get (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11632:17)
  at serializationGuard (<anonymous>:198:67)
  at buildError (<anonymous>:319:27)
  (Session info: chrome=115.0.5790.171)
```

### Version

latest

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello, @henzycuong1. Thanks for reporting! I will pass this on to the team.
