### ISSUE TITLE
Please provide examples for web3.currentProvider, as requested here:

### ISSUE THREAD

**Issue by ftppro** [MetaMask/metamask-extension#2041]
Please provide examples for web3.currentProvider, as requested here:
https://ethereum.stackexchange.com/questions/25962/please-provide-example-for-web3-currentprovider

**Comment by flyswatter** [comment]
Here's a code example to hold you over, it isn't a sendTransaction, but it shows how the provider API matches the JSON RPC api:
https://github.com/flyswatter/js-eth-personal-sign-examples/blob/master/index.js#L40

**Comment by flyswatter** [comment]
As a reminder, the JSON RPC api is documented [here](https://github.com/ethereum/wiki/wiki/JSON-RPC).

**Comment by ftppro** [comment]
That example did not help at all. Please reply to the following post, and
indicate specifically how to convert the two JS methods that I have
provided in that post:
https://ethereum.stackexchange.com/questions/25962/please-provide-example-for-web3-currentprovider

Please also show how to use the web3.currentProvider object to create
myContractInstance (or another way to perform "sendTransaction", "call",
and "web3.toWei"), since apparently Web3 will no longer be available after
this deprecation. I also need an approximate date when this deprecation
will occur. Will it be deprecated in 1 month, 6 months, or perhaps never?

I don't want my websites to suddenly stop working when Web3 is no longer
included. As I indicated in the above-mentioned post, it is not possible to
use.any libraries that require an npm installation. If I need to simply
download a certain set of JS include files (with unambigous instructions),
that is acceptable.
