### ISSUE TITLE
[Bug]: very slow working on linux (ubuntu) firefox

### ISSUE THREAD

**Issue by Surya-Git-hub** [MetaMask/metamask-extension#20437]
### Describe the bug

In firefox browser the extension in working very slowly(unresponsive) one click is registered after 8-10 seconds. and ui also appears after some delay.

### Steps to reproduce

1.
just install extension in firefox browser running on ubuntu 22 stable version and do some transactions.

### Version

10.34.0

### Build type

None

### Browser

Firefox

### Operating system

Linux

**Comment by Surya-Git-hub** [comment]
yes @anaamolnar  i double checked the latest version available in the firefox, but for some reason the latest version on firefox is 10.34.0 and on github it is 10.34.4
![Screenshot from 2023-08-16 01-34-03](https://github.com/MetaMask/metamask-extension/assets/64036341/2e70fbb9-d370-4059-adc0-32409b284441)

**Comment by anaamolnar** [comment]
Hello, @Surya-Git-hub. Please update to the latest version and clean your browser's cache. Feel free to re-open this if it continues to occur. Thank you!
