### ISSUE TITLE
Metamask not able to connect to Main Ethereum Network, not able to login

### ISSUE THREAD

**Issue by sreekanth-kalapur** [MetaMask/metamask-extension#2043]
<img width="361" alt="screen shot 2017-09-07 at 11 18 32 pm" src="https://user-images.githubusercontent.com/13747219/30177265-ea2d8b26-9422-11e7-9e9a-628ac80f2445.png">

**Comment by flyswatter** [comment]
For user issues, please open a ticket on https://support.metamask.io
If a bug is identified, it will be opened as an issue here.

**Comment by mmustafaaslan** [comment]
Having the same problem at least 2 times in a week...

**Comment by ypershin** [comment]
The same problem today

**Comment by cjmoles** [comment]
No answers to this problem?

**Comment by tmashuang** [comment]
#2529. TLDR; switch network to Test Network and switch back to Mainnet

**Comment by cjmoles** [comment]
Wow....thanks!  Thought I tried that once....worked immediately this time. +1

**Comment by dl7267** [comment]
Thanks, this helped me get my MetaMask working. Perfect!

**Comment by sunsetblues** [comment]
Thanks! Worked for me. ;0)

**Comment by fylim** [comment]
Currently having this issue ? What is the problem ?

**Comment by escrowdis** [comment]
@fylim Had same issue now, but solved by instruction from @tmashuang

**Comment by Christophe80** [comment]
Still not working over here... :/

**Comment by chrisdnn** [comment]
Try to disable/enable the extension through the Extension Manager. This worked for me in Chrome.

**Comment by Douglasacost** [comment]
in my case the issue is caused by the date configuration

**Comment by Kralunar** [comment]
Same issue, switch internet Main-Secondary doesn't work :'( help

**Comment by romeshomey** [comment]
Having this issue again.   Switching to a secondary network and back to main again no longer works to resolve.

**Comment by danfinlay** [comment]
That's very strange.

For others coming here "having the same problem": It's almost never the same problem. If you have this symptom, please check your logs and open a new issue with anything you see there that is red (an error):

https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by 7urboPitt** [comment]
This adon is giving me problems on opera browser, wont work with correct password, I am new and paranoid to mining. is this a bug a flaw or a scam , all of my software is up to date. If it dont work from seed phrase I am seriously gona dump this ware.

**Comment by danfinlay** [comment]
@7urboPitt If this were a scam, why would WE tell you? ;)

To get some personal help, please email support@metamask.io 

We're happy to try to work through any problems you're having.

**Comment by tusharpawar789** [comment]
@danfinlay Dear Sir,
Warm greetings from India..!

Since last few day, I'm facing issue with metamsk i.e. the chrome extension of metamask is not connecting to main etherium network. I'm facing this issue at least for last 20 days. I have also tried to switch to another netwrok and then again to connect with main etherium network but I can only see the infinite speener on my metamask extension. Can you please help me to sort out this issue ?

I have no technical knowledge about why this is happening and without your help I won't be able to sort it out.

Please help.
![metamask](https://user-images.githubusercontent.com/37632683/37727297-782fcc30-2d5d-11e8-8fa6-2777cb2f8f9c.jpg)

**Comment by graciousunit** [comment]
Please I need help. I have tried to switch to another network and back to ethereum network still is not connecting. Help call me +2348033772721 or email me okaroworld@gmail.com

**Comment by danfinlay** [comment]
To get some personal help, please email support@metamask.io
