### ISSUE TITLE
[Bug]: Metamask crashes if additional data is added at the end of an ERC20 approval transaction calldata

### ISSUE THREAD

**Issue by georgeroman** [MetaMask/metamask-extension#20438]
### Describe the bug

If any additional bytes are added at the end of an ERC20 approval transaction data (the standard `function approve(address spender, uint256 amount)`), Metamask will crash with the following message:    

    Message: Invalid token value; should be exactly 64 hex digits long (u256)

    Code: Error
    Stack:

    Error@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/runtime-lavamoat.js:7838:17
    n.getCustomTxParamsData@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-8.js:1:188827
    W@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-10.js:1:334200
    va@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:60111
    Mu@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:105038
    Al@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:90903
    Rl@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:90826
    El@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:88166
    ti/<@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:46516
    n.unstable_runWithPriority@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:416038
    Jo@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:46225
    ti@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:46463
    ei@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:46396
    bl@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:84932
    Aa@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-3.js:1:63770
    n.useAssetDetails/</<@moz-extension://d43da057-d5a1-4c9f-abe7-f70fe74d7e07/ui-8.js:1:41501

Here's a screenshot as well:

![image](https://github.com/MetaMask/metamask-extension/assets/30772943/f4ea1cd1-aa56-48e1-8175-21bcd29df8a2)

### Steps to reproduce

1.

### Version

10.34.0

### Build type

None

### Browser

Firefox

### Operating system

Linux

**Comment by anaamolnar** [comment]
Hello, @georgeroman. Thanks for reporting! I will pass this on to the team.
