### ISSUE TITLE
[Bug]: User rejected the request

### ISSUE THREAD

**Issue by amilkov3** [MetaMask/metamask-extension#20446]
### Describe the bug

<img width="477" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/5270817/4a555b89-8500-44ee-bd87-0e9c6e2458f4">

this error appeared once i deployed my server against mainnet (vs sepolia). no indication of why/where this is happening in the stack trace, even after i wrapped the press connect button callback in 
```
const handleConnect = async () => {
    try {
      let accounts = await window.ethereum.request({
        method: "eth_requestAccounts",
      })
      console.log(`metamask accts ${JSON.stringify(accounts)}`)
      setWallet({ adapter: 'metamask', addr: accounts[0] })
    } catch (e) {
      console.error(`handleConnect failed ${e}`)
    }
  }
```
it never actually hits this code

ive found some other thread https://github.com/MetaMask/metamask-extension/issues/7007 which indicates it could be this 

> It's really ugly to have MetaMask throwing errors whenever a query for a non-existent ERC-721 does not exist. It would be nice to have the ability to suppress errors.

### Steps to reproduce

```
declare global {
  interface Window {
    ethereum: any;
  }
}

<a
                        onClick={handleConnect}
                        className={classNames(
                          active ? 'bg-gray-100 text-gray-900' : 'text-gray-700',
                          'flex flex-row block px-4 py-2 text-sm'
                        )}
                      >
                        <i className={"wallet-adapter-button-start-icon"}>
                          <img src={"https://upload.wikimedia.org/wikipedia/commons/3/36/MetaMask_Fox.svg"}/>
                        </i>Metamask
                      </a>

const handleConnect = async () => {
    try {
      let accounts = await window.ethereum.request({
        method: "eth_requestAccounts",
      })
      console.log(`metamask accts ${JSON.stringify(accounts)}`)
      setWallet({ adapter: 'metamask', addr: accounts[0] })
    } catch (e) {
      console.error(`handleConnect failed ${e}`)
    }
  }
```

### Version

10.34.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

its happening on all browsers. service is deployed on vercel and it mostly works when i go to a the vercel git hash domains (generated for each deploy) but never on the static domains, where once it fails once it never works again

**Comment by amilkov3** [comment]
fyi for anyone that comes across this, since its clear just browsing through these issues whoever maintains this extension has no intention or bandwidth to provide support, this problem went away when i switched from raw `window.ethereum` to `@metamask/sdk` https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/react/

**Comment by anaamolnar** [comment]
Hello, @amilkov3. Thanks so much for the report! I am so sorry; I seem to have missed the issue you created. We are doing our best to assign each issue to their respective teams. Please feel free to open a new issue if this continues to occur.  I am really sorry for the inconvenience. Thank you!

**Comment by marsidorowicz** [comment]
any news? i still get this error
