### ISSUE TITLE
Replace deprecated SiteIcon component with AvatarFavicon from the component-library

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20459]
### Description

Currently, the extension is using an outdated `SiteIcon` component, which needs to be replaced with the new `AvatarFavicon` component.

This is a large undertaking by itself and creating a single PR would be too large. Smaller PRs can be submitted against this issue to ensure easier review and gradual improvements.

### Technical Details

- Replace instances of `SiteIcon` component (`ui/components/ui/site-icon/site-icon.js`) with `AvatarFavicon` component (`ui/components/component-library/avatar-favicon/avatar-favicon.tsx`)
- Component APIs are slightly different so ensure all props have been migrated appropriately

### Acceptance Criteria

- Instances of `SiteIcon` component are completely replaced with the new `AvatarFavicon` component
- The component APIs are updated to reflect the changes in the new `SiteIcon`` component and there is no functional changes or visual regression
- Each Pull Request (PR) should include **no more than 3 files**
- The code changes should pass Jest tests, linting, and Storybook without any errors.
- The PR must include before and after screenshots of the UI to ensure there are no visual regressions.

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with running the extension locally, have knowledge of React, component props, Jest tests, linting, and Storybook, and want to contribute to improving the cohesiveness of UI in the extension

**Comment by NiteshSamuel** [comment]
@georgewrmarshall , If it is still open i would like to work on it

**Comment by georgewrmarshall** [comment]
Hey @NiteshSamuel, it is still open. Looking forward to your PR.

**Comment by npismenkov** [comment]
@georgewrmarshall Could you assign this issue on me?

**Comment by georgewrmarshall** [comment]
Hey @npismenkov, it looks like all deprecated `SiteIcon` components have been replaced! We can remove it from the codebase. Closing this issue. Thanks for your comment!
