### ISSUE TITLE
Deprecate IconWithFallback in favor of AvatarNetwork or AvatarFavicon

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20460]
### Description

To prevent further tech debt and inconsistencies `IconWithFallback` can be deprecated in favor of `AvatarNetwork` or `AvatarFavicon`

`IconWithFallback` (old): `ui/components/ui/icon-with-fallback/icon-with-fallback.component.js`
`AvatarNetwork` or `AvatarFavicon` (new): `ui/components/component-library`

Add the deprecation JSDoc format below to the deprecated code

```
/**
 * @deprecated The `<IconWithFallback />` component has been deprecated in favor of the new `<AvatarNetwork or AvatarFavicon>` component from the component-library.
 * Please update your code to use the new `<AvatarNetwork or AvatarFavicon>` component instead, which can be found at ui/components/component-library.
 * You can find documentation for the new `AvatarNetwork` or `AvatarFavicon` component in the MetaMask Storybook:
 * {@link https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-avatarnetwork--docs}
 * {@link https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-avatarfavicon--docs}
 * If you would like to help with the replacement of the old `IconWithFallback` component, please submit a pull request
 */
```

### Technical Details

- Add deprecation notice to storybook
- Add deprecation message above old component function or class

### Acceptance Criteria

- Old component has been deprecated (deprecation indicator shows up in VS Code)
- Good first issue has been created for the community to contribute to reducing tech debt and improving the UI consistency of MetaMask

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are able to run the extension locally, familiar with React, component props and proficient at searching a codebase

**Comment by subhajit20** [comment]
@georgewrmarshall  Pr is linked.
Please assign this issue to me.

**Comment by georgewrmarshall** [comment]
Closed by https://github.com/MetaMask/metamask-extension/pull/20656
