### ISSUE TITLE
[Bug]: `BigNumber.toString does not accept any parameters; base-10 is assumed`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#20475]
### Describe the bug

**Problem**:  whenever I am approving a USDT token, I can see the following error in the background console `BigNumber.toString does not accept any parameters; base-10 is assumed`.

https://github.com/MetaMask/metamask-extension/assets/54408225/6ea3bebf-e155-4dc9-883a-b49292ae1660

### Steps to reproduce

1. Go to [Etherscan USDT contract](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#writeContract)
2. Connect MetaMask
3. Change to Mainnet
4. Click Write Contract
5. Click Approve
6. Add any address an amount
7. Click Write
8. See error in the console

Notice this only happens the first time I trigger an approve, if I repeat the action the error does not appear again. For reproing again you need to disable and enable the extension and try another approve.

### Version

`10.34.3` prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
This error is still present as of today:

![Screenshot from 2024-02-09 13-21-51](https://github.com/MetaMask/metamask-extension/assets/54408225/8c9997b3-5659-4bc5-85a1-e92979ceb8ea)

**Comment by hjetpoluru** [comment]
Unable to reproduce the issue, looks like the console log message does not appears.
