### ISSUE TITLE
Deprecate TextField in favor of TextField

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20484]
### Description

To prevent further tech debt and inconsistencies `TextField` can be deprecated in favor of `TextField`

`TextField` (old): `ui/components/ui/text-field/text-field.component.js`
`TextField` (new): `ui/components/component-library/text-field/text-field.js`

Add the deprecation JSDoc format below to the deprecated code

```
/**
 * @deprecated The `<TextField />` component has been deprecated in favor of the new `<TextField>` component from the component-library.
 * Please update your code to use the new `<TextField>` component instead, which can be found at ui/components/component-library/text-field/text-field.js.
 * You can find documentation for the new `TextField` component in the MetaMask Storybook:
 * {@link https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-textfield--docs}
 * If you would like to help with the replacement of the old `TextField` component, please submit a pull request against this GitHub issue:
 * {@link https://github.com/MetaMask/metamask-extension/issues/20483}
 */
```

### Technical Details

- Add deprecation notice to storybook
- Add deprecation message above old component function or class

### Acceptance Criteria

- Old component has been deprecated (deprecation indicator shows up in VS Code)
- Good first issue has been created for the community to contribute to reducing tech debt and improving the UI consistency of MetaMask

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are able to run the extension locally, familiar with React, component props and proficient at searching a codebase

**Comment by subhajit20** [comment]
@georgewrmarshall  Pr is linked.
Can you assign it to me?

**Comment by georgewrmarshall** [comment]
Assigned thanks @subhajit20

**Comment by georgewrmarshall** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/20640
