### ISSUE TITLE
Deprecate Chip in favor of Tag

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20488]
### Description

To prevent further tech debt and inconsistencies `Chip` can be deprecated in favor of `Tag`

`Chip` (old): `ui/components/ui/chip/chip.js`
`Tag` (new): `ui/components/component-library/tag/tag.tsx`

Add the deprecation JSDoc format below to the deprecated code

```
/**
 * @deprecated The `<Chip />` component has been deprecated in favor of the new `<Tag>` component from the component-library.
 * Please update your code to use the new `<Tag>` component instead, which can be found at ui/components/component-library/tag/tag.tsx.
 * You can find documentation for the new `Tag` component in the MetaMask Storybook:
 * {@link https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-tag--docs}
 * If you would like to help with the replacement of the old `Chip` component, please submit a pull request against this GitHub issue:
 * {@link https://github.com/MetaMask/metamask-extension/issues/20487}
 */
```

### Technical Details

- Add deprecation notice to storybook
- Add deprecation message above old component function or class
- Create good first issue to replace all old components with new [Replace old Chip component with new Tag component](https://github.com/georgewrmarshall/issue-templates/blob/main/REPLACE.md)

### Acceptance Criteria

- Old component has been deprecated (deprecation indicator shows up in VS Code)
- Good first issue has been created for the community to contribute to reducing tech debt and improving the UI consistency of MetaMask

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are able to run the extension locally, familiar with React, component props and proficient at searching a codebase

**Comment by jase-b** [comment]
Requesting assignment.  PR is ready. 👍
