### ISSUE TITLE
Keystone logo update

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#20481]
### Describe the bug

Asset image within the SVG file app/images/qrcode-wallet-demo.svg needs to be updated to reflect the recent change.
![CurrentKeystoneLogo](https://github.com/MetaMask/metamask-extension/assets/32695229/265b17fb-33b7-43f3-916d-47ed68ad7fa5)

### Steps to reproduce

1. Tap accounts drop-down
2. select `Hardware Wallet`
3. Select `QR-based`

Logo that needs replaced will appear above the `Continue` CTA

### Version

10.34.4

### Build type

None

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS, Linux

### Hardware wallet

Keystone

### Additional context
Discussion: [Initial request ](https://consensys.slack.com/archives/C029LTNQ56C/p1691738908138809)

Updated assets 
[Keystone Logo.zip](https://github.com/MetaMask/metamask-extension/files/12361733/Keystone.Logo.zip)

**Comment by raulmono** [comment]
Here, you can find the updated image. It's the same size as the original 297x101 px in .svg format to avoid issues.

Figma: https://www.figma.com/file/QH1o9xljFRfbupXDLvaFNP/Keystone-update-logo?type=design&node-id=5209%3A3092&mode=design&t=Cyy47XK0ZQcyYUPT-1

Image:
![qrcode-wallet-demo](https://github.com/MetaMask/metamask-extension/assets/11038018/71a959fe-eda9-4e03-ba7e-5ddbcc985021)
