### ISSUE TITLE
Replace deprecated mixins `@include H1` - `@include H9` in SCSS with Text component

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20496]
### Description

Currently, the extension is using outdated mixins `@include H1` - `@include H9`. This CSS should be removed and the JSX associated with these styles replaced with the `Text` component. This will reduce the amount of CSS in the extension and improve the cohesiveness of the UI.

This is a massive undertaking by itself and creating a single PR would be too large. Smaller PRs can be submitted against this issue to ensure easier review and gradual improvements.

### Technical Details

- Remove instances of the deprecated mixins from the CSS and replace the JSX element with `Text` component (`ui/components/component-library/text/text.tsx`) or [appropriate component from the component-library](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-introduction--docs).
- There will also be CSS that can be removed in favor of the style utility props that are available on the `Text` component. For example, `display: flex` can be replaced with `display={Display.Flex}` prop on the `Text` component. [Check out all the available style utility props in the Text docs in storybook](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-text--docs).
- The `Text` component has a `variant` prop that can be used to set the font size and weight. Use the `TextVariant` enum (`ui/helpers/constants/design-system.ts`) to set the appropriate variant.
- There are 9 deprecated mixins that need to be replaced. The following is a mapping of the mixin to the component that should be used to replace it:

`@include H1` => `<Text variant={TextVariant.displayMd}>`
`@include H2` => `<Text variant={TextVariant.displayLg}>`
`@include H3` => `<Text variant={TextVariant.headingMd}>`
`@include H4` => `<Text variant={TextVariant.headingSm}>`
`@include H5` => `<Text variant={TextVariant.bodyMd}>`
`@include H6` => `<Text variant={TextVariant.bodyMd}>`
`@include H7` => `<Text variant={TextVariant.bodySm}>`
`@include H8` => `<Text variant={TextVariant.bodyXs}>`
`@include H9` => `<Text variant={TextVariant.bodyXs}>`

### Acceptance Criteria

- Instances of deprecated mixins `@include H1` - `@include H9` are completely replaced with the `Text` component or appropriate component from the component-library
- Each Pull Request (PR) should include **no more than 3 files**
- The code changes should pass Jest tests, e2e tests, linting, and Storybook without any errors.
- The PR must include before and after screenshots of the UI to ensure there are no visual regressions.

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are familiar with running the extension locally, have knowledge of React, component props, Jest tests, linting, and Storybook, and want to contribute to improving the cohesiveness of UI in the extension

**Comment by subhajit20** [comment]
https://github.com/MetaMask/metamask-extension/blob/982a1b2c5133cb73068cd30634290b56203e5601/ui/pages/unlock-page/index.scss#L37-L38

Do I have to put `<Text variant={TextVariant.bodyXs}>` component in replace with the above `@include H2` ?
Is it what this issue is all about ?

**Comment by subhajit20** [comment]
@georgewrmarshall  in every single page that has `h1-h9` tags will be replaced with this `<Text />` component. right?

**Comment by subhajit20** [comment]
@georgewrmarshall  hey this is being shown while running yarn start.
in which port application up and running ?
<img width="1280" alt="Screenshot 2023-08-31 at 12 19 06 PM" src="https://github.com/MetaMask/metamask-extension/assets/99127578/1fe45dac-52c2-4792-abf2-e3f3c0f706cc">

**Comment by subhajit20** [comment]
@georgewrmarshall Hey can you help me out with this test issue? I have replaced the `H1` tag `Text` component on the below file.

`FAIL ui/pages/unlock-page/unlock-page.test.js (8.608 s)
  ● Unlock Page › should match snapshot

    expect(received).toMatchSnapshot()

    Snapshot name: `Unlock Page should match snapshot 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -14,11 +14,11 @@
              >
                <svg />
              </div>
            </div>
            <h1
    -         class="unlock-page__title"
    +         class="mm-box mm-text mm-text--display-md mm-box--margin-top-1 mm-box--color-text-alternative"
            >
              Welcome back!
            </h1>
            <div>
              The decentralized web awaits

      35 |     const { container } = renderWithProvider(<UnlockPage />, mockStore);
      36 |
    > 37 |     expect(container).toMatchSnapshot();
         |                       ^
      38 |   });

**Comment by 0xClint** [comment]
Hey @georgewrmarshall ,
I just open  a PR by replacing deprecated minxins H1,H2,..  of few components. Please check whether they are right or not so that to commit more changes.

 PR #20700

**Comment by subhajit20** [comment]
@georgewrmarshall Hey, made a pr.
Can you please check and let me know further modifications.

**Comment by LeonxLJX** [comment]
I'd like to take this one — I'll follow up with a PR. (claiming via @LeonxLJX)

**Comment by LeonxLJX** [comment]
Hi! I'd like to replace deprecated SCSS mixins H1-H9 with tokens. Plan: audit, replace, run lint/tests. May I be assigned?
