### ISSUE TITLE
Deprecate Menu in favor of Popover

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20499]
### Description

To prevent further tech debt and inconsistencies `Menu` can be deprecated in favor of `Popover`

`Menu` (old): `ui/components/ui/menu/menu.js`
`Popover` (new): `ui/components/component-library/popover/popover.tsx`

Add the deprecation JSDoc format below to the deprecated code

```
/**
 * @deprecated The `<Menu />` component has been deprecated in favor of the new `<Popover>` component from the component-library.
 * Please update your code to use the new `<Popover>` component instead, which can be found at ui/components/component-library/popover/popover.tsx.
 * You can find documentation for the new `Popover` component in the MetaMask Storybook:
 * {@link https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-popover--docs}
 * If you would like to help with the replacement of the old `Menu` component, please submit a pull request against this GitHub issue:
 * {@link https://github.com/MetaMask/metamask-extension/issues/20498}
 */
```

### Technical Details

- Add deprecation notice to storybook
- Add deprecation message above old component function or class
- Create good first issue to replace all old components with new [Replace old Menu component with new Popover component](https://github.com/georgewrmarshall/issue-templates/blob/main/REPLACE.md)

### Acceptance Criteria

- Old component has been deprecated (deprecation indicator shows up in VS Code)
- Good first issue has been created for the community to contribute to reducing tech debt and improving the UI consistency of MetaMask

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are able to run the extension locally, familiar with React, component props and proficient at searching a codebase

**Comment by subhajit20** [comment]
@georgewrmarshall  I didn't understand this following statement ,
 `Old component has been deprecated (deprecation indicator shows up in VS Code)`,
All I have to do only add that doc to deprecated code right or anything more than this ?

**Comment by subhajit20** [comment]
@georgewrmarshall  Pr has been ready.
Can you please assign it me 🙏?

**Comment by georgewrmarshall** [comment]
Assigned. Thanks @subhajit20!

**Comment by georgewrmarshall** [comment]
Closed by https://github.com/MetaMask/metamask-extension/pull/20622
