### ISSUE TITLE
Drop `@metamask/eth-keyring-controller`

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/metamask-extension#20508]
After migrating all direct interactions with `@metamask/eth-keyring-controller` package with `@metamask/keyring-controller`, we should be able to remove the use of `EthKeyringController` completely, and also remove the patch from `@metamask/keyring-controller`.

- [x] https://github.com/MetaMask/core/issues/1595
- [x] #20510
  - [ ] `MMIController`
  - [ ] `DetectTokensController`
  - [ ] `DecryptMessageController`
  - [ ] `SignatureController`
- [x] #20511
- [x] #20512

**Comment by xinnanyemm** [comment]
Hi @desi I noticed this ticket is in `Epic`. I assume we want to put it back to `Product Backlog`? Thanks.

**Comment by mcmire** [comment]
I'm checking back on this ticket and it looks like core#1595 was completed, so I marked it as such in the description above. Does this mean that we can now close this ticket?

**Comment by mikesposito** [comment]
@mcmire yes, this can also be closed
