### ISSUE TITLE
[Bug]: Import NFT focuses on Token ID input instead of Address input when opened

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#20516]
### Describe the bug

https://github.com/MetaMask/metamask-extension/assets/53189696/0f4f2135-cf08-4ed0-adc4-d1076b23d8bb

### Steps to reproduce

1. Log in to the extension
2. Switch to the NFT tab
3. Click Import NFT

Actual result:
The cursor is focused on the Token ID input

Expected result:
The cursor is focused on the Address input

### Version

10.35

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
Fixed here: https://github.com/MetaMask/metamask-extension/pull/20225
