### ISSUE TITLE
MetaMask silently swallows the gas estimation errors when sending a Token

### ISSUE THREAD

**Issue by tenbits** [MetaMask/metamask-extension#20515]
### Describe the bug

Hello Team,

when sending a Token and gas estimation fails due to contract reverts MetaMask doesn't notify the user as it does when submitting a transaction via the dApp. Not sure if this is the intended behavior to silently swallow the error in [send.js#L1551](https://github.com/MetaMask/metamask-extension/blob/861c30de299cfe5d3c43c043a588ace37e1d0a6a/ui/ducks/send/send.js#L1551). As in comparison to [confirm-transaction-base.component.js#L454](https://github.com/MetaMask/metamask-extension/blob/861c30de299cfe5d3c43c043a588ace37e1d0a6a/ui/pages/confirm-transaction-base/confirm-transaction-base.component.js#L454) 

### Steps to reproduce

1. Add a test token to MetaMask on goerli network: [0x27F02912D6be3520feF4D1b657f55188B5440788](https://goerli.etherscan.io/address/0x27F02912D6be3520feF4D1b657f55188B5440788)

2. The test token will always fail on transfer
3. Send the token to any address and any amount
4. The gas estimation fails due to the test `revert` in the contract 

### Error messages or log output

```shell
MetaMask doesn't notify the user about the failed estimation and will set the default GasLimit.
```

### Version

10.34.3

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Additional context

The conversation source at StackExchange: https://ethereum.stackexchange.com/questions/153378/metamask-doesnt-catch-erc20-reverts/153522

**Comment by anaamolnar** [comment]
Hello, @tenbits. Thanks for the report! I will pass this on to the team.
