### ISSUE TITLE
[Bug]: Not import proxy token contract

### ISSUE THREAD

**Issue by ruymaster** [MetaMask/metamask-extension#20522]
### Describe the bug

Some contracts implements ERC20 and ERC1155 both with EIP2535 diamond protocol. In that case, we want to import the ERC20 token.
https://polygonscan.com/token/0x127e47aba094a9a87d084a3a93732909ff031419

### Steps to reproduce

- add polygon network
- import token `0x127e47aba094a9a87d084a3a93732909ff031419`
- then shows error `This token is an NFT. Add on the Import NFT page`

### Error messages or log output

```shell
This token is an NFT. Add on the Import NFT page
```

### Version

10.34.3

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS

**Comment by Super-Genius** [comment]
Just a note on this, the code shouldn't be checking for only 1 contract type when adding tokens.  It should check for the type of token being added, i.e. ERC20, NFT and then check Interfaces available
```
      function checkInterfaceType(interfaceType: string) : bool {
      switch (interfaceType) {
        case "ERC1155":
          const IERC1155Interface = IERC1155__factory.createInterface();
          // interface ID does not include base contract(s) functions.
          const IERC1155InterfaceID = getInterfaceID(IERC1155Interface);
          if !(await contract.supportsInterface(IERC1155Interface._hex))
          { 
            console.log("Doesn't support IERC1155Interface");
            // in case interface isn't there, you could double check GetNFTInfo()
            try {
              GetERC1155NFTInfo();
            } catch()
             return false;
           }
       }
       return true;
       case 'ERC20':
            try {
              GetTokenInfo();
            } catch()
             return false;
           }
           return true;
        case "ERC721":
          const IERC721Interface = IERC721__factory.createInterface();
          // interface ID does not include base contract(s) functions.
          const IERC721InterfaceID = getInterfaceID(IERC721Interface);
          if !(await contract.supportsInterface(IERC721Interface._hex))
          { 
            console.log("Doesn't support IERC721Interface");
            // in case interface isn't there, you could double check GetNFTInfo()
            try {
              GetERC721NFTInfo();
            } catch()
             return false;
           }
         return true;
       }       
    }
    
    
    ```
    
    Also, using the GetERC1155NFTInfo() is not a good practice as with ERC1155 there can be multiple ID's for the TokenID.

**Comment by anaamolnar** [comment]
Hello, @ruymaster. Thanks for reporting! I will ask the team to take a look.

**Comment by Super-Genius** [comment]
There could be a quick fix to change the error to just a warning and let the user add the ERC-20 token anyway!!

**Comment by Super-Genius** [comment]
There is a simple solution for this, just a pop-up dialog box warning to let the user add the token to ERC-20 anyway, instead of just blocking them from adding it.
