### ISSUE TITLE
Render method metadata 

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2055]
TIL https://solidity.readthedocs.io/en/develop/miscellaneous.html#contract-metadata

Solidity has a method for encoding a link to a full contract metadata file that can be published over Swarm or IPFS. We should be using this on-chain method to render contract methods on the transaction confirmation screen, and then we can encourage devs to do it much more!

Thanks to @axic

**Comment by danfinlay** [comment]
I just learned about parity's 4byte registry, and whipped up [a small module for using it](https://github.com/danfinlay/eth-method-registry), so we could at least immediately start rendering extra data when it's available:

- Method names
- Arguments as their correct data types

**Comment by danfinlay** [comment]
Another good resource for the swarm hash data:

https://www.reddit.com/r/ethereum/comments/5d5lyd/first_contract_to_contain_swarm_hash_to_its/?st=J9FEY2L7&sh=3476b7b9

**Comment by bdresser** [comment]
this is a feature in the new UI! closing~
