### ISSUE TITLE
Warn users on their first interaction with an entity

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#20564]
**This is a security enhancement.**

Extending https://github.com/MetaMask/metamask-extension/issues/17987, we want to warn users about interacting with unknown entities for the first time (eg., EOA addresses and contracts). 

It is a handy pattern to encourage users to increase items in their local address book via petnames. 

For imported accounts, we can include a TX history scanning.  

Previously, we had a banner suggesting users include the "new" address in the address book for convenience. Still, it resulted in a 1. very annoying banner with multiple exposures and 2. non-engaging UI. We could research why it has not worked and explore engaging UI/UX to encourage (or reward?) users to save known entities.

**Comment by blurpesec** [comment]
> For imported accounts, we can include a TX history scanning.

This should hold true for both accounts imported during initial extension installation/setup AND for imported private key / mnemonic / hardware wallet accounts

**Comment by flyingbanannas** [comment]
Any progress here? This is super important, as mentioned here https://github.com/MetaMask/metamask-extension/issues/17987#issuecomment-2025130359 I lost 25k USDT sending funds to a poisoned address that appeared in my optimistic etherscan adderss page. This is super important!

**Comment by bschorchit** [comment]
Closing this in favor of: https://github.com/MetaMask/MetaMask-planning/issues/3040
