### ISSUE TITLE
[Bug]: When selected Advanced gas setting are getting carried over as default from L1 to L2

### ISSUE THREAD

**Issue by LoveKosmos** [MetaMask/metamask-extension#20573]
### Describe the bug

When Advanced settings are used for calculating gas fees on Ethereum Mainnet, they are saved as default and to be applied across all networks despite actual gas fees that are currently on the network (in this example on Linea, other networks could be affected as well).

This should be considered as a severe MM issue:
1. applying, by default, the same value to other networks can lead user to lose money by over paying for the fees
2. or to get their transactions stuck by underestimating the fees on the network

### Steps to reproduce

1. In MM; use Ethereum mainnet.
2. Start to create a tx, when setting the tx fees, go to "advanced" and check the box "save these new values as default"
3. Exit the transaction
4. Switch to Linea testnet network
5. Send a tx by just confirming everything ( no changes in the gas fees )
6. The value you will see in the explorer should be the "advanced ones" from Ethereum mainnet, and not the one that should be adjusted to the in this case Linea testnet.

<img width="362" alt="Screenshot 2023-08-23 at 1 59 19 PM" src="https://github.com/MetaMask/metamask-extension/assets/12563620/a60dfd92-c47e-4752-83f5-fe95fcbcec4a">
<img width="369" alt="Screenshot 2023-08-23 at 1 59 07 PM" src="https://github.com/MetaMask/metamask-extension/assets/12563620/95ea6713-b900-4e20-9e31-3c3f7989c149">
<img width="358" alt="Screenshot 2023-08-23 at 1 58 55 PM" src="https://github.com/MetaMask/metamask-extension/assets/12563620/b110ff08-69ed-4293-a23d-1f22b380477c">
<img width="358" alt="Screenshot 2023-08-23 at 1 58 46 PM" src="https://github.com/MetaMask/metamask-extension/assets/12563620/4ef19c03-f518-4a81-b450-ae42894aceda">
<img width="357" alt="Screenshot 2023-08-23 at 1 58 14 PM" src="https://github.com/MetaMask/metamask-extension/assets/12563620/6c07d11f-15c6-4e54-b3e2-5c073bf4d426">
<img width="360" alt="Screenshot 2023-08-23 at 1 57 45 PM" src="https://github.com/MetaMask/metamask-extension/assets/12563620/c8d4af21-e548-42a5-8d79-e3c25e1d6cfd">

[https://explorer.goerli.linea.build/tx/0xff741faa3d4f6a2e8299fa4e3f73290599ee28b0ab36ba2f683dd906e2e36775](url)

<img width="869" alt="Screenshot 2023-08-23 at 2 09 50 PM" src="https://github.com/MetaMask/metamask-extension/assets/12563620/98eb53a7-e6dc-4d7e-96af-f84278e1a7c1">

Nevertheless, this tx was processed on Linea testnet but in fact, would have been stuck on Linea Mainnet (with Max Priority Fee per Gas 0.1 Gwei) as the fas fees at the time of the transaction were the following: 
<img width="208" alt="Screenshot 2023-08-23 at 2 03 43 PM" src="https://github.com/MetaMask/metamask-extension/assets/12563620/ac28c9fa-ac9c-4749-97c1-d502f91a65ec">

The same behavior can be reproduced on any other network when switching from Ethereum Mainnet, selecting advanced gas fees, to Polygon, Goerli..

### Version

10.34.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

The original discovery is outlined here:
[https://github.com/Consensys/zkevm-monorepo/issues/1214#issuecomment-1690185983](url)

**Comment by Gudahtt** [comment]
Related to #13800
