### ISSUE TITLE
[Bug]: Adding a Network displays a popup asking if I want to switching to it, but switch is already performed

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#20581]
### Describe the bug

**Problem**: whenever I add a new network, I am automatically switched to it. The problem is that a popover appears asking if I want to switch to that network (which I am already switch) so Accepting or Dismissing has no effect

https://github.com/MetaMask/metamask-extension/assets/54408225/7fec6303-449f-4564-be60-044a5b9b3d63

### Steps to reproduce

1. Go to settings
2. Add a network
3. See popup asking if you want to switch
4. See on the background you have already been switched
5. Dismiss the action
6. See how you have already been switched

### Version

10.34.5 prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by benjisclowder** [comment]
I have followed this behaviorback  to 10.30.1 Somewhere between that and 10.25.0 the "switch/dismiss" buttons were added, but I couldn't find the exact version where this was added or the respective PR.

**Comment by gauthierpetetin** [comment]
Closing this issue as fixed by https://github.com/MetaMask/metamask-extension/pull/22832
