### ISSUE TITLE
[Bug]: Display NFT media button is cut off / miss-aligned

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#20583]
### Describe the bug

**Problem**: on Security and Privacy Settings, we can see how the button for Display NFT Media is cut off if the screen is small and miss-aligned in comparision with other buttons

![Screenshot from 2023-08-24 10-12-53](https://github.com/MetaMask/metamask-extension/assets/54408225/f63968c9-3bf9-48ff-8181-6b4a3013d725)

### Steps to reproduce

1. Open Security and Privacy Settings
2. Scroll down to Display NFT Media
3. Make screen smaller
4. See how button is cut and miss-aligned

### Version

in current develop (not in 11.0.0 but will be in the next release)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bergeron** [comment]
Seems to have been fixed
