### ISSUE TITLE
[Bug]: Tap and hold to reveal private key is not presented after tapping back arrow and then tapping show private key a second time

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#20598]
### Describe the bug

After PR 20109, there is some inconsistent behavior with the tap and hold to reveal button after tapping the back arrow on the private key pop-up. If I use back, and then tap "Show private key" a second time, the tap and hold to reveal does not appear and instead presents the private key value. For SRP reveal, there is no back arrow on extension. On iOS mobile, when tapping the back arrow from "Show private key" returns the user to wallet view instead of account details.

### Steps to reproduce

1. Setup a wallet and be at wallet view
2. Select accounts drop-down
3. Select kebab menu next to an HD account
4. Select "Account details"
5. Select "Show private key"
6. Provide correct password and select "confirm"
7. Click and hold to reveal private key
8. Select the back arrow and note that you are returned to "Account details"
9. Select "Show private key"
10. Note that there is no prompt for the password or to tap and hold, the private key is simply presented
11. This can be observed on both Chrome and Firefox and is not consistent with the mobile client behavior.

### Version

10.34.5

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

Video of Firefox: https://recordit.co/G1tIIcPoDx
Video of iOS mobile client: https://recordit.co/MDnNHXm80O

**Comment by dawnseeker8** [comment]
I have reviewed the PR, currently the PR is more than 6 months old and the code haven't been updated for a while which PR has some conflict with latest `Dev (main` branch currently. 

@AlexJupiter what should we do with this PR?  should i modify the branch code to rebase to latest and then apply the changes as feature enhancement?

**Comment by HowardBraham** [comment]
The PR #20597 is just a placeholder, and only has one small meaningless comment change

**Comment by dawnseeker8** [comment]
Just to test this in bug in Extensions and try the same in mobile version, confirm that extensions will not ask for password prompt again in above step 9, but mobile will ask for password prompt every time you click `show private key`.

For better security, extension should follow  mobile behaviour to ask user password prompt every time user click `show private key`.

I also test MM extension further,  the `back` button in `reveal private key` screen will go back to `account detail` screen like this <img width="348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEV4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d93051353dd0f10feab840a48b11246e93df52f/Screenshot%202024-02-06%20at%2019.53.12.png" alt="Screenshot 2024-02-06 at 19.53.12.png" />

but in mobile, there is not `account detail` screen, `back` button in `reveal private key` screen will go back to account drop down list in main screen directly.

**Comment by dawnseeker8** [comment]
PR has been created for this issue https://github.com/MetaMask/metamask-extension/pull/22867

**Comment by dawnseeker8** [comment]
PR has been successfully merged.

**Comment by dawnseeker8** [comment]
PR has been successfully merged.
