### ISSUE TITLE
Implement What's New update for changing Advanced Gas Fee Setting

### ISSUE THREAD

**Issue by brad-decker** [MetaMask/metamask-extension#20628]
In #20576 we split the advanced gas fee setting by network. We erased the previous setting to prevent it from being applied erroneously across all networks, which could have an impact on the amount of gas a user is paying or, conversely, cause transactions to become stuck. Both scenarios are listed here for information if they need to be considered for copy:

## Example A: Overpaying
User sets their preferred settings for Ethereum mainnet. They then switch to Optimism and issue a transaction, and those default settings are applied to their transaction on Optimism. This could result in overpaying because gas fees are typically lower on Optimism than on mainnet. 

## Example B: Stuck transactions
User sets their preferred settings for Optimism. They then switch from Optimism to mainnet and attempt to make a transaction. The preferred settings are applied to this transaction and because they were set on a network with typically lower gas fees the transaction will take a very long time to be included into a block, which has the potential to indefinitely delay the transaction. 

## How this is resolved
Going forward your preferences for advanced gas fee settings are remembered by network, rather than globally. This means you may choose to apply an advanced gas fee on a network by network basis and your settings will not be applied on other networks.

**Comment by Gudahtt** [comment]
To add my perspective on the copy we need here: The information we strictly need to communicate in What's New is that we have erased users "default gas fee" setting. If they are relying on this for future confirmations, they need to set it again.

Conveying the _purpose_ of this change makes sense too (to justify this change), but we could describe the purpose here quite broadly. For example, we could explain that "The default gas setting is now stored per-chain, which helps prevent gas overpayment and stuck transactions", without explaining how it does those things.

**Comment by coreyjanssen** [comment]
How about this for the content? Lmk if it needs more work!

**Advanced gas fees by network**

Advanced gas fee settings are now remembered based on the network you're using. This means you can set specific advanced gas fees for each network and avoid overpaying for gas or stuck transactions.

**Comment by brad-decker** [comment]
Implemented in #20632
