### ISSUE TITLE
Metamask account Wipe out

### ISSUE THREAD

**Issue by Mowhaling** [MetaMask/metamask-extension#2063]
Dan, 
I have an issue with my Metamask and need your help to restore a few dozen ETH that are at stake.

 I am one of the users who is unable to reload their account on Metamask after restarting the browser about a week ago and being asked to CREATE a new DEN. I input what I thought was my seed and it loads different address accounts. The +  account menu prompts me to load several different available accounts although none are mine I've sifted through like 30 accounts in vain.  So each time I restart the browser/PC, It challenges me to create a NEW account. I am using Firefox and the Metamask instruction guides to locate the private key dont seem exist. Can you help in restoring my account? I still have my Public address that displays the correct ETH and also my Metamask access password. 

Thanks 
Mo

**Comment by flyswatter** [comment]
Hi there, a few things:

I'm not the only member of the team! Please don't assume I'm going to personally help you every time there's an issue. For personal issues like this, we have a new support system, which is a great way to make sure you get the support you need. https://support.metamask.io

What browser are you using? Is this Firefox?

Were you using EtherDelta before this issue? Many people who create accounts with EtherDelta misunderstand that they created a MetaMask account.
https://support.metamask.io/kb/article/21-etherdelta-account-management

If you have your seed phrase backed up, try uninstalling & reinstalling MetaMask, and restoring from your seed phrase.

If it still creates a DEN, I might ask you to look at the background logs during this process:
https://github.com/MetaMask/faq/blob/master/LOGS.md

Please open an issue on our support system.

**Comment by Mowhaling** [comment]
OK,
Point noted on future issues.
So this is what I have-
- No Etherdelta account. Been there but never setup an etherdelta account. 
- Then this is definitely a metamask issue on Firefox 32 bit WIN platform.
- Before I uninstall how can I backup the existing logs I now have just in case? 
- I managed to get the state logs that I will send privately, but the other log-types from help are chrome specific.
Thanks for your  attention. Looking fwd to your diagnosis.
Mo

**Comment by flyswatter** [comment]
Before you uninstall, what you really want to back up is your seed phrase, not your logs, but just in case:
- [exporting seed phrase](https://support.metamask.io/kb/article/23-exporting-your-seed-phrase)
- [backing up vault data](https://support.metamask.io/kb/article/22-how-to-copy-your-vault-data)
- [copying logs](https://support.metamask.io/kb/article/15-copying-state-logs).

I'd encourage you to send those logs to use on support.metamask.io so we might see what happened on Firefox for your extension to get reset.

**Comment by danfinlay** [comment]
Closing from inactivity, let us know if there's anything else we can do!
