### ISSUE TITLE
[Bug]: Unable to edit spending cap from portfolio requests

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#20649]
### Describe the bug

When you receive a erc-20 allowance request from https://portfolio.metamask.io/ and you try to edit it to a custom value, the value does not get updated in the confirmation screen or in the transaction data.

### Steps to reproduce

1. Go to https://portfolio.metamask.io/swap
2. Start a swap from a erc20 token that you haven't given allowance for yet
3. Click 'approve' in the portfolio UI
4. Click 'edit' in the spending cap section of the MM popup
5. Enter a custom number and click on next to see how the value remains unchanged 

### Version

10.34

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Additional context

https://github.com/MetaMask/metamask-extension/assets/34968356/c435f289-12a4-4be5-8232-56c99fd7ae3a

**Comment by digiwand** [comment]
Sharing the token allowance flow in this use-case in case others find it useful. It also contains some out-of-scope findings that I found interesting.

**Research:**
- ConfirmTransaction gets the unapproved transaction from the metamask state as `transaction`
- ConfirmTransaction passes `transaction` to ConfirmTokenTransactionSwitch
- ConfirmTokenTransactionSwitch passes `tokenAmount` to ConfirmApprove
    - `tokenAmount` is returned from `useAssetDetails` hook
    - `useAssetDetails` gets `tokenAmount` from `getAssetDetails`
    - `getAssetDetails`
        - creates `tokenData` const (TransactionDescription type)
          ```js
          const tokenData = parseStandardTokenTransactionData(transactionData);
            ```
            - `transactionData` is essentially metamaskState.transactions[targetTransactionId].txParams.data
                - example value in bug-case: `0x095ea7b3000000000000000000000000881d41337659c251811cec9c364ef91dc08d300cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`
                - `0x095ea7b3` resolves to `approve(address,uint256)` ([4byte directory](https://www.4byte.directory/signatures/?bytes4_signature=0x095ea7b3))
                    - accepts `spender` and `value` as args
            - parseStandardTokenTransactionData method parses `transactionData` using @metamask/metamask-eth-abis erc20Interface#parseTransaction
            - erc20Interface#parseTransaction returns a TransactionDescription type object
                - `args` computes to an array with `spender` and `value`. This value is set to a BigNumber with the value `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`
                - `value` set to BigNumber(`0`) as `tx.value` in the following code is null
              ```js
              Interface.prototype.parseTransaction = function (tx) {
                    var fragment = this.getFunction(tx.data.substring(0, 10).toLowerCase());
                    if (!fragment) {
                        return null;
                    }
                    
                    return new TransactionDescription({
                        args: this._abiCoder.decode(fragment.inputs, "0x" + tx.data.substring(10)),
                        functionFragment: fragment,
                        name: fragment.name,
                        signature: fragment.format(),
                        sighash: this.getSighash(fragment),
                        value: bignumber_1.BigNumber.from(tx.value || "0"),
                    });
                };
                ```
        - creates `tokenValue` const
            ```js
            const tokenValue = getTokenValueParam(tokenData);
            ```
            - `shared/lib/metamask-controller-utils.js`:
                ```js
                export function getTokenValueParam(tokenData = {}) {
                    return tokenData?.args?._value?.toString();
                }
                ```
                - this is interesting...
                  ```
                  > tokenData.args[1].toString()
                  // result: '115792089237316195423570985008687907853269984665640564039457584007913129639935'
                  > tokenData?.args?._value?.toString()
                  // result: '115792089237316195423570985008687907853269984665640564039457584007913129639935'
                  > tokenData.value.toString()
                  // result: '0'

                    ```
                - `tokenData.args[1]` and `tokenData.value` are BigNumber types
                - `_value` is an internal value
                    - In JavaScript, prefixing names with underscore is used to denote private variables and functions
                    - These are not meant to be accessed outside of its block. e.g. If we copy an object using the Chrome Command Line API `copy()` , it will exclude variables prefixed with `_`
                    - To access the BigNumber values, we should use the [BigNumber conversion methods](https://docs.ethers.org/v5/api/utils/bignumber/#BigNumber--BigNumber--methods--conversion)
- ConfirmApprove passes `tokenAmount` as `dappProposedTokenAmount` to TokenAllowance
- TokenAllowance
  - uses 3 variables to represent the token amount in different forms
    - `dappProposedTokenAmount` is the initial `tokenAmount` passed in from ConfirmApprove 
    - `customSpendingCap`
       - initially set as `dappProposedTokenAmount`
       - may be updated through CustomSpendingCap (not accessed in through portfolio) 
    - `customPermissionAmount` = `replaceCommaToDot(customSpendingCap).toString()`

**Suggested Improvements found during investigation:**
1. `getTokenValueParam` and `getTokenIdParam` (PR created https://github.com/MetaMask/metamask-extension/issues/20789)
     - move methods into the same file
     - use BigNumber conversion methods instead of accessing internal/private JS props
     - note: `getTokenValueParam` has been used to retrieve the token id. See `const transactionDataTokenId` in  `ui/hooks/useTransactionDisplayData.js`
2. `customPermissionAmount` may be set as a string or a number type (PR created https://github.com/MetaMask/metamask-extension/issues/20790)
3. Fix console errors (PR created https://github.com/MetaMask/metamask-extension/issues/20791)
     - incorrect object key param formats
     - unexpected false boolean param

**Comment by digiwand** [comment]
Sharing the token allowance flow in this use-case in case others find it useful. It includes some out-of-scope findings that I found interesting. This information should not be needed to fix the Portfolio Dapp Bug.

**Research:**
- ConfirmTransaction gets the unapproved transaction from the metamask state as `transaction`
- ConfirmTransaction passes `transaction` to ConfirmTokenTransactionSwitch
- ConfirmTokenTransactionSwitch passes `tokenAmount` to ConfirmApprove
    - `tokenAmount` is returned from `useAssetDetails` hook
    - `useAssetDetails` gets `tokenAmount` from `getAssetDetails`
    - `getAssetDetails`
        - creates `tokenData` const (TransactionDescription type)
          ```js
          const tokenData = parseStandardTokenTransactionData(transactionData);
            ```
            - `transactionData` is essentially metamaskState.transactions[targetTransactionId].txParams.data
                - example value in bug-case: `0x095ea7b3000000000000000000000000881d41337659c251811cec9c364ef91dc08d300cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`
                - `0x095ea7b3` resolves to `approve(address,uint256)` ([4byte directory](https://www.4byte.directory/signatures/?bytes4_signature=0x095ea7b3))
                    - accepts `spender` and `value` as args
            - parseStandardTokenTransactionData method parses `transactionData` using @metamask/metamask-eth-abis erc20Interface#parseTransaction
            - erc20Interface#parseTransaction returns a TransactionDescription type object
                - `args` computes to an array with `spender` and `value`. This value is set to a BigNumber with the value `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`
                - `value` set to BigNumber(`0`) as `tx.value` in the following code is null
              ```js
              Interface.prototype.parseTransaction = function (tx) {
                    var fragment = this.getFunction(tx.data.substring(0, 10).toLowerCase());
                    if (!fragment) {
                        return null;
                    }
                    
                    return new TransactionDescription({
                        args: this._abiCoder.decode(fragment.inputs, "0x" + tx.data.substring(10)),
                        functionFragment: fragment,
                        name: fragment.name,
                        signature: fragment.format(),
                        sighash: this.getSighash(fragment),
                        value: bignumber_1.BigNumber.from(tx.value || "0"),
                    });
                };
                ```
        - creates `tokenValue` const
            ```js
            const tokenValue = getTokenValueParam(tokenData);
            ```
            - `shared/lib/metamask-controller-utils.js`:
                ```js
                export function getTokenValueParam(tokenData = {}) {
                    return tokenData?.args?._value?.toString();
                }
                ```
                - this is interesting...
                  ```
                  > tokenData.args[1].toString()
                  // result: '115792089237316195423570985008687907853269984665640564039457584007913129639935'
                  > tokenData?.args?._value?.toString()
                  // result: '115792089237316195423570985008687907853269984665640564039457584007913129639935'
                  > tokenData.value.toString()
                  // result: '0'

                    ```
                - `tokenData.args[1]` and `tokenData.value` are BigNumber types
                - `_value` is an internal value
                    - In JavaScript, prefixing names with underscore is used to denote private variables and functions
                    - These are not meant to be accessed outside of its block. e.g. If we copy an object using the Chrome Command Line API `copy()` , it will exclude variables prefixed with `_`
                    - To access the BigNumber values, we should use the [BigNumber conversion methods](https://docs.ethers.org/v5/api/utils/bignumber/#BigNumber--BigNumber--methods--conversion)
- ConfirmApprove passes `tokenAmount` as `dappProposedTokenAmount` to TokenAllowance
- TokenAllowance
  - uses 3 variables to represent the token amount in different forms
    - `dappProposedTokenAmount` is the initial `tokenAmount` passed in from ConfirmApprove 
    - `customSpendingCap`
       - initially set as `dappProposedTokenAmount`
       - may be updated through CustomSpendingCap (This component is not accessed through portfolio. Portfolio will render ReviewSpendingCap.)
    - `customPermissionAmount` = `replaceCommaToDot(customSpendingCap).toString()`

**Suggested Improvements found during investigation:**
1. `getTokenValueParam` and `getTokenIdParam` (PR created https://github.com/MetaMask/metamask-extension/issues/20789)
     - move methods into the same file
     - use BigNumber conversion methods instead of accessing internal/private JS props
     - note: `getTokenValueParam` has been used to retrieve the token id. See `const transactionDataTokenId` in  `ui/hooks/useTransactionDisplayData.js`
2. `customPermissionAmount` may be set as a string or a number type (PR created https://github.com/MetaMask/metamask-extension/issues/20790)
3. Fix console errors (PR created https://github.com/MetaMask/metamask-extension/issues/20791)
     - incorrect object key param formats
     - unexpected false boolean param
