### ISSUE TITLE
[Bug]: Create account button is disabled

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#20667]
### Describe the bug

See https://github.com/MetaMask/metamask-extension/pull/20168

<img width="1512" alt="Create account" src="https://github.com/MetaMask/metamask-extension/assets/53189696/1f07424e-541a-43ba-8526-42234c21d422">

### Steps to reproduce

1. Open the account menu
2. Click "Add account"
3. Don't change the value of the Account input (keep it empty)
4. Click Create

Actual result:

- The Create button is disabled
- The account is not created

Expected result:

- See the account created with the placeholder name

### Version

v10.35.1

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by Gudahtt** [comment]
I think I found the problem, described here: https://github.com/MetaMask/metamask-extension/pull/20168#discussion_r1310675888

**Comment by Gudahtt** [comment]
This renders the UX improvement/bug fix (however you want to categorize it) in #20168 ineffective, but functionally this is how v10.35.0 works as well.

I will remove #20168 from the RC, then maybe we can remove the regression label here and unlink it from the RC bug epic?

**Comment by Gudahtt** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/issues/20667
