### ISSUE TITLE
[Bug]: PPOM UI warnings appearing while using not supported networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#20688]
### Describe the bug

**Problem**: whenever we have PPOM module enabled, if we are on a different network than chainId 1, we can still see how UI warnings are being displayed on any type of transaction/signature screen

https://github.com/MetaMask/metamask-extension/assets/54408225/15953be2-2124-4487-970e-0feb59fd8122

**Expectation**: since the module is only supported on Mainnet, we shouldn't be displaying any warnings on the rest of the networks cc @bschorchit 

### Steps to reproduce

1. Build flask with ppom envars
2. Select Sepolia network
3. Enable Blockaid from experimental settings
4. Go to the test dapp
5. Try any tx/signature
6. See how warnings are still displayed

### Version

flask on top of https://github.com/MetaMask/metamask-extension/pull/20566

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I believe this will be addressed as part of this issue: https://github.com/MetaMask/MetaMask-planning/issues/1194

**Comment by bschorchit** [comment]
Closing as fixed :)
