### ISSUE TITLE
[Bug]: PPOM Warnings UI issues with specific responses

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#20691]
### Describe the bug

**Problem**: after reviewing different possible responses from ppom, the following UI issues have been identified:

- If ppom passes an object on one of the `features` field, MetaMask breaks
- If ppom passes an address without stringify it, MetaMask transforms it into a number

**Note:** The above issues are not issues found in production. This is rather a feature request to ensure in the case we receive unexpected responses, we can handle them gracefully. See https://consensys.slack.com/archives/C04C0F6SSJH/p1696951687197109

**Other problems reported we will not be addressing in this ticket:**
- If ppom passes a long string, this overflows the container 
   note: Create new Issue https://github.com/MetaMask/metamask-extension/issues/21316)
- If ppom passes a long list of items, it will take over almost all the window space - for this one, not sure if there's a solution :thinking: 
   note: not addressing here https://github.com/MetaMask/metamask-extension/issues/20691#issuecomment-1733552381

![Screenshot from 2023-09-01 15-31-15](https://github.com/MetaMask/metamask-extension/assets/54408225/d71120ba-d99c-41ce-8aa3-d69950a28a81)

![Screenshot from 2023-09-01 15-28-24](https://github.com/MetaMask/metamask-extension/assets/54408225/239f8e18-1737-45af-8fda-8bc1131032f3)

### Steps to reproduce

1. Go to extension codebase file `ppom-midleware.ts`
2. Change line 48 with the following code:
3. Build flask
4. Go to test dapp and trigger any tx
5. See all the UI issues mentioned above, by manipulating the `res` variable
6. (After removing the object one you'll be able to see the rest of the issues, as this one breaks MM)
```
        req.securityAlertResponse = await ppomController.usePPOM(
          async (ppom: PPOM) => {
            const res =
            {
              "result_type": "Warning",
              "reason": "",
              "description": "",
              "features": [
                "The address 0x07Be9763a718C0539017E2Ab6fC42853b4aEeb6B is malicious",
                "blablabla",
                "blablabla",
                {"slkjd": "sjdfsa", "ksdf": "skhdjfska"}
              ]
          }

            return res;
          },
        );
```

### Version

flask on top of https://github.com/MetaMask/metamask-extension/pull/20566

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by DhairyaMajmudar** [comment]
@bschorchit @seaona I would like to contribute can you please assign this issue to me.

**Comment by bschorchit** [comment]
Internal note: check with Blockaid team wether `features` parameter is ready to be used

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/20691?planning-poker) with Zenhub @digiwand @seaona @segun @blackdevelopa @jpuri

**Comment by segun** [comment]
@bschorchit @jpuri what's the proposed solution to point 4 above

```
If ppom passes a long list of items, it will take over almost all the window space - for this one, not sure if there's a solution 🤔
```

**Comment by bschorchit** [comment]
> @bschorchit @jpuri what's the proposed solution to point 4 above
> 
> ```
> If ppom passes a long list of items, it will take over almost all the window space - for this one, not sure if there's a solution 🤔
> ```

Let's not address this one. The warning is already collapsed by default and the user can collapse it back again.

**Comment by digiwand** [comment]
as mentioned above, we will not be addressing 
> If ppom passes an address without stringify it, MetaMask transforms it into a number

we can close this ticket
