### ISSUE TITLE
[Bug]: Unable to Sign Typed Data V4 or Sign Permit with Trezor HW

### ISSUE THREAD

**Issue by 0xGitGuy** [MetaMask/metamask-extension#20746]
### Describe the bug

Describe the bug
Metamask throws "Result: Error: Unknown message" when attempting to Sign Typed Data V4 or Sign Permit.

Trezor Protected Wallet address:
Sign Typed Data V4: "Result: Error: Unknown message"
Sign Permit : "Result: Error: Unknown message"
Personal Sign: No issues

NON-Trezor Wallet address:
Sign Typed Data V4: No issues
Sign Permit : No issues
Personal Sign: No issues

Firmware version and revision
Model One: 1.11.1 and 1.12.1
Trezor Suite : v23.8.1

Desktop/smartphone setup (please complete the following information):

Metamask 10.35.0 and 10.35.1
Windows 10
Brave Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (64-bit)
To Reproduce

### Steps to reproduce

1. Simply perform any Typed Data V4 or Sign Permit
2. Try signing Typed V4 or Permit at https://metamask.github.io/test-dapp/

Expected behavior
Data signing should not produce error

### Error messages or log output

```shell
"Result: Error: Unknown message"
```

### Version

10.35.0 and 10.35.1

### Build type

None

### Browser

Brave

### Operating system

Windows

### Hardware wallet

Trezor

**Comment by plasmacorral** [comment]
Sorry for the difficulty and thank you for making the time to share this info with us.  We have not been able to reproduce this on Windows 10 with Brave on v10.35.1 using Trezor firmware 1.11.2 or 1.12.1.   Is there anything further you can share about what occurred prior to this, or the last time you saw this work as expected?

As a sidenote, it looks like we need to update Trezor Connect dependancies and that may help improve this experience.  Keep an eye on https://github.com/MetaMask/eth-trezor-keyring/issues/187 for more details.
