### ISSUE TITLE
[Bug]: PPOM Security Alerts does not appear in Settings Search

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#20753]
### Describe the bug

**Problem:** whenever we search for `Security Alerts` in the settings search we can see how it does not find the new ppom/Blockaid section.

Side note: I'm a bit confused on the naming for the 2 features `Security alerts` and `Enable security alerts` for Blockaid vs Opensea respectively , not sure if this could also be improved?

https://github.com/MetaMask/metamask-extension/assets/54408225/a7751cd8-95a6-4307-a41f-86c5d25b6b81

### Steps to reproduce

1. Open settings
2. Search for `Security alerts`
3. See only the Opensea feature is displayed in the results (not the Blockaid/ppom one)

### Version

11.1.0 flask dev

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/20753?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun
