### ISSUE TITLE
[Bug]: Swap fails with error in TransactionController.getAdvancedGasFee

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#20766]
### Describe the bug

Swap fails with an error in TransactionController.getAdvancedGasFee after that I am seeing unapproved transaction in the activity but reject on confirm won't work. Only way is to recover is to reload the extension and rejecting the transaction. 

### Steps to reproduce

1. Try to swap any token 
2. Notice that swap fails with the error shown in the screenshot

https://github.com/MetaMask/metamask-extension/assets/6082863/1656de6d-731f-4bb2-81bb-c6012e02d151

<img width="1358" alt="Screenshot 2023-09-06 at 10 56 33 PM" src="https://github.com/MetaMask/metamask-extension/assets/6082863/d66707b9-455c-4493-87c5-b611bfa532a9">

### Error messages or log output

```shell
sentry-install.js:1   at R.getAdvancedGasFee (chrome-extension://kebmidnflamkfeeiboaeemgopfbffgnc/background-2.js:28:136268)
  at R._addTxGasDefaults (chrome-extension://kebmidnflamkfeeiboaeemgopfbffgnc/background-2.js:28:124400)
  at async R._addTransactionGasDefaults (chrome-extension://kebmidnflamkfeeiboaeemgopfbffgnc/background-2.js:28:122997)
  at async R._createTransaction (chrome-extension://kebmidnflamkfeeiboaeemgopfbffgnc/background-2.js:28:132310)
  at async R.addTransaction (chrome-extension://kebmidnflamkfeeiboaeemgopfbffgnc/background-2.js:28:116491)
  at async Ke.addTransactionAndWaitForPublish (chrome-extension://kebmidnflamkfeeiboaeemgopfbffgnc/background-4.js:1:214738)
  at async s.<anonymous> (chrome-extension://kebmidnflamkfeeiboaeemgopfbffgnc/background-4.js:1:56518)
```

### Version

11.0.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

I built locally with `yarn dist` after pulling the latest code from the `develop` branch

**Comment by davibroc** [comment]
@dan437 @danjm I tried with the release v11 and it's not happening there. Still happening on the latest code today

**Comment by sleepytanya** [comment]
Swaps work normally for me both on `dev` build  swaps and on `dist `build with the latest pull from `develop` branch (macOS).
1. `Dist` build:

https://github.com/MetaMask/metamask-extension/assets/104780023/41d8792d-f3b8-4c33-8c0c-e0ec5ccaad54

2. `Dev` build:

https://github.com/MetaMask/metamask-extension/assets/104780023/9b613f6a-a011-4c72-8b04-9f5700f126e3

**Comment by davibroc** [comment]
After doing a fresh install the problem disappeared for me and also another person that was seeing that. According to the Confirmation Sytem team it appears that when the error occurs, the advancedGasFee preferences state is null or undefined.
This was introduced recently in this PR though it appears to have a thorough migration so they're uncertain how this state was reached. This could be due to state and a bad upgrade migration
https://github.com/MetaMask/metamask-extension/pull/20576

**Comment by danjm** [comment]
Closing for now. Please alert me if anything like this is seen again
