### ISSUE TITLE
[Bug]: When I import the gold token by token address in custom token section it showed me the name of another token which is listed on coingecko

### ISSUE THREAD

**Issue by Musfirazia** [MetaMask/metamask-extension#20776]
### Describe the bug

In custom token section, by inputing token address it showed the correct token name but after clicking on import and land on main wallet screen, token name changed to some other token name.

### Steps to reproduce

1. Enter the following address 0x57c88ed53d53fDc6B41D57463E6C405dE162843e in custom token, first it detects the correct name and then import token.
2. After importing it will replace the name with some dragoneum token which is listed on coingecko

### Version

10.35.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS, Linux

**Comment by kevinghim** [comment]
Could not reproduce. @Musfirazia can you send a screen recording?

**Comment by Musfirazia** [comment]
@kevinghim 
Here you can see the screen recording, https://drive.google.com/file/d/1ZALuCmmtQf1Nquvxmsem4_ADSp685Tnn/view?usp=sharing
in the recording you can see that first I remove the token name dragoneum gold as shown in my metamask, however Its name on etherscan is GOLD(GOLD) then when I import again the same token it first shown me the correct name but when I move to accounts screen, name changed to draganoum gold, which is another token listed on coingecko.

**Comment by Musfirazia** [comment]
@kevinghim This issue is still not resolved when can I expect the next release
