### ISSUE TITLE
Investigate Unified Deploy Process and CDN Logistics

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#2081]
* Needs investigation per platform:
            * Chrome
            * Firefox
            * Mascara CDN
            * Github Releases
        * Automate new release announcements
            * Slack
            * Twitter
            * Facebook

**Comment by danfinlay** [comment]
Opened issues in place of all these bullet points, Related to this epic: https://github.com/MetaMask/metamask-extension/issues/3389
