### ISSUE TITLE
Add snap label to Account Snaps in the account list

### ISSUE THREAD

**Issue by raulmono** [MetaMask/metamask-extension#20819]
The snap label is missing in the accounts list. Account snaps should present a snap, including the snap badge and the name of the snap it's derived from.

Current displayed only as "snaps"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXFKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--38f6cbc82cd489f34f79b40142e52ce4226aa5e6/image.png)

Snapl label
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWlKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--690d6858155a3452f9b15b2ac6f919d44134d334/image.png)

Figma file
https://www.figma.com/file/4jYXYiXhJfr1iknC1ElGVt/Account-details-%23446?type=design&node-id=6640%3A78639&mode=design&t=rXqNkhSfsTkqwX5s-1

**Comment by AlexJupiter** [comment]
Confirming the copy for the pill `{{Snap name}} (Beta)`

**Comment by AlexJupiter** [comment]
Started to implement this:
- https://github.com/MetaMask/metamask-extension/commit/ac38e06c933ed331bfcd81dbe1047c3c3f4bfcf4
- https://github.com/MetaMask/metamask-extension/commit/21c98ba5d56ae75e1eb25a723affa3a2563aba9e
But we need to use the Accounts Controller now.

**Comment by k-g-j** [comment]
Working on this and would like confirmation of the desired copy.
Here is the current look.
<img width="722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmMxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a4ec0e204c151536a69ec036717e501d4c01319/Screenshot%202023-12-05%20at%205.13.16%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 5.13.16 PM.png" />

**Comment by AlexJupiter** [comment]
LGTM!

**Comment by danroc** [comment]
I had this change here to support the icon in the Tag component: https://github.com/MetaMask/metamask-extension/commit/21c98ba5d56ae75e1eb25a723affa3a2563aba9e

**Comment by k-g-j** [comment]
I can adjust the spacing on the tag. It seems like they are using a [refactored tag component](https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/component-library/tag/tag.tsx) now than the one @danroc [mentioned](https://github.com/MetaMask/metamask-extension/commit/21c98ba5d56ae75e1eb25a723affa3a2563aba9e)

**Comment by k-g-j** [comment]
> * The icon is missing

In regards to this, do we want to use the icon that is in the metadata about the snap or the MetaMask snap icon from the library? If we use a custom icon from metadata about the snap, will the icon be a url in the snap metadata or something we can pull from the npm package for the snap?

**Comment by k-g-j** [comment]
Draft PR: https://github.com/MetaMask/metamask-extension/pull/22251
