### ISSUE TITLE
Mascara Responsibilities vs. Extension

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#2082]
* Mascara Phishing Concerns
            * Do we limit account importing as extension-only?

**Comment by kumavis** [comment]
I'm again

**Comment by kumavis** [comment]
On the call we identified that key import is a user-driven action (they want to import a key) as opposed to an app-driven function (app wants you to import a key) and so an unlikely target for phishing

There is still a heightened phishing risk with mascara by faking a need to reimport your seed phrase for "verification" etc

I think we should address phishing head on with a secure pattern/phrase in the app bar or footer (needs design)
