### ISSUE TITLE
[Bug]: ERC1155 token image is not displayed

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#20849]
### Describe the bug

When import an ERC1155 NFT, the image is not displayed.

### Steps to reproduce

1. Enable ipfs gateway toggle and display NFT media toggle in privacy setting page.
2. Go to testdapp, deploy an ERC1155 contract and batch mint tokens.
3. Go to MM and import the minted token.

Expected: image should be displayed.

https://github.com/MetaMask/metamask-extension/assets/105063779/b98fe777-010d-4fb0-be8a-018062b6a79f

### Version

v11.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by darkwing** [comment]
Possibly related is that the breadcrumb is missing too:
<img width="788" alt="SCR-20230915-lmio" src="https://github.com/MetaMask/metamask-extension/assets/46655/a51274b4-15d4-45d7-a5f4-10c6eb2991c5">
