### ISSUE TITLE
Implement Error Reporting Service

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#2084]
https://sentry.io/welcome/

- [ ] Get designs / consultation on how to ask users to opt-in
- [ ] Get server running to accept sentry logs (must be able to handle possibly 100k requests in a short time period)
- [ ] Add sentry to the actual application

**Comment by flyswatter** [comment]
> Get designs / consultation on how to ask users to opt-in
How about we just have a screen that we show when signing up that asks users if it's ok for us to collect error data to make the app more stable?

**Comment by kumavis** [comment]
should also look at some other options as sentry is not the only solution out there

**Comment by danfinlay** [comment]
Another cheaper option is [Airbrake](https://airbrake.io/), $99/month for them to host & maintain an instance.

**Comment by kumavis** [comment]
We did this, yay
