### ISSUE TITLE
Create component: Table

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#20876]
### **Description**

Create `Table` component based on audit and insight report 

### **Technical Details**
- TBC

### **Acceptance Criteria**
- Component exists built to specifications outlined in the insight report
 
### **References**
- TBC

**Comment by subhajit20** [comment]
@georgewrmarshall Hey, can you give some brief about creating components like what steps to follow to get it done?

**Comment by georgewrmarshall** [comment]
Hey @subhajit20, thanks for your interest. I haven't managed to create any good first issues relating to component creation because it involves many nuances and I can't find the time to write a detailed good first issue that would provide all of the technical and design information needed. I would like to provide some in future!

**Comment by subhajit20** [comment]
@georgewrmarshall Okay sure, then can you help me to fix this one? https://github.com/MetaMask/metamask-extension/pull/20805#issuecomment-1717907044...I am almost close of making this issue fixed.
