### ISSUE TITLE
[Bug]: Show ENS domain in address bar toggle defaults 

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#20910]
### Describe the bug

The `Show ENS domain in address bar` toggle should switch OFF if the `IPFS gateway` is switched OFF, as the functionality does not work without an IPFS gateway 

https://github.com/MetaMask/metamask-extension/assets/53189696/bfb22b33-cc66-43fc-b0d5-9d0452f4c9d7

### Steps to reproduce

1. Log in to the extension
2. Click the Account menu, followed by the Settings menu item
3. Click Settings & Privacy from the left-hand menu
4. Turn ON the IPFS gateway toggle
5. Turn ON the Show ENS domain in address bar toggle
6. navigate to https://metamask.eth/ in another tab
7. switch back to the extension
8. Turn OFF the IPFS gateway toggle, Leave Show ENS domain in address bar toggle ON
9. navigate to https://metamask.eth/ in another tab

### Version

11.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Hi @PeterYinusa ,

> The Show ENS domain in address bar toggle should switch OFF if the IPFS gateway is switched OFF, as the functionality does not work without an IPFS gateway

I'm not sure about this assumption, my understanding is:
1) In some cases, an ENS resolves to an IPFS website. Ex: https://vitalik.eth/ => https://bafybeidj4gxdnaau7xzt52nxxrla7oyu75shok3xngyu6buww4zu6zvhmu.ipfs.dweb.link/
2) In some cases, an ENS resolves to a website that's not on IPFS. Ex: https://metamask.eth/ => https://app.ens.domains/metamask.eth

If that's correct, it means the `Show ENS domain in address bar` toggle doesn't have to switch OFF if the `IPFS gateway` is switched OFF.

It's worth being investigated though.

**Comment by PeterYinusa** [comment]
@gauthierpetetin My assumption is that most will be static website content hosted on IPFS. 
Thanks for providing more info, as I now see that my assumption was incorrect.
However, both  https://vitalik.eth/ (IPFS) and https://metamask.eth/ (not IPFS) do not resolve with `IPFS gateway` OFF

> Hi @PeterYinusa ,
> 
> > The Show ENS domain in address bar toggle should switch OFF if the IPFS gateway is switched OFF, as the functionality does not work without an IPFS gateway
> 
> I'm not sure about this assumption, my understanding is:
> 
> 1. In some cases, an ENS resolves to an IPFS website. Ex: https://vitalik.eth/ => https://bafybeidj4gxdnaau7xzt52nxxrla7oyu75shok3xngyu6buww4zu6zvhmu.ipfs.dweb.link/
> 2. In some cases, an ENS resolves to a website that's not on IPFS. Ex: https://metamask.eth/ => https://app.ens.domains/metamask.eth
> 
> If that's correct, it means the `Show ENS domain in address bar` toggle doesn't have to switch OFF if the `IPFS gateway` is switched OFF.
> 
> It's worth being investigated though.

**Comment by PeterYinusa** [comment]
I've placed the `DO NOT MERGE` label on https://github.com/MetaMask/metamask-extension/pull/20915 so we can continue the discussion on this issue.

**Comment by tommasini** [comment]
Yes! That's what we have almost finished on mobile 🙏🏼
