### ISSUE TITLE
[Bug]: Incoming transactions not displayed with toggle ON

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#20933]
### Describe the bug

Incoming transactions are not displayed even the toggle in privacy for incoming transaction is ON.
Info: I tested with both Goerli and Sepolia, we have the same issue on both.

https://github.com/MetaMask/metamask-extension/assets/105063779/dc696a31-d525-4db1-8670-2bafa71447a4

### Steps to reproduce

1. Make sure the toggle for incoming transaction is ON in settings/privacy.
2. Trigger a transaction.
3. See incoming transactions are not displayed

### Version

v11.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Gudahtt** [comment]
Fixed by #20973
