### ISSUE TITLE
[Bug]: Symbol @ is displayed as first character of a Snap's name

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#20969]
### Describe the bug

Regarding to #20851 , we should use the first non-symbol character as the snap fallback icon because we often have snap name starts with @

### Expected behavior

Text on notification screen should be displayed as: ***wants to connect to kleros/scout-snap. 

### Screenshots

<img width="359" alt="Screenshot 2023-09-20 at 09 53 43" src="https://github.com/MetaMask/metamask-extension/assets/105063779/b97e0a02-691f-4240-8255-33df65756217">

### Steps to reproduce

1. Try to connect to a snap that starts with @ (example: @kleros/scout-snap)
2. On connect notification screen, check displayed snap name.

### Version

v11.2.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by FrederikBolding** [comment]
@chloeYue https://github.com/MetaMask/metamask-extension/pull/20851 was only meant to be a fix for the icon. We still want to show the full snap ID in the copy below the icon.

**Comment by danjm** [comment]
Closing as per @FrederikBolding's comment

**Comment by chloeYue** [comment]
OK make sense, thanks !
