### ISSUE TITLE
[Bug]: Confirmation Add Suggested NFTs page is missing responsive support

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#20975]
### Describe the bug

Confirm Add Suggestion NFT page is a fairly new confirmation page added. It is missing responsive support. 

### Expected behavior

UI/UX should be have similar to other confirmation pages when expanding and collapsing window size

### Screenshots

![ConfirmAddSuggestedNft non-responsive](https://github.com/MetaMask/metamask-extension/assets/20778143/0500b268-94d8-4ad1-83b7-27305e47acdc)

![Screenshot 2023-09-20 at 8 57 13 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/ef6b3660-8988-4abb-b224-259c8e9e46cc)

### Steps to reproduce

1. Go to test dapp https://metamask.github.io/test-dapp/
2. NFT > Deploy button
3. NFT > Mint button
4. NFT > Watch NFT

### Version

11.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by vandan** [comment]
This issue is not directly related to the dapp API, looks like more of a general UX issue.
Re-assigning to `team-extension-client` to determine what's required here (and priority).

**Comment by alfeng6** [comment]
The Assets team can take this. I'll work with Amanda to get a design to implement.

**Comment by MrBlackGhostt** [comment]
is the issue is solve if not i want to work onit

**Comment by smitpatel98** [comment]
Hi! I'd like to help with this issue if no one is actively working on it.

**Comment by Jaycat66** [comment]
https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
