### ISSUE TITLE
Link to allowlisted website field in Snap settings

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-extension#20988]
<img width="338" alt="Screenshot 2023-09-21 at 8 51 13 AM" src="https://github.com/MetaMask/metamask-extension/assets/19909/1906c5cc-1391-4c5e-9ca0-bf2cced6bc7b">

In the above screenshot, a row is added for the website if a website is specified in the allowlist

Also, the install origin should not be a link and the connected sites far below this could be styled differently because they are not links

**Comment by eriknson** [comment]
Design: https://www.figma.com/file/Wlwk0cTx6PQkNhiX7vN13e/Snaps-Platform-v1?type=design&node-id=796%3A10038&mode=design&t=qWkRYWdnMSoM1ccw-1

**Comment by david0xd** [comment]
As discussed on the standup, we should also check if website is on the phishing list before displaying it in UI (don't display it if it's on the list).
