### ISSUE TITLE
[Bug]: Gas - `gasLimit` value passed from a dapp cannot be changed and if small, no UI feedback but button disabled

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21003]
### Describe the bug

**Problem**: whenever a dapp passes a `gasLimit`value, we can see 2 issues:
1. if the `gasLimit` is smaller than `21000` the transaction is triggered but the Confirm button is always disabled. No warning is showed.
2. if the user then tries to edit the gas values, the `gasLimit` will not be edited, instead the dapp value is preserved. Meaning that the Confirm button will continue to be disabled in the case of (1)

### Expected behavior

1. Whenever the dapp passes a `gasLimit` smaller than `21000` (the smallest amount allowed) we should expect some feedback from the UI instead of just disable the Confirm button, so the user can understand what's going on
2. Whenever the user changes then edits the gasLimit value, it should be saved and the Confirm button should be enabled

### Screenshots

https://github.com/MetaMask/metamask-extension/assets/54408225/73ca56f6-591b-4982-8c38-7f339ccc1e7a

### Steps to reproduce

1. Checkout the test dapp locally
2. Change the `transferTokens` gas value to the following values:
```
gasLimit: 20999,
```

3. Go to the test dapp
4. Click Create Token
5. Accept tx
6. Click Transfer token
7. See Submit button is disabled
8. Change gas settings
9. See Submit button continues to be disabled

### Version

11.0.0 production 

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by karangarg218** [comment]
can i solve this issue

**Comment by seaona** [comment]
This issue is still present

**Comment by bschorchit** [comment]
We should make sure [this warning](https://www.figma.com/design/yUczlH2HbHaHsYijiONKx0/Alerts-DS?node-id=2415-79361&node-type=frame&t=l24yG3BF01plrIMd-0) is shown in this case and make sure the user is able to edit it.

Maybe in the future we could automatically increase the gas limit to 21000? And just show a warning to tell the user that?

![Image](https://github.com/user-attachments/assets/db73e10c-55b5-4b1f-b879-c5a7068451b9)

**Comment by sleepytanya** [comment]
The issue in not present in 12.10.0:


https://github.com/user-attachments/assets/c354d657-b1b0-4dbb-96bb-92f9259b2ce8
