### ISSUE TITLE
Build error: RegExpCompiler Allocation failed - process out of memory

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#21006]
We have had some CI failures as follows:

![Screenshot from 2023-09-22 10-56-36](https://github.com/MetaMask/metamask-extension/assets/7499938/cfc0e117-5fdb-4bb3-a950-23eb8cbf13a8)

@Gudahtt commented:

> This comment suggests that there is a size limit in v8 for RegExp code objects, of 128 MB: https://bugs.chromium.org/p/v8/issues/detail?id=10441#c5
> Apparently this error can be encountered when your application uses RegExps that build up in memory without getting garbage collected. Solutions are to use smaller RegExps or take precautions to ensure they can be garbage collected sooner. The garbage collection explains why it's intermittent.

We should investigate and fix at some point, because this hurts development velocity

**Comment by danjm** [comment]
It is happening on at least one other CI job (in addition to the one in the screenshot above)
![Screenshot from 2023-09-22 11-05-29](https://github.com/MetaMask/metamask-extension/assets/7499938/ecd49820-53dd-4d76-8b12-7c476726a976)

**Comment by Gudahtt** [comment]
This may have been fixed by #22521. I'll close this for now. We can re-open if we see this recur in the near future.
