### ISSUE TITLE
[Bug]: Multiple transaction screen approval

### ISSUE THREAD

**Issue by OGPoyraz** [MetaMask/metamask-extension#21026]
### Describe the bug

This issue is found while working on `UUID` refactor on extension: https://github.com/MetaMask/metamask-extension/pull/20952

Basically if you have two different type of unapproved transaction (let's say signature and simple transaction), and if you confirm transaction, error is thrown.

I've tried couple of commit builds in order to address which PR introduced the issue but couldn't find the exact point. If that helps, it's between two of these PRs.
https://github.com/MetaMask/metamask-extension/commit/2070e5e42af276d1b314f37c64ca30706f0b4793 (3 months old)
https://github.com/MetaMask/metamask-extension/commit/1c0ff8a6e8c5aad67b83762e4e70b587f822ab21 (7 months old)

### Expected behavior

It should approve transaction and go back to signature confirmation screen

### Steps to reproduce

In order to reproduce the issue as it described [in the comment](https://github.com/MetaMask/metamask-extension/pull/20952#issuecomment-1731830647) :
1. Create regular 'send' transaction.
2. Do not close confirmation.
3. Go to test-dapp and create 'signature' transaction.
4. Try to navigate between two confirmations.
5. Try to confirm 'send' transaction.
6. See the error message.

### Version

develop

### Build type

None

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS, Linux

**Comment by seaona** [comment]
Relates/Same as https://github.com/MetaMask/metamask-extension/issues/19512

**Comment by dbrans** [comment]
This issue was fixed by commit https://github.com/MetaMask/metamask-extension/commit/a0e8ee14af00f9793349206909c44d7b68985c41

Parent commit, 5d818bb2, the issue was still happening.
