### ISSUE TITLE
Create a CLA bot

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#2105]
https://github.com/clabot/clabot

> The purpose of a CLA is to ensure that the guardian of a project's outputs has the necessary ownership or grants of rights over all contributions to allow them to distribute under the chosen licence. Wikipedia

**Comment by macbem** [comment]
https://cla-assistant.io/ This one might be a bit nicer as it doesn't require the contributor to type in a command that makes the CLAbot check if the user has signed the CLA.
