### ISSUE TITLE
Manual testing plan for MV3

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#21070]
Manual tests for MV3 should include:

- all e2e should pass
- all manual scenarios should pass (https://github.com/MetaMask/metamask-extension/tree/develop/test/scenarios)
- all manual scenarios should pass when done with a hardware wallet
- verify that every snap works with MV3 (https://snaps.metamask.io/)
- test metamask over a 1-2 hour period, using multiple dapps over that time
- test in Edge, Brave, Chrome, Chrome Beta and Chrome Canary
- Performance tests: measure before and after loading times of key flows
- ENS domain resolution
- the blockaid integration

**Comment by danjm** [comment]
- hardware wallets
- snaps
- blockaid

**Comment by gauthierpetetin** [comment]
https://docs.google.com/spreadsheets/d/1pIIEcY8vz0DEzHGyGBfue7tVwb139uc-C_pAAJe7zkQ/edit#gid=534384704
