### ISSUE TITLE
[Bug]: transaction data readout errs

### ISSUE THREAD

**Issue by hexpaydaydev** [MetaMask/metamask-extension#21133]
### Describe the bug

when one looks at the activity tab, clicks on a transaction, and scrolls to the bottom to see the "transaction data", an error with the phrasing: `Cannot read properties of undefined (reading 'map')` shows

### Expected behavior

not an error

### Screenshots

![Screenshot 2023-09-29 at 16 58 56](https://github.com/MetaMask/metamask-extension/assets/136479589/e7519dfa-d2d8-444e-a8bb-777cc3a10f6a)

### Steps to reproduce

1. go to activity tab
2. click on a recent transaction
3. scroll to bottom of detail modal
4. click on transaction data

### Version

11.0.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by anaamolnar** [comment]
I am closing this issue in favor of https://github.com/MetaMask/metamask-extension/issues/15009
