### ISSUE TITLE
[Bug]: metamask add  manta network report error

### ISSUE THREAD

**Issue by hoodmount** [MetaMask/metamask-extension#21137]
### Describe the bug

when i add manta network,it always report "Error while connecting to the custom network.",i use this url  https://chainlist.org/?search=manta to  add manta network,whether hava some  solution

### Expected behavior

can't add manta 

### Screenshots

![20231001171327](https://github.com/MetaMask/metamask-extension/assets/74347839/be7454f1-fc20-4cef-923f-dbadb2a9b3d2)

### Steps to reproduce

open this url https://chainlist.org/?search=manta  ，connect Metamask wallet, click Add to Metamask  button, then agree add manta network,the result is error,

### Version

11

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by hoodmount** [comment]
This problem has been resolved，I just  change the computer network

**Comment by Blackyems** [comment]
you changed the computer network how bro

**Comment by Blackyems** [comment]
having the same issue now
