### ISSUE TITLE
Move native token value below Fiat within Token list

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#21132]
## Background
We have inconsistencies around how we display locations of native token values and fiat. Particularly, on the token list, we have ETH below the token name and fiat value right aligned. Everywhere else it's juxtaposed next to the fiat value. We should be consistent about this pairing across different screens: wallet, activity, current connection, and all connected accounts, etc.

## Acceptance criteria
- Given that the user is on the wallet screen
- When the user view their token list
- Then display the native token value below the fiat value
  - When the primary currency is ETH, then the order should be flipped: ETH above fiat
  - Native token value should be followed by the native token symbol
- Then display the native token symbol over the full name of the token
 

Before:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkx4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ef39a654040e4e295684969d1b9bf0e06501754/Screenshot%202023-09-29%20at%204.45.34%20PM.png)

After:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2dhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--015d0cb560f6e7547d495cbbafeb2063e7a2ccf6/Screenshot%202023-11-29%20at%2010.22.00%E2%80%AFAM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE1hQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8c4da04bf68457c6e890eeb06094d8d252feab7/Screenshot%202023-11-29%20at%2010.26.39%E2%80%AFAM.png)

**Comment by kylefiedler** [comment]
This change creates consistency between Portfolio and Extension

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGdhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4871c0ab060835f1ff8aa972ca47494644c04a80/screenshot_2023-11-21_at_1.45.16___pm.png)

**Comment by kylefiedler** [comment]
Figma for component: https://www.figma.com/file/MlBUrNnIXlftX4TSjqiUYg/branch/NPl39fj5Av5kuBihsiwoCf/Core-Components?type=design&node-id=1717%3A21222&mode=design&t=Saw7dKcIRepHPkz6-1

Figma for screen view: https://www.figma.com/file/LDlI7yjKBNIY60MtQv9QS0/Amon-Hen%2FV1?type=design&node-id=6803%3A51537&mode=design&t=9TeOl30hSI3UXB2a-1

**Comment by kevinghim** [comment]
I'm unblocking this @vthomas13
