### ISSUE TITLE
[Bug]: Layer 1 fees not displayed on tx's triggered from inside the wallet, in L2 networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21139]
### Describe the bug

**Problem**: whenever we are on a L2 network and we are triggering a transaction from inside the wallet, we can see that Layer 1 fees are not displayed, only L2.

This issue will be introduced when [this PR](https://github.com/MetaMask/metamask-extension/pull/19960) get's merged.

### Expected behavior

Display both L1 and L2 fees in the same way it's done from tx triggered from a dapp

### Screenshots

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/d09d62d5-0b83-4593-88ee-ff1d300530f7)

We should expect to see both fees, example:

![Screenshot from 2023-10-02 11-04-51](https://github.com/MetaMask/metamask-extension/assets/54408225/b45c5c93-9be7-492d-b06c-1d5e2f078db1)

### Steps to reproduce

1. Select Optimism network
2. Trigger a Send from inside the wallet
3. See fees details

### Version

develop when this get's merged https://github.com/MetaMask/metamask-extension/pull/19960

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21139?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
This issue is a high priority for early January because it's a regression being introduced on extension v11.9

**Comment by segun** [comment]
There are 2 issues

1. I have an issue with optimism network, once I add it to MetaMask it hangs and I can't do anything else until I delete and re-install MM
2. It seems from code below that we are only calculating L1 Fees for Optimism network. So Optimism Network should have the L1 fees (I can't confirm this because of 1. above) but other L2 won't

```
  const contract = new Contract(
    OPTIMISM_GAS_PRICE_ORACLE_ADDRESS,
    OPTIMISM_GAS_PRICE_ORACLE_ABI,
    provider,
  );
  const serializedTransaction =
    buildUnserializedTransaction(txMeta).serialize();
  const result = await contract.getL1Fee(serializedTransaction);
  return result?.toHexString();
```

**Comment by segun** [comment]
@seaona I can confirm that layer 1 fees are shown for optimism wallet send. Can you please check again and let me know if you're still experiencing this bug? Thanks,

**Comment by seaona** [comment]
hi @segun I've just checked and I see the L1 fees now with internal transactions too :raised_hands:  So I think we can close the issue 

![Screenshot from 2024-01-09 13-02-18](https://github.com/MetaMask/metamask-extension/assets/54408225/df8aec84-38dc-4b3b-afdf-ccb7fd17c8f6)
