### ISSUE TITLE
Move Snaps to 3-dot menu

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-extension#21168]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFA4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--449848e5c79e8196b44f70f4a5327023c3cc6d95/Screenshot%202023-10-03%20at%2010.04.17%E2%80%AFAM.png)

**Comment by kenhkan** [comment]
From sprint planning: Erik to provide Figma and David to implement

**Comment by eriknson** [comment]
Design: https://www.figma.com/file/3Z2k9kDpHxoyjwtQo1DAam/Home?type=design&node-id=1%3A13377&mode=design&t=r3kMWXs5ve8DHUpZ-1

**Comment by eriknson** [comment]
From discussion on Slack: We're removing the Snaps settings menu in favor of this.
