### ISSUE TITLE
Change network display name "Optimism" to "OP Mainnet"

### ISSUE THREAD

**Issue by kevinghim** [MetaMask/metamask-extension#21179]
## Acceptance criteria
- Change network display name "Optimism" to "OP Mainnet" for all occurrences of the network name throughout the extension

**Comment by davesurbhit** [comment]
Please assign this issue to me

**Comment by davesurbhit** [comment]
Also, should we also change optimism to  OP Mainnet from the keys in json?
For eg : 
"networkNameOptimism": {
    "message": "Optimism"
    
Should I change it to 
"networkNameOptimism": {
    "message": "OP Mainnet"
    
or 

"networkNameOPMainnet": {
    "message": "OP Mainnet"
