### ISSUE TITLE
Write security guidelines for Account Snap developers

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-extension#21209]

**Comment by danroc** [comment]
This issue was created in the wrong repo, closing.

**Comment by dicv2** [comment]
kay

**Comment by Anouk1973** [comment]
Vraagje kunnen jullie mn crypto valuta gewoon omwisselen maar euro en terug
storten op BUNQ rekening

Anouk Wijkens

Op ma 1 jan. 2024 10:55 schreef Decentralazied Internet Coin <
***@***.***>:
