### ISSUE TITLE
[Bug]: Cannot find network details check entry in settings search

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#21206]
### Describe the bug

Cannot find new entry "network details check" in setting's search bar.

https://github.com/MetaMask/metamask-extension/assets/105063779/b73b1d7b-6ad3-4396-90d0-c666e9dbebd1

### Expected behavior

Should be able to find "network details check" entry by any of the word "network" or "details" or "check".

### Steps to reproduce

1. Go to Settings page
2. Try to find "network details check" by search bar

### Version

v11.3.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
I am going to say this is not a release blocker, but I will add it to the extension platform team's next sprint
