### ISSUE TITLE
An Error occurred while downloading an install extension

### ISSUE THREAD

**Issue by notocrypto** [MetaMask/metamask-extension#2120]
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior >>> Add Extension
  *  Actual Behavior  >>> Click Add to chrome >> Click Add Extension >> Error 
  *  Browser Used >>> Google Chrome
  *  Operating System Used  >>> **Window 7 Ultimate, 64bit**

![1505764434915](https://user-images.githubusercontent.com/32077111/30563209-606e23f6-9ceb-11e7-9e10-313f7ad5969e.jpg)

**Comment by Zanibas** [comment]
Not able to replicate on my device--Ubuntu 16.04, Google Chrome. Does the error still persist even after a full browser restart?
