### ISSUE TITLE
[Bug]: Same NFT can be added twice if using integer and hex value for the token id

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#21227]
### Describe the bug

According to previous fix #20940 , when users try to import same NFT twice first with tokenId(decimal value) then with hex value, error message should be displayed informing that nft has been already imported and cannot be re-imported.

However now i can still import a NFT twice on Goerli network.

Info: When i test with Mainnet, behaviours is expected, the error message is correctly displayed and prevent user to import a NFT twice.

https://github.com/MetaMask/metamask-extension/assets/105063779/f680b6e2-cde8-42a6-bc45-7ca7b3a6bfe2

### Expected behavior

Error message is displayed and user cannot import same NFT twice.

<img width="367" alt="Screenshot 2023-10-06 at 11 29 15" src="https://github.com/MetaMask/metamask-extension/assets/105063779/1d8576d7-08ff-4193-9370-0340db3a7c3f">

### Steps to reproduce

1. Go to test dapp
2. Deploy and Mint the NFT
3. Go to wallet
4. Click Import NFT
5. Add token contract and id 
6. See token is added
7. Click Import Nft again
8. Add token contract and same id in hex value
9. See token is added, we have now 2 tokens which are the same

### Version

v11.3.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sahar-fehri** [comment]
Hello @chloeYue,
I have tested this locally and the fix is working; I'm still not sure if that fix is included in the build you are testing

![image](https://github.com/MetaMask/metamask-extension/assets/10994169/f7b6e3f1-d851-4cd9-bb89-1ba2e65abaa0)

![image](https://github.com/MetaMask/metamask-extension/assets/10994169/a6ae699f-6c38-4c5e-9e2a-190179f2f2b3)

**Comment by sahar-fehri** [comment]
Working on the fix for this 🙏
