### ISSUE TITLE
Creating a reusable footer component for confirmation pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21278]
The task includes creating a reusable footer component for confirmation pages. This will be very similar to current footer component for confirmation pages.

Designs here: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=775-28145&mode=design&t=fcwGIVZS3lkt9rOO-0

Implementation Notes:
- Could reutilize mobile footer. In case of any questions, please reach out to @brianacnguyen 
- Please use the proposed [file structure](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#b504b50ddc1842d08d61a85cf7bc3160) while designing this component
- Refer to component [checklist](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#f43a74be4bfa424c87206b0a97a51ea2)

We need to add logic to cancel / submit the signature request. These functions can be declared inside a hook or the component itself.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelFkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39454f30e90e363f2703bd636bfd22c0e8e0f4fd/Screenshot%202023-10-10%20at%203.45.22%E2%80%AFPM.png)

**Comment by digiwand** [comment]
updated with **Implementation Notes:**

**Comment by digiwand** [comment]
updated description with **Implementation Notes**
