### ISSUE TITLE
Implement new routing for signature request pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21277]
As part of re-design we will implement new routing for signature request pages. Details for implementing routing can be found here: https://docs.google.com/document/d/1B1rUIC4ENSDythP1_CZ-T3HNZF8KPzVV4T0oGmwigSQ/edit?usp=sharing

We need to ensure that this change is hidden behind a build flag.

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21277?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun
