### ISSUE TITLE
Unable to get return value from contract

### ISSUE THREAD

**Issue by EasonWang01** [MetaMask/metamask-extension#2127]
if the function is a pure function like return `const` or `view` it can successful return the value;
```
function f(uint a, uint b) view returns (uint) {
        return a * (b + 42);
    }
```
but if it's something need to execute the contract and wait for it to return,the result will be

in remix browser IDE
```
Results: {
......
}
```

in web3 metamask api

```
return some tx hash
```

Both are not the return value that write in contract.

also refer to this issue https://ethereum.stackexchange.com/questions/10948/why-do-solidity-browser-non-constant-functions-return-values

How can we using the metamask browser web3 api to get contract return value?

**Comment by kumavis** [comment]
yes transactions do not yield a return value
you must use `eth_call` with the same parameters of the tx to get the return value

**Comment by EasonWang01** [comment]
Thanks, can you give an example?

Because the below eth.call also only return `0x`
```
web3.eth.call({
  "blockHash": "0xee20e00292aef9ec3b65b1eacdd3a19a75c3f13c015d4d73c7163d0b13cfd0e5",
  "blockNumber": 1706625,
  "contractAddress": null,
  "cumulativeGasUsed": 50527,
  "from": "0x10c88bba3f0fc1a77c22540661c9d19a3ae06a33",
  "gasUsed": 21464,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "root": "0x",
  "to": "0xe7a20925f50fea2d961c90a8888f2593aca068a0",
  "transactionHash": "0xdf71c30765330fa90bd452fdd8ca6b9d3e62cbe72af46e3deddda44f3b42ec6b",
  "transactionIndex": 1
}, (a,b) => {
console.log(a);
console.log(b)
})
```

**Comment by savy-91** [comment]
@EasonWang01 did you manage to get the return value?

**Comment by jennypollack** [comment]
closing for now, feel free to reopen if you're still having issues @EasonWang01
