### ISSUE TITLE
Creating reusable header component for confirmation pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21279]
We need to creating reusable header component for confirmation pages.

Designs: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=775-28145&mode=design&t=fcwGIVZS3lkt9rOO-0

This can be placed at /ui/components/app/confirmations

For the data that is required by header component we need to create / use existing hooks.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--055ad992e73e45f18866ac97b7df0287e07ca3fd/Screenshot%202023-10-10%20at%203.45.29%E2%80%AFPM.png)

### Out of scope
There will be separate tasks to implement both the info icon (the icon on the left) and advanced user toggle (the icon further to the right) in header component.
- Info icon issue: https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-extension/21280

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21279?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by digiwand** [comment]
should we also include support for multiple navigation with this header? or create a new ticket to support @jpuri @hilvmason

**Comment by digiwand** [comment]
actually multi navigation will be interesting as they are supported on a per page basis. what would the experience be navigating from an existing confirmation page to a new confirmation page?

**Comment by digiwand** [comment]
multi navigation will be interesting as they are supported on a per page basis. what would the experience be navigating from an existing confirmation page to a new confirmation page?

**Comment by digiwand** [comment]
multi navigation will be interesting as they are supported on a per page basis. what would the experience be navigating from an existing confirmation page to a new confirmation page?
