### ISSUE TITLE
Create message component for signature request pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21287]
We need add message component for signature request pages:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8389e74949f364678e65f64b4b90a6a28c935798/Screenshot%202023-10-10%20at%204.44.02%E2%80%AFPM.png)

Designs: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=775-28145&mode=design&t=fcwGIVZS3lkt9rOO-0

The component can be places in /ui/components/app/confirm

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21287?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
This is also blocked by the key value component
