### ISSUE TITLE
Create a base component for confirmation pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21281]
#### What is this about?

We need to create a base component for the confirmation pages. This will support other child components:

- Header
- Banners
- Title and Description
- Request origin info
- Signature request message
- Footer

We plan to use this base to support other transaction-type pages 

Designs: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=775-28145&mode=design&t=fcwGIVZS3lkt9rOO-0

See Architecture Proposal for more info: https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069#de28d103ea3e443f88fbae916ffba548

The component can be placed in /ui/pages/confirm

A separate task is created to add scroll to this page: https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-extension/21285

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21281?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by digiwand** [comment]
Based on a discussion and the architecture proposal, we plan to create a page for each transaction page type. It is possible we can create a general ConfirmPage for the other pages to use

updated the description with more details

**Comment by jpuri** [comment]
Re-opening the task to use multichain page component in base component.
