### ISSUE TITLE
Create component to display origin information

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21286]
We need a component that should display the origin for the confirmation:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53c30e27f65806b7b6f18ece82e1bc12be9e9099/Screenshot%202023-10-10%20at%204.15.26%E2%80%AFPM.png)

Please note that not every request will have a contract.

Designs: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=775-28145&mode=design&t=fcwGIVZS3lkt9rOO-0

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21286?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
This issue is also blocked by the key-value components

**Comment by digiwand** [comment]
A row wrapper component is being created here https://github.com/MetaMask/metamask-extension/pull/19957/files

**Comment by digiwand** [comment]
dependent ConfirmInfoRow (key/value support) Issue here 
https://github.com/MetaMask/metamask-extension/issues/21751

**Comment by digiwand** [comment]
I split this ticket into two tickets:
1. row component for origin (https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-extension/22277) 
2. row component for contract 

The reason for splitting out the row component for the contract is that I don't believe we will be supporting the contract display for the first MVP page based on https://www.figma.com/file/CeAIcptzeaI5ciTpYBaiqr/Confirmations-DS?type=design&node-id=350-34792&mode=design&t=eMSz04Li6OzJ0Di6-0. Also, it may need some more discussion to see if we will support a different UI while petnames is being fully launched.

**Comment by digiwand** [comment]
moving back to in progress because I realized we will want to apply similar checks we have on the existing site origin UI component here
