### ISSUE TITLE
Kindly help with warning message please!

### ISSUE THREAD

**Issue by FrothMeista** [MetaMask/metamask-extension#2128]
Hello community, sorry if this has been answered, but how do I deal with the following message:

"Signing this message can have dangerous side effects. Only sign messages from sites you fully trust with your entire account. This dangerous method will be removed in a future version. Read more here."

This is when I attempted to open an order for OMG, using my deposit of ETH on EtherDelta. I went ahead and signed anyway, but now I am growing worried that my account is vulnerable. Can you please tell me what I should do, as if I was 4 years old! Much appreciated!

**Comment by flyswatter** [comment]
What website gave you this message?

The message means exactly what it says: When you sign that, we can't tell you exactly what you're signing, but it may be something malicious, like a contract you can't read, so you should only sign things from sources you totally trust.

**Comment by FrothMeista** [comment]
It’s from the EtherDelta site. How else do I place a buy order? The warning always comes up.

Many thanks
Bruce

**Comment by flyswatter** [comment]
That's a good question for EtherDelta, it's up to them how they run their site.

**Comment by FrothMeista** [comment]
Too true. Would you kindly consider one more question. Can you please recommend the site/s that work in a secure way with your amazing extension?

Many thanks
Bruce

**Comment by flyswatter** [comment]
There was a recent twitter thread with a lot of good recommendations: https://twitter.com/radix42/status/905960763075977216

**Comment by FrothMeista** [comment]
Many thanks Dan, please feel free to ask me for a favour any day!

**Comment by sai-sai-sai** [comment]
Hi FrothMeista , i am getting this message too , is it ok to place the order . I am also using EtherDelta + Metamask Wallet. Can you please suggest or help let me know a better way you may have taken?

**Comment by FrothMeista** [comment]
Hi sai-sai-sai - I went ahead and ignored the message, and have traded many coins on EtherDelta since I posted this question. There is truly a risk, but everyone has to take it to trade on ED, so I would like to say don't worry. All I can say is went ahead after the warning and all was fine. Good luck!

**Comment by pdramorim** [comment]
Hi guys, conscious that this is an old thread, but I am having the exact same concern here.

So, I too am trying to trade on ED with MM for the first time, I too am getting the exact same warning, and I too certainly do not feel like this is a site I can “fully trust with my entire account”. Especially after reading all the terrible user reviews and phishing reports that are out there.

That being said, the wallet I’m trying to use is empty, so I’m not really worried about having anything stolen from it if it were to eventually become compromised. But that wallet is synced to my MetaMask account, which in turn contains the details of other wallets that aren’t empty.

What I’m trying to understand is: would signing this message give the website access only to the wallet that happens to be in use in that particular moment? Or would I be granting access to the entire MetaMask account instead, along with the details of any other wallets that happen to be associated with it?

Thanks in advance,
Pedro

**Comment by danfinlay** [comment]
@pdramorim we've just added a new knowledge base article about this:
https://consensys.zendesk.com/hc/en-us/articles/360004427792#

In short: Signing a message only risks the account you are signing with. It gives no other powers to the site.

**Comment by pdramorim** [comment]
thanks for the clarification @danfinlay, much appreciated
