### ISSUE TITLE
Create a component to show title and description of confirmation pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21282]
We need to add a component to display title and description for the confirmation. The title and description content will depend of the type of the confirmation request.

Designs: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=775-28145&mode=design&t=fcwGIVZS3lkt9rOO-0

See Architecture Proposal for more info: https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069#de28d103ea3e443f88fbae916ffba548

The component can be placed in /ui/components/app/confirm

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ffb82714644a7ce9d0fabcbce33fe7f64c95165/Screenshot%202023-10-10%20at%204.02.02%E2%80%AFPM.png)

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21282?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
Note from refinement: This should include storybook and unit tests
