### ISSUE TITLE
Create info icon in confirmation page header

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21280]
Once reusable header component is added as part of [this](https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-extension/21279) task we need to add info icon to it.

Designs: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=982-34677&mode=design&t=IanteD1CJ5MeHToB-0

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekFuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62477f7d351ca288a4296d26958f4215ae148ebc/Screenshot%202023-10-11%20at%209.33.33%E2%80%AFPM.png)

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21280?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
The key value component is a pre-requisite for this. We'll add it as dependency once we create the issues for it.
