### ISSUE TITLE
Create component to display nested message data for signature request typed data

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21284]
Signature request typed message has a tree structure. We need to create a component to display this:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30cdd5301bec849bf037c11f6bf709fa09e8c5f9/Screenshot%202023-10-10%20at%204.25.37%E2%80%AFPM.png)

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21284?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
This is blocked by the key value components

**Comment by bschorchit** [comment]
We should solve input validation separately as a different issue (mobile examples: https://github.com/MetaMask/metamask-mobile/issues/5590 https://github.com/MetaMask/metamask-mobile/issues/7316)

**Comment by digiwand** [comment]
ConfirmInfoRow component has been started here https://github.com/MetaMask/metamask-extension/pull/19957/files
