### ISSUE TITLE
Create scroll to bottom component

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21285]
We need to add scroll to the bottom component created as part of [this](https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-extension/21281) task.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07172c9f6875f57500f532354f98525d44ca7d94/Screenshot%202023-10-10%20at%204.22.38%E2%80%AFPM.png)

Deliverables: 
- Only visible if content is scrollable
- Hidden at the end of scroll content

As discussed with the Design System (DS) team, we will implement the scroll-to-button using the [ButtonIcon](https://metamask.github.io/metamask-storybook/?path=/story/components-componentlibrary-buttonicon--as) with a background and drop shadow. The DS team has spoken about creating a floating action button. We will implement the component for our use case and maybe the DS Team will adopt parts of it in the future.

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21285?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by digiwand** [comment]
updated description with notes following DS office hours

**Comment by digiwand** [comment]
updated with deliverables. 
we may consider inspiration from existing scroll-to-bottom buttons e.g. https://metamask.github.io/metamask-storybook/?path=/docs/components-app-termsofusepopup--docs
