### ISSUE TITLE
unable to swap on linea

### ISSUE THREAD

**Issue by povertyhacked** [MetaMask/metamask-extension#21296]
### What is this about?

option to swap on MM not available on Linea. Saw tweet around a month ago saying that this feature was available. have updated to most recent version and re-installed; can swap on other networks but not Linea still.

**Comment by anaamolnar** [comment]
Hey @povertyhacked. Thanks for reporting! Please reach out to our live support by clicking on 'Start a conversation' on our official support link: https://support.metamask.io/hc/en-us
