### ISSUE TITLE
[Bug]: Don't see 'App installed' event when onboarding whether user choose to opt in or opt out metrics

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#21300]
### Describe the bug

In #20909, when user opts in metrics, we should see 'App installed' event during onboarding. 
When user opts out metrics, 'App installed' event will not be sent until user enable MetaMetrics in privacy settings.

However, now i don't see 'App installed' event either user choose to opt in or opt out metrics.

https://github.com/MetaMask/metamask-extension/assets/105063779/d559a95d-357d-4a4a-b81b-09c8f72dad44

### Steps to reproduce

1. Install the unpacked zip
2. open dev tool from background.html
3. inspect the network request with keyword batch
4. onboard with opting in will see the batch request 'App installed'
5. onboard with opting out will not see the request 'App installed' until enable MetaMetrics in the privacy setting

### Version

v11.3.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
I'm marking this as a release blocker as this is an important metric event
