### ISSUE TITLE
Metamask Recent Transaction History Missing

### ISSUE THREAD

**Issue by pigtofly** [MetaMask/metamask-extension#2132]
I have multiple accounts under 1 metamask account. After switching between accounts, several accounts only show the most recent 1 transaction (sent), and another account missing all September transactions (sent). Any fix?

Btw, metamask was really slow when I tried to sent transacations, and several transactions showed up as failed although actually were successful according to etherscan.

Thank you!

**Comment by Zanibas** [comment]
Could you open up a support ticket at https://support.metamask.io/home and provide us with state logs?

**Comment by willnwhite** [comment]
I believe this is the same problem as #1210. I came here to report this problem too. I have this: 
![screen shot 2017-11-03 at 12 28 15](https://user-images.githubusercontent.com/8081877/32373840-2bc1443c-c093-11e7-8b9a-ef9cff3468b0.png)
I know I made a transaction from this account using MetaMask, so there should be a transaction in the history. I see the same thing with test accounts (on test networks) that I've made transactions from... their transaction history goes missing. I can try to reproduce the error if you wish.

**Comment by jebus197** [comment]
Hi I have the same problem. Not all of my transaction history is showing up. Specifically not all incoming transactions are showing up in my history. I have the setting to show all incoming transactions in my history enabled. (It was enabled by default). I believe MetaMask is showing my correct balance, but not my full history. I haven't made any outgoing transactions using Mertamask, only incoming ones. Clearly my displayed balance does not match my transaction history. What's going on? Thanks.

![Capture](https://user-images.githubusercontent.com/9163762/81311650-9565a600-907d-11ea-8892-62c0ab1bbd18.JPG)
