### ISSUE TITLE
`allowedOrigins` is not shown properly in Snaps permission screen

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/metamask-extension#21351]
Recently we expanded the snaps permission `endowment:rpc` to support a new entry `allowedOrigins`.

This means that in addition to the existing functionality (`{ dapps: true, snaps: true }`) you can now customize and allow only specific origins, e.g. a specific snap and/or dapp: `{ allowedOrigins: ['metamask.io', 'npm:metamask/example-snap'] }`. The current permissions UI does not support this currently, so we should implement a permissions request list item for this new functionality.

**Comment by kenhkan** [comment]
From refinement:
* Frederik to add details

**Comment by eriknson** [comment]
Proposed solution / copy in this thread: https://consensys.slack.com/archives/C02GL38PLE6/p1698744834804939

**Comment by eriknson** [comment]
Design ready, unassigning myself
