### ISSUE TITLE
web3.eth.accounts empty on window load event

### ISSUE THREAD

**Issue by macbem** [MetaMask/metamask-extension#2140]
Env: macOS Sierra, Chrome 61

Reproduction steps:
- install MetaMask
- log into MetaMask
- go to https://codepen.io/anon/pen/EwyMgN
- observe an empty array in the console

Disclaimer: I know that you shouldn't rely on the injected web3 instance and I don't do it in my Dapp, but I didn't link web3 to this Codepen since it doesn't make any difference when I use web3 supplied by me.

Previously, web3.eth.accounts was available as soon as the window load event fired - now I can't access it like I used to. Do I have to use web3.eth.getAccounts now? If so, a warning would be useful - I spent a while debugging this issue.

**Comment by owocki** [comment]
heres a handy workaround i've been using to calling a callback when web3 is available

```
var waitforWeb3 = function(callback){
    if(typeof web3 != 'undefined'){
        callback();
    } else {
        var wait_callback = function(){
            waitforWeb3(callback);
        };
        setTimeout(wait_callback, 100);
    }
}
```

**Comment by macbem** [comment]
@owocki This issue is about `web3.eth.accounts` not being populated on load, not about `web3` being undefined.

**Comment by danfinlay** [comment]
I'm able to see `web3.eth.accounts` in the console when I try reproducing, but I've confirmed it's not always present on initial load. You can work around this issue by checking occasionally:

```javascript
window.addEventListener('load', () => {
	console.log('codepen load' + web3.eth.accounts);
  
  setTimeout(function() {
    	console.log('codepen timeout ' + web3.eth.accounts);
  }, 2000)
});
```

**Comment by macbem** [comment]
Well, yeah, you could do that, but it's not the best option if you need to request some data regarding an account from an API. To work around this, I've used `web3.eth.getAccounts` which is async and seems to work every time.

**Comment by sandeep1116** [comment]
I am calling web3.eth.getAccounts also but in vain . It is not giving me account list at all. 
Can any one help what can be the problem.

**Comment by danfinlay** [comment]
@sandeep1116 What are you getting back instead? Maybe try reloading that page? Is MetaMask unlocked?

**Comment by sandeep1116** [comment]
Thanks for response !
It returns 'undefined'
Metamask is unlocked I even submitted one contract on ropsten test network via remix.
I wrote below code inside index.html.
`  window.addEventListener('load', () => {
    console.log('codepen load' + web3.eth.accounts);
    if (typeof web3 !== 'undefined') {
        // Use Mist/MetaMask's provider
       window.web3 = new Web3(web3.currentProvider);
       //window.web3 = new Web3(Eth.givenProvider || 'ws://some.local-or-remote.node:8545');
       
       // web3 = new Web3(Web3.givenProvider || 'ws://some.local-or-remote.node:8545');
        alert('Metamask used');
    }
     else {
        console.log('No web3? You should consider trying MetaMask!')
        // fallback - use your fallback strategy (local node / hosted node + in-dapp id mgmt / fail)
        window.web3 = new Web3(new Web3.providers.HttpProvider("https://ropsten.infura.io/token"));
    }
  
  setTimeout(function()
   {
        
        console.log('codepen timeout ' + web3.eth.accounts[0]);
        alert('after timeout');
    var res  = web3.eth.getAccounts()
     {                   
        console.log(res);
        web3.eth.defaultAccount = web3.eth.accounts[0];
        alert('Sandeep'); 
        console.log(web3.eth.accounts[0]);

    }

  }, 2000)
  alert( 'inside timeout');

});`

**Comment by sandeep1116** [comment]
Just more info
web3.currentProvider.isMetaMask    is true

**Comment by danfinlay** [comment]
@sandeep1116  `getAccounts` is a callback function. It does not provide a synchronous result.

Learn more here:
https://developer.mozilla.org/en-US/docs/Glossary/Callback_function

To get those accounts, you need to:
```javascript
web3.eth.getAccounts(function (error, accounts) {
  if (error) return console.error(error)
  doWhatYouWantWithAccounts(accounts)
})
```

**Comment by bdresser** [comment]
@macbem @sandeep1116 closing this, as we're moving away from allowing access to the user's current account on load for a bit of added user privacy. read more on #714 or the more general [EIP](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md)
