### ISSUE TITLE
Create folder structure for new confirmation components

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21413]
We plan to re-write the confirmation pages while re-designing them. We need to create folder structure for placing the new confirmation components. This will include

- new component for routing
- new app components
- new UI components

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21413?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun
