### ISSUE TITLE
[Bug]: ENS name, icon and hexadecimal address wrongly positioned

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#21411]
### Describe the bug

The ENS text and icon is positioned on the far left side of the extension. 

### Expected behavior

For UI/UX purposes, the ENS name, address and icon should be correctly aligned as per the screenshot below.

![image](https://github.com/MetaMask/metamask-extension/assets/120041701/5bc4f0b6-2ad5-480f-9f9a-723fb3efc365)

### Screenshots

![image](https://github.com/MetaMask/metamask-extension/assets/120041701/eb9352cb-972e-4dfa-917b-ce85e8b02aaa)

### Steps to reproduce

1. Open MetaMask extension
2. Fill in your password
3. Proceed to the send flow
4. Enter an ENS name: e.g. aed.eth
5. Notice the result is positioned too close to the left margin. 

### Version

11.4.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by benjisclowder** [comment]
![image](https://github.com/MetaMask/metamask-extension/assets/120041701/526da289-046d-4a09-8266-ad45834ee65c)
On the same note: The text in "Asset" overflows the box.

**Comment by georgewrmarshall** [comment]
Reassigning to Wallet UX as not directly related to design system but rather the implementation of UI rather that the UI component itself. Happy to support
