### ISSUE TITLE
[Bug]: Cannot add a network if I have another network with same chainId and different symbol in the Wallet

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21428]
### Describe the bug

**Problem**: whenever I want to add a new network using the MM API, if I have another network with the same chainId, which as a custom symbol (instead of the one expected by the network), I cannot add another network and I see the error 

`MetaMask - RPC Error: nativeCurrency.symbol does not match currency symbol for a network the user already has added with the same chainId. Received:ETH`

I will only be able to add another network with the same chainId, if I delete the custom one I have, or if I change the symbol to match the suggested currency (i.e. ETH)

### Expected behavior

We should be able to add other networks with the same chain id, even if the other network I already have in the wallet has a different currency symbol.

### Screenshots

https://github.com/MetaMask/metamask-extension/assets/54408225/9ef10d09-f49f-4eae-962b-e923b03d2317

### Steps to reproduce

1. Manually add a network with chainId 1, and a different symbol than ETH (i.e. ETH123)
2. Go https://chainlist.org/
3. Select Mainnet
4. Connect MM
5. Try to add another mainnet provider
6. Nothing happens. See error in the console

### Version

11.2.0 prod (possibly earlier)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
we don't want this to be closed

**Comment by anaamolnar** [comment]
Hey, @seaona Can you assign this to a team, please? Thanks!
