### ISSUE TITLE
[Bug]: Network toggles unaligned in Security and Privacy Settings

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#21430]
### Describe the bug

The ON/OFF toggles for networks in Security&Privacy Settings / Show incoming transactions are unaligned on the regular (unexpanded) extension view compared to the expanded view.

### Expected behavior

Toggles should be aligned.

### Screenshots

![image (1)](https://github.com/MetaMask/metamask-extension/assets/120041701/de02ffa8-4818-49b0-8651-b3838d6cdc16)

### Steps to reproduce

1. Open MetaMask extension
2. Fill in your password
3. Add multiple custom networks to the wallet with different name lengths
4. Proceed to Security and Privacy Settings
5. Scroll down to "Show incoming transactions" and notice the toggles are chaotically placed based on network's name length

### Version

11.4.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by kevinghim** [comment]
fixed via https://github.com/MetaMask/metamask-extension/pull/21370
