### ISSUE TITLE
[Sentry] [Bug]: Error prompt when speeding up or speeding up cancellation of a transaction

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#21453]
### Describe the bug

Error prompt shows in the console in these two cases:
1. Try to cancel a transaction and then speed up cancellation
2. Try to speed up a transaction but with a very low gas fee

### Expected behavior

No error prompt is shown.

### Screenshots

https://github.com/MetaMask/metamask-extension/assets/120041701/64b6910c-13ed-4662-935f-3faf54d61962

### Steps to reproduce

1. Open MetaMask
2. Fill in your password
3. Switch to a test network: e.g. Goerli
4. Proceed to the send flow
5. Send 0.1 ETH to an address: e.g. 0x3D0b9b4056D86f8d9889B2C8e26FFCedC62D3036
6. Edit the gas settings in Market --> Advanced: Max base fee to 0.0000001 and Priority Fee to 0.0000001
7. Confirm the transaction
8. Cancel the transaction
9. Speed up cancellation
10. Notice the error prompt in the console

Alternatively from step 7 (all previous steps executed the same):

7. Confirm the transaction
8. Speed up transaction with edited gas settings in Market --> Advanced: Max base fee to 0.0000001 and Priority Fee to 0.0000001
9. Save and submit the transaction
10. Notice the error prompt in the console

### Error messages or log output

```shell
SES_UNHANDLED_REJECTION: (Error#11)
Error#11: [ethjs-rpc] rpc error with payload
{"id":8003592214011,”jsonrpc":"2.0","params":
["0x0286c058202ee8459682008459682f1d825208942990079bcdee240329a520d2444386fc119da21a8080c08
0a0da085e57e8afff85ba16bfae10fe76£78e16604a6f273£68242e0ca47e7468a0a00e46f8685099e9200c1a0490
68375a82aa7e0695ccc022f2675a050c44027a98"
"method":"eth sendRawTransaction”} [object Object] 
e.<computed>		@	sentry-install.js:1
(anonymous)	@	sentry-install.js:1
logError	@	runtime-lavamoat.js:6791
logSubErrors	@	runtime-lavamoat.js:6734
error	@	runtime-lavamoat.js:6832
handleRejection	@	runtime-lavamoat.js:7131
finalizeDroppedPromise	@	runtime-lavamoat.js:6959
at chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-3.js:18:97991
 at a._handle (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-4.js:19:36247)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6813
logSubErrors @ runtime-lavamoat.js:6734
error @ runtime-lavamoat.js:6832
handleRejection @ runtime-lavamoat.js:7131
finalizeDroppedPromise @ runtime-lavamoat.js:6959
```

### Version

11.4.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by benjisclowder** [comment]
This could not be reproduced on older RC's. cc @danjm

**Comment by dbrans** [comment]
Fixed in develop. Related PR: https://github.com/MetaMask/metamask-extension/pull/21604
