### ISSUE TITLE
[Bug]: update metamask send_transaction 

### ISSUE THREAD

**Issue by luu-alex** [MetaMask/metamask-extension#21467]
### Describe the bug

https://docs.metamask.io/wallet/reference/eth_sendtransaction/
the metamask docs, send_transaction accepts `data` as calldata and not `input` within the transaction,
according to the updated [ethereum docs](https://ethereum.github.io/execution-apis/api-documentation/) it should be accept `input` within a transaction for calldata.

another thing:
metamask expects input on eth_call, but it expects data on eth_sendTransaction

### Expected behavior

when web3js uses send_transaction, `input` is populated not `data`.
a transaction with the `input` property should have callData populated in metamask, but does not.

### Steps to reproduce

look at spec above or i can provide more details if neccesary

### Version

11.0

### Build type

None

### Browser

Firefox

### Operating system

Windows, MacOS

### Additional context

would like to know your thoughts if u can change this to also accept `input`

**Comment by vandan** [comment]
Thanks for bringing this discrepancy to our attention. We will looking into it.

**Comment by jdevcs** [comment]
Thanks @vandan , This bug in metamask is effecting many web3.js v4 users, could you share with us when this will be fixed in metamask.

According to EL Specs:
https://github.com/ethereum/execution-apis/blob/057892b256c181232ca22499d1801b9637192698/src/eth/submit.yaml#L7C37-L7C55

https://github.com/ethereum/execution-apis/blob/main/src/schemas/transaction.yaml#L385

**Comment by vandan** [comment]
`eth_sendTransaction` is actually meant to be a wallet method.
See further details in our issue against the Ethereum Execution API repo: https://github.com/ethereum/execution-apis/issues/367

**Comment by vandan** [comment]
https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sendtransaction

**Comment by Muhammad-Altabba** [comment]
Hi @vandan,
Could you please, at least update MetaMask to accept if the `input` was passed; according to the Execution Layer documentation mentioned at https://github.com/ethereum/execution-apis/blob/main/src/schemas/transaction.yaml#L385 and https://ethereum.github.io/execution-apis/api-documentation/?
Thanks in advance,

**Comment by jdevcs** [comment]
> `eth_sendTransaction` is actually meant to be a wallet method. See further details in our issue against the Ethereum Execution API repo: [ethereum/execution-apis#367](https://github.com/ethereum/execution-apis/issues/367)

Above issue is still open and not fixed/merged into Ethereum Execution Layer Specs, also following now has `input` field :

> https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sendtransaction

EL Specs has some JSON RPCs for wallet functions in case if any EL client want to expose wallet functionality ( like under Eth Personal API ), 

I'll suggest to allow `input` field as well in metamask until EL Specs are doing it and https://github.com/ethereum/execution-apis/issues/363 is not concluded. and if its removed from EL Specs or updated after that you should update MM logic for it.  @vandan Thanks

**Comment by holic** [comment]
Any update on this? Just found this via https://github.com/MetaMask/metamask-extension/issues/21467
