### ISSUE TITLE
[Bug]: MaxUint256 ERC20 approval: Custom value is larger than u256.

### ISSUE THREAD

**Issue by paouvrard** [MetaMask/metamask-extension#21471]
### Describe the bug

Browser extension crashes with error when a dApp requests MaxUint256 ERC20 approval of a token with 24 decimals (for example NEAR)
No problem when approving a lower amount but most dApps request infinite approval so the token cannot be traded.
```
Message: Custom value is larger than u256
Code: Error
Stack:
Error: Custom value is larger than u256
  at a.getCustomTxParamsData (chrome-extension...)
```

### Expected behavior

Being able make an ERC-20 approve transaction and edit the ERC-20 approval amount even if the token has 24 decimals.

### Steps to reproduce

1. Go to https://app.1inch.io/#/1/simple/swap/0x85F17Cf997934a597031b2E18a9aB6ebD4B9f6a4
2. "Give permission to swap NEAR" will request MaxUint256 to be spendable and throw the MetaMask error described above.

### Version

11.2.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by DanielTech21** [comment]
Hi @paouvrard,
Thank you for reporting this bug. I will pass this on to the team to investigate this issue.

**Comment by sahar-fehri** [comment]
Hello @paouvrard ; I was able to swap NEAR; could you double check if this is still an issue? 🙏

**Comment by paouvrard** [comment]
Thank you, I can confirm it is fixed 👍
