### ISSUE TITLE
[Bug]: throw "response has no error or result for request" when call 'eth_requestAccounts' rpc method if metamask is locked

### ISSUE THREAD

**Issue by GinMu** [MetaMask/metamask-extension#21474]
### Describe the bug

when metamask is locked, i open a website and call "eth_requestAccounts" method, it throw "response has no error or result for request" error.

### Expected behavior

when i unlock metamask and get permitted accounts.

### Screenshots

![Screenshot 2023-10-20 at 17 08 54](https://github.com/MetaMask/metamask-extension/assets/12183493/9f31b889-3af1-4803-8b83-0bbc06a0eedb)

### Steps to reproduce

1. git clone https://github.com/GinMu/metamask-test.git
2. run `npm run serve`
3. lock metamask and open `http://localhost:8080/`

### Version

from latest git

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by DanielTech21** [comment]
Hi @GinMu 
Thanks for reporting this bug. I will pass this on to the team, who will further investigate it.

**Comment by GinMu** [comment]
Hi @DanielTech21
I found send [`METAMASK_EXTENSION_CONNECT_CAN_RETRY`](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/contentscript.js#L481) message and [json rpc middleware stream](https://github.com/MetaMask/json-rpc-middleware-stream/blob/main/src/createStreamMiddleware.ts#L129) process will retry this request, so that cause this issue.

**Comment by vandan** [comment]
We could not reproduce this issue. Can you provide OS, browser, and MetaMask browser extension version?

**Comment by GinMu** [comment]
@vandan 
OS: `macOS Sonoma v14.0`
browser: `Chrome Version 119.0.6045.105 (Official Build) (x86_64)`
metamask version: `development build from git id: a6a322e5`
