### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by BaronHusak** [MetaMask/metamask-extension#21477]
### Describe the bug

After transferring ether tokens to any network, an error occurs.Cannot read properties of undefined (reading 'map')

### Screenshots/Recordings

https://recordit.co/Hl3OKrMHNG

### Steps to reproduce

https://recordit.co/RPOUBrP5fu

### Version

MetaMask  2.99.3

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Windows

### Additional context

I use the Opera browser, but I also tried Google Chrome.

**Comment by anaamolnar** [comment]
I am closing this issue in favor of https://github.com/MetaMask/metamask-extension/issues/15009
