### ISSUE TITLE
[Bug]: `Snaps` word is bigger than the rest in the Truffle warning description

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21485]
### Describe the bug

**Problem**: in the deprecation warning for Truffle decoder, we see that Snaps word is bigger (`14px`) than the rest of the description text (`12px`)
Noted by @eriknson 

### Expected behavior

They should have the same text size

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/2283961f-a8ad-4623-92d3-8316d5e8564c)

### Steps to reproduce

1. Trigger a tx in mainnet
2. Click DATA tab
3. See warning and `Snaps` word bigger than the rest

### Version

11.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by FrederikBolding** [comment]
Closing as this UI has been removed regardless.
