### ISSUE TITLE
Fix flaky test "Multiple transactions creates multiple queued transactions, then confirms"

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#21488]
Frequency: **High** (6 times in the develop branch over the last 4 days)

Test file: `test/e2e/tests/multiple-transactions.spec.js`
Test name: `Multiple transactions creates multiple queued transactions, then confirms`
Test error message:
```
    message: 'Error: waitUntilXWindowHandles timed out polling window handles\n' +
      '    at Driver.driver [as waitUntilXWindowHandles] (test/e2e/webdriver/driver.js:407:9)\n' +
      '    at /home/circleci/project/test/e2e/tests/multiple-transactions.spec.js:64:15\n' +
      '    at hardfork (test/e2e/helpers.js:107:9)\n' +
      '    at Context.<anonymous> (test/e2e/tests/multiple-transactions.spec.js:13:5)',
```

Failed build: [link](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/60470/workflows/e8212a35-65ea-4ce9-a26d-67e1cdd8b838/jobs/1883435).

**Comment by chloeYue** [comment]
Close this ticket as the test is not flaky anymore
