### ISSUE TITLE
Fix and create a success e2e tests pipeline against mv3 build

### ISSUE THREAD

**Issue by DDDDDanica** [MetaMask/metamask-extension#21496]
- Filtering out tests are flakier in MV3 than MV2, 
- Not necessary need to fix flaky ones overlapping

**Comment by DDDDDanica** [comment]
Notes: Document the flakyness difference between mv2 and mv3 , and the blocker for mv3 release

**Comment by gauthierpetetin** [comment]
Notes: Snaps tests are currently failing and will have to be fixed once @brad-decker 's [ticket](https://github.com/MetaMask/metamask-extension/issues/17195) is finalised.

**Comment by DDDDDanica** [comment]
Updates: report on flaky e2e tests against mv3 build (excluding snaps)
A. MV3 only
Test Name: should show the correct private key for a second account from global menu
Failure Frequency: 252

Test Name: 'should display correct new account name after create' 
Failure Frequency: 252

Test Name: should not affect public address when using secret recovery phrase to recover account with non-zero balance @no-mmi
Failure Frequency: 252

Test Name: should be possible to remove an account imported with a private key, but should not be possible to remove an account generated from the SRP imported in onboarding @no-mmi
Failure Frequency: 252

B. Similar as MV2
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf8ed0ce5b24e063e148b5aacbb643ff21875f34/Screenshot%202023-11-02%20at%2002.08.52.png)

**Comment by DDDDDanica** [comment]
Updates: report on flaky e2e tests against mv3 build (excluding snaps)
A. MV3 only
Test Name: should show the correct private key for a second account from global menu
Failure Frequency: 252

Test Name: 'should display correct new account name after create' 
Failure Frequency: 252

Test Name: should not affect public address when using secret recovery phrase to recover account with non-zero balance @no-mmi
Failure Frequency: 252

Test Name: should be possible to remove an account imported with a private key, but should not be possible to remove an account generated from the SRP imported in onboarding @no-mmi
Failure Frequency: 252

B. Similar as MV2
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf8ed0ce5b24e063e148b5aacbb643ff21875f34/Screenshot%202023-11-02%20at%2002.08.52.png)

**Comment by DDDDDanica** [comment]
Top few after https://github.com/MetaMask/metamask-extension/pull/21672
```
  'should not have extra properties in UI state mask @no-mmi'                                                          │                                                        'Sentry errors should not have extra properties in UI state mask @no-mmi'                                                         │    72     │
│    1    │                                                                    'should capture UI application state'                                                                     │                                       'Sentry errors after initialization, after opting into metrics @no-mmi should capture UI application state'                                        │    72     │
│    2    │                                                                  'Connects to a Hardware wallet for trezor'                                                                  │                                                              'Import flow @no-mmi Connects to a Hardware wallet for trezor'                                                              │    72     │
│    3    │                                                            'should not show security alerts for benign requests'                                                             │                                           'Confirmation Security Alert - Blockaid @no-mmi should not show security alerts for benign requests'                                           │    72     │
│    4    │                                                                'should capture background application state'                                                                 │                                   'Sentry errors after initialization, after opting into metrics @no-mmi should capture background application state'                                    │    71     │
│    5    │                                                                          'should show banner alert'                                                                          │                                                    'PPOM Blockaid Alert - Malicious ERC20 Approval @no-mmi should show banner alert'                                                     │    69     │
│    6    │                                                                          'should show banner alert'                                                                          │                                                    'PPOM Blockaid Alert - Malicious ERC20 Transfer @no-mmi should show banner alert'                                                     │    69     │
│    7    │                                       'should capture migration log breadcrumbs when there is an invariant state error in a migration'                                       │         'Sentry errors before initialization, after opting into metrics @no-mmi should capture migration log breadcrumbs when there is an invariant state error in a migration' 
```

**Comment by legobeat** [comment]
This is currently failing on `develop`: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/82879/workflows/3fe572a0-a25c-4c11-bbbc-eeca61cada94/jobs/2959568
