### ISSUE TITLE
[Bug]: Metamask freeze

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#21509]
### Describe the bug

pretty fresh install on Arch Linux
browser : Chromium 118.0.5993.88
Metamask : 11.2.0 & 11.3.0

When going to "Settings" , Metamask freezes, does not accept clicks any more

### Expected behaviour

I view and change settings on the Settings page

### Steps to reproduce

Go To "Settings"
Metamask freezes, does not accept clicks any more

### Version

11.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by anaamolnar** [comment]
Hello, @SvenMeyer. Thanks for reporting! Is the behavior consistent after deleting cache and cookies and restarting your browser? Could you provide a screenshot of the console log errors when accessing the settings menu, where the extension freezes? Thank you!

**Comment by SvenMeyer** [comment]
![Metamask Settings freeze - Screenshot from 2023-10-24](https://github.com/MetaMask/metamask-extension/assets/25609/e341253e-b687-4cb7-aa90-77b3c95851b6)

Once this happended, I close Metamask and it would even pop up any more when clicking on the small icon

**Comment by anaamolnar** [comment]
Thanks @SvenMeyer. So it freezes on this menu, and you are unable to click on anything after? Or is it lagging and then comes back to normal?

**Comment by SvenMeyer** [comment]
@anaamolnar Yes, exactly as I already wrote above ...
- "Metamask freezes, does not accept clicks any more" (also no keyboard input into the search field)
- no just lagging, never comes back, even (see above) "Once this happened, I close Metamask and it would NOT even pop up any more when clicking on the small icon"

**Comment by SvenMeyer** [comment]
@anaamolnar I now evenr chromium accounts , and Metamask showed the same behaviour (at least I thought initially). `Settings` froze again and not knowing what to do , I just left it open ... and it came back to life after ~5 min !
I clicked a bit around, it worked for a couple of times, then froze again. Sometimes for 5 min, then for shorter times, then it worked again for a while ... :thinking: :man_shrugging: 

I created the new account within Chromium, installed the same extensions:
- chromium-extension-web-store 1.5.3.1-1 (then updated to 1.5.4)
- ublock Origin 1.52.2
- Metamask 11.3.0

I have NO idea if that has anything to do with it, just noticed that it loaded a lot of `data:image/png;base...` - see screenshot.

current browser version : `Version 118.0.5993.117 (Official Build, ungoogled-chromium) Arch Linux (64-bit)`

Anything else I can to/check ?

![Metamask - Chromium Console](https://github.com/MetaMask/metamask-extension/assets/25609/ee68b403-71a9-42d4-9f4d-a79e5e2cacf1)

![Metamask - Chromium Network](https://github.com/MetaMask/metamask-extension/assets/25609/b967ddd1-1ace-44ff-85fb-1f0dcd22a4dc)

**Comment by SvenMeyer** [comment]
Still no change after upgrading to 
`Version 119.0.6045.105 (Official Build, ungoogled-chromium) Arch Linux (64-bit)`
`Metamask 11.4.0`
Actually, with this combination it works for a few clicks before it froze again. Not sure if that was just a random coincidence though ...

**Comment by anaamolnar** [comment]
Hey @danjm, can you please take a look? 🙏

**Comment by SvenMeyer** [comment]
Tried again today with latest MM version.
- going to "Settings" page
- clicking on "Networks"
- nothing happens for ~ 5 min
- and only after these console messages show up, I can use the Setting page ... 

![image](https://github.com/MetaMask/metamask-extension/assets/25609/aae67023-1482-42e3-9a32-711ceb3b793e)

[nkbihfbeogaeaoehlefnkodbefgpgknn-1700572306811.log](https://github.com/MetaMask/metamask-extension/files/13426620/nkbihfbeogaeaoehlefnkodbefgpgknn-1700572306811.log)

**Comment by SvenMeyer** [comment]
also happens in incognito mode
