### ISSUE TITLE
[Bug]: not showing popup window of metamask

### ISSUE THREAD

**Issue by kriptobereli** [MetaMask/metamask-extension#21512]
### Describe the bug

not showing popup window of metamask

### Expected behavior

Popup window should open if there is any action, just showing action numbers on the pinned metamask icon

### Steps to reproduce

Open Brave browser
Go to Uniswap
Click to connect button

### Version

11.3.0

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by kriptobereli** [comment]
I tried below linked solution but didnt work

https://github.com/MetaMask/metamask-extension/issues/13590

**Comment by ZbrancaI** [comment]
Hey @kriptobereli! Thank you for reporting the issue! 

Is this behavior consistent whenever you receive a prompt in MetaMask?

**Comment by kriptobereli** [comment]
> Hey @kriptobereli! Thank you for reporting the issue!
> 
> Is this behavior consistent whenever you receive a prompt in MetaMask?

t doesn't display a pop-up window for any request. It simply shows the number of requests on the pinned icon.

**Comment by ZbrancaI** [comment]
@kriptobereli Got it! Did the issue start with the version 11.3 of the extension? 

Do you have any other crypto wallets installed on your browser? 

Also, please ensure your browser is updated to the latest version.

**Comment by kriptobereli** [comment]
Sorry, I'm not sure which version it began with, but I think it started about 2-3 weeks ago.

I have multiple wallets (like keplr, Polkadot, Petra, etc.), but even after disabling all the other wallets from the extensions page, the popup still doesn't appear.

I've made sure that all my extensions and the browser are up to date.

**Comment by kriptobereli** [comment]
![metamask issue](https://github.com/MetaMask/metamask-extension/assets/35870343/ea42f28b-4ede-4997-8649-95333d354a46)

**Comment by kriptobereli** [comment]
I have attempted a clean installation, but the issue still persists. It seems that my problem may require further investigation and support.

**Comment by PeterYinusa** [comment]
Hi @kriptobereli,

1. Can you confirm what version of Brave you are using?
You can find the version in the About Brave section after navigating to the following URL brave://settings/help

2. Do you have more than one monitor display currently connected to your computer/laptop?

**Comment by kriptobereli** [comment]
Brave is up to date
[Version 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)](https://brave.com/latest/)

Laptop monitor + from HDMI + sometimes also from USB Type C
Minimum 2 monitors, but sometimes 3 monitors I use

**Comment by kriptobereli** [comment]
> Brave is up to date [Version 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)](https://brave.com/latest/)
> 
> Laptop monitor + from HDMI + sometimes also from USB Type C Minimum 2 monitors, but sometimes 3 monitors I use

I tested it without external monitors and the popup is working. But when I connect an external monitor, the popup stops working.

**Comment by PeterYinusa** [comment]
> I tested it without external monitors and the popup is working. But when I connect an external monitor, the popup stops working.

Thanks for confirming, we're looking into a fix for this.
