### ISSUE TITLE
[Bug]: Unable to obtain chainId information

### ISSUE THREAD

**Issue by hhhyyy2001** [MetaMask/metamask-extension#21575]
### Describe the bug

ChainId switches chains on its own in the mobile version of MetaMask. I am unable to obtain information about the new exchange chain based on what I have written.

### Expected behavior

I should be able to obtain the chainId and use it to determine.
TokenPocket and BitgetWallet have now been adjusted to jump to separate modules, prohibiting users from switching wallet chains

### Steps to reproduce

1. Open MetaMask.
2. After logging in, open the browser.
3. Log in to a website that can link to the chain.
4. Log in and use their company's chain, then switch to another chain in the MetaMask wallet.
After testing, their company's chain did not match MetaMask's chain, resulting in the website being unusable.
After debugging, I found that your company did not transmit ChainId at all

### Version

MetaMask v7.3.1(1156)

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by ZbrancaI** [comment]
Hey @hhhyyy2001 !

Thank you for reporting this! I will pass this on to the team!

**Comment by vandan** [comment]
We need more information about the specific setup and detailed reproduction steps to investigate this issue. Code examples would help.
