### ISSUE TITLE
Is Metamask down? unable to send ETH

### ISSUE THREAD

**Issue by welshmentrader** [MetaMask/metamask-extension#2160]
Currently getting the same error, i have already uninstalled and installed metamask again

 
![meta error](https://user-images.githubusercontent.com/32241141/30782961-31a7722e-a133-11e7-9a54-ac5f622852e1.PNG)

**Comment by raizla** [comment]
I'm getting the same error.

**Comment by drreen** [comment]
Same issue

**Comment by basit121** [comment]
i am getting same issue! tried it like 30 times ! v frustrating ! can someone let me know if it now working

**Comment by demmersong** [comment]
@flyswatter

**Comment by jesusperezsanchez** [comment]
Me too!!

**Comment by jesusperezsanchez** [comment]
Could be a pishing?

**Comment by welshmentrader** [comment]
Same issue for everyone by the looks of it. The only way round it is to use your metamask private key with your MEW wallet

**Comment by roesaysgo** [comment]
following

**Comment by roesaysgo** [comment]
Hey, just tried a transaction and it went through no problem. thanks for your help

**Comment by tmashuang** [comment]
The issue with the network provider has been resolved, comment if there is still an issue.

**Comment by mujtabaidrees94** [comment]
Hi Still facing same issue..

**Comment by danfinlay** [comment]
If you have an issue using MetaMask, please email our support team at support@metamask.io
