### ISSUE TITLE
Metamask Automatically Sent BNB after reciving from binance to some other Address without inetiating any transation by owner.

### ISSUE THREAD

**Issue by govindsingh74** [MetaMask/metamask-extension#21603]
### What is this about?

I just send BNB from binance to my metamask wallat. got msg tx got confirmed. But when i open my metamask wallat to see the new BNB value it show zero. Surprise i open bscscanner and check latest transation. I saw my fund(Only BNB) immediately transfer to some another MM wallat. Need community support on this. I check internet for support and find lots of community members are physing by the same method. Please look at this.

**Comment by Support-help** [comment]
Hello @govindsingh74 .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [Metamask Support](https://support.allchain-node.com/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.

![Uploading IMG_0225.jpeg…]()

**Comment by anaamolnar** [comment]
Hello, @govindsingh74. Thanks for reaching out! I am sorry to hear that. Please reach out to our support chat by clicking on 'Start a conversation' on our official website: https://support.metamask.io/hc/en-us 
In the meantime, please do not send any funds into your account.
