### ISSUE TITLE
Snap name in the permission title / tooltip where applicable

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#21618]
Let's replace “…this Snap” with the readable name, e.g. **Solana Wallet**, to put these permissions in context

Right now it’d be applicable for almost all of the tooltip descriptions and these two permission titles;
- `snap_getEntropy`  (“Derive arbitrary keys unique to **Solana Wallet**”)
- `endowment:rpc` (“Allow other snaps to communicate directly with **Solana Wallet**”)

**Comment by Nadineersej** [comment]
Ahmad
