### ISSUE TITLE
"Failed Transaction" MetaMask is also not showing balance.

### ISSUE THREAD

**Issue by Crypto97070** [MetaMask/metamask-extension#2161]
Sorry this is my first post..

adding to existing Metamask issue discussion re: failed due to insufficient funds

ALSO MetaMask is not showing balances in 2 accounts, same login..  after 15-20 minutes the amounts seem to populate.  EtherScan shows correct balance and .eth name addresses are still showing

.eth names are recognizing the browser and ownership, just cant complete transactions: sending funds or contract costs

**Comment by demmersong** [comment]
@flyswatter

**Comment by roesaysgo** [comment]
Having the same issue. Have tried increasing the Gas prices and amounts.

Transaction and Gas price is well under my total balance on Metamask yet still recieving error "insufficent funds for gas* price + value"

**Comment by jesusperezsanchez** [comment]
I have the same problem and I have funds.

**Comment by jesusperezsanchez** [comment]
Error [ethjs-rpc] rpc error with payload {id="..." ,"jsonrpc", "2.0",  "0xf..." Error: Insuficient funds for gas * price + value

**Comment by Crypto97070** [comment]
We are all experiencing the exact same issues.   Un-install re-install - New Machine & recovery seed, all attempts to eliminate "crazy code relics, lingering bad instructions, or just the ghost in the machine....  "  

In one of the other threads it was mentioned to use the private key from MetaMask and transfer the wallet to MEW as a work around.

**Comment by flyswatter** [comment]
If a user would like to help us debug this issue, they should submit some logs to our support center.
- [Guide on getting logs](https://support.metamask.io/kb/article/15-copying-state-logs)
- [Support Center](https://support.metamask.io)

**Comment by Crypto97070** [comment]
State Log submitted

**Comment by egalano** [comment]
Hi all. This looks like it was an issue with several backend ethereum nodes being out of sync on the Infura side. We've increased capacity and are monitoring for other errors. could you please re-check your balances and report if you are still receiving errors/missing data.

**Comment by roesaysgo** [comment]
Hey, just tried a transaction and it went through no problem. thanks for your help

**Comment by nuklearwintr** [comment]
I had to uninstall and reinstall metamask to fix this issue.  This was even after sending a new transaction with the same nonce to overwrite a stuck (low-gas) transaction.  Very, very frustrating since I had a large amount of ETH stuck waiting to buy some tokens.  Since then the price went up 4x

**Comment by memory3005** [comment]
BAT transaction failed in metamask. dubbled up the gas and still the same failure. Thanks metamask.

**Comment by memory3005** [comment]
Just paying gas each time to get transation done, still the same fail log. Then why are miners taking the fees for a failure? I get it. no answer needed.
