### ISSUE TITLE
Token list displaying incorrect value

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#2162]
I have 0.00000000000027929 OMG tokens but MetaMask shows me as having 0.279 OMG tokens.

Steps:
1. Acquire 0.00000000000027929 OMG tokens.
2. Add the OMG token (`0xd26114cd6EE289AccF82350c8d8487fedB8A0C07`) to MetaMask with 18 decimals.
3. Notice that MetaMask shows you having 0.279 OMG tokens.

This problem is currently visible for account `0xA3e9CF840BBe40F1599D434d460C7E5f2DC64279`.

![image](https://user-images.githubusercontent.com/886059/30784581-b42245fc-a10c-11e7-9fa7-ecd0851d384f.png)

**Comment by flyswatter** [comment]
Notes:

- Micah has `2179663820576` OMG tokens at time of reading.
- Etherscan renders this as `0.000002179663820576 OMG`.
- In the picture it shows .205 OMG
- That actual balance *does* have the numbers `205` in it, so that might suggest what the error is.

Will fix soon.

**Comment by flyswatter** [comment]
Ok I just added [a test for this precision](https://github.com/MetaMask/eth-token-tracker/blob/master/test/token-precision.js#L63-L71) and it doesn't give the displayed output.

Is it possible you initially put the OMG tokens in with the wrong precision, @MicahZoltu?

It could help debug this from the state. To give partial state, you could open the inspector on the UI and type `JSON.stringify(JSON.parse(logState()).metamask.tokens)`. That will give us your configured tokens and their precisions, we could see if maybe yours got saved with the wrong precision.

**Comment by MicahZoltu** [comment]
I added the OMG token with 18 decimals and originally (when I had > 1 OMG token) it correctly displayed my tokens.  I then transferred most of the tokens out (I thought all of the tokens, but apparently not) and now it displays the incorrect value.

Result of state: `[{"address":"0xd26114cd6ee289accf82350c8d8487fedb8a0c07","symbol":"OMG","decimals":"18"}]`
