### ISSUE TITLE
[Bug]: "Terms of use" link for blockaid is broken

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#21684]
### Describe the bug

When i click the "Terms of use" link for blockaid, the opened tab shows page not found.

<img width="591" alt="Screenshot 2023-11-03 at 17 08 30" src="https://github.com/MetaMask/metamask-extension/assets/105063779/9a6ab964-b9b6-489a-9800-c9fd4950fd7a">
<img width="1905" alt="Screenshot 2023-11-03 at 17 08 22" src="https://github.com/MetaMask/metamask-extension/assets/105063779/495ea757-b8b2-4af2-ba26-3a1fb73fb805">

### Expected behavior

Terms of use should show in new tab.

### Steps to reproduce

1. Go to Settings, select experimental tab.
2. Click the terms of use link for blockaid section. 
3. See page not found error.

### Version

11.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Tushar-2003** [comment]
Hey, I would like to work on this, can you assign this to me?

**Comment by seaona** [comment]
This issue was mentioned [here](https://github.com/MetaMask/metamask-extension/pull/21466#discussion_r1371330454) and it needs to be fixed on Blockaid side, not MetaMask side (the URL is correct). I can update this ticket when we get more news

**Comment by danjm** [comment]
@Tushar-2003 thanks for your interest in contributing to MetaMask! This ticket needs to involve work with engineers outside of MetaMask, and so is not a great ticket for community contributors such as yourself. Instead you might want to look at issues listed here https://github.com/MetaMask/metamask-extension/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by bschorchit** [comment]
Update: we should remove "Terms of Use" copy from Blockaid's option
