### ISSUE TITLE
[Bug]: Incorrect selected Network displayed on Approve screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21694]
### Describe the bug

**Problem:** whenever I have a custom network with the same chain ID as one of the pre-default ones (i.e. Mainnet), if I trigger an Approve transaction from a Dapp, I can see how the displayed network on the Confirmation screen is the pre-defualt one, instead of the custom one that I have selected. Affected screens:
- Approve ERC20
- Approve ERC721
- SetApprovalForAll ERC721
- Revoke ERC721

### Expected behavior

We should display the custom selected network name

### Screenshots/Recordings

See on top, the selected network is the custom network `main tend` but in the Confirmation screen is displayed `Ethereum Mainnet`

![Screenshot from 2023-11-06 09-51-24](https://github.com/MetaMask/metamask-extension/assets/54408225/b2cf3c95-bb5c-40b7-a74f-4053b3f5863a)

https://github.com/MetaMask/metamask-extension/assets/54408225/159cfcf2-6419-4f5e-bf8c-3ad459fc8128

### Steps to reproduce

1. Add a custom Mainnet network, with a custom name i.e. create a mainnet in Tenderly https://dashboard.tenderly.co/ 
2. Select the custom network
3. Go to this contract https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#writeProxyContract
4. Connect MMM
5. Click Approve
6. Add any address and amount and confirm
7. See Confirmation screen displays `Ethereum Mainnet` instead of your custom network

### Version

11.4.0 prod, possibly earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
we don't want this to be closed

**Comment by desi** [comment]
The issue no longer applies as we have consolidated a single network name for each chain id even if the user has multiple rpcs and this name is what is displayed on confirmations. Leaving as closed.
