### ISSUE TITLE
[Bug]: AddNFT (wallet_watchAsset) NFT Image doesn't show

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-extension#21701]
### Describe the bug

Using `wallet_watchAsset` for adding NFTs, there seems to be an issue with displaying those NFTs within MetaMask Extension. The confirmation modal displays the NFT, but when you go into the NFT tab and view the NFT (ON Linea and Mumbai testnets) the image is blank.

### Expected behavior

I expect that once I add the NFT using the `wallet_watchAsset` api using the following code:

```
try {
      await window.ethereum?.request({
        method: 'wallet_watchAsset',
        params: {
          type: "ERC721",
          options: {
            address: contractAddress,
            tokenId: tokenId
          }
        }
      })
    } catch (err: any) {
      console.error(err.message)
    }
  }
  ```
  
Once the confirmation and NFT is added, I should be able to view the NFT within the MetaMask NFTs tab.

### Screenshots/Recordings

Here is a video of the issue. Notice at the end after adding the NFT that the image is blank:

https://github.com/MetaMask/metamask-extension/assets/4899480/e190d253-a6bb-44e6-95ca-5f5c71e0f4be

### Steps to reproduce

1. Create an NFT and deploy to Linea or Mumbai Testnet
2. Call a function that passes the correct information to the `wallet_watchAsset` RPC API endpoint
3. Accept the Confirmation modal
4. View the NFT in MetaMask NFT tab.

### Error messages or log output

```shell
No errors occurred.
```

### Version

11.3.0-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

### Severity

- This is a UX issue
-  Severity is not high as it does add the NFT
- The issue is mostly around the user not being able to visually see their NFT added.

**Comment by adonesky1** [comment]
Pretty sure [this change](https://github.com/MetaMask/core/pull/1772/files) has caused this issue. @pedronfigueiredo 
 I'm not sure I understand the logic of this bit:

 ```
const isDisplayNFTMediaToggleEnabled = this.config.openSeaEnabled
```

Or atleast the setting should be called something else. We often get the NFT metadata directly from the chain - not just from OpenSea. The way this is set up now ties the OpenSea API toggle to whether we show any NFT media at all. We should rename this preference to Show NFT Media (or Load NFT Metadata) And we may need to toggle it on by default otherwise people might be confused when their NFT images stop showing up.

**Comment by adonesky1** [comment]
Also one problem of this logic where it is is that we currently have no way for the user to refresh the metadata (something I've been saying we should do for a while) and so if the user has this setting toggled off when they add the NFT there is no way for them to get the media to show up unless they remove it, toggle on the setting and re-add the NFT

**Comment by httpJunkie** [comment]
Perfect this helped and I will be sure to include coverage of that setting in my demos.

**Comment by httpJunkie** [comment]
This is not a bug as Alex has stated. I just needed to update my Settings > Security & Privacy > Display NFT media and toggle it to "ON".

NOTE: When this feature is ON.... 
Displaying NFT media and data exposes your IP address to OpenSea or other third parties. This can allow attackers to associate your IP address with your Ethereum address. NFT autodetection relies on this setting, and won't be available when this is turned off.
