### ISSUE TITLE
[Bug]: Breaking Changes; Metamask infinite load; Cannot be used any longer

### ISSUE THREAD

**Issue by tdev00** [MetaMask/metamask-extension#21719]
### Describe the bug

MetaMask displays an infinite loading spinner without end.

### Expected behavior

MetaMask should display all the wallets after entering credentials.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/63981572/c4eaa267-ec89-4b85-88fc-a8390e2997b5)

### Steps to reproduce

**Steps to reproduce the issue:**

- Load Chrome browser
- Click on MM extension
- MM doesn't load/infinite spinning wheel

**I attempted the following steps, but none resolved the issue:**

- Cleared the browser cache and cookies.
- Closed the browser completely and restarted the PC.
- Disabled the VPN.
- Tried to remove the loading overlay via CSS to access the settings.
- Ensured the extension's access is set to "On all sites."
- Attempted to open the extension in incognito mode.
- Updated Chrome. Current version: 119.0.6045.106 (Official Build) (64-bit)

**_Please note that this issue does not exist on Brave browser_**
**_Please also note that re-installing the extension is not feasible for individuals with multiple wallets_**

### Error messages or log output

```shell
After turning on Chrome extensions "Developer mode", then clicked on "background.html", I see this:

`Error#373: PollingBlockTracker - encountered an error while attempting to update latest block:
{
  "code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": -32010,
    "message": "Public RPC endpoints at gateway.pokt.network are deprecated as of November 1 2023. For continued service please use Pocket's new public endpoints at https://docs.pokt.network/use/public-rpc."
  },
  "stack": "Error: Internal JSON-RPC error.\n    at new i (chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/common-3.js:16:10940)\n    at s (chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/common-3.js:16:13880)\n    at Object.internal (chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/common-3.js:16:14490)\n    at u (chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/background-0.js:7:49968)\n    at chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/background-0.js:7:50970\n    at async chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/common-4.js:19:37935"
}
  at new i (chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/common-3.js:16:10940)
  at s (chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/common-3.js:16:13880)
  at Object.internal (chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/common-3.js:16:14490)
  at u (chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/background-0.js:7:49968)
  at chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/background-0.js:7:50970
  at async chrome-extension://nkbghyukfkoogamvc3lefnkodbefgpgtee/common-4.js:19:37935
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6791
logSubErrors @ runtime-lavamoat.js:6734
error @ runtime-lavamoat.js:6832
error @ runtime-lavamoat.js:11750
_synchronize @ background-2.js:19`
```

### Version

11.4.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Closing this in favor of https://github.com/MetaMask/metamask-extension/issues/21598

**Comment by danjm** [comment]
This was fixed in https://github.com/MetaMask/metamask-extension/pull/21854, which will be in v11.5.1

v11.5.1 was submitted to chrome yesterday, so hopefully it will be available to users some time today. I will comment here again once it is available to users
