### ISSUE TITLE
[Bug]: Editing gas fees in advanced settings is faulty, the zero value cannot be deleted

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#21724]
### Describe the bug

When you try to edit the gas fees, the zero is impossible to delete and every value you type will go after the zero. You need to place the value behind the zero and then delete the zero to make it work. 

### Expected behavior

The zero should be removable/replaced by other values

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/82a7aeea-dbe5-4351-bbf9-6d79c8a69227

### Steps to reproduce

1. Log into MetaMask
2. Fill in your password
3. Switch over to a test network (e.g.: Sepolia)
4. Head over to the test dapp: https://metamask.github.io/test-dapp/ and connect the MM account
5. Proceed to send eip-1559 transaction
6. Go to site suggested --> Advanced --> Attempt to change the gas fees and notice the zero is non-removable and every other value is added. after the zero

This is also a problem in the regular send flow with edited gas fees.

### Version

11.5.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by danjm** [comment]
I found that this same behaviour exists on earlier versions as well, including v11.4.0 and v11.1.0

So I am going to remove the 11.5.0 related labels

**Comment by adrigug** [comment]
@benjisclowder - i was able to reproduce these steps using MM extension v12.9.2. See the recording below reproducing the issue.

https://github.com/user-attachments/assets/0e41575e-40aa-4269-95b1-3f5b562117b0

**Comment by pedronfigueiredo** [comment]
This has been fixed on https://github.com/MetaMask/metamask-extension/pull/28869 which will go into v12.10
