### ISSUE TITLE
MetaMetricsId shall not change when user opts-in, then outs-out, then opts-in again

### ISSUE THREAD

**Issue by gauthierpetetin** [MetaMask/metamask-extension#21728]
### What is this about?

`metaMetricsId` shall not change when user opts-in, then outs-out, then opts-in again.

This is already implemented in Mobile and shall now be implemented in Extension as well.

### Scenario

- GIVEN As a User, I am opt-in to MetaMetrics
- AND My metaMetricsId is equal to "xyz"
- WHEN I go in the settings to opt-out from MetaMetrics
- AND I opt-in again to MetaMetrics
- THEN My metaMetricsId is still equal to "xyz"

### Technical Details

- metaMetricsId shall not be erased [here](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/metametrics.js#L459)

### Threat Modeling Framework

- We need to be careful about anywhere where we reference metaMetricsId without checking the optin status.
- This could result in a change in our number of MAUs.

### Acceptance Criteria

- See "Scenario" section
- + we need to make sure metaMetricsId is not used anywhere without the optin status being set to true
- + ensure that the metaMetricsId being `null` is never used in the decision to send or not an event

### Testing plan

- Add an E2E test where user toggles on, then off, then on again and confirm metaMetricsId is unchanged

### References

- [Discussion in metamask-attribution Slack channel](https://consensys.slack.com/archives/C0573UE7J1H/p1698915603546629)
- [Discussion in metamask-dev Slack channel](https://consensys.slack.com/archives/G1L7H42BT/p1699271759633729)

**Comment by brad-decker** [comment]
Prior art: https://github.com/MetaMask/metamask-extension/pull/16744
