### ISSUE TITLE
[Bug]: `No metadata found for 'networkId' ` when changing networks after a wallet upgrade

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21737]
### Describe the bug

**Problem**: whenever I switch to another network I see the following background error. This happens after performing a wallet upgrade.

![Screenshot from 2023-11-08 10-08-56](https://github.com/MetaMask/metamask-extension/assets/54408225/3a9ee032-60f9-4450-9f66-388a95dc2621)

### Expected behavior

No error should appear

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/c2f53a1e-586d-4f85-a376-c3d765b797d0

### Steps to reproduce
1. Checkout branch Version-v11.4.1
2. Unlock the wallet
3. Now migrate to develop branch (re-build and re-start)
4. Open background console
5. Change networks
6. See error in background console

Now everytime you change networks you will see the error.

Video with repro steps (a bit long since it builds the wallet)

https://github.com/MetaMask/metamask-extension/assets/54408225/9b1da174-9a03-438b-a050-311f324ffd62

### Version

migrating from `11.4.1` to develop (maybe earlier issue)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Gudahtt** [comment]
We are still seeing this error in Sentry, but I'm unsure if it has the same cause as originally in this report (or whether it's related to an upgrade).

Closing in favour of this new issue which we're using to consolidate any remaining related Sentry errors: #26297
