### ISSUE TITLE
[Bug]: After triggering a Signautre, metrics events are sent non-stop until I confirm/cancel it

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21738]
### Describe the bug

**Problem**: whenever I trigger a signature, I can see how instead of 1 metrics event, they are sent infinetly events, until I close/confirm the signature.

This might be caused by to this PR, trying to capture the RPC requests https://github.com/MetaMask/metamask-extension/pull/21482/files

### Expected behavior

Just 1 request should be sent after an action

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/3987e53c-40b8-4a84-b14d-be3ef620e29b

### Steps to reproduce

1. Open Segment on one window
2. Start metamask
3. Enable blockaid
4. Select mainnet
5. Trigger any signature
6. See events sent non stop

### Version

11.5.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by segun** [comment]
I found this issue while working on an e2e metric, so I fixed it in this PR 
https://github.com/MetaMask/metamask-extension/pull/21708/files#diff-23ba5982fcc93dd2ef18d2889fe480da559dda4137e155f7f46edb793463d1b7

cc @blackdevelopa
