### ISSUE TITLE
[Bug]: javascript console error

### ISSUE THREAD

**Issue by HeavySnowJakarta** [MetaMask/metamask-extension#21734]
### Describe the bug

the same as #20847.

![image](https://github.com/MetaMask/metamask-extension/assets/54460050/eb244cf9-47a7-4d6f-94ac-40ec17a1425a)
![image](https://github.com/MetaMask/metamask-extension/assets/54460050/2bc0e4b2-246e-400c-8fff-8e6cdf7adebf)

### Steps to reproduce

visit spacedrive.com with metamask enabled

### Version

11.4.1

### Build type

None

### Browser

Microsoft Edge

### Operating system

Windows

**Comment by DDDDDanica** [comment]
Hey @HeavySnowJakarta thanks for reporting this issue. I just took a quick look at latest (11.4.1) extension in edge with **_mac_,** and i visited spacedrive with MM enabled. However, i didn't have any issue when visiting (see attachment), can you give us a bit more details about what actions did you execute, or even provide a recording, which would be very helpful for us to identify the issue. Thank you ! 
<img width="1782" alt="Screenshot 2023-11-14 at 01 35 31" src="https://github.com/MetaMask/metamask-extension/assets/12678455/11d16306-5ba7-4639-a2aa-2a40251ee114">

**Comment by HeavySnowJakarta** [comment]
I'd like to provide any kind of details you need. How do I get the info or logs?

**Comment by DDDDDanica** [comment]
Hey @HeavySnowJakarta if possible, a screen recording with you installing MM and opening spacedrive and connect MM would be sufficient.

**Comment by HeavySnowJakarta** [comment]
like this?
![image](https://github.com/MetaMask/metamask-extension/assets/54460050/d081ab71-0e68-4d2f-bf29-75ba06e5aa26)

**Comment by HeavySnowJakarta** [comment]
> Hi @HeavySnowJakarta could you please send us a screen recording (using a tool like https://recordit.co/ or similar) with you installing MM and opening spacedrive and connect MM.

Thank you for your concern. I'm sorry that after I restored Windows the problem disappeared. I can't reproduce the problem as well as telling why. Before that I disabled Metamask to prevent it.

**Comment by gauthierpetetin** [comment]
No worries, thank you @HeavySnowJakarta
