### ISSUE TITLE
Create ConfirmInfo to display confirmation content

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#21747]
### What is this about?

Create ConfirmInfo 
- Consider reutilizing Card component (not a DS component)
- Could use DS Box component with background + border-radius
- This would likely not have inner padding

Create ConfirmInfoSection
- used to separate component parts with border e.g. add border bottom to all sections except for the last section and if it is also not the first section
- consider inner padding here or on the ConfirmInfoRow level (see [ConfirmInfoRow PR](https://github.com/MetaMask/metamask-extension/pull/19957/files))

### Design

<img width="314" alt="Screenshot 2023-11-08 at 5 42 05 PM" src="https://github.com/MetaMask/metamask-extension/assets/20778143/65554413-a2f9-4b38-93df-2b8ca96ad559">

### Technical Details

- Please use the proposed [file structure](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#b504b50ddc1842d08d61a85cf7bc3160) while designing this component
- Refer to component [checklist](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#f43a74be4bfa424c87206b0a97a51ea2)

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21747?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun
