### ISSUE TITLE
Create multiple transaction navigation header

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#21741]
### What is this about?

For the new confirmation pages, we will want to support the feature to navigate through multiple transactions. The new confirmation pages will have new UI

Reject Button itself will be handled by this ticket: Relates to: https://github.com/MetaMask/metamask-extension/issues/22744

### Design

![image](https://github.com/MetaMask/metamask-extension/assets/20778143/68418616-5772-488e-8c7c-9f0a0ccdd154)

### Technical Details

- Design: [Figma](https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=982-45793&mode=design&t=UXL4JzT6G9DcDYVQ-0)
- We can utilize [DS HeaderBase](https://metamask.github.io/metamask-storybook/?path=/docs/components-componentlibrary-headerbase--docs) to support this header
- Please use the proposed [file structure](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#b504b50ddc1842d08d61a85cf7bc3160) while designing this component
- Refer to component [checklist](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#f43a74be4bfa424c87206b0a97a51ea2)

We may consider how this works alongside the account header below

**Comment by bschorchit** [comment]
Only the top one in design is in scope - @SayaGT to confirm

**Comment by bschorchit** [comment]
We might consider this out of scope for personal sign effort being pursued in Q4

**Comment by bschorchit** [comment]
This might have been completed already
