### ISSUE TITLE
[Bug]: Approving an ERC721 token does not display the token collection name

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21756]
### Describe the bug

**Problem:** whenever we are approving an ERC721 token, we can see how the collection name is not displayed.

### Expected behavior

The collection name should be displayed in the same way it's done for Set Approval For All / Revoke screens.

### Screenshots/Recordings

Approve screen, not displaying the collection name but `this collection` fallback
![Screenshot from 2023-11-08 18-26-52](https://github.com/MetaMask/metamask-extension/assets/54408225/a6ced5e0-2ee1-4e6f-a9a4-a622821ba267)

Expected: like in Set Approval for all screen, the collection name is correctly displayed

![Screenshot from 2023-11-08 18-27-05](https://github.com/MetaMask/metamask-extension/assets/54408225/842e1af3-5acf-4e5e-a9fa-84f85002ff55)

### Steps to reproduce

1. Go to the test dapp https://metamask.github.io/test-dapp/
2. Deploy an NFT ERC721 token
3. Mint tokens
4. **Watch the NFT** -- this is the key step - if the token is not added, you will see the collection normally
5. Click Approve, see collection name is not displayed, but `this collection` instead
6. Click Set Approval for all, see here collection name is correctly displayed

https://github.com/MetaMask/metamask-extension/assets/54408225/312236ae-39e1-47b5-a5ee-6c28039d3ddd

### Version

11.5.0 - not happening on 11.4.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by salimtb** [comment]
Related [#1813](https://github.com/MetaMask/metamask-extension/issues/18133)

**Comment by salimtb** [comment]
hello @seaona ,
i just did the tests locally and in production and i was not able to reproduce it , can you pls give the contract address

**Comment by seaona** [comment]
You need to add the token to the wallet (watch NFT) before the Approve. If the token is **not ** in the wallet, the collection name is displayed correctly.
I'll add this step in the description as I missed it :pray:  hopefully you can repro now
