### ISSUE TITLE
[Bug]: `TypeError: cb is not a function` when speeding up or cancelling a transaction

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21754]
### Describe the bug

**Problem:** whenever I speed up or cancel a transaction I see the following background console error `TypeError: cb is not a function` from the JsonRpcEngine

### Expected behavior

No errors should appear

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/3cd9dd9e-2225-4521-9373-a0f1a1b3b421

### Steps to reproduce

1. Submit a tx
2. Speed up or cancel
3. Check background console

### Version

11.5.0 - not happening on 11.4.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by OGPoyraz** [comment]
Hey @seaona, I believe this is fixed [in this commit](https://github.com/MetaMask/metamask-extension/pull/21604/files/668054d989843814da2ee7c2fe7767a05487d703#diff-57e38278f8e09d93b0037ed8fdc648d9c9601a67854a17c454bd5b3ac1d94c3dR24) which is not applied in the 11.5.0.

I've cherrypicked and recorded a speed-up and cancel transaction flows here for you to check. 

https://github.com/MetaMask/metamask-extension/assets/7644512/d16b41f9-60a1-468e-8c2b-3771108bec3c

**Comment by sleepytanya** [comment]
Just adding more evidence.
`t is not a function error` appears every time when `cancelling/speeding up`the transaction (Chrome 11.5.1):
<img width="492" alt="Screenshot 2023-11-20 at 4 39 16 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/67214c85-49b8-4229-a782-9257683127a6">
After `speeding up the cancelation` error message appears in the `General Settings`:
<img width="927" alt="Screenshot 2023-11-20 at 4 48 13 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/e879b42a-8c44-4369-8fd2-11d15e4af839">

**Comment by OGPoyraz** [comment]
Hey @sleepytanya, I just checked with current dev version (`11.7.1`) and error is not appearing on my end while cancel or speeding up the tx. Can you please confirm for the last time if this issue still persist or not?

**Comment by sleepytanya** [comment]
@OGPoyraz I don't see the error while cancelling / speeding up with the 11.7.1:


https://github.com/MetaMask/metamask-extension/assets/104780023/3ecbf96c-60cd-497b-bb61-0f739189ec73

**Comment by OGPoyraz** [comment]
Perfect, I am closing this then!
