### ISSUE TITLE
Create ConfirmInfoRow components to support key/values

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#21751]
### What is this about?

Create a resuable row component that may be used as a wrapper for other row components. This supports various row states and shared styles.

### Design

![Screenshot 2023-11-08 at 7 15 23 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/f06bf6fc-ba11-4724-afac-36d9862e2315)

### Technical Details

- See [Info (Key/Value) section](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#daefd38bbf804cfb99a75b97edab0730) in Architecture Proposal
- Please use the proposed [file structure](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#b504b50ddc1842d08d61a85cf7bc3160) while designing this component
- Refer to component [checklist](https://www.notion.so/Confirmation-UI-UX-Redesign-c99de275e5914a27a5a578faf9aa6069?pvs=4#f43a74be4bfa424c87206b0a97a51ea2)

### References

- Fixed by https://github.com/MetaMask/metamask-extension/pull/19957/files

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-extension/pull/19957 has been merged. 
Please do re-open if this is not correct, @digiwand (I assumed from the Fixed by note in description)

**Comment by digiwand** [comment]
reopening to do a slight refactor https://github.com/MetaMask/metamask-extension/pull/22096
