### ISSUE TITLE
[Bug]: Scanning QR in send flow from ios mobile client receive results in `Recipient address is invalid` error

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#21766]
### Describe the bug

If I attempt to scan a QR code from extension in the send flow, of the receive address we present from the mobile client, an`Recipient address is invalid` error is produced.

Observed with Mac OS sonoma and chrome 117.0.5938.92
Observed in 11.4.0 and confirmed as far back as 10.17.0, and may be even older.
Mobile device was iPhone XS running iOS 17.0.3 and mobile client 7.7.0 build 1171 and 7.10.0 build 1187

QR code presented from mobile receive is in the format`ethereum:PUBLICADDRESS@1`

### Expected behavior

Extension user should be able to scan QR code in send flow from mobile receive without error.

### Screenshots/Recordings

<img width="376" alt="Screenshot 2023-11-08 at 10 56 39 PM" src="https://github.com/MetaMask/metamask-extension/assets/32695229/d4c89e7c-1489-496e-b6e9-0df74ae3ce27">

### Steps to reproduce

1. Have both a mobile wallet and extension configured
2. From wallet view in mobile tap the send and receive button in at the bottom middle of the page
3. Select `Receive` and QR is presented
4. From extension tap send
5. Tap QR scanner in address field
6. Grant camera permissions as requested
7. Hold mobile QR up to camera
8. Note error

### Error messages or log output

```shell
Recipient address is invalid
```

### Version

10.17.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
@segun mentioned it seems this was introduced with https://github.com/MetaMask/metamask-mobile/commit/6697afbe7d671ef0f43fb115c5b25387fe57989d . @frankvonhoven would you mind taking a look on this issue? Ty!

**Comment by plasmacorral** [comment]
This issue still exists with mobile 7.19.1 (build 1306) and extension 11.13.1.

I also notice that when many accounts are present in extension that the error is presented at the bottom of the account list.  If the user doesn't scroll down to see it, it seems like extension is simply ignoring the user attempt to scan a QR.

https://www.loom.com/share/e19fdd6be63447dc88cc6bf57f32f951?sid=ae698a57-80b4-4199-9c4b-7a9b7e7847bc
