### ISSUE TITLE
[Bug]: 2 Duplicated Signature requests events are triggered for any signature

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21770]
### Describe the bug

**Problem:** after [this PR](https://github.com/MetaMask/metamask-extension/pull/21482) was merged, and the [infinite requests](https://github.com/MetaMask/metamask-extension/pull/21743) has been fixed, we can now see another issue, where signature requests are duplicated x2.

### Expected behavior

Just 1 Signature request should be triggered for a Signature event

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/926b1da1-deac-45b3-91d9-f55f5da6cbe6

Before, in `11.4.1` (working correctly):

https://github.com/MetaMask/metamask-extension/assets/54408225/81858b04-59b0-44a6-9325-2bd0d348cbef

### Steps to reproduce

1. Setup Metrics project
2. Trigger any Signature
3. See 2 Signature Requests

### Version

11.5.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Closing as fixed with https://github.com/MetaMask/metamask-extension/pull/21791
