### ISSUE TITLE
[Bug]: Bening signatures don't display any RPC information in metrics events

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21771]
### Describe the bug

**Problem**: after https://github.com/MetaMask/metamask-extension/pull/21482 was merged, and the https://github.com/MetaMask/metamask-extension/pull/21743 has been fixed, we can now see how the bening signatures don't show any RPC events information

### Expected behavior

We should display RPC info to any signature

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/c76ba238-a7f3-4e8c-8e6b-a1641b9c66a5

### Steps to reproduce

1. Setup a metrics project
2. Go to the test dapp
3. Trigger any bening signature (i.e. typed 4)
4. See no RPC information is embedded in the metrics event

### Version

11.5.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
To check with Blockaid whether this is expected (no RPC calls).

**Comment by bschorchit** [comment]
From Blockaid's documentation it seems RPC calls are expected for some signatures (seaport): 
https://wobbly-nutmeg-8a5.notion.site/MM-JSON-RPC-Benchmark-37d4a3bd74914b0fbe9147582c0cde51

**Comment by bschorchit** [comment]
Asked Blockaid team here: https://consensys.slack.com/archives/C05HZHDS89Z/p1699969577364129

**Comment by bschorchit** [comment]
Not all signature requests will trigger RPC requests, but some will.

**Comment by jpuri** [comment]
I debugged this issue and also looked at the code RPC details are always provided whenever applicable.
