### ISSUE TITLE
[e2e] Fix PPOM flaky test and re-enable it

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21778]
This test was disabled because it was failing too often. It needs to be fixed and re-enabled.

https://github.com/MetaMask/metamask-extension/pull/21627

See here: https://consensys.slack.com/archives/GTQAGKY5V/p1698774543268939

From Slack: 
> I believe the problem with test/e2e/tests/ppom-blockaid-alert.spec.js is that when you click "Malicious Trade Order" on the Test Dapp, it does not show a Blockaid warning.

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21778?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by cryptotavares** [comment]
Closing it as it will be fixed with this #23642
