### ISSUE TITLE
Add ability to auto-detect tokens

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2178]
We changed this feature because it was too heavy to check every token on every block, but we should still explore ways of detecting tokens for user accounts. It might even be worth using a central server to track what tokens users have at least on the main network.

**Comment by owocki** [comment]
i wonder if doing a `web3.eth.filter()` on events from the ERC20 token standard (Transfer, Approval), for which one of the `web3.eth.accounts` is an argument, might be an acceptable way to detect tokens.

```
    event Transfer(address indexed _from, address indexed _to, uint _value);
10     event Approval(address indexed _owner, address indexed _spender, uint _value);
11 }
```

**Comment by danfinlay** [comment]
The Event API is incredibly slow, it's not really a performant answer to any question, it's just dev convenience for the present.

**Comment by danfinlay** [comment]
Closing as duplicate of #3034 or #2560
