### ISSUE TITLE
[Bug]: `Metamask` should have `M` in uppercase from token list

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21805]
### Describe the bug

**Problem:** `Metamask` should have the 2nd `M` as uppercase in the token lists for token details. The problem seems to be in the Metaswap API response, but not sure if there's an open repo for opening an issue there

### Screenshots/Recordings

![Screenshot from 2023-11-13 10-11-44](https://github.com/MetaMask/metamask-extension/assets/54408225/013a05ae-3bda-4d29-b6aa-d20f4442359b)

See API response:

![Screenshot from 2023-11-13 10-13-44](https://github.com/MetaMask/metamask-extension/assets/54408225/87087b3a-2422-42ee-9a8c-ae31fa6474bf)

### Steps to reproduce

1. Enable token detection
2. Click any asset details
3. See `Metamask`

### Version

11.4.1 (it's an old issue)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sam41306061** [comment]
@seaona , just wanted to ask if this issue is linked to other issues related to the API?
