### ISSUE TITLE
Confirm Approve and Token Allowance Blockaid Banner Alerts do not include onClickSupportLink and it's associated events

### ISSUE THREAD

**Issue by segun** [MetaMask/metamask-extension#21802]
When we show the BlockaidBanner Alerts, we add a property onClickSupportLink that gets triggered when the Support link is clicked and we capture the events. On ConfirmApprove page and TokenAllowance page, the Banner did not include this property, so the events are not captured.

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21802?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
It seems the property is also not getting added as part of the transaction and signature events, but rather in an External Link Clicked event. This prevents us from knowing what transaction or signature is causing confusion to users when flagged as the External Link Clicked event doesn't carry any info around the transaction or the signature.

**Comment by seaona** [comment]
<img width="1491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2U3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--758d010fb256748b66c9298190a8b903dd2ae0b8/Screenshot%20from%202024-01-11%2016-20-03.png" alt="Screenshot from 2024-01-11 16-20-03.png" />

**Comment by bschorchit** [comment]
Closing as I believe this was addressed with this 2 PRs: https://github.com/MetaMask/metamask-extension/pull/22631 and https://github.com/MetaMask/metamask-extension/issues/22667
