### ISSUE TITLE
[Bug]: Mobile app suddenly closed and not working anymore when adding dQuick Token

### ISSUE THREAD

**Issue by duoseven** [MetaMask/metamask-extension#21800]
### Describe the bug

When i add dQuick Token, then app is closed and when i open again it's not working anymore, always closed when trying to open. My phone is Oppo A92.

### Steps to reproduce

1. Go to QuickSwap site
2. Add dQuick to wallet with click on + sign from the token list
3. then metamask is closed and can't open it anymore

### Version

7.10.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by anaamolnar** [comment]
Hello, @duoseven.Thanks for reporting! This belongs to the metamask-mobile repository.  Please update to the latest version and let us know if this continues to occur. Feel free to open a new issue there if that is the case. Thank you!
