### ISSUE TITLE
[Bug]: ERC20 token image is cut in the Token Details page, if the token has several decimals (i.e. 18)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21806]
### Describe the bug

**Problem**: If I have a token with an amount with lots of decimals (i.e. 18), I can see how the token image is cut in the screen, for the Token Details page.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/df4dc9c7-d4a1-4cac-a2cc-0613cccf81fb)

### Steps to reproduce

1. Import a token with an amount of several decimals
2. See token details
3. See image is cut

### Version

11.4.1 (seen in older versions too i.e. 10...)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by georgewrmarshall** [comment]
Reassigning to wallet ux team but happy to collaborate on it
