### ISSUE TITLE
[Bug]: Metamask sending requests with empty body

### ISSUE THREAD

**Issue by makemake-kbo** [MetaMask/metamask-extension#21803]
### Describe the bug

When swithching to a new network, metamask seems to be sending requests with an empty body. Example:
```
"Request"{
   "method":"OPTIONS",
   "uri":"/",
   "version":HTTP/1.1,
   "headers":{
      "host":"127.0.0.1:3000",
      "user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0",
      "accept":"*/*",
      "accept-language":"en-GB,en;q=0.5",
      "accept-encoding":"gzip, deflate, br",
      "access-control-request-method":"POST",
      "access-control-request-headers":"content-type",
      "origin":"moz-extension://8ecf6143-adcf-4e06-9787-d0895acaf7b5",
      "dnt":"1",
      "connection":"keep-alive",
      "sec-fetch-dest":"empty",
      "sec-fetch-mode":"cors",
      "sec-fetch-site":"cross-site"
   },
   "body":"Body(Empty)"
}
```   

This is quite strange, so Im wondering what the purpose of this is and how id go about supporting it?

### Steps to reproduce

1. Set up [Blutgang](https://github.com/rainshowerLabs/blutgang)
2. Add a network with Blutgang as the url
3. Cry because it's erroring out

### Version

Latest

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS, Linux

**Comment by anaamolnar** [comment]
Hello, @makemake-kbo. Thanks for reporting! I have passed this on to the appropriate team. They will review your inquiry and follow up with any updates as soon as possible.

**Comment by jiexi** [comment]
@makemake-kbo Are you saying that MetaMask is sending requests to the RPC endpoint?

The request above being `OPTIONS` seems to imply that the request you have shared is preflight check

**Comment by makemake-kbo** [comment]
> @makemake-kbo Are you saying that MetaMask is sending requests to the RPC endpoint?
> 
> The request above being `OPTIONS` seems to imply that the request you have shared is preflight check

yes, looks like it. im wondering how id go about supporting it properly since metamask errors out, because the body is empty.

my main question is what response is metamask expecting to receive when it sends such a check?

**Comment by jiexi** [comment]
I believe this is underlying browser behavior to prevent XSS. 

Adding `Access-Control-Allow-Origin: *` to the header in your RPC endpoint's responses may resolve it.
