### ISSUE TITLE
[Bug]: `No metadata found for 'unencryptedSnapStates'` when removing a snap

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21817]
### Describe the bug

**Problem:** when I remove a snap I see the following error in the background `No metadata found for 'unencryptedSnapStates'`

### Expected behavior

No error should appear

### Screenshots/Recordings

![Screenshot from 2023-11-13 11-59-21](https://github.com/MetaMask/metamask-extension/assets/54408225/ec8b2047-9cbb-4e8d-81fe-da34cf5b93cd)

### Steps to reproduce

1. Add a snap
2. Remove it
3. Check console

### Version

develop (but maybe existing issue)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by FrederikBolding** [comment]
@seaona How does one reproduce this? We added this new state field in https://github.com/MetaMask/metamask-extension/pull/21774 - could it be that this is caused by moving backwards between versions of MM or something?

**Comment by seaona** [comment]
hi @FrederikBolding thanks for pointing this out. I confirm this appeared during a backwards migration, the same as the other metadata issue for snaps. I defer to you to close the issue. Thank you!
