### ISSUE TITLE
[Bug]: json rpc calls (such as eth_accounts and eth_chainId ) to the wallet to sporadically hang

### ISSUE THREAD

**Issue by RyanTimesTen** [MetaMask/metamask-extension#21831]
### Describe the bug

hello 👋 was there a change recently in MM that could cause json rpc calls (such as eth_accounts and eth_chainId ) to the wallet to sporadically hang?
we noticed a problem recently where our calls to get the accounts and network from MM sometimes never resolve on page load.
this seems to be a race condition because it doesn’t happen every time, but you will hit it eventually.

### Expected behavior

Everytime upon page load, the json rpc calls should resolve and not hang

### Steps to reproduce

codesandbox repro: https://codesandbox.io/s/holy-feather-l5gshn?file=/src/App.js

on: https://l5gshn.csb.app/
1. click connect, connect your MM wallet
2. open a new tab, notice that it says “refreshing accounts” and gets stuck there.
  a. sometimes it does not hang, and it does progress to “refreshed accounts”. just keep trying :) it starts happening consistently for me after 3-4 attempts.

### Version

11.4.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jiexi** [comment]
Hey there, @RyanTimesTen. Thank you for bringing this to our attention. Could you help us verify something by disabling preloading in your Chrome settings? This can achieved by:
1. Opening settings
2. Searching for "Preload"
3. Toggling the "Preload pages" setting to off

After you do this, are you still able to reproduce the bug you are seeing?

Also, may we know what version of Chrome you are using?

Thank you

**Comment by RyanTimesTen** [comment]
hey @jiexi sorry for the delay

> After you do this, are you still able to reproduce the bug you are seeing?

no, i am not able to repro after doing this! very intesreting. i'm currently on Chrome version 120.0.6099.109

**Comment by gauthierpetetin** [comment]
Hi @jiexi are there any conclusions we can draw, based on the test done by @RyanTimesTen ?

**Comment by jiexi** [comment]
This should be resolved by https://github.com/MetaMask/metamask-extension/pull/24317 which is slated for release with version 11.17.0

The caveat being that you must be on one of the newer chrome versions. 120+ for MacOS and Windows or 121+ on Linux.

Thank you again for taking the time to report this bug 🙏
