### ISSUE TITLE
MetaMask deleted vault, saved vault key does not restore all wallets.

### ISSUE THREAD

**Issue by dskvr** [MetaMask/metamask-extension#2186]
Expected Behavior:
Vault key restores vault.

Actual Behavior:
Vault key restores a single wallet.

**Comment by Zanibas** [comment]
You can continue to reveal the same accounts by clicking "add account". We're sorry this isn't clear and we hope to reveal all accounts in the future!

**Comment by dskvr** [comment]
@Zanibas there is no "add account" functionality. You mean "create account" or "import account" ???

**Comment by dskvr** [comment]
@Zanibas ?

**Comment by NikitaSavik** [comment]
@dskvr @Zanibas Any solution to this problem?
