### ISSUE TITLE
[Bug]: `Unable to determine contract standard` when `executed reverted` for `eth_calls` 

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21867]
### Describe the bug

**Problem:** whenever we are trying to send a transaction to a contract, if we get `execution reverted` for all the `eth_call`  requests, we cannot proceed to the Confirmation screen for a Send transaction, but we see no information on the UI.
The UI console gives the `Unable to determine contract standard` error.

This situation can happen if one of our eth_calls calls a method that does not exist and the contract has a fallback for reverting.
Simple example (where any eth_call will revert):

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract SimpleRevert {
    fallback() external payable {
        revert();
    }
}
```
**Context**: we perform `eth_calls` to get the following information: `decimals, supportsInterface, symbol...etc`. on the Recipient input page. I am not sure why we do it in this screen, as we are not selecting the Asset (previously done or defaulting to ETH/native token chain. In the next screen we can change the asset, so I would also expect calls there.

### Expected behavior

- why are we performing the eth calls on the Recipient screen?
- why are we performing eth calls against the recipient address: notice if we send a token, the eth calls should be made against the token contract address, not the 'recipient' that we have on the UI (even if the recipient it's a contract).
- if our selected asset is ETH from the start, why are we performing eth_calls at all?

- Not sure - I would maybe expect some UI feedback? and revise the above points

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/d6c09655-c4a1-4091-97a5-9e38a55fb260

![Screenshot from 2023-11-16 20-16-04](https://github.com/MetaMask/metamask-extension/assets/54408225/7a4a4052-1033-45ea-99cf-f13e6aaa11df)

### Steps to reproduce

1. Select Mainnet
2. Click Send
3. Paste this recipient `0x000080eE0919AbDC6568E6898c61f49E98ec0000`
4. Check console

===========
On Sepolia network, you can try with this contract `0xEbbe5b7E5d911448f9990567144FF163E0C95Bf7`

### Version

11.5.0 and possibly earlier

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Are the eth_calls possibly being made to try to identify that you're sending a transaction to a contract and raise a warning if yes? Even if yes, this issue is still valid.
