### ISSUE TITLE
[Bug]: Connections UI indicator does not update when user disconnect from the dapp using snaps

### ISSUE THREAD

**Issue by holantonela** [MetaMask/metamask-extension#21860]
### Describe the bug

The connected dapp<>account UI indicator does not update when user disconnect an account from the dapp *using snaps*. 

### Expected behavior

Not sure. It been discussed in the past that in this case the indicator should be an outlined circle, not a filled green dot.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/87079938/5806d9e1-722d-4241-bdb7-968516ac2593

### Steps to reproduce

1. Go to [app.shapeshift.com](https://app.shapeshift.com/)
2. Install the snap, connect wallet
3. Disconnect wallet from the dapp menu

### Version

11.0

### Build type

Flask

### Browser

Firefox

### Operating system

MacOS

### Additional context

H1 report in the security incident response queue was closed as informational as we consider this a UI bug.

**Comment by vandan** [comment]
Shapeshift would have to disconnect using our official disconnection method (introduced in Dec 2023):
https://docs.metamask.io/wallet/reference/wallet_revokepermissions/
