### ISSUE TITLE
Awaiting details to further triage. Unclear if the value discrepancy is specific to token and/or network vs affecting all users.

### ISSUE THREAD

**Issue by vania221** [MetaMask/metamask-extension#21885]
Awaiting details to further triage. Unclear if the value discrepancy is specific to token and/or network vs affecting all users.

_Originally posted by @hesterbruikman in https://github.com/MetaMask/metamask-mobile/issues/7787#issuecomment-1810818726_

**Comment by anaamolnar** [comment]
Hey @vania221 I am going to close this as it's not related to this repo. Feel free to open another more detailed issue if you feel that is not the case. Thank you!
