### ISSUE TITLE
[Bug]: Inaccurate gas estimate shown from actual transaction sent on Optimism OP Optimistic L2

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#21898]
### Describe the bug

Users submitting transactions on OP network see different gas prices in MetaMask from the final gas prices being issued. 

[Shared in internal thread](https://consensys.slack.com/archives/C01KXHPU3C6/p1699907987750119): 

> We have encountered some issues with the gas estimate not being accurate on MM vs the actual txn.  Here are two cases:
From Sound.xyz (please see image 1)
https://optimistic.etherscan.io/tx/0x6600fa3f79e253adc5adf6f8f8620dad0ef4011e1cc9b74c75d4e3919874ed17, users
From me (reproduced via a Uni, swapping ETH --> AAVE (image 2)
https://optimistic.etherscan.io/tx/0x8ab65283db9fdfafa803100bc2c7512f15e750fe248b6db68a5698f2016e8ed6

<img src='https://github.com/MetaMask/metamask-extension/assets/20778143/38982471-59e6-4a1c-908c-ce8db9d13c79' width='250'>
<img src='https://github.com/MetaMask/metamask-extension/assets/20778143/8850b2e5-422f-4f7f-972e-fb2132c406be' width='270'>

From [internal thread mentioning](https://consensys.slack.com/archives/C01KXHPU3C6/p1699910537050839?thread_ts=1699907987.750119&cid=C01KXHPU3C6) conversation from sound.xyz:
> easy OP mainnet repro -> collect on secondary on https://www.sound.xyz/optimism/v-buterin
>
> a user got a metamask estimate for $0.12 and then got whacked with a $17 tx fee for a larger order, so def something we want to get ahead of

### Steps to reproduce

Create and send OP transaction on Optimistic Ethereum. Observe gas price in MetaMask and then in final transaction.

### Version

???

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

As of now, no build specs reported

**Comment by bschorchit** [comment]
This might be fixed with https://github.com/MetaMask/metamask-extension/pull/19960 as the cause might be L1 fees not being displayed to the user.

**Comment by bschorchit** [comment]
Closing as this has been solved
