### ISSUE TITLE
[Bug]: Token price is not displayed correctly for some native tokens.

### ISSUE THREAD

**Issue by salimtb** [MetaMask/metamask-extension#21891]
### Describe the bug

[Bug]: Token price is not displayed correctly for some native tokens.

### Expected behavior

should display this [price](https://www.coingecko.com/en/coins/beam-2) 

### Steps to reproduce

1. Go to add custom network 
2. use the informations below to import BEAM custom network:
        Network Name: Beam
        RPC: https://subnets.avax.network/beam/mainnet/rpc
        Chain ID: 4337
        Token Symbol: Beam
        Explorer: https://subnets.avax.network/beam
3. check the displayed price ( should be [this-price](https://www.coingecko.com/en/coins/beam-2) instead of the one [displayed](https://www.coingecko.com/en/coins/beam) )

### Version

11.5.0

### Build type

None

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hey @salimtb. Thanks for reporting! I will pass this on to the team.

**Comment by 0x0sub** [comment]
Hi @anaamolnar, I reported this issue previously. It has now been resolved. I was under the impression that Metamask would use the CoinGecko API for price data, but I later discovered that it uses data from CryptoCompare.

The issue can be closed, as the price displayed now accurately reflects BEAM.
