### ISSUE TITLE
[Bug]: Not enough gas blocks user transaction despite having enough funds on Optimism OP Optimistic L2

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#21899]
### Describe the bug

When attempting to issue transaction with OP network, e.g. on https://welovetheart.optimism.io/, users are observing MetaMask display not enough funds for the gas fee, when they do report having enough funds.

[Internal Thread reported issue](https://consensys.slack.com/archives/C01KXHPU3C6/p1700482859796709?thread_ts=1699907987.750119&cid=C01KXHPU3C6): 

> We have a lot of new users coming through the welovetheart.optimism.io campaign and are facing issues like this:
(They made a typo on the “0.22” but the problem is real because gas estimations are off on the UI)
Appreciate your help in looking into this, and let me know if there is anything I can do from our end :pray:

> "metamask says I don't have enough money for a 0.22 gas fee but i have 18$ of eth in the account [...]"

### Steps to reproduce

-

### Version

???

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

no build specs provided at this time

**Comment by bschorchit** [comment]
Curious if this could be related with L1 fees not being displayed to the user that will be fixed with https://github.com/MetaMask/metamask-extension/pull/19960

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-extension/pull/19960 has been merged and released
