### ISSUE TITLE
[Bug]: Gas option displays `Site suggested` with a transaction triggered from the inside the wallet (no dapp)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21905]
### Describe the bug

**Problem:** whenever I am sending a token or ETH from inside the wallet, I can see how the gas is set to `Site suggested` even though there is no dapp, as I've initiated the transfer from inside the wallet.

This seems to happen if I have the `Hex Data` setting enabled and I use a custom network.

### Expected behavior

We should not see Site suggested for the gas default option, as there is no dapp suggesting a gas value.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/8b9bdce0-d16e-4e60-8bc7-f25df27e123e

https://github.com/MetaMask/metamask-extension/assets/54408225/1faed728-219b-4aed-9b21-1e9635a79315

### Steps to reproduce

1. Add a tenderly network with balance https://devnet-config.onrender.com/
2. Enable hex data
3. Trigger any tx
4. See gas set as `Site suggested`

### Version

11.5.0 production (possibly earlier too)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
@vinistevam  Works as expected for me too:

https://github.com/MetaMask/metamask-extension/assets/104780023/4a6768b6-5f22-452b-96f2-65c7b72d9219
