### ISSUE TITLE
[Bug]: Performance degradation

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21907]
### Describe the bug

**Problem:** after switching networks I experimented a performance degradation of the wallet. Initiating a send flow takes way longer as well as all the steps until sending a transaction. I see numerous warnings on the UI console saying `ImmutableStateInvariantMiddleware took 262ms, which is more than the warning threshold of 100ms`

Reloading the wallet does not fix it. The only way is to remove the extension and upload it again.

[Update] From the information in the comments and slack, it seems there is a perfomance issue around Swaps - but might be different from this one:

### Expected behavior

Performance should be the same as before

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/20adb03c-1840-4c33-a995-bf6dbcfb1268

### Steps to reproduce
It seems this started happening when I switched networks, but further investigation needed.
I used Sepolia, Goerli and Tenderly devnet.

### Version

https://github.com/MetaMask/metamask-extension/pull/21166

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
For me performance slows down when I try to use `Swaps` whenever on Goerli or Mainnet.

**Comment by seaona** [comment]
ℹ️ this issue was originally found in the Controllers PR but I confirm it's also present in the RC branch 11.6.0 so maybe this ticket should be re-assigned
cc @matthewwalsh0

**Comment by pedronfigueiredo** [comment]
I investigated the swaps performance degradation report above.

I couldn't reproduce the issue reported on the send flow.

On the swaps flow, I have repro'ed the `ImmutableStateInvariantMiddleware` warning message in commits all the way back to August, but a much smaller slowdown (~110ms). It doesn't seem to be a regression on the v11.6.0 release or https://github.com/MetaMask/metamask-extension/pull/21166.

**Comment by danjm** [comment]
I can't repro either, but the slowdown is almost definitely due to the `ImmutableStateInvariantMiddleware`, which won't be a problem in prod. So I am going to go forward with release and we can look into this more in the coming days.
