### ISSUE TITLE
[Bug]: After changing network and then back to Mainnet, fetching swap quotes on non-native token is getting call revert exception

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#21904]
### Describe the bug

After changing network and back to Mainnet fetching swap quotes on non-native token is getting call revert exception
This happens when:

- swap from no-native tokens to Ether  => error fetching quotes
- swap from no-native tokens to no-native tokens => error fetching quote

Swapping from Ether to no-native tokens (DAI/WETH/USDT, etc) => works fine

After seeing that problem if I open the transaction modal then `fetching quotes` get stuck and I need to exit Swap to restore working condition. Please see attached video

### Expected behavior

I am able to fetch a quote even after changing networks

### Screenshots/Recordings

<img width="1264" alt="Screenshot 2023-11-21 at 11 16 05 AM" src="https://github.com/MetaMask/metamask-extension/assets/6082863/4d17bd47-896b-4b70-bae3-668b57ada20c">

https://github.com/MetaMask/metamask-extension/assets/6082863/fca33076-33f1-479b-85a5-8c4e1620e379

### Steps to reproduce

1. Try to change network to any popular one
2. Switch back to mainnet
3. Now try to swap WETH->ETH or USDC->ETH
4. You will see error on getting quotes with a call revert exception
5. Now open the transaction modal and close it
6. Notice that fetching quotes starts again but it gets stuck

### Version

11.6.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Was tested using the 11.6.0 release candidate

**Comment by sleepytanya** [comment]
> swap` from no-native tokens to Ether => error fetching quotes
swap from no-native tokens to no-native tokens => error fetching quote

Occurs for me every time on Mainnet, without network switching.
There is also an issue with the Goerli swaps. 
Swap Eth to non-native token - see the error on the background console and while there is no fetching quotes error the `swap` button is unavailable:

<img width="1342" alt="Screenshot 2023-11-21 at 3 23 08 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/3c062ed5-7d07-4d7e-89e4-52cf40f9e690">
I don't have non-natibe tokens on Goerli and can't confirm if swap non-native to eth/non-native token can be performed.
