### ISSUE TITLE
[Bug]: Not Restricting Users From Sending 0 Assets

### ISSUE THREAD

**Issue by nithinmrl1890** [MetaMask/metamask-extension#21906]
### Describe the bug

Presently, users are able to send 0 assets, resulting in unnecessary gas fees being consumed, despite a warning message appearing. This action doesn't align with the expected user behavior and is causing unnecessary gas expenses.

### Expected behavior

Users should be restricted from sending 0 assets to prevent unnecessary gas fees. Metamask or similar wallet integrations should disallow such transactions to align with common user expectations and prevent unnecessary expenses.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/151626508/ba523432-bcf5-4ab5-9b91-d6d9b4ab72d3)
transaction hash: https://polygonscan.com/tx/0xfe3f00bd5b4416dbc6f0c4215145ab44e6fffb2373e4534580395290205a462a

### Steps to reproduce

1. Initiate a transaction to send 0 assets.
2. Despite a warning, proceed with the transaction.
3. Observe that the transaction goes through, consuming gas fees.

### Version

3.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Severity

medium

**Comment by bschorchit** [comment]
Hey @nithinmrl1890 , currently users do have legitimate reasons to send 0 value transactions (e.g. to cancel a transaction with the same nonce) and this is not something we want to prevent them from doing. 

We can consider a more aggressive warning than the one that currently exists.
