### ISSUE TITLE
[Bug]: CONTROLLERS MIGRATION - Incorrect nonce jump

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21910]
### Describe the bug

**Problem:**  nonce has been incorrectly calculated, causing a transaction to have higher nonce than expected, leaving it on a pending state.
This happens when you send a tx to yourself on another network and then go back to the original network. The nonce is incremented there too.

### Expected behavior

Nonce should be correctly calculated

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/99fccf11-08a1-4915-bd34-32a648fcb050

### Steps to reproduce
1. Select a network
2. Send a tx
3. Verify nonce number
4. Now change to another network
5. Send ie.. x2 tx to yourself
6. Switch back to the original network
7. Send a tx
8. See nonce is higher than expected (+2)

### Version

https://github.com/MetaMask/metamask-extension/pull/21166

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by matthewwalsh0** [comment]
This should be fixed now, it's using the same nonce fixes as mobile 🤞

**Comment by matthewwalsh0** [comment]
I can replicate this now as it seems to occur after the first network switch.

It appears to be an undiscovered issue in the `nonce-tracker` package but have added a patch to hopefully fix this.

**Comment by seaona** [comment]
thank you for the investigation @matthewwalsh0 :heart_eyes:  I'll re-check the behaviour again with the changes and add a comment in this same ticket

**Comment by sleepytanya** [comment]
Nonce jump after switching networks does not occur:

https://github.com/MetaMask/metamask-extension/assets/104780023/5caece41-3034-405d-9dc0-d01463b22f43

**Comment by sleepytanya** [comment]
'0 nonce' issue also has been fixed and I'm not seeing it.

**Comment by seaona** [comment]
@matthewwalsh0 @sleepytanya I also see the above issue fixed :pray: closing the ticket now
