### ISSUE TITLE
[Bug]: CONTROLLERS MIGRATION - Send To screen displays incorrect gas when insufficient balance and Next button enabled 

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21916]
### Describe the bug

**Problem:** whenever I am trying to send an ERC20 token, if I don't have enough balance for that token, I can see 2 different behaviours than before:
- the gas seems overly calculated
- the Next button is now enabled (not sure if this is desired, but it's different from the previous behaviour)

### Expected behavior

Same as before (see right side of the screen)

### Screenshots/Recordings
Left side: controllers branch
Right side: both production and current `develop`

https://github.com/MetaMask/metamask-extension/assets/54408225/d1eabc63-2c05-4370-afae-190d146d3fad

### Steps to reproduce

1. Click Send ERC20
2. Add any recipient
3. Add an amount of token higher than your balance
4. See gas is suddenly miss-calculated
5. See Next button is enabled (not sure if this is desired now, but it's different than before)

### Version

https://github.com/MetaMask/metamask-extension/pull/21166

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by matthewwalsh0** [comment]
Great spot @seaona ! I think this is now fixed 🤞

**Comment by seaona** [comment]
thank you @matthewwalsh0 :pray:  I'll re-check the behaviour again with the changes and add a comment in this same ticket

**Comment by sleepytanya** [comment]
Sending ERC20 with insufficient token balance shows correct gas, `Next` button is blocked.
`Develop`, Chrome, DAI, LINK:

https://github.com/MetaMask/metamask-extension/assets/104780023/dc7bc7be-6df0-486c-acdd-b70015db75a1

`Production`, Chrome, DAI:

https://github.com/MetaMask/metamask-extension/assets/104780023/3c867878-1d42-48a5-8f13-09bf7d176f81

Chrome, `develop`, TST - left side, right side - Firefox, `production`:

https://github.com/MetaMask/metamask-extension/assets/104780023/b8f1f848-b562-43db-a464-dcee6c6c58a7
