### ISSUE TITLE
Enable support to blockaid on custom network - PPOMController

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#21913]
We should enabled it on the following networks:

- Ethereum Mainnet (already done)
- BNB chain
- Polygon
- Arbitrum
- Optimism
- Avalanche
- Linea

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/21913?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun
