### ISSUE TITLE
 [Bug]: MetaMask unresponsive after switching networks from dapp

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21929]
### Describe the bug

**Problem:** MetaMask stays unresponsive after switching networks from a dapp

### Expected behavior

Should continue to work

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/41210b3d-004a-4283-9ffc-b656ccdba2be

### Steps to reproduce

1. Go to https://chainlist.org/
2. Connect MM
3. Add any network
4. Switch to that network using the button in the web
5. See MM stays unresponsive
6. No error

### Error messages or log output

![Screenshot from 2023-11-22 09-30-39](https://github.com/MetaMask/metamask-extension/assets/54408225/fe7f54f7-deb9-4145-a7e9-ab006f08c5fc)

### Version

`11.6.0`

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
:information_source:  this issue was originally found in the Controllers PR but I confirm it's also present in the RC branch `11.6.0` so maybe this ticket should be re-assigned
cc @matthewwalsh0

**Comment by danjm** [comment]
I have found that this was introduced in v11.3.0, but is only reproducible on local dev builds.
