### ISSUE TITLE
[Bug]: Should allow users to use gasLimit above 7920027

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-extension#21927]
### Describe the bug

should allow users to use gasLimit above 7920027
both Ethereum mainnet and Optimism have a max gas limit = 30,000,000.
![1](https://github.com/MetaMask/metamask-extension/assets/92011506/cd1f51f4-2bdb-4fe4-8ad9-c24fabff8751)

### Steps to reproduce

1.send a transaction
2.edit gaslimit

### Version

11.5.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello, @SekiCokeZERO. Thanks for reporting! I will pass this on to the appropriate team.
