### ISSUE TITLE
[Bug]: Nonce set too low when trying to send a tx (no custom nonce enabled) - [rare case]

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21932]
### Describe the bug

**Problem:** whenever trying to send a transaction I got the error:
```
backend.js:2045 [ethjs-rpc] rpc error with payload {"id":4788209828699,"jsonrpc":"2.0","params":["0x02f87083aa36a782055c8459682f0085032f7eceaf82520894c86ebdd39d5bd736f95abc0da314b5522dcaa2cf8080c080a0f69a2ab47df4191164053aa9cbf994647e84fd618a75ac95d3a729c9fcdb13b7a04d5c7f1454c6d628a31c45f7717df955ca74dbde6828dbc54690b44d5df947bb"],"method":"eth_sendRawTransaction"} [object Object

```
and the transaction always fails.

[Update] the error was indicating a `nonce too low` issue (a separate ticket has been created for logging the correct information). This ticket is scoped to the behaviour of having a nonce set too low by default in one Account, without manually customizing it before. (See comments below)

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/d8acbe86-e1ad-4d1b-a3a2-3f99ad7a7bfc

### Steps to reproduce
[To investigate steps, as seemed more that the wallet was into a weird state]
1. Add a tenderly devnet
2. Perform a tx
3. Change to Sepolia
4. Perfom a tx
5. This fails with the error above

### Version

11.6.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
I've added the release blocker tag just to be overly cautious, but feel free to remove it if you consider so. Might be an edge case not so easy to repro

**Comment by danjm** [comment]
@seaona You said "the transaction always fails", but e2e tests are passing. Does it only fail when you follow the exact repro steps you shared?

**Comment by seaona** [comment]
It was only failing for that account in that network. Switching to another account transactions work fine, but back to the first account it fails everytime.

Adding some more info. I've subsequently done the following:
- I've switched back to Tenderly
- Started a Swap
- Cancelled
- Switched to Sepolia
- Now tx work
- I've checked the Failed tx in the History and it had an incorrect nonce (1372 - lower than expected) 

So 2 things: 
- I'm wondering, if the error was the nonce, aren't we logging anymore the low nonce message error? only a generic json rpc fail. Or maybe I'm confused and we never did ? :thinking: @danjm 
- Not sure how could possibly had this low nonce though, as I had the edit nonce always disabled. Maybe from a previous wallet state :thinking:  I'm digging more into this now to see if I can repro again.
- If I was coming from a 'bad state' wouldn't the nonce be re-calculated every-time I initiate a transaction?

I think if this is something very specific we could remove the release-blocker, as I cannot ensure this was introduced in this RC

![Screenshot from 2023-11-22 11-24-43](https://github.com/MetaMask/metamask-extension/assets/54408225/100591b7-94d8-4674-affe-455e6570395b)

[MetaMask state logs-nonce.json](https://github.com/MetaMask/metamask-extension/files/13437988/MetaMask.state.logs-nonce.json)


[Screencast from 22-11-23 10:51:50.webm](https://github.com/MetaMask/metamask-extension/assets/54408225/7e813671-f18e-42dc-bdc8-1308222acda6)

**Comment by seaona** [comment]
I confirm we were displaying the `nonce too low errror` in the error message before, but we don't do this anymore. Seems that the issue was introduced between `10.29` and `11.1.2`

![Screenshot from 2023-11-22 12-36-53](https://github.com/MetaMask/metamask-extension/assets/54408225/8c11d32e-4d5a-4660-b9ee-60e8604d0717)

- I'll open a separate issue for that
- I'll separately investigate the nonce being low issue -but seems not related to the RC so we can remove the RC label

What do you think @danjm ?

**Comment by danjm** [comment]
That makes sense to me @seaona 

I was worried about the tx failing after a network switch. But it seems the network switching is unrelated. I might have an idea about the cause of the error not showing properly... I will look into that ticket when you create it

The nonce too low error is interesting... I will check back on this later today to see if that is concerning.

**Comment by seaona** [comment]
thank you @danjm [here](https://github.com/MetaMask/metamask-extension/issues/21938) is the ticket about the RPC logging error.
Also trying to reproduce the low nonce behaviour on my end. I will add any findings in this ticket

**Comment by seaona** [comment]
I think I might have an explanation now. When I was testing this, I was comparing with a previous version of MetaMask (switching back and forth).
I did a couple of transactions on another MM wallet and then switched back to `11.6` and did what I described above. It seems that might be the network was a bit slow and when I was in the new MM instance the wallet was not seeing the transactions sent in the other MM instance - since possibly tx were not confirmed yet and there were no Submitted tx in the current wallet instance, so it was grabbing the nonce old value (without the 2 transactions performed in the other MM instance).

This also explains that the tx `1373` is not on the state logs for that wallet instance, but directly we jump into the `1374` successful.

The fact that I switched to Tenderly and perform a swap and afterwards it worked again, might be simply that there was time for the tx to being confirmed, and then the new tx saw the correct nonce once back in Sepolia.

I could repro like this:

https://github.com/MetaMask/metamask-extension/assets/54408225/5b35f9d6-f09d-46f9-8135-fde91fe703d5

cc @danjm let me know if this makes sense

**Comment by danjm** [comment]
that makes sense @seaona 

I was able to reproduce the same way with v11.2.0 and v11.3.0

I not sure if there is anything we can do about the failures, but we can improve error messaging and we could add functionality that would help users recover more easily from the situation.

**Comment by seaona** [comment]
thank you for confirming @danjm :pray: I think this shows that the nonce logic is actually working correctly. If the [logging error ticket ](https://github.com/MetaMask/metamask-extension/issues/21938)is fixed, we would have better log information for the failure.
I think this situation won't be correct if we were operating with the SDK and using one Extension and one Mobile wallet instance sending transactions from the same account (like done here). Not 100% sure though :thinking: I can verify this later on

https://docs.metamask.io/wallet/concepts/architecture/

**Comment by seaona** [comment]
This can be closed as per above comments. The logging issue has already been fixed, and the explanation for setting a low nonce is due to using 2 wallet instances and subsequent really close transactions on each wallet
