### ISSUE TITLE
[Bug]: RPC generic error is shown instead of logging error information

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21938]
### Describe the bug

**Problem:** whenever there is an RPC error (i.e. nonce too low) I can see how no error log information is being displayed about the nonce error, and only a more generic error is logged

### Expected behavior

I expect to see `nonce too low` in the RPC error as we used to

### Screenshots/Recordings

Now:
![Screenshot from 2023-11-22 13-32-23](https://github.com/MetaMask/metamask-extension/assets/54408225/2d18bcda-55ca-45ae-8edd-da2b77dc2139)

Before:
![Screenshot from 2023-11-22 12-36-53](https://github.com/MetaMask/metamask-extension/assets/54408225/6402050a-3976-474c-9c06-2b0ee313fe07)

### Steps to reproduce

1. Enable custom nonce from settings
2. Initialize a Send tx
3. Set a lower nonce value
4. See generic RPC error, but not `nonce too low` information

### Error messages or log output

```shell
sentry-install.js:1 [ethjs-rpc] rpc error with payload {"id":6095961616212,"jsonrpc":"2.0","params":["0x02f86e83aa36a70b8459682f00850105912ecf82520894c86ebdd39d5bd736f95abc0da314b5522dcaa2cf8080c001a08fb18318e03ecce755b6addc0f86dfd5f5ead86663547d9b9086185efb94921fa07293a8669c0f7ef6fe24313b16614e0bb5e8b240b1b4f886fd5ff0a2f7edc263"],"method":"eth_sendRawTransaction"} [object Object]

```

### Version

11.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by vinistevam** [comment]
I've tested the MM v11.7, so after the transaction controller migration (https://github.com/MetaMask/metamask-extension/pull/21166) we can see in the video that a notification is displayed and a message is logged in the console. 

![Image](https://github.com/MetaMask/metamask-extension/assets/45455812/ee298193-868b-4524-ab5c-54c77c8e1f33)


https://github.com/MetaMask/metamask-extension/assets/45455812/b1153fe1-15d4-4e28-b8db-273e24315f78

**Comment by seaona** [comment]
thank you or investigating this, @vinistevam f! I've just tried with 11.7 too and I confirm I see this fixed on my end. The issue can be now closed
