### ISSUE TITLE
[Bug]: Transaction stays in `Pending` state even though it's confirmed in Etherscan

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#21941]
### Describe the bug

**Problem:** after sending a transaction I can see how sometimes it stays unusually long to `pending` state. This happened a couple of times and there's [another engineer reporting seeing the same](https://consensys.slack.com/archives/GTQAGKY5V/p1700650172724109).

I've encountered another case even weirder where, I send 2 transactions and both are confirmed on Ethercan but the **first one** stays pending on MetaMask  

### Expected behavior

Tx state should be updated in a reasonable amount of time
Not possible that a subsequent tx is confirmed and the first one is pending (in the wallet)

### Screenshots/Recordings

[MetaMask state logs-pending-tx-11.6.json](https://github.com/MetaMask/metamask-extension/files/13440789/MetaMask.state.logs-pending-tx-11.6.json)

https://github.com/MetaMask/metamask-extension/assets/54408225/f3a99167-7764-4be4-b36c-3060a989e598

https://github.com/MetaMask/metamask-extension/assets/54408225/f0625f9e-d2c3-4afd-a31f-ef2101ff7e9d

### Steps to reproduce

[Edited] Steps:

1. Select Sepolia
2. Send a transaction
3. Before being confirmed, change to Goerli
4. Send a transaction
5. Change back to Sepolia
6. See initial transaction stays in Pending
7. See in Etherscan is confirmed

### Version

11.6.0 - also reported in 11.5.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
Reproduced on 11.6.0 - transactions successfully confirmed on Block Explorer 10 mins ago are still in `Pending` and `Queued` state in the wallet:

https://github.com/MetaMask/metamask-extension/assets/104780023/acfb4a75-8911-44da-bdc0-e64cd36c69bf

Trying to `Cancel` or `Speed up` the transactions triggers state update and transactions can be seen as `Confirmed`.

**Comment by nikicat** [comment]
The same fo me

**Comment by seaona** [comment]
I think I know how to reproduce this know. If noticed that this **only** happens when you send a transaction with an Account which its Activity list is empty.
If the activity list contains already transactions, then the status is updated correctly, but if the activity list is empty, the very first transaction you perform, it will stay with a `Pending` status

https://github.com/MetaMask/metamask-extension/assets/54408225/c9170c41-764d-4177-b21d-c40e4ae41b14

**Comment by seaona** [comment]
The above comment to be dismissed - correct repro steps are in the issue description
