### ISSUE TITLE
Hardware wallet: Eth Sign

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#22026]

**Comment by seaona** [comment]
Example PRs on a similar task:
- https://github.com/MetaMask/metamask-extension/pull/23063 
- https://github.com/MetaMask/metamask-extension/pull/23043

**Comment by segun** [comment]
Rainbow CSV VSCode plugin makes this a lot easier to do

Each col is colour coded and you can see what col you are on as you're editing the data

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJ3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a219ba054626c8c18035baef759d010e763d8f45/Screenshot%202024-03-05%20at%2013.34.48.png" alt="Screenshot 2024-03-05 at 13.34.48.png" />
