### ISSUE TITLE
Hardware wallet: Sign Typed Data V3

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#22028]

**Comment by seaona** [comment]
hi there, this scenario cannot be added since Trezor/Ledger do not support sign typed data v3 - only v4

![Screenshot from 2024-02-20 11-53-53](https://github.com/MetaMask/metamask-extension/assets/54408225/4f3849e1-8193-45eb-9750-3fd250bd0dbf)

can I close the issue @chloeYue ?
