### ISSUE TITLE
[Bug]: Incoming transactions not shown in activity

### ISSUE THREAD

**Issue by matthewwalsh0** [MetaMask/metamask-extension#22045]
### Describe the bug

Incoming transactions are retrieved and available in the state but not visible in the activity list.

### Expected behavior

Incoming transactions for the current account and chain should be shown in the activity list.

### Steps to reproduce

1. Send balance between two wallet accounts.
2. Switch to the retrieving account.
3. Observe no incoming transactions are visible.

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Confirmed that incoming transactions are not visible in the Activity list - Chrome, develop.
No incoming transactions in the Activity (0xA24B5c474dF517b083811b099054D670Ba696C7a)
<img width="1194" alt="Screenshot 2023-11-28 at 6 04 24 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/22173d51-d8a1-4779-99a7-0a00e2d7db9c"> 
[Etherscan for the 0xA24B5c474dF517b083811b099054D670Ba696C7a](https://sepolia.etherscan.io/address/0xA24B5c474dF517b083811b099054D670Ba696C7a)
<img width="1368" alt="Screenshot 2023-11-28 at 6 05 58 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/1971ed78-23db-46e8-9c57-fc7f114e4a1d">

**Comment by matthewwalsh0** [comment]
Fixed by #22041.
