### ISSUE TITLE
[Bug]: Custom nonces values ignored 

### ISSUE THREAD

**Issue by matthewwalsh0** [MetaMask/metamask-extension#22043]
### Describe the bug

When custom nonces are enabled, the transaction submits without error however the original calculated nonce is used rather than the custom value.

### Expected behavior

The custom nonce value would be used in the submitted transaction.

### Steps to reproduce

1. Enable custom nonces.
2. Specify a low custom nonce.
3. Expect an error, but instead see a successful transaction with the next valid nonce.

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Transaction sent with low custom nonce submits with the calculated +1 nonce, ignoring custom value. Same for the transaction with higher nonce - it is confirmed with +1 nonce, not with the higher custom nonce. No error message is shown (Chrome, develop):

https://github.com/MetaMask/metamask-extension/assets/104780023/cb3dfc66-2c80-4844-997c-8bb139b84bcf

https://github.com/MetaMask/metamask-extension/assets/104780023/c3ca3cbf-d28b-4fb5-82eb-7d5441770c94
