### ISSUE TITLE
[Bug]: Faulty scam warning message

### ISSUE THREAD

**Issue by TaprootFreak** [MetaMask/metamask-extension#22062]
### Describe the bug

One of our customers receives the following advert:

This is a fraudulent request.
If you authorise this request, a third party known for fraud will seize all your assets.

Well, that's very unpleasant for us. We are a reputable on and off ramp regulated in Switzerland. Not a scam. 😄

--> https://exchange.dfx.swiss/

<img width="335" alt="uyBP8_gLk_H3xZREk0Y01MzErk1_25lxzg" src="https://github.com/MetaMask/metamask-extension/assets/142087526/0c02b43b-35d0-496a-9148-a7225677a03d">

### Steps to reproduce

The problem cannot be reproduced in general. This problem does not occur with other customers.

The blockchain address of this one customer is:

https://etherscan.io/address/0xD89EC2a80D53796Caa0408b2cC1702791D24D3bc

The customer has been with us for a long time and is very satisfied with the service. Only the false warning message is annoying. 

### Version

the latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

### Additional context

We are a Swiss regulated exchange and are happy to help you solve the problem correctly.

https://exchange.dfx.swiss/

support@dfx.swiss

**Comment by anaamolnar** [comment]
Hello, @TaprootFreak. Thanks for reporting! I will pass this on to the team.

**Comment by bschorchit** [comment]
Thank you for reporting this @TaprootFreak. We've shared this with the Blockaid for further investigation.

**Comment by hoangsonsky** [comment]
Unfortunately @bschorchit, I have also encountered a similar error even after verifying. https://bscscan.com/address/0x07882bc4df55554a8b85f944bd93affcfd5eb098#code

**Comment by hoangsonsky** [comment]
@anaamolnar @bschorchit Help me! My project is working. When new users see a notification like this, they feel worried.

**Comment by Sotatek-HauTran3** [comment]
@anaamolnar  @bschorchit. Hi team, we also get the same issue when launching a new NFT selling program.
Chain: Ethereum
Contract address: https://etherscan.io/address/0xb2c43cba1eb66cb40955a113de287a2383c8184c

Please let us know how we can pass this warning. We are not a scam, this message makes our customers feel confused

We are looking forward to your feedback

**Comment by miniaev** [comment]
Hi! And thank you for your business. I have the same issue,
Chain: Polygon
Contract address: https://polygonscan.com/address/0x3d3a360ee14592edf087401df269eb64b36154df

During the betatest I've got a "This is a deceptive request If you approve this request, a third party known for scams might take all your assets. See details • The contract 0x3d3a360ee14592edf087401df269eb64b36154df involved in the transaction is unverified"

Please help because I believe it is verified.
Thank you!
Vlad.

**Comment by anaamolnar** [comment]
Sorry I missed this @miniaev @Sotatek-HauTran3 If this is still an issue, please click on the Report an issue link. Thank you!

**Comment by irealrahul** [comment]
how should we resolved this issue. i have created new domain and showing this issue

**Comment by fusionstakee** [comment]
Hi
We just created these contracts and they give this message!
We haven't had any transactions yet.

0xfc54e4c282e266341dc10d60f4bc26d0eb357707
0x6c1d957c0d9290b27c2a568a4dbfa7d34e933ea6

**Comment by alexk-in** [comment]
@anaamolnar @bschorchit. Hi team, we also get the same issue with with our project. All contracts are verified
Chain: Base
Project address: https://basescan.org/address/0xBF35e4273db5692777EA475728fDbBa092FFa1B3

Please let us know how we can pass this warning. 

We are looking forward to your feedback

<img width="341" alt="Image" src="https://github.com/user-attachments/assets/df362055-1b28-4205-9f6e-3abbf0141dfd" />
