### ISSUE TITLE
[Bug]: Typed Signatures with `0x` value fails to recover Snaps Accounts

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22099]
### Describe the bug

**Problem:** in the process of updating the [test-dapp version module](https://github.com/MetaMask/metamask-extension/pull/22088), for testing signatures with `0x` values, I've seen that Snap Accounts fail to recover their address on those type of signatures.

**Context**: https://github.com/MetaMask/test-dapp/pull/274/files

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/6e2e883d-f5ae-4b9e-9115-9ec071f36e13

### Steps to reproduce

1. Add a Snap Account
2. Go to the test dapp
3. Trigger a Signature Typed 4
4. Try to recover the address -- see console error

### Version

11.6.0 (probably earlier too)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by plasmacorral** [comment]
Related https://github.com/MetaMask/accounts-planning/issues/166

**Comment by plasmacorral** [comment]
Resolved with [changes](https://github.com/MetaMask/snap-simple-keyring/pull/131) in Snap Simple Keyring v 1.1.1, tested with extension 11.7.2 in chrome.

https://recordit.co/hqGAaJzrXA
