### ISSUE TITLE
Add token prices to token list

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2210]
The Balanc3 team has provided us with an exchange rate API we can use for this.

Talk to Griffin Anderson / Gabriel Barros for API info.

Also needs design.

**Comment by ntziolis** [comment]
Whats the current status of providing token price conversion to fiat? If there is active dev going on can please somebody to the current discussion

**Comment by danfinlay** [comment]
This should be a reasonably easy task to add, the API exists for this, adding to the next sprint.

**Comment by danfinlay** [comment]
When we say "Token list" we mean the list of tokens in the account detail view.
When we say "Token prices", we mean the current total value (in the user's preferred fiat) of that token.

Christian says we could just copy the current design for showing Eth balance value.
