### ISSUE TITLE
[Bug]: `Invalid data; should be approve but instead is setApprovalForAll`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22106]
### Describe the bug

**Problem:** whenever a test dapp tries to trigger a SetApprovalForAll method (with the corresponding function signature `0xa22cb465`) but that contract does not support it, MetaMask breaks with the error `Invalid data; should be approve but instead is setApprovalForAll`

### Expected behavior

We should handle this type of cases - possibly displaying the fallback Contract Interaction screen + warning that transaction will fail?

### Screenshots/Recordings
(this is a modified test dapp with the to address changed to a random contract address, which does not support SetApprovalForAll - 0x2791bca1f2de4661ed88a30c99a7a9449aa84174)

https://github.com/MetaMask/metamask-extension/assets/54408225/f142357d-c9fe-4f20-b687-7f7a46a63c16

### Steps to reproduce

1. Go to the test dapp
2. Connect MM
3. Open the console
4. Paste this, changing the `from` field for your current address
5. Enter
6. See MM breaks

```
await ethereum.request({
      method: 'eth_sendTransaction',
      params: [
        {
          from: 'YOUR_ADDRESS',
          to: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174',
          data: '0xa22cb465000000000000000000000000b85492afc686d5ca405e3cd4f50b05d358c75ede0000000000000000000000000000000000000000000000000000000000000001',
        },
      ],
    });
```

### Version

11.6.0 (possibly earlier too)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
we don't want it to be closed

**Comment by anaamolnar** [comment]
Is this still happening?

**Comment by bschorchit** [comment]
Closing as this doesn't seem to be an issue still. 

The resulting transaction also didn't fail on chain: https://sepolia.etherscan.io/tx/0x83ac48280507cf0d2894b967ef5701d24c5e88f4216a30ca0e34096e2aee78be cc: @seaona in case this was not expected
