### ISSUE TITLE
[Bug]: Custom token spending entry is ignored and tx fails- out of gas

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#22119]
### Describe the bug

Observed this in 11.7 RC commit 9787b7eeadfa887900f710a716c2b117c2447fdb.  Testing Chrome 117.0.5938.92 in Mac Sonoma 14.0.  Initially observed on a Ledger, but can also produce on HD account.  This is not present on current production 11.6.3.

When I edit a token spending approval amount, my input is ignored and instead a value of `0000000000000000000000000000000000000000000000000000000000011170` is sent to the network regardless of what I enter.

### Expected behavior

User input on the custom token spending amount should be respected and reflected in what is broadcast to the network.

### Screenshots/Recordings

RC: https://recordit.co/zXdCzoD1j6 

Same case on 11.6.3: https://recordit.co/f7wp1rVZy2

Failed Goerli Approval TX from 11.7 RC: https://goerli.etherscan.io/tx/0xd60ccfea1977ab8737c9379061fb2766bf1a5d647a0c09c21de3dbbb418d09e0

Succesful Goerli Approval TX from 11.6.3: https://goerli.etherscan.io/tx/0xbcb0f74c105543602daa7b9b4e0aa44ab433b8937b0caaa0f34c822592aa10fa

### Steps to reproduce

1. Have an account with testnet funds (Goerli)
2. Have hex data enabled in settings>advanced
3. Connect to test dapp https://metamask.github.io/test-dapp/
4. Under `Send Tokens` tap create token
5. Approve contract deployment
6. Once Confirmed, tap `Add Token(s) to wallet`
7. Confirm with the `Add token` CTA
8. Paste an address into the `Approve to address` field
9. tap `Approve tokens` in test dapp
10. Edit custom spending cap....in my video I used `0.3549` which in hex should be `ddd`
11. tap `View details` and note that hex data matches expectations in the display
12. Tap `Next` CTA
13. Tap `Approve` CTA
14. Open pending tx detail
15. Tap `View on block explorer`
16. On pending tx tap `Click to show more`
17. Note that hex data in position 1 now ends with `11170` instead of expected `ddd`
18. Wait to run out of gas

### Error messages or log output

```shell
Warning! Error encountered during contract execution [out of gas]
```

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

### Additional context

Intially observed on Ledger, confirmed on HD account in 11.7.  Not present in production 11.6.3

**Comment by bschorchit** [comment]
Fixed with https://github.com/MetaMask/metamask-extension/pull/22129
