### ISSUE TITLE
Add visual security indication

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2212]
One powerful way to help users avoid phishing sites is to use security visuals, to help them recognize when they're on an impostor site.

This means making some visual aspect of the site totally personalized to that user. These are sometimes in the form of little icon "security images" that a user chooses when setting up, or it can also be a generated color or background that is applied to some part of the UI.

We should choose a custom visual security indication for MetaMascara and add it asap, so that phishers can't as easily impersonate a user's real wallet.

Also, we will probably want to add a screen explaining the security image to the vault setup. It could maybe be merged with other security setup screens.

**Comment by 10a7** [comment]
I would not mind picking up some design tasks here and there. Is there a workflow or set of design templates used internally?
