### ISSUE TITLE
[Bug]: USDT on Polygon not displaying properly on Firefox extension

### ISSUE THREAD

**Issue by affinixy** [MetaMask/metamask-extension#22132]
### Describe the bug

USDT on Polygon mainnet not displaying with the right decimals.
Eg: 0.00000000062930 instead of 629.30

### Expected behavior

USDT should display the same amount as stated in the Polyscan and on Metamask mobile app.

### Screenshots/Recordings

![ScreenHunter 312](https://github.com/MetaMask/metamask-extension/assets/84224084/6d46674f-e79b-483b-87d1-59bdebcd2576)

### Steps to reproduce

Use Firefox extension
Change to Polygon mainnet
Import USDT token

### Version

11.5.1

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello, @affinixy. Thanks for reaching out! It seems like your token has been imported with the wrong token decimals. You will need to go to the token details, click on the three-dotted menu and click on 'Hide token'. After that, please go to the Import token section, and paste the following contract address: 0xc2132D05D31c914a87C6611C10748AEb04B58e8F
Make sure in the token decimals section you have 6. I am going to close this issue. Feel free to re-open it if you still encounter the issue.

**Comment by MetaMask-Support-io** [comment]
> ### Describe the bug
> 
> USDT on Polygon mainnet not displaying with the right decimals.
> Eg: 0.00000000062930 instead of 629.30
> 
> ### Expected behavior
> 
> USDT should display the same amount as stated in the Polyscan and on Metamask mobile app.
> 
> ### Screenshots/Recordings
> 
> ![ScreenHunter 312](https://github.com/MetaMask/metamask-extension/assets/84224084/6d46674f-e79b-483b-87d1-59bdebcd2576)
> 
> 
> ### Steps to reproduce
> 
> Use Firefox extension
> Change to Polygon mainnet
> Import USDT token
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Version
> 
> 11.5.1
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Firefox
> 
> ### Operating system
> 
> Windows
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_
> 
> ### Severity
> 
> _No response_

NEED HELP @affinixy ??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)
