### ISSUE TITLE
Metamask not sinking with Etherdelta

### ISSUE THREAD

**Issue by lukeder** [MetaMask/metamask-extension#2216]
Hello I deleted the Metamask  extension and readded it. My seed words bring up my account but ether delta keeps prompting me to sign in. I am signed into MetaMask account. Previously if this happened I would just refresh and all was well. Since removing the extension and adding it back on it does not seem to work. 

 I am not sure what to do can someone please help? Thank you!
-->

**Comment by danfinlay** [comment]
Have you tried restarting the browser or computer?

**Comment by danfinlay** [comment]
I believe this was a short-lived bug that is fixed in 3.10.7. You can force Chrome to update an extension by right clicking the MetaMask icon, selecting "Manage Extensions", and clicking "Update now" next to MetaMask.
