### ISSUE TITLE
[Bug]: Imported ERC721 token shows broken image / not showing the image. 

### ISSUE THREAD

**Issue by pavinthan** [MetaMask/metamask-extension#22179]
### Describe the bug

I have minted gasless an ERC 721 token to my wallet address `0x....2fee` and I able to import it to my MetaMask wallet but the imported token shows broken image / doesn't show any details of that token. 

 

### Expected behavior

It should show the image and name from the metadata response. 

### Screenshots/Recordings

Metadata URL
<img width="518" alt="Screenshot 2023-12-06 at 11 59 30" src="https://github.com/MetaMask/metamask-extension/assets/13897936/68ab6db2-b0bc-4566-b38c-f6f60ddb9099">

Imported Token
<img width="355" alt="Screenshot 2023-12-06 at 11 56 51" src="https://github.com/MetaMask/metamask-extension/assets/13897936/ba8355b4-fe2c-48ba-a904-f4ed4b089c5e">

### Steps to reproduce

1. Open MetaMask
2. Switch to NFT tab
3. Import NFT
4. Enter `Address` and `Token ID` 

### Version

11.4.1

### Build type

None

### Browser

Chrome, Microsoft Edge

### Operating system

MacOS

### Additional context

Since `OwnerOf` and `tokenURI` respond current values, we can show up the details from that Metadata 

### Severity

- All the users

**Comment by Vikram710** [comment]
any updates on this?

**Comment by pavinthan** [comment]
@anaamolnar any updates?

**Comment by seaona** [comment]
I can see the same for ERC1155 tokens, not only with the image but also missing the description and name. I see that the request is correctly sent and I get the expected response, but this is not shown on the UI

![Screenshot from 2024-01-17 14-37-33](https://github.com/MetaMask/metamask-extension/assets/54408225/ab63195b-6f4b-4a15-828f-7ca63a0ce489)

**Comment by aheedkhan** [comment]
Greetings!, i was having this but i fixed it with some changes in metadata before stroing it,

my prevous metadata on ipfs:
{
    "name": "vjhgjh ",
    "description": "vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh vjhgjh sadasdvjhgjh vjhgjh vjhg",
    "amount": "1",
    "category": "",
    "imageURI": "https://salmon-main-antlion-827.mypinata.cloud/ipfs/QmXXLtg7T82v2XgDu3Ts7Yh2tzMJPTTsJJWiEFkFsGHacg"
}


my new metadata:
{
    "name": "gfhgfhgf",
    "description": "f hgfghfhgfhg fhg fhf hf hf h fhf h fhgfh hg fhg hg hg fhvh h h g hf hg fh fhfh gf hfhfh hf         hgf hgfhgf hgfhf hgf hgfhfh h fhf hfgh  hfhf hgfhf",
    "amount": "0.3",
    "category": "Travel",
    "image": "https://salmon-main-antlion-827.mypinata.cloud/ipfs/QmXK4no33cbgEGppwPAaUTLoPFpcYtaFDXV85cXnsKygCG"
}



my code:

  const sendFileToIPFS = async (e) => {
    if (file) {
      try {
        // create a new form data object
        const formData = new FormData();
        // append the file to the form data
        formData.append("file", file);

        // upload the file to IPFS using the Pinata SDK
        const resFile = await axios({
          method: "post",
          url: "https://api.pinata.cloud/pinning/pinFileToIPFS",
          data: formData,
          headers: {
            pinata_api_key: `${import.meta.env.VITE_APP_PINATA_API_KEY}`,
            pinata_secret_api_key: `${
              import.meta.env.VITE_APP_PINATA_API_SECRET
            }`,
            "Content-Type": "multipart/form-data",
          },
        });

        // get the IPFS hash of the file from the response
        const ipfsHash = resFile.data.IpfsHash;

        // set the image hash state
        setImageHash(ipfsHash);
        console.log(imageHash);

        // create a metadata object with the required fields
        const metadata = {
          name: title,
          description: description,
          amount: amount,
          category: category,
          image: `https://salmon-main-antlion-827.mypinata.cloud/ipfs/${ipfsHash}`,
        };

        // upload the metadata as a JSON file to IPFS using the Pinata SDK
        const resMeta = await axios({
          method: "post",
          url: "https://api.pinata.cloud/pinning/pinJSONToIPFS",
          data: metadata,
          headers: {
            pinata_api_key: `${import.meta.env.VITE_APP_PINATA_API_KEY}`,
            pinata_secret_api_key: `${
              import.meta.env.VITE_APP_PINATA_API_SECRET
            }`,
            "Content-Type": "application/json",
          },
        });

        // get the IPFS hash of the metadata from the response
        const metadataHash = resMeta.data.IpfsHash;

        // set the metadata hash state
        setMetadataHash(metadataHash);

        retirveData(metadataHash);
        console.log(metadataHash);
        console.log(web3Config);

        //Take a look at your Pinata Pinned section, you will see a new file and a new JSON added to your list.
      } catch (error) {
        console.log("Error sending File and Metadata to IPFS: ");
        console.log(error);
        alert("Error from pinata api server");
      }
    }
  };

**Comment by aheedkhan** [comment]
> Hello, @pavinthan. Thanks for reporting! I will pass this on to the appropriate team for review.

checkout my solution, that works for me

**Comment by pavinthan** [comment]
@aheedkhan that token metadata has image attribute, and it not only image name and description also missing

https://[metadata.mintology.app/45c1fb20-883c-11ee-a676-817ff0e681de/27808670864086717628299727037978068637842718696994987727543071207416345864004](https://metadata.mintology.app/45c1fb20-883c-11ee-a676-817ff0e681de/27808670864086717628299727037978068637842718696994987727543071207416345864004)

**Comment by anaamolnar** [comment]
Hey @alfeng6 Can you please check the above?

**Comment by bergeron** [comment]
- chainId = 1
- contract = 0x99d9b2b3e4376326d84de2cb0dc8bb867b8d7631
- tokenId = 27808670864086717628299727037978068637842718696994987727543071207416345864004

MetaMask does not find an image because the contract doesn't implement ERC-165 / `supportsInterface`:

![image](https://github.com/MetaMask/metamask-extension/assets/3500406/9d2b8c80-b521-4883-85a6-237acd3866e5)

![image](https://github.com/MetaMask/metamask-extension/assets/3500406/3c6921f9-d69a-4777-9d16-9bc931521d35)

The ERC-721 spec requires ERC-165 to be implemented, but MetaMask could try to support contracts that implement `tokenURI()` without declaring so via ERC-165.

**Comment by pavinthan** [comment]
Thanks @bergeron @anaamolnar it works after we added support to ERC165
