### ISSUE TITLE
Latest version, upon installing metamask, accounts array is empty

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#2218]
I just tried installing the latest metamask on a fresh google chrome browser profile and after setting it up, when i call
```
web3.eth.getAccounts(function(err,accounts){
});
```
err is null and accounts is an empty array

On profile where metamask was already installed I do not have this issue

**Comment by wighawag** [comment]
After creating a new account (Account 2) getAccounts return that account
Then switching back to the first it works too

**Comment by danfinlay** [comment]
Thanks for the report & reproduction steps, found the issue & fixed, publishing soon, hopefully including a couple other fixes.
