### ISSUE TITLE
I don't understand... :c

### ISSUE THREAD

**Issue by efichot** [MetaMask/metamask-extension#2220]
Hi everyone, I don't understand why async function or promise call don't work with metamask when i  create a smart contract like below:
```js
Conference.new({ from: accounts[0], gas: 3141592 }).then((conference) => {
  console.log(conference.address);
});
```
--> log nothing but the smart contract are deploy on testrpc but can't enter in my promise call... :(

**Comment by danfinlay** [comment]
This looks like a question for some JavaScript library that you're using. Is this Web3? What version? EthJS? What version? Are you sure that library supports promises?

Also, this title is useless. Please re-submit with better information.
