### ISSUE TITLE
[Bug]: No EIP-6963 Provider Detected Error on the Test Dapp

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#22211]
### Describe the bug

The error comes up as soon as I load the test dapp. This started occurring after I investigated an issue with two added MetaMask wallets on the same Chrome profile and hasn't resolved afterwards. Cache cleaned, restarted browser, deleted all wallets, installed a fresh one, tried loading on a different Chrome profile and that works as expected, only on the current profile I can't seem to work around it. I cannot even connect to the MetaMask wallet on the Test Dapp. 

### Expected behavior

The Test dapp loads and allows connection. 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/3a038ed7-4610-43f9-a82f-786fe12f27db

### Steps to reproduce

Possible scenario that leads to the error, from my experience:

1. Install two MetaMask wallets, of different versions (for instance, v11.7.0 and v.11.6.0). 
2. While they are both enabled here chrome://extensions/, add some custom networks on one of them, switch between them and perform some transaction cancellations.

### Error messages or log output

```shell
index.js:716 Error: missing provider (argument="provider", value=undefined, code=INVALID_ARGUMENT, version=providers/5.0.24)
    at lib_esm_Logger.makeError (index.js:166:1)
    at lib_esm_Logger.throwError (index.js:175:1)
    at lib_esm_Logger.throwArgumentError (index.js:178:1)
    at new Web3Provider (web3-provider.js:56:19)
    at initializeContracts (index.js:652:1)
    at initializeProvider (index.js:577:1)
    at setActiveProviderDetail (index.js:397:1)
    at setActiveProviderDetailWindowEthereum (index.js:417:1)
    at initialize (index.js:2432:1)
```

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Closing this issue as we're not able to reproduce this anymore.
