### ISSUE TITLE
How to remove - "Request may not be safe" warning for security providers ?

### ISSUE THREAD

**Issue by dev-ramverma** [MetaMask/metamask-extension#22218]
### What is this about?

Error -

Request may not be safe
Because of an error, this request was not verified by the security provider.Proceed with caution
![WhatsApp Image 2023-12-07 at 10 42 32](https://github.com/MetaMask/metamask-extension/assets/118476064/2b6868fd-d95e-42b3-9030-3c3e0b251ccf)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Jonath-z** [comment]
Can I look into this?

**Comment by dev-ramverma** [comment]
Please

**Comment by Jonath-z** [comment]
I would like to get more information about this issue. @dev-ramverma

**Comment by dev-ramverma** [comment]
You can visit - https://blockstarcoin.com/

**Comment by bschorchit** [comment]
Could you update to the latest version v11.7 and confirm this is still happening?

**Comment by cryptocodyram** [comment]
Request may not be safe

![Uploading Screenshot 2023-12-23 at 6.54.12 PM.png…]()

**Comment by cryptocodyram** [comment]
<img width="463" alt="Screenshot 2023-12-23 at 7 25 19 PM" src="https://github.com/MetaMask/metamask-extension/assets/54006364/db34d11d-4458-40c5-b9e8-4845055ba172">

**Comment by cryptocodyram** [comment]
Current Metamask version is 11.7.2 @bschorchit

**Comment by g1tt** [comment]
I am receiving this error now, if this will help to resolve the problem!
I am at https://pacific-bridge.manta.network/
I try to bridge ETH to Manta Pacific Mainnet
I see this warning -

![image](https://github.com/MetaMask/metamask-extension/assets/43521452/e9f52d20-c441-4572-bc49-0df2980c8f15)

I am using MetaMask 11.7.3 on Brave 1.61.116 Chromium 120.0.6099.217. Windows 10 22H2.

HTH!

**Comment by TerryGuo** [comment]
I am also running into this problem:
<img width="311" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/1544365/0b536043-b093-400c-9ae9-36b07152633c">

**Comment by GitHerDoneSon** [comment]
> Can I look into this?

Did you ever figure out what this "Request may not be safe." MetaMask warning is about? Would really like an answer. Thanks.

**Comment by GitHerDoneSon** [comment]
> ### What is this about?
> Error -
> 
> Request may not be safe Because of an error, this request was not verified by the security provider.Proceed with caution ![WhatsApp Image 2023-12-07 at 10 42 32](https://private-user-images.githubusercontent.com/118476064/289283674-2b6868fd-d95e-42b3-9030-3c3e0b251ccf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTE1NDEsIm5iZiI6MTcwODE5MTI0MSwicGF0aCI6Ii8xMTg0NzYwNjQvMjg5MjgzNjc0LTJiNjg2OGZkLWQ5NWUtNDJiMy05MDMwLTNjM2UwYjI1MWNjZi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMTczNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTlhYzhiM2IzOTg0MTkzZTMwMWI5YzkwZWQyNTk5MTViMDkyYjczMGZlNDJlNDNjNTExZWNkM2U1NGQ4YWM1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BdgjVvxcyoeDpqzrSkrlYT9nf0bOS3S0q636IC56zfQ)
> 
> ### Scenario
> _No response_
> 
> ### Design
> _No response_
> 
> ### Technical Details
> _No response_
> 
> ### Threat Modeling Framework
> _No response_
> 
> ### Acceptance Criteria
> _No response_
> 
> ### Stakeholder review needed before the work gets merged
> * [ ]  Engineering (needed in most cases)
> * [ ]  Design
> * [ ]  Product
> * [ ]  QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
> * [ ]  Security
> * [ ]  Legal
> * [ ]  Marketing
> * [ ]  Management (please specify)
> * [ ]  Other (please specify)
> 
> ### References
> _No response_

Hey Ramverma! Did you ever figure out what this message on metamask means?

**Comment by GitHerDoneSon** [comment]
> Can I look into this?

Hey I'm still trying to figure out what this metamask message means. If you ever did, please let me know! Thank you.

**Comment by GitHerDoneSon** [comment]
> I am also running into this problem: <img alt="image" width="311" src="https://private-user-images.githubusercontent.com/1544365/296919975-0b536043-b093-400c-9ae9-36b07152633c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTEzODEsIm5iZiI6MTcwODE5MTA4MSwicGF0aCI6Ii8xNTQ0MzY1LzI5NjkxOTk3NS0wYjUzNjA0My1iMDkzLTQwMGMtOWFlOS0zNmIwNzE1MjYzM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMTczMTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM0OGZhYjYxMjQ2YjEzNjk0MmVlNDZkMTdmNzU1MTQ4NmJlZjJmZDkwYzRjYjgzMWUwM2E4YmJiYjRlODM0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I76Wu8jt4BFDvHVpqrg0opl2SffvRj9QrZIslsPLT4M">

Hi, did you ever find out what to do with this message? Did you click through anyway? Or find another solution? Thanks

**Comment by GitHerDoneSon** [comment]
> I am receiving this error now, if this will help to resolve the problem! I am at https://pacific-bridge.manta.network/ I try to bridge ETH to Manta Pacific Mainnet I see this warning -
> 
> ![image](https://private-user-images.githubusercontent.com/43521452/296875720-e9f52d20-c441-4572-bc49-0df2980c8f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTEzODEsIm5iZiI6MTcwODE5MTA4MSwicGF0aCI6Ii80MzUyMTQ1Mi8yOTY4NzU3MjAtZTlmNTJkMjAtYzQ0MS00NTcyLWJjNDktMGRmMjk4MGM4ZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE3MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZmMxNDNmODFhNTdiMmRiMTBiMjM5ZDIzYzUwMzNiYTdhNTEyZjVlMThjOTMyNGViMWM0NWYzMmM1Zjg5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.APOKt0kKvfX-ve8csfUFzKvXsVdTxi2pJlt7mfL46qc)
> 
> I am using MetaMask 11.7.3 on Brave 1.61.116 Chromium 120.0.6099.217. Windows 10 22H2.
> 
> HTH!

Hey what did you end up doing with this message you saw on metamask? Did you click through? And if so what happened? Thank you!

**Comment by bschorchit** [comment]
Hey, we currently have an issue that is causing this message to appear more frequently than it should. We're rolling out a fix in v11.9.5 that solves it. 
Please update to this version and let me know if you're still encountering it.

**Comment by cryptocodyram** [comment]
I had a problem with the Tether interface. I used the Openzepplin ERC20 interface instead of Tether interface.
ERC20 interface - { transfer(address to, uint256 amount) → bool }
Tether interface - { transfer(address _to, uint _value)  -> no return }

**Comment by Nebula-Spark** [comment]
> Could you update to the latest version v11.7 and confirm this is still happening?

Hello,
Still facing the same issue @ AAVE Leding Protocal durining asset switch transaction!
Is that safe to process the transcation or should we need to wait for that error fix?

Version 11.10.0

**Comment by SvenMeyer** [comment]
@bschorchit Any updates ?
How often does that happen ?
And do we know why or under what circumstances ?

**Comment by artiface** [comment]
> Hey, we currently have an issue that is causing this message to appear more frequently than it should. We're rolling out a fix in v11.9.5 that solves it. Please update to this version and let me know if you're still encountering it.

Just update to 11.10.1  and i see this message on every transaction now?  Can you give any explanation about what it means or what causes it?

**Comment by SvenMeyer** [comment]
Who is actually the "Security Provider" ?

**Comment by SvenMeyer** [comment]
Should 11.11.3 fix this problem ?

**Comment by redcomethk** [comment]
<img width="339" alt="Screenshot 2024-03-08 at 8 51 07 PM" src="https://github.com/MetaMask/metamask-extension/assets/2778099/4fb789ae-1151-4a8e-af47-65a7d31db9dd">
The version I am using is also 11.10.1
It seems that the details cannot be shown properly.

When "Report an issue" is pressed a page for https://blockaid-false-positive-portal.metamask.io/ is shown.

**Comment by redcomethk** [comment]
@artiface Have you tried to call the same method in https://etherscan.io/ for example? I tried that and that "Request may not be safe" box does not appear...
I guess that maybe caused by some frontend libraries involved.

**Comment by artiface** [comment]
> @artiface Have you tried to call the same method in https://etherscan.io/ for example? I tried that and that "Request may not be safe" box does not appear... I guess that maybe caused by some frontend libraries involved.

So yes, there are some instances where I do not get the warning message, like Opensea transfers did not show it.  But the majority of sites I interact with still show this message.  If it's supposed to be a warning, this will lead quickly to warning fatigue and the messages being ignored.  

I updated to 11.11.4 and this message is still present.  

I use PocketUniverse extension which already simulates transactions to show what transactions will do before approving them, and all these transactions are safe, so why is Metamask flagging them with a bogus "warning"?

**Comment by GithubsFan2024** [comment]
Hi guys,

I also received this "Request may not be safe" message when signing a contract. Someone in Reddit told me that it's a new security feature of Metamask powered by Blockaid. It can be turned on and off. Here's the detailed link. 

https://support.metamask.io/hc/en-us/articles/19878220833947-How-to-turn-on-Blockaid-security-alerts

Hence, my question is that is this really an issue (a bug or something that needs to be fixed)? I'm a newbie. Please advise. Thank you.

**Comment by starlabs007** [comment]
This is a big issue. This is showing up for one of our contracts on ethereum. It states that the contract is unverified but the contract is **_FULLY_** verified on etherscan.io. Obviously this is alarming our users. I have already used the `Report an issue` link.

![Image from iOS](https://github.com/MetaMask/metamask-extension/assets/8631608/64817001-7c68-4a83-8d2f-0e93f46f92b7)

**Comment by bschorchit** [comment]
Thank you for the reports! Would you mind clicking on report an issue within the warning, that will make sure the info needed gets in the most efficient and fast way to the relevant team so we address those in a timely manner. Thank you so much! 
I'm also making the team aware of this.

**Comment by starlabs007** [comment]
Yes, I've reported the issue within the warning as well as reported it directly to BlockAid. I neglected to include my email in the first report, but did include it when I reported the issue to BlockAid. To their credit, I received a reply within 2 days that this was indeed a flagging error and that it has been resolved. 👍 
Thank you.

**Comment by SquidFinder** [comment]
receiving this error with wagmi and wallet connect front end build

**Comment by SvenMeyer** [comment]
Blockaid , which is the "Security" provider Metamask used present way too often warning even on totally safe websites and contracts. If you are sure that it is safe you can ..

If users are presented with this warning on our website, they shall

- click on See details
- click on Report an issue
- write that Blockaid is wrong and all is good

**Comment by NeeteshMaurya** [comment]
> Yes, I've reported the issue within the warning as well as reported it directly to BlockAid. I neglected to include my email in the first report, but did include it when I reported the issue to BlockAid. To their credit, I received a reply within 2 days that this was indeed a flagging error and that it has been resolved. 👍 Thank you.

What do you mean by flagging error here? do i need to make changes in my contract if i am getting same warning as you were getting it or they will resolve it by their side?

**Comment by Rooibossie** [comment]
**Request may not be safe**

**Because of an error, this request was not verified by the security provider. Proceed with caution**.
So frustrating, i am also getting this error message a lot lately on while on Aave de-fi platform. I've was on Microsoft Edge web browser but i have switched over to Firefox. I checked and yes, i am using the latest version of Metamask.
When i was using Metamask on Microsoft Edge the Matic balance was also incorrect. Now that i am on Firefox it has been resolved.
Using windows 10. I don't know what other info. you require. I tried to report it to Github but that just led me down the garden path completely off course. Seems like this BlockAid is being overbearing.
James Warrington, South Africa
jwarrington4@gmail.com

**Comment by SvenMeyer** [comment]
Looks like Blockaid is the problem and their "algorithm" hasn't improve a bit since months ... and MetaMask continues to use them "as is" :-(

**Comment by SvenMeyer** [comment]
@bschorchit Any updates ... plans you can share ?

**Comment by bschorchit** [comment]
Hey all, we're continuously working on improving the experience around this feature. 
If your contract is being incorrectly flagged, clicking on "Report an issue" within the warning and submitting the form will make sure the needed information get to both us and Blockaid and that the issue is addressed in up to 24 hours. We're also actively working on allowing the issue to be addressed quicker as well. 

Here are some details on the challenges of building a robust solution to prevent malicious transactions: https://x.com/blockaid_/status/1780326332519346249

**Comment by bschorchit** [comment]
Closing this issue for now. Please do report if encounter any issues with this feature in the future!

**Comment by tokdaniel** [comment]
It is still an issue though.
