### ISSUE TITLE
[Bug]: cannot open in opera - ubuntu 22

### ISSUE THREAD

**Issue by abraham-yusuf** [MetaMask/metamask-extension#22221]
### Describe the bug

![image_2023-12-10_172435823](https://github.com/MetaMask/metamask-extension/assets/76843145/3d2e3ed6-5c52-40c2-9737-28c198ab7857)

cannot open the extensions, just overload 

### Screenshots/Recordings

![Cuplikan layar dari 2023-12-10 17-22-34](https://github.com/MetaMask/metamask-extension/assets/76843145/9ad53cd6-2ecf-4df5-a4a7-aceb1effcb02)

### Steps to reproduce

re-install metamask will got works again

### Version

11.4.1

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Linux

### Severity

localForage -- Offline Storage, Improved
    Version 1.10.0
    https://localforage.github.io/localForage
    (c) 2013-2017 Mozilla, Apache License 2.0

**Comment by gauthierpetetin** [comment]
Closing this issue as we're not able to reproduce
