### ISSUE TITLE
[Bug]: Keystone unable to verify sign permit on test dapp

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#22256]
### Describe the bug

Observed this in feature testing and confirmed this is present in 11.7.0.  Testing with Keystone 3 pro with firmware 1.2 with chrome 117.0.5938.92 on Sonoma 14.0.

I am otherwise able to Eth sign, Personal sign, Sign typed data v3, and sign typed data v4 with a Keystone. 

### Expected behavior

Should be able to verify the signer= public address in the test dapp.

### Screenshots/Recordings

https://recordit.co/CjyEhhhart

### Steps to reproduce

1. Configure a wallet and bind a keystone address
2. Connect to the test dapp https://metamask.github.io/test-dapp/
3. Scroll down to Sign permit
4. tap sign in test dapp
5. tap sign in MM 
6. tap extension again to show QR because of annoying bug previously reported in [19780](https://github.com/MetaMask/metamask-extension/issues/19780)
7. Scan QR with Keystone
8. Sign on Keystone
9. Scan signed QR with MM
10. tap verify
11. Note console error

### Error messages or log output

```shell
Failed to verify signer when comparing 0x... to 0xpublicAddress
```

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Keystone

**Comment by plasmacorral** [comment]
Will note that this appears to be limited to V3 hardware. Confirmed today that 1.2 on v3 cannot verify signature, but V2 running M-12.4

**Comment by angelcheung22** [comment]
AirGap has no issue, but Keystone device have issues. And related to sign typed v1 data only. 
Pending on Keystone devices for team to look at this issue.

**Comment by angelcheung22** [comment]
Pending supporting from Keystone team.

**Comment by vivek-consensys** [comment]
Tested with latest version of test-dapp v8.7.0 and working as expected. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0tBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc376fc068a6b381913ee3238177ecd786812c28/Screen%20Recording%202024-04-22%20at%2016.08.06.mov)
