### ISSUE TITLE
[Bug]: Manually entered network is automatically selected without awaiting user confirmation

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#22255]
### Describe the bug

Noticed this testing a feature branch and confirmed this issue in production v11.7.0 when testing with Chrome 117.0.5938.92 on sonoma 14.0

Observed testing on local host and confirmed this impacts an RPC that is manually entered.  This is not impacting networks that are pre-populated or when the user adds the new network via a dapp.

### Expected behavior

When a new network is manually entered, do not change to it until user provides consent.

### Screenshots/Recordings

https://recordit.co/ZERFaHLPBH 

### Steps to reproduce

1.  Have a wallet configured
2. Navigate to chainlist.org and choose a network
3. Goto network dropdown and select `Add network`
4. Select `Add a network manually`
5. Copy/paste the values from chainlist manually
6. tap `Save` once completed
7. Note that when the network is added, it becomes selected even though the modal seeking consent had not been ack'd
8. Tap `Dismiss` and note that newly added network is selected

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
I think this is the same as https://github.com/MetaMask/metamask-extension/issues/20581

**Comment by plasmacorral** [comment]
Sure is. Closing.
