### ISSUE TITLE
Create contract information ConfirmInfoRow

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#22277]
We need a component that should display the contract information, etc for the confirmation:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53c30e27f65806b7b6f18ece82e1bc12be9e9099/Screenshot%202023-10-10%20at%204.15.26%E2%80%AFPM.png)

We should support petnames as it's recently been launched. It is currently behind a flag. Should we support an alternative UI while petnames has not been fully launched? 

Please note that not every request will have a contract.

Designs: https://www.figma.com/file/uACzbBjwU2tV30UuewYiTx/Confirmation-redesign-V2?type=design&node-id=775-28145&mode=design&t=fcwGIVZS3lkt9rOO-0

**Comment by seaona** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/22277?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @segun

**Comment by seaona** [comment]
From standup:
- It should use the petname on the value
- Should it be the same for address vs contract? -> designs could be updated if needed for this task, since petnames was added after the designs were created

**Comment by jpuri** [comment]
This component is same as address value component, hence closing this issue.
