### ISSUE TITLE
Add e2e test to validate that the show hex data toggle in settings works

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#22271]
The task is to add a new e2e test: `show-hex-data.spec.js`

The file can be added in the `test/e2e/tests/` directory.

It should follow the structure and patterns of the other tests in that directory. `test/e2e/tests/simple-send.spec.js` is a simple example.

The test should navigate to the Advanced tab of Settings. An example of how to do this can be seen within the `passwordUnlockOpenSRPRevealQuiz` helper method. Then it should toggle on the "Show Hex Data" toggle

![Screenshot from 2023-12-13 13-01-23](https://github.com/MetaMask/metamask-extension/assets/7499938/70765cc0-8840-453a-9460-6f848a98ab47)

Then it should navigate to the home screen. From there it should naviate to the send screen, the `openActionMenuAndStartSendFlow` helper can be used for that.

A recipient address should be entered on the send screen (see `test/e2e/tests/send-eth.spec.js`  for examples of how to do that. Then `0xabc` should be entered in the hex data field.

The test should then click next, and confirm that the expected hex data is shown on the Data tab of the confirm screen. The test does not need to take further steps after that.

**Comment by lltx16888** [comment]
0xF605B8D08732AA49B008C837067DD87CE61C26C7
