### ISSUE TITLE
[Bug]: User survey not showing up on home screen

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#22284]
### Describe the bug

The user survey added in this PR: https://github.com/MetaMask/metamask-extension/pull/21918 is not showing up. The test was performed on three types of builds: [PR build ](https://github.com/MetaMask/metamask-extension/pull/21918#issuecomment-1839006151) which shows up as v11.6.3, [RC latest build](https://github.com/MetaMask/metamask-extension/pull/22201#issuecomment-1853519301) and v11.8.0 built locally. 

### Expected behavior

The user survey shows up on the home screen. 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/cb106483-12ac-4c43-9009-1d6ebfaeea05

### Steps to reproduce

1. Load a freshly installed MetaMask extension
2. Fill in your SRP and password
3. Skip onboarding and "what's new"
4. Check home screen on both expanded and pop-up view
5. Notice there is no user survey showing up

### Version

11.8.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by kevinghim** [comment]
Hi @benjisclowder this survey has a timebound exposure of Jan 17 Wed between 11am-12pm EST. Here's the original planning issue: https://github.com/MetaMask/MetaMask-planning/issues/1650

**Comment by benjisclowder** [comment]
> Hi @benjisclowder this survey has a timebound exposure of Jan 17 Wed between 11am-12pm EST. Here's the original planning issue: https://github.com/MetaMask/MetaMask-planning/issues/1650

Hi Kevin, so 11.8.0 does not actually include this survey, but it is externally triggered on a specific date?
