### ISSUE TITLE
Incorrect "Password too short" validation error

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2229]
A user with an existing account (with a long password) got locked out of vault with a "Password too short" warning.

**Comment by Zanibas** [comment]
Tested with a password that is 849888 characters long--didn't get anything weird. There's also no validations on our unlock password input enforcing short passwords

**Comment by danfinlay** [comment]
From `Makc` on our Slack:

> When you created a new wallet on 3.10.6 (as me) and send money on it, and you try to use an old version, when you enter your seed + password (even if more than 8 caracteres) you can't open the wallet ^^

<img width="381" alt="capture d ecran 2017-09-29 a 19 17 56" src="https://user-images.githubusercontent.com/542863/31038026-3f4fe40c-a529-11e7-9abe-8a4c7bc9794e.png">

**Comment by Zanibas** [comment]
So it appears this is related to seed restoration. Still investigating

**Comment by tmashuang** [comment]
Closing, will reopen if other users are experiencing this issue.
