### ISSUE TITLE
[Bug]: Swap shows as Dropped in MM UI and successful on chain (example - LINEA) 

### ISSUE THREAD

**Issue by LoveKosmos** [MetaMask/metamask-extension#22312]
### Describe the bug

Swap shows as Dropped in MM UI and successful on network

### Screenshots/Recordings

![Screenshot 2023-12-17 at 1 04 42 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/a33cd58e-d44b-489e-bae7-2f0649353fa4)

![Screenshot 2023-12-17 at 12 38 17 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/3f99c7f4-c069-40a8-8c6c-a04745c1f5c5)

![Screenshot 2023-12-17 at 12 38 27 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/881aff03-c1ab-46b6-9fde-e8b516a03c39)

![Screenshot 2023-12-17 at 12 39 35 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/6d1b40e9-0e41-489e-b4e3-b5767c553726)

![Screenshot 2023-12-17 at 12 45 11 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/21347f02-4d00-489d-ae4e-52422ac76609)

![Screenshot 2023-12-17 at 12 58 46 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/554f41b9-d336-4078-a801-47ae0692d231)

![Screenshot 2023-12-17 at 12 43 46 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/00808bda-f45a-4c97-9cb5-cb7849aa90e1)

![Screenshot 2023-12-17 at 12 43 56 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/5fab664a-d74d-4c5a-a130-a2e06156d6ac)

![Screenshot 2023-12-17 at 12 44 22 PM](https://github.com/MetaMask/metamask-extension/assets/12563620/51431959-e095-4355-821e-7ce0e1b0a243)

### Steps to reproduce

The following was tested on Linea Mainnet 

1. Go to the Swap feature in MM UI 
2. Select token ( my example ETH to USDC) and add the amount
3. Once the estimation of gas is in place confirm the swap ( I have confirmed that gas fees were within current market values that should cover the swap) 
4. When clicking on a hyperlink "View Swap on lineascan.build"  within the 'Processing.. " view it leads to the pending tx 
5. Click on the "View in activity" button within the 'Processing.. " view - and at that time the UI showed that Swap was Failed 
5. Later on in MM UI swap appears as dropped, but when you click on "View on block explore" - it leads you to the successful tx on chain [https://lineascan.build/tx/0x028025cc34cc0889084a71a2d0c20950d42d055d527e0711abbf9cda928ee19e](url)

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by nkeywal** [comment]
The issue we received from Lynex (a Linea partner) is that it receives "nonce already nonce" messages on RPC calls (not only MM). It seems to be new, i.e. something, somewhere, made this return message more frequent than before. The discussion here is interesting: https://github.com/ethereum/go-ethereum/issues/22093

My interpretation is:
- infura may duplicates messages (hence the transaction is received multiple times, so MM receives the message above) more than it used to do. Still, imho, Infura should be allowed to duplicate messages, so the rest of the architecture should support this. Still, rhere is likely a problem there (possibly on infura, as not only Linea sees this increase of this message it seems), but it's not the only place with a problem.
- MM does not react properly to this message, and considers that the transactions was dropped. But the geth message does not say the transaction was not received, it says "I've received it already. That would be a MM bug that seems important.
- I personally think that geth should not return this message cf; the discussion in the github issue above: "idempotent operation and no matter how many times you call it, you should always get the same result"), but it's not possible short term on all network in any way.
