### ISSUE TITLE
[Bug]: Invalid warning "This is a potential scam" when chainid.network check enabled

### ISSUE THREAD

**Issue by aspiers** [MetaMask/metamask-extension#22316]
### Describe the bug

In the last 24-48 hours or so, I have started to see a warning triangle icon to the right-hand side of the balance of every native (i.e. gas) token on every chain for every wallet:

![image](https://github.com/MetaMask/metamask-extension/assets/100738/d24a5191-a831-4a26-a56e-46422c70bd3d)

Clicking on the warning icon yields this message:

![image](https://github.com/MetaMask/metamask-extension/assets/100738/0bffa617-e0ae-48a3-819e-be08e33a53ba)

[Apparently this has been acknowledged by MetaMask Support](https://twitter.com/fusegold/status/1736703773844648291), but I couldn't see any issue already filed here on GitHub, so I'm filing one.

### Expected behavior

No misleading warning should appear.

### Steps to reproduce

1. Have MetaMask Chrome extension 11.7.0 installed on Chrome
2. View the balances of any wallet.

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Additional context

I have confirmed this is a brand new issue on two separate machines I own.  It happens for every wallet on multiple networks (e.g. Ethereum, Polygon, Celo).

**Comment by 4u2hear3000** [comment]
![Untitled 4](https://github.com/MetaMask/metamask-extension/assets/135171640/9e49604d-33ec-41db-8f03-6063f8beb26b)

If I switch the "Network details check" Off, the triangle and warning disappear. However, the Portfolio still not showing anything!! at "portfolio.metamask.io/?metamaskEntry=ext_portfolio_button&metametricsId=null "

**Comment by aspiers** [comment]
> If I switch the "Network details check" Off, the triangle and warning disappear. 

Same here, good find! So this is a bug with how MM interacts with chainid.network.  If there is an issue with the latter, then MM should be able to handle that gracefully rather than issuing misleading warnings.

**Comment by kacperzuk-neti** [comment]
Perhaps related: #22315 .

**Comment by anaamolnar** [comment]
Hello, @aspiers. Thanks for reporting! Please make sure to update to 11.7.1. This should fix the issue. You will be able to update manually from your browser. Go to extensions-> Metamask->Details->Enable developer mode from the top right, then there should be a button for Updating in the top left. Please let us know if you still encounter the issue after updating.

**Comment by aspiers** [comment]
@anaamolnar I can confirm this is fixed in 11.7.1. Thanks a lot!  Please can you link the commit or PR which fixed this?  It's normally best to reference the issue from the commit / PR which fixes it, as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by 4u2hear3000** [comment]
Perfect, upgraded to 11.7.1 and back to normal - many thanks

**Comment by 4u2hear3000** [comment]
> > If I switch the "Network details check" Off, the triangle and warning disappear.
> 
> Same here, good find! So this is a bug with how MM interacts with chainid.network. If there is an issue with the latter, then MM should be able to handle that gracefully rather than issuing misleading warnings.

Good Morning,

MetaMask extension is doing the same when using Ethereum. It is not showing the tokens and prompting for transaction confirmation. It is only on Ethereum, but working fine on other networks  such as BNB or Polygon!!
![Untitled 5](https://github.com/MetaMask/metamask-extension/assets/135171640/df824198-7168-4483-baaa-9105f59df0c6)
Using version 11.7.2

**Comment by anaamolnar** [comment]
Hey @4u2hear3000 Please try the following [settings](https://support.metamask.io/hc/en-us/articles/360038139452-MetaMask-states-Balance-may-be-outdated-displays-in-orange-or-ETH-not-added-to-balance) and let me know if you still encounter this issue.
