### ISSUE TITLE
[Bug]: Error when trying to speed or cancel transaction on Firefox.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#22314]
### Describe the bug

Every time when transaction is sped up or cancelled you can the error in the background console.

### Expected behavior

There should be no error.

### Screenshots/Recordings

Sepolia:

https://github.com/MetaMask/metamask-extension/assets/104780023/edc894ce-495b-4350-b647-fca9518959ea

Linea Goerli:

https://github.com/MetaMask/metamask-extension/assets/104780023/59ebe381-9978-463d-956a-4cc2495497fb

Errors are the same for speeding up and cancelling:
<img width="470" alt="Screenshot 2023-12-18 at 12 57 49 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/d7d50583-b00b-4cd7-b475-2e896ff791bc">

### Steps to reproduce

1. Connect to Sepolia or Linea Goerli testnet
2. Send regular Eth transaction or deploy the contract with low gas setting so you have time to speed it up or cancel
3. Try to speed up / cancel
4. See the error message in the background console

### Version

11.8.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
MetaMask 11.6.2 Firefox - I'm seeing different errors when trying to speed up / cancel transaction. UI for cancelled transaction looks different.
<img width="574" alt="Screenshot 2023-12-18 at 9 43 43 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/4d1a3c8a-0e4a-434a-b251-01380e8a3acc">
<img width="721" alt="Screenshot 2023-12-18 at 9 42 49 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/92d2c9d2-6ccf-4a2f-af91-c0ad2d2ef0d7">
<img width="474" alt="Screenshot 2023-12-18 at 9 41 12 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/0f71b40d-ac79-4130-829a-3a87a42550ee">
<img width="720" alt="Screenshot 2023-12-18 at 9 43 19 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/284e13cb-e12c-4094-bb87-8a30d812be1d">

**Comment by benjisclowder** [comment]
This is what I got inn two different instances of Firefox, on Sepolia. Steps: Deploy erc20 contract --> approve tokens --> transaction is stuck on pending and in the end it does get confirmed but this error shows up both in speeding up and cancelling the pending tx.

![image](https://github.com/MetaMask/metamask-extension/assets/120041701/cffc013b-8bec-46a1-bc5a-9b8014a47857)

![image](https://github.com/MetaMask/metamask-extension/assets/120041701/85e87f92-79c6-40f3-a1a2-a06c740f98ae)
