### ISSUE TITLE
[Bug]: Gas section is not present in the Confirmation screen if the transaction would fail (for any reason)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22339]
### Describe the bug

**Problem:** whenever the transaction is going to fail (for any reason - i.e. trying to send a token you don't own) the gas section disappears from the Confirmation screen.

There are several problems related to not properly handling failing transactions, but those were reported in other tickets (i.e. https://github.com/MetaMask/metamask-extension/issues/17866)
This ticket is specific for the gas section not being present, which is a new behaviour.

### Expected behavior

The gas section should be present in the confirmation screen

### Screenshots/Recordings

![Screenshot from 2023-12-19 14-36-47](https://github.com/MetaMask/metamask-extension/assets/54408225/6c8ae6a2-0535-4d17-836a-7889bbd58a14)

### Steps to reproduce

You can get this behaviour by triggering a failing transaction. I.e.
1. Select Mainnet
2. Go to this contract https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52#writeContract
3. Connect the wallet
4. Click transfer
5. Add any recipient and an amount greater than your balance
6. See confirmation screen without gas
https://github.com/MetaMask/metamask-extension/assets/54408225/5ac0caf6-264f-49ee-bf64-99e71d2991d7

### Version

This issue will be introduced in 11.9.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
It seems there was possibly already some issue with displaying the gas component when we fail to estimate gas in v11.7 per the screenshot in this ticket https://github.com/MetaMask/metamask-extension/issues/22318 (Total component is displayed and includes a high gas value, but the gas value part is not displayed).
