### ISSUE TITLE
[Bug]: Intrinsic Gas Too Low - MM can't estimate gas on 11.7.0 for Viem

### ISSUE THREAD

**Issue by mpeyfuss** [MetaMask/metamask-extension#22359]
### Describe the bug

When I go to deploy a contract from our dashboard, MM properly recognizes that I am going to deploy a contract. On 11.6.2, if I submit the transaction, gas is properly estimated. On 11.7.0, the transaction interface looks a bit different than I remember and when I submit the transaction, it fails with error code -32603 "Intrinsic gas too low: needed 81164, allowed 21000".

### Expected behavior

I expect that gas is estimated properly and the transaction succeeds. This seems to only affect interactions built with Viem and not those built with Ethers. I'll be submitting an issue with Viem as well, but other wallet clients and 11.6.2 of MM work with Viem so it seems to be MM 1.7.0 related.

### Screenshots/Recordings

<img width="350" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/82735893/947628bc-6c9d-4269-be65-65c4d6831410">

![image](https://github.com/MetaMask/metamask-extension/assets/82735893/c12f1006-c510-4f60-9989-10dd0e5beab5)

### Steps to reproduce

1. Go to https://stackblitz.com/github/wevm/viem/tree/main/examples/contracts_deploying-contracts
2. Wait for the example to build
3. Connect MM
4. Click `deploy`
5. Submit tx
6. See that tx failed in MM
7. Open console to inspect the failure 

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

Pretty critical as our users can't deploy contracts on the latest MM version

**Comment by anaamolnar** [comment]
Hello, @mpeyfuss. Thanks for reporting! I will pass this on to the appropriate team.

**Comment by YoonsooKim9** [comment]
Same issue on 11.7.3. Please let me know if there is any other solution or update on this issue.
