### ISSUE TITLE
[Bug]: missing v when sending transaction

### ISSUE THREAD

**Issue by irfanonk** [MetaMask/metamask-extension#22353]
### Describe the bug

when calling a function from smart contract using ethers.js and metamask as browser provider, it returns uncatchable error. It prevents to wait the transaction result, yet the transaction is succeeds in the blockchain. 

 

### Expected behavior

It should call a smart contract function without error.

### Screenshots/Recordings

<img width="356" alt="Screenshot 2023-12-20 at 10 50 09" src="https://github.com/MetaMask/metamask-extension/assets/57913715/973ff6fc-7826-4ccc-b4e9-48f93464d627">
<img width="370" alt="Screenshot 2023-12-20 at 10 54 34" src="https://github.com/MetaMask/metamask-extension/assets/57913715/c87e4506-4d40-4e87-841e-7bc191d50c41">

### Steps to reproduce

1. Call a function from a smart contract that requires fee  (like approve from ERC20 Token contract) in your web3 app
2. Confirm the transaction using metamask
3. Checkt the logs in the console 

### Error messages or log output

```shell
`
Uncaught (in promise) TypeError: missing v (argument="signature", value={ "accessList": null, "blockHash": null, "blockNumber": null, "from": "(sender address)", "gas": "0xf856", "gasPrice": "0x2540be400", "hash": "(removed)", "input": "(removed)", "maxFeePerGas": "0x2540be400", "maxPriorityFeePerGas": "0x2540be400", "nonce": "0x16", "r": "(removed)", "s": "(removed)", "to": "(removed)", "transactionIndex": null, "type": "0x2", "value": "0x0" }, code=INVALID_ARGUMENT, version=6.9.0)
`
```

### Version

11.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

This issue experiencing only in  google chrome browser, not occurs in microsoft edge or firefox. It may not happen sometimes but most of time it occurs, especially successive function calls from smart contract.

Do not work on:
Google Chrome Version 119.0.6045.199 (Official Build) (arm64) and Version 120.0.6099.109 (Official Build) (arm64)
Mumbai Network
metamask 11.7.0
ethers 6.8.1

Works on:
Firefox 121.0
Mumbai Network
MetaMask 11.4.1
ethers 6.8.1

Microsoft Edge Version 119.0.2151.97 (Official build) (arm64)
Mumbai Network
MetaMask 11.6.2
ethers 6.8.1

**Comment by daenamkim** [comment]
@irfanonk I got the same issues before and I think 11.7.2 seems fixing the issue according to my test.

**Comment by daenamkim** [comment]
@irfanonk FYI, related to issue at [here](https://github.com/ethers-io/ethers.js/issues/4513) as well.

**Comment by anaamolnar** [comment]
Hello, @irfanonk. Thanks for confirming! I will close this issue then. Feel free to open this again if this continues to occur.
