### ISSUE TITLE
EtherDelta Error message: "You are connected to MetaMask, but you are either using a non-MetaMask account, or you are not logged into the MetaMask account you have selected. Check this in MetaMask, then refresh and try again"

### ISSUE THREAD

**Issue by MrBobSapp** [MetaMask/metamask-extension#2236]
Hi there I'm getting this message popup whenever I try to do anything on EtherDelta. I don't get why. I'm clearly logged in to the correct MetaMask account. This was never an issue for me at first, only recently. Why is this happening? 

Thanks

**Comment by danfinlay** [comment]
I believe this was a short-lived bug that is fixed in 3.10.7. You can force Chrome to update an extension by right clicking the MetaMask icon, selecting "Manage Extensions", and clicking "Update now" next to MetaMask.

**Comment by MrBobSapp** [comment]
Hello thanks for the reply. Indeed the version of Metamask I'm using is 3.10.6. However there is no option available to "Update now" after I click "Manage Extensions".  And there is no option available to update it via the google store either :/ So I'm kinda stuck.

**Comment by danfinlay** [comment]
A few options:
- Check the "Developer mode" box (might reveal the update button)
- Wait (auto-updates over time)
- Uninstall & reinstall off the Chrome store.
