### ISSUE TITLE
[Bug]: Unable to add a network with 'wallet_addEthereumChain' with token symbol length less than 2

### ISSUE THREAD

**Issue by KlausKidman** [MetaMask/metamask-extension#22389]
### Describe the bug

When adding a network using the JSON-RPC API request "wallet_addEthereumChain", I get the following error.
> Expected 2-6 character string 'nativeCurrency.symbol'. Received: Q

We tried to get around this limitation by adding a space after sybol "Q ". In the latest update, this message appeared in the latest updates

<img width="1792" alt="Screenshot 2023-12-25 at 11 50 06" src="https://github.com/MetaMask/metamask-extension/assets/70257786/c77534f4-ebb6-4ad7-81f3-ee9656eafeed">

Also, you can enter 1 character in the UI and it won't give an error.

<img width="1111" alt="Screenshot 2023-12-25 at 11 55 59" src="https://github.com/MetaMask/metamask-extension/assets/70257786/f673e245-f3c3-4bbd-8469-b00b62053998">

You can also use [this request](https://chainid.network/chains.json) to check that the network is registered with 1 character.
**chainId: 35441**

### Expected behavior

When adding a network using 'wallet_addEthereumChain' there should be no error if the token symbol length is 1.

### Steps to reproduce

```
provider.send('wallet_addEthereumChain', [
  {
    chainId: '0x8A71',
    chainName: 'Q Mainnet',
    nativeCurrency: {
      name: 'Q token',
      symbol: 'Q',
      decimals: 18,
    },
    rpcUrls: ['https://rpc.q.org'],
    blockExplorerUrls: ['https://explorer.q.org'],
  },
])
```

### Version

11.7.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

This error can be fixed for expansion on this [section of code.](https://github.com/MetaMask/metamask-extension/blob/c40dbb1ec72b91827debb2fffba4097a838f21c7/app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js#L225)

Suggestion for correction:
```
(typeof ticker !== 'string' || ticker.length < 1 || ticker.length > 6)
```

Also, it would be nice to add this change to the mobile app as well.

**Comment by anaamolnar** [comment]
Hello, @KlausKidman. Thanks for reporting! I will pass this on to the appropriate team so they can look into this issue. Happy New Year!

**Comment by jmynes** [comment]
Bumping this issue, as $FTM is rebranding to $S, which is also a 1 character ticker for their native currency
https://x.com/SonicLabs
