### ISSUE TITLE
Migrate price conversion preference to infura API

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#2240]
- [x] change to lower case
- [ ] make sure the selected option is available in our options, otherwise default to USD

**Comment by kumavis** [comment]
maybe @Zanibas or @tmashuang

**Comment by kumavis** [comment]
AFAIK, currency conversion is broken for all active users unless they got and re-select their currency

**Comment by danfinlay** [comment]
Maurcy even warned us about the first one: https://github.com/MetaMask/metamask-extension/pull/2177#issuecomment-332593481

**Comment by danfinlay** [comment]
I'm going to do the first one immediately, I hope someone will pick up the 2nd part soon.
