### ISSUE TITLE
Rename index.js to index.ts in component-library and export component types

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#22430]
### What is this about?

As part of our ongoing migration to TypeScript, all components in the component-library have been successfully converted to TypeScript. The next step in this process is to rename the index.js file in the component-library to index.ts.

This change will allow us to leverage TypeScript's static typing in the index file and will ensure consistency in our codebase. Additionally, renaming the file will enable us to export the component types directly from the index file. This will make it easier for engineers to import types, using syntax like import type { ButtonProps } from '../../component-library'.

### Threat Modeling Framework

- Rename `index.js` to `index.ts` in the component-library.
- Export the component types from `index.ts`
- Test the changes to ensure that the component-library works as expected and that types can be correctly imported.
- Update any relevant documentation to reflect these changes

### Acceptance Criteria

- The index.js file in the component-library has been renamed to `index.ts`
- All references to index.js in the codebase have been updated to `index.ts`
- Component types are being correctly exported from `index.ts`
- The component-library works as expected and types can be correctly imported in other parts of the codebase.
- Relevant documentation has been updated to reflect these changes.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Anouk1973** [comment]
Luister ik snap er niks van wil mn geld eruit en stoppen
Of praat ik een taal jullie niet begrijpen

Op vr 5 jan. 2024 00:26 schreef George Marshall ***@***.***>:
