### ISSUE TITLE
How to import new account with seed words?

### ISSUE THREAD

**Issue by stefek99** [MetaMask/metamask-extension#2243]
I had a few accounts.

Something happened (not sure what)

Now no accounts.

I've created a new den.

I have my 12 words recovery phrase.

I can import account only via private key.

What is the recommended workflow now?

* how do I remove the newly created den?
* how do I remove account in a den?

**Comment by Zanibas** [comment]
It's not immediately obvious, but to restore from seed phrase (and consequently overwrite your current seed phrase saved, be careful), lock MetaMask and click on "restore from seed" at the bottom of the screen.

**Comment by pelisboule** [comment]
Thanks for the tip Zanibas.... huge issue on my side though as I've imported the seed but my first wallet is no longer available :( How can I get the initial wallet back?

**Comment by bwheeler96** [comment]
@Zanibas I personally think this is still an issue. Developing with multiple accounts is already hard enough. If I have to overwrite my existing config to do something like... add my ropsten wallet seed phrase, then it is IMO a bug with the UX.

**Comment by stefek99** [comment]
![image](https://user-images.githubusercontent.com/249703/33554958-9739f2a6-d8f6-11e7-8764-5572bd434dec.png)

Asked on StackOverflow: https://ethereum.stackexchange.com/questions/30824/what-is-the-easiest-way-to-convert-mnemonic-phrase-into-keystore-file

**Comment by daevski** [comment]
You originally asked about Seed words, which is why I'm here. Restore with seed (and the same password as my other den) appears to create me a *new* den with only one (new) account. I was expecting it to import the 3 accounts I had in the other browser (just on another PC). 

What am I doing wrong? What is "restore from seed" supposed to do!?

**Comment by bwheeler96** [comment]
@daevski the seed word generates accounts in order, deterministically.

Click "new account" twice and you'll have your three accounts back.

**Comment by daevski** [comment]
@bwheeler96 First of all, that sounds like a horrible way to implement that, secondly, are you talking about this "Create Account" link? That doesn't help, it just creates empty accounts, and ones with different addresses from the ones I wanted to restore...

![image](https://user-images.githubusercontent.com/1388502/36336855-d4d01fda-1359-11e8-826e-a20ebbc4d906.png)

**Comment by bwheeler96** [comment]
@daevski this wasn't implemented by MetaMask, and it sure wasn't implemented by me (I don't work for MM). This was the design of the BIP 39 standard.

Were your other accounts created from that same seed phrase? If so, this would be how you get them. If not, you will have to import those private keys manually

Does the first account get imported correctly?

**Comment by daevski** [comment]
@bwheeler96  Okay, good questions - only the first account was part of that seed, the other 2 accounts were 'loose,' so with that in mind, I can see how they might not be generated with that same seed. I think I will need to import them again. I expected them to appear when using the same seed, but they were not generated with that seed originally. Thanks for the assistance.
