### ISSUE TITLE
Metamask with TypeScript

### ISSUE THREAD

**Issue by DexSwaper** [MetaMask/metamask-extension#22449]
### Describe the bug

Hi, I'm following the tutorial provided here:
https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/react/

using react+ts , but in browser console it says:

```
Invalid dappMetadata.url: URL must start with http:// or https://
(anonymous) @ @metamask_sdk-react.js?v=2244880d:42403
```

What should i do?

Thanks

### Steps to reproduce

1.in a new folder :
```
npm init vite@latest
```
and install react+TS

2. copy paste the codes provided here:
https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/react/

### Version

11.7.2

### Build type

None

### Browser

Chrome

### Operating system

Windows, Linux

**Comment by gauthierpetetin** [comment]
Hi @vandan @httpJunkie do you have the answer to the question raised in this issue?

**Comment by vandan** [comment]
This issue is most appropriate for the SDK team.

**Comment by gauthierpetetin** [comment]
cc @ezgi-cengiz for visibility

**Comment by christopherferreira9** [comment]
Hi @DexSwaper ! The URL in the dappMetadata object needs to have that specific format. Can you please try to change the dappMetada object to this one:
```
dappMetadata: {
    name: "Example React Dapp",
    url: window.location.href,
}
```
We are going to update the documentation in the coming days to reflect this change. We're sorry for the inconvenience.
