### ISSUE TITLE
MetaMask running slow

### ISSUE THREAD

**Issue by Vigme86** [MetaMask/metamask-extension#2244]
Hi guys,

since a couple of days Metamask is really slow, practically unusuable, 
but Chrome and my laptop are normal.
I have tried to google this problem but found nothing to solve it.
I have also tried to restart Chrome but with no success.
Hope you guys could help me.

**Comment by Zanibas** [comment]
Could you submit a ticket at https://support.metamask.io/home, tell them it was from Zanibas, and follow the instructions here? https://support.metamask.io/kb/article/15-copying-state-logs (except instead of pasting, give us the direct file as an attach).
