### ISSUE TITLE
[Bug]:LavaPack is not defined on Chrome Canary

### ISSUE THREAD

**Issue by Move4284** [MetaMask/metamask-extension#22440]
### Describe the bug

LavaPack is not defined on Chrome Canary

### Steps to reproduce

Download the latest chrome canary
Download metamask
Reproduction of the situation

### Version

11.7.3

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS

**Comment by NickStein85** [comment]
Same here
![image](https://github.com/MetaMask/metamask-extension/assets/59476615/9e8e92f9-4332-4714-ba58-9b1c9d3740bb)

**Comment by nostitos** [comment]
Same problem

**Comment by NickStein85** [comment]
Now it's not working with **Chrome Dev**

**Comment by Move4284** [comment]
> Now it's not working with **Chrome Dev**

same

**Comment by NickStein85** [comment]
Everything is working fine now on Canary and Chrome Dev. Please close the issue
