### ISSUE TITLE
Bug: we are currently passing more fields to blockaid report issue site in extension

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#22446]
Here we are passing all of fields in txParams to the website. That might include a lot of fields. We should include only the JSON RPC request that we send to PPOM for validation.

https://github.com/MetaMask/metamask-extension/blob/e76a99279de3be682d72ce1a5060014375f9f270/ui/components/app/security-provider-banner-alert/blockaid-banner-alert/blockaid-banner-alert.js#L93

**Acceptance criteria:**
* ensure that the FE form is properly populated
* ensure that the background request does not have more data than it should

**Comment by cryptotavares** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/22446?planning-poker) with Zenhub @jpuri @segun @blackdevelopa @seaona

**Comment by digiwand** [comment]
Based on my investigation, it seems we **don't** add additional props to txParams and we **do** add the `origin` and `version` props to msgParams. 

note: In one of our middlewares, we serialize some of the JsonRpcRequest params. existing param names seem to be preserved and some values may be altered through normalization. See: https://github.com/MetaMask/eth-json-rpc-middleware/blob/main/src/wallet.ts

**example txParams:**
<img width="650" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46d5f8808beb70a2dc477626bf97f682fd3a1dd5/Screenshot%202024-01-17%20at%209.42.36%E2%80%AFPM.png" alt="Screenshot 2024-01-17 at 9.42.36 PM.png" />

**example msgParams:**
<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTNYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--273e5587b06a90af9c27f8d22d111ce56267fdbd/Screenshot%202024-01-17%20at%209.45.06%E2%80%AFPM.png" alt="Screenshot 2024-01-17 at 9.45.06 PM.png" />

**example msgParams.data:**
```
"{"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Permit":[{"name":"owner","type":"address"},{"name":"spender","type":"address"},{"name":"value","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]},"primaryType":"Permit","domain":{"name":"USD Coin","verifyingContract":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","chainId":1,"version":"2"},"message":{"owner":"0xe56e7847fd3661a9b7c86aaf1daea08d9da5750e","spender":"0x1661F1B207629e4F385DA89cFF535C8E5Eb23Ee3","value":"1033366316628","nonce":1,"deadline":1678709555}}"
```

Based on these findings and only omitting params that PPOM does not use, I think we could omit the gas props from txParams and the version prop from msgParams. That said, as discussed in this [thread](https://consensys.slack.com/archives/C04C0F6SSJH/p1705507657063379?thread_ts=1705426837.504339&cid=C04C0F6SSJH), we'll be leaving the `jsonRpcParams` as is. It's better to keep complexity to a minimum here.
