### ISSUE TITLE
Request to Add Shackleford Token Data from CoinMarketCap API

### ISSUE THREAD

**Issue by illuminatedinformation** [MetaMask/metamask-extension#22459]
### What is this about?

Dear MetaMask Support Team,

I am writing to request the addition of Shackleford Token (SHACK) data from the CoinMarketCap API to MetaMask.

We have recently been listed on both CoinMarketCap and CoinGecko, and several of our users are experiencing difficulty viewing our information correctly on MetaMask . Our UCID is #28896, and you can find our CoinMarketCap listing here:

https://coinmarketcap.com/currencies/shackleford/
https://www.coingecko.com/en/coins/shackleford

We appreciate your prompt attention to this matter and look forward to providing a seamless experience for our users on MetaMask .

Thank you for your assistance.

Best regards,
Mr. Shackleford
CEO and Founder

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by anaamolnar** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/22429
