### ISSUE TITLE
Connect Wallet issue on own extension

### ISSUE THREAD

**Issue by blockchain-app12** [MetaMask/metamask-extension#22468]
### What is this about?

We are developing a new extension for our own use cases. We have completed the separate wallet functionalities similar to MetaMask and developed our own DApp application. However, we are encountering issues while trying to connect the wallet with the DApp, akin to the functionality provided by the `ethereum.enable()` function in the MetaMask extension. We are facing challenges in establishing a connection between the extension and the DApp. Although we have successfully connected the extension for balance display using a popup, not all functionalities are working seamlessly, mirroring the workflow of the extension like Metamask.

### Technical Details

 We are facing challenges in establishing a connection between the extension and the DApp. Although we have successfully connected the extension for balance display using a popup, not all functionalities are working seamlessly, mirroring the workflow of the extension like Metamask.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [X] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [X] Other (please specify)

**Comment by blockchain-app12** [comment]
Hi @anaamolnar,

I referred to the links you provided, but we need the exact functions or procedures required for custom wallet connection with the Dapp. We have a separate custom RPC based on the besu network that's get imported in the wallet. By using that wallet, connect with the Dapp to execute the transactions. we stuck at this process.if you have suggestions, please let me know to complete it.

**Comment by anaamolnar** [comment]
Hello, @blockchain-app12. Thanks for the details. I recommend you review the topics posted here https://community.metamask.io/c/developer-discussion/extension/48 and also refer to a developer forum such as Ethereum Stack Exchange or Stackoverflow. Thank you!
