### ISSUE TITLE
[Bug]: Swap Timeout Issue

### ISSUE THREAD

**Issue by austinmarkus** [MetaMask/metamask-extension#22496]
### Describe the bug

I press the swap button and attempt to swap a small amount from VCNT to Matic. It attempts to get quotes but returns the error "No quotes available. Reduce the size of your trade or use a different token." Looking under the hood MetaMask is making a request to swap.metaswap.codefi.network/networks/137/trades. The underlying API call is reaching out to the various DEXs but all of those calls are timing out.

### Expected behavior

I expected quotes for the swap.

### Steps to reproduce

1. Press the "Swap" button
2. Select VCNT as the "from" coin
3. Select MATIC as the "to" coin
4. Enter 0.5 as the amount
5. Wait as it fetches quotes

### Error messages or log output

```shell
No quotes available. Reduce the size of your trade or use a different token.

https://swap.metaswap.codefi.network/networks/137/trades?destinationToken=0x0000000000000000000000000000000000000000&sourceToken=0x8a16d4bf8a0a716017e8d2262c4ac32927797a2f&sourceAmount=500000000000000000&slippage=2&timeout=10000&walletAddress=**Redacted**

Has "Timeout" listed as an error for each of the DEXs
```

### Version

11.7.2

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Additional context

This has been happening across multiple devices on multiple OSs for the past 4 days or so.

**Comment by gauthierpetetin** [comment]
Downgrading severity to `sev2`, as per recommendation from @forest-diggs-consensys , since the issue seems to be occurring for a single random token. Additionally, it's still possible to get quotes by setting a higher slippage limit (tested with 10%).
It could be helpful to update the error message, by prompting the user to adjust slippage.

**Comment by austinmarkus** [comment]
The issue is not confined to VCNT. I get the same timeout when attempting to swap from USDC to DAI, DAI to MATIC, and USDC to MATIC (all that I have tried). That said, my guess is that is it specific to the Polygon chain as I can't reproduce on Ethereum. I also think that the slippage change is a red herring, I was just timed out on a quote twice for a USDC to MATIC with 10% slippage. As it is an intermittent bug quotes do sometimes work, but the cause of success is not determined by the coins or the slippage as far as I can tell.
