### ISSUE TITLE
[Bug]: Auto token detection list collision with other networks

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#22512]
### Describe the bug

When having auto detection setting turned on, multiple networks, and multiple tokens associated with an account I find that the list for "found tokens to add" has other from another network on the list to add.

### Expected behavior

Should only detect tokens based on network to curate the "found tokens to add" list.

### Screenshots/Recordings

![Screenshot 2024-01-12 at 7 59 13 PM](https://github.com/MetaMask/metamask-extension/assets/13376180/ca84c32c-1e39-4f79-a019-21124be76e51)
![Screenshot 2024-01-12 at 7 55 34 PM](https://github.com/MetaMask/metamask-extension/assets/13376180/6016576d-3036-4230-9c65-4b7ec811528b)

### Steps to reproduce

Turn on Auto Detection of tokens list. 
Add networks where the account has tokens. (I used Linea and Matic)
Wait for token detection list notification to add found tokens.
Lists should have extra tokens from Mainnet.

### Version

11.8.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

**Comment by adonesky1** [comment]
@tmashuang, neither @jiexi or I have have been able to reproduce this issue.

**Comment by gauthierpetetin** [comment]
Similar issue was raised here: https://github.com/MetaMask/metamask-mobile/issues/7587

**Comment by bergeron** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/22814
