### ISSUE TITLE
switching from localhost to rinkeby doesn't reload page

### ISSUE THREAD

**Issue by szerintedmi** [MetaMask/metamask-extension#2253]
MacOs Sierra 10.12.6
Chrome 61.0.3163.100 (Official Build) (64-bit)
Metamask 3.10.8

When switching from Rinkeby/Ropsten to Localhost the page reloads.
When switching from localhost to Rinkeby/Ropsten or between non local networks then there is no page reload anymore.

It used always reload the page when I switched network.

**Comment by szerintedmi** [comment]
behaviour changed in latest version (Metamask 3.11.0). Now it never refreshes the page when I change the network. I'm fine with this way too - I can just poll network id and handle change manually. 
Is this the behaviour you want to keep?
 @Zanibas you marked this issue as duplicate. Would you please link the other issue so I can follow that too?

**Comment by szerintedmi** [comment]
Ok, I found the other issue: #2300

**Comment by tmashuang** [comment]
Closing, should have been fixed in master. Will reopen if the issue persists.
