### ISSUE TITLE
[Bug]: PPOM - Report false positives always sets `Result Type` as bening

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22536]
### Describe the bug

**Problem:** within the Blockaid feature, whenever you click on reporting a false positive, if you unfold the `Details` section, you see the `Result Type` is always set to `bening`, no matter if the transaction was flagged as `malicious` or `failed to verify`

### Expected behavior

`Result type` value from the Report false positive portal should have the value from the transaction, and not default to bening

### Screenshots/Recordings

Malicious Tx - set as bening in Result Type

https://github.com/MetaMask/metamask-extension/assets/54408225/c1e9f083-b566-4a9c-8d1f-cb3a128baad7

Failed to verify Tx - set as bening in Result Type

https://github.com/MetaMask/metamask-extension/assets/54408225/e4187150-f991-44a7-9660-8e00eb71ba7b

### Steps to reproduce

1. Go to the test dapp
2. Trigger a malicious tx
3. Click Report false positives
4. Proceed
5. Check details
6. See `Result Type` is set to `bening`

### Version

11.9.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/22536?planning-poker) with Zenhub @blackdevelopa @digiwand @seaona @segun

**Comment by seaona** [comment]
From Blockaid:

> Looks like a bug on our side (False positive portal parsing) :slightly_smiling_face:
> Investigating.. will update when I have findings

**Comment by digiwand** [comment]
thanks @seaona! I suppose we can leave this in progress since Blockaid is working on it. I will unassign myself until further action is needed

**Comment by bschorchit** [comment]
I believe this has been fixed now and can be closed as per this [slack comment](https://consensys.slack.com/archives/C05HZHDS89Z/p1705590835116759?thread_ts=1705393852.556679&cid=C05HZHDS89Z)

**Comment by seaona** [comment]
I confirm I see this fixed by Blockaid. We can close the issue

![Screenshot from 2024-01-26 15-57-46](https://github.com/MetaMask/metamask-extension/assets/54408225/427df69d-a25e-4af4-8500-6b00792d8c9a)
