### ISSUE TITLE
[Bug]: PPOM - Blockaid `What's new` shows small UI differences compared to Figma designs

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22535]
### Describe the bug

**Problem:** on the update of What's New for Blockaid I see some small differences from the Figma designs:
- the first sentence `Stay safe from scams` is not bold compared to Figma
- the picture has a grey background
- the button takes the full width - this affects all the What's new items so I don't think it's an issue, just mentioning because it's different from Figma, but I don't think this one needs to be addressed

### Expected behavior

- To discuss with @SayaGT

### Screenshots/Recordings
Left: Extension version         ||                                        Right: Figma version

![Screenshot from 2024-01-15 12-03-13](https://github.com/MetaMask/metamask-extension/assets/54408225/56de2773-83b6-49b0-b55e-fed5a507ee78)

### Steps to reproduce

1. Update Extension to `develop` branch

### Version

11.9.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/22535?planning-poker) with Zenhub @blackdevelopa @digiwand @seaona @segun

**Comment by digiwand** [comment]
PNG found here
https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?type=design&node-id=6657-17712&mode=design&t=GjKUqMcigcHGMZCJ-0

I concur with @jpuri earlier that the bold "Stay safe from scams" is not supported with our current notification/announcements/what's new system. I believe it would require changes in our core AnnouncementsController. Although this text is typically created by us, we would still want to ensure no future implementation may introduce dynamic input with XSS. If we want to support this, we should create a new ticket for this as a feature cc: @SayaGT @seaona

I concur with @jpuri and @seaona the button doesn't need to be fixed. Not sure where the second image in the description came from, but the one in this [Figma](https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?type=design&node-id=6657-17712&mode=design&t=GjKUqMcigcHGMZCJ-0) has the full width button as expected
