### ISSUE TITLE
NFT Image not loading

### ISSUE THREAD

**Issue by allwin199** [MetaMask/metamask-extension#22545]
### Describe the bug

After adding NFT to the metamask only placeholder is displayed.

### Expected behavior

Original NFT Image

### Screenshots/Recordings

![Screenshot 2024-01-16 at 4 29 47 PM](https://github.com/MetaMask/metamask-extension/assets/127643894/ff810f4f-3d40-4cc5-9223-58a425e4ffd4)

### Steps to reproduce

Importing NFT

### Version

11.7.3

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Hi @kevinghim @danjm , this issue looks similar to this one: https://github.com/MetaMask/MetaMask-planning/issues/1727
We might want to prioritise it soon, any idea who'd be most appropriate to work on it?
