### ISSUE TITLE
[Bug]: Custom network not displayed or selectable in network selection

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#22559]
### Describe the bug

Was testing with develop and noticed in commit 1e5e386b3ee6195a2e21e9842d493e7aea4efb9c that after I added a custom network that it was not displayed in the network selection drop down.  This is not the case in production with 11.7.3.

### Expected behavior

Once a custom network is added, it is presented and can be selected from the drop down.

### Screenshots/Recordings

11.7.3 production stable recording: https://recordit.co/tjxEqyZsuj
Commit 1e5e386b3ee6195a2e21e9842d493e7aea4efb9c in a flask build: https://recordit.co/6ASR0uVsPz

### Steps to reproduce

1. Have ganache running locally with `npx ganache-cli --fork https://mainnet.infura.io/v3/[YOUROWNINFURAID] --chainId 1`
2. Add it as a custom network with chainId=1
3. Select the newly added network
4. Change to another network
5. Note that you are no longer able to change back to custom network even though it remains present

### Version
Observed initially while testing against develop commit:
1e5e386b3ee6195a2e21e9842d493e7aea4efb9c

Can now confirm that 2f0f141b6e52061d6acd097f600f81bde9bb26a1 appears to be where this was introduced.

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

### Additional context

Mac sonoma 14.2.1 with Chrome 117.0.5938.92

**Comment by NidhiKJha** [comment]
@plasmacorral unfortunately, I am not able to replicate this issue. When I try to add a network, It's added in the list. 
https://github.com/MetaMask/metamask-extension/assets/39872794/3f47ab30-4805-41ac-b334-4ec7b62e8eab

**Comment by chloeYue** [comment]
Hello @NidhiKJha , could you please try to reproduce this bug with a testnet who has chainID=1 ? I tested with a mainnet fork on tenderly and i reproduced it:

https://github.com/MetaMask/metamask-extension/assets/105063779/64bece55-05c1-47a9-8013-1a4e36b6eebd

**Comment by chloeYue** [comment]
Hi @NidhiKJha , do we have any update for this ticket?
