### ISSUE TITLE
Fix "Show account details should..." flaky tests

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#22565]
Flaky tests include:

- Show account details should show the QR code for the account
- Show account details should show the correct private key from account menu
- Show account details should show the correct private key for an unselected account from account menu
- Show account details should show the correct private key from global menu
- Show account details should not reveal private key when password is incorrect
- Show account details should unpin the account when unpin is clicked

**Comment by HowardBraham** [comment]
When you do this, may I suggest that you split these tests into multiple spec files?  The reason has to do with parallel runs and retries.  There are currently 11 tests in one file, and that tends to lengthen overall execution time.

**Comment by hjetpoluru** [comment]
Test scenario 'should unpin the account when unpin is clicked' in the account-details.spec.js, the scenario focuses on unpinning the account and verifying that the 'unpin' action does not result in the 'pinnedIcon' element appearing. I noticed that we are currently checking for the presence of the 'pinnedIcon' element both before and after the unpin action. To improve the test, could @NidhiKJha please add an assertion to ensure that the 'unpin' element does not appear after the unpinning action?

**Comment by chloeYue** [comment]
> When you do this, may I suggest that you split these tests into multiple spec files? The reason has to do with parallel runs and retries. There are currently 11 tests in one file, and that tends to lengthen overall execution time.

resolved here: https://github.com/MetaMask/metamask-extension/pull/22635

**Comment by chloeYue** [comment]
> Test scenario 'should unpin the account when unpin is clicked' in the account-details.spec.js, the scenario focuses on unpinning the account and verifying that the 'unpin' action does not result in the 'pinnedIcon' element appearing. I noticed that we are currently checking for the presence of the 'pinnedIcon' element both before and after the unpin action. To improve the test, could @NidhiKJha please add an assertion to ensure that the 'unpin' element does not appear after the unpinning action?

resolved here: https://github.com/MetaMask/metamask-extension/pull/22635

**Comment by chloeYue** [comment]
`Show account details should unpin the account when unpin is clicked` has been fixed, and i don't see failures for other tests anymore. Last time they failed with error message "address already in use 127.0.0.1:8545.", seems it was not because tests themselves. So i close this issue now.
