### ISSUE TITLE
[Bug]: CircleCI E2E test workflows intermittently get stuck in Fontconfig error loop

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#22564]
### Describe the bug

For the past month or so, we've been seeing that CircleCI E2E test jobs will occasionally get stuck and stay running indefinitely without ever passing. The logs form the job show the error message:

```
Fontconfig error: Cannot load default config file: No such file: (null)
```

### Expected behavior

Jobs should timeout after a reasonable timeframe if they get stuck, and this specific error should not be occurring.

### Steps to reproduce

This happens occasionally on E2E test jobs, we don't know of a way to reliably reproduce it.

### Version

N/A

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by desi** [comment]
Potential next steps: @Gudahtt will share link on chromium. Update chromium as a first try of a fix. Verify if the "no sandbox" flag is used with Chromium (as this could be related). This might lead to investigating the image more. We will timebox investigation.

**Comment by Gudahtt** [comment]
Here is an old Chromium bug that seemed similar: https://bugs.chromium.org/p/chromium/issues/detail?id=1010388

**Comment by desi** [comment]
The other thing @Gudahtt said he was going to try is to update Chrome.

**Comment by Gudahtt** [comment]
Reopening because Chrome hasn't been updated yet, and because we've found that the FONTCONFIG_PATH solution did not work

**Comment by HowardBraham** [comment]
@Gudahtt Chrome and Chromedriver automatically get updated to the latest stable version because of #21481
