### ISSUE TITLE
Fix "approve token" flaky test

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#22572]
![Screenshot from 2024-01-17 16-28-59](https://github.com/MetaMask/metamask-extension/assets/7499938/a222168c-68c7-4a21-8e03-dab2a249627f)

**Comment by digiwand** [comment]
Related thread: [link](https://consensys.slack.com/archives/GTQAGKY5V/p1705521390579229?thread_ts=1705519555.188529&cid=GTQAGKY5V)
Circle CI (may need to search pages): https://app.circleci.com/insights/github/MetaMask/metamask-extension/workflows/test_and_release/tests?branch=develop

dev notes: 
- related test phrase is the value of the classname above 
"set custom spending cap, customizes gas, edit spending cap and checks transaction in transaction list @no-mmi"
- file: test/e2e/tests/custom-token-add-approve.spec.js
