### ISSUE TITLE
Fix "Import flow" flaky test

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#22571]
![Screenshot from 2024-01-17 16-27-33](https://github.com/MetaMask/metamask-extension/assets/7499938/43b8ad4e-de48-47e6-b7ba-dc8b935ac714)

**Comment by Gudahtt** [comment]
Here is an example failure: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/67420/workflows/91d58c04-ba08-4a39-ab0b-7a685768dda2/jobs/2215948/tests
