### ISSUE TITLE
Fix "Snap Account Transfers" flaky test

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#22576]
![Screenshot from 2024-01-17 16-56-59](https://github.com/MetaMask/metamask-extension/assets/7499938/c618a003-f55f-4aff-9d80-0bac82a4cfd0)

**Comment by HowardBraham** [comment]
@danjm I think I fixed this with #22497

I see that it failed recently, but not on `develop`, and I'm not sure if those branches were up to date.  I'll continue to monitor.
