### ISSUE TITLE
Fix  "PPOM Blockaid Alert - Malicious ERC20 Approval @no-mmi should show banner alert" flaky test

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#22577]

**Comment by digiwand** [comment]
mentioned in the [thread](https://consensys.slack.com/archives/GTQAGKY5V/p1705521390579229?thread_ts=1705519555.188529&cid=GTQAGKY5V) 2023.01.17:
> The "PPOM Blockaid Alert - Malicious ERC20 Approval @no-mmi should show banner alert" test is now flaking a lot. Seems to be a new issue today
![Screenshot 2024-01-17 at 5 47 20 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/2d0a20fd-ec04-486e-a8c9-a080d3872c5d)

Circle CI (may need to search pages): https://app.circleci.com/insights/github/MetaMask/metamask-extension/workflows/test_and_release/tests?branch=develop

other Blockaid flaky tests found:
![Screenshot 2024-01-17 at 5 45 35 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/bc48e6ee-5589-4b93-a1a9-de3790f2bb44)
![Screenshot 2024-01-17 at 5 45 42 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/91f9ee63-db65-451f-8dc9-a83b42016e0a)
![Screenshot 2024-01-17 at 5 46 44 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/fb61ed3e-d0b1-4828-a00b-d109ca29149d)
![Screenshot 2024-01-17 at 5 46 59 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/012f1b98-e5d5-4fbf-801d-5dbc795327b6)
![Screenshot 2024-01-17 at 5 47 06 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/c5647d9f-dd61-44e9-ab53-c373e8f06f48)
![Screenshot 2024-01-17 at 5 49 42 PM](https://github.com/MetaMask/metamask-extension/assets/20778143/da5cd321-b78e-4885-87e9-77b6e1463dfa)

**Comment by seaona** [comment]
I'm looking for an instance of this test failing on ci - haven't found any so far.
I need it for debugging, since the test seems to run fine locally.
@digiwand do you happen to have a link for one of the failing jobs for this test?

**Comment by Gudahtt** [comment]
Here is an example failure: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/67324/workflows/8f380ed1-9c1e-49a0-8f3e-6f760ba98fab/jobs/2211382/tests
