### ISSUE TITLE
New Warning for High Gas Prices

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#2258]

**Comment by WestonReed** [comment]
What should the threshold be for high gas prices? Should it include some note that says whether or not the network is under heavy load (last n blocks are >95% gas limit), so gas prices may need to be higher? https://ethgasstation.info/ has some good info on gas prices, so maybe we could define a "high" gas price as some multiple of the "Fast" gas price.

**Comment by jennypollack** [comment]
I think this is covered by our slow, average, fast transaction fee components
