### ISSUE TITLE
[preferences-controller] Remove unused PreferencesController methods

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#22596]
### What is this about?

After completing #22594 and https://github.com/MetaMask/core/issues/3699 (and releasing and updating the `KeyringController` here), I expect the methods `syncIdentities` and `updateIdentities` to no longer be used. These unused methods should be removed.

### Technical Details

Remove the methods `syncIdentities` and `updateIdentities`

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by desi** [comment]
This ticket has a blocking ticket but can be worked on. Just don't merge until "React to keyring state changes" has merged.

**Comment by cryptodev-2s** [comment]
waiting for @metamask/keyring-controller@13.0.0 release

**Comment by desi** [comment]
@cryptodev-2s is this still blocked or is it able to be picked up now?

**Comment by cryptodev-2s** [comment]
@desi yes it's still blocked I just updated the current blocking ticket

**Comment by mikesposito** [comment]
This is being taken care of with https://github.com/MetaMask/metamask-extension/pull/23620
