### ISSUE TITLE
Indicate transaction errors in tx history

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#226]
This issue is now open to add an indication to the transaction history of when a transaction ran out of gas.

This may require also logging when a transaction ran out of gas.

The original issue text follows.

---

Just verifying this is correct behavior.

If a user submits a tx, and they run out of gas, that's a "successful" transaction? It feels like it deserves its own icon in our transaction list:

<img width="622" alt="screen shot 2016-05-26 at 2 44 43 pm" src="https://cloud.githubusercontent.com/assets/542863/15591246/af5239c8-2350-11e6-894c-54526408caf8.png">

**Comment by Zanibas** [comment]
Closing this as more specific issues can be opened
