### ISSUE TITLE
[Feat]: Update Blockaid MetaMetrics based on "External Link Click" schema

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#22604]
### Describe the bug

This PR proposes updates to the "External Link Click" event we fire when the user clicks "Report an Issue" on the BlockaidBannerAlert which is used to report false positives. 

----
The following proposal is taken verbatim from an investigation of another issue. 
ref: https://github.com/MetaMask/MetaMask-planning/issues/1756#issuecomment-1894471209
 
 [...] we are using the property name external_link_clicked which isn't used by any other events. The other 'External Link Clicked' events are using the property `link_type`. The metametric schema for 'External Link Clicked' can be found here: [internal link](https://www.notion.so/Working-with-Event-Metrics-eec3d8da9b0f45429c912278959cd742?p=057a1373af0e4c8c8451c3b6b11b3c3c&pm=s). Should we update this property name and value to be consistent with the other ones?

existing `link_type` values:
- 'Account Tracker'
- 'Block Explorer'
- 'Token Tracker'
- 'Transaction Block Explorer'

#### proposed updated "External Link Clicked" prop # 1
key: external_link_clicked → link_type
value: security_alert_support_link → Blockaid Report Issue

#### proposed updated "External Link Clicked" prop # 2
key: action → location
value 1: Confirm Screen → Confirm or Confirm
value 2: Sign Request → Confirm Sign
others to be added along with this fix: Confirm Sign SIWE, Confirm Approve, Confirm Allowance

---

### Steps to reproduce

1. For our local environment, you may need to setup appropriate blockaid and Segment ENV variables
2. Turn on Blockaid from Experimental Settings
3. Turn on MetaMetrics in settings
4. Open test dapp
5. Start PPOM malicious transaction
6. Observe BlockaidBannerAlert
7. Click "See Details"
8. Click "Report an Issue"
9. Observe metametric event

### Version

11.7.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Closing as this is no longer an issue :)
