### ISSUE TITLE
[Bug]: VM410:1 MetaMask - RPC Error: while converting number to string, invalid number value '1e-10', should be a number matching (^-?[0-9.]+). 

### ISSUE THREAD

**Issue by kabaluyot** [MetaMask/metamask-extension#22605]
### Describe the bug

I was saving default values to Advance Settings gas ettings for my Besu-based private network with zero gas fee.

The fees was set to 0.0000000001 and "saved to remember"

The next transactions then are failing for that network.

### Expected behavior

Should work as usual

### Steps to reproduce

I was saving default values to Advance Settings gas ettings for my Besu-based private network with zero gas fee.

The fees was set to 0.0000000001 and "saved to remember"

The next transactions then are failing for that network.

### Error messages or log output

```shell
main.06f2c52bf3ee3881.js:1 ERROR Error: Uncaught (in promise): Error: while converting number to string, invalid number value '1e-10', should be a number matching (^-?[0-9.]+).
{
  "originalError": {}
}
Error: while converting number to string, invalid number value '1e-10', should be a number matching (^-?[0-9.]+).
{
  "originalError": {}
}

---

code
: 
-32603
data
: 
"{\n  \"originalError\": {}\n}"
message
: 
"while converting number to string, invalid number value '1e-10', should be a number matching (^-?[0-9.]+)."
```

### Version

11.7.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

Very needed for testing out free gas network (besu) interaction with metamask

**Comment by kabaluyot** [comment]
@gauthierpetetin I think this shouldn't have low severity. Atm metamask is not usable at all for affected networks

**Comment by gauthierpetetin** [comment]
Hi @bschorchit , bringing this bug to your attention as it seems to prevent using MM on several networks. Feel free to re-evaluate severity if inaccurate.

**Comment by kamikazechaser** [comment]
Similar issue on Celo Mainnet.

**Comment by kamikazechaser** [comment]
Downgrading resolves the issue. Can confirm that it affects all browsers when attempting to sign on Celo.
