### ISSUE TITLE
Metamask 

### ISSUE THREAD

**Issue by GiiMar** [MetaMask/metamask-extension#22620]
### What is this about?

Usar extensión 

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by plasmacorral** [comment]
Closing this issue for lack of information, please feel free to open a fresh issue if you have something to actually report.
