### ISSUE TITLE
Investigate Blockaid gzip compression logic

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#22626]
### Describe the bug

Investigate the following inquiry by @legobeat: 

https://github.com/MetaMask/metamask-extension/pull/22274/files:
> Have tests confirmed that applying gzip before base64-encoding actually brings any benefits here?
> 
> Depending on the shape of the data, redundant compression does not necessarily help.
> 
> Even the fallback should already be at least base64 -> gzip or base64 -> brotli, with the happy path doing gzip -> base64 -> gzip/brotli
> 
> Before applying manual compression here, it'd be good to
> verify that compression is properly applied to the underlying transport when sending. And if it indeed already is, that the dual-compression is actually beneficial enough to be worth it.
> 
> https://blog.cloudflare.com/this-is-brotli-from-origin/
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding
> 
> Or if not, maybe can just drop the gzip step alltogether to simplify the logic?
> 
> (Can disregard this comment if this has already been concluded, just want to make sure it's not an oversight)

Answering the above question may affect our mobile implementation as well. We may be able to remove the following package
https://github.com/MetaMask/metamask-mobile/pull/8216#discussion_r1452977532

### Steps to reproduce

-

### Version

11.7.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by digiwand** [comment]
cc: @segun @jpuri

**Comment by jpuri** [comment]
We are using gzip for compressing the data we are sending to false positive site. This is a requirement from blockaid team, they use this compressing format.
