### ISSUE TITLE
Metamask sometimes shows negative balance

### ISSUE THREAD

**Issue by morelazers** [MetaMask/metamask-extension#2263]
I was making trades on Etherdelta, and one got stuck because of the low default gas price (4Gwei), so I imported my seed into Parity and cancelled the tx.

Metamask now thinks I have -10 Ether.
![image](https://user-images.githubusercontent.com/2966123/31105666-9d17b83e-a831-11e7-9eed-e8a1decd7ce5.png)

What's the easiest way to reset the state of the plugin.

Cheers

**Comment by morelazers** [comment]
Reinstalled the plugin and restored the account - all working again.

**Comment by kumavis** [comment]
Thanks for the report - this shouldn't require a restart to fix 😉

**Comment by Zanibas** [comment]
This should be fixed in master as we reverted to our old calculation of balances (straight from the block).
