### ISSUE TITLE
"Dangerously high gas limit" warning gets concatenated with "Insufficient funds" warning

### ISSUE THREAD

**Issue by macbem** [MetaMask/metamask-extension#2265]
If you input an amount of gas that is:
- "dangerously high", according to MetaMask
- exceeding your ETH balance

The warning messages are displayed at the same time which doesn't look good.
<img width="372" alt="screen shot 2017-10-03 at 12 55 56" src="https://user-images.githubusercontent.com/12464061/31121998-9174c536-a83a-11e7-800c-ddc560daed2f.png">

**Comment by Zanibas** [comment]
Will fix in the new UI deployment
