### ISSUE TITLE
[Bug]: Cancelling Swap transaction on Arbitrum, Optimism and Avalanche network doesn't succeed

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#22663]
### Describe the bug

When Swapping a token on Arbitrum, Optimism and Avalanche network, if the user attemps cancel the transaction it nevers succeeds and console showing errors (see screenshots)

### Expected behavior

I am able to cancel the swap transaction

### Screenshots/Recordings

<img width="1246" alt="Screenshot 2024-01-24 at 10 32 10 PM" src="https://github.com/MetaMask/metamask-extension/assets/6082863/c4b27f75-92bb-4641-9af0-669be0453fe1">
<img width="1261" alt="Screenshot 2024-01-24 at 10 33 19 PM" src="https://github.com/MetaMask/metamask-extension/assets/6082863/04bca885-1ebb-4634-815d-0cddca914ef8">
<img width="1274" alt="Screenshot 2024-01-24 at 10 35 29 PM" src="https://github.com/MetaMask/metamask-extension/assets/6082863/c04ce2b2-2d63-4e7d-a2b7-e927ccc151b9">

### Steps to reproduce

1. Change the Network to Arbitrum, Optimism or Avalanche
2. Go to Swap and open the console
3. Trade any tokens
4. As soon as swap starts go back to the activity
5. Cancel the transaction
6. Notice the error in the console and that the swap transaction fails to cancel 

### Version

11.7.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by dan437** [comment]
This is not a swaps-specific issue, I can see it also happens in the Send flow and very likely other non-swap flows as well.

**Comment by OGPoyraz** [comment]
We think that transactions are happening too fast in the mentioned networks. However if user cancelling a transaction, and if it's already confirmed, needs a feedback in the UI that the transaction already confirmed. 

This is a known issue where we are actively working on it with https://github.com/MetaMask/metamask-extension/issues/22314 

We will test this and close this issue once other PR is ready.

**Comment by OGPoyraz** [comment]
@sleepytanya since these layer 2 solutions are really fast, it would be hard to reproduce this. But I think we could at least test this out after new developments around new "confirmation already approved" modal because the bug case perfectly fits there.

**Comment by sleepytanya** [comment]
@OGPoyraz Looks like it's the case - the transaction is already confirmed and 'Activity' list is updated several seconds after.
dev build from `develop`, Chrome:

Arbitrum

https://github.com/MetaMask/metamask-extension/assets/104780023/2a283cce-9dd8-4512-93ef-c5fad8a42ba9

Avalanche


https://github.com/MetaMask/metamask-extension/assets/104780023/a9c79a63-33e1-4cd9-ab63-9c0df8fada47

Optimism

https://github.com/MetaMask/metamask-extension/assets/104780023/46b535f9-dc53-4ed5-ad0b-f2ae8bcab038
