### ISSUE TITLE
[Bug]: Canceling Swap transaction with Smart Swap ON fails with error 500

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#22662]
### Describe the bug

Attempting to cancel a swap transaction with Smart Swap ON fails. In the background.html I see that API calls to `https://transaction.metaswap.codefi.network/networks/1/cancel` fails with error 500 Internal Server Error. On the extension console I also see an error `Unexpected end of JSON input` see screenshots below

### Expected behavior

The transaction is cancelled succesfully

### Screenshots/Recordings

<img width="559" alt="Screenshot 2024-01-24 at 9 53 30 PM" src="https://github.com/MetaMask/metamask-extension/assets/6082863/262222b7-1f7e-448e-b0af-cac3f2febc4b">

### Steps to reproduce

1. Go to Swap
2. Make sure Smart Swap is on
3. Swap ETH->WETH
4. Attempt to cancel the transaction with the console opened
5. Notice the error in the console `Unexpected end of JSON input` 
6. Go to the background.html and notice that the call to `https://transaction.metaswap.codefi.network/networks/1/cancel` failed with error 500

### Version

11.7.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by antonydenyer** [comment]
We're making a bunch of major changes around smart transactions at the moment. The immediate error has been fixed, and the user will be presented with a notification about attempting to cancel the transaction.

There is a lot to be improved here around finality - it's a work in progress and will be improved over the coming months.

**Comment by vpintorico** [comment]
Hi team, any update on this one? Can be close as non fixed?

**Comment by klejeune** [comment]
@vpintorico can we tag this as `team-transactions` instead of "team-swaps"?
Smart swaps cancellation is currently being improved. @antonydenyer @forest-diggs-consensys

**Comment by antonydenyer** [comment]
This should be fixed now.
