### ISSUE TITLE
[Bug]: NFT not displaying the image in metamask

### ISSUE THREAD

**Issue by ncrimi** [MetaMask/metamask-extension#22671]
### Describe the bug

When I buy an ERC721 token which is minted according to OpenSea/OpenZeppelin Standard with "name", "description", "image" and buy/transfer it into my Metamask on Localhost/Sepolia the NFT is not displayed correctly (white square).
the "image" has an ipfs link as value (e.g. "image": "ipfs://QmSbh33SzqBotFQmundnqDJEVBvpLLSXFCTdZ8pwHqAmjt").
The link points to an animated webp which was pinned via pinata.

### Expected behavior

To show the media which is behind the "image" link instead of just a white empty square.

### Screenshots/Recordings

![Screenshot 2024-01-25 at 15 31 40](https://github.com/MetaMask/metamask-extension/assets/37104494/3595a9b8-2391-4723-a943-dc95d9885266)

### Steps to reproduce

For example: buy NFT on Sepolia Testnet here
https://cm-dg-git-main-casella-meyer.vercel.app/casella-meyer/visions/silk-cargo-pants-allover-spirits

### Version

11.7.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

During my testing period it worked once as expected. The screenshot shows an animated webp which was displayed as it should. I used the NFTstorage pinning service for this file. However, I tested it with many other ERC721 tokens which were also pinned with this service and they were not displayed correctly.

<img width="355" alt="Screenshot 2024-01-26 at 09 40 15" src="https://github.com/MetaMask/metamask-extension/assets/37104494/598bbb1f-9cf3-49f4-a781-e1c3a11e8fb5">

### Severity

Visible to all users.

**Comment by ncrimi** [comment]
Btw I ensured that in Settings > Security & Privacy > Display NFT media is ON. 
My IPFS gateway is ipfs.io

**Comment by gauthierpetetin** [comment]
Will probably be closed once fix for this issue is released by Assets team (cc @alfeng6 @bergeron for visibility):
https://github.com/MetaMask/MetaMask-planning/issues/1727

**Comment by ncrimi** [comment]
Thank you @gauthierpetetin  for your feedback. 
I assume the repository is private as I receive a 404 when clicking on it. 
Therefore my question; when will this fix be released?
Thank you and best,
Nicola

**Comment by gauthierpetetin** [comment]
Hi @ncrimi , I'll leave it up to @alfeng6 and @bergeron to confirm this to you.

**Comment by ncrimi** [comment]
Hi @alfeng6 and @bergeron do you have a specific date for the release?
Thanks for the feedback and best!

**Comment by bergeron** [comment]
Hi @ncrimi , we think the IPFS nft issues should be fixed  by https://github.com/MetaMask/metamask-extension/pull/22627 once it releases.  Don't have a specific date, may take a couple weeks
