### ISSUE TITLE
[Bug]: Same Petname can be assigned for different accounts.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#22677]
### Describe the bug

Now we allow to assign one `Petname` for different accounts and it doesn't look safe and reliable from the user's perspective. 

### Expected behavior

Only unique `Petnames` should be allowed.

### Screenshots/Recordings

<img width="251" alt="Screenshot 2024-01-26 at 4 25 28 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/586d6519-e9b3-458e-aafd-3a852cf68d32">

### Steps to reproduce

1. Use build from `develop` branch
2. Connect to [test-dapp](https://metamask.github.io/test-dapp/)
3. Sign with `typed data V3` or `typed data V4`
4. On the confirmation screen assign same `petnames` for different account
5. See different accounts with the same `petname` saved in `Settings - >Contacts`.

### Version

11.7.3

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by matthewwalsh0** [comment]
Confirmed this is aligned with existing address book functionality. Not currently a bug.
