### ISSUE TITLE
[Bug]: Wallet cannot be opened

### ISSUE THREAD

**Issue by jgvnn** [MetaMask/metamask-extension#22681]
### Describe the bug

I am using Google Chrome, and the plug-in cannot be opened. Clicking it keeps spinning, and I cannot enter the password input interface.

### Screenshots/Recordings

![1706338585769](https://github.com/MetaMask/metamask-extension/assets/134611736/e765f42a-612b-44ea-a013-5b3039b952a2)

### Steps to reproduce

Unable to enter by clicking on the plug-in

### Version

11.7.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Severity

Many wallets cannot be opened, and the private keys and mnemonic phrases of some wallets have not yet been saved. Now the wallet cannot be opened and the assets inside cannot be obtained.

**Comment by louischanz** [comment]
I have the same problem as him, the following is the error message：
![iShot_2024-01-28_04 00 34](https://github.com/MetaMask/metamask-extension/assets/75527558/bc293711-35e7-4c46-adb7-a1783319075e)

**Comment by danjm** [comment]
@jgvnn @louischanz This is due to an incompatibility between MetaMask and chrome v122+. This is fixed in v11.7.5, which should be released within a day or two, but in the meantime if you switch to chrome v121, you can avoid this error

**Comment by ZbrancaI** [comment]
Hey @jgvnn @louischanz! I'm going to close this, as the issue should be fixed in the 11.7.5 update! In case the issue persists after the update, please feel free to reopen it!
