### ISSUE TITLE
MetaMask Transactions Not Being Processed on EtherDelta

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/metamask-extension#2271]
ref: #MET00257457 (with state logs)

> User: I'm currently having issues with withdrawing funds back into my MetaMask wallet. I'm trying to withdraw  ether and tokens back, but nothing seems to be happening. The trade keeps pending, and looking up the Tx hash on EtherScan gives me the 'Sorry, we are unable to locate the transaction entry' error. The transactions are not going through on etherdelta but the gas is showing subtraction on my MetaMask . Showing up on MetaMask different than on Etherscan ?

ref: #MET00257487 (with state logs

**Comment by callaloma** [comment]
Had the same issue. Try removing your Metamask extension from your browser and reinstalling it using your seed words (**make sure you have your seed words safed before you follow the steps**). Worked for me.

**Comment by jrmoreau** [comment]
additional state log ref: #MET00257480

**Comment by danfinlay** [comment]
Both of the referenced metamask tickets appear to have been users who submitted transactions with a low gas price (like around 4 gwei) during what seems to have been heavy network congestion. Once that low-gas-price tx was submitted, any subsequent (later-nonce) transactions had to wait for it before they could be processed.

Also, both of those referenced tickets' users seem to have worked around the issue, maybe by uninstalling/reinstalling and sending txs with higher gas price, or using another client.

Those are the workarounds at the moment. We are raising the priority on #2278 and should have a feature for "Resubmitting with higher gas price" soon. Until that's implemented, workaround steps are:

- Make sure your seed phrase is backed up
- Reinstall MetaMask
- Submit some alternative transactions with higher gas, which will “race” these other ones.
- If your new transactions get mined first, the old ones will be invalid, and will not be a concern, but make sure you send the same number of txs, but higher gas price, to avoid unwanted consequences.

**Comment by tr4vis** [comment]
Hi, I've been having the same problem for 7 days on Etherdelta with Metamask. I originally deposited 3 ETH into my Metamask account. Then I "sent" it to EtherDelta (Eth address ending in 819). It showed up as 2.99 -- great. But I have never been able to make ANY transaction ever with the 2.99 which is in the "EtherDelta" column (near the blue button). I thought it could be gas so I've now deposited over 1.1 ETH (over $300) into my Metamask again and it's showing up in "Wallet" column - great. So I have 1.1 ETH in that column and 2.99 in the EtherDelta column and I can not get a single transaction of any kind to go through. I'm trying to trade altcoins, deposit, transfer, withdraw --- NOTHING! Very frustrating... I saved my Metamask seed and uninstalled from Chrome and reinstalled, etc. I've literally spent 10 hours on this over the course of 7 days whenever I have a chance. What could the solution be? Thanks in advance.

![etherdelta nothing](https://user-images.githubusercontent.com/28112891/31302090-10206662-aacd-11e7-8bc6-bc0429b26157.jpg)

**Comment by tmashuang** [comment]
@tr4vis open a support ticket at [https://support.metamask.io](https://support.metamask.io) with your transaction/state logs. Here's how to get your state logs, [Copying State Logs](https://support.metamask.io/kb/article/15-copying-state-logs).

**Comment by danfinlay** [comment]
Pretty sure this was a congested network, closing b/c it's outdated, and we've fixed many bugs since this.

**Comment by porkchop315** [comment]
Having the same issues all day can someone help me

**Comment by nategrech** [comment]
Set a gas price of 30, made a buy, got given a transaction ID , no transaction goes through and not found on the blockchain?

**Comment by rdcx** [comment]
I'm having the same issue, got given ID, no transaction goes through and can't see on the blockchain

**Comment by eladleb** [comment]
I had the same issue today, using Ropsten testnet. 
I tried different gas prices, but none of my transactions were picked up by https://ropsten.etherscan.io

When I changed a metamask account user within the same browser, I successfully sent a transaction and it immediately appeared on etherscan.

When I switched the user in the browser and imported the same metamask account, I was able to send the transactions (even with a lower gas price).

I believe there is a bug within MetaMask which isn't directly related to network conjestion. Perhaps there is an issue with "retry with higher gas price" ?

**Comment by danfinlay** [comment]
@eladleb Please submit your debugging help request to support@metamask.io

We will probably want your logs to debug:
https://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs

**Comment by tr4vis** [comment]
This was a long time ago, but as best I recall this problem was solved for me by completely uninstalling the Metamask Chrome Extension and then reinstalling it (as always make sure you know your seed before during and after).

**Comment by danfinlay** [comment]
That may help work around the issue, but if you submit your logs, we may be able to prevent whatever you ran into from happening to others.

**Comment by eladleb** [comment]
@danfinlay Sent the logs as requested, hope it helps.

**Comment by ztnark** [comment]
I experienced this same issue. Uninstalling and reinstalling fixed the issue with the same gas price.

**Comment by porkchop315** [comment]
Will it erase my account I have eth in there

**Comment by danfinlay** [comment]
Never uninstall your account without your seed phrase backed up. If you have it backed up, you might even want to restore it on another computer before deleting the extension, to make sure you've written it down right.
