### ISSUE TITLE
Confirmations redesign - implement reject all button for confirmation pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#22744]
Currently at bottom of confirmation pages we have feature like below to reject all confirmations:

<img width="364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca1ccd205aa290ec7783aa23ae5e6948630ae839/Screenshot%202024-01-31%20at%2012.39.15%E2%80%AFPM.png" alt="Screenshot 2024-01-31 at 12.39.15 PM.png" />

Design: https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=982-45793&mode=design&t=UXL4JzT6G9DcDYVQ-0

**Comment by bschorchit** [comment]
I believe designs for these are here: https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=982-45793&mode=design&t=5zt1botZdDsqOf5v-0
@SayaGT can confirm

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/22744?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona

**Comment by jpuri** [comment]
Hey @SayaGT : currently on message page we are able to reject all messages on message page and transaction on transaction page. Does this behaviour continue in new implementation also ?
