### ISSUE TITLE
Confirmation redesign - add ledger instruction banner

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#22743]
In current confirmation pages we have ledger instruction banner displayed for ledger transactions, we need this in new confirmation implementation also:

Current:
<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzBVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d311a998cd3d9a6d71098d0f92c1a4d0dae2a3d1/Screenshot%202024-01-31%20at%2011.59.25%E2%80%AFAM.png" alt="Screenshot 2024-01-31 at 11.59.25 AM.png" />

For new implementation we follow design something similar to below, but we need to check. this with design team. cc @SayaGT <img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3c57fcbe56d1c3994cd67d2f318020f2f946b79/Screenshot%202024-01-31%20at%2012.02.02%E2%80%AFPM.png" alt="Screenshot 2024-01-31 at 12.02.02 PM.png" />

**Comment by SayaGT** [comment]
I can't seem to view the screenshots @jpuri. can you please share them separately with me. Thanks!

**Comment by jpuri** [comment]
Designs: https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=1703-34436&mode=design&t=mWM1UtB6YGXq4jyf-0
