### ISSUE TITLE
Confirmations redesign - port current blockaid / opensea error /warning to new designs

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#22747]

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/22747?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona

**Comment by seaona** [comment]
Update: the system team will take care of the error & warning part.
We can make sure this is accomplished on a future design review.
