### ISSUE TITLE
 [Bug]: PPOM - Storage is not cleaned up when removing a Blockaid supported network

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22777]
### Describe the bug

**Problem**: whenever we remove a Blockaid supported network, I see that the storage is not cleaned up and data regarding that network will stay there forever.

### Expected behavior

We should clean up the storage when a network is deleted, removing the data for that network

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/5041a727-f956-4c42-b803-88a727b85eae

### Steps to reproduce

1. Open the background console in the Application tab
2. Add a new supported network i.e. Optimism
3. Refresh the storage
4. See how the data for that network is now there
5. Now delete that network
6. Refresh the storage
7. See how the data is still there

### Version

11.10.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Linux

**Comment by jpuri** [comment]
Every 2 hours we have a regular job running to download old files and it also syncs the storage. I have made the code changes to ensure that this job delete files for networks no longer active.

Also, please note that PPOMController keeps record of networks user visited in last 1 week and caches data files for them. This is irrespective of whether the user keeps the network in extension or removes it.
