### ISSUE TITLE
[Bug]: NFT added to one account is wrongly displayed on all accounts

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#22794]
### Describe the bug

NFT added to one account via "watch asset" is wrongly displayed on all accounts and shows as previously owned in all of them after being sent out. 

Important mention, it cannot be sent out from the other accounts that don't own the NFT even though it is displayed in them. 

Workaround: adding another account to the wallet helps get rid of this issue and the user can then continue importing the NFT via contract address and asset ID in the receiving account. P.S.: The mention of "previously owned" dissapears also from the initial account that owned the asset, when it should not.

### Expected behavior

NFT is only displayed in the asset list of the account that owns it.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/640aa6a2-58c5-46e1-b423-d6fcd5a57f9d

### Steps to reproduce

1. Load MetaMask and connect an account to https://metamask.github.io/test-dapp/ (precondition: have a secondary account added in the wallet)
2. Deploy NFT
3. Mint NFT
4. Watch NFT
5. Proceed to MetaMask, notice the NFT is displayed on both accounts in the asset list
6. Try to send the NFT from the second account (that does not own the NFT) - notice it will not work
7. Send the NFT to the secondary account - the transaction is successful. Notice how the NFT is displayed on both accounts as previously owned. 
8. Create a third account - hover back to accounts 1 and 2 and notice the NFT dissapears, alongside the previously owned mention and then the user can proceed and import the NFT via contract address and asset ID.

### Error messages or log output

```shell
N/A
```

### Version

11.10.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Prod build

**Comment by danjm** [comment]
Confirmed that this was fixed with 167036f
