### ISSUE TITLE
[Bug]: Unable to send ERC-20 Approval transaction in gas-free case

### ISSUE THREAD

**Issue by Karkunow** [MetaMask/metamask-extension#22793]
### Describe the bug

While sending the gasless ERC-20 Approval transaction, the user with 0 ETH in his wallet gets "Insufficient funds for gas" error, even if he doesn't need to pay anything.

### Expected behavior

We are expecting it not to throw the error "Insufficient funds for gas", because we do not charge gas for such interaction with the Aurora ERC-20 contract. And you can see clearly, that the fee is 0 ETH there.

### Screenshots/Recordings

Here is the video demonstration of what is happening:
https://www.youtube.com/watch?v=aNnGhvDTJmc

Here is the popup with the error:
<img width="386" alt="Screenshot 2024-02-02 at 12 35 19" src="https://github.com/MetaMask/metamask-extension/assets/2808283/d28d0432-57cc-4627-b0e5-ad4409d68ff6">

And here is the second one without it:
<img width="408" alt="Screenshot 2024-02-02 at 13 15 31" src="https://github.com/MetaMask/metamask-extension/assets/2808283/616de734-2629-4b67-8807-c0ab478ba722">

### Steps to reproduce

1. Go to https://aurora.plus/
2. Connect Metamask wallet and switch to AuroraMainnet [important, you need to have 0 ETH there on Aurora network].
3. Click on "Stake" and then on "Approve my AURORA" button.
4. Get an approval popup, click "Next"
5. Get an error about insufficient funds.

### Version

11.7.5

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

### Additional context

You can now do the next steps to trick the Metamask and do the transaction:
1. Click outside the popup.
2. Click on Metamask icon.
3. See the same popup, but now it is not native one! The first popup with an error was a native one, with the window controls (like hide, and close buttons) and I could move it freely over the screen. This one I can't.
4. Notice, it has no errors. And we can just Send the transaction.

### Severity

- It is visible to all of the users who use Aurora+  and has 0 ETH in their wallet, and I think this apply to any other gasless ERC-20 contracts on other networks.
- Probably mid severity.

**Comment by dbrans** [comment]
Hi @Karkunow, thank you for reporting this bug. 

I'm having trouble following the steps you provided to reproduce this bug. The "Stake" button is disabled for me:

![Image](https://github.com/MetaMask/metamask-extension/assets/507015/a9dd98c2-8fe9-4135-acb1-f2347af7d3d7)

To be clear, I have no AURORA tokens and no ETH on Aurora.

**Comment by Karkunow** [comment]
@dbrans hi! yes, sorry, forgot to say that you need to have some AURORA - I can send some to your wallet, just let me know

**Comment by dbrans** [comment]
> @dbrans hi! yes, sorry, forgot to say that you need to have some AURORA - I can send some to your wallet, just let me know

@Karkunow, could you send the AURORA to 0x2990079bcdEe240329a520d2444386FC119da21a? Thank you.

**Comment by Karkunow** [comment]
> > @dbrans hi! yes, sorry, forgot to say that you need to have some AURORA - I can send some to your wallet, just let me know
> 
> @Karkunow, could you send the AURORA to 0x2990079bcdEe240329a520d2444386FC119da21a? Thank you.

Done. Sent 0.1 AURORA to you. Should be enough to test.

**Comment by dbrans** [comment]
Hi @Karkunow, I'm trying to reproduce on 11.9.5 but I don't get an "Insufficient Funds for Gas" error. It seems to work fine:

<img width="353" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/507015/b57973c1-b639-4360-8a84-7f8e4a2b1be7">
<img width="346" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/507015/83362fab-eafc-4fed-80b9-ba384dab999d">

**Comment by Karkunow** [comment]
@dbrans Just tested it and it is still reproducible. Make sure you get the native OS window first. And not the one from the extension. 
Here is what I get in native window on 11.9.5:
<img width="366" alt="Screenshot 2024-02-22 at 13 52 24" src="https://github.com/MetaMask/metamask-extension/assets/2808283/67eb2251-0bf5-4988-91ce-015eff676ef8">

And later, in the extension window, if I click outside of the first one and reenter:
<img width="379" alt="Screenshot 2024-02-22 at 13 52 55" src="https://github.com/MetaMask/metamask-extension/assets/2808283/ca11ae76-997d-4ad0-b24b-107b589973a1">

**Comment by dbrans** [comment]
Hi @Karkunow, I confirmed on my end that I get the native OS window as you mentioned. However, I don't encounter the "insufficient funds" message that you're running into. I've attached a screen recording below for you to take a look. Could I be missing a step somewhere? Let me know!

https://github.com/MetaMask/metamask-extension/assets/507015/69956976-a058-443c-86ac-a322c8c18904

**Comment by Karkunow** [comment]
@dbrans I've rechecked - still have the error there.
<img width="365" alt="Screenshot 2024-03-01 at 14 53 11" src="https://github.com/MetaMask/metamask-extension/assets/2808283/ed414f0f-094d-419b-84af-93e2b5423bfa">
Metamask version 11.10.0.

**Comment by Karkunow** [comment]
Do you have 0 ETH on your wallet?

**Comment by dbrans** [comment]
@Karkunow I just realized I missed that crucial detail after switching to a new testing account, and I'm really sorry for the mix-up and the back-and-forth over the last couple weeks. Thanks for your patience.

Good news, though—I can now consistently reproduce the issue, which means we're on the right track to sorting it out.

Thanks for bearing with me, and I'll make sure we get this fixed as soon as possible. In the meantime, I'll post regular updates.

**Comment by Ramyromel** [comment]
Translation.. ميتا ماسك لم يحمينى من الهجمات داخل التليفون وداخل المحفظه . المعامله صعبه وجدا وتليفونى متكتف منذ يومين . حاول تساعدونى .. انا بيحصل فى تليفونى حاجات غريبه جدا

**Comment by Ramyromel** [comment]
Help me please 🥺

**Comment by dbrans** [comment]
> Translation.. ميتا ماسك لم يحمينى من الهجمات داخل التليفون وداخل المحفظه . المعامله صعبه وجدا وتليفونى متكتف منذ يومين . حاول تساعدونى .. انا بيحصل فى تليفونى حاجات غريبه جدا

@Ramyromel, please go to [support.MetaMask.io](https://support.MetaMask.io) select “Start a conversation” and our User Safety team will assist you.

**Comment by dbrans** [comment]
After some investigation:

When this bug is triggered, I see an inconsistency where the "Fee details" shown on the confirmation screen don't match the "Transaction fee" displayed above. The expected fee (and fee details) is zero. This is likely causing the "insufficient funds for gas" message on that screen when the user has zero ETH in their account.

Below is an image highlighting this issue:

<img width="361" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/507015/da807000-e138-4dd8-8abb-3f2606526976">

---
@Karkunow, I'm going to triage this bug to the right team based on these findings.

**Comment by Karkunow** [comment]
@dbrans glad you've managed to reproduce this! looking forward to triage.

**Comment by bschorchit** [comment]
Hey @Karkunow sorry for the delay in getting to this. Could you test it on the latest version of MetaMask v12.8 and with this toggle enabled in settings "Improved transaction requests" to check if you still encounter the issue? Alternatively, you can send Aurora to this address so I test it: 0x9B285340bB67eb56fd093a612784c0B5FD5304c4

 ![Image](https://github.com/user-attachments/assets/319cf103-431b-4b7e-bbd2-50c1928d78ac)

**Comment by benjisclowder** [comment]
This is no longer reproducible in 12.10.0.

![Image](https://github.com/user-attachments/assets/b3e134e3-d4ed-4c53-9485-06e4c2238329)
