### ISSUE TITLE
[ENHANCEMENT] Add support for ENS on Sepolia 

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#22797]
### What is this about?

Currently ENS is not supported on Sepolia and with further deprecation of Georli, ENS testing will be blocked due to Sepolia not supporting this. 

Message that comes up when typing a valid ENS address at the moment: No address has been set for this name.

### Scenario

- GIVEN a user is trying to send a transaction to a ENS address
- WHEN a user is typing the ENS address
- AND a user wants to proceed with the transaction
- THEN ENS address should be accepted 

### Technical Details

ENS support needs to be added on Sepolia due to deprecation of Goerli and lack of means to test the ENS feature in these conditions.

### Threat Modeling Framework

This will help us further test the feature and prevent issues from being released in prod. 

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Chomtana** [comment]
Hi, @benjisclowder I have added ENS support for Sepolia to the Metamask. The original author of `ethereum-ens-network-map` has not maintained their package anymore. We can help continue maintaining this package if you like.

https://github.com/MetaMask/metamask-extension/pull/22869

**Comment by mirceanis** [comment]
will be resolved by #26242
