### ISSUE TITLE
Investigate as prop Typescript update

### ISSUE THREAD

**Issue by garrettbear** [MetaMask/metamask-extension#22803]
@georgewrmarshall  would like to scrutinize this PR https://github.com/MetaMask/metamask-extension/pull/22523 and see if an update can be made at the `Box` component level

**Comment by davidmurdoch** [comment]
The PR deals with the `Text` component as well.

**Comment by georgewrmarshall** [comment]
Excellent work on the fast issue creation. We resolved it! https://github.com/MetaMask/metamask-extension/pull/22523
