### ISSUE TITLE
[Bug]: PPOM - MM enters into a broken state if the PPOM storage is cleared

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22810]
### Describe the bug

**Problem:** if for some reason the storage of the app is cleared, I see that the wallet does not recover the files and continues to work normally, like in 11.7.5, but it now enters into some sort of broken state:
- After refreshing the wallet and switching networks I get this error in the console: `metamask-controller.js:718 Error in reading file: Failed to execute 'digest' on 'SubtleCrypto': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'.` (in 11.10)
- After trying to switch networks, they were not changed
- After trying to trigger tx's, the popup was not opened
- I see the storage is empty, even after I've cleared, but initially I could still trigger tx's and see them being flagged (not sure if this is expected, this also happens in 11.7.5)

### Expected behavior

- We should be able to recover the ppom storage by making again cdn requests and downloading the files
- We should be able to switch networks
- We should be able to trigger tx's

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/3787693b-e1aa-4c25-84fe-a8fef815aead

![Screenshot from 2024-02-05 12-34-03](https://github.com/MetaMask/metamask-extension/assets/54408225/d2f1cff6-e65d-4164-9a80-e9091d3f50c1)

https://github.com/MetaMask/metamask-extension/assets/54408225/87688158-2eef-4717-a1f5-ded8ca44ceb8

https://github.com/MetaMask/metamask-extension/assets/54408225/fd398e2b-f4c8-48fb-9a31-140ea49d61f9

Expected: see correct behaviour like in `11.7.5`

https://github.com/MetaMask/metamask-extension/assets/54408225/2315f552-f9ce-4d2c-9e07-e3ca73218004

### Steps to reproduce

1. open the background console
2. click on Application // storage
3. Select a supported network in mm (i.e. Linea)
4. go to the test dapp
5. see tx's are triggered and validated
6. now right click on ppom storage and click Clear
7. refresh storage, to see the data is cleared
8. go to the wallet
9. change networks - see is not possible
10. 

### Version
11.10.0 not in 11.7.5

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
Closing the issue as it can not be reproduced in latest code.
