### ISSUE TITLE
[QA] Add e2e test and manual scenario for settings:about metamask page

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#22812]
### What is this about?

Add e2e test and manual scenario for about metamask page

### Scenario

- Version 
- Links
- Close button

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by hjetpoluru** [comment]
Thanks Chloe for creating ticket and manual test steps are included.

**Comment by chloeYue** [comment]
Hi @hjetpoluru , i think we need more elements to complete this ticket.
- In general, we need to get the PR merged to consider that this ticket is complete, then we can close this ticket.
- See the scenario description of this ticket, we also need e2e test AND manual scenario documentation for links on about page.
