### ISSUE TITLE
PPOM - Loading Spinner Style

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22842]
### What is this about?

**Context**: in the 11.9 release, it has been introduced a loading spinner state for Extension, that is display and visible during the ppom validation. If it's fast, you almost don't see it, but if it's slow, you see a small spinner on top of the confirmations screens. (See below).

We want to add some styling, since specially in custom screens is hard to see.

This includes all screens and custom screens:
- Signatures
- Approve ERC
- SetApproval for All
- Transfer ERC
- Send Eth

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/3f9affb5-e65b-4f87-9a33-e131d0055eb0)

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/9d464a41-8ae9-4f92-84f6-f2b22c6bebf2)

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [X] Design
- [X] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/22842?planning-poker) with Zenhub @blackdevelopa @jpuri @seaona @digiwand
