### ISSUE TITLE
[Bug]: Metamask keeps trying to connect Ledger device when clicking add hardware wallet

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-extension#22851]
### Describe the bug

The request to connect to a HID device pops up every time the user tries to add a new hardware wallet. If the request is canceled, an error appears. If the request is accepted and ledger is connected, it automatically navigates to the Ledger device option with the list of accounts. 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/106310394/cb58e867-03ad-46b3-b59d-548b325dcdc0

### Steps to reproduce

1. Add Ledger device
2. Click on account
3. Add hardware wallet
4. Wait for the pop up for HID access
5. Click cancel
6. Error appears
7. Click on account
3. Add hardware wallet
4. Wait for the pop up for HID access
5. Click connect
6. Ledger is automatically navigated to the accounts of Ledger device

### Version

11.10.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

**Comment by gauthierpetetin** [comment]
Hi @vivek-consensys , do you know if the hardware wallet team has time to look in this?

**Comment by vivek-consensys** [comment]
I am able to replicate this issue on v11.14.1 of MM Extension. @Akaryatrh can you debug?
