### ISSUE TITLE
Clicking on Metamask icon and blank window appears

### ISSUE THREAD

**Issue by amirsohail01** [MetaMask/metamask-extension#2286]
Hi

I am clicking on the MetaMask icon from Google Chrome (version 53.0.2785.116 m) and the popup window opens as completely blank. Can anyone help? Screenshot attached. 

Tried re-installing the extension and restarting PC multiple times already. 

Thanks

![image](https://user-images.githubusercontent.com/12250521/31205827-a39c4c08-a9bf-11e7-9ef6-dc0a325e9f77.png)

**Comment by danfinlay** [comment]
What version of MetaMask are you using? Do you see [any red errors in the popup logs?](https://github.com/MetaMask/faq/blob/master/LOGS.md#popup-logs-chrome)

This looks like #2025 and I recently had to reopen #1372 for a similar result.

It looks like some people have no code in their Chrome MetaMask distribution:
`Uncaught SyntaxError: Unexpected identifier`
which points to:
`async initialize () {}`

**Comment by amirsohail01** [comment]
Hi Dan

Thanks for the response. I suppose the MM version would be 3.10.8. Below is what I see what I go to Console. 

![image](https://user-images.githubusercontent.com/12250521/31206439-8d1a20b4-a9c3-11e7-8a9c-0159d3478b1a.png)

**Comment by amirsohail01** [comment]
I updated my Google Chrome to latest version now i.e. new version 61.0.3163.100 (Official Build) (64-bit) and MetaMask is working fine now. Issue can be closed. 
Thanks
