### ISSUE TITLE
transactions on loose account not going through

### ISSUE THREAD

**Issue by qjflores** [MetaMask/metamask-extension#2287]
I've imported a loose account on into metamask

none of the transactions that I sign are going through

I've tried two types of transactions - one on a consensys multisig and a normal transaction to a metamask address

**Comment by qjflores** [comment]
The balance showing in metamask is also showing a different amount than on etherscan.

**Comment by Zanibas** [comment]
Is this issue still persisting for you after the recent update?

**Comment by qjflores** [comment]
not working with 3.11.0

https://etherscan.io/tx/0x19d4adfd4b1c4a40183bf46aa8f147d57722f0d782cf918203f2f457c6f04d3a

The transaction just remains pending

**Comment by bdresser** [comment]
@qjflores sorry for the long delay. is this still an issue for you on 4.7.4?

**Comment by whymarrh** [comment]
Closing this for now—@qjflores let us know if you're still having issues
