### ISSUE TITLE
[Bug]: Metamask 11.9.0 - can not change gas option or value any more

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#22872]
### Describe the bug

I want to send ETH , but can not set gas estimation mode (low/market/high/advanced) or gas value when in Advanced Mode.

### Expected behavior

I expect that I can either select the gas estimation mode (low/market/high/advanced) or when in `Advanced Mode` specify the gas amount - neither is possible.

### Screenshots/Recordings

![Metamask 11 9 - send ETH - step 1](https://github.com/MetaMask/metamask-extension/assets/25609/81015e42-870c-4752-aaac-bd6b666c7f9d)

![Metamask 11 9 - send ETH - step 2](https://github.com/MetaMask/metamask-extension/assets/25609/2d659bbd-8b44-4c3b-9c74-2bce0d2c53cf)

### Steps to reproduce

1. click [send]
2. select destination account 
3. [step 1 - on Send page] enter ETH value, Estimated Fee is displayed "Market ~30 sec 0.0012.. , Max Fee 0.0017..]
4. there is NO possibility to change the gas estimation from `Market` to something else
5. click [Next]
6. [step 2 - on Sending ETH page] Estimated fee is now in `Advanced` mode showing 0.000525 ETH, Max fee: 0.000525
7. Obviously the gas fee is too low, 
8. ... but there is NO way to change the gas estimation mode from `Advanced` to `Market` , `Low`, or `High`
9. ... also there is no way, although in `Advanced` gas estimation mode to change the gas value

### Version

11.9.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Severity

- HIGH as neither gas estimation mode nor gas value can be set , so all tx will fail

**Comment by ZbrancaI** [comment]
Hey @SvenMeyer ! Thank you for reporting this issue! Our team is investigating it!

**Comment by danjm** [comment]
@SvenMeyer What network were you on when you saw this?

**Comment by SvenMeyer** [comment]
@danjm Ethereum mainnet, and I am 90% sure that I used Infura RPC

**Comment by SvenMeyer** [comment]
browser : `Version 120.0.6099.199 (Official Build, ungoogled-chromium) Arch Linux (64-bit)`

**Comment by bschorchit** [comment]
Hey @SvenMeyer, thank you for your report! We found the issue and are working on releasing a fix for it soon. In the meantime - as a workaround - you can enable the `Show balance and token price checker` and that should make the `edit` button visible on the sending ETH page. 

![Screenshot 2024-02-09 at 6 33 04 PM](https://github.com/MetaMask/metamask-extension/assets/34968356/45b45653-1f8b-43fd-8d1c-ebfd33fc5866)

**Comment by sandy7012** [comment]
I can not open app in metamask wallet what I do
