### ISSUE TITLE
My screen is blank when I open Metamask. Can anyone assist?  Thank you

### ISSUE THREAD

**Issue by tobydaniel2** [MetaMask/metamask-extension#2288]
I even removed it from my Chrome browser and reinstalled it and it still turns out blank. I have my seed phrase if I need to delete Metamask from my computer.
FAQ:
  BEFORE SUBMITTING, please make sure your question hasn't been answered in our FAQ: https://github.com/MetaMask/faq
  Common questions such as "Where is my ether?" or "Where did my tokens go?" are answered in the FAQ.

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by Zanibas** [comment]
Please provide the type of browser used and your OS so we can diagnose this issue better!

**Comment by tobydaniel2** [comment]
Hello, I use the latest version of Chrome and Mac OS.

**Comment by bdresser** [comment]
@tobydaniel2 do you still encounter this issue?

**Comment by tobydaniel2** [comment]
No I don’t. Thanks
