### ISSUE TITLE
[Bug]: Signatures - MetaMask breaks with the error `Invalid primary type definition`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22899]
### Describe the bug

**Problem:** whenever we pass a non-existent type as `primaryType` the wallet breaks with the error  `Invalid primary type definition`

### Expected behavior

- The wallet should not break
- It needs to be defined a proper way of handling these cases

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/63a9f8b7-c72b-462b-9b0d-b87f8ccfe3fa

### Steps to reproduce

1. Go to the test dapp
2. Click 'Invalid Primary Type'
3. See wallet breaks

### Version

11.9.0 but it's an old issue

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
Present in v12.0.5:


https://github.com/user-attachments/assets/f883fa8a-3bf2-4736-9aa8-f2c49ee2280d

**Comment by Unik0rnMaggie** [comment]
Present in v12.4.0 RC

https://github.com/user-attachments/assets/d88d89df-9234-4d3e-bebd-3e93bd555f73
