### ISSUE TITLE
[Bug]: Signatures - MetaMask breaks with `TypeError: text.slice is not a function` when passing invalid `verifyingContract`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22901]
### Describe the bug

**Problem:** whenever we pass a signature with an invalid `verifyingContract` value (ie. an integer instead of an address), MetaMask breaks with the error `TypeError: text.slice is not a function` when clicking Verify third party details. There are multiple errors around that.

If I pass a number I see

![Screenshot from 2024-02-23 15-33-02](https://github.com/MetaMask/metamask-extension/assets/54408225/b7388b0f-cc66-4492-833c-7b34968ac3c7)

If I pass a string I see

![Screenshot from 2024-02-23 15-34-26](https://github.com/MetaMask/metamask-extension/assets/54408225/f1e9c95f-62af-4eb8-b712-9fcc3a8aa007)

### Expected behavior

to define with signatures validation refactor

### Screenshots/Recordings

![Screenshot from 2024-02-11 12-43-08](https://github.com/MetaMask/metamask-extension/assets/54408225/17348d42-f621-4122-b0df-bf6792a3c135)

https://github.com/MetaMask/metamask-extension/assets/54408225/9778cc6d-5889-460b-a407-4e09d0267732

### Steps to reproduce

1. Checkout the test dapp https://github.com/MetaMask/test-dapp/pull/290
2. Connect MM
3. Click Invalid Verifying Contract Type
4. Click Verify Third Party details
5. See error

### Version

11.9.0 but it's an old issue

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Closing as of v12.1.2 we're only accepting hex addresses for verifyingContract :)
