### ISSUE TITLE
[Bug]: Signatures - Passing extra data not typed is added in the signature but not visible on the UI

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22900]
### Describe the bug

**Problem:** passing extra data which is not in the typed definition, results in being it hidden in the UI but actually being signed in the signature result

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/301147cc-3dd7-4272-b7e0-460ac980d23e

### Steps to reproduce

(See video)
1. Checkout test-dapp
2. Add an extra field in a typed 4 signature
3. Sign it -- see the extra data is not there
4. Copy the hash result
5. Remove the extra field in the same signature
6. Sign it -- copy the hash result
7. Compare to hashes -- see they are different

### Version

11.9.0 but introduced earlier

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
This is as per requirement, please check this PR: https://github.com/MetaMask/metamask-mobile/pull/9795

Fields which are not typed are not part of finally signed message.
