### ISSUE TITLE
Confirmation redesign - add feature to navigate between transactions

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#22935]
<img width="344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ea5a27d573f041d8f915870c989eb909f980e8d/Screenshot%202024-02-14%20at%2012.21.56%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 12.21.56 PM.png" />

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-extension/pull/22942 mentions that fixes this issue
