### ISSUE TITLE
[Bug]: Popup remains open after Reject/Accepting a tx, if I was on the Edit screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22939]
### Describe the bug

**Problem:** whenever I start a transaction from a dapp (popup), if I click Edit, and then open the Unapproved transaction from the wallet view and Accept/Reject it from there, the Edit popup screen remains open

### Expected behavior

- The popup should be closed since the tx has been accepted/rejected.
- Not sure if when we open the Unapproved tx we should be also in the Edit screen, or in the last confirmation screen 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/28a27dd8-07a0-46d3-91ce-f26cc11865a8

### Steps to reproduce

1. Go to the test dapp
2. Trigger a Send ETH tx
3. Click Edit
4. Now go to the MM wide wallet view
5. Click the Unapprove tx
6. Accept it or Reject it
7. See the popup remains open

### Version

11.9.0 prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
This appears to already be fixed in the latest code.
