### ISSUE TITLE
[Bug]: MetaMask unresponsive after adding and switching networks from a dapp

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22937]
### Describe the bug

**Problem:** whenever I add a netowrk from a dapp, MetaMask stays unresponsive and I see an empty error in the background.
If I reload MetaMask I see how the network was not added and I remain in the previous selected network.

- This is not happening in prod builds
- Furthermore, this is not happening if I add this same network manually
- The error appears independently of having the `Select networks for each site` enabled or disabled - makes no difference

### Expected behavior

MetaMask should switch networks and continue to work. I am able to do it in prod

### Screenshots/Recordings

![Screenshot from 2024-02-14 09-39-33](https://github.com/MetaMask/metamask-extension/assets/54408225/86b103be-6303-4fea-aa4c-5f37d533e99e)

https://github.com/MetaMask/metamask-extension/assets/54408225/b838f6d1-77a8-432b-a75c-8b20341a0a7d

### Steps to reproduce

1. Go to chainlist https://chainlist.org/?testnets=true&search=bsc
2. Connect MM
3. Add a Network Binance Testnet
4. Approve
5. Switch networks
6. Click again the MM icon--- see it's unresponsive, see error in the background

### Version

develop - with multichain flag

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by shanejonas** [comment]
@seaona this is only with the request queuing toggled on right?

**Comment by darkwing** [comment]
This does not appear to be related to send flow.

**Comment by seaona** [comment]
Update: after investigating further with Shane and Alex, we've seen that this is the same issue as this one https://github.com/MetaMask/metamask-extension/issues/21929 which was already present before. From slack: 'it seems related to queueing multichain' and it might be that the work on that area fixes this one
