### ISSUE TITLE
[Bug]:  Outdated year in the footer section

### ISSUE THREAD

**Issue by subhamkumarr** [MetaMask/metamask-extension#22957]
### Describe the bug

The footer copyright year is `2023`

### Expected behavior

The footer copyright year is should be `2024`

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/99977240/13ab0faa-4f7f-404a-b4e1-38fe7114302d)

### Steps to reproduce

1. Scroll down to footer section and see the copyright year.

### Version

latest version

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by subhamkumarr** [comment]
I would like to work on this issue. Can I get this issue assigned?

**Comment by anaamolnar** [comment]
Hey @mapachurro. Can you help with this? Thanks!

**Comment by mapachurro** [comment]
... Why yes, yes I can 🫡
I will fix this Soon

**Comment by mapachurro** [comment]
Fixed last week! Thank you for your diligence, all!
![image](https://github.com/MetaMask/metamask-extension/assets/7252642/716d946e-208f-4f7c-a1fe-97f3b410de3f)

**Comment by subhamkumarr** [comment]
@mapachurro did you raised PR for this?
