### ISSUE TITLE
[Bug]: alignment issues on `Add suggested tokens` confirmation

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#22952]
### Describe the bug

Confirmation screen issue after deploying an ERC20 contract and adding tokens to wallet with the [test dapp](https://metamask.github.io/test-dapp/) in 11.11.0 RC commit 6d34630bb78be87da26ee45efad4fcf29d332b87

Chrome 117.0.5938.92
Mac Sonoma 14.2.1

### Expected behavior

address alignment and spacing

### Screenshots/Recordings

![Screenshot 2024-02-13 at 9 18 53 PM](https://github.com/MetaMask/metamask-extension/assets/32695229/3e55623a-bfc7-4732-ad95-4824fde5f21f)

### Steps to reproduce

1. Have wallet setup and an address with testnet funds
2. go to test dapp
3. Connect
4. Scroll down to `Send Tokens` and tap `CREATE TOKEN`
5. Once contract deployment is confirmed tap `ADD TOKEN(S) TO WALLET`
6. Observe `Add suggested tokens` confirmation

### Version

11.11.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Closing as no longer an issue
![Image](https://github.com/user-attachments/assets/51bb0c2c-d3f4-43bc-a303-f5c529450225)
