### ISSUE TITLE
Accounts list pin / hide animation looks like the cells are draggable 

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#22969]
The current animation by the top of our accounts modal (supposed to educate the user about pinning / hiding) is literally dragging one (account) cell to another position in the list. Which, in production, is not something you can do within this list (yet?). _Works great for the network list tho!_

![image](https://github.com/MetaMask/metamask-extension/assets/34306844/5853b8db-2336-4c73-a5f7-5b8299dad372)

### Acceptance Criteria

Short term: Hide the banner, this is probably not something we need to announce.
Long term: Create animation for hiding / pinning (not sure this is something we really need to prio tho tbh)

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [X] Design
- [X] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

Slack thread: https://consensys.slack.com/archives/C06FXU326RL/p1707992423722049?thread_ts=1707919071.665089&cid=C06FXU326RL

**Comment by hesterbruikman** [comment]
Closing in favor of duplicate https://github.com/MetaMask/metamask-extension/issues/23321
