### ISSUE TITLE
Sorry for the difficulty here, but thank you for taking the time to share this report.  I am not able to reproduce on my Samsung A515f running android 12, even with the font display at the largest and the zoom set at max. Is there any further info you can share to help us reproduce?

### ISSUE THREAD

**Issue by vania221** [MetaMask/metamask-extension#22973]
Hi👋              Sorry for the difficulty here, but thank you for taking the time to share this report.  I am not able to reproduce on my Samsung A515f running android 12, even with the font display at the largest and the zoom set at max. Is there any further info you can share to help us reproduce?

_Originally posted by @plasmacorral in https://github.com/MetaMask/metamask-mobile/issues/7511#issuecomment-1934849395_

**Comment by plasmacorral** [comment]
It is unclear to me why this user is opening a new issue for our extension client by simply coping my response to a mobile issue that is missing information.  I'll give the benefit of the doubt and some time before I check back to see if there are edits or any actionable information, then I intend to close this issue and report the user to github.
