### ISSUE TITLE
[Bug]: Max Gwei value from transaction on account A, persists across send tx on account B and C

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#22976]
### Describe the bug
Chrome 117.0.5938.92
Mac Sonoma
Tested with dist build of commit 6d34630bb78be87da26ee45efad4fcf29d332b87 for 11.11.0 RC

My first transaction after migrating from a dist build of 11.10.0 to 11.11.0 yesterday was a send tx to fund a new snap account I created with the [SSK v1.1.1](https://metamask.github.io/snap-simple-keyring/1.1.1/)

That [transaction (t1)](https://sepolia.etherscan.io/tx/0x92869b28b3c16863488e2e5fcd91fff8ffa18336bb2ab2aab9fe7827387a85a3) from[ account A](https://sepolia.etherscan.io/address/0x8d5daa0375b302d9a2c290612609d9a6e801b2e6) was sent with max Gwei= 63.831029746 even though gas for that [block](https://sepolia.etherscan.io/block/5282839) and the [block before it](https://sepolia.etherscan.io/block/5282838) were ~45 Gwei.

Then I switched to that [account B](https://sepolia.etherscan.io/address/0x8a20c19933ffce706c36110bc2621af0e1b7cf12) that I had just funded and connected to our [test dapp](https://metamask.github.io/test-dapp/).  I attempted to do a legacy send, but site suggested gas was too low at 10 Gwei.  In my state logs there is indication that this tx with hash 0x4e2c7476c0b4af7fd30fcd019a1dd060845211dec89d32ae80b92135eea1d5fa was dropped, and etherscan could not find it at the time.  However, it was still showing pending in my activity view, so I clicked into the tx details and tapped `Speed up`.  The confirmation was pre-populated with this same value, 63.xxxxx .  I tapped save, and since the SSK was still on the default setting for Synchronous transactions, I did not need to approve this tx within the test Snap's dapp and upon my saving of the new gas values this replacement was broadcast.

The next two send tx from this account included that same Max Gwei value when sending with account B.

Then I switched to [account C](https://sepolia.etherscan.io/address/0x81526d72edec700353dacd11b6788c98af6c3a0e) which was a QR hardware address, and 9 of the next 16 nonces I broadcast to Sepolia all had this same Max Gwei value of 63.xxxxx

At no time was I asked to if I wanted to save this gas value, but it seems like it was definitely saved.  Beyond wondering how it was saved, I also wonder where the 63.xxxxx value originated from since I never entered that or otherwise tinkered with gas settings throughout these tests.  Even for the speed up, I simply saved the pre-populated values that were suggested.

Please note: for All etherscan tx's linked, you can tap `Click to show more` in the tx details to see this max Gwei value.

### Expected behavior

Max Gwei should not be saved and persisted without user input

### Screenshots/Recordings

[Account A-t1](https://sepolia.etherscan.io/tx/0x92869b28b3c16863488e2e5fcd91fff8ffa18336bb2ab2aab9fe7827387a85a3) 
[Recording](https://recordit.co/AraLoek6fe) of this tx
Confirmation screens:
<div style="display: inline-block"> <img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/bb7f9985-b16b-4a10-9591-ac27c5bf979a"><img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/fb4db196-9a97-4385-bbd7-c68c4af46cb1"></div>

[Account B](https://sepolia.etherscan.io/address/0x8a20c19933ffce706c36110bc2621af0e1b7cf12) legacy send first attempt:
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/97a9d19b-e21d-442d-8e20-61b10fe40893">

Account B Speed up [replacement](https://sepolia.etherscan.io/tx/0xaf6244bbc42d1a1350e702a4466c86d8737ade0db6f99e9a7a085e4d3f479ffb)
[Recording](https://recordit.co/LqMyGHE3qP) of initial legacy send and subsequent speed up tx
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/8cd173ab-afe3-47da-bd99-85299ba39e21">

Account B nonce [1](https://sepolia.etherscan.io/tx/0xa1608c8c0ea734781839d1db27255753852f0be820cd8793a4277ffc89ed6e7d) was an EIP1559 send from the test dapp:
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/06a39a8b-d040-48d7-a834-744d5ecea150">

Account B nonce [2](https://sepolia.etherscan.io/tx/0xdad5396277f061fa75b81909a72bf534fdc6e28188ba95c213b376aae4b097cc) was a send initiated from within extension: 
<div style="display: inline-block"> <img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/f397658d-f276-4065-a586-d379cb23b5dc"><img width="200" src="https://github.com/MetaMask/metamask-extension/assets/32695229/59f75f17-4efd-4a2f-a882-1176a5aa9b4c"></div style>

Then [Account C](https://sepolia.etherscan.io/address/0x81526d72edec700353dacd11b6788c98af6c3a0e) has 9 of 16 subsequent nonces broadcast showing this same max Gwei value of 63.xxxx
They are nonces: [72](https://sepolia.etherscan.io/tx/0x23ab865bacfb21b15648587f936f6d0fde241d311496e261f0a21db6fcf0b99b), [75](https://sepolia.etherscan.io/tx/0x74b9db75f994c7869e4fc0a58632803947237ece0a8b1c4d124e4c754310f536), [80](https://sepolia.etherscan.io/tx/0xe81396efb7f50019d6ea23b01fbae87bc7e795476a6bcfaef3cb6560df0303ba), [81](https://sepolia.etherscan.io/tx/0x6fb8b9263d5b7926bfdd9785cc2568fa24c5c7a88f6568246fed859c5ad142c3), [82](https://sepolia.etherscan.io/tx/0xabf3f06ea2090a464aac85119e8546491a7eff4ddd829103a1715b8ba6d334ee), [83](https://sepolia.etherscan.io/tx/0x3c7c8dc2b8cfbe9712c621116c212bf7d3652bdfe99b2362b20a0349b2a28448), [84](https://sepolia.etherscan.io/tx/0x03bb8f45e7f960d5500b5520e6622b10f06a2118f67820f9a3697034dcc1619d), [85](https://sepolia.etherscan.io/tx/0x6fae98b8246d5b99b20929362cb01e42440e4f76f0d48f7b6df1ef017bbec2c4), and [86](https://sepolia.etherscan.io/tx/0x2badc9198ca26913fff18209d476aec59fd8dcbbf5f5ed647da170757aac5380)

### Steps to reproduce

1. Import an SRP with an account that has testnet funds available with version 11.10.0 
2. Upgrade to to v11.11.0
3. Open [SSK](https://metamask.github.io/snap-simple-keyring/1.1.1/) and connect and install the snap
4. Create a new account with SSK
5. Fund new account from testnet funds on HD account
6. Switch to new snap account
7. Attempt legacy send with the [test dapp](https://metamask.github.io/test-dapp/)
8. Try to speed up legacy send and check if max GWEI from first tx is prepopulated
9. save new values to send replacement speed up tx
10. Run further send tx to see if max gwei persists
11. Switch to another account and see if max gwei persists

### Version

11.11.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

State logs: 
[MetaMask state logs_issue22976.json](https://github.com/MetaMask/metamask-extension/files/14300717/MetaMask.state.logs_issue22976.json)

0xedca037f2 (63.xxxxx) is found within~48 times

**Comment by plasmacorral** [comment]
Update: I have found tx's from my testing of 11.10.0RC that suggest this is not being introduced in 11.11.0 RC

https://sepolia.etherscan.io/tx/0x5206b9def33cbd32e189e06b6ef05f87002d705de17efe64b0b007a33ed24383 from https://sepolia.etherscan.io/block/5233955 9 days 2 hrs ago (Feb-06-2024 06:40:24 PM +UTC) ~40 GWEI

https://sepolia.etherscan.io/tx/0xa5d19b5c2a9a594e3c497e0919456ca3a1728ce31a2d9d041e3a02742cce87a2 from https://sepolia.etherscan.io/block/5233958  9 days 2 hrs ago (Feb-06-2024 06:41:00 PM +UTC) ~37 GWEI

https://sepolia.etherscan.io/tx/0xb73476ea214fc517c20d759449fbe482711be72a8a86170b0a266f81de5f745f from https://sepolia.etherscan.io/block/5233966 9 days 2 hrs ago (Feb-06-2024 06:43:00 PM +UTC) ~30 GWEI

https://sepolia.etherscan.io/tx/0xd38fe80de47eadb64994bb7a1bd84b840c0df19e17f02dc4913d396d95535b18 from https://sepolia.etherscan.io/block/5233966 9 days 2 hrs ago (Feb-06-2024 06:43:00 PM +UTC) ~30 GWEI

https://sepolia.etherscan.io/tx/0xb73476ea214fc517c20d759449fbe482711be72a8a86170b0a266f81de5f745f from https://sepolia.etherscan.io/block/5233966 9 days 2 hrs ago (Feb-06-2024 06:43:00 PM +UTC) ~30 GWEI

**Comment by sleepytanya** [comment]
Confirming Mike's comment above^^ that issue was not introduced with RC11.11.0.
Here are two consecutive transaction with the same Max gas of 75.360601676 GWEI and they were made 21 days 17 hours ago:
https://sepolia.etherscan.io/tx/0xf56100a1f4d66f12245ac6736d4cd9f27a51102110078f9719becc1538712965
https://sepolia.etherscan.io/tx/0x9b0b1a292d3c2d9fc2e0ef17221af5a3aeb70c734ab13545cde5e3d4ee6afab7
Assuming that slack thread for RC 11.10.0 was started 20 days ago, at the moment I was probably testing older MM version.

**Comment by sleepytanya** [comment]
For this [Account](https://sepolia.etherscan.io/address/0xA24B5c474dF517b083811b099054D670Ba696C7a) transactions with 'saved' Max gas value started [here](https://sepolia.etherscan.io/tx/0xf56100a1f4d66f12245ac6736d4cd9f27a51102110078f9719becc1538712965)  21 days ago and stopped [here](https://sepolia.etherscan.io/tx/0x905c0e629c55492f38d3bfb74b47cd4e068bfbaa82873d359d4afce766ca9ce7) 2 days ago

**Comment by plasmacorral** [comment]
Retested the same series of [sends tx's](https://sepolia.etherscan.io/address/0x5d930ae342573cb23f761d4a53924bf3c9a46c64) like what was in the initial report and the 11.10.0 RC testing after an adjustment to cloudflare configs as discussed in [slack](https://consensys.slack.com/archives/GTQAGKY5V/p1708009998733439).  

Values are now returned to being cached for only 12s.  I have not produced any tx showing the same values, although that may be possible if conducted within the 12s cache period.  Am satisfied with the changes and retests, so will close this issue.
