### ISSUE TITLE
[Bug]: After adding a custom network I am unable to see the tokens in the imported wallet

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#22992]
### Describe the bug

It used be able to add Tenderly as a customer network and import the tokens in the account. But that no longer works and because of that I am able to test the extension using Tenderly and to merge my e2e tests. This functionality was broken by the following PR https://github.com/MetaMask/metamask-extension/pull/22814
See the screen recording that shows the problem before and after the PR was merged

### Expected behavior

 I am able to import the tokens in the wallet when using a custom network

### Screenshots/Recordings

Before:

https://github.com/MetaMask/metamask-extension/assets/6082863/ac627c6b-c68b-4c78-9866-7aa455e97a1f

After:

https://github.com/MetaMask/metamask-extension/assets/6082863/7b62026d-0453-40db-aa3e-1c771967042d

### Steps to reproduce

1. Create a new account in the extension
2. Import a wallet using this seed phrase `buzz pill embody elite name festival crystal pigeon grief memory allow blue`
3. After the account is imported add a custom network:
    name: 'Tenderly',
    url: 'https://rpc.tenderly.co/fork/c2e7fb02-9c2e-40ee-b911-ebf5b0326f96',
    chainID: '1',
    symbol: 'ETH',
4. After switching the network to Tenderly click on the `Refresh list` button
5. Notice that the tokens in the account cannot be imported
   

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
@davibroc this has a label "regression-prod-11.8.0". Does that mean you can reproduce this in production? Or only on our `develop` branch?

**Comment by bergeron** [comment]
Since the linked PR was checked in a few days ago this should not be in 11.8 or any release yet.  I did attempt a fix here, which worked for me locally and I think makes sense: https://github.com/MetaMask/core/pull/3927

**Comment by davibroc** [comment]
> @davibroc this has a label "regression-prod-11.8.0". Does that mean you can reproduce this in production? Or only on our `develop` branch?

Yes my fault. Only happens on `develop`. I have removed it
