### ISSUE TITLE
[Bug]: PPOM - Background errors: `Cannot assign to read only property version of object`, `Failed to execute 'digest' on 'SubtleCrypto':` from ppom-controller

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#22991]
### Describe the bug

**Problem:** whenever I cleared the storage, switch to Sepolia and switch back to Ethereum mainnet I got the following errors:

- `Error in reading file: Failed to execute 'digest' on 'SubtleCrypto': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'.` in metamask-controlller
- `Error in writing file: Cannot assign to read only property 'version' of object '[object Object]' in metamask-controlller
- `Cannot assign to read only property version of object` in `develop` previous to the ppom update change

The functionality seems to be preserved, and malicious warnings continue to be displayed

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/cca53c15-961d-4259-a6e1-11dc4bc19fcd

### Steps to reproduce
1. Open the background console and the Application tab
2. Select mainnet
3. Clear the site data
4. Switch to Goerli
5. Switch back to mainnet
6. See background errors

### Version

It's present in prod 11.9.4 but may be earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
I also encountered this in a different scenario


https://github.com/MetaMask/metamask-extension/assets/54408225/7ef6ac51-d0c9-4238-af98-b9a00031ce23

**Comment by jpuri** [comment]
The issue seems to be pretty old, I could not replicate in the latest code.
