### ISSUE TITLE
No Network change event from Chrome plugin

### ISSUE THREAD

**Issue by DaneWiid1** [MetaMask/metamask-extension#2300]
In previous versions, web3 was re-injected after an account or network change. My dapp polled the web3 data to detect network changes. This seems to have disappeared now. Is that intentional, and if so is there any event to indicate network status changes to the dapp ?

**Comment by TripleSpeeder** [comment]
I hope it's not intentional. I really liked this functionality.

**Comment by tmashuang** [comment]
Closing, should have been fixed in master. Will reopen if the issue persists.
