### ISSUE TITLE
Firefox: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by DaneWiid1** [MetaMask/metamask-extension#2301]
I'm getting error in Firefox: NetworkError when attempting to fetch resource in version 3.10.8. Stack trace attached. There is no error when running the same dapp with V3.7.8
[stacktrace.txt](https://github.com/MetaMask/metamask-extension/files/1362428/stacktrace.txt)

**Comment by tmashuang** [comment]
This should have been fixed in v3.10.9. When we added Firefox CORS preflight in #2138. Please update your Metamask addon in Firefox through the gear icon in your addon's list. Please comment if this is still an issue.
