### ISSUE TITLE
[Bug]: Transaction function method name of replaced transaction remains even after being replaced by another transaction type

### ISSUE THREAD

**Issue by suspended** [MetaMask/metamask-extension#23038]
### Describe the bug

I sent a transaction with "Unstake" function method name. After that, I replaced it with another transaction (send USDC to another address) with higher gas fee but the same nonce, yet the "Unstake" method is still displayed even though it should be "Send USDC".

### Expected behavior

The replaced transaction should have an updated method name of the new transaction, not the replaced one.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/6438083/9dd5da91-b8fb-4644-b29f-e813b887e440)

### Steps to reproduce

1. Send transaction 1 (ie. Stake, Unstake, etc.) with low gas price so it won't be mined immediately.
2. Send transaction 2 with same nonce and higher gas price to replace transaction 1.
3. Transaction 2 will succeed but retain the function method name of transaction 1.

### Version

11.9.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by Bullcoiner** [comment]
Hi There! Thank you for reporting this, it has been assigned to the appropriate team to be looked at.

**Comment by seaona** [comment]
this relates to https://github.com/MetaMask/metamask-extension/issues/15632
