### ISSUE TITLE
Error: Transaction Underpriced

### ISSUE THREAD

**Issue by FedericoCapello** [MetaMask/metamask-extension#2303]
Hi, I tried everything possible but still i am incurring in this error, both when I create contracts and when I send ether to other accounts on the MainNet (on Ropsten it works):

The error is:

```
rpc error with payload
error: transaction underpriced
```
![screenshot from 2017-10-06 19-57-00](https://user-images.githubusercontent.com/10402300/31291610-a297aa98-aad0-11e7-9196-81f312f17c83.png)

What I've tried so far:

- Restarted Chrome
- Reinstalled Metamask after restarting the PC
- Used another ethereum account for creating the contracts/sending the transactions
- Logged into my accounts from another PC
- Switched wifis
- Switched back and forth from Ethereum Networks
- Maxed out on the gas limit

I'm desperate, what can I do? Thanks

**Comment by tmashuang** [comment]
@FedericoCapello please submit a support ticket with your transaction/state logs and your Metamask version to [https://support.metamask.io](https://support.metamask.io).

**Comment by rshuk** [comment]
@tmashuang I am facing similar issue and have already created a ticket (Ticket #MET00267336) on https://support.metamask.io.

Any help would be much appreciated.

**Comment by venkatsan13** [comment]
I am also facing same issue since morning, please help lot lot of money in gas tried multiple times.

**Comment by elie222** [comment]
Same issue here

**Comment by ryan-mulrooney** [comment]
Same here.

**Comment by elie222** [comment]
I got it working for me using a higher gas price. Try 32-45 for the gas
price and it should go through. The higher you pay the faster it will go
through, but 25 is too little right now.

There's also another issue that relates to this. You can run a geth client
locally to help potentially.

**Comment by escrowdis** [comment]
Same issue

**Comment by marisancans** [comment]
Same issue

**Comment by alexwagg** [comment]
Same issue here

**Comment by elie222** [comment]
If this is happening you need to set a higher gas price. Try 41 wei

**Comment by pranay0211** [comment]
I just restarted the chrome and it is working perfectly. By the time please also keep eye on etherscan as well.
