### ISSUE TITLE
This issue was closed because there has been no follow up activity in the last 45 days. If you feel this was closed in error, please reopen and provide evidence on the latest release of the extension. Thank you for your contributions.

### ISSUE THREAD

**Issue by Super-Genius** [MetaMask/metamask-extension#23035]
This issue was closed because there has been no follow up activity in the last 45 days. If you feel this was closed in error, please reopen and provide evidence on the latest release of the extension. Thank you for your contributions.

_Originally posted by @github-actions[bot] in https://github.com/MetaMask/metamask-extension/issues/20522#issuecomment-1912471320_

**Comment by Jaycat66** [comment]
https://github.com/MobileWalletProtocol/wallet-mobile-sdk/blob/edfd884b0eb8bce3b3e4dead67342e312d1f9546/android/README.md#:~:text=0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826
