### ISSUE TITLE
[Bug]: P0 - Import account through private key, i get two of identical account

### ISSUE THREAD

**Issue by iseekTo** [MetaMask/metamask-extension#23036]
## Version
- MacOS M1 Pro 13.5
- MetaMask 11.7.5

## What happened?
One day, I uninstall the Chrome Broswer,  for a while time later, i re-install the Chrome, so i should re-install MetaMask Extension, fortunately, i have private key on MetaMask Mobile App, I copy the private key and import to web MetaMask Extension, but i get the below case(see image

Other than that, I can't add a new account anymore(besides import method

<img width="407" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/33739877/2dde32e5-4f25-4c46-90f5-3a456b9fb666">

### Expected behavior

1. Remove the repeat account
2. Can add new account whenever

### Steps to reproduce

see the above desc

### Version

11.7.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Bullcoiner** [comment]
Hi There, Thank you for reporting this to us. It has been reported to a team and will be looked at.

**Comment by AlexJupiter** [comment]
@montelaidev have you been able to reproduce this?
