### ISSUE TITLE
[Bug]: Metamask does not import proxy token contracts 

### ISSUE THREAD

**Issue by Super-Genius** [MetaMask/metamask-extension#23034]
### Describe the bug

Some contracts implement ERC20 and ERC1155 Hybrid with EIP2535 diamond protocol. In that case, MetaMask should allow importing the ERC20 token.

https://polygonscan.com/token/0x127e47aba094a9a87d084a3a93732909ff031419

Metamask is the only Wallet that fails to import this hybrid token correctly.

Re-opening with a new issue, as it was closed. previously closed issue [https://github.com/MetaMask/metamask-extension/issues/20522](https://github.com/MetaMask/metamask-extension/issues/20522)

### Expected behavior

Metamask should allow the ERC-20 token to be imported.  There is no reason to block a hybrid contract that supports both ERC-20 and ERC-1155 contract

### Screenshots/Recordings

![Screen Shot 2024-02-17 at 1 53 14 PM](https://github.com/MetaMask/metamask-extension/assets/1320023/1d7109e4-3cb6-4412-abe7-8cf5dd021f40)

### Steps to reproduce

1, Add polygon network
2. import token 0x127e47aba094a9a87d084a3a93732909ff031419 (GNUS)

- OR -

1. Use Ethereum network 
2. import token 0x251FAe8f687545BDD462Ba4FCDd7581051740463 (WATER)

### Error messages or log output

```shell
Metamask shows an error. This token is an NFT. Add on the Import NFT page.
```

### Version

11.7.5

### Build type

None

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows, MacOS, Linux

### Hardware wallet

Ledger, Trezor, Keystone, GridPlus Lattice1, AirGap Vault, imToken

### Additional context

None

### Severity

Severe - Blocks user from seeing their tokens in the wallet and sending via MetaMask, as it doesn't support ERC-1155 transfers yet.  All other wallets support this.

**Comment by Bullcoiner** [comment]
Hi There! Thank you for reporting this, it has been assigned to the appropriate team to be looked at.

**Comment by Super-Genius** [comment]
Any update on this?  The last one went stale, so I'm going to keep adding comments so it won't automatically close.

**Comment by Super-Genius** [comment]
Once again, I'm adding a comment so this doesn't fall through the cracks, considering we filed this bug six months ago, and now many users are complaining. 

We're redirecting them to BitGet extension, Mobile TrustWallet, etc.  It works in your Mobile Metamask wallet, so I'm not sure why the extension is the only one that is is broken like this.

**Comment by Super-Genius** [comment]
Bump, so it doesn't get stale.  Is there any update on the timeframe to fix this?

**Comment by Super-Genius** [comment]
@Bullcoiner Willing to pay a bounty to fix this.

**Comment by danfodorean** [comment]
@Bullcoiner also having this issue and it's annoying as hell

**Comment by Super-Genius** [comment]
@davidmurdoch, anyone?  Willing to pay for it.

**Comment by jfayad** [comment]
Any update on this one ?
I'm facing the same issue on the extension and would happily see it fixed.

**Comment by Super-Genius** [comment]
3 weeks ago to fix this bug?  Now Metamask incorrectly tags https://www.gnus.ai as a phishing website?

Are you trying to take down my project on purpose?

**Comment by danfodorean** [comment]
Bump of interest :)

**Comment by hjetpoluru** [comment]
1, Add polygon network
2. import token 0x127e47aba094a9a87d084a3a93732909ff031419 (GNUS)

I was able to import this token could you please see the video attached https://github.com/user-attachments/assets/65efbdb6-1a13-4fc0-b429-10442538d424
