### ISSUE TITLE
Bottom Account cuts off "Pin to top" when trying to pin

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-extension#23040]
<img width="459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aff50d1c8ec3954943cfd160c54dcd14355811d4/image.png" alt="image.png" />

Ideal solution would be to extend the height of the tooltip. 

Edit: this also totally removes the ability to "Remove account" in this tooltip, which should also be fixed in this ticket. @eriknson also proposes a specific component [here in Slack](^ ideally the native dropdown ( <select>) should be used as it can be displayed outside of the container and is generally faster / smoother / more accessible).

**Comment by gantunesr** [comment]
Already fixed in https://github.com/MetaMask/metamask-extension/pull/22889
