### ISSUE TITLE
[Bug]: Multichain - Edit Send asset transaction by switching networks leads to multiple errors and MM loading indefinetly

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23041]
### Describe the bug

**Problem:** whenever I start a Send ERC20 flow and switch networks in the Amount transaction screen, I get the following errors and behaviours.
Note, even though this is happening with Send ERC20, not simple Send ETH flow, this errors are introduced with the multichain feature flag, since on the regular build it's not possible to switch networks once a transaction has been initiated.

This error immediately appears after switching networks:

`Error: [ethjs-rpc] rpc error with payload {"id":"373f91de-8e19-4b7f-a36f-f397534efd0f","jsonrpc":"2.0","params":[{"to":"0x0413f702fc9c535b0ca9490337e7d33fb95a50cd","data":"0x70a0823100000000000000000000000007be9763a718c0539017e2ab6fc42853b4aeeb6b"},"latest"],"method":"eth_call"} {"code":-32000,"message":"execution reverted"}`

Then there are 2 different behaviours:
#### Case 1: whenever I switch networks directly after adding the asset amount
 - this throws the warning ` failed to load balance for token at 0x0413F702fc9C535b0ca9490337e7d33FB95a50cd`
 - I still see the token symbol and amount I had for the previous network - this is not correct since in this new network, that address is not a contract/doesn't exist
 - it let's me proceed to the next screen
 - I see a Token Transfer screen
 - I see a token transfer screen with `undefined value` in the last confirmation screen
 - If then I try to Edit the transaction MetaMask stays loading indefinetly and I see the following error in the console `Error: Unable to determine contract standard at AssetsContractController.`

https://github.com/MetaMask/metamask-extension/assets/54408225/e175a268-f545-4ca6-98d2-976d14d267e4

#### Case 2: whenever I go to the last confirm screen, then go back and switch networks during the Edit screen
 - this doesn't allow me to proceed to the next screen
 - I see the additional error `TypeError: Cannot read properties of undefined (reading 'userEditedGasLimit')` when I click Next

https://github.com/MetaMask/metamask-extension/assets/54408225/2cc8a384-2a25-4d7b-820d-6420e0c56b4d

### Expected behavior

There are multiple specs to be defined here - I think it should also be discussed with confirmations team and @bschorchit , but my understanding is the following:
- whenever I switch networks after having added a token and amount***
*** there are few cases where token contract preserve their address within different networks. However we cannot assume this is always the case.

=============
**Case A: If the token address is not preserved in another network**
  - we should see the token symbol and amount cleared
  - we should also clear the hex data for that transaction behind the scene, otherwise the hex value is dragged to the next screen
  - when Continue, we should not see the Token Transfer screen - since that address is not the token address anymore for the new network and we've cleared the hex data. We should see the screen according to the new updated transaction

An alternative for this is, if you selected DAI on Mainnet and now switch to Polygon, we preserve the DAI token, but now it points to another address, since in Polygon the DAI contract is in `0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063` and in mainnet is `0x6B175474E89094C44Da98b954EedeAC495271d0F`. However, this approach will add complexity to the code and to the users. :thinking: 

**Case B: If the token address is the same for the other network:** 
- Should we save the token symbol and amount that the user inputed? However, we need to check that the token is the same and cannot be assumed beforehand.
- when Continue, we should the Token Transfer screen with the token amount chosen

Note: I think adding this second case can add a bit more complexity, so unless this is needed for multichain (seamless network switch experience) we could opt for case A always - no matter if the token address is the same

=============

### Screenshots/Recordings

Above

### Steps to reproduce

**Case 1:**
1. Deploy an ERC20 asset
2. Click Send ERC20
3. Add recipient
4. Add amount
5. Switch networks -- see errors in the background console and token amount and symbol remain the same
6. Proceed to the next screen -- see we are in the Token Transfer screen, however here it should be a fallback screen since that token address doesn't exist in the new network
7. Click Edit -- see MM stays loading indefinetly and we get the error in the background console

**Case 2:**
1. Deploy an ERC20 asset
2. Click Send ERC20
3. Add recipient
4. Add amount
5. Proceed to the last confirmation screen
6. Click Edit
7. Change networks -- see background errors
8. Click Continue -- see you cannot proceed to the next screen

**Case 3:**
Same as 2, but the Send ERC20 flow is initiated from a dapp

### Version

develop - with multichain flag

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
As info, this was shared in the multichain channel to get feedback from product on what should be the expectations:

https://consensys.slack.com/archives/C04M4QU03MG/p1709229675959739?thread_ts=1709214462.454779&cid=C04M4QU03MG

**Comment by hesterbruikman** [comment]
Close as network picker will be removed. Included to address in new designs in this [spreadsheet](https://docs.google.com/spreadsheets/d/1HsXWIUqShWSpVQ1x8ZoN5K47k9jT94hc-vzZZgmxSyE/edit#gid=0)
