### ISSUE TITLE
[Bug]: Cannot connect to the test dapp with any account: `Received unrecognized address` after adding a Trezor and then a Ledger account

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23065]
### Describe the bug

**Problem:** I cannot connect to the test dapp with any account. The trigger for this behaviour was adding a Trezor account, then removing it and subsequently adding a Ledger account. After that, I tried to connect to the test dapp with the Ledger account and it was not possible. Switching to MM accounts and trying to connect was then also not possible.
Disabling and Enabling the wallet doesn't fix it.

### Expected behavior

We should be able to connect to dapps

### Screenshots/Recordings

![Screenshot from 2024-02-20 11-56-21](https://github.com/MetaMask/metamask-extension/assets/54408225/5b9103e1-3494-46e9-8d2e-3a5b59dd26d6)

https://github.com/MetaMask/metamask-extension/assets/54408225/bd8f3ed1-aca1-4cab-8289-72be30293f2c

https://github.com/MetaMask/metamask-extension/assets/54408225/43292533-9156-45d6-bc11-a3950b7ee123

### Steps to reproduce

1. Import a Trezor account
2. Connect to the test dapp
3. Change account
4. Hide Trezor account
5. Import a Ledger account --> saw an `iframe error` and had to refresh the wallet
6. Now import it
7. Go to the test dapp
8. Try to connect
9. Nothing happens
10. Open the popup
11. See Ui and background errors
12. Switch accounts for a MM internal account
13. Try to connect
14. See background error -> nothing happens

Video a bit long, but with full steps

https://github.com/MetaMask/metamask-extension/assets/54408225/4295829f-b8f4-44a3-8dcd-723f2a570a62

### Version

seen in 11.9.5 prod - not sure when this was first introduced

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Bullcoiner** [comment]
Hi There! Thank you for reporting this, it has been assigned to the appropriate team to be looked at.
