### ISSUE TITLE
[Bug]: Cannot Hide the last account from the popup view (modal is cut)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23066]
### Describe the bug

**Problem:** whenever I try to hide the last account from the popup view, I see it's not possible since the modal is cut and cannot scroll neither.

### Expected behavior

I should be able to hide the last account from the popup

### Screenshots/Recordings

![Screenshot from 2024-02-20 12-18-56](https://github.com/MetaMask/metamask-extension/assets/54408225/67451a45-4f41-41c8-9b0a-66b1da4c6b54)

https://github.com/MetaMask/metamask-extension/assets/54408225/a24affeb-5ef9-4c58-8ee2-fd7444c2b19a

### Steps to reproduce

1. Add several accounts
2. Open the popup view
3. Try to Hide the last account
4. See modal is cut

### Version

11.9.5 but maybe introduced earlier

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Bullcoiner** [comment]
Hi There! Thank you for reporting this, it has been assigned to the appropriate team to be looked at.
