### ISSUE TITLE
[Bug]: Bad formatting when importing a token

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#23079]
### Describe the bug

Text and token symbol are pushed to the left side of the pop-up screen. 

### Expected behavior

Text and symbol are correctly aligned on page.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/120041701/d956190f-cb6f-4ad2-b364-26567ea8148d)

### Steps to reproduce

1. Login to MetaMask
2. Select a test network (e.g. Sepolia)
3. Head over to the test dapp: https://metamask.github.io/test-dapp/
4. Connect wuth current account
5. Create token
6. Add tokens to wallet
7. Notice the elements dragged to the left

### Version

11.11.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by seaona** [comment]
I think this is the same as those:
- https://github.com/MetaMask/metamask-extension/issues/22952
- https://github.com/MetaMask/metamask-extension/issues/22906

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/22952
