### ISSUE TITLE
[Bug]: Aurora Deprecation Message is Unclear and Annoying

### ISSUE THREAD

**Issue by Karkunow** [MetaMask/metamask-extension#23078]
### Describe the bug

I am constantly getting the Aurora deprecation message, added via [this PR](https://github.com/MetaMask/metamask-extension/pull/21933). 

Which is misleading, as there is no planned deprecation of the Aurora network by Metamask in the foreseeable future.
It also ruins the user experience and makes people worry about using Aurora products with Metamask.

### Expected behavior

I have a few suggestions about how to fix it:

1. The message inside the popup is misleading. It says, "Aurora network will be deprecated," which simply is not true. In PR devs are just saying about the removal from Popular Network List. So, let's change it to something else, like "Aurora Chain has been removed from the Popular Network List".

2. The second part of the message says, "Please add it as a custom network". But if I add it as custom network - I still see the message. How can I get rid of this then? 

3. It is also not clear how to add a Custom Network from that popup. In "Learn More" you just have a redirect to the aurora.dev site. I propose to change it to either https://aurora.dev/start or even better - https://support.metamask.io/hc/en-us/articles/360058992772-Add-a-network-using-Chainlist 

4. Allow the user not to see that message if he has closed it or has done the action you've asked him for.

### Screenshots/Recordings

It looks like this:
<img width="360" alt="Screenshot 2024-02-20 at 15 23 02" src="https://github.com/MetaMask/metamask-extension/assets/2808283/52fdeecd-1895-4a34-a2aa-751e1869c65b">

### Steps to reproduce

1. Make sure you have added Aurora Mainnet (https://aurora.dev/start) and Ethereum Mainnet networks.
2. Switch to Ethereum Network.
3. Switch to Aurora Network.
4. See popup at the bottom of the screen.

### Version

11.9.5

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Severity

- It is a mid-severe bug for the Aurora Users and impacts the whole ecosystem

**Comment by Bullcoiner** [comment]
Hi There! Thank you for reporting this, it has been assigned to the appropriate team to be looked at.

**Comment by Karkunow** [comment]
@Bullcoiner looking forward to it and a person assigned directly to this issue here.

**Comment by evienear** [comment]
I am from a project on Aurora and our community has been extremely confused by this message. The misleading message has been a huge turn off for new users thinking something is wrong with the chain. I support this post.

**Comment by bravepooh** [comment]
Working on a project on Aurora, I've found  this deprecation posted message and started to get questions from users about it. It caused some uncertainty. Hope it can be resolved

**Comment by Karkunow** [comment]
@Bullcoiner could you please push this issue on your side? Thank you!

**Comment by armanddid** [comment]
@Bullcoiner any update on this issue? This has been extremely misleading for our users. Appreciate your time in solving this!

**Comment by tuanhvdev** [comment]
@Bullcoiner I'm working on a project on Aurora chain.
Our community is very confused by this message and asking us about it. It's very misleading to our users, especially new users.
I hope it can be resolved soon. Thanks

**Comment by Karkunow** [comment]
@NidhiKJha, Hello! I see you have been working on this. Could you please explain why this warning exists? 
Aurora Mainnet is fully functional and working. It shouldn't be deprecated.

**Comment by Karkunow** [comment]
@pedronfigueiredo, hello! I see that you've been working on Add loading message to deprecated networks (https://github.com/MetaMask/metamask-extension/pull/22323) PR, could you please comment on why Aurora network was included into the Deprecation List? Thank you!

**Comment by Karkunow** [comment]
@pedronfigueiredo @gauthierpetetin @NidhiKJha Hello! Can someone clarify this one? And push the issue forward to be solved? Thank you!

**Comment by Karkunow** [comment]
@bergeron Hey! Could you please provide any updates about this one? Thank you!

**Comment by CosmicVentus** [comment]
Had this message for a while and I can assure that this is a huge turn off. Imagine staking your tokens when your metamask didn't show this bug and now you need to unstake them and you see that message. Would look super risky to remove your staked token to redeem them in a wallet with a faulty network. Please consider fixing this.

p.s. Thankfully the Aurora support team is always available to help.
