### ISSUE TITLE
[Bug]: Signatures - Triggering a signature with a QR based wallet closes the popup for the first time and leaves popup opened after signed

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23074]
### Describe the bug

**Problem:** there are a couple of strange behaviours related to the MM popup when using Signatures with QR based account.

1. Whenever I trigger a Signature and click Sign, the popup is closed and I need to click again Sign to be able to see the QR code to scan (I don't see the signature data, but the QR code directly)

2. After signing a signature with a QR based wallet, we see how the popup with the Signature remains open. However the Signature was completed and I can see the signature hash and validate it in the test dapp

### Expected behavior
1. I should see first the signature data, and when clicking Sign, the QR code for scanning
2. Once the signature is sign the popup should be closed

### Screenshots/Recordings

popup remains open after signing

https://github.com/MetaMask/metamask-extension/assets/54408225/6648a208-58de-491e-8158-d05ca32a042d

first signature triggered closes the popup when clicking Sign

https://github.com/MetaMask/metamask-extension/assets/54408225/49c957c7-696e-4f94-976b-1f1fae6685f8

### Steps to reproduce

1. Add a QRbased account
3. Go to the test dapp
4. Connect Account
5. Click Sign
6. Sign
7. Scan QR code with the wallet
8. Click Get Signature
9. Scan signature
10. See how the result signature is already in the test dapp, but the popup remains open

### Version

11.9.5 but maybe introduced earlier

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Bullcoiner** [comment]
Hi There! Thank you for reporting this, it has been assigned to the appropriate team to be looked at.

**Comment by vinistevam** [comment]
Not able to reproduce the issue.

https://github.com/user-attachments/assets/538469b2-5644-47e0-935d-312ba2049f34

**Comment by seaona** [comment]
I've just tried production 12.4 and I confirm this issue is not present anymore. Both with signature re-design on and off, the issue seems to be fixed
