### ISSUE TITLE
[Bug]: ENS is displayed as an address in the last confirmation screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23072]
### Describe the bug

**Problem:** it seems that after the introduction of Petnames, we don't display anymore the ens domain in the last confirmation screen, for recipients which were entered as ENS domains

### Expected behavior

We should see the ENS instead of the address like we used to, if the recipient is added as an ENS? cc @bschorchit 

### Screenshots/Recordings

left side: current view without ENS recipient
right side: previous view with ENS reicipient
![Screenshot from 2024-02-20 15-01-38](https://github.com/MetaMask/metamask-extension/assets/54408225/c1096c83-26a8-4a80-b8a8-c5cadcdc4105)

https://github.com/MetaMask/metamask-extension/assets/54408225/29865797-85ce-4732-886a-921a05cd01b2

### Steps to reproduce

1. Select Mainnet
2. Click Send
3. Add an ENS recipient ie `vitalik.eth`
4. Proceed to the next screen
5. See ENS is displayed as an address

### Version

11.11.0 

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Closing as this is now fixed on the redesigned confirmations and we're making them default with extension v12.9

![Image](https://github.com/user-attachments/assets/478be751-9262-4b3c-8e62-e51f6c959a26)
