### ISSUE TITLE
[Bug]: When there are multiple account, the delete key for the last account cannot be found

### ISSUE THREAD

**Issue by junjie9021** [MetaMask/metamask-extension#23083]
### Describe the bug

When there are multiple account, the delete key for the last account cannot be found
<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/71370818/5bc305a1-24ec-4c77-bb5f-5536813931ae">

### Steps to reproduce

pls check `Describe the bug`

### Version

11.10.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Hi @junjie9021 , when you say "the delete key for the last account cannot be found", do you mean you can find the delete key for other accounts? (other than the last one)

**Comment by plasmacorral** [comment]
This is a duplicate of https://github.com/MetaMask/metamask-extension/issues/22836.  The [fix](https://github.com/MetaMask/metamask-extension/pull/22889) is merged to develop and expected in upcoming release 11.12.0
