### ISSUE TITLE
[Bug]: PPOM - Storage jump of `12 MB` after switching to BNB chain

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23109]
### Describe the bug

**Problem:** when switching to Binance Chain, the storage jump was 12 MB causing the total storage to be 30.5 MB in that occasion.
Despite this is not happening always, I experienced this 2 times already.

### Expected behavior

BNB files should take around  ~3MB

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/62485ec6-ba3f-4446-a7cb-16b0398103da

https://github.com/MetaMask/metamask-extension/assets/54408225/4f90ab17-3026-489d-b26a-530c348f2ffb

### Steps to reproduce

1. Open application inspector
2. Switch to BNB chain
3. See how much is the storage increase

### Version

11.10.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
I am not able to replicate this, also there is change in how blockaid files are downloaded since this task was created. Hence closing this.
