### ISSUE TITLE
[Bug]: An error occurs when I try to connect hardware wallet account to Dapps

### ISSUE THREAD

**Issue by Takayuki-Suzuki** [MetaMask/metamask-extension#23110]
### Describe the bug

Can't connect to the hardware wallet account due to an error

### Expected behavior

It should be successfully connecting to the Dapp

### Screenshots/Recordings

<img width="327" alt="スクリーンショット 2024-02-22 17 17 40" src="https://github.com/MetaMask/metamask-extension/assets/3956234/4cbf36c1-7e8c-49b3-bd7b-935394ad81a8">

### Steps to reproduce

1. Import an account A from Trezor hidden wallet A.
2. Connecting to a Dapp with account A.
3. Forget the device.
4. Import an account B from Trezor hidden wallet B.
5. Connecting to a Dapp with account B.

After 5, it shows an error saying "Something went wrong"

### Error messages or log output

<img width="1025" alt="スクリーンショット 2024-02-22 17 12 16" src="https://github.com/MetaMask/metamask-extension/assets/3956234/2a13857a-d2e3-4ece-91e1-0e3785e0bb53">

### Version

11.7.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

### Additional context

"Unrecognized address" in the error message is pointing to the address of account A

**Comment by Bullcoiner** [comment]
Hi There, Thank you for reporting this to us. It has been reported to a team and will be looked at.
