### ISSUE TITLE
[Bug]: Multichain - When editing a transaction, clicking Continue does nothing and I remain in the Edit page

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23114]
### Describe the bug

**Problem:** whenever I start a transaction and I land into the last confirmation screen, if I click Edit I am able to change the network. However, if I change the network I am not able to proceed to the next screen, clicking Continue does nothing and I see the following error in the UI `TypeError: Cannot read properties of undefined (reading 'userEditedGasLimit')`

### Expected behavior

Clicking Continue should land me to the last confirmation screen with the updated network?
Or, if we don't want the user to change networks when editing a transaction, the network switch should then be disabled.

cc @hesterbruikman @bschorchit not sure which is the expectation here

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/8629950b-e799-4524-8d32-812eb5b5d167

### Steps to reproduce

1. Start a transaction
2. Add recipient and amount
3. Click Continue
4. On the last confirmation screen, click Edit
5. Change networks
6. Click Continue
7. See nothing happens and a console error appears

### Version

develop - with multichain flag

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Bullcoiner** [comment]
Hi There, Thank you for reporting this to us. It has been reported to a team and will be looked at.

**Comment by darkwing** [comment]
Seeing this error in the console:

```
SES_UNHANDLED_REJECTION: TypeError: Cannot read properties of undefined (reading 'userEditedGasLimit')
  at send.js:2330:26
```

After changing networks, `unapprovedTxs` becomes an empty object so `unapprovedTx` is `undefined`.  The error is triggered by:

```
gas: unapprovedTx.userEditedGasLimit
          ? unapprovedTx.txParams.gas
          : txParams.gas
``

`draftTransaction` *does* exist so changing teh network is somehow clearing `unapprovedTxs`.

<img width="1114" alt="SCR-20240222-ttht" src="https://github.com/MetaMask/metamask-extension/assets/46655/5c538f3e-c66c-48c5-8e8a-7d5f2da8b242">

Continuously editing the transaction *without changing network* works properly, so this issue is specific to changing networks.
