### ISSUE TITLE
Metamask in portuguese asks for start transactions (iniciar transações) while english asks for suggest transactions to aproove 

### ISSUE THREAD

**Issue by frcd10** [MetaMask/metamask-extension#23121]
### Describe the bug

When connecting a wallet to a Dapp like uniswapv3 when I connect with my metamask in English it asks me to "see address, account balance, activity and SUGGEST TRANSATIONS TO APPROVE" while if I use portuguese is asks for "Ver endereço, saldo da conta, atividade e INICIAR TRANSAÇÕES."
I have been receiveing much questions about it from my friends who does not know crypto that thinks that they are beeing scammed because the wallet is asking them permission to START transactions.

### Expected behavior

The correct would be changing INICIAR TRANSAÇÕES to SUGERIR TRANSAÇÕES PARA APROVAÇÃO

### Screenshots/Recordings

![Metamask portuguese](https://github.com/MetaMask/metamask-extension/assets/117095751/1dee7ce6-0931-4d27-940d-c997d5a4c226)
![Metamask english](https://github.com/MetaMask/metamask-extension/assets/117095751/2f8aea03-0efc-47ec-9866-a337690407d9)

### Steps to reproduce

1 [Go to uniswap V3]
2 [select portuguese]
3 [click on connect wallet]

### Version

11.9.5

### Build type

None

### Browser

Chrome, Firefox, Brave

### Operating system

Windows

### Additional context

That's impacting users to have a smooth experience on metamask, as mainly if they are new users, they stop interaction or just go to another wallet that does not ask them for permission to START transactions instead of permission to suggest transatcion to approve

### Severity

That's impacting users to have a smooth experience on metamask, as mainly if they are new users, they stop interaction or just go to another wallet that does not ask them for permission to START transactions instead of permission to suggest transatcion to approvea

**Comment by Bullcoiner** [comment]
Hi There, Thank you for reporting this to us. It has been reported to a team and will be looked at.
