### ISSUE TITLE
Confirmation re-design: add account info modal

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#23124]
Add account info modal to confirmation page header:

<img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77884a77d3e5929512c47e3cb4a099a13746ceeb/Screenshot%202024-02-22%20at%206.38.07%E2%80%AFPM.png" alt="Screenshot 2024-02-22 at 6.38.07 PM.png" />

**Comment by seaona** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23124?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @segun

**Comment by seaona** [comment]
This task scope is to add the icon and the modal.
The below points are to be develop in separate task:

- variant of the address with a copy icon and func 
- currency component is also missing and will go into a separate ticket: which will display native token or fiat, depending on user preferences

Status: we wait for design feedback for estimating

**Comment by segun** [comment]
Duplicate
