### ISSUE TITLE
Question: what's the factor that makes a MetaMask tx confirmation window popup time fast/slow?

### ISSUE THREAD

**Issue by macbem** [MetaMask/metamask-extension#2313]
At times, you might wait up to a few minutes for the MetaMask tx confirmation window (the one that's opened for you when you use `sendTransaction`, where you can tweak the gas limit / gas price and accept/reject the tx) - sometimes it's almost instant though.

What's the reason for the difference here? Can we optimize it in our Dapps or is it entirely on the MetaMask / Ethereum network / Infura side? Maybe the popup should open instantly with a loader?

I'm asking about this, because it's a bit of an UX issue when users don't get any feedback for a long while after triggering a tx. For now, I handle this in my UI, but I'm wondering why isn't this handled in the extension itself.

**Comment by kumavis** [comment]
primarily gasLimit calculation

**Comment by kumavis** [comment]
we can refactor to pop up the dialog first before calculating the gasLimit

**Comment by kumavis** [comment]
@macbem how long times are you seeing between tx trigger and pop up?

**Comment by macbem** [comment]
The most I've seen was probably 3-5 minutes. I've noticed this on the EtherDelta contract (the newest one). As I've said, sometimes it's nearly instant, but usually it'd take up to a few minutes.

What's interesting is that when you call `estimateGas` before a tx, it almost always takes a long time to open the tx confirmation popup, but I've seen such long popup times even without calling `estimateGas` beforehand.

**Comment by macbem** [comment]
Forgot to mention - it was on the main network, calling `order` / `trade` functions from the EtherDelta contract for example.

**Comment by kumavis** [comment]
infura was experiencing higher than normal latency on `estimateGas` calls, they increased scaling

we'll also move the calculation to after the add per #2142
