### ISSUE TITLE
[Bug]: 'Next' button on the confirmation screen is unavailable when attempting to put first-party contract as recipient address. 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23138]
### Describe the bug

Trying to perform 'send' flow using first-party contract address as a recipient results in unresponsive 'Next' button on the Confirmation modal.

If I remove the address and add the same address again "Next' button becomes responsive and transaction can be successfully submitted.
'Send Eth' works as expected with regular address (0x76F07dc010801B675C3E843E15b81BD98bFA8e44) as a recipient.
Bug was first noticed in this [PR](https://github.com/MetaMask/metamask-extension/pull/23092#pullrequestreview-1897050219) but it also exists on develop and production.

### Expected behavior

'Next' button should be available and user should be able to submit transaction.

### Screenshots/Recordings

Development build from git id: 9a782e16, Chrome (same behavior on Firefox):

https://github.com/MetaMask/metamask-extension/assets/104780023/7d92823e-e5cc-4281-8e7b-8a22f7f7538b

### Steps to reproduce

1. Set the current chain to mainnet
2. Start a send transaction from the extension wallet
3. Put 0x0439e60F02a8900a951603950d8D4527f400C3f1 as the recipient
4. Notice "Next" button is unavailable

### Error messages or log output

No error messages in the background console.

### Version

develop, MM 11.7.5 (Firefox)

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by seaona** [comment]
I think what happens here might be the same/similar as:
https://github.com/MetaMask/metamask-extension/issues/21867

**Comment by sleepytanya** [comment]
@bschorchit @mariona also pointed this issue looking similar https://github.com/MetaMask/metamask-extension/issues/22219

**Comment by sleepytanya** [comment]
Closing as two similar issues https://github.com/MetaMask/metamask-extension/issues/22219 https://github.com/MetaMask/metamask-extension/issues/21867 already exist.
