### ISSUE TITLE
[Bug]: Cannot switch networks on Firefox

### ISSUE THREAD

**Issue by rac-sri** [MetaMask/metamask-extension#23132]
### Describe the bug

I switched to an RPC endpoint which now doesn't exist, now when I try to change the network the extension breaks. This happens even when metamask says that it cannot connect to the RPC so switch network, but clicking on it breaks it.

### Expected behavior

The network switch window to open up.

### Screenshots/Recordings

![Screenshot 2024-02-23 at 1 57 37 AM](https://github.com/MetaMask/metamask-extension/assets/43861614/9789982d-7109-4fb0-aefc-e7d998e5f72f)

### Steps to reproduce

1. Install metamask extension on Firefox
2. Connect to an rpc that doesn't exist anymore.
3. Wait for metamask to connect. Now try switching the network.

### Error messages or log output

```shell
Message: O is undefined

    Code: TypeError
    Stack:

    x/R/<@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-5.js:1:73069
    R@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-5.js:1:72994
    x@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-5.js:1:74847
    va@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:60111
    Mu@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:105038
    As@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:90903
    Rs@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:90826
    xs@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:88166
    ti/<@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:46516
    n.unstable_runWithPriority@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:491157
    Qo@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:46225
    ti@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:46463
    ei@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:46396
    ue@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:115076
    jn@moz-extension://db04e2af-9dcb-49e4-a50e-c8d45a8b424e/ui-1.js:1:29860
```

### Version

11.7.5

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by Bullcoiner** [comment]
Hi There, Thank you for reporting this to us. It has been reported to a team and will be looked at.

**Comment by alanwu4321** [comment]
+1 👍🏻
