### ISSUE TITLE
[Bug]: Chrome Store version 11.10.0, keeps loading forever when you open it

### ISSUE THREAD

**Issue by MiniSuperDev** [MetaMask/metamask-extension#23141]
### Describe the bug

When you open metamask it stays loading forever

It happened to me on several computers, and I saw the ratings in the chrome store and apparently I'm not the only one

It happens on several computers, the error appears on several, but in the ones that appear, it never worked again, that is, it always stays loading forever every time it is opened

Of course, they all have version 11.10.0

it stays like this:

![image](https://github.com/MetaMask/metamask-extension/assets/105388540/f829141f-66a8-4286-84e2-c2cb3192e253)

and in the extension console you see this:
![image](https://github.com/MetaMask/metamask-extension/assets/105388540/abb89460-ced8-4578-acee-92cf38b16709)

Other users have the same error:

![image](https://github.com/MetaMask/metamask-extension/assets/105388540/a84e585f-fc94-4932-8baa-e430f3fe69cd)

### Steps to reproduce

1. Open metamask 11.10.0
2. It will keep loading forever

### Version

11.10.0

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by Bullcoiner** [comment]
Hi There, Thank you for reporting this to us. It has been reported to a team and will be looked at.

**Comment by danjm** [comment]
@MiniSuperDev can you go to chrome://extensions/?id=nkbihfbeogaeaoehlefnkodbefgpgknn and take a screenshot of the metamask description, version and size?

Also, what version of Brave are you using?

**Comment by MiniSuperDev** [comment]
@danjm Thanks
![image](https://github.com/MetaMask/metamask-extension/assets/105388540/c6bfabf2-c32c-4d63-a776-ca3e25148b06)
![image](https://github.com/MetaMask/metamask-extension/assets/105388540/6b16ef47-687e-4c4f-96a3-84000b485277)

I checked and the ones that were damaged had versions 11.7.0, 11.7.2 and 11.7.3

They were fixed by updating manually and work fine in version 11.10.0
![image](https://github.com/MetaMask/metamask-extension/assets/105388540/00ad74a8-1963-432d-9897-4c0ce94a5566)

Those that worked previously, I reviewed them and they had versions equal to or greater than 11.0.5.

For now everything is fine after updating manually, strange that those are not updated automatically and will be stuck loading

**Comment by danjm** [comment]
@MiniSuperDev thanks for the information. There is a known incompatibility between MetaMask versions below v11.7.5 and chromium versions v122 and higher.

That incompatibility is fixed in MetaMask 11.7.5. Like the problem you saw started occuring after a Brave update, and then the problem was fixed when you manually updated MetaMask.
