### ISSUE TITLE
Confirmation redesign - create various variants of address value component

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#23158]
Address component has multiple variants at different places. We need to discuss with design team and add support for all of these. We need the one with copy icon as in image below for account modal:

<img width="338" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL21HQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa31b3da5cb6c9ee6f717e2e28bbd8b8dbfaebeb/Screenshot%202024-02-23%20at%209.56.56%E2%80%AFPM.png" alt="Screenshot 2024-02-23 at 9.56.56 PM.png" />

https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=1670-10408&mode=design&t=vRW9fK7sygPSzi2s-0

https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=907-23977&mode=design&t=rRvawNcgeQmtaTHm-0

**Comment by blackdevelopa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23158?planning-poker) with Zenhub @segun @digiwand @jpuri

**Comment by SayaGT** [comment]
Hello please refer to the following updated design using the petname component. 
[Figma link depicting all address variants](https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=775%3A28145&mode=design&t=aqquutShpVRX5yyG-1)
[Figma link](https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=907%3A23977&mode=design&t=aqquutShpVRX5yyG-1)
<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33db4490b278d3be908aadfff386aacfb4b54a0e/Screenshot%202024-03-13%20at%2015.48.03.png" alt="Screenshot 2024-03-13 at 15.48.03.png" />
