### ISSUE TITLE
Transaction popup takes too long, estimates gas to be 0

### ISSUE THREAD

**Issue by mbeylin** [MetaMask/metamask-extension#2315]
Submitting transactions through metamask (on main net) frequently causing long delays, before finally launching the popup with a gas estimate of 0 (even on simple sends, as shown below).
<img width="363" alt="screen shot 2017-10-10 at 1 04 43 pm" src="https://user-images.githubusercontent.com/6082639/31400207-bdd79752-adbc-11e7-8f40-acb2289e3aae.png">

**Comment by macbem** [comment]
I've encountered this issue as well. It usually had something to do with a contract function that would probably throw. Also mentioned in #2266

**Comment by bdresser** [comment]
closing in favor of #2266. if you're still experiencing this, holler there.
