### ISSUE TITLE
[Bug]: Send - Editting a Transfer From transaction displays the ERC20 token as if it was an ERC721 with tokenId and weird behaviour if proceed

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23152]
### Describe the bug

**Problem:** whenever I am performing a transfer from functionality for an ERC20 token, if I edit that transaction I see how the Asset displays the token amount as if it were the token id of an NFT and on the amount field I see 0 ETH.
If I then proceed to the next screen I see now an amount of 0.

### Expected behavior

We should see the Edit ERC20 screen

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/9e55ee99-cec6-46fa-87f7-557c0a1e31c8

### Steps to reproduce

1. Select Mainnet
2. Go to the DAI contract
3. Connect MM
4. Click transferFrom
5. Add any recipient, src and amount
6. Click Write
7. Click Edit transaction on MM
8. See how the amount is now a token id
9. Click next
10. See how the screen now displays amount of 0

### Version

11.11.0 but seems an older issue - already happening in prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This will be fixed with https://github.com/MetaMask/metamask-extension/issues/24322

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-extension/issues/24322 was merged
