### ISSUE TITLE
[Bug]: metamask for android firefox browser keeps loading

### ISSUE THREAD

**Issue by Tanzin01** [MetaMask/metamask-extension#23162]
### Describe the bug

Upon clicking the extension , it keeps loading.
I tried few versions. The recently ones behaves like the title saying.
Tried a 10.x.x which gives this error- MetaMask had trouble starting. This error could be intermittent, so try restarting the extension. 

### Steps to reproduce

Click extension -> the metamask page appear , loading
Animation. It's keeps loading forever

### Version

11.10.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Firefox

### Operating system

Linux

### Additional context

Not others but rather tried all version. From ff store to this git relase

**Comment by danjm** [comment]
@Tanzin01 is it possible for you to inspect the dev console to see if there are any error messages?

**Comment by danjm** [comment]
@Tanzin01 have you had metamask work on android firefox in the past? We don't explicitly support that browser, so we can't guarantee it will work correctly.

**Comment by gauthierpetetin** [comment]
Potentially a duplicate of https://github.com/MetaMask/metamask-extension/issues/22533
