### ISSUE TITLE
Every time I click the metamask extension it crashes and is corrupt

### ISSUE THREAD

**Issue by rawdawgass** [MetaMask/metamask-extension#2316]
I can't find my seed words at the moment. When connecting to Etherdelta it shows the wallet information and amounts, but I can't enter my password because it corrupts and crashes when I click on the icon. Please help.

**Comment by fjchen7** [comment]
I have the same problem as yours. My MetaMask has 17 address. It will crash each time I enter password to unlock them. How to access my address? I havent backup them. Help please!!!

**Comment by bdresser** [comment]
hey folks - if you're still having trouble, please reach out to support@metamask.io
