### ISSUE TITLE
[Bug]: Fiat symbol wrongly displayed as native currency symbol and overall account balance in native currency is missing

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#23186]
### Describe the bug

Right now being on Fiat currency wrongly displays the fiat value as ETH instead of USD but with the correct value and currency. Same happens if I change the currency conversion to euro or other currencies. But only to native tokens (ETH). Other ERC-20 tokens are displayed with correct symbol, EUR. This happens on other networks as well. Not happening on v11.11.0

### Expected behavior

Fiat symbol is displayed correctly based on the currency selected. 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/2d3629ed-d168-4e8b-8755-65e63565f091

![image](https://github.com/MetaMask/metamask-extension/assets/120041701/09501edb-f94c-4c26-9d73-66aa735e565f)

### Steps to reproduce

1. Log in to MetaMask
2. Notice overall account balance in native tokens is missing
3. Go to Settings --> General --> Primary currency and select Fiat
4. Notice how token balance in the tokens list appears with wrong symbol for fiat (ETH instead of USD)

### Version

11.12.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by federicosan** [comment]
ETH is not being listed for sellection on general settings, I think this may be the issue.

**Comment by gauthierpetetin** [comment]
Hi @benjisclowder , this issue can be closed, right?
