### ISSUE TITLE
[Bug]: Transaction with invalid/unsupported type cannot be cleared from the wallet and remains as `Unapproved`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23180]
### Describe the bug

**Problem:** whenever I trigger a not-supported or invalid transaction type, with gasLimit and gasPrice params, if I accept the transaction MM stays loading, but the transaction stays in an `Unapproved` state. If I try to reject it, nothing happens and tx remains `Unapproved` and cannot clear it from the wallet

### Expected behavior

I think that, if the tx type is invalid or not supported, we shouldn't allow to proceed with the MM popup?
cc @bschorchit @matthewwalsh0 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/ba147211-cc23-47b9-ba08-71d55fbb93d9

### Steps to reproduce

1. Go to the test dapp (locally)
2. Change the Send Eth (legacy) tx type to `type: '0x3'`
3. Trigger that tx on the test dapp
4. Accept it --MM stays loading
5. Go to the full view of the wallet
6. See tx stays as `Unapproved`
7. Try to reject it
8. See tx stays as `Unapproved`

### Version

11.10 but it's an pre-existing issue

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
> I think that, if the tx type is invalid or not supported, we shouldn't allow to proceed with the MM popup?

I agree

**Comment by anaamolnar** [comment]
Should I remove the stale label from this? @bschorchit

**Comment by bschorchit** [comment]
Closing as a fix has been merged: https://github.com/MetaMask/core/pull/4596
