### ISSUE TITLE
NewUI - QR codes are missing the `ethereum:` prefix

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#2320]

**Comment by chikeichan** [comment]
@kumavis it seems that `ethereum:` is already prefix for the Account Detail QR code. Which QR code were you testing?

**Comment by kumavis** [comment]
Maybe the initial deposit QR code? Not sure now

**Comment by bdresser** [comment]
no longer an issue, but we now have https://github.com/MetaMask/metamask-extension/issues/5125
