### ISSUE TITLE
Replace EnsController with core EnsController

### ISSUE THREAD

**Issue by cryptodev-2s** [MetaMask/metamask-extension#23223]
### What is this about?

Following the successful merge of EnsController from the extension to the core Existing EnsController as detailed in https://github.com/MetaMask/core/issues/1129, we should now fully remove the EnsController logic from the extension and instead rely entirely on the core monorepo implementation.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by mcmire** [comment]
Closed via #23224.
