### ISSUE TITLE
[Bug]: Can not send funds to a contract from the extension

### ISSUE THREAD

**Issue by livingrockrises** [MetaMask/metamask-extension#23226]
### Describe the bug

I am trying to replay a transaction from metamask that requires me to send 0 funds to a contract address and use custom hex data. when the extension detects target is a contract it blocks me from clicking 'next'. This should not be expected behavior. Also there is a use case to send funds to smart contract accounts.

### Expected behavior

Should be able to interact with a contract from metamask.

### Screenshots/Recordings

<img width="391" alt="Screenshot 2024-02-28 at 8 54 18 PM" src="https://github.com/MetaMask/metamask-extension/assets/90545960/1e51164e-a8e6-4ac4-b78e-046b1795d44b">
<img width="381" alt="Screenshot 2024-02-28 at 8 54 24 PM" src="https://github.com/MetaMask/metamask-extension/assets/90545960/f6584ac1-8974-402f-975d-6935c029389b">

### Steps to reproduce

try to send native token >=0 on Mumbai / major EVM networks on any contract address as target (I used 0x4e59b44847b379578588920ca78fbf26c0b4956c)

### Version

11.9.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by livingrockrises** [comment]
Is it possible it checks for receive function during estimation?
I have been able to do this in the past though.

It doesn't happen when I try to send on a different contract on ethereum which has receive hooks

**Comment by seaona** [comment]
Possibly same/similar issue than https://github.com/MetaMask/metamask-extension/issues/22219#issuecomment-1855804721
