### ISSUE TITLE
[Bug]: PPOM - Batch Signatures trigger batch ppom requests and several errors follow

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23222]
### Describe the bug

**Problem:** if a dapp triggers a batch of 10 signatures, several things happen:
- x10 requests are sent to the cdn (see screenshot below)
- the following errors appear
  -  https://github.com/MetaMask/metamask-extension/issues/23173
  -  `Error: File metadata config 0x1 not found
  - `TypeError: Failed to execute digest on subltecrypto: the provided value is not of type ArrayBuffer or ArrayBufferView` relates to https://github.com/MetaMask/metamask-extension/issues/22991
  - `Cannot assign read only property version of object object` relates to https://github.com/MetaMask/metamask-extension/issues/22991

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/cd28c950-6193-4176-86d8-b6736c198448

![Screenshot from 2024-02-28 12-13-48](https://github.com/MetaMask/metamask-extension/assets/54408225/a2015ab9-022f-40cc-b216-f187a20fc5a7)

### Steps to reproduce

1. Go to the test dapp branch where batch signatures are implemented https://github.com/MetaMask/test-dapp/pull/294
2. Select Mainnet
3. Trigger 10 batch signatures
4. Check background console

### Version

11.12 / develop , but might be introduced earlier / never accounted this case

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Closing as this seem to no longer be happening
