### ISSUE TITLE
[NewUI] Seed word importing/resetting is currently broken. Seed word at-start is fine.

### ISSUE THREAD

**Issue by chikeichan** [MetaMask/metamask-extension#2322]

**Comment by chikeichan** [comment]
@Zanibas Would you mind to elaborate? I tested `reset password with seed phrase` from the login screen, and it works. There is also no `import from seed phrase` option.

**Comment by Zanibas** [comment]
This may be leftover from UAT v1: I believe importing works fine now--I'll resubmit if this isn't the case.
