### ISSUE TITLE
Facelifting installation & update screens

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#23244]
Let's match our snaps lifecycle screens with the confirmation redesign (and our upcoming dynamic permission request screen)

<img width="1525" alt="facelifted-snaps-flows" src="https://github.com/MetaMask/metamask-extension/assets/34306844/42c3429a-89f3-4217-b77f-1c3ffe461842">

**Comment by eriknson** [comment]
Design almost done

**Comment by eriknson** [comment]
Updated this issue with the design

**Comment by david0xd** [comment]
The first screen displayed here will be updated in the refactoring PR that will go first: https://github.com/MetaMask/metamask-extension/pull/23557
It would be something like:
<img width="361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0U4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a13b97fd2f190ac323b1cc98eaf30c630116ca81/Screenshot%202024-04-05%20at%2023.36.31.png" alt="Screenshot 2024-04-05 at 23.36.31.png" />
This screen, for Snaps, should appear when requesting account or in the future when requesting dynamic permissions.
