### ISSUE TITLE
[Bug]: Multichain - same amount is carried over when switching networks.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23254]
### Describe the bug

When the network is changed, the 'send' amount is retained and applied to the new network. It's worth considering whether this behavior is intended, as it could potentially cause confusion, particularly when the tokens differ across networks. For instance, if I'm sending 1 ETH on the Ethereum mainnet and then switch to the Avalanche network, the confirmation screen shows 1 AVAX.

### Expected behavior

The Confirmations System team has observed this behavior and is currently not sure whether it represents a bug or if it's functioning as intended, could benefit from further clarification.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/42fe525f-4856-400e-ba5e-7ff89c1fcd0e

### Steps to reproduce

1. Initiate regular 'send' transaction
2. Add amount
3. Click "Continue" to get to the last confirmation screen
4.  Click "Edit"
5. Switch networks
6. See the same amount is applied to the transaction on another network

### Error messages or log output

```shell
No errors in the background console.
```

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Dev build from [7860514](https://github.com/MetaMask/metamask-extension/pull/22457/commits/78605142feb654717132c70f253d416ea66c373c)

**Comment by hesterbruikman** [comment]
Great catch @sleepytanya. Agree that if the native token no longer applies the amount should be reset to zero.

cc @darkwing

**Comment by hesterbruikman** [comment]
Close as network picker will be removed. Included to address in new designs in this [spreadsheet](https://docs.google.com/spreadsheets/d/1HsXWIUqShWSpVQ1x8ZoN5K47k9jT94hc-vzZZgmxSyE/edit#gid=0)
