### ISSUE TITLE
[Bug]: Multichain - notification about switching to a different network is visible for a very short time, disappears without clicking 'Got it' button.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23255]
### Describe the bug

The notification regarding the switch to a different network appears briefly and then vanishes without the need to click the 'Got It' button. Might be too quick for users to fully acknowledge the change.

### Expected behavior

Users are provided with ample time to read the notification and can click 'Got It' to acknowledge the change.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/ce211659-f26b-4d03-b31a-3fcf26ef4715

### Steps to reproduce

1. Go to 'Add a network'
2. Switch to selected network
3. Send any transaction
4. Add amount
5. Click 'Continue' to proceed 
6. Click 'Edit' 
7. Switch to Linea mainnet
8. See the notification appear briefly and disappear without clicking on it

### Error messages or log output

[consoleErrors.txt](https://github.com/MetaMask/metamask-extension/files/14454904/consoleErrors.txt)

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Dev build from [7860514](https://github.com/MetaMask/metamask-extension/pull/22457/commits/78605142feb654717132c70f253d416ea66c373c)

**Comment by sleepytanya** [comment]
This bug is still present on develop but it seems to happen less often:


https://github.com/MetaMask/metamask-extension/assets/104780023/371ecf8c-dcbc-4a48-a6d9-620ede87eed4



https://github.com/MetaMask/metamask-extension/assets/104780023/261f7183-d7e9-4ddc-92dc-c69e7180fca7

**Comment by hesterbruikman** [comment]
Removed from Amon hen v1 as issue is already in production. To review where this might have been introduced.
