### ISSUE TITLE
[Bug]: Multichain - Adding a network during the Edit Send Flow lands me to the last Confirmation screen without the network switch popup

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23262]
### Describe the bug

**Problem:** whenever I am editing a transaction, if I add a network, I am landed into the last Confirmation screen with the current network selected. After confirming/rejecting the transaction I see the network switch request popup

### Expected behavior

This is my intuition of what we should expect, but to verify with product cc @hesterbruikman 

- We should see the network switch right after (like it's used to outside send flow)
- We should remain in the Edit transaction page
- We should change networks if user accepts changing networks in the popup
- We should not change networks if the user reject changing networks in the popup

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/7d02b277-7540-42a8-a33f-b8d31309a5b3

### Steps to reproduce

1. Start a send flow
2. Go to the last confirmation page
3. Click Edit
4. Click Add network
5. Add any network --- see you are landed into last confirmation page with the previous network selected
6. Accept/Reject the transaction -- see the network switch request popup appears at the home screen

### Version

develop - with multichain flag

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by hesterbruikman** [comment]
Close as network picker will be removed. Included to address in new designs in this [spreadsheet](https://docs.google.com/spreadsheets/d/1HsXWIUqShWSpVQ1x8ZoN5K47k9jT94hc-vzZZgmxSyE/edit#gid=0)
