### ISSUE TITLE
[Bug]: Multichain - Attempting to add a custom test network results in the wallet becoming unresponsive.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23279]
### Describe the bug

MetaMask freezes completely when custom test network added. Issue can be resolved by reloading extension. Custom network may be randomly added or not.

### Expected behavior

User is able to add custom test networks.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/774bafce-a909-4353-96bd-36ca18c269bf

![Screenshot 2024-03-01 at 6 21 52 PM](https://github.com/MetaMask/metamask-extension/assets/104780023/9fb9ac72-3bfd-4f08-8f41-ee2c2d9a4718)

### Steps to reproduce

1. Go to https://chainlist.org/
2. Add BNB Smart Chain Testnet / Avalanche Fuji Testnet / Arbitrum Goerli
3. See the wallet completely frozen

### Version

Dev build git id 23a9982

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
Close as network picker will be removed. Included to address in new designs in this [spreadsheet](https://docs.google.com/spreadsheets/d/1HsXWIUqShWSpVQ1x8ZoN5K47k9jT94hc-vzZZgmxSyE/edit#gid=0)
