### ISSUE TITLE
PPOM - Support Blockaid validations on Sepolia network

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23272]
### What is this about?

After last ppom version has been released v1.4.2, we can now use Blockaid in Sepolia. We should add the necessary changes to support it in Extension.

Extra note: there's an[ upcoming change in geth](https://github.com/ethereum/go-ethereum/releases/tag/v1.13.14), which might affect[ `eth_creatAccessList`](https://github.com/ethereum/go-ethereum/pull/28846) so we need to test this in Sepolia before this is implemented in Mainnet

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by segun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23272?planning-poker) with Zenhub @blackdevelopa @jpuri @seaona
