### ISSUE TITLE
[Bug]: Sign message show hex string instead of utf-8 in some specific message.

### ISSUE THREAD

**Issue by y-pakorn** [MetaMask/metamask-extension#23282]
### Describe the bug

When signing some specific message, Metamask shows hex string instead of its original utf-8 counterparts. This happen with only some message as I tested. 

### Expected behavior

With the actual message being: `Sign in to VVVVVVV early access.`
What I got from Metamask when I clicked sign: `0x5369676e20696e20746f2056565656565656206561726c79206163636573732e`
What I SHOULD got from Metamask when I clicked sign: `Sign in to VVVVVVV early access.`

### Screenshots/Recordings

This is from metamask

<img width="381" alt="Screenshot 2567-03-02 at 15 22 44" src="https://github.com/MetaMask/metamask-extension/assets/48324733/c5c4e3a9-bd65-4979-b4bf-07cf2cf9b1c6">

This is from other wallet

<img width="376" alt="Screenshot 2567-03-02 at 15 21 54" src="https://github.com/MetaMask/metamask-extension/assets/48324733/ab02dde4-8f50-499d-93ee-dceeea0c8972">

### Steps to reproduce

[Link to reproducible code](https://stackblitz.com/edit/sign-bug-metamask?file=src%2FApp.tsx)

### Version

11.10.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

MacOS

### Additional context

Browser: Arc

**Comment by jpuri** [comment]
Text strings that result in hex string of length 32 can give issue with personal signs, but it is more of an edge case. We display string of length 32 as hex only as it can be a hash value. More details here: https://github.com/MetaMask/metamask-extension/pull/24367#discussion_r1589303851
