### ISSUE TITLE
[Bug]: About the Extension manifest v3 build command

### ISSUE THREAD

**Issue by pemaju** [MetaMask/metamask-extension#23283]
### Describe the bug

Hi Team,

Now we have integrated your github code.

It’s working fine, while running “yarn dist” for manifest v2. But this not possible to publish in chrome store as you know.

So we build to manifest v3 by running “yarn dist:mv3”. But in this case when initially the extension was working good. But one time close a browser, again open it. its loading issue occurs

![Screenshot from 2024-03-01 19-33-42](https://github.com/MetaMask/metamask-extension/assets/112880019/e80e96bf-6e50-43d1-99c8-b783b8a5b784)

Kindly guide me. If anything missing my end

Thanks in advance

### Steps to reproduce

While close the browser, and open it again, See this issue

![Screenshot from 2024-03-01 19-33-42](https://github.com/MetaMask/metamask-extension/assets/112880019/fb10cd9d-2a54-4752-a38d-821328223214)

### Version

11.9.5

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by anaamolnar** [comment]
Hello, @pemaju. Thanks for reporting this! I am really sorry I missed this. Please attempt this in the latest version and let us know if it still occurs. Thanks!

**Comment by pemaju** [comment]
we have fixed this issue. In app-init file we have changed the eventlistener from chrome.runtime.onMessage to chrome.runtime.onConnect.
