### ISSUE TITLE
[Bug]: Multichain - account balance is not consistently updated when switching networks during a transaction.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23280]
### Describe the bug

Account balance is not always updated if I switch networks while sending a transaction.  

### Expected behavior

Account balance is refreshed to align with the selected network.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/0238e71d-8f91-450f-a98d-04dbdb846f5a

### Steps to reproduce

1. Choose any network
2. Start 'send' transaction
3. Switch networks
4. Notice that balance for the selected network is not always updated

### Version

Dev build git id https://github.com/MetaMask/metamask-extension/pull/22457/commits/23a99825a2cad956e1621c76fe43c89f9718f31a

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
Close as network picker will be removed. Included to address in new designs in this [spreadsheet](https://docs.google.com/spreadsheets/d/1HsXWIUqShWSpVQ1x8ZoN5K47k9jT94hc-vzZZgmxSyE/edit#gid=0)
