### ISSUE TITLE
[Bug]: PPOM - `CompileError: WebAssembly.instantiateStreaming(): Refused to compile or instantiate WebAssembly module because neither 'wasm-eval' nor 'unsafe-eval' is an allowed...f'"`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23285]
### Describe the bug

**Problem:** when using a different RPC provider, if I try to perform a tx a get the following error and ppom spinner stays loading indefinetly:
- `UNHANDLED_REJECTION: CompileError: WebAssembly.instantiateStreaming(): Refused to compile or instantiate WebAssembly module because neither 'wasm-eval' nor 'unsafe-eval' is an allowed source of script in the following Content Security Policy directive: "script-src 'self'"`

### Expected behavior

This seems an issue on ppom side. Blockaid needs to revise how to handle such cases.
On MM side, we should revise what to do with the loading spinner in this case. cc @bschorchit 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/a37175f3-cdfa-44f9-89b9-a993432592e3

### Steps to reproduce

1. Create an Optimism network in tenderly dashboard.tenderly.c
2. Add it to MM
3. Initiate a tx
5. PPOM Stays loading indefinetly

### Version

11.10.0 but may be an existing issue

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by cryptotavares** [comment]
@seaona is this still happening? I know that this was happening on the MV3 build.. but the main reason was due to the manifest file content policy config. That has been fixed. [More in this slack thread](https://consensys.slack.com/archives/GTQAGKY5V/p1713347307183669?thread_ts=1713278799.505269&cid=GTQAGKY5V)

**Comment by jpuri** [comment]
Closing the issue as it is not replicating in latest code.
