### ISSUE TITLE
[Bug]: Default gas settings on arbitrum orbit chains is too high

### ISSUE THREAD

**Issue by mattvv** [MetaMask/metamask-extension#23289]
### Describe the bug

Hi guys! 

We run an orbit chain (https://explorer.apex.proofofplay.com/) and we are experiencing a high level of complaints from metamask users that metamask defaults their gas estimations too high. I believe this issue likely happens with any arbitrum orbit chain. Our chain has a default gas of 0.01gwei, and metamask is estimating at 1.5 gwei.

We previously used arbitrum orbit, which has a similar configuration to this chain but does not face this issue.

### Expected behavior

Users are prompted with lower gas estimation

### Steps to reproduce

1. Add Proof of Play Apex chain (https://explorer.apex.proofofplay.com/ has an add to metamask button at the bottom)
2. Attempt to do any transaction
3. Observe gas estimation is significantly higher then it needs to be.

### Version

11.7.5

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Severity

It appears this is happening to all metamask users on our chain (and potentially other chains).

**Comment by mattvv** [comment]
Looks like the current approach is  either https://gas-api.metaswap.codefi.network/networks/42161/suggestedGasFees returns a non error value in which case that's used or it falls back to using eth_feeHistory, but lower bounds the priority fee

The problem for arbitrum chains is that the priority fee should be 0. I'm assuming there's a reason why the minimum priority fee is put in place by default, but I'm wondering if you'd be up to put in place a system to disable the minimum bound for orbit chains (like metamask does for arb) chains, basically bypassing this line for all arbitrum chains https://github.com/MetaMask/core/blob/c5dbb372dc0514fa4009d7f3d2eb9bdc76a8369f/packages/gas-fee-controller/src/fetchGasEstimatesViaEthFeeHistory/calculateGasFeeEstimatesForPriorityLevels.ts#L79. It'd be pretty easy to detect if a chain is an arbitrum chain by seeing whether an rpc call to some arbitrum specific precompile returned a valid result

**Comment by cloudonshore** [comment]
This is supported now: https://gas-api.metaswap.codefi.network/networks/70700/suggestedGasFees

**Comment by anaamolnar** [comment]
Hey @mattvv. We haven't heard back from you. I will close this issue for now. Feel free to reopen it if this continues to occur.
