### ISSUE TITLE
[Bug]: Multichain - L1 and L2 gas fees breakdown is not displayed on the Send screen for L2 networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23290]
### Describe the bug

**Problem:** if I am performing a send on Optimism, I can see how on the Send screen, one line of gas is displayed. At this stage, we don't know if that's L1 or L2 fees (it seems it's L2). However, for networks where there are 2 fees, this behaviour doesn't seem correct

### Expected behavior

On the non-multichain, we don't display fees on the send screen. So not sure what we should expect here. One of the 2:
- display both L1 and L2
- not display fess on the Send screen

Question for product @hesterbruikman @bschorchit 

### Screenshots/Recordings

No L1/L2 fees split in the Send screen:

![Screenshot from 2024-03-04 08-24-58](https://github.com/MetaMask/metamask-extension/assets/54408225/cbe3e5d6-3453-4bbf-95c9-bbe168abb3c2)

L1 and L2 fees split in the Confirmation screen:
![Screenshot from 2024-03-04 08-25-27](https://github.com/MetaMask/metamask-extension/assets/54408225/d1f1f509-b401-4a0f-91c6-277e3ec692a1)

### Steps to reproduce

1. Select Optimism network
2. Start a transaction
3. Add a recipient
4. See no L1/L2 fee split - only one fee is displayed (it seems it's the L2)
5. GO to the confirmation screen
6. Check fees details
7. See both L1 and L2 information

### Version

develop - with multichain flag

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by hesterbruikman** [comment]
Recap of Slack conversation for posterity. Decision was made to remove gas component from send flow.

Gas fee and gas logic is really complex in the UI and follows legacy logic. Confining gas estimation to the Confirmations screen makes it easier to maintain.

This bug is addressed by removing the gas component.
