### ISSUE TITLE
[Bug]: Gas - Duplicated fee section for Legacy transactions in L2

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23291]
### Describe the bug

**Problem:** whenever we are performing a legacy transaction on Optimism, we see the gas fees section duplicated

![Screenshot from 2024-03-04 08-37-25](https://github.com/MetaMask/metamask-extension/assets/54408225/b03471d4-d8a2-4fb6-b4f7-fba5a62e79bd)

### Expected behavior

Not sure how the design/organization of the fees should be, but it feels strange to see the same info twice. Once in the main gas fee and the other under gas fee details.
cc @bschorchit 

### Steps to reproduce

1. Select Optimism
2. Trigger a legacy tx from the test dapp
3. See gas fees

### Version

11.10.0 but possibly earlier

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
We should not duplicate information or fees and we should display fees in the same format that we currently do for non legacy transactions. 
<img width="364" alt="Screenshot 2024-03-21 at 16 48 18" src="https://github.com/MetaMask/metamask-extension/assets/34968356/fab5e976-eebf-4757-8aa2-31b68ac2f553">
<img width="364" alt="Screenshot 2024-03-21 at 16 48 25" src="https://github.com/MetaMask/metamask-extension/assets/34968356/da264793-0da8-4c0d-b2b7-5383ad3fc087">

**Comment by pedronfigueiredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23291?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by seaona** [comment]
Context: when the new Gas Display was introduced it was decided to leave out of scope the Legacy transactions, and fix it in another PR. This has not been done yet. However, I think that the scope of this ticket is not to fix the design, but just to fix the duplicated fees 

https://github.com/MetaMask/metamask-extension/pull/19960#issuecomment-1706171781

**Comment by jpuri** [comment]
This looks already fixed in latest code, can you plz confirm @seaona 

<img width="415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenFGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6c406957ed72c400c08f4bbcd7af135b19e6236/Screenshot%202024-04-23%20at%205.34.31%E2%80%AFPM.png" alt="Screenshot 2024-04-23 at 5.34.31 PM.png" />

**Comment by seaona** [comment]
hey Jyoti I think that the issue is we don't want to show the same L1 and L2 sections on both the gas section and the fee details sections, since then there is no actual point of having the Fee details section.
So the solution should be to follow the same approach we do for EIP1559 tx, where the L1 and L2 gas split is only shown on the Fee details.

Does it make sensE?

**Comment by jpuri** [comment]
Hey @seaona , @bschorchit 

will something like this screenshot look good ?

<img width="458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9TQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b83f41da6058fa5035df8f467777daf8f23e1102/Screenshot%202024-04-25%20at%205.47.58%E2%80%AFPM.png" alt="Screenshot 2024-04-25 at 5.47.58 PM.png" />

**Comment by bschorchit** [comment]
Hey @jpuri , the part below `Fee details` look good. The part above it needs some small tweaks. We should call `Estimated fee` instead of `Total` there, hide `Amount+fees` copy and reduce the spacing between the `Edit` button and the rest of the info.

**Comment by SayaGT** [comment]
You can find the [design here](https://www.figma.com/file/oHNdOauz7w9PEti2zX83Cg/Gas-component?type=design&node-id=18%3A904&mode=design&t=x7IrvAXsOwKW3JLK-1) @jpuri
