### ISSUE TITLE
[Bug]: Multichain - same petname is applied to a different network while switching networks in send flow.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23302]
### Describe the bug

 When a user switches networks while conducting a transaction, the initially created petname is transferred to the other networks (same in case when the account has different petname on selected network).

### Expected behavior

Account petname should match the petname of the selected network for this account.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/182aaeb2-1eb3-40e3-bc88-a4e325d8d19f

### Steps to reproduce

1. Start regular 'send' transaction
2. Create a petname for the recipient's account on the Confirmation screen
3. Proceed to edit the transaction, switch to another network
4. See the same petname for the account is used for selected network

### Version

Dev build git id 23a9982

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
Close as network picker will be removed. Included to address in new designs in this [spreadsheet](https://docs.google.com/spreadsheets/d/1HsXWIUqShWSpVQ1x8ZoN5K47k9jT94hc-vzZZgmxSyE/edit#gid=0)
