### ISSUE TITLE
[Bug]: Multichain - low values handled improperly in the new send flow.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23305]
### Describe the bug

When a user selects a very low 'send' amount, such as 0.0000001, and proceeds to edit transaction, the amount is converted into the '1e-7' representation.

### Expected behavior

Proper management of low numbers.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/37ff1ea2-f04f-4e07-bc72-fa3c054b2a20

### Steps to reproduce

1. Start simple 'send' transaction
2. Set low ETH amount (i.e. 0.0000001)
3. Click 'Continue'
4. Click 'Edit'
5. See ETH amount converted into 1e-7

### Version

Dev build git id 23a9982

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
I reproduce this.  Since the new asset picker re-uses the old `UserPreferencedCurrencyInput`, the bug also occurs in the current send flow.

https://github.com/MetaMask/metamask-extension/assets/3500406/b338349c-8edb-4fca-bdc6-265a7e616a90

**Comment by sleepytanya** [comment]
@salimtb 
Dev build git id [(8218554)](https://app.codecov.io/gh/MetaMask/metamask-extension/pull/23341?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=MetaMask), Chrome.
Small numbers rendered correctly. UI doesn't display numbers as low as 0.000 000 001 when editing transaction  but the transaction is sent with the correct amount:


https://github.com/MetaMask/metamask-extension/assets/104780023/93983e82-2460-47b8-8186-5449e024b4b8

**Comment by hesterbruikman** [comment]
@sleepytanya @darkwing Does it make sense to you to remove the `amon-hen-blocker` label? Going by @bergeron's comment, this is in production today and I don't consider it a blocker specific to Amon Hen.

**Comment by sleepytanya** [comment]
@hesterbruikman Removed!
