### ISSUE TITLE
[Bug]: Multichain - random characters displayed in red within the petnames.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23304]
### Describe the bug

Random characters displayed in red within the petnames.

### Expected behavior

Petnames are presented in the same font.

### Screenshots/Recordings

<img width="288" alt="Screenshot 2024-03-05 at 12 21 34 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/0ca04c66-73e0-4a0e-8e9d-20f8ff58dc68">

### Steps to reproduce

1. Go to 'Settings' -> 'Contacts'
2. Create petname (-s)
3. See some numbers / symbols / letters displayed in red

### Version

Dev build git id 23a9982

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
I think an explanation of this might be:

https://github.com/MetaMask/metamask-extension/issues/14800#issuecomment-1141348077

**Comment by darkwing** [comment]
This should definitely be updated; address book items should be trusted since the user already approved them.

**Comment by darkwing** [comment]
This has been merged into the `release-send` branch
