### ISSUE TITLE
[Bug]: #22790 should be treated as a Sev1-high

### ISSUE THREAD

**Issue by kamikazechaser** [MetaMask/metamask-extension#23306]
### Describe the bug

Metamask has been unusable when setting gas fee parameters. Once set metamask completely breaks. You cannot proceed to the step to fallback to network defaults. In short, the only workaround is to delete metamask, reload all your keys and never set a custom  gas fee param. This has already been described in #22790.

Please bump this to a high sev and if possible, an immediate patch release (manual install is complicated with unsigned extensions).

This bug is affecting several sidechains e.g. Celo and a lot of users are already on the brink of leaving metamask. I have confirmed reports of at least 10 users facing the same issue.

### Screenshots/Recordings

Metamask works fine with custom gas parameters.

### Steps to reproduce

Described in parent issue.

### Version

11.10.1

### Build type

None

### Browser

Firefox, Microsoft Edge

### Operating system

Linux

### Severity

* I'd put this as sev-0 or at least sev-1

**Comment by gauthierpetetin** [comment]
cc @bschorchit @cryptotavares @vinistevam @anaamolnar for visibility

**Comment by bschorchit** [comment]
Hey @gauthierpetetin it seems the fix he's referring to was merged 3 weeks ago. In order to solve this current issue we would need to expedite the release of that fix. Would that be possible? cc: @danjm

**Comment by bschorchit** [comment]
Currently, we expect the fix to rollout to users in 10 days (starting on March 18th)

**Comment by bschorchit** [comment]
Closing as the fix has been rolled out to all users ✅
