### ISSUE TITLE
[Bug]: Multichain - `React has detected a change in the order of Hooks called by ConnectedStatus.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23312]
### Describe the bug

**Problem:** whenever I initiate the Send flow, I see the following warning in the ui console `React has detected a change in the order of Hooks called by ConnectedStatus. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks` from the `connected-status.tsx`

Not sure if this is an issue, or a known change.

### Expected behavior

To investigate the impact of this.
Handle the warning.

### Screenshots/Recordings

![Screenshot from 2024-03-05 12-00-11](https://github.com/MetaMask/metamask-extension/assets/54408225/b1b07b9e-99bd-45e8-aaca-6a185d9a14c2)

### Steps to reproduce

1. Build with the multichain flag on
2. Start a transaction
3. See UI console warning

### Version

release-send with multichain flag on (also present in develop with feature flag on)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by darkwing** [comment]
This has been fixed.
