### ISSUE TITLE
Convert detect-tokens.js to typescript

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#23322]
Part of https://github.com/MetaMask/metamask-extension/issues/23018

**Comment by MajorLift** [comment]
Heads-up that shared libraries is in the last stages of replacing `detect-tokens.js` with the core repo `TokenDetectionController` written in TypeScript. 

- Epic https://github.com/MetaMask/core/issues/1812 
- Latest ticket https://github.com/MetaMask/metamask-extension/pull/22928

**Comment by DDDDDanica** [comment]
@danjm  @NiranjanaBinoy close this one as it is covered by shared libraries team
