### ISSUE TITLE
[Bug]: Animation for pinning accounts looks too much like networks (drag & drop)

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#23321]
### Describe the bug

We've had numerous comments from users that the animation in the Accounts menu is too much like the Network menu, which illustrates drag and drop.

### Steps to reproduce

1.  Open the account menu
2. See the animation

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by mmragkandala** [comment]
There seems to be a related ticket open: https://app.zenhub.com/workspaces/metamask-wallet-ux-63529dce65cbb100265a3842/issues/gh/metamask/metamask-extension/22969
