### ISSUE TITLE
[Bug]: Faulty scam warning message

### ISSUE THREAD

**Issue by Avinaash7** [MetaMask/metamask-extension#23328]
### Describe the bug

Domain :- https://kittpad.net/

We are a genuine staking company where we stake our own made token called "Meow" but while trying to call the approve function for staking the token. We encounter this faulty scam message from metamask. Kindly check this and sort this out. This gives a false message to our customers
![IMG-20240306-WA0000](https://github.com/MetaMask/metamask-extension/assets/71816352/a546d8e8-cb96-43b1-a614-f3c636ba8420)

### Steps to reproduce

1. Go to https://kittpad.net/
2. Scroll down to Stake
3. Input a number and click Stake

### Version

7.1.0

### Build type

None

### Browser

Chrome, Brave

### Operating system

Windows

**Comment by bschorchit** [comment]
Hey @Avinaash7 thank you for your report. Would you mind clicking on the `Report an issue` within the warning and submitting the form? That's the quickest way to have such issues addressed.

**Comment by bschorchit** [comment]
Closing as I learned that this has been already solved.
