### ISSUE TITLE
[Bug]: Multichain - switching 'From' accounts is ignored.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23331]
### Describe the bug

When a user switches `From` accounts during the process of sending a transaction,  transaction is sent from the initially selected account. The warning `Is this a correct account? It's different from the currently selected account in your wallet` is shown.

### Expected behavior

Transaction is sent from the selected account.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/06f76d61-fcbc-4ff5-841e-88fc82038f1c

### Steps to reproduce

1. Start regular 'send' transaction
2. Switch sender's account
3. Initially selected account is displayed on the confirmation screen with the warning about possibly different account
4. Confirm transaction
5. Transaction is on the initially selected account Activity list

### Version

Dev build git id 23a9982

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Possibly related https://github.com/MetaMask/metamask-extension/issues/23284

**Comment by darkwing** [comment]
This is actually current behavior as well.

**Comment by hesterbruikman** [comment]
Decision: Disable from account selection when coming from Confirmations > Edit

**Comment by sleepytanya** [comment]
Confirming the same behavior on the latest build on `mb843/data-flows`:

https://github.com/MetaMask/metamask-extension/assets/104780023/2b50974f-c55c-4aae-8276-a078180ab5db

**Comment by sleepytanya** [comment]
Still present on [the latest build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN):


https://github.com/MetaMask/metamask-extension/assets/104780023/e1ebb7d7-d2df-4102-bca0-5c1477d18e40

**Comment by BZahory** [comment]
Resolved by https://github.com/MetaMask/metamask-extension/pull/23708
