### ISSUE TITLE
[Bug]: Abnormal gas cost prompts the contract to report an error and cannot calculate the price

### ISSUE THREAD

**Issue by jasonDesyn** [MetaMask/metamask-extension#23335]
### Describe the bug

When I send an on-chain contract interaction request under the ETH Mannit network, he will prompt me that the contract reports an error and cannot calculate gas, and the gas fee will be much higher than normal.

I haven't found any relevant solutions. I can do the same operation using other wallets.

### Screenshots/Recordings

![WechatIMG334](https://github.com/MetaMask/metamask-extension/assets/89964643/1a7d0cdf-8d06-4dbf-a7f2-ed78c8d75fff)

### Steps to reproduce

A problem occurred when I purchased DeFi funds and sent on-chain contract interactions. The problem is as described above.

### Version

11.7.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jasonDesyn** [comment]
I updated my wallet to the latest 11.11 version and got the same error

**Comment by jasonDesyn** [comment]
![WechatIMG335](https://github.com/MetaMask/metamask-extension/assets/89964643/79c9d714-bbb3-4572-a311-192c6fe61526)


I captured the wallet console prompting an error like this

**Comment by anaamolnar** [comment]
Hello, @jasonDesyn. I am really sorry for responding so late, I did not see this for some reason. Is this something you are still experiencing in version 11.13.0? Thanks!

**Comment by bschorchit** [comment]
@jasonDesyn would you mind sharing repro steps for this issue? We'll try replicate it on our side and understand why we're encountering an error if none is expected.

**Comment by bschorchit** [comment]
Closing due to lack of repro steps
