### ISSUE TITLE
[Bug]: Calling `request` too early after the browser start leads to a Promise which is never settled

### ISSUE THREAD

**Issue by imajus** [MetaMask/metamask-extension#23336]
### Describe the bug

The problem occurs when web page starts to interact with MetaMask shortly after a fresh browser instance is started (important: not a new tab/page is opened in already running browser instance). Apparently, the MetaMask extension takes time to initialize, and until it's done the web app should not call any MetaMask API methods.

What is really bad is that the call to request method returns a Promise which hangs forever, not giving any result or error, which negatively affects the web application behavior in what seems like a random manner which is pretty hard to debug.

Moreover, it's unclear how to properly wait until the MetaMask extension initialization process is finished, in order to adjust the web app initialization logic accordingly.

Whilst the problem won't affect 99% of web app users who open it in a new tab of already running browser instance, it does affect web app developers who are frequently starting new browser instances for debugging and/or automated testing purposes.

Similar issues has already been submitted [here](https://github.com/MetaMask/metamask-extension/issues/14283) and [here](https://github.com/MetaMask/metamask-extension/issues/19290) but the issue is still not fixed, as per the latest MetaMask Chrome extension.

### Expected behavior

The promise returned from the `window.ethereum.request()` call must always settle, e.g. either resolve or reject with an error.
Additionally, if in this case it will be rejected with an error, there must be a clear way for web page to ensure when it's OK to do the first call.

### Screenshots/Recordings

[Screencast from 2024-03-06 11-01-16.webm](https://github.com/MetaMask/metamask-extension/assets/1805633/817cd8f8-1a56-4dfb-aede-49c5812a1bcf)

### Steps to reproduce

1. Have a web page which calls `window.ethereum.request()` just after the web page is loaded in a browser
2. Open a web page in a new Chrome browser instance

### Error messages or log output

```shell
localhost/:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
(2) content-script-start.js:3543 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at wrappedSendMessageCallback (content-script-start.js:3543:20)
```

### Version

11.10.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Additional context

I've made an sample project with a straightforward way to reproduce the issue: https://github.com/imajus/metamask-initialization-bug

**Comment by jiexi** [comment]
Could be solved by this https://github.com/MetaMask/metamask-extension/pull/24142
