### ISSUE TITLE
[Bug]: MM breaks with the error `String provided to stringToBigNumber is not a hexadecimal or decimal string`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23346]
### Describe the bug

**Problem:** whenever triggering a transaction from a dapp, if the `maxFeePerGas` or the `maxPriorityFeePerGas` have an invalid value type (ie string), MM breaks.

### Expected behavior

Handle invalid gas params coming from a dapp

### Screenshots/Recordings

![Screenshot from 2024-03-06 15-26-20](https://github.com/MetaMask/metamask-extension/assets/54408225/349300cf-0ed6-4e2e-9aca-eac167700d95)

https://github.com/MetaMask/metamask-extension/assets/54408225/1fde043f-5ff6-4ed7-88b1-c8a192d4aa60

### Steps to reproduce

1. Go to the test dapp - this version https://github.com/MetaMask/test-dapp/pull/295
2. Trigger invalid max fee per gas
3. See MM breaks with the error

### Version

11.10.0 but possibly earlier

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by matthewwalsh0** [comment]
The `value` property should be validated to be a valid number or hex string within the `TransactionController`, hence the assignment to the transactions team.

**Comment by digiwand** [comment]
screenshots of states with `0xinvalid` maxFeePerGas
![CleanShot 2024-06-21 at 20 59 22@2x](https://github.com/MetaMask/metamask-extension/assets/20778143/0f789b8d-c6ee-4ae7-9ed8-08817de3e40d)
![CleanShot 2024-06-21 at 21 02 01@2x](https://github.com/MetaMask/metamask-extension/assets/20778143/e4afd090-a2cd-4647-acca-d492a3670cf3)
![CleanShot 2024-06-21 at 21 07 13@2x](https://github.com/MetaMask/metamask-extension/assets/20778143/a8666729-2775-4087-a996-c6458dd01273)

**Comment by sleepytanya** [comment]
https://github.com/MetaMask/metamask-extension/issues/26547 duplicate

**Comment by Unik0rnMaggie** [comment]
Present in v12.4.0 RC

https://github.com/user-attachments/assets/7422cb7c-aa3c-4eae-9cf9-b0f40743195a

**Comment by OGPoyraz** [comment]
I am unable to repro this issue, extension is not breaking anymore, rejecting request with an error.
https://github.com/user-attachments/assets/568c5275-4986-460a-b326-f3da518f8753
