### ISSUE TITLE
[BUG]: MMI Broken in Production

### ISSUE THREAD

**Issue by dbrans** [MetaMask/metamask-extension#23343]
@matthewwalsh0 wrote:

> We previously added a UI validation to prevent confirming a transaction if another was being signed or submitted, as it would lock up the UI due to locks in the TransactionController.
> Except this is impacting MMI also despite them supporting this since they skip signing using a hook.
> I think the quickest fix is to literally just disable the UI validation using an MMI code fence.

**Comment by dbrans** [comment]
@zone-live we'd appreciate if you could test the solution here: https://github.com/MetaMask/metamask-extension/pull/23342. Thanks!

**Comment by zone-live** [comment]
> @zone-live we'd appreciate if you could test the solution here: #23342. Thanks!

It's working again! Thank you @dbrans 🙏🏼
