### ISSUE TITLE
[Bug]: Swap is no longer working when Smart Transaction is turned ON

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#23373]
### Describe the bug

When Smart Transaction is turned ON, Swap is no longer working 

From the initial look
TransactionController.approveTransactionsWithSameNonce expects a chainId inside each transaction, which is missing now. It can be added to transactions in ui/ducks/swaps/swaps.js in the

The problem doesn't happen if Smart Transaction is OFF or in production

### Expected behavior

Swap is able complete when Smart Transcation is ON

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/6082863/f356c1b4-d0f7-46f8-abd2-50297c691514

![image (8)](https://github.com/MetaMask/metamask-extension/assets/6082863/44670eb2-650c-45fa-b174-c9bba6cc2cf0)

### Steps to reproduce

1. Go to Swap 
2. Turn Smart Transaction ON
3. Get a quote ETH->WETH
4. Click on Swap
5. Notice that the screen gets stuck on `Preparing Swap`

### Error messages or log output

```shell
signAndSendSwapsSmartTransaction error (Error#1)

The number NaN cannot be converted to a BigInt because it is not an integer
```

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Can confirm the same behavior on [v.11.12.0]([https://github.com/MetaMask/metamask-extension/commit/683f4c8a8e6c64a12bb5ef815f2cd8db86ef1aa4])
