### ISSUE TITLE
[Bug]: Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key.\n DataError: Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key.

### ISSUE THREAD

**Issue by hgaron-blockbar** [MetaMask/metamask-extension#23403]
### Describe the bug

Metamask is no longer connecting to dapps in Google Chrome. Any request to metamask throws the following error:

`Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key.\n DataError: Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key.`

This started for me today using chrome `Version 122.0.6261.112 (Official Build) (arm64)` and metamask extension `11.11.4
`.

I realize this is a duplicate of [bug 22534](https://github.com/MetaMask/metamask-extension/issues/22534) reported fixed already in version `11.7.3`, but this began today for me (I didn't previously notice it) with the latest chrome and metamask.

### Expected behavior

I expect metamask extension to not throw an IndexDB related error.

### Steps to reproduce

1. Go to any dapp
2. Try to connect wallet

You should get an error in the console.

**If this does not happen -- first disconnect all wallets from that site, then repeat these steps**

### Error messages or log output

```shell
{
    "code": 500,
    "message": "Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key.\n DataError: Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key."
}
```

### Version

11.7.3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

critical

**Comment by hgaron-blockbar** [comment]
After more investigation, it looks like this is triggered by the existence of other browser extensions. For those experiencing the issue, try disabling all other browser extensions, clearing cache, and restarting your browser. For me it fixed the issue.

Note: in my case, the offending extension that caused the problem was the crypto.com wallet extension. But for others it may be some other extension.

**Comment by anaamolnar** [comment]
Hello, @hgaron-blockbar. Thanks for reporting! I am sorry for missing this. I will close this issue for now, but feel free to reopen it if the problem comes back.
