### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mo-diggity** [MetaMask/metamask-extension#23410]
### Describe the bug

Stuck on loading screen, never get prompted for password

### Expected behavior

I expect to be prompted for password and then to be able to use the extension

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/133728135/8f2263a0-0c29-4505-b2df-7a3f1c7b870e)

### Steps to reproduce

1. click MM icon to open it
2. wait forever

### Version

11.10.1

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Hardware wallet

Ledger

### Additional context

Hardware wallet not relevant 

### Severity

Very Severe

**Comment by anaamolnar** [comment]
Hello, @mo-diggity. I am sorry for missing this. Please make sure you update manually to the latest version of the extension. You should be able to access the wallet then. 
https://support.mozilla.org/en-US/kb/how-update-add-ons#:~:text=Click%20More%20to%20see%20the,manual%20updates%20for%20that%20extension

Feel free to reopen this if the issue continues to occur! Thank you for your patience!
