### ISSUE TITLE
[Bug]: Polling Infura mainnet regardless of network settings

### ISSUE THREAD

**Issue by legobeat** [MetaMask/metamask-extension#23415]
### Describe the bug

MetaMask keeps polling `https://mainnet.infura/io/v3/${INFURA_PROJECT_ID}` despite being on a separate network with a manually configured RPC node. We do also see `eth_blockNumber` calls successfully go through to the configured custom RPC endpoint. On average ca 2-3 mainnet requests for every custom request.

This is with an account that had custom RPC configured on onboarding and never had mainnet activated.

### Expected behavior

Scheduled background RPC requests go to configured RPC node only.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/109787230/4b7d3db0-e70d-4f48-8df4-266a230eee70

### Steps to reproduce

1. Add custom provider
2. Switch to custom network
3. Inspect network tab in developer tools

### Version

`develop`

### Build type

None

### Browser

Firefox

### Operating system

Linux

**Comment by gauthierpetetin** [comment]
Thanks for reporting this @legobeat.
Closing it in favour of this existing issue: https://github.com/MetaMask/metamask-extension/issues/17040
