### ISSUE TITLE
[Bug]: Import token in @MetaMask seems to be broken for Pulsechain

### ISSUE THREAD

**Issue by NotMainstream** [MetaMask/metamask-extension#23412]
### Describe the bug

Import token in @MetaMask seems to be broken for Pulsechain? Example of Issue using Hex on Pulsechain.

WORKAROUND:
1. Open app.pulsex.com and click the IPFS Link, for example mypinata (alternatively use PulseX Server)
2. Select your token in the swap window (manage tokens to add others)
3. Click the Fox Icon
4. Click "Add token"

### Expected behavior

There should be "Token Symbol" and "Token decimal" option appearing after entering the HEX CA. It does work for the Ethereum network (see pic A) and it should show what token is imported on the next screen instead being empty (see pic B)

Seems to be happening after most recent update to version v11.11.4

### Steps to reproduce

1. Unlock wallet
2. Click "Tokens" -> "Import tokens"
3. Paste CA 0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39 (see pic 1)
-->> "Token symbol" and "Token decimal" don't appear
-->> Clicking Next brings you to an empty screen 

### Version

v11.11.4

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello, @NotMainstream. Thanks for reporting! I have passed this along to the appropriate team.
