### ISSUE TITLE
[Bug]: Metamask Expanded View Requires Password Re-entry After Browser Reopen

### ISSUE THREAD

**Issue by cryptowhizard** [MetaMask/metamask-extension#23427]
### Describe the bug

 In the Metamask Firefox extension, there exists a bug pertaining to the behavior of the password field when the Expanded View is open and the browser is reopened.

### Expected behavior

Upon reopening the browser and filling the password field in the Metamask normal view, the Expanded View should recognize the authentication status and not require the user to re-enter the password.

### Screenshots/Recordings

![metamask-bug](https://github.com/MetaMask/metamask-extension/assets/139334570/2aefbb52-96e8-473e-b242-885ec1c868bb)

### Steps to reproduce

1. Open the Metamask Firefox extension.
2. Navigate to the Expanded View.
3. Close the browser.
4. Reopen the browser.
5. Fill the password field in the Metamask normal view.

### Version

11.10.1

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by anaamolnar** [comment]
Hello, @cryptowhizard. Thanks for reporting! Could you please update manually to the latest version of the extension and let me know if this continues to occur? You will be able to update manually from your browser. Go to extensions-> Metamask->Details->Enable developer mode from the top right, then there should be a button for Updating in the top left. I am unable to reproduce this issue. Thanks!

**Comment by cryptowhizard** [comment]
Hey @anaamolnar, I've upgraded to version 11.12.2. Noticed a slight difference from the reported version: now, when I unlock in normal view, the expanded view displays the accounts list and names, but the unlocking screen is still present and need password.

**Comment by anaamolnar** [comment]
Hello @cryptowhizard Just curious, is your browser on full screen when doing this?
