### ISSUE TITLE
Confirmation re-design: add required metrics events in footer

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#23483]
Old typed sign pages have metrics events captured in footer, we need to look more into it and add metrics events to new footer in way that it can be re-used for different confirmations.

**Comment by blackdevelopa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23483?planning-poker) with Zenhub @digiwand @jpuri @pedronfigueiredo @segun

**Comment by jpuri** [comment]
I found that metrics events on footer of signed type data page are redundant and thus we do not need to port them to new designs.
