### ISSUE TITLE
[Bug]: Balance always shown in Fiat on the main screen, despite ETH being selected in setting

### ISSUE THREAD

**Issue by gauthierpetetin** [MetaMask/metamask-extension#23514]
### Describe the bug

Balance always shown in Fiat on the main screen, despite ETH being selected in setting

### Expected behavior

Balance shall be shown in ETH

### Screenshots/Recordings

<img width="354" alt="Screenshot 2024-03-15 at 07 21 08" src="https://github.com/MetaMask/metamask-extension/assets/7071180/0b81f804-be28-4a20-9e1d-48f55e7d1207">
<img width="354" alt="Screenshot 2024-03-15 at 07 21 21" src="https://github.com/MetaMask/metamask-extension/assets/7071180/085f4028-4b1e-4f5f-8ea0-9df8c7f9d18c">

### Steps to reproduce

1. Open MetaMask
2. Balance is shown in Fiat, whatever I do

### Version

11.12.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

- Regression (sev2)

**Comment by hjetpoluru** [comment]
The setting has been changed and now the currency appears as expected attached the video.https://github.com/user-attachments/assets/53eb07e8-0ac1-4a74-82aa-14640194ed10

**Comment by hjetpoluru** [comment]
Closing the ticket based on the above comment
