### ISSUE TITLE
fix: Confirmation Redesign value component tooltip

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#23512]
Tooltip is current value components is very different from our new designs, we need to fix these. It will be useful to also once check about this with snaps or other teams using these value components.

Current tooltip:

<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38bd054e39b12a27248d3846f60eb346e860cbc0/Screenshot%202024-03-15%20at%2011.41.49%E2%80%AFAM.png" alt="Screenshot 2024-03-15 at 11.41.49 AM.png" />

New designs:
<img width="941" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekRqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92e949861c797b1ee2e447d3a7d5342dcab0889c/Screenshot%202024-03-15%20at%2011.44.32%E2%80%AFAM.png" alt="Screenshot 2024-03-15 at 11.44.32 AM.png" />

Figma: https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=907-23976&mode=design&t=hfWd2n2a6ApmrSD5-0

**Comment by jpuri** [comment]
We are currently using the tooltip from component library for extension, we need to check with design system team for new tooltip component development.

**Comment by bschorchit** [comment]
Closing this for now as there's no timeline for a tooltip component - [slack thread](https://consensys.slack.com/archives/C0354T27M5M/p1724343634135389?thread_ts=1724336807.381339&cid=C0354T27M5M)
