### ISSUE TITLE
Tests failing intermittently

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2351]
Pretty much every PR initially fails these days, and requires a retry just to see if it's a real fail or not.

Some speculation is that it has to do with a bad block-tracker stub.

In any case, we need to fix this, our tests are slow enough without needing to run them multiple times per PR.

**Comment by kumavis** [comment]
I think duplicate of https://github.com/MetaMask/metamask-extension/issues/2351
are you still seeing it? PR was merged 7 hours ago

**Comment by danfinlay** [comment]
I'll close this in hopes that it's fixed, will reopen if it's not.
