### ISSUE TITLE
[Bug]: Sent NFT is not received even if autodetect is ON

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#23522]
### Describe the bug

Using the the latest code on `Develop` when sending an NFT to a different account the transaction succeeds but the NFT is not showing in the wallet of the receiving account even though autodetect is ON.

I tried on the production build and it works fine

Please see the video

### Expected behavior

The NFT is shown

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/6082863/3ebc90ce-b3c0-45cc-9790-a5e0e150b1f1

### Steps to reproduce

1. In the extension chose Sepolia or Goerli as a network
2. Go to https://metamask.github.io/test-dapp/
3. In the NFT section click on `Deploy`
4. Click on `Mint`
5. Click on `Watch NFT`
6. Wait until the transaction completes
7. Click on the NFT
8. Click on `Send` 
10. Chose a different account and confirm
11. Wait until the NFT is sent
12. Switch to the receiving account
13. Notice that the NFT is not there

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Hi @davibroc , I see on the recording this occurs on Sepolia and I don't know if the autodetection works on this network. @alfeng6 do you have more info about it?

**Comment by bergeron** [comment]
its true that autodetection is mainnet only right now

**Comment by gauthierpetetin** [comment]
Thanks @bergeron , in that case I think we can close that issue as it doesn't seem to be a bug
