### ISSUE TITLE
[Bug]: Importing token fails although it says it succeeds

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#23526]
### Describe the bug

When I see a message that `tokens have been found` in my account and click on Import I get a notification that it succeeds but I don't see the tokens in my wallet. And the message that I have tokens to import doesn't clear

See video

### Expected behavior

Token are imported succesfully

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/6082863/e6854e87-2ee1-4302-8c9a-68ae922d284d

### Steps to reproduce

1. Open Metamask using an account that has tokens to import
2. Click on Import tokens
3. Notice that the it shows it was imported successfully but tokens still not imported

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by davibroc** [comment]
Not seeing it anymore so I will close and reopen it if I see it again

**Comment by bergeron** [comment]
Should be fixed by https://github.com/MetaMask/metamask-extension/pull/23798 and cherry picked to 11.14 in https://github.com/MetaMask/metamask-extension/pull/23871
