### ISSUE TITLE
Remove the maximum limit constraint on Mantle Mainnet

### ISSUE THREAD

**Issue by zengbing15** [MetaMask/metamask-extension#23534]
### What is this about?

For instance, When Mantle's estimated gas is 269580441, altering this value triggers a prompt: "Gas limit must be greater than 20999 and less than 7920027."

Please remove this kind of maximum limit constraint.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by anaamolnar** [comment]
Hey @zengbing15. Thank you for this report! This will be looked at by the appropriate team as soon as they can.

**Comment by bschorchit** [comment]
Thank you for your report, @zengbing15! This is likely some old gas limit requirement that applied for other networks but not for your case. We'll look into this, a couple of questions to understand this better first: 
- Do you expect users to often have to manually edit the gas limit while using Mantle with MM?
- What is the current impact of those constraints? Are they causing transactions to fail?
- Is there any constraint that would apply for gas limits on Mantle?

**Comment by bschorchit** [comment]
Thank you for details @zengbing15. We're looking into this.

**Comment by zengbing15** [comment]
and please let me explain your questions. @bschorchit 
> * Do you expect users to often have to manually edit the gas limit while using Mantle with MM?
As I mentioned above, users don't need to manually edit the gas limit all the time; they only need to edit it when necessary.
> * What is the current impact of those constraints? Are they causing transactions to fail?
Users are greatly overpaying gas and also failed txs due to insufficient gas fees.
> * Is there any constraint that would apply for gas limits on Mantle?
As I mentioned above, When edit **Gas limit** , Remove the maximum value limitation of Gas limit, currently Mantle Mainnet v2 gas limit will reach a maximum value of 200,000,000,000.

**Comment by zengbing15** [comment]
Mantle will make the adjustments here, no need for Metamask to make any changes.

**Comment by zengbing15** [comment]
Hi metamask team @bschorchit 
After further investigation and validation, we hope that MetaMask will continue addressing this gas fee optimization issue.
We sincerely apologize for the changes and fluctuations in decisions. This should be the final decision, and there won't be any further alterations. Thank you for your patience.
