### ISSUE TITLE
[Bug]: MetaMask popup very slow to appear (20+ seconds)

### ISSUE THREAD

**Issue by william2313** [MetaMask/metamask-extension#23544]
### Describe the bug

Whenever I want to interact with a smart contract from a dapp, the MetaMask popup takes more than 20 seconds to load. 
This is not a recent bug, it has been occurring for at least the last 2 years in Chrome, Edge and Brave.
I have taken the following steps to try to fix this:
1. removed all unneeded accounts
2. removed any unneeded (test) networks
3. disabled all other browser extensions
4. cleared activity tab data 
5. uninstalled MetaMask extension, cleared browser cache, restarted browser and re-installed MetaMask (and imported my existing account with the secret recovery phrase)

All this had no noticeable effect. To be clear, the delay occurs on EVERY kind of smart contract transaction on all chains. (I use dozens of different well known dapps on several well known chains). In fact, I have not seen the popup appearing without delay a single time during the last 2 years.

### Expected behavior

Loading the MetaMask popup should take no more than 5 seconds for a reasonable user experience.

### Steps to reproduce

The bug description says it all.

### Version

11.12.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by Fredakikay32** [comment]
@william2313 [](url)

**Comment by Fredakikay32** [comment]
[logs_21828966765.zip](https://github.com/MetaMask/metamask-extension/files/14635456/logs_21828966765.zip)

**Comment by danjm** [comment]
@william2313 Does the bug occur when creating a non-smart contract transaction from a dapp (e.g. just a simple eth send) ?

**Comment by william2313** [comment]
@danjm  No, because that's initiated with the send button from the MetaMask UI, so the popup doesn't need to load. The send screen appears within 3 seconds.

**Comment by william2313** [comment]
Ok, I did that. "Send legacy transaction" took 20 seconds for the popup to appear (fully populated). "Send EIP 1559 tx" took 25 seconds. This was on mainnet.
