### ISSUE TITLE
Blank MetaMask

### ISSUE THREAD

**Issue by Goldie309** [MetaMask/metamask-extension#2354]
Hello! 
I just downloaded metamask for Chrome. I cant seem to open it as it just is a blank screen. I have not had a chance to enter in any information or get my seed code. Any help will be appreciated.

Thanks!
![screen shot 2017-10-12 at 6 19 30 pm](https://user-images.githubusercontent.com/32752399/31522048-f2918e6c-af79-11e7-849e-b56ed3d141e1.png)

FAQ:
  BEFORE SUBMITTING, please make sure your question hasn't been answered in our FAQ: https://github.com/MetaMask/faq
  Common questions such as "Where is my ether?" or "Where did my tokens go?" are answered in the FAQ.

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by nharlow89** [comment]
Had this happen to me earlier on Firefox. Updated Firefox and just tried again, now it seems to be working.

**Comment by danfinlay** [comment]
It could help for you to open logs to look for any red errors:
https://github.com/MetaMask/faq/blob/master/LOGS.md
