### ISSUE TITLE
Confirmation redesign - add preference flag for re-designed signature request pages

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#23554]
User should be able to access redesigned pages if preference is enabled.

[Figma design](https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=1720-12461&mode=design&t=Dayzg9Q0KNS1Ax51-0) (still needs copy)

<img width="542" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7bf4e6f28016968e5e623aa05c8ca4c0a1d1958/Screenshot%202024-04-11%20at%2018.17.09.png" alt="Screenshot 2024-04-11 at 18.17.09.png" />

**Comment by digiwand** [comment]
Confirmation Secure UX Discussion:
- Hide setting behind ENV flag
- Hide redesign signature features behind settings flag

**Comment by digiwand** [comment]
Confirmation Secure UX Discussion:
- Hide setting behind ENV flag
- Hide redesign signature features behind settings flag

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23554?planning-poker) with Zenhub @pedronfigueiredo @cryptotavares

**Comment by pedronfigueiredo** [comment]
- Adding e2e test for toggling the setting
- UI work
- Adding new properties on the preferences controller
- Unit tests
- Adding selector and action

**Comment by digiwand** [comment]
- plan to create separate ticket for metrics
