### ISSUE TITLE
[Bug]: Wallet fails to indicate user is signing a non-existing contract

### ISSUE THREAD

**Issue by avious00** [MetaMask/metamask-extension#23568]
### Describe the bug

User was signing an interchain token transfer intended from inEVM, but due to a wagmi.sh network switching issue, ended up on [zkSync](https://explorer.zksync.io/tx/0xa426bda761ac2e77198fd373b17c6e1c77e1592c03ebfee826bec9ff1aeeefc8). Metamask failed to prompt the user that they were signing a non-existing contract.

This issue has occurred multiple times with different users, causing meaningful financial loss:
zkSync etherscan: https://explorer.zksync.io/address/0x26f32245fCF5Ad53159E875d5Cae62aEcf19c2d4
Etherscan: https://etherscan.io/address/0x26f32245fCF5Ad53159E875d5Cae62aEcf19c2d4

### Expected behavior

Indicate the presence of calldata for a call to a non-existing contract, and prevent users from signing non-existing contracts.

### Steps to reproduce

https://discord.com/channels/935678348330434570/1217928354871640187/1217928354871640187

### Version

Unknown

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by avious00** [comment]
Opened issues with underlying library + wallet here:
Wagmi https://github.com/wevm/wagmi/issues/3720
Metamask https://github.com/MetaMask/metamask-extension/issues/23568

**Comment by pedronfigueiredo** [comment]
Thanks for reporting this, @avious00. I can't open the reproduction steps on Discord. Can you clarify what server and channel this is reported on and include an invite link, if possible, so that we can look into it?

**Comment by bschorchit** [comment]
Could you add the reproduction steps to this issue @avious00 ?

**Comment by bschorchit** [comment]
This seems to be an issue caused by not properly triggering a network switch request ahead of the transaction request as reported [here](https://github.com/wevm/wagmi/issues/3720). For this reason I removed the bug label as it's not a MetaMask bug, but I'm keeping this issue open as a feature request as we do want to consider this for a potential improvement to the wallet.

**Comment by avious00** [comment]
hey @bschorchit @pedronfigueiredo appreciate the quick response here

in the reproduction section, linked the discord report of a user who experienced this problem.

the rough steps to reproduce are:
1. Visit https://www.usenexus.org/ - a bridging UI for Hyperlane
2. Attempt a transaction while being on zkSync Era
3. This should usually automatically switch over because of our use of the wagmi lib, but this can fail. Users usually don't catch that this has not gone through.
5. If this failure mode occurs, which it has for a meaningful amount of our users and I assume other defi apps, a tx gets submitted by MM to a non-existent contract, burning their fees. 

Regardless of the contract switching bug (which isn't material here), MM should in general prevent tx being signed to non-existent contracts.

**Comment by bschorchit** [comment]
Closing in favor of: https://github.com/MetaMask/MetaMask-planning/issues/2926
