### ISSUE TITLE
[Bug]: MetaMask displaying the wrong price of Mantle Mainnet L2 MNT

### ISSUE THREAD

**Issue by zengbing15** [MetaMask/metamask-extension#23596]
### Describe the bug

When using Metamask add the Mantle Mainnet.
The USD price corresponding to MNT is incorrect.

### Screenshots/Recordings

<img width="359" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/40650475/e63da943-7f22-46d5-a23f-ff69bc428aad">

### Steps to reproduce

1. add Mantle Mainnet Network: https://docs-v2.mantle.xyz/devs/dev-guides/quick
2. There are MNT tokens in the account. 

### Version

11.11.4 and all other Metamask versions

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @zengbing15. Thanks for reporting! I will pass this on to the appropriate team!
