### ISSUE TITLE
[Bug]: Gas - Optimism max gas missmatch and scientific notation

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23601]
### Describe the bug

**Problem:** there is a gas miss-match between max fees and max total when not sending 
Ex. in Sending an ERC20 the max fee and max amount should the same for the ETH in this case. However I see those 2 values different:

- Max fee: 0.00000146 ETH
- Max amount: 345 DAI + 0.000001336 ETH 

I've seen also occasionally scientific notation in the total max amount :thinking_face:

### Expected behavior

- Max fee and max amount should be consistent
- We should not display scientific notation

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/05b3b653-b118-459c-92de-35eb6565e458)

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/191b9c1e-5106-41ba-b08f-7999fbbd86a1)

### Steps to reproduce

1. Select Optimism
2. Start a SendERC20
3. See gas

### Version

11.12.2 prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
Note: there's this PR from Dan which attempts to fix it, but the work should be finalized (fix ci etc)
https://github.com/MetaMask/metamask-extension/pull/23549

**Comment by pedronfigueiredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23601?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by jpuri** [comment]
<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24024d8c590f6a1eb98f740b21353e0c8944bc4c/Screenshot%202024-04-25%20at%205.58.11%E2%80%AFPM.png" alt="Screenshot 2024-04-25 at 5.58.11 PM.png" />

Hey @seaona , it looks good in latest code.
