### ISSUE TITLE
Create GitHub action to inform users about the ongoing confirmation redesign

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#23626]
## Context

We want to inform any users touching confirmations code that we are supporting both old and new pages for an indefinite period of time.

Unfortunately, blocking changes to the old pages entirely is not practical because bugs might need to be addressed, or new features might need to be added in both old and new pages. In some cases we will want to add features to the old pages only (for example for the upcoming work on Alerts by the Confirmation System team).

## Solution [WIP]
We can add a GitHub comment or a [job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) with information about the ongoing redesign, and an ask to work with the Confirmation UX team to not break feature parity.

[@actions/core npm package reference](https://www.npmjs.com/package/@actions/core)

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23626?planning-poker) with Zenhub @cryptotavares @pedronfigueiredo

**Comment by pedronfigueiredo** [comment]
Confirm that codeowners are blocking changes to PRs that touch `ui/pages/confirm` without approvals from confirmation teams
