### ISSUE TITLE
Extension Blockaid validations : request left in loading state

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#23621]
This is a relatively frequent issue in extension and I could replicate it locally. Result of blockaid validation is not updated in the transaction and transaction is left in loading state of PPOM validation for ever.

**Comment by seaona** [comment]
I've encountered this for Linea. Unfortunately in this case, I don't see any errors in the console :thinking: 


https://github.com/MetaMask/metamask-extension/assets/54408225/64ef51cb-4258-4340-a9c0-1a9e61e822d5

**Comment by jpuri** [comment]
I also encountered this for linea when validation was completed without errors.

**Comment by jpuri** [comment]
I also encountered this for linea when validation was completed without errors.

**Comment by jpuri** [comment]
I could not replicate the issue, thus closing it.
