### ISSUE TITLE
[e2e] PPOM - Add spec for testing a cdn files update

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23641]
### What is this about?

Add spec for testing a cdn files update.

This should be done after those are closed:
- https://github.com/MetaMask/metamask-extension/issues/23639
- https://github.com/MetaMask/metamask-extension/issues/23640

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by cryptotavares** [comment]
Test flow:
trigger Confirmation -> check that cdn requests to fetch files v1 were done -> update cdn files -> trigger another confirmation -> check that cdn requests to fetch files were done to v2

**Comment by bschorchit** [comment]
Closing this as we'll be moving to security alerts API soon and these tests will no longer be needed.
