### ISSUE TITLE
Review PetNames component styles

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#23652]
<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a570ae8d42dd2982bd30d61ac04f3fecc9ad084/petnames-layout.png" alt="petnames-layout.png" />

[More context here](https://consensys.slack.com/archives/C04C0F6SSJH/p1711115620518119?thread_ts=1711109007.601559&cid=C04C0F6SSJH)

**Comment by bschorchit** [comment]
Closing as there are other style review being planned for petnames
