### ISSUE TITLE
[Bug]: MetaMask can't fetch token symbol for local development network such an anvil for foundry

### ISSUE THREAD

**Issue by EggsyOnCode** [MetaMask/metamask-extension#23657]
### Describe the bug

During develoopment, I often connect my local anvil chain (foundry) with my metamask wallet to test functionality in my web3 app. Today, when i imported some dummy accounts from anvil to metamask; it is unable to read the token symbol and hence metamask labels anvil as scam and doesn't allow testing as intended.

The error thrown is the following:
`This network doesn't match its associated chain ID or name. Many popular tokens use the name GO, making it a target for scams. Scammers may trick you into sending them more valuable currency in return. Verify everything before you continue.`

### Expected behavior

MetaMask should be able to fetch the local node's chainid and token symbol and correctly load the dumy account's balance in the correct token and allow interactions as normal.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/77304003/79f83c28-2e8b-41ce-8de7-bb53621a4061)

![image](https://github.com/MetaMask/metamask-extension/assets/77304003/25774b80-c445-4138-8cf5-64b748b149a5)

### Steps to reproduce

1. Add a local dev node such as hardhat or anvil for foundry such as this 
> 
![image](https://github.com/MetaMask/metamask-extension/assets/77304003/d555714b-cff4-463c-82ee-1a0bd16660b5)

2. Import a dummy account from anvil using their private key 
3. Check to see if the corresponding tokens (for anvil its 100ETH) get recognized and loaded into metamask extension.

### Error messages or log output

```shell
The error thrown is the following:
`This network doesn't match its associated chain ID or name. Many popular tokens use the name GO, making it a target for scams. Scammers may trick you into sending them more valuable currency in return. Verify everything before you continue.`
```

### Version

11.12.2

### Build type

None

### Browser

Firefox, Brave

### Operating system

Linux

**Comment by EggsyOnCode** [comment]
# A workaround

Go to Setting>General>Pirmary Currency 

Set it to `Fiat` and then remove the local testnet node and re-add it to the extension

**Comment by DanielTech21** [comment]
Hi @EggsyOnCode 

Thanks for bringing this issue to us.

We will review it and fix it.
