### ISSUE TITLE
Does Metamask resubmit transactions automatically?

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#2366]
Sorry if this is somewhere in the docs, I could not find it if it is.  I'm also not sure if it's an Etherscan issue or not, or if it's just something fundamental about how the eth blockchain works that I'm not understanding.

All that said -- Does Metamask automatically submit transactions to the network?  Under what conditions does it resubmit transactions? 

> Expected Behavior

Example transaction: https://etherscan.io/tx/0xd4378ee0e4ea94e141a31103a11625daa757f998977ff254baea2e645f606434

This transaction was submitted last night at 11pm MST (about 18 hours ago).  It has a super low gas price and no confirmations.   Etherscan should show that timestamp as the submission time.

>  Actual Behavior

Etherscan seems to show 30 minus ago as the submission time for this transaction, and seems to reset the submission time periodically http://bits.owocki.com/0D1C060P2t0r/Image%202017-10-13%20at%204.03.18%20PM.png

>  Browser Used

Chrome

>  Operating System Used

OS X

>  Screenshots are very helpful and will expedite your issue being resolved!

This is the only screenshot I have, its of Etherscan today at 3pm (ish) MST

http://bits.owocki.com/0D1C060P2t0r/Image%202017-10-13%20at%204.03.18%20PM.png

cc @cmditch

**Comment by owocki** [comment]
From https://github.com/MetaMask/metamask-extension/issues/1652

> We resubmit every 10 seconds up to 200 times until we mark it as "giving up submitting tx". However, this does not necessarily mean that your transaction won't reach the network, it means we as a client have stopped attempting to push requests for submission. We will be working on better UI for this in the future.

Whats confusing to me WRT this specific issue is that I'm seeing behaviour that could be characterized as "resubmission" 18 hours later, presumably more than the 10 * 200 = 2000 seconds later quoted above.

**Comment by Zanibas** [comment]
The short answer is yes: we resubmit transactions, but @kumavis or @flyswatter can give a few more details on the conditions for resubmission.

**Comment by danfinlay** [comment]
That answer is no longer accurate. To get the most accurate info, you should refer to our [resubmit logic](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/lib/pending-tx-tracker.js#L104). Currently we retry on each new block for 24 hours, and then mark the transaction failed with a warning that we gave up resubmitting, allowing the user to submit a fresh transaction with that nonce.

**Comment by danfinlay** [comment]
The "buggy behavior" you're describing is an issue with Etherscan, and how it manages its pending tx mempool. We have no control over that, and there isn't even any good way for them to know the absolute time of submission, only the first time they remember seeing it, and when they finally saw it mined.

While we could document our resubmit logic better, we're improving it constantly, so I think that's a better use of our time atm.

Closing since it's not a MM issue.

**Comment by owocki** [comment]
thanks for letting me know @Zanibas @danfinlay .  this is super useful!

gas prices have been super low since the HF and hopefully gas prices stay below 1 gwei for the foreseeable future, and this wont be an issue at all

**Comment by cmditch** [comment]
Indeed, very good to know, thanks!
