### ISSUE TITLE
[Bug]: Transactions might be marked as 'Failed' while they are successfully confirmed according to the block explorer

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23660]
### Describe the bug

In instances where a low gas fee is chosen through Advanced settings, transactions might be marked as 'Failed' within MetaMask, yet they are successfully confirmed according to the block explorer. Failed transaction nonce is suggested in the custom nonce field for the next created transaction.

### Expected behavior

The transaction status shown in the MetaMask UI should be consistent with the information on the block explorer.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/52f33d86-b342-4bf2-91ad-fa30b9b28e14

<img width="904" alt="Screenshot 2024-03-22 at 6 03 48 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/935edec6-6841-4e6a-9c86-b759558e105b">
<img width="823" alt="Screenshot 2024-03-22 at 6 04 36 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/3bdf8283-b6e9-47af-bc7d-c9fc9f4e0abe">

<img width="704" alt="Screenshot 2024-03-22 at 6 05 21 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/0bc9c386-f108-4217-b6da-a8fbac58ce65">

While there are no error messages appearing in the background console, you might occasionally encounter unexpected error notifications within the 'Settings' area:
<img width="510" alt="Screenshot 2024-03-22 at 5 04 57 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/845589ef-8516-4dbb-b04a-7c391b793c34">
Sometimes transaction fails with the notification "Already known".

### Steps to reproduce

1. Start 'Send' transaction
2. Click 'Next'
3. On the Confirmation screen set low gas fee (i.e. 0.01 / 0.0001) via Advanced gas settings
4. Confirm transaction
5. In roughly one out of every ten cases, the transaction may fail (while block explorer will show successful transaction). Speeding up the transaction can be useful to reproduce the bug.

 State logs:
[MetaMask state logs.json](https://github.com/MetaMask/metamask-extension/files/14733814/MetaMask.state.logs.json)

### Version

Dev build from `develop`

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
I see the same issue on this [branch](https://github.com/MetaMask/metamask-extension/pull/23717) but this time I didn't set low gas fee through 'Advanced' settings. Transactions marked as 'Failed' in the MM were send with 'Market' and 'Aggressive' gas settings:


https://github.com/MetaMask/metamask-extension/assets/104780023/0edbe322-1285-4564-9291-62bb943d50a7

**Comment by gauthierpetetin** [comment]
Duplicate issue: https://github.com/MetaMask/metamask-extension/issues/24784

**Comment by dbrans** [comment]
@sleepytanya I believe this was fixed by https://github.com/MetaMask/core/pull/4255 and should no longer be happening. 

Could you verify this issue is fixed and close it?

**Comment by sleepytanya** [comment]
@dbrans 
Confirming it is not happening anymore, at least I wasn't able to reproduce it. Low gas transactions stays in 'Pending' state for hours until user speed up / cancel it.
