### ISSUE TITLE
Get working on Android Firefox

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2367]
Android Firefox has extension support, so this should be feasible, but apparently doesn't work yet.

**Comment by bogdoslav** [comment]
It work for me at Android Firefox, but does not shows pop-ups when I make transaction from  DAPP webpage - I have to switch to Metamask extension then Submit transaction from there.

**Comment by danfinlay** [comment]
Wow, it’s awesome that it works at all! Makes me want to get an android dev device.

**Comment by Gudahtt** [comment]
The last time I tested this (a few months ago now), MetaMask _did_ work on Firefox mobile, but not very well. The main problem I encountered was UI designed for fullscreen (e.g. onboarding) not working well on mobile.

Firefox v82 has disabled support for _most_ extensions, including MetaMask, so I can't test this anymore. I can see from usage metrics that some users are still using Firefox mobile v81 to use the MetaMask extension though. We may be able to apply to be approved as a Firefox Mobile extension as well.

**Comment by leafcutterant** [comment]
@Gudahtt what's the criterion to be accepted for Firefox v82+?

**Comment by brad-decker** [comment]
with Mobile now going strong on android and iOS do we need to progress this any further or can we close? @Gudahtt

**Comment by Gudahtt** [comment]
I think we can close this. The extension doesn't work on mobile Firefox today.

**Comment by eboye** [comment]
Is this a done deal or is there any hope of FF mobile being supported. It would be much better to use the daily browser with MM wallet and not having to switch to MM app to login etc via wallet.
