### ISSUE TITLE
[Bug]: Confirmations Re-design -  Sign Typed Data signature not using Re-design components

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23688]
### Describe the bug

The Signed Typed Data signature is not using the new re-design components. I think we should also use it in this signature type?

![Screenshot from 2024-03-25 10-33-09](https://github.com/MetaMask/metamask-extension/assets/54408225/c8f341bb-5bf7-42d0-a1b4-b16dd9c4092e)

### Steps to reproduce

1. Build the re-design
2. Trigger a typed signature

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
Hey @seaona : this should be fixed after the PR is merged: https://github.com/MetaMask/metamask-extension/pull/23539
