### ISSUE TITLE
[Bug]: Security alerts using incorrect alignment and wrong toggle placement

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23684]
### Describe the bug

~~Blockaid has disappeared from Security and privacy settings~~
The statement above is incorrect.
See comments. 

UPDATE: the scope of this ticket is only to fix the alignments and toggle

### Screenshots/Recordings

![Screenshot from 2024-03-25 09-40-15](https://github.com/MetaMask/metamask-extension/assets/54408225/b40b6b86-88a2-4fea-bc7f-eb0cd86345ed)

### Steps to reproduce

1. Go to Privacy Settings
2. See there is no Blockaid option there

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I see `Security Alerts` within the settings. The title might be using the wrong text color though? cc: @SayaGT

**Comment by SayaGT** [comment]
Yes all the secondary titles seem to be using Text muted instead of text alternative. Can we switch it to text alternative please?

**Comment by bschorchit** [comment]
I've created an issue for the wrong color being used here: https://github.com/MetaMask/metamask-extension/issues/23696

**Comment by seaona** [comment]
thank you for the replies!
@bschorchit in which version are you seeing it in settings? I do see it in prod, but not on the current `develop` branch :thinking:

**Comment by seaona** [comment]
oh I just see it now :open_mouth:  woooow how a color change can have this effect? Maybe I need to renew my glasses too :laughing:

**Comment by bschorchit** [comment]
The security alerts toggle also seems to have a different placement than the others

**Comment by pedronfigueiredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23684?planning-poker) with Zenhub @jpuri @segun @blackdevelopa @digiwand @seaona
