### ISSUE TITLE
[Bug]: Confirmations Re-design - Not able to Sign Typed v4 with a Hardware Wallet and HW warning missing

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23687]
### Describe the bug

I am not able to perform a typed 4 signature when using a hardware wallet: the Confirm button remains disabled.
Furthermore, I am not seeing any info regarding using the hardware wallet like we used to do. Should we also see it here?

![Screenshot from 2024-03-25 10-35-47](https://github.com/MetaMask/metamask-extension/assets/54408225/8d87682f-b487-4bb6-a1c3-d80b104532fd)

This is the prod warning we see (maybe the warning should be tackled within the Notification work)

![Screenshot from 2024-03-25 10-38-45](https://github.com/MetaMask/metamask-extension/assets/54408225/d504d6fe-21f7-40f9-b907-7a8063bd80c8)

### Steps to reproduce

1. Build the re-design
2. Trigger a typed signature

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
I think the scope of this task should be to fix the Signature functionality as it's broken now.
The warning can be handled in the ticket above.

Wdyt?

**Comment by jpuri** [comment]
Agreed warning banner will be covered by this task: https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-extension/22743
