### ISSUE TITLE
[Bug]: Confirmations Re-design - Signatures Navigation problems when mixing with Transactions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23692]
### Describe the bug

Whenever I trigger a couple of signatures, together with a transaction, I can see how
- the navigation displays the total of Signatures + Transactions
- I cannot navigate to the Transaction, only Signatures --> I think this should be possible. However, in current develop the behaviour is different: we don't mix tx with signatures and they popup in a "different window", meaning when you reject all, you affect all signatures and then tx appear
- If I reject the first Signature, I see that the navigation number is set to 0 incorrectly --> I think this should be fixed
- Reject all, reject both the Tx and Signatures

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/7e52aa4e-c043-4e72-ae34-c2e54d2a17c4

### Steps to reproduce

1. Trigger a couple of signatures
2. Trigger a couple of tx
3. Go to the page 1
4. Reject signature
5. See  you are in the page `0` in the navigation -- this shouldn't be the case
6. Navigate
7. See how page 0 disappears
8. Try to navigate to the transactions -- this is not possible

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
Hey @seaona : the new designs as I understand treats signatures and transactions alike. Navigation between signatures and transactions was broken I fixed that - pt-3 above.

Can you plz confirm @SayaGT

**Comment by SayaGT** [comment]
Yup @jpuri to the user it is a confirmation. So they should be treated the same when it comes to navigation or collective actions (reject all).
