### ISSUE TITLE
[Bug]: Confirmations Redesign - Account Balance displays incorrect currency

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23690]
### Describe the bug

My primary selected currency is ETH but in the Account balance details I can see the balance displayed in fiat.

### Screenshots/Recordings

![Screenshot from 2024-03-25 10-23-32](https://github.com/MetaMask/metamask-extension/assets/54408225/987dbdc9-8c1b-47c5-aecc-875a5a9fde16)

### Steps to reproduce

1. Build the re-design
2. Trigger a typed 4 signature
3. Check Account details
4. See balance is in USD instead of ETH (primary currency selected)

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by digiwand** [comment]
ui/components/app/user-preferenced-currency-display/user-preferenced-currency-display.component.js might be a helpful component here
