### ISSUE TITLE
[Mascara] Seed Phrase Screen - Scrolling Header Covers Back Button

### ISSUE THREAD

**Issue by sdtsui** [MetaMask/metamask-extension#2371]
Expected Behavior: when scrolling, all UI elements should remain visible + active.
Actual Behavior:
![mascara-scrolly-thing](https://user-images.githubusercontent.com/8230144/31579442-849700c2-b104-11e7-9541-becbaaaa1640.gif)
`Chrome 61.0.3163.100`
`macOS Sierra 10.12.6`

/cc @frankiebee @chikeichan @tmashuang

**Comment by whymarrh** [comment]
Mascara isn't being actively developed right now
