### ISSUE TITLE
[Bug]: PPOM - All validations fail on Base network when performing any contract interaction. Error: `String("over rate limit")}`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23728]
### Describe the bug

All validations fail on Base network when performing any contract interaction. Error: `String("over rate limit")}`

### Expected behavior

Validations should work.

### Screenshots/Recordings

![Screenshot from 2024-03-26 15-42-56](https://github.com/MetaMask/metamask-extension/assets/54408225/348d04cb-eb2d-4bf8-bbe5-87ea3bf9b838)

### Steps to reproduce

1. Select Base Mainnet
2. Trigger any malicious contract interation (approve, transfer setApprovalForAll)
3. See validation fails and error in the console.

### Error messages or log output

```shell
Error validating JSON RPC using PPOM:  Error: simulation: (code: -32603, message: , data: Some(Object {"cause": Null, "error": Object {"code": Number(-32016), "message": String("over rate limit")}, "id": Number(7550174764223937), "jsonrpc": String("2.0")}))
```
```


### Version

11.14.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

**Comment by seaona** [comment]
Now I'm seeing a different error `Error validating JSON RPC using PPOM:  Error: simulation: (code: -32603, message: , data: Some(Object {"cause": Null, "error": Object {"code": Number(-32001), "message": String("rpc method is not allowed")}, "id": Number(676544233823505), "jsonrpc": String("2.0")}))`


![Screenshot from 2024-04-08 14-15-08](https://github.com/MetaMask/metamask-extension/assets/54408225/987a50d7-2af2-4c4f-bbee-d4132b904e46)

**Comment by bschorchit** [comment]
Closing as this has been solved :)
