### ISSUE TITLE
[Bug]: Gas - Base network displays fees for L1 and for L2 displays `Optimism` as the L2 network name

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23723]
### Describe the bug

**Problem:** whenever I am using Base network, I can already see the fee split into the 2 layers: for mainnet (L1) and L2. However, on the L2 name it states `Optimism`.

Context: there is [some pending work ](https://github.com/MetaMask/metamask-extension/issues/20012)for splitting fees with L1 and L2s. However, I would expect, to not display the split at all, if this work is not yet ready. This only happens to Base, from the list of the pending nets support for L1/L2 split

### Expected behavior

Either we don't display the network fee split or display it and show the correct L2 name

### Screenshots/Recordings

![Screenshot from 2024-03-26 15-20-59](https://github.com/MetaMask/metamask-extension/assets/54408225/ee37595e-44dc-4eac-8b50-05506121473d)

### Steps to reproduce

1. Select Base network
2. Trigger a tx
3. See fee detils --> See L1 and Optimism

### Version

11.13.0 prod maybe earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
We should display `Layer 2` instead of `Optimism` whenever we split the gas fee. 

My understanding is that we're already estimating and splitting it correctly for Base, but not naming it properly.

**Comment by cryptotavares** [comment]
@seaona I am closing it as this was fixed on this [PR](https://github.com/MetaMask/metamask-extension/pull/23991).
