### ISSUE TITLE
[Bug]: `Got it` button style seems incorrect: letters were white now are black, degrading readability

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23725]
### Describe the bug

The  `Got it` button style for the network switch popup, seems incorrect: letters were white now are black, degrading readability

### Expected behavior

I think the button letters should continue to be white for light theme?

### Screenshots/Recordings

Now:
![Screenshot from 2024-03-26 15-22-13](https://github.com/MetaMask/metamask-extension/assets/54408225/dbf5df75-14eb-4dc9-b501-b9292e143643)

Before:
![Screenshot from 2024-03-26 15-35-36](https://github.com/MetaMask/metamask-extension/assets/54408225/d608713d-2044-4ad8-85b6-8a1a860a1110)

### Steps to reproduce

1. Select Light theme
2. Switch networks for the first time --> see Got it text

### Version

11.14.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by hjetpoluru** [comment]
@micaelae, could you please take a look.

**Comment by micaelae** [comment]
published the fix in this PR: https://github.com/MetaMask/metamask-extension/pull/23988

can I get an approval please? @hjetpoluru
