### ISSUE TITLE
[Bug]: Simulations - I get an error for Contract Deployment tx types `There was an error loading your estimation.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23731]
### Describe the bug

Whenever I'm trying to deploy a contract I see the error `There was an error loading your estimation.` on transaction simulation.

[Edit] This seems to affect only Sepolia

### Expected behavior

- if we don't support contract deployment simulations yet -- display some message around it? / dont' display simulations at all?
- if we do support it, error must be investigated

Note: contract deployments could also hide malicious behaviors, so it should be ideal to also run simulations to contract deployments

### Screenshots/Recordings

![Screenshot from 2024-03-26 15-54-27](https://github.com/MetaMask/metamask-extension/assets/54408225/031a4ef1-e19c-490b-ada8-4661d8be1c21)

### Steps to reproduce

1. Go to the test dapp
2. Trigger a contract deployment
3. See error

### Version

11.14.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by cryptotavares** [comment]
@seaona have you run the test on sepolia? Currently there's an ongoing issue with simulating any trx on sepolia. Can you test this on another network?

**Comment by seaona** [comment]
hi @cryptotavares I confirm this seems to be only a Sepolia issue. If I try a deploy contract on Mainnet simulations work fine. Feel free to close the issue, if the Sepolia issue is captured somewhere else. Thank you v much :pray:
