### ISSUE TITLE
[Bug]: Unable to Access MetaMask Wallet after Network Issues

### ISSUE THREAD

**Issue by mo-bay** [MetaMask/metamask-extension#23737]
### Describe the bug

I am encountering an issue with my MetaMask wallet on Ubuntu using the Chromium browser. My wallet was working fine, and I was connected to the base network. However, when I attempted to send a transaction, it failed due to network issues on the base network. I tried sending the transaction twice, and later discovered the network was indeed facing issues.

To resolve the problem, I restarted the browser and attempted to reload MetaMask. However, I'm now stuck in a loop where MetaMask does not prompt me for my password. Instead, I'm seeing the following errors in the JavaScript console:

### Expected behavior

MetaMask should prompt me for my password and load properly even after network issues and browser restart.

### Screenshots/Recordings

![Screenshot from 2024-03-26 20-36-48](https://github.com/MetaMask/metamask-extension/assets/40464904/5daca1b6-eb7b-4752-834d-2a10ba32e009)

### Steps to reproduce

1.     Connect to the base network with MetaMask.
2.     Attempt to send a transaction.
3.     Encounter network issues during the transaction.
4.     Restart the browser.
5.     Attempt to reload MetaMask.
6.     Observe the loop behavior and errors in the JavaScript console.

Note:
This issue may not be consistently reproducible and could be specific to certain network conditions or browser states.

### Error messages or log output

```shell
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN
runtime-lavamoat.js:4079 Removing unpermitted intrinsics
use-snow.js:23 Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. Window {window: Window, self: Window, document: document, name: '', location: Location, …}
use-snow.js:23 Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. Window {window: Window, document: document, location: Location, …}
sentry-install.js:1 Property eval will not be hardened because it is scuttled by LavaMoat protection. Visit https://github.com/LavaMoat/LavaMoat/pull/360 to learn more.
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
warn @ runtime-lavamoat.js:6929
(anonymous) @ lockdown-more.js:74
protectIntrinsics @ lockdown-more.js:44
(anonymous) @ lockdown-more.js:97
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#1)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:6929
handleRejection @ runtime-lavamoat.js:7285
finalizeDroppedPromise @ runtime-lavamoat.js:7058
sentry-install.js:1 Error#1: Corruption: block checksum mismatch
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6890
logSubErrors @ runtime-lavamoat.js:6833
error @ runtime-lavamoat.js:6931
handleRejection @ runtime-lavamoat.js:7285
finalizeDroppedPromise @ runtime-lavamoat.js:7058
sentry-install.js:1   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:1:203965

e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6912
logSubErrors @ runtime-lavamoat.js:6833
error @ runtime-lavamoat.js:6931
handleRejection @ runtime-lavamoat.js:7285
finalizeDroppedPromise @ runtime-lavamoat.js:7058
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:6929
handleRejection @ runtime-lavamoat.js:7285
finalizeDroppedPromise @ runtime-lavamoat.js:7058
sentry-install.js:1 Error#2: Corruption: block checksum mismatch
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6890
logSubErrors @ runtime-lavamoat.js:6833
error @ runtime-lavamoat.js:6931
handleRejection @ runtime-lavamoat.js:7285
finalizeDroppedPromise @ runtime-lavamoat.js:7058
sentry-install.js:1   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:1:203965

e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6912
logSubErrors @ runtime-lavamoat.js:6833
error @ runtime-lavamoat.js:6931
handleRejection @ runtime-lavamoat.js:7285
finalizeDroppedPromise @ runtime-lavamoat.js:7058
```

### Version

11.12.4

### Build type

None

### Browser

Chrome, Other (please elaborate in the "Additional Context" section)

### Operating system

Linux

### Additional context

- OS: Ubuntu
- Browser: Chromium

**Comment by anaamolnar** [comment]
Hello, @mo-bay. Thanks for reporting! Are you still getting the same issue after updating to the latest version? You will be able to update manually from your browser. Go to extensions-> Metamask->Details->Enable developer mode from the top right, then there should be a button for Updating in the top left. Thanks!

**Comment by SartajHundal** [comment]
Very similar problem with the Swift version of the app; could be session management? Session information persistence not largely defined yet (at least what I can see in this repo).
