### ISSUE TITLE
[Bug]: Blockaid False Positive

### ISSUE THREAD

**Issue by gramanicu** [MetaMask/metamask-extension#23752]
### Describe the bug

Users of our revenue sharing system (https://revshare.coinracer.io/) are reporting that they receive the following message when attempting to send tokens to the revenue share smartcontract:

> This is a deceptive request. If you approve this request, a third party known for scams might take all your assets.

![image](https://github.com/MetaMask/metamask-extension/assets/23612572/65a07b14-0369-4743-b8bc-750a8af2bcdd)

All our smartcontracts are verified:
- ether revshare - https://etherscan.io/address/0xB208222089e9c48F3a0680b91Be5a79D79aD429E
- ether token - https://etherscan.io/address/0x1c92c0295807F1f7C0726cf51A1D26298563F14A
- bsc revshare - https://bscscan.com/address/0xDc26B7f663f1a9Ed7eD7da474B36D3f9677B9a35
- bsc token - https://bscscan.com/address/0x7342717afb1F0C23153fE506Dc70164204Abb7a1

Is it something more we should do to ensure this message will not appear anymore? Or is it an issue with blockaid?

### Steps to reproduce

This isn't something that happened to everyone (and not always on both chains). However, as a general direction, this happens when:
1. Go to https://revshare.coinracer.io/
2. Connect your wallet ("Step 1" box)
3. Select one of the chains ("Step 1" box)
4. Enter a token amount in the input and click deposit ("Step 2" box)

### Version

11.12.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

The revshare system is a new part of the Coinracer game (https://coinracer.io/)

**Comment by anaamolnar** [comment]
Hello, @gramanicu. Thank you for your report. Could you click the Report an issue within the warning and submit the form? That's the quickest way to have such issues addressed. Furthermore, can you please ensure you are still experiencing this after updating to the latest Metamask version, 11.13.0? You will be able to update manually from your browser. Go to extensions-> Metamask->Details->Enable developer mode from the top right, then there should be a button for Updating in the top left. Thank you!

**Comment by gramanicu** [comment]
Thank you for your quick response.

I updated my metamask version to the latest. The issue persists. 

However, one thing I noted is the fact that this does not happen if I activate "Opensea + Blockaid". 
I have also sent an issue report through the "Report an issue" form.

**Comment by anaamolnar** [comment]
Hey @gramanicu This should be all resolved now. Feel free to reopen this if that is still not the case. Have a nice day!
