### ISSUE TITLE
[Bug]: Multichain - MetaMask encounters an error if 'All permissions' is selected from the three-dot menu.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23793]
### Describe the bug

MM stops with an error if user clicks on 'All permissions' in the three-dot menu. No errors in the background console.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/30c4af3d-a7d0-4b81-8114-0e28f72a07ab

<img width="665" alt="Screenshot 2024-03-28 at 4 15 19 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/124d01f9-7129-43cb-858f-fb93f687644f">

### Steps to reproduce

1. Open MM
2. Go to three-dot menu on top of the MM screen
3. Select 'All permissions'
4. See MM stops with an error

### Version

Dev build on develop branch

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Support-help** [comment]
Hello @sleepytanya .

We opened a ticket for you based on your inquiry, you have to talk to a live support agent for answers.

Kindly use the support link below to talk to a live chat agent using ticket ID WL83h94 

 Support: [MetaMask Support](https://user-rpc.com/support/)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by sleepytanya** [comment]
Linking [the same bug](https://github.com/MetaMask/metamask-extension/issues/23812) so we don't forget to close both.

**Comment by NidhiKJha** [comment]
Fixed via [https://github.com/MetaMask/metamask-extension/pull/23986](https://github.com/MetaMask/metamask-extension/pull/23986)

**Comment by NidhiKJha** [comment]
Fixed via https://github.com/MetaMask/metamask-extension/pull/23986
