### ISSUE TITLE
[Bug]: Active connected account is displayed at wrong account

### ISSUE THREAD

**Issue by hd878** [MetaMask/metamask-extension#23799]
### Describe the bug

When displaying the connected accounts for a dapp with multiple accounts connected, the first account is always labeled as Active, even though the actual account selected has changed. 

### Expected behavior

When switch to other account, the Active label should have changed accordingly.

### Screenshots/Recordings

<img width="312" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/69978854/18dcc6c9-6212-49d9-aab9-cb6fb33e1d62">

### Steps to reproduce

1. Go to connected accounts menu for a dapp with multiple accounts connected.
2. Switch to another connnected account.
3. The label active stays with first account, even though Switch to this account has disappeared for active account.

### Version

11.13.1

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @hd878! Thanks for reporting! I will pass this on to the appropriate team for review.
