### ISSUE TITLE
[Bug]: Hardware wallet QR connection unsuccessful

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#23804]
### Describe the bug

The connection via QR code on Hardware wallet is not proceeding past scanning the QR code. Functionality is working in the release version v11.13.1. 

### Expected behavior

The QR code should be scanned and you should be taken to the next screen of selecting the hardware wallet account you wish to add to MetaMask. 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/120041701/da648f60-e044-4dd4-8e10-484f68dc4ee4

### Steps to reproduce

1. Load MetaMask
2. On your hardware wallet, fetch the QR code for MetaMask
3. Proceed to add hardware wallet from the account drop-down selector
4. Select QR-based and Continue
5. Scan the QR code from the hardware wallet 
6. Notice the QR code is scanned and nothing happens afterwards

### Error messages or log output

```shell
No console error
```

### Version

11.14.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows, MacOS

### Hardware wallet

Keystone

### Severity

Release-blocker

**Comment by vivek-consensys** [comment]
Tested using the branch `fix/23804-add-qr-connection-issue` and working as expected. 
https://github.com/MetaMask/metamask-extension/tree/fix/23804-add-qr-connection-issue


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXBHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c93709493c008b4b9a5b04dcf723e821094c9a15/Screen%20Recording%202024-04-09%20at%2013.44.15.mov)
