### ISSUE TITLE
[Bug]: Multichain: All Permissions Page Breaks in Popup

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#23812]
### Describe the bug

I tried viewing the "All Permissions" page in the popup and was immediately hit with an error.

### Expected behavior

No error, all hostnames display

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/46655/beb948ed-e959-40f9-85b9-f834c8404ccb

### Steps to reproduce

1.  Connect an account on Uniswap
2.  Open the popup
3.  Open the three-dot menu and choose "All Permissions"
4. See the error

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Linking [the same bug](https://github.com/MetaMask/metamask-extension/issues/23793) so we don't forget to close both.
