### ISSUE TITLE
[Bug]: Metamask Add-On is stuck in an endless loop and not logging in 

### ISSUE THREAD

**Issue by Zabibi45** [MetaMask/metamask-extension#23825]
### Describe the bug

I was doing a transaction on my metamask add on and in the middle of the process an electric issue occured in my home and my pc immediately shut down. Now after everything was fixed the Metamask Add-On is stuck in an endless loop and not logging in.
![Screenshot 2024-04-01 231615](https://github.com/MetaMask/metamask-extension/assets/165719785/a361b7f8-2c00-426e-99c0-7a0a7efcae20)
![Screenshot 2024-04-01 231615](https://github.com/MetaMask/metamask-extension/assets/165719785/a93556b0-4cb7-470f-8623-c3861c7172d1)

### Expected behavior

I Expected to Use my Wallet as usual 

### Screenshots/Recordings

![Screenshot 2024-04-01 231615](https://github.com/MetaMask/metamask-extension/assets/165719785/3bb7c6c4-b185-4b8b-94b1-f0b157b0c911)

### Steps to reproduce

1.Open Firefox (Windows 10) 
2.Click on the Metamask Icon in the Top right
3. Open your wallet and select a currency of your choice 
4. pull off the Plug of your PC and Internet Router 
5. Plug it back in after 2 min and Try again the first 2 Steps 
6. Enjoy the Endless Loop... No im kidding, i need to login my account immediately

### Error messages or log output

```shell
.
```

### Version

v11.12.4

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Additional context

.

### Severity

.

**Comment by Zabibi45** [comment]
Hey there, i restarted my PC multiple times and i can’t Login via Mobile Phone because i lost my secret recovery Phrase. I only have my password. I can only Login via my Firefox addon and its really  Depressing that it doesnt work anymore. When will be a new update? Maybe the Update will resolve the issue..- WarisVon meinem iPhone gesendetAm 02.04.2024 um 14:30 schrieb Sweetmind300 ***@***.***>:﻿
Hello @Zabibi45
Restart your PC
Or preferably Use Metamask app on your device instead
If the error persists….. kindly visit the official Ethereum website to report and resolve this issue.

**Comment by Zabibi45** [comment]
Hey, i am using Firefox as my main browser and my MetaMask Extension is loaded on Firefox. I am Not able to access it in any way because it is stuck in this loop. Not even trough the console was I able to get my information out of it so I could maybe decrypt it and get my Secret recovery phrase out of it. But it isn’t working and I have a shit ton of money sitting in there. Von meinem iPhone gesendetAm 02.04.2024 um 16:03 schrieb kanye west ***@***.***>:﻿Hey there, i restarted my PC multiple times and i can’t Login via Mobile Phone because i lost my secret recovery Phrase. I only have my password. I can only Login via my Firefox addon and its really  Depressing that it doesnt work anymore. When will be a new update? Maybe the Update will resolve the issue..- WarisVon meinem iPhone gesendetAm 02.04.2024 um 14:30 schrieb Sweetmind300 ***@***.***>:﻿
Hello @Zabibi45
Restart your PC
Or preferably Use Metamask app on your device instead
If the error persists….. kindly visit the official Ethereum website to report and resolve this issue.

**Comment by Virgus** [comment]
> Hi @Zabibi45
> 
> You can receive support for this technical issue by contacting us at https://support.metamask.io. From there, a member of our customer success team will be able to help investigate how to recover from this issue.

This is unbelievable: the support.metamask.io requires a working extension to be able to access the support chat. But the extension does not open if the no-password endless loop blocks the access.

So I had to use a backup of my FF browser + MM extension. A backup which unfortunately lacks of two metamask accounts. But at least now I'm in line for a person from the support team. 40 minutes waiting time so far... Unbelievable.
Wouldn't be better to allow users to send an email instead of having to wait in front of the screen for so long ?

Unbelievable !

**Comment by Gudahtt** [comment]
>This is unbelievable: the support.metamask.io requires a working extension to be able to access the support chat

The support site does not require an extension. I am unsure what you are referring to.

**Comment by gauthierpetetin** [comment]
Hi everyone, if you're still facing a similar issue, this issue is the possible cause: https://github.com/MetaMask/metamask-extension/issues/9196

**Comment by Virgus** [comment]
> Hi everyone, if you're still facing a similar issue, this issue is the possible cause: #9196

Thanks @gauthierpetetin after the initial panic I used a backup to contact the customer service and then restored the missing accounts. Next time I'll try this other solution...
