### ISSUE TITLE
User flow - cancel transaction using custom nonce feature.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23830]
### What is this about?

Create a simple "Send" transaction and cancel it by sending another transaction with the same nonce.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by justinasfour04** [comment]
I tried it on my end and it doesn't work anymore, I can't even speed up a transaction anymore either

**Comment by sleepytanya** [comment]
@justinasfour04 
Thank you for reaching out! 
ThisPR primarily provides a detailed description of the user flow. It's designed to offer a clear and comprehensive overview of the steps and interactions a user can expect. 
If you're encountering difficulties with accelerating or canceling transactions using the MetaMask wallet, we encourage you to submit a [bug report here](https://github.com/MetaMask/metamask-extension/issues). Please specify whether you're using the MetaMask extension or the mobile app. Additionally, including the MetaMask version and the type of device you're using (if you're on the mobile app) will greatly assist us in diagnosing and addressing the issue more efficiently.
Thank you!
