### ISSUE TITLE
[Bug]: I have issue when use web3js web3.eth.sendTransaction(transactionObject [, callback])

### ISSUE THREAD

**Issue by thongnhatgraphic** [MetaMask/metamask-extension#23836]
### Describe the bug

I have a source code in nodejs. Client send request buyNft to nodeJs. NodeJs had encodeAbi function buyNft and respon rawFunction to Client. After that, Client receive rawFunction buyNft in responsive of api, client use rawFunction buyNft put into web3.eth.sendTransaction({
data:rawFunction, gas, from, to, value,... }). afterward extension metamask don't open, and show error message.
Please tell me this issue where come from?. I tried rpc in [infura.io](http://infura.io/) but it not work effectively

### Expected behavior

Open extension metamask

### Screenshots/Recordings

![issue](https://github.com/MetaMask/metamask-extension/assets/69072603/876b9ebc-9df5-4a68-8662-c6929e4629cd)

### Steps to reproduce

1.  Client send request buyNft to nodeJs. NodeJs had encodeAbi function buyNft and respon rawFunction to Client.
2. Client receive rawFunction buyNft in responsive of api, client use rawFunction buyNft put into web3.eth.sendTransaction({
data:rawFunction, gas, from, to, value,... })
3. extension metamask don't open, and show error message "MetaMask - RPC Error: e.startsWith is not a function. "
code: -32603
data:  "{\n  \"originalError\": {}\n}"
message: "e.startsWith is not a function"

### Error messages or log output

```shell
MetaMask - RPC Error: e.startsWith is not a function
```

### Version

11.13.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Severity

My project is working on production

**Comment by dattran92** [comment]
Same issue to me. I tried to manually install a previous [Version 11.12.4](https://github.com/MetaMask/metamask-extension/releases/tag/v11.12.4), and it work normally.

**Comment by vandan** [comment]
Need to confirm that the issue can be reproduced.

**Comment by dattran92** [comment]
A work around could be using `window.ethereum.request` instead

```
window.ethereum
    .request({
      method: 'eth_sendTransaction',
      // The following sends an EIP-1559 transaction. Legacy transactions are also supported.
      params: [
        {
          from: account,
          to: address,
          value: web3.utils.toHex(web3.utils.toWei(amount.toString())),
          gasPrice,
          gasLimit: '0x5028',
          // Customizable by the user during MetaMask confirmation.
          maxPriorityFeePerGas: '0x3b9aca00',
          // Customizable by the user during MetaMask confirmation.
          maxFeePerGas: '0x2540be400',
        },
      ],
    })
 ```

**Comment by jiajames** [comment]
@vandan we're witnessing this issue as well, it is reproduceable on newer versions of Metamask for a certain set of calldata
