### ISSUE TITLE
[Bug]: metaxseed transaction classified as deceptive request

### ISSUE THREAD

**Issue by metaxseed** [MetaMask/metamask-extension#23845]
### Describe the bug

Hi,

Domain: www.metaxseed.op
Inaccurate message: "This is a deceptive request. If you approve this request, a third party known for scams will take all your assets. Powered by Blockaid"

We are a reputable project building for two years and backed by Ava Labs and Ferrum Networks.  Please would you kindly be able to remove this mis-classification?

https://www.metaxseed.io

https://x.com/avax/status/1770115560983953785?s=20

https://twitter.com/metaxseed
https://linktr.ee/metaxseed

Thank you
Shipon Chowdhury
Telegram: @Ezekial25_17

### Expected behavior

No warning should popup in metamask.  It is having a negative impact on our sales.

### Screenshots/Recordings

![Screenshot 2024-04-03 221741](https://github.com/MetaMask/metamask-extension/assets/99299293/7409802d-880f-4143-89e1-df35239a16a8)

### Steps to reproduce

1. Create transaction in www.metaxseed.io/nodes
2. Select to buy 1 node licence
2. Open metamask
3. Error message appear when metamask pops up

### Error messages or log output

```shell
Domain: www.metaxseed.op
Inaccurate message: "This is a deceptive request. If you approve this request, a third party known for scams will take all your assets. Powered by Blockaid"
```

### Version

11.13.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Additional context

None

### Severity

Severe impact.  This is having a negative impact on our business.
People are scared to complete transaction due to this error.

**Comment by gauthierpetetin** [comment]
Hello, @metaxseed . Thank you for your report. Could you click the "Report an issue" within the warning and submit the form? That's the quickest way to have such issues addressed.

**Comment by bschorchit** [comment]
Closing as this has been resolved.
