### ISSUE TITLE
Flaky test [Confirmation]: User Operations from send transaction 

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#23851]
<img width="1450" alt="Screenshot 2024-04-04 at 10 54 15 AM" src="https://github.com/MetaMask/metamask-extension/assets/153644847/cdcbc283-6065-4b9a-858a-53ab16a6360d">

Reason for flaky waiting for element load
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/75682/workflows/f63b3742-898b-4d43-94d6-bb1869e6612e/jobs/2600459/tests

Reason for flaky is the window title
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/75969/workflows/3fd1b6f7-fd12-49e8-bcde-5d3d79e384e5/jobs/2613562/tests

Reason for flaky includes all
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/75939/workflows/4e8cc772-8434-4d46-bd21-16c85fe93152/jobs/2612147/tests

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
