### ISSUE TITLE
[Bug]: Blockaid False Positive

### ISSUE THREAD

**Issue by huostarter** [MetaMask/metamask-extension#23854]
### Describe the bug

Users of our launchpad system (https://www.huostarter.io/) are reporting that they receive the following message when attempting to send tokens to the smartcontract:

![mm-error](https://github.com/MetaMask/metamask-extension/assets/157201322/1e1dcbac-6107-4b71-82db-2c9fc60269af)

Our smartcontracts are verified:
launchpad: (https://bscscan.com/address/0x0972fd93a42E6b4a456BCE67D3ae42a29f400e53)

Is it something more we should do to ensure this message will not appear anymore?

### Steps to reproduce

1- Go to https://www.huostarter.io/projects/rgames
2- Connect your wallet
3- Select Join Pool 
4- Enter a token amount in the input and click approve

### Version

11.13.1

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows, MacOS

**Comment by gauthierpetetin** [comment]
Hello @huostarter,
Thank you for your report. Could you click the "Report an issue" within the warning and submit the form? That's the quickest way to have such issues addressed.

**Comment by bschorchit** [comment]
Closing as this has been fixed - please re-open if you encounter this issue again!
