### ISSUE TITLE
[Bug]: The calculations for sending the 'MAX' amount may not accurately reflect the intended figures

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23850]
### Describe the bug

1. When a user opts to send the maximum amount, both the gas fee and the amount to be sent undergo a recalculation whenever gas estimations are updated. If a user toggles between ETH and USD, and the gas estimation are refreshed the figures displayed in the 'From' field do not accurately reflect the intended values. 
2. When a user switches between ETH and USD, the number of decimal places displayed in the 'From' and 'To' fields may differ.

<img width="447" alt="Screenshot 2024-04-04 at 12 09 57 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/c835d7d6-9e6a-4804-860d-24b4749eceee">

4. Question: The 'MAX' button feature is currently appears only when ETH is selected on the first line of the transaction interface. When USD is chosen as the primary currency, the 'MAX' button is not visible. Is it designed to look like this?

<img width="422" alt="Screenshot 2024-04-04 at 12 32 36 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/fd8e1d3a-85a1-48e6-9481-efbf4f224627">

 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/b0501382-3bae-474d-a470-dc2949ce7c3f

### Steps to reproduce

1. Start 'Send' transaction
2. Set max amount
3. Switch main currency to USD
4. Wait till gas fee estimation is refreshed and amounts are recalculated

### Version

dev build <mb843/data-flows>

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
The issue also exist on this build [slack discussion link](https://consensys.slack.com/archives/C068SFX90PN/p1712701228770469)

https://github.com/MetaMask/metamask-extension/assets/104780023/fa518376-42c1-4c44-a678-ee997846f724

**Comment by sleepytanya** [comment]
Still present on [the latest build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN).

**Comment by BZahory** [comment]
Resolved as part of this change - enabled Max on fiat as well as a result of changes in how we align with upstream values (i.e., the send amount in the redux state) in that input

420010ae7951b4188ad6bab16af4d640a5643307
