### ISSUE TITLE
[Bug]: Attempting to send ERC1155 NFTs result in a request error

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23861]
### Describe the bug

Sending Longimals, Shark Art, OpenSea NFTs result in the error in the background console.
'Continue' buttton on the confirmation screen becomes inactive when trying to send Zen Academy NFT.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/681c513e-1152-406f-9604-7bfa782145c6

https://github.com/MetaMask/metamask-extension/assets/104780023/fab49586-8a96-4268-89d0-7c1ee58a1576

https://github.com/MetaMask/metamask-extension/assets/104780023/7e2581fb-0e32-4995-88fe-d633adca5d7a

### Steps to reproduce

1. Go to NFT tab
2. Send NFT mentioned above
3. See 'GET' error in the background console or inactive 'Continue' button for Zen Academy NFT

### Error messages or log output

```shell
metamask-controller.js:3340 
 GET https://bafybeia3py4roeyreze4r7wzp26b45ll6ajgwkas57uvswr5bb65erjxgu.ipfs.dweb.link/%7Bid%7D 404 (Not Found)
(anonymous)	@	util.js:306
(anonymous)	@	util.js:8
__awaiter	@	util.js:4
successfulFetch	@	util.js:305
(anonymous)	@	util.js:373
(anonymous)	@	util.js:8
__awaiter	@	util.js:4
timeoutFetch	@	util.js:371
(anonymous)	@	ERC1155Standard.js:194
fulfilled	@	ERC1155Standard.js:5
Promise.then (async)		
step	@	ERC1155Standard.js:7
fulfilled	@	ERC1155Standard.js:5
Promise.then (async)		
step	@	ERC1155Standard.js:7
(anonymous)	@	ERC1155Standard.js:8
__awaiter	@	ERC1155Standard.js:4
getDetails	@	ERC1155Standard.js:177
(anonymous)	@	AssetsContractController.js:232
rejected	@	AssetsContractController.js:6
Promise.then (async)		
step	@	AssetsContractController.js:7
(anonymous)	@	AssetsContractController.js:8
__awaiter	@	AssetsContractController.js:4
getTokenStandardAndDetails	@	AssetsContractController.js:217
getTokenStandardAndDetails	@	metamask-controller.js:3340
(anonymous)	@	createMetaRPCHandler.js:23
emit	@	events.js:153
addChunk	@	_stream_readable.js:291
readableAddChunk	@	_stream_readable.js:278
Readable.push	@	_stream_readable.js:245
_write	@	index.js:68
doWrite	@	_stream_writable.js:428
writeOrBuffer	@	_stream_writable.js:417
Writable.write	@	_stream_writable.js:334
ondata	@	readable.js:662
emit	@	events.js:153
addChunk	@	readable.js:278
readableAddChunk	@	readable.js:255
Readable.push	@	readable.js:201
_onMessage	@	index.js:30
(anonymous)	@	index.js:12
```

### Version

dev build <mb843/data-flows>

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Still present in [the latest build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN).

**Comment by ejwessel** [comment]
The last NFT in the above video is soulbound (Non-transferrable NFT)
https://opensea.io/assets/ethereum/0x26d6c3e7aefce970fe3be5d589dbabfd30026924/13742

**Comment by ejwessel** [comment]
Second NFT is 
address - 1:0x495f947276749Ce646f68AC8c248420045cb7b5e 
id - 18799305281945155391898832401974082284629067930754790331667001269349123096577

**Comment by ejwessel** [comment]
I'm removing `swap-send-blocker` because this has no effect on the swap + send feature or behavior.

**Comment by ejwessel** [comment]
Problem exists in core
https://github.com/MetaMask/core/pull/4276

**Comment by sahar-fehri** [comment]
Hello @sleepytanya is this bug reproducible on latest develop?
Im trying to reproduce but it seems i can send ERC1155 NFTs and i can
not see the error in the logs

https://github.com/user-attachments/assets/676504d3-a027-4fcd-aebf-aa69ad37bc47

**Comment by sahar-fehri** [comment]
Hello @sleepytanya !
I retested this issue on latest develop; it seems like
1- I can no longer see the error logs
2- I can send any ERC721/ ERC1155 except for that Zen academy NFT
(From what i checked, the query to estimate gas  `eth_estimateGas` fails on that specific NFT, but for the rest of NFTs you can send them with no issues)

**Comment by sahar-fehri** [comment]
Alright, after more digging, and if @sleepytanya confirms that the log is no longer being displayed, I think its safe to close this issue.

Not being able to send the Zen academy NFT is not a MM issue, it's an expected behavior;
Looking at the smart contract, its throwing here 

<img width="1713" alt="Screenshot 2024-07-19 at 16 02 27" src="https://github.com/user-attachments/assets/f59f0897-08ba-4932-acd5-02fce0a4be0c">
<img width="494" alt="Screenshot 2024-07-19 at 16 01 06" src="https://github.com/user-attachments/assets/6820b079-34ab-46e1-a77a-4aa390d468b2">

**Comment by sleepytanya** [comment]
@sahar-fehri 
Agree, I don't see it as well in v12.0.0 or v12.0.1.
