### ISSUE TITLE
[Bug]: ERC404 import nft not show image

### ISSUE THREAD

**Issue by huuduynvc** [MetaMask/metamask-extension#23865]
### Describe the bug

hello everyone, I am deploying erc404 on linea, I have a problem when importing nft into metamask is detected as type erc1155 and cannot display the image, I have double checked my ipfs is correct. Does anyone have experience with this issue please help me

### Expected behavior

import nft and show image

### Screenshots/Recordings

![Screenshot 2024-04-04 at 22 09 03](https://github.com/MetaMask/metamask-extension/assets/55422205/ced9cbb2-90c2-4689-aaf6-82a541d08308)
![Screenshot 2024-04-05 at 11 31 43](https://github.com/MetaMask/metamask-extension/assets/55422205/c70c148b-0620-4425-a8cb-dc4b6c17b794)

### Steps to reproduce

deploy erc404
mint erc404
import nft input contract, id

### Version

11.13.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by huuduynvc** [comment]
My nft is erc721 (all marketplaces detect this) why does the metamask detect it as erc1155?

**Comment by bergeron** [comment]
What is the contract address and token id of the NFT?
