### ISSUE TITLE
[Bug]: Amount in the 'From' field resets to 0

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23860]
### Describe the bug

When a user selects a token for the recipient to receive, the amount displayed in the 'From' field resets to zero, requiring user to input the amount once more.

UI question: 
when a fiat value is selected as the primary currency, it is displayed in the format of *** USD. Conversely, when it is not the primary currency, the display format changes to $***. Is this  expected behavior?

<img width="405" alt="Screenshot 2024-04-04 at 7 13 11 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/867fe449-a482-44bb-97d5-629937929ec9">

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/f31ea413-386d-4ae2-b119-b3a430168387

### Steps to reproduce

1. Start 'Send' transaction
2. Set an amount in the 'From' field
3. Choose another token for the recipient
4. Amount in 'From' field resets to 0

### Version

dev build <mb843/data-flows>

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Fixed in[ this build.](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN)

**Comment by micaelae** [comment]
@sleepytanya can we close this issue?

**Comment by BZahory** [comment]
Confirming that this issue no longer exists – closing.

And yes, the mentioned behavior is expected.
