### ISSUE TITLE
[Bug]: Sending 0 amount results in an error in the background console

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23862]
### Describe the bug

 Sending 0 amount results in an error in the background console

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/20d15997-645e-4a7d-94b7-dbfe370a2b1b

### Steps to reproduce

I haven't figured the way to consistently reproduce this bug. The steps are:

1. Start 'Send' transaction
2. Send 0 amount
3. See the errors in the background console

### Version

dev build <mb843/data-flows>

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by BZahory** [comment]
No longer seeing this error in the console

https://github.com/MetaMask/metamask-extension/assets/44588480/8f797297-02e8-401d-8c7c-38652386f0c4
