### ISSUE TITLE
[Bug]: NFT media are not visible while the NFT toggles in the Security and Privacy settings are activated.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23878]
NFT media are not visible while the NFT toggles in the Security and Privacy settings are activated. It is possible to manually import NFT (media is displayed in the NFT tab). This probably is related to [this bug](https://github.com/MetaMask/metamask-extension/issues/23612).
 Additionally, during the process of sending NFTs, the media for some tokens may not appear on the confirmation screen.
     

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/a97cb1be-c0bc-42bb-9e89-7e25ad9fbfb8

### Steps to reproduce

1. Install MM extension on Firefox
2. Turn NFT toggles in Security and Privacy settings
3. NFTs are not detected (not visible in the NFT tab)
4. Manually import NFT
5. Start 'send and swap' transaction for NFT (i.e. Shark Art)
6. NFT's image is not displayed on the confirmation screen

### Version

dev build <mb843/data-flows>

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by fuelmessenger** [comment]
:sparkles: Thanks to the community, there's an estimated bounty value of **$8.73 USD** for a successful merge request of this issue via contributions such as **9.750 MATIC** tokens. Happy coding :grinning:
Details and T&Cs at [joinfuel.io](https://joinfuel.io)

**Comment by ejwessel** [comment]
I'm not seeing this happening anymore on `mb843/updates-2`
https://github.com/MetaMask/metamask-extension/assets/3590816/feea80e4-8200-464f-8a45-5c8885811f6f

**Comment by sleepytanya** [comment]
@ejwessel 
Confirming, I don't see too:

https://github.com/MetaMask/metamask-extension/assets/104780023/bef77398-859d-479c-9f62-8fcb7bb9a483

I think the issue can be closed?

**Comment by alfeng6** [comment]
can we close this @sleepytanya @ejwessel

**Comment by sleepytanya** [comment]
I don't see the bug on `develop` and in v12.0.0 beta:

<img width="360" alt="Screenshot 2024-07-21 at 19 05 17" src="https://github.com/user-attachments/assets/974706ef-7cfe-450d-a5c5-11c9623ec921">
@alfeng6
