### ISSUE TITLE
[Bug]: The NFT picker on send and swap screen is not displaying the full list of NFTs currently associated with an account.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23875]
### Describe the bug

The NFT picker is not displaying the full list of NFTs currently associated with an account.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/dc3b49e6-15d9-4acf-857b-cc617b225a59

### Steps to reproduce

1. Go to NFT tab and note how many NFTs are listed there
2. Start 'send-swap' transaction
3. Select NFT
4. Notice that NFT tab doesn't reflect all NFTs associated with the current account

### Version

dev build <mb843/data-flows>

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Fixed in [the latest build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN).


https://github.com/MetaMask/metamask-extension/assets/104780023/a4407fe4-5772-45d1-a870-5e51fba7d575

**Comment by sleepytanya** [comment]
The same issue is present in the amon-hen-v1-rc1:


https://github.com/MetaMask/metamask-extension/assets/104780023/9474f4ae-c8dd-4b9f-9177-7c59dff08e76

**Comment by BZahory** [comment]
Resolved for swap+send; removing tag

**Comment by alfeng6** [comment]
@sleepytanya is this still an issue or can we close it?

**Comment by sleepytanya** [comment]
@alfeng6 

The issue is not present in v12.0.0 beta and on `develop`:

<img width="358" alt="Screenshot 2024-07-21 at 19 08 11" src="https://github.com/user-attachments/assets/17c4aa35-b816-47cf-93f5-ddbfef394885">
