### ISSUE TITLE
[Bug]: After switching networks, the conversion rates for tokens are no longer displayed, and eventually, the tokens do not appear.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23874]
### Describe the bug

When switching networks, the conversion rates for tokens are no longer displayed, and eventually, the tokens themselves might not appear within the account's assets. Eventually 'Too many requests' errors will result in MetaMask unresponsive (spinner).

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/c4a9e3b8-060a-4ca1-9f17-d0e1d17f3ef0

### Steps to reproduce

1. Start 'Send and swap' transaction on Linea mainnet
2. Cancel it
3. Switch to Ethereum mainnet
4. Start 'Send and swap' transaction on Ethereum mainnet
5. Notice that conversion rates are no longer visible
6. Switch back to Linea mainnet
7. Start 'Send and swap' transaction on Linea mainnet
8. See ETH only in the assets picker

### Version

dev build <mb843/data-flows>

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Still present in [the latest build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN):


https://github.com/MetaMask/metamask-extension/assets/104780023/86adf8f0-2cd8-43d4-8c69-3f53bd0917c0

**Comment by BZahory** [comment]
Not present in the latest build

https://github.com/MetaMask/metamask-extension/assets/44588480/636c08d7-b440-413b-92b2-77e92ecd2e45
