### ISSUE TITLE
[Bug]: Switching between tokens on the send and swap page triggers 'Too many requests' errors

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23873]
### Describe the bug

Switching between tokens on the send and swap page triggers 'Too many requests' errors. Eventually MetaMask becomes unresponsive, with a continuous loading spinner.
After reloading the extension 'couldn't find price error in the background console:

<img width="449" alt="Screenshot 2024-04-05 at 11 42 37 PM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/76906854-4107-4919-a353-5c4c15f407b3">

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/ab50072e-8e05-4b27-b329-571b97459840

### Steps to reproduce

1. Start 'Send' transaction
2. Switch between different tokens
3. See errors appear in the background console and MM eventually frozen

### Version

dev build <mb843/data-flows>

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Still present in [the latest build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN).

**Comment by BZahory** [comment]
Resolved in latest build


https://github.com/MetaMask/metamask-extension/assets/44588480/50d67e1e-28b6-418f-a333-80850e07cc5a
