### ISSUE TITLE
[Sentry] [Bug]: Gas - `TypeError: Cannot assign to read only property 'layer1GasFee' of object '[object Object]`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23887]
### Describe the bug

I get the following error when triggering any transaction on Base/Polygon/probably more (both from a dapp and from the wallet)

`TypeError: Cannot assign to read only property 'layer1GasFee' of object '[object Object]` and

` at s.updateTransactionLayer1GasFee (`

### Screenshots/Recordings

![Screenshot from 2024-04-08 14-10-37](https://github.com/MetaMask/metamask-extension/assets/54408225/167dae30-57af-4e00-95d3-0a324117d8dc)

https://github.com/MetaMask/metamask-extension/assets/54408225/af151f9a-b3e6-42fc-ac5d-dc4ee770781a

### Steps to reproduce

1. Select Base network
2. Trigger any tx
3. See console error

### Version

[Edit] Finding this on 11.14 prod already

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
This should be fixed with https://github.com/MetaMask/metamask-extension/pull/23521 that will rollout to users on extension v11.16
