### ISSUE TITLE
Local test network 8545 won't connect it just spins out when I know the node is running

### ISSUE THREAD

**Issue by beshogun** [MetaMask/metamask-extension#2390]
Hi I have tried repeatedly to launch metamask with the test network, first on chrome and it just spins out and never connects and I know the node is running.. I also tried a fresh account on brave and got the same behaviour.. any thoughts?
<img width="652" alt="screen shot 2017-10-18 at 00 49 17" src="https://user-images.githubusercontent.com/28452476/31695000-96a50f00-b39f-11e7-9826-c26795c5f3f4.png">

**Comment by Zanibas** [comment]
Tried to reproduce on Ubuntu/Brave and not getting reproduction. Can you try to disable and re-enable MetaMask on about:preferences#extensions ?

**Comment by beshogun** [comment]
Hi, thanks for the suggestion I have tried a few time to disable and reenable and it has no effect.. When I use testrpc it connects immediately though.. its quite strange..

**Comment by RobertoC27** [comment]
This is happening to me as well, I'm on Ubuntu 16.04 virtual machine. When using ganache as network it works fine but switching to my private network just reproduces this behavior.

**Comment by bdresser** [comment]
hey folks, we've fixed this wonky loading screen in https://github.com/MetaMask/metamask-extension/pull/5893

let me know if you're still having trouble!
