### ISSUE TITLE
harddrive failure lost private key and passphrase

### ISSUE THREAD

**Issue by RoyPrins** [MetaMask/metamask-extension#2391]
I have had a harddrive failure. The drive is still spinning but i cannot access it. I installed a new harddrive and installed the chrome extension for metamask again. But i cannot access my wallet. If i bring my harddrive to a datarecovery center, which file should they be looking for? I was on windows 10 with up to date chrome. Please help me. I made a mistake by copying the wrong private key towards my vault. I still know the password and i have the public address. What can there be done?

**Comment by Zanibas** [comment]
Did you save your seed phrase by any chance? If so, you can recover using that method.

**Comment by RoyPrins** [comment]
What happens when i use the seed phrase to change the password a d i want
to login with my previous computer and old password? Will I still be able
to access it via the old computer?

**Comment by velerodro** [comment]
@Zanibas how is it possible to recover the private key just with the seed phrase?

**Comment by danfinlay** [comment]
> How is it possible to recover the private key just with the seed phrase? I guess you generate the private key with some random generator that takes this phrase as an input?

That is correct. All accounts are generated from the seed phrase.

If you restore your vault with your seed phrase on a new computer, it will work fine, even without the same password. The password is just used to encrypt the vault on your hard drive.
