### ISSUE TITLE
Metamask starts slowing down at around 5 accounts and crashes on login at 10 accounts

### ISSUE THREAD

**Issue by WeBetCrypto** [MetaMask/metamask-extension#2392]
This is a huge set-back for our testing period as we wanted to test our dividence function. We would appreciate any temporary work-arounds so we can proceed with testing.

  *  Metamask logs in normally
  *  Metamask crashes upon successful password input
  *  Google Chrome
  *  Windows 10

**Comment by Zanibas** [comment]
Is this a uniform behavior across multiple devices? Even with a fresh reinstall? Tried to replicate on Ubuntu/Chrome but no avail. Do each of these accounts have several transaction histories attached to them?

**Comment by WeBetCrypto** [comment]
This issue occurred on Chrome no matter how many resources were being used up. Fresh re-install has the same issue.
