### ISSUE TITLE
[Bug]: The primary currency for the next initiated transaction defaults to USD instead of reverting back to ETH

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23922]
### Describe the bug

Upon switching the primary currency on the send+swap page, if a transaction is rejected while USD is selected, the primary currency for the next initiated transaction defaults to USD instead of reverting back to ETH. 
Swap+send build [slack discussion link](https://consensys.slack.com/archives/C068SFX90PN/p1712701228770469)

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/8adeddae-4827-4446-9e69-bd326d2db6f1

### Steps to reproduce

1. Start send+swap transaction
2. Switch currency ETH -> USD
3. Reject transaction
4. Start another send+swap transaction
5. See that primary currency is pre-set to USD

### Version

dev build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Present in [the latest build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN):


https://github.com/MetaMask/metamask-extension/assets/104780023/330ee295-5d60-4ce2-8f1e-77df7671509c

**Comment by vstern1** [comment]
Expected behavior - design sign off
