### ISSUE TITLE
[Tech Task] Implement Transaction Insights Component

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#23942]
The snaps team will own this component for now.

<img width="644" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2addd53ccf7a3a40be543020258e4cb2d6c04c0b/Screenshot%202024-04-10%20at%2018.54.55.png" alt="Screenshot 2024-04-10 at 18.54.55.png" />

**Comment by jpuri** [comment]
Closing this task as the requirement is already covered by this task: https://github.com/MetaMask/metamask-extension/issues/24995
