### ISSUE TITLE
[Tech Task] Implement info subsection for advanced view in contract interaction

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#23946]
> [!IMPORTANT]  
> Question for @bschorchit: When the user toggles the advanced nonce controls setting we:
> a) Make the nonce visible or
> b) Make the nonce editable (and it's always visible)

> [!IMPORTANT]  
> @SayaGT to supply tooltip wireframes and copy

> [!IMPORTANT]  
> @SayaGT to supply wireframes for nonce edit behavior and validation. What happens if the user inputs -1?

Progresses #23905

## Context

Toggle:

<img width="320" alt="Screenshot 2024-04-11 at 12 35 36" src="https://github.com/MetaMask/metamask-extension/assets/13814744/ccfc7691-62dd-44e0-832f-d6d9d1f305cd">

<br />

SubSection:

<img width="320" alt="Screenshot 2024-04-11 at 12 34 56" src="https://github.com/MetaMask/metamask-extension/assets/13814744/538c039f-13e1-4ad2-8415-2e00589f70ea">

(source: [Figma design file](https://www.figma.com/file/gcwF9smHsgvFWQK83lT5UU/Confirmation-redesign-V4?type=design&node-id=0-1&mode=design&t=Kn34KocD9l76FH7I-0))

## Approach

The section appears after clicking the icon in the header

Create a dedicated component inside the confirm/info folder. The component will be imported inside the contract-interaction info component.

This component will include the ability to edit the nonce. We can reuse this action:

`https://github.com/MetaMask/metamask-extension/blob/develop/ui/store/actions.ts#L762-L767`

## Acceptance Criteria
- Implement a new component that includes the described functionality.
- Use that component in the info section for contract interaction.
- Add the icon to the header.
- Create a hook at the info component level to expand and collapse the section. Pass down the setter to the header component and the value to the info component and into this subsection of the contract interaction component.

**Comment by bschorchit** [comment]
> [!IMPORTANT]  
> Question for @bschorchit: When the user toggles the advanced nonce controls setting we:
> a) Make the nonce visible or
> b) Make the nonce editable (and it's always visible)

a). When the user toggles the advanced nonce controls setting we make the nonce visible and editable. If the toggle is off, the nonce should not visible.
