### ISSUE TITLE
Migrate existing alerts to new contract interaction confirmation

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#23953]
Implement the existing transaction alerts (applicable to contract interaction) in the new transaction confirmation via the new alert system.

**Existing Transaction Alerts**

<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/6e3921f2-14e7-4702-bda8-482760c30fe7"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/a59548a5-a751-46e1-bc7f-b0fd379de37b"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/e0d6a46a-b888-432a-8c25-8f1edd5995f8"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/ef46505f-e09c-4a3f-abbb-9916f55f4eed"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/308cf939-7eb4-4274-924d-6c19a6ee4c1d"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/6fef80a4-eed6-473b-96e4-51d01da5c3ee"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/962d88af-38f7-4f2f-afe3-662a825bfc34"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/0963a9e3-6b3e-45a0-8c3d-7bd1579ba371"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/7b5b12f6-bdaf-4bbe-90b7-f2dda52e5367"/>
<img width="200" src="https://github.com/MetaMask/metamask-extension/assets/19745142/492c02d2-7e2c-4430-9a00-c0a78d775707"/>

**Comment by bschorchit** [comment]
Note: This should leverage the [new alert system](https://www.figma.com/file/yUczlH2HbHaHsYijiONKx0/Warnings%2C-Alerts-and-Flags?type=design&node-id=1208-25406&mode=design&t=60sUfG04mZWCJuB9-0) that is being developed by confirmations system team.

**Comment by bschorchit** [comment]
Re-posting the above warnings with initial comments.

I broke it down on:
- type: informational, non-critical or critical
- placement: in context or generic
- actionable: blocking or non-blocking


# 1. Unable to estimate gas

- type: critical
- placement: in context: gas key-value row (once that is implemented)
- actionable: non-blocking?


# 2. Insufficient funds

- type: critical
- placement: in context: gas key-value row
- actionable: blocking


# 3. Test 1 2 3
This one should be deleted unless it's useful for testing purposes :)

# 4. Previous transaction still being signed

- type: critical
- placement: in context: generic
- actionable: blocking

# 5. You have (x) pending transactions

- type: non-critical
- placement: in context: speed key-value row (once that is implemented)
- actionable: non-blocking

# 6. Future transactions will queue

- type: non-critical
- placement: in context: speed key-value row (once that is implemented)
- actionable: non-blocking

# 7. Paymaster sponsorship

- type: informational
- placement: in context: gas key-value row (once that is implemented)
- actionable: non-blocking

# 8. Minimum gas limit

- type: critical
- placement: in context: gas key-value row (once that is implemented)
- actionable: blocking

question: how does one get to this warning? I'm not able to manually edit to lower than 21000.

# 9. Failed to estimate gas price

- type: critical
- placement: in context: gas key-value row (once that is implemented)
- actionable: non-blocking?


----------------------------------------------

# Same content as above with each screenshot for easier reference:

# 1. Unable to estimate gas

- type: critical
- placement: in context: gas key-value row (once that is implemented)
- actionable: non-blocking?

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/20f4a77c-ab27-46c1-a7e3-b10ac5514fd0)


# 2. Insufficient funds

- type: critical
- placement: in context: gas key-value row
- actionable: blocking

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/cfc61557-8204-4146-8127-aa82bfb0eb1b)

# 3. Test 1 2 3
This one should be deleted unless it's useful for testing purposes :)
![image](https://github.com/MetaMask/metamask-extension/assets/34968356/22df6d7b-8332-4daf-8c88-ebe53f02f92f)

# 4. Previous transaction still being signed

- type: critical
- placement: in context: generic
- actionable: blocking

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/c84b9c8e-f087-486f-a9db-c3e5b43a11e0)

# 5. You have (x) pending transactions

- type: non-critical
- placement: in context: speed key-value row (once that is implemented)
- actionable: non-blocking

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/7794ddb9-2d6f-4ac2-bd34-7623b18eefc3)

# 6. Future transactions will queue

- type: non-critical
- placement: in context: speed key-value row (once that is implemented)
- actionable: non-blocking

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/92ed79cf-4b71-4f56-97e1-2bec58d55ef0)

# 7. Paymaster sponsorship

- type: informational
- placement: in context: gas key-value row (once that is implemented)
- actionable: non-blocking

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/f5b8b08a-444c-4da2-af4e-7c95557e6234)

# 8. Minimum gas limit

- type: critical
- placement: in context: gas key-value row (once that is implemented)
- actionable: blocking

question: how does one get to this warning? I'm not able to manually edit to lower than 21000.

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/62558361-c38a-4bea-ba9b-bc0919c0613e)

# 9. Failed to estimate gas price

- type: critical
- placement: in context: gas key-value row (once that is implemented)
- actionable: non-blocking?

![image](https://github.com/MetaMask/metamask-extension/assets/34968356/47396e54-7ea2-4546-81c1-61ea005a9c2d)
