### ISSUE TITLE
[e2e] Signature redesign - Create test for ENV variable and settings toggle

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#23975]
Original request: 
We need to setup a new job for conf-redesign and build the app with the env variable feature toggle turned on.

Requirement:
Test old confirmation and new redesign confirmation display based on confirgurations

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23975?planning-poker) with Zenhub @blackdevelopa @jpuri @pedronfigueiredo @segun

**Comment by cryptotavares** [comment]
* New build type on ci and new e2e test job
* We should run all existing e2e tests on the new job that we are creating
* Specific redesign e2e tests should bail if redesign env is not set
