### ISSUE TITLE
[e2e] Signature redesign - Create metric tests

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#23979]
ref: https://github.com/MetaMask/metamask-extension/issues/23552#issuecomment-2017496179

Create e2e tests:
- [ ] Metrics
  - [ ] check we are tracking the redesigned UI is being used (while we have both new and old co-existing). For this we can add the value redesigned_confirmation to the ui_customizations property of all signature events when the redesigned UI is being displayed
  - [ ] check we are tracking opening of account info modal

**Comment by jpuri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23979?planning-poker) with Zenhub @pedronfigueiredo @digiwand @seaona @pnarayanaswamy
