### ISSUE TITLE
[e2e] Signature redesign - Create tests to check info per signature type

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#23977]
ref: https://github.com/MetaMask/metamask-extension/issues/23552#issuecomment-2017496179
Blocked By: https://github.com/MetaMask/metamask-extension/issues/24712

Create e2e tests:
- [ ] Signature domain section (per signature type)
  - [ ] `Request from` displays the url with HTTP warning if using HTTP instead of HTTPS
  - [ ] `Interacting with` displays the verifying contract address
- [ ] Signature message section (per signature type)
  - [ ] Primary type is correctly displayed
  - [ ] Message info matches the one we pass on the test dapp (no missing fields, correct identation etc)

**Comment by cryptotavares** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23977?planning-poker) with Zenhub @digiwand @jpuri @pedronfigueiredo
