### ISSUE TITLE
[e2e] Confirmation redesign - Create Header tests

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#23976]
ref: https://github.com/MetaMask/metamask-extension/issues/23552#issuecomment-2017496179

Create e2e tests:
- Headers
  1. Account details display `address` (can be copied) and `balance` with the correct currency
  2. Selected account not the current one warning is displayed when a different account than the connected one is selected
    
    ref: https://github.com/MetaMask/metamask-extension/issues/23552#issuecomment-2050038435 cc: @seaona 
    > it refers to the case when there is a mismatch between the account that's connected to the dapp and the currently selected account (not connected). We display the following warning in the current design and we should support something similar in the re-design:
    ![Screenshot from 2024-04-11 18-03-45](https://github.com/MetaMask/metamask-extension/assets/54408225/f511f1e5-63d2-4909-9dc8-91314da1d3ef)

**Comment by cryptotavares** [comment]
FYI - https://github.com/MetaMask/metamask-extension/blob/develop/test/e2e/webdriver/driver.js#L474
