### ISSUE TITLE
[e2e] Confirmation redesign - Create Navigation tests

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#23978]
ref: https://github.com/MetaMask/metamask-extension/issues/23552#issuecomment-2017496179

Create e2e tests:
- [ ] Navigation (signatures only)
  - [ ] I can navigate through multiple signatures
  - [ ] I can reject all signatures at once
  - [ ] I can reject/accept signatures one by one
- [ ] Navigation (mix transaction + signatures)
  - [ ] I can navigate through multiple signatures and transactions
  - [ ] I can reject all signatures and transactions at once
  - [ ] I can reject/accept signatures and transactions one by one

**Comment by jpuri** [comment]
Let's limit the scope of e2e to new designed confirmation pages.

**Comment by jpuri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/23978?planning-poker) with Zenhub @digiwand @pedronfigueiredo @pnarayanaswamy @seaona
