### ISSUE TITLE
[Bug]: Simulations - Lacking decimals precision

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#23982]
### Describe the bug

Whenever I am sending an amount of any token, if the amount needs several decimals, we loose precision on what we display in simulations

### Expected behavior

Not sure if we should display all the decimals in simulations but I believe we should? @bschorchit 

### Screenshots/Recordings

![Screenshot from 2024-04-11 19-17-21](https://github.com/MetaMask/metamask-extension/assets/54408225/59df28b1-b873-43c1-8b92-6c8f54328b08)

### Steps to reproduce

1. Start a Send ETH
2. Add any recipient
3. Add this amount `0.0000015`
4. See simulations display `0.000001`

### Version

11.14.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
You can see the full precision if you hove over the number:

![Image](https://github.com/MetaMask/metamask-extension/assets/34968356/cd0f4156-f184-4f03-b7ba-00a8bc70d853)

**Comment by bschorchit** [comment]
We're also planning to work further on decimals here https://github.com/MetaMask/MetaMask-planning/issues/2343 so closing this in favor of that other issue, if that's ok, @seaona :)
