### ISSUE TITLE
Setup office hours for e2e

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#24008]
### What is this about?

- Setup office hours for code walkthrough for specific topics locator strategy,  waits, assertion understanding of the current tooling with development team and  QA team.
- Setup office hours for fixtures, ganache, smart contracts.

Developer feedback
_- I don't know a good place to put it, so I just don't put it anywhere - David M
- I don't believe devs don't write test for any other reason than just not knowing how to write them correctly. - Nico
- not enough separation between unit and integration tests. - Nico
- not enough separation between UI and control tests. -Nico
- Our test setup is complicated and makes it difficult to understand the environment that tests are run in. This is particularly bad on mobile, but applies to the extension as well. - Mark_

Potential topics:-
- Explain the percentage of coverage for unit test and e2e tests
- Explain e2e testing should primarily focus on covering user flows, emphasizing the majority of happy path scenarios.
- Explain the advantages of Unit Testing that is efficient and error-resilient with proper case study.
- Explain the extension build process, environment which commands need to be used.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by gauthierpetetin** [comment]
Closing as content can be included in: https://github.com/MetaMask/metamask-extension/issues/24220
