### ISSUE TITLE
[Bug]: When user choose a new token in the 'From' field, the token in the 'To' field automatically updates to match this change, overriding any previous selection. 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24017]
### Describe the bug

[build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN)

When you choose a new token in the 'From' field, the token in the 'To' field automatically updates to match this change, overriding any previous selection. 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/54d8eb24-ea4e-4f1e-86e8-6d37a950c9cc

### Steps to reproduce

1. Start send+swap transaction
2. In the recipient's field switch ETH to any other token
3. Go back to 'From' field and select any token
4. See the same token is selected in both fields ('From' and 'To')

### Version

x

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by vstern1** [comment]
Discussed with Bilal. This is expected and we can close this issue.
