### ISSUE TITLE
[Bug]: Signatures - We are not displaying any warning when triggering a Signature with the not current selected account

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24046]
### Describe the bug

Whenever we are connected to a dapp with an account, but we have selected another account in the wallet, if we trigger a signature, we see how no warning is displayed due to the miss-match accounts (the dapp one triggering the signature and the selected one).

This happens both to old design and new designs.

### Expected behavior

Display a warning like we do in Transactions?

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/3a51b699-19b3-4163-99a3-5ff91263dd6a

In transactions we display this warning:

![Screenshot from 2024-04-16 11-29-25](https://github.com/MetaMask/metamask-extension/assets/54408225/02bd0ebb-37e1-4d9b-b121-afd4d2c6f371)

### Steps to reproduce

1. Go to the test dapp
2. Connect Account 1
3. Go to MM full width
4. Select Account 2
5. Trigger a Signature
6. See Account 1 without any warning

### Version

(production) it's an old issue

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
I think we need to understand/investigate whether this warning is still helpful and if we want to persist/re-introduce it within transactions/signatures. And if yes, if we can leverage the new alert system for that. I'll sync with Saya on this once she's back.
This shouldn't be a blocker for signatures redesign though. I've also labelled it as a feature request for now.

**Comment by seaona** [comment]
Relates to: https://github.com/MetaMask/metamask-extension/issues/24046

**Comment by cryptotavares** [comment]
Relates to: https://github.com/orgs/MetaMask/projects/78/views/1?pane=issue&itemId=60743203

**Comment by bschorchit** [comment]
Closing in favor of: https://github.com/MetaMask/metamask-extension/issues/24164
