### ISSUE TITLE
Reduce minimum gas price

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2404]
Byzantium has somehow dramatically dropped commonly mined gas prices.

We should be able to safely reduce our enforced minimum gas price. First need to confirm our current gwei input handles decimals gracefully. Paging @Zanibas

**Comment by ligi** [comment]
![metamask](https://user-images.githubusercontent.com/111600/31997844-bad3920e-b98d-11e7-8596-c25169828ec5.png)

was sad to notice it is not possible with metamask - was happily sending 1<Gwei txes with MEW and WALLETH

**Comment by danfinlay** [comment]
Sorry for making you sad. As you can see above, we are already working on changing this.

**Comment by ligi** [comment]
YAY - looking forward to it!
