### ISSUE TITLE
[Bug]: Transactions and Signatures Extended view displays duplicated headers

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24044]
### Describe the bug

Whenever we trigger a transaction or signature, if we open the extended MM view, we can see how 2 headers are displayed on the signature screen.

This has changed from the old design (though in the old design it does not seem ideal neither --see below)

### Expected behavior

Need design/product input @SayaGT @bschorchit 

### Screenshots/Recordings

Re-design:
![Screenshot from 2024-04-16 09-21-49](https://github.com/MetaMask/metamask-extension/assets/54408225/2a8d61c7-ce8d-4255-a133-e6da0339a9d4)

Old design:
![Screenshot from 2024-04-16 09-21-19](https://github.com/MetaMask/metamask-extension/assets/54408225/282216e8-34ec-4111-b5df-392e63543aa5)

### Steps to reproduce

1. Trigger a Signature
2. Open MM width view
3. Click on the pending Signature
4. See screen

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by digiwand** [comment]
To do for shipping Signature Redesign: 
- Remove duplicate header or keep duplicate header

**Comment by cryptotavares** [comment]
If we decide to hide the appHeader from Transactions and Signatures confirmations we should those routes here - https://github.com/MetaMask/metamask-extension/blob/develop/ui/pages/routes/routes.component.js#L521-L605

And then if we want to display the network details on the Confirmations header in fullscreen we just need to remove this ternary - https://github.com/MetaMask/metamask-extension/blob/develop/ui/pages/confirmations/components/confirm-page-container/confirm-page-container-header/confirm-page-container-header.component.js#L67
(not applicable to new confirmation pages as those will already have the network being displayed on the header)

**Comment by cryptotavares** [comment]
Figma for new header - https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=1846-17234&mode=design&t=iAudnODDTZ3MDqnt-0

Proposed approach:
* Get rid of the fullwidth app header on all confirmation screens
* Add the network display to the header of all "soon to be legacy" confirmation screens when in fullwidth

**Comment by cryptotavares** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/24044?planning-poker) with Zenhub @digiwand @jpuri @pedronfigueiredo
