### ISSUE TITLE
[Bug]: Confirmation Redesign - Extended view and expanded width displays odd width

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#24055]
### Describe the bug

Whenever we trigger a redesign confirmation, there is an odd width for both header and body.

### Expected behavior

Need design/product input @SayaGT 

### Screenshots/Recordings

Re-design:
![Screenshot from 2024-04-16 09-21-49](https://github.com/MetaMask/metamask-extension/assets/54408225/2a8d61c7-ce8d-4255-a133-e6da0339a9d4)

Old design:
![Screenshot from 2024-04-16 09-21-19](https://github.com/MetaMask/metamask-extension/assets/54408225/282216e8-34ec-4111-b5df-392e63543aa5)

### Steps to reproduce

1. Trigger a Signature
2. Open MM width view
3. Click on the pending Signature
4. See screen

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by SayaGT** [comment]
[Here are the designs](https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=1846%3A17234&mode=design&t=21WGDWK3vmYQkack-1). Thanks!

**Comment by cryptotavares** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-extension/24055?planning-poker) with Zenhub @pedronfigueiredo @jpuri @digiwand
