### ISSUE TITLE
[Bug]: Discrepancy in the 'All permissions' menu

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24066]
### Describe the bug

The 'All permissions' menu displays a list of connected sites; however, upon clicking on these items, it becomes apparent that a connection does not actually exist.  Selecting 'Connect accounts' closes the permissions tab without initiating the intended action. 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/f6b3fd91-bd3f-47e3-86a5-f6a12518e899

### Steps to reproduce

1. Connect MM to the dapp / dapps
2. Click 'All permission' in the three-dot menu in the upper right corner
3. See the connected site / list of connected sites
4. Click any item
5. Note the message  'MM is not connected to this site'
6. Click 'Connect accounts'
7. Permission tab is closed

### Version

dev build on develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by NidhiKJha** [comment]
@sleepytanya are you testing it on latest develop or the build?
