### ISSUE TITLE
[Bug]: Faulty scam warning message

### ISSUE THREAD

**Issue by nhoclove9x** [MetaMask/metamask-extension#24071]
### Describe the bug

One of our customers receives the following advert:

This is a fraudulent request.
If you authorise this request, a third party known for fraud will seize all your assets.

Well, that's very unpleasant for us. We are a reputable on. Not a scam.

![2024-04-17 12 18 00](https://github.com/MetaMask/metamask-extension/assets/2536935/95610122-f7a9-46e8-bc7b-8e3b15bbbd4b)

=> https://unicornhunter.io

### Steps to reproduce

The problem cannot be reproduced in general. This problem does not occur with other customers.

The customer has been with us for a long time and is very satisfied with the service. Only the false warning message is annoying.

### Version

11.13.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

https://unicornhunter.io/

[info@unicornhunter.io](mailto:info@unicornhunter.io)

**Comment by gauthierpetetin** [comment]
Hi @nhoclove9x , we recommend you click on “See details” within the banner warning and then on “Report an issue” as this is the most effective to have the issue addressed.

**Comment by bschorchit** [comment]
Closing as this has been resolved. Let us know if you encounter any other issue in the future!
