### ISSUE TITLE
[Bug]: Connected accounts within 'All permissions' tab and on the MetaMask popup are not updated

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24101]
### Describe the bug

When a user disconnects a dApp using the dApp's website interface, the changes are not immediately reflected in MetaMask's connections. Accounts that have been disconnected from dApps still appear as connected within the "All permissions" tab and on the MetaMask popup opened on the dApp page.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/54a9328c-1cae-48ea-9eb3-5c0c2e365215

### Steps to reproduce

1. Connect MM to dapp / dapps
2. Disconnect account from the dapp page
3. See that disconnected account displayed as connected within 'All permissions' and on the MM popup

### Version

dev build on develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by NidhiKJha** [comment]
@sleepytanya I am not sure if this is specific to Multichain. It shows the same behaviour for connected sites in Prod. Can you confirm? cc @darkwing

**Comment by sleepytanya** [comment]
@NidhiKJha You are right!
Given that this behavior is in the Production, it raises a question: is this considered a bug, or is it the expected behavior, not specific to multi-chain operations?


https://github.com/MetaMask/metamask-extension/assets/104780023/48c01756-8b25-4d76-87cc-5ac2a4ce95bd

**Comment by adonesky1** [comment]
So what is shown in this video is not actually a bug. It stems from the fact that all those dapps are not actually implementing `wallet_revokePermission` which was a recently added API, rather they are simply updating their own UI to pretend that a permission revocation has happened.

**Comment by hesterbruikman** [comment]
Note that this issue is closed because the reported behavior is expected. With our increased understanding we'll focus on better setting expectations in the UI.
