### ISSUE TITLE
[Bug]: Account name selector spacing has shrunk

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-extension#24125]
### Describe the bug

As soon as the user has double digit accounts, say "Account 10", we show an ellipsis instead of the number. This is a regression. We can see on the Chrome listing that we used to support more characters in the account name in the account picker.

<img width="160" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/7900773/2b4c40b1-4e0d-45a8-9371-075039f26b7c">

<img width="1173" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/7900773/f699f938-58e6-4853-9fc3-b05e8e925525">

### Expected behavior

The space for the account selector should be increased to the maximum available width. 

### Steps to reproduce

Name an account with more characters than "Account 1". 

### Version

11.14

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Stam098c** [comment]
ฉันเอง

- [ ]
