### ISSUE TITLE
[Bug]: Metamask recommended gas fees for B^2 Network is too high

### ISSUE THREAD

**Issue by Stonepapa** [MetaMask/metamask-extension#24120]
### Describe the bug

Just like the problem faced by opBNB chain, Metamask suggests a very high gas fee on B^2 Network. Maybe Metamask had set a default minimum recommendation price for gas based on the average of all networks.

B^2 Network is a fully EVM-compatible Rollup built through the OP Stack. And here are some infos for B^2 testnet and mainnet.

```
Mainnet Info:
Chain ID: 223
RPC: 
	https://rpc.bsquared.network/
	https://b2-mainnet.alt.technology/
Explorer:
	https://explorer.bsquared.network/

Testnet Info:
ChainID: 1123
RPC: 
	https://b2-testnet.alt.technology/
Explorer: 
        https://testnet-explorer.bsquared.network/
```

And here is the recommended gas fee by Metamask.

<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/125890624/e404cdb1-9304-4620-a046-19851b5f33f7">

The recommended gas price is default 1.5gwei.

And here is the real gas price on B^2 mainnet.

```
curl https://rpc.bsquared.network/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":1,"result":"0xf433c"}

cast gas-price -r=https://rpc.bsquared.network

1000252
```

The real gas price is much lower than the default minimum recommendation price, it is 1000252wei (0.001000252gwei).

### Expected behavior

We expect that Metamask can provide a recommended gas fee based on the real gas price on B^2 chain.

### Screenshots/Recordings

<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/125890624/ba9c9de0-541e-45e4-a9bc-a3d12180ecdd">

<img width="581" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/125890624/77cccf74-2269-4f45-8e44-5cf70ffb756d">

### Steps to reproduce

1. Add custom network using B^2 network info.

```
Chain ID: 223
RPC: 
	https://rpc.bsquared.network/
	https://b2-mainnet.alt.technology/
Explorer:
	https://explorer.bsquared.network/
```

2. Send asset on Metamask, edit "Estimated fee".
3. Click on "Advanced", and can see the Priority Fee is default 1.5gwei, the Max base fee is 1.500000302gwei.
4. Get the real gas price from B^2 chain rpc.

```
curl https://rpc.bsquared.network/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}'
```

or

```
cast gas-price -r=https://rpc.bsquared.network
```

The B^2 gas price is 0.001000252gwei.

### Version

11.13.1

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows, MacOS

**Comment by bschorchit** [comment]
Closing as this should be fixed with v11.16. Please re-open if that's not the case!
