### ISSUE TITLE
[Bug]: Tokens other that ETH are not displayed on the dropdown menu on the send page

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24145]
### Describe the bug

Tokens other than ETH are not consistently displayed in the dropdown menu on the send page. The occurrence of this issue seems to vary, with tokens sometimes reappearing in the dropdown menu without a clear pattern, as highlighted in the second video. Additionally, during these instances, the background console reports 429 errors, indicating potential cause(?).
This bug probably shares the same underlying cause as https://github.com/MetaMask/metamask-extension/issues/24144 and https://github.com/MetaMask/metamask-extension/issues/23863

<img width="785" alt="Screenshot 2024-04-19 at 21 23 02" src="https://github.com/MetaMask/metamask-extension/assets/104780023/f9d14b9c-6e48-4f8d-80df-c83b861c76fe">

<img width="387" alt="Screenshot 2024-04-19 at 21 09 48" src="https://github.com/MetaMask/metamask-extension/assets/104780023/8d6ae2b4-2275-493e-9c6e-a0cf072c66ee">

<img width="395" alt="Screenshot 2024-04-19 at 21 10 13" src="https://github.com/MetaMask/metamask-extension/assets/104780023/5ee3a286-c030-4d09-bd02-643073b02d2b">

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/fed97c9d-5960-4569-bdee-f2e44ff6fa13

https://github.com/MetaMask/metamask-extension/assets/104780023/8bea96cd-5887-4bad-a9bc-29e17f4a1ebd

### Steps to reproduce

1. Start 'Send' transaction
2. Try to select token other that ETH

### Version

amon-hen-v1-rc1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by pepijndevos** [comment]
I seem to have the same issue where I see USDT in my wallet, but clicking on it does nothing.
Indeed if I go to send and pick a contact there is only ETH despite USDT being listed in my wallet.

**Comment by BZahory** [comment]
Fixed (see: https://github.com/MetaMask/metamask-extension/issues/24151#issuecomment-2099737105)
