### ISSUE TITLE
[Bug]: MetaMask becomes unresponsive when selecting a token other that ETH on the send page

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24144]
### Describe the bug

When selecting a token other than ETH, MetaMask becomes unresponsive, accompanied by a loading spinner and 429 (Too Many Requests) errors appearing in the background console. 
Might be related to https://github.com/MetaMask/metamask-extension/issues/23863

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/8d16e4f0-0b17-4aca-8415-e48b957cc22d

### Steps to reproduce

1. Start 'Send' transaction
2. Select a token other that ETH (Arbitrum in the video)
3. See MetaMask frozen with a spinner

### Version

amon-hen-v1-rc1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
MM can also become unresponsive when sending NFT (with the same 429 errors):

<img width="715" alt="Screenshot 2024-04-20 at 21 33 40" src="https://github.com/MetaMask/metamask-extension/assets/104780023/0f044e3c-af4c-4c1c-bb94-11713e2f848a">

**Comment by BZahory** [comment]
Resolved in the latest build.

https://github.com/MetaMask/metamask-extension/assets/44588480/5b1afd64-4132-4a3e-b1c6-14cc609d2d04
