### ISSUE TITLE
[Bug]: Account assets may not be appearing as expected on the token list within the send+swap page

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24151]
### Describe the bug

On the send+swap screen, ETH is currently the only token consistently available in the dropdown menu. Additionally, there are moments when the NFT tab may not display the account's NFTs as expected. The visibility of tokens in the dropdown menu can vary, with tokens occasionally appearing and disappearing.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/a2375490-80db-413e-b7fe-66a496d80c97

### Steps to reproduce

1. Start 'Send' transaction
2. Select token other that ETH
3. Notice that the only available token is ETH

### Version

latest send+swap [build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN)

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by BZahory** [comment]
As of 7476b4218947cc8b1abf026a736d9613b1b54d3c, we support all swap tokens.

https://github.com/MetaMask/metamask-extension/assets/44588480/e0329127-4fe2-4377-afac-a65e9fa77e1b
