### ISSUE TITLE
[Bug]: The fiat balance for the account's assets are not accurately displayed on the send+swap screen

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24152]
### Describe the bug

Upon switching the primary currency, the displayed fiat balances appear unreasonably high.

Observed in latest send+swap build and amon-hen-v1-rc1.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/a236ae88-8275-4545-a56b-62b0e151dc93

https://github.com/MetaMask/metamask-extension/assets/104780023/19c75a7b-abad-4ec8-8865-0989166d71bb

### Steps to reproduce

1. Start "Send' transaction
2. Choose token other that ETH
3. Switch currency
4. Notice the fiat value for the account's balance is too high

### Version

latest send+swap [build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN) and amon-hen-v1-rc1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by BZahory** [comment]
Fixed in latest build

https://github.com/MetaMask/metamask-extension/assets/44588480/5b97eb16-2358-4b13-9ff4-7f1cdf656e95
