### ISSUE TITLE
[Bug]: PPOM - Metrics event sets `loading` to the `security_alert_reason` for benign transactions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24157]
### Describe the bug

Whenever we are accepting or rejecting benign transactions, we can see how on the metrics event, the `security_alert_reason` is set to `loading`

### Screenshots/Recordings

![Screenshot from 2024-04-22 10-58-18](https://github.com/MetaMask/metamask-extension/assets/54408225/2c417cf2-457b-4eb2-8dcd-767163aff8ef)

### Steps to reproduce

1. Go to the test dapp
2. Trigger a benign tx
3. Accept/reject
4. Check metrics event (background network request or segment)
5. See the `security_alert_reason` is set to `loading`

### Version

11.15.0 might be earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
I still see this issue in latest code:

<img width="440" alt="Screenshot 2024-06-25 at 6 08 08 PM" src="https://github.com/MetaMask/metamask-extension/assets/2182307/127776a2-9d0a-4bd7-b769-1353a95522c8">

**Comment by bschorchit** [comment]
Closing this as it doesn't currently impact our metrics dashboard.
