### ISSUE TITLE
[Bug]: Within the 'Tokens' tab, the balances of account assets may display as 0 before reverting to their actual balances, balances displayed on the send screen may occasionally show as 0

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24154]
### Describe the bug

Within the 'Tokens' tab, the balances of account assets may display as 0 before reverting to their actual balances. Balances displayed on the send screen may occasionally show as 0. Also 'Max' button on the send screen randomly disappears and appears again.

### Expected behavior

-

### Screenshots/Recordings

Fluctuations in the balances of tokens within the 'Tokens' list for the same account:

<img width="553" alt="0values" src="https://github.com/MetaMask/metamask-extension/assets/104780023/39d2ccc4-0b66-4c0e-a3db-2199174a8c25">

<img width="553" alt="less0s" src="https://github.com/MetaMask/metamask-extension/assets/104780023/9b817853-d611-4f78-84a6-e07bea541209">

Option to send 'Max' value is not displayed:

<img width="414" alt="noMax" src="https://github.com/MetaMask/metamask-extension/assets/104780023/9c654df4-3874-4ad5-9f37-c78e46c301ca">

USDT balance appears within the 'Tokens' list:

https://github.com/MetaMask/metamask-extension/assets/104780023/bfd2d73d-984f-478b-bfc1-c29f6a2c01c6

 0 MATIC on the send screen while the actual balance is correctly displayed on another screen:

https://github.com/MetaMask/metamask-extension/assets/104780023/374b51eb-87ad-48a7-a299-6acc9609a284

### Steps to reproduce

1. Open MetaMask extension
2. Have an account with different tokens
3. Notice that not all token balances correctly reflect the actual values
4. Try to send a token other that ETH
5. 'Max' button may occasionally disappear from the send screen, token's balance on the send screen may show '0' instead of actual balance

### Version

latest send+swap [build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN)

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by BZahory** [comment]
Balance issue is no longer present in the latest build. The Max button issue was resolved in fd73f29096efe329a4271746cd8045dd1a462c55

https://github.com/MetaMask/metamask-extension/assets/44588480/97b6bb92-6592-4196-b863-6494c905c7be
