### ISSUE TITLE
[Bug]: Smart Transactions - The link for View transaction is broken

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24158]
### Describe the bug

The link for View Transaction lands me to the portfolio dapp with a `Something went wrong` message

### Expected behavior

Not sure if we should go to the Portfolio dapp (a correct page) or Etherscan.

### Screenshots/Recordings

![Screenshot from 2024-04-22 11-15-26](https://github.com/MetaMask/metamask-extension/assets/54408225/0a72130a-2a76-4950-89a8-9ef5b6dc0c3c)

https://github.com/MetaMask/metamask-extension/assets/54408225/e86da437-8407-474e-abf7-502231b4bd91

### Steps to reproduce

1. Enable Smart Transactions
2. Perform a tx
3. Click View Transaction
4. See portfolio dapp with `Something went wrong` error

### Version

11.15.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by forest-diggs-consensys** [comment]
this is likely just related to the network (Sepolia vs. Ethereum mainnet)

**Comment by klejeune** [comment]
This issue has been acknowledged, but it is not a current priority. Closing for now, but feel free to reopen if needed in the future.
