### ISSUE TITLE
[Bug]: Smart Transactions - Not seeing the `Submitting your transaction` screen for tx signed using a hardware wallet

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24160]
### Describe the bug

Whenever I am using a hardware wallet, if I enable the Smart Transactions and I perform a transaction I land into the Home screen and I don't see the `Submitting your transaction` intermediate screen

### Expected behavior

Not sure, but possibly we should display the `Submitting your transaction` screen, once we approve the tx in the device?

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/ef6423ea-ef02-4589-91f3-e104ea125ace

This shows for regular accounts but not for hardware wallets:

![Screenshot from 2024-04-22 11-46-46](https://github.com/MetaMask/metamask-extension/assets/54408225/ac0370cf-e56c-4573-b2be-853975168a35)

### Steps to reproduce

1. Enable smart transactions
2. Import a hardware wallet account (ie ledger, QR code acct etc)
3. Start a tx
4. Confirm it
5. Confirm it with the device
6. See no `Submitting your transaction` screen appears in this flow

### Version

11.15.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by forest-diggs-consensys** [comment]
@seaona I'm closing this one since this will soon be the pattern for all transactions.
