### ISSUE TITLE
[Bug]: Not ellipsing long NFT ID within simulations

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#24178]
### Describe the bug

We show too many numbers for long NFT ids causing the name component to be very small.

### Expected behavior

We should show less numbers for long NFT ID within simulations and allow users to see the full id with the tooltip. 

### Screenshots/Recordings

![Screenshot 2024-04-22 at 14 03 10](https://github.com/MetaMask/metamask-extension/assets/34968356/7ed1686d-ec73-4a93-94ac-fe4cd5a36a13)

### Steps to reproduce

Go to ENS on Sepolia test network and purchase an ENS name

### Version

11.14.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by SayaGT** [comment]
Lets truncate the NFT ID and only show first & last 4 characters of the ID. So it would look like `+ 1 #1234...7890`
