### ISSUE TITLE
[Bug]: Missing "X" close button in the notification 

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#24180]
### Describe the bug

I was looking at this flaky test related to the test-e2e-chrome-vault-decryption.
CircleCI - https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/77436/workflows/983b4b1c-104a-4acc-ad35-36fe09a03a29/jobs/2685234

I observed that the functionality of the notification has changed, the "X" close button is no longer present, and the text has been altered as well. The changes to the notification can be found in this PR: https://github.com/MetaMask/metamask-extension/pull/23155

I am uncertain whether the missing "X" functionality should be classified as a defect or if we need to update the automation script.

Note:- This test is executed only in the develop and release builds, which is why it was not reproduced in the initial PR that contained the changes.

### Steps to reproduce

Run the test-e2e-chrome-vault-decryption locally against develop build and master
yarn
yarn dist
yarn test:e2e:single test/e2e/vault-decryption-chrome.spec.js --browser=chrome --debug --leave-running

<img width="361" alt="develop-build" src="https://github.com/MetaMask/metamask-extension/assets/153644847/2e1104ba-1341-4ee3-ad6d-128269c415b7">
<img width="1193" alt="master-build" src="https://github.com/MetaMask/metamask-extension/assets/153644847/ae6ecd2c-6dce-4fa4-ae70-257e3ffa2f8b">

### Version

11.15.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by forest-diggs-consensys** [comment]
Thanks for raising this - this is the expected behavior for this notification modal. The "what's new" modal behaves differently since it can contain multiple notifications/alerts.

**Comment by hjetpoluru** [comment]
Thank you for clarifying the expected behavior, where the new notification will not feature an 'X' button and the user must choose between the two provided options. Also, I will update the automation test as I have already have fix with the potential options.
