### ISSUE TITLE
[Bug]: Faulty scam warning message 

### ISSUE THREAD

**Issue by Mameta29** [MetaMask/metamask-extension#24186]
### Describe the bug

One of our customers receives the following advert:

This is a fraudulent request.
If you authorise this request, a third party known for fraud will seize all your assets.

Well, that's very unpleasant for us. We are Not a scam.

There are those problems at 2 sites.
- our domein : [edoverse.io](http://edoverse.io/)
1. site : https://www.marketplace.edoverse.io/edojofudosan
    contract address : [0xb70ad3d259bbca6c611f3858f153bde032700fb5](https://etherscan.io/address/0xb70ad3d259bbca6c611f3858f153bde032700fb5)
2. site : https://fttoken.edoverse.io
    constract address : 0xF95D0121d0e6fCe29F9D98F821440e4ec486163C

![image (2)](https://github.com/MetaMask/metamask-extension/assets/102901017/b4c6a901-20fe-40dc-ba78-c2a4a6c8b3f1)

### Steps to reproduce

The problem cannot be reproduced in general. This problem does not occur with other customers.

### Version

the latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @Mameta29. Thanks for reporting! Please use the Report an Issue form to flag this to the appropriate team.

**Comment by Mameta29** [comment]
@anaamolnar 
Thank you for your an advise and added the label !

**Comment by Mameta29** [comment]
@bschorchit 
I hasn't yet solved. Why did you closed?
