### ISSUE TITLE
lost connection to MetaMask after rejecting a transaction

### ISSUE THREAD

**Issue by or2008** [MetaMask/metamask-extension#2420]
when a user rejects a web3 transaction, looks like metamask doesn't call the provided callback anymore.

see attached image: 
![image](https://user-images.githubusercontent.com/3414979/31849019-40408c46-b644-11e7-834f-2bfa5be90d2b.png)

**Comment by nteymory** [comment]
+1 
Was about to write up this issue myself. It also occurs when canceling out of a signing operation. Here is a simple example that reproduces the problem: https://gist.github.com/nteymory/86b840ef0bedacb531ac4dc6017790bc.

Just reject the metamask prompt.

**Comment by or2008** [comment]
updated to 3.11.2 version and it works fine, I am closing this issue
