### ISSUE TITLE
Dockerize our E2E tests setup in order to reduce flakiness

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#24221]
### What is this about?

Tests fails in CircleCI and does not fail locally.
Setting up Dockerization for the CircleCI job would help identify and fix the issue with the test.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by chloeYue** [comment]
Close this ticket as the enable VNC over ssh PR has been merged.
PR here: https://github.com/MetaMask/metamask-extension/pull/26106
