### ISSUE TITLE
MV3: Add flag to disable MV3 service worker keep alive code

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#24224]
The `saveTimestamp` function is called at an interval in background.js to prevent the service worker from dying. We should put this behind a flag, so that we can disable this behaviour easily.

Once this behaviour is disabled, we should test how the extension behaves if/when dapps communicate with the extension after the service worker has been termined

**Comment by danjm** [comment]
To complete this task:
- this code needs to be in an if block: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/background.js#L287-L292
- the if condition should be a boolean property `enableMV3TimestampSave`
- that property should be managed by the preferences controller, and should default to true
- the property should be controlled by a toggle in settings in the new "Developer Options" section, that was introduced in this PR https://github.com/MetaMask/metamask-extension/pull/22382 (so the toggle will not be visible on production builds)

Once the above is done, we should able to toggle the functionality on and off in MV3 dev builds, and see the timestamp saving when toggled on and not saving when toggled off

**Comment by DDDDDanica** [comment]
@danjm Do you have the copy for new toggle in developer options?
> the property should be controlled by a toggle in settings in the new "Developer Options" section, that was introduced in this PR https://github.com/MetaMask/metamask-extension/pull/22382 (so the toggle will not be visible on production builds)
