### ISSUE TITLE
[Bug]: Missing methods `eth_getBlockReceipts` and `eth_maxPriorityFeePerGas`

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/metamask-extension#24225]
### Describe the bug

When running the API Spec tests I ran into these methods not being supported. Ideally they are added to the unrestricted method list, or even that list could come from api-specs.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/364566/81cca891-305a-4979-90d5-ea2ead0d60f3)

### Steps to reproduce

1. check api-spec tests in circleci (only on sj/api-spec-tests atm)
2. check the failures
3. see the methods not supported

## Error or Response
```
The method "eth_maxPriorityFeePerGas" does not exist / is not available.
```

### Version

sj/api-spec-tests

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

test build

**Comment by alexandratran** [comment]
The standard versions of `eth_subscribe` and `eth_blobBaseFee` are also not supported and should be added to the appropriate list.

**Comment by hjetpoluru** [comment]
With the current report generated [here ](https://output.circle-artifacts.com/output/job/298f6ada-f230-4a28-bc04-f3d51af2948b/artifacts/0/html-report/index.html). I dont see any request call with eth_maxPriorityFeePerGas and may have been fixed this PR https://github.com/MetaMask/api-specs/pull/249 and hence closing this ticket.
