### ISSUE TITLE
[Bug]: yarn start:mv3 with errors!

### ISSUE THREAD

**Issue by cuiweixie** [MetaMask/metamask-extension#24234]
### Describe the bug

<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/1579517/cd17a5db-d8b5-4a84-973c-483ab370edb9">   
errors:   

![image](https://github.com/MetaMask/metamask-extension/assets/1579517/89f4571e-5e77-49e0-8f7f-43a71c770b25)
![image](https://github.com/MetaMask/metamask-extension/assets/1579517/aee3fb2a-79e0-41e1-876c-8d4a99ea5636)

### Expected behavior

work normally!

### Steps to reproduce

chrome version 124.0.6367.62 (arm64)
1. yarn start:mv3
2. load dist/chrome to chrome browser.
3. click metamask plugin will trigger the error.

### Version

develop branch

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Hi @cuiweixie , we merged a [fix](https://github.com/MetaMask/metamask-extension/pull/24060) last week for `yarn start:mv3`. Do you still have this issue on latest version of `develop` branch?
cc @MetaMask/extension-platform for visibility

**Comment by cuiweixie** [comment]
it's ok now.

**Comment by gauthierpetetin** [comment]
Nice, thanks for the feedback @cuiweixie . Closing this issue now.
