### ISSUE TITLE
Enhance the clarity of error messages for CircleCI failures

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#24248]
### What is this about?

During a team pair programming session aimed at debugging a flaky test, we discovered that the error log provided by CircleCI was not helpful in diagnosing the cause of the failure.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by chloeYue** [comment]
Close this one as the enhance log will be implemented in page object modal.
