### ISSUE TITLE
[Bug]: `wallet_switchEthereumChain` never emits `chainChanged` if `net_version` RPC is disabled

### ISSUE THREAD

**Issue by holic** [MetaMask/metamask-extension#24247]
### Describe the bug

I have a chain where the old RPC method `net_version` was not enabled/whitelisted by default and we noticed that MetaMask switching chains to this network would not emit the `chainChanged` event that tools like wagmi depend on.

### Expected behavior

I would expect MetaMask to use `eth_chainId` for this initial call, or at least fallback to it, so `chainChanged` can be properly emitted in cases where `net_version` is not supported by the RPC.

### Steps to reproduce

Add a chain where the RPC method `net_version` is disabled. Specifically, ours returned
```json
{"error":{"code":-32610,"message":"rpc method is not whitelisted"},"id":9999,"jsonrpc":"2.0"}
```

Listen for `chainChanged` events with:
```
window.ethereum.on('chainChanged', (chainId) => console.log('MM switched to chain', chainId));
```

Then call `wallet_switchEthereumChain` to the target chain. You'll see the RPC call return but you won't see an event emission, even though the MetaMask extension will have switched to that chain.

### Error messages or log output

Unclear where to find errors/logs in MetaMask extension.
### Version

11.14.1

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by holic** [comment]
I was previously seeing an issue with deleting these custom networks but turns out MetaMask won't let you delete a network you're currently connected to. I was able to delete it after switching to another network.

**Comment by holic** [comment]
Okay, narrowed this down to MetaMask not handling a lack of `net_version` RPC method. Updated the PR description.

**Comment by vandan** [comment]
from @jiexi :

> https://github.com/MetaMask/providers/blob/4f12239247b30a03884df5c6623429d215e78e4f/src/StreamProvider.ts#L198-L202
> networkVersion ends up being sent to the provider as loading if net_version fails which is explicitly guarded against in the lines linked in Provider

**Comment by vandan** [comment]
Possibly related to: https://github.com/MetaMask/metamask-extension/pull/20652
