### ISSUE TITLE
[Bug]: `eth_getTransactionCount` with a bad address gives "network does not support ENS" error

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/metamask-extension#24246]
### Describe the bug

When providing a bad address, `eth_getTransactionCount` errors with an error message about not supporting ENS. 

### Expected behavior

Ideally this should error with `invalid address`

### Steps to reproduce

1. see test output here: https://output.circle-artifacts.com/output/job/bffd2656-2b53-48e0-b110-bc0437fd8100/artifacts/0/html-report/index.html#/details/46

### Error messages or log output

request
```json
{
  "id": 46,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionCount",
  "params": [
    "0x0Bc,e74408D1f8Cb8B67FED245,18f3aDAd00292",
    "pending"
  ]
}
```

response
```json
{
  "id": 46,
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "data": {
      "originalError": {
        "code": "UNSUPPORTED_OPERATION",
        "network": "unknown",
        "operation": "getResolver",
        "reason": "network does not support ENS"
      }
    },
    "message": "network does not support ENS (operation=\"getResolver\", network=\"unknown\", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)"
  }
}
```

### Version

sj/api-spec-tests

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

test build on sj/api-spec-tests

**Comment by vandan** [comment]
Relates to: https://github.com/MetaMask/metamask-extension/pull/14822
Didn't make the change mainly due to lack of procedures for dev outreach.
