### ISSUE TITLE
[Bug]: Duplicated transaction requests

### ISSUE THREAD

**Issue by hawkofsky** [MetaMask/metamask-extension#24249]
### Describe the bug

When I connect to arbiscan.io to interact with contract, any transaction request triggers multiple transaction requests in metamask.
It happens most of time.
So I checked the console of chrome browser and I found metamask conflicts with tronlink.
In the past, i didn't have such issue so it means the previous version of metamask didn't conflict with tronlink. but new version (11.14.1 updated at April 23, 2024) conflicts with tronlink, I think. 
In the browser console (Inspect), it says tronlink provider initialized 6 times. and when i click contract function to interact with the contract, metamask shows 7 transaction requests of same function to be confirm.
I disabled tronlink extension and it was resolved.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/53114416/5f21d876-bd44-4ecf-b48a-7a1a5e4b4ad0)
![image](https://github.com/MetaMask/metamask-extension/assets/53114416/643ec608-7ffe-4ae9-a747-6785615c2116)

### Steps to reproduce

1. Install tronlink chrome extension.
2. Install metamask chrome extension.
3. open link https://arbiscan.io/token/0xaf88d065e77c8cc2239327c5edb3a432268e5831#writeProxyContract
4. use any amount and address to call approve function

### Version

11.14.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Severity

This is visible to all users who installed both of metamask and tronlink.
And it's so annoying.

**Comment by hjetpoluru** [comment]
Unable to reproduce the issue. [hawkofsky](https://github.com/hawkofsky) could you please confirm if the issue exist.
