### ISSUE TITLE
Metamask can't send a transaction with Base or Blast chains - chain ID not found

### ISSUE THREAD

**Issue by Cavin72** [MetaMask/metamask-extension#24268]
### Describe the bug

I use metamask extension to work with Base chain (id 8453) - I'm sure I have add it correctly.
Metatmask extension version: 11.14.1

About 3 days ago this problem starts:
When I try to do any spend on Base chain it starts ok (but show "There was an error loading your estimation." on confirmation page). When I click "Confirm" button I see error: 
An internal error was received. Request Arguments: chain: undefined (id: 8453) from: 0x42f2......BD to: 0x1195cf65f83b…
And notification: Transaction NaN i failed: Internal JSON-RPC error.
On some swap sites report as Error code: -32603

I have update Metatmask to the latest version. I have enough gas to complete transaction on my account.

Smae problem with Blast chain.

However there is no such problem with Ethereum or for ex. zkSync chains.

### Expected behavior

Complete transaction

### Steps to reproduce

Switch to Base chain
Send any amount from one account to another

### Version

11.14.1

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by bschorchit** [comment]
@Cavin72 are you still encountering this issue on the latest versions (v12.0)?

**Comment by hjetpoluru** [comment]
We're able to transfer amount in the base network and attached is the video for reference. cc [adrigug](https://github.com/adrigug)
https://github.com/user-attachments/assets/93ec37b6-9fc6-4cff-9bed-00567c82ae87
