### ISSUE TITLE
MetaMask Encontered an error

### ISSUE THREAD

**Issue by ninjaswapapp** [MetaMask/metamask-extension#24265]
### What is this about?

Hi i added a new network and then extension crashed i dont want to re-install application , is there any way to disable or switch network inside local storage settings of extension ? 

`Message: Cannot destructure property 'chainId' of '(0 , t.useSelector)(...)' as it is undefined.`

![Screenshot from 2024-04-27 03-02-52](https://github.com/MetaMask/metamask-extension/assets/79689190/c204e4a0-08ca-46e6-92e6-08b3c9de1b22)

added RPC : https://rpc.ankr.com/polygon_mumbai
**Extension In google Chrome , OS Ubuntu**

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by anaamolnar** [comment]
Hi there, @ninjaswapapp Thanks for reporting! Would you mind updating manually to the latest version and letting us know if you still experience this issue? Thank you!

**Comment by anaamolnar** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/25043
