### ISSUE TITLE
[Bug]: Metamask wallet reject on refresh of page using Rainbow connector

### ISSUE THREAD

**Issue by ayabelarbi** [MetaMask/metamask-extension#24267]
### Describe the bug

why, when my Dapp is refreshing for some metamask wallet, the wallet is disconnecting ? 

Not for every wallet, just some wallet connecting to metamask through RainbowKit. 

    "@rainbow-me/rainbowkit": "^1.3.2"

### Expected behavior

I am expecting, on refresh, to still have the wallet connected. The state connect is not working well, as it's disconnecting for some wallet while it's should be the case. 

const { connectors } = getDefaultWallets({
  appName: "My RainbowKit App",
  projectId: " ",
  chains,
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
});

AutoConnect, is set to true, so on refresh of the page, it should stay connected. 

### Steps to reproduce

1. Connect wallet trought rainbow wallet 
2. Refresh the page 
3. Disconnection happen 

### Version

 Throught @rainbow-me/rainbowkit": "^1.3.2"

### Build type

None

### Browser

Chrome, Firefox

### Operating system

Windows, MacOS

**Comment by vandan** [comment]
For issues like this, we recommend moving to RainbowKit v2.x for improved EIP-6963 support:
https://www.rainbowkit.com/docs/migration-guide
