### ISSUE TITLE
[Bug]: Fees are updating so fast on Metamask, I paid 0.74$ fee on base L2 while on L1 mainnet gwei is at 9 (0.60$). It was showing 0.04$ when I confirmed

### ISSUE THREAD

**Issue by akincibor** [MetaMask/metamask-extension#24270]
### Describe the bug

[Bug]: Fees are updating so fast on Metamask, manual edit doesn't works, I paid 0.74$ fee on base L2 while on L1 mainnet gwei is at 9 (0.60$). It was showing 0.04$ when Tx was confirmed but when check Tx I found I paid 0.74$ for it. I am not going to verify each of my latest transactions but probably lost 20$ fees for nothing due to Metamask latest update! I'm moving to OKX wallet unfortunately.

### Steps to reproduce

.

### Version

Latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
I'm closing this issue as the bug has been resolved and rolled out to users on v11.14.3. Reach out if there's anything we can support you with.
