### ISSUE TITLE
Metamask web3 doesn't return status in transaction receipt

### ISSUE THREAD

**Issue by mihasK** [MetaMask/metamask-extension#2427]
Version of metamask: 3.11.2

Expected behavior:

Transaction receipt should contain  `status` with value `1` or `0`

**Comment by tmashuang** [comment]
I believe this is still an open discussion here, [Embedding transaction return data in receipts](https://github.com/ethereum/EIPs/pull/658)

**Comment by tmashuang** [comment]
Seems that transactions after block 4370000 should have the transaction status when using `web.eth.getTransactionReciept(txReciept, (err, res) => console.log(res))`

**Comment by mihasK** [comment]
@tmashuang I'm testing on ropsten, status should be there already (byzantium is already on ropsten)

**Comment by tmashuang** [comment]
I see now. Weird I got the `status` once, all attempts afterwards returns `root` in its place.

**Comment by tmashuang** [comment]
Seems to return the status when running the snippet above, closing for now. Will reopen if this is still and issue.
