### ISSUE TITLE
Process improvements

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#24289]
### What is this about?

TBD

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by benjisclowder** [comment]
This is lacking context and multiple different (more specific) issues have been opened for process improvements. Should we close this particular ticket, @hjetpoluru ?
