### ISSUE TITLE
Investigate the "Snaps execution environment failed to start" error

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#24290]
### What is this about?

Dan will add details

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by gauthierpetetin** [comment]
Fixed by Snaps team: https://github.com/MetaMask/snaps/pull/2389
Todo: import the changes in Extension repo
