### ISSUE TITLE
[Bug]: Signature Redesign - Signatures are broken with `Rendered more hooks than during the previous render.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24307]
### Describe the bug

Whenever enabling re-design, if I trigger a signature I get the MM error page `Rendered more hooks than during the previous render.`

### Screenshots/Recordings

![Screenshot from 2024-04-30 14-16-55](https://github.com/MetaMask/metamask-extension/assets/54408225/d0e065a4-f739-4f5e-a46c-1a63d71fc3fa)

### Steps to reproduce

1. Enable re-design from settings
2. Trigger a signature
3. See MM error

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
I added a sev-2 since this is not production, though there is no workaround to this issue

**Comment by jpuri** [comment]
PR https://github.com/MetaMask/metamask-extension/pull/24280/files#diff-5cc70a381cff8b41f2f920438cd1ea429932a215e8173ed28414bb1db09ba183R14 fixes this.

**Comment by bschorchit** [comment]
Closing as this has been fixed
