### ISSUE TITLE
feat: Remove ENABLE_CONFIRMATION_REDESIGN ENV variable from Signature Redesign related code

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#24312]
### What is this about?

We will no longer require the ENABLE_CONFIRMATION_REDESIGN ENV variable to show the new Signature Redesign for launch. 

Remove ENABLE_CONFIRMATION_REDESIGN from Signature Redesign related code. ENABLE_CONFIRMATION_REDESIGN will continue to be used for our upcoming Transaction Redesigns. 

Note: this issue should also cover enabling the preference toggle by default for new users.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by cryptotavares** [comment]
Also enable the redesign preferences toggle by default for new users
