### ISSUE TITLE
[Bug]: Editing a safeTransferFrom transaction request converts it to a transferFrom 

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#24320]
### Describe the bug

`safeTransferFrom` transaction requests are incorrectly converted to `transferFrom` transaction if users navigate to edit and then back to the transaction. 

Introduced on v11.9.0 with https://github.com/MetaMask/metamask-extension/pull/22228/

Expected to be fixed on v11.15.1 with https://github.com/MetaMask/metamask-extension/pull/24319

### Expected behavior

Transaction requests are not converted from safeTransferFrom to transferFrom.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/34968356/e40cdcf3-8ac7-4f7d-aa82-1200311d356c

### Steps to reproduce

1. On [MM test dapp](https://metamask.github.io/test-dapp/), connect to an account on Sepolia
2. Click on NFTs Deploy
3. Click on Mint
4. Go to your NFT contract on the Sepolia block explorer
5. Go to write Contract tab
6. Connect your wallet
7. Scroll to safeTransferFrom and fill in the info
8. Click write
9. On the MM popup, notice `safeTransferFrom` as the method
10. Click on edit on the confirmation
11. Click on Next button
12. Notice `transferFrom` as the method on the confirmation

Alternatively, you can also skip steps 1 to 4 and use [this link](https://sepolia.etherscan.io/address/0x07B6C897a68D53948422B534935C4f40c5F25DaE#writeContract). The only difference is that as you don't own the NFT you'll see warnings for gas estimation failures.

### Version

11.9.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by benjisclowder** [comment]
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
 
 We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
 
1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

cc: @darkwing

**Comment by benjisclowder** [comment]
> **Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
> 
> We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
> 
> 1. What PR fixed the issue?
> 2. Can you pinpoint the commit from which the issue originated?
> 3. Write a short explanation of the technical cause of the bug
> 4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
>    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
>    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
>    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
> 
> Please provide your answers as a reply to this comment and tag me as well.
> 
> You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!
> 
> Tagging eng. who added the fix: [@darkwing](https://github.com/darkwing)

Hi, @darkwing  , if you're not able to conduct RCA on this issue, is there anyone you can assign this to? I would very much appreciate it. Thank you!
