### ISSUE TITLE
[Bug]: Can no longer create new accounts

### ISSUE THREAD

**Issue by justinasfour04** [MetaMask/metamask-extension#24324]
### Describe the bug

I created a new account today. When I tried to create another new account Metamask would not let me create more accounts. Every time I press create now, I see the yellow loading circle and then nothing happens. It seems to be stuck for some reason 

### Expected behavior

A new account be created

### Steps to reproduce

1. Go to Select Account dropdown
2. Click Add Account or Hardware Wallet
3. Click add a new account
4. Name the new account
5. Press enter or click create

### Error messages or log output

```shell
I looked through the console or network tabs for an error and could not find anything
```

### Version

11.14.3

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by Bullcoiner** [comment]
Hi There, Thank you for reporting this to us. It has been reported to a team and will be looked at.

**Comment by danjm** [comment]
@justinasfour04 Can you share a screen recording of the reproduction of this bug?

**Comment by justinasfour04** [comment]
What's the best tool to use to record to show you?

**Comment by danjm** [comment]
Any screen recording tool is fine. If you are on a mac, you should be able to use the "New Screen Recording" option in Quicktime

**Comment by justinasfour04** [comment]
I'll get you that later today. But if I had to explain it basically when I click create new account nothing happens. The background stays grey. There is a yellow loading circle that shows up and then nothing happens. No errors in the console or network tab. I'm also at my 14th wallet being created on this PC that I'm using

**Comment by KaranKaira** [comment]
@justinasfour04  just tried this , I am able to create new account .
Did u try again ?

**Comment by justinasfour04** [comment]
Here is a screen recording
https://github.com/MetaMask/metamask-extension/assets/6599551/66828a69-5ad5-49aa-a017-dd16a62b87b2

**Comment by justinasfour04** [comment]
Seems like metamask does not like having duplicate wallets created after those same wallets have been imported. I just tried it out on firefox and when I have a wallet imported that matches the one that will get created metamask complains when creating new wallets and this happens as you can see in the video

**Comment by Jaspix** [comment]
I'm having this exact same issue after importing a bunch of wallets from a different browser

**Comment by desi** [comment]
I have tried to reproduce the error in 12.9.2 and RC 12.10.0 but I am unable to reproduce exactly this error so I am leaving it as closed. However, I was able to find some odd behavior that is related. Documented in #29303.

Please feel free to reopen if you are still experiencing the original issue.
