### ISSUE TITLE
[Bug]: MetaMask encounters errors when processing transactions initiated from dapp

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24336]
### Describe the bug

MetaMask encounters errors when processing transactions initiated from dapps.

### Expected behavior

Smooth and accurate transaction handling in scenarios involving extensive numerical data.

### Screenshots/Recordings

Ethereum mainnet, Chrome:

https://github.com/MetaMask/metamask-extension/assets/104780023/4ff70c21-8a29-411f-a6e6-8a81bc6f1993

Polygon, Chrome:

https://github.com/MetaMask/metamask-extension/assets/104780023/3f2442cb-ac08-4794-a37a-2ac12965e32b

<img width="358" alt="Screenshot 2024-05-01 at 18 29 58" src="https://github.com/MetaMask/metamask-extension/assets/104780023/1e9b07a9-28d4-4cf4-bc3a-566f92900472">

Polygon, Firefox:

https://github.com/MetaMask/metamask-extension/assets/104780023/64f61a7e-b871-461e-9982-bd3c781f4afe

Different error message for shorter number:

<img width="363" alt="Screenshot 2024-05-01 at 19 32 08" src="https://github.com/MetaMask/metamask-extension/assets/104780023/f70c226e-8e4c-4df0-b53e-bde4b67b9d36">

https://github.com/MetaMask/metamask-extension/assets/104780023/962ad496-9d78-4994-aea2-a1e9aaf58f19

### Steps to reproduce

1. Go to Uniswap / Pancakeswap etc.
2. Start swap transaction 
3. Proceed to MetaMask confirmation screen
4. See the error

### Version

11.16.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
MM error with short number:


https://github.com/MetaMask/metamask-extension/assets/104780023/c0dddfad-7d71-4624-a290-50f137e171bb

**Comment by davibroc** [comment]
I have investigated the issue and it looks like it's commit 9bf2c9e that causes the problem https://github.com/MetaMask/metamask-extension/commit/9bf2c9e929e330c6fe688781d5bcdd0ae6b23631

if I go back to commit  b3949d9 the problem doesn't happen

**Comment by sleepytanya** [comment]
The bug doesn't happen on swaps initiated from within the wallet:
<img width="465" alt="Screenshot 2024-05-03 at 10 46 43" src="https://github.com/MetaMask/metamask-extension/assets/104780023/69da6f33-9e5e-474c-a2d8-617436023b7d">
