### ISSUE TITLE
[Bug]: eth_getTransactionByHash stopped returning r, s, v

### ISSUE THREAD

**Issue by keithchew** [MetaMask/metamask-extension#24359]
### Describe the bug

The call to eth_getTransactionByHash (after calling eth_sendTransaction) used to return the signature of the transaction, ie r, s, v values. But a recent update is causing the r s v to be missing. Is this a regression issue?

### Expected behavior

Previous versions used to return rsv, expected to have the rsv values.

### Steps to reproduce

Snippet below:
```
        const web3Metamask = new Web3(window.ethereum);
        const txnId = await web3Metamask.currentProvider.request({
            method: 'eth_sendTransaction',
            params: [txn],
        });
        console.log(`txnId [${txnId}]`);
        const transaction = await web3Metamask.currentProvider.request({
            method: 'eth_getTransactionByHash',
            params: [txnId],
        });
        console.log(`r [${transaction.r}] s [${transaction.s}] v [${transaction.v}]`);
```

The transaction above will be missing the rsv values.

### Version

11.14.4

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by dbrans** [comment]
@keithchew great catch and good job tracking this down. I'm adding this bug as fixed by https://github.com/MetaMask/metamask-extension/pull/24701. I'll ping you on that PR to take a look.
