### ISSUE TITLE
fetchErc20Decimals should not use getTokenStandardAndDetails

### ISSUE THREAD

**Issue by dbrans** [MetaMask/metamask-extension#24374]
We are making 3-4 additional RPC requests for each ERC20 token during simulation renders. Given that 90% of transactions involve only a single token, and many of these are not ERC20 tokens, this extra load is generally manageable. However, for the 10% of transactions involving multiple ERC20 tokens, this can quickly add up.

For example, transactions with 10 or more tokens could result in 20-30 additional requests, which might impact performance and rate limits.

@bergeron [wrote](https://consensys.slack.com/archives/GTQAGKY5V/p1714773613632259?thread_ts=1714771396.130019&cid=GTQAGKY5V):

> I do suspect getTokenStandardAndDetails is used in some places it shouldn't.  It should only be used when we have an address and no idea what kind of token it is.  Because it has to cycle through all the standards.  For example this code just wants ERC20 decimals:
> ```
> async function fetchErc20Decimals(address: Hex): Promise<number> {
>   try {
>     const { decimals } = await getTokenStandardAndDetails(address);
>     return decimals ? parseInt(decimals, 10) : ERC20_DEFAULT_DECIMALS;
>   } catch {
>     return ERC20_DEFAULT_DECIMALS;
>   }
> }
> ```
> Which should be 1 RPC request since we already 'know' its an ERC20, but that could do up to 4 RPC requests (checking for NFTs and returning other ERC20 details other than decimals)

**Comment by bschorchit** [comment]
Data insight: transaction with 10+ tokens are represent less than 0.1%
