### ISSUE TITLE
uat: Can't edit account name

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2437]
Is there a way to edit an account name in UAT/NewUI? I can't find it.

**Comment by kidsil** [comment]
1. Click the hamburger (3 lines) menu on the left side
2. Click details ![image](https://user-images.githubusercontent.com/154950/34618778-c7791096-f237-11e7-8c7c-74a286ff4998.png)
3. On top you'll see a small edit icon next to the account's name
