### ISSUE TITLE
[Bug]: Confirmed Tx showed as failed

### ISSUE THREAD

**Issue by akincibor** [MetaMask/metamask-extension#24378]
### Describe the bug

Confirmed Tx showed as failed

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/99909324/593407ce-4661-44fe-ba40-2960f949177f

### Steps to reproduce

NA

### Version

latest

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Probably the same issue https://github.com/MetaMask/metamask-extension/issues/24183.

**Comment by dbrans** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/24701
