### ISSUE TITLE
[Bug]: Users may encounter difficulties when attempting to manually import ERC20 tokens on specific networks

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24381]
### Describe the bug

MetaMask manual importation of ERC20 tokens on certain networks doesn't work (Theta network). The 'Import Tokens' screen does not display the fields for the token address, symbol, or decimals. After attempting to import, the tokens do not appear in the 'Tokens' tab. 
However, on networks like Cronos and PulseChain, this issue can often be remedied by clicking the 'Back' button on the Import screen, which then presents the full view, allowing for successful token importation.

The issue is present on 11.14.4, 11.14.5, 11.16.0.

### Expected behavior

Users should be able to import ERC20 tokens manually.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/26400711-dfbe-4e13-9d23-4f3d9d8a259f

https://github.com/MetaMask/metamask-extension/assets/104780023/996688fd-dfaa-4e90-a173-a04167fd01ca

### Steps to reproduce

1. Connect to Theta, Cronos, PulseChain (may be other networks are also affected)
2. Try to manually import any ERC20 token
3. Notice the Import screen doesn't display all fields for token details
4. In some cases tokens can be imported (Cronos and PulseChain), on Theta network ERC20  can't be imported manually.

### Error messages or log output

```shell
No errors in the background console.
```

### Version

11.14.4, 11.14.5, 11.16.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gambinish** [comment]
Thank you for reporting this.

Closing this bug ticket, as this has been fixed in a later release. Confirmed that on chrome `v12.0.6` this issue was not apparent while importing TONIC and WCRO tokens on Theta Mainnet:

https://github.com/user-attachments/assets/a51e366e-0f77-43a4-8997-97ce12dbf644
