### ISSUE TITLE
uat: Too many clicks to copy address

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2438]
Having our account options in a menu behind a menu seems like a lot of work for some simple, frequently-used operations, like copying an address.

A couple ways I think we can make it easier:
- In the sidebar, clicking anywhere on that top section w/ the icon opens the menu (easier to click fast)
- Add a `copy` button next to the accounts in the account menu might be cool!

**Comment by chikeichan** [comment]
a6337340
