### ISSUE TITLE
[Bug]: Confirmations Redesign - Reject All does not display a confirmation popup

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24384]
### Describe the bug

Whenever I am rejecting Signatures in batch, I don't see any confirmation popup as I used to see before.

### Expected behavior

Show a confirmations popup before rejecting all

### Screenshots/Recordings

Confirmation Redesign - no popup after clicking Reject All

![Screenshot from 2024-05-06 09-58-36](https://github.com/MetaMask/metamask-extension/assets/54408225/66752952-7eca-4939-83f4-a39ee5053f2f)

Old design - popup

![Screenshot from 2024-05-06 09-59-12](https://github.com/MetaMask/metamask-extension/assets/54408225/e781d0bd-b58b-41d8-9a03-54bf42ffaf74)

### Steps to reproduce

1. Trigger multiple signatures
2. Click Reject All -- see all signatures are rejected right after

### Version

develop (re-design build)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by npismenkov** [comment]
@seaona Could you assign this bug on me? And I've a question. Do I have to ask to assign bug/feature on me before I start working on it? Or I can create PR even if the problem wasn't assigned to me?

**Comment by bschorchit** [comment]
This is intentional for now. We'll re-introduce the modal, if needed.
