### ISSUE TITLE
New functional component for Data deletion

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#24407]
Part of https://github.com/MetaMask/MetaMask-planning/issues/880
 
 To confirm the deletion when the Delete MetaMetrics Data button from Security & Privacy is clicked.

>  
> Title: Delete MetaMetrics data?
> Description: We are about to remove all your MetaMetrics data. Are you sure?
> Buttons: Clear & Cancel
> Clear button click:  Onclick of the button will create the delete regulation

**Comment by gauthierpetetin** [comment]
Fixed in this PR: https://github.com/MetaMask/metamask-extension/pull/24571
