### ISSUE TITLE
[Bug]: Smart Transactions on Sepolia Don't Work

### ISSUE THREAD

**Issue by pcaversaccio** [MetaMask/metamask-extension#24423]
### Describe the bug

I enabled Smart Transactions and when I interact with Sepolia and click on the transaction link in the MetaMask pop-up UI, the following happens (the transaction itself got successfully included if you check it on Etherscan):

![image](https://github.com/MetaMask/metamask-extension/assets/25297591/bf3f0f5a-5b62-4eb1-868c-1cfc3d53f4b0)

### Expected behavior

I expected that Smart Transactions only would be enabled for Ethereum Mainnet, so I was surprised to see it enabled for the Ethereum test network(s).

### Steps to reproduce

- Enable Smart Transactions
- Interact with Sepolia

### Version

11.15.2

### Build type

None

### Browser

Brave

### Operating system

Windows

**Comment by seaona** [comment]
Same/similar: https://github.com/MetaMask/metamask-extension/issues/24158
@dan437 mentioned Sepolia support is not there yet

**Comment by hjetpoluru** [comment]
@pcaversaccio Thanks for reporting the issue and closing the defect as its already be tracked.
