### ISSUE TITLE
[Bug]: TypeError: missing r

### ISSUE THREAD

**Issue by JeremyX2022** [MetaMask/metamask-extension#24431]
### Describe the bug

The transaction is successfully onto the chain, but just got this error and cannot catch the exception (seems it stucked inside).

### Screenshots/Recordings

![1715165502556](https://github.com/MetaMask/metamask-extension/assets/115964498/75c4be1a-3482-485b-ad97-d7c1bcf22418)

### Steps to reproduce

general steps to send a transaction

### Version

11.15.3 or 11.14

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by peterjurco** [comment]
I experienced the same error but seems to be solved by [this fix](https://github.com/MetaMask/metamask-extension/issues/24359#issuecomment-2124634895) and released in 11.16.0

**Comment by cryptotavares** [comment]
Closing as it is fixed by https://github.com/MetaMask/metamask-extension/issues/24359
