### ISSUE TITLE
[Bug]: Big Number Error

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24448]
### Describe the bug

When users attempt to conduct a swap from a dApp using numbers with a high number of decimals, MetaMask experience an error.

This bug was first found here [bug ticket](https://github.com/MetaMask/metamask-extension/issues/24336).

It was fixed by these PRs:

https://github.com/MetaMask/metamask-extension/pull/24382
https://github.com/MetaMask/metamask-extension/pull/24422
### Expected behavior
Accurate transaction handling.
-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/4cb5ab47-e874-4c18-8f89-b506d0d8e81a

### Steps to reproduce

1. Connect to Uniswap / Pancake / Sushi / etc
2. Swap amount with a high number of decimals
3. See MetaMask encounters Big Number error

### Version

latest build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by ejwessel** [comment]
I'm not seeing this happening anymore on `mb843/updates-2`
https://github.com/MetaMask/metamask-extension/assets/3590816/a99fc045-dc2c-4c1d-b1c1-c274a178e786

**Comment by sleepytanya** [comment]
Bugs was fixed by https://github.com/MetaMask/metamask-extension/pull/24382
                                https://github.com/MetaMask/metamask-extension/pull/24422


https://github.com/MetaMask/metamask-extension/assets/104780023/2b75d784-30c9-4036-a5c2-b049402c924d
