### ISSUE TITLE
[Bug]: Sending the maximum amount on the mainnet and allowing for gas fees to refresh cause simulation to fail

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24451]
### Describe the bug

When attempting to send the maximum amount and waiting for the gas fees to refresh, users encounter a message indicating 'This transaction is likely to fail' instead of seeing the estimated changes. Additionally, the 'Total' section appears due to the simulation failing.

### Expected behavior

Transaction estimations and simulations handled accurately.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/1bc5fe07-5cbb-4ef1-92da-19e360031f78

### Steps to reproduce

1. Go to mainnet
2. Start Send transaction
3. Set MAX amount
4. Click 'Continue'
5. Allow some time for gas fees to refresh
6. Notice simulation fails

### Version

latest build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
@BZahory @ejwessel 
Now we can't see if this bug is still happening since we don't have the confirmation screen for send+swap (except for the case when sending ETH -> ETH).

**Comment by sleepytanya** [comment]
This issue doesn't happen on 11.15.5, 11.17.0 and as mentioned above we now bypass the confirmation screen  so there is no place for the bug to exist. I never encountered this bug outside of send+swap.
@hesterbruikman

**Comment by hesterbruikman** [comment]
Great! So seems we can close these. Please reopen if I've misunderstood this @sleepytanya
