### ISSUE TITLE
[Bug]: Token balances displayed incorrectly, unable to send any tokens other that ETH

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24454]
### Describe the bug
  
1. When selecting a token in the Select Asset To Send modal, the displayed token balances are not accurate, with the exception of ETH, which appears to be displayed correctly. Upon a second attempt to send the same token, the balance is accurately reflected.
    Token balances on BNB seem to be more accurate but tokens are displayed in different order on Select Asset modal and in the Token tab.
2. Token balances on BNB has fiat values while on mainnet fiat value is shown for ETH only.

### Expected behavior

Token balances displayed correctly.
### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/d2ad38df-12da-4856-939e-32da05f8ee52

https://github.com/MetaMask/metamask-extension/assets/104780023/bdfa51f8-c055-4649-b3ac-d341429992c2

### Steps to reproduce

1. Start Send transaction
2. Select a token
4. Notice that token balances, with the exception of ETH, are being displayed as zero
5. Switch to BNB Chain
6. Notice that token balances on Token tab have fiat values 
7. Start Send transaction
8. Notice that tokens are displayed in different order and some of them may show 0 balance

### Version

Latest build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
@sleepytanya is this an issue that appears on the latest Swap and Send build or in production?

**Comment by sleepytanya** [comment]
@hesterbruikman I don't see it on develop and also on the latest send+swap build. I don't think I ever seen it outside send+swap flow.

**Comment by hesterbruikman** [comment]
Great! So seems we can close these. Please reopen if I've misunderstood this @sleepytanya
