### ISSUE TITLE
[Bug]: Misalignment on Send screen on Firefox

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24453]
### Describe the bug

A misalignment issue on the Send screen when using Firefox, where the arrows intended to switch the primary currency are not correctly positioned and overlap with the currency symbol.

### Expected behavior

All elements on the Send screen are properly aligned.

### Screenshots/Recordings

Firefox:

<img width="403" alt="Screenshot 2024-05-08 at 22 51 34" src="https://github.com/MetaMask/metamask-extension/assets/104780023/843fb81e-d2ea-4645-a69b-b379a2c85a58">

Chrome:

<img width="533" alt="Screenshot 2024-05-08 at 22 54 32" src="https://github.com/MetaMask/metamask-extension/assets/104780023/6da7def1-fa78-4d0c-b14b-0c246d9d5783">

### Steps to reproduce

1. Start Send transaction on Firefox
2. Notice arrows next to the currency symbol appear misaligned

### Version

latest build

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by BZahory** [comment]
<img width="1728" alt="Screenshot 2024-05-10 at 12 54 54 PM" src="https://github.com/MetaMask/metamask-extension/assets/44588480/704ad6e2-6956-4625-a78f-2a6069a9aa87">
No longer seeing this on the latest build

**Comment by sleepytanya** [comment]
Re-opening as it is present on the latest 11.14.4 build, Firefox 125.03:


https://github.com/MetaMask/metamask-extension/assets/104780023/ad730d23-21f3-4c6b-9fe6-7a4456a47a3e

@BZahory

**Comment by BZahory** [comment]
Fixed in the latest build

<img width="415" alt="Screenshot 2024-06-06 at 1 22 31 AM" src="https://github.com/MetaMask/metamask-extension/assets/44588480/f1afe612-a6c8-478c-bb1f-2377ca6a7414">
