### ISSUE TITLE
[Bug]: On the BNB Chain the gas fees displayed on the confirmation screen may not be refreshing as expected

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24452]
### Describe the bug

I was checking if [the same bug](https://github.com/MetaMask/metamask-extension/issues/24451) is present on the BNB Chain. The issue is not happening in BNB, but there seems to be a concern with gas fees not refreshing as they should or the UI doesn't reflect changes in the gas fees (when the actual amount remains unchanged but the gas fee is refreshed, screen provides a visual indication- a brief blink).

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/2e3cee84-8321-479b-8f63-6dffeb0b2d4b

### Steps to reproduce

1. Switch to BNB Chain
2. Start Send transaction
3. Click 'Continue'
4. Wait for the gas fee to refresh
5. Notice that fee stays unchanged and there is no visual indications that gas is being refreshed

### Version

latest build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by BZahory** [comment]
This was most likely related to my Infura account gas API setting and seems to be fixed in the latest build

https://github.com/MetaMask/metamask-extension/assets/44588480/842e8443-2ee2-486a-8f68-227782257e09

**Comment by sleepytanya** [comment]
https://github.com/MetaMask/metamask-extension/assets/104780023/f4588dad-cb4d-4f12-a173-cd392e06ea46
