### ISSUE TITLE
[Bug]: When users edit a transaction, the information entered in the destination asset input field may not be preserved as expected

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24465]
### Describe the bug

Destination asset input isn't remaining intact when transaction is edited.
- change destination token once (e.g. USDC when sending ETH)
- change destination token again (e.g. WBTC)
- click "Continue"
- click "Edit" to return to Send screen
- destination asset is appearing as previously selected token

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/6983fc98-1d6a-4b27-a3ea-573bd0a74ecd

### Steps to reproduce

1. Start Send transaction
2. Change destination token once (e.g. USDC when sending ETH)
3. Change destination token again (e.g. WBTC)
4. Click "Continue"
5. Click "Edit" to return to Send screen
6. Notice destination asset is appearing as previously selected token

### Version

latest build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by BZahory** [comment]
We now bypass this screen all together

**Comment by sleepytanya** [comment]
@BZahory let's not close it yet in case the bypass decision is not final?

**Comment by BZahory** [comment]
Downgrading from a blocker since we no longer use the confirmations screen

**Comment by sleepytanya** [comment]
Closing as we don't show the confirmation screen for send+swap flow and bug can't happen.
