### ISSUE TITLE
uat: Enhance corner fox

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2447]
We can definitely use a higher res fox in the top left corner, maybe use a forward-facing one like this:

![screen shot 2017-10-23 at 12 49 24 pm](https://user-images.githubusercontent.com/542863/31909920-9c465162-b7f0-11e7-90d5-abe260c0eced.png)

Also maybe a little bigger?
Also: I think clicking it should go to the main account screen.

**Comment by chikeichan** [comment]
@danfinlay @MetaMask/design Can we get a version of this with transparent background?

**Comment by chikeichan** [comment]
8d3a317b - Show home page when metafox is clicked

**Comment by cjeria** [comment]
@danfinlay @chikeichan this one's ready. https://invis.io/G9CESQXW6#/246400884_Metamascara_-_Flat_Accounts_1

![metamascara - flat accounts 1](https://user-images.githubusercontent.com/597770/32079248-d1aef24e-ba5e-11e7-8918-3ce057adccac.png)

**Comment by bdresser** [comment]
request for click -> home screen here #2248
