### ISSUE TITLE
[Bug]: Non-numerical characters can be entered on the Send screen, Firefox

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24491]
### Describe the bug

 Non-numerical characters can be entered on the Send screen, leading to the transaction being created with an amount of 0. This issue doesn't exist on Chrome.

Build 11.14.4

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/0e7e353b-7938-47b9-a934-1dad6f53cc1d

### Steps to reproduce

1. Start Send transaction
2. Type in non-numerical characters into amount field

### Version

Latest build

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Present on 11.17.0:


https://github.com/MetaMask/metamask-extension/assets/104780023/9e8f94d9-4c8e-4eea-a927-4207369353cb


https://github.com/MetaMask/metamask-extension/assets/104780023/c3d7043d-8b71-4e2a-b8bc-90755353c1af

**Comment by hesterbruikman** [comment]
@ejwessel can we close this issue as per your commit?

**Comment by ejwessel** [comment]
@hesterbruikman yes idk why it wasn't closed eralier.
