### ISSUE TITLE
[Bug]: Unable to confirm Send transaction from the Tokens tab, 'Continue' button is inactive

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24490]
### Describe the bug

If Send transaction started from the Tokens tab, token balance displayed correctly, quotes are fetched but Continue button stays inactive and tx can't be submitted.

Some tokens doesn't have balance shown (screenshots below).

Build 11.14.4 (I don't put it in the 'build' field so 11.14.0 regression label doesn't apply automatically)
### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/86d82e19-b509-40d0-b1b1-d29a99ea5461

<img width="521" alt="Screenshot 2024-05-10 at 18 26 55" src="https://github.com/MetaMask/metamask-extension/assets/104780023/2784c673-50b5-4061-9c4d-8f80b98e9c95">

<img width="580" alt="Screenshot 2024-05-10 at 18 23 42" src="https://github.com/MetaMask/metamask-extension/assets/104780023/3cbb0e2c-85f3-41a8-b496-91dce17aa1bb">

<img width="582" alt="Screenshot 2024-05-10 at 18 27 49" src="https://github.com/MetaMask/metamask-extension/assets/104780023/6fdd5bec-0c0b-4eba-9c2c-38e33804d713">

### Steps to reproduce
1. Navigate to the Tokens tab
2. Start Send transaction by clicking on token other that ETH that has actual balance
3. Click Send button
4. Select amount and destination token
5. Notice Continue button is unavailable
6. Try to select different tokens and notice that balances are not displaeyd for some of them

### Version

latest build

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Sending FalconSwap for Tokens tab. Balance is not present on the Token screen and balance marked as 'undefined' in the Send screen:


https://github.com/MetaMask/metamask-extension/assets/104780023/d4b0d18b-8201-4379-82cd-eb7dd61f8b41

**Comment by ejwessel** [comment]
I'm unable to reproduce the above. I wonder if a part of the problem is the account's api not having processed an account or tokens at times.
