### ISSUE TITLE
uat: Make key downloading actually download

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2450]
Currently, clicking "Download" on the "Download Private Key" screen actually shows the private key on screen, which could cause security mishaps.

Short term fix: Change verbage from "Download" to "Show".

Long term fix: Download a file

There is a standard key storage format that we could easily export to on this screen (and we already support importing), and we probably should use it.

It has one additional requirement: We need the user to provide a password to encrypt the downloaded file with.

![screen shot 2017-10-23 at 1 20 42 pm](https://user-images.githubusercontent.com/542863/31911327-246ff4c2-b7f5-11e7-9563-34c07c472599.png)

**Comment by chikeichan** [comment]
ebb2d384
