### ISSUE TITLE
[Bug]: The amount in the 'From' field is not rounded correctly (Firefox)

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24505]
### Describe the bug

The amount in the 'From' field is not rounded as expected, with the last digits that should be rounded being displayed, and additional digits only revealed upon hovering over with a tooltip.

### Expected behavior

-

### Screenshots/Recordings

<img width="421" alt="Screenshot 2024-05-13 at 21 12 03" src="https://github.com/MetaMask/metamask-extension/assets/104780023/2ac832fd-72d1-4b8a-8969-56285feabc37">

<img width="424" alt="Screenshot 2024-05-13 at 20 51 19" src="https://github.com/MetaMask/metamask-extension/assets/104780023/261b0a40-6f88-431e-a52c-6f0d85116566">

<img width="400" alt="Screenshot 2024-05-12 at 01 17 01" src="https://github.com/MetaMask/metamask-extension/assets/104780023/b09fb72e-2619-46ec-9755-9e592d547020">

<img width="406" alt="Screenshot 2024-05-13 at 21 13 50" src="https://github.com/MetaMask/metamask-extension/assets/104780023/6e728559-31a5-4276-be2f-3a50b4a46271">

### Steps to reproduce

1. Start Send transaction
2. Enter long number into 'From' field
3. Notice that amount is not rounded correctly

### Version

latest build

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
When currencies switched token symbol is not shown:

<img width="450" alt="Screenshot 2024-05-17 at 18 17 31" src="https://github.com/MetaMask/metamask-extension/assets/104780023/7c17316e-b3e9-48b1-8872-9210e10a822a">

**Comment by micaelae** [comment]
is this only happening in firefox? if so, it might be due to [expected inconsistent behavior](https://bugzilla.mozilla.org/show_bug.cgi?id=860329)

**Comment by sleepytanya** [comment]
Yes, happens only in Firefox! Should we close it?

**Comment by hesterbruikman** [comment]
@micaelae It looks like your fix was merged, but this issue was not auto-closed. Does it make sense to close this ticket?
