### ISSUE TITLE
[Bug]: MetaMask - RPC Error: Ledger: Unknown error while Signing transaction

### ISSUE THREAD

**Issue by Spider-yuchen** [MetaMask/metamask-extension#24506]
### Describe the bug

Using matemask to connect to Ledger to send a transaction, Ledger will not pop up the signature, the transaction fails on matemask, console error: MetaMask - RPC Error: Ledger: Unknown error while signing transaction

### Expected behavior

Ledger Hardware Wallet Signs and Sends Transactions Properly

### Steps to reproduce

Select ledger address wallet on matemask, 
send transaction, 
enter amount, 
comfirm

### Error messages or log output

```shell
MetaMask - RPC Error: Ledger: Unknown error while signing transaction
```

### Version

11.12.2

### Build type

None

### Browser

Microsoft Edge

### Operating system

Windows

### Hardware wallet

Ledger

### Additional context

Ledger Nano X v2.2.3

**Comment by DanielTech21** [comment]
Hi @Spider-yuchen ,

Please update your MetaMask extension wallet version to 11.15.2. and disable other extensions on your browser.
You can use the official website - https://metamask.io/download/

To ensure a seamless experience when using your Ledger device with MetaMask, please adhere to the following guidelines:
 
Close Ledger Live: Ledger Live should be closed to avoid conflicts when MetaMask attempts to connect to your Ledger device.
Please unlock your Device: Ensure your Ledger is unlocked and the Ethereum application is open.
Update Your Device and Apps:
Firmware: Verify that your Ledger or Trezor device runs the latest firmware version.
Ethereum App: Reinstall or update the Ethereum app on your Ledger through Ledger Live (Manager section).
Browser Compatibility: Make sure that your internet browser is up to date.
Enable Contract Data: In the Ethereum app settings on your Ledger device, enable "Contract data".
For detailed instructions on how to connect and use your Ledger or Trezor with MetaMask, please visit our guide here: [How to connect a Trezor or Ledger Hardware Wallet](https://metamask.zendesk.com/hc/en-us/articles/360020394612).
 
Additional Steps for Ledger Users:
 
Enable Blind Signing: To manage ERC-20 tokens and interact with smart contracts, turn on "Blind Signing" in the Ethereum app settings on your Ledger device.
Connect Ledger to MetaMask: Follow the specific steps provided on Ledger's support page to connect your Ledger device to MetaMask correctly. [Connect your Ledger to MetaMask](https://support.ledger.com/hc/en-us/articles/4404366864657).

Let me know if you still need help with the error.

**Comment by Spider-yuchen** [comment]
> Hi @Spider-yuchen ,
> 
> Please update your MetaMask extension wallet version to 11.15.2. and disable other extensions on your browser. You can use the official website - https://metamask.io/download/
> 
> To ensure a seamless experience when using your Ledger device with MetaMask, please adhere to the following guidelines:
> 
> Close Ledger Live: Ledger Live should be closed to avoid conflicts when MetaMask attempts to connect to your Ledger device. Please unlock your Device: Ensure your Ledger is unlocked and the Ethereum application is open. Update Your Device and Apps: Firmware: Verify that your Ledger or Trezor device runs the latest firmware version. Ethereum App: Reinstall or update the Ethereum app on your Ledger through Ledger Live (Manager section). Browser Compatibility: Make sure that your internet browser is up to date. Enable Contract Data: In the Ethereum app settings on your Ledger device, enable "Contract data". For detailed instructions on how to connect and use your Ledger or Trezor with MetaMask, please visit our guide here: [How to connect a Trezor or Ledger Hardware Wallet](https://metamask.zendesk.com/hc/en-us/articles/360020394612).
> 
> Additional Steps for Ledger Users:
> 
> Enable Blind Signing: To manage ERC-20 tokens and interact with smart contracts, turn on "Blind Signing" in the Ethereum app settings on your Ledger device. Connect Ledger to MetaMask: Follow the specific steps provided on Ledger's support page to connect your Ledger device to MetaMask correctly. [Connect your Ledger to MetaMask](https://support.ledger.com/hc/en-us/articles/4404366864657).
> 
> Let me know if you still need help with the error.

in edge, the version 11.12.2 was latest

**Comment by Spider-yuchen** [comment]
> 你好@Spider-yuchen,
> 
> 请将您的 MetaMask 扩展钱包版本更新至 11.15.2。并禁用浏览器上的其他扩展。 您可以使用官方网站 - https://metamask.io/download/
> 
> 为了确保在将 Ledger 设备与 MetaMask 一起使用时获得无缝体验，请遵守以下准则：
> 
> 关闭 Ledger Live：应关闭 Ledger Live，以避免 MetaMask 尝试连接到您的 Ledger 设备时发生冲突。 请解锁您的设备：确保您的账本已解锁并且以太坊应用程序已打开。 更新您的设备和应用程序： 固件：验证您的 Ledger 或 Trezor 设备是否运行最新的固件版本。 以太坊应用程序：通过 Ledger Live（管理器部分）重新安装或更新 Ledger 上的以太坊应用程序。 浏览器兼容性：确保您的互联网浏览器是最新的。 启用合约数据：在 Ledger 设备上的以太坊应用程序设置中，启用“合约数据”。 有关如何通过 MetaMask 连接和使用 Ledger 或 Trezor 的详细说明，请访问我们的指南：[如何连接 Trezor 或 Ledger 硬件钱包](https://metamask.zendesk.com/hc/en-us/articles/360020394612)。
> 
> 分类帐用户的附加步骤：
> 
> 启用盲签名：要管理 ERC-20 代币并与智能合约交互，请在 Ledger 设备上的以太坊应用程序设置中打开“盲签名”。 将 Ledger 连接到 MetaMask：按照 Ledger 支持页面上提供的具体步骤将您的 Ledger 设备正确连接到 MetaMask。[将您的 Ledger 连接到 MetaMask](https://support.ledger.com/hc/en-us/articles/4404366864657)。
> 
> 如果您仍然需要有关该错误的帮助，请告诉我。

Following the above steps we successfully send the transaction, but there is still a problem: we use wagmi to call object to connect to matemask, matemask is connected to a ledger hardware wallet, and the same problem occurs when we call the pledge deposit contract, and it turns out that everything works fine when we use only matemask and not ledger!
![img_v3_02ar_18ff040e-9b80-4470-81cb-118717ba80hu](https://github.com/MetaMask/metamask-extension/assets/85734745/d3d7e2ec-e0d7-4558-8bc0-8df685180ddb)

**Comment by Spider-yuchen** [comment]
> Hi @Spider-yuchen ,
> 
> Please update your MetaMask extension wallet version to 11.15.2. and disable other extensions on your browser. You can use the official website - https://metamask.io/download/
> 
> To ensure a seamless experience when using your Ledger device with MetaMask, please adhere to the following guidelines:
> 
> Close Ledger Live: Ledger Live should be closed to avoid conflicts when MetaMask attempts to connect to your Ledger device. Please unlock your Device: Ensure your Ledger is unlocked and the Ethereum application is open. Update Your Device and Apps: Firmware: Verify that your Ledger or Trezor device runs the latest firmware version. Ethereum App: Reinstall or update the Ethereum app on your Ledger through Ledger Live (Manager section). Browser Compatibility: Make sure that your internet browser is up to date. Enable Contract Data: In the Ethereum app settings on your Ledger device, enable "Contract data". For detailed instructions on how to connect and use your Ledger or Trezor with MetaMask, please visit our guide here: [How to connect a Trezor or Ledger Hardware Wallet](https://metamask.zendesk.com/hc/en-us/articles/360020394612).
> 
> Additional Steps for Ledger Users:
> 
> Enable Blind Signing: To manage ERC-20 tokens and interact with smart contracts, turn on "Blind Signing" in the Ethereum app settings on your Ledger device. Connect Ledger to MetaMask: Follow the specific steps provided on Ledger's support page to connect your Ledger device to MetaMask correctly. [Connect your Ledger to MetaMask](https://support.ledger.com/hc/en-us/articles/4404366864657).
> 
> Let me know if you still need help with the error.

Following the above steps we successfully send the transaction, but there is still a problem: we use wagmi to call injected to connect to matemask, matemask is connected to a ledger hardware wallet, and the same problem occurs when we call the pledge deposit contract, and it turns out that everything works fine when we use only matemask and not ledger!

![img_v3_02ar_18ff040e-9b80-4470-81cb-118717ba80hu](https://github.com/MetaMask/metamask-extension/assets/85734745/af035a5b-5fc3-4cb0-9ed6-2f38e9674e31)

**Comment by lechuckchuck** [comment]
Same issue here, also on ledger. Please fix ASAP!

**Comment by szabope** [comment]
Same here with version 12.0.1 and Nano S (just updated).
I suspect this change https://support.ledger.com/article/4405481324433-zd
Although can't find when it happened.

**Comment by benjisclowder** [comment]
Not reproducible in 12.10.0.
