### ISSUE TITLE
uat: Implement signTypedData design

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2453]
Looks like it was merged in from master, so the template & functionality is there, ready to go:

![screen shot 2017-10-23 at 3 50 12 pm](https://user-images.githubusercontent.com/542863/31916943-f71905c6-b809-11e7-9bee-c75c39183503.png)

For reference, Christian's design is:

![signature tx 3](https://user-images.githubusercontent.com/542863/31916981-249c8d06-b80a-11e7-8525-d782ac955de1.png)

**Comment by danfinlay** [comment]
You can easily invoke this screen with metamask using the "sign typed data" button on this page:

https://danfinlay.github.io/js-eth-personal-sign-examples/

**Comment by chikeichan** [comment]
Implemented by ddf11011
