### ISSUE TITLE
[Bug]: EIP 1559 send transaction for gas fee fails

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#24546]
### Describe the bug

EIP 1559 send transaction for gas fee fails the transaction instead of completed status.

### Expected behavior

Transaction should be completed. 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/153644847/16197333-213a-43b0-83ba-d9ea11e6a3c6

### Steps to reproduce

1. Log into MetaMask
2. Fill in your password
3. Switch over to a test network (e.g.: Sepolia)
4. Head over to the test dapp: https://metamask.github.io/test-dapp/ and connect the MM account
5. Proceed to send eip-1559 transaction
6. Click on the edit pencil --> Advanced --> provide the max base fee to 25 and priority fee to 2.
7. Confirm the transaction. 

### Error messages or log output

```shell
Transaction id - 0x9c0acc7644d6f64ebb3d7d44a09ced05a2f99d7b2a9d7fdc4f039d5b7731c404

https://sepolia.etherscan.io/tx/0x9c0acc7644d6f64ebb3d7d44a09ced05a2f99d7b2a9d7fdc4f039d5b7731c404
```

### Version

11.16.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
I think this is the same as:
- https://github.com/MetaMask/metamask-extension/issues/24378
- https://github.com/MetaMask/metamask-extension/issues/24183

**Comment by hjetpoluru** [comment]
Thank you, Mariona. I was not familiar with the functionality and performed a search for EIP 1559 but did not find any issues. However, after your review and the bugs you referenced, it all makes sense now. Closing the ticket as duplicate.
