### ISSUE TITLE
[Bug]: Metamask recommended gas fees for Bitlayer Network is too high

### ISSUE THREAD

**Issue by freddi8e** [MetaMask/metamask-extension#24559]
### Describe the bug

Just like the problem faced by opBNB chain, Metamask suggests a very high gas fee on Bitlayer Network. Maybe Metamask had set a default minimum recommendation price for gas based on the average of all networks.

Bitlayer is the first Layer 2 solution for Bitcoin that offers security equivalent to Bitcoin's own and Turing completeness. Bitlayer is  fully EVM-compatible.  And here are some infos for Bitlayer testnet and mainnet.
```
Mainnet Info:
Chain ID: 200901
RPC: 
	https://rpc.bitlayer.org/, https://rpc.bitlayer-rpc.com/, https://rpc.ankr.com/bitlayer
Explorer:
	https://www.btrscan.com/

Testnet Info:
ChainID: 200810
RPC: 
	https://testnet-rpc.bitlayer.org/
Explorer: 
        https://testnet-scan.bitlayer.org/
```
And here is the recommended gas fee by Metamask.
<img width="309" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/152241286/05ee04d2-5d04-4e79-92a2-abc34d425af8">

The recommended gas price is default 1.5gwei.

And here is the real gas price on Bitlayer testnet.
```
curl https://testnet-rpc.bitlayer.org   -X POST   -H "Content-Type: application/json"   --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}'
{"id":1,"jsonrpc":"2.0","result":"0x5f5e107"}
```
The real gas price is much lower than the default minimum recommendation price, it is 0.100000007 gwei.

### Expected behavior

We expect that Metamask can provide a recommended gas fee based on the real gas price on Bitlayer chain.

### Screenshots/Recordings

<img width="309" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/152241286/8f3145ae-17b7-4bd2-a629-0287fbedce9b">

<img width="1251" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/152241286/8f3e1964-4041-482d-9520-5d1fcae69732">

### Steps to reproduce

1. Add custom network using Bitlayer network info.
```
Chain ID: 200810
RPC: 
	https://testnet-rpc.bitlayer.org/
Explorer:
	https://testnet-scan.bitlayer.org/
```
2.Send asset on Metamask, edit "Estimated fee".
3.Click on "Advanced", and can see the Priority Fee is default 1.5gwei, the Max base fee is 1.500000008gwei.
4.Get the real gas price from Bitlayer chain rpc.
```
curl https://testnet-rpc.bitlayer.org   -X POST   -H "Content-Type: application/json"   --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}'
{"id":1,"jsonrpc":"2.0","result":"0x5f5e107"}
```
The Bitlayer gas price is 0.100000007gwei.

### Version

11.15.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Hey @freddi8e, sorry for the delay on replying to you. Closing as this should be fixed in the latest releases (starting on v11.16 release). 
Let us know if that is not the case!
