### ISSUE TITLE
[Bug]: MV3 - Signatures - Personal Sign not working with Ledger

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#24588]
### Describe the bug

Whenever I try to perform a Personal Sign with a ledger device using an MV3 build, I can see how it does not trigger anything in my ledger device.

### Expected behavior

I should see the signature prompt into my ledger device

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/11a059a9-6630-42af-940e-2f2da69e9873

### Steps to reproduce

1. Build MV3
2. Import a ledger
3. Go to the test dapp
4. Try a Personal Sign
5. Accept in MM
6. See nothing happens in ledger

### Version

develop MV3 build

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by danjm** [comment]
@seaona Do other signature types work with ledger on mv3?

**Comment by seaona** [comment]
so:
- :green_circle: typed v4: works on Ledger
- :white_circle:  typed v3 , typed (v1): don't work but because they are not supported by Ledger, so that's expected
- :red_circle: personal sign: doesn't work
- :red_circle: eth_sign: doesn't work, but since it's being deprecated I didn't open an issue for that one
