### ISSUE TITLE
"Unhandled rejection Error: Returned error: unknown account"

### ISSUE THREAD

**Issue by hynese** [MetaMask/metamask-extension#2459]
I'm trying to do a function call to my contract via MetaMask and it's just not working...

"Unhandled rejection Error: Returned error: unknown account"

I have the following JavaScript:

```
let instance = new window.web3.eth.Contract(abi,address);

console.log(instance)
console.log("----->"+accounts[0])

instance.methods.participate().send({
	from: accounts[0],
	value: _valWei.toString(),
	gas: Constants.defaultGas
})
.then(function(receipt){
	console.log("then")
	console.log(receipt)
});

```

I'm using `web3@1.0.0-beta.24`

When my user clicks on the button (i.e. call my smart contract's "participate" function) they get this error in the Google Chrome console:

`Unhandled rejection Error: Returned error: authentication needed: password or unlock`

MetaMask is definitely unlocked!

If I do a plain 'send()' transaction, MetaMask works fine - window pops up, etc.

```
web3.eth.sendTransaction({
	from: accounts[0],
	value: _valWei.toString(),
	gas: Constants.defaultGas,
	to:"0xbb9bc244d798123fde783fcc1c72d3bb8c189413"
})
```

**Comment by bdresser** [comment]
we believe this is fixed in the current version (4.7.4). if the problem persists, feel free to re-open this issue!
