### ISSUE TITLE
[Bug]: Mainnet icon is not displayed on token icons following fresh install / Firefox

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24590]
### Describe the bug

Mainnet icon is not displayed on token icons following fresh install / Firefox. The issue can be resolved by re-loading browser page.

Latest 14.4.4 send+swap build

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/2adf50fc-654c-4281-809f-f2e8c67712db

<img width="653" alt="Screenshot 2024-05-17 at 20 05 35" src="https://github.com/MetaMask/metamask-extension/assets/104780023/7f8ffb26-cd5c-4234-8369-76187a91bdda">

### Steps to reproduce

1. Install MetaMask on Firefox
2. Import the wallet
3. Switch to Ethereum Mainnet
4. Notice mainnet icon is not shown on top of the token icons 

### Version

latest build

### Build type

None

### Browser

Firefox

### Operating system

MacOS

**Comment by BZahory** [comment]
Is this a swap+send bug?

**Comment by sleepytanya** [comment]
I don't this issue on the latest build on `develop`. But now mainnet icon is not shown within the networks list. After addidng networks / switching networks it eventually appears.

<img width="402" alt="Screenshot 2024-06-10 at 21 08 26" src="https://github.com/MetaMask/metamask-extension/assets/104780023/fced9679-1bdf-4882-b03d-02866db04bb5">

<img width="410" alt="Screenshot 2024-06-10 at 21 19 59" src="https://github.com/MetaMask/metamask-extension/assets/104780023/17acecc7-b08a-4dab-8b1f-e18acb733887">

**Comment by sleepytanya** [comment]
> Is this a swap+send bug?

Great question. I do not have an answer but it is present on develop and RC 12.0.0. So I think we can safely remove send+swap label? @BZahory @micaelae @hesterbruikman

**Comment by sleepytanya** [comment]
RC 12.0.0:


https://github.com/MetaMask/metamask-extension/assets/104780023/6a6c6b3f-0149-4d2f-84d5-161b144efae6

**Comment by sleepytanya** [comment]
Latest [v12.0.0 build](08dbe017e1fd5ddb709de0456ba602b630025449dc8313ebab22d624e5208a69)

Mainnet icons displayed on Firefox, fresh install:



https://github.com/MetaMask/metamask-extension/assets/104780023/a4660c33-8716-47c0-803b-b33ca69c5498

**Comment by danjm** [comment]
closing as the bug seems to be fixed. Let's re-open if it happens again
