### ISSUE TITLE
Flaky Test: Multiple tests failing with ElementClickInterceptedError on dapp interaction

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24597]
### What is this about?

Related tests:

- Permissions Page should redirect users to connections page when users click on connected permission
- Connections page should disconnect when click on Disconnect button in connections page

Failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81118/workflows/04fa31d6-ea90-4e1d-9161-0e61fb05b85e/jobs/2873298/tests
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81133/workflows/0b962d69-e9d4-4c3e-9ca0-cfa829b667e2/jobs/2874111/tests

Error message
![Screenshot 2024-05-20 at 09 45 55](https://github.com/MetaMask/metamask-extension/assets/105063779/956a6173-7ed2-423f-8eec-bbd08fe8c938)

![Screenshot 2024-05-20 at 11 18 20](https://github.com/MetaMask/metamask-extension/assets/105063779/5ab0539d-6546-4657-b6c6-8a8ec81a0e8e)

Screenshot
![Screenshot 2024-05-20 at 09 46 06](https://github.com/MetaMask/metamask-extension/assets/105063779/24fba6ca-9cd0-4861-945c-bfd28a5feaf2)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by seaona** [comment]
I had this PR for fixing one of these instances
https://github.com/MetaMask/metamask-extension/pull/24580


And opened this other PR for fixing the rest of instances with this same problem
https://github.com/MetaMask/metamask-extension/pull/24607

**Comment by seaona** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/24580
