### ISSUE TITLE
Flaky Test [Confirmation]  - "User Operations from swap"

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24606]
### What is this about?

Failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81133/workflows/0b962d69-e9d4-4c3e-9ca0-cfa829b667e2/jobs/2874097/tests

Error message
![Screenshot 2024-05-20 at 11 45 38](https://github.com/MetaMask/metamask-extension/assets/105063779/09208dff-44d6-43dd-871d-5ef7efed0405)

Screenshot
![Screenshot 2024-05-20 at 11 45 45](https://github.com/MetaMask/metamask-extension/assets/105063779/0fb3fac4-5ec6-45fd-8593-49c42c999982)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by bschorchit** [comment]
Closing as fixed with https://github.com/MetaMask/metamask-extension/pull/25913
