### ISSUE TITLE
I forgot my Wallet Seed,I had deposited Eth and bought Plutos. 

### ISSUE THREAD

**Issue by woody85250** [MetaMask/metamask-extension#2460]
I forgot my Wallet Seed,I had deposited Eth.
Can u help me find my Wallet Seed?

I have two accounts:
1.0xd0d2fC2F9f4eE3e82Bd92AF7e762Cc7048Ad7f8B
2.0x81A48F417c9dD9b33b50b64E4B65f96cb5add8A9

**Comment by Zanibas** [comment]
If you do not have your seed phrase, we cannot restore your account--there simply isn't any other way around this.

**Comment by johnjames333** [comment]
@woody85250 
we have developed our own hardware for cracking Metamask wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by DanielsBerlin** [comment]
@woody85250 
you can use hashcat to crack your password. you can contact me if you need assistance
