### ISSUE TITLE
Flaky Test: Multiple onboarding tests failing due to an error where the "Reveal secret recovery phrase" button cannot be found

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24608]
### What is this about?

Reason of flakiness:
We are trying to find button on wrong screen! Need to check why we are not on expected screen.

Related tests:
Wallet Created Events @no-mmi are sent when onboarding user who chooses to opt in metrics
Wallet Created Events @no-mmi are not sent when onboarding user who chooses to opt out metrics

Failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81114/workflows/d532e9e3-0401-4b01-aae7-1682303bc3fe/jobs/2873090/tests
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81133/workflows/0b962d69-e9d4-4c3e-9ca0-cfa829b667e2/jobs/2874110/tests

Error message
![Screenshot 2024-05-20 at 12 08 53](https://github.com/MetaMask/metamask-extension/assets/105063779/59888541-8d7a-4635-a30b-dae69fdad480)

![Screenshot 2024-05-20 at 12 15 50](https://github.com/MetaMask/metamask-extension/assets/105063779/3229b5e3-f55e-4bc7-918c-d9d083ad4875)

Screenshot
![Screenshot 2024-05-20 at 12 09 07](https://github.com/MetaMask/metamask-extension/assets/105063779/791d9cbe-6967-4127-9f12-e7b23c55e479)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by seaona** [comment]
## Findings

For one type of Onboarding failure, this seems to be the error logs. 
```
[0521/181627.165843:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0521/181627.165925:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
```

When this error is hit, we stay in the first page and nothing happens. This corresponds to the following failed tests:
- MetaMask onboarding @no-mmi Clicks import a new wallet, accepts a secure password, reveals the Secret Recovery Phrase, confirm SRP
- MetaMask onboarding @no-mmi Verify that the user has been redirected to the correct page after creating a password for their new wallet
 MetaMask onboarding @no-mmi Verify that the user has been redirected to the correct page after creating a password for their new wallet
- MetaMask onboarding @no-mmi Verify that the user has been redirected to the correct page after importing their wallet


https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81546/workflows/df92714b-7157-4126-8b72-0634e69ddf8e/jobs/2896296/artifacts

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/7ee8c940-05ea-46d3-a342-bbb51717b292)

**Comment by danjm** [comment]
Re-opening as we discovered the problem was not resolved when we thought it was
