### ISSUE TITLE
Redesign Signature Permit: create simulation section

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#24618]
Create and add a simulation section on permit signature pages:

<img width="373" alt="Screenshot 2024-05-20 at 9 09 29 PM" src="https://github.com/MetaMask/metamask-extension/assets/2182307/c5509283-3123-45de-ab6f-8654b8ffe797">

Figma designs: https://www.figma.com/design/wcXUl6AH5KNFwKdAIv49kh/Confirmation-redesign-V5?node-id=3478-4937&t=ntn8vkJLaLNRFq1T-0

**Comment by cryptotavares** [comment]
Collapsable message does not need to be implemented right now. For MVP we will go with scroll to bottom (but users can proceed without scrolling to bottom)
