### ISSUE TITLE
Enable Redesign Signature SIWE

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#24617]
The task will involve enabling new designs for SIWE signature requests.

https://www.figma.com/design/v8npDTFD2fofLjDfbJUD9j/Confirmation-redesign-V3?node-id=360%3A4051&t=EuGBZwCijC3AjXa8-1

**Comment by cryptotavares** [comment]
Collapsable message does not need to be implemented right now. For MVP we will go with scroll to bottom (but users can proceed without scrolling to bottom)

**Comment by digiwand** [comment]
Issue ticket to handle collapsible section separately 
https://github.com/MetaMask/metamask-extension/issues/24680

**Comment by digiwand** [comment]
To enable SIWE for our redesign pages, go to `ui/pages/confirmations/hooks/useCurrentConfirmation.ts` and remove `isSIWE` from the condition statement
