### ISSUE TITLE
Flaky Test: [Snap] Test Snap bip-32 tests various functions of bip-32

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24638]
### What is this about?

Failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81209/workflows/c77b109f-cb76-4476-9ecd-70f966ae244a/jobs/2878499/tests

Error message

![Screenshot 2024-05-20 at 16 48 01](https://github.com/MetaMask/metamask-extension/assets/105063779/eb086e79-fcef-4f08-9ef5-f0941bebeb88)

Screenshot
![Screenshot 2024-05-20 at 16 47 43](https://github.com/MetaMask/metamask-extension/assets/105063779/2ec4621e-96b1-485b-8385-85d2ece74e04)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by chloeYue** [comment]
This test is flaky due to same error:
test: Test Snap update can install an old and then updated version

Failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81120/workflows/d772f57b-6f5f-441e-98d6-cf47fdf569ff/jobs/2873414/tests

Error message:
![Screenshot 2024-05-20 at 17 04 00](https://github.com/MetaMask/metamask-extension/assets/105063779/3a7b6cb8-468f-42f7-ab08-8be03bfaa706)

Screenshot:

![Screenshot 2024-05-20 at 17 04 07](https://github.com/MetaMask/metamask-extension/assets/105063779/04317864-a7f3-49b7-a049-286bd106f163)

**Comment by chloeYue** [comment]
Same error in test: 
Test Snap bip-44 can pop up bip-44 snap and get private key result

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/80881/workflows/87720e4a-6069-4873-abef-49666d1ef741/jobs/2860834/tests

**Comment by chloeYue** [comment]
Same error in test:
Test Snap RPC can use the cross-snap RPC endowment and produce a public key

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81146/workflows/1dd2a38e-145b-4791-b5c6-d4bda5caa42e/jobs/2874872/tests

**Comment by chloeYue** [comment]
Same error in test:
Test Snap update via snaps component can install an old and then update via the snaps component

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81034/workflows/63fd7df7-a5e9-4e28-9818-541d92687730/jobs/2868930/tests

**Comment by bowensanders** [comment]
Failed test ([link](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81209/workflows/c77b109f-cb76-4476-9ecd-70f966ae244a/jobs/2878499/parallel-runs/11?filterBy=ALL) line 643)
Console log:
```
Running tests on firefox

Executing testcase: 'Test Snap bip-32 tests various functions of bip-32'

[driver] Called 'navigate' with arguments []
[driver] Called 'fill' with arguments ["#password","correct horse battery staple"]
[driver] Called 'press' with arguments ["#password",""]
[driver] Called 'assertElementNotPresent' with arguments ["[data-testid=\"unlock-page\"]"]
[driver] Called 'waitForSelector' with arguments [{"text":"Installed Snaps","tag":"h2"}]
[driver] Called 'findElement' with arguments ["#connectbip32"]
[driver] Called 'scrollToElement' with arguments [{"driver_":{"session_":{},"executor_":{"customCommands_":{},"log_":{"name_":"driver.http.Executor","level_":null,"parent_":{"name_":"driver.http","level_":null,"parent_":{"name_":"driver","level_":nu
[driver] Called 'waitForSelector' with arguments ["#connectbip32"]
[driver] Called 'clickElement' with arguments ["#connectbip32"]
[driver] Called 'waitUntilXWindowHandles' with arguments [2]
[driver] Called 'switchToWindowWithTitle' with arguments ["MetaMask Dialog",["a355209f-d623-4b96-8b31-8e62d13d3b8d","cbd76403-e313-4968-9e1c-1054bfa399b0"]]
[driver] Called 'waitForSelector' with arguments [{"text":"Connect","tag":"button"}]
[driver] Called 'clickElement' with arguments [{"text":"Connect","tag":"button"}]
[driver] Called 'waitForSelector' with arguments [{"text":"Confirm"}]
[driver] Called 'clickElementSafe' with arguments ["[data-testid=\"snap-install-scroll\"]"]
[driver] Called 'clickElement' with arguments [{"text":"Confirm","tag":"button"}]
Failure on testcase: 'Test Snap bip-32 tests various functions of bip-32', for more information see the artifacts tab in CI

TimeoutError: Waiting until element is enabled
Wait timed out after 10153ms
```

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
