### ISSUE TITLE
Flaky test [Snap]: "Test Snap UI Links test link in confirmation snap_dialog type"

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24635]
### What is this about?

Failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81189/workflows/2c314a50-9a49-41d5-ace8-e11fca461442/jobs/2877235/tests

Error message
![Screenshot 2024-05-20 at 16 32 05](https://github.com/MetaMask/metamask-extension/assets/105063779/1ed95eb5-a5ca-46b7-a117-5b85bba65c09)

Screenshot
![Screenshot 2024-05-20 at 16 31 53](https://github.com/MetaMask/metamask-extension/assets/105063779/b83cf6c9-e015-4e41-aa97-ce5c200ea12e)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by bowensanders** [comment]
Relevant failure ([link](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81189/workflows/2c314a50-9a49-41d5-ace8-e11fca461442/jobs/2877235/parallel-runs/21?filterBy=ALL) line 617)
Console log:
Executing testPath: /home/circleci/project/test/e2e/snaps/test-snap-uilinks.spec.js

Running tests on firefox

```
Executing testcase: 'Test Snap UI Links test link in confirmation snap_dialog type'

[driver] Called 'navigate' with arguments []
[driver] Called 'fill' with arguments ["#password","correct horse battery staple"]
[driver] Called 'press' with arguments ["#password",""]
[driver] Called 'assertElementNotPresent' with arguments ["[data-testid=\"unlock-page\"]"]
[driver] Called 'openNewPage' with arguments ["https://metamask.github.io/snaps/test-snaps/2.6.1/"]
[driver] Called 'delay' with arguments [1000]
[driver] Called 'findElement' with arguments ["#connectdialogs"]
[driver] Called 'scrollToElement' with arguments [{"driver_":{"session_":{},"executor_":{"customCommands_":{},"log_":{"name_":"driver.http.Executor","level_":null,"parent_":{"name_":"driver.http","level_":null,"parent_":{"name_":"driver","level_":nu
[driver] Called 'delay' with arguments [1000]
[driver] Called 'clickElement' with arguments ["#connectdialogs"]
[driver] Called 'waitUntilXWindowHandles' with arguments [3]
[driver] Called 'switchToWindowWithTitle' with arguments ["MetaMask Dialog",["f91e34a6-7b64-4cbc-98ec-0ca6a754ce2d","ee1556ed-3f82-48ce-9615-31f16755257d","0e625a2b-ed22-48e3-b1d0-e463640f166e"]]
[driver] Called 'clickElement' with arguments [{"text":"Connect","tag":"button"}]
[driver] Called 'waitForSelector' with arguments [{"text":"Confirm"}]
Failure on testcase: 'Test Snap UI Links test link in confirmation snap_dialog type', for more information see the artifacts tab in CI

TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Confirm")])
Wait timed out after 10057ms
```

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
