### ISSUE TITLE
uat: Transaction confirm view notes

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2464]
A few minor issues on the confirm screen:

- Confirm buttons should probably bottom-align
- There is a little bit of space to the right of the scrollable section.

![screen shot 2017-10-24 at 11 44 05 am](https://user-images.githubusercontent.com/542863/31961881-f2fdd320-b8b0-11e7-9df9-6ef5085c0a7b.png)

Also, on the Confirm Transaction screen, the text looks too close to the button. Maybe we should make the title font a little smaller:

![screen shot 2017-10-24 at 11 46 58 am](https://user-images.githubusercontent.com/542863/31961993-312d2330-b8b1-11e7-9350-f381d65c3b0f.png)

Also, I'd prefer if the arrow were vertically aligned between the circles, instead of those account elements. It looks good on contract publishing, but not as much on `Confirm Transaction`

**Comment by chikeichan** [comment]
Fixed alignment and size on notifications. Creating task for Christian to review responsive design

**Comment by chikeichan** [comment]
7c10cda8

![screen shot 2017-10-25 at 12 17 27 am](https://user-images.githubusercontent.com/8507735/31985690-cd78b6b4-b91a-11e7-9535-5543627394dc.png)
![screen shot 2017-10-25 at 12 23 05 am](https://user-images.githubusercontent.com/8507735/31985691-cda27684-b91a-11e7-91e0-2a2355092eb8.png)
