### ISSUE TITLE
flaky test: "Navigate transactions should reject and remove an unapproved transaction"

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24641]
### What is this about?

Failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81057/workflows/8f00a564-7c95-404d-8539-3e09a3c3e6cf/jobs/2870201/tests

Error message

![Screenshot 2024-05-20 at 17 08 48](https://github.com/MetaMask/metamask-extension/assets/105063779/547bf12d-ae0f-4b39-8b50-4e487cc4d38f)

Screenshot
![Screenshot 2024-05-20 at 17 08 55](https://github.com/MetaMask/metamask-extension/assets/105063779/df9c9591-4014-4c78-800a-3a10d6d81c57)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by hjetpoluru** [comment]
Flaky test is fixed and closing this ticket
