### ISSUE TITLE
flaky test:  "Dapp viewed Event @no-mmi is sent when navigating to a connected dapp"

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24651]
### What is this about?

Latest CI failure

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101259/workflows/506f3637-17c1-42dd-82b0-8e62ee9e6ff3/jobs/3770240

**Comment by chloeYue** [comment]
This test is still flaky and needs investigation

**Comment by hjetpoluru** [comment]
Fix in PR 27381
