### ISSUE TITLE
flaky test:  "Settings Search should find element inside the Alerts tab"

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24654]
### What is this about?

Failure:

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81189/workflows/2c314a50-9a49-41d5-ace8-e11fca461442/jobs/2877230/tests

Update CI failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/92972/workflows/d2861b4e-f778-4875-96bc-adbb8502523b/jobs/3462599/tests

Error message
![Screenshot 2024-05-20 at 18 06 03](https://github.com/MetaMask/metamask-extension/assets/105063779/f3125b05-b6f0-44cd-84ad-cd6a6c8f902e)

Screenshot
![Screenshot 2024-05-20 at 18 06 12](https://github.com/MetaMask/metamask-extension/assets/105063779/91249782-9c29-44ee-b869-727197ded6c5)

<img width="1050" alt="Screenshot 2024-07-23 at 11 16 08 AM" src="https://github.com/user-attachments/assets/17a582d2-7494-4a69-b0f4-0096cc70ce24">

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/92972/workflows/d2861b4e-f778-4875-96bc-adbb8502523b/jobs/3462599/tests

**Comment by chloeYue** [comment]
Same error in flaky test:
Settings Search should find element inside the Contacts tab

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81132/workflows/76b59ca6-3a4d-4273-84a9-38283f2d2754/jobs/2874082/tests



![Image](https://github.com/MetaMask/metamask-extension/assets/105063779/649aee89-a5c3-46e5-9075-628d433f1573)

**Comment by hjetpoluru** [comment]
Its already addressed and closing this ticket
