### ISSUE TITLE
Redesign Signature SIWE create message section

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#24650]
![Screenshot 2024-05-20 at 9 31 38 PM](https://github.com/MetaMask/metamask-extension/assets/2182307/60665459-78f3-4ce9-98e5-ca439a756619)

Figma: https://www.figma.com/design/v8npDTFD2fofLjDfbJUD9j/Confirmation-redesign-V3?node-id=360%3A4051&t=EuGBZwCijC3AjXa8-1

**Comment by digiwand** [comment]
Issue ticket to handle collapsible section separately
https://github.com/MetaMask/metamask-extension/issues/24680
