### ISSUE TITLE
flaky test: Navigate transactions should reject and remove all unapproved transactions

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#24661]
### What is this about?

Failure:

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/81189/workflows/2c314a50-9a49-41d5-ace8-e11fca461442/jobs/2877230/tests

Error message

![Screenshot 2024-05-20 at 18 34 35](https://github.com/MetaMask/metamask-extension/assets/105063779/0a3fa375-430b-42e8-a47b-366c52ef359f)

Screenshot
![Screenshot 2024-05-20 at 18 34 44](https://github.com/MetaMask/metamask-extension/assets/105063779/9cbdbb01-1f78-4e3f-a301-62ad6c67f0f7)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by vthomas13** [comment]
I'm unable to reproduce this on Mac.
Using the commands:
`yarn && yarn build:test:mmi` 
`yarn test:e2e:single test/e2e/tests/transaction/navigate-transactions.spec.js --debug --mmi --browser=chrome --leave-running --retry-until-failure --retries=30`
@chloeYue
