### ISSUE TITLE
uat: Gas popup can spill off screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2466]
![screen shot 2017-10-24 at 11 50 49 am](https://user-images.githubusercontent.com/542863/31962217-d2661c52-b8b1-11e7-8df0-980d7e0674a5.png)

We could probably fix this just by removing some of that bottom padding. No scrolling needed.

**Comment by chikeichan** [comment]
![screen shot 2017-10-25 at 1 08 32 am](https://user-images.githubusercontent.com/8507735/31987585-19f7fed6-b921-11e7-98d2-3127cd629335.png)
![screen shot 2017-10-25 at 1 08 41 am](https://user-images.githubusercontent.com/8507735/31987586-1a10c024-b921-11e7-87e6-3f1a14834225.png)

resolved by 0d522139
