### ISSUE TITLE
UAT: Gas price should show units (GWEI)

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2467]
Currently gas price does not indicate units, but really should:

![screen shot 2017-10-24 at 11 50 49 am](https://user-images.githubusercontent.com/542863/31962255-f09488c6-b8b1-11e7-861e-5cadb2e8e0de.png)

**Comment by chikeichan** [comment]
![screen shot 2017-10-25 at 1 16 10 am](https://user-images.githubusercontent.com/8507735/31987918-34d81406-b922-11e7-884a-005b64109ff8.png)

2b72b706
