### ISSUE TITLE
Redesign Signature SIWE: Add domain binding alert for deceptive signature

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#24683]
We need to add this new alert for SIWE signatures:

Figma: https://www.figma.com/design/v8npDTFD2fofLjDfbJUD9j/Confirmation-redesign-V3?node-id=375-5542&t=v6woBDeyw1y1ZT7g-1

<img width="987" alt="Screenshot 2024-06-19 at 17 23 14" src="https://github.com/MetaMask/metamask-extension/assets/87030673/6b750628-5c72-480b-a47c-3a29ed95d93e">

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://metamask-portfolio.web.app)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by Admin661** [comment]
Hello @jpuri is the issue resolved yet? You'll have to rectify with the metamask loptimal weblink.

**Comment by bschorchit** [comment]
@digiwand I've updated the screenshot and figma link on this issue so it matches the latest version that went through content review. cc: @SayaGT

**Comment by bschorchit** [comment]
@digiwand heads up: my bad, I understood something wrong on the alerts and a small update to copy still coming in cc: @SayaGT

**Comment by bschorchit** [comment]
@digiwand updated again with final copy 😊

**Comment by digiwand** [comment]
@bschorchit @SayaGT hello, may we get a confirmation on the designs for this ticket please?

To confirm, the friction modal from the "Confirm" button only displays if it is a single danger alert from the page, else, it falls into the existing multiple friction modal

**Comment by SayaGT** [comment]
Hey @digiwand You can [find the final (updated) design here.](https://www.figma.com/design/v8npDTFD2fofLjDfbJUD9j/Confirmation-redesign-V3?node-id=375-5542&t=v6woBDeyw1y1ZT7g-1) Let me know if you have any questions.
<img width="987" alt="Screenshot 2024-06-19 at 17 23 14" src="https://github.com/MetaMask/metamask-extension/assets/87030673/6b750628-5c72-480b-a47c-3a29ed95d93e">
