### ISSUE TITLE
uat: Sent token indication for removed tokens

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2472]
Reproduction steps:

1. Add a token
2. Send that token
3. Remove that token

The token list will now not know how to render the token sent:

![screen shot 2017-10-24 at 12 58 20 pm](https://user-images.githubusercontent.com/542863/31965151-466305da-b8bb-11e7-88e5-d357a246bb57.png)

**Comment by kidsil** [comment]
I only see an option to "Hide Token", after choosing that, the transactions still display correctly:
![image](https://user-images.githubusercontent.com/154950/34616909-7f57984c-f231-11e7-98e5-3b9831e6e49b.png)
