### ISSUE TITLE
uat: UI logs not showing

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2473]
Mostly a Q for my own local development:

When I add logs to the `uat` branch, they don't show up in the UI console. Is that normal? Is there a new tool I need to learn to use?

**Comment by chikeichan** [comment]
That's weird. I am able to add logs and have it show up in UI console. What are you trying to log?

**Comment by danfinlay** [comment]
Just click events and things. Maybe I have a weird filter applied, I’ll try again soon.
