### ISSUE TITLE
Privacy warning should refer to locking, not logging out.

### ISSUE THREAD

**Issue by velerodro** [MetaMask/metamask-extension#2475]
Hello,

IIRC, during the account creation process, the application recommends to log out while you are not using it. Also, I don't want the websites I visit to be able to know that I use metamask or my address, etc.

However, I cannot find how to log out. So, could you please tell me how to log out? Is it the same as locking the account?

**Comment by Zanibas** [comment]
Yes, it is the same as locking your account!

**Comment by danfinlay** [comment]
Just use the menu in the top right and select "Lock". Sorry for the confusing verbage. We should make that warning specify locking, not logging out, leaving this issue open and editing the title to reflect that.

![screen shot 2017-10-26 at 12 46 08 pm](https://user-images.githubusercontent.com/542863/32073665-ac3c6c8e-ba4b-11e7-93b5-d277d94c4bf5.png)

**Comment by Brigzyman** [comment]
Man you'd think tey'd have changed that by now ! It's counter-intuitive, I mean lock my account No wants to do that for fear they'll have a badass time trying to unlock .Lock is such a strong word to use for log out.

**Comment by echolabstech** [comment]
@danfinlay Please change this to 'logout'

**Comment by zerePesseJ** [comment]
@danfinlay - bumping this request: can we change the ''lock' and replace with "log out"...?

**Comment by diegonc** [comment]
Why? Given you followed this route, please change the "Unlock" button to "log in" to be consistent everywhere.

**Comment by danfinlay** [comment]
Closing in favor of #3174.
