### ISSUE TITLE
[Bug]: Metamask Stuck on Loading open

### ISSUE THREAD

**Issue by alfariky** [MetaMask/metamask-extension#24777]
### Describe the bug

hi there, sorry if i put it in a wrong section but i think it's a bug, 
i am using google chrome Version 125.0.6422.113 (Official Build) (64-bit)
since 2 week ago, my metamask didn't opening. everytime i click extension it's stuck on loading logo, 
any fix for it?
and my bad, i have 2 wallet inside, which is my main wallet and another wallet for a testnet activity which is i forgot to backup.
here i screenshot my metamask
![WhatsApp Image 2024-05-25 at 19 34 07](https://github.com/MetaMask/metamask-extension/assets/53390678/c01d5071-0f12-436e-8f66-7c7c2d5fac57)

i hope i can find an answer for this bug

### Steps to reproduce

1. i open extension as usual
2. im waiting for more than 5 minute
3. i though my internet slow but then i realize it's stuck
4. i try to import my main wallet and creating new profile chrome it's success
5. the problem is, i have 2 walletin my main chrome profile and one of it i forgot to backup

### Version

11.16.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by gauthierpetetin** [comment]
Closing as duplicate: https://github.com/MetaMask/metamask-extension/issues/21874

**Comment by alfariky** [comment]
owh sorry i missed that post on 2023, i though no one share this one. thanks anyway
