### ISSUE TITLE
[Bug]: MetaMask shows transaction failed - but it's not true

### ISSUE THREAD

**Issue by mcf-rocks** [MetaMask/metamask-extension#24784]
### Describe the bug

Metamask (under activity tab) shows transaction failed... however, both the explorer (and the recipient) Coinbase, show the transaction worked.

### Expected behavior

It didn't fail - why does it show failed?

### Screenshots/Recordings

too sensetive

### Steps to reproduce

Send - USDC

### Version

11.15.6

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Severity

not all that critical, but i am kind of surprised.

**Comment by gauthierpetetin** [comment]
Closing as duplicate: https://github.com/MetaMask/metamask-extension/issues/23660
