### ISSUE TITLE
[Bug]: Metamask won't load and stuck for a long time

### ISSUE THREAD

**Issue by dedekganteng** [MetaMask/metamask-extension#24782]
### Describe the bug

Hi, i've been waiting for more 3 hours to open metamask but still won't open and stuck on loading screen
What should i do to make the app work fine? 
Because i have more than 30 wallet on it, some private key hasn't backed up
So please help me fix this issue, or some javascript i can paste on developer tools

Thank you

### Screenshots/Recordings

![Screenshot_1335](https://github.com/MetaMask/metamask-extension/assets/34489304/b480c287-5811-4989-be66-59fc9bd50665)

### Steps to reproduce

Open the metamask app won't load

### Error messages or log output

```shell
Property eval will not be hardened because it is scuttled by LavaMoat protection. Visit https://github.com/LavaMoat/LavaMoat/pull/360 to learn more.
e.<computed> @ scripts/sentry-install.js:1
 SES_UNHANDLED_REJECTION: (Error#1)
e.<computed> @ scripts/sentry-install.js:1
 Error#1: Corruption: block checksum mismatch
e.<computed> @ scripts/sentry-install.js:1
   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:274239

e.<computed> @ scripts/sentry-install.js:1
 SES_UNHANDLED_REJECTION: (Error#2)
e.<computed> @ scripts/sentry-install.js:1
 Error#2: Corruption: block checksum mismatch
e.<computed> @ scripts/sentry-install.js:1
   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:274239

e.<computed> @ scripts/sentry-install.js:1
 SES_UNHANDLED_REJECTION: (Error#3)
e.<computed> @ scripts/sentry-install.js:1
 Error#3: Corruption: block checksum mismatch
e.<computed> @ scripts/sentry-install.js:1
   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:274239
```

### Version

11.16.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Severity

This critical bug make user cannot open the app and lost data to their own

**Comment by cnsilvan** [comment]
same here.

**Comment by gauthierpetetin** [comment]
Closing as duplicate: https://github.com/MetaMask/metamask-extension/issues/21874

**Comment by dedekganteng** [comment]
why its closed as its the latest version of MM?
and still have no solution too?

**Comment by gauthierpetetin** [comment]
Hi @dedekganteng , thanks for reporting this issue. I closed it as duplicate but it's something we're trying to solve. It's just very hard to reproduce for us at the moment.
cc @MetaMask/extension-platform for visibility
