### ISSUE TITLE
Changing networks breaks watching events

### ISSUE THREAD

**Issue by futuremarc** [MetaMask/metamask-extension#2484]
Hello!

My environment is:
Metamask v3.11.2
Chrome v61.0.3163.100
MacOS v10.12.3
web3 v0.20.0

After changing networks within MetaMask, I've noticed web3.js no longer listens to watching events, and can no longer use a `filter`. The only way fix this is to disable the Chrome extension, re-enable and sign back in. I've heard reports from other users of the same behavior. I think this is related to #2454

**Comment by danfinlay** [comment]
Can you try again with the latest version of MetaMask, just published today? (v3.12.0)

What should happen:
Switching networks in MetaMask should reload any page using web3.

If you have this problem, you should also be able to remedy it by reloading the page, not re-enabling MetaMask.

Let me know if it's still happening on the current version, I see it reloading correctly atm.

**Comment by futuremarc** [comment]
Hi @danfinlay. Just tried v3.12.0 with no success. It seems if you're on the page while switching networks `filter` seems to be watching correctly, but once you've refreshed the page you're on after switching networks, the watching events no longer seem responsive. 

Switching networks again after the page loads with non responsive filters, makes them responsive again, however after refreshing the page one more time you'll be with non responsive filters again until you disable, and re-enable the extension for a more permanent solution.

**Comment by danfinlay** [comment]
Those sound like some good reproduction steps. Is there a page you're getting this result reliably, @futuremarc?

**Comment by futuremarc** [comment]
yes! my own here: [cryptolovelocks.co](http://cryptolovelocks.co)

You should be seeing a "filter" log in the console on every "latest" event. If you logged into MetaMask with a different network and try to switch to Rinkeby after-the-fact, you should be experiencing the issue

**Comment by futuremarc** [comment]
found older duplicate issue #2393
