### ISSUE TITLE
[Bug]: When conducting a direct send transaction and hovering over the 'Continue' button on the Confirmation screen, a message stating, 'Clicking this button will immediately initiate your swap transaction...'  is shown

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24915]
### Describe the bug

When conducting a direct send transaction (e.g., ETH to ETH) and hovering over the 'Continue' button on the Confirmation screen, users are presented with a message stating, 'Clicking this button will immediately initiate your swap transaction...'. The send flow remains uninterrupted; clicking 'Continue' transitions the user to a subsequent screen where they can confirm their transaction. 

### Expected behavior

The notification should be removed.

### Screenshots/Recordings

https://jam.dev/c/5b27367a-beb8-4294-84f7-d870199eeeab

### Steps to reproduce

1. Start send+swap transaction
2. Select the same destination token (e.g., ETH->ETH, LINK->LINK)
3. Hover over 'Continue" button - allow 1-2 seconds for the notification to appear
4. Notice the notification 'Clicking this button will immediately initiate your swap transaction...'

### Version

dev build

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

dev build [4c64f44](https://github.com/MetaMask/metamask-extension/pull/24914/commits/4c64f449edbfe332f60bb56db6901949af9fb5e8)

**Comment by sleepytanya** [comment]
Also present on `develop`:

https://github.com/MetaMask/metamask-extension/assets/104780023/f9906909-c768-4f93-a7b3-e4ee1f758035

**Comment by hesterbruikman** [comment]
I would add that while not severe; this issue will likely have significant reach as it's essentially a basic send tx of sending ETH from one address to another.

**Comment by sleepytanya** [comment]
Fixed, latest build [Slack discussion link](https://consensys.slack.com/archives/C068SFX90PN/p1717713259996549):

https://jam.dev/c/5232297a-ca8e-4b12-840e-40e6e083a3cb
