### ISSUE TITLE
[Bug]: Initiating a Send transaction from the Tokens tab occasionally requires two or more clicks on the 'Send' button to successfully start the transaction

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24925]
### Describe the bug

Initiating a Send transaction from the Tokens tab, specifically when selecting a token, occasionally requires two or more clicks on the 'Send' button to successfully start the transaction. 

### Expected behavior

-

### Screenshots/Recordings

Chrome:

https://jam.dev/c/b04375a9-b789-4c5b-807e-262b353f4149

Firefox:

https://github.com/MetaMask/metamask-extension/assets/104780023/26ae72fb-3863-486f-946a-191da2ac0e99

### Steps to reproduce

1. Go to Tokens tab
2. Click any token
3. Click 'Send'
4. Notice that sometimes 2 or 3 click required to start the transaction

### Error messages or log output

```shell
Warning: Failed prop type: The prop `accountName` is marked as required in `AssetBreadcrumb`, but its value is `undefined`.
    in AssetBreadcrumb (created by AssetNavigation)
    in AssetNavigation (created by NativeAsset)
    in NativeAsset (created by Asset)
    in div (created by Asset)
    in Asset (created by Context.Consumer)
    in Route (created by Authenticated)
    in Authenticated (created by ConnectFunction)
    in ConnectFunction (created by Routes)
    in Switch (created by Routes)
    in div (created by ForwardRef)
    in ForwardRef (created by Routes)
    in div (created by Routes)
    in Routes (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(Routes)) (created by Index)
    in MetamaskNotificationsProvider (created by Index)
    in CurrencyRateProvider (created by Index)
    in LegacyI18nProvider (created by Index)
    in I18nProvider (created by Index)
    in LegacyMetaMetricsProvider (created by Index)
    in MetaMetricsProvider (created by Index)
    in Router (created by HashRouter)
    in HashRouter (created by Index)
    in Provider (created by Index)
    in Index backend.js:2045
    overrideMethod backend.js:2045
    printWarning checkPropTypes.js:20
    checkPropTypes checkPropTypes.js:83
    React 2
    AssetNavigation asset-navigation.js:9
    React 8
    unstable_runWithPriority scheduler.development.js:697
    React 26
    startApp index.js:213
    launchMetamaskUi index.js:75
    handleResponse metaRPCClientFactory.js:99
    emit events.js:153
    addChunk _stream_readable.js:279
    readableAddChunk _stream_readable.js:262
    push _stream_readable.js:228
    _write ObjectMultiplex.js:70
    doWrite _stream_writable.js:390
    writeOrBuffer _stream_writable.js:381
    write _stream_writable.js:302
    ondata readable.js:662
    emit events.js:153
    addChunk readable.js:278
    readableAddChunk readable.js:255
    push readable.js:201
    _onMessage index.js:30
    PortDuplexStream index.js:12


Warning: Failed prop type: The prop `accountName` is marked as required in `AssetNavigation`, but its value is `undefined`.
    in AssetNavigation (created by NativeAsset)
    in NativeAsset (created by Asset)
    in div (created by Asset)
    in Asset (created by Context.Consumer)
    in Route (created by Authenticated)
    in Authenticated (created by ConnectFunction)
    in ConnectFunction (created by Routes)
    in Switch (created by Routes)
    in div (created by ForwardRef)
    in ForwardRef (created by Routes)
    in div (created by Routes)
    in Routes (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(Routes)) (created by Index)
    in MetamaskNotificationsProvider (created by Index)
    in CurrencyRateProvider (created by Index)
    in LegacyI18nProvider (created by Index)
    in I18nProvider (created by Index)
    in LegacyMetaMetricsProvider (created by Index)
    in MetaMetricsProvider (created by Index)
    in Router (created by HashRouter)
    in HashRouter (created by Index)
    in Provider (created by Index)
    in Index backend.js:2045
    overrideMethod backend.js:2045
    printWarning checkPropTypes.js:20
    checkPropTypes checkPropTypes.js:83
    React 2
    NativeAsset native-asset.js:35
    React 8
    unstable_runWithPriority scheduler.development.js:697
    React 26
    startApp index.js:213
    launchMetamaskUi index.js:75
    handleResponse metaRPCClientFactory.js:99
    emit events.js:153
    addChunk _stream_readable.js:279
    readableAddChunk _stream_readable.js:262
    push _stream_readable.js:228
    _write ObjectMultiplex.js:70
    doWrite _stream_writable.js:390
    writeOrBuffer _stream_writable.js:381
    write _stream_writable.js:302
    ondata readable.js:662
    emit events.js:153
    addChunk readable.js:278
    readableAddChunk readable.js:255
    push readable.js:201
    _onMessage index.js:30
    PortDuplexStream index.js:12
```

### Version

dev build

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

dev build [4c64f44](https://github.com/MetaMask/metamask-extension/pull/24914/commits/4c64f449edbfe332f60bb56db6901949af9fb5e8)

**Comment by Admin661** [comment]
> ### Describe the bug
> 
> Initiating a Send transaction from the Tokens tab, specifically when selecting a token, occasionally requires two or more clicks on the 'Send' button to successfully start the transaction. 
> 
> ### Expected behavior
> 
> -
> 
> ### Screenshots/Recordings
> 
> Chrome:
> 
> 
> 
> https://jam.dev/c/b04375a9-b789-4c5b-807e-262b353f4149
> 
> 
> 
> Firefox:
> 
> 
> 
> 
> 
> https://github.com/MetaMask/metamask-extension/assets/104780023/26ae72fb-3863-486f-946a-191da2ac0e99
> 
> 
> 
> 
> 
> ### Steps to reproduce
> 
> 1. Go to Tokens tab
> 
> 2. Click any token
> 
> 3. Click 'Send'
> 
> 4. Notice that sometimes 2 or 3 click required to start the transaction
> 
> ### Error messages or log output
> 
> ```shell
> Warning: Failed prop type: The prop `accountName` is marked as required in `AssetBreadcrumb`, but its value is `undefined`.
> 
>     in AssetBreadcrumb (created by AssetNavigation)
> 
>     in AssetNavigation (created by NativeAsset)
> 
>     in NativeAsset (created by Asset)
> 
>     in div (created by Asset)
> 
>     in Asset (created by Context.Consumer)
> 
>     in Route (created by Authenticated)
> 
>     in Authenticated (created by ConnectFunction)
> 
>     in ConnectFunction (created by Routes)
> 
>     in Switch (created by Routes)
> 
>     in div (created by ForwardRef)
> 
>     in ForwardRef (created by Routes)
> 
>     in div (created by Routes)
> 
>     in Routes (created by ConnectFunction)
> 
>     in ConnectFunction (created by Context.Consumer)
> 
>     in withRouter(Connect(Routes)) (created by Index)
> 
>     in MetamaskNotificationsProvider (created by Index)
> 
>     in CurrencyRateProvider (created by Index)
> 
>     in LegacyI18nProvider (created by Index)
> 
>     in I18nProvider (created by Index)
> 
>     in LegacyMetaMetricsProvider (created by Index)
> 
>     in MetaMetricsProvider (created by Index)
> 
>     in Router (created by HashRouter)
> 
>     in HashRouter (created by Index)
> 
>     in Provider (created by Index)
> 
>     in Index backend.js:2045
> 
>     overrideMethod backend.js:2045
> 
>     printWarning checkPropTypes.js:20
> 
>     checkPropTypes checkPropTypes.js:83
> 
>     React 2
> 
>     AssetNavigation asset-navigation.js:9
> 
>     React 8
> 
>     unstable_runWithPriority scheduler.development.js:697
> 
>     React 26
> 
>     startApp index.js:213
> 
>     launchMetamaskUi index.js:75
> 
>     handleResponse metaRPCClientFactory.js:99
> 
>     emit events.js:153
> 
>     addChunk _stream_readable.js:279
> 
>     readableAddChunk _stream_readable.js:262
> 
>     push _stream_readable.js:228
> 
>     _write ObjectMultiplex.js:70
> 
>     doWrite _stream_writable.js:390
> 
>     writeOrBuffer _stream_writable.js:381
> 
>     write _stream_writable.js:302
> 
>     ondata readable.js:662
> 
>     emit events.js:153
> 
>     addChunk readable.js:278
> 
>     readableAddChunk readable.js:255
> 
>     push readable.js:201
> 
>     _onMessage index.js:30
> 
>     PortDuplexStream index.js:12
> 
> 
> 
> 
> 
> Warning: Failed prop type: The prop `accountName` is marked as required in `AssetNavigation`, but its value is `undefined`.
> 
>     in AssetNavigation (created by NativeAsset)
> 
>     in NativeAsset (created by Asset)
> 
>     in div (created by Asset)
> 
>     in Asset (created by Context.Consumer)
> 
>     in Route (created by Authenticated)
> 
>     in Authenticated (created by ConnectFunction)
> 
>     in ConnectFunction (created by Routes)
> 
>     in Switch (created by Routes)
> 
>     in div (created by ForwardRef)
> 
>     in ForwardRef (created by Routes)
> 
>     in div (created by Routes)
> 
>     in Routes (created by ConnectFunction)
> 
>     in ConnectFunction (created by Context.Consumer)
> 
>     in withRouter(Connect(Routes)) (created by Index)
> 
>     in MetamaskNotificationsProvider (created by Index)
> 
>     in CurrencyRateProvider (created by Index)
> 
>     in LegacyI18nProvider (created by Index)
> 
>     in I18nProvider (created by Index)
> 
>     in LegacyMetaMetricsProvider (created by Index)
> 
>     in MetaMetricsProvider (created by Index)
> 
>     in Router (created by HashRouter)
> 
>     in HashRouter (created by Index)
> 
>     in Provider (created by Index)
> 
>     in Index backend.js:2045
> 
>     overrideMethod backend.js:2045
> 
>     printWarning checkPropTypes.js:20
> 
>     checkPropTypes checkPropTypes.js:83
> 
>     React 2
> 
>     NativeAsset native-asset.js:35
> 
>     React 8
> 
>     unstable_runWithPriority scheduler.development.js:697
> 
>     React 26
> 
>     startApp index.js:213
> 
>     launchMetamaskUi index.js:75
> 
>     handleResponse metaRPCClientFactory.js:99
> 
>     emit events.js:153
> 
>     addChunk _stream_readable.js:279
> 
>     readableAddChunk _stream_readable.js:262
> 
>     push _stream_readable.js:228
> 
>     _write ObjectMultiplex.js:70
> 
>     doWrite _stream_writable.js:390
> 
>     writeOrBuffer _stream_writable.js:381
> 
>     write _stream_writable.js:302
> 
>     ondata readable.js:662
> 
>     emit events.js:153
> 
>     addChunk readable.js:278
> 
>     readableAddChunk readable.js:255
> 
>     push readable.js:201
> 
>     _onMessage index.js:30
> 
>     PortDuplexStream index.js:12
> ```
> 
> 
> ### Version
> 
> dev build
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Chrome, Firefox
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> dev build [4c64f44](https://github.com/MetaMask/metamask-extension/pull/24914/commits/4c64f449edbfe332f60bb56db6901949af9fb5e8)
> 
> ### Severity
> 
> _No response_

Hello @sleepytanya you'll have to rectify with the metamask loptimal weblink and try it again.

**Comment by sleepytanya** [comment]
Also present on `develop`:


https://github.com/MetaMask/metamask-extension/assets/104780023/223e732c-ce2a-4992-ac14-9571308a5087

**Comment by sleepytanya** [comment]
The issue is still present on the latest build [Slack discussion link](https://consensys.slack.com/archives/C068SFX90PN/p1717713259996549):

https://jam.dev/c/3c7e9c6d-5177-41a5-8be3-58cd1a01bc39

**Comment by BZahory** [comment]
Holding off on this one for now since it's seems to be related to the broader `getTokenStandardAndDetails` issues

**Comment by desi** [comment]
I no longer see this issue, tested on RC 12.10.0. Leaving as closed
