### ISSUE TITLE
[Bug]: The quotes are not being fetched when sending tokens other than ETH 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24921]
### Describe the bug

When attempting to send tokens other than ETH and choosing any destination token, the quotes are not being fetched as expected.
Here is the [related bug](https://github.com/MetaMask/metamask-extension/issues/24445), that was happening following fresh installation (not every time). Current bug doesn't need to have a fresh install to happen. Within the same installation this bug may intermittently appear and then resolve itself. The behavior seems to be related to the token balances being shown in the send flow screens.

https://github.com/MetaMask/metamask-extension/issues/24918 - probably the same bug.

No errors except 429s:

<img width="472" alt="Screenshot 2024-05-30 at 15 35 45" src="https://github.com/MetaMask/metamask-extension/assets/104780023/66d197ce-dbb2-4c4b-9559-20ce91e0a576">

### Expected behavior

-

### Screenshots/Recordings
Bug:
https://jam.dev/c/f52644d9-a592-4004-9234-30f1d1a90ea2

Same install, bug appears and disappears:
 https://jam.dev/c/0f1374f1-0263-4cde-80d9-bfaed4f53f57

### Steps to reproduce

1. Start send+swap transaction
2. Select token other than ETH
3. Select different destination token

### Version

dev build

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

dev build [4c64f44](https://github.com/MetaMask/metamask-extension/pull/24914/commits/4c64f449edbfe332f60bb56db6901949af9fb5e8)

**Comment by bschorchit** [comment]
Besides the bug reported here, whenever we disable the continue/confirm button, we should be some feedback to the user on what is preventing them to proceed (an error or some action they need to take). 
On the recording I see the button becomes disabled, but there's no feedback to the user on why this happened and how they can possibly recover from it.

**Comment by BZahory** [comment]
Not sure if this is a bug; the user needs to input an amount before we can fetch a swap+send quote

**Comment by micaelae** [comment]
@sleepytanya can this be closed?

**Comment by sleepytanya** [comment]
@micaela I think we already have this bug here https://github.com/MetaMask/metamask-extension/issues/24918. Closing!
