### ISSUE TITLE
[Bug]: CORS, 'Failed gas fee / price estimation failed' error displays in FireFox on ConfirmLegacyGasDisplay

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#24948]
### Describe the bug

On Firefox I see CORS, 'Failed gas fee / price estimation failed'

Discovered while QA'ing https://github.com/MetaMask/metamask-extension/pull/24854#issuecomment-2136464701

### Screenshots/Recordings

![CleanShot 2024-05-31 at 23 27 24](https://github.com/MetaMask/metamask-extension/assets/20778143/f99b0319-c7ad-4a48-88dd-710b8487cd61)

### Steps to reproduce

1. Go to test dapp
2. Use L2 Network
3. Click on "Create a token."
4. Observe error message in console

### Version

11.16.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
I was not able to reproduce this issue

**Comment by adrigug** [comment]
Hi @digiwand - i tried to reproduce the issue in firefox 12.6.2. When i select "scroll" as a network, and then click on "create token", i only get an error message after i cancel the signature part.

Can you please review the recording below, try again on your end and let me know if you still see this behavior?

https://github.com/user-attachments/assets/a5b38a1b-f0cf-49d9-a3a1-98f4018a9991
thanks

**Comment by adrigug** [comment]
https://github.com/user-attachments/assets/3184b07c-0d01-4dc3-8e98-3e803e978b2e

**Comment by adrigug** [comment]
closing this issue. I did not get the CORS error message when reproducing the steps. the only error message that i had was after i cancelled the processing of the transaction (as highlighted in the video).
