### ISSUE TITLE
[Bug]: Fiat values continue to show despite "Show conversion on test networks" (Advanced Settings) being disabled

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#24945]
### Describe the bug

Fiat values continue to show despite "Show conversion on test networks" (Advanced Settings) being disabled

Discovered in https://github.com/MetaMask/metamask-extension/pull/24854#issuecomment-2136464701

### Expected behavior

Fiat conversion values should not show on test networks when  "Show conversion on test networks" (Advanced Settings) being disabled

### Screenshots/Recordings

<img width="358" alt="334642377-bd2eec03-02da-4f56-a2b0-5a3f39abbef9" src="https://github.com/MetaMask/metamask-extension/assets/20778143/f5725468-4eb2-478e-a048-e137a5216c37">

### Steps to reproduce

1. Turn off "Show conversion on test networks" setting in Advanced Settings
2. Use L2 test network
3. Go to test dapp
4. Click on "Create a token"
5. Observe fiat value is shown

### Version

11.18.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
`Develop`, Settings->Advanced->Show conversion on test networks disabled - for certain test networks fat values are shown.
Sepolia, BNB Chain testnets - no conversion:

<img width="887" alt="Screenshot 2024-06-01 at 14 19 15" src="https://github.com/MetaMask/metamask-extension/assets/104780023/d2b29569-70ff-46a3-9d92-9ebda76397eb">

Arbitrum Sepolia, Polygon Amoy, Avalanche Fuji - fiat values displayed:

<img width="887" alt="Screenshot 2024-06-01 at 14 16 27" src="https://github.com/MetaMask/metamask-extension/assets/104780023/55f17fb0-d59b-47b2-b844-8d4e77ec9ae9">

**Comment by digiwand** [comment]
thanks @sleepytanya for the screenshots and additional cases above!

I've tested and also confirmed this issue exists for native testnets.

It appears a few places on confirmation pages rely only on the useCurrencyRateCheck (Security & Privacy > "Show balance and token price checker" setting value) where we display fiat values. However, we are expecting the display of the fiat value also to include showFiatInTestnets (Advanced > "Show conversion on test networks" setting value) in the logic. 

I believe we'll want to use the `getShouldShowFiat` for these instances which takes both the useCurrencyRateCheck and showFiatInTestnets checks, along with other conditions.
```
export function getShouldShowFiat(state) {
  const isMainNet = getIsMainnet(state);
  const isLineaMainNet = getIsLineaMainnet(state);
  const isCustomNetwork = getIsCustomNetwork(state);
  const conversionRate = getConversionRate(state);
  const useCurrencyRateCheck = getUseCurrencyRateCheck(state);
  const { showFiatInTestnets } = getPreferences(state);
  return Boolean(
    (isMainNet || isLineaMainNet || isCustomNetwork || showFiatInTestnets) &&
      useCurrencyRateCheck &&
      conversionRate,
  );
}
```

**Comment by digiwand** [comment]
unassigning myself to refine and reprioritize the issue
