### ISSUE TITLE
[Bug]: Invalid prop `contentText` supplied to `InfoTooltip using ConfirmLegacyGasDisplay

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#24946]
### Describe the bug

Invalid prop Error displays while using ConfirmLegacyGasDisplay

### Steps to reproduce

1. Go to test dapp
2. Use L2 Network
3. Click on "Create a token."
4. Observe error message in console

### Error messages or log output

```shell
Invalid prop `contentText` of value `Edit to use MetaMask's recommended gas fee based on the latest block.` supplied to `InfoTooltip, expected one of [null,null]
```

### Version

11.16.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hjetpoluru** [comment]
Unable to reproduce the issue. 
[digiwand](https://github.com/digiwand) could you please confirm if its still issue
