### ISSUE TITLE
uat- Allow adding token by address in search field

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2495]
Right now the new token adding flow is great, I really like it. Here's a way it can be better:

When you click "add token", the top field is a search field for token names. The "add custom token" button is so far down, I think most people won't see it, and so I expect most people will paste token addresses into the token name field, resulting in something like this:

![screen shot 2017-10-26 at 1 12 44 pm](https://user-images.githubusercontent.com/542863/32074798-61457eba-ba4f-11e7-9da5-22a747e6100d.png)

We could auto-identify an ethereum address-like string in that input, and if they input an ethereum address, automatically open the "add custom token" view and copy the address into it.

This would save the user an extra click and a paste when adding tokens by address.

**Comment by danjm** [comment]
This should be resolved with the implementation of https://github.com/MetaMask/metamask-extension/issues/3326
