### ISSUE TITLE
[Bug]: Errors on the  'remove-old-send' branch 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24977]
### Describe the bug

I've noticed a pattern of random errors which seem to be occurring within the `remove-old-send` branch, and do not appear to be tied to any particular actions. Despite their seemingly random nature, these errors are occurring with notable consistency. 

Created for visibility, will keep this issue updated.

### Expected behavior

-

### Screenshots/Recordings

<img width="556" alt="Screenshot 2024-06-01 at 23 52 58" src="https://github.com/MetaMask/metamask-extension/assets/104780023/7a89ce55-17e0-41f2-b402-5f99a820f928">

<img width="553" alt="Screenshot 2024-06-02 at 00 00 56" src="https://github.com/MetaMask/metamask-extension/assets/104780023/d56ef797-c68d-44bc-8bd1-53097c386815">

<img width="1112" alt="Screenshot 2024-05-30 at 19 28 23" src="https://github.com/MetaMask/metamask-extension/assets/104780023/35f34de1-d185-4d1c-9cc4-b37870d03eee">

<img width="1084" alt="Screenshot 2024-05-30 at 19 28 03" src="https://github.com/MetaMask/metamask-extension/assets/104780023/c2cda16a-cfc7-4153-ab37-a640e1354d4f">

<img width="1115" alt="Screenshot 2024-05-30 at 19 30 21" src="https://github.com/MetaMask/metamask-extension/assets/104780023/960c4c85-65b9-4d50-b3c4-8f57bd71446b">

### Steps to reproduce

1. Perform any actions
2. Notice errors

### Version

dev build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

dev build [4c64f44](https://github.com/MetaMask/metamask-extension/pull/24914/commits/4c64f449edbfe332f60bb56db6901949af9fb5e8)

**Comment by BZahory** [comment]
Are you still seeing these?

**Comment by sleepytanya** [comment]
I'm pretty sure I see al of those errors on `develop` as well. So I'm closing this as it doesn't look like being introduced by send+swap.
