### ISSUE TITLE
[Bug]: Performance degradation when deploying contracts from the test-dapp

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#24976]
### Describe the bug

While Legacy and EIP1559 transactions initiated from the test-dApp seem to operate smoothly, attempting to deploy any type of contract, including ERC20, ERC721, or ERC1155 contracts, significantly slows down the extension. In some instances, the extension may become unresponsive for a minute or more. When the request eventually processes, an indication of an unapproved transaction might only be visible through the MetaMask blue badge or within the Activity tab, without the automatic appearance of the popup. To view the popup, one needs to manually click on the MetaMask icon, and it also requires an external click to close, as it doesn't automatically dismiss itself.

### Expected behavior

-

### Screenshots/Recordings

Firefox:

https://github.com/MetaMask/metamask-extension/assets/104780023/75511c33-eb84-4ecc-bc9f-b8a304b1e46a

Chrome:

https://github.com/MetaMask/metamask-extension/assets/104780023/57be1e31-660e-42bb-8507-fe841be4caae

<img width="840" alt="Screenshot 2024-06-01 at 18 44 24" src="https://github.com/MetaMask/metamask-extension/assets/104780023/d3f4ed11-2d40-4e74-b2c5-8ea9ff706f8e">

<img width="942" alt="Screenshot 2024-06-01 at 18 44 35" src="https://github.com/MetaMask/metamask-extension/assets/104780023/806a1594-e610-4a67-8d37-e9a9995a970d">

### Steps to reproduce

1. Go to [test dapp](https://metamask.github.io/test-dapp/)
2. Connect to MetaMask
3. Select any network
4. Try to deploy any kind of contracts 
5. See MM slowing down

### Error messages or log output

```shell
common-1.js:1 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'gasFeeEstimates')
  at chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-1.js:1:158861
  at chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-1.js:1:156987
  at e.produce (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-4.js:3:34095)
  at e.produceWithPatches (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-4.js:3:34610)
  at He.update (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-1.js:1:229444)
  at He.O (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-1.js:1:156897)
  at He.W (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-1.js:1:158792)
  at a.emit (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-3.js:27:59630)
  at n.GasFeePoller.b (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-1.js:1:167637)
  at async Promise.all (index 0)
  at async n.GasFeePoller._ (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-1.js:1:167305)
  at async n.GasFeePoller.v (chrome-extension://mjbmnplbjghbbgcbammdooemmipebiil/common-1.js:1:166875)
(anonymous)	@
```

### Version

11.16.3, 11.16.4

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Same behavior on production 11.16.3:

https://jam.dev/c/4dc42f33-2d28-4fb7-97ce-2c11480524d3

**Comment by blurpesec** [comment]
This network is now supported and should be a non-issue now. Can you validate @sleepytanya ?

**Comment by dbrans** [comment]
Assigned to @sleepytanya to confirm this is no longer an issue because of @blurpesec's comment.

**Comment by sleepytanya** [comment]
Confirming that this is no longer an issue:


https://github.com/user-attachments/assets/349bff7d-f255-4fd3-a9b9-4646d5cf66ef
