### ISSUE TITLE
FQA for "Where did my tokens go?" didn't help

### ISSUE THREAD

**Issue by nissimt** [MetaMask/metamask-extension#2499]
Hi,
Metamask doesn't add my EOS tokens when I put the contract address, EOS name and decimals 18.
 I do see my tokens on etherscan.
I bought the tokens, two months ago.
Please advise.

**Comment by Zanibas** [comment]
Are you sure you inputted 0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0 and not 0xd0a6E6C54DbC68Db5db3A091B171A77407Ff7ccf

**Comment by nissimt** [comment]
Hi Kevin,Thank you for replying.
I am new in this.What is this address:0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0?Where can I see it?Regards,nissimt
 

    On Friday, October 27, 2017 11:35 PM, Kevin Serrano <notifications@github.com> wrote:
 

 Are you sure you inputted 0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0 and not 0xd0a6E6C54DbC68Db5db3A091B171A77407Ff7ccf—

**Comment by tmashuang** [comment]
[https://etherscan.io/token/EOS](https://etherscan.io/token/EOS) 0x86fa... is the listed contract address for EOS.

**Comment by nissimt** [comment]
So I need to put this address(0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0) in my metamask, in order to see my EOS tokens there? with EOS as symbol and 18 ?
