### ISSUE TITLE
Add support for natspec

### ISSUE THREAD

**Issue by fvictorio** [MetaMask/metamask-extension#2501]
Solidity allows using natspec comments to provide a confirmation text to a user when they attempt to call a function of a contract. Right now, it seems like MetaMask doesn't support this. It would be nice to have it added.

See:
- [Docs](http://solidity.readthedocs.io/en/develop/layout-of-source-files.html#comments)
- [Question in StackExchange](https://ethereum.stackexchange.com/questions/29332/how-do-you-use-natspec-comments-to-provide-a-confirmation-text)

**Comment by WopKatan** [comment]
+1

**Comment by danfinlay** [comment]
This would be really cool, but the docs are awful. It's unclear how to parse these natspec comments, and it's unclear if these comments are even published with the bytecode with Solidity. I'm actually pretty sure these are not published by the bytecode, they seem to only be output as a metadata file:
https://github.com/ethereum/wiki/wiki/Natspec-Example

I would love for NatSpec definitions to be published with smart contracts, but if they aren't, there's an open question for how we can trust any documents associated with a smart contract.

Closing until a solution is available for securely retrieving natspec documents from a published bytecode.

**Comment by guylando** [comment]
@danfinlay the natspec is inside a metadata file which can be published to swarm and it IS always embedded in the contract bytecode, see:
https://solidity.readthedocs.io/en/v0.5.8/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode
https://solidity.readthedocs.io/en/v0.5.8/metadata.html#usage-for-automatic-interface-generation-and-natspec
reopen?

**Comment by CJentzsch** [comment]
@danfinlay I think this is the solution to the problem: https://sourcify.dev/

MM could check whether they find a verified contract there, and if so, use the NatSpec comments.
