### ISSUE TITLE
[Bug]:mumubit.com transaction  wrong classified as deceptive request 

### ISSUE THREAD

**Issue by Duanwu0111** [MetaMask/metamask-extension#25016]
### Describe the bug

when users approve USDT to our contract, the Metamask display the "this is a deceptive request" notice, this is definitely a wrong classification. 
![image](https://github.com/MetaMask/metamask-extension/assets/171629730/522b6c3a-b966-4f0e-bdd6-2672f0e73cba)

https://buider.mumubit.com/buy is an node sales Dapp site under the Metacraft.pro, and our contract had beed audited and verified by Certik(https://www.certik.com/).

Metacraft is a leading-edge platform dedicated to transforming the landscape of blockchain and project release. Established in Toronto, Canada, in the year of 2021, Metacraft operates with a global perspective, boasting team members across Europe, Asia, and other parts of the world. Our mission is to provide a comprehensive ecosystem that supports innovative projects and fosters community engagement through a suite of groundbreaking products and services.

MetaCraft.pro is a leading decentralized IDO and project launch platform.
MetaCraft official website: https://metacraft.pro/
Official community link: https://t.me/MetacraftproEN
Official Twitter: https://twitter.com/Metacraftpro

We have submit several times on the issue reports site, but there has no improve process for days. It is having a negative impact on our sales.
So submit this issue here, please remove the metamask wrong classfication report

Thanks alot!

### Expected behavior

No warning should popup in metamask. It is having a negative impact on our sales.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/171629730/e179d2f0-547c-4165-a3ba-3cf2346fca2b)

### Steps to reproduce

Create transaction in [builder.mumubit.com/buy](https://builder.mumubit.com/buy/)
Select to  buy Validator Node
input the node name
click the approve button, and  click the confirm purchase
Open metamask
Error message appear when metamask pops up

'''

This is a deceptive request

If you approve this request, you might lose your assets.

See details

• Transaction with suspicious patterns
Something doesn't look right? 
Report anissue
Powered by  blockaid
'''

### Version

11.16.4

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS, Linux

### Severity

Severe, has an negative impact on our project
All users are scared to confirm the transaction due to this error.

@bschorchit could you please do resolve this issue when you see this issue here?

**Comment by gauthierpetetin** [comment]
Hi @Duanwu0111 , we recommend you click on “See details” within the banner warning and then on “Report an issue” as this is the most effective to have the issue addressed.

**Comment by Duanwu0111** [comment]
Hi @gauthierpetetin We have submit several times on Se Details and Report an Issue, but the alert does not disappear.
I find out some issues like this are solved here, so I post it this morinig!

**Comment by gauthierpetetin** [comment]
cc @bschorchit @MetaMask/confirmations for visibility
