### ISSUE TITLE
[Bug]: Smart Transactions - Legacy transactions (type 0x0) are converted in type 0x2 when routed as a smart transaction

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25021]
### Describe the bug

Whenever I am sending a type 0x0 transaction, I can see how the gas values are the ones corresponding to the type 0x0 tx. However, if I have the Smart Transaction setting enabled, that transaction will be sent as a type 0x2 without notice.

### Expected behavior

If Smart Transactions are only supporting type 0x2, we should not convert legacy tx to type 0x2 tx without notice
- either we display a warning to the user
- or directly display the EIP1559 tx screen with the corresponding gas

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/9eeeb103-79a0-4724-a378-33798e5ed04d

See how displayed gas values are legacy ones

![Screenshot from 2024-06-04 10-06-09](https://github.com/MetaMask/metamask-extension/assets/54408225/9ca45a27-593b-4b53-8245-bd42e068ca5a)

### Steps to reproduce

1. Enable Smart Transactions
2. Select Sepolia
3. Go to the test dapp
4. Trigger a Legacy tx
5. See how gas corresponds to the legacy tx view
6. Submit the tx
7. Go to Etherscan
8. See how the tx is no type 0x2 with the EIP1559 gas

### Version

11.16.4 prod

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by klejeune** [comment]
This feature is not currently supported. Closing the ticket.
