### ISSUE TITLE
[Bug]: Got "missing r" error when using EAS + Metamask + etherjs #97

### ISSUE THREAD

**Issue by xiaohou77** [MetaMask/metamask-extension#25032]
### Describe the bug

**Issue detail**
In our dApp https://app.fairsharing.xyz/, when we make an onchain attestaion call, metamask returned the error as below snapshot below.

We use EAS + Metamask + etherjs. When we change wallet app to like OKX/Rabby wallet, it works well.

I found a relative issue https://github.com/ethers-io/ethers.js/issues/3926, seems we have to wait for metamask to fix it?

Please help look into this issue, it is blocking many users using our dApp now.

**Many people met the same issue too:**
https://github.com/ethereum-attestation-service/eas-sdk/issues/97

### Expected behavior

No error reported by MetaMask extention since onchain call is successful.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/38149053/4871d7bd-7996-451a-be22-65869027eb94)

### Steps to reproduce

1. Go to: https://app.fairsharing.xyz/
2. Create a project, then add 1 or 2 members by wallet addresses
3. Adding members will fail

### Version

11.15.6

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context
Before it works well, abour 1 month ago the issue started occuring.
 
### Severity
**P0**
Many developers have reported this issue as well, see https://github.com/ethereum-attestation-service/eas-sdk/issues/97

_No response_

**Comment by itev4n7** [comment]
https://github.com/ethereum-attestation-service/eas-sdk/issues/97#issuecomment-2147241562

**Comment by peterjurco** [comment]
I experienced "Missing r" error as well but it was [fixed](https://github.com/MetaMask/metamask-extension/issues/24359#issuecomment-2124634895) in MetaMask [11.16.0](https://github.com/MetaMask/metamask-extension/releases/tag/v11.16.0)

**Comment by dbrans** [comment]
I've marked this issue as fixed. If you run into this bug again on v11.16.0 or later, please let us know!
