### ISSUE TITLE
[Bug]: Move ToastContainer and Toasts to Home component

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#25035]
### Describe the bug

At present, since the `<ToastContainer>` and `<Toast>`s are in `routes.component.js`, these toasts (like the Privacy Policy) can display on top of confirmations.  Instead, we should move these to `home.component.js` so that they only display on the wallet screen.

### Steps to reproduce

1.  Hardcode a toast in `routes.component.js` to display
2. Open a confirmation
3. See the toast

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hjetpoluru** [comment]
I see the toast appearing the home page and the PR that fixed is here https://github.com/MetaMask/metamask-extension/pull/25187 and hence closing the issue
