### ISSUE TITLE
Cannot install opera extension

### ISSUE THREAD

**Issue by jlanzago** [MetaMask/metamask-extension#2504]
I cannot install the extension for Opera 48.0.2685.52, Mac OS High Sierra. It just displays an error when trying to install from the Opera extension page. 
<img width="1006" alt="captura de pantalla 2017-10-27 a la s 23 24 55" src="https://user-images.githubusercontent.com/5902645/32131221-1724de00-bb6e-11e7-9024-4e7a04f4092b.png">

**Comment by StevenGann** [comment]
I ran into this issue today.
At this point, MetaMask is the only reason I have Chrome installed. Opera may be a minority, but it exists and has users that appreciate MetaMask.

**Comment by StevenGann** [comment]
I tried downloading the extension manually from the Releases page, and it still cannot load correctly.

The manifest.json references a script "scripts/chromereload.js" which is not present in the released zip file.

**Comment by Freekoid** [comment]
Yes I also have to use Chrome "only" for Metamask which is a drag :(
I am not a techi but I can manage with enough info... can you please specify the process a bit more StevenGann ? Where do I get this chromereload.js file exactly ? What repository ?
Thx

**Comment by tmashuang** [comment]
@Freekoid You will need the source from 'scripts/chromereload.js'. I will link a zip build with the missing script. [Metamask-opera.zip](https://github.com/MetaMask/metamask-extension/files/1468302/Metamask-opera.zip). You will need to extract the folder in whichever directory is easiest to find for you and load it into Opera. 
If you are worried about me providing malicious code. You can clone the repository, `npm i && npm dist` through cmd, and find `app/scripts/chromereload.js`, and add it to `dist/opera/scripts/chromereload.js`. 
In Opera, you will need to go to the extension list, enable developer mode, and Load the unpacked extension in the directory you have it stored.

**Comment by danfinlay** [comment]
Sounds like an issue with our `gulpfile.js` build, is for some reason not including that reload file. Should be fairly easy to fix...

**Comment by danfinlay** [comment]
I have a fix for this pending merge, should make it in the next release, next week.

**Comment by Freekoid** [comment]
Thanx @tmashuang and @danfinlay

**Comment by tmashuang** [comment]
Opera extension review could take a while. I have an alternative install to the Opera Addon Store. Opera Software created a `Download Chrome Extension` addon to install extensions from the Chrome Extension Web Store.

Steps to get the latest Metamask Version: 
- Download `Download Chrome Extension` Opera addon
- navigate to Metamask in the Chrome Web Store, `https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn`
