### ISSUE TITLE
Full-screen home page & dialog

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#25068]
Similar to e.g. iOS or Telegram mini apps, let's;
- drop the delineator on the home pages & dialogs and i.e. populate the content straight into the container with the same `16px` padding all around
- make home pages full-screen (and i.e. hide the global MetaMask header)
- update to the redesigned header (with `back` button on the home page, and `close` button on the dialogs)

<img width="1089" alt="full-screen-experiences" src="https://github.com/MetaMask/metamask-extension/assets/34306844/6ba003f1-44cf-4a36-8906-c5f6d143123c">

**Comment by david0xd** [comment]
After having discussion we made decision to update the `SnapAuthorshipHeader` primary component and reflect the changes everywhere its used. New design instructions are provided [here](https://www.figma.com/design/Dxbatuhh6MPg0mQ5Vqa4cI/Headers?node-id=2-2043&t=PPyh7R6cV4ObK6u7-1).
