### ISSUE TITLE
UI makes it difficult to copy/paste transaction data

### ISSUE THREAD

**Issue by ptrwtts** [MetaMask/metamask-extension#2509]
It's very common to copy/paste values in order to execute a transaction. However, if you need to copy multiple values (recipient + data, recipient + amount, etc), MetaMask makes it very difficult to do. When you go to copy the second value, your draft transaction with the first value is discarded.

To make this possible, the extension should keep track of your draft if you have started to fill out any values.

**Comment by crystalneth** [comment]
It's basically impossible to use MetaMask Chrome when multiple fields need to be copy/pasted, e.g. address and data fields. I've had to move back to MEW.

**Comment by tmashuang** [comment]
A workaround for losing focus off of Metamask would be to open up the extension directly through the url. Should be something like chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html. If Metamask is loaded locally, the extension ID will be different.

**Comment by ptrwtts** [comment]
Thanks. I'll probably use this workaround myself, however it's not very user friendly. 

We have an application where end users will need to make transactions and paste data in. We were going recommend MetaMask, but until this fixed, we will need to recommend alternatives.

**Comment by danfinlay** [comment]
This is fixed in our new UI, coming soon, because we have an "open in full window" button.
