### ISSUE TITLE
[Bug]: On the token details screen, the amount displayed is not rounded and may not be fully visible

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25132]
### Describe the bug

On the token details screen, the amount displayed is not rounded and may not be fully visible.

### Expected behavior

-

### Screenshots/Recordings

<img width="650" alt="Screenshot 2024-06-06 at 21 55 11" src="https://github.com/MetaMask/metamask-extension/assets/104780023/e0444253-8f8c-494c-9e70-47b7ba3c2ced">

### Steps to reproduce

1. Select any token that has a lengthy value
2. Notice the amount is not fully visible

### Version

sens+swap build

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Latest build [Slack discussion link](https://consensys.slack.com/archives/C068SFX90PN/p1717713259996549)

**Comment by BZahory** [comment]
Can we remove the swap+send label? This issue is out of scope and present in prod as well
