### ISSUE TITLE
[Bug]: No warning shown when the account doesn't have sufficient balance' for gas fees, pop-up notification wording should be modified

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25133]
### Describe the bug

Currently we show warning 'Insufficient funds for gas' only for native origin token. 
If user selects non-native origin token the warning is not displayed and transaction can be submitted - this is incorrect behavior and the transaction fails as expected. Additionally 'Failed transaction...' pop-up wording should be more human-readable.

### Expected behavior

Warning 'Insufficient funds for gas' should be displayed for all tokens. Pop-up message should be user friendly.

### Screenshots/Recordings

Video:   https://jam.dev/c/a7680c65-c4ca-400d-b766-d1bba3a4f402

Warning for native token:

<img width="422" alt="Screenshot 2024-06-07 at 00 02 09" src="https://github.com/MetaMask/metamask-extension/assets/104780023/50d27841-4cae-4823-908e-f40a679ad08e">

Pop-up text:

<img width="388" alt="Screenshot 2024-06-07 at 00 03 58" src="https://github.com/MetaMask/metamask-extension/assets/104780023/2d8a07c1-c31d-4583-8c73-88369b913600">

<img width="376" alt="Screenshot 2024-06-07 at 00 04 36" src="https://github.com/MetaMask/metamask-extension/assets/104780023/72c90739-94b8-49a3-aa40-fd4f6db97bc6">

### Steps to reproduce

1. Start send+swap transaction for the account with low balance
2. Select non-native origin token
3. Notice that warning about insufficient funds is not shown and 'Confirm' button is available
4. Confirm transaction
5. See the notification

### Version

Latest send+swap build

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Latest build [Slack discussion link](https://consensys.slack.com/archives/C068SFX90PN/p1717713259996549)

**Comment by sleepytanya** [comment]
Latest send+swap build:
- warning 'Insufficient funds for gas' is displayed for native and non-native tokens
- 'Confirm' button is disabled only for the native token, transactions for other token can be submitted

Native token with insufficient funds:             https://jam.dev/c/71b7f50f-a2af-4dc8-ac9d-6392a2195474

Non-native token with insufficient funds:     https://jam.dev/c/d26af297-8842-46fa-a39d-9a8150ad7147

**Comment by ejwessel** [comment]
@sleepytanya it seems all that's left is that the confirmation button should be disabled right?

**Comment by sleepytanya** [comment]
@ejwessel Should we close it since it's already disabled in 12.0.0?


https://github.com/user-attachments/assets/694e149c-cd68-4a57-8ef2-8c303f858c11
