### ISSUE TITLE
Metamask not injecting web3 in chrome

### ISSUE THREAD

**Issue by rawadrifai** [MetaMask/metamask-extension#2514]
I'm running Metamask 3.12.0, Chrome 61.0.3163.100
When I connect from Metamask to local rpc 8545, there seems to be an issue injecting web3 object in my runtime. 
Specifically this condition is never satisfied `if (typeof web3 !== 'undefined')`
Furthermore, I think metamask is supposed to throw a message in console of chrome that it injected web3. I don't see that either.
p.s. I'm using a react js frontend (not sure if that matters).

Can you assist please?

Thanks,

**Comment by danfinlay** [comment]
I would first look for errors in the background console:
https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by rawadrifai** [comment]
I found these logs

> Failed to load resource: net::ERR_CONNECTION_REFUSED
> background.js:17107 Uncaught (in promise) TypeError: Failed to fetch

Another behavior worth mentioning:
If I have "private network" selected, then I disable and enable metamask, Metamask is not able to connect to the test private network. It gets stuck at "Connecting to unknown private network". If I switch to Main network then back to private, then it shows the logs above in the background console.

**Comment by danfinlay** [comment]
Sorry this is so mysterious! Before we go further, just know you might be able to just fix this by restarting your browser.

If you're up for more debugging, we can try to get to the root of this.

That error *could* cause this, depending where it's happening. In that background inspector, you can check the network tab, and if you can find the red request representing the `ERR_CONNECTION_REFUSED` error, you can look at request + response data, and that would both be relevant to investigating this.

**Comment by rawadrifai** [comment]
No worries, and thanks for helping.
So I restarted Chrome, you're right.. that partially fixed something. The call to localhost:8545 is not coming back with 200 OK in the Network Tab. So I don't see errors in the background Console anymore.

But I still don't see web3 being injected. Is it supposed to log something in console when it gets injected? Also my custom react js app did not detect web3 either. 

I'm up for debugging. I need to resolve this.

**Comment by rawadrifai** [comment]
![image](https://user-images.githubusercontent.com/24530625/32244970-7d9a21ce-be37-11e7-9cc3-a32a9b8d045c.png)

**Comment by rawadrifai** [comment]
![image](https://user-images.githubusercontent.com/24530625/32245271-74fb3de0-be38-11e7-96e6-4b115e150b4e.png)

**Comment by rawadrifai** [comment]
![image](https://user-images.githubusercontent.com/24530625/32245285-8037c584-be38-11e7-8847-1af03ffaab3f.png)

**Comment by danfinlay** [comment]
In that screenshot, I don't see MetaMask in the toolbar. Is it possible you're using a different chrome user profile that doesn't have MetaMask installed?

**Comment by rawadrifai** [comment]
it's there.. just in the hidden menu.

**Comment by rawadrifai** [comment]
any updates by any chance?

**Comment by tmashuang** [comment]
There might be an issue with how Metamask runs after all other scripts are running. Are you able to access the web3 object by typing `web3` in the console?

**Comment by rawadrifai** [comment]
gives me this
`web3
Proxy {_requestManager: s, currentProvider: MetamaskInpageProvider, eth: r, db: e.exports, shh: a, …}
[[Handler]]
:
Object
get
:
ƒ get(_web3, key)
set
:
ƒ set(_web3, key, value)
__proto__
:
Object
[[Target]]
:
r
bzz
:
e.exports {_requestManager: s, blockNetworkRead: ƒ, syncEnabled: ƒ, swapEnabled: ƒ, download: ƒ, …}
currentProvider
:
MetamaskInpageProvider {mux: ObjectMultiplex, publicConfigStore: ObservableStore, rpcEngine: RpcEngine}
db
:
e.exports {_requestManager: s, putString: ƒ, getString: ƒ, putHex: ƒ, getHex: ƒ}
eth
:
r {_requestManager: s, getBalance: ƒ, getStorageAt: ƒ, getCode: ƒ, getBlock: ƒ, …}
net
:
e.exports {_requestManager: s, getListening: ƒ, getPeerCount: ƒ}
personal
:
e.exports {_requestManager: s, newAccount: ƒ, importRawKey: ƒ, unlockAccount: ƒ, ecRecover: ƒ, …}
providers
:
{HttpProvider: ƒ, IpcProvider: ƒ}
setProvider
:
ƒ ()
settings
:
e.exports {defaultBlock: "latest", defaultAccount: undefined}
shh
:
a {_requestManager: s, version: ƒ, info: ƒ, setMaxMessageSize: ƒ, setMinPoW: ƒ, …}
version
:
{api: "0.20.2", getNode: ƒ, getNetwork: ƒ, …}
_extend
:
ƒ (e)
_requestManager
:
s {provider: MetamaskInpageProvider, polls: {…}, timeout: null}
__proto__
:
Object
[[IsRevoked]]
:
false`

**Comment by rawadrifai** [comment]
is metamask supposed to output something in console once it injects web3?

**Comment by tmashuang** [comment]
So this is the web3 object that is injected that is supposedly missing. 

> Also, how are you handling the window load for loading completion to avoid race conditions with web3 injection timing?

**Comment by rawadrifai** [comment]
This is my code for the react frontend. App.js is the main component and I'm calling initWeb3 from componentDidMount(). The condition `if (typeof web3 !== 'undefined')` is never satisfied. So it always creates a new web3 object and bypasses metamask.

```
componentDidMount() {
    this.initWeb3();
}

initWeb3() {
       if (typeof web3 !== 'undefined') {
         this.web3Provider = web3.currentProvider;
         web3 = new Web3(web3.currentProvider);
         console.log("existing web3: provider " + typeof web3);
      } else {

          this.web3Provider = new Web3.providers.HttpProvider('http://localhost:8545');
          web3 = new Web3(this.web3Provider);
          console.log("new web3");
        }

       this.displayAccountInfo();
       this.initiateContract();
  }
```

**Comment by rawadrifai** [comment]
![image](https://user-images.githubusercontent.com/24530625/32294419-61762066-bf03-11e7-959c-9c4e579a8331.png)

**Comment by tmashuang** [comment]
`window.web3`?

**Comment by rawadrifai** [comment]
![image](https://user-images.githubusercontent.com/24530625/32294528-aac63b20-bf03-11e7-8e83-52091dc4b327.png)

**Comment by rawadrifai** [comment]
btw this is how I'm declaring web3, according to: https://github.com/ethereum/web3.js/
```
var Web3 = require('web3');
var web3 = new Web3();
```

**Comment by rawadrifai** [comment]
so do you suspect this is something with metamask or on my end?

**Comment by tmashuang** [comment]
Regardless if Metamask is installed or not just but calling `web3` you should get the web3 object, not undefined. Try reinstalling web3 package. I suggest using web3@0.19.0 since 1.0.0 is in beta right now.

**Comment by danfinlay** [comment]
To clarify: your script is not detecting web3, but right after you can via console?

As a curiosity, can you detect it in a timeout? Is this a race condition or a context issue?

**Comment by rawadrifai** [comment]
![image](https://user-images.githubusercontent.com/24530625/32346272-0a11fea4-bfca-11e7-98ed-681da8d78e8e.png)

**Comment by rawadrifai** [comment]
Dan, I set a timeout like this, still web3 is undefined. I'm not sure what Thomas meant.. web3 should `not` be undefined even if there is no Metamask present? Is that a true statement?

```
componentDidMount() {

    var millisecondsToWait = 1000;
    setTimeout(this.initWeb3.bind(this), millisecondsToWait);

   // this.initWeb3();
  }
```

**Comment by rawadrifai** [comment]
Can you please confirm these simple steps would inject web3 object? I'm getting paranoid that I did something fundamentally off:

1- Run test rpc `testrpc`
2- Install metamask in chrome
3- log into metamask
4- connect to private network from metamask

**Comment by danfinlay** [comment]
That sounds fine to me. Do you have a github repo I could try reproducing on?

**Comment by rawadrifai** [comment]
I do: https://github.com/rawadrifai/ethereum
navigate to <repo-location>/ChainList
run the following:
```
npm install
./starttestrpc.sh
npm run migrate
npm start
```
You might need these global npm installs:
ethereumjs-testrpc@4.1.3
truffle@3.4.11

good luck.

**Comment by rawadrifai** [comment]
Also 
> Is metamask supposed to output "Metamask injected web3" in the chrome console?
as in any chrome tab that's open.

**Comment by rawadrifai** [comment]
Solved this. ugghh.
Must declare web3 like this: `var web3 = window.web3`
I had it `var web3 = Web3()` (as suggested by Web3). Funnies.

**Comment by superkarolis** [comment]
I encountered the same issue, so far I have only seen this problem with React projects.

**Comment by thanikc** [comment]
I actually get this issue in this simple example https://citywebconsultants.co.uk/blog/blockchain/introducing-ethereum-development-part-1-metamask-and-web3

**Comment by codemeit** [comment]
Make sure you have <!DOCTYPE html>

**Comment by mawenpeng** [comment]
> Make sure you have `<!DOCTYPE html>`

This really helps.

**Comment by saadibrahimiv** [comment]
![ss](https://user-images.githubusercontent.com/38457173/83855699-e4acfe00-a731-11ea-8665-7dab3e8fb0bf.png)
I am having the same issue here. 
`if (typeof web3 !== 'undefined') {
    App.web3Provider = web3.currentProvider;
  }`
this evaluates to false and web3 is undefined and it bypasses the metamask and it goes to the rinkeby provider. I can not resolve it with `window.web3`.

**Comment by saadibrahimiv** [comment]
> ![ss](https://user-images.githubusercontent.com/38457173/83855699-e4acfe00-a731-11ea-8665-7dab3e8fb0bf.png)
> I am having the same issue here.
> `if (typeof web3 !== 'undefined') { App.web3Provider = web3.currentProvider; }`
> this evaluates to false and web3 is undefined and it bypasses the metamask and it goes to the rinkeby provider. I can not resolve it with `window.web3`.

solved. Apparently i was running my html on local file method. 
"Due to browser security restrictions, we can't communicate with dapps running on file://. Please use a local server for development."
Run the file in local server and allow the connection manually to the website from metamask settings and it will work.

**Comment by Hrithiksh28** [comment]
> Solved this. ugghh.
> Must declare web3 like this: `var web3 = window.web3`
> I had it `var web3 = Web3()` (as suggested by Web3). Funnies.

Could you give an updated code? I'm very new to web3 and I cannot figure out what to change.
