### ISSUE TITLE
[Bug]: For imported accounts, tokens are not immediately recognized until there is a network switch or the extension is reloaded

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25156]
### Describe the bug

For imported accounts, tokens are not immediately recognized until there is a network switch or the extension is reloaded.

### Expected behavior

Token assets detected and imported.

### Screenshots/Recordings

Video:
https://jam.dev/c/413213f8-3e3a-412a-acdb-f53607333649

### Steps to reproduce

1. Import account which has different tokens
2. Notice that tokens are not autodetected
3. Try switch a network or reload extension

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by desi** [comment]
This is working properly in 12.9.2.
