### ISSUE TITLE
[Bug]: Inconsistency in the behavior between native and non-native tokens during the process of switching tokens

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25159]
### Describe the bug

An inconsistency in the behavior between native and non-native tokens during the process of switching tokens. 
1. User sends a native token: when a user changes the destination token from native to non-native and then back to simple send, the destination value is retained
2. User sends non-native token:  if the same actions as above are performed with a non-native origin token, the token amount is not preserved upon switching back to a simple send

### Expected behavior

-

### Screenshots/Recordings

Native token:

https://github.com/MetaMask/metamask-extension/assets/104780023/fcd13d63-9a87-43b3-b60b-2587fc82cd39

Non-native token:

https://github.com/MetaMask/metamask-extension/assets/104780023/a5d0386f-a3b8-4b5e-84d6-ca767c3a7f2b

### Steps to reproduce

1. Start send+swap transaction
2. Select non-native token as an origin
3. Switch destination token to any other token and then back to initially selected token
4. Notice the destination value is 0

### Version

latest send+swap build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Aliba22** [comment]
Good

**Comment by sleepytanya** [comment]
Latest v12.0.0 build [https://github.com/MetaMask/metamask-extension/commit/eebc4d5b2284024eaeb190cddfa89990f593ca34]

Consistent behavior while selecting tokens for all ERC20 tokens.

BNB Chain:


https://github.com/MetaMask/metamask-extension/assets/104780023/77293a2c-6115-431c-b2f4-b72fa2e0397d

Mainnet:


https://github.com/MetaMask/metamask-extension/assets/104780023/e893ac1f-e6b0-46a6-b83b-e28b0a95c489
