### ISSUE TITLE
Password stops working intermittently

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2515]
Opening instead of https://github.com/MetaMask/faq/issues/81#issuecomment-340806406 so we actually track it.

@metamaskwhyyy writes:
> Every few days my password stops working. I have to keep restoring my wallet from my unlock key and then change password then it works again. I have had no coins stolen or moved so don't understand wtf is going on. Thanks

**Comment by danfinlay** [comment]
I'm a bit curious if any errors are visible in the background on the failed unlock attempts:
https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome

**Comment by metamaskwhyyy** [comment]
I have multiple error messages 

warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by metamaskwhyyy** [comment]
no just the multiple red warnings

**Comment by metamaskwhyyy** [comment]
they're all written in red though

**Comment by neuhaus** [comment]
Can confirm on Iridium 2017.10 browser with metamask 3.12.0 on Linux.

**Comment by vaspoz** [comment]
Same problem here.
Win10, Chrome Version 62.0.3202.94 (Official Build) (64-bit)
I believe that it happened after every switch off my laptop (haven't check it though)

The red (!) warning in the logs:
![2017-12-04_10-57-39](https://user-images.githubusercontent.com/4658186/33546684-f623e28c-d8e1-11e7-9328-2d84b8319e99.png)

**Comment by vaspoz** [comment]
Just checked both cases:
1. Turn off the laptop using Windows' Restart.
2. Turn off the laptop using long press on Power button.
In both cases password works.

**Comment by binjin123** [comment]
Hi, i am unable to login to my metamask acct using the extension app, but i was able to log into the metamask support site. I want to get back into my acct, however it kept saying invalid password despite it being accurate.. i dont have the 12 key phrase since i skimmed through that part and i need my passkey to log into my acct using the extension app...please help

**Comment by davesque** [comment]
I'm getting the same behavior on macOS 10.13.3, Chrome 65.0.3325.181, and MetaMask 4.5.3. 
 Password stops working after some time and I have to restore from the mnemonic passphrase.  Next time this happens, I'll check for any Javascript errors in the console.

@binjin123 Have you tried rebooting your computer?  It seems like some people are reporting that this might fix things.

**Comment by danfinlay** [comment]
Interesting that you're having this @davesque, I would have guessed this was fixed in our move to the `storage.local` API.

Next time you get locked out, maybe open up your background console and try copying your vault storage. It contains your encrypted seed phrase, but could help us diagnose what went wrong (maybe corrupted somehow?)

https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by GeeeCoin** [comment]
Has there been any progress made on this issue? I have to restore from seed phrase every day, thanks!

**Comment by bdresser** [comment]
@GeeeCoin we think it's related to an issue with user storage that's been hard to track down. We've created a bug bounty for the issue at #3314 if you're interested in helping out.

next time this happens, could you pop open the chrome console and let us know if you see any errors?

**Comment by GeeeCoin** [comment]
@bdresser  I checked earlier today. Looked for Metamask output in the console and nothing was logged. It happens everyday though; I have to paste in my seed phrase. I don't mind doing it, but customers will when apps/dapps try to roll out MM implementations!

**Comment by bdresser** [comment]
thanks for checking @GeeeCoin. 

Agree, super not ideal. We'll let you know when we track it down.

**Comment by GeeeCoin** [comment]
I do have a uBlock JS blocker extension, but testing with it toggled on or off, I don't see a differential. Login seems to work for a while and then it doesn't. Also, I've noticed a higher priority vulnerability: seed phrases that are pasted into the restore text box don't clear the words if the extension is minimized. Once you click open the extension, you can access the word phrase after clicking restore again. Not sure this is known. I can open a new issue if you like.

**Comment by bdresser** [comment]
@GeeeCoin tracking the seed phrase issue in #4261

**Comment by whymarrh** [comment]
Is anyone still dealing with this daily? I'm closing this pending further updates but we can and should re-open and re-investigate if this is still a bug in the latest version of MetaMask.

**Comment by dylangolow** [comment]
I still have this issue in Chrome (daily), I've resorted to using Brave where I don't have this password issue.
