### ISSUE TITLE
Builds script incorrectly create an MV3 build for firefox

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#25183]
We saw that the firefox build created by job-publish-pre-release on the merge commit of v11.16.7 to master, an MV3 build was created. This should instead create an MV2 build.

**Comment by Gudahtt** [comment]
This seems to have been fixed by #25209

**Comment by DDDDDanica** [comment]
@Gudahtt it seems to be fixed indeed. 
will close this ticket
