### ISSUE TITLE
Update Gas API to use MetaMask Gas API

### ISSUE THREAD

**Issue by desi** [MetaMask/metamask-extension#25194]
### What is this about?

We recently made a change to use a new Infura Gas API but we would like to go back to using the previous MetaMask Gas API which some additional changes are made to the Infura one. We should use `gas.api.cx.metamask.io` rather than `gas.api.infura.io`

**Comment by dbrans** [comment]
More context: 

* We need to produce a hotfix to revert a recent gas api endpoint change in the Extension until a cache issue with the `infura.io` endpoint has been fixed. 

* The original PRs:
  - [MetaMask Core gas-fee-controller PR #4068](https://github.com/MetaMask/core/pull/4068)
  - [MetaMask Extension PR #23717](https://github.com/MetaMask/metamask-extension/pull/23717)

* Extension is currently on gas-fee-controller@15.1.2. There have been 114 commits to the gas-fee-controller between 14.0.1, (pre-[#4068](https://github.com/MetaMask/core/pull/4068)), and 15.1.2.

* The api team will let us know when they have a rough idea of how long it will take to fix the cache issue.

**Comment by desi** [comment]
All PR's are merged for this.
