### ISSUE TITLE
Metamask (cancel transaction)

### ISSUE THREAD

**Issue by effort89** [MetaMask/metamask-extension#2521]
Hello guys please does anyone know whats going on here....am using metamask ethereum wallet....today i decided to transfer my little coin from my wallet to exchange wallet but somehow i cancel the transaction but when i check at my balance it shows $0 or ETH 0...(empty) whats going on?
![iota](https://user-images.githubusercontent.com/16853726/32318033-91ad5892-bfbe-11e7-94d4-48d6c4822255.png)

**Comment by tmashuang** [comment]
The current Metamask extension does not support token sending. Here's a guide for managing tokens, [Managing Tokens](https://support.metamask.io/kb/article/4-managing-tokens)

**Comment by 7--** [comment]
Still an issue. No cancel order button.
