### ISSUE TITLE
Stop Desktop Builds

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#25232]
### What is this about?

The decision has been made to stop all desktop builds. This issue tracks the process of halting these builds and ensuring no further desktop builds are triggered.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Gudahtt** [comment]
This was done in #25147
