### ISSUE TITLE
flaky test: "Full-size View Setting @no-mmi opens the extension in popup view when opened from a dapp after enabling it in Advanced Settings"

### ISSUE THREAD

**Issue by DDDDDanica** [MetaMask/metamask-extension#25240]
**What is this about?**
Failure:

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/86970/workflows/6ccd9803-3bde-438b-91fc-8232f1c2ad8e/jobs/3177286
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/86823/workflows/ad2338b6-3249-4b28-b7eb-f0dd004b675e/jobs/3169580

**Error message**

![Image](https://github.com/MetaMask/metamask-extension/assets/12678455/c4ab8f83-ac27-4c88-9ff2-be79c655bc8d)

Screenshot

![Image](https://github.com/MetaMask/metamask-extension/assets/12678455/2f69700e-5ba2-4e80-931c-19929d020965)

**Comment by DDDDDanica** [comment]
Other flaky point found when running locally:
<img width="903" alt="截屏2024-06-12 06 15 30" src="https://github.com/MetaMask/metamask-extension/assets/12678455/6b93a95e-adcc-48c9-9efc-e181b32bfbe2">

**Comment by DDDDDanica** [comment]
Investigation: Test is somehow running in mv3 even with `yarn start:test:mv2` and 
`ENABLE_CONFIRMATION_REDESIGN=true ENABLE_MV3=false yarn test:e2e:single test/e2e/tests/settings/full-size-view-settings.spec.js --browser=firefox --leave-running=true --retryUntilFailure --retries=10`


<img width="1263" alt="截屏2024-06-12 06 39 17" src="https://github.com/MetaMask/metamask-extension/assets/12678455/d135f3c1-f1b2-4b23-bb2c-91e80c4c5ee8">

**Comment by hjetpoluru** [comment]
Thanks @DDDDDanica I could take it from here. There is already a ticket to track this work and closing it now. https://github.com/MetaMask/metamask-extension/issues/24642
