### ISSUE TITLE
[Bug]: Gas - Race condition where gas is not updated after switching assets and going to the last Confirmation screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25243]
### Describe the bug

Whenever we are sending an asset (ERC20, ERC721..) and we are on the Send Asset page, if we change the asset for another one (ie ETH) and proceed to the last Confirmation screen, the gasLimit is not updated no matter how long we wait.

- if we switch from an ERC to ETH, this will make the tx be sent with a higher gas than necessary
- if we switch from ETH to an ERC token, this will make the tx fail, due to low gas
- this makes the e2e test for this flow flaky https://github.com/MetaMask/metamask-extension/issues/25181

This can cause troubles to users which are under slow network conditions.
Note: the hex data value is indeed updated immediately when we change assets, which is expected.

### Expected behavior

If we don't want to block the Continue button before loading the new gas value, we should make sure that the gasLimit is set accordingly to the last transaction values (recipient, hex data and value) on the last confirmation screen.
At the moment this doesn't happen, as it seems that the gasLimit is only updated in the Send Assets screen (where these values can be changed).

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/cbef5440-078d-48e1-a3b6-57ab8503ed22

### Steps to reproduce

You can run the assets test to reproduce it (once the test it's fixed, you can go to an older commit)

https://github.com/MetaMask/metamask-extension/issues/25181

Alternatively, you can simulate this by adding some delays in the code or slowing down your network

### Version

11.16.8 but seems earlier too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by hjetpoluru** [comment]
@MetaMask/confirmations, Could someone prioritize this bug? It is currently causing the automation test to fail. cc @bschorchit for more visibility.

**Comment by jpuri** [comment]
Confirmation pages use the Gas Limit value passed to it in the transaction object. In this case I found that the bug is with send pages actually which is not updating the gas limit as asset of the transaction is changed.

**Comment by micaelae** [comment]
The gas fees are fetched in the background each time the asset changes between native/nft/erc20 (also when changing recipient or amount). The pending gas fees are set to the most recently returned value. If the initial gas fetch takes longer than the next one, there's a chance the older gas fee replaces the current one on fetch

**Comment by hjetpoluru** [comment]
The issue is fixed as part of the PR 27184 and hence closing this ticket
