### ISSUE TITLE
Race condition changes order in which transactions are displayed

### ISSUE THREAD

**Issue by pnarayanaswamy** [MetaMask/metamask-extension#25251]
The e2e tests for signature navigation is flaky because when you add a signTypedData_v3, send_ETH transaction and signTypedData_v4 in quick succession using the test dapp, then use the header to navigate between the three types the order in which the screens are displayed is signTypedData_v3, signTypedData_v4 and send_ETH transaction. Moreover the header also shows for both the send_ETH and signTypedData_v4 the page number as 2 of 3.

This happens only when running the e2e tests and manually it works fine. To reproduce run the test test/e2e/tests/confirmations/signatures/navigation.spec.ts by removing the driver.delay in the queueSignaturesAndTransactions() function

https://consensys.slack.com/archives/C070G0RCX0T/p1718188641805159

**Comment by seaona** [comment]
I think this issue can be closed, as we can completely mitigate the race condition by awaiting for the correct navigation values.

I've removed all the delays and added the conditions [in this PR](https://github.com/MetaMask/metamask-extension/pull/27606/files#r1789776474)
