### ISSUE TITLE
[UAT] Show Tokens with Zero Balances

### ISSUE THREAD

**Issue by sdtsui** [MetaMask/metamask-extension#2526]
Previously (in the release prior to what's live), we automatically added all tokens and filtered out zero balances.  Now, the user to adds tokens manually, but we still filter zero balances. 

We'd like the new release to add zero balances back, so the user can see all of their added tokens. This creates a more consistent user experience, and is related to #2513 .

**Comment by danfinlay** [comment]
I thought I did this here:
https://github.com/MetaMask/metamask-extension/pull/2474

**Comment by tmashuang** [comment]
Closing, this is been in master, but needs to be ironed out.
