### ISSUE TITLE
[Bug]: Nonce issues on Sepolia

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#25273]
### Describe the bug

With an account that was previously used on Sepolia, I am seeing new transaction attempts created with Nonce 0 when 59 is expected based on the account in test.

[Account](https://sepolia.etherscan.io/address/0x8D5daa0375b302d9A2C290612609D9A6E801B2e6) tested

This has been observed with this account in both Chrome 125.0.6422.142 and Firefox ~125.0.3~ 127.0 running Mac Sonoma 14.5.  Can be observed whether using send button or the test dapp and regardless of whether of custom nonce is enabled or not.  Has been observed both on a fresh install, as well as for a user that migrated from earlier version 11.16.10.

### Expected behavior

Expecting the next tx to have Nonce 59 on Sepolia, instead I see nonce 0 being used.

### Screenshots/Recordings

https://www.loom.com/share/09818c967c2f46be93c65f19057dec1a

### Steps to reproduce

1. Import SRP that has previous testnet transactions
2. Be on testnet
3. Attempt to send to another account
4. Note nonce submitted is 0 and transaction fails

In the video above, I also added the following steps to show it also happens without custom nonce enabled
1. Clear activity data
2. Disable custom nonce
5. attempt to send
6. on failure, click into activity view and note nonce 0

### Error messages or log output

```shell
Have uncaught Premature closes as well as 

sentry-install.js:1 {
  "code": -32603,
  "message": "Request is being rate limited.",
  "stack": "Error: Request is being rate limited.\n    at new c (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:758788)\n    at l (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:763444)\n    at Object.internal (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:762102)\n    at h (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:250677)\n    at u (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:250269)\n    at async chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:251340"
}
  at new c (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:758788)
  at l (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:763444)
  at Object.internal (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:762102)
  at h (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:250677)
  at u (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:250269)
  at async chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:251340
  at h._updateAndQueue (chrome-extension://pajiicbbailpdoigccomnoelkdlhmlcn/common-0.js:1:237948)
```

### Version

12.0.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Additional context

Observed in both Firefox and Chrome after migration test shows migrations 117, 118, 119 and 120 all completed, as well as on a fresh install without any migrations involved.

### Severity

Prevents testnet activity with Sepolia for users that have not enabled custom nonce and know to edit it, but is not observed on eth mainnet

**Comment by sleepytanya** [comment]
I see the same behavior, Chrome, MacOS, RC 12.0.0:



https://github.com/MetaMask/metamask-extension/assets/104780023/8d9ff316-2b0c-42ba-952a-368e7b9a2160

<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; track: click" role="link" tabindex="-1" title="chrome-extension://licedfdhofbjlalaklmidjbdfklijlnh/scripts/sentry-install.js:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">sentry-install.js:1</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">nonce too low: next nonce 22, tx nonce 0</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: monospace; --source-code-font-size: 11px; --source-code-font-family: monospace; width: 305.2px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | e.<computed> | @ | sentry-install.js:1
-- | -- | -- | --
  | (anonymous) | @ | sentry-install.js:1
  | error | @ | runtime-lavamoat.js:7134
  | r.logErrorWithMessage | @ | common-7.js:1
  | (anonymous) | @ | common-9.js:1
  | handleResponse | @ | ui-10.js:1
  | s.emit | @ | common-4.js:1
  | I | @ | common-6.js:1
  | S | @ | common-6.js:1
  | w.push | @ | common-6.js:1
  | _write | @ | common-0.js:1
  | S | @ | common-6.js:1
  | (anonymous) | @ | common-6.js:1
  | w.write | @ | common-6.js:1
  | f | @ | common-4.js:1
  | s.emit | @ | common-4.js:1
  | H | @ | common-4.js:1
  | F | @ | common-4.js:1
  | L.push | @ | common-4.js:1
  | _onMessage | @ | common-4.js:1
  | (anonymous) | @ | common-4.js:1

</span></div>

**Comment by plasmacorral** [comment]
Also noticing some irregularity when conducting a dapp transaction while another account is selected in the wallet.  Nonce being used belongs to actively selected account, which is different than the nonce of the dapp connected account.

Steps:
1. Have a wallet with >1 account where one account has transactions and another does not
2. Enable custom nonce in settings>advanced
3. Dapp connect account without transactions to MetaMask.github.io/test-dapp
4. Switch to account with a transaction history in extension, but do NOT connect to test dapp
5. Attempt to send eth with test dapp
6. Note that nonce of selected account appears instead of expected 0 for dapp connected account

Recording of v12.0.0 in Chrome 125.0.6422.142

**Comment by seaona** [comment]
I've encountered the same behaviour after upgrading from 11.16.10 to 12.0.0 Should we mark this as a release blocker? :thinking: 

https://github.com/MetaMask/metamask-extension/assets/54408225/c27bb7db-2d35-48ea-9c69-3bb130132fab

**Comment by sleepytanya** [comment]
@plasmacorral @seaona  
We may be encountering multiple issues that originate from a same underlying problem with the nonce tracker. I linked current bug report here https://github.com/MetaMask/metamask-extension/issues/25134 (this is a release blocker - in this bug every transaction is created with an empty nonce).
<img width="374" alt="Screenshot 2024-06-13 at 21 14 11" src="https://github.com/MetaMask/metamask-extension/assets/104780023/276ef8c1-8011-448a-9c4f-3d129ca26cf2">
But makes sense to make this one a release blocker as well!

**Comment by benjisclowder** [comment]
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**

We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:

**1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?**
4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

**Tagging eng. who added the fix:** @dbrans
