### ISSUE TITLE
[UAT] Add ENS Support for Payee

### ISSUE THREAD

**Issue by sdtsui** [MetaMask/metamask-extension#2528]
Placeholder ticket for ENS Support in `To:` field. Will fill this out after a sync w/ team.
![](https://puu.sh/ydfUs/b882a446b7.png)

**Comment by danfinlay** [comment]
Needs a little design, here is our previous version below:

![ens-input](https://user-images.githubusercontent.com/542863/37490012-adaef630-2856-11e8-86be-e5702f3b0c6f.gif)

Should have design for:

- [ ] Confirmed valid ens address (hover to view address & click to copy)
- [ ] Failed to resolve ENS address (hover to view problem)

Those are the previous versions, but other design is ok.

**Comment by danjm** [comment]
fixed on master
