### ISSUE TITLE
metamask won't load

### ISSUE THREAD

**Issue by randyh45** [MetaMask/metamask-extension#2529]
when I click on the Metamask Icon it goes into Metamask but doesn't open.  it has the spinning orange in the center but never loads.  I've used it many times on the same computer using chrome.  what could be the issue?  Thanks!

**Comment by tmashuang** [comment]
Some potential fixes would be to restart your browser, disable and reenable Metamask from the chrome://extensions list, and switch networks and switch back to the primary network. Any further issues can be directed to [https://support.metamask.io/](https://support.metamask.io/).
