### ISSUE TITLE
Lost private key

### ISSUE THREAD

**Issue by jamikka1111** [MetaMask/metamask-extension#2531]
Is there any way to access a lost wallet with only the public key and the password used to access it?

**Comment by raisty** [comment]
Nice information will be - How MetaMask handle private keys?

**Comment by tmashuang** [comment]
The primary way to recover a vault is with a Metamask provided 12-word seed phrase. Accounts can be imported with a private key. If the account is still loaded into Metamask there is a potential recovery process through the Metamask's local storage, instructions can be received through [https://support.metamask.io/](https://support.metamask.io/).

**Comment by TonyVernon20** [comment]
If you have been scammed by fake crypto investors or lost your crypto coin, reach out to cryptospamhacker@gmail. com for your coin recovery solution. They just helped me to reverse my stolen coins.
