### ISSUE TITLE
Re-introduce spinner for blockaid warnings on redesigned confirmations

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#25323]
### What is this about?

While we'll re-visit this to improve the loading UI in the future, we should re-introduce the existing spinner for when blockaid's warning is still loading in the meantime to prevent user confusion when the alert UI is suddenly triggered.

### Scenario

- Go to test dapp on v12.0.0
- Click on Malicious Permit

https://github.com/MetaMask/metamask-extension/assets/34968356/410502f2-ed5e-42bb-9144-7a554f096bed

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by jpuri** [comment]
@bschorchit , @SayaGT : currently spinner appears as in image below:

![Image](https://github.com/MetaMask/metamask-extension/assets/2182307/8fed40a8-ff33-4003-b2e8-9c6d92fc278c)

Can you plz suggest design for re-designed pages.

**Comment by SayaGT** [comment]
Hey @jpuri you can [find the design here](https://www.figma.com/design/yUczlH2HbHaHsYijiONKx0/Warnings%2C-Alerts-and-Flags?node-id=2161-31476&t=fDjvDjbLL23HHkNW-1) Let me know if you have any questions.
