### ISSUE TITLE
Learning Polygon Drawing [Not an Issue]

### ISSUE THREAD

**Issue by AnalystStins** [MetaMask/metamask-extension#2533]
I am new to development. I was very impressed with how you implemented the Fox animation. Could some one throw some light into how it is done. I am trying to learn. I cant seem to understand what exactly 'positions' is, and also what each chunk.faces co-ordinates do. I tried a lot of trial and error but was not able to figure it out.

I am sorry if this is the wrong place to ask for help. Please advise

**Comment by danfinlay** [comment]
That's a great question, @AnalystStins. That unique encoding format was whipped up by @mikolalysenko, presumably totally custom for this. That JSON is more efficient than string-style STL or even an SVG of the same fox's face!

That said, I'm not sure he ever documented it, so while I know it's basically just mesh data, I'd have to refer to the code closely myself to describe the format. Maybe Mikola would like to go into detail.

For convenience, the file he's referencing is this:
https://github.com/MetaMask/metamask-logo/blob/gh-pages/fox.json

**Comment by AnalystStins** [comment]
Thanks a lot @danfinlay . I tried the entire day in vain with trial and error to understand the relationship between 'positions' and 'chunk'. I hope   @mikolalysenko can throw some light :)

**Comment by danfinlay** [comment]
Oh, he left the script used to generate the file here:

https://github.com/MetaMask/metamask-logo/blob/gh-pages/convert.js

**Comment by AnalystStins** [comment]
Thanks for that. I still do not understand it from a Physics perspective. Also how is .MTL and .OBJ file generated?

**Comment by danfinlay** [comment]
The mtl and obj format is commonly exported from a variety of mesh software, especially Autodesk, I think.

**Comment by AnalystStins** [comment]
Thanks!
