### ISSUE TITLE
[Bug]: Smart Transactions UI is different for direct send and send+swap transactions

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25345]
### Describe the bug

The user interface for Smart Transactions differs between direct send transactions, direct send for native tokens and send+swap transactions. Specifically, for direct sends with native token, the Smart Transaction screen is displayed on the home screen, whereas for send+swap transactions, direct send for non-native tokens, this interface is presented exclusively within the MetaMask popup.
Sometimes for send+swap the popup doesn't appear (last recording) - I'm not sure how to reproduce this behavior.

### Expected behavior

-

### Screenshots/Recordings

ETH->ETH

https://github.com/MetaMask/metamask-extension/assets/104780023/d76621d8-7800-4f61-8dc6-9ee41f33bdc6

ETH->SUSHI

https://github.com/MetaMask/metamask-extension/assets/104780023/c0f89ed1-c82a-4710-95f6-02b472e787f1

BAT->BAT 

https://github.com/MetaMask/metamask-extension/assets/104780023/982a7368-87de-4bb9-9290-b900a24d7f29

Popup doesn't appear:

https://github.com/MetaMask/metamask-extension/assets/104780023/c39e47de-68b4-4a02-b807-1eb2fcfe9315

### Steps to reproduce

1. Start Send transaction
2. Select the same token as an origin and destination (direct send)
3. Start another Send transaction
4. Select different destination token (send+swap transaction)
5. Observe the difference in the UI

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by dan437** [comment]
I've removed the regression-RC-12.0.0 label, since we disabled smart transactions for this new Send&Swap feature here: https://github.com/MetaMask/metamask-extension/pull/25422

We will make smart transactions work with Send&Swap in one of the future releases.

**Comment by klejeune** [comment]
This feature is not currently supported. Closing the ticket.
