### ISSUE TITLE
MetaMask Web3 identification issue

### ISSUE THREAD

**Issue by raisty** [MetaMask/metamask-extension#2534]
Web3 version 0.20.1 with Angular2 give me:
`web3.service.ts:15 Uncaught TypeError: Cannot read property 'isMetaMask' of undefined`

when trying check it using:
`web3.currentProvider.isMetaMask`

**Comment by tmashuang** [comment]
Are you using your own `web3` instead of the Metamask injected one, what is your `web3.currentProvider`?

**Comment by raisty** [comment]
Trying connect to local and remote server also.
