### ISSUE TITLE
Uncaught out of memory

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#25343]
### Describe the bug

Was testing with a snap account in async mode with the test dapp in Firefox 127.0 on Mac Sonoma 14.5.  I have not pinned down reliable steps of what led up to the extension locking up, and unfortunately lost a key 6 minute chunk of recording.  In the recording I have available you can see extension is a bit sluggish.

### Expected behavior

Extension to handle dapp interations including rejected confirmations.

### Screenshots/Recordings

<img width="377" alt="Still" src="https://github.com/MetaMask/metamask-extension/assets/32695229/54703c20-b489-40d1-ae66-9f5f47fcd30b">

LONG and inclusive [Recording](https://www.loom.com/share/f2e0fe3e2f684abfb43126ac4f20ae5a?sid=b87c014e-34ba-4262-844c-6e50e764fc3e) of events leading up to out of memory

Statelogs:
[FirefoxOutOfMemory.json](https://github.com/user-attachments/files/15843959/FirefoxOutOfMemory.json)

### Steps to reproduce

Unclear at this time

Had 4 HD accounts, 1 Imported account, and 6 SSK created snap accounts
Was dapp connected with the imported account to: 
Pancakeswap.finance on Base
ENS on ethmainnet
Opensea on ethmainnet
Odos.xyz on Arbitrum
Test-dapp on Sepolia

Conducted multiple sends with the [test dapp](https://metamask.github.io/test-dapp/), as well as deployed ERC20 and signatures all with async approval on the SSK.  Also had some transactions that I rejected.

### Error messages or log output

```shell
Uncaught out of memory
Uncaught (in promise) out of memory
```

### Version

12.0.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Hardware wallet

Other (please elaborate in the "Additional Context" section)

### Additional context

Was migration testing with snap account created with [SSK 1.1.1](https://metamask.github.io/snap-simple-keyring/1.1.1/) and was recently testing with the test dapp when slowness was observed and extension froze.

**Comment by hesterbruikman** [comment]
@plasmacorral how confident are you that this is a regression on v12? Is there a way to confirm that it is?

**Comment by plasmacorral** [comment]
Until we sort out reproduction steps, not sure I can say one way or the other, unfortunately.
