### ISSUE TITLE
[Bug]: The functionality to wrap ETH to WETH on the Sepolia network is unavailable when a user is utilizing Sushi Swaps

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25359]
### Describe the bug

 The functionality to wrap ETH to WETH on the Sepolia network is unavailable when a user is utilizing Sushi Swaps. 

### Expected behavior

Sepolia wrap work for Sushi Swaps.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/f6c6d791-5988-41f5-97be-3fda90c632ba

### Steps to reproduce

1. Connect account to Sushi Swaps
2. Switch to Sepolia
3. Try to wrap ETH->WETH

### Error messages or log output

```shell
No errors in the console
```

### Version

11.16.11

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by desi** [comment]
Validated this is indeed no longer an issues on RC 12.10.0
