### ISSUE TITLE
[Bug]: When Smart transactions enabled, send+swap transactions sometimes displayed as "Send as" within the Activity tab without explicitly specifying the involved token

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25355]
### Describe the bug

When Smart transaction toggle is ON, send+swap transactions sometimes displayed as "Send as" within the Activity tab without explicitly specifying the involved token.

### Expected behavior

-

### Screenshots/Recordings

<img width="328" alt="Screenshot 2024-06-15 at 15 44 36" src="https://github.com/MetaMask/metamask-extension/assets/104780023/9063234c-cab0-45e3-acfb-58eac725b4f9">

https://github.com/MetaMask/metamask-extension/assets/104780023/fd6f0420-f964-47bb-aead-92172c5a0920

### Steps to reproduce

1. Enable Smart Transactions in the Settings->Advanced
2. Start send+swap transaction (select different destination token)

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by dan437** [comment]
I've removed the regression-RC-12.0.0 label, since we disabled smart transactions for this new Send&Swap feature here: https://github.com/MetaMask/metamask-extension/pull/25422

We will make smart transactions work with Send&Swap in one of the future releases.

**Comment by klejeune** [comment]
This feature is not currently supported. Closing the ticket.
