### ISSUE TITLE
UAT - Browser Back Button

### ISSUE THREAD

**Issue by chikeichan** [MetaMask/metamask-extension#2535]
User should be able to press the browser back button to go back to previous screen.

This would be a fairly large initiative to put in `react-router` to metamask. We can do it incrementally by flows, but user would have inconsistent back-button behavior before feature is 100% complete. I think the only **right** approach for the user is to implement it all the way with one release.

@sdtsui @kumavis @danfinlay @danjm @alextsg for comments

**Comment by danfinlay** [comment]
I agree, especially now that we're allowing people to use full browser windows.
