### ISSUE TITLE
[Bug]: blockaidDescriptionErrored with several tokens 

### ISSUE THREAD

**Issue by gades** [MetaMask/metamask-extension#25358]
### Describe the bug

In case working with following contacts 

0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05  (piratecash)
0x5F980533B994c93631A639dEdA7892fC49995839  (cosanta)
0xCbFB0D98151D03eF8bB71fA668F57Df5E3fb4673 (wdash)

metamask app is showing SECURITY_ALERT_RESPONSE_ERROR

It was happened when blockaid added flag and after remove this error was not removed. I'm thinking that mechanism blockaid doesn't work correctly  

### Expected behavior

No alert because not any flag bad contract 

### Screenshots/Recordings

<img width="1728" alt="Screenshot 2024-06-16 at 11 28 00" src="https://github.com/MetaMask/metamask-extension/assets/4200730/1b8e1294-f344-40bc-a8ac-0d7d21393b46">
<img width="1728" alt="Screenshot 2024-06-16 at 11 30 56" src="https://github.com/MetaMask/metamask-extension/assets/4200730/2c8687ba-aaa8-4521-a1be-e39bfb7bdf86">
<img width="1728" alt="Screenshot 2024-06-16 at 11 34 06" src="https://github.com/MetaMask/metamask-extension/assets/4200730/cca27bd0-6440-4ca1-9e7c-fa2cb38a86f9">

### Steps to reproduce

1. Add coin 0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05 to metamask (Binance smart chain)
2. open pancake swap and add 0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05 too
3. try to swap any asset to 0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05 
4.you will see this error

### Version

11.16.10

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Trezor

**Comment by bschorchit** [comment]
Closing as the issue seems no longer reproduceable:
<img width="368" alt="Screenshot 2024-09-05 at 19 22 13" src="https://github.com/user-attachments/assets/ef2dde8b-731c-419f-b6d6-e25a0b8d1666">
