### ISSUE TITLE
[Bug]: Smart Transactions enabled - send+swap transaction marked in a different way within the Activity tab

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25357]
### Describe the bug

Smart Transactions enabled - send+swap transaction marked in a different way within the Activity tab.

Probably related (?):  https://github.com/MetaMask/metamask-extension/issues/24929

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/bb993aee-65f5-4ef8-b9a7-777115bdb957

<img width="767" alt="Screenshot 2024-06-15 at 17 17 16" src="https://github.com/MetaMask/metamask-extension/assets/104780023/45c6ef98-90ee-435a-86c8-0917f312836a">

<img width="634" alt="Screenshot 2024-06-15 at 17 19 27" src="https://github.com/MetaMask/metamask-extension/assets/104780023/0fda0c4b-588b-4afe-80df-46f3260eb882">

https://github.com/MetaMask/metamask-extension/assets/104780023/b953440f-0b49-492c-9420-9f65a39b767e

<img width="640" alt="Screenshot 2024-06-15 at 17 24 56" src="https://github.com/MetaMask/metamask-extension/assets/104780023/bc52efc4-5829-45ec-83e0-e82b94303ef1">

### Steps to reproduce

1. Start send+swap transaction

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by dan437** [comment]
I've removed the `regression-RC-12.0.0` label, since we disabled smart transactions for this new Send&Swap feature here: https://github.com/MetaMask/metamask-extension/pull/25422

We will make smart transactions work with Send&Swap in one of the future releases.
