### ISSUE TITLE
[Bug]: When the Approval request is initiated from a dApp, users may encounter varying approval screens

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25360]
### Describe the bug

When the Approval request is initiated from a dApp, users may encounter varying approval screens. 
Note: one of the Approval screen shows '1 of 2' on the top right corner - is it expected?

### Expected behavior

-

### Screenshots/Recordings

<img width="361" alt="Screenshot 2024-06-16 at 20 55 44" src="https://github.com/MetaMask/metamask-extension/assets/104780023/3efc7711-7de7-4670-8afb-29ff07495d6f">

<img width="361" alt="Screenshot 2024-06-16 at 20 56 43" src="https://github.com/MetaMask/metamask-extension/assets/104780023/a341d11e-6b33-4773-befd-1b14c7ad2212">

https://github.com/MetaMask/metamask-extension/assets/104780023/e9539974-a92d-404e-9626-3abf8d941303

### Steps to reproduce

1. Connect to a dApp
2. Trigger Approval transaction

### Error messages or log output

```shell
No errors
```

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
@sleepytanya could you try and reproduce and checking the request type in the console. If it shows, perhaps checking with an engineer on the team if needed. Assumption is that the dapp is sending different request types `approve` vs `allowance` method.

**Comment by bschorchit** [comment]
Marking this as a release-blocker for v12.0.0 until we investigate more

**Comment by bschorchit** [comment]
> Note: one of the Approval screen shows '1 of 2' on the top right corner - is it expected?

This is expected as it's a 2-page confirmation.

**Comment by sleepytanya** [comment]
Can't reproduce on the latest build [https://github.com/MetaMask/metamask-extension/commit/eebc4d5b2284024eaeb190cddfa89990f593ca34]

**Comment by bschorchit** [comment]
We are downgrading severity on this issue as we're no longer able to reproduce this issue. We'll keep it open as we'll try reproducing it further on our side.

**Comment by desi** [comment]
Validated it is not reproducible in RC 12.10.0
