### ISSUE TITLE
[Bug]: When a popup is initiated from a dApp, the tooltip message for gas fees appears off-center

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25368]
### Describe the bug

1. When a popup is initiated from a dApp, the tooltip message for gas fees appears off-center, message is not fully visible.

### Expected behavior

-

### Screenshots/Recordings

<img width="360" alt="Screenshot 2024-06-17 at 14 46 51" src="https://github.com/MetaMask/metamask-extension/assets/104780023/f5f1f7e8-dd2e-4e8f-b8cf-7d5aa50164e2">

### Steps to reproduce

1. Connect to a dapp
2. Start a transaction
3. On the confirmation screen click on a pen icon next to the 'Estimated fee'
4. Hover over 'Priority fee' in the 'Network status' section

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
This is a regression on `develop` so I'll change the label @bschorchit 

RC 12.0.0. tooltip looks good:


https://github.com/MetaMask/metamask-extension/assets/104780023/318c6f60-243b-45fc-8ee4-8ca8aaa01b08

v11.16.12 tooltip also looks good:


https://github.com/MetaMask/metamask-extension/assets/104780023/d60160e9-6e5e-4262-a908-7518778fa3ad

`Develop` tooltip is broken:


https://github.com/MetaMask/metamask-extension/assets/104780023/70e21344-47dc-4feb-851f-7620a1b31bda

**Comment by desi** [comment]
Hovered over every tooltip in the transaction confirmation screen and all stayed within the bounds on RC 12.10.0. Valid to be closed.
