### ISSUE TITLE
[Bug]: The popup for the transactions initiated from a dapp are not shown if user has an unapproved transaction

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25361]
### Describe the bug

Currently, when a user has an unapproved transaction pending, popups for subsequent transactions initiated from a dApp are not displayed. 
If user clicks on a MM budge the notification for the test dapp transaction is shown. After rejecting the fist tx, user can click on MM badge again and see / reject / approve all unapproved dapp transactions.
In some cases after rejecting the first transaction MetaMask shows an error (second video).

Related issues:

https://github.com/MetaMask/metamask-extension/issues/25397

https://github.com/MetaMask/metamask-extension/issues/25393

Slack discussion links:

https://consensys.slack.com/archives/C03ETQA9EPK/p1695933147044299

https://consensys.slack.com/archives/C03ETQA9EPK/p1695932531166009

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/6089114a-e9d8-4209-9256-788310afc47c

https://github.com/MetaMask/metamask-extension/assets/104780023/7efbbf54-13d6-4519-bc37-26ff940faa77

<img width="576" alt="Screenshot 2024-06-17 at 14 02 43" src="https://github.com/MetaMask/metamask-extension/assets/104780023/904bd247-432b-4b71-9465-d3547e498e91">

### Steps to reproduce

1. Connect to dapp / test dapp 
2. Trigger any transaction, do not approve it
3. Switch to another dapp
4. Trigger transaction from a dapp or switch a network
5. Notice that popup doesn't appear while the number on the extension icon increased

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by forest-diggs-consensys** [comment]
@sleepytanya can you confirm that this is not the same as this? https://github.com/MetaMask/metamask-extension/issues/25397 

Specifically, if you check the MetaMask popup (in your initial video, it's just behind your main chrome window), do you see these subsequent transaction/approval requests?

**Comment by sleepytanya** [comment]
Yes, I think these probably are also the same bug:
 https://github.com/MetaMask/metamask-extension/issues/25393
https://github.com/MetaMask/metamask-extension/issues/25406
