### ISSUE TITLE
[Bug]: Gas - Sending a tx on Linea Sepolia throws error `Gas Price below configured minimum gas price`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25374]
### Describe the bug

Whenever I am trying to send ETH on Linea Sepolia network, I get the error `Gas Price below configured minimum gas price` and tx fails

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/961f0963-813f-4365-bb2b-3c4f18bbe04b

### Steps to reproduce

1. Select Linea Sepolia network
2. Start a tx
3. (set correct nonce if it's not correct, due to the issue )
4. Send tx
5. See gas error

### Version
11.16.11
12.0.0
maybe earlier versions too

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by gauthierpetetin** [comment]
Based on comment from Linea team on [Slack](https://consensys.slack.com/archives/C05NX55B747/p1718900767427679?thread_ts=1718892977.708479&cid=C05NX55B747), this shall be fixed now.
