### ISSUE TITLE
[Bug]: PPOM - If the Blockaid validation fails for a given tx, triggering the same transaction again, shows it as benign the second time

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25378]
### Describe the bug

Whenever there is an error with the Blockaid validation for a given transaction, we can see how if we trigger the same transaction again, the second time the transaction will be displayed as Benign instead of failed.

It seems that something is odd there, and this behaviour could be used as a bypass - if I make the first validation fail, the second one will be flagged as benign

### Expected behavior

Since I'm using tenderly network, I expect that the contract deployment validation always fails consistently (not only the first time), since tenderly RPC network does not follow the expected standards.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/a4845b60-108d-43e3-802e-50f25ef60337

### Steps to reproduce

1. Import a tenderly network, to make the validation fail
2. Go to the test dapp
3. Trigger  Create Token action for deploying a contract
4. See validation failing
5. Trigger again the same tx
6. See how it tx is now displayed as benign

### Version

11.16.2 production (maybe introduced earlier)

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
I could replicate this issue with tenderly network, if a benign transaction is submitted first time blockaid throws error but it does not throw error second time. This does not happen for malicious transactions - they are either reported as malicious or. they always throw error.

I do not think this is high priority as it is not happening in other networks for which blockaid is supported, additionally this is not an error at out end, blockaid needs to fix this.

cc @bschorchit

**Comment by bschorchit** [comment]
We discussed this in sync and lowered severity as this is only happening for tenderly
