### ISSUE TITLE
[Bug]: NFTs with long IDs can lead to disruptions on the send flow

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25370]
### Describe the bug

NFTs (ERC1155 in this case) with long IDs can lead to disruptions on the confirmation screen. 
Transaction detail seems to display wrong number with scientific notation under 'You send' amount.
Transaction hash: 0x280fa63d91b90a24d22d7d4fa32aa93437b586726e739a0dd32a9dd2ee58c08a

### Expected behavior

Smooth and coherent display regardless of the ID length.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/31ec4eb0-6ae6-419f-b7c4-907dc34b0cc1

<img width="434" alt="Screenshot 2024-06-17 at 19 21 59" src="https://github.com/MetaMask/metamask-extension/assets/104780023/94c1158e-47ee-4aa7-8635-76c751217300">

<img width="393" alt="Screenshot 2024-06-17 at 19 44 13" src="https://github.com/MetaMask/metamask-extension/assets/104780023/dfbadab1-2b57-49aa-9ff2-3e1228bf4136">

<img width="567" alt="Screenshot 2024-06-17 at 20 06 42" src="https://github.com/MetaMask/metamask-extension/assets/104780023/91e6669d-cb3e-46cb-b10e-2f187b4293ed">

### Steps to reproduce

1. 

### Error messages or log output

```shell
1. Send ERC1155 with the long ID
```

### Version

12.0.0.

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
Expected
- Wrap NFT ID on Send flow and Confirmation screen (`team-confirmations`)
- Token value of 1155 accurate, currently shows ETH value when RARI amount is expected (`team-assets`)

**Comment by bschorchit** [comment]
@hesterbruikman The send flow would actually fall under the bridge

**Comment by bschorchit** [comment]
I've moved the confirmations piece to a new issue: https://github.com/MetaMask/metamask-extension/issues/25446
Also, for visibility the confirmations issue is not a release regression - It's a pre-existing issue.

**Comment by vpintorico** [comment]
Hi @bschorchit, should we remove the release regression label?
