### ISSUE TITLE
Missing Feature: impossible to get rid of ERC20 Token added to an account

### ISSUE THREAD

**Issue by Remi-Tuy** [MetaMask/metamask-extension#2539]
It would be nice if we could "forget" the link between an account and a specific ERC20 contract.
The only way I found it to create a whole new account all together, but since you can't even "forget" accounts, the only permanent way is to uninstall the extension all together and reinstall it.

VERY FRUSTRATING when developing !

**Comment by tmashuang** [comment]
Consolidating to #2910
