### ISSUE TITLE
[Bug]: Unexpected popup behavior when interacting with dapps

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25393]
### Describe the bug

Popup functionality seems working not as expected. 

Scenarios:
1. Have unapproved transaction
2. Request to switch network - number on the MM icon will increase +1
3. Popup appears but you can't see the network request, only the unapproved transaction
4. If you access the popup manually it will show the unapproved transaction 
5. After unapproved transactions rejected, network request can be seen
6. If you go to the MM home page and reject unapproved tx from there the network request will be shown in full screen mode
  
1. Switch network, do not approve
2. Go to another dapp
3. Start transaction
4. MM icon number will increase +1
7. Popup appears but shows only network request
8. If you access the popup manually it will show the unapproved transaction request 
9. After unapproved transactions rejected, network request can be seen
10. If you go to the MM home page and reject unapproved tx from there the network request will be shown in full screen mode

Related issues:

https://github.com/MetaMask/metamask-extension/issues/25361

https://github.com/MetaMask/metamask-extension/issues/25397

Slack discussion links:

https://consensys.slack.com/archives/C03ETQA9EPK/p1695933147044299

https://consensys.slack.com/archives/C03ETQA9EPK/p1695932531166009

### Expected behavior

-

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/5bc1388b-f0ff-4843-81fa-386a21ae43a5

https://github.com/MetaMask/metamask-extension/assets/104780023/8759f31f-e53b-4be2-b200-a3c0bf2d3d1b

<img width="983" alt="Screenshot 2024-06-17 at 15 04 58" src="https://github.com/MetaMask/metamask-extension/assets/104780023/adbbc3ed-ada0-4372-8ba2-07d46b6cd78d">

### Steps to reproduce

In the description^^

### Version

11.16.11

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
@bschorchit it looks like this issue might describes [expected behavior](https://consensys.slack.com/archives/C029JG63136/p1718743006482709?thread_ts=1717752643.659019&cid=C029JG63136) around confirmations sequencing that is not obvious from the UI. Knowing the evolution of confirmation designs, can you take a look please and share if you see it likely this  issue can be addressed with a UI improvement? cc @sleepytanya

**Comment by bschorchit** [comment]
I've assigned this to confirmations @hesterbruikman
