### ISSUE TITLE
Upgrade core packages to release 159.0.0

### ISSUE THREAD

**Issue by mcmire** [MetaMask/metamask-extension#25401]
### What is this about?

Some time ago, the Wallet Framework team released version 159.0.0 of the `core` repo, which bumped all `core` packages to use a minimum version of Node 18. We need to ensure that among the packages that the extension are using, the versions of these packages match at least those that were included in release 159.0.0.

### Technical Details

We do not need to upgrade the extension to Node 18, as that is already the case.

### Acceptance Criteria

These packages are upgraded:

- [ ] `@metamask/address-book-controller` (4.0.2 -> 5.0.0)
- [ ] `@metamask/announcement-controller` (6.1.1 -> 7.0.0)
- [ ] `@metamask/assets-controller` (30.0.0 -> 32.0.0)
- [ ] `@metamask/base-controller` (5.0.2 -> 6.0.0)
- [ ] `@metamask/build-utils` (2.0.1 -> 3.0.0)
- [ ] `@metamask/controller-utils` (10.0.0 -> 11.0.0)
- [ ] `@metamask/ens-controller` (11.0.0 -> 12.0.0)
- [ ] `@metamask/eth-json-rpc-provider` (3.0.2 -> 4.0.0)
- [ ] `@metamask/gas-fee-controller` (16.0.0 -> 17.0.0)
- [ ] `@metamask/json-rpc-engine` (8.0.2 -> 9.0.0)
- [ ] `@metamask/json-rpc-middleware-stream` (7.0.2 -> 8.0.0)
- [ ] `@metamask/keyring-controller` (16.1.0 -> 17.0.0)
- [ ] `@metamask/logging-controller` (4.0.0 -> 5.0.0)
- [ ] `@metamask/message-manager` (9.0.0 -> 10.0.0)
- [ ] `@metamask/name-controller` (7.0.0 -> 8.0.0)
- [ ] `@metamask/notification-controller` (5.0.2 -> 6.0.0)
- [ ] `@metamask/phishing-controller` (9.0.4 -> 10.0.0)
- [ ] `@metamask/preferences-controller` (12.0.0 -> 13.0.0)
- [ ] `@metamask/queued-request-controller` (0.11.0 -> 0.12.0)
- [ ] `@metamask/rate-limit-controller` (5.0.2 -> 6.0.0)
- [ ] `@metamask/signature-controller` (17.0.0 -> 18.0.0)
- [ ] `@metamask/transaction-controller` (31.0.0 -> 32.0.0)
- [ ] `@metamask/user-operation-controller` (11.0.0 -> 12.0.0)

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by desi** [comment]
Check with Wallet API team about ethSign removal -- should maybe be combined with this.
