### ISSUE TITLE
[Bug]: Multichain - The MM popup keeps opening and closing in an infinite loop when I had a ledger tx unapproved, trigger another tx from another dapp and account and then approve the ledger one

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25412]
### Describe the bug

I had a ledger account connected to dapp 1 (linea sepolia) and a regular MM account connected to dapp 2 (mainnet).
Whenever I trigger a ledger tx and leave it unapproved, if then I trigger a tx from dapp 2, and Accept the first ledger tx (on MM), MM starts opening and closing the popup indefinelty.

This is similar to this [other issue](https://github.com/MetaMask/metamask-extension/issues/25408), but it has different repro steps, hence it's a separate ticket, though it might have the same fix.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/0234d3f9-3ac4-45c4-a614-27ffb6e96bfd

### Steps to reproduce

1. Import a ledger account
2. Connect ledger account to dapp 1 with linea sepolia
3. Connect a MM account to dapp 2 with mainnet
4. Trigger a tx from dapp 1 with ledger
5. Trigger a tx from dapp 2 with MM account
6. Confirm tx 1
7. See MM keeps opening and closing the popup indefinetly

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by hesterbruikman** [comment]
Possible causes
- Confirm that STX is enabled. STX does not work with Hardware wallet and could be a cause of confirmation getting into a loop.
     - Issue seems to start after 'Please confirm transaction on hardware wallet'
- Confirmation requested for a network while confirmation is queued for another network


Confirm with STX enabled and submit transaction with hardware wallet account connected. @benjisclowder This needs someone with a hardware wallet. Could you try and reproduce this to to help understand if this is an issue with STX or Multichain?

**Comment by benjisclowder** [comment]
Hi, @hesterbruikman and @seaona. Following the repro steps above, with Smart transactions toggled off, I got exactly the same result as in Mariona's video above. After toggling on the STX, the infinite pop-up is not showing anymore, but the Ledger transaction failed after signing it. Also, the network is automatically switching to Ethereum although I have "Select networks for each site" toggled on.

**Comment by benjisclowder** [comment]
https://github.com/MetaMask/metamask-extension/assets/120041701/2692f632-bf1b-4abb-a446-db8b297cd676

**Comment by jiexi** [comment]
Am able to repro on v12 eebc4d5b2284024eaeb190cddfa89990f593ca34

**Comment by jiexi** [comment]
Some clarifying points, the hardware wallet must be unlocked for the repro steps.

When I get to the infinite loop, I am able to close the notification window, and metamask shows a 1 on the badge count. At this point, I cannot get the pending confirmation to show, and any requests I add remain queued up and inaccessible. The only way to continue is to reject the transaction on the hardware wallet itself, after which the remaining confirmations start coming through as expected

**Comment by jiexi** [comment]
should be resolved by https://github.com/MetaMask/metamask-extension/pull/25475

**Comment by jiexi** [comment]
resolved in https://github.com/MetaMask/metamask-extension/pull/25098#issuecomment-2196458627
