### ISSUE TITLE
1.0.0-beta.24 Only 1 account being returned by getAccounts

### ISSUE THREAD

**Issue by dsinkey** [MetaMask/metamask-extension#2541]
I currently have three account in MetaMask on Ropsten, but whenever I call getAccounts it only returns the currently selected account.  If I change the account in MetaMask that's the account that will be returned.

export const getAccounts = () => async dispatch => {
	const res = await web3.eth.getAccounts();
	dispatch({ type: GET_ACCOUNTS, payload: res });
};

**Comment by tmashuang** [comment]
I believe this is intended to provide as little information about user's vaults as much as possible. It gives the users my security over their vaults. We could open up the discussion for why Dapps would need a list of accounts.
