### ISSUE TITLE
[Bug]: Chain icons are not displayed on confirmations

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#25447]
### Describe the bug

All chain icons other than Ethereum mainnet are not displayed on confirmation screen. For Arbitrum, Linea mainnet, Base, zkSync Era icons also not displayed for the currencies on the asset selection screen:

### Screenshots/Recordings

<img width="360" alt="Screenshot 2024-06-10 at 16 45 54" src="https://github.com/MetaMask/metamask-extension/assets/104780023/3b4f45cc-e73b-46e2-8162-41306ee41611">

<img width="412" alt="Screenshot 2024-06-10 at 16 46 51" src="https://github.com/MetaMask/metamask-extension/assets/104780023/44fe30b0-538d-4419-b7cc-94dd5f8dae62">

<img width="674" alt="Screenshot 2024-06-10 at 16 49 02" src="https://github.com/MetaMask/metamask-extension/assets/104780023/be29b119-affc-44e3-8fb9-1d9cfa786bfe">

 Two different icons for the mainnet:

<img width="674" alt="Screenshot 2024-06-10 at 16 49 02" src="https://github.com/MetaMask/metamask-extension/assets/104780023/2cb2155a-831b-4b50-a08f-525498e99d09">

### Steps to reproduce

Switch to any network other than mainnet, e.g. Base
Start send+swap / legacy / EIP 1559 etc. transaction
Notice that chain icon is not shown on the confirmation screen

### Version

11.16.12

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by ejwessel** [comment]
https://github.com/MetaMask/metamask-extension/pull/25518

**Comment by sleepytanya** [comment]
Present in the latest v12.0.0 https://github.com/MetaMask/metamask-extension/pull/25098#issuecomment-2251300111

<img width="359" alt="Screenshot 2024-07-25 at 22 50 52" src="https://github.com/user-attachments/assets/c2d9f0dc-3fa1-4c30-b5c1-968e5f2f2911">

**Comment by bschorchit** [comment]
Closing as no longer an issue
