### ISSUE TITLE
Where is keystore file saved?

### ISSUE THREAD

**Issue by rongierlach** [MetaMask/metamask-extension#2545]
Plugin data was "corrupted" and had to reinstall.
Neglected to write down keystore and created a new den 0_o
Is keystore encoded in local storage somewhere?
Is there a local directory for the extension I can dig around in?

**Comment by tmashuang** [comment]
Unfortunately, if you reinstalled, the previous store was deleted. When you created a new vault/den it populated the storage with the new one. The recovery process for vaults is the Metamask 12-word seed phrase.

**Comment by rongierlach** [comment]
RIP $ZRX https://etherscan.io/token/ZRX?a=0x6eE80A1181c252CD447d54CC85d5E2EeF761D6C7

**Comment by rongierlach** [comment]
Good news, recovered my old keystore in some backup I had and all is well with the world! 🦊

**Comment by tmashuang** [comment]
@rongierlach would you be willing to provide the solution for users that had the same problem?

**Comment by rongierlach** [comment]
My "Solution":
Backup your seed phrase and remember where you put it (critical).

Because MetaMask uses the BIP44 standard to generate seed phrases you can access your vault from pretty much any interface that accepts mnemonic phrases as a means of unlocking a wallet.

I used MyEtherWallet.

Basically I got lucky. Backup your seeds folks.
