### ISSUE TITLE
[Bug]: Announcements - NFT autodetection modal overlays Token autodetection modal

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25465]
### Describe the bug

The NFT autodetection modal is overlaying the Token autodetection modal, causing test flakiness and a wrong visual effect.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/54408225/73675db5-4de9-4a77-97a7-6a8887627117)

https://github.com/MetaMask/metamask-extension/assets/54408225/22850e1d-b013-4b44-8c14-d0782236aad1

### Steps to reproduce

1. Enable all announcements from Settings or with a fresh MM
2. See overlaying modals

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by alfeng6** [comment]
we've removed both modals so this should no longer be an issue.
