### ISSUE TITLE
[Extension] Lattice hardware device keeps disconnecting from MM Extension

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-extension#25467]
Steps to reproduce:- 

1. connect your Lattice to MetaMask and then close the browser window
2. Then try sending a tx and you should be redirected to the Lattice Connector module where you input the device ID and password
3. Requires to connect to Lattice device again

Actual:- The Lattice should stay connected to MM even after the browser is closed the way it was before, reconnecting shouldn't be required every time the browser is closed. 
Expected:- Ideally you would just connect once and that's it, unless you manually disconnect.

MM Extension version:- The first report was with 11.16.11, keeps happening with the newer version as well.

(First report:- MM has been randomly disconnecting from the Lattice. With the update to manifest v3, Lattice accounts are required to log in every time the browser is reopened, previously, it would stay logged in until they logout.)

**Comment by Akaryatrh** [comment]
I can not reproduce this issue. On my side Lattice login page indeed opens after a browser restart, but I'm getting connecting automatically, page is closing and transaction is sent.

- **Lattice info:**
  - Router: 0.49.0
  - Bootloader: 0.3.1
  - Firmware: 0.17.0
  - Hardware: V2
- **MM Version: 11.16.14**
- **Browser: tested on:** 
  - Chrome Version 126.0.6478.115 (arm64)
  - Chrome dev Version 128.0.6559.0 dev (arm64)


Here's a recording:
https://github.com/MetaMask/metamask-extension/assets/574787/641cdc09-7dd6-4222-9cf3-ee1f8eba3d26

**Comment by angelcheung22** [comment]
Lattice has confirmed this issue no longer exist.
