### ISSUE TITLE
[Bug]: Transaction reverted if Swap is initiated from token detail

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#25463]
### Describe the bug

If I try click on a token in the wallet and try to initiate a swap, there transaction is reverted with an error `missing revert data in call exception; Transaction reverted without a reason string`. See video below

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/6082863/d23f7a26-347c-44a1-80ec-ab55599d352e

### Steps to reproduce

1. Click on a token in the wallet
2. Click on Swap
3. Select any token
4. Get a quote and try to swap

Notice the error fetching quote and see the details in the console

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by davibroc** [comment]
@infiniteflower  cannot reproduce with the official RC build, only when I build the app locally. This likely has the same root cause as this https://github.com/MetaMask/metamask-extension/issues/25463 which is rate limiting. I have lowered the severity and remove the release blocker label

**Comment by dan437** [comment]
Since there is "Error fetching quotes", can the Swaps team have a look first?
![image](https://github.com/MetaMask/metamask-extension/assets/80175477/556b4555-7cd4-48cb-8d1b-67547ec83a2d)

**Comment by desi** [comment]
Can't reproduce on RC 12.10.0 with a dev build. Will leave as closed.
