### ISSUE TITLE
[Bug]: Multichain - transaction generated on the wrong network

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25528]
### Describe the bug

When a transaction is initiated on one network, subsequent transaction that was initially created on a different network may be executed on the incorrect network.

Blue badge shows '...' instead of  numbers'.

### Expected behavior

- 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/104780023/3e283869-a033-4787-a387-a95b0be32b9e

### Steps to reproduce

1. Connect to Ethereum mainnet on test dapp
2. Connect to the BNB on [Pancake](https://pancakeswap.finance/swap?chain=eth&outputCurrency=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&inputCurrency=ETH) 
3. Connect to Polygon on [Uniswap](https://app.uniswap.org/swap?chain=polygon)
4. Start a transaction on Uniswap, do not approve
5. Start a transaction on Pancake, do not approve
6. Start a transaction / signature from the test dapp 
7. See the test dapp transaction generated on Polygon

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
I think this is fixed by the commit just added to the v12 branch https://github.com/MetaMask/metamask-extension/pull/25098/commits/f5631fba1e83899f3e8d8a1bf2b1fc0de9fb87c6

**Comment by sleepytanya** [comment]
[Slack thread link](https://consensys.slack.com/archives/C06FXU326RL/p1719415715492249) with the details about the decision to remove the release-blocker label.
Thank you @danjm !
