### ISSUE TITLE
Add brand evolution fonts and enable use through styles

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-extension#25531]
### What is this about?

Add new brand evolution font files (TBC) to the MetaMask extension and make them available in the CSS by adding `@font-face` in `ui/css/utilities/fonts.scss`.

### Technical Details

- Upload the new font files to the appropriate directory within the project.
- Edit `ui/css/utilities/fonts.scss` to include the new font files using the `@font-face` CSS rule.
- Ensure that the new fonts are properly referenced and usable in the application’s CSS.

### Acceptance Criteria

- New font files are added to the project.
- `@font-face` declarations for the new fonts are included in `ui/css/utilities/fonts.scss`.
- The `.custom-font { font-family: 'Centura'; }` style can be used and works correctly.
- Verify that the fonts render correctly in different browsers and devices.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by brianacnguyen** [comment]
Duplicate ticket
