### ISSUE TITLE
Restoring vault does not clear account nicknames

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2554]
Currently restoring from a seed phrase deletes all vault data, but not account labels, which it probably should to reduce confusion.

**Comment by scsaba** [comment]
hi @danfinlay, I had a look into this and found that handling nicknames has been [moved](https://github.com/MetaMask/metamask-extension/pull/4034) from KeyringController to PreferencesController recently and at the same time, the behavior is also changed.

After restoring the vault only the label of the first account is restored, all the subsequent accounts have the default Account 2, 3, 4, etc names.

In my opinion this is what the user may expect. If you think the first account should have the default name (Account 1) also, then I can craft a PR quickly :)

**Comment by danfinlay** [comment]
I would agree that the first account nickname is a safe one to persist, so I'll close this issue for now.

Eventually we will definitely be replacing this kind of rudimentary nicknaming with much richer metadata, and probably allow it to be cloud-synced.
