### ISSUE TITLE
[Bug]: When useing EIP6963 Connect MetaMask I can't use widnow.etherem Json API to get Address in chrome but brave is available

### ISSUE THREAD

**Issue by fakeou** [MetaMask/metamask-extension#25542]
### Describe the bug

chrome
![image](https://github.com/MetaMask/metamask-extension/assets/7885490/fa3ea232-7cf6-40ac-b7d5-62e33a6af04c)

brave
<img width="687" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/7885490/d406465a-c5fc-48d1-bb5b-4c97668c6ab5">

### Expected behavior

Expected can use Json Api get addres in chrome

### Steps to reproduce

1.connect metamask use EIP6963 in chrome
2.use injected provider window.ethereum.request call "eth_accounts" at console
3.see address array in console

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by vandan** [comment]
@fakeou are you seeing this behavior consistently on your system?

**Comment by fakeou** [comment]
> @fakeou are you seeing this behavior consistently on your system?

yes, i got the same behavior at my PC windows, and Edge also available get address

## Google Chrome

https://github.com/MetaMask/metamask-extension/assets/7885490/033921e5-5a2d-4399-a604-eb88bcc4bd18

## Edge

https://github.com/MetaMask/metamask-extension/assets/7885490/9e1fccdd-d9c3-4c78-8477-cfa525e6aeb7


SourceCode here
``` html 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      let walletList = [];
      const getWalletList = (event) => {
        console.log(event);
        walletList.push(event.detail);
      };
      window.addEventListener("eip6963:announceProvider", getWalletList);
      window.dispatchEvent(new Event("eip6963:requestProvider"));

      const openWallet = async (e, rdns) => {
        e.style.color = "blue";
        const walletItem = walletList.find((item) => item.info.rdns === rdns);
        walletItem.provider.request({
          method: "eth_requestAccounts",
        });
      };
    </script>
    <div onclick="openWallet(this, 'com.okex.wallet')">Okx wallet</div>
    <div onclick="openWallet(this,'io.metamask')">matemask</div>
  </body>
</html>
```

**Comment by fakeou** [comment]
by the way

this is the version of my metamask plugin at windows

Edge:
![image](https://github.com/MetaMask/metamask-extension/assets/7885490/248249a6-fde5-40d3-83d1-0f50152f13e1)


chrome
![image](https://github.com/MetaMask/metamask-extension/assets/7885490/e3ef77df-97bf-4c8a-81a3-fd6176fe6c32)

**Comment by jiexi** [comment]
To confirm, in your screen recording after you click the MetaMask text in your webpage, you then also select at least one account and click confirm in the MetaMask confirmation?

**Comment by jiexi** [comment]
Sorry, just noticed that you are using the globally injected provider `window.ethereum` to make the `eth_accounts` request after using the MetaMask EIP-6963 provider that you made a `eth_requestAccounts` request with.

`window.ethereum` is not guaranteed to point to MetaMask went multiple wallet extensions are installed and enabled in your browser. Please call `eth_accounts` using the MetaMask provider as announced via EIP-6963 events
