### ISSUE TITLE
[Signature Redesign]: add non-critical alert for account mismatch MMI to support EOA accounts

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#25573]
### What is this about?

We currently have a warning for signature account mismatch when using MMI. It is using the old design. We would like to update the UI to use a Blue BannerAlert.

This account mismatch warning has been displayed for all signatures except for SIWE. This warning checks the MM selected address and the from/sender address. SIWE has a different account mismatch check that checks the MM selected address and the msgParams address. 

Deliverables:
- Update UI to use blue BannerAlert

Existing warning message on redesign signatures:
![CleanShot 2024-06-28 at 18 18 27@2x](https://github.com/MetaMask/metamask-extension/assets/20778143/20c8b2ba-d781-4f23-8b6f-84787f704457)

Existing warning message on old confirmation pages:
![Image](https://github.com/MetaMask/metamask-extension/assets/20778143/a888a6fd-b506-4926-81b5-c924e772f6c6)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by albertolive** [comment]
I created this PR to fix the issue: https://github.com/MetaMask/metamask-extension/pull/25626
