### ISSUE TITLE
[Bug]: Internal JSON-RPC error on balance sweep (Optimism) - `Can only call updateEditableParams on an unapproved transaction`

### ISSUE THREAD

**Issue by alecov** [MetaMask/metamask-extension#25577]
### Describe the bug

Sweeping ETH on Optimism to another address yields "Internal JSON-RPC error". No further information given. The attached console log is what happens right after clicking "Confirm".

### Expected behavior

The transaction goes and the whole balance is transferred with no dust left.

### Steps to reproduce

1. Create a new transaction by clicking "Send";
2. Select ETH;
3. Click "Max";
4. Click "Confirm";
5. Internal JSON-RPC error.

### Error messages or log output

```shell
sentry-install.js:1 TransactionsController: Can only call updateEditableParams on an unapproved transaction.
sentry-install.js:1 Internal JSON-RPC error.
```

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by hjetpoluru** [comment]
We tested the issue and its not reproducible and attached video for reference 
cc @adrigug 
https://github.com/user-attachments/assets/7940a3cb-980f-4fcd-b0ff-4a10745a67c1
