### ISSUE TITLE
[Bug]: send page modal styling broken

### ISSUE THREAD

**Issue by BZahory** [MetaMask/metamask-extension#25575]
### Describe the bug

At least three regressions have occurred to the `AssetPickerModal` component:

- The symbols no longer show for each list item (regressed by #24223)
- Blocked token symbols (e.g., BNB on Ethereum Mainnet) are no longer greyed out in the UI despite still being inert 
- Token names are not truncated

### Expected behavior

- Symbols should show on top of the token name (see: screenshots)
- Disabled item styling should be restored
- Longer token names should be truncated

### Current

<img width="482" alt="Screenshot 2024-06-27 at 5 41 23 PM" src="https://github.com/MetaMask/metamask-extension/assets/44588480/10a52b7a-c0ce-44e7-a4cd-76d1edd650e9">

### Expected

<img width="482" alt="Screenshot 2024-06-27 at 5 45 39 PM" src="https://github.com/MetaMask/metamask-extension/assets/44588480/22a42eb2-6571-4efa-8b68-6d216728f6a6">

### Steps to reproduce

1. Select Ethereum Mainnet
2. Go to Send page
3. Click on destination asset picker
4. Observe that symbols are not present and names are not truncated
5. Search for "BNB"
6. Observe that it is not styled as a disabled button

### Version

12.1.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

Tested on `develop`

**Comment by salimtb** [comment]
hey @BZahory ,
i have a small question regarding the comment below:
```
Blocked token symbols (e.g., BNB on Ethereum Mainnet) are no longer greyed out in the UI despite still being inert
```
i want to understand something , Binance coin is an [ERC20](https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52) deployed on Ethereum mainnet, why should we disable it ( and not allow users to select it ) ?

**Comment by BZahory** [comment]
> hey @BZahory , i have a small question regarding the comment below:
> 
> ```
> Blocked token symbols (e.g., BNB on Ethereum Mainnet) are no longer greyed out in the UI despite still being inert
> ```
> 
> i want to understand something , Binance coin is an [ERC20](https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52) deployed on Ethereum mainnet, why should we disable it ( and not allow users to select it ) ?

It’s blocked as a swaps token. It should not be disabled as a sending asset, only as a destination asset. The token is still blocked, it is just the design that’s still broken

**Comment by Jellyman447** [comment]
Let's connect and bind the company with the supply chain all in one package
