### ISSUE TITLE
[Bug]: When a user disconnects from Uniswap, the 'All permissions' connection status doesn't automatically update

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25595]
### Describe the bug

When a user disconnects from Uniswap, the 'All permissions' connection status doesn't automatically update. Same behavior on current production v11.16.14.

### Expected behavior

'All permissions' connection status updates accurately.

### Screenshots/Recordings

v12.0.0

https://github.com/MetaMask/metamask-extension/assets/104780023/2237561a-65f1-4e9a-a30f-b8c5971ef798

v11.16.14

https://github.com/MetaMask/metamask-extension/assets/104780023/8e8f9154-057c-453b-b4c4-43bd3dcfa4ff

### Steps to reproduce

1. Connect Metamask wallet to [Uniswap dapp](https://app.uniswap.org/swap)
2. Go to 'All permissions' to see account connected to Uniswap
3. Return to Uniswap dapp and disconnect account
4. Go back to MetaMask -> 'All permissions' -> see that the account is displayed as connected to Uniswap

### Version

11.16.14, 12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by darkwing** [comment]
Can no longer reproduce on `develop`
