### ISSUE TITLE
[Bug]: Metamask 11.16.14 not working with Chrome 126.0.6478.127 (MacOS 11.7.0)

### ISSUE THREAD

**Issue by turtlenice** [MetaMask/metamask-extension#25599]
### Describe the bug

Metamask 11.16.14 not working with Chrome 126.0.6478.127 (MacOS 11.7.0) on a Late 2013 Macbook Pro (2.6GHz Intel i5). Extension was working fine but then updated and now has spinning wheel forever when trying to open.

### Expected behavior

Expect login screen

### Screenshots/Recordings

![mm](https://github.com/MetaMask/metamask-extension/assets/169300765/d9431761-7ddb-4130-baf9-b0b2023ba751)

### Steps to reproduce

Use Chrome 126.0.6478.127 on MacOS11 and download latest version of metamask. This laptop (late 2013) is unable to update past this.

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Completely locked out, cannot use metamask or access seed phrase or anything

**Comment by MarcusWentz** [comment]
I had this issue on Firefox as well.

**Comment by coj337** [comment]
+1 for Firefox on Windows, can't get into the wallet at all. Extension is up to the latest possible release (v11.16.10) without trying to manually install.

**Comment by gauthierpetetin** [comment]
Closing as duplicate: https://github.com/MetaMask/metamask-extension/issues/22533
