### ISSUE TITLE
I can not confirm transaction in Ledger

### ISSUE THREAD

**Issue by Malikrehman00107** [MetaMask/metamask-extension#25623]
### Describe the bug

I am trying to send funds from Metamask with ledger , the ledger is connected and ETH app is open with status "Application is ready"

When i confirm the transaction then it shows that verify on hardware wallet and nothing show on ledger and disconnect.

Please help.

Thank

### Expected behavior

After i confirm and click on  send it should show the transaction on ledger screen to verify but end up in failed.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/111962911/adce73c2-c6dd-4dad-aab8-b1763071ecbb

### Steps to reproduce

please check the attached video

### Error messages or log output

```shell
Failed Transaction 

Log : Transaction created with a value of 0 BNB at 04:28 on 7/2/2024.
```

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Ledger

### Additional context

N/A

### Severity

Critical!

**Comment by vivek-consensys** [comment]
@Malikrehman00107 can you confirm/share the following please?

- Network
- Ledger Model
- Ledger firmware versions
- Browser version
- Console logs
- Is your Ledger device connected with the ETH app open?
- Have you enabled 'Blind signing' or 'Smart contract data' on your Ledger device?

Thanks.

**Comment by austin0125** [comment]
I had the same problem when calling smart contract using ledger. My configuration parameters are as follows:

- Ledger Model:  Nano S+
- Ledger firmware versions:  1.1.2
- Metamask Version:  11.16.14
- Browser:  Chrome Version 126.0.6478.127 (Official Build) (arm64)
- Operating system:  MacOS
- Network:  Binance SmartChain 
- Console logs: "Ledger: Unknown error while signing transaction"
- Is your Ledger device connected with the ETH app open?
Yes
- Have you enabled 'Blind signing' or 'Smart contract data' on your Ledger device?
Yes

**Comment by lechuckchuck** [comment]
Same issue here, also on ledger. Tried both Chrome and Firefox, none work, therefore it looks like a Metamask bug. Please fix asap!

**Comment by lechuckchuck** [comment]
Contract interactions are not possible, cannot sign. Sending ETH works though. I tried 2 different ledgers, browsers (chrome/ff) and OSes (mac/windows): same issue. It really looks like a Metamask issue.

**Comment by vivek-consensys** [comment]
Hey @austin0125, are you able to share a screen recording with the logs pls?

**Comment by austin0125** [comment]
Here is the log.
[metamask.log](https://github.com/user-attachments/files/16081581/metamask.log)

**Comment by vivek-consensys** [comment]
@lechuckchuck can you ensure the blind signing option is Enabled? After a firmware update on the Ledger device, it automatically sets to default, which is Disabled.

**Comment by lechuckchuck** [comment]
It is enabled. I tried on 2 devices Nano S Plus, updated with the latest firmware. Rabby works so I would exclude the device.

**Comment by kalabdalla** [comment]
Same issue. Can send/interact with ETH but approvals for ERC20 tokens don't make it to the Ledger.

**Comment by danjm** [comment]
thanks everyone, we are investigating this with high priority

**Comment by danjm** [comment]
@austin0125 Thanks for sharing the log. Would you be able to share the log from offscreen.html?

1. Go to chrome://extensions
2. Toggle on "Developer mode" in the top right corner
3. Go to chrome://extensions/?id=nkbihfbeogaeaoehlefnkodbefgpgknn
4. Click "offscreen.html"
5.Save the console output

(If others can do the same, that would be a help)

**Comment by zhang0125** [comment]
> @austin0125 Thanks for sharing the log. Would you be able to share the log from offscreen.html?
> 
> 1. Go to chrome://extensions
> 2. Toggle on "Developer mode" in the top right corner
> 3. Go to chrome://extensions/?id=nkbihfbeogaeaoehlefnkodbefgpgknn
> 4. Click "offscreen.html"
>    5.Save the console output
> 
> (If others can do the same, that would be a help)

<img width="789" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/24861757/8e8f77d0-732c-4091-8d65-7715eb12e150">
[offscreen.log](https://github.com/user-attachments/files/16083209/offscreen.log)

**Comment by austin0125** [comment]
> @austin0125 Thanks for sharing the log. Would you be able to share the log from offscreen.html?
> 
> 1. Go to chrome://extensions
> 2. Toggle on "Developer mode" in the top right corner
> 3. Go to chrome://extensions/?id=nkbihfbeogaeaoehlefnkodbefgpgknn
> 4. Click "offscreen.html"
>    5.Save the console output
> 
> (If others can do the same, that would be a help)

![Uploading image.png…]()
[Uploading offscreen.log…]()

**Comment by danjm** [comment]
thanks @austin0125, it looks like there was an error uploading those files, can you try again?

**Comment by kalabdalla** [comment]
[nkbihfbeogaeaoehlefnkodbefgpgknn-1720007772860.log](https://github.com/user-attachments/files/16083235/nkbihfbeogaeaoehlefnkodbefgpgknn-1720007772860.log)

**Comment by lechuckchuck** [comment]
Could it be similar to https://github.com/MetaMask/metamask-extension/issues/17964 ?

**Comment by danjm** [comment]
I think you are right @lechuckchuck, and the logs from @kalabdalla show an error that suggest that:

"eth-ledger-bridge-keyring/:1 Access to XMLHttpRequest at 'https://cdn.live.ledger.com/plugins/ethereum.json' from origin 'https://metamask.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

thanks to both of you

**Comment by kalabdalla** [comment]
> I think you are right @lechuckchuck, and the logs from @kalabdalla show an error that suggest that:
> 
> "eth-ledger-bridge-keyring/:1 Access to XMLHttpRequest at 'https://cdn.live.ledger.com/plugins/ethereum.json' from origin 'https://metamask.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
> 
> thanks to both of you

Is there a work around for us or do we need to wait for a new version release?

**Comment by danjm** [comment]
We are currently in contact with the Ledger team, trying to see if there is a server side fix possible (and so a new release would not be required). Meanwhile, we will continue to investigate possible work arounds.

**Comment by danjm** [comment]
At least one change has been made by Ledger on the server side that might resolve this problem. Please comment here if you see it working where it was previously breaking

**Comment by lechuckchuck** [comment]
Nope, still not working

**Comment by Malikrehman00107** [comment]
Same here, still not working!!

**Comment by kalabdalla** [comment]
Same, not working

**Comment by StayCoolDK** [comment]
Still not working here either

**Comment by danjm** [comment]
Thanks for your patience everyone. The Ledger team has another change to make, and we have much more confidence that this will resolve the problem. I will post a message here once that change is made.

**Comment by Malikrehman00107** [comment]
I just try with Rabby wallet and it’s working , so I don’t think it’s the
issue with the ledger. Is it?

**Comment by Malikrehman00107** [comment]
Same error with Metamask.

**Comment by danjm** [comment]
> I just try with Rabby wallet and it’s working , so I don’t think it’s the
> issue with the ledger. Is it?

I believe the ledger functionality on MetaMask and Rabby are different. Another user experiencing the issue had this to say:

"Metamask doesn't work well with tokens. I've tried using Rabby and it functions properly, but I assume that it works because Rabby treats every smart contract call as blind signing or something similar. When attempting to send, for example, USDT from Metamask, the Ledger displays the exact amount of the token, whereas Rabby just generates a blind signing transaction. This is not acceptable because I want to see the amount and recipient, not just the contract address.
Therefore, I suspect that there is an issue with smart contract recognition within the Ledger software. I even attempted to update the Ledger firmware to the latest version, but that didn't resolve the problem either."

Meanwhile, MetaMask has not shipped any changes to ledger related code in the last few weeks. We do need to make an improvement so that Ledger server issues don't block these transactions, but for the moment the immediate fix sits on the ledger server side.

**Comment by Malikrehman00107** [comment]
I always use like this so something surely went wrong that’s why we are
having this trouble.

I don’t think waiting for ledger going to make any difference , I insist
problem is with metamask.

Best

**Comment by lechuckchuck** [comment]
You insisting doesn't change the facts. This is not a Metamask issue, which can be easily proven by installing an older version which will reproduce the problem as well. Ledger needs to fix CORS on the server side.

**Comment by Malikrehman00107** [comment]
@lechuckchuck  so you contact their ledger's team already ?

I also mention some key people from the ledger's team to have their attention on the issue. apart you could reproduce the issue at your end if that is the case can you please share the "logs" with me to have a look? 



 @abonnaudet-ledger @aelmilligy-ledger @AEnguerrand @b0l0k  can you please have a look? 
 
 best regards

**Comment by danjm** [comment]
The server side fix from Ledger has been deployed. This should be working now. Please comment here if you continue to experience problems.

**Comment by StayCoolDK** [comment]
Can confirm it's working now :-)

**Comment by Malikrehman00107** [comment]
Yes, Working now! 

Thank you so much.
