### ISSUE TITLE
[Bug]: Extension crashes after several transactions

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#25649]
### Describe the bug

Extension crashes and becomes unresponsive after several transactions.
This bug can be reproduced with bnb chain and Sepolia test net using test dapp.

Slack message here: https://consensys.slack.com/archives/CTQAGKY5V/p1719961514193589

### Expected behavior

Extension to be responsive.

### Screenshots/Recordings

https://consensys.slack.com/archives/CTQAGKY5V/p1719981296076299?thread_ts=1719961514.193589&cid=CTQAGKY5V

### Steps to reproduce

1. Connect testdapp to Sepolia network. (toggle off smart transaction in settings)
2. Using send eth buttons on testdapp to trigger transactions.
3. Trigger multiple transactions
4. After 5-12 times, the mm extension crashes.

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
Not sure if it's related, but I've encountered this a couple of times in some flaky tests ([ex](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/90306/workflows/c0a2fbfa-4842-4a9c-a52b-c7e209303791/jobs/3347276/parallel-runs/7)), where the popup stays unresponsive. 
It seems that this happens after closing the popup, I get the `at new NodeError ...at ObjectMultiplex.onclose` in the background console.

![Screenshot from 2024-07-03 15-33-33](https://github.com/MetaMask/metamask-extension/assets/54408225/71362f8f-3f49-4011-97eb-a40c74091299)

**Comment by sleepytanya** [comment]
The crash happens on mainnet and (most likely) on every other network. Happens for transactions initiated from within the wallet, from dapps, including test dapp. 
I almost never see errors in the console but a couple of times I had the error (below), not sure if it's related to the bug:

<img width="761" alt="Screenshot 2024-07-02 at 15 24 04" src="https://github.com/MetaMask/metamask-extension/assets/104780023/8101062b-40bf-43df-8404-e1b0a811b76b">

**Comment by sleepytanya** [comment]
Unfortunately I see this bug in v12.1.0:


https://github.com/user-attachments/assets/d70a1cac-81c9-4041-8ec9-7d8176c7edb5

**Comment by gauthierpetetin** [comment]
Hi @sleepytanya , I see `release-RC-12.1.0` label was added. Was the intention to add `regression-RC-12.1.0`?

**Comment by Gudahtt** [comment]
From looking at the PR where this was fixed, it appears that this problem still exists in v12.1.0. We need to cherry-pick the fix into the v12.1.0 RC.

**Comment by bschorchit** [comment]
Was this the PR https://github.com/MetaMask/metamask-extension/pull/25686 that fixed it? It seems unrelated, but it's linked to this issue

**Comment by Gudahtt** [comment]
This is now included in the v12.1.0 RC (cherry-picked in this commit: https://github.com/MetaMask/metamask-extension/pull/25586/commits/8e7f71b8593dea94df6c6d9d8554712bcc5eb092)
