### ISSUE TITLE
[Bug]: Blockaid - Report false positive link from the Blockaid working is incorrect

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25656]
### Describe the bug

The report false positive link, now takes me to the https://support.metamask.io/ page instead of the pre-filled form.
This happens with the re-designed pages but not if the setting is disabled/with the old screens.

### Expected behavior

The link should take me to the prefilled false positive form

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/54408225/a93602d8-d972-4904-a7a0-0bf07dc2eacd

### Steps to reproduce

1. Make sure the redesign setting is enabled
2. Trigger a malicious signature from the test dapp
3. Click See details
4. Click report an issue
5. See now you land into the mm support page

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Umiiii** [comment]
dup #25622
