### ISSUE TITLE
Extension appears as a blank gray box

### ISSUE THREAD

**Issue by kdm5126** [MetaMask/metamask-extension#2566]
When i click on the extension nothing happens. I tried the tips for getting it to load such as disabling and enabling again as well as switching networks and it is just blank. I am not signed in to google but the metamask icon is there as an extension. I am using windows ten and is says its compatible.

**Comment by tmashuang** [comment]
Errors in the background and UI console can show application errors. Please follow this guide [How to get logs ans help metamask support and diagnose your issue](https://support.metamask.io/kb/article/29-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue) and send your findings to [https://support.metamask.io/new](https://support.metamask.io/new)
