### ISSUE TITLE
[Bug]: Estimations fail on Polygon

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25671]
### Describe the bug

Estimated changes fail on Polygon

### Expected behavior

Estimations work as expected

### Screenshots/Recordings

<img width="373" alt="Screenshot 2024-07-03 at 20 57 35" src="https://github.com/MetaMask/metamask-extension/assets/104780023/b774afa3-f507-4e58-80ef-221970e27f09">

### Steps to reproduce

1. Make sure `Security & Privacy`->  `Estimate balance changes` toggle is ON
2. Connect to Polygon on Uniswap or Sushiswap
3. Start a transaction
4. See estimation fails

### Version

11.16.14, 12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
I'm not able repro it on the latest 12.0.0 build
![Screenshot 2024-07-05 at 10 02 15](https://github.com/MetaMask/metamask-extension/assets/34968356/171d6557-8378-4a1c-9e7c-efef1b9230da)

**Comment by sleepytanya** [comment]
@bschorchit 
I can't reproduce as well on 11.16.14, 12.0.0 and `develop`.

**Comment by bschorchit** [comment]
Closing it for now. Let's re-open in case we encounter this again.
