### ISSUE TITLE
[Bug]: Accounts - All Permissions screens are displayed in full width when we are in the extension window view

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25678]
### Describe the bug

All Permissions screens are displayed in full width when we are in the extension window view.
Relates to https://github.com/MetaMask/metamask-extension/issues/25658

### Screenshots/Recordings

![Screenshot from 2024-07-04 12-53-05](https://github.com/MetaMask/metamask-extension/assets/54408225/2631b859-564e-4db6-8cbb-3d09f2459f10)

![Screenshot from 2024-07-04 12-53-21](https://github.com/MetaMask/metamask-extension/assets/54408225/0e1170a5-1517-4ab5-b609-46869b8478e9)

![Screenshot from 2024-07-04 12-53-28](https://github.com/MetaMask/metamask-extension/assets/54408225/42247730-e9a5-47b8-a53e-6e8a9bd47791)

### Steps to reproduce

1. Click Menu (3 dots)
2. Click All Permissions
3. See width from subsequent pages

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
Present in the v12.0.0 beta:

<img width="804" alt="Screenshot 2024-07-15 at 22 02 26" src="https://github.com/user-attachments/assets/fe2e0078-9646-4f32-bdaf-77f4edd3ccca">

**Comment by danjm** [comment]
@hesterbruikman why was the "won't fix" label added?

**Comment by sleepytanya** [comment]
Latest v12.0.0 build https://github.com/MetaMask/metamask-extension/pull/25098#issuecomment-2251300111

<img width="881" alt="Screenshot 2024-07-25 at 16 14 00" src="https://github.com/user-attachments/assets/54176073-653a-45bb-b9a5-85ad0c3b0d7e">

**Comment by hesterbruikman** [comment]
Issue resolved in [this PR](https://github.com/MetaMask/metamask-extension/pull/25870) 

Added `won't fix` initially as we're not prioritising the full screen view at the moment. Regardless, happy this was fixed!
