### ISSUE TITLE
MetaMask randomly requiring a seed phrase

### ISSUE THREAD

**Issue by cryptopioneer** [MetaMask/metamask-extension#2567]
My computer did not restart, and it does not appear that Chrome updated, but alas, Meta Mask is asking me to create a new den or restore from a seed phrase. 

When I created my initial address in Meta I saved only the pkey, but not the seed phrase. I have created 1 other very important address since then, actually quite recently, and had not yet saved the pkey. I had not expected this to happen as I've been using this den for many months without issue.

Is there any possible way for me to regain access to my den?

**Comment by tmashuang** [comment]
To recover whole vaults/dens, the associated seed phrase is needed. Individual accounts/addresses can still be imported through pkeys when a different seed phrase is loaded. The imported/loose account will not be associated will the seed phrase. Refer to [How to get logs and help Metamask support and diagnose your issue guide](https://support.metamask.io/kb/article/29-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue) and send your findings to [https://support.metamask.io/new](https://support.metamask.io/new)
