### ISSUE TITLE
User expects to have to edit the to-be-signed message

### ISSUE THREAD

**Issue by willnwhite** [MetaMask/metamask-extension#2568]
![screen shot 2017-11-10 at 16 59 38](https://user-images.githubusercontent.com/8081877/32669659-2e675fcc-c639-11e7-856f-02c8416dcd8d.png)
A user asked me "Do I have to write here?", I guess because the white box looks like an input (textarea). The message should not be edited.

**Comment by danfinlay** [comment]
We have a new facelift for this UI coming soon, and it solves this.
