### ISSUE TITLE
MetaMask not reading Token Balance

### ISSUE THREAD

**Issue by nikita-fuchs** [MetaMask/metamask-extension#2571]
*  Expected Behavior
After adding the Tokencontract's address, MetaMask would add the token and display my balance.

  *  Actual Behavior
The Token Name is displayed, also the decimals, but as it apparently can't read the user's balance, the token won't be added.

  *  Browser Used
Chrome@latest

  *  Operating System Used
Windows

* Contracts used
https://github.com/Leondra/PXLT/tree/master/contracts

The main contract is PXLToken, it inherits from StandardToken the function

```
 function balanceOf(address _owner)
    public constant
    returns (uint256 balance) {
        return balances[_owner];
    }
```

The contract's address is 0xc138c004F23E0246dA3AB1a2c945659036b95495, an address of a user already holding tokens: 0x2a7750ce195376166e4abdc916e64b48d6da19aa

As described in the gitter channel, fetching balance via http://www.proofsuite.com/tokenbalance/ works.

**Comment by danfinlay** [comment]
The `proofsuite.com/tokenbalance` site you linked doesn't seem to use the injected web3 provider (MetaMask), so I cannot debug why that site might not be able to retrieve the token balance with MetaMask.

I'll do some deeper digging on this soon.

**Comment by nikita-fuchs** [comment]
Sorr if I have been unclear. It's not about displaying token balance on the site. I meant the "Add Token" feature of metamask.

**Comment by danfinlay** [comment]
I see.

I've [tried reproducing this issue using the module we use internally](0xFDEa65C8e26263F6d9A1B5de9555D2931A33b825), and it seems to load without a problem, so this is very strange. Would you mind sending me a hundredth of one of these tokens to test with easily myself? (need to add some better UI mocking infrastructure in the future) `0xFDEa65C8e26263F6d9A1B5de9555D2931A33b825`

**Comment by danfinlay** [comment]
Closing until we have better reproduction steps.
