### ISSUE TITLE
[Bug]: ReferenceError: jQuery is not defined in web browser - lockdown-install.js:1:97687

### ISSUE THREAD

**Issue by slrslr** [MetaMask/metamask-extension#25710]
### Describe the bug

ReferenceError: jQuery is not defined in web browser

### Expected behavior

Metamask does not spam the console with error.

### Steps to reproduce

Opening new Firefox 115.12.0esr (64-bit) tab, F12 key to open dev. console, Console tab, open page http://cellyforum.com
Check errors in a dev console. I can see:
```

ReferenceError: jQuery is not defined
    <anonymous> http://myanonymousdomain.com/jscripts/general.js?ver=1603:754
lockdown-install.js:1:97687
    functors moz-extension://string-matching-metamask-extension/scripts/lockdown-install.js:1
    (Async: EventListener.handleEvent)
    functors moz-extension://string-matching-metamask-extension/scripts/lockdown-install.js:1
    functors moz-extension://string-matching-metamask-extension/scripts/lockdown-install.js:1
    lockdown moz-extension://string-matching-metamask-extension/scripts/lockdown-install.js:1
    <anonymous> moz-extension://string-matching-metamask-extension/scripts/lockdown-run.js:4
```

How I have figured out it is matching Metamask? searching that string at about:debugging#/runtime/this-firefox (expand Extensions)

### Version

11.16.13

### Build type

None

### Browser

Firefox

### Operating system

Linux

**Comment by katkopel** [comment]
@slrslr Thank you for reporting this issue! Our team will be looking int this soon.

**Comment by danjm** [comment]
@slrslr if you open the same website in an instance of the browser where MetaMask is not installed, does the error still occur?

**Comment by slrslr** [comment]
I think that when I have tested with a disabled MetaMask extension, that error have not appeared. Yet if you are unable to reproduce this, please close it.
