### ISSUE TITLE
events not working with eip 55 Mixed-case checksum encoded address

### ISSUE THREAD

**Issue by nkraetzschmar** [MetaMask/metamask-extension#2572]
When instantiating an existing contract using
```javascript
contract.at(callback, address);
```
(where address is encoded as an [eip 55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) Mixed-case checksum encoded address)
listening to events doesn't work:
```javascript
contractInstance.someEvent({}).watch(eventCallback);
```
No exception / warning is being raised, however the *eventCallback* function will not be called when the event occurs.
Getting old events works without any issues no matter the address encoding.

The obvious workaround is using
```javascript
contract.at(callback, address.toLowerCase());
```
but it would be nice if checksum addresses worked as well since they work without problem for anything else.

**Comment by tmashuang** [comment]
Consolidating to #2393
