### ISSUE TITLE
User should be able to put a lower gas price

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#2573]
Currently metamask restrict gasPrice to not be below a hard coded limit (0.1 gwei for now)

While this might be useful to avoid transaction to be "pending" forever it would be useful if the user could override such limit.

Related to https://github.com/MetaMask/metamask-extension/issues/2256

**Comment by wighawag** [comment]
Also if the dapp set a gasPrice lower than that limit, metamask should accept it assuming the dapp knows what it does.

**Comment by vincentserpoul** [comment]
I totally agree.
The simple use case of private chain with 0 gasPrice is blocked because of this.

**Comment by MiguelBel** [comment]
Agree.

Short term solution can be put lower gas price, `0` or `0.01`.
Long term solution can be let the user configure that value.

**Comment by bdresser** [comment]
this is now possible on the current version (4.7.3)
