### ISSUE TITLE
[Bug]: PPOM - extension crashes with a error when performing Malicious permit with integer address 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25733]
### Describe the bug

` Malicious permit with integer address` from `PPOM Malicious warning bypasses - Signatures ` section breaks MetaMask with an error

### Expected behavior

`Deceptive request` warning should be displayed.

### Screenshots/Recordings

<img width="620" alt="Screenshot 2024-07-10 at 00 40 48" src="https://github.com/MetaMask/metamask-extension/assets/104780023/bf530732-b688-4bb9-90a6-e3d14d30fa37">

### Steps to reproduce

1. Connect to [test dapp](https://metamask.github.io/test-dapp/)
2. Click ` Malicious permit with integer address` within the  `PPOM Malicious warning bypasses - Signatures ` section
3. See the error

### Version

12.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by pedronfigueiredo** [comment]
To be cherry-picked into RC 12.1.0.

**Comment by matthewwalsh0** [comment]
Blocked by #26287.

**Comment by bschorchit** [comment]
No longer treating this as release-blocker for v12.1, since it should be rare occurrence and mainly done by malicious actors. Fix will go out on v12.5.
