### ISSUE TITLE
[Bug]: Notifications - `Error fetching from Contentful after 3 retries: Error: Fetch failed with status: 404`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25748]
### Describe the bug

Whenever I enable notifications I see the following background error `Error fetching from Contentful after 3 retries: Error: Fetch failed with status: 404`and it takes several seconds for the loading spinner to disappear (not sure if it's related).

### Expected behavior

No error and good performance

### Screenshots/Recordings

![Screenshot from 2024-07-10 18-04-55](https://github.com/MetaMask/metamask-extension/assets/54408225/6c09d114-b94a-46dd-a7b3-b522b7430ddb)

https://github.com/MetaMask/metamask-extension/assets/54408225/6ec3c2c8-2266-4855-b3b8-c3bb75b34566

### Steps to reproduce

1. Onboard
2. Click Enable notifications
3. See error in the background/service worker console

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
Different error on 12.1.0, appears every time I turn notifications ON and OFF:



https://github.com/MetaMask/metamask-extension/assets/104780023/638f39b7-0faf-4384-af83-18c902363ac2



<img width="644" alt="Screenshot 2024-07-10 at 18 28 08" src="https://github.com/MetaMask/metamask-extension/assets/104780023/a8baef75-2cc7-4c75-b3e2-148ff7fa2705">

**Comment by Prithpal-Sooriya** [comment]
TY. Jira Ticket created [here](https://consensyssoftware.atlassian.net/browse/NOTIFY-848). Our team will investigate.

**Comment by Prithpal-Sooriya** [comment]
It may be that this API call to contentful is missing some environment variables on dev, but has been added to our CI pipeline/releases.

We will find a better way to handle this.

**Comment by Prithpal-Sooriya** [comment]
This was backported here: https://github.com/MetaMask/metamask-extension/pull/25863

**Comment by Prithpal-Sooriya** [comment]
This is fixed in v12.0.0
