### ISSUE TITLE
[Bug]: Notifications - •Failed to update OnChain triggers metamask-notifications.ts: 928 Error: Failed to update triggers for push notifications: Error: Failed to create a new registration token 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25750]
### Describe the bug

Every time when user adds a new account there is error in the console.

Error is present in the latest v12.0.0 branch, I'm seeing the error in the v12.1.0 build.

### Expected behavior

-

### Screenshots/Recordings

v12.0.0 branch

https://github.com/MetaMask/metamask-extension/assets/104780023/c1f0eeb4-4812-41f5-a35c-c84856548270

<img width="618" alt="Screenshot 2024-07-10 at 12 37 00" src="https://github.com/MetaMask/metamask-extension/assets/104780023/becbb44f-d7d1-4004-a9b1-b5fb0e4bd6a5">

No error in v12.1.0:

https://github.com/MetaMask/metamask-extension/assets/104780023/ec4b2eb1-0520-4a03-83f1-85cc97d3ae81

### Steps to reproduce

1. Enable Notifications
2. Add a new account
3. See the error

### Version

v12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Prithpal-Sooriya** [comment]
TY. Jira Ticket created [here](https://consensyssoftware.atlassian.net/browse/NOTIFY-846). Our team will investigate.

**Comment by Prithpal-Sooriya** [comment]
@matteoscurati can we make sure that push notifications do not block the full notifications flow. Instead push notifications should fail silently and we can resolve this at a later process.

**Comment by gauthierpetetin** [comment]
Is this a duplicate: https://github.com/MetaMask/metamask-extension/issues/25748

**Comment by sleepytanya** [comment]
@gauthierpetetin 
Looks like a different error for the different action. `Add a new account` vs `Turn notifications ON`. But I defer to the Notifications team to decide.

**Comment by Prithpal-Sooriya** [comment]
Lets keep these separate. Some potential fixes may resolve a series of these issues.

**Comment by Prithpal-Sooriya** [comment]
Tested and fixed in v12.

The slowness is still a thing when enabling/disabling notifications. We are working on improving this (it is mostly API call/backend improvements)
