### ISSUE TITLE
[NewUI] While on Send Screen, creating a new account generates a infinite spinner.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#2575]
Sometimes when I test new features I forget to add another account to send to. I attempt to add an account to while on the send screen and then it initiates an infinite loading spinner. 
A workaround for me would be to allow the recipient to also be the sender.
Error message when adding a new account while on send screen.
![error-new-account-while-on-send-screen](https://user-images.githubusercontent.com/13376180/32744341-0c098158-c864-11e7-8d45-e32a9516a073.png)

**Comment by alextsg** [comment]
Will triage to verify
