### ISSUE TITLE
[Bug]: A pop-up window displays a blank page that remains loaded.

### ISSUE THREAD

**Issue by linxin2020** [MetaMask/metamask-extension#25756]
### Describe the bug

After installing the extension, my chrome browser can now be used normally; But a few days later, it will become unusable. Click the plugin button, a blank window will pop up and remain loaded.

### Expected behavior

Pop up an input box and prompt to enter the unlock password.

### Screenshots/Recordings

![f78271c4a86659134c877b2182131ce](https://github.com/MetaMask/metamask-extension/assets/46699328/87db5ca1-e5c9-4256-b475-8dfdcb4a36ce)
![d3ff4b5a1c669f4ca75e28fcdd7944b](https://github.com/MetaMask/metamask-extension/assets/46699328/d2608eb6-fe37-48d3-be38-cfad7956e96e)
![ffc1e8d2913ed09d4c904644a730548](https://github.com/MetaMask/metamask-extension/assets/46699328/411856aa-7c40-4600-ad91-0335ec57e89d)

### Steps to reproduce

unwanted.

### Error messages or log output

```shell
The screenshot shows some error messages.
```

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by gauthierpetetin** [comment]
Hi @linxin2020 thanks for reporting this issue, we'll close it as we're already tracking it here: https://github.com/MetaMask/metamask-extension/issues/22533

cc @MetaMask/extension-platform for visibility
