### ISSUE TITLE
[Bug]: This extension often experiences crashes during use.

### ISSUE THREAD

**Issue by linxin2020** [MetaMask/metamask-extension#25757]
### Describe the bug

This wallet extension often crashes during use, with error codes such as STATUS_ACCESS_VIOLATION, as well as STATUS_STACK_BUFFER_OVERRUN.

### Expected behavior

Normal display.

### Screenshots/Recordings

![2e8816368e4612f0b6d7caaafc2c234](https://github.com/MetaMask/metamask-extension/assets/46699328/ab48e30b-3863-4d69-b7f7-ad70ebb854a8)

### Steps to reproduce

Appearing by chance without finding a pattern.

### Error messages or log output

```shell
Error: Extension context invalidated.
上下文
https://msu.io/
堆叠追踪
scripts/lockdown-install.js:1 (匿名函数)


"use strict";(()=>{const functors=[({imports:$h‍_imports,liveVar:$h‍_live,onceVar:$h‍_once,importMeta:$h‍____meta})=>function(){$h‍_imports([]);const universalThis=globalThis;
...
```

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by katkopel** [comment]
@linxin2020 Thank you for reporting! 

What version of Chrome are you experiencing this issue on? Does this issue only impact the platform listed in the error log?

**Comment by desi** [comment]
Next steps from refinement are to see if we can locate where this error is coming from to get clues on how to maybe reproduce.

**Comment by desi** [comment]
This seems to be a Chrome issue based on a few reddit threads:
https://www.reddit.com/r/chrome/comments/1afs1xa/keep_getting_status_access_violation_in_chrome/
https://www.reddit.com/r/sysadmin/comments/13dtum4/chrome_status_stack_buffer_overrun_error/
