### ISSUE TITLE
[Bug]: Token detection  doesn't work with custom network after bumping assets controller to v34.0.0

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#25762]
### Describe the bug

After adding Tenderly as a custom network I see token detection not working anymore please watch videos below to understand the issue. While this might seems as a minor issue, in the swap team we often use Tenderly for functionality testing and that allows us to save money. So making sure Tenderly works a custom network is important.

I was able to pinpoint the issue starting with this commit 
https://github.com/MetaMask/metamask-extension/commit/f353f0c316a18510a71ac3c4d45b765f78475028 

If I go back to this commit the problem doesn't happen
 https://github.com/MetaMask/metamask-extension/commit/58082f542b950f979ac362d7aa428f8181e80b9b

### Screenshots/Recordings

Before the changes

https://github.com/MetaMask/metamask-extension/assets/6082863/c07db8cf-1072-4a49-a5ee-18ea733161ba

After

https://github.com/MetaMask/metamask-extension/assets/6082863/353aecc8-e5f2-430b-a7e5-107192e0578f

### Steps to reproduce

1. Register with Metamask by importing an existing account with the follow seed phrase  
`ancient cloth onion decline gloom air scare addict action exhaust neck auto`
2. After the accout is setup add Tenderly as a custom newtork with the following settings
    name: 'Tenderly',
    url: 'https://rpc.tenderly.co/fork/cdbcd795-097d-4624-aa16-680374d89a43',
    chainID: '1',
    symbol: 'ETH',
 3. After switching to network notice that token detection doesn't work  

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
The v34 bump of assets controllers in https://github.com/MetaMask/metamask-extension/pull/25540 did break some token detection cases.  I reported this to Monte Lai and he fixed the repro that I had.   Mine wasn't tenderly specific tho, so could you try on latest develop?  It's on v36 now

**Comment by desi** [comment]
The UI has changed since this was created but the repro steps are still valid if you use the new edit functionality to add the rpc url. Additionally, that rpc url that was shared isn't working (it is an old issue). I tested with a different rpc url (not specific to Tenderly) and Token detection appears to be working. Marking this one as validated fixed unless @davibroc indicates otherwise.
