### ISSUE TITLE
Disable CI on the l10n_crowdin_action branch

### ISSUE THREAD

**Issue by vthomas13** [MetaMask/metamask-extension#25770]
### What is this about?

A suggestion from @HowardBraham, we want to avoid running CI on this `l10n_crowdin_action` branch. 
@Gudahtt suggests that we keep the lint step to catch issues with localized messages.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by HowardBraham** [comment]
I think it would be easiest to implement the "just run the lint step" using GitHub Actions.  You're going to encounter great complexities if you try to do it within CircleCI.

**Comment by HowardBraham** [comment]
I made some changes that I documented in this PR comment: https://github.com/MetaMask/metamask-extension/pull/25489#issuecomment-2224044285

I am not sure if this will already stop running CI on the `l10n_crowdin_action` branch, but it might.  There does appear to be a PR though (https://github.com/MetaMask/metamask-extension/pull/24889), so let's keep an eye on this.
