### ISSUE TITLE
[Bug]: Multi RPC functionality - errors in the console when network is switched: 'TypeError: Cannot read properties of undefined (reading 'chainId')' and 'Internal JSON-RPC error'

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25785]
### Describe the bug

When a user switches a network often there is an error in the console. Sometimes Internal JSON-RPC error appears but not very often.

### Expected behavior

-

### Screenshots/Recordings

TypeError:

https://github.com/MetaMask/metamask-extension/assets/104780023/587b02ed-459c-42b9-afec-d116bb87bb89

<img width="596" alt="Screenshot 2024-07-11 at 15 25 41" src="https://github.com/MetaMask/metamask-extension/assets/104780023/67982b7d-24f6-4418-a7db-96598f09a78a">

Internal JSON-RPC error:

https://github.com/MetaMask/metamask-extension/assets/104780023/f759d09a-e4e5-4a7d-ae8c-cae7452e721c

<img width="591" alt="Screenshot 2024-07-11 at 16 13 33" src="https://github.com/MetaMask/metamask-extension/assets/104780023/83ac5470-5be1-4e7e-a71c-93e380e6a833">

Error message randomly floating in the `Settings`:

<img width="825" alt="Screenshot 2024-07-13 at 17 48 54" src="https://github.com/user-attachments/assets/8f408fe9-ef43-46fe-893e-56a8a13889e3">

### Steps to reproduce

1. Add some networks from the Popular list
2. Switch between networks
3. See the error in the console

### Version

multi RPC build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by desi** [comment]
Tested in v12.9.1 and RC 12.10.0 and can't reproduce. This is valid to be closed.
