### ISSUE TITLE
Analyse Current Network Requests & Isolate ones we need to mock

### ISSUE THREAD

**Issue by Andepande** [MetaMask/metamask-extension#25791]
### What is this about?

Once a tool is identified, use that to monitor and log current network requests made by the app to identify services that need to be mocked.

### Acceptance Criteria

- Install and configure Flipper in the development environment.
- Document the services and endpoints currently used by the app.
- Save example requests and responses for each service to be mocked.

### Stakeholder review needed before the work gets merged

- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security

**Comment by gauthierpetetin** [comment]
Hi @Andepande , shall this ticket be closed?
