### ISSUE TITLE
[Bug]: Multi RPC - adding new network with the different RPC URL

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25792]
### Describe the bug

I'm not sure this is a bug, probably more an expected behavior questions.

1.  When adding an existing network but with a different RPC URL, the RPC URL for the existing network updates as though I edited the existing network directly. From a user's perspective, this process might not be entirely clear, especially since there are no notifications to highlight this change:

https://github.com/user-attachments/assets/21f1a1b1-d8a3-4ffc-b27b-fcc5f6547736

2. When attempting to add an existing network with a modified name, there is a message next to a network name  indicating that 'the network name may not correctly match this chain ID.' Despite this warning, the 'Approve' button remains clickable. After clicking 'Approve,' the network with the mismatched name replaces the existing network. Users don't receive any notification about this. Users can't see the new network name until they switch networks back and forth, after that the wrong name network appears on the list. Seems like it is impossible to edit the name of the wrong network.
3. Additionally, there are three errors logged in the console following this action.

https://github.com/user-attachments/assets/c1235f65-ca45-4486-831f-002c7f6d693a

<img width="747" alt="Screenshot 2024-07-11 at 18 17 01" src="https://github.com/user-attachments/assets/d3ec7133-b064-4b1c-ba6d-a7dbddc5df03">

<img width="649" alt="Screenshot 2024-07-11 at 18 36 51" src="https://github.com/user-attachments/assets/a0bd5fa0-543a-44ff-aae2-7bdf7b1b4687">

### Expected behavior

-

### Steps to reproduce

1. Add an existing network with the different RPC URL

1. Add a network with the modified name

### Version

Multi RPC build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
Closing as this was QAd on an early build and these issues have since been resolved
