### ISSUE TITLE
[Bug]:  Batch request error smartTransaction:showSmartTransactionStatusPage

### ISSUE THREAD

**Issue by Pasha8914** [MetaMask/metamask-extension#25796]
### Describe the bug

When sending a batch of transaction requests, an error occurs on the second transaction. However, the transaction is mined successfully.

### Expected behavior

When sending a batch of transaction requests, it should be processed without errors, and the transaction hash must be returned

### Screenshots/Recordings

https://github.com/user-attachments/assets/83ead1f5-5590-44a7-b021-eb0a3acb9140

### Steps to reproduce

1. Run [project](https://github.com/Pasha8914/wagmi-approve/pull/1)
2. Click _Send self-tx_
3. Sign first transaction
4. Sign second transaction as soon as the signature button is unlocked.

### Error messages or log output

```shell
Request of type 'smartTransaction:showSmartTransactionStatusPage' already pending for origin chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn. Please wait.
```

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

- The functionality of services that send a large number of consecutive transactions is blocked, making the services unusable.
- An error will appear in the interface, but the transaction will actually be sent, which may result in a loss of funds for the user.

**Comment by forest-diggs-consensys** [comment]
This is fixed in v12, though a transaction hash is only returned once a transaction is finalized. For context, this is to account for the case of dropped/automatically cancelled transactions (ie. if we detect a transaction would revert). This case is handled the same as if a user rejected the first transaction. Following that, the user will be able to confirm the 2nd queued transaction.

**Comment by Pasha8914** [comment]
> Это исправлено в v12, хотя хэш транзакции возвращается только после завершения транзакции. Для контекста это необходимо для учета случая сброшенных/автоматически отмененных транзакций (т. е. если мы обнаруживаем, что транзакция будет возвращена). Этот случай обрабатывается так же, как если бы пользователь отклонил первую транзакцию. После этого пользователь сможет подтвердить вторую поставленную в очередь транзакцию.

when to expect the release of version 12

**Comment by Pasha8914** [comment]
> This is fixed in v12, though a transaction hash is only returned once a transaction is finalized. For context, this is to account for the case of dropped/automatically cancelled transactions (ie. if we detect a transaction would revert). This case is handled the same as if a user rejected the first transaction. Following that, the user will be able to confirm the 2nd queued transaction.

when to expect the release of version 12

**Comment by Pasha8914** [comment]
> This is fixed in v12, though a transaction hash is only returned once a transaction is finalized. For context, this is to account for the case of dropped/automatically cancelled transactions (ie. if we detect a transaction would revert). This case is handled the same as if a user rejected the first transaction. Following that, the user will be able to confirm the 2nd queued transaction.


Это исправлено в v12, хотя хэш транзакции возвращается только после завершения транзакции. Для контекста это необходимо для учета случая сброшенных/автоматически отмененных транзакций (т. е. если мы обнаруживаем, что транзакция будет возвращена). Этот случай обрабатывается так же, как если бы пользователь отклонил первую транзакцию. После этого пользователь сможет подтвердить вторую поставленную в очередь транзакцию.

when to expect the release of version 12
