### ISSUE TITLE
[Bug]: Multi RPC - adding networks using dapps

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25794]
### Describe the bug

When attempting to add networks using dapps, there seems to be a discrepancy where the modal indicates successful network addition, yet the network doesn't appear in the 'Enabled' list. 
Additionally, in some instances, trying to add a network via chainlist.org can cause the extension to stop loading, there is an error in the console. I haven't seen it with other dapps yet. This issue can be resolved by reloading the extension.

### Expected behavior

-

### Screenshots/Recordings

Added networks are not visible within the Enabled networks list:

https://github.com/user-attachments/assets/8f337698-29e3-4fe1-8d32-6a0f63ccd5a4

https://github.com/user-attachments/assets/1c4e512e-4861-4763-af5b-bc7101e2c135

Extension stops loading:

https://github.com/user-attachments/assets/fd8e5c38-1ad8-43d4-b7ec-f8c6143f8167

<img width="689" alt="Screenshot 2024-07-11 at 23 30 46" src="https://github.com/user-attachments/assets/a51237a5-96a3-4b4f-836b-dda6643aa53e">

### Steps to reproduce

1. Connect MetaMask to a dapp
2. Try to add a network

### Version

Multi RPC build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
Closing as this was QAd on an early build and these issues have since been resolved
