### ISSUE TITLE
Cannot send ETH to any address

### ISSUE THREAD

**Issue by dalanmiller** [MetaMask/metamask-extension#2580]
* Brave 0.19.88
* Mac OS X 10.12.6

When trying to send ETH to an address after selecting the gas and Gwei and clicking submit, the extension will move to the next screen and just show the spinner for an indefinite period of time. No errors are visible in the console window as coming from Metamask. 

![screen shot 2017-11-13 at 23 37 36](https://user-images.githubusercontent.com/863286/32768187-ac7796c2-c8cb-11e7-971b-3e64eea26db2.png)

**Comment by tmashuang** [comment]
Can you access the developer console through chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html in brave and get any kind of errors?

**Comment by danfinlay** [comment]
Since this appears to be on Brave, the URL that @tmashuang won't work.

Could you right-click the popup area, and select `Inspect Element`, and look there for any errors in *that* console?

If there are no errors there, we'll probably want a look at your state logs, which you might want to keep private, so I'd recommend opening an issue on support.metamask.io

**Comment by tmashuang** [comment]
I was able to access the extension similarly to Chrome since I could not directly open the developer console from the icon. Am I the only one who can do this? 
![extension-url-in-brave](https://user-images.githubusercontent.com/13376180/32811249-8ac4f938-c953-11e7-866f-3b9b9f6495be.png)

**Comment by danfinlay** [comment]
Oh, that's funny. I just assumed it would have a different name.

**Comment by dalanmiller** [comment]
Came to investigate the issue but it now seems to be fixed now for whatever reason. Computer wasn't restarted but I did restart Brave which means I either got the extension out of the state it was in, or an update occurred that fixed my problem. Closing for now.
