### ISSUE TITLE
[Bug]: Multi RPC - unable to add RPC URL or custom network using Settings -> Networks

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25817]
### Describe the bug

'Add RPC URL' is not clickable in `Settings` -> `Networks`.

### Expected behavior

User can add custom network and new RPC URL using Settings.

### Screenshots/Recordings

<img width="826" alt="Screenshot 2024-07-13 at 17 23 21" src="https://github.com/user-attachments/assets/182e68bf-eaf4-4925-b685-143cd8c4d551">

### Steps to reproduce

1. Go to Settings -> Networks
2. Select a network or add new network manually
3. Click dropdown menu next to the `Default RPC URL`

### Version

Multi RPC build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
Closing as this was QAd on an early build and the network editing UI in settings has since been removed.
