### ISSUE TITLE
[Bug]: Metamask not loading in firefox

### ISSUE THREAD

**Issue by italy2010** [MetaMask/metamask-extension#25815]
### Describe the bug

![1](https://github.com/user-attachments/assets/0fa89d5f-7d24-4e1c-89ae-5221fb97c680)
Hello today i wanted open metamask it stop on loading
i tired some ways like this
https://support.metamask.io/managing-my-wallet/secret-recovery-phrase-and-private-keys/how-to-recover-your-secret-recovery-phrase/

but it give me this error
![gik](https://github.com/user-attachments/assets/c478d29c-7f5b-42fe-83a0-f35daa9951e2)

### Steps to reproduce

I click on metamask to open but it is stoped on loading

### Version

Version 11.16.15

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by italy2010** [comment]
any idea?

**Comment by gauthierpetetin** [comment]
Hi @italy2010  , thanks for reporting this issue!
We'll close it in favour of https://github.com/MetaMask/metamask-extension/issues/9196, which we're already investigating on at the moment, as our assumption is it has the same root cause.
