### ISSUE TITLE
[Bug]: Multi RPC - RPC URL and Block explorer URL are not displayed

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25819]
### Describe the bug

PRC URL is not displayed in `Settings` - > `Networks` for `Popular` and manually added networks.
Block explorer URL displayed only for the mainnet.

### Expected behavior

-

### Screenshots/Recordings

<img width="823" alt="Screenshot 2024-07-13 at 18 09 58" src="https://github.com/user-attachments/assets/1624b700-80b1-4b87-90c4-9612a998b33b">

### Steps to reproduce

1. Go to `Settings` - > `Networks`
2. Check if RPC and block explorer URLs are visible

### Version

Multi RPC build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
Closing as this was QAd on an early build and the network editing UI in settings has since been removed.
