### ISSUE TITLE
[Bug]: Multi RPC - when user adds new RPC URL through Settings the "Add RPC URL" modal stays open

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25818]
### Describe the bug

If user tries to add new RPC URL through the `Settings`,  the `Add RPC URL` modal stays open even another network is selected. The only way to close this modal is to close `Settings`.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/d4722ddb-544f-4f1c-9177-9cd878cc8947

### Steps to reproduce

1. Go to `Settings` -> `Networks`
2. Click Add `RPC URL`
3. Try to make it disappear

### Version

Multi RPC build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
Closing as this was QAd on an early build and the network editing UI in settings has since been removed.
