### ISSUE TITLE
[Bug]: Multi RPC - adding devnet (Tenderly) replaces Ethereum mainnet

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25820]
### Describe the bug

I added Tenderly net with the Test1 name to the MetaMask and it replaced the Ethereum mainnet.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/4f4ffc29-7a29-4628-bbe4-bbc319948399

### Steps to reproduce

1. Add mainnet Tenderly net to MM
2. Notice it replaces the Ethereum mainnet

### Version

Multi RPC build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
Closing as this was QAd on an early build and this issue has since been resolved
