### ISSUE TITLE
[Bug]: MetaMask displays error messages across various screens

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25838]
### Describe the bug

Occasionally, MetaMask users may notice error messages appearing across various screens, floating above the interface in a random manner. These errors primarily observed within the `Settings` section, though they have also made appearances on other screens. I'll make sure to update this ticket with more detailed information as it becomes available.

### Expected behavior

Errors should be displayed in a predictable sequence, either within the console or as predefined error messages, to ensure clarity and ease of troubleshooting for users.

### Screenshots/Recordings

<img width="780" alt="Screenshot 2024-07-15 at 14 51 43" src="https://github.com/user-attachments/assets/0b405eff-8e0b-465e-b102-65d7a48a7d96">

<img width="791" alt="Screenshot 2024-07-15 at 14 52 30" src="https://github.com/user-attachments/assets/f7b5a75f-b36c-40d1-a126-a00310467f8d">

<img width="750" alt="Screenshot 2024-07-15 at 14 52 03" src="https://github.com/user-attachments/assets/730a76ca-b98f-415d-9954-979fb7fbf23b">

### Steps to reproduce

1. Once you see any error, check if there is a error message within the `Settings` (or other screens)

### Version

11.6.0, 11.16.0, 12.0.0, 12.1.0, `develop`

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by Gudahtt** [comment]
The `displayWarning` function in `actions.ts` is responsible for this. This function is deprecated; replacing remaining usages will resolve this problem.

Though we'll have to find a more appropriate way to display each error on a case-by-case basis.

**Comment by gauthierpetetin** [comment]
We've reviewed this issue during refinement with @MetaMask/extension-platform . It seems the next step is clear as indicated by Gudahtt: remove occurrences of `displayWarning` function from the entire codebase. Changing the status to "ready for dev" to reflect that.

**Comment by gauthierpetetin** [comment]
Fixed by these 2 PRs:
- https://github.com/MetaMask/metamask-extension/pull/27990
- https://github.com/MetaMask/metamask-extension/pull/26999
