### ISSUE TITLE
Failed transactions don't call callbacks functions

### ISSUE THREAD

**Issue by MFranceschi6** [MetaMask/metamask-extension#2585]
If I test a Contract method that just throws
```
function testThrow(){
        throw;
}
```
and my test DApp function is the following
``` javascript
        function testThrow(){
            $.getJSON("Voting.json", function (data) {
                console.log(data.abi);
                var c = web3.eth.contract(data.abi).at("0x4e88059f8ced5639758a398218dc7fe8deec8514");
                console.log(c);
                c.testThrow.(function (err, res) {
                    console.log(err);
                    console.log(res);

                });
            });
        }
```
Calling the function opens the Metamask UI to ask for authorization. And if I reject the transaction I obtain an error in the err callback arguments:
![reject](https://user-images.githubusercontent.com/9447889/32841295-38cb79e6-ca1a-11e7-92f6-8ccaf46acc38.png)
 But if I submit the transaction the function doesn't receive anything and the callback is not even called the exception is just registered in the metamask UI
![submit](https://user-images.githubusercontent.com/9447889/32841888-ec3e63de-ca1b-11e7-9dbe-97f761ecba27.png)
If I change the code to call the function and not to send a transaction:
```javascript
       function testThrow(){
            $.getJSON("Voting.json", function (data) {
                console.log(data.abi);
                var c = web3.eth.contract(data.abi).at("0x4e88059f8ced5639758a398218dc7fe8deec8514");
                console.log(c);
                c.testThrow.call(function (err, res) {
                    console.log(err);
                    console.log(res);

                });
            });
        }
```
The callback function is invoked as expected
![call](https://user-images.githubusercontent.com/9447889/32841780-91280770-ca1b-11e7-8a4c-bb2a33a37c35.png)

Metamask version is 3.12.0
OS is windows 10
Using testrpc version v6.0.1

**Comment by danfinlay** [comment]
Hi, sorry for the slow reply. Is this issue still affecting you? We think we may have fixed this recently.

Also, a reproduction repository would be very helpful.
