### ISSUE TITLE
[Bug]: Translations for several languages are missing on the onboarding pages

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#25850]
### Describe the bug

Changing language from the dropdown menu during wallet creation does not work for several languages, including "Italiano" and "Polski."

### Expected behavior

Translations on onboarding pages are accurate and comprehensive for all languages.

### Screenshots/Recordings

![Screenshot 2024-07-16 at 17 09 16](https://github.com/user-attachments/assets/86cf1f5b-ea78-43be-9120-0dfdf3136040)
![Screenshot 2024-07-16 at 17 08 28](https://github.com/user-attachments/assets/236482e3-bde7-48d4-b4f8-bde80670d6a9)

### Steps to reproduce

1. Onboarding on MetaMask by creating a new wallet.
2. Select a language from the dropdown menu during onboarding, such as "Italiano"or "Polskie."
3. Verify the translations on the onboarding pages.

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Looks like a duplicate of https://github.com/MetaMask/metamask-extension/issues/25698

**Comment by chloeYue** [comment]
Close this one as it is a duplicate of https://github.com/MetaMask/metamask-extension/issues/25698
