### ISSUE TITLE
[Bug]: Multi RPC - Adding network with same chainId as existing one, makes that the selected one displays the exsiting one name, instead of the new one

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25864]
### Describe the bug

Adding a network with the same chain id as the one pre-existing in the wallet (ie Ethereum mainnet) makes that when I switch to that network I see the network name for the pre-existing one, instead of the one I have selected

### Screenshots/Recordings

https://github.com/user-attachments/assets/01735c28-0117-4822-b12a-dfe85adaa98a

### Steps to reproduce

1. Add a tenderly mainnet network
2. Select it
3. See how it continues to display Ethereum Mainnet on the selected network menu

### Version

develop - not 12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jiexi** [comment]
@seaona to clarify, does this occur when the pre-existing network is not a built-in network?

**Comment by vandan** [comment]
From a few quick tests on v12.1.0, I found that this issue is occurring for both built-in and added networks.
Ethereum Mainnnet -> adding Ethereum on Ankr failed to switch after the confirmation
Added OP on LlamaNodes then adding OP on Tenderly failed to switch after the confirmation

**Comment by jiexi** [comment]
https://github.com/user-attachments/assets/58b1790a-5eba-4af8-8861-e283712e433a

Unable to reproduce this issue on latest develop. Some Network form/add/switch behavior was recently updated though.

**Comment by jiexi** [comment]
I do see the issue still on `Version-v12.1.0`

**Comment by adonesky1** [comment]
It appears this issue is now resolved on the `Version-v12.1.0` branch: 

https://github.com/user-attachments/assets/f9ede97a-ced3-48d6-bc42-1bdb969bd6dd
