### ISSUE TITLE
[Bug]: Notifications do not work on Base and zkSync Era

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25879]
### Describe the bug

Despite waiting for the long time the notifications do not appear on Base and zkSync Era.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/fd93f582-3174-4c2c-bded-6139b741042f

https://github.com/user-attachments/assets/404809ff-29d2-4d42-b75d-dbde09bf48ba

### Steps to reproduce

1. Connect to zkSync Era or Base
2. Send a transaction
3. Notice that notification doesn't appear

### Detection stage

In production (default)

### Version

v12.0.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

**Comment by Prithpal-Sooriya** [comment]
Closing as we do not support Base and zkSync notifications (yet). We are slowly expanding the chains we support.

NOTE we will have a discussion on the best way of surfacing the chains we support notifications on. Currently this is:
- Ethereum
- Optimism
- Polygon
- Arbitrum
- Avalanche
- Linea
- BNB
