### ISSUE TITLE
[Bug]: Notifications - the 'Check on the Block Explorer' link leads to a 404 page, manual search on Etherscan.io with the transaction hash is successfull

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25878]
### Describe the bug

The `Check on the Block Explorer` link seems to lead to a 404 page, manually searching on Etherscan.io with the transaction hash opens the page successfully. 

Broken link https://www.etherscan.io/tx/0xa65272b9d2a7c5407b5aefb03ce7ac563b83f57fa1bdef260a8a3f50ce135bfc
(link should look like his https://etherscan.io/tx/0xa65272b9d2a7c5407b5aefb03ce7ac563b83f57fa1bdef260a8a3f50ce135bfc)

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/7b945009-e982-4a2f-902c-e4a9139f2a89

### Steps to reproduce

1. Go to `Notifications`
2. Click the `Check on the Block Explorer` link on the mainnet transaction
3. 

### Detection stage

In production (default)

### Version

v12.0.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

**Comment by Prithpal-Sooriya** [comment]
Tested, this has been fixed in v12.
