### ISSUE TITLE
[Bug]: Notifications are not showing up as expected, errors appearing in the console, notification page is not loading

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25877]
### Describe the bug

I don't have exact steps to reproduce, seems like the bug is easy to repro, it happens after some interactions with the extension (probably I was interacting more with the notifications) . At some point notifications are not showing up as expected (red badge doesn't appear), alongside some errors appearing in the console and issues with the notification page loading properly. Issue resolves by reloading the extension.

Probably related: 
https://github.com/MetaMask/metamask-extension/issues/25748
https://github.com/MetaMask/metamask-extension/issues/25749
https://github.com/MetaMask/metamask-extension/issues/25754
https://github.com/MetaMask/metamask-extension/issues/25750

### Expected behavior

Notifications work as expected.

### Screenshots/Recordings

https://github.com/user-attachments/assets/a8c82c92-d4c5-4786-9acd-e33867e86448

https://github.com/user-attachments/assets/54526510-b680-4622-9bc9-7ff62f3bd287

<img width="709" alt="Screenshot 2024-07-16 at 19 37 47" src="https://github.com/user-attachments/assets/7c80d428-50a8-44aa-b911-552550030f19">

<img width="503" alt="Screenshot 2024-07-16 at 19 31 26" src="https://github.com/user-attachments/assets/1d48f516-8fdc-4434-94d0-586a16fc496f">

<img width="555" alt="Screenshot 2024-07-16 at 18 26 05" src="https://github.com/user-attachments/assets/28afd343-886b-4eef-9ece-64f9507289e2">

<img width="555" alt="Screenshot 2024-07-16 at 18 26 20" src="https://github.com/user-attachments/assets/44bcb2ac-d9fa-488d-985c-8900c30973ce">

<img width="557" alt="Screenshot 2024-07-16 at 18 26 37" src="https://github.com/user-attachments/assets/bde9b92d-9e9b-4a45-a715-344fcdd36368">

### Steps to reproduce

1. Send transaction
2. Check for notifications

### Detection stage

In production (default)

### Version

v12.0.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

**Comment by Prithpal-Sooriya** [comment]
Posting for visibility. From some investigations, there seems to be a couple of things we can do to improve performance and also reliability.

**Snap Issues:**
We have a pre-installed snap that we use for logging in and also for creating keys for profile syncing. We are doing this too much, which is slowing down and also throwing errors in the snap environment. We can cache the snap results and don't need to re-call as often.

**Excessive API Calls:**
On the settings page, we are calling our APIs too many times. For each account, we re-call some APIs. We don't need to do this, so deduping and ensuring we call the minimal amount of APIs. Effects are ran at the account components, we should lift this to the single parent/root.

**Storage Setup:**
Profile syncing secures user data by creating a client side encryption key. Generating this key (KDF) takes time (up to 5 seconds). This is in-memory cached, but does mean we need to eat slow initial loads. We can explore persisting this KDF Key, but will need additional eyes/investigations.

**Comment by Prithpal-Sooriya** [comment]
Errors have been fixed and cherry-picked into v12.0.0:
https://github.com/MetaMask/metamask-extension/pull/25946
https://github.com/MetaMask/metamask-extension/pull/25979

There is still some slowness in enabling/disabling notifications. This seems to be from the number of API calls required to setup notifications. Discussing with our backend team to see if we can alleviate some slowness.

**Comment by Prithpal-Sooriya** [comment]
I have tested this on v12. This has been fixed.
