### ISSUE TITLE
[Bug]: On the Transaction details screen, amounts are presented in scientific notation

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25876]
### Describe the bug

On the Transaction details screen, amounts are presented in scientific notation instead of the numerical values.
The bug is reproducible only for send+swap transactions:

<img width="1092" alt="Screenshot 2024-07-17 at 16 11 29" src="https://github.com/user-attachments/assets/b2e4f4c9-6d83-4cff-ab54-ec550564b5e3">

### Expected behavior

Amounts are presented in numerical values.

### Screenshots/Recordings

<img width="327" alt="Screenshot 2024-07-16 at 01 42 14" src="https://github.com/user-attachments/assets/1dc9e6b1-ed0a-4b7b-a8a7-dd1c15bc0b46">

### Steps to reproduce

1. Click on the confirmed transaction within the Activity list

### Detection stage

In production (default)

### Version

v12.0.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
I suspect the scientific notation may be specific to swap + send.  At least, I've been unable to reproduce with regular sends:


<img width="320" alt="Screenshot 2024-07-17 at 11 47 52 AM" src="https://github.com/user-attachments/assets/bec55736-7595-493b-b6b9-953263492d79">

<img width="315" alt="Screenshot 2024-07-17 at 11 53 35 AM" src="https://github.com/user-attachments/assets/ad645f62-ad74-4329-af70-faeb4aaa5f28">


But when there's a swap involved, such that the send and receive assets are different, the amounts do appear in scientific notation:

<img width="322" alt="Screenshot 2024-07-17 at 11 48 22 AM" src="https://github.com/user-attachments/assets/3c6b3677-43f8-4d8b-b2a2-6304e3e9b3c5">

**Comment by sleepytanya** [comment]
@bergeron Thank you, Brian! I updated the description.
