### ISSUE TITLE
[Bug]: Address Book - I cannot add a new account to the address book by pasting an address as the button is always disabled

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25889]
### Describe the bug

I cannot add a new account to the address book by pasting an address. The button remains always disabled

### Screenshots/Recordings

![Screenshot from 2024-07-17 13-03-54](https://github.com/user-attachments/assets/e815af83-1ef1-4b58-af5d-0a34fd4e792c)

https://github.com/user-attachments/assets/c518b5f1-285f-4bc3-b2da-50b3b87d6bd7

### Steps to reproduce

1. Select Mainnet
2. Go to address book
3. Click Add account
4. Paste this address `0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045`
5. See button is always disabled, without any error
Note: you are able to add an account only if you add an ENS domain, that resolves to an address and the button is then disabled

### Detection stage

Develop

### Version

develop - not 12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
:information_source: I added the 12.1.0 tag, since this is not present in 12.0.0, so I assume this will be in the next release.

**Comment by darkwing** [comment]
The issue is one of the newly added `disabled` conditions:

```
disabled={Boolean(
            this.state.error ||
              //!this.state.selectedAddress || <-- Problem
              !this.state.newName.trim(),
)}
```

This condition was added in https://github.com/metamask/metamask-extension/issues/23697

**Comment by mirceanis** [comment]
I need an extra pair of eyes on the PR that fixes this issue: https://github.com/MetaMask/metamask-extension/pull/26155
