### ISSUE TITLE
[Bug]: RPC - MM breaks with error `Message: Cannot read properties of undefined (reading 'rpcPrefs')`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25887]
### Describe the bug

Whenever I click on the `All Permissions` option from the accounts menu, MetaMask breaks with the error `Message: Cannot read properties of undefined (reading 'rpcPrefs')`

### Screenshots/Recordings

![Screenshot from 2024-07-17 12-50-05](https://github.com/user-attachments/assets/d874eac9-1189-4bd4-8d09-3fded58a5bfd)

https://github.com/user-attachments/assets/144aca8e-77fc-4f8d-ba81-34d940590109

### Steps to reproduce

1. [UPDATE] Disable the `Select Networks for each site` toggle --> this is what makes it fail. If you have it enabled. the Permissions work
2. Open menu account
3. Click All Permissions

### Detection stage

In production (default)

### Version

12.0.0 beta build

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by NidhiKJha** [comment]
@seaona I am testing on the beta build. But I couldn't replicate this one. It seems to work fine for me. Can you check which Dapps were you connected to?

**Comment by seaona** [comment]
After investigating a bit further, looks like this only happens if you have the `Select Networks for each site` toggle disabled. I will update the repro steps description:

![Screenshot from 2024-07-17 16-45-43](https://github.com/user-attachments/assets/e080a7ad-6aa8-4fd0-85c0-b2920caa8f22)
