### ISSUE TITLE
[Bug]: Optimism 'Check on the Block Explorer' link leads to 404 (link points to the ethrescan.io instead of optimistic.etherscan.io

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25882]
### Describe the bug

Optimism 'Check on the Block Explorer' link leads to 404 page. Links points to the ethrescan.io instead of optimistic.etherscan.io

Wrong link: https://www.etherscan.io/tx/0x5a4104158f1ebc518f7288f2afa2c3a4827300523026583c324d36e0eb90ccd1

Right link: https://optimistic.etherscan.io/tx/0x5a4104158f1ebc518f7288f2afa2c3a4827300523026583c324d36e0eb90ccd1

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/de4dbe5b-473f-4c2b-ba43-cbf93df4c08d

### Steps to reproduce

1. Go to Notifications
2. Click on Op transaction Block explorer link 

### Detection stage

In production (default)

### Version

v12.0.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

**Comment by Prithpal-Sooriya** [comment]
Tested on v12.0.0 (dev) this is resolved.
