### ISSUE TITLE
[Bug]: When transactions are executed in a non-sequential order, the notifications do not appear as expected

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#25883]
### Describe the bug

When transactions are executed in a non-sequential order, such as canceling a transaction or sending a transaction with a higher nonce, the notifications do not appear as expected.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/fbff6178-00d3-4852-97ba-8035e02a9cac

### Steps to reproduce

1. Send a transaction with the same / high nonce
2. Wait for the transaction to be confirmed
3. Notice that notifications were not shown

### Detection stage

In production (default)

### Version

v.12.0.0

### Build type

Beta

### Browser

Chrome

### Operating system

MacOS

**Comment by Prithpal-Sooriya** [comment]
We've had discussions on this, and believe this is resolved. This was not related to transactions out-of-order, but due to transactions in the same block. The back-end performs strict deduping/filtering when processing a block for notifications, this I believe has been resolved.
