### ISSUE TITLE
[Bug]: Buttons migrated on the side in the 'Add contacts' flow  

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-extension#25890]
### Describe the bug

Buttons migrated to the right side; you have to scroll to the right to be able to add the contact

### Screenshots/Recordings

https://github.com/user-attachments/assets/acff4cee-bd48-48ec-a8c7-711ef151ebd9

### Steps to reproduce

1. Open Metamask in pop-up view
2. Go to Settings->Contacts
3. Add contact
4. See the two buttons migrate to the right side of the pop up; you need to scroll to get to them

### Detection stage

During release testing

### Version

12.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by HarshS1611** [comment]
Hey, I would like to work on this issue. Can you please assign me?

**Comment by darkwing** [comment]
This appears in versions earlier than 12.0, so this shouldn't be attributed to 12
