### ISSUE TITLE
I am Not Able To Download Metamask.

### ISSUE THREAD

**Issue by alijannati** [MetaMask/metamask-extension#2593]
I have tried many times to download Metamask Chrome Extension to no avail. I have communicated with James a few times today, yesterday, and I think even before that. However everything that I was instructed to do I did but still cannot get this app to download. 
Please advise, as my tokens/coins are sitting suspended in MyEtherWallet and I cannot send them without first connecting to Metamask.
Thank you,
Ali Jannati 
FAQ:
  BEFORE SUBMITTING, please make sure your question hasn't been answered in our FAQ: https://github.com/MetaMask/faq
  Common questions such as "Where is my ether?" or "Where did my tokens go?" are answered in the FAQ.

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by tmashuang** [comment]
@alijannati Related to #1070. TL;DR: might need to restart your browser. Which OS and Chrome version are you using?

**Comment by danfinlay** [comment]
What happens when you try to install?

Your tokens/assets should not be frozen, because you can use your seed phrase with any wallet, either MyEtherWallet, or Jaxx, or Parity, or any other ethereum wallet.

**Comment by danfinlay** [comment]
Closing until user replies.
