### ISSUE TITLE
Add Developer Flags to Skip Onboarding Steps

### ISSUE THREAD

**Issue by seesemichaelj** [MetaMask/metamask-extension#2595]
It'd be nice to be able to skip the onboarding steps (i.e. the NoticeScreen and the "how it works" webpage) with some developer flag. I'm not sure if you can do this given your terms/etc. Maybe theres a thing that pops up on the terminal when they type `gulp dev` saying they're agreeing to your terms and service found at "..." by using this in dev mode.

The things I'm mainly interested can be found in https://github.com/seesemichaelj/metamask-extension/commit/f2abd03ab72302a0868a672c4fc58712a48fa97a

**Comment by danfinlay** [comment]
We actually do have developer mode flags, and they deactivate our auto-faucet feature. We could potentially also have a flag for skipping those.
