### ISSUE TITLE
uat - Eth input suffix assumes fixed width

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2597]
![screen shot 2017-11-17 at 12 17 48 pm](https://user-images.githubusercontent.com/542863/32967152-67687092-cb91-11e7-9d6d-3a0e066e8b04.png)
![screen shot 2017-11-17 at 12 17 41 pm](https://user-images.githubusercontent.com/542863/32967153-678543fc-cb91-11e7-8b63-636a178f4cee.png)

Also, it's very hard to click on the narrow "input" area.

Clicking directly between two numbers should still put cursor at that point, but:
Clicking elsewhere in the input field should highlight all input.

**Comment by danjm** [comment]
If I checkout the uat branch, I see the following behaviour:

![amountuat](https://user-images.githubusercontent.com/7499938/32967668-f8a9f36a-cbb8-11e7-88f6-c8ec04f60832.gif)

And it is not very visibile in that gif, but on the uat branch, if I click anywhere in the amount field (anywhere with the the border), the cursor moves to the end of the input. We can change that to highlighting the input though.

You might be taking different steps than me to cause the above behaviour, or maybe you did this on an older branch or version?

**Comment by danfinlay** [comment]
Oh sorry, I'm working on a branch of an older uat!
