### ISSUE TITLE
Metamask Confirm Button Greyed Out

### ISSUE THREAD

**Issue by thedinarian** [MetaMask/metamask-extension#25989]
### Describe the bug

Whether I am using Chrome or Brave, The confirm button does not come up as an option to sign transactions. I have tried clearing the cache, making sure the Metamask version is up to date (11.16.14) and made sure my ledger Eth app ledger firmware is up to date, adjusted the gas. Any help would be grateful.. This all started in the past week. It worked fine before then. I used the same website on my laptop and everything works fine, so this is isolated to my PC, whatever it is causing it.

### Expected behavior

Confirm and sign transaction

### Screenshots/Recordings

![image](https://github.com/user-attachments/assets/2819cd1f-6654-4f7d-aedf-9aa445970b73)

### Steps to reproduce

Happens at the signing of any transaction.

### Detection stage

In production (default)

### Version

11.16.14

### Build type

None

### Device

Gaming PC

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

Windows 10 Brave and Chrome

### Severity

Can not use metamask for transactions

**Comment by szabope** [comment]
Exactly the same issue here. Although I updated ledger before trying. Then I found this: https://support.ledger.com/article/4405481324433-zd

**Comment by thedinarian** [comment]
I apologize for the delay, I am a truck driver and I had two back to back cross country runs and the a NJ-NY run. 
The above issue seems to have resolved itself somehow. I did have Ledger updated and blind signing enabled, and It did effect all chains. All is good for now! Thank you everyone!
