### ISSUE TITLE
[Bug]: How to remove “This is a deceptive request” message from metamask popup

### ISSUE THREAD

**Issue by austinrampt1** [MetaMask/metamask-extension#25992]
### Describe the bug

Recently the message “this is a deceptive request from a we site known for scams” has started appearing on our users transactions. 

We are devvelaunchpad.io and not deceptive or scamming in any way. Users are trying to stake their token. This is a false flag that was definitely made in error

### Expected behavior

This message shouldnt be appearing at all. 

### Screenshots/Recordings

![IMG_5549](https://github.com/user-attachments/assets/214c76e0-18ee-45f5-9e45-d59aa1d660cb)

### Steps to reproduce

Go to devvelaunchpad.io
Navigate to stake devve
Click to approve the stake (you mist have atleast one devve in your account)
The approval will go to this contract 0xa0dab5d6907a9CFFD023e0160210eAB464322b70 which is not malicious
You will see the metamask message saying that the request is deceptive and that our website is known for scams. Which is inaccurate. Somehow we got classified here. 

### Detection stage

In production (default)

### Version

7.26.1

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS, Linux

### Hardware wallet

Ledger, Trezor, GridPlus Lattice1

### Severity

This is a critical error for us. It prevents many users from using our website

**Comment by bschorchit** [comment]
Hey @austinrampt1, sorry for this issue! The issue will be resolved within the next 24hours.
