### ISSUE TITLE
[Bug]: Notifications - Incorrect text in the notification popup pointing to Settings, but they are not present there

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#25994]
### Describe the bug

Whenever you try to enable Notifications, you can see how the text points you to `Settings>Notifications` however, Notifications does not appear in Settings.
If you try to look for it in the Search settings bar, you can see how it seems to appear under Experimental, but it is not present there neither

### Expected behavior

Not sure what's the correct behaviour here: either change the miss-leading text and fixed the setting search so it does not appear in settings, or add the Notifications section in Settings 

### Screenshots/Recordings

![Screenshot from 2024-07-22 09-06-28](https://github.com/user-attachments/assets/71a0f8e3-a14a-4d80-8aeb-4cfd4c7658b1)

![Screenshot from 2024-07-22 09-06-16](https://github.com/user-attachments/assets/d4121afa-8f0c-4ceb-93ae-9eabad742e0c)

### Steps to reproduce

1. Click Account menu
2. Click Notifications
3. See text `You can turn off notifications at any time in Settings > Notifications.`
4. Go to Settings
5. See Notifications is not there in any section
6. Look for notifications using the search bar
7. See how it appears in the Experimental section
8. Click Experimental
9. See how it's not there

### Detection stage

In production (default)

### Version

12.0.0 beta build

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Prithpal-Sooriya** [comment]
This has been merged into v12 and is resolved.

<details><summary>See screenshot</summary>
The copy has changed and removed the path to settings. We will add this path back in once the settings page has been created.

This settings is still accessible through the notifications page.

![Screenshot 2024-07-23 at 15 45 46](https://github.com/user-attachments/assets/26a35ebc-909f-4827-b31c-547f8cc34fe7)

</details>
