### ISSUE TITLE
How to ask MM to display the "unlock account" dialog?

### ISSUE THREAD

**Issue by sulliwane** [MetaMask/metamask-extension#2602]
Hello,

I would like to know if MM/Mascara offers any way to control its UI/settings from my frontend? I have many actions I'd like to do, for example:

- User click "unlock MM" on my website, and MM browser extension opens up the unlock dialog (I currently detect MM is locked by polling account state every 1sec, but I don't know how to prompt for unlock dialog)
- User click "switch network" on my website UI, and it switches MM/Mascara chain (ropsten -> rinkeby)
- ...etc

Many thanks!

**Comment by danfinlay** [comment]
Any call that uses the user's keys (sendTransaction, or any sign method) will prompt the user to log in if they aren't already.

You can learn a bit more about developing for MetaMask here:
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md

**Comment by gkaemmer** [comment]
> Any call that uses the user's keys (sendTransaction, or any sign method) will prompt the user to log in if they aren't already.

But this is impossible because you don't know the user's address, right? The address is a required argument to sendTransaction or eth_sign.

**Comment by tbrannt** [comment]
I'd also like to know if there's a way to promt the user to unlock metamask without the need of letting him sign an invalid request (because there's no known account yet.

**Comment by bdresser** [comment]
you should call `ethereum.enable()` to get the user's account address. If the user doesn't have their MetaMask unlocked, they'll first see the log in screen before the "connect" screen.

**Comment by gkaemmer** [comment]
@bdresser What if the user's metamask is enabled (i.e. they've already approved the domain), but locked? Is it required to keep asking users to re-enable metamask every time they log out?

**Comment by bdresser** [comment]
@gkaemmer yeah, if the user's extension is locked, calling enable will open the password prompt, then the connect screen. 

Couple reasons - it's a bit strange to ask for the password without context, and dapps shouldn't be reliant on our caching / approval behavior since it's not technically part of [EIP 1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md) and other browsers might not implement it. 

We know this is extra friction - eventually we'll get around to combining the two screens, see https://github.com/MetaMask/metamask-extension/issues/5836

**Comment by realisation** [comment]
@bdresser that is not the behavior I am getting - when I call enable(), nothing happens. It just returns a promise, but no popups occur or anything.

What am I missing? I would like to prompt the user to log in/ulock in the case they aren't, say they've logged out or just opened Chrome after it was quit before.

**Comment by bdresser** [comment]
@realisation you may have encountered a bug in 6.5.1 & 6.5.2 (https://github.com/MetaMask/metamask-extension/issues/6618) fixed in 6.5.3 (https://github.com/MetaMask/metamask-extension/pull/6619). 

Could you update your extension, try again, and let us know?

**Comment by realisation** [comment]
Indeed - it disappeared later that day.
