### ISSUE TITLE
Fix "Dapp interactions should connect a second Dapp despi..." flaky tests

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#26035]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/92651/workflows/dac61e17-caa2-44ab-979c-05c38b16541b/jobs/3449334/tests

**Comment by chloeYue** [comment]
Close this one because duplicate with https://github.com/MetaMask/metamask-extension/issues/19726
