### ISSUE TITLE
Fix "Confirmation Signature - Sign Typed Data initiates a..." flaky tests

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#26037]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/92641/workflows/f18c022a-5130-48c9-b7e0-f4340b44ea0a/jobs/3448887/tests

**Comment by pedronfigueiredo** [comment]
I tried to reproduce the issue locally by running `yarn && yarn start:test:mv2` on one console and `ENABLE_MV3=false yarn test:e2e:single test/e2e/tests/confirmations/signatures/sign-typed-data.spec.ts --browser=firefox --debug --leave-running` on another one. I ran the tests locally ~30 times with no luck reproducing the issue.

**Comment by OGPoyraz** [comment]
I've done the local tests and couldn't see any issue.
Closing this for now, we can re-open if flakiness persists
