### ISSUE TITLE
opera extension not working. 

### ISSUE THREAD

**Issue by SurpriseBit** [MetaMask/metamask-extension#2606]
Briefly describe the issue you've encountered
  *  To install metamask as a opera extension 
  *  Error : An error occurred when installing the extension: Installation failed
  *  Opera
  *  Windows 10
![3af40d2afa439943fa65f39da8a83ad4](https://user-images.githubusercontent.com/33877624/33091993-bb634fa4-cec6-11e7-9bfe-f312476e57bf.png)

**Comment by tmashuang** [comment]
Duplicate of #2504, there is a missing script on the bundle. I have provided a solution on the other thread. Will include the missing script in the next deployment.

**Comment by SurpriseBit** [comment]
Ok, thanks.
