### ISSUE TITLE
[Bug]: Errors in the console when enabling notifications for an account

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26068]
### Describe the bug

Every time when user enables notifications for the account there are errors in the console. 

Develop:

https://github.com/user-attachments/assets/70879d42-7e54-4b0e-95d6-70e544897ece

<img width="589" alt="Screenshot 2024-07-23 at 15 51 38" src="https://github.com/user-attachments/assets/7a416daa-6258-472c-9642-2a21e1425bcb">

Latest v12.0.0 build and beta - only 'Uncaught' errors:

https://github.com/user-attachments/assets/9bb0b32c-f2e4-4a89-84de-6b9c978e19e8

https://github.com/user-attachments/assets/cd2c03e4-3b8e-4c0d-8e05-98f13a2fc041

### Expected behavior

-

### Steps to reproduce

1. Go to Notifications
2. Disable / Enable notification for account

### Detection stage

On the development branch

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Prod v12.1.0

Every time user disables notifications for the selected account there is an error:


<img width="660" alt="Screenshot 2024-08-09 at 17 22 39" src="https://github.com/user-attachments/assets/ebf811ec-0421-472a-9234-b62bcc9da09b">



https://github.com/user-attachments/assets/a187094a-6c7d-4bbd-b38e-ab317d0f7d13

**Comment by Prithpal-Sooriya** [comment]
Noted. These error logs are valid (we may make these silent in future versions).

Our team will investigate.

There is a known bug on push notifications with our API.

This impact is on push notifications. It will not impact showing notifications, or modifying settings.

**Comment by desi** [comment]
Tried to reproduce today on RC 12.10.0 and I am not seeing these errors. I am only seeing the Firebase errors referenced in #26089 

@sleepytanya Are you ok to close this one?

**Comment by desi** [comment]
Confirmed ok to close with @sleepytanya
