### ISSUE TITLE
[Bug]: many pop-ups show up unexpectedly when submitting transaction with MM extension into Cypress framework

### ISSUE THREAD

**Issue by lidiia-kondratiuk** [MetaMask/metamask-extension#26060]
### Describe the bug

During transaction confirmations in Cypress with the MetaMask wallet extension, we encounter a problem where several strange pop-ups appear simultaneously, which shouldn't be happening.  It blocks us from completing all tests that include the transaction submission step. As a result, all such tests like delegation votes, publishing proposals on-chain, and voting on proposals are failing.

We are using this meta mask synpress:
 "name": "metamask.synpresstests",
      "version": "1.0.0",
      "license": "ISC",
      "dependencies": {
        "@synthetixio/synpress": "^3.7.3",
        "node-fetch": "^2.7.0"

### Expected behavior

Once the transaction is completed with MM extension into Cypress, we should not see any additional pop-ups that can not be closed.

### Screenshots/Recordings

![image (3)](https://github.com/user-attachments/assets/16a4e331-20f0-4a17-9aea-94ece60bc1eb)

### Steps to reproduce

Preconditions: you need to have automated test via Cypress framework and integrated metaMask extension into.
1. Open your automated test into Visual Studio.
2. Force executing this test with the transaction.
3. See how unexpected many pop-up from MetaMask extension appear once the transaction is completed.

### Error messages or log output

```shell
Three pop-ups that can not be closed automatically in Cypress framework when executing transaction submission.
```

### Detection stage

In production (default)

### Version

11.16.14

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS

### Additional context

We are using Cypress framework with integred MM extension
11.16.14

### Severity

It`s a blocker issue for automated tests via Cypress frameworks and MM extension

**Comment by seaona** [comment]
hey @lidiia-kondratiuk, thank you for reporting this! Could you let us know,
- which is the Chrome version you are using?
- when did this behaviour start happening?
- I see you reported MM version 11.16.14, is it working on MM previous versions?

Thank you in advance!

**Comment by lidiia-kondratiuk** [comment]
Hey Seaona,
My team is using this Chrome 126.0.6478.183 version.
This issue started happening 1 month ago from 25th June. We have been
trying to fix this ourselves but have had no results.
Good questions about the previous version. Let us to try reinstalling the
previous version to see if it will work.
Also, I`m adding the error form console that causes the issue with pop-ups:
CypressError: `cy.task('confirmMetamaskSignatureRequest')` failed with the
following error:> page.waitForEvent: Timeout 30000ms exceeded while waiting
for event "close"
=========================== logs ===========================
waiting for event "close"

Many thanks for considering my request!
