### ISSUE TITLE
flaky tests: mmi flaky tests Reveal SRP through settings completes quiz and reveals SRP QR after wrong answers , Sign Typed Data Signature Request can initiate and reject a Signature Request of Sign Typed Data, Sign Typed Data Signature Request can queue multiple Signature Requests of Sign Typed Data and confirm

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#26076]
### What is this about?

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/93056/workflows/ba01ff72-1e2e-4eba-b8ea-fb22aa07250c/jobs/3465362/tests

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by seaona** [comment]
fixed by this PR https://github.com/MetaMask/metamask-extension/pull/26055

**Comment by hjetpoluru** [comment]
Flaky test is fixed and closing this ticket.
