### ISSUE TITLE
Unable to start using

### ISSUE THREAD

**Issue by soolyhuey1** [MetaMask/metamask-extension#2609]
After I add the extension I can't go any further to join/login/create vault etc for Metamask. All that comes up is the help video. On the man page the swinging foxhead cant be clicked on.
Anyone got any ideas? Macbook Air, chrome

BEFORE SUBMITTING, please make sure your question hasn't been answered in our support center: https://support.metamask.io
Common questions such as "Where is my ether?" or "Where did my tokens go?" are answered there.

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by danfinlay** [comment]
Are you clicking on the fox head in your menu bar to interact with MetaMask?

Try looking at logs if you still can't use this:
https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by danfinlay** [comment]
Let us know if you still can't find the foxhead in the menu bar. Closing for now.
