### ISSUE TITLE
does not show transaction window for  web3 '.call()' function.

### ISSUE THREAD

**Issue by coindevbw** [MetaMask/metamask-extension#2611]
Hi,
for a 'payable' Solidity function,
calling a function by 'instance.functionName({value:10000})' does trigger the transaction window,
but 'instance.functionName.call({value:10000})' does not trigger transaction window and the solidity function just executed. 'require(msg.value == value);' does not work.
This seems critical security hole.

Best,
coindevbw

**Comment by danfinlay** [comment]
The .call method does not send an actual transaction, it just simulates one. This is usually used for reading from the blockchain. For sending a transaction, with user approval, use `eth.sendTransaction()`
