### ISSUE TITLE
Make MetaMask (or web3 in general) available on android default browser, mobile chrome and safari on iOS

### ISSUE THREAD

**Issue by buhrmi** [MetaMask/metamask-extension#2612]
Hello,

how can we get web3 everywhere? How do we convince Microsoft, Apple and Google that this is "the right way to go" and they should add web3 support everywhere and support private key management on the operating-system level?

**Comment by tmashuang** [comment]
Https://wallet.metamask.io

**Comment by buhrmi** [comment]
@tmashuang this currently shows an empty page and the console reads `ui.js:20338 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The request to fetch the script was interrupted.`. Does it work for you?

**Comment by tmashuang** [comment]
@buhrmi need to refresh a couple times for the service worker installation.

**Comment by mimiisriii** [comment]
Is there any way to retrieve a vault information from Android? I may have accidentally "create a wallet" from my phone with no seed phrase (thinking it was the same one I had created on my PC). Now I am not able to access my coin... Please advise.

**Comment by buhrmi** [comment]
this was dumb

**Comment by cyruswise** [comment]
Open your site in the metamask browser and it works!

**Comment by cyruswise** [comment]
There exist a browser in the metamask android app
