### ISSUE TITLE
[Bug]: Signatures - Re-design feature is disabled by default after a migration, but enabled by deafult with a fresh install

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#26151]
### Describe the bug

If I perform a migration from current prod 11.16.X to 12.0, I can see how the Signatures Redesign feature is disabled, whereas if I do a fresh install, the feature is enabled

### Screenshots/Recordings

Migration (feature disabled)

https://github.com/user-attachments/assets/c625c745-9c75-4341-9d29-0bc161d1b1a4

Fresh install v12 (feature enabled)

https://github.com/user-attachments/assets/60f4c8e2-0d3b-46e2-ae34-c50b78e9901a

### Steps to reproduce

1. Import v11.16.x
2. Migrate to x12
3. Check experimental settings

### Detection stage

In beta

### Version

12.0.0 beta build

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by cryptotavares** [comment]
@seaona this is working as expected. 12.2.0 is where we enable it by default for all users.

**Comment by seaona** [comment]
thank you @cryptotavares I wasn't aware of this, then I'll close the issue!
