### ISSUE TITLE
[Bug]: Signatures - Metrics - `ui_customizations` doesn't display `redesigned_confirmation` if the signature is malicious

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#26152]
### Describe the bug

With the redesigned signatures, whenever there is a case when a signature is both redesigned and malicious, we don't display the `redesigned_confirmation` property in the `ui_customizations`. Here is what we do on each case in the `ui_customizations` property:
- :green_circle:  If the signature is redesigned and benign, we display `redesigned_confirmation`
- :red_circle:  If the signature is redesigned and malicious we display `flagged_as_malicious` but we don't display `redesigned_confirmation` --> this seems incorrect
- :green_circle:  If the signature is not redesigned and benign, we don't display the field `ui_customization`
- :green_circle:  If the signature is not redesigned and malicious we display `flagged_as_malicious`

### Expected behavior

For the case 2, we should display both `flagged_as_malicious` and `redesigned_confirmation` ?

### Screenshots/Recordings

Redesigned + Benign 
![Screenshot from 2024-07-26 10-49-23](https://github.com/user-attachments/assets/37653ad5-4c1d-4f5c-a19f-e604fc55c8a1)

Redesigned + Malicious
![Screenshot from 2024-07-26 10-49-17](https://github.com/user-attachments/assets/a2c145dc-1c93-4063-812c-196ed211c233)

https://github.com/user-attachments/assets/132288a5-a6aa-463a-8252-1530051301d2

### Steps to reproduce

1. Enable redesigned signatures
2. Trigger a malicious signature
3. Check segment event properties

### Detection stage

In beta

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by jpuri** [comment]
This seems to be fixed already in latest code in develop branch.

<img width="978" alt="Screenshot 2024-07-29 at 4 12 26 PM" src="https://github.com/user-attachments/assets/62b420ed-2ba2-4035-837c-b5df80aae3b9">

**Comment by jpuri** [comment]
Hey @seaona : can you plz check to confirm that issue is already fixed ?
