### ISSUE TITLE
Issues Restoring Wallet from Seed Phrase

### ISSUE THREAD

**Issue by vincefutr23** [MetaMask/metamask-extension#2617]
Hi all, 

I am locked out of my metamask vault, and unfortunately have quite a large number of tokens in there. The lockout occurred a few weeks ago, when I believe Metamask updated, and stopped prompting me with the "login" screen, and instead began to show the "enter new password" screen that you would see if you had just installed it. I clicked the part on the bottom where you can restore from mnemonic, retrieved my piece of paper where the seed was written down, but then to my great dismay, was told "invalid seed phrase" by metamask. Same result after trying multiple variations of phrase, and reinstalling the extension. 

So either there is some issue with restoring wallets on metamask from seed, I have copied down the wrong phrase or mispelled something, or there is something going on entirely that I am not aware of. Below is a summary of things i have tried, clues i have gathered so far. Maybe you can help !

**Things I have:** 
-Wallet's public address
-Password to metamask vault
-12 word phrase written on a piece of paper (does not appear to work though) 
-Macbook wallet downloaded and operated on 

I have contacted Metamask support through their support system, and they got back to me quickly. They pointed me to this tool [https://metamask.github.io/vault-decryptor/](url) that is able to take some locally stored Chrome data and the vault password to recover your seed. The problem with this for me is that in the process of trying to restore my vault, I have deleted and redownloaded the metamask extension a couple of times, so when i use this tool, it recovers the most recent (empty) wallet. **If someone knows how to access old local chrome files from deleted extensions that would solve this**! but seems like a long shot.  

They also showed me this tool [https://danfinlay.github.io/hd-seed-phrase-guesser/](url) but i am not sure what exactly it does or how it can help me? 

Another element of confusion, is that a reddit user pointed me to this list, saying that all seed words can be found on this list [https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt](url)  Can anyone confirm if this is the case? not sure how word generation works. unfortunately not many of my seed words are also found on that list, not sure of the significance of that. 

I have also tried to recover from MEW. Using the "Mnemonic" way to access a wallet. This does not seem to do anything or work. This Might support the case that I have a miscopied seed phrase or something along those lines. 

If anyone is able to help restoring this wallet given the information above I would be eternally greatful and happy to pay a bounty! 

Most promising path to recovery from my investigation so far 
- some way to find old chrome extension data stored on computer and use vault tool from metamask
- some way to programmatically brute force slight variations of my written seed phrase (under the assumption that i misspelled it)
- if there exists a way through the development team to open a wallet with just the public key and the vault password? 
-something i am overlooking operationally that i causing me to have this trouble when my seed may be actually correct?

**Comment by tmashuang** [comment]
Here is a non-polished seed phrase recovery tool https://danfinlay.github.io/js-recover-bip39/. Each word needs at least 4 letters to guess the rest of word. If the word is 4 letters or less it won't guess it, the non-polished part. Also, words can have prefixes and suffixes that may or may not be the correct word.

**Comment by sardoru** [comment]
I have the same issue @vincefutr23. have all the above info as well.


> If someone knows how to access old local chrome files from deleted extensions that would solve this!

If anyone can help, would be great! I got quite a bit in tokens locked up.

**Comment by vincefutr23** [comment]
@tmashuang thanks for the link. Can you explain a little more how that tool works? it does not appear to work for me and only outputs one or two words

**Comment by vincefutr23** [comment]
@sardoru would love to discuss your experience further. Whats a good email ?

**Comment by tmashuang** [comment]
@vincefutr23 it will guess each individual word with 4 letters. Something like `unaw` will guess `unaware` or `awar` will guess `aware`. When submitting a 12 whole seed phrase it will omit the word it does not find in the dictionary.  It does not have the ability to find the correct order of a seed phrase

**Comment by sardoru** [comment]
@vincefutr23  - pls email sardoru [att] gmail

**Comment by danfinlay** [comment]
You might want to try spell checking the twelve words you have. If it isn't working, it could be a spelling mistake.

To access old chrome files from a deleted extension, you probably need to keep regular backups of your computer. Do you have backups available? If so, you can usually google for your system and browser, and where it stores extension data. Let us know what your OS and browser version are.

**Comment by danfinlay** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/2893

**Comment by jazzinuf** [comment]
@tmashuang
Hey my friend, I’m having the same trouble as well. Did you ever get your account back?
