### ISSUE TITLE
[Design Quality]: Update styling of the secondary currency and balance %

### ISSUE THREAD

**Issue by amandaye0h** [MetaMask/metamask-extension#26188]
### **Problem statement** 
There is a lack of hierarchy of the balance components. Strengthening the contrast will improve the visual appeal of the product. 

### Expected behavior

**### Acceptance criteria**

- Primary balance `font-weight = 500 (medium)`
- Secondary currency `color = text.alternative`
- Secondary currency `text size = body md (14px / 0.875rem)`
- Secondary currency `font weight = medium` 
- When +/- changes are 0, color = `text.alternative`
- Review final implementation with @amandaye0h 

### Screenshots/Recordings

<img width="997" alt="Screenshot 2024-07-29 at 7 05 11 AM" src="https://github.com/user-attachments/assets/c328ae1f-7fa4-4b16-84d0-a8b819f2c5c6">

[Link to Figma](https://www.figma.com/design/bkJ9Ot0HGXiakMqZtQfs8G/Design-Quality?node-id=214-3)

### Steps to reproduce

1. Open MetaMask

### Detection stage

On the development branch

### Version

11.16.15

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by agagancarczyk** [comment]
hi @amandaye0h enhancements look fantastic - great job! I'd love to work on the implementation. Could you please assign me to this issue? Thanks
