### ISSUE TITLE
Deploy contract (with MEW) causes "Recipient address is invalid."

### ISSUE THREAD

**Issue by DaveAppleton** [MetaMask/metamask-extension#2621]
Trying to deploy a contract with myetherwallet/metamask combo on rinkeby

MEW prepares data but in MM, error message is seen

![image](https://user-images.githubusercontent.com/1858302/33287477-c22b29e2-d3f3-11e7-894e-2276b851d3a2.png)

Note : Data is BIG (300K+)

**Comment by tmashuang** [comment]
How are you initializing the transaction? Seems that there is an issue with the format of the recipient address. The recipient should be omitted for account creation. And contract bytecode should be in the data field

**Comment by DaveAppleton** [comment]
On MEW select deploy contract. (no params so this should work)

Select to use with metamask.

Sign Tx (that works)

Write it
Q) are you sure 
A) damn right I'm sure
 -> up comes the commit window as shown.

**Comment by accraze** [comment]
I'm having the same issue with MEW, any suggestions?

**Comment by danfinlay** [comment]
Looks like MEW is passing us *something* as the recipient, and we aren't recognizing it as nothing. We'll need to investigate this.

**Comment by tmashuang** [comment]
So in the official Web3 docs, https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction, the 'to' should be left `undefined` for Contract Creation we can open either open an issue with MEW, and/or we can account for this issue in MetaMask.

**Comment by toneloc** [comment]
Similar issue when deploying to Ropsten.

**Comment by kumavis** [comment]
looks like mew is giving us `"to": ""`

```json
{
  "from": "<valid from address>",
  "nonce": "0xd4",
  "gasPrice": "0x04e3b29200",
  "gasLimit": "0x5208",
  "to": "",
  "value": "0x00",
  "data": "0xabcd",
  "chainId": 3
}
```

**Comment by tina1998612** [comment]
I have the same issue when using the "Metamask/Mist" option, but using the "private key" option as follows worked:
![screen shot 2018-01-06 at 10 11 01 pm](https://user-images.githubusercontent.com/19768276/34640487-8f746ed2-f32e-11e7-8ecf-cf3806907033.png)

So in my view, the problem can be fixed if Metamask makes the empty string a valid recipient address, and warn the user this is only valid for contract deploy. 
Thanks!

**Comment by mswezey23** [comment]
Hitting the same roadblock trying to deploy to Ropsten using MEW & MetaMask.
