### ISSUE TITLE
Memory usage can spike on entering large numbers on swaps

### ISSUE THREAD

**Issue by desi** [MetaMask/metamask-extension#26238]
### What is this about?

As a user when I open the swaps interface and enter a large set of digits such as ".123412341234123412341234123412341234123412341234"
Then I can observe a spike in memory usage through the task manager on chrome

We have a screencap of this if needed.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by hjetpoluru** [comment]
@desi, I think this was addressed and fixed. Do you happen to remember, I tried to search for the ticket but unable to find it.

**Comment by desi** [comment]
@hjetpoluru I can't find the PR but I just tried to recreate in v12.10.0 and can't so I will close this now.
