### ISSUE TITLE
[Bug]: No clear feedback to user on why it's not possible to send a token 

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#26263]
### Describe the bug

User is not able to send LXP on Linea and no feedback is shown. 

LXP is a soulbound token so that's likely the reason for not being able to proceed. 

### Screenshots/Recordings

<img width="370" alt="Screenshot 2024-07-31 at 15 24 38" src="https://github.com/user-attachments/assets/8a0cbf2b-dbcc-458b-983f-87259d920694">

### Steps to reproduce

1. Have LXP in your wallet
2. Try to send it
3. Notice how you're not able to proceed and there's no explanation on why

### Detection stage

In production (default)

### Version

v12.0.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by bschorchit** [comment]
Closing as I can no longer reproduce it.

**Comment by skenaja** [comment]
I've found this happening with another SBT ERC20. 

* contract address: 0x6E9C1F88a960fE63387eb4b71BC525a9313d8461 (APPL)
* chain: Etherlink mainnet (chain id 42793)

"continue" is greyed out:
<img width="352" alt="Image" src="https://github.com/user-attachments/assets/b2e87f32-0d66-468a-8ba4-91b7a20ae61a" />

if you estimate gas for the `transfer()` tx you get 0x3d693ada revert error `NotAllowed()` which implies it's a SBT

If you remove the recipient account by "X" button and add it back in again, the Continue button is enabled

<img width="340" alt="Image" src="https://github.com/user-attachments/assets/1cbb5716-b79b-4989-81fc-66b3884ea8bb" />

If you click confirm, the transaction appears to be sent to txpool, receives a pending tx hash, and remains at "pending" state until it's replaced (eg via a send 0 ether transaction with custom nonce)
