### ISSUE TITLE
Calling contract method with too many decimals for value results in Metamask showing wrong value

### ISSUE THREAD

**Issue by manosamy** [MetaMask/metamask-extension#2628]
Tried to call deposit method on a contract for 1 CAD converted to ETH without any rounding, 
My call looks like this:

receiverWallet.deposit(message, { from: from, value: web3.toWei("0.0016482067510548521", "ether"), gasPrice: web3.toWei(gasPriceGWei, 'gwei') })

But metamask seem to convert it into 3.189E22 ETH (If only I had so many ethers...)

Doesnt happen always, in some other cases, it arbitrarily rounds it down to fewer decimals.

Doing this works:

receiverWallet.deposit(message, { from: from, value: web3.toWei(parseFloat("0.0016482067510548521").toFixed(4), "ether"), gasPrice: web3.toWei(gasPriceGWei, 'gwei') })

![image](https://user-images.githubusercontent.com/29697041/33346778-73399a18-d456-11e7-9fef-e5ab8248fce9.png)

I already patched it on my site by rounding
Unpatched version is here:
https://bitofme-2.azurewebsites.net/pay?name=mano.thisisme.eth&amount=1cad
If by chance the exchange rate at that time lends itself to rounding, change the amount to 0.0016482067510548521 and try again.

Version with rounding (works fine):
https://bitofme.io/pay?name=mano.thisisme.eth&amount=1cad

Expected behavior:
Metmask should consistently round (or preferably do BigNumber operations accurately, without having to round), and document the rounding logic.

**Comment by danfinlay** [comment]
This may be a web3 error, (if the `toWei` method returns the buggy value). Need to investigate more.

**Comment by frankiebee** [comment]
This defiantly seems like a web3 issue it doesn't look like we avoid rounding with txParam values  and doing `web3.toWei("0.0016482067510548521", "ether")` will return `"1648206751054852.1"` and we dont except decimals and in future behavior it will throw an error which is fixed in PR #2783
