### ISSUE TITLE
Fix "View ERC1155 NFT details user should be able to view..." flaky tests

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#26313]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/94695/workflows/88624a2b-7758-4b7a-a787-f3bcbff5d010/jobs/3524549/tests

<img width="1611" alt="Screenshot 2024-08-02 at 2 22 39 PM" src="https://github.com/user-attachments/assets/057f35bf-ac24-47a4-89b3-46eeadc54303">

From the above CI link below are my findings.
- The screenshot was not captured but based on test steps, browser was launched and password was entered. This leads me to assume that the browser either crashed or disconnected at the capture of screenshot or may something else too.
- Below error happens after the server mocha client is connected:-

```
[driver] Called 'navigate' with arguments []
[driver] Called 'fill' with arguments ["#password","correct horse battery staple"]
ServerMochaToBackground got a client connection
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="80.007" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2024-08-01T19:46:47" tests="0" time="0.000" failures="0">
  </testsuite>
  <testsuite name="View ERC1155 NFT details" timestamp="2024-08-01T19:46:47" tests="1" file="/home/circleci/project/test/e2e/tests/tokens/nft/view-erc1155-details.spec.js" time="80.006" failures="1">
    <testcase name="View ERC1155 NFT details user should be able to view ERC1155 NFT details" time="80.004" classname="user should be able to view ERC1155 NFT details">
      <failure message="Timeout of 80000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (/home/circleci/project/test/e2e/tests/tokens/nft/view-erc1155-details.spec.js)" type="Error"><![CDATA[Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/circleci/project/test/e2e/tests/tokens/nft/view-erc1155-details.spec.js)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>
```
- On the second attempt was executed successfully
```
[driver] Called 'navigate' with arguments []
[driver] Called 'fill' with arguments ["#password","correct horse battery staple"]
ServerMochaToBackground got a client connection
[driver] Called 'press' with arguments ["#password",""]
```

There was another failure in a similar section. I have mentioned it below in case the fixtures are related. I am planning to review the fixtures to determine any details.

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/94877/workflows/8907a3bf-bfc2-42f0-b8b2-fd8a4bd4f3b4/jobs/3530884/tests

![image](https://github.com/user-attachments/assets/63cc9512-3f4e-4091-8060-d739dd30c38c)

**Comment by hjetpoluru** [comment]
This is a tricky flaky test and it has not been observed again. It might just be an environment issue, and if it is more often, it should be investigated. For now, it can be closed and I have documented my observations.
