### ISSUE TITLE
Fix "Create Snap Account cancelling naming Snap account r..." flaky tests

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#26314]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/94628/workflows/4f96dc5a-0a42-4b6f-9725-387ecabb230b/jobs/3521844/tests

**Comment by plasmacorral** [comment]
was resolved [here](https://github.com/MetaMask/metamask-extension/pull/26950)
