### ISSUE TITLE
[Design Quality]: Update styling of Ramps Card

### ISSUE THREAD

**Issue by amandaye0h** [MetaMask/metamask-extension#26321]
### Describe the bug

The spacing of the card is inconsistent, which makes the alignment on the page inconsistent. Adjusting this will improve the polish of the home page.

### Expected behavior

**Acceptance Criteria**
- Padding between “Fund your wallet” and “get started” = `0px`
- Padding between “Get started...” and “Buy ETH” = `0px`
- “Getting started” margin bottom = `8px`
- Card margin = `16px`
- Card top/bottom padding = `12px` and left/right = `16px`
- “Get started” text width reduced to `60%`
- [close icon](https://github.com/MetaMask/metamask-extension/blob/653962c72d11f6b738140da613cc6cd184f6cdb9/ui/components/component-library/icon/icon.types.ts) added on the top right 
- Changes are applied to NFT and Activity variations

### Screenshots/Recordings

<img width="1079" alt="Screenshot 2024-08-02 at 8 10 25 AM" src="https://github.com/user-attachments/assets/a544197c-4daf-4051-9cf2-4439f48f0ddc">

### Steps to reproduce

1. Onboard to MM
2. Create new wallet (Do not select import wallet)

### Detection stage

In production (default)

### Version

11.16.15

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Ping @amandaye0h (Assets Designer) for additional context

**Comment by anaamolnar** [comment]
Hey @amandaye0h Thanks for reporting! I will pass this on to the team.

**Comment by amandaye0h** [comment]
Resolved [here](https://github.com/MetaMask/metamask-extension/pull/27184)
