### ISSUE TITLE
[Bug]: Unable to swap hidden token / not imported tokens

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26340]
### Describe the bug

When a user chooses to hide a token, its balance becomes undetectable in the swaps feature, leading to swaps being unavailable and a message indicating an insufficient balance being displayed.
Following a fresh installation, if a user decides not to import tokens, swaps involving non-native tokens become unavailable too.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/9511ad3d-c1b2-4d5d-a02b-9306f8942654

https://github.com/user-attachments/assets/45698081-4ff6-415f-b4e3-dac22c985ab5

### Steps to reproduce

1. Hide a token
2. Start swap for hidden token
OR
1. Install the extension
2. Do not import tokens
3. Start swap for non-native token
4. See 'Insufficient balance' and 0 balance on the confirmation screen

### Detection stage

In production (default)

### Version

v12.0.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by am3443** [comment]
This is existing behavior, not a bug. Can be closed.
