### ISSUE TITLE
[Bug]: Incorrect warning message shown when there is an insufficient balance for a swap, errors in the console

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26341]
### Describe the bug

When there is an insufficient balance for a swap, users encounter a misleading warning message stating "No quotes available," instead of a more accurate indication of the balance issue.
This issue arises because the amount does not automatically reset to zero when a user selects a different token, leading to an insufficient balance problem.

### Expected behavior

The amount should automatically reset to zero whenever a token is switched and correct warning message should be displayed, to ensure clarity and prevent any balance discrepancies.

### Screenshots/Recordings

https://github.com/user-attachments/assets/77697d2b-b1c5-4cbb-b385-173a86829be6

<img width="520" alt="Screenshot 2024-08-05 at 01 23 30" src="https://github.com/user-attachments/assets/20cebca5-12a4-45d2-a0db-b5478049994c">

https://github.com/user-attachments/assets/91ca948c-0f6f-4b36-8132-6169fd887ef2

Correct 'Insufficient balance' message that should be displayed:

<img width="354" alt="Screenshot 2024-08-05 at 01 32 46" src="https://github.com/user-attachments/assets/1267304f-6255-4b59-b0ea-7c1b91d12763">

### Steps to reproduce

1. Start swap for any token, choose amount
2. Switch to the token with a smaller balance than selected amount

### Detection stage

In production (default)

### Version

v11.16.16, v12.0.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by Sentini14** [comment]
[CSV.csv](https://github.com/user-attachments/files/16517745/CSV.csv)

**Comment by desi** [comment]
In trying to recreate this I get a message that says "Insufficient Balance" which seems like it is the correct message. However, sometimes I get the "Error fetching quotes" message which I assume is not related. I think this bug can be closed.
