### ISSUE TITLE
web3 injection failed

### ISSUE THREAD

**Issue by nicos99** [MetaMask/metamask-extension#2634]
I'm using MetaMask 3.12.1 with FireFox "Quantum" (57.0.1) (64 bits) on Windows 10 64 bits.
There is an error in the FireFox console each time a web page is loaded: "SyntaxError: An invalid or illegal string was specified" at inpage.js:10788, see the full call-stack below. As a consequence (I guess) the web3 object is undefined !

I have the same problem on an other similar PC and on a XP VM with FireFox ESR (52.5.0) (32 bits).

- [116]</PostMessageStream.prototype._write
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/inpage.js:10788:3
- PostMessageStream
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/inpage.js:10744:3
- [1]</<
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/inpage.js:25:22
- [1]<
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/inpage.js:2:2
- s
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/inpage.js:1:246
- e
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/inpage.js:1:425
- (anonyme)
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/inpage.js:1:11
- setupInjection
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/contentscript.js:40:5
- [1]</<
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/contentscript.js:26:3
- [1]<
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/contentscript.js:2:2
- s
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/contentscript.js:1:246
- e
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/contentscript.js:1:425
- (anonyme)
  - moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/scripts/contentscript.js:1:11
- inject
  - resource://gre/modules/ExtensionContent.jsm:357:18
- next
  - self-hosted:1188:9

**Comment by danfinlay** [comment]
May be related to #2736. Is this still happening, or was this just when a backend provider was unavailable?

**Comment by nicos99** [comment]
Yes, I still have the issue today with MetaMask 3.13.3. I'm connected to the main net.

**Comment by nicos99** [comment]
it turns out that this issue is related to the fact that I used a file for my tests instead of an url as it is now well explained in the documentation :
> Due to browser security restrictions, we can't communicate with dapps running on file://. Please use a local server for development. 

Sorry for that, all is working fine now on FireFox 58.0.2 with MataMask 4.2.0 and a webserver for my tests
