### ISSUE TITLE
Fix "Test Snap Signature Insights tests Signature Insight..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26369]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/95137/workflows/8b3a8fa0-4ac5-4bac-97cb-7073ee45dfbb/jobs/3540796/tests

**Comment by sunobun** [comment]
Fix it

**Comment by hjetpoluru** [comment]
Fixed in the PR - https://github.com/MetaMask/metamask-extension/pull/26449
