### ISSUE TITLE
firefox error using locally built metamask instance

### ISSUE THREAD

**Issue by saneletm** [MetaMask/metamask-extension#2640]
MetaMask

    Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
    Reading manifest: Error processing externally_connectable: An unexpected property was found in the WebExtension manifest.

Location
    /metamask-extension-master/dist/firefox/
Extension ID
    webextension@metamask.io
Internal UUID
    196319ec-3a5e-4efe-9413-c327a770d874Manifest URL

#### System
  * firefox version 57.0.1 64 bit on 
  * Ubuntu 16.04 64 bit

#### Steps
  * downloaded the metamask repo, 
  * unzipped and cd to it, 
  * run `npm run dist`, hopefully successful
  * on firefox on the address bar, type: config:debugging
  * click `Load temporary Add-on`
  * upload  `/metamask-extension-master/dist/firefox/manifest.json`
  * click `open`

### Is this a known issue?

**Comment by danfinlay** [comment]
What version of MetaMask is this? Are you still having this issue?

We have enough people using Firefox with the same build folder as you, that this seems strange.

**Comment by danfinlay** [comment]
You might try editing your `manifest.json` file to remove whatever is the key in externally_connectable that is breaking the build.

**Comment by saneletm** [comment]
I just checked out MetaMask from github a few minutes ago and reproduced the same error.  I will mess with this a bit and see if I find some clue.... I might try to see if I can do this on a different machine/firefox version, and will update this with my findings

**Comment by saneletm** [comment]
## Somehow my locally built MetaMask is conflicling with my previously installed MetaMusk plugin, I'll try to find a solution
------------------------------------------------------------------------------------------------------------------------
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  frame:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. www.uport.me:38:9
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-UyDAeH2YFIYaIX42KFpyOLMwoB8' https://notifications.google.com 'unsafe-eval' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com”). Source: (function e(t,n,r){function s(o,u){if(!n.... widget:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: (function e(t,n,r){function s(o,u){if(!n.... 2640:1
TypeError: (intermediate value).search is not a function sh.7a295a410262af12dfaaa96a.html:1:16704
No matching message handler for the given recipient. MessageChannel.jsm:703
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  download:38:9
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: (function e(t,n,r){function s(o,u){if(!n.... metamask-extension:1
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  2:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. developer.uport.me:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. 30060883:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  connector.html:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  sh.7a295a410262af12dfaaa96a.html:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  21176:38:9
TypeError: (intermediate value).search is not a function sh.7a295a410262af12dfaaa96a.html:1:16704
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: (function e(t,n,r){function s(o,u){if(!n.... issues:1
TypeError: (intermediate value).search is not a function sh.7a295a410262af12dfaaa96a.html:1:16704
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  0:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  rs=AHGWq9Azbe-4XILHpAIDQFqZJh4eDQ7Ajw:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. 0:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  rs=AHGWq9Azbe-4XILHpAIDQFqZJh4eDQ7Ajw:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  jn:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  dn:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  postmessageRelay:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  blank:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  hscv:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  postmessageRelay:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  hscv:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  postmessageRelay:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  proxy.html:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  client:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  client:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  frame2:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  frame2:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  frame:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. www.uport.me:38:9
No matching message handler for the given recipient. MessageChannel.jsm:703
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  download:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  2:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. developer.uport.me:38:9
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.  background.js:58065:7
console.trace():  background.js:58071
	[394]</EventEmitter.prototype.addListener moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:58071:9
	addListener moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:2943:5
	createEthFilterMiddleware moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:51241:3
	setupProviderConnection moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:5947:30
	setupUntrustedCommunication moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:5905:7
	connectRemote moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:301:7
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. 30060883:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  connector.html:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  sh.7a295a410262af12dfaaa96a.html:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  21176:38:9
TypeError: (intermediate value).search is not a function sh.7a295a410262af12dfaaa96a.html:1:16704
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.  background.js:58065:7
	[394]</EventEmitter.prototype.addListener moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:58065:7
	subscribe moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:73404:7
	ObsStoreStream moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:73493:5
	asStream moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:73470:10
	setupPublicConfig moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:5968:12
	setupUntrustedCommunication moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:5906:7
	connectRemote moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:301:7
console.trace():  background.js:58071
	[394]</EventEmitter.prototype.addListener moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:58071:9
	subscribe moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:73404:7
	ObsStoreStream moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:73493:5
	asStream moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:73470:10
	setupPublicConfig moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:5968:12
	setupUntrustedCommunication moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:5906:7
	connectRemote moz-extension://0b98cb17-0cb5-46c0-a2ec-2271ff7760eb/scripts/background.js:301:7
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  0:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  rs=AHGWq9Azbe-4XILHpAIDQFqZJh4eDQ7Ajw:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. 0:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  rs=AHGWq9Azbe-4XILHpAIDQFqZJh4eDQ7Ajw:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  jn:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  dn:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  postmessageRelay:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  blank:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  hscv:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  postmessageRelay:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  hscv:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  postmessageRelay:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  proxy.html:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  client:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  client:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  frame2:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  frame2:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.  frame:38:9
Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again. www.uport.me:38:9
TypeError: (intermediate value).search is not a function sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
Attempt to set a forbidden header was denied: Connection  805599773-lcs_client_bin.js:99:385
TypeError: (intermediate value).search is not a function sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  jquery.min.js:4:25244
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
SyntaxError: An invalid or illegal string was specified  inpage.js:10807
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704

**Comment by saneletm** [comment]
I think the conflict comment is just my issue.... I am still trying to chase the underlying issue

**Comment by saneletm** [comment]
### I can't figure this  out yet..... by the way.... the plugin looks like it still  works fine. Here is a log from the browser debug: 
--------------------------------------
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.  background.js:58065:7
	[394]</EventEmitter.prototype.addListener moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:58065:7
	addListener moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:2943:5
	createEthFilterMiddleware moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:51241:3
	setupProviderConnection moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:5947:30
	setupUntrustedCommunication moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:5905:7
	connectRemote moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:301:7
console.trace():  background.js:58071
	[394]</EventEmitter.prototype.addListener moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:58071:9
	addListener moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:2943:5
	createEthFilterMiddleware moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:51241:3
	setupProviderConnection moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:5947:30
	setupUntrustedCommunication moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:5905:7
	connectRemote moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:301:7
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.  background.js:58065:7
	[394]</EventEmitter.prototype.addListener moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:58065:7
	subscribe moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:73404:7
	ObsStoreStream moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:73493:5
	asStream moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:73470:10
	setupPublicConfig moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:5968:12
	setupUntrustedCommunication moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:5906:7
	connectRemote moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:301:7
console.trace():  background.js:58071
	[394]</EventEmitter.prototype.addListener moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:58071:9
	subscribe moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:73404:7
	ObsStoreStream moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:73493:5
	asStream moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:73470:10
	setupPublicConfig moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:5968:12
	setupUntrustedCommunication moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:5906:7
	connectRemote moz-extension://982f4b5d-e8e5-4598-8f4e-149afde8c54d/scripts/background.js:301:7
Error: aa  rs=AGyH-Fuynni_o6tthz48-hcSloKFjCNXKA:1536:135
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it.  hscv
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  www.infinitiusa.com:14
Error: aa  rs=AGyH-Fuynni_o6tthz48-hcSloKFjCNXKA:1536:135
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it.  hscv
Attempt to set a forbidden header was denied: Connection  805599773-lcs_client_bin.js:99:385
Attempt to set a forbidden header was denied: Connection  805599773-lcs_client_bin.js:99:385
TypeError: (intermediate value).search is not a function sh.7a295a410262af12dfaaa96a.html:1:16704
TypeError: (intermediate value).search is not a function  sh.7a295a410262af12dfaaa96a.html:1:16704

**Comment by danfinlay** [comment]
The error message tells you what the problem is there. You can only have one web3 extension enabled at once without unpredictable results.
