### ISSUE TITLE
[e2e] Fix flaky SIWE tests

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#26445]
### What is this about?

Fix flaky tests
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/95685/workflows/1a74bc2d-b031-4316-b236-8968c487363d/jobs/3562383/tests

![Image](https://github.com/user-attachments/assets/c50e9d1d-a563-4501-8236-dc56f16484ae)

Reply to thread: https://consensys.slack.com/archives/CTQAGKY5V/p1723728992741969?thread_ts=1723717063.283689&cid=CTQAGKY5V

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
