### ISSUE TITLE
[e2e] Fix flaky Redesign Signature Navigation tests

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#26446]
### What is this about?

Fix flaky tests
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/95522/workflows/70e8aedf-6722-4beb-9a18-79fa2f3e4787/jobs/3555814/tests

See bottom failed test in screenshot: 
![Image](https://github.com/user-attachments/assets/0ebd203f-07cd-4c0a-935a-aa62b747f0f7)

Reply to thread: https://consensys.slack.com/archives/CTQAGKY5V/p1723728992741969?thread_ts=1723717063.283689&cid=CTQAGKY5V

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by pnarayanaswamy** [comment]
Cannot reproduce on CI or locally , will tackle it if we see it again.
