### ISSUE TITLE
[Bug]: Help modal buttons have wrong size

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26452]
### Describe the bug

The buttons within the help modal appear to be of an unexpected size.

### Expected behavior

-

### Screenshots/Recordings

<img width="503" alt="Screenshot 2024-08-15 at 14 59 08" src="https://github.com/user-attachments/assets/ea8b6bfb-6921-4341-b5e9-2b4621d3dd31">

### Steps to reproduce

1. Install MetaMask extension

### Detection stage

In production (default)

### Version

v12.1.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Closed here https://github.com/MetaMask/metamask-extension/pull/26519

**Comment by georgewrmarshall** [comment]
Confirmed fix

<img width="627" alt="Screenshot 2024-08-21 at 2 23 29 PM" src="https://github.com/user-attachments/assets/a660ce56-f63d-4c4a-8c5c-8f8e49d01f11">
