### ISSUE TITLE
Feature request: allow drop-down window to remain open (or not clear inputs) when it loses focus

### ISSUE THREAD

**Issue by tinybike** [MetaMask/metamask-extension#2646]
I think it would be great if MetaMask had a setting to make the little drop-down window either:
- stay open when it loses focus, or
- not clear its input fields when it closes.

Rationale: I use MetaMask regularly, and often I find myself needing to copy-and-paste both an address _and_ an amount into the send dialogue.  However, MetaMask loses focus when I go to copy the second quantity (since it's usually off of some website that I have open in Chrome), and then the address is cleared.

**Comment by vicnaum** [comment]
Yeah, same problem - hard to copy-paste two things

**Comment by danfinlay** [comment]
This is a feature request for browser vendors, we have no control over it. We're going to add the ability to open in new tab to mitigate this frustration. Closing for now, but be assured this is being worked on. #2768
