### ISSUE TITLE
Hi, I need some help to reïnstall my metamask

### ISSUE THREAD

**Issue by crypwin** [MetaMask/metamask-extension#2648]
After deleting my cookies and when restarting metamask, it was asking my 12 seed words.  (import seed)
After doing this I got the message that the seed was invalid.  

When I got my seed words the first time when  I installed the plugin in my chrome browser I have copied and pasted the seed words into a text file and saved it on a usb stick.

I am 100% sure that my password and the seed that I have saved is correct.

Thank you for reading this, I hope someone can help me...   I have asked this question at the help supportdesk too but I didn't get answer.  I have ETH and tokens in this app. Can someone help me?

Crypwin

**Comment by brandoncurtis** [comment]
Make sure that everything is exact and that there isn't any extraneous whitespace or punctuation before, between, or after the seed phrase words.  The entire phrase should be on a single line, with a single space between each word.

**Comment by crypwin** [comment]
Hi, thank you for your help!  I have placed the words on online and I saw that there was one space too much, and after deleting it, it works!
But it doesn't show a second account that I have made in metamask itself and where I stored tokens.  I have only the address of this account, no keys, because I was presuming that metamask would save this all, but apparently, it doesn't.  Now I can see my tokens on the website where I purchased them, because of the site synchronizing with the account, but I can't use the tokens because I have imported them in my metamask.  How can I restore this account, not having a private key ?  Thank You  so much for your help.

**Comment by brandoncurtis** [comment]
Try clicking on the "create new account" button and it should create that second account!

MetaMask uses a system called a "Hierarchical Deterministic wallet" (HD wallet).  From a single seed, it can generate an unlimited number of accounts.  You can read a little more about that here: https://github.com/MetaMask/metamask-extension/issues/2641#issuecomment-350520614

**Comment by crypwin** [comment]
Hi Brandon,
That worked!  I don't know how to thank You but your really made my day!!!!
Thank you soooo much!!!

**Comment by brandoncurtis** [comment]
You're very welcome!
