### ISSUE TITLE
[Bug]: Unable to Transfer From Tokens in test dapp

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26481]
### Describe the bug

Unable to Transfer from tokens in the test dapp. 

### Steps to reproduce

I followed the steps in the e2e test scenario (test/e2e/tests/tokens/increase-token-allowance.spec.js)

Below are the commands I used to execute the test scenario:-
yarn
yarn build:test:webpack
ENABLE_MV3=false yarn test:e2e:single test/e2e/tests/tokens/increase-token-allowance.spec.js --browser=chrome --debug --leave-running

### Error messages or log output

<img width="1695" alt="Screenshot 2024-08-16 at 1 31 48 PM" src="https://github.com/user-attachments/assets/02a2189b-4939-4628-874e-2556001f0348">

_No response_

### Detection stage

On the development branch

### Version

12.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gauthierpetetin** [comment]
Notes from tirage session:
- If this is a flaky test, it could be due to a race condition, where the "Approve" transaction isn't yet accepted when we try to send the "TransferFrom" transaction

**Comment by hjetpoluru** [comment]
Closing this ticket as its expected behavior. thanks @seaona for clarifying this one for me.
