### ISSUE TITLE
Help  i have 20  problems with pending transactions

### ISSUE THREAD

**Issue by poetarojo** [MetaMask/metamask-extension#2649]
![problema](https://user-images.githubusercontent.com/34245563/33563924-80f4ed98-d919-11e7-9ed7-d1e27d4f732f.jpg)

I'm afraid this will bring unnecessary expenses. please help. 

![problem2](https://user-images.githubusercontent.com/34245563/33563939-887763ca-d919-11e7-8adc-caf4684f156f.jpg)

**Comment by tmashuang** [comment]
The current transaction number that is pending, waiting to get mined is 59. Judging from your screenshots. There are more transactions that are waiting to get mined? I would like to view your transactions logs to further investigate. Please submit your state logs to https://support.metamask.io. Here's a guide to state logs, https://support.metamask.io/kb/article/15-copying-state-logs

**Comment by tmashuang** [comment]
Users have been report similar issues and I have determined that our provider to the Ethereum network is out of sync.

Users with similar issues have better experience with syncing MetaMask with MyEtherWallet and used their nodes to send transactions through their provider. Also, some users have reported using https://mainnet.infura.io and adding it as New RPC URL under Custom RPC in the network dropdown in Metamask to submit transactions.

Solutions are being provided on #2655.

**Comment by danfinlay** [comment]
These failures were related to the great kitty backlog of 2017. This issue should be mostly mitigated now, let us know if you have these problems again.
