### ISSUE TITLE
Coinbase sent Eth not showing up in Metamask wallet

### ISSUE THREAD

**Issue by TheCoinsigliere** [MetaMask/metamask-extension#2651]
I just created an MetaMask and send some ETH from coinbase to it to buy some cryptokitties.

It's been more than an our and the ETH only says: Pending on coinbase.

https://etherscan.io/address/0x83f1FDCA92707E48DB66BbC815DAEeBA3C42ad99

The txn was sent: 12/4/2017 7:19 PM

**Comment by tmashuang** [comment]
Seems this is due has been resolved since the incoming transaction was successfully mined. Closing, will reopen if this is still and issue.
