### ISSUE TITLE
Settings menu are not shown completely in Firefox 57

### ISSUE THREAD

**Issue by abitrolly** [MetaMask/metamask-extension#2652]
I can't see the end of Settings page. It doesn't show up and there is no scrollbar or "View Source" options. 

![image](https://user-images.githubusercontent.com/8781107/33576944-80a8455e-d952-11e7-8423-543499b39a2b.png)

Firefox 57. Fedora 27.

**Comment by danfinlay** [comment]
This will be scrollable very soon in our new updated UI. Leaving open until then.

**Comment by abitrolly** [comment]
Still the problem with 3.13.3

**Comment by bdresser** [comment]
fixed in the new UI
