### ISSUE TITLE
Error "replacement transaction underpriced"

### ISSUE THREAD

**Issue by Tigerfood** [MetaMask/metamask-extension#2653]
I have an error that makes me unable to do anything.
I use Metamask mostly for EtherDelta and try to buy or sell other coins but everything i try to do it fails. I get message "replacement transaction underpriced".

I tried changing to test server and back to main server but it didn't solve.
I also tried uninstall metamask and reinstall it and it didn't fix this.
I tried to up the gas price and it didn't help.

Has anyone the same error? Any way to solve this?
My adress: 0x58292B41EAba1529B2dB5aDC1C6aF8672D32c9C2
Logs: https://mega.nz/#!ihR3yAYC!G0Ss5zh78YhO_Efef-OOIYSII9xJpJv5peunjnVl1hk

![error-1](https://user-images.githubusercontent.com/34252426/33577181-e189b900-d94a-11e7-9ba8-8f90aec1f084.jpg)

Have metamask 3.12.1.

**Comment by tmashuang** [comment]
Currently, the network has a backlog of transactions, ~140,000, so transactions are waiting to get mined. Will continue to monitor network. I assume the initial transaction hasn't been mined yet.

**Comment by tmashuang** [comment]
Edit: ~14k pending transactions.

**Comment by Tigerfood** [comment]
same shit transaction underpriced ,,,,

**Comment by tmashuang** [comment]
https://etherscan.io/tx/0x29c82cc315632c2ee2117658d6dd582763d7fae0075d7f5ccce5c35a5feaccc1 this transaction is still pending. Are you trying to send the same transaction over again, or are the following transactions different?

**Comment by tmashuang** [comment]
Users have been report similar issues and I have determined that our provider to the Ethereum network is out of sync.

Users with similar issues have better experience with syncing MetaMask with MyEtherWallet and used their nodes to send transactions through their provider. Also, some users have reported using https://mainnet.infura.io and adding it as New RPC URL under Custom RPC in the network dropdown in Metamask to submit transactions.

Solutions are being provided on #2655.

**Comment by tmashuang** [comment]
Closing to consolidate issues and solution. Refer to #2655.
