### ISSUE TITLE
Hi Metamask - A little challenge wiht Metamask and token.

### ISSUE THREAD

**Issue by JoeMalone** [MetaMask/metamask-extension#2656]
Hi Metamask

I am having an issue concerning my smart contract generated via Token Factory.

First I cannot add my Token to my Metamask account via add token with the right address, nothing happens.

I am running MetaMask on a mac...

Further, I cannot see my balance when I click watch at my wallet at ethereum.org.

I can now only see my token name and then balance is only 00000000000000000 
when it should be 21000000

I have looked through many videos on youtube and on stack overview but no helpful info.

Thanks in advance and for a good product.

/ Kind regards Joe.

**Comment by k06a** [comment]
Same for me!

**Comment by tmashuang** [comment]
What were the parameters of the token contract, specifically the total supply and decimal precision?

**Comment by JoeMalone** [comment]
Total supply 21 million and decimal 18 like normal eth contract...
I just don't get what is wrong, I think I should have just uploaded my own contract instead of standard human contract at token factory ?...

Thanks

**Comment by JoeMalone** [comment]
Hi and thanks for reply.

Ok, so 3 decimals it is.

The thing is that I have deployed my contract and it is up and running...

But I cannot change a contract when first published at etherscan right ?

Then I just need to change the decimals to 3 instead of 18.

Thanks 

/ J.

**Comment by JoeMalone** [comment]
Can you help me Thomas, if I send you the contract name, normally I only work in Swift, and if this does not work I will need to make a new contract so I can call the custom token and totalsupply and transfer it to another eth address.

Thanks in advance

/ Joe.

**Comment by JoeMalone** [comment]
I am trying to transfer tokens from this standard contract, please see below image, I have used Token Factory as generator...
The site says it has been transferred but nothing shows up...?

![screen](https://user-images.githubusercontent.com/17169318/33715760-f7de5188-db53-11e7-8c05-0ad263c134e7.png)
