### ISSUE TITLE
Fix "Test Snap Metrics tests snap uninstall metric" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26575]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/96587/workflows/b7beffde-c70c-4ee8-9f22-3d840f6e8a3f/jobs/3595672/tests

```
TimeoutError: Waiting until element is enabled
Wait timed out after 10189ms
  (Ran on CircleCI Node 1 of 10, Job test-e2e-firefox-flask)
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![image](https://github.com/user-attachments/assets/2bc9e415-990f-41fe-a2a6-1a8b870ae0ed)

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
