### ISSUE TITLE
[FUNDS LOCKED] "Sorry, We are unable to locate the Transaction Hash" on etherscan when sending transaction through metamask

### ISSUE THREAD

**Issue by jeffchang138** [MetaMask/metamask-extension#2657]
*  Expected Behavior
Send a transaction through metamask, click link to transaction, view on etherscan, transaction copletes
  *  Actual Behavior
Send a transaction through metamask, click link to transaction, see "Sorry, We are unable to locate the Transaction Hash" for example https://etherscan.io/tx/0x2bade01159ebcade4092fd4d2460a6ddabff69b6696986c6ab6359d7f98a7778

Transaction never sends.
My account has no pending transactions on etherscan, I've tried with different gas limits (between 25-1000 gwei, and different amounts of eth). Previously was using it for crypto kitties but now normal transactions show the same thing. Let me know if any other info can be useful

  *  Browser Used
Chrome, Firefox (doesn't work on fresh install on both)
  *  Operating System Used
MacOS 10.12.6

Related reddit threads:
https://www.reddit.com/r/CryptoKitties/comments/7hl0nv/sorry_we_are_unable_to_locate_the_transaction/
https://www.reddit.com/r/CryptoKitties/comments/7hlb71/in_progressunable_to_locate_transaction_hash/
https://www.reddit.com/r/CryptoKitties/comments/7hkpju/at_this_point_the_game_is_unplayable_and_im/

**Comment by tmashuang** [comment]
Please submit a ticket to https://support.metamask.io with your transaction/state logs. Here's a guide to obtaining these logs. https://support.metamask.io/kb/article/15-copying-state-logs

**Comment by jeffchang138** [comment]
Submitted ticket #MET00267479. This seems to be a widespread issue, multiple people reporting it and nobody has a working solution (see reddit threads).

**Comment by tmashuang** [comment]
Users have been report similar issues and I have determined that our provider to the Ethereum network is out of sync.

Users with similar issues have better experience with syncing MetaMask with MyEtherWallet and used their nodes to send transactions through their provider. Also, some users have reported using https://mainnet.infura.io and adding it as New RPC URL under Custom RPC in the network dropdown in Metamask to submit transactions.

Solutions are being provided on #2655.

**Comment by tmashuang** [comment]
Closing in favor of #2655.
