### ISSUE TITLE
WArnings and Timeouts on ALL transactions out

### ISSUE THREAD

**Issue by scottie** [MetaMask/metamask-extension#2658]
Can send ETH in instantly no issues no worries.
but cant send out, all i get is warnings and fails.
Litteraly cant send anywhere, but i can keep sending in ....
https://i.imgur.com/5jJa40E.png
https://i.imgur.com/FbAS4vF.png
https://i.imgur.com/pmFgzBg.png

**Comment by scottie** [comment]
https://i.imgur.com/66rnSbz.png

**Comment by scottie** [comment]
fix from guy in discord:
Looks like the main metamask node is borked. Thats why my transactions didnt show up in the mempool and timed out. Changing node fixed it right away. Go into metamask settings and change RPC-URL to https://mainnet.infura.io/

**Comment by tmashuang** [comment]
Users have been report similar issues and I have determined that our provider to the Ethereum network is out of sync.

Users with similar issues have better experience with syncing MetaMask with MyEtherWallet and used their nodes to send transactions through their provider. Also, some users have reported using https://mainnet.infura.io and adding it as New RPC URL under Custom RPC in the network dropdown in Metamask to submit transactions.

Solutions are being provided on #2655.

**Comment by tmashuang** [comment]
Closing in favor of #2655
