### ISSUE TITLE
Metamask wallet pending transactions

### ISSUE THREAD

**Issue by GreenMeansGO** [MetaMask/metamask-extension#2659]
So Forgive me Im pretty new to this, my metamask wallet keeps failing to send transactions

Error: rpc error with payload....insufficient funds gas*price + value

I have more than enough eth in the account to cover the transaction...

Looking down my transactions I have transactions pending from which i believe i didnt provide enough gwei (2 was put) which I believe has to do with the issue.

Ive spent 2 hours trying to resolve this issue..please help

state log is 296 pages....

[MetaMask State Logs.txt](https://github.com/MetaMask/metamask-extension/files/1529389/MetaMask.State.Logs.txt)

Will gladly tip ETH from my fixed wallet :)

**Comment by tmashuang** [comment]
Users have been report similar issues and I have determined that our provider to the Ethereum network is out of sync.

Users with similar issues have better experience with syncing MetaMask with MyEtherWallet and used their nodes to send transactions through their provider. Also, some users have reported using https://mainnet.infura.io and adding it as New RPC URL under Custom RPC in the network dropdown in Metamask to submit transactions.

Solutions are being provided on #2655.

**Comment by tmashuang** [comment]
Closing in favor of #2655
