### ISSUE TITLE
[Signature Redesign] fixes to PermitSingle and PermitTransferFrom simulation

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#26591]
### What is this about?
Within the estimated changes section, we should:
- display the token address instead of verifyingContract address
- display the amount and fiat conversion information

### Scenario

1. Go to app.uniswap.org/swap
2. Have some balance of USDT on Polygon
3. Switch to Polygon (https://app.uniswap.org/swap?chain=polygon)
4. Try swapping your USDT to something
5. Notice the PermitSingle signature request on MM

### Design

Current UI:
<img width="365" alt="Screenshot 2024-08-21 at 14 31 53" src="https://github.com/user-attachments/assets/62cf6150-4ba2-4f77-b095-1f8235a2c1a7">

Desired UI:
![Screenshot 2024-08-14 at 15 28 03](https://github.com/user-attachments/assets/ec721639-50d9-422c-a30d-7ef77f38fc77)

[Figma file](https://www.figma.com/design/wcXUl6AH5KNFwKdAIv49kh/Confirmation-redesign-V5?node-id=3826-12006&t=KbkyZM8KoJqKNSCo-0)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

- Uniswap docs: https://docs.uniswap.org/contracts/permit2/reference/allowance-transfer

**Comment by digiwand** [comment]
Solution is combined with PermitTransferFrom and PermitBatchTransferFrom support
