### ISSUE TITLE
[Bug]: migration PR for field versionFileETag deleted from PPOMController is missing

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#26604]
### Describe the bug

The [PR](https://github.com/MetaMask/metamask-extension/pull/25136) removed field `versionFileETag` from `PPOMController`. We should write a migration PR to delete it from the state.

### Expected behavior
NA

### Screenshots/Recordings
NA

### Steps to reproduce
NA

**Comment by Gudahtt** [comment]
Apologies, this was reported by me but I believe it to be a false positive because the PPOMController is effectively deleting this key in the constructor: https://github.com/MetaMask/ppom-validator/blob/873a7c65399e7fb4f03f18672a8dae65ba4d5a84/src/ppom-controller.ts#L264
