### ISSUE TITLE
Metamask Error 328 - rpc error with playload 

### ISSUE THREAD

**Issue by Darehwinston** [MetaMask/metamask-extension#2661]
I am having issues with my metamask, these include the following: 
- unable to deposit tokens into ether delta
- unable to deposit ethereum into ether delta

I have over 1.3 ether in there, and it keeps giving me the above erro message. No transactions are created either. 

I have done the following to resolve, so luck so far: 
- deleted metamask from chrome and installed again 
- deleted metamask, restarted my computer, installed again
- I have adblock, made sure it is not running on any etherdelta pages, nor metamask pages

Please advice. 
Thank you kindly. 
DH

**Comment by Darehwinston** [comment]
<img width="350" alt="screen shot 2017-12-04 at 10 46 34 pm" src="https://user-images.githubusercontent.com/34263725/33593637-1bf652ac-d945-11e7-9078-87f107f53299.png">

**Comment by Darehwinston** [comment]
This is the address should you wish to investigate further: 
0x9Ee1830ff376758c5Ecc7FB465f3b14d64116d71

**Comment by k06a** [comment]
Same problem here: https://github.com/MetaMask/metamask-extension/issues/2655

**Comment by ricardo-ferenz** [comment]
Ive also been trying to resolve this for the last 12 hours...

Ticket number: #MET00267438

Please assist as a matter of importance.

**Comment by Liviulsc** [comment]
I have also the same problem for over 24h. 

Added a ticket on support.metamask.io yesterday and one today and didn't get any respond.
#MET00267629
#MET00267396 

Can't deposit Eth to Etherdelta
Can't cancel old orders on Etherdelta
Can't send Eth to another wallet

**Comment by Darehwinston** [comment]
Guys, if any of you gets a response, please post the solution here to help us all.

**Comment by vishaluae** [comment]
Crypto Kitties are clogging the network

**Comment by sandberg420** [comment]
Same problem here, but there is no one its happening to everyone because there are new sales every second.

**Comment by Liviulsc** [comment]
Here is the answer for Metamask support:


Hello, 

There is currently a combination of both a backlog in pending transactions on the network as well as rising competition for gas prices with CryptoKitties. Unfortunately this is causing some transactions with lower gas prices to take longer to process or even fail. Unfortunately there is little to be done about this besides waiting for any pending transactions to go through or show as failed/rejected. This waiting period can take up to 24 hours during congested network times such as this. 

For your refernece in using gas with Dapps such as CryptoKitties, Ether Delta and others: https://support.metamask.io/kb/article/25-transaction-submission-best-practices-on-etherdelta-and-dapps/

**Comment by rshuk** [comment]
Perhaps, this is not the right forum to ask this question but what can be possibly be done about CryptoKittens? Their transactions are too frequent and people involved with them continue to pay higher gas price thus increasing average gas price for the transactions.

**Comment by JesseBusman** [comment]
I have the same problem, I can't send any transactions with MetaMask anymore.
I installed the Firefox addon with the same seed words, same problem. Can't do anything.

**Comment by Liviulsc** [comment]
You can find the solution here: 
https://github.com/MetaMask/metamask-extension/issues/2655

Fix:  
1. Close chrome 
2. Open BRAVE browser (you can take it from metamask site)
3. Login to BRAVE metamask using the 12 WORDS SEED. 
4. Change in MetaMask -  settings - Custom RPC connection - to https://mainnet.infura.io - Click Save
5. Do the transfer using minimum 25 GWEI

**Comment by tmashuang** [comment]
Closing in favor of #2655

**Comment by Darehwinston** [comment]
Thank you Liviulsc. I tried that, unfortunately I continue to have the same issue.

**Comment by Liviulsc** [comment]
Worked for me, but I've still waited 3-4h for the transfer on 12 GWEI
