### ISSUE TITLE
I keep getting transaction failures and warnings

### ISSUE THREAD

**Issue by OrbisNL** [MetaMask/metamask-extension#2663]
{
  "metamask": {
    "isInitialized": true,
    "isUnlocked": true,
    "isMascara": false,
    "rpcTarget": "https://rawtestrpc.metamask.io/",
    "identities": {
      "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720": {
        "address": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720",
        "name": "Account 1"
      }
    },
    "unapprovedTxs": {},
    "noActiveNotices": true,
    "frequentRpcList": [
      "https://mainnet.infura.io/"
    ],
    "addressBook": [],
    "tokenExchangeRates": {},
    "coinOptions": {},
    "provider": {
      "type": "mainnet",
      "rpcTarget": "https://mainnet.infura.io/metamask"
    },
    "network": "1",
    "accounts": {
      "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720": {
        "code": "0x",
        "nonce": "0x2",
        "balance": "0x4195bb42e63a000",
        "address": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720"
      }
    },
    "currentBlockGasLimit": "0x67067f",
    "selectedAddressTxList": [
      {
        "id": 5005824154531113,
        "time": 1512474086834,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720",
          "to": "0x6090a6e47849629b7245dfa1ca21d94cd15878ef",
          "value": "0x2386f26fc10000",
          "data": "0xfebefd6100000000000000000000000000000000000000000000000000000000000000406a3fa238f4f8279458584a46c9bb9b6955b1e375ef4de3d3d490339f9bfd00d000000000000000000000000000000000000000000000000000000000000000039c8ef344efea147c6a0014f8f9f245443f6fdba083af06b76fdc3e05aab46437bb79360bf5067cb20a2ee00cf4700cca17d77805cd8e2698feb7df4ce21298ab154c4ca196ddb72f43c2f4289598f87274e0248c21c3381d24d849c466b8349d",
          "gas": "0x493e0",
          "gasPrice": "0x2540be400",
          "nonce": "0x2",
          "chainId": "0x1"
        },
        "gasPriceSpecified": true,
        "gasLimitSpecified": true,
        "estimatedGas": "0x9eb10",
        "history": [
          {
            "id": 5005824154531113,
            "time": 1512474086834,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720",
              "to": "0x6090a6e47849629b7245dfa1ca21d94cd15878ef",
              "value": "0x2386f26fc10000",
              "data": "0xfebefd6100000000000000000000000000000000000000000000000000000000000000406a3fa238f4f8279458584a46c9bb9b6955b1e375ef4de3d3d490339f9bfd00d000000000000000000000000000000000000000000000000000000000000000039c8ef344efea147c6a0014f8f9f245443f6fdba083af06b76fdc3e05aab46437bb79360bf5067cb20a2ee00cf4700cca17d77805cd8e2698feb7df4ce21298ab154c4ca196ddb72f43c2f4289598f87274e0248c21c3381d24d849c466b8349d",
              "gas": "0x9eb10",
              "gasPrice": "0x4a817c800"
            },
            "gasPriceSpecified": true,
            "gasLimitSpecified": true,
            "estimatedGas": "0x9eb10"
          },
          [
            {
              "op": "replace",
              "path": "/txParams/gasPrice",
              "value": "0x2540be400",
              "note": "confTx: user approved transaction"
            },
            {
              "op": "replace",
              "path": "/txParams/gas",
              "value": "0x493e0"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "approved",
              "note": "txStateManager: setting status to approved"
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/nonce",
              "value": "0x2",
              "note": "transactions#approveTransaction"
            },
            {
              "op": "add",
              "path": "/nonceDetails",
              "value": {
                "params": {
                  "highestLocalNonce": 0,
                  "highestSuggested": 2,
                  "nextNetworkNonce": 2
                },
                "local": {
                  "name": "local",
                  "nonce": 2,
                  "details": {
                    "startPoint": 2,
                    "highest": 2
                  }
                },
                "network": {
                  "name": "network",
                  "nonce": 2,
                  "details": {
                    "baseCount": 2
                  }
                }
              }
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/chainId",
              "value": "0x1",
              "note": "txStateManager: setting status to signed"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "signed"
            }
          ],
          [
            {
              "op": "add",
              "path": "/rawTx",
              "value": "0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000406a3fa238f4f8279458584a46c9bb9b6955b1e375ef4de3d3d490339f9bfd00d000000000000000000000000000000000000000000000000000000000000000039c8ef344efea147c6a0014f8f9f245443f6fdba083af06b76fdc3e05aab46437bb79360bf5067cb20a2ee00cf4700cca17d77805cd8e2698feb7df4ce21298ab154c4ca196ddb72f43c2f4289598f87274e0248c21c3381d24d849c466b8349d26a0e45a34766271f37ec0111ee65b2651e26383b77e79b3718f2139cd81cbbd7d6da046e4826238ae2fa76d63e08d04d56cda02fee3497386a9835d41c95c91250dde",
              "note": "transactions#publishTransaction"
            }
          ],
          [
            {
              "op": "add",
              "path": "/err",
              "value": {
                "message": "Error: [ethjs-rpc] rpc error with payload {\"id\":7861201035799,\"jsonrpc\":\"2.0\",\"params\":[\"0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000406a3fa238f4f8279458584a46c9bb9b6955b1e375ef4de3d3d490339f9bfd00d000000000000000000000000000000000000000000000000000000000000000039c8ef344efea147c6a0014f8f9f245443f6fdba083af06b76fdc3e05aab46437bb79360bf5067cb20a2ee00cf4700cca17d77805cd8e2698feb7df4ce21298ab154c4ca196ddb72f43c2f4289598f87274e0248c21c3381d24d849c466b8349d26a0e45a34766271f37ec0111ee65b2651e26383b77e79b3718f2139cd81cbbd7d6da046e4826238ae2fa76d63e08d04d56cda02fee3497386a9835d41c95c91250dde\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value",
                "stack": "Error: [ethjs-rpc] rpc error with payload {\"id\":7861201035799,\"jsonrpc\":\"2.0\",\"params\":[\"0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000406a3fa238f4f8279458584a46c9bb9b6955b1e375ef4de3d3d490339f9bfd00d000000000000000000000000000000000000000000000000000000000000000039c8ef344efea147c6a0014f8f9f245443f6fdba083af06b76fdc3e05aab46437bb79360bf5067cb20a2ee00cf4700cca17d77805cd8e2698feb7df4ce21298ab154c4ca196ddb72f43c2f4289598f87274e0248c21c3381d24d849c466b8349d26a0e45a34766271f37ec0111ee65b2651e26383b77e79b3718f2139cd81cbbd7d6da046e4826238ae2fa76d63e08d04d56cda02fee3497386a9835d41c95c91250dde\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:57473:26\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85143:9\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16619:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16463:25)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16453:17)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16635:16\n    at resultObj.id (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85125:9)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16753:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16468:17)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16453:17)"
              }
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "failed",
              "note": "txStateManager: setting status to failed"
            }
          ]
        ],
        "nonceDetails": {
          "params": {
            "highestLocalNonce": 0,
            "highestSuggested": 2,
            "nextNetworkNonce": 2
          },
          "local": {
            "name": "local",
            "nonce": 2,
            "details": {
              "startPoint": 2,
              "highest": 2
            }
          },
          "network": {
            "name": "network",
            "nonce": 2,
            "details": {
              "baseCount": 2
            }
          }
        },
        "rawTx": "0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000406a3fa238f4f8279458584a46c9bb9b6955b1e375ef4de3d3d490339f9bfd00d000000000000000000000000000000000000000000000000000000000000000039c8ef344efea147c6a0014f8f9f245443f6fdba083af06b76fdc3e05aab46437bb79360bf5067cb20a2ee00cf4700cca17d77805cd8e2698feb7df4ce21298ab154c4ca196ddb72f43c2f4289598f87274e0248c21c3381d24d849c466b8349d26a0e45a34766271f37ec0111ee65b2651e26383b77e79b3718f2139cd81cbbd7d6da046e4826238ae2fa76d63e08d04d56cda02fee3497386a9835d41c95c91250dde",
        "err": {
          "message": "Error: [ethjs-rpc] rpc error with payload {\"id\":7861201035799,\"jsonrpc\":\"2.0\",\"params\":[\"0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000406a3fa238f4f8279458584a46c9bb9b6955b1e375ef4de3d3d490339f9bfd00d000000000000000000000000000000000000000000000000000000000000000039c8ef344efea147c6a0014f8f9f245443f6fdba083af06b76fdc3e05aab46437bb79360bf5067cb20a2ee00cf4700cca17d77805cd8e2698feb7df4ce21298ab154c4ca196ddb72f43c2f4289598f87274e0248c21c3381d24d849c466b8349d26a0e45a34766271f37ec0111ee65b2651e26383b77e79b3718f2139cd81cbbd7d6da046e4826238ae2fa76d63e08d04d56cda02fee3497386a9835d41c95c91250dde\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value",
          "stack": "Error: [ethjs-rpc] rpc error with payload {\"id\":7861201035799,\"jsonrpc\":\"2.0\",\"params\":[\"0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000406a3fa238f4f8279458584a46c9bb9b6955b1e375ef4de3d3d490339f9bfd00d000000000000000000000000000000000000000000000000000000000000000039c8ef344efea147c6a0014f8f9f245443f6fdba083af06b76fdc3e05aab46437bb79360bf5067cb20a2ee00cf4700cca17d77805cd8e2698feb7df4ce21298ab154c4ca196ddb72f43c2f4289598f87274e0248c21c3381d24d849c466b8349d26a0e45a34766271f37ec0111ee65b2651e26383b77e79b3718f2139cd81cbbd7d6da046e4826238ae2fa76d63e08d04d56cda02fee3497386a9835d41c95c91250dde\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:57473:26\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85143:9\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16619:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16463:25)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16453:17)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16635:16\n    at resultObj.id (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85125:9)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16753:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16468:17)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16453:17)"
        }
      },
      {
        "id": 5005824154531112,
        "time": 1512473730767,
        "status": "rejected",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720",
          "to": "0x6090a6e47849629b7245dfa1ca21d94cd15878ef",
          "data": "0x47872b4241e282e3582449a829f9114ec36a09042db444809e2e4a49bd09b2e39d5c6586000000000000000000000000000000000000000000000000002386f26fc100003c06a7479f0c4bccaa326b56d7cacd3ef4090973b5742f8ee7ea041075244f98",
          "gas": "0x493e0",
          "gasPrice": "0x6fc23ac00",
          "value": "0x0"
        },
        "gasPriceSpecified": false,
        "gasLimitSpecified": true,
        "estimatedGas": "0x493e0",
        "history": [
          {
            "id": 5005824154531112,
            "time": 1512473730767,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720",
              "to": "0x6090a6e47849629b7245dfa1ca21d94cd15878ef",
              "data": "0x47872b4241e282e3582449a829f9114ec36a09042db444809e2e4a49bd09b2e39d5c6586000000000000000000000000000000000000000000000000002386f26fc100003c06a7479f0c4bccaa326b56d7cacd3ef4090973b5742f8ee7ea041075244f98",
              "gas": "0x493e0",
              "gasPrice": "0x6fc23ac00",
              "value": "0x0"
            },
            "gasPriceSpecified": false,
            "gasLimitSpecified": true,
            "estimatedGas": "0x493e0"
          },
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "rejected",
              "note": "txStateManager: setting status to rejected"
            }
          ]
        ]
      },
      {
        "id": 5005824154531111,
        "time": 1512473366741,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720",
          "to": "0x6090a6e47849629b7245dfa1ca21d94cd15878ef",
          "value": "0x2386f26fc10000",
          "data": "0xfebefd6100000000000000000000000000000000000000000000000000000000000000404502936b6fc40ad934f5e440632c2d5d7157ce6d69cfcef05f6c3d1b0ecbef660000000000000000000000000000000000000000000000000000000000000003a8e50af785956d16c8c87d4de62ec32c9c10861c630c868dc1d2561e8cfbae304d3134418ccc3defb7bd7b72d22b2668aac7d1e757ba5a966733daad8d6b7ea4a62d4c11aa73508f85d8614befd57dcd260853f2775a27fe60f736171b7f526a",
          "gas": "0x493e0",
          "gasPrice": "0x2540be400",
          "nonce": "0x2",
          "chainId": "0x1"
        },
        "gasPriceSpecified": true,
        "gasLimitSpecified": true,
        "estimatedGas": "0x9eb10",
        "history": [
          {
            "id": 5005824154531111,
            "time": 1512473366741,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720",
              "to": "0x6090a6e47849629b7245dfa1ca21d94cd15878ef",
              "value": "0x2386f26fc10000",
              "data": "0xfebefd6100000000000000000000000000000000000000000000000000000000000000404502936b6fc40ad934f5e440632c2d5d7157ce6d69cfcef05f6c3d1b0ecbef660000000000000000000000000000000000000000000000000000000000000003a8e50af785956d16c8c87d4de62ec32c9c10861c630c868dc1d2561e8cfbae304d3134418ccc3defb7bd7b72d22b2668aac7d1e757ba5a966733daad8d6b7ea4a62d4c11aa73508f85d8614befd57dcd260853f2775a27fe60f736171b7f526a",
              "gas": "0x9eb10",
              "gasPrice": "0x4a817c800"
            },
            "gasPriceSpecified": true,
            "gasLimitSpecified": true,
            "estimatedGas": "0x9eb10"
          },
          [
            {
              "op": "replace",
              "path": "/txParams/gasPrice",
              "value": "0x2540be400",
              "note": "confTx: user approved transaction"
            },
            {
              "op": "replace",
              "path": "/txParams/gas",
              "value": "0x493e0"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "approved",
              "note": "txStateManager: setting status to approved"
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/nonce",
              "value": "0x2",
              "note": "transactions#approveTransaction"
            },
            {
              "op": "add",
              "path": "/nonceDetails",
              "value": {
                "params": {
                  "highestLocalNonce": 0,
                  "highestSuggested": 2,
                  "nextNetworkNonce": 2
                },
                "local": {
                  "name": "local",
                  "nonce": 2,
                  "details": {
                    "startPoint": 2,
                    "highest": 2
                  }
                },
                "network": {
                  "name": "network",
                  "nonce": 2,
                  "details": {
                    "baseCount": 2
                  }
                }
              }
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/chainId",
              "value": "0x1",
              "note": "txStateManager: setting status to signed"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "signed"
            }
          ],
          [
            {
              "op": "add",
              "path": "/rawTx",
              "value": "0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000404502936b6fc40ad934f5e440632c2d5d7157ce6d69cfcef05f6c3d1b0ecbef660000000000000000000000000000000000000000000000000000000000000003a8e50af785956d16c8c87d4de62ec32c9c10861c630c868dc1d2561e8cfbae304d3134418ccc3defb7bd7b72d22b2668aac7d1e757ba5a966733daad8d6b7ea4a62d4c11aa73508f85d8614befd57dcd260853f2775a27fe60f736171b7f526a26a01fd8e1b25fa1bcf154c5b2c0a84fbd4080246129d9f9838b96a93ec37f5ad0c7a051ccf9bcc53d0e1468521ba63f29be4eb82e791fa034e467bee528c199fda2e8",
              "note": "transactions#publishTransaction"
            }
          ],
          [
            {
              "op": "add",
              "path": "/err",
              "value": {
                "message": "Error: [ethjs-rpc] rpc error with payload {\"id\":7861201035797,\"jsonrpc\":\"2.0\",\"params\":[\"0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000404502936b6fc40ad934f5e440632c2d5d7157ce6d69cfcef05f6c3d1b0ecbef660000000000000000000000000000000000000000000000000000000000000003a8e50af785956d16c8c87d4de62ec32c9c10861c630c868dc1d2561e8cfbae304d3134418ccc3defb7bd7b72d22b2668aac7d1e757ba5a966733daad8d6b7ea4a62d4c11aa73508f85d8614befd57dcd260853f2775a27fe60f736171b7f526a26a01fd8e1b25fa1bcf154c5b2c0a84fbd4080246129d9f9838b96a93ec37f5ad0c7a051ccf9bcc53d0e1468521ba63f29be4eb82e791fa034e467bee528c199fda2e8\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value",
                "stack": "Error: [ethjs-rpc] rpc error with payload {\"id\":7861201035797,\"jsonrpc\":\"2.0\",\"params\":[\"0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000404502936b6fc40ad934f5e440632c2d5d7157ce6d69cfcef05f6c3d1b0ecbef660000000000000000000000000000000000000000000000000000000000000003a8e50af785956d16c8c87d4de62ec32c9c10861c630c868dc1d2561e8cfbae304d3134418ccc3defb7bd7b72d22b2668aac7d1e757ba5a966733daad8d6b7ea4a62d4c11aa73508f85d8614befd57dcd260853f2775a27fe60f736171b7f526a26a01fd8e1b25fa1bcf154c5b2c0a84fbd4080246129d9f9838b96a93ec37f5ad0c7a051ccf9bcc53d0e1468521ba63f29be4eb82e791fa034e467bee528c199fda2e8\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:57473:26\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85143:9\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16619:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16463:25)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16453:17)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16635:16\n    at resultObj.id (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85125:9)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16753:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16468:17)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16453:17)"
              }
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "failed",
              "note": "txStateManager: setting status to failed"
            }
          ]
        ],
        "nonceDetails": {
          "params": {
            "highestLocalNonce": 0,
            "highestSuggested": 2,
            "nextNetworkNonce": 2
          },
          "local": {
            "name": "local",
            "nonce": 2,
            "details": {
              "startPoint": 2,
              "highest": 2
            }
          },
          "network": {
            "name": "network",
            "nonce": 2,
            "details": {
              "baseCount": 2
            }
          }
        },
        "rawTx": "0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000404502936b6fc40ad934f5e440632c2d5d7157ce6d69cfcef05f6c3d1b0ecbef660000000000000000000000000000000000000000000000000000000000000003a8e50af785956d16c8c87d4de62ec32c9c10861c630c868dc1d2561e8cfbae304d3134418ccc3defb7bd7b72d22b2668aac7d1e757ba5a966733daad8d6b7ea4a62d4c11aa73508f85d8614befd57dcd260853f2775a27fe60f736171b7f526a26a01fd8e1b25fa1bcf154c5b2c0a84fbd4080246129d9f9838b96a93ec37f5ad0c7a051ccf9bcc53d0e1468521ba63f29be4eb82e791fa034e467bee528c199fda2e8",
        "err": {
          "message": "Error: [ethjs-rpc] rpc error with payload {\"id\":7861201035797,\"jsonrpc\":\"2.0\",\"params\":[\"0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000404502936b6fc40ad934f5e440632c2d5d7157ce6d69cfcef05f6c3d1b0ecbef660000000000000000000000000000000000000000000000000000000000000003a8e50af785956d16c8c87d4de62ec32c9c10861c630c868dc1d2561e8cfbae304d3134418ccc3defb7bd7b72d22b2668aac7d1e757ba5a966733daad8d6b7ea4a62d4c11aa73508f85d8614befd57dcd260853f2775a27fe60f736171b7f526a26a01fd8e1b25fa1bcf154c5b2c0a84fbd4080246129d9f9838b96a93ec37f5ad0c7a051ccf9bcc53d0e1468521ba63f29be4eb82e791fa034e467bee528c199fda2e8\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value",
          "stack": "Error: [ethjs-rpc] rpc error with payload {\"id\":7861201035797,\"jsonrpc\":\"2.0\",\"params\":[\"0xf90131028502540be400830493e0946090a6e47849629b7245dfa1ca21d94cd15878ef872386f26fc10000b8c4febefd6100000000000000000000000000000000000000000000000000000000000000404502936b6fc40ad934f5e440632c2d5d7157ce6d69cfcef05f6c3d1b0ecbef660000000000000000000000000000000000000000000000000000000000000003a8e50af785956d16c8c87d4de62ec32c9c10861c630c868dc1d2561e8cfbae304d3134418ccc3defb7bd7b72d22b2668aac7d1e757ba5a966733daad8d6b7ea4a62d4c11aa73508f85d8614befd57dcd260853f2775a27fe60f736171b7f526a26a01fd8e1b25fa1bcf154c5b2c0a84fbd4080246129d9f9838b96a93ec37f5ad0c7a051ccf9bcc53d0e1468521ba63f29be4eb82e791fa034e467bee528c199fda2e8\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:57473:26\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85143:9\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16619:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16463:25)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16453:17)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16635:16\n    at resultObj.id (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85125:9)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16753:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16468:17)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16453:17)"
        }
      }
    ],
    "unapprovedMsgs": {},
    "unapprovedMsgCount": 0,
    "unapprovedPersonalMsgs": {},
    "unapprovedPersonalMsgCount": 0,
    "unapprovedTypedMessages": {},
    "unapprovedTypedMessagesCount": 0,
    "keyringTypes": [
      "Simple Key Pair",
      "HD Key Tree"
    ],
    "keyrings": [
      {
        "type": "HD Key Tree",
        "accounts": [
          "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720"
        ]
      }
    ],
    "computedBalances": {},
    "currentAccountTab": "history",
    "tokens": [],
    "selectedAddress": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720",
    "currentCurrency": "usd",
    "conversionRate": 460.51,
    "conversionDate": 1512473817,
    "infuraNetworkStatus": {
      "mainnet": "ok",
      "ropsten": "ok",
      "kovan": "ok",
      "rinkeby": "ok"
    },
    "shapeShiftTxList": [],
    "lostAccounts": []
  },
  "appState": {
    "shouldClose": false,
    "menuOpen": false,
    "currentView": {
      "name": "config",
      "context": "0xb762679f2bf3328e1dcbb24b7d905d3d7b77d720"
    },
    "accountDetail": {
      "subview": "transactions",
      "accountExport": "none",
      "privateKey": ""
    },
    "transForward": true,
    "isLoading": false,
    "warning": null
  },
  "identities": {},
  "version": "3.12.1",
  "platform": {
    "arch": "x86-64",
    "nacl_arch": "x86-64",
    "os": "win"
  },
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
}

**Comment by JesseBusman** [comment]
I might have the same problem, I can't send any transactions with MetaMask anymore.
I installed the Firefox addon with the same seed words, same problem. Can't do anything.
That leads me to believe the problem is not on my end.

**Comment by OrbisNL** [comment]
Hi Jesse,


Does the following error also keep occurring to you?

"Error insufficient funds for gas * price + value"


________________________________
Van: Jesse Busman <notifications@github.com>
Verzonden: dinsdag 5 december 2017 13:22
Aan: MetaMask/metamask-extension
CC: OrbisNL; Author
Onderwerp: Re: [MetaMask/metamask-extension] I keep getting transaction failures and warnings (#2663)


I might have the same problem, I can't send any transactions with MetaMask anymore.
I installed the Firefox addon with the same seed words, same problem. Can't do anything.
That leads me to believe the problem is not on my end.

**Comment by submariner86** [comment]
same problem here.. rpc.. even i have enough funds.. can't send to ED or EXODUS or anywhere anymore.............

**Comment by RayZhuAU** [comment]
I have the same problem as well and it only seems to be on the Ethereum main network because transactions on the Ropsten test network are working.

**Comment by AAAAAAlone** [comment]
maybe same problem too...

**Comment by submariner86** [comment]
sam here.. none of the workarounds work

**Comment by WBenfeiW** [comment]
same here tho.....

**Comment by elijahmurray** [comment]
+1 from me. Who knew you guys would be so popular? Hope you don't get PTSD from all the CryptoKitties!

**Comment by ernaneluis** [comment]
You guys can export the private key from metamask and import to MyEtherWallet.

**Comment by WBenfeiW** [comment]
MyEtherWallet is not supported by CryptoKitties, sigh

**Comment by escrowdis** [comment]
+1 Need help~

**Comment by tmashuang** [comment]
state logs can be submitted to https://support.metamask.io, relate to #2655
