### ISSUE TITLE
[Bug]: Lack of origin display on wallet_addEthereumChain

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#26656]
### Describe the bug

Fix https://github.com/MetaMask/MetaMask-planning/issues/3471

todo add details to address fix 

### Steps to reproduce

1. Open https://pkeshkamat.github.io/poc15 in a browser with the MetaMask extension installed.
2. Within 5 seconds, switch to another tab, for example, https://www.gnosis.io/.
3. The addEthereumChain request will appear as though it came from gnosis.io

### Detection stage

In production (default)

### Version

12.0.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hjetpoluru** [comment]
I tested this scenario against the latest 12.7.2 in chrome browser and unable to reproduce the issue. @digiwand, could you please confirm and mark the status accordingly.

**Comment by bschorchit** [comment]
To fix this, we should display the origin pill in these confirmations
