### ISSUE TITLE
Remove text in the Activity empty state

### ISSUE THREAD

**Issue by amandaye0h** [MetaMask/metamask-extension#26669]
### What is this about?

The implementation of the Ramps card has resulted in conflicting hierarchy in the Activity empty state

### Design

<img width="651" alt="Screenshot 2024-08-26 at 1 42 36 PM" src="https://github.com/user-attachments/assets/92c2ed45-bcf5-4930-99af-1d5c33a8e0ad">

[Figma link](https://www.figma.com/design/aMYisczaJyEsYl1TYdcPUL/Portfolio-View?node-id=3479-36253&t=onfs1L939A4x62sk-4)

### Acceptance Criteria

"You have no transactions" and MetaMask support link have been removed.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Alcala1234** [comment]
Ch duh j it
