### ISSUE TITLE
Metamask Chrome extension can not send ETH, which was working before

### ISSUE THREAD

**Issue by halic1998** [MetaMask/metamask-extension#2667]
I can see the ETH balance that I created as a private wallet address. but I can not send it using MetaMask
Chrome extension. It keeps giving me error with the attached screenshot : ethjs-rpc: rpc error with payload ... Error: Insufficiend funds for gas * price + value

Could you please help ? 

![2017-12-05-metamask problem](https://user-images.githubusercontent.com/34273858/33608345-4a2344ec-d9d5-11e7-876e-ad712179ca24.jpg)

**Comment by sunotis** [comment]
same here

**Comment by tmashuang** [comment]
closing to consolidate to #2655

**Comment by clintonredula245** [comment]
same here? how can we solve it?
