### ISSUE TITLE
Switch Retry Algorithm to Exponential Backoff

### ISSUE THREAD

**Issue by sdtsui** [MetaMask/metamask-extension#2669]
(This issue uses private Slack archive links.)

From @maurycyp in [Slack](https://consensys.slack.com/archives/G0SCK68Q5/p1512441932000032): we'd like to lower our total number of retries for pending tx's, using [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff). This would decrease load on infura nodes, and help lower current congestion more quickly.  This was discussed live with @frankiebee and is ready to be started on.

There are a few libs out there that can help with this. It may be simplest to roll our own algo, using examples [here](https://jsfiddle.net/pajtai/pLka0ow9/) and [here](https://stackoverflow.com/questions/19657361/how-to-implement-exponential-backoff-in-this-simple-mutex-implementation): just remember to cap the backoff to, say, a day.   I'm not familiar enough with these controllers to suggest that we use localStorage to keep track of retries or if we have a preferred way of doing this: will leave it up to the implementor.

- Potential (i.e. suggested) place for this change: [transactions.js](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/controllers/transactions.js#L76
). Looks like retryCount is already implemented. 
- Additional context: how this change will be used in `pending-tx-tracker`: [here](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/lib/pending-tx-tracker.js#L105
) & [here](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/lib/pending-tx-tracker.js#L26).

Notes:
- MetaMask and Infura [will discuss this morning](https://consensys.slack.com/archives/G1L7H42BT/p1512467088000134), when more of the team is awake.
- In parallel, Frankie may be able to work on [disabling/tweaking manual resubmit](https://consensys.slack.com/archives/G1L7H42BT/p1512466650000253).

**Comment by danfinlay** [comment]
Cool idea!

**Comment by sdtsui** [comment]
Implemented in #2670.
