### ISSUE TITLE
[Bug]: Issue with contract interaction

### ISSUE THREAD

**Issue by u-hubar** [MetaMask/metamask-extension#26702]
### Describe the bug

Issue described in the #11471 is present in Metamask 12.0.5

"Continue" button is disabled when trying to interact with any contract using Hex Data.

Workaround described in the mentioned issue still works.

### Expected behavior

"Continue" button should be enabled while trying to interact with contract

### Steps to reproduce

1. Go to Metamask
2. Click "Send"
3. Paste contract address
4. "Continue" button is disabled

### Detection stage

In production (default)

### Version

12.0.5

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

MacOS

### Additional context

Arc Browser (Chromium)

**Comment by gauthierpetetin** [comment]
Closing as duplicate: https://github.com/MetaMask/metamask-extension/issues/26700
