### ISSUE TITLE
[Bug]: BigNumber Error#2: div() number type has more than 15 significant digits

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#26734]
### Describe the bug

```
BigNumber Error#2: div() number type has more than 15 significant digits: 9.999999999999999e+35
```

### Expected behavior

Transfer token prompt

### Screenshots/Recordings

<img width="331" alt="Screenshot 2024-08-28 at 8 53 07 PM" src="https://github.com/user-attachments/assets/0a2eb0cf-a751-42b7-a5dc-bc28554693ae">

### Steps to reproduce

I believe this happens in part because the token has 36 decimals. It could also be related to how the transfer amount is so large

1. Go to https://holesky.etherscan.io/address/0x0982857bc518873b8a28700fb149d80f08d08f2b#writeContract
2. manufacture() to mint one of these tokens for yourself
3. try to transfer it (`10**36`) to any other account via the Etherscan write tab

The result is that your metamask gets permanently stuck with this BigNumber error

I'm unable to try other methods because of how broken the final state is.

### Error messages or log output

```shell
BigNumber Error#2: div() number type has more than 15 significant digits: 9.999999999999999e+35
at ee (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:15:149519) at V (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:15:147746) at P.dividedBy.P.div (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:15:155468) at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:323796) at r.getAssetDetails (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:387684) at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:192421
```

### Detection stage

In production (default)

### Version

12.0.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

Completely breaks metamask; remains broken after restart toggle in `chrome://extensions`.

**Comment by digiwand** [comment]
same error message in another location has been fixed here:
Issue: https://github.com/MetaMask/metamask-extension/issues/13738
PR: https://github.com/MetaMask/metamask-extension/pull/25799

possibly we could apply a similar fix

**Comment by wjmelements** [comment]
I don't see why they use Number and div to place a decimal point when you can just splice the string.

**Comment by digiwand** [comment]
hi @wjmelements, and thanks for reporting this issue! 

I think it's because, e.g., calcTokenAmount accepts value types `number|string|BigNumber`. If a number type was passed to calcTokenAmount, it may have passed in scientific notation form. The scientific notation form can happen if the number is greater than MAX_SAFE_INTEGER which causes JavaScript to coerce it. Stringifying this first and then using the splice method, in this case, would not work.

**Comment by wjmelements** [comment]
big integers should never be converted to js Number no matter their size

**Comment by jpuri** [comment]
Hey @wjmelements ; I tried to replicate the steps but manufacture is failing for me, do you have some context: https://holesky.etherscan.io/tx/0x9167e44d24c02b90ef0e6bd28ccbe63348d272fc6089490ea510f0bc61581151

**Comment by wjmelements** [comment]
> Hey @wjmelements ; I tried to replicate the steps but manufacture is failing for me. Can you plz share if you have some context: https://holesky.etherscan.io/tx/0x9167e44d24c02b90ef0e6bd28ccbe63348d272fc6089490ea510f0bc61581151

try again https://holesky.etherscan.io/tx/0xcca99dcd2f5fd5fb9a2c42c69bf3fe720770a37ce4fe63c02bc2507d7823ef20

**Comment by jpuri** [comment]
Hey @wjmelements : thanks a lot for sharing these details. I could successfully manufacture now. https://holesky.etherscan.io/tx/0xaa61d4fbd1bdd3f4371bba622ba738fd74fe077296efdb3d0dd449dad5b15f13

But transfer seems to work smooth for me, though approve is failing:

https://github.com/user-attachments/assets/8d0cbf2a-6f36-44f4-a994-7259a11ecb1d

I am not sure if I am missing something, can you please suggest.

**Comment by wjmelements** [comment]
I cannot try to reproduce because my metamask is permanently broken as aforementioned.

One possibility is that Metamask behaves differently when you are transferring to an account besides yourself. The account I was transferring to was a smart contract.

Another possibility is that the breakage was caused by [another token, AntiHydrogen](https://holesky.etherscan.io/address/0xb6b7a544daad6f05e20e5f1174391435fac5073d#code) I was testing concurrently. This token also has 36 decimals but `manufacture()` creates one unit instead of `10**36`. I may have enqueued transfers for both around the same time. While I believe the issue was with MicroPlastics because of the error message, AntiHydrogen could also produce this error if that number,`9.999999999999999e+35`, is the denominator.

Hopefully the error you see in `approve` is similar enough to fix the general issue. One difference is that my metamask is unusable, possibly because it tries to prompt me to sign the transaction again on restart. I'm fairly confident the error I am seeing originated in `transfer`.

**Comment by jpuri** [comment]
Thanks, I am looking to fix approve issue now.

Submitting another transaction to MM should fix ur extension.
