### ISSUE TITLE
[Bug]: Activity title truncation feels way too tight

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#26744]
### Describe the bug

Our activity title labels for e.g. “Send ETH...” gets truncated too tight in a way where it almost looks like it’s loading "..."

### Expected behavior

Allow more characters before truncation and look through overall truncation rules / config

### Screenshots/Recordings

![image](https://github.com/user-attachments/assets/1b393f93-d6f9-424a-9a45-b541dfcc873d)

### Steps to reproduce

1. Go to your activity tab
2. Look at any item label that is longer than > ~8 characters

### Detection stage

In production (default)

### Version

12.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by DDDDDanica** [comment]
Fixed in the new design: 

<img width="362" alt="Image" src="https://github.com/user-attachments/assets/f03dd6d8-08cc-4284-8b9a-9f029b267e98" />
