### ISSUE TITLE
[Bug]: Arrow icon is not clickable, just the “Edit” label is

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-extension#26746]
### Describe the bug

As a user, you can't click the (seemingly clickable) arrow icon next to the `< Edit` button

### Expected behavior

You should be able to click the arrow icon as well

### Screenshots/Recordings

![image](https://github.com/user-attachments/assets/bfde9b1d-6ecf-4a41-b698-555824e38f16)

### Steps to reproduce

1. Trigger a send confirmation (or similar)
2. Try to click on the arrow icon in the top left corner of the screen

### Detection stage

In production (default)

### Version

12.0

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by bschorchit** [comment]
Closing as this is no longer an issue on the redesigned confirmations. The new screens will be made default on extension v12.9 
![Image](https://github.com/user-attachments/assets/23a5f4c6-019b-44ef-be04-d37951b2f60c)
