### ISSUE TITLE
[Bug]: Send barcode scanner does not work

### ISSUE THREAD

**Issue by mmragkandala** [MetaMask/metamask-extension#26751]
### Describe the bug

When trying to use the barcode scanner in the send flow on my laptop (macbook pro), I get an error saying the recipient address is invalid.

https://github.com/user-attachments/assets/08b5a2e6-aad7-44f6-8b23-39b479e4afd1

### Steps to reproduce

1. Click send from the wallet screen
2. Click the scan barcode icon in the to address field
3. Give camera access to the extension/browser
4. Show barcode in the camera

### Detection stage

In production (default)

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by plasmacorral** [comment]
Related https://github.com/MetaMask/metamask-extension/issues/21766
