### ISSUE TITLE
[Bug]: Helptext for NFTs says, “Balance 1 token”

### ISSUE THREAD

**Issue by mmragkandala** [MetaMask/metamask-extension#26772]
### Describe the bug

When select an NFT to send, the helptext below the asset input field says "Balance 1 token". Should this say 1 NFT or something else?
<img width="360" alt="Screenshot 2024-08-29 at 9 33 51 AM" src="https://github.com/user-attachments/assets/4918a8bb-c310-4124-b3a9-170f7e96b700">

### Steps to reproduce

1. Click send
2. Select an NFT from the sent to asset input

### Detection stage

In production (default)

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by coreyjanssen** [comment]
Thanks for tagging me @DDDDDanica! Definitely need to revise this! Is it possible to have 2 variants for this? 1 that is for 1 NFT, and 1 for 2 or more. For example:

`Balance: 1 NFT ` or 
`Balance: [2-1000000] NFTs`

**Comment by DDDDDanica** [comment]
Sounds good ! Will address that !
