### ISSUE TITLE
[Bug]: From account input and continue button get disabled when editing send flow

### ISSUE THREAD

**Issue by mmragkandala** [MetaMask/metamask-extension#26781]
### Describe the bug

The account input and continue button get disabled without context if a user tries edit an in-progress send TX for an NFT

https://github.com/user-attachments/assets/2c61116d-0a2f-4417-9646-9ebd2e3873d5

### Steps to reproduce

1. Click send
2. Select an NFT to send
3. Click continue
4. Click edit from Tx review screen

### Detection stage

In production (default)

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
@ejwessel @mmragkandala 
Can't reproduce in v12.0.0 and later versions:





https://github.com/user-attachments/assets/a48cf45f-4429-43bc-8b2c-b0dec60535ac

**Comment by ejwessel** [comment]
it looks to be related to NFTS that were cached and no longer a part of the account. I was able to repo this with @jclancy93 and establish the above behavior is because the NFT is no longer owned yet still visible within the send list.
