### ISSUE TITLE
[Bug]: "Currency conversion" on extension settings has no description but a time stamp

### ISSUE THREAD

**Issue by yanrong-chen** [MetaMask/metamask-extension#26787]
### Describe the bug

Currently the "Currency conversion" on extension settings has no description but a time stamp. I don't think users need to know when their currency are last updated. Instead, we should be consistent with mobile design and show a description explaining what currency conversion means. On mobile we currently do show a description and no time stamp

<img width="844" alt="Screenshot 2024-08-29 at 4 32 37 PM" src="https://github.com/user-attachments/assets/34c8d882-c193-4712-9a6b-8131aacbec76">

### Expected behavior

Remove time stamp on extension for "Currency conversion" and add description, just like what mobile does.

### Steps to reproduce

1. Go to settings on extension
2. Go to General 

### Detection stage

In production (default)

### Version

11.16.10

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by amandaye0h** [comment]
Updated formatting [in this ticket](https://github.com/MetaMask/metamask-extension/pull/27161), albeit we removed the description:
