### ISSUE TITLE
FAILED TX in MetaMask is really PENDING in Etherscan

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#2681]
My transaction says **failed** in Metamask but when I check it on Etherscan it is actually is **Pending**

<img width="1327" alt="screen shot 2017-12-06 at 8 52 53 pm" src="https://user-images.githubusercontent.com/597770/33694773-dc2cfd72-dac7-11e7-996b-712140b7dcd1.png">

**Comment by cjeria** [comment]
@frankiebee There was a misalignment with what we see in MM and what is shown in Etherscan as you can see from the screenshot.

**Comment by cjeria** [comment]
@frankiebee This data seems like it should be reflected consistently in MM.

**Comment by cjeria** [comment]
"Pending" in Etherscan, shouldn't mean "Failed" in metamask.

**Comment by danfinlay** [comment]
This is a known behavior. We “fail” after 24 hours of no mining. Now that we have a “retry with higher gas” button, we can change that, and only "fail" a pending tx if one with its nonce is mined.

Also, for people whose txs were incorrectly marked failed, we could add a "retry" button on failed txs whose nonce has not yet been mined.

**Comment by danfinlay** [comment]
Solution:

- Do not "fail" a transaction for pending a long time. Our "retry with higher gas" button makes this unnecessary.
