### ISSUE TITLE
Cherry-pick PRs for 12.3.0 (including formal 12.4.0 PRs)

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#26830]
### What is this about?

As mentioned in our [internal thread](https://consensys.slack.com/archives/C029JG63136/p1725346800854389), we are combining release 12.3.0 and 12.4.0. This PR is to track cherry-picks that are targeting 12.3.0

Create cherry-pick PRs for the PRs fixing these issues:

- [x] https://github.com/MetaMask/metamask-extension/issues/26593
- [x] https://github.com/MetaMask/metamask-extension/issues/26591 (PermitSingle)
- [x] https://github.com/MetaMask/metamask-extension/issues/26592 (PermitBatch)
- [x] https://github.com/MetaMask/metamask-extension/issues/27137
- [ ] https://github.com/MetaMask/MetaMask-planning/issues/2936
- [x] https://github.com/MetaMask/MetaMask-planning/issues/3010
- [ ] https://github.com/MetaMask/MetaMask-planning/issues/3274
- [x] https://github.com/MetaMask/metamask-extension/issues/27139
- [x] https://github.com/MetaMask/metamask-extension/issues/27147

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by bschorchit** [comment]
Closing this as completed (possibly the ppom cherry pick is still missing, but this will be followed up separately)
