### ISSUE TITLE
[Bug]: Multi RPC - Upon importing an account after the addition of a custom RPC URL, users encounter an error message within the account addition modal

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26834]
### Describe the bug

Upon importing an account after the addition of a custom RPC URL, users encounter an error message within the account addition modal stating, "Had a problem changing networks!" Despite this message, there are no errors reported in the console, and the account is imported as anticipated.

### Expected behavior

-

### Screenshots/Recordings

<img width="508" alt="Screenshot 2024-09-02 at 00 05 58" src="https://github.com/user-attachments/assets/85f13bf2-5ebf-40f2-b41b-fdfd2659a65d">

https://github.com/user-attachments/assets/7eb9a60c-39a0-495d-8ab8-291d865f0e6c

### Steps to reproduce

1. Add custom RPC URL
2. Import account

### Detection stage

On the development branch

### Version

12.0.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Build https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/97568/workflows/28d6cb81-d0e8-410f-ae41-7f8b6cc5c5a9/jobs/3631842/artifacts

**Comment by salimtb** [comment]
hey @sleepytanya ,
this bug has been addressed on the latest build.
you can find it [here](https://github.com/MetaMask/metamask-extension/pull/26433#issuecomment-2323795439)


https://github.com/user-attachments/assets/23fdc16e-8a6a-4a31-bc17-84c1e3dcb9b0

**Comment by sleepytanya** [comment]
I don't see it on the latest commit [0b38bd5](https://github.com/MetaMask/metamask-extension/pull/26433/commits/0b38bd5f1f7a2211671d839ca7db78a3be7426f2)


https://github.com/user-attachments/assets/5aa56a2a-0507-451e-b3ef-605e0b114b4e
