### ISSUE TITLE
[Bug]: Multi RPC - unable to swap 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26847]
### Describe the bug

When attempting to perform a swap in MetaMask (both with default and custom RPC URLs), users may experience the application freezing. Additionally, the block explorer link may direct to an error page, and the 'View in Activity' button could be disabled.  Reloading the extension resolves the freezing issue but swaps still can't be performed.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/a60777d3-2b0d-478e-b2db-86dbe8bf80be

https://github.com/user-attachments/assets/bce37f18-ef4d-4e92-b2f6-c9dac22275bf

<img width="691" alt="Screenshot 2024-09-02 at 16 28 00" src="https://github.com/user-attachments/assets/719f47e3-53ce-4a70-9845-e63f1ac23fa2">

<img width="693" alt="Screenshot 2024-09-02 at 16 28 29" src="https://github.com/user-attachments/assets/2a47f5e4-16fa-44c9-ad21-99470fa466b6">

### Steps to reproduce

1. Start swap

### Detection stage

On the development branch

### Version

dev build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Dev build commit [0b38bd5](https://github.com/MetaMask/metamask-extension/pull/26433/commits/0b38bd5f1f7a2211671d839ca7db78a3be7426f2)

**Comment by bergeron** [comment]
Not yet sure how to reproduce this one.  Have done several swaps with different networks and tokens, but all successful

https://github.com/user-attachments/assets/3ddd4dc2-e0d1-46dd-a30d-c2996b26c52c

**Comment by sleepytanya** [comment]
Rebuilt, reinstalled and still can't swap (tried with imported and original account):


https://github.com/user-attachments/assets/1aa03b04-a7b3-48b7-bf4c-02b370da465a

**Comment by bergeron** [comment]
I'm stumped on what the repro steps are for this one.  Can @salimtb or anyone else trigger it?  And if so, can you trigger it on develop or is it specific to the network UI feature?

Might help to have the same seed + key.   I'm also trying original + imported accounts, various tokens and chains.  But all successful.  Here's the identical steps I mimicked:

https://github.com/user-attachments/assets/8b217777-cc1a-4550-bfb8-d16599fc7392

**Comment by salimtb** [comment]
hey @bergeron @sleepytanya ,
i was able to reproduce with the following inputs:
rpc used: `https://eth.llamarpc.com`
scenario: swap `0.00001` ETH to `USDC`
you can find the video + the error attached beelow

https://github.com/user-attachments/assets/ffba9b28-19d9-47de-8e6c-3691e10eb3ab
<img width="1226" alt="Screenshot 2024-09-03 at 09 30 01" src="https://github.com/user-attachments/assets/809e05f9-8711-446b-9590-9a3c849b79bf">

**Comment by salimtb** [comment]
just tested on develop with same data, i'm getting the same error , i cannot do the swap with llama node
<img width="1365" alt="Screenshot 2024-09-03 at 10 19 04" src="https://github.com/user-attachments/assets/77d6b46a-fc5f-48f1-9e92-7d25e4cfda79">

**Comment by salimtb** [comment]
hey @sleepytanya ,
i went through the same steps than you but i wasn't able to reproduce.
i'm i doing something wrong ?

https://github.com/user-attachments/assets/147506ae-e452-412f-b317-93441b524adb

**Comment by salimtb** [comment]
@sleepytanya can you share the rpc you're using pls

**Comment by sleepytanya** [comment]
I think we can close it as it looks something was wrong with my local builds. Swaps in CI build off the branch work as expected.
