### ISSUE TITLE
Every transaction it makes it says transaction underpriced. This is fucking bullshit. My transaction of yesterday did not go through, but the gas is gone. I don't get it. Im sorry Im a noob. But this nonsense.

### ISSUE THREAD

**Issue by Sthom33** [MetaMask/metamask-extension#2685]

**Comment by brandoncurtis** [comment]
The network is under heavy load, and a higher gas cost than usual is needed for transactions to go through.  

You can use https://etherscan.io/ to check your balances and pending transactions and https://ethgasstation.info/ for recommended gas prices based on realtime network traffic.

**Comment by tmashuang** [comment]
Thanks @brandoncurtis. @Sthom33 if you want to know how the ecosystem works and why your gas was contributed, there is a great article from one of the developers of the ecosystem. [Gas, Accounts, Contracts](https://www.reddit.com/r/ethereum/comments/7ictig/want_to_understand_block_gas_limits_accounts/)
