### ISSUE TITLE
Error: transaction underpriced

### ISSUE THREAD

**Issue by sevku** [MetaMask/metamask-extension#2686]
First transaction and it failed. Hope this gets fixed. How can I get my ETH back?

Yes there is the same issue from 23 minutes ago but I didn't confirm that Issue due to its agressive language.

**Comment by CryptoDoll** [comment]
I am having this same problem too. I am trying to buy a cryptokitty, but my transaction fails. I have messed with the gas and it is still the same error message. Please advise!

**Comment by sabotagebeats** [comment]
Try 60 gwei 200k gas limit

**Comment by brandoncurtis** [comment]
The network is under heavy load, and a higher gas cost than usual is needed for transactions to go through.

You can use https://etherscan.io/ to check your balances and pending transactions and https://ethgasstation.info/ for recommended gas prices based on realtime network traffic.

**Comment by danfinlay** [comment]
These failures were related to the great kitty backlog of 2017. This issue should be mostly mitigated now, let us know if you have these problems again.

**Comment by Maxxboy** [comment]
I've been having the same issues for the last 3 days too. I tried increasing my gas but transactions are still not going through.
"rpc error with payload" on the bottom it says "replacement transaction underpriced"

Any pointers on how to solve this?

**Comment by danfinlay** [comment]
Submit the transaction with a higher gas price. The error means what it says! Transactions are expensive right now, check it out:
https://ethgasstation.info/
