### ISSUE TITLE
[Feat]: Add Network Icon for ApeChain 

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#26874]
### What is this about?

Add support network icon for ApeChain 

Requested by members of Yuga Labs

#### Mainnet 

TBD

#### Testnet RPC:

testnet 

Network Name  
Curtis

RPC URL  
https://curtis.rpc.caldera.xyz/http

Chain ID  
33111

Currency Symbol  
APE

Block Explorer  
https://curtis.explorer.caldera.xyz/

#### Requires:
- [x] png version of icon image
- [ ] chain id of RPC mainnet network 

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by onwardyuga** [comment]
![apechain](https://github.com/user-attachments/assets/ad0ff81e-d86c-490d-9bd8-d1c9e9a650ea)

**Comment by sahar-fehri** [comment]
Hi @robbiekruszynski ! Thank you for reaching out; could you provide the SVG format of the image? 🙏

**Comment by sahar-fehri** [comment]
Hello again @digiwand  @robbiekruszynski  👋  i can merge this https://github.com/MetaMask/metamask-extension/pull/27841 if you guys are happy with how the logo looks!

**Comment by robbiekruszynski** [comment]
Perfect, will reach out later today with more details. Thank you

**Comment by robbiekruszynski** [comment]
@sahar-fehri We are going to update the img, after that we are good for a launch on Friday

**Comment by sahar-fehri** [comment]
Hi @robbiekruszynski , i can update my PR, could you send me the updated image? Is it SVG?

**Comment by sahar-fehri** [comment]
Ho @robbiekruszynski ; I will proceed to merging the [PR](https://github.com/MetaMask/metamask-extension/pull/27841) then once i get a green CI.
Its @Sahar_fehri

**Comment by sahar-fehri** [comment]
@robbiekruszynski PR merged.

**Comment by robbiekruszynski** [comment]
Hi @sahar-fehri , following the steps to add I'm not getting the same results with the logo appearing post network add

**Comment by sahar-fehri** [comment]
Hi @robbiekruszynski ! Could you share a video of the results you are seeing? 🙏
