### ISSUE TITLE
Failed to send ETH but disappear from the wallet 

### ISSUE THREAD

**Issue by jerrchang** [MetaMask/metamask-extension#2687]
My 2 ETH disappeared after a failed transfer: 
Error: rpc error with payload
Error: replacement transaction underpriced

my destination is 0xe2E3EB9D03C9F926D451727dB0ff7285da93DB84

But on etherscan it showing the ETH has been sent to 0x708352CD28ea06e6bbD5C1a9408b4966Ac1226e4

<img width="334" alt="screen shot 2017-12-07 at 12 22 08 am" src="https://user-images.githubusercontent.com/34334524/33705634-ed5d44ee-dae5-11e7-8524-afe868bf19b0.png">
<img width="1123" alt="screen shot 2017-12-07 at 12 30 13 am" src="https://user-images.githubusercontent.com/34334524/33705643-f33e1cf8-dae5-11e7-82ca-7a5c1f147c9f.png">

**Comment by brandoncurtis** [comment]
It appears that you purchased 14,000 SHAREs in the Vyral token sale: https://etherscan.io/address/0x57c52db1f61713d9ca7f7c645f2edeb159a9dd6a

Based on the error, it looks like you tried to cancel or modify this transaction and either rejected the replacement transaction in MetaMask, or (more likely from the text of the error) you did not set a higher gas price in the replacement transaction than you had set for the initial transaction.
