### ISSUE TITLE
[Bug]: Unable to add or sign Trezor account in v12.1.1

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#26875]
### Describe the bug

Was working on a migration test from 12.1.1 to RC 12.2.0 and noticed that I was unable to add a Trezor account.  If I add a Trezor account in a version prior to 12.1.1 I can add the Trezor address, but after migration to v12.2.0 RC 8fa9cc090c2804d0dd5e3448e9d1b25eb958833e
 I am not able to sign, send, or add more Trezor accounts. 

Confirmed that 12.0.6 and 12.1.0 do not have this issue, but 12.1.1 and 12.2.0 are impacted.

This was observed with a Trezor Model T running firmware 2.8.1 on a Mac running Sonoma 14.6.1.

### Expected behavior

When using a Trezor address a pop-up window is opened and can communicate with Trezor.  

Also, should not show a Ledger Live related error in yellow text while trying to add Trezor. 

### Screenshots/Recordings

12.1.1:
Not able to add the device (or sign if address was present from migration from MM <12.1.1) [Recording](https://www.loom.com/share/3e1f3d2cc57247a5b02e0ff8d61babb8?sid=1b17e423-16cf-4260-a1ed-674441e25b3a)

12.1.0:
Able to send/sign in Chrome [Recording](https://www.loom.com/share/3ee257993a774316b8aa3e4db513565c)

### Steps to reproduce

1. Configure a wallet and get to wallet view
2. Tap the account
3. Tap `Add account or Hardware wallet`
4. Tap `Add hardware wallet'
5. Tap `Trezor`
6. Note pop-up opens, but green spinner

### Error messages or log output

```shell
{name: 'Error', message: 'Error: Iframe timeout', stack: 'Error: Error: Iframe timeout\n  at I.i (chrome-exte…anaaeohfgaadkdjecdcmbdigiagi/common-0.js:1:527723', code: undefined, rpc: undefined}
code
```

Also
```shell
 Failed to execute `postMessage` on `Window:  Invalid target origin `unknown` in a call to `postMessage`
```

### Detection stage

In production (default)

### Version

12.1.1

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

### Hardware wallet

Trezor

### Severity

Cannot seem to find a work around to be able to sign or add new accounts to MetaMask.

**Comment by Gudahtt** [comment]
I am able to reproduce this locally as well. It works on v12.1.0, fails on v12.1.1.
