### ISSUE TITLE
NetworkController upgrade from v20 to v21

### ISSUE THREAD

**Issue by desi** [MetaMask/metamask-extension#26911]
### What is this about?

The `NetworkController` is behind by one major version and needs to be updated. 
Upgrade from v20 to v21.
Additionally, there are several peer dependencies which will likely be best to be upgraded at the same time. Those are the following:

- `SelectedNetworkController` currently on v15, should be upgraded to v18
- `PermissionController` currently on v10, should be upgraded to v11 
- `PermissionLogController` currently on v2, should be on v3
- `GasfeeController` currently on v18, should be on v20
- `TransactionController` currently on v35, should be v36
- `UserOperationController` currently on v13, should be on v15
- `QueuedRequestController` currently on v2, should be on v5
- `EnsController` currently on 13, should be 14

### Scenario

n/a

### Design

n/a

### Technical Details

See Description

### Acceptance Criteria

- `NetworkController` version is v21
- `SelectedNetworkController` version is v18
- `PermissionController` version is v11 
- `PermissionLogController` version is v3
- `GasfeeController` version is v20
- `TransactionController` version is v36
- `UserOperationController` version is v15
- `QueuedRequestController` version is v5
- `EnsController` version is 14

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Gudahtt** [comment]
Completed in https://github.com/MetaMask/metamask-extension/pull/26433
