### ISSUE TITLE
Along with resubmit, add cancel button to pending txs

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2693]
Cancel button would be about sending a null transaction with the higher minimum gas price as that transaction.

**Comment by cjeria** [comment]
@danfinlay @kumavis just a theory but it seems to me that if we give users the ability to cancel a transaction, we wouldn't need a "retry" feature, which has proven to cause new problems that @jrmoreau has flagged for us.  

To refer back to the original problem we're trying to solve:
Transactions sometimes take too long and users get impatient. 

An obvious solution: Give users a way to cancel their transaction and give them the choice to retry if they want to.

I think the harder problem to solve is the "retry" feature. It involves educating users about nonces, gas prices etc. Cancel FTW!

**Comment by cjeria** [comment]
On the other hand, we could implement both options as planned and with some analytics seeing which feature gets used most.

**Comment by danfinlay** [comment]
Unfortunately, “cancel” isn’t magically simpler. The cancel button will do the exact same thing as the retry button, except instead of duplicating the transaction at the same nonce, it will create a zero value transaction with the same nonce.

**Comment by cjeria** [comment]
@danfinlay I'm aware of the technical implications of how cancelling a tx would work. What I meant was we can streamline the cancel transaction UX and maybe even make it feel a little magical if we handle some of the work for the user. 😉 

See step 2.2 in this flow
![retry or cancel tx flow](https://user-images.githubusercontent.com/597770/35260399-382a9fa4-ffc0-11e7-9373-2f4d11e7fdc0.png)

**Comment by kublermdk** [comment]
Just a tiny grammar nazi point in case that gets implemented.
In 2.2 Cancel Transaction it should be "Gas fee to cancel your transactíon" not "you're".

I do like the Cancel Transaction option.

**Comment by MicahZoltu** [comment]
Step 2.1 in that flow is too complicated for end-users IMO.  In particular, end-users don't understand nonces.

Also, "duplicate" I think gives users the wrong idea about what is happening.  Only one of the two transactions will succeed but to a naïve user there is a possibility of both succeeding based on the wording "duplicate".  Perhaps label it as "Modify Transaction" instead?   I think "modify" gives the user the correct high level understanding of what is happening, and the UI would only need to let them know that modification may not succeed.

**Comment by danfinlay** [comment]
@cjeria I'd love to go for this one soon, if we could get the designs finalized for the MVP. Might be worth doing it for the old UI too, because it could help users get out of some dangerous situations (like ghost accounts): https://metamask.helpscoutdocs.com/article/37-ghost-accounts-ether-sending-away-whenever-funding-an-account

**Comment by bdresser** [comment]
added in https://github.com/MetaMask/metamask-extension/pull/5282
