### ISSUE TITLE
Fix "Account-watcher snap Invalid input handling handles ..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26932]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/98899/workflows/d67e21de-42fc-4609-a0a1-663312d79fc7/jobs/3681026/tests

Build - Flask
Browser - Firefox

I have noticed that the below-mentioned test scenario has the same issue. This could be intermittent, but it needs to be confirmed by the Snaps team. If required, please create individual tickets.

Test scenario - Account-watcher snap Invalid input handling handles invalid input: invalid address
Test scenario - Account-watcher snap Invalid input handling handles invalid input: address missing 0x prefix
Test scenario - Account-watcher snap Account management removes a watched account
Test scenario - Account-watcher snap Adding watched accounts disables 'Send' 'Swap' and 'Bridge' buttons for watch accounts
Test scenario - Account-watcher snap Account management can remove and recreate a watched account
Test scenario - Account-watcher snap Account management does not allow user to import private key of watched address

```
TimeoutError: Waiting for element to be located By(css selector, [placeholder="Enter a public address or ENS name"])
Wait timed out after 10147ms
  (Ran on CircleCI Node 0 of 10, Job test-e2e-firefox-flask)
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
![image](https://github.com/user-attachments/assets/24e96207-01bb-4c5a-ac6b-08e0f7633ed1)

**Comment by plasmacorral** [comment]
Should be resolved with https://github.com/MetaMask/metamask-extension/pull/26950 merged
