### ISSUE TITLE
[Bug]: Multiple backslashes are breaking the settings search.

### ISSUE THREAD

**Issue by NiranjanaBinoy** [MetaMask/metamask-extension#26945]
### Describe the bug

The app breaks if we enter more than two back-slash (`\`) while performing search in the settings.

### Expected behavior

The application should not break.

### Screenshots/Recordings

https://github.com/user-attachments/assets/d20045ee-9579-4ffa-8a18-14ef937e27f3

### Steps to reproduce

1. Go to settings page.
2. In the search bar, enter three back-slack `\\\`
3. The app will break.

### Detection stage

On the development branch

### Version

12.1.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by DDDDDanica** [comment]
Fix in https://github.com/MetaMask/metamask-extension/pull/27432
