### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by Kuzirashi** [MetaMask/metamask-extension#2694]
I'm using MetaMask on Ember application. I need Babel polyfill in that application. When MetaMask is enabled on that site then I get error:

```
Uncaught Error: only one instance of babel-polyfill is allowed
```

How to solve it? Can your extension check before trying to require babel-polyfill?

**Comment by danfinlay** [comment]
Can you provide a reproduction app, so we can try addressing this?

**Comment by Kuzirashi** [comment]
The issue've gone away and I don't know exactly how it got solved. It's totally possible to use MetaMask with Ember. Thanks for great job!

**Comment by danfinlay** [comment]
Well great! Let us know if it comes back!
