### ISSUE TITLE
QR Code and Copy Address Provide Different Addresses

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#2695]
As stated above. Need repro steps.

**Comment by tmashuang** [comment]
Could be related to. https://cointelegraph.com/news/bitcoin-malware-changes-destination-wallet-to-steal-13-btc

**Comment by tmashuang** [comment]
https://coinjournal.net/pc-malware-steals-funds-modifying-ethereum-addresses/

**Comment by whymarrh** [comment]
I think we might be able to close this in lieu of any reproduction steps, it's an old one (cc @bdresser)

**Comment by tmashuang** [comment]
We recently worked on this feature and saw no disparities in the address. #9667 #9043. As this is relatively aged issue, if anyone else finds themselves here with this issue feel free to open a new issue with additional information.
