### ISSUE TITLE
Transaction pending no matter what I do I have tried to cancel it several times by sending another transaction like it 

### ISSUE THREAD

**Issue by almondrah** [MetaMask/metamask-extension#2696]

**Comment by almondrah** [comment]
I am trying to do this Crypto Kitties and I have 1 transaction stuck that I can't get to complete and can't cancel no matter what I do.... I have gone to youtube and done the tutorials on how to cancel/make a stuck transaction complete and NOTHING is working... how do I fix this?

**Comment by tmashuang** [comment]
With the network congestion transactions with a lower recommend gas price will take longer to mine. We have implemented a couple updates to edit the gas price a transaction that is in a pending state.
