### ISSUE TITLE
[Bug]: When a user switches networks, the transaction created on the newly selected network adopts a nonce that is incremented by one from the transaction on the previous network

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26979]
### Describe the bug

When a user switches networks, the transaction created on the newly selected network adopts a nonce that is incremented by one from the transaction on the previous network. If the user opts to reject the transaction, the correct nonce briefly appears. If transaction is confirmed by the user, it submits with the low nonce and subsequently fails, or it is submitted with the high nonce and stays in `Pending` state and seems like it can't be cancelled (I waited for ~20 mins). Upon a subsequent attempt, the transaction is then created with the accurate nonce and can be successfully submitted.

### Expected behavior

Transactions created with the correct nonce value

### Screenshots/Recordings

https://github.com/user-attachments/assets/0fe23ded-8a2b-4a56-9348-dbecd9857690

Tx with low nonce fails - popup  is not visible when screen recording is on but it is there and displays correct error message:

https://github.com/user-attachments/assets/546137c7-14ee-44e5-95c9-85627ca16955

Tx with high nonce stays in `Pending` state:

https://github.com/user-attachments/assets/f1c29012-446a-4888-9c8a-eb9fa8fec73e

### Steps to reproduce

1. Note the transaction nonce
2. Switch to another chain
3. Create a transaction
4. Notice that transaction created with incorrect nonce

### Detection stage

In production (default)

### Version

dev build https://github.com/MetaMask/metamask-extension/pull/26433#issuecomment-2330104521

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bergeron** [comment]
I reproduce this.  But it also reproduces on the latest develop commit https://github.com/MetaMask/metamask-extension/commit/b2fd6a51c4c4087670a341d1837f6c2d063ada68, so I don't think it's related to the multi rpc network upgrade.

It did not reproduce on production version 12.1.3

https://github.com/user-attachments/assets/a55ae8ba-985c-4b47-b116-85b05fd669c8

**Comment by sleepytanya** [comment]
@bergeron 
 latest develop [7dc6362](https://github.com/MetaMask/metamask-extension/commit/7dc6362a70a3e7ab1de406bfdcbae7ad4d2c68be) 

I can reproduce if I start transaction from within the wallet:



https://github.com/user-attachments/assets/091e8e7e-33c0-4eac-bbb1-cf98a859c07c

If transaction is from the test dapp the nonce is correct:


https://github.com/user-attachments/assets/be57dba6-852b-44ed-8f3d-3e87e9728dba
