### ISSUE TITLE
[Bug]: Network toast is not displayed or populated when user selects custom RPC URL

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26982]
### Describe the bug

1. Network notification is not displayed when user selects custom RPC URL
2. When selected network is not on Popular list notification message is 'Network switched to' or, in some cases, notification doesn't appear
3. To provide some clarity, notification appears on the second Confirmation screen, obscuring information (such as the nonce number, as seen in screen recordings). This prompts a question: is the timing of the notification display—occurring not immediately after a network switch but rather at the conclusion of a transaction—intentional?

### Expected behavior

-

### Screenshots/Recordings

Switching to custom RPC BNB:

https://github.com/user-attachments/assets/52f005ab-279c-45d1-8eb3-9ab90c7804cb

To default ROC BNB:

https://github.com/user-attachments/assets/bb2f9e95-9a03-4abe-a3d0-79388803936e

To custom RPC Polygon:

https://github.com/user-attachments/assets/d8d8af05-1d73-4dfc-b946-2adbac02aa13

To default RPC Polygon:

https://github.com/user-attachments/assets/4c564c39-2bee-452c-8d93-2917af82b788

Notification for manually added network:

<img width="405" alt="Screenshot 2024-09-08 at 18 20 13" src="https://github.com/user-attachments/assets/015ae1e3-3812-4039-872b-4521cb6c0b07">

<img width="393" alt="Screenshot 2024-09-06 at 20 56 13" src="https://github.com/user-attachments/assets/e7cb5175-9b75-4b05-82f3-73d9ff33ec8a">

### Steps to reproduce

1. Switch to another network using default RPC, observe notification blocking info on Confirmation screen
2. Switch to another network using custom RPC, not^ that notification is not displayed

### Detection stage

In production (default)

### Version

latest Multichain build https://github.com/MetaMask/metamask-extension/pull/26433#issuecomment-2330104521

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by hesterbruikman** [comment]
@mmragkandala @NidhiKJha @adonesky1 I'm thinking this network 'changed toast' should be removed altogether. Wdyt?

**Comment by mmragkandala** [comment]
> @mmragkandala @NidhiKJha @adonesky1 I'm thinking this network 'changed toast' should be removed altogether. Wdyt?

I agree, we can probably remove it.

**Comment by bschorchit** [comment]
Hey @hesterbruikman @mmragkandala could you share more insight on why it should be removed? iirc, this was a change introduced to raise user awareness when they were interacting with different chains one right after the other. This was a high priority ask from Amon Hen for confirmations that has yet to rollout.

**Comment by jpuri** [comment]
Hey @sleepytanya : I added 2 networks manually but it seems to work well, please check:

https://github.com/user-attachments/assets/16aaa285-bb6a-48e5-9617-f42c04d1542a

**Comment by sleepytanya** [comment]
@jpuri  Thank you!
 

> Network notification is not displayed when user selects custom RPC URL

   So what happens is that the toast doesn't appear if on the previous network user didn't trigger the confirmation. It doesn't matter if the RPC URL is default or custom - is it expected?

   

https://github.com/user-attachments/assets/ed89903e-e55e-4174-a99d-e7954fef7fb9


Tried to start swap and then switched to BNB - no toast:


https://github.com/user-attachments/assets/798ee02a-b9ab-43b0-917e-eb7d9fc832e3



Fantom added from Sushi Swaps:


https://github.com/user-attachments/assets/8c9d77fa-61ef-4f1c-9f48-4f08486ee7d2

**Comment by bergeron** [comment]
I haven't yet reproduced any impacts of the multi rpc feature on this toast.

I see the toast when I:
- start a tx on one chain
- switch chains
- start a tx on the new chain.

I see the toast when switching by clicking the overall network in the list, and when switching via a particular RPC endpoint.

The only existing thing that looks odd to me, is how this network name is calculated:

https://github.com/MetaMask/metamask-extension/blob/7dc6362a70a3e7ab1de406bfdcbae7ad4d2c68be/ui/pages/confirmations/components/confirm/network-change-toast/network-change-toast-legacy.tsx#L75

`NETWORK_TO_NAME_MAP` only has constants for a few networks, and would not respect the custom names users have given to their networks.  This may explain the screenshots in the initial report where the name is empty.  In our new multi rpc world, this can start looking up names via `getNetworkConfigurationsByChainId` instead.

**Comment by jpuri** [comment]
@sleepytanya , @bergeron : network toasts only appears if user submits confirmation in quick succession from different networks.

**Comment by sleepytanya** [comment]
The network toast notification is not populated for many networks beyond those listed as 'Popular' networks, including Fantom, Chronos, Rootstock, Polygon zkEVM, Mantle and others.

I was adding networks using [suchiswaps](https://www.sushi.com/swap?utm_source=coinbase&utm_medium=web&chainId=81457&token0=NATIVE&token1=0x4300000000000000000000000000000000000003)
  
`Develop` commit [a61b938](https://github.com/MetaMask/metamask-extension/commit/a61b9382ef5d90ae6eaee844306f2a420653e7d9)

<img width="896" alt="Screenshot 2024-09-11 at 20 08 43" src="https://github.com/user-attachments/assets/5bc3b9c0-3f8c-45c5-b735-63cf7339bd83">

<img width="1417" alt="Screenshot 2024-09-11 at 20 08 17" src="https://github.com/user-attachments/assets/c56e04df-5c2b-4d59-a8fc-4dcfe099cb87">
