### ISSUE TITLE
DESAPARECEN LOS ETH

### ISSUE THREAD

**Issue by pacoluisa** [MetaMask/metamask-extension#2698]
¡¡¡¡Han desaparecido 0,01056973 ETH!!!!

0,01056973
--

0,01056973
--

**Comment by pacoluisa** [comment]
Buenas tardes, he intentado varias transacciones, todas han fallado, pero me ha quitado un montón de ETH, quiero que me los devuelva 

0x4cc3ccecc5e71324860a6e3bb4e7d8fdaab97363048dc09acc7ff0c3e230b89a | 4692282 | 24 mins ago | 0x08dadc028935546e424d4785f559e0158822fa97 | OUT | CryptoKittiesSalesAuction | 0.022996086364409 Ether | 0.003772
-- | -- | -- | -- | -- | -- | -- | --
0x171b9c2e414931ebd60da640f944066c14a7cb37ab9d539c390ad5a51533009c | 4692260 | 30 mins ago | 0x08dadc028935546e424d4785f559e0158822fa97 | OUT | CryptoKittiesSalesAuction | 0.023999424205054 Ether | 0.002254
0xec04c237061b21c85a870ead9b3e7e4d0d840f373c0d5bee45ba7296e140259c | 4692235 | 35 mins ago | 0x08dadc028935546e424d4785f559e0158822fa97 | OUT | CryptoKittiesSalesAuction | 0.022051573946759 Ether | 0.00154357
0xbc99cf27c4c0e612c717a042a3b9c4b6a7de1fd26683fa59672a5b35ba06e344 | 4692225 | 39 mins ago | 0x08dadc028935546e424d4785f559e0158822fa97 | OUT | CryptoKittiesSalesAuction | 0.025049512785879 Ether | 0.000996912
0x292cd471747ec268442eb2d08c7cbaeca4eee7ab1bcd5656571e67a974361e0e | 4692073 | 1 hr 15 mins ago | 0x08dadc028935546e424d4785f559e0158822fa97 | OUT | CryptoKittiesSalesAuction | 0.01899859142552 Ether | 0.0010143
0xc9116af09dc9ecfe43a3906c951d317c64c62f53f7d5747b859132f94e87af94 | 4692054 | 1 hr 19 mins ago | 0x08dadc028935546e424d4785f559e0158822fa97 | OUT | CryptoKittiesSalesAuction | 0.025 Ether | 0.000988944
0x835c1c59cbb4c643f048e052f6c4b2ed9e3750dc3e7b9c8e998779f6f883c7e4 | 4682538 | 1 day 18 hrs ago | 0x8412ea13b010f8ffd3bfc1799f70e5018b1639bf | IN | 0x08dadc028935546e424d4785f559e0158822fa97 | 0.03356773 Ether | 0.00063

**Comment by tmashuang** [comment]
Estoy usando una aplicación de traducción.
Las transacciones fallidas se deben a un error de contrato. Por favor, contrata CytoKitties con tu problema.
