### ISSUE TITLE
Add generic type to useConfirmContext hook

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-extension#26989]
Using generic typing in useConfirmContext hook to avoid typecasting:

Before
```
const { currentConfirmation } = useConfirmContext() as {
    currentConfirmation: SignatureRequestType;
  };
```

After
```
  const { currentConfirmation } = useConfirmContext<SignatureRequestType>();
```

**Comment by DanielTech21** [comment]
Hello @jpuri 

Thank you for raising this query to us.

Our team will look into this and let you know if you need more information.
