### ISSUE TITLE
Error: Gave up submitting after 24.0 hours.

### ISSUE THREAD

**Issue by Didi1992** [MetaMask/metamask-extension#2700]
![42ceffa1-25be-4954-ad66-fc08141f76d5](https://user-images.githubusercontent.com/34354587/33741182-2aa655f4-dbc5-11e7-998f-cbc20f287f86.jpg)
using exchange etherdelta can't make a single transaction get permanently error Gave up submitting after 24.0 hours.
![42ceffa1-25be-4954-ad66-fc08141f76d5](https://user-images.githubusercontent.com/34354587/33741209-459cc0dc-dbc5-11e7-905a-b2b892b30881.jpg)

**Comment by tmashuang** [comment]
For the most recent error, try increasing the gas price for transactions.
