### ISSUE TITLE
Can't transfer ER20 tokens from MetaMask - will only send ETH

### ISSUE THREAD

**Issue by DaveDave1290282** [MetaMask/metamask-extension#2702]
Hi,

I am trying to transfer ER20 tokens (VEE or ENG) from MetaMask to an exchange. I am using myetherwallet.com, I use the send tokens options, it can find the tokens etc, but when it goes to the actual transfer page, this is what happens:
![eng](https://user-images.githubusercontent.com/34355754/33743552-99269bb4-dbad-11e7-9a68-4b18dca1d74b.png). So then I click proceed, and metamask opens a window. The problem is that in that window I can only select ETH, of which I have almost nothing. I can't select the token I want to send, in an way. This is really frustrating since I need to get the tokens to an exchange so I can change them to BTC (they are losing value with the hour). This is what I see in MetaMask:
![eng2](https://user-images.githubusercontent.com/34355754/33743598-de9f02c6-dbad-11e7-83d1-7d4346bfb8ec.png)

Your help or feedback is greatly appreciated! Thank you!

Dave

**Comment by tmashuang** [comment]
I agree that the transaction confirmation window for token sending has no reference of the token. The screen being shown indicates the recipient is the Token Contract and calls a function to transfer ownership of the tokens. We are currently improving this screen  tokens.

**Comment by Trancenow** [comment]
Same issue cannot send ANYTHING except ETH or BTC!??

**Comment by famemon78** [comment]
exact same issue why isnt there a single solution listed? can someone help pls

**Comment by bdresser** [comment]
@famemon78 first make sure you're on the "new" UI, should look like the below. If it doesnt, click the top-right menu and "Try Beta!"

<img width="387" alt="screen shot 2018-11-14 at 11 38 24 am" src="https://user-images.githubusercontent.com/1016190/48497292-d753ba00-e801-11e8-835b-336ba98bf84f.png">

From the above screen, click the three-line menu on the left side. Click the token you want to send. Then click the "Send" button in the middle of the screen.

**Comment by famemon78** [comment]
thank 

> @famemon78 first make sure you're on the "new" UI, should look like the below. If it doesnt, click the top-right menu and "Try Beta!"
> 
> <img alt="screen shot 2018-11-14 at 11 38 24 am" width="387" src="https://user-images.githubusercontent.com/1016190/48497292-d753ba00-e801-11e8-835b-336ba98bf84f.png">
> 
> From the above screen, click the three-line menu on the left side. Click the token you want to send. Then click the "Send" button in the middle of the screen.

thank you so much! it worked perfectly

**Comment by scardinal3** [comment]
CANNOT SEND ANY ERC20 WITH METAMASK SO 8i)(**ENDk frustrating!!!!!
