### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by moneykicks007** [MetaMask/metamask-extension#2703]
Hey Please Help! I tried to make a transaction on ED via Metamask but It's showing this "There was an error when resubmitting this transaction"  It's still showing as pending transaction
How can I fix this?  

<img width="357" alt="screen shot 2017-12-07 at 4 58 18 pm" src="https://user-images.githubusercontent.com/34356304/33744718-e155a03a-db6f-11e7-9660-cf5289b41d1f.png">

**Comment by tmashuang** [comment]
Please send your transactions logs to https://support.metamask.io. Here's a guide to obtain your transaction logs within MetaMask, https://support.metamask.io/kb/article/15-copying-state-logs/
