### ISSUE TITLE
Transaction failed but the ether is gone!

### ISSUE THREAD

**Issue by aliarkani** [MetaMask/metamask-extension#2705]
Hello
I had several transactions in cryptokitties that failed, but my ether was reduced twice. here is my transaction history:
![1](https://user-images.githubusercontent.com/34370674/33762956-dc5ed006-dc23-11e7-9f7d-26ae07c67fec.jpg)
Please help.

**Comment by tmashuang** [comment]
Failed transactions still require gas, transaction, fees. Could the gas fee for all the failed transactions be the potential issue?

**Comment by aliarkani** [comment]
Thank you for the reply, it seems you are right.
 

    On Friday, December 8, 2017, 5:40:46 PM GMT+3:30, Thomas Huang <notifications@github.com> wrote:  
 
 
Failed transactions still require gas, transaction, fees. Could the gas fee for all the failed transactions be the potential issue?
