### ISSUE TITLE
[Bug]: Gas - Save Advanced Gas button is disabled without any error

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27089]
### Describe the bug

Whenever I'm trying to send a transaction, if the value of the `eth_estimateGas` rpc call returns a value outside the gas limit range, I see that if I try to Edit the Gas, clicking Advanced gas fees, the button for Save is always disabled, without displaying any error.

### Expected behavior

The gas form is currently split into 2 pieces, which doesn't seem ideal, as it leads to this kind of problem to arise. We have 3 input values for edit:
- Max base fee
- Priority fee 
- Gas limit input

but there is only validation on the first 2, unless you click explicitly Edit the Gas limit, then there will be validation for the 3rd one, otherwise there isn't. 
This way of constructing the form (into 2 separate pieces) makes that if the Gas limit value is not correct, but you don't explicitly click Edit, you won't be able to change any value as Save button will always be disabled, without any error displayed.

### Screenshots/Recordings

https://github.com/user-attachments/assets/eb6d5feb-4b9e-4350-b4f2-e3eb7883e24f

### Steps to reproduce

1. Import a Tenderly Mainnet work (seed your account with an ERC20 token and ETH)
2. Start a Send ERC20 token
3. Add recipient and value
4. In the last confirmation screen, click Edit gas
5. Try to change gas values--> see Save button is always disabled without any error displayed

### Detection stage

In production (default)

### Version

12.2.3

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by pedronfigueiredo** [comment]
The gas limit returned by the provider should supersede the suggested dapp suggested gas limit, allowing the user to proceed in this case.
