### ISSUE TITLE
Transaction Underpriced

### ISSUE THREAD

**Issue by yungwolf** [MetaMask/metamask-extension#2708]
Trying to move alt coins from wallet to ED. I have set up the Gas to 52 GWEI and it still gives me the error message of transaction underpriced. I have enough Ether in my wallet but it won't allow me to deposit any of my alt coins from my wallet to ether delta to trade. Any tips?

**Comment by tmashuang** [comment]
The error you are experiencing with transactions is hitting the whole network. Everyone has reported this issue and we have implemented a minimum gas price cap. Transactions lower than the recommended gas price for the network are susceptible to wait and have a high likely chance to fail. We try our best to estimate a gas price that is likely to produce a transaction that is successful. To view a recommended gas price for successful transaction please use [Ethgasstation]( https://ethgasstation.info). Transactions with a recommended gas price, or 10% higher, have a higher chance to be successful. To prevent further contribution to the congestion, after a transaction is made and pending, please check the transaction on [Etherscan](https://etherscan.io) by clicking the transaction on MetaMask or inputting your public Ethereum address on Etherscan to ensure that your transaction has been submitted.
