### ISSUE TITLE
[Bug]: Transactions - When trying to Cancel/Speed up a transaction I see `undefined` 10% increase

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27092]
### Describe the bug

When I've submitted a transaction and I try to Cancel or Speed it up, I see `undefined` 10% increase

![Screenshot from 2024-09-12 08-55-58](https://github.com/user-attachments/assets/e898d643-cac2-40b7-b9b2-7a079402f8c6)

### Expected behavior

This happens anytime I try to Send a transaction, and Confirm it right away --> if I edit the gas in the last confirmation screen, and wait some seconds, then I see this below, which seems the expected behaviour

![Screenshot from 2024-09-12 09-05-25](https://github.com/user-attachments/assets/7e9844f0-7e16-410f-a982-d92794a4784a)

### Screenshots/Recordings

Repro:

https://github.com/user-attachments/assets/5c10664a-4cb7-41d9-9ff4-59593c652f1d

### Steps to reproduce

1. Start a transaction
2. Confirm it
3. Click Speed up/Cancel
4. See `undefined` 10% increase

### Detection stage

In production (default)

### Version

12.2.3

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/28840 so we track it in a single place
