### ISSUE TITLE
Misleading UI when Resubmission Is Cancelled

### ISSUE THREAD

**Issue by brandoncurtis** [MetaMask/metamask-extension#2709]
If you click the "retry with higher gas" button and then reject the retry transaction, it shows the original transaction as rejected even if the original transaction goes through:

![mm-ux-cancel](https://user-images.githubusercontent.com/2591290/33783478-d8d7c292-dc11-11e7-81f0-343c3b5c0b0d.png)

**Comment by danfinlay** [comment]
That's true, this was added pretty urgently to deal with CryptoKitty filled blocks.

A better solution will need some consideration, of how we handle retries long-term.

**Comment by whymarrh** [comment]
This issue looks like it's pertaining to the old MetaMask UI, which we no longer support. We welcome feedback on the current UI—if you're still experiencing a similar issue please open up a new issue.
