### ISSUE TITLE
[Bug]: Smart Transaction - When having a STX in a pending state, if I trigger a dapp Connection I see an incorrect screen and cannot do anything until STX is Confirmed

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27098]
### Describe the bug

When I've submitted a smart transaction (in the status of pending) if I then trigger a dapp connection action, I see a wrong MM screen.
That screen is displayed until the STX is confirmed. Once that happens, I see the expected connect screen.

Note: this is similar to [this other issue](https://github.com/MetaMask/metamask-extension/issues/26706) which was fixed, in the sense that the wrong screen I was seeing there, is the same as the one I see here, though the repro steps are different.

cc @adonesky1 though not sure if it's a problem in the API or in the STX side

### Expected behavior

We should see the connect screen

### Screenshots/Recordings

![Screenshot from 2024-09-12 12-31-14](https://github.com/user-attachments/assets/48648c28-6776-4c7d-a06e-e8ca566c95eb)

https://github.com/user-attachments/assets/bb4be8db-6d38-4f41-b070-e3e6ff953a84

### Steps to reproduce

1. Make sure you have STX enabled from settings
2. Trigger a tx from another dapp, e.g. uniswap. I.e.,you cannot use the wallet send flow.
3. Confirm
4. Go to test dapp
5. Click Connect --> this needs to happen while STX is pending
6. See wrong screen
7. Wait until the tx is confirmed
8. See how now the Connect screen is displayed

### Detection stage

During release testing

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by dbrans** [comment]
Hi @seaona – I'm not able to reproduce this on mainnet using [this chrome build](https://github.com/MetaMask/metamask-extension/pull/26973#issuecomment-2349241228).

**Comment by dbrans** [comment]
Looping in transactions and wallet-api teams

**Comment by dbrans** [comment]
Just reproduced the issue – the pending transaction has to be triggered by a dapp, not through the wallet send flow. I’ll update the steps to reflect this!

**Comment by dbrans** [comment]
Hi @seaona – I am also able to reproduce this in 12.2.3.

**Comment by seaona** [comment]
hi there :wave: I've checked 12.2.3 and it's not happening to me.
After investigating, I've noticed that in the prod version, we don't support STX in Sepolia so that's possibly the reason why I couldn't repro, as I was testing with Sepolia.

If you confirm this is repro in prod, then we can remove the release blocker label


https://github.com/user-attachments/assets/d9fe7aab-16bb-4dfb-b04c-a31245859790

**Comment by dbrans** [comment]
Hi @seaona – here is a recording of mainnet with 12.2.3.

https://github.com/user-attachments/assets/3b9c64f4-e244-4756-9736-718e6d67cdb9
