### ISSUE TITLE
Fix "Trezor Hardware derives the correct accounts" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27104]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/99981/workflows/74b00c47-b958-437d-9e4b-9b9940383de2/jobs/3721933/tests

Test scenario - Trezor Hardware derives the correct accounts
Test Path - test/e2e/tests/hardware-wallets/trezor-account.spec.js
Build - Webpack

```
Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/circleci/project/test/e2e/tests/hardware-wallets/trezor-account.spec.js)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
```

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
