### ISSUE TITLE
Fix "Send ERC20 token to contract address should display ..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27103]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/99802/workflows/771b56a0-4f4d-476a-9782-ed8a16f72c6b/jobs/3715329/tests

Build - webpack
Test scenario - Send ERC20 token to contract address should display the token contract warning to the user
Test Path - test/e2e/tests/tokens/send-erc20-to-contract.spec.js

```
Error: SES_UNHANDLED_REJECTION:
  (Ran on CircleCI Node 0 of 20, Job test-e2e-chrome-webpack)
    at withFixtures (test/e2e/helpers.js:224:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (test/e2e/tests/tokens/send-erc20-to-contract.spec.js:14:5)
```

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
