### ISSUE TITLE
i deposit US10 from bitcoin 10 hours ago and my account is still in 0

### ISSUE THREAD

**Issue by Beetleboom** [MetaMask/metamask-extension#2711]
i deposit US10 from bitcoin 10 hours ago and my account is still in 0

address 0x78cAe41b53058012eeBDA084B0003C07ECB14812

**Comment by brandoncurtis** [comment]
Can you provide more details about your transaction?

Here are the transactions involving your address that have gone through: https://etherscan.io/address/0x78cae41b53058012eebda084b0003c07ecb14812

**Comment by tmashuang** [comment]
@Beetleboom Did you use a service to convert BTC to ETH?

**Comment by tmashuang** [comment]
Closing.
