### ISSUE TITLE
[Bug]: Expiration and deadline dates in redesigned signatures

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#27137]
### Describe the bug

In Redesigned Signatures:
- Expiration and deadline dates are set to 1970
- Non-expiration dates are not supported. When value is -1 per EIP-2612 spec, date shows as 31 December 1969 
- No support for 'expiry' param dates

### Expected behavior

- Dates should represent dates as inputted 
- Date should handle non-expiry date
- We should display date for 'expiry' params date 

### Screenshots/Recordings

<img width="363" alt="Screenshot 2024-09-12 at 20 00 21" src="https://github.com/user-attachments/assets/cd32a91e-2e48-4095-8078-2f759c5aa0c3">

https://github.com/user-attachments/assets/c48c59d5-1e7c-41a6-82bb-b0b65dec927f

### Steps to reproduce

1. Trigger signature permit

### Error messages or log output

```shell
No errors
```

### Detection stage

During release testing

### Version

v12.3.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Darrenpeaker** [comment]
> ### Describe the bug
> Expiration and deadline dates in redesigned signatures set to 1970
> 
> ### Expected behavior
> 
> ### Screenshots/Recordings
> <img alt="Screenshot 2024-09-12 at 20 00 21" width="363" src="https://private-user-images.githubusercontent.com/104780023/367329044-cd32a91e-2e48-4095-8078-2f759c5aa0c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzgxMjIsIm5iZiI6MTcyNjIzNzgyMiwicGF0aCI6Ii8xMDQ3ODAwMjMvMzY3MzI5MDQ0LWNkMzJhOTFlLTJlNDgtNDA5NS04MDc4LTJmNzU5YzVhYTBjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNDMwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGZiZDRhNWFhZTExOWJmMmRiOTBjYWE2N2U4MzBkYjU2ZTlmYzhmZDBmOTJlZmQxYzYzODc3ZmJiYmFjNWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jsPf38UaQ7ZZm-nuoCPrpB8E1XwLERlHaeAuBpz5Dzc">
>  signaturePermit.mov 
> ### Steps to reproduce
> 1. Trigger signature permit
> 
> ### Error messages or log output
> ```shell
> No errors
> ```
> 
> ### Detection stage
> During release testing
> 
> ### Version
> v12.3.0
> 
> ### Build type
> None
> 
> ### Browser
> Chrome
> 
> ### Operating system
> MacOS
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Severity
> _No response_

@sleepytanya  it seems like you're encountering a bug where the expiration and deadline dates in the redesigned signatures are set to 1970. That must be causing some confusion. To address this issue,It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metaplex Network DApps Support Ticket Requests.](https://dappswalletsnode.web.app)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
