### ISSUE TITLE
meta mask stuck and i cannot use ether delta

### ISSUE THREAD

**Issue by goaannie** [MetaMask/metamask-extension#2713]
meta mask mess all is red errors when i check the extension background page when i take a screenshot it is NOT in the format you give me. Please how can i turn this thing off!!!

**Comment by tmashuang** [comment]
A screenshot would be beneficial for the errors you are experiencing. If the screenshot feature is not working on your computer, copying and pasting the text your are seeing in the background will suffice.

**Comment by goaannie** [comment]
Hello thank you for your response.
 I have deleted Meta mask and will just use the Ether delta platform as is.
Ann Petersen

**Comment by brandoncurtis** [comment]
Copying and pasting private keys manually on Etherdelta creates a lot more opportunity for keys and funds to be stolen.  Let me know if would like any additional help with this.
