### ISSUE TITLE
Fix ci to allow running jobs for forks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27135]
### What is this about?

Jobs:
- [ ] Sonar Cloud
- [x] get-changed-files-with-git-diff

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by gauthierpetetin** [comment]
Can be split into 2 sub-tasks

**Comment by OSHORDESMOND** [comment]
Release
