### ISSUE TITLE
The fox icon [logo] on the top left should navigate to widget home 

### ISSUE THREAD

**Issue by srameshr** [MetaMask/metamask-extension#2715]
Briefly describe the issue you've encountered
  *  Expected Behavior: Clicking on the fox icon [logo] on the top left should navigate to widget home screen or provide a home icon.
![screen shot 2017-12-09 at 8 03 21 pm](https://user-images.githubusercontent.com/8149408/33796534-0f4712fa-dd1c-11e7-9898-dddc8d7e2bf0.png)

  *  Actual Behavior: It does not

  *  Browser Used: Chrome
  *  Operating System Used: Mac High  Sierra

**Comment by tmashuang** [comment]
Closing in favor of #2712.
