### ISSUE TITLE
[Bug]: Network toast appears only for direct transactions

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#27151]
### Describe the bug

 Network toast appears on the second confirmation screen so it is displayed only for direct transactions, for send+swap MM doesn't show network notification

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/9143c1c7-63bb-45d5-9df9-4e631b093f9d

### Steps to reproduce

1. Submit transaction on any network
2. Switch to another network
3. Start send+swap transaction
4. Observe that the network toast is not disaplayed

### Detection stage

During release testing

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Closing as this is expected. The toast should only appear for dapp proposed confirmations as for the in-wallet ones the flow itself of selecting assets already gives the user context on the network they are on.

**Comment by sleepytanya** [comment]
@bschorchit 

In 12.4.0. the network toast is displayed for wallet initiated transactions and only for direct ones, so if the first transaction on newly selected network is send+swap the toast will be displayed only for the second direct send transaction:



https://github.com/user-attachments/assets/d1f5abf1-52cc-47cf-ba3f-08551b399190
