### ISSUE TITLE
File upload is broken in production but not in development

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/metamask-extension#27167]
The file upload component in Snaps UI is broken in production, but not in development. In production it fails with an error like "arrayBuffer is undefined". Potentially it's a LavaMoat policy issue, but I haven't looked into it further.

**Comment by gauthierpetetin** [comment]
Hi @Mrtenz , how crucial is the file upload feature here?
(we're trying to assess if this is a sev2 or a sev1)

**Comment by Mrtenz** [comment]
> Hi @Mrtenz , how crucial is the file upload feature here? (we're trying to assess if this is a sev2 or a sev1)

I don't think any Snap is using this yet, so it's not very crucial. @hmalik88 is looking into resolving it.

**Comment by weizman** [comment]
This issue will be closed once #27386 is merged, as it addresses a bug within snow that causes this issue
