### ISSUE TITLE
Metamask unlogged - don't have the seed

### ISSUE THREAD

**Issue by bernardorq** [MetaMask/metamask-extension#2719]
Hi guys,

I restarted my macbook and my metamask unlogged for some reason. I don't know where I stored my seed. I have my main ETH address and the metamask password. Is it possible to recover it? Any help is very welcome.

Best,
Bernardo

**Comment by brandoncurtis** [comment]
It's not possible to recover the phrase from an address and the password.

If you haven't backed up the seed phase and you haven't used the same seed phase to log into MetaMask on another machine or browser (or another BIP-39 compatible software or hardware wallet) or manually exported the account's private key, I don't believe it's possible to recover.

If you have access to a system-wide backup that includes your browser's configuration files, this article describes how to export the extension's data: http://metamask.consensyssupport.happyfox.com/kb/article/22-how-to-copy-your-vault-data

**Comment by danfinlay** [comment]
Sometimes browsers spontaneously wipe their storage, and that sounds like what happened here.

If you have backups of your computer from when MetaMask was working, you can use those to restore your vault.

Without that or your seed phrase backed up, there is nothing we can do for you.
