### ISSUE TITLE
Handle new type of estimateGas error: Failing tx

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2720]
```
{"jsonrpc":"2.0","id":3520039121240,"error":{"code":-32000,"message":"gas required exceeds allowance or always failing transaction"}}
```

Apparently we interpret this as "gas limit 0", which means we're suddenly not correctly warning about on-chain errors.

**Comment by egalano** [comment]
Checking our infura node configs but we did not make any gas config updates today

**Comment by egalano** [comment]
It looks like this error is returned by geth 1.7.3 due to the changes implemented here https://github.com/ethereum/go-ethereum/pull/15477 . We will roll back Infura nodes to geth-1.7.2 as a hotfix until we you are able to release an update to handle the new behavior.

**Comment by parliament718** [comment]
on point and perfect timing. I was getting this error calling giveBirth() in the Cryptokitties contract. Reverting to geth 1.7.2 fixed it. y'all saved my night. thanks!

**Comment by almindor** [comment]
Can someone confirm if this new error from Geth is returned wrongly at times? I'm getting it on calls to ERC20 compatible contract's Transfer method in cases where the value is > 0. Oddly enough if the value is 0 it works ok and I can't see anything wrong with the RLP of the data.

**Comment by avinashvattikutti** [comment]
hello everyone
I am not able to create contract address! when environoment is web3
could anyone please help me out
