### ISSUE TITLE
Fix "Test Snap Get Locale test snap_getLocale functionali..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27248]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/100773/workflows/d9897eaf-76ac-4069-9b92-6de8338f0c2c/jobs/3752071/tests

Build - Flask
Browser - Firefox
Test Path - /test/e2e/snaps/test-snap-get-locale.spec.js
Test Scenario - Test Snap Get Locale test snap_getLocale functionality

```
TimeoutError: Waiting for element to be located By(xpath, //p[contains(text(), "Localization Example Snap")])
Wait timed out after 10105ms
  (Ran on CircleCI Node 2 of 10, Job test-e2e-firefox-flask)
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```
![image](https://github.com/user-attachments/assets/cfcf5a59-c89c-48bd-949b-a36f048c14a1)

**Comment by chloeYue** [comment]
close this ticket as this test is not flaky anymore
