### ISSUE TITLE
[Bug]: Fix Permit token decimal amounts

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#27243]
### Describe the bug

If no contract was found within the Permit DataTree component, we should use the verifiedContract tokenDecimals. Passing the verifiedContract's tokenDecimals, when no decimals are found for this contract, will apply the default 18 token decimals. This is missing. Notice in the screenshot that Spending Cap displays "< 0.000001", while Message > Value displays "3,000". Value should also display "< 0.000001".

### Details of applying default 18 token decimals to Redesigned Permit

When we adopted `fetchErc20Decimals` for Permit Simulation, we enforced a default of 18 token decimals to be used when no token decimals were found in the details. `fetchErc20Decimals` is the same method used in `ui/pages/confirmations/components/simulation-details/useBalanceChanges.test.ts` which is why we adopted it.

Previously, clicking on test-dapp > Permit would display 3,000. Now, it displays 0 < 0.000001. 

@dbrans: 

> 18 is the common convention for ERC20 tokens, largely due to OpenZeppelin's widely-used [implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L21-L22). Vitalik [proposed](https://github.com/ethereum/EIPs/issues/724) making it a required standard, though it didn’t gain momentum. [EIP-1046](https://eips.ethereum.org/EIPS/eip-1046) also suggests 18 as the default if decimals() isn’t implemented.
>
> That said, some platforms, like Etherscan and certain wallets, default to zero when decimals() isn't defined, so there's a lot of inconsistency out there. 

### Screenshots/Recordings

Notice that Simulation > Spending Cap value does not match Message > Value

![CleanShot 2024-09-18 at 17 53 09@2x](https://github.com/user-attachments/assets/b31f0964-9602-4284-bcf0-3fe1a49c7703)

### Steps to reproduce

1. Go to test-dapp
2. Click Permit button
3. Observe Spending Cap and Message > Value

### Detection stage

On the development branch

### Version

12.2.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
As discussed in the DSU, we can adopt the 18 decimals as the fallback and add metrics to capture when we fail to fetch decimals. 
For metrics, we can re-use this event that we created for simulations: 

event: `Incomplete Asset Displayed`

properties:
`token_decimals_available`: false
`asset_address`: < token address >
`asset_type: `erc20
`chain_id`: < chain id >
`location`: confirmation

**Comment by digiwand** [comment]
thank you @bschorchit! I created a separate ticket for this one: https://github.com/MetaMask/metamask-extension/issues/27333
