### ISSUE TITLE
is that possible to login metamask by using private key?  (seeds are lost)

### ISSUE THREAD

**Issue by dimitar9** [MetaMask/metamask-extension#2725]
Should this provide restore account by private key in front page?
now I noticed you have to create a new account, then from that, you can restore account by private key.

**Comment by tmashuang** [comment]
A vault/DEN/accounts would need to be loaded into MetaMask before an account can be imported into MetaMask. Please follow https://support.metamask.io/kb/article/7-importing-accounts to import through a private key. Importing through a private key will result in a 'Loose' label and the private key's primary recovery option will be the private key, not the seed phrase that a vault/DEN/accounts. Read more on Loose accounts referenced here, https://support.metamask.io/kb/article/6-loose-accounts

**Comment by ttmc** [comment]
The linked Metamask support pages no longer exist.
