### ISSUE TITLE
Create a client config util with unit testing for feature flags

### ISSUE THREAD

**Issue by vthomas13** [MetaMask/metamask-extension#27253]
### What is this about?

Include client config api fetch calls for both endpoints (all flags & single flag)
Include unit testing for that util

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by DDDDDanica** [comment]
Implement a controller to consume api instead
