### ISSUE TITLE
Insufficient balance for transaction . DECEMBER. 5 ETH in

### ISSUE THREAD

**Issue by ands77** [MetaMask/metamask-extension#2726]
I Imported 5 ETH to Metamask for Ethadelta. Plus another 0.673 for gas. But I cannot move, the 5 ETH back to Metamask  or move any ETH because message at MetaMask of "Insufficient balance for transaction" shows during Ethadelta transactions, and constant on Metamask. It has worked fine in the past with loaing ETH.

I have trie to download the state logs an have ha big problems trying to convert to a file you accept.  I have spent 6 hours getting to this stage here!1! I am not a computer person.

Kind regars,

Andy
![metamask problem 1](https://user-images.githubusercontent.com/34435054/33821205-df710408-deb7-11e7-97e1-7af7ed9374de.PNG)

**Comment by ands77** [comment]
here also is a top up for Metamask, with still no traansaction power to get my ETH back into Metamask. It keeps say get a valid adress. I have left no gaps for the Metamask adress I put in. It shoul be all goo, but its not. 
https://etherscan.io/tx/0x260b3cd33cd5ae33fac345b0c174507bc5ee82291500dcfb226327e209ae7888 deposite ETH METAMASK  .3

**Comment by brandoncurtis** [comment]
Hello!  It looks like you may be trying to "withdraw" from EtherDelta by executing another "deposit".  When you deposit, it's placed into the EtherDelta smart contract where it can be traded on your behalf; to withdraw, you need to click on the "Withdraw" tab (second tab, top left-hand corner), specify an amount, and then click the "Withdraw" button to execute the transaction.

Let me know if this answers your question!

**Comment by ands77** [comment]
Thanks. All fixed

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com

14. Dec 2017 13:34 by notifications@github.com:

**Comment by cryptokingca** [comment]
Hi i am unable to transfer around 0.1918457 ETH from Matamask. in the past i have transferred ETH in smaller denominations with NO issues. where ever i try to send the 0.1918457 ETH , i get a message " insufficient balance for transaction" 
Please a\help

**Comment by Markov123** [comment]
Hi wanna send also around 0.3 ETH from Metamask and i have same issue. I create a ticket for metamask. Hope they will answer fast.

**Comment by fylim** [comment]
Same here. Made multiple transactions earlier and it works fine
