### ISSUE TITLE
Metamask injects script tags into XML documents

### ISSUE THREAD

**Issue by ScottyMJacobson** [MetaMask/metamask-extension#2727]
*  Expected Behavior:

MetaMask only injecting itself into contexts that are I guess .html pages (or some other heuristic to know that it's not a raw data response)

  *  Actual Behavior

MetaMask injects itself into my XML ad tags

  *  Browser Used

Chrome 62.0.3202.94

  *  Operating System Used

Mac OS X Sierra 10.12.6

Also, on a separate note, it looks like line-style (`//`) comments are preserved in the minified script; my beautifier seems to think this comments out everything until the end of the script (because there are no newlines), but I can't [definitively interpret the ECMAScript spec](https://www.ecma-international.org/ecma-262/5.1/#sec-7.4) in a way that supports that conclusion (it's been a while since I've read language specs)

<img width="1248" alt="screen shot 2017-12-11 at 11 51 23 am" src="https://user-images.githubusercontent.com/8656857/33843229-c71d2cd0-de6a-11e7-8089-d496798f9df2.png">

**Comment by tmashuang** [comment]
Should have been fixed in #2662. Closing for now. If there is still an issue, reopen.
