### ISSUE TITLE
[Bug]: Isssues when interacting with WETH on Base (contract: 0x4200000000000000000000000000000000000006)

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#27288]
### Describe the bug

The Base network is experiencing occasional variability in its quote fetching capabilities. At times, it efficiently retrieves quotes for all tokens, but in certain instances, only a limited number of tokens receive quotes. Additionally, there are moments when the quote fetching feature may temporarily become non-functional.
While investigating issues related to Base, it was noted that a similar temporary issue might also affect zkSync ERA. However, all other popular networks appear to be unaffected (not 100 % sure).
The quotes issue is also present in the mobile app (I included mobile recording).
Probably related - https://github.com/MetaMask/metamask-mobile/issues/10834

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/3c298ee8-4f49-4280-9f1f-73ead52bd3c5

https://github.com/user-attachments/assets/d7827e02-ca54-444a-8127-facddc5568c1

https://github.com/user-attachments/assets/14e0f512-2a10-4d73-b8b1-a2852f9a0fa9

![Screenshot 2024-09-18 at 19 07 15](https://github.com/user-attachments/assets/a14a8dbe-c79e-47ed-8659-68311d2ad30c)

### Steps to reproduce

1. Connect to Base
2. Start swap
3. 

### Detection stage

During release testing

### Version

12.3.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by ejwessel** [comment]
issue has been resolved with the `metamask-transactions` team
