### ISSUE TITLE
Remove the description for "current language" from the extension settings

### ISSUE THREAD

**Issue by SayaGT** [MetaMask/metamask-extension#27280]
### What is this about?

To have the parity with other patterns on the page, remove the "selected language" that appears as description for the setting. The dropdown selector indicates the selected language, so we don't need to repeat in the description. See screenshot below.

![image](https://github.com/user-attachments/assets/988321d2-f8ab-4032-87c2-dd8ca8505253)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by alfeng6** [comment]
Marking as done because of this: https://github.com/MetaMask/metamask-extension/pull/27097
