### ISSUE TITLE
Kovan transaction receipts are missing status property

### ISSUE THREAD

**Issue by nt85** [MetaMask/metamask-extension#2730]
Briefly describe the issue you've encountered
  *  Expected Behavior
Calling web3.eth.getTransactionReceipt returns a receipt with a valid status property
  *  Actual Behavior
Calling web3.eth.getTransactionReceipt returns a receipt with a null status property
  *  Browser Used
Chrome Version 63.0.3239.84
  *  Operating System Used
MacOS High Sierra 10.13.1

Example code to reproduce the issue. It only occurs on the Kovan network. Any transaction seems to have this problem.
```
window.addEventListener('load', function()
{
    window.web3 = new window.Web3(window.web3.currentProvider);
    window.web3.eth.getTransactionReceipt("0xfd02557ba3d4cd0b3acb38922fd7ecaf4824c3a23a78a89967194b722855617e", function(err, result)
    {
        console.log(result); 
        console.log("status: " + result.status); 
    });
});
````

**Comment by brandoncurtis** [comment]
Hello!  Kovan has not yet implemented the Byzantium hardfork that will add the status feature proposed in [EIP-658](https://github.com/ethereum/EIPs/pull/658).

From the [Ethereum blog](https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement/),

> The way to detect failed transactions will change with Byzantium, even for contracts created before the Byzantium hard fork is enacted. After the fork, eth.getTransactionReceipt(…) will return a status field. The status field has a value of 0 when a transaction has failed and 1 when the transaction has succeeded.

Mainnet implemented Byzantium at block 4,370,000, which occurred in mid-October; Kovan will implement Byzantium on block 5,067,000, which should arrive tomorrow (Thursday 2017-12-14)!

**Comment by nt85** [comment]
Ah, makes sense. I didn't realize kovan hasn't upgraded yet. Closing this issue
