### ISSUE TITLE
Fix "Import flow @no-mmi Import wallet using Secret Recov..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27337]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101671/workflows/7916cc8f-082c-4486-8cc0-36802704df43/jobs/3785883/tests

Build - Regular
Browser - Chrome
Test Scenario - Import flow @no-mmi Import wallet using Secret Recovery Phrase with pasting word by word
Test Path - /test/e2e/tests/account/import-flow.spec.js

```
TimeoutError: Waiting for element to be located By(css selector, [data-testid="account-list-menu-details")
Wait timed out after 10005ms
  (Ran on CircleCI Node 17 of 20, Job test-e2e-chrome)
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![image](https://github.com/user-attachments/assets/0caea5ce-c94e-45a7-96c5-5e642a3d93c6)

**Comment by chloeYue** [comment]
Close this ticket because duplicate with https://github.com/MetaMask/metamask-extension/issues/27336
