### ISSUE TITLE
[Bug]: Cannot sign typed data with primaryType: "Permit"

### ISSUE THREAD

**Issue by jiaqi-aperture** [MetaMask/metamask-extension#27356]
### Describe the bug

Hi I am facing a `new BigNumber() not a number: undefined` issue when calling the `signTypedData` function from viem: https://viem.sh/docs/actions/wallet/signTypedData.html

Weirdly, there is no problem with Metamask version 12.0.6 and before. Could you help to check? 

There is no problem with other `primaryType`s, except `primaryType: "Permit",`.

Thank you in advance and have a nice day.

### Screenshots/Recordings

![Screenshot 2024-09-24 at 15 46 51](https://github.com/user-attachments/assets/dfdf2602-ef24-4177-9933-8d88b9aa105d)

### Steps to reproduce

Calling the `signTypedData` function from viem with the following parameter:

```
{
        account: "0xdC333239245ebBC6B656Ace7c08099AA415585d1",
        types: {
          Person: [
            { name: "name", type: "string" },
            { name: "wallet", type: "address" },
          ],
          Permit: [
            { name: "from", type: "Person" },
            { name: "to", type: "Person" },
            { name: "contents", type: "string" },
          ],
        },
        primaryType: "Permit",
        message: {
          from: {
            name: "Cow",
            wallet: "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826",
          },
          to: {
            name: "Bob",
            wallet: "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB",
          },
          contents: "Hello, Bob!",
        },
      }
```

![Screenshot 2024-09-24 at 19 46 41](https://github.com/user-attachments/assets/e573fe29-f210-4b27-afb5-ab94ce63efb8)

By the way, I just found something interesting, if I turn off the `Improved signature requests` toggle in Experimental settings, the error will be gone.

### Detection stage

In production (default)

### Version

12.1.0

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS

**Comment by ZbrancaI** [comment]
Hey @jiaqi-aperture ! Thank you for reporting this issue to us! We are looking into it!

**Comment by anaamolnar** [comment]
Hi @jiaqi-aperture Could you please update manually to the latest version available and let us know if you still encounter this issue?

**Comment by gaohan137** [comment]
Gentle ping on this thread. It is directly affecting users UX experience. We have to tell them individually to turn off "Improved Signature Requests" as a temporary work around.

**Comment by bschorchit** [comment]
We'll investigate this very soon. 
Do you also have a example of the Permit payload request that users are encountering issues with? I'm curious if its format is something that MM might not be expecting.

**Comment by gaohan137** [comment]
Does this help (see more in the first post in this thread)?

```
{
        account: "0xdC333239245ebBC6B656Ace7c08099AA415585d1",
        types: {
          Person: [
            { name: "name", type: "string" },
            { name: "wallet", type: "address" },
          ],
          Permit: [
            { name: "from", type: "Person" },
            { name: "to", type: "Person" },
            { name: "contents", type: "string" },
          ],
        },
        primaryType: "Permit",
        message: {
          from: {
            name: "Cow",
            wallet: "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826",
          },
          to: {
            name: "Bob",
            wallet: "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB",
          },
          contents: "Hello, Bob!",
        },
      }
```

And see below for what the working version looks like if I'm using version 12.0.5, which is less than `12.0.6` as Jiaqi mentioned above.
![Screenshot 2024-09-24 at 2 23 30 PM](https://github.com/user-attachments/assets/3fa8fc35-1961-4452-a868-b0a34f96340a)

**Comment by bschorchit** [comment]
So the example in the first post seems to be a dummy example. Your screenshot seems to be a real case - let us know if you have the payload or repro steps for it.

We have recently added some validation that checks against the [Permit EIP spec](https://eips.ethereum.org/EIPS/eip-2612) and I think this could be related with what is causing this issue. 

The reason I'm curious about the real example is that even if we fix the crash reported, depending on the payload that is being used, we could still throw an error for it if it doesn't match the spec in the Permit EIP. So it might still not solve the issue.

**Comment by gaohan137** [comment]
@bschorchit Thanks for the prompt response! Here is the a snippet of the real msg to be signed:

```
{"domain":{"name":"Uniswap V3 Positions NFT-V1","version":"1","chainId":42161,"verifyingContract":"0xC36442b4a4522E871399CD717aBDD847Ab11FE88"},"types":{"Permit":[{"name":"spender","type":"address"},{"name":"tokenId","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]},"primaryType":"Permit","message":{"spender":"0x00000000Ede6d8D217c60f93191C060747324bca","tokenId":"3606393","nonce":"0","deadline":"1734995006"}}
```

And also see below for a formatted screenshot. My guess the offending candidate is the big number fields, such as `tokenId: 3606393n`.

![Screenshot 2024-09-24 at 3 09 05 PM](https://github.com/user-attachments/assets/f3c5edca-deef-451d-a808-90706e27de81)

Guidance would be appreciated. Thx a lot!

**Comment by lanceaper** [comment]
Update: @bschorchit 

We updated the Permit structure to include "value" field
![image](https://github.com/user-attachments/assets/6102621e-0524-4abb-9415-49199db0851c)

but the permitInfo actually failed to get verified on UniswapV3NFT contract
![image](https://github.com/user-attachments/assets/42935f13-c398-48f2-b245-e938f5575220)

**Comment by jpuri** [comment]
The permit request above seems to be missing field `value` which is the number of tokens that is creating this issue. According to the EIP https://eips.ethereum.org/EIPS/eip-2612, it is a mandatory field.

```
    {
            domain: {
              name: 'Uniswap V3 Positions NFT-V1',
              version: '1',
              chainId: 1,
              verifyingContract: '0xC36442b4a4522E871399CD717aBDD847Ab11FE88',
            },
            types: {
              Permit: [
                { name: 'spender', type: 'address' },
                { name: 'tokenId', type: 'uint256' },
                { name: 'nonce', type: 'uint256' },
                { name: 'deadline', type: 'uint256' },
              ],
            },
            primaryType: 'Permit',
            message: {
              spender: '0x00000000Ede6d8D217c60f93191C060747324bca',
              tokenId: '3606393',
              nonce: '0',
              deadline: '1734995006',
            },
          }
```
Message above should have a field `value` also.

**Comment by lanceaper** [comment]
We are actually asking approve for NFT token(ERC721), which "value" doesn't make sense here， and will cause verification error on Uniswap side.

**Comment by lanceaper** [comment]
We're actually following the standard [EIP-4494 Advancing the NFT standard: ERC721-Permit](https://soliditydeveloper.com/erc721-permit)

If possible, please help to disable the `Improved signature requests` by default for now and release a new version, thanks

**Comment by lanceaper** [comment]
Great to hear, thanks for update

**Comment by lanceaper** [comment]
I saws the release is ready now, how long will it take to reach Chrome store? @digiwand

**Comment by digiwand** [comment]
hey @lanceaper, that's correct and we've submitted the release to the Chrome store. I'm inquiring about specific rollout timing. Sorry for the inconvenience. Please continue to sign signatures with "Improved signatures request" disabled to unblock these permits. A hotfix will not be conducted to mitigate risk with its complexity.

We're also working on improvements for supporting EIP-721 Permits in upcoming releases

**Comment by digiwand** [comment]
currently, 1% has been rolled out to Chrome users

**Comment by bschorchit** [comment]
Hey @jiaqi-aperture even after we roll it out to 100% users, it might still take sometime for the update to reach everyone so feel free to tell your users to manually update to the latest version in the meantime.

**Comment by bschorchit** [comment]
Hey @jiaqi-aperture, we have rolled out the fix to 100% of users. Closing this issue. Please do report if you encounter this or any other issue in the future again, thank you!
