### ISSUE TITLE
Throw better errors when having trouble parsing Infura XML replies

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#2736]
Occasionally, when unpacking the response from pub.all in https://github.com/wjmelements/pub/blob/master/grafiti/client/lib/ethereum/pub.js I get:

> Error: new BigNumber() not a base 16 number: 
>     at I (inpage.js:14335)
>     at inpage.js:14335
>     at new e (inpage.js:14335)
>     at i.formatOutputString [as _outputFormatter] (inpage.js:14335)
>     at inpage.js:14335
>     at i.decode (inpage.js:14335)
>     at inpage.js:14335
>     at Array.map (<anonymous>)
>     at d.decodeParams (inpage.js:14335)
>     at c.unpackOutput (inpage.js:14335)

I believe this is an issue either with the RPC response error handling or with bytes unpacking.

Until this is fixed, I will workaround by re-issuing the request, since it still succeeds probabilistically. I encourage other developers to do the same. Metamask will be under additional load until this problem is resolved. I can provide additional information upon request.

**Comment by wjmelements** [comment]
Related:

> Error: Unexpected token < in JSON at position 0
    at Object.InvalidResponse (inpage.js:14335)
    at inpage.js:14335
    at inpage.js:9909
    at completeRequest (inpage.js:9960)
    at inpage.js:683
    at replenish (inpage.js:1203)
    at iterateeCallback (inpage.js:1193)
    at inpage.js:1168
    at inpage.js:9837
    at inpage.js:9933

**Comment by owocki** [comment]
i seem to be getting a huge increase in both of these exceptions today / yesterday

**Comment by owocki** [comment]
@wjmelements i just tweeted the team to see if there was a recent release https://twitter.com/owocki/status/940695583332773888

do you think you could add reproduction steps?  id add more of my own.. but the issue that i'm getting is deep in the gitcoin.co smart contracts and is not easy to extract out into isolated repro steps.

**Comment by danfinlay** [comment]
This is an error we get when Infura replies with an error. Maybe @eg or @maurycy can tell us if they're getting a lot of errors.

**Comment by owocki** [comment]
fwiw, im seeing green across the board at http://status.infura.io/

**Comment by wjmelements** [comment]
I don't think this is related to Infura. Grafiti falls back to Infura when not on Mist or Metamask, and in that case I do not see these errors. I believe this is from Metamask's RPC.
See the console errors for https://grafiti.online/ with/without Metamask.

**Comment by danfinlay** [comment]
Infura *is* MetaMask's RPC. Infura routes MetaMask's traffic to its own cluster of servers, so it does not necessarily correlate to other services.

**Comment by maurycyp** [comment]
Thanks, we're looking into it.

**Comment by owocki** [comment]
fwiw, issues seem to have disappated for me this morning. @wjmelements how about you

**Comment by owocki** [comment]
nevermind, i seem to be getting the issues today.. just less frequently http://bits.owocki.com/3c3n3t090u0R/Screen%20Shot%202017-12-13%20at%209.11.37%20AM.png

**Comment by danfinlay** [comment]
Infura can address this by scaling up, but we can address it by throwing better errors when we have trouble parsing error responses.

I think OP's strategy of retrying is going to continue being correct, even with both fixes.
