### ISSUE TITLE
Upgrade AssetsController to Version 38

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#27374]
### What is this about?

Presently the AssetsController is on version 36 and should be upgraded to 38.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by desi** [comment]
https://github.com/MetaMask/metamask-extension/pull/27755
