### ISSUE TITLE
Fix "Settings - general tab @no-mmi validate \"Magyar\" l..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27390]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102141/workflows/ebf4465e-b8ee-4bc1-8bd1-0b71a56c148b/jobs/3805055/tests

Build - Webpack
Browser - Chrome
Test Scenario - Settings - general tab @no-mmi validate "Magyar" language change on hypertext
Test Path - /test/e2e/tests/settings/change-language.spec.ts

```
Error: failed to fetch hu locale because of TypeError: Failed to fetch
  (Ran on CircleCI Node 5 of 20, Job test-e2e-chrome-webpack)
    at withFixtures (test/e2e/helpers.js:229:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (test/e2e/tests/settings/change-language.spec.ts:2:6290)
```

![image](https://github.com/user-attachments/assets/2ee922a4-9074-44d6-8c2a-0ae0d8251dc4)

Console log
```
-----Received an error from Chrome-----
failed to fetch hu locale because of TypeError: Failed to fetch
----------End of Chrome error----------

```

**Comment by chloeYue** [comment]
Fixed by PR https://github.com/MetaMask/metamask-extension/pull/28777
