### ISSUE TITLE
Fix "Add account should not affect public address when us..." flaky tests

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27419]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102230/workflows/464f7ef8-7df3-4ed9-80c9-776e71b1297f/jobs/3808841/tests

**Comment by chloeYue** [comment]
wait a bit to close this ticket, we need to verify that the test is not flaky anymore with the fix

**Comment by chloeYue** [comment]
> @chloeYue do you think we can close this ticket now? The PR which fixed this and other cases with the same root cause has now been merged. See below:
> 
> [7a5e4d6](https://github.com/MetaMask/metamask-extension/commit/7a5e4d6b88897eb914780fdd15157fc0d9b6f0c5)

 yes we can close it ! thanks for the fix!
