### ISSUE TITLE
Transaction broadcasting after being successful.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#2742]
Reproduction steps:
- Send transaction on Rinkeby (or any network)
- While the transaction is still pending, switch network to a different one
- Send another transaction.
- Wait for the initial Tx to be mined on Etherscan.
- Open the background
- Once the Tx is completed on Etherscan, switch back to the initial network and it should still be pending and the background will continue to broadcast the `sendRawTransaction` and `Error: nonce too low`

Example error: 
- `Uncaught (in promise) Error: [ethjs-rpc] rpc error with payload {"id":4102003752840,"jsonrpc":"2.0","params":["0xf86c118504e6d5aa1a827b0c9492e659448c48fc926ec942d0da1459260d36bb33884563918244f40000802ba04ccd47f43de7f020bb39118f4c6375076fc73c7b21d539a283347380395c668ba01d96a90977ebc61489a5922a371f61a16f8e0d468040dc0e26646e0a488dd568"],"method":"eth_sendRawTransaction"} Error: nonce too low`

**Comment by frankiebee** [comment]
this very much looks like a bug between the 2 event listeners the one marking confirmations and the one submmiting pending tx's 

```
    this.blockTracker.on('latest', this.pendingTxTracker.resubmitPendingTxs.bind(this.pendingTxTracker))
    this.blockTracker.on('sync', this.pendingTxTracker.queryPendingTxs.bind(this.pendingTxTracker))
```

**Comment by frankiebee** [comment]
https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/controllers/transactions.js#L90L91

**Comment by danfinlay** [comment]
Could also be related to retrying a transaction on the new network. A good case for having multiple providers, so transaction retries only submit against their originally intended network.

**Comment by danfinlay** [comment]
Kindof two issues. The one I listed above, and:

- Upon switching networks, pending txs should be checked (block tracker caught up) before resubmitting.

**Comment by bdresser** [comment]
@tmashuang I can't reproduce this anymore. Could you try, and if not let's close.
