### ISSUE TITLE
[Bug]: MetaMask crash if we type enter anything followed by a \ in settings search

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#27428]
### Describe the bug

MetaMask crash if user enters anything followed by a` \`, e.g. `foobar\`

### Screenshots/Recordings

![Screenshot 2024-09-26 at 17 26 38](https://github.com/user-attachments/assets/14b0f00e-2f5d-42e7-a6cd-e70f222ba90b)

### Steps to reproduce

1. Go to settings page
2. Enter anything followed by a` \`, example `foobar\`
3. See metaMask crash

### Detection stage

In production (default)

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by DDDDDanica** [comment]
Also duplicated with https://github.com/MetaMask/metamask-extension/issues/26945

**Comment by seaona** [comment]
I think it can be flagged as sev2, since you can just refresh the browser and MM works back again
