### ISSUE TITLE
[Bug]: Swaps shows 0 quotes available when there is an available balance and when quotes are returned

### ISSUE THREAD

**Issue by ejwessel** [MetaMask/metamask-extension#27433]
### Describe the bug

When requesting on `ZKSync:ZF <> ZKSync:WBTC` an error message shows that there are no available quotes. If we check the networks tab there are available quotes that are just not shown.

Swapping the src and dest tokens so that it goes `ZF <> WBTC`, `WBTC <> ZF`, `ZF <> WBTC` eventually shows the fetched quotes.

### Expected behavior

The quotes fetched should show in the UI

### Screenshots/Recordings

https://github.com/user-attachments/assets/fa04fe00-2eb8-4d64-862a-539744a21db5

### Steps to reproduce

1. open networks tab
2. go to swap
3. go select ZF token as src
4. select WBTC token as dest
5. input an amount for ZF token
6. confirm that there are no visible quotes
7. confirm that there are available quotes in the networks tab

### Detection stage

In production (default)

### Version

12.2.4

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by sleepytanya** [comment]
@ejwessel 

I'm on latest `develop`

Reproducible with other token on zkSync:


https://github.com/user-attachments/assets/97489cf7-33f2-4701-bfdd-f1f389138562



https://github.com/user-attachments/assets/f052d8e9-404b-4298-95ba-35116816615b



Sushi <>WBTC on Polygon, quotes are returned, but 'Error fetching quotes' is disaplyed. Also worng error message when trying to swap with insufficient balance - MM shows 'No quotes available' (should be 'Insufficient balance')


https://github.com/user-attachments/assets/03f3e07c-4ac7-4fc3-a28d-657d9fa406e1

**Comment by martahj** [comment]
I believe this issue is now resolved
https://github.com/user-attachments/assets/df16595d-489a-469c-88ff-d8db4c23a1b2
