### ISSUE TITLE
[Bug]: Phising detection - `https://client-side-detection.api.cx.metamask.io/v1/request-blocklist` returns always a 404

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27443]
### Describe the bug

The GET request to `https://client-side-detection.api.cx.metamask.io/v1/request-blocklist` returns always a 404.

Note: not sure where this server hosted and its repo, so I open the issue in MetaMask repo.

### Expected behavior

Either the[ link is incorrect](https://github.com/MetaMask/core/blob/b120adad4b7cc738eca321cf31f2e01bbd5fd9b9/packages/phishing-controller/src/PhishingController.ts#L28), or the server is not properly working

### Screenshots/Recordings

![Screenshot from 2024-09-27 09-11-30](https://github.com/user-attachments/assets/8bed5ead-82fc-447c-80d3-693ca8ae6445)

### Steps to reproduce

1. Open the network tab
2. Onboard MM
3. See request returns 404

### Detection stage

In production (default)

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by mindofmar** [comment]
This is now fixed thanks @seaona !

**Comment by seaona** [comment]
thank you @mindofmar we can close the issue
