### ISSUE TITLE
[Bug]: PPOM / Wallet API - `Error createPPOMMiddleware: TypeError: Cannot destructure property 'chainId' of 'networkController.getNetworkConfigurationByNetworkClientId(...)' as it is undefined.`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27447]
### Describe the bug

When I add an extra RPC to an existing network, I see this error `Error createPPOMMiddleware TypeError: Cannot destructure property 'chainId' of 'networkController.getNetworkConfigurationByNetworkClientId(...)' as it is undefined.`

### Screenshots/Recordings

https://github.com/user-attachments/assets/c184a6df-c80b-41b0-b49c-42a6d227c8bd

### Steps to reproduce

1. Click Networks
2. Click Sepolia details
3. Add new RPC `https://ethereum-sepolia.rpc.subquery.network/public`
4. Confirm

### Detection stage

On the development branch

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bschorchit** [comment]
Raising to a sev1 as ppom will break with this error

**Comment by bschorchit** [comment]
Also labeling as a release blocker for v12.5

**Comment by seaona** [comment]
thank you for reviewing the labels @bschorchit  :heart:

**Comment by MajorLift** [comment]
I removed the team-wallet-framework label since it looks like this issue is actively being worked on by the wallet api team: https://github.com/MetaMask/metamask-extension/pull/27570. 

Please feel free to revert if tagging the wallet framework team was intentional.

**Comment by adonesky1** [comment]
Resolved by https://github.com/MetaMask/metamask-extension/pull/27848
