### ISSUE TITLE
Account 2 - No longer showing - missing coins

### ISSUE THREAD

**Issue by kschill** [MetaMask/metamask-extension#2745]
Using Metamask, I purchased some COB tokens a few months back.  Today I open up metamask and it only shows 1 account, and of course it was not this account that I used to purchase COBs with.  How do I retrieve this account that holds the tokens and tx history?

**Comment by kschill** [comment]
hhmm.. i figured it out, but need clarification.  I re-imported the json file into metamask, then i guess it scanned the network to find the transactions.  Do I need to do anything to 'see' this account in MetaMask automatically or do I need to import it each time?

**Comment by tmashuang** [comment]
https://support.metamask.io/kb/article/6-loose-accounts

We can add the link under the Loose label.

**Comment by danfinlay** [comment]
You'll need to add it each time. Closing for now, because there's no way we can make a seed phrase recover other imported accounts, although the cross-browser sync features we have issues open for might help this.
