### ISSUE TITLE
Clean-up files-to-convert.json

### ISSUE THREAD

**Issue by kanthesha** [MetaMask/metamask-extension#27453]
### What is this about?

The controllers in the extension have been converted to typescript from javascript. During the process, they should have been removed from files-to-convert.json, but some of them are still there. We need to get this file up to date.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by mcmire** [comment]
@kanthesha The name of this file is a bit of a misnomer. The TypeScript migration dashboard uses this list of files to know which JavaScript files have been converted to TypeScript. It does this by iterating over each file and checking to see if there is a TypeScript file with the same name in the project. If it detects a conversion, it will assign a different color to the file on the dashboard.

If we remove files from this list, then the dashboard will no longer be able to tell which files have been converted. So we don't need to do that.

**Comment by desi** [comment]
Should we close this issue @mcmire
