### ISSUE TITLE
Confirmation window blank in firefox  57.0.1 (64 bits) linux

### ISSUE THREAD

**Issue by LukeVideo** [MetaMask/metamask-extension#2746]
When sending transaction to a contract in firefox a popup widget thingy open and i should be able to confirm my transaction there.

But when i send a transaction the popup is blank. With a strange address/url  moz-extention:// followed by a UUID or something similar.

If i switch to chrome it works fine.

**Comment by LukeVideo** [comment]
Wait i tried again and if ( only if ) i right click in the popup does it show the confirm transaction dialog.

**Comment by LukeVideo** [comment]
Wait i tried again and if ( only if ) i right click in the popup does it show the confirm transaction dialog.

**Comment by danfinlay** [comment]
it could help to inspect that blank popup and look for errors in the console.

https://support.metamask.io/kb/article/29-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by almindor** [comment]
Confirming the issue, Arch Linux x86_64 with firefox 57.0.2. Opening the tx popup with console on doesn't show any errors (not sure if it shows anything from that popup window tho).

**Comment by danfinlay** [comment]
If there are no errors in that popup, there might still be errors in the background. We can't really debug this without more information.

**Comment by LukeVideo** [comment]
I just added foundation and jquery to the app and i don't have the issue any-more. Could it have something to do with a call to jquery ?

If i remove materialize and jquey i get the issue again.

I don't get any errors in the popup console just these warnings from react 
`Download the React DevTools for a better development experience: https://fb.me/react-devtools
popup.js:59505:9
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
popup.js:76948:7`

**Comment by bensonkb** [comment]
![screenshot from 2018-03-07 15-10-19](https://user-images.githubusercontent.com/4044180/37085118-3e9a626c-221a-11e8-871c-ea96b61f16bf.png)
i too had the same issue on Firefox 58.0.2

**Comment by kekkyojin** [comment]
That's a multiplatform issue. Having the same problem on macOS Firefox 60. The problem is not happening in MetaMask on Opera, which is the older 3 version, not the current 4 one.

**Comment by estebanmino** [comment]
I'm able to reproduce the same issue with other add-ons that trigger a notification popup on Firefox. #4796

**Comment by sulliwane** [comment]
Same problem here, blank metamask popup in firefox (unless I resize the window).

OS : Ubuntu 18.04, Firefox 62, Metamask 4.9.2

**Comment by danfinlay** [comment]
Could anyone experiencing this issue post their version of MetaMask? Should be available in your browser's extensions panel. On chrome this is `chrome://extensions`.

Also, @sulliwane: Your error message says there was an error in calls for token at address, could you copy/paste that token address here, so I don't have to transcribe it from image?

**Comment by sulliwane** [comment]
@danfinlay here is the address the message: ```symbol() and decimal() calls for token at address 0x12b92a17b1ca4bb10b861386446b8b2716e58c9b```. The address is an ERC20 contract on Kovan for RLC token (symbol = RLC, decimal = 9).

**Comment by bdresser** [comment]
hey folks, is this still affecting you on MM 6.2.1?

**Comment by quezak** [comment]
I'm on MM 6.1.0 and it seems like it doesn't happen anymore (before it happened for me every time). It may be connected to firefox version too? I'm on 65.0 for a few weeks now.
