### ISSUE TITLE
[Bug]: Unable to send transaction with the high nonce (+1) on Arbitrum, transaction fails with 'Internal JSON RPC error'. Subsequent transaction on a different network adopts the nonce from the previously failed transaction

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#27479]
### Describe the bug

 Unable to send transaction with the high nonce (+1) on Arbitrum, transaction fails with `Internal JSON RPC error`. Subsequent transaction on a different network adopts the nonce from the previously failed transaction

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/4f994638-fd22-466b-abd9-3725eaab11e5

### Steps to reproduce

1. Connect to Arbitrum
2. Submit transaction with the high nonce 
3. Observe it fails with `Internal JSON RPC error`
4. Switch to BNB Chain
5. Start a transaction
6. Transaction is created with the same nonce as failed transaction on Arbitrum

### Error messages or log output

```shell
Internal JSON-RPC error.
CSS
函
=
ロ_
XHR
Requests
X
sentry-install.js:1:739
Tokens
Sep 30, 2024
Send USDA
Failed
Send USDT
Confirmed
Send DAI
Confirmed
Send DAI
Confirmed
Send DAI
Confirmed
Send USDT
Status
Failed
From
0x05217...96...
Transaction
Nonce
Amount
Gas Limit (Units)
Total gas fee
Max fee per gas
Total
+ Activity log
View on block explorer
Copy transaction ID
To
Account 1
35
-0.00001 USDT
109479
O ETH
$0.00 USD
<0.000001 ETH
$0.00 USD
O ETH
$0.00 USD
Activity

...f50270ba/scripts/sentry-install.js:1

...f50270ba/scripts/sentry-install.js:3
levelMethod
..Oba/scripts/ runtime-lavamoat.js:7134
logErrorWithMessage
4efc-bela-3393f50270ba/common-8-js:1
updateAndApproveTx
..c-bela-3393f50270ba/common-10.js: 361
handleResponse
..6b-4efc-bela-3393f50270ba/ui-11.js:8
emit
4efc-bela-3393f50270ba/common-5. js:1

4efc-bela-3393f50270ba/common-7-js:1
S
4efc-bela-3393f50270ba/common-7-js:1
push
•4efc-bela-3393f50270ba/common-7- js: 1
write
4efc-bela-3393f50270ba/common-1.js:1
S
...4efc-bela-3393f50270ba/common-7.js:1

4efc-bela-3393f50270ba/common-7. js: 1
write
4efc-bela-3393f50270ba/common-7-js:1

•4efc-bela-3393f50270ba/common-5. js: 1
emit
..4efc-bela-3393f50270ba/common-5. js:1

..4efc-bela-3393f50270ba/common-5. js:1

..4efc-bela-3393f50270ba/common-5. js:1
push
..4efc-bela-3393f50270ba/common-5. js:1

4efc-bela-3393f50270ba/common-5. js:1
onMessage
•4efc-bela-3393f50270ba/common-5. js: 1
```

### Detection stage

During release testing

### Version

12.4.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by jpuri** [comment]
Hey @sleepytanya : I am unable to replicate, for me a transaction with incremented nonce is stuck in pending state:

![Image](https://github.com/user-attachments/assets/2c7de641-51c4-4c9f-a43a-411042caa182)

**Comment by sleepytanya** [comment]
@jpuri 
Thank you, Jyoti!

Have you tried latest build from [this comment](https://github.com/MetaMask/metamask-extension/pull/27287#issuecomment-2386455730 )? 
 
Very consistent on my side:


https://github.com/user-attachments/assets/a10f2602-cef2-4e1f-ac0a-177bf76e950a

**Comment by sleepytanya** [comment]
We have opted to divide this ticket since the bug encompasses two distinct aspects: the issue of incorrect nonce generation and the specific challenge related to Arbitrum, which involves the inability to send transactions with a nonce incremented by one.

Incorrect nonce generation was fixed in this PR - https://github.com/MetaMask/metamask-extension/pull/27297

Ticket for the Arbitrum specific nonce+1 issue - https://github.com/MetaMask/metamask-extension/issues/27638
