### ISSUE TITLE
Rewrite Token view to individually render instead of rendering the list all at once.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#2748]
Issue is raised since when there is an error with one token, it will prevent the rest of the token list from loading.

**Comment by danfinlay** [comment]
Could be made easily by using https://github.com/MetaMask/eth-token-tracker/blob/master/lib/token.js directly (instead of through the index.js)

**Comment by whymarrh** [comment]
@tmashuang is this still the case? Do "error" with one token still crash that component?

**Comment by tmashuang** [comment]
Closing old issue since I don't see any issues with the token list anymore.
