### ISSUE TITLE
Lost Private Key

### ISSUE THREAD

**Issue by laremmohan** [MetaMask/metamask-extension#2750]
Hi,

I lost my private key. I do still have my seed words and adress.

What are my options?

**Comment by frankiebee** [comment]
@laremmohan Is this an account that you imported into metamask?
If not you should be able to use your seed words in metamask to recover your accounts.
Is this a new install of MetaMask?

**Comment by laremmohan** [comment]
@frankiebee I resolved it already. Thanks for the fast response! I was using the wrong seed words....
