### ISSUE TITLE
[Bug]: Contract Deployment - When I deploy a contract I see the `At Inversebrah` value as `method` in the new redesigned screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27524]
### Describe the bug

When I deploy a contract I see the `At Inversebrah` value as `method` in the new redesigned screen.
Notice: this doesn't happen with the test-dapp ERC20 contract for some reason, but you can try it with any other contract

### Screenshots/Recordings

https://github.com/user-attachments/assets/4b117ddd-710b-4b5e-919f-9ab1703db0bb

### Steps to reproduce

1. Make sure you have transaction redesigned enabled from Experimental settings
2. Trigger a contract deployment ie ERC721
3. Click on Settings in the Confirmation screen
4. See `At Inversebrah` as method

### Detection stage

During release testing

### Version

12.4.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by matthewwalsh0** [comment]
Does this occur on `develop`? This could be the same issue as #27120.

**Comment by seaona** [comment]
yes, this also happens on current develop @matthewwalsh0
