### ISSUE TITLE
Fix Input of type number messing up with units in custom UI

### ISSUE THREAD

**Issue by GuillaumeRx** [MetaMask/metamask-extension#27536]
There's a problem with the native input of type `number` messing up with units when you use it to work with numbers with decimals.

**Comment by hmalik88** [comment]
what's the observed behavior?

**Comment by GuillaumeRx** [comment]
> what's the observed behavior?


https://github.com/user-attachments/assets/80942ce5-6d01-45d2-98e9-a8fc97cd5709
