### ISSUE TITLE
[Bug]: Not working (Empty body) on Arc Browser

### ISSUE THREAD

**Issue by aminlatifi** [MetaMask/metamask-extension#27540]
### Describe the bug

I use the latest version of Metmask and Arc browser. My metamask extension window doesn't show anything when I open it
<img width="364" alt="image" src="https://github.com/user-attachments/assets/1ad9056c-4bb5-44d9-97b9-e653ccd42bab">

It's the inspection of body

<img width="248" alt="image" src="https://github.com/user-attachments/assets/4f590c97-fb7a-4a79-98b3-782828a75926">

### Steps to reproduce

Open the metamask extension

### Detection stage

In production (default)

### Version

12.2.4

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

MacOS

### Additional context

It's Arc browser

### Severity

High

**Comment by danjm** [comment]
Thanks for reporting. This is being discussed over here https://github.com/MetaMask/metamask-extension/issues/12809#issuecomment-2374080282

There is fix needed within the Arc browser itself. It should be released today or tomorrow. In the meantime, you can read the comment I just linked for a workaround
