### ISSUE TITLE
[Bug]: Infinite loading on 12.3.1

### ISSUE THREAD

**Issue by maxikgreat** [MetaMask/metamask-extension#27555]
### Describe the bug

After quite time I tried to open extension but after that only what it gave me was infinite loader. I tried to install/reinstall extension couple times or reset but it does not help

### Expected behavior

Password input screen

### Screenshots/Recordings

https://github.com/user-attachments/assets/8b819676-8660-4576-901d-9607ac835d07

### Steps to reproduce

1. Open extension
2. Done

### Error messages or log output

```shell
Sorry, I don't know how to check extension logs. Please guide me if possible and I will share them
```

### Detection stage

In production (default)

### Version

12.3.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by wslyvh** [comment]
Same issue with v12.0.6 on Firefox / Linux 
Can't open or do anything with Metamask. Keeps loading

**Comment by maxikgreat** [comment]
Today suddenly everything works! Idk how

**Comment by takadr** [comment]
I was facing the same issue and managed to recover.

1. Go to the extension setting
chrome://extensions/?id=nkbihfbeogaeaoehlefnkodbefgpgknn

2. Turn on the toggle for "Allow in Incognito"
3. Open Metamask on the incognito window
