### ISSUE TITLE
[Bug]: Incorrect Deadline Conversion for ERC20 Permit Signing in Metamask Extension

### ISSUE THREAD

**Issue by ngduythao** [MetaMask/metamask-extension#27553]
## Problem Description

The Metamask extension is incorrectly converting and displaying the deadline timestamp when signing ERC20 permit transactions.

## Details

- The input deadline timestamp is in seconds (which is the standard Ethereum timestamp format for ERC20 permit).
- Metamask appears to be interpreting this deadline timestamp as milliseconds instead of seconds.
- As a result, the displayed deadline date in the signing interface is incorrectly shown as sometime in 1970.

## Confirmation

- I have verified that the input deadline timestamp I'm passing is correct.
- I have an image that demonstrates this issue, which I can attach to this report.

### Expected behavior

The Metamask UI should correctly interpret the deadline timestamp in seconds and display the appropriate date when requesting signature for ERC20 permit.

## Additional Information
<img width="355" alt="image_2024_10_2" src="https://github.com/user-attachments/assets/0559590d-1af6-4467-9bed-0f56555f9d16">

### Steps to reproduce

1. Navigate to a dApp that implements ERC20 permit functionality.
2. Initiate an action that requires signing an ERC20 permit (e.g., approving tokens for a DEX).
3. In the permit signing interface, set a future deadline (e.g., current time + 1 hour).
4. Observe the deadline displayed in the Metamask signing window.

Expected result: The deadline should be displayed as the correct future date and time.
Actual result: The deadline is displayed as a date in 1970.

### Detection stage

In production (default)

### Version

12.2.4

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by vinistevam** [comment]
Thank you @gduythao for reporting this bug. The issue has been addressed in [PR #27249](https://github.com/MetaMask/metamask-extension/pull/27249) and is resolved in version 12.3.0 of the extension. Please feel free to reach out if you encounter this issue again in version 12.3.0 or if you have any further questions.

**Comment by bschorchit** [comment]
Closing as it was fixed in the latest release v12.3 as mentioned above. The v12.3 release is already available and you can manually update to it @ngduythao. We'll be pushing that release to all users soon. Thank you for your report!
