### ISSUE TITLE
[Bug]: Main screen top section with currency display component and button icons misaligned

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#27593]
### Describe the bug

The main screen's top section, which includes the currency display component and button icons, appears to be misaligned from the center

### Expected behavior

-

### Screenshots/Recordings

<img width="859" alt="Screenshot 2024-10-02 at 22 33 51" src="https://github.com/user-attachments/assets/6a04e8bc-2d9b-4ed2-9241-33e5748b4a0a">

### Steps to reproduce

1. Install extension

### Detection stage

On the development branch

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
The change was intentional https://github.com/MetaMask/metamask-extension/pull/27097

**Comment by Gudahtt** [comment]
Reopening because while the change was intentional overall, it was mainly designed with the popup UI in mind. The affect it had on the fullscreen UI was not intended.
