### ISSUE TITLE
Connecting Metamask to test network on cloud9

### ISSUE THREAD

**Issue by damoonazarpazhooh** [MetaMask/metamask-extension#2760]
I am trying to connect metamask to a test network that runs on cloud9 but sadly nothing seems to work . Any suggestions? in cloud9 , I have installed Meteor and in the “private” folder , have initialized truffle . I have started truffle develop in the private directory. Truffle, when using testRpc in the private director behaves the way you would expect it to and also meteor starts properly but it seems like metamask cannot connect to the test network launched by truffle and I cannot link my meteor app to that network . I have followed the guidelines and put

```
if (typeof web3 !== 'undefined') {
  web3 = new Web3(web3.currentProvider);
} else {
  // set the provider you want from Web3.providers
  web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
}
```
in ./client/lib/lib.js and also in Metamask, set RemoteRPC as

`http://my-app-name.c9users.io:8545/
`can you please tell me what might be wrong with my setup? thanks a lot.

**Comment by danfinlay** [comment]
Is it possible you don't have a cloud9 port open?

**Comment by danfinlay** [comment]
Could be that you need to configure some CORS settings on cloud9? Really sounds like a cloud9 configuration issue, since people connect MetaMask to custom providers all the time.

**Comment by damoonazarpazhooh** [comment]
@danfinlay Thanks man , I figured it out. I was just being dumb ... It's quite simple really, on cloud9, only these three ports are available : 8080,8081,8082 . If you are running meteor, the first two are used by Meteor and MongoDB and the only available port is 8082 so all one has to do is to set the testnet to run on port 8082 and on metamask , connect to the remoteRPC address through port 8082, eg:
`http://my-app-name.c9users.io:8082/`
One just has to make sure that the project on cloud9 is public so that Metamask can connect to it from remote origin.

**Comment by danfinlay** [comment]
Glad to hear it, thanks for the update.
