### ISSUE TITLE
[Bug]: After Metamask 12.3.0 update, recently updated tokens in Contract-metadata are not detected in Metamask

### ISSUE THREAD

**Issue by mandoopapa** [MetaMask/metamask-extension#27614]
### Describe the bug

Hi team.
Recently there was an update to Metamask 12.3.0, and after the update we noticed that our project team's token, which was merged from the Contract-metadata repository on July 16, is not being detected in Metamask.

I have attached some relevant information below.
Please check them out.

Thank you.

https://github.com/MetaMask/contract-metadata/pull/1329

Token Information
Tokamak Network Token
Network : Ethereum
Token Address : 0x2be5e8c109e2197D077D13A82dAead6a9b3433C5
Symbol : TON
Etherscan(verified) : https://etherscan.io/token/0x2be5e8c109e2197D077D13A82dAead6a9b3433C5

### Steps to reproduce

After selecting Ethereum Mainnet as the network, Go to 'import token'
tokamak or ton, the above mentioned tokens are not found.
Before the 12.3.0 update, they were found.

### Detection stage

In production (default)

### Version

12.3.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by sahar-fehri** [comment]
Hi @mandoopapa 👋 ; 
We are working on fixing this for token `0x2be5e8c109e2197D077D13A82dAead6a9b3433C5`.
For the wrapped token: `0xc4a11aaf6ea915ed7ac194161d2fc9384f15bff2`;
Could you add the token Coingecko? You should be able to see it afterwards 🙏

**Comment by mandoopapa** [comment]
An issue that occurred after 12.3.0 has not been fixed in the current update to 12.5.0. Is there any chance it will be delayed further?

**Comment by alfeng6** [comment]
from reading comments above, this has been fixed.

**Comment by alfeng6** [comment]
https://github.com/MetaMask/contract-metadata/issues/1371

this fixed it ^^
