### ISSUE TITLE
Failing to load events on a new provider

### ISSUE THREAD

**Issue by alex-miller-0** [MetaMask/metamask-extension#2761]
I am building an application that requires me to interact with a provider, switch providers, and pull events from the new provider (e.g. localhost:7545 -> localhost:8545). After switching providers, I get zero events about 90% of the time (I can see logs of the events in a separate web3 console). The only way to get the events in Metamask seems to be restarting Chrome entirely. What's strange is that once in a while, things work as expected, but that's probably 1 in 10 tries.

**Expected Behavior**

Upon switching providers, I expect the new provider to collect events from a contract that has emitted them.

**Actual Behavior**

No events are found from e.g. `allEvents.get()` after switching providers until I reboot Chrome.

**Browser Used**

Chrome 63.0

**Operating System Used**

macOS Sierra

**Comment by danfinlay** [comment]
Have you tried reloading the page after switching the provider (if it isn't automatically)?

**Comment by alex-miller-0** [comment]
Yes, hard reloading didn't solve it. Neither did switching users and coming back to the original user.

**Comment by alex-miller-0** [comment]
Interesting to note: I am not finding this buggy behavior on Brave.

**Comment by danfinlay** [comment]
Hey @alex-miller-0, is this still an issue for you? We did some things that may have fixed this.

**Comment by danfinlay** [comment]
We could really use reproduction steps here, or we should maybe close it in favor of #2978.

**Comment by alex-miller-0** [comment]
Sorry for the delay. Here are the reproduction steps (only in Chrome):

1. Load page with logs - get logs
2. Switch providers in Metamask
3. Page reloads automatically - no logs

I haven't worked on that project in a while and can't seem to get my workflow working, so I can't verify if it's still there or not.

I think it's okay if you close this for now and I'll let you know if I see it again. Good work squashing all those log bugs!

**Comment by danfinlay** [comment]
Certainly not all yet, some still out there for sure. Thanks for the follow up!
