### ISSUE TITLE
[Bug]: Changing Swap source token frequently causes extension to crash 

### ISSUE THREAD

**Issue by martahj** [MetaMask/metamask-extension#27625]
### Describe the bug

Changing the swap source token frequently causes the extension to crash.

### Expected behavior

I expected the extension not to crash and to continue to get quotes

### Screenshots/Recordings

Video of issue
https://github.com/user-attachments/assets/8445e684-a47f-46c0-b12a-1a363c92f561

Error in console
<img width="700" alt="Screenshot 2024-10-04 at 8 35 03 AM" src="https://github.com/user-attachments/assets/b2d7c3dd-1fae-4604-835e-7222c9d21f7f">

### Steps to reproduce

1. Go to Swaps page
2. Select a source token + amount and a destination token
3. Keep changing the source token until the extension crashes

### Detection stage

In production (default)

### Version

12.2.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Unik0rnMaggie** [comment]
Present in v12.5.0 RC 

https://github.com/user-attachments/assets/df435a03-2227-455c-b050-6b9287f1e96e

**Comment by martahj** [comment]
I think this was fixed in https://github.com/MetaMask/metamask-extension/pull/27708 - @jclancy93 could you cherry-pick that fix into the v12.5.0 RC?

**Comment by jclancy93** [comment]
This is now solved and was cherry picked into v12.5.0
