### ISSUE TITLE
Different Accounts, merged interactions.

### ISSUE THREAD

**Issue by bpate** [MetaMask/metamask-extension#2762]
Report:
Expected Behavior: - Two people visiting the same website would be able to use the form on the website independently of each other, and also be able to submit the form without affecting the other people viewing the website at the same time.

Actual Behavior: - Form values are shared with anyone using the site that also has the metamask extension installed. Form submission is also shared, when one user clicks the submit button all users connected to the site that have MetaMask see a popup requesting a transaction.

Browser Used: - Chrome - Version 63.0.3239.108 (Official Build) (64-bit) 
Operating System Used: OSX 10.12.5 and Windows 8.1 (both chrome)

More: 
I am not convinced this is a MetaMask issue I do not have a lot of experience in client side languages, but I don't know where else to ask. I have an HTML and JavaScript (Jquery) site hosted on the a Google Compute VM, it is located at http://35.227.121.105:3000/ if anyone wants to see this in action. It is connected with Web3.js to a smart contract on the Ropsten test network. If you open the page with two different instances (I used two computers in my house) and then begin to fill out the form fields, the other (and all other connected) instances of the site will update too. If you click the button to send the transaction to the smart contract that updates the data, each instance of the site gets a MetaMask popup requesting them to submit the transaction, even though only 1 person actually clicked the button.

Am I just overlooking something extremely basic? Thanks for any help.

**Comment by williamchong007** [comment]
this is totally unrelated to metamask and is related to the `browsersync` js script you are using

**Comment by bpate** [comment]
You are absolutely correct! Thank you so much it was something I was overlooking that was extremely basic. I have never used this lite-server before. Thanks so much for your help, sorry for wasting your time lol. Closing.

**Comment by Febin56** [comment]
@bpate Could you please explain how you resolved the issue, We are on the same boat
