### ISSUE TITLE
[Bug]: When a transaction fails the subsequent transaction created on another network adopts a nonce from the previosly failed transaction

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#27657]
### Describe the bug

When a transaction fails the subsequent transaction created on another network adopts a nonce from the previosly failed transaction

### Expected behavior

Transactions created with the correct nonce value

### Screenshots/Recordings

https://github.com/user-attachments/assets/fc5f8d9f-0a67-41f9-86ad-acbe74200c67

### Steps to reproduce

1. Connect to Arbitrum
2. Submit transaction with the high nonce
3. Observe it fails with Internal JSON RPC error
4. Switch to BNB Chain
5. Start a transaction
6. Transaction is created with the same nonce as failed transaction on Arbitrum

### Detection stage

During release testing

### Version

12.4.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by bschorchit** [comment]
Closing as fixed by: https://github.com/MetaMask/metamask-extension/pull/27634
