### ISSUE TITLE
Wallet lost after chrome crash

### ISSUE THREAD

**Issue by betheglass** [MetaMask/metamask-extension#2766]
Chrome browser crashed.  After restarting my computer my metmask wallet is not recognized and I am prompted to create a new wallet.  I have misplaced my seed phrase for this particular account.  I have tried multiple time machine restores with no success.  Restores from images saved within the past few days start with a Chrome pop up notifying me that Chrome has crashed.  Is there a way to point the Chrome extension to the old data on one of my older backups to get the extension to recognize my old wallet?  Obviously I know the password but without my old wallet loading it is useless. 

OSX 10.10.5
Chrome 63.0.3239.108

**Comment by danfinlay** [comment]
On a mac, chrome should store your extension data at `~/Library/Application\ Support/Google/Chrome/Default/Extensions`.

If you can get the main metamask vault JSON file, you can decrypt it with your password using [this utility](https://metamask.github.io/vault-decryptor/).

For more individual assistance, please open a ticket at https://support.metamask.io

**Comment by mattraw86** [comment]
Hi

I have a similar issue. I set up MetaMask on my Windows Computer to which I have received some Tokens into. 
Unfortunatley I did not save the seed words and my Computer reset. I still know the wallet address and the Password.

I now have a new copy of MetaMask running but I cannot add my old wallet with the Tokens,.

I have completed a files recovery run on my System, but I am unsure where to find the JSON file on a Windows PC. Please could you help me locate it? Or any other way that it could be saved?
I am running Windows 10. 

Best regards

**Comment by danfinlay** [comment]
You will need to track down that storage yourself. Here is one quick search result:
https://superuser.com/questions/507536/where-does-google-chrome-save-localstorage-from-extensions

**Comment by martineezz** [comment]
@betheglass 
@mattraw86 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
