### ISSUE TITLE
[Bug]: CCIP Read ENS resolution fails

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#27784]
### Describe the bug

Originally reported in https://github.com/MetaMask/eth-json-rpc-middleware/issues/335:

>ENS resolution sometimes uses CCIP read ([eip-3668](https://eips.ethereum.org/EIPS/eip-3668)) to resolve an address.
That relies on a reverted execution being interpreted as a redirect.
When the provider used to perform such a read is managed by this middleware, the read operation fails.
My guess is that the reverted execution is somehow wrapped such that the error is no longer interpretable.

### Expected behavior

ENS resolution should succeed, including addresses that use CCIP read.

### Steps to reproduce

1. Checkout the `test-app` repository locally to the `ens-resolution` branch (see https://github.com/MetaMask/test-dapp/pull/362)
2. Start the test dapp using `yarn start`
3. Install the MetaMask extension (any type of build)
4. Ensure that the current selected chain is Ethereum Mainnet
5. Navigate to the locally-hosted test dapp and connect at least one account
6. Scroll to the bottom, enter `jwt.ro` into the "ENS Resolution" field, then click Submit

This should resolve to an address, but it currently resolves to `null` instead.

### Detection stage

In production (default)

### Version

12.1.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by FrederikBolding** [comment]
@Gudahtt We'll need https://github.com/MetaMask/metamask-extension/pull/22875

Blocked by:
https://github.com/MetaMask/core/pull/4773
https://github.com/MetaMask/metamask-extension/pull/24496
https://github.com/MetaMask/metamask-extension/pull/27700

**Comment by snackman** [comment]
plz fiz this, PizzaDAO needs you. We'll buy pizza for whoever does it!

**Comment by legobeat** [comment]
- https://github.com/MetaMask/metamask-extension/pull/22875

Also related:
- https://github.com/MetaMask/core/pull/4769
  - https://github.com/MetaMask/eth-json-rpc-infura/pull/114
  - https://github.com/MetaMask/providers/pull/380

**Comment by mirceanis** [comment]
looks like #22875 fixed it

**Comment by mirceanis** [comment]
This issue has been fixed. Are we waiting for a release to close it?

**Comment by desi** [comment]
@mirceanis Nope we are all good. Just missed closing the issue! It was included in 12.6.0
