### ISSUE TITLE
[Bug]: Swaps requiring a token Approval transaction fail on Linea ('transaction reverted')

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#27786]
### Describe the bug

Swaps requiring a token `Approval` transaction encounter issues on Linea, resulting in a 'transaction reverted' message. 
If a swap is initiated for a token that hasn't been previously approved, the initial Approval transaction will succeed, but the swap itself fails with the 'transaction reverted' message. However, a follow-up attempt to swap the now-approved token typically proceeds successfully. Present in 12.3.1, 12.4.0, 12.5.0.

The latest `develop` build exhibits a different behavior: users are presented with a 'Swap failed' screen, accompanied by a 'Try again' button. A second attempt leads to a successful swap.

### Expected behavior

-

### Screenshots/Recordings

v12.3.1:

https://github.com/user-attachments/assets/0bddf80c-35d9-494b-8130-74e784ce6092

v12.4.0:

https://github.com/user-attachments/assets/f527f8f7-61ac-4344-aea1-b8e9695fb51b

v12.5.0:

https://github.com/user-attachments/assets/51728bde-71c8-4ac3-9817-cd203da91416

<img width="561" alt="Screenshot 2024-10-11 at 00 47 26" src="https://github.com/user-attachments/assets/40f25ab7-c355-468d-b69a-f70e838d3012">

`Develop`:

https://github.com/user-attachments/assets/73cc0ece-2aae-4076-b069-025e92b03f9d

<img width="648" alt="Screenshot 2024-10-11 at 00 50 05" src="https://github.com/user-attachments/assets/73a4216b-d5ac-4432-be52-162df0536ea2">

### Steps to reproduce

1. Connect to Linea Mainnet
2. Swap a token that requires Approval

### Detection stage

In production (default)

### Version

12.3.1, 12.4.0, 12.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jclancy93** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/27804
