### ISSUE TITLE
Metamask inside a normal HTML page instead of extension for Chrome, FF, Opera, etc...

### ISSUE THREAD

**Issue by gdeverlant** [MetaMask/metamask-extension#2780]
This is a simple question if it is possible to use Metamask inside an IFRAME instead of extension in Browser?

**Comment by frankiebee** [comment]
MetaMask can not be iframed to protect against click jacking but here is a web version of metamask: https://wallet.metamask.io/ 

and the library to work with it: https://github.com/MetaMask/mascara
