### ISSUE TITLE
[Bug]: Swap of unapproved token fails on Linea

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-extension#27804]
### Describe the bug

When swapping any unapproved token on Linea, only the approval transaction succeeds. However the actual swap transaction - that happens after that - fails. I tried to submit the same swap a second time, and since the approval is already there the transaction goes through. So the user can somehow still recover, but we might lose the transaction if the user doesn’t retry.

I checked and this is also in production
I checked on Mainnet and doesn't happen

### Screenshots/Recordings

https://github.com/user-attachments/assets/343ab5ee-1bcb-45cb-9d42-c753b80c1fea

### Steps to reproduce

1. Change Network to Linea
2. Swap ETH to unapproved token
3. Swap unapproved token to any token
4. Notice that the transaction fails

### Detection stage

During release testing

### Version

12.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
@davibroc 

The issue is present in 12.4.0 and 12.3.1 and most likely in earlier versions too 

https://github.com/MetaMask/metamask-extension/issues/27786
