### ISSUE TITLE
[Bug]: balance is undefined when pricing is not available

### ISSUE THREAD

**Issue by ejwessel** [MetaMask/metamask-extension#27805]
### Describe the bug

USD balance is shown as default and initially in place of the token balance.
If this token has no pricing data or if the pricing data is unavailable the balance is `undefined` and the USD is 0.

Not only is this confusing for the user, the amount that can be transacted is unclear.

### Expected behavior

Token balance should take priority over USD value balance.

### Screenshots/Recordings

<img width="423" alt="Screenshot 2024-10-11 at 11 33 49" src="https://github.com/user-attachments/assets/007bed4c-5d67-4fd0-ae01-b06725591567">
<img width="418" alt="Screenshot 2024-10-11 at 11 26 17" src="https://github.com/user-attachments/assets/64d13dbe-3047-48ea-a258-edbff1987008">
<img width="414" alt="Screenshot 2024-10-11 at 11 34 09" src="https://github.com/user-attachments/assets/df2fb8b7-22fb-4767-9fdc-882fce7b6a83">

### Steps to reproduce

1. click on send
2. select account to send to
3. select token to send, preferably one with poor pricing data (`ETH: 0xaec2e87e0a235266d9c5adc9deb4b2e29b54d009`)
4. confirm that `balance` is `undefined`
5. select a token that has pricing data
6. use arrows on the right of the amount field to swap USD amount to token amount
7. reselect token to send in prior step
8. confirm that token balance now shows.

### Detection stage

During release testing

### Version

v12.5.0

### Build type

None

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by bergeron** [comment]
My repro is to start sending an asset, switch it to fiat input.  Then pick a different asset that does not support fiat pricing.  It remains on fiat input when it should switch to balance input.

https://github.com/user-attachments/assets/204a5e7f-e26d-48c4-9f4f-a72b0df990c4
