### ISSUE TITLE
Overflow bug sent 12.11111111111111 ETH instead of 1.111111111111111 ETH

### ISSUE THREAD

**Issue by GriffGreen** [MetaMask/metamask-extension#2782]
I had a few bugs in one, luckily this ain't my first rodeo so no harm done :-D

  *  Expected Behavior
I was trying to donate 1.111111111111111111111111111 ETH to TrueBit's Merkle Christmas tree magic, then it said i didnt have enough funds to send it, i thought it was a false error but it didnt like how many 1's i had so i deleted some without counting and then it went thru, right before that I had made a tx on MEW (using etherscan's node) of course the way the network is going they both went out with the same nonce... but this tx made it to etherscan... thats when i noticed the problem

  *  Actual Behavior
There was an overflow bug, a really weird one... it submitted the tx as 12.11111111111111111 ETH (i'm not counting the 1's on any of these)... luckily i was able to replace it quickly by upping the gas price on my MEW tx, which made it thru even though on MetaMask it says the 12.1 ETH tx made it thru, but when i view the tx on etherscan it confirms the tx never happened.

  *  Browser Used
Chrome Version 63.0.3239.84 (Official Build) (64-bit)

  *  Operating System Used
macOS Sierra 10.12.6 (16G29)

  Screenshots are very helpful and will expedite your issue being resolved!
-->
(Note this screen shot was taken a long time after the tx was sent and replaced, i just conveniently left the tab open)
<img width="1221" alt="screen shot 2017-12-20 at 12 13 32 pm" src="https://user-images.githubusercontent.com/14945613/34226669-46017c70-e57f-11e7-969c-87d840577fce.png">

<img width="363" alt="screen shot 2017-12-20 at 7 39 11 am" src="https://user-images.githubusercontent.com/14945613/34216689-e7a0db60-e55d-11e7-9b5d-2bac171ff331.png">

<img width="941" alt="screen shot 2017-12-20 at 7 39 32 am" src="https://user-images.githubusercontent.com/14945613/34216735-09de90d2-e55e-11e7-84e2-88c01c2f1c01.png">

Much Love, Merry Wednesday,
Griff

**Comment by danfinlay** [comment]
Hey Griff, scary bug! How did you initiate the send? Was it our send form, mew, or the console?

**Comment by GriffGreen** [comment]
Chrome extension, regular input. I was connected to our node tho, https://mew.giveth.io

The plot thickens as our node was acting weird and actually went down yesterday....

**Comment by beether** [comment]
Omfg this is terrible.

**Comment by Zanibas** [comment]
1.11111111111111111111 => 12.111 eth confirmed. You need to remove 7 zeroes @GriffGreen haha.

**Comment by Zanibas** [comment]
Confirmed that this is a problem with `ui/app/util.js` with the `normalizeEthStringToWei` function
