### ISSUE TITLE
Option to view/display own address

### ISSUE THREAD

**Issue by balzss** [MetaMask/metamask-extension#2786]
Is there a specific reason that I can't view my own address easily in the extension only the "shortened form"? When I'm purchasing Ether or sending from a different account I use the copy button but I want to double check after pasting that I didn't paste a different address accidentally (can easily happen I you use a clipboard manager or misclick the copy button). Right now I have to click on the "view account on etherscan" but would be much easier to just display it under my account name or if there's not enough space there then under the QR code.  

If there's no specific reason to hide it and it's only a matter of implementation I'm more then happy to submit a PR.

**Comment by tmashuang** [comment]
This will be addressed in the future implementation of MetaMask. Closing for now.
