### ISSUE TITLE
[Bug]: Certain PPOM signatures are not functioning as expected.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#27905]
### Describe the bug

`Malicious ERC 20 Approval (BUSD)`, `Malicious Set Approval for All,` and `Malicious ERC20 Approval with Odd Hex Data` are not being identified by PPOM. 
Not sure if that's expected but the token name on BNB is displayed as `anyUSDC` and in RC 12.5.0 `Malicious ERC 20 Approval (BUSD)` is not flagged (account has enough USDC).

### Expected behavior

-

### Screenshots/Recordings

<img width="687" alt="mainnet1" src="https://github.com/user-attachments/assets/fb9b2203-5317-4b7d-8e35-fe83fb68952a">

<img width="691" alt="mainnet2" src="https://github.com/user-attachments/assets/3014b4ca-b878-4c0d-9c36-2cd2d332adc8">

<img width="657" alt="mainnet3" src="https://github.com/user-attachments/assets/81a7b88b-4186-41c6-bdac-ee017a47c6ca">

<img width="755" alt="bnb1" src="https://github.com/user-attachments/assets/9f850edf-2082-4f51-a31c-bcb86912dd80">

<img width="687" alt="bnb2" src="https://github.com/user-attachments/assets/5b1577ac-f2c7-4971-9e6d-3c7d535ca555">

<img width="1072" alt="Screenshot 2024-10-16 at 09 35 23" src="https://github.com/user-attachments/assets/73d4a83c-de8e-4b35-bd28-bb5466407be4">

### Steps to reproduce

1. Connect to [test dapp](https://metamask.github.io/test-dapp/)
2. Click `Malicious ERC 20 Approval (BUSD)`, `Malicious Set Approval for All,` or `Malicious ERC20 Approval with Odd Hex Data` 

### Detection stage

In production (default)

### Version

`develop`

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Latest `develop` build

`Malicious ERC 20 Transfer(USDC)` is not flagged on          - Ethereum, Linea, BNB
`Malicious ERC 20 Approval (BUSD)` is not flagged on        - Ethereum, Linea
`Malicious Set Approval for All` is not flagged on                  - Ethereum, Linea, Avalanche
`Malicious Permit` is not flagged on                                        - zkSync
`Malicious Seaport` is not flagged on                                      - zkSync
`Set ETH Malicious x10 Batch` is not flagged on                    - zkSync
`Set ETH Malicious x10 Queue` is not flagged on                  - zkSync
`Malicious Approval with Odd Hex Data` is not flagged on    - Linea
`Malicious Permit with Padded ChainID` is not flagged on     - zkSync
`Sign Permi`t is not flagged on                                                  - Linea, Avalanche, zkSync

ERC20 transfer on BNB (header):



<img width="866" alt="Screenshot 2024-10-18 at 13 23 35" src="https://github.com/user-attachments/assets/e795c29d-27d4-4610-8728-86ccf7a70db2">

**Comment by Unik0rnMaggie** [comment]
On the latest `develop` build, getting the same above results, except for Ethereum Mainnet and zkSync:

1. Ethereum Mainnet:

Console error `Error validating JSON RPC using PPOM:  Error: simulation: fallback: (code: -32000, message: , data: None)` for all the below:

```Send Legacy Transaction
      Send EIP 1559 Transaction
      Send EIP 1559 without gas
      Malicious ERC20 transfer (USDC) 
      Malicious ERC20 Approval (BUSD)
      Malicious Set Approval for All 
      Malicious ERC 20 Approval with Odd Hex Data 
      ```
      
    2. zkSync:
    
   No console error and only the following are not flagged:
    
    ```
    Malicious Permit 
    Malicious Seaport
    Malicious Permit with Padded ChainID 
    ```
    


https://github.com/user-attachments/assets/2d77731c-9646-4390-88fd-b4b5451bdc75


https://github.com/user-attachments/assets/eee54dda-fce0-4e19-be92-3730e6b5c1d2

**Comment by bschorchit** [comment]
The errors should recently have been fixed with this PR: https://github.com/MetaMask/metamask-extension/pull/27939

**Comment by sleepytanya** [comment]
@Unik0rnMaggie  
Latest `develop`.
Ethereum:

`EIP 1559` and Legacy - no errors in the console, yellow warning:

<img width="351" alt="Screenshot 2024-10-21 at 23 07 56" src="https://github.com/user-attachments/assets/b3efcad3-d084-43b8-b8d3-422c141e336c">

 Not flagged: 

```
 Malicious ERC20 transfer (USDC) 
 Malicious ERC20 Approval (BUSD)
 Malicious Set Approval for All 
 Malicious ERC 20 Approval with Odd Hex Data
```

**Comment by jpuri** [comment]
I checked with latest code in develop branch today and all malicious transactions except `Malicious ERC20 Transfer (USDC)` is working on mainnet. This one I think was not working even before.

**Comment by Unik0rnMaggie** [comment]
Hi Team,

As per chat with @jpuri it seems the errors might occur due to missing access on provider for my Infura Key.

With the production Infura key I do not experience any errors. 

@bschorchit would it be possible to receive the access on my Infura key to verify if the error persists? 

Thank you

**Comment by bschorchit** [comment]
Closing as this is not an issue with the production Infura key! We can re-open if we encounter this again. 

@Unik0rnMaggie I'll follow up with you re: permissions for Infura key on slack
