### ISSUE TITLE
[Bug]: Attributions link returns 404: Not found

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#27906]
### Describe the bug

Loading Attributions link in Settings --> About, returns 404: Not found

### Expected behavior

Link returns expected page as in current production build (12.4.1).

### Screenshots/Recordings

https://github.com/user-attachments/assets/c1200c17-93bb-459b-a6d8-f61634fd81b9

### Steps to reproduce

1. Load MM extension
2. Go to Settings --> About
3. Click on Attributions link
4. Notice returned **404: Not found** page

### Detection stage

During release testing

### Version

12.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Gudahtt** [comment]
Closing as expected behavior; the attributions page will not exist until after the release has been published (and this was reported prior to publishing). The attributions now load correctly for v12.5.0
