### ISSUE TITLE
Fix "Settings - general tab @no-mmi validate \"मानक हिन्द..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27904]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/105740/workflows/61aeecc6-d20f-4e84-aeba-bf23f5d6e892/jobs/3947158/tests

Build - Webpack
Browser - Chrome 
Test Path  - /test/e2e/tests/settings/change-language.spec.ts
Test Scenario - Settings - general tab @no-mmi validate "मानक हिन्दी" language on tooltips

```
Language changes is not reflected on the account toolTip
  (Ran on CircleCI Node 10 of 20, Job test-e2e-chrome-webpack)
AssertionError [ERR_ASSERTION]: Language changes is not reflected on the account toolTip
    at /home/circleci/project/test/e2e/tests/settings/change-language.spec.ts:2:5891
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withFixtures (test/e2e/helpers.js:217:5)
    at async Context.<anonymous> (test/e2e/tests/settings/change-language.spec.ts:2:5476)

      + expected - actual

      -false
      +true
```

![image](https://github.com/user-attachments/assets/19dea0ca-8fad-4d29-a541-acd770f0918c)

**Comment by chloeYue** [comment]
Fixed by PR https://github.com/MetaMask/metamask-extension/pull/28777
