### ISSUE TITLE
[Bug]: ppom failing on RC v12.5

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#27909]
### Describe the bug

For the same transaction, ppom is successful on v12.4.0 while it fails on RC v12.5.0. On both releases, ppom version is the same and the node provider being used should be the same too (networks were added from the network menu within the wallet).

Console logs on v12.5 on BNB: 

```
{
  "code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": -32002,
    "message": "the resource debug_traceCall is not available.",
    "cause": null
  },
```

Console logs on v12.5 on Base

```
sentry-install.js:1 {
  "code": -32603,
  "message": "Non-200 status code: '403'",
  "data": {
    "jsonrpc": "2.0",
    "error": {
      "code": -32601,
      "message": "rpc method is unsupported"
    },
    "id": 6378648550496817,
    "cause": null
    },
```

### Expected behavior

ppom works as expected.

### Screenshots/Recordings

v12.4.0:
![image](https://github.com/user-attachments/assets/8534b21d-f65e-42c1-a5e1-d056b12a93a5)

v12.5.0:
![image](https://github.com/user-attachments/assets/0e011487-64cd-4f05-83e9-8365fba7854f)

### Steps to reproduce

1. Add BNB and Base networks from the network menu
2. Go to test dapp
3. Trigger `Malicious erc20 approval (BUSD)` on BNB or Base
4. See the error message being show

### Detection stage

During release testing

### Version

12.5

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by Unik0rnMaggie** [comment]
Reproduced on Version-v12.5.0 local build, MacOS, browsers Chrome & Firefox.

Networks: Ethereum Mainnet, Sepolia, BNB, Base, Linea, Avalanche, Arbitrum

PPOM failing for:

* Malicious ERC20 transfer (USDC) 
* Malicious ERC20 Approval (BUSD) 
* Malicious Set Approval for All 
* Malicious ERC 20 Approval with Odd Hex Data 

Console log errors - Chrome: 

`"code": -32603,
  "message": "Non-200 status code: '403'",
  "data": {
    "jsonrpc": "2.0",
    "error": {
      "code": -32601,
      "message": "rpc method is unsupported"
    },
    "id": 5903517567864872,
    "cause": null`
    
    `"code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": -32601,
    "message": "The method debug_traceCall does not exist/is not available",
    "cause": null`
    
    
Console log errors - Firefox:
    
`Error validating JSON RPC using PPOM: Error: simulation: JS: JsValue(Error: Non-200 status code: '403'`
Base, Avalanche

`Error validating JSON RPC using PPOM: Error: simulation: JS: JsValue(Error: Internal JSON-RPC error.` 
Arbitrum, BNB   

`Error: simulation: JS: JsValue(Error: The method debug_traceCall does not exist/is not available` 
Linea, Ethereum Mainnet


https://github.com/user-attachments/assets/3d5fbdf8-5ae1-4a0e-90b0-416ef5921b22

**Comment by Unik0rnMaggie** [comment]
Firefox PPOM errors

https://github.com/user-attachments/assets/d3e750f9-1edd-45ee-827a-cfbcbe28d31c


https://github.com/user-attachments/assets/f2331a34-aabe-4ccc-832d-ec64f91ba9da


https://github.com/user-attachments/assets/12aea4c0-c4de-42e1-86e0-eab08051218a
