### ISSUE TITLE
Fix "Confirmation Redesign ERC721 Approve Component Submit an Approve transaction @no-mmi Sends a type 2 transaction (EIP1559)"

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27929]
### What is this about?

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/106162/workflows/f5e12fd8-1e8e-42db-a142-704f62e18a8f/jobs/3965001/tests

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by hjetpoluru** [comment]
Here is the fix for this flaky test - https://github.com/MetaMask/metamask-extension/pull/27928

**Comment by hjetpoluru** [comment]
@seaona, I closed the ticket with the above-mentioned PR. Could you please confirm if that is correct? I actually noticed this flaky test last week as well. Also, looking at this PR https://github.com/MetaMask/metamask-extension/pull/27928 it seems to have fixed anti-patterns. 
Here is another ticket I created last week: https://github.com/MetaMask/metamask-extension/issues/28264, and I have started the analysis.
