### ISSUE TITLE
Too much gas is suggested for transfers

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#2792]
Transfers will *always* use 21000 gas, but Metamask suggests 31500, which overestimates transaction fees by 50%.

**Comment by wjmelements** [comment]
Metamask > Send > Next

**Comment by danfinlay** [comment]
We simply ask the node `eth_estimateGas` and return the result. There's probably a reason geth has started returning 31500 for the transfers you're estimating. Are they to contracts?

**Comment by danfinlay** [comment]
Oh actually I think we do fudge slightly higher than the estimated gas price, to account for mid-transaction-execution gas refunds, which were resulting in Out-of-gas errors on otherwise fine transactions.

I guess we could hard code simple send gas prices?

**Comment by wjmelements** [comment]
Yes, you can hard code transfer gas cost since it is constant, even if the recipient is a smart contract that overrides the fallback function.

**Comment by danfinlay** [comment]
But it's *not* constant if the recipient is a smart contract that overrides the fallback function. We'd still need to estimate gas, and then just assume a `21000` estimate was because the fallback function wasn't used or because the transaction resulted in that much gas burned. This looks like a change of dubious value with potentially buggy results to me.

**Comment by wjmelements** [comment]
http://solidity.readthedocs.io/en/develop/contracts.html#fallback-function
http://solidity.readthedocs.io/en/develop/security-considerations.html#sending-and-receiving-ether
https://ethereum.github.io/yellowpaper/paper.pdf

The fallback function is limited to a 2300 gas stipend from the 21000 transfer gas. Using more than 2300 gas causes the transfer to fail, but does not impact the 21000 defined in the yellow paper. Sending additional gas does not increase the stipend. You can test this yourself.

**Comment by wjmelements** [comment]
I am mistaken. I tested this on rinkeby (https://rinkeby.etherscan.io/tx/0xe0de7690105ca15a3a66c318f6e070c191241153dbcb8646d67a4fd7e78eb7b5) and found that fallback functions do in fact consume gas outside of the transfer cost. I believe this may still be limited by the 2300 stipend, however.

**Comment by wjmelements** [comment]
For transfers where estimateGas returns 21000, the recipient is not a smart contract, so that case could be hardcoded.

**Comment by kumavis** [comment]
>  I believe this may still be limited by the 2300 stipend, however.

this is not correct

**Comment by kumavis** [comment]
the 2300 gas stipend refers to a common pattern in contract -> contract calls, not top level txs

**Comment by kumavis** [comment]
> For transfers where estimateGas returns 21000, the recipient is not a smart contract, so that case could be hardcoded.

I agree, but I would implement it via a `eth_getCode` check

**Comment by kumavis** [comment]
Formalized as feature request here https://github.com/MetaMask/metamask-extension/issues/2907
