### ISSUE TITLE
Chrome plug-in never accepts password, requires seed recovery every time.

### ISSUE THREAD

**Issue by dkirby7** [MetaMask/metamask-extension#2795]
I suspect I may be using invalid special characters, but have tried different combinations of typical sets including no special characters at all. The passwords I try are always 12+ characters and are accepted during seed recovery.

There should be password strength requirements that are clearly stated (one uppercase, one lowercase, one number, one special [with list of accepted special characters], etc.).

**Comment by Zanibas** [comment]
Can you give us an example of what kinds of invalid characters you are attempting to use?

**Comment by dkirby7** [comment]
I have used standard special characters with a number of different
passwords such as !@#$%^&*()

**Comment by bdresser** [comment]
fixed on the new UI
