### ISSUE TITLE
[Bug]: Network Switch - Weird screen appears when I trigger the `wallet_switchEthereumChain` method and pending notification number keeps adding up

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27977]
### Describe the bug

The classical weird screen appears when I trigger a `wallet_switchEthereumChain` method on a second dapp, after triggering a signature and a `wallet_switchEthereumChain` on a first dapp . The notification number keeps adding up in the MM icon, no matter if I close the screen.
The recovery path is to click the reload button from the Extension.

![Screenshot from 2024-10-21 08-21-50](https://github.com/user-attachments/assets/7f4ed0e4-6e91-413e-b30c-812670f6f480)

### Screenshots/Recordings

https://github.com/user-attachments/assets/eb97da1c-29b4-4760-8e7f-8f76ba4c7042

### Steps to reproduce

1. Go to test dapp and open the console
2. Being on Sepolia, trigger a signature
3. Switch to Mainnet using switchEthereumChain method
4. Go to another dapp and switch to Sepolia using switchEthereumChain
5. See screen

```
await window.ethereum.request({
 "method": "wallet_switchEthereumChain",
 "params": [
  {
    chainId: "0xAA36A7"
  }
],
});
```

### Detection stage

On the development branch

### Version

last develop (oct 21st) - commit 4eaeb68

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
Update: changing the severity to sev 2 as disabling and enabling the wallet clears the pending notifications

**Comment by dabossdana** [comment]
Update: changing the severity to sev 2 as disabling and enabling the wallet clears the pending notifications

**Comment by seaona** [comment]
This will appear in version `12.8.0`. I've added the tag `release-blocker` but feel free to re-assess if you think it's not a blocker
cc @adonesky1
