### ISSUE TITLE
not able to send tokens from loose Account

### ISSUE THREAD

**Issue by cparkhi** [MetaMask/metamask-extension#2800]
Hi,
I had an ether address created on Jaxx in which the NGC tokens have been received. I imported the same account to metamask and i can see my tokens ... however when i try to send the tokens to HitBtc exchange the metamask shows that I have insufficient balance ... though when i go back to token screen it shows my tokens there ...... is it not allowed to send tokens from loose account ? .. if not then what is the alternative ?

**Comment by Zanibas** [comment]
Do you have enough ether in your account to pay for the transaction fees? All ethereum transactions require some ether--you'll probably need more in your acct to process it, unfortunately.

**Comment by bdresser** [comment]
@cparkhi if you're still looking for help please reach out to support@metamask.io
