### ISSUE TITLE
[Bug]: When an account hasn't been enabled in the Permissions, attempting to initiate a transaction from a dApp results in the transaction being created from an enabled account but with the nonce value matching the account selected by user

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28014]
### Describe the bug

When an account hasn't been enabled in the` Permissions`, attempting to initiate a transaction from a dApp results in the transaction being created from a different, enabled account. Interestingly, the nonce value corresponds to the non-enabled account selected in MetaMask.

If a transaction is created with a nonce that is too low, it fails and generates errors. Conversely, if the nonce is set too high, the transaction remains in a` Pending` state without displaying any error messages. 

### Expected behavior

-

### Screenshots/Recordings

<img width="782" alt="Screenshot 2024-10-22 at 12 30 35" src="https://github.com/user-attachments/assets/9c1c380b-bf40-423d-bfff-e2e8e727cac6">

<img width="700" alt="Screenshot 2024-10-22 at 12 30 44" src="https://github.com/user-attachments/assets/6b03bfa6-6942-47cb-82b2-0896f92e5905">

<img width="624" alt="Screenshot 2024-10-22 at 12 35 14" src="https://github.com/user-attachments/assets/82bdc087-aabb-4304-9529-ea9ad329e96a">

https://github.com/user-attachments/assets/33c08073-e553-4cfa-bb4b-a07cede6e011

### Steps to reproduce

1. Enable an account connected to the dApp
2. Switch to non-enabled account in the MetaMask
3. Initiate a transaction from the dApp

### Detection stage

On the development branch

### Version

develop

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
@jpuri reported this is not a v12.6 regression so I have updated the label. We'll continue to prioritize a fix for this issue
