### ISSUE TITLE
Download Google Chrome

### ISSUE THREAD

**Issue by Annecoolitz** [MetaMask/metamask-extension#2803]
I tried to download the meramask or the mist but alwasy pop up need to download the googe chrome but i am using google chrome for ios. What google chrome i need to download so that i can download and make an account to metamask and the mist. Please help what i need to do to. Thank you and happy holidays
![db06039f-4d3c-4c2e-bb6e-d28ada41e9d0](https://user-images.githubusercontent.com/34797228/34321612-118212b2-e84e-11e7-8a13-3621d72cfe83.jpeg)

**Comment by tmashuang** [comment]
It seems you are trying to download on a mobile device. I do not believe Chrome has enabled extensions for mobile. I believe Firefox has implement it. Also, look into the Cypher browser for iOS.

**Comment by Zanibas** [comment]
Future maybe TODO: add to landing page that we don't support mobile.
