### ISSUE TITLE
MetaMask Lost Account

### ISSUE THREAD

**Issue by ZuFire** [MetaMask/metamask-extension#2804]
I cannot access my previous MetaMask address.  Everytime I log into "MyEtherWallet" using MetaMask, it takes me to a different address.  I've used my private key, secret seeds, and generated 20+ accounts trying to find the 1 account I had before MetaMask screwed me over and changed it for some reason.

Correct/Original address: 
0x3720db24E7EB7a328B8c18CFe734783cEa5837b3
New Address that keeps appearing:
0xfE6b669d4CD4b3f834e54413DBb0353Bc4911fA3

Please someone help me recover my account!!!!!!

**Comment by protonjo** [comment]
Was this issue ever resolved? This is the same thing that happened to me while using metamask with MEW. See my unresolved post https://github.com/MetaMask/metamask-extension/issues/2874

**Comment by Zanibas** [comment]
If you are restoring from MEW using your secret seed words, are you restoring without a password? The MetaMask password is different from the MEW password--try restoring without the password.

**Comment by bdresser** [comment]
@ZuFire if you're still looking for help I'd encourage you to reach out to support@metamask.io

**Comment by anthonyC77** [comment]
Hello all. I had lost my accounts on Metamask.
I'm not sure what happened, I think it was the use of Brave/Chrome/Firefox at the same time with 2 differents seeds or changes 
You need to have your seed and the metamask's password attached to this seed.
This tool saved my accounts : https://iancoleman.io/bip39/
You can run it offline (recommended) , it will seek in your browser and it will find all your lost accounts.

Thanks to the developpers who have created this great tool !
Have a nice day hope you will recover your accounts. 

![image](https://user-images.githubusercontent.com/35571461/112808745-9c244f80-9079-11eb-8cfb-e6ed3795aebc.png)

**Comment by monikatern** [comment]
@Silentmobius If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
