### ISSUE TITLE
[Bug]: Clicking Send Shows Over 600+ Local Accounts

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#28053]
### Describe the bug

When clicking the "Send" button from the wallet home screen, the screen hangs until the Send page finally loads and suddenly there are 600+ accounts in my MetaMask.  The 600+ accounts persist when opening the Accounts Menu as well.

### Expected behavior

There should only be the few accounts I had created in the first place.

### Screenshots/Recordings

https://github.com/user-attachments/assets/4e09eec1-65c2-4c31-b617-3d709282157f

### Steps to reproduce

1.  Click send
2. (wait for hang to finish)
3. Scroll to see 600+ accounts

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by plasmacorral** [comment]
related to profile sync

**Comment by Prithpal-Sooriya** [comment]
CC @MetaMask/notifications to look into.
We have turned off account sync for V12.6.0, this should not appear for this version.
We are undergoing QA to ensure that this feature is working as intended.

**Comment by Prithpal-Sooriya** [comment]
Qs:
1. Is the SRP used an account shared by other teams?
- If so then there may have been performance tests done by other teams of adding multiple accounts and this was synced. Meaning as a user who is importing this SRP, of course you would retrieve all the synced accounts - so is functioning as intended.

2. If not, then we need to investigate and ensure that we aren't arbitrarily adding accounts you have not synced!

**Comment by hjetpoluru** [comment]
I have removed the label release blocker with the reference to the [comment here. ](https://consensys.slack.com/archives/C029JG63136/p1729784501975159?thread_ts=1728037233.079029&cid=C029JG63136) I have added sev1- high label

**Comment by Prithpal-Sooriya** [comment]
This needs to be double checked, but we don't think this is a high sev (sev-1) bug.

Shared SRPs (especially with devs who are running the extension with 100 accounts) will get synced, and subsequent onboarding will append these accounts.
We have a section in the developer options to clear the SRP.

Real users will not be impacted by this (as they cannot onboard their wallet with an initial 100s of accounts).

I will leave this for @mathieuartu to comment and close :)

**Comment by Prithpal-Sooriya** [comment]
I am removing the high sev (sev-1) bug, as this has been resolved.

https://github.com/MetaMask/core/pull/4933
https://github.com/MetaMask/core/pull/4746

I will move this to sev-2, and @mathieuartu / @cmd-ob can confirm if this can be closed

**Comment by Prithpal-Sooriya** [comment]
Confirmed, this can be closed.
