### ISSUE TITLE
Is it a firefox legit version ?

### ISSUE THREAD

**Issue by Nogreedy** [MetaMask/metamask-extension#2806]
Hello,
Is it a legit version : YES or NO?   
https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/   
https://www.reddit.com/r/ethereum/comments/7l7ify/hacked_anyone_wanna_help_figure_out_whats_going_on/
Thanks for your answer.

**Comment by amites** [comment]
don't know with any certainty, the code inside seems to be a pretty clean match

though the manifest.json includes entries that aren't compatible with firefox (still seems to work through)

**Comment by Nogreedy** [comment]
@amites : thanks for your answer....   
I wasn't sure about this version (because I believed there wasn't a firefox version...)... now I think it's the "new" Firefox version...

**Comment by Zanibas** [comment]
This is the correct Firefox version--no worries. We link it directly in our landing page!
