### ISSUE TITLE
option to not show USD?

### ISSUE THREAD

**Issue by dchudz** [MetaMask/metamask-extension#2807]
Not sure if anyone else has the same issue, but I find it's better for my happiness to not follow day-to-day (or hour-to-hour) price movements.

To let me satisfy that goal while still using MetaMask, it'd be nice to have an option in settings to turn off showing the USD equivalent.

(I won't be offended if you close this, figuring that no one else cares - just thought I'd toss it out there.)

**Comment by Zanibas** [comment]
We understand the sentiment that you're coming from--we'll propose it as an idea at one of our next design meetings!

**Comment by dchudz** [comment]
Thanks!

**Comment by jennypollack** [comment]
Option to select display of Primary Currency (ETH vs Fiat) was added here https://github.com/MetaMask/metamask-extension/pull/5421

**Comment by dchudz** [comment]
Thanks!
