### ISSUE TITLE
Compile error for gulp build

### ISSUE THREAD

**Issue by JD-YANG** [MetaMask/metamask-extension#2808]
Compile error for gulp build

What I want to build by guild commend (gulp-build) , error occurs,

[11:43:17] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (/Users/d/dev/metamask-extension/node_modules/vinyl-fs/lib/dest/prepare.js:16:17)
    at DestroyableTransform.Transform._read (/Users/d/dev/metamask-extension/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/d/dev/metamask-extension/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/d/dev/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/d/dev/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/d/dev/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (/Users/d/dev/metamask-extension/node_modules/duplexify/index.js:201:22)
    at doWrite (/Users/d/dev/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/d/dev/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Pumpify.Writable.write (/Users/d/dev/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:322:11)

**Comment by rolong** [comment]
fix vinyl-source-stream to 2.0.0 in /package.json，it's fine!
"vinyl-source-stream": "^2.0.0"

**Comment by nithya2609** [comment]
hi,
I have the same error. i dont have vinyl dependency in my package.json.

this is my package.json

{
  "name": "clfatest",
  "version": "2.7.3",
  "license": "UNLICENSED",
  "keywords": [
    "5 Star",
    "appgen",
    "appgen-v3",
    "intc",
    "Intel"
  ],
  "dependencies": {
    "gulp": "^3.9.1",
    "lodash": "^3.10.0"
  },
  "devDependencies": {
    "bardjs": "^0.1.8",
    "browser-sync": "^2.7.13",
    "chai": "^3.5.0",
    "chalk": "^1.1.0",
    "del": "^2.2.0",
    "eslint": "^2.5.3",
    "eslint-html-reporter": "^0.4.10",
    "eslint-plugin-angular": "1.0.0",
    "estraverse": "^4.2.0",
    "estraverse-fb": "^1.3.1",
    "globby": "^4.0.0",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-angular-filesort": "^1.1.1",
    "gulp-angular-templatecache": "^1.7.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-bump": "^2.1.0",
    "gulp-cheerio": "^0.6.2",
    "gulp-concat": "^2.6.0",
    "gulp-debug": "3.x",
    "gulp-dom-src": "^0.2.0",
    "gulp-eslint": "^2.0.0",
    "gulp-flatten": "0.2.0",
    "gulp-git": "^1.2.4",
    "gulp-htmlmin": "^2.0.0",
    "gulp-inject": "^4.0.0",
    "gulp-minify-inline": "^0.2.1",
    "gulp-natural-sort": "0.1.1",
    "gulp-ng-annotate": "^2.0.0",
    "gulp-purifycss": "^0.2.0",
    "gulp-replace": "^0.5.3",
    "gulp-rev": "^7.0.0",
    "gulp-rev-replace": "^0.4.2",
    "gulp-sass": "^2.0.3",
    "gulp-size": "^2.1.0",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.6",
    "gulp-watch": "^4.2.4",
    "icap-publish": "git+https://github.intel.com/intc/icap-publish.git#1.x",
    "karma": "^0.13.22",
    "karma-chai": "^0.1.0",
    "karma-chai-sinon": "^0.1.5",
    "karma-chrome-launcher": "^0.2.2",
    "karma-coffee-preprocessor": "^0.3.0",
    "karma-coverage": "^0.5.5",
    "karma-firefox-launcher": "^0.1.7",
    "karma-ie-launcher": "^0.2.0",
    "karma-mocha": "^0.2.2",
    "karma-ng-html2js-preprocessor": "^0.2.1",
    "karma-ng-scenario": "^0.1.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sinon": "^1.0.4",
    "main-bower-files": "^2.8.2",
    "mocha": "^2.4.5",
    "phantomjs-prebuilt": "^2.1.6",
    "semver": "^5.0.3",
    "sinon": "^1.17.2",
    "sinon-chai": "^2.8.0",
    "spock": "^0.3.3",
    "stream-series": "^0.1.1",
    "yargs": "^4.3.2"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp build",
    "test": "gulp test"
  }
}

**Comment by nullbio** [comment]
Same error for me too.

```  "devDependencies": {
    "autoprefixer": "^6.7.7",
    "event-stream": "^3.3.4",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-clean-css": "^3.0.4",
    "gulp-gzip": "^1.4.0",
    "gulp-less": "^3.3.0",
    "gulp-livereload": "^3.8.1",
    "gulp-minify": "0.0.15",
    "gulp-plumber": "^1.1.0",
    "gulp-postcss": "^6.4.0",
    "gulp-rev": "^7.1.2",
    "gulp-rev-delete-original": "^0.2.3",
    "del": "^2.2.2",
    "gulp-sass": "^3.1.0",
    "gulp-watch": "^4.3.11",
    "postcss-flexbugs-fixes": "^2.1.0",
    "vinyl-source-stream": "^2.0.0"
  }
```

**Comment by nithya2609** [comment]
change this  "gulp": "github:gulpjs/gulp#4.0", to 
"gulp": "git://github.com/gulpjs/gulp.git#6d71a658c61edb3090221579d8f97dbe086ba2ed"

remove node modules and run npm install again.
this should fix the error

**Comment by DurgaMasabattula** [comment]
@nithya2609 it worked with your suggestion, but why should we update it in that way

**Comment by nithya2609** [comment]
earlier my gulp version was pointing to 4.0.0 alpha 3 ..n i had the same problm ..when i  changed gulp to alpha  4.0.0 alpha 2  , it worked

**Comment by nithya2609** [comment]
not sure why it doesnt work with alpha 3

**Comment by nullbio** [comment]
@nithya2609 Worked for me, thank you.

**Comment by quickstep25** [comment]
I was using Gulp 4.0 and was getting the same error message about vinyl when trying to send my .js through the **reqiurejs.js** optimizer **r.js**:

**Received a non-Vinyl object in dest()**

```
	"devDependencies": {
		"babel-core": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"chalk": "^2.3.0",
		"deeply": "^2.0.3",
		"del": "^3.0.0",
		"gulp": "^4.0.0",
		"gulp-babel": "^7.0.1",
		"gulp-clean-css": "^3.9.2",
		"gulp-concat": "^2.6.1",
		"gulp-filter": "^5.1.0",
		"gulp-html-replace": "^1.6.2",
		"gulp-imagemin": "^4.1.0",
		"gulp-less": "^3.4.0",
		"gulp-pug": "^3.3.0",
		"gulp-remove-markdown": "^1.0.2",
		"gulp-rename": "^1.2.2",
		"gulp-requirejs-bundler": "^0.1.1",
		"gulp-sass": "^3.1.0",
		"gulp-uglify": "^3.0.0",
		"gulplog": "^1.0.0"
	}
```

Reverting to a previous version of gulp was the only thing that successfully worked for me as well:

```
"gulp": "git://github.com/gulpjs/gulp.git#6d71a658c61edb3090221579d8f97dbe086ba2ed"
```
Thank you @nithya2609, your solution worked for me too.

**Comment by yupnano** [comment]
@nithya2609 worked for me! Thank you! It's Sooooo Cool!
