### ISSUE TITLE
[Design quality]: Update border weight and color for networks and status badges

### ISSUE THREAD

**Issue by amandaye0h** [MetaMask/metamask-extension#28081]
### Describe the bug

There is inconsistent border width for badges (status and networks) which makes the Portfolio View spacing feel off. Updating this improves overall visual cohesion and product quality. 

### Expected behavior

Multichain menu badge (connected sites)
- `border width` = `3px` > `2px`

Network badge updates
- `border width` = `1px` > `2px`
- `color` = `bg.alternative` > `bg.default`
- Make sure changes are reflected in the `Asset Picker` and `Import Tokens`

Network menu
- Remove border in default, selected and hover states

Account badge
- `border width` = `4px` > `2px`

### Screenshots/Recordings

<img width="1070" alt="Screenshot 2024-10-25 at 12 18 29 AM" src="https://github.com/user-attachments/assets/2a040b63-382d-4665-9840-f3bf7061b51f">

[Figma link](https://www.figma.com/design/aMYisczaJyEsYl1TYdcPUL/Portfolio-View?node-id=6235-15524&t=x7GxHjVI19oISUoI-4)

<img width="815" alt="Screenshot 2024-10-25 at 12 26 09 AM" src="https://github.com/user-attachments/assets/c34b80e8-4dde-456a-81df-c13c38dc57bc">

[Figma link](https://www.figma.com/design/aMYisczaJyEsYl1TYdcPUL/Portfolio-View?node-id=6235-15566&t=x7GxHjVI19oISUoI-4)

<img width="729" alt="Screenshot 2024-10-25 at 12 30 11 AM" src="https://github.com/user-attachments/assets/467b1625-6092-43de-96e4-5e15e1e8f92f">

[Figma link](https://www.figma.com/design/aMYisczaJyEsYl1TYdcPUL/Portfolio-View?node-id=6235-15580&t=x7GxHjVI19oISUoI-4)

### Steps to reproduce

1. Open MetaMask
2. Open network menu
3. Connect account
4. Click on account selector

### Detection stage

In production (default)

### Version

12.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Ping @amandaye0h and @georgewrmarshall for reviews

**Comment by DDDDDanica** [comment]
Note: based on https://github.com/MetaMask/metamask-extension/pull/28976/files#r1878908560 => 
> Network menu: Remove border in default, selected and hover states

this one does not apply any more.
