### ISSUE TITLE
[Bug]:  Unable to send ERC20 from the token details screen

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28083]
i### Describe the bug

There's an issue when attempting to send ERC20 tokens from the token details screen, where token balances are displayed as zero on confirmation screen. Entering any amount to send triggers an "insufficient token balance" message. 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/cf1da1ba-e46c-4114-b6e8-47c663f9759e

### Steps to reproduce

1. Go to any non-native token details
2. Click 'Send'

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by sleepytanya** [comment]
closing - duplicate https://github.com/MetaMask/metamask-extension/issues/27813

**Comment by Tao546127REP** [comment]
> i### Describe the bug
> 
> There's an issue when attempting to send ERC20 tokens from the token details screen, where token balances are displayed as zero on confirmation screen. Entering any amount to send triggers an "insufficient token balance" message.
> 
> ### Expected behavior
> 
> ### Screenshots/Recordings
>  sendToken.mov 
> 
> ### Steps to reproduce
> 1. Go to any non-native token details
> 2. Click 'Send'
> 
> ### Error messages or log output
> _No response_
> 
> ### Detection stage
> During release testing
> 
> ### Version
> 12.6.0
> 
> ### Build type
> None
> 
> ### Browser
> Chrome, Firefox
> 
> ### Operating system
> MacOS
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Severity
> _No response_



Hey @sleepytanya It sounds like you're facing a frustrating issue with sending ERC20 tokens. If the token balances show as zero on the confirmation screen, it could be a problem with the wallet syncing or a bug in the interface. consider reaching out to the support team of the wallet or platform you’re using for further assistance. I'll have to refer you to the official support Requests team with the ticket ID MET124560
Please see the link below to our dedicated support line:
[Metamask Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat.
