### ISSUE TITLE
[Bug]: Onboarding - After adding a network while in the Onboarding Settings page, I land into the Password screen and when Iog in I land again into the Onboarding page

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28097]
### Describe the bug

When I am performing the Onboarding flow, if I go to General Settings and I add a network, I see how I land automatically to the Password page.
This seems wrong. After I add my newly created password, I land back again into the Onboarding page Your Wallet is Ready.

### Expected behavior

After adding a network, I should remain into the Onbording General Settings page

### Screenshots/Recordings

https://github.com/user-attachments/assets/961920a6-40e5-4910-9c3e-ffe2be1a3517

### Steps to reproduce

1. Start the onboarding
2. Click Manage Settings
3. Go to General Settings
4. Click Add network
5. Click Arrow back
6. Add any popular network
7. See how you land into the Password page
8. Log in
9. See how you land back to the Your wallet is ready page

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
:information_source: Added the release-blocker tag just in case, given the onboarding change is new, but feel free to re-assess if needed

**Comment by NidhiKJha** [comment]
@seaona I am not able to repro this bug. 
https://github.com/user-attachments/assets/7bc5bbb5-dd30-4391-8f40-952423705647

**Comment by hesterbruikman** [comment]
@seaona can you confirm that you're uses an Imported account? I can reproduce, but only when importing.

**Comment by hesterbruikman** [comment]
Removing the release-blocker label. While a clunky experience we want to improve, the flow to is not expected to occur frequently. Thanks for providing a fix @darkwing . If we can get it merged and into release, great, but @vpintorico I would not block release for it. Too much going out and on cadence.

**Comment by seaona** [comment]
I see this happenning when you are performing the Onboarding flow both with Create New Wallet and Import Wallet.

Thank you for taking a look! It make sense to me @hesterbruikman
