### ISSUE TITLE
[Bug]: API Requests Unordered - Whenever I perform different wallet API requests from different dapps, those don't appear ordered sequentially based on the order of myactions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28102]
### Describe the bug

Whenever I perform different wallet API requests from different dapps, those don't appear ordered sequentially.

### Expected behavior

Not 100% sure but, I think requests should be ordered sequentially based in the order of the request happening? (first request appears first, second request appears second, and so on) ?

@adonesky1 and the wallet api team can confirm what's the expected behaviour here

### Screenshots/Recordings

Example 1:
1. Dapp1: `eth_signTypedData_v4`
2. Dapp1: `wallet_addEthereumChain`
3. Dapp2: `personal_sign`

Resulting order:
1. Dapp1: `eth_signTypedData_v4` --confirm/cancel
2. Dapp2: `personal_sign` --confirm/cancel
3. Dapp1: `wallet_addEthereumChain`

https://github.com/user-attachments/assets/b309ce93-e593-4e88-a622-dd7d5cfd2123

Example 1:
1. Dapp1: `eth_signTypedData_v4` x10
2. Dapp2: `wallet_requestPermissions`

Resulting order:
1. Dapp1: `eth_signTypedData_v4` x10 --confirm/cancel
2. Dapp2: `wallet_requestPermissions` --confirm(if in the same network)/cancel
3. The remaining 9 signatures  Dapp1: `eth_signTypedData_v4` x9
https://github.com/user-attachments/assets/2288e2ff-dd3e-4113-94fa-8d89bde2c29d

### Steps to reproduce

See above 

### Detection stage

In production (default)

### Version

12.5.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Gudahtt** [comment]
This appears to be resolved by https://github.com/MetaMask/metamask-extension/pull/28090 as well
