### ISSUE TITLE
transaction says failed, but succeeded

### ISSUE THREAD

**Issue by dchudz** [MetaMask/metamask-extension#2810]
The latest transaction in my MetaMask history says it failed (`NonceTakenErr`), but when I click on the transaction and view it in etherscan, I can see that it succeeded just fine.

In case it helps: This transaction was generated by MEW to call a function in a contract in the Ropsten test network.

Screenshot:

<img width="1315" alt="screen shot 2017-12-25 at 7 22 39 pm" src="https://user-images.githubusercontent.com/1222726/34343796-878ed54c-e9a9-11e7-8945-d181c533726e.png">

**Comment by frankiebee** [comment]
@dchudz would you mind providing the state? heres how you can do that: https://github.com/MetaMask/faq/blob/master/LOGS.md#ui-state-logs-chrome

**Comment by dchudz** [comment]
Sure, here you go: https://gist.github.com/dchudz/3ff32a66d7ec05e21d535a9884da8b5c

**Comment by frankiebee** [comment]
Thanks this is defiantly a bug!

**Comment by dchudz** [comment]
Thanks for working on it! :)

**Comment by Srdjn1986** [comment]
I have had the same problem. also on 25 Dec 2017. This was a transaction for EOS ico. Now I can not claim the tokens from EOS. Can this still be solved?
