### ISSUE TITLE
Will not connect to main Ethereum network

### ISSUE THREAD

**Issue by zeldalink1** [MetaMask/metamask-extension#2811]
Hi,

I have been using metamask with no issue but have now found that it will not connect to the main ethereum network at all. I get the below screenshot.

![image](https://user-images.githubusercontent.com/34855776/34352758-497b17ca-ea1c-11e7-8aed-140dfdb30c2c.png)

What can I do?

**Comment by frankiebee** [comment]
@zeldalink1 have you tried switching network and then switching back to main net?

**Comment by reverendcaptainkickass** [comment]
I've encountered this exact same issue when attempting to restore from phrase. I extra mega double checked the spelling and attempted to connect to every network visible from the selection dropdown.  I can enter data and click the OK button but am only met with the infinite spinner. Any help is appreciated.

**Comment by EventStudyTools** [comment]
Same here... is it network congestion or something with meta mask?

**Comment by zeldalink1** [comment]
Hi, after some time I tried changing to Test network and back and this fixed the issue, would suggest anyone else try the same.

**Comment by tmashuang** [comment]
Consolidating to #2636.
