### ISSUE TITLE
[Bug]: Permit token amounts display different values in the Estimated Changes > Spending Cap and Message > Value

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28118]
### Describe the bug

Permit token amounts display different values in the `Estimated Changes > Spending Cap` and `Message > Value`

Related - https://github.com/MetaMask/metamask-extension/pull/27328

### Expected behavior

- Both values must be 3.000

### Screenshots/Recordings

<img width="796" alt="Screenshot 2024-10-27 at 22 17 58" src="https://github.com/user-attachments/assets/95ff2704-fca4-411e-b2b6-40dc6b099531">

### Steps to reproduce

1. Go to the [test dapp](https://metamask.github.io/test-dapp/)
2. Click `Sign Permit`
3. Observe that values in the `Estimated Changes > Spending Cap` and `Message > Value` do not match

### Detection stage

During release testing

### Version

12.6.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by pnarayanaswamy** [comment]
ToDo: Check if this is fixed in 12.7.0
