### ISSUE TITLE
Metamask removing imported accounts after restarting Chrome

### ISSUE THREAD

**Issue by beether** [MetaMask/metamask-extension#2820]
This is annoying as hell.

**Comment by frankiebee** [comment]
@beether I'm sure it is annoying but we cant help you or fix this with out knowing anything.
Things that would be useful:
- What OS are you using
- What browser are you using and what version number
- What version number of metamask are you on (that can be found in the info section which you can navigate to from the menu in the top right corner)
- Are their any error messages in your background console ([here is how to do that](https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome))

**Comment by Zanibas** [comment]
If you could also provide us with your state logs if possible? Can be retrieved from the settings page.

**Comment by mico** [comment]
Experiencing same problem. Also it forgot main account. I have to start from very beginning.
Mac OS X 10.13.3
Chrome 66.0.3359.139
Metamask 4.6.1

**Comment by electronicdreamer** [comment]
Have the same problem.

Windows 10 Pro 
Chrome 66.0.3359.181
Metamask 4.7.3

No errors in the background console

My main account is always there but everytime I import an account, it disappears later.
I don't even think I close Chrome, I just put my computer in sleep mode.

**Comment by brandostrong** [comment]
I have this issue as well. Account does not persist after any restarts. Has persisted through multiple chrome installs.

Metamask 4.7.4
Chrome Version 68.0.3440.15 (Official Build) dev (64-bit)
Windows 10 Pro

**Comment by jennypollack** [comment]
closing for now, but anyone still experience the issue, please open a ticket on our support site https://metamask.zendesk.com/hc/en-us
