### ISSUE TITLE
[Bug]: when sending a batchRequest the same nonce for all transactions

### ISSUE THREAD

**Issue by Pasha8914** [MetaMask/metamask-extension#28239]
### Describe the bug

When sending a Batch request, confirmation windows appear with the same nonce

### Expected behavior

 nonce should be different

### Screenshots/Recordings

https://github.com/user-attachments/assets/3493481d-a61b-4b96-89b8-99edc646aec4

### Steps to reproduce

1. Run [project](https://github.com/Pasha8914/wagmi-approve/pull/1)
2. Click _Send self-tx_
3. Sign your first transaction instantly
4. Second transaction has same nonce

### Detection stage

In production (default)

### Version

12.5.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Severity

High probability of losing funds

**Comment by dan1kov** [comment]
I had the same problem ☹️

**Comment by dan1kov** [comment]
I have the same problem ☹️

**Comment by lamarinatesh** [comment]
☝️☝️

**Comment by seaona** [comment]
Might be similar/same as https://github.com/MetaMask/metamask-extension/issues/27617

**Comment by bschorchit** [comment]
This will be fixed on extension release v12.7 if the user has "Improve transaction requests" toggle enabled. The toggle will be automatically enabled to all users on v12.8

**Comment by sleepytanya** [comment]
Possibly fixed by https://github.com/MetaMask/metamask-extension/pull/28272

**Comment by bschorchit** [comment]
Closing as this has been fixed
