### ISSUE TITLE
max option not available when transfering funds

### ISSUE THREAD

**Issue by brandonm78** [MetaMask/metamask-extension#28246]
### What is this about?

I am using the chrome extension and recently it upgraded to version 12.5.0.  Since the upgrade, the max option for sending an ERC20 token is not displayed when you click on the token first, and then select the send option under the token.    I can still get the max option for sending if I click on send when first launching the extension (defaults to ETH), then select the token But not the other way around.  It used to work both ways in prior versions and now is a bit confusing cumbersome.

### Technical Details

C

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by bergeron** [comment]
Potentially resolved in 12.5.1 by https://github.com/MetaMask/metamask-extension/pull/28136

**Comment by Elsiehwoods** [comment]
@brandonm78  It seems like the recent update might have introduced some changes to the interface.I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
