### ISSUE TITLE
I’m trying to add the MetaMask plugin into the Google Chrome on iPad

### ISSUE THREAD

**Issue by TonyAello** [MetaMask/metamask-extension#2824]
Hi
how can I add the MetaMask plugin into the Google Chrome on iPad?

I tried to follow the instructionsions on environ.org ICO web site, following the link and after clicking ”add to desktop“ from their link (the same that leads from MM web site) and the the icon changes to “added on desktop”, but nothing nor on the desktop neither in the Crome browser on the right hand side from the search link as shown on your introduction video.

thanks in advance to let me know.

I have no other device, so would be good to find resolution for iPad.

Anton

**Comment by Zanibas** [comment]
This is not possible right now. We only support desktop devices at the moment. We hope to reach mobile devices in the future, but we do not support iPad right now.
