### ISSUE TITLE
[Bug]: Security Alerts API - Banner loads indefinetly if the response to `https://security-alerts.api.cx.metamask.io/validate/0xaa36a7`is 500

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28257]
### Describe the bug

Whenever we are triggering a transaction/signature, if the response to the request `https://security-alerts.api.cx.metamask.io/validate/0xaa36a7` is 500, we do see an error in the background but the banner remains loading indefinetly

### Expected behavior

The banner should stop loading and display the Validation Failed message?

### Screenshots/Recordings

https://github.com/user-attachments/assets/3d4d5694-4ebb-4faf-ba4f-2f933a507867

### Steps to reproduce

1. Use a proxy to intercept requests like Burpsuite
2. Trigger a transaction/signature
3. Intercept the request to `https://security-alerts.api.cx.metamask.io/validate/0xaa36a7`
4. Return a 500 response
5. See error in the console but the Blockaid banner remains loading indefinetly

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by vinistevam** [comment]
fixed by https://github.com/MetaMask/metamask-extension/pull/28313
and cherry-picked to v12.7.0 https://github.com/MetaMask/metamask-extension/pull/28422
