### ISSUE TITLE
[Bug]: Delete Networks - When I delete Sepolia and re-add it again I get the error `No Infura network client was found with the ID "sepolia"`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28263]
### Describe the bug

When I delete Sepolia and re-add it again I get the error  `No Infura network client was found with the ID "sepolia"`.
The requests are working normally.

### Expected behavior

No error, like what's currently in prod

### Screenshots/Recordings

https://github.com/user-attachments/assets/2889042d-2cf1-4c2e-843a-4cde2902eee7

### Steps to reproduce

1. Remove Sepolia network
2. Add Sepolia network using Infura RPC
3. Switch to Sepolia
4. Click Activity tab
5. See UI console error

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by bergeron** [comment]
Check if this is same as https://github.com/MetaMask/metamask-extension/issues/28247

**Comment by seaona** [comment]
hi there @salimtb :wave:  I'm using the Sepolia production RPC URL (the same one as the default). I've reached out to you in slack
