### ISSUE TITLE
Pending transaction coinbase to metamask chrome extension 

### ISSUE THREAD

**Issue by burkecolby** [MetaMask/metamask-extension#2829]
Hi - I sent eth from coinbase to metamask chrome extension. Has been showing as pending for 65 minutes now. Any ideas what is happening?

BEFORE SUBMITTING, please make sure your question hasn't been answered in our support center: https://support.metamask.io
Common questions such as "Where is my ether?" or "Where did my tokens go?" are answered there.

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by frankiebee** [comment]
It's possible that your transaction just hasn't been mined yet or that coinbase is slow to update. I would recommend contacting coinbase support if it still hasn't gone through.

**Comment by frankiebee** [comment]
I'm going to close this as this is a question for coinbase but feel free to open it again if that case changes.

**Comment by burkecolby** [comment]
If using metamask. Should I have a private key and a code with random words? 
Can I access the private key again or should I create a new MEW?

What do you suggest?

**Comment by tmashuang** [comment]
@burkecolby That depends on if the account was created via MEW and imported as a 'Loose' account. If so, the private key will be the primary recovery.  Vaults created in MetaMask are provided a twelve word, mnemonic, seed phrase that can hold infinite number of key pairs.

**Comment by burkecolby** [comment]
Ok. I did metamask and I have the twelve word mnemonic. 

Just ensuring that is all I need. Thanks.

**Comment by tmashuang** [comment]
@burkecolby Also, wouldn't hurt to backup the private keys with the addresses that have ETH value in them.

**Comment by burkecolby** [comment]
Hi - I am trying to access my MetaMask via the chrome extension.  I’ve entered the seed phrase but not seeing that the extension has synced with the web to sync funds. Any suggestions on my best way forward? I have the seed phrase. 

Best,
Colby
