### ISSUE TITLE
Lost account 

### ISSUE THREAD

**Issue by Aman773** [MetaMask/metamask-extension#2830]
hey I usually use to just open chrome and click metamask and put in password to log in. But yesterday it was telling to create a new den. I created one but my old account didn’t appear. I have lost the private or seed phrase of my old account, is there a way I can get my old account back?

**Comment by frankiebee** [comment]
I'm sorry to hear this @Aman773 but unfortunately you can not recover your accounts with out your seed phrase.

**Comment by Aman773** [comment]
ty for reply but chrome inertnal storage could have my private keys?

**Comment by Aman773** [comment]
what if i get my chrome extensions background page and click application get metamask config vaults data is there any way with this method?

**Comment by frankiebee** [comment]
is their anything their?

**Comment by abemcdaniel45** [comment]
On Jan 3, 2018 10:22 AM, "Frankie" <notifications@github.com> wrote:

>

> is their anything their?
>
> —best new years ever
as the dust settles for the wheel to turn for the next rotation of
planetary bodies in cyclical fashion word soar without impedemence the
dance floor is shaking and shaking from so many people grooving in states
of ecstacy in a covered area sorounded by a jungle canopy
i float naked in natures womb with the super ninja bee woman who looks like
a pixie and dive deep in this soothing liquid i am breaking my cocoon like
a gecko hatching from an egg being a viscous soft adaptable being instead a
hard shelled creature stuck in a cave of repition
we nerd out about the science of bees on the beach and eat banana bread
filters are removed from awareness so anything can be said in healthy
communications we congregate in a bungalow she has rented with her friends
and we make our own fire works when eye contact is made when we part ways
the conch shell blows for dinner prepared by gourmet chefs i sit in the
silence of my solitude and savour this feast by randomness i find myself in
the garden temple at the end of a dirt road where lava flows on the dance
floor feeling the bliss of moving my body in rhythm with the music after
observing zodiac signs in the sky with a new friend
getting a ride back to town with one of the musicians talking in the back
seat with this beauty with nubian features about stars being born and dying
standinding on the side of the road hitchhiking at 2 in the morning being
amazed at what is
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/MetaMask/metamask-extension/issues/2830#issuecomment-355116712>,
or mute the thread

**Comment by abemcdaniel45** [comment]
can bathe in each others glow as we soak our bodies in hot springs and the
moon is larger than usual on the horizon we can put our foreheads together
so there is no filter between awarenesses which creates a blissful clarity
as we offer each other gifts of sensuality she has the sides of her head
shaved so she looks like a pigmy warrior her skin art is her war paint she
is developing her super powers in this jungle paradise

On Jan 3, 2018 10:22 AM, "Frankie" <notifications@github.com> wrote:

>

> is their anything their?
>
> —best new years ever
as the dust settles for the wheel to turn for the next rotation of
planetary bodies in cyclical fashion word soar without impedemence the
dance floor is shaking and shaking from so many people grooving in states
of ecstacy in a covered area sorounded by a jungle canopy
i float naked in natures womb with the super ninja bee woman who looks like
a pixie and dive deep in this soothing liquid i am breaking my cocoon like
a gecko hatching from an egg being a viscous soft adaptable being instead a
hard shelled creature stuck in a cave of repition
we nerd out about the science of bees on the beach and eat banana bread
filters are removed from awareness so anything can be said in healthy
communications we congregate in a bungalow she has rented with her friends
and we make our own fire works when eye contact is made when we part ways
the conch shell blows for dinner prepared by gourmet chefs i sit in the
silence of my solitude and savour this feast by randomness i find myself in
the garden temple at the end of a dirt road where lava flows on the dance
floor feeling the bliss of moving my body in rhythm with the music after
observing zodiac signs in the sky with a new friend
getting a ride back to town with one of the musicians talking in the back
seat with this beauty with nubian features about stars being born and dying
standinding on the side of the road hitchhiking at 2 in the morning being
amazed at what is
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/MetaMask/metamask-extension/issues/2830#issuecomment-355116712>,
or mute the thread

**Comment by martineezz** [comment]
@Aman773 If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
