### ISSUE TITLE
Missing link on pending transaction alert

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-extension#28308]
### What is this about?

`how to cancel or speed up a transaction` should be a hyperlink to: https://support.metamask.io/transactions-and-gas/transactions/how-to-speed-up-or-cancel-a-pending-transaction/

<img width="365" alt="Screenshot 2024-11-05 at 20 26 08" src="https://github.com/user-attachments/assets/772e1db1-fb58-4b90-a8cb-824a5ce396dc">

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Alexahalid** [comment]
@bschorchit You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
