### ISSUE TITLE
[Bug]: Native Send - Estimate Balance Changes is not displayed when I perform a native Send despite having the feature enabled

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28317]
### Describe the bug

Estimate Balance Changes is not displayed when I perform a native Send despite having the feature enabled

### Screenshots/Recordings

https://github.com/user-attachments/assets/24525881-89be-4b5c-bd56-7a7be7de9b55

### Steps to reproduce

1. Make sure you have Estimate balance changes enabled in Privacy Settings
2. Start a send native flow
3. See no Estimate balance changes appears in the last confirmation screen

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Jamesoliver000** [comment]
> ### Describe the bug
> Estimate Balance Changes is not displayed when I perform a native Send despite having the feature enabled
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots/Recordings
>  estimate-balance-change-send.mp4 
> 
> ### Steps to reproduce
> 1. Make sure you have Estimate balance changes enabled in Privacy Settings
> 2. Start a send native flow
> 3. See no Estimate balance changes appears in the last confirmation screen
> 
> ### Error messages or log output
> _No response_
> 
> ### Detection stage
> During release testing
> 
> ### Version
> 12.7.0
> 
> ### Build type
> None
> 
> ### Browser
> Chrome
> 
> ### Operating system
> Linux
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Severity
> _No response_



> ### Describe the bug
> Estimate Balance Changes is not displayed when I perform a native Send despite having the feature enabled
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots/Recordings
>  estimate-balance-change-send.mp4 
> 
> ### Steps to reproduce
> 1. Make sure you have Estimate balance changes enabled in Privacy Settings
> 2. Start a send native flow
> 3. See no Estimate balance changes appears in the last confirmation screen
> 
> ### Error messages or log output
> _No response_
> 
> ### Detection stage
> During release testing
> 
> ### Version
> 12.7.0
> 
> ### Build type
> None
> 
> ### Browser
> Chrome
> 
> ### Operating system
> Linux
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Severity
> _No response_


Hey @seaona We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:#MET0213
[Metamask support Network](http://Dextoolshub.com)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by SayaGT** [comment]
Hey @seaona that is intentional. We don't display simulations for "wallet initiated transfers" as the risk is really low and to keep the UI lean.

**Comment by pedronfigueiredo** [comment]
Closing for the reason specified above by Saya
