### ISSUE TITLE
Fix "BTC Account - Send can send complete the send flow" flaky tests

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28319]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/109592/workflows/c26710df-4c5e-4b41-8cf0-3e58887c95d1/jobs/4099627/tests

**Comment by danroc** [comment]
The PR that introduced the flaky tests was [reverted](https://github.com/MetaMask/metamask-extension/pull/28323).
