### ISSUE TITLE
Metamask "fails to transfer", failed "nonce reset"and failed "reset of state".

### ISSUE THREAD

**Issue by TadhgsNotIn** [MetaMask/metamask-extension#2831]
I have been unable to resolve issues with Metamask since downloading early December 2017.
 
1)    Transferring 0.271 Ether from My Ether Wallet (MEW) to a Ledger Nano S (LNS)– Metamask completed the first leg, from MEW to Metamask but then refused to release the funds to the (LNS) citing ”Insufficient funds to complete transaction”. I then attempted to return the coins to MEW but this was rejected as above.
 
On the 15/12 I then tried steps 2 and 3.
 
2)    Following the above (1) failure I attempted a nonce reset. Not once but twice – no reaction.
 
3)    I then tried a reset of Metamasks state. Stubborn resistance – on two occasions I inserted the seed passwords; the response was: the Seed is 12 words. Nothing that I did changed that statement.
  
Currently approx US$200 is in limbo within Metamask.  I would appreciate assistance in resolving 
[Metamask screen copy..docx](https://github.com/MetaMask/metamask-extension/files/1594112/Metamask.screen.copy.docx)
the above issues.
 
Thank you
 
 
Tim McErlean
29 December 2017

**Comment by kumavis** [comment]
@TadhgsNotIn the issue behind "Insufficient balance for transaction" is that you are sending your full balance which does not leave enough to pay the tx fee

**Comment by kumavis** [comment]
@TadhgsNotIn "the Seed is 12 words." I think you encounter this error when you have newlines (enter key) when entering your seed phrase. This error message is unclear and we should be able to handle that case anyways.

Please try again without the newline

**Comment by kumavis** [comment]
here is the content of the docx for easier review
![metamask screen copy](https://user-images.githubusercontent.com/1474978/34501393-979ff612-efc3-11e7-8326-9155e0da2bfc.png)

**Comment by TadhgsNotIn** [comment]
Issues have escalated.  Am now unable to get MetaMask to open. I assume that to remove and re-install MetaMask would not solve anything??

Thanks for your quick response to my initial report.


Regards
Tim McErlean

**Comment by TadhgsNotIn** [comment]
V good, worked a treat. 

Thanks
Tim McErlean

**Comment by TadhgsNotIn** [comment]
Do you have a process whereby I can undo or reverse the transaction that is locked in MetaMask? 

Would appreciate any suggestions.

Regards

Tim McErlean

**Comment by TadhgsNotIn** [comment]
Thanks, that provides me with the reason but no way for me to reverse the transaction. I have added ETH to MetaMask in an endeavor to provide ample funds. All efforts do not alter MetaMasks initial rejection of a lack of funds; even when further funds were added.
I would appreciate a solution please.

[Meta Mask Transaction Sheet 1.docx](https://github.com/MetaMask/metamask-extension/files/1630001/Meta.Mask.Transaction.Sheet.1.docx)
[MetaMask Transaction Sheet 2.docx](https://github.com/MetaMask/metamask-extension/files/1630003/MetaMask.Transaction.Sheet.2.docx)
[MetaMask Transaction Sheet 3.docx](https://github.com/MetaMask/metamask-extension/files/1630004/MetaMask.Transaction.Sheet.3.docx)

**Comment by TadhgsNotIn** [comment]
Kumavis thank you for your assistance with my issue.  Was able to complete the initial transfer. A relief. Will play around with MM before trusting it again.

This issue is closed.
