### ISSUE TITLE
[Bug]: Contract Interaction / Deployment - Metrics - When I have the redesign toggle disabled I still see contract interactions/deployments with redesigned_confirmation in Metrics Events

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28339]
### Describe the bug

When I have the redesign toggle disabled I still see contract interactions/deployments with `redesigned_confirmation in Metrics Events.

[Update]

- In current production 12.6.0, the issue is that we always see `ui_customizations` as `null` no matter if I have the Transactions Enabled or disabled (see picture)
- in 12.7.0, we always see `ui_customizations` as `redesigned_confirmation` no matter if I have the Transactions Enabled or disabled

### Expected behavior
12.6.0

![Screenshot from 2024-11-07 09-43-33](https://github.com/user-attachments/assets/22554d1f-da09-489b-82de-060565281b4c)

12.7.0

https://github.com/user-attachments/assets/1d9a3842-85d4-4284-9750-67fc600d2e7b

### Steps to reproduce

1. Enable Metrics
2. Disable Transactions Redesign from Settings
3. Trigger a Contract Deployment/ Contract Interaction
4. See metrics event with ui_customization: `redesigned_confirmation`

### Detection stage

In production (default) + RC (there is a different issue on each version, affecting this same metrics)

### Version

12.6.0 12.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by seaona** [comment]
Update:
- In current production 12.6.0, the issue is that we always see `ui_customizations` as `null` no matter if I have the Transactions Enabled or disabled (see picture)
- in 12.7.0, we always see `ui_customizations` as `redesigned_confirmation` no matter if I have the Transactions Enabled or disabled


![Screenshot from 2024-11-07 09-43-33](https://github.com/user-attachments/assets/1626d4db-729c-4fa9-8e1f-b66f2c5d258b)

**Comment by sleepytanya** [comment]
Related https://github.com/MetaMask/metamask-extension/issues/28322
