### ISSUE TITLE
Seed visible after password timeout

### ISSUE THREAD

**Issue by lasharor** [MetaMask/metamask-extension#2834]
1. Unlock wallet
2. Reveal seed words
3. Wait for password timeout, don't close seed word window
4. Seed words remain visible. Once you press "I've copied it somewhere safe" . MEW will actually go back to the password input screen.

I believe a time out should also be added to the seedwords. They shouldn't be visible when MEW asks for the password. 

Metamask 3.13.2; Chrome 63.0.3239.84; Mac OS 10.13.1

**Comment by kumavis** [comment]
I assume you meant MetaMask instead of MEW

**Comment by kumavis** [comment]
> 3. Wait for password timeout, don't close seed word window

im not sure what you mean here - afaik there is no timeout

@lasharor
