### ISSUE TITLE
[Bug]:  Privacy Mode (Balances) - When performing a Send flow with hidden balances, some values are hidden, but it shouldn't be (fees, amount and conversion) which can lead to funds loss

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28348]
### Describe the bug

Whenever I have privacy mode enabled, I see that if I start a Send flow, some values are hidden, but it seems it shouldn't be:
- amount conversion (in the first send screen)
- fees (in the last confirmation screen)
- amount (in the last confirmation screen)

### Expected behavior

I think that if we perform a Send with privacy mode enabled, we still want to see the amount we are sending as well as the fees?
Otherwise this has a risk of to funds loss

### Screenshots/Recordings

https://github.com/user-attachments/assets/76d9c7a0-c004-468f-94ec-3b9d693ab625

### Steps to reproduce

1. [Update] Disable Transactions Redesign from Experimental Settings -->this toggle needs to be OFF in order to reproduce the issue 
2. Enable Privacy mode by clicking the eye
3. Perform a Send flow
4. See amount, fees and conversion are hidden too

![Screenshot from 2024-11-07 15-23-57](https://github.com/user-attachments/assets/f5e5facb-bd91-4dc4-b73e-6e49883ea2e5)

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Annawoody** [comment]
When balances are hidden in Privacy Mode during a Send flow, it's crucial that all relevant values like fees, amount, and conversion are visible to avoid any potential loss of funds.I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
 @seaona

**Comment by darkwing** [comment]
Was fixed and cherry-picked by https://github.com/MetaMask/metamask-extension/pull/28372
