### ISSUE TITLE
[Bug]: Privacy Mode (Balances) - Native token Balance is not hidden while having privacy mode, if I go to the Native Assets page (ie ETH)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28347]
### Describe the bug

Whenever I have the privacy mode enabled, I see that the balance is not hidden in the native token page.
Ie if I click on ETH or Sepolia ETH, I can see my balance

### Screenshots/Recordings

https://github.com/user-attachments/assets/34d5bdfa-b854-4575-b71a-9f43711400f5

### Steps to reproduce

1. Click the eye for hiding the balance
2. Click on ETH or SepoliaETH asset
3. See how you can still see your balance

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by darkwing** [comment]
Should be fixed by https://github.com/MetaMask/metamask-extension/pull/28248

**Comment by alfeng6** [comment]
@seaona when testing, why did you expect that the token balance in the asset page would be hidden too? Given the setting is a local setting (only able to toggle in the main wallet view), originally the intention was to have the hidden values only occur in the main wallet view (main token list + account picker).

**Comment by seaona** [comment]
> @seaona when testing, why did you expect that the token balance in the asset page would be hidden too?

hi there @alfeng6 :wave: I expect it to be hidden because I see this behaviour in all the tokens, except the native token (ie ETH)

https://github.com/user-attachments/assets/a6a879c0-2310-4de9-b4f8-3359fbec2719

**Comment by alfeng6** [comment]
ah ok let me make sure the team knows not to hide the token values for any of the asset pages :) thank you for your QA!
