### ISSUE TITLE
[Bug]: Simulation metrics not captured in the wallet initiated Redesigned Confirmation Send Flow 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28369]
### Describe the bug

The properties `simulations_sending_assets_total_value`, `simulations_receiving_assets_total_value` and `transaction_contract_method` are intended to be present in both Anonymous and non-Anonymous events. However, these simulation metrics are not presented for wallet initiated redesigned send flow. 

### Expected behavior
For a given transaction, we should see the same simulations metrics when doing it with the improved transactions toggle on and when doing it with the  improved transactions toggle off.
Simulations metrics should be capture even when the simulation UI is not visible (only exception is if the user had disabled it themselves).

### Screenshots/Recordings

`Experimental` and `Developer` toggles are ON - simulations metrics are not present:

https://github.com/user-attachments/assets/c1d84e52-3046-4879-a68a-b0a65015bfc3

`Experimental` and `Developer` toggles are OFF - simulation metrics are in Anon- and non-Anon events:

https://github.com/user-attachments/assets/92a4e134-bf6f-48b6-9d8e-6119b55beb02

### Steps to reproduce

1. Send a transaction with simulation
2. Send a tx with  Redesign `Experimental` and `Developer` toggles ON
3. Observe `Transaction Approved` and `Transaction Approved Anon` events in the Segment
4. Repeat step 2 with toggles OFF
5. Repeat step 3

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by digiwand** [comment]
hello @sleepytanya! I think the bug is that the simulation is expected to work in the redesign as it is shown in the old confirmation pages using the same flow.

we can observe no "Estimated Changes" section in the redesign here: 
![Image](https://github.com/user-attachments/assets/6b624fbf-3473-42f2-91a0-cfda34145520)

For now, I will unassign myself and put this back into refine status to re-refine next week

**Comment by bschorchit** [comment]
@digiwand could we still capture the simulation data even if we don't display it to the user?

**Comment by digiwand** [comment]
hello @bschorchit 👋🏼 we could. What I would suggest or question is how we'd distinguish between no results returned vs. not showing the simulation. (I'm not exactly sure of the UI/UX behavior here as I'm writing this.)


Updating metrics to indicate whether the user has seen or has not seen the simulation rendered in the advanced view could be a different feature request

**Comment by bschorchit** [comment]
That's a good point. 

I think we could infer if the user has seen simulations or not from other properties like:
(1) the transaction type and referrer (these will tell us it's a send started within MM) and
(2)the advanced_view property (this will tell whether the user was seeing advanced view or not - this is not working on prod yet, but I believe it's on develop). 

With that we can build a dashboard or even custom property directly on Mixpanel to indicate to us whether the simulations UI was visible to users at transaction time.

**Comment by digiwand** [comment]
As discussed in an internal slack thread, we will capture simulation metrics even when no estimated changes are shown e.g. when we initiate send through the wallet. We will mirror the same metrics that we use when we display "Estimated Changes" "No changes..."
![CleanShot 2024-11-11 at 23 52 06@2x](https://github.com/user-attachments/assets/033f0926-c376-4c3f-9186-225b3ed64d3a)
