### ISSUE TITLE
Wrong private key game me access to an account on metamask

### ISSUE THREAD

**Issue by Gusmaster** [MetaMask/metamask-extension#2836]
I wanted to import an account on metamask and so it asked me for the private key, I entered and it gave me an address that had 0 in it (mine was supposed to not be on 0) so I checked the address and it was different. Then I clicked on the "Export private key" and it gave the key. I checked with the one that I have and I made a mistake when I entered it. Two of the digits on my account were "c0" and I entered them as "0c". 
Could it be that by making this simple mistake (of entering two digits backwards) I was able to get another account's private key correctly? What are the odds of that happening? Or is it a bug?

**Comment by kumavis** [comment]
Any hex of correct length should be a valid key and have an address associated with it

**Comment by kumavis** [comment]
In general, please never type an address or private key by hand, too risky to make a mistake
