### ISSUE TITLE
specify meaning of DEN somewhere

### ISSUE THREAD

**Issue by jordanglassman** [MetaMask/metamask-extension#2837]
Metamask uses the acronym "DEN" which I think means "HD wallet".  I've never seen it anywhere else, and I don't see it anywhere in the Metamask docs or support pages.

**Comment by Zanibas** [comment]
True: it's sort of a metaphor we tried developing in the past to help users understand the surface level concepts of ethereum wallet management. We'll clarify these metaphors or remove them in our new UI release.

**Comment by mecampbellsoup** [comment]
What does it actually stand for? Very curious; came here wondering the same thing.

**Comment by JACC35** [comment]
I'm wondering the same... I've been using Metamask for almost a year and I think I've been misunderstanding all along.  I've always just signed in with my password and was able to access my wallet and tokens; however yesterday the plugin was still there but it didn't allow me to enter my password, it's now asking me to create a new DEN and new passwords, which I don't want to yet in case I then wipe out my needed Metamask access unknowingly.  Unfortunately, I cannot locate my seed words but found a saved document from a year ago that says "you created an Ethereum account" along with the private key.  This account number does not match the wallet address I've been using and seeing all along when I've created transactions during this past year, which reminded me that address is my public one.  How can I restore my wallet using that information and gain access again to all my tokens associated with that public address?  Basically I'm wondering if that account number and private key will give me access to the wallet address again that has all my tokens?  I know, it's awful I can't find my seed words but it is what it is and now I'm freaking out.  Lesson learned for the future but I have to get access to my tokens!!  Can anyone advise?

**Comment by JACC35** [comment]
And I have no idea why Metamask plugin "lost" my regular sign in and is now only giving me the option of creating a new one. I didn't have a crash or anything...??

**Comment by artiya4u** [comment]
According to UI tooltip **"Your DEN is your password-encrypted storage within MetaMask."**

**Comment by bolelang** [comment]
Is it possible to have access to the same account from Chrome browsers in different machines? When I installed the MetaMask Chrome extension on an additional laptop, it never gave me the opportunity to log in. It went through the process of showing me the conditions to accept. It then offered me the option to create or to import existing DEN. 

What worried me about importing the existing DEN, is that in addition to the Wallet Seed it also asked for a new password. What happens when I use the existing password? After this process will I be able to use both laptops browsers to access the same wallet?

**Comment by jackkinsella** [comment]
Bit of feedback - I got a shock when MetaMask asked me for a 'DEN' password - I thought I was being forced to swallow yet another new standard.

At least from my perspective, I would call a 'password' a 'password' and confine the den metaphor, (which is cute and cool BTW!!), to the naming of the storage area.

**Comment by lazaridiscom** [comment]
related: #3720

@bolelang 
> After this process will I be able to use both laptops browsers to access the same wallet?
yes, your wallets are essentially stored on the Ethereum network, and will be accessible from both laptop-browsers.

@jackkinsella 
> it just worked, which is basically a miracle in the blockchain world
Nah, many things  work out-of-the box... not just MetaMask!

**Comment by bdresser** [comment]
the "DEN" metaphor will be phased out as we move users towards the new UI. thanks for the feedback all!
