### ISSUE TITLE
[Bug]: Wallet and dApp initiated Send NFT confirmations

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28370]
### Describe the bug

There are discrepancies between some of the `Send NFT` confirmation screens and their corresponding Figma designs.

Related:
https://github.com/MetaMask/MetaMask-planning/issues/3018
https://github.com/MetaMask/MetaMask-planning/issues/3019

### Expected behavior

-

### Screenshots/Recordings

<img width="1301" alt="Screenshot 2024-11-07 at 17 38 31" src="https://github.com/user-attachments/assets/50763784-fe9f-44c1-b3e7-1d8ec3e3b1cd">

<img width="1418" alt="Screenshot 2024-11-07 at 17 39 06" src="https://github.com/user-attachments/assets/07676aec-d9d0-449b-ad04-0e0fd8086f27">

<img width="1347" alt="Screenshot 2024-11-07 at 17 39 43" src="https://github.com/user-attachments/assets/48f574c0-e59f-41b0-aab3-5fad731c6e73">

<img width="1679" alt="Screenshot 2024-11-07 at 17 37 51" src="https://github.com/user-attachments/assets/28f6e481-cd15-443e-aeb5-350ce16d1eac">

<img width="660" alt="Screenshot 2024-11-07 at 17 41 09" src="https://github.com/user-attachments/assets/5296eb02-7c2f-46ce-b3df-2cb497eac915">

### Steps to reproduce

1. Enable Confirmations redesign
2. Transfer NFT

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by SayaGT** [comment]
[Here is the design QA](https://www.figma.com/design/H52Ob2wDWsPY4g9DeYuCLk/Confirmation-redesign-V6?node-id=4081-26202&t=vIpDMn8DLbEC5KXm-1)
