### ISSUE TITLE
Lost ETH

### ISSUE THREAD

**Issue by vemuriraja** [MetaMask/metamask-extension#2841]
I did a transaction which appears to be failed. But the money hasn´t come back to the account. And if I look on
http://etherscan.io/tx/0x1edd2b0e4fd1964714e504663ec99a66dc792882abaf071d420c52f0672ea9b0

I can´t find the transaction.

What can I do?

Thanks!

**Comment by vemuriraja** [comment]
Attaching the log



{
  "metamask": {
    "isInitialized": true,
    "isUnlocked": true,
    "isMascara": false,
    "rpcTarget": "https://rawtestrpc.metamask.io/",
    "identities": {
      "0xe29552697faef8203aa6dfd1006e075abe282991": {
        "address": "0xe29552697faef8203aa6dfd1006e075abe282991",
        "name": "ICO Account"
      }
    },
    "unapprovedTxs": {},
    "noActiveNotices": true,
    "frequentRpcList": [],
    "addressBook": [
      {
        "address": "0x26e7686d135ed44dd15cc4ed9eff77f67c1de1ee",
        "name": " "
      }
    ],
    "tokenExchangeRates": {},
    "coinOptions": {},
    "provider": {
      "type": "mainnet",
      "rpcTarget": "https://mainnet.infura.io/metamask"
    },
    "network": "1",
    "accounts": {
      "0xe29552697faef8203aa6dfd1006e075abe282991": {
        "code": "0x",
        "balance": "0x1fcf476f99ac00",
        "nonce": "0x4",
        "address": "0xe29552697faef8203aa6dfd1006e075abe282991"
      }
    },
    "currentBlockGasLimit": "0x7a121d",
    "selectedAddressTxList": [
      {
        "id": 868159933241010,
        "time": 1514950154676,
        "status": "rejected",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
          "to": "0x26e7686d135ed44dd15cc4ed9eff77f67c1de1ee",
          "value": "0xdbd2fc137a30000",
          "gasPrice": "0x55ae82600",
          "gas": "0xc544",
          "nonce": "0x3",
          "chainId": "0x1"
        },
        "gasPriceSpecified": false,
        "nonceSpecified": false,
        "gasLimitSpecified": false,
        "estimatedGas": "5208",
        "history": [
          {
            "id": 868159933241010,
            "time": 1514950154676,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
              "to": "0x26e7686d135ed44dd15cc4ed9eff77f67c1de1ee",
              "value": "0xdbd2fc137a30000",
              "gasPrice": "0x4a817c800",
              "gas": "0x7b0c"
            },
            "gasPriceSpecified": false,
            "nonceSpecified": false,
            "gasLimitSpecified": false,
            "estimatedGas": "5208"
          },
          [],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "approved",
              "note": "txStateManager: setting status to approved"
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/nonce",
              "value": "0x3",
              "note": "transactions#approveTransaction"
            },
            {
              "op": "add",
              "path": "/nonceDetails",
              "value": {
                "params": {
                  "highestLocalNonce": 3,
                  "highestSuggested": 3,
                  "nextNetworkNonce": 3
                },
                "local": {
                  "name": "local",
                  "nonce": 3,
                  "details": {
                    "startPoint": 3,
                    "highest": 3
                  }
                },
                "network": {
                  "name": "network",
                  "nonce": 3,
                  "details": {
                    "baseCount": 3
                  }
                }
              }
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/chainId",
              "value": "0x1",
              "note": "txStateManager: setting status to signed"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "signed"
            }
          ],
          [
            {
              "op": "add",
              "path": "/rawTx",
              "value": "0xf86c038504a817c800827b0c9426e7686d135ed44dd15cc4ed9eff77f67c1de1ee880dbd2fc137a300008026a07d8aea4d0b1891c0aeb66b80610c7dfed49f6ada215c5525832e0871f05510b2a0090b3f4e8b953e7da9fb6026253346ce1065337252c9745376b723a86c7da188",
              "note": "transactions#publishTransaction"
            }
          ],
          [
            {
              "op": "add",
              "path": "/hash",
              "value": "0xd618ad5a5bfe1a01e8932a7f64d3f3c43ddec990586ef0366d5428b774d0f863",
              "note": "transactions#setTxHash"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "submitted",
              "note": "txStateManager: setting status to submitted"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "unapproved",
              "note": "txStateManager: setting status to unapproved"
            }
          ],
          [
            {
              "op": "add",
              "path": "/lastGasPrice",
              "value": "0x4a817c800",
              "note": "retryTransaction: manual retry"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/txParams/gas",
              "value": "0xc544",
              "note": "confTx: user approved transaction"
            },
            {
              "op": "replace",
              "path": "/txParams/gasPrice",
              "value": "0x55ae82600"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "approved",
              "note": "txStateManager: setting status to approved"
            }
          ],
          [],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "signed",
              "note": "txStateManager: setting status to signed"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/rawTx",
              "value": "0xf86c0385055ae8260082c5449426e7686d135ed44dd15cc4ed9eff77f67c1de1ee880dbd2fc137a300008025a0c5349611877b5fd1d6cee469e8a593bcb4773ee8dc27d26cde171a24b6b56699a03c5b756c8f2f214741b56b3c7272fae9b5d8f150e691d80b721253847b3d2fd6",
              "note": "transactions#publishTransaction"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/hash",
              "value": "0x1edd2b0e4fd1964714e504663ec99a66dc792882abaf071d420c52f0672ea9b0",
              "note": "transactions#setTxHash"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "submitted",
              "note": "txStateManager: setting status to submitted"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "unapproved",
              "note": "txStateManager: setting status to unapproved"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/lastGasPrice",
              "value": "0x55ae82600",
              "note": "retryTransaction: manual retry"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "rejected",
              "note": "txStateManager: setting status to rejected"
            }
          ]
        ],
        "nonceDetails": {
          "params": {
            "highestLocalNonce": 3,
            "highestSuggested": 3,
            "nextNetworkNonce": 3
          },
          "local": {
            "name": "local",
            "nonce": 3,
            "details": {
              "startPoint": 3,
              "highest": 3
            }
          },
          "network": {
            "name": "network",
            "nonce": 3,
            "details": {
              "baseCount": 3
            }
          }
        },
        "rawTx": "0xf86c0385055ae8260082c5449426e7686d135ed44dd15cc4ed9eff77f67c1de1ee880dbd2fc137a300008025a0c5349611877b5fd1d6cee469e8a593bcb4773ee8dc27d26cde171a24b6b56699a03c5b756c8f2f214741b56b3c7272fae9b5d8f150e691d80b721253847b3d2fd6",
        "hash": "0x1edd2b0e4fd1964714e504663ec99a66dc792882abaf071d420c52f0672ea9b0",
        "lastGasPrice": "0x55ae82600"
      },
      {
        "id": 7294226079289933,
        "time": 1514866704521,
        "status": "rejected",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
          "to": "0xce53a179047ebed80261689367c093c90a94cc08",
          "value": "0x6f05b59d3b20000",
          "gasPrice": "0x4a817c800",
          "gas": "0x1ebe5"
        },
        "gasPriceSpecified": false,
        "nonceSpecified": false,
        "gasLimitSpecified": false,
        "estimatedGas": "147ee",
        "history": [
          {
            "id": 7294226079289933,
            "time": 1514866704521,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
              "to": "0xce53a179047ebed80261689367c093c90a94cc08",
              "value": "0x6f05b59d3b20000",
              "gasPrice": "0x4a817c800",
              "gas": "0x1ebe5"
            },
            "gasPriceSpecified": false,
            "nonceSpecified": false,
            "gasLimitSpecified": false,
            "estimatedGas": "147ee"
          },
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "rejected",
              "note": "txStateManager: setting status to rejected"
            }
          ]
        ]
      },
      {
        "id": 8110151584150284,
        "time": 1514775091957,
        "status": "rejected",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
          "to": "0x10a76ca1f5b0e0334910fb3c8581ab91cf93b814",
          "value": "0xc7d713b49da0000",
          "gasPrice": "0x4e3b29200",
          "gas": "0x7b0c"
        },
        "gasPriceSpecified": false,
        "nonceSpecified": false,
        "gasLimitSpecified": false,
        "estimatedGas": "5208",
        "history": [
          {
            "id": 8110151584150284,
            "time": 1514775091957,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
              "to": "0x10a76ca1f5b0e0334910fb3c8581ab91cf93b814",
              "value": "0xc7d713b49da0000",
              "gasPrice": "0x4e3b29200",
              "gas": "0x7b0c"
            },
            "gasPriceSpecified": false,
            "nonceSpecified": false,
            "gasLimitSpecified": false,
            "estimatedGas": "5208"
          },
          [
            {
              "op": "remove",
              "path": "/estimatedGas/red",
              "note": "txStateManager: setting status to rejected"
            },
            {
              "op": "replace",
              "path": "/estimatedGas/length",
              "value": 4
            },
            {
              "op": "remove",
              "path": "/estimatedGas/words"
            },
            {
              "op": "remove",
              "path": "/estimatedGas/negative"
            },
            {
              "op": "add",
              "path": "/estimatedGas/0",
              "value": "5"
            },
            {
              "op": "add",
              "path": "/estimatedGas/1",
              "value": "2"
            },
            {
              "op": "add",
              "path": "/estimatedGas/2",
              "value": "0"
            },
            {
              "op": "add",
              "path": "/estimatedGas/3",
              "value": "8"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "rejected"
            }
          ]
        ]
      },
      {
        "id": 8110151584150283,
        "time": 1514775049804,
        "status": "rejected",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
          "to": "0x10a76ca1f5b0e0334910fb3c8581ab91cf93b814",
          "value": "0xdde7c72d71dd000",
          "gasPrice": "0x4e3b29200",
          "gas": "0x7b0c"
        },
        "gasPriceSpecified": false,
        "nonceSpecified": false,
        "gasLimitSpecified": false,
        "estimatedGas": "5208",
        "history": [
          {
            "id": 8110151584150283,
            "time": 1514775049804,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
              "to": "0x10a76ca1f5b0e0334910fb3c8581ab91cf93b814",
              "value": "0xdde7c72d71dd000",
              "gasPrice": "0x4e3b29200",
              "gas": "0x7b0c"
            },
            "gasPriceSpecified": false,
            "nonceSpecified": false,
            "gasLimitSpecified": false,
            "estimatedGas": "5208"
          },
          [
            {
              "op": "remove",
              "path": "/estimatedGas/red",
              "note": "txStateManager: setting status to rejected"
            },
            {
              "op": "replace",
              "path": "/estimatedGas/length",
              "value": 4
            },
            {
              "op": "remove",
              "path": "/estimatedGas/words"
            },
            {
              "op": "remove",
              "path": "/estimatedGas/negative"
            },
            {
              "op": "add",
              "path": "/estimatedGas/0",
              "value": "5"
            },
            {
              "op": "add",
              "path": "/estimatedGas/1",
              "value": "2"
            },
            {
              "op": "add",
              "path": "/estimatedGas/2",
              "value": "0"
            },
            {
              "op": "add",
              "path": "/estimatedGas/3",
              "value": "8"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "rejected"
            }
          ]
        ]
      },
      {
        "id": 3212078799923922,
        "time": 1514655272115,
        "status": "confirmed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
          "to": "0x354bf2c763e09006cbc5fd8e2420e78a0684dbce",
          "value": "0xec7a3db7dca8000",
          "gasPrice": "0x4a817c800",
          "gas": "0x100bd",
          "nonce": "0x2",
          "chainId": "0x1"
        },
        "gasPriceSpecified": false,
        "nonceSpecified": false,
        "gasLimitSpecified": false,
        "estimatedGas": "ab29",
        "history": [
          {
            "id": 3212078799923922,
            "time": 1514655272115,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
              "to": "0x354bf2c763e09006cbc5fd8e2420e78a0684dbce",
              "value": "0xec7a3db7dca8000",
              "gasPrice": "0x4a817c800",
              "gas": "0x100bd"
            },
            "gasPriceSpecified": false,
            "nonceSpecified": false,
            "gasLimitSpecified": false,
            "estimatedGas": "ab29"
          },
          [],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "approved",
              "note": "txStateManager: setting status to approved"
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/nonce",
              "value": "0x2",
              "note": "transactions#approveTransaction"
            },
            {
              "op": "add",
              "path": "/nonceDetails",
              "value": {
                "params": {
                  "highestLocalNonce": 2,
                  "highestSuggested": 2,
                  "nextNetworkNonce": 2
                },
                "local": {
                  "name": "local",
                  "nonce": 2,
                  "details": {
                    "startPoint": 2,
                    "highest": 2
                  }
                },
                "network": {
                  "name": "network",
                  "nonce": 2,
                  "details": {
                    "baseCount": 2
                  }
                }
              }
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/chainId",
              "value": "0x1",
              "note": "txStateManager: setting status to signed"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "signed"
            }
          ],
          [
            {
              "op": "add",
              "path": "/rawTx",
              "value": "0xf86d028504a817c800830100bd94354bf2c763e09006cbc5fd8e2420e78a0684dbce880ec7a3db7dca80008025a02a825f96cd3320be9cafafbfea5b8791a3648a3dcb9c1e0131202dbe4e7eeff4a005ccd06e7914bc76370bea3cb72753be190b46a61dbcee0585a81d781e417a77",
              "note": "transactions#publishTransaction"
            }
          ],
          [
            {
              "op": "add",
              "path": "/hash",
              "value": "0x53950f5385e033d9c0a1f074d2596d0eb0fbc954263bf738dd20bfeca92d068e",
              "note": "transactions#setTxHash"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "submitted",
              "note": "txStateManager: setting status to submitted"
            }
          ],
          [
            {
              "op": "add",
              "path": "/firstRetryBlockNumber",
              "value": "0x49a06b",
              "note": "transactions/pending-tx-tracker#event: tx:block-update"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "confirmed",
              "note": "txStateManager: setting status to confirmed"
            }
          ]
        ],
        "nonceDetails": {
          "params": {
            "highestLocalNonce": 2,
            "highestSuggested": 2,
            "nextNetworkNonce": 2
          },
          "local": {
            "name": "local",
            "nonce": 2,
            "details": {
              "startPoint": 2,
              "highest": 2
            }
          },
          "network": {
            "name": "network",
            "nonce": 2,
            "details": {
              "baseCount": 2
            }
          }
        },
        "rawTx": "0xf86d028504a817c800830100bd94354bf2c763e09006cbc5fd8e2420e78a0684dbce880ec7a3db7dca80008025a02a825f96cd3320be9cafafbfea5b8791a3648a3dcb9c1e0131202dbe4e7eeff4a005ccd06e7914bc76370bea3cb72753be190b46a61dbcee0585a81d781e417a77",
        "hash": "0x53950f5385e033d9c0a1f074d2596d0eb0fbc954263bf738dd20bfeca92d068e",
        "firstRetryBlockNumber": "0x49a06b"
      },
      {
        "id": 3212078799923921,
        "time": 1514650470026,
        "status": "confirmed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
          "to": "0x5401bb4729bd7f025b97399c3c92854ec299f81a",
          "value": "0x18fae27693b40000",
          "gasPrice": "0x4a817c800",
          "gas": "0x244d4",
          "nonce": "0x1",
          "chainId": "0x1"
        },
        "gasPriceSpecified": false,
        "nonceSpecified": false,
        "gasLimitSpecified": false,
        "estimatedGas": "19d43",
        "history": [
          {
            "id": 3212078799923921,
            "time": 1514650470026,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
              "to": "0x5401bb4729bd7f025b97399c3c92854ec299f81a",
              "value": "0x18fae27693b40000",
              "gasPrice": "0x4a817c800",
              "gas": "0x26be4"
            },
            "gasPriceSpecified": false,
            "nonceSpecified": false,
            "gasLimitSpecified": false,
            "estimatedGas": "19d43"
          },
          [
            {
              "op": "replace",
              "path": "/txParams/gas",
              "value": "0x244d4",
              "note": "confTx: user approved transaction"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "approved",
              "note": "txStateManager: setting status to approved"
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/nonce",
              "value": "0x1",
              "note": "transactions#approveTransaction"
            },
            {
              "op": "add",
              "path": "/nonceDetails",
              "value": {
                "params": {
                  "highestLocalNonce": 1,
                  "highestSuggested": 1,
                  "nextNetworkNonce": 1
                },
                "local": {
                  "name": "local",
                  "nonce": 1,
                  "details": {
                    "startPoint": 1,
                    "highest": 1
                  }
                },
                "network": {
                  "name": "network",
                  "nonce": 1,
                  "details": {
                    "baseCount": 1
                  }
                }
              }
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/chainId",
              "value": "0x1",
              "note": "txStateManager: setting status to signed"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "signed"
            }
          ],
          [
            {
              "op": "add",
              "path": "/rawTx",
              "value": "0xf86d018504a817c800830244d4945401bb4729bd7f025b97399c3c92854ec299f81a8818fae27693b400008026a0d7f7a56a4dc641514d30c405334869c25122a8bd3f397e8fa63a64fab032bfcea0186a666096a83c827e3ccc01f69c45251582e32f70088da155cc351f5e26f804",
              "note": "transactions#publishTransaction"
            }
          ],
          [
            {
              "op": "add",
              "path": "/hash",
              "value": "0x520a9df28fa12c5f9eac48993a54fa1f3e01d74a6c31f3db4dc1e66734dad4cc",
              "note": "transactions#setTxHash"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "submitted",
              "note": "txStateManager: setting status to submitted"
            }
          ],
          [
            {
              "op": "add",
              "path": "/firstRetryBlockNumber",
              "value": "0x499f2c",
              "note": "transactions/pending-tx-tracker#event: tx:block-update"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "confirmed",
              "note": "txStateManager: setting status to confirmed"
            }
          ]
        ],
        "nonceDetails": {
          "params": {
            "highestLocalNonce": 1,
            "highestSuggested": 1,
            "nextNetworkNonce": 1
          },
          "local": {
            "name": "local",
            "nonce": 1,
            "details": {
              "startPoint": 1,
              "highest": 1
            }
          },
          "network": {
            "name": "network",
            "nonce": 1,
            "details": {
              "baseCount": 1
            }
          }
        },
        "rawTx": "0xf86d018504a817c800830244d4945401bb4729bd7f025b97399c3c92854ec299f81a8818fae27693b400008026a0d7f7a56a4dc641514d30c405334869c25122a8bd3f397e8fa63a64fab032bfcea0186a666096a83c827e3ccc01f69c45251582e32f70088da155cc351f5e26f804",
        "hash": "0x520a9df28fa12c5f9eac48993a54fa1f3e01d74a6c31f3db4dc1e66734dad4cc",
        "firstRetryBlockNumber": "0x499f2c"
      },
      {
        "id": 3212078799923920,
        "time": 1514648577442,
        "status": "confirmed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
          "to": "0xb547cc51ce58293e6945ba08d664ce051563d9ac",
          "value": "0x29a2241af62c0000",
          "gasPrice": "0x4a817c800",
          "gas": "0x2dc27",
          "nonce": "0x0",
          "chainId": "0x1"
        },
        "gasPriceSpecified": false,
        "nonceSpecified": false,
        "gasLimitSpecified": false,
        "estimatedGas": "1e81a",
        "history": [
          {
            "id": 3212078799923920,
            "time": 1514648577442,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0xe29552697faef8203aa6dfd1006e075abe282991",
              "to": "0xb547cc51ce58293e6945ba08d664ce051563d9ac",
              "value": "0x29a2241af62c0000",
              "gasPrice": "0x4a817c800",
              "gas": "0x2dc27"
            },
            "gasPriceSpecified": false,
            "nonceSpecified": false,
            "gasLimitSpecified": false,
            "estimatedGas": "1e81a"
          },
          [],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "approved",
              "note": "txStateManager: setting status to approved"
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/nonce",
              "value": "0x0",
              "note": "transactions#approveTransaction"
            },
            {
              "op": "add",
              "path": "/nonceDetails",
              "value": {
                "params": {
                  "highestLocalNonce": 0,
                  "highestSuggested": 0,
                  "nextNetworkNonce": 0
                },
                "local": {
                  "name": "local",
                  "nonce": 0,
                  "details": {
                    "startPoint": 0,
                    "highest": 0
                  }
                },
                "network": {
                  "name": "network",
                  "nonce": 0,
                  "details": {
                    "baseCount": 0
                  }
                }
              }
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/chainId",
              "value": "0x1",
              "note": "txStateManager: setting status to signed"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "signed"
            }
          ],
          [
            {
              "op": "add",
              "path": "/rawTx",
              "value": "0xf86d808504a817c8008302dc2794b547cc51ce58293e6945ba08d664ce051563d9ac8829a2241af62c00008026a078558c7981bacab695b5e1587fc4ab316be3318a3f908315406a331c8c463653a00ee043e64cc4da052754d9fa5e62d582a0cc20433e07bafe2c16b706f2db88ae",
              "note": "transactions#publishTransaction"
            }
          ],
          [
            {
              "op": "add",
              "path": "/hash",
              "value": "0x18e4299d619be1a5a870af8c8fe4e0cc3b876efa54132b087f65152569361c93",
              "note": "transactions#setTxHash"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "submitted",
              "note": "txStateManager: setting status to submitted"
            }
          ],
          [
            {
              "op": "add",
              "path": "/firstRetryBlockNumber",
              "value": "0x499ebc",
              "note": "transactions/pending-tx-tracker#event: tx:block-update"
            }
          ],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "confirmed",
              "note": "txStateManager: setting status to confirmed"
            }
          ]
        ],
        "nonceDetails": {
          "params": {
            "highestLocalNonce": 0,
            "highestSuggested": 0,
            "nextNetworkNonce": 0
          },
          "local": {
            "name": "local",
            "nonce": 0,
            "details": {
              "startPoint": 0,
              "highest": 0
            }
          },
          "network": {
            "name": "network",
            "nonce": 0,
            "details": {
              "baseCount": 0
            }
          }
        },
        "rawTx": "0xf86d808504a817c8008302dc2794b547cc51ce58293e6945ba08d664ce051563d9ac8829a2241af62c00008026a078558c7981bacab695b5e1587fc4ab316be3318a3f908315406a331c8c463653a00ee043e64cc4da052754d9fa5e62d582a0cc20433e07bafe2c16b706f2db88ae",
        "hash": "0x18e4299d619be1a5a870af8c8fe4e0cc3b876efa54132b087f65152569361c93",
        "firstRetryBlockNumber": "0x499ebc"
      }
    ],
    "unapprovedMsgs": {},
    "unapprovedMsgCount": 0,
    "unapprovedPersonalMsgs": {},
    "unapprovedPersonalMsgCount": 0,
    "unapprovedTypedMessages": {},
    "unapprovedTypedMessagesCount": 0,
    "keyringTypes": [
      "Simple Key Pair",
      "HD Key Tree"
    ],
    "keyrings": [
      {
        "type": "HD Key Tree",
        "accounts": [
          "0xe29552697faef8203aa6dfd1006e075abe282991"
        ]
      }
    ],
    "computedBalances": {},
    "currentAccountTab": "history",
    "tokens": [
      {
        "address": "0xb547cc51ce58293e6945ba08d664ce051563d9ac",
        "symbol": "BLT",
        "decimals": "18"
      },
      {
        "address": "0x5401bb4729bd7f025b97399c3c92854ec299f81a",
        "symbol": "LOCI",
        "decimals": "18"
      },
      {
        "address": "0x107c4504cd79c5d2696ea0030a8dd4e92601b82e",
        "symbol": "BLT",
        "decimals": "18"
      },
      {
        "address": "0x354bf2c763e09006cbc5fd8e2420e78a0684dbce",
        "symbol": "loci",
        "decimals": "18"
      },
      {
        "address": "0x9c23d67aea7b95d80942e3836bcdf7e708a747c2",
        "symbol": "LOCI",
        "decimals": "18"
      }
    ],
    "selectedAddress": "0xe29552697faef8203aa6dfd1006e075abe282991",
    "currentCurrency": "usd",
    "conversionRate": 861.02,
    "conversionDate": 1514953704,
    "infuraNetworkStatus": {
      "mainnet": "ok",
      "ropsten": "ok",
      "kovan": "ok",
      "rinkeby": "ok"
    },
    "shapeShiftTxList": [],
    "lostAccounts": []
  },
  "appState": {
    "shouldClose": false,
    "menuOpen": false,
    "currentView": {
      "name": "config",
      "context": "0xe29552697faef8203aa6dfd1006e075abe282991"
    },
    "accountDetail": {
      "subview": "transactions"
    },
    "transForward": true,
    "isLoading": false,
    "warning": null
  },
  "identities": {},
  "version": "3.13.2",
  "platform": {
    "arch": "x86-64",
    "nacl_arch": "x86-64",
    "os": "win"
  },
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
}

**Comment by Zanibas** [comment]
It looks like the transaction went through and you weren't able to change the transaction details in time. Sorry to hear, but those funds won't be able to come back unless you're able to contact the person who controls the other address.

https://etherscan.io/tx/0xd618ad5a5bfe1a01e8932a7f64d3f3c43ddec990586ef0366d5428b774d0f863
