### ISSUE TITLE
[Bug]: When adding the Polygon network via MetaMask Portfolio, the token is identified as MATIC rather than POL, leading to an "Unexpected Native Token Symbol" warning instead of displaying the asset balance

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28417]
### Describe the bug

When adding the Polygon network via MetaMask Portfolio, the RPC URL utilized is polygon-rpc.com. As a result, the token is identified as MATIC rather than POL, leading to an "Unexpected Native Token Symbol" warning instead of displaying the asset balance. Attempting to resolve this by adding an alternative RPC, such as llama.rpc.com, does not address the issue. To resolve this, the Polygon network must be removed and then re-added using the MetaMask networks modal / dApps / etc.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/0d2cb6c4-1fa4-45e9-b95d-a8ba2f1a5018

<img width="364" alt="Screenshot 2024-11-12 at 00 25 51" src="https://github.com/user-attachments/assets/e64437ee-592c-4991-b59b-6728d7008942">

<img width="688" alt="Screenshot 2024-11-12 at 00 25 05" src="https://github.com/user-attachments/assets/8e42f4dd-9c38-477e-8c76-4368b4dc2a59">

### Steps to reproduce

1. Go to Portfolio
2. Add Polygon network

### Detection stage

During release testing

### Version

12.7.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by jclancy93** [comment]
This should have been solved by Portfolio PR linked above
