### ISSUE TITLE
Metamask reloads all tabs when switching network which makes chrome crashes.

### ISSUE THREAD

**Issue by bneiluj** [MetaMask/metamask-extension#2842]
*  Expected Behavior
As a user of chrome
When I switch Metamask network 
It should not refresh all opened Chrome tabs 

  *  Actual Behavior
As a user of Chrome 
When I switch Metamask network (ie: from mainnet to kovan for example) 
It reloads all opened tabs
Which crashes the machine because of consuming too much CPU and memory. 

Not sure if it's possible to resolve this issue based on the security aspect of having multiple tabs and sharing sessionStorage / cookie session. 

  *  Browser Used
3.13.2 

  *  Operating System Used
Chrome: Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by tmashuang** [comment]
If the tabs are using the MetaMask provider, changing the provider will refresh the tabs. For instance MetaMask should not refresh pages like Google or Youtube. If this is not the case will reopen.

**Comment by Gizzbert** [comment]
this issue is back, I am using v8.08
