### ISSUE TITLE
metamask seed recvoery

### ISSUE THREAD

**Issue by JALEELKHAN0** [MetaMask/metamask-extension#2843]

**Comment by JALEELKHAN0** [comment]
MY mistake i format my harddrive and later I realize i didnt back up my metamask seed now i can only few my transaction cant dot anything . can someone help me to recover my seed from metamask

I try to use recover disk to recover my files but i dont konw where chrome same meta mask seed 

thanks

**Comment by Zanibas** [comment]
There is no way for us to recover your seed--there is no centralized service that backs up your seed words. Sorry to hear, but there is 0 ability for us from a technical perspective to help you out.

**Comment by JALEELKHAN0** [comment]
Ii used disk recovery . I saved my file somewhere . Is there any way they keep the backup file one chrome extension or any file type so I can recover . 

Please help me on that thanks
