### ISSUE TITLE
Metamask just reset itself.

### ISSUE THREAD

**Issue by Vox-draconis** [MetaMask/metamask-extension#28440]
### What is this about?

I see lots here having the issue where MM just decides to lose all info. I've been using the POS thing for years now, suddenly I have to import my PKey or seed phrase again. I just made this post to say...
F*CK YOU, for not just the issue, but all the BULLSH!T excuses you're making to your users posting here - time to change to another wallet, MM is just pulling a Firefox, where it's now a fat, bloated, slow POS that's trying to do everything and doesn't care about quality of life, nor a VERY CONCERNING issue.
If I wasn't quite clear before, or you missed it... F*CK YOU.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by danjm** [comment]
Sorry for your experience. Feel free to share any other technical details of the bug you experienced. Which browser were you using? When you opened MetaMask and you were required to enter your seed phrase or private key, which screen did you first see? When did you last use metamask before this occured?

Closing the issue for now, but feel free to comment further if you wish to share more technical details
