### ISSUE TITLE
Error: [ethjs-query] while formatting inputs

### ISSUE THREAD

**Issue by elliotthill** [MetaMask/metamask-extension#2846]
Calling function 'create' 
`myethobj.create("0x2ce13d8dd1b248286575591b695805327cf7d9ba", "hello");
`
Gives me an error:

`Error: [ethjs-query] while formatting inputs '[{"to":"0x208A8B1A0318E5ed3E1bd3412B5d2E7eE688fac0","data":"0xa15ab08d0000000000000000000000002ce13d8dd1b248286575591b695805327cf7d9ba0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000"}]' for method 'sendTransaction' error: Error: [ethjs-format] object {"to":"0x208A8B1A0318E5ed3E1bd3412B5d2E7eE688fac0","data":"0xa15ab08d0000000000000000000000002ce13d8dd1b248286575591b695805327cf7d9ba0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000"} must contain properties: from, data`

The function in solidity:

`    function create(address to, string metadata) public onlyAdmin {`

Whats going on here?

**Comment by 1blockologist** [comment]
Yeah how did you solve this?

**Comment by elliotthill** [comment]
Payable functions have to be called with from parameters like so:

`myethobj.create("0x2ce13d8dd1b248286575591b695805327cf7d9ba", "hello", {from: '0x2ce13d8dd1b248286575591b695805327cf7d9ba'});`

Where the from should be the current account selected in metamask/mist.
