### ISSUE TITLE
[Bug]: Network is not switched when performing swap

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28477]
### Describe the bug

Network is not switched when performing swap.

1. Non-native token
       When "All networks" is selected and the wallet is set to Polygon (any network other than the one we are going to swap on), choosing BNB USDC correctly displays the USDC balance in both the wallet view and the token details screen. However, on the swap screen and the asset picker screen, the balance appears as zero, accompanied by an incorrect token symbol. Consequently, swaps cannot be executed due to a "Not enough USDC" error. Switching the network to BNB then correctly reflects the USDC balance.

2. Native token
   Choosing native token on another network displays native token for the currently selected network, in the assets picker only current network tokens are shown

Build https://drive.google.com/file/d/1jvpo5HO2M3XxOEIg-nKJFL_SRkINkMxT/view

### Expected behavior

-

### Screenshots/Recordings

Non-native token swap:

https://github.com/user-attachments/assets/58bf59c6-68cd-492c-8ebb-6fbb54e3bc5a

Native token swap:

https://github.com/user-attachments/assets/5cb144a6-3428-4b08-be34-ba462a091137

### Steps to reproduce

1. Start swap

### Detection stage

On the development branch

### Version

dev build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Fixed in this build https://drive.google.com/file/d/1qhGX0lnrTX47M_7kbqBmhOXTd8HvmflL/view?usp=drive_link

**Comment by Unik0rnMaggie** [comment]
Fixed in qa-3 build. 

 Note:

- For native token swap - the token selected on the swap screen is the one from the previous swap, not the current one.

This does not happen for non-native token swaps.

Is it expected behavior? 


https://github.com/user-attachments/assets/26369555-4534-4e72-a9f2-c29315aad887
