### ISSUE TITLE
Sent funds to unknown wallet

### ISSUE THREAD

**Issue by rubenbleeker** [MetaMask/metamask-extension#2849]
Dear Team,

I sent 0.24 etherium from metamask wallet 0x8b0f31df3da4152e47d76d82275d21adcfa54cf4 to wallet 0x851ddcc6466c7b96a40f04b4b3a182ea2039b1b7
The problem is that i dont remeber what wallet i sent it too and i dont have the key. I just tried to make transaction on exchange.
Here you can check my logs:
https://gist.github.com/anonymous/52736e9e70c75070bcca0c17de027be6 

Please help! I need to know if there is a chance i can get the etherium back to metamask wallet or at least find out what wallet it is i sent it to.

Thank you so much,
Ruben

**Comment by Zanibas** [comment]
Can you clarify what you mean when you don't remember what wallet you sent it to? Is it not the address 0x851ddcc6466c7b96a40f04b4b3a182ea2039b1b7?

**Comment by rubenbleeker** [comment]
Yeah thats the address... but i dont remember on witch website i got that wallet address from, i cant find out Where i made the transaction to...
There is a chance i sent my etheriums directly to a wrong address but i cant trace the address itself...?
Thanks!

**Comment by bdresser** [comment]
@rubenbleeker if you're still having trouble, please reach out to support@metamask.io.
