### ISSUE TITLE
[Bug]: Currency name is not displayed for native tokens, for some other tokens fiat values are not shown

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28511]
### Describe the bug

Build https://drive.google.com/file/d/1qhGX0lnrTX47M_7kbqBmhOXTd8HvmflL/view?usp=drive_link

### Expected behavior

-

### Screenshots/Recordings

<img width="687" alt="Screenshot 2024-11-16 at 02 03 39" src="https://github.com/user-attachments/assets/6b7c33ab-5bcf-4f9d-a64d-4809f43d029d">

<img width="1360" alt="Screenshot 2024-11-16 at 01 57 46" src="https://github.com/user-attachments/assets/977d686d-2b68-4eb2-b9fe-d85cb79cff8a">

<img width="1384" alt="Screenshot 2024-11-16 at 02 00 36" src="https://github.com/user-attachments/assets/0b83aa20-9bf2-4887-9d96-6cac33897b1f">

### Steps to reproduce

1. Observe token list 

### Detection stage

On the development branch

### Version

dev build 

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gambinish** [comment]
I've addressed the native token symbol not showing up here: https://github.com/MetaMask/metamask-extension/pull/28386/commits/825b97986d7a0b30bf776271e0411f39fd60dc1a

For the second piece, I'm not sure that this is a regression. On my production wallet, there are certain cases where we do not display the fiat value for currencies without price data:

<img width="360" alt="Screenshot 2024-11-18 at 2 11 13 PM" src="https://github.com/user-attachments/assets/5a589bce-6707-4be0-a10f-e5859a46e6f6">

Can you please confirm if this behavior is consistent with the production instance of this same wallet account?

**Comment by sleepytanya** [comment]
@gambinish 
Confirmed!
12.6.1:

<img width="922" alt="Screenshot 2024-11-18 at 22 34 29" src="https://github.com/user-attachments/assets/a53f9a9a-4e6c-441f-a614-8c0150869230">

**Comment by sleepytanya** [comment]
Fixed in qa-3 build, Nov. 18:


https://github.com/user-attachments/assets/79f467c7-3190-47b4-85b6-d45ecfcffd9a
