### ISSUE TITLE
[Bug]: Upon adding a new network while viewing assets from a currently selected network, there is an inconsistency where the assets of the previously selected network are displayed under the name of the newly added network

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28513]
### Describe the bug

qa-2 build

Upon adding a new network while viewing assets from a currently selected network, there is an inconsistency where the assets of the previously selected network are displayed under the name of the newly added network, even though the correct network name is shown.
The issue can be resolved by navigating away from and then back to the newly added network, which refreshes the asset display 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/16ce704d-03b2-401e-ab6b-3ef3c2238e3d

### Steps to reproduce

1. Select current network assets view
2. Add another network
3. Observe token list

### Detection stage

On the development branch

### Version

qa-2 build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gambinish** [comment]
I do remember runningn into this once or twice. Ty for capturing

**Comment by gambinish** [comment]
Addressed here: https://github.com/MetaMask/metamask-extension/pull/28386/commits/3deb9be14976429dde9d9f5b43024936e57fa767

**Comment by sleepytanya** [comment]
Fixed in qa-3 build, Nov. 18:


https://github.com/user-attachments/assets/e06e8674-a161-4d80-bf09-eb5689196174
