### ISSUE TITLE
Add exit survey on uninstall

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2852]
I saw Pinterest do this, was a clever way to get negative user feedback. Have a short poll asking users why leaving on uninstall.

**Comment by tmashuang** [comment]
https://developer.chrome.com/docs/extensions/reference/runtime/#method-setUninstallURL

**Comment by brad-decker** [comment]
We now have a exit page when a user uninstalls which is a perfect place to add a survey, and @worldlyjohn already has one in mind. We are close to being able to close this one out 4 years later :)

**Comment by worldlyjohn** [comment]
@brad-decker @danfinlay this is completed and deployed
