### ISSUE TITLE
[Bug]: When a user selects the native token of a network different from the one currently active, the swap functionality does not operate correctly

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28534]
### Describe the bug

1. The correct token details are displayed
2. Upon initiating a swap, the appropriate network switch toast notification is displayed
3. The token amount displayed is accurate; however, the name of the currency from the previously selected network is shown instead of the correct token name
4. The swap can be submitted, but the Confirmation screen displays the incorrect currency name
5. Despite the discrepancy in currency name, the swap is executed with the correct token (according to the block explorer)
6. Occasionally extension may experience a crash, reloading resolves the issue

qa-3 build

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/41727ba3-c731-4f71-909d-7cfcbac486f2

https://github.com/user-attachments/assets/a08204cd-0049-4987-99c5-5e207739f5c8

<img width="684" alt="Screenshot 2024-11-19 at 01 01 58" src="https://github.com/user-attachments/assets/07c3925a-b058-45a8-9220-9ed01e083c86">

### Steps to reproduce

1. Connect to any network
2. Select 'All networks'
3. Select native token from another network
4. Click Swap

### Detection stage

On the development branch

### Version

qa-3 build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Unik0rnMaggie** [comment]
Experienced the same behavior on the qa-3 build.

Also described [here](https://github.com/MetaMask/metamask-extension/issues/28477#issuecomment-2488085524)

For native-tokens, the token selected on the swap screen is the one from the previous swap, not the current one.
despite this, the swap is executed correctly. 


https://github.com/user-attachments/assets/c8dedfdd-2f3c-4a72-bc37-682a1d9a8d2f

**Comment by Unik0rnMaggie** [comment]
Following the successful swap, the native token was added on the initially selected network, with 0 balance. Is this intended behavior? 


https://github.com/user-attachments/assets/97e467dd-8747-4f47-ade8-f3e1d99e4109

**Comment by darkwing** [comment]
`getSwapsDefaultToken` is the issue here, since it uses `getCurrentChainId`

**Comment by sleepytanya** [comment]
Native token name issue fixed in qa-7 build:


https://github.com/user-attachments/assets/31ba3cfc-7594-4085-a450-90b47bdd9d60
