### ISSUE TITLE
[Bug]: When test network is selected 'All networks' and 'Current network' balances show zero

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28532]
### Describe the bug

When test network is selected 'All networks' and 'Current network' balances show zero
qa-3 build

### Expected behavior

-

### Screenshots/Recordings

<img width="1094" alt="Screenshot 2024-11-19 at 01 58 31" src="https://github.com/user-attachments/assets/a6286553-7438-4f09-9473-07ecb9cda2ea">

### Steps to reproduce

1. Switch to Sepolia or Linea Sepolia
2. Observe networks balance

### Detection stage

On the development branch

### Version

build qa-3

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by kieth314M7** [comment]
@sleepytanya Thanks for bringing this issue to our attention, The best way to resolve this is to contact our support team.
For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Unik0rnMaggie** [comment]
Reproduced in qa-3 build.


https://github.com/user-attachments/assets/3473c6de-310b-4331-b57d-a06e94d9fae3

**Comment by sleepytanya** [comment]
@gambinish 

'All networks' is unavailable when a test network is selected - is that intentional?

https://github.com/user-attachments/assets/7c1a8689-34e6-4a34-bebd-bd213c66c8fa

**Comment by Unik0rnMaggie** [comment]
Present in qa-5 build, but only for the two default test networks 


https://github.com/user-attachments/assets/9f7495b7-cd0e-458a-9c58-04f58504f65e

**Comment by Unik0rnMaggie** [comment]
Not present in qa-7 build.

For the default test networks, `All networks` selector is disabled.


https://github.com/user-attachments/assets/f80e95f3-47e1-4f17-b3d1-6f8043b459be

**Comment by gambinish** [comment]
This may be an expected behavior. I will make a note to check with product tomorrow.

**Comment by gambinish** [comment]
Just synced with the team, and this is the expected behavior. Closing.
