### ISSUE TITLE
In the current crypto climate, how long does it take ETH purchases to enter MetaMask accounts? 

### ISSUE THREAD

**Issue by williamhessian** [MetaMask/metamask-extension#2857]
I am only a few weeks into finally learning about cryptocurrencies, and am still unclear about how funds go from one place to another, and how to track those funds. After downloading metamask, I had no issues buying ETH, but it has not appeared in my metamask (90 minutes has lapsed) and there are no indications that the funds are still processing (below was my confirmation e-mail 90 minutes ago). I researched other issues regarding this issue and was mostly curious how long it is expected for purchases of ETH to arrive in Metamask at this current time: January 4th 2018. 
Thanks. 

"You purchased0.05105381 ETH
 
Your purchase of 0.05105381 ETH for $53.61 USD was successful!Thank you for using Coinbase to buy Ethereum on MetaMask.View Transaction"

**Comment by Zanibas** [comment]
If you are purchasing from coinbase, transactions may take extended periods of time to process during high traffic moments--this has happened several times within the last few weeks.

Do you have the funds now that it's been about a week?

**Comment by williamhessian** [comment]
Yes i do, thanks. I think it took 13 hours or so.
