### ISSUE TITLE
[Bug]: PPOM error when sending any non-native token

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#28571]
### Describe the bug

When sending any non-native token from Account 2 to Account 1, the Blockaid banner is shown and PPOM error in the console:

`Error#20: Failed to fetch file with url: https://ppom_version.json/`

### Expected behavior

No banner message and no error.

### Screenshots/Recordings

https://github.com/user-attachments/assets/c280c7ad-ad3c-4548-ab51-702e29276a74

### Steps to reproduce

1. Add Account 2
2. Send any non-native token from Account 2 to Account 1
3. See Blockaid banner and console error

### Detection stage

In beta

### Version

12.7.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

qa-3 build

**Comment by sleepytanya** [comment]
Same for the bridge - Blockaid message and transaction fails (the same tx works on prod). 

I've seen [the same issue](https://github.com/MetaMask/metamask-extension/pull/28452#issuecomment-2479562050) where Blockaid validation is shown for  in the `develop`, but it was fixed at least two days ago.


<img width="1046" alt="blockaidBridge" src="https://github.com/user-attachments/assets/14815931-8b69-4b00-ad37-bfdabf8dd196">



https://github.com/user-attachments/assets/27bce078-a0b6-44b1-ac94-bc41e4e252a3

**Comment by Unik0rnMaggie** [comment]
Present in QA-5 build, for Send and Bridge transactions:

![Screenshot 2024-11-21 at 10 40 31](https://github.com/user-attachments/assets/29123d4c-d278-488e-9338-ae45ab1f0db5)
![Screenshot 2024-11-21 at 11 41 48](https://github.com/user-attachments/assets/fe74d30b-0f3a-4005-945e-f416dedf48d5)

**Comment by Unik0rnMaggie** [comment]
Not present in qa-7 build; for both Send or Bridge transactions.


https://github.com/user-attachments/assets/9541ae8d-9c88-4a1e-84ab-f1d5f6beeecb

<img width="361" alt="Screenshot 2024-11-25 at 09 57 54" src="https://github.com/user-attachments/assets/05144552-7bb5-499b-85af-c98f7256c196">

**Comment by darkwing** [comment]
Marking as closed as not present in latest QA build.  Also appears unrelated to PortfolioView work.
