### ISSUE TITLE
[Bug]: The "Select an account" modal displays incorrect balances

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28592]
### Describe the bug

The "Select an account" modal displays incorrect balances. Balances vary depending on the currently selected network but the balance is always incorrect (too big).
For a newly added account the correct balance is shown - 0.

qa-5 build

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/805795c9-0747-444c-a28b-2b603402e345

<img width="1142" alt="Screenshot 2024-11-20 at 23 19 19" src="https://github.com/user-attachments/assets/eea9525d-a685-4c76-8e8a-b58a85280bf7">

### Steps to reproduce

1. Open 'Select an account' modal
2. Observe token balance

### Detection stage

On the development branch

### Version

qa-5 build

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Unik0rnMaggie** [comment]
Present in qa-5 build in "Select Account" mode and also "Send" flow:

![Screenshot 2024-11-21 at 10 51 36](https://github.com/user-attachments/assets/f55382aa-264c-4140-aaef-429d0cfb69ef)
![Screenshot 2024-11-21 at 10 51 58](https://github.com/user-attachments/assets/21a052c5-72b5-49b4-85c3-59a17861bcf0)
