### ISSUE TITLE
[Sentry] [Bug]: TypeError: Cannot add property chain_id, object is not extensible for every send transaction

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#28599]
### Describe the bug

There is a console error for every _Send_ Transaction, but the Tx is successful

`Uncaught (in promise) TypeError: Cannot add property chain_id, object is not extensible`

### Expected behavior

No console error

### Screenshots/Recordings

![Screenshot 2024-11-21 at 11 28 16](https://github.com/user-attachments/assets/f560b936-eda7-4fba-bb6f-5be2d55eb438)

### Steps to reproduce

1. Go to any network
2. Initiate Send transaction for any token
3. Notice console error

### Error messages or log output

```shell
Uncaught (in promise) TypeError: Cannot add property chain_id, object is not extensible
```

### Detection stage

In beta

### Version

12.8.0

(originally found in a QA build for portfolio view)

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

QA-5 build

**Comment by Unik0rnMaggie** [comment]
Present in qa-8 build


https://github.com/user-attachments/assets/465b08b7-1ba7-4bf5-aee0-d56b49a4391c

**Comment by jonybur** [comment]
Been unable to reproduce this yet

**Comment by sleepytanya** [comment]
@Unik0rnMaggie  @jonybur @gambinish 
The issue has been present in `develop` for about a week, is it related to current PR?

**Comment by sahar-fehri** [comment]
I confirm that im also able to see this in develop; also i'm not able to repro everytime i initiate a transaction, i was able to see the error in console once so far; then i do the same steps to initiate a transaction, and the error is not displayed anymore

**Comment by Unik0rnMaggie** [comment]
Thank you @sleepytanya and @sahar-fehri ! i am also able to see it on the latest `develop` build.

I removed the portfolio-view label
