### ISSUE TITLE
Metamask & EtherDelta "No Private Key" error

### ISSUE THREAD

**Issue by DanDan87** [MetaMask/metamask-extension#2860]
So I have only 1 MetaMask account (One 12 word seed phrase) that I have created and I used ETH to buy some Alt coins the other day and when I go to withdraw the coin I get this error below.

![image](https://user-images.githubusercontent.com/35106762/34578329-8aa85fb8-f152-11e7-8f75-c962e7d7e066.png)

Now, it's been suggested to me to use my private key, but from my understanding there is no private key created by MetaMask so I'm confused as to why I can't export since the EtherDelta public key displayed in the top right states "No Private Key" in red.

Here is a picture to show you my MetaMask account in ED along with the EtherDelta public key:

![image](https://user-images.githubusercontent.com/35106762/34578451-fd882afe-f152-11e7-8798-1ab5be8edb7c.png)

Also here is what it shows me when I click export private key on the drop down of the EtherDelta key:

![image](https://user-images.githubusercontent.com/35106762/34578470-140ecd6e-f153-11e7-8194-a4dd5b7f75ec.png)

Any help would be greatly appreciated and I will reward you with some tokens if successful. 

Thank you!

**Comment by DanDan87** [comment]
I will reward anyone $200 in Tokens if they can help me resolve this issue. Thank you.

**Comment by seriousleisure** [comment]
I also need help.

**Comment by drdexter33** [comment]
Did you resolve this issue?\

**Comment by tmashuang** [comment]
Refer to this guide on [Etherdelta account management](http://metamask.helpscoutdocs.com/article/8-etherdelta-account-management-tips) with MetaMask.
