### ISSUE TITLE
[Bug]: Confirmations - Address icons are displayed as JazzIcons in Signatures/Transactions despite having Blockies option selected

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28609]
### Describe the bug

Address icons are displayed as JazzIcons in Signatures/Transactions despite having Blockies option selected

### Screenshots/Recordings

See how the Account icon is displayed in Blockies (Expected) but the addresses inside the Confirmation Signature/Transaction are displayed in JAzzicons

![Screenshot from 2024-11-21 12-57-34](https://github.com/user-attachments/assets/28378c3f-3042-4141-8f72-85ad7d8a56d6)

![Screenshot from 2024-11-21 12-57-48](https://github.com/user-attachments/assets/f173d9a0-a1f1-47f3-b9cc-1fc20747990b)

### Steps to reproduce

1. Go to settings
2. [Update] Disable Nicknames --> this is needed to reproduce the bug
3. Select Blockies icons
4. Trigger a signature or contract interaction
5. See the addresses there are displayed in Jazzicons

### Detection stage

In production (default)

### Version

12.6.2

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by digiwand** [comment]
possibly related to recent asset team changes

**Comment by OGPoyraz** [comment]
Hey @seaona ! Can you help me to identify what am I doing wrong here to replicate this bug?


https://github.com/user-attachments/assets/f33acbff-6eb8-4c37-acad-f865617bafce
