### ISSUE TITLE
[Bug]: Send to ENS emojis domain - Wrong handling of emojis ENS domains

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#28610]
### Describe the bug

Whenever we try to perform a send tx to an address with an ENS domain which uses emojis, like 😉️😉️😉️.eth with Nicknames disabled, we can see in 2 places how this is not correctly handled:
- in the case of old transactions screens, we can see this value in the recipient `xn-n28haa.eth` for the last confirmation page
- in both redesigned and non redesigned, after performing the transaction, we can see the recipient `xn-n28haa.eth`  in the tx receipt

### Expected behavior

I think for the old transaction screens, that could be left unfixed, since this will be fixed in the new redesigned screens.
For the transactions details, once that tx has been send, the recipient should be fixed.

### Screenshots/Recordings

In the Transaction receipt, I can see the wrong "parsing" of that ENS domain:

![Screenshot from 2024-11-21 13-25-35](https://github.com/user-attachments/assets/e6007b3f-bce1-4828-bdf4-9f9186f137a4)

In the non redesign transactions, I can also see the wrong parsing in the last Confirmation screen:

https://github.com/user-attachments/assets/c64e7b9e-43d5-4b8a-aa52-e032c6aaafd2

### Steps to reproduce

1. Disable allow nicknames from experimental settings
2. Disable Improved Transaction Requests from experimental settings
3. Start a send to this account `0x02d8B596130Fc2d8263d32F4f08a92d1761f2e86
4. See how in the last confirmation page is displayed `xn-n28haa.eth`
5. Enable Improved Transaction REquests
6. Perform a complete send flow
7. Wait until tx is confirmed
8. Check tx receipt info --> see how recipient is `xn-n28haa.eth`

### Detection stage

In production (default)

### Version

12.6.2

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
I can't reproduce the bug in 12.11.0 ( we don't have the option to Disable improved transaction requests in 12.11.0:

https://github.com/user-attachments/assets/4252515a-d5a3-4b86-bb36-50e4cef3e4ae
