### ISSUE TITLE
[Bug]: Unable to edit nonce on Ethereum Mainnet - customize transaction nonce is enabled

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#28642]
### Describe the bug

Editing the `nonce` for any send transaction on Ethereum network is not possible, even though `Customize transaction nonce` is enabled in settings. 
This does not affect other networks, only Ethereum Mainnet.

### Expected behavior

Be able to edit the nonce when setting is enabled

### Screenshots/Recordings

https://github.com/user-attachments/assets/d69ba8ec-7745-4d74-9da2-f77bd07b78bf

### Steps to reproduce

1. Switch to Ethereum Mainnet
2. Go to Settings--> Advanced and turn ON `Customize transaction nonce`
3. Send any transaction
4. Noticed the `Nonce` field is missing the edit button

### Detection stage

During release testing

### Version

12.8.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

I obtained the build from [here](https://github.com/MetaMask/metamask-extension/pull/28503#issuecomment-2480210134)

**Comment by Unik0rnMaggie** [comment]
Could be expected behavior. 

When turning "Smart transactions" toggle OFF, the nonce can be edited also on Ethereum Mainnet

**Comment by sleepytanya** [comment]
@Unik0rnMaggie yes, this is expected behavior. Nonce customization is not allowed for STX.

**Comment by pedronfigueiredo** [comment]
Closing this ticket as the behaviour is expected
