### ISSUE TITLE
Metamask & EtherDelta insufficient eth balance message

### ISSUE THREAD

**Issue by mtcarmel1914** [MetaMask/metamask-extension#2865]
I have $100 in eth balance I am trying to make a transaction and I am being told that I have an insufficient balance to carry out the transaction and I am being asked to buy more eth...why? Is there a problem between you and etherdelta that i need to know about or is this strictly a metamask issue? how do I fix this?

**Comment by Zanibas** [comment]
Your MetaMask account needs ether in order to execute the transaction, on top of the ether that's in EtherDelta. If you do not have enough ether in MetaMask, you can't execute the transaction. It's an unfortunate user experience, but this is what the technology is at right now.
