### ISSUE TITLE
my ethers are not being deposited in etherdelta from metamask. Although the balance clearly reflects in the etherdelta.

### ISSUE THREAD

**Issue by sriharimk** [MetaMask/metamask-extension#2866]
![ethde](https://user-images.githubusercontent.com/35127145/34595587-315a7fe2-f1ff-11e7-9a79-07305ce4ee3b.png)

**Comment by Zanibas** [comment]
The transaction has not finished processing. Have the funds appeared in EtherDelta yet?

**Comment by heybud1** [comment]
probably lost your money, no surprise to me, same issue for everyone.

**Comment by sriharimk** [comment]
It will be really good when any DEX comes into picture.

**Comment by Zanibas** [comment]
Did the transaction finish processing?
