### ISSUE TITLE
[Bug]: Notifications show up for a previously imported account, not associated with the current SRP - on develop build

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#28690]
### Describe the bug

When restoring an SRP that had a previously imported account and turning ON Notifications, the list is populated with notifications corresponding to the imported account, not the current one associated with this SRP.

### Expected behavior

Not to show notifications for a previously imported account

### Screenshots/Recordings

https://github.com/user-attachments/assets/df281ea4-db0d-4cab-a7dd-a86d44b56368

### Steps to reproduce

1. Restore an existing wallet with an SRP that had an imported account.
2. Notice Account 1 is restored 
3. Turn ON Notifications
4. Notice notifications for the previously imported account

### Detection stage

On the development branch

### Version

12.7.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

On `develop` branch

**Comment by Prithpal-Sooriya** [comment]
Sorry for the tag updates. Originally I expected that this account importing was related to account syncing (identity team). However this is notifications related.

**Some hypothesis/context:**

Notifications rely on the same mechanism for Profile Syncing. And you can technically create notifications for any address.
My hypothesis is that the settings page on notifications allows you to create notifications for imported accounts.
So when you re-onboard the wallet (with the same SRP), it will also contain notifications from the imported accounts you previously have added.

**Comment by Prithpal-Sooriya** [comment]
I wouldn't mark this as a high sev-1 bug, as this isn't breaking any existing flow, but can be confusing for users who off-board and on-board with notifications.

**Comment by Prithpal-Sooriya** [comment]
FIXES:

**Comment by Prithpal-Sooriya** [comment]
Cleanup - we now filter in-app notifications based on the accounts available in the wallet.
Plus with account-syncing, accounts are added during onboarding
