### ISSUE TITLE
[Bug]: Upgrade Testing scenario fails on Firefox

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#28718]
### Describe the bug

The [Upgrade testing](https://github.com/MetaMask/metamask-extension/blob/develop/test/manual-scenarios/upgrade-testing/upgrade-testing.md) scenario fails on Firefox browser.

Post-upgrade to Version-v12.8.0 the send flow is unresponsive; "Loading tokens" message shows up and cannot switch networks.

### Expected behavior

Be able to send post-upgrade

### Screenshots/Recordings

https://github.com/user-attachments/assets/64a5e558-cbde-41ec-b27a-d6cb7cb3c633

### Steps to reproduce

1. Follow the steps from the upgrade testing scenario for Firefox `yarn start:mv2`
2. Notice that post-upgrade to the release branch `Version-v12.8.0`:

- unable to send transaction
- "Loading tokens" message
- unable to switch networks

### Detection stage

During release testing

### Version

12.8.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Firefox

### Operating system

MacOS

### Additional context

Upgrading from `master` branch to `Version-v12.8.0` release branch

**Comment by hjetpoluru** [comment]
@Unik0rnMaggie, I tested this scenario and its working as expected. I have attached video for reference please let me know if its the same and I will wait for you to confirm before closing the ticket.

With master build
https://github.com/user-attachments/assets/1121c0d9-8dae-430a-bd5d-769d5dcf5894

Upgrade to v12.8.0
https://github.com/user-attachments/assets/779e1594-5f58-4453-9886-47069abf1584

Note: I have tried it 3 times just to get the prefect video.

**Comment by Unik0rnMaggie** [comment]
Hi @hjetpoluru! Thank you very much for sharing the videos! 

I tried again and it works on Firefox also. It seems I wasn't loading the extension properly the first time!

thank you!
