### ISSUE TITLE
Failed Ether Transfer Still Lost Sent Ethers

### ISSUE THREAD

**Issue by Edmundhe** [MetaMask/metamask-extension#2871]
Hi Metamask Team,
At approximately Jan/5/2018 1:17 AM EST I sent 0.157143 from my Metamask wallet to my wallet on the Gemini exchange. Though the transaction failed on the Metamask extension, I still completely lost the corresponding ethers and never received them on the other end either. Is there anything I can do to get back my lost ethers?

Thank you!

![screen shot 2018-01-05 at 1 54 09 am](https://user-images.githubusercontent.com/19366355/34598692-3c8caac2-f1bc-11e7-838b-d70685c065b8.png)

[MetaMask State Logs.txt](https://github.com/MetaMask/metamask-extension/files/1605778/MetaMask.State.Logs.txt)

**Comment by Zanibas** [comment]
It looks like the funds were received on the other side--did the situation eventually resolve?

**Comment by Edmundhe** [comment]
Yes the funds were received. Sorry I didn't have the opportunity to close
this sooner.

**Comment by Zanibas** [comment]
No problemo~
