### ISSUE TITLE
[Bug]: Account connected count is incorrect

### ISSUE THREAD

**Issue by racitores** [MetaMask/metamask-extension#28724]
### Describe the bug

When several accounts are connected to a dapp, the number of account connected shown in the details is incorrect
![Screenshot 2024-11-22 at 12 23 45](https://github.com/user-attachments/assets/94d24f9b-0e3c-424d-bca8-cf4bbfb0cc0c)

### Expected behavior

The number of accounts connected should be 2

### Steps to reproduce

1. Connect 2 of 3 accounts to a dapp (E2E Test Dapp)
2. Check in main screen > connected accounts 
3. You can see the screenshot above

### Detection stage

During release testing

### Version

12.8.0

### Build type

None

### Browser

Firefox

### Operating system

MacOS

### Severity

Minor

**Comment by HeroldAlpha-tech** [comment]
> ### Describe the bug
> 
> When several accounts are connected to a dapp, the number of account connected shown in the details is incorrect
> 
> ![Screenshot 2024-11-22 at 12 23 45](https://github.com/user-attachments/assets/94d24f9b-0e3c-424d-bca8-cf4bbfb0cc0c)
> 
> 
> 
> 
> 
> ### Expected behavior
> 
> The number of accounts connected should be 2
> 
> ### Screenshots/Recordings
> 
> _No response_
> 
> ### Steps to reproduce
> 
> 1. Connect 2 of 3 accounts to a dapp (E2E Test Dapp)
> 
> 2. Check in main screen > connected accounts 
> 
> 3. You can see the screenshot above
> 
> ### Error messages or log output
> 
> _No response_
> 
> ### Detection stage
> 
> During release testing
> 
> ### Version
> 
> 12.8.0
> 
> ### Build type
> 
> None
> 
> ### Browser
> 
> Firefox
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_
> 
> ### Severity
> 
> Minor

Thanks for bringing this issue to our attention.The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by NidhiKJha** [comment]
This PR will fix this https://github.com/MetaMask/metamask-extension/pull/28725

**Comment by racitores** [comment]
Tested and fixed
