### ISSUE TITLE
Cannot deposit to EtherDelta with a few of error messages

### ISSUE THREAD

**Issue by skhiewla** [MetaMask/metamask-extension#2872]
Below are error messages I got when depositing to EtherDelta

<img width="364" alt="screen shot 2561-01-05 at 16 05 42" src="https://user-images.githubusercontent.com/35133818/34602863-10ee4e5c-f234-11e7-86b2-f084e18db425.png">

<img width="362" alt="screen shot 2561-01-05 at 16 13 38" src="https://user-images.githubusercontent.com/35133818/34602893-2e374b58-f234-11e7-81ea-134ccfcb4978.png">

<img width="345" alt="screen shot 2561-01-05 at 16 14 00" src="https://user-images.githubusercontent.com/35133818/34602907-37140fc2-f234-11e7-9d62-770d2f728d0b.png">

Before this happen, I did reject pending transection,0x62b72ccf378942517ada697ec272b272b738cfd3cf5c75eed787edd7f309a3f2.

https://etherscan.io/tx/0x62b72ccf378942517ada697ec272b272b738cfd3cf5c75eed787edd7f309a3f2

However, I check my account in Etherscan the balance is still as it was at 0.248741 Ether. 
<img width="344" alt="screen shot 2561-01-05 at 16 14 18" src="https://user-images.githubusercontent.com/35133818/34602967-912b1690-f234-11e7-865d-3ea9a574e588.png">
 
My wallet address ==> 0xd0854Ccd1AD2169D97fAADd30BAc40A28F6aceCD
<img width="673" alt="screen shot 2561-01-05 at 16 22 57" src="https://user-images.githubusercontent.com/35133818/34603074-f6c5afba-f234-11e7-9fbb-7606b191c591.png">

<img width="1175" alt="screen shot 2561-01-05 at 16 30 40" src="https://user-images.githubusercontent.com/35133818/34603257-da479a6e-f235-11e7-9417-342d2b6abf4d.png">

[MetaMask State Logs.json.txt](https://github.com/MetaMask/metamask-extension/files/1607016/MetaMask.State.Logs.json.txt)

So, please help investigate why I cannot deposit to EtherDelta

Thank you in advance,
-Sakon

**Comment by tmashuang** [comment]
Might have been a network issue at the time. Will reopen if this is still and issue.
