### ISSUE TITLE
[Bug]: Misalignment in send, speed up, cancel and swaps screens

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#28722]
### Describe the bug

The Send screen and Swap to, swap from screens look different:

### Expected behavior

Same alignment as before:

![Screenshot 2024-11-26 at 13 42 20](https://github.com/user-attachments/assets/9f95bccf-95a9-40ea-a259-f0a2ce5843c1)
![Screenshot 2024-11-26 at 13 42 29](https://github.com/user-attachments/assets/dabc6d3e-4bc3-4172-8111-6612ef9ea3f5)
![qa-7 build](https://github.com/user-attachments/assets/db061dcd-e680-4e5e-814b-3ca4a737ed84)

### Screenshots/Recordings

![Screenshot 2024-11-26 at 13 32 12](https://github.com/user-attachments/assets/440bf0dc-46ab-48af-b872-5f083d37c122)
![Screenshot 2024-11-26 at 13 32 21](https://github.com/user-attachments/assets/94114e46-937a-4533-8848-2830e5c45de7)
![Screenshot 2024-11-26 at 13 29 51](https://github.com/user-attachments/assets/3d6d5bb3-4232-4028-a258-1c275135d41c)
![Screenshot 2024-11-26 at 13 29 59](https://github.com/user-attachments/assets/0251f75f-7f36-4c05-b760-e3e1ed9a8503)
![Screenshot 2024-11-26 at 13 29 35](https://github.com/user-attachments/assets/1da118bf-df9d-44a0-b15c-3e52dc0d2cf6)
![qa-8 build](https://github.com/user-attachments/assets/a9d66e8a-a828-4694-b096-7f797154c4b8)

### Steps to reproduce

1. build locally on latest `develop` branch
2. notice UI changes and misalignment for:
- Send Flow (From and To), speed up, cancel transaction
- Swaps flow (Swap to, Swap From, slippage)

### Detection stage

On the development branch

### Version

12.7.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Looks great!

https://github.com/user-attachments/assets/f360831b-33ae-4a4e-8f67-950db2a53dd6





https://github.com/user-attachments/assets/5a84f5ec-071e-4e0f-a0ec-fdb115079054


<img width="1399" alt="Screenshot 2024-11-26 at 18 06 18" src="https://github.com/user-attachments/assets/0e4616ae-8c4a-409b-bd2c-31d4757a8288">



<img width="1044" alt="Screenshot 2024-11-26 at 18 07 14" src="https://github.com/user-attachments/assets/163bb696-b31a-402e-82c1-4bb59710ac9c">
