### ISSUE TITLE
[Bug]: When importing tokens across all networks, users encounter misaligned Token Import modal

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28749]
### Describe the bug

When importing tokens across all networks, users encounter a visually deformed token import modal. However, switching the view to 'Current network' results in the import modal appearing normal

Probably related to[ this bug](https://github.com/MetaMask/metamask-extension/issues/28722) which is already fixed in [develop]

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/02ba6740-07df-458f-a13c-596b7a035513

<img width="366" alt="Screenshot 2024-11-26 at 18 42 11" src="https://github.com/user-attachments/assets/bb8c1c3b-5d18-47d5-bf36-5fe11c2f3d05">

### Steps to reproduce

1. Have account with non-imported tokens across different networks
2. Select 'All networks'
3. Try to import tokens

### Detection stage

On the development branch

### Version

qa-9

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gambinish** [comment]
I believe this will be addressed with this PR: https://consensys.slack.com/archives/CTQAGKY5V/p1732644278395929?thread_ts=1732601670.933809&cid=CTQAGKY5V

**Comment by gambinish** [comment]
Actually, after pulling the latest develop, this does in fact, seem to be fixed.

**Comment by gambinish** [comment]
<img width="443" alt="Screenshot 2024-11-26 at 5 21 48 PM" src="https://github.com/user-attachments/assets/6f3abecf-4bfa-447c-a30d-876ce3088ed4">

**Comment by sleepytanya** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/28739 
Latest `develop` build:



https://github.com/user-attachments/assets/4554c4f8-51d2-414c-a9bd-f38df9860dd6
