### ISSUE TITLE
Restored account is not showing address with ERC20 tokens, even after adding multiple accounts

### ISSUE THREAD

**Issue by protonjo** [MetaMask/metamask-extension#2874]
This morning I logged into myetherwallet.com and tried to connect it with Metamask. Metamask would not connect to the ETH network. It then kicked me out to the enter password screen in which I tried to enter my password but my password would not work. I restored the wallet using a seed key but the restored account only shows a new address. I have tried adding multiple accounts and I am still not seeing the address with the balance. I also restored the seed key on MEW and that interface as well is not showing the account with my ERC20 balance that I am trying to access. At this moment I cannot find the UCT file or private key that is associated with the account address I am trying to restore. 0xfb898a4C355bCdCb5524DF3f04EADadDc1c3A637

Thanks in Advance,
Protonjo

**Comment by tmashuang** [comment]
Was this a new MetaMask account or one created in MEW then imported into MetaMask? Please send a reply to #2804.
