### ISSUE TITLE
[Bug]: Extension breaks with an error TypeError: Cannot read properties of undefined (reading 'conversion at LavaPack.loadBundle.n.useTokenFiatAmount when trying to import tokens

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28750]
### Describe the bug

The issue described tends to occur when a user possesses assets across different networks, switching between networks and importing tokens.
For me It is most likely to manifest after adding a new network and attempting to import tokens while the 'Current network' option is selected. Although exact reproduction steps are not available and this bug also happened to me while importing token for 'All networks' 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/b66ca142-1a2c-4401-9a60-8d5fe23e6744

<img width="1508" alt="Screenshot 2024-11-26 at 17 44 05" src="https://github.com/user-attachments/assets/fa69fa8e-1a7c-4d92-8fed-620a672c92ae">

### Steps to reproduce

1. Have non-imported tokens across different networks
2. Switch networks, import tokens

### Detection stage

On the development branch

### Version

qa-9

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Unik0rnMaggie** [comment]
Not present in the latest `develop` build
