### ISSUE TITLE
Some parts not showing on smaller screens

### ISSUE THREAD

**Issue by step21** [MetaMask/metamask-extension#2875]
Expected:

All important parts of the extension are visible or can be scrolled to.

  *  Actual Behavior

Lower button is not shown properly. This is on a Lenovo x230 with a 1366x768 screen
Similar to https://github.com/MetaMask/metamask-extension/issues/782
![metamask](https://user-images.githubusercontent.com/46968/34620531-0fb878d4-f246-11e7-9206-c7d401227fd3.png)

  *  Browser Used

Firefox (latest)

  *  Operating System Used
Ubuntu 16.04.3 with Unity

**Comment by Kordau** [comment]
Same issue...

- Win10
- Firefox
- 1920x1080 resolution

This issue also means you can only see THREE tokens listed in the TOKENS tab. There are 4-5 pixels of the hitbox for the fourth token clickable, at the bottom of the window.

![metamask - windows size issue](https://user-images.githubusercontent.com/10484068/34755732-d0f237b4-f611-11e7-975e-198a30bdcf9b.jpeg)

**Comment by tmashuang** [comment]
Fixed in #2929 and #3176.
