### ISSUE TITLE
[Bug]: Base Chain: Max send does not factor in gas cost

### ISSUE THREAD

**Issue by MeltedMindz** [MetaMask/metamask-extension#28760]
### Describe the bug

When using Base on metamask if you go to send eth to another wallet and you click "Send max" it doesnt factor in the gas cost and tries to send the entire amount, this would be an easy fix. 

### Expected behavior

On mainnet when you hit "Send max" it adjusts it to subtract enough to cover the gas cost. It should be the same way on base. 

### Steps to reproduce

Go to Base

Click on send eth.

Enter the destination wallet and click send max

The transaction will fail because it hasnt subtracted the gas cost 

### Detection stage

In production (default)

### Version

12.6.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
I was not able to reproduce this issue. Is there any other step or detail I might be missing to repro, @MeltedMindz ?

**Comment by MeltedMindz** [comment]
It looks like it must of been fixed since I created this issue, I apologize.

**Comment by bschorchit** [comment]
No worries at all. I am glad this was fixed! Thank you for reporting it, @MeltedMindz.
