### ISSUE TITLE
metamask wont generate deposit, horrible do not use

### ISSUE THREAD

**Issue by heybud1** [MetaMask/metamask-extension#2876]
wont deposit on etherdelta and wont send ether back to my wallet.   seems like a scam

**Comment by Zanibas** [comment]
EtherDelta has been experiencing tons of issues recently due to its change of ownership. That is a problem on their side--not ours. We are welcome for your feedback, but we do not tolerate baseless accusations.

**Comment by heybud1** [comment]
so no useful feedback but to be sensitive!  sounds very scammy
