### ISSUE TITLE
sneaky little fox, appropriate logo,lol.  cant get ether back to my desktop wallet

### ISSUE THREAD

**Issue by heybud1** [MetaMask/metamask-extension#2877]
Im glad I only put 20 dollars of ether into metamask trying to learn the exchange.  Cant deposit into etherdelta smart contract so tried to to go back to desktop wallet and cant get a transaction address or anything.  Even if i increase the gas to 40% of transction.  I guess my trades will stay on other exchanges.

**Comment by heybud1** [comment]
all i received were some defensive emails but no useful feedback

**Comment by tmashuang** [comment]
Seems this and #2876 are your "issues" you are referring to. I will try to clarify to the best of my ability with the fragmented information provided on the possible issue with transactions via EtherDelta. We allow Dapps to submit transactions with what they determine what an adequate gas price would be. Dapps can guess the appropriate gas price or just submit a default one. In EtherDelta's case they submit a default of 4 Gwei. The recommended gas price can be found on [EthGasStation](https://ethgasstation.info/). To prevent transactions being stuck in limbo when there is an abundance of transactions, we prevent sending transactions that are not close to the recommended gas price. Network congestion can be seen here, https://etherscan.io/txsPending. We could handle the transaction state better. The resolution would be to send a transaction with the recommended gas price. 40% of 4 is still a low gas price in times when there's an abundance of transactions trying to get processed.

**Comment by heybud1** [comment]
pretty funny only took a couple seconds to put my .02 ether and been trying to get it out for 6 hours.   A little help would be appreciated.  Thanks I tried to paying almost half in gas of my .02 ether and still can't withdraw .014.  obviously I'm missing something.  also tried exporting still can't.

**Comment by heybud1** [comment]
why would I want to deposit real money in this wallet when there are wallets on exchanges that will help me

**Comment by heybud1** [comment]
40% of 20$ is 8$. that is absurd and still can't
