### ISSUE TITLE
[Bug]: CTA is disabled in transaction confirmation

### ISSUE THREAD

**Issue by SayaGT** [MetaMask/metamask-extension#28792]
### Describe the bug

When content falls below the fold, an arrow appears and CTA is disabled. This legacy behavior specific to signature and should not be happening for transactions.
<img width="472" alt="Screenshot 2024-11-28 at 15 28 59" src="https://github.com/user-attachments/assets/efb2b0f0-6490-4689-8f9d-ebc84dce31bf">

### Steps to reproduce

Generate any transaction

### Detection stage

In production (default)

### Version

12.7.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Closing as I confirmed this is fixed on v12.8
