### ISSUE TITLE
[Bug]: Send+swap requests are failing on all networks, quotes not fetched

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28798]
### Describe the bug

Send+swap request are failing on all networks, quotes not fetched

@infiniteflower - thank you for investigation!

> Looks like an issue on Swap API 0.17.0, which was deployed yesterday
> 0.16.0 does not give the 500 code

[https://swap.api.cx.metamask.io/v2/networks/1/quotes?sourceAmount=2000000000000000000&so[…]ent=0xa24b5c474df517b083811b099054d670ba696c7a&slippage=2](https://swap.api.cx.metamask.io/v2/networks/1/quotes?sourceAmount=2000000000000000000&sourceToken=0x6b175474e89094c44da98b954eedeac495271d0f&destinationToken=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&sender=0x27ffa2cc5417dda8653147ab989953e84debd5a6&recipient=0xa24b5c474df517b083811b099054d670ba696c7a&slippage=2) 

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/730c1649-f78c-49fd-b9e5-d4254e14c6d4

<img width="812" alt="Screenshot 2024-11-28 at 14 35 32" src="https://github.com/user-attachments/assets/4a27ee86-3fee-4418-9379-8da77d430a2f">

<img width="1336" alt="Screenshot 2024-11-28 at 14 28 29" src="https://github.com/user-attachments/assets/cd35e06e-54de-4629-944c-1573585790f2">

### Steps to reproduce

1. Start send+swap flow

### Detection stage

In production (default)

### Version

12.7.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by frank239tech** [comment]
> ### Describe the bug
> Send+swap request are failing on all networks, quotes not fetched
> 
> @infiniteflower - thank you for investigation!
> 
> > Looks like an issue on Swap API 0.17.0, which was deployed yesterday
> > 0.16.0 does not give the 500 code
> 
> [https://swap.api.cx.metamask.io/v2/networks/1/quotes?sourceAmount=2000000000000000000&so[…]ent=0xa24b5c474df517b083811b099054d670ba696c7a&slippage=2](https://swap.api.cx.metamask.io/v2/networks/1/quotes?sourceAmount=2000000000000000000&sourceToken=0x6b175474e89094c44da98b954eedeac495271d0f&destinationToken=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&sender=0x27ffa2cc5417dda8653147ab989953e84debd5a6&recipient=0xa24b5c474df517b083811b099054d670ba696c7a&slippage=2)
> 
> ### Expected behavior
> 
> ### Screenshots/Recordings
>  Screen.Recording.2024-11-28.at.14.34.06.mov 
> <img alt="Screenshot 2024-11-28 at 14 35 32" width="812" src="https://private-user-images.githubusercontent.com/104780023/390893061-4a27ee86-3fee-4418-9379-8da77d430a2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MzM1NDUsIm5iZiI6MTczMjgzMzI0NSwicGF0aCI6Ii8xMDQ3ODAwMjMvMzkwODkzMDYxLTRhMjdlZTg2LTNmZWUtNDQxOC05Mzc5LThkYTc3ZDQzMGEyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQyMjM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODZmMjY2YjdjMzY0YTYwMGFlZDIxZDFkNDVkN2Q0MWNkNjY1NGIxZmFlM2Y4YjU0NjU2OGM1MTJiNmI5ZmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.890YKjrJbAsoI9DchKv9jpyil3xcrxYrQ3i79VyC4hs"> <img alt="Screenshot 2024-11-28 at 14 28 29" width="1336" src="https://private-user-images.githubusercontent.com/104780023/390894141-cd35e06e-54de-4629-944c-1573585790f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MzM1NDUsIm5iZiI6MTczMjgzMzI0NSwicGF0aCI6Ii8xMDQ3ODAwMjMvMzkwODk0MTQxLWNkMzVlMDZlLTU0ZGUtNDYyOS05NDRjLTE1NzM1ODU3OTBmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQyMjM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzM4YzA2MWEzZTBjYzQ5MjgxZGQ4MDNkMmY3MDUxYmQxZTAxNGYzOGExNDI2ZjAwMmRiMjVmZWEwYTQ1N2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z2gq9I4WRWp-yHh7m5WN7cTQQce5OunnLiA4ZbtlzGo">
> ### Steps to reproduce
> 1. Start send+swap flow
> 
> ### Error messages or log output
> _No response_
> 
> ### Detection stage
> In production (default)
> 
> ### Version
> 12.7.2
> 
> ### Build type
> None
> 
> ### Browser
> Chrome
> 
> ### Operating system
> MacOS
> 
> ### Hardware wallet
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Severity
> _No response_

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Metamask Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by sleepytanya** [comment]
May be fixed by https://github.com/consensys-vertical-apps/va-mmcx-swap-api/pull/226
