### ISSUE TITLE
failed transaction and fund is missing

### ISSUE THREAD

**Issue by absan86** [MetaMask/metamask-extension#2883]

**Comment by absan86** [comment]
![1](https://user-images.githubusercontent.com/35181500/34645536-3fb02aae-f31e-11e7-8bfa-d7e7a36497be.jpg)
![2](https://user-images.githubusercontent.com/35181500/34645538-41f18ce0-f31e-11e7-93a0-0f38a131565b.jpg)

**Comment by absan86** [comment]
Transaction  0x88f426362e85ca9c30b73876fb734f4214c551096c4681a260c807eaeb0d2107

**Comment by absan86** [comment]
[MetaMask State Logs.zip](https://github.com/MetaMask/metamask-extension/files/1609417/MetaMask.State.Logs.zip)

**Comment by tmashuang** [comment]
Seems the transaction was updated with a different gas price thus creating a new transaction hash. The transaction was successful, https://etherscan.io/tx/0xadfc8bf91d04f2ea1197335ad1f3d7b423df1de7e3ac984b191f31f7662099a2. Is this still an issue?

**Comment by absan86** [comment]
thanks tmashuang yea it went in after 3 days.
