### ISSUE TITLE
[Bug]: Following the link to view TXS details, then BlockExplorerUrl undefined error in portfolio

### ISSUE THREAD

**Issue by racitores** [MetaMask/metamask-extension#28846]
### Describe the bug

https://www.loom.com/share/0904c789978f41ffb6c6be37d6f7373c

### Expected behavior

Either shows the txs data or if is not ready not show an error

### Screenshots/Recordings

Error with console error
![Screenshot 2024-12-02 at 13 19 50](https://github.com/user-attachments/assets/02d9c034-d3da-407e-99ad-c3662feeea85)

### Steps to reproduce

Send TX
Once is confirmed click view tx from confirmation screen
The portfolio opens showing the error

### Detection stage

During release testing

### Version

12.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
I think this issue is not a regression but a pre-existing issue (affecting Sepolia), see [here](https://github.com/MetaMask/metamask-extension/issues/24158) for more context.
Could you try to reproduce this in prod, and confirm if you see the same behaviour, just to confirm it? @racitores
