### ISSUE TITLE
[Bug]: undefined value display on speed popover 

### ISSUE THREAD

**Issue by Akaryatrh** [MetaMask/metamask-extension#28840]
### Describe the bug

When user wants to speed up a slow transaction, once he clicks on speed up button, an `undefined` value is displayed besides the `10% increase` message.

### Expected behavior

I'm not sure what should be displayed instead of `undefined` but it replaces 🐢 icon during a re-render of the component `ui/pages/confirmations/components/gas-timing/gas-timing.component.js`.

Please check component here https://github.com/MetaMask/metamask-extension/blob/5ab288b8587df64bd7a9c0ede2d0d085dfd713ae/ui/pages/confirmations/components/gas-timing/gas-timing.component.js#L136

### Screenshots/Recordings

https://github.com/user-attachments/assets/2d1ed99f-ea56-41ce-b42d-b14092b2a169

### Steps to reproduce

- click on send button
- select another account and let 0 for amount
- edit Network fee and select low fees
- send the transaction and click on speed up button when it appears (you may have to try multiple times if tx gets validated too fast)
- notice the undefined value on the speed up popover

### Detection stage

In production (default)

### Version

12.7.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by cryptotavares** [comment]
Duplicate - https://github.com/MetaMask/metamask-extension/issues/27092
