### ISSUE TITLE
[Bug]: My metamask in firefox is loading for 30+mins.

### ISSUE THREAD

**Issue by GoodsHope** [MetaMask/metamask-extension#28859]
### Describe the bug

[Bug]: My metamask in firefox is loading for 30+mins.
I can't get my money,can't access to the wallet
My firefox is 133.0(64),and the metamask plugin in firefox is still 12.0.6,but it said it's newest.

### Expected behavior

I want to open the plugin and can access to my money
I've already asked for help in metamask official site,none of their operations are helpful.
Update,and make it work,thanks

### Screenshots/Recordings

![图片](https://github.com/user-attachments/assets/87f9ec28-160d-4962-89e1-fd621aa26476)
![图片](https://github.com/user-attachments/assets/15471d89-ff9e-4072-bfc3-d5f078475148)

### Steps to reproduce

1.click the plugin logo

### Detection stage

In production (default)

### Version

12.0.6

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by Direnyy** [comment]
Hello @GoodsHope  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by DanielTech21** [comment]
Hi @GoodsHope 

Thank you for reporting the issue to us.

Our team is investigating and get back to you with updates.

**Comment by owoerator** [comment]
Also affected, firefox infinite load.
There's also people in the other thread here: https://github.com/MetaMask/metamask-extension/issues/22533
Suffering the same trouble. Hope this gets fixed asap and pushed to FF apps

**Comment by gauthierpetetin** [comment]
Thanks for reporting this issue, we're currently tracking it in #22533 already so I'll close this one as duplicate.
