### ISSUE TITLE
[Bug]: MetaMask crash when try to import token after onboarding with basic functionality off

### ISSUE THREAD

**Issue by chloeYue** [MetaMask/metamask-extension#28864]
### Describe the bug

Onboarding MM by importing a wallet which have ERC20 token asset, toggle off basic functionality on manage privacy settings page during onboarding, click import token on homepage after onboarding makes MM crashes.

Note: not reproducible on production

### Expected behavior

MM should not crash

### Screenshots/Recordings

https://github.com/user-attachments/assets/305cafab-5350-4977-b30b-c189bed80796

### Steps to reproduce

1. Onboarding to MM by importing wallet with ERC20 asset
2. Toggle off basic functionality on privacy settings during onboarding
3. Click import token on homepage

### Detection stage

During release testing

### Version

12.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by seaona** [comment]
Could this be related to the below Sentry issue? I see that the error is the same `TypeError: Cannot convert undefined or null to object`. Possibly it's a different way to reproduce it, given in this ticket it's not in prod, but closely related :thinking: 

The below case is reproduceable with the Token price feature disabled, and not when enabled. It happens both in the RC and in current prod. Possibly something changed and now the error can also be triggered with the above repro steps

https://github.com/MetaMask/metamask-extension/issues/28019

**Comment by gambinish** [comment]
PR fix here: https://github.com/MetaMask/metamask-extension/pull/28904

Will cherry pick to RC once approved and merged

**Comment by gambinish** [comment]
Let's actually go with @sahar-fehri fix here: https://github.com/MetaMask/metamask-extension/pull/28870

Same fix for a different bug, but should also resolve this issue here.
