### ISSUE TITLE
after restore from seed phrase any extra accounts are not shown

### ISSUE THREAD

**Issue by nZale** [MetaMask/metamask-extension#2887]
After locking out and trying to restore with seed phrase only 1 account is shown (the default 'Account 1'). I can't find the other one where i actually have currency.

Any ideas why?

**Comment by protonjo** [comment]
If all is working as it is designed to, you would have to add multiple new accounts until the account with the balance shows up.

**Comment by tmashuang** [comment]
@nZale when restoring a seed phrase, only the first account is shown for simplicity. By clicking the 'Create Account' button it will generate the accounts in the order it was generated in.

**Comment by Jules-Win** [comment]
> If all is working as it is designed to, you would have to add multiple new accounts until the account with the balance shows up.

This is not happening for me.
It restored the first account and I can add others, but the account I have with live funds in it (and a node connected to it) doesn't show up, no matter how many accounts I add. The account wasn't imported from another wallet, but created in the Brave wallet, so I assume it was derived from my seed phrase derivation path. Why is it not showing up then? Please respond if there's any way to access my address, cause I didn't back up the private key to that account, and only have the seed phrase for back up.

**Comment by mattpascoe** [comment]
Just mentioning that my ticket #20233 was basically this same thing.  I think the problem for me is around the wording in the dialogs talking about the backups and restore.  It is unclear what was going to happen.  Not that I'm offering any specific solution but if somehow we could wordsmith something here that would help explain things better, or maybe reference some sort of brave documentation that explains that you can simply just keep adding accounts, that would be appreciated.   Additionally some way to save/sync the account names would be helpful.

Thanks much.
