### ISSUE TITLE
Eth_decrypt not working anymore

### ISSUE THREAD

**Issue by randy75828** [MetaMask/metamask-extension#28879]
### What is this about?

eth_decrypt doesn't seem to work anymore. Was trying out via https://docs.metamask.io/wallet/reference/json-rpc-methods/eth_decrypt/ and it wasnt working too. I do have some legacy application where i used eth_getEncryptionPublicKey to encrypt some funds. How can i migrate out my funds?

Error
```
{
  "code": -32603,
  "message": "MetaMask DecryptMessage: User denied message decryption.",
  "data": {
    "cause": {
      "stack": "Error: MetaMask DecryptMessage: User denied message decryption.\n  at s.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:239980)\n  at Function.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/sentry-install.js:1:750)\n  at Object.d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:1:368259)\n  at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-5.js:1:370304)\n  at a.setMessageStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:231008)\n  at a.rejectMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:232352)\n  at g._cancelAbstractMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:355368)\n  at g.decryptMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:354477)\n  at async r.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-6.js:1:167523)",
      "message": "MetaMask DecryptMessage: User denied message decryption."
    }
  }
}
```
![image](https://github.com/user-attachments/assets/86e3c1c3-0e08-4549-8e11-c2b40658534f)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by DanielTech21** [comment]
Hi @randy75828 

This method is deprecated based on the documentation [here](https://docs.metamask.io/wallet/reference/json-rpc-methods/eth_decrypt/).
That is the reason why you are getting an error.

I have assigned this issue to a team to advise you on resolving the error.

Thank you.

**Comment by DanielTech21** [comment]
@randy75828 
Can you please provide your MetaMask and browser version?

**Comment by bschorchit** [comment]
I can't repro the issue on v12.8.0

**Comment by randy75828** [comment]
Oh great, updated to v12.8.0 and it works too! Would wanna ask is `eth_decrypt` still supported for mobile too?

**Comment by bschorchit** [comment]
Awesome, @randy75828 ! We support it only on extension. 

Closing this ticket as the issue has been fixed.

**Comment by randy75828** [comment]
hi can i also check is there any hard deadline where metamask will be removing eth_decrypt entirely?

**Comment by bschorchit** [comment]
Hey @randy75828, we don't have a hard deadline to share at moment.
