### ISSUE TITLE
[Bug]: TypeError: Cannot convert undefined or null to object (AssetListControlBar)

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-extension#28882]
### Describe the bug

Uncaught TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>) at asset-list-control-bar.tsx:102:16

I have found this bug to be present in the MetaMask Extension main branch (currently @ v12.7.2)
It occurred for me when I was testing an unrelated feature and switching from v12.5.0 => 12.7.2 in order to trigger migrations.

Upon swapping out the extension code and re-enabling the extension, refreshing and logging in, this error is encountered and a dialogue is displayed:
![image](https://github.com/user-attachments/assets/d8e7b302-8d17-4224-a956-a592a61f9434)

### Expected behavior

When logging in I should not see this dialogue as a user.

### Screenshots/Recordings

https://github.com/user-attachments/assets/6b0ccd96-a807-419c-9ad5-d64f93de3bb9

### Steps to reproduce

1. Load v12.5.0 and run yarn & yarn webpack:
```
git checkout tags/v12.5.0
yarn 
yarn webpack
```
2. Load Unpacked from the `/dist/chrome` and log into MetaMask
(It should not matter if you choose to enable STX or NOT (unrelated))
3. Toggle off MetaMask in Extension Manager
4. Delete the `/dist` directory and run:
```
git checkout main 
git pull
yarn 
yarn webpack
```
5. Open Extension Details
6. Toggle on MetaMask Extension
7. Refresh Extension
8. Launch MetaMask Extension
9. Log In and you will see “MetaMask Encountered an Error” dialogue
10. Right click and inspect on the error 

You will see the associated error related to `asset-list-control-bar.tsx`:102
Click on the link in the top right to be taken to line 102 in that component’s code where the issue originated from

### Error messages or log output

```shell
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at asset-list-control-bar.tsx:102:16
    at commitHookEffectList (react-dom.development.js:22030:26)
    at commitPassiveHookEffects (react-dom.development.js:22064:11)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385:16)
    at invokeGuardedCallback (react-dom.development.js:440:31)
    at flushPassiveEffectsImpl (react-dom.development.js:25392:7)
    at unstable_runWithPriority (scheduler.development.js:697:12)
    at runWithPriority$2 (react-dom.development.js:12149:10)
```

### Detection stage

On the development branch

### Version

12.7.2

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

I ensured that it was not related to my own changes by checking out the main branch and trying to reproduce and had success in encountering the error again.

The repro steps are only the way I found the bug and I feel that it could be encountered in other ways  also, but have not tested any other repro steps.

### Severity

- I believe that this bug could be encountered outside of my repro steps and could potentially impact  many users that are receiving an updated version and I have noticed it when switching from various older versions to `12.7.1` and `12.7.2`

**Comment by sleepytanya** [comment]
I couldn't reproduce when going from 12.7.2 to `main` (using `webpack`)
Reproduce consistently when upgrading 12.5.0 to `main` with the same error message:


<img width="358" alt="Screenshot 2024-12-03 at 17 00 24" src="https://github.com/user-attachments/assets/a5138b6a-0caa-43d4-9865-5cf141eb5b01">

<img width="582" alt="Screenshot 2024-12-03 at 17 03 29" src="https://github.com/user-attachments/assets/ce01d86d-3713-4f67-af3c-08a10d17edfc">



https://github.com/user-attachments/assets/0545e258-4c3d-4045-9022-757dc05275a6

**Comment by httpJunkie** [comment]
> I couldn't reproduce when going from 12.7.2 to main (using webpack)

Did you mean `12.7.1` to `main`?

**Comment by sahar-fehri** [comment]
Hello @httpJunkie ! Could you verify that this https://github.com/MetaMask/metamask-extension/pull/28870 fixes the issue? 🙏

**Comment by sahar-fehri** [comment]
I have pushed changes to the [PR](https://github.com/MetaMask/metamask-extension/pull/28870); it should now fix this issue 🙏
