### ISSUE TITLE
Missing options on my MetaMask extension

### ISSUE THREAD

**Issue by hetchz** [MetaMask/metamask-extension#2890]
Hello Support, I noticed some missing features of MM on my chrome extension while watching a youtuber demoing it.. so would like to report it as i believe it's a bug and couldn't find any similar topics in GitHub mention about it.. (as far as i did my research)

Thanks to let me know if you've seen similar reporting of the same issue.
Hesham

![image](https://user-images.githubusercontent.com/33793150/34651617-429d0990-f3db-11e7-9b85-f177d0c7763d.png)

![image](https://user-images.githubusercontent.com/33793150/34651639-6b37ca2a-f3db-11e7-8cdc-97dc0ff95498.png)

**Comment by tmashuang** [comment]
There have been many iterations of MetaMask since the first image. The icons have been turned into text of their functions and moved to a drop down menu when clicking the ellipsis, three dots, icon of the  second image.
