### ISSUE TITLE
[Bug]: An alert warning is displayed to users about their first-time interaction with an account, even for accounts that are owned and contained within the wallet

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#28942]
### Describe the bug

Currently, an alert `You're interacting with this address for the first time. Make sure that it's correct before you continue.` is displayed for accounts within the wallet. 

### Expected behavior

This alert should be reserved for external accounts. 

### Screenshots/Recordings

https://github.com/user-attachments/assets/ca3f18f2-02b0-4c19-b592-9127b09035af

<img width="542" alt="Screenshot 2024-12-04 at 16 20 45" src="https://github.com/user-attachments/assets/af2e75b9-995d-4141-ab4e-e58c15404101">

### Steps to reproduce

1. Have several accounts in the wallet
2. Send a transaction to one of your accounts

### Error messages or log output

```shell
-
```

### Detection stage

During release testing

### Version

12.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
Great catch, Tanya! I missed that scenario. @OGPoyraz can we skip this alert if the user is sending to one of its own accounts?
