### ISSUE TITLE
Transaction - handle case where estimateGas fails

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#2898]
ended up with suggested gasLimit of 0

**Comment by danfinlay** [comment]
Simulating situations where Infura returns a 403 error in response to estimateGas.

We could either:
- Transition tx to "failed" state and return an error to the dapp
- Auto-fill a default (> 21k gas) with a warning that estimate failed, submit at caution. Needs good copy/language for that warning.

Either one could hold us over for now.
