### ISSUE TITLE
[Bug]: Flaky ` test/integration/confirmations/transactions/` tests

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#29002]
### Describe the bug

We have seen two instances where two separate integration tests, both under `./test/integration/confirmations/transactions/`, have failed during the same run with a timeout.

### Expected behavior

No flaky test failures.

### Screenshots/Recordings

Here are the examples:

* https://github.com/MetaMask/metamask-extension/actions/runs/12187544885/job/33998568985
* https://github.com/MetaMask/metamask-extension/actions/runs/12190403069/job/34007448448

### Steps to reproduce

N/A

### Error messages or log output

```shell
FAIL test/integration/confirmations/transactions/increase-allowance.test.tsx (64.074 s)

ERC20 increaseAllowance Confirmation › displays spending cap request title

    thrown: "Exceeded timeout of 10000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."



...


FAIL test/integration/confirmations/transactions/alerts.test.tsx (63.327 s)

...
(approximately 1 million console errors)
...
Contract Interaction Confirmation Alerts › displays the alert when network is busy

thrown: "Exceeded timeout of 10000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
```

### Detection stage

On the development branch

### Version

develop

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by cryptotavares** [comment]
This might have been a side effect of the lazy loading PR - https://github.com/MetaMask/metamask-extension/pull/28172/files#diff-01d6f6eed529f687257cd520459561f1b588b5992048f7dc31f8068e70418641R28

I'll open a PR to improve current tests (example too many logs due to propTypes or even the Ganache ones when we are stubbing the provider) and will think about a way to better address the lazy loading effects (besides increasing the test timeout)

**Comment by cryptotavares** [comment]
We have increased test timeout to 15s. Besides We have opened a [PR](https://github.com/MetaMask/metamask-extension/pull/29007) to tone down some of the logs that we were outputting in the Integration tests.
