### ISSUE TITLE
[Bug]: Infinite Load after upgrade to `12.9.0`

### ISSUE THREAD

**Issue by pcaversaccio** [MetaMask/metamask-extension#29055]
### Describe the bug

I just updated to the latest version `12.9.0` and it keeps loading forever when I log in. Before you ask, yes I cleared the cache, yes I restarted the browser, yes I checked that it's the correct MetaMask version. Previously I had no such issue.

![Image](https://github.com/user-attachments/assets/71c957d0-fa7b-4e02-8040-4c40a0e2b345)

### Steps to reproduce

1. Upgrade to latest MetaMask version and try log in

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.9.0

### Build type

None

### Browser

Microsoft Edge

### Operating system

Windows

**Comment by pcaversaccio** [comment]
Guys, that release is fucked up. After 5mins I got to the main screen finally. I can't switch chains (it doesn't react), if I click again on the MetaMask pop it gets me this forever
![Image](https://github.com/user-attachments/assets/009c8a59-40e9-4099-aa13-56b9ff92bc95)

**Comment by pcaversaccio** [comment]
Adding a network is now taking 2 mins...

![Image](https://github.com/user-attachments/assets/60b3d0af-f488-49ab-8716-786a64cf4813)

**Comment by DanielTech21** [comment]
Hi @pcaversaccio 

Thank you for reporting it to us.

Our team will look into this and get back to you.

**Comment by danjm** [comment]
@pcaversaccio Could you open the developer console and check if there are any errors?

**Comment by pcaversaccio** [comment]
yeah there are some errors indeed (probably from the RPC, haven't checked so far): [debug.log](https://github.com/user-attachments/files/18082933/debug.log)

**Comment by danjm** [comment]
thanks, we are investigating

**Comment by danjm** [comment]
there are definitely some RPC errors. Are you able to change RPCs?

Also, did you have a large number of accounts added to your metamask install?

**Comment by danjm** [comment]
okay, that's useful to know

**Comment by pcaversaccio** [comment]
Example: When I change the network from Linea Infura to Ethereum Mainnet Infura it takes around 25-30s.

**Comment by danjm** [comment]
We are actively investigating, but something you could try in the meantime that might alleviate the problems you are seeing:

On the "Tokens" tab on the home screen, there is a new dropdown that says "All Networks". Click the dropdown and select something other than "All networks". Example video here:

https://github.com/user-attachments/assets/2d9bcf91-c4ab-4a44-8e72-d9c66d5831c3

Can you try that and let us know whether it improves things for you?

**Comment by pcaversaccio** [comment]
> We are actively investigating, but something you could try in the meantime that might alleviate the problems you are seeing:
> 
> On the "Tokens" tab on the home screen, there is a new dropdown that says "All Networks". Click the dropdown and select something other than "All networks". Example video here:
> 
>  Screencast.2024-12-10.14.19.04.mp4 
> Can you try that and let us know whether it improves things for you?

This is what happens when I do it first

![Image](https://github.com/user-attachments/assets/1e5baf4a-bcb5-4b6b-b600-7cd7013a17f1)

after I reloaded crashed again, and the third time it worked but not really faster tbh.

**Comment by danjm** [comment]
okay, thank-you again for the info you are sharing. It is very helpful

**Comment by danjm** [comment]
Now that you switched away from that "All Networks" setting, you may need to reload the extension to correct performance. To do so, you can go to chrome://extensions, and toggle MetaMask on and off (using the blue toggle in the bottom right corner of the box that contains metamask)

![Image](https://github.com/user-attachments/assets/f881bd02-bd70-46e2-bf7a-d315c9ce38f2)

**Comment by pcaversaccio** [comment]
> Now that you switched away from that "All Networks" setting, you may need to reload the extension to correct performance. To do so, you can go to chrome://extensions, and toggle MetaMask on and off (using the blue toggle in the bottom right corner of the box that contains metamask)
> 
> ![Image](https://github.com/user-attachments/assets/f881bd02-bd70-46e2-bf7a-d315c9ce38f2)

Alright - this makes it definitely work again as previously (almost). But that "All Networks" tab breaks really everything for me...
