### ISSUE TITLE
Add "Remove Token" button to token list items

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2910]
To allow users to un-track tokens they used to have.

**Comment by manuelpaulo** [comment]
Any update? Thanks.

**Comment by danfinlay** [comment]
We have a new UI coming out soon, which already features token removing, so we may not add it to the current UI, and just let the new UI handle this when it's out later this month.

**Comment by mgladden2** [comment]
Looking forward to being able to delete clutter token entries in the new UI!

**Comment by Freydal** [comment]
I was impatient and used the info [here](https://github.com/MetaMask/metamask-extension/issues/2749) to just manually edit out the tokens I needed to go away.  I am (not so)patiently awaiting a better solution!

**Comment by glaksmono** [comment]
Looking forward for this! 👍

**Comment by danfinlay** [comment]
This has been added in the new UI, to try it out, you can click "Try Beta!" in the top right corner of MetaMask. New features are appearing in there, and eventually we will roll it out as our primary interface.
