### ISSUE TITLE
payment for transactions (GAS)

### ISSUE THREAD

**Issue by Pickles89** [MetaMask/metamask-extension#2916]
Hello!
When transferring from the deposit Etherdelta to the wallet, the transaction occurs from the wallet to the wallet!
Also, the payment for the transaction(GAS) does not happen with the wallet chosen by default!
![12](https://user-images.githubusercontent.com/35285833/34757262-15a67cc0-f5e1-11e7-86b5-e8777bb2293b.jpg)

**Comment by tmashuang** [comment]
This is how Etherdelta functions. They hold funds in their smart contract, the address that it is the recipient, makes a call and transfers funds.

**Comment by Pickles89** [comment]
You did not understand me!
transaction does not happen with a deposit !!!! the transaction is made from a wallet Myetherwallet  to wallet Metamask!!!!! so it should not be! This is NOT the operation I want to do! I want withdraw token with deposit etherdelta to my wallet! it works this way!

**Comment by Pickles89** [comment]
you have an error in the code when using several wallets:
1. transactions with deposits, the wallet is misused
2. payment for the transaction(gas), is not collected from the wallet  by default, if it is not a wallet metamask
