### ISSUE TITLE
[Bug]: Assets - Watching multiple NFTs displays navigation header in the UI which is broken as everything is consolidated in 1 screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#29189]
### Describe the bug

Watching multiple NFTs opens 1 UI screen with everything consolidated, however now there's a navigation header which appears on top, and it is broken, which is expected since in reality it's only 1 UI screen consolidating all assets

### Expected behavior

If we are trying to watch for multiple assets, that's consolidated in 1 screen, so we shouldn't display the navigation header, as it's just 1 screen?

### Screenshots/Recordings

https://github.com/user-attachments/assets/95af2f3a-5029-4458-8f6d-4df0dad4bf04

https://github.com/user-attachments/assets/63a889be-d6dd-4c29-a177-bb65f80a5e76

This is current prod 12.9.1, where there' s no navigation header:

![Image](https://github.com/user-attachments/assets/683f5716-3f6f-40dc-9b62-cdfe66d35d9d)

### Steps to reproduce

1. Go to the test dapp
2. Deploy an ERC721 contract
3. Mint some tokens
4. Watch multiple assets (or Watch all assets)
5. See how the notification number increases, but you cannot navigate to the different screens since everything is aggregated to 1 screen

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.10.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by sleepytanya** [comment]
Fixed:


https://github.com/user-attachments/assets/c0598ced-5429-48d5-99a9-ecc35aaf9124

**Comment by cryptotavares** [comment]
RCA: https://www.notion.so/metamask-consensys/Bug-Assets-Watching-multiple-NFTs-displays-navigation-header-in-the-UI-which-is-broken-as-everyt-185f86d67d68802b9b2cf1b66f618364

FYI @vpintorico @jvbriones
