### ISSUE TITLE
Injecting Metamask Web3 into an extension

### ISSUE THREAD

**Issue by macbem** [MetaMask/metamask-extension#2919]
Is it possible to use MetaMask from within another web extension? I need to create a browser extension that will handle Ethereum payments and I'd like to use MetaMask for that.

**Comment by tmashuang** [comment]
I do not believe so, seems Chrome prevents this type of behavior for security reasons.

**Comment by zgallagher08** [comment]
Is this still impossible? What about using background.js to fetch the web3 instance?

**Comment by Powersource** [comment]
There's recently been added a way to do this https://github.com/MetaMask/metamask-extension/issues/4577
