### ISSUE TITLE
[Bug]: Whenever an NFT is sent through the Send flow, a console message appears: TypeError#24:Cannot read properties of undefined (reading 'scrollTo').

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#29226]
### Describe the bug

Whenever an NFT is sent through the Send flow, a console message appears: TypeError#24:Cannot read properties of undefined (reading 'scrollTo').

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/6d003400-f0cc-48bd-a102-a96702603e64

<img width="641" alt="Image" src="https://github.com/user-attachments/assets/d2e756cd-03d9-4e1a-9f23-f81d0566d906" />

### Steps to reproduce

1. Send an NFT from the Send flow

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

v12.10.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by DDDDDanica** [comment]
Fixed: https://github.com/MetaMask/metamask-extension/pull/29386
