### ISSUE TITLE
[Bug]: Wrong account information being sent to snap.

### ISSUE THREAD

**Issue by gdoteof** [MetaMask/metamask-extension#29221]
### Describe the bug

Metamask seems to force me to create an in-memory private key rather than let me start with a hardware wallet.

After creating the in-memory mnemonic, I am able to create a hardware wallet.  After creating a QR code wallet (keystone), i install the shapeshift multi-chain snap, and connect only the hardware wallet, not the undeletable hot private key account. 

The ethereum based addresses are correct, but the the thorchain (maybe others) are incorrect.

I thought at first perhaps it was a different derivation path, but after testing a transaction, it is clear that the xpub from the hardware wallet is completely ignored and, silenetly, the thorchain address is tied to the unauthorized private key. 

### Expected behavior

Use the hardware wallet.  Don't even allow in-memory private keys, or at least allow creating a wallet without one.

### Steps to reproduce

1.  Install fresh metamask plugin>
2.  Generate new hot wallet.
3.  Add a hardware wallet, QR code.
4.  Add shapeshift snap, and connect the hardware wallet.  do NOT connect hot wallet
5.  Check receiving thoraddress.
6.  Observe it is derived from the hot wallet that is not authorized, and the xpub hardware wallet is ignored.

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.9.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

Keystone

### Severity

I would consider this pretty critical.  I was forcec to create an insecure wallet but didn't back up any of the information.  Then after connecting the hardware wallet, I thought i had secured my funds, but i had actually sent funds to a throwaway private key.

**Comment by Anitasmith0072** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action and resolve this.

Please write to us using the “Chat Support” icon located on the [Metamask Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by DanielTech21** [comment]
Hi @gdoteof 

Thank you for bringing this to our attention.  

Our team will review it and provide you with more information soon.

**Comment by Montoya** [comment]
Hi @gdoteof 

Snaps can only derive accounts from the default SRP. They cannot derive accounts from other sources of entropy like a hardware device or an imported account.

**Comment by gdoteof** [comment]
@Montoya I hope that is internally recognized as insufficient.  Encouraging people to use hot wallets like that is incredibly irresponsible.
