### ISSUE TITLE
[Bug]: Personal Sign - Address cannot be recovered when the personal sign message includes a number

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#29220]
### Describe the bug

My address cannot be recovered when I use the personal_sign method for signing a message which contains a number. Ie `'Example 123'`

### Expected behavior

Either fix recovery or not support this type of message

### Screenshots/Recordings

https://github.com/user-attachments/assets/bec9fa2e-3984-402d-a9de-6a60cffeb12f

### Steps to reproduce

1. Checkout the test dapp locally
2. Change the personal message to 
3. Run the dapp locally
4. Connect
5. Click Personal Sign
6. Accept singature in MM
7. Click Verify
8. See recovered addresses do not match in the console log

```
  personalSign.onclick = async () => {
    const exampleMessage = 'Example 123';
    try {
      const from = accounts[0];
      const msg = `0x${Buffer.from(exampleMessage, 'utf8').toString('hex')}`;
      const sign = await provider.request({
        method: 'personal_sign',
        params: [msg, from, 'Example password'],
      });
      personalSignResult.innerHTML = sign;
      personalSignVerify.disabled = false;
    } catch (err) {
      console.error(err);
      personalSign.innerHTML = `Error: ${err.message}`;
    }
  };


```

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.9.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Severity

Not sure how often this method is used, but it seems between a sev2-sev1, leaving it up to the Confirmations team to finish the assessment

**Comment by jpuri** [comment]
I tried it and it does seems to work, we need to change message in both sign and verify functions.

https://github.com/user-attachments/assets/10d81466-afd7-4add-8287-8be1c2dd1ca3
