### ISSUE TITLE
Need help with selling and buying, says not enough gas fee while i have enough in my wallet and on etherdelta tried with 34 gas fee

### ISSUE THREAD

**Issue by tripzwam** [MetaMask/metamask-extension#2923]
Need help with the following, cannot buy and sell, deposit and withdraw. also tried to download chrome and metamask several times. this is my log: 
{
  "metamask": {
    "isInitialized": true,
    "isUnlocked": true,
    "isMascara": false,
    "rpcTarget": "https://rawtestrpc.metamask.io/",
    "identities": {
      "0x3cfc5022811d6bd8c13401296937b081cde07663": {
        "address": "0x3cfc5022811d6bd8c13401296937b081cde07663",
        "name": "Account 1"
      }
    },
    "unapprovedTxs": {},
    "noActiveNotices": true,
    "frequentRpcList": [],
    "addressBook": [],
    "tokenExchangeRates": {},
    "coinOptions": {},
    "provider": {
      "type": "mainnet",
      "rpcTarget": "https://mainnet.infura.io/metamask"
    },
    "network": "1",
    "accounts": {
      "0x3cfc5022811d6bd8c13401296937b081cde07663": {
        "balance": "0x156ca5432007a00",
        "address": "0x3cfc5022811d6bd8c13401296937b081cde07663"
      }
    },
    "currentBlockGasLimit": "0x79f379",
    "selectedAddressTxList": [
      {
        "id": 1931699612964624,
        "time": 1515612158649,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x3cfc5022811d6bd8c13401296937b081cde07663",
          "to": "0x8d12a197cb00d4747a1fe03395095ce2a5cc6819",
          "value": "0x0",
          "data": "0x2e1a7d4d00000000000000000000000000000000000000000000000002307380a0dfd880",
          "gas": "0x3d090",
          "gasPrice": "0xee6b2800",
          "nonce": "0x9",
          "chainId": "0x1"
        },
        "gasPriceSpecified": true,
        "nonceSpecified": true,
        "gasLimitSpecified": true,
        "estimatedGas": "0x3d090",
        "history": [
          {
            "id": 1931699612964624,
            "time": 1515612158649,
            "status": "unapproved",
            "metamaskNetworkId": "1",
            "txParams": {
              "from": "0x3cfc5022811d6bd8c13401296937b081cde07663",
              "to": "0x8d12a197cb00d4747a1fe03395095ce2a5cc6819",
              "value": "0x0",
              "data": "0x2e1a7d4d00000000000000000000000000000000000000000000000002307380a0dfd880",
              "gas": "0x3d090",
              "gasPrice": "0xee6b2800",
              "nonce": "0x9"
            },
            "gasPriceSpecified": true,
            "nonceSpecified": true,
            "gasLimitSpecified": true,
            "estimatedGas": "0x3d090"
          },
          [],
          [
            {
              "op": "replace",
              "path": "/status",
              "value": "approved",
              "note": "txStateManager: setting status to approved"
            }
          ],
          [
            {
              "op": "add",
              "path": "/nonceDetails",
              "value": {
                "params": {
                  "highestLocalNonce": 0,
                  "highestSuggested": 9,
                  "nextNetworkNonce": 9
                },
                "local": {
                  "name": "local",
                  "nonce": 9,
                  "details": {
                    "startPoint": 9,
                    "highest": 9
                  }
                },
                "network": {
                  "name": "network",
                  "nonce": 9,
                  "details": {
                    "baseCount": 9
                  }
                }
              },
              "note": "transactions#approveTransaction"
            }
          ],
          [
            {
              "op": "add",
              "path": "/txParams/chainId",
              "value": "0x1",
              "note": "txStateManager: setting status to signed"
            },
            {
              "op": "replace",
              "path": "/status",
              "value": "signed"
            }
          ],
          [
            {
              "op": "add",
              "path": "/rawTx",
              "value": "0xf8880984ee6b28008303d090948d12a197cb00d4747a1fe03395095ce2a5cc681980a42e1a7d4d00000000000000000000000000000000000000000000000002307380a0dfd88026a0ba451416971308d35dc22384a3490797701f4a4218328c4c9e003930f7835871a01cb29647293f0d419904523932121d4672c7eafd6a0ce50d022a741091c4b721",
              "note": "transactions#publishTransaction"
            }
          ],
          [
            {
              "op": "add",
              "path": "/err",
              "value": {
                "message": "Error: [ethjs-rpc] rpc error with payload {\"id\":1728716206750,\"jsonrpc\":\"2.0\",\"params\":[\"0xf8880984ee6b28008303d090948d12a197cb00d4747a1fe03395095ce2a5cc681980a42e1a7d4d00000000000000000000000000000000000000000000000002307380a0dfd88026a0ba451416971308d35dc22384a3490797701f4a4218328c4c9e003930f7835871a01cb29647293f0d419904523932121d4672c7eafd6a0ce50d022a741091c4b721\"],\"method\":\"eth_sendRawTransaction\"} Error: transaction underpriced",

**Comment by tmashuang** [comment]
The transaction with the same nonce as the logs shows it is still pending. https://etherscan.io/tx/0xa212c6db6aa646ee458c6209637652d208d0345e38a4e1bdd44387ff6d8522ca.
Creating the same transaction does not expedite the transaction. I assume you have reset your transaction log of the original transaction during reinstalling with prevents the 'Retry with higher gas price' feature for the transaction. There is no immediate resolution, other than to wait for the transaction to be processed.

**Comment by tripzwam** [comment]
Also tried yesterday and day before

**Comment by tripzwam** [comment]
Than iT also did not work
