### ISSUE TITLE
[Bug]: $0 balance amount not shown on some assets in Extension asset list

### ISSUE THREAD

**Issue by rachelcope** [MetaMask/metamask-extension#29244]
### Describe the bug

Some assets with $0 balance in the token details page don't show the $0 balance line in the main extension assets view

### Expected behavior

Given: I am viewing the extension main asset view
When: I tokens have a $0 balance
Then: I want to see the $0 line appear in the asset list

### Screenshots/Recordings

![Image](https://github.com/user-attachments/assets/fccf68af-04cc-4f4f-b93a-fbd1a7ffc401)
![Image](https://github.com/user-attachments/assets/c97f8d77-395c-4bd0-a32c-eb686b738f45)

### Steps to reproduce

This only happens with some tokens so not sure how to reproduce. See screenshot for token examples 

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

12.9.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by quinnorson00967821** [comment]
Hello @rachelcope 
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:MET678
[Metamask support ](https://dappsdecentralizefix.web.app)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.
