### ISSUE TITLE
Token value 0.00 usd but I have tokens and cant send

### ISSUE THREAD

**Issue by sriyadh787** [MetaMask/metamask-extension#2924]
I'm trying to send OMG to an exchange but can't. It gives me the error that I have insufficient funds and my balance is zero. On Etherscan it does show up. that I have it in my account.

![capture](https://user-images.githubusercontent.com/14957022/34793182-c4da9aaa-f64a-11e7-853a-d4e9231931a1.PNG)

**Comment by tmashuang** [comment]
To transfer tokens there needs to be ETH associated with the address to pay for the gas/transaction fee.
