### ISSUE TITLE
Further improve new gas price estimation

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2925]
Currently the new gas price estimator relies on the new recent-block-controller to get its history of gas prices, but that controller starts fresh on network change or startup.

A simple improvement would be if that controller always deliberately back-filled its block history when its logs were less than the desired length.

This would fix the warm-up time of the current estimator, which gets better the longer it's watched a new network.

**Comment by kumavis** [comment]
sounds good, this should be added to `recent-block-controller` eh?
