### ISSUE TITLE
Struggle to deposit from metamask to etherdelta - metamask account lost?!

### ISSUE THREAD

**Issue by jdn-za** [MetaMask/metamask-extension#2934]
So right off the bat:

- I have search through every open and closed issue and tried all methods to recover my account from my seed words without any luck.
- I created a metamask account a few days ago and have the following information saved: **seed words**, **password**, **public address**
- I had 3 accounts in this metamask account (0x9b0d8FA89D8B978502798f35Ba50eeeF2b70C635 was account 1)
- unfortunately I _**DO NOT**_ have the private key (forgot to export it, I assumed that recover was possible with seed words) =\
- I am 100% sure I didnt create an etherdelta account as I transferred from coinbase before I had even opened etherdelta
- I have tried to recover using jaxx and I get the new account number not the old.

Earlier today I transferred ETH from coinbase to my Metamask wallet **0x9b0d8FA89D8B978502798f35Ba50eeeF2b70C635** and saw the transaction go through just fine [as per here](https://www.etherchain.org/account/9b0d8FA89D8B978502798f35Ba50eeeF2b70C635)

I tried to then deposit several times into ether delta without any luck, errors about not enough eth or gas price (the site was under load and was lagging out pretty badly. Suspecting maybe an issue with Chrome I installed metamask on Firefox. 

On Firefox I recovered account with the seed words and used the same password as I had previously used, right off the bat I noticed that the account number was different (**0xAB2CfAD5f3285B75070Ec8994c2eA3b4f5225765**) and ofcorse balance 0.

I then after reading github issues in a panic uninstalled and reinstalled metamask from both chrome and firefox and recovered the account with seed words. The recovered accounts always end up with account 1 as **0xAB2CfAD5f3285B75070Ec8994c2eA3b4f5225765**

So I mean I guess fortunately it was a small amount of eth I transferred, I did 0.00631 as a first test and 0.09111 as a second.

Did I some how overwrite the wallet, if there any way to recover it?

**Comment by Zanibas** [comment]
Are there any words that you may have potentially misspelled?

**Comment by jdn-za** [comment]
I wish, I used an password store and have checked for copy paste special chars.

The seed words also DID restore several times just not with the account number I need o.O?

**Comment by Zanibas** [comment]
Could you please clarify what you mean that they restored several times? Also, when you transferred your seed words to your password store, did you do this as a copy-paste straight from MetaMask?

**Comment by jdn-za** [comment]
I did copy directly from meta mask yes.

I have restored from seed words on another browser, on two other PC's (two browsers per) and to Jaxx, so not special char's messing it up is what I meant

**Comment by jdn-za** [comment]
Also went and checked all version of the metamask entry history I have in 1password and it has never been different to what I have currently

**Comment by jdn-za** [comment]
shit well I guess that is gone then?

that is a let down =\

Just  thought, is there nay way to validate if the address **0x9b0d8FA89D8B978502798f35Ba50eeeF2b70C635** was created by metamask?
