### ISSUE TITLE
I also lost ETH

### ISSUE THREAD

**Issue by JeanClaude66** [MetaMask/metamask-extension#2939]
Hello

I just used MetaMask for the first time.
I am also on mac using chrome.

I Sent two packets of 0.15 and 0.045 ETH but I never received them I Kucoin.

It was sent from my address:
0x750C66208222f7cAd3D965753CcaABC55F108305
To this address:
0xc7142c5e65c5caf0e3edcb2ba58307c0b67ab931

Several hours after my Kucoin account is still empty.
when I clik on the MetaMask operation I have this error:
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

How can this happen?
Please help!
Thanks,
JC

![screen shot 2018-01-12 at 1 23 22 am](https://user-images.githubusercontent.com/35353035/34854433-fb2ccfe8-f739-11e7-8203-22f943278ca6.png)

![screen shot 2018-01-12 at 1 44 06 am](https://user-images.githubusercontent.com/35353035/34854480-3cbd6850-f73a-11e7-826f-137650ab36ed.png)

**Comment by tmashuang** [comment]
Seems that at the time the issue was open the transaction was still pending. I reviewed the addresses and transaction on a block explorer and seems the transactions were successful. The 404 error was with Etherscan which was having issues with their site at the time.

**Comment by JeanClaude66** [comment]
Hello
Thanks Tom.
CheersJC Jean Claude RICQUEBOURG

IMDB:http://www.imdb.me/jeanclaudericquebourgWeb: Facebook oficial
Blog: http://jeanclaudericquebourg.blogspot.com
Mobile: + 34 687 431 253 
Home tel: + 34 933771746 

    On Monday, January 15, 2018 6:16 PM, Thomas Huang <notifications@github.com> wrote:
 

 Seems that at the time the issue was open the transaction was still pending. I reviewed the addresses and transaction on a block explorer and seems the transactions were successful. The 404 error was with Etherscan which was having issues with their site at the time.—
