### ISSUE TITLE
MetaMask not work properly with Ganache

### ISSUE THREAD

**Issue by alvarofvr** [MetaMask/metamask-extension#2941]
Hi guys i have a problem when i try to work with [Ganache](https://github.com/trufflesuite/ganache) and MetaMask togheter.
Sometimes when i restart Ganache and try to make a simple test transaction with **MetaMask** extension for **Firefox Developer Edition 58.0b15 (64 bit)** connected on the custom RPC network created by Ganache on 127.0.0.1:7545 it not works and transaction fail with this log error:

![immagine](https://user-images.githubusercontent.com/13423318/34872248-8958acdc-f790-11e7-9f15-fe5b4c66a7cb.png)

If i uninstall and reinstall MetaMask extension and reconfigure custom RPC network on Ganache with the same configs (127.0.0.1:7545) it starts to work.
But when i restart Ganache the problem reoccurs and so on.
In Metamask I also tried to change the network on another and then return to custom RPC becouse i hope in a refresh of the wallet but nothing, the only way to work when restart Ganache is uninstall the extension and reinstall. Any way to fix this?

**Comment by benjamincburns** [comment]
@alvarofvr please don't double post. This issue duplicates #1999.

**Comment by tmashuang** [comment]
Closing in favor of #1999.
