### ISSUE TITLE
[Bug]: Infinte Loading when entering password for Metamask in Firefox after Update

### ISSUE THREAD

**Issue by v0dev** [MetaMask/metamask-extension#29416]
### Describe the bug

I updated Firefox extension to the latest release (12.6.2), and it ended up causing an infinite loop when entering password and clicking next. The previous version which was running was from July, 2024 (unsure of the exact version), was working fine.

 

### Expected behavior

Entering password unlocks the wallet and allows using it.

### Screenshots/Recordings

![Image](https://github.com/user-attachments/assets/2d54f6ff-494c-475d-a74c-70e2be396f27)
![Image](https://github.com/user-attachments/assets/0ad19a83-e6dd-4667-ac82-7dca46c090d5)

### Steps to reproduce

1. Update/Install the Metamask Wallet and try to login

### Error messages or log output

```shell
Content-Security-Policy: The page’s settings blocked a JavaScript eval (script-src) from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'” (Missing 'unsafe-eval') runtime-lavamoat.js:10422:15
Content-Security-Policy: The page’s settings blocked a JavaScript eval (script-src) from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'” (Missing 'unsafe-eval') runtime-lavamoat.js:4525:30
```

### Detection stage

In production (default)

### Version

12.6.2

### Build type

None

### Browser

Firefox

### Operating system

Windows

### Additional context

I also noticed version on Firefox is alot older than on chrome , on Firefox the version is at 12.6.2 and on chrome its 12.9.x

**Comment by seaona** [comment]
hi there @v0dev, thank you for your report. This is a known issue and we are working on a fix. In the meantime, could you close your Firefox browser (all windows) and re-open it again and see if that fixes the issue for you?

**Comment by v0dev** [comment]
Hi @seaona ,

This workaround seems to be working for the time being after a few tries of restarting and then disabling and enabling the extension, I was able to use the wallet. I will close this Issue , as it seems to be duplicate of https://github.com/MetaMask/metamask-extension/issues/29302.

**Comment by seaona** [comment]
thank you @v0dev 🙏 glad to hear the workaround works for you, in the meantime!
