### ISSUE TITLE
Cant access metamask account after updating and agreeing to new terms and conditions

### ISSUE THREAD

**Issue by tonysharks** [MetaMask/metamask-extension#2942]

**Comment by tonysharks** [comment]
cant seem to locate my original account. it has given me a whole new account. I only have the password to the original account. Cant seem to locate the 12 word seed phrase. Is there anything i can do to fix this or im i out of luck? i would be very appreciative if someone can guide me in the right direction, if there is any hope of recovering. Thanks!

**Comment by tmashuang** [comment]
Seed words are the primary way to restore MetaMask vaults. If you have the private key for a single account, you can also import it as a Imported Account. This will then be the primary way to restore every time.
