### ISSUE TITLE
Lost my cat in metamask ! 

### ISSUE THREAD

**Issue by Ryuu92** [MetaMask/metamask-extension#2943]
Hi, 

I have sent my bitclave ( CAT ) on metamask, the tokens were here, everything was good ( 2523 if my memory is on point ) on the address 0x4C48A85A6898600F7070FBB614849fA2Ef71E974 ( they are still here )

Yesterday, I was connected on my metamask account and my address had changed, 0x288F7ae5F79D0BF9372CC9A124B02c638E54ec39 for this one. This is the SAME ACCOUNT with the SAME 12 key mnemonic phrase and the SAME PASSWORD. But in this one, there's no token. 
I don't have the private key, I dont know if I have the same right now than the one I got with the older address ( because the actual one, yes, I exported it, but there's nothing inside this account )

I have tried to add the contract address like I did in the older one, but nothing. I tried to check it out in MEW with my 12 words phrase, nothing. Like my address is on another account I dont have. 
And on my metamask menu, there's only one account. 

I don't know what to do, please help me

**Comment by jdn-za** [comment]
This is exactly like the issue I had https://github.com/MetaMask/metamask-extension/issues/2934

I am busy trying to do a HDD recovery of the chrome extension to see if I can use the vault Decrypter  on it https://metamask.github.io/vault-decryptor/

will let you know if I find resolution.

**Comment by Ryuu92** [comment]
Thanks a lot mate

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jazzinuf** [comment]
i have the same issue. Does anyone have any idea what is happening?

**Comment by Ryuu92** [comment]
Currently in conversation with the metamask support, I still don’t have the answer

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bdresser** [comment]
@Ryuu92 try clicking "Create Account," which creates the same accounts you used to have in the same order. Lots of explainers in our [support site](https://consensys.zendesk.com/hc/en-us/categories/360000441452-Using-MetaMask) as well. 

If you need more help from support@metamask.io, please ping again and mention this issue number. Closing this because we use this board for bugs or feature requests, not specific user help issues. Hope that helps!

**Comment by martineezz** [comment]
@jazzinuf 
@Ryuu92 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
