### ISSUE TITLE
Changing Password Does Not Change On All Browsers

### ISSUE THREAD

**Issue by adam2392** [MetaMask/metamask-extension#2949]
I wanted to test the security of the passcode if say I messed up my computer / had it stolen and I set up a new passcode for metamask on a different browser.

Setup:
1. create passcode for google chrome
2. use secret keys to access and create new passcode for firefox.

However, I ended up still being able to log in via my old passcode to google chrome. This would essentially allow me to send my ethers. 

I can definitely imagine a scenario where someone can get a newbie's first passcode because they didn't realize they made an easy one. And eventually log into the same browser if the newbie did not change the passcode on that browser, or wipe that program from their computer.

If I'm totally misunderstood something, please feel free to just let me know. If this is a bug, I'm curious is there a way I can help contribute / where could I begin to help?

**Comment by tmashuang** [comment]
MetaMask passwords are not associated with seed phrases or key pairs. They only allow reentry when MetaMask is locked. If a workstation is being used temporarily, we recommend uninstalling after MetaMask before leaving the workstation. In the scenario where multiple users are using a workstation, we recommend using different Chrome Profiles. Also, the password can be changed by locking and re-importing a seed phrase.
