### ISSUE TITLE
import account not available unless account already created

### ISSUE THREAD

**Issue by jordanglassman** [MetaMask/metamask-extension#2950]
Importing an account via JSON or private key is in the account menu, which is not accessible unless at least one _other_ account exists and is unlocked.

Yes you could restore from a seed phrase, but not having a seed phrase available is common; for example accounts created with geth have no associated seed phrase.

**Comment by Gudahtt** [comment]
Thanks for the suggestion! I'm going to close this in favour of #6466, which seems to be a more general version of this.
