### ISSUE TITLE
Recently events from solidity are not firing on Chrome, but working fine on firefox and Brave.  

### ISSUE THREAD

**Issue by kevinstotz** [MetaMask/metamask-extension#2952]
I have a contract running on Ropsten and the events show up in Brave and Firefox, but nothing in Chrome. This is a recent issue.  This seems odd.

solidity
contract MyLife is Owned, Accounting  {
    
    event FeePaid(address indexed _from, bytes32 _sentence);

}

function payForEntry(bytes32 sentenceHash) onlyBy(msg.sender) public payable {
        FeePaid(msg.sender, sentenceHash);
}

JS.

let c = web3.eth.contract(_this.data.contract.abi, _this.data.contract.address)
let cI = c.at(_this.data.contract.address)
cI.FeePaid({},{address:_this.data.contract.address}).watch(function (error, result) {
              if (!error) {
                console.log("Good" + result)
              } else {
                console.log(error)
              }
})

**Comment by damorton** [comment]
I'm also having this issue. I have an Ethereum node running locally, Chrome does not have MM installed and is getting the `currentProvider` data directly from `localhost:8545`, Firefox has MM installed. The contract is called to create an event from Firefox, which triggers MM for the GAS payment. Chrome is connected to the node and can receive the event data, but in Firefox MM does not propagate the event data to the application. However the callback is triggered when the event is called.

```
createEvent: function() {

    Contract.deployed().then(function(contractInstance) {

      contractInstance.createRandomEvent("test_input", {from:account}).then(function(result){
        console.log("called createRandomEvent() function ");
      });
    });
  }
```

Firefox MM console logs
<img width="896" alt="screen shot 2018-01-14 at 01 54 46" src="https://user-images.githubusercontent.com/3397660/34912044-ff4a06f0-f8cd-11e7-8ce1-88a95e3beb6f.png">

**Comment by kevinstotz** [comment]
I am not sure why..but it's working again.

**Comment by halgurdh** [comment]
I have the same issue, when i try it in incognito mode it works, but when i try normal, it doesn't

**Comment by halgurdh** [comment]
@bdresser not anymore, I think it was something else that wasn't working which didn't fire the events. Its works now.

**Comment by halgurdh** [comment]
hey I noticed there is still this issue in the latest version of metamask (beta), anyone else having this problem?
