### ISSUE TITLE
Unable to Transfer ETH from Metamask

### ISSUE THREAD

**Issue by cryptokingca** [MetaMask/metamask-extension#2955]
Hi i am unable to transfer around 0.1918457 ETH from Matamask. In the past i have transferred ETH in smaller denominations with NO issues. when ever i try to send the 0.1918457 ETH , i get a message " insufficient balance for transaction"
Please a help
Thanks

**Comment by Markov123** [comment]
Hi wanna send also around 0.3 ETH from Metamask and i have same issue. I create a ticket for metamask. Hope they will answer fast.

**Comment by cryptokingca** [comment]
i just tried again and was successful
Try transferring to a maximum of 2 digits.
so if you have 0.32917534 ETH
try to send 0.31 or just 0.32

**Comment by Markov123** [comment]
Thank you for info but i have the same problem when i send 0.27.
So for me it is not fix :(
