### ISSUE TITLE
meta mask seed and private key do not work for all accounts why

### ISSUE THREAD

**Issue by hasnot** [MetaMask/metamask-extension#2956]
any way i had a fire and lost all my seed phrases for account that has all my tokens.but i had my private key in my wallet thinking that that is a safe place and it was i did save it from fire.but now i enter the private key in sure it brings up the account but not all my wallet address's.so now what do i do to get access to my wallet address's.so i filed a support ticket with metamask they still have not even got back to me and it has bean days now the support here is no good i have contacted chrome to see if they can intercept this extension and find problems why they lack support for the users.unless someone can give advice on how to retrieve the seed i guess metamask has more funds to themselves since they would be the only ones to access them.they may say they do not but i can not believe that it is their back office to do all.

**Comment by tmashuang** [comment]
Mnemonic/Seed phrases are associated, and can generate, infinite number of private/public addresses. While importing a private key can only be associated with its public address.

**Comment by hasnot** [comment]
okay but is there a way of retreiving my seed phrase as you must be able to
see that i did have it saved for i used it to login a few times until the
fire distroyed everything.or can you just transfer the balances to my new
account address?or must i hire a tech  to do this for me

**Comment by tmashuang** [comment]
For the security, MetaMask does not hold any of its instances on a centralized servers. If the hard-drive can be salvaged, the files that hold the Chrome, or whichever browser, should have the extension's data stored on it.

**Comment by hasnot** [comment]
no i sent the harddrive and what was left of computer after fire to
microsoft but it was melted to badly and could not recover and that costed
1200 dollars.so as you see i am really out.
