### ISSUE TITLE
Metamask not able to connect to Main Ethereum Network, not able to login

### ISSUE THREAD

**Issue by xdanjing** [MetaMask/metamask-extension#2957]
Metamask not able to connect to Main Ethereum Network, not able to login

![image](https://user-images.githubusercontent.com/23659117/34912659-f1d7cbb6-f921-11e7-9ed3-bff2ce7a4c8d.png)

**Comment by lukebyte** [comment]
I have the same problem too. Yesterday there was no problem to login.

**Comment by tmashuang** [comment]
Related to #2043. TLDR; switch network to Test Network and switch back to Mainnet, or disable and renable MetaMask in the chrome extension list.
