### ISSUE TITLE
Diffrent public/Private key against a Seed.

### ISSUE THREAD

**Issue by danishsaber** [MetaMask/metamask-extension#2958]
I had generated a random seed with eth-Lightwallet and also generate Public/Private key against that seed.
Butt
When i use that seed into metamask it give an other account to me which is diffrent from my account which i had created myself using eth-lightWallet.
Why??

**Comment by nickoneill** [comment]
Looks like eth-Lightwallet defaults to the derivation path `m/0'/0'/0'/x` whereas metamask uses the standard `m/44'/60'/0'/0/x`. All derived addresses will be different.

**Comment by tmashuang** [comment]
Thanks @nickoneill fort the insight.
