### ISSUE TITLE
Metamask extension throws VM Exception while processing transaction error.

### ISSUE THREAD

**Issue by prameshbajra** [MetaMask/metamask-extension#2959]
I got this error from metamask.

```
    errors.js:35 Uncaught (in promise) Error: VM Exception while processing transaction: revert
        at Object.InvalidResponse (errors.js:35)
        at requestmanager.js:86
        at inpage.js:9909
        at completeRequest (inpage.js:9960)
        at inpage.js:683
        at replenish (inpage.js:1203)
        at iterateeCallback (inpage.js:1193)
        at inpage.js:1168
        at inpage.js:9837
        at inpage.js:993
```

It was working fine couple of hours ago. I have tried reinstalling/ disable and re-enabling the extension again but nothing worked.

Also, My smart contract is fully functional (Tested in Remix Browser-based IDE) and no other errors or logs are present anywhere. I also restarted Ganache and re-compiled and re-migrated my contracts with no luck.

I am using one of the truffle boxes (REACT) and no logs/errors are present in console either.

**Comment by frankiebee** [comment]
Do you have some reproduction code we can test this for maybe a repo?

**Comment by prameshbajra** [comment]
I re-wrote a couple of methods and after 12+ hours the error went away. And honestly, I do not know where the error came from but it's working now. Closing this.
