### ISSUE TITLE
Sending tokens from Metamask via MEW problem, doesn't show token to send

### ISSUE THREAD

**Issue by Stephane1234567** [MetaMask/metamask-extension#2960]
Hi, 
I'm trying to send my NGC tokens to another adress. When I want to send my tokens via MEW, I can't choose NGC, only ETH. My NGC are on my metamask account, and I do have some ETH on my Metamask to use for the sending fees. What can I do? Is this a bug, did I something wrong? Thank you very much!
![metamask wallet](https://user-images.githubusercontent.com/35407607/34919452-95266b96-f964-11e7-8ecb-1715b5198672.png)

![sending tokens via mew](https://user-images.githubusercontent.com/35407607/34919416-f28553d4-f963-11e7-95ca-03842d7dfc98.png)

**Comment by tmashuang** [comment]
On the right side, further down, there should be a list of all the tokens. If it is not rendering correctly, there should be a way to refresh the token list in MEW.

**Comment by Stephane1234567** [comment]
I clicked on the "show all tokens", but there wasn't any NGC token. I can add a token though, not quiet sure what it does, but could this help?

![image](https://user-images.githubusercontent.com/35407607/34957815-724734e0-fa2f-11e7-90a4-67ced3e5c69f.png)

**Comment by keitheisenberger** [comment]
Having the same issue. I have TRX token on Metamask (wallet though shows a balance of -despite there are 9200 TRX under it. When i go to MEW, TRX is not one of the available tokens. I created the token based on what i thought was the correct information and MEW still shows a balance of 0. Where are my tokens? How do i transfer or sell them?
![picture1](https://user-images.githubusercontent.com/35533666/35051818-85a75eac-fbbf-11e7-8073-a3bb090d8ac5.jpg)

**Comment by hupengbuaa** [comment]
encountered the same problem, there is no way to send token through MetaMast~ there should be a checkbox for the token type during sending token.
