### ISSUE TITLE
ETG tokens do not show up in metamask wallet

### ISSUE THREAD

**Issue by FluLuv** [MetaMask/metamask-extension#2965]
Hello. I am using mac OS Sierra and using Chrome browser. I have download the chrome extension MetaMask. I have added the ETG token contract using this: 0x28c8d01ff633ea9cd8fc6a451d7457889e698de6
I also added this contract address as well: 0x988383d7730B68A4cbC1Fc1aBBA08554fD605f6a

I have withdrawn my ETG to MetaMask and they can be seen here: https://etherscan.io/token/0x28c8d01ff633ea9cd8fc6a451d7457889e698de6?a=0x27779aad581ce637f30c6251abb092d7e5b8bc14

However, My MetaMask wallet shows 0ETG. 

Can you please help me get my ETG to my Metamask wallet? 

Thank you.
![screen shot 2018-01-15 at 2 38 45 am](https://user-images.githubusercontent.com/35451569/34938514-7ca38f98-f99d-11e7-972b-73e7699d5be7.png)
![screen shot 2018-01-15 at 2 41 07 am](https://user-images.githubusercontent.com/35451569/34938552-9eda8210-f99d-11e7-9c08-d54ca8cf8208.png)

**Comment by tmashuang** [comment]
Can you confirm that ETG's token contract address is 0x28c8d01ff633ea9cd8fc6a451d7457889e698de6 that is being entered the token decimal precision should also be 0?

**Comment by FluLuv** [comment]
I contacted the admin for etherdelta and he gave me this token address and said the decimal is 18. I tired using this token address and using 0 for the decimal like you said, but when I do so it does not let me submit. So I dont think the decimal is 0.

**Comment by FluLuv** [comment]
IT WORKED!! Thank you so much. You're the best!

**Comment by cpieps** [comment]
I am having this same issue what did you do to fix it?

**Comment by bdresser** [comment]
@cpieps check out https://metamask.zendesk.com/hc/en-us/articles/360015489031-Adding-and-Managing-Tokens-ERC20-In-The-New-UI
