### ISSUE TITLE
Remote CDN *might* be an attack vector

### ISSUE THREAD

**Issue by pocesar** [MetaMask/metamask-extension#2966]
With meltdown and spectre around, a DNS poisoning attack could leak private keys stored in MetaMask by targeting the remote HTTP request of the CDN resources to bootstrapcdn.com. it's not as bad and easy to accompllish like the Electrum wallet RPC issue, but raises concerns. We still have to see meltdown in the wild using JS, but the less prone to it, the better. didn't think thoroughly how exactly it would be executed, but it would be much better to ship those resources directly with the extension bundle IMHO

**Comment by kumavis** [comment]
im more concerned with the reading of secrets out of metamask memory, but i agree we should server our own assets

**Comment by kumavis** [comment]
https://github.com/MetaMask/metamask-extension/blob/07422ae8350c08a68ecf17b8ca2ec08f9ea1805f/ui/app/css/fonts.css#L1-L2
