### ISSUE TITLE
Metamask accounts showing multiple token symbols zero balances

### ISSUE THREAD

**Issue by Lethcorp** [MetaMask/metamask-extension#2967]

**Comment by Lethcorp** [comment]
I have 12 metamask wallets each created for 1 particular token. Each account shows the full balance of its relative token but it also shows a list of all my other tokens symbols from my other metamask accounts with a zero balance. Is this correct? Also each account will not let me send tokens “ insufficient funds”. I have even tried to send the tokens to a new metamask account and still the same. There’s about $10 of funds in the account I have tried. Please help. Thanks

**Comment by tmashuang** [comment]
Is the transactions gas fee being taken into account when attempting to send a transaction?

**Comment by Lethcorp** [comment]
No. It is not giving me a chance to view or change the gas. My concern is that metamask is reading a token higher in the list with a zero balance.  
For example if I try to send OST from the OST funded metamask account the OST token symbol is not at the top of the list. Is it normal for each of my accounts to show the token symbols from my other accounts with a zero balance. Thanks

**Comment by tmashuang** [comment]
The token list needs to be enhanced a little more. Originally the list would auto-detect tokens, but make unnecessary calls to our node provider. There is already an issue that seems to still be related, #2561. Once auto-detection of tokens gets added, it will potentially fix this issue closing for now in favor of #2561.
