### ISSUE TITLE
Metamask accounts showing list of tokens of all my other metamask accounts 

### ISSUE THREAD

**Issue by Lethcorp** [MetaMask/metamask-extension#2968]
I have 12 metamask wallets each created for 1 particular token. Each account shows the full balance of its relative token but it also shows a list of all my other tokens symbols from my other metamask accounts with a zero balance. Is this correct? Also each account will not let me send tokens “ insufficient funds”. I have even tried to send the tokens to a new metamask account and still the same. There’s about $10 of funds in the account I have tried. Please help. Thanks

**Comment by tmashuang** [comment]
Duplicate #2967.
