### ISSUE TITLE
Investigate integration with decentralized exchanges

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#2971]
A common user demand is to be able to send tokens. The exchange of tokens is MVP, but we believe we can further reduce user error by implementing an in-app flow for exchanging Ethereum tokens into other tokens or Ether itself.

We will update this issue with the pros and cons of our interview process as we proceed.

**Comment by aktary** [comment]
I'd like to talk with whomever from the MM team is investigating this.

**Comment by bdresser** [comment]
@aktary have some ideas?

**Comment by bdresser** [comment]
Closing - integrations are being addressed on individual issues
