### ISSUE TITLE
Seed words not generating original addresses 

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#2972]
A catch-all issue for all the seed word issues that persist where users are reporting that their seed words are restoring different accounts than they previously saw.

First, must determine where the common user errors are in order to differentiate these issues from real potential issues with the system. Common causes are:

- Misspelled words
- Wrong order of words
- Adding a password to MEW's mnemonic restoration
- Not realizing that the user must reveal additional accounts manually.
- Confusing another set of seed words as their intended restoration method.
- Entering the same password on a new installation without seed phrases does not restore the accounts.

Second, propose more thorough in-app checks and notices that the seed words saved are the same as the seed words displayed, as well as that the seed words saved generate the same accounts that are displayed. Sync with @jrmoreau on this.

Third, determine the actual causes of these incidents and if necessary, make refactors and fixes to the code in order to fix this seed word difference.

**Comment by jazzinuf** [comment]
@zanibas good evening! I see that you are working really hard in github.
I just want to let you know of the issue that has come to my vision. Basically the same thing has happened to me where the metamask locked out this morning and it gave me an option to restore my account. I have downloaded the seed phrase document.  As I have put the words in, it lead me to a seperate account that I have not seen before. And my previous account is no longer visible.  Any help would be much appreciated.

**Comment by vladfr** [comment]
Hey @Zanibas  I'm having a bit of trouble with this as well.
What do you mean by "Not realizing that the user must reveal additional accounts manually."

**Comment by Moejoe90** [comment]
@vladfr 
I think what she means is there are derivation paths and you have to know which derivation path were you using based on BIP44.

**Comment by danfinlay** [comment]
@vladfr He means that some users restore from seed phrase and say "I had more than one account before, where did they go?", when clicking "Add account" would re-generate them.

**Comment by danfinlay** [comment]
Related to #3127.

**Comment by bdresser** [comment]
closing in favor of #3127 – if you find anything, report it there!

**Comment by martineezz** [comment]
@Zanibas 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by darkwing** [comment]
Please do not contact the email cited, it is a scammer that will try to get your recovery phrase.
