### ISSUE TITLE
Token not adding to list

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2974]
User @oliver1977 on our slack says this token can't be tracked by MetaMask:

0xf6e66480c1cec714f11e20db1ba6a32e5d533580b50aced891bbf7b8756b9c5a

He sent me a test one to my test account, so I should probably do this, but could also send a test token to someone else.

**Comment by tmashuang** [comment]
This token was deployed on the Ropsten, I was able to add the token address which is 0x8398fE8944e63d94d90E99397a8b4De004E98895, OLIVER, 18. Closing unless there is further issue with the token address.
