### ISSUE TITLE
Coins Showing up in my wallet but I have no access to them. 

### ISSUE THREAD

**Issue by Deshaunbaylock** [MetaMask/metamask-extension#2979]
HI,

I'm having issue with being able to access my tokens. Currently it says the transaction was a success and the coins are in my wallet but I don't have the ability to access them to withdraw them. 

When I go to ether delta or Idex they can see that I have the tokens as well but don't have the ablitly to withdraw them.

Thanks in advance or the help!

I used a Firefox browser with the metamask update and i am currently on windows 10. 

  Screenshots are very helpful and will expedite your issue being resolved!
![screenshot 1](https://user-images.githubusercontent.com/35470702/34964122-9bef2fe6-fa11-11e7-97b6-e617757da968.png)

**Comment by tmashuang** [comment]
Can I receive clarification on 'withdraw'? The tokens seem to already associated with the address. If the intended action is to send tokens to a different address, integrating MetaMask with MEW's send token feature could be the potential solution. Here's a guide, [Sending Tokens via MEW](http://metamask.helpscoutdocs.com/article/32-sending-tokens-with-metamask-and-myetherwallet).

**Comment by Deshaunbaylock** [comment]
I bought them on etherdelta and wanted to make sure that they are actually
in my wallet.

I’m just checking to make sure that they are secure and not lost.

**Comment by Deshaunbaylock** [comment]
I guess for clarification -  I wanted to be able to deposit or send them back to ether delta to sell now. Would I have to use MEW for that?

**Comment by tmashuang** [comment]
You are able to post sell orders with MetaMask and Etherdelta, without MEW.

**Comment by Deshaunbaylock** [comment]
Also I just plan on holding till it gets to bigger exchanges, I just want to make sure that the coins are actually in my wallet. What's the best way to confirm that?

Also again thanks for the help!

**Comment by tmashuang** [comment]
The screenshot provided is a good indication that the tokens are confirmed, and associated, with your address.

**Comment by Deshaunbaylock** [comment]
Thanks!

First time leaving big exchanges, still have a lot to learn.
