### ISSUE TITLE
`eth_signTypedData` cannot process array inputs

### ISSUE THREAD

**Issue by nnkken** [MetaMask/metamask-extension#2986]
To reproduce the bug, open Chrome developer console in any Metamask-injected page and input:

const signData = [{type: "uint256[]", name: "values", value: "[1, 2, 3]"}];
web3.currentProvider.sendAsync({
        method: "eth_signTypedData",
        params: [signData, from],
        from: web3.eth.accounts[0]
    }, console.log);
Expected: a pop-up showing that I'm signing values: [1, 2, 3].

Actual result: a response with error object {code: -32603, message: "Got unwanted exception. Expected EIP712 typed data"}

Same for type `address[]`, `int[]`, `bool[]`.

Similar to #2826 

It seems that ethereumjs-abi does not support solidityPack on array types.

**Comment by danfinlay** [comment]
This is expected, the spec does not yet support arrays or structs, but may eventually. Follow the spec and chime in here:
https://github.com/ethereum/EIPs/pull/712
