### ISSUE TITLE
Restore from seed phrase - clear old state

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#2989]
To help clear up any buggy state

**Comment by chiquitar** [comment]
I thought by restoring from seed phrase it was supposed to do this, but when I tried it, all my transactions returned. I have some hanging ones from several days ago where the transaction cannot be found by etherscan and I haven't been able to clear them or add any new ones with them hanging there.

**Comment by danfinlay** [comment]
In the meanwhile, the only way to clear out your transactions is to reinstall MetaMask, or to submit & reject enough transactions to roll the old ones out, which [seems to be 40](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/metamask-controller.js#L136).

**Comment by kumavis** [comment]
This should clear out all old state

**Comment by kumavis** [comment]
https://sentry.io/metamask/metamask/issues/439113240/

**Comment by kumavis** [comment]
Since this is blocking vault recovery for users hitting the storage quota, I'm raising the priority

**Comment by kumavis** [comment]
https://sentry.io/metamask/metamask/issues/439113090/

**Comment by danfinlay** [comment]
Might be better to simply have a "clear state" emergency button in settings, since transaction history is generally useful to most users.  It also seems like reinstalling is the ultimate state-clearing, so not sure why that doesn't work here.

**Comment by bdresser** [comment]
since the reset account feature is live on both UIs and seems to clear transaction history, can I bump this down from P1?

**Comment by kevinorin** [comment]
Is this related to the issue I'm having with Brave. I've lost all my deposits to Brave Wallet and restoring with seed key doesn't help. https://community.brave.com/t/issues-with-cryptowallet-crypto-missing/96938/5
