### ISSUE TITLE
Cannot scroll

### ISSUE THREAD

**Issue by chiquitar** [MetaMask/metamask-extension#2993]
Right-click Metamask popdown menu to see transactions.
Expected: Can scroll down to see more than most recent 3 transactions
Actual: No scrolling possible up and down. There is a scrollbar for left to right, but nothing shows to the right of the original column.
Browser: Firefox 57.0.4 (64 bit)
OS: Windows 10 vs 1709
![screenshot 1](https://user-images.githubusercontent.com/35504907/35009685-91d128f0-fabd-11e7-82f0-0acfbcbbc9af.png)

**Comment by tmashuang** [comment]
Fixed in #2929. Should be rolled out today. Thanks for the report.
