### ISSUE TITLE
A total of 4 Pending txns found

### ISSUE THREAD

**Issue by simooo31** [MetaMask/metamask-extension#2994]
I have A total of 4 Pending txns found, for more then 24 hours. 

what should I do? I state that the metamask account does not recognize the tokens and I was trying to put them on ether delta through metamask, but it made me 4 pending orders that remain incomplete, can I cancel or do something?

**Comment by Zanibas** [comment]
Could you please forward this ticket to support@metamask.io? That'd be a more appropriate place to answer this question.
