### ISSUE TITLE
Pending confirmation in etherscan

### ISSUE THREAD

**Issue by charansai27** [MetaMask/metamask-extension#2997]
I recently started a transaction from Metamask to Cryptopia around 0.20 Eth. It's been 3 hrs then I updated my gas price to 38.4 Gwei still I'm unable to see the transaction. It is in nonce 2 can anyone help me how to reset nonce. I tried using restoration of seed phrase still I'm unable to reset nonce. But I can see my Ethereum balance in metamask wallet.

**Comment by Zanibas** [comment]
Please forward this ticket to support@metamask.io, but if you have your seed words backed up, you can try uninstalling and reinstalling to reset your state--we'll work on better clear tx handling soon.
