### ISSUE TITLE
Re-enabling Metamask Chrome Extension after crash

### ISSUE THREAD

**Issue by etruschi** [MetaMask/metamask-extension#2998]
![image](https://user-images.githubusercontent.com/29963695/35014356-4e10300e-fade-11e7-87e3-5a4058ac4962.png)

**Comment by etruschi** [comment]
Hi, my Metamask crashed. It was disabled somehow and I can't enable it again, the link doesn't work and it says that the extension has been added. Anyone has ever encountered this problem?

Thank you

**Comment by kumavis** [comment]
@etruschi You need to go to the extensions tab in chrome

![image](https://user-images.githubusercontent.com/1474978/35075784-ef1105ac-fba9-11e7-9c31-37c7bad22d20.png)

**Comment by etruschi** [comment]
Solved. Thanks mate.

Sent from Mail for Windows 10

**Comment by Musashi13** [comment]
My MetaMask ext has all of a sudden decided to not pull down when clicked on. I wa able to use it earlier today but now will no longer work. Anyone know what's going on? I've tried from firefox and brave both so far. working in linux parrot os distro.
