### ISSUE TITLE
Hide Token Button UI Bug

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3001]
There's a UI bug with the "hide token" selector when the list is scrolled. See gif.

![hide token bug](https://user-images.githubusercontent.com/597770/35018101-d751470e-fad4-11e7-84c8-0412b80b5f8f.gif)

**Comment by alextsg** [comment]
@cjeria This should be fixed with a recent update, https://github.com/MetaMask/metamask-extension/pull/2954
