### ISSUE TITLE
Copy address to clipboard BUG

### ISSUE THREAD

**Issue by AndyGerald** [MetaMask/metamask-extension#3006]
Hi,

This is my situation : I transferend some ETH to my metamask account

Im sure if I copied the address from the "Copy address to clipboard" drop-down menu and not the "show QR code" option...

Approximately ten hours ago I decided to check the transfer to that same address, and nothing. And still nothing.

 I'm positive, I used the "Copy address to clipboard" from the drop-down menu feature.

And the ETH never arrived :-(

After checking on etherscan and on the website whithdrawals page, I noticed that the addresses I had copied was different than the address I had used for the test transfer : letters and numbers where exactly the same and correct, but the second address that had been copied had lot of capital letters where the other had mostly lower case.

I went back checking in the Metamax app and noticed that copying an address from the "Copy address to clipboard" drop-down menu's feature and copying the (supposedly) same address from the "show QR code" resulted in having to different presentation of the same suite of letters/numbers. the first full of capitals and the second with mostly lower case letters.

Here is an exemple of the same address copied with both methods, i will copy now, without changing anything :

0x174d73eab593CaEc59e49696F5D5b52E8c804a64

0x174d73eab593caec59e49696f5d5b52e8c804a64

How is this possible?

The ETH is missing from the exchange and its not in my metamask. I still cannot believe this.

Since I never got the ETH I guess there is no point in asking if the addresses are the same or not..

My question is : is this a bug or is it a known feature and am I the culprit (beside from the fact that I didn't check carefully enough even though after pasting the address I checked that the seven first letters matched the seven letters from the address displayed just below the account name in the in the Metamask app)

Other question : where did the ETH? Do I have a chance to see them back again ? Will them be resend to the transaction platform ?t's quite vital for me...

If needed I can provide the addresses, and email, screen caps from the web platform regarding the transfers.

Thanks for your answers...

**Comment by tmashuang** [comment]
Is the transaction still pending?

**Comment by AndyGerald** [comment]
I dont have the funds in the exchange, and shows withdraw status: succed, but i click on the Blockchain record link and shows: "Sorry, we are unable to locate this Transaction"

No dia 17/01/2018, às 02:09, Thomas Huang <notifications@github.com<mailto:notifications@github.com>> escreveu:


Is the transaction still pending?

**Comment by tmashuang** [comment]
Have you contacted the exchange?

**Comment by AndyGerald** [comment]
Yes, no answer yet. But how is this possible? How can a simple copy, dont work properly? I dont understand! Has this happen to anyone? Is this recorring? This is a very seriuos matter, i lost alot of money because of this error. How can a copy change the letters you are copying?..

**Comment by tmashuang** [comment]
When sending transaction over the network address letter case is optional. https://ethereum.stackexchange.com/questions/2045/is-ethereum-wallet-address-case-sensitive/2046

**Comment by AndyGerald** [comment]
Oh really?! Im so realeaved, thank you so much. But i still dont see the funds anywhere...

**Comment by tmashuang** [comment]
The reason I asked about the discussion about the exchange was to ascertain the status/details of the transaction. Questions like do they provide a status indication of the transactions, do they provide a transaction hash, or do they send a transaction with a default gas price?

**Comment by AndyGerald** [comment]
the exchange was Kucoin and it looks like there is a very big delay with ETH withdraws right now, i think that is the reason. But that together with the difference on the address it really got me scared.

**Comment by AndyGerald** [comment]
Thanks for you help. Everything is good.

**Comment by sawluke** [comment]
I have this EXACT problem.  Copied my ETH address from MetaMask, pasted it, sent funds, transfer comfirmed as complete, nothing in my wallet on other side of transaction.  WTF???  Looked at address I copied, and compared to actual address, and all upper case letters in actual address are all lower case in address that I copied, pasted and sent my fucking 5 ETC to.  tell me everthing worked out for you.

**Comment by sawluke** [comment]
0x8039A121D294458DB8564267AA4a8e1968EebB45
0x8039a121d294458db8564267aa4a8e1968eebb45

These are the two ways I can copy my address from MetaMask.  Wtf would this be possible???

**Comment by tmashuang** [comment]
@sawluke the issue you are encounter in is not an issue with the case size of the address. The issue is you sent ETC to an MetaMask which doesn't display ETC values.

**Comment by sawluke** [comment]
Soooo, if that's the case Thomas, Have I lost my ETC?   If not, how do I
find/retrieve it?

**Comment by BMaster34** [comment]
Had the same metamask issue while transferring an NFT to my ledger. I copied the address from the clipboard and when pasted into opensea some of the letters were changed from upper to lower case. PLEASE tell me there's something I can do.
