### ISSUE TITLE
User Question: app not working (?)

### ISSUE THREAD

**Issue by tossiii** [MetaMask/metamask-extension#3008]
What to try to introduce METAMASK into but for the message, having added to CHROME, not to advance to it any more by coming out should we do?

**Comment by Zanibas** [comment]
Can you please expand on the details? Also, if English is not your first language, please try stating your question in your first language? Sorry, but it's hard to interpret what you are asking.

**Comment by tmashuang** [comment]
Closing issue, will reopen when OP provides information and will investigate.
