### ISSUE TITLE
Funds not showing but show in deltabalances.github.io

### ISSUE THREAD

**Issue by kalm1975** [MetaMask/metamask-extension#3009]
<script src="https://gist.github.com/kalm1975/94ed3a5db0a741b514630721ad870df8.js"></script>

Hello,
I've reinstalled both Chrome and MetaMask on my desktop but my funds are still not viewable in MetaMask on Chrome desktop. Transaction history is also gone. When I check on https://deltabalances.github.io my funds are viewable on my iphone but not on desktop. I get an error saying failed to load all wallet balances after 3 tries. New deposits to MetaMask from today show but my previous funds still do not.

Kind regards,
Kat

**Comment by Zanibas** [comment]
Could you please verify which public address you're attempting to compare?

**Comment by kalm1975** [comment]
Hi there,

This is my public address: 0x0a67B0e48436b922E87556fCCbCFb107d13e3B1F

It shows up in Deltabalances on my desktop & on my iphone but going into
MetaMask (Chrome browswer) on my desktop, my exisiting funds & transfers
before yesterday do not show up.

**Comment by kalm1975** [comment]
Hi there, any update on this thanks. Would really appreciate a status update.

**Comment by bdresser** [comment]
@kalm1975 I recommend you reach out to support@metamask.io and they'll be able to help you with a bit more privacy.
