### ISSUE TITLE
Recovery metamask

### ISSUE THREAD

**Issue by natkar26** [MetaMask/metamask-extension#3010]
Hello!
I installed metamask and create new account, but NOT saved seed phrase. My Google Chrome automatically sign in and I didn't have any problem. But I deleted metamask and installed it again. Can I recovery account anyway?

Thank you.

**Comment by frankiebee** [comment]
Without the seed phrase after uninstalling and then reinstalling you can not recover the account, sorry about this.

**Comment by Creamers158** [comment]
I had the same problem, but it reset by itself. I logged into a second laptop without internet and saved the plugin data before it could update and reset itself.
Is there a way to use the plugin extension work again so I can login again?
