### ISSUE TITLE
Update Retry Transaction Logic

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#3011]
Currently, we show the Reject button on retying transactions and is causing a issue. We can set a Retry flag to remove the button, or create a duplicate and add a new transaction once the retry button is hit. Once the transaction is rejected, the nonce will get stuck.

**Comment by danfinlay** [comment]
Adding this to the current sprint, I'm going with the latter strategy:

> create a duplicate and add a new transaction once the retry button is hit.

This way the retry can be plainly seen as a second transaction, and whichever one succeeds will show success, whichever one doesn't will show failure, and all will be well.

**Comment by cjeria** [comment]
Here's my suggestion @danfinlay @kumavis. See my notes in the mock flow.

![duplicate tx flow](https://user-images.githubusercontent.com/597770/35177105-009e68bc-fd32-11e7-92b7-46dfc8410ccc.png)

There's an edge case here and that is what to do if the original transaction successfully goes through while the user is in the duplicate tx screen? My suggestion: Through an alert modal informing the user that their original tx just went through. Hitting OK should put the user back to the account page.

![success alert](https://user-images.githubusercontent.com/597770/35177324-2ca9a39e-fd33-11e7-8477-dd0cbdd7eaa4.png)
