### ISSUE TITLE
ETH not showing in MetaMask wallet

### ISSUE THREAD

**Issue by crptosystem** [MetaMask/metamask-extension#3013]
About 5 hours ago, I sent 0.29 ETH from my Binance account to my MetaMask wallet address below:

0x2fb3fa27191a125474929d5fe65ef4aa24249012

with transaction ID:

0x54f5e01da9637a603949075af543bfcf3cc4292eb8696571157e8cea79fa99fa

EtherScan confirms this transaction is successful & complete but my MetaMask shows 0eth still.

Browser used: Google Chrome

Operating System used: 32 bit Operating System. Windows 7 Ultimate
Please what can be done to rectify this? Attached image explains more.

![mew](https://user-images.githubusercontent.com/35541566/35064928-e62fa426-fbcb-11e7-9e4d-ff3228a5f789.jpg)

**Comment by tmashuang** [comment]
@crptosystem Could you please forward this ticket to support@metamask.io? That'd be a more appropriate place to answer this question with your state logs. Obtain State Logs within MetaMask.

**Comment by samfidodido24** [comment]
@crptosystem can I get in touch with you?

**Comment by samfidodido24** [comment]
> About 5 hours ago, I sent 0.29 ETH from my Binance account to my MetaMask wallet address below:
> 
> 0x2fb3fa27191a125474929d5fe65ef4aa24249012
> 
> with transaction ID:
> 
> 0x54f5e01da9637a603949075af543bfcf3cc4292eb8696571157e8cea79fa99fa
> 
> EtherScan confirms this transaction is successful & complete but my MetaMask shows 0eth still.
> 
> Browser used: Google Chrome
> 
> Operating System used: 32 bit Operating System. Windows 7 Ultimate Please what can be done to rectify this? Attached image explains more.
> 
> ![mew](https://user-images.githubusercontent.com/35541566/35064928-e62fa426-fbcb-11e7-9e4d-ff3228a5f789.jpg)

Can I know do you own that address?

**Comment by samfidodido24** [comment]
helo?
