### ISSUE TITLE
metamask maximizes in screen

### ISSUE THREAD

**Issue by pizza222** [MetaMask/metamask-extension#3022]

**Comment by pizza222** [comment]
When i click  on metamask and it opens for my approval, the whole screen goes white and metamsk maximizes.  How can i have it open in a smaller box?

**Comment by kumavis** [comment]
@pizza222 is your chrome browser maximized? That could trigger these maximized windows.

**Comment by kumavis** [comment]
also let us know what OS you are using

**Comment by pizza222** [comment]
How do i change this?
also now my metamask isnt opening>

I am on a mac

**Comment by pizza222** [comment]
Kumavis...i feel like I am talking to a celebrity...lol

**Comment by pizza222** [comment]
update now.. metamask opens but with a lag.
