### ISSUE TITLE
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page. Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.

### ISSUE THREAD

**Issue by Jay34970** [MetaMask/metamask-extension#3032]
Hi, 

When logging to MetaMask, a blank window appears (see screenshot).

MacOS 10.10.6
Firefox 57.0.4 (64-bit)
Metamask 3.13.4

    Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
    Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.

Extension ID
    jid1-TMndP6cdKgxLcQ@jetpack
Internal UUID
    2de1b9ff-5847-464a-b0f2-e153fbd1feb7

![screen shot 2018-01-18 at 10 04 42 pm](https://user-images.githubusercontent.com/35568068/35101777-b09f9a5c-fc9b-11e7-884b-3baca6466406.png)

**Comment by danfinlay** [comment]
Thanks for the bug report, we'll look at this soon, and we'll raise the priority if other Firefox users have this issue.

**Comment by Jay34970** [comment]
Thanks Danfilay. For info, I could retrieve my Seed Words, re-install the add-on and login. All is working fine now.

**Comment by jconley** [comment]
should no longer show up when Firefox 66 is released.
https://blog.mozilla.org/addons/2019/02/15/extensions-in-firefox-66/
