### ISSUE TITLE
Auto-detect tokens on the add token screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3034]
We're talking about removing the suggested tokens on the add token screen.

We could replace that section with "Detected tokens", which the user can then easily select and track.

When on Mainnet, we could just ask Balanc3 or Etherscan what tokens the user has too, to further reduce our need for client-side work here.

We could also create an on-chain contract for requesting balances from several tokens at once, which we've heard from DappHub is more performant.

Some constraints:

- Should only check while on the main network.
- Should not check every token at once (lazily iterate through tokens, to not overwhelm infura)
- Should only check balances, not other token details (to minimize load on infura)
- Should auto-add these tokens to the user's account.

**Comment by bdresser** [comment]
@danfinlay why not just show auto-detected tokens in the side tray? 

I think "Add tokens" can be a little confusing for a non-pro user. they don't want to necessarily "add" a token to a given account, but want to display the tokens they've already acquired. we could potentially just avoid that whole doublethink.

@cjeria any thoughts here?

**Comment by cjeria** [comment]
@bdresser I totally agree. Auto-loading tokens means less friction for the user which == better ux. I think the add token feature is still useful for pro-users to add custom tokens, test, etc. But for the average user, this sounds like great ux!

**Comment by cjeria** [comment]
We also need the add token feature so that users who have chosen to hide their token(s) can re-add them later.

**Comment by estebanmino** [comment]
I'm currently working in a MVP of this feature, so far is auto detecting tokens and adding it automatically to the token list.

@cjeria do you think that adding a "confirm detected token" confirmation to the UI would be useful?

**Comment by cjeria** [comment]
@estebanmino Possibly? Is there a technical reason you think adding a "confirm detected token" button is necessary?

If we do add such button I think the wording should be stated in question form like "Add detected token?". I also think it would be cool if we use a general-purpose card/banner style element that slides in from the bottom that shows this alert, like how the Jaxx wallet shows alert message. we'd add a button that says "add" or "ignore". Thoughts?

![image](https://user-images.githubusercontent.com/597770/41688828-85bd53c2-74a2-11e8-9704-8d9d6390d69d.png)

**Comment by estebanmino** [comment]
@cjeria for that confirmation I was thinking in an user that hided a token, it  that is done is going to update the tokens again and it's going to appear again. I haven't seen how the hide token option works yet but right now that would happen, I'll check it out, I agree that this would be the best option.

Would be a good option, but my first idea with that banner was, what happen if two or more tokens are detected? Would pop up each time, all at once, etc. (open question).

**Comment by bdresser** [comment]
My hunch is that the "hide token" feature is most often used by people who've added a token they don't have anymore. Or people who added a token by accident.

I'm in favor of just adding the tokens quietly without asking for user confirmation. Based on how people usually ask this question, I think most new users expect this to happen automatically and don't actually understand that token balances are tracked on a specific contract.

**Comment by estebanmino** [comment]
#4683

**Comment by estebanmino** [comment]
here is an implementation of this feature, comments are appreciated #4683

**Comment by estebanmino** [comment]
this feature was implemented in #4683
