### ISSUE TITLE
WARNING (There was an error when resubmitting this transaction.)

### ISSUE THREAD

**Issue by NEtimebuddy** [MetaMask/metamask-extension#3043]
I followed a guide on Steemit for investing in the EOS ICO. After claiming my EOS tokens, I received a warning that there was an error when resubmitting the transaction. The Etherscan transactions show "Success" but I'm not sure where my EOS tokens are.

I would really appreciate some help on this, or at least somebody to point this layman in the right direction.

Thank you in advance.

**Comment by bdresser** [comment]
check out [this support article](https://consensys.zendesk.com/hc/en-us/articles/360004135092-Managing-ERC20-Tokens)
