### ISSUE TITLE
UX - Disallow contract publishing that does not result in contract code

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3044]
A user tried to send funds to an address, but accidentally performed a contract publish that did not result in contract code.

Some strategies to prevent this:
1. Hide contract publish behind a separate option
2. Disallow sending eth when publishing a contract
3. Don't allow a contract publish tx to be submitted if it does not result in contract code
4. i18n! English may not have been the primary language of this user

Here is an example tx. Note the data field of the publishing tx and the resultant code (empty) of the published contract.
https://etherscan.io/address/0xd83bdb0db2adcb9f683529bb929b8c2abfda6e3f

**Comment by danfinlay** [comment]
Easier short-term win: Hide the data field by default.
