### ISSUE TITLE
New UI Welcome Screen

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3045]
On reinstalling the latest version (4.0.10) I noticed there is no way to experience the new UI onboarding flow. I'd suggest we add a welcome screen and ask users if they want to experience the new UI. I attached a mockup of what this could look like.

Here's what users see on initial launch
![image](https://user-images.githubusercontent.com/597770/35166224-fc530460-fd05-11e7-8fd7-04c21c5ea69d.png)

Suggested screen
![extension welcome screen](https://user-images.githubusercontent.com/597770/35166858-208f7e6a-fd08-11e7-88de-08f191922fdc.png)

**Comment by kumavis** [comment]
I agree we need to improve over our old one

I think we need to reduce the wall of text

**Comment by kumavis** [comment]
![image](https://user-images.githubusercontent.com/1474978/35167835-c0f0cae6-fd0b-11e7-808c-8255f43a721b.png)

![image](https://user-images.githubusercontent.com/1474978/35167860-cdc7ded0-fd0b-11e7-882a-985884d5abd9.png)

**Comment by cjeria** [comment]
@kumavis Ok, reduced the wording. Added a screenshot of the new UI. Tried to make it fun. Too much?

![extension welcome screen copy](https://user-images.githubusercontent.com/597770/35168596-5cf1f706-fd0e-11e7-9e32-32cfe667ff86.png)

**Comment by danfinlay** [comment]
How did this only now occur to me?:

We can open a full page experience on first install. It could include all setup & tutorials. Why use the popup for setup unless the user closed that full tab experience?

We could even, say:
- If a user is not set up, opening the "action view" shows a screen that says "Welcome to MetaMask" with one button: "Get Started" (which opens the full tab intro experience!)

**Comment by cjeria** [comment]
@danfinlay interesting! Right now, immediately after install we're loading metamask.io. What you're suggesting is loading up a welcome screen (like above mock)? I dig it, however my concern is if users load the old UI in the full page experience, they are going to see this:

![image](https://user-images.githubusercontent.com/597770/35169364-2487cc1c-fd11-11e7-8fe1-6f457719cd48.png)

**Comment by danfinlay** [comment]
Yeah, I'm thinking definitely this is after the NewUI transition.

**Comment by cjeria** [comment]
Short term solution for trying new UI in fresh install and during sign in screen.

![image](https://user-images.githubusercontent.com/597770/35698719-c29bff00-0742-11e8-8ba1-5884d9f91d1b.png)

**Comment by danfinlay** [comment]
For the new UI, we'd need to show different text, like "Use old interface"

**Comment by cjeria** [comment]
Or how about "Use classic interface"?

**Comment by danfinlay** [comment]
I'll probably never feel normal about the word "classic" again...

![triggered](https://giphy.com/embed/lz9lPkqddgoec)

**Comment by alextsg** [comment]
Try Beta links have been added.
