### ISSUE TITLE
re-direct all urls on MetaMask.io to helpscout KB

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/metamask-extension#3048]
HappyFox will be shut down any day now and we want our users to fund our KB docs and be able to submit new tickets. Let's re-direct to [http://metamask.helpscoutdocs.com/](http://metamask.helpscoutdocs.com/) where they can search for articles and submit to the contact field with questions/tickets.

**Comment by bdresser** [comment]
Alrea
