### ISSUE TITLE
Feature Request: Differentiate Development wallets from Mainnet

### ISSUE THREAD

**Issue by quantumproducer** [MetaMask/metamask-extension#3052]
I am writing dapps. I frequently run `ganache-cli` and import those private keys into Metamask. This litters my wallet list.

I would prefer 1 of 2 things:

1) Switching networks used a different set of wallets (I shouldn't see my mainnet wallet address listed in localhost or ropsten)
2) I have the option of temporary developer addresses to paste in but they are ephemeral and are deleted after closing browser.

**Comment by Robbiekruszynski** [comment]
Hey @quantumproducer I know this ticket has been floating for a bit but please know it was never lost! We have migrated all of our requests and general inquiries over to ZenDesk. Here is a [link ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas)if you'd like to add a feature request or have any other ideas you'd like to share with the community!
