### ISSUE TITLE
Extension is blank

### ISSUE THREAD

**Issue by ryanwar** [MetaMask/metamask-extension#3055]
I installed the MetaMask extension on chrome.  But when I click the fox icon to open it, it is just a blank box.  This is happening in chrome on a Macbook.
![screen shot 2018-01-20 at 10 23 27 am](https://user-images.githubusercontent.com/35636700/35186648-23a6ff3c-fdcc-11e7-995f-679243197e4b.png)

**Comment by frankiebee** [comment]
Hey @ryanwar could you provide a little more information for me such as your browser version and weather or not you are seeing any error logs in the background console. [Here](https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome) is how to do that.

**Comment by ryanwar** [comment]
I solved the issue.  It was because my chrome browser was out of date.
Thank you for reaching out.
