### ISSUE TITLE
Reveal Seed Word Design

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3059]
Update design of the reveal seed word design

![image](https://user-images.githubusercontent.com/597770/35236847-9681ac0e-ff5d-11e7-8b44-9417cc83820c.png)

**Comment by cjeria** [comment]
![image](https://user-images.githubusercontent.com/597770/35247587-d6639036-ff7f-11e7-95c4-ee9db96559b7.png)

**Comment by cjeria** [comment]
https://github.com/MetaMask/metamask-extension/issues/3168

**Comment by bdresser** [comment]
this has been updated in the new UI
