### ISSUE TITLE
master: Canceling TX breaks ui/background stream

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3063]
Reproduction:
- Create a new tx
- on Confirmation screen, click "reject"
- Notice the tx is still listed with a blue "unapproved" dot.

What should happen:
- The tx should immediately show rejected

Reason:
As visible in the UI console, there is a stream break after rejecting that seems to break the UI's connection to the background. After a rejection, no other action is possible.

**Comment by kumavis** [comment]
We fixed this : )

**Comment by kumavis** [comment]
fixed by #3064
