### ISSUE TITLE
possibility to "web3.eth.sign" with no dialog 

### ISSUE THREAD

**Issue by saveriocastellano** [MetaMask/metamask-extension#3067]
hello, 

I see that when "web3.eth.sign" is called then the user is prompted for a dialog by metamask and only after accepting the sign call is executed. Will it ever be possible to sign without needing user confirmation? 
This is crucial for dapps where the state of a channel is exchanged many times completely offchain between client and server.. in this cases each party must sign the state and before sending it to the other party. Several use cases (for instance when client and server communicate in a gambling app for bets and wins) that rely on this method will not be feasible if the player/user has to confirm each sign operation in a dialog..

thanks in advance

**Comment by danfinlay** [comment]
We might eventually add some key types that don't require confirmation, but that's a very early concept right now. #2532

One way to achieve this today is to generate a local key in your site, and sign freely with it. You can even ask the user to sign that new signing key first, as a way of proving they intended to use it as their temporary signer.

**Comment by danfinlay** [comment]
Closing since the general goal is captured in that RFC, and I'd like to focus discussion of how this would be achieved in one place.
