### ISSUE TITLE
Deep linking to Add Token

### ISSUE THREAD

**Issue by gtaschuk** [MetaMask/metamask-extension#3068]
Our app allows users to earn tokens by performing various actions.  While we have some indicators built out around the token, we would like the user to use metamask to manage (view balance, send, receive) tokens earned in our platform.

We would like a way to link into metamask to the Add Token screen, optimally with values pre-filled (symbol, contract address), so that they can manage their use of our token through metamask.  This would simplify onboarding of new users who may be unfamiliar with metamask.

Is this a feature other people would find useful?

Thanks

**Comment by danfinlay** [comment]
I think a lot of people would find this useful, please add your thoughts on this proposed specification here:
https://github.com/ethereum/EIPs/issues/747

**Comment by bdresser** [comment]
check out https://ethereum-magicians.org/t/eip-747-eth-watchtoken/1048
