### ISSUE TITLE
Sent ETH to a ETC address by mistake

### ISSUE THREAD

**Issue by shazukhan** [MetaMask/metamask-extension#3070]

**Comment by danfinlay** [comment]
ETH and ETC addresses are mostly the same. If you have the private key of one, you can still use that account on the other, you just have to be cautious of replay attacks.

Here is a guide to splitting your account again:
https://steemit.com/ethereum/@pauls/ethereum-fork-step-by-step-guide-to-safely-splitting-your-eth-etc
