### ISSUE TITLE
Allow zero gas cost for non-main network

### ISSUE THREAD

**Issue by codyborn** [MetaMask/metamask-extension#3074]
MetaMask currently provides an error when setting the gas price to 0 gwei.  The Parity PoA client allows the consortium to configure free-gas transactions.  Ether doesn't serve much purpose on a consortium network so free-gas transactions are a legitimate use-case for enterprise scenarios.  It'd be great to remove this error from MetaMask in the case that the user is not connected to the public network.

**Comment by nujabes403** [comment]
I modified this code on #4037

**Comment by danfinlay** [comment]
Closing in favor of #4058 (allowing zero gas cost txs on all networks).
