### ISSUE TITLE
Make our background storage more size resilient

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3076]
Related to #3071

Meta-issue to address #3071.

We now know that storage is overflowing for some users, and this may be causing vault loss.

We need to develop strategies to improve our storage size resilience, and implement them.

- [x] Study what happens when background localstorage cannot write anymore. Is the storage instantly lost? Is there an opportunity to backup/recover?
- [x] Study which portions of our persisted state take the most size (probably transactions).
- [x] Review extension storage limits.
- [x] Research other alternative storage strategies.
- [ ] Move our `localStorage` use to the better solution (`storage.local`).

**Comment by danfinlay** [comment]
>  Study what happens when background localstorage cannot write anymore. Is the storage instantly lost? Is there an opportunity to backup/recover?

While the write attempt fails, the storage seems to persist, suggesting this issue may not be causing any data loss.

**Comment by danfinlay** [comment]
> Study which portions of our persisted state take the most size

- `RecentBlocks` (doesn't *need* to be persisted, should be removed from storage)
- `BlacklistController` is getting pretty big, could use own key.
- `TransactionController`

**Comment by danfinlay** [comment]
> Review extension storage limits.

Looks like the clear correct path is [storage.local](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage).

From the MDN documentation:

> Although this API is similar to Window.localStorage it is recommended that you don't use Window.localStorage in the extension code to store extension-related data. Firefox will clear data stored by extensions using the localStorage API in various scenarios where users clear their browsing history and data for privacy reasons, while data saved using the storage.local API will be correctly persisted in these scenarios.

The [storage.local](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/local) API could allow for [unlimited storage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Unlimited_storage).

**Comment by danfinlay** [comment]
`storage.local` API originally defined by chromium team [in these docs](https://developer.chrome.com/extensions/storage#type-StorageArea).

**Comment by danfinlay** [comment]
Previous example of setting up MetaMask to use an async storage api [here](https://github.com/MetaMask/metamask-extension/blob/master/mascara/src/background.js).

**Comment by danfinlay** [comment]
Turns out much of the work to use the `extension.storage` API properly was already done by @heyellieday in [this PR](https://github.com/MetaMask/metamask-extension/pull/2802), I've forked her work to leverage this for an easier fix. (Forget that other bounty, she gets a bounty for this).

**Comment by danfinlay** [comment]
Began the work converting to `extension.storage` in [this branch](https://github.com/MetaMask/metamask-extension/tree/i3076-UseStorageLocalInstead).

**Comment by kumavis** [comment]
https://sentry.io/metamask/metamask/issues/439253980/

**Comment by danfinlay** [comment]
@kumavis that particular sentry error refers to our send-form's persistence, not background, so it probably deserves its own issue.

**Comment by danfinlay** [comment]
Added to that branch:
- No longer writes to `localStorage`.
- Fixed issue where quantity of write attempts overwhelmed our `pump` to `storage.local` stream.

**Comment by danfinlay** [comment]
Fixes #3071
