### ISSUE TITLE
Wallet UI - Cannot properly see account address in Firefox 56.0.3

### ISSUE THREAD

**Issue by aaroncolwill** [MetaMask/metamask-extension#3078]
Below account name -- address container isn't high enough to display content.

![image](https://user-images.githubusercontent.com/12788627/35332280-6d1f1c4c-0102-11e8-849d-64fa864881b0.png)

**Comment by danfinlay** [comment]
I believe @tmashuang fixed this in master, is that right? Should be fixed & deployed soon?

**Comment by tmashuang** [comment]
Should have been fixed in master(#2929). The Firefox addon needs to be reviewed by the Firefox code auditors and are behind a few versions.

**Comment by bdresser** [comment]
this is fixed in production on both old and new UIs
