### ISSUE TITLE
How to recover my matamask wallet account dissapear from my browser and I tried to recover using my 12 written seed passphrase words but it says invalid seed words. I am in a dilemma. Help.

### ISSUE THREAD

**Issue by Woods8** [MetaMask/metamask-extension#3080]

**Comment by danfinlay** [comment]
Please refer to #3061 for steps to try.

If those don't work, please email support@metamask.io for personal support.

**Comment by anywalletrecovery** [comment]
we have several powerful rigs as well as efficient software to find lost word or password
here is a summary of what we do:
if you have access to your faulty recovery phrase we will do following phases to repair the typos in it:
1. we use artificial intelligence to reorder the words in 479001600 new combination to locate the one that creates your target account
2. we use artificial intelligence to edit the words in seed with similar words to locate the one that creates your target account
3. we use artificial intelligence to edit the words in seed with all other 2048 words to to locate the one that creates your target account
4. we use artificial intelligence to edit the words in seed with similar words and reorder the words in 480 million new combination to locate the one that creates your target account
  you can reach us by gmail or telegram
