### ISSUE TITLE
Firefox - limited to seeing 3 tokens max

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3081]
"On Chrome a scroll bar appears when you add more than 3 tokens, but not 
on Firefox so you can only see the top 3 tokens."

This issue came from support ticket https://secure.helpscout.net/conversation/509033261/2491/?folderId=1795595

**Comment by tmashuang** [comment]
Should have been fixed in master(#2929), are you building MM locally or from the Firefox addon store? The Firefox addon needs to be reviewed by the Firefox code auditors.

**Comment by danfinlay** [comment]
Yeah we're rolling this fix out today, thanks to Thomas's fix, will be out soon.
