### ISSUE TITLE
MetaMask account recovery

### ISSUE THREAD

**Issue by JanNowak69** [MetaMask/metamask-extension#3093]
I've registered MetaMask account and imported my other wallet by importing private key.
Now I have 2 accounts and the one I imported is "loose". I've checked FAQ and it means this account will not recover if I have to reinstall metamask and recover it by using "seed" words.

I wonder, if I will use this "loose" account as the main one. I will have 20 different tokens there + some ethereum...once my metamask get's deleted, I will recover it from old "seed" + I will import private key from the other account which will become "loose" again. Will it recover all of the coins?
I've heard somewhere that once account have more tokens, addresses etc. than some certain number, more private keys are created to handle it. If I have only 1 private key backed-up, is it possible that I will loose some of the tokens? Or there is only one private key per account, no matter how many different tokens are stored there?

**Comment by Zanibas** [comment]
One private key can carry all the tokens you want (though having all tokens in one address is not good practice). If you recover your private key again, you should not lose any of your tokens, of course assuming that you had your tokens all in that private key. If you put any tokens in addresses generated by your seed phrase, your seed phrase should allow access back into those accounts as well.

**Comment by JanNowak69** [comment]
How to find out if all tokens are on the same private key?

**Comment by danfinlay** [comment]
You have to check for those tokens either on a block explorer like etherscan, or by adding them to your token list in MetaMask.

Any other questions on usage please email support@metamask.io
