### ISSUE TITLE
Allow users to manage custom networks

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3102]
- [ ] Allow users to nickname networks
- [ ] Allow users to remove networks

As suggested by @alex-miller-0 [here](https://github.com/MetaMask/metamask-extension/pull/2815#issuecomment-360607421).

**Comment by alex-miller-0** [comment]
Not just remove default networks, but any saved network.

**Comment by lazaridiscom** [comment]
related: #3604

**Comment by bdresser** [comment]
We now allow nicknames & removal for all custom RPC networks. This is probably as far as we'll go for now to prevent newer users from removing defaults and not knowing how to reconnect.
