### ISSUE TITLE
Meta Mask Hacked?

### ISSUE THREAD

**Issue by Mrtwizzle** [MetaMask/metamask-extension#3105]
Meta mask logged me out and I had to sign up to DEN? giving a new password. Re instated my old meta mask account but funds taken out.  Unknown where there going.  0.05ETH taken.

![new project](https://user-images.githubusercontent.com/35832490/35430666-3df9daf2-02b4-11e8-8e9b-042a9750edf3.jpg)

No sent funds in history.  I thought maybe it returned back. Different address.  I have no clue where it's going or who's this address is.
Any ideas.  Hacker got me?
Thanks

**Comment by Mrtwizzle** [comment]
Found the error.  Continued with new "send" requests, while the old ones had not being cancelled.  e.g.  send request show error, wrong GAS price entered.  Send again in a new request and the old one although in error then goes to PENDING.  Click the gas price hyperlink and hit REJECT.  Had 3 all ready to go off as soon as new funds were loaded.  Normally if something says error or wrong data it's normally automatically cancelled.  Also managed to log into my old account and the mistake was easy to find. Should be a warning about pending requests and not 3 dots to work it out.  Knowledge gained and this is all a learning experience.

**Comment by lehuuchung2304** [comment]
Hi, 

I had issue with meta mask near 2 days ago. I had lost all my eth balance and ERC 20 token. Can any one can help me to got it back ? @.@

**Comment by Mrtwizzle** [comment]
Scary, Meta keeps updating my REJECTED transactions to pending.  That was my problem.  If you did't hit the REJECT and added a new payment, as soon as you but more ETH it just sends it off to the address you've already paid.  As for for your tokens they can't be spent? Good luck with Meta as I've been waiting a week and no contact of this problem...

**Comment by tmashuang** [comment]
I believe this is the issue you are referring to https://metamask.helpscoutdocs.com/article/37-ghost-accounts-ether-sending-away-whenever-funding-an-account. Since 'Rejecting' a transaction once it has been sent does not actually cancel it.

**Comment by lehuuchung2304** [comment]
It not actually the problem, so up to now, any update for this case ?
please advice.

2018-03-13 21:35 GMT+07:00 Thomas Huang <notifications@github.com>:

**Comment by tmashuang** [comment]
@lehuuchung2304 email support@metamask.io with your Ethereum address and state logs.

**Comment by lehuuchung2304** [comment]
Hi tmashuang, 

What you mean when mention: "@lehuuchung2304 email support@metamask.io with your Ethereum address and state logs.". Please instruct more.

**Comment by lehuuchung2304** [comment]
Hi Thomas,

I have create my new eth wallet as:

   0x4D846B7584b64205BA2282bafFe2c23c5387A183
   Please instruct more, the old wallet was suspicious for hack so I clear
   all from my Computer.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-13 23:05 GMT+07:00 Thomas Huang <notifications@github.com>:
