### ISSUE TITLE
Invalid JSON RPC response: undefined

### ISSUE THREAD

**Issue by dsslimshaddy** [MetaMask/metamask-extension#3107]
```
const web3 = new Web3(window.web3.currentProvider);
const instance = web3.eth.contract(abiArray).at(address);
const count = await instance.getCount.call();
```

It works when using this instead
`const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));`

metamask is connected `window.web3.currentProvider` outputs `MetamaskInpageProvider{...}`

**Comment by danfinlay** [comment]
The injected web3 does not return promises, it accepts callbacks. Try [ethjs](https://github.com/ethjs/ethjs) for a promise-based interface.
