### ISSUE TITLE
Zero token shows up after withdraw from Ether Delta

### ISSUE THREAD

**Issue by tetevi** [MetaMask/metamask-extension#3110]
Having a problem here, bought some tokens on ether delta & withdrew to meta mask. Etherscan shows the transaction was complete but under my tokens I have 0 tokens but i can see it available for deposit on ether delta. I'm I missing something here? I'm totally lost at this point. [](https://ibb.co/fWtH1w
https://ibb.co/nfdH1w
https://ibb.co/geNXZG)

**Comment by tmashuang** [comment]
Have you added the token contract address to the token list with the correct decimal precision?

**Comment by tetevi** [comment]
yes, i have.

**Comment by tmashuang** [comment]
Seems that the WAN has been transferred back and forth to Etherdelta and finally to an address. Referenced here. https://etherscan.io/address/0xa6c614d988f8baef23dc276bf23c90d1a7720d9c#tokentxns. Do you have any indication as to the nature of these transactions?

**Comment by tetevi** [comment]
yes that's me doing all those transfers. some how this token has 2 contract addresses. I finally have it in myetherwallet. is it possible to have 2 contract addresses for one token?

**Comment by tmashuang** [comment]
It depends on how the token operates, there could be different contract address that handle different operations.
