### ISSUE TITLE
Metamask / Chrome hacked?

### ISSUE THREAD

**Issue by desertedisland** [MetaMask/metamask-extension#3115]
I sent half an ether to my Metamask wallet and saw the balance right there. About 30 seconds later the Ether was gone with no input from myself. You can see the sequence of transactions at:

https://etherscan.io/visualizer?tx=0xc555e815036c4f9486f6d027ae30e2c26422970b29bd3bb0fb2f9dba64f6738d&type=txn . (you need to click on the first address to see the transfer out). All of the Ether straight in and straight out. I have no knowledge of the second account (and can't find anything about it) except that it seems to do nothing but accumulate ether.

There may be something else going on (perhaps a Chrome or Windows hack) but people really need to know about this.

**Comment by desertedisland** [comment]
Update: Metamask assigned me an account that belonged to someone else. So when I copied the address for that account and sent money to it, the money went in and the person was able to take it straight out - they did not need any private keys or anything.

**Comment by desertedisland** [comment]
Further update.

This has occurred because I was developing using Ganache and Metamask yesterday. I connected to Ganache with Metamask (i.e. a different network) and created an account by importing the private key from Ganache.

This morning I switched accounts in Metamask to the main Ethereum network and sent Ethereum to, yup, the Ganache account, all of which was accepted and processed. Clearly someone (probably lots of people) have used the seed words from Ganache to access the same accounts on the Ethereum network and are creaming off *tens of thousands* of dollars due to this issue. 

Is this my fault? Really? I lost 700 fucking dollars this morning. Is it *really* impossible for Metamask to know which network an account was created on?

**Comment by danfinlay** [comment]
Really sorry this happened to you, I've sent word to Ganache, I hope they remove the "default phrase" feature.

**Comment by iamjaime** [comment]
You are not the only one encountering issues with this! 
I got robbed for 0.25 Ether ($214.03) Today and 0.217597433 Ether ($186.37) last night!

I think i'm going through the same exact thing!

I sent money to myself from a different ethereum address to my Meta Mask and it automatically was forwarded to a different address!

I think Meta Mask got hacked and we are paying the consequences for it!

**Comment by danfinlay** [comment]
@iamjaime Your issue is different from this one. Please don't go around our issues trying to claim common bugs, it isn't productive. I hope you've sent your state logs into support, that's the only place we can look into what actually happened.
