### ISSUE TITLE
Updating the amount to be sent if not enough gas

### ISSUE THREAD

**Issue by mpepito13** [MetaMask/metamask-extension#3118]
This is not an issue, more a request. Sorry if this not in the right place.

I have 0.2 ETH in my wallet. If I want to empty my wallet, I first have to calculate the fee then putting the right amount. If I'm wrong, I have to reject the request ("reject" although I didn't request anything yet), then coe back at the begining.

I would like the amount to be updating accordinly while adjusting the gas and gwei.

What do you think ?

**Comment by tmashuang** [comment]
There could be two solutions relating to this issue. Gas transaction fees are less than the decimal precision provided in the total amount shown. We could increase the decimal precision shown, or we can add a 'Send Max' Button that calculates an adequate gas limit/price and the balance, which was the direction we were going.

**Comment by mpepito13** [comment]
I would vote for the second solution and its 'Send max' button. Thanks

**Comment by bdresser** [comment]
"Send Max" is in production on the new UI.
