### ISSUE TITLE
Meta: Transaction Failed

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3135]
Seeing a lot of "Transaction Failed" reports in sentry. Here are some of the reports.

- "Error: intrinsic gas too low" `gasLimitSpecified: False`
user manually lowered gasLimit too low on contract publish https://sentry.io/metamask/metamask/issues/438684339/events/13110590368/

- "Error: intrinsic gas too low" `gasLimitSpecified: False` contract data
bug: gas calc failed because dest is non-contract account but data is not empty 
https://sentry.io/metamask/metamask/issues/438684339/events/13083433916/

- "Error: [ethjs-query] while formatting outputs from RPC 'undefined' for method 'sendRawTransaction' Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 66 utf8 byte hex (chars: a-fA-F) string, is 0 bytes"
maybe failing on some omitted fields?
https://sentry.io/metamask/metamask/issues/438684339/events/13110567286/
```
txParams: {
  data: 0x8588b2c50000000000000000000000000000000000000000000000000000000000000000, 
  from: 0x627306090abab3a6e1400e9345bc60c78a8bef57, 
  to: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
}
```

- "Error: nonce too low" `nonceSpecified: True`
dapp suggesting bad nonce
https://sentry.io/metamask/metamask/issues/438684339/events/13102508520/
https://sentry.io/metamask/metamask/issues/438684339/events/13094238067/

- "Error: replacement transaction underpriced" `nonceSpecified: True`
dapp suggesting bad nonce
https://sentry.io/metamask/metamask/issues/438684339/events/13101444149/
https://sentry.io/metamask/metamask/issues/438684339/events/13083469951/

- "Error: replacement transaction underpriced" `nonceSpecified: False`
probably bad metamask/infura behavior
https://sentry.io/metamask/metamask/issues/438684339/events/13091497538/
https://sentry.io/metamask/metamask/issues/438684339/events/13094303267/

- "Error: nonce too low" `nonceSpecified: False`
probably bad metamask/infura behavior
our nonce details are not very clear -- an off-by-one could be hiding in there (`latestUsedNonce` vs `nextNonce`)
https://sentry.io/metamask/metamask/issues/438684339/events/13101415666/
```
{
  "local": {
    "details": {
      "highest": 581,
      "startPoint": 581
    },
    "name": "local",
    "nonce": 581
  },
  "network": {
    "details": {
      "baseCount": 581
    },
    "name": "network",
    "nonce": 581
  },
  "params": {
    "highestLocalNonce": 0,
    "highestSuggested": 581,
    "nextNetworkNonce": 581
  }
}
```

- "Error: Specified nonce may not be larger than account's next valid nonce." `nonceSpecified: True`
bad nonce from dapp (?)
https://sentry.io/metamask/metamask/issues/438684339/events/13101406615/
https://sentry.io/metamask/metamask/issues/438684339/events/13083451280/

- "Error: invalid sender"
wat?? doesn't make sense. also `from === to`
https://sentry.io/metamask/metamask/issues/438684339/events/13094284098/

- "Error: VM Exception while processing transaction: out of gas" `gasLimitSpecified: False`
this happens on publish after signing, not part of gasCalc. could be onchain throw?
https://sentry.io/metamask/metamask/issues/438684339/events/13091495533/

- "Error: known transaction:" `nonceSpecified: True`
user doing same action twice + dapp suggesting bad nonce (?)
https://sentry.io/metamask/metamask/issues/438684339/events/13083447733/

- "Error: [ethjs-rpc] rpc error with payload {"id":281883120825,"jsonrpc":"2.0","params":["latest",true],"method":"eth_getBlockByNumber"} TypeError: NetworkError when attempting to fetch resource."
hmmm -- not sure, should be protected by retry
maybe we went offline and then sentry reported when it came online (?)
https://sentry.io/metamask/metamask/issues/438684339/events/13083440577/

**Comment by kumavis** [comment]
found a bug https://github.com/MetaMask/metamask-extension/issues/3136

**Comment by pointtoken** [comment]
Thanks for this -- helped me fix my bug which was a result of 
"Error: intrinsic gas too low" gasLimitSpecified: False contract data
bug: gas calc failed because dest is non-contract account but data is not empty"

For anyone else out there, if you are just sending eth and using ethjs, you have to have a data value, but you set it to null. If you set it to 0x00 it will fail with the above error.

**Comment by kumavis** [comment]
closing due to old age :older_man: :older_woman:
