### ISSUE TITLE
Confirmation does not auto open on Brave  

### ISSUE THREAD

**Issue by DaneWiid1** [MetaMask/metamask-extension#3137]
When creating a transaction in a dapp running in Brave, Metamask does not auto open to the signing screen.

**Comment by danfinlay** [comment]
Is there a particular site this is not working on? I don't have this problem on Brave.

**Comment by tmashuang** [comment]
Closing a duplicate issue, #3219 and opened on https://github.com/brave/browser-laptop/issues/13315.
