### ISSUE TITLE
cannot access my metamask account

### ISSUE THREAD

**Issue by General44** [MetaMask/metamask-extension#3138]

**Comment by General44** [comment]
cannot access my account just stays on loading when i press the fox in right hand corner.. cant see my wallets need help[

**Comment by tmashuang** [comment]
Some have encountered this issue and a potential solution would be to switch to one of the test networks then switch back to the main network.

**Comment by General44** [comment]
I ended up getting in after 12 hours but it’s happening again. This is gonna be a problem what else can I do because I have a trezor but it doesn’t show what’s in my etherwallet only metamask

Sent from my iPhone

On 30 Jan 2018, at 18:40, Thomas Huang <notifications@github.com<mailto:notifications@github.com>> wrote:


Some have encountered this issue and a potential solution would be to switch to one of the test networks then switch back to the main network.

**Comment by danfinlay** [comment]
This sounds like #2548. We are already working on a fix, but in the meantime you can work around it by switching the top left network to another one and back again.

**Comment by josephjomon** [comment]
my metamask account stays in the loading state like forever with the message'ACCESSING UNKNOWN NETWORK' i am not able to view any of my accounts or networks. 
It would be really great if someone would help me.
