### ISSUE TITLE
Possible flaw when using metamask Chrome extension with etherdelta.com and myetherwallet.com

### ISSUE THREAD

**Issue by ovidiu-pislaru** [MetaMask/metamask-extension#3139]
I recently had an issue with my wallet being hacked while operating on etherdelta.com
I only used metamask to login to etherdelta.com and I suspect that my private key was stolen.

I used Google Chrome Version 64.0.3282.119 (Official Build) (64-bit) with Metamask  3.13.8 on a MacBook Pro on an OS X El Capitan (10.11.6).

**Comment by danfinlay** [comment]
Could you provide more details about why you think you were hacked? Maybe open a ticket with us on support@metamask.io?
