### ISSUE TITLE
Can't open MetaMask

### ISSUE THREAD

**Issue by grooveasylum** [MetaMask/metamask-extension#3141]
I installed MetaMask and when I go to open it, it displays a Privacy Statement. There is an orange "Accept" button that doesn't do anything. I can click on it a thousand times... nothing.

In short, I cannot get past this screen.

![accept-error](https://user-images.githubusercontent.com/35968487/35578982-c931a9ba-05a2-11e8-8796-e2cdc75c2922.PNG)

I have uninstalled/ reinstalled the extension a dozen times, restarted my browser, my computer, nothing...

**Comment by tmashuang** [comment]
Are you on a second monitor with a different text size?

**Comment by grooveasylum** [comment]
I am on a second monitor, I use 6 monitors G. WadeFounderMIDDLE MANN LLC  |  middlemaan.com 602.206.2100  |  mail@middlemaan.comIG: @iammiddlemannFacebook: @iammiddlemannTwitter: @iammiddlemann


-------- Original Message --------
Subject: Re: [MetaMask/metamask-extension] Can't open MetaMask (#3141)
