### ISSUE TITLE
Add a "reset account" feature to Settings

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3147]
To alleviate pain from #1999, we could add a button in settings that wipes the current account's transaction history. This would allow developers resetting a test blockchain to continue using MetaMask without having to reinstall.

**Comment by brunobar79** [comment]
@danfinlay  Just submitted #3155.  LMK what you think!

**Comment by wbt** [comment]
#3155 seems to clear out all transaction history for all accounts on all networks, which seems like more of a wipeout than desired.  Would it be possible to right-click on the Network in the network drop-down, or the Account in the account drop-down, and have a menu (with more than just "Inspect") option to rest that network/account history only?

**Comment by brunobar79** [comment]
@wbt  it does not.  It takes all the transactions for the selected network and it deletes the ones for  the selected account. (I fixed that in the last 2 commits)

**Comment by wbt** [comment]
I think the slight confusion about what the button will do is just a UI issue with placement. Might it make more sense to put it at the bottom of the list of transactions, if that list is non empty?
Also, would it make sense to call it "Clear Transaction History" to make it clearer what it does, or am I missing something else that it does?

Thanks for your work on this!

**Comment by danfinlay** [comment]
> I think the slight confusion about what the button will do is just a UI issue with placement. 

This button could cause problems for normal users, so I prefer to have it somewhere inaccessible and unlikely, like where it is now. The plan is to eventually auto-detect network changes and do this automatically anyway, so it should be increasingly rare that anyone needs to do this manually.

**Comment by kyriediculous** [comment]
This button seems to be gone in the new version for firefox?

**Comment by danfinlay** [comment]
Firefox has actually not accepted a MetaMask update in a little while, the Firefox version is a bit outdated. We should be getting it up to date with our next release with a little luck, though.
