### ISSUE TITLE
Metamask generated new address after disabling Chrome extension?

### ISSUE THREAD

**Issue by essek85** [MetaMask/metamask-extension#3149]
Hi, I guess I just lost a 1000 dollars.. :( But I hope someone might be able to help me!

So this is what happened.

1. I store all my ERC20 tokens in MEW. I use MetaMask Chrone extension on my homecomputer.

2. While at work, I was going to by TRAC from EtherDelta. I was on my workcomputer and had to disable the MetaMask extension to be able for purchase TRAC from EtherDelta.

3. I sent the TRAC tokens to my MEW address, the same address I have used for a long time:
![skjermbilde 2018-01-30 kl 23 28 33](https://user-images.githubusercontent.com/35977503/35594957-5b223840-0615-11e8-992a-9132261f6615.png)
As shown on the attachement, I have sent OST, ICX and others to the same address. 

4. When I got home and logged on my homecomputer, I had to enable MetaMask in Chrome. 

5. I logged into to MEW and all my tokens where there except from TRAC!

6. My MEW public address had changed!? If I paste my old address into MEW, I can see the TRAC tokens - but Im not able to log into that MEW account anymore.

![skjermbilde 2018-01-30 kl 23 32 44](https://user-images.githubusercontent.com/35977503/35595168-ffdd34fc-0615-11e8-8801-a26784ba6bf3.png)

7. I freaked out, and transfered all my tokens back to binance from my MEW address....

I have tried to restore MetaMask with the seed, but it will only restore the "new" address.

**Comment by danfinlay** [comment]
1. I take it you have MetaMask on both home and work computers?
2. I don't know why you'd have to disable MetaMask to use EtherDelta. MetaMask makes EtherDelta safer to use.

It sounds like you *might* be having a problem with EtherDelta accounts: http://metamask.helpscoutdocs.com/article/8-etherdelta-account-management-tips

Could you paste the mew address you expected to see, and the one you ended up seeing at the end instead?

Have those accounts ever been part of MetaMask, or did you just import them on your work computer?

If you only imported this on your work computer, you probably need to import it on your home computer too.

**Comment by metamaskfan** [comment]
HI 

I cannot log in to my meta mask wallet address and while i tried to retrieve using 12 phrase and password it created new address.
How to retrieve my old wallet ?  I have 12 phrase and password with me .But it only opens the new wallet.There are no sign of old wallet at all.
I can send you my wallet address if required.

**Comment by danfinlay** [comment]
You can email us for support at support@metamask.io 

This is someone else’s question, I don’t want to mix it up.

**Comment by Sharehearts** [comment]
same here , this is fucked up.  but I'm not giving up my tokens ,  that was not just money .     it was important to me .               tell me if any of you could solve this problem .  I'll give you reward .  thank you

**Comment by nickjuntilla** [comment]
It might be because you're using the default ganache seed.

**Comment by damster7** [comment]
COMMENT PROCÉDER POUR AVOIR LA BONNE CONVECTION
