### ISSUE TITLE
Security error accessing local storage

### ISSUE THREAD

**Issue by quantumproducer** [MetaMask/metamask-extension#3152]
I'm just using a React app, I think local storage here is coming from React State? Is this intentionally off by default?

SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
▼ 23 stack frames were expanded.
(anonymous function)
node_modules/web3-eth-accounts/src/index.js:474
./node_modules/web3-eth-accounts/src/index.js
http://67.205.174.88:3000/static/js/bundle.js:97704:30
__webpack_require__
/root/keystore/buy/webpack/bootstrap 5e81087b2605f028037e:678
fn
/root/keystore/buy/webpack/bootstrap 5e81087b2605f028037e:88
./node_modules/web3-eth/src/index.js
node_modules/web3-eth/src/index.js:36
__webpack_require__
/root/keystore/buy/webpack/bootstrap 5e81087b2605f028037e:678
fn
/root/keystore/buy/webpack/bootstrap 5e81087b2605f028037e:88
./node_modules/web3/src/index.js
node_modules/web3/src/index.js:33
__webpack_require__

**Comment by tmashuang** [comment]
There could be a couple issues here, the first would be to if the Chrome settings are blocking all third-party cookies and site data under chrome://settings/content/cookies.

**Comment by danfinlay** [comment]
Could you provide a reproduction repo for us to try debugging with?
