### ISSUE TITLE
Develop Script for New Intro Video

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3162]
[Our beloved intro video](https://www.youtube.com/watch?v=6Gf_kRE4MJU) has served us since July 14, 2016, when our audience was composed of a few dozen developers, and the hope that useful applications would one day be built on Ethereum was just that, a hope.

Well, the popular applications are here, from crowdfunding and exchanges to digital collectibles, and we're introducing thousands of new users to Ethereum every day, so we've known for some time that we're due for a better explanation.

Given MetaMask's position as a log-in for many Ethereum enabled sites, we end up often forming the first impression that the entire Ethereum ecosystem gets to make on new visitors to this domain. That's a big responsibility!

Rather than developing this script and video entirely in a black box, I thought it might be fun to open the floor for comments and suggestions. What do you think is important that users understand when logging into a web3 site for the first time? What can be left out? What absolutely can't?

I'll include some of my thoughts in a later post, but first, I want to leave this question open to the public for a while.

**Comment by bdresser** [comment]
if we're really shooting for a general population user base, it could make sense to start with the big picture and walk through the evolution of applications: 

local programs where you're running the whole thing on your machine --> web apps w/ password-protected access to your data --> decentralized apps where you keep your own secret safe & prove ownership w basic crypography

**Comment by danfinlay** [comment]
Did a quick scan of my notes for possible scripts to mine.  Here's one:

You're going about your way, trying to use a web site, and it asked you to use MetaMask just to log in, so what gives?

When you sign into a website with MetaMask, you aren't signing into some central server and asking them to store your password, instead you're using modern cryptography to store your personal secrets locally, putting you in control of your own security.

This let's you connect to networks of computers that have no central authority, and exist only peer to peer, like Ethereum and IPFS. MetaMask lets websites experiment with some of these cutting edge networks. 

The difference may not sound like much, but let's look at some examples of web sites that are only possible with personal key management and peer to peer networking like MetaMask...

**Comment by danfinlay** [comment]
Here's the outline I used to write the original video's script:

Outline:
- Welcome to MetaMask!
    - In this video I’m going to talk about what MetaMask is, and why someone building a web app on the Ethereum blockchain might care.
- Ethereum is awesome.
    - It lets anyone issue their own currencies
    - create fair-trade supply chains
    - crowd fund projects for equity
    - let that equity be traded
    - use that equity to vote on expenditures.
    - and so much more
- But once you try to make an actual Distributed App, or Ðapp, it’s not so simple.
    - Some Ðapps require you to upload your private key (insecure!)
    - Some require you to be running a local blockchain server that automatically approves all transactions (also insecure!)
    - Some just ask you to enter commands in your terminal (is that even a web app anymore?)
- Fortunately, the Ethereum foundation declared a standard for this.
    - The web3 Javascript API is a javascript object that should be available in any blockchain-dependent environment.
    - It’s the same object that is exposed in command-line Ethereum consoles like go-ethereum.
    - The Ethereum Foundation’s own Mist browser plans to support this API.
    - To use it, all you have to do is check if the browser has exposed it.
- Mist isn’t ready yet.
    - It’s still under production
    - It easily takes twelve hours just to synchronize the client, before it can be used to do anything, although SPV with FastSync should improve that a bit.
- MetaMask has an answer.
    - By putting Ethereum identity management in a browser extension, we give the same private-key management of a custom-built solution like Mist, but with a one-click installation.
    - While you can run your own blockchain node, we host one by default, so new users are up and running in seconds, not hours.
    - Every time a Ðapp tries to write to the blockchain, the user gets a chance to review the transaction, and approve or reject it.
        - Long term we’re committed to making these transactions easier and easier to review intelligently, so the public nature of the contracts isn’t wasted by being indecipherable.
    - MetaMask’s beta is available now.
        - You can start developing your Ðapps today.
        - Stop worrying about how to connect to the blockchain.
        - Stop worrying about user management in your applications.
        - Focus on what matters to you, creating tools that are meaningful to people.
- To get started, click this link to download the extension today.
    - Check out one of our tutorials to get your dev environment working smoothly.
    - If you have any questions, reach out to us in the comments, or on our Slack or Github.
    - We hope we can help build an Ethereum web that’s easier to use and develop for, so please let us know if there are any other ways we can help.  Build on!
