### ISSUE TITLE
Cannot log in metamask after 6 hours of sleep

### ISSUE THREAD

**Issue by whyalwaysldm** [MetaMask/metamask-extension#3165]
I logged in metamask last night, after that I disable metamask extension in chrome. 

In the morning I wake up and enable it for some checking, but I cant log in as metamask continue saying my password is incorrect (It can't be the case because I logged in metamask quite frequently). 

I think the reason is not because I disabled metamask extension on my chrome.

I use Chome on Window 10.
![123](https://user-images.githubusercontent.com/36024817/35662158-42b50078-0749-11e8-9cd2-64aeae6ac9f5.png)

**Comment by danfinlay** [comment]
As long as you copied your seed phrase, you can reset your password by clicking "Restore from seed phrase".

If you have any other user questions, please submit them to support@metamask.io, and we'll help you in the order you request.
