### ISSUE TITLE
Add "expert mode" in settings

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3169]
Some options are just too advanced to show to normal users.

By adding an "expert mode", we can allow experts to opt in to more advanced options (like gas limit, nonce).

**Comment by brunobar79** [comment]
@danfinlay I would like to help on this one. It would be cool to add a bit more context of which features to "hide" and discuss about UI for toggling the dev mode. LMK!

**Comment by danfinlay** [comment]
Two candidates could be `gasLimit` and `nonce` on the tx confirmation/editing screens.

**Comment by yazeed** [comment]
Agreed, we need this to resubmit/override pending transactions. Specially ones that metamask isn't detecting in the transactions list anymore.

**Comment by dpyro** [comment]
It might even be possible to include these options in the main UI with some judicious design. Manually setting `nonce` is a crucial feature for transaction management.

**Comment by bdresser** [comment]
closing in favor of https://github.com/MetaMask/metamask-extension/issues/4254
