### ISSUE TITLE
web3.currentProvider becomes null after first loading of accounts

### ISSUE THREAD

**Issue by quantumproducer** [MetaMask/metamask-extension#3178]
The first call of this function shows an alert with [Object object];
10 seconds later, per the timeout interval, "null" shows. Then I am unable to load the accounts from the web3.eth.getAccounts callback.

I am not setting web3.currentProvider anywhere in the entire project.

On Firefox. Just updated MetaMask today ( 2 minutesa go), bug still persists.

```
static loadAccounts() {
    let web3 = window.web3;
    
    if (!web3) {
      Pubsub.publish('metamask-accounts', {hasMetamask: false});
      setTimeout(Merchant.loadAccounts, 1000);
      return;
    }    

    alert(web3.currentProvider);

    web3.eth.getAccounts(function(a,b) {
      Merchant.accounts = b;
      console.log("Merchant accounts: " + Merchant.accounts);
      if (b && Merchant.accounts.length > 0) {
        Pubsub.publish('metamask-accounts', {hasMetamask: true, account: Merchant.accounts[0]});  
      } else {
        Pubsub.publish('metamask-accounts', {hasMetamask: true, account: null});  
      }
      
    });
    setTimeout(Merchant.loadAccounts, 10000);

  }
```

**Comment by frankiebee** [comment]
Can you get this to happen consistently? also if possible link me to a repo where this is being reproduced in so i can try it myself? I cant get it to reproduce.

**Comment by frankiebee** [comment]
@quantumproducer sorry to hear this. It could you check the background logs ([here's](https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome) how) and tell me i fou see any error messages their

**Comment by danfinlay** [comment]
I suspect this is a local dev issue, so please ask the question publicly on Stack exchange:
https://ethereum.stackexchange.com/

We'll look at it when we can, but it's unlikely this is a bug on our end, and our github is reserved for bugs and issues, not usage questions.
