### ISSUE TITLE
Where Metamask saves keystore?

### ISSUE THREAD

**Issue by SPASoman** [MetaMask/metamask-extension#3183]
Hello everybody.

An unpleasant incident. At one point, chrome itself was logged out of my account on the PC (some kind of failure probably), and all the settings of the Chrome extensions was lost.

I used Metamask to import there the keyster of the main wallet, so I created a new account (that seed has not been saved anywhere).

But on ISO Comsa accidentally indicated the purse that created the Metamask. I wanted to flip but decided to hold. Now, I have a wallet address, a password for a keystore, and basically a copy of the folder "userdata" from chrome (but afterward as a metamask flew off!).

The extensions themselves have not been lost, only extensions settings. 
Therefore, I have a hope that somewhere in that folder metamask holds a keystore or something like that.

 

What I tried to do -
The program for recovering deleted files. No chance.
Re-logged several times in chrome, delete and install a metamask, etc.
I have searched all my seed and keystore. I don't have keystore or seed for that wallet.

 Maybe someone has an idea, where a metamask keeps a gift. Since the extension was not removed, there may be a chance.

Or just invested in the economy of the Japanese? :)

**Comment by Bener3** [comment]
OMG, I HAVE THE SAME PROBLEM TODAY. When i open my computer, i see a new account screen on metamask and now cant reach my old account. I have a seed phrase only not private key.

**Comment by tmashuang** [comment]
The seed phrase for accounts is the primary way to back up multiple accounts, keystores are for individual accounts. Secondly, MetaMask allows the feature to download a file for MetaMask's seed phrase if users prefer not to hand write it down when first creating a seed phrase. If individual accounts are preferred to manage, we also allow exporting individual private keys under the three horizontal dots icon.
