### ISSUE TITLE
Question on security

### ISSUE THREAD

**Issue by docloulou** [MetaMask/metamask-extension#3187]
I know that there are 2 way to generate address from Mnemonic seed (from Extended Private Key and Extended Public Key). 

What i can't understand is that Metamask doesn't re-ask password to generate another address (add account) and datas in LocalStorage are still encrypted during that.

So my question is: what they use to generate another address ? (cached Extended Public Key ?...)

Thanks

**Comment by docloulou** [comment]
i thinks i have my answer: the password is store in the background.js instance and can be call by popup.js at any moment.

The fact is you can show your password as plain text with a console.log command until you lock your account ---> someone can confirm ?

**Comment by danfinlay** [comment]
Hi doc, sorry for the slow reply.

There is no console.log that will show either the password or seed phrase, from either a visited Dapp or the metamask UI.

The seed phrase is stored in memory when MetaMask is unlocked, and this allows additional account key pairs to be generated when the UI requests this, but the secret key is never passed to the user interface, except for the "reveal seed phrase" or "export private key" pages, both of which require a correct password for the background to return them.
