### ISSUE TITLE
Invalid prop `selected` of type `number` supplied to `AccountDropdowns`, expected `string`.

### ISSUE THREAD

**Issue by whydna** [MetaMask/metamask-extension#3188]
When connecting to the Main Network, everything works as expected. When connecting to the Ropsten Test Network, the extension popover is completely blank, and the console spits out a bunch of errors (see screenshot). 

This was working a few weeks ago.

  *  Expected Behavior
UI loads and I can see my balance + transactions.

  *  Actual Behavior
UI is blank and I need to restart Chrome. 

  *  Browser Used
Chrome Version 64.0.3282.140 (Official Build) (64-bit)

  *  Operating System Used
MacOS 10.12

<img width="372" alt="screen shot 2018-02-04 at 1 56 52 pm" src="https://user-images.githubusercontent.com/177505/35781081-4cc62e68-09b3-11e8-9680-4ca5f5c6ec5b.png">

<img width="814" alt="screen shot 2018-02-04 at 12 36 15 pm" src="https://user-images.githubusercontent.com/177505/35780366-480276ee-09a8-11e8-917d-0ee8f026eb4b.png">

**Comment by frankiebee** [comment]
@whydna sorry to hear this. Could you check the background logs (here's how) and tell me if you see any error messages their it will help me figure out whats going on a little better.

**Comment by whydna** [comment]
@frankiebee did you mean to include instructions on how to get the background logs?

**Comment by frankiebee** [comment]
Yeah those are for the popup. I would like to know if their is any error messages in the background console https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome

**Comment by bdresser** [comment]
Fixed in production - if you're still having trouble feel free to open a new issue.
