### ISSUE TITLE
PropTypes will no longer be accessible from the main React package

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#3192]
FYI, MetaMask is reporting the following Console warning:
>Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

This seems likely to be a consequence of several lines in the codebase which look like one of these:
`import React, {Component, PropTypes} from 'react' `
or
`const PropTypes = require('react').PropTypes`
and which maybe should be replaced with 

`import PropTypes from 'prop-types'; // ES6`
or 
`var PropTypes = require('prop-types'); // ES5 with npm`

per [official documentation](https://github.com/facebook/prop-types#prop-types).

**Comment by frankiebee** [comment]
@alextsg or @danjm is this fixed in uat?

**Comment by alextsg** [comment]
@frankiebee most have been fixed but I'll go through and double check

**Comment by frankiebee** [comment]
cool closing this issue then if fixed in uat branch
