### ISSUE TITLE
NewUI - Make gas price editable on confirm tx screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3202]
I know we've gone back and forth on this, but I'm taking the position that gas editing is fundamental enough that it belongs even on the final tx confirm screen. @cjeria

**Comment by JohnAllen** [comment]
Isn't it already editable?  One can click up and down and adjust the `price` and `gas limit`

**Comment by danfinlay** [comment]
The NewUI tag refers to the uat branch.

**Comment by bdresser** [comment]
@danfinlay @danjm unless this is referring to a different screen, it seems like gas price is editable already:

<img width="351" alt="screen shot 2018-05-30 at 4 27 36 pm" src="https://user-images.githubusercontent.com/1016190/40753914-3c56da8c-642b-11e8-83e7-f164780fa634.png">

it does overlap with where it says `ETH` which i will file separately.

**Comment by danfinlay** [comment]
I agree, looks like it.
