### ISSUE TITLE
Hello ,the contract is published of my erc20 token but when I try to add the contract address it populates the symbol but it doesn't add the token.

### ISSUE THREAD

**Issue by ji2mma** [MetaMask/metamask-extension#3204]

**Comment by tmashuang** [comment]
Please provide the token/contract address for further investigation.

**Comment by ji2mma** [comment]
Hi Thomas,The address from is 0xad2951846de972274c611cf3565e00c4b0e57a2f

| 
| 
|  | 
Ethereum Account 0xad2951846de972274c611cf3565e00c4b0e57a2f Info

etherscan.io

The Ethereum BlockChain Explorer, API and Analytics Platform
 |

 |

 |



and the contract address is  0xae100cd6386debb9bf14133129d2d11daa9d0e02

| 
| 
|  | 
Ethereum Account 0xae100cd6386debb9bf14133129d2d11daa9d0e02 Info

etherscan.io

The Ethereum BlockChain Explorer, API and Analytics Platform
 |

 |

 |





Transaction  0x5b3c12dd8e9a4fd1d2247970193fe516550c20ffeff558dbc259cba941e66e28
Thanks for your support.
    On Thursday, February 8, 2018, 9:29:36 AM GMT+1, Thomas Huang <notifications@github.com> wrote:  
 
 
Please provide the token/contract address for further investigation.

**Comment by ji2mma** [comment]
Hello I have found my token .Thanks again for your support and I don't need it to be resolved.
Regards,
Adel
    On Thursday, February 8, 2018, 9:29:36 AM GMT+1, Thomas Huang <notifications@github.com> wrote:  
 
 
Please provide the token/contract address for further investigation.

**Comment by tmashuang** [comment]
May I ask what was the underlying issue and how you solved the issue?

**Comment by ji2mma** [comment]
I had different tokens from ropsten test and it was confusing from my main account to find the right one .
I checked by clicking on each one and it showed me the correct contract address.
