### ISSUE TITLE
web3.eth.accounts always returning only one selected account

### ISSUE THREAD

**Issue by siphiuel** [MetaMask/metamask-extension#3207]
Hi all,

I'm using MetaMask 3.14.1. There are 3 accounts in it. My issue is that `web3.eth.accounts` always returns a single-element array with just the account that is selected in MetaMask, but not the complete list of accounts.

E.g., suppose there are 3 accounts - `0xA...`, `0xB...`, `0xC...`. Account `0xB...` is selected in MetaMask. Then `web3.eth.accounts` will return `["0xb..."]`, but should return `["0xa...", "0xb...", "0xc..."]`.

**Comment by tmashuang** [comment]
We prevent this type of behavior to enable users to choose which "address and/or identity" to use with specific Dapps. It enables which accounts the users deems appropriate to interacted with a Dapps. The behavior can ways be changed when the Dapps have a reasonable and viable reason to access multiple accounts.

**Comment by royeom** [comment]
@tmashuang  I'm a student who is studying dapp.. Could you tell me what is viable reason which you said.. ? :) And I'll very very thank you if you explain about how can I get all of my accounts in MetaMask.

**Comment by mallapurbharat** [comment]
Shouldn't there be a way to make it possible for users to enable (through Metamask) certain accounts to be "visible" in the DApp? Right now, I don't see any such option to allow visiblity in Metamask.

**Comment by akumthek** [comment]
[25th June 2018 Monday 10:04 pm IST] well... i want to transfer my ERC tokens from one acc to other typically web3.eth.accounts[0] to web3.eth.accounts[1] I had hard time finding what the safeTransferFrom call was not working (some BigNumber error) finally realized that I do not have the second account at all ! 
   I am using reactJs and truffle (development) and have tried with Ganache as well. I guess web3 1.0
   For now I have just hardcoded second account, but of course i dont like it, as i keep swithching from Development to Ganache to Ropsten

**Comment by sowmyakannan** [comment]
Me too having the same issue. Have to hard code the second account, hoping to find a better way, like accessing the account as accounts[1], accounts[2]... etc.

**Comment by suchit001** [comment]
If you managed to solve your query can you please help with with it too? I am facing the same issue.

**Comment by httpJunkie** [comment]
How about calling `wallet_getPermissions`. The result will be an array, you can just read the first item of that array which has a property named `caveats`. As well inside the first item of its array there is a property named `value`. 

You could map over it and get all accounts in the wallet that are connected to the dapp. In React, a very crude way might look something like this:

```js
const GetPermissions = () => {
  const [permissions, setPermissions] = useState({})
  const [permissionRequested, setPermissionRequested] = useState(false)

  const requestPermissions = async () => {
    await window.ethereum.request({
      method: 'wallet_requestPermissions',
      params: [
        { "eth_accounts": {} }
      ]
    })
    .then((res) => {
      setPermissionRequested(true)
    })
  }

  const getPermissions = async () => {
    await window.ethereum.request({
      method: 'wallet_getPermissions'
    })
    .then((res) => {
      setPermissions(res[0])
    })
  }

  return (
    <>
      <Button handleClick={requestPermissions}>
        <p>Request Permissions</p>
      </Button>
      <Button handleClick={getPermissions}>
        <p>Get Accounts</p>
      </Button>
      <div>caveats.value: 
        { permissionRequested ?
          permissions.caveats[0].value.map(account => <div key={account}>{account}</div>)
          : null
        }
      </div>
    </>
  )
}
```

Here I have a button that requests permissions, this would prompt MetaMask to allow you to connect multiple accounts, then we have another button that calls `wallet_getPermissions` now I can print all accounts I'm connected to:
<img width="594" alt="Screen Shot 2022-05-20 at 2 17 58 AM" src="https://user-images.githubusercontent.com/4899480/169496990-8ef4eff1-6f90-47f9-9225-1fba9f0724f9.png">
