### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Maxishake** [MetaMask/metamask-extension#3211]
For a long time now I can not translate the etherium to buy EOS or any other purse. Help

if you can, please write in Russian

![image](https://user-images.githubusercontent.com/35490854/35993036-21340eb0-0d1d-11e8-8a4b-5dbfce5ffbc1.png)

![image](https://user-images.githubusercontent.com/35490854/35993053-2edabb90-0d1d-11e8-909b-cae95b1b823e.png)

![image](https://user-images.githubusercontent.com/35490854/35993063-35c2c2f4-0d1d-11e8-9526-9d3fed1eadb0.png)

**Comment by tmashuang** [comment]
Пожалуйста, напишите информацию о проблемах с токенами и обратитесь к `support в metamask dot io`.

Pozhaluysta, napishite informatsiyu o problemakh s tokenami i obratites' k `support v metamask dot io`.

**Comment by Maxishake** [comment]
какую именно информацию вам написать? к support в metamask dot io. это где именно?

**Comment by Maxishake** [comment]
не могу провести никакую транзакцию ни на какой кошелёк-вот и вся проблема
