### ISSUE TITLE
Design for Shapeshift transactions in New UI

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#3214]
When shapeshift transactions are shown in the transaction list in the new UI, we are using a design that borrows heavily from the shapeshift transactions in the old-ui. We might want to update these at some point.

<img width="1092" alt="screen shot 2018-02-08 at 11 01 51 am" src="https://user-images.githubusercontent.com/7499938/36004723-c6294476-0d0e-11e8-932a-bac68641c8d9.png">

**Comment by cjeria** [comment]
Good catch @danjm. I'll put this my shortlist of designs to pick up for new UI release epic.

**Comment by cjeria** [comment]
What other data can we pull from shapeshift transactions?
To addresses
Amount being transferred

**Comment by snreynolds** [comment]
I also noticed that the first couple of screens are a bit messed up in the new UI as well. Here is potential fix/update for the screen when users are first connecting to shapeshift. 
<img width="729" alt="screen shot 2018-06-21 at 2 01 49 pm" src="https://user-images.githubusercontent.com/30504811/41745609-5ca11220-755c-11e8-9b2a-49bd953c33c5.png">

**Comment by cjeria** [comment]
Good catch @snreynolds . Here's a screenshot of how it looks right now. Looks like it can easily be fixed (centered on the screen, padding fixed etc). We have specific react components already in place for pop ups such as this screen, so for now, let's stick to our current defined styles. 
![image](https://user-images.githubusercontent.com/597770/41747523-2496f19a-7563-11e8-93b0-17b6fe3b97e0.png)

**Comment by cjeria** [comment]
created a new issue for this UI bug https://github.com/MetaMask/metamask-extension/issues/4637

**Comment by bdresser** [comment]
Not going to have this block removing the old UI, moved out of epic~

**Comment by whymarrh** [comment]
We've dropped support for Shapeshift transactions, so this is unneeded now
