### ISSUE TITLE
Cannot Access My Wallet! Lost Key and Seed, only have password!

### ISSUE THREAD

**Issue by KyleSmiles** [MetaMask/metamask-extension#3217]
I took my computer in for repair and when they rebooted my computer, they also rebooted the MetaMask so it could not recognize I had signed in before. I tried to login, but it gave me a new account and I could not recover my old one. I lost my seed and the private key, but have the password which is a unique one. Can I recover my account with only the password?

**Comment by tmashuang** [comment]
MetaMask does not have any centralized servers to store any of this information. The seed phrase is the primary recovery for MetaMask vaults.

**Comment by martineezz** [comment]
@KyleSmiles If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
