### ISSUE TITLE
missing metamask 

### ISSUE THREAD

**Issue by TonyBuen** [MetaMask/metamask-extension#3218]
i cannot find my metamask wallet in my browser. how can i put it back?

**Comment by tmashuang** [comment]
Could it possibly be in the extension overflow list when a Chrome profile as too many extensions? This list can be found by clicking the three vertical dots next the extensions on the toolbar. To verify if MetaMask is installed, navigate to the extension list view in the particular browser.

**Comment by TonyBuen** [comment]
Thanx for your reply. Searched my history and it said might have been corrupted. It asked for a fix and it did. The only problem is that the other accounts are missing.Good thing tho is that metamask is back in my browser extension.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 10, 2018 at 5:49 AM, Thomas Huang<notifications@github.com> wrote:   
Could it possibly be in the extension overflow list when a Chrome profile as too many extensions? This list can be found by clicking the three vertical dots next the extensions on the toolbar. To verify if MetaMask is installed, navigate to the extension list view in the particular browser.

**Comment by Zanibas** [comment]
If you're still having this issue, can you try re-adding accounts from "add account" and see if that shows your other accounts?
