### ISSUE TITLE
TX pop up in Brave does not appear

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3219]
When buying a spaceship in etherspace.co in Brave, I'm expecting the tx pop window to appear just like in Chrome, but it doesn't. All that is visible is the badge notification. 

For feature parity, we should make the pop up appear as expected.

![image](https://user-images.githubusercontent.com/597770/36030609-cdb72550-0d9f-11e8-96d0-0d4e00ef41d0.png)

**Comment by tmashuang** [comment]
Unfortunately, we have no control over how Brave implements MetaMask. Will post an issue with the Brave project, here https://github.com/brave/browser-laptop/issues/13315.

**Comment by cjeria** [comment]
Thanks @tmashuang !

**Comment by jonathansampson** [comment]
How is the popup triggered? Perhaps we're missing an API on the Brave end (or our implementation is limited in some way).

**Comment by bdresser** [comment]
closing - duplicates several other open popup/rendering issues on Brave (eg #4782 )
