### ISSUE TITLE
Update Myetherwallet helpdesk links to MyCrypto

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3220]
Tayvano and the whole team left the MEW brand, and so it looks like this is the new token/ENS UI to recommend for the moment.

**Comment by DanielMReed** [comment]
Should either company be preferred? Should both not be included?

**Comment by danfinlay** [comment]
I think it's OK for us to prefer the interface that we have the best personal relationships with, which includes doing the best user support (keeping users from coming to us frustrated).

That said, we're adding our own token sending functionality soon, so this is not a high priority link overhaul.

**Comment by whymarrh** [comment]
A cursory look through the codebase makes me think that there aren't any remaining references to these links. I'm closing this for now, we can reopen it if I've missed anything.
