### ISSUE TITLE
Other Chrome extension has no access to web3 object

### ISSUE THREAD

**Issue by sergejmueller** [MetaMask/metamask-extension#3221]
An error occurs when i try to access to web3: _Uncaught ReferenceError: web3 is not defined_
The page works with a SimpleHTTPServer ([no file:// calls](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#globe_with_meridians-https---web-server-required)).

`window.web3` does not work too.
Any idea?

_manifest.json_
```
{
  "manifest_version": 2,
  "name": "Getting started example",
  "description": "This extension allows the user to change the background color of the current page.",
  "version": "1.0",
  "content_scripts": [
     {
      "matches": [
        "file://*/*",
        "http://*/*",
        "https://*/*"
      ],
       "js": ["main.js"],
       "run_at": "document_end"
     }
   ]
}
```

_main.js_
`console.log(web3)`

**Comment by 360disrupt** [comment]
It's a limitation of chrome content scripts they run in a Sandbox environment and have no access to ja vars on the page:
https://developer.chrome.com/extensions/content_scripts#execution-environment
