### ISSUE TITLE
INABILITY TO ACCESS METAMASK AFTER INSTALLING EXTENSON

### ISSUE THREAD

**Issue by ejaisco** [MetaMask/metamask-extension#3223]

**Comment by tmashuang** [comment]
Does it show up on the chrome extension list?

**Comment by ejaisco** [comment]
Yes it does and it is ticked as enabled

**Comment by tmashuang** [comment]
If it is not on the toolbar, is in the the overflowed extension list when clicking the three vertical dots?

**Comment by ejaisco** [comment]
It shows where the extensions usually show
