### ISSUE TITLE
Missing ETH

### ISSUE THREAD

**Issue by PrincipeAus** [MetaMask/metamask-extension#3227]
I attempted to buy during ICO but the Metamask stated the transaction Failed. I followed the advice of one of these posts and uninstalled the extension, then reinstalled it, but of course, there is no ETH on it as it is now a new profile. How do I get my ETH back and why did it show as Failed, but it also took my ETH?

**Comment by WestonReed** [comment]
What's the transaction hash?

**Comment by PrincipeAus** [comment]
0x23f3828a646d5e4e1a5835ce4b338eb10c74f0faf3e83c81125bd3890b9483c

Adam Robertson
Director
0421 908 277


On 13 Feb 2018, at 2:21 am, Weston Reed <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the transaction hash?

**Comment by danfinlay** [comment]
To restore your old account on a new installation of MetaMask, you just click "Restore from seed phrase" during the setup process, after agreeing to terms on the fresh installation.

The process is basically described here:
https://metamask.helpscoutdocs.com/article/28-using-metamask-on-multiple-computers

As long as you saved your 12 word seed phrase when first setting up, you can always restore the accounts that you were first given, on a fresh install, or another computer, or another client entirely!
