### ISSUE TITLE
I logged out :(

### ISSUE THREAD

**Issue by PenguinKnight1** [MetaMask/metamask-extension#3229]
My nightmare came true , i loged out of my acount and the recovery phrace opens 0 balance acount 

I made Myetherwallet and printed the paper copy wrote the password and everything then i installed metta mask and i thought everything is awsome after 2 months of using it , i decided to logout,  in reality i somehow made a second acount and i was sending money there , the utc and the 12 phrace opens the 0 balance acount.

0xfc2e5da1e7032f94e8ef4e7e217fde48016f0f54   
is this over , should i call it quits? the only thing i know is my password :(
i do have another 12 phrace saved  during all of this, but its invalid :( i wrote it and i copy/pasted

**Comment by PenguinKnight1** [comment]
UTC, and 12 phrace only opens the 0 balance acount. 0x6c08c66A0DF14DF0fDe87B354f7d48D4E021E6d0
Is there anything i can do

**Comment by PenguinKnight1** [comment]
I didnt know that once you install meta mask , it comes with a wallet alredy. for 2 months i was thinking i was using my paper wallet but in reality i was using the meta mask generated wallet , untill i loged out i noticed recovery only recovers 0 balance wallet (paper wallet)
I did copy the 12 phrace  that metamask provided , but it says invalid phrace
i check the spelling, specing ,and checked all the words from https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
I know my password and i have all the transactions i can confirm.

**Comment by lazaridiscom** [comment]
This is possibly related to #3127

**Comment by PenguinKnight1** [comment]
Solved the problem. 
A month ago i used my parents computer to log on to Meta Mask , i gaved them a call and told them if they can enter the password and BOOM they got in :) ( no seed needed )
I asked them to recover the seed and it was completely different. it said You copleteted the wallet .... I always had the wallet.
Any way i am super happy and i can go to sleep.
