### ISSUE TITLE
More Tests!

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#3233]
Here are the goals that we'd like hit for the next two weeks with testing and notes from @tmashuang and I's talk:

- metamask-controller: 85-75 (curent: 42)
- network:
  bare min is to get the test properly stubbed
- blacklist:
  bare min is to get the test properly stubbed

**Comment by bdresser** [comment]
@tmashuang @frankiebee closing this - seems like we're tracking in more specific issues
