### ISSUE TITLE
Incorrect insufficient funds error from geth

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3237]
It appears we can sometimes get an insufficient funds error from geth.

The problem is described in this issue:
https://github.com/ethereum/go-ethereum/issues/2173

State logs with reproduction params are in HelpScout ticket # 6047.

Params include:
```
              "value": "0x4ed369e7f438000",
              "gasPrice": "0xa7a358200",
              "gas": "0x7b58"
```

From account with balance `0x3b9d4d605c2da80` wei.

Seems that whatever we're sending over the RPC is being rounded incorrectly.

**Comment by danfinlay** [comment]
I've deconstructed the original tx, and it doesn't seem we're overflowing on our side, this seems to be a geth-side bug. I'm going to suggest the user try connecting to a different client as a workaround.

**Comment by frankiebee** [comment]
@danfinlay can this be closed or is their some more plan of action for this issue?

**Comment by Gudahtt** [comment]
I'll close this for now, since there were insufficient details to investigate.
