### ISSUE TITLE
Doesn't respect privacy window in Firefox

### ISSUE THREAD

**Issue by abitrolly** [MetaMask/metamask-extension#3238]
*  Expected Behavior - opening new Private Window in Firefox should not login me into Metamask
  *  Actual Behavior - when I open new Private Window I am logged in and my details are inserted into page
  *  Browser Used - Firefox 58.0.1 // MetaMask 3.13.4
  *  Operating System Used - Fedora 27

![image](https://user-images.githubusercontent.com/8781107/36162120-9a9c32b4-10f6-11e8-8322-8e50889385d5.png)

**Comment by Zanibas** [comment]
Are extensions enabled by default in private windows?

**Comment by Gudahtt** [comment]
Extensions should be disabled by default in private windows. We also don't inject anything by default anymore since v7.0.0, when "privacy mode" was made default. So even in private windows, your personal details are no longer injected unless you explicitly consent by connecting to the site.
