### ISSUE TITLE
UI - token view sometimes fails

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3243]
Token list currently requests all your token balances at once, on switching to the token tab. The easy way to retry is to switch to "sent" and back to "tokens" again.

The long term solution will be to load the tokens individually, retry them individually, fail them individually.

**Comment by danfinlay** [comment]
We could also move token balance loading to the background process.

**Comment by bdresser** [comment]
relates to #3034

**Comment by leafcutterant** [comment]
This still happens to me. Requesting re-opening.

Logging out and in again solves this. Could this reloading be automated so the user doesn't have to log out in the first place?

**Comment by 0xdevalias** [comment]
I'm also seeing MetaMask stuck on "Loading Tokens..." at the moment (for a hardware based wallet if that matters), logging out and back in didn't appear to help the situation at all.

**Comment by linxux** [comment]
Same issue...
Any workaround for this issue?

**Comment by bigcook12345** [comment]
Nothing just yet 🤦‍♂️. I'm going through everything, just to try and have
something work..? Problem is, I'm sure it's something right in front of me
like always. But at least I'm trying everything possible to make it work...

**Comment by Djtons85** [comment]
ok so i had some issued, metamask cannot loading my token balance. only can see it via ethplorer. try everything to fixed it but not working.

Anyone can help?
