### ISSUE TITLE
Do not poll infura when no web3 sites and not unlocked

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3244]
Could spare some bandwidth.

**Comment by whymarrh** [comment]
@frankiebee @kumavis 👀 can we close this?

**Comment by frankiebee** [comment]
@whymarrh lets keep it open for now and i'll close it at the end of this week after a little confirmation that this is not an issue

**Comment by whymarrh** [comment]
This has been merged into `develop` and published in quite a few releases 😅
