### ISSUE TITLE
Update MetaMask.io support footer to re-direct to HappyFox

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/metamask-extension#3248]
Previous HappyFox access is disabled - the footer link at metamask.io still links to HappyFox. Can we please re-direct to http://metamask.helpscoutdocs.com/ and also provide a link for contact-us which opens to support@metamask.io

**Comment by danfinlay** [comment]
Four files need to be updated for the basic support link: https://github.com/MetaMask/landing/search?utf8=%E2%9C%93&q=happyfox&type=

**Comment by danfinlay** [comment]
Keeping open until @kumavis does a fresh deploy to the page.

**Comment by kumavis** [comment]
done
