### ISSUE TITLE
Can't connect to my account, it says Connecting to main Ethereum Network... and nothing happens

### ISSUE THREAD

**Issue by Santosh3298** [MetaMask/metamask-extension#3255]

**Comment by JohnAllen** [comment]
try refreshing and reload the page, selecting a different account then back to mainnet.

**Comment by shahjee81** [comment]
Hi dear my metamask account removed from chrome please tell me how it recover

**Comment by danfinlay** [comment]
On your first question:
Sometimes if you get an infinite "Connecting" spinner, you can fix this by switching the network in the top left menu to a different network and back again.

If your account was removed from Chrome, you can use your 12-word seed phrase to restore your account when first setting MetaMask up. If you already created a different vault, you can lock MetaMask (top right menu) and then click "Restore from seed phrase".

For usage questions in the future, check out [our knowledge base](https://metamask.helpscoutdocs.com/), or email our support at support@metamask.io for faster responses.
