### ISSUE TITLE
Hi there just transfered 0.1 ETC to metamask as a test but it doesnt show in metamask.

### ISSUE THREAD

**Issue by cryptogaz** [MetaMask/metamask-extension#3256]

**Comment by JohnAllen** [comment]
Are you sure you have the right account selected in MetaMask?  I didn't even know MetaMask supported ETC.

**Comment by tmashuang** [comment]
ETH and ETC have the same format of private keys and addresses. MetaMask does not support ETC. If can use MEW or MyCrypto with MetaMask and change the network to ETC.
