### ISSUE TITLE
NewUI - confirming final tx does not return to main account view

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3263]
Seems related to #3262.

While that one regards the app-initiated popup, this one is also reproducible within the extension "action view", by clicking the fox, and sending a tx. After clicking "confirm", a spinner is shown indefinitely.

A warning is visible in the UI:

```
bundle.js:121348 Warning: Failed prop type: Invalid prop `selected` of type `number` supplied to `AccountDropdowns`, expected `string`.
    in AccountDropdowns (created by Connect(AccountDropdowns))
    in Connect(AccountDropdowns) (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by SelectedApp)
    in SelectedApp (created by Connect(SelectedApp))
    in Connect(SelectedApp) (created by Root)
```

**Comment by danfinlay** [comment]
Seems this is a UI crash caused by [this line](https://github.com/MetaMask/metamask-extension/blob/uat/old-ui/app/app.js#L200), which is receiving a number for "context", because on `confTx`, the `context` refers to the current message/tx index, and on the account detail view, it refers to the current selected account.

This is basically caused by overloading this `currentView.context` key, we could either break apart what the two views rely on in the state, or do something hackier, like coersing this key to be a string on that line, since it should be a momentary transition.

**Comment by danfinlay** [comment]
Oh, also `props.selected` already keys to the current selected account here...

**Comment by danfinlay** [comment]
Formerly, processing the reducer with 0 pending txs or msgs would return a `currentView.name` of `accountDetail`, but it seems like it doesn't anymore.

**Comment by danfinlay** [comment]
I guess in some ways that is an abuse of the `reducer` pattern. Is it an antipattern to use a reducer to "clean up" or "correct" state? I figure if it's part of the "update_state" action, it's ok (new metamask/background state used to derive new app/UI state.

**Comment by danjm** [comment]
@danfinlay was this also an issue with your local build?
