### ISSUE TITLE
Tx status "approved" should appear pending in list

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3268]
Currently `approved` state looks like successfully mined, but this can be very deceptive. I'm currently seeing this on `master` where I'm experiencing a non-broadcasting tx bug, and it was very confusing b/c txs looked successfully transmitted, but were not transmitted at all.

**Comment by danjm** [comment]
@danfinlay Just so I can understand this issue better: was this just a design issue whereby the "approved but not confirmed" state just needs to look a bit more like a pending state? Or (if you remember) did it seem that the rendered state was incorrect and did not match the actual state?

**Comment by danfinlay** [comment]
No sorry, this is only a problem with old UI, and is specifically mostly a problem with that build bug I was having. Not worth fixing.
