### ISSUE TITLE
Api feature request: popup management

### ISSUE THREAD

**Issue by Jabher** [MetaMask/metamask-extension#3270]
Metamask is creating actions which require confirmation by user.
However, some of them (e.g. eth.personal.sign) are meaningless without page context (no callback to recieve data), and sometimes - as long as developer do not always know about already spawned popups - duplicate popups (for some contract call or transfer e.g.) can be spawned accidentially.

So, I'd like to request for following api improvements, either jsonrpc exrension like parity or additional page-level api:

- management of popup close policy: "do not close", "close with initiator page", "close with last page of domain" (here some condition should be probably passed - include subdomains, parent domains etc)
- access to list of pending actions (sign, call, blahblahblah) spawned by pages in this domain/this page in format of `Array<{uuid, jsonrpc_payload}>` or similar
- force re-open of modal window with uuid of pending action with sign request, as long as request can be simply ignored and closed and be kept under the icon, and after half an hour user is acting like "wat? What are this transactions for? I do not remember, what is happening"
- request cancellation (if call demand disappeared - e.g. we're waiting for some deposit to happen, and it comes not as used action but from old and low-fee just-happened transaction)

**Comment by JohnAllen** [comment]
I actually have had some related thoughts but simply about duplicate popups and how they always popup in the far top-left of the window (High Sierra 10.13.3  Chrome: 64.0.3282).  Would be nice to popup center of screen and not on top of one another.  

Would be willing to work on this if someone knows if popup positioning is possible (probably center issue is simpler)

**Comment by Jabher** [comment]
@JohnAllen arent "left" and "top" properties not working? https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/create

About popups, I'm personally stuck with simple problem - I have ethereum-based auth via personal_sign, and user can accidentially close tab, but popup with "sign this to authorize" is still there. It is confusing and makes thing more complicated. If possible, I would implement behavior like "if any tab from this domain is still here, keep this popup - I'll re-elect the master and track execution result with it, otherwise close this popup".
Aaand I just understood that I also forgot about "subscribe to result from other tab" feature.

**Comment by Robbiekruszynski** [comment]
Hey @Jabher 
I know it has been some time but please know this ticket was never lost. Hoping you've been enjoying the improvements the team has made as of late. We have migrated our conversations for support / feature requests to [ZenDesk](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas). Feel free to make a ticket / share your thoughts there! 

Going to close this ticket.
