### ISSUE TITLE
Metamask does not show Account 2 (Chrome crashed maybe)

### ISSUE THREAD

**Issue by aalamrangi** [MetaMask/metamask-extension#3273]
Created a new account in Metamask extension (default name Account 2) a couple of days ago. Received and sent coins from this account successfully. Renamed Account 1 and 2 with friendly names. Opened Chrome the next day. There was a crash message and an option to reopen the tabs. Logged into Metamask normally with the password. Only Account 1 is visible. Account 2 is gone. The friendly name is also reverted back to the default Account 1.

I have exported the Account 1 private key and the state logs now. Is there any way to get the Account 2 back in Metamask (or any other wallet)?

I have the 12-word Metamask seed and the blockchain address for Account 2 that can be verified on Etherscan.io. 

To avoid further complications, I did NOT try to create a new account, or restore from the 12-word seed, or remove/reinstall the extension.

Not sure if this is related but before I noticed the Metamask issue, I'd been trying to install Mist Ethereum desktop wallet and the sync was running for over a day. So I stopped it and restarted fresh sync via CLI after doing **geth --removedb** and then **geth --fast** option, which is still running.

Windows 10
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by Zanibas** [comment]
Did you try to "Create Account" again?

**Comment by aalamrangi** [comment]
Thanks! I tried Create Account and the Account 2 is back! Etherscan.io transaction matches. But funny that it does not show the transaction history in Metamask.

**Comment by Zanibas** [comment]
We're hoping to have these transaction histories "persist" across sessions. Another feature on a long list of "things we need to do"!
