### ISSUE TITLE
Meta Mask is not connecting to the main eth network

### ISSUE THREAD

**Issue by LK1097** [MetaMask/metamask-extension#3274]
![image](https://user-images.githubusercontent.com/36542745/36316074-4b088ae6-1307-11e8-9963-56c1d3848622.png)
my meta mask has been like this for a day or so now. What can i do to fix it?

**Comment by tmashuang** [comment]
Some of the quick solutions would be to switch networks in the top-left network indicator and switch back to Mainnet. Other issues could that some networks could block the network calls for MetaMask to work properly.

**Comment by tmashuang** [comment]
Closing issue as duplicate for #2043, #2529, and potentially #3151.
