### ISSUE TITLE
walltet menu (three dots) is hidden upder scrollbar

### ISSUE THREAD

**Issue by Obie-Wan** [MetaMask/metamask-extension#3280]
It's difficult to copy wallet address by clicking Copy in the wallet menu, because scrollbar is drawn on top of menu. Sometimes it's impossible to open it at all.

**Comment by tmashuang** [comment]
Could this be caused by a different OS text-size other than 100%. Possibly related to #2767.

**Comment by inter23** [comment]
Hi, facing the same issue, changing of chrome text size doesn't help. Win7 Chrome

**Comment by frankiebee** [comment]
@Obie-Wan @inter23 can you provide your browser types that you are using and what would be most useful is a screen shot.

**Comment by Obie-Wan** [comment]
![mm](https://user-images.githubusercontent.com/669667/36699315-4fe01f1c-1b5d-11e8-933b-34e284c4b8b2.jpg)

OS: windows 7 64 
browser: chrome 64.0 
resolution: 1600x1200 
display: dell u2414M

**Comment by tmashuang** [comment]
> chrome text size doesn't help
It is not chrome's text size that needs to be changed, but the actual windows display text size. 

https://productforums.google.com/forum/#!topic/chrome/tyzywUJfkQI

Found a workaround for a monitor with a different text size other than 100%.
> Yes! Disabling chrome://flags/#enable-use-zoom-for-dsf "Use Blink's zoom for device scale factor" fixes the mouse offset issue for me on latest Chrome (63.0.3239.108).

**Comment by Obie-Wan** [comment]
> Found a workaround for a monitor with a different text size other than 100%.
Unfortunately it did not help. My chrome font size is BIG, temporarily set it to medium - looks fine.

**Comment by tmashuang** [comment]
Oh I see now, seems chrome extensions honor the browser settings for text size. We will investigate and apply a fix soon.

**Comment by bdresser** [comment]
This issue is resolved on the new UI
