### ISSUE TITLE
Stuck on infinite Estimating Transaction Cost loop

### ISSUE THREAD

**Issue by Kail68** [MetaMask/metamask-extension#3284]
As the title says, tried to purchase 2 smart contracts. Stuck on the loop and can't continue.
Galaxy s7
Android 7.0
Latest version of Firefox and Metamask plugin

Worked the previous 25 transactions

**Comment by Zanibas** [comment]
Sorry, how are you able to do these transactions on your phone? Are you using MetaMask or another app?

**Comment by Kail68** [comment]
Hey, using my s7. Have Firefox with metamask extension on it.

Working fine now, there is a tiny X that you can press to manually enter
gas.
