### ISSUE TITLE
How to track clicking of "Submit" button in MetaMask?

### ISSUE THREAD

**Issue by elie222** [MetaMask/metamask-extension#3290]
We run code like this to do the transaction:
```
const { receipt } = await instance.bid(id, { from: accounts[0], value: amount })
```
It takes a while till the `await` returns and for me to know that the Submit button has been clicked by the user since I don't control the MetaMask plugin. Is there a way to know as soon as the user sticks is transaction through by using a callback?

This would help with tracking events too as a user will often refresh a page after submitting a transaction before the promise completes.

**Comment by tmashuang** [comment]
This issue seems to be a implementation decision for a contract. I believe it would be better to gain insight through https://ethereum.stackexchange.com/

**Comment by elie222** [comment]
How is this the contracts decision?

I mean from the time the user clicks submit to the time there's a callback
from metamask / web3, there's a significant break. This doesn't happen
instantaneously. Is the wait time the amount of time it takes to send the
tx, because it feels unnecessarily long in that case.

**Comment by tmashuang** [comment]
Seems like this is possible related? https://ethereum.stackexchange.com/questions/36779/get-transaction-hash-and-mined-receipt

**Comment by elie222** [comment]
That looks like it may solve my problem! Thanks

**Comment by UchihaKutter** [comment]
@elie222 can you tell me how to solve it

**Comment by elie222** [comment]
Yes, you can use `sendTransaction`.

Something like this for an immediate response:
const transactionHash = instance[methodName].sendTransaction(...args,
options)

You can then listen for when the result comes in with using the
`transactionHash`.
