### ISSUE TITLE
NewUI- Creating new send should not trigger popup

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3292]
When in full screen mode, initiating a send both:
- Shows confirmation in screen
- Triggers confirmation popup

If the user is in the UI (either full tab or extension action view), a popup should not appear.

<img width="1229" alt="screen shot 2018-02-18 at 12 31 01 pm" src="https://user-images.githubusercontent.com/542863/36356495-a9e1b140-14a7-11e8-8990-9624451584d4.png">

**Comment by danjm** [comment]
I created a PR to resolve this: https://github.com/MetaMask/metamask-extension/pull/3306
