### ISSUE TITLE
Error when try to deposit Token

### ISSUE THREAD

**Issue by kevincruelz** [MetaMask/metamask-extension#3293]
Everytime i want to try to deposit my Token to idex.market it's always shows this error but when i try send my ETH it works , i already use Chrome and Firefox and the results are same , can anyone help me with this?
Thanks in advance

Screenshot : 
https://imgur.com/LZRjgSM
https://imgur.com/usY1JqV

**Comment by frankiebee** [comment]
hey @kevincruelz the application is trying to send a transaction with to high of a nonce so we dont allow that. This sounds more like an issue with index.market

**Comment by frankiebee** [comment]
im going to close this due to lack of response and being a user question
