### ISSUE TITLE
Local node geth 1.8.1

### ISSUE THREAD

**Issue by aribo** [MetaMask/metamask-extension#3294]
I'm having an issue with executing transactions through metamask connected with my geth 1.8.1 local node.

When I send a transactions it indicates "failed" and as reason: undefined is not a promise. Then after I connect again to node Main Network and it can't send transactions anymore either.

![screen shot 2018-02-19 at 16 21 35](https://user-images.githubusercontent.com/92448/36384860-07a2c9ce-1591-11e8-8459-b3b7b594e812.png)

**Comment by Zanibas** [comment]
Sorry, could you submit this as a ticket to our helpdesk with reproduction steps and your state logs, and mention my username on it? @Zanibas. We'll be able to help you more there with more privacy.
