### ISSUE TITLE
metamask is sittitng trying to load so i can sign in but wont get there

### ISSUE THREAD

**Issue by JOINGROWTH** [MetaMask/metamask-extension#3295]

**Comment by joingrowth** [comment]
is says trying to connect to main eth network but isn't connecting

**Comment by danfinlay** [comment]
We're working on fixing this when it happens, but glad you found the workaround.

**Comment by JOINGROWTH** [comment]
Dan nmy computer crashed and had to reset everything I have my jgc tokens
in metamask so i reinstalled meta mask and put send word frase in but its
not showing my tokens at all the person that sent them to me is my business
partner he is here with me any way opf helping
