### ISSUE TITLE
Interrupted MetaMask "Send" Session Replaces Recipient Address with the Empty String

### ISSUE THREAD

**Issue by myhndl** [MetaMask/metamask-extension#3300]
Browser: 
Chrome + MetaMask extension

OS:
Linux

Expected behavior:
1. user clicks MetaMask icon
1. user clicks Send
1. user populates `Recipient Address`, `Amount`, and / or `Transaction Data`
1. user clicks away from MetaMask, e.g. onto the webpage they're interacting with, dismissing the popup
1. user clicks MetaMask icon again
1. user clicks Send
1. previously completed `Recipient Address`, `Amount` and / or `Transaction Data` fields retain values previously populated

Actual Behavior:
Same as above except the `Recipient Address` field is *not* retained. Previously populated `Recipient Address` is replaced with the empty string.

Impact:
This wouldn't be a big deal if it weren't for the fact that MetaMask interprets an empty string in the `Recipient Address` field as the `0x0` Ethereum address. It is almost certainly never the user's intent to send ETH to the `0x0` address in such a case, causing the user to irrecoverable lose funds.

Recommendations:
1. Do not allow the user to proceed (click Next) until a `Recipient Address` is populated. 
1. Do not equate the empty string with the `0x0` address; require the user to enter `0x0` if that is their intent.
1. Retain the `Recipient Address` when a Send session is interrupted. The other fields (`Amount` and `Transaction Data`) are already retained; `Recipient Address` should be retained in the same manner.

**Comment by tmashuang** [comment]
Closing duplicate issue #2509. The issue has a work around, and a incoming solution.
