### ISSUE TITLE
the metamask in private network can not send the coin

### ISSUE THREAD

**Issue by MOKAKI** [MetaMask/metamask-extension#3315]
hi pls help me..

i wish send the coin on  private network in metamask(chrome)
i don't know how can do this
i am beginner

i already use "geth" build my private network in my windows 7

start up code is:

geth --identity "DAPP0222" --rpc --rpccorsdomain="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html" --datadir data  --port "30303" --rpcapi "db,eth,net,web3" --networkid 9394 console

the metamask(chrome) current rpc:
http://localhost:8545

------------------------------------

i tryed 
get the newAccount in the geth  ,and Import it in the metamask 
or
get the newAccount in the metamask  ,and start miner in the geth 

now if start miner , i can see the A acc have income the eth coin
B account send eth to this A acc also is work
use the Ethereum-Wallet  , A acc can send the eth coin B account

but if use the metamask(chrome) is can't send to anyway , allway is failed

the error code pls saw the pic

because i need try smart contract in browser-solidity , but now metamask(chrome) can't send ,i can't start my work

pls help me... i very need your help!! thank you so much!!

![0224](https://user-images.githubusercontent.com/32431004/36625891-6307a354-1963-11e8-810b-22b7750db922.jpg)

**Comment by bdresser** [comment]
@MOKAKI this question may be better suited for Stack Exchange or a geth community forum.
