### ISSUE TITLE
Uncaught Error: Provided address "" is invalid,

### ISSUE THREAD

**Issue by woniesong92** [MetaMask/metamask-extension#3318]
All of sudden, I am getting the error `Uncaught Error: Provided address "MY_ADDRESS" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.`

Using the latest metamask with a valid account address.

**Comment by tmashuang** [comment]
Is this error message coming from a Dapp? Any more context to this error message would be greatly appreciated.
