### ISSUE TITLE
Changing metamask rpc provider programmatically

### ISSUE THREAD

**Issue by bluebirdly** [MetaMask/metamask-extension#3319]
Is there a way to use MetaMask's currentProvider, and simply point it to a third party rpc-json provider programmatically (i.e. not through the extension gui)? Or do I have to go down the provider-engine -> RpcSubprovider route?

**Comment by frankiebee** [comment]
currently their is no way for a application to set the provider. So for now you'd have to check the network id and then prompt the user to switch networks

**Comment by bluebirdly** [comment]
So there's no way to check the json uri endpoint metamask is using correct?
