### ISSUE TITLE
[SEVERE] Incoming Transactions are not Displayed.

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3320]
## Issue

This morning I told someone that I did not received his payment. Then suddenly it hit me

 * SENT | TOKENS

I realized that MM does not show incoming transactions, which is **totally confusing** to me.

## Expected

As its natural to any account, MM should show me the 3 relevant things of my Eth Accounts:

* Balance
* Received
* Sent

**Comment by tmashuang** [comment]
Duplicate issue. Closing in favor of #133.
