### ISSUE TITLE
Implement new designs for 'Add Token' screen in NewUI

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#3326]
@cjeria has some very nice new designs for the 'Add Token' screen. These need to be implemented.

Should resolve #2495

**Comment by cjeria** [comment]
![image](https://user-images.githubusercontent.com/597770/36695388-080fc618-1af6-11e8-86ee-67f64f5bee3e.png)

**Comment by cjeria** [comment]
@danjm See above

**Comment by cjeria** [comment]
These are not updated on invision yet, but will do today.

**Comment by danjm** [comment]
merged to master
