### ISSUE TITLE
UI - "Cancel" button on the "Buy Eth" screen not navigating home.

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3336]
https://sentry.io/metamask/metamask/issues/474888634/

```
TypeError: Cannot read property 'address' of undefined
  at onClick (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1844091)
  at Object.i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1389858)
  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1330812)
  at Object.executeDispatchesInOrder (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1331541)
  at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1326949)
...
(11 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
Set P1 because its a very common error to see in Sentry

**Comment by kumavis** [comment]
still getting this in `4.1.1`

**Comment by kumavis** [comment]
still getting this in `4.1.2`

**Comment by danjm** [comment]
I don't think this error is present in `4.1.2`.
- I am unable to reproduce it locally. The cancel button behaves as expected.
- It does not appear in this search (4.1.2 events only): https://sentry.io/metamask/metamask/issues/474888634/events/?query=release%3A%224.1.2%22
- Meanwhile, it appears many times in 4.1.1 and 4.1.0 only searches: https://sentry.io/metamask/metamask/issues/474888634/events/?query=release%3A%224.1.1%22 and https://sentry.io/metamask/metamask/issues/474888634/events/?query=release%3A%224.1.0%22
- https://sentry.io/metamask/metamask/releases/4.1.2/all-events/ currently shows 11 other issues with `TypeError` in the issue title (476385110, 476385036, 476385017, 476338910, 476326852, 476309443, 476274795, 476265370, 475160869, 475032746, 474925962), but none of these contain events that reference the `Cannot read property 'address' of undefined` error

**Comment by kumavis** [comment]
Confirmed Fixed my dude
