### ISSUE TITLE
UI (old and new) - unapproved tx in tx history shows "contract published"

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3338]
"contract published" sounds like its already confirmed, hasnt even been approved yet

appears like this in both UIs

**Comment by danjm** [comment]
@kumavis is this for all types of transactions? Or did you just see it for sending eth, or tokens, or attempting to publish a contract?

And I am guessing you saw this in the deployed version and on mainnet?

**Comment by danjm** [comment]
Ah, I think I found it. To confirm, this issue refers to the user seeing below after attempting to publish a contract but before confirming, correct?

<img width="389" alt="screen shot 2018-02-27 at 7 27 54 pm" src="https://user-images.githubusercontent.com/7499938/36760213-7c7c0184-1bf4-11e8-83a0-f53bec497d93.png">
----
<img width="441" alt="screen shot 2018-02-27 at 7 27 41 pm" src="https://user-images.githubusercontent.com/7499938/36760217-7ee53b5c-1bf4-11e8-98a4-42a42adb1a68.png">

**Comment by kumavis** [comment]
>  this issue refers to the user seeing below after attempting to publish a contract but before 
confirming, correct?

@danjm  Thats correct
