### ISSUE TITLE
Browser doesn't know when a transaction is replaced (retried)

### ISSUE THREAD

**Issue by davewc** [MetaMask/metamask-extension#3347]
There doesn't seem to be a way to know when a user retries with higher gas..?

The tx is replaced with a new tx. Is there any way to get notified about this? Or poll / query it..?

**Comment by olaf89** [comment]
I have the same issue, from the dapp point of view the transaction is "stuck", what is the best way to handle the once there were overwritten? 

Etherscan shows "Nonce: XXX (Also found 1 other dropped Txn #1 with the same `from` account nonce)"

So maybe looking for tx with same nonce would be one of the solutions?

**Comment by prographo** [comment]
see also https://github.com/MetaMask/metamask-extension/issues/7227

**Comment by HM999** [comment]
Need a way to know a) the "retired" transaction and b) the new transaction.

**Comment by gorgos** [comment]
See also the related Web3 issue: https://github.com/ethereum/web3.js/issues/3585

**Comment by GregTheGreek** [comment]
I've created [EIP-2831](https://github.com/ethereum/EIPs/pull/2831/) in attempt to address this (still making edits)

**Comment by Gudahtt** [comment]
We're going to try using EIP-2831 for this, which is being tracked in #9174. Please follow that discussion for further updates.
