### ISSUE TITLE
Transaction Failed: TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3349]
https://sentry.io/metamask/metamask/issues/475375150/

```
Transaction Failed: TypeError: Cannot read property 'toString' of undefined
```

**Comment by jennypollack** [comment]
updated sentry link: https://sentry.io/organizations/metamask/issues/1066032710/

**Comment by Gudahtt** [comment]
Those links no longer work. I'll open a separate issue for this if I see it in Sentry again.
