### ISSUE TITLE
Add "submit support" page within app

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3351]
- Item in menu "Help"
- Should open full tab
- Should submit to our support system via API
- Should have default-clicked "Include logs to help debug" feature, which includes state logs.
- Include `?` next to that checkbox, that explains that no account secrets are included, but accounts and transactions are.

**Comment by brad-decker** [comment]
We now have a zendesk page for support requests and it is linked to from the app in much the way described here.
