### ISSUE TITLE
Metamask no longer working with iDex - the exchange will not connect with the wallet and says that there is no plugin extension.

### ISSUE THREAD

**Issue by kiwisanchez** [MetaMask/metamask-extension#3357]

**Comment by tmashuang** [comment]
Have you contacted IDEX with their issue? Will leave this open for others to chime in on the issue with IDEX and MetaMask.

**Comment by kiwisanchez** [comment]
Hi Thomas - yes have raised it with them, will see what they come back
with.  See if other people chime in with other probs.

Thanks

**Comment by tmashuang** [comment]
Related reddit post on Auroradao by one of its moderators: 
https://www.reddit.com/r/auroradao/comments/80t5ok/idex_metamask_announcement/

**Comment by kiwisanchez** [comment]
Legend, thanks for the info.

**Comment by ThreePhper** [comment]
Dose idex detect MetakMask by web3.currentProvider.constructor.name.
I found it has been changed from "MetamaskInpageProvider" to "f" today.

**Comment by jeff70** [comment]
Yep mine don't connect to it either.

**Comment by webcaetano** [comment]
Bancor also start experiencing multiple tx Failed. On this new major version

Related:
https://github.com/bancorprotocol/contracts/issues/195

**Comment by Gektorian** [comment]
not working on my end as well

**Comment by relpmis** [comment]
not working for me, confirm

**Comment by kumavis** [comment]
devs: please use `web3.currentProvider.isMetaMask`

**Comment by danfinlay** [comment]
With a little more detail:

Caused by #3372. Sites here broke because they used an undocumented method of identifying MetaMask, which we broke because we didn't know anyone was doing it:
```
window.web3.currentProvider.constructor.name === 'MetamaskInpageProvider'
```

The correct way to identify MetaMask from in a page is:
```
window.web3.currentProvider.isMetaMask
```

Closing as a duplicate of #3372

**Comment by keife** [comment]
IDEX sucks! Never working with MetaMask, worst exchange I have come across.
