### ISSUE TITLE
Update all Buttons Styles

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3362]
@alextsg I went through the entire app and compiled all screens that use old buttons styles. Let's update those to these styles

**Style guide w/specs**
![buttons styles](https://user-images.githubusercontent.com/597770/36819999-a583fe86-1ca0-11e8-8ba9-0c6b549cdc20.png)

**I created a codepen with active styles in CSS:**
https://codepen.io/cjeria/pen/RQvKqq?q=flat%20button&order=popularity&depth=everything&show_forks=false

**Screens where buttons need to be updated:**
![image](https://user-images.githubusercontent.com/597770/36818098-6cc26a0e-1c98-11e8-861b-eab73440cece.png)

![image](https://user-images.githubusercontent.com/597770/36816947-55a8e888-1c94-11e8-960f-ae1033e5749f.png)

![image](https://user-images.githubusercontent.com/597770/36818026-27e2ca46-1c98-11e8-844f-80cf90b16d1b.png)

**Comment by cjeria** [comment]
The signature screen buttons also need to be updated. This sign request pop up also needs a slight refresh to match the new UI styles. I'll create a new ticket for this task.

![image](https://user-images.githubusercontent.com/597770/37477485-0b8da1ce-2835-11e8-9754-2cc07ddfeea9.png)

**Comment by cjeria** [comment]
issue for updating sign popup styles #3578

**Comment by danfinlay** [comment]
@cjeria is the design complete on this? If so, could you update the `pipeline` to `Development Ready`?

**Comment by cjeria** [comment]
@danfinlay cool, yea this one's ready for dev. Should the pipeline `pending development`?

**Comment by danfinlay** [comment]
Yeah that's right. Sorry been playing with pipeline names.
