### ISSUE TITLE
Idex exchange no longer working

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3365]
Reported in tweet:
https://twitter.com/AndyrooMac/status/969017105457692672

Web3 seems to suddenly be not detected by this site for this user, need to try reproducing.

**Comment by ThreePhper** [comment]
Dose idex detect metamask by web3.currentProvider.constructor.name?
I found it has been changed from MetamaskInpageProvider to f today. 
Maybe that's the reason.

**Comment by danfinlay** [comment]
That's a dangerous sounding regression, probably worth fixing for its own reasons.

I've been unable to reproduce this bug, so I'm inclined to say that isn't the problem.

**Comment by lazaridiscom** [comment]
related: #3357

**Comment by danfinlay** [comment]
Caused by #3372. Sites here broke because they used an undocumented method of identifying MetaMask, which we broke because we didn't know anyone was doing it:
```
window.web3.currentProvider.constructor.name === 'MetamaskInpageProvider'
```

The correct way to identify MetaMask from in a page is:
```
window.web3.currentProvider.isMetaMask
```

Closing as a duplicate of #3372
