### ISSUE TITLE
New UI: Missing transaction data

### ISSUE THREAD

**Issue by lambi9891** [MetaMask/metamask-extension#3367]
Cannot add custom transaction data in the new UI

Is the feature missing or am I missing a step ?

**Comment by danfinlay** [comment]
This was a proposed change from some design research that suggested most people do not use that field. Clearly someone does! Can you describe what you use it for, so we can make sure you're accounted for?

We're currently thinking of adding this as an "advanced mode" feature that you can enable in settings, but is hidden from most users, who tend to be confused by it.

**Comment by lambi9891** [comment]
Agree with you.

IMO it still could be a good feature for the user to be able to double check the hex data as it could be an easy malicious attack angle.

**Comment by danfinlay** [comment]
I agree, the data should be reviewable on the final confirmation screen, and we have open issues for that already.

**Comment by bdresser** [comment]
relates to [Design#11](https://github.com/MetaMask/Design/issues/11)

**Comment by 1blockologist** [comment]
Is there anything I can help with here? In such a way I could submit a PR with this fixed

**Comment by bdresser** [comment]
@alextsg would a PR be helpful, or is this handled in the confirm screen refactor?

**Comment by alextsg** [comment]
@bdresser This will be handled with the confirm screen refactor/redesign and will be merged shortly. We're currently working on adding tests.

**Comment by bdresser** [comment]
cool - thanks for the offer @1blockologist but this will be released shortly! appreciate your patience.

**Comment by bdresser** [comment]
this is fixed in https://github.com/MetaMask/metamask-extension/pull/4691 and will be released shortly

**Comment by mikedeshazer** [comment]
August 2019... transaction data field still missing
