### ISSUE TITLE
Regression: InpageProvider constructor name is now "f"

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3372]
This is a regression for dapps that checked the constructor name to identify MetaMask.

This could come from build minification.

Identified in https://github.com/MetaMask/metamask-extension/issues/3365#issuecomment-369468520

**Comment by danfinlay** [comment]
Btw, I wasn't able to reproduce, so really this is just to check with @kumavis if he built the last version with some minification.

**Comment by danfinlay** [comment]
A new check that is working for others in the meanwhile:
`window.web3.currentProvider.constructor.name === 'MetamaskInpageProvider' || window.web3.currentProvider.isMetaMask`

**Comment by lazaridiscom** [comment]
@danfinlay , shouldn't there be a test-case added, which catches this regression in future?
