### ISSUE TITLE
Resending a transaction does not work anymore

### ISSUE THREAD

**Issue by Swift42** [MetaMask/metamask-extension#3374]
It seems that the update from yesterday broke my MetaMask:

I tried to send some transactions with a low gas. Normally MetaMask displays a text/link like "Taking too long? Resend the transaction here" after a few seconds. But this link isn't displayed anymore.
To be sure I waited some hours and restarted Chrome/Metamask several times, but the link does not show up.

This means: Currently my transactions are stuck because I cannot raise the gas with MetaMask.

**Comment by Swift42** [comment]
Oops, davesumter was 3 minutes faster :-)
So this is a duplicate of #3373 ...

**Comment by davesumter** [comment]
Swift42, I had to replace a TX using MEW as a workaround, but it's messy..

This is probably one of the most important features for me. I send hundreds of TX's a day and many get stuck. I pretty much can't use MM in chrome now..

**Comment by Swift42** [comment]
Yes, I thought about MEW, too, but as you said: it's messy.
So I likely wait for a MetaMask fix, which comes hopefully today or tomorrow.
I think this is severe bug (T0-bug / P1-asap).

**Comment by davesumter** [comment]
yeah, I run a dapp with a few hundred users and everyone has stuck tx's..

very very severe..

**Comment by fabiohild** [comment]
Same issue here, I'm willing to help if anyone provides the guidance on what has to be done, I have a client stuck at the moment and they would not be able to use the MEW method.

**Comment by lazaridiscom** [comment]
May I ask: wasn't there a beta-test phase?

**Comment by davesumter** [comment]
I'm kind of annoyed these extension's seem to have auto updated to a buggy version. I would prefer to stay on one version when it's working..

**Comment by fabiohild** [comment]
Chrome automatically updates all extensions, and curiously does not allow to force updates (we'll probably go through this once the issue is solved, we'll have to wait until chrome decides to update). I'm not sure about the other Browsers though, might be possible.

**Comment by davesumter** [comment]
I'm using firefox now
slow as hell, but at least I can resend

**Comment by Swift42** [comment]
I forced my chrome to update to MetaMask 4.1.3 (Addons -> Dev Mode -> Update all addons) and it is now working again. I was able to resend all stuck transactions with a higher fee. 
Thank you for the fix.

**Comment by danjm** [comment]
Thanks @Swift42 for reporting this. Much appreciated.

**Comment by mryellow** [comment]
This has regressed in some way? Not seeing retry buttons.

**Comment by mryellow** [comment]
A new transaction created with MEW for the purposes of beating this nonce and cancelling the transaction, thanks to new code instead gets a new valid nonce. This leaves the old transaction.

Interestingly the new transaction created by MEW has the retry button.

Could this be existing transactions are not having the correct "status"?
I'm not sure where this is being handled in the current layout and if "old-ui" is still used where status is checked for `submitted`...

If I'm seeing this right lot of people will be left with stuck transactions if the current build isn't rolled back or a hotfix created which puts their older transactions in a state where the retry button is shown.
