### ISSUE TITLE
Problem entering custom token data

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3378]
A user entered a token that failed to auto-fill, and was unable to edit the fields after that. Was this a crash? Need reproduction steps.

**Comment by lawrensp** [comment]
I'm unable to add a token. I enter the contract address, the Token Symbol field auto-fills the correct symbol and same for decimals, but when I click add, nothing happens. Tried refreshing and logging in and out. Contract address is 0xBE11eEb186e624b8f26A5045575a1340E4054552 and symbol is CCC. Please help

**Comment by danjm** [comment]
@lawrensp To confirm that we understand your issue, are you stuck here, and "Add Tokens" but just does nothing?

<img width="354" alt="screen shot 2018-03-01 at 10 32 52 pm" src="https://user-images.githubusercontent.com/7499938/36879933-a8d4f076-1da0-11e8-90e5-d3f7c5743c64.png">

(or, if you are using the popup view):

<img width="354" alt="screen shot 2018-03-01 at 10 32 52 pm" src="https://user-images.githubusercontent.com/7499938/36880050-496ee492-1da1-11e8-8335-79ee2a3c35cf.png">

**Comment by danjm** [comment]
@danfinlay I believe the bug you have described is distinct from the bug reported above by @lawrensp. As I explained to @jrmoreau in slack where he reported another user issue that seems to match this:

> When a user enters a custom token address, we query the blockchain to get other required info about that token ("Token Symbol" and "Decimals of Precision" on the Add Token page).

> For some reason, our code does not allow users to enter the symbol and decimals information themselves. So if the above mentioned query turns up empty, there is nothing the user can do.

I've bumped up the priority of this ticket and am working on it now.

I suspect, but cannot confirm, that the problem experienced by @lawrensp will be fixed when #3390 is resolved.

**Comment by lawrensp** [comment]
@danjm This is as far as I get. Once I click "Add," the refresh icon appears for a split second, and then nothing happens. 

![screen shot 2018-03-02 at 11 11 07 am](https://user-images.githubusercontent.com/36972488/36908971-d041fe3c-1e0a-11e8-801a-48c110bcac98.png)
