### ISSUE TITLE
[NewUI] SignTypedData horizontal text overflow

### ISSUE THREAD

**Issue by DeltaBalances** [MetaMask/metamask-extension#3379]
On the New UI, the data displayed for signTypedData does not properly overflow horizontally. 
The old UI shows scrollbars on long strings (a contract address), the new UI starts to overlap itself as it does not overflow.

![metamask-signtypeddata](https://user-images.githubusercontent.com/30391324/36861586-8fff3aa0-1d84-11e8-911d-5d31ba3bc49c.png)

The short messages available at https://danfinlay.github.io/js-eth-personal-sign-examples/ work and display as expected.

For reference, this is Metamask installed on Chrome 64.0.3282.186 on Windows 10, 1080p display resolution.

**Comment by danjm** [comment]
Thank-you for reporting this issue.

**Comment by danjm** [comment]
fixed on master
