### ISSUE TITLE
Rename "Seed Phrase" to "Account Phrase" or "Vault Phrase"

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3380]
Finally!

It could be that #3127 is caused by confusion.

I just understood this https://github.com/MetaMask/metamask-extension/issues/3331#issuecomment-369321618, and was writing a reply, when it hit me!

Finally I have overcome my confusion.

The reason I did not understood all this "Seed Phrase" stuff is something simple and not very uncommon:

miss-leading naming.

See here:

* With the Seed Phrase, you can Recreate your Account

this means?

* The Seed Phrase **IS** your Account

And if its so, then why not directly say:

# Account Phrase

# => Account Seed

2018-03-19

**Comment by mryellow** [comment]
>  why not directly say:

Just passing by... It's "Seed" all across the cryptocurreny space. Changing this to "account" would make metamask the odd one out and cause confusion.

Perhaps "Mnemonic phrase" is better but "seed" is very common.

https://en.bitcoin.it/wiki/Deterministic_wallet  
https://en.bitcoin.it/wiki/Mnemonic_phrase

**Comment by lazaridiscom** [comment]
Mr Yellow, thanks for the notes.

# Priorities

* A) Comply to CryptoCurrency Domain Terminology
* B) Security of Funds

I assume that 100% of people will agree here:

=> the "Security of Funds" has top-priority, above all.

# Security of Funds

## Confused Users - A Major Security Hazard

New users of MetaMask do not always have the full Crypto Knowledge. It is important to not confuse them, because

=> **confused users are a major security hazard**.

MetaMask **must** do **everything** to avoid confused users. 

Knowledge is a dangerous thing. "Seed Phrase" introduces a mental indirection. "Account Phrase" has zero mental indirections.

Personally, I'm 100% sure that this starts by concise naming, which does not confuse **newcomers**.

## Further Confusion

Looking at the code that flied in within  #3409, I start to doubt my abilities: did I still not understand all this? Am I so incapable, or is the documentation missleading.

Question:

* Within the crypto-currency domain in general, **one** seed phrase, restores how many accounts (key pairs) ?

* Within MetaMask, **one** seed phrase restores how many accounts (key pairs, ..., ??? ) ?

**Comment by lazaridiscom** [comment]
@danfinlay 

"Seed Phrase" is used within discussions here in issues, but the MM code refers to "Seed Words".

The terminology is already misleading, but at least there should be a unified use of either "Phrase" or "Words"?

MetaMask Code says "Words" (partially now "Phrase", see SeedPhraseVerifier).

"Phrase" is essentially invalid, as the Seed is just "words" in a random (non grammatically correct) order.

**Comment by lazaridiscom** [comment]
closing in favor of #3720
