### ISSUE TITLE
(New UI) gas fee calculator prevents transfer on private network

### ISSUE THREAD

**Issue by kangarang** [MetaMask/metamask-extension#3391]
i'm so happy with the new UI so far. and i especially appreciate the separate tab feature. thank you.

Expected Behavior: i would like to send ether and tokens from MM acct 1 -> MM acct 2 over localhost

Actual Behavior: when i'm working on a local dev network, I experience a minor bug where (i think) the gas fee calculator doesn't complete in returning a valid value, thus the next button remains inactive.

happens for both tokens and ether

<img width="357" alt="eth" src="https://user-images.githubusercontent.com/18040654/36881456-3605d514-1d9c-11e8-8f62-b01339ee4713.png">

<img width="350" alt="tok" src="https://user-images.githubusercontent.com/18040654/36881457-3614b368-1d9c-11e8-9874-a937ee0ebf60.png">

working fine for rinkeby though

<img width="345" alt="rink" src="https://user-images.githubusercontent.com/18040654/36881598-f07e1082-1d9c-11e8-956d-e9ee4d793af6.png">

Browser: Chrome v64.0.3282.186
OS: 2016 Macbook Pro

**Comment by danjm** [comment]
Thank-you for reporting this issue. It will be addressed soon.
