### ISSUE TITLE
NewUI Proposal: Display Network on Confirm Transaction Screen.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#3397]
@adam.yala on slack: 
> In the new UI, could we still display the current network in a popup transaction? When I click on the extension and look at my transaction it’s there. I ask because everytime I make a transaction I’m terrified I’m accidentally not on the correct network

Proposal: Add network on confirmation screen as we do in classic UI.

**Comment by cjeria** [comment]
Let's include the top bar that shows the network in the TX popup. 

Screenshot from invision:
![image](https://user-images.githubusercontent.com/597770/36921655-012fd47e-1e1a-11e8-9a15-83e3e65ab930.png)

Prototype
https://consensys.invisionapp.com/share/BEF3JZ126#/252407561_confirm_Tx

**Comment by cjeria** [comment]
@alextsg @danjm Actually, here's the latest design for the TX screen. I've reduced the size of the emoticons to reduce the overall height, which makes more vertical space for the top bar. Not sure why this was not implemented as spec'd?

![confirm tx copy](https://user-images.githubusercontent.com/597770/36921755-544eb472-1e1a-11e8-9b1d-442869705aa2.png)

**Comment by cjeria** [comment]
On second thought, I like how clean it looks without the top bar. We can mode the edit button to above the header label and add the network floated to the right. see mockup.

![confirm tx copy 2](https://user-images.githubusercontent.com/597770/36922073-8bcfb1c0-1e1b-11e8-8f76-374ea4d48521.png)

**Comment by johndangerstorey** [comment]
➕
