### ISSUE TITLE
Create automated Opera deploy script

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3401]

**Comment by tmashuang** [comment]
Closing this, as we don't have any concrete plans to get into the Opera store again. The build script has opera included as a browserPlatform. https://github.com/MetaMask/metamask-extension/blob/2ebf8756a4c1023e45e4bd98367f384836cb464a/development/build/index.js#L24

If this something we want in the future we can internally/async talk about it.
