### ISSUE TITLE
Create automated Github Releases deploy script

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3403]

**Comment by danjm** [comment]
Some pieces of this:

- automating the creation of a release PR
  - pull latest develop
  - checkout branch named after appropriate version number
  - update manifest
  - update changelong
  - create PR with correct name
- automate tagging process
- automate the merge to master PR OR automating the deploy of sourcemaps

**Comment by whymarrh** [comment]
I've spent some time playing around with various options here and my current thinking is that we could have a lot of this automation in a separate tool/CLI that we build for this. I'm thinking something like `metamask-devtool` where we build a bunch of commands that can automate some of our conventions for the extension repo.

### `metamask-devtool` with the [Node.js Open CLI Framework](https://oclif.io/)

```bash
$ metamask-devtool
```

```
MetaMask dev CLI, helping us build MetaMask

VERSION
  metamask-devtool/0.0.0 darwin-x64 node-v8.15.1

USAGE
  $ metamask-devtool [COMMAND]

COMMANDS
  help             display help for metamask-devtool
  propose-release  Tag a new version of MetaMask

```

With commands like `propose-release`, that creates a version branch with the updated manifest and changelog files:

- Pull the latest `develop`
- Checkout branch named after appropriate version number
- Update manifest
- Update changelog
- Push version branch to `origin`/`upstream`

```
Tag a new version of MetaMask

USAGE
  $ metamask-devtool propose-release TYPE

ARGUMENTS
  TYPE  (major|minor|patch) semver type

OPTIONS
  -h, --help  show CLI help

EXAMPLE
  $ metamask-devtool tag minor

```

With this kind of setup we could extend the tool to include issues like [#3389](https://github.com/MetaMask/metamask-extension/issues/3389) and [#3400](https://github.com/MetaMask/metamask-extension/issues/3400).

**Comment by daddyfatstaks** [comment]
Dont do it. They're not smart enough to do shit on their own so they try to
steal other peoples work and take credit for it. They should automate a
retarded thief button to deploy to ban them from the network completely
when caught.

**Comment by bdresser** [comment]
that sounds good @whymarrh. out of curiosity, have you looked in to Github Actions? I know other teams have found it useful for flows like this.

@danjm @danfinlay @kumavis any other thoughts on this?

**Comment by whymarrh** [comment]
I've somewhat come around on my previous idea—I think we can automate a lot of things via CI if we agree to a bit of convention. I've created #6653 with more details on that idea.
