### ISSUE TITLE
cache net_version call

### ISSUE THREAD

**Issue by hayeah** [MetaMask/metamask-extension#3419]
If a DApp needs to detect account switching or locking, it needs to poll accounts and net_version.

Right now account is cached, so the poll does not create an additional network call.

net_version isn't cached.

**Comment by whymarrh** [comment]
> If a DApp needs to detect account switching or locking, it needs to poll accounts and `net_version`

This is no longer the case, [`ethereum.on(eventName, callback)`][1] can be used with the `accountsChanged` and `networkChanged` events to avoid polling.

I respect that the "issue" here is to cache a particular network call but I believe that to be a very particular implementation detail unrelated to the problem statement.

  [1]:https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.on(eventname%2C-callback)
