### ISSUE TITLE
Document Vault Restoration Procedure

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3424]
from https://github.com/MetaMask/metamask-extension/pull/3409/files/92453f8715b78c0e6e2cdb9b2e1cfe48c0b013ad#r172029019

> The created accounts in the primary keyring are always the same. E.g. if you had 3 accounts and you restore your vault using your seed words, initially you will get one account and you can use the create account option to restore the other 2. They will be the same as you had before. The keyring creates the accounts in the same sequence.

Is this so?

Is there any documentation available about this?

**Comment by danfinlay** [comment]
Yes, this is accurate. We follow the [bip39 standard, an extension of bip44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki).

It doesn't look like we have this explicitly documented, so I'm renaming this issue to do that.

**Comment by danfinlay** [comment]
Is related to #654, which would automatically detect & restore accounts with balances.

**Comment by lazaridiscom** [comment]
Essentially duplicate of #654, superseded by mm-vault redesign (which naturally includes vault-restore-procedure).
