### ISSUE TITLE
i tried to login to metamask, it said my acct was expired and to contact the administrator

### ISSUE THREAD

**Issue by Robynpmartin** [MetaMask/metamask-extension#3428]
i signed up for metamask last month but even though my tablet said to look on the desk top there was no icon. it took me weeks of searching to find the file (json). i never received my 12 words, or the app, even though it said it was installed on my desktop. well, my son went out of town and I have taken over his computer. i managed to redownload the app. this morning, but I had to delete the copy I never received. then I logged into my wallet to hook up the two. i used my private key to login. I was told I had no wallet when I logged in with my ens. mew found my acct. ...or created a new one. i manually added my metamask acct. from a dropdown list and my code words. problem is, both places tell me that i have a zero balance. etherscan tells different. i dont know how to reconcile the three. i have my prive key, my json file, 12 words, ens, hash name, and label hash. the email metamask told me was expired is the same one that i've been getting updates from etherscan from the past couple weeks. they also sent me a password reset just this morning so I cant understand how that same email is expired for metamask! my ens is robynmartin6.eth   email robynmartin6@aol.com  i,m afraid i don't know the difference between a label hash and a name hash. you need more info justb let me know. thanks, robyn

**Comment by Zanibas** [comment]
I believe that emailing our support desk at support@metamask.io will give you better answers, but to quickly address this, it sounds like you have been the target of a scam/phishing incident. We do not ever say that "your MetaMask is expired" or that there is a process to reset your password through an email. 

If you are willing, we'd like more details on where these emails are coming from, as well as the contents of them, to help inform users of this scam.

**Comment by Robynpmartin** [comment]
after mew told me that my acct. had no balance, i went to etherscan (i had it bookmarked) to check my balance. i was unable to login, so i requested a new password. etherscan sent a password reset to the email on file (the same one i get updates from on two accts. i'm watching). with the new password i was able to login and my balance is still their, and i'm still receiving my updates. i accessed metamask through the link on mew; and i also had that correct link bookmarked, plus double checked the green address. when i logged into metamask with my original email and password, that is when i was told my acct was expired. i had a whole list of new accts., but i need the original one to access my funds. you know, there is a link on etherscan that says i can register a new acct. but i'm afraid that it will make all disappear! do you know the difference between a label hash and a name hash? i thought perhaps i could transfer my funds to my new accts(both mew and metamask) but i'm a pre-newbie and have no idea what i'm doing. i've followed all directions on mew, did all according to their explicit instructions, so this mess is confusing. oh, the only email that i got was the one i initiated on etherscan when i requested a password reset. i directly accessed the other sites. thanks so much for your help.

**Comment by kumavis** [comment]
> when i logged into metamask with my original email and password,

you never log in to metamask with an email, you only unlock your metamask with a password. maybe you're confused what service you're using?

> when i logged into metamask [...], that is when i was told my acct was expired.

we dont have an "expired" error message. can you take a screen shot of this error?

>  i'm a pre-newbie 

good luck/
you'll figure it out

**Comment by Robynpmartin** [comment]
i was unable to duplicate the transaction, therefore unable to take a screenshot. can i transfer all my eth to my new wallet without losing it/ and what wallet would that be/ mew or metemask???


?

**Comment by danfinlay** [comment]
Please open a conversation by emailing us at support@metamask.io

Closing it here because our GitHub is for solving specific issues in our software.
