### ISSUE TITLE
Data field is missing in Send screen

### ISSUE THREAD

**Issue by askucher** [MetaMask/metamask-extension#3430]
Where is data field?

![screen shot 2018-03-05 at 06 27 08](https://user-images.githubusercontent.com/4496793/36957636-60ac528a-203e-11e8-9e3f-0f52d066706e.png)

**Comment by Zanibas** [comment]
We do not currently support the data field in the new UI, since we anticipate most transactions requiring data are sent from the dapp rather than user-initiated. 

What are you attempting to do that requires use of the data field?

**Comment by Zanibas** [comment]
https://github.com/MetaMask/Design/issues/2

**Comment by cjeria** [comment]
@celinepark94 this is what it looks like in the old UI.
![image](https://user-images.githubusercontent.com/597770/38214126-80a8e5e4-3678-11e8-831f-c260e60cd172.png)

**Comment by cjeria** [comment]
This issue is related to https://github.com/MetaMask/Design/issues/2

**Comment by cjeria** [comment]
Adding latest designs for this feature. Since this is a `developer feature` maybe the data field should be disabled by default and switch to turn it on in settings page.

![image](https://user-images.githubusercontent.com/597770/40320032-16cfed06-5cdf-11e8-89e4-53b8ff1a2193.png)

**Comment by Parz-val** [comment]
> Since this is a developer feature maybe the data field should be disabled by default and switch to turn it on in settings page.

I really do not agree that this is a 'developer feature'.  For some use cases, normal users have to use this data field.

**Comment by abliss** [comment]
I still don't see the data field in version 7.7.9 . Am I missing it somewhere?

**Comment by whymarrh** [comment]
@abliss you can enable it in settings (pictured below). Please open up a new issue if you're having issues with it.

<img width="358" alt="" src="https://user-images.githubusercontent.com/1623628/85823159-4374fe80-b757-11ea-95a0-163596199f72.png">
