### ISSUE TITLE
Measure New UI Usage Rate

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3438]
Right now we have no sense of what % of MetaMask users are using the New UI, and this will be critical insight for rolling it out cleanly.

Maybe by using a different Infura endpoint for the New UI.

**Comment by danjm** [comment]
@danfinlay this was done by @alextsg in https://github.com/MetaMask/metamask-extension/pull/2794/files

**Comment by danfinlay** [comment]
Oh great!

**Comment by txtechs** [comment]
Using Okay I'm using the meta mask  March 3rd Edition March 3rd addition
for meta mask 4.1.3 chrome

**Comment by danfinlay** [comment]
Actually we moved off that endpoint @danjm to use the new RESTful endpoints that Infura gave us. We need them to provide some new RESTful endpoints to enable this again.

**Comment by danfinlay** [comment]
@txtechs I think you may have replied to the wrong message.

**Comment by kumavis** [comment]
blocked by infura adding endpoints

**Comment by whymarrh** [comment]
I think we can close this in preparation for 6.0 👀
