### ISSUE TITLE
Allow users to opt out of error reporting

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3441]
We added #3066 urgently to track down some bugs in production, but since this is crypto, we have some very privacy-centric users, and they would certainly like the option to opt-out of this error reporting.

Shouldn't need more design than a toggle switch in settings, maybe adding an opt-out opportunity during setup.

**Comment by holantonela** [comment]
I am proposing a custom setting under privacy for error reporting. 

This is going to be cross-platform, but we may have different providers for each app. @coreyjanssen may we have your review? 

https://www.figma.com/file/4gkmBwSE9qkecCS69pwsG3/Onboarding-Redesign?node-id=1214%3A53666&t=AITTRibW06CHlps7-4

**Comment by coreyjanssen** [comment]
Reviewed! @holantonela  looks good to me!

**Comment by holantonela** [comment]
This is done. Removing myself and `needs-design`.

**Comment by Gudahtt** [comment]
This was completed years ago, unsure of exact PR.

**Comment by Gudahtt** [comment]
Oh sorry, to clarify, we still didn't do this:

>We could potentially still add a toggle specifically for error reporting, so that users could be opted into one of metametrics or error reporting, but not the other.

But I don't think we need to keep this issue open to track that idea anymore. This is being considered in future designs of the privacy settings page during onboarding.
