### ISSUE TITLE
Empty balance after restore account and new password reset

### ISSUE THREAD

**Issue by Afectr** [MetaMask/metamask-extension#3443]
I have a Chrome browser that I use my Metamask App on.

There have been a few transactions lately on it, and suddenly I thought I might want to give it a new password.

So I  hit restore using my seedphrase, pop in a new password with a confirm password, and bam it created a new account. However this time all my balance is gone.

I must have missed something here, but is there anyway to restore my balance? I found a few related topics online but have not found anything specific to my case that can resolve the issue.

Cheers

**Comment by kumavis** [comment]
when did you first create your account?

**Comment by Afectr** [comment]
I will check this when I get home tonight to my home computer, Thanks

**Comment by Afectr** [comment]
36 days ago

**Comment by whymarrh** [comment]
@Afectr it's been a while but do you have any follow-up to this? Please re-open this issue if there's something we can fix.
