### ISSUE TITLE
Cannot change Gas Limit to a valid level trying to send ETC.  It toggles between 21000 and 0 but I am unable to submit

### ISSUE THREAD

**Issue by m4nc3-r4yd3r** [MetaMask/metamask-extension#3447]
I get this:
<img width="358" alt="screen shot 2018-03-06 at 12 31 26 am" src="https://user-images.githubusercontent.com/36798703/37017306-cf50caee-20d5-11e8-89c1-c016354acbb1.png">
I reset and then try to change the gas limit again and the submit button grays out.

**Comment by kumavis** [comment]
Looks like you're using [ClassicMask](https://github.com/EthereumCommonwealth/ClassicMask/issues/new).
We don't run that project and can't provide support for it. Please open an issue over there.

**Comment by m4nc3-r4yd3r** [comment]
Thanks for the response.  I noticed that after i posted but i could not
find the classic mask github.  Thanks for pointing me in the right
direction. I also use metamask but i was trying tgis out as well.  Thanks
again.
