### ISSUE TITLE
Using Azure blockchain metamask is not connect when geth --rpcapi ="eth,admin,personal" 

### ISSUE THREAD

**Issue by athlona64** [MetaMask/metamask-extension#3448]
Using Azure blockchain metamask is not connect when geth --rpcapi ="eth,admin,personal" 

when i remove --rpcapi="eth,admin,personal" it work ?

**Comment by kumavis** [comment]
hmmm weird -- any errors from the network tab?
https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome

**Comment by athlona64** [comment]
loop connecting it work when i remove --rpcapi on geth but not work on add --rpcapi

![s](https://user-images.githubusercontent.com/3031787/37067875-75e0d526-21de-11e8-9d38-9919fdaf7cb7.png)

**Comment by athlona64** [comment]
network show 

{"jsonrpc":"2.0","id":1622289956636666,"error":{"code":-32601,"message":"The method net_version does not exist/is not available"}}

**Comment by athlona64** [comment]
OK it work when i add --rpcapi="net"
