### ISSUE TITLE
Feature: Override chain id in network config

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3453]
Currently we use the rpc response of `net_version` for the EIP155 `chainId` value when signing all txs.

For some chains (e.g. ETC) `net_version` !== `chainId` which causes an invalid tx sig for the network.

The **correct** thing to do is introduce an rpc method for querying the chainId.

A workaround is to allow the user to override the chainId in the network settings.

This feature includes:
- UI to set the chainId
- wiring to use this chainId in the tx signing process

**Comment by kumavis** [comment]
If you want this feature, please let us know what network you are wanting to use

**Comment by p-s-dev** [comment]
The VictoriumProject uses "network": 93610431 and (eip155) "chainID": 4388577777

https://github.com/VictoriumProject/go-victorium/blob/master/core/config/mainnet.json

**Comment by lazaridiscom** [comment]
> A workaround is to allow the user to override the chainId in the network settings.

A possible implementation would be:

* Provide an Advanced(!) User functionality: Add Network

This would be e.g. a dialogue, where the user points to a network json.

e.g., user adds "https://github.com/VictoriumProject/go-victorium/blob/master/core/config/mainnet.json" into the field, MetaMask makes this network permanently available.

**Comment by Legacytrx** [comment]
Hi, any progress on this as we have the same problem with Atheios:
Network ID: 11235813
Chain ID: 1620
?

**Comment by hackmod** [comment]
See also PR #4932

**Comment by buhrmi** [comment]
Hi guys, any update on this? I want to use the "old" ethereum network with chainid 61 because i dont like the main net.

**Comment by buhrmi** [comment]
https://github.com/MetaMask/metamask-extension/pull/5134 seems to do exactly what I need... Can I do something to help getting it merged?

**Comment by Gudahtt** [comment]
We now require the `chain_id` to be specified on all custom networks, and we call `eth_chainId` to verify that it matches the network chain id. I think this satisfies the original problem here well enough.
