### ISSUE TITLE
Build Coinbase widget into our UI

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3454]
We currently link over to Coinbase for the ether buy widget, but their buy widget API also supports buying within our own UI.

We should build the buy widget right into the app, to minimize context switching for the user.

https://developers.coinbase.com/docs/buy-widget

**Comment by bdresser** [comment]
putting in the icebox for now, in favor of https://github.com/MetaMask/metamask-extension/issues/5260

**Comment by whymarrh** [comment]
Closing in favour of the same issue, linked above
