### ISSUE TITLE
Indicate the current selected account on the popup account view

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3463]
Reported via tweet:
https://twitter.com/mattgcondon/status/971133042654822400

Mostly about showing name/address in the main account view.

Requires some design consideration. Currently the account nickname is on the left-hand drawer, which is very visible in full-screen, but on the corner pop-up, it can leave a person unsure what account they're using without a click.

**Comment by cjeria** [comment]
Just got another user requesting this feature. I believe there's another ticket with mockups for a quick solution.

**Comment by cjeria** [comment]
![image](https://user-images.githubusercontent.com/597770/39145732-7cb42daa-46e9-11e8-8180-261c61e1ac0f.png)

**Comment by cjeria** [comment]
Here's the copy to clipboard design for this feature
![copy to clipboard](https://user-images.githubusercontent.com/597770/40089937-6f8dcd76-5863-11e8-8b6d-c9230efaa756.gif)
