### ISSUE TITLE
The Chrome Metamask cannot connect to networks

### ISSUE THREAD

**Issue by JoshuaAiYimi** [MetaMask/metamask-extension#3465]
Hi All,
Sorry, if this has been answered before.
My MetaMask could not connect to the main ethereum network. And all of the other networks (i.e. ropsten, kovan, rinkeby) couldn't be connected either. I wonder if anyone know something about this. 
I am using Chrome, Windows7
Thanks!

**Comment by tmashuang** [comment]
Some of the quick solutions would be to switch networks in the top-left network indicator and switch back to Mainnet. Other issues could that some networks could block the network calls for MetaMask to work properly.
#2043, #2529, and potentially #3151.

**Comment by kovrigin92** [comment]
I think it will be interesting to everyone who faced this problem before the problem occurred, I saw a message on my computer (the firewall tried to block one of the certificates), I did not hesitate to ban traffic, after that I again allowed access and everything worked! I apologize if anyone then already solved the problem the same way![
![default](https://user-images.githubusercontent.com/38068151/38298789-0f7b35b8-3801-11e8-99e2-f915f36be545.png)
![default](https://user-images.githubusercontent.com/38068151/38298870-3a59ebe4-3801-11e8-9af3-0880eb6a7692.png)

](url)

**Comment by whymarrh** [comment]
I'm closing this for now (it's been a while). Please open up a new issue if you're still having problems.
