### ISSUE TITLE
Corner fox looks a little cruddy

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3473]
I think the seams of the SVG are visible. We should maybe bake a bitmap for this, it looks a little dirty:

![screen shot 2018-03-07 at 1 43 23 pm](https://user-images.githubusercontent.com/542863/37119845-94545ef4-220d-11e8-808c-17b4f7c742e5.png)

**Comment by bdresser** [comment]
foxy nice and clean now :)
