### ISSUE TITLE
Put an ® for registered trademark where we use our name

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3474]
We keep having to shut down clones that re-use our branding & name, so we can help clarify this by adding a little ® next to where we use our name.
https://en.wikipedia.org/wiki/Registered_trademark_symbol

Apparently ™ is for non-registered trademarks, and ® is for registered trademarks like ours.

Task includes adding the ® in the most prominent places:

- [ ] Our extension
- [ ] Our landing page
- [ ] Other places???

### To external readers:

MetaMask is MIT open sourced, so people can clone the project and reuse it however they see fit, however, the MetaMask name and fox logo is a registered trademark, so before repackaging, distributing, or selling your fork of MetaMask, you have to rebrand the project.

We may modularize the code at some point to make it easier for people to rebrand, but it's not really a high priority for us so far, more focused on making it all work well, sorry!

**Comment by whymarrh** [comment]
Is this still a thing we should do?

**Comment by danfinlay** [comment]
I think the lawyers would say yes, but I don't see basically any other major site/service doing this, and it looks ugly, so I'm inclined to not? I guess worth a discussion. Not sure this would actually deter or increase enforcibility.

**Comment by whymarrh** [comment]
Yeah, I agree that it's not a thing that you often see (outside of the most corporate of environments). We could close this for now and reopen it should it come up again?

**Comment by danfinlay** [comment]
Sounds good to me.
