### ISSUE TITLE
Remove zero value tokens already! Was promised over 2 weeks ago

### ISSUE THREAD

**Issue by MudWar** [MetaMask/metamask-extension#3476]

**Comment by danjm** [comment]
@MudWar You can do this in the new-ui:

![hidezerotoken](https://user-images.githubusercontent.com/7499938/37166592-061f17d2-22da-11e8-9d56-83d4d18b01ab.gif)

Does that meet your requirements?

**Comment by MudWar** [comment]
OK, so can you implement that please

**Comment by lazaridiscom** [comment]
@MudWar , my understanding is that this is int he new UI, which you can activate by `menu -> "Try beta"`

**Comment by MudWar** [comment]
any risks of using the Beta?

**Comment by lazaridiscom** [comment]
You can switch back to the old UI if you feel its risky.

**Comment by MudWar** [comment]
Love it, the pop out to full screen-new window helps a lot too. Thanks

**Comment by lazaridiscom** [comment]
@danjm , @MudWar - Issue can be closed.
