### ISSUE TITLE
New Accounts not remaining

### ISSUE THREAD

**Issue by AngusMacbagpipe** [MetaMask/metamask-extension#3477]
I have created several new accounts as well as renamed 1 and they show up when created. After logging out of Metamask, the renamed account has reverted to the previous name and the new accounts are gone. I will create a new account again using the same name as before and that address is the same as the 1st time I created it, but again everrytime I log out, all those changes and new accounts are gone.

**Comment by musteecode** [comment]
me having the same issue. after logging in I created a second time a new account and the address is the same as the first time

**Comment by whymarrh** [comment]
Hey @AngusMacbagpipe and @musteecode, I'm going to close this because it's been a while but please do open up a new issue if you're still having issues with the latest version of MetaMask.
