### ISSUE TITLE
Fix Token Name Overflow

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3478]
User found a UI bug that doesn't allow him to hide token. The problem is that long token name push the 'hide token' button off the container view. https://secure.helpscout.net/conversation/537188567/10993/

Quick solution:
Ellipsis long token names

Long term solution:
Find a better place for token hiding button. Possibly within the token detail view. This may require the repositioning of other UI elements in the account/token detail view.

![token name overflow](https://user-images.githubusercontent.com/597770/37166588-4b953dd0-22b4-11e8-9cee-a70f08ad3dab.png)

**Comment by danjm** [comment]
@cjeria I guess we should implement the quick fix now, and then the long term solution whenever the designs are complete?

**Comment by cjeria** [comment]
@danjm Sure! It seems like a quick enough fix to squeeze into our current sprint.

**Comment by cjeria** [comment]
Will focus on long term solution for this ticket next.

**Comment by cjeria** [comment]
related to #3745

**Comment by cjeria** [comment]
@adamjm We received another support ticket about a related issue - token name not displaying. User's on Windows 10.

![image](https://user-images.githubusercontent.com/597770/38945180-ac8230ac-42ea-11e8-823b-b4de4c3ddd50.png)

**Comment by cjeria** [comment]
Another user running into the same issue:
![image](https://user-images.githubusercontent.com/597770/40083068-f0408592-5847-11e8-8c37-b010f300f24f.png)

I will look at how to address this problem with updated designs.
