### ISSUE TITLE
Nonce Reset not working

### ISSUE THREAD

**Issue by elie222** [MetaMask/metamask-extension#3479]
I'm developing with Truffle and attempting to do a nonce reset with MetaMask. When I do that, all the txs get wiped, but MetaMask still attempts to do the next tx at nonce 141, when it should be doing it with nonce 0.

**Comment by tmashuang** [comment]
I believe there you might need to reset the testrpc to get the correct nonce. This guide might be informative https://metamask.helpscoutdocs.com/article/36-resetting-an-account

**Comment by pierreneter** [comment]
> Page Not Found

**Comment by pierreneter** [comment]
> Page not found

<img width="646" alt="screen shot 2018-08-31 at 12 41 09 pm" src="https://user-images.githubusercontent.com/12815768/44894676-29b12e80-ad1b-11e8-9255-b389ff9139a8.png">

**Comment by bdresser** [comment]
proper article is [here](https://consensys.zendesk.com/hc/en-us/articles/360004177531-Resetting-an-Account-New-UI-), but it doesn't address the original question.

@elie222 are you still having this issue?

**Comment by elie222** [comment]
No. Closing now

**Comment by michaelosbornegit** [comment]
Now both links are broken. For anyone else who runs into this problem the button to reset your account is under Settings > Reset Account in the MetaMask extension.
