### ISSUE TITLE
Consider doing live user testing with lookback.io

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3483]
Obviously requires very explicit user opt-in, and very tight privacy guards in place, but:

We could potentially learn a lot by watching users use the product, and seeing how they get held up on features. Could be combined with A/B testing to really refine what the best UX for different features is.

**Comment by whymarrh** [comment]
I think we can close this for now—we have privacy-focused opt-in metrics and we do user testing.
