### ISSUE TITLE
web3.eth.accounts[0]  always comes  as undefined.

### ISSUE THREAD

**Issue by sandeep1116** [MetaMask/metamask-extension#3488]
my condition (typeof web3 !== 'undefined')  is true 
inside this condition  i write 
window.web3 = new Web3(web3.currentProvider);
but alway web3.eth.accounts[0]; is coming as 'undefined' I even called it via web3.eth.getAccounts() but in vain .
I checked my Metamask it is working fine as i tried to submit some contract via remix to ropstan and it worked without any problem.

Any `Help`  . Please find below as my code snippet.
`  window.addEventListener('load', () => {
    console.log('codepen load' + web3.eth.accounts);
    if (typeof web3 !== 'undefined') {
        // Use Mist/MetaMask's provider
       window.web3 = new Web3(web3.currentProvider);
       //window.web3 = new Web3(Eth.givenProvider || 'ws://some.local-or-remote.node:8545');
       
       // web3 = new Web3(Web3.givenProvider || 'ws://some.local-or-remote.node:8545');
        alert('Metamask used');
    }
     else {
        console.log('No web3? You should consider trying MetaMask!')
        // fallback - use your fallback strategy (local node / hosted node + in-dapp id mgmt / fail)
        window.web3 = new Web3(new Web3.providers.HttpProvider("https://ropsten.infura.io/token"));
    }
  
  setTimeout(function()
   {
        
        console.log('codepen timeout ' + web3.eth.accounts[0]);
        alert('after timeout');
    var res  = web3.eth.getAccounts()
     {                   
        console.log(res);
        web3.eth.defaultAccount = web3.eth.accounts[0];
        alert('Sandeep'); 
        console.log(web3.eth.accounts[0]);

    }

  }, 2000)
  alert( 'inside timeout');

});`

**Comment by sandeep1116** [comment]
Output of TestRPC is following

$ testRPC
EthereumJS TestRPC v6.0.3 (ganache-core: 2.0.2)

Available Accounts
==================
(0) 0xc4f162cc57071fb431c30e28b769df20f88365d2
(1) 0x531f070170d1e50cf6833f4d990b19318d56f03f
(2) 0xc0c620149d353cf90f5a8a30b4f8e3f506abb36a
(3) 0xb40f3acca408ab43ac02cff1ea94786cbf2fdd20
(4) 0x3b9dfd235c471e67117960e749a49324d1f8b74c
(5) 0x805e46df989606ac1fa674e9916e19b46c47e613
(6) 0x34e5025a1cca24800c9006f9140c240748cb80d8
(7) 0x364ea4cebfbf5c59c9a90f387f2df3c4074cb686
(8) 0x05b363d860520e278924924aba06ba4939745aab
(9) 0x619955e701e9744a73f8ca2387eafb25637b4271

Private Keys
==================
(0) f6950e2f6277a77e006f577568b2676e0aa0cfe848d361ad15f3e61a6145d179
(1) b8cc8307d626341cbc5c86ed2d5ce44619ba0230d9f51bd1caaa2fe6e32b844e
(2) 7f753d48e2ba015253e432f98356f8e6bd539da8bccfb9032ac48eae0d6d7ea6
(3) c1e4de7ca5e66b9a36d9010d001f5572e0e86157cafeefa3d3256580ac0c5358
(4) 5c6aa5f2b4149e30d3d4c675b271f77a88847fb193b99d32c256be6c2b9e075f
(5) 6c93231f053216aacf387bafda88e5cef2e9c8482ec88d5d2d1cc0e67287d8b1
(6) 1a63c2ea568eedaa74cf55518144ed0ce08de292c1307664ab0502b23e688666
(7) 45ec0175bf625871d228271b776273147cad3ed954e3787b98f56fef3824e05d
(8) 850e847941902fcd19aef32a86d8075d06635b4d3745a04ad809f59606d70997
(9) 885fbbc0d2a772ff435fb32314df2116ff11f167da875ccdd63daa8ebcc3aebd

HD Wallet
==================
Mnemonic:      globe donkey memory still trial ensure floor panel boring industry adjust narrow
Base HD Path:  m/44'/60'/0'/0/{account_index}

Listening on localhost:8545
net_version
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
net_version
net_version
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
net_version
eth_getBalance
net_version
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
net_version
net_version
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
n

**Comment by sandeep1116** [comment]
$ testRPC
EthereumJS TestRPC v6.0.3 (ganache-core: 2.0.2)
it show all Available Accounts and Private keys.

**Comment by frankiebee** [comment]
hey @sandeep1116 are you seeing any errors in the console from metamask also is your metamask unlocked?

if your metamask is unlocked could you check you background logs (instructions on how to do that [here](https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome)) and also check to see  if web3.currentProvider.publicConfigStore.getState() returns an object that has the selectedAddress set

**Comment by vrepsys** [comment]
You might be using web3js 1.0 which is not fully supported by MetaMask based on [this open issue](https://github.com/MetaMask/metamask-extension/issues/2350)

To make sure try 
`const web3 = new Web3(window.web3.currentProvider);
console.log(web3.eth.accounts)`

If you're using 1.0 it will print an object described in [1.0. documentation](http://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html)

As a hacky workaround (if you really want to use web3js 1.0. beta)  you could save the `defaultAccount` before discarding the `web3` provided by MetaMask.
`
const defaultAccount = web3.eth.defaultAccount
const web3 = new Web3(window.web3.currentProvider);
`

**Comment by leonprou** [comment]
I use Metamask with web3 1.0.0, to get the current account I call:
`web3.eth.getAccounts()`, this gives an array which has maximum one element, I mean it has the unlocked account or it is empty.

**Comment by zach-is-my-name** [comment]
Having the same problem, though 

> truffle(development)> web3.eth.defaultAccount === null


while

> truffle(development)> web3.eth.getAccounts()   === [''0xaBFF4,...]

**Comment by whymarrh** [comment]
@sandeep1116 it looks like there's some good comments here—I'm going to close this for now, if you run into more issues feel free to open up a new issue.

**Comment by parin13** [comment]
hey guys i am using web3 1.2.1. Its always says 

> Cannot read property 'currentProvider' of undefines

```
const Web3 =  require('web3')  
const window = require('window');
const web3 = new Web3(window.Web3.currentProvider);

```

the comments seem to be familiar with my approach that's why reopening the thread.

**Comment by Gudahtt** [comment]
Hey @parin13  - that might be because you've capitalized `web3`. The `web3` property on `window` is lower-cased.
