### ISSUE TITLE
PICTURE 1 :MY ETHESCAN SHOWS I HAVE MY 428 EOS... BUT IN PICTURE 2 THE METAMASK UI SAYS I HAVE 0(ZERO AS THE PICTURE SHOWS,AM GOOD OR IS THERE A NEED FOR CONCERN? PLEASE HELP

### ISSUE THREAD

**Issue by nanaadjapong** [MetaMask/metamask-extension#3490]
PICTURE 1
![screen shot 2018-03-09 at 12 23 35 am](https://user-images.githubusercontent.com/22830439/37193619-53bc1ff2-2330-11e8-9094-281390deccee.png)
PICTURE 2
![screen shot 2018-03-09 at 12 24 31 am](https://user-images.githubusercontent.com/22830439/37193626-582c6682-2330-11e8-9773-b99f38b23b58.png)

**Comment by danfinlay** [comment]
For help using MetaMask, please email our support team at support@metamask.io

It might help for you to include your state logs:
https://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs
