### ISSUE TITLE
[DEV] move ui-dev.js and mock-dev.js to ./development/

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3503]
It looks like `ui-dev.js` and `mock-dev.js` belong into the `./development` folder.

They are currently within root.

**Comment by anticlimactic** [comment]
Happy to have a go at this one!

**Comment by lazaridiscom** [comment]
@anticlimactic , fine to me, I leave this to you if you want it! `git mv` and the correction of  `./package.json` will do it.
