### ISSUE TITLE
Metamask not working

### ISSUE THREAD

**Issue by grimaldo35** [MetaMask/metamask-extension#3506]

**Comment by lazaridiscom** [comment]
@grimaldo35, please contact https://support.metamask.io (and provide them if possible with a little bit more information).

**Comment by kumavis** [comment]
@lazaridiscom thanks-- better to just give the email link, ( support@metamask.io ). The submit form on the support website is not obvious.

**Comment by tmashuang** [comment]
Closing issue with no reproduction steps and should gain insight through the proper support link/email above.
