### ISSUE TITLE
Deleting accounts and networks

### ISSUE THREAD

**Issue by filips123** [MetaMask/metamask-extension#3507]
Can you please support deleting accounts and custom RPC networks? This would be very useful because users will be able to delete old test accounts and networks.

**Comment by tmashuang** [comment]
Deleting accounts and custom RPCs from the network  are not currently supported. We could hide accounts and networks in MetaMask. Closing this issue as a duplicate of #2028, #1658.

**Comment by gerchicov-bp** [comment]
@tmashuang AND? how to delete an extra network if I wrote it with mistakes and so now it is totally useless?

**Comment by tmashuang** [comment]
Switch back to one of the default networks and add reenter the Custom Rpc.
