### ISSUE TITLE
More CustomRPC options in network dropdown list

### ISSUE THREAD

**Issue by p-s-dev** [MetaMask/metamask-extension#3512]
The network dropdown list contains Mainnet, testnets, localhost, and the **last two custom RPC that were used**.  

If you use more than two custom RPC urls, you need to constantly go in to the Settings window and copy-paste the "New RPC URL".

It would be really nice if the Settings UI allowed for a user-defined list of RPC urls to show in the network dropdown list with "add new" and "remove from list" functions.  Maybe the list of RPC Urls could contain a "visible" toggle boolean for each, which would allow the urls to be saved but not shown in the "select network" dropdown by default.

**Comment by bdresser** [comment]
@p-s-dev thanks for the feedback - this was partially handled in https://github.com/MetaMask/metamask-extension/pull/5096 by persisting the most recent three custom RPC URLs. 

We will hopefully add more robust management features as we explore allowing users to add ETH-like networks or dapp-suggested custom RPCs. 

Closing for this issue for now - I've flagged your feedback for our designer, and you can keep up on these proposed features on https://github.com/MetaMask/metamask-extension/issues/5101#issuecomment-416494564 or https://github.com/MetaMask/metamask-extension/issues/3604
