### ISSUE TITLE
password: how many characters max?

### ISSUE THREAD

**Issue by Katrin007007** [MetaMask/metamask-extension#3515]
How many characters can the metamask password be made out of at max?

Thanks in advance

**Comment by tmashuang** [comment]
The password can be as long as you want. Passwords can be paragraphs long, as long as it is the correct form. MetaMask doesn't save passwords on a central database, meaning MetaMask does not have a way to recover passwords on our side. Make sure it's back up! Hope this helps.

**Comment by Katrin007007** [comment]
Big thanks Mr. Huang!
As you can see, I new. This would be my first ewallet. So I apologize for the next question too:
what do you mean with the "correct form" of the password?
Thanks again!

**Comment by tmashuang** [comment]
The correct form that the password was created. This mostly pertains to translations. Ex. A password in English won't be accepted if it is the same words in Spanish.
