### ISSUE TITLE
web3.eth.accounts throws Error: Invalid JSON RPC response: undefined

### ISSUE THREAD

**Issue by TrejGun** [MetaMask/metamask-extension#3524]
so i have my local setup and trying to develop on localhost using metamask and ethereumjs-testrpc

testrpc works using my metamask mnemonics
```sh
node_modules/.bin/testrpc -m "xxx yyy"
```
when i'm trying to get accounts list with `web3.eth.accounts` from console it  throws `Error: Invalid JSON RPC response: undefined` but in metamask itself it shows correct data

i started to debug and found out that there should not be any rpc request because it gets data from `web3.currentProvider.publicConfigStore.getState()` which has correct data.

then i realized that debugger is pointing me out to wrong method
it should be `MetamaskInpageProvider.prototype.send` but in fact `MetamaskInpageProvider.prototype.sendAsync` is called, which does not return anything so response is really undefined. My guess something is overriding send with sendAsync but i can't find what

**Comment by TrejGun** [comment]
it was web3@1.0-beta

**Comment by VickyPhoton** [comment]
@TrejGun I am still getting this issue how am I supposed to solve this issue?

**Comment by TrejGun** [comment]
@VickyPhoton 
it was sooo long time ago... i dont remember
you can dig my fork if you like 
https://github.com/TrejGun/BitWallet
