### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3530]
Guide to translating:
https://github.com/MetaMask/metamask-extension/blob/master/docs/translating-guide.md

**Comment by AKingUltra** [comment]
Working on it now.

**Comment by AKingUltra** [comment]
First iteration of German translation.
1) I am not perfectly happy with a few word/wording and will work on them
2) I used the formal way of addressing users. Question is whether this is correct or if the informal way is preferred.
[messages_de.txt](https://github.com/MetaMask/metamask-extension/files/1811605/messages_de.txt)

**Comment by AKingUltra** [comment]
Still formal but revised iteration
[messages2_de.txt](https://github.com/MetaMask/metamask-extension/files/1814532/messages2_de.txt)

**Comment by lazaridiscom** [comment]
Is here still something needed?

**Comment by Gudahtt** [comment]
This has been completed in #3575, so I'll close it for now. We're pursuing other means of keeping these up-to-date over time.
