### ISSUE TITLE
Translate to Tagalog

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3535]
Guide to translating:
https://github.com/MetaMask/metamask-extension/blob/master/docs/translating-guide.md

**Comment by marvinvista** [comment]
Thanks Dan. Working on this. 👨‍💻

@danfinlay

**Comment by marvinvista** [comment]
Done! Opened a pull request here: Tagalog Translation #3574.

@danfinlay

**Comment by mapmeld** [comment]
Recommend marking this one as closed
