### ISSUE TITLE
Add Translations

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3537]
This is a meta-issue (ZenHub "epic") which links to multiple other issues, and represents the completion of those other issues. Install the ZenHub browser extension to view the related issues.

This epic represents the goal of adding all desired translations to MetaMask!

When a person submits a translation, they should be invited to the [Translators team](https://github.com/orgs/MetaMask/teams/translators/members), so they can be notified when we update some language and could use help updating the translations.

**Comment by danfinlay** [comment]
Guide to translating:
https://github.com/MetaMask/metamask-extension/blob/master/docs/translating-guide.md

**Comment by frostornge** [comment]
Add Korean please!

**Comment by cassidypignatello** [comment]
any chance of adding an issue for Bahasa Indonesia? I'd gladly grab it :)

**Comment by danfinlay** [comment]
@espoem you can just open a PR if you have it ready already, thanks!

**Comment by danfinlay** [comment]
@cassidypignatello Feel free to open an issue for Bahasa Indonesia, or just submit a PR, we'd be happy to have it!

**Comment by Gudahtt** [comment]
We're still working on adding and improving translations, but we're not using this issue to track these improvements anymore.
