### ISSUE TITLE
Adding new MKR token fails to auto-fill token params

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3553]
New token address: `0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2`

Throws error:
```
popup.js:1 Uncaught (in promise) Error: [ethjs-contract] while formatting incoming raw call data "0x4d4b520000000000000000000000000000000000000000000000000000000000" Error: Number can only safely store up to 53 bits
```

**Comment by kumavis** [comment]
possibly related? https://github.com/MetaMask/metamask-extension/issues/3617

**Comment by nanexcool** [comment]
Hey, so MKR is a `ds-token` and we use `bytes32` for name and symbol instead of `string`. Think that could be it?

`0x4d4b52 == MKR`

**Comment by danfinlay** [comment]
That definitely could be it. Could you tell me more about why you chose to do this? Is there an EIP for this kind of token naming format we should be aware of?

If we have to check for multiple different token symbol methods, we're going to start multiplying the amount of VM work we do when we list tokens, it would be *great* to consolidate on a standard.

Maybe if tokens start also implementing something like [EIP 165](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md) to make it slightly cheaper to check what interfaces it supports. I'd prefer one that returns an array of supported EIP numbers.

**Comment by danfinlay** [comment]
Alright, we'll try to support this kind of token signature the sprint after next. Thanks for the details & explanation.

**Comment by kumavis** [comment]
so `string` and `bytes32` are incompatible because `string` has a length pre-fix

**Comment by estebanmino** [comment]
@bdresser  yes it does, as long is a ERC20 token is going to work.

**Comment by danfinlay** [comment]
It is not a normal ERC20 token, and so possibly no.

**Comment by estebanmino** [comment]
The functionality only interact with `balanceOf` that is implemented in this contract, isn't that enough? Then the name and symbol is extracted from `eth-contract-metadata`

**Comment by estebanmino** [comment]
I just tested it and works when user address has balance

**Comment by danfinlay** [comment]
That's kindof awesome. It must be because we don't need to fetch the symbol when we already have it in the local token list.

**Comment by bdresser** [comment]
fixed in https://github.com/MetaMask/metamask-extension/pull/4844
