### ISSUE TITLE
When edit transaction in Beta Metamask, it creates wrong tx

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#3554]
Bug Reports:

 Editing a tx completely messes with tx data.
Example: 
```js
return token.methods['approve(address,uint256)'](this.tokenStore.proxyMultiSenderAddress, this.tokenStore.totalBalanceWithDecimals)
      .send({from: this.web3Store.defaultAccount, gasPrice: this.gasPriceStore.standardInHex})
```
If I do click send -> it would send a normal tx like it should.
If I do click Edit in metamask BEFORE sending, it actually, overwrites data, to, value fields:
### Scenario#1: if token address was added to metamask 
Instead of making original `approve` call, it now turns it into token transfer.

### Scenario#2:
IF token address is not known to metamask(if you haven't added that token address to metamask)
when EDIT button was clicked, it turns into simple ETH transfer with the VALUE put into ETH(even if it was simple approve call) to the recipient.
Very dangerous! 

So, Please don't use EDIT button in new metamask, it completely messes the data

URL to check on any network:
https://poanetwork.github.io/multisender/#/
1. Just select any token address (make sure you have some balance)
2. Provide JSON [{"0xa35c9Af9e78B90B7217e1262cBd3638075A14CEe": "1"}]
3. click next, next
When metamask pops up for 1st tx, click edit
Now your pregenerated `approve` call turned into token transfer.

**Comment by danjm** [comment]
@rstormsf Is this only for `approve()` calls? Or have you seen it for other method calls as well?

**Comment by rstormsf** [comment]
@danjm I suspect it will be the same story for other calls, just try to `edit` the tx. 
I haven't tested with other pre-generated `data`
