### ISSUE TITLE
back up com palavras chaves - perda de tokens 

### ISSUE THREAD

**Issue by FCOGUIMARAES** [MetaMask/metamask-extension#3561]

**Comment by FCOGUIMARAES** [comment]
tive um problema no meu computador e o mesmo perdeu o icone metamask
esta conta estava com alguns tokens 
estou tentando recuperá-la 
solicito ajuda 
possuo as palavras chaves e o endereço da conta

**Comment by kumavis** [comment]
google translate:
>  I had a problem on my computer and the same lost the metamask icon
this account was with some tokens
I'm trying to get it back.
I ask for help
I have the key words and the address of the account

**Comment by jrmoreau** [comment]
Si tiene su frase clave, puede restaurar sus cuentas y claves privadas.

Hay dos maneras:

Restauración de DEN existente

Después de aceptar los términos y condiciones durante la configuración, haga clic en "Restaurar desde DEN existente".
Ingrese su frase clave

O,

Restaurar desde la pantalla de "bloqueo"

Seleccione "Cerrar sesión" en el menú superior derecho.
Haga clic en "Restaurar desde la frase semilla"
TbqWhUpF78Qw8zfpA-mihENbBe6mQng4_oAi8PasBPVCKBbu0Gj_GbpfIgHgWyTlej0x9Vm4lxNMgmXdmDVzWVU7pCzC0ZFARExlcRkbrD-9Gwct2Erc5vt3cpdkFgeOBydSR4h-
Ingrese su frase inicial de 12 palabras y una nueva contraseña.
Haga clic en Aceptar.
Solo tendrá una cuenta restaurada al principio, haga clic en "Crear cuenta" (menú superior derecho de la cuenta) para cualquier cuenta faltante.
Para restaurar y ver los tokens, consulte esta guía:
http://metamask.helpscoutdocs.com/article/16-managing-erc20-tokens

Después de restaurar las cuentas, puede exportar y guardar la clave privada siguiendo esta guía: https://secure.helpscout.net/docs/5a4d70662c7d3a194367d6ef/article/5a4e544b0428631938009829/
