### ISSUE TITLE
Metamask account somehow comprimised.

### ISSUE THREAD

**Issue by hollon21** [MetaMask/metamask-extension#3570]
Hello,

It would seem that somehow my metamask account was compromised. Luckily, I did not have too much in it,  but I lost at least 1k USD. I don't expect to be getting this back but can someone help me figure out what I've done wrong? I really don't want this to happen in the future obviously.

My Metamask address: 0x264cA39e97A81e566f16dFaB0FDf928FF8249511
 You can see all the transactions after 4500 PRL went to the same address. If you follow it, it goes through several address until it gets to this one:

0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208

This address according to etherscan is IDEX, which means that whoever pulled this off has undoubtedly already cashed out my tokens. I don't understand how this happened to me though. I've only used metamask with ethlend and myetherwallet. I just noticed that now when I visit myetherwallet, MYETHERWALLET LLC isn't displayed to the left of the address.

What can I do to re-secure my metamask account/computer and prevent this from happening again?

Edit: Just installed the Metacert (formerly cryptonite) addon and it says that the website that comes up when I go to my etherwallet is safe and real. I'm really confused by how this could've happened

Edit 2: If you're looking at the transactions, the more recent ones are me transferring out the dregs of what was left that the scammer didn't take for some reason.

**Comment by hollon21** [comment]
Just installed the Metacert (formerly cryptonite) addon and it says that the website that comes up when I go to my etherwallet is safe and real. I'm really confused by how this could've happened

**Comment by tmashuang** [comment]
If you have an issue with MetaMask please email support@metamask.io with the description you provided. As well as transaction logs. https://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs

**Comment by satnam** [comment]
Hi @hollon21 I hope @tmashuang's suggestion helps you figure out exactly what happened. It sounds like you may have visited a phishing website. At any point were you asked to provide your private key to a website? 

Regarding the Cryptonite extension, it will block known phishing sites as well as present a green shield when you're on a legitimate cryptocurrency exchange, project website or block explorer. Keep an eye out for the green shield when visiting these types of websites.

For context, here's an example of some phishing sites that MetaCert added in recent days including some fake MyEtherWallet domains.
![image](https://user-images.githubusercontent.com/4543496/37550065-9f946e06-2944-11e8-85e5-137297b98c5c.png)
