### ISSUE TITLE
Complete i18n templates

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#3571]
Screens: 
- [x] Login
- [x] recover from Seed phrase
- [x] Settings
- [x] Info
- [x] Send ETH
- [x] Add Token
- [x] Import Account Disclaimer
- [x] Current network indication
- [x] transaction history

edited by kumavis

**Comment by kumavis** [comment]
network option menu looks good, but the current network at the top is in english

![image](https://user-images.githubusercontent.com/1474978/37436231-11ac326e-27a4-11e8-8d6a-2f34e190a4c4.png)

**Comment by kumavis** [comment]
Some news things are added to the i18n files here 
https://github.com/MetaMask/metamask-extension/pull/3581/files

**Comment by danfinlay** [comment]
Implementing these changes on this branch:
https://github.com/MetaMask/metamask-extension/tree/i3571-CompleteI18nTemplates

**Comment by danfinlay** [comment]
Unassigning myself for the moment because I'm being occupied with other things. Someone else could pick up this task and resume it.
