### ISSUE TITLE
Deprecate Web3 as injected library

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3573]
The Web3 library adds 500kb to every page a MetaMask user loads.

We should only inject `web3.currentProvider`, and allow developers to bundle convenience libraries as they prefer them.

Causes a huge breaking change, should be accompanied by a big blog post whose link could be added to our deprecation notice on the web3 object (some time in advance).

Related to #3382.

Less important once we fix #714, since we'll only inject on pages that request it.

**Comment by lazaridiscom** [comment]
related https://github.com/MetaMask/metamask-extension/issues/2350#issuecomment-370717226

**Comment by whymarrh** [comment]
> Less important once we fix #714, since we'll only inject on pages that request it.

Do we want to close this for now, considering we've implemented #714?

**Comment by whymarrh** [comment]
Do we want to close this in favour of #7163?

**Comment by danfinlay** [comment]
Yes, that makes sense.
