### ISSUE TITLE
Update Sign Request Popup with latest UI styles

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3578]
Signature request pop UI needs a slight style refresh to better match the latest UI styles.

![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/a3b13e7e-8c54-493c-bdde-2d5cfea451a0)

**Comment by cjeria** [comment]
No new designs have been worked on for this screen. Moving back to "pending design" for now.

**Comment by bdresser** [comment]
may want to add a "reject all" button 

will also be related to #4803

**Comment by whymarrh** [comment]
> will also be related to #4803

Specifically this popup is being reworked as part of #4803

**Comment by bdresser** [comment]
Closing in favor of #4803 & https://github.com/MetaMask/metamask-extension/issues/4752

@whymarrh, check the newest designs on https://github.com/MetaMask/metamask-extension/issues/4752
