### ISSUE TITLE
Ensure seed phrase is not persisted in UI between restarts

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3583]
As reported [in this twitter thread](https://twitter.com/rbelane/status/974334026340360192). It may already be fixed, but we should verify.

The bug may be that when `showSeedWords` is active (during the "reveal seed phrase" feature), the seed words are persisted to the unencrypted portion of disk, so on restart, even a locked vault makes the seed phrase recoverable by someone with access to the user's disk.

It may be some other cleanup issue, needs investigation.

**Comment by danfinlay** [comment]
Related to #4032

**Comment by alextsg** [comment]
Fixed with #4059
