### ISSUE TITLE
Create gas input using estimated transaction time chart

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3586]
We have a nearly complete, working estimated transaction time chart [here](https://github.com/gitcoinco/skunkworks/pull/50).

Among some other styling adjustments, it needs a slider that corresponds to a selection dot on the chart, like is seen in this animated design:

![gas slider design](https://user-images.githubusercontent.com/597770/36178945-da40811c-111a-11e8-960d-5d82e9e8d13c.gif)

The finished component could either be just the chart + slider, or could include the dynamic price/time estimate above the chart, and be ready to drop into our transaction fee component.

**Comment by danfinlay** [comment]
To clarify, we know the chart currently doesn't match this design's chart, and this issue does not include all of that design work (unless you wanted to just forego that chart for a new one, optional).

The MVP would be to add that outlined dot representing the current selected gas price to the chart, plus the slider itself. The dot does not need to include the tooltip yet as part of this issue, just get the dot corresponding to the slider.

**Comment by bdresser** [comment]
evolved in to https://github.com/MetaMask/metamask-extension/issues/4789
