### ISSUE TITLE
Can't log back in

### ISSUE THREAD

**Issue by shyheim103** [MetaMask/metamask-extension#3606]
Meta Mask logged me out somehow and now it won't let me sign back in. It is asking me to create a new password. I haven't done this as I feel like it will give me a new account. How do I fix this?

**Comment by shyheim103** [comment]
All my ETH is gone now. can someone help? I also can't play etherbots or even see them. Everything is gone.

**Comment by jrmoreau** [comment]
Can you please submit a ticket to our support team? support@metamask.io
