### ISSUE TITLE
Endless working of `npm start` process

### ISSUE THREAD

**Issue by askucher** [MetaMask/metamask-extension#3607]
Expected: It should be done in 5-10 minutes

![screen shot 2018-03-19 at 06 45 52](https://user-images.githubusercontent.com/4496793/37578400-3f112372-2b41-11e8-8f23-343e1d9988a2.png)

I can see this picture for 1 hour.

**Comment by tmashuang** [comment]
`npm start` is the same as `npm run dev` which watches files changes.
