### ISSUE TITLE
Privacy : Metamask balances and information is readable without confirmation

### ISSUE THREAD

**Issue by negamax** [MetaMask/metamask-extension#3608]
This is a feature request. I do think it's important to have this addressed. If concern is around usability, I suggest providing an option in settings for this.

Right now, Metamask balances can be queried by *any* website that person is visiting. This combined with cross domain profiling can create a notable security issue and that person can be de-anonymized. 

A possible solution would be to prompt for allowing read access (like Chrome does for push notifications)

**Comment by negamax** [comment]
To add more context. It's not Metamask balances as it's a bridge to the blockchain. But the user account information that can be read by web3 injection using 

`web3.eth.accounts[0]`

**Comment by radeksvarz** [comment]
+1 This was already experienced. Current workaround is to create the empty account and switch between main and empty accounts accordingly.

**Comment by danfinlay** [comment]
Closing as duplicate of #714
