### ISSUE TITLE
Unlock screen design + enable password manager

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3614]
While testing the new unlock screen in full page mode, I tried using my password manager and it didn't work. This might be enabled by following password form input best practices. Here's 1password's https://support.1password.com/compatible-website-design/

Attaching the design here. I also created a codepen version to reference for the password input animation: https://codepen.io/cjeria/pen/ZxBeEM?editors=1100

Also notice that I've removed the top bar (with fox and network switcher as it's not necessary when account is locked).

Let's keep the animated fox but with new dimensions of this design. 

![image](https://user-images.githubusercontent.com/597770/37561793-29cbdf8e-2a15-11e8-9940-74a9ea9b4dc7.png)
![unlock screen](https://user-images.githubusercontent.com/597770/37611448-a0704576-2b5f-11e8-8a5f-40390785fffd.gif)

**Comment by stephenowl** [comment]
this unlock screen just appeared out of the blue when I went to access my Meta Mask , any idea why? I was immediately suspicious obvs.

**Comment by cjeria** [comment]
@stephenowl a new update of the extension was just released which auto updates and logs you out. Nothing to be concerned about. Sorry for any confusion this may have caused!

**Comment by stephenowl** [comment]
thanks.  I have lost  recent transactions (from end april) including 10
pending (eth so damn slow at mo.) they haven't come back!

**Comment by stephenowl** [comment]
also lost all recently added tokens, have to add them all again

**Comment by stephenowl** [comment]
also 'my accounts' list is completely mixed up, in a hopeless random order

all in all, my metamask is a total f...ing mess - almost unusable

**Comment by bdresser** [comment]
@stephenowl the accounts issue you mentioned is tracked as #4442 

for issues with pending tx or lost tokens please reach out to support@metamask.io with a description of your issue and a copy of your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI-)

**Comment by acuvic** [comment]
hello @cjeria , I acknowledge your old post but please if you have the answer?
I installed Metamask extension on Brave browser, but cannot get 1password to work with thee login page. Is this commit not in the latest code? I'm a newbie so might have missed something. I'll definitely tip (can do Doge but eth later when wallet sorted).
