### ISSUE TITLE
Unable to add unpacked extension - missing i18n key

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3615]
`There is no "message" element for key blockiesIdenticon`

> master branch, commit e2f340b3242c436bd4d7bc802662ae6f9f195899

reported by mariano.conti in https://chat.makerdao.com/channel/keeper

![screenshot from 2018-03-18 15-11-04](https://user-images.githubusercontent.com/1474978/37613285-dc519dba-2b64-11e8-893b-3054b85bf958.png)

**Comment by tmashuang** [comment]
Oh this was my mistake, when adding more keys for the strings, I made a typo. Fixed it here: https://github.com/MetaMask/metamask-extension/pull/3591. It was merge into master, so I believe it will be fixed with a pull and rebuild.

**Comment by tmashuang** [comment]
Messaged the original issue reporter and the latest master resolved his issue, closing.
