### ISSUE TITLE
Provide Test Cases for Web3 1.0 Support

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3618]
affects #3642 and MetaMask/provider-engine#189

In order to clarify the implementation-requirements of the web3 1.0 support, test-cases should be provided.

The test-cases can be used for both web3 1.0 support implementation paths:

* Path A - via Websockets (see MetaMask/provider-engine#189)
* Path B - via polled-subprovider, see #3642

## Step One

Provide simple js code files, which demonstrate the web3 1.0 access (which should fail)

from https://github.com/MetaMask/metamask-extension/issues/3642#issue-307084613

```js
// Importing the latest version from NPM
const Web3 = require('web3')

// initializing a local instance
const web3 = new Web3(window.web3.currentProvider)
web3.eth.subscribe('logs', {
  address: '0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0',  // EOS token is popular atm.
  topics: [], // A token transfer log would be good for now.
}, function (err, result) {
  if (err) throw err
  console.log('Success!', result)
})
```

## Step Two

Embed those code files into the MM test system.

Draft/Starting-Point: https://gist.github.com/ryan-rowland/54218bde11170734acb276a3564ac06b

## References
from: https://github.com/MetaMask/metamask-extension/issues/3618#issuecomment-374976884

### web3 original test-cases
https://github.com/ethereum/web3.js/blob/1.0/test/helpers/test.subscription.js
https://github.com/ethereum/web3.js/blob/1.0/test/eth.subscribe.js

### Subscription relevant specs:
https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html

**Comment by ryan-rowland** [comment]
Here are the tests `web3.js` is running against their own provider to test subscriptions:

https://github.com/ethereum/web3.js/blob/1.0/test/helpers/test.subscription.js
https://github.com/ethereum/web3.js/blob/1.0/test/eth.subscribe.js

**Comment by ryan-rowland** [comment]
Here's a first pass at a draft of **Step A**. Some of the actual tests are filled in, but toward the bottom there are some empty tests just outlining what needs to be validated.
https://gist.github.com/ryan-rowland/54218bde11170734acb276a3564ac06b

**Comment by lazaridiscom** [comment]
@ryan-rowland , very nice! I've updated the document. At this point it should be much easier for anyone to get started.

**Comment by ryan-rowland** [comment]
Running some tests locally using `web3` on npm against rinkeby. Some of my initial assumptions were wrong, particularly regarding the `subscribe` callback. It actually runs every time a `data` event fires with `(err, data, subscription)`. The web3 docs aren't very thorough in this regard.

I'll update later when I have time.

**Comment by lazaridiscom** [comment]
@ryan-rowland , i'm closing down here. For the case you still want to push this, just go on please.

follow-up MetaMask/provider-engine#189 & #3642
