### ISSUE TITLE
Reopen ganache to restart development network, the MeatMask transcation state isn't refreshed right.

### ISSUE THREAD

**Issue by 3for** [MetaMask/metamask-extension#3629]
I'm now following the website below to try to use truffle and ganache in windows 10 with Chrome browser 64.0.3282.186 and MetaMask 4.2.0:
http://truffleframework.com/tutorials/robust-smart-contracts-with-openzeppelin

I install & open ganache to start the development network, the block height is zero;
Using 'truffle migrate' to deploy the contracts on the development network successfully, the block height in ganache is 4;
made a token transfer successfully, the block height in ganache is 5;
close the ganache and reopen ganache, the block height is reset to zero!
I redeploy the contracts,, the block height changed to 4;
made a token transfer failed, for the height is not corresponding.("Error: the tx doesn't have the correct nonce. account has nonce of:4 tx has nonce of:5 at runCall")
![image](https://user-images.githubusercontent.com/30716372/37644695-95f111b0-2c5f-11e8-88f6-c2b9315a391d.png)
![image](https://user-images.githubusercontent.com/30716372/37644860-09a48056-2c60-11e8-96e6-c9ead10aed91.png)

How can I fix this problem while using MetaMask to test?

**Comment by tmashuang** [comment]
Hamburger icon, top-right, > Settings > Reset Account. This should only be used in the scenario that you are describing and not for any other network other than Ganache/Testrpc. Might require to disable/enable the extension.

**Comment by 3for** [comment]
Thank you so much. @tmashuang Reset the Account is just helpful.
