### ISSUE TITLE
Investigate possible causes of a password suddenly not working

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3643]
Occasionally users report that their password no longer works. ([Example](https://github.com/MetaMask/metamask-extension/issues/2655#issuecomment-374769459))

We need to investigate this, and see if we can find a case where our normal storage procedure results in a vault that will not be unlocked by its normal password.

If we add a bounty to this, the bounty will be paid out to the next person who can reproduce a case that meets those criteria. We should re-post the bounty after that point, to keep a standing bounty for anything that can cause this.

A fix should include a test case, probably testing the [metamask-controller](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/metamask-controller.js) for its `data` events (passed to storage), vs its [submitPassword](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/metamask-controller.js#L372) method.

It's possible this could be reproduced as a unit test of [eth-keyring-controller](https://www.npmjs.com/package/eth-keyring-controller) by itself.

**Comment by lazaridiscom** [comment]
@danfinlay i remembered the pattern:

> Basically the recent terms of service agreement or whatever that was - messed up the account.
from: https://github.com/MetaMask/metamask-extension/issues/3330#issuecomment-369351791

> Cant access metamask account after updating and agreeing to new terms and conditions
from:  https://github.com/MetaMask/metamask-extension/issues/2942

> I had to accept the terms of agreement and so on
from: https://github.com/MetaMask/metamask-extension/issues/3467

The last one has a comment of you which ends up in this fix: #3076

I assume the data-wipe results into a new request for terms&conditions - and not e.g. an update to a specific new version?

**Comment by danfinlay** [comment]
All three of those look like the user mis-understanding when we show the terms. We show the terms on first app boot (i.e. it can indicate that MetaMask storage was completely wiped. This should be fixed by #3083, included in the next release.

This bounty is not for that bug. This bounty is for situations where MetaMask shows the password login page (not the terms), and the user's old password does not unlock their vault anymore.

**Comment by danfinlay** [comment]
Closing since all the examples of this seem to be fixed by #3083.
