### ISSUE TITLE
Why "Gas limit set dangerously high. Approving this transaction is likely to fail."?

### ISSUE THREAD

**Issue by taxic** [MetaMask/metamask-extension#3646]
In Metamask, when we set a higher gasLimit, i.e., close to current block gas limit, it will show this message:
> "Gas limit set dangerously high. Approving this transaction is likely to fail."

I don't understand the reason behind it. Anyone has good explanation for it? Thanks!

Currently, I get some possible reasons:
1. higher gasLimit will cost you much ether, and you can't afford it, thus causing fail.
2. higher gasLimit may exceed the current block gas limit, and then you will wait for a long time until miners modify the block gas limit, which could cover the gasLimit you set.
3. miners tend to confirm more transactions in one block (because of meaning more TX rewards apart from mining rewards), thus a transaction with very high gasLimit will have much lower priority to be confirmed first.

**Comment by riccardopersiani** [comment]
Hi, 
got the same problem this morning.

Metamask says: "Gas limit set dangerously high. Approving this transaction is likely to fail."

My account balance is 20ETH and my transaction fails like this:
[link to rinkeby.etherscan](https://rinkeby.etherscan.io/tx/0x8df0bacf718f69fc3f88214e909bb87cb42c740899331888f5c4931206da8598)

I fixed it setting `gas: '1000000'`.
Like you, I still do not understand the reason behind it.

**Comment by danfinlay** [comment]
MetaMask automatically estimates the amount of gas required to complete a transaction. Sometimes, an estimate will take up very close to a full block of gas. This can mean that the transaction is going to hit an error and fail, but we cannot yet tell for sure if that is the case. All MetaMask can do at the moment is warn you that this transaction is likely to fail with the estimated gas limit, and let you act accordingly.

**Comment by taxic** [comment]
I see. Metamask doesn't check whether the high gas cost is set by the return value from eth_estimateGas.
