### ISSUE TITLE
What lines do I edit to change the default network to Kovan?

### ISSUE THREAD

**Issue by NicholasFarrow** [MetaMask/metamask-extension#3647]
I am writing a python script for a website which requires metamask to be seen on the correct network (Kovan in this case).

Unfortunately when using selenium in python for the chrome environment you are unable to interact with the extension.

Therefore I have downloaded the metamask source and am looking for a line(s) to change so that when I use this modified extension on selenium, the default net will be Kovan.

I have been looking but am yet to find the location where Mainnet is set to default.

**Comment by alextsg** [comment]
Hi @NicholasFarrow , if you go to `app/scripts/first-time-state.js`, it currently uses `rinkeby` and `mainnet` as the default networks based on the environment. Changing that to `kovan` should make Kovan the default instead.

**Comment by danfinlay** [comment]
Closing in favor of #3653.

**Comment by NicholasFarrow** [comment]
@alextsg Great thanks a lot Alex, much appreciated!

I did not realise that the code from unpacking the app was diffrerent to the code on Github!

Thanks, I'll give it a shot.
