### ISSUE TITLE
Blank popup on specific network

### ISSUE THREAD

**Issue by adam-clarey** [MetaMask/metamask-extension#3649]
When connecting to Rinkeby, the popup shows the account details in the popup then if the popup closes and you click the icon to open it again its completely blank.

I suspect its because ive been testing some transactions on rinkeby that maybe throwing an exception. 

Latest version of chrome and app.

Attached is what i see in console
![screen shot 2018-03-21 at 12 55 17](https://user-images.githubusercontent.com/907933/37711290-22d762de-2d08-11e8-861c-038979de8226.png)

**Comment by danfinlay** [comment]
That's an interesting and strange case to have gotten your app into.

Would you mind sending [your error logs](https://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs) to support [at] metamask [dot] io?

**Comment by danfinlay** [comment]
I'll reopen when we have some information to reproduce this with. Probably as a new issue.
