### ISSUE TITLE
When MetaMask installed (not necessarily activated) images on website do not display correctly

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/metamask-extension#3651]
Example websites which not show images properly. 

www.holidaypirates.com
www.urlaubspiraten.de
www.travelpirates.com
www.urlaubspiraten.at
www.vakantiepiraten.nl
www.piratinviaggio.it
www.wakacyjnipiraci.pl
www.voyagespirates.fr
www.viajerospiratas.es
www.ferienpiraten.ch
www.semesterpiraterna.se

**Comment by danfinlay** [comment]
Just need to be added to our domain blacklist in the `inpage.js` script for the next release.

**Comment by kumavis** [comment]
This is because we are setting `window.log` in `inpage` https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/inpage.js#L13
