### ISSUE TITLE
Since yesterday i have been battling with delay to connect to ethereum main network. I have tried i could. Please help

### ISSUE THREAD

**Issue by graciousunit** [MetaMask/metamask-extension#3659]

**Comment by jrmoreau** [comment]
Try clicking the network dropdown and selecting another network. Then switch back to the main network.

**Comment by graciousunit** [comment]
I have done that several time but still it is not connecting. I have switched to other network is not connecting. I have disable and delete extension but still nothing is happening. Please help.

**Comment by graciousunit** [comment]
It can not allow me to restore my DEN. Please help.
