### ISSUE TITLE
Ensure bundle script is determinsitic

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3664]
This is a huge issue for verifiable security. The Mozilla team has gotten good about trying to reproduce our bundles, but unfortunately it seems [browserify is currently non deterministic](https://github.com/browserify/browserify/issues/1796).

Fixing that could be part of the solution, but there may be other parts of our current build that are non deterministic. We need to find what variables there are, and develop a strategy for consistent builds, so that consumers of MetaMask can easily verify that the source code that is visible here on GitHub really is what produced the software they're running on their computers.

**Comment by danfinlay** [comment]
Fixes #3664

**Comment by abitrolly** [comment]
Have it built on Windows and Linux and then compare?

**Comment by brad-decker** [comment]
@Gudahtt i know we recently did fixes for this for firefox does this mean we can close this issue or is it still a thing

**Comment by Gudahtt** [comment]
I believe this has been resolved by #14763 and #14623. Possibly other PRs were related as well.
