### ISSUE TITLE
Fix bug where nonce is under-calculated

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3670]
https://sentry.io/metamask/metamask/issues/476304902/

specifically https://sentry.io/metamask/metamask/issues/476304902/events/16312681729/

Seems like our nonce calculation is a bit screwy in some cases?

**Comment by kumavis** [comment]
hard to really understand whats going on here just from nonceDetails.

`params.highestLocalNonce === 0`
but
`local.details.highest === 9`
and
`params.highestSuggested === 6`

That said! a nonce of `0x9` was selected, but it had already been used.
If the highest existing local nonce is indeed 9 as the nonceDetails naming suggests, we should have used 9+1 = 10. Is this an off-by-one error between choosing strategies?

```json
{
  "params": {
    "highestLocalNonce": 0,
    "nextNetworkNonce": 6,
    "highestSuggested": 6
  },
  "local": {
    "nonce": 9,
    "details": {
      "highest": 9,
      "startPoint": 6
    },
    "name": "local"
  },
  "network": {
    "nonce": 6,
    "details": {
      "baseCount": 6
    },
    "name": "network"
  }
}
```

**Comment by ElPatricio** [comment]
Hi Guys, I'm having this problem. How do I get around it? It's preventing me from making any transactions and I want to close my CDPs in Maker. Thank you.

**Comment by frankiebee** [comment]
the test looks good to me and happy its passing
