### ISSUE TITLE
EIP155 Transaction Failed: invalid sender

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3673]
https://sentry.io/metamask/metamask/issues/476440965/

this seems to be when users try to connect to a client where `networkId !== chainId`

```
Transaction Failed: invalid sender
```

**Comment by kumavis** [comment]
here is one where networkId = 1 (etc?) https://sentry.io/metamask/metamask/issues/476440965/events/16307225092/

**Comment by bdresser** [comment]
both issues are gone from sentry at this point
