### ISSUE TITLE
[BETA-UI] Import JSON Keystore didn't work

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#3675]
In Metamask Beta, I tried to import an account with JSON Keystore and nothing happened.
I click Import button and I don't see any logs, in background.html nor in home.html
 Has anybody got it working successfully?

**Comment by jrmoreau** [comment]
which browser/OS are you using? Just tried importing a JSON myself and it worked, but interested to see which browser you're using. Also, which version of MetaMask?

**Comment by rstormsf** [comment]
Mac OSX
Browser:
Version 62.0.3180.0 (Developer Build) (64-bit)
Metamask: 4.2.0

**Comment by rstormsf** [comment]
The same thing on
`Version 65.0.3325.181 (Official Build) (64-bit)` 
Metamask: 4.2.0 
Mac OSX

**Comment by rstormsf** [comment]
@jrmoreau same goes to you: Which browser you are using, version and OS

**Comment by tmashuang** [comment]
I believe `t.props.goHome is not a function` is the error message that is shown in the console. This issue was fixed here, https://github.com/MetaMask/metamask-extension/pull/3491/files. Any was published yesterday as version 4.3.0.
