### ISSUE TITLE
BLANK METAMASK AND SEED PHRASES

### ISSUE THREAD

**Issue by Wallabok** [MetaMask/metamask-extension#3676]

**Comment by graciousunit** [comment]
What is really wrong with metamask now?. I like like metamask but i do not understand what is wrong. I can not log in or connect to ethereum main network.

**Comment by riccimeta** [comment]
Same problem. No metamask "MASK". Always blank

**Comment by jrmoreau** [comment]
Can you submit screenshots and any error logs you're seeing to support@metamask.io please?

**Comment by Wallabok** [comment]
Ive already sorted it out. my questions weren't answered so I took a risk
and uninstalled and re installed problem is now gone. issue was a blank
screen when you click on the fox attached to google chrome. It worked this
morning fine and then for some reason by midmorning screen was blank. I
hope you can resolve the issue for more people. Thanx
