### ISSUE TITLE
Animation after tx confirmation

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#3681]
when confirming or rejecting multiple transactions that have the same params i noticed that i clicked through 4 transactions with get any feed back from clicking the reject button and before i know it had clicked through them all. In the old ui a transition happened representing moving to another transaction it would be nice if we had some sort of responsive feed back to rejecting or confirming transactions

**Comment by bdresser** [comment]
from @omnat 

> Some explorations by Rimble (design system team) around transaction statuses: https://www.figma.com/file/3OWINeMnH2w2hySyopiupz/Rimble---Transaction-status?node-id=456%3A612

> This is in response to a top dapp developer need they found from their research “help users see how the MM transaction status reflects in the app”..

**Comment by bdresser** [comment]
from @omnat - Rimble team has done some research on this topic ([ref](https://consensys.slack.com/archives/G4V2HTG0Y/p1549668726116000?thread_ts=1549564263.095100&cid=G4V2HTG0Y))

**Comment by bdresser** [comment]
Could also apply to "connect" screens and actions like "speed up" or "cancel"
