### ISSUE TITLE
Add test to ensure all history list items render correctly

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#3684]

**Comment by kumavis** [comment]
doesnt need full integration testing, just making sure its rendered correctly in the history list

**Comment by danjm** [comment]
@frankiebee @kumavis I am modifying this ticket to reflect what I learned about the root of the issue while working on https://github.com/MetaMask/metamask-extension/pull/3774

**Comment by kumavis** [comment]
closed here https://github.com/MetaMask/metamask-extension/pull/3801#pullrequestreview-108484018
