### ISSUE TITLE
Errors on localStorage write crash MetaMask

### ISSUE THREAD

**Issue by hanoncs** [MetaMask/metamask-extension#3706]
*  When I click MetaMask I expect to be prompted for a password.
  *  Right now when I click MetaMask its a blank window
  *  Chrome Latest Updates
  *  Windows 10 Latest Updates

![image](https://user-images.githubusercontent.com/4771689/37845427-19a2e664-2e90-11e8-97b0-9a601f45e142.png)

**Comment by tmashuang** [comment]
The error shows that the web page has lost connection to MetaMask, doesn't help to determine why the extension is not working. Please provide error messages from the extension and the background process. Here's a guide: https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by tmashuang** [comment]
MetaMask version?

**Comment by hanoncs** [comment]
I installed it for the first time just a few days ago.
![metamaskversion](https://user-images.githubusercontent.com/4771689/37854050-e5998fd4-2eae-11e8-88d5-bb7c3b2916b6.PNG)

**Comment by danfinlay** [comment]
In that background log, could you click the top "url link", and then screen shot the code it shows?

I'm talking about this part:
![code link](https://user-images.githubusercontent.com/542863/37858512-ac72c95a-2ec2-11e8-96ab-386d7c426b81.png)

**Comment by hanoncs** [comment]
No problem. 
![metamask_error4_background_pagelink](https://user-images.githubusercontent.com/4771689/37858537-7bc4de0c-2ecb-11e8-975e-0c8953ab439d.PNG)

**Comment by danfinlay** [comment]
@hanoncs I've found the root of your bug. Before I explain that (so we can fix it), here is your workaround: If you have your seed phrase backed up, just uninstall & reinstall for now. If you don't have your seed phrase backed up, let us know and we'll explain how to get it before you uninstall.

Hanocs' bug is that while we've moved to the new `storage.local` API, we still initially write to `localStorage` on app boot, and we don't catch its errors, so when there is a storage overflow error, it crashes start-up.

We could fix this either by:
- Adding proper error handling around our localStorage usage.
- Removing our localStorage usage entirely, since the new method seems to be working for our users just fine.

**Comment by hanoncs** [comment]
@danfinlay I removed and reinstalled. Back working now. That was scary. Thanks.

**Comment by digitalassetjunkie** [comment]
same issue...do not have my private key handy...

**Comment by J4nJ** [comment]
Hm, im kinda scared of uninstalling even though i have most of my private keys backed up. 
How long do these fixes usually take?

**Comment by lazaridiscom** [comment]
@digitalassetjunkie , @J4nJ - you could try this one: https://github.com/MetaMask/metamask-extension/issues/3714#issuecomment-375917067

**Comment by juanKba** [comment]
@danfinlay i have the same problem and i  don't have myseed phrase backed up help me please!

**Comment by rstormsf** [comment]
@lazaridiscom clearing cache doesn't WORK! please don't recommend it

**Comment by lazaridiscom** [comment]
@rstormsf , 

a) look at the times of posting
b) not all installations are the same

**Comment by rstormsf** [comment]
So, what should I do?

**Comment by lazaridiscom** [comment]
@danfinlay , any news on this? This should be worth an hot-fix.

**Comment by danfinlay** [comment]
We are currently writing a hot-fix. Sorry for not responding over the weekend.

If you have a MetaMask with this problem, you can just leave it alone for a day or two, and the hotfix should fix this.

If you need to rush, if you have your seed phrase, you can uninstall & reinstall.

If you need to rush and don't have your seed phrase, you need to figure out how to get your vault data out of the extension's storage.local storage area. We don't have a guide on this yet.

**Comment by godwin-l** [comment]
When the browser reaches the maximum limit of local storage it will show those errors
Empty cache and hard reload it
Right clicking in refresh button when the browser is in inspect mode And Empty cache and hard reload it

this solves the problem for me
