### ISSUE TITLE
Retry button missing for older transactions

### ISSUE THREAD

**Issue by mryellow** [MetaMask/metamask-extension#3709]
https://github.com/MetaMask/metamask-extension/commit/d6e4d2e80d05f64bb543e524c6288b8b7c33e4c1#diff-7149b58ee444aa0d4fa440fe12f47a29

It would appear this change from `time` to `submittedTime` has broken retry button on existing transactions. New transactions appear as intended however the button will not appear for older ones, leaving them broken.

This combined with the new approach of favouring internal nonce over dApp provided one means that MEW can not be used to cancel these transactions with a duplicate nonce.

This leaves blocker transactions which may never be confirmed and can not be rejected, effectively locking the account.

**Comment by mryellow** [comment]
Unless this was a breaking update with appropriate warning think this deserves a hotfix to re-insert the needed `time` field. Any change to field names in a system like this should be done in a backwards compatible way, existing fields remaining while new ones with new names are added. People in this situation are stuck relying on official re-release.

`submittedTime` should only be used if it is in-fact set.

**Comment by mryellow** [comment]
Work-around:

* Leave MetaMask installed
* Disable MetaMask
* Build `v4.1.3` from source and install
* Use MEW to cancel transactions with nonce method
* Disable/Uninstall `v4.1.3`
* Re-enable official release.

**Comment by danfinlay** [comment]
Needs a migration to update these transactions.
