### ISSUE TITLE
[ShowStopper] - DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'metamask-config' exceeded the quota.

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#3714]
Fatal Error - I cannot load metamask and use it
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior - **load metamask**
  *  Actual Behavior - **WhiteScreen** - can't do anything with metamask
  *  Browser Used - Chrome 65
  *  Operating System Used MacOSX

  Screenshots are very helpful and will expedite your issue being resolved!
When I inspect background.html here is what I see:

```

DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'metamask-config' exceeded the quota.
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1031303)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1027213)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:3266
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087652)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087440)
    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087831)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390856)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390952
```
<img width="1601" alt="screen shot 2018-03-24 at 11 15 46 am" src="https://user-images.githubusercontent.com/9360827/37867400-015f8dd0-2f55-11e8-94d1-272395e1d1ab.png">

Seems like I have exceeded localStorage limits
Clearing localStorage didn't help - what should I do?

**Comment by lazaridiscom** [comment]
@rstormsf , this here should be related: https://github.com/MetaMask/metamask-extension/issues/3706#issuecomment-375835556

**Comment by rstormsf** [comment]
@lazaridiscom indeed. same error. I'm curious how to fix it without reinstallation

**Comment by rstormsf** [comment]
seems like I have to reinstall, re-import all my keys :-( not a great UX

**Comment by lazaridiscom** [comment]
the alternative is to wait till the fix (this should have priority, so it will happen the next days I guess)

**Comment by rstormsf** [comment]
also I noticed in TransactionController I had around ~ 300 transactions stored there

**Comment by rstormsf** [comment]
what doesn't make sense to me - is that clearing cache didn't help. emptying  localStorage

**Comment by lazaridiscom** [comment]
@rstormsf , try this one (I did not verify on my side) :

go

chrome://settings/siteData?search=cookies

locate any entries with "Local Storage"

Delete them.

**Comment by rstormsf** [comment]
tried....didn't work

**Comment by digitalassetjunkie** [comment]
I cleared all cookies and verified my extensions are safe. Metamask Still not working

**Comment by lazaridiscom** [comment]
folks, i guess you have to wait for the official fix...

**Comment by digitalassetjunkie** [comment]
I reinstalled. All good now!

**Comment by lazaridiscom** [comment]
@rstormsf , you could close this issue as a "duplicate of #3706".

**Comment by rstormsf** [comment]
@lazaridiscom done. Where should I wait for guide on how to fix it?

**Comment by lazaridiscom** [comment]
@rstormsf , follow-up: #3706

**Comment by danfinlay** [comment]
## The workaround until this bug is fixed

As explained [here](https://github.com/MetaMask/metamask-extension/issues/3706#issuecomment-375835556).

Uninstall & Reinstall MetaMask.

Closing as a duplicate of #3706.

**Comment by danfinlay** [comment]
Copied from #3706:

We are currently writing a hot-fix. Sorry for not responding over the weekend.

If you have a MetaMask with this problem, you can just leave it alone for a day or two, and the hotfix should fix this.

If you need to rush, if you have your seed phrase, you can uninstall & reinstall.

If you need to rush and don't have your seed phrase, you need to figure out how to get your vault data out of the extension's storage.local storage area. We don't have a guide on this yet.

**Comment by rstormsf** [comment]
@danfinlay thank you for your answer.
I'll wait for a fix.
I do have backups, etc. I'm just a bit lazzy to do the reinstallation :-) 
Cheers!

**Comment by ninja765** [comment]
I have same issue.
I tried update ver4.4.0  clicked update extensions now button.
But can't update from ver4.3.0 to ver4.4.0.
What should I do to solve?

**Comment by godwin-l** [comment]
When the browser reaches the maximum limit of local storage it will show those errors
Empty cache and hard reload it
Right clicking in refresh button when the browser is in inspect mode And Empty cache and hard reload it

this solves the problem for me

**Comment by bidhan-in** [comment]
- [ ]

**Comment by bidhan-in** [comment]
- [ ] ty56y
