### ISSUE TITLE
restore from seed phrase  just gave me an empty wallet 

### ISSUE THREAD

**Issue by Sharehearts** [MetaMask/metamask-extension#3715]
today I simply restore the wallet by fill in my 12phrase in order to change password.  restore from seed phrase . but by doing so ,  I got my whole tokens voided and it shows zero all the way down .      if  I have my private key seemingly I can import a former address back in.  but since I neglected , 12phrase is the only I've got .   I try connect from MyEtherWallet typing in Mnemonic phrase(12phrase) but it only shows those addresses that is created after I restored the wallet .         
 what can I do to fix this ? and it is too cruel if  I loose all tokens that I worked hard to get over just a password change .  
![tokens](https://user-images.githubusercontent.com/37304975/37870385-e33a7778-300f-11e8-9e99-c32509b664ca.JPG)
![oo](https://user-images.githubusercontent.com/37304975/37870394-21cf0bfc-3010-11e8-8cc2-7d70c3931890.JPG)

**Comment by jrmoreau** [comment]
We can run you though some troubleshooting steps in a private support convo here: support@metamask.io
