### ISSUE TITLE
Metamask is not initiating (opening up) when I click on the foz icon on the Crome browser.

### ISSUE THREAD

**Issue by race2jannah** [MetaMask/metamask-extension#3717]

**Comment by race2jannah** [comment]
When I click on the fox icon, a rectangular blank shape opens.  No icon is there, no writing, no graphs.  It is just a blank.  I'm unable to view my tokens sent to me by an ICO.  Also can't use with Myetherwallet to trade.

**Comment by race2jannah** [comment]
Well, mixed feelings now.  Glad it wasn't my computer that was hacked but now I have to wonder if this problem is much bigger than I thought.  Please keep in touch and let me know if they fix your metamask app.

________________________________

**Comment by TommyShelby9** [comment]
I have the same problem

**Comment by lazaridiscom** [comment]
Find some information here: https://github.com/MetaMask/metamask-extension/issues/3706#issuecomment-375835556

**Comment by lazaridiscom** [comment]
@race2jannah , you could close this issue as a "duplicate of #3706".

**Comment by juanKba** [comment]
I have the same problem

**Comment by jrmoreau** [comment]
Duplicate of  #3706. Closing
