### ISSUE TITLE
[RFC] Provide A Terminology Document

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3720]
affects #3679 

<hr/>

## Goals (Prioritized List)

* Exceptional Security (Coins, Tokens etc.)
* Exceptional UX (User Experience)
* Exceptional DX (Developer Experience)

## Resulting Requirements (Prioritized)

* Align to Known Terminology/Constructs (e.g. Standard Banking, IT)
* Use Direct Naming (Avoid Mental Indirections)
* Align to Common Crypto-Domain Terminology

## Draft

Term | Description
-- | --
**Private Key** | The private part of a Cryptographic Key. This holds the value.
**Public Key** | The public part of a Cryptographic Key
**Key Pair** | Cryptographic Key Pair (public and private key)
**Address** | A public key, used to send/receive assets (coins etc.)
**Address** | Short Form of a public key,  used to send/receive assets (coins etc.)
**Account** | Holds many addresses
**Wallet** | Holds many Accounts
**Vault** | Holds many Wallets
-- | **Pass Mechanisms**
 **Entity** | Cryptographic Entity like: Account, Address, Wallet, Vault
**Pass Word** | A word which allow to pass (The Classical Password)
**Pass Phrase** | A grammatically correct sentence, which allows to pass
**Seed Phrase** | A grammatically correct sentence, which represents a cryptographic entity
**Seed Words** | A sequence of words which represents a cryptographic entity
**<Entity> Seed** | A Seed which represents/restores the cryptograpic <Entity>
**Secret** | Denotes something that should be kept secret (private)
-- | **Ethereum Specific**
**Wallet Contract** | A wallet, implement as a contract
-- | --
**Avoid** | **Suggested Replacement**
**keyring** | use: Wallet, see #3738
**DEN** | use: Vault

## Resources

* https://myetherwallet.github.io/knowledge-base/getting-started/ethereum-glossary.html
* https://blog.trezor.io/wallet-accounts-and-addresses-bdfa6b66b037

<hr/>

**!This Issue-Text is Permanently Revised!**

**Comment by danfinlay** [comment]
I think myetherwallet did a good job starting a glossary of terms here:
https://myetherwallet.github.io/knowledge-base/getting-started/ethereum-glossary.html

**Comment by lazaridiscom** [comment]
Additional Resource with Diagram:
https://blog.trezor.io/wallet-accounts-and-addresses-bdfa6b66b037

**Comment by lazaridiscom** [comment]
@danfinlay , closing, as I'm moving this over to the sub-project (https://github.com/lazaridiscom/mm-vault). Will add/evolve a document there, which can be then review as a whole (with the sub-module).
