### ISSUE TITLE
reset chrome meta mask account

### ISSUE THREAD

**Issue by keithofaptos** [MetaMask/metamask-extension#3761]
reset chrome extention beta meta mask account.
i put seed words in ,it brought up my Account 1, that was good.
my question is, where are my other 15 accounts ?

**Comment by tmashuang** [comment]
Are the accounts different when you add new accounts?

**Comment by keithofaptos** [comment]
No 
Other than I’m have to re- add all of them .
Fortunately I copied the addresses and keys !
1 copied incorrectly so I’m blaming myself. But I’m pissed because it was on meta. And I expected the whole accounting bunch to reload.
And the fact that it didn’t SUCKS.
Why didn’t reload all of the accounts?

**Comment by keithofaptos** [comment]
Some coins load back in with add tokens.why do some not reload, or show up later?

And how do I delete an account in the list?

Is there a max number of accounts mask will hold?

**Comment by keithofaptos** [comment]
???

**Comment by danfinlay** [comment]
Sorry for the slow response!

There is not a max number accounts, you should be able to re-generate all of your accounts after restoring by clicking "Add Account" in the top-right account menu.

Please send any usage questions to support@metamask.io, we mostly use github for tracking action items, not answering questions, so we can be slow to answer!

**Comment by 4real4life** [comment]
Hi there, exactly the same thing happened to me today. Have had to create up to 20 accounts with hope of retrieving the one that has my eth and tokens but no luck.Any hope of getting it back?

**Comment by keithofaptos** [comment]
Keys?
Import?

**Comment by 4real4life** [comment]
How do u mean by keys and import?, sorry but I don't get that

**Comment by 4real4life** [comment]
Oh sorry, I suppose u were't referring to me

**Comment by keithofaptos** [comment]
Did you save your metamask address with matching key , or 12 words?as a backup.
There software is in beta. I messed up and lost tokens and about 8 hrs of work.so I get it.
I had saved most keys. Copied a few down wrong too. That sucked. But the addresses I had keys for I got them back .

**Comment by 4real4life** [comment]
I only have keys and 12 words for the original address that I initially linked from myetherwallet when I first signed up.i then created another account on metamask where I then stored all my tokens and ether. The only account showing up now is just the original one but the account with all my tokens and ether can not be found. From the comments have seen so far I was meant to create more accounts after logging in to metamask again and the account with tokens should be available again but that is not the case.I will be so gutted if I can't get it back as :(

**Comment by 4real4life** [comment]
Did u contact metamask service support?, i mean did anyone try to help or is there any solution?

**Comment by keithofaptos** [comment]
I did. 
And it came down to the key or the 12 words.
Back up your info is the name of the crypto game.

**Comment by 4real4life** [comment]
yeah true but the key and phrase should give one access to every other accounts that were generated afterwards i should think?. Have only got the phrase for the one account but not for all other accounts that were generated afterwards. Am just feeling so frustrated

**Comment by keithofaptos** [comment]
i had thought the same damn things! but it don’t matter because like MEW  MM doesn’t hold your (our) keys.

we both learned a rough lesson. imagine you had 80 million valued tokens in those accounts. I did.(unvalued) :/

**Comment by 4real4life** [comment]
still can't get my head around it, i mean when u first get linked to metamask you are reminded to save the phrases and keys but that's not the case when a new account is generated afterwards. The accounts just get generated and that's it. To be honest i have cried today

**Comment by 4real4life** [comment]
Oh well i guess it;s what it is. Life goes on i suppose.Thanks for the chat mate,u take care

**Comment by keithofaptos** [comment]
i cried a little too. blamed MM.almost punched a wall. then realized it was totally my fault.
MM could build something into a json file that encrypts our each account info that can be decoded 
after you’ve signed in ,and or with 1 key or 12 word pass. but they haven’t.
And I think they absolutely would be doing every user a massive favor if they would.

FUCK! i feel you. and I’m sure we aren’t the only folk that have had this happen.
and it is huge !!

**Comment by danfinlay** [comment]
Believe me, we are working *very hard* to improve the *many ways* users confuse themselves every day. You aren't the only ones affected, and we aren't ignoring you. If you want a smoother experience, just wait, all of this takes time.

**Comment by keithofaptos** [comment]
Thank you very much for saying that! 

Light in the darkness.

**Comment by 4real4life** [comment]
i suppose the only choice we all have now is to wait,i dare not say a word to my mrs about this or else i will end up on the street.

**Comment by keithofaptos** [comment]
The devs have heard our conversation. That fix is coming, I’d bet on that.
 As for the Mrs. well buy her flowers and keep your mouth shut.We have to learn in order to get better at not messing up.
With tech the devil is in the details. Build in room for errors.
There’s nothing “wrong” with MM. it’s our lazy lack of assumptions. And these fine devs are going to fix this particular broken bridge.
