### ISSUE TITLE
META MASK IS NOT RECOGNIZING MY PASSWORD!

### ISSUE THREAD

**Issue by Professor-Curtis** [MetaMask/metamask-extension#3766]

**Comment by danfinlay** [comment]
Please send an email to support@metamask.io.

You'll want to include:
Have you kept your seed phrase safely backed up?

It may help to include some logs: https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by Professor-Curtis** [comment]
Don't close this case.  I do not have another 5 hours immediately
available to me to deal with this problem.  I will get back to you when I
have to devote to this issue.
