### ISSUE TITLE
On boot - transition all txs in weird states to failed

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3771]
anything stuck in "approved" or "signed" but not "submitted" "rejected" etc

should be moved to "failed"

**Comment by kumavis** [comment]
![image](https://user-images.githubusercontent.com/1474978/38015275-267a1108-3220-11e8-930b-ef3b1da3c919.png)

**Comment by frankiebee** [comment]
we already transition transactions in approved state to failed on boot i'll write a test for it

**Comment by bdresser** [comment]
relates to #3896

**Comment by frankiebee** [comment]
issue was fixed in #2988
