### ISSUE TITLE
Metamask Transaction Hashes on etherscan no found, unable to withdraw money back into MM from forkdelta.

### ISSUE THREAD

**Issue by Jmag31** [MetaMask/metamask-extension#3778]
0xB9Fed5199B29a76Ae9e4D468a87E7DbcD617a0dA is the public key. I have a situation that hasn't occurred before. I deposited 1.85 eth into ForkDelta wallet leaving .225 eth within my metamask wallet. I then proceeded to try and buy the lowest sell orders that I wanted to buy of a coin with plenty of gas.
Then I checked the ehterscan for the transactions and it said the hash couldnt be located
so I tried buying several more times and still nothing. Then I placed a buy order at the same price and amount and the lowest sell order which should make a match and exectute the contract, but it wont. Then everytime I attempt to cancel the order of about .9 eth with 30 or so gwei for gas, it still does nothing. Etherscan says it cant locate the hash. Iv tried canceling at least 10 times. Finally, I cant withdraw my eth from ForkDelta back into my Metamask wallet at all either as everytime I execute the contract, etherscan give me the same message that it is unable to locate this transaction hash. I have 1.85 eth stuck right now on Forkdelta that I cannot spend, send anywhere else, or withdraw, same message given to me for every contract I execute on etherscan. I emailed MM support and they told me to download state logs and send in, but when I click on download state logs, nothin at all happens. Here are alot of screenshots. Need help. Thanks!
![fd eth](https://user-images.githubusercontent.com/37879581/38048671-9b7b2c38-328b-11e8-8961-e16f42aae3c1.PNG)
![fd order](https://user-images.githubusercontent.com/37879581/38048672-9b8f7ac6-328b-11e8-8595-0820db192c39.PNG)
![fd](https://user-images.githubusercontent.com/37879581/38048673-9ba927be-328b-11e8-9d4e-72d58296593e.PNG)
![fd3](https://user-images.githubusercontent.com/37879581/38048674-9bbc5da2-328b-11e8-842f-8e037d2c9dab.PNG)
![fd4](https://user-images.githubusercontent.com/37879581/38048675-9bd10220-328b-11e8-8bc5-f9ed37fe7be4.PNG)
![fd5](https://user-images.githubusercontent.com/37879581/38048676-9be3ae70-328b-11e8-9e1e-13a1d4f433ea.PNG)
![fd6](https://user-images.githubusercontent.com/37879581/38048677-9c04586e-328b-11e8-9c2d-204b11ebcbd1.PNG)
![fd7](https://user-images.githubusercontent.com/37879581/38048678-9c145200-328b-11e8-9bb2-f8539026b7e8.PNG)
![fork](https://user-images.githubusercontent.com/37879581/38048679-9c27e40a-328b-11e8-8a11-a70bbf8a274a.PNG)
![mm total](https://user-images.githubusercontent.com/37879581/38048781-f97c9a06-328b-11e8-840a-ff52022029d0.PNG)

**Comment by danfinlay** [comment]
Sorry for the slow reply:

My guess is that your "next transaction" (by nonce number, lowest first) was the one with a low gas price, blocking the rest of your transactions from being mined. I would recommend increasing the gas price on that (lowest numbered but stuck) one.

Please be aware that by repeatedly trying to send transactions, you have "queued up" all of these transactions to be processed as soon as the earliest (blocking) transaction is mined.

Resetting the account could result in a ghost account, so this could be dangerous:
https://metamask.helpscoutdocs.com/article/37-ghost-accounts-ether-sending-away-whenever-funding-an-account

If you did decide you wanted a fresh start, and were willing to take that risk, you can reset your account like this:
![reset account](https://camo.githubusercontent.com/0110d30052ad5224a90fba102c39a60765e07966/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c3470543834596e5a744f5447787741672f67697068792e676966)

If you have any other questions about using MetaMask, please email support@metamask.io
