### ISSUE TITLE
Metamask does not connect to any networks

### ISSUE THREAD

**Issue by nugrohodanangs** [MetaMask/metamask-extension#3802]
Hi, 

I just cannot login into metamask, it just happened by today previously was fine.  the loading keeps spinning and never resolve.
Below the screen shot of the metamask and its error that I got. I still can surf into another sites.

![image](https://user-images.githubusercontent.com/6951921/38143299-6e308564-3472-11e8-8260-43395cb6c76d.png)

![image](https://user-images.githubusercontent.com/6951921/38143319-80749c2e-3472-11e8-91de-23be7fab080e.png)

Could you please help me with this matter.

Thanks,

**Comment by danfinlay** [comment]
Are you behind a firewall or VPN?

Infura is working for most users, so the most likely cause is a local networking issue.

If you click the `Network` tab of the background inspector, you should be able to click a failed (red) request, and see more details. Is there any more detail than a timeout?

Lastly, sometimes people have luck switching the network (in the top left menu) to another one and back again. This can reset our connection, and so it can be worth trying.

**Comment by danfinlay** [comment]
Please email support@metamask.io for user support questions, closing this so it doesn't clutter up our development backlog.
