### ISSUE TITLE
Onboarding: Verify seed phrase styling issues in extension view

### ISSUE THREAD

**Issue by alextsg** [MetaMask/metamask-extension#3804]
Font size is too big, and when clicking the words to add to the textarea, the expanding textarea moves the entire screen.

**Comment by danjm** [comment]
@alextsg Is this still an issue?

**Comment by alextsg** [comment]
Yes. I haven't made changes to that view yet.

**Comment by alextsg** [comment]
Punting as it's not a priority right now
