### ISSUE TITLE
How can I access my previous account/wallet?

### ISSUE THREAD

**Issue by rolix7** [MetaMask/metamask-extension#3807]
A few months ago, I made a new wallet, let's call it "wallet 2", and restored it in MetaMask. Today I was trying to access it, but none of my passwords worked. After a few unsuccessful tries I decided to restore my jaxx wallet (wallet 1), because I wasn't sure, if I already moved everything from wallet 2 to wallet 1. This wasn't the case and my problem now is, that I don't have the seed phrase of wallet 2 (never wrote it down, dumb me) and can't try some other passwords, because I restored another wallet in the meantime.

Can I somehow "reset" MetaMask to the state, before I restored wallet 1, so I can access wallet 2 with the right password?

**Comment by lazaridiscom** [comment]
> Can I somehow "reset" MetaMask to the state, before I restored wallet 1, so I can access wallet 2 with the right password?

The only way I see would be a classis "data backup", which would contain the state of your browser and thus your wallet 2. You would still need the password.

Other than that: no, you can't restore wallet2, as it was erased when you restored wallet 1.

**Comment by rolix7** [comment]
Thanks for your fast response. Which files do I have to restore? I am using the chrome extension on windows.

**Comment by lazaridiscom** [comment]
> Which files do I have to restore?

Not sure if this is documented / supported. You can try this info here:

https://superuser.com/questions/507536/where-does-google-chrome-save-localstorage-from-extensions

**Comment by alacrity26** [comment]
@rolix7 for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by martineezz** [comment]
@rkieslinger If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
