### ISSUE TITLE
Can't open metamask and can't update from version4.3.0 to version4.4.0.

### ISSUE THREAD

**Issue by ninja765** [MetaMask/metamask-extension#3813]
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used　Google Chrome  version 65.0.3325.181（Official Build）64bit
  *  Operating System Used　windows 10 home version 1709

I have same issue #3719.
I tried update version4.4.0 clicked update extensions now button.
But can't update from version4.3.0 to version4.4.0.
I don't have wallet seed.
What should I do to solve?
![default](https://user-images.githubusercontent.com/37945488/38159656-e2eb22f4-34e7-11e8-9d5e-173762d47727.png)
![2](https://user-images.githubusercontent.com/37945488/38159658-e5052440-34e7-11e8-8e65-fb168a6f9d78.png)

**Comment by lazaridiscom** [comment]
> I tried update version4.4.0 clicked update extensions now button.
> But can't update from version4.3.0 to version4.4.0.

I can confirm this, on my chrome "update extension now" did not work, too.

You have to wait until some core-dev responds (could be on Monday)

**Comment by alacrity26** [comment]
#3881 
@ninja765 Have you tried restarting your browser? If you have your seed phrase backed up, you can probably work around this by uninstalling, reinstalling, and restoring from your seed phrase.
 
If you'd like us to figure out exactly what has gone wrong for you, you should send us your logs to support@metamask.io
 
Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
