### ISSUE TITLE
import account form geth cosole to metamask (private blockchain)

### ISSUE THREAD

**Issue by eaknoppanut** [MetaMask/metamask-extension#3815]
I want to import account form geth console(private network) but i can't ,i have UTC file when i create account with geth but when i open file and copy mac and paste to metamask (private key) account not match between geth and metamask.

pls help me, i want to use account form geth  to metamask

**Comment by alacrity26** [comment]
@eaknoppanut for future/user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
