### ISSUE TITLE
hi, my metamask window has suddenly gone blank in chrome extension

### ISSUE THREAD

**Issue by SoccerCoins** [MetaMask/metamask-extension#3818]
Hi,

I have tried to solve by using the boards and general googling but I seem to have hit a stumbling block and cant progress to resolution, of course I cant find my seed words either....

Here are the error logs if someone can advise and help me decrypt my problem I would appreciate it, thanks in advance, I also checked if I have latest chorme version which it says I do:

DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'metamask-config' exceeded the quota.
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1031303)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1027213)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:3266
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087652)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087440)
    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087831)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390856)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390952

**Comment by lazaridiscom** [comment]
Please try this: https://github.com/MetaMask/metamask-extension/issues/3772#issuecomment-377601225

**Comment by usirld** [comment]
I'm showing the same message in console as SoccerCoins.  My Metamask version on Chrome is currently 4.3 but it is not allowing me to update to version 4.4.  I know my ether address and metamask password, but I've misplaced my seed phrase so I'll need metamask to operate properly in order to access my ether.

Any help/guidance would be much appreciated.

**Comment by SoccerCoins** [comment]
Hi, I also cant upgrade my version from 4.3.0

**Comment by alacrity26** [comment]
@SoccerCoins @usirld Have you tried restarting your browser? If you have your seed phrase backed up, you can probably work around this by uninstalling, reinstalling, and restoring from your seed phrase.

If you'd like us to figure out exactly what has gone wrong for you, you should send us your logs to support@metamask.io

Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
