### ISSUE TITLE
how the hell do you get on the website and open it up??? I'm just going round in circles

### ISSUE THREAD

**Issue by keithym10** [MetaMask/metamask-extension#3820]

**Comment by lazaridiscom** [comment]
@keithym10 , 

* which website?
* what do you mean by "open it up"?

**Comment by keithym10** [comment]
OK....obviously I'm wasting my time here?? I assumed the contact given me
was for Metamask....??

Clearly the incorrect contact details are given on their website....I'll
get it sorted?

**Comment by jrmoreau** [comment]
you can create a ticket by emailing support@metamask.io and someone will get back to you on Monday.
