### ISSUE TITLE
Just downloaded Metamask and will not open

### ISSUE THREAD

**Issue by bjd4260** [MetaMask/metamask-extension#3821]

**Comment by jensdj2002** [comment]
Same issue, downloaded Metamask, getting the message "added to Chrome" but cannot navigate any further

**Comment by alacrity26** [comment]
@bjd4260 @jensdj2002 for user issues, please send a ticket to support@metamask.io. Kindly include snapshots of the issue you face on MetaMask, as well as your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
