### ISSUE TITLE
Metamask don't work

### ISSUE THREAD

**Issue by timofeyivanov** [MetaMask/metamask-extension#3823]
Hello Metamask doesn't open. I work with it before, and now if try to open i saw wight list?
<img width="1328" alt="2018-04-02 18 02 23" src="https://user-images.githubusercontent.com/38009572/38201337-a2f5afce-36a0-11e8-8a59-b00ac70f60c1.png">

**Comment by boumanb** [comment]
Hi,

Can you take a look in your console (Press F12 and click console)  after opening metamask?
If you see any errors, please post them here.

**Comment by alacrity26** [comment]
@timofeyivanov Have you tried restarting your browser? If you have your seed phrase backed up, you can probably work around this by uninstalling, reinstalling, and restoring from your seed phrase.

If you'd like us to figure out exactly what has gone wrong for you, you should send us your logs to support@metamask.io
