### ISSUE TITLE
Metamask Blank. Not working. F12 Screenshot

### ISSUE THREAD

**Issue by Buhboom** [MetaMask/metamask-extension#3836]
My metamask version is still on 4.3.0 and theres no button to update. 

These are the errors in the console

https://imgur.com/MRymMvd

https://i.imgur.com/9bBBgvP.png

**Comment by jrmoreau** [comment]
Have you tried putting your browser in developer mode and manually updating MetaMask?

**Comment by Buhboom** [comment]
Works now!
