### ISSUE TITLE
MetaMask not showing ETC balance

### ISSUE THREAD

**Issue by PavlinETC** [MetaMask/metamask-extension#3838]
MetaMask not showing balance

Hello,

MetaMask doesn't show my ETC balance for last several weeks. Instead of balance I see only three dots ...

Can you please help me?

**Comment by jrmoreau** [comment]
MetaMask is an Ethereum only tool and does not support Ethereum Classic (ETC) or Ethereum Classic tokens. You will need to use an Ethereum Classic supported solution for this.

**Comment by PavlinETC** [comment]
Please note I made a mistake, not MetaMask but ClassicMask. I use ClassicMask and I face issue with not showing balance. Can you please help?
