### ISSUE TITLE
Blank after entering the seed.

### ISSUE THREAD

**Issue by hgreenwood** [MetaMask/metamask-extension#3840]
Had metamask installed for a few months.

Today I noticed I cannot send tokens anymore. Confirmation was not possible. 

Than uninstalled. Installed the same extension again. Entered my seed. And then blank ...

  *  Browser Used: Chrome 65.0.3325.181 (Official Build) (64-bit)
  *  Operating System Used: Mac OS 10.13.3

Is the release from yesterday buggy?

<img width="359" alt="screen shot 2018-04-03 at 11 53 34" src="https://user-images.githubusercontent.com/38035742/38242911-48d1b1a0-3736-11e8-94a9-9b29011b7360.png">

**Comment by danfinlay** [comment]
This would probably be good to send to support@metamask.io. We have not seen this problem with anyone else yet. Please include a copy of your logs:

https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by danfinlay** [comment]
Was support able to help you here? Any update?

Closing until we get an update.
