### ISSUE TITLE
Error: chainId: 1 in txParams is not a string

### ISSUE THREAD

**Issue by adamson791** [MetaMask/metamask-extension#3842]
Getting following error. What does it mean and how do I fix?

Error: Error: chainId: 1 in txParams is not a string at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:246:3389 at Array.forEach () at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:246:3330) at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:246:2823) at t. (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:141:7541) at L (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:17730:4382) at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:17730:4170) at Generator.t.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:17730:4561) at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:531:350) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:531:454 at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:445:27853) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:445:60227 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:336:855 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:2363 at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:20595) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:5238 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:2363 at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:5514) at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:5436) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:5238

**Comment by Thkub001** [comment]
I'm facing the same issue. Anyone can help plese ?

**Comment by postnikov** [comment]
Same problem for me. Please help.

**Comment by adamson791** [comment]
Surely someone must have a solution?

**Comment by postnikov** [comment]
It worked for me in Firefox
So probably it's Chromes problem or Metamask for Chrome is not working correctly

**Comment by geeogi** [comment]
same issue here. Trying to finalise an ENS auction on MEW. Using Metamask on Chrome.

**Comment by ronbarbados** [comment]
same issue

**Comment by adamson791** [comment]
It worked in Firefox - thanks to postnikov for the solution!!

**Comment by jaggedsoft** [comment]
Same problem here, can't interact with smart contract or send tokens. This is happening from myEtherWallet and mycrypto.com

**Comment by adamson791** [comment]
Use mew in Firefox browser. Looks like there's an issue with chrome

**Comment by webcaetano** [comment]
This should be closed in favor of #3841
