### ISSUE TITLE
I used copy address to clipboard, sent ETH, realized clipboard gave a different address from mine

### ISSUE THREAD

**Issue by Miitcher1** [MetaMask/metamask-extension#3844]
So, I sent ETH in my Metamask address. I just used copy from clipboard, you know, the usual. 
Weird thing is I haven't received my ETH yet. 

So I checked, and I suddenly noticed how the address in my clipboard is different from my address in Etherscan. I lost my money basically. Is anyone else having similar issues?

I used Chrome, and W10.

**Comment by jrmoreau** [comment]
Can you send an email to support@metamask.io with proof/reproduction steps, please?
