### ISSUE TITLE
Chrome Extension Error MetaMask when sending ERC-20 Tokens

### ISSUE THREAD

**Issue by Cryptonicles** [MetaMask/metamask-extension#3847]
Having this error come up when sending ERC-20 tokens to another address.

I've got the necessary gas in ETH, it's about 50 cents.

But whenever I try to submit the transaction through meta, nothing resolves.

I am in no way a developer, but am looking for some layman asnwers as to why transaction will not go through.

I was given these coins by the creators in exchange for marketing services, we've already made transactions between these 2 wallets, anyone have an idea on what could have changed?

Feel free to email me solutions as well: alex@peakdemand.ca

Thank you Github community, much appreciated.

![screenshot 2018-04-03 13 40 32](https://user-images.githubusercontent.com/38049456/38267036-39b58de2-3748-11e8-8a81-f2c110f98161.png)

**Comment by tmashuang** [comment]
Closing in favor #3841.

**Comment by Cryptonicles** [comment]
Thanks Thomas


I’ll wait for MEW to update fix.


Alex Masters Lecky
416 844 0808
alex@peakdemand.ca<mailto:alex@peakdemand.ca>

www.Cryptonicles.com<http://www.Cryptonicles.com>
www.peakdemand.ca<http://www.peakdemand.ca>

With trillions of dollars hanging in the balance, this conversation is for everyone…
[cid:F11688ED-52AF-4403-A2F6-C77B719B55BE@hitronhub.home][cid:2ECF245C-EE83-4A99-86A9-C41C13D0BC3E@hitronhub.home]


*****NOTE: Please exercise caution when making any investment decisions. Whether rags or riches; your choices, and the resulting outcomes are your own. That is why education is important when navigating new financial landscapes. ALWAYS consult with a financial advisor or expert in the respective field if you need guidance. Financial prosperity should be available to everyone.



On Apr 3, 2018, at 2:10 PM, Thomas Huang <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #3847<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMetaMask%2Fmetamask-extension%2Fissues%2F3847&data=02%7C01%7C%7C2d1781bc68424271113b08d5998e2523%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636583758139296782&sdata=I6pRwdBnR3nchidbjbhdAjy9qoKzvM%2BXa%2BMlJtamq4o%3D&reserved=0>.
