### ISSUE TITLE
Error: chainId in txParams is not a Number. got: (0x3)

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3856]
https://sentry.io/metamask/metamask/issues/512760455/

```
Error: chainId in txParams is not a Number. got: (0x3)
  at None (app/scripts/lib/tx-state-manager.js:146:48)
  at Array.forEach (<anonymous>)
  at e.value (app/scripts/lib/tx-state-manager.js:141:27)
  at e.value (app/scripts/lib/tx-state-manager.js:111:12)
  at r.<anonymous> (app/scripts/controllers/transactions.js:92:27)
...
(3 additional frame(s) were not displayed)
```

**Comment by tveloq** [comment]
I'm having issues with both Myetherwallet and Ethereum Wallet while transferring ETH with Metamask with similar errors. The only way to make transactions work seems to be to manually add "0x" to the data field.

**Comment by frankiebee** [comment]
we dont use chainIds provided by the dapps nor do we persist the one we use on txParams i can fix it so we persist the one we use and throw away the  one the dapp provides

**Comment by kumavis** [comment]
will publish a fix tomorrow
