### ISSUE TITLE
Lost 1 account from multiple accounts

### ISSUE THREAD

**Issue by dzuncoi** [MetaMask/metamask-extension#3859]
I already had an account and used it normally on Chrome. 2 days ago I created another account and deposit some ETH into, but now this account has gone ???!!!! I don't see it in the list account when open Metamask on Chrome.
This is the address of lost account: `0xd21e416199aef4c4a95343446508498fb97806c9`
How can I get it back?

**Comment by holcoin** [comment]
find after createaccount  in metamask

**Comment by dzuncoi** [comment]
@holcoin I don't understand what you mean

**Comment by holcoin** [comment]
sorry..  my english is short.
if you added address in metamask. so you can find the address.
try by clicking CreateAccount in Top-left menus in metamask.

**Comment by alacrity26** [comment]
@dzuncoi for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
