### ISSUE TITLE
Restored from Seed Phrase gave me wrong wallet address

### ISSUE THREAD

**Issue by icewoii** [MetaMask/metamask-extension#3863]
Couple days ago, I wanted to use my existing MetaMask account on my new laptop so I signed out from Google Chrome and remove everything(app, extension, history) on my old laptop . On new laptop, I tried to restore Seed Phrases which I backed up from the old laptop but Metamask gave me a wrong address.

My old address is : 0x57244ad575dab2e8fb86372ec1aaa9dda9131ed7
But my restored account is : 0xD47E79d89F27dA103cA306Cb9778741f33B05E61 

Please help me to fix this. It's a serious issue. I have balance and tokens on that address.

Thank you.

**Comment by holcoin** [comment]
i  guess.  you backed wrong seed Phrases.

**Comment by jrmoreau** [comment]
Please submit a ticket for troubleshooting support@metamask.io
