### ISSUE TITLE
Metamask for Firefox lost all my data after sleep mode

### ISSUE THREAD

**Issue by abara-kedavra** [MetaMask/metamask-extension#3866]
Today I opened my laptop and saw what my Metamask (Firefox) lost my account. I restored from the seed phrase, but all my data (imported accounts and etc. was lost). But how it's possible? I did nothing, and all my data should store locally. Why Metamask can't restore?

**Comment by alacrity26** [comment]
@abara-kedavra for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

In the mean time, you could follow these steps to import your accounts:
​Importing accounts (Old UI): https://metamask.helpscoutdocs.com/article/19-importing-accounts
Importing accounts (New UI): https://metamask.helpscoutdocs.com/article/75-importing-accounts-new-ui 

Restoring MetaMask doesn't restore imported accounts. To understand why, please see: https://metamask.helpscoutdocs.com/article/52-what-is-an-imported-account
