### ISSUE TITLE
Address has ETH but then shows for contract transaction as empty

### ISSUE THREAD

**Issue by ErikAugust** [MetaMask/metamask-extension#3871]
I have an address with ETH on it - and I can send/receive ETH just fine in MetaMask. The balance updates.

However, when I call a contract function - MetaMask shows 0 ETH in the address.

Here's a screenshot of the address main screen (that shows in account):
https://s3.amazonaws.com/cacheassets/Screenshot+2018-04-04+10.01.33.png

Here's a screenshot of the transaction confirmation (that fails): 
https://s3.amazonaws.com/cacheassets/Screenshot+2018-04-03+14.30.19(2).png

**Comment by skilesare** [comment]
I'm seeing the same behavior when using a TestRPC.

**Comment by helplsasap** [comment]
@ErikAugust  i am having the same exact problem. I lost eth from many failed transactions because of gas. Did you find a solution to the problem? I am on the main ether network and it has never done this before. thank you
