### ISSUE TITLE
Using MetaMask for encryption/decryption

### ISSUE THREAD

**Issue by Qqwy** [MetaMask/metamask-extension#3872]
We would like to create an application that encrypts/decrypts small pieces of information (that themselves will be used as passphrases for some larger synchronious encryption/decryption scheme).

What would be the best way to do this using MetaMask? Is it at all possible, or does MetaMask currently really only expose the functionality to `sign`/`sendTransaction`?

**Comment by kumavis** [comment]
We currently only support signing and do not support encryption/decryption
more general key mgmt is on our roadmap

in the mean time take a look at https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

**Comment by danfinlay** [comment]
Closing as duplicate of #1190.
