### ISSUE TITLE
Is it safe to request many web3.eth.getAccounts() without flood the server

### ISSUE THREAD

**Issue by eduardonunesp** [MetaMask/metamask-extension#3873]
The `web3.eth.accounts[0]` should be removed on `WebJS 1.0`, and replaced by `web3.eth.getAccounts()`, but `web3.eth.getAccounts()` is an async function and `web3.eth.accounts` isn’t (at least looks like sync method) when comes to get the selected account from MetaMask.

My question is about the nature of the `async` call `getAccounts()`, does that is a harm to the Ethereum node, by the "DDOSing" the node ? or Metamask serves as kind of cache.

I tried here locally on my machine by setting up `ganache-cli` connected with MetaMask and imported the private key from `ganache-cli` creating an imported account, so in the browser, I created a page which does lots of requests to using the `web3.currentProvider` (which return MetaMask) to `web3.eth.getAccounts()`, it returned correctly and `ganache-cli` only a pooling of `8000ms` without flooding of `get_accounts`.

Looks like MetaMask doesn't forward that call to my local `ganache-cli`.

Could someone please do a good technical explanation about that?

**Comment by kumavis** [comment]
`eth_accounts` actually never hits the network, as they keys + addresses are stored locally. That said you likely don't need to do it more than 1/sec.

All rpc methods that relate to account management are handled internally by metamask and do not go to the node

**Comment by eduardonunesp** [comment]
@kumavis thanks for the answer, I'd use that method in my DApp to check if the user changed the accounts using the `web3.eth.getAccounts()`, so its safe to say that `100ms` checkings are ok to make sure that user changed the account
