### ISSUE TITLE
Can't send ETH to self/same address

### ISSUE THREAD

**Issue by JohnAllen** [MetaMask/metamask-extension#3874]
*  Expected Behavior: able to send tx to same account
  *  Actual Behavior red outline around `to` address
  *  Browser Used: `chrome 65.0.3325.162`
  *  Operating System Used: `macOS 10.13.3`

**Comment by kumavis** [comment]
@JohnAllen is this just for testing / debugging?
A user requested this be disallowed so they dont accidently waste money on fees
in general for real world uses its a mistake but maybe should allow with just a warning

**Comment by kumavis** [comment]
@danjm this may be a feature not a bug - not sure about new-ui

**Comment by JohnAllen** [comment]
you can cancel pending txs for the account by sending 0 ETH to yourself, so in that sense it is a feature.

**Comment by EddieOne** [comment]
Maybe need a warning though, since it's easy to do by mistake as well. Waiting for it to confirm, only to realize it was sent to same address.
