### ISSUE TITLE
"Reprice" TX UI Feedback

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3885]
If a retry/reprice/speed up tx is rejected, what's the reason behind showing the rejected event in the TX history? I believe the rejected event isn't important enough to show in the history (other tx events are more important like displaying incoming transactions). I would compare it to opening up a new text file and closing it without ever saving it. I don't need to see somewhere that I've thrown something away. I consider login and sign requests generated by a smart contract to be important to display in the tx history, but not user generated tx's.

Also some UI feedback on the "reprice" screen. I think we can reduce the overall height of data fields which would give us more vertical area to display the total cost of transaction (tx + gas price). Also wondering if we just show the total value up at the top since it's the most important piece of data @kumavis? 

![image](https://user-images.githubusercontent.com/597770/38342040-aa4bfa58-3830-11e8-9e69-b6a7a741e466.png)

**Comment by kumavis** [comment]
>  I believe the rejected event isn't important enough to show in the history

makes sense, i agree

**Comment by alacrity26** [comment]
@kumavis the last point is interesting. I wonder if we could throw it to users and ask what they think, or test/observe it without asking.

**Comment by cjeria** [comment]
I agree with @alacrity26. Will be conducting user tests very soon.

**Comment by cjeria** [comment]
Latest option for showing all vital transaction data above the fold (no need to scroll).
![artboard](https://user-images.githubusercontent.com/597770/40194792-712ce91a-59c0-11e8-9cbe-83c2c7e413c5.png)

**Comment by thjnhcolag** [comment]
#4724
