### ISSUE TITLE
Metamask shows an infinite spinner to connect to local host 8545

### ISSUE THREAD

**Issue by galladivya** [MetaMask/metamask-extension#3889]
Expected Behavior:
Want to run a DApp on chrome so I installed Metamask Plugin to chrome.I started with basic DApp-Voting Tutorial which shows total no.of votes gained by a person.
Actual Behavior:
Metamask shows infinite spinner if selected a localhost:8545.
Browser Used:
Chrome
Operating System Used:
MacOSX 10.13.1

**Comment by lazaridiscom** [comment]
possibly related to: https://github.com/MetaMask/metamask-extension/issues/3881#issuecomment-379010933

**Comment by bdresser** [comment]
thanks @galladivya. do you have an app running on that port? if not, the extension won't be able to find anything. 

worth noting that the small spinner in the top-right is still clickable, so you can switch away from the network when you need to. 

tracking work to make this interaction more intuitive in #3776
