### ISSUE TITLE
Cannot import JSON file

### ISSUE THREAD

**Issue by vporton** [MetaMask/metamask-extension#3893]
MetaMask 4.5.3 for both Chrome and Firefox on Linux has this bug:

When I try to import an account from a JSON keystore file, the following happens:

When I open the file chooser dialog, the MetaMask window is closed.

When I reopen the MetaMask window (by clicking MetaMask button) after choosing a JSON file, the window shows the current account, not the import dialog. So I am unable to finish the import.

**Comment by tmashuang** [comment]
This is a known issue that is block by the OS, https://github.com/MetaMask/metamask-extension/issues/1136. The alternative would be to open the extension in fullscreen tab by navigating to the extension URL in a new tab.

**Comment by ObiWanSatoshi** [comment]
@tmashuang can you elaborate on what exactly this work around is?

I don't understand where I find the "extension URL"?

Thanks!

**Comment by tmashuang** [comment]
The extension url/uuid can be found in the extension/addon list of browser. Chrome is chrome://extensions and Firefox about:addon. The workaround, that is described in the other linked issue, is to open the extension in expanded view. 
![2021_02_11_09_22_31_](https://user-images.githubusercontent.com/13376180/107673538-f5136200-6c4a-11eb-9905-b4c96f70498f.png)

**Comment by ObiWanSatoshi** [comment]
Thanks!

**Comment by Alinezami1** [comment]
Hi 
I have replaced my iphone and I do not have my 12 phrases. However I have got backup from my old Iphone before returning to Apple. Now my password does not open my metamask on new iphone. How can I use JSON file and where can I find JSON file on backup files?
