### ISSUE TITLE
Some messages are without translation even if it is in messages.json

### ISSUE THREAD

**Issue by gornov** [MetaMask/metamask-extension#3905]
Hello! I found few cases where I got messages without translation. Some of them are in messages.json but not used in code.

**Case**: When I log in on the main screen (ui/app/unlock.js)
Phrases which wasn't translated yet:
_"enter password_" - a placeholder in the input box
![metamask-00](https://user-images.githubusercontent.com/12135088/38397168-7872ada8-393c-11e8-84a8-de492f71c8f7.jpg)

**Case**: When I send Ether and see the first dialog box (ui/app/send-v2.js):
Phrases which wasn't translated yet:
"_From_:" - a label for an input box
"_Amount_:" - a label for an input box
![metamask-01](https://user-images.githubusercontent.com/12135088/38397219-d1930f2c-393c-11e8-98f7-b73702488900.jpg)

**Case**: When I have to confirm transaction (second dialog box, on the top of it, ui/app/components/pending-tx/confirm-send-ether.js)
Phrases which wasn't translated yet:
"_Edit_" - a link
"_Confirm_" - a header
"_Please review your transaction_." - a note
![metamask-02](https://user-images.githubusercontent.com/12135088/38397244-fd7698de-393c-11e8-9d22-434ca75c4baa.jpg)

**Case**: Settings, under the Current Conversion message (ui/app/settings.js)
Phrases which wasn't translated yet:
"_Updated_" - a word before updated date
![metamask-06](https://user-images.githubusercontent.com/12135088/38397322-5a064fe0-393d-11e8-9f4a-9f94d1b8fef2.jpg)

**Case**: Import account (mascara/src/app/first-time/import-account-screen.js)
Press Import button without private key and got message in English:
"_Private key does not satisfy the curve requirements (ie. it is invalid)_"
![metamask-03](https://user-images.githubusercontent.com/12135088/38397291-32c69250-393d-11e8-8125-5b8a4f4349f5.jpg)

Thanks.

**Comment by alacrity26** [comment]
@gornov would you like to comment/contribute on this at gitcoin: https://gitcoin.co/issue/MetaMask/metamask-extension/3534 ?

**Comment by bdresser** [comment]
thanks for finding @gornov! did you find any other instances of this in the extension?

**Comment by thjnhcolag** [comment]
[Gridcoin Colours.pdf](https://github.com/MetaMask/metamask-extension/files/2156090/Gridcoin.Colours.pdf)
