### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by Aceric1201** [MetaMask/metamask-extension#3910]

**Comment by Aceric1201** [comment]
Hi i clicked on the fox icon and only a white pop up, tried reinstalling and closing browser as well as restart computer but to no avail. please assist

**Comment by lazaridiscom** [comment]
> Hi i have the same issue i am current at version 4.5.5 and have attempted to reinstall but to no avail, still white screen

@Aceric1201 , could you please edit the title of your issue to "White Screen on version 4.5.5"?

An you can edit your original comment, too, and add your browser version and os.

**Comment by alacrity26** [comment]
@Aceric1201 Have you tried restarting your browser? If you have your seed phrase backed up, you may try work around this by uninstalling, reinstalling, and restoring from your seed phrase.

If you'd like us to figure out exactly what has gone wrong for you, you should send us your logs to support@metamask.io
