### ISSUE TITLE
Allow customizing gas recommendations

### ISSUE THREAD

**Issue by Snoogins** [MetaMask/metamask-extension#3912]
Metamask and I don't often agree on the recommended gas price for a given transaction.
Is it possible to add some settings so I can choose some defaults, that I can override manually if needed?
See attached image, and please add some suggestions if you have a work around.
Thank you.
![gas price limits](https://user-images.githubusercontent.com/378952/38429700-7161ad38-39bf-11e8-989c-bde9b261cd5d.jpg)

**Comment by Snoogins** [comment]
The reason for the low/high limits, is to protect me from my own mistypes, so exceeding these values would result in a warning.

**Comment by esmamma** [comment]
A manual default will be really convenient to users, they don't need to change the gas price in every transaction
And for the upper limit, I have just carelessly typed 101gwei for the gas price, so I will be really grateful if setting like that is available

**Comment by Snoogins** [comment]
This would be really useful, I don't understand why it doesn't get more traction.

**Comment by bdresser** [comment]
@cjeria what do you think?

**Comment by cjeria** [comment]
@Snoogins Is the desired feature that you're suggesting specific to GWEI or would you be happy with a selection much like the screenshot attached but for gas fee.

We've done a lot of thinking and designing around gas controls. Would like to understand you're use-case better.

**Comment by cjeria** [comment]
Here's one of our designs with the new segmented gas control 

![image](https://user-images.githubusercontent.com/597770/41558630-3dd05cce-72f6-11e8-8a6e-7c5497eea5b3.png)

**Comment by whymarrh** [comment]
@Snoogins @kthonenice how do you feel about the screenshots posted above/the current gas features available in MetaMask? Is there something more we can add? Should we close this issue?

@esmamma I think the manual default you're suggesting is implemented and part of an upcoming release

**Comment by kthonenice** [comment]
Can you show us the Advanced Options?
Looks good, but the suggestion was on custom GWEI though?

**Comment by d10r** [comment]
The initial suggestion was also about the possibility to set a default.  
That's something I also greatly miss, especially when interacting with sidechains like POA or ARTIS. 
UI wise, I'd suggest to add a field _Default Gas Price_ to the dialog which allows to configure a network 
(this one) 
![image](https://user-images.githubusercontent.com/5479136/60262294-1ee50d00-98de-11e9-9152-d5eeeeffce1c.png)

What makes a lack of such a setting even worse is that currently Metamask seems to ignore (or at least not taking as lower threshold) the value returned by `eth.gasPrice`. Meaning transactions with the gas price left at its default value (how that is chosen I didn't yet understand) may be rejected by the RPC server (if configured to do so) or just remain stuck in the mempool forever (if miners/validators have higher thresholds set). Both are outcomes which overwhelm non-technical users.

**Comment by bdresser** [comment]
From another user: 
> Basically it's annoying having to reduce the gas price for every tx. Just let me set my preferred gas price to safe-low, since I need to make many transactions and have to click extra buttons each time.

**Comment by d10r** [comment]
related to https://github.com/MetaMask/metamask-extension/issues/7142 because the broken error message makes it more difficult to understand for users why transactions fail.

**Comment by Gudahtt** [comment]
We should be using the `eth_gasPrice` returned from the network as our default gas price for all confirmations, as of v8.0.0. Is this satisfactory, or is a custom default gas still a desired feature? I don't know of any situations where that would be preferred over `eth_gasPrice`.

**Comment by d10r** [comment]
@Gudahtt for us that would be good enough.  
However I can't confirm that this is now the case. With v8.0.8 installed, I still get the gas price of the oracle for Ethereum mainnet proposed as default, no matter which network I'm connected to. Is there something I need to do in order to switch to the new behaviour?

**Comment by Gudahtt** [comment]
@d10r Good question - sorry I should have clarified this in my earlier comment. The default gas prices should be set using `eth_gasPrice` as of v8.0.0, but unfortunately it still shows the mainnet-based prices in the UI on v8.0.8. This was fixed in v8.0.9 but that release hasn't been shipped on Chrome yet - it's just on Firefox.

The mainnet prices will be hidden on non-mainnet networks in the next release, which should be in a week or two.

**Comment by d10r** [comment]
unfortunately, I still can observe the old behavior on v8.0.10.
Can you point me to the code? Maybe I can spot something which explains why it's not working (for me).

**Comment by Gudahtt** [comment]
Unfortunately the code is spread across a few different places. Could you give a specific example of what you're seeing, where, and in what circumstances? e.g. what network are you on, and what action were you taking at the time? Screenshots would be fantastic as well!

We show gas prices during the "send" flow, on the confirmation screen, and on the gas speed up modal and sidebar. I could point out where the related code for each is.

**Comment by d10r** [comment]
You asked for screenshots, you'll get screenshots :-)

Example dialog to do a transfer on xdai chain with the default gas price it comes up with:

![image](https://user-images.githubusercontent.com/5479136/99131525-b18d6580-2613-11eb-916a-bd69e7044fd8.png)

ethgasstation at the same time:

![image](https://user-images.githubusercontent.com/5479136/99131577-d386e800-2613-11eb-894a-af2202c472bc.png)

network settings:

![image](https://user-images.githubusercontent.com/5479136/99131411-5eb3ae00-2613-11eb-89dc-6226bab57263.png)

gas settings:

![image](https://user-images.githubusercontent.com/5479136/99131443-6ffcba80-2613-11eb-86e2-43a4457afacc.png)

version:

![image](https://user-images.githubusercontent.com/5479136/99131456-79862280-2613-11eb-9f3c-895be75b6c8d.png)

**Comment by Gudahtt** [comment]
Thanks @d10r - I'll double-check that we're not using the ETH Gas Station prices on that screen.

Are you sure that that wasn't the result of an `eth_gasPrice` call on XDAI at the time though? The similarity may have been a coincidence.

**Comment by Gudahtt** [comment]
Thanks again @d10r - I'm still investigating how to best solve this, but I've created #10003 to track the issue you ran into.

I'm going to close this in the meantime, as I think we've adequately addressed this suggestion for the time being, aside from this bug you found. I don't doubt there are still good reasons to allow further customization of default gas prices, but my guess is that a _better_ default will satisfy most users. IWe'd need more information about what problems further customization would solve before we give it serious consideration again.
