### ISSUE TITLE
Error: intrinsic gas too low

### ISSUE THREAD

**Issue by abitrolly** [MetaMask/metamask-extension#3923]
I tried to send some ETH to non-contract address with some data.

![image](https://user-images.githubusercontent.com/8781107/38442931-ac31c0a0-39f2-11e8-8226-176c6dcfec8b.png)

It failed with `Error: intrinsic gas too low`. From #3135 it looks like the gas limit was not enough to record data. Two issues here:

1. Can Metamask calculate the gas for the data automatically?
2. Can the error message be improved?

**Comment by abitrolly** [comment]
Sent [transaction](https://etherscan.io/tx/0xd23cc4670d41e4b98b2d992b1bb9820d7e633a9afc25122034fb7b73ba9fabac) with 1 byte data and it took 21068 gas. Is the storage fee 68 gas per byte?

**Comment by ShoaibIqbal452** [comment]
same issue, can't send any transaction, ' Error: intrinsic gas too low' when trying to transfer funds.

**Comment by abitrolly** [comment]
I think I reported the issue for 4.x already. Haven't used Metamask for a while. If there is a commit that touches these strings, then I guess it can be closed for now.

**Comment by Azghour-Saad** [comment]
Hi,


Same issue, can't deploy a smart contract in solidity ( IDE ) using MetaMask , `'Error: intrinsic gas too low'`   when trying to deploy my contract.


![issue](https://user-images.githubusercontent.com/33766249/105170827-d1626d80-5b1d-11eb-8edc-4378df1f1b1f.PNG)


Thanks in advance.

**Comment by Citarosoftwarerepairs** [comment]
I also have this problem in remix ethereum using solidity...

**Comment by ameshkin** [comment]
Having this issue as well. Increasing gas to high doesn't seem to help. I'm afraid of setting it even higher. I am putting some data in the data field, but not that much.

            {
              "op": "add",
              "path": "/err",
              "value": {
                "message": "Error: [ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32000,\"message\":\"intrinsic gas too low\"}}'",
                "stack": "Error: [ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32000,\"message\":\"intrinsic gas too low\"}}'\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:71:30653"
              },
              "note": "transactions:tx-state-manager#fail - add error",
              "timestamp": 1620733954687
            }

**Comment by SanderBel** [comment]
Could this be reopened please? Have the same issue, trying to send crypto with Metamask and always fails with the intrinsic gas too low message. @bdresser

**Comment by velhoti** [comment]
Also having this issue now but only on Firefox, I tried to increase the gas but do not work, in Chrome worked as expected, with relative low gas and no need to adjusts.

**Comment by dpazdan** [comment]
cc @velhoti https://github.com/MetaMask/metamask-extension/issues/11255
