### ISSUE TITLE
Should the topics for this repo also have other browsers that Metamask works with: Brave, Firefox, Opera

### ISSUE THREAD

**Issue by jamesray1** [MetaMask/metamask-extension#3926]

**Comment by lazaridiscom** [comment]
You're of course right, it should be more general.

@danfinlay 

>  🌐 🔌 metamask chrome extension https://metamask.io/

becomes

Ethereum Browser Extension - https://metamask.io

(and the other project descriptions should be revised, too. The most important 6 should be pinned)

**Comment by lazaridiscom** [comment]
fixed within  #3959, @jamesray1 , you can close this issue if you like.

**Comment by jamesray1** [comment]
I think you misunderstand me. I am referring to the topics for the repo.

![screenshot from 2018-04-15 15-02-11](https://user-images.githubusercontent.com/16969914/38775137-0c73f574-40be-11e8-9939-49fc7597afb0.png)

**Comment by lazaridiscom** [comment]
You're right. @danfinlay

**Comment by danfinlay** [comment]
Did I miss any?

![screen shot 2018-04-16 at 1 46 43 pm](https://user-images.githubusercontent.com/542863/38834219-9ec5696c-417c-11e8-94b1-7ad2c832cd0d.png)

**Comment by jamesray1** [comment]
Haha, looks like you covered them well!

**Comment by lazaridiscom** [comment]
@danfinlay , too well: should be kept to one line, e.g. remove: *-extension & firefox-addon.
