### ISSUE TITLE
Unable to reject transactions that is pending

### ISSUE THREAD

**Issue by vcube1** [MetaMask/metamask-extension#3927]
Due to some transaction error, I had to submit a transaction multiple times and eventually the very first transaction got executed that transferred my ETH to destination making my ETH balance low for other duplicate transactions. So the other duplicate transactions are showing as pending with error 'Insufficient balance for transaction'. I tried to REJECT these pending transactions, but it's not getting rejected. How do I kill these pending transactions? I think if I move any ETH to my account, then these transactions might get triggered which should not happen. 

Below are the screenshots. 

![del](https://user-images.githubusercontent.com/38161002/38456710-5cf42d10-3a4d-11e8-8c58-662584811556.JPG)

When I click on 'retry with higher gas here' for pending transaction it shows like this.

![image](https://user-images.githubusercontent.com/38161002/38456756-c0c7b53c-3a4d-11e8-93ef-77dce35cd8e0.png)

After pressing REJECT, it shows like this. 

![reject](https://user-images.githubusercontent.com/38161002/38456803-3c21fd00-3a4e-11e8-8981-dda7eb137739.JPG)

Please help me to kill this pending transactions! Appreciate your help!

**Comment by alacrity26** [comment]
For user issues, please send a ticket to support@metamask.io. Kindly include your snapshots and state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by grafx77** [comment]
It would be nice if you posted a resolution to this issue as this is an legit and ongoing problem with Metamask. I am having the exact same issue. Neither the Reject or Reset buttons work.
