### ISSUE TITLE
Transferring non-ETH tokens out of Meta mask 

### ISSUE THREAD

**Issue by keithofaptos** [MetaMask/metamask-extension#3928]
I wrote some tokens on the Erc20 blockchain, then transferred them to MEW ,then to
metamask thinking they'd be safer there. Now I need to transfer them .And I can't figure
out how to do this .In the "SEND" area on my chrome extention it says to only transfer ETH.
What do I do ? I'm stuck .

**Comment by alacrity26** [comment]
@keithofaptos Here's a snapshot of how you may do so with the new UI:
![20180409 mm kb 2ftix send token new ui](https://user-images.githubusercontent.com/17925120/38484599-b6899b0e-3c09-11e8-9a15-463d1cde31ec.jpg)

For other/future user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by helplsasap** [comment]
how do we do that? i need to do that
