### ISSUE TITLE
Metamask keeps resetting and asking for DEN

### ISSUE THREAD

**Issue by glints** [MetaMask/metamask-extension#3929]
In version 4.5.5 of the Chrome extension, Metamask keeps resetting on my Macbook Air. And even when I keep my browser open, often the next day, I can no longer access my Metamask and need to reimport my DEN and resubmit the warnings procedures. I mainly use Metamask with Idex, but that should be unrelated I guess. Only thing I know for sure that is changing is my IP address, every time I reconnect my WIFI; might this have an influence? Or do I need to grant special permissions in Chrome maybe? Chrome Version 65.0.3325.181 (Official build) (64-bits)

**Comment by glints** [comment]
Removed the extension and reinstalled and the problem seems to be solved.

**Comment by gangachris** [comment]
I'm on version 4.7.4, and this keeps happening.

**Comment by bdresser** [comment]
@gangachris tracking this issue in #3314. any further detail you can provide would be helpful!
