### ISSUE TITLE
 My Ether was turned out of my own

### ISSUE THREAD

**Issue by leonlee723** [MetaMask/metamask-extension#3936]
I buy 0.026614478 and turn in my wallet. But this ether  was turned out of my own to 0x2d7311279A3ba818Db2aD84eED09324A2577188A at once. I find records of 
 0x2d7311279A3ba818Db2aD84eED09324A2577188A all is "in" on etherscan.io. So I don't know what is happen. Who can help me? Thank you very much.

**Comment by danfinlay** [comment]
Please send an email to support@metamask.io for support.
