### ISSUE TITLE
Translate to Czech

### ISSUE THREAD

**Issue by espoem** [MetaMask/metamask-extension#3939]
Hi, I have seen that you have translations of MetaMask in several languages so I was wondering if you are interested in the Czech translation. If so, I can submit a PR immediately, it is prepared.

Followed the translating guide:
https://github.com/MetaMask/metamask-extension/blob/master/docs/translating-guide.md

**Comment by danfinlay** [comment]
We would be happy to accept a Czech translation, thank you for offering one!

**Comment by espoem** [comment]
I submitted the PR. If there is anything to change and adjust, let me know.
