### ISSUE TITLE
Can't customise gas limit in new UI

### ISSUE THREAD

**Issue by andytudhope** [MetaMask/metamask-extension#3942]
*  Expected Behavior
I am making a call to a contract that invokes another call which the estimateGas does not account for (when confirming bounties). Therefore, I want to customise the gasLimit to an amount I know will succeed and send the transaction.
  *  Actual Behavior
Customising the gasLimit and saving it does not work.
  *  Browser Used
Chrome 65.0.3325.181 
  *  Operating System Used
Mac OS

Here is how I set up the transaction:

<img width="353" alt="screen shot 2018-04-10 at 18 00 26" src="https://user-images.githubusercontent.com/13001517/38569132-cc3e7aa0-3cea-11e8-87e0-002635240d6c.png">

Here is the result:

https://etherscan.io/tx/0x7df2aba99e5be81a56d9058cb8759e2077213b38c35c05a1ac1a7f46e61924d1

**Comment by kumavis** [comment]
Also default / calculated gas is too low

**Comment by andytudhope** [comment]
FYI @kumavis: I uninstalled, re-installed and customised the gas again just trying to do a vanilla token send - seems to have worked well: https://etherscan.io/tx/0x9c9306630bb39007771514ebca051b26b6e1a75a69bfa426e37c184e31b680cf

I did notice that, in the new UI, SNT is not loaded as one of the auto options - is there a reason for that? Would be awesome to have it there, alongside ANT etc... 

Contract address: 0x744d70fdbe2ba4cf95131626614a1763df805b9e

**Comment by andytudhope** [comment]
And, another update on my latest woes with the new UI:

<img width="342" alt="screen shot 2018-04-20 at 15 04 05" src="https://user-images.githubusercontent.com/13001517/39052442-3eea7d9c-44ac-11e8-8b9e-650c6ac95b59.png">

I managed to send the transaction at the bottom of that list (linked in previous comment) but any further token sends from the same account fail. 

The first one failed outright and is listed as such.

The second one, listed as approved, caused the UI to hang indefinitely until I changed to another account and back. It then says approved, but is not clickable (neither is the failed one), and there is no matching tx out of the account on etherscan.

**Comment by scottydelta** [comment]
facing same issue as @andytudhope 

<img width="667" alt="screen shot 2018-04-23 at 8 47 24 pm" src="https://user-images.githubusercontent.com/2242189/39165098-95b3d276-4737-11e8-9e2f-39fe440d3eaa.png">

**Comment by frankiebee** [comment]
@andytudhope would you mind submitting a ticket to support@metamask.io  with your issue number on github and your state logs too so i can better debug your issue
https://metamask.helpscoutdocs.com/article/54-how-to-download-state-logs-new-ui

**Comment by frankiebee** [comment]
cc @scottydelta ^^

**Comment by passabilities** [comment]
I'm having a slightly different issue here #4508 

When I change the gas limit, it updates the gas fee but the total transaction cost does not get update.
