### ISSUE TITLE
Functionally organize background files

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3945]
We should organize our `app/scripts` folders and files to reflect the logical structure of the application. Right now it's messy, and definitely hard to reason about for a newcomer.

Prioritize grouping by functionality, instead of "file type". ie instead of "controllers vs libs", "lib" can continue to be "general reusable utilities", but otherwise our folder structure should start to reflect our state tree:

```
- app/scripts/controllers
  - transactions
    - index
    - nonce
    - gas-calculator
  - recent-blocks
  - keyrings
  - preferences
```

**Comment by lazaridiscom** [comment]
This would be a "senior grade redesign/architecture task".

Although, if you prefer so, it could be done in tiny steps in combination with documenting the source, see: https://github.com/MetaMask/metamask-extension/issues/3941#issuecomment-381788339

**Comment by danfinlay** [comment]
We made some file organization improvements, and should continue to do so. Further reorganizations and architecture tasks will be addressed in other issues.
