### ISSUE TITLE
Move account nicknames out of keyring controller

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3946]
This is an old mistake, we should clean it up. `account-nicknames` probably deserve their own controller for now, would be a good candidate for cloud-syncing.

**Comment by danjm** [comment]
A few introductory notes:
- the keyring controller is its own separate module/package: https://github.com/MetaMask/KeyringController/
- it is imported as `'eth-keyring-controller'` in three files in `metamask-extension/app/scripts/`
- "account nicknames" refer to the labels the user can attach to an account when adding a new account. See below gif for how to do this via the new ui:
![accountlabels](https://user-images.githubusercontent.com/7499938/38623392-2145b992-3d80-11e8-9e7a-d629b2b8429a.gif)
- note that the labels default to "Account #" where # auto-increments as new accounts are added, but that the nicknames can be manually set by the user

**Comment by whymarrh** [comment]
@danfinlay once we move the account nicknames somewhere else, did we want to remove that functionality from the KeyringController class altogether (i.e. major bump the `eth-keyring-controller` package)?

**Comment by lazaridiscom** [comment]
@danfinlay , keyring-controller is currently under redesign (mm-vault), so you should not interfere with the ongoing work by changing the code.

**Comment by whymarrh** [comment]
@lazaridiscom I think the idea here is more to move towards changes in MetaMask that will store the account nicknames outside of the KeyringController. I am leaning towards removing the functionality from the KeyringController altogether only to allow us to commit to an API and know what we're working with inside MM. I'm open to alternatives.

We'd be open to contributing the same changes (MetaMask/KeyringController#13) to the mm-vault redesign which would allow us to be able to use that as a replacement once its ready—thoughts?

**Comment by lazaridiscom** [comment]
@whymarrh , actually my stomach turns around when seeing the term "keyring", so I can't think now! Just go on, nothing can explode here anyway!!!
