### ISSUE TITLE
Add deprecation warning for network change page reload

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3951]
Need to communicate somehow (maybe a tweet or small blog post) that we will change reload behavior on network change.

**Comment by danfinlay** [comment]
Add a guide to detecting network change.

**Comment by danfinlay** [comment]
I started this blog post, and realized that if we deprecate this before we support subscriptions, it will mean asking devs to use polling, which is awful.

Instead, I am marking this issue blocked by web3 1.0 support, so we should first:
- [ ] merge #4047 
- [ ] Complete either #3642 or #3639.

**Comment by bdresser** [comment]
article published here: https://medium.com/metamask/breaking-change-no-longer-reloading-pages-on-network-change-4a3e1fd2f5e7
