### ISSUE TITLE
Stuck in Reveal Seed Mode

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#3955]
This is a pretty bad ux bug implemented, I'm stuck in reveal seed page, there's no way to exit this page unless I disable/enable the extension. 

![reveal seed bug](https://user-images.githubusercontent.com/597770/38596789-5efb882a-3d08-11e8-9cd6-cf747aea8c9a.gif)

See this issue for latest designs for this page https://github.com/MetaMask/metamask-extension/issues/3168

![image](https://user-images.githubusercontent.com/597770/38596854-d2926510-3d08-11e8-998d-6ff82f1cb44a.png)

**Comment by cjeria** [comment]
Correction: I'm perpetually stuck in reveal seedphrase mode even if I disable and enable the extension.

**Comment by danjm** [comment]
I've investigated this. There are root two problems:

1. We use the reveal seed words functionality from the 'first time flow'
2. There is no way to exit the reveal seed words screen in first time flow

In the old-ui, the reveal seed words screen allows you to click one button to return to the main screen. This is true whether in first time flow or not.

In the new ui, we want force the user to confirm their seed words when in the first time flow, but not when just revealing seed words after. Therefore, we need to give them a close button to leave the reveal seed words screen if they decide not to reveal. Currently we have no way of distinguishing whether the user is in first time flow or not when on this screen (and after the page refreshes).

So we need to do the following:

- [ ] Add a background property that indicates whether the user is in the first time flow, with appropriate getters and setters
- [ ] Ensure that property is correctly set and unset during the first time flow
- [ ] Add a close or cancel button to the reveal seed words screen when not in first time flow.
- [ ] Ensure that the seed words are removed from front and backend state when cancelling.
- [ ] Route the user to the main screen (and not the confirm seed words screen) when clicking next on the reveal seed words screen and in first time flow

(We might want to also remove the seed words within a `window.onbeforeunload` event when not in first time flow)

**Comment by alextsg** [comment]
We have an `isInitialized` property that gets set from `false` to `true` when the password has been created, but I think the name is better suited for completing the whole first time flow. Maybe we can instead add a property for password creation and use `isInitialized` for first time flow completion?
