### ISSUE TITLE
i have a missing account can somebody please help me?

### ISSUE THREAD

**Issue by kiwicrypto** [MetaMask/metamask-extension#3956]

**Comment by kiwicrypto** [comment]
i had 3 accounts in Meatmask and now i only have 2. 1 has gone and it is freaking me out a bit

**Comment by lazaridiscom** [comment]
@kiwicrypto , did you create the accounts, or did you import the keys? I assume created. Install metamask in another browser (or other machine), restore with you seed words, then "create account" twice, so you have in total 3 accounts (on the new machine). if luck, it should include the missing one.

**Comment by danfinlay** [comment]
@kiwicrypto if the above advice does not help, please email us at support@metamask.io
