### ISSUE TITLE
Missing Metamask Account

### ISSUE THREAD

**Issue by malabananNorm** [MetaMask/metamask-extension#3957]
Hello! Good Afternoon, I have Missing  my Account HOW can I bring it back ?How can I transfer my Tokens into Etherdelta without My Metamask..my  account has gone..Is Anyone can HELP me PLEASE...I need my Account back and so i can  transfer my tokens into Etheredelta..Thank you very much..Have a Lovely day!

**Comment by danfinlay** [comment]
Our support staff will contact you as soon as they are able to, if they haven't already.

**Comment by malabananNorm** [comment]
Hello Dan,
Good Afternoon,
Thank you for your time for replying my  support ticket  #3957
But wondering Why were #Closed? I haven't  recover until now
my Metamask Account..and no one contacting me yet..
I  Appreciate.. if you could able to help me to recover my
MetaMask account..don't know really what to do with it..I have
my Tokens on my account and I  wants to transfer on Etherdelta.
Help me Please..
Thank you very much!
Have a Wonderful day!
Norm

**Comment by danfinlay** [comment]
@malabananNorm I've looked into our support system, and I see that apparently we had an auto-reply sent to you, but you never replied, so the ticket was closed.

I have re-opened the ticket, and you will be contacted soon by one of our support staff. Sorry that you had to wait this long. If you aren't contacted within the day, go ahead and message again here.
