### ISSUE TITLE
[GITHUB] Cleanup Repo Descriptions, Pin Repos

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#3959]
The descriptions of the repositories should be verified and corrected, e.g.:

🌐 🔌 metamask chrome extension 

becomes: Ethereum Browser Extension

-

## Pinned Repositories
6 can be pinned, ordered, would be:

* metamask-extension
* provider-engine
* eth-keyring-controller
* ?
* ?
* faq

**Comment by danfinlay** [comment]
Revised my choice of top 6, and updated their descriptions:

![screen shot 2018-04-12 at 2 09 31 pm](https://user-images.githubusercontent.com/542863/38704444-31499da0-3e5b-11e8-8432-081581e7bc30.png)

Close if you think that answers your questions.

**Comment by lazaridiscom** [comment]
2 things:

* metamask-extension, i think it **must** mention "Ethereum", so it would be "Ethereum Browser Extension" or "The MetaMask Ethereum Browser Extension".

* Shouldn't KeyringController go to the 3rd position? If you had to keep 3 pins, whould it be in there?

**Comment by danfinlay** [comment]
Added Ethereum note & updated the order. I had missed how to reorder them on the first pass.
