### ISSUE TITLE
Blank screen for Custom RPC Transactions

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#3960]
VERSION:
`4.5.5`
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
Should behave the same as whitelisted networks: Kovan, Mainnet, etc
  *  Actual Behavior
Shows white screen
  *  Browser Used
Chrome `65.0.3325.181 (Official Build) (64-bit)`
  *  Operating System Used
Mac OSX

So why there is whitescreen metamask if I'm using Custom RPC URL? While if I use Kovan, it works fine.

![sdfmetamask](https://user-images.githubusercontent.com/9360827/38648649-36f17138-3da7-11e8-894b-6b71927cf8c5.gif)

## Steps to reproduce:
1. Setup Custom RPC URL in metamask:
`https://sokol.poa.network`
2. Fund your account via Faucet: https://faucet-sokol.herokuapp.com/
3. Go to Bridge UI Dapp: https://poanetwork.github.io/bridge-ui/#/
4. Send a Transaction like you see on the gif above (0.1 Sokol POA)
Result: Metamask shows Blank Screen
5. Switch to Kovan Network
6. Wait when your POA20 balance is shown(Bridge is relaying your POA to Kovan net)
7. Click Switch
8. Specify amount and click on Arrow left button
9. Verify the now metamask works as expected by showing non-white popup.

### Note
On OLD UI it works as expected

![2018-04-11 17 03 15](https://user-images.githubusercontent.com/9360827/38649281-7ebaec62-3daa-11e8-9c36-51160afe9f43.gif)

**Comment by bitpshr** [comment]
Thanks for the detailed report @rstormsf. Can you confirm this is still an issue? I can't reproduce the white screen bug on Chrome 66.0.3359.117 (the latest build as of this post) on OSX 10.13.4. I'd be happy to dig deeper if you can provide something reproducible. Thanks!

![MetaMask example](https://i.gyazo.com/5856c11dc0cddf3254806f4593d3d5d3.gif)

**Comment by rstormsf** [comment]
@bitpshr I can still reproduce it

![image](https://user-images.githubusercontent.com/9360827/39381983-d2297f56-4a18-11e8-9e4e-9ce84925484b.png)
