### ISSUE TITLE
Typo in action switch statement for reducer SET_CURRENT_LOCALE

### ISSUE THREAD

**Issue by cedricf** [MetaMask/metamask-extension#3973]
In ui/app/reducers/metamask.js 

Line: 361 should be
    `case actions.SET_CURRENT_LOCALE`
not     
   `case action.SET_CURRENT_LOCALE`

'`actions`' vs '`action`'

**Comment by danfinlay** [comment]
Thanks for the report!

**Comment by cedricf** [comment]
No problem. Sometimes there are the hard to spot irritating bugs. Glad I could help.
