### ISSUE TITLE
imported addresses missing

### ISSUE THREAD

**Issue by p-s-dev** [MetaMask/metamask-extension#3979]
*  Expected Behavior
Metamask should remember imported accounts

  *  Actual Behavior
Close browser.  Open browser again.  Some addresses that were imported are now gone from the account list.

  *  Browser Used
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

  *  Operating System Used
macOS 10.13.3

Using metamask 4.5.5.  Switching back and forth from Beta to Old UI a few times.  Using many custom rpc urls on alternative chains.

I know it sounds crazy.  I thought it happened before, but wasn't sure.  Metamask was running slow.  It took a while to validate the password.  And validating the password to get the private key never worked.  After entering the password to get private key, it would start using a huge amount of CPU until eventually metamask would crash and prompt to restart the plugin.  So I decided to remove the plugin, which would remove all my accounts, and re-import them.  So then I had one seed-generated metamask address and then 11 account addresses imported from geth json wallet files.  When I go to use metamask the next day, after having closed the browser, now I only have 3 accounts.  One seed-generated and 2 imported.  Before I removed and re-installed, I noticed one or two newly imported accounts disappear.  I had a lot of accounts and though maybe I had reached a max limit, so that caused it to not be retained after browser restart.

I'll just import them again, but wanted to report.

**Comment by egenny** [comment]
I've experienced something similar, running MacOS 10.10.5, meta mask 4.5.5 chrome Version 65.0.3325.181 (Official Build) (64-bit)   
I had imported several accounts using Private Key.  I was doing some testing so disabled meta mask in chrome, when I re-enabled meta mask the imported accounts were gone.  It wasn't a big deal as I simply imported them again but it was unexpected.

**Comment by jchittoda** [comment]
I am also facing this problem. When I import multiple PKs and browser just restarts, this clears the imported PKs.

MacOS 10.13.5
Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by bdresser** [comment]
hey all - anyone have reliable reproduction steps we can follow? haven't seen this ourselves.

**Comment by whymarrh** [comment]
I'm closing this for now, if folks have reliable reproduction steps, please ping us.
