### ISSUE TITLE
Only fetch token prices by token address

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3981]
Token exchange rates are currently fetching by THREE LETTER SYMBOL, instead of token address. This means anyone can fake a valuable token by naming it the same thing as another token. That’s not ok!

We should ensure that we get token prices by address. Pretty sure the balanc3 team set this up just for us when we asked, so we should use that, not Shapeshift.

This was brought to my attention because a user is deploying a new token using the `BTG` symbol (Boulion Troy Grain), which is widely used for "Bitcoin Gold"

**Comment by danfinlay** [comment]
Here's the API docs:
https://exchanges.balanc3.net/

And an interactive API explorer:
https://exchanges.balanc3.net/

Requires hitting the `/coins` endpoint first to get a list of coins they have prices for, and then you still look up by symbol, but at least you can know you're looking up by the wrong symbol.

It would be better if we could do a request directly for token pairs by address, it seems like by requiring requests to be by "symbol", they ensure no two symbols can ever be useful, and my belief is that we're quickly headed to a world where we have far too many coins to price by symbol.

A few sample APIs that might allow us to look up by symbol:
`/price?from=ERC20${address}&to=ETH`
^ In that example, a prefix can be used to identify non-symbol identifiers. Other formats could work. Maybe one where query params specify type:
`/price?fromType=ERC20&toType=SYMBOL&from=${tokenAddress}&to=ETH`

Those are a few ideas. I'll pass this to the Balanc3 team for possible API update, in the meanwhile, at least we could not show tokens if they aren't one of the "supported symbols".

**Comment by danfinlay** [comment]
Ah it already allows querying their API by address, here is a working query:

`https://exchanges.balanc3.net/prices?from=0X6810E776880C02933D47DB1B9FC05908E5386B96&to=ETH&exchanges=hitbtc&exchanges=binance&exchanges=bittrex&exchanges=kraken&exchanges=poloniex&exchanges=cexio&exchanges=gdax&exchanges=bitmex&exchanges=gemini&autoConversion=false&summaryOnly=false`

**Comment by danfinlay** [comment]
Another working query:
`https://exchanges.balanc3.net/prices?from=0x6810e776880c02933d47db1b9fc05908e5386b96&to=ETH&exchanges=hitbtc&exchanges=binance&exchanges=bittrex&exchanges=kraken&exchanges=poloniex&exchanges=cexio&exchanges=gdax&exchanges=bitmex&exchanges=gemini&autoConversion=false&summaryOnly=false`

**Comment by bitpshr** [comment]
Awesome, thanks @danfinlay. Working on a fix to this now.
