### ISSUE TITLE
Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by Hus4kV** [MetaMask/metamask-extension#3993]
So I'm quite new to this, but this is a new bug I haven't encountered before. Basically when I try to send EOS from my meta mask back to an exchange, I can't submit the transaction. The new beta UI gives me a blank screen after i fill the info and click "next". Then it's an incomplete transaction in the EOS menu (greyed out) and when I click on it I get another empty screen. The console returns this error: 

ui.js:5268 Uncaught (in promise) Error: [ethjs-contract] while formatting incoming raw call data "0x454f530000000000000000000000000000000000000000000000000000000000" Error: Number can only safely store up to 53 bits
    at ui.js:5268
    at a (ui.js:6034)
    at ui.js:5793
    at ui.js:10437
    at i (ui.js:9034)

  *  Browser Used
Google Chrome
  *  Operating System Used
Win10

I've looked over if some1 had a similar issue lately, but didn't find anything. So I hope I wasn't just blind and wasted your time. Have a nice day!

**Comment by danfinlay** [comment]
One ether is `1e18` "wei", the smallest number in its blockchain, which is already too big for JavaScript to represent accurately.

You need to learn how to manage hex strings to use ethereum with JavaScript, I recommend [ethereumjs-util](https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/index.md).

If you want specific help, please post a repository so your problem can be specifically reproduced.
