### ISSUE TITLE
Start relying on a well maintained token list

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3994]
Maintaining a list of tokens and logos is a nightmarishly large task.

Long term, I am really not sure what is a fair way to look up logos and names.

In the short term, finding a list that is well maintained would be an upgrade from our current list, which we do not adequately maintain.

A few options:
- Come up with a protocol for our team to share the job of maintaining our list.
- https://github.com/MyEtherWallet/ethereum-lists
- https://github.com/TrustWallet/tokens

**Comment by tmashuang** [comment]
This is done in https://github.com/metamask/eth-contract-metadata
