### ISSUE TITLE
Unable to install the metamask extension on brave browser for android tablet

### ISSUE THREAD

**Issue by Adexbafo** [MetaMask/metamask-extension#3996]
Am using brave browser for android phone, have been trying to install meta mask extension to use on my Samsung tablet. So please help me out on this.

**Comment by vishva007** [comment]
Looks like MetaMask is currently only available on Brave desktop. Am not sure if extension are even part of mobile platform.

https://community.brave.com/t/brave-browser-on-android-and-accessing-meta-mask/15884

**Comment by bdresser** [comment]
@Adexbafo above post is correct, [Brave doesn't support](https://community.brave.com/t/brave-browser-on-android-and-accessing-meta-mask/15884/3) extensions on mobile yet.
