### ISSUE TITLE
some address lost when reboot

### ISSUE THREAD

**Issue by fuzzface** [MetaMask/metamask-extension#4003]
I roughly searched previous issues, but couldn't find similar issue.
Recently, I've lost some addresses twice. and i think it's related to imported address.

It has occurred when I reboot while Chrome opened (Metamask was signed in), and address is randomly ordered in both case.

Case 1 : address 1\~6 (generated), address 7\~9 (imported) <- address 7~9 lost
Case 2 : address 1 (generated), address 2\~3 (imported), address 4\~5 (generated) <- address 4\~5 lost

My theory is, if Metamask session is opened while reboot, address might not stored properly, and remains only address within count of HD generated address. In Case 1, only 6 addresses is survived, and 3 addresses survived  in case 2.

I know it needs more cases to prove, i'll update when it occurs again.

**Comment by bdresser** [comment]
hey @fuzzface, thanks for reporting. we've had several issues filed in this same category. for now, capturing all we can at #4287. any additional info you can provide is helpful!
