### ISSUE TITLE
Fake metamask on Google Play Store!?

### ISSUE THREAD

**Issue by totedati** [MetaMask/metamask-extension#4005]
I stumbled upon this apparently another fake metamask clone:
[Google Play MetaMask](https://play.google.com/store/apps/details?id=com.digital.metamask)

Is legit? Fake? Time to know to make reports to google to remove it from google play

**Comment by williamchong007** [comment]
seems already taken down by now

**Comment by totedati** [comment]
True, is closed down by Google Play and removed from any installed setup, including my device. But what my tried to do with this issue was to have an official statement from the real metamask devs about that fake app before next step, a report from my smartphone in Google Play app store. Anyway is very strange and disturbing how this style of fake apps can jump in Google Play app store, i mean "Brought to you by Google Commerce Ltd"!?!? Wtf!? Only later i see that all apps from Google Play is "Brought to you by Google Commerce Ltd" ... duh! So is still very easy to sneak fake apps in Google Play!
