### ISSUE TITLE
New UI - Account Label not visible on account screen 

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#4009]
Account Label hiding behind the left drawer

**Comment by danjm** [comment]
@kumavis Do you remember exactly what this was? Are you able to get a screen shot... or perhaps remember reproduction steps?

**Comment by kumavis** [comment]
![image](https://user-images.githubusercontent.com/1474978/40516075-333b737a-5f64-11e8-9827-8a20998573a8.png)

cant see account nickname for account that is currently selected

**Comment by cjeria** [comment]
@kumavis the design is ready for development on this issue. See https://github.com/MetaMask/metamask-extension/issues/3463

This issue can be closed out.

**Comment by danjm** [comment]
Created a ticket for the minimum viable solution: https://github.com/MetaMask/metamask-extension/issues/4474
