### ISSUE TITLE
Auto accept transactions under certain conditions rather than prompting users each time

### ISSUE THREAD

**Issue by rohithpr** [MetaMask/metamask-extension#4011]
This feature request is inspired by a discussion on Reddit: https://www.reddit.com/r/ethtrader/comments/8d3hou/daily_general_discussion_april_18_2018/dxkydd5/

I've faced a similar situation to what's described in the chain of comments linked above.

---

Problem:

- When I'm interacting with a DApp for a long time it is annoying to wait for the Metamask popup to appear and to accept it for each and every transaction.
- Same when I'm testing my own DApps as a developer but here the number of transactions signed would be higher at times.

Potential Solution:

- Provide users with an option to set allowances to DApps (tracking it by contract address would be safer than by website address) and automatically sign all transactions destined to that contract till its allowance is exhausted.

Eg: If I know that I'm going to be interacting with the cryptokitties contract a lot I can set an allowance of 10 ETH to the contract.

- Each time a transaction occurs whatever ETH leaves the wallet is deducted from the allowance.

- Once the DApp runs out of allowances users can be prompted with a list of all transactions that were automatically signed. The popup can also ask if they wish to give the DApp some more allowance or if they wish to manually sign txs from then on.

- Allowances could be reset to `0` once the account is locked.

- Since users can't see the data that we're actually signing, I don't think we're losing much in terms of security.

---

I haven't contributed to metamask in the past but I'd like to try and implement this if the feature request is accepted.

**Comment by bdresser** [comment]
relates to #3703

**Comment by danfinlay** [comment]
We may be getting closer to supporting something like this:
https://github.com/danfinlay/EIPs/blob/WalletPermissions/EIPS/eip-PermissionsSystem.md

**Comment by Robbiekruszynski** [comment]
Hi @rohithpr 

We are working on porting over feature request conversations over to our [zendesk](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) and encourage you to keep an eye on the conversations happening + open a ticket / contribute over there. 

Thanks!

I'm going to go ahead and close this ticket.

**Comment by Kingzleey** [comment]
Hello, did u later find any work around for this? I am trying to build a webapp that performs transactions (call functions) at a set interval automatically and looking for this exact feature.

**Comment by MaverickSamar** [comment]
Is there any way to auto sign transactions?

**Comment by isaack87** [comment]
> Hello, did u later find any work around for this? I am trying to build a webapp that performs transactions (call functions) at a set interval automatically and looking for this exact feature.

Did you ever find a way to do this?
