### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by tplenge** [MetaMask/metamask-extension#4012]
I have experienced lately that the CPU usage on my laptop when using metamask to access Dapps. The behavior happens in both Firefox and Chrome.

Steps to reproduce:
Launch Chrome with no tabs open, cpu usage is <1%
Log into Metamask, cpu is mainly unaffected
Launch https://beta.akasha.world/ having one board with tag "Ethereum" on Rinkely, cpu around 20%-40%
Open one post, cpu around 70%

Is this normal behavior, for using metamask, normal webbrowsing does not cause this high cpu usage

**Comment by bdresser** [comment]
@tplenge thanks for reporting and sorry for the delay. we're tracking this issue in #4047.
