### ISSUE TITLE
NewUI CustomRPC network dropdown doesnt navigate

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#4016]
Clicking the Custom RPC in the network dropdown tab navigates to the Settings View in the oldUI. Should either do the same or we could make a custom modal for setting a Custom RPC url.

**Comment by danfinlay** [comment]
What does it do in thew New UI now?

**Comment by alextsg** [comment]
@danfinlay It was still changing the view using the old `currentView` navigation which doesn't do anything after adding react-router. The PR to fix this is open: https://github.com/MetaMask/metamask-extension/pull/4028
