### ISSUE TITLE
Unable to retry a transaction with a higher gas price in Ganache.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#4018]
When testing the retry transaction with a increased mining block time in Ganache, I was unable to retry a transaction with a higher gas price. The retry transaction instantly fails with this error: 
`Error: the tx doesn't have the correct nonce. account has nonce of: 1 tx has nonce of: 0"`. Once the original transaction gets mined it will be confirmed and the retried transaction will be dropped.

**Comment by frankiebee** [comment]
i dont think this is a deploy blocker removing the tag

**Comment by frankiebee** [comment]
solution dont submit the transaction and remove it from tx list if the original tx gets confirmed in a block

**Comment by cjeria** [comment]
@alextsg here's an updated flow for this feature https://consensys.invisionapp.com/share/URIRKLT4AFW#/297103285_Full_Page_V2
