### ISSUE TITLE
NewUI Add Token button persists the sidebar

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#4024]
Clicking the Add Token Button should close the sidebar to add/search for tokens. Currently, once the Add Token button is clicked, the user has to click outside of the sidebar to close it.

**Comment by alextsg** [comment]
Fixed with https://github.com/MetaMask/metamask-extension/commit/2381c0e0f461304265279155176fa655e2eb97b4#diff-8d871944d31048c270174b1ca7fbcf54
