### ISSUE TITLE
Add doc generation to CI

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4027]
We should remove our `docs/jsdocs` from version control, and instead add it to our CircleCI artifacts, and link to it from the Readme.

This way, we will re-generate docs on every PR & merge, and will not need to store the full history of these doc pages in our git history.

**Comment by lazaridiscom** [comment]
https://github.com/lazaridiscom/mm-vault/blob/master/package.json#L11

**Comment by lazaridiscom** [comment]
todo or not todo...

**Comment by lazaridiscom** [comment]
I just wanted to make you a tiny present by providing this, but it looks that its already done:

https://github.com/MetaMask/metamask-extension/blob/develop/.circleci/config.yml#L123

And the relevant gitignore within: 1ef6528

So I guess this issue can be closed.

**Comment by whymarrh** [comment]
> We should remove our `docs/jsdocs` from version control [...]

That directory is no longer in the main extension repo
