### ISSUE TITLE
I can not connect to my private network

### ISSUE THREAD

**Issue by ARR552** [MetaMask/metamask-extension#4035]
Hello,
I have an issue when i try to connect metamask to my private network based on quorum.
I have already import my account succesfully and i have configured the rpc http://myip:22000
In my server i use the option --rpccorsdomain moz-extension://624d6f9b-e5bd-4685-9fd4-760cb1990efa,chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn
I think it should be working but when i select the private network, metamask crashes all the time and it shows a blank window and nothing happens. Sometimes i am able to select the private network successfullly but when i interact with the contract and i have to confirm the transaction on metamask, the white window appears. However the number that appears in the metamask icon works well.

I firefox i get this error:

![firefox error](https://user-images.githubusercontent.com/11256256/38980187-6dbe4392-43bc-11e8-9668-657921d9288c.png)

In chrome:

![chrome error](https://user-images.githubusercontent.com/11256256/38980217-85138430-43bc-11e8-9dcb-0a85ca6ad802.png)

Cors is working fine. I have checked it with:
curl -H "Origin: moz-extension://624d6f9b-e5bd-4685-9fd4-760cb1990efa" -H "Access-Control-Request-Method: GET" -H "Access-Control-Request-Headers: X-Requested-With" -X OPTIONS --verbose "http://myip:22000"

Any idea??

Thank you

**Comment by ARR552** [comment]
Cors is working fine. I have checked with:
curl -H "Origin: moz-extension://624d6f9b-e5bd-4685-9fd4-760cb1990efa" -H "Access-Control-Request-Method: GET"   -H "Access-Control-Request-Headers: X-Requested-With" -X OPTIONS --verbose "http://myip:22000"

**Comment by bdresser** [comment]
hey @ARR552 sorry for the delay in response. Are you still experiencing this issue?

**Comment by ARR552** [comment]
@bdresser Yes, i still have the same issue.
In beta ui i get a different error.
![imagen](https://user-images.githubusercontent.com/11256256/41336338-3f8c03f0-6eec-11e8-8f83-7a4906928d70.png)

**Comment by whymarrh** [comment]
I'm going to close this for now. @ARR552 if you're still seeing issues on the latest MetaMask version, please open up a new issue with reproduction steps.
