### ISSUE TITLE
The occurrence of metamask malfunction

### ISSUE THREAD

**Issue by barvalley** [MetaMask/metamask-extension#4045]

**Comment by alacrity26** [comment]
@barvalley Have you tried restarting your browser? If you have your seed phrase backed up, you can probably work around this by uninstalling, reinstalling, and restoring from your seed phrase. Please refer:
https://metamask.helpscoutdocs.com/article/60-restore-from-seed-phrase-new-ui
 
If you'd like us to figure out exactly what has gone wrong for you, you should send us your logs to support@metamask.io
 
Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
