### ISSUE TITLE
Metamask User - Private Key

### ISSUE THREAD

**Issue by jj3311** [MetaMask/metamask-extension#4046]

**Comment by alacrity26** [comment]
@jj3311 for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by jj3311** [comment]
how to get ticket .....

**Comment by jj3311** [comment]
sent but not sure is it correct ..... need guideline 

thanks
