### ISSUE TITLE
Cannot access the wallets created yesterday

### ISSUE THREAD

**Issue by scorpion1958** [MetaMask/metamask-extension#4048]
Lost my password and restored with the 12 keywords, but now it does not show one of the accounts created and imported yesterday, its like brandnew and empty and also not any of the menu selections like Import is working

**Comment by royreyg** [comment]
Similar issue here.  Didn't lose my password, but created an account and transfered some Eth to it.  Now it is not shown up in my Account list, although the older accounts are still shown up.  Please help.

**Comment by kid007** [comment]
+++++

**Comment by bdresser** [comment]
if you click "create account" in the top right again, the extension will recreate your previously made accounts. see [this comment](https://github.com/MetaMask/metamask-extension/issues/4207#issuecomment-394864588) for details.

we'll work on making this clearer in the extension.

**Comment by martineezz** [comment]
@scorpion1958 If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by darkwing** [comment]
Please do not contact the email cited, it is a scammer that will try to get your recovery phrase.
