### ISSUE TITLE
Reset password forgotten on restarting Firefox

### ISSUE THREAD

**Issue by sheldrake** [MetaMask/metamask-extension#4049]
Hi, I've experienced a problem with your Firefox (ver 60.0b13) add-on .

Install Metamask
Create password
Close browser
Open browser
Change password
Close browser
Open browser
New password does not work.

Checked this twice now.

**Comment by alacrity26** [comment]
@sheldrake for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
