### ISSUE TITLE
WebExtension Standard Status - tcp/udp sockets

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#4051]
Chrome allows this for Chrome Apps (already years into a deprecation path)
https://developer.chrome.com/apps/manifest/sockets
[Here is a ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=152875) for requesting support in WebExtensions, currently labeled `wontfix`.

Firefox supposedly supports this through [XPCOM](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM) which seems to be deprecated. [Here is a ticket](https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1247628) for enabling it under the extension api, currently labeled "new / unassigned".

**Comment by Gudahtt** [comment]
It doesn't seem like much progress has been made on this in either Chrome or Firefox, so I think we'll have to operate on the assumption that we won't be getting an API like this for the forseeable future. I'll close this for now.
