### ISSUE TITLE
Transactions backing up and not validating no matter how much gwei/gas

### ISSUE THREAD

**Issue by diondalton** [MetaMask/metamask-extension#4054]
I have used metamask plenty in the past, but not sure whats happening or how to resolve?
Transactions are just sitting there, and I cant reject them or add more gas and make them speed or do anything.  Please help

<img width="341" alt="screen shot 2018-04-21 at 10 01 12 pm" src="https://user-images.githubusercontent.com/38589413/39086066-ae74d5c6-45cf-11e8-922b-83c75a7da632.png">

**Comment by godman84** [comment]
I'm having the same issue...

**Comment by dunnsa** [comment]
I'm having this issue right now.  Was there a resolution for you yet?

**Comment by Sufuron** [comment]
same problem, someone have any solution ?

**Comment by dunnsa** [comment]
I deinstalled then reinstalled the chrome extension, then restored with seed words.  Don't do Beta.  Works again for me.

**Comment by bdresser** [comment]
hey @diondalton @dunnsa sorry for the delay. there have been a couple updates to the tx submit logic since this was filed - can you let us know if you're still experiencing this issue on 4.7.4?
