### ISSUE TITLE
MetaMask infinite spinner

### ISSUE THREAD

**Issue by elie222** [MetaMask/metamask-extension#4064]
Switching to mainnet or rinkeby from private network, metamask just shows an infinite loader. Happening on my colleagues computer too.

**Comment by bdresser** [comment]
@elie222 are you still experiencing this issue?

**Comment by elie222** [comment]
I see this sort of thing happen occasionally. For others that run into this, I would recommend:

* restarting MetaMask (disable and reenable the Chrome extension for example)
* checking to see that you are running a node on the specified port (specific to local development networks)

**Comment by mushketyk** [comment]
Happens of Firefox as well. Noticed this after an exception was thrown during executing a transaction.

**Comment by whymarrh** [comment]
> Switching [...] network, [MetaMask] just shows an infinite loader

We've addressed infinite spinners when switching networks, if you're still seeing issues there feel free to open up a new issue.

For infinite spinners arising from other conditions, we're looking at implementing a timeout (#3253). If you have reliable reproduction steps for an infinite spinner, please open up a new issue.
