### ISSUE TITLE
Incorrect Token Balance

### ISSUE THREAD

**Issue by GeoAloha** [MetaMask/metamask-extension#4067]
Hi,

I added AUC token to my metamask wallet, but changed the precision to 8, because sixteen seemed like a lot of decimals. Well, I have 366 AUC, but metamask shows 366665214810320.709 -- which would be nice. Something to aim for I guess. In the meantime though, any suggestions for how to fix this? I thought maybe I cold remove the token then re-add it, so I tried the beta UI, but no luck. Here's a screen shot. Guess maybe I don't know what "Precision" is for. (I assumed it would set the number of decimal places displayed.)

I'm on the current release of Brave, on Mac High Sierra.

<img width="354" alt="screen shot 2018-04-24 at 11 44 38 am" src="https://user-images.githubusercontent.com/38702679/39207919-1f15666e-47b6-11e8-8d1b-1882dbf6d1a7.png">

Thank you!

**Comment by danfinlay** [comment]
We auto-fill the `precision` field with data from the smart contract when possible, so you basically shouldn't edit it if it is auto-filled. Maybe we should disable editing it when we're able to ask the chain.

You should be able to edit this by re-adding the token with a different precision. You also *could* remove the token if you could see the three dots, but we have a formatting issue here that is being fixed very soon, so you don't actually have the three dots.

I would try to "Add Token" again but use the correct precision, it should update the listing.

**Comment by GeoAloha** [comment]
Hi Dan,

Thanks for the response. Re-adding just put a second "AUC" token in the wallet, so there are two now. And there's another problem -- I stupidly went to IDEX and bought a little more AUC, then tried to withdraw from IDEX into my metamask wallet. That transaction is now "processing" -- neither on IDEX nor in the wallet, and I suspect the condition of the metamask wallet has broken something required for the transaction -- is that possible?
<img width="347" alt="screen shot 2018-05-01 at 6 57 59 pm" src="https://user-images.githubusercontent.com/38702679/39501816-e11af600-4d71-11e8-83ef-123ffbdeee39.png">

Anway -- thank you for helping with this.

**Comment by bdresser** [comment]
hey @GeoAloha - if you're still having trouble, I recommend you reach out to support@metamask.io
