### ISSUE TITLE
Cannot send Etherium from my Metamask? 23 april 2018

### ISSUE THREAD

**Issue by Densi1** [MetaMask/metamask-extension#4071]
It worked great until I switched to beta?

**Comment by dunnsa** [comment]
I had to double check my seed words, remove the extension then reinstall.  Restored with seed words.  Do not move back to Beta.  Works now for me.

**Comment by Densi1** [comment]
What do I do if all the funds are gone after I reinstall and recover with seed phrase? Now what?

**Comment by bdresser** [comment]
@Densi1 please email support@metamask.io with a copy of your [state logs ](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI)
