### ISSUE TITLE
Metamask record transaction hash show error

### ISSUE THREAD

**Issue by NextZeus** [MetaMask/metamask-extension#4075]
mac os 
google chrom 
ropsten network

# step:
1. buy some token on website but not submit
2. one by one click submit to send transaction

# appearance

1. 10,11,12 tell me 'please retry .... with higher price'
2. 9,10,11,12 with the same transaction hash
3. after some time, these transaction all success, but transaction hash not update to correct hash.

![image](https://user-images.githubusercontent.com/10203487/39235125-a3db29b4-48a7-11e8-9c5b-10bcc99cb951.png)

**Comment by danfinlay** [comment]
Are you saying after retrying with higher gas, if you click on that successful tx, it does not go to etherscan properly?

**Comment by NextZeus** [comment]
@danfinlay when i click on successful tx, it go to etherscan with the correct tx, but metamask tx record  `s tx hash was not updated to the correct hash.

**Comment by bdresser** [comment]
@NextZeus that grey text displaying below the timestamp (`0x5e5...B3F7`) is the recipient address, not the transaction hash
