### ISSUE TITLE
UX: Import Account message suggests seed phrase association on Create Account

### ISSUE THREAD

**Issue by mryellow** [MetaMask/metamask-extension#4089]
> Imported accounts will not be associated with your originally created MetaMask account seedphrase. 

This suggests that as opposed to using this `Import Account` feature, using the alternate option of `Create Account` will somehow generate a key "associated" with your seed phrase. 

https://github.com/MetaMask/metamask-extension/issues/2641#issuecomment-384595884

**Comment by bdresser** [comment]
closing this in favor of #4207
