### ISSUE TITLE
Proposal: Move off of the extension view.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#4094]
Leaving this is a proposal to move MetaMask to a full screen experience and the extension view would be for confirming transactions.

**Comment by june07** [comment]
Check out https://june07.com/crypto/metamaskpay.html?amount=1&payee=0x69F3C9210091A0E5cb7D01459683447173D4BDDA

Might be applicable.  Note, it will call MetaMask automatically with the given parameters on page load.  You have the options of customizing MetaMask arguments via the page (full screen).

**Comment by Gudahtt** [comment]
@tmashuang Is this worth keeping open?

There's still a strong case for focusing more upon the fullscreen UI, but I doubt we'll ever remove the popup UI completely. Too many users prefer it, and it's much better for some cases (like when checking balance/history without totally switching contexts away from a dapp).
