### ISSUE TITLE
Move back to Uglifyify from npm

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4098]
Our problem with uglifyify has been fixed in version `5.0.0`, so we can move back to it:
https://github.com/hughsk/uglifyify/pull/62#event-1597677552

Or we could wait until more changes are merged in, since right now we have the same thing on our git branch, so there's no pressing benefit yet.

**Comment by abitrolly** [comment]
https://github.com/MetaMask/metamask-extension/pull/4111 kills uglifyify in `package.json`.
