### ISSUE TITLE
Add `eth_watchToken` method to provider.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4112]
Would allow sites to suggest new tokens for the user to track in our token tracker:

https://github.com/ethereum/EIPs/issues/747

Could maybe namespace under `wallet_` or something, if we wanted to logically separate it from blockchain interactions.

Would allow users to easily add tokens to watch, with logos and everything, without us carrying the burden of verifying token projects and their logos.

Would require a new confirmation view "Do you want to add this token to your wallet?", along with the details of the token, including the current account's balance.

**Comment by bdresser** [comment]
closing - this was handled in #4606 @danfinlay ?
