### ISSUE TITLE
Ensure NODE_ENV === 'production' in production build

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4115]
See screen shot below. Note that sentry is set to 'PROD', but NODE_ENV must not be 'production' given the react warnings.

<img width="636" alt="screen shot 2018-04-27 at 7 51 55 pm" src="https://user-images.githubusercontent.com/7499938/39390370-5d1b5292-4a6e-11e8-9abe-91af7cffde05.png">

**Comment by kumavis** [comment]
sentry uses the `METAMASK_DEBUG` flag

**Comment by kumavis** [comment]
should be set correctly here https://github.com/MetaMask/metamask-extension/blob/141884ee6ad55da98f5a0752b76e55238ddc5c5d/gulpfile.js#L484

**Comment by kumavis** [comment]
maybe it gets minified or otherwise mangled

**Comment by whymarrh** [comment]
Fixed on `develop`
