### ISSUE TITLE
Missing account

### ISSUE THREAD

**Issue by sergmih2** [MetaMask/metamask-extension#4119]
Hello,

Today he created a second account for a friend and paid money there. But I did not manage to import it, Chrome browser crashed and rebooted, now I do not see my second account in the list of accounts, and the money is already on it. What do i do? How can I restore my second account?

**Comment by achwartz** [comment]
had the same problem , did not worked for me taht solution , i already verified this accoutn was made in the same wallet

**Comment by bdresser** [comment]
hey folks: please reach out to support@metamask.io if you're still having trouble.
