### ISSUE TITLE
Depositing Ether from MM Error

### ISSUE THREAD

**Issue by brandysue** [MetaMask/metamask-extension#4127]
Noob here... I am trying to figure out what happened when I deposited Ether on FD from MM. I'm not sure if i needed to do a deposit since the Ether shows up as being there when i'm signed into Metamask. I foolishly tired it twice.  
So the Ether is no where to be found but. the deposit is showing on FD under funding. Also the transactions were successful. Here is the address and the tx hash logs: 

0x46b19f28c022fdd05ce7763e8dbdb92b6916e1d5
0xbffae9306c1c4f525ef01ca63bc5f081fdfa581ab8ce678f04f5f65effb3f492 
0x3eb9036e8e193dab02d357cfec95bb047b707a1071880817435d70e2a64f9635
Funds 0xbffae930	Deposit		0.252

Many thanks... sorry I'm still floundering a bit.

**Comment by frankiebee** [comment]
what is FD?

**Comment by brandysue** [comment]
Fork Delta

**Comment by bdresser** [comment]
hey @brandysue – please email support@metamask.io with a copy of your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI-)
