### ISSUE TITLE
Console web3 errors

### ISSUE THREAD

**Issue by agentcobra** [MetaMask/metamask-extension#4129]
Hello there,
When I delete or disable the extension, I've got the problem.
 # Expected Behavior
no console erreur
 # Actual Behavior
## with metamask enabled
MetaMask: web3 will be deprecated in the near future in favor of the ethereumProvider 
https://github.com/MetaMask/faq/blob/master/detecting_metamask.md#web3-deprecation
## without metamask
Uncaught ReferenceError: web3 is not defined
 #  Browser Used
Vivaldi 1.15.1147.36 
 # Operating System Used
4.16.3-1-ARCH
# Screenshots
## with metamask enabled
![capture du 2018-04-29 23-10-52](https://user-images.githubusercontent.com/1831853/39411050-92ed37f6-4c02-11e8-8986-1beb576c6250.png)
## without metamask
![capture du 2018-04-29 23-08-51](https://user-images.githubusercontent.com/1831853/39411036-4f365ef2-4c02-11e8-9a58-536ea5903723.png)

**Comment by frankiebee** [comment]
>MetaMask: web3 will be deprecated in the near future in favor of the ethereumProvider
thats not an error it's a warning

**Comment by bdresser** [comment]
As frankie mentioned, this is a warning that the global `web3` object will be deprecated in the future. You should begin to rely on `web3.currentProvider` instead. Read more [here](https://github.com/MetaMask/faq/blob/master/detecting_metamask.md#web3-deprecation)
