### ISSUE TITLE
Nonce Too Low - using new address with no TX

### ISSUE THREAD

**Issue by tjc4** [MetaMask/metamask-extension#4134]
I'm trying to get ETH to my MetaMask wallet from a Rinkeby faucet but the faucet tells me "nonce too low".  This is the faucet I'm using:
https://faucet.rinkeby.io/

I'm using a brand new MetaMask ETH address with no TX history / no established nonce value.  See:
https://rinkeby.etherscan.io/address/0xC1a4B227869135F05bd6667154CD722ef1240a1B

Another user had a similar question and was told that it was told that "a transaction can only be mined if its nonce is one more than the nonce of the last transaction that was mined from that address" but that does not seem to apply as there are no TX associated with this address.  

I also found another nonce error thread where there was a suggestion to "please reset metamask by switching to testnet and back.  then try again and let us know."  But switching to main net then back to Rinkeby did not solve the issue.  

Any ideas?

**Comment by juanpe1103** [comment]
I have the same problem..

**Comment by kumavis** [comment]
"nonce too low" is an internal error from the rinkeby faucet. it is currently broken.
