### ISSUE TITLE
Cannot Reset Account on Firefox

### ISSUE THREAD

**Issue by jevdiego** [MetaMask/metamask-extension#4136]
Hi,

I need to reset the account (as explained here https://metamask.helpscoutdocs.com/article/36-resetting-an-account), but as shown below, I cannot get to the 'reset account' button. Either I should be able to scroll down (which obviously I can't) or the Metamask window needs to be bigger. I'm assuming this is a bug in the Firefox extension.

![firefox](https://user-images.githubusercontent.com/20283397/39436887-92ac2160-4c9f-11e8-9b20-720796cffed0.png)

**Comment by mallapurbharat** [comment]
True... The "Reset account" button displays in Chrome, but doesn't show up in Firefox 60.0.1 (64-bit) on Ubuntu.

**Comment by bdresser** [comment]
@mallapurbharat @jevdiego Firefox is now up to date with our most recent release (4.7.4) and I'm no longer seeing this issue – could you confirm this is fixed? 

(It's also fixed on the new UI, click in the top right and then "Try beta!")

**Comment by jevdiego** [comment]
Yes, displays now. Thanks for the fix.

**Comment by mallapurbharat** [comment]
Yes, the issue is fixed now.

**Comment by unparalleled-js** [comment]
I am currently having this issue
