### ISSUE TITLE
Allow deactivation of MetaMask Phishing behavior - Allow Whitelisting

### ISSUE THREAD

**Issue by dievardump** [MetaMask/metamask-extension#4138]
Bug Reports:

  Briefly describe the issue you've encountered

When trying to go on a website that is in the Ethereum Phishing Detector list, it doesn't let the browser load the page, and there is absolutely no way to change this behavior outside deactivating the Add-on itself.
The domain is a domain that allows for free sub-domains registration. One of the sub-domain used to be a bad one, now all sub-domains are inaccessible because of this one.

  *  Expected Behavior 
1 / There is no reason for MetaMask to mess with my content.
It should for sure show a warning, opening a new tab or opening a pop-in in the window, but not change the URL of the website, and not disallowing me to go on the website. I should have a way to pass.
2 / I should be able to myself whitelist (localy) the current website.
3 / I shouldn't have to disable completely the MetaMask extension to be able to load one website. There should be a "turn off" button in the MetaMask UI. Preferably "Turn-off for this website." like Adblock.

  *  Actual Behavior
Nothing to turn MetaMask off, impossible to load a page I know is legit.

  *  Browser Used
59.0.2 (64 bits)
  *  Operating System Used
Linux 16.04 LTS

**Comment by frankiebee** [comment]
What was the domain if you dont mind me asking?

**Comment by frankiebee** [comment]
So their is a lot going on here in the issue you've opened i've opened issues for your concerns individually so we can discuss them and see what we can do about them and make easier to target each one specifically:

#4148 
#4149 
#4150 
#4151 

Im going to close this issue just so their isnt any confusion with the other issues
