### ISSUE TITLE
[feature request] less aggressive warning page for blak listed sites

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#4148]
>It should for sure show a warning, opening a new tab or opening a pop-in in the window, but not change the URL of the website, and not disallowing me to go on the website. I should have a way to pass.

This is a feature request captured from issue #4138

**Comment by bdresser** [comment]
given all the aggo phishing we've seen, we probably won't make the warning page less scary, but we will allow users to proceed the phishing warning if they really really want to.
