### ISSUE TITLE
fuzzy blocking of sites preventing legitimate sites from being loaded 

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#4150]
>The domain is a domain that allows for free sub-domains registration. One of the sub-domain used to be a bad one, now all sub-domains are inaccessible because of this one.

this was the bug captured from #4138

**Comment by dievardump** [comment]
Thank you.

To answer your question in #4138
> What was the domain if you dont mind me asking?

the domain is http://rf.gd which is owned by a free hosting platform and offers free domains in the form of http://your-domain.rf.gd

**Comment by bdresser** [comment]
this logic is handled in the https://github.com/MetaMask/eth-phishing-detect/ repo, so please open an issue there if the fuzzy matching logic is causing you issues.
