### ISSUE TITLE
Allow user to proceed through phishing warning

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#4151]
> I shouldn't have to disable completely the MetaMask extension to be able to load one website. There should be a "turn off" button in the MetaMask UI. Preferably "Turn-off for this website." like Adblock.

this is a feature request captured from #4138

**Comment by bdresser** [comment]
Came up again in a recent security report we got. Allowing users to proceed through the phishing warning could make them less likely to disable the entire extension.

**Comment by bdresser** [comment]
closing, dupes https://github.com/MetaMask/metamask-extension/issues/2784
