### ISSUE TITLE
Recent Block Tracker doesn't handle low block number or changing networks

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#4154]
Multiple issues here
- [ ] was on `ganache-cli` on genesis block. This generates bad requests because the recent block tracker does not expect the block number to be so low. it requests `0x-1`.
- [ ] upon changing networks, recent block tracker started spamming infura hard with the same bad requests

**Comment by bdresser** [comment]
@kumavis is this relevant after provider re-write or can we close

**Comment by Gudahtt** [comment]
I haven't heard of these things happening recently, so I'll close this for now. Hopefully this is no longer a problem
