### ISSUE TITLE
Metamask not interacting with website

### ISSUE THREAD

**Issue by MarkyCruise** [MetaMask/metamask-extension#4158]
Hi, I'm new to this. 

I have downloaded metamask, and it is not working.

I intend to use it to buy tokens from a website - however, when I try buying through website, metamask doesn't show the 'Buy' button. 

In addition - the website can read my metamask wallet.

I have the following:
-Metamask set up correctly
-Token added
-Has ether balance
-Correct ID use
-Imported MEW to Metamask

**Comment by frankiebee** [comment]
Hey @MarkyCruise I recommend that you email support@metamask.io and we can help you out better their.
