### ISSUE TITLE
MM won't sync to local node

### ISSUE THREAD

**Issue by harksha** [MetaMask/metamask-extension#4159]
After the latest update(I assume, as the same setup worked just yesterday) metamask doesn't sync with my local node anymore. 
I'm using ganache to run a node on HTTP://127.0.0.1:7545 - which I configured in metamask as a custom RPC connection.
I imported a few other accounts from ganache and none of them show the ETH amount I have in ganache - they're all 0.
I also deployed a very basic contract which it can't read, throwing:
 "Contract has not been deployed to detected network (network/artifact mismatch)" 

I also changed the web3 provider to use ganache and that works fine, reading the contract.
Browser: Chrome Version 65.0.3325.181 
OS: Win10

http://prntscr.com/jc9q8r
http://prntscr.com/jc9oar

**Comment by harksha** [comment]
Had a hunch and tried again, using lowercase: "http://127.0.0.1:7545" - and this works. still a bug if you ask me, but I guess this can be closed.

**Comment by kumavis** [comment]
filed over here https://github.com/MetaMask/provider-engine/issues/237
