### ISSUE TITLE
My accounts has vanished!

### ISSUE THREAD

**Issue by KotaKudo** [MetaMask/metamask-extension#4160]
I made 70 empty accounts on metamask extension about a month ago.
And now, the number has decreased to 14 accounts.
There should be airdrop tokens in those missing accounts.
 I send an email to metamask team about this issue but their reply was automated one and it was pointless. Is this a common problem with metamask?
I would appreciate if you help me with this issue.

**Comment by kumavis** [comment]
@KotaKudo press the create account button and it will recreate the same accounts

**Comment by jennypollack** [comment]
@kumavis do we have another issue for tracking the root cause of this?

**Comment by bdresser** [comment]
@KotaKudo we now auto-generate any accounts from the same seed that we detect have value on them.

If you're still having trouble, please reach out to support@metamask.io
