### ISSUE TITLE
No results when I sign a transaction

### ISSUE THREAD

**Issue by wilbur8** [MetaMask/metamask-extension#4175]
![image](https://user-images.githubusercontent.com/38931399/39558329-b7c300b4-4e5b-11e8-8403-5406b68d061f.png)
So i am attempting to close this buy order on IDEX exchange but every time I click close, metamask asks for my approval but when I sign it, nothing happens. This has been happening for over three weeks now.

**Comment by alacrity26** [comment]
for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by bdresser** [comment]
@wilbur8 i'm not able to reproduce this bug – could you try on ^4.7.0 with the new UI? (from the top-right menu, click "try beta!")
