### ISSUE TITLE
Issue in calling encodeABI() - synchronous methods are not allowed

### ISSUE THREAD

**Issue by vu3mmg** [MetaMask/metamask-extension#4177]
We are facing issues in calling encodeABI() function from browser using metamask .
We are invoking encodeABI() as follows

`const sdata = contract.method(args).encodeABI();`

We are getting an error that encodeABI () is synchronous .

 `MetaMask Web3 object does not support synchronous methods like eth_sendTransaction without a callback parameter. See https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client for details.`

Could you please let me know whether any workaround is there for the same .

**Comment by shawntabrizi** [comment]
It looks like you are using Web3.js 1.0 which has a special pattern for contract methods:

[From: Callbacks Promises Events](http://web3js.readthedocs.io/en/1.0/callbacks-promises-events.html)

> Ethereum as a blockchain has different levels of finality and therefore needs to return multiple “stages” of an action. To cope with requirement we return a “promiEvent” for functions like `web3.eth.sendTransaction` or contract methods. This “promiEvent” is a promise combined with an event emitter to allow acting on different stages of action on the blockchain, like a transaction.
> 
> PromiEvents work like a normal promises with added `on`, `once` and `off` functions. This way developers can watch for additional events like on “receipt” or “transactionHash”.
> 
> ```
> web3.eth.sendTransaction({from: '0x123...', data: '0x432...'})
> .once('transactionHash', function(hash){ ... })
> .once('receipt', function(receipt){ ... })
> .on('confirmation', function(confNumber, receipt){ ... })
> .on('error', function(error){ ... })
> .then(function(receipt){
>     // will be fired once the receipt its mined
> });
> ```

It appears you will need to use this pattern to have the `encodeABI()` function behave asynchronously.

**Comment by alvinveroy** [comment]
Any updates on this?

**Comment by danfinlay** [comment]
Could you please add details about how you're constructing your `contract` object?

In general, you should not use the injected `web3` object directly, but should instead use it to initialize your own local abstraction library, like web3, ethjs, or truffle-contract.

**Comment by mkshibu** [comment]
my contract invocation code is something like below.


```
let erc827_abi = { contract abi}
let service_abi = {contract abi}
var erc827_address = '0x9df5e31a1e5de828254d535d5c9b514d513316e8'
var service_crt_address = '0x1ce94a12f58b0b9b39d0a9f1520878a07d9a72e8' 
var user_address = web3.eth.accounts[0]

const erc827contractInstance = web3.eth.contract(erc827_abi).at(erc827_address);
const servicecontractInstance = web3.eth.contract(service_abi).at(service_crt_address);

```
//encodeABI() is the call which fails.
   ```
const sdata = servicecontractInstance.bookService(args.servicename,user_address,args.customername,args.servicetype,args.value,args.transaction_type,args.account_number).encodeABI(function(error, result){
    if(!error)
        console.log(result);
    else
        console.error(error)
	});
  console.log("encoded ABI is",sdata)


   erc827contractInstance.transferFrom(user_address,testadd_2,tokensToSend,sdata{from: testadd_2,gas:55000},function (error, result){ //get callback from function which is your transaction key
      if(!error){
           console.log(result);
       } else{
           console.log(error);
       }
});

```
When we hardcode the encodeABI, something like below,
```
const sdata = "0000...06..000"
erc827contractInstance.transferFrom(user_address,testadd_2,tokensToSend,sdata{from: testadd_2,gas:55000},function (error, result){ //get callback from function which is your transaction key
      if(!error){
           console.log(result);
       } else{
           console.log(error);
       }
});
```

it works fine. 

I was under the impression that encodeABI() failure is due to the synchronous nature of the call.

could you please let us know how to use encodeABI() with metamask? do you have some example code?
This is important for token standards like ERC827 where we can pass data to contract functions.

**Comment by danfinlay** [comment]
I don't think you can call `encodeABI()` on the result of a method call.

When you call:

```javascript
const sdata = servicecontractInstance.bookService(args.servicename,user_address,args.customername,args.servicetype,args.value,args.transaction_type,args.account_number).encodeABI(function(error, result){
 if(!error)
     console.log(result);
 else
     console.error(error)
 });
console.log("encoded ABI is",sdata)
```

You called the method synchronously, and then tried to call `encodeABI()` on the result.

Instead, if you want the ABI of that method, you should simply get it from the method:

```javascript
const abi = servicecontractInstance.bookService.encodeABI()
```

If you want to call the method, you need to include a callback as the last parameter to that method:

```javascript
servicecontractInstance.bookService(args.servicename,user_address,args.customername,args.servicetype,args.value,args.transaction_type,args.account_number, function(error, result){
 if(!error)
     console.log(result);
 else
     console.error(error)
 });
```

I hope this helps.

You can also use other web3 library alternatives, like [ethjs](https://www.npmjs.com/package/ethjs) or [truffle-contract](https://www.npmjs.com/package/truffle-contract) if you prefer working with promises. These libraries both have slightly more intuitive interfaces.

Let me know if this doesn't solve your problem, and I will re-open.

**Comment by mkshibu** [comment]
Thanks Dan. will try it out and come back.

**Comment by mkshibu** [comment]
Hi Danfinlay,
I tried the workaround suggested by you. It won't work. underlying web3js method encodeABI() is synchronous, there is no asynchronous counterpart at least in documentation. So encodeABI() call will not work through metamask.   Only option is web3 library alternatives, like ethjs or truffle-contract as you suggested.

Thanks for your time.

**Comment by danfinlay** [comment]
@mkshibu I did not say `encodeABI()` is async. I said the contract call is.

Please re-read my response carefully.

**Comment by mkshibu** [comment]
@danfinlay 
your suggestion was const abi = servicecontractInstance.bookService.encodeABI()
I am not sure how is it going to work as the output from encodeABI is tied to the arguments to the function on which one is invoking encodeABI().

Further more, my use case is not about calling  bookService directly, but pass it as data in the ERC827 transfer method.

my comment was that metamask alone will not fullfil this usecase, it needs other library alternatives as you suggested.

Hope it is clear.

**Comment by vu3mmg** [comment]
@danfinlay  could you please let us know any other work around . Is this a limitation of metamask

**Comment by danfinlay** [comment]
I don't believe this is a limitation of MetaMask, but maybe web3.js depends on a synchronous call to perform this basic function. If that is the case, that is a weakness of [the web3.js library](https://github.com/ethereum/web3.js/). I do not personally use web3.js directly to interact with smart contracts, because I prefer other smart contract abstraction libraries.

MetaMask's primary responsibility is injecting the provider (`window.web3.currentProvider`), and this object can be used to interact with the blockchain with a variety of libraries, even beyond web3.js:

- [ethjs](https://www.npmjs.com/package/ethjs)
- [truffle-contract](https://github.com/trufflesuite/truffle-contract)

You may also have luck asking web3.js questions on [stackexchange](https://ethereum.stackexchange.com/questions/42766/missing-ether-after-uninstalling-metamask).

**Comment by mkshibu** [comment]
@danfinlay
Problem is not because of web3.js, it is because of the fact that injected web3 is of lower version and api name itself is different.
https://ethereum.stackexchange.com/questions/50005/web3js-encodeabi-is-there-way-to-call-it-asynchronously?
Thanks.
