### ISSUE TITLE
Chrome extension freezing

### ISSUE THREAD

**Issue by ben-johnstone** [MetaMask/metamask-extension#4179]
Click on Extension, login window pops up, Fox starts to move head but then freezes. V. slow operation, can't enter password or click any other extension links.

Chrome: Version 66.0.3359.139 (Official Build) (64-bit)
Windows 10

**Comment by alacrity26** [comment]
@ben-johnstone For user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
