### ISSUE TITLE
Showing connecting to Main Ethereum Network

### ISSUE THREAD

**Issue by thackerronak** [MetaMask/metamask-extension#4180]
I have checked with all browser chrome,firebox and brave and also changed my wifi network but i'm still facing same error. 
metamask version : 4.6.1
chrome version : Version 66.0.3359.139 (Official Build) (64-bit)
Please check attachment for error info. 

This issue facing in my MacBook OSX but in ubuntu pc, it's working fine. 

<img width="1280" alt="screen shot 2018-05-03 at 3 00 37 pm" src="https://user-images.githubusercontent.com/26240401/39569506-05360616-4ee3-11e8-87cd-e936e867608f.png">

**Comment by gs047** [comment]
same issue

**Comment by alacrity26** [comment]
@thackerronak @gs047 For user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by thackerronak** [comment]
today working fine.
