### ISSUE TITLE
MetaMask 4.6.1 Amount Overflow

### ISSUE THREAD

**Issue by vgorin** [MetaMask/metamask-extension#4182]
MetaMask 4.6.1 doesn't check for amount overflow when sending funds manually.

Steps to reproduce:
1. Make sure to have 23ETH on your account or more.
2. Send 0.00022222222222222222222 ETH to another account which you own.
Note: MetaMask tries to send 22.22222222222222222222 ETH instead.

https://youtu.be/6EQzQl_FkQw

**Comment by alacrity26** [comment]
@vgorin for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by bdresser** [comment]
@vgorin could you try on ^4.7.0 with the new UI? (from the top-right menu, click "try beta!") 

i'm not able to reproduce
