### ISSUE TITLE
Warn when retrying a duplicate tx

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4185]
A common problem (just seen on stage at EdCon) is that a user who is impatient for a tx to go through will click "submit" again from the Dapp UI, and now have another identical transaction queued up.

In practice, what they *really* want to do, is to re-submit that transaction with the same nonce and higher gas, but it's a common mistake!

We could detect when a new transaction appears to be a retry (parameter wise, ie `to`, `value`, `data`), and warn the user, or even suggest "Are you trying to speed up your last transaction?", and redirect to the speed-up flow instead of sending a new transaction.

**Comment by woodydeck** [comment]
Just to shed light on another context; I came across this potential problem when testing my backend for processing withdrawals. 
![Screen Shot 2020-01-22 at 8 26 18 PM](https://user-images.githubusercontent.com/13375011/72949163-80c30380-3d55-11ea-9783-711b0229f3d2.png)
When you click the "Process" button it could of course execute the send Tx serverside and be seamless for dupe checking, however this means you can't use a HW wallet. Doing it on the frontend though opens the possibility to accidentally paying someone twice.

The solution is basically the same as suggested in OP, where I just keep recent row IDs in an array in memory and stop it that way by checking each button click.

**Comment by bschorchit** [comment]
Closing in favor of: https://github.com/MetaMask/MetaMask-planning/issues/3043
