### ISSUE TITLE
Chrome extension issue in block-chain transaction

### ISSUE THREAD

**Issue by jasham** [MetaMask/metamask-extension#4198]
Basically I want a chrome extension which takes data from block-chain and display in chrome content-script also when user click on that data one transaction happen which will increase the count in block-chain.

I am able to retrieve data from block-chain please check the below code.

```
async componentDidMount(){
    const ads = await advertiserAbi.methods
                     .getSpecificAdvertiserDetail(
                     "any address").call();
    this.setState({ads});
}
```
But the problem is coming in performing transaction. Please check the below code.

```
async onSubmitForUpdate() {
    console.log("Hello");
    await userAbi.methods
      .setStatistics("any address")
      .send({
      from: "any address"
    });
}
```
Below is the error which I am getting when checked in console.

```
POST https://rinkeby.infura.io/<--specific address--> 405 ()

Uncaught (in promise) Error: Invalid JSON RPC response: ""
at Object.InvalidResponse (content.js:108391)
at XMLHttpRequest.request.onreadystatechange `(content.js:119211)```
```

**Comment by danfinlay** [comment]
Are you making a chrome extension?

Currently chrome extensions are not able to call MetaMask methods, and so you are probably connecting to an RPC API provider directly, and calling `sendTransaction` on it. These RPC APIs usually do not hold accounts, and so you're getting a failure.

You are probably waiting for #3997 to get merged and published, to make a metamask-powered browser extension.

**Comment by jasham** [comment]
Thanks Dan I was looking for the same.
