### ISSUE TITLE
Proxy.js not found

### ISSUE THREAD

**Issue by pranay01** [MetaMask/metamask-extension#4200]
mascara/proxy/index.html  refers to proxy.js - but there is no such file in the entire metamask-extension repository. This leads to a not found error at run time. How can this be resolved?

![screen shot 2018-05-06 at 4 58 02 pm](https://user-images.githubusercontent.com/504541/39672794-b44a5086-514e-11e8-8613-4ec8bc935248.jpg)

**Comment by pranay01** [comment]
Found proxy.js in src app folder in mascara

**Comment by wh78garcia** [comment]
hello，I got the same problem, do you solve it?
