### ISSUE TITLE
UX: Sending ETH losses state with focus

### ISSUE THREAD

**Issue by mryellow** [MetaMask/metamask-extension#4206]
UX failure 1:

* Open MetaMask
* Send
* Paste address
* Take focus to browser for more copying
* Open MetakMask
* Click Send again (Why?)
* Address is gone.

Same process, with amount field, behaves differently:

* Open MetaMask
* Send
* Paste amount
* Take focus to browser for more copying
* Open MetakMask
* Click Send again (Why?)
* Amount remains.

There should be no clicking of "Send" again, MetaMask should already be displaying the send form with any information previously entered.

Same thing happens on the next page with `gasPrice`.

* Click Next
* Adjust `gasPrice`
* Take focus to browser for more copying
* Open MetaMask
* `gasPrice` has been reset to `1`

**Comment by CryptoLibertus** [comment]
I second this.

**Comment by danjm** [comment]
@mryellow Is this on the old-ui or new ui (beta)?

**Comment by mryellow** [comment]
Old-ui.

**Comment by bdresser** [comment]
actually applies to the new UI as well.

if possible, we should persist state so the "send" flow remains in the state it was left

**Comment by kwikiel** [comment]
This is absolutely infuriating as one usually wants to double check both amount and recipient eth address.  Is this a bug or is this for security feature?

**Comment by bdresser** [comment]
We recommend opening the Send screen as a full tab for this exact reason. We may make this default behavior in an upcoming release.

**Comment by bdresser** [comment]
Going to close this & consolidate with the more general  https://github.com/MetaMask/metamask-extension/issues/5657, we'll update there
