### ISSUE TITLE
Unhandled Promise rejection when running Mascara

### ISSUE THREAD

**Issue by pranay01** [MetaMask/metamask-extension#4209]
I am working with develop branch. I am trying to run mascara

After going through instructions, I run 
`npm run mascara`

This starts 2 servers at 9001 and 9002 port. The server on 9001 runs fine. I have a version on Metamascara alpha running on it. I create an account in Metamascara Alpha and then start localhost:9002  and then get a Unhandled promise rejection error. In the web page I get only Get Account and Send Transaction error, and nothing happens on pressing it. 

I have tried in 
Safari Version 11.1 (13605.1.33.1.4)
Firefox 59.0.2 (64 bit)
and Chrome Version 66.0.3359.139

I am running macOS High Sierra - Version 66.0.3359.139

Below is a screenshot of error from Firefox
![screen shot 2018-05-07 at 4 59 07 pm](https://user-images.githubusercontent.com/504541/39699892-ccc24554-5218-11e8-9851-df68506d02f3.jpg)

**Comment by bdresser** [comment]
We no longer actively maintain the Mascara project.

**Comment by wh78garcia** [comment]
@pranay01 hello，I want to know if you solve this problem??
