### ISSUE TITLE
Find out how this user would generate an owned account

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4212]
A user on Twitter user `@tomislavmamic` reports they generated an account with ether on it:
https://twitter.com/tomislavmamic/status/993471509602668544

They also say they've successfully identified & contacted the owner of the original account.

They say it wasn't the first account MetaMask gave them, which makes me think:
- Since usually people use their first account, the first account is usually the one with ether.
- This may not be _the other person's_ account in the same mnemonic order.
- There could be a bug in the bip39 spec. (we've seen it before).

We should investigate this and figure out exactly what happened. `tomislavmamic` suspects RNG issues, [so we should investigate that, but it seems unlikely](https://github.com/MetaMask/metamask-extension/issues/4210).

**Comment by mryellow** [comment]
"Create account" ends up over here in `hdkey.deriveChild()` best I can figure:

https://github.com/cryptocoinjs/hdkey/blob/61c511b1cc6d9ed178fd917f8c7265f186a587d2/lib/hdkey.js#L96

**Comment by lastperson** [comment]
After an investigation it came up that the very same address was generated by the same metamask instance 2 weeks before. Here is the answer from the reporter:

> That must be it. But weird, when I pressed Create new account on MetaMask it switched to Account number 7 and I thought it was a new account. Sorry for the false alarm.

**Comment by danfinlay** [comment]
The user who reported this issue has discovered their experience was a fluke, they had made a mistake and misunderstood what happened!

https://twitter.com/tomislavmamic/status/993777588488294400

Closing... FOR NOW!!!  (Always let us know if something seemingly impossible happens, so we can ensure it stays impossible).
