### ISSUE TITLE
[NewUI] Gas Price Edit Button overlaps ETH denomination on Confirm Transactions Notification/Popup

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#4213]
The button to navigate to the Gas Edit Screen on the Confirm Transaction Screen overlaps the ETH denomination.

![screenshot from 2018-05-07 10-56-26](https://user-images.githubusercontent.com/13376180/39716639-c552f2a6-51e5-11e8-85f9-899f074e64bf.png)

**Comment by danjm** [comment]
This should be fixed on develop. @tmashuang can you confirm?

**Comment by bdresser** [comment]
@danjm yes i see it fixed on develop 👍
