### ISSUE TITLE
Stuck on "Connecting to Unknown Private Network"

### ISSUE THREAD

**Issue by johncrisostomo** [MetaMask/metamask-extension#4219]
I am connecting to a PrivateNet on a different computer. The weird thing here is that it can actually connect without any errors on the log, but the spinner won't close. Even the ether is correctly being updated under the "Connecting to Unknown Private Network" overlay. Another odd thing here is I cannot connect using a browser on the local PC where `geth` is running. Another piece of information that isolates possible networking issues is that I have Mist installed on both computers and can connect to the chain without any problems.
 
**Expected Behavior**
MetaMask's "Connecting to Unknown Private Network" should disappear after connecting to custom RPC.

**Actual Behavior**
Loading spinner shows infinitely despite having a good connection

**Browser Used**
- Chrome v66.0.3359.139 and Brave v0.22.669 on MacOS 10.13.4
- Chrome v66.0.3359.139 on Windows 7

**Operating System Used**
- MacOS 10.13.4
- Windows 7 

**Screenshots**
<img width="395" alt="screen shot 2018-05-08 at 1 23 46 pm" src="https://user-images.githubusercontent.com/240522/39739347-0f63e20a-52c3-11e8-985e-e21d2b959b05.png">
<img width="834" alt="screen shot 2018-05-08 at 1 25 58 pm" src="https://user-images.githubusercontent.com/240522/39739435-69c8745e-52c3-11e8-86e0-4334a383dd16.png">
 **Troubleshooting Steps Done**
1. Restart browsers
2. Uninstalled / installed MetaMask
3. Tried other browsers (such as Brave)
4. Start PrivateNet again, making sure `rpccorsdomain` is provided and making sure networkid is consistent with the Chain ID on genesis file.

**Comment by johncrisostomo** [comment]
I'm closing this because I also don't understand why this is happening. But a different set of flags upon spinning up the `geth` instance "fixed" it. If someone chanced upon this in the future just leave a comment then let's try to troubleshoot your `geth` flags.

**Comment by nageshvcommandgithub** [comment]
Hi, I am facing the exact right problem mentioned above. I am trying to connect to a Ethernet RPC on Azure and when I connect to that RPC from Meta mask, 'Connecting to Unknown Private network' is spinning all day long. Can you please let me know how can I connect to the new RPC.

**Comment by johncrisostomo** [comment]
Hello @nageshvcommandgithub , can you share your `geth` command that you ran on Azure? Also, can you connect to it through Mist?
