### ISSUE TITLE
Reinstalled Chrome...Now Metamask data gone!

### ISSUE THREAD

**Issue by rayj00** [MetaMask/metamask-extension#4223]
So I was having issues with Chrome and showing a live streaming video player webpage.   
The video would only show if I was in the Dev Tools Console after I did a refresh of he page!  I know, weird.
But it is reproducible.   The live video is viewable in Firefox with no problems.

I could not figure out the problem so I uninstalled and re-installed.   I must say this new way of signing in to Chrome sucks.  But anyway, now my Metamask is gone!  I re-installed the extension and now it thinks I am a new user!   Is all of my ethereum data gone now?

**Comment by bwheeler96** [comment]
@rayj00 did you copy down your seed file like it told you to when configuring your initial account?

**Comment by bwheeler96** [comment]
@rayj00 Well that might be a problem then.

If you're luck metamask might store the data in the system keychain in which case you would just need to remember your password. I'm not a core dev, but one of those guys should be able to help you.

**Comment by rayj00** [comment]
Well, it was suggested that I use the 12 secret words that I had and just keep trying to create accounts.  The one I was interested in popped up after 4 attempts!   So all is fine!
