### ISSUE TITLE
Eth JSON RPC: Support cancelation

### ISSUE THREAD

**Issue by safareli** [MetaMask/metamask-extension#4225]
Would be nice if sencAsync returned something like `XMLHttpRequest` object so once can abort the request (like [XMLHttpRequest.abort()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort)).  

I guess this would be blocked until https://github.com/kumavis/json-rpc-engine/issues/4 is fixed

**Comment by kumavis** [comment]
this would be a change to the standard ethereum JSON-RPC spec, goes a bit beyond a feature request in metamask

what is your primary usecase and what sort of calls are you interested in canceling?

**Comment by safareli** [comment]
If you are referring to [ethereum/wiki/JSON-RPC](https://github.com/ethereum/wiki/wiki/JSON-RPC) by "standard ethereum JSON-RPC spec" then I don't see how this request would result in change of that spec, can you clarify?

`sencAsync` at this moment is not returning any value. and I was proposing to to return underling XMLHttpRequest so one can `.abort()` that, if client is not interested in result of the call and free up enquired resources.

Exposing `XMLHttpRequest` might not be the best as transport layer might change or something, so some object with a `cancel` or `abort` method might be much better.

**Comment by safareli** [comment]
For reference this is was just merged in web3.js
https://github.com/ethereum/web3.js/pull/1618

**Comment by danfinlay** [comment]
This would be something to add to the provider API, so now part of EIP-1193.

**Comment by danfinlay** [comment]
The simpler path to this is probably to add an RPC method for requesting the cancellation of a pending transaction, rather than modifying the provider interface.

Since a provider change is huge in scope and either path would require a standard (EIP or ethereum-magicians post) I'm closing this until a suitable proposal is drafted.
