### ISSUE TITLE
Extension keeps forgetting my tokens

### ISSUE THREAD

**Issue by PaznerA** [MetaMask/metamask-extension#4228]
Hi, 
I did not found this issue, so I'm opening new...
Same as this post: [](https://bitcoin.stackexchange.com/questions/74840/metamask-keeps-forgetting-my-tokens)

Every day, after login, all my added tokens are gone.
Can this problem block my incoming payment? If so, i can't stay with this "wallet"

**Comment by dsilletti** [comment]
Same problem here (Google Chrome 66.0.3359.170, MacOS High Sierra 10.13.4) often I need to add some tokens again. (BTW @PaznerA this this will not affect your incoming payments, the tokens are only hidden)
