### ISSUE TITLE
"Generating transaction" load screen.

### ISSUE THREAD

**Issue by snakeKings** [MetaMask/metamask-extension#4230]
Hi everybody. I  have a problem with Meta Mask. I just see a "Generating transaction" load screen.
I wait more than 10 minutes - but still loading.
What can I do?

Thanks for help

![screenshoth generating transaction issue](https://user-images.githubusercontent.com/39128709/39820681-ab9ad6f4-53a6-11e8-9654-870088a0c637.png)

**Comment by mechtholdrings** [comment]
I got this support from meta mask, so it seems that it is a bug.
Do you have a bug bounty?

"Please first of all make sure that you have your seed phrase backed up in paper and stored in a safe place. Also, if you have any imported accounts, please also make sure to back up those addresses' private keys.

If you've named the accounts, you can also copy those names so you are able to rename them again once you've restored from the seed phrase.

Then can you please try removing the browser extension and installing it again from https://metamask.io/ 

After completing the reinstall, you can use the Restore from seed phrase button, this would let you use your recovery seed phrase and set a new password for this new MetaMask installation.

By now you would only need to re-CREATE the accounts if you had several of them setup in your previous MetaMask instance, and import the private keys of the addresses you had as IMPORTED accounts before.

If the issue persists or if you need further assistance, don't hesitate on letting me know."

**Comment by ChicoBitcoinJoe** [comment]
This happened to me and it looks like I will need to reinstall MetaMask as well.
I'd like to point out that you can disable metamask and reenable it and the login screen will appear, if you switch networks it will work fine until you switch back to the effected network (in my case kovan).

**Comment by spiritss** [comment]
@mechtholdrings I have the same issue, was your problem solved after following those steps?

**Comment by mechtholdrings** [comment]
Yes, it helped. :-)

**Comment by spiritss** [comment]
@mechtholdrings thanks for letting me know! Also, when you reinstalled and restored from the seed phrase, was the transaction in question remaining in the metamask wallet?  or did you find that it went through?

(Sorry for such noob questions, I'm very new to metamask!)

**Comment by r3lax** [comment]
You can try this in Chrome: Go to More Tools -> Extensions -> Metamask

     - Disable MetaMask
     - Turn on Developer Mode (top right)
     - Click Update
     - Turn Off Developer Mode (top right)
     - Enable MetaMask

Log back in (I logged into a test network before switching back to main)
This resolved the issue for me; interested to know if it worked for anybody else.

**Comment by bdresser** [comment]
consolidating to #4264
