### ISSUE TITLE
Smartcontract interaction transparency

### ISSUE THREAD

**Issue by gernotpokorny** [MetaMask/metamask-extension#4234]
When a user for example interacts with a smart contract and is prompted to confirm the tx in my opinion he should see the details of the function call just in case the site was malicious and altered the inputs. 

For example lets say you interact with the KyberNetwork smart contract. In the trade function you have to set the destAddress where the funds should go. 

```
function trade( ERC20 source, uint srcAmount,
                    ERC20 dest, address destAddress, uint maxDestAmount,
                    uint minConversionRate,
                    bool throwOnFailure )
```

At the moment you cannot spot with Metamask if the site is about to make a malicous function call by not taking your inputs as function arguments, but using malicous arguments.

**Comment by prettymuchbryce** [comment]
Strong +1

Currently it's possible to approve a transaction which looks to be a transaction from your address to an ERC20 smart contract. Even if these addresses are legitimate, the function call could be to the `approve` function and the data payload could be setting approval to a malicious contract, which could be stealing all of your tokens.

Currently it's not even possible to look at the data payload and confirm these details.

Furthermore, it should be possible for MetaMask to understand that the receiving address is an ERC20 contract and show a special UX flow for something like granting approval.

**Comment by bdresser** [comment]
We now include a `data` tab as part of the confirmation screen. If the function name is included in the parity on-chain function registry, we include that as well:

<img width="438" alt="screen shot 2018-10-15 at 3 54 02 pm" src="https://user-images.githubusercontent.com/1016190/46982818-b8db9100-d092-11e8-898f-ff66d968414c.png">

**Comment by fxfrnk** [comment]
Would it be possible to reopen this? There still seems to be a lack of transparency with some smart contract interactions. 

For example, when going to uniswap.exchange to swap tokens, the confirmation screen does not show what tokens and how many are going to be transferred unless you're swapping eth from your wallet.
![image](https://user-images.githubusercontent.com/11490430/79005141-42530e80-7b24-11ea-9082-b8df6a6164e0.png)

The data tab also does not show a reference to the type of tokens or how many.
![image](https://user-images.githubusercontent.com/11490430/79005236-66aeeb00-7b24-11ea-9374-f43066425195.png)

------------------------------
support reference: 33363
