### ISSUE TITLE
Currency Swapper

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4238]
Inputting an exact fiat value with ETH is difficult. Let's add a swapper to the amount field in the send screen. 

![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/585d1bc6-f2e8-4087-958d-d40caaa2623a)

**Comment by cjeria** [comment]
Let's keep it and use it to measure how people calculate amounts they want to send. This could help us understand how people think (do they think in Fiat, or do they think in ETH?) 

The default could be set to whatever the user set the main currency in settings, but they can freely toggle the currency without it affecting the main currency that was set in settings.

**Comment by whymarrh** [comment]
Fixed with #6091
