### ISSUE TITLE
Import Account Via JSON

### ISSUE THREAD

**Issue by Minnesotans** [MetaMask/metamask-extension#4243]
Hello,

I am experiencing an issue importing an account and am unsure if recovery is possible. All I have is the MetaMask State Logs.json file that I downloaded when I made the account. I thought this was the basic recovery file so kept it safe, however I cant seem to recover the account with this. Since then I've realized I should have downloaded the private key UTC file, sadly I did not.

1. Problem -> MetaMask Error: "Not a V3 Wallet" 

2. What I have -> MetaMask State Logs.json file and the password 

Is there any method for this to be imported as I do not have the private key for this account?

Thank you!

**Comment by alacrity26** [comment]
@Minnesotans for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
