### ISSUE TITLE
i need to know my wallets address 

### ISSUE THREAD

**Issue by jellybeancs74** [MetaMask/metamask-extension#4244]

**Comment by tincampi** [comment]
https://i.gyazo.com/af53648ef3397f456e4952d81f213b85.png ...

**Comment by alacrity26** [comment]
@jellybeancs74 for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
