### ISSUE TITLE
Seed Phrase Recovery 

### ISSUE THREAD

**Issue by NociremA** [MetaMask/metamask-extension#4246]
Hello,

I just tried MetaMask on a new computer and may have really messed up. I tried to log on my MetaMask account with my seed phrase and password. Doing so seems to have created a separate account instead of signing me into my account.

I was pretty tired working late when I made this mistake. MetaMask gave me a new seed phrase which I thought was odd, and then I did something stupid...I copied and pasted the new seed phrase over my original seed phrase without another backup of the original phrase, tiredly thinking that logging on a new device may have just given me a new phrase. After that I realized that I was logged into a brand new wallet and without my original seed phrase or private key I'm out a well...my life savings I suppose. 

Any possible way to recover the original account?

**Comment by alacrity26** [comment]
@NociremA for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by martineezz** [comment]
@NociremA If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by darkwing** [comment]
Please do not contact the email cited, it is a scammer that will try to get your recovery phrase.
