### ISSUE TITLE
Inability to withdraw funds / Tx can't be found loop.

### ISSUE THREAD

**Issue by tincampi** [MetaMask/metamask-extension#4247]
So, after looking around I found out multiple people have had this issue. 

I tried to send a transaction with metamask. Between the acceptance of that transaction and the actual transaction, my ethereum dissapeared from my account due to a buy/sell function on eg. Etherdelta. That transaction is now trying to send nonexistant ether to an address, which causes the entire address to be unable to do anything.

I've now been unable to withdraw any tokens / do anything with my address except for signing contracts for a couple of days now. The transaction is still stuck.

This leads to a friendly "Sorry, We are unable to locate the Transaction Hash" on etherscan."

https://i.gyazo.com/935b7208773f6407981416dabd21b827.png

Is there any solution to this? Some guy recommended resending the same transaction, with a higher gas limit, but that'd require another x eth to retry the transaction. My funds are stucked in Forkdelta's contract, out of which I can't get them.

https://github.com/MetaMask/metamask-extension/issues/2657

Browser Used
Chrome, Firefox (doesn't work on fresh install on both)
Operating System Used
MacOS 10.12.6

**Comment by alacrity26** [comment]
@tincampi for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
