### ISSUE TITLE
Metamask unable to restore from seed phrase

### ISSUE THREAD

**Issue by byosofi** [MetaMask/metamask-extension#4248]
Hello,

Recently my laptop in which I had installed Metamask crashed. I tried to restore my Metamask account on another device with the seed phrase. Luckily I was able to restore my account, but it says there are no tokens found. After reading on the internet I tried to use the 'Create a new Account' function without any success. Anyone able to help me? I had a lot of money in there and now all is lost, as it seems. At the moment I'm logged in into Metamask with my account with the right address, but again no tokens anymore (I can only view them in etherscan). Is there any possibility I can add my tokens again in into my account by using the 'Add token' function? I would appreciate some help, thanks.

**Comment by alacrity26** [comment]
@byosofi for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue
