### ISSUE TITLE
Tracking vulnerability

### ISSUE THREAD

**Issue by rumkin** [MetaMask/metamask-extension#4257]
Metamask extension provides access to ethereum address to every site and it's not clear to users. Users should be warned about this opportunity. This is more vulnerability than feature. It could be used for social engineering attacks very easy and It's nearly impossible to detect the source of such attack. 

 Possible solutions:

- Switcher to enable/disable metamask injection right in the extension popup.
- Automatic metamask disabling after timeout.
- Special notification warning. 

Please take this seriously.

**Comment by Zanibas** [comment]
We are taking this seriously. Please see: https://github.com/MetaMask/metamask-extension/issues/3930

**Comment by rumkin** [comment]
Task that you provided is enhancement and still in progress since April till now. That's why I wrote "Please take this seriously".

This information should be published on your site and in extension. You ought to inform your users about vulnerabilities. Especially if you cannot fix it immediately.
