### ISSUE TITLE
Can not withdraw Eth.

### ISSUE THREAD

**Issue by gopherpig** [MetaMask/metamask-extension#4258]
I have chrome extension. I have not been able to send eth for the last three days. I usaully get a fail or it just says sorry cant find transaction. I have uped the gas and still nothing. using version 4.6.1. Is there an issue with the wallet? I have never had problems before.

BEFORE SUBMITTING, please make sure your question hasn't been answered in our support center: https://support.metamask.io
Common questions such as "Where is my ether?" or "Where did my tokens go?" are answered there.

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by bdresser** [comment]
@gopherpig please email support@metamask.io with a copy of your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI)
