### ISSUE TITLE
Change Log in/Log out to Unlock/Lock

### ISSUE THREAD

**Issue by alextsg** [MetaMask/metamask-extension#4259]
In unlock screen, account dropdown, etc.

**Comment by alextsg** [comment]
Oh, this was from a comment from @cjeria for one of my PRs: https://github.com/MetaMask/metamask-extension/pull/4190#issuecomment-386931877
I had forgotten the terminology we decided so I created this issue.

**Comment by cjeria** [comment]
Ah, thanks @Zanibas for referencing that issue and what we decided on. We can close this issue out and go with log in/log out
