### ISSUE TITLE
Stuck on "Generating transaction" load screen

### ISSUE THREAD

**Issue by RomanFro** [MetaMask/metamask-extension#4264]
**Expected Behavior:**
Access to my wallet
**Actual Behavior:**
![Generating transaction forever](https://image.ibb.co/maV1ty/Screen_Shot_2018_05_16_at_3_45_23_PM.png)
![Generating transaction forever](https://preview.ibb.co/cPzGRJ/Screen_Shot_2018_05_16_at_3_46_16_PM.png)
**Browser Used:**
Chrome Version 66.0.3359.139 (Official Build) (64-bit)
**Operating System Used:**
macOS Sierra Version 10.12.6

**Comment by r3lax** [comment]
You can try this in Chrome: Go to More Tools -> Extensions -> Metamask

     - Disable MetaMask
     - Turn on Developer Mode (top right)
     - Click Update
     - Turn Off Developer Mode (top right)
     - Enable MetaMask

Log back in (I logged into a test network before switching back to main)
This resolved the issue for me; interested to know if it worked for anybody else.

**Comment by Vasetoo0** [comment]
Guys i fixed it.
First yo do these steps:
 - Disable MetaMask
 - Turn on Developer Mode (top right)
 - Click Update
 - Turn Off Developer Mode (top right)
 - Enable MetaMask

Then you dont log in , but switch with the classic view of MetaMask. Then log in and you can reject the stuck transaction from there!! 
This is it . Hope i can help!

**Comment by tmashuang** [comment]
What was the interaction that lead to this issue? Obviously it was a generating a transaction, but was it a tx from within MetaMask or a Dapp initiated one? If from a Dapp, which Dapp?

**Comment by RomanFro** [comment]
@tmashuang I can't say for sure now, as it was 24 days ago, but most probably tx was generated in MEW. In old design it was just generating tx without blocking the interface, but when you have such tx and switch to beta interface everything get stuck like on the screenshot provided above.

**Comment by bdresser** [comment]
anyone seen this recently? reports of this issue have died down significantly in the past ~3 months - let me know if I may close this.

**Comment by kalistace** [comment]
Just happened to me. 

version 5.0.2. Tried the above workaround but it takes me the loading page as soon as I log in again. Not sure how to switch to "classic view" ?

**Comment by bdresser** [comment]
Checking back in - anyone seen this on a version after 6.0?

**Comment by tmashuang** [comment]
Closing if anyone else finds themselves here contact us as https://support.metamask.io.
