### ISSUE TITLE
ETH balance is 0ETH even though I have lots of tokens in Metamask 

### ISSUE THREAD

**Issue by MichaelPtacek** [MetaMask/metamask-extension#4265]
Hello, I am using Metamask for storing Tron (TRC) and Signals tokens (SGN) I see these tokens in my Metamask account after logging in, however I cannot send them to an exchange as Metamask shows my ETH balance is 0. Any idea why is that?

Thank you

**Comment by alacrity26** [comment]
@MichaelPtacek for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

https://metamask.helpscoutdocs.com/article/54-how-to-download-state-logs-new-ui
