### ISSUE TITLE
Transaction Hash No Longer Exists

### ISSUE THREAD

**Issue by jack-crypter** [MetaMask/metamask-extension#4268]
So about 2 days ago I tried to send 2 ETH to a friend's address.  As of this morning, it was still "pending" Now the transaction reads as follows: <!-Sorry, we are unable to locate this Transaction Hash.  Here is the trx hash: -0x2d902410479e75435c58fd592b332dbf79414899d3299ca1bf1f1154d56aa7be.  Can anyone help me locate my 2 ETH?

BEFORE SUBMITTING, please make sure your question hasn't been answered in our support center: https://support.metamask.io
Common questions such as "Where is my ether?" or "Where did my tokens go?" are answered there.

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by alacrity26** [comment]
@jack-crypter for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

https://metamask.helpscoutdocs.com/article/54-how-to-download-state-logs-new-ui
