### ISSUE TITLE
Privacy Proposal

### ISSUE THREAD

**Issue by sullof** [MetaMask/metamask-extension#4269]
I am building [Tweedentity](https://tweedentity.com), an identity system based on Twitter and Ethereum. This would allow people to log in DApps without username and password, but just showing the DApp that they are the owner of that Twitter account.
The big problem using Metamask is that when it is active, it injects web3 and users' info in any tab. This does not allow the users to decide which DApp can see their info and which app can't.
There is also a security issue because when a tab intercepts my wallet, the tab can generate a transaction hoping that I submit it inadvertently.
Is there any plan to add a settable option that requires an explicit approval before injecting web3 in a specific tab?

**Comment by bdresser** [comment]
thanks @sullof - we're aware and taking steps towards a full solution tracked in #714
