### ISSUE TITLE
Brave handles i18n API differently and sometimes cannot open until fixed

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4270]
Some time after version 4.3, MetaMask's view size seems to have changed, and broken with the Brave browser:
https://github.com/brave/browser-laptop/issues/14122

To reproduce, we will need to build a local version of Brave with the extension installed. The last time I went through that process I produced this guide to doing it:
https://medium.com/metamask/building-metamask-into-brave-838d616dd93f

The Brave team cannot update MetaMask on their platform until we resolve this.

**Comment by danfinlay** [comment]
We believe this may be related to the i18n API.

**Comment by danfinlay** [comment]
From Brave:

Looks like we still have an issue with MetaMask in Brave, @kumavis. As it turns out, we do expose both the `chrome.i18n.` namespace, as well as the `getAcceptedLanguages` method. Unfortunately, this method isn't fully implemented. Calling it will throw an exception. The exception only appears to be thrown when you don't evaluate `chrome.runtime.lastError` in the callback. If you evaluate _lastError_, no exception is thrown.

```
chrome.i18n.getAcceptLanguages( e => {
  if (chrome.runtime.lastError) return;
  console.log( e )
})
```

In Chrome, this logs an _array_. In Brave, it logs _undefined_. If you remove the evaluation of `chrome.runtime.lastError`, an exception is thrown. (edited)
I'm working with one of our devs to get this feature implemented (if even as a stub that yields `['en-US', 'en']` when called. But for now, MetaMask could remove the feature-detection, and instead add a call to `chrome.runtime.lastError` to resolve the popup-window in Brave.
You could even wrap it in a try...catch:
```
let isSupported;
try {
  chrome.i18n.getAcceptLanguages(e => {
    isSupported = true
  })
} catch (e) {
  isSupported = false
}
```

**Comment by danfinlay** [comment]
May be the cause of #4281.

**Comment by jennypollack** [comment]
Can repro in latest Brave mm (v4.3.0) by setting language preferences to language other than English (U.S)
