### ISSUE TITLE
Help please ASAP!!!!! MetaMask Extension Older UI - Where did my XYO tokens go?!

### ISSUE THREAD

**Issue by ndavis10al** [MetaMask/metamask-extension#4274]
Purchased XYO tokens and they loaded into meta mask wallet when I added the tokens 2 days ago. Now MetaMask shows no tokens even added and when I add the tokens same way i did right after purchasing, the balance doesn't load and just shows 0 tokens. When I check both ethplorer and etherscan, it shows my MetaMask wallet address as the owner with the correct balance of XYO Tokens purchased. If anyone can help, the wallet address is: 0x10671B18A7c566B4C7e8C5082Bb523D8168Ac45A to check everything on etherscan or ethplorer in case ive overlooked something

**Comment by danfinlay** [comment]
Please email our support staff at support@metamask.io
