### ISSUE TITLE
Add migrations before e2e tests

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4283]
An issue discovered in #4034 would have been caught if we ran a series of migrations before running our e2e tests (effectively including migrations as part of our e2e tests).

We should be able to pretty much copy-paste some of our migration test code before at least one suite of e2e tests, and that would automatically detect some class of migration errors.

**Comment by kumavis** [comment]
e2e runs built prod, so it runs migrations (over a new empty vault)
we also run our migrations in unit tests
