### ISSUE TITLE
Cannot import Private Key Using JSON file it says Unexpected token b in JSON at position 0

### ISSUE THREAD

**Issue by 2i101y1** [MetaMask/metamask-extension#4284]
Hi, i reset my PC and now i want to restore/import my metamask private key. But, when i try to import the JSON file which i have saved. it shows me an error Unexpected token b in JSON at position 0. 

I don't know what is this all about?

**Comment by JohnAllen** [comment]
Is the first character in your keystore file a double quote: `"`?  Or is it just a private key?  If you're importing a keystore/json file, well that is more than just a private key.

Are you sure you selected the right option: `private key` and not `JSON file` if you just have your private key in this file?  Actually when importing just a private key I'm pretty sure you just paste the private key.

**Comment by bdresser** [comment]
@2i101y1 if you're still having an issue, please email support@metamask.io!
