### ISSUE TITLE
Metamask not processing any transactions

### ISSUE THREAD

**Issue by JupiterJazz1988** [MetaMask/metamask-extension#4289]
24 hours ago I sent some ether to ForkDelta.  It was my first time using that exchange.  The transaction never completed and doesn't seem to be making any progress, and since that time, I haven't been able to process any transaction at all from my Metamask wallet.  If I try to send ether to another exchange (like binance or kucoin) or back to one of my other wallets, it just doesn't work at all.  When I try to do it and check the Etherscan, I get the message: "Sorry, we are unable to locate this Transaction Hash."  
I apologize if this question is in the wrong place or if it's already answered somewhere.  I am new to this space and only been involved in cryptocurrency for 1 month.  
I'm using Windows 10 and Google Chrome.

**Comment by alacrity26** [comment]
@JupiterJazz1988 for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

https://metamask.helpscoutdocs.com/article/54-how-to-download-state-logs-new-ui
