### ISSUE TITLE
Cannot get past 12 seed words

### ISSUE THREAD

**Issue by NZKrypto** [MetaMask/metamask-extension#4290]

**Comment by alacrity26** [comment]
@NZKrypto for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

https://metamask.helpscoutdocs.com/article/54-how-to-download-state-logs-new-ui
