### ISSUE TITLE
Send Eth to Blank Adress Created a Contract?

### ISSUE THREAD

**Issue by levyashin1** [MetaMask/metamask-extension#4291]
Today i accidentally put the address in the memo line and left the recipient address part empty.

  *  Expected Behavior - No transaction.
  *  Actual Behavior -  It created and contract and my eth is there now.
  *  Browser Used - Chrome

Here is the tx of the incident. https://etherscan.io/tx/0x0dbec3c3f7659c9ad5cd67c25b02f85fd5579b53db6044c806fbc58ee6f0da78

If anyone tells me how to claim it back. That would be marvelous :(

**Comment by bdresser** [comment]
@levyashin1 please reach out to support@metamask.io with a copy of your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI-)
