### ISSUE TITLE
Error: Token Balance Lookup Failure

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#4294]
https://sentry.io/metamask/metamask/issues/540400626/

```
Error: [ethjs-rpc] rpc error with payload {"id":3322843147836,"jsonrpc":"2.0","params":[{"to":"0xf3e014fe81267870624132ef3a646b8e83853a96","data":"0x70a08231000000000000000000000000e8429c87d5661cf8ab581d0f49419d470784534c"},"latest"],"method":"eth_call"} null
  at None (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:844579)
  at None (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2050166)
  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1408324)
```

**Comment by kumavis** [comment]
This request is a balance lookup `balanceOf(address)`
https://www.4byte.directory/signatures/?bytes4_signature=0x70a08231

the request itself is fine, so my guess is that our infura middleware is not handling some type of request failure
```
curl -d '{"id":3322843147836,"jsonrpc":"2.0","params":[{"to":"0xf3e014fe81267870624132ef3a646b8e83853a96","data":"0x70a08231000000000000000000000000e8429c87d5661cf8ab581d0f49419d470784534c"},"latest"],"method":"eth_call"}' https://mainnet.infura.io/
```

I also investigated the `ethjs-rpc` error message to determine why it was not very helpful
The error message is built here https://github.com/ethjs/ethjs-rpc/blob/master/src/index.js#L50

It seems to imply that `responseObject.error` is truthy and either
- `err` is truthy and `String(err) === 'null'`
- `JSON.stringify(responseObject.error) === 'null'`

both of which seem unlikely. One possible case is that `err === 'null'` (the string).

**Comment by kumavis** [comment]
There's also a bunch of **warnings** for `TypeError: Cannot read property 'includes' of undefined`, which should prolly be errors. not sure why they are warnings.

**Comment by bdresser** [comment]
@kumavis looks like this has really died off in the last couple weeks - hasn't been seen since 4.6.1. good to close?
