### ISSUE TITLE
Ensure other extensions cannot snoop our data.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4296]
In [this comment](https://github.com/MetaMask/metamask-extension/issues/2749#issuecomment-390328007) I realized that extensions like [Storage Area Explorer](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb?hl=en) allow users to view their vault data. This implies access to vault data.

We need to investigate this and make sure we are doing everything we can to prevent other extensions from accessing user data.

**Comment by bdresser** [comment]
is this possible without opening the inspector?

**Comment by Gudahtt** [comment]
I've investigated this, and I don't think there is any cause for concern. The `Storage Area Explorer` extension doesn't _directly_ access extension storage - it allows the _user_ to more easily see stored data when opening dev tools on a Chrome extension page. There isn't even any cross-origin data access - the user has to open dev tools _directly_ on the extension page. They could already access data by that point using `chrome.storage.local`.

Additionally, the encrypted vault data is also stored on disk and is fairly easy to find and recover on all browsers. We have a support article guide for doing exactly this, for users that want to extract their vault for whatever reason. This can't be a layer of security we depend on - not even as an inconvenience to attackers.

This extension doesn't appear to be any more threatening than the risk of _any_ malware a user might have installed on their machine, nor do I believe it warrants any mitigation. We rely upon encryption to keep the vault safe; we can't do much to mitigate the risk of local malware obtaining this encrypted data. If we're concerned about this risk, I think it would be a better use of our time to consider enhancements to the "choose password" screen to encourage better password use, and considering improvements to how we're encrypting data.
