### ISSUE TITLE
NewUI: Show eth values on confirm screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4298]
User reported the eth value of a transfer isn't reflected on the NewUI confirm screen. We should definitely still show ether. Does our design not include ether value? @cjeria 

![image 2](https://user-images.githubusercontent.com/542863/40258104-50161734-5aa5-11e8-8ff7-0193b76acf86.png)

**Comment by cjeria** [comment]
We do show it, but user needs to scroll to the bottom to see it (see screenshot). This is on our radar to fix asap. @danfinlay 

![image](https://user-images.githubusercontent.com/597770/40258214-ac219da0-5aa5-11e8-8736-a3dfca6992d0.png)

**Comment by cjeria** [comment]
Solution to this was to remove the to and from rows in this screen:

![image](https://user-images.githubusercontent.com/597770/40934131-a6e12838-67e8-11e8-9bd8-c6d992bcdaee.png)

**Comment by bdresser** [comment]
looks good @cjeria

do you want the "total" row to stay gray or change to white? also what about the helper text up top? 

<img width="300" alt="screen shot 2018-06-04 at 12 16 08 pm" src="https://user-images.githubusercontent.com/1016190/40936759-3c3143f2-67f1-11e8-95b2-6ece942c8b82.png">
