### ISSUE TITLE
NewUI: Text glitch on settings screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4299]
If you open the settings in the Firefox extension and then scroll down, you get some weird overlapping text.  If you wait a few seconds (maybe 5) it goes away:

![image 3](https://user-images.githubusercontent.com/542863/40258155-7d8aa32e-5aa5-11e8-8331-ec84e23fe85c.png)

**Comment by bdresser** [comment]
i don't see this on 4.7.2 with firefox 75 or 60. @danjm or @alextsg if you can't repro let's close
