### ISSUE TITLE
FD and ED transaction problem

### ISSUE THREAD

**Issue by kjw4011** [MetaMask/metamask-extension#4300]
Hey! I heard your system Have a very big problem!! shit..I'm the user of it.. then I usually makes a transaction at ForkDelta and ETHdelta...but all the functions(withdraw/ Deposit) isn't working because of your problem..I heard the manager of ED...he told me it's totally MetaMask problem...

**Comment by alacrity26** [comment]
@kjw4011 for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

https://metamask.helpscoutdocs.com/article/54-how-to-download-state-logs-new-ui
