### ISSUE TITLE
Metamask can't open

### ISSUE THREAD

**Issue by MMElias** [MetaMask/metamask-extension#4301]

**Comment by alacrity26** [comment]
@MMElias for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

https://metamask.helpscoutdocs.com/article/54-how-to-download-state-logs-new-ui
