### ISSUE TITLE
Metamask not showing latest transactions

### ISSUE THREAD

**Issue by arisie** [MetaMask/metamask-extension#4303]
Hi there,

My Metamask Chrome extension is not showing the latest transactions as well as some tokens. I can see these transactions and tokens on Etherscan of course. I've tried connecting to the testnet and back, restarting, etc but nothing works. 

Any ideas?

[MetaMask State Logs.txt](https://github.com/MetaMask/metamask-extension/files/2019560/MetaMask.State.Logs.txt)

Thanks in advance.

**Comment by alacrity26** [comment]
@arisie for user issues, please send a ticket to support@metamask.io. Kindly include your state logs too. Here's how:
https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

https://metamask.helpscoutdocs.com/article/54-how-to-download-state-logs-new-ui
