### ISSUE TITLE
Recovery from seed an issue 

### ISSUE THREAD

**Issue by nik5504** [MetaMask/metamask-extension#4305]
OS -Mac OS 
Browser -chrome 
i had set up metamask with new accounts as well as couple of imported accounts for use on dexs
i was adding some tokens overnight in metamask , in the morning i saw my metamask was logged out (could this be an issue )
i got option to create new account or import existing  . when i clicked on existing and used the seed phrase which i have copied in multiple places  it keeps giving me error -invalid seed phrase .is it a bug or can i recheck or use some other method . 
i saw a link fm dan in another thread which could get the bip39 keys ,using 1st 4 letters .but that link seems  dead now 
ive reached out to support ,its been 5 days now and couple of back and forth now ,but not made any progress . 
my new tokens are on that address and im freaking out now .
Pl guide me on what could be done . 
thanks

**Comment by JSON-LEE13** [comment]
Hello,

Please send a ticket to support@metamask.io.

Thanks!

**Comment by nik5504** [comment]
hi as mentioned above ,i havent got a response from support in over 4 days now ?

**Comment by bdresser** [comment]
closing here - fyi @JSON-LEE13 @alacrity26
