### ISSUE TITLE
Upgrading web3 API to 1.0.0+

### ISSUE THREAD

**Issue by quantumproducer** [MetaMask/metamask-extension#4306]
Is there a roadmap for upgrading to 1.0.0+?

**Comment by bdresser** [comment]
@quantumproducer check out this [comment](https://github.com/MetaMask/metamask-extension/issues/2350#issuecomment-374717425) for some context. 

first piece of this work being tracked on #3642 and [PR #4279](https://github.com/MetaMask/metamask-extension/pull/4279)

**Comment by quantumproducer** [comment]
Thank you @bdresser
