### ISSUE TITLE
Unable to create and import accounts once I have 6 accounts configured

### ISSUE THREAD

**Issue by truedoubletrue** [MetaMask/metamask-extension#4315]
I am unable to create and import accounts once I have 6 accounts configured.

The account listing UI limits the number of spaces available. In my case once you fill it past five spaces you can no longer import an account and once you have six accounts you can no longer create accounts either. 
There also is no option to remove accounts, so I need to reset in order to add different accounts. 

Please see attached image to see what I am seeing.  
![screen shot 2018-05-20 at 10 41 42 am](https://user-images.githubusercontent.com/37390851/40280101-91be08cc-5c1c-11e8-9a0d-91aaf03b22e1.png)
I am using Chrome with MetaMask extension on a Mac 10.11.6.

**Comment by p-s-dev** [comment]
For me, the account list window scrolls down.  If you put the mouse over and scroll down.  The Import button is shown below the account list.

**Comment by superwikime** [comment]
https://app.mural.co/t/consensys3989/m/consensys3989/1527187224674/c1ede03935b891c510322112e456029556233e22
