### ISSUE TITLE
Duplicate Transactions processed 5 days later after I already fixed them

### ISSUE THREAD

**Issue by dunnavilleq** [MetaMask/metamask-extension#4318]
I used MetaMask to send ETH to another party on Weds.  When I sent the transaction for ,25 ETH it did not process.  It did not show in etherscan.io, nor did I receive a tx hash for it.  I tried again by upping the gas and resent it.  Still did not show and did not have a tx hash for it.  After a while I clicked the taking too long link and upped the gas.  Still didn't work.  I then decided to just go online and use myetherwallet.com to send the transaction.  It went through just fine.  Nothing was happening in the MetaMask so I rejected the transactions.  I looked into cancelling them, but they were not showing up in etherscan, so there was nothing i could do about it.  This morning I woke up and sent some more ETH to the wallet and then I noticed that .5 ETH was missing.  I was on myetherwallet.com so I quickly went to etherscan and found that the other two transactions from days ago had been processed this morning in metamask.  I am seriously bothered by the fact that metamask did not function properly and cost me .5 ETH.  There is no way to get that back and I am completely frustrated that the transactions were not listed as pending in etherscan.  I had no tx hash, and rejected them in MetaMask.  Why then are they still out there processing four/five days later?  Is there a way for me to recover those funds.

**Comment by JSON-LEE13** [comment]
Hello,

Please send a ticket to support@metamask.io for this issue.

Thanks!
Hello,

Hello,

Please send a ticket to support@metamask.io for this issue.

Thanks!

**Comment by JSON-LEE13** [comment]
Hello,

Please send a ticket to support@metamask.io for this issue.

Thanks!
