### ISSUE TITLE
Update "Restore Account" to New UI

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4320]
Let's reuse the import screens from the new onboarding flow for the Restore Account screens. The restore account button is found in the login screens after the user has created their account can't remember their password and wants to restore using their private keypass.

Note, the main difference between the two is the wording. 

"Restore" and "Import" should be reflected in the UI and the main action button.

Left is the UI that needs updating, the right screen is the same component from the onboarding flow.
![image](https://user-images.githubusercontent.com/597770/40323923-c2132bc2-5ceb-11e8-8bd6-58a17c3620fb.png)

**Comment by alextsg** [comment]
Resolved by #4648
