### ISSUE TITLE
Doc: extension-to-extension provider connections

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#4322]
Following up on https://github.com/MetaMask/metamask-extension/pull/3997

here is implementation
https://github.com/jakubsta/example-extension/blob/master/background.js#L7

**Comment by kumavis** [comment]
beyond documentation we may want to publish this provider

**Comment by bdresser** [comment]
mostly handled https://medium.com/@writeprovidence/how-to-create-a-web3-provider-from-another-extension-6b5ea59ed4c9 and https://github.com/MetaMask/metamask-extension-provider
