### ISSUE TITLE
Fix font source issue with Brave

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4330]
We are still loading some fonts over the network, we should probably just put our required fonts into the bundle.

For at least one user (@jrmoreau), this is preventing MetaMask from starting on Brave.

<img width="801" alt="brage-error" src="https://user-images.githubusercontent.com/542863/40331020-d3f8f822-5d03-11e8-87ce-20f355869a63.png">

So far, only one report of this specific bug, but it may be related to other Brave bugs that users have reported, such as #4281 and #4270.

**Comment by z12b** [comment]
When will this be done? I can't access my EOS token and need to register. Thanks

**Comment by z12b** [comment]
![brave issue](https://user-images.githubusercontent.com/39470521/40401968-2efcb696-5e17-11e8-8bbf-10aaf15946ba.png)

**Comment by danfinlay** [comment]
@z12b If you're experiencing this issu on Brave, and have an urgent event coming up, please just use your 12-word seed phrase to instantiate MetaMask on another browser for now.

**Comment by z12b** [comment]
I lost it (my fault) but any way to access before June 2nd? I have my
metamask password and public address but that's it

Thanks for your help!

**Comment by dwisdom23** [comment]
I have the same problem. please help

**Comment by tcivil412** [comment]
I'm having the same issue and need to register my EOSDAC and move coins. This is becoming a big hassle. I have my 12 seed but I created other accounts within the metamask and when i open on chrome browser, it doesn't show all my accounts. I'm stuck until this is fixed.

**Comment by tcivil412** [comment]
z12b wow been pulling my hair out for over an hour. Got it to work thank you!!!!

**Comment by dinosworld** [comment]
I'm with these guys I cant even access it using MEW.

**Comment by z12b** [comment]
One helpful thing Randy (ConsenSys support) gave me is if you are using
Brave browser and you go to
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html directly you
should be able to see the MetaMask extension in a browser tab

**Comment by tcivil412** [comment]
Still no issue to this fix? I was able to open on chrome but I have to add the accounts back. I'm able to add my accounts back but all my tokens are missing and I need to transfer EOSDAC to MEW asap or I'll lose them.

**Comment by danfinlay** [comment]
> I need to transfer EOSDAC to MEW asap or I'll lose them.

As I wrote above:

> If you're experiencing this issue on Brave, and have an urgent event coming up, please just use your 12-word seed phrase to instantiate MetaMask on another browser for now, or on another wallet client.

**Comment by danfinlay** [comment]
Possibly related to #4281.

**Comment by dinosworld** [comment]
so I did the update last night still no view on metamask gui I'm using google chrome now.  Not really by choice.

**Comment by bdresser** [comment]
hoping this may be mitigated by #4524 – if the error persists once the patch is out, let us know

**Comment by bdresser** [comment]
Haven't heard from anyone, so closing this for now - let me know if you're still having trouble!

**Comment by dinosworld** [comment]
yeah its working now, the app is refreshing and working 100% now.  Thanks
now if the coins in the account would hold some value! lol
