### ISSUE TITLE
Issues with logging into Metamask (blank screen) on Chrome (updated)

### ISSUE THREAD

**Issue by harryT8988** [MetaMask/metamask-extension#4339]
Hi Metamask team and friends, 

I have created a wallet and deposited some ETH into MEW months ago. 

**Issue 1) Blank screen**
But recently, i tried to click the fox icon, a blank screen appeared. I had read some reviews, reinstalled the most updated metamask extension to no avail, still blank screen. 

![image](https://user-images.githubusercontent.com/39519700/40357225-10f69e4c-5dee-11e8-83b5-585d44fb8136.png)

My google chrome browser is also updated. 

**Issue 2) "Connect to Metamask button not responsive"** 
This is on MEW website.
![image](https://user-images.githubusercontent.com/39519700/40357345-750fe3a2-5dee-11e8-87b1-b86c73563deb.png)

Thanks
Harry

**Comment by bdresser** [comment]
@harryT8988 what OS and Chrome version are you running?
