### ISSUE TITLE
Usage Metrics for Measuring Design Impact 

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4348]
Look for methods to integrate and gather usage metrics (mixpanel?) in our product to help us measure impact of our design decisions. The idea is to gather randomized usage metrics (how the product is being used) to help us make better informed design decisions with real data. 

This talk by a designer at Status mentions collecting usage data for their mobile product: https://www.youtube.com/watch?v=yE9jY9o-mEU

**Comment by cjeria** [comment]
related https://github.com/MetaMask/Design/issues/10

**Comment by bdresser** [comment]
closing for now - will break up in to more granular issues as we begin implementing matomo
