### ISSUE TITLE
Metamask: At every PC restart, DISAPPEAR transaction History .. also CUSTOM TOKEN .. I have to re-enter manually again ...

### ISSUE THREAD

**Issue by HologramX** [MetaMask/metamask-extension#4352]
I used metamask for a year ... no problem until March 1 .. I have not used PC for about 2 months .. On reboot ... (end of April) a bit 'of upgade ... SO and app .. .. since then, it seems that metamask is frozen .. I can use it without problems but when I restart the pc and reopen it, history contains only 2 old transactions and the token section is EMPTY ... I can add ALL custom tokens again , but I have many and then I stopped adding them. ... I check my balance on etherscan ... Removed .. Removed chrome, Reinstalled ... no change ... anyone knows a solution Or where does metamask store transaction history and custom token configuration? I would keep a copy of the configuration file so it does not have to ADD every time my custom token contract ...

**Comment by bdresser** [comment]
@HologramX please email support@metamask.io with a description of your issue
