### ISSUE TITLE
Allow wallet seeds longer than 12 words

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#4358]
I thought that Metamask conforms in this to the general usage of BIP39, but it seems that's not the case.

BIP39 mnemonics can be multiples of 3 words, which means there can also be 15, 18, 21 and 24 words long mnemonics. (I haven't seen anything above that.) People use them, one reason being that 24 words long mnemonics (256 bit entropy) are safe against quantum computation attacks.

My point is that right now Metamask won't let me through if my seed is longer than 12 words. This limits the user, and also compromises seed portability.

Could we have longer seeds accepted?

**Comment by Ratnaram12** [comment]
I like metamask wallet

**Comment by dhodge229** [comment]
Would like to bump this a bit for consideration. 24 word mnemonics seem to be picking up traction so it'd be great from a user perspective to have support.

**Comment by Drive4ik** [comment]
My wallet has 24 words seed. And this is the only limitation that does not allow me to use MetaMask.
As far as I know, making support for 24 words should not be a lot of work, just the last keyword and its bits to calculate from the total number of words in seed. Still need to fix the translations)
Thank you very much in advance!

**Comment by wjmelements** [comment]
👍 

This would help with compatibility and shouldn't be too hard of a change

**Comment by wjmelements** [comment]
It looks fairly easy to do this because the bip39 dependency already supports 24-word seed phrases.

**Comment by wjmelements** [comment]
I have a WIP [here](https://github.com/MetaMask/metamask-extension/pull/7987)

**Comment by asmodat** [comment]
Definitely need this feature, because it makes it incompatible with the ledger and importing old accounts which are by default 24 words
