### ISSUE TITLE
[Beta UI] Misbehavior in Import Account

### ISSUE THREAD

**Issue by neilpalima** [MetaMask/metamask-extension#4368]
(BETA UI) Error handling messages are still showing even after successful import of account. Also, there is no successful import message after importing a wallet.

Error messages:
"You must enter a password for the selected file." or "Key derivation failed - possibly wrong passphrase"

These were still shown when you edit a wallet name.

![screenshot from 2018-05-25 07-40-48](https://user-images.githubusercontent.com/10279494/40518869-448add7e-5fef-11e8-9f3a-541075589d5c.png)
![screenshot from 2018-05-25 07-39-11](https://user-images.githubusercontent.com/10279494/40518870-44ca8046-5fef-11e8-9072-8f98c05c9f85.png)

**Comment by whymarrh** [comment]
@danjm is this fixed given #4663?
