### ISSUE TITLE
MetaMask Ether Faucet Issue

### ISSUE THREAD

**Issue by cmaliwal** [MetaMask/metamask-extension#4370]
**MetaMask Ether Faucet**\

I am getting error when I requesting for test ropsten ether.

transactions
{"error":"[ethjs-rpc] rpc error with payload {\"id\":9773661096202,\"jsonrpc\":\"2.0\",\"params\":[{\"to\":\"0x211ae9b571ed1524075dbb2a8ce87b0def98ad07\",\"from\":\"0x81b7e08f65bdf5648606c89998a9cc8164397647\",\"value\":\"0xde0b6b3a7640000\",\"data\":\"0x\"}],\"method\":\"eth_sendTransaction\"} [object Object]"}

**Comment by Zanibas** [comment]
The test faucet restarts every now and then--hopefully you were able to get a transaction through.

**Comment by therightstuff** [comment]
This helped: https://github.com/MetaMask/metamask-extension/issues/2038#issuecomment-413470293
