### ISSUE TITLE
URGENT REQUEST as account was hacked - cannot send tokens

### ISSUE THREAD

**Issue by EmileduToit** [MetaMask/metamask-extension#4372]
URGENT!!

Hi there,

I could really use a quick solution here. My account MEW (not MM) account was hacked yesterday and I lost a lot of EOS and XYO. Funnily enough I think the only reason they didn't take everything is that there wasn't enough ETH left for gas. Anyhow, I am trying to transfer what tokens are left out of MEW into my MetaMask account (i.e. the one I set up when I first installed Metamask). Basically, I need to get the tokens out of that account immediately.

I started transferring tokens and some transferred successfully. But then they just stopped transferring. There is ETH for gas, and I have tried some pretty high gas limits (the latest transaction i set it to 200 000). Recently, I get to the point where I click the last button on MEW and then "Submit" on Metamask, and then it just does nothing.

I am a sitting duck right now so would really appreciate a prompt response.

Here is the link https://gist.github.com/EmileduToit/640bf6b3478b64290b394ba16b65c5d1#file-gistfile1-txt

I am running Windows 10 64bit and Chrome Browser Version 65.0.3325.181 (Official Build) (64-bit)

I have attached some screen shots too. I see there order got scrambled; obviously they should be ordered (from the top) first, second, fifth, fourth, third.

Emile
emiledutoit@gmail.com

![metamask2](https://user-images.githubusercontent.com/39376970/40540559-e0aa3672-6018-11e8-94bc-6dbffd51532d.png)
![metamask1](https://user-images.githubusercontent.com/39376970/40540561-e0deb532-6018-11e8-8bd0-c0fd4c0b3995.png)
![metamask5](https://user-images.githubusercontent.com/39376970/40540562-e1135cc4-6018-11e8-83f6-d981e3f5939d.png)
![metamask4](https://user-images.githubusercontent.com/39376970/40540563-e148f24e-6018-11e8-9cc9-4d5e2027127a.png)
![metamask3](https://user-images.githubusercontent.com/39376970/40540564-e17da49e-6018-11e8-8fe0-d403664eba81.png)

**Comment by Zanibas** [comment]
I  know this has been 5 days, but did your transactions eventually go through? Apologies that you got hacked.

**Comment by EmileduToit** [comment]
Yes the ones that can go through eventually did. I had uninstalled and then
reinstalled Chrome extensions and that seemed to do the trick.











*Private practice website*

http://www.emiledutoit.co.za



*My new psycho-educational website: Tools for Health and Wellness*

http://www.toolsforhealthandwellness.com/

https://www.facebook.com/toolsforhealthandwellness

http://www.pinterest.com/TFHAWellness/

https://twitter.com/TFHAWellness

https://www.linkedin.com/company/tools-for-health-and-wellness

https://www.google.com/+Toolsforhealthandwellness
