### ISSUE TITLE
Test - unit - no tests for MetamaskController.importAccountWithStrategy

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#4392]
seems important 😉

**Comment by bdresser** [comment]
@danjm @tmashuang is this still relevant?

**Comment by tmashuang** [comment]
There is an open PR with some `importAccountWithStrategy` tests. Also, tests in the `actions`, https://github.com/MetaMask/metamask-extension/blob/fba17d77de9e60de0e02e90dc6dbcbbf7454158a/test/unit/ui/app/actions.spec.js#L591
