### ISSUE TITLE
Unable to import account priv key or json file.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#4412]
Importing a private key does not return an error message, returns to the account detail screen of Account 1.
Importing json file loads renders loading screen, but does not import the account. Also, no error messages.

**Comment by kumavis** [comment]
hmm importing priv key works for me

**Comment by kumavis** [comment]
i was able to reproduce on the metamaskbot build 👍

**Comment by tmashuang** [comment]
![screenshot from 2018-05-30 10-16-39](https://user-images.githubusercontent.com/13376180/40736497-0b2c12de-63f3-11e8-9d41-a8dacb4d40bb.png)

Had to put 'Pause on Exception' in the extension in the background. This is the only error that showed.
