### ISSUE TITLE
METAMASK HIDE TOKEN FIX

### ISSUE THREAD

**Issue by MetaMaskFixer** [MetaMask/metamask-extension#4422]
Hi All if you wish to Hide tokens please follow these steps.......

open Meta Mask and sign in.
click the 3 little dot to bring up log out settings etc
click on try beta!
after you have opened the beta version go to your tokens
Click the 3 little dots next to you token to hide them
ENJOY!!!!!

**Comment by MetaMaskFixer** [comment]
Hi All if you wish to Hide tokens please follow these steps.......

open Meta Mask and sign in.
click the 3 little dot to bring up log out settings etc
click on try beta!
after you have opened the beta version go to your tokens
Click the 3 little dots next to you token to hide them
ENJOY!!!!!

**Comment by fblauer** [comment]
How do you unhide them?
