### ISSUE TITLE
Import Account - no validation on private key

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#4427]
importing a private key with arbitrary data generates a junk keyring. this keyring is persisted.

**Comment by kumavis** [comment]
thankfully this just creates an empty keyring and does not otherwise cause much harm

**Comment by kumavis** [comment]
Sentry issue: [METAMASK-29QY](https://sentry.io/metamask/metamask/issues/568496657/)

**Comment by danfinlay** [comment]
Fixed by #4513.
