### ISSUE TITLE
4.7 release introduces a bug when the user rejects signing a transaction.

### ISSUE THREAD

**Issue by mattgstevens** [MetaMask/metamask-extension#4441]
## Description
Latest version (4.7) introduces a bug when the user rejects signing a transaction.

## System details
Browser: Chrome Version 66.0.3359.181
Operating System: macOS 10.13.4

## Details
Our web client handles errors from web3 signing by wrapping in a try/catch block; in previous versions of MetaMask this worked well: if a user rejected the transaction an error was thrown, and the catch logic would run.

With the latest MetaMask (4.7) this is not the case, and a stack trace like the following is in the dev console.
![image](https://user-images.githubusercontent.com/2363636/40840757-4b2f2194-65a8-11e8-9a9a-873cc5c33eef.png)

The code that handles this transaction looks like the following (where the `token` object is a contract instance from library 'truffle-contract')
```js
try {
    const transactionHash = yield call(Token.buy.sendTransaction, {
      from: activeAccount,
      value: weiAmount,
      gas: defaultTransactionGas
    })
    yield put({
      type: 'Token/buy-tokens/SUCCESS',
      payload: {
        contractAddress,
        transactionHash,
        amount: weiAmount
      }
    })
  } catch (error) {
    yield put({
      type: 'Token/buy-tokens/FAIL',
      payload: {
        amount,
        contractAddress,
        message: error.message
      }
    })
  }
```

To verify, I installed the last MetaMask version (4.6.1) and this bug was not present; when a user rejects signing a transaction the `catch` block will execute.

**Comment by Pedro-vk** [comment]
I'm having the same problem when I'm subscribed to an `error`.
E.g.:
```typescript
sendResonse
  .on('transactionHash', txHash => {
    // Do things
  })
  .on('confirmation', confirmations => {
    // Do things
  })
  .on('error', error => {
    reject({error}); // <--- Not called
  })
  .then(receipt => {
    resolve(receipt);
  });
```
The complete code is here: https://github.com/Pedro-vk/EthKudos/blob/master/src/app/shared/smart-contract.abstract.ts#L127
