### ISSUE TITLE
[NewUI] Account order jumbled

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4442]
SimonDLR reported his account order got jumbled:

![screen shot 2018-06-01 at 10 22 27 am](https://user-images.githubusercontent.com/542863/40854263-b77a8c1c-6585-11e8-97a6-42e178500a1b.png)

Was there a change to account order logic @danjm?

**Comment by whymarrh** [comment]
I could be wrong here but there wasn't ever an explicit order to the accounts and we were (unfortunately) relying on object key iteration order. This bug, a reversal of the account order essentially, would make sense as migration 26 reduced the old identities into a new identities: https://github.com/MetaMask/metamask-extension/blob/003172231a46ea4587dfdf55ec3ba0803597419b/app/scripts/migrations/026.js#L37-L44

I'm not entirely sure of two things: 1) if this would be a list reversal consistently for all users, and 2) if there's a good solution to _undoing_ this. It might be best to enforce an order on the accounts (alphabetical?) going forward.

**Comment by danjm** [comment]
Closing in favour of #4465
