### ISSUE TITLE
Unable to hide tokens

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#4443]
`Uncaught TypeError: Cannot read property 'symbol' of undefined` on Rinkeby tokens.
`Uncaught TypeError: Cannot read property 'show' of null` on Mainnet tokens.

**Comment by chapati23** [comment]
confirmed. i also can't hide tokens. after clicking the button nothing happens

**Comment by danjm** [comment]
@tmashuang @chapati23  Is that for all tokens in the mentioned networks? Or does it work for some and not for others?

**Comment by bdresser** [comment]
@danjm haven't been able to remove either suggested or custom tokens on mainnet or rinkeby
