### ISSUE TITLE
Suddenly disabled from Chrome, and will not enable after clicking "enable".

### ISSUE THREAD

**Issue by aremkay** [MetaMask/metamask-extension#4444]
#

**Comment by bdresser** [comment]
@aremkay could you provide some more details? browser version, where you're seeing these "enable" / "disable" buttons, etc?

**Comment by bdresser** [comment]
Token balances and transactions aren't shown by default, you have to add them. Please read our [help article](https://consensys.zendesk.com/hc/en-us/articles/360004135092-Managing-ERC20-Tokens) on this topic and reach out to support@metamask.io with further questions.

**Comment by aremkay** [comment]
The door slammed shut so fast that it hit my nose.
Apparently there is no response to my concern that assets in MetaMask are just not appearing, or being reported, by the app.
Fare thee well.

Sent from Mail for Windows 10

**Comment by aremkay** [comment]
Of course they have been added!

**Comment by bdresser** [comment]
didn't mean to bump you with the door @aremkay 😃 but we do deal with general user support in a different system. if this is a bug, we need a little more detail to be useful!

you're saying the extension is reporting a different token value than is actually on your account? could you provide a screenshot & address to help us debug (along with the basic info I requested above)?

**Comment by aremkay** [comment]
Attached is a screenshot. 
![meta mask](https://user-images.githubusercontent.com/39576626/41127804-0f649050-6a7a-11e8-956c-ec80220f0263.JPG)
As to the tech support address: I was being sent from there to there to here. I chirped where I landed. Like any bird.

**Comment by bdresser** [comment]
this doesn't help - is this the bug you're claiming to encounter? 

> you're saying the extension is reporting a different token value than is actually on your account?

if so, what do you see in the extension UI and how does this differ from the account balance on etherscan.

**Comment by aremkay** [comment]
Well I was lead to believe that XYO deposits into this wallet.
![meta mask 3](https://user-images.githubusercontent.com/39576626/41128248-7ec75300-6a7b-11e8-899d-c448e4f84df6.JPG)

**Comment by bdresser** [comment]
so if you follow the steps listed in this help article (https://consensys.zendesk.com/hc/en-us/articles/360004135092-Managing-ERC20-Tokens), and there's a balance of tokens on that address, you'll be able to see the tokens.

**Comment by aremkay** [comment]
OK, so I follow the links and here is where it takes me. Another fork without a hint as to which turn is for me.

Sent from Mail for Windows 10

**Comment by tmashuang** [comment]
I'll try to address the concerns in order from top to bottom:
> Suddenly disabled from Chrome, and will not enable after clicking "enable"

Seems to render for you.
>However, I do have a serious issue with the fact that my XYO purchases do not appear. Nor for that matter my LCS.

Both of these links shows you have tokens associated with the address you provided.
https://etherscan.io/token/0xaa19961b6b858d9f18a115f25aa1d98abc1fdba8?a=0xa56b17ac21a0460d33339a5ed2267f11faf8069d
https://etherscan.io/token/0x55296f69f40ea6d20e478533c15a6b08b654e758?a=0xa56b17ac21a0460d33339a5ed2267f11faf8069d

>Another fork without a hint as to which turn is for me

It is not clear to me what you mean by this. Are you referring to the steps? If the guide is too long and extensive then I will provide a TLDR; to your specific issue.
1. Click the three horizontal lines in the top left section of MetaMask.
2. Click Add Token button
3. Select Custom Token Tab
4. Add the token address 
    (Don't know what this is?)
    Just put in this:
    0x55296f69f40ea6d20e478533c15a6b08b654e758 for XYO
    0xaa19961b6b858d9f18a115f25aa1d98abc1fdba8 for LCS
    Should AutoFill in Token Symbol and Decimal of Precision
5. Click Next
6. Should show Token name and Balance
6. Click Add Tokens

**Comment by aremkay** [comment]
a) It just said at the top of ”the menu” – how was I to know to leave this site and go to another? I have now found it. But the confusion continues.
b) Token address, the token symbol – so I didn’t know the token address (where should I have acquired it?) I put in XYO. Nothing. That’s where I am at. It would have helped if there were a grey dimple of an address to make that clear.
c) So where do I get the token address? Just by entering the symbol in Etherscan? So why not such an easy facility here.?
d) No. I still do not have the address. Which and where is it?

Sent from Mail for Windows 10

**Comment by aremkay** [comment]
OK, so thank you. 
(Suggestion: Long addresses [0xaa19961b6b858d9f18a115f25aa1d98abc1fdba8 for LCS] are best listed as follows: For LCS - 0xaa19961b6b858d9f18a115f25aa1d98abc1fdba8. 
It took me a while to realize that I was pasting the last words as part of the token address.

But how do I find the address for next t ime?
I have not seen that MetaMask stores other tokens – am I mistaken? 

Thank you again, and convey to bobby dresser also.

Sent from Mail for Windows 10
