### ISSUE TITLE
Old + New UI: Weird right padding

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4452]
We have some strange padding on the right of the extension "action view":

![screen shot 2018-06-01 at 4 27 47 pm](https://user-images.githubusercontent.com/542863/40867420-caf2a45e-65b8-11e8-893c-cbaa48941e8b.png)

**Comment by whymarrh** [comment]
I've not seen this is any recent screenshots from us, devs, or users. We can re-open this if it comes up again.
