### ISSUE TITLE
Metatask account not showing balance and white screen

### ISSUE THREAD

**Issue by djaygit** [MetaMask/metamask-extension#4457]
I'm running windows 10 and using chrome and latest meta task
when i open metatask, it asks for login then shows the login screen again with weird/unorganized UI
so I tried myetherwallet and confirm transaction is white as well

other account balances are showing except the one created by metatask

![image](https://user-images.githubusercontent.com/1255841/40879079-70d901ec-66b8-11e8-9d7c-f0c0a492aba3.png)

this is when i try myetherwallet
![image](https://user-images.githubusercontent.com/1255841/40879074-5d2953b8-66b8-11e8-9402-26c7b4527826.png)

this screen shows after login
![image](https://user-images.githubusercontent.com/1255841/40879087-889e70c8-66b8-11e8-9d85-83b86d30a1e5.png)

**Comment by mukeshmali** [comment]
same issue with my wallet to ......... please help me too

**Comment by mukeshmali** [comment]
@kumavis don't have seed phrase And still want to recover. its a huge money for me ....... please help me dear

**Comment by iamankush** [comment]
Hi @kumavis - i am also facing the same issue. No seed phrase.but still i would want to recover. It was always working fine before update on 1 june. I suppose there is some bug introduced on 1 june version which is why we are getting this issue. 

I have trust team should be able to help us and we will be able to recover these accounts. This is a major issue with lot of users as i know many friends who are facing this same problem. Please let us know if you want any more info to recover. 

Also i dont have that much funds too where in i can wait for weeks to fix this, i would request you to help in this case urgently so that i should be able to withdraw my funds.

**Comment by akusdgpt** [comment]
@kumavis same issue on my PC, i was using metamask normally till 1st of June, but i see a blank page while doing transaction from yesterday.
I couldn't find my seed phrase, how to recover that account... please help us :)

**Comment by HrishikeshR03** [comment]
@kumavis and Metamask team, I did the reinstall if metamask many times, but  every time I re install, multiple accounts are not shown, for that I have to click on create new account to see my previously created accounts. And this issue of multiple ETH accounts is an existing bug. But after reinstalling yesterday, the above process of clikcing on Create new ETH address seems not working. And I can see only 1 ETH account in my meta mask. Seems there is an issue with latest update, please check. I have my ETH stored in my other ETH accounts which are unfortunately not being shown now. What I have is the seed words of my Metamask and not the private keys. please help me out

**Comment by aganurag58** [comment]
@kumavis  Me too facing same problem. No seed phrase. No private key. Could not transfer ether. And this problem came after update of metamask.pls help in this matter.

**Comment by neocodes** [comment]
Facing the same Issue, not having seed phase or Pvt key. metamask is stuck in a white screen. Please, devs help. :(

**Comment by kumavis** [comment]
have a potential fix in the works

@djaygit @mukeshmali @iamankush @akusdgpt @HrishikeshR03 @aganurag58 @neocodes
make sure you have your seed phrase stored somewhere safe! without access to your seed phrase you are stuck and at risk of losing your accounts! I recommend writing it on a piece of paper and keeping somewhere safe.

**Comment by iamankush** [comment]
Thanks @kumavis for taking it on priority! 

The situation is many of us dont have our seed phrase and please just save us this time from a situation of losing funds. Please help and recover this time. This is a learning for me and will always be keeping it.

**Comment by kumavis** [comment]
Published a potential fix 4.7.2, rolling out now (**may take a couple hours**)

As its difficult to determine the exact cause of the issue everyone is encountering, please let us know if this new version did not solve your problem.

**Comment by mukeshmali** [comment]
@kumavis tried the new 4.7.2 update, still the same issue. Whats worst is that i have the seed key and when i try on other chrome accounts, it doesn't show the account with ether ether balance

**Comment by djaygit** [comment]
I confirm i still have the same issue, may be you could take a look over teamviewer?

**Comment by kumavis** [comment]
@djaygit a screenshare would be very helpful

**Comment by mukeshmali** [comment]
@kumavis which app is better for screen share

**Comment by kumavis** [comment]
does google hangouts work? I'll create a link

**Comment by mukeshmali** [comment]
@kumavis  yes give link

**Comment by kumavis** [comment]
in a metamask meeting, lets do it in 15 minutes, ok?

**Comment by danfinlay** [comment]
Could someone still experiencing this on 4.7.2 email state logs to support@metamask.io and then post your issue number here?

https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue

**Comment by mukeshmali** [comment]
@kumavis   yes np

**Comment by kumavis** [comment]
@mukeshmali @djaygit before the video call, can you email the UI logs using dan's link above

**Comment by kumavis** [comment]
@mukeshmali @djaygit https://hangouts.google.com/call/Iu2oCydTutZ_w04TZuLMAAEE

**Comment by djaygit** [comment]
@kumavis @danfinlay thanks for the quick support guys, we really appreciate it. Hope we get this issue resolved soon

**Comment by kumavis** [comment]
@djaygit @mukeshmali where did this "Account 1" come from? was this an imported account or did it come from a seed phrase? If it came from a seed phrase did it come from the current used seed phrase?

in the logs we see it doesn't have a private key associated with it

**Comment by djaygit** [comment]
@kumavis it was created on meta task on 2nd June

**Comment by mukeshmali** [comment]
@kumavis Account 1 created by using metamask

**Comment by kumavis** [comment]
@djaygit @mukeshmali ok can you rejoin the hangouts? same link as before

**Comment by mukeshmali** [comment]
yes sure

**Comment by kumavis** [comment]
@mukeshmali we're still investigating the cause of the issue, will give you an update tomorrow

**Comment by mukeshmali** [comment]
@kumavis sure bro . i am waiting :P

**Comment by mukeshmali** [comment]
@kumavis  After an auto update, the account which was not accessible earlier is now not even visible. 

Guys please help me, this will make me lose all my funds . I cant afford this situation

 Please look at the screenshot for reference.
![metas](https://user-images.githubusercontent.com/3995918/40989127-82df6468-690a-11e8-8f69-e53b655e5b38.JPG)


here previous version metamask pic.

![28279014_1795988837112061_4934985495673079085_n](https://user-images.githubusercontent.com/3995918/40989154-963e8caa-690a-11e8-8e72-d2668a25a35a.jpg)

**Comment by iamankush** [comment]
Hi @kumavis this is really critical for us as there is too much amount stuck for us, now that you have made updates, we are not even able to see the account. Could you please help us on how to fix that now and get the funds out of this account? Please please help this is really urgent.

**Comment by govindk007** [comment]
Hi @kumavis u people stucked their eth nd that too large sum of money is stucked u should take some serious steps 
As how to trust metamask anything can be happen with us also ,please help as soon as possible so that i myself can start using metamask again till then i stopped using it its him today may be i tomorrow

**Comment by aganurag58** [comment]
It's been 3 days and problem is not solved 20 ether is a big amount. All this is happening coz of metamask update. Pls urgently help in this case.

**Comment by amanbhag** [comment]
this thing was not expected from metamask looks like metamask is not safe for our funds 20 eth is a huge amount. i am not gonna use metamask from now onwards

**Comment by kumavis** [comment]
@djaygit @mukeshmali thank you for your patience, we have an update from our research. are you available for another hangouts

**Comment by kumavis** [comment]
sorry i realize its 2am in mumbai so its no problem to do this tomorrow

**Comment by mukeshmali** [comment]
@kumavis  possible to next day ..........  for hangout i not perfect in english ... but understand little english ......  besy way to team viear or other think possible bro

**Comment by mukeshmali** [comment]
@kumavis  if you want team viewer info i will share you

**Comment by kumavis** [comment]
@mukeshmali we dont need any more info, want to present the results of our research

**Comment by mukeshmali** [comment]
sure ..... when i got my ETH back ....... please its very bad and critical condition for me .... please help buddy @kumavis 


your help very good bro

**Comment by kumavis** [comment]
@mukeshmali here i can give a simple update https://hangouts.google.com/call/jU48_T_6VmLN_d_kbV2EAAEE?no_rd

**Comment by mukeshmali** [comment]
@kumavis here my email address : **me@mukeshmali.com** and eth address : **0x608aAD43748BfEf790cC40B4dA4378591474cB09**

**Comment by mukeshmali** [comment]
when transfer please send asap  @kumavis thanks buddy for helping :P

**Comment by mukeshmali** [comment]
@kumavis any update dear ..............

**Comment by kumavis** [comment]
@mukeshmali the bug bounty reward should be in by friday

**Comment by mukeshmali** [comment]
@kumavis Thanks ! This help is appreciated

**Comment by mukeshmali** [comment]
@kumavis today is Friday ........ any update ... :P

**Comment by mukeshmali** [comment]
Win Bug bounty reward from #Metamask  @kumavis 

https://medium.com/metamask/metamask-bug-report-june-5-2018-428e91276142

**Comment by kumavis** [comment]
Bug Bounty award has been sent

**Comment by djaygit** [comment]
@kumavis what about the lost ether? was it included in bounty? is it lost forever? am i supposed to get it from metamask team? 
if its included in the bounty, then the bounty is not actually "25 ether" but 3.5eth?
if its not included in the bounty, Am i ever getting it back again?

**Comment by kumavis** [comment]
@djaygit we do not reimburse lost ether. backup of accounts is the responsibility of the user.

**Comment by djaygit** [comment]
@kumavis as you saw during the screenshare, we never got any private key for that account. you saw that right?

**Comment by sunnynjoy** [comment]
Hi,
I transferred Ether to Metamask but it is not showing up in the main Ethereum network. When I click on "view on etherscan" on Metamask, it takes me to the below address. One can see that it's a valid and successful transaction. Emailed support@metamask.io but did not get a reply.

https://etherscan.io/address/0x2fd72bd1a59342f93aeb6f3e01f6bdb8783916e9

**Comment by gabchuks** [comment]
I have zero balance when I login to my metamask but I have eth on it
