### ISSUE TITLE
my metamask got out of use

### ISSUE THREAD

**Issue by es335ab** [MetaMask/metamask-extension#4458]
Because metamask became unusable,
I am planning to restore the account of the new metamask.
However, I have lost the seed information of my current account.

Is it possible to restore metamask account from this state?

### When I click the icon

<img src="https://i.gyazo.com/d8cd2becbbab014bff0b57912d8b88e3.png">

### Browser console

<img src="https://i.gyazo.com/10408841f74a86d957404b3ad68fbe0d.png">

**Comment by bdresser** [comment]
@es335ab @Kil0grm what browser & browser version are you on?

**Comment by es335ab** [comment]
@bdresser

Sorry for my late reply.
This is chrome69.0.3497.100.

**Comment by bdresser** [comment]
@es335ab you should always always back up your seed phrase!

for issues with the blank screen on Chrome, see #4894. If you need help recovering your account, please reach out to support@metamask.io
