### ISSUE TITLE
UI doesn't show ETH!

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#4459]
Windows 10, Firefox

As a user, I expect to see the amount of ETH I'm sending in the UI, but instead I only see USD.  I would be OK with a subscript of my chosen currency.  If I go into the currency selector, I can choose just about every currency imaginable _except_ ETH.

![image](https://user-images.githubusercontent.com/886059/40882994-105ce6ae-6725-11e8-85a1-3b86e37cca1d.png)

As a user, I find this very frustrating because I want to see how much ETH a transaction costs me, not how much USD-worth-of-ETH it costs me.  This is especially because the dapps I'm interacting with list prices in ETH, not USD, and I want to be able to validate that the transaction I am submitting aligns with what the dapp said.

**Comment by danfinlay** [comment]
We're aware of this one, please just use the old UI for now. The New UI is catching up.

**Comment by bdresser** [comment]
@MicahZoltu we're discussing next round of updates to the confirm screen in MetaMask/Design#11
