### ISSUE TITLE
Account sequences distorted

### ISSUE THREAD

**Issue by Kings1314** [MetaMask/metamask-extension#4460]
I have 40+ accounts on my Google Chrome Metamask. When I logged in this morning, the sequence of my accounts are all distorted. For example, the original sequence goes as Account 1->2->3->4->5, etc, now it goes Accounts 25->17->4->1, etc.

**Comment by danfinlay** [comment]
Sorry, we recently moved some of our nickname code and apparently this was a possible result. We will fix this soon. Closing as a duplicate of #4465.
