### ISSUE TITLE
Can't reset account with custom RPC selected

### ISSUE THREAD

**Issue by pavankat** [MetaMask/metamask-extension#4462]
When I get an rpc error, I reset my account and the error goes away

However, recently when I tried to reset my account, I get this and i'm not able to reset the account.

NetworkController - cannot call "setProviderType" with type 'rpc'. use "setRpcTarget"

![screen shot 2018-06-03 at 5 20 04 am](https://user-images.githubusercontent.com/1513415/40886506-ddadf536-66ed-11e8-89de-6efdc8cee868.png)

I'm on chrome and on version 4.7.1 of metamask

**Comment by bdresser** [comment]
also reported by another user on the new UI with similar steps to repro:

> Setup Custom RPC pointing to a local node.
Go into settings and Reset Account.
Wait for a while before realizing that nothing is happening.
Click outside of the reset box to make it go away.
Scroll up.
--> Notice the following error:
![image](https://user-images.githubusercontent.com/1016190/40989713-8b24544c-68a3-11e8-956f-707eb3d3b764.png)

**Comment by bdresser** [comment]
heads up @danfinlay @kumavis

**Comment by danfinlay** [comment]
I've fixed this issue, PR opened on #4523.

**Comment by phunsukwangdu** [comment]
yes ,same error
