### ISSUE TITLE
Account menu order can be random, is non-deterministic

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4465]
This line:
https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/components/account-menu/index.js#L138

Orders the account menu based on a call of `Object.keys(accounts)`, which does not return the list in a reliable order.

We need to list the accounts based on their creation date.  

This affects both old and new UI.

**Comment by superwikime** [comment]
*2late,bugg Biggs
