### ISSUE TITLE
Refactor the wallet view eth/token list

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4472]
The organization of the code for the wallet view ETH/token list would be easier to navigate, maintain and update edit if:
- the same component was used for rendering the ETH list item and the token list items
- the ETH list item and token list items were part of the same list component

Refactoring in this was would require the component for rendering the item to be configurable (e.g. whether or not it should have a dropdown menu). The component for rendering the list would take an array of data to render as list items. Either within the list component, or its parent, there would be logic that would output the array of data to pass to the list component, including properties needed to configure the item component. This logic would likely make use of imported selector or utility methods.

As this refactor is done, we should ensure that the ETH list item gets the same styles that the token list items got with this update: https://github.com/MetaMask/metamask-extension/pull/4428/files

**Comment by bdresser** [comment]
@danjm related to / duped by #6230 ?

**Comment by brad-decker** [comment]
closed by #8696 and constituents
