### ISSUE TITLE
sent tokens to my metamask, the tokens were showing 5 days later I logged in , now they are gone , not on etherscan

### ISSUE THREAD

**Issue by cryptoarun** [MetaMask/metamask-extension#4473]

**Comment by cryptoarun** [comment]
https://etherscan.io/token/0xc16b542ff490e01fcc0dc58a60e1efdc3e357ca6?a=0x9533dbcf46e454169783aa47c2592e0f3df02370

**Comment by Azier777** [comment]
I can't find ANY of my tokens and I don't know what's going on either.
Every token is missing

**Comment by cryptoarun** [comment]
https://ethplorer.io/address/0xbe0a2e4be0a0e7879f8b1da49a3c95a39b3c71dc
this is my last eth where it showed the tokens,, maybe im putting in wrong address in meta mask?

**Comment by cryptoarun** [comment]
just added the address from the second ethplorer.io post and it still shows 0 to the metamask, weird it showed the day I did it

**Comment by cryptoarun** [comment]
also what do i put in the decimal place?

**Comment by bdresser** [comment]
@cryptoarun please email support@metamask.io with a copy of your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI-)
