### ISSUE TITLE
Add the account address and name to the popup main screen

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4474]
The implemented feature should look like the below mockup

<img width="233" alt="screen shot 2018-06-03 at 7 58 28 pm" src="https://user-images.githubusercontent.com/597770/39145732-7cb42daa-46e9-11e8-8180-261c61e1ac0f.png">

This was originally added with comment https://github.com/MetaMask/metamask-extension/issues/3463#issuecomment-383676058

**Comment by alextsg** [comment]
There's an open PR for this task already: https://github.com/MetaMask/metamask-extension/pull/4445
