### ISSUE TITLE
Stucked at "Generating Transaction" Screen

### ISSUE THREAD

**Issue by valluminarias** [MetaMask/metamask-extension#4476]
Hello
*  Expected Behavior
   - Access Metamask UI
* Actual Behavior
   - Stucked in "Generating Transaction" Loading screen
   - Screenshot
![metamask](https://user-images.githubusercontent.com/8232426/40893776-e373e964-67d6-11e8-9bc1-973682dafeaf.png)
* browser used 
    - Mozilla Firefox 60.0.1 (64 bit)
* Operating System
    - Windows 10 version 1709

**Comment by bdresser** [comment]
consolidating to #4264
