### ISSUE TITLE
How to change Amount value for Dapps?

### ISSUE THREAD

**Issue by OrionStar25** [MetaMask/metamask-extension#4478]
Bug Reports: Every time I make a transaction using my Dapp, the Amount field is 0 ET. I want it to be the price of the good being purchased. How do I change that?

  Briefly describe the issue you've encountered
  *  Expected Behavior : Amount should be customizable
  *  Actual Behavior : Its not customizable
  *  Browser Used : Firefox
  *  Operating System Used : Ubuntu 16.04
![screenshot from 2018-06-04 13-56-31](https://user-images.githubusercontent.com/28835849/40906924-e718eab4-67ff-11e8-8c38-a5c01d4f6e9c.png)

**Comment by wjmelements** [comment]
Dapps should set the `value:` field in the transaction before sending it to Metamask. Users should not modify it within Metamask.
