### ISSUE TITLE
Network spinner blocks custom RPC form

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4479]
Story:

- User wants to connect to a custom RPC
- They enter the RPC wrong
- The spinner appears
- They click the network menu again to select custom again
- They are taken back to settings, but cannot edit the form:

![screen shot 2018-06-04 at 9 11 19 am](https://user-images.githubusercontent.com/542863/40928789-62142eb4-67d7-11e8-94cc-92db3c986db4.png)

This enhancement needs design first:
https://github.com/MetaMask/Design/issues/21

**Comment by bdresser** [comment]
@danfinlay @cjeria when I put in a custom RPC, it adds that new URL to the list of networks.

If I click "Custom RPC" again, it feels like the extension should stop trying to connect to the previously entered URL, cancel the spinner, and drop me on a fresh settings page. (Right now it just continues to try connecting to the URL I entered) 

Potentially a design-free solution?

**Comment by danfinlay** [comment]
Right now this bug doesn't exist on old-UI because it just doesn't show the spinner on the settings page, which has the same ultimate effect: People can pick a new custom RPC even when they were just searching for one. I like this solution because it's easier to implement, but either would be good.

**Comment by cjeria** [comment]
This sounds like a good opportunity to time-out with a message to "Try again" and link to the settings page per @bdresser suggestion. Easy enough to create a design for if this sounds like a desirable implementation.

**Comment by bdresser** [comment]
closing in favor of https://github.com/MetaMask/metamask-extension/issues/3776
