### ISSUE TITLE
Requirements gathering, architecture and code design for Confirm Screen refactor

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4481]
This is a ticket for the architecture and code design for https://github.com/MetaMask/metamask-extension/issues/4404

@alextsg @whymarrh

**Comment by danjm** [comment]
Requirements should include accomodatation of these designs: https://github.com/MetaMask/Design/issues/18, https://github.com/MetaMask/Design/issues/16

Another note on requirements: Metamask may eventually wish to support additional transaction types. For example, confirmation of multisig transactions. For different transaction types, validation of transaction data, and the method called when clicking submit, may differ. UIs for different types may differ as well, but the differences will likely be small.

**Comment by superwikime** [comment]
Libido's œ

**Comment by bdresser** [comment]
@danjm are you guys moving on this shortly? if so let's chat with @cjeria tomorrow to make sure we're on the same page for the UI updates
