### ISSUE TITLE
Error: Request timed out for web3 when using MyCrypto

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#4492]
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior - after signing the transaction via MyCrypto it would be broadcast and confirmed
  *  Actual Behavior - received message: `Error: Request timed out for web3`
  *  Browser Used - Chromium Version 66.0.3359.181 (Official Build) Built on Ubuntu
  *  Operating System Used - LinuxMint 18.3 (64-bit)

![requestimedout](https://user-images.githubusercontent.com/9424721/40950646-7eb8dcda-6828-11e8-89b3-e7d7e9fba7d4.png)

**Comment by bdresser** [comment]
@john-light are you still getting this error? might've been related to the same bug over the weekend that caused those other two issues.

**Comment by john-light** [comment]
@bdresser seems to work now, thanks!
