### ISSUE TITLE
Account balance not loading

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#4493]
**Edit: this may be related to #4457** 

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior - I can see my balance in my wallet
  *  Actual Behavior - the app just shows `...` where the balance amount should be
  *  Browser Used - Chromium Version 66.0.3359.181 (Official Build) Built on Ubuntu
  *  Operating System Used - LinuxMint 18.3 (64-bit)

![metamask_error_1](https://user-images.githubusercontent.com/9424721/40950721-b9b5395a-6828-11e8-8233-50d7e4603328.png)

**Comment by bdresser** [comment]
@john-light we pushed a patch yesterday for #4457 – can you let us know if you're still experiencing this bug on `4.7.4`?

**Comment by john-light** [comment]
@bdresser fixed, closing
