### ISSUE TITLE
Redundant accounts shown out of order

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#4494]
**Edit: this may be related to #4457** 

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior - I see all of my accounts in numeric order (Account 1, Account 2, etc...) and each account only once
  *  Actual Behavior - the app shows multiple "Account 4, Account 4..." etc and shows the accounts out of order (Account 4, Account 3, Account 1... etc)
  *  Browser Used - Chromium Version 66.0.3359.181 (Official Build) Built on Ubuntu
  *  Operating System Used - LinuxMint 18.3 (64-bit)

![metamask_error_1](https://user-images.githubusercontent.com/9424721/40950801-13966de0-6829-11e8-9c34-5e9bcae4f1fe.png)

**Comment by whymarrh** [comment]
The disorder of the list is related to #4465 at the very least

**Comment by whymarrh** [comment]
@john-light can you still reproduce this on 4.7.4?

**Comment by john-light** [comment]
@whymarrh fixed, closing
