### ISSUE TITLE
Can't send eth, invalid seed phrase as well. 

### ISSUE THREAD

**Issue by kinkykiwe** [MetaMask/metamask-extension#4495]
Hi, I have just tried to send transactions and it just comes back with taking too long I have also tried sending to different wallets with the same result. I also tried to restore my account on a different computer but says the seed phrase is invalid. I can still log in and out fine, but just can't send transactions and don't want to reset my account because I may have written the seed phrase down wrong.

**Comment by bdresser** [comment]
@kinkykiwe this may have been fixed by #4486. if you're still experiencing this issue, please email support@metamask.io with a copy of your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI) and we can help you troubleshoot there.
