### ISSUE TITLE
Stuck at "Connecting to Main Ethereum Network" if Firefox is launched offline, but brought online later

### ISSUE THREAD

**Issue by gustafla** [MetaMask/metamask-extension#4496]
As the title says, MetaMask on Firefox 60.0.1 (Linux 4.16.12-gentoo x86_64 GNU/Linux) won't let me enter the password, only shows a connecting spinner. This happens when firefox is launched before machine has connected to a network.
![screenshot](https://user-images.githubusercontent.com/8680135/40957398-b04e120e-689d-11e8-9a00-7dcf38f7a7df.png)

**Comment by whymarrh** [comment]
We've since updated the logic for handling timeouts when switching networks. If you're seeing similar issues on the latest version of MetaMask, please open up a new issue.
