### ISSUE TITLE
transactions not going through

### ISSUE THREAD

**Issue by TheKriptKeeper** [MetaMask/metamask-extension#4497]
Transactions have not been going through for a few days now. It's as though there is a backlog and a couple of transactions are not cancelling and not allowing any others to go through. Here is a screenshot attached. Address: 0xF89928aFC1b7214B2F95FEd9Eb82B0CcFe3C3C44
![error](https://user-images.githubusercontent.com/39943404/40961311-8d0e2656-68e5-11e8-8df2-f1b940b3693a.jpg)

**Comment by TheKriptKeeper** [comment]
EthQuery - RPC Error - Error: Error: [ethjs-rpc] rpc error with payload {"id":8936747568256,"jsonrpc":"2.0","params":["0xf86e8184850ba43b740083030d409463ba132c8c0103c70f187dcb4bad8d39d63603478802c68af0bb1400008025a021504087b397581e5bfb678c5b2ef746f4a96030afb368609ec672d3167399afa05b5c91cb7112c9ccc8562d1fa6dc23ade764dfa1b42c605164906f0b42f4a88e"],"method":"eth_sendRawTransaction"} Error: replacement transaction underpriced.

This error also coming through^^^^^

**Comment by TheKriptKeeper** [comment]
SOLVED. Just went to settings/reset.

**Comment by anthony33lewis** [comment]
So such simple fix was causing all that trouble... Should I reset also ?
Great ob by the way..

**Comment by TheKriptKeeper** [comment]
Are you having similar issues? Yes was a ridiculously simple fix. Didn't even see the reset button when looking around yesterday. Saw it in a blog just before!


________________________________
