### ISSUE TITLE
Firefox has blank screen when opening

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4501]
Versions 4.7.2-4.7.3 both opening the 'action view' with a blank screen, reports firefox user `Underdoggie` on our slack.

> having a re-draw problem with MetaMask loading the first time. The window is white.

**Comment by bdresser** [comment]
closing for #4501

**Comment by mallapurbharat** [comment]
Yes, I too am facing this same issue with Firefox 61.0.1 (64-bit) on Ubuntu. The metamask window opens up with a white blank window. However, if I resize the window even slightly, the controls are then displayed properly. Seems like a window sizing event is not firing, or not being captured properly.
