### ISSUE TITLE
Editing gas limit on Confirm screen does not change transaction total

### ISSUE THREAD

**Issue by passabilities** [MetaMask/metamask-extension#4508]
*  Expected Behavior
Edit the gas limit to update the transaction total cost.

*  Actual Behavior
Transaction total cost does not change.

*  Browser Used
Chrome

*  Operating System Used
Linux

![image](https://user-images.githubusercontent.com/6958300/40996897-02ee61f2-68d1-11e8-81a6-69e0bb2987e9.png)

![image](https://user-images.githubusercontent.com/6958300/40996914-12b98e36-68d1-11e8-92c2-96e171c4ec18.png)

**Comment by bdresser** [comment]
@passabilities I'm having trouble reproducing - could you give some more detail about how you encountered this error? were you sending from the extension yourself, or being requested by a dapp? did you edit by clicking in the top-right, or on the adjustment icon by the gas fee?

**Comment by passabilities** [comment]
This was a tx that my dapp requested. It fills in a gas price and limit. When I go to change the price by clicking on the adjustment icon from the screen in the pics above, it updates, but changing the limit has no affect. 

It appears, however, by clicking on the **edit** button in the top right, **adjustment icon**, **next** it then updates as expected.

**Comment by bdresser** [comment]
got it! thanks for the info, reproduced successfully. definitely worth fixing - heads up @danjm @danfinlay
