### ISSUE TITLE
Different token list for each network

### ISSUE THREAD

**Issue by levity** [MetaMask/metamask-extension#4518]
Since token contract addresses are different depending on the network you're on, if I'm testing a new version of a token that already has a mainnet deployment, then I have to add one address to my token list for mainnet and one for Kovan. 

Then I'm always going to see two items in my list for the same token, with one balance or the other always equal to 0.

So it would be nice if I could add a token just for Kovan and not see it show up in my token list when I'm on mainnet, and vice versa.

**Comment by bdresser** [comment]
relates to #3521

**Comment by Gudahtt** [comment]
This was completed in #4884
