### ISSUE TITLE
Repeated "Sorry, we are unable to locate this Transaction Hash"

### ISSUE THREAD

**Issue by JohnAllen** [MetaMask/metamask-extension#4520]
*  Expected Behavior when submitting a transaction the transaction is able to be found on etherscan
  *  Actual Behavior "Sorry, we are unable to locate this Transaction Hash"
  *  Browser Used `Chrome 66.0.3359.181`
  *  Operating System Used `MacOS 10.13.4`

**Comment by bdresser** [comment]
@JohnAllen sounds like this is the same issue reported in #4066, yeah?
