### ISSUE TITLE
Multiple clicks on "Confirm" button sends multiple tx (New UI)

### ISSUE THREAD

**Issue by yuxulong00** [MetaMask/metamask-extension#4532]
Briefly describe the issue you've encountered
  *  Send transaction by new UI(Beta)
  *  Quickly click the confirm button
  *  Chrome 67
  *  MacOS 10.13.4

![image](https://user-images.githubusercontent.com/1438549/41134906-699ac72e-6b01-11e8-8cf9-5bef1a3a0e94.png)

I send only one transaction by metamask,in confirm page i quickly click the confirm button,then the ethscan show me 6 record(my address:0xf6158f9fd763caa65cdd9607e77233397b370dde):

https://kovan.etherscan.io/tx/0x595bf36a8154e74d45f13057ebe528e6f0055c8ec192e9bdc5e4988469be1cba
https://kovan.etherscan.io/tx/0x2ba4e009b417b66e6f2241835f1b137f9acbc5fc297cc66e7df73701c07bfaa9
https://kovan.etherscan.io/tx/0xb30f4d79d4cd9179140d29023a2872e6bc9c078dc590dc399d21e6393fc4cc96
https://kovan.etherscan.io/tx/0xe35599abb6f90df0d958319e6013c9cca52ae5a239ff770e0a01ee4270a11c44
https://kovan.etherscan.io/tx/0xf4259b46c1e1a448900e63895934dfcc01c2bfbf8e26308bd7e2b7a3e93cfd1f
https://kovan.etherscan.io/tx/0xf76d61b2b9555762a8f092aed808cacb7db50d0119f58b4983a4111fe9d38816

I think the confirm button in new UI should be disabled after once click :)

**Comment by bdresser** [comment]
I've been unable to reproduce this, but we just heard the same from another user (https://github.com/MetaMask/metamask-extension/issues/4941). @alextsg or @danjm could you take a look?
