### ISSUE TITLE
E2E test for transaction retry in new-ui

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4547]
This was originally requested as part of https://github.com/MetaMask/metamask-extension/issues/3949

However, this is blocked by https://github.com/MetaMask/metamask-extension/issues/1999

I am going to close #3949 with the merging of #4546, and am creating this ticket for the outstanding task.

**Comment by Gudahtt** [comment]
We should do a thorough accounting in the near future of our e2e tests to ensure all of our UI is covered, but I don't think there is a need to track this gap in particular at the moment. I'll close this for now.
