### ISSUE TITLE
Create general purpose error display component

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4548]
Inspired by #4145.

Sometimes there are errors we haven't prepared for, and we should have a way to show them to the user.

**Comment by Gudahtt** [comment]
Since this issue was created, we have introduced a top-level Error page for any UI crashes. I think that covers this request adequately.

We still need to introduce unexpected, non-fatal error handling into each of our UI flows, but we'd need to do this on a case-by-case basis.
