### ISSUE TITLE
Signing a transaction - warning message

### ISSUE THREAD

**Issue by pdramorim** [MetaMask/metamask-extension#4549]
Hello,

I've decided to try my hand at selling a few tokens on EtherDelta to see how it works. I'm using MetaMask, so whenever I try to place a sell order I get the following warning:

"Signing this message can have dangerous side effects. Only sign messages from sites you fully trust with your entire account. This dangerous method will be removed in a future version.”

Will signing this message give the website access to my entire MetaMask account, along with the details of any other wallets that happen to be associated with it? Or will it just grant access to the wallet that happens to be in use in that particular moment?

Thanks in advance,
Pedro

**Comment by bdresser** [comment]
hey @pdramorim - EtherDelta is using an older signing method called `eth_sign`. This presents data to you in an unreadable format, which prevents MetaMask from showing you the contents of what you're signing. A bad actor could present a transaction for some amount of ETH, ask you to sign it, then submit it to the network. 

The action won't let the site access any of your other accounts. It doesn't even "grant access" to your currently used wallet, besides the attack vector I mentioned above.

You can read more about this warning here: https://consensys.zendesk.com/hc/en-us/articles/360004427792

**Comment by pdramorim** [comment]
Thanks for the quick reply @bdresser, much appreciated.

And apologies for the follow up, but just to be absolutely clear. Am I therefore right in understanding that even if I were to inadvertently sign an authorisation request presented by a bad actor, all I'd be risking would be the balance of whichever wallet I happen to be using with MetaMask in that particular moment? And that no private keys, seed words or any other type of login details would be at risk because of that?

I don't consider EtherDelta to be a trusted website, but I'm not looking to use it for large transactions. Would using a wallet containing only small balances for all my EtherDelta activities be enough to keep my larger balance wallets safe from bad actors in that particular space?
