### ISSUE TITLE
User Question: can I reject transaction in metamask from code?

### ISSUE THREAD

**Issue by Polina97** [MetaMask/metamask-extension#4563]
Hello. can anyone tell me if it is possible to reject transaction in metamask from code after few minutes, if user didn't submit or reject it by himself?

The problem is that the user of my site can submit transaction to my smart-contract within 2-3 minutes.  If the transaction is sent later, there is a possibility that the user will simply lose his/her ether

**Comment by bdresser** [comment]
@Polina97 not currently possible. exposing this level of permission to a web app has some implications for security. 

based on your brief description it sounds like this is best handled through your dapp's UI
