### ISSUE TITLE
executing estimateGas() return meta mask error

### ISSUE THREAD

**Issue by arashkiani** [MetaMask/metamask-extension#4564]
Executing the following code in both Chromium & Firefox returns error.

```
const deposit = contract.methods.deposit()
const abi = await deposit.encodeABI()
const gas = await deposit.estimateGas({from: myAddress, value: value})

```
  *  Browser (Chromium (Meta Mask 4.7.4 ) & Firefox (Meta Mask 4.2.0 ))
  *  OS: Ubuntu
  *  Network : Rinkeby

**in Chromium:** 

{code: -32603, message: "Error: gas required exceeds allowance or always fa…ogaeaoehlefnkodbefgpgknn/background.js:1:1070602)"}

Denying load of chrome-extension://.../background.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

Uncaught (in promise) Error: Returned error: Error: gas required exceeds allowance or always failing transaction

chrome-extension://invalid/ 0 ()

**In FireFox:** 

Error: Returned error: [597]</o.prototype.handleRequest/<@moz-extension://.../scripts/background.js:1:1341136

**Comment by tmashuang** [comment]
This might issue might have more traction on stack exchange/overflow.

Here's a link to [Ethereum Stack Exchange Error Gas Allowance](https://ethereum.stackexchange.com/search?q=gas+required+exceed+allowance) that others have asked and possible solved.
