### ISSUE TITLE
Address privacy concerns of auto-fauceting

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-extension#457]
To auto-faucet, a client has to send its address to our faucet URL.

This could be considered a breach of privacy to some users.

This came up in [a discussion on Reddit here](https://www.reddit.com/r/ethereum/comments/4svuqp/metamask_public_developer_beta_begins_our/d5e8v3j?context=3).

Also, since all accounts are seeded from the same faucet, it should be really easy to track new metamask vaults on the blockchain for anyone on it.  Maybe we should publicize this as Wallet 1 is your publicly known vault, everyone knows it's a MetaMask account.

**Comment by flyswatter** [comment]
I'm also open to simply making it more obvious that Wallet 1 is public with UI strategies.

**Comment by Zanibas** [comment]
We don't autofaucet anymore, so...
