### ISSUE TITLE
Bug in mozzila after last update (14.06)

### ISSUE THREAD

**Issue by deniscoman** [MetaMask/metamask-extension#4572]
Yesterday it worked perfectly, but today it doesn't work at all in mozzila. For chrome it's ok except that custom RPC problem. 
![screenshot from 2018-06-14 10-26-30](https://user-images.githubusercontent.com/29035132/41397839-1ec2c8c0-6fbe-11e8-8baf-23d298076110.png)

**Comment by deniscoman** [comment]
I tried to reinstall it, but nothing happend.

**Comment by bdresser** [comment]
thanks @deniscoman - we're tracking this issue in #3963
