### ISSUE TITLE
"Insufficient gas" error needs formatting

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#4579]
small formatting nit with the red error message shown when my account doesn't have enough to cover the gas:

<img width="346" alt="screen shot 2018-06-14 at 12 04 13 pm" src="https://user-images.githubusercontent.com/1016190/41432491-2c0f973a-6fcb-11e8-8e62-2cd4cbcc4f35.png">

<img width="754" alt="screen shot 2018-06-14 at 12 04 29 pm" src="https://user-images.githubusercontent.com/1016190/41432495-2eb896da-6fcb-11e8-9690-46608d579037.png">

don't know if more padding is the move - there maybe isn't space below the divider line but above the button. maybe above the divider line, or just below the last form field?

**Comment by danjm** [comment]
I think we can fix this with some minor tweaks to the css.

This modal will be getting a complete design overhaul when we implement the new designs referenced in https://github.com/MetaMask/metamask-extension/issues/3435

**Comment by raboid** [comment]
I've submitted a PR #5265 that is a small CSS change to improve this UX until the new designs are implemented.
