### ISSUE TITLE
[Metamask beta] send erc20 token failed with network disconnect, but etherscan shows two success token transfer.

### ISSUE THREAD

**Issue by jerry-sl** [MetaMask/metamask-extension#4589]
Bug Reports:

  I use Metamask BETA sending erc20 token, it quickly show failed at transactions list.
But when I check etherscan.io it show two same token transfer success.
  *  Expected Behavior
I should fail with no transaction or only one token transfer success.
  *  Actual Behavior
Two same transfer token success.
  *  Browser Used
chrome
  *  Operating System Used
Mac OS High Sierra

Screenshots:
![2221529139897_ pic](https://user-images.githubusercontent.com/5476062/41497497-1d17f3d8-711c-11e8-8ab1-bc1db833b922.jpg)

token transfer history:
![2231529139917_ pic](https://user-images.githubusercontent.com/5476062/41497499-2e575e72-711c-11e8-9d16-7cc8968858ac.jpg)

https://etherscan.io/address/0xfbfc47a4b7E528B01281DCd249D8EDA3B7a39396#tokentxns

**Comment by bdresser** [comment]
thanks for reporting @jerry-sl. was this a one-time thing, or are you able to reproduce reliably?

**Comment by jerry-sl** [comment]
@bdresser  It's not a one-time thing.   But it's hard to reproduce.

**I open two chrome tab each with metamask beta opened.** 
￼
![image](https://user-images.githubusercontent.com/5476062/42020102-8bccf3a0-7a7c-11e8-9729-abf4bd2055d7.png)

![image](https://user-images.githubusercontent.com/5476062/42019994-3a73c61e-7a7c-11e8-8b0c-eb7f4c2780b8.png)

**Comment by whymarrh** [comment]
@jerry-sl is this something you can reproduce on the latest version of MetaMask?

**Comment by whymarrh** [comment]
@jerry-sl I'm closing this for now, but please chime in with reproduction steps on the latest version of MetaMask
