### ISSUE TITLE
MetaMask is safe 100%?

### ISSUE THREAD

**Issue by HaiNguyen14** [MetaMask/metamask-extension#4590]
Metamask uses a (possibly centralized) repository to store information of wallet accounts. Is this a worrying issue? The worst thing that can happen is that the repository has problems such as being hacked.

**Comment by bdresser** [comment]
@HaiNguyen14 accounts and passwords are stored only on your device, never on a central server.

**Comment by HaiNguyen14** [comment]
okay, thank
