### ISSUE TITLE
[TASK] Implement mm-ledger-gateway

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#4593]
affects #4060 
<hr/>

(draft)

## Problem

USB access is not allowed for extensions, thus the Ledger hw-wallet cannot be accessed directly by MetaMask.

## Solution Summary

* Implement a "mini-metamask" within a chrome app, which accesses the ledger device directly
* Only the minimal functionality needed is implemented
* Allow the metamask-extension to connect to this "mini-metamask" chrome app

## Solution Details

This solution does not depend on the Ledger Native app. MetaMask would be able to communicate directly to the Ledger-Device, by using only the mm-ledger-gateway.

### A) ledgerjs

The relevant ledger libraries:

Preferred Path (Latest Ledger code, no native-code or desktop-app needed)

* https://github.com/LedgerHQ/ledgerjs
* https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-eth
* https://github.com/LedgerHQ/ledgerjs/blob/master/docs/ethereum_ledger_integration.md

### A.1) mm-ledger-u2f-gateway Chrome App

* Chrome App can access U2F and works with cross-extension-messaging

* Within this Chrome App, Implement a provider:
  * https://github.com/LedgerHQ/ledgerjs/blob/master/docs/ethereum_ledger_integration.md
  * allow only MM to access this app
* The provider is then accessed by MM using the same technique as here:
  * #3997
  * https://developer.chrome.com/extensions/messaging#external

The [eth-ledger-keyring](https://github.com/jamespic/eth-ledger-keyring) depends-on/accesses the **mm-ledger-u2f-gateway**

**User Manual:** "If you want to interface Ledger, you have to install additionally the **mm-ledger-u2f-gateway Chrome App**

### A.2) mm-ledger-u2f-gateway IFRAME

Same as above, but uses an IFRAME and (mm-extension-) internal-messaging

(no additional installation steps needed)

### Further alternatives

xyz = any applicable alternative transport 

* mm-ledger-xyz-gateway Chrome-App or IFRAME

## End Notes

The same Solution-Path should be applicable to other hw-wallets (including Trezor, for a more direct interfacing-approach than #4625)

**Comment by lazaridiscom** [comment]
The "A.2) mm-ledger-u2f-gateway IFRAME" was implemented within #5050

**Comment by ethanfrey** [comment]
Curious about the solution using chrome apps, as they seem to be deprecated... https://9to5google.com/2017/12/06/google-chrome-apps-dead-web-store/

But I guess the iframe solution won in the end

**Comment by lazaridiscom** [comment]
@ethanfrey , I somewhere saw that the end-of-life for chrome-apps was extended. Additionally, A.1 and A.2 use essentially the same messaging-technique, thus code produced for A.1 could be reusable for a A.2 implementation.

Both A.1 and A.2 implementations are not the final ones. They are just kind of workarounds, until a direct-access-layer  (U2F or WebUSB) for browser-extensions is provided by the browsers.

(feel free to contact me via info at lazaridis.com, here @ MetaMask the things are done/closed)
