### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by nolash** [MetaMask/metamask-extension#4596]
I have 4 accounts on my chromium metamask plugin. I run this snippet via http on localhost 

```
                window.onload = function() {
                        if (typeof web3 !== 'undefined') {
                                console.log("metamask");
                                web3 = new Web3(web3.currentProvider);
                        } else {
                                // set the provider you want from Web3.providers
                                console.log("whops");
                                //web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
                        }
                        web3.version.getNetwork(function(e, v) {
                                if (!e) {
                                        console.log("have network: " + v);
                                        console.log("have account: " + web3.eth.accounts[0]);
                                }       
                        });
                };

```
console outputs:

```
metamask.html:6 metamask
metamask.html:15 have network: 3
metamask.html:16 have account: undefined
```

Why is account undefined? Is there any particular setup required first?

Running `Version 67.0.3396.87 (Official Build) Arch Linux (64-bit)`

**Comment by lazaridiscom** [comment]
@nolash , if you still need help with this, you should try to contact support@metamask.io (please expect delays of up to one week).

**Comment by nolash** [comment]
@lazaridiscom ok so it's not a bug then?

**Comment by lazaridiscom** [comment]
Nah, its most possibly on your side.

Maybe you can find hints here: https://ethereum.stackexchange.com/questions/32551/web3-currentprovider-is-undefined-with-metamask

or place a separate question on stackexchange (but post the full code).
