### ISSUE TITLE
Token Specific Controls (dropdown)

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4598]
@bdresser Here's what I was thinking for consolidating token specific controls.

![image](https://user-images.githubusercontent.com/597770/41510237-d0777fb2-7215-11e8-9cea-6321acd024a8.png)

In full page mode, the "expand view" option is hidden since we're in full page mode. Thoughts?
![full page mode](https://user-images.githubusercontent.com/597770/41510269-5e91e1b6-7216-11e8-8066-1621e4a3aaf7.png)

**Comment by cjeria** [comment]
@danfinlay @kumavis  ^^

**Comment by bdresser** [comment]
@cjeria looks good to me, like the icons too. for now, i think it makes sense to get in #4591 to reach feature parity with the old UI in minimal dev time. once the new UI is default, we can neaten up & iterate. is that okay by you?

more generally, i have some questions about the logical distinctions between the top-right accounts menu, the tray on the left, and the different token views.

**Comment by bdresser** [comment]
also, the "hide account" option people keep asking about is relevant to this conversation (#1658)

**Comment by Gudahtt** [comment]
This was implemented a while back - we now have token option menus on the token pages.
