### ISSUE TITLE
Unable to send Ethereum from Metamask

### ISSUE THREAD

**Issue by neocodes** [MetaMask/metamask-extension#4599]
I'm running windows 8.1 and using chrome and latest MetaMask.

While sending ETH I am able to put all the details including adjusting gas price etc.
Now while submitting the transaction the screen is getting stuck, like below: 
![image](https://user-images.githubusercontent.com/12828698/41510174-75b14cbc-727d-11e8-8e53-ad81791c5016.png)

But unable to locate the transaction hash. (not clickable)
![untitled](https://user-images.githubusercontent.com/12828698/41515638-a2d56796-72cd-11e8-8daa-4cc305cc09c4.jpg)

Tried it twice and failed. But none of the time the funds deducted.

So went with sending it through MEW. Please help me resolve the issue as it is not safe to use private key for a transaction.

**Comment by bdresser** [comment]
@neocodes do you see any errors in the javascript console when this happens? 

and to clarify - you see the spinner get stuck, then you close the extension, and when you re-open you're on the main screen showing two transactions? or are these two separate issues.

**Comment by whymarrh** [comment]
Hey @neocodes, we've done a lot of work on the extension since and, most importantly, deprecated the old UI. If you're still seeing this issue or similar issues with the current MetaMask UI please feel free to open up a new issue.
