### ISSUE TITLE
Seed words Invalid - Previous suggestions have not helped

### ISSUE THREAD

**Issue by kaydub99** [MetaMask/metamask-extension#4600]
Hello, 

I have had an issue with our MetaMask account for quite some time. I have tried to login with the seed words, however the error still says seed words are invalid.  I have read the other issue regarding invalid seed words and have tried the suggestions (copy/paste, ensure all words are spelled correctly, lower case only, only 1 space between words) made there, however I am still unable to get into this account.  This account was opened in January 2018 via chrome extension on a windows 10.  I am hoping to be able to get into this account as there are tokens associated.  

Can you please advise on next steps and how to get this account recovered?

**Comment by bdresser** [comment]
hi @kaydub99, sorry to hear about your trouble. For user issues like this, please reach out to support@metamask.io and include a copy of your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI) to help them debug.
