### ISSUE TITLE
Stuck on "Connecting to Unknown Private Network" when connecting to HTTP endpoint on local network

### ISSUE THREAD

**Issue by techieanant** [MetaMask/metamask-extension#4604]
I have geth running on a raspberry pi with following settings:
--syncmode "light"
--rpc
--rpcaddr "10.0.0.145"
--rpcapi db,eth,web3
--rpcport 8545
--rpccorsdomain "*"

I'm able to connect to Geth Javascript Console from a different machine on the same network by typing "geth attach http://10.0.0.145:8545". I'm also able to send and receive transactions using MEW chrome plugin while connected to this HTTP endpoint, but Metamask gets stuck on "Connecting to Unknown Private Network". The generated background page shows this on console:

![image](https://user-images.githubusercontent.com/7658579/41564752-dcbf491e-7321-11e8-89c6-ecf2aa55bc0a.png)

  *  Expected Behavior
Metamask connects to the HTTP endpoint on local network similar to connecting it to localhost or an Infura node.
  *  Actual Behavior
Metamask gets stuck on "Connecting to Unknown Private Network". Trying to connect to mainnet not a private network.
  *  Browser Used
Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
  *  Operating System Used
Windows 10 Pro x64

**Comment by rookieofC** [comment]
I have successfully connected to the server private chain in a format like this: geth --identity "xxx" --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --datadir /home/xxx --port "30303" --rpcapi "db,eth,personal,net,web3" --networkid xxx --targetgaslimit xxx

**Comment by techieanant** [comment]
@rookieofC You've set the rpcaddr as 0.0.0.0, how did you connect to this RPC endpoint from a different machine on the network?

**Comment by rookieofC** [comment]
0.0.0.0 is for the external network to access your ip address，you can use http://IP:8545 in the new rpc url

**Comment by whymarrh** [comment]
Hey folks, we've done a lot of work on the extension over the past ~8 months and, specifically, we've updated how we handle timeouts when switching networks. Please open up a new issue if you guys are having similar issues with the latest MetaMask version. (That said, this as well looks like your local node might be misconfigured.)
