### ISSUE TITLE
Disabled/Enabled Extension > Accounts lost! 

### ISSUE THREAD

**Issue by aliparlar** [MetaMask/metamask-extension#4613]
Hello,

I had 3 accounts on Metamask, the extension became sluggish when trying to add a 4th account.

I have disabled/enabled it on chrome's extensions page.

Now the 2 accounts are vanished. Is there a way to restore these? I don't have the private keys to these accounts.

**Comment by bdresser** [comment]
@aliparlar if you created them via MetaMask - click "create account" again and you will recreate the same accounts. they're all generated from your seed phrase.
