### ISSUE TITLE
detect metamask version?

### ISSUE THREAD

**Issue by or2008** [MetaMask/metamask-extension#4619]
I would like to detect if a user uses the Beta version or the old one, is it possible?

**Comment by bdresser** [comment]
sorry @or2008, that's not currently possible. we don't even have analytics to know how many users are on the new UI vs the old.

out of curiosity, why would you like to detect which UI the user is on?

**Comment by or2008** [comment]
because unfortunately batch requests doesn't work as excepted with the new UI, I wanted to show my users a warning
