### ISSUE TITLE
Convert gas-fee-display-v2.js to follow pattern in the send/ directory

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4622]
`gas-fee-display-v2.js` is currently used by a couple confirm components and `send-gas-row`

Soon it will only be used by `send-gas-row`. It should be given its own directory within `send-gas-row/` and refactored to follow the pattern used for the other components in the `send/` directory.

In particular, the `gas-fee-display/` directory should have the following:
- `index.js`
- `gas-fee-display.component.js`
- `tests/` which will have `gas-fee-display-component.test.js`

Look at `metamask-extension/ui/app/components/send/send-content/send-from-row/from-dropdown/from-dropdown.component.js` and the rest of its directory for an example to follow.

**Comment by TrejGun** [comment]
i'd like to take this issue
