### ISSUE TITLE
Amalgamate ‘getCurrentCurrency’ and ‘getConvertedCurrency’

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4623]
In `metamask-extension/ui/app/components/send/send.selectors.js`, there are two functions that do the exact same thing: ‘getCurrentCurrency’ and ‘getConvertedCurrency’

One of these should be deleted. All cases where it is used should be updated to use the other.

**Comment by snreynolds** [comment]
@danjm Is anyone working on this? Seems easy enough.. so I can take a stab at it.
