### ISSUE TITLE
Bug - Does not refresh token balances when switching accounts

### ISSUE THREAD

**Issue by prographo** [MetaMask/metamask-extension#4631]
Bug.

  *  Expected Behavior
I have the TOKEN tab open, I see a token balance, I switch to another account, the token balance should refresh to reflect the balance in the account I am switching to. 
  *  Actual Behavior
It doesn't. Instead it still displays balance of previous account. (To make it refresh I switch to SENT tab then back to TOKEN tab.)
  *  Browser Used
Chrome
  *  Operating System Used
Apple Mac

<img width="349" alt="screen shot 2018-06-21 at 14 15 44" src="https://user-images.githubusercontent.com/11575008/41721391-a29b1fae-755d-11e8-8f6d-4dcf6ec282c7.png">

**Comment by bdresser** [comment]
Thanks for reporting @prographo. We're in the process of moving our users to a new UI, so we likely won't fix this issue. 

It doesn't exist on the beta version of the new UI, so if it bothers you try out the new version by clicking "Try Beta" in the top-right menu

**Comment by bdresser** [comment]
actually, duped by #3041

**Comment by prographo** [comment]
Thanks, I switched to beta, looks very good.
