### ISSUE TITLE
Should display values of EIP712 typed boolean fields in the signing prompt

### ISSUE THREAD

**Issue by weijiekoh** [MetaMask/metamask-extension#4639]
**Expected Behavior**
When MetaMask prompts the user to sign EIP-712 typed data, the preview of said data should display values of boolean fields if provided.
 
**Actual Behavior**
A blank space where one might expect to see "true" or "false". See the screenshot below.

Here is a demo of the bug in action: https://weijiekoh.github.io/js-eth-personal-sign-examples/index.html

This happens in the Beta UI as well as the regular UI.

**Browser Used**
Chrome 67

**Operating System Used**
Ubuntu Linux

**Screenshots**
<img width=400 src="https://i.imgur.com/dArKidf.png" />

**Comment by weijiekoh** [comment]
The issue worsens in Firefox 60.0.2:

<img src="https://i.imgur.com/VLmCJPR.png" width=500 />

**Comment by weijiekoh** [comment]
The issue on Firefox 60 with the non-beta UI: <img src="https://i.imgur.com/sOUHPLE.png" width=500 />

**Comment by weijiekoh** [comment]
Fixed with this PR: https://github.com/MetaMask/metamask-extension/pull/4640

**Comment by Gudahtt** [comment]
There has been a report that this has regressed: https://github.com/MetaMask/metamask-extension/pull/4640#issuecomment-666599237
