### ISSUE TITLE
Empty window instead of Authorisation window

### ISSUE THREAD

**Issue by prographo** [MetaMask/metamask-extension#4643]
On remix when deploying a contract to mainnet:

Bug
  *  Expected Behavior
Metamask should popup window to authorise transaction

  *  Actual Behavior
Metamask pops up empty window (I closed window and deployed again - worked - authorisation popup)

  *  Browser Used
Firefox / Metamask BETA.

  *  Operating System Used
Mac

**Comment by bdresser** [comment]
thanks @prographo 

also seeing in the add-on console
```
TypeError: gBrowser.tabContainer.uiDensityChanged is not a function  browser.js:5861:5
TypeError: gBrowser.tabContainer.updateVisibility is not a function
```

just to make sure, you see the confirm screen after clicking the fox in the top-right, correct? and you see the popup display correctly if you close the blank popup and try again?

**Comment by mallapurbharat** [comment]
I too have seen this kind of issue. In my case, this blank window kept popping up no matter how many deployments I did. Normally, the fix is to switch from one network to another, and then try again. Then I find that the window pops up properly.

**Comment by arisAlexis** [comment]
I have this problem also on Firefox 62 Linux.

Not only when sending transaction but also when using for example `web3.eth.personal.sign`.

There is an empty window popping up but if you press on the addon again on the toolbar the correct window pops up. The empty ghost window needs to be closed manually.

**Comment by whymarrh** [comment]
@prographo @arisAlexis are either of you still running into this particular issue with newer versions of MetaMask?

**Comment by prographo** [comment]
> @prographo @arisAlexis are either of you still running into this particular issue with newer versions of MetaMask?

Doing it all in Truffle now so no MM, only do the initial development in using remix. If you think you've fixed it, you could close it I think... if it's still broke, ppl will let you know soon enough. :)
