### ISSUE TITLE
Uncaught (in promise) Error: DappTokenSale has not been deployed to detected network (network/artifact mismatch)

### ISSUE THREAD

**Issue by louisdeck** [MetaMask/metamask-extension#4644]
- Expected Behavior : Correct balance showing up (100 ~)
- Actual behavior : Metamask  shows invalid balance (0) on my private network and blocks loading of my app
- Browser : Google chrome
- Operating System : Windows 10
- Code: https://github.com/dappuniversity/token_sale/tree/95a493d88989a6d4f26d80a75148a4257deced6c

Custom RPC input on Metamask : HTTP://127.0.0.1:7545/ (added / and solved a previous issue)

Screenshots : 
- Metamask : https://gyazo.com/f14f8b4280253511d0ed19762bbd6597 (first ganache account, it should be 99.42 ETH)
- Ganache : https://gyazo.com/5a9e1101e8568bd4f46519b9485b9749

I have also issued blank window Metamask, having to uninstall and reinstall it and a Metamask VM throw error revert (but can't show issue at the moment because of balance issue..).

**Comment by louisdeck** [comment]
I get rid of this error several days ago by adding a "/" at the end of the custom RPC address and this is working fine now (using website instead of the pop-up).

**Comment by bdresser** [comment]
@louisdeck good to know - i'll pass along to other folks who have experienced this issue and see it helps. thanks!

are you still experiencing the issue found in the title? if so, can you provide a little more detail?

**Comment by louisdeck** [comment]
Hello, no not experiencing this one anymore, this error was an easy one covering a bigger fish.
I've never figured out a pattern for this error but what I can say is that since I use the web front end instead of the window, I don't experience metamask chrome application issues anymore. 

I've sent a support @ metamask  about the new error, a metamask rpc error popping up during a transaction event (in terminal with truffle console or using the front end).
I'll wait metamask response, don't think this is appropriate to post a different error here.
I can send you what I sent to metamask support if you wish to know.

**Comment by bdresser** [comment]
Got it. Closing this for now, please feel free to start a new issue for the RPC error if it doesn't match anything that's already been opened.
