### ISSUE TITLE
Account listed twice

### ISSUE THREAD

**Issue by takeufoni** [MetaMask/metamask-extension#4653]
Windows 7 (64bit), Firefox 60.0.2 (64bit), Metamask 4.8.0

In dropdown list of accounts is one account listed twice. Second appeared without any my action. No matter which account is selected  (account 2/1 or account 2/2)  behaviour is same.

![image](https://user-images.githubusercontent.com/40516409/41808282-72b54fd8-76db-11e8-9d03-5fbe80b31e03.png)

**Comment by bdresser** [comment]
@takeufoni could you please send a copy of your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133392-How-To-Download-State-Logs-Old-UI-) to support@metamask.io and reference this issue? that'll help us debug

**Comment by bdresser** [comment]
might relate to #4704

**Comment by whymarrh** [comment]
@takeufoni is this an issue you can reproduce in the current MetaMask UI?

**Comment by bdresser** [comment]
closing, please let us know if you're still experiencing this
