### ISSUE TITLE
Hide converted price of token if no conversion rate found

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4661]
Currently on the send screen, if we do not have currency conversion data for a token, we show represent the converted amount as 0 in whatever the users selected currency is. For example, see the '$0.00 USD' in the screenshots of https://github.com/MetaMask/metamask-extension/issues/4645

If we do not have currency conversion information, we simply should not show a converted currency.

**Comment by danjm** [comment]
To replicate:

- switch to ropsten network
- go to https://faucet.metamask.io/ and request 1 ether from faucet
- go to https://tokenfactory.surge.sh/#/ and create token contract (e.g. Enter: 100, ABC, 0, ABC to keep things simple)
- once the token is created, copy the contract address
- back in metamask, click "Add Token"
- click the "Custom Token" tab and copy the address of the token you just created, the other fields should autopopulate
- click Next and Next
- select the newly created token in the sidebar
- click 'Send'

You will see the above describe issue on the send screen

**Comment by snreynolds** [comment]
Closed with #4777
