### ISSUE TITLE
Move `removeLeadingZeroes` to `send.utils.js` and add unit test

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4665]
Move the `removeLeadingZeroes` method from `metamask-extension/ui/app/components/send/currency-display.js` to `metamask-extension/ui/app/components/send_/send.utils.js` and add a unit test to `metamask-extension/ui/app/components/send_/tests/send-utils.test.js`

**Comment by TrejGun** [comment]
i'd like to work on this
