### ISSUE TITLE
The EOS chain has been launched. Does MetaMask plan to support it?

### ISSUE THREAD

**Issue by cppfuns** [MetaMask/metamask-extension#4671]

**Comment by lazaridiscom** [comment]
I've not done my homework re EOS, so I cannot answer even theoretically.

Please have a little patience, you should get an answer from the the devs within a few days.

**Comment by Gudahtt** [comment]
One of our goals with the [upcoming snaps system](https://medium.com/metamask/introducing-the-next-evolution-of-the-web3-wallet-4abdf801a4ee) is to allow developers to implement their own MetaMask integrations for chains like EOS. It is doubtful that we'll provide first-party support for EOS, but I'd recommend checking back once snaps has been released to look for an EOS snap!
