### ISSUE TITLE
hi all. i am totally new to crypto and meta mask, and in need of some help .

### ISSUE THREAD

**Issue by larrym3235** [MetaMask/metamask-extension#4684]
unable to send funds from my wallet, i am unable to send any funds from my chrome extension meta mask wallet . no matter how much gas i use. it comes back as a failed transaction or still pending . i can receive funds straight away . any help would be greatfull.

**Comment by lazaridiscom** [comment]
Are you sure you enter all relevant data correctly (possibly a screenshot could help).

Additionally: for this kind of user-level issues, you can contact support@metamask.io to get some help.

**Comment by bdresser** [comment]
@larrym3235 as lazaridiscom mentioned, you should reach out to support@metamask.io 👍
