### ISSUE TITLE
Chrome desktop apps crashes when signing transactions

### ISSUE THREAD

**Issue by tonygustafsson** [MetaMask/metamask-extension#4688]
Excepted behavior: 
When signing transactions for IDEX I open MetaMask (not opened by itself any longer) and press Sign. I except any other chrome windows to not crash :D

Actual Behavior:
Any chrome apps, like when you save a page to desktop and open it without the address bar and such. They all crash when MetaMask asks for a sign.

Browser used:
Chrome 67

Operating system used: Windows 3.1 (OK Win 10, latest updates).

**Comment by lazaridiscom** [comment]
This sounds like a bug. Please have a few days patience until a core-dev can take a look.

(if possibly: can you name one concrete chrome app that crashes? )

**Comment by tonygustafsson** [comment]
Yes of course. If you make an app off https://www.messenger.com (In chrome More tools > Create shortcut (I think it was named Save to Desktop before). Then run the app and open MetaMask by clicking on the awesome fox - and your app will close.

**Comment by tonygustafsson** [comment]
I think Google were talking about apps that you install from their store
when they said that they were to be removed. This is more of a Progressive
Web App (PWA) kind of thing. Save to desktop works fine on mobile and can
give reative web pages app like capabilities.

Google just talked about supporting this for desktop. It kind of works all
ready, but they are going to be more native looking. But yeah, you can wait
for this new system to be included and see if the issue persist.


sön 1 juli 2018 kl 04:22 skrev Bruno Barbieri <notifications@github.com>:

**Comment by jennypollack** [comment]
closing for now, can revisit when supported
