### ISSUE TITLE
Restored by seed words BUT get different set of accounts except for the main account.

### ISSUE THREAD

**Issue by ludosone** [MetaMask/metamask-extension#4697]
I've met this white screen issue:
https://github.com/MetaMask/metamask-extension/issues/1372

and checked lots of solutions but failed to solve the problem, including switch to test nets and get back.

and occasionally I saw this video:
https://www.youtube.com/watch?v=cqz8-hOz_nk

I had the seed words(fortunately)

and I understand that I can restore the origin sets of accounts by the single set of seed words.

I removed the extension, reinstall it, and then it turns out that the main account is intact but other accounts are GONE, and it seems that I've lost tens of ETHs here.

I tried creating new accounts, but I only got new ones, not the ones that I have assets stored in.

QUESTIONS:
so I believe the MetaMask is based on HD wallet structure,
and for some reason the dev team changed the algorithm of generation new accounts from the root seed??

(I'm using 4.8.0, the removed version is still 4.8.0)

Pleeeeeeeeeeeeease help me out of this!!

Thanks.

**Comment by lazaridiscom** [comment]
> so I believe the MetaMask is based on HD wallet structure,

yes

> for some reason the dev team changed the algorithm of generation new accounts from the root seed??

no (at least not intentionally), it's the same standard.

## What you could try

MetaMask HD wallet is standards based, so you can use the seed-words to 

* install MetaMask in another Browser, try the recreation there

* recreated your accounts in any other Eth HD wallet, see https://github.com/MetaMask/metamask-extension/issues/1372#issuecomment-334561203  for example wallets)

* If you know your initial MetaMask version (that one which created the seed-words), install it manually from https://github.com/MetaMask/metamask-extension/releases and recreate from your seed.

* verify the info within kvhnuke/etherwallet/issues/1013 (e.g. password), this will possibly give you a hint.

If all of the above fail to recreate your accounts, then I'm out of ideas. You could contact support@metamask.io (expect a few days delay) or await another response here (again, please expect a few days delay)

**Comment by bdresser** [comment]
@ludosone, sorry to hear about your issue.

As laxaridis mentioned, you should reach out to support@metamask.io for personal help recovering your funds/accounts, if possible.

Issues concerning seed generation and account recovery are taken seriously. We have a standing bounty for anyone who discovers a reproducible issue: https://github.com/MetaMask/metamask-extension/issues/3127.

If you encounter this again, or if you can provide more info, please let us know. In the meantime, I'm going to close this issue and reference it on the bug bounty so anyone who investigates has a full list of reports.
