### ISSUE TITLE
CANT GET MY DEBITUM.Network tokens

### ISSUE THREAD

**Issue by danielhtht** [MetaMask/metamask-extension#4700]
I HAVE CONNECTED MY METAMASK TO MY ETHER WALLET AND TRIED TO TRANSFER MY TOKENS TO AN EXCHANGE BUT THE TRANSFER NEVER GETS DONE, I HAVE TRIED WITH ALL THE GAS PRICES AND YES I DO HAVE ETH TO PROCESS THE TRANSFER

**Comment by bdresser** [comment]
@danielhtht try checking etherscan for your tx status and what address they ended up at. if you need more help, please reach out to support@metamask.io.
