### ISSUE TITLE
Entering RPC URL doesn't change network

### ISSUE THREAD

**Issue by snreynolds** [MetaMask/metamask-extension#4705]

**Comment by snreynolds** [comment]
Clicking "save" doesn't do anything... about the 3rd time this has happened to me. 

<img width="354" alt="screen shot 2018-07-02 at 11 21 57 am" src="https://user-images.githubusercontent.com/30504811/42179985-5ab43a6e-7dea-11e8-9568-13791680a1b9.png">

**Comment by bdresser** [comment]
@snreynolds check if you can scroll up? sometimes there are validation errors that only appear at the top of this screen, so it seems like nothing is happening.

**Comment by snreynolds** [comment]
@bdresser -- Scrolled up and nothing appears. Also, this happens in the OLD UI as well.. It will connect to the private network only when I click out of MetaMask and then open it up again. Even then, the accounts from ganache don't show up with the 100ETH.

**Comment by bdresser** [comment]
hmm interesting @snreynolds. can you check if you already have `http://127.0.0.1:7545` in your network dropdown?

the ganache bug has been reported in #3245 but i've never been able to reproduce. could you send thomas and me your state logs via slack? not sure there'll be anything useful in there but can't hurt.

**Comment by EduardoCortesL** [comment]
Hey @snreynolds  I'm having the exact same issue, It shows is connected to the private network but does not show the balances.

**Comment by EduardoCortesL** [comment]
So I figure out a workaround, you re-install metamask. Click on import DEN and write the 12 words given by Ganache/TestRPC. After you register with a new password, you go to `Coustom RPC` and write the `RPC URL` you have from Ganace/TestRPC, after it connects you should be able to see the balance of those accounts.

**Comment by bdresser** [comment]
Closing this - I think partially mitigated by the fix to #4253, and the rest should be taken care of in a better format for the error message
