### ISSUE TITLE
METAMASK (FAILED), Etherscan (success), Funds gone, But where? 

### ISSUE THREAD

**Issue by SCXXX1234** [MetaMask/metamask-extension#4706]
Hi everyone, 

Metamask says my transaction is failed, but my tokens are gone, and etherscan says success, but the tokens don't appear in the exchange wallet I deposited them into....I even did a test transaction before this that worked. 

This is the TX i am talking about https://etherscan.io/tx/0xed83aef79c6c1fcad85b523a96b127c5b9c65bace2b4fb8e9049fac5949da65f

Sam

**Comment by bdresser** [comment]
@SCXXX1234 looks like they were both successful: https://etherscan.io/token/0x4092678e4e78230f46a1534c0fbc8fa39780892b?a=0xed7738fd852c0a05aeb085ab06c6140a0d76d16d

exchange wallets sometimes take a while. if it never shows up, this is likely a problem with your exchange.

if you need more help, please reach out to support@metamask.io

**Comment by SCXXX1234** [comment]
Thank you, its been like 3 hours so I hope it gets there soon
