### ISSUE TITLE
Updating eth-contract-metadata

### ISSUE THREAD

**Issue by tomhschmidt** [MetaMask/metamask-extension#4707]
How often does Metamask update which version of eth-contract-metadata it uses? https://github.com/MetaMask/eth-contract-metadata

I added ZRX to the eth-contract-metadata repo a few months ago, but it still isn't showing up in the latest version of Metamask.

**Comment by bdresser** [comment]
@tomhschmidt definitely due for an update - we'll make sure we're on the most recent version of eth-contract-metadata in our next release, either later this week or early next.

**Comment by bdresser** [comment]
taken care of in #4709
