### ISSUE TITLE
web3.version.getNetwork returns 'loading'

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#4714]
If I set Firefox to open new Firefox windows to a dapp that calls `web3.version.getNetwork` on event `'load'`, I get no error but instead the result `'loading'`, which is a case that is undocumented. ~I believe the origin of this string is `ui/app/send-v2.js`, so~ this might be a metamask-only behavior.

**Comment by bdresser** [comment]
@wjmelements firefox only, not on chrome?

**Comment by wjmelements** [comment]
I don’t think chrome lets you set a homepage

**Comment by wjmelements** [comment]
Okay I found how to set a startup page in Chrome. That gives `null` instead of `'loading'`.

**Comment by wjmelements** [comment]
I think loading and null are different states. My firefox extension is actually stuck in the loading state:

<img width="356" alt="screen shot 2018-07-03 at 2 02 33 pm" src="https://user-images.githubusercontent.com/799573/42244433-ddea20e4-7ec9-11e8-9d62-9660e864b51f.png">

**Comment by wjmelements** [comment]
Multiple people reporting the loading issue on reddit: https://www.reddit.com/r/Metamask/comments/8x3bxh/loop_connecting_to_main_ethereum_network_anyone/
