### ISSUE TITLE
Update key names for props that are meant to receive translation keys

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4726]
As per a discussion with @alextsg and @whymarrh:

If a ui component has a property that is a string which will be translated, then the name of the prop should always end with 'Key'. This is to make clear to the user of the component that the property is meant to receive a string that will be translated, and not a string that will be rendered exactly as passed.

We need to update all components in the `ui/` directory that pass props to the translation function to match this change.

**Comment by TrejGun** [comment]
i can work on this

**Comment by haxwell** [comment]
Hello.. new guy, looking through Good First Issues here.. Can anyone verify this is still an issue? I looked and it doesn't seem the code from the July 4 merge still exists, and I can't, with my cursory effort, tell if the current components need this treatment.

**Comment by Gudahtt** [comment]
This appears to be done already
