### ISSUE TITLE
Transaction memo's in new UI

### ISSUE THREAD

**Issue by abitrolly** [MetaMask/metamask-extension#4727]
There is no way to set memo for transactions in new UI in version 4.8.0.

Memo could add automated hints to items (preferable) to help understand transaction, and also allow manual commenting (less useful, spends time). First could be implemented as tooltips or graphics.

**Comment by bdresser** [comment]
thanks @abitrolly - this is duped by #2335

**Comment by abitrolly** [comment]
@bdresser set no see.
