### ISSUE TITLE
Check box to agree to terms

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-extension#4737]
It would be cool to add some kind of warning explaining that you must "read" or scroll down  all the notices (TOS / Phishing alerts, etc)  in order to continue, rather than just disabling the button.

This might cause some users to be confused and abort the onboarding process cause they don't know how to proceed.

![screen shot 2018-07-05 at 2 09 38 pm](https://user-images.githubusercontent.com/1247834/42341501-435d0fca-8061-11e8-840f-59651051f60e.png)

cc: @cjeria

**Comment by bdresser** [comment]
Do we even need to require that the user scroll all the way to the bottom before the button is active? 

Other apps just link to the terms and say "do you agree?" which is admittedly a little whack but certainly easier.

I would be satisfied if we displayed the whole text but allowed clicking through automatically.

**Comment by bdresser** [comment]
![terms](https://user-images.githubusercontent.com/1016190/45451483-15aceb80-b690-11e8-82a8-2c96ff238acc.jpg)

Like every other sane product in the world...

@cjeria feel okay? I assume kyo can use the standard styling but if you wanna push a smoother version be my guest :)

**Comment by bdresser** [comment]
handled as part of #6163
