### ISSUE TITLE
Pass `origin` HTTP header on requests to Infura

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#4739]
Adding a MetaMask-specific header to Infura requests will let us segment our traffic and understand more about daily usage. 

This header used to exist but was pulled because it caused issues with custom RPC options. We should only include the header when we're certain the request is headed to Infura. See #2250 and maybe #2138.

Prior implementation used `x-metamask-origin` – we should check with Infura team to see if this is suitable, or the simple `origin` header will do, or if there's something else they prefer

**Comment by bdresser** [comment]
relates to #4279

**Comment by bdresser** [comment]
@danfinlay @kumavis any concerns with using `x-metamask-origin` and passing through the dapp that initiated the transaction? This should let us see total numbers from MetaMask as well as generate a list of dapps folks are using (beyond what Infura is able to look up by contract)

**Comment by danfinlay** [comment]
I think that's fine, I believe that's what we used previously. I would want @kumavis to chime in on whether this is going to trigger a preflight.

**Comment by whymarrh** [comment]
As an FYI, the `X-` prefix for custom headers is deprecated ([RFC 6648](https://tools.ietf.org/html/rfc6648)) so if possible we might want to talk to Infura about their desired custom header (e.g. maybe a `Infrua-Source: MetaMask/<dapp name>` or something).

**Comment by whymarrh** [comment]
Did we hear back from Infura about which header they'd like us to implement?

**Comment by bdresser** [comment]
implemented in MetaMask/metamask-extension#6023
