### ISSUE TITLE
Update to react 16.x

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4740]
Currently we are still on react 15. We should update. The task to update should include:

- checking the react 16 breaking changes against our code, updating/fixing if necessary
- checking that all dependencies are compatible, replacing when not
- replacing lifecycle methods that are deprecated in react 16
- thorough QA

Maybe we should do it after deleting old-ui, to reduce the amount of possible imcompatabilities.

**Comment by TrejGun** [comment]
i'd like to work on this, i have already started refactoring and can do this after I finish all components

**Comment by whymarrh** [comment]
@TrejGun this is something we may want to discuss and schedule internally, so I think it'll be easier if we take this on (I may very well end up tackling this myself). That said, we appreciate your enthusiasm and you've made a number of strong contributions so we're happy to work on identifying some larger issues that you can take.

**Comment by josx** [comment]
We can do the first steps to migrate in the future. At least we need to avoid warnings like:

```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
```
```
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```
There is branch With some commits but still not merge:
https://github.com/MetaMask/metamask-extension/tree/uat
