### ISSUE TITLE
Brave and metamask

### ISSUE THREAD

**Issue by onehates** [MetaMask/metamask-extension#4741]
I am running brave 0.23.19 and metamask 4.3. When I try to open metamask in brave, metamask just loads and empty screen and kind of "shakes" nonstop. Clicking the icon again will just load the same behavior...

![image](https://user-images.githubusercontent.com/29721161/42355675-518e2d46-809c-11e8-9db3-7c05f78f4191.png)

![image](https://user-images.githubusercontent.com/29721161/42355641-1be26d24-809c-11e8-8928-fbaf4202deba.png)

**Comment by bdresser** [comment]
@onehates i'm on the same MM & Brave versions but am not seeing this issue. Sometimes on first open I get a blank or empty box, but on second open it always loads fine.

What OS are you running? And do you remember if you're on the new/beta UI or the old UI?

**Comment by onehates** [comment]
Right actually the first time I open it, it does 

![image](https://user-images.githubusercontent.com/29721161/42405074-77ba266a-815e-11e8-970f-8db9db342395.png)

Like you said, this happens the second time I open it.. It is basically those two screenshots redrawing on top of each other over and over....

**Comment by jennypollack** [comment]
Hey @onehates, the Brave MM extension version has just been bumped to 4.8.0
Closing this as we believe it should be fixed, but please reopen if you still experience the issue after update.

**Comment by onehates** [comment]
Sorry I was out of town the past week. When Iook at extensions in brave, it shows Metamask as on, and the version as 4.3. When I disable this it shows this as the latest version.  Isnt this supposed to auto update in brave?
