### ISSUE TITLE
Metamask Beta has no transaction data field

### ISSUE THREAD

**Issue by 1blockologist** [MetaMask/metamask-extension#4745]
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
When forming a transaction, amount, gas settings and transaction data should be present.
  *  Actual Behavior
When forming a transaction, amount, gas settings are present, but transaction data is absent.
  *  Browser Used
Chrome
  *  Operating System Used
OSX

  Screenshots are very helpful and will expedite your issue being resolved!

Old UI has a transaction data field easily visible and part of transaction formation

![image](https://user-images.githubusercontent.com/21366360/42359037-0ee041fc-80e0-11e8-9e52-b2f9ae31cf7a.png)

New UI seems to have it nowhere to be seen.

**Comment by 1blockologist** [comment]
#3367

**Comment by bdresser** [comment]
closing in favor of #3367
