### ISSUE TITLE
If webpage javascript code contains function called setTimeout - it get's called by Metamask plugin

### ISSUE THREAD

**Issue by vbresan** [MetaMask/metamask-extension#4750]
Just as the title says. 

If any web page that you open with a browser contains the definition of function called setTimeout - this function will be invoked by Metamask plugin instead of it's own setTimeout function.

I am sending the javascript console output which logs received function parameter as well:
"ƒ (t){if(t)return i(t);o=!0,i()}"

![clipboard01](https://user-images.githubusercontent.com/288855/42391515-f31fa5aa-814f-11e8-8dce-3b85849d3456.png)

**Comment by whymarrh** [comment]
@vbresan thanks for reporting this. There are a lot of global functions provided to JavaScript applications by the runtime,<sup>[\[1\]](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope)[\[2\]](https://developer.mozilla.org/en-US/docs/Web/API/Window)[\[3\]](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope)</sup> `setTimeout` being one of them—unfortunately it would be impractical to bundle our own versions of each of the functions and the standard [built-in objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects) so we are expecting websites to not overwrite these functions.

A lot of things will break when websites and apps override the runtime-provided globals and that's not really a case we can easily work around.
