### ISSUE TITLE
Migrate test deps job to npm audit

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-extension#4751]
NSP is shutting down in 3 months so the build will break at that time.

https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

Also, there's no way to ignore vulnerabilities (via .nsprc) that we can't fix so we might need to disable this job temporarily until npm takes care of this. More info: https://github.com/npm/npm/issues/20565#issuecomment-391706973

**Comment by roseandcolumns** [comment]
@brunobar79 Hi, I'm new to this project. I was looking into this issue and it looks like this setting might live in userland. I'm not entirely positive. [docs](https://docs.npmjs.com/getting-started/running-a-security-audit#installing-all-packages)

**Comment by brunobar79** [comment]
@roseandcolumns  I think I might use that setting before running npm install since we have a separate build step "test deps" which takes care of that.  It won't fix this specific issue but it will help npm install to run faster (since it doesn't have to audit all the packages).
