### ISSUE TITLE
Status request on including ETC mainnet

### ISSUE THREAD

**Issue by 34r7h** [MetaMask/metamask-extension#4753]
Hi, saw https://ambcrypto.com/ethereum-classic-etc-support-with-metamask-coming-soon-says-ecc-director/ and hoping to learn where we are in the pipeline and if there's anything to help with.

Thanks!

**Comment by johcam12** [comment]
+1

**Comment by hackmod** [comment]
Please see https://github.com/MetaMask/metamask-extension/pull/4516

*work in progress.*

**Comment by irthos** [comment]
Groovy thank ya. Any discussion around this yet or direction to lend a hand?

**Comment by tmashuang** [comment]
You can push feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests.
