### ISSUE TITLE
Installed metamask extension yesterday. Closed firefox, when reopened password didn't work. Restored from seed, different account. 

### ISSUE THREAD

**Issue by CrypticAutistic** [MetaMask/metamask-extension#4756]
Installed the metamask extension yesterday. Set up my password, copied down my seed phrase, and proceeded to fund it with some ether. Today, after reopening firefox, i click on the extension and my password doesn't work. Luckily, i screenshotted the seed phrase yesterday. I put the seed phrase in. The account that it restored is a totally different address with no ether in it. W......t.....f.

**Comment by rdymac** [comment]
Hello there, 

​If you are seeing at least the first account correctly (Account 1), you will need to re-CREATE the other accounts using the top-right icon until you get all the ones you want.  As the wallet is deterministic you only need the seed phrase you've backed up, as it will always recreate the same Accounts in the same order.

If you had other specific addresses manually imported, take into account that those imported addresses' private keys cannot be restored with your wallet seed phrase, you need to have them backed up in paper separately along with your your 12 words seed phrase.

Did you try using the Create Account button to regenerate the other derived accounts to see if one of those is the one you are looking for?

**Comment by CrypticAutistic** [comment]
I tried that. I had never created any other accounts, so no, that didn't work. I have seen in other threads going back to last year that there is a bug where metamask will create two completely separate accounts when someone first installs it, and gives the seed for the first, but shows the second. Then when the browser is closed, it erases any record of the first one which is what was being used. It seems as though the bug is still around.

**Comment by bdresser** [comment]
@CrypticAutistic are you on 4.8.0? what browser & OS? and are you able to reproduce this reliably if you uninstall & re-install the extension?

it'd also be helpful if you could email your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI-) to support@metamask.io and mention this issue number (cc @rdymac)

**Comment by bdresser** [comment]
@CrypticAutistic I'm going to close this issue for now and point you towards the standing seed phrase bug bounty https://github.com/MetaMask/metamask-extension/issues/3127. 

We take reports like this very seriously, and we're willing to pay a bounty to anyone who finds a reproducible issue with how this portion of our application works.

I'll reference this issue there, so anyone investigating can have this as reference. Sorry for your trouble.
