### ISSUE TITLE
hacked , phished ?

### ISSUE THREAD

**Issue by 7nicoale** [MetaMask/metamask-extension#4757]

**Comment by 7nicoale** [comment]
3 times  eth. was missing from my metamask account. 
hire is where it went : https://etherscan.io/address/0x79675145ff147e3e21ac99fb3aa9969633d4f3ff
In realised that on 3rd time when I send eth. to wallet log out, and when log in after 2-3 hours there was nothing. coinbase showed the transaction complete, and I followed this transaction.
What are my actions now? How I can get back my eth? 
and the most important it is safe for my to use or keep tokens on metamask?

**Comment by bdresser** [comment]
@7nicoale, sorry to hear about your issue. We've heard reports of phishing strategies becoming more and more common, so be careful out there – never enter your seed phrase unless you're certain it's MetaMask that's asking for it. 

Read our medium post for more info: https://medium.com/metamask/new-phishing-strategy-becoming-common-1b1123837168

And for more help, please reach out to support@metamask.io
