### ISSUE TITLE
White screen when trying to open metamask on firefox ubuntu 18 

### ISSUE THREAD

**Issue by alin101** [MetaMask/metamask-extension#4758]

**Comment by JesseBusman** [comment]
I might have the same problem (also Firefox, Ubuntu 18.04). When I click the Metamask icon I get a white screen. It closes on its own after about a quarter of a second.

**Comment by bdresser** [comment]
this is duplicated by #3963 and #4502

Some users have had success updating to Firefox 61. If that doesn't solve the issue for you, any extra info you can provide on #3963 would be helpful.
