### ISSUE TITLE
Allow user to force-inject web3

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#4759]
Once #4703 is merged, web3 will not be exposed by default and dapps will be expected to request user consent to access an Ethereum provider API as per [EIP 1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md)

It's possible that some dapps will not update immediately, and users on the newest MetaMask who visit these dapps will be left in limbo: the site will expect web3 by default, and the user will be waiting for the site to request access.

As a fallback in these situations, it makes sense to allow the user to choose to expose the web3 object so that these dapps are still usable. 

A common flow might be
(1) user visits dapp; dapp says "Unlock MetaMask" or the equivalent
(2) user enters MM password OR user checks and sees MM already unlocked
(3) dapp still says "Unlock MetaMask"
(4) user sees something in the extension (this feature), clicks "force log-in," dapp proceeds as usual

At first, we might need to place this somewhere visible. Hopefully this is a temporary feature that can be relegated to the settings menu once most dapps catch up. There's a tricky communication challenge, as users will have to understand enough of what's going on to know they need to take action. Could be something like a banner along the top/bottom with "Dapp unresponsive? Force log-in." 

@cjeria @danfinlay @bitpshr any thoughts on how to explain what's happening or surface this action?

**Comment by cjeria** [comment]
@bdresser To make this feature easy to understand, I suggest we go with a simple "login" request from within the extension. Early on in discussing this feature, I had put together this ux flow that displays an "action sheet" in MetaMask if there's a dapp requesting user consent to expose web3 (in effect loging the user into the dapp). 

![artboard](https://user-images.githubusercontent.com/597770/42474497-a60ea4a8-837c-11e8-9b73-719b7d8fd482.png)

**Comment by bdresser** [comment]
@cjeria for sure - this issue is for an edge case to help with backward compatibility, where a user is trying to interact with a dapp that hasn't updated to match this new standard. So the dapp doesn't know it's supposed to request access to web3, and instead is just waiting for the web3 object as dapps do now. Creates a sort of dead-end for the user that it'd be nice to solve for.

Chatted with @bitpshr and he has some concerns with technical feasibility, so let's wait til we have a better sense of how this would work.

**Comment by bdresser** [comment]
Not gonna happen - will instead implement 1102 as an optional protocol during the grace period before rollout
