### ISSUE TITLE
Is it a bug?  

### ISSUE THREAD

**Issue by santos177** [MetaMask/metamask-extension#4763]
I sent 0.005 ETH to my friend, but 1 minute later his metamask sent the money to another address without his permission. Is it an bug? or  maybe metamask was hacked?

This is my transaction:
https://etherscan.io/tx/0x7e40468fa27c386398f2a00305153ed15e77d30f0b650cda88e1c395faa242a6

This is this the transaction without permission:

https://etherscan.io/tx/0xe357c5e176bc297b9cf1e4aa7a302726ec9d8056b4f08dab29067d284ccc0757

Thanks !

**Comment by bdresser** [comment]
@santos117 it's possible your friend had been the victim of a phishing attack, or he otherwise compromised his seed phrase. It's probably best to reach out to support@metamask.io with this one and they'll be able to help you off this public forum. Sorry to hear about the trouble!
