### ISSUE TITLE
development tools are broken

### ISSUE THREAD

**Issue by TrejGun** [MetaMask/metamask-extension#4768]
`npm run ui` is completely broken because  `modifyBackgroundConnection`, `backGroundConnectionModifiers` are not passed to Select

`npm run mock` throws thousand of errors related to incomplete state from `./development/states.js`

**Comment by whymarrh** [comment]
@TrejGun thanks for reporting this. Clearly these scripts have fallen to the wayside as we focus on the new UI—I think long term we're going to remove these in favour of different/better devtools.
