### ISSUE TITLE
ethjs-rpc : error from payload : invalid sender ( ChaidID and Networkid same but not working?)

### ISSUE THREAD

**Issue by CryptoBeginner** [MetaMask/metamask-extension#4770]
`{
  enode: "enode://13c7dc3f40f4e24cf3a877bfba1de7e7ead99b614d09d3f97457c4de163f6776783674e1a6e3be2807c4aadc62798b355ceadc442c1f037887ae26453769fb1a@0.0.0.0:30303",
  id: "13c7dc3f40f4e24cf3a877bfba1de7e7ead99b614d09d3f97457c4de163f6776783674e1a6e3be2807c4aadc62798b355ceadc442c1f037887ae26453769fb1a",
  ip: "0.0.0.0",
  listenAddr: "[::]:30303",
  name: "Geth/v1.8.4-stable/darwin-amd64/go1.10.1",
  ports: {
    discovery: 30303,
    listener: 30303
  },
  protocols: {
    eth: {
      config: {
        chainId: 15,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0
      },
      difficulty: 49013904,
      genesis: "0xb84d353a97ce9e68626f118da7dfc197ddf51b3ef57211f04642ad1aeea26093",
      head: "0x83677f34a044f5febbae05aa6a2fd74243ac511d01d24143925cabbda10b5deb",
      network: 15
    }
  }
}
`
Im having this issue with localnode using geth with above setting yet get 
ethjs-rpc : error with payload : invalid sender.

i have tried to make the networkid to 15 and chainID to15 but not working.

**Comment by CryptoBeginner** [comment]
fixed 
it works!

**Comment by mawenpeng** [comment]
> fixed
> it works!

Hi buddy,
Would you please share your workaround? I believe many guys got such issues, including myself.
Thanks.
