### ISSUE TITLE
New UI: Send Token Screen Improvements

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4772]
@cjeria 

We got a user in our support system who was frustrated with our send token screen. In their case, they had an account with many UTK tokens, but no ether, resulting in this experience:

![screen shot 2018-07-11 at 9 52 50 am](https://user-images.githubusercontent.com/542863/42587685-57d3d40a-84f0-11e8-8853-14565e3cea73.png)

They were frustrated because they knew they had tokens, and this screen:

- [ ] Should show the relevant token's balance for selected accounts.
- [x] The "insufficient funds" warning should distinguish between "insufficient ether" and "insufficient tokens".

**Comment by cjeria** [comment]
Here's a suggested solution. How about we add an extra dropdown for accounts that hold tokens? 

![send screen](https://user-images.githubusercontent.com/597770/42833317-9e173bb6-89a8-11e8-9cd5-a724c523950b.png)

**Comment by cjeria** [comment]
Here's the flow
![image](https://user-images.githubusercontent.com/597770/42835574-f1ff0484-89ad-11e8-8798-40e91e2f6445.png)
![image](https://user-images.githubusercontent.com/597770/42835512-d8ce8d86-89ad-11e8-8a5a-e336b816f365.png)
![image](https://user-images.githubusercontent.com/597770/42835521-dcca90e2-89ad-11e8-8e95-50cd7f243162.png)

**Comment by bdresser** [comment]
Looks good @cjeria! Makes sense to show the new row only if the account has tokens. In general I think this will solve a lot of headaches.
- Will users miss the account switcher in the top-right? I often click "Send," then switch to my relevant account. Could perhaps reduce some padding to help it all fit? Maybe worth some informal interviews. 
- If I am sending ETH from an account with tokens, I might feel weird about the blank field. Why not re-label the field something generic (like "Send" or "Currency") and include ETH as the default option?

**Comment by cjeria** [comment]
@danjm the first option in the dropdown should be ETH. If the user starts the send flow from a token view, that token should be populated in the token field.

**Comment by bdresser** [comment]
@cjeria @danjm my only open question is what the label for the form field should be. `token` isn't really accurate since we're including ETH. `currency` ? `asset` ?

I know kyo is busy on other things but I'm happy to get a bounty up if it makes sense.

**Comment by cjeria** [comment]
@bdresser maybe coins makes more sense for this category. Coinbase uses this term and categorizes eth under "coins".

**Comment by bdresser** [comment]
Per convo with @cjeria, let's start with `asset` as the label.

Flagging for @omnat - specifically, is anyone confused by showing the asset amount alongside it's ticker symbol in the dropdown? We want to show how much they have, but don't want to make it sound like they're automatically sending the max.

Will move forward with development, can make these tweaks easily once it's in production.

**Comment by omnat** [comment]
No one has mentioned it yet in the tests. Could prompt it more in the next tests to see if this is confusing. Will comment if tweaks needed.

**Comment by cjeria** [comment]
This was insight was uncovered during our first mobile prototype user testing sessions (before @omnat started). I had used the same send screen as in extension and made the whole screen interactive. 

We'll want to take a closer look at the send screen (with the new token selection option) along with anything else that users might find confusing in future testing sessions.

**Comment by bschorchit** [comment]
closed by https://github.com/MetaMask/metamask-extension/pull/6445
