### ISSUE TITLE
Remove Prices from UI for Testnets

### ISSUE THREAD

**Issue by fubuloubu** [MetaMask/metamask-extension#4775]
This isn't really useful information on testnets, and it would create an additional UX feedback if the monetary value only appeared on networks where the tokens had value.

A naive suggestion would just be to hide it using the network selector. Something better would be to change the positions of the amount of ETH you have to fill in the negative space left by removing the price.

**Comment by wbt** [comment]
Allowing someone to specify a different lookup / fiat conversion service per network would be a good solution here, including an option to leave the field blank, in which case no conversion is shown.

**Comment by bdresser** [comment]
Agreed @fubuloubu, and we've received some feedback that it's actually confusing to include the conversion on testnets.

Also agree it'd be nice to allow a conversion on custom networks if the user wants @wbt.

* Hide conversion by default for all testnets
* Add a toggle to settings for "show conversion on test networks" (defaulted to "off")
* Update the Custom RPC form in settings to include a conversion drop-down, defaulted to "None." (See mock-up below)
* We really need to clean up the settings menu :) https://github.com/MetaMask/metamask-extension/issues/5790

![custom-rpc-conversion](https://user-images.githubusercontent.com/1016190/52074462-c5e79780-253e-11e9-80e6-4e662b35d64d.png)

cc @omnat @cjeria

**Comment by fubuloubu** [comment]
Nice! I actually could see the price thing being opt-out instead of opt-in. I definitely see the argument for new users to impress on them the costs of using applications as UX feedback preparing them for mainnet, I just want to be able to shut it off as a power user.

**Comment by bdresser** [comment]
We've heard feedback from novice users that it can make using testnets feel scary. @omnat will probably do a little more research before we make a change here.
