### ISSUE TITLE
Infinite spinner on "Back" from Confirm Contract page

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#4778]
When I press back on the Confirm Contract I get an infinite spinner. 
I guess the expected would be that back would take me into my account overview and from there allow me to re-enter contract deployment in the pending transactions list..
When I press Cancel the Contract Deployment is Rejected (which is expected)

![back_confirm_contract](https://user-images.githubusercontent.com/3885055/42604376-4acae550-8527-11e8-971a-a06c912013ef.png)

**Comment by Maayu2415** [comment]
Help me! I was not found google metamask ethereum in one page.

**Comment by Maayu2415** [comment]
Thank you. Please tell me about step to do it.
Now my computer is not confirm to accept matamask
How to do?Can not install seed phrase and privait key

**Comment by Maayu2415** [comment]
I am working wrong step?

**Comment by Maayu2415** [comment]
You are have knowledge." TELL ME PLEASE" I am so many  problems. I am very serious. Because  I am unknowledge about working. Bus it is interresting.

**Comment by Maayu2415** [comment]
If you know can to tell step slowly by slowly .

**Comment by Maayu2415** [comment]
It about 2 week that I can' crate my account wallet address.Howt  to I do!

**Comment by bdresser** [comment]
@Maayu2415 please email support@metamask.io and they'll help answer your questions!

**Comment by bdresser** [comment]
this is fixed on develop by hiding the `Edit` button.
