### ISSUE TITLE
Add option to change password without having to restore from seed

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#4781]
This was supposed to go to #2168, but that was closed due to off-topic posts, so I'm continuing here.

Essentially, there is no "change password" function, you need to restore from seed to define a new password.

This is bad because:
* regular user who can't/doesn't read Github issues won't know how to do this;
* discouraging the regular user is even worse because if they realize that they used a weak password, or figure out that their password is compromised, they will do nothing with a greater probability;
* restoring from seed deletes all your loose accounts and imported tokens (the work put into that... gasp!);
* even barring the above, it's just extra fuss.

I advocate it would be much better to have a "change password" option. It could be placed in the "..." menu next to the account's name, and tied to first entering the present password.

**Comment by danfinlay** [comment]
This is more important in Brave than ever, because uninstalling/reinstalling the extension isn't an option in Brave, so "Create new vault" probably _needs_ to be an option.

Creating a new vault should not destroy old vault data, so that a person using your computer neither can control your locked MetaMask, nor can wipe your vault without your consent.

**Comment by bdresser** [comment]
relates to #4828

**Comment by SPQRBob** [comment]
Also, people reading this after searching on how to change their MetaMask password need to understand the full process **as it stands now:** 
1. Log out of your current MetaMask session.  
    a. This can be done by clicking on your wallet image in the top right corner of the MetaMask drop 
        down in Chrome.
    b. Click on the MetaMask icon in Chrome again, which will bring you to a `Welcome Back!` screen 
        where you can either: 
        1. log-in with your existing password, or 
        2. select the `Import using account seed phrase` option, which is the option you want to change 
            your password.
        3. This will bring you to the full-screen view, where you can input your seed phrase and provide a 
            new password, which you will have to type twice.

**Comment by leejaycantA** [comment]
1.  Im told  'restoring from seed deletes all your loose accounts and imported tokens (the work put into that... gasp!);'
all voided. Lost $$ .  leafct

1a.  how  get new  seed +   pswrd,  by- 

 1c.   How to get mnemonic used by your metamask wallet, you could directly import this mnemonic on your satochip. So all coins go from  metamask wallet   on   to  your satochip

2.  Then metamask wallet  be empty, then delete  metamask wallet,  then install new  metamask wallet,   and with New paswrd.

3.  Satochip is not integrated with Metamask. When it will be, there is no fee for using Satochip with Metamask. 

4.  Ledger    is  integrated with Metamask.  Not memo.cash., will it soon.

Can I  move coins  from    Metamask  to  Ledger  free of gas fees  + etc...

5.  Does  Leger  support BTC, BCH, LTC, ETH, all ERC20 and SLP tokens. Also note that you can use the same card for all your BCH  SLP   supported coins.

6.    Can I use sato  chip inconjunction my atomic wallet, meta mask, and other wallets such as electron cash. 

Currently, integration is only available for Electrum (BTC), Electron Cash (BCH), Electron Cash SLP edition (SLP), Electrum Litecoin (LTC) and MyCrypto (ETH & ERC20).

7.  My AIM is  get  'hardware  chip-walet'    full  inconjunction my atomic wallet, meta mask,  other wallets such as electron cash.  memo.cash. , for All coins  + SLP

**Comment by Longame208** [comment]
> This is more important in Brave than ever, because uninstalling/reinstalling the extension isn't an option in Brave, so "Create new vault" probably _needs_ to be an option.
> 
> Creating a new vault should not destroy old vault data, so that a person using your computer neither can control your locked MetaMask, nor can wipe your vault without your consent.

Is it then possible to restore loose accounts from the vault, if you have not stored the private key or JSON for the particular loose account? I have restored meta mask and similar story exitsing accounts are showing but not the loose account/s which had most my tokens on. I was using chrome

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/7661

**Comment by SPQRBob** [comment]
> Is it then possible to restore loose accounts from the vault, if you have not stored the private key or JSON for the particular loose account? I have restored meta mask and similar story existing accounts are showing but not the loose account/s which had most my tokens on. I was using chrome

@Longame208 - Oh, noes! 🥺
