### ISSUE TITLE
Blank Popup on Brave

### ISSUE THREAD

**Issue by Strernd** [MetaMask/metamask-extension#4782]
**Expected Behavior**
The MetaMask extension popup opens as usually
 **Actual Behavior**
The popup is empty. [Screenshot Brave](https://imgur.com/a/KdACsCW)
I am experiencing this behavior since half an hour. Reinstall and restarts haven't solved the problem.
**Browser Used**
Brave 0.23.31
and Chrome 67.0.3396.99
**Operating System Used**
Mac 10.13.4

**Comment by rdymac** [comment]
Hello @Strernd , on my I've just fixed it by going to Mac tools bar > Brave > Quit Brave (or CMD+Q).

I had to do it twice for the 4.8.0 version that have just been added to Brave to work correctly and load the UI, both in the extension icon and in tab: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html

**Comment by bdresser** [comment]
@seb0zz as @rdymac mentioned, try closing brave and re-opening, maybe a few times. Does that help?

**Comment by seb0zz** [comment]
Tried a few times and it didn't work. Now I just came back from dinner and it worked ¯\_(ツ)_/¯

**Comment by bdresser** [comment]
Ok thanks for the report. Glad it's working.

We'll leave this open for a little bit to see if others experience the same.

**Comment by Strernd** [comment]
Issue is still open for me

**Comment by tmashuang** [comment]
Close this issue in favor of #4894 which seems to be more active, if anyone else finds themselves here feel free to contact https://support.metamask.io with some additional information to help solve the issue.
