### ISSUE TITLE
Warn user when connecting to misconfigured custom network

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4788]
If
- a user gets a transaction error in response to `sendRawTransaction` with `Invalid sender` in the message body
- They are on a custom network

Then
- They probably have not set their `--networkId` and `--chainId` values to the same number, a requirement for our current EIP 155 compliance.

We could easily warn users in this situation of the nature of that error, and alleviate one type of support question.

**Comment by Gudahtt** [comment]
We now require `chainId` to be specified in our custom network form, and we also validate that it matches the response for `eth_chainId`, so I don't think this situation is possible to get into anymore. I'll close this for now, as I don't think it applies anymore.
