### ISSUE TITLE
New Gas Controls

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4789]
It's currently difficult to make an informed decision on what gas to set your transactions to. So we've designed better gas controls that can be used in two areas of the app. 

1 - Speeding up a "slow" transaction
2 - Sending ETH

## Speed up a slow transaction

![image](https://user-images.githubusercontent.com/597770/42657507-43199e4a-85d7-11e8-9a31-4ccfee47082d.png)

![image](https://user-images.githubusercontent.com/597770/42657528-5047a9d6-85d7-11e8-9cbe-2f2b4c9db2bf.png)

## Send ETH

![image](https://user-images.githubusercontent.com/597770/42657629-a79146fc-85d7-11e8-96e1-0bb56ce73647.png)

Related design issue:
https://github.com/MetaMask/Design/issues/25

**Comment by brunobar79** [comment]
@cjeria  I just wanted to say that I love this.

**Comment by bdresser** [comment]
I second @brunobar79 😸 

- might make sense to split this in two - first, the new "basic" controls, then add "advanced" afterwards? @MetaMask/kyokan what do y'all think? 
- moving to "transaction fee" from "gas fee" is bold but I think makes a lot of sense 
- in the "Send ETH" flow, do you think we need ETH values for gas as well as fiat? right now in prod we have both & ETH is primary
- how do the advanced controls look in the extension view? 

@cjeria

**Comment by snreynolds** [comment]
love this +  some thoughts:
• the transaction fee descriptions range from cheap >> average >> fast but describing a transaction as cheap vs. fast may not be super intuitive to new users. For example, it might be good to have descriptions based on _either_ the speed of the transaction _or_ the cost but not a mix of both... so you could label it cheap >> normal >> expensive  or  slow >> average >> fast or more logically combine both so new users know that a cheap transaction equates to slower confirmation time.

**Comment by cjeria** [comment]
Reworked the speed up components a bit here and made two options. Left option is **Time** focused and right is **Price** focused. Updated the labeling per options as well. @bdresser @snreynolds Thoughts?

<img width="971" alt="image" src="https://user-images.githubusercontent.com/597770/43878416-018af720-9b6d-11e8-9add-3eabca3cceb0.png">

**Comment by bdresser** [comment]
I actually like the initial version with Cheap / Average / Fast. Including the price makes it obvious that speed costs more, and there's something good about any choice.

I do like this visual treatment, sneakily adding in the new typeface 😉 

On the extension-sized Confirm screen, I'm assuming the "Advanced options" opens right to the graph? Could you mock what this would look like? We may have to make some adjustments for size.

**Comment by bdresser** [comment]
If I click "edit" from the Confirm screen, what edit view do I see?

**Comment by kingjacob** [comment]
Since it's  ETH being sent/spent and the USD is just an estimated description, the primary really needs to be Eth (or the token being sent/spent)with any meta descriptions placed below at a smaller size. As is, it looks like you're spending USD to speed up transactions, and the eth amount is just an fyi.

**Comment by bdresser** [comment]
@kingjacob check out https://github.com/MetaMask/metamask-extension/issues/4510 and https://github.com/MetaMask/metamask-extension/issues/4804

**Comment by cjeria** [comment]
Based on our twitter poll , option A is the preferred design with some minor tweaks to be made:
- Change the >>> icons to text  labels "Slow, Average, Fast", which makes sense for sending ETH, but not so much for speeding up a transaction.  
- Increase price font size
- Put ETH above fiat value

https://twitter.com/cjeria/status/1027710558785613824
<img width="668" alt="image" src="https://user-images.githubusercontent.com/597770/44125259-67397af6-9fe6-11e8-8ad0-a85dd076102d.png">

Notable feedback from the community:
"
1) explain why: state that the network is slow which is why you’re asking 
2) speed is the primary concern so lead with that over price 
3) consider first time users - is gas well understood? 
4) avoid explaining the UI - for example you don’t need to talk about options in copy"

"I’m a big fan of option A, mostly because the emphasis is put on time rather than price. I also feel that as a new user it may not be apparent that low means a slow transaction and high means a fast transaction."

"A. but reversed ordering or the “optimal” choice selected. Let the user know what metamask would do cause they trust you."
I'd say A, but two thoughts: 1) the current time format is a bit ambiguous, e.g. unclear if it's 8 hr 25 min or 8 min 25 sec, and 2) the font size of the price seems a little small"

"Like option A, but an “Advanced” option with a slider would be nice :)"

**Comment by cjeria** [comment]
Here's an updated design 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/597770/44126284-3a98baba-9fec-11e8-9ad2-9e1e93404170.png">

Bonus option to make it a bit more obvious that the fastest option costs more.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/597770/44126387-d83b7604-9fec-11e8-910d-b4b2e6fc0448.png">

**Comment by bdresser** [comment]
Good feedback from the crowd, liking the input.

The word "slowest" feels like the odd man out. If we're just talking about the "speed up" component, I would think they should all be some form of fast -- like, "fast / faster / fastest" (which I think you were going for with the arrows.)

Also @alextsg or @danjm how are we going to estimate these? Will we suggest proportionally higher gas, or aim for a set of estimated times?

**Comment by danjm** [comment]
@bdresser Our intention was to follow the recommendation scheme of ethgasstation: https://ethgasstation.info/gasrecs.php

Unless @danfinlay has other thoughts on what sort of gas estimates will allow for the best UX

**Comment by bdresser** [comment]
@danjm what if `Safe low` is less than or equal to what the user paid in the first place? Since this is specifically the "Speed up" component, we should adjust to make sure our lowest suggestion is still an improvement above the user's original gas, and adjust the faster options accordingly.

Will we use the same API for the user's original gas options? (aka https://github.com/MetaMask/Design/issues/37)

**Comment by cjeria** [comment]
Posting updates to the advanced custom gas component here for feedback.

![advanced - customize gas modal dialog](https://user-images.githubusercontent.com/597770/44747023-e491c000-aac0-11e8-95eb-64259d007496.png)
![advanced - speed up](https://user-images.githubusercontent.com/597770/44747024-e491c000-aac0-11e8-9b75-f8cf039184e2.png)

**Comment by danjm** [comment]
@cjeria These look great.

One comment: when opening the modal from the confirm screen, we need to give the user access to both the basic tab and the advanced tab. So, we need to give the user a way to switch between tabs.

**Comment by cjeria** [comment]
@danfinlay @danjm Posting for feedback on the tabbed gas dialog

![customize gas modal dialog](https://user-images.githubusercontent.com/597770/44929153-d0430280-ad0e-11e8-9b0e-643a7723fe51.png)

**Comment by bdresser** [comment]
@alextsg @danjm you guys have everything you need? @cjeria any final thoughts? 

otherwise will mark as done if we think nothing else is going to change~

**Comment by bdresser** [comment]
@cjeria did you guys chat about a place for an error message if the user doesn't have enough ETH to speed up their tx? Found this separate issue https://github.com/MetaMask/metamask-extension/issues/4810 but let's keep the convo here.

**Comment by cjeria** [comment]
Yep! There's an error notification component that's in the confirm screen that we could reuse for this screen

![image](https://user-images.githubusercontent.com/597770/45389694-86d99980-b5d1-11e8-9030-a689ecdc9a84.png)

**Comment by danjm** [comment]
@bdresser We have everything we need. Thanks!

**Comment by danjm** [comment]
And great work @cjeria!
