### ISSUE TITLE
What can you do if the correct amount of tokens are not reflecting in your public key within MetaMask in Chrome?

### ISSUE THREAD

**Issue by jeffs3** [MetaMask/metamask-extension#4790]

**Comment by bdresser** [comment]
@jeffs3 you have to add tokens manually for their balance to appear - check out our [support article](https://consensys.zendesk.com/hc/en-us/articles/360004135092-Managing-ERC20-Tokens) on the topic if you haven't already.

beyond that, I recommend you reach out to support@metamask.io with your question and they'll be able to assist.
