### ISSUE TITLE
Notifications not showing on Firefox Ubuntu

### ISSUE THREAD

**Issue by estebanmino** [MetaMask/metamask-extension#4796]
When a transaction has to be confirmed MetaMask triggers a notification popup, but isn't showing the content.

![image](https://user-images.githubusercontent.com/12115171/42718748-0a7b0156-86da-11e8-88bb-cf193e86137c.png)

After a manual resize of the popup, the content is displayed.

![image](https://user-images.githubusercontent.com/12115171/42718771-5e4715e0-86da-11e8-9f6a-8fcd4dcfb5a7.png)

In Firefox 61.0 snap version and apt version. Ubuntu 18.04 64 bits.

**Comment by bdresser** [comment]
closing for https://github.com/MetaMask/metamask-extension/issues/2746
