### ISSUE TITLE
metamask error

### ISSUE THREAD

**Issue by vijayantjain** [MetaMask/metamask-extension#4798]
Dear admin,
   I tried sending PLR from my metamask wallet to another wallet. After a few minutes, the transaction appears like this.

<img width="1110" alt="screen shot 2018-07-14 at 8 55 35 am" src="https://user-images.githubusercontent.com/9728661/42720582-fd317e0e-8746-11e8-9c0e-af58c4965c7f.png">

when I click on the transaction, etherscan.io gives the following message.
"Sorry, we are unable to locate this Transaction Hash"
please resolv that issue asap.
.
Thanks 
vijayant jain

<!

BEFORE SUBMITTING, please make sure your question hasn't been answered in our support center: https://support.metamask.io
Common questions such as "Where is my ether?" or "Where did my tokens go?" are answered there.

Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
  *  Actual Behavior
  *  Browser Used
  *  Operating System Used

  Screenshots are very helpful and will expedite your issue being resolved!
-->

**Comment by bdresser** [comment]
@vijayantjain looks like you submitted several transactions trying to send your PLR token.

Note that transactions can only process in the sequence you submit them, keeping the transaction nonce in order, so later transactions you submit won't succeed until the first transaction is confirmed.

When you're submitting a transaction, make sure you're sending with a high enough gas price, or the transaction can take a very long time to settle. 

When you see the first "taking to lonng?" message, it's probably a good idea to consider resubmitting that transaction with a higher gas price. 

It usually takes a couple seconds, sometimes a couple minutes for the transaction to appear on Etherscan. 

For more user questions like this, please reach out to support@metamask.io and they'll be able to help.
