### ISSUE TITLE
Metamask breaks website, stops ani.gamer.com.tw video player.

### ISSUE THREAD

**Issue by axzxc1236** [MetaMask/metamask-extension#4799]
preface: ani.gamer.com.tw is a online anime video platform, and it's regional service (Taiwan only), so you probably need some help to debug this issue (and I can if you need more information).
This website doesn't have anything to do with cryptocurrencies, so I have no clue what happened and why.

What happened:
If I enable Metamask, video players breaks so it's not possible to play anime.

Expected Behavior:
I can play anime without issue.

Actual Behavior:
Metamask did something so no video at all.

Browser used:
Google Chrome 67.0.3396.99

Operating System Used: Windows 10 1803 (17134.165)

[Picture1 (with Metamask)](https://i.imgur.com/oiy3bO1.png)
[Picture2 (without Metamask)](https://i.imgur.com/MF9VZoS.png)

**Comment by bdresser** [comment]
@axzxc1236 any errors in the console?

**Comment by axzxc1236** [comment]
@bdresser 
Yes, in the screenshot.
