### ISSUE TITLE
Move to three (0.79.0) vs three.js in package.json

### ISSUE THREAD

**Issue by simondlr** [MetaMask/metamask-extension#480]
For some reason, using npm install, three.js kept hanging. Could install modules. Kept failing here Seeing it in npm, it moved to just "three". I updated to 0.79.0 and it worked.

**Comment by simondlr** [comment]
Spoke slightly too soon. The issue was in metamask-logo, calling what seems to be a commit not around anymore? Anyway, moving all three.js to three ~0.79.0 fixed the installation.

**Comment by flyswatter** [comment]
This seems to be working for all of us, so I'm going to consider this an npm fluke for now?

**Comment by simondlr** [comment]
Interesting. Might be npm3 or something? I'll re-open if I reinstall from scratch and it fails.

Either way, it seems three.js has moved to new package name (https://www.npmjs.com/package/three.js). So might be useful still to move over to that. :)

**Comment by flyswatter** [comment]
Yeah, we're interested in moving to it partly because they now have a browserified build where you can import modules as needed, making for a leaner project.  We definitely will be at some point, just probably after devcon.

**Comment by tmashuang** [comment]
Closing old issue since I could find no indication of `three.js` in the project anymore.
