### ISSUE TITLE
Metamask Overrides Nonce

### ISSUE THREAD

**Issue by geniusboy91** [MetaMask/metamask-extension#4801]
In this example, I have a pending transaction with a nonce of 7. On mycrypto.com, I create a new transaction and set the nonce as 7 with a higher gas price, as shown in picture one. This transaction is completely unrelated to the current pending transaction at nonce 7. I am doing this intentionally because I no longer need the current transaction to go through. However, when mycrypto pushes the new transaction to metamask and I submit it, the transaction has now been changed to having a nonce of 8. Now, both transactions will be processed by the network instead of the second transaction taking miner preference (due to higher gas price) over the original.

While the side by side screenshot shows as confirmed now, the first transaction was pending at the time of submitting the second and for quite a while after. Also, the rejected transaction in the picture is not relevant to this discussion. 
![cap1](https://user-images.githubusercontent.com/41244412/42729532-2fbf9786-87a9-11e8-831e-cbc9521e303a.PNG)
![cap2](https://user-images.githubusercontent.com/41244412/42729533-2fcdeba6-87a9-11e8-91b8-7866aa101f92.PNG)
![cap3](https://user-images.githubusercontent.com/41244412/42729534-2fd9d060-87a9-11e8-9fc7-c76f48d3334e.PNG)

**Comment by bdresser** [comment]
@geniusboy91 we plan on adding a "cancel" button for specific transactions, as well as a "cancel all" to clear out all pending tx.

Check out #3312 & #4022, as well as https://github.com/MetaMask/Design/issues/25

Closing for now, but feel free to re-open if you feel like the above don't cover what you're looking for.
