### ISSUE TITLE
Allow users to specify the symbol other than ETH and hide currency conversion

### ISSUE THREAD

**Issue by radamosch** [MetaMask/metamask-extension#4804]
When connected to private or other networks than ETH, it's not currently possible to set the symbol or avoid default denomination in ETH for currency conversion.

While you guys contemplate the ecumenical & security & political matters around network selection in other issues this simple and flexible proposal will mean MM is usable on other networks with a little edit by users.

1. Allow user to self specify the symbol for the currency from "ETH" --> whatever
2. Allow user to choose "none" for currency conversion and hide that if it is not set.

This will avoid confusion and wrong denominations in MM when users are connected to networks that are transferring value in other symbols.

![image](https://user-images.githubusercontent.com/35626984/42733865-7db181ce-8831-11e8-87d2-ef3a281f9893.png)

![image](https://user-images.githubusercontent.com/35626984/42733867-884a983c-8831-11e8-93b9-f5fdd27c7289.png)

(If you were feeling really helpful, an autodetect of the symbol / currency would be great)

**Comment by SoberKush** [comment]
Please take this guy in consideration. This is useful for a huge portion of MetaMask users and I wonder why it hasn't been implemented yet! 

Thanks for posting this @radamosch

**Comment by davidzki** [comment]
^^^ This!

**Comment by bdresser** [comment]
> Allow user to choose "none" for currency conversion and hide that if it is not set.

Makes sense - this will also require logic that swaps ETH to the primary currency on the confirm screens (i.e. swap the `1` and the `478.30` below)

We should probably allow users to swap ETH to the primary currency without having to hide the conversion (as described in #4510) and add a toggle in the settings. 

<img width="351" alt="screen shot 2018-07-16 at 4 01 32 pm" src="https://user-images.githubusercontent.com/1016190/42780565-8caca902-8911-11e8-9f8b-1b87d1a9de5c.png">

thoughts @danfinlay @cjeria @alextsg? bounty worthy?

**Comment by bdresser** [comment]
> Allow user to self specify the symbol for the currency from "ETH" --> whatever

This is in production!

> Allow user to choose "none" for currency conversion and hide that if it is not set.

Tracking this in https://github.com/MetaMask/metamask-extension/issues/5327 and https://github.com/MetaMask/metamask-extension/issues/4775.
