### ISSUE TITLE
Metamask very slow to respond

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#4805]
Expected Behaviour
* Metamask pop up immediately when I call a web3 interaction
* Confirmation button responds immediately (at the very least with a loading indicator)

Actual Behaviour
* Metamask pop up 6 seconds after I call a web3 interaction.
* Confirmation button doesnt respond (even 60 seconds later).

Video: http://bits.owocki.com/3y2d0X0G173W/Screen%20Recording%202018-07-15%20at%2007.27%20AM.gif

**Comment by owocki** [comment]
edit: for the confrimation button interaction, i was using 0xddf369c3bf18b1b12ea295d597b943b955ef4671, which didnt have enough ETH to pay the gas fee.  metamask should have told me this instead of just not-responding

**Comment by whymarrh** [comment]
Could be related to #4195

**Comment by owocki** [comment]
What RPC node are you using on MEW @bdresser ?

I've noticed it intermittently on Gitcoin; but GC is really the only dapp i use day over day so I can't say if it happens on other sites or not.

I'm assuming its either Metamask or infura related, because I've traced through the code and the delay happens after we enter the `web3.eth.sendTransaction` method

**Comment by owocki** [comment]
entered this ticket on infura https://github.com/INFURA/infura/issues/128

**Comment by OneUnderBridge** [comment]
How to speed up MetaMask?....I keep missing my numbers because it's too slow to pop-up and by the time it displays, my choice of numbers has been altered by the draw frequency being displayed (Dice2Win).
