### ISSUE TITLE
metamask chrome extension crashes when trying to open

### ISSUE THREAD

**Issue by craigvh** [MetaMask/metamask-extension#4806]

**Comment by craigvh** [comment]
Pops up with a blank window and then after about 10 seconds closes and shows: Metamask has crashed. Click this baloon to reload the extension.

**Comment by bdresser** [comment]
@craigvh what OS and version of Chrome are you running?

**Comment by craigvh** [comment]
Hi,
I solved this issue by uninstalling and then adding the extension again.
Fortunately I had my Eth key to reinstall myetherwallet address.
