### ISSUE TITLE
Error Messages within Speed Up Component

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4810]
If a user wants to speed up a slow transaction but doesn't have enough gas to pay for a higher gas fee, we need to show error messages. The place that makes the most sense is within the Speed Up transaction panel view.

![image](https://user-images.githubusercontent.com/597770/42780864-52208f64-88f9-11e8-88f6-7f61ebe40897.png)

**Comment by bdresser** [comment]
relates to #4789

**Comment by bdresser** [comment]
closing in favor of #4789
