### ISSUE TITLE
Old UI component to suggest Beta UI

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#4811]
To finish up #3384, we need a UI component that asks users to upgrade to the new UI. Maybe a persistent banner or something. 

@cjeria @whymarrh

**Comment by cjeria** [comment]
The message should probably say that support for the old UI has been discontinued. No action is required, but that they should be aware that If they don't switch to the New UI, we will automatically be switching everyone over on XX date. 

Maybe to encourage users to switch, we use both a modal and banner. The modal will provide us with plenty of room to make the announcement and a button the "Switch to the New UI" button. If modal is dismissed and the user doesn't switch, we then show a persistent banner with a CTA to switch to the old UI. Would be good to also have a "learn more" and link to an article describing our plans for the switch.

**Comment by cjeria** [comment]
@whymarrh Here are the suggested designs for the announcement in the old to ui.

![image](https://user-images.githubusercontent.com/597770/42973204-2bf27080-8b67-11e8-9971-447efc966507.png)

**Comment by whymarrh** [comment]
@cjeria thanks, this looks great! Where did you imagine the "Read more about our plans" and "learn more" links going?

**Comment by danfinlay** [comment]
What will our "Read more about our plans" link go to?

**Comment by cjeria** [comment]
Let's change that link to say "Learn more" and link to https://medium.com/metamask/metamasks-new-ui-has-begun-to-roll-out-74dba32cc7f7

thoughts? @whymarrh @danfinlay

**Comment by danfinlay** [comment]
Sounds good. Maybe we edit the post to add info about the gas editing + tx parameter viewing.

**Comment by bdresser** [comment]
looks great @cjeria except weird to say "No action is required right now" and then also ask them to click a shiny blue button :) so maybe we remove that little line?

**Comment by cjeria** [comment]
good call @danfinlay 

@bdresser @whymarrh See updated copy.

![image](https://user-images.githubusercontent.com/597770/42980717-79f12b52-8b8d-11e8-8244-b2bd80cfdc31.png)

**Comment by bdresser** [comment]
looks great, thanks Christian.

@whymarrh @kumavis what do you think about using Sentry to understand how many clicks we get? Okay by me if we can't de-dupe, would just love any signal on whether people are moving over.

**Comment by bdresser** [comment]
when will this display for brand-new users? right on startup?

**Comment by Maayu2415** [comment]
ทำไงต่อล่ะ

**Comment by whymarrh** [comment]
@bdresser right on startup

**Comment by bdresser** [comment]
gotcha @whymarrh. can we link them to new UI's full-screen onboarding, rather than the extension? this might be what you're already planning, just want to double check.

**Comment by whymarrh** [comment]
We can, that's a good idea—you're thinking that the switch will turn on the new UI and then open up a new tab?

**Comment by bdresser** [comment]
Yeah. Full screen in the new UI is a little better formatted, fewer page breaks etc (vs. extension view). 

i think that's how it used to work with the small "Try the Beta UI" link at the bottom of Old UI onboarding. But just found https://github.com/MetaMask/metamask-extension/issues/4896, not super urgent, and even less urgent as we push more people off the old.
