### ISSUE TITLE
MetaMask does not show signature request if open when 'eth_signTypedData' request is sent

### ISSUE THREAD

**Issue by alex-ppg** [MetaMask/metamask-extension#4821]
This is quite a crucial issue with user interaction as we cannot reasonably expect a user, after unlocking his account, to close and re-open the MetaMask plugin screen.

- **Expected Behavior**: Whilst the MetaMask plugin screen is open, either the page itself transitions to the signature request or the signature request pop-up shows.
- **Actual Behavior**: If MetaMask is open when the request is sent, the request does not show unless I close and re-open the MetaMask screen.
- **Browser Used**: Google Chrome although I believe this is irrelevant.
- **Operating System Used**: Windows 10 but likewise irrelevant.

Code Example (Ensure your account is locked):

```js
const msgParams = [
    {
        type: 'string',
        name: 'Authorization Request',
        value: 'test'
    }
];
if (typeof window.web3 !== 'undefined' && typeof window.web3.currentProvider !== 'undefined') {
    let localWeb3 = new Web3(window.web3.currentProvider);
    window.web3.eth.getAccounts((err, accounts) => {
        if (!accounts[0]) {
            watchAccountUnlock();
        } else {
            localWeb3.eth.defaultAccount = accounts[0];
            requestSignature();
        }
    });
}

function watchAccountUnlock() {
    const toClear = setInterval(() => {
       window.web3.eth.getAccounts((err, accounts) => {
            if (accounts[0] !== localWeb3.eth.defaultAccount) {
                localWeb3.eth.defaultAccount = accounts[0];
                requestSignature();
                clearInterval(toClear);
            }
        });
    },500);
}

function requestSignature() {
    localWeb3.currentProvider.sendAsync({
      method: 'eth_signTypedData',
      params: [msgParams, localWeb3.eth.defaultAccount],
      from: localWeb3.eth.defaultAccount,
    }, (err, result) => {
      if (err) return console.error(err)
      if (result.error) {
        // User denied signature
      }
      const signature = result.result;
      alert(signature);
    });
}
```

**Comment by bdresser** [comment]
@alex-ppg a simple workaround might be to have the user click a UI element to prompt the signing request, rather than trying to fire it automatically on login. 

curious what your usecase is – if you're trying to create a sort of log-in behavior, make sure you've checked out this [web3 opt-in feature](https://github.com/MetaMask/metamask-extension/pull/4703) that we'll be rolling out shortly.

@danfinlay @bitpshr any other thoughts?

**Comment by alex-ppg** [comment]
@bdresser While what I am trying to do is create a sort of log-in behavior, it doesn't exactly work in the same way most DApps do.

We are creating a multi-currency front-end wallet that derives the various keys from a seed and in order to support MetaMask, we want the user to sign a randomly generated (once) and server-side stored string, using the resulting signature as the seed for the various currencies. 

We are going to allow the user to use their Ethereum based wallet directly via MetaMask obviously but we need the signature for the rest of the currencies.

**Comment by bdresser** [comment]
@bitpshr might have to do with the logic around the popup ID https://github.com/MetaMask/metamask-extension/pull/4592

**Comment by joenhon** [comment]
Excuse me, how do you call MetaMask, is it convenient to call the code to give me a copy?

**Comment by alex-ppg** [comment]
Hey @joenhon, sorry for the late response I've been abroad. I recreated the problem in the following Gist: https://gist.github.com/alex-ppg/86ddf1bd997e016aef95f46b8497d7b7

I am developing the application using Angular but the problem seems to be related to the MetaMask plugin API rather than any of the technology stacks. 

I have also tried delaying the signature request for a while but the issue is that the MetaMask pop-up is kept open after unlocking. If I close the MetaMask plugin page **before** the signature request occurs, the pop-up will show just fine.

**Comment by Gudahtt** [comment]
Thanks for the report @alex-ppg ! Are you still experiencing this problem with the latest version of MetaMask? I suspect that this has been fixed.

**Comment by tmashuang** [comment]
Closing this, the issue was the result of the first iteration of the login-per-site and the notification windows. This has since been changed and reworked as well as fix.

**Comment by JithinKS97** [comment]
@alex-ppg Could you please let me know how you resolved the issue? I ran into the exact use case and I'm observing the same behaviour. If the wallet is already open, signature screen is not shown unless we explicitly close and open the metamask widget.

**Comment by Rizwankmc** [comment]
I have encounter the issue when the metamask is connected with the dapp and it is locked, and user tries to sign the signature with the signTypedData it does not show any popup and any error but if its disconnected and locked it does how the popup to unlock it first and then its works.

and if wallet is unlocked, the signTypedData request also go through. only if the wallet is locked and connected its not showing popup to unlocked and sign the message
