### ISSUE TITLE
Transactions: Only show "Retry" button on the earliest pending tx

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4826]
To prevent users from increasing gas prices on transactions that aren't clogging their queue.

**Comment by bdresser** [comment]
relates to https://github.com/MetaMask/Design/issues/25

**Comment by danfinlay** [comment]
Should make the change on both old AND new UI.

**Comment by danjm** [comment]
@danfinlay This will show the retry option on the transaction that is being labelled as "Pending" in the latest designs, correct? (MetaMask/Design#25)

Currently, the transaction history list is ordered from latest at top to earliest at bottom. So implementing this change now will result in the retry button appearing somewhere below the top item in the list. This will then switch once we implement the new designs.

Two questions:
(1) I want to confirm that the above described changes are indeed what we intend to do presently?
(2) Should the new transaction histroy designed in MetaMask/Design#25 also follow this change?

**Comment by danjm** [comment]
Actually, @danfinlay, I thought about it some more. The answer to question (1) above is definitely yes. And I will move question (2) to the design doc/issue.

**Comment by danfinlay** [comment]
Fixed by #4885

**Comment by Maayu2415** [comment]
HOW TO LOGIN? Then how to install ip.?


ในวันที่ ส. 28 ก.ค. 2018 17:27 maayu2415 <mjaniam2415@gmail.com> เขียนว่า:

**Comment by Maayu2415** [comment]
Domain nane = name email ?

ในวันที่ ส. 28 ก.ค. 2018 17:27 maayu2415 <mjaniam2415@gmail.com> เขียนว่า:
