### ISSUE TITLE
Cannot change gas price on deploying contracts

### ISSUE THREAD

**Issue by aidatorajiro** [MetaMask/metamask-extension#4831]
I tried to increase gas price of a contract deployment transaction, but I couldn't. There was no sliders or anything to change gas price.

First, I pressed "Increase gas price on your transaction" button.
![scrchot1](https://user-images.githubusercontent.com/7290197/42922665-97a9b8e8-8b5c-11e8-9885-9797388da559.png)

But no sliders shows up.
![scrchot2](https://user-images.githubusercontent.com/7290197/42922668-9a1919ca-8b5c-11e8-90d4-49924548b540.png)

For normal ETH transfer, I could change the gas price.

Browser Used: Chrome 67
Operating System: MacOS Sierra
Solidity IDE: Remix

**Comment by bdresser** [comment]
@aidatorajiro this is due to the same issue mentioned in #4635, fixed by #4691 and out shortly in our next release
