### ISSUE TITLE
Gas Estimation failed

### ISSUE THREAD

**Issue by karthikcyadav98** [MetaMask/metamask-extension#4832]
i developed a smart contract and its working fine in javascript VM and in web3 provider, but while i deployed the same contract on ropsten i got an error saying "gas estimanation failed" and the transaction reverted

**Comment by danfinlay** [comment]
Could you send your [state logs](https://consensys.zendesk.com/hc/en-us/articles/360004133392-How-To-Download-State-Logs-Old-UI-) to support@metamask.io so we can inspect what may have gone wrong? It's possible this was an error at the RPC layer, but we'd have to see the logs to be sure.

**Comment by bdresser** [comment]
@karthikcyadav98 were you able to send your state logs? don't see any open tickets that reference this issue. (cc @alacrity26)

**Comment by Aiden-Wu** [comment]
I have also had such a problem. What is this caused?
