### ISSUE TITLE
Write unit tests for the confirm-detail-row.component.js

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4835]
`metamask-extension/ui/app/components/confirm-page-container/confirm-detail-row/confirm-detail-row.component.js` needs unit tests.

Use `metamask-extension/ui/app/components/send/send-content/send-row-wrapper/send-row-wrapper.component.js` and `metamask-extension/ui/app/components/send/send-content/send-row-wrapper/tests/send-row-wrapper-component.test.js` as an example to follow.

Tests to include:
- check that the outer div renders (get the div by its classname)
- separate unit tests to check that each of `label`, `headerText`, `fiatText` and `ethText` rendered correctly and within the expected divs
- check that the passed `fiatTextColor` gets set on the expected div
- check that the `className` of the div that includes the `confirm-detail-row__header-text` class is as expected
- check that `onHeaderClick()` gets called when `headerText` div gets clicked

documentation that might be helpful:
- http://airbnb.io/enzyme/
- https://github.com/JedWatson/classnames

**Comment by snreynolds** [comment]
I think the file directory is actually `metamask-extension/ui/app/components/confirm-page-container/confirm-detail-row/confirm-detail-row.component.js`
