### ISSUE TITLE
MetaMask crashed, will not respond!

### ISSUE THREAD

**Issue by Professor-Curtis** [MetaMask/metamask-extension#4846]

**Comment by Professor-Curtis** [comment]
Nothing works.  Cannot trade on ForkDelta, have not been able to trade for over 1 week.  I have gone to the site to reinstall. pressed enable, nothing happens.

**Comment by bdresser** [comment]
@Professor-Curtis what browser and OS are you using?

**Comment by bdresser** [comment]
@Professor-Curtis closing this for now - if you're still having trouble or can share more details about what's happening, please feel free to re-open.

**Comment by Professor-Curtis** [comment]
Here's the problem.  Metamask stopped working on my computer.  I removed
and then re-installed Metamask on to my computer.  I have no idea as to how
to import my old accounts into my new account.  I have been dealing with
this problem for about 20 days now.  The last communication I received from
Metamask support stated that I needed to use my private keys to import my
older accounts.  I'm an investor, not a computer scientist.  I have no idea
as to how to use my private keys.  Why would any company set us a system
like Metamask and place it between an investor and his money, without
instructions? I need a link or other instructions.  Thank you.
Curtis.

**Comment by bdresser** [comment]
@Professor-Curtis this does sound like a support issue – we try to keep this forum to feature requests or bug reports that have to do with our code.

As I'm sure support has mentioned, you need access to your seed phrase to restore your account. Read more [here](https://consensys.zendesk.com/hc/en-us/articles/360004179591-Restore-from-seed-phrase-New-UI-).

If you didn't write down your seed phrase, it may be impossible to recover your funds. If it is possible, support will walk you through how.

**Comment by bdresser** [comment]
That's great news :) 

Try this article: https://consensys.zendesk.com/hc/en-us/articles/360004179591-Restore-from-seed-phrase-New-UI-

If the screens look a little different, that's totally okay, you might be on an older version.  Look for the link at the bottom of the extension that says "Restore from seed phrase" and follow the steps.!

**Comment by Professor-Curtis** [comment]
This looks good.  I will try it out in the morning.  Bobby, your response
is more like what I would have expected out of Metamask.  For almost 20
days all I got was delays and half-answers.  I don't understand it!  Why
did Metamask Support make a simple solution so hard?!

Thank you,
Curtis
