### ISSUE TITLE
check failed authentication on sign ddex

### ISSUE THREAD

**Issue by black13trader** [MetaMask/metamask-extension#4849]
i have problem on ddex.io After sign i see red color message: Authentication check failed! please make sure you have authenticated already. 
Brouser Chrome

**Comment by bdresser** [comment]
@black13trader could you share a screenshot? I don't think that error message originates from MetaMask, it could be an issue with ddex

**Comment by bdresser** [comment]
@black13trader closing this for now, if you're still having trouble or can share more details about what's happening, please feel free to reopen
