### ISSUE TITLE
When I link to my private chain, my account balance is inexplicably much less, and there are no hints and no transaction records on the metamask. This is not my operation, but I can actually find the deal on the private chain.

### ISSUE THREAD

**Issue by heaven668** [MetaMask/metamask-extension#4863]

**Comment by rookieofC** [comment]
I mean, when I log in to the metamask, connect to my private chain and start mining, the eth on my account is turned away, and there is no prompt for me to sign the transaction on the metamask. “ no transaction records” means no record of successful or failed transactions

**Comment by rookieofC** [comment]
I mean, when I log in to the metamask, connect to my private chain and start mining, the eth on my account is turned away, and there is no prompt for me to sign the transaction on the metamask. “ no transaction records” means no record of successful or failed transactions on metamask。

**Comment by Maayu2415** [comment]
Thank you for your service.



ในวันที่ พฤ. 26 ก.ค. 2018 18:03 rookieofC <notifications@github.com>
เขียนว่า:

**Comment by bdresser** [comment]
The extension is only going to show transactions from your most recent install or account reset, it won't show historical transactions. 

Have you imported an account that has funds on your private chain?

**Comment by rookieofC** [comment]
yes，I imported the account I set up on the private chain. but the eth in my private chain was transferred after I logged in to the metamask. I didn't have such a thing when I didn't log in to the metamask.
I am sorry that I have not been able to respond to you in time, and will not happen again in the future. Thank you for your kind reply.

**Comment by bdresser** [comment]
@rookieofC can I close this issue, or are you still experiencing the issue you described?

**Comment by rookieofC** [comment]
Yes, I still have this problem, but it seems that it is very difficult for anyone to help me solve it.

**Comment by MagRelo** [comment]
Is your private network available to the public internet? This sounds a bit like this issue: https://medium.com/coinmonks/securing-your-ethereum-nodes-from-hackers-8b7d5bac8986

ie, someone else is sending transactions to your geth instance...

**Comment by Gudahtt** [comment]
Thanks for the report! This issue is rather old and never had enough information to reproduce, so I'll close this for now. Please make a new issue with more information if you're still experiencing this issue.
