### ISSUE TITLE
MetaMask removed from google extension store?

### ISSUE THREAD

**Issue by creazy231** [MetaMask/metamask-extension#4874]
Just wonder why I cant access the MetaMask-Extension on google anymore.

https://chrome.google.com/webstore/detail/nkbihfbeogaeaoehlefnkodbefgpgknn

Anyone got some information about that?

**Comment by bdresser** [comment]
The extension has been temporarily removed from the Chrome store for reasons we're not sure of yet. The Chrome team has been banning applications that involve mining, and it's possible MetaMask was improperly classified. 

Existing users and other browsers are unaffected, stay tuned to [our Twitter](https://twitter.com/metamask_io/status/1022125347259576320) for more information

**Comment by creazy231** [comment]
@bdresser thanks for the fast reply. Is there any other way to get the Chrome Extension without compiling the repo on my own?

**Comment by bdresser** [comment]
You could download a build from a closed pull request if you really need to get chrome up and running. You'll be using the develop branch, so we can't promise stability, but you'll also get access to some fun new features 😄 

check out https://github.com/MetaMask/metamask-extension/pull/4865, download the metamaskbot's build for chrome, head to `chrome://extensions`, load the unzipped build with "Load Unpacked." You'll have to restore your accounts using your seed phrase.

**Comment by creazy231** [comment]
Worked as it used to :)
Thanks for the help.

I'll let this issue open until MetaMask is back in chrome store so other users can easily follow the steps above.

**Comment by bdresser** [comment]
actually, a better answer is to download our current production build from the [releases](https://github.com/MetaMask/metamask-extension/releases) page

**Comment by bdresser** [comment]
back up!
