### ISSUE TITLE
Reset Account button

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#4881]
The Reset button right now does these two things in one click:

- Wipes tx history
- Reset network connections

We should break out those functions in two seperate buttons for more granular control when a user only wants to cancel pending/stuck transactions (reset network does this).

**Comment by fullammo** [comment]
Hello! I would like to do my first contribution to open source, and as a i researched what needs to be done here, I think it is pretty isolated and i would like to take it up. Can you guys assign somebody from the team to guide me through this "journey"?
Thanks in advance!
Happy Coding!

**Comment by yozaam** [comment]
Hey Is this [ui/app/components/app/modals/confirm-reset-account/tests/confirm-reset-account.test.js](https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/components/app/modals/confirm-reset-account/tests/confirm-reset-account.test.js)

The correct file to make the changes in?

**Comment by Gudahtt** [comment]
I'm not sure this is still something we want to do. The "Reset Account" button is most often used by people using MetaMask in development, and such users do always want both of these things, so separate buttons wouldn't be an improvement.

The name for this button remains misleading, and I don't think it's especially convenient for anyone, but I think we can track improving this in other related issues (#4254, #5067, #6559, #8081)
