### ISSUE TITLE
MetaMask

### ISSUE THREAD

**Issue by Sammonac** [MetaMask/metamask-extension#4892]
My MetaMask is not connecting. Every time I try to open it there is only white. 
When I try to go to myetherwallet and click connect to metamask it does not do anything.

**Comment by bdresser** [comment]
@Sammonac what browser, browser version, and operating system are you using?

**Comment by bdresser** [comment]
@Sammonac closing this for now, if you are still having trouble or can get us some more info, feel free to re-open!
