### ISSUE TITLE
Migrate to Trezor Connect v5

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-extension#4904]
TREZOR  remade the whole library from scratch

https://github.com/trezor/connect/tree/v5

**Comment by tmashuang** [comment]
Page is 404.

**Comment by Maayu2415** [comment]
Top intelligent.


ในวันที่ ส. 28 ก.ค. 2018 02:04 Bruno Barbieri <notifications@github.com>
เขียนว่า:
