### ISSUE TITLE
New UI does not show transaction data size

### ISSUE THREAD

**Issue by adrianmcli** [MetaMask/metamask-extension#4909]
In the old UI, when you were sending a transaction with something in the data field, you get an indicator showing the size of such data in the MetaMask prompt:

![screen shot 2018-07-28 at 3 33 10 am](https://user-images.githubusercontent.com/943555/43354279-274ba428-9217-11e8-8edb-dfe27b9dc4e9.png)

This is sometimes useful, because it gives the user an indication of why the default gas was set higher than usual, for example. So while the new UI for selecting gas is much nicer, I am still surprised to see that this bit of information has been removed.

**Comment by bdresser** [comment]
good call @adrianmcli, thanks 

heads up @cjeria @alextsg. this could probably get tucked away on the `Data` tab? 

<img width="200" alt="screen shot 2018-07-31 at 11 37 20 am" src="https://user-images.githubusercontent.com/1016190/43479801-276af50c-94b6-11e8-8ca0-cddf2ebc2933.png">

**Comment by adrianmcli** [comment]
Note that sometimes I'm not calling a function. I might just be leaving a message while sending a friend some ETH; Kinda like "This is for last night's dinner". I think the UI is different for simple ETH transfers, but I think it's important to show that there's data included for that case as well.

**Comment by bdresser** [comment]
@adrianmcli definitely - basic transactions with ETH do have a slightly simpler confirm screen. (this screen is from the new confirm screen being released early next week 😄)

Trouble is, when you include hex data on a transaction, the extension looks up the first four bytes to see if they correspond to a known function call. If we find something, the new confirm screen will display the name of that function so the user knows what they're confirming.

If we don't find a function that matches the first four bytes of data, we inform the user that it's an "unknown function." An unintended side-effect of displaying the function name might be the inability to distinguish between simple ETH transactions with hex data, and function calls not present in the registry we use. 

@alextsg @danfinlay does that sound right?

**Comment by alextsg** [comment]
@bdresser Yeah, at least that's how I understand the problem. @danfinlay Any suggestions for a workaround?

**Comment by xifengxx** [comment]
I also think the transaction data(Optional) function is neccesary

**Comment by alextsg** [comment]
Is this still an issue? Users can click the data tab when data exists, and sending ether with optional hex data is now supported.

**Comment by alextsg** [comment]
This has been added.
