### ISSUE TITLE
Can't send my ethereum from metamask to ledger nano S

### ISSUE THREAD

**Issue by drejke** [MetaMask/metamask-extension#4911]
I tried sending 0.5 eth to my nano ledger s and it worked perfect. After this i tried sending the left over eth but I made an mistake and tried sending 0.5 eth to much, so the transaction failed. Then i tried to send 15.2 eth to my nano ledger s but this doesn't work. I tried higher gass prices but it never shows the transaction on etherscan.io.
If someone could help me, that would be very kind

![image](https://user-images.githubusercontent.com/41873412/43368720-16bf4438-9362-11e8-98d8-0495b36ab093.png)
![image](https://user-images.githubusercontent.com/41873412/43368725-25245054-9362-11e8-89f3-5d91a0e2d087.png)

![image](https://user-images.githubusercontent.com/41873412/43368727-3275303e-9362-11e8-8f4c-842569c77ac3.png)

![image](https://user-images.githubusercontent.com/41873412/43368733-44cff462-9362-11e8-8f32-745f7dca8e27.png)

**Comment by Nathapon8899** [comment]
I tried to send 0.5 eth to my nano ledger and it worked perfectly after this I tried to send left over eth but i made a mistake and tried to send 0.5 eth to a lot so the transaction failed then i tried sending 15.2 eth to It's my nano ledger, but it does not work. I try to use higher gas prices. But it never listed about. etherscan.io
If someone helped me, it would be great.

**Comment by bdresser** [comment]
Hey @drejke - transactions have to be confirmed in the same order as the nonce. So if you have transaction `4` pending, transactions `5` or `6` will not be able to confirm until `4` is mined successfully. 

If you have multiple transactions still pending, you should increase the gas on the transaction with the lowest nonce. Only once that transaction is confirmed will the other transactions with higher nonce make it through. 

We have plans to update the "reprice" UI so this is more clear: https://github.com/MetaMask/Design/issues/25

For more questions on specific user issues, please reach out to support@metamask.io
