### ISSUE TITLE
Brave Extension: Unable to conduct 0 Eth transaction on a private POA

### ISSUE THREAD

**Issue by gmjacob** [MetaMask/metamask-extension#4913]
We permit 0 Eth transaction on the POA of our DApp. Hence no Eth or any gas cost is required. On extensions on all browsers except for Brave this works fine. On brave, it does not allow 0 gas/eth transactions.

Link to DApp: https://beta.springrole.com/
PFA a screenshot of the issue:
![zeroethissue](https://user-images.githubusercontent.com/25900986/43395271-18e7eeb8-941b-11e8-8033-08708e540c1d.png)

**Comment by HowardBraham** [comment]
Cannot reproduce in either the old UI or the new UI.  The interface is definitely a little wonky, but these 4 transactions were sent from the Brave browser with 0 gas and 0 ETH:

https://explorer.springrole.com/account/0xb18c26e07674c239e3f041f076a051152760157c

**Comment by gmjacob** [comment]
We are not facing this issue anymore either. I just verified it, maybe it got fixed somewhere down the line at somepoint.
