### ISSUE TITLE
In Brave Browser - MetaMask Extension not recognized in Apps when Browsing using in Private Mode both with or without Tor

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#4915]
User submitted ticket reporting this.  Ticket #: 4276.  Confirmed MetaMask does interact with websites in "private tabs with Tor".  

Tested on a couple dex and confirmed issue exists on v4.8.

**Comment by rdymac** [comment]
Ticket with more info, which could use some follow up once resolved: # 3519

**Comment by bdresser** [comment]
Might relate to https://github.com/MetaMask/metamask-extension/issues/4771

**Comment by dpazdan** [comment]
Did some additional testing.  Currently MM does not work in Private browser mode at all on Brave browser.  With or without Tor option.

It does work in Private Browser mode in Chrome and Firefox.
