### ISSUE TITLE
Could I use metamask to secure and use a GPG key?

### ISSUE THREAD

**Issue by ghthor** [MetaMask/metamask-extension#4916]
# Problem

I want to be able to store GPG encrypted files into IPFS and send someone an IPFS hash as the link. I want them to be able open the link in there browser and have the browser decrypt and display the file.

# Why Metamask?

I would like to reuse the engineering that has been going into metamask to store ethereum private keys by extending metamask to store and provide access to GPG private keys as well.

# Thoughts/Questions

#### Would it be better to construct a specific addon while reusing the secure storage that metamask has developed?

Thanks for all the good work, metamask is a stellar piece of software with a great UX and I love the Fox!

**Comment by bdresser** [comment]
@ghthor this is a great usecase, and something we've been discussing for a while. See https://github.com/MetaMask/metamask-extension/issues/1190.

This project is related to a pending EIP, https://github.com/ethereum/EIPs/pull/1098, and we're looking forward to it being finalized. 

I'll let @danfinlay chime in on whether GPG keys pose any particular technical challenges that would make this a larger project than #1190.

**Comment by danfinlay** [comment]
Short term I'd recommend challenging a user with a signature and using the resulting signature as entropy for signatures OR using [our new encrypt/decrypt methods](https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods).

Longer term, our Snaps system will totally make this possible!

Sorry for taking so long to get to this!
