### ISSUE TITLE
Lost my Seed Words for MetaMask

### ISSUE THREAD

**Issue by KoenB9** [MetaMask/metamask-extension#4920]
Dear People,

I am very shocked. After a crash on my computer, I lost my Seed Words file to access my MetaMask account. However, I found a Keystore file (UTC or json file), but when I import it into MetaMask I can not find my Ethereum. I'll get another ETH adress and there is no ETH in my wallet.. How is this possible? And how do I get back into my old account without Seed Words, but with UTC keystore file? If this succeeds, it will make me very happy!

Kind regards,

Koen

**Comment by bdresser** [comment]
hey @KoenB9 - please reach out to support@metamask.io with your issue and they may be able to assist.
