### ISSUE TITLE
White screen while loading plugin

### ISSUE THREAD

**Issue by Nickrtje** [MetaMask/metamask-extension#4921]
Dear support team,

When opening the MetaMask plugin in chrome it will not load. It only shows a white screen (see screenshot). Now that the MetaMask plugin isn't available in the Chrome Store anymore, how can I solve this error?

Kind Regards,
Nick

![schermafbeelding 2018-07-31 om 13 46 17](https://user-images.githubusercontent.com/41954649/43457760-23e2c5c4-94c8-11e8-8f4e-48e8c0b9ec01.png)

**Comment by bdresser** [comment]
@Nickrtje 

- the MetaMask extension is available in the Chrome store. It was only missing for about 6 hours. If you have your seed phrase backed up, you might want to try uninstalling & re-installing the extension. 
- to help us debug, could you inspect your background logs and see if there are any errors present? [Here's some detail](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue) on how to view them.
- this issue has been reported at https://github.com/MetaMask/metamask-extension/issues/4894 so I'm closing this, please feel free to add more details there.
