### ISSUE TITLE
detecting_metamask.md does not describe how to detect metamask

### ISSUE THREAD

**Issue by N-McA** [MetaMask/metamask-extension#4922]
Hey!

I'm trying to understand the guidance provided by
https://github.com/MetaMask/faq/blob/master/detecting_metamask.md

This page does not tell the reader how to detect metamask. Instead, it tells them how to construct a web3 instance in two types of metamask installation; namely injected web3 (current) and provider-only (current beta).

How should one detect metamask? Previous methods have used `(typeof web3 === 'undefined')` but the current page does make it clear that this no longer works, in the case of no injection.

**Comment by bdresser** [comment]
@bitpshr

**Comment by bitpshr** [comment]
Hi @N-McA. The documentation you saw was prematurely merged to master and will only be relevant when we release [EIP-1102](https://eips.ethereum.org/EIPS/eip-1102) support. We fixed the issue so the documentation should once again be accurate. Thanks for letting us know about this issue!

https://github.com/MetaMask/faq/blob/master/detecting_metamask.md

**Comment by N-McA** [comment]
Hey @bitpshr is there no future proof way to check? For now it seems like `(typeof Web3 !== "undefined")` (noting capitalisation) is strictly better than what is provided in the docs, because it will not get borked by EIP-1102 compatibility? But this can only be done if you haven't loaded in `Web3` yourself (In my app, we only load our `Web3` code if the user has MetaMask, because `Web3` is super-phat, so this looks to be our short term solution).
