### ISSUE TITLE
Better wording / description of MetaMask in Chrome Store and Google search

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#4924]
MetaMask does not show up when searching crypto wallet or ethereum wallet in the Chrome store.  It only shows up when searching ethereum or metamask.

I recommend we revisit the wording of the extension in order to help make it more visible to the ethereum community and those new to it, in general.

**Comment by bdresser** [comment]
@danfinlay or @kumavis could you take care of this when you have a sec? at the very least, adding the word "wallet" in the description should increase our visibility

**Comment by dpazdan** [comment]
Proposed Revision:
Title: MetaMask: Ethereum Blockchain wallet and browser extension
Section: Productivity
Description:
MetaMask is an extension for accessing Ethereum enabled distributed applications, or "Dapps" in your browser!

The extension injects the Ethereum web3 API into every website's javascript context, so that dapps can read from the blockchain.

MetaMask also lets the user create and manage their own identities (via private keys, local client wallet and hardware wallets like Trezor™), so when a Dapp wants to perform a transaction and write to the blockchain, the user gets a secure interface to review the transaction, before approving or rejecting it.

Because it adds functionality to the normal browser context, MetaMask requires the permission to read and write to any webpage. You can always "view the source" of MetaMask the way you do any Chrome extension, or view the source code on Github:
https://github.com/MetaMask/metamask-plugin

Enables access to:
Web 3.0
Dapps 
NFTs
erc20
tokens
ICOs
erc271
...and more!

**Comment by danfinlay** [comment]
I have to remember to do this between releases. It may even trigger a new release when we edit this stuff. Thanks for providing the revised copy, David!

**Comment by danfinlay** [comment]
Added to Chrome store description. Still pending Firefox store.

**Comment by danfinlay** [comment]
Updated on Firefox.
