### ISSUE TITLE
metamaks freezes up before i can put pw in and sometimes after

### ISSUE THREAD

**Issue by 0988655331** [MetaMask/metamask-extension#4925]

**Comment by bdresser** [comment]
@0988655331 what browser and operating system are you using? and if possible, could you open the [background logs](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue) and let us know if you see any errors?

**Comment by 0988655331** [comment]
Using Chrome windows says win 7 , sir, I will do my best to get you the
logs. I am having back surgery this week and just cant sit in front of cpu
long enough to get you what you need right now. I'll get back to you soon
as I physically can do it.
Thx much
James mccammon
It's just like it got real slow for no reason. As soon as I get pain pump
put in I will get the logs or you are welcome to log into my cpu if you do
that.
Good day
James mccammon

On Jul 31, 2018 12:28 PM, "bobby dresser" <notifications@github.com> wrote:

@0988655331 <https://github.com/0988655331> what browser and operating
system are you using? and if possible, could you open the background logs
<https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue>
and let us know if you see any errors?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MetaMask/metamask-extension/issues/4925#issuecomment-409283227>,
or mute the thread

**Comment by 0988655331** [comment]
says win 7, using google chrome
this may help i dont know

This content moved to
https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md
.

**Comment by 0988655331** [comment]
Thank you so much. You don't know the pain you saved me.....


Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by 0988655331** [comment]
Sir,When you know what I should try, please let me know. I am not planning on selling these coins for a while anyway. Just knowing they are there and safe is the most important thing and since I have the number and word phrase, I should be fine til you all figure out why it is timing out. The kupi metamask works just fine on the same cpu and the brown fox metamask works fine on my laptop although neither have anything in them. Yesterday when it almost came up, I could see the little bit of eth. And the alt coins were trying to load, so they should be there. Thx much and have a great eve and thx for all.James


Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by 0988655331** [comment]
Also Sir, I have meta mask on my laptop and it is on the same WiFi my main cpu is on, but I tried using the pass phrase to have the one on my laptop work since my main one is not, but there must me a different cpu address stopping me from doing so. Thought I would tell you I tried.James


Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by 0988655331** [comment]
Would you suggest I remove the program off my cpu then Re install it? I can put the 12 word phrase in, just don't want to lose my coins. No hurry,  the program will try to come up in the beginning then get stuck. I have no idea. Whatever is safest for my coins as I have quite a bit of money in them I will do.Thank youHave a great dayJames mccammon


Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by bdresser** [comment]
if you have your seed phrase, your tokens are safe! Uninstalling & re-installing the extension may help resolve this problem. 

We've had other issues reported like this, so I'm going to close this particular issue and ask you to reach out to support@metamask.io with further questions. Thanks for your time!

**Comment by 0988655331** [comment]
That's wild you said that. I just reset my cpu earlier. I got rid of the kupi fake one and now metamask comes up quite fast. I have not put in the phrase, but have them on a thumb drive. Yea, think this is best way to go. I'll do the rest tomm. Only can sit for about 30 min now, sucks...thx so much and take care


Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------
