### ISSUE TITLE
Integrate Coinmama for fiat onboarding

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#4927]
Coinmama is a retail exchange based in Israel. Providing more options to get users up & running with their first ETH can generally help with onboarding and usability.

The Coinmama team will take the lead on integrating this into the extension.

The entry point should live on the "Deposit" page / popup, which shows after a new user completes onboarding.

Probably makes sense to build this in to the new UI, as we'll be moving users off the old one shortly.

<img width="500" alt="screen shot 2018-07-24 at 10 58 05 am" src="https://user-images.githubusercontent.com/1016190/43484187-792542e2-94c2-11e8-9870-24a5733315af.png">

**Comment by Robbiekruszynski** [comment]
Hi @bdresser, 
I know this ticket has been on ice but it is not forgotten! I wanted to reach out and let you know we are migrating our feature requests, along with overall community support to [zendesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas). Please feel free to add a ticket there. 

Going to close this ticket.
