### ISSUE TITLE
请问有没有正确的接口说明

### ISSUE THREAD

**Issue by joenhon** [MetaMask/metamask-extension#4929]

**Comment by bdresser** [comment]
@joenhon start here: https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md
 
We expose the standard [web3 API](https://github.com/ethereum/wiki/wiki/JavaScript-API).

And there's some more basic documentation [here](https://github.com/MetaMask/metamask-extension/tree/develop/docs#documentation).
