### ISSUE TITLE
我只想简单的调用，签名一个事务，为什么一直就找不到调用的接口方法

### ISSUE THREAD

**Issue by joenhon** [MetaMask/metamask-extension#4930]
<html>
	<head>
		<meta charset="utf-8">
		<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js/dist/web3.min.js"></script>
		<script type="text/javascript" src="D:/AIRDROP_JS/node_modules/web3/dist/ethereumjs-accounts.js"></script>
		
		<script type="text/javascript">
			var Web3 = require("web3");
			// 连接到以太坊节点
			var localWeb3  = new Web3(new Web3.providers.HttpProvider("https://rinkeby.infura.io/v3/30a5e75585ae4636b1c53d216ede9847"));//http://localhost:8545
			var BigNumber = require('bignumber.js');
			window.addEventListener('load', function() {

				// Checking if Web3 has been injected by the browser (Mist/MetaMask)
				if (typeof localWeb3 !== 'undefined') {
					// Use Mist/MetaMask's provider
					web3js = new Web3(web3.currentProvider);
				} else {
					console.log('No web3? You should consider trying MetaMask!')
					// fallback - use your fallback strategy (local node / hosted node + in-dapp id mgmt / fail)
					web3js = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
				}
				 // Now you can start your app & access web3 freely:
				//startApp();

			})
			function GasPrice(){
				document.getElementById("Price_span").innerHTML =getGasPrice()/1000000000;
			}
			function tijiao(){
				var value=document.getElementById("value").value;
				console.log(value_(value));
			}
			function getPeerCount_(){
				document.getElementById("con").innerHTML =getPeerCount();
				console.log(getPeerCount());
			}
			function sen(){
				document.getElementById("con").innerHTML = sendRawTransaction();
			}
			
			

			// 判断是否连接节点
			var connected = localWeb3.isConnected();
			if(!connected){
			  console.log("node not connected!");
			}else{
			  console.log("node connected");
			}
			function value_(val){
				var value = localWeb3.fromDecimal(localWeb3.toWei(val, 'ether'));
				return value;
			}

			function getPeerCount(){
				return localWeb3.net.peerCount;
			}
			function getGasPrice(){
				return localWeb3.eth.gasPrice;
			}
			function sendRawTransaction(nonce,gasPrice,gasLimit,to,value,data){
				var rawTx = {
				  nonce: '0x00',
				  gasPrice: '0x09184e72a000', 
				  gasLimit: '0x2710',
				  to: '0x0000000000000000000000000000000000000000', 
				  value: '0x00', 
				  data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057'
				}
				var tx = new Tx(rawTx);
				tx.sign("130171155707");
				var serializedTx = tx.serialize();
				localWeb3.eth.sendRawTransaction(serializedTx.toString('hex'), function(err, hash) {
				if (!err)
					console.log(hash); // "0x7f9fade1c0d57a7af66ab4ead79fade1c0d57a7af66ab4ead7c2c2eb7b11a91385"
				});
			}
			function estimateGas(to,data){
				var result = localWeb3.eth.estimateGas({
					form: "0xb6f362f29705af19cb3559878099f92d183646cd",
					to: "0xbcb9235387955ca174d5943ea75c4a02cb4d3dda", 
					data: "0x095ea7b3000000000000000000000000b6f362f29705af19cb3559878099f92d183646cd00000000000000000000000000000000000004ee2d6d415b85acef8100000000"
				});
				console.log(result);
				return result;
			}
			// 合约ABI
			var abi = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferAuthority","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferDataAuthority","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_value","type":"uint256"}],"name":"burn","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"sellPrice","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"dataAddress","type":"address"},{"name":"logicAddressr","type":"address"}],"name":"setBitSTD","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"addr","type":"address"}],"name":"migration","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"add","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"target","type":"address"},{"name":"mintedAmount","type":"uint256"}],"name":"mintToken","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_value","type":"uint256"}],"name":"burnFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"buyPrice","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferLogicAuthority","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"buy","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"addr","type":"address"}],"name":"frozenAccount","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"},{"name":"_extraData","type":"bytes"}],"name":"approveAndCall","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"authorizer","type":"address"},{"name":"sender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"amount","type":"uint256"}],"name":"sell","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"target","type":"address"},{"name":"freeze","type":"bool"}],"name":"freezeAccount","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"logicAddressr","type":"address"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"target","type":"address"},{"indexed":false,"name":"frozen","type":"bool"}],"name":"FrozenFunds","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Burn","type":"event"}];
			// 合约地址
			var address = "0xd97b92aCC0AefEBC2A65Cd88ED12B50e4f8f2D59";
			// 通过ABI和地址获取已部署的合约对象
			var metacoin = localWeb3.eth.contract(abi).at(address);

			
			setInterval("GasPrice()",1000);
		</script>
	</head>
	<body>
		<p>
			当前区块GasPrice：<span id="Price_span"></span>Gwei
		</p>
		<input type="text" name="value" id="value"/>
		<button onclick="tijiao()">ss</button>
		<button onclick="estimateGas(1,1)">hu</button>
		<button onclick="sen()">发送</button>
		<div id="con">
			
		</div>
	</body>
</html>

**Comment by bdresser** [comment]
hey @joenhon I think this question would be better suited to Stack Exchange, we try to keep our issues focused on bug reports or feature requests. thanks!
