### ISSUE TITLE
Gas price estimates of 0 are appearing on ropsten

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4933]
This affects the old and new ui.

Its coming from the `metamask-controller.js` `getGasPrice` method. The problem is basically:
- gas prices from recent blocks are in WEI and the `getGasPrice` divides them by 1000000000 to convert the prices to GWEI
- the metamask backend uses BN.js everywhere
- ropsten is successfully processing transactions with really low gas prices. I am seeing 50000 WEI as a common value
- BN.js can't deal with fractional decimals, so the conversion to GWEI of these low gas prices produces a value rounded to 0
- `getGasPrice` estimates gas by getting the median value of the lowest price from each of the most recent 40 blocks
- because of the rounding issue mentioned above, this median value is often being calculated to 0

Where as the correct estimate might be something like 0.0005 GWEI

This will be resolved relatively soon as we are going to be getting gas price estimates from infura. However, that will definitely not be before the next release.

Other options include switching the background to bignumber.js, or just adding a new method that returns price in WEI and handling the conversion to GWEI in the new ui only.

cc @alextsg @whymarrh

**Comment by bdresser** [comment]
@danjm is this in production or on develop?

**Comment by danjm** [comment]
@bdresser Develop (but probably happening on production as well, the code causing this has not change since last release). This won't happen all the time as the estimation of gas price depends on averages over a set number of recent blocks. The issue seemed to be fairly frequent last week.

**Comment by whymarrh** [comment]
@danjm is this something we can fix or was this a temporary issue?

**Comment by KaloNK** [comment]
What if in the settings we have a dropdown (like "Currency Conversion") to select the units to show in (separately for gas and for balance). BN should stay in WEI and converted/rounded only to display it.
That way,  one may show the balance in miliether for example and select the gas price to be GWEI on MainNet and MWEI on test nets

**Comment by Gudahtt** [comment]
I am unable to reproduce this. I suspect it's no longer an issue because we use Infura for our initial gas estimates now.
