### ISSUE TITLE
Plugin flickers when opened on Brave Browser

### ISSUE THREAD

**Issue by pcatana** [MetaMask/metamask-extension#4935]
When trying to open MetaMask on Brave browser it starts to flicker.    
Check video:     
![ezgif com-optimize](https://user-images.githubusercontent.com/19393057/43545893-6a772736-95d7-11e8-8cd6-23a1d8ed6335.gif)

It's been an issue for some time now.     
Brave Browser:  0.23.73 Version    
Windows Latest Update

**Comment by Gudahtt** [comment]
Thanks for the report @pcatana ! Is this still an issue on the latest version of MetaMask? I suspect this has been fixed.

**Comment by pcatana** [comment]
Hi, 
Yes it has. It's been 2 years :D
