### ISSUE TITLE
Token amounts are not formatted with commas

### ISSUE THREAD

**Issue by wooriapt79** [MetaMask/metamask-extension#4937]
Q. After creating a token, you need to mark the token in the meta mask wallet.
The comma (,) is not displayed (ex:100,000,000)
What is the solution to this problem?

Is there a problem with the token generation program?
Is there a separate feature to display currency units in my wallet ..?

I'm curious.
please answer about my question.

**Comment by bdresser** [comment]
@wooriapt79 no problem, we just aren't formatting numbers with commas! feel free to open a pull request if this is something you'd like to see urgently.

**Comment by wooriapt79** [comment]
thank.
Again question.
Is there a problem with the token generation program?

**Comment by Gudahtt** [comment]
I'll close this for now, as it should be covered under #9024.
