### ISSUE TITLE
Filtering by multiple address does not work

### ISSUE THREAD

**Issue by olaf89** [MetaMask/metamask-extension#4938]
It works when using directly ganache-cli but does not work with metamask

From the spec
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs

address is of type DATA|Array, 20 Bytes - (optional) Contract address or a list of addresses from which logs should originate.

Metamask assumes address can be only string and tries to call toLowerCase on it which gives the error "this.params.address.toLowerCase is not a function"

**Comment by olaf89** [comment]
This problem is still occurring, could it get some higher priority as its breaking Ethereum JSON RPC specification?

**Comment by olaf89** [comment]
I think it was issue with provider engine and its fixed in latest version. Actually latest "stable" version breaks my tests but the beta seem to works well.

Here is a fix for this issue i found
https://github.com/MetaMask/provider-engine/commit/248468ca619f4cde49e368eca5ca5fe080abbd5c

Feel free to close it, i could not fully confirm it yet, but in case it does not work ill ask for reopening, thanks.

**Comment by tmashuang** [comment]
Seems this is no longer the case. I used this example to test this by setting the address to an array. If this is not the case and I am missing something please provide a snippet here, or in a new issue.

```
var params = [
  {
    fromBlock: '0x91F37C',
    toBlock: '0x91F37C',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x000000000000000000000000ee25e1ba53c225d250861c8e5a9a3e0fe19c790e',
      '0x000000000000000000000000dfbaf3e4c7496dad574a1b842bc85b402bdc298d'
    ],
    address: ['0x6B175474E89094C44Da98b954EedeAC495271d0F']
  }
]


ethereum.request({
  method: 'eth_getLogs',
  params,
})
.then((result) => {
  console.log('Success')
  console.log(result)
})
.catch((error) => {
  console.log('Error')
  console.log(error)
})
```
