### ISSUE TITLE
withdrawal submitted - did not receive in my metamask wallet

### ISSUE THREAD

**Issue by cablexman** [MetaMask/metamask-extension#4939]

**Comment by cablexman** [comment]
-I submitted a withdrawal of eth approx 1 eth in the arbitraging.co website and the transaction went quickly - on the site and etherscan shows success but i don't see it in my wallet. It's been 3 days now. Arbitraging.co says it's metamask -  the transaction with tx hash.


ARBITRAGING

#	Tx Type	Credit/Debit	Value	Created At

4	User Request for ETH Withdraw (0xfb89775278fe54e6c99d1fb59db8b25616129d534f74aee6fca0e1555bacf035)	Debit	0.997	2018-07-30 09:17:15

Etherscan shows the transaction - but I don't see that amount 0.997 eth in credited in my wallet. Please let me know and help.

THanks

**Comment by bdresser** [comment]
hey @cablexman, looks like .997 ETH was transferred in an internal tx 4 days ago from `0x001fbf99b635bbce9181c6e5c3e2eee0efafc560` (arbitraging.co) to `0x20890f6f8954a13ad93972c2ac15412573f9fea1`, which is presumably your address.

Etherscan says the total balance for that address is 12.3 ETH. What are you seeing in MetaMask?

(cc @tmashuang)
