### ISSUE TITLE
firefox : forever in generating transaction state

### ISSUE THREAD

**Issue by thelostone-mc** [MetaMask/metamask-extension#4942]
**Browser:** Firefox Quantum 61.0.1 (64-bit)
**OS:** MAC

Metamask-extension seems to be stuck in a forever waiting state ( stating generating transaction ) after I had tried signing a transaction over at Gitcoin thus making it unusable.
It's been stuck in this state for a few days now 😓 

<img width="361" alt="screen shot 2018-08-03 at 8 36 57 am" src="https://user-images.githubusercontent.com/5358146/43622207-99768d34-96f8-11e8-99d2-0f8bb2de96e7.png">

Any way I can get past this without reinstalling the plugin ?
Works fine on other browsers though

**Comment by bdresser** [comment]
@thelostone-mc thanks for reporting. Do you see anything in your popup log or background log? You can find instructions on how to view your logs [here](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue). (cc @tmashuang)

**Comment by thelostone-mc** [comment]
@bdresser Ah so i just disabled and enabled the plugin and it worked 🤔 
Guess my transaction got stalled over the rinkeby network / so 

Closing this now ! PS: thanks for making metamask soo awesome ^_^
