### ISSUE TITLE
[ALL] Look at the Weaknesses of other Projects

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#4943]
Hi there all!

My role within this project has ended a few weeks ago. The main results can be found within:

https://github.com/MetaMask/metamask-extension/issues/4060

and most importantly:

https://github.com/lazaridiscom/mm-vault - (see the linked issues within the readme)

**Applying the Project-Redesign** is still the most important thing.

To those who have blocked the Project-Redesign:

I suggest that you look at the issues within other projects. This makes it easier to realize the flaws in ones own project:

https://github.com/EOSIO/eos/issues?utf8=%E2%9C%93&q=+author%3Alazaridiscom+

Its nearly always the same pattern:

* Missing Transparency
* Missing Procedures
* Weak Build and Test-Systems (e.g. "Missing Abstraction/Reuse/Unification")
* Weak Abstraction/Reuse/Unification/Clarity within the code-base
* ...

Please feel free to contact me at any time, for the case you wish to finally apply a Project-Redesign.

Cu around!

**Comment by bdresser** [comment]
Thanks @lazaridiscom. Will leave this open for a couple days to make sure the team has time to see it. Best of luck!
