### ISSUE TITLE
separate wallets for each network (main/test/...)

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#4949]
For development and testing, it would be great to have different wallets (for each network). You would switch to mainnet, you would have your wallet with your (real) mainnet accounts, you switch to a test networks, you would use a dedicated wallet for that network.

Instead you have one wallet, which contains real live ETH accounts as well as (worthless) Test-ETH in another account. If you send real ETH by accident to a test account, its gone. If you select by accident a mainnet account while testing you might easily loose quite some real ETH.

As a workaround and to protect my assets, I currently have one browser (Chrome) with Metamask which only contains Test Accounts and another browser (Brave) with Metamask only with real mainnet accounts ... but ideally that would not be necessary.

If MetaMask aims for mass adoption and a broader audience, then it should a) make the life of developers easy, and b) protect real mainnet assets as good as possible.
Together with the more general UX failures of the new UI (see here) ->
https://github.com/MetaMask/metamask-ui/issues/23
https://github.com/MetaMask/metamask-ui/issues/24
..., I would say that MetaMask is (unfortunately) even much further away from that goal now.

**Comment by bdresser** [comment]
> You would switch to mainnet, you would have your wallet with your (real) mainnet accounts, you switch to a test networks, you would use a dedicated wallet for that network.

This is how the extension works. By switching the network in the top-right corner, you switch between wallets on different networks. 

If you create a new MetaMask account (in the top-right menu), you're creating an Ethereum account on every network. Those Ethereum accounts have the same address across networks, which is nice: if I then send from MetaMask Account 1 to MetaMask Account 2, it's automatically going to send on the same network. 

This of course works differently for imported accounts, which may exist on only one network and the safeguards of native account generation aren't the same.

Perhaps I'm misunderstanding your suggestion?

**Comment by SvenMeyer** [comment]
I wasn't aware that there is such a difference between MM generated accounts and imported accounts

Anyway, especially when in comes to mainnet accounts, I would not be keen to use the same address on another network (ie. for testing), that is even more prone to errors. I would always want to use a different account (number) across various networks. I would even argue that any account should actually only be valid on one network - especially when it comes to mainnet accounts. Maybe (?), there is a scenario that somebody wants to use a certain account number on one test network and wants to use the same accounts number on a different test network, but I think this scenario does not make sense either, as for testing you would anyway refer to theses accounts by account[0], account[1], ... no matter what the account number is.

The next issues is, if you regenerate a wallet from the seed words, maybe for testing because you want to have the same account numbers than described in some tutorial for easier verification. Currently that would wipe out the whole wallet including all real mainnet accounts (hopefully you have a backup, but that's a good idea anyway).

Also, if I import or export a wallet, I have to deal with (a potentially long list of) account numbers, not knowing which ones are relevant within what network. If I would have different wallets for different networks, then I could backup and restore just real accounts or just the accounts from another test network without affecting accounts for mainnet.

If you have all accounts in one wallet and would like to implement a feature to tag them for which network they are relevant, then it becomes an interoperability problem with other wallets as there is no standard exchange format and you can not derive from the address to what network they belongs to.
If test and mainnet accounts would live in different wallet, then you could just import/export a list of real or test accounts, the only requirement being that the filename or a header/comment within the file would state the relevant network.

I hope I was able to summarize my thoughts about usage (scenarios) and it inspires a discussion how this can be handled best.
