### ISSUE TITLE
Add option to autmatically log out

### ISSUE THREAD

**Issue by lunokhod** [MetaMask/metamask-extension#4950]
Metamask is very risky and insecure for me, because you remain logged in until you manually log out. Even if I close my computer and wake it up several days later, I will still be logged in. Thus, if your laptop is stolen while you are authenticated, you are screwed.

I propose to add a setting that will allow you to automatically log you out after a certain amount of time, and/or whenever your computer goes to sleep.

**Comment by whymarrh** [comment]
I'm closing this in favour of #39—this is definitely something on our radar
