### ISSUE TITLE
Generic modal component should provide optional top right closing 'X'

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#4956]
`metamask-extension/ui/app/components/modals/modal.js` is used to create most of the modals in the new ui.

In provides a fade in/out modal container that will close on a click of anything outside its border. It does not provide an 'X' in the top right corner of the modal that will close the modal when clicked. However, this top right x is a feature of multiple modals. We should make it possible to add a consistently styled closing x with an addition of a single property to the modal config.

**Comment by bdresser** [comment]
@danjm check out #4963
