### ISSUE TITLE
Private key export window displays wrong account for correct private key in beta UI.

### ISSUE THREAD

**Issue by TimTinkers** [MetaMask/metamask-extension#4957]
To the best of my knowledge this hasn't been reported elsewhere.

When attempting to export private key from the full-tab web interface for an account in MetaMask using the beta interface, MetaMask automatically switches to the first account listed in the extension in the window which displays the private key. It displays the icon for that first account and the correct address for that first account, but actually shows the private key for the requested account. This is usable but gives the impression that the user requested the wrong private key.

Bug report:
  *  The account icon and public address displayed in the private key export window should match the one I'm exporting the private key for.
  *  The account icon and public address displayed in the private key export window match the first account in the account list.
  *  Chrome 67.0.3396.99 (Official Build) (64-bit)
  *  Windows 10

Thank you.

**Comment by bdresser** [comment]
thanks for reporting @TimTinkers. I've been unable to reproduce this, so let me make sure we're doing the same thing:

1. go to full-screen MetaMask, beta UI
2. switch to Account 2
3. click "Details" then "Export Private Key" then type password
4. get private key

When I do this, the UI shows the avatar & public address for Account 2 the whole time. The private key I receive in (4) corresponds to Account 2 as expected. 

You're saying you receive the private key for Account 2 (as expected), but you see the avatar and public address for Account 1 on the details screen? Could you include a screenshot? 

<img width="736" alt="screen shot 2018-08-07 at 12 44 15 pm" src="https://user-images.githubusercontent.com/1016190/43798513-b00cedb4-9a3f-11e8-8dbf-837ae4ca06af.png">

(cc @tmashuang)

**Comment by TimTinkers** [comment]
> You're saying you receive the private key for Account 2 (as expected), but you see the avatar and public address for Account 1 on the details screen?

Yes, that's exactly correct. Here's a gif with some sacrificial accounts.

![Account changes.](https://i.imgur.com/zgsNM8C.gif)

**Comment by tmashuang** [comment]
Some leading questions about `Do Not Use 2`, was it imported as JSON or Priv key? If it was JSON are you using the password created it along with it?

**Comment by bdresser** [comment]
Thanks for the GIF, exactly as you described. Not good!

Does this happen in the extension view as well, or just full-screen?

And could I trouble you to email your state logs to support@metamask.io. [Here's how](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-Old-Ui).

@danjm or @alextsg could you take a look?

**Comment by TimTinkers** [comment]
Both of these accounts were imported as private key. This happens in the extension view as well as full-screen. I've emailed my state logs.

**Comment by TimTinkers** [comment]
@whymarrh happy to help, thanks for taking care of it.
