### ISSUE TITLE
won't download- getting an error message. 

### ISSUE THREAD

**Issue by Theisha-Marie** [MetaMask/metamask-extension#4958]

**Comment by bdresser** [comment]
@Theisha-Marie what browser are you using? And what's the error you see? A screenshot might be helpful.

**Comment by gala1956** [comment]
Не открывается Метамаск 
![met](https://user-images.githubusercontent.com/33600339/43948239-277015de-9cac-11e8-9d5a-1456cbec1106.png)

**Comment by bdresser** [comment]
@gala1956 try closing the extension from the Chrome Task Manager - `...` --> More Tools --> Task Manager.

Closing this original issue, please let us know if you're still having trouble.

**Comment by gala1956** [comment]
Thank you, I did so, but I have a NEW account for the Metamask and it's blocked: writes for security reasons ??10.08.2018, 21:31, "bobby dresser" <notifications@github.com>:@gala1956 try closing the extension from the Chrome Task Manager - ... --> More Tools --> Task Manager.
Closing this original issue, please let us know if you're still having trouble.
