### ISSUE TITLE
blank screen and blink

### ISSUE THREAD

**Issue by idotial** [MetaMask/metamask-extension#4959]
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior
open metamask successfully
  *  Actual Behavior
blank and blink
  *  Browser Used
brave
  *  Operating System Used
osx

![2deceae8-cffc-4698-b8ca-3146a2cd5127](https://user-images.githubusercontent.com/15015597/43753607-38a54c5e-9a39-11e8-92ba-44fcc9e26644.png)
![d70742af-f133-439c-a647-15e48f174160](https://user-images.githubusercontent.com/15015597/43753621-4149b11a-9a39-11e8-8147-b72010e0347a.png)

**Comment by renaud12** [comment]
im having the same issue and i cant reinstall cuz i didnt save seed phrase help pz

**Comment by bdresser** [comment]
Thanks for reporting @idotial. If you could share a bit more information it'll help us debug.

1. could you visit `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html` to load the extension full-screen, right click the page and click "Inspect Element" -- do you see any errors in the console?

2. from the console, enter `logState(true)` which will copy your state log to your clipboard. Could you send this to support@metamask.io and reference this issue number?

**Comment by bdresser** [comment]
@renaud12 looks from your screenshot like you're on Chrome, check #4894 / #4817 and perhaps try restarting the process in Chrome Task Manager as described in https://github.com/MetaMask/metamask-extension/issues/4817#issuecomment-409717110

**Comment by idotial** [comment]
@bdresser I use it in brave not chrome, it seems like the blank screen keep changing and i couldn't right click the page to inspect it, you can see the two screenshot are different, it's like switch a thousand times per second

**Comment by idotial** [comment]
![etasfasd](https://user-images.githubusercontent.com/15015597/43811784-ecf356c6-9af0-11e8-937c-64be298d2b64.png)
@bdresser here is the screenshot of "Inspect Element" in the way you say, is it right that i use `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html` in brave?

**Comment by renaud12** [comment]
@bdresser  i did that alredy many times but doesnt work is say i have a new update if i update metamask will ask me for seed phrase later? cuz i dont have them sadly

**Comment by renaud12** [comment]
@bdresser yeah im ussing crhone and window 10 should i do this ? or i will ened to type ty seed phrase after the update? https://gyazo.com/56de3f942a03e770dbf56163a911afba

**Comment by renaud12** [comment]
if i click no thanks it goes blank again

**Comment by renaud12** [comment]
@bdresser  https://gyazo.com/48511199010ab3a58d094db352d4c615?token=85f182097ef2a6058de88c9696659b57 this is what i get on console

**Comment by bdresser** [comment]
for blank screen on chrome, we're tracking the issue on https://github.com/MetaMask/metamask-extension/issues/4894

for blank screen on brave, we're tracking the issue on https://github.com/MetaMask/metamask-extension/issues/4782

the issues may be related, but steps to debug are often different so tracking them separately for now.
