### ISSUE TITLE
Metamask crashing after update august 07 2018

### ISSUE THREAD

**Issue by jfdelgad** [MetaMask/metamask-extension#4967]
Just after update, metamask crash after 5 seconds of clicking on it. Restating the browser (chrome) generates the same pattern once an again.

**Comment by bdresser** [comment]
@jfdelgad anything in your browser console or background logs? You can view the extension logs by following instructions [here](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue).

cc @danfinlay @tmashuang

**Comment by tmashuang** [comment]
https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue

**Comment by jfdelgad** [comment]
Can't get the logs because even if I do not click on metamask it closes after 5seconds of opening the browser (chrome)

**Comment by tmashuang** [comment]
The background logs should always show even when the extension is not operating correctly. What about when you navigate to the extension url in a new tab?

**Comment by jfdelgad** [comment]
I just saw that chrome is disabling it each time. I force it to re-enable it. Metamask is now requesting to modify the data that I copy and paste, is this correct?

**Comment by bdresser** [comment]
Yep, this is required to allow us to let you copy your address from within the extension to your clipboard. Thread [here](https://www.reddit.com/r/ethereum/comments/566pot/are_the_new_metamask_permission_safe/).

Any clues why Chrome is disabling it?

**Comment by jfdelgad** [comment]
Nope,but after going through the extensions settings in chrome and turning and re-anable it, it is working.

**Comment by danfinlay** [comment]
I sure hope that's a rare issue! Thanks for sharing it with us.
