### ISSUE TITLE
will not start in firefox after update. Removing key file.  

### ISSUE THREAD

**Issue by galturok** [MetaMask/metamask-extension#4968]
after a few weeks of not using metamask I was unable to get the program to launch the popup.html. 

The window would just stay blank then disappear on any click out. 

Debugging showed a undefined H error

I did not have my words to remake the den in another computer, but i still had the password so I needed a way to recover my vault data. Lots on online info on where to find the vault in chrome, but almost nothing out there for firefox. 

I was able to recover the wallet by doing the following. 

I copied the profile Firefox and inserted in in a different computer
step 1 copy the following files to a flash drive:
     .... AppData\Roaming\Mozilla\Firefox\Profiles\The_profile_that_you_used    
     .... AppData\Local\Mozilla\Firefox\Profiles\The_profile_that_you_used   
     .... AppData\Roaming\Mozilla\Firefox\profiles.ini

step 2 copy and paste the "The_profile_that_you_used" into the following:

     .... AppData\Roaming\Mozilla\Firefox\Profiles\  
     .... AppData\Local\Mozilla\Firefox\Profiles\

Step 3 open the profiles.ini file from your flashdrive and in the new computer with notepad. 
you will see in the flashdrive file:

[Profile0]
Name=The_Name
IsRelative=1
Path=Profiles/The_Profile_that_you_used

Copy this and paste it into the profiles.ini file in the new computer. Change The [Profile0] to [Profile1]. 
Save the file. 

You should now be able to launch firefox on the new computer and run metamask, you will not need to install metamask on the new computer, if it works, it will already have it. It will ask for you password and unlock. 

You may need to launch the profile manager for firefox using the run: firefox.exe -p

Dont know it this helps anyone but it worked for me.

**Comment by bdresser** [comment]
thanks @galturok this is definitely helpful for someone out there.

@alacrity26 @rdymac could we get this in the Support Center?

**Comment by pipermerriam** [comment]
I'm experiencing the same issue and have been unable to get metamask to launch.  Has anyone come up with a way to fix the issue?

**Comment by perissology** [comment]
same, I just get the blank screen when metamask tries to open

**Comment by perissology** [comment]
okay, here's what I did to get MetaMask to work again. Note this will reset the MetaMask state, so make sure you have the seed phrase (which you should already have backed up).

Open console & run the following:

`localStorage.getItem('metamask-config')`

If you get an `NS_ERROR_FILE_CORRUPTED` error, the firefox db was corrupted at some point.

As stated on [Ask Ubuntu](https://askubuntu.com/questions/110649/how-can-i-stop-firefox-throwing-a-ns-error-file-corrupted-error):

> Firefox stores its HTML5 data in a file called webappsstore.sqlite. That's sitting in your profile directory which lurks somewhere in ~/.mozilla/firefox/....default/ (depending on what your profile is called).
>
> Move that out the way and restart Firefox and everything will come back to life.

If you move/delete that file & restart firefox, a new `webappsstore.sqlite` will be built & MetaMask will work correctly.

**Comment by Platinumwrist** [comment]
That’s all I’ve been getting as well what’s the solution you guys think

**Comment by pipermerriam** [comment]
I've been opening the actual extension page which you'll find under a `moz-extension://` URI but it appears to have a big UUID in it which may be special to each installation.

**Comment by Gudahtt** [comment]
Thanks for all of these helpful instructions! I'll close this for now as any blank screen issues are already being tracked under #4894, but any help reproducing this would be greatly appreciated! We haven't been able to reproduce this issue yet.
