### ISSUE TITLE
Display New UI by default

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#4971]
Once https://github.com/MetaMask/metamask-extension/issues/3386 is completed, we should put all users in the New UI by default.

* For users who were still on the old UI, we should display a welcome screen in the New UI. We can re-use the screen in https://github.com/MetaMask/metamask-extension/issues/4811 with some updated copy
* The option to switch to "Old UI" should remain in settings (for now)
* Old UI should include a persistent banner that asks the user why they prefer the old UI. @bdresser to find appropriate survey / feedback mechanism.

**Comment by bdresser** [comment]
@CruzMolina I don't think you can detect which UI they're on, but you can check their version with

```
web3.version.getNode(function(err, result){ console.log(result) })
```

**Comment by CruzMolina** [comment]
That returns `MetaMask/v4.9.0` for both the old and new UI.

**Comment by bdresser** [comment]
@CruzMolina We'll be on the new UI well before 11/2, hopefully in the next couple weeks
