### ISSUE TITLE
Unable to resend tx with higher gas in v4.9.0

### ISSUE THREAD

**Issue by devenoges** [MetaMask/metamask-extension#4974]
After the update to 4.9.0 I tried to send some transactions with a low gas. Normally MetaMask displays a text/link like "Taking too long? Resend the transaction here" after a few seconds. But this link isn't displayed anymore.

To be sure I waited some hours and restarted Chrome/Metamask several times, but the link does not show up.

This means: Currently my transactions are stuck because I cannot raise the gas with MetaMask.

**Comment by bdresser** [comment]
@devenoges thanks for reporting - are you using the old UI or the new/beta UI?

**Comment by devenoges** [comment]
Did not see in old UI after update, then switched to new UI, no change. Tx gone through now so can not check atm. 

Where should the 'reprice' link appear? 
After how long or how many blocks until the reprice option is shown? 

(btw using Chrome on linux)

**Comment by devenoges** [comment]
Tried another TX, the current pending tx has nonce around 500, the "Taking too long? Increase the gas price on your transaction" link does appear but its at the bottom of the list of shown transactions below  an earlier dropped transaction from months ago with a nonce around 20 rather then the current pending tx.

I can try grabbing a screenshot next time if that helps.

**Comment by bdresser** [comment]
Ok thanks for the extra detail.

> its at the bottom of the list of shown transactions below an earlier dropped transaction

"below" as in, it's asking you to retry the dropped transaction? or it's included on a pending transaction that's further back in the history than this old dropped transaction? Trying to determine if it's an issue with history ordering, or with which tx we're asking to retry.

Heads up @danjm @estebanmino

**Comment by danfinlay** [comment]
@devenoges actually what would be perfect for this would be your state logs:
https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-New-UI-

You can email them to support@metamask.io for increased confidentiality (only addresses are disclosed, no private keys).

Sounds like there was an issue with https://github.com/MetaMask/metamask-extension/pull/4885 @estebanmino, sorry we didn't catch it before release.

**Comment by devenoges** [comment]
I recall using MEW to fix some stuck transactions a while ago, possibly related. 

Have emailed state log, thanks!

**Comment by frankiebee** [comment]
after talking with @danjm it's clear what the problem is:
when a transaction is retried and succeeds outside of metamask the transaction in metamask is not marked dropped:

some solutions and actions moving forward:
background: i can put guards for pending transaction to check if the known nonce has exceeded the pending transaction in metamask and if so transition the status to dropped.
 
ui: instead of just putting the retry button on the first pending transaction the ui can request the transactionCount and apply the retry button to the last transaction matching that nonce.

**Comment by devenoges** [comment]
Did the fix for this get merged into 4.9.2? 

I still see the same behavior, do you want an updated state log?

**Comment by bdresser** [comment]
@devenoges yeah, an updated state log would be helpful.

we merged the UI fix mentioned above, but if you're submitting tx outside MetaMask it's still possible our nonce will get out of sync and we'll ask to retry the wrong transaction - we'll address that in https://github.com/MetaMask/metamask-extension/issues/5031
