### ISSUE TITLE
Token balance display with non standard Decimals eg DGD DGX RHOC

### ISSUE THREAD

**Issue by devenoges** [MetaMask/metamask-extension#4977]
Automatically added tokens with decimals != 18 appear to display wrong balance in both old and new UI with version 4.9.0

e.g. DGD balance of 0.000002942 shows as 2942 DGD
(DGD has 9 decimals)

**Comment by bdresser** [comment]
thanks for reporting @devenoges. @danjm @estebanmino could you take a look?

**Comment by danjm** [comment]
@devenoges Can you confirm that the incorrect balance shows up for DGX and RHOC as well?

The DGD error makes sense given our current method of finding decimals, as the DGD token contract does not have a decimal method https://etherscan.io/address/0xe0b7927c4af23765cb51314a0e0521a9645f0e2a#code

I'll investigate what we might be able to do about the DGD error, but if you can confirm whether the error shows up for the other tokens it will help us identify if there are further bugs in the existing code.

**Comment by devenoges** [comment]
Sorry should have checked more thoroughly. Address holds RHOC but appears that is not added automatically. Do not have any DGX so can not check that.

**Comment by estebanmino** [comment]
@devenoges thank you very much for the feedback. As you said RHOC is not auto detected, neither DGX. In DGD case it should be fixed.
