### ISSUE TITLE
Updated metamask asks for additional permissions

### ISSUE THREAD

**Issue by bobbyvinon** [MetaMask/metamask-extension#4978]
After updating this morning, metamask is disabled and asks for additional permissions:

* read and change your data on all eth sites and all test sites

what is this? i want to use it only for purse management and i don't want give this permissions to metamask.

**Comment by ngtuna** [comment]
Same concern here

**Comment by simonk1234** [comment]
Same here. How do I know it can be trusted?

**Comment by bdresser** [comment]
Hi @bobbyvinon and others - those permissions are for two new features we've added in 4.9.0

The permission to "change data on .eth and .test sites" is so we can reroute you to the content hash of sites hosted on IPFS / ENS. (https://github.com/MetaMask/metamask-extension/pull/4405)

The permission to show browser notifications is so we can notify you when your transactions mine. (https://github.com/MetaMask/metamask-extension/pull/4840)

You can read more about what's new in this most recent version (and more on why we request these permissions) here: https://medium.com/metamask/metamask-monthly-august-8b409c3fa18

Totally fair question - next time our feature set changes the permission level we require, we should try to let you know via the UI or something. I will leave this open for a couple days so others with the same question can find it easily.

**Comment by mryellow** [comment]
> The permission to "change data on .eth and .test sites"

Is that what the message was saying!!

Chrome just says "eth" without a dot, making it not very obvious that they're talking about a TLD. Had me wondering, "What the hell is an 'eth' site".

Seems Chrome might need a UX issue opened.

**Comment by JohnAllen** [comment]
Just to be clear, Chrome does not say "change data on .eth and .test sites". It says this:

<img width="437" alt="screen shot 2018-08-09 at 8 04 42 am" src="https://user-images.githubusercontent.com/2800641/43907715-f7c86e5a-9baa-11e8-8b84-e116a2569219.png">

**Comment by JohnAllen** [comment]
For me it says `read and change all data on the websites` I visit.  So is it all or just `.eth`?

**Comment by bdresser** [comment]
@JohnAllen it's all

As described in the reddit post above, the initial permissions on download look like this:

<img width="490" alt="screen shot 2018-08-09 at 2 03 57 pm" src="https://user-images.githubusercontent.com/1016190/43927012-f3075c10-9be0-11e8-846a-9b339902d865.png">

The permission to "read and change all your data on the websites you visit" is what allows us to inject an Ethereum provider and web3 object.

What the original poster is asking about are the additional permissions some user saw after their browsers auto-updated to 4.9.0. Those looked like this:

![image](https://user-images.githubusercontent.com/1016190/43927138-597e2ffa-9be1-11e8-9781-89850595c766.png)

The permission to read and change data "on all eth and test sites" seems redundant after agreeing to the download permissions, and we're investigating why this was shown to users.

**Comment by dsilberschmidt** [comment]
i have this message:
MetaMask is disabled
To re-enable it, accept the new permissions:
.Read and change your data on all eth sites and all test sites
.Display notifications

                                         Remove    Accept permissions

Same concern as previous users. Is this a new permission YOU ask for?
