### ISSUE TITLE
Confirm button is not clickable

### ISSUE THREAD

**Issue by Twibap** [MetaMask/metamask-extension#4980]
![2018-08-08 4 45 07](https://user-images.githubusercontent.com/26022935/43823768-1e8876d2-9b2b-11e8-8f89-1575e812b253.png)

i cannot send ether to my contract
is it relation with "MetaMask: web3 will be deprecated in the near future in favor of the ethereumProvider"??

if i change 'web3' to 'ethjs' in my dApp, not work "require()'

is there way to my contract user send ether to my contract method using metamask

this is my client script to send ether
```javascript
var Web3 = require('web3');
var web3js = new Web3(web3.currentProvider);
var myContract = web3js.eth.contract(myContractABI).at(myContractAddress);

myContract.myMethod.sendTransaction( 
    argument, 
    {from:userAccount, value...}, 
    function(error, result){
        if(error != null)
            console.log(result);
        else
            console.error(error);
});
```

**Comment by williamchong007** [comment]
Do the client have enough ETH to pay for the transaction?

**Comment by Dimazsever** [comment]
I have a similar problem.

**Comment by bdresser** [comment]
thanks for reporting @Twibap.

Do you have enough ETH in Account 1 to cover the transaction? Also, what browser are you using? 

> is it relation with "MetaMask: web3 will be deprecated in the near future in favor of the ethereumProvider"??

This is a standard warning, doesn't affect your UI. Are there any other errors you see in the console?

**Comment by bdresser** [comment]
sounds like this could related to #4955

**Comment by jeffscottward** [comment]
When swithcing back to the old UI in the settings menu - I see
`Transaction Error. Exception thrown in contract code.`

A demo of ours that uses `truffle-contract` to create the contract object, is able to submit.

I think this may explain "Unknown Function" at the top of the new UI

@danfinlay / @bdresser

**Comment by bdresser** [comment]
@jeffscottward are you experiencing the same error as OP? are you sure you have enough ETH to send? 

the "Unknown Function" is expected behavior - we'll show this when we can't lookup the function name in the [method registry](https://github.com/danfinlay/eth-method-registry) we're using.

**Comment by jeffscottward** [comment]
@bdresser - yes same issue. yes have enough ETH. understood re: UF

**Comment by jeffscottward** [comment]
MM @4.5.5 - submission works!
Still see that error though in the MM UI `Execption thrown in contract code`

**Comment by jennypollack** [comment]
hey @jeffscottward does the tx succeed after you submit from the older version of mm? would you mind linking the tx here? 
The `Transaction Error. Exception thrown in contract code.` is from `estimateGas` and iirc in the old-ui we present this to the user but still allow them to submit (which is inline with what you're reporting from the older version) - sounds like in the new-ui that error is blocking

**Comment by bdresser** [comment]
@jtakalai wow I had no idea the difference was that huge. We went with Partiy since it's nice to rely on decentralized infrastructure, but the 4byte registry makes a lot of sense as a fallback for more coverage.

**Comment by jtakalai** [comment]
Yea granted, it's a random service; although its return value would be simple to double-check:
1) ask eth-method-registry
2a) if no luck, ask 4byte.registry
2b) check that the hash of the returned value is same as given signature

That way 4byte.registry at least shouldn't be able to form much of an attack vector.

**Comment by bdresser** [comment]
@jtakalai makes sense to me - opened https://github.com/MetaMask/metamask-extension/issues/5057

**Comment by LenaStarikova** [comment]
Guys, I know it is a closed one, but I have the same on different computers :(

**Comment by lamafab** [comment]
@LenaStarikova Make sure you have enough **ETH** in order to cover the gas cost (transaction fee). Might be nice for MetaMask to give the user a hint on why a transaction cannot be confirmed, though.
