### ISSUE TITLE
Why does MetaMask 4.9 ask for new permissions? 

### ISSUE THREAD

**Issue by consaltus** [MetaMask/metamask-extension#4981]
Hi! Why do you need this permission
Changing the copied and pasted data ?
![image](https://user-images.githubusercontent.com/30024675/43833306-f6d6ee60-9b12-11e8-8f5a-00dc0c1fdcfe.png)

**Comment by bdresser** [comment]
hey @consaltus - those permissions are for two new features we've added in 4.9.0

The permission to "change data on `.eth` and `.test` sites is so we can reroute you to the content hash of sites hosted on IPFS / ENs.

The permission to show browser notifications is so we can notify you when your transactions mine.

You can read more about what's new in this most recent version (and more on why we request these permissions) here: https://medium.com/metamask/metamask-monthly-august-8b409c3fa18

I will leave this open for a couple days so others with the same question can find it easily.
