### ISSUE TITLE
Metamask doesn't respect token decimals when calling approve on ERC20

### ISSUE THREAD

**Issue by weichain** [MetaMask/metamask-extension#4984]
*  Expected Behavior: If I want to approve 120 tokens I should confirm a transaction with 120 tokens
  *  Actual Behavior: I sign a transaction with 120000000000000000000.
  *  Browser Used: Mozilla Firefox, Chrome
  *  Operating System Used: Windows 10/Ubuntu 18

![image](https://user-images.githubusercontent.com/39411116/43841656-56736c54-9b2c-11e8-97b2-dc555aece2be.png)

**Comment by bdresser** [comment]
thanks for reporting @weichain 

@alextsg same as what was reported via Slack

**Comment by leafcutterant** [comment]
Is this screen the result of the same bug? This happened when I was sending Dai.

![0](https://user-images.githubusercontent.com/7106231/44621035-82a64000-a89f-11e8-87b0-d714792a4d4d.png)
