### ISSUE TITLE
Trying to install metamask extension, after i have removed it bu mistake. but it wouldn't allow to to add to the chrome, please help

### ISSUE THREAD

**Issue by steve310572** [MetaMask/metamask-extension#4987]

**Comment by bdresser** [comment]
@steve310572 can you say more about why it wouldn't allow you to add it to chrome? Screenshots may be helpful. 

Try visiting `chrome://extensions` and making sure the extension is "enabled."

**Comment by steve310572** [comment]
All sorted, thank you
