### ISSUE TITLE
problems with eth_signTypedData 

### ISSUE THREAD

**Issue by hbeckeri** [MetaMask/metamask-extension#4990]
I have been using message signing for authentication in my app. To authenticate I generate a challenge on my server, and then metamask users will sign that challenge and send it back to the server to sign in. 

client code:
<img width="459" alt="screen shot 2018-08-08 at 12 18 23 pm" src="https://user-images.githubusercontent.com/8557965/43850165-30f86a6e-9b05-11e8-8a39-c10d903dd6e1.png">

I understand `eth_signTypedData` will be deprecated soon in favor of `web3.eth.signTypedData` and follow EIP-712. This was working fine for me until I updated my metamask version today. I would expect that after I sign the message the metamask notification window would close and the `sendAsync` callback would run. The actual behavior is that I am never seeing the callback for `sendAsync` run. Once I sign the message, the metamask notification window just changes back to the default balance screen rather than closing the running the callback.

If you would like to test this behavior you may visit https://www.poolminer.io/sign-in

I am running macOS 10.13.5 and chrome 67

**Comment by bdresser** [comment]
@hbeckeri this is a known issue, fix should be out today.

duplicates #4975
