### ISSUE TITLE
Export Private Key: entering incorrect password crashes MetaMask

### ISSUE THREAD

**Issue by codyborn** [MetaMask/metamask-extension#4992]
Bug Reports:

  Briefly describe the issue you've encountered
  *  Expected Behavior: Entering incorrect password on export private keys screen should allow password retry.
  *  Actual Behavior: Entering incorrect password prevents future attempts with correct password from working.  MetaMask client shows blank screen after re-opening.
  *  Browser Used: Chrome Version 68.0.3440.84
  *  Operating System Used: Win10

Experiencing this with the new MetaMask UI (v 4.9.0)
![image](https://user-images.githubusercontent.com/11261382/43855319-116cd1a4-9afa-11e8-9cc6-adaefc1a8022.png)

**Comment by bdresser** [comment]
thanks for the report @codyborn, I can reproduce reliably. 

Was able to get the extension working again by ending the process in the Chrome Task Manager 
(`...` --> More Tools --> Chrome Task Manager)


Couple errors in the UI console:

```
ui.js:1 Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
ui.js:1 Uncaught TypeError: Cannot read property '__reactInternalInstance$kfmd1hebaoj' of null
Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
popup.html:1 Error in event handler for (unknown): TypeError: Cannot read property '_currentElement' of null
```

**Comment by whymarrh** [comment]
@codyborn thanks for the bug report, this should be fixed in an upcoming release
