### ISSUE TITLE
Getting metamask version from console

### ISSUE THREAD

**Issue by indie-rok** [MetaMask/metamask-extension#4994]
I was expecting to do `web.currentProvider.metamask_version` or something similar but I can't find the correct command.

Worth saying that I don't need `web3`version. I need `metamask version` (4.8,4.9, etc)

**Comment by bdresser** [comment]
you can use something like 

```
web3.version.getNode(function(err, result){ console.log(result) })
```

Curious: why do you want to detect users' versions? Are you trying to workaround one of the recent issues in 4.9?

**Comment by indie-rok** [comment]
Thank you @bdresser .  Works great. Yes, have some informative screenshots for our users to use metamask. Since v.8 and 4.9 UI does not match. We would need to detect metamask version and render the appropriate image.

**Comment by bdresser** [comment]
Makes sense. Could you share a link? I'd love to improve our documentation and it's good insight to see what other sites find they need to explain
