### ISSUE TITLE
Detect if Metamask is installed

### ISSUE THREAD

**Issue by JaceHensley** [MetaMask/metamask-extension#4998]
Since [web3 will no longer be injected by the extension](https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8) there isn't really a way to detect if Metamask is installed.

What would be the best way of detecting if the extension is installed or not going forward?

**Comment by bdresser** [comment]
hey @JaceHensley - you're right, and that's sort of the point. But this definitely poses some interesting UX challenges. There's an open discussion on Ethereum Magicians on the same topic [here](https://ethereum-magicians.org/t/the-ux-of-eip-1102/814). From that thread:

> Feature detection is impossible, and so Dapps will need to present some kind of open-ended log-in button that both tries to log on and suggests installing a web3 browser if the user doesn’t have one yet.

Suggestions for a smooth UX are welcome! We're working on this on our end as well, feel free to check out our proposed implementation [here](https://github.com/MetaMask/Design/issues/36).

**Comment by JaceHensley** [comment]
So our flow currently allows detection of install while the user remains on our dapp's signin page. What we do is inject an iframe that refreshes until it detects `web3` (since extensions can't inject into already loaded pages). This allows the user to come to our site without MM installed and either be instructed to install MM or continue. And the page only refreshes once the iframe has detected a web3 instance.

We can't really do the same thing with the new request because we wouldn't really want to request from an iframe.

My suggestion would be just a simple `window.isMetamaskInstalled` or something like that. This would still not give the site access to an `ethereum` until they request and the user accepts it. But it would help determine if the site should request access or instruct the user to install MM right off the bat.

This would improve UX as well since we wouldn't be waiting to determine if the user accepted/declined or if they don't have MM installed.

---

I do really like that UX shown [here](https://github.com/MetaMask/Design/issues/36)!

**Comment by bdresser** [comment]
Part of the purpose of [EIP 1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md) is to prevent sites from knowing if the user has any sort of web3 extension installed. Even this basic info can be used to identify the user's browser fingerprint. 

We're aware that adding this layer of privacy makes for a more open-ended experience, where you're not sure whether the user doesn't have MetaMask or if they're just slow. Still, we think this is a necessary step to protect users.

We plan to release a couple tools/components to show the interaction with the `postMessage` API and demonstrate what we think makes sense for good UX. In general, I think it will be palatable to most users if your dapp says something like "Connect with your web3 browser. If you don't have one, get one!"

If it's okay with you, let's keep this discussion on the Ethereum magicians thread where more folks will see it. (cc @bitpshr)
