### ISSUE TITLE
4.9.0 broke eth_signTypedData

### ISSUE THREAD

**Issue by qcdll** [MetaMask/metamask-extension#5001]
verified that 4.8.0 worked.

To reproduce: https://danfinlay.github.io/js-eth-personal-sign-examples/
Click "sign typed data"
NOTE that if you cancel, it still works, but actually signing will not close the popup, and further clicking "sign typed data" does not prompt anything (except warning message from https://github.com/MetaMask/metamask-extension/pull/4905 in console)

**Comment by ninjaahhh** [comment]
seems both *sign typed data* and *sign typed data with ethjs* would fail

**Comment by bdresser** [comment]
this is fixed in develop, should be out in production tomorrow morning. see https://github.com/MetaMask/metamask-extension/issues/4975

going to leave this issue open for now since it keeps getting reported 😄

**Comment by qcdll** [comment]
Thanks @bdresser !

**Comment by bdresser** [comment]
we've updated to 4.9.2, and this issue is resolved - let us know if you're still having trouble!

**Comment by qcdll** [comment]
confirmed, thanks!
