### ISSUE TITLE
Goat Cash (GOAT) Icon

### ISSUE THREAD

**Issue by goatcash** [MetaMask/metamask-extension#5004]
Hi,

How do we get our token logo so that it appears in metamask?

Thanks.

**Comment by goatcash** [comment]
We'd also love to be added to the metamask token search as well, instead of using the custom token addition menu.

**Comment by bdresser** [comment]
hey @goatcash - you can open a pull request on our [contract metadata repo](https://github.com/MetaMask/eth-contract-metadata), it'll take care of both requests

**Comment by goatcash** [comment]
Thanks and will do.
