### ISSUE TITLE
metamask in brave doesn't render (always blank)

### ISSUE THREAD

**Issue by cryprohippo** [MetaMask/metamask-extension#5005]
this is reopening of:
metamask in brave doesn't render (always blank) #4281 
as the issue is still exactly the same. Please let me know if there is a way for me to update a closed ticket instead. 

Hi,
expected behaviour - metamask opens and prompts for login.
actual behaviour -
My metamask extension in brave browser has not worked for a month or two.
When I click on the extension icon, the popup window opens, but is completely blank. It doesn't matter how many times I click on it. Occasionally it is transparent instead of blank. If transparent, it will be blank (white) if I click on it again.
I have noticed a new behaviour (which may have started after windows updates this week, but not certain) but the popup window borders vibrate rapidly - scrollbars on right and bottom, and the left border. Top doesn't have a vibrating border
I've disabled and re-enabled the extension, and reinstalled brave. No change.
 
browser - brave (extension works fine in chrome)
os - win 10 x64 v1803 build 17134.48 (although issue predates this build).
Thanks

I collected an update for brave this morning - 0.23.77
metamask extension is 4.3.0
Is there anything else I need to do? Metamask has been totally non functional for a long time now.

**Comment by bdresser** [comment]
hey @cryprohippo, sorry to hear you're still experiencing this issue. 

this duplicates #4782 so I'm going to close to consolidate the conversation there.
