### ISSUE TITLE
meu metamask sumil

### ISSUE THREAD

**Issue by adnoan** [MetaMask/metamask-extension#5007]
Good morning, my name is Adnoan Majori, I have problems in my metamask wallet, two days ago I was asked to update so I did and my metamask disappeared from my pc. I'm not having any kind of access to it, I'd like to know the What can I do ? my email adnoan40@gmail.com

**Comment by bdresser** [comment]
hey @adnoan, please reach out to support@metamask.io and they'll be able to help answer your questions!
