### ISSUE TITLE
Metamask icon suddenly disappeared. 'metamask is not enabled' i use chrome browser on windows10

### ISSUE THREAD

**Issue by snezanasucurovic** [MetaMask/metamask-extension#5008]
Metamask icon suddenly disappeared. 'metamask is not enabled'
 i use chrome browser on windows10
however when i start to install again 'it has been added' appears i expect bounty.

**Comment by bdresser** [comment]
@snezanasucurovic are you saying you had to re-install to get the extension to appear? 

If you're still having trouble, try heading to `chrome://extensions` and making sure the extension is enabled.
