### ISSUE TITLE
Token amount is displayed in wei

### ISSUE THREAD

**Issue by lukaszGrynasz** [MetaMask/metamask-extension#5011]
When I want to user ERC20.approve metamask display token amount in wei. 
![capture](https://user-images.githubusercontent.com/40950183/43899985-d9c3100c-9be3-11e8-919e-d8ecbdbdf2a1.PNG)

**Comment by bdresser** [comment]
@lukaszGrynasz this was fixed in https://github.com/MetaMask/metamask-extension/pull/4986, should be out in the next couple hours!
