### ISSUE TITLE
User initiated sign arbitrary messages within Metamask GUI

### ISSUE THREAD

**Issue by 1blockologist** [MetaMask/metamask-extension#5018]
feature request

Some wallets make it easy to sign messages within the wallet, instead of going to an external service.

Given that Ethereum libraries in particular offer a variety of signing methods. Having a full service wallet allow the user to initiate a signing request within its own GUI would be a nice feature to explore.

The desired outcome is that was a menu option or button to sign a message, and that screen then allowing different signing protocols and then give the resulting message. 

I can help with the UI and UX of this. The new metamask GUI is nice, the 'details' page seems like a nice candidate to add more elements, or a button next to details dedicated to signing a message.

**Comment by bdresser** [comment]
@1blockologist thanks, sounds like it relates to https://github.com/MetaMask/metamask-extension/issues/2532, but that describes a pattern initiated by a dapp. 

Could you describe your usecase?

**Comment by 1blockologist** [comment]
My use cases:

- When someone asks me to sign an address to prove ownership, with no further instructions. Then I can sign the address with arbitrary text inside of the wallet, and tell them the address and text I used and the signature so they can verify.

- When a chat bot asks me to verify my address by signing it. The byteball chatbot asked this of bitcoin users for their airdrop, and over 1 billion worth of addresses containing bitcoin signed up for it. Several classic bitcoin wallets like Electrum have the ability in app to sign messages, as it was considered a rudimentary cryptographic principle to expose to the users with their newfangled cryptographic money. In Ethereum world, the Cindicator chat bot verifies ownership to extend access to their chatbot this way too.

It is currently true that very few Ethereum wallets have in-wallet signing. It is fairly low hanging fruit though despite the lack of familiarity with signing amongst people I've talked with. (Many don't know they are signing messages even when dApps prompt them). For people outside of the Ethereum ecosystem, saying "download a convenient wallet by one organization, and then go to this other website that splintered between MyCrypto And MyEtherWallet to sign an address but its cool they're both safe, but only copy the 'sig' key in the key value pair, no quotes" its a little jarring.

**Comment by 1blockologist** [comment]
bump

**Comment by 1blockologist** [comment]
bump

**Comment by bdresser** [comment]
thanks @1blockologist, we're aware of this but likely won't be working on it in the next month or two. 

if you're interested in helping implement to get it done faster, let us know!

**Comment by 1blockologist** [comment]
@bdresser I am interested in helping implement, but my contributions to community projects like this have often been met with unilateral closure of pull requests and arbitrary conditions

Is there a clear framework on contributing to this project?

**Comment by 1blockologist** [comment]
@bdresser  bump

There is no sign message button in metamask

**Comment by 1blockologist** [comment]
2020, the metamask platform offers no ability to sign user generated messages. Users must still go to third party websites and get signatures of different standards.
