### ISSUE TITLE
"Connect Hardware Wallet" not translated when changing languages.

### ISSUE THREAD

**Issue by Kyrrui** [MetaMask/metamask-extension#5019]
**Describe the bug**
"Connect Hardware Wallet" menu option is not translated to regional language.

**To Reproduce**
1. Open Metamask
2. Go to options menu
3. Change language
4. Open options and see option "connect hardware wallet" in english

**Expected behavior**
"Connect Hardware Wallet" should be in each language.

**Screenshots**
<img width="303" alt="screen shot 2018-08-09 at 11 13 10 pm" src="https://user-images.githubusercontent.com/8539426/43937135-dfd21d12-9c29-11e8-9172-68c03161f539.png">

**Browser details (please complete the following information):**
 - OS: windows 10
 - Browser chrome 
 - MetaMask Version  4.9.0
 - New / Beta UI

**Comment by Gudahtt** [comment]
Thanks for the report! This message is correctly localized, but we're missing a lot of translations for it. We're missing translations for many messages unfortunately.

If you'd like to help with translation, it would be greatly appreciated! [There is a transaction guide here](https://github.com/MetaMask/metamask-extension/blob/develop/docs/translating-guide.md); let me know if you have any questions.
