### ISSUE TITLE
Model T not working with web3.eth.sign()

### ISSUE THREAD

**Issue by dconroy** [MetaMask/metamask-extension#5021]
**Describe the bug**
When using hardware wallet, Model T Trezor, I am able to send /receive ether as expected. However, when using a dApp that requires web3.eth.sign(), after clicking the sign transaction button in meta mask, there is never any subsequent popups in chrome or any confirmation prompted on the hardware device.

**To Reproduce**
1. Plug in Model T
2. Unlock with pin
3. Use dapp that requires web3.eth.sign()
4. Sign message in meta mask
5. Expect a  chrome popup or confirmation on device, but never happens

**Expected behavior**
I would expect to confirm this signature action on my device.

**Browser details (please complete the following information):**
 - MacOS High Sierra, 10.13.6: 
 - Chrome Version 68.0.3440.106 (Official Build) (64-bit)
 - MetaMask Version 4.9.0
 - New UI

**Comment by brunobar79** [comment]
Hi @dconroy,  you are right about that method not working with TREZOR via metamask. 
The main reason is that the TREZOR connect API only supports one signing method (See https://github.com/trezor/connect/blob/develop/docs/methods.md#ethereum), which uses personalSign under the hood and this is what most dApps use (for ex. CryptoKitties). 

You can open an issue on the TREZOR connect repo asking them to support it.
I'm closing this but feel free to reopen once TREZOR adds support for it on their end.
