### ISSUE TITLE
"Error: insufficient funds for gas * price + value" when there are sufficient funds

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#5026]
**Describe the bug**
`Error: insufficient funds for gas * price + value` with Raw Transaction when there are sufficient funds

**To Reproduce**

1. open a new html file and make sure you `<script src='https://gitcoin.co/static/onepager/js/tx.js'>` on the page
2. generate a new account with metamask, copy its private key
open up on your console and set

```
var private_key= 'INSERT_KEY_HERE';
var account_address='INSERT_ADDRESS_HERE';
var to='0x0000000000000000000000000000000000000000'
```

3. fund your new account with some ETH (lets say 1 Rinkeby ETH)

4. run the following javascript:

``` javascript
var buffer = 0; //set higher if you want to leave 'eth on the table' as you send it
web3.eth.getTransactionCount(account_address,function(error,result){
    var nonce = result;
    web3.eth.getBalance(account_address,function(error,result){
        var balance = result.toNumber();
        var gas = 21000;
        var gasPrice = 21 * 10**9; //21 gwei, enough for these conditions
        var amount_in_wei = balance - (gas * gasPrice) - buffer;
        var rawTx = {
          nonce: web3.toHex(nonce),
          to: to,
          from: account_address,
          value: amount_in_wei,
          gas: gas,
          gasLimit: gas,
          gasPrice: gasPrice,
        };
        console.log("send amount: ", rawTx['value']);
        var total_gas = rawTx['gas'] * rawTx['gasPrice'];
        console.log("buffer amount: ", buffer);
        console.log("gas total amount: ", total_gas);
        console.log("has enough gas?: ", balance >= (rawTx['value'] + buffer + total_gas));
        var tx = new EthJS.Tx(rawTx);
        var callback = function(error, result){
            console.log(error,result);
        }

        tx.sign(new EthJS.Buffer.Buffer.from(private_key, 'hex'));
        var serializedTx = tx.serialize();
        web3.eth.sendRawTransaction('0x' + serializedTx.toString('hex'), callback, callback);
    });
});


```

**Expected behavior**
`Error: insufficient funds for gas * price + value` error

**Browser details (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome latest
 - MetaMask Version [e.g. 4.9.0] 4.9.0

**Additional context**
Started happening since Metamask wallet upgrade

**Comment by danfinlay** [comment]
Yeah, the string `insufficient funds for gas * price + value` does not appear in our codebase, but it does seem to be in Geth, so it definitely begs the question of what's wrong.

Next time it happens, grab the `sendRawTransaction` request off the background network tab, (`copy as cURL`), and post it in the Infura slack, they are great at debugging weird geth behavior like this.

**Comment by owocki** [comment]
curl to repro 

```
curl 'https://api.infura.io/v1/jsonrpc/rinkeby' -H 'origin: null' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'authority: api.infura.io' -H 'dnt: 1' --data-binary '{"id":1324400226,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86c028504e3b29200825208940000000000000000000000000000000000000000880161b4620d319710801ba05662e3568a5b61d204f012dfefa31e9324384eaad603ff707e77670d8c36c12ea004235d56c0e3e9888034eca236f59bcf93c6267643f32e08e935628666f08ebc"]}' --compressed
```

**Comment by danfinlay** [comment]
We figured this out. Use BNs not JS numbers!

**Comment by owocki** [comment]
@danfinlay  sorry to be a pest, but i do think i found an example that is not related to JS math.. as i am using BigNumber.js (and am sure i’m casting all my variables correctly here)

here is the CURL for it

```
curl 'https://api.infura.io/v1/jsonrpc/mainnet' -H 'origin: null' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'authority: api.infura.io' -H 'dnt: 1' --data-binary '{"id":639345602,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86c8085012a05f20082520894db282cee382244e05dd226c8809d2405b76fbdc988010a149b0e73ec18801ca08ef43d1759278639cef28a1c25bc865efe1427071d9c6b7e0f5b927f6874d237a0091a2ed3f2250943e4696c191e45cb680d6762ad007183e1f595c34917127320"]}' --compressed
```

**Comment by morkeltry** [comment]
Umm.. @danfinlay care to elaborate?
I found [this](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0#user-content-breaking-changes) but seems to concern return values, not values in truffle-config.js

This is probably an issue for the truffle repo (misleading error output?) but if you have the answer, can you let us know?
I'm currently also asking truffle folks, will link to issue there once it's up.
