### ISSUE TITLE
account import from json file not working

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#5029]
Metamask 4.9.2
Ubuntu 16.04 / Linux Mint 18.3

I want to import an account from a json file, but after selecting the json file , the MM window is gone and I can not enter the password for that file

**Comment by SvenMeyer** [comment]
Looks like as if this issue is know since quite a while, but still has not been resolved:

Problems with the popup closing?
We're aware that on some browser-system combinations, the extension popup will collapse on you when trying to select a file. The solution to this problem is to open MetaMask in a full tab. We will make this easier in the future.

On Chrome:

Visit chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html in a new tab.

[https://consensys.zendesk.com/hc/en-us/articles/360004134212-Importing-Accounts](https://consensys.zendesk.com/hc/en-us/articles/360004134212-Importing-Accounts)

**Comment by tmashuang** [comment]
@SvenMeyer try going to chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html

**Comment by bdresser** [comment]
@SvenMeyer but only full screen, still not working in the extension view on 4.9.2 ?

**Comment by whymarrh** [comment]
ping @SvenMeyer any follow-up on this?

**Comment by PierreJeanjacquot** [comment]
Hi,
Do you have any plan to fix this issue?

**Comment by AndrewDonelson** [comment]
Still does not work

**Comment by SvenMeyer** [comment]
yes, you still have to switch to full / expanded screen mode first ...

**Comment by richardsonn09** [comment]
@SvenMeyer 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by sltmunky69** [comment]
> yes, you still have to switch to full / expanded screen mode first ...

This issue still exists as of today on MM for Firefox.
