### ISSUE TITLE
Address / Contact Book

### ISSUE THREAD

**Issue by jeevan-shikaram** [MetaMask/metamask-extension#5030]
# Problem
At the moment, transacting with an "unknown" address will lead to the address being displayed across the application. When this address is shown, the user will have to verify the address manually. If the "unknown" address is an address that is frequently transacted with, the user will be manually verifying it over and over again.

For example when a call is received on a person's mobile phone and the phone number exists in a contacts book, the number is replaced with a name. This way when an incoming call, a text or a voice mail is received, the user sees the name of the person rather than the phone number.

# Proposal
A solution would to have a "add contact" screen where a user will create an entry to which they can register one or multiple addresses to it.

Following this, whenever MetaMask goes to render an address, it is replaced with the name / identifier of the address by looking it up in the contact book.

It might be easiest to start on the transaction screen, so we will use this as an example.

For example, when transferring between two of my own accounts, we see this:
![screen shot 2018-08-10 at 11 01 27 pm](https://user-images.githubusercontent.com/13756536/43959405-10ee6a90-9cf2-11e8-90a4-ae25cce232f8.png)

At the moment, when I interact with a known address, we see this:
![screen shot 2018-08-10 at 11 03 27 pm](https://user-images.githubusercontent.com/13756536/43959424-21bb8f10-9cf2-11e8-9242-b55e243b5335.png)

If this feature was implemented, and the address was associated with a name/Identifier, we would see this:
![screen shot 2018-08-10 at 11 04 45 pm](https://user-images.githubusercontent.com/13756536/43959447-3639240c-9cf2-11e8-80d4-951905898274.png)

If the name/Identifier has multiple accounts associated with it, we could display `My Friend - Account 1 ` or something along the lines.

# Benefits
This will help the user easily confirm that they are transacting with a "known" address, instead of having the burden of manually looking it up every time. This will also make transaction history very clear (for example instead of `transaction to <address>` they see `transaction to <FirstName LastName>`).

**Comment by bdresser** [comment]
thanks @jeevan-shikaram ! this is a good one. 

right now we rely on [this repo](https://github.com/MetaMask/eth-contract-metadata) to maintain a list of known addresses and icons. It's a pretty manual process, and it certainly doesn't include everything, especially personal addresses of friends. 

Long term, it may be simpler to use ENS for communicable addresses, but it'd still be nice to map (an address or ENS domain) to a custom string. Ideally this could sync across devices. 

Relates to https://github.com/MetaMask/metamask-extension/issues/1132

**Comment by bdresser** [comment]
Mural [here](https://app.mural.co/t/consensys3989/m/consensys3989/1551209550952/a29134e95a43a3d4ce65379ec17aafdafac7c238)

**Comment by bdresser** [comment]
live in v7.0.0

**Comment by EGreg** [comment]
Where is it? I used the Address Book and saved many nicknames for addresses, now somehow they are all gone. MetaMask upgrade killed the ability to get them? Can I at least access it somehow in IndexedDB or something?

**Comment by soulston** [comment]
Same here, when I try to send funds to any address I get the prompt: "New address detected! Click here to add to your address book."

I add a nickname but it's never saved?
