### ISSUE TITLE
Check if known nonce is higher than pending tx

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5031]
If users submit tx outside MetaMask it can cause us to lose track of which tx are actually pending, which can affect which transaction we ask the user to reprice / speed up.

As described in https://github.com/MetaMask/metamask-extension/issues/4974#issuecomment-411531728, we can check on pending tx if the account's known nonce has exceeded the pending transaction in metamask and if so transition the status to dropped.

**Comment by rstormsf** [comment]
Bump. 
I just experienced an issue due to stalled pending txs

**Comment by bdresser** [comment]
@rstormsf thanks for the bump

as a fix in the meantime, doing a "reset account" from settings should force the extension to re-sync your nonce.
