### ISSUE TITLE
bug: eth_sign does not validate input

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#5039]
i was seeing the metamask approval window and approving it but not seeing the callback called from the dapp

invocation method:
```js
web3.eth.sign(web3.eth.accounts[0], 'yo', console.log)
```

**Comment by w7788129** [comment]
Go

**Comment by dekz** [comment]
Any update on this? Also seeing the same behaviour in both Chrome and FF, reinstalled down to 4.7.4 and still see this issue.

**Comment by kumavis** [comment]
thanks @dekz - verified that it does call the callback when the signing data is valid + user confirms/cancels

MetaMask should reject the message when the input is invalid
