### ISSUE TITLE
Chrome disabled Metamask and some tokens now missing

### ISSUE THREAD

**Issue by brandysue** [MetaMask/metamask-extension#5043]
FOR USER QUESTIONS, PLEASE DO NOT OPEN A GITHUB ISSUE - IT WILL NOT BE HANDLED HERE.

INSTEAD, PLEASE EMAIL SUPPORT@METAMASK.IO WITH A DESCRIPTION OF YOUR PROBLEM.

**Comment by bdresser** [comment]
@brandysue please email support@metamask.io!
