### ISSUE TITLE
UI improvements around pending transactions

### ISSUE THREAD

**Issue by kingjacob** [MetaMask/metamask-extension#5044]
**Problem**
1)Dropping the pending transaction "---" and replacing it with greyed text (the same color as the confirmed state) makes it more difficult to see from a quick glance if you have pending transactions.

2)"Pending" is also the more accurate phrasing and it's how etherscan describes the state if you click through. Could cause confusion describing the same thing differently.

***Recommendation***
1)At a minimun adding colors to differentiate the states, though the --- to refer to pending was clean. Visually looked like a loading gif.

2)Change the text describing a pending transaction to "pending".

<img width="129" alt="screen shot 2018-08-07 at 11 43 01 am" src="https://user-images.githubusercontent.com/806312/43998101-9655c01a-9da2-11e8-9ab7-d34b5072d083.png"><img width="149" alt="screen shot 2018-08-07 at 11 48 38 am" src="https://user-images.githubusercontent.com/806312/43998102-9674c366-9da2-11e8-8943-0192e92a7143.png">

**Comment by bdresser** [comment]
Thanks for the feedback @kingjacob. We have designs for a re-work of this transaction detail screen - feel free to leave feedback on [the issue](https://github.com/MetaMask/Design/issues/25) if you have any. Should enter development early next week. (@cjeria)
