### ISSUE TITLE
Adding an indication that one has to click in order to raise gas prices.

### ISSUE THREAD

**Issue by kingjacob** [MetaMask/metamask-extension#5045]
There is no indication that one is able to click through in order to raise gas. As seen below.
<img width="297" alt="screen shot 2018-08-11 at 8 28 01 pm" src="https://user-images.githubusercontent.com/806312/43998210-175fef6c-9da5-11e8-83d8-a42f16beaacb.png">

Previous UI did this with an underline. So probably simplest fix.

More broadly, theres ALOT of similiarly _hidden_ links.

**Comment by bdresser** [comment]
Thanks for the feedback @kingjacob - I'll refer you again to our redesign of the tx detail view #4786. @cjeria
