### ISSUE TITLE
The new UX & UI around changing gas is more difficult to navigate

### ISSUE THREAD

**Issue by kingjacob** [MetaMask/metamask-extension#5046]
**Problem**
It's now two step to change gas fees. The expectation on clicking the notice to adjust gas prices is that the next screen will allow one to change gas fees. In the newUI, you have to click once more to edit gas. And you can't see the price in usd when adjusting the price per unit, only after. Making it more difficult to determine if the transaction is expensive because the networks clogged, it's a complicated transaction, or ETHUSD changed.

**Recommendation:**
* change ui from two pages to something more like the oldUI
* if the intent is to keep most users from adjusting from the default, implementing a locked/unlocked UX would serve the same effect while also not making the experience worse for more advanced users.
* you're sending and spending ETH and the USD is a meta description. Making the meta description larger than ETH seems like it should be reversed.

<img width="342" alt="screen shot 2018-08-11 at 8 39 21 pm" src="https://user-images.githubusercontent.com/806312/43998271-c32d6d6e-9da6-11e8-8628-c40c9829269b.png">
<img width="394" alt="screen shot 2018-08-11 at 8 39 48 pm" src="https://user-images.githubusercontent.com/806312/43998272-c349dc1a-9da6-11e8-900c-c307687fdfd6.png">
<img width="705" alt="screen shot 2018-08-11 at 8 39 55 pm" src="https://user-images.githubusercontent.com/806312/43998273-c36d465a-9da6-11e8-9b22-e6b41abae97d.png">

**Comment by bdresser** [comment]
@kingjacob check out our designs for a more robust set of gas tools #4789 

these are actively in development, but any additional feedback is welcome 

@cjeria
