### ISSUE TITLE
Link contract address to a Dapp

### ISSUE THREAD

**Issue by DRYuval** [MetaMask/metamask-extension#5054]
**What problem are you trying to solve?**
Maybe I'm paranoid, but I've always had the fear that my favorite Dapp's server will be hacked, and the hacker will change the frontend code and change the Dapp's contract address.
Such malicous act can make me think I'm invoking some Dapp function, but instead, It'll invoke some other function in an unknown, evil smart contract.

**Describe the solution you'd like**
To mitigate this, I suggest (and have already started implementing) 2 solutions:

1. Adding the option to give a contract address an alias. For example, when you're about the send a transaction, and Metamask prompts you with a confirmation window, it'll show you the contract address as well as the alias you assigned to that contract.
![metamask](https://user-images.githubusercontent.com/31539124/44047710-d97b211e-9f37-11e8-85a0-67ee0d633a6f.jpg)

2. A second possible addition to the first solution, is to link an alias to a specific url, and warn users when they try to invoke other contracts' functions from that url. For example, if Alice linked contract address `0x666` to https://www.cryptokitties.co , and then she tries to invoke a function at contract address `0x123`, Metamask will show a warning.

I'm opening this issue to hear what do you guys think, do you think it's even necessary or maybe I'm just a little overly paranoid.

**Comment by bschorchit** [comment]
Closing as giving alias to contract addresses is now possible with the `Contacts` feature.
