### ISSUE TITLE
USD conversion not always accurate (e.g. OMG token)

### ISSUE THREAD

**Issue by joeytwiddle** [MetaMask/metamask-extension#5062]
**Describe the bug**
I have a few OmiseGO tokens in my wallet. But the USD value displayed below them is inaccurate!

It is displaying 6.14 USD per OMG today, but the real exchange rate today is around 3.39 USD per OMG.

The 6.14 exchange rate _was accurate_ around 31st July, so possibly the exchange which MetaMask uses to grab exchange rates dropped OMG at that time.

**Expected behavior**
With 2 OMG in my wallet, I would expect to see ~6.78 USD displayed below it.
But I am actually seeing ~12.27 USD displayed below it.

**Browser details (please complete the following information):**
 - Using Google Chrome on Mac, MetaMask v4.9.2, Beta UI

**Additional info**
I tried hiding and then re-adding the OMG token (inspired by https://github.com/MetaMask/metamask-extension/issues/2240#issuecomment-333267521) but still see the same values.

**Comment by bdresser** [comment]
Can confirm the GET to `balanc3.metamask.net` is hitting a 400

```
{"statusCode":400,"error":"Bad Request","message":"child \"from\" fails because [required field that must match supported coins. Check at /coins endpoint.]","validation":{"source":"query","keys":["from"]}}
```

**Comment by bdresser** [comment]
This might be an issue with the Balanc3 API we use to pull current token conversions, we're investigating.

**Comment by williamchong007** [comment]
@bdresser How does a token get listed in Balanc3 API? 
Some of my token has USD value on coin market cap/etherscan, but not in metamask

**Comment by danfinlay** [comment]
@williamchong007 can you give examples of which tokens?

**Comment by williamchong007** [comment]
@danfinlay These are the 2 I use mostly

LIKE:
https://etherscan.io/token/0x02f61fd266da6e8b102d4121f5ce7b992640cf98
https://coinmarketcap.com/currencies/likecoin/

MDT:
https://etherscan.io/token/0x814e0908b12a99fecf5bc101bb5d0b8b5cdf7d26
https://coinmarketcap.com/currencies/measurable-data-token/

but even ZRX does not show conversion as of `5.0.2`
https://etherscan.io/token/0xe41d2489571d322189246dafa5ebde1f4699f498
https://coinmarketcap.com/currencies/0x/

**Comment by bdresser** [comment]
According to the balanc3 team, this would be fixed by https://github.com/MetaMask/metamask-extension/pull/5744

**Comment by williamchong007** [comment]
With 5.0.3 I am always getting `No Conversion Rate Available` for all ERC20 tokens now
Is it expected behaviour? @bdresser

**Comment by bdresser** [comment]
Definitely not @williamchong007, I'm seeing the same and filed in https://github.com/MetaMask/metamask-extension/issues/5855. 

Other teammates are having trouble reproducing so it seems like it's not affecting everyone. We'll update on that other thread.

**Comment by sameer300** [comment]
Sir I have some token fund or USD in my metamask wallet and I want to withdraw or transfer this fund into my bank account so plz tell me how can I do this

**Comment by bdresser** [comment]
@sameer300 please email support@metamask.io
