### ISSUE TITLE
Warn user: previous account funds + customizations will be lost if they restore a new mnemonic

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#5065]
Whether previous accounts/account instances should be deleted when restoring from seed is a question which deserves its own thorough discussion. But to combat [restoration-related account loss](https://github.com/MetaMask/metamask-extension/issues/5027#issuecomment-412636715), other and more imminent solutions are needed.

When going to "Restore from seed", let's have a big warning that if the account the user restoring is not the same which is currently used, then funds on the currently saved account and its customizations (accounts added later, tokens added) will be lost. (Yeah, it's not irreversibly lost if they have  a backup of the older seed, but let's play on the safe side.)

This might frighten inexperienced users, but they need to know this. The message could be simplified so that it's understood more widely.

And while we're there, there should also be a warning that even if it's the same account being restored, its customizations (accounts added later, tokens added) will still be lost.

(The first warning *could* be displayed on a selective basis only when it's really a different account being restored. But to achieve that, MM would have to store some form of identifying information about the current account in an unencrypted form. That is really bad for passive plausible deniability, so I advise against it.)

**Comment by leafcutterant** [comment]
I'm glad you like it! I myself have been frustrated by having to spin up a separate browser for each mnemonic account, and this is a corollary. But the comment I linked to above claims to know some novice users who lost funds this way.

**Comment by kevinorin** [comment]
Is this related to the issue I'm having with Brave. I've lost all my deposits to Brave Wallet and restoring with seed key doesn't help. https://community.brave.com/t/issues-with-cryptowallet-crypto-missing/96938/5

**Comment by bschorchit** [comment]
Closing this as we currently already warn the users that added accounts and tokens will be lost. 
We also have [this PR](https://github.com/MetaMask/metamask-extension/pull/13493) in progress that improves this message and we a [new flow](https://www.notion.so/Make-the-forgot-password-flow-more-compassionate-and-add-recoverability-c92708c4fbe743659a04ff68960afd8e) lined up that addresses all feedback above 😊
