### ISSUE TITLE
Price discrepancies

### ISSUE THREAD

**Issue by dwolfgram** [MetaMask/metamask-extension#5070]
**Describe the bug**
OMG is currently priced at $3.69 at Tuesday Aug 14 10:17PM EST, but on metamask is priced at ~$7

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
<img width="897" alt="screen shot 2018-08-14 at 10 07 21 pm" src="https://user-images.githubusercontent.com/33427321/44128239-e69d83ae-a00f-11e8-9125-f1fc7cc54a45.png">
<img width="928" alt="screen shot 2018-08-14 at 10 18 16 pm" src="https://user-images.githubusercontent.com/33427321/44128250-002e7986-a010-11e8-85ee-40f261c27ece.png">

**Browser details (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI? - new

**Additional context**

**Comment by bdresser** [comment]
duplicates #5062
