### ISSUE TITLE
Password doesnt work and seed phrase wont reset wallet

### ISSUE THREAD

**Issue by mandrews72** [MetaMask/metamask-extension#5071]
i went to open Meta Mask on my Dell lap top as normal and i've been told the password is invalid, which it isn't as i opened it a few days ago.

I have subsequently reset it with my seed phrase but the wallets are empty and when i go to load some of the coins the balance is zero. I have tried the "create account" and now have 3 accounts that are empty.

I can see my coins on etherscan but wont reload in meta mask

help please

**Comment by bdresser** [comment]
Hi @mandrews72, sorry to hear about your trouble. You should reach out to support@metamask.io and they'll walk you through a couple steps that might help solve your problem. Best of luck~

**Comment by martineezz** [comment]
@mandrews72 If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
