### ISSUE TITLE
Resubmitting transaction should be worded clearer and better highlighted

### ISSUE THREAD

**Issue by Cygnusfear** [MetaMask/metamask-extension#5075]
**What problem are you trying to solve?**
Currently transactions that are not processed hold up all future transactions, the offending transaction is marked by Metamask with a small blue subtext saying 'Taking too long? Retry with a higher gas price here'. However, as much as I'd not consider myself fully stupid, the wording of this subtext is vague enough that I had no idea this was how I could resubmit the transaction.

**Describe the solution you'd like**
Replace the text with 'Click here to resubmit your transaction with a higher gas price'. Alternatively:
'Click here to increase the gas price for speeding up your transaction'

**Additional comments**
If future transactions are being blocked by that one transaction, this should be made apparent to the user; novice users may probably not be aware that their transactions are being blocked and will resubmit new transactions which does not help. Suggested solutions:
- Grey out new transactions making it clearer what the last 'active' transaction is and thus highlighting the increase gas feature
- Notify the user in a new transaction screen that there is a transaction pending that may block any further transactions

Issue described above may cost unknowing users money due to their Metamask seemingly being 'broken':
https://www.reddit.com/r/ethtrader/comments/975ybz/daily_general_discussion_august_14_2018/e45viqx/

**Comment by Cygnusfear** [comment]
Additionally: Showing the offending transaction at the top of the transaction list might help make the user more aware of the transaction blocking all other transactions.

**Comment by bdresser** [comment]
@Cygnusfear check out our designs for a new transaction detail view - it's ordered with pending tx first, like you suggest, and changes the way we suggest users speed up pending tx: #4786

**Comment by Cygnusfear** [comment]
That looks great! Only suggestions I could think of is a warning if a transaction suddenly takes extremely long (pending label could be colored red) due to a spontaneous increase in network usage. I'll head over to the design corner and start rummaging around there!

**Comment by bdresser** [comment]
Sounds good. Closing this, thanks for the feedback.
