### ISSUE TITLE
unblock myetpwallet.com

### ISSUE THREAD

**Issue by baaa** [MetaMask/metamask-extension#5080]
**Describe the bug**
metamask is blocking myetpwallet.com, which is a (the) web wallet for Metaverse (ETP) project, and has no relation to Ethereum or its forks, except the usage of dagger hashimoto algorithm

**To Reproduce**
1. https://www.myetpwallet.com/
2. See The website is blocked

**Expected behavior**
https://www.myetpwallet.com/ should not be blocked, 

**Screenshots**

**Browser details (please complete the following information):**
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI?

**Additional context**

**Comment by bdresser** [comment]
@baaa please open a PR or issue on our [eth-phishing-detect repo](https://github.com/MetaMask/eth-phishing-detect/)
