### ISSUE TITLE
Issues resolving .eth domains

### ISSUE THREAD

**Issue by whyrusleeping** [MetaMask/metamask-extension#5092]
**Describe the bug**
Loading .eth domains appears to only work sometimes

**To Reproduce**
Install foxy ether extension
go to phyrextsai.eth
say "oh cool, that worked"
do it again
say "aw, why didnt that work?"
 
**Expected behavior**
Expected page to load

**Screenshots**
sad browser
<img width="832" alt="screen shot 2018-08-17 at 8 18 42 pm" src="https://user-images.githubusercontent.com/1243164/44295285-cb844600-a25a-11e8-83b2-0a900abf044a.png">

**Browser details (please complete the following information):**
 - OS: apple os
 - Browser: flamey fox 62.0b16
 - MetaMask Version: A new one? 4.9.2
 - Old UI or New / Beta UI? no idea

**Additional context**
Appears to work correctly the first time around, then fail afterwards. Smells like caching.

**Comment by MikeCheng1208** [comment]
@whyrusleeping Do you use the "mainnet" or other network of Ethereum provider?
I think ENS resolve function now only support on "mainnet" or "ropsten"

**Comment by bdresser** [comment]
@whyrusleeping can we get more reliable repro steps? works for me regularly

**Comment by whyrusleeping** [comment]
@bdresser It seems like its working consistently now. Thanks to whoever fixed it :)
