### ISSUE TITLE
MetaMask not connecting to local Parity node

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#5098]
**Describe the bug**
When I select Localhost 8545 in my network dropdown, MetaMask shows the message `Connecting to Unknown Private Network...` and never completes the connection to my fully-synced local Parity node. This is happening on both the old UI and the new UI, in both up-to-date Firefox and Chromium.

**To Reproduce**
1. Open MetaMask
2. Open Parity, let it fully sync
3. Select Localhost 8545 in MetaMask dropdown
4. See `Connecting to Unknown Private Network...` message and notice that it does not finish connecting.

**Expected behavior**
I expect MetaMask to connect to Parity node and allow me to continue using MetaMask while connected to Parity.

**Screenshots**

![metaparity](https://user-images.githubusercontent.com/9424721/44313511-00a9a900-a3bf-11e8-837b-b2d53930ffb1.png)

**Browser details (please complete the following information):**
 - OS: Linux Mint 18.3 64-bit
 - Browser: Firefox and Chromium
 - MetaMask Version: 4.9.3
 - Old UI or New / Beta UI? Both

**Additional context**
Trying to connect to Parity UI full node Parity-Ethereum v2.0.1-20180726 beta

**Comment by tmashuang** [comment]
What port is Parity open as?

**Comment by john-light** [comment]
@tmashuang not sure, I haven't changed any settings in the node. I am just following the instructions MetaMask published here: https://consensys.zendesk.com/hc/en-us/articles/360004060451-Using-a-Local-Node

**Comment by tmashuang** [comment]
The article described focuses on Geth, and could be outdated. From what I see, Parity uses a default port of http://localhost:8180. Try switching back to one of the default networks, select Custom RPC from the dropdown network menu, and enter http://localhost:8180 in the Custom RPC URL field.

**Comment by john-light** [comment]
Thank you for the suggestion @tmashuang. After trying with localhost:8180 MetaMask still shows the error: `Connecting to Unknown Network` until I change it back to mainnet or testnet.

**Comment by tmashuang** [comment]
Try using the IP instead of localhost, the one specifically in the url that Parity opens as. If the issue persists, provide background logs, and the network tab, to see what kinds of errors might be coming from the server.

**Comment by john-light** [comment]
> Try using the IP instead of localhost, the one specifically in the url that Parity opens as.

I do not understand what you mean or know how to do this.

>  provide background logs, and the network tab, to see what kinds of errors might be coming from the server.

Where do I find the background logs and network tab?

**Comment by mannutech** [comment]
@john-light I have got it working at my end by starting the parity node as below :
`parity --chain=ropsten --jsonrpc-cors="all" --jsonrpc-apis="all" --jsonrpc-interface=all`
I am sure this won't be a recommended way of starting the node, but you can get started atleast

**Comment by Tbaut** [comment]
Hi guys, Thibaut from Parity.
@mannutech is opening a little bit too much the node so that it's not secure, but the idea goes in the right direction. Since Parity only allows local HTTP RPC per default, you need to specifically whitelist the domain used by Metamask using the flag `jsonrpc-cors`. The domain used can be figured out by opening Metamask in a new tab (top right icon in the beta version). You will find the domain in the address bar. I have it working on Firefox using `parity --chain kovan --jsonrpc-cors moz-extension://ae62fc16-c916-4c24-9a36-97f5a850f25c`

**Comment by john-light** [comment]
I have MetaMask connected to local Parity node following @Tbaut instructions. Thanks everyone for your help!

**Comment by saeedjaafari** [comment]
i have the same problem
localhost:8545 in windows
but not connect to network

info in terminal : ganache-cli -v
127.0.0.1:8545
with SID info
but to connect ganache to metamask at first metamask have to connect to local network but dosnt work !!

how can i solved it /?
with thx
