### ISSUE TITLE
Sorry, we are unable to locate this Transaction Hash

### ISSUE THREAD

**Issue by XYOGeorge** [MetaMask/metamask-extension#5105]
**Describe the bug**
I am trying to deposit funds from my MetaMask to IDEX and although IDEX says the request mas been made AND MetaMask is showing the request, enough Gwei has been offered, and sufficiend funds are in the account, the transaction details cannot be found on Etherscan and the transaction never completes..  This has been for the past two days

**To Reproduce**

**Expected behavior**
Completion of transaction

**Screenshots**
![2018-08-20](https://user-images.githubusercontent.com/42548267/44353371-a3852480-a49e-11e8-8e3f-f25bf0e6886c.png)
![2018-08-20 1](https://user-images.githubusercontent.com/42548267/44353372-a3852480-a49e-11e8-8b38-5a2467faaad8.png)

**Browser details (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [Chrome]
 - MetaMask Version [4.9.3]
 - Old UI or New / Beta UI? Old UI

**Additional context**

**Comment by bdresser** [comment]
@XYOGeorge it's possible your transactions are blocked by an earlier pending transaction. 

If you scroll down in your transaction list, do you see a link that says "Taking too long? Retry your transaction with higher gas" ? Later transactions (with higher nonce) won't be able to process until the pending transaction with lowest nonce lands.

**Comment by XYOGeorge** [comment]
Yes..  I see it.. thank you..  However, I have tried to cancel the transaction by clicking the link that brings up the new transaction then clicking REJECT, but it keeps coming back.

Can you suggest anything?

**Comment by XYOGeorge** [comment]
![2018-08-20](https://user-images.githubusercontent.com/42548267/44367844-d5ab7c00-a4c8-11e8-83a9-4acde82c8ba4.png)

**Comment by XYOGeorge** [comment]
Thanks for your assistance..
I played tennis with a bit of funds, biting the bullet on the fees, until all the outstanding transactions had depleted ..  I then deleted and reinstalled the plugin.
All is working fine now.

THANKS AGAIN
