### ISSUE TITLE
Strange Metamask Behavior When I Enter "test" in the Address Bar

### ISSUE THREAD

**Issue by ZitRos** [MetaMask/metamask-extension#5131]
Check this screen recording out:

![2018-08-23_17-10-23](https://user-images.githubusercontent.com/4989256/44530672-a75fb380-a6f7-11e8-8f59-535b47c36db8.gif)

When I enter "test" in the address bar and press enter, I get a Google search and almost immediately this page is redirected to Metamask's **404 not found powered by [portal network](https://www.portal.network/)** page.

I suppose some testing code appeared in production Metamask, which is very, very unwanted. This issue was tested on 2 PCs with Chrome browser just now.

P.S. I appreciate your work on Metamask! Thanks!

**Comment by whymarrh** [comment]
This might be a duplicate of #5063

**Comment by ZitRos** [comment]
@whymarrh, it is. Thank you!
