### ISSUE TITLE
Metamask added but the fox does not appear on my chrome bar

### ISSUE THREAD

**Issue by steveireton** [MetaMask/metamask-extension#5132]
FOR USER QUESTIONS, PLEASE DO NOT OPEN A GITHUB ISSUE - IT WILL NOT BE HANDLED HERE.

INSTEAD, PLEASE EMAIL SUPPORT@METAMASK.IO WITH A DESCRIPTION OF YOUR PROBLEM.

**Comment by bdresser** [comment]
hey @steveireton - as the template says, you should email support@metamask.io :)

(that said - head to `chrome://extensions` and make sure MetaMask is enabled)
