### ISSUE TITLE
"Connecting" spinner blocks onboarding

### ISSUE THREAD

**Issue by RusVakhitov** [MetaMask/metamask-extension#5143]
Hello. I have a problem. The wallet does not start. The browser has ads blockers. When I turn them off and restart. The wallet does not work. I attach screenshot. Waiting for an answer. Thank you in advance
https://s20.postimg.cc/9wd2yjc9p/image.jpg

**Comment by kwaazaar** [comment]
Same here. It says "Connecting to main network", but fails to connect. I'm not aware of an outage at infura.

**Comment by dpdanpittman** [comment]
I'm having the same issue. Please fix ASAP my dApp relies on it.  [www.qwoyn.io](https://www.qwoyn.io)

**Comment by kwaazaar** [comment]
Reinstallation fixed it for me. I also choose not to install the new version.

**Comment by whymarrh** [comment]
Hey @kwaazaar @dpdanpittman we've updated the network timeout logic (as of a few releases ago). Please open up a new issue if you're still having similar issues with the latest version of MetaMask.
