### ISSUE TITLE
Transfer ERC721 token

### ISSUE THREAD

**Issue by sevriugin** [MetaMask/metamask-extension#5145]
**What problem are you trying to solve?**
We have ERC721 token than we are using in crowdsurance project. Before token activation it can be transfer to another user / account. The new version  of Metamask supports ERC20 token transfer but did not recognise the difference between two types of token. We can add ERC721 token to the address and we can try to send it to other address but the transaction will fail because ERC721 transfer expect as the second argument not a token amount but unique NFT ID. 

**Describe the solution you'd like**
It will be great for Metamask to recognise ERC721 token and support a transfer of this type of tokens. 

**Additional context**
Here it is an example how it looks now when we transfer one ERC721 token to another account using our Dapp. You can see that Matamask consider this transaction with token amount equal to NFT ID.
<img width="1358" alt="screen shot 2018-08-26 at 12 21 16" src="https://user-images.githubusercontent.com/5311893/44632416-81961100-a97a-11e8-89b8-498f32c0139f.png"> and it is not possible to enter this type transaction in Metamask directly because the number of LCST token is 1 and Metamask is now allowing to enter in the amount field value that is more then 1

**Comment by sevriugin** [comment]
By the way if you try to enter in the amount field 1 the the transaction will be confirmed but will fail later. 
<img width="364" alt="screen shot 2018-08-26 at 12 17 36" src="https://user-images.githubusercontent.com/5311893/44632461-1f89db80-a97b-11e8-8a32-166e1c06787c.png">
https://rinkeby.etherscan.io/tx/0xecd6f195d76161263ac8d9b2cea893f6b1ea91748fa87e82f43eb66ad3012d03

**Comment by taylor-cz** [comment]
I can second to this. It would be valuable of Metamask knew how to transfer ERC-721 non fungible tokens.

**Comment by eyemine** [comment]
I concur, it would be invaluable

**Comment by bdresser** [comment]
Thanks all, we're eager to get started on this but are waiting until we've migrated some of our backend controllers to a simpler shared module. See https://github.com/MetaMask/metamask-extension/issues/5806 for more details, we'll update here when work starts!

**Comment by nfurfaro** [comment]
Hey there. Any progress on this front? I've been trying to use metamask to view/move NFT's  (erc721) with only partial success. I can see that it's not possible to send NFT's yet, but I can sort of view them By this I mean that I can add my NFT as a custom token and see that I have 1 of them. If I then transfer it to another metamask account, both the sending and recieving accounts now show my balance as being 1.

**Comment by bdresser** [comment]
still working on it @nfurfaro, hang tight. given our design bandwidth and some backend changes, rough ETA ~3 weeks

**Comment by denniswell** [comment]
Hey there! Any updates here? Would really be an invaluable feature....

**Comment by supertyler** [comment]
Seconded - any updates?  Trying to get ENS addresses into metamask in token form...

**Comment by mikemixell** [comment]
Hi! Also working on a project considering using ERC-721. Is there an estimate when you tackle this?

**Comment by Thread7** [comment]
I would also like to see this feature. It would really be a boost to the NFT community!

**Comment by danfinlay** [comment]
I'll note that there is also a new NFT standard that would be good to support also: https://github.com/MetaMask/metamask-extension/issues/5887

**Comment by julien51** [comment]
We would love to see this happen as well as we've seen several people trying to transfer their Unlock membershp tokens using MetaMask. See for example this transaction https://etherscan.io/tx/0x901df122a0b64c9b82ed3d90bf3baacfadbdddb8223f05ae518112dce0ab2bae

**Comment by Cryptojim7** [comment]
Opps, I just transferred some ERC721 tokens to my metamask brave extension.  I was planning on transferring one of them to another wallet/.  Am I screwed now?

**Comment by eyemine** [comment]
no you are fine. you have transferred them to an Ethereum address they are safe
if you explore metamask extension you will see that you have the option to export the private key
of this ethereum address(public key)
one way it resolve your problem to go to opensea.io NFT  marketplace sign in with the wallet holding the NFTs and select the load my items from the opensea account dropdown
you will see your NFts listed, you may gift them to another ethereum address or sell them, it will cost some gas,

**Comment by folktale42** [comment]
Still not able to transfer NFTs. Any updates on this?

**Comment by DenhamPreen** [comment]
+1 request

**Comment by jacobcantele** [comment]
this work has taken longer than originally expected because of some dependencies. sorry about that. you can certainly still transfer/view them either from MetaMask Mobile or by going to a dapp like Rarible or OpenSea. @folktale42

**Comment by Jovonni** [comment]
Is there any development work we can do ahead of time to prepare for this change? web specifically

**Comment by deliprof** [comment]
This is very important issue and seems to becoming urgent for many NFT owners and projects. Is there any estimated time for update? Thanks.

**Comment by quaekr** [comment]
Any update on this?

**Comment by pemulis** [comment]
I'm also curious if there are any updates on this issue.

**Comment by adonesky1** [comment]
This will be released on extension very soon.
