### ISSUE TITLE
Switching accounts on signing popup doesn't work

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-extension#5149]
**Describe the bug**
If you try to sign a message with account 1, and then switch to account 2 in the same signing popup,
the message gets signed with account 1 instead of 2

**To Reproduce**
1. Make sure you have at least 2 accounts on metamask
2. Go to https://danfinlay.github.io/js-eth-personal-sign-examples/
3. Tap on any of the buttons
4. Switch accounts inside the signing popup
5. Sign the message

If you look at the console you'll see that the signature was recovered with the original account and not the one you switched after.

**Expected behavior**
The message should be signed with the account that you selected in the popup.

**Screenshots**
![bug](https://user-images.githubusercontent.com/1247834/44679828-fd8b6a00-aa09-11e8-9d84-5e48d3a236c3.gif)

**Browser details (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Chrome
 - MetaMask Version 4.9.3
 - New UI

**Comment by danfinlay** [comment]
I don’t think we meant to allow users to change the signing on this screen, since it breaks a Ðapp expectation. Maybe we can later by providing a mutable method like sendMutableTransaction:

https://github.com/MetaMask/metamask-extension/issues/4260

**Comment by whymarrh** [comment]
This should be fixed as of #6024
