### ISSUE TITLE
Selecting Import using account seed phrase provides unexpected result / flow on Chrome

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#5150]
**Describe the bug**
When clicking "Import using account seed phrase", the result is the same login/password prompt page loads in full tab.  The person then has to select the same "Import using account seed phrase" link again in order to get to the "Restore your Account with Seed Phrase" page.  This issue does not occur on firefox, it appears to be Chrome only, because Chrome opens a new tab, closing the MetaMask extension.

**To Reproduce**
1. Go to MetaMask extension (v4.9 or newer, which is only avail. on Chrome and Firefox atm)
2. Click on 'Import using account seed phrase'
3. Click on 'Import using account seed phrase' again

**Expected behavior**
User has to click Import using account seed phrase twice.

**Browser details (please complete the following information):**
 - OS: OS agnostic
 - Browser: Chrome
 - MetaMask Version: [4.9+]
 - New UI, this function still works in old UI on 4.9+

**Comment by tmashuang** [comment]
This seems to have been fixed. Closing.
