### ISSUE TITLE
metamask ha desaparecido de mi extension en crohme

### ISSUE THREAD

**Issue by guannay** [MetaMask/metamask-extension#5153]
Si intento reinstalarlo me dice que ya esta añadido y que esta inhabilitado. Pulso la tecla para volver a habilitar y no se vuelve a habilitar. Mi navegador es crohme. Indiquenme como puedo recuperar la extension  o como puedo solucionar el problema y tener acceso a mis tokens. Gracias.

**Comment by bdresser** [comment]
hey @guannay - please reach out to support@metamask.io and they'll be able to help you re-install and log in
