### ISSUE TITLE
metamask DAI numbers are wrong (and null on the confirmation page)

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#5161]
**Describe the bug**
metamask DAI numbers are wrong (and null on the confirmation page)

![screencast](https://user-images.githubusercontent.com/513929/44811464-c0a6ab00-aba2-11e8-9b80-2d7dcf3535a4.gif)

**To Reproduce**
1. Go to Metamask
2. Click on 'click on DAI
3. try to send some DAI
4. on confirmation page, the numbers are all off, and there is a null symbol

**Expected behavior**
confirmation page shows correct details

**Screenshots**
[screencast](http://bits.owocki.com/ddf4a60e2c67/Screen%20Recording%202018-08-29%20at%2003.41%20PM.gif)

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser [e.g. chrome, safari] Chrome  Version 68.0.3440.106 (Official Build) (64-bit)
 - MetaMask Version 4.9.3

 - Old UI or New / Beta UI? Beta UI

**Comment by owocki** [comment]
looks like related to eth-contract registry call?

```curl 'https://mainnet.infura.io/eth-contract-registry' -H 'origin: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'content-type: application/json' -H 'accept: */*' -H 'authority: mainnet.infura.io' -H 'dnt: 1' --data-binary '{"id":8863445484838,"jsonrpc":"2.0","params":[{"to":"0x44691B39d1a75dC4E0A0346CBB15E310e6ED1E86","data":"0xb46bcdaaa9059cbb00000000000000000000000000000000000000000000000000000000"},"latest"],"method":"eth_call"}' --compressed```

[screencast](http://bits.owocki.com/eaa343387e18/Screen%20Recording%202018-08-29%20at%2003.50%20PM.gif)

**Comment by owocki** [comment]
hmm it happens on my chrome canary also (totally independent metamask install, which also already had DAI installed)

**Comment by bdresser** [comment]
@owocki this should be fixed by https://github.com/MetaMask/metamask-extension/pull/5121 in develop
