### ISSUE TITLE
Metamask internally increments nonce even though MEW states it differently

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#5166]
1. Have a pending tx in metamask
2. Go to MEW and sign in with metamask
3. Generate a tx, MEW would show you the `nonce field`:
![image](https://user-images.githubusercontent.com/9360827/44820053-1d569580-aba4-11e8-9265-4401e0608b58.png)

Because MEW relies on `getTransactionCount` method and correctly inserts it.

However, metamask disregards such information and increments it.

There has to be some consensus about nonce field. OR let the user submit it

**Comment by bdresser** [comment]
hey @rstormsf - check out https://github.com/MetaMask/metamask-extension/issues/1410 for a lengthy discussion of why our nonce logic increments automatically and a couple coming changes that may help mitigate the issues this can cause. 

Closing this for now as a duplicate, let me know if you'd like to re-open for a specific reason.
