### ISSUE TITLE
Connecting to Unknown Network - can't stop it

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#5169]
Whenever MetaMask has a problem to connect to a (local) node, it just display the spinning circle and there is no way to stop it or choose another network, IP or port.

**Comment by bdresser** [comment]
You can navigate away from the spinner screen by clicking the small spinner in the top-right and selecting a different network. This isn't ideal UX and we're working on a better solution in https://github.com/MetaMask/metamask-extension/issues/3776

**Comment by AlexanderPoschenrieder** [comment]
In my case, there is no  small spinner in the top-right when you are just logging it. So i can't stop it.

**Comment by bdresser** [comment]
@AlexanderPoschenrieder this will be fixed by https://github.com/MetaMask/metamask-extension/pull/5893 in our next release, maybe later today or tomorrow!

**Comment by chfast** [comment]
@AlexanderPoschenrieder I had the same. 
Workaround:
Go to chrome://extensions, disable and enable Metamask.
The magic "small spinner" will appear.
