### ISSUE TITLE
MetaMask forgets custom network setup

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#5170]
I do quite some testing with truffle develop which is running on port 9545 by default. As this network is not in the standard list of networks, I have to add it everytime. Everytime, because even after just switching to another network, the entry is gone.

Also , it would be a good idea to have some visual feedback when setting up a new network and it worked. At the moment there is a [save] button, no no indication once pressed if that entry was accepted, stored or even connected.

**Comment by bdresser** [comment]
this was handled in https://github.com/MetaMask/metamask-extension/pull/5096 and will be out in our next release
