### ISSUE TITLE
Bring popup to front when new transaction is added

### ISSUE THREAD

**Issue by digitaldonkey** [MetaMask/metamask-extension#5171]
When I request a signature as a dapp dev normally a popup shows up asking th user for his signature.
In case the popup is all ready open, the counter at the extension will increment, but the popup hidden in the background want focus. 

This creates a very inconsistent user experience, as sometimes there is a popup and sometimes there seem to be no popup (brcause it's hidden in the background). 

**To Reproduce**
1. request a signature from dapp (popup shows up)
2. ignore it by clicking back into your browser dapp window
3. request a signature from dapp like in 1.
4. See that no popup appears

**Expected behavior**
the popup should come to front by calling focus() on the (previously opened) window.

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - MetaMask 4.9.3
 - Old&new UI

**Comment by div-production** [comment]
Is there any way to make Metamask popup modal? i.e. don't hide popup when user clicks outside?
