### ISSUE TITLE
Nothing happens on posting ETHEREUM_PROVIDER_REQUEST message

### ISSUE THREAD

**Issue by tarekskr** [MetaMask/metamask-extension#5178]
** **MetaMask Version: 4.9.3**
** **Browser: Chrome version 68.0.3440.106**

I am using the code provided in @bitpshr [article](https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8) to post an `ETHEREUM_PROVIDER_REQUEST` message, but absolutely nothing happens when I post it. MetaMask does not show any popups, nor does the listening event `data.type` is ever equal to `ETHEREUM_PROVIDER_SUCCESS`.

Here is the code used:

```
window.addEventListener('load', () => {
        // Listen for provider injection
        window.addEventListener('message', ({ data }) => {
            if (data && data.type && data.type === 'ETHEREUM_PROVIDER_SUCCESS') {
                // Use injected provider, start dapp...
                web3 = new Web3(ethereum);
            }
        });
        // Request provider
        window.postMessage({ type: 'ETHEREUM_PROVIDER_REQUEST' }, '*');
});
```

**Comment by bitpshr** [comment]
Hi @tarekskr. As mentioned in the article, we don't plan to release these breaking changes until November 2nd, 2018. The exact API may change slightly before that time, and if it does, we'll be sure to update the community via a follow-up blog post.

If you have any additional questions, please let us know. Thanks!

**Comment by tarekskr** [comment]
Oh I completely misunderstood, I thought the breaking change will happen on November 2nd. Thanks a lot for the clarification.
