### ISSUE TITLE
Display issue with french translation

### ISSUE THREAD

**Issue by valnuro** [MetaMask/metamask-extension#5181]
**Describe the bug**
There is a display issue with the french translation on the link to ethersan.io

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Details', not sure about the english word used
3. Look at 'Show on etherscan', same don't know the english translation used, in french it's 'Afficher le compte sur etherscan'
4. So the translation 'Afficher le compte sur etherscan' goes beyond the frame.

**Expected behavior**
If you can't reduce the size of the text you may use those translations.

- 'Voir sur etherscan'
- 'Voir le compte sur etherscan' (I think this one won't resolve the display issue)
- 'Afficher sur etherscan'

**Screenshots**

![issuemetamask](https://user-images.githubusercontent.com/31988506/44902263-cc60b180-ad09-11e8-9677-2da2864880a9.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - MetaMask 4.9.2
 - Beta UI

**Additional context**
Same issue on extension page

**Comment by Bunjin** [comment]
Thanks for the report!
It seems this was fixed in the current versions of MetaMask. Please reopen the issue if you still experience the issue

![image](https://user-images.githubusercontent.com/11554098/50693816-6201aa00-1038-11e9-9e47-6453dd3a555e.png)
