### ISSUE TITLE
another wallet

### ISSUE THREAD

**Issue by Leowal** [MetaMask/metamask-extension#5184]
hello....do is possible to install another new wallet MetaMask....?  how  ?      **What problem are you trying to solve?**
A short description of what you're trying to do. E.g., "My users need to wrap ETH, but they're intimidated by the confirm screen..." or "I'm trying to debug my application, and XYZ..."

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Try to also include any alternative solutions you've considered.

**Additional context**

**Comment by bdresser** [comment]
@Leowal I'm not sure I understand your question. You can add new accounts to your MetaMask extension in the top-right menu, and you can always uninstall and re-install your extension if you'd like to create an entirely new wallet.

For further questions, please reach out to support@metamask.io

**Comment by Leowal** [comment]
Perfect....!    Thank you


Inviato da Yahoo Mail per iPad


Il martedì, settembre 4, 2018, 8:33 PM, bobby dresser <notifications@github.com> ha scritto:


@Leowal I'm not sure I understand your question. You can add new accounts to your MetaMask extension in the top-right menu, and you can always uninstall and re-install your extension if you'd like to create an entirely new wallet.

For further questions, please reach out to support@metamask.io
