### ISSUE TITLE
Metamask getAccounts() not returning if user is not logged in

### ISSUE THREAD

**Issue by roschler** [MetaMask/metamask-extension#5185]
In the past I was able to use the _getAccounts()_ method to "test" if the user was logged in to the Metamask extension for Chrome.  As of late, this doesn't work anymore.  In the past, the _getAccounts()_ method would return an empty list of accounts if the user was not logged in to Metamask.  Now, that method never returns (i.e. - the "then" block attached to the _getAccounts()_ method is never execute or entered.)

- Make sure you are not logged into Metamask.
- Make a _web3.eth.getAccounts()_ call from the browser code with a breakpoint on the first line of code in the "then" block attached to that call.
- Note that the breakpoint is never hit.

```js
			localWeb3.eth.getAccounts()
			.then(function (result)
			{
                                // If the user is not logged into Metamask, the breakpoint on the line below is never hit.
				aryAccounts = result;
```

Browser details:

Version 68.0.3440.106 (Official Build) (64-bit) running on Linux Ubuntu 18.04 (Bionic Beaver).

**Comment by fredbuluku** [comment]
> the problem is metamask is not accessible 

> git rectify the problem to let me login

**Comment by fredbuluku** [comment]
I have had un issue logging in their site,and I suspect they are the ones taking away my funds because I have lost a lot in MyEtherWallet even through that incident I acted in hunger,only to find that I was moving to store my funds where people are crying more than I do.Thanks a lot.

**Comment by fredbuluku** [comment]
> git disconnect the attachment of the following wallets from my operations of crypto currency 

> git the wallets are as follows Metamask.io,Status,Everest,Everex exchange 

> git I suspect one of them is interfering and stealing funds from MyEtherWallet

> git suspend their operations

**Comment by bdresser** [comment]
@roschler not aware of any change in the past couple weeks that would have caused this. @tmashuang can you take a look?

Also, we're going to be deprecating automatic web3 injection in early November, so you may need to reconsider this method of detecting whether a user is logged in. Check out [the EIP](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md) for the technical specification or [this Medium post](https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8) for our rationale. (cc @bitpshr)

**Comment by roschler** [comment]
@bdresser Thanks.

**Comment by uneeb123** [comment]
This still works for me. But I have a different question. Do you have any ideas around how can I detect if the account has been changed without querying `web3.eth.getAccounts()` each time? I need this because a user might switch accounts. Alternatively, metamask can display all accounts.

**Comment by roschler** [comment]
@bdresser I'm using 4.11.1 and it happened a few days ago.

This is just a hunch but my gut feeling is that it has something to do with the active tab and window focus.  My guess is that Metamask does some kind of check to see if it is OK to obtain input focus and to activate it's window client area.  If not, it resorts to accumulating pending transactions

I have a vague memory of something similar happening a month or so ago when I was switching between a lot of tabs.  If you get more reports on this, it might be useful to add a new debug pane to the pop-menu that shows the status of the elements that Metamask uses to make its decision to not to pop-up and to queue transactions instead.  Then we could help you debug this better.  Probably a good idea to have a "reset" button to reset whatever flags Metamask sets/uses to make that decision.  Just my two cents (two Eth).

**Comment by whymarrh** [comment]
Let us know if you're still seeing this issue with the latest version of MetaMask and we can re-open and re-investigate
