### ISSUE TITLE
Expose currency converter code via Web3 object?

### ISSUE THREAD

**Issue by roschler** [MetaMask/metamask-extension#5186]
Metamask obviously does currency conversion, at least for ETH TO USD.  The amount specified by the developer via JS in the Web3 call that triggers the pop-up shows as USD.  Are there any plans to expose that currency conversion code via the Web3 object?  That would be a great help to those of us that are making games that have entry fees, so we could allow the user to enter the fee in their native currency instead of currently asking them to enter it in Ether.

**Comment by Robbiekruszynski** [comment]
Hi @roschler 
I hope the game development is going well! Wanted to let you know this ticket is not forgotten but we have migrated our feature requests + community support over to [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas. Please feel free to have a look around and make a post there!

Going to close this ticket
