### ISSUE TITLE
v4.9.3 not uploaded to addons.mozilla.org

### ISSUE THREAD

**Issue by enolan** [MetaMask/metamask-extension#5193]
**The official Firefox addons site is still listing 4.9.2**
[Here's](https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/) the Firefox page, with 4.9.2. The Chrome web store has 4.9.3.

**To Reproduce**
1. Go to the the a.m.o link above
2. Look at the version number under "More information"

**Expected behavior**
Should be 4.9.3

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - MetaMask Version: N/A
 - Old UI or New / Beta UI: N/A

**Comment by dsilberschmidt** [comment]
At the moment metamask is not working on firefox, while it does on chrome. Perhaps enolan 's suggested update would fix the issue.

**Comment by bdresser** [comment]
4.9.3 exceeded the size limit allowed for Firefox addons, so we're working on pruning our dependency graph for this next release. Hang tight!

**Comment by leroldary** [comment]
@bdresser any news? Would be great if MetaMask 4.12.0 would be available on firefox.

**Comment by bdresser** [comment]
We're rolling out 4.12 very slowly on Chrome so we can catch anything that might act up. Firefox will follow shortly after - ideally end of this week or early next if everything goes smoothly.

In the meantime, you can download 4.12 for Firefox on our [Releases page](https://github.com/MetaMask/metamask-extension/releases)!

**Comment by leroldary** [comment]
@bdesser any updates?

**Comment by bdresser** [comment]
4.16 is now published on Firefox! Thanks for waiting 😄
