### ISSUE TITLE
Moving Certain Permissions to "Optional Permissions"

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#5196]
As described here:
https://developer.chrome.com/apps/permissions

There is an optional permissions field that can ask permissions from the user when they decide to use a feature. In the spirit of fostering trust with our users, I think that this should be an easy fix--literally just modifying the manifest to move permissions, such as notifications and copy/paste, into the `optional_permissions` field

**Comment by bdresser** [comment]
Relates to #809

**Comment by bdresser** [comment]
closing in favor of https://github.com/MetaMask/metamask-extension/issues/809
