### ISSUE TITLE
Performance Issues w/ NewUI (and old?)

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#5197]
As evidenced by several of the one star reviews on the chrome store as seen here: https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/reviews

There seems to be an uptick of users dealing with performance issues, mostly related to the new interface. However, it should be noted that slowdowns have been reported even before our rollout the new UI.

This is an open-ended discussion as to why the extension seems to have performance issues, as well as strategies to properly triage the causes.

**Comment by bdresser** [comment]
Probably relates to our open bounty here: https://github.com/MetaMask/metamask-extension/issues/4074
