### ISSUE TITLE
Reading Private Keys in Metamask Wallet

### ISSUE THREAD

**Issue by mdpienaar** [MetaMask/metamask-extension#5200]
When private keys are viewed with Firefox 61.0.2 (64-bit), in
the add-on screen the bottoms of the letters of the last row, are
cut by the box's bottom line. Therefore it is not possible to clearly
distinguish between an E and an F.

![screen shot 2018-09-04 at 10 38 47 pm](https://user-images.githubusercontent.com/11485999/45056541-7be3ae00-b093-11e8-8d39-6603cfcde511.png)
 (the screen print attached shows what i mean with "add-on screen")

**Comment by whymarrh** [comment]
@mdpienaar can you reproduce this on 62.0.2? If so, what version of MetaMask do you have installed?

On 62.0.2 I see the following when viewing a private key:

<img width="370" src="https://user-images.githubusercontent.com/1623628/45987304-422b1500-c04b-11e8-9c9d-e0e645fd6408.png">

Is this the box you're talking about?

**Comment by alextsg** [comment]
@mdpienaar Can you please verify? Thanks.

**Comment by mdpienaar** [comment]
With Firefox 62.0.3 currently, on my laptop, private keys in the Metamask Wallet, you and i attached photos of above, do not appear clearly. In the photo you attached above the 8F119F752, would have appeared, if i looked at it with my wallet in Firefox, with the lower part of the letters and numbers cut off. Therefore an E could look like an F. In a Firefox browser tab, the private keys appear clearly.

**Comment by whymarrh** [comment]
This wasn't and continues to be something we can't quite reproduce, unfortunately.
