### ISSUE TITLE
My Metamask extension cant connect to any networks on any browsers. 

### ISSUE THREAD

**Issue by relpmis** [MetaMask/metamask-extension#5202]
After I click on the extension app I see this infinite connection: 

![image](https://user-images.githubusercontent.com/35630628/45075966-7452f200-b0f1-11e8-9d0b-1dc4aacd7730.png)

I tried to switch networks and back to main Ethereum one, but it doesnt help me.

I tried to kill the process of metamask but it doesnt help.

I tried to reinstall the extension and again nothing changed.

I tried to connect throught VPN and rebooted my router but the problem still there. 

Also I dont have an access to metamask' interface so I cant restore my seed phrase. All that I can do to choose a network which will not connect. And that's it. 

![image](https://user-images.githubusercontent.com/35630628/45076240-51750d80-b0f2-11e8-8265-5f5075e4cf09.png)

I have the same issue in all of my browsers (Opera, Firefox, Chrome).

It stopped my work for about already 2 weeks. 

Any suggestions?

**Comment by bdresser** [comment]
Sorry to hear @relpmis. If you have your seed phrase, could you try in another browser - Firefox or Brave? @tmashuang any other ideas?

**Comment by relpmis** [comment]
Finally fixed the problem.

The reason was about strange traffic blocking by my antivirus soft NOD32 11.2. After right and logic setting of this filters my metamask started to work properly.

Im closing this ussue.
