### ISSUE TITLE
MetaMask Login Problem

### ISSUE THREAD

**Issue by Nitishkumar3211** [MetaMask/metamask-extension#5203]
**Describe the bug**
When i am working on RPC local network and then shut down my pc then i reopen it then he is asking for signin Password and after submit correct password it will go on search and never connect because last used was on Custom RPC network.

**To Reproduce**
1. Go to '.Run Ganache/ testRPC.'
2. Click on '.Select Network in metamask via Custom RPC.'
3. Restart you pc and just and just try to connect with other network
4. Its will not connect to any network.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Browser :- Chrome
 - MetaMask: 4.9.3
 -  Beta UI

**Comment by bdresser** [comment]
@Nitishkumar3211 when the extension is trying to connect to the custom network, try clicking the very small spinner in the top-right of the extension screen. It's possible to escape this loading screen, but the way out isn't particularly clear.

We realize it's not the best UX and are in the process of fixing it here: https://github.com/MetaMask/metamask-extension/issues/3776

Closing this issue for now – if it's actually not possible to switch away from the "connecting" screen as I describe, let me know and I can re-open.
