### ISSUE TITLE
Stop attempting ENS resolution on `eth`

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5205]
Our TLD matching tries to match even if the user enters `eth` without the `.` 

We should make it more specific to only attempt to resolve to an ENS domain if the user has actually entered `.eth`

**Comment by raboid** [comment]
Where exactly is this issue present?

I see there is already [code](../blob/master/app/scripts/lib/resolver.js#L64) on master that seems to handle this.

**Comment by bdresser** [comment]
this is being handled in https://github.com/MetaMask/metamask-extension/pull/5250

**Comment by whymarrh** [comment]
#5250 has been merged
