### ISSUE TITLE
UI only shows 3 accounts inf NEW UI

### ISSUE THREAD

**Issue by gianni-dalerta** [MetaMask/metamask-extension#5219]
**Describe the bug**
After importing 3 accounts, on attempting to import a 4th, the UI does not show the 4th account. When attempting to do the import function again, I get the "The account you're are trying to import is a duplicate" status report.

**To Reproduce**
1. Import account. Seems to succeed.
2. Does not show on the list of accounts.
3. Attempting to import again provides the "The account you're are trying to import is a duplicate"

**Expected behavior**
Show 4+ accounts.

**Browser details (please complete the following information):**
 - OS: Lastest Windows
 - Browser Chrome
 - MetaMask Version Latest
 - Old UI or New / Beta UI? NEW

**Comment by bdresser** [comment]
The top part of the Account menu is scrollable - it's possible your additional account is hidden below the scroll?

![screen recording 2018-09-10 at 11 25 am](https://user-images.githubusercontent.com/1016190/45316667-8d421580-b4ec-11e8-9719-f09bd4732d6e.gif)


If you're unable to scroll, could you specify your Windows & Chrome versions?

**Comment by gianni-dalerta** [comment]
@bdresser dang! The 4th account icon, was not peeking enough for me to see, the top of the icon was a color that blended a bit into the background. You can see it on the uploaded image. 

Highly suggest you guys add something on the side that shows that there are other accounts below the fold, maybe a right hand scroll or some arrows that show there are more accounts. 

![metamask](https://user-images.githubusercontent.com/770459/45327178-7e775500-b524-11e8-90e2-e57e771989b9.jpg)

please close out this issue. Thanks for the responses.
