### ISSUE TITLE
Update custom token name in new UI after its been added.

### ISSUE THREAD

**Issue by gianni-dalerta** [MetaMask/metamask-extension#5221]
**What problem are you trying to solve?**
There is no way to update the token name after its been added in an account.

**Describe the solution you'd like**
Be able to change the name of a token, instead of it appear generically as ERC 20

**Comment by gianni-dalerta** [comment]
@bdresser yes, maybe the symbol is arbitrary, or the person is experimenting (like I am), or you want to overwrite it for whatever reason. But something like the way you an rewrite the account name, or like on MEW that you can type in whatever ticker you want. 

Its not a necessary feature, just an idea. Please feel free to kill it.

**Comment by jschiarizzi** [comment]
This _is_ necessary. If the ERC 20 token id is longer than 12 characters it is currently impossible to add it to metamask. Very annoying 
![screenshot 104](https://user-images.githubusercontent.com/9449596/52129352-5092ca00-2605-11e9-9e91-cb6f18d2486f.png) I would like this to be a bit higher priority. @bdresser can I put a bounty on this?

**Comment by brunobar79** [comment]
@jschiarizzi

Are you sure you are not confusing the name attribute with the symbol?

The symbol is supposed to be something short, SNT, GNO, OMG, DAI, etc (just look at any other ERC20 tokens) while the name is expected to be longer.

IMO, `dogsonchain.com` looks like a not ideal usage of the symbol property...

Can you add some context about why do you think this is necessary?

**Comment by jschiarizzi** [comment]
Yes, I did mean token symbol.

The token pictured here is just an example which sent me random tokens so when you see it on etherscan you go to their site, a bit of a scam. I agree that the symbol _should_ be something shorter. I think it's necessary because if the symbol happens to be longer metamask doesn't support it.

If I want to use one of these s̶h̶i̶t̶c̶o̶i̶n̶s̶ randomly airdropped worthless tokens for something, I can't use it with metamask at all because I can't use the Add Token form with it.

**Comment by whymarrh** [comment]
Fixed in #6147

**Comment by jschiarizzi** [comment]
thank you @whymarrh, you rock!

**Comment by whymarrh** [comment]
@chikeichan did all the hard work 😄

**Comment by RickSpindler** [comment]
This issue needs to be worked again with the new Metamask UI. For instance...I'm on stargate wanting to add USDC to the pool. There is no difference displayed between Arbitrum USDC (USDC) and Bridged Arbitrum USDC (USDC.e) So, one must try to figure it out. Why not just let me edit the token name. Now both contracts say USDC in Metamask,.
