### ISSUE TITLE
Allow deletion of custom networks

### ISSUE THREAD

**Issue by cliffhall** [MetaMask/metamask-extension#5222]
**What problem are you trying to solve?**

- Trying  to remove an incorrectly specified custom network from MetaMask.

**Describe the solution you'd like**
1. Add an 'x' button to the right of each custom network name in the networks dropdown. 
1. Clicking the button should raise a confirmation dialog with 'Yes' and 'Cancel' buttons, saying "Are you sure you want to delete this network?". 
1. Clicking 'Yes' should delete the custom network.

**Additional context**

- In the screenshot below, I had inadvertently added the https://127.0.0.1:7545 address which did not work, then added http://127.0.0.1:7545 which did. Now I'd like to remove the one that did not work.
![screen shot 2018-09-09 at 5 00 02 pm](https://user-images.githubusercontent.com/871933/45268928-68995f80-b452-11e8-91a9-388fef4e3db8.png)

- Also, the following advice from issue #3507 does not work:
https://github.com/MetaMask/metamask-extension/issues/3507#issuecomment-391780307

**Comment by hackmod** [comment]
Please see UI suggestion #5246 and the PR #5267

**Comment by bdresser** [comment]
hey @cliffhall - as @hackmod mentions, this will be handled in #5267

**Comment by zemse** [comment]
Is this implemented? I'm using Metamask 7.7.3 but can't find the option

**Comment by gonchs** [comment]
Has this option been removed? It's not available in 7.7.9 anymore. I have to reinstall Metamask to delete the network.

**Comment by davidcallanan** [comment]
This is ridiculous. I'm trying to test my apps ability to automatically add a chain to metamask. For testing purposes, I must delete the network from metamask so I can test this.

It would be great if this is fixed!
