### ISSUE TITLE
Missing Metamask extension from Chrome Browser 

### ISSUE THREAD

**Issue by techkaki** [MetaMask/metamask-extension#5226]
**Issues**
I open up my Chrome browser as usual only to spot my Metamask extension is missing. Tried to refresh and restart the browser but nothing happen.

**Browser details**
 - OS: MacOS High Sierra 10.13.6
 - Browser : Chrome
 - MetaMask Version 4.9.3

**Comment by bdresser** [comment]
@techkaki head to `chrome://extensions` and make sure MetaMask is enabled. If you accidentally declined the recent permissions ask, it's possible that Chrome disabled the extension.

**Comment by techkaki** [comment]
@bdresser , thank you so much! You are a life saver! Got my Metamask back with my precious cryptos intact 👍 👍 👍

**Comment by bdresser** [comment]
no problem @techkaki 😄 

please make sure you back up your seed phrase so you'll be able to restore your MetaMask account on another computer if something really goes wrong!
