### ISSUE TITLE
I'm Still Have My MetaMask Wallet But How To Retrieve It When The MetaMask on Google Chrome Removed?

### ISSUE THREAD

**Issue by jsim77** [MetaMask/metamask-extension#5227]
Dear Support,

I need HELP to retrieve my MetaMask Wallet using Google Chrome as it has been removed unintentionally. Also, I have not save my SEED Phrase at all. My fault.

I need to access it as my Balance and my New Token are all inside this Wallet of mine. Please please reply and many thanks for your help.

**Comment by bdresser** [comment]
hey @jsim77 - please send an email to support@metamask.io and they'll be able to help you out!
