### ISSUE TITLE
Add useful debugging tips on the default (un-loaded/errored) screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5239]
When MetaMask UI crashes, it currently shows nothing:
https://twitter.com/eeligul/status/1039535652486959104

It would be great if we made the popup show _something_ useful instead. It could say something like "MetaMask is starting up, but if it seems stuck, click here"

We could then link people to how to check UI logs and report those to support, and how to even uninstall/reinstall, or move their seed phrase to another client in case they're in an emergency!

**Comment by tmashuang** [comment]
Closed by #7889.
