### ISSUE TITLE
Ability to Inject inpage.js on Approved Sites

### ISSUE THREAD

**Issue by JoshuaCaputo** [MetaMask/metamask-extension#5243]
**What problem are you trying to solve?**
When your MetaMask is unlocked, it is possible for the address you are currently using to be viewed by all the other tabs you have open in your web browser.

**Describe the solution you'd like**
In many web browsers, your are asked if you would like to send your location, receive notifications, etc., under site settings. Is it possible for the MetaMask extension to only inject it's scripts on approved domains, possibly with SSL authentication?

**Additional context**
I know, this may seem like a super-user feature. However, it does seem to clear up any mapping of public address by sites. I was thinking of making a separate extension to kill the injection of MetaMask on any site not in the list.

**Comment by bdresser** [comment]
@JoshuaCaputo check out #714 and related issues; also check out https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md

First step is opt-in web3 injection (and address exposure) and from there we'll work on making it per-site. Closing this for now, holler if you have more questions!
