### ISSUE TITLE
Download distributable files?

### ISSUE THREAD

**Issue by EddieOne** [MetaMask/metamask-extension#5244]
**What problem are you trying to solve?**
I want to add metamask to an electron app/browser. Are there dist files available to download?

**Describe the solution you'd like**
For Flash, I have 3 pepper plugin files for win, mac, linux. I would like something like that for metamask.

**Additional context**
This is a browser for y8.com, that's the reason for Flash.

Thanks

**Comment by bdresser** [comment]
@EddieOne check the extension README - `npm start` and `gulp build` should both output some dist files.

**Comment by EddieOne** [comment]
ok thanks, I will try to build it.
