### ISSUE TITLE
When i click on Metamask i am just getting a blank white page. I have been using in the same computer since January

### ISSUE THREAD

**Issue by ThanePropertyInvestmentsLtd** [MetaMask/metamask-extension#5245]
**Describe the bug**

 It is just blank white. No Metamask fox or anything in the box

**To Reproduce**

**Expected behavior**
 Expected to see the Metamask menu

**Screenshots**

![image](https://user-images.githubusercontent.com/36347543/45435976-a512c880-b6a9-11e8-9e4e-88ccdee8e7df.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser  Chrome
 - MetaMask Version  4.9.0
 - Old UI  

**Additional context**

**Comment by ThanePropertyInvestmentsLtd** [comment]
When i click on MetaMask i am just getting a blank screen.

**Comment by bdresser** [comment]
@ThanePropertyInvestmentsLtd we're aware of the issue and have an open bounty for anyone who can help - see #4894

**Comment by ThanePropertyInvestmentsLtd** [comment]
No I did not add anything.On 15 September 2018 at 02:20 tiro6090 <notifications@github.com> wrote:  @ThanePropertyInvestmentsLtd so the extension previously worked for you, and just started not working?Did you recently add any kind of security (VPN, Proxy, Antivirus, or even a new adBlock)?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
