### ISSUE TITLE
Editable Networks

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5246]
Right now we persist the last three custom networks a user has joined (https://github.com/MetaMask/metamask-extension/pull/5096)

It'd be nice if we remembered every custom network and let the user decide which they want to remove.

![remove-networks](https://user-images.githubusercontent.com/1016190/45444577-b1346100-b67c-11e8-83f5-ffee18760478.jpg)

**Comment by whymarrh** [comment]
Added in #5267
