### ISSUE TITLE
Add support for a hosted blocklist of addresses

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5248]
We sometimes become aware of addresses of phishers, for example phishers operating on Telegram, and so a hosted list of phishing addresses could allow us to at least temporarily and quickly respond to known phishing attempts.

**Comment by jennypollack** [comment]
this is covered by [eth-phishing-detect](https://github.com/MetaMask/eth-phishing-detect), unless you had something else in mind?
