### ISSUE TITLE
[CANCEL] and [CONFIRM] buttons are hidden : Firefox + second monitor

### ISSUE THREAD

**Issue by sulliwane** [MetaMask/metamask-extension#5252]
**Describe the bug**
On Firefox, I can't see the [CANCEL] and [CONFIRM] buttons.

**To Reproduce**
1. Open firefox in a second monitor (1920x1080px)
2. launch a transaction that needs confirmation

**Expected behavior**
I should see the [CANCEL] and [CONFIRM] buttons.

**Screenshots**
NOT OK on my second display:
![metamask-zoom-issue-firefox](https://user-images.githubusercontent.com/1733686/45496931-c5f51f80-b776-11e8-8da4-cc9ad462f1d6.png)

But Ok on my main screen (3200 x 1800px):
![metamask-ok](https://user-images.githubusercontent.com/1733686/45496924-c392c580-b776-11e8-97fa-5d1930211f19.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : Firefoox
 - MetaMask Version : 4.9.2
 -  New / Beta UI

**Additional context**
It's working on chrome (both modes are working : as a popup or as a popover)
![screenshot from 2018-09-13 17-05-20](https://user-images.githubusercontent.com/1733686/45497115-4f0c5680-b777-11e8-822f-37d1e5818602.png)

**Comment by brunobar79** [comment]
@sulliwane make sure your zoom level is set to 100% (disabled). Based on the screenshots you provided it looks like that’s the case.  Closing for now but feel free to reopen if you confirm that’s not the case.

**Comment by weijiekoh** [comment]
I face this issue all the time. Shouldn't MetaMask's UI adapt to the zoom level? That would provide better UX for people who need their browser to be a little more zoomed in than the default.
