### ISSUE TITLE
Integrate Wyre for fiat onboarding

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5260]
Sounds like a nice option for in-extension fiat onboarding

https://www.sendwyre.com/docs/

**Comment by bdresser** [comment]
https://medium.com/fluidity/convert-fiat-on-airswap-with-wyre-48c6d044d8cb

**Comment by bdresser** [comment]
Because of #6199, we should at least change a link to a solid wyre integration

How changing the Coinbase header to link to https://instant.airswap.io/. Needs a little additional copy.

"Buy ETH with Wyre"
Wyre lets you use aa credit caard to deposit ETH right in to your MetaMask account. From the Airswap website, click "Use Fiat" in the top-right corner. You can also use Airswap to get started with ERC 20 tokens!

Should also discuss just integrating the Wyre widget right in to a full-screen ui @danjm

**Comment by bdresser** [comment]
Docs for the widget are [here](https://docs.sendwyre.com/docs/widget-api).

**Comment by bdresser** [comment]
Legal has the financial docs we need to set up an account, should be unblocked shortly.

**Comment by pgebheim** [comment]
> Should also discuss just integrating the Wyre widget right in to a full-screen ui @danjm

Has this been done / is using the Wyre widget the current plan / scope for this ticket? For Augur v2 we're going through all the wallets people commonly use and trying to make sure Fiat on ramp fits in with what users of the platform would need. Currently this looks like (minimally) supporting the Wyre widget where that's possible.

**Comment by bdresser** [comment]
@pgebheim this is in progress! since Wyre is US-only we're also planning to support a fiat on-ramp via Simplex as well.
