### ISSUE TITLE
Label Custom RPC's, or re-assign the provider for preconfigured Ethereum networks

### ISSUE THREAD

**Issue by 1blockologist** [MetaMask/metamask-extension#5277]
**Describe the bug**
I have a few custom RPCs added and these show as a URL in the Metamask network switcher. This gets confusing, they lack the color configuration and names of the Ethereum networks, unlike the default configuration networks.

These custom RPCs can be mainnet, ropsten or other Ethereum networks, but Metamask currently treats them as unknown networks as if they were private nets.

**To Reproduce**
1. Go to Network dropdown
2. Click on existing added custom link (initially you do this by scrolling to Custom RPC and adding a provider URL
3. See that Metamask sometimes has no clue which Ethereum network its on, but will check the balances of that address no problem.
4. See description of this experience written above

**Expected behavior**
The expected behavior is that they should replace the infura connection completely at the user's discretion. If the user wants a custom RPC to a private net, then that can be a separate network they can add. 

**Additional context**
Maybe your team will call this a feature request, but those semantics are unimportant as long as its not unilaterally closed and instead moved into the development process.

**Comment by whymarrh** [comment]
You can now add a nickname for custom RPC networks (pictured below)

![](https://user-images.githubusercontent.com/1623628/52385865-15a5f180-2a5e-11e9-9df9-58a6fb613c41.png)
