### ISSUE TITLE
How do i receive an event in web3 when a user confirms a transaction in MetaMask

### ISSUE THREAD

**Issue by mjdietzx** [MetaMask/metamask-extension#5279]
I'm using MetaMask as my web3 provider. And I need to listen to some events (ie when a user confirms a transaction). Looked through code and searched around but haven't found anything.

Use-case is I need to indicate `sign the transaction in MetaMask` and then `transaction is being mined` loading bar. but I havn't been able to do this without getting some kind of event

i guessed some things like `confirmed` and `transactionConfirmed` but no luck
`web3.currentProvider.publicConfigStore.on('transactionConfirmed', () => {`

**Comment by danfinlay** [comment]
When a user accepts a transaction, you receive a callback with that transaction's hash. We currently do not have an event for that transaction's completion, it requires polling `getTransactionByHash`, or using  a convenience library like the [ethjs.getTransactionSuccess()](https://github.com/ethjs/ethjs) method.
