### ISSUE TITLE
In Console: getListAccounts -> Internal JSON-RPC Error ?

### ISSUE THREAD

**Issue by theomarshanti** [MetaMask/metamask-extension#5285]
**Describe the bug*
The user can not retrieve account information through the `personal` module. 
The personal.getListAccounts returns an Internal JSON-RPC error;
The personal.listAccounts fails to recognize the callback parameter and throws an error.

**To Reproduce**
1. If not already logged in to the MetaMask browser extension in Google Chrome, then log in.
2. Open "google.com" (or any arbitrary webpage) with Google Chrome..
3. Open your console.
4. Enter `web3.personal.getListAccounts(function(err,data){if(err){console.log("err is:", err)}else{console.log("data is:", data)}});` Observe "Internal JSON-RPC error".
5. Enter `web3.personal.listAccounts(function(err,data){if(err){console.log("err is:", err)}else{console.log("data is:", data)}});`. Observe error asking for a callback parameter.

**Expected behavior**
Steps 4 & 5 should each console.log the data accordingly.

**Screenshots**
Attached.

**Browser details (please complete the following information):**
 - OS: MacOS 10.13.4
 - Chrome 69.0.3497.92
 - MM Version: 4.9.3
 - New / Beta UI

**Additional context**

**Comment by theomarshanti** [comment]
@bdresser it works and outputs the same array as `web3.eth.accounts`. I am just trying to figure out how MetaMask works under the hood and so wanted to see what was stored in the `personal` module. So my inquiry is for educational purposes - but in any case, it is the expected behavior too


<img width="1440" alt="screen shot 2018-09-18 at 9 36 24 am" src="https://user-images.githubusercontent.com/42391911/45705001-002b3c00-bb3e-11e8-8ffd-144ae5a6626c.png">

**Comment by danfinlay** [comment]
The `personal` module shouldn't be supported by MetaMask at all, it implies an environment that is trusted with the user's private keys. For the Dapp sandbox, you should use `web3.eth.getAccounts()`.
