### ISSUE TITLE
Shape shift api change

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#5297]
Shape shift now requires [kyc](https://en.wikipedia.org/wiki/Know_your_customer) we may want to consider something else or talk to legal about this if we want to integrate. 

here are the new docs: https://documenter.getpostman.com/view/44077/716cFNs

*we have until November first to deal with this.*

**Comment by whymarrh** [comment]
We've removed the ShapeShift deposit modal (refs #6478, #6746)
