### ISSUE TITLE
Metamask Version returned as 'vundefined' by web3.version.getNode()

### ISSUE THREAD

**Issue by destrys** [MetaMask/metamask-extension#5299]
### Expected Behavior:
```
web3.version.getNode(function(er,res) {console.log(res)})
Metamask/v4.10.0
```
### Actual Behavior:
```
web3.version.getNode(function(er,res) {console.log(res)})
Metamask/vundefined
```
<img width="655" alt="screen shot 2018-09-19 at 12 36 33 pm" src="https://user-images.githubusercontent.com/1590973/45776740-b0fe0d80-bc08-11e8-98d0-0871d347ad20.png">

### Browser/ OS:
Chrome Version 68.0.3440.106
OSX 10.13.5

### Note:
This behavior started after upgrading to `4.10.0`. Behavior was as expected in `4.9.3`

**Comment by bdresser** [comment]
@tmashuang did something happen with the tag or internal bump?
