### ISSUE TITLE
Chrome extension for Metamask not working

### ISSUE THREAD

**Issue by GtDane57** [MetaMask/metamask-extension#5300]
New to Metamask
I'm using Chrome 69... on Windows 10
I have installed Chrome extension for Metamask,
but metamask.io keeps asking for it:

![image](https://user-images.githubusercontent.com/6466196/45777822-bd379a00-bc0b-11e8-8df6-9695bd4b73f2.png)
![image](https://user-images.githubusercontent.com/6466196/45777860-d5a7b480-bc0b-11e8-93a8-c4aac626cdb0.png)
I looked thru the FAQ's but didn't find anything helpful

**Comment by bdresser** [comment]
hey @GtDane57 - this is a question for support. Please email support@metamask.io and we can help you there!

in the meantime, look in the top-right of your browser (next to the address bar) for a small fox icon...
