### ISSUE TITLE
"Retry" button should only be available on earliest "submitted/pending" transaction.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5301]
Seems like we have a user who was increasing price on a later (blocked) transaction.

This issue can be closed by verifying/ensuring that we only have our "Retry/Speed up" button on the earliest (nonce) pending transaction in the queue.

**Comment by alextsg** [comment]
Testing on ganache I'm seeing the speed up button on only the earliest transaction:

![image](https://user-images.githubusercontent.com/8051479/45796392-298abb80-bc55-11e8-9788-c29df055ca5c.png)

**Comment by bdresser** [comment]
yep this was fixed in https://github.com/MetaMask/metamask-extension/pull/4926
