### ISSUE TITLE
Add a button to completely unlink current vault.

### ISSUE THREAD

**Issue by alxmhe** [MetaMask/metamask-extension#5305]
**What problem are you trying to solve?**
I have been using Metamask for development with a seed phrase shared between multiple developers. Now I want to use a different vault (and new accounts) for another project (or for personal use). I can't get Metamask to display the option to create a new vault again. Uninstalling and reinstalling Metamask is not enough anymore.

**Describe the solution you'd like**
I would like an option to completely unlink Metamask from its current vault, after making sure I backed up my seed phrase and password.

**Additional context**
I am using Metamask v.4.9.2.

**Comment by bdresser** [comment]
Thanks for the suggestion @alxmhe - closing as a dulplicate of #4828
