### ISSUE TITLE
Broken method signature.

### ISSUE THREAD

**Issue by peculiarity** [MetaMask/metamask-extension#5306]
Calling `web3.eth.getTransactionCount` method results in the following error:
 `MetaMask - RPC Error: TypeError: r is not a function`

**To Reproduce**

1. Go to `https://oasis.direct`
2. Click on `"Continue"` next to the `Metamask` label
3. Leave it as it is and sell `ETH `for `DAI`.
4. Open the `dev console`
5. When asked to sign the TX , just do it.
6. UI gets frozen on `Signing Transaction` state.
7. There is an error thrown in the `dev console`

**Expected behavior**
 Sign the transaction successfully without throwing any errors.

![image](https://user-images.githubusercontent.com/23715025/45822080-feeb4200-bcea-11e8-9416-b19dd260df25.png)

![image](https://user-images.githubusercontent.com/23715025/45822108-0ca0c780-bceb-11e8-8be3-e551dab688d1.png)

**Browser details (please complete the following information):**
 - OS: Linux 
 - Chrome Version 67.0.3396.99 (Official Build) (64-bit)
 - MetaMask Version 4.10.0
 - Beta UI
 - web3 0.20.6 ( local instance with injected provider )
**Additional context**
This is quite important. We have a method that is listening for all the pending transactions for a given address.

```javascript 
export const getTransactionCount = address => {
  return promisify(web3.eth.getTransactionCount)(address, "pending");
}
```

The problem comes from the second argument. If we remove it, everything works fine but if we leave it as it is now, everything is broken. According to the method signature [https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactioncount](url) the first argument is the `address` , second one is `Number|String` and third one is a `Function`. 

I think somehow you guys skip passing the second argument and instead you pass the third one as second and this is where the confusing comes from.

It was working fine so far but since the latest version things are broken.

Also have in mind that we tried `infura` nodes directly through our hardware wallet support so on the node side everything works fine  ( unless you have some dedicated node ) 

Please elaborate as soon as possible!

@danfinlay  @kumavis @alextsg

**Comment by bdresser** [comment]
hey @peculiarity - I went through the flow at oasis.direct and also got the error you mentioned. However, my UI never froze on the "signing transaction" state and the transaction went through (Etherscan). And I now have 30 DAI  😄 

I'm on MM v4.10 and Chrome 69 - have you tried in other browsers? And would you mind sending your state logs to support@metamask.io and mentioning this issue number? They might help us debug how you got stuck in this state. 

cc @danjm

**Comment by peculiarity** [comment]
@bdresser As  I have mention the UI gets stuck but transaction passes. The problem is when you query for existing pending transactions which doesnt affect the happy path. If its on Main then congrats on the DAI

**Comment by bdresser** [comment]
> UI gets frozen on Signing Transaction state.

Do you mean the extension freezes with the spinner overlay on top of the confirmation screen? or do you mean the transaction just stays as `pending` even once it's confirmed?

Might be related to #5174, we're investigating.

**Comment by peculiarity** [comment]
I'm the UI of the dapp :) (probably shouldn't have mentioned it since it's not explicitly metamask but it is a result of Metamask not being able to perform the `getTransactionCount` call. )

![image](https://user-images.githubusercontent.com/23715025/45843942-37a60e00-bd21-11e8-922b-df88df1c88f9.png)

YOu have mentioned that you were able to reproduce it but the issue itself is marked with a label `needsReproduction`

**Comment by taxe1** [comment]
The same problem with it in chrome browser: TypeError: r is not a function at chrome-  . When you fix it already? It happens in tokenstore, forkdelta, etc.. Return the previous normal version please and don't touch anything more, thanks.

**Comment by TimGeibel** [comment]
I can confirm this Error. Appears on tokenstore when trying to cancel an open order: 
<img width="796" alt="bildschirmfoto 2018-09-23 um 18 02 09" src="https://user-images.githubusercontent.com/1818480/45930076-02850000-bf5b-11e8-8466-8c4768732ca2.png"> 

macOS 10.13.6, Chrome 69.0.3497.100

**Comment by itokenstore** [comment]
Confirming that our users are facing issues. Seems you can reproduce by attempting to cancel a trade with latest version of Metamask on http://token.store/.

**Comment by peculiarity** [comment]
@tmashuang When should we expect the release of the fix?

**Comment by exarus** [comment]
@peculiarity @itokenstore it seems to be fixed:
(source #5323 )
