### ISSUE TITLE
Recovering account with a seed phrase after 50 days of not having meta mask installed resulted in all addresses and data deleted from meta mask account!

### ISSUE THREAD

**Issue by innerlogic1** [MetaMask/metamask-extension#5308]
I have been emailing support about this, and they do not seem to be taking me seriously about it, so i am putting this here so no one else loses there funds hopefully in the future, if you guys can find a fix for it. Anyway, I had meta mask installed about 2 months ago, however, i had to wipe my computer because of some issues. I wasnt worried because i had used my seed phrase many times before. However, this time, when i entered the seed phrase an entirely new account was created. ALL OF MY ADDRESSES GONE. I looked around for a fix to this because apparently many people have experienced this issue. Except some  said all they had to do was just hit create new address and their original addresses would come up. This has not worked for me, it has only created new addresses. my original address that had all my funds on it is here 0xfaDaB48B3a1A48385B8a1DF870CE0375ED5d286e. And all my funds are there, with my most recent activity being from about 2 months ago. Somehow meta mask account got dissociated to my addresses so i am essentially screwed. I do not have my private key because meta mask assured me that the seed phrase was what i needed to save. 

This a very serious bug you have here and it must be related to these other posts i found, and i would hate for someone to lose more than $400 because they put to much trust in google chrome extension with potential flaws. But i wasnt so lucky. If you need anymore info, let me know

**Comment by innerlogic1** [comment]
this is for google chrome, i tried previous versions of meta mask besides the latest one, and the issue was still the same.

**Comment by tmashuang** [comment]
Personally, I have two seed phrases that very similar, only difference is one word `aware` and `unaware`. They both give me a list of different accounts. So, my question is how accurate is your seed phrase? The reddit thread that you researched is very detailed and trying to figure out a solution to seed phrase issues. Short of providing us with your seed phrase, we can only provide debugging strategies.

**Comment by innerlogic1** [comment]
its a text document i created the day i created the account and has
remained untouched on my usb. Literally no way it could be a different
phrase. I also have a copy that has been on my computer, exactly the same.
I have checked them both. This copy has absolutely been used to recover it
when i got a new computer and when i had to use on a spare computer. I can
give you my seed address, it is obviously worthless now if i cant get my
address back. If i can get it to you privately i will give it to you for
research purposes

**Comment by tmashuang** [comment]
The address of the seed phrase is less important than the seed phrase itself. If you wanted to provide any sensitive information, please reply to the support thread that. On the Seed Phrase Bounty issue, https://github.com/MetaMask/metamask-extension/issues/3127, recently reproduced an issue with the UI showing an old seed phrase when an new phrase is inputted on a specific step.

**Comment by innerlogic1** [comment]
sorry, i am not very familiar with github. i followed that link. So if i
comment on the bottom, no one but meta mask staff will see it...? I just
want to make sure its for "need to know" people. thanks

**Comment by innerlogic1** [comment]
so how can i get this seed phrase to the meta mask team, secretly?

**Comment by bdresser** [comment]
hey @innerlogic1 - this is a question for our support team. Please send us an email at support@metamask.io and we'll help you out there. Sorry for your trouble!
