### ISSUE TITLE
BigNumber being fed nil

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#531]
@niran:
web3 is feeding `<nil>` into a BigNumber constructor, which I haven’t seen outside of Metamask. Has anyone seen that before?

I've also seen this as well when developing on the conversion feature.

**Comment by flyswatter** [comment]
We could use some reproduction steps if possible, @niran.

**Comment by Zanibas** [comment]
Does anybody remember the status of this?
