### ISSUE TITLE
Add better description to "export password" input 

### ISSUE THREAD

**Issue by JSON-LEE13** [MetaMask/metamask-extension#5314]
**Describe the bug**
User attempts to export a private key of a imported account however they are hit with a "incorrect password" message even though the same password is used to import the account seconds earlier.

See below video

https://twitter.com/theadityanalge/status/1042545966140669952/video/1

Update:
Not actually a bug. 
User must input the password that decrypts the JSON file when importing their account.
User must input the extension password when exporting the private key.
We should clarify each input in the UI

**Comment by JSON-LEE13** [comment]
MetaMask Version 4.10.0 
Browser - Google Chrome Version 69

**Comment by tmashuang** [comment]
It is possible we are using the vault/Metamask default password instead of the imported Json File password.

**Comment by whymarrh** [comment]
> It is possible we are checking for the vault/Metamask default password instead of the imported Json File password.

I was able to reproduce this locally and I can confirm that the default password does work

**Comment by whymarrh** [comment]
Is this a bug? I can see a case being made for either password working. The password that works here is the same password that's used to unlock MetaMask.

**Comment by bdresser** [comment]
from the tweet referenced in #5315 this is on 4.10

**Comment by bdresser** [comment]
fair point @whymarrh but if the behavior changed we should know why? 

also either way we should update the UI to clarify which password we're looking for (on both password fields)

**Comment by whymarrh** [comment]
> if the behavior changed we should know why

I'm not sure it changed. I'll take a look at 4.9.3.

**Comment by whymarrh** [comment]
> also either way we should update the UI to clarify which password we're looking for (on both password fields)

That's a good point
