### ISSUE TITLE
Add Transaction ID to Transaction Detail View

### ISSUE THREAD

**Issue by 1blockologist** [MetaMask/metamask-extension#5316]
**What problem are you trying to solve?**
Currently as of 4.10 the user can expand transaction history and copy the sender and recipient addresses upon hovering.

![image](https://user-images.githubusercontent.com/21366360/45911291-1ea36880-bdc6-11e8-969e-74db2018c4f9.png)

Despite there being plenty of transaction details available, there is no way to copy to the transaction id in the same way, or at all.

The problem is that there is no way to copy the transaction id within the interface itself.

**Describe the solution you'd like**

The ability to copy the transaction id in the same area as the addresses would be what I'd like.

I've attached a few candidate solutions that I hope to inspire.

A) The transaction ID underneath the address hashes. I think a transaction ID is longer anyway, so it might be a good fit. The counterpoint being that who cares, just need a way to click it and get it on the clipboard, so it may not need much space.

![image](https://user-images.githubusercontent.com/21366360/45911309-632f0400-bdc6-11e8-9573-83f0cc3ebfe2.png)

B) The transaction ID within the transaction header.
![image](https://user-images.githubusercontent.com/21366360/45911314-66c28b00-bdc6-11e8-9fc4-bb1978db5a7d.png)

**Additional context**
Attached above.

**Comment by bdresser** [comment]
@1blockologist thanks for the suggestion. Curious - what's your usecase? 

Also, you probably know this, but the small arrow on the top-right of the transaction detail view will take you to Etherscan, where you can easily pull the transaction hash.

**Comment by 1blockologist** [comment]
I would primarily use it for copying and pasting transactions IDs to people that I paid, so they can follow the transaction's progress towards confirmation.

**Comment by bdresser** [comment]
Makes sense! Any reason to not use an Etherscan link for that?

**Comment by 1blockologist** [comment]
Note, 4.11.0 seems to have removed this feature for me. Clicking on a transaction goes straight to etherscan, it was either rolled back or I got stuck in the hell section of the A/B test.


To answer your question blockexplorers don't relay unconfirmed transactions reliably and I'd rather not rely on them, although Etherscan will at least form the url slug from the txid whether there is info or not. There is no way to copy the transaction id within this wallet. If I tried to replace a transaction and had several pending transactions in Metamask, it would be convenient to quickly expand them and copy and txid's when I decided which one was the one I wanted. A tiny button in the collapsed version of the cell that let me copy it would be welcome too

**Comment by bdresser** [comment]
we rolled back a couple features in 4.11 to address some issues users were experiencing.

once that expanded transaction detail view is back - clicking the small arrow icon on the top-right of the transaction detail view will take you to etherscan.

**Comment by 1blockologist** [comment]
Would it be more productive for me or my team to submit a PR with this? We don't want to do the work and then get summarily dismissed

or do people do PRs + Issues

or is there another chatroom we can talk directly with you guys and the design team

**Comment by bdresser** [comment]
@1blockologist we're in the middle of a redesign of the transaction detail view (https://github.com/MetaMask/Design/issues/25) so we'd prefer not to add another field in the middle of that work - especially since it's just a small improvement to the "View on Etherscan" link. Let's check back in a couple of weeks! 

Thanks as always for the feedback.

**Comment by 1blockologist** [comment]
How are we looking on this? Metamask 4.16 is pretty good

**Comment by bdresser** [comment]
@1blockologist we'll post designs for what this could look like as soon as we have the bandwidth! Thanks for your patience.

**Comment by MadelineMurray** [comment]
Would love to see this enhancement in MetaMask.  My use-case is using MetaMask to make transactions and then needing the transaction to use as input JSON-RPC APIs methods to get transaction details.

**Comment by 1blockologist** [comment]
Thanks for adding the copy button for this simple feature!
