### ISSUE TITLE
Cant withdraw my funds from Forkdelta

### ISSUE THREAD

**Issue by MrMojito007** [MetaMask/metamask-extension#5321]
I cant withdraw funds from Forkdelta, No transactions are being showed on etherscan.
 wallet adress: 0x51be5D11c158b257a8E6a20878E86a9b940E7a46
Doesnt show any transactions..

![metamask](https://user-images.githubusercontent.com/43496875/45917676-6c2ddd00-be7b-11e8-93b7-b7043e871ca5.png)

![metamask 1](https://user-images.githubusercontent.com/43496875/45917693-a8613d80-be7b-11e8-927b-ecd0900f12d2.png)

**Comment by tmashuang** [comment]
With the information you provided, the transaction hash and your address, I found the transaction on a block explorer (https://etherscan.io/tx/0x92c113b2629fa91c04876ab453955329b98396e60d50ba2c3e0ad8dca78e59a9). Then searched for the contract error on Etherdelta related forums. Found this thread, https://www.reddit.com/r/EtherDelta/comments/6u7s1v/bad_jump_destination/

**Comment by bdresser** [comment]
It also looks like Forkdelta fixed a compatibility issue with 4.10 [here](https://github.com/forkdelta/classic-frontend/pull/175). Closing this for now, but please let us know if you're still having trouble.
