### ISSUE TITLE
Am not seeing my eth in forkdelta neither my tokens deduct from my wallet

### ISSUE THREAD

**Issue by priyankg3** [MetaMask/metamask-extension#5322]
**Describe the bug**
![photo_2018-09-22_19-24-38](https://user-images.githubusercontent.com/43497168/45917846-4ca6ac80-be9b-11e8-8cfa-6056674ae76c.jpg)

Recently someone buy coins in trade but neither tokens deduct in wallet nor eth amount transferred . But in trades I can easily see that trade executed .. infact in order book I can see also that my tokens decreased because someone buy that.
Eth don't come as I see in forkdelta.. and my 288897.369 token as it as. If someone buy 24270.748 from my order.. it should be deduct.. . But in order book it's showing deduct. i didnt see my 0.364 eth in forkdelta
Check the image. 
**To Reproduce**
Steps

**Comment by bdresser** [comment]
hey @priyankg3 - looks like forkdelta shipped a fix for this issue [here](https://github.com/forkdelta/classic-frontend/pull/175). Closing for now, but please let us know if you're still having trouble.
