### ISSUE TITLE
`this.getKeyringClassForType(...)` is not a constructor

### ISSUE THREAD

**Issue by cryptogoth** [MetaMask/metamask-extension#5338]
**Describe the bug**
In the new version of Metamask chrome plugin, logging in with your password gives a red error message below the password blank that says
`this.getKeyringClassForType(...) is not a constructor`

**To Reproduce**
1. Have an existing Metamask account. Upgrade metamask pluging.
2. Click the Metamask chrome fox icon in the plugin toolbar.
3. Enter in password
4. See error beneath password blank.

**Expected behavior**
I expected Metamask to unlock its vault and show me the default account's balance, as it's normal function.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/148553/45977608-22c6c480-c018-11e8-98cd-e9fe0c247e56.png)

**Browser details (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser Chrome
 - MetaMask Version 4.11.0
 - New / Beta UI

**Comment by bdresser** [comment]
@cryptogoth any errors in the UI or background consoles? 

For UI console, right click on the extension and click `Inspect`

For background console, head to `chrome://extensions` and click `Background page`

You sure you're using the correct password? If you're urgently stuck you can head to our [releases page](https://github.com/MetaMask/metamask-extension/releases), download 4.9.3, and try there. 

cc @tmashuang

**Comment by danfinlay** [comment]
Question: did you briefly get the version with Ledger support and then set up a Ledger with MetaMask? We had to roll back that feature temporarily and I could  imagine that causing this. If that sounds familiar, you will probably need to reinstall to fix this. Make sure you have your seed phrase backed up first.

**Comment by danfinlay** [comment]
It sounds like one person had this, but was able to get around it simply by closing the meta-mask pop up and opening it again, and trying again. Does that work?

**Comment by nataouze** [comment]
I have the same issue. Closing the popup works, but the problem also happens when trying to export the private key, without possibility to make it work. I tried to install 4.9.3 but it didn't find the existing accounts.

**Comment by cryptogoth** [comment]
Exiting the browser and restarting it appeared to fix the problem. I didn't
get to check either console in time.

**Comment by WXTux** [comment]
Same issue. I had set up a Ledger with Metamask, so this is probably an explication...
The connection with Ledger does not work anymore with 4.11.0 :(

**Comment by brunobar79** [comment]
We're rolling out a new version v4.11.1 today that will fix the issue and re-introduce Ledger support.
Sorry about that!

**Comment by sharonbk** [comment]
You scared me.
Hope that it will be fixed soon
Does the seed for the metamask is the same for all of the accounts on the Metamask?
