### ISSUE TITLE
I successfully connected my ledger nano to MM, but updated contents of the wallet do not appear in the UI of Chrome plugin

### ISSUE THREAD

**Issue by brentxu** [MetaMask/metamask-extension#5339]
**Describe the bug**
I connected my ledger Nano to metamask.  

Switched to Legacy (MEW/My Crypto)

Selected a account to unlock - call this Account A

I add 0.05 ether to Account A:  0x128C1A6F00f1c6C779f93eD129d817761e9CF42a

The 0.05 ether does not appear in Account A in the MM chrome plugin UI or the browser tab when you select to view account in browser

I replicated this error again using the same Ledger Nano

**To Reproduce**
1. connected ledger Nano to metamask.  
2. Switch to Legacy (MEW/My Crypto)
3. Selected a account to unlock
4. add ether to account from another account in MM
5. after transaction is submitted and confirmed on etherscan, look at the account on the MM chrome plugin UI.  The ether does not appear in the account

**Expected behavior**
I expected the ether to appear on the account in the MM chrome plugin UI and browser tab.
**Screenshots**

I tried adding ether to another account.  Encountered the same problem:
 0xdf9A54333C429D472701b3941eB96221D537bCd0

![image](https://user-images.githubusercontent.com/18404104/45980313-a6d07a80-c01f-11e8-89c8-a243d89fc25f.png)

**Browser details (please complete the following information):**
 - OS: [e.g. iOS] MacOS high sierra 10.13.4
 - Browser [e.g. chrome, safari] Chrome
 - MetaMask Version [e.g. 4.9.0] 4.10.0
 - Old UI or New / Beta UI? New 

**Additional context**
I pinged about this on slack.

**Comment by brunobar79** [comment]
This looks like it's related to #5341 where we stop getting updates from the blockchain. Also could be related to #5174

**Comment by bdresser** [comment]
closing in favor of https://github.com/MetaMask/metamask-extension/issues/5174

thanks for the help debugging @brentxu
