### ISSUE TITLE
Cannot connect ledger nano s

### ISSUE THREAD

**Issue by roadh0use** [MetaMask/metamask-extension#5343]
clicking on connect to hardware wallet opens up a new tab. but the only option to choose from is trezor.
here is a screenshot https://imgur.com/iaZ0k2J

**Comment by brunobar79** [comment]
@roadh0use  which version are you using?  This feature (Ledger support) wasn't released to the public yet but you can get it by building our develop branch

**Comment by roadh0use** [comment]
I'm honestly not sure which version I'll check tomorrow when I'm by my computer. It's just the one off the chrome store. Strange thing is, is that it worked yesterday when I tried it. It showed both ledger and trezor on that screen

**Comment by v-six** [comment]
@brunobar79 Ledger support was introduced with 4.10.0 7 days ago. 
But it has been reverted for a unknown reason on the last 4.11.0 deployed 15 hours ago :(

**Comment by WXTux** [comment]
Same issue here. Ledger connection was working until yesterday but does not work with 4.11.0 anymore :(

**Comment by brunobar79** [comment]
@v-six  @WXTux  @roadh0use  We're rolling out a new version v4.11.1 today that includes Ledger support. Hold tight and sorry about that!
