### ISSUE TITLE
Geth not able to mine block submitted via Metamask

### ISSUE THREAD

**Issue by jiten518** [MetaMask/metamask-extension#5344]
I am able to invoke smart contract method with web3js.
When I am calling the same contract method with the above data using metamask, its submiting transaction to my local ethereum network. But that transaction is not mining. Metamask is working for me the day before yesterday. Now I am not able to send transaction normal Eth transfer using metamask.  Even though I am giving updated latest gas price before submitting the transaction.

**Browser details :**
 - OS: Mac
 - Browser [Chrome]
 - MetaMask Version 4.11.0
 - Old UI or New / Beta UI?

**Comment by bdresser** [comment]
@jiten518 could you please share some slightly more detailed reproduction steps? That will help us address this more quickly.

Might be related to #5174

**Comment by tabcat** [comment]
i think i have same issue, when i try to send tx with metamask to my local geth-rpc it hangs but when i use ganache works fine. this just started recently

**Comment by tmashuang** [comment]
Closing this issue, with lack of information as how the local geth is being initiated, connecting, and the details of the tx/contract interaction. If you have additional information pls open a new issue with adequate information to better debug/reproduce/solve this issue.
