### ISSUE TITLE
Transaction Details Improvements

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5355]
A couple notes on the new tx details views:

- I kinda think the "speed up" and "cancel" buttons should be visible on the main tx cell, even without clicking into the tx, since many of our users are conditioned to think clicking will take them away to etherscan.

- Clicking "speed up" should close the tx details modal.

Other than that:

Omg I love this feature.

**Comment by bdresser** [comment]
@danfinlay i totally agree

having "speed up" close the modal seems mandatory for 4.12. upgrading those two buttons to the main tx view can wait I think? @alextsg

**Comment by bdresser** [comment]
closing this and making two separate issues

speed up / modal https://github.com/MetaMask/metamask-extension/issues/5373

increasing speed up / cancel visibility https://github.com/MetaMask/metamask-extension/issues/5374
