### ISSUE TITLE
Metamask Electron Extension

### ISSUE THREAD

**Issue by EddieOne** [MetaMask/metamask-extension#5365]
**What problem are you trying to solve?**
A lot of people are making dapps or in my case a game browser. Electron is the most advanced here. We could use an easy solution to get metamask in these applications.

**Describe the solution you'd like**
It's pretty easy to get the Metamask extension in chromium via https://www.npmjs.com/package/electron-devtools-installer

then we can open it like so

```
metamaskPopup = new BrowserWindow({
  title: 'MetaMask',
  width: 360,
  height: 520,
  type: 'popup',
  resizable: false
});
var appPath = app.getPath('userData');
var metaMenu = path.join('file://', appPath, '/extensions/', METAMASK_ID, '/popup.html');
```

**Additional context**
![image](https://user-images.githubusercontent.com/1835156/46060277-debee700-c11f-11e8-9180-12aef38eca65.png)

**Comment by whymarrh** [comment]
From the looks of it, Electron doesn't support Chrome extensions<sup>[\[1\]](
https://github.com/electron/electron/issues/1498#issuecomment-96995155)</sup> so there isn't much we can do here.

**Comment by EddieOne** [comment]
I read somewhere that Brave had to mock some api in their electron fork. It
must be possible, just not user friendly.

**Comment by DavidAmunga** [comment]
Found this awesome [repo ](https://github.com/SwapyNetwork/electron-metamask-boilerplate) which is a fork of Muon maintained by Brave. Might give it a try.

**Comment by vm06007** [comment]
so how to connect metamask with Remix Desktop IDE?

**Comment by iousin** [comment]
> so how to connect metamask with Remix Desktop IDE?

Same here please is this possible?

**Comment by claudioantonio** [comment]
Hey @iousin , I think It would be better to create an specific issue for You need. 😉
