### ISSUE TITLE
Adding Custom RPC unexpected behavior

### ISSUE THREAD

**Issue by estebanmino** [MetaMask/metamask-extension#5381]
**Describe the bug**
When adding Custom RPC there is an unexpected behavior.

1. When adding an invalid RPC URI, error message stays there even when that view is opened again.
![image](https://user-images.githubusercontent.com/12115171/46156831-c13d6a80-c250-11e8-9914-24abef2c43b5.png)

2. When adding a correct RPC, the view stays the same way without any notification that this successfully finished. I'd expect redirect to main view.

**To Reproduce**
1. Open settings and add invalid Custom RPC URI, you'll get an error message.
2. Close it, open it again and that warning is still there even though the RPC URI is not there anymore.
3. Now add right RPC URI, there is no redirection nor message saying that it was added successfully.

**Expected behavior**

1. I'd expect that error message is cleared.
2. I'd expect redirect to main view or any message confirming the addition.

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - MetaMask Version 4.11.1
 - New / Beta UI?

**Comment by bdresser** [comment]
Yea @estebanmino this behavior is a little wonky. Let's wait til #5134 is merged in, since it edits this form heavily, then revisit.

**Comment by whymarrh** [comment]
This is something we can address now that the custom RPC code has settled down a bit

**Comment by bdresser** [comment]
handled in https://github.com/MetaMask/metamask-extension/issues/6209
