### ISSUE TITLE
Implement new signing UI

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5388]
We support the new spec, now we need to update the designs to match our UI. Picking up from #4752, @cjeria's WIP is here:

![image](https://user-images.githubusercontent.com/1016190/46171677-0f08a180-c256-11e8-8861-15143cf554d4.png)

still need to
* de camel-case, so the categories/keys are very legible
* loosen up formatting a bit to still show the nested structure of the message without looking like code (see below)

<img width="280" alt="format" src="https://user-images.githubusercontent.com/1016190/46171806-85a59f00-c256-11e8-8ed0-40ea0f7c24be.png">

**Comment by cjeria** [comment]
In attempt to make this more human-readable, here are a couple of options for displaying signature request data @bdresser @omnat 

Simple version
![image](https://user-images.githubusercontent.com/597770/48228492-51ec8780-e373-11e8-80ba-6385bf2f5f3d.png)

And a more message-like presentation style
![image](https://user-images.githubusercontent.com/597770/48228434-28336080-e373-11e8-9a02-4801f033b9f6.png)

Info tooltip with more context
![image](https://user-images.githubusercontent.com/597770/48226998-18b21880-e36f-11e8-9e47-9e3f94434692.png)

**Comment by bdresser** [comment]
these look great @cjeria! like them both, slightly prefer how sophisticated the second looks.

I like that the original mocks had an affordance for expanding / collapsing a section. It might be the case that apps suggest huge blobs of data, in which case it might be useful to collapse some sections. If we see that as a trend, we could arbitrarily select a depth to auto-expand (like three objects deep) and then leave everything beyond that collapsed.

I'm not sure that messages will have a title or header (where you say `Message` in the first, and `Cryptokitties` in the second). It's possible some messages will be wrapped by a "title" type thing, but not guaranteed. Maybe just remove the second "Message" title in the first look?

**Comment by tmashuang** [comment]
As #6891 has been merge closing this issue thread. Any iteration of this should be opened in a new issue thread.
