### ISSUE TITLE
npm run mock deprecated ? Alternative to perform fast UI prototyping

### ISSUE THREAD

**Issue by santteegt** [MetaMask/metamask-extension#5389]
**Describe the bug**
If I want to perform some changes on the metamask UI, which is the best alternative to dev/test locally without rebuilding the whole plugin? I tried using the `npm run mock` but I'm getting some errors, besides it was reported that it hasn't been maintained for a while.

**To Reproduce**
1. npm run mock

**Expected behavior**
Getting `undefined` errors in some state properties in states.js. Then, get more errors for not found components.

**Comment by bdresser** [comment]
hey @santteegt - sorry to say that our dev tools for fast UI work are not super sophisticated at this point. We do need to re-invest in better tooling but haven't gotten around to it.

The best development flow at this point is to use `npm start`. You will have to log in to the extension after each file change.

See https://github.com/MetaMask/metamask-extension/issues/4768 for a little more detail.
