### ISSUE TITLE
Exporting private key of imported account not working

### ISSUE THREAD

**Issue by Magicking** [MetaMask/metamask-extension#5390]
**Describe the bug**
Exporting the private key of an imported account result in exporting the private key of the first non-imported account instead of the selected imported account

**To Reproduce**
1. Click on Metamask Icon
2. Select desired imported account
3. Go to export private key frame
4. Verify that the first input match the account
5. Enter password
6. Watch the address of the account change to first non-imported account
7. Private key is of the first non-imported account

**Expected behavior**
Export the private key of the desired account

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser Version 69.0.3497.100
 - MetaMask Version 4.11.1
 - Beta UI

**Additional context**
There is no error displayed whatsoever, I almost deleted an account irreversibly while thinking the private key was in clipboard.

**Comment by tmashuang** [comment]
Try using the local MetaMask password on step 5.

**Comment by Magicking** [comment]
After somehow corrupting my configuration, I updated to version 4.12.0 and the problem did not showed up.
