### ISSUE TITLE
Contract.prototype.methods[#METHOD_NAME](...args).send(data) does not resolve a promise since 4.12

### ISSUE THREAD

**Issue by pr0fedt** [MetaMask/metamask-extension#5391]
First call of this function causes MetaMask to do a GET reguest to https://api.infura.io/v1/jsonrpc/kovan/eth_subscribe?params=%5B%22newHeads%22%5D
that returns 400 error and it rejects the promise

After that all consequtive send requests to any method do not neiter resolve nor reject the promise

https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#methods-mymethod-send (return value)

**Comment by tmashuang** [comment]
Could we get the Contract/Dapp/Snippet? So I can try to debug from my side. Would like to curl the contract method and test other networks to see if it is consistent with MetaMask/Infura/Contract. Meanwhile, ill try some dummy Contract in the meantime to try to reproduce.

**Comment by pr0fedt** [comment]
https://kovan.nitrogen.network for kovan test net
https://platform.nitrogen.network for mainnet

**Comment by tmashuang** [comment]
> https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#methods-mymethod-send (return value)

Currently, web3.1.0 methods are not supported.

**Comment by bdresser** [comment]
see https://github.com/MetaMask/metamask-extension/issues/3639
