### ISSUE TITLE
Transaction with Ledger Fails: 'Transaction 54 Failed! [object Object]

### ISSUE THREAD

**Issue by WXTux** [MetaMask/metamask-extension#5392]
I have tried to buy artworks on Superrare and on Rare Art Labs with my Ledger Nano S account connected to Metamask.
But when I confirm the transaction on the Metamask pop-up window, I immediately get an error notification: **Transaction 54 Failed! [object Object]** (or **Transaction 55 Failed! [object Object]** in the last attempts).

Note that I can sign messages with these sites without any problem (I have to do this to authenticate myself), so the Metamask-Ledger connection is active. But all transactions fail as described above.

I have uninstalled and reintalled Metamask, I have restarted my laptop several times and there is no other application connected to the Ledger.

**To Reproduce**
1. Go to Site and buy item
2. Click on Confirm on the Metamask pop-up window presenting the transaction
3. Ledger does not request any confirmation
3. See immediately Chrome notification: Transaction 54 Failed! [object Object]

**Expected behavior**
I expect a request from Ledger to confirm the transaction on the device in order for the transaction to go through.

**Browser details:**
 - OS: Windows 10
 - Chrome 69.0.3497.100
 - MetaMask Version 4.12.0
 - New UI

**Comment by deearrdev** [comment]
@WXTux Hey there, you might want to check that the `Contract data` setting of the Ethereum app is set to active. 

More details here: https://support.ledgerwallet.com/hc/en-us/articles/115005200009-Set-up-and-use-MyEtherWallet

**Comment by WXTux** [comment]
@deearrdev Thank you! This was the issue. Transactions go through when the Contrat data setting of the Ethereum app is set to 'Yes'.
