### ISSUE TITLE
MetaMask just started using 100gb+ of data per day

### ISSUE THREAD

**Issue by jmooo** [MetaMask/metamask-extension#5398]
**Describe the bug**
This was kind of tough to track down, I could see a consistent 800kbp/s incoming & outgoing in my router 24hrs a day, but macOS activity monitor didn't show anything unusual, and Chrome Task Manager didn't show much data activity either. Finally after force-quitting the MetaMask extension, data usage on my network dropped to single-digit kbps. Uninstalling MetaMask has kept the issue from recurring.

I've had MetaMask installed on Chrome, which itself syncs across a macOS Mojave install and a Windows 10 install, for 2 months. Only within the last 2 days have I been getting warnings from my ISP for a crazy amount of data transfer.

The things that have changed in the last few days:
* I upgraded macOS to Mojave 10.14
* On Chrome for Windows 10 I _disabled_ the flag Account consistency: chrome://flags/#account-consistency, because Chrome is having a problem staying logged in and syncing on my Windows machine, and disabling that feature was recommended in a forum by Google and it has solved that specific problem.
* MetaMask updated on September 27th.

Wether my MetaMask issue is related to any of those 3 things, I do not know. But the excess data using was coming from the macOS chrome extension, *not* the Windows extension.

Sorry, not a ton to go on but figured I better report the behavior in case anyone else comes looking with this same problem.

**Browser details (please complete the following information):**
 - OS: macOS 10.14 Mojave, Windows 10
 - Browser: Chrome 69 (both machines)
 - MetaMask Version: 4.12.0
 - Old UI or New / Beta UI? Beta UI

**Comment by bdresser** [comment]
thanks for the report @fxer if this happens again, or if you can identify what causes it, please let us know.

may relate to #4074

**Comment by joshfraser** [comment]
Metamask has become so slow to the point of being almost unusable for me after upgrading to Mojave. It was working fine this afternoon before I upgraded.

**Comment by whymarrh** [comment]
@joshfraser were you using the same MetaMask version before and after the upgrade?

**Comment by joshfraser** [comment]
Correct

**Comment by danfinlay** [comment]
I assume this is no longer an issue? Any recurrence? Would we be ok to close this?

**Comment by whymarrh** [comment]
@danfinlay I think we can close this for now, pending reproducible reports on the latest version
