### ISSUE TITLE
Allow method to add custom RPC nicknames

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#540]
When adding a custom RPC URL, we could add a nickname field, and then keep that RPC in the user's menu.

This would be really nice for people who maybe run a test blockchain they like to use, like the Consensys Testnet, or even just a household blockchain.

**Comment by kumavis** [comment]
diggit!

**Comment by flyswatter** [comment]
Related to #541

**Comment by egalano** [comment]
I'd really like to have this :) 👍  for next release please :)

**Comment by flyswatter** [comment]
Would we want to also show the URL in the menu, if there's a nickname? I guess there's no other way to see what you're connecting to.

**Comment by egalano** [comment]
Im thinking maybe the nickname can be a in a small label off to the right side? Or maybe as the hover tooltip. My use case being I have several RPC endpoints that are IP addresses and not domains so having some labeling on what each one is is useful.

**Comment by ekreda** [comment]
This issue is happening also on the current "old" UI too!
Once I add more the one RPC url - can't find them anymore...

**Comment by bdresser** [comment]
in production as of 4.16
