### ISSUE TITLE
Can't get balance or send amount to ERC20 tokens

### ISSUE THREAD

**Issue by LavanyaDR** [MetaMask/metamask-extension#5401]
Hi,

I integrate metamask on my site but I need to send amount and also check balance on ERC 20 token using metamask but nothing works on me .I try diffrent coding and methos on WEB3

Kindly provide the executed code to me.

Here is my code:

> var contractadd = "0xd26114cd6ee289accf82350c8d8487fedb8a0c07";
> 
> $.getJSON( "https://api.etherscan.io/api?module=contract&action=getabi&address="+contractadd, function( data ) {
>   var abivalue = (data.result);
> 
>     
>     if (typeof web3 !== "undefined") {
>       // Use Mist/MetaMask's provider
>       window.web3 = new Web3(web3.currentProvider);
>     } else {
>      alert("Metamask extension not added on your browser");return false;
>       
>    
>     }
> 
> 
> 
>   const contract_address = contractadd;
>       
> 
> 
> var userAddress = '0x12A922212C20EFe9b8d5799CC67C619F9F1617b9';
> var amount = 0.2;
>          alert();  
> web3.eth.getBlock('latest',function(err,getBlock) {
> 
> web3.eth.getGasPrice(function(err, getGasPrice) {
>   
>  
>  web3.eth.getAccounts(function(err, accounts){
> 
> 
> 
>       if (err != null) {
>          console.log(err)
>       }
>       else if (accounts.length === 0) {
>          alert("Your metamask account is locked please unlock");return false;
>       }
>       else {
> 
>      
> 
>           var contractAddress  =  contractadd;
> var FromAddress    =  accounts[0];
> 
> var ToAddress      =  "hghfghfg";
> 
> var Amount         =  0.5;
> var Key          =  "";
> var host             =  "localhost";
> var port              =  "8665";
> var Amount=Amount*1000000000000000000;
>   const abi =JSON.parse(abivalue);
>   alert(abi);
> 
> 
> let contract = web3.eth.contract(abi).at(contractAddress);
> 
> 
> contract.balanceOf(FromAddress, (error, balance) => {
> 
>   contract.decimals((error, decimals) => {
> 
>     alert(balance);
>     console.log(balance.toString());
>   });
> });
>       }
> 
> 
> });
> });

})

  });

**Comment by bdresser** [comment]
hey @LavanyaDR, sounds like this would be better suited for Stack Exchange - try posting there and see if anyone can help you out!
