### ISSUE TITLE
Easily fixed UI/UX blocker: "Connecting to Unknown Network"

### ISSUE THREAD

**Issue by weijiekoh** [MetaMask/metamask-extension#5405]
If you use MetaMask to connect to a private network, stop said network and don't switch back to a mainnet or testnet, MetaMask will show an blurred screen with an infinite spinner and no obvious way to get out. However, if you click on the spinner on the top right (which is not an obvious or intuitive UI element) you can bail out and connect to another network and finally use MetaMask.

**Expected behavior**
There should be an easy way to bail out of the "Connecting to Unknown Network" screen if said network is unavailable. There should at least be some kind of timeout so that it MM doesn't just get stuck at this spinner screen, which is not ideal UX.

**Screenshots**
<img src="https://i.imgur.com/KInGObu.png" />

<img src="https://i.imgur.com/VuQmapQ.png" />

**Browser details (please complete the following information):**
 - Ubuntu Linux
 - Chrome 68
 - New UI

**Additional context**

Because MetaMask doesn't handle non-default zoom levels, the small spinner on the top right is hidden at first and one has to scroll up using the outer scrollbar. See also #5252

**Comment by bdresser** [comment]
dupes https://github.com/MetaMask/metamask-extension/issues/3776
