### ISSUE TITLE
Provider bug: eth_signTransaction throws internal error

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#5407]
```js
web3.currentProvider.sendAsync({
  method: 'eth_signTransaction',
  params: [ ... ]
}, (...args) => console.log(args))
```

 is throwing this error: `MetaMask - RPC Error: TypeError: Cannot read property 'bind' of undefined`

**Comment by bitpshr** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/2506

**Comment by kumavis** [comment]
Actually not intended to be related to #3475 
Ive managed to confuse myself with a parity rpc method similar to `eth_sendTransaction` but it doesn't wait for user approval before returning the callback, instead it exposes a few methods for querying status about the tx

**Comment by Gudahtt** [comment]
This appears to have been fixed at some point; I'm not sure when.
