### ISSUE TITLE
s avery ,im not sure what to do here but my metamask is like a minute behind when i type i cant send funds anywere just says submitted for nearly a week or so then etherscan says cannot find transaction!!! has been fine up till past few weeks its just tottally slowed down were u have to wait ages for anything to connect,could you please advise its been great up till recent i use for icos,right now i dont no what to do,thankyou

### ISSUE THREAD

**Issue by soxxxx44** [MetaMask/metamask-extension#5410]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI?

**Additional context**

**Comment by tmashuang** [comment]
Please email support [at]  metamask io.
