### ISSUE TITLE
Metamask cannot seem to connect to private testnet geth with the --dev flag 

### ISSUE THREAD

**Issue by davekaj** [MetaMask/metamask-extension#5411]
**Describe the bug**

It appears that metamask can't connect to a private network, when the private network is ran with the `geth --dev` command.

It just hangs on `Connecting to unknown network`

**To Reproduce**
Steps to reproduce the behaviour:
1. start a new geth node with the following command:
```
geth --ipcpath ~/coding-no-icloud-backup/geth-dev/geth.ipc --datadir ~/coding-no-icloud-
backup/geth-dev/ --dev console --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --rpccorsdomain "*" 
--rpcapi "eth,web3,debug"
```
2. Make a new account with `personal.newAccount()`, and import that account to metamask.
3. send ether from the coinbase account to the new account
4. Open up metamask, connect to localhost 8545, and it will hang there 

**Expected behaviour**

I would expect it to work. It is possible that not many people use this, and most of them use ganache. But we are having issues with ganache right now so we were hoping this would be a work around. 

**Browser details (please complete the following information):**
 - OS: MAC
 - Browser Chrome
 - MetaMask Version [e.g. 4.11.1
 - New UI

I think it is fine if it is not supported, --dev is kinda obsolete with ganache in place. But it would be good to have an issue about it so others can see!

**Comment by tmashuang** [comment]
Haven't tested out this out yet, but on first glance 
> --rpcaddr 0.0.0.0

This doesn't point to localhost. Maybe  omit this out and it should point to localhost by default.

**Comment by davekaj** [comment]
It works with paritys dev chain. with this command
`parity --chain dev --unsafe-expose --jsonrpc-cors="all"`

I'd recommend other users to go with this. I'll close the issue.
