### ISSUE TITLE
MetaMask always underestimates gas fee

### ISSUE THREAD

**Issue by un1t** [MetaMask/metamask-extension#5416]
When I try use default fee, suggested by MetaMask, transactions stays in pending status for very long time. Don't know exactly how long could it take, after 15-30 minutes I always raise gas fee.

So now I almost never use default MetaMask fees, because I don't like that transactions stuck. I use ethgasstation.info, usually their estimation is a bit higher, and transactions always confirms in a few blocks.

**Comment by danfinlay** [comment]
I have a PR to increase our target gas price here: #5359.

**Comment by danfinlay** [comment]
Closing as addressed by #5359
