### ISSUE TITLE
Unable to sign structures following the EIP712 proposition

### ISSUE THREAD

**Issue by Amxx** [MetaMask/metamask-extension#5417]
I am having issues with the metamask implementation of EIP712. There are already a few issues talking about parameters orders but my issue is different.

**Context**
Client-side javascript (web page) using web3.js and metamask to populate the current provider.
I want to sign a typedStruct using the mechanism specified in [EIP-712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md).

**What I manage to do**
I manage to sign a simple key-value representation without a domain using the following code:

```
const msgParams = [
	{ name: "owner", type: "address", value: user },
	{ name: "value", type: "uint256", value: 100  },
];
web3.currentProvider.sendAsync({
	method: "eth_signTypedData",
	params: [ msgParams, user ],
	from: user,
}, (err, result) => {
	console.log(result);
	//...
});
```

This prompt a popup as expected and I can handle the signature in the callback.

**What I am not managing to do (bug)**
I should be able to sign typedData as follows

```
const typedData = {
	types: {
		EIP712Domain: [
			{ name: "name",    type: "string"  },
			{ name: "version", type: "string"  },
			{ name: "chainId", type: "uint256" },
		],
		CustomType: [
			{ name: "owner",   type: "address" },
			{ name: "value",   type: "uint256" },
		],
	},
	primaryType: "CustomType",
	domain: {
		name:    "test domain",
		version: "0.0.1-alpha",
		chainId: 1,
	},
	message: {
		owner: user,
		value: 100,
	},
};
web3.currentProvider.sendAsync({
	method: "eth_signTypedData_v3",
	params: [ JSON.stringify(typedData), user ],
	from: user,
}, (err, result) => {
	console.log(result);
	// ...
});
```
But I get error:

- Using `method: "eth_signTypedData_v3"`, I get `RPC Error: Internal JSON-RPC error`.
- Using `method: "eth_signTypedData"`, I get `RPC Error: AssertionError: Data should be an array`.
- I have tried with and without `JSON.stringify`

**To Reproduce**
Run the attached file in a browser (without the .txt additional extention)
[index.html.txt](https://github.com/MetaMask/metamask-extension/files/2442231/index.html.txt)

**Details**
- Archlinux
- Firefox & Chrome
- Metamask 4.9.2 (both for firefow and chrome)

I have noticed the bug with metamask linked to a ganache-cli, but this should not have an impact, and the bug also happens when linked to ropsten

### EDIT: SOLUTION

the error was not in the code, but in metamask version. I tried with a custom install of 4.12 and it worked immidiatly. I wish firefox/chrome would update metamask better :/

**Comment by bitpshr** [comment]
Hi @Amxx, thanks for filing such a detailed issue.

Based on the code you provided, it looks like your parameters for `eth_signTypedData_v3` are reversed: rather than `[ JSON.stringify(typedData), user ]`, it should be `[ user, JSON.stringify(typedData) ]`.

**Comment by Amxx** [comment]
@bitpshr order is not the issue here. I've tryed both and the issue comes from somewhere else

**Comment by Amxx** [comment]
I found the issue and updated the post.

**Comment by tiennt0212** [comment]
Respect you, I tried your code and it worked :sunflower:
