### ISSUE TITLE
Transaction details look blurred. Or only me?

### ISSUE THREAD

**Issue by pmaojo** [MetaMask/metamask-extension#5424]
**Describe the bug**
Transaction details look blurred.

**To Reproduce**
1. Open the extension widget on Chrome.
2. Click on one transaction
3. Do you notice the blur effect?

**Expected behavior**
Texts not blurred.

**Screenshots**
![captura de pantalla 2018-10-04 10 16 45](https://user-images.githubusercontent.com/411551/46464793-1b917a80-c7bf-11e8-9708-931c207ab8aa.png)

**Browser details (please complete the following information):**
 - OS: Mac
 - Chrome

**Comment by danfinlay** [comment]
This does look blurry in your screenshot. Could you share the exact versions of Mac OS and Chrome you are using?

**Comment by bdresser** [comment]
@pmaojo are any other parts of the UI blurry in a similar way?

@alextsg could you take a look?

**Comment by pmaojo** [comment]
I only noticed it on that component.

**Comment by alextsg** [comment]
@pmaojo Are you maybe using some extension to always show a scrollbar? I noticed from the screenshot that it looks a little squished because of the scrollbar.

**Comment by alextsg** [comment]
@pmaojo Can you please verify? Thanks.

**Comment by pmaojo** [comment]
It is still wrong. i found the problem.
No the css styling of the element is like:
![captura de pantalla 2018-10-18 22 42 25](https://user-images.githubusercontent.com/411551/47186051-3d464200-d327-11e8-8d2f-71b5d913aad0.png) if Translate3D is removed:
![captura de pantalla 2018-10-18 22 42 17](https://user-images.githubusercontent.com/411551/47186074-48996d80-d327-11e8-93ff-0c18aff50ca7.png)
it looks good, no blur.

**Comment by alextsg** [comment]
@pmaojo We're updating the transaction details in the next release to not appear as a modal (for the extension view) and instead behave in the same way as the full-screen view (where the details slide down). Closing the issue as this should no longer apply. Thank you though!
