### ISSUE TITLE
ETH not showing in metamask

### ISSUE THREAD

**Issue by harshalsp7** [MetaMask/metamask-extension#5429]
I sent 2 ethereums from exchange to metmask address 0x14BexZMoP1gqvSbLZSfYigjUvfcXkroScK041E850CAd660 
Transaction is successful past 3 hours but still metastock does not show up my ethereums.
Please look in to it. Really urgent
Thanks

**Comment by danfinlay** [comment]
Yeah, this is not a valid MetaMask address. MetaMask addresses are hexadecimal (0-9 and A-F). This address has letters including x, Z, M, etc. It appears to be a base62 address, which we do not provide.

Is it possible you copied down the wrong address?

Closing until there is some follow-up. Feel free to contact support@metamask.io
