### ISSUE TITLE
Expose Metamask version in injected web3

### ISSUE THREAD

**Issue by sparrowDom** [MetaMask/metamask-extension#5433]
**What problem are you trying to solve?**
Metamask 4.12.0 introduced breaking changes where the DApp using it could not detect transaction confirmation. This behaviour affects the user experience badly in our application. Aside from detecting that it was Metamask who injected the web3 ( https://github.com/MetaMask/metamask-extension/issues/1158 ) we have no way of knowing what version of Metamask that was. It would be so great if we could implement a check in the DApp to prompt users to upgrade Metamask if they have an outdated version. 

**Describe the solution you'd like**
Adding Metamask version information in injected `web3.currentProvider` would be really great.

**Comment by estebanmino** [comment]
Hi @sparrowDom, you can get MetaMask version doing `web3.version.getNode(function(er,res) {console.log(res)})`. Let me know if this is working for you.

**Comment by sparrowDom** [comment]
That works perfectly thanks!
