### ISSUE TITLE
[Not reliably reproducible?] Repeated "intrinsic gas too low" and "nonce too low" errors

### ISSUE THREAD

**Issue by nmclrn** [MetaMask/metamask-extension#5435]
On Thu 4 Oct, multiple members of the ConsenSys/TrSet team independently observed Rinkeby transactions failing with "intrinsic gas too low" and "nonce too low" errors. There was no obvious pattern. Different accounts and contract calls were involved in different failures - though all failing transactions were contract calls rather than value transfers. MM v4.13

We believe that in all cases we let MetaMask estimate the gas limit/nonce for all transactions (a layman's reading of the state logs confirms this). For all erroneous transactions, MetaMask set the gas limit to 21000, which is intrinsically too low for the contract call we were attempting.

I've attached one relevant state logs file showing:
- 2 instances of a "nonce too low" error (2018-10-04 09:42:16 and 2018-10-04 10:07:20; both times UTC)
- 3 instances of the "intrinsic gas too low" error (2018-10-04 10:04:43, 2018-10-04 10:30:12 and 2018-10-04 15:17:36; all times UTC)

I'm not sure whether these two different errors are related, hence one issue.

We've not seen these errors repeat today. We saw quite a lot of infura issues yesterday on Rinkeby, so we have dared to speculate that an infura availability/lag issues might have caused bad gas estimates/nonces. But that's purely speculation on our part and I don't know whether it's realistic.

[MetaMask State Logs.json.txt](https://github.com/MetaMask/metamask-extension/files/2451332/MetaMask.State.Logs.json.txt)

OS/Browser/MetaMask version details to follow later once I collect them from the team.

Here are the nonceDetails sections of the two "nonce too low" transactions in the attached state logs file:

        "nonceDetails": {
          "local": {
            "details": {
              "highest": 751,
              "startPoint": 749
            },
            "name": "local",
            "nonce": 751
          },
          "network": {
            "details": {
              "baseCount": 749,
              "blockNumber": "0x2f4e58"
            },
            "name": "network",
            "nonce": 749
          },
          "params": {
            "highestLocallyConfirmed": 749,
            "highestSuggested": 749,
            "nextNetworkNonce": 749
          }
        },

------------

        "nonceDetails": {
          "local": {
            "details": {
              "highest": 751,
              "startPoint": 749
            },
            "name": "local",
            "nonce": 751
          },
          "network": {
            "details": {
              "baseCount": 749,
              "blockNumber": "0x2f4e58"
            },
            "name": "network",
            "nonce": 749
          },
          "params": {
            "highestLocallyConfirmed": 749,
            "highestSuggested": 749,
            "nextNetworkNonce": 749
          }
        },

**Comment by nmclrn** [comment]
Hi Dan. That's the first thing I asked, too. I'm told these accounts are not in use elsewhere.

We were connected to "Rinkeby" in MetaMask, which I assume connects to Infura? If so, one possibility is that MetaMask is connecting to a load balanced Infura pool in which some nodes are lagging behind others. We have seen other issues with this suspected root cause this week (e.g. getBlock(x) requests coming back empty even though a lot subscription already told us about a log in block x).

**Comment by nmclrn** [comment]
We've been hitting this again over the weekend.

Once use was OS 10.13.6, Chrome, old MetaMask UI. But another user is new MetaMask UI.

Anything we can do to help with a diagnosis if it happens again?

(Worth noting that some of our transactions have a decent-sized blob of JSON in the transaction data. Seems unlikely that that is related as we've no evidence that the problem correlates with data size, but I'm scratching my head to think of things that could be construed as special or unusual.)

**Comment by bdresser** [comment]
hey folks, closing this for now – let us know if it comes up again and we can re-open.
