### ISSUE TITLE
Make UI support right-to-left languages

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5436]
**What problem are you trying to solve?**
Some languages, like Arabic (#3531), Hebrew, and Farsi (#5273) read from right to left. This affects not only text direction, but the general orientation of all UI elements: the side of a "back" arrow, the direction of that arrow, basically the whole UI would ideally be flipped vertically to support these languages.

**Describe the solution you'd like**
Ideally MetaMask auto-detects when a right-to-left language is selected, and orients its elements correctly, in an easily reusable way across the UI.

**Comment by brad-decker** [comment]
https://github.com/MetaMask/metamask-extension/pull/7072 -- believe this was resolved when this merged. @Gudahtt can you confirm and close issue if you agree?

**Comment by Gudahtt** [comment]
I agree - this has been implemented, and should still work as far as I know.

I'm sure there are RTL mistakes here and there still, but we can open individual issues for any such mistakes we find.
