### ISSUE TITLE
Ropsten test faucet not working

### ISSUE THREAD

**Issue by modong** [MetaMask/metamask-extension#5439]
**Describe the bug**
Ropsten faucet is not working

**To Reproduce**
1. Goto https://faucet.metamask.io/
2. Click request ether
3. see this error: 
`{"error":"[ethjs-rpc] rpc error with payload {\"id\":9931713908278,\"jsonrpc\":\"2.0\",\"params\":[{\"to\":\"0xf5e9d550c3c50364d630edb4753be404cd109121\",\"from\":\"0x81b7e08f65bdf5648606c89998a9cc8164397647\",\"value\":\"0xde0b6b3a7640000\",\"data\":\"0x\"}],\"method\":\"eth_sendTransaction\"} [object Object]"}`

**Expected behavior**
Expect to have received some testnet eth

**Browser details (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - web faucet

**Additional context**
We are launching an off-chain platform testnet that depends on metamask faucet for user testing. We would appreciate so much if you could help fix the faucet issue.

**Comment by bdresser** [comment]
@modong faucet is working fine for me, and there are lots of successful tx over the past couple days from Etherscan. You still having trouble? Can we get a screenshot?

**Comment by youssefgh** [comment]
Same issue here

**Comment by jobinjohnym84** [comment]
This is the exact error message - someone help please---

{"error":"[ethjs-rpc] rpc error with payload {\"id\":1358577249026,\"jsonrpc\":\"2.0\",\"params\":[{\"to\":\"0xce35b218f28a275457b9e7efd1257c08d201c9ec\",\"from\":\"0x81b7e08f65bdf5648606c89998a9cc8164397647\",\"value\":\"0xde0b6b3a7640000\",\"data\":\"0x\"}],\"method\":\"eth_sendTransaction\"} [object Object]"}

**Comment by pizza-r0b** [comment]
Happening to me as well

![image](https://user-images.githubusercontent.com/5282495/46919836-2ce63e00-cf9a-11e8-94b1-37e1d453b233.png)

**Comment by jobinjohnym84** [comment]
Can someone respond please? Any workaround as of now?

**Comment by jobinjohnym84** [comment]
I tried to reset my MetaMask account, created new account, rebooted Chrome. Still same issue.

**Comment by tmashuang** [comment]
Currenty, Infura is working on getting Ropsten to up to date with the Contantinople fork. In the meantime, it is recommended to use a different test network. Thanks for your patience.

**Comment by jobinjohnym84** [comment]
Thanks much for your response. Any ETA?

**Comment by bdresser** [comment]
@jobinjohnym84 no ETA yet, we'll let you know! for now, use another test network

**Comment by tmashuang** [comment]
Seems that the nodes have synced up when I tested it this morning.

**Comment by Sureshtathari** [comment]
Guys, any update on this?

**Comment by spazzyt** [comment]
Still not working, did it work from oct 2018 to feb 2019?

**Comment by bulutym74** [comment]
Same issue??Help

**Comment by aditya-citrix** [comment]
same issue here

**Comment by t4i5uKE** [comment]
I am suffering from this problem now.

**Comment by alusiu** [comment]
Same thing as the above atm.

**Comment by Lachs7** [comment]
seems the problem persists. Any updates?
![image](https://user-images.githubusercontent.com/36352796/53533876-2c21f480-3ac2-11e9-9848-c6802294ec18.png)

**Comment by truongnmt** [comment]
Due to a consensus issue with the Constantinople fork, Ropsten is currently not usable.

**Comment by Lachs7** [comment]
Awesome, thanks for letting me know.

**Comment by istabraq-iot** [comment]
Hi I have this error :
```
transactions
{"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Proxy.eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Object.eval [as apply] (LavaMoat/core/kernel:806:17)\\n at Object.eval [as apply] (LavaMoat/core/kernel:806:17)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Object.eval [as apply] (LavaMoat/core/kernel:806:17)\\n at Proxy.emit (events.js:310:20)\\n at Object.eval [as apply] (LavaMoat/core/kernel:806:17)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Object.eval [as apply] (LavaMoat/core/kernel:806:17)\"}}'"}
```

is the problem solved or go to another test network?

**Comment by megancooper** [comment]
Experiencing the same issue as @istabraq-iot

**Comment by Waheed388** [comment]
Did not receive a single test ether but now getting this error.

{"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at /www/node_modules/web3-provider-engine/subproviders/rpc.js:51:23\\n at Request._callback (/www/node_modules/web3-provider-engine/subproviders/rpc.js:53:11)\\n at Request.self.callback (/www/node_modules/request/request.js:185:22)\\n at Request.emit (events.js:310:20)\\n at Request.<anonymous> (/www/node_modules/request/request.js:1154:10)\\n at Request.emit (events.js:310:20)\\n at IncomingMessage.<anonymous> (/www/node_modules/request/request.js:1076:12)\\n at Object.onceWrapper (events.js:416:28)\\n at IncomingMessage.emit (events.js:322:22)\\n at endReadableNT (_stream_readable.js:1187:12)\"}}'"}

**Comment by drptbl** [comment]
> Did not receive a single test ether but now getting this error.
> 
> Browser: Chrome
> OS: macOS (Catalina)
> 
> {"error":"[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"message":"Too Many Requests","data":{"originalError":{}},"stack":"Error: Too Many Requests\n at /www/node_modules/web3-provider-engine/subproviders/rpc.js:51:23\n at Request._callback (/www/node_modules/web3-provider-engine/subproviders/rpc.js:53:11)\n at Request.self.callback (/www/node_modules/request/request.js:185:22)\n at Request.emit (events.js:310:20)\n at Request. (/www/node_modules/request/request.js:1154:10)\n at Request.emit (events.js:310:20)\n at IncomingMessage. (/www/node_modules/request/request.js:1076:12)\n at Object.onceWrapper (events.js:416:28)\n at IncomingMessage.emit (events.js:322:22)\n at endReadableNT (_stream_readable.js:1187:12)"}}'"}

Same issue.

**Comment by dportabella** [comment]
Experiencing the same issue as @istabraq-iot

**Comment by TheGrandNobody** [comment]
Experiencing the same issue as @dportabella 
Browser: Chrome
OS: macOS (Catalina)

**Comment by MrUke** [comment]
I'm experiencing the same issue too. Error message:
`{"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Proxy.eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\\n at Proxy.emit (events.js:310:20)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Object.eval [as apply] (LavaMoat/core/kernel:939:17)\"}}'"}`

Browser: Chrome
OS: Windows 10

**Comment by nikmindboomer** [comment]
Hi the same error is coming again and again. I have done everything. Some new ideas to solve it

Big hugs

**Comment by MrUke** [comment]
> 
> 
> Hi the same error is coming again and again. I have done everything. Some new ideas to solve it
> 
> Big hugs

In the meantime you can search for other Ropsten ETH faucets. Google it.

**Comment by nikmindboomer** [comment]
@MrUke it work!!!!
i google it and the first suggestion was de correct

[https://faucet.dimensions.network/](url)
Dimensions Cryptocurrency Faucets

THX

**Comment by Titan-C** [comment]
I just tried. Metamask connects to the page and I even see the transaction listed after requesting ETH. Yet the transaction is never broadcasted. Etherscan never finds it and I never receive it.
Other testnet faucets I tried work fine.

**Comment by GGG1998** [comment]
@Up same here problem.

**Comment by mrblanch** [comment]
Same problem.

**Comment by CrackerHax** [comment]
faucet still not working

**Comment by blocktechmc** [comment]
still not working please fix asap

**Comment by bart-antczak** [comment]
Still not working...

**Comment by ansharah-gs** [comment]
![image](https://user-images.githubusercontent.com/56068507/112325148-421c3680-8cd5-11eb-8e61-a88a139770d6.png)
still not working...

**Comment by pkshefi** [comment]
I have similar issue,

Steps to reproduce:
- got to https://faucet.metamask.io/ by tapping get ether
- Click request ether
- see this error:

Error: 500 {"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Request.eval [as _callback] (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Request.emit (events.js:315:20)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Request.emit (events.js:315:20)\\n at IncomingMessage.eval (/www/node_modules/request/request.js:1077:12)\\n at Object.onceWrapper (events.js:421:28)\\n at IncomingMessage.emit (events.js:327:22)\\n at endReadableNT (internal/streams/readable.js:1327:12)\"}}'"}

**Comment by evolving-zd** [comment]
Same issue

**Comment by evolving-zd** [comment]
> Same issue here.
> However, I found I can use this website to send me test eth.
> https://faucet.ropsten.be/

This works for me. Just note, it may take a while to receive 1 eth from the sender.

**Comment by liam-ot** [comment]
same issue as @istabraq-iot

**Comment by kyasbal-1994** [comment]
I have same issue. I think we have enough reports to start considering reopen this issue.

**Comment by vinstercrypto** [comment]
Having issues as well, tried reset, restart, and different browsers. No luck. 

![image](https://user-images.githubusercontent.com/81456687/125201165-e05bea00-e23b-11eb-94d3-cce817c6eb80.png)

**Comment by vinstercrypto** [comment]
> Having issues as well, tried reset, restart, and different browsers. No luck.
> 
> ![image](https://user-images.githubusercontent.com/81456687/125201165-e05bea00-e23b-11eb-94d3-cce817c6eb80.png)

Did some digging and found this link:  https://ipfs.io/ipfs/QmU7Ecw419si7D8gq4tB3qVBraitBGeVrsMESHBMD1DnCb/

I was able to get .5eth, it might work for you.

**Comment by xinfangwu** [comment]
I have same issue. 
I found this link, but not sure if it works.
https://faucet.dimensions.network/

**Comment by AlirezaAsadi** [comment]
Still not working!

**Comment by AbhinavXT** [comment]
Tried Test Faucet given in extension
Site: https://faucet.metamask.io/
No Luck
![Screenshot from 2021-08-25 20-16-46](https://user-images.githubusercontent.com/56548922/130813106-bd53ab59-6338-4c76-b270-a47121517c70.png)

**Comment by Js-full-stack-dev** [comment]
Error: 500 {"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Request.eval [as _callback] (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Request.emit (events.js:315:20)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Request.emit (events.js:315:20)\\n at IncomingMessage.eval (/www/node_modules/request/request.js:1077:12)\\n at Object.onceWrapper (events.js:421:28)\\n at IncomingMessage.emit (events.js:327:22)\\n at endReadableNT (internal/streams/readable.js:1327:12)\"}}'"}

**Comment by A1ve5** [comment]
FYI: https://faucet.ropsten.be/ worked for me on Ropsten Test Network.

**Comment by jeanmaried** [comment]
Was having problems across different faucets. Eventually just switched on a VPN and it started working again. Hope this helps someone.

**Comment by fahimermo** [comment]
Same issue

**Comment by pokokichi13** [comment]
Use this link
https://faucet.ropsten.be

**Comment by Eganizm** [comment]
It's inexcusable that this problem has existed for at least three years. I was unable to receive test ETH in both the Ropsten and Goerli test networks across a half-dozen browsers. I did everything I could think of to troubleshoot the issue and followed the advice provided in this thread. Given that Metamask is touted as the standard browser extension wallet by countless websites, videos, online courses, and many others, this glaring flaw needs to be fixed.

**Comment by Eganizm** [comment]
It's inexcusable that this problem has existed for at least three years. I was unable to receive test ETH in both the Ropsten and Goerli test networks across a half-dozen browsers. I did everything I could think of to troubleshoot the issue and followed the advice provided in this thread. Given that Metamask is touted as the standard browser extension crypto wallet by countless websites, videos, online courses, and many others, this glaring flaw needs to be fixed.

**Comment by mohammadmadadi** [comment]
> It's inexcusable that this problem has existed for at least three years. I was unable to receive test ETH in both the Ropsten and Goerli test networks across a half-dozen browsers. I did everything I could think of to troubleshoot the issue and followed the advice provided in this thread. Given that Metamask is touted as the standard browser extension crypto wallet by countless websites, videos, online courses, and many others, this glaring flaw needs to be fixed.

Yes bro I have same problem and I do not know what is next step ??

**Comment by MilanPoznan** [comment]
Same issues here. I'm trying for a few days to get one, but no luck...

**Comment by mohammadmadadi** [comment]
> Same issues here. I'm trying for a few days to get one, but no luck...

Guys, I founded a solution for that !
try that below link:
https://faucets.chain.link/rinkeby
Good wishes for all in 2022

**Comment by glitterlip** [comment]
other  websites 
https://faucet.metamask.io/
https://faucet.ropsten.be/
https://faucet.dimensions.network/
https://faucet.kyber.network/（仅限GitHub用户）
https://ipfs.io/ipfs/QmVAwVKys271P5EQyEfVSxm7BJDKWt42A2gHvNmxLjZMps/
http://faucet.bitfwd.xyz/

**Comment by Eganizm** [comment]
Wanted to clarify that my last post wasn't about Metamask specifically, but the test networks more generally (although you should avoid Metamask anyway due to their sketchy privacy agreement, which mentions the use of Google Analytics among other concerning practices). If you had an issue with the test network pages that Metamask linked to, you'll likely have the same issue with other wallets. I'm not sure what the root of this problem is yet.

**Comment by Eganizm** [comment]
Wanted to clarify that my last post wasn't about Metamask specifically, but the test networks more generally (although you should avoid Metamask anyway due to their sketchy privacy agreement, which mentions the use of Google Analytics among other concerning practices). 

If you had an issue with the test network pages that Metamask linked to, you'll likely have the same issue with other wallets. I'm not sure what the root of this problem is yet. Also, thanks for the links - @glitterlip, but none of them worked for me.

**Comment by Eganizm** [comment]
I wanted to clarify that my last post wasn't about Metamask specifically, but the Ropsten and Goerli test networks more generally (although you should avoid Metamask anyway due to their sketchy privacy agreement, which mentions the use of Google Analytics among other concerning practices).

Based on my experience, the problem is the Ropsten and Goerli networks, so none of the links that @glitterlip provided worked for me. I did, however, send test ETH to my Brave Wallet through the Rinkeby Test Network using the link that @mohammadmadadi provided. Thanks, Mohammad!

**Comment by Eganizm** [comment]
The problem appears to be the Ropsten and Goerli networks and isn't limited to Metamask users (although you should avoid Metamask due to their sketchy privacy agreement, which mentions the use of Google Analytics among other concerning practices).

With that being said, none of the links that @glitterlip provided worked for me. I did, however, send test ETH to my Brave Wallet through the Rinkeby Test Network using the link that @mohammadmadadi provided. Thanks, Mohammad!

**Comment by Eganizm** [comment]
The problem appears to be the links that many of us were using and isn't limited to Metamask users (although you should avoid Metamask due to their sketchy privacy agreement, which mentions the use of Google Analytics among other concerning practices).

With that being said, none of the links that @glitterlip provided worked for me. I did, however, send test ETH to my Brave Wallet through the Rinkeby, Goerli, and Kovan test networks using the link that @mohammadmadadi provided. Thanks, Mohammad!

**Comment by Eganizm** [comment]
The problem appears to be the links that many of us were using and isn't limited to Metamask users (although you should avoid Metamask due to their sketchy privacy agreement, which mentions the use of Google Analytics among other concerning practices).

With that being said, thanks for the links, @glitterlip, but none of those worked for me. I did, however, send test ETH to my Brave Wallet through the Rinkeby, Goerli, and Kovan test networks using the link that @mohammadmadadi provided. Thanks, Mohammad!

**Comment by princegoyal65** [comment]
![image](https://user-images.githubusercontent.com/78958474/148683494-861d3313-200d-400b-b331-15159cefce9a.png)


Still not resolved

**Comment by princegoyal65** [comment]
![image](https://user-images.githubusercontent.com/78958474/148683541-77795965-93c5-4e75-afd1-7ff885369d9e.png)

Still not resolved !!!!

**Comment by hshoja** [comment]
worked for me

**Comment by CypElf** [comment]
If it can help, I was experiencing this issue while using the Brave browser, but it worked in Firefox instead. No idea why or if it will be the same for other people, but you can still try.

**Comment by themightylaz** [comment]
These two worked for me:
 - Rinkeby: https://faucets.chain.link/rinkeby
 - Ropsten: https://faucet.egorfine.com/

**Comment by d0nluka** [comment]
It's a f'n joke that this issue is still not resolved

**Comment by myk4040okothogodo** [comment]
still running into this issue, three years later, any updates?
