### ISSUE TITLE
when i try to open meta mask its stuck on welcome

### ISSUE THREAD

**Issue by airboat** [MetaMask/metamask-extension#5441]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI?

**Additional context**

**Comment by bdresser** [comment]
@airboat we need a little more detail

Stuck on welcome - you mean you see the password input screen, but you can't click in or type or anything?

What MetaMask version and OS are you on? (If you can't click in the extension, visit `chrome://extensions` to check your version.)

Any errors in the popup logs or [background console](https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue)?

**Comment by whymarrh** [comment]
Hey @airboat, I'm going to close this for now but please ping us if you can produce reliable reproduction steps (or even just more information about your setup) and we can work to fix the issue!
