### ISSUE TITLE
Meta wont log into MEW

### ISSUE THREAD

**Issue by rubens1985** [MetaMask/metamask-extension#5444]
I logged into my metta mask and when i get into MEW it wont log me in using metta mask 

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI?

**Additional context**

**Comment by bdresser** [comment]
@rubens1985 we need more detail to help you. Please fill out the template below your comment! Screenshots are helpful too.

**Comment by tmashuang** [comment]
Closing due to lack of description and activity.
