### ISSUE TITLE
window.ethereum not injected in current MetaMask version (4.13.0)

### ISSUE THREAD

**Issue by NoahWarnke** [MetaMask/metamask-extension#5446]
**Describe the bug**
The window.ethereum object is not being injected by the latest MetaMask extension (in Chrome, not tested in other browsers.) This means the "ethereum.enable()" function is unavailable, even though it's supposed to become required on November 2, and dapps have to fall back on web3.currentProvider.

**To Reproduce**
1. Open a tab with the latest-version MetaMask extension active.
2. Type 'window.ethereum' into the developer console.
3. See 'undefined' as the result. Expected a provider object.

**Expected behavior**
window.ethereum should contain the provider object injected by MetaMask.

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Chrome 69.0.3497.100
 - MetaMask Version: 4.13.0
 - New / Beta UI (I think).

**Additional context**
I'm pretty new to working with web3, so I could easily be missing something, but I was successfully using window.ethereum.enable() (even though it automatically grants access prior to Nov. 2) a few days ago, following https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8 Now it definitely doesn't work.

Thanks for any help!

**Comment by ntulsy** [comment]
I have the same issue when using Metamask 4.13.0 on Windows 10.

**Comment by bitpshr** [comment]
Hi @NoahWarnke and @ntulsy, thanks fo reaching out. We had a few critical issues with the most recent release of MetaMask that caused us to temporarily roll back to a previous version, but we're resolving this now. As soon as we push a new release shortly, all `window.ethereum` / `ethereum#enable` functionality will be present once again. Apologies for the inconvenience.

In the meantime, you can always download and manually install one of the [latest builds](https://github.com/MetaMask/metamask-extension/pull/4703#issuecomment-427062852) from the actual EIP-1102 PR to fully test the breaking changes.

**Comment by NoahWarnke** [comment]
Thanks for clarifying! window.ethereum becoming temporarily unavailable _has_ helped me test my code for the "legacy" case :)

**Comment by NoahWarnke** [comment]
I see that MetaMask 4.16.0 came out in the past day or two. It's injecting window.ethereum as expected, so closing this issue now. Thanks!

**Comment by jtrainaldi** [comment]
Anyone experiencing the window.ethereum object returning undefined when using the Brave browser?

**Comment by mtsalenc** [comment]
@jtrainaldi Yes :hand: unfortunately

**Comment by Tectract** [comment]
ARGH wut

**Comment by Tectract** [comment]
Please reopen until we can get this issue resolved under Brave.
