### ISSUE TITLE
Stop supporting the old UI

### ISSUE THREAD

**Issue by chaftacode** [MetaMask/metamask-extension#5448]
**What problem are you trying to solve?**

Default to the updated UI

**Describe the solution you'd like**

MetaMask to default to the updated UI and delete the old UI from the main repository

**Additional context**

Developers on our team have been trying to make contributions but are intimidated by the need to make changes against two UIs.

**Comment by danfinlay** [comment]
You don't need to update the old UI as long as you don't break the background API. We're already removing it as fast as we can without breaking lots of users' experiences and frustrating them. Closing because we're already tracking this.
