### ISSUE TITLE
Ensure test suite is deterministic

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5451]
When submitting a PR, I often have to re-run the tests many times before I get the tests to pass. This is an awful experience. I never know if there really is a bug, just that there might be, and since the test suite takes 5-10 minutes per run, a few retries means possibly a half hour before I start to suspect there actually is something wrong with the code.

[Here is a PR that kept failing for different non-deterministic reasons](https://circleci.com/gh/MetaMask/workflows/metamask-extension/tree/i5449-SimpleSubscriptionSupport).

We need to fix this urgently. It has gone on far too long.

**Comment by whymarrh** [comment]
> We need to fix this urgently. It has gone on far too long.

I agree, 100%. The inconsistency of the e2e tests leads to trust issues and blind re-running of tests, as you noted.

A few proposed changes:

1. **Delete the old UI, its integration tests, and its e2e tests (#5334)**: this brings us down to just the e2e tests for the new UI
2. **Retry tests at multiple "layers" before failing**: we currently have timeouts and retries built into some of the e2e tests. Still when the tests fail we can retry the whole command *N* times as well (that is, at the shell command "layer").

**Comment by whymarrh** [comment]
cc @tmashuang @danjm who I imagine are also thinking about this

**Comment by Gudahtt** [comment]
While I'm sure there is still room for improvement, it seems that the test suite is _mostly_ deterministic now. Perhaps this can be closed?
