### ISSUE TITLE
Does the 2nd November Change Provide A New Way For Users To Login to a Dapp?

### ISSUE THREAD

**Issue by mudgen** [MetaMask/metamask-extension#5452]
Currently, for dapps like CryptoKitties a user will login by signing a message with metamask. This action proves that a user indeed owns the public address that is being used in metamask.

On November 2nd a new change in MetaMask is going live that requires that users enable websites to access their data.  More info about that here: https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

My question is this:  Can this change be used by websites to securely verify that the addresses in metamask are owned by a user?   Can this mechanism be used instead of signing a message to prove that the user owns a public address?

Otherwise users will have to login twice:   Once to approve access to public addresses,  and once again to prove that the user owns an address.

**Comment by VexyCats** [comment]
Good question. 

I believe it will request that the user gives metamask permission to inject window.ethereum with their address and info like it does now. 

So I believe, in an easy world, changing the getWeb3 util that comes with truffle, to simply check first for window.ethereum, and if so, return the web3 object on user approval, will do the same. 

So from there on, they would have unlocked metamask, and now you can request them to sign a message. 

So yes, 1. to accept metamask on this dapp. 2. to sign message,

**Comment by mudgen** [comment]
I really wish there was another function similar to the one to give approval to access the users public address that did both things: made the user's address available and signed a message,  so that we don't a have to make users sign into the website twice.  I think it could be confusing to users to have to essentially login to a website twice in order to use it.

**Comment by VexyCats** [comment]
Yeah that does seem like a nice feature, once a user logins in (allows your dapp access) it also signs a message with your dapps info, that you can use to verify their identity....

Although I have yet to implement the new changes in my dapp, so I could be wrong about my previous post.

**Comment by crazyrabbitLTC** [comment]
Thats a great idea but i think the answer is no. There really (as far as i know) isnt any security around injecting the web3 on the window and returning a list of public keys. Nothing stops you from building a fake metamask that only returns arbitrary public keys. The only security is signing a transaction. So unfortunately i would say we need to confirm metamask twice, which, really, is kind of a shame because its not very nice ui experience. 

Its hard to see how to improve this though, i have yet to implement the change myself, so lets see.

**Comment by bitpshr** [comment]
Hi @mudgen, @VexyCats, and @crazyrabbitLTC, thanks for reaching out.

Your understanding is correct: users will not be able to both enable a full provider and also sign a message (or complete any other approval-requiring RPC call) batched within the same approval window. These operations are inherently different provider calls, one being to enable accounts in the first place, and the other to specifically call `eth_sign` (or something similar). This also opens up a few questions: How would the UX look? What RPC calls should be able to be "batched" or combined after provider enablement? We may put more thought into combining provider-enablement with other RPC calls in the future, but we don't plan to at this time. This concern should also be greatly alleviated by MetaMask's caching of user approvals: once a user approves full provider access once for a given dapp domain, they never have to again unless they manually clear their prior "approval data" via settings. The "double login" UX issue as I understand it would only happen initially.

From a high level, it's probably most beneficial to think of provider-enablement more like requesting a access to a user's webcam, not necessarily part of a login paradigm. The login paradigm should still rely on some identity attestation.

Thanks again for your feedback, this is very informative. We'll think more about streamlining approval UX for dapps that rely on signature-based login, but this won't be part of the official November 2nd date.

**Comment by mudgen** [comment]
Sorry to open this again. I just wanted to say @bitpshr thank you for the very informative and complete response. As a developer and user it feels very good to get such a good answer/response.

**Comment by pointtoken** [comment]
Can someone from MetaMask do a new blog post that enumerates exactly what needs to be done for any dapp that uses signature-based login?

**Comment by bdresser** [comment]
@pointtoken yes! We'll have a new post for devs and one for users out shortly. Will post here when they're up 👍

**Comment by bitpshr** [comment]
Hi @pointtaken, @bdresser is correct: we'll have a new developer-focused blog post published shortly that summarizes all necessary changes.

From a high level, a dapp that uses signature-based login should be updated in the same way as any other dapp: before calling the signature RPC method, `ethereum.enable()` must be called first.

We'll be sure to drop the link to the new blog post in this issue for posterity.
