### ISSUE TITLE
verify-locale-string.js fails when using a locale option

### ISSUE THREAD

**Issue by Bunjin** [MetaMask/metamask-extension#5457]
Running node verify-locale-string.js returns an error when using a locale option

e.g. `node verify-locale-string.js fr`

but it works without a locale option

![image](https://user-images.githubusercontent.com/11554098/46617622-79a2c280-cb1d-11e8-8829-f3b37c70baca.png)

develop branch running on node v9.11.1 on ubuntu 16.04

commit:
https://github.com/MetaMask/metamask-extension/commit/26e4f87ce4b256a8fd879d2c57a63124315d798e

seems to be related to the {} in line 23 and 33 (and maybe my node version ? )

Fixed in commit in my fork :
https://github.com/Bunjin/metamask-extension/commit/d63a77e61cb9b29d26e7dc473f79563f0bfa5e71

**Comment by Bunjin** [comment]
Just tried with node v8.11.3 and I've got the same error.

The fix proposed in https://github.com/Bunjin/metamask-extension/commit/d63a77e61cb9b29d26e7dc473f79563f0bfa5e71 works also under node v8.11.3

**Comment by bdresser** [comment]
@Bunjin feel free to open a PR!

**Comment by Bunjin** [comment]
@bdresser Sure, I want to :) I was just waiting to fully test the french locale first and make sure everything is working properly.
