### ISSUE TITLE
Defining: Drizzle compatibility issue

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5459]
Related to #5458 and #5425

Fixing subscribe:

- Drizzle pifies its provider, breaking the `this` reference.
  -  Should make sure pify method receives correct context argument.
  - requires patch in blocktracker-es5 2.3.2, which we don't own (to define later, ask @kumavis, I didn't follow this part)

Non breaking API Proposal:
- [x] open issue in metamask that explains why this goop exists. (this issue)
- [ ] goop will be in inpage-provider, marked with a `TODO:` tag.
    - In the bottom of the constructor
        - binding sendAsync methods to `this`.
        - This should prevent drizzle from breaking the this reference with pify later on.

**Comment by danfinlay** [comment]
- Drizzle is using old eth-block-tracker
- It loses the reference to the block tracker somehow, inside a pify statement.
- The way we implement the inpage provider depends on a correct `this` value.
    - Trying to force-bind our inpage provider to itself, so it can’t be rebound: https://stackoverflow.com/questions/20925138/bind-more-arguments-of-an-already-bound-function-in-javascript/20925268#20925268
        - However, this isn’t working. Pify is still rebinding somehow.
            - Is this some weird Class behavior?
            -

**Comment by stobiewan** [comment]
@danfinlay As of metamask 4.14 drizzle is no longer working with metamask, it never sees contracts are synced so the basic examples always show the refresh symbol. Is this related?

**Comment by DiscRiskandBisque** [comment]
This should be able to be closed with the merger of trufflesuite/drizzle#131.

**Comment by whymarrh** [comment]
The issue @DiscRiskandBisque noted above has been merged and we've also added Drizzle to our test setup, so I think this is safe to close.

@stobiewan if you're seeing issues with Drizzle and MetaMask, please open up a new issue and we can fix it
