### ISSUE TITLE
Change clickable are of "Max" button

### ISSUE THREAD

**Issue by grinry** [MetaMask/metamask-extension#5469]
Right now, when sending tokens you can click `Max` by mistake, because clickable area is bigger than text on this.
User may not realise that he send all of his tokens because in next page, `total` doesn't include token price and numbers like `123.456` and `12345.6` can look pretty same to human eye.

**Comment by whymarrh** [comment]
Thanks for reporting this @grinry! This has been improved and is coming soon to a release near you!
