### ISSUE TITLE
How does MetaMask calculate the correct transaction nonce?

### ISSUE THREAD

**Issue by tarekskr** [MetaMask/metamask-extension#5476]
How does MetaMask calculate the correct transaction nonce when multiple transactions are being issued?

It's well known that [eth_getTransactionCount does not return the correct number of pending transactions](https://github.com/ethereum/go-ethereum/issues/2880), so I was wondering how you guys do it. Could be really beneficial for the community to learn from.

**Comment by frankiebee** [comment]
Put simply: we take the "highest" known confirmed nonce and add the pending transaction count from your local tx history (the transactions you've sent from within metamask). Given that sometimes infura may not know the most update nonce (asking a node a block behind etc.) We do to calculations for confirmed nonces: Derived from local confirmed and eth_getTransactionCount.

you can reference all this code here: [nonce-tracker](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/nonce-tracker.js)

**Comment by tarekskr** [comment]
Excellent, thank you so much for the link @frankiebee !

**Comment by kaibakker** [comment]
Is it possible to suggest a nonce to be able to cancel an pending transaction or update the gas price?

**Comment by bdresser** [comment]
@kaibakker we support speeding up tx already, check out https://github.com/MetaMask/metamask-extension/issues/4022 re: cancelling
