### ISSUE TITLE
Unifiy e2e test boilerplate code

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-extension#5488]
@kumavis  brought a good point [here](https://github.com/MetaMask/metamask-extension/pull/5467#discussion_r223896388) and [here](https://github.com/MetaMask/metamask-extension/pull/5467#discussion_r223897602).

We have 3 specs where we need to set up MM from scratch to be able to start using it ( basic selenium boilerplate code +  onboarding / import account )

It would be cool to move this into a separate package so we don't repeat ourselves and also we can give dApps the ability to use it to write e2e tests with MetaMask.

@tmashuang  @danjm What would be the best approach to do that?

**Comment by whymarrh** [comment]
I think this is something we'll need to consider when working on #6035, #6036, and #6038

**Comment by Gudahtt** [comment]
The `withFixtures` function here should serve this purpose: https://github.com/MetaMask/metamask-extension/blob/develop/test/e2e/helpers.js
