### ISSUE TITLE
Search account by name

### ISSUE THREAD

**Issue by markusbkoch** [MetaMask/metamask-extension#5492]
**What problem are you trying to solve?**
I have many accounts. I have to scroll through the list in order to find the one I'm looking for.

**Describe the solution you'd like**
A "search" text field that allows me to filter the list of accounts by the name of the account and the name/symbol of the tokens it holds

**Comment by danwani** [comment]
As well as this, would it be possible to search by address?

**Comment by damster7** [comment]
je n arrive pas a ouvrir mon, compte que faire

**Comment by marsrobertson** [comment]
~I have 1 account for daily usage.~

~Another account for some dust.~

~Another one for API.~

~Another one for this...~

~Another 3 for developing on localhost.~

~After some weeks you build memory and start recognizing them.~

**Nevermind, I've figured out how to rename them**

Keywords: account, label, labels
