### ISSUE TITLE
Increase eventEmitter.maxListeners in inpage script

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5493]
Seems that our new `.subscribe()` support has introduced an event listener warning to our inpage script:

`MaxListenersExceededWarning: "Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit"`

Reported [here](https://github.com/MetaMask/metamask-extension/issues/5425#issuecomment-428504195).

**Comment by bdresser** [comment]
fwiw i've seen this error intermittently for the past several months

**Comment by hodlbank** [comment]
Solution for our DApp is to increase maxListeners of currentProvider upon provider initialisation:
```
// typescript
private tuneUpProvider(provider: Provider): void {
    let providerEE = provider as any;
    if (typeof providerEE.setMaxListeners == 'function') {
      providerEE.setMaxListeners(999);
    }
  }
```
