### ISSUE TITLE
Token sending failed on-chain, but confirmed in Ui.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#5495]
Repo:

1. Create token on Rinkeby (token.surge.sh)
2. Add Custom Token
3. Send Token to another address
4. Might have to set lower gas limit to fail tx
5. Ui should confirm the tx.
![send-token-confirm-but-failed](https://user-images.githubusercontent.com/13376180/46767805-fdce8480-cc9a-11e8-8d6b-c4227eb7332f.png)

**Comment by tmashuang** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/5387

**Comment by bdresser** [comment]
expected behavior, closing in favor of https://github.com/MetaMask/Design/issues/46 and #5387
