### ISSUE TITLE
Update support article links

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#5501]
We recently changed our guide to metamask.zendesk.  Please update these four support article links (search for consensys.zendesk):

**Current:**
https://github.com/MetaMask/metamask-extension/search?q=https%3A%2F%2Fconsensys.zendesk&unscoped_q=https%3A%2F%2Fconsensys.zendesk

**New:**
https://metamask.zendesk.com/hc/en-us/articles/360015289932-What-are-imported-accounts-New-UI-

https://metamask.zendesk.com/hc/en-us/articles/360015289612-Restoring-MetaMask-from-seed-phrase-New-UI-

https://metamask.zendesk.com/hc/en-us/articles/360015289932-What-are-imported-accounts-New-UI-

https://metamask.zendesk.com/hc/en-us/articles/360015488751-Signature-Request-Warnings-eth-sign

**Comment by bdresser** [comment]
fixed in https://github.com/MetaMask/metamask-extension/pull/5503
