### ISSUE TITLE
JsonRpcEngine error: response has no error or result for request getting pending block data.

### ISSUE THREAD

**Issue by Pedro-vk** [MetaMask/metamask-extension#5507]
**To Reproduce**
Steps to reproduce the behaviour:
1. Request the pending block.
2. The error is thrown and the console shows:
```
inpage.js:1 MetaMask - RPC Error: Error: JsonRpcEngine - response has no error or result for request:
{
  "jsonrpc": "2.0",
  "id": 3279580878,
  "method": "eth_getBlockByNumber",
  "params": [
    "pending",
    false
  ],
  "origin": "127.0.0.1"
}
```

**Expected behaviour**
Return pending block data without errors.

**Browser details (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chrome
 - MetaMask Version: 4.14.0
 - Old UI or New / Beta UI? New UI

**Comment by tmashuang** [comment]
Seems to be happening for all methods that has the pending parameter.

**Comment by bdresser** [comment]
thanks for reporting @Pedro-vk - should be fixed by https://github.com/MetaMask/metamask-extension/pull/5510.
