### ISSUE TITLE
Scrollable home page & inline transaction detail view

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5508]
We've introduced several different floating or sliding elements in to the extension, most added individually, and the modal transaction detail view & slide-in "speed up" component make for a very awkward transition. This issue aims to simplify UI treatment of a couple new elements:

We should 
* make it so that everything from the account nickname and below scrolls together. That includes transaction history, overall ETH balance, overall fiat balance, deposit/send buttons, and token/ETH logo. The bar with hamburger menu, account bar, and account `...` options should be fixed.
* show the transaction detail view inline (as it's shown in the full-tab view).
* remove that tiny line on top of the transaction history because we don't need it and it will make @cjeria very happy 😄 

<img width="1074" alt="screen shot 2018-10-11 at 1 30 11 pm" src="https://user-images.githubusercontent.com/1016190/46832021-d2f73580-cd59-11e8-8b14-c92d5c71badd.png">

**Comment by alextsg** [comment]
@bdresser Just to confirm, bullet point #2 is referring to removing the flow of opening up a modal with the transaction details and using the expanding behavior of the full-screen view right?

**Comment by bdresser** [comment]
@alextsg correct - like it used to be in your first iteration 🙈
