### ISSUE TITLE
Transaction Information {Dropped} 

### ISSUE THREAD

**Issue by c-jun88** [MetaMask/metamask-extension#5514]
Please check the error.

▼

Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
(anonymous) @ ui.js:1
ui.js:1 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.
n.default @ ui.js:1
ui.js:1 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
(anonymous) @ ui.js:1
ui.js:1 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
(anonymous) @ ui.js:1
ui.js:1 Setting up Sentry Remote Error Reporting: PROD

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI?

**Additional context**

**Comment by bdresser** [comment]
@c-jun88 did you experience a bug using the extension? or are you just drawing our attention to these warnings in the console

**Comment by bdresser** [comment]
thanks for reporting - we're handling each warning in separate issues.
