### ISSUE TITLE
Show ENS reverse-resolved names where addresses are used

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5525]
When available, we can show ENS reverse-resolved names instead of ethereum addresses. This issue will encompass that general goal of replacing ugly ethereum addresses with nice names.

Related to #5294.

Needs to incorporate homoglyph protection, which can be accomplished by incorporating [MyCryptoHQ/ens-validation](https://github.com/MyCryptoHQ/ens-validation).

I support easily checking reverse-resolution in [ethjs-ens](https://www.npmjs.com/package/ethjs-ens) Using `const name = await ens.reverse( address )`.

**Comment by bdresser** [comment]
https://github.com/MetaMask/metamask-extension/issues/4616 and https://github.com/MetaMask/metamask-extension/issues/4380 also relevant

**Comment by bdresser** [comment]
design should be pretty simple - only Q that comes to mind if we're showing the `.eth` address: what does the copy option do? copy the ENS address, or copy the underlying ethereum address?

**Comment by whymarrh** [comment]
Should we close this in favour of #1131 which has design discussion or do we want to prefer this one over that to give us a fresh slate for thinking about a solution? (Maybe let's prefer this since the discussion there is centred around the old UI.)

**Comment by danfinlay** [comment]
Hey @cjeria @omnat I opened a design issue for this [here](https://github.com/MetaMask/Design/issues/89). I think this is pretty simple and overdue, maybe we can get it on the next sprint.

(Ignore the other issue I posted this on, mis-posted)

**Comment by bdresser** [comment]
- cache the ens name so it can be re-used around the extension
- some sort of expiry for that cache since the 0x address an ENS name points to can be changed
- a saved contact should take precedent over an ENS lookup
