### ISSUE TITLE
Update "Deposit" page

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5526]
We've gotten a lot of inbound request for additional exchanges on our "Deposit" page

We should update the page at the very least to accomodate more than just Coinbase (shown below)

It'd be nice to also group thematically - rather than end destination, show the options by what the user is trying to do.

This is probably stopgap while we do more research in to the whole onboarding experience

![deposit-page](https://user-images.githubusercontent.com/1016190/46976151-81161e80-d07d-11e8-861f-8042d77fb47a.jpg)

**Comment by bdresser** [comment]
Mural brainstorm with @omnat and @dpazdan [here](https://app.mural.co/t/consensys3989/m/consensys3989/1551727039639/ae121c30fc78a3deb8bad28665ffded964a1f71e)

Initial idea may be to highlight the WAYS a user can get their first ETH. Like `Buy with a credit card` OR `Request funds from a friend`

For the first, we could link to a MetaMask-native fiat onramp (like Airswap's Wyre integraation). For the latter, we can give the user an option to show / copy their address, which eventually could evolve into initiating a payment request once we move on that.

**Comment by Gudahtt** [comment]
We've made a number of changes to our Deposit page since this issue was created. Likely more changes are on the way, but we can track those separately as designs are finalized, so I'll close this for now.
