### ISSUE TITLE
Integrate Gemini for fiat onboarding

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5527]
We should include options other than Coinbase for Fiat -> ETH onboarding.

Spoke with some folks from Gemini who are interested in building a MetaMask-specific flow

Our basic requirements for such a page are
- start the user in a standalone Gemini flow with ETH address pre-filled
- include some basic MM branding
- end with a custom graphic that helps the user find their way back to MetaMask

@cjeria any other thoughts?

**Comment by cjeria** [comment]
I think it's great that we're thinking about adding more fiat onboarding options within MetaMask, especially if other options reduce friction.

The two big problems with existing options are:
- Lot's of friction: users need to create an account in Coinbase, verify, wait longs times and potentially drop out of buying and transferring to MetaMask.
- No transfer feature, only buying ETH - If I already hold ETH, there's no option to Transfer ETH from Coinbase. Buying ETH through the MM w/Coinbase adds a service fee!

I'll need more context for what is possible with Gemini, but here's rough initial flow of what can potentially happen:

1. **In MetaMask**
- User clicks "Transfer" in MetaMask
- Present option to transfer ETH w/Gemini (in list next Coinbase and Shapeshift)
- User clicks Gemini: Opens new browser window, start of the custom Gemini flow

2. **In Gemini:** 
-  Login or Continue as Guest?
- If login
-- Present two options after login
-- Buy ETH?
-- Transfer from my account?
- If Continue as guest
-- Buy ETH only flow

Happy to help better define the UX for this once we have more context. @bdresser
