### ISSUE TITLE
Metamask doesn't update block number after laptop sleep 

### ISSUE THREAD

**Issue by Vourhey** [MetaMask/metamask-extension#5531]
Sometimes Metamask don't update block number. Usually I close my laptops screen and the next day I try to use it, block number stays the same as the day before. 

Ubuntu 18.04
I use Chromium Version 69.0.3497.81
Metamask 4.14.0 / New UI

![screenshot_2018-10-16_09-52-01](https://user-images.githubusercontent.com/709124/46997782-479aed00-d129-11e8-98a3-6d772bbb6b3d.png)

**Comment by bdresser** [comment]
@Vourhey what happens if you open the extension, then check the block number? What about if you change accounts, then check?

**Comment by ProtonGustave** [comment]
@bdresser how can i check the block number in mm? with getBlockNumber function?

**Comment by bdresser** [comment]
This was fixed in https://github.com/MetaMask/metamask-extension/pull/5614 and released in 4.17. Let us know if you're still seeing this issue and we can re-open.

@ProtonGustave `web3.eth.getBlockNumber('latest`, cb())` should give you the latest block number.
