### ISSUE TITLE
how get metamask user's nickname

### ISSUE THREAD

**Issue by LeJane** [MetaMask/metamask-extension#5532]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI?

**Additional context**

**Comment by bdresser** [comment]
@LeJane we don't expose users' account nicknames
