### ISSUE TITLE
Signing messages with full-screen notification breaks UI

### ISSUE THREAD

**Issue by decanus** [MetaMask/metamask-extension#5538]
**Describe the bug**
<img width="1280" alt="screen shot 2018-10-18 at 01 33 06" src="https://user-images.githubusercontent.com/7621705/47122265-5f33bc00-d276-11e8-8030-bc9674a421e8.PNG">
I can't see what is being signed.

**To Reproduce**
This appears whenever I try and sign a message, I don't know whether its with the ``eth_sign`` or ``personal_sign`` or ``eth_signTypedData`` function (@mbeylin might be able to give the answer). However it happens when I sign a message to login on bounties.network.

**Expected behavior**
Being able to see what I sign, and the UI not being completely borked.

**Browser details (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
 - MetaMask Version: 4.14.0
 - Beta UI I think, if it still is?

**Comment by bdresser** [comment]
Woah, super weird, have never seen this before. Couple q's to help us dig in:

Is this happening consistently?
Is this with the standalone popup or the extension attached to the top-right of your browser? 
Does it happen with normal transactions, or just with signing data?
Have you used (and resized) chrome pop-ups created by any other apps? 

And to clarify, you're on `explorer.bounties.network` trying to sign in (as below)?

<img width="1110" alt="screen shot 2018-10-17 at 5 10 28 pm" src="https://user-images.githubusercontent.com/1016190/47123319-97fc7280-d22f-11e8-92f6-d1ee6f3a5d80.png">

**Comment by decanus** [comment]
@tmashuang I'm not entirely sure what you mean, this just happens when its in fullscreen for me. Like on the mac when the window is then a separate desktop pane?

**Comment by bdresser** [comment]
I think it's the same root cause - when the notification window is huge, the UI gets jumbled. Happens if you're either in a full-screen browser or if you stretch the notification window.

Thanks for reporting - for now you can workaround by using non-fullscreen, yeah?

**Comment by WopKatan** [comment]
Is there any workaround as the service provider? 
something like forcing popup to open in non-full screen?
