### ISSUE TITLE
Pas

### ISSUE THREAD

**Issue by wandhy79** [MetaMask/metamask-extension#5546]
FOR USER QUESTIONS, PLEASE DO NOT OPEN A GITHUB ISSUE - IT WILL NOT BE HANDLED HERE.

INSTEAD, PLEASE EMAIL SUPPORT@METAMASK.IO WITH A DESCRIPTION OF YOUR PROBLEM.

**Comment by bdresser** [comment]
hey @wandhy79 - if you're having trouble with the extension, please email support@metamask.io!
