### ISSUE TITLE
Balance not updating on 4.16

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5553]
Some users have reported that their ETH balance is not updating (or taking a very long time to update) on 4.16

For those who experience this: please let us know here, and then try switching to a testnet then back. 

@kumavis

**Comment by PumpkingWok** [comment]
Hi @bdresser,
I have encountered the same problem yesterday, but with a custom token balance. I had to close the browser and reopen it, It was 15/20 minutes that i could see the new balance in etherscan but not in Metasmak.
Thanks.

**Comment by lovvtide** [comment]
Can confirm something similar is happening to me. I'm working on a dapp which calls functions on Rinkeby and the transactions were not showing confirmed even though they had many confirmations on etherscan. Seems like this problem started in 4.16. I switched to Mainnet and then back to Rinkeby and it fixed the problem.

**Comment by guix77** [comment]
Could be related: https://github.com/MetaMask/metamask-extension/issues/5551#issuecomment-431932314

**Comment by brentxu** [comment]
same thing happening to me in regards to my Trezor wallet linked to MM.

**Comment by Vetal4uk** [comment]
Good

**Comment by AntonioJuliano** [comment]
Seeing this as well. Not sure if it's on Metamask or Infura. It seems like the nodes it's pulling from are out of sync (gets results from an outdated block)

**Comment by bdresser** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/5614 and released in 4.17. Let us know if you're still having trouble with this and we can re-open.

**Comment by emkman** [comment]
@bdresser Just had this happen to me for the first time ever, running 5.3.2 on Chrome 71 for Mac. Switching to testnet and back resolved it.

**Comment by naviloper** [comment]
I have also this problem with the balance of my tokens and eth. after I did a swap in Curve this happened. I think it is because of Infura API that Metamask is using it and not related to Metamask itself.
