### ISSUE TITLE
Popup notification not wide enough

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#5557]
**Describe the bug**
When an account has a ridiculously high ETH balance, the default MetaMask notification popup shows a relatively useless dialog and it's not clear what the user is supposed to do.  The notification looks like this:

![typical popup as it comes up](https://user-images.githubusercontent.com/563406/47238321-d1f48280-d3af-11e8-9c58-50cfd5f51ce0.PNG)

The workaround is to hover the mouse over the right or left edge of the popup window and hope it turns into resize handles, then click and drag to widen the notification and display something like this:

![popup widened](https://user-images.githubusercontent.com/563406/47238372-fa7c7c80-d3af-11e8-855d-2e55b727b511.PNG)

Unfortunately, if the notification is getting displayed by clicking on the MetaMask icon in the upper right corner instead of being a popup notification, it cannot be resized:
![popup manually opened cannot be resized](https://user-images.githubusercontent.com/563406/47238868-9e1a5c80-d3b1-11e8-9f19-6b9cf8c41f2f.PNG)
The only way I have found to get this version wide enough is to right-click on the popup, Inspect Element, and edit the `html` **and** `body` element widths to a significantly larger number of pixels (700 instead of 357 usually works for me).  These are not user friendly steps for submitting a transaction. 

**To Reproduce**
1. Use Geth to set up a simple private network in which one account has an extremely large balance.
2. Use MetaMask to connect to that private network and install the private key for the rich account. 
3. Load UI for a dapp and trigger a transaction. 
4. See Metamask popup and wonder what you're supposed to do next.

**Expected behavior**
The notification should be sufficiently wide for the display.  
To reduce the required width, a very large balance may be elided (e.g. "904...465.124 ETH") similar to how the address is (and you should be able to click on it to copy the full value, as with the address) OR the balance may use scientific notation (as with the estimated fiat conversion just below it). 

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 69.0.3497.100
 - MetaMask Version 4.16.0
 - Old UI (new/beta has other blocking bugs for future reporting)

**Comment by bdresser** [comment]
hey @wbt - we won't fix this, as we're moving entirely over to the "new" UI shortly. You can give it a try from the Settings menu in the top-right.

On the new UI, huge amounts are rounded. Couple folks have reported they'd also prefer an ellipses or other treatment, so I'll point you towards https://github.com/MetaMask/metamask-extension/issues/5180
