### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the n component.

### ISSUE THREAD

**Issue by Chippi** [MetaMask/metamask-extension#5571]
**Describe the bug**
Cannot access MetaMask UI while connected to local RPC network. (localhost:8545). I get the following error in popup console. 

```Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the n component.```

**To Reproduce**
1. Select network, Localhost 8545
2. Close UI
3. Open UI
4. Stuck on loading screen indicator

**Screenshots**
![image](https://user-images.githubusercontent.com/6388933/47267437-1749b900-d544-11e8-98c2-f90733e05d09.png)

**Browser details (please complete the following information):**
Windows 10
Version 70.0.3538.67 (Official Build) beta (64-bit)

 - MetaMask Version [e.g. 4.9.0]
4.16.0
 - Old UI or New / Beta UI?
New

**Additional context**

**Comment by whymarrh** [comment]
@Chippi thanks for reporting this. We've been working hard to fix all of the usages of setState throughout the app and will be keeping an eye out for new errors.
