### ISSUE TITLE
Metamask Parity `eth_call` response error not handled correctly

### ISSUE THREAD

**Issue by dekz** [MetaMask/metamask-extension#5579]
**Describe the bug**

`eth_call` error responses from Parity/Kovan are not handled correctly. Looks like subsequent calls are then cached and no callback is ever called.

**To Reproduce**
Connect to Kovan

```javascript
web3.version.getNetwork((e, id) => console.log('networkId', id));
payload = {"method":"eth_call","params":[{"to":"0xd85e2fa7e7e252b27b01bf0d65c946959d2f45b8","nonce":"0x63","data":"0x18978e8200000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000004125c5a4149ebd50000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000003e0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000004524baa98f9a3b9dec57caae7633936ef96bd7080000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000006a6b65d93cdd5026729973d835716ba0450b00200000000000000000000000000000000000000000000000000000000000000000000000000000000000000004524baa98f9a3b9dec57caae7633936ef96bd70800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007b5b5c814f7e0000000000000000000000000000000000000000000000000000000d7441a5c3b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005c00ec204de62156fec2a14cfdfb866788cc1e7b52e032864a9fb24bd30e4433694d32b2000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000024f47261b0000000000000000000000000ace9bf740465f83acb93c90859a57ad5fb49f7be0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000421b4929a5a4835b8a11d50006d98079b2551f1e4a1454b3b8b8d806f0f812316f880f1690b3609455cc06df8a6c017dd5816988636f37de6829568f4de094635f130200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","value":"0x71ccef2d72001","from":"0xd40af4a0ec5e0340c2948d38b034a50ddca17671"},"0x8ba2a9"]};
web3.currentProvider.sendAsync(payload, (e, result) => console.log('result', result, 'error', e));
```

The RPC Response from Parity returns:

```
{"jsonrpc":"2.0","id":1969235914,"error":{"code":-32015,"data":"Reverted 0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014434f4d504c4554455f46494c4c5f4641494c4544000000000000000000000000","message":"VM execution error."}}
```

Metamask doesn't appear to understand this response which causes it to retry a number of times.

Once the retry limit is exhausted an error result is returned (not an error on the callback).

```
code: -32603, message: "Error: BlockReEmitMiddleware - retries exhausted↵ …beogaeaoehlefnkodbefgpgknn/background.js:1:928350"
```

All subsequent attempts appear to be cached and a result is never returned when the same `eth_call` is attempted again.

**Expected behavior**

Metamask should understand this JSON RPC response error from Parity and not attempt to retry. It should callback with this error to the caller. The cache should be cleared and subsequent attempts should also fail.

**Screenshots**

Initial Retry logic retrying the request multiple times.  
<img width="1440" alt="screen shot 2018-10-23 at 2 49 41 pm" src="https://user-images.githubusercontent.com/27389/47334933-75a5a180-d6d4-11e8-8c30-9ac71279e560.png">

"Error" result 
<img width="1405" alt="screen shot 2018-10-23 at 2 53 06 pm" src="https://user-images.githubusercontent.com/27389/47334946-88b87180-d6d4-11e8-9a5c-4f6d00fbcb12.png">

Attempting to call again results in a hang (no network requests, callback never called)
<img width="1429" alt="screen shot 2018-10-23 at 2 59 08 pm" src="https://user-images.githubusercontent.com/27389/47335013-d03efd80-d6d4-11e8-8038-617e3b4d8c73.png">

**Browser details (please complete the following information):**
 - MetaMask Version [e.g. 4.9.0]
 - Old UI or New / Beta UI?

**Additional context**

**Comment by tmashuang** [comment]
Seems to be an issue with the block parameter, and it tries to step into the "latest" rather than return it from the block specified. To be clear, it does return the response from the block specified then makes subsequent requests looking like the `latest` block param.

**Comment by tmashuang** [comment]
Looping back to this, this is still a bug but debugging has lead to inconsistencies in finding the root cause. Still in progress.
