### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Sentrycs** [MetaMask/metamask-extension#5585]
**Describe the bug**
running npm install on cloned metamask code and getting following errors. See below:

**Screenshots**
C:\Users\***\Documents\GitHub\Metamask\metamask-extension>npm install

> scrypt@6.0.3 preinstall C:\Users\***\Documents\GitHub\Metamask\metamask-extension\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install C:\Users\***\Documents\GitHub\Metamask\metamask-extension\node_modules\scrypt
> node-gyp rebuild

C:\Users\***\Documents\GitHub\Metamask\metamask-extension\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\***\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:336:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\***\Documents\GitHub\Metamask\metamask-extension\node_modules\scrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN @babel/register@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/core@1.0.0 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/core@1.0.0 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-merge-patch@4.1.0 requires a peer of ajv@>=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gulp-stylelint@7.0.0 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.0.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.1.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-standard@18.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package css-loader is included as both a dev and production dependency.
npm WARN The package eslint-plugin-react is included as both a dev and production dependency.
npm WARN The package eth-keyring-controller is included as both a dev and production dependency.
npm WARN The package file-loader is included as both a dev and production dependency.
npm WARN The package gulp is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Browser details (please complete the following information):**
 - OS:Windows 10 64 bit
 - Browser Chrome
 - MetaMask Version [latest from Github]

**Comment by brunobar79** [comment]
@Sentrycs  which versions of node and npm are you using?

**Comment by Sentrycs** [comment]
@brunobar79  We are using NodeJS 8.12.0 and npm v. 6.4.1 (they are latest downloads).

**Comment by tmashuang** [comment]
https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies#39648550

**Comment by Sentrycs** [comment]
thanks @tmashuang  It did work and python error is resolved. 
We still got bunch of warnings at npm install - see below. Shoud we address them or ignore them?
npm WARN @babel/register@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/core@1.0.0 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/core@1.0.0 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-merge-patch@4.1.0 requires a peer of ajv@>=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gulp-stylelint@7.0.0 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.0.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.1.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-standard@18.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package css-loader is included as both a dev and production dependency.
npm WARN The package eslint-plugin-react is included as both a dev and production dependency.
npm WARN The package eth-keyring-controller is included as both a dev and production dependency.
npm WARN The package file-loader is included as both a dev and production dependency.
npm WARN The package gulp is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by Sentrycs** [comment]
Further to the warnings on screen, during npm install, as shown above - we have looked at the npm-cache log and found these errors:
11 error code ELOCKVERIFY
12 error Errors were found in your package-lock.json, run  npm install  to fix them.
12 error     Invalid: lock file's eth-keyring-controller@3.3.0 does not satisfy eth-keyring-controller@^3.3.1.
Please advise on this comment and comment above regarding warnings.

**Comment by tmashuang** [comment]
Resolved, any other issues on windows should be redirected to https://github.com/MetaMask/metamask-extension/issues/5668
