### ISSUE TITLE
Transactions failing with "Invalid From Address"

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5587]
via Support:

I'm having a bug where my payable transactions have suddenly started failing with an "invalid from address" error.

In the console I'm getting
```
VM1525 inpage.js:1 MetaMask - RPC Error: Error: WalletMiddleware - Invalid "from" address.
at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:931096) {code: -32603, message: "Error: WalletMiddleware - Invalid "from" address.↵…eogaeaoehlefnkodbefgpgknn/background.js:1:931096)"}
```
This is a new error - these functions previously worked fine, but late last week I switched to the new MetaMask connection protocol. I tested by moving my code back to the old connection, but it made no difference. Transactions work fine in Remix, so I'm wondering if maybe the protocol for calling these functions with web3 has changed? One of the functions with this issue is below.

```
const addToWhitelist = async () => {
try {
let user = await getUserAccount();
const chainId = await web3.eth.net.getId();
let owner = await factory.methods.owner().call();
const adding = await factory.methods.addToWhitelist(user).send({ from: owner, gas: gas, chainId });
const result = await verifyWhitelist();
}
catch (err) {
console.log('error adding to the whitelist', err)}}
```

**Comment by sarbogast** [comment]
I'm having the exact same issue.

**Comment by bdresser** [comment]
hey all - yep, this behavior was added in https://github.com/MetaMask/metamask-extension/pull/5491 and released in 4.16

the `from` parameter in `eth.sendTransaction` must match the users address.

will leave this open for a couple days for others having the same issue.

**Comment by allegramarie** [comment]
Is there an approved protocol for a user to trigger a transaction where costs are borne by the contract owner?

**Comment by sarbogast** [comment]
I'm not sending a transaction from a different account than the one selected in Metamask and I still have this issue. I don't even see how I could do that, because Metamask would not be able to sign it.

**Comment by sarbogast** [comment]
In fact, after troubleshooting the issue for a bit, I noticed that the issue arises only in my React project using Drizzle. Could that be an incompatibility problem with Drizzle? Here are the versions I'm using in my project:
    ```
"drizzle": "^1.2.2",
    "drizzle-react": "^1.1.1",
    "drizzle-react-components": "^1.2.0",
```

**Comment by asghaier76** [comment]
you need to add ethereum.enable(); before calling ethereum.send

MetaMask introduced a Privacy Mode  that requires dapps to ask permission to view users’ accounts

**Comment by prashantprabhakar** [comment]
@asghaier76  I already did `ethereum.enable()`. Then users `ethereum.selectedAddress` as from in the param to sendETHWithMetamask

**Comment by asghaier76** [comment]
@prashantprabhakar 
 Using ethereal.enable() did MetaMask asked for approval.
 Also did you make sure that your ethereum.send is waiting for the promise from ethereum.enable()

**Comment by dsemenovsky** [comment]
It seems to be not documented, but you have to include **from** in _transactionParameters_ hash as well:
```

**Comment by vyomshm** [comment]
If you switch your user account on metamask, you need to ensure that the default account(i.e. `from`  is updated before doing anything else.

For non drizzle users, I wrote a simple async function which should work for any react dapp -

```
updateDefaultAccount = async () => {
    const web3 = this.state.web3;
    const accounts = await web3.eth.getAccounts();
    this.setState({defaultAccount: accounts[0].toString()});
};
```

**Comment by JoshGendein** [comment]
Can someone help me out with this problem. This is inside a new react app I made to start learning web3.
The getCoinBase() method is returning the address of the account I have on metamask but when I try to sign a message I get the same error message as seen above.

> inpage.js:1 MetaMask - RPC Error: Error: WalletMiddleware - Invalid "from" address.

Here's my code:

```javascript
let Web3 = require('web3')
.
.
.
constructor(props) {

    super(props);

    if (typeof web3 != 'undefined') {
      // eslint-disable-next-line no-undef  
      this.web3 = new Web3(web3.currentProvider);
    }

    this.web3.eth.getCoinbase()
    .then(account => {
      this.web3.eth.sign('test message', account);
    });
}
```

**Comment by bdresser** [comment]
As mentioned above, you must include a `from` address as part of the `transactionParameters` that matches the user's selected account. This is now included in our documentation [here](ttps://metamask.github.io/metamask-docs/Main_Concepts/Sending_Transactions).

**Comment by tsujp** [comment]
Still broken.

```
    const txParams = {
      from: test[0],
      to: addr,
      gasLimit: ethers.utils.hexlify(6721975),
      gasPrice: ethers.utils.hexlify(20000000000),
      value: ethers.utils.hexlify(150000000),
      chainId: 1337,
    }

    console.log('tx payload', txParams)

    library.send('eth_sendTransaction', txParams)
      .then((res: any) => {
        console.log('res', res)
      })
      .catch((err: any) => {
        console.log('err', err)
      })
```
