### ISSUE TITLE
Account names are not retained after uninstall/reinstall of MetaMask

### ISSUE THREAD

**Issue by janpeeters70** [MetaMask/metamask-extension#5592]
I've written to support about why account names were not retained after uninstall/reinstall. They answered that these were stored locally, so therefore MetaMask was unable to restore those. 
They advised me
"For the time being, you may write down the account names, to pair with the accounts with balance when they are restored."

I'd like to do a feature request so that these names are stored too. Maybe via data in IFPS/Swarm and a link to it in the blockchain to make it tamper proof?

**Comment by whymarrh** [comment]
@danjm is this something we'll store in 3Box?

**Comment by Gudahtt** [comment]
These are currently stored as part of our experimental 3Box backup. They will be included in other backup strategies we explore in the future as well, so I'll close this for now.
