### ISSUE TITLE
Style focus state of buttons

### ISSUE THREAD

**Issue by evansjohnson** [MetaMask/metamask-extension#5593]
**Describe the bug**
When using the tab key to navigate the MetaMask extension, I am given no visual indication of the active element.  https://github.com/MetaMask/metamask-extension/issues/3058 seems to have requested the outline be removed, but leave the outline when navigating with tab, although it seems to have just been entirely removed.

**To Reproduce**
1. Open MetaMask window
2. Press the tab key a few times
3. Hit enter
4. Find out which button was active

**Expected behavior**
An outline on the active element.

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - MetaMask Version 4.16.0
 - New / Beta UI

**Comment by danjm** [comment]
Resolved by #6860
