### ISSUE TITLE
If importing a key, metamask does not get the nonce correctly 

### ISSUE THREAD

**Issue by James-Sangalli** [MetaMask/metamask-extension#5600]
ALERT: [ethjs-rpc] rpc error with payload {"id":2379129378017,"jsonrpc":"2.0","params":["0xf919ab4885024a45567c835216f694830e1650a87a754e37ca7ed76b700395a7c6161480b91944cf0b41a3000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000000000000000000000000000000000000e7ea5bd186ea455448434b4202e8000026a0e5133ae595c8f54dfb88e26ac008ef9a02c0ca249d3bfeec6dab34c8b19edc8da054f9977c7686892e1ad1f1c68ed4339cd1a03e9b44aa3d163df996c80109ec1f"],"method":"eth_sendRawTransaction"} {"code":-32000,"message":"nonce too low"}

**Comment by bdresser** [comment]
@James-Sangalli can we get a little more info - where you're importing from, how you've used the other key before, general reproduction steps?

**Comment by jennypollack** [comment]
Closing for now but feel free to reopen if you're still experiencing the issue.
