### ISSUE TITLE
Network settings: Grammar error in "Current Conversion" 

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#5603]
**Describe the bug**
In the Custom RPC editor, the first item is labeled "Current Conversion" and the second is "Primary Currency."  In this context, it seems like that first word should be "Currency" instead of "Current."  

**To Reproduce**
1. Install MetaMask and create an account or log in to an existing install.
2. Click on the MetaMask icon in the browser.
3. Click the Network selector (where it might say "Main Ethereum Network" in the upper right).
4. Click "Custom RPC" (the last item in the list). 
5. The network selector disappears and the UI changes to this:
![custom rpc editor](https://user-images.githubusercontent.com/563406/47506147-8291d480-d83d-11e8-97d7-75ebfef77760.PNG)

**Expected behavior**
In context with the second item focusing on "Currency," and with the default option in the list being "USD - United States Dollar," the word "Current" looks like a grammatical error where the word "Currency" should appear. 

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 70.0.3538.77 (Official Build) (64-bit) (cohort: 70_77_Win)
 - MetaMask Version: 4.16.0
 - New / Beta UI

**Comment by bdresser** [comment]
If you toggle the setting, you'll notice that we show both ETH and whichever fiat you've chosen to convert to. The `primary currency` option just dictates which is shown more prominently, so we feel the wording is correct.

Also, this is the "Settings" page, not just the Custom RPC menu! Clearly we've crammed a lot of stuff in here and a re-organization with some more targeted menus is in order :)

Closing this one - thanks for all your feedback @wbt.

**Comment by bdresser** [comment]
whoops, misunderstood - you're suggesting "Current Conversion" --> "Currency Conversion" ?

Makes sense to me, @alextsg what do you think?

**Comment by wbt** [comment]
Yep, this one should be a 5 minute fix in some text file.  I was going to come back to it after finishing describing the other bugs.

**Comment by wbt** [comment]
I take that back...the project's pretty well translated!  
The English version can be fixed in [app/_locales/en/messages.json:250](https://github.com/MetaMask/metamask-extension/blob/7852269ed156787eb279e0b55d643c4c13c04020/app/_locales/en/messages.json#L250), but other translations might need updating too.  At least the ones that I understand reasonably well appear to have directly translated "current" instead of "currency."

**Comment by alextsg** [comment]
@bdresser Yep that makes sense

@wbt One way around this and to prevent mistranslations would be to create a new key, ie. `currencyConversion`, and to use that instead. Languages that don't yet have a translation for `currencyConversion` will just have that string displayed in English to be translated later.

**Comment by wbt** [comment]
@alextsg That is a valid approach, though having another language's equivalent of "current conversion" is probably a better transition state than showing the English.  What's the translation process like on this project?

**Comment by alextsg** [comment]
@wbt The typical process is that a translation is added to the English file, then people using other languages see an English string in the app and create a separate pull request to add a translation for it. (Though ambitious people will add a translation for every language using Google translate, but I can't verify the accuracy of those translations) My point is that if we're changing `app/_locales/en/messages.json` to have `"currentConversion"` => `"Currency Conversion"`, it's an incorrect translation and can be misleading. Furthermore, it's likely that people using other languages don't notice this change, and this never gets corrected in other languages.
