### ISSUE TITLE
NewUI: Custom RPC editor scroll bar mostly hidden

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#5604]
**Describe the bug**
The vertical scroll bar in the custom RPC settings UI is mostly hidden under a taller but inactive scroll bar on the right side of the popup. 

**To Reproduce**
1. Install MetaMask and create an account or log in to an existing install.
2. Click on the MetaMask icon in the browser.
3. Click the Network selector (where it might say "Main Ethereum Network" in the upper right).
4. Click "Custom RPC" (the last item in the list). 
5. The network selector disappears and the UI changes to this:
![custom rpc editor](https://user-images.githubusercontent.com/563406/47506147-8291d480-d83d-11e8-97d7-75ebfef77760.PNG)

Notice that on the right side, there's a full-height inactive vertical scroll bar.
There's also a shorter scroll bar for the Settings tab, which is necessary to scroll down to enter the RPC URL.  This shorter scroll bar is mostly hidden under the larger inactive one.  

**Expected behavior**
The primary expected behavior is that I shouldn't have to scroll to reach the most important settings, but that's issue #5605.  If I do have to scroll to change any of the settings (which will happen at least sometimes), the expected behavior is that the scroll bar is visible and accessible, not mostly hidden under an inactive UI element.   The focus of the expected behavior for this issue is that **the scroll bar for the "Settings" tab is fully visible.** Removing the taller inactive scroll bar seems like a useful but not 100% necessary step towards achieving this expected behavior. 

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 70.0.3538.77 (Official Build) (64-bit) (cohort: 70_77_Win)
 - MetaMask Version: 4.16.0
 - New / Beta UI

**Comment by bdresser** [comment]
@tmashuang or @alextsg are either of you able to reproduce? I only get one scrollbar

**Comment by whymarrh** [comment]
I too only get one scrollbar. @wbt ping us if you're able to reproduce this on the latest MetaMask and we can re-open and investigate.

**Comment by wbt** [comment]
It appears the other scrollbar may only appear after clicking the network selector dropdown (while viewing Settings), if there are enough networks in the list (I have mainnet, the 3 big testnets, 5 others, and then Custom RPC).
