### ISSUE TITLE
CustomRPC option in network selector does nothing when logged out

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#5606]
**Describe the bug**
Choosing "Custom RPC" from the network selector, when logged out, dismisses the network selector but does not change anything else in the UI, does not offer any opportunity to enter custom RPC URL, and does not display any message. 

**To Reproduce**
1. Install MetaMask in a browser.  
2. Connect to the main Ethereum Network.
3. Log out or restart the browser. 
4. Click on the MetaMask icon.  See this:
![metamask welcome back mainnet](https://user-images.githubusercontent.com/563406/47505587-6ccfdf80-d83c-11e8-9b83-1c89539b2faa.PNG)
5. Click the Network selector (where it says "Main Ethereum Network" in the upper right).
6. Click "Custom RPC" (the last item in the list). 
7. The network selector disappears, and the display is back to the screenshot in step 4. 
8. Log in.
9. Repeat steps 5-6.  
10. The network selector disappears and the UI changes to this:
![custom rpc editor](https://user-images.githubusercontent.com/563406/47506147-8291d480-d83d-11e8-97d7-75ebfef77760.PNG)

**Expected behavior**
The primary expected behavior is that the UI shown in Step 10 is shown in step 7.  

Note: Because the "Info" tab is accessed by first selecting Custom RPC, implementing this would also likely address Issue #5601.

If for some (e.g. security) reason this is a bad idea, then some message should be shown to the user saying "You must log in before creating a Custom RPC." 

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 70.0.3538.77 (Official Build) (64-bit) (cohort: 70_77_Win)
 - MetaMask Version: 4.16.0
 - New / Beta UI

**Comment by wbt** [comment]
This comment hereby replaces the reference to #5601 with one to #5589.

**Comment by whymarrh** [comment]
I think this would be solved by addressing #5589, yeah? If so, @wbt would you be cool with us closing this as a duplicate of that one?

**Comment by wbt** [comment]
@whymarrh I could be wrong here but I think not quite, because of issue #5609.  Suppose I can't connect to mainnet (e.g. no Internet connection, but in theory should still be able to develop from localhost).  Even if #5598 allows settings to be accessed when logged out, that won't work when there's an overlay over most of the area.  
I would generally prefer leaving the Issue open until one can walk through the steps above and get the expected behavior.

**Comment by whymarrh** [comment]
> If for some (e.g. security) reason this is a bad idea, then some message should be shown to the user saying "You must log in before creating a Custom RPC."

How about we only show actual networks when you're logged out? (i.e. hide the custom RPC option when you're logged out.)

**Comment by wbt** [comment]
> How about we only show actual networks when you're logged out? (i.e. hide the custom RPC option when you're logged out.)
That seems like a bad idea.  For example, suppose you're offline and want to do some development using localhost.  Since you can't connect to a network, you can't log in, and if you haven't **previously** added that localhost network, without the Custom RPC option being available to add it, you'd be hosed.

**Comment by whymarrh** [comment]
That's fair. That said, I think your point re-affirms that the expected behaviour (as your noted in the OP) is to show the settings screen while you're logged out (i.e. #5589). I think it makes sense to merge this with that.

**Comment by wbt** [comment]
There are ways of fixing #5589 which address this Issue and ways of fixing #5589 which do not.  I would prefer the latter, but we won't know 100% sure until the fix has actually been committed.  **After that happens** we can come back here and see if this Issue is addressed.  We should leave this Issue open until then, so that we can come back here and have the reminder that this is an open issue.

The communication link of "let's try to address this along with another issue, please see discussion over there" is helpful, but I don't quite understand the emphasis being placed on spending time trying to close valid, well-documented, still-unaddressed Issues instead of actually fixing open Issues in this project, even if time on the latter task is focused on higher-priority Issues.

**Comment by wbt** [comment]
I don't think this should be closed without an improvement.

**Comment by wbt** [comment]
I still don't think this should be closed without an improvement.

**Comment by gauthierpetetin** [comment]
Hi @wbt , is this still a valid issue in the latest version of Extension. When I try to reproduce, I log out, I open network selector but the `Add Network` button is greyed out, so I'm not able to add a custom network, are you?
<img width="353" alt="Screenshot 2024-04-12 at 15 57 28" src="https://github.com/MetaMask/metamask-extension/assets/7071180/dfdebd30-e9a0-4e1b-bc69-6ca183eea5ab">

**Comment by wbt** [comment]
No, and I find that annoying for the same offline-local-development reason I cited over a half decade ago.

**Comment by gauthierpetetin** [comment]
> Since you can't connect to a network, you can't log in

@wbt is this still the case?
