### ISSUE TITLE
Show origin domain on Confirm screen and tx detail view

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#5611]
Show origin that suggested the transaction. We already capture this on `txMeta.origin`
We should also show this on the confirmation screen.

**Comment by bdresser** [comment]
From the above duplicate, user suggests also including
- URL
- Title
- Favicon

and particularly emphasizes that this is important on the tx history (so the list of tx has some useful context)

**Comment by bdresser** [comment]
Also should include on signing screens as mentioned in https://github.com/MetaMask/metamask-extension/issues/6071

**Comment by bdresser** [comment]
Also time of transaction initiation (as requested in https://github.com/metamask/metamask-extension/issues/6433)
