### ISSUE TITLE
Unknown function => where to register it

### ISSUE THREAD

**Issue by guix77** [MetaMask/metamask-extension#5616]
MM shows "Unknown function", how to register our solidity functions to make display the nice function name on MM ?

I only found this unofficial & incomplete way for the moment (not tested) : https://ethereum.stackexchange.com/questions/59678/metamask-shows-unknown-function-when-calling-method-send-function

I thought that publishing the source code on Etherscan would do it, but is seems that no...

**Comment by bdresser** [comment]
@guix77 that answer on stackexchange is correct!

We rely on the parity on-chain function registry ( at `0x44691B39d1a75dC4E0A0346CBB15E310e6ED1E86`) to pull function names. This is the best decentralized method we have to understand what the function is called. 

We've discussed also using other services (https://github.com/MetaMask/metamask-extension/issues/5057) but haven't implemented yet.

**Comment by bdresser** [comment]
@Araton95 we plan to document the process very shortly! follow https://github.com/MetaMask/metamask-extension/issues/5808 for updates
