### ISSUE TITLE
npm metamask extension test errors 

### ISSUE THREAD

**Issue by Sentrycs** [MetaMask/metamask-extension#5617]
After gulp bulild we are running npm test and getting following errors:
[MetaMaskBuildCmdPrintScreen1.txt](https://github.com/MetaMask/metamask-extension/files/2519595/MetaMaskBuildCmdPrintScreen1.txt)

**Browser details (please complete the following information):**
 - OS: Win10 64bit
 - Browser 
 - MetaMask Version latest from Github
 - Node.js version 8.12.0
-npm version 6.4.1

**Comment by tmashuang** [comment]
https://github.com/libxmljs/libxmljs/issues/253
https://stackoverflow.com/questions/37458918/node-js-could-not-locate-the-bindings-file#37459192

**Comment by Sentrycs** [comment]
@tmashuang thanks for the comment. Tried it - no change : the errors remain.

**Comment by tmashuang** [comment]
Might have to downgrade a node version, see https://github.com/MetaMask/metamask-extension/issues/5668 so we can follow the same thread for Windows dev environment.
