### ISSUE TITLE
Web3 provider stops fetching latest data

### ISSUE THREAD

**Issue by yvon** [MetaMask/metamask-extension#5618]
Injected web3 stops synchronizing blockchain blocks.

**To Reproduce**

It seems to happen after a while, when Chrome is left open. It happens to me approx once a day but I have colleagues that never faced this issue :/

When it happens this JS code (from any chrome tabulation) returns an old block and it's stuck (it never changes):

```
web3.eth.getBlock('latest', function(e, { timestamp }) { console.log(new Date(timestamp * 1000)) });
```

To solve it I have to kill all my chrome instances or reset my account from Metamask.

**Browser details:**
 - OS: Arch Linux and OSX
 - Browser: chrome and chromium
 - MetaMask Version: 4.16.0
 - New UI

**Comment by olaf89** [comment]
I have same problem, you can reset metamask account to "fix" that, but its still a pain and most users won't do that

**Comment by bdresser** [comment]
@yvon thanks for reporting. this was fixed yesterday in https://github.com/MetaMask/metamask-extension/pull/5614, should be released shortly.
