### ISSUE TITLE
Extra scrollbar appears on right side of extension popup. This issue began with Chrome version 70

### ISSUE THREAD

**Issue by celwell** [MetaMask/metamask-extension#5622]
**Describe the bug**
Extra scrollbar appears on right side of extension popup. This issue began with Chrome version 70

**To Reproduce**
1. Have Chrome 70 update
2. Click MetaMask extension icon
3. See scrollbar always on right side; looks bad and doubled on many pages.

**Expected behavior**
Prior to Chrome 70 that scrollbar was not there and popup had cleaner appearance.

**Screenshots**
![image](https://user-images.githubusercontent.com/1365334/47592230-4c308400-d927-11e8-8285-d2659e0b83c7.png)

**Browser details (please complete the following information):**
 - OS: OSX 10.13.2
 - Browser: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
 - MetaMask Version: 4.16.0
 - New / Beta UI

**Comment by MicahZoltu** [comment]
Same problem on Firefox, even more noticeable too: 
![image](https://user-images.githubusercontent.com/886059/48307999-6f4c6c00-e594-11e8-84fe-8a9abd467105.png)

Scrollbar shows up on most (all) views, info is just a convenient one to take a screenshot of while retaining privacy.

Windows 10
Firefox 63.0.1
MetaMask 1.17.1

**Comment by celwell** [comment]
I'm a little confused. This issue went away for a few days, and I thought maybe a new Chrome update has coincidentally resolved the issue. However, looking at it again today, the issue is back.

**Comment by whymarrh** [comment]
@celwell @MicahZoltu do you still see this on the latest MetaMask? I can only see one scrollbar. Ping us if you either of you can still reproduce this and we can re-open.

**Comment by celwell** [comment]
I don't see it anymore (OSX - Chrome). Looking great, keep up the good work!

**Comment by MicahZoltu** [comment]
Problem appears to be resolved.
