### ISSUE TITLE
estimateGas freeze on contract

### ISSUE THREAD

**Issue by afiorenza** [MetaMask/metamask-extension#5624]
I'm trying to estimate the gas required in order to execute this function:

```
function transferFunds() public returns (bool){
          require(owner == msg.sender);
          owner.transfer(address(this).balance);
          emit transfer(owner, address(this).balance);
          return true;
}
```

If i'm the owner the estimation is fine and i can execute the transaction. But if i'm not the owner, the estimateGas function freeze and not return error or gas estimation. I test this estimation on a local web3 and is working fine.

This is the code i'm using to estimate the gas:

```
try {
      const gas = await instance.methods[method](...Object.values(params)).estimateGas({
        from: sender,
        value: abi.payable
          ? web3.utils.toWei(this.state.value, 'ether')
          : null
      });

      return gas;
    } catch (error) {
      console.log(error);
}
```

**To Reproduce**
1. Go to https://explorer.bitsign.io/address/0x1287214888867000A5bed29D793a2dBd4c629596
2. Click on Write button.
3. Click on transferFunds submit button.
4. Check that any error is raised and is you press accept button Metamask doesn't allow to execute the transaction

**Expected behavior**
An error should raise.

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - MetaMask Version 4.16.0
 - New UI

**Comment by tmashuang** [comment]
What network is this on, the repro stops a step 3 which tells me that I am on the wrong network?

**Comment by afiorenza** [comment]
I'm on a private network called Bitsign. The RPC url is [http://rpc-legacy.bitsign.network](http://rpc-legacy.bitsign.network). Let me know your address if you need some eths to test.

**Comment by tmashuang** [comment]
`[0x]b3d40CB475f9Dc46b59dc30Fd43deBE382f7b45A`

**Comment by tmashuang** [comment]
Closing old issue, I am unable to reproduce a number of contract deploys and interactions. Might have been caused by the custom network.
