### ISSUE TITLE
After importing account, balance stays 0 ETH

### ISSUE THREAD

**Issue by rajurandhav** [MetaMask/metamask-extension#5627]
**Describe the bug**
After importing account using a private key, a new account with 0 ETH balance is created (!) 
(On Etherscan, the old address clearly shows the actual balance.)
Same issue occurs even if I try to import the account using my correct seed phrase of the original main account. 

**Browser details (please complete the following information):**
 - OS: [iOS]
 - Browser [Chrome]
 - MetaMask Version [4.16.0]
 - Old UI as well as New / Beta UI
<img width="1195" alt="screen shot 2018-10-28 at 4 51 47 pm" src="https://user-images.githubusercontent.com/44545107/47615204-20053680-dad2-11e8-8ef2-bf41ba84bb46.png">
<img width="1234" alt="screen shot 2018-10-28 at 4 52 01 pm" src="https://user-images.githubusercontent.com/44545107/47615205-209dcd00-dad2-11e8-8a2a-48a08e353bf8.png">

**Comment by bdresser** [comment]
it looks like those are two different accounts - you can see in the MetaMask screenshot below where it says "details" that the address begins with `0x00c9` and ends with `1312`. The one shown in Etherscan doesn't match.

Could you double / triple check that you're looking at the same accounts? And if you're still having trouble, please reach out to support@metamask.io and we'll be able to help you there.
