### ISSUE TITLE
Add custom name to private networks/custom RPCs

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#5630]
**What problem are you trying to solve?**
I'm frequently changing between private networks and want to see at a glance which network I'm on, ideally with some human-readable name, instead of just "Private Network:"
![image](https://user-images.githubusercontent.com/563406/47668170-1a652a80-db7e-11e8-8065-b892ed40ab9e.png)
Why should only large public testnets be nameable?  

**Describe the solution you'd like**
I'd like the ability to assign a custom name to RPCs, similar to how I can assign a custom name to an account number. 
Also, in the popup where I'm asked to approve a transaction being sent, I'd like to be able to see which network I'm on when sending the transaction.  In the upper right, there's a box containing a question mark in a circle with the words "Custom RPC" but clicking on that circle (or anywhere else in that box) does nothing, nor does hovering over it show a tooltip with the URL.  

![image](https://user-images.githubusercontent.com/563406/47667859-695e9000-db7d-11e8-87e2-d527fb7706c1.png)

I would like for the box to say "Development Server" or "Test Server" or whatever other name I want to affiliate with the RPC URL, and on hover see a tooltip that shows me it's using RPC https://12.34.56.78:9001 or something like that.

**Comment by wbt** [comment]
An implementation of the UI from @bdresser's September 12 [comment](https://github.com/MetaMask/metamask-extension/pull/5134#issuecomment-420746241) on issue #5134 would likely address at least part of this Issue; there may be some residual parts regarding the tooltip on hover to show the URL.

**Comment by wbt** [comment]
This appears fixed in version 4.17.1 likely in [PR 5134](https://github.com/MetaMask/metamask-extension/pull/5134).

**Comment by filips123** [comment]
Pull request #5134 only adds `chainId` field, but network will still be displayed as URL in menu. Is it possible to change it?

**Comment by wbt** [comment]
@filips123 What version are you using?  When I set a custom name for the network (see field in [this](https://github.com/MetaMask/metamask-extension/pull/5134#issuecomment-420970887) screenshot or [later](https://github.com/MetaMask/metamask-extension/pull/5134#issuecomment-425758480) [ones](https://github.com/MetaMask/metamask-extension/pull/5134#issuecomment-431335109)) that custom name shows up in the upper right and in the drop-down that appears when I click on the network selector.

**Comment by filips123** [comment]
@wbt It is OK! I change wrong field.
