### ISSUE TITLE
Hide links to etherscan when no block explorer is specified for a custom network

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#5631]
**Describe the bug**
The transaction confirmation popup looks like this:
![Confirmed Transaction](https://user-images.githubusercontent.com/563406/47668547-22719a00-db7f-11e8-8e7b-a267100457a7.png)

Clicking on it will open Etherscan to view the transaction on mainnet.  

However, if the transaction was not on mainnet, Etherscan will (most likely) not find the transaction OR show information about a transaction **other than** the one the user initiated. It **definitely** will **not** show information about the transaction that was just confirmed on a private network. 

**To Reproduce**
1. Install MetaMask and create an account or log in to an existing install.
2. Connect to a custom RPC running some dapp.
3. Visit the dapp in a browser, trigger a transaction, and approve it. 
4. Wait until the transaction is mined. 
5. See the popup similar to screenshot above. 
6. Click on the popup. 
7. Etherscan will open in your default browser and say it can't find information about that transaction.

**Expected behavior**
A. "View on Etherscan" does not appear if the transaction was executed on a private network.  In this case, the popup should not contain a link to Etherscan and Etherscan should not open if clicking on the popup.

B. If the transaction was executed on a large public testnet, it should open the Etherscan for that testnet (example links: [Rinkeby](https://rinkeby.etherscan.io/tx/0x6e40a26ac4f403099e88b4335233f0d1c479d52e9c16f576eebadfa16e624e1f), [Ropsten](https://ropsten.etherscan.io/tx/0xc46e2440914f6762ab2fa09e06451e64ff7c3a56b027f147d58f9c50303ac71f), [Kovan](https://kovan.etherscan.io/tx/0x0948ad35ed0b3edae798e288ad3c26d715878e07d55a9109a08c8d1bcddf96fa)).  I have not tested to see if this is already implemented. 

C. In cases where there is an Etherscan view of the transaction (large public net), there is a line break before the word "View."  (This might be a separate Issue.)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 70.0.3538.77 (Official Build) (64-bit) (cohort: 70_77_Win)
 - MetaMask Version: 4.16.0
 - New / Beta UI

**Comment by bdresser** [comment]
We should disable Etherscan links for custom networks until we find a simple way to let people enter their own custom block explorers when using the custom RPC feature

**Comment by wbt** [comment]
As a UI design point for feedback, are there any objections to changing "View on Etherscan" to "View on block explorer" more generally, when editing to address this issue?

**Comment by MicahZoltu** [comment]
Note: I use a custom network that points to mainnet for security (don't trust third party node providers and all that jazz).  In whatever UI is created, there should be an option to mark a custom endpoint as mainnet.

Also, I have multiple custom endpoints, some of them point at private networks (no block explorer).

**Comment by wbt** [comment]
@MicahZoltu The Network Settings menu requested [here](https://github.com/MetaMask/metamask-extension/issues/5790#issuecomment-461838951) would allow you to just replace the default provider for mainnet, and leave out block explorers for networks that don't have them.

**Comment by IvanRF** [comment]
@bdresser this is an old issue, but the notification link is still pointing to `https://etherscan.io/tx/${transaction_id}` for a custom RPC network.

> We should disable Etherscan links for custom networks until we find a simple way to let people enter their own custom block explorers when using the custom RPC feature

Since the option `Block Explorer URL` was already added, is it possible to used that URL on the notification links too?

**Comment by wbt** [comment]
It would also be nice to drop "View on etherscan" altogether when there is no block explorer for a custom network.

**Comment by BboyAkers** [comment]
@Gudahtt  working on this 🙂

**Comment by BboyAkers** [comment]
These two PR's should fix this issue 🙂
https://github.com/MetaMask/etherscan-link/pull/29
https://github.com/MetaMask/metamask-extension/pull/10455

**Comment by IvanRF** [comment]
> @bdresser this is an old issue, but the notification link is still pointing to `https://etherscan.io/tx/${transaction_id}` for a custom RPC network.
> 
> Since the option `Block Explorer URL` was already added, is it possible to use that URL on the notification links too?

@BboyAkers thanks for the PR's! Since you made those fixes, I believe you will be able to fix what I mentioned 😃 .
I just saw there is an open issue too: #7864

In your last PR's the link was removed if the network is not a valid prefix for etherscan.io. However, `Block Explorer URL` can be used if it was set for the custom RPC network.

**Comment by BboyAkers** [comment]
Hmmm interesting, I'll dig into this @IvanRF  🙂

**Comment by IvanRF** [comment]
> Hmmm interesting, I'll dig into this @IvanRF 🙂

@BboyAkers Excellent! thanks! 👏 👏 👏
