### ISSUE TITLE
Extension causes taobao to fail to load properly

### ISSUE THREAD

**Issue by ckykenken** [MetaMask/metamask-extension#5638]
**Describe the bug**
TaoBao (www.taobao.com) (淘寶網) fails to load properly, just the layout shell, and no content, when the extension is enabled
![image](https://user-images.githubusercontent.com/26035978/47705615-fed35000-dc61-11e8-99d7-1bcd6cdcb689.png)
Here is the log file generated from Chrome console:
[world.taobao.com-1540888725060.log](https://github.com/MetaMask/metamask-extension/files/2528719/world.taobao.com-1540888725060.log)

**To Reproduce**
1. Install MetaMask and enable it
2. Navigate to https://www.taobao.com

**Expected behavior**
The site looks like this if it is loaded properly
![image](https://user-images.githubusercontent.com/26035978/47705786-8ae57780-dc62-11e8-95de-a75dbad32250.png)

**Browser details (please complete the following information):**
- OS: Windows 10
- Browser: Chrome 70.0.3538.77 (Official Build) (64-bit) (cohort: 70_77_Win)
- MetaMask Version: 4.16.0
- New / Beta UI

**Comment by bdresser** [comment]
<img width="958" alt="screen shot 2018-10-30 at 10 48 50 am" src="https://user-images.githubusercontent.com/1016190/47709804-7046da80-dc31-11e8-8eb5-6dbe1ef3744a.png">

**Comment by tmashuang** [comment]
As of this comment, v8.1.9, and on Firefox this is no longer an issue. Navigating and interacting to the site is working as intended.

**Comment by eligao** [comment]
Unfortunately, this is still an issue on Chrome 90 with Metamask 9.4.0
![image](https://user-images.githubusercontent.com/2323992/118000921-d40cfb00-b378-11eb-9c1a-3c255aaac856.png)
