### ISSUE TITLE
Errors when sending transaction to ledger

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#5641]
> Uncaught Error: new BigNumber() not a base 16 number: null

![screen shot 2018-10-30 at 3 05 07 pm](https://user-images.githubusercontent.com/799573/47753593-54553000-dc55-11e8-96c8-81271a69677d.png)

> Uncaught (in promise) Error: invalid transport instance

![screen shot 2018-10-30 at 3 07 19 pm](https://user-images.githubusercontent.com/799573/47753656-89fa1900-dc55-11e8-9b6c-47b568fc6449.png)

**Comment by wjmelements** [comment]
MetaMask version is 4.16.0. Chrome version is 70.0.3538.77.

**Comment by wjmelements** [comment]
![screen shot 2018-10-30 at 3 13 38 pm](https://user-images.githubusercontent.com/799573/47753919-6e434280-dc56-11e8-93d9-8b83704e51a6.png)

**Comment by wjmelements** [comment]
@brunobar79 ptal when you get a chance

**Comment by wjmelements** [comment]
![screen shot 2018-10-30 at 3 19 56 pm](https://user-images.githubusercontent.com/799573/47754189-4b655e00-dc57-11e8-8f2e-0abb6f2337d4.png)

**Comment by wjmelements** [comment]
The immediate issue seems to be the invalid transport instance error.

**Comment by wjmelements** [comment]
I was using the Ledger incorrectly so this issue should be subdivided into surfacing the error to the user better, as MyEtherWallet does, and addressing the BigNumber issue, which seems to be separate. Stringifying the error should be sufficient for the first item.

**Comment by brunobar79** [comment]
@wjmelements  Thanks for reporting! I'll take a look next week.

**Comment by bdresser** [comment]
closing, happy to re-open with reproduction steps.
