### ISSUE TITLE
Popup with a question doesn't open and approves set by default

### ISSUE THREAD

**Issue by ermo4enkov** [MetaMask/metamask-extension#5643]
**To Reproduce**
1. Go to console
2. Call window.ethereum.enable()
3. Popup doesn't appear on the screen
4. Call window.ethereum._metamask.isEnabled() it returns true
5. All of these steps work without my login to metamask

### !!! Also, it works even user didn't login in the metamask !!!

**Expected behavior**
- **window.ethereum.enable()** expect to see a popup
- **window.ethereum._metamask.isEnabled()** mustn't return true without approval
- **window.ethereum.enable()** method can't work without user login

**Browser details (please complete the following information):**
 - **OS**: macOS Mojave
 - **Browser**: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
 - **MetaMask**: Version 4.16.0 [e6bc949]
 - Beta UI

**Comment by bitpshr** [comment]
Hi @ermo4enkov, thanks for reaching out. We're having trouble reproducing this issue. We downloaded the [latest build](https://github.com/MetaMask/metamask-extension/pull/4703#issuecomment-434615101), manually installed it, and verified `ethereum.enable()` works as expected.

Could you please verify that the "privacy mode" settings option is enabled during your testing?
