### ISSUE TITLE
After login, Metamask disappears after a few seconds.

### ISSUE THREAD

**Issue by Binksma** [MetaMask/metamask-extension#5645]
**Describe the bug**
After login, Metamask disappears from the screen after a few seconds. The extension logo in the plugin bar also disappears.

**To Reproduce**
1. Log in
2. Wait 2 or 3 seconds.

**Expected behavior**
Stay on the screen and in plugin bar.

**Screenshots**
Would be useless.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - MetaMask Version: 4.16.0
 - UI: New / Beta UI

**Additional context**
Please help.
Thank you. 
Michiel

**Comment by tmashuang** [comment]
It is possible that permissions are needed to be reconfirmed in the extensions list.

**Comment by Binksma** [comment]
Hi Thomas,

Not sure what it was but it works fine now. Thx for your swift reply!
________________________________
Van: Thomas Huang <notifications@github.com>
Verzonden: donderdag 1 november 2018 19:18
Aan: MetaMask/metamask-extension
CC: Michiel Binksma; Author
Onderwerp: Re: [MetaMask/metamask-extension] After login, Metamask disappears after a few seconds. (#5645)


It is possible that permissions are needed to be reconfirmed in the extensions list.
