### ISSUE TITLE
wallet_watchAsset will not accept "0" for decimals option

### ISSUE THREAD

**Issue by jmcnevin** [MetaMask/metamask-extension#5647]
**Describe the bug**
If you try to set the number 0 for the decimals option for wallet_watchAsset, the test here (https://github.com/MetaMask/metamask-extension/blob/9514c56f0754fe9c3d6cef6f9e543f8d50a616db/app/scripts/controllers/preferences.js#L586) thinks you haven't configured a value at all.

**To Reproduce**
```js
web3js.currentProvider.sendAsync(
    {
      method: "metamask_watchAsset",
      params: {
        type: "ERC20",
        options: {
          address: "0x000...",
          symbol: "FOO",
          decimals: 0
        }
      },
      id: Math.round(Math.random() * 100000)
    },
    console.log
  );
```

**Expected behavior**
Allow zero as a valid decimal value.

**Browser details (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - MetaMask Version: 4.16.0
 - Old UI or New / Beta UI: New

**Comment by estebanmino** [comment]
Thanks for pointing this @jmcnevin !
