### ISSUE TITLE
allow the use of file://

### ISSUE THREAD

**Issue by dave-dm** [MetaMask/metamask-extension#5652]
We're trying to build a web app that is as censorship resistant as possible, which would mean distributing it as a stand alone html file that the user can run on their computer. It is not realistic to expect the user to run a web server.

What are the security vulnerabilities that prevent metamask from working with file:// ?

We don't need to access any files, we just need metamask to inject web3 as if it was http

**Comment by dave-dm** [comment]
Follow up on this, we posted on reddit about our app and it got 400 upvotes, so I think people are interested in using the file:// protocol considering how it removes the host centralization (if it can be done securely)

link: https://www.reddit.com/r/ethereum/comments/9ux6x4/weve_been_working_on_an_uncensorable_platform_for/

**Comment by kumavis** [comment]
Metamask injection doesn't work with `file://`
There may be a work around but I'm not aware of one

**Comment by whymarrh** [comment]
Indeed, as @kumavis noted this isn't possible currently. We can re-open this when things change.
