### ISSUE TITLE
how to add a different  hd derivation path 

### ISSUE THREAD

**Issue by liwei00wade** [MetaMask/metamask-extension#5655]
I want to add a different hd derivation path,
Could you give me some document or example.

**Comment by brunobar79** [comment]
We don't support that through the UI but feel free to generate a custom build and do it.  
This is the package that has handles our HD accounts: https://github.com/MetaMask/eth-hd-keyring/blob/master/index.js#L8

I recommend you to take a look at the README of that repo for more info.

**Comment by liwei00wade** [comment]
@brunobar79 thank you.

I am sorry for my JS;
Could you please give me an example how to use eth-hd-keyring with metamask.
