### ISSUE TITLE
Don't reset the extension on close - Display the last screen visited along with its data

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#5657]
**What problem are you trying to solve?**
When I need to import my account via "import with seedphrase" flow in the Firefox extension:

- I open the extension
- go to "import with seedphrase screen"
- I'm asked to insert seedphrase and password
- I focus away from the extension (it closes) and open my password manager
- I copy my seedphrase from my password manager
- I go back to MetaMask and I'm not in the import with seedphrase, I'm back in the splash page.
- I click on the "import with seedphrase" again
- Past in my seedphrase
- In the password field, I want to use the same password I saved in my password manager for my account
- I focus away from the extension (MetaMask closes) and open my password manager
- I copy my password from my password manager
- I go back to MetaMask and I'm not in the import with seedphrase page anymore, I'm back in the splash page.
- I click on the "import with seedphrase" again
- My seedphrase is no longer in the import with seedphrase screen anymore

**Describe the solution you'd like**
Don't reload the extension! Display the last screen that was visited and persist the data that was inserted in the input fields (in this case the seedphrase and/or passwords)

**Additional context**
It's very frustrating to loose my place (context) in the extension when it closes out!

**Comment by bdresser** [comment]
https://github.com/MetaMask/metamask-extension/issues/4206 describes this same pain point with the Send screen & gas customization screen.

As noted there, opening Send as a full-tab would mitigate this issue and have a variety of other positive side-effects

**Comment by Gudahtt** [comment]
We switched the onboarding flow to the fullscreen UI, so the original flow described is no longer an issue.

We do restore the user to the last page they were looking at for some flows (e.g. swaps). We may want to consider a similar approach in more cases going forward, but I think we can close this for now and consider it as completed. We can consider further improvements along these lines separately.
