### ISSUE TITLE
Unable to connect to the Mainnet

### ISSUE THREAD

**Issue by MUSystem** [MetaMask/metamask-extension#5661]
**Describe the bug**
When choosing a main network, the constant rotation of the preloader and then no reaction. It connects to other networks. For Chrome & Firefox extensions
![screenshot_80](https://user-images.githubusercontent.com/41549798/47951739-d60acd80-df75-11e8-8cc0-df2253215cd9.png)

**To Reproduce**
1. Open the browser.
2.  Click on the extension icon. 
3. Message: Connecting to Main Ethereum Network.....
4. Message: Connecting to Main Ethereum Network.....

**Expected behavior**
You should be prompted to enter a password.

**Screenshots**
Screenshot was added

**Browser details (please complete the following information):**
 - OS: Win10
 - Browser Chrome & Firefox 
 - MetaMask Version: 4.17.0 
 - Beta UI

**Comment by mschristensen** [comment]
Also experiencing this in Chrome 70.0.3538.77 on macOS High Sierra 10.13.6

**Comment by MUSystem** [comment]
Update from topic starter. If you wait a few minutes, then the connection occurs. But waiting so long is unbearable. If you enable debugging in Firefox browser, you can see some errors. It may be useful to solve the issue. ![screenshot_81](https://user-images.githubusercontent.com/41549798/47956055-f2c3f700-dfaf-11e8-93d8-b33647be0878.png)

**Comment by danfinlay** [comment]
We've fixed the issue by reverting a change in #5662. We're deploying the fix in a few minutes in [version 4.7.1](https://github.com/MetaMask/metamask-extension/pull/5663).
