### ISSUE TITLE
Mascara cannot load iframe

### ISSUE THREAD

**Issue by psychoplasma** [MetaMask/metamask-extension#5666]
**Description**
1. After building and trying to run metamask-extension/mascara server, after starting the server, when trying to open `localhost:9001` and `localhost:9002`, `ui.js`, `proxy.js` and `background.js` files are being fetched from the wrong paths, `./scripts/ui.js` `./proxy.js` and `./scripts/background.js` respectively.

2. In `mascara/src/proxy.js` file, `controller` property is being tried to access directly from `background` object which is an instance of `sw-controller` which cause an error. Actually `sw-controller` object does not have a direct `controller` property, instead it has `serviceWorkerApi.controller` property.

**To Reproduce**
Run
1. `gulp dev:mascara`
2. `node ../../mascara/example/server.js` in `./dist/mascara` dir

**Expected behavior**
1. I guess, `ui.js`, `background.js`, `proxy.js` files should be fetched from `./ui.js`, `./background.js` and `../proxy.js` respectively or in build, the file dirs should be adjusted accordingly.
2. In `mascara/src/proxy.js` file, instead of accessing `background.controller` directly, it can be accessed through `serviceWorkerApi.controller` I guess. At least, it works in that way as a workaround.

**Browser details (please complete the following information):**
 - macOS 10.14
 - Chrome
 - mascara

**Comment by bdresser** [comment]
hey @psychoplasma - the Mascara project is no longer maintained
