### ISSUE TITLE
how to  create a BTC address with   keyring in metamask?

### ISSUE THREAD

**Issue by liwei00wade** [MetaMask/metamask-extension#5667]
Could you help me to  create a BTC address with metamask and keyring,
Send me a simple  example.

**Comment by Raiane234** [comment]
Ola  Gostaria de criar minha carteira metasmak

**Comment by liwei00wade** [comment]
@Raiane234   
I am sorry, 
I do not understand "Ola Gostaria de criar minha carteira metasmak"

**Comment by bdresser** [comment]
@liwei00wade we don't yet support creating BTC addresses via MetaMask

see https://github.com/MetaMask/metamask-extension/issues/1820

**Comment by liwei00wade** [comment]
@bdresser   thank you.
