### ISSUE TITLE
npm start fails when running metamask latest version downloaded from GitHub

### ISSUE THREAD

**Issue by Sentrycs** [MetaMask/metamask-extension#5668]
npm start fails when running metamask latest version downloaded from GitHub

**To Reproduce**
1. In CLI screen Go to metamask-extension folder created when download the MetaMask extension source from GitHub
2. Do npm install and then npm start
3. See error

C:\Users\***\Documents\GitHub\Metamask\metamask-extension>npm start

> metamask-crx@0.0.0 start C:\Users\***\Documents\GitHub\Metamask\metamask-extension
> gulp dev:extension

[12:11:05] Using gulpfile ~\Documents\GitHub\Metamask\metamask-extension\gulpfile.js
[12:11:05] Starting 'dev:extension'...
[12:11:05] Starting 'clean'...
[12:11:26] 'clean' errored after 21 s
[12:11:26] Error: EPERM: operation not permitted, unlink 'C:\Users\***\Documents\GitHub\Metamask\metamask-extension\dist\chrome\fonts'
[12:11:26] 'dev:extension' errored after 21 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metamask-crx@0.0.0 start: `gulp dev:extension`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metamask-crx@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2018-11-04T10_11_26_808Z-debug.log

**Browser details (please complete the following information):**
 - OS: win10 64bit
 - Browser  chrome
 -MetaMask Version latest from GitHub built with node.js ver 8.12.0LTS and npm 6.4.1

**Comment by liwei00wade** [comment]
do you have resolved the problem ?

**Comment by Sentrycs** [comment]
@liwei00wade Unfortunately - no.

**Comment by tmashuang** [comment]
As a Windows 10 user, building a development environment on windows can be tricky and a hassle. I have node v8.11.3 and npm v6.1.0, I do not recommend using a node version manger. Download and install older node version directly from node. To help isolate what the issue is, it would be more beneficial to stay on one thread for all the Windows issues.

**Comment by whymarrh** [comment]
@Sentrycs @liwei00wade if you are still having issues feel free to open up a new issue
