### ISSUE TITLE
Local ganache instance is spawned with eth_getLogs 

### ISSUE THREAD

**Issue by hellobart** [MetaMask/metamask-extension#5669]
Custom rpc ganache instance is spawned with `eth_getLogs` when i refresh browser during fetching old transaction. Im using Truffle Contract to filter data. On every tab refresh im getting more `eth_getLogs` each block mined. Do you have any solution to uninstall old filters?

**Comment by tmashuang** [comment]
How are you using filters? As per the web3 api, https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter,  `filter.stopWatching()` is this what you're looking for?

**Comment by zlyojciec** [comment]
Hi @tmashuang 

This is how i fetch old logs: 
```
const e = contract.Transfer( { from: account, to: address }, { fromBlock, toBlock })
const eventResult = await promisifyWeb3(() => e.get())
e.stopWatching()
```

It works fine when i patiently wait for the eventResult. But if i refresh browser tab during Filter call then stopWatching never get called.

**Comment by zlyojciec** [comment]
Looks like a problem is gone after switch from `web3 v0.x / truffle-contract` to `ethers.js`

**Comment by tmashuang** [comment]
Closing old issue, which seems resolved with swapping packages, although the root cause was never determined. If you have any new information, reproduction steps, code examples, etc. feel free to add them.
