### ISSUE TITLE
ethereumjs-vm issue `Missing trie node`

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#567]
Example error:
 `"Missing trie node f2bfeff202e4859980668b9c618dd8b22545bb8c67ae964a5b94f442a543cbce”`
@index.js :79
inside EthereumStore.prototype._updateForBlock

**Comment by flyswatter** [comment]
Does anyone know more about how to reproduce this bug?

**Comment by wanderer** [comment]
wierd

**Comment by wanderer** [comment]
are you using merkle-patricia-trie?

**Comment by kumavis** [comment]
not really sure how this could have come from `EthereumStore` or how it was triggered.
its definitely a `merkle-patricia-trie` error, but idk how we hit it. must have been an eth-call or something
