### ISSUE TITLE
New MetaMask 'enable' doesn't trigger any effect on Chrome

### ISSUE THREAD

**Issue by joelamouche** [MetaMask/metamask-extension#5676]
**Describe the bug**
I followed the instructions witten in https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8 to integrate the new window.ethereum.enable() feature and I get this warning:

Heads up! ethereum._metamask exposes methods that have not been standardized yet. This means that these methods may not be implemented in other dapp browsers and may be removed from MetaMask in the future.

and no effect on the extension, the account being exposed as usual.

**To Reproduce**

As per https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

1. Implement new web3 loading script (below)
2. Download custom MM build
3. Window.ethereum is detected, so the app calls window.ethereum.enable()
3. Nothing happens when reloading the page with privacy mode

**Expected behavior**
A clear description of what you expected to happen.

Some kind of popup asking me authorization to give my address?

**Screenshots**

**Browser details (please complete the following information):**
 - Browser : Chrome
 - MetaMask Version : https://github.com/MetaMask/metamask-extension/pull/4703#issuecomment-435892763

```
// Modern dapp browsers...
    let web3:any;
    if ((window as any)['ethereum']) {
        web3 = new Web3((window as any)['ethereum']);
        try {
            // Request account access if needed
            let res=await (window as any)['ethereum'].enable();
            console.log(res)
        } catch (error) {
            // User denied account access...
        }
    }
    // Legacy dapp browsers...
    else if ((window as any)['web3']) {
        web3 = new Web3((window as any)['web3'].currentProvider);
        // Acccounts always exposed
    }
    // Non-dapp browsers...
    else {
        console.log('Non-Ethereum browser detected. You should consider trying MetaMask!');
      return dispatch(setMetamaskLoadingStage('Error'))
    }
```

**Comment by bdresser** [comment]
hey @joelamouche, the "Privacy Mode" feature will be released in 4.18, either later this afternoon or tomorrow morning. Had a couple things to fix up. Thanks for your patience!

**Comment by joelamouche** [comment]
No problem, let me know!

**Comment by darkellydel** [comment]
https://github.com/MetaMask/metamask-extension/pull/4703#issuecomment-434615101

Metamask v.4.16 has privacy mode if you want to test out your implementation. You can get it in the above link.

**Comment by bdresser** [comment]
v5.0 with this feature has been pushed to the Chrome store, your extension will auto-update soon

**Comment by yucob** [comment]
How to auto-fix this error?
