### ISSUE TITLE
Import JSON Keystore Without Password

### ISSUE THREAD

**Issue by zulhfreelancer** [MetaMask/metamask-extension#5681]
**What problem are you trying to solve?**

I want to import some JSON keystore files into MetaMask. They don't have password. The current version of MetaMask doesn't allow me to proceed if the password is blank.

**Describe the solution you'd like**

Can we add a checkbox with copy like... 

* [✔️] Confirm no password

OR

* [ ✔️] This JSON keystore has no password

...?

**Additional context**

This is what I get now:

![mm](https://user-images.githubusercontent.com/3416976/48026801-0626bc00-e182-11e8-85e4-59ee1479fdc9.png)

Thanks.

**Comment by spalladino** [comment]
Just dropping the validation would be useful. I'm trying to import the account generated by geth in dev mode into Metamask for quick testing, and it's impossible to do so since it's generated with a blank password.

**Comment by dappsar** [comment]
Just load file, then put cursor on password field and press enter key. That skip validation.

**Comment by quantbrothers** [comment]
> Just load file, then put cursor on password field and press enter key. That skip validation.

Now working for now. Metamask 10.22.2 (Firefox)
