### ISSUE TITLE
Script tags added continuously added to <head>

### ISSUE THREAD

**Issue by JaceHensley** [MetaMask/metamask-extension#5683]
**Describe the bug**
A script tag keeps getting added to the head of the document.

Script tag: 
```
<script>window.dispatchEvent(new CustomEvent('ethereumisapproved', { detail: { isApproved: true, caching: true}}))</script>
```

This may just be isolated to https://github.com/MetaMask/metamask-extension/pull/4703

**To Reproduce**
1. Install the build from the mentioned PR
2. Notice that scripts are getting added to the start of the `<head />`

**Expected behavior**
If script tags need to be added they should probably be cleaned up afterwards

**Screenshots**
![image](https://user-images.githubusercontent.com/6597117/48031501-bad4c500-e111-11e8-88e3-1ec6863b27c4.png)

**Browser details (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - MetaMask Version: One of the latest builds from https://github.com/MetaMask/metamask-extension/pull/4703

**Comment by bitpshr** [comment]
Hi @JaceHensley, thanks for reporting this issue. A fix can be found at #5689 and associated builds can be found on that PR to use for manual verification. We hope to release this hotfix (as version 5.0.1) in the next few days.
