### ISSUE TITLE
calling `ethereum.enable()` on locked but already approved account asks user to approve again, but ignores if rejected

### ISSUE THREAD

**Issue by perissology** [MetaMask/metamask-extension#5688]
**Describe the bug**

2 things...

1. If I have already approved a domain, lock my account, & refresh the page, then metamask opens asking for my password. Once unlocked, I am asked to approve that domain again. However I have already approved it.

2. After unlocking, if I reject the 2nd approval, then call `ethereum.enable()` again the approval succeeds w/o asking the user to approve.

**To Reproduce**
1. call `ethereum.enable()` & approve dapp
2. lock account
3. refresh page
4. call `ethereuem.enable()`
5. enter password
6. reject approval
7. call `ethereum.enable()` again

**Expected behavior**

1. I would expect to not have to approve after unlocking my account if I have already approved a domain.

2. If that is the intended behavior, then I would expect that denying the 2nd approval would reset the cached approvals & not auto approve the domain in the future

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] chrome
 - MetaMask Version [e.g. 4.9.0] build found at https://github.com/MetaMask/metamask-extension/pull/5685
 - Old UI or New / Beta UI? new

**Additional context**

**Comment by bitpshr** [comment]
Hi @perissology, thanks very much for taking the time to report these issues. The first issue you mentioned is intended behavior; specifically, if MetaMask is locked and `ethereum.enable()` is called, the user will always be presented with both the login screen and a subsequent approval screen regardless of cached approval. We've been investigating ways to only show the login screen if a cached approval exists in this case, but for now, we always show both screens. The second issue you mentioned was a bug: rejecting an approval should always clear the cached approvals for that domain.

A fix can be found at #5689 and associated builds can be found on that PR to use for manual verification. We hope to release this hotfix (as version `5.0.1`) in the next few days. Thanks again for the clear bug report.
