### ISSUE TITLE
Website privacy popup appears every time when browser restarted

### ISSUE THREAD

**Issue by dlc9113** [MetaMask/metamask-extension#5697]
**Describe the bug**
Popup of connect request appears every time when browser restarted even if the website have been accepted before.

**To Reproduce**
1. Go to 'https://www.bithumb.io/'
2. Popup will appear
3. Click 'Connect' to accept it
3. Close browser, open browser
4. Go to 'https://www.bithumb.io/'

**Expected behavior**
No popup

**Browser details (please complete the following information):**
 - OS: macOS 10.14.1
 - Chrome 69.0.3497.100
 - MetaMask 5.0.1
 - Beta UI

**Comment by bitpshr** [comment]
Hi @dlc9113 and @jurosh, thanks for reaching out. This is intended behavior: whenever MetaMask is locked (which occurs when the browser is restarted), calling `ethereum.enable()` will always present the user with a password prompt and approval screen so the user can log in. Subsequent requests (or initial requests if MetaMask is already unlocked and has a cached approval) won't trigger a login screen or approval popup.

**Comment by jurosh** [comment]
It might be kind of annoying for user to always do confirmation. On devcon4 and also in some article about privacy mode, it was presented that there will be way to enable website forever by ticking checkbox and that would be ideal for our users.

**Comment by bitpshr** [comment]
Hi @jurosh. Approval caching is already "on" by default in the current version of MetaMask, meaning the behavior you're describing is already happening. Specifically, if a user approves a dapp (such as IDEX) then reloads the page, they will not be presented with additional approval dialogs. Instead, the dapp's `ethereum.enable()` call will resolve immediately with user accounts.

The user will only be presented with an approval dialog after approving a dapp in the past if MetaMask is locked (the rationale for which can be found [above](#issuecomment-437029430).) Let us know if you have any additional questions.
