### ISSUE TITLE
Privacy mode (Connect Request) display incorrect website name

### ISSUE THREAD

**Issue by jurosh** [MetaMask/metamask-extension#5698]
**Describe the bug**
Incorrect name of web/service displayed in privacy mode connect popup.

**To Reproduce**
1. Go to 'https://idex.market/unlock'
2. Select 'Software Wallet'
3. Click on 'Unlock Software Wallet'
4. Now restart browser, or remove IDEX from approved websites in Metamask
5. Go to (or refresh) 'https://idex.market'
6. Wait a while after metamask popup appears
7. See that metamask popup using title instead of meta title tag (and we are using title to display prices information to users) - see screenshot below.

**Expected behavior**
Because title is often used to display dynamic information to user it's not good to use it for service identification. Instead we can use title meta tag instead of title as site name, and use <title /> only as failback if `<meta name="title" content="TEXT">` is not in DOM.

Alternative approach might be to create way how to specify name of web - eg custom metatag or parameter to `enable()` method.

**Screenshots**
![image](https://user-images.githubusercontent.com/1630137/48189569-c9ed8a00-e340-11e8-84ba-d2899ea9888c.png)

**Browser details (please complete the following information):**
 - Browser: Chrome
 - MetaMask Version 5.0.1

**Comment by bitpshr** [comment]
Thanks for the report @jurosh. We're looking into this now.

**Comment by justinkchen** [comment]
Also the favicon is being set to a relative path I think. 
On our site: https://www.tokensets.com/set/ethx
It is trying to use `https://www.tokensets.com/set/favicon.ico` as the favicon instead of `https://www.tokensets.com/favicon.ico`
