### ISSUE TITLE
Connect Request shown when privacy is disabled

### ISSUE THREAD

**Issue by DaneWiid1** [MetaMask/metamask-extension#5699]
**Description**
V5.0.1 introduces a bug where connect request dialog is displayed even with privacy mode turned off. This issue was not present in v5.0.0

**To Reproduce**
1. Go to settings and disable privacy.
2. Refresh the page.
3. Notice Connect Request dialog

**Expected behavior**
The Connect Request dialog should not be displayed when privacy is turned off.

**Browser details**
 - OS: Windows 10 Pro
 - Browser Chrome version 70.0.3538.77 (Official Build) (64-bit)
 - MetaMask Version 5.0.1
 - Beta UI

**Comment by bitpshr** [comment]
Hi @DaneWiid1, thanks for taking the time to file this issue. We recently simplified our implementation of the "privacy mode" settings option. Specifically, turning this option "off" makes it so your accounts are always exposed to the dapps you visit, but this doesn't prevent the approval popup from showing if a dapp explicitly calls `ethereum.enable()`. The "privacy mode" settings option was only ever meant to allow users to continue to use legacy dapps that may be slow to update to the new API. However, if a dapp is already calling the new API, meaning their code is already updated to handle the approval popup, users will still see the approval popup regardless of whether "privacy mode" is "on" or "off". It should also be noted that this settings option is temporary: it will eventually be defaulted to "on" and ultimately removed altogether in future releases, making private browsing the only option for users.

Thanks again for reaching out. Let us know if you have any additional questions while testing.

**Comment by geehsien** [comment]
Thanks for the explanation @bitpshr. I think it's easy to misunderstand the behavior of "Privacy mode" given the name. We also expected connect requests to not show as long as this was off.

Perhaps something like "Legacy Support" with the on/off meanings switched (Privacy mode "off" == Legacy support "on") would've reduced confusion a bit. I guess either way it'll all be removed soon, so it's no big deal.

**Comment by arektdev** [comment]
You can avoid the popup if privacy mode is turned off by checking if window.ethereum.selectedAccount is undefined. If it is undefined, then attempt to enable.

Something like:
`if (window.ethereum) {
        try {
            if (typeof window.ethereum.selectedAddress === 'undefined') {
                await window.ethereum.enable();
                window.web3 = new Web3(window.ethereum);
            }
            else {
                window.web3 = new Web3(window.ethereum);
            }
        } catch (error) {
            alert('You denied access to your metamask. You will not be able to utilize the site.');
        }
    }`

**Comment by bitpshr** [comment]
> If enabling or disabling Privacy Mode has no effect, why include it in the interface at all?

This settings option does have an effect, just not a visual one: accounts are either automatically exposed to dapps if this option is disabled, or not automatically exposed if this option is enabled.

**Comment by wbt** [comment]
> This settings option does have an effect, just not a visual one: **accounts are** either **automatically exposed to dapps if this option is disabled**, or not automatically exposed if this option is enabled.

That's what I expected, too, based on all the documentation and logical software behavior.  That's apparently not how the software actually behaves.  If the option is disabled, accounts are apparently **not** automatically exposed to dapps, and if the user clicks "cancel" on the popup the dapp apparently does not ever get the account exposed unless the user later returns and clicks "connect."  

This disconnect between our and even your expert expectations of how the software *should* behave and how it actually *does* behave is the basis and trigger for my bug report (#5971) and apparently this one as well.

**Comment by dkent600** [comment]
So apps that *are* implementing the new API are stuck with a crummy UX, where the popup appears even though the user has explicitely requested not to see it, and the app has no way (that I can find) of preventing the popup from being shown, nor any way of anticipating that the popup is going to be shown.  It is an unavoidable, meaningless popup that is presented to the user for no explainable reason, and the app has no means of ameliorating the situation.

**Comment by bitpshr** [comment]
@dkent600:

> nor any way of anticipating that the popup is going to be shown

For now, you can use `ethereum._metamask.isApproved` to know if calling `ethereum.enable` will trigger a popup to show. `ethereum._metamask.isApproved` returns a `Promise` that resolves to `true` or `false` depending on if a user has previously approved a given dapp. Also, "privacy mode" was never part of the underlying EIP and was added as an afterthought to ease the transition from the old API to the new API. Unfortunately, we're now in a difficult spot where dapps are split between the two. Ideally, "privacy mode" would go away entirely since it was never meant to be a longterm feature, negating the issue you identified above re: divergent logic paths / UX flows.

**Comment by dkent600** [comment]
@bitpshr 
> For now, you can use ethereum._metamask.isApproved to know if calling ethereum.enable will trigger a popup to show. 

I don't think that helps because it doesn't tell you whether the popup should or should not be showing.

**Comment by dkent600** [comment]
@bitpshr 

> Also, "privacy mode" was never part of the underlying EIP...

This is really no consolation
