### ISSUE TITLE
Add Dai as a currency to the display options

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#5706]
I propose adding MakerDAO's stablecoin Dai both as a "Current Conversion" currency (weird name in the Setting UI by the way) (strange thing that I can view in Hong Kong Dollars, in Gnosis tokens, but not in Dai) and both as a Primary Currency.

If we wish to move away from a centralized measurement of value, adopting Dai as a unit of account is a reasonable first step.

**Comment by leafcutterant** [comment]
I can still see my balance in Bancor tokens, First Blood and Dash(!), but no love for Dai.

Me sad.

**Comment by bdresser** [comment]
PRs or bounties welcome! Should be pretty straightforward

**Comment by PeterTheOne** [comment]
Not sure but looks like a limitation of infura:

- https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/helpers/constants/infura-conversion.json
- https://infura.io/docs/ethereum/other/symbol
- https://api.infura.io/v1/ticker/symbols

**Comment by leafcutterant** [comment]
Thank you a lot!

**Comment by leafcutterant** [comment]
Hey, when can we expect to see this in a release? I still can't see this in 7.7.8 even though it was merged a few months ago.

**Comment by tmashuang** [comment]
will be in 8.0.0
