### ISSUE TITLE
Wrong response id on dry-run

### ISSUE THREAD

**Issue by RafaelVidaurre** [MetaMask/metamask-extension#5713]
**Describe the bug**
Transaction failing on dry run, getting "wrong response id" error. This happens randomly and I've found no reliable way to reproduce this.

**To Reproduce**
1. Dry-run a transaction on kovan
2. Get error about response id not matching expected. This only happens some times, *not* always.

**Expected behavior**
Dry run should work without throwing an exception

**Screenshots**

<img width="465" alt="screen shot 2018-11-09 at 3 15 18 pm" src="https://user-images.githubusercontent.com/1808674/48280423-4e6c0580-e432-11e8-8fbc-ee441c0d3a6d.png">

**Browser details (please complete the following information):**
 - OS: iOS 10.14
 - Browser: Chrome
 - MetaMask Version: 5.0.1
 - Old UI or New / Beta UI?: Beta UI

**Additional context**
This happens randomly, we have not identified a pattern yet. This does *not* happen on ganache

**Comment by kvhnuke** [comment]
This always happens during estimateGas if the transaction is going to fail here is the jsfiddle to replicate https://jsfiddle.net/s62rtk9y/

**Comment by tmashuang** [comment]
I do recognize that the error is not very helpful, but a little insight on the actual issue. You're not specifying what you're executing in the contract, or specifying a nonexistent method, so there's no contract code to execute.

@kvhnuke I have deployed a SimpleStorage contract on the Ropsten network, https://jsfiddle.net/pjb30kLx/. I commented out the failing scenarios that either data is omitted, or data is nonexistent.

**Comment by kvhnuke** [comment]
That is not the issue, issue is, metamask should return the correct response id that matches the request id. I intentionally made that call to fail in order to show the error. This will happen whenever, a call exceeds the gas limit. Pretty much whenever estimateGas call fails

**Comment by kvhnuke** [comment]
Here is the correct error it should return for the same call
https://jsfiddle.net/tgmbvnr7/

**Comment by tmashuang** [comment]
Current reproduction with the aforementioned jsfiddle leads me to believe this has been fixed. If I am mistaken, let me know and I can reopen.
