### ISSUE TITLE
Why does everyone and there Dog tell me to come here to buy XYO????

### ISSUE THREAD

**Issue by Marya27** [MetaMask/metamask-extension#5720]
FOR USER QUESTIONS, PLEASE DO NOT OPEN A GITHUB ISSUE - IT WILL NOT BE HANDLED HERE.

INSTEAD, PLEASE EMAIL SUPPORT@METAMASK.IO WITH A DESCRIPTION OF YOUR PROBLEM.

**Comment by Marya27** [comment]
I mean "THEIR DOG"< sorry.    I will go back to XYO and ask them again!
If you know email me, please. akinmary35@gmail.com 
I am trying to purchase tokens.

**Comment by bdresser** [comment]
@Marya27 MetaMask will set you up with a wallet you can use to hold & send ETH and tokens.

You can find more information at metamask.io or by doing some basic research.
