### ISSUE TITLE
MetaMask is loading missing network indefinitely

### ISSUE THREAD

**Issue by vporton** [MetaMask/metamask-extension#5721]
**Describe the bug**
I connected MetaMask to a test network running on localhost.

Then I exited the browser (Chrome) and also turned off the Ethereum network software.

Then I started MetaMask and it tries to connect to now non-existing network infinitely, without any way to interrupt it.

**To Reproduce**
1. Start a network
2. Connect to this network
3. Exit the browser and put down the network.
4. Restart the browser and try to launch MetaMask

**Expected behavior**
There should be a way to connect to another network.

**Screenshots**
![screenshot from 2018-11-11 02-03-02](https://user-images.githubusercontent.com/2900574/48307480-3ee5dd00-e556-11e8-82d2-28794e5a80c1.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu Linux
 - Chromium 70.0.3538.77
 - MetaMask Version 5.0.2
 - New / Beta UI

**Comment by bdresser** [comment]
This will be handled as part of #5210
