### ISSUE TITLE
Add pending transactions to icon overlay

### ISSUE THREAD

**Issue by destenson** [MetaMask/metamask-extension#5726]
It would be nice if pending transactions were overlayed onto the icon like pending signatures are.

It would make sense to replace the existing overlay in the bottom right corner for pending signatures with one for pending transactions, and put the overlay for pending signatures in the top left corner of the icon. 

I suspect it would be an easy change. If I have time I'll look into doing it, but I don't expect to soon.

**Comment by Gudahtt** [comment]
Thanks for the suggestion! Pending transactions are included in the count displayed on the browser toolbar icon, along with pending signatures. So I think this has already been done? I'll close this for now, but let me know if I've misunderstood something.
