### ISSUE TITLE
Resetting Instructions

### ISSUE THREAD

**Issue by micahalcorn** [MetaMask/metamask-extension#5727]
[This link](https://github.com/MetaMask/metamask-extension/blob/f692123f513b6d71797a609311df507cd1ee3d48/old-ui/app/config.js#L291) is dead. 💀 How are we supposed to reset with MetaMask 5.x.x?

![screen shot 2018-11-11 at 4 58 08 pm](https://user-images.githubusercontent.com/273937/48320908-397aa800-e5d3-11e8-8d49-80cf7a0fc58d.jpg)

**Comment by bdresser** [comment]
Support articles have moved to metamask.zendesk.com.

Instructions on how to reset an account for the [old UI](https://metamask.zendesk.com/hc/en-us/articles/360015489231-Resetting-an-Account-Old-UI-) and [new UI](https://metamask.zendesk.com/hc/en-us/articles/360015488891-Resetting-an-Account-New-UI-) are both there. 

You should be able to scroll down on that screen you're looking at!

**Comment by micahalcorn** [comment]
Thanks @bdresser, but no, I cannot scroll any further. And the instructions that you link to call for using the reset button, which has appears to have been removed in 5.x.x. 😕

_Firefox 63.0.1 with MetaMask 5.0.2_

![metamask](https://user-images.githubusercontent.com/273937/48363682-5e1a6280-e65b-11e8-8ede-5e61bfcce32e.gif)

**Comment by micahalcorn** [comment]
Ah, I see ☝️ It looks to be a height/overflow problem causing the button to be hidden.

**Comment by bdresser** [comment]
gotcha - I recommend you switch over to the "new" UI, we don't update or patch the old UI anymore plan on entirely deprecating it shortly. Click on the top-right menu, then "Try Beta!"

If you have trouble with the new UI, please feel free to open a new issue!
