### ISSUE TITLE
Sending USD or ETH via metamask

### ISSUE THREAD

**Issue by bestrateorg** [MetaMask/metamask-extension#5729]
**What problem are you trying to solve?**
Hello! A lot of services ask people to send ETH to some address. For example OTC exchanges. To exchange ETH to some crypto you need to send exact amount of ETH to ETH address. For example, I want to change 0.2 ETH to 0.00653832BTC. OTC exchange asks me to send 0.2 ETH to their hot wallet. 

In the new design, I can not send the amount of ETH.

It means - that I can't use metamask for sending eth - I use myetherwallet with metamask login to send the correct amount of ETH.

**Describe the solution you'd like**
I offer to add switch ETH - USD. If a user needs to send the exact amount of ETH - he can choose ETH amount.

<img width="437" alt="screenshot 2018-11-12 at 13 23 43" src="https://user-images.githubusercontent.com/37540605/48341804-19082780-e67f-11e8-9d57-f8d807cb7429.png">

In your case If user needs to send ETH - He will use another wallet. It's bad!

**Comment by bdresser** [comment]
hey @bestrateorg - in your settings menu, you can customize what MetaMask displays as your primary currency. Click the menu in the top-right, then click "Settings," then select ETH as your primary currency.

cc @alextsg - seems like some users have their extension set to fiat by default. Any additional info we can ask for to help diagnose?

**Comment by bestrateorg** [comment]
Hey! @bdresser! Thanks for reply!

Settings? I tried everything:

<img width="373" alt="screenshot 2018-11-12 at 19 02 32" src="https://user-images.githubusercontent.com/37540605/48359280-a7939d80-e6ad-11e8-9572-6525f6f8b4ea.png">

**Comment by bdresser** [comment]
click the round icon in the top-right!

**Comment by bestrateorg** [comment]
Oh god, bingo! Thanks, sorry for inconvenience!

**Comment by alexburciu** [comment]
Could you please maybe fix the UX somehow? I also ended up here because it wasn't obvious how to do it and it could be confusing for new users.

**Comment by bdresser** [comment]
@alexburciu agree, it'd be nice to be able to swap right from the send screen. tracking that issue in our design repo https://github.com/MetaMask/Design/issues/51
