### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by digitaldonkey** [MetaMask/metamask-extension#5731]
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#requirements-nut_and_bolt

This doc page is outdated.

**Comment by bdresser** [comment]
@digitaldonkey unfortunately a lot of our documentation is out of date. we will refresh this page in particular with the recent updates from EIP 1102 but in general plan to overhaul and consolidate our documentation starting shortly.

**Comment by bitpshr** [comment]
We have a new documentation effort underway [here](https://metamask.github.io/metamask-docs/). Please let us know if there's information that's missing so we can be sure to cover it.
