### ISSUE TITLE
ENS resolution suddenly requires http/https prefix

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5734]
Reported in [this reddit post](https://www.reddit.com/r/Metamask/comments/9vcke4/ens_redirect_to_ipfs_not_working/).

Our [support for ENS resolution](https://medium.com/metamask/metamask-monthly-august-8b409c3fa18) stopped working without an http/https prefix.

Did we give up a browser permission? Did chrome change its behavior on us?

cc @PhyrexTsai. Two new ENS issues in one day, who would've thought!

**Comment by PhyrexTsai** [comment]
@danfinlay Thanks for the information.
It seems redirect to IPFS website need http/https prefix is effect by `content_security_policy`.
We'll keep dive deeper and fix it.
