### ISSUE TITLE
Metamask stuck on loading(cant export private key, seedwords or send eth)

### ISSUE THREAD

**Issue by SilverLaius** [MetaMask/metamask-extension#5735]
Using windows 10, 
chrome 70.0.3538, 
metamask 5.0.2
old UI and new both have the same problem

I just sent eth to my metamask wallet and want to send them to another wallet. None of the transactions go through and I cant export private key nor export seed words. Whenever I click submit to send funds, it just starts loading and never gets anywhere. I have 25 pending transactions tho. none of them are available in ethscan. the infinite loading occurs when I enter my password and try to export private key or seeds aswell. Basically my eth is just stuck there with no hope of leaving.

tried to relog and log back in but same stuff. Sometimes also shows 0 balance when I open the extension.

**Comment by oschvr** [comment]
Try going to Manage Extensions in Chrome, and then Disable/Enable Metamask. Worked for me.

**Comment by yehia67** [comment]
Hello this issue is still there
