### ISSUE TITLE
Warn users if transaction(s) are pending for a long time

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#5738]
**What problem are you trying to solve?**
A short description of what you're trying to do. E.g., "My users need to wrap ETH, but they're intimidated by the confirm screen..." or "I'm trying to debug my application, and XYZ..."
The problem where the user has a tx with a low nonce and gas price thats holding up a ton of transactions.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Try to also include any alternative solutions you've considered.
If I have > 3 pending txes for more than 12 hours, warn me at the top of Metamask when I (a) open Metamask or (b) go to send another transaction, with a nice big red alert that says

"Did you know that you've got a bunch of pending tx's? Click here to speed up the lowest transaction or click here to read more about how Metamask and Ethereum work"

**Additional context**

**Comment by owocki** [comment]
logging this because i am an ethereum expert by many standards, and i even didnt realize i had a bunch of pending tx's until someone told me they didnt get my ETH

**Comment by bschorchit** [comment]
Cool to see @owocki around here! Closing this issue as we now have this:

<img width="222" alt="Screen Shot 2022-06-13 at 18 19 03" src="https://user-images.githubusercontent.com/34968356/173447249-885e645f-79ca-4913-ac30-6e3cce255208.png">
