### ISSUE TITLE
Update ENS resolving implementation to match what is defined in EIP-1577

### ISSUE THREAD

**Issue by decanus** [MetaMask/metamask-extension#5742]
**What problem are you trying to solve?**

Name resolution is done using the `content` and `multihash` fields right now, to try and find a better system @arachnid and I created [EIP-1577](https://github.com/ethereum/EIPs/pull/1577) that allows for a better representation of network and content addresses.

**Describe the solution you'd like**

Implement resolution using the new `multiaddr` field when available.

**Comment by decanus** [comment]
There will be changes made to the EIP so implementation should be paused.

**Comment by decanus** [comment]
The EIP has been updated and should be good to go: https://eips.ethereum.org/EIPS/eip-1577

**Comment by danfinlay** [comment]
Pinging @PhyrexTsai in case he has bandwidth for this.

**Comment by decanus** [comment]
@danfinlay @bitpshr probably best to put this on pause, as we expect to update the spec again soon.

**Comment by decanus** [comment]
@danfinlay The EIP has been updated, work should be able to start on it now. https://eips.ethereum.org/EIPS/eip-1577

**Comment by Platinumwrist** [comment]
Cant connect blank screen at least 8hrs of nothing but blank

**Comment by bdresser** [comment]
@Platinumwrist could you share your UI and background logs on issue https://github.com/MetaMask/metamask-extension/issues/4894 to help us debug. This issue is for something entirely different. 

Instructions how to find those logs are [here](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue).

**Comment by pldespaigne** [comment]
Hi ! I have wirtten a [small JS lib](https://github.com/pldespaigne/content-hash) to implement EIP1577 ! @decanus and the ENS team have [used it](https://github.com/ensdomains/ens-app/blob/dev/package.json#L15) for the ENS Manager dApp ([issue](https://github.com/ensdomains/ens-contenthash/issues/1)), so I think it could also help in Metamask :)
Also it would be an honnor for me to contribute !

**Comment by danfinlay** [comment]
@pldespaigne that's fantastic! We would be incredibly grateful for the contribution, we want our ENS support to reflect the latest standard. Please let us know if you have any questions!

**Comment by pldespaigne** [comment]
OK I will be working on it :grinning: ! Can you help me to find my way through the metamask codebase ?

**Comment by danfinlay** [comment]
I believe our current implementation is in this folder:
https://github.com/MetaMask/metamask-extension/tree/develop/app/scripts/lib/ens-ipfs

I was just made aware of this library, which may be useful for allowing us to resolve a variety of decentralized name services, although I need to look into it more (can it use our user's configured blockchain provider?)
https://github.com/unstoppabledomains/namicorn

**Comment by Arachnid** [comment]
namicorn looks okay, but I'm not sure of its value: The format of its returned data seems to depend on the provider, and it doesn't attempt to encode or decode the content hash data at all. I'm not sure it would save you any time over just using our libraries (or calling the contracts) directly.

**Comment by pldespaigne** [comment]
Work in progress ;)

**Comment by pldespaigne** [comment]
ping @danfinlay @kumavis @decanus @Arachnid work done ✔️
review requested [here](https://github.com/MetaMask/metamask-extension/pull/6402)

**Comment by pldespaigne** [comment]
Guys ? Is there anybody to review my [PR](https://github.com/MetaMask/metamask-extension/pull/6402) ?
@danfinlay @kumavis @bdresser

**Comment by bdresser** [comment]
Closed in https://github.com/MetaMask/metamask-extension/pull/6402
