### ISSUE TITLE
Broken link on Add Tokens page

### ISSUE THREAD

**Issue by osyed** [MetaMask/metamask-extension#5743]
On the Add Tokens screen it says:
"Add the tokens you've acquired using MetaMask
Learn more"

The "Learn More" is a link to:
https://consensys.zendesk.com/hc/en-us/articles/360004135092
which is a non-existent page.

This was In the 4.11.1 version of the MetaMask extension in the Brave browser. I did not check it on other browsers.

**Comment by bdresser** [comment]
@osyed thanks for reporting. our support articles have moved to `metamask.zendesk.com`, and on 5.0.2 this link points to the proper article [here](https://metamask.zendesk.com/hc/en-us/articles/360015489031).

Brave is several versions behind, their team manually updates from the Chrome store so we're stuck waiting
