### ISSUE TITLE
Allow Viewing of Pending Transactions

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#5748]
**What problem are you trying to solve?**
#5739 
#4760
#5687
I believe somehow Pending Transactions(Transactions that have not been submitted but `approved?`) are showing up in the transaction history. I am still unsure how users are getting pasted the transaction confirmation without either confirming/rejecting the transactions. Possible issues could be that we are populating the Mainnet tx history with Custom RPC/Ganache txs via getting `metamaskNetworkId` is incorrect. Another theory is dropped txs are coming back. Either way the local nonce is incorrectly calculate with the list of pending txs. I believe the only way to clear them now is to Reset Account.

**Describe the solution you'd like**
Be able to view all pending txs and reject them.

**Additional context**
These pending tx aren't transitioning to failed/dropped.

**Comment by brad-decker** [comment]
@tmashuang this issue seems old due to the fact that we now display pending txs and allow cancel/retry/etc -- can you confirm and close if this is out of date?
