### ISSUE TITLE
list of accounts does not show a scrollbar if there are more than 3 accounts

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#5751]
The list of accounts does not show a scrollbar if there are more than 3 accounts , easily leading to the interpretation that there are not more than 3 accounts

**Comment by bdresser** [comment]
thanks for the suggestion @SvenMeyer, this has come up a couple times

cc @omnat @cjeria

**Comment by 6proof** [comment]
As this was not a problem in previous versions of MetaMask, could someone please share the fix to display more than three accounts?

**Comment by bdresser** [comment]
@6proof the section of the menu that displays your accounts is able to scroll (inside of the menu itself)

**Comment by cjeria** [comment]
Two updates I think would help with this issues:

- hide 25% of the 4th account below the fold of the container
- add a FAB (floating action button) with arrow that smooth scrolls the list to show the other accounts.

cc @alextsg 
 
Mockup
![account dropdown top bar](https://user-images.githubusercontent.com/597770/48793195-331bb880-ecc4-11e8-8671-e8157445f94d.png)

**Comment by bdresser** [comment]
the changes described above are now live in production
