### ISSUE TITLE
No prompt or info given when user action required, for trezor or ledger wallet txs - breaks flow

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#5757]
**Describe the bug**
User is prompted with a spinwheel and no other information after clicking confirm transaction.  If the user does not have their hw wallet connected, they can still do this entire process.  The window will just continue to display the spinwheel.  User can close this window out and then the tx displays in a "queue".  If the user tries to click cancel, it does nothing.

tl;dr - you can break the flow of using a hw wallet and then these tx stay but need a way to be cleared or accurately shown as "failed".

**To Reproduce**
1. click on linked hw wallet account
2. send eth or tokens anywhere
3. click confirm (without hw wallet connected)
4. See spinwheel
5. close window

**Expected behavior**
I would expect instructions be displayed when I got the spinwheel. 

**Screenshots**
![hw_wallet](https://user-images.githubusercontent.com/16330048/48488593-bfbb0800-e7e6-11e8-8426-5ccc8f9bb197.png)

**Comment by dpazdan** [comment]
could be related https://github.com/MetaMask/metamask-extension/issues/5364

this user experienced a similar "queue" of stuck txs after his issue:
https://github.com/MetaMask/metamask-extension/issues/5687

**Comment by nottoseethesun** [comment]
Also, the same scenario happens if the user doesn't have "Browser Support" enabled on their wallet; iirc no indication is given to the user that this will be needed.  Also, perhaps "Contact Data" needs to be enabled as well.  At least, provide a prominent, tiny reminder - should only take four or five words total on the u.i.  Otherwise, even experienced users who haven't used MEW in a while will forget and be flummoxed for a while.

**Comment by mmquimby** [comment]
I am hitting the same problem. Have just started using Ledger with MM, and it is super confusing that there is no prompt to connect ledger and approve transaction on it, just a spinner. This is a big UI gap for MM's standards, bordering on unusable. 

What is the status of this bug? I see no owner, which is unfortunate.

**Comment by mmquimby** [comment]
@bdresser why is this labeled as an enhancement? Putting up a spinner animation and not prompting the user for an action they need to take with a hardware wallet is a bug, the same as popping up a dialog box with buttons in a foreign language would be a bug and not a feature request.

Would appreciate a workaround on this.

**Comment by dpazdan** [comment]
maybe add these "tips" to the same screen 
Make sure you have:
-your ledger plugged in, unlocked, with the Ethereum app open
-the firmware updated on your ledger or trezor device
-the most up-to-date browser
-"browser support" on the device enabled
-"contract data" on the device enabled (if needed for what you are doing)

**Comment by Gaianeo** [comment]
I got the same 'spinning wheel' problem. Currently having 4 Transactions that say APPROVED in metamask, but nothing appears on the blockchain. How did you resolve this? Have followed the instructions of dpazdan but it doesnt help. Anyone that can help?

**Comment by Gaianeo** [comment]
I restarted my Mac.  Did as instructed above and managed in the end to transfer from one to another account. What didnt work was to approve a transaction through an app (pool together) that connects to MM directly

**Comment by avalyn2** [comment]
seems the same issue I reported here https://github.com/MetaMask/metamask-extension/issues/7809

will try this https://github.com/MetaMask/metamask-extension/issues/5757#issuecomment-532941266 now and report back if it works

**Comment by avalyn2** [comment]
I can confirm following https://github.com/MetaMask/metamask-extension/issues/5757#issuecomment-532941266 works.

**Comment by pcko1** [comment]
problem is still present and the proposed solutions didn't fix it for me. I can see my ledger wallet balance on metamask but nothing happens when I try to transact (spinning wheel only regardless of ledger X being connected or not)

**Comment by AlexJupiter** [comment]
I don't believe this is a problem anymore. MetaMask prompts to connect Ledger if it isn't connected and Trezor forces you to connect the device when attempting to sign a transaction. No constant spinning wheel noticed on Chrome. 
![image](https://user-images.githubusercontent.com/7900773/154551963-83ce68c4-8c7b-44a0-9761-881a23d95abb.png)
![image](https://user-images.githubusercontent.com/7900773/154552514-15bb9b97-2732-49e7-81ec-9ba890040d7f.png)
