### ISSUE TITLE
Fix connection to Parity RPC provider

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#576]
A friend from Etherchain is trying to get [their RPC provider](https://etherchain.org/api/web3) working as a hosted MetaMask node, but is having issues.

From our slack (@peter_etherchain on slack):

> I am currently testing metamask with our new web3 proxy at etherchain.org/api/web3 . Currently I have the problem that once I set the proxy as web3 provide in metamask I only receive repeated eth_getblockbynumber calls once every 5 seconds. But when I try to execute a method of the injected web3 object the async handler is never called. Also I do not get any errors in the console.
> 
> the proxy uses parity as backend node, could this be the reason?

**Comment by ppratscher** [comment]
If you need more info or support during tests, please let me know.

**Comment by tmashuang** [comment]
Closing old issue.
