### ISSUE TITLE
Link transactions with the dApp that requested it

### ISSUE THREAD

**Issue by joaoaguiam** [MetaMask/metamask-extension#5761]
**What problem are you trying to solve?**
When one verifies the transactions that have been executed on a given account, there is no information about the dApp that launched that transaction. This is important when checking the list of past transactions, the same way we verify our bank accounts. We can know the address to where the transaction has been sent but this may not allow to retrieve the dApp that was on the source of the transaction.

**Describe the solution you'd like**
I would like to keep an association between a transaction and the dApp that requested it. When opening the details of the transaction, some more information should be shown from the page requesting the transaction:
- URL
- Title
- Favicon

**Comment by bdresser** [comment]
This is a great idea @joaoaguiam. Already filed as https://github.com/MetaMask/metamask-extension/issues/5611 so closing this to consolidate.
