### ISSUE TITLE
Pending transaction from a side chain was executed on the mainnet 

### ISSUE THREAD

**Issue by joaoaguiam** [MetaMask/metamask-extension#5762]
**Describe the bug**
I was using the xDAI POA side chain and my transaction was pending for several days. After changing to the mainnet and launch a new transaction, my previous side chain transaction was executed.

**To Reproduce**
Not sure I am able to reproduce it again. 
I was using xdai.io burner wallet, which uses the xDAI POA sidechain. Somehow the transaction was not going through and stays in the pending state on my wallet. When moving to the mainnet, the pending transaction was still there. 
I then executed a new transaction on the mainnet, and suddenly my pending transactions from the side chain were executed. Therefore some ethers went to a unknown address and got lost forever!

**Expected behavior**
Transactions from private RPCs should not be mixed in the list of transactions on the mainnet

**Screenshots**
![screen shot 2018-11-14 at 23 28 17](https://user-images.githubusercontent.com/5901730/48534561-b755e200-e865-11e8-841c-e2b9ed4e1c16.png)

Tx link: https://etherscan.io/tx/0x20d1787d23ff345b64314559294f03f06e2f8d23e79037709d3ab7778959939c

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - MetaMask Version: 5.0.2

**Comment by riusricardo** [comment]
I experienced the exact same issue using xDAI POA side chain. xDai pending transactions resolved on the Ethereum mainnet.

OS: Linux Ubuntu 16.04
Browser: Chrome
Metamask Version: 5.0.2

**Comment by danfinlay** [comment]
Hi all, sorry for the slow reply. If you're able to reproduce this, please contact us at support@metamask.io so we can get some logs to help us diagnose how this could happen.

**Comment by joaoaguiam** [comment]
Hi @danfinlay , this issue just happened to me again, I had a transaction that was rejected or pending (not sure which state) on the xDai POA side chain, and when I moved to the Mainnet and executed another transaction, the one from the POA side chain was executed on the mainnet. 
The failed transaction didn't have much value luckily, otherwise, it would have been lost.

Here is the transaction on the mainnet: https://etherscan.io/tx/0xec77021ae69a93cc4f6a72bfaa6f90d98f35b0c813aa5733f160379b3d9c3a3d 

Metamask version: 5.3.1

Feel free to contact me on telegram at @joaoaguiam to help you debugging.

**Comment by frankiebee** [comment]
it's possible if the xDAI POA has the same netID and chainID as ethereum main net it is possible for the pending tx to be submitted to the ethereum main net. do you have a url enpoint i could use for xDAI POA chain?

**Comment by frankiebee** [comment]
^ @joaoaguiam

**Comment by frankiebee** [comment]
oh scratch that found one

**Comment by riusricardo** [comment]
Network -> Id

> Ethereum mainnet -> 1

> https://dai.poa.network -> 100
> https://core.poa.network -> 99
> https://sokol.poa.network -> 77

I don't think it is the case.

**Comment by frankiebee** [comment]
yeah just confirmed that

**Comment by frankiebee** [comment]
might be related to https://github.com/MetaMask/metamask-extension/issues/5956

**Comment by joaoaguiam** [comment]
@riusricardo Yes I was playing with the Burner Wallet and Burn token.

I didn't set the chain id when I added the xDai RPC. Do you think if this is set to 100 there should be no issue?

Next time it fails I will move to the test net then. Thanks!

**Comment by rstormsf** [comment]
@joaoaguiam just make sure you don't have more than 1 custom rpc in your list. Remove all RPCs and only use one for now

**Comment by danfinlay** [comment]
> Remove all RPCs and only use one Custom RPC in metamask for now.

If that's a user-side workaround, we should just make `add custom rpc` overwrite any existing rpc, to do the same programmatically. @frankiebee

**Comment by joaoaguiam** [comment]
I have two custom rpc indeed, but just allow one rpc is very limiting in my opinion.

<img width="297" alt="screen shot 2019-01-29 at 18 30 51" src="https://user-images.githubusercontent.com/5901730/51952102-709f6f00-23f4-11e9-9971-1c9714f05b52.png">

**Comment by rstormsf** [comment]
@joaoaguiam 
Hopefully this PR fixes this issue
https://github.com/MetaMask/metamask-extension/pull/6044
Please let us know

**Comment by frankiebee** [comment]
> Remove all RPCs and only use one Custom RPC in metamask for now.

@joaoaguiam @danfinlay that is not an effective workaround; best  to just put the chain Id in settings when you use the rpc till the new update has reached all users 

the update will not be able to fix miss-assigned chainID's so you will still need to reenter them on the new update if they have a cached value that is incorrect.

**Comment by danfinlay** [comment]
This should be fixed in v5.3.4, let us know if not!
