### ISSUE TITLE
where is the function that  signing tx ?

### ISSUE THREAD

**Issue by liwei00wade** [MetaMask/metamask-extension#5763]
I found out the following codes, 
but I can not tracked how to call  metamaskController.txController.signTransaction, 
I want to know  some function about      create tx --> sign tx      
please help me, thanks a lot.

metamask-extension/ui/app/actions.js

function signTx (txData) {
  return (dispatch) => {
    global.ethQuery.sendTransaction(txData, (err, data) => {
      if (err) {
        return dispatch(actions.displayWarning(err.message))
      }
    })
    dispatch(actions.showConfTxPage({}))
  }
}

**Comment by bdresser** [comment]
@liwei00wade don't mean to be rude, but this question is much better suited for Stack Exchange! It will live on a public site for longer and help devs in the future find the answer. We're trying to keep our issues focused on bugs & feature requests for the extension. 

Feel free to post there & share the link!

**Comment by zhugeliange** [comment]
+1
