### ISSUE TITLE
Support Hierarchical Deterministic (HD) Wallets in Ledger/Trezor

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#5768]
**What problem are you trying to solve?**
When I connect a new HD address on my hardware wallet it replaces my prior HD address

**Describe the solution you'd like**
I can add multiple HD addresses per HW wallet

**Additional context**
I am using a Ledger.

**Comment by kosecki123** [comment]
Yes, this is really annoying, hardware wallet account are still view-only accounts, I would love to be able to import more of them.

**Comment by Gudahtt** [comment]
This seems like a duplicate of #6649. I'll close for now, but please let me know if I've misunderstood the request.
