### ISSUE TITLE
Add night mode

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#577]
Some people even prefer night mode by default! That's another discussion!

Should be in settings, should persist between page openings, all views should adjust accordingly.

Probably means any reference to a CSS color should actually reference a css color file that can conditionally swap, kindof like `i18n` for appearance.

Requires design for a night mode, so all other things being the same, but with a darker color theme.

**Comment by bdresser** [comment]
@cjeria would you add your night mode designs to this ancient story? wonder if we could bounty or find a contributor to take this on, folks might dig it.

**Comment by cjeria** [comment]
Yep! The UI here is a outdated and the colors might need to go through a more thorough accessibility test for colorblind @bdresser 
![dark mode](https://user-images.githubusercontent.com/597770/41129679-0e7d5d3c-6a68-11e8-8f20-f523e02e1f11.png)

**Comment by bdresser** [comment]
@ChrisCates may be interested in helping here!

**Comment by ChrisCates** [comment]
@bdresser, @cjeria, 

I'm just going to throw in some CSS (plus a button switch) in a PR, and we can move from there.

**Comment by cjeria** [comment]
Sounds good @ChrisCates. I imagine we'll need to do an accessibility audit to make sure the colors are good for the colorblind, but don't let that slow you down!

**Comment by ChrisCates** [comment]
Here's some stuff I did.
Feel free to give feedback.

https://github.com/MetaMask/metamask-extension/pull/5800

**Comment by ChrisCates** [comment]
Any have recommendations for svg editors?
I also need to update the `/images/logo/metamask-logo-horizontal-beta.svg` image.

**Comment by MCYayes** [comment]
I see some good work on this from months ago... is this aspect of the project still going? 
Being implemented? The white is physically painful for me, but I want to use the extension, so... ?

**Comment by fonziemedia** [comment]
Hey guys, any news on night mode feature?
I'm really reluctant on installing a third party plugin to achieve this and other users should be too but it's either that or migraines..

**Comment by whymarrh** [comment]
@fonziemedia no updates, it's still a nice to have

**Comment by cyberfunk** [comment]
Any updates on dark mode? Or maybe just some CSS I can add to the user styles plugin for Chrome/Brave?

**Comment by stychu** [comment]
++
updates?

**Comment by proudmuslim-dev** [comment]
It's genuinely irritating that 5 years later we still to do not have a simple dark mode toggle.

**Comment by linaspasv** [comment]
When night mode?

**Comment by ChrisCates** [comment]
Hey guys! I've agreed to the CLA just to ensure nothing is blocking this PR.
Mind you the branch is very out of date and will need to be rebased.

If someone from the Community could pick this up and rebase it. Would be awesome.

Thanks all, looking forward to dark mode... One day :)

**Comment by bschorchit** [comment]
https://github.com/MetaMask/metamask-extension/pull/13097 fixes this.

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/13719
