### ISSUE TITLE
 Search my vault data.

### ISSUE THREAD

**Issue by SeaCancel** [MetaMask/metamask-extension#5771]
I do not have a secret phrase and key. There is a password for the account. Where can I find metamask-config? In chrome, DevTools issues a loglevel WARN, and there’s no such thing.

**Comment by SeaCancel** [comment]
Google Chrome version 70.0.3538.102
Windows 7

**Comment by SeaCancel** [comment]
![image](https://user-images.githubusercontent.com/45097775/48621674-0c106e80-e9c6-11e8-9c43-c1063f3f6448.png)

**Comment by bdresser** [comment]
@SeaCancel head to your Settings menu (click the circle in the top-right, then down to Settings) and scrolll down til you see `REVEAL SEED WORDS`. Click, you'll be asked for your password, then you'll see your seed phrase.

For more questions like this please reach out to support@metamask.io

**Comment by SeaCancel** [comment]
The problem is that the metamask has been reset and I have lost access to the wallet.

**Comment by bdresser** [comment]
always back up your seed phrase! without it, you may not be able to recover your wallet. 

email support@metamask.io and they may be able to help you recover your vault from the console.

**Comment by martineezz** [comment]
@SeaCancel If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
