### ISSUE TITLE
MetaMask error "Attempting to use a disconnected port object" causes dApp hang

### ISSUE THREAD

**Issue by ajm13** [MetaMask/metamask-extension#5773]
I get the following error in the console when launching Chrome where a dApp is one of the tabs it reopens from the previous session:

```
Uncaught Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (VM29 extensions::messaging:102)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at onloadwff.js:58
    at r (onloadwff.js:58)
    at s (onloadwff.js:58)
```

Steps to reproduce:
- Change Chrome "On startup" settings to "Continue where you left off"
- Open a dApp, like https://www.cryptokitties.co/sign-in
- Quit Chrome
- Open Chrome
- dApp is now hanging, console shows the above error

Refreshing the page fixes it, so I'm assuming this issue is a race-condition where MetaMask isn't fully setup when the dApp loads on Chrome's initial startup.

Note: this is on MetaMask v5.0.2

**Comment by Gudahtt** [comment]
Thanks for the report! Sorry it took so long to reply. This issue is rather old, and we haven't had reports of this in the past few years to my knowledge, so I'm going to assume this is no longer happening and close this issue. Please let me know if this problem persists though!

**Comment by nuurcodes** [comment]
I am facing this issue with chrome 92.0.4515.107

**Comment by joehawary** [comment]
me too

**Comment by Gudahtt** [comment]
Thanks for the report @joehawary and @nuurcodes! Could one of you open a new ticket, and include details such as the exact error (and stack trace if present), the steps to reproduce, the browser and browser version used, and the MetaMask version used?

**Comment by nuurcodes** [comment]
@Gudahtt 

https://github.com/MetaMask/metamask-extension/issues/11730
