### ISSUE TITLE
Stuck in loading state; had to reinstall

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#5774]
I have my ledger wallet unplugged but I was using it when this started happening. I have tried disabling and re-enabling but this does not fix the issue.

The current behavior is that I re-enable metamask, enter my password, and encounter a stuck loading screen.

![screen shot 2018-11-16 at 4 15 06 pm](https://user-images.githubusercontent.com/799573/48653564-0c573c80-e9bb-11e8-8716-ad9244255be3.png)

Here are the background logs:

![screen shot 2018-11-16 at 4 17 31 pm](https://user-images.githubusercontent.com/799573/48653583-2d1f9200-e9bb-11e8-9bd1-e9aae5588fa3.png)

It's strange that it attempts to connect to ledger even though it is disconnected, but there is no other evidence of anything going wrong.

**Comment by wjmelements** [comment]
cc @brunobar79

**Comment by sandyleo26** [comment]
Encounter the same issue here when I want to connect MM to Ganache. For me the solution is to uninstall/install MM, recover from seed, add custom RPC and reimport the same account on Ganache and it works. I tried Disable/Enable MM extension, restart browser etc but only this works.

**Comment by tmashuang** [comment]
Closing this old thread. For any future issues that seem related please open a new issue with detailed reproduction steps.

**Comment by kenerik** [comment]
> Try disabling/enabling MM, switch network before logging in, switch back to original network, and reject any unapproved txs.

Thanks.
Happend to me for the first time to day..
Disable - Enable MetaMask. Then switch network .. Worked like a charm :-)
Hope you guys get's this sorted out..
