### ISSUE TITLE
Custom CSS/Skin for Metamask.

### ISSUE THREAD

**Issue by ChrisCates** [MetaMask/metamask-extension#5776]
**What problem are you trying to solve?**

I prefer a dark theme for pretty much everything. Would love to be able to toggle it "dark"/"light" CSS styles in the settings portion of the app.

**Describe the solution you'd like**

Just a simple toggle button in settings.

**Additional context**

Just curious if you guys would accept a PR and deploy it in the next release... I'm sure many other people would prefer a dark theme too.

**Comment by bdresser** [comment]
duplicates https://github.com/MetaMask/metamask-extension/issues/577

we'd love help on this one! have some rough designs, just haven't gotten around to it :)
