### ISSUE TITLE
RpcError with code: -32603 and message: "Error: Error: No keyring found for the requested account."

### ISSUE THREAD

**Issue by jorgejesus** [MetaMask/metamask-extension#5778]
**Describe the bug**
RpcError with code: -32603 and message: "Error: Error: No keyring found for the requested account."

**To Reproduce**

This occurs when trying to pairing a secondary non metamask address in the FOAM infrastructure

https://mapguide.foam.space/initial-proof-of-use-period/pairing-a-secondary-non-metamask-address

**Expected behavior**
For transaction to be confimed and mined by system

**Screenshots**

![image](https://user-images.githubusercontent.com/1275400/48669503-310bfb00-eb06-11e8-9508-af032b410ae4.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.01 (Bionic Beaver)
 - Browser: Chroem Version 68.0.3440.106 (Official Build) (64-bit)
 - MetaMask Version 5.0.2

**Additional context**

Read Ticket #3738 not certain if the keyring in error message is related to wallet or keyring used in ubuntu/chrome ( libpam-gnome-keyring)

**Comment by murisimov** [comment]
For those who just need things to work:
Disabling and then enabling of MetaMask extension can help

**Comment by tmashuang** [comment]
Closing this for now. If the issue has persisted in the latest version, please open a new issue with a more detailed issue description.
