### ISSUE TITLE
Speed up Queue Order Issue

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5780]
Currently if I have a queue with a `speed up` attempt, the new attempt will appear lower in the list, since it is newer and the current list is chronological.

This is counter-intuitive since we try to put the "speed up" on the top transaction.

<img width="702" alt="screen shot 2018-11-18 at 3 39 26 pm" src="https://user-images.githubusercontent.com/542863/48679686-30945400-eb48-11e8-8607-87cafa015b3b.png">

Proposal:
The "Queue" sort order should be nonce order increasing, with nonce ties broken by ranking the highest priced transaction as earlier in the list.

This would be a band-aid until we're grouping retry attempts into the same history item. (https://github.com/MetaMask/metamask-extension/issues/5544)

Related to #5374

**Comment by Gudahtt** [comment]
Since this issue was created, we have made dramatic changes to the transaction history view. Retry/speedup attempts are now grouped with the original transaction being retried, and the status is more clearly labelled. I think we can consider this to have been completed.
