### ISSUE TITLE
improve gas price suggestions in retry tx's 

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#5782]
At this moment the gas price can be set to 0... which when retried the minimum can be set to 0 because 0 / 100 * 10 = 0 so lets not do this because txs will either fail or hang in pending.

I can do the background if you want to handle the ui @danjm

**Comment by tmashuang** [comment]
https://github.com/MetaMask/metamask-extension/issues/4058
https://github.com/MetaMask/metamask-extension/pull/4073
https://github.com/MetaMask/metamask-extension/pull/4037

TLDR; private/test networks. Maybe just mainnet?

**Comment by danfinlay** [comment]
Rather than doing a blanket ban on a price that could be valid for many networks, I'd like to learn why 0 was estimated.

The retry issue would be solved with #5779.

**Comment by frankiebee** [comment]
@danfinlay 0 was not estimated for gasPrice the user chose it

**Comment by frankiebee** [comment]
and then was able to continue using it through the retries. The actual recommended gas price was ignored

**Comment by frankiebee** [comment]
i've renamed this issue to better reflect the problem
