### ISSUE TITLE
Allow setting Custom RPC as default network

### ISSUE THREAD

**Issue by tomtom87** [MetaMask/metamask-extension#5788]
How can I set the default RPC and network ID to be a custom RPC and not the infura mainnet, as I would like to customise metamask to default start on my custom rpc url and network. 

I have tested and everything is working as desired if I input a custom rpc.

 I just want to make that the default setting for 'mainnet' now.

Thanks

**Comment by bdresser** [comment]
Sorry @tomtom87, we don't allow you to change the default network settings - just add new ones. 

Will leave this open for now to gauge broader interest.

**Comment by tomtom87** [comment]
@bdresser ok thanks for explaining. Cheers!

**Comment by whymarrh** [comment]
I think this is by design, the current workflow is to add a new custom network and use that.

**Comment by Mister-Sonny** [comment]
I would also like to request this feature.  I use Metamask for my Ethereum wallet, but I also use Metamask for MATIC (polygon) network transactions.  Right now if I want to get MATIC into my wallet and on the MATIC network I end up with it first showing up on the Ethereum Mainnet section of Metamask, then incurring a gas fee to bridge it over.

**Comment by zakrad** [comment]
Now they banned certain countries to access by Infura blacklist and don't allow to change default RPC, such a BS metamask turned out to be in decentralized web3

**Comment by bordee** [comment]
I'm going to tell everyone I know not to use MetaMask anymore.
The default RPC is set to a CENTRALIZED one and users can't even change it?!?! Really?!
What values are you committed to? Or should I say: who's money?....

**Comment by mosi-sol** [comment]
> I'm going to tell everyone I know not to use MetaMask anymore. The default RPC is set to a CENTRALIZED one and users can't even change it?!?! Really?! What values are you committed to? Or should I say: who's money?....

they are sold the souls for more power
