### ISSUE TITLE
Organize Settings Menu

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5790]
It's getting busy in there! 

Rough organization might be

Display
- currency conversion
- primary currency
- language 
- blockies identicon 

Developers 
- Download State Logs
- Reset Account
- Edit gas from send/confirm screens
- Show Hex Data
- Show conversion on testnets
- Custom RPC fields
  - view current custom network?
- More, as we determine what devs should be able to switch on/off

Accounts & Security
- Privacy Mode
- Clear Privacy Data
- Reveal Seed Words

**Comment by bdresser** [comment]
@cjeria @danfinlay any other thoughts?

**Comment by wbt** [comment]
I'd really like to be able to view (and ideally edit) settings for the currently selected network.  Right now, if I've gone into Settings for a New Network/custom RPC, I can't **double-check those settings (like URL or ChainID) when debugging a connection issue**, and can't even fix a typo in the nickname, without just creating another new network and hoping that all the information is getting stored right.

**Comment by wbt** [comment]
>Custom RPCs could easily be their own tab / section in a new menu.

**I would definitely separate Network Settings and Metamask settings into separate screens.**  The Network Settings screen would be accessible from the Network dropdown, showing network settings for the currently selected network.  Clicking Custom RPC in that same dropdown would pull up the same Network Settings display, but blank, and allow someone to add a new network.  

When logged out, the Network Settings view could still be available, and functional for the blank custom RPC instance (might address issue #5606), with other networks' settings read-only plus a message "you need to log in to Metamask before you can change these settings.  You can also _copy these settings to a new custom network_ and edit them there. (Italics = link)

**Comment by wbt** [comment]
In the Network Settings screen, I would add a setting for the color, so that Custom RPC networks aren't always a white circle with a black question mark indicating something might be wrong.

**Comment by bdresser** [comment]
done in https://github.com/MetaMask/metamask-extension/pull/6333
