### ISSUE TITLE
Handle undefined RPC responses more gracefully

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5794]
Sometimes Infura is throwing us `undefined` in response to our requests. That's not our fault, but it is our fault that we don't handle it gracefully.

We should make sure we can handle `undefined` responses without crashing, and just resume our best.

Related to #3107

**Comment by bdresser** [comment]
@danfinlay good to close this?

**Comment by Gudahtt** [comment]
This has been fixed since the introduction of the permission system
