### ISSUE TITLE
Connect requests don't pop up/generate notifications

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#5795]
Connect Requests (those in "privacy mode") don't pop up or generate notifications on the icon, I have to guess that that's why the site is not loading and intuitively click on the MM icon to make the request appear.

 - OS: Windows
 - Browser: Waterfox
 - MetaMask Version: e.g. 5.0.2

**Comment by bdresser** [comment]
@leafcutterant you're right that connect requests don't generate a notification on the icon. But I am seeing them pop up reliably on Waterfox, on 5.0.2 and 5.0.3 (which is just now rolling out). 

What dapp / site are you using? Does it pop open when you manually call `ethereum.enable()` from the console?

**Comment by whymarrh** [comment]
This was fixed in #5832 (noted above)
