### ISSUE TITLE
When I submit a transaction , I stuck on `Estimating transaction cost…`

### ISSUE THREAD

**Issue by tanhuiya** [MetaMask/metamask-extension#5802]
![image](https://user-images.githubusercontent.com/10923091/48833777-1b712c80-edb7-11e8-84ab-60830d83be5a.png)

**Comment by tanhuiya** [comment]
version  : 5.0.3

**Comment by tanhuiya** [comment]
I found the problem happend in my private network using `geth`

![image](https://user-images.githubusercontent.com/10923091/48876880-895f3780-ee3b-11e8-83c3-56e93a983b71.png)

**Comment by jflowers1974** [comment]
BUMP - same here....

**Comment by bdresser** [comment]
@jflowers1974 are you on a private or public network? any reproduction steps to help us debug? looks like OP found the issue was on their own end, not a MM bug.

**Comment by jennypollack** [comment]
Hey @tanhuiya are you still experiencing this issue? Closing for now, but feel free to reopen if it's still causing you trouble.
