### ISSUE TITLE
Migrate to GABA

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5806]
Migration plan TBD, but could start with a couple specific controllers. 

See https://github.com/MetaMask/metamask-extension/pull/4491

Relates to #5230

**Comment by bitpshr** [comment]
I started on this before getting sidetracked by the new provider API:

https://github.com/MetaMask/metamask-extension/pull/5844
https://github.com/MetaMask/metamask-extension/pull/5847

I'll clean this work up this week and continue with controller conversion.

**Comment by bdresser** [comment]
Transaction controller and preferences controller will unblock collectibles #5230 
Transaction controller will unblock incoming transactions #133

**Comment by bdresser** [comment]
GABA notes [here](https://hackmd.io/XTTL60n4R5mt69vtbK1qGg?view)

**Comment by brad-decker** [comment]
We still intend to migrate controllers into metamask/controllers, however, the order of operations and action plan has likely changed. We will revisit issue creation in the new year when we target this work.
