### ISSUE TITLE
Better Reliability

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5807]
Catch-all epic to track our work on improving release process and product reliability. Ship easier & with fewer bugs.

**Comment by bdresser** [comment]
Many of these issues involve making a switch from Selenium to Cypress. In general it's more reliable, comes with some helpful auxiliary tools, helps identify bug source more quickly. 
- doesn't support testing Chrome extensions out of the box. there are some workarounds to investigate
- may need to mock out parts of the extension API in order to fully test MM with Cypress; could be costly in terms of effort
  - wouldn't be super tough to mock out the extension API, but mocking the popup mechanics could be challenging - might try replicating using a series of iframes?
  - BUT some bits have crept in to the main app folder
- Cypress has extension support "in their roadmap" -- perhaps we can reach out? or delay until they land support?
- Could also explore other options (e.g. Puppeteer)


Plan of action: 
- @danjm and @tmashuang start with #6034 and then revisit the rest of the epic
- @bdresser to check on status of extension support

**Comment by Gudahtt** [comment]
Closing; many of the original issues linked to this epic are still outstanding, but this has gone stale. We're not even using ZenHub anymore. We'll track any outstanding work elsewhere instead.
