### ISSUE TITLE
Support Grid+ Lattice1 hardware wallet

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5811]
Grid+ is launching a hardware wallet in early 2019
* pairs over wifi
* can sign ETH transactions
* can pre-approve signatures
* no support for standard signing methods yet

More info
https://blog.gridplus.io/introducing-the-grid-lattice1-bc4ff6df5321
https://github.com/GridPlus/gridplus-sdk

**Comment by Robbiekruszynski** [comment]
@bdresser 
Please feel free to share this find in the ConsenSys discord! 
Let me know if you need an invite. 

Going to close this ticket.
