### ISSUE TITLE
Versions 4.17 and newer do not work on Opera

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#5818]
The current version available to opera users from the opera store is 3.14.1, which is quite old.  Some users would like to manually install a newer version.  The latest version that works is 4.16.  Newer versions are available to manually download but throw errors.  I recommend we pull opera versions of 4.17+ until addressed.

Setting up Sentry Remote Error Reporting: SENTRY_DSN_PROD
background.js:1 Injecting MetaMask Mesh testing client
TypeError: Cannot read property 'onErrorOccurred' of null
    at t.exports (background.js:1)
    at ee (background.js:1)
    at background.js:1
    at _ (background.js:1)
    at Generator._invoke (background.js:1)
    at Generator.e.(anonymous function) [as next] (chrome-extension://ecdgfjlaipnedkkkajjnldjadjlfdgfd/background.js:1:1676388)
    at n (background.js:1)
    at background.js:1
inpage.js:1 ATTENTION: In an effort to improve user privacy, MetaMask stopped exposing user accounts to dapps if "privacy mode" is enabled on November 2nd, 2018. Dapps should now call provider.enable() in order to view and use accounts. Please see https://bit.ly/2QQHXvF for complete information and up-to-date example code.
(anonymous) @ inpage.js:1
contentscript.js:1 MetamaskContentscript - lost connection to MetaMask Contentscript Forwarding
a @ contentscript.js:1
contentscript.js:1 MetamaskContentscript - lost connection to MetaMask Inpage
a @ contentscript.js:1
contentscript.js:1 MetamaskContentscript - lost connection to MetaMask Background
a @ contentscript.js:1
contentscript.js:1 MetamaskContentscript - lost connection to MetaMask PingPongStream
a @ contentscript.js:1
partialRollout.js:28 MetaMask Mesh Testing - threshold not matched -- skipping test

**Comment by k06a** [comment]
Got same error for MetaMask 5.0.3

**Comment by Geenustthanapuss** [comment]
Ha ha ha g

**Comment by Geenustthanapuss** [comment]
In your life when issues was happened. What wi

**Comment by tmashuang** [comment]
Closing due to the lack of support we have for Opera.
