### ISSUE TITLE
How to revoke permission of ethereum.enable()

### ISSUE THREAD

**Issue by glitch003** [MetaMask/metamask-extension#5821]
I am trying to test adding ethereum.enable() to my dApp, but in order to test properly, I need to be able to revoke permission.  But ethereum.disable() is not a function, and I cannot find docs on how to do this.

How does one revoke account permission on a given website?

**Comment by micahalcorn** [comment]
@glitch003 in my case, I just open MetaMask > Settings > Clear privacy data. I doubt there is a method for it.

**Comment by glitch003** [comment]
Wow, how did I miss that button?  Thank so much @micahalcorn !

**Comment by kyriediculous** [comment]
It would be nice to have such a method though.

Uport offers similar functionality to remove credentials from localstorage.

Using the button would clear privacy settings for ALL of the users websites, so I still feel functionality to revoke single websites is needed. 

> Clear privacy data so all websites must request access to view account information again.
