### ISSUE TITLE
Installation Detection

### ISSUE THREAD

**Issue by micahalcorn** [MetaMask/metamask-extension#5823]
I understand that checking for `web3.currentProvider.isMetaMask` or `ethereum._metamask` can reveal whether or not MetaMask was installed _at the time that the page was loaded_. I am looking for a way to detect the actual installation of the extension. This can be done with Firefox by polling for the injection as follows (assuming version >=5.0.0):
```js
const { ethereum } = window

if (!ethereum) {
  const int = setInterval(() => {

    if (ethereum && ethereum._metamask) {
      // installation has occurred

      clearInterval(int)
    }
  }, 1000)
}
```
However, this does not work in Chrome as there is no injection until the page is manually reloaded. It seems that maybe [an `onInstalled` event](https://developer.chrome.com/extensions/runtime#event-onInstalled) could be used to either initiate the injection or set some other flag that a DApp could watch for. Is there already a way to handle this in Chrome?

**Comment by jennypollack** [comment]
Hey @micahalcorn please check out our [onboarding library](https://github.com/MetaMask/metamask-onboarding) I think it might be useful for you here.
