### ISSUE TITLE
Impossible to cancel transactions

### ISSUE THREAD

**Issue by bneiluj** [MetaMask/metamask-extension#5824]
**Describe the bug**
It's impossible to cancel one, multiple or all transactions. When a cancel is triggered on a tx, it creates a cancel attempt and keeps the the original tx in pending mode. 

**To Reproduce**
1. Go to TX's
2. Cancel the oldest tx 
3. Scroll down to the pending tx
4. See pending tx

**Expected behavior**
I should be able to cancel the first tx in the queue (eg: oldest) to unlock all the other tx's. Even canceling all tx's doesn't work. 

**Screenshots**

All tx's are in cancel pending status.

<img width="691" alt="screen shot 2018-11-25 at 10 55 46" src="https://user-images.githubusercontent.com/3680497/48978284-35ee2300-f0a1-11e8-8b65-e8121ba35262.png">

**Browser details:**
 - OS:  Mac High Sierra
 - Browser: Chrome Version 70.0.3538.77
- MetaMask: Version 5.0.3

**Additional context**

**Comment by bdresser** [comment]
@bneiluj as you probably know, trying "cancel" a transaction is simply submitting another empty transaction with the same nonce and higher gas. If that second tx (the cancellation attempt) is confirmed first, the earlier transaction will never be confirmed, effectively "cancelling" it.

This is totally dependent on current gas prices when you try to cancel - sometimes those cancellation attempts take a long time to land too, in which case we should allow you to speed up your cancellation attempt (https://github.com/MetaMask/metamask-extension/issues/5732)

In https://github.com/MetaMask/metamask-extension/issues/5544 we'll update to a slightly more accurate design, grouped by nonce, which will show one nonce as one entry and will let you know the most recent activity taken with that transaction.

For now, try going to one of the "Cancel Attempt" transactions with nonce 43, clicking "Speed Up," and increase the gas price to something competitive. This should confirm, mark all other transactions with nonce 43 as `dropped` and unstick transactions with a higher nonce. 

Closing this, as the design feedback should be taken care of in the two issues linked above. 

cc @cjeria @alextsg @danjm
