### ISSUE TITLE
Seed Phrase Education

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5834]
Starter issue for a discussion on seed phrase education. Some ideas we've discussed
* Better copy and UI during the initial seed phrase / setup flow
* Video resources to explain what each piece is used for (password, seed, etc) and how accounts relate to each other
* Onboarding wizard described in #4323

**Comment by hatgit** [comment]
I would recommend firstly teaching the users that the seed phrase is derived from a large random number 128 bits long, and 4 bits are added to that as a checksum-derived portion of a hash (where those 128 bits are hashed). And - even if they don't understand it (which we don't expect them to, but maybe they can click here to learn more,etc.) - how what that means is that the final word fits to make all 12 words valid. So when they back up those words it is an easy way for them to remember those 132 bits, and that this all happens client-side in their browsers so no one else will know this data unless there is some eavesdropper watching them (in which case they can perhaps click here, to learn about offline mnemonic seed phrase derivation methods, to create their own recovery phrases offline then import into MetaMask).

**Comment by Gudahtt** [comment]
This is still actively being worked on., but I'm closing this issue now, as we're tracking efforts to improve seed phrase education elsewhere now (in Avion, Figma, etc.).
