### ISSUE TITLE
Hybrid "Connect" and "Password" screen

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5836]
When a user's wallet is locked and a dapp calls `ethereum.enable()`, MetaMask pops open the password window, then after the user enters their password, it shows the 1102 "Connect" modal – even if the user has previously approved the domain.

We could implement a hybrid version of the Connect modal that includes the relevant 1102 infos, but also asks for a password on the same screen.

Would require some education to get users comfortable with entering their password in a new UI - and worth considering that expanding the different password UIs may not be great for security.

**Comment by Gudahtt** [comment]
This was fixed a while back; we now no longer show the user the Connect flow if they've already been connected. Instead the popup appears, navigates to the lock screen, then closes when the user unlocks.
