### ISSUE TITLE
Error: [ethjs-query] while formatting outputs from RPC '{"value":{}}'

### ISSUE THREAD

**Issue by rekt0x** [MetaMask/metamask-extension#5837]
**Describe the bug**
I developed a web app which serves as a dApp frontend for a smart contract. It works fine on my local Ganache testnet and the Ropsten testnet, but after deploying the contract to the mainnet the application/MetaMask throws some weird errors in the developer console.
In addition to that the UI of my dApp sometimes changes in an unexpected manner (it seems like web3 can not read values properly).

**To Reproduce**
1. Go to https://block42.uber.space/smart-wedding-contract/
2. Tell MetaMask to use the Main Ethereum Network
3. Open the Chrome Developer Console
4. Wait until the error appears in the console
5. (optional) Refresh the browser and repeat 4.

**Expected behavior**
I expect it not to throw an error

**Screenshots**
![image](https://user-images.githubusercontent.com/6087393/49032491-fdd40680-f1ac-11e8-8b54-85a05b98c4f1.png)

**Browser details (please complete the following information):**
 - OS: MacOS 10.14.1 (18B75)
 - Browser: Chrome Version 70.0.3538.102 (Official Build) (64-bit)
 - MetaMask Version: 5.0.3

**Comment by snoopy1412** [comment]
same to me

**Comment by rekt0x** [comment]
I thought it's could be due to the web3 instance injected by metamask. Maybe the problem could be solved by using the standalone web3js.

**Comment by miketeix** [comment]
I'm seeing this

**Comment by yfenggo** [comment]
Has someone find the solution for this?

I encounter this issue on localhost (React JS project), on local Ganache blockchain.

.call() works perfectly, but .send() causes the same issue.

**Comment by tmashuang** [comment]
OP's reproduction has been resolved with the site in question. If you need further help try https://ethereum.stackexchange.com/.
