### ISSUE TITLE
Incorrectly showing checksums on non-ETH blockchains

### ISSUE THREAD

**Issue by herrerameri** [MetaMask/metamask-extension#5838]
**Describe the bug**
If you add a custom RPC node, the addresses are always shown as they're ETH addresses.

**To Reproduce**
1. Add a CUSTOM RPC node (e.g.: RSK public node https://public-node.testnet.rsk.co)
2. Look at default address: checksum is not correct for RSK, because it's ETH checksum

**Expected behavior**
If network `chainId` is not an ETH one, it's better to see the address without checksum (lower case) instead of an address with a checksum which is not correct.

**Browser details (please complete the following information):**
 - OS: Ubuntu - Linux
 - Browser Chrome
 - MetaMask 5.0.3

**Comment by aeidelman** [comment]
The ideal scenario would be to adopt [EIP-1191](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md). If not possible, showing non-checksumed addresses in these cases is better than current situation.

**Comment by lazaridiscom** [comment]
@bdresser , should be closable (looks like fixed in #6001)
