### ISSUE TITLE
how to get the field "hex data optional"  on contract  when I send eth with metamask;

### ISSUE THREAD

**Issue by liwei00wade** [MetaMask/metamask-extension#5841]
I want to receive an optional data on contract  when send eth to my contract address;
Can i use the field "hex data optional" ?

**Comment by tmashuang** [comment]
Settings > Show Hex Data Toggle button

**Comment by 1blockologist** [comment]
Can you guys stop hiding this? @bdresser 

It should be in some advanced or gas tab on the form transaction screen by default, it doesn't have to be an expanded field
