### ISSUE TITLE
eth_getTransactionCount of "pending" returns number instead of hex string

### ISSUE THREAD

**Issue by epheph** [MetaMask/metamask-extension#5845]
Calling eth_getTransactionCount against the "pending" block returns transaction count as a number. Asking for "latest" or any other block returns hex string of the transaction count.

In your browser console:
```
window.ethereum.sendAsync({"jsonrpc":"2.0","method":"eth_getTransactionCount","params":
 ["0x003bbce1eac59b406dd0e143e856542df3659075", "pending"],"id":1}, console.log)

{id: 1, jsonrpc: "2.0", result: 35693}
```

```
window.ethereum.sendAsync({"jsonrpc":"2.0","method":"eth_getTransactionCount","params":
 ["0x003bbce1eac59b406dd0e143e856542df3659075", "latest"],"id":1}, console.log)

{id: 1, jsonrpc: "2.0", result: "0x8b6d"}
```

**Expected behavior**:  The JSON-RPC interface standard uses hex-string for transactionCount result

 - OS: OS X
 - Chrome
 - MetaMask Version 5.0.3

Found while fixing this eth library issue: https://github.com/ethereumjs/ethrpc/pull/122
Discovered while using a hardware wallet to sign using custom code, but metamask is loaded and the `window.ethereum` object is used to query for nonce.

**Comment by Gudahtt** [comment]
I am still able to reproduce this bug in v8.1.10
