### ISSUE TITLE
batch transactions appear in wrong order and fail my transactions

### ISSUE THREAD

**Issue by ashachaf** [MetaMask/metamask-extension#5852]
**Describe the bug**
when trying to sign a batched transaction, it actually appear in the wrong order on metamask and force nonce that sends the transactions in the wrong order to the blockchain, resulting in a fail transaction due to that.

**To Reproduce**
1. Go to 'https://www.bancor.network/tokens'
2. Click on 'convert'
3. select to execute the transaction using metamask
4. select any pair of tokens to convert (select erc20, not ETH or BNT)
![image](https://user-images.githubusercontent.com/40430285/49227824-b6d75280-f3f2-11e8-9e7f-95dbfb9d6e48.png)

5. view the transaction on metamask
![image](https://user-images.githubusercontent.com/40430285/49232967-a11b5a80-f3fd-11e8-91d5-75236585ab27.png)

**Expected behavior**
expected: 1st transaction is "approve", 2nd is the quickconvert 
actual: 1st transaction is quickconvert (should be 2nd), 2nd is "approve" (should be 1st)

**Screenshots**
metamask interface display the transactions in the wrong order (notice order and nonce)
![image](https://user-images.githubusercontent.com/40430285/49233094-e8095000-f3fd-11e8-93df-66dd7934db89.png)
![image](https://user-images.githubusercontent.com/40430285/49233119-f9525c80-f3fd-11e8-894d-c53d92d1e026.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - MetaMask Version 5.0.3

**Additional context**
old UI handle the transactions incorrectly as well, where it orders them correctly but let the user sign the 2nd transaction first.
this is the popup you will see
![image](https://user-images.githubusercontent.com/40430285/49233447-b5ac2280-f3fe-11e8-8ce9-90a1e9f64ad4.png)

**Comment by ashachaf** [comment]
@whymarrh @PaddyMc,
please let me know if you require additional information on this bug.
thanks,

**Comment by ashachaf** [comment]
@whymarrh @danfinlay,
bug #3425 was opened to fix an existing issue. the work was done and published yet it fixed nothing.
how can we reopen this topic and make sure it is sorted?

thanks,

**Comment by or2008** [comment]
any updates?

**Comment by mitar** [comment]
For me this is a problem with simple ERC-20 token, where I first call `approve` on it and then `transferFrom` (wrapped inside a call to my contract's method) to transfer tokens. If I batch them together, they are not shown in the correct order, so `transferFrom` is called before `approve`. Which of course does not work.

**Comment by danfinlay** [comment]
If someone can provide a sample dapp demonstrating how batching is not working correctly, I'll reopen this issue.

**Comment by ashachaf** [comment]
Hi @danfinlay,

If you try to convert any ERC20 token to another token using bancor.network, you will be able to see how batch transactions are not handled correctly on metamask.

I can provide more details yet it is all available both online and in this thread.

Best,

**Comment by 0v1se** [comment]
Hi everyone.
I get the same bug. Sometimes order is wrong when I use batch.
But this behavior is rather unstable. It occurs about 25%.

This is shown when order is incorrect (although caption says 1 of 2 )
![image](https://user-images.githubusercontent.com/32102012/65518700-5ec38c80-deed-11e9-843e-815cd835bb03.png)

And this is shown when the order is correct (approve transaction added first to the batch)
![image](https://user-images.githubusercontent.com/32102012/65518749-74d14d00-deed-11e9-9c88-9710aa3c2b58.png)

**Comment by 0v1se** [comment]
Also, more information found: When I batch.execute(), new chromium window is opened.
My colleague has slightly different behaviour: window is not opened automatically. If he presses metamask button on the toolbar, 1 of 2 transactions is always shown

**Comment by adamsoffer** [comment]
Running into this issue as well! `batch.execute()` is confirming transactions in incorrect order. Seems there are a few open issues related to this. Any ideas @danfinlay @kumavis  ?

**Comment by danfinlay** [comment]
Can anyone provide a low-level example? `batch.execute()` is not a provider method, so it seems likely to me that this is the web3.js convenience library misbehaving.  Some sample code would really be _the_ thing to allow easy fixing of this. Sorry it's just not high enough of a priority for me to go digging into Bancor's code, since the workaround (delay serial transactions) is so simple.

**Comment by adamsoffer** [comment]
@danfinlay Here's ya go: https://codesandbox.io/s/metamask-batchrequest-bug-demo-emnph?fontsize=14

Instructions:
1. Connect to Rinkeby on MetaMask
2. Click "Activate MetaMask"
3. Click "Send Batch Transactions"

Clicking "Send Batch Transactions" will submit 3 transactions to a contract I deployed to rinkeby with a method called `setNumber`. The method will revert if you try and set a number lower than the currently set number. Notice the third transaction fails because metamask always submits the third transaction before the 2nd.

**Comment by adamsoffer** [comment]
Let me know if there's anything else you need to help reproduce and debug.

**Comment by adamsoffer** [comment]
@danfinlay Trying to debug. I think the issue was introduced somewhere [here](https://github.com/MetaMask/metamask-extension/pull/5437/files#diff-3a4a4206490ecc358f8c8d91d94b76d4R360). Any suspicions?

**Comment by adamsoffer** [comment]
Also, until this is fixed, do you mind sharing that simple workaround you mentioned (delaying serial transactions)? Maybe in a forked version of that codesandbox I sent?

**Comment by danfinlay** [comment]
A fix is starting to roll out tomorrow. I recommend waiting.

**Comment by adamsoffer** [comment]
Hey @danfinlay - looks like transactions are being ordered correctly now. Awesome! Not sure if y'all are still working on it, but noticing a few issues introduced:

1. It no longer prompts you to confirm the next transaction in the batch after you click confirm which is confusing.
2. It no longer displays the total number of transactions in the extension, it always displays `1` even if there are 3 pending transactions in the batch to be confirmed.
3. The ability to navigate between each transaction is gone.

To illustrate: here's what a batch request of 3 transactions looks like for me now.

![metamask-batch-bug](https://user-images.githubusercontent.com/555740/68974146-022e7080-07be-11ea-98c6-130b91ab2be3.gif)

**Comment by danfinlay** [comment]
Thanks for the quick catches, @adamsoffer. We'll address these sooner than the batch bug.

**Comment by ashachaf** [comment]
A M A Z I N G !
@danfinlay thanks for finally sorting this out!
@adamsoffer thanks for picking up a long unresolved conversation and bringing it to resolution!

**Comment by rekmarks** [comment]
@adamsoffer just wanted to note that those UX issues you described should not be an issue as of 7.7.2
