### ISSUE TITLE
Token balances not found

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5855]
No token balances appearing for several different tokens on production.

No errors in UI or background console.

Corroborated by https://github.com/MetaMask/metamask-extension/issues/5062#issuecomment-442336930

Could be related to a silent blocktracker failure, or related to 
https://github.com/MetaMask/metamask-extension/issues/5842
https://github.com/MetaMask/metamask-extension/issues/5723

**Comment by aleqx** [comment]
Sorry for necro, but I'm getting "No conversion rate available" now on v7.7.4 in Chrome for ETH. However, I just tried it Firefox and there it does show an USD value for ETH.
