### ISSUE TITLE
Wrong password when restoring from seed

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5866]
A user reported they got a wrong password error when restoring from seed, which should be impossible.

https://twitter.com/OwenFernau/status/1068700205195751424

**Comment by whymarrh** [comment]
This certainly shouldn't happen. We'd need more information though about how to reproduce it.

**Comment by whymarrh** [comment]
I'm thinking we can close this until we get further reports, ideally with reproduction steps?
