### ISSUE TITLE
Gas price and amount of gas 0. Transactions stuck

### ISSUE THREAD

**Issue by Forestgump999** [MetaMask/metamask-extension#5867]
Hi there,

Got a problem with a stuck transactions on MetaMask.
I have tried to send zero (0 ETH) transaction with zero gas price and zero gas limit and it looks like it stuck.
After that, I've tried to make any other transactions even with a good price and gas limit but all of them have "Pending" status. Looks like any of them won't start before first one will be executed.
But the interesting thing is, no any of that transactions have their TxHash, so its just says "Transaction has not found".

What can I do in this situation? I still have some ethereum on that account I want to transfer to another account.

I tried to send zero transaction to my own account. I have also tried to send the same transaction with big gas price and good enough gas limit, but it just put that transaction in queue as well.

So status says "Pending" but the transaction has "Unknown function" name or "Cancel Attempt".

This is the first transaction I got a problem with https://etherscan.io/tx/0xaab687175efc23cc6e16da043bab0b12321b5606e574992bf28dd6f8fd254140

**Comment by gohuygo** [comment]
@Forestgump999 Have you tried setting creating a new transaction with a higher gas price and setting the nonce to match the nonce of your first pending transaction?

**Comment by Forestgump999** [comment]
> @Forestgump999 Have you tried creating a new transaction with a higher gas price and setting the nonce to match the nonce of your first pending transaction?

I can't see nonce of the first transaction as it says "Transaction has not been found" so how can I now nonce of the first transaction? But in MetaMask history all of them have "Pending" status.

**Comment by gohuygo** [comment]
Try viewing your public address on etherscan and clicking on your latest valid transaction. You should see a nonce.

**Comment by Forestgump999** [comment]
Here is address on etherscan https://etherscan.io/address/0xa8b3dce898717f34ab13728bffa7378a8f07a2cd
The latest valid is "IN" transaction. But there are no any other transactions. Queued transactions are only on MetaMask history.

**Comment by Forestgump999** [comment]
> @Forestgump999 A nonce of 1 should do it.

So how can a create transaction with a nonce of 1? As I know I can only enter gas limit, gas price, address to and amount.

**Comment by gohuygo** [comment]
Forgot that I was on the Metamask github repo for a bit. It looks like Metamask doesn't support it yet - https://github.com/MetaMask/metamask-extension/issues/1410

It looks like you will have to use the offline feature of MEW or another wallet to do this. Look into MyEtherWallet > Send Offline.

**Comment by Forestgump999** [comment]
> Forgot that I was on the Metamask github repo for a bit. It looks like Metamask doesn't support it yet - #1410
> 
> It looks like you will have to use the offline feature of MEW or another wallet to do this. Look into MyEtherWallet > Send Offline. I've never used this feature so you're on your own here. Good luck!
> 
> This might help - https://www.reddit.com/r/EtherDelta/comments/72tctz/guide_how_to_cancel_a_pending_transaction/

What do you think, will “Reset account” button help in this situation? Will I loose wallets and any ETH in my account by doing this?

**Comment by drossi79** [comment]
I got exactly this problem.  After some hours if you check your very first transaction in the metamask stuck list (the one the caused the queue) just next the word "Details" it appears a button "speed up" click that botton then edit and then set a gas price different than zero. This unlock all the list.

If you can t' see that button wait tomorrow or more. Soon or later it will appear.

Cheers.

**Comment by Krumil** [comment]
Same problem here, but also the cancel transaction (and the next speed up transaction) got stuck. Now i cannot speed up the transaction. There's something i can do to resolve this?

**Comment by bdresser** [comment]
You should be able to "speed up" the transaction again, and supply a higher gas price. 

You can go to settings --> reset account, which will clear your transaction history. @Forestgump999 you will not lose your wallets or ETH, but as a reminder you should ALWAYS have your seed phrase backed up somewhere safe.

**Comment by tuenhi4817** [comment]
@Forestgump999 I am facing the same problem with zero gas price, have you solved it? Is resetting the account the solution?

**Comment by tmashuang** [comment]
Sending a transactions with 0 gas price can be done, but gives not incentive for miners to mine the transaction, which means that it will have submitted to the network but be in a perpetual state of `pending` until someone mines it. Sending a transaction with the same nonce as the 0 gas price transaction, but just with a gas price > 0 will provide incentives to mine the transaction. 

We've also have implement the Speed Up button for transactions which allow to speed up the transactions gas price with the same method I mentioned above.
