### ISSUE TITLE
Memory leak on Firefox, so far one site affected

### ISSUE THREAD

**Issue by cymerrad** [MetaMask/metamask-extension#5871]
**Describe the bug**
I've noticed it on only one site so far. As soon as the page loads, Firefox starts hoarding memory, something like 100MB/s. I've checked a lot of extension on/off combinations and it worked when MetaMask was _the only_ extension activated.

**To Reproduce**
1. Go to [KnowYourMeme (any article will work)](https://knowyourmeme.com/memes/impact)

**Expected behavior**
My whole system should remain stable. Firefox obviously too.

**Screenshots**
This was very difficult to screenshot. On the bottom screen there is a system CPU/Memory monitor.  
I've also captured `ps` output with 79% memory usage.  
[https://imgur.com/a/341t0ja](https://imgur.com/a/341t0ja)

**Browser details:**
 - OS: Manjaro 18.0, kernel release 4.19.4-1-MANJARO
 - Browser: Firefox 63.0.3 (64-bit)
 - MetaMask: 5.0.3

**Additional context**
As of writing this, KnowYourMeme may be slightly NSFW, because of Amouranth trending article.  
  
**Added note**: this also works when the page has already loaded and extension is just being activated.

**Added note 2**: I have a profiling file of the 'incident', created by Firefox. It's a 7MB tar.gz, any suggestions where to host it?

**Comment by bdresser** [comment]
Thanks for reporting @cymerrad. Definitely got my machine cooking. 

@tmashuang could you take a look? Seems like we haven't found all the memory leaks from https://github.com/MetaMask/metamask-extension/issues/4074

**Comment by marki555** [comment]
I also see high memory usage by MetaMask on Firefox. Usually I have FF running for several weeks without restart, with about 20 tabs open.
Right now MetaMask is using more than 1.5 GB as reported by `about:memory`. FF 64.0, MetaMask 5.3.0 on Windows 10.
Should I open a separate Issue for this?

```
│  ├──1,549.17 MB (68.11%) -- top(moz-extension://eb11d023-3cdb-4985-a12d-0ddf831338b6/_generated_background_page.html, id=4294967316)
│  │  ├──1,180.87 MB (51.91%) -- js-zone(0x10f27970000)
│  │  │  ├──1,148.36 MB (50.49%) -- strings
│  │  │  │  ├────824.40 MB (36.24%) -- string(<non-notable strings>)
│  │  │  │  │    ├──602.77 MB (26.50%) -- malloc-heap
│  │  │  │  │    │  ├──601.57 MB (26.45%) ── latin1
│  │  │  │  │    │  └────1.20 MB (00.05%) ── two-byte
│  │  │  │  │    └──221.63 MB (09.74%) -- gc-heap
│  │  │  │  │       ├──221.55 MB (09.74%) ── latin1
│  │  │  │  │       └────0.08 MB (00.00%) ── two-byte
│  │  │  │  └────323.96 MB (14.24%) ++ (5228 tiny)
│  │  │  └─────32.51 MB (01.43%) ++ (16 tiny)
│  │  └────368.30 MB (16.19%) -- active
│  │       ├──366.69 MB (16.12%) -- window(moz-extension://eb11d023-3cdb-4985-a12d-0ddf831338b6/_generated_background_page.html)
│  │       │  ├──366.51 MB (16.11%) -- js-realm(moz-extension://eb11d023-3cdb-4985-a12d-0ddf831338b6/_generated_background_page.html)
│  │       │  │  ├──362.60 MB (15.94%) -- classes
│  │       │  │  │  ├──232.72 MB (10.23%) -- class(Object)/objects
│  │       │  │  │  │  ├──217.72 MB (09.57%) ── gc-heap
│  │       │  │  │  │  └───15.00 MB (00.66%) ++ malloc-heap
│  │       │  │  │  ├───66.51 MB (02.92%) -- class(Function)/objects
│  │       │  │  │  │   ├──58.67 MB (02.58%) ── gc-heap
│  │       │  │  │  │   └───7.84 MB (00.34%) ── malloc-heap/slots
│  │       │  │  │  ├───28.49 MB (01.25%) -- class(Call)/objects
│  │       │  │  │  │   ├──28.49 MB (01.25%) ── gc-heap
│  │       │  │  │  │   └───0.01 MB (00.00%) ── malloc-heap/slots
│  │       │  │  │  ├───26.19 MB (01.15%) ++ class(Array)/objects
│  │       │  │  │  └────8.68 MB (00.38%) ++ (7 tiny)
│  │       │  │  └────3.91 MB (00.17%) ++ (8 tiny)
│  │       │  └────0.18 MB (00.01%) ++ (4 tiny)
│  │       └────1.61 MB (00.07%) ++ window(https://metamask.github.io/mesh-testing/)
```

**Comment by vinhtq115** [comment]
Got the same issue here. I'm on Firefox 69.0.1 (64-bit), Windows 10 ver 1903, MetaMask 7.1.1 and have the same memory leak when visiting KnowYourMeme with MetaMask plugin enabled. Previously I got the same bug with my old computer as well.

**Comment by pizzapim** [comment]
I investigated this a bit. The problem is not specifically with KYM but a Google Trends script. I created a minimal document that shows the memory leak:
https://gist.github.com/pizzapim/07c439a35de92edd2bd79d54ffb0b627

I might investigate at a later date, but if anyone else wants to, feel free to use the document I provided

**Comment by sydbarrett74** [comment]
I am suffering from a memory leak bug, as well. MetaMask consistently takes up over 400MB of RAM. This seems a bit piggy for an extension. This is across dozens of Firefox versions, over a period of several years.

Machine specs:
Lenovo IdeaPad Y500
1TB HDD (50% full)
12MB RAM
Windows 10 x64 1909

If a developer wants logs or other helpful diagnostic information, please let me know.

**Comment by KingTerrytheTerrible** [comment]
I have trends.google.com blocked in my hosts file to alleviate this

**Comment by sydbarrett74** [comment]
@KingTerrytheTerrible do you have some numbers to show before/after impact? Can any of you others try this solution to see if it helps? If so, I'll contact Slashdot as well as Google to let them know of the impact that the Trends website is having on FF's rendering of that site, and this bug can then be marked as 'not our problem'.

**Comment by vinhtq115** [comment]
> 
> 
> @KingTerrytheTerrible do you have some numbers to show before/after impact? Can any of you others try this solution to see if it helps? If so, I'll contact Google to let them know of the impact that the Trends website is having on FF's use of that extension.

Here is my result:
Firefox 73.0 (64-bit)
Tested URL: [https://knowyourmeme.com/memes/crying-cat](url)

With MetaMask disabled: Firefox RAM usage hovers around 550-750MB
With MetaMask enabled: Firefox RAM usage shoots up to 2GB within 10 seconds and continues increasing.

**Comment by KingTerrytheTerrible** [comment]
Apologies, I was incorrect. It did not help after all

**Comment by PandaWhisperer** [comment]
How much RAM usage is normal for Metamask? I just had some memory issues in Firefox myself, and when trying to find the culprit on `about:performance`, I noticed Metamask taking up about 145 MB, which is more than literally all other extensions, combined.

**Comment by vinhtq115** [comment]
Another site that cause memory leak issue. This one also uses Google Trends.
Link: https://bitinfocharts.com/ethereum/
Seems like the issue #1689 is also related to this one.

**Comment by tmashuang** [comment]
Currently still active trying to reproduce this and improving injection on sites like G Trends.

**Comment by Saectar** [comment]
This problem is still present today. I am unable to access [Know Your Meme](https://knowyourmeme.com/) due to this error. What I can do?

**Comment by alula** [comment]
You can use the following uBlock Origin filter as a workaround:
```
! 2022-04-07 https://knowyourmeme.com
||trends.google.com/trends/embed/*$subdocument,domain=knowyourmeme.com
knowyourmeme.com##.google-trends-embed-wrapper
```

**Comment by Saectar** [comment]
> You can use the following uBlock Origin filter as a workaround:
> 
> ```
> ! 2022-04-07 https://knowyourmeme.com
> ||trends.google.com/trends/embed/*$subdocument,domain=knowyourmeme.com
> knowyourmeme.com##.google-trends-embed-wrapper
> ```
Thank you! It works, although you obviously lose the functionality of Google Trends. I hope the MetaMask can fix the problem.

**Comment by Corosauce** [comment]
> You can use the following uBlock Origin filter as a workaround:
> 
> ```
> ! 2022-04-07 https://knowyourmeme.com
> ||trends.google.com/trends/embed/*$subdocument,domain=knowyourmeme.com
> knowyourmeme.com##.google-trends-embed-wrapper
> ```

This worked for me too on both chrome and firefox that each have metamask installed, thanks!

**Comment by alula** [comment]
^ they still are lol

**Comment by NDR0216** [comment]
this issue still exists on Firefox...
