### ISSUE TITLE
Notification popUp By MetaMask

### ISSUE THREAD

**Issue by Mazze44** [MetaMask/metamask-extension#5873]
Hi, i'm using testrpc with a private network in metamask, regarding the same contract if i make a transaction via remix, metamask ask me to accept the transaction , but if i use a simple interface make with web3, the transaction is confirmed in the blockchain and in remix too (the ether of the fee is subtract from the total of the address too) but metamask don't notify me anything

**Comment by bdresser** [comment]
@Mazze44 you're saying the transaction submits without asking confirmation? Could you provide some more thorough reproduction steps and maybe the example code you're using in Remix please?

**Comment by saranyailla** [comment]
I have the same issue. Also, transaction receipt is not returned though it is a success.

**Comment by tmashuang** [comment]
Closing this, please provide reproduction steps. The description you provided has no easy way to reproduce your issue, just your methods. Please provide the details with the network, remix contract version, and contract to get better support.
