### ISSUE TITLE
Transaction NaN failed! Error:

### ISSUE THREAD

**Issue by rubgithub** [MetaMask/metamask-extension#5880]
I've received this google chrome notification, this happened a few moments after open chrome.

> Transaction NaN failed! Error:
> Transaction found as "approved" 
> during boot - possibly stuck during signing
![untitled](https://user-images.githubusercontent.com/3399476/49479402-4fa60d80-f7f9-11e8-8c2f-d0e22da5fe17.png)

What does this mean? 
Is this some hacker trying to steal??

**Comment by bdresser** [comment]
No hacker, just a failed transaction. If you experience this again, or can reproduce reliably, please let us know.

**Comment by alvarocheca** [comment]
It is happening to me now, exactly the same. I´m traying to send LINK tokens through Smart Chain Binance network (BEP20) back to my binance wallet. Because I accidentaly I selected that network instead of ERC20 to send those to my ledger, and obviously they´ve never arrived.
@bdresser can you help me?

**Comment by bigcook12345** [comment]
Are you using the "Web3" extension? The majority of the time, it always has
to be used to even login....

Safer network

**Comment by alvarocheca** [comment]
@bigcook12345 Yes, I am. The transaction just stays "pending" for an hour and then that notification appears...

**Comment by bigcook12345** [comment]
Yeah,

With it being down. It sure is a pain...I've even tried outsourcing, my
transfers, and nothing seems to work 🤷‍♂️.

**Comment by melsmog** [comment]
Happens to me now on BSC, how do I fix it?

**Comment by VSG24** [comment]
Don't use MetaMask on BSC

**Comment by danielmacuare** [comment]
I'm having exactly the same Issue. I'm trying to approve CAKE on Binance Smart Chain (via PancakeSwap) but I always get the pending transaction for an hour to later get the same error Transaction NaN Failed!

![image](https://user-images.githubusercontent.com/24361228/108756022-e6c52000-753f-11eb-9258-895c5662319c.png)


![image](https://user-images.githubusercontent.com/24361228/108755996-df057b80-753f-11eb-8255-b5dfbecb8f06.png)


Anyone has been able to find a workaround?

@VSG24 What do you use an alternative to Metamask to do trades on BSC?

**Comment by danielmacuare** [comment]
This has helped me to solve the problem, hope it helps someone else. https://github.com/MetaMask/metamask-extension/issues/10132

- Make sure ledger live is upto date and all your apps in ledger live is also updated.
- Close ledger live
- Close you browser
- Connect ledger to laptop
- Unlock your ledger using pin number
- Open the ethereum app on the ledger, under contract data make sure it is set to "allowed"
- Open the ethereum app on the ledger and make sure it is set on "application is ready"
- Now open your browser
- Sign into metamask and connect ledger
- Proceed with contracts, approve them as normal
- Check your ledger and make sure to approve any contracts that pop up on the ledger.

Following these steps should fix your problem with "stalled out transactions" on metamask while your ledger is connected.

Source: https://github.com/MetaMask/metamask-extension/issues/10132
Thanks to  @cam8099sa

**Comment by IzHB** [comment]
having the same problem as JafCR under same circumstances. but not only the NAN failed but also it's been saying I have no gas money, but I do. Any work arounds for metamask in polygon

**Comment by JafCR** [comment]
> having the same problem as JafCR under same circumstances. but not only the NAN failed but also it's been saying I have no gas money, but I do. Any work arounds for metamask in polygon

Quick update:
This started happening ~2weeks ago, but only using Metamask in Brave browser.
On Chrome I'm able to operate normally.

**Comment by Toty02** [comment]
guys if you are using brave just turn off this button 
![bravee](https://user-images.githubusercontent.com/35378525/143789044-54dbd002-30fc-4b06-a90c-ba9e72f70226.PNG)

**Comment by JafCR** [comment]
Thank you @Toty02 
it worked! - Gracias!
