### ISSUE TITLE
using block numbers against infura that the nodes are not aware of result in miss information 

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#5881]
if you were to query for example getCode with a block number out of bounds of what the node knows the response will be `0x` which is a misrepresentation of the current state and can cause gas estimation on transactions to be set to 21000 along with some other nasty side effects.

some solutions could include allowing 'latest' to be passed as the block number instead of trying to fill it with the block-trackers know number on request.

some cases of this:
#5868 
#5588

**Comment by Gudahtt** [comment]
This appears to have been caused by a bug in geth (https://github.com/ethereum/go-ethereum/issues/18254), and has been fixed.
