### ISSUE TITLE
Ether balance still not showing

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5883]
On version 5.1.0, ether balance sometimes showing as `...`. This seems to suggest the cached-balances-controller is maybe not doing everything it needs to, to avoid this kind of bad balance state.

Reported in:
https://consensys.zendesk.com/agent/tickets/13573

**Comment by danfinlay** [comment]
One way this might happen (not sure) is if we have:

- Load balancer
  - Node A: block 1, balance 0
  - Node B: block 2, balance 1

And then this happens:

1. User hits load balancer, is routed to Node B, gets balance 1
2. User hits load balancer, is routed to Node A, gets null response b/c node is not aware of block 2.

The second request returns a more recent valid response, but does it overwrite the value?

Another way to extend the balance cache would be to cache the block number of the cached balance, and only update the cache when a later block balance is found.

**Comment by danjm** [comment]
@danfinlay any chance we have state logs for this?

And the balance will only ever be cached if it is not null or undefined. If a non-null balance, is cached, then a future null balance will not overwrite it.
