### ISSUE TITLE
Ctrl+Shift+T brings back Metamask pop-ups

### ISSUE THREAD

**Issue by diegonc** [MetaMask/metamask-extension#5895]
**Describe the bug**

When an operation requires user confirmation a pop-up window will be opened by Metamask. After confirmation is given, pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> (Chrome key combination to reopen last closed page) will bring back the pop-up displaying what it looks like the account status window.

**Expected behavior**

If possible, these pop-up windows should be excluded from the page trail.

**Screenshots**

![metamask_ctrl-shift-t](https://user-images.githubusercontent.com/261458/49688529-795d7e00-faf2-11e8-8f26-3def5fb3360d.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - MetaMask Version: 5.1.0

**Comment by Gudahtt** [comment]
Thanks for the request! Unfortunately I don't believe this is possible without manipulating browser history, which would require additional extension permissions. We have a very high bar for asking for more permissions from users (especially one as invasive as `history`), so we won't be considering this in the near future.

Sorry we couldn't accommodate this request, but this is more of a browser mis-feature than a MetaMask bug. As understandable a request as this is, our hands are tied.

Please let me know if I've misunderstood the request though, or if I am wrong about this requiring the manipulation of browser history.
