### ISSUE TITLE
bug - after chrome has been open for a while, chrome requires a restart in order to send a tx

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#5898]
**Describe the bug**
bug - after chrome has been open for a while, chrome requires a restart in order to send a tx

**To Reproduce**
1. leave chrome open for hours, maybe days.
2. try to send a tx
3. tx hangs

**Expected behavior**
instead of tx hanging, tx will go through

**Screenshots**
When Chrome has been open for a while:
![screen recording 2018-12-09 at 06 55 am](https://user-images.githubusercontent.com/513929/49698373-f71b9b00-fb7f-11e8-94ee-8301dc077f91.gif)

When Chrome has recent been restarted:
![screen recording 2018-12-09 at 06 56 am](https://user-images.githubusercontent.com/513929/49698375-f97df500-fb7f-11e8-8f13-461e66fa685a.gif)

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows] OS X
 - Browser [e.g. chrome, safari] Chrome
 - MetaMask Version [e.g. 5.0.2] 5.1.0

**Additional context**
I <3 🦊

**Comment by danjm** [comment]
I can recreate this by by turning off my wifi, turning it back on and then trying to send a tx.

**Comment by bdresser** [comment]
Relates to https://github.com/MetaMask/metamask-extension/issues/5784

**Comment by bdresser** [comment]
I can no longer reproduce this on 6.2.1 - closing, holler if you experience this or something similar @owocki !
