### ISSUE TITLE
More complete documentation for Network Controller, block tracker and their dependencies

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#5899]
The network-controller and block tracker are some of the most essential and pieces of MetaMask core. They rely on dependencies that allow for a json-rpc-engine provider, as well as various middlewares.

Finding bugs or making appropriate improvements can be challenging for uninitiated developers.

We should thoroughly document how all the pieces fit together, the cases in which various middlewares are used, the edge cases that particular lines of code are meant to handle, and whatever else we might need to make work on this part of the codebase accessible and resilient against bugs.

**Comment by Gudahtt** [comment]
This will be mostly supplanted by the TypeScript migration, and the migration of core controllers to `@metamask/controllers`. As such, I'm not sure this issue is useful anymore, so I'll close it for now.
