### ISSUE TITLE
document differences between web3 0.2x.x vs 1.0.0 

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#5901]

**Comment by Levino** [comment]
I do not understand this issue in context of MetaMask.

**Comment by bdresser** [comment]
We support much (if not all) of web3 1.00 – would be ideal to document exactly what portion of it we support, what's still unsupported, and what different behavior folks might expect from each.

**Comment by Levino** [comment]
I do understand the question now: One can use the injected `Provider` instance of `Web3` in version `0.2x.x` or `1.x`. The question is: Does it work with both versions of `Web3` and if so are there any differences?

**Comment by Gudahtt** [comment]
We will be removing our injected `web3` instance very shortly, and we are no longer interested in making special accommodation for documenting the various strange and buggy behaviours of older `web3` versions. So I'll close this for now.
