### ISSUE TITLE
"Max" token Amount calculation ignores decimals after account change

### ISSUE THREAD

**Issue by beyondlogical** [MetaMask/metamask-extension#5906]
When sending tokens and using the "max" calculation feature, the number produced is initially correct. However, after changing the account, the calculation no longer seems to account for the decimal places of the token.

**To Reproduce**
1. Open Metamask
2. Open a token you have previously added to Metamask with a balance
3. Click the Send button
4. Click the "Max" anchor below Amount and see the amount properly calculated
5. Delete the amount and click anywhere outside the field to return Amount to 0 and see the "Max" anchor re-appear
5. Select a different account from the dropdown, selecting one that also has some of the same token
6. Click "Max" anchor again and see the amount improperly calculated, apparently not applying the decimal places. 

**Expected behavior**
Appears to be missing the application of the decimal places.
E.g. It calculates 10000000000000000000 instead of 10 for an 18 decimal token. Tested with 0xf9f8587544471dcf00a48b0d4231ce7ca9b03487 on rinkeby: https://rinkeby.etherscan.io/address/0xf9f8587544471dcf00a48b0d4231ce7ca9b03487

**Browser details (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser: Firefox
 - MetaMask Version: 5.0.3

**Comment by chikeichan** [comment]
seems like this is fixed already - moving to QA to verify
