### ISSUE TITLE
[Feature] Add EOS Support

### ISSUE THREAD

**Issue by asddsaz** [MetaMask/metamask-extension#5911]
**Feature**: Support EOS tokens and contracts.
**EOS**: https://eos.io/
**Why**? Although, ETH IMHO will always be a stronger network, we do have scalability issues. Many that EOS fixes. There are already many EOS-based games like [CryptoWizards](https://wizards.one/) and [MonsterEOS](https://monstereos.io/).
___________________
Want to back this issue? Post a [bounty on it](https://www.bountysource.com/issues/67374449-feature-add-eos-support)! We accept bounties via [Bountysource](http://www.bountysource.com/).

**Comment by tmashuang** [comment]
You can push feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests.
