### ISSUE TITLE
[Feature] Add Nano Wallet

### ISSUE THREAD

**Issue by asddsaz** [MetaMask/metamask-extension#5912]
## **What problem are you trying to solve?**
Nano is a feeless fully decentralized cryptocurrency.
**Great Video**: https://invidio.us/watch?v=dlRhUwLQWXc
However, it is currently mainly supported by their "in-house" wallet. I am unaware of any web based solutions, harming adoption.

## **Describe the solution you'd like**
I propose adding NANO to the list of supported coins.

## **Additional context**
Nano URL: https://nano.org/
**Note**: NANO is not on Ethereum.
___________________
Want to back this issue? Post a [bounty on it](https://www.bountysource.com/issues/67374756-feature-add-nano-wallet)! We accept bounties via [Bountysource](http://www.bountysource.com/).

**Comment by tmashuang** [comment]
You can push feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests.
