### ISSUE TITLE
[Feature] Backup/Restore local folder from Chrome/Brave

### ISSUE THREAD

**Issue by LF76** [MetaMask/metamask-extension#5913]
Playing around with Metamask, it seems this method would work to backup or export the account & settings to another computer. I tested with mine, but can't guarantee it would work in other systems. I'm using the Brave Browser on Win7-32 bits, I think it would work on Chrome too. 

If it would work as expected, could Metamask add an option to export/import this zipped folder? It would be very convenient, at least to save all the time, to import all tokens and settings again.

Also, with the due security measures, it could be sent to a cloud. Maybe encrypted inside Metamask before sending it.

Anyway, here it goes, all the process:

-----------
1-Click on Metamask and on the popup window, click on the 3 dots and 'Expand View'. It will open a new tab with this page (possibly, the url may change eventually): 
`chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html`

2- Now open a file manager or Window Explorer and go to `c:\Users\Your Username\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Local Extension Settings`

In that folder, copy the folder `nkbihfbeogaeaoehlefnkodbefgpgknn`. It's the same name as in the URL we saw in the previous step. Backup this folder and copy it into a flashdrive.

3- In your other PC, install the same browser and Metamask. Close the browser and look for the same folder as in the step 2, the `nkbihfbeogaeaoehlefnkodbefgpgknn`. Now plug in your flashdrive and overwrite the folder in this PC with the content from the flashdrive.

4- Open the browser again, and check Metamask. It should ask for the same password from the older PC, and it will open with all accounts and tokens from the backup.

Hope it works. I hope also it can work with other browsers mixed (Chrome/Brave) and diff. systems (Linux/Mac/Win)

**Comment by bdresser** [comment]
Relates to #1459

**Comment by LF76** [comment]
Just to complement, the strategy works if you move the folder from Windows to Ubuntu. In Uuntu the folder is located at `~/.config/BraveSoftware/Brave-Browser/Default/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn`

**Comment by leafcutterant** [comment]
This would be sorely needed, would be helpful in [situations lie this](https://github.com/MetaMask/metamask-extension/issues/2340#issuecomment-552023609).

Since you closed the other relevant issue (#2340) without explanation, could you at least tell where Metamask stores its data within the Firefox profile folder? @bdresser please?

**Comment by rekmarks** [comment]
For the benefit of anyone looking at this issue:

We have not recently discussed backup and restore for local user data, but you can extract your persisted user data following the instructions in this support article: https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-

**Comment by leafcutterant** [comment]
@rekmarks Are you sure that is the article you wanted to link? It describes state logs.

**Comment by rekmarks** [comment]
@leafcutterant, yeah, that was my intention. If there's any data you want to extract from your MetaMask instance, for any reason, you can grab the state logs. Although it's not a substitute for a backup/restore feature, it may be helpful to someone reading this issue until we are able to ship that feature.

**Comment by leafcutterant** [comment]
@rekmarks okay, I see now. Though why can't the user copy a set of folders and files, and paste it in the right location to restore a Metamask vault?

**Comment by rekmarks** [comment]
I've never tried it, but that could very well work!

**Comment by leafcutterant** [comment]
Well I tried it a few times and it didn't work, but it could be because I copied the wrong files and folders. Thus [my question above](https://github.com/MetaMask/metamask-extension/issues/5913#issuecomment-597130832). I hoped that Bobby, you or someone on the team knows where the data is actually located. It shouldn't be hard, but so far I failed to pinpoint it.

**Comment by tmashuang** [comment]
You can push feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests.

**Comment by leafcutterant** [comment]
@tmashuang if you close it, at least push it over yourself. Metamask maintainers rarely ever solve anything users bring up, they just ignore or close the issue. Last time issues were closed because they were too old. Now it's because you jump platforms.

**Comment by rekmarks** [comment]
@leafcutterant, I truly, truly wish we could be more responsive and implement more features requested by our users, but constraints on our time and resources prevent us from doing so.

I'll make sure that this feature request is documented internally. Thank you for speaking up.
