### ISSUE TITLE
Wrong unit in Live Gas Price Preditions

### ISSUE THREAD

**Issue by eloudsa** [MetaMask/metamask-extension#5915]
Hi

I've just installed Metamask 5.2.0.

I noticed that the unit used in the "Live Gas Price Predictions" graph uses $ instead of GWei.

Just a detail but devil is in the details :-)

<img width="324" alt="screenshot 2018-12-12 at 11 46 32" src="https://user-images.githubusercontent.com/300818/49865233-b1bbcf80-fe04-11e8-9494-06ed14f18dc3.png">

**Comment by danjm** [comment]
fixed with https://github.com/MetaMask/metamask-extension/pull/5919
