### ISSUE TITLE
Editing gas price resets gas limit

### ISSUE THREAD

**Issue by hoytech** [MetaMask/metamask-extension#5921]
After a new metamask update I noticed today (Dec 12), editing the gas price of a transaction has a problem when interacting with a dapp.

After clicking on "edit" in the gas fee section and changing from the default using the new "slow"/"fast" etc buttons, I always see this error:

    {"code":-32000,"message":"intrinsic gas too low"}

When I go to the advanced tab in the customize gas window it seems the gas limit has been reset to 21000, ignoring the gasLimit that the dapp tried to set (150000 in my case).

If I don't try to edit the gas price it seems to work.

**Comment by whymarrh** [comment]
What version of MetaMask are you using?

**Comment by hoytech** [comment]
I reproduced it on 5.2.0. It was initially reported by users, not sure what versions they were using.

**Comment by whymarrh** [comment]
Thanks for reporting this. 5.2.1 was released earlier today with a fix for this exact issue—let us know if you can still reproduce this on the latest version.

**Comment by hoytech** [comment]
Yep it seems to be fixed now, thanks!

**Comment by janus** [comment]
I am noticing this issue current ... I access metamask via myEtherWallet .. and when I want to send transaction  error message appears. I have not done any reset
