### ISSUE TITLE
Cancel Transaction modal needs to handle insufficient balance error

### ISSUE THREAD

**Issue by alextsg** [MetaMask/metamask-extension#5927]
It's possible that when a user attempts to cancel a transaction, his balance is insufficient. We should display an error message if this happens.

@cjeria We'll need a design for an error message in the Cancel Transaction modal.

**Comment by danjm** [comment]
What if we just prevent the opening of the transaction modal in this case?

Grey out the Cancel button and then show a tooltip on hover that says "Not enough funds to cancel".
