### ISSUE TITLE
Network Issue

### ISSUE THREAD

**Issue by Nitishkumar3211** [MetaMask/metamask-extension#5928]
**Describe the bug**
Metamask was connected on Private network after that i switched off my pc and Login to metamask again then i am unable to change network.

**To Reproduce**
1. Go to 'Metamask and connect its with local geth or rpc'
2. Restart your pc while its connected with Private Network
3. Now login and try to chnage network like Private to Ropsten Network.
4. Unable to chnage 

**Expected behavior**
There should be option to change network selection

**Screenshots**
![image](https://user-images.githubusercontent.com/38950255/49920869-c1edb080-fed1-11e8-997d-038391d8821b.png)

**Browser details (please complete the following information):**
 - OS: -Ubuntu 16.4.0
 - Browser :- Google chrome
 - MetaMask Version :-Beta

**Comment by bdresser** [comment]
duplicates https://github.com/MetaMask/metamask-extension/issues/5609, fixed in https://github.com/MetaMask/metamask-extension/pull/5893
