### ISSUE TITLE
Make advanced gas controls the default for dev users

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#5931]
Some people complain about the extra click to get to granular gas controls. We could lump this in with a set of features under "advanced" or "Dev mode"

**Comment by cjeria** [comment]
@whymarrh @danfinlay check it out
![image](https://user-images.githubusercontent.com/597770/52231160-5e17b080-28a0-11e9-8b30-9c46fa1cc7af.png)
