### ISSUE TITLE
Chain ID is not reapply on tx signature on a memorized custom network.

### ISSUE THREAD

**Issue by Alban-io** [MetaMask/metamask-extension#5934]
Chain ID is not reapply on tx signature on a memorized custom network.

**To Reproduce**
1. Mainnet network 
  :arrow_right: Custom RPC 
  :arrow_right: New Network `https://auctionity.network` 
  :arrow_right: save
2. Send ETH
  :arrow_right: To: 0x0000000000000000000000000000000000000001
  :arrow_right: Amount: 0
  :arrow_right: Transaction Fee: 0
  :arrow_right: Gas Price (GWEI): 0
  :arrow_right: Hex Data: 0x0
  :arrow_right: Next
  :arrow_right: Confirm
  signed tx = `0xf84d80808301368c80800081a1a0a2b3723cbc0eb0a4e5ca6e42f1020fd37792021c3931f3d9bf929d10bc796bb9a028b0c2c989e93f1480089be0307cff9d03cd7984d4987aa440724c6def147f01`
  **v ECDSA recovery id** = `a1` :heavy_check_mark: 
3. Switch to Mainnet network 
4. Switch to `https://auctionity.network` network _( memorized in dropdown network list)_
5. Send ETH
  :arrow_right: To: 0x0000000000000000000000000000000000000001
  :arrow_right: Amount: 0
  :arrow_right: Transaction Fee: 0
  :arrow_right: Gas Price (GWEI): 0
  :arrow_right: Hex Data: 0x0
  :arrow_right: Next
  :arrow_right: Confirm
  signed tx = `0xf85f8080827b0c945870bef24ae18b2385563ef7e94f4103a3de8fb0800026a05ba413a255eaf736bbdfb4675d1fb93a79b65088836db161652c22ee597f3409a064850dd2610df0f6f3f84c5fb42d498db38012ab4dc34db94c96ffc53d537042`
  **v ECDSA recovery id** = `26` :x:
  
**Browser details:**
 - Ubuntu 18.4
 - Chrome 69
 - MetaMask 5.2.2

**Additional context**
Private network is EIP 155 complian

**Comment by rstormsf** [comment]
I believe it's also related to #5956 

They read lastNetwork from dropdown which is rinkeby and apply their chainId while it should have been a custom rpc network's id.

**Comment by bdresser** [comment]
fixed in https://github.com/MetaMask/metamask-extension/pull/6044
