### ISSUE TITLE
Bad UX failure mode for network errors

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#5937]
hey fam~
im at a hackathon in Osaka, lots of metamask users

in some cases some bug with network connection is causing the "waiting for network" error message to show. In the worst cases this is shown without any accessible network selection mechanism. Its not hidden behind a semitransparent window its just not visible and not clickable. On restart, it shows the loading icon and is clickable (but completely in-obvious that its clickable)

**Comment by whymarrh** [comment]
Refs #3776 and #5609

I think @danjm made this ux better with #5893. Were folks using the latest and greatest? Or is this a different issue?

**Comment by bdresser** [comment]
yep, fixed finally in #5893 but not released yet. Will be out in 5.2.3!
