### ISSUE TITLE
Bug: network selection not updated on network failure (?)

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#5938]
another bug report from the hackathon trenches

some weird situation where the loaded custom network appeared as ropsten
and then also loading the custom network showed an infinite spinner despite no errors front + back including network requests

**Comment by whymarrh** [comment]
Refs #5937

Hmm, this might be caused by #5893? cc @danjm

**Comment by kumavis** [comment]
too old, not enough info
