### ISSUE TITLE
fail mit hdg and int

### ISSUE THREAD

**Issue by Xm3sm9** [MetaMask/metamask-extension#5942]
Hello,

most of my coins I have send to platforms, but with some 'int' and some 'hdg' I have Problems. 
All the time, and I tried it often and also with a higher gas limit, for example 42000, there is a fail. Please can you help me?

Thanks a lot,
Stefanie

**Comment by tmashuang** [comment]
If you have issue with sending transaction, provide those transaction details to support@metamask.io
