### ISSUE TITLE
Wrong sorting of the ShapeShift transactions history

### ISSUE THREAD

**Issue by Astxsilencer** [MetaMask/metamask-extension#5943]
Here is expanded screenshot of the transactions history I made.
How You can see, all ShapeShift’s transactions stay on the top of the list, not by dates/time of it.

Please, fix placement of them or add ability to select in «Options» how to deal with them: show/hide maybe. Thank You!
![2018-12-15 10 50 49](https://user-images.githubusercontent.com/34488447/50112778-2fdb0480-0251-11e9-8ded-ad30f30417fe.png)

**Comment by bdresser** [comment]
@alextsg looks like this was an accidental side effect of grouping by nonce / ordering by highest nonce first (the shapeshift tx don't have a nonce).

**Comment by MicahZoltu** [comment]
Same problem, but it shows ShapeShift transactions for my _other accounts_.  I have multiple accounts created from one seed, and when I switch between them it shows the ShapeShift transaction.  If I go into settings and reset account data it also continues to show this one ShapeShift transaction.  Even if I add an account by private key and switch to a private dev server, it still shows that one ShapeShift transaction!

No matter what I do, I can't get rid of it.

**Comment by MicahZoltu** [comment]
@alextsg Did that PR also fix the issue with ShapeShift transactions never being cleared?

**Comment by alextsg** [comment]
@MicahZoltu No, that requires a bit more work in the backend to better organize ShapeShift transactions. However, they should now be better sorted and should be less prominent in your transactions list.
