### ISSUE TITLE
How to find out loglevel print ?

### ISSUE THREAD

**Issue by liwei00wade** [MetaMask/metamask-extension#5946]
1、 
I enable METAMASK_DEBUG;
wade@wade-work:~/metamask-extension$ export METAMASK_DEBUG=true
wade@wade-work:~/metamask-extension$ echo $METAMASK_DEBUG
true
2、
npm start 
3、import dist/build/chrome to my browser

4、open chrome console; but I can't found out my log.

**Comment by tmashuang** [comment]
The logs are in the extension's developer tools.
