### ISSUE TITLE
Can't import JSON file as extension window closes on file selection

### ISSUE THREAD

**Issue by chrsengel** [MetaMask/metamask-extension#5952]
When trying to import a JSON file the extension window closes when the file selection window opens. When submitting the file via the file explorer window nothing happens. When reopening the metamask window the file selection was not saved so it's impossible to import the file.

**Expected behavior**
I expected the extension window to stay open so that I could commit the action and enter the password to import the account.

**Browser details:**
 - OS: Ubuntu 18.10
 - Browser Brave
 - MetaMask Version: 5.2.2

**Comment by tmashuang** [comment]
Closing as a duplicate https://github.com/MetaMask/metamask-extension/issues/5029#issuecomment-412248105 
https://github.com/MetaMask/metamask-extension/issues/1136
https://github.com/MetaMask/metamask-extension/issues/1536
 
Workaround is so to import the file while expanding the extension to full screen mode. Ellipsis(...) icon > Expand View > Import.

**Comment by NeevJewalkar** [comment]
Im having the same issue, but i cant expand the extension, I'm on mac OS 12 and using Chrome
