### ISSUE TITLE
Date in Activity Log is incorrect

### ISSUE THREAD

**Issue by corymsmith** [MetaMask/metamask-extension#5953]
**Describe the bug**
The date in the Activity Log is always wrong. It always shows 3/16/2014, the time is always correct but the date is not.

**To Reproduce**
1. Send a TX on Ropsten
2. Click on the TX in the History

**Expected behavior**
I expect the date in the History to match the Activity Log

**Screenshots**
![screen shot 2018-12-19 at 8 33 25 pm](https://user-images.githubusercontent.com/7315/50262247-63db3480-03cd-11e9-84f4-178d1fa8e6f2.png)

**Browser details:**
 - OS: OS X
 - Browser: Chrome
 - MetaMask Version: 5.2.2

**Comment by dostu** [comment]
This was fixed in #5932 but a new version is not released yet.

**Comment by corymsmith** [comment]
Perfect thanks!
