### ISSUE TITLE
Exporting a private key for an imported account not always working

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5968]
I got a report via @vor0220 on Twitter, seems related to #4957 and #5390.

## Reproduction steps:

1. Have MetaMask set up with one account.
2. Import a new account via private key.
3. With that newly imported account selected, in the full-screen interface, select "export private key".

## Expected result

Exporting an imported account should show the imported private key.

## Actual result

The private key revealed is related to account 1, not the newly imported account 2.

## Other notes

Issue #5390 suggests this bug may be intermittent, or require some corrupted state.
Issue #4957 shows we have tried to fix this before, but some version of it has persisted. Assigning to Whymarrh because he has worked on this issue recently, so may be freshest on it.

**Comment by whymarrh** [comment]
I'll take a look at this!

**Comment by tmashuang** [comment]
Reproduction on v8.1.3 if anyone else finds themselves here, please open a new issue with your reproduction steps, and or send details and state logs to https://support.metamask.io.
