### ISSUE TITLE
Date of Transaction & WEI is incorrect in the Expanded View

### ISSUE THREAD

**Issue by JakeBelford** [MetaMask/metamask-extension#5974]
![image](https://user-images.githubusercontent.com/40902281/50494464-6f43e680-09f1-11e9-9591-90cc8b6180d0.png)

**Describe the bug**
The **Activity Log** displays incorrect WEI & Date information in the Expanded View.

**To Reproduce**
1. Go to the MetaMask Google Chrome plug-in (v71.0.3578.98)
2. Click on _Expanded View_ under _Account Options_
3. Click on any transaction to view more details

**Comment by tmashuang** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/5932, will be in the next update.
