### ISSUE TITLE
Don't display nonce suggested by dapp

### ISSUE THREAD

**Issue by VieYang** [MetaMask/metamask-extension#5975]
**moderator edit:** since we don't currently allow dapps to suggest a nonce (see #1410) we shouldn't display a suggested nonce to the user, since it won't be the nonce actually used once the transaction is signed.

--

**What problem are you trying to solve?**
The MetaMask auto update my nonce

**Describe the solution you'd like**
I use MyCrypto "interact contracts", when I want to replace an old tx with the specified nonce, all is ok.
And the MetaMask show me the nonce is 21, but when I confirm it, it signed with the nonce 22.

**Additional context**
Sign Transaction with the nonce the MetaMask show

**Comment by bdresser** [comment]
Hi @VieYang - we don't allow users to set the nonce themselves for a variety of reasons. Check out https://github.com/MetaMask/metamask-extension/issues/1410 for a more detailed explanation. 

> And the MetaMask show me the nonce is 21, but when I confirm it, it signed with the nonce 22.

To the second part of your issue: could you share a screenshot where MetaMask shows you you're using nonce 21?

**Comment by bdresser** [comment]
@VieYang thanks, can confirm as you say we're showing the suggested nonce rather than the nonce we calculate & use. Will update the title & description, thanks for reporting.

**Comment by VieYang** [comment]
@bdresser ok
