### ISSUE TITLE
Add Indian rupee to currency list

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#5976]
https://twitter.com/sauravtom/status/1078550668359553024?s=21

**Comment by whymarrh** [comment]
Looks like Infura's API doesn't support INR: https://api.infura.io/v1/ticker/ethinr returns 404

**Comment by whymarrh** [comment]
I can take this, it's simple enough if we're willing to always use the CryptoCompare API

**Comment by whymarrh** [comment]
We could also use CoinGecko here (e.g. https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd,cad)
