### ISSUE TITLE
accountChanged event is triggered even if the eth_requestAccounts is declined by user.

### ISSUE THREAD

**Issue by leonprou** [MetaMask/metamask-extension#5979]
**Describe the bug**
If user didn't enabled the Dapp through `windows.ethereum.enable`, the listener to the event `accountsChanged` does not suppose to trigger.

**To Reproduce**
1. Open a dapp that uses `window.ethereum.on('accountsChanged', func)`
2. log into Metamask if needed (write you password)
3. Decline the connect request
4. Change to other account via metamask
5. Voila you the event listener is triggered with the new account

**Expected behavior**
The event should not be triggered. Reference: [EIP-1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#eth_requestaccounts)

**Browser details (please complete the following information):**
 - MacOS
 - Chrome  71
 - MetaMask Version 5.2.2

**Comment by tmashuang** [comment]
First initial reproduction hasn't triggered the event. Along with your reproduction, I ensured that it was a site that I haven't approved before, or cleared my approved site list.


![1](https://user-images.githubusercontent.com/13376180/50609677-3f7b5f80-0e85-11e9-854c-205729b61ebd.gif)

**Comment by leonprou** [comment]
Tested this in our Dapp: [Video link](https://www.useloom.com/share/b27e3410d9a341dd911a5169aecf955b)
You can see that after I change accounts the account address is appeared in the top of the Top Nav.

See it yourself on our [QA](https://communities-qa.fuse.io)

And this is where I do the listening - https://github.com/ColuLocalNetwork/CLN-community-app/blob/master/client/src/containers/Web3.js#L14.

**Comment by leonprou** [comment]
My bad, wasn't aware of the "privacy mode" in MetaMask settings.
