### ISSUE TITLE
Use inline installation on home page

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#598]
What happened to doing that?
https://developers.google.com/chrome/web-store/docs/inline_installation

**Comment by whymarrh** [comment]
From the link:

> **Important:** As of 06/12/2018, inline installation is deprecated. For more information, read our **[Chromium Blog post](https://blog.chromium.org/2018/06/improving-extension-transparency-for.html)** and **[Migration FAQ](https://developer.chrome.com/extensions/inline_faq)**.

From the migration docs:

> [We] suggest you review your installation flow and [navigate] directly to your item’s Chrome Web Store listing. Doing that now lets you verify it produces the best user experience.

Sounds like we currently do all we can.
