### ISSUE TITLE
[GABA] A few thoughts re Process of Introduction

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-extension#5981]
A few points re GABA introduction (#5806)

* GABA is essentially a tiny component-model
* The term "Controller" should be changed to "Component"
* https://github.com/MetaMask/gaba is far too flat, at minimum, the few core files should be isolated
* revise the "GABA" naming (names/acronyms introduce one more mental indirection)
  * metamask-component

As for the introduction of GABA to mm:

A quite secure process would be:

* decouple "gaba-core" from "gaba-components"
* introduce the core into the mm-extension
  * ideally: works in parallel with the existent functionality
* rewrite existent "controllers" to become "components" (one after another, right within the existent "battle-proofed" mm-extension)
* "Controllers" are old style, "Components" are new style (e.g. Comp or Cmp suffix).

This process is possibly a bit more difficult, but ensures that the live mm source-code can be migrated in incremental steps.

**Comment by bitpshr** [comment]
Thanks for the input, this is helpful insight. We're following many of these guidelines already and will adhere to them closely going forward. Don't hesitate to share if you have any additional thoughts.
