### ISSUE TITLE
Function lookup and ABIV2Encoding 

### ISSUE THREAD

**Issue by dekz** [MetaMask/metamask-extension#5983]
**Describe the bug**

The function signature lookup doesn't properly parse ABIV2Encoded structs. 0x uses structs in function parameters and can be tested out on a testnet. I applaud the effort of trying to decode this for the user to show them relevant information for their interaction with the blockchain.

**To Reproduce**
1. Head over to [0x codesandbox](https://codesandbox.io/s/github/0xproject/0x-codesandbox).
2. Ensure connected to a testnet. Follow the prompts and create an order.
3. Attempt to fill the order 
4. See improperly rendered function signature.

**Expected behavior**
Renders the function signature correctly.

**Screenshots**
<img width="359" alt="screen shot 2018-12-28 at 11 33 28 am" src="https://user-images.githubusercontent.com/27389/50588691-52b71b00-0ed7-11e9-8994-0fe471b29a02.png">

Notice the `FILLORDER(` another open parenthesis in `(address` and there is another hanging parenthesis further on.

<img width="613" alt="screen shot 2019-01-02 at 10 01 46 pm" src="https://user-images.githubusercontent.com/27389/50589266-13d69480-0eda-11e9-8b33-0352886e2a87.png">

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - MetaMask Version [e.g. 5.0.2]

**Additional context**

As an example here are a few more function signatures for test cases:
```
fillOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes)
matchOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),(address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),bytes,bytes)
batchFillOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256[],bytes[])
marketBuyOrders((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],uint256,bytes[])
```

[Current regex](https://github.com/danfinlay/eth-method-registry/blob/master/index.js#L26) appears to be:
```
let name = signature.match(/^.+(?=\()/)[0]
```

Possible regex (from [ethersjs](https://github.com/ethers-io/ethers.js/blob/fefdd51084f79a282a576aa3a8d404c5a9335c11/src.ts/utils/abi-coder.ts#L76)):

```
new RegExp("^([^)(]*)\\((.*)\\)([^)(]*)$");
```

```
> signature
'fillOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes)'
> signature.match(/^.+(?=\()/)[0]
'fillOrder('
> signature.match(new RegExp("^([^)(]*)\\((.*)\\)([^)(]*)$"))
[ 'fillOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes)',
  'fillOrder',
 '(address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes',
  '',
  index: 0,
  input: 'fillOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes)',
  groups: undefined ]
```

**Comment by danjm** [comment]
Note that fixing this requires a pull request against https://github.com/danfinlay/eth-method-registry/ and then a version update in `package.json` of metamask-extension

**Comment by danjm** [comment]
This is addressed with https://github.com/danfinlay/eth-method-registry/pull/6 and https://github.com/MetaMask/metamask-extension/pull/6403
