### ISSUE TITLE
Odd history showing up in account

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#5984]
**Describe the bug**
I have an account on a local chain that I use fairly often, and recently noticed the account history has been replaced with a single suspect entry:

![screenshot](https://user-images.githubusercontent.com/563406/50598894-2a4d0380-0e7a-11e9-874f-f543be71e1e6.png)

The top of the history entry shows "11/19/18 at 15:32, Sent Ether, 0 ETH, failed." The bottom of the entry says "Transaction created with a value of 0 ETH at 15:32 on 3/16/2014."   

It doesn't seem to matter what network I'm connected to, except that if I try to connect to an unreachable network it says "You have no transactions" below a "Connecting to Unknown Network popover" (as shown in Issue #5609). 

It might be odd that the real history is gone, though it is possible that a Reset Account was done so I can't be sure that's actually an issue.  There have been several transactions since 11/19/18 on this account which were not sending ETH, and I don't recall ever trying to send ETH from this account to any other.  This account has a zero balance on the main Ethereum chain, always has, and probably always will.

It's definitely a bug that the two dates for the same transaction disagree with each other.  It also seems odd that the Activity Log shows a date well prior to the genesis block of Ethereum's main chain.  

It seems strange to have a "Sent Ether" transaction for 0 ETH, to have a "Sent Ether" transaction with such a high gas limit, and to have a transaction with such a low gas price, especially dated back then.

I'm not sure how to reliably reproduce this on other machines without my private key. 

**Browser details (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: Chrome 71.0.3578.98 (Official Build) (64-bit)
 - MetaMask Version 5.2.2

**Comment by bdresser** [comment]
Thanks for the writeup @wbt. The date issue is a bug, fixed in https://github.com/MetaMask/metamask-extension/pull/5932 but not yet released. 

The persistent tx sounds like it may be a separate issue though. You're saying it appears at the top of your activity log for this account, regardless of what network you're on? Is this an imported account?

**Comment by wbt** [comment]
The account is imported.  Maybe I use imported accounts a lot, but my general memory is that Metamask shows the same transaction history regardless of network as a general issue, probably one that should be filed separately if it's not an intentional design decision.  
That one odd transaction appears **as the entire history of** the activity log for this account, and I don't know where that transaction came from.

**Comment by tmashuang** [comment]
Possible an issue with the transaction list selector, this has been numerously, and continues, to be updated. If this happens to you, or anyone else that finds themselves here, contact https://support.metamask.io with your state logs.
