### ISSUE TITLE
Ether Balance not visible on metamask

### ISSUE THREAD

**Issue by sunnynjoy** [MetaMask/metamask-extension#5985]
Hi,
I have transferred Ether from Coinbase. Unfortunately, I am not able to view it on my Metamask account, still showing 0$.  Please find below the link of the transaction. Kindly, let me know what's the problem with this transaction and what can I do to view the balance on Metamask?

https://etherscan.io/tx/0xafb65badc03f050af21f132845dc64c539eb77dbad8fc37cf6879a090afc8028

Regards,
Sunny

**Comment by bdresser** [comment]
hey @sunnynjoy, sorry to hear you're having trouble -- please email support@metamask.io and we'll be able to help you there!
