### ISSUE TITLE
[PROJECT] Introduce a "metamask-request" Issue-Tracker

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-extension#5988]
**What problem are you trying to solve?**
Feature- and Enhancement-Request-Issues stay many times within the repo for a long time. This increases the amount of Issues and "masks" the "real" issues (especially bugs).

**Describe the solution you'd like**
* A separate system to track Feature/Enhancement Requests, where users can additionally vote

**Additional context**

Github has a new functionality "transfer Issues". This would allow to create a new repo like "metamask-requests" (Features, Enhancements, possibly Questions, too) etc., and transfer the issues over without much information loss.

The ISSUE_TEMPLATE would point users to the feature-request repo (Features/Enhancements/Unclear Issues).

Voting would happen via a simple "thumb up" (Repo Title like "MetaMask Requests. Ensure that you vote via the Thumbs-Up").

Issues can be transfered back to the metamask-extension repo whenever necessary.

## Example issues

Nearly 200 issues could be moved (Jan 2019), reducing the active issues within the main repo below 400.

https://github.com/MetaMask/metamask-extension/issues?q=is%3Aopen+is%3Aissue+label%3AT01-enhancement

https://github.com/MetaMask/metamask-extension/issues?q=is%3Aopen+is%3Aissue+label%3AT09-featureRequest

**Comment by masool** [comment]
unable to view metamask extention in ubuntu, please provide the resolution for the same.

**Comment by bdresser** [comment]
Thanks for the suggestion @lazaridiscom, we've thought about it but for now are happy keeping things in roughly one place.
