### ISSUE TITLE
Ether is not displaying on Metamask. Contacted support but no reply from them.

### ISSUE THREAD

**Issue by sunnynjoy** [MetaMask/metamask-extension#5998]
Hi,
I transferred Ether to Metamask but it is not showing up in the main Ethereum network. When I click on "view on etherscan" on Metamask, it takes me to the below address. One can see that it's a valid and successful transaction. Emailed support@metamask.io but did not get a reply.

https://etherscan.io/address/0x2fd72bd1a59342f93aeb6f3e01f6bdb8783916e9

**Comment by tmashuang** [comment]
If you viewed the address's transaction list on Etherscan, there is a transaction right after the deposit for the balance.
https://etherscan.io/tx/0xad4a721520c6a6c9b1b71c00a4c50063d99bda9226f24a0bf72c5fda24187644

This is most likely watching for a balance and sending a transaction for the balance to a different account. This address's private key, or mnemonic, has been made public. 

Following the transactions to an account, https://etherscan.io/address/0xf2d00e3080e1d9fd5e47f54188434e24cfe54da2. The comments say that others have used public truffle mnemonic from a tutorial or elsewhere and the account in question is siphoning public addresses. Recommend to create a new vault/seed/mnemonic to continue using MetaMask.

**Comment by tmashuang** [comment]
There is no way to reverse the transaction.

**Comment by sunnynjoy** [comment]
Okay, that's a shame. But I would accept it. Thank you!
