### ISSUE TITLE
Meta Mask not connecting to custom RPC when tried to connect to Block Chain

### ISSUE THREAD

**Issue by srinivaskch** [MetaMask/metamask-extension#6000]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - MetaMask Version [e.g. 5.0.2]

**Additional context**

**Comment by srinivaskch** [comment]
I have tried so many times in installing uninstalling Metamask version, it is connecting to local Ganache - local block chain network through custom RPC. it is working  when i use Rinkeby network or Ropsten.
Can you please help asap. I also reinstalled Chrome and Metamask once again, still no luck

**Comment by bdresser** [comment]
@srinivaskch could you please give us a more detailed set of steps to reproduce the issue you're having?

For the record, to connect to a custom RPC (like Ganache), click the Settings menu (from the round icon in the top-right), scroll down to "New RPC URL" and input the url (e.g. `http://127.0.0.1:7545` for Ganache).

Closing this issue for now, happy to reopen if you provide some more detail!

**Comment by Cryptoshak** [comment]
Need help with something.

I sent ETH erc20 tokens from binance to MetaMask . I should have sent Bep20 as the main ETH network on MetaMask does not accept ERC 20. Support says I need to add a custom network to MetaMask and I’m trying but can’t seem to find a custom RPC and this is as far as I get. My MetaMask doesn't give me the option for the custom RPC to be added. Please advise

**Comment by papacrypt** [comment]
Good news - I think you can recover. 

Add the binance smart chain to your meta mask. 
https://docs.binance.org/smart-chain/wallet/metamask.html

If you don't see your address - select the other option where it has (Ledger Live vs MEW/MyCrypto).
