### ISSUE TITLE
Wrong function type when sending ETH

### ISSUE THREAD

**Issue by estebanmino** [MetaMask/metamask-extension#6002]
**Describe the bug**

When sending an ETH transaction with hex data, Function Type is `CONTRACT INTERACTION` even though I'm not interacting with a contract.

**To Reproduce**

Follow the GIF 

![bugg](https://user-images.githubusercontent.com/12115171/50800388-c7ff6300-12be-11e9-8e3d-977ebe6bdd3e.gif)

**Expected behavior**
Should have the same behavior, regarding Function Type, when sending ETH without hex data.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - MetaMask Version 5.3.0

**Additional context**

**Comment by bdresser** [comment]
If a normal send has hex data attached, it's very tough for us to distinguish it from a contract interaction. @alextsg this has come up before, yes?

**Comment by alextsg** [comment]
@bdresser We can make an external request to check if the recipient is a smart contract address, which is what we're doing in the transactions view. I can make that change here as well.
