### ISSUE TITLE
MetamaskContentscript loses connection Chrome

### ISSUE THREAD

**Issue by aaronbarnardsound** [MetaMask/metamask-extension#6003]
**Describe the bug**

Extension content script loses connection when Chrome restores a session on reopen. This leaves the dapp hanging without being able to interact with the network. A refresh of the page fixes the problem, but a user will think the dapp is borked.

**To Reproduce**

1. Open dapp in Chrome
2. Set Chrome preferences "On startup" to "Continue where you left off"
3. Quit Chrome
4. Start Chrome up again
5. Chrome will reopen with dapp running
6. Inspect console to see warnings

**Expected behavior**

Expect that the extension will reconnect upon launching chrome as it does on Firefox

**Screenshots**

<img width="875" alt="screen shot 2019-01-08 at 9 19 32 am" src="https://user-images.githubusercontent.com/29873495/50836680-c9b14100-1327-11e9-9371-814f836896b6.png">

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
 - MetaMask Version: 5.3.0

**Comment by tmashuang** [comment]
I don't believe this is isolated to just MetaMask but the whole chrome ecosystem.

It comes down to Chrome racing to open all the tabs from the previous session before the contentscripts are loaded from extensions. You can see this when using an Ad blocker and Youtube with your reproduction steps.
