### ISSUE TITLE
Have price estimation fall back to dexes

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6009]
Currently we just hit the balance api then call it a day. To give estimations of increasingly small tokens, it would be cool to check dexes for conversion rates.

I think uniswap would be a good MVP of this. 

It sure would be nice if there were a uniswap exchange on every network we connected to. They could even have the same address:
https://twitter.com/PhABCD/status/1082703455943315456

**Comment by haydenadams** [comment]
@danfinlay I think this is a great idea - let me know if I can help in any way. Uniswap is being efficiently arbitraged, so it acts as a good price oracle. Setting this up should be easy.

For a given token:
```javascript
exchangeAddress = UniswapFactory.getExchange(tokenAddress)

ethBal = web3.eth.getBalance(exchangeAddress)
tokenBal = TokenContract.balanceOf(exchangeAddress)

// ERC20 / ETH rate
rate = tokenBal/ethBal 
```

Then do the same for DAI to get the USD rate of ETH and you're done! To make sure you're always getting a good rate, only do this for tokens with more than 10 ETH in liquidity.

**Comment by PhABC** [comment]
@haydenadams Would you consider deploying UniSwap contracts to the same addresses on different network via `CREATE2` post Constantinople fork?

**Comment by haydenadams** [comment]
Would be awesome. But requires a redeploy of Uniswap - so it would have to be bundled in with other significant upgrades to justify. 

What networks are you thinking of?

**Comment by danfinlay** [comment]
It would be easy to hard-code to point to the current contract for the main chain, but for "the world of coming other chains", would be great to have a fallback address that is deterministic and trustworthy via `create2`.

Other networks include:
- rootstock
- xdai
- poa
- etc

And more are really being created all the time.

**Comment by PhABC** [comment]
@haydenadams A nice compromise would be to not upgrade the mainnet contract, but have all the other "copies" deployed using `CREATE2`. So only `1/N` would be different, or `(N-1) / N` would be the same. That would already be an improvement until `uniswap` V2.

**Comment by haydenadams** [comment]
@danfinlay gotcha, yeah I like the idea. Will look into it! 

@PhABC seems like a reasonable solution

**Comment by danfinlay** [comment]
One concern:

If token price estimation fell back to Uniswap, we would probably want some visual indication of the market depth, otherwise phishers would be sure to prop up their scam coins with tiny collaterals.

Has anyone built a uniswap market depth component yet?

**Comment by haydenadams** [comment]
Uniswap maintains a 50-50 value of ETH and the erc20 token being sold in the relevant exchange contract. Checking the ETH balance is the best way of finding the depth. 

 Finding the MKR depth is as simple as:

```javascript
mkrExchangeAddress = factoryContract.getExchange(mkrAddress)
// Measured in ETH
mkrDepth = web3.eth.getBalance(mkrExchangeAddress)
```

If you want the depth measured relative to DAI, just get the ETH<>DAI exchange rate on Uniswap. That pair has plenty of liquidity ($225k as of today).

**Comment by salimtb** [comment]
fixed

**Comment by PhABC** [comment]
Now that was an old ticket. Don't remember this convo at all!
