### ISSUE TITLE
Ledger Nano: Submitting Transactions from Wrong Address

### ISSUE THREAD

**Issue by AusIV** [MetaMask/metamask-extension#6011]
**Describe the bug**
If you set up a Metamask hardware wallet account with one Ledger Nano S, then connect another Ledger Nano S and attempt to send a transaction from the account on the first, it will sign and send a transaction from the connected Ledger Nano S even though it's a different account.

**To Reproduce**
0. This process requires two Ledger Nano S's, each configured independently. I will refer to these as Ledger 1 and Ledger 2.
1. Connect Ledger 1, unlock it, and navigate to the Ethereum App
2. Click "Connect Hardware Wallet" From the accounts menu
3. Select "Ledger", then "Connect"
4. Select Address 1 and click "Unlock"
5. Disconnect Ledger 1
6. Connect Ledger 2, unlock it, and navigate to the Ethereum App
7. Attempt to send a transaction from the imported ledger account.
8. Confirm the transaction on the Ledger Nano. 
9. The transaction will be signed with Address 1 from Ledger 2 (while metamask shows Address 1 from Ledger 1), and submitted to the blockchain.

**Expected behavior**
If an account is not available on the attached ledger, sending the transaction should fail.

**Browser details (please complete the following information):**
 - OS: Tested on Windows 10, Ubuntu 16.04
 - Browser Chrome
 - MetaMask Version 5.3.0

**Additional context**
In our case, the attempts to send the transaction failed, because Address 1 on Ledger 2 lacked ETH to complete the transaction. We tried this with a couple different configurations, and got consistent results. If that had not been the case, we could have sent ETH / tokens with no indication from Metamask that it was going to come from the wrong account. It strikes me that it should be pretty easy for Metamask to verify that a hardware wallet's signature matches the expected address, and fail if the address does not match.

**Comment by jacobcantele** [comment]
@AusIV could you verify whether this issue was resolved by MetaMask 7.7.7 or higher? We resolved similar issues but haven't yet replicated the specific workflow you're describing here.

**Comment by jennypollack** [comment]
this should be fixed as of https://github.com/MetaMask/metamask-extension/releases/tag/v7.7.7
