### ISSUE TITLE
wrap and unwrap weth

### ISSUE THREAD

**Issue by zyfrank** [MetaMask/metamask-extension#6015]
Is that possible that MetaMask support wrapping and unwrapping WETH directly?  because WETH is  different from other ERC20 token

**Comment by Robbiekruszynski** [comment]
Hi @zyfrank 
Just wanted to let you know we are migrating our feature requests  + community efforts over to our [ZenDesk](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas). Please feel free to add to the discussion! 

Closing this ticket.
