### ISSUE TITLE
Invalid Sender

### ISSUE THREAD

**Issue by rhpk** [MetaMask/metamask-extension#6016]
So, it seems I've incurred in the "invalid sender" issue when connected to my private chain.

So, here are the details:

- geth: 1.8.20-stable-24d727b6 on Ubuntu
- MataMask: 5.3.0
- Chrome: 71.0.3578.98 on macOs

My genesis block for a Clique PoA chain:

```
{
  "config": {
    "chainId": 2627,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "clique": {
      "period": 15,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5c3b3c26",
```

This is the geth command line:

```
geth --datadir node0/ --syncmode 'full' --port 30320 \
--rpccorsdomain="*" --rpc --rpcaddr 'localhost' --rpcport 8500 --rpcapi 'personal,debug,db,eth,net,web3,txpool,miner' \
--bootnodes 'enode://824996499836771e7220010d3d0bc4835acbc81658ca3af88c63913c254eb1f91b3ec2a03d011b4ebb58c46b5098fc4a939cda9111f3dfd97cf27f245e667117@127.0.0.1:30310' \
--networkid 2767 --gasprice '1' --unlock 'd2c5df14aea4781727c5a5b5717f610c9fac1392' --mine
```

When I try to deploy a new contract from the Ethereum's remix instance (https://remix.ethereum.org) I get the "invalid sender" error.

Any clue?

Thanks.

**Comment by thibmeu** [comment]
I had the same problem with my private chain.

I solved it by adding the private chain again along with its chainid.
You can do it this way:
1. Settings
2. New network
3. Click on `Advanced options`
4. Address: `https://address/of/your/chain`
5. ChainID: `2627`
6. Add the network

**Comment by tmashuang** [comment]
@rhpk as @thibmeu mentions, are your adding your ChainId under the CustomRPC network settings?

**Comment by rhpk** [comment]
Thanks a lot for your replies. Sorry, it took me some time to re-run the test but, unfortunately, it still doesn't work. These are the parameters of the network.

![image](https://user-images.githubusercontent.com/117070/51186181-56846d80-18d9-11e9-86cb-443cd679e4e0.png)

I still get the following error:

EthQuery - RPC Error - Error: Error: [ethjs-rpc] rpc error with payload {"id":4335822084459,"jsonrpc":"2.0","params":["0xf86e8085046c7cfe00825208949a9723d4053999a2a96c0f4e7e596b99f57b0b67880de0b6b3a7640000808215c1a01c49c82338b36d5c4a5f16d7d479be085404b6ceed88eb48090dd6d9eda12354a068c03d60ae55c2855228da4c82479c887f22998f83b3de045c27a620725a005e"],"method":"eth_sendRawTransaction"} Error: invalid sender

Notice that checking the balances works flawlessly and I can see that I have 100 Eth in the private chain connecting to the mining nodes.

**Comment by rhpk** [comment]
So, it seems that upgrading to 5.3.1 doesn't solve the issue.

**Comment by EmiyaGm** [comment]
I think you write wrong your chainid,  **2627 yes √**   **2767 wrong ×**

**Comment by jennypollack** [comment]
hey @rhpk was this resolved by using chainId 2627?

**Comment by rhpk** [comment]
As far as I remember, no. I gave up and then, after a while, it worked again.

**Comment by Gudahtt** [comment]
Thanks for the report! Because this issue is quote old, and because the most recent report was that this started working again, I'm going to assume this was fixed at some point. Please open a new issue if you see something like this again.
