### ISSUE TITLE
Feature request: Add optional popup parameter to .enable()

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6022]
**What problem are you trying to solve?**
A dapp has a valuable use case for a read-only user, and offers additional functionality to certain authenticated users.  The dapp should show controls for that additional functionality to certain people who are logged in via MetaMask, without bothering those who aren't.  Authenticated users should only have to click to login *once* instead of on every page.  

**Describe the solution you'd like**
A 'popup' parameter to the `enable()` function that, if `true` (the default), asks the user if they want to grant permission or not [current behavior] and if `false` (`enable(false)`), immediately returns/resolves, authenticating iff the user previously cached permission to do so by a previous call to `enable(true)`. 

If the user has not cached permissions, the effect of `enable(false)` is the same as if the user had clicked "cancel" instead of "connect" after a call to `enable(true)`.

A dapp developer could then tie a call to `enable(true)` to a 'login' button when explicit permission is requested, and use `enable(false)` on pageload to determine whether to display an authenticated-user view or a non-authenticated-user view which omits certain controls and actions that are not available without authentication. 

My (possibly defective) understanding of the options as currently implemented are: 
1. Call `enable()` on every page load.  Authenticated users will see a popup the first time, and have a smooth experience after that, with actions available (requiring confirmation popup for each action) but no further requests to authenticate, until/unless they Clear Privacy Data or log out of MetaMask.  Their experience is smoothest in this case.

1b. Non-authenticated users who don't wish to connect their accounts but instead use the dapp in read-only mode, will see a popup on every pageload asking for either login to MetaMask, or if already logged in, a notification that the dapp "would like to connect to your account" with cancel/connect options.  This will keep popping up with **every** pageload until the user clicks Connect instead of Cancel.  The user might do this just to dismiss the annoyance of the popup, but in doing so grants the dapp access to information that the dapp doesn't actually need in order to do what that user is trying to accomplish.  They might also uninstall MetaMask.  All that user needs is for the annoying popup to go away.  

2. Only call `enable()` when the user clicks a "login" or similarly labeled button.  Read-only users don't get all those annoying popups; they'd only get a popup if they clicked the button.  Their experience is smoothest in this case. 

2b. Authenticated users have to click that button after every page load in order to see their action buttons etc. appear.  This is an interruption in flow for the authenticated users and not good UX, especially compared to the general understanding of traditional logins, where websites remember that you've logged in for the whole session.  Dapps can avoid requiring such users again click on the authentication button by always constraining themselves to Single Page Applications, but that is not always the best architectural choice, and makes certain use cases harder to implement/support. 

3. Authenticated-user actions are shown for everybody, and `enable()` is called after a user clicks on them before the processing of the actual action they are supposed to represent.  Read-only users don't get all those annoying popups, and authenticated users can see the available actions without first having to click a login button on every page.

3b.  Read-only users see lots of what amounts to distracting visual clutter in the form of interface elements they can't use.  For most read-only users, even if they authenticated with _some_ account, they would not be allowed to take those actions.  Only users who are recorded *in the dapp* as having permission to take those actions can actually do so.  For everybody else, you're presenting an unreachable carrot and/or unnecessary frustration. 

Adding a parameter to `enable()` seems like a relatively easy step that would allow good experiences for both the read-only and authenticated users.  It does a better job of protecting the privacy of read-only users in implementation 1, provides a better argument for replacing traditional username+password authentication systems in implementation 2, and supports adherence to basic UI principles in implementation 3. 

If my understanding is defective and there exists a solution for this already, I would request documentation be linked from [here](https://medium.com/metamask/eip-1102-preparing-your-dapp-5027b2c9ed76).

**Comment by wighawag** [comment]
It is possible to use `eth_accounts` to check whether the dapp has already approved the app. 
a) If it returns [] then it is either not enabled or metamask is logged out.
b) if it returns an non-empty array, then the user has already enabled the dapp

for a) you can display a "connect Wallet" button and upon clicking you call enable
This will popup the enable popup
Unfortunately there is a case where metamask will bring 2 popups : when the user previously approved the dapp but logged out of Metamask, the user will be presented with the password popup and then just after that with the enable popup. The latter should not be shown if the user has approved it in the past.

**Comment by danfinlay** [comment]
Since Version 8, we've made it possible to check the current connection status of an application via the `wallet_getPermissions` RPC method, so I believe the goals of this issue have been satisfied.

https://docs.metamask.io/guide/ethereum-provider.html#table-of-contents

**Comment by impguard** [comment]
@danfinlay I don't believe this works when the user is logged out. I currently check for permissions before "auto connecting" the user by requesting permissions. When metamask is logged out, permissions are still provided and so I attempt to connect the user bringing up the popup on page load.

In my opinion, permissions should always be empty if the user is logged out OR a separate command/RPC call is provided to check login status.

Is there another option out there or should I request a feature request?
