### ISSUE TITLE
Promise not resolving on second transaction in sequence

### ISSUE THREAD

**Issue by woeltjen** [MetaMask/metamask-extension#6028]
**Describe the bug**
I have a sequence of two contract calls (one to approve transfer of tokens, one to collect those tokens) which I'd like to present to the user in order. I'm able to display and confirm both; however, the promise associated with the second call never resolves, even though the transaction completes, so the application is unable to handle the results of these calls.

If I wait long enough "Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!" appears on console. Note that this error is incorrect: The transaction has been mined by that point, and I can see that this is the case in MetaMask.

**To Reproduce**

Relevant snippet (simplified):

    const token = new web3.eth.Contract(TOKEN_ABI, TOKEN_ADDRESS);
    await token.methods.approve(PAYMENT_ADDRESS, value).send({ from: wallet });
    console.log("Approve call completed.");
    const payment = new web3.eth.Contract(PAYMENT_ABI, PAYMENT_ADDRESS);
    await payment.methods.collect(wallet, TOKEN_ADDRESS, value).send({ from: wallet });
    console.log("Collect call completed.");

1. Confirm first transaction in MetaMask
2. Wait for status to change to "confirmed" in MetaMask
3. Observe "Approve call completed" on console
4. Confirm second transaction in MetaMask
5. Wait for status to change to "confirmed" in MetaMask
6. Notice that "Collect call completed" is *not* written to console
7. Wait even more
8. See a "Transaction was not mined" error appear on console

**Expected behavior**
Expect `send` to return a Promise which resolves after MetaMask sees that the transaction has been mined.

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - MetaMask Version: 5.3.0

**Additional context**
I recall there being rules enforced by user agents to limit the interaction of extensions with scripts. Could it be the case that initiating the second call from an `await`-sequence/promise-chain gets handled differently because it is not directly initiated by a user action?

If that's the case, it sounds like I want to BatchRequest here (but then I hit #5817)

**Comment by woeltjen** [comment]
Currently using the following workaround:

    const token = new web3.eth.Contract(TOKEN_ABI, TOKEN_ADDRESS);
    await token.methods.approve(PAYMENT_ADDRESS, value).send({ from: wallet });
    console.log("Approve call completed.");
    const payment = new web3.eth.Contract(PAYMENT_ABI, PAYMENT_ADDRESS);
    await new Promise((resolve, reject) => payment.methods
      .collect(wallet, TOKEN_ADDRESS, value)
      .send({ from: wallet })
      .once('transactionHash', resolve)
      .on('error', reject)
    );
    console.log("Collect call completed.");

This happens to work in my use case; the web application can assume the transaction will go through, and we can deal with failures/errors off-line/subsequently.

**Comment by markusait** [comment]
Thanks for the workaround @woeltjen I can confirm this is still an issue as of now.
