### ISSUE TITLE
Options for change language

### ISSUE THREAD

**Issue by tamsamani** [MetaMask/metamask-extension#6031]
**there no option to change language?**
I'am using english language on my laptop and browser, but in my region (North Africa) used French as default instead, so, the extension comes with french language as default and there no option to change language.

**Add Option for change Language or make it followed by Browser primary language**
sometime user need change language but still want use multiple language during browsing, so I think if we add a option for change language of extension is better than try to choose primary user language.
![capture_xmmn998533761](https://user-images.githubusercontent.com/6149387/51295792-8f2b6080-1a19-11e9-9e9c-f24625918a88.PNG)
![capture_xmmn998533762](https://user-images.githubusercontent.com/6149387/51295793-8f2b6080-1a19-11e9-8a03-fff3d71f4380.PNG)

**Comment by bdresser** [comment]
@tamsamani there is an option to change the language in the extension's Settings menu, but the menu isn't reachable from the onboarding flow.

This relates to https://github.com/MetaMask/metamask-extension/issues/5589, which calls for access to the settings menu even when logged out. Perhaps also need access to the settings menu during onboarding, or at least the language portion

**Comment by whymarrh** [comment]
> Add Option for change Language or make it followed by Browser primary language

This should be the case—we default to whatever locale the browser is using and allow users to change the locale after the onboarding:

https://github.com/MetaMask/metamask-extension/blob/1a4203a8c608c1ee9e13d4196f1ee0c6cac6886e/app/scripts/lib/get-first-preferred-lang-code.js#L5-L8

In the situation you're describing, the browser is returning a different language to us than it is set to? What is your browser version and how did you set the language? Maybe there's something we're missing on our end?

**Comment by fsiddiqi** [comment]
@tamsamani I experienced exactly the same situation and found that Metamask defaults to the first language installed in chrome.  I was able to resolve this by moving the desired language to the top in Chrome settings.  I did have to reinstall the extension, but it worked as expected after that.

**Comment by JoshuaPaulBarnard** [comment]
that worked!  Thank you fsiddiqi!

**Comment by mando-dev** [comment]
what you wanna do is:
step 1: open maetamas in a FULL tab. you can do this by cliking on the 3 vertical dots and clicking on the sort of diagonal arrows (this is the symbol to expand).
step 2: once you are in full view, right click and you should have an option for "translate this page to english" 
step 3: now that everythings in english, look for the gear icon somewhere and there you will see that your Metamask had been predefined to be some random foreign language. 
step4: message me if you get stuck : MandoDev.com

**Comment by hikaritenchi** [comment]
> @tamsamani I experienced exactly the same situation and found that Metamask defaults to the first language installed in chrome. I was able to resolve this by moving the desired language to the top in Chrome settings. I did have to reinstall the extension, but it worked as expected after that.

This doesn't work in Chrome 94 on Windows 11 (idk if those details matter) I reinstalled the extension and closed the browser completely, etc.
