### ISSUE TITLE
Street mode

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#6033]
**What problem are you trying to solve?**
The user should be able to retain more of their privacy when using Metamask at public places.

**Describe the solution you'd like**
I propose a switch in the Settings called Street mode (named after the similar option in [Monerujo](https://github.com/m2049r/xmrwallet)). If turned on, it will hide the following:

On the main screen:

* account name
* address
* identicon
* selected token amount
* the amount of value held in the selected token (this is usually fiat)

In the history:

* identicon
* date and time
* transaction value (both in token amount and (fiat) valuation)
* viewing details is disabled

In the token selector:

* account name
* address
* identicon
* token amount for each token
* the amount of value held in each token (this is usually fiat)

On the send screen:

* identicon
* account name
* whole "From" filed (account name, token amount held, value held in token)

On the approval screen:

* identicon
* account name

There's probably a bunch of other items I forgot about, feel free to expand it.

**Comment by Robbiekruszynski** [comment]
Hi @leafcutterant

Thanks for reaching out with the enchantment suggestion! I would love this conversation to be ported over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas)where we are keeping a close eye on feature request tickets. 

I'm going to go ahead and close this ticket here. 

-Robbie

**Comment by leafcutterant** [comment]
If you close my requests, at least port them over yourself. Metamask maintainers rarely ever solve anything users bring up, they just ignore or close the issue. Last time issues were closed because they were too old. Now it's because you jump platforms.
