### ISSUE TITLE
Write a core set of e2e tests with Cypress

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6036]
This depends on successful completion of #6035

The task is to write a core set of e2e tests with the infrastructure implemented in #6035.

Let's focus on these user flows for this task:
- first time flow via a new password (not importing)
- sending a transaction
- logging out and logging in

For each user action, if some change is made in the dom, we should run an assertion against it.

**Comment by danjm** [comment]
Be mindful to mock external api calls (e.g. for gas estimation)

**Comment by Gudahtt** [comment]
We're no longer planning to use Cypress, as it still doesn't support testing extensions.
