### ISSUE TITLE
Migrate all e2e tests to use of Cypress

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6038]
After #6036, we should be ready to rewrite all our e2e tests with Cypress.

Preferably, this task will be completed in multiple PRs, for ease of code review. The assigned developer could consider breaking it into PRs based on types of user flow or interaction:

- [ ] Adding, removing, tracking tokens
- [ ] Sending from in the app (ether, tokens and contracts)
- [ ] Dapp interactions (deploying contracts, calling contract methods, sending tokens). (Note that sending eth via dapp should have been completed in #6034, but may need to be updated here)
- [ ] switching networks
- [ ] Adding, removing, switching accounts
- [ ] speeding up and cancelling transactions
- [ ] Signing messages
- [ ] Changing currency and locale settings
- [ ] "deposit" options, e.g. shapeshift
- [ ] Adding custom networks and basic use of a custom network (this should be a local custom network)
- [ ] Transaction list: correct info rendering and correct behaviour upon interacting 
- [ ] Core flow in pop-up view

While these items are being completed, it will be ideal if the responsible developer can find a clean way to run each in isolation via an npm command with the appropriate flags.

**Comment by rstormsf** [comment]
I'd be curious to learn the diff between cypress and puppeteer
What made you to choose cypress?

**Comment by Gudahtt** [comment]
We're no longer planning to use Cypress, as it still doesn't support testing extensions.
