### ISSUE TITLE
Differentiate between ETH and test ETH

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-extension#6047]
**What problem are you trying to solve?**
Users using testnet often alternate between test and mainnets. ETH shown on test and mainnet right now look exactly the same. This isn't accurate and users have to make extra cognitive effort to make that differentiation themselves to not make errors.

**Describe the solution you'd like**
- Differentiate how test ETH and actual ETH looks visually
- When a user is alternating a lot between testnets and mainnet, add an alert when they are using mainnet to caution them that they'll spend real ETH
- Consider hiding currency translation for test ETH by default. Why keep the option for currency translation at all? For the use-case where a developer wants to simulate how much gas a transaction / call might cost when on mainnet

**Comment by omnat** [comment]
#4254

**Comment by bdresser** [comment]
Relates to https://github.com/MetaMask/metamask-extension/issues/4775

**Comment by bschorchit** [comment]
Fixed with https://github.com/MetaMask/metamask-extension/pull/14454
