### ISSUE TITLE
Metmask breaks and doesnt open 

### ISSUE THREAD

**Issue by 7--** [MetaMask/metamask-extension#6050]
Third time today I have to reinstall and insert my private key. Metamask just stops openeing, and the only way to fix is reinstall. Ubuntu 18.  
![screenshot from 2019-01-21 13-47-49](https://user-images.githubusercontent.com/4725003/51493983-1d3e7880-1d85-11e9-9f1d-8d6a0758dce2.png)

**Comment by 7--** [comment]
why's it need a seed phrase to start. why cant i use private key.

**Comment by bdresser** [comment]
@7-- what browser? If firefox, there's some discussion on [this thread](https://github.com/MetaMask/metamask-extension/issues/4502) of how to resolve.

Any errors in the background extension console when trying to open?

**Comment by 7--** [comment]
thanks. ill try another browser.

**Comment by whymarrh** [comment]
Let us know if you're still running into this on the latest build on the latest version of a browser
