### ISSUE TITLE
Injected Rinkeby provider out of sync (x / ethereum/remix-ide)

### ISSUE THREAD

**Issue by alsco77** [MetaMask/metamask-extension#6053]
**Describe the bug**
Seemingly out of sync or inconsistent Rinkeby connection injected into the Remix IDE via Metamask. Is unable to read values from a deployed smart contract. 

**To Reproduce**
1. Deployed a contract to Rinkeby via truffle, using Infura provider
2. Went to remix to test it out using the Rinkeby provider injected by MetaMask
3. Incorrect (empty) values being returned from the contract (either it is out of sync or is working on a different chain potentially due to fork?)
4. Switched to custom Web3 provider using personal Rinkeby Infura key and it allows me to read the correct values from the contract

**Expected behavior**
Should be able to read default instantiated values from the contract via Remix

**Browser details (please complete the following information):**
 - Ubuntu 18.04
 - Chrome
 - MM 5.3.1

**Additional context**
x/post from [ethereum/remix-ide](https://github.com/ethereum/remix-ide/issues/1675#issue-401279230)

**Comment by alsco77** [comment]
IIRC - I am able to test by deploying directly through Remix however have to work around my ZOS upgradable proxy pattern, so is not ideal. The contract is over the gas limit for Ropsten deployment so unfortunately I can't just switch testnets.

**Comment by tmashuang** [comment]
Close archiving issue. My steps to reproduce this issue we're not exactly the same, didn't have an personal Infura endpoint, but the result of the contract method values came out the same. If this is still an issue, please open a anew issue.
