### ISSUE TITLE
Show sent token amounts in transaction list when ETH is selected 

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6055]
In the transaction list, if ETH is selected in the token sidebar, the sent amount shown next to a token transaction is "0 ETH". This is not useful information and can actually confuse users into thinking that they did not send anything with that transaction when in fact tokens were sent.

To recreate this:
(1) send tokens from MetaMask
(2) send an eth transaction with a non-zero eth amount
(3) Select the "Eth" option in the token sidebar on the home screen of the app
(4) Look at the amount sent info on the right side of the two rows corresponding to the two transactions you just sent

Meanwhile, if you select the token you just sent in the sidebar, the transaction row will correctly display the amount of token sent on the right side of the row.

We should change the behaviour of transactions so that, if they are token transactions, they display the token amount sent, instead of "0 ETH" on the right side of the transaction row.

Relevant screen shots:

![screenshot from 2019-01-22 11-50-59](https://user-images.githubusercontent.com/7499938/51545589-dca23600-1e3c-11e9-83b8-bf1fb12ac816.png)
-
![screenshot from 2019-01-22 11-50-51](https://user-images.githubusercontent.com/7499938/51545590-dca23600-1e3c-11e9-87a3-912a9af84b6a.png)

**Comment by brad-decker** [comment]
Resolved in #8564 , further refinements coming soon.
