### ISSUE TITLE
Signature dialog account dropdown misleading

### ISSUE THREAD

**Issue by ajm13** [MetaMask/metamask-extension#6057]
**Describe the bug**
Requesting a signature using `personal_sign` or `web3.personal.sign` opens a dialog that has a dropdown in the top left corner to change accounts. Selecting a different account does not change which account signs the message; the account provided to `personal_sign` will be the one signing. This is potentially misleading as a user could interpret the dropdown as changing which account will sign the message.

**To Reproduce**
1. Call `web3.personal.sign(<message>, <account A>)`
2. Select `<account B>` in the top left dropdown
3. Click 'sign'
4. Derive public address from signature: `<account A>`

**Expected behavior**
Account dropdown should either not be visible, or not be clickable / changeable

**Browser details**
 - Chrome v71
 - MetaMask v5.3.1

**Comment by tmashuang** [comment]
Thanks for the report. https://github.com/MetaMask/metamask-extension/pull/6024 has already been merged to fix the issue. Will be out in the next release, sometime this week.
