### ISSUE TITLE
Query Account Balances via BalanceChecker

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#6061]
All account balances can be requested in a single call. 

See #6049 for similar details.

getBalance gets called every ~20-40 seconds per number of accounts in the account menu

**Comment by brunobar79** [comment]
@jennypollack  One thing I forgot to mention, that contract is only deployed in mainnet, but since we have the source we could deploy it to all other testnets.

**Comment by bdresser** [comment]
done in https://github.com/MetaMask/metamask-extension/pull/6181
