### ISSUE TITLE
Privacy mode isn't very private.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6065]
**Describe the bug**
With privacy mode enabled, if a dapp calls `window.ethereum.enable()` I am prompted to approve the dapp _with a specific account_.  The dapp can then do `window.ethereum.selectedAddress` to see what my address is.  However, if I switch accounts to one that I have _not_ allowed the dapp to see, the dapp will still see my address with `window.ethereum.selectedAddress` anyway.

**To Reproduce**
1. Clear privacy data in MetaMask
1. Refresh page.
1. Open browser developer console.
1. `window.ethereum.enable()`
1. Notice that the pop-up specifies the currently selected account.
1. Accept the pop-up.
1. Notice that `window.ethereum.selectedAddress` returns the approved account.
1. Switch accounts in MetaMask.
1. Notice that `window.ethereum.selectedAddress` shows the new, not-approved, account.

**Expected behavior**
When I approve a dapp to see one of my accounts, I expect that it will only be able to see that account, not all of them.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - MetaMask Version: 5.3.1

**Additional context**
If this is intended behavior, then the MetaMask enable() pop-up should not specify an account, it should instead be more clear to the user that they are approving access to _all_ accounts, not just the currently selected one.

**Comment by bitpshr** [comment]
Thanks for filing this @MicahZoltu. For now, approval is for general account access, not a specific account. I'll use this issue to track an improvement to the verbiage as an immediate fix.

You're right that approval should ultimately be on a per-account basis. We've talked about this in the provider ring and I believe that's what Mist already does.

**Comment by leafcutterant** [comment]
Thank you for bringing this up, came to say the same. +1.

**Comment by Gudahtt** [comment]
I believe this concern has been addressed with the new permission system introduced in v8.0.0
