### ISSUE TITLE
Faucet broken

### ISSUE THREAD

**Issue by sshelton76** [MetaMask/metamask-extension#6068]
Faucet is down at https://faucet.metamask.io/
I only get...
```
{"error":"[ethjs-rpc] rpc error with payload {\"id\":4730044424265,\"jsonrpc\":\"2.0\",\"params\":[{\"to\":\"0x0530db0e28761c34e54f12636f35d780dee092f8\",\"from\":\"0x81b7e08f65bdf5648606c89998a9cc8164397647\",\"value\":\"0xde0b6b3a7640000\",\"data\":\"0x\"}],\"method\":\"eth_sendTransaction\"} [object Object]"}
```

I'm using Rinkeby testnet, seems the problem is the same on Ropsten though too.

**Comment by sshelton76** [comment]
Correction, a page refresh after switching to Ropsten seems to have fixed the problem for Ropsten.  Doesn't seem to work for Rinkeby though :(

**Comment by sshelton76** [comment]
Yes  I saw it and agreed.
Still getting
```
{"error":"[ethjs-rpc] rpc error with payload {\"id\":5742230967278,\"jsonrpc\":\"2.0\",\"params\":[{\"to\":\"0x0530db0e28761c34e54f12636f35d780dee092f8\",\"from\":\"0x81b7e08f65bdf5648606c89998a9cc8164397647\",\"value\":\"0xde0b6b3a7640000\",\"data\":\"0x\"}],\"method\":\"eth_sendTransaction\"} [object Object]"}
```

**Comment by sshelton76** [comment]
Any word on this?

**Comment by bdresser** [comment]
@sshelton76 what browser are you using? haven't been able to reproduce with Chrome. @tmashuang have you had trouble with the faucet?

**Comment by tmashuang** [comment]
It's working for me as well. Also to note, the https://faucet.metamask.io/ should only be used with Ropsten network.

**Comment by sshelton76** [comment]
Chromium logo
Chromium
Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)


Also does the same thing on Vivaldi

**Comment by tmashuang** [comment]
We link to https://www.rinkeby.io/ for Depositing on Rinkeby. On the side they have a faucet, https://rinkeby.io/#faucet. Also, https://faucet.rinkeby.io/. Both require a social media link to a post of a address. http://etherfaucet.xyz totally doesn't scale, but if you don't want to get your social media involved, you can get 0.01ETH per each request. If any of these are not an option, put your address here and can send some.

**Comment by sshelton76** [comment]
Thank you, I've discovered another rinkeby faucet which doesn't require social media, just an email and a captcha and will dispense 1ETH daily which is more than sufficient for testing.

My point was that there is nothing in your faucet which says Ropsten only, thus it is broken for Rinkeby.  It would be helpful if either you updated it work with Rinkeby or if you threw an error if netId != 3 and direct people to rinkeby.io because otherwise it is totally non-obvious.
