### ISSUE TITLE
Callback and show error for unsupported signing methods via hardware wallet

### ISSUE THREAD

**Issue by AusIV** [MetaMask/metamask-extension#6070]
**Describe the bug**
Using web3.eth.sign on a Hardware account backed by a ledger, I confirm the signature in the metamask UI, but get no confirmation screen on the ledger, and no callback.

If I inspect the Metamask dialog with Chrome's developer tools, I see a message logged `{"message": "Not supported on this device"}`

**To Reproduce**
0. Have a ledger wallet configured with Metamask
1. Go to https://danfinlay.github.io/js-eth-personal-sign-examples/
2. Click the "eth_sign" button
3. Confirm in metamask
4. At this point, I'd expect to confirm on my Ledger, but no confirmation dialog appears. The metamask dialog closes as though it has completed the signature. No callback is made.

**Expected behavior**
Ideally, I'd get the opportunity to confirm and sign with the ledger. If the ledger is not capable of supporting this signing feature, I would at least expect a callback from metamask with the error.

**Browser details (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Chrome
 - MetaMask Version 5.3.1

**Comment by bdresser** [comment]
@AusIV we only support signing via Ledger with `personal_sign`

You're right that we should have a callback and show the user a message as well - this comes up a lot. 

Going to repurpose this issue if that's okay.

**Comment by AusIV** [comment]
By all means. As a side note, it would be convenient if the error could be delivered without showing the user the confirmation box first.

**Comment by dereksilva** [comment]
Do we have an ETA on resolving this? Someone trying to create a BloomID at https://bloom.co encountered it last week. Thanks.

**Comment by bdresser** [comment]
@dereksilva no ETA, but we're aware of this in the backlog. May have an update for you next Monday, thank you for your patience!

We'd happily accept a PR for the error callback, or this would be a great candidate for a bounty if you'd like to post something on Gitcoin.

**Comment by stobiewan** [comment]
I was about to raise a bug for this issue but found this. It means you can't use radar relay with metamask connected to ledger.

**Comment by bdresser** [comment]
@stobiewan to be clear, Trezor and Ledger still don't support signing methods other than `personal_sign`. That means that if Radar Relay is using one of those other methods, this issue won't solve the problem - it will just allow the site to show you an informative error.

**Comment by stobiewan** [comment]
If connecting directly to the ledger it works fine.

**Comment by bdresser** [comment]
This issue is fixed for Trezor in https://github.com/MetaMask/eth-trezor-keyring/pull/16, stilll open for Ledger

**Comment by brunobar79** [comment]
Already fixed on ledger via https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/12 which hopefully goes out in the next release. 

- eth_sign now supported
- other methods like signTypedData receive the corresponding error
