### ISSUE TITLE
signTypedDataV3Button make distinct class for puppeteer selector

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#6073]
![image](https://user-images.githubusercontent.com/9360827/51983878-ad826900-24bb-11e9-9f36-fa4c941d29c1.png)

It would be really awesome if I could have a unique selector for sign button similar to cancel button

**Comment by whymarrh** [comment]
@trowacat fixed this with #6120, cheers

Btw, we don't go out of our way to change classes on you but know that using the classes is brittle 😅
