### ISSUE TITLE
Transactions with Internal Transactions Do Not Fire Listeners

### ISSUE THREAD

**Issue by epiqueras** [MetaMask/metamask-extension#6081]
**Describe the bug**
When sending a transaction, listeners only fire if the transaction only touches 1 contract. I.e. transactions with internal transactions to other contracts never fire listeners in the browser.

```
const send = (txObject, ...args) =>
  txObject
    .send(...args)
    .on('transactionHash', console.log) // Always fires
    .on('confirmation', console.log) // Only fires for single contract TXs
    .on('receipt', console.log) // Only fires for single contract TXs
    .on('error', console.log) // Only fires for single contract TXs
```

**To Reproduce**
Use the code above to send transactions with and without internal transactions.

**Expected behavior**
The listeners to always fire for any transaction.

**Browser details (please complete the following information):**
 - OS: macOS Mojave 10.14.2
 - Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
 - MetaMask Version: 5.3.2

**Additional context**
This was working fine before, it started happening a few weeks ago.

**Comment by tmashuang** [comment]
The linked issue quote 
> It’s actially a web3 issue as you can see they handled it in the last update beta 41. If I remove drizzle, my app works fine. If I update drizzle to 41, drizzle crashes. Though, the update to 41 could be a meta mask issue with drizzle but I doubt it. If I remove drizzle all works just fine.

I'm going to close this, if this is still an issue, please provide your web3 version and steps to easily reproduce this issue.
