### ISSUE TITLE
Allow custom block explorer

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-extension#6083]
**What problem are you trying to solve?**
We're using etherscan.io which only supports mainnet + testnets.
- If etherscan goes down, there's no alternative solution.
- If another chain has its own explorer it can't be used.

**Describe the solution you'd like**
I'd like to add an option to our settings page to allow users to switch to a different block explorer (like ethstats.io) and also allow to enter a custom one.

The scope of this would be to:
- Create a block explorer section under settings
- Add a dropdown to select different block explorers (etherscan.io / ethstats.io / custom )
- If custom, add a new field to enter the base url of the block explorer (for ex. https://myblockexplorer.io)
- Replace all the strings where we are mentioning etherscan (most likely in the language files) and use the value from the settings instead
- Replace all the etherscan links and use the value from the settings instead.

**Additional context**

- Additional block explorers should conform to the same url format that etherscan provides:
  - `https://${hostname}/tx/${transaction_id}`
  - `https://${hostname}/address/${address}`
 
(ethstats.io already does it)

@bdresser  @cjeria  @danfinlay  @omnat  take a look at this and lmk what you guys think.

**Comment by bdresser** [comment]
This would also be useful for devs joining custom RPC networks.

Looks like ethplorer also uses the same format. Rather than implement a whole templating thing, I'd be down to just include a disclaimer that we'll only support custoom block trackers that use the same format.

**Comment by bdresser** [comment]
Relates to https://github.com/MetaMask/metamask-extension/issues/5631

**Comment by tzapu** [comment]
hey guys, for this situation `If etherscan goes down, there's no alternative solution.` , if it's a temporary outage, it would kind of make sense to have actions/buttons for all the setup explorers. 
So as a user, if i click the etherscan button and it doesn't work, i can try the next one and so on.

**Comment by bdresser** [comment]
This feature was added in https://github.com/MetaMask/metamask-extension/pull/6490
