### ISSUE TITLE
Developer Extension

### ISSUE THREAD

**Issue by sirromdev** [MetaMask/metamask-extension#6092]
**What problem are you trying to solve?**
Having to manually configure metamask during development is a time-consuming process, especially when these underlying parameters (rpc_url, network_id, tokens, account_seed, balances, etc) are changing. 

**Describe the solution you'd like**
Enabling a developer to be able to programmatically define the state of the metamask extension through an api would make development of applications much more streamlined. This functionality may exist to some extent but it may want to be it's own extension entirely to delineate between developer and user, with the developer extension having more relaxed security (with the exception of blocking of mainnet).

**Comment by bdresser** [comment]
Relates to https://github.com/MetaMask/metamask-extension/issues/5101
