### ISSUE TITLE
White screen on starting Metamask.

### ISSUE THREAD

**Issue by Sahilthakur7** [MetaMask/metamask-extension#6096]
MetamaskContentscript - lost connection to MetaMask Contentscript Forwarding  contentscript.js:1:404718
MetamaskContentscript - lost connection to MetaMask Inpage  contentscript.js:1:404718
MetamaskContentscript - lost connection to MetaMask Background  contentscript.js:1:404718
MetamaskContentscript - lost connection to MetaMask PingPongStream  contentscript.js:1:404718

Browser -> Problem exists on both Firefox and Chrome,
OS -> Ubuntu 15.10

Uninstalled and re-installed, no progress. Same Problem exists.

**Comment by whymarrh** [comment]
What version of MetaMask are you using? Is this an issue with the latest version?

**Comment by Sahilthakur7** [comment]
It's 5.3.5 on Ubuntu 16.04LTS

**Comment by whymarrh** [comment]
Do you have full error output available? (A stack trace?) Or a screenshot? When does this error occur?

**Comment by deesk** [comment]
even reinstalled still getting white screen in both chrome and brave browser. 
OS: ubuntu 16.04lts 
screenshot: its just a blank white page whenever i try to open MM
A stack trace: where can i find
following error message at console: "Setting up Sentry Remote Error Reporting: SENTRY_DSN_PROD"
Please help.

**Comment by bdresser** [comment]
@deesk what version are you running? 

try killing the process from the Chrome Task Manager and re-enabling the extension?

**Comment by deesk** [comment]
@bdresser didn't work still getting white page. even tried by removing first from Task Mgr then deleting from extensions and reinstalling. any other way??

**Comment by Sahilthakur7** [comment]
The problem still exists even after a week. Same errors in the console and white screen on Metamask . All the lost connection errors in console.

**Comment by deesk** [comment]
I'm thinking to try on windows. have you?

**Comment by Sahilthakur7** [comment]
It works on Windows, but I want it to run on Ubuntu, I'm writing a DApp. How am I supposed to test it without Metamask?

**Comment by bdresser** [comment]
@Sahilthakur7 please email support@metamask.io and they can try to help

**Comment by deesk** [comment]
@Sahilthakur7 ya may be support can help. m writting them... @bdresser tnx.

**Comment by yushih** [comment]
I had the same issue with Chrome v58 and MetaMask 6.0.1 (current chrome extension store release), solved by either way:
1. Downgrade metamask to  4.17.1 (not recommended)
2. Upgrade Chrome v72
Hope this helps.

**Comment by deesk** [comment]
@yushih tnx a lot it helped. somehow chrome don't get auto update in linux ho did some google search and worked. tnx a lot...cheers. 
How to update Google chrome in Ubuntu? https://superuser.com/questions/130260/how-to-update-google-chrome-in-ubuntu

**Comment by leafcutterant** [comment]
So what was the cause of the blank screen? Did anyone find that out?
