### ISSUE TITLE
Wallet Shows 0 Balance

### ISSUE THREAD

**Issue by dangell7** [MetaMask/metamask-extension#6098]
**Describe the bug**
My Meta Mask Extension is showing a balance of 0. Etherscan shows 5 ether. (Ropsten)
0x7E3716Fba86132361C0980335Eb5380442b11B1E

**To Reproduce**
Not really sure how to reproduce this... 

**Expected behavior**
Ability to spend send receive ether in the wallet was what I expected. 

**Screenshots**
It shows 0

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - MetaMask Version 5.3.4

**Additional context**

**Comment by bdresser** [comment]
@dangell7 please email support@metamask.io and we'll be able to help you there!

If this is indeed a bug, we can re-open the issue.

As a first step - double check you're on the same network & account as the one you're viewing on Etherscan!
