### ISSUE TITLE
"WEB3 API REQUEST" can't be passed

### ISSUE THREAD

**Issue by alexanderm39** [MetaMask/metamask-extension#6100]
**Describe the bug**
The request hangs somewhere inside MM and blocks all further requests after that.
Nothing happens when I click "accept", "reject" or arrow button.
I tried to restart browser and to reboot OS. That does not help.

**To Reproduce**
Open a page with "await window.ethereum.enable();" statement.

**Expected behavior**
Request either accepted or rejected by clicking corresponding button

**Screenshots**
![image](https://user-images.githubusercontent.com/38374375/52176919-e0ce3c00-27ca-11e9-95dc-2d00649fac2c.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - MetaMask Version 5.3.4

**Additional context**
I can easily reproduce that. Is there a way to investigate the issue, please?

**Comment by whymarrh** [comment]
Similar to #6107

A fix for this went out in 5.3.5, released yesterday. Sorry about this!
