### ISSUE TITLE
Change how NFTs show up in transfers

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-extension#6104]
Right now Metamask display NFT transfers using '{{tokenId}} {{NFT Symbol}}'. I think it makes more sense to reverse it and use the name because right now if you're sending a cryptokitty with id of 0 it shows up as '0 CK' or whatever their symbol is. A better way would be '{{NFT name}} #{{tokenId}}' so it would show up as 'CryptoKitty #0'

**Comment by aakilfernandes** [comment]
In general, symbols don't really make sense for NFTs since unlike ERC20s, no one looks at them on coinmarketcap

**Comment by bdresser** [comment]
closing in favor of https://github.com/MetaMask/metamask-extension/issues/5230
