### ISSUE TITLE
Metamask enable doesnt resolve promise (Old UI)

### ISSUE THREAD

**Issue by jurosh** [MetaMask/metamask-extension#6107]
**Describe the bug**
`enable()` doesn't work with "old metamask UI" - which users still can use even with latest Metamask.

**To Reproduce**
1. Go to website with metamask enabled.
2. Call in console `window.ethereum.enable().then(() => console.log('DONE'))`
3. See and approve popup (screenshot)
4. See promise not resolved and no output of "DONE"

**Expected behavior**
Promise should resolve if user approved.

**Screenshots**
![image](https://user-images.githubusercontent.com/1630137/52207271-3c590200-287d-11e9-9342-56ad70b034a2.png)

**Environment**
 - Browser Chrome
 - MetaMask Version 5.3.4 (Old UI Only)

**Comment by jurosh** [comment]
I believe that there might be right time to CUT old metamask UI as new one looks to be stable and very well adopted.

So there might be no need to deal with this bug then :smirk:

**Comment by whymarrh** [comment]
This bug will be fixed in a patch release (sorry!) but also, yes, the new UI is going to be the only UI very soon.

**Comment by whymarrh** [comment]
[This fix went out in 5.3.5](https://github.com/MetaMask/metamask-extension/releases/tag/v5.3.5).
