### ISSUE TITLE
Unable to Send Transaction when selecting Tx Fee rates in MetaMask on v6

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#6118]
Repro Steps: 

1. Be on any network with 2 created accounts with a balance
2. Send Button 
3. Set Recipient Address to Account 2
4. Set Amount to 1 ETH (or any amount that is sufficient)
5. Set Slow or Fast Transaction Fee.
6. Insufficient Funds error on Amount. 

Additional Context

In my `send` state, I believe it shows the correct amounts for gasPrice/Amount, but when I select Advanced Options it shows me 1000000000 GWEI.

Edit: No, the gas price is definitely not correct conversion to 1000000000 GWEI. Seems like we changed how to converted the Slow/Fast Tx Fee tabs to number, or vise versa.

**Comment by bdresser** [comment]
@tmashuang perhaps from https://github.com/MetaMask/metamask-extension/pull/6090 ?

**Comment by whymarrh** [comment]
I can confirm that this isn't because of #6090 or #6091
