### ISSUE TITLE
Attempting to sign messages in ledger through metamask gives no response for certain message strings

### ISSUE THREAD

**Issue by cloudonshore** [MetaMask/metamask-extension#6123]
**Describe the bug**
There is a bug when trying to sign messages that contain certain characters with ledger connected through metamask. The JSON RPC call on the frontend never resolves. However, it does resolve when:
1. using a normal metamask account (non-hardware wallet)
2. using a ledger without metamask

**To Reproduce**
The following steps should be completed with.
A. A ledger connected directly
B. A normal metamask account
C. A ledger connected through metamask
Steps:
1. Go to https://mycrypto.com/sign-and-verify-message/sign
2. Connect with one of the wallets from the above (A, B, C) options
3. Attempt to sign this message `Uß>YÂ Uè îN?>Nb«®ã[ÍÄÞvÝË_` (this is the ascii representation of a hashed airswap order). (sorry it looks like github can't render these characters, I uploaded them here: https://ipfs.io/ipfs/QmaXBGQxC65Kceo8FQdE72yb4iJjmjXiU6L5rYh6K4GizF)

The signing will be successful with A and B, but with C, there is never any response to the JSON RPC call. 

**Expected behavior**
A clear description of what you expected to happen.

I would expect C to behave exactly the same as A & B. 

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - MetaMask Version [e.g. 5.0.2]

macOS High Sierra
chrome v71
metamask v. 5.3.5

**Additional context**

**Comment by wighawag** [comment]
I have the same issue, 

```
const signature = await web3.eth.personal.sign(message, from)
```

The promise never resolve nor reject

**Comment by brunobar79** [comment]
This is fixed via https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/12
