### ISSUE TITLE
Custom Network pointing at Rinkeby Etherscan.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6127]
**Describe the bug**
When I click on the Etherscan link for a transaction while connected to a custom network (that points at mainnet), I am sent to rinkeby etherscan rather than mainnet etherscan.

**To Reproduce**
1. Add a custom RPC endpoint that points to mainnet.
2. Submit a transaction.
3. Click on the transaction while it is pending to view its details.
4. Click the arrow to view in Etherscan.
5. Notice that you are sent to Rinkeby.

**Expected behavior**
Expected to be sent to mainnet etherscan, since the node is pointing to mainnet network.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - MetaMask Version: 5.3.5

**Comment by bdresser** [comment]
thanks for reporting @MicahZoltu. Another user reported custom networks linking to Mainnet Etherscan as a bug on https://github.com/MetaMask/metamask-extension/issues/5631

I like your suggestion of allowing the user to indicate if their testnet is pointing to Mainnet so the block explorer can be updated correctly. A full solution (discussed on https://github.com/MetaMask/metamask-extension/issues/5790) will involve a Custom RPC form that allows the user to specify any block explorer they'd like. This issue will most likely be taken care of as part of that project.

**Comment by bdresser** [comment]
https://github.com/MetaMask/metamask-extension/pull/6490 adds the ability to specify a block explorer for custom RPC networks. 

If no block explorer is provided, the "view on Etherscan" links will error - leaving https://github.com/MetaMask/metamask-extension/issues/5631 to address this.
