### ISSUE TITLE
Metamask recognises seed but fails to restore ETH and gives different deposit address

### ISSUE THREAD

**Issue by kapfo06** [MetaMask/metamask-extension#6128]
FOR USER QUESTIONS, PLEASE DO NOT OPEN A GITHUB ISSUE - IT WILL NOT BE HANDLED HERE.

INSTEAD, PLEASE EMAIL SUPPORT@METAMASK.IO WITH A DESCRIPTION OF YOUR PROBLEM.

**Comment by bdresser** [comment]
hey @kapfo06, as the issue template says, please reach out to support@metamask.io and we'll help you out there!
