### ISSUE TITLE
Kucoin Shares has wrong symbol

### ISSUE THREAD

**Issue by marcuswin** [MetaMask/metamask-extension#6135]
In MetaMask Kucoin Shares has symbol LIKE, but real symbol is KCS like on Kucoin.

**Comment by whymarrh** [comment]
@marcuswin would you mind opening up a PR against our eth-contract-metadata repo?

https://github.com/MetaMask/eth-contract-metadata/blob/588b2c5/contract-map.json#L873-L879

**Comment by marcuswin** [comment]
Oh, I couldn't find repo with metadata, now I make PR, thank you.
