### ISSUE TITLE
Metamask - web3.eth.personal.unlockAccount : Uncaught (in promise): Error: JsonRpcEngine - response has no error or result for request

### ISSUE THREAD

**Issue by rahulpnsare8** [MetaMask/metamask-extension#6148]
**Describe the bug**
I am calling web3.eth.personal.unlockAccount() method but it giving me error.

**Expected behavior**
The account should get unlocked

**Screenshots**
ERROR Error: Uncaught (in promise): Error: JsonRpcEngine - response has no error or result for request:
{
  "jsonrpc": "2.0",
  "id": 971271824,
  "method": "personal_unlockAccount",
  "params": [
    "0x0fc12a04b180d5432d27d54f3723de2e4231170f",
    "abcd1234",
    300
  ]
}
Error: JsonRpcEngine - response has no error or result for request:
{
  "jsonrpc": "2.0",
  "id": 971271824,
  "method": "personal_unlockAccount",
  "params": [
    "0x0fc12a04b180d5432d27d54f3723de2e4231170f",
    "******",
    300
  ]
}
    at inpage.js:1
    at n (inpage.js:1)
    at o (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at a (inpage.js:1)
    at inpage.js:1
    at resolvePromise (zone.js:831)
    at zone.js:741

**Browser details (please complete the following information):**
 - OS: [ubuntu]
 - Browser [chrome : Version 72.0.3626.81]
 - MetaMask Version [5.3.5]

**Comment by bdresser** [comment]
@rahulpnsare8 check out our [documentation](https://metamask.github.io/metamask-docs/Main_Concepts/Getting_Started#logging-in) on how to access user accounts by calling `ethereum.enable()`
