### ISSUE TITLE
ui.js not found

### ISSUE THREAD

**Issue by deltachase** [MetaMask/metamask-extension#6149]
Whenever I open the MetaMask icon or the home.html page opens up, it throws this error in the console and the pages stay blank.

![Imgur](https://i.imgur.com/5XnZzDt.png)
**Browser details:**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - MetaMask Version: 5.3.5 and 6.0.1

I also tried it on Edge and Firefox but it still doesn't work.

**Comment by bdresser** [comment]
are you still seeing this on v6.2.2 ?
