### ISSUE TITLE
Unable to increase gas fee after timeout on ledger

### ISSUE THREAD

**Issue by JacksonOBrian** [MetaMask/metamask-extension#6152]
Hi there,

Currently ran into an issue where when running on Kyber I had entered a 1 Gwei 400,000 gas limit transaction (contract) on metamask when going to do an exchange. I went to increase to a bit more gwei and forgot to sign on the ledger. The option to speed up is gone forever now and is stuck pending as it is in metamask as "failed" and can no longer send any more transactions until position 32 is cleared. Is there any way to try and resend with a higher gas fee?

Transaction hash is: 0xde9a91ffe32f283205fb10a94012df361108568b8c5cc3187b06d5b6a039f26b 

![image](https://user-images.githubusercontent.com/47289730/52753020-b0e91a80-2fba-11e9-86fa-775e210fb5f4.png)
![image](https://user-images.githubusercontent.com/47289730/52753035-be9ea000-2fba-11e9-96d2-9b5763fda1b8.png)

**Comment by tmashuang** [comment]
Looks like it cleared up. Any other issues?

**Comment by tbenr** [comment]
@tmashuang i'm in the same situation.. is there a way to reset the metamask transaction status to be able to redo speedup?

**Comment by tbenr** [comment]
@tmashuang I'm using ledger nano s and i generated an U2F_TIMEOUT error cose i didn't unlock\signed in time.
