### ISSUE TITLE
Allow loading of ganache, background and redux states on e2e test runs

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6154]
We need to create infrastructure and tooling that allows us to run our e2e tests from an existing state.

`ganache-cli`s `--db` option allows us to save and load the blockchain in a given state

We currently have a way to set redux state in our integration (not e2e) tests. We can reuse that approach if necessary, but if there is a programmatic approach, that would be preffered.

We need a solution for the background that allows us to dynamically load state during test runs. We may need to add a way to specify a storage key for use when initializing the background, and a way to load data from json into browser storage at that key. Alternatively, perhaps an api can be added just for usage with tests?

Along with those solutions, we will need to determine a schema for state files and a way to consume it within our e2e tests that interacts with the above three storage loading solutions.

Once this task is complete, our e2e tests will be able to start the app at a state given in json file (plus the ganache db file) and run tests from there.

**Comment by whymarrh** [comment]
Implemented in #6215
