### ISSUE TITLE
Create one-click onboarding button/link

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6161]
## Problem:

Sites hate directing users to MetaMask, because it's a pain to:

1. visit our site
2. install an extension
3. go through onboarding
4. get back to the site.

We now have [a pretty button](https://github.com/MetaMask/React-MetaMask-Login-Button) (thanks @Sneh1999!) that sites can use to detect metamask (or lack of it), and easily link to the appropriate install page, which allows skipping step 1, but it does not offer a skip for step 4.

## Proposed Solution

We could have a special kind of onboarding button that allows a site to "onboard with metamask and link back" to the site.

## Design challenges

We would need to answer questions about exactly where in the onboarding flow we link back to the requesting site.

Should the forwarding site (only visible briefly) have any visual content, or just leave it blank, as it should just flicker open before opening a store page?

## Architectural considerations

The invite link could direct to a simple relay page, like [fwd.metamask.io](http://fwd.metamask.io/) (currently directing to [Forwarder](https://github.com/MetaMask/forwarder)). That page could record the site that linked to it, or the site could even include a query param `?link=backTo.mysite.com`, which could be used by MetaMask to open the requested site after onboarding is complete.

**Comment by bdresser** [comment]
So rough user flow is
1) user visits dapp
2) user clicks "install MetaMask" button
3) user hits new redirect page quickly, then hits browser store
4) user installs MetaMask
5) user completes MetaMask onboarding
6) MetaMask redirects back to dapp

I think we could use a simple page for (3) with a fox head and "redirecting..." or something.

Might also need a screen in (6) to show at the end of onboarding, like "Welcome to MetaMask! You're all set – we're sending you back to your dapp now."

**Comment by danfinlay** [comment]
That's right.

Re: that last point: We could even say "Would you like to go back to _________?", make it fully explicit.

**Comment by bdresser** [comment]
Designs nearly sorted in https://github.com/MetaMask/Design/issues/78
