### ISSUE TITLE
wrong contract address is used in testnet

### ISSUE THREAD

**Issue by anubnair** [MetaMask/metamask-extension#6167]
The contract address for TUSD is 0x0000000000085d4780B73119b644AE5ecd22b376(I have seen metamask is using the same address -> https://github.com/MetaMask/eth-contract-metadata/blob/master/contract-map.json) But this contract address is not available in testnet account. Should we keep two contract map? If not, how to load TUSD in rinkeby network with my existing eth balance?

**Comment by bdresser** [comment]
TUSD tokens on Mainnet are not also on Rinkeby. If you have a token on a testnet, that token will have a different contract address.

Again, these questions are better for support@metamask.io than Github - we try to keep this to bug reports or feature requests!
