### ISSUE TITLE
Unable to send token

### ISSUE THREAD

**Issue by anubnair** [MetaMask/metamask-extension#6168]
I am trying to send TUSD token and it is showing me that 'insufficient TUSD', even though I have enough ETH. I am unable to change to beta. Any specific version is available with the feature of sending token?

**Comment by bdresser** [comment]
@anubnair do you have enough TUSD token to send? If the token is not auto-detected, you can add the token following [these steps](https://metamask.zendesk.com/hc/en-us/articles/360015489031-Adding-and-Managing-Tokens-ERC20-In-The-New-UI).

Please email support@metamask.io with further questions
