### ISSUE TITLE
ERC721 and costs

### ISSUE THREAD

**Issue by zillerium** [MetaMask/metamask-extension#6174]
**Describe the bug**
A ERC721 token is assigned to a wallet address using MM. Then when a transfer is done, the cost displayed is distorted by the token number.

**To Reproduce**
1.Assign a tokenid.
2. Transfer a tokenid.

**Expected behavior**
The cost should be be affected by the tokenid value.

**Screenshots**
 https://ethereum.stackexchange.com/questions/67125/erc721-how-is-gas-worked-out-with-tokenid/67136#67136

**Comment by bdresser** [comment]
This will be handled in #5230
