### ISSUE TITLE
UX: Add explainer/justification field to SignedTypedData_v3

### ISSUE THREAD

**Issue by ryancreatescopy** [MetaMask/metamask-extension#6179]
**What problem are you trying to solve?**
For novice or first-time users interacting with a smart contract, the signature request message can be intimidating and particularly daunting for non-technical folk. It's hard to verify your transaction when you're not sure what you're looking for or what you should be verifying. 

**Describe the solution you'd like**
I think it'd be great to include a field in the data structure that allows dApp teams to write an explanation to the user about what they're seeing and what they should look out for. This could include why they're being asked to sign the message as well as advice on how and what to verify. It's such an alien concept for new-to-web3 users. 

This solution could be shared between MetaMask and the dApp itself setting expectations about verification prior to the signature request step. However I believe having this explainer in MetaMask provides the users the lowest amount of friction as they can read about it and sign it in the same place.

**Additional context**
/

**Comment by iainnash** [comment]
I think it'd be nice to move the verifying contract out of the "View 3rd party details" button and also attempt to display the domain for the action (usually that's a clue as to what it is for).

I've drafted a pr for the first idea here: #22962 22962
