### ISSUE TITLE
signTypedData_v3 generates same signature for same data

### ISSUE THREAD

**Issue by hgedia** [MetaMask/metamask-extension#6180]
As far as i understand ECDSA signatures have a random component ,hence same data signed with the same key twice should yield two different signatures. I was playing around with  'eth_signTypedData_v3' for EIP712 and noticed it always yields the same signature when signing same data. Is this behaviour expected?

Thanks,
Haresh

**Comment by leroldary** [comment]
@hgedia The random component is derived from the private key of the signer and the message (deterministic ECDSA). If the message and the signer are the same the same signature is generated. For details see https://tools.ietf.org/html/rfc6979. So this is expected behaviour.

**Comment by hgedia** [comment]
@leroldary  cheers! Closed!
