### ISSUE TITLE
network controller emits 'loading' state

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#6189]
we should prevent network controller from ever emitting in 'loading' state to prevent downstream checks on network specific logic

currently 'networkDidChange' triggers updates in accountTracker (and probably other places, pending investigation)

we talked briefly about triggering another network change event once it's not 'loading' but i don't think that would solve the issue, because it would just get us into a perpetual networkDidChange loop or lead to checking everywhere downstream that the network state !loading

**Comment by shellyjean300** [comment]
Trying to figure all this out

**Comment by Gudahtt** [comment]
It appears as though `networkDidChange` can no longer emit the `loading` state. This must have been fixed.
