### ISSUE TITLE
Missing close button / toggle

### ISSUE THREAD

**Issue by EddieOne** [MetaMask/metamask-extension#6196]
**What problem are you trying to solve?**
I find myself repeatedly opening metamask on accident because there is no close button and I expect the metamask button to be a toggle.

**Comment by bdresser** [comment]
@EddieOne could you explain further? If you click anywhere except the popup, the extension will close.  If you click the fox head on the browser bar, the extension will also close.

Are you looking for a UI button within the extension that would close the window?

**Comment by EddieOne** [comment]
Hello, I updated and it works as expected now. I was on 5.x. Let's close, if someone find this, they know to update. 😄
