### ISSUE TITLE
"Save" button for gas selection not visible while full screen

### ISSUE THREAD

**Issue by dmihal** [MetaMask/metamask-extension#6197]
**Describe the bug**
While using chrome full screen, the "save" button when editing the gas cost is hidden below the scroll view. I've been opening the gas editor, decreasing my gas price, then clicking the "close" button in the top right, which causes my changes to be reverted.

**To Reproduce**
1. Open chrome full screen (OS X)
2. Create transaction
3. Edit gas

**Expected behavior**
The save button should be clearly visible (there's plenty of screen real estate).

**Screenshots**
![image](https://user-images.githubusercontent.com/1661138/53186906-32ded200-35bf-11e9-9188-b2ca4947379e.png)

**Browser details**
 - Chrome, OS X, Metamask 6.0.1

**Comment by chikeichan** [comment]
<img width="1023" alt="Screen Shot 2019-03-12 at 5 07 18 PM" src="https://user-images.githubusercontent.com/8507735/54244315-54114f00-44e9-11e9-8c92-d0a3cdc49d85.png">

@dmihal just tried and cannot repo the bug (see screenshot above). I did the following:
- open metamask
- click send
- click Advanced Options

I am on Chrome, OSX, MM6.2.0

**Comment by tmashuang** [comment]
Closing due to issue seems to have been fixed on the latest version, please open a new issue if it has not.
