### ISSUE TITLE
Deposit via Coinbase widget no longer works

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6199]
**Describe the bug**
Previously, when clicking "continue to coinbase" under deposit, you would be presented with a Coinbase widget that would let you buy ETH with your account, and then it would auto-send it to the ethereum address of the account you were on, in MetaMask.

example:
https://buy.coinbase.com/?code=9ec56d01-7e81-5017-930c-513daa27bb6a&amount=0&address="users_MetaMask_address_here"&crypto_currency=ETH

Now the buy.coinbase.com widget simply redirects to coinbase.com.

**To Reproduce**
1. Go to MetaMask
2. Click on Deposit
3. Click on "continue to Coinbase"
4. See the redirect

**Expected behavior**
Allow you to easily buy and not have to enter your MetaMask account address.  Better integration.

**Additional context**
Emailed Coinbase support, they may push us to their commerce offering.
https://commerce.coinbase.com/docs/

Also, I think this opens up the conversation to revisit the entire deposit section in general.

**Comment by bdresser** [comment]
For now, let's swap out the dead Coinbase link to point to Wyre: 

>"Buy ETH with Wyre"
>Wyre lets you use aa credit card to deposit ETH right in to your MetaMask account. From the Airswap website, click "Use Fiat" in the top-right corner. You can also use Airswap to get started with ERC 20 tokens!
