### ISSUE TITLE
window.ethereum.disable() to revoke site permission.

### ISSUE THREAD

**Issue by kyriediculous** [MetaMask/metamask-extension#6201]
With metamask privacy settings enabled apps must call window.ethereum.enable() to request access to the user's address as well as inject web3. 

There is no method or functionality in place it seems though for revoking single app access.

The `Clear Privacy Data` Button in settings clearly states `Clear privacy data so all websites must request access to view account information again.`

Similar to uport-connect's` .logout()` method , which removes saved credentials from localstorage (it puts them there on first credential request by an app ) , it would be nice to have such functionality for metamask, which removes the app's permission from the settings requiring the user to have to call `window.ethereum.enable() `again

**Comment by bdresser** [comment]
Just to clarify -- you're looking for a feature in the extension that allow users to clear permissions for a single app (rather than use the `Clear Privacy Data` option in Settings since it clears for all sites) ?

**Comment by kyriediculous** [comment]
For my use case an update to the API would suffice. 

I'm not very familiar with the metamask codebase, but my guess is that the extension uses some sort of local key-value store. Which is why I used the uport analogy. 

How I imagine it being implemented is through a `Forget Me` button on the dApp side. When the button is clicked a method is invoked to remove a specific key or set the value at a specific key to false.

For the broader end-user I think a feature in the extension itself is a nice to have for a future release. An _all or nothing_ approach isn't very flexible. I imagine an implementation similar to web notifications in chrome: chrome://settings/content/notifications
(I'd post a screenshot but its in dutch )

**Comment by whymarrh** [comment]
MetaMask v7.1.0 does add the ability for a _user_ to revoke a site's access and require it to call enable again (#7013). To suggest new methods for the `ethereum` global, it might be best to go through the EIP process, which is outlined in [EIP-1](https://eips.ethereum.org/EIPS/eip-1) or to draft something on [Ethereum Magicians](https://ethereum-magicians.org).
