### ISSUE TITLE
Metamask plugin shows just a white page

### ISSUE THREAD

**Issue by aleenajohn** [MetaMask/metamask-extension#6202]

**Comment by bdresser** [comment]
If Chrome, duplicates #4894. If you're not on Chrome, please re-open with the debugging details outlined in the issue template!

**Comment by donaldwazowski** [comment]
![metamask_blank](https://user-images.githubusercontent.com/32551991/76707372-b5bd5800-66ff-11ea-9411-82d97d7a52a5.png)
Ubuntu/Chrome/Metamask
bkankscreen

It's worked perfect before and now it does not.

**Comment by donaldwazowski** [comment]
look metamusk white window on right uooer part of screenshot.
left one is from this forum (not mine)
