### ISSUE TITLE
logging phantom request that dont actually go to network  

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#6205]
it seems that we are possibly logging some request from the dapp as `eth_accounts` or `net_version` but they never go to network and they dont seem to be valid requests

**Comment by frankiebee** [comment]
possibly a issue with web3

**Comment by Gudahtt** [comment]
I'll close this for now, as I haven't heard of any reports of this in some time, and I can't find any evidence of it occurring. Please let me know if you see this happening again though!
