### ISSUE TITLE
Improvements to Custom RPC form

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6209]
Relates to general work to improve the Settings menu (https://github.com/MetaMask/metamask-extension/issues/5790) but may be tackled separately / afterwards.

The custom RPC form is an important developer feature and we should give it its due!

### Basic Functionality

We can add a top-level "Networks" category on the Settings designs outlined above. The category takes you to a page that lets you
* see a list of all your networks
* add a new custom network
* tap in to an existing network to view and/or edit

for each network, users should be able to set
* RPC URL (required)
* nickname 
* chain ID
* symbol (ETH, ETC, ...)
* block explorer 
* color picker (nice-to-have)

### Other in-scope updates
**Block explorers**
* editable on any network (https://github.com/MetaMask/metamask-extension/issues/6083)
* accepts URLs in the format `* https://${hostname}/tx/${transaction_id}` or `* https://${hostname}/address/${address}`
* rinkeby should default to rinkeby.etherscan.io; ropsten to ropsten.etherscan.io (https://github.com/MetaMask/metamask-extension/issues/6127, https://github.com/MetaMask/metamask-extension/issues/5631)

**Updates to universal network dropdown**
* A fresh install of the extension should show Mainnet, Ropsten, Rinkeby, and "Manage Networks..." which will take the user to this page in settings
* Network names in the top bar should end in ellipses so they don't clip the account image, as described in https://github.com/MetaMask/metamask-extension/issues/6094
* Behavior that persists saved networks and allows removing with the `x` should remain unchanged

**Questions**
* We may allow the option to edit default networks (Mainnet, Ropsten, etc). If we do, probably wise to include aan additional warning / double confirmation and a "return to default settings" button for those networks.
* Would be nice to include a "duplicate network" button somewhere on the index screen
* Would be nice to allow removing custom networks from the index screen
* Should we move the "show/hide fiat conversion on testnets" (https://github.com/MetaMask/metamask-extension/pull/6153) to a per-network setting? (i.e. "Show / hide fiat conversion on *this network* as a checkbox on each network form)

Addresses https://github.com/MetaMask/metamask-extension/issues/5605, https://github.com/MetaMask/metamask-extension/issues/5631, https://github.com/MetaMask/metamask-extension/issues/5381, https://github.com/MetaMask/metamask-extension/issues/6083, https://github.com/MetaMask/metamask-extension/issues/6094

Working Mural is [here](https://app.mural.co/t/consensys3989/m/consensys3989/1551123019824/4ce169cf177495117739c4138dcb16c7e9937177)

**Comment by bdresser** [comment]
with these updates to block explorer, we should consider changing instances of "view on Etherscan" to  
"view on block explorer"

**Comment by danjm** [comment]
@bdresser Where are the finalized designs for this?
