### ISSUE TITLE
Address error with private network / ganache

### ISSUE THREAD

**Issue by tclairet** [MetaMask/metamask-extension#6214]
**Describe the bug**
With a private network or ganache Metamask print an error "No ETH network, set to lowercase" with address with uppercase letter. 

**To Reproduce**
1. Start ganache-cli
```
ganache-cli
```
2. Connect metamask to "Localhost 8545".
3. Try to make a  transaction to an address with uppercase letter for example `0x581e97b7E8B650230F549C0EDCbe7B569Bda16bc`

**Screenshots**
(sorry for french)
![](https://i.imgur.com/o4EOeOK.png)

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: chrome
 - MetaMask: Version 6.1.0

**Additional context**
This was working with previous version of Metamask.

**Comment by tmashuang** [comment]
I believe this [PR](https://github.com/MetaMask/metamask-extension/pull/6001), which prevents checksum addresses on non-ETH blockchains. The issue with ganache-cli is that the networkId is set to the initialized time, which is always changing. The quick options would be to either use Ganache App(which defaults to networkId 5777), or set the networkId via command line `ganache-cli -i "5777"`.

**Comment by tclairet** [comment]
So if my private network has a networkID different than 1, 3, 4, 42 or 5777 Metamask will no longer support checksum address ? Is that definitive or just a collateral issue ?

**Comment by tmashuang** [comment]
It was mostly definitive, I believe for POA, xdai, network that uses non-checksummed address. If more networks implement checksummed address we can look to revert the PR, or just keep adding on to the networkId list as needed.

**Comment by davidmurdoch** [comment]
The issue described in https://github.com/MetaMask/metamask-extension/issues/5838 was that addresses were _displayed_ with an incorrect checksum for the connected network.

Perhaps the fix could just be to set an option in the `Custom RPC` dialog to select whether or not the RPC endpoint should require addresses to be ETH checksum validated or not? Or even just use the whitelist to _display_ imported addresses as checksummed (without requiring user-entered addresses to be lowercase for non-whitelisted network ids).

It'd make for a bad user experience if metamask required that users manually checksummed an all lower-case recipient address before sending, yet metamask now requires that users manually convert already (sometimes valid) checksummed addresses to lower case.

Additionally, metamask currently tells the user that the ganache-cli network they are connected to is not an Eth network, which makes ganache-cli look like it is not a compliant eth network, which is a perception we do not want our users to have.

**Comment by NicolasMassart** [comment]
We have the exact same issue with private Pantheon networks for which only the network id and chain id differ. Otherwise it's Eth network and we were using checksummed addresses just fine before.

**Comment by NicolasMassart** [comment]
I have issues seeing the bug fixed. I have latest 6.2.1 version of the extension and tried it on Firefox and Chrome but I still have the error message on a local RPC network. I tried to remove and reinstall extension but it doesn't change the behaviour. Any ideas why ?

**Comment by NicolasMassart** [comment]
Seems to be fixed with 6.2.2

**Comment by jonathansmirnoff** [comment]
With this https://github.com/MetaMask/metamask-extension/pull/6280 PR the issue #5838 is opened again. @whymarrh and @frankiebee, do you mind tell us the expected solution you want achieve? We are happy to collaborate. You can review the PR https://github.com/MetaMask/metamask-extension/pull/6001
