### ISSUE TITLE
Extra scrollbar when multiple transactions are pending

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6218]
**Describe the bug**
When there are multiple transactions pending user approval, the MetaMask Notification popup interface is just a little too short for the extra elements like the top bar "1 of X requests waiting to be acknowledged" and bottom "Reject X transactions," causing an extra scroll bar to appear on the right.  

**Expected behavior**
The popup is a little taller to accommodate all the display elements and there is no scrollbar needed. 

**Browser details (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - MetaMask Version: 6.1.0

**Comment by tmashuang** [comment]
This seems to be fixed in my reproduction with notifications with multiple transactions. If this is still happening let us know your browser/OS resolution and zoom settings, that might be the cause.
