### ISSUE TITLE
UI fixes to new Onboarding flow

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6222]
Couple tweaks to https://github.com/MetaMask/metamask-extension/pull/6192, apologies for not QA'ing before merge

"Protect Your Seed" step
* I think this step needs to be AFTER the seed backup, before the "Congrats!" step. Otherwise, the user might not know what we're talking about, since the seed hasn't been introduced yet. 
* Can we say "MetaMask will never *spontaneously* ask for your seed phrase"
* Can we make `support@metamask.io` a mailto: link so it's more visible

Other
* Checkbox string on both flows should be "I have read and agree to the Terms of Use" where "Terms of Use" links to [this page](https://metamask.io/terms.html)
* On the New vs Import step, can we re-introduce the helper text from Christian's designs? My mockup was just meant to indicate switching the main options, I think the details in @cjeria's designs can remain. My bad this was not clear. 
<img width="833" alt="screen shot 2019-02-28 at 10 49 15 am" src="https://user-images.githubusercontent.com/1016190/53591340-9aa99580-3b48-11e9-8986-0b9a497b19a8.png">
* Under "Yes, let's get set up!" we can say "This will create a new wallet and seed phrase"
* Under "No, I already have a seed phrase" we can say "Import your existing wallet using a 12 word seed phrase"

I think this screen needs a quick once-over from @cjeria -- at the very least, let's make each phrase below "Tips on storing it safely" into a bullet point with consistent styling

<img width="824" alt="screen shot 2019-02-28 at 10 52 09 am" src="https://user-images.githubusercontent.com/1016190/53591534-199ece00-3b49-11e9-941b-332bd4e3ada2.png">

**Comment by danjm** [comment]
#6171 now has all of these changes except the mailto link on the phishing warning screen

We need to improve the way our translations system works before we can cleanly add that. I may get that in with #6171, or maybe with an additional PR
