### ISSUE TITLE
Exposing user's address without permission

### ISSUE THREAD

**Issue by Alirun** [MetaMask/metamask-extension#6226]
**Describe the bug**
I have question, why inventing ethereum.enable() if ethereum.selectedAddress still returns user's address?

**To Reproduce**
1. Go to any web page with Metamask extension turned on
2. Open developer console
3. Don't call ethereum.enable()
4. Call ethereum.selectedAddress
5. See your public key

**Expected behavior**
ethereum.selectedAddress shouldn't expose your address

**Browser details (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - MetaMask Version 6.1.0

**Comment by bdresser** [comment]
@Alirun have you enabled Privacy Mode in your settings? If Privacy Mode is enabled, `ethereum.selectedAddress` returns undefined until you have called `ethereum.enable()` and the user approves. This is part of a cautious roll-out process to prevent breaking dapps - we'll enable Privacy 
Mode by default in the coming months. 

If you have Privacy Mode enabled and are seeing `.selectedAddress` return, let me know and I'll re-open.
