### ISSUE TITLE
eth-contract-metadata didn't update for more than a month

### ISSUE THREAD

**Issue by guo** [MetaMask/metamask-extension#6227]
It seems https://github.com/MetaMask/eth-contract-metadata has not been updated for more than a month. 
I created a PR to add IOTX 24 days ago. The PR is still not reviewed and updated. 

I appreciate if you can expedite the reviewing process. Thanks!

**Comment by bdresser** [comment]
Thanks for the bump @guo, one of the maintainers has been offline, your PR is reviewed and merged 👍

**Comment by guo** [comment]
Thanks! Keep up the good work!
