### ISSUE TITLE
Improve ui/ directory structure

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6229]
# New Folder Structure
```
— ui
  |—— app
      |—— components
      |—— pages
      |—— ducks
      |—— constants
      |—— store
      |—— css
      |—— helpers
          |—— utils
          |—— higher-order-components
```

# Ducks Folder Structure (Metamask Example)
```
— ducks
  |—— metamask
  |   |—— types.js
  |   |—— actions.js
  |   |—— reducers.js
  |   |—— selectors.js
  |   |—— index.js
  |—— app-state
  |—— confirm-transaction
  |—— send
  |—— gas
  |—— locale-messages
  |—— network-version (seems deprecated)
```

# Sample index.js in Ducks
```js
import metamaskReducer from "./reducers";

export { default as metamaskSelectors } from "./selectors";
export { default as metamaskActions } from "./actions";
export { default as metamaskTypes } from "./types";

export default metamaskReducer;
```

Tasks
- [x] ui/app/keychains/hd has no usage - remove
- [x] move ui/app/img to app/images/
- [x] move all utils in ui/app/* to ui/helpers/utils/*
- [x] move all higher-order-components to ui/helpers/higher-order-components. I18n-provider should be considered a higher-order-components.
- [x] move all react components in ui/app/* to ui/app/components or ui/app/pages
- [x] move ui/app/infra-conversion.json to ui/app/constants
- [x] move ui/app/store.js and ui/app/reducers.js to ui/app/store

Note: the above was prepared by @chikeichan

**Comment by danjm** [comment]
Modals deserves a special place, beyond just under `components/` Either same level as `pages/` or under `pages/` Same could be said of the `app-header/` and app-header menus. Perhaps we need two sorts of component directories: (1) those that are content-ful, require connection to state, but are not explicitly/exclusively children of any page components; (2) those that are not content-ful, therefore not requiring any connection to state, and are not explicitly/exclusively children of any page component

(1) could be in a directory called "app-components" and (2) could be in a directory called "reuseable-components" (or maybe "shared-components")

We should also follow a standard whereby a component that is only used by one other component be included as a sub-directory of its parent, regardless of where its parent is.

Together, these suggest that we can break down our directory structure as:

```
— ui
  |—— app
      |—— reusable-components
        |—— account-dropdown-mini
        |—— alert
        |—— balance
        |—— breadcrumbs
        |—— button
        |—— button-group
        |—— card
        |—— copyButton
        |—— currency-display
        |—— currency-input
        |—— editable-label
        |—— error-message
        |—— eth-balance
        |—— export-text-container
        |—— fiat-value
        |—— hex-to-decimal
        |—— identicon
        |—— jazzicon
        |—— loading-screen
        |—— lock-icon
        |—— mascot
        |—— page-container
        |—— qr-code
        |—— readonly-input
        |—— sender-to-recipient
        |—— spinner
        |—— tabs
        |—— text-field
        |—— token-balance (requires deconnection from container)
        |—— token-currency-display
        |—— token-input (requires deconnection from container)
        |—— tooltip
        |—— tooltip-v2
        |—— unit-input
      |—— app-components
        |—— account-menu
        |—— app-header
          |—— network
        |—— dropdowns
          |—— account-dropdowns
          |—— menu-droppo
          |—— {...current account-dropdowns/*}
        |—— gas-customization
        |—— loading-network-screen
        |—— menu-bar
          |—— selected-account
        |—— modals
          |—— modal
          |—— deposit-ether-modal
            |—— shapeshift-form
          |—— {...current modals/*}
        |—— network-display
        |—— notice
        |—— sidebars
        |—— token-list
          |—— token-cell
        |—— transaction-list
          |—— transaction-action
          |—— shift-list-item
          |—— transaction-activity-log
          |—— transaction-breakdown
          |—— transaction-list-item
          |—— transaction-list-item-details
          |—— transaction-status
          |—— transaction-view
          |—— transaction-view-balance
        |—— ui-migration-accouncement
        |—— wallet-view
          |—— add-token-button
          |—— token-list
      |—— pages
        |—— confirm
        |—— send
          |—— ens-input
        |—— settings
        |—— settings-tab
        |—— provider-approval
        |—— provider-page-container
        |—— signature-request
        |—— {...current pages/*}
      |—— ducks
      |—— constants
      |—— store
      |—— css
      |—— helpers
          |—— utils
          |—— higher-order-components
```

**Comment by chikeichan** [comment]
How about the following?

components
- app
-- modals
- ui
pages
- [...]

**Comment by danjm** [comment]
@chikeichan so `components/app` would contain what I've called `app-components` above? and `components/ui` would contain what I've called `reusable-components`?

That sounds good to me.

**Comment by brad-decker** [comment]
@danjm can this be closed?

**Comment by Gudahtt** [comment]
The reorganization discussed here happened in https://github.com/MetaMask/metamask-extension/pull/6304, so I'll close this now.
