### ISSUE TITLE
Front End Refactors

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6230]
Two large front end codebase goals to pursue:
- Significantly increase the number of value-adding community PRs. Where a 'value-adding community PR' is defined as one that:
  - is bug free
  - saves the MetaMask team time (i.e. takes less time to review and merge than would have been taken if a MetaMask dev had coded and merged it themselves)
- Minimize or even eliminate frontend bugs that are deployed to production

Towards those goals, the codebase should become:
  - easy to read and navigate
    - easy to follow data flows and easy to find data sources
    - easy to find ui features in codebase
    - purpose of any given line/section of code easier to determine
  - easy to add, delete, update code
  - easy to test
  - easy to notice bugs

**Comment by danfinlay** [comment]
Closing as this is old and a bit general to track.
