### ISSUE TITLE
Plan out standardization of structure of component directories

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6232]
All components should have:
- a directory
- an index.js file
- a `.component.js` file

We need some standards regarding the best way to connect components to state.

I think the strongest options are:

1. One connected component per "page": where a "page" is either everything you see when on a given route, or (perhaps) everything inside a modal. All descendants of that component receiving their state from their parent.
2. Every component that requires data from state that it's parent would not otherwise have must itself be connected to state. This could be modified to "it's _grand_parent". If two or more siblings require the same data from state, the parent can get them even if the parent does not need them

We then need to make a decision on whether component directories should have their own `.selectors.js` and/or `.utils.js` files. Or whether these should all be collected in one location (i.e. one selectors directory that contains all selectors for all files. I think arguments can be made for both.

Component directories should have their own `.scss` files, unless all the css they need has been included in a scss file for a component of an older generation.

Finally, there are some distinctions that can be made here between components that will only ever be used on a given page/screen, and those that will be reused.

The task is to get the front end team to consensus on these questions, and then make an exhaustive list of tasks. The list of tasks can be included here. Once complete, we can decide whether to break them into separate githubs tickets.

**Comment by danjm** [comment]
With the suggestions laid out here https://github.com/metamask/metamask-extension/issues/6229 in mind, I believe the following makes sense:

- All `reusable-components` directories can be structured as follows:
```
|—— name
  |—— name.test.js
  |—— name.component.js
  |—— index.js
  |—— name.md
  |—— name.scss
```
- All `app-components` directories will be structured as
```
|—— name
  |—— subcomponent1-name
  |—— subcomponent2-name
  |—— tests
    |—— name.component.test.js
    |—— name.container.test.js
    |—— name.container-helpers.test.js
  |—— name.component.js
  |—— name.container.js
  |—— name.container-helpers.js
  |—— index.js
  |—— name.md
  |—— name.scss
```
Where `*.container-helpers.js` files include any methods used to convert selected data into the form it needs to be in to be rendered. While the ducks selectors will strictly select data from the reducer, these methods can include those needed to sort, filter and map arrays, find data using data selected from multiple reducers, convert data across currencies/number base/denomination, perform arithmetic operations on data, etc Then `*.container.js` files can be kept to just importing and calling methods and passing the results to `mapStateToProps` and not be particularly cluttered with method calls, variable declarations and property selection. This structure can probably also be the structure for directories of page components.

**Comment by danjm** [comment]
Not that `containuer-helpers` could also just be `helpers`. Alternatively, `pipers` because their purpose is piping data.

**Comment by brad-decker** [comment]
This issue is particularly dated and dangerous as it contains details of our structure several iterations old, i'm closing to prevent confusion.
