### ISSUE TITLE
Reduce conversion code duplication and improve conversion utility api

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6233]
For now just linking to https://github.com/MetaMask/metamask-extension/pull/4895#issuecomment-408452748

I think we've started in the right direction with `metamask-extension/ui/app/helpers/conversions.util.js`

We need to fully think through what the API of such a util should be, implement that util, and then replace all cases of conversion with calls to that util.

We might also want to publish this as its own library.

**Comment by kumavis** [comment]
duplicate of #6290
