### ISSUE TITLE
Standardize approach to manipulating data flows between redux store and rendering

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6234]
Key observation is that there are four things we do to data as we move it from the store to being rendered:
- selecting: picking the data we want from state
- operating: currency conversions, mathematical operations, filtering, sorting, combining lists, etc
- formatting: turning data into the exact strings we want to render
- rendering: show the data to the user via react components

Should we do 1-3 in selectors in container components?
Should selectors be one of three types of methods that data gets piped through in container components?
What can we learn from how this is handled in the gas-customization modal?

We need to pick a pattern, document the standards, ticket out all refactors required.

**Comment by Ryan1208** [comment]
ryan.alvar@yahoo.com

**Comment by danjm** [comment]
I believe the best approach to this task is to:

- [ ] start by moving as much logic as possible out of components and into containers, or the containers of parent components. Only when it is unavoidable should logic be in component.js files
- [ ] Once https://github.com/metamask/metamask-extension/issues/6229 is implemented, then we identify all selector type logic that does not easily fit into selector files paired with reducers. These can be placed in the `container-helpers` files described in #6232 
- [ ] Once the above task is complete, we can attempt to reduce code duplication across all files.

**Comment by danjm** [comment]
To dos for "start by moving as much logic as possible out of components and into containers, or the containers of parent components. Only when it is unavoidable should logic be in component.js files"

- [ ] `ui/app/components/account-menu/account-menu.component.js`: move reduce and filter calls, and the data operations in their callbacks to container; `isRemovable; `renderScrollButton`;
- [ ] `ui/app/components/currency-display/currency-display.component.js`: `text`, `title`, `hideTitle`
- [ ] `ui/app/components/dropdowns/account-details-dropdown.js`: `address`, `keyring`, `isRemoveable`
- [ ] `metamask-extension/ui/app/components/gas-customization/advanced-gas-inputs/advanced-gas-inputs.component.js`: gasInputError()
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/loading-network-screen/loading-network-screen.component.js`: getConnectingLabel()
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/modals/account-details-modal.js`: calculation of `keyring` and `exportPrivateKeyFeatureEnabled`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/modals/buy-options-modal.js`: `isTestNetwork` and `networkName`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/modals/deposit-ether-modal.js`: `isTestNetwork` and `networkName`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/modals/export-private-key-modal.js`: `plainKey`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/modals/hide-token-confirmation-modal.js`: `symbol`, `address`, `image`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/modals/new-account-modal.js`: `newAccountNumber`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/modals/notification-modal.js`: `showButtons`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/network-display/network-display.component.js`: `networkClass` and maybe type/nickname
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-add-suggested-token/confirm-add-suggested-token.component.js`: `pendingToken`, map of `pendingTokens`, `getTokenName`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-add-token/confirm-add-token.component.js`: map of `pendingTokens`, `getTokenName`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-deploy-contract/confirm-deploy-contract.component.js`: `origin`, `data`, `data` buffer length
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-send-ether/confirm-send-ether.component.js`: `shouldHideData()`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-token-transaction-base/confirm-token-transaction-base.component.js`: `getFiatTransactionAmount()`, `hexWeiValue`, `tokensText`, `getSecondaryTotalTextOverride()`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-transaction/confirm-transaction.component.js`: `getParamsTransactionId()`, `!totalUnapprovedCount && !send.to`, `!transactionId`, `paramsTransactionId && transactionId && paramsTransactionId !== transactionId + ''`, `!tx`, `setTransactionToConfirm(transactionId)`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-transaction-base/confirm-transaction-base.component.js`: `transactionStatus === DROPPED_STATUS || transactionStatus === CONFIRMED_STATUS`, `getErrorKey`, `JSON.stringify(params, null, 2)`, `ethUtil.toBuffer(data).length}`,  `getNavigateTxData`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/confirm-transaction-switch/confirm-transaction-switch.component.js`: `data`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/create-account/new-account.js`: `newAccountNumber`, 
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/pages/home/home.component.js`: `Object.keys(suggestedTokens).length > 0`, `unconfirmedTransactionsCount > 0`, `(providerRequests && providerRequests.length > 0`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/selected-account/selected-account.component.js`: `checksummedAddress`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/send/send.component.js`: `currentAddress !== scannedAddress`, `getToAddressForGasUpdate(updatedToAddress, currentToAddress)`, `uninitialized`, `amountErrorRequiresUpdate`, `amountErrorObject`, `gasFeeErrorObject`, `network !== 'loading'`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/send/account-list-item/account-list-item.component.js`: `const { name, address, balance } = account || {}`
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/send/send-content/send-hex-data-row/send-hex-data-row.component.js`: `onInput`(?)
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/send/send-content/send-to-row/send-to-row.component.js`: `toWarningObject`, `toErrorObject`,
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/send/send-footer/send-footer.component.js`: `shouldBeDisabled`, `errorField`, `errorMessage`, 
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/transaction-activity-log/transaction-activity-log.component.js`: `prefix`, `status !== CONFIRMED_STATUS`,`ethValue`, `formattedTimestamp`,  `activityText`,
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/transaction-list/transaction-list.component.js`: `pendingTransactions.length > prevPendingTransactions.length`, everything to do with `transactionGroup`s
- [ ] `/home/danjm/kyokan/metamask-extension/ui/app/components/transaction-list-item/transaction-list-item.component.js`: `toAddress` and destructuring
- [ ]

**Comment by Gudahtt** [comment]
I'm not sure we want to do these things anymore. We've been using a new pattern recently that is loosely based upon the [Redux style guide](https://redux.js.org/style-guide/style-guide/). We can make a separate tracking issue for converting to that format once we begin that work in earnest.
