### ISSUE TITLE
Proper description of MetaMetrics on Setting page

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#6236]
<img width="657" alt="screen shot 2019-03-05 at 11 53 15 am" src="https://user-images.githubusercontent.com/13376180/53826222-c6a88a80-3f3d-11e9-820e-5a702fb3818d.png">

**Comment by bdresser** [comment]
In grey, how about something simple like:
>>>
MetaMetrics sends basic UI events to the MetaMask team to help us improve our product. Turning this toggle "off" will disable sending these events. [Learn more](https://medium.com/metamask/metametrics-an-introduction-to-metamasks-new-analytics-system-e9749e74a275)
