### ISSUE TITLE
Incorrect rendering on opt-out for Metametrics

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-extension#6241]
**Describe the bug**
Placeholder is not being replaced by proper text.

**To Reproduce**
1. Go to Settings
2. Scroll down to 'Participate in MetaMetrics'
3. See as the description 
```
Participate in MetaMetrics
[participateInMetaMetricsDescription]
```

**Expected behavior**
The placeholder to be filled.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - MetaMask Version 6.2.0

**Comment by tmashuang** [comment]
Duplicate https://github.com/MetaMask/metamask-extension/issues/6236
Fixed in https://github.com/MetaMask/metamask-extension/pull/6237
