### ISSUE TITLE
MM 6.2.1 sends invalid JSONRPC requests to private network

### ISSUE THREAD

**Issue by hoytech** [MetaMask/metamask-extension#6263]
Metamask 6.2.1 seems to be broken in my dev environment. I'm running parity 2.3.5 with a private network, and it seems to be sending the following request:

    $ curl http://localhost:8545 -H 'Content-Type: application/json' -d '{"method":"net_version","params":[],"beta":true,"id":2790068417}'
    {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":2790068417}

It seems to have replaced `"jsonrpc":"2.0"` with `"beta":true` ?

This shows up in the browser console as:

    MetaMask - RPC Error: Internal JSON-RPC error. 
    {code: -32603, message: "Internal JSON-RPC error."}

**Comment by kumavis** [comment]
we have this for infura but I guess we don't use this for the custom networks
https://github.com/MetaMask/eth-json-rpc-infura/blob/14df65a671ef2eefa02b8766cc4b3e42c3651d79/src/index.js#L134-L142

I'll take a look
