### ISSUE TITLE
Batch transaction creates multiple notifications in v6.2.0

### ISSUE THREAD

**Issue by Pablittos** [MetaMask/metamask-extension#6264]
**Describe the bug**
When executing a batch request using web3, MM displays transactions' confirmation windows for each transaction instead of a single pop-up (tested using batch of 3 and 4 transactions). Each window displays the same information. After confirming all transactions using the top window, it closes, but the other windows stay opened and need to be manually closed. One of them displays an infinite loader, the other - an information about transaction success. Transactions themselves do execute properly.

**To Reproduce**
1. Create a batch request containing multiple transactions using web3's BatchRequest.
2. Execute the request.
2. Notice a new MM popup being opened for each of the transactions.

**Expected behavior**
A single window should appear, in which user can confirm every transaction in the batch. After the user confirmed or rejected the transactions, the window should close (behavior known from version 6.1.0).

**Browser details**
 - OS: Windows 10
 - Browser: Chrome
 - MetaMask Version 6.2.0

**Comment by tmashuang** [comment]
Introduced by #6223. The ultimate goal is to bring the notification in front of windows when sending transactions/signing messages. #6183 was first introduced but the notification was popup when sending a transaction inside the extension, also does multiple notifications with batch txs. #6223 prevents the notification when in the extension. The original snippet https://github.com/MetaMask/metamask-extension/blob/b0a105ce809b8b7e5e4431bd1ddecc523586cad0/app/scripts/background.js#L290 works with batch transactions but doesn't bring the notification to the front.
