### ISSUE TITLE
Tx Pending Approval Disappears if Another tx Confirms

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#6265]
If I am on the Confirm/Reject screen for a transaction when another transaction confirms, the transaction request disappears and becomes inaccessible. I have to refresh the page and submit the tx again.

Version 6.2.1

**Comment by tmashuang** [comment]
Seems to no longer to be an issue. Tested with send transactions, no contract interactions/deployments. If my findings are inaccurate please open a new issue.
