### ISSUE TITLE
Center all popups

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#6269]
**Describe the bug**
Currently, all popups appear on the top left of the screen.

**To Reproduce**
Any transaction that initiates a popup.

**Expected behavior**
Center popups on the screen for easier interaction.

**Screenshots**
Not centered 👎 
<img width="1680" alt="screen shot 2019-03-08 at 2 43 08 pm" src="https://user-images.githubusercontent.com/597770/54045492-869d0e00-41b0-11e9-82a4-cc5e27ef30ac.png">

**Additional context**

Resource with code and demo showing it is possible to center popups http://www.nigraphic.com/blog/java-script/how-open-new-window-popup-center-screen

Gif of user centering popup.
![user centering the pop up screen1](https://user-images.githubusercontent.com/597770/54045864-75083600-41b1-11e9-8d2b-b11179ab0e52.gif)

**Comment by Azier777** [comment]
We need to figure what's up with the node
