### ISSUE TITLE
"reject all" doesnt reject all windows

### ISSUE THREAD

**Issue by ashachaf** [MetaMask/metamask-extension#6273]
**Describe the bug**
when several transactions are waiting my confirmation, i also have the option to "reject all". when clicking this option, not all waiting transactions are rejected.

**To Reproduce**
1. go to bancor.network
2. convert any erc20 to erc20 or eth
3. click "reject all"

**Expected behavior**
all waiting transactions (that are part of the batched transaction) should be rejected

**Browser details (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser chrome
 - MetaMask Version 6.2.1

**Comment by tmashuang** [comment]
There is currently an issue with batch transactions we are working to fix, #6264.
