### ISSUE TITLE
Refactor everything from hyperscript to jsx

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6291]
Lots of hyperscript still in the codebase. We should convert it all to JSX

**Comment by danjm** [comment]
Preferably we add a unit test before each refactor, and then refactor it.

It some cases, instead of refactoring, we can depricate the component in favour of a newer one.

**Comment by whymarrh** [comment]
I'm going to attempt to simply convert components as a first pass.

We have the following usages:

- [ ] `development/mock-dev.js`
- [ ] `development/selector.js`
- [ ] `package.json`
- [ ] `test/unit/responsive/components/dropdown-test.js`
- [ ] `ui/app/components/app/account-panel.js`
- [ ] `ui/app/components/app/bn-as-decimal-input.js`
- [ ] `ui/app/components/app/copyable.js`
- [ ] `ui/app/components/app/customize-gas-modal/gas-modal-card.js`
- [ ] `ui/app/components/app/customize-gas-modal/gas-slider.js`
- [ ] `ui/app/components/app/customize-gas-modal/index.js`
- [ ] `ui/app/components/app/dropdowns/account-details-dropdown.js`
- [ ] `ui/app/components/app/dropdowns/components/dropdown.js`
- [ ] `ui/app/components/app/dropdowns/components/menu.js`
- [ ] `ui/app/components/app/dropdowns/components/network-dropdown-icon.js`
- [ ] `ui/app/components/app/dropdowns/network-dropdown.js`
- [ ] `ui/app/components/app/dropdowns/simple-dropdown.js`
- [ ] `ui/app/components/app/dropdowns/token-menu-dropdown.js`
- [ ] `ui/app/components/app/input-number.js`
- [ ] `ui/app/components/app/menu-droppo.js`
- [ ] `ui/app/components/app/modals/account-modal-container.js`
- [ ] `ui/app/components/app/modals/deposit-ether-modal.js`
- [ ] `ui/app/components/app/modals/export-private-key-modal.js`
- [ ] `ui/app/components/app/modals/hide-token-confirmation-modal.js`
- [ ] `ui/app/components/app/modals/modal.js`
- [ ] `ui/app/components/app/modals/notification-modal.js`
- [ ] `ui/app/components/app/network.js`
- [ ] `ui/app/components/app/shift-list-item.js`
- [ ] `ui/app/components/app/token-cell.js`
- [ ] `ui/app/components/app/token-list.js`
- [ ] `ui/app/components/app/wallet-view.js`
- [ ] `ui/app/components/ui/alert/index.js`
- [ ] `ui/app/components/ui/copyButton.js`
- [ ] `ui/app/components/ui/editable-label.js`
- [ ] `ui/app/components/ui/eth-balance.js`
- [ ] `ui/app/components/ui/export-text-container/export-text-container.component.js`
- [ ] `ui/app/components/ui/fiat-value.js`
- [ ] `ui/app/components/ui/loading-screen/loading-screen.component.js`
- [ ] `ui/app/components/ui/mascot.js`
- [ ] `ui/app/components/ui/qr-code.js`
- [ ] `ui/app/components/ui/readonly-input.js`
- [ ] `ui/app/components/ui/tooltip.js`
- [ ] `ui/app/pages/confirm-transaction/conf-tx.js`
- [ ] `ui/app/pages/create-account/connect-hardware/account-list.js`
- [ ] `ui/app/pages/create-account/connect-hardware/connect-screen.js`
- [ ] `ui/app/pages/create-account/connect-hardware/index.js`
- [ ] `ui/app/pages/create-account/import-account/index.js`
- [ ] `ui/app/pages/create-account/import-account/json.js`
- [ ] `ui/app/pages/create-account/import-account/private-key.js`
- [ ] `ui/app/pages/create-account/import-account/seed.js`
- [ ] `ui/app/pages/keychains/reveal-seed.js`
- [ ] `ui/app/pages/mobile-sync/index.js`
- [ ] `ui/app/pages/send/to-autocomplete/to-autocomplete.js`
- [ ] `ui/index.js`
- [ ] `yarn.lock`
