### ISSUE TITLE
6.2.1 - Unable to click "I Agree" to MetaMetrics

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6295]
**Describe the bug**
Unable to click "I Agree".  Users can only continue by clicking "No thanks" (twice).

**To Reproduce**
New 6.2.1 install, create a wallet, try to select "I Agree".

**Screenshots**
![metrics_bug](https://user-images.githubusercontent.com/16330048/54225485-c5d9a080-44c9-11e9-9484-ae2743106c6d.gif)

**Browser details (please complete the following information):**
 - Browser Firefox
 - MetaMask Version 6.2.1

**Comment by dpazdan** [comment]
The issue appears to only occur on new extension installs.  Existing installs are able to click "I Agree" as shown here: 
![upgrade_ff_meta](https://user-images.githubusercontent.com/16330048/54226570-2073fc00-44cc-11e9-8db9-2d6398cdb85f.gif)

**Comment by tmashuang** [comment]
Closing, fixed.

**Comment by matt454** [comment]
@tmashuang same issue here - Chrome Version 86.0.4240.198 (Official Build) (64-bit)

**Comment by pattarapon23** [comment]
187dca2
