### ISSUE TITLE
Metamask does not show popups after 6.2.2

### ISSUE THREAD

**Issue by wmsouza** [MetaMask/metamask-extension#6299]
Since the 6.2.2 update today, MetaMask stopped showing popups, it shows the number of pending requests on the plugin icon, but no popups are shown.

I'm using Chrome and Brave on Windows 10.

Seems to be a regression of issue #4006

**Comment by tmashuang** [comment]
Is there already a MetaMask Notification/Popup up already?

**Comment by wmsouza** [comment]
I tried with and without pending notifications, I also tried restarting the browsers.
And still all notifications get queued.

**Comment by bdresser** [comment]
@wmsouza I can't reproduce with 6.2.2 on Chrome. What dapp are you using? And you're certain there's no MetaMask popup already open and hidden behind another window? Any errors in the extension console?

**Comment by wmsouza** [comment]
Several different dapps: cryptokitties, axie, opensea.

I will try to see if I find anything wrong.

**Comment by wmsouza** [comment]
Only thing wrong on the logs is 404 trying to get the conversion rate:

```exchanges.balanc3.net/pie?pairs[]=0x06012c8cf97bead5deae237070f9587f8e7a266d/ETH&autoConversion=false:1 Failed to load resource: the server responded with a status of 404 ()```

Looks like it is not sending any pairs to it

**Comment by tmashuang** [comment]
Hmm it is possible Chrome didn't update the extension properly, try resetting the extension in the extension list by toggling.

**Comment by dpazdan** [comment]
opened this issue, possibly related https://github.com/MetaMask/metamask-extension/issues/6306

**Comment by wmsouza** [comment]
I got the error, it goes to the console once if I restart the browser:

Error handling response: TypeError: Error in invocation of windows.create(optional object createData, optional function callback): Error at parameter 'createData': Error at property 'top': Invalid type: expected integer, found number.
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:131480
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:131824
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:131947

I was trying to install the dev environment so I could debug it and submit a PR but couldn't make it run on windows yet, but I suspect is related to #6271 :
top: Math.max(notificationTop, 0),
left: Math.max(notificationLeft, 0),

I tested on:
 Brave Version 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)
and
 Chrome Version 72.0.3626.121 (Official Build) (64-bit)

Somehow that is returning a number and not an integer.

**Comment by wmsouza** [comment]
Ok, it happens when notificationTop or notificationLeft is decimal and not integer

**Comment by stoplion** [comment]
Installing extension for first time. Clicked "Import using account seed phrase". Nothing happens.
