### ISSUE TITLE
Break ui/app/actions.js into different ducks folder based on relevant states

### ISSUE THREAD

**Issue by chikeichan** [MetaMask/metamask-extension#6303]
`actions.js` currently housed all of the actions in the app, limiting code discoverability.

As part of the frontend refactor epic, we should rethink how the shape of metamask's redux store should look like, and re-organize actions into appropriate ducks.

**Comment by danfinlay** [comment]
We've started to! This is an ongoing process, but thanks for suggesting it then Jacky!
