### ISSUE TITLE
Transaction Activity Log shows Gas Limit instead of Gas Price

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6305]
**Describe the bug**
![image](https://user-images.githubusercontent.com/886059/54351958-a7bb9e00-468b-11e9-9a25-486fd3898887.png)
Notice how the Gas Limit is 144141 and the Gas Price is 1 but the Activity Log shows:
> Transaction resubmitted with gas fee increased to 144141 GWEI.

As an expert, I recognize what is trying to be presented, but the current wording is really confusing.  As a user, I don't think of Limit * Price = Fee, I think of Limit and Price independently.  Recommend changing the text to say,
> Transaction resubmitted with gas price increased to 1

**To Reproduce**
1. Submit a transaction with a very low gas price.
2. Click the Speed Up button in the UI to increase the _gas price_.
3. Click on the Pending transaction in the transaction history.
4. Notice that the activity log shows gas cost in ETH, a measure that isn't present anywhere else in the UI.

**Expected behavior**
Existing terms are used in the activity log.

**Actual behavior**
New terms that I am unfamiliar with are introduced in an area with no room to help explain the terms to me.

**Screenshots**
![image](https://user-images.githubusercontent.com/886059/54351958-a7bb9e00-468b-11e9-9a25-486fd3898887.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - MetaMask Version: 6.1.0

**Comment by bdresser** [comment]
Thanks for the feedback @MicahZoltu. Just so I understand, you're suggesting that we only show the variable (either price or limit) that has changed, rather than showing the updated estimate for the total cost of gas? 

> 4. Notice that the activity log shows gas price, a measure that isn't present anywhere else in the UI.

Do you mean "gas fee" ? 

Related https://github.com/MetaMask/metamask-extension/issues/6208

**Comment by MicahZoltu** [comment]
Yes.  The issue is that a new variable not present anywhere else in this part of the UI is presented to the user.  Another solution would be to include the gas fee in the transaction details above, so it isn't a new concept being introduced in a log line and instead is a concept previously introduced in a more prominent part of the UI.  This also creates an opportunity to add (if desired) a tooltip over "gas fee" that tells the user how it is calculated, so they can learn more.  Such a tooltip wouldn't fit well in the log line.

Things the user sets:
1. Attached value (most common)
1. Gas fee (somewhat common)
2. Gas limit (rarely)

Things that are derived from the above and presented to the user:
1. Gas fee (price * gas)
2. Total cost (attached value + fee)

**Comment by wjmelements** [comment]
This is still happening. Quite the scare. I had sped up a transaction.
<img width="353" alt="Screen Shot 2019-10-11 at 1 08 14 AM" src="https://user-images.githubusercontent.com/799573/66635330-d408b000-ebc3-11e9-8e2a-8f0e3549dd52.png">
It's actually showing the max transaction fee instead of the gasPrice.
<img width="497" alt="Screen Shot 2019-10-11 at 1 08 36 AM" src="https://user-images.githubusercontent.com/799573/66635375-f3074200-ebc3-11e9-90ec-00e2ceeb080e.png">

**Comment by ZimZim9** [comment]
> **Describe the bug**
> ![image](https://user-images.githubusercontent.com/886059/54351958-a7bb9e00-468b-11e9-9a25-486fd3898887.png)
> Notice how the Gas Limit is 144141 and the Gas Price is 1 but the Activity Log shows:
> 
> > Transaction resubmitted with gas fee increased to 144141 GWEI.
> 
> As an expert, I recognize what is trying to be presented, but the current wording is really confusing. As a user, I don't think of Limit * Price = Fee, I think of Limit and Price independently. Recommend changing the text to say,
> 
> > Transaction resubmitted with gas price increased to 1
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Submit a transaction with a very low gas price.
> 2. Click the Speed Up button in the UI to increase the _gas price_.
> 3. Click on the Pending transaction in the transaction history.
> 4. Notice that the activity log shows gas cost in ETH, a measure that isn't present anywhere else in the UI.
> 
> **Expected behavior**
> Existing terms are used in the activity log.
> 
> **Actual behavior**
> New terms that I am unfamiliar with are introduced in an area with no room to help explain the terms to me.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/886059/54351958-a7bb9e00-468b-11e9-9a25-486fd3898887.png)
> 
> **Browser details (please complete the following information):**
> 
> * OS: android
> * Browser: metamask
> * 
0xD4D14e59F6a681dFe5a2E89e04ed7CcB1BBBd6c5

**Comment by bschorchit** [comment]
Closing as this is now fixed.
