### ISSUE TITLE
Allow numbers longer than 15 places

### ISSUE THREAD

**Issue by gnorbsl** [MetaMask/metamask-extension#6310]
**What problem are you trying to solve?**
Sending tokens with more than 15 places for example:

123456789.123456789123456789
or
1234567.123456789123456789

MetaMask cuts of everything after 15 places:

123456789.123457
1234567.123456789

**Describe the solution you'd like**
If a token supports 18 decimalplaces, allow the user to send 18 decimalplaces, no matter how high the number in front of the decimalpoint is.

**Additional context**

**Comment by kumavis** [comment]
@gnorbsl as a user do you actually want to see that level of detail in metamask? Tiny fractions of a token? Accuracy down to tiny percent of the amount?

**Comment by gnorbsl** [comment]
What's the reasoning behind cutting off numbers after the 15 place? I would
understand if this is the 15th place after the decimal point but it's not
so it's not a tiny percentage it could be a significant percentage.



Am Do., 28. März 2019, 03:04 hat kumavis <notifications@github.com>
geschrieben:
