### ISSUE TITLE
MetaMask doesn't work with limited site access.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6319]
**Describe the bug**
Brave (by way of Chrome) has a feature where you can limit what domains a given extension can interact with.  To access this, right click on the extension and choose "This site can read and change site data >".

If you switch to per-domain mode and add a dapp domain then refresh the page, MetaMask becomes unable to talk to infura due to CORS preflight failures (as seen by debugging the MM extension background page).

**To Reproduce**
1. Install Brave.
2. Install MetaMask.
3. Limit MetaMask access to per-domain.
4. Load a dapp.
5. Give MetaMask access to pages on that domain.
6. Refresh the dapp.
7. Notice that the dapp doesn't work and cannot access blockchain data.

**Expected behavior**
MetaMask works when limited to certain domains.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - MetaMask Version: 6.2.2

**Comment by sajal** [comment]
I was trying out that option(on vanilla chrome), and it worked for me, while using my private parity instance which is set to return proper CORS headers. Then when I switched to mainnet, metamask stopped working. The following error on background page's console.

```
Access to XMLHttpRequest at 'https://api.infura.io/v1/jsonrpc/mainnet/eth_blockNumber?params=%5B%5D' from origin 'chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

After reading this post, I restored the default setting, i.e. allow on all sites, now main net works. There is something difference in the way metamask (or chrome) makes requests based on the options used. I really like the option to whitelist sites in chrome.

**Comment by ContemporaryAnarchy** [comment]
Hey, I tried this out. The workaround is to add 'api.infura.io' in the list of authorized domains. It must have something to do with the way Infura manages CORS in their response headers. Ive submitted a PR with a doc that explains this.

**Comment by danfinlay** [comment]
Closing since there's a workaround.

**Comment by fostro** [comment]
The workaround doesn't appear to work anymore, or at least not on Brave on linux.  Currently running Brave Version 1.21.76 Chromium: 89.0.4389.86 (Official Build) (64-bit)) with MetaMask version 9.1.1

**Comment by NeutrinoMajorana** [comment]
2024 and this bug is still there ...
