### ISSUE TITLE
Allow manual enable for legacy sites.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6320]
**What problem are you trying to solve?**
There are a number of older sites that do not call `.enable()`, they just try to access `web3.currentProvider`.  Without taking MetaMask out of privacy mode, I would like a way to be able to approve the site so it gets an injected `web3.currentProvider` so I can continue using the dapp.

**Describe the solution you'd like**
Put a button in the extension UI for "Allow this site to see your MetaMask address" (wording could probably be improved).

**Additional context**
Part of the idea with dapps is that they can be deployed to things like IPFS and live forever, even after the author is gone.  Also, if you audit a dapp you may not want to spend (or have the) time to re-audit it so you choose to not update to a newer version of the dapp that supports `.enable()`.  In these cases, there is value in allowing MetaMask to be backward compatible for as long as possible.

Toggling off Privacy Mode is _not_ what I want because that disables privacy mode for _every open tab I have_.  I want to just allow a specific site access through the UI.

**Comment by bdresser** [comment]
This is also a relevant feature for when we enable privacy mode by default

**Comment by bdresser** [comment]
Designs [here](https://github.com/MetaMask/Design/issues/54#issuecomment-497510700)
