### ISSUE TITLE
UI RPC URL Discrepancy

### ISSUE THREAD

**Issue by CruzMolina** [MetaMask/metamask-extension#6321]
Hey MM team!

Noticed a discrepancy on the UI.

<img width="358" alt="Screen Shot 2019-03-19 at 9 37 37 AM" src="https://user-images.githubusercontent.com/7537712/54625709-06d33700-4a2d-11e9-8f3b-9ff621420a7e.png">

Are the current intentions to support the RPC URL as localhost 8545 or localhost 9545?

Thanks for your time! 🍫 

MM: 6.2.2
Browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
OS: macOS 10.13.6 (High Sierra)

**Comment by tmashuang** [comment]
What's running on that port, Ganache, parity, geth, or etc.?

**Comment by adrianmcli** [comment]
Wouldn't it be nice if we could standardize on a port number for all local dev?

**Comment by CruzMolina** [comment]
@tmashuang ganache is running on 8545 in that screenshot.

I'm unable to have MM connect w/ ganache on 9545 unless I specify correct Custom RPC settings. The discrepancy is more that the text at the top shows http://127.0.0.1:9545 while ganache is running on 8545.

**Comment by tmashuang** [comment]
We're overriding `localhost` data. So if there was a previous connection to `http://127.0.01:9545 / http://127.0.01:7545`  it will change the `localhost 8545` nickname we show at the selected network.

**Comment by joshmobley** [comment]
Also, a long rpc endpoint url (with auth) breaks the UI. 

It overflows the container preventing access to the account switcher.

**Comment by bdresser** [comment]
@joshmobley tracked in https://github.com/MetaMask/metamask-extension/issues/6094
