### ISSUE TITLE
When gas API is down, gas info is not editable

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6322]
Per this tweet:
https://twitter.com/PhABCD/status/1108115715998003200

![D2DQ9-nWkAAgb2a](https://user-images.githubusercontent.com/542863/54643317-ccc95b80-4a53-11e9-809a-b44a4ed9efff.png)

**Comment by danjm** [comment]
Solution should be easy: just some css changes on the loading overlay to ensure it does not cover the save button.

**Comment by tmashuang** [comment]
Does this branch have the appropriate fixes for this issue, https://github.com/MetaMask/metamask-extension/compare/fix-loading-gas-chart-css?
