### ISSUE TITLE
Sweeping account leaves dust.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6323]
**Describe the bug**
I just used MetaMask to sweep an account and it left dust (0.00016779 ETH) in the account.

**To Reproduce**
1. Open the account with expanded view.
1. Sweep any tokens in the account.
1. Click on Ether and click Send.
1. Fill in recipient.
1. Click the `max` button for amount.
1. Adjust gas price.
1. Click Next.
1. Confirm transaction.

**Expected behavior**
All ETH in account is sweeped.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - MetaMask Version: 6.2.2

**Additional context**
I suspect the issue is that when I clicked max, the gas price was set to some crazy high default (like 10 nanoeth).  I then reduced it to something reasonable (2 nanoeth) and submitted the transaction.  From a UX flow perspective, gas price came after amount in the form, which is why I filled it in second.  Perhaps put gas price first, amount last so users fill in proper order?  Alternatively, make it so when the user clicks "max" it flags the transaction as a sweep and will sweep everything, adjusting for gas price.  I can't think of a situation where the user would click max and then adjust the gas price and _expect_ their account to not be swept.

**Comment by ContemporaryAnarchy** [comment]
Check out #6488

**Comment by MicahZoltu** [comment]
Looks good assuming it gets finished (https://github.com/MetaMask/metamask-extension/pull/6488#issuecomment-485379818 is implemented).  😄

**Comment by ContemporaryAnarchy** [comment]
Working on it!

**Comment by Gudahtt** [comment]
Closing, as #6488 seems to have addressed this request.

**Comment by alecov** [comment]
This doesn't seem to be working when default custom (advanced) fees are set.

1. Setup a sweep by selecting some destination address and clicking "max";
2. On the "Edit gas fees", select "Advanced", set some max/prio fees values, click on "Save these values as default". (Leave the Gas limit as 21000);
3. Cancel the sweep and go back to the wallet screen.

Now the "Advanced" setting is set by default.

1. Setup a new sweep by selecting an address and clicking "max";
2. The "Advanced" fees are preselected as default. Hover over the "Estimated changes" and take note of the number.
3. Press "Reject" and do this all over. You'll notice the "Estimated changes" will display a different amount (it should be the same -- after all fees and gas limit are static from the "Advanced" default setting).

I have not sent any transaction so this might just be an UI estimation problem.
