### ISSUE TITLE
error:32603, internal JSON-RPC error.

### ISSUE THREAD

**Issue by HavardPede** [MetaMask/metamask-extension#6331]
I am currently running a smart contract on my local ganache network. I have been using 2 different send functions, createToken and upgradeToken. I never get the error with create, but always get it with upgrade. I know this has been an issue of the past, so I did as mentioned, and turned off my ganache, reset metamask account and even reuploaded the SC to the blockchain just to be safe. Still get this error on only the one function. 
I even tried downloading Brave to no avail. Is there a fix for this?

**Comment by HavardPede** [comment]
I have located what causes it. Whenver I call the following: 
`       deleteItem(_account, _id1);
        deleteItem(_account, _id2);
        deleteItem(_account, _id3);`

`    function deleteItem(address _owner, uint _id) internal {
        //Check that the address given owns the item
        require(ownerOfItem[_id] == _owner, "That user dont own the item");
        require(users[_owner].items.length > 0, "Account must have items to remove fron");

        User user = users[_owner];
        //remove item from users list of items
        if (users[_owner].items.length > 1) {
            Item memory lastItem = user.items[user.items.length - 1]; //store last item
            user.items[user.indexOfItem[_id]] = lastItem; //Overwrite item to be removed
            users[_owner].indexOfItem[lastItem.id] = users[_owner].indexOfItem[_id]; //Correct index
        }
        users[_owner].items.length--; //Remove last element in array

        //remove item from list of item-indexes
        delete users[_owner].indexOfItem[_id]; //remove index of deleted item
        
        //Remove map-element in ownerOfItem
        delete ownerOfItem[_id]; //remove ownerOf
        
        //Let it be known that an item has been removed
        numberOfItems--; //decrement numberOfItems

        //Emit tranfser event
        emit Transfer(_owner, address(0), _id);
    }`

By calling this once, the error does not occur. However, when it is called repeatedly, it throws the error. What is puzzling is that it still correctly removes the items from the game.

**Comment by HavardPede** [comment]
I have narrowed it down. Calling array.length -- repeatedly like this causes the error:
`users[_owner].items.length--; //Remove last element in array`

**Comment by geofflangenderfer** [comment]
@HavardPede why does this cause an error?

I'm getting this error executing a metamask swap 

I wonder how you fixed it

**Comment by Tweaker177** [comment]
I can't interact with any smart contract on any of my 5 accounts in Metamask they al give me the same exception, internal RPC JSON error.

It originally started after interacting with a smart contract that had an undefined method, which through a warning, but the contract worked (it minted my NFT and transferred it to me).

I've tried switching to other networks and then reconnecting to the ETC mainnet, since the couple times it suddenly worked both were after changing networks from ETH or KCC or a testnet, then back to ETC mainnet.

Any ideas for a fix besides restoring the wallet?
