### ISSUE TITLE
add test faucet to advanced settings

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#6336]
- [x] change copy "Get Ether from a faucet for the Ropsten **Testnet**"
- [x] change copy "the quickest way to get Ether in your new wallet **is** by direct deposit.

**Comment by Gudahtt** [comment]
The Ropsten test faucet is shown in the deposit modal, so perhaps this has been done? It's not entirely clear to me whether this was meant to represent some additional work or not. I'll close for now, as I think we're OK with how the faucet is presented for now.
