### ISSUE TITLE
MetaMask not returning to web3.js

### ISSUE THREAD

**Issue by stefdworschak** [MetaMask/metamask-extension#6337]
Hi All,

I ran into an issue with MetaMask and web3.js. When sending a transaction via web3.js I do not get any response and my async await function gets stuck. I also do not get the automatic pop-up to confirm/reject the transaction, but had to open the MetaMask manually to confirm/reject.

Here is the error message that I found when opening the extension's background.js through Chrome.

![image](https://user-images.githubusercontent.com/31205982/54872082-74c58880-4db6-11e9-8c78-142a5ef434d4.png)

Here the code excerpt from my React app:

    await lottery.methods.enter().send({
      from: accounts[0],
      value: web3.utils.toWei(this.state.value, 'ether')
    })

    # This line never gets executed because the callback from the previous function never arrives
    this.setState({ message: 'Player was entered!' })`

I'm using the provider from the injected web3.js version from MetaMask.

MetaMask Version: 6.2.2
Chrome Version: 73.0.3683.86 (Official Build) (64-bit) 
OS: Windows 10

Hope anyone can help! Let me know if you have any tips.

Thanks,
Stefan

**Comment by bdresser** [comment]
hey @stefdworschak - this type of question is better suited for Stack Exchange. We try to keep issues focused on feature requests or reproducible bugs. 

Our developer docs might also be a helpful resource - find them [here](https://metamask.github.io/metamask-docs/).
