### ISSUE TITLE
[idea] Unauthorized request count

### ISSUE THREAD

**Issue by mortimr** [MetaMask/metamask-extension#6338]
**What problem are you trying to solve?**
Lack of transparency in the communication of the dapp and the extension when no authorization has been given.

**Describe the solution you'd like**
It would be extremely nice to have a badge with the count of unauthorized requests. This means that if a website is currently trying to use web3 before trying to enable it, the user will immediately see it. 

**Additional context**
I am on a non-dapp website, and suddenly I see this little badge number go to `1` (just like the adblock ones showing how much ads were blocked). I know that the current website is trying to fetch informations about my wallet without asking my authorization. I can report it and ask for explanations. This will discourage website from silently trying to gather data from metamask users that have no privacy mode enabled as they will very easily be exposed.

This is just an idea that I had and wanted to share with you, feel free to shred it to pieces and close this issue :) .

**Comment by bdresser** [comment]
thanks for the idea @mortimr 

we currently use the app-baadge to show the number of queued un-approved requests.

we also plan on enabling privacy mode by default for new users in today's release, and migrating all users to having privacy mode enabled in our next release (early next week)
