### ISSUE TITLE
Cannot use index for `from` address in `sendTransaction`

### ISSUE THREAD

**Issue by thomaseizinger** [MetaMask/metamask-extension#6339]
I am trying to send a transaction through the `sendTransaction` API call documented here: https://web3js.readthedocs.io/en/1.0/web3-eth.html#id70

According to the docs, the `from` property can be an address OR an index that refers to the account in the users wallet.

When using Metamask, the latter doesn't work and results in a cryptic error:

![image](https://user-images.githubusercontent.com/5486389/54894120-35f61680-4f0d-11e9-99cf-8c8c564692b9.png)

**Comment by bdresser** [comment]
@thomaseizinger we only support using an address in the `from` parameter (as documented [here](https://metamask.github.io/metamask-docs/Main_Concepts/Sending_Transactions#sending-transactions)) to prevent dapps from requesting access to or requesting transactions from accounts other than the one the user has selected.

Is there a particular reason you'd like a use an index?

**Comment by thomaseizinger** [comment]
> @thomaseizinger we only support using an address in the from parameter (as documented here) ...

Fair enough. An error message saying this would help a lot in this case! After all, esp. when using typescript, passing a number compiles perfectly fine since the Web3 documentation states that passing an index is allowed!

> to prevent dapps from requesting access to or requesting transactions from accounts other than the one the user has selected.

That is the precise reason I would like to use an index! I wanted to pass `0` in order to not having to bother with what the user's currently selected account is. As a workaround, I now have to do this:

```js
const onClickHandler = web3
    ? async () => {
        setState(TransactionState.Signing);
        try {
          // Have to fetch default account ourselves until this works:
          // https://github.com/MetaMask/metamask-extension/issues/6339
          const accounts = await web3.eth.getAccounts();
          await web3.eth.sendTransaction({
            ...transaction,
            from: accounts[0]
          });
          setState(TransactionState.Sent);
        } catch (e) {
          setState(TransactionState.Error);
        }
      }
    : () => undefined;
```
