### ISSUE TITLE
Ledger requires signing twice.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#6344]
**Describe the bug**
When using a Ledger to sign a transaction, the ledger prompts to sign twice.

**To Reproduce**
1. Add a ledger to MetaMask
2. Send ETH to yourself from the Ledger.
3. Accept the transaction in MetaMask.
4. Accept the signing prompt on the Ledger.
5. Notice that MetaMask doesn't register the signature in the UI.
6. Notice that the Ledger is prompting again for the same transaction.
7. Accept the signing prompt on the Ledger.
8. Notice that MetaMask now accepts the transaction.

**Expected behavior**
One signing prompt on the ledger.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - MetaMask Version: 6.2.2

**Comment by brunobar79** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/6345#issuecomment-477413579

**Comment by brunobar79** [comment]
Same as #6345. Fixed by upgrading to the latest firmware and ETH app version
