### ISSUE TITLE
Enable privacy mode by default

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6352]
Privacy mode should be "ON" by default, with the option to disable.

This requires
- [ ] UI to notify users this change was made
- [ ] addition of "force log in" button described in https://github.com/MetaMask/metamask-extension/issues/6320, https://github.com/MetaMask/metamask-extension/issues/6110
- [ ] some affordance to help users on legacy sites know that they must force log-in 
  - [ ] research if we can detect sites trying to read .accounts[0] before requesting access
  - [ ] if yes, we can show a conditional UI helper just when necessary
  - [ ] if no, we should show something persistent for a period of time
- [ ] message from Twitter and Medium

**Comment by bdresser** [comment]
cc @bitpshr @whymarrh @JSON-LEE13

**Comment by omnat** [comment]
Note:
**conditional UI helper** can be a notification / pop-up that leads user directly to the force log-in option. cc @cjeria

**Comment by whymarrh** [comment]
> - some affordance to help users on legacy sites know that they must force log-in
>     - research if we can detect sites trying to read .accounts[0] before requesting access

Refs https://github.com/MetaMask/metamask-extension/issues/6384#issuecomment-480885405 and https://github.com/MetaMask/metamask-extension/issues/6384#issuecomment-481740856

The answer is yes, we can detect (pending some implementation details) sites that aren't using the 1102 flow.

**Comment by bdresser** [comment]
design issue: https://github.com/MetaMask/Design/issues/54
