### ISSUE TITLE
Missing copy when approving token without a symbol

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-extension#6354]
**Describe the bug**
Copy says 'By approving this action, you grant permission for this contract to spend up to 1.158e+77 of your .'

**To Reproduce**
Try to approve a token without a symbol

**Expected behavior**
Use 'tokens' or some other filler word

**Screenshots**
<img width="359" alt="Screen Shot 2019-03-26 at 8 22 46 PM" src="https://user-images.githubusercontent.com/1577353/55041847-5c977880-5005-11e9-9b0a-14a81560093f.png">

**Comment by bdresser** [comment]
did you... remove your token's ticker symbol when adding it ?

**Comment by aakilfernandes** [comment]
@bdresser this was a test token on the test network without a symbol set.

**Comment by bschorchit** [comment]
We should probably not allow tokens to be added without a symbol. Any thoughts against this?

**Comment by danjm** [comment]
We no longer allow tokens to be added without a symbol, and the confirmation screen for approvals has been fully redesigned within the past 12 months, so this is no longer an issue
