### ISSUE TITLE
"Info & help" should link to "About us" section of settings

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6355]
<img width="353" alt="Screen Shot 2019-03-26 at 8 22 19 PM" src="https://user-images.githubusercontent.com/1016190/55048380-3540ab80-5005-11e9-9cf0-9dfacd3ff1ae.png">

When I click Info & help from the main menu, it takes me to Settings > General. It should link to Settings > About Us

<img width="359" alt="Screen Shot 2019-03-26 at 8 24 00 PM" src="https://user-images.githubusercontent.com/1016190/55048474-8badea00-5005-11e9-9dee-e685f980dadc.png">

Let's also shorten "About us" to "About" since it's really about the extension 😄 and also add a sub-header like the other menu items have. Can say `Version, support center, and contact info.`

**Comment by wbt** [comment]
Where's the PR which supposedly fixed this?

**Comment by whymarrh** [comment]
@wbt #6356

**Comment by whymarrh** [comment]
I can confirm that this is fixed in the latest release

**Comment by Chornuy91** [comment]
chornuy090591@bigmir.net
