### ISSUE TITLE
Not working in canary 75.0.3747.0

### ISSUE THREAD

**Issue by octavioamu** [MetaMask/metamask-extension#6359]
**Describe the bug**
metamask 6.3.0 (same problem in 6.2.0) doesn't open in Version 75.0.3747.0 (Official Build) canary (64-bit)

**To Reproduce**
Last versions of canary and metamask

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1358093/55106708-5c06ec80-50ae-11e9-8477-9ef699af7136.png)
![image](https://user-images.githubusercontent.com/1358093/55106835-a1c3b500-50ae-11e9-90bd-554325a22a17.png)

**Browser details (please complete the following information):**
 - OS: Mac 10.14.4 (18E226)
 - Browser Version 75.0.3747.0 (Official Build) canary (64-bit)
 - MetaMask Version 6.3.0 6.2.0

**Additional context**

**Comment by bdresser** [comment]
any errors in the UI log or background log? 

you can right-click the extension icon for UI log, and go to chrome://extensions and click "background page" for the background log

**Comment by octavioamu** [comment]
Nop, Is kind of small but behind the image there is another image with the log from background

**Comment by whymarrh** [comment]
The current stable Google Chrome version is ahead of this:

> 76.0.3809.100 (Official Build) (64-bit)

We can open up a separate issue for new bugs with Canar builds.
