### ISSUE TITLE
Update tab bar icon

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6366]
@cjeria suggests we change the tab bar icon to a flat fox (!!!!)

<img width="710" alt="Screen Shot 2019-03-28 at 11 23 37 AM" src="https://user-images.githubusercontent.com/1016190/55182937-f8330100-514b-11e9-9c63-527e431ed12a.png">

**Comment by cjeria** [comment]
Tab bar and extension icon.

The logo is difficult to see in chrome dark mode. 
![image](https://user-images.githubusercontent.com/597770/55194344-27676380-5188-11e9-9751-b59e14e18619.png)

Tab
![image](https://user-images.githubusercontent.com/597770/55194371-3c43f700-5188-11e9-91ae-cf27936a7ba2.png)

Main extension icon
![image](https://user-images.githubusercontent.com/597770/55194386-4534c880-5188-11e9-968b-3487c97a42c4.png)

**Comment by jennypollack** [comment]
done in https://github.com/MetaMask/metamask-extension/pull/7408
