### ISSUE TITLE
Update buttons & colors to match design system

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6368]
Update all colors & buttons across the extension to match the components & colors laid out in the [design system](https://www.figma.com/file/aWgwMrzdAuv9VuPdtst64uuw/Style-Guide?node-id=211%3A0).

Notes:
* Button text changes to lowercase.
* Buttons can have the width of their parent element (not just the width defined in the examples)
* If any change (esp for color shades) in the extension is unclear, feel free to ping @cjeria 
* sync with @cjeria on naming conventions so storybook, figma, extension can all stay together

Goal outcome:
* All buttons & colors in extension match the options laid out in the guide

**Comment by danjm** [comment]
Closed by https://github.com/MetaMask/metamask-extension/pull/6446
