### ISSUE TITLE
Implement Design System

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6369]
This is a multi-part issue to complete implementation of the design system code named ~ [MetaMorph](https://www.figma.com/file/aWgwMrzdAuv9VuPdtst64uuw/Style-Guide?node-id=176%3A83)

### Goals
Improve the efficiency, consistency and accuracy of design & development across platforms

### Plan
- [x] Update buttons & colors (https://github.com/MetaMask/metamask-extension/issues/6368)
- [x] Update typography & layout/grid/spacing
- [ ] Update forms, lists, iconography
- [x] Host storybook

### Notes for development
* sync with @cjeria on naming conventions so components can have the same names between Figma, Storybook and compiled UI
* Buttons & colors may be somewhat straightforward, but for future work items feel free to reach out for pairing to address any situation where it's not clear which styles/components should be applied where.

**Comment by brad-decker** [comment]
Going to close this one, all the steps that were completed are for a design system that no longer exists. I do like the name though MetaMorph @georgewrmarshall for inspiration ;P

**Comment by georgewrmarshall** [comment]
Agree!! I like MetaMorph the most from the suggestions so far
