### ISSUE TITLE
Misc Metrics Updates

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6370]
New Events
- [x] Track validation errors in the Import flow (line 34)
- [x] Track clicks on “Go Back” from the import flow (line 37)
- [x] Track completed “Edit” screens with non-standard gas button (line 210)
- [x] Track sends on the token home screen (line 57)
Line numbers refer to MM spreadsheet

Misc / Investigation
- [x] Dedupe function names by language, if possible
- [x] Investigate -- # Accounts most commonly reported as `-`
- [x] Possible to add an event for failed transactions, either on-chain or off?

**Comment by danjm** [comment]
@bdresser Re: "Track clicks on "Go Back" from the import flow". We are currently tracking "Go Back from Onboarding Import"

Are you looking for something different?

**Comment by danjm** [comment]
@bdresser Re: "Tracks sends on the token home screen." How is this different from the `Navigation -> Home -> Clicks Send` event?

**Comment by bdresser** [comment]
Re: onboarding. Sounds good, I probably missed that.

On token sends, we should distinguish between `home -> send` and clicking
Send when the user is on the main screen with a token selected (I.e, they
go to side tray, click a token, land on that token’s “home” screeen). Is
that already knowable and I’m missing something?

**Comment by danjm** [comment]
Moving  "Possible to add an event for failed transactions, either on-chain or off?" to #6416
