### ISSUE TITLE
Support for ERC721 Tokens

### ISSUE THREAD

**Issue by mudgen** [MetaMask/metamask-extension#6379]
**What problem are you trying to solve?**
I am the creator of [mokens.io](https://mokens.io), which is a website for creating and viewing valuable cryptocollectibles called mokens.  I would like my users to be able to see their mokens in MetaMask. 

**Describe the solution you'd like**
I would like a way for users to see what mokens they own in metamask.

Mokens are ERC721 tokens. Will ERC721 support be added to metamask so people can see what ERC721 tokens they have?

**Comment by sekisanchi** [comment]
I wish and strongly recommend Metamask team to lead design and implementation standard about non-fungible asset token along with the ERC. 

"Send" should be capable to treat NFT through some standardized decoding module provided by the originated community like punks, kitties, ENS, collectibles and existing security asset classes.

**Comment by bdresser** [comment]
Duplicates https://github.com/MetaMask/metamask-extension/issues/5230

We have some backend work to do before this gets moving, hang tight folks - we're working on it!!

**Comment by zhous** [comment]
Still hanging?

**Comment by yellowBirdy** [comment]
+
