### ISSUE TITLE
Improve front end methods for identifying transaction type

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6380]
As demonstrated by the bugs we fixed with 6.3.1, our approach to determining transaction type, and therefore confirmation screen to show, is somewhat fragile.

Improvements were made with 6.3.1, but I wonder if we can go a step further, and identify a transaction type at the time the transaction is created. This could be saved with txData, and then we have an authoritative answer with the transaction at all times.

I believe there will always be 4 types of transactions:
- simple sends
- contract deployments
- contract method calls on contracts for which we know the abi within the metamask codebase
- contract method calls on contracts for which the abi is not known

I believe we can identify all cases without having to rely on a network request. While a network request will be needed to get UI relevant data in the last case (i.e. contract method name), it is not needed to successfully render the right contract on the right confirm screen.

I believe the assigning of transaction type to transaction data can be handle without too much difficulty by the transaction controller.

**Comment by bdresser** [comment]
relates to https://github.com/MetaMask/Design/issues/16
