### ISSUE TITLE
Move to the CoinGecko pricing API

### ISSUE THREAD

**Issue by bitpshr** [MetaMask/metamask-extension#6383]
**What problem are you trying to solve?**

MetaMask currently uses the Balanc3 pricing API for token rates. Unfortunately, this API is being shut down soon.

**Describe the solution you'd like**

We should transition the `TokenRatesController` to the [CoinGecko pricing API](https://www.coingecko.com/api/docs/v3) (assuming its rate limit is per IP.)

**Comment by bdresser** [comment]
@bitpshr how soon is soon?

**Comment by tmlee** [comment]
Hi @bitpshr , co-founder at CoinGecko here. Excited to learn that you guys are considering our API.
Yes the rate limit is by API. Full docs over at https://coingecko.com/api

Would be happy to hear how you guys intend to consume the API so we can suggest some suitable endpoints to use.

**Comment by bitpshr** [comment]
Hi @tmlee, thanks for reaching out. We're trying to find a pricing endpoint that supports bulk pricing for assets based on their contract address. It looks like the `/simple/price` endpoint only supports ID-based lookup, and the `/coins/{id}/contract/{contract_address}` endpoint only supports one contract address at a time. Does CoinGecko offer any bulk contract-based pricing endpoint?

**Comment by tmlee** [comment]
@bitpshr Yes that is correct. Both the simple and markets API endpoint do support bulk query but only if the coin-id is passed in.

We are exploring the possibility of extending that to contract address. 
However do you run into cases where the url gets too long with all the bulk contract addresses being passed in, and as such not able to process the query? Basically this problem https://helpx.adobe.com/experience-manager/scene7/kb/base/is_protocol-_-forming_is/url-character-limit-get-requests.html

**Comment by bitpshr** [comment]
Hi @tmlee, thanks for the response. The main reason we need to do contract-based pricing for tokens is because MetaMask users can [create their own custom tokens](http://thetokenfactory.com/#/) very easily and assign them any ticker they'd like. This means it would be possible to make a custom "DAI" token that is not really DAI, but it would still (incorrectly) show DAI's prices because the CoinGecko API only offers bulk pricing based on ticker.

Ideally, we're trying to find an API that allows us to query multiple token prices at once, while still being able to differentiate one from another based on contract address, even if they share the same ticker.

**Comment by tmlee** [comment]
@bitpshr we just pre-release a new endpoint that may suit your use case. Care to give it a go?

For example
https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0x0d8775f648430679a709e98d2b0cb6250d2887ef%2C0xB8c77482e45F1F44dE1745F52C74426C631bDD52&vs_currencies=usd%2Ceur%2Cgbp

Docs for this endpoint at https://www.coingecko.com/api/documentations/v3#/simple/get_simple_token_price__id_
