### ISSUE TITLE
Popup does not open in mobile browser

### ISSUE THREAD

**Issue by manoj529** [MetaMask/metamask-extension#6386]
Hi Team,
We are trying to make a transaction using metamask-extension(V6.3.1)  added in Firefox(V 65.0.1) running in a android mobile (Redmi POCO F1). 

The popup appears automatically when ever we make a transaction in Desktop using chrome/firefox browser. However, The popup does not appear in Mobile browser. We had to manually open the extension  by clicking on the menu options of the browser. 

Can you please look into this issue? Also can you please let us know if we are missing any settings in the mobile browser that need to be re-looked.

Any help regarding it will be appreciated. 
Thanks in advance.

**Comment by tmashuang** [comment]
Seems that Firefox on Andriod/iOS doesn't support the same addon API that creates the notification. The tx should should up if you click the addon at the bottom of the Menu sidebar.
