### ISSUE TITLE
Error: No privateKey given to the TransactionSigner.

### ISSUE THREAD

**Issue by dillonsvincent** [MetaMask/metamask-extension#6390]
**Describe the bug**
When submitting a transaction using web3@1.0.0-beta.51 from my live domain I get an Error: No privateKey given to the TransactionSigner. logged to the console, when I run the same code from my localhost everything is fine.

It's either an issue with the web3 build that gets deployed with react projects or an issue with web3.

link to web3 github could possible be related to web3 and not a metamask issue.
https://github.com/ethereum/web3.js/issues/2638

Code:
```
let web3React = new Web3(window.ethereum);
let contractInstance = new web3React.eth.Contract(JSON.parse(trigger.abi), trigger.rinkeby);
let invoke = contractInstance.methods.invoke([...inputs]).send(sendData)
```

**Browser details:**
 - OS: OS X
 - Browser Chrome/Firefox/Brave
 - MetaMask Version - 6.3.1

**Comment by dillonsvincent** [comment]
Here is a test dapp to show the problem, just open the console
https://console.atra.io/app/1bebd277-7945-4cab-9178-d10255884f95

**Comment by dillonsvincent** [comment]
When i try and use remix.ethereum.org with injected provider I get an error 

Send transaction failed: invalid address . if you use an injected provider, please check it is properly unlocked.

**Comment by EddieOne** [comment]
I see you closed the issue, what was the solution?
