### ISSUE TITLE
Filtering on String throwing 'response has no error or result for request'

### ISSUE THREAD

**Issue by devedse** [MetaMask/metamask-extension#6394]
### Description
I'm trying to get events for my contract in my VueJS application using MetaMask as it's provider:
```js
event ContractAddressChanged(string indexed contractName, address newAddress);
```

I do this by executing the following code:
```js
const allEvents = await contractFinderContract.getPastEvents('ContractAddressChanged', {
        filter: { contractName: ['GreenEnergyContract'] },
        fromBlock: 0,
      });
```
I however keep getting the following error:
```json
Uncaught (in promise) Error: JsonRpcEngine - response has no error or result for request:
{
  "jsonrpc": "2.0",
  "id": 2424636363,
  "method": "eth_getLogs",
  "params": [
    {
      "fromBlock": "0x0",
      "topics": [
        "0x7cc5320aa18fb40c93aed6f76ae28088a8aaf67a112e0ca55367cd087b21802f",
        [
          "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013477265656e456e65726779436f6e747261637400000000000000000000000000"
        ]
      ],
      "address": "0x395aeee1e3c39e6d85da5776848e351c0f81a8ce"
    }
  ]
}
```
If I remove the string filter the query works and I get all the results back.

Contract with source code on ropsten:
https://ropsten.etherscan.io/address/0x395aeee1e3c39e6d85da5776848e351c0f81a8ce

When I query the contract you can see the data is correct:
![image](https://user-images.githubusercontent.com/2350015/55480859-78140c00-5621-11e9-8f3f-e2c77d0366b2.png)

The event is also fired according to Ropsten Etherscan:
![image](https://user-images.githubusercontent.com/2350015/55480889-8530fb00-5621-11e9-9124-377e42deace7.png)

Small note: Another place in my code does actually use a filter on a uint value. That one does actually work.

#### Expected behavior

Once you request an event with a filter provided, don't throw an error but return all the elements that match the filter.

#### Actual behavior
Error `Uncaught (in promise) Error: JsonRpcEngine - response has no error or result for request` is thrown when filtering on a string.

#### Steps to reproduce the behavior
Call the contract mentioned above on the Ropsten network with the code pasted above.

#### Error Logs 
See above

#### Gists
---

### Versions 
* web3.js: `1.0.0-beta.51`
* nodejs: `npm@6.8.0, Node: v10.11.0`
* browser: `Latest chrome`
* ethereum node: `Metamask Ropsten Network`

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - MetaMask Version [e.g. 6.3.1]

**Comment by devedse** [comment]
According to the developer from Web3.JS this is an issue with MetaMask and not with Web3.JS. Original Bug Report on Web3.JS:
https://github.com/ethereum/web3.js/issues/2641

**Comment by kumavis** [comment]
@devedse
> If I remove the string filter the query works and I get all the results back.
what do you mean by the 'string filter'?

**Comment by kumavis** [comment]
so metamask is somehow failing to append the error message from infura, but it looks like this:
```
error: {code: -32602,…}
code: -32602
message: "invalid argument 0: hex has invalid length 96 after decoding; expected 32 for topic"
id: 0
jsonrpc: "2.0"
```

I'm not sure who is preparing that payload (you? web3?) but it seems to be incorrectly formatted or infura's nodes are interpreting them incorrectly

**Comment by devedse** [comment]
> @devedse
> 
> > If I remove the string filter the query works and I get all the results back.
> 
> what do you mean by the 'string filter'?

Instead of:
```js
const allEvents = await contractFinderContract.getPastEvents('ContractAddressChanged', {
        filter: { contractName: ['GreenEnergyContract'] },
        fromBlock: 0,
      });
```

I use:
```js
const allEvents = await contractFinderContract.getPastEvents('ContractAddressChanged', {
        filter: { }, // This is now empty
        fromBlock: 0,
      });
```

If I do that, it returns all items correctly.

**Comment by kumavis** [comment]
here is the PR for fixing the error handling https://github.com/MetaMask/metamask-extension/pull/6401

**Comment by kumavis** [comment]
> According to their developer the payload that's being created is good.

either its a bug in geth (infura) or web3js, metamask just forwards the `eth_getLogs` request and error response

i wish you luck pursuing it.

here's my hint:
this is not a 32 byte topic per the spec https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs
`0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013477265656e456e65726779436f6e747261637400000000000000000000000000`

**Comment by devedse** [comment]
@kumavis, so if the logs mention that, musnt it be in Web3js then?
