### ISSUE TITLE
Token Search not working for many tokens listed in eth-contract-metadata

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#6398]
# Preconditions

* I am set to mainnet
* I have no tokens listed in the left sidebar for my current account (though maybe some of my other accounts have some)
<img width="297" alt="Screen Shot 2019-04-03 at 3 49 09 PM" src="https://user-images.githubusercontent.com/799573/55518215-1014f400-5628-11e9-99e1-aabfa54f5905.png">
* The tokens mentioned here are listed in eth-contract-metadata

# Bugs

I am unable to search for TrueUSD with either "TrueUSD" or "TUSD":
<img width="356" alt="Screen Shot 2019-04-03 at 3 46 24 PM" src="https://user-images.githubusercontent.com/799573/55518141-b90f1f00-5627-11e9-99e8-1202fdd91dbc.png">
<img width="353" alt="Screen Shot 2019-04-03 at 3 46 33 PM" src="https://user-images.githubusercontent.com/799573/55518142-b90f1f00-5627-11e9-950b-e105bdc2ce6d.png">

I am unable to search for USDCoin with either "USD Coin" or "USDC"
<img width="352" alt="Screen Shot 2019-04-03 at 3 49 57 PM" src="https://user-images.githubusercontent.com/799573/55518247-2753e180-5628-11e9-864c-b7da135a2c28.png">

I am unable to search for Gemini USD with either "Gemini USD" or "GUSD"
<img width="355" alt="Screen Shot 2019-04-03 at 3 50 43 PM" src="https://user-images.githubusercontent.com/799573/55518275-46527380-5628-11e9-9dff-8f0d44f64741.png">

Other tokens affected include
* XBP
* KODA
* BOB

Several tokens are searchable, however:
* PAX
* OMG
* BNB
* BBK
* BNT
* TRST
* DATA

I have not found the common denominator between the ones that work.

**Comment by terryli0095** [comment]
Bump

**Comment by tmashuang** [comment]
If your Metamask version is 6.3.1, then those token will not be on the list. We are slowly rolling out v6.3.2 with the up-to-date list. If you want to force the extension to the latest, reinstall the extension from the chrome store.
