### ISSUE TITLE
failed to execute fetch on 'window': the origin of '*/api' should be same as 'chrome-extension*'

### ISSUE THREAD

**Issue by winsvega** [MetaMask/metamask-extension#6400]
**Describe the bug**
The metamask seems to be unable to estimate the gas fee. Label stays like this: `Transaction Fee:
Loading...` and nothing happens. 

Console Log:
```
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': The origin of 'https://dev.blockscale.net/api/' should be same as 'chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn'
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:216722
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2909447
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2221333
```

The network tab shows this one failing:
```
Request URL: https://sentry.io/api/273505/store/?sentry_key=<hash>&sentry_version=7
Request Method: POST
Status Code: 429 TOO MANY REQUESTS
Remote Address: 35.188.42.15:443
Referrer Policy: no-referrer-when-downgrade
```

=====>>>**This issue break metamask completely.**<<<=====

**To Reproduce**
Ubuntu 16.04. Metamask chrome plugin. Metamask default behavior: Metamask does not work.

**Expected behavior**
Metamask should sign and send transactions
Metamask should estimate at least the minimum gasFee for a transaction. 

**Browser details (please complete the following information):**
- Metamask `version 6.3.2`
- Chrome version  `Version 60.0.3112.90 (Official Build) (64-bit)`
- Ubuntu `16_04 LTS`

**Screenshots**
https://ibb.co/NWKn9WX
https://ibb.co/q7YBtWw
(might require proxy it seems in some regions)

**Comment by bdresser** [comment]
@winsvega is this from attempting to initiate a transaction from the extension? would you mind sharing a screenshot and checking your background and UI logs for errors? (instructions [here](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue))

**Comment by tmashuang** [comment]
>  Ability to set the gasFee manually

`Settings -> Advanced -> Toggle Advanced gas controls`

**Comment by winsvega** [comment]
does not work even in advanced menu

**Comment by winsvega** [comment]
https://ibb.co/NWKn9WX

**Comment by winsvega** [comment]
https://ibb.co/q7YBtWw

**Comment by winsvega** [comment]
Metamask `version 6.3.2`
Chrome version  `Version 60.0.3112.90 (Official Build) (64-bit)`
Ubuntu `16_04 LTS`

**Comment by bdresser** [comment]
@winsvega we're still having trouble reproducing, and the links you posted above don't resolve. Could you check again? It's possible the ethgasstation API we use went down briefly.

**Comment by winsvega** [comment]
Links work. Try opening it via proxy. It has debug log on a screenshot

**Comment by winsvega** [comment]
up

**Comment by tmashuang** [comment]
This could be a an API issue, although we use two different services for the gas prices. In the same Console, can you show the Network tab for HTTP response status codes?

**Comment by pytour** [comment]
I have the same issue 
and i solved it by installing metamask on Brave browser.

**Comment by winsvega** [comment]
The network tab shows this one failing:

```
Request URL: https://sentry.io/api/273505/store/?sentry_key=<hash>&sentry_version=7
Request Method: POST
Status Code: 429 TOO MANY REQUESTS
Remote Address: 35.188.42.15:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by Gudahtt** [comment]
The Sentry request failures you're seeing aren't responsible for this problem - you can ignore those.

I'm seeing reports of this issue affecting users of Chromium-derived browsers between v60 and v64. Could you try updating your browser to a more recent version? I haven't managed to figure out _why_ it's failing yet, but I'm guessing something about that `fetch` request was broken between those browser versions.

**Comment by kumavis** [comment]
> Our team had a very bad experience working with metamask. 

@winsvega sorry to hear that, happy to hear any and all feedback to help solve the shortcommings

> I've heard that Brave brwoser been dead for a while now

brave is alive and well.

> Is anyone using metamask on linux at all?

I've used and developed metamask on ubuntu and qubes. haven't had any issues besides some visual ones in qubes

**Comment by tmashuang** [comment]
We have since moved from blockscale to ethgasstation, PR that implementated #7059.
