### ISSUE TITLE
audit codebase for use of deprecated infura endpoints

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#6408]

**Comment by bdresser** [comment]
Also should audit MetaMask dependencies (eth-method-registry, etc)

Could be as simple as grepping for infura in a dev build

**Comment by danfinlay** [comment]
To grep your local dev build for all instances of `infura`:
`grep -r infura dist/chrome/*`

**Comment by jennypollack** [comment]
monitored network traffic and discussed the results in the bi-weekly infura sync, did not find any deprecated endpoints, but we still plan to migrate to v3 (see #6541)
