### ISSUE TITLE
MetaMask doesn't work on Brave browser

### ISSUE THREAD

**Issue by MASY2000** [MetaMask/metamask-extension#6409]
MetaMask doesn't work on Brave browser

**Browser details (please complete the following information):**
 - OS : Windows 10 Pro
 - Browser : Brave 0.64.30 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
 - MetaMask Version 6.3.1

**Additional context**
When I was added MetaMask to Brave, it was appear many time message (Failed - Network error).

What shall i do ?

**Comment by bdresser** [comment]
@MASY2000 looks like the latest production release is 0.62, 0.64 is a dev release that we may not support.

could you try again on 0.62 and let us know if your problem persists? could you also include screenshots of the error, and let us know what you mean by "doesn't work" -- does the extension appear blank, or does it not install correctly, etc etc. (cc @tmashuang )

**Comment by miguelmota** [comment]
Invoking web3 functions throw errors on Brave:

<img width="555" alt="Screen Shot 2019-04-25 at 3 07 34 PM" src="https://user-images.githubusercontent.com/168240/56771591-f0c33f80-676b-11e9-9d2a-77e04b8ee422.png">

**Comment by bdresser** [comment]
make sure you're calling `ethereum.enable()` to request access to users' accounts (as described in EIP 1102)

<img width="415" alt="Screen Shot 2019-05-01 at 11 53 37 AM" src="https://user-images.githubusercontent.com/1016190/57035836-d1169600-6c07-11e9-9f3d-e052f92ca73d.png">

Happy to re-open if there's a reproducible bug here.

**Comment by miguelmota** [comment]
@bdresser yea that was the fix, thanks!
