### ISSUE TITLE
Long RPC Addresses pushes Account Switcher out of view

### ISSUE THREAD

**Issue by dconroy** [MetaMask/metamask-extension#6414]
**Describe the bug**
When connecting to a long RPC address, it bumps the account switcher off the screen.

**Expected behavior**
Id expect the account switcher to wrap or the address bar be truncated.

**Screenshots**
https://imgur.com/ZPvsoyu

**Browser details (please complete the following information):**
Chrome on Mac OS

**Additional context**
RPC address is a Kaleido endpoint.

**Comment by bdresser** [comment]
duplicates https://github.com/MetaMask/metamask-extension/issues/6094
