### ISSUE TITLE
Fix metrics events reporting number of accounts as '--'

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6415]
We are seeing the `numberOfAccounts` dimensions in the metrics dashboards regularly record a value === `'--'`. I cannot figure out why this is by looking at the code nor can I recreate this locally.

Next step is to check if Matomo has a peculiar default... perhaps if the submitted event does not include the dimension at all?

Action on this was first requested in #6370

**Comment by Gudahtt** [comment]
Closing, as we aren't seeing this in our metrics anymore.
