### ISSUE TITLE
No conversion rate for ETH

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6421]
Seeing intermittent issues with missing ETH conversion rates.

No background or UI console errors. Response from Infura's ETH conversion endpoint returns accurately. 

MM v6.3.1

**Comment by bdresser** [comment]
@omnat is still seeing this on 6.4.1

**Comment by scotthelmreich** [comment]
Hi,
I was just trying to send some ETH with Metamask and it is stuck in a loading screen: 
![image](https://user-images.githubusercontent.com/46651705/58410090-7a05b480-803f-11e9-890c-3123f9655df9.png)
I am thinking it might be similar to above, but I have already input the gas price, which was a "Average/Normal" speed. It has been loading (searching for gas?) now for about 20 minutes. I have restarted my browser, restarted my computer-- which caused me to have to log back into Metamask, and after log-in it went straight back to the loading screen. Do you have any advice? I don't mind paying a little extra gas to get this transaction pushed through.
Best Regards,
Scott

**Comment by scotthelmreich** [comment]
I've got it figured out, please disregard.
-Scott

**Comment by KaiserTom** [comment]
A bit of a necro of this issue but I had much similar issues which were instantly resolved by switching to a testnet and then back to the mainnet in the Metamask window. 

Restarting the browser didn't work which was odd. Maybe a PC restart would have rectified it but I didn't test that.

**Comment by tmashuang** [comment]
Archiving issue. If the issue has persisted for anyone else please open a new issue with screenshot as the one above and network logs if possible.
