### ISSUE TITLE
Custom tokens do not respect precision in the UI

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-extension#6426]
**Describe the bug**
Custom tokens do not respect the precision in the UI (still works submits transactions as expected)

**To Reproduce**
1. Create a custom token with precision with precision of 18
2. Send 1 custom token
3. UI will say "Sending 1e18 tokens"

**Expected behavior**
UI should say "sending 1 token"

**Screenshots**
<img width="359" alt="Screen Shot 2019-04-09 at 11 35 32 AM" src="https://user-images.githubusercontent.com/1577353/55814163-06720d00-5abc-11e9-9727-b07f7f1e94a2.png">
<img width="352" alt="Screen Shot 2019-04-09 at 11 35 40 AM" src="https://user-images.githubusercontent.com/1577353/55814170-0a059400-5abc-11e9-958a-821b2dfe7885.png">

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser Chrom
 - MetaMask Version 6.3.1

**Additional context**
Testing with fake-DAI on rinkeby. There is no on-chain "decimals" which might be causing the issue

**Comment by tmashuang** [comment]
This seems to have been fixed in the latest version. If this issue has persisted, please open a new issue.
