### ISSUE TITLE
Do not minify Chrome builds

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6429]
We had an old UAT metamask extension that got deactivated by Google for code minification. They may be going through and disabling extensions that use minification, and so we may want to stop minifying our chrome builds to pre-empt a possible abrupt deactivation.

**Comment by whymarrh** [comment]
Refs #6875, as @ catsass19 experienced, this might be due to our injection strategy

**Comment by Gudahtt** [comment]
Closing, as minification is explicitly allowed by both Chrome and Firefox. They do disallow other forms of obfuscation, but as far as I know our current approach is OK.
