### ISSUE TITLE
Request: Change management documentation

### ISSUE THREAD

**Issue by darenfrankel** [MetaMask/metamask-extension#6432]
Hey MetaMask team (@kumavis),

Need your help with something. I've taken a look at your "Publishing Guide" on GitHub (https://github.com/MetaMask/metamask-extension/blob/develop/docs/publishing.md), but was curious if you could provide more information on your Change Management practices for releasing code including how code is reviewed, approved, and eventually pushed into production? 

Additional context provided in the ConsenSys Slack: https://consensys.slack.com/archives/G0SCK68Q5/p1554362647020500

Thanks!

Daren

**Comment by bdresser** [comment]
handled in https://github.com/MetaMask/metamask-extension/pull/6470
