### ISSUE TITLE
Show additional info on Confirm screen (time, domain, dupes)

### ISSUE THREAD

**Issue by marceljay** [MetaMask/metamask-extension#6433]
The main feature request is to provide the user with additional information regarding the transaction to be sent.

One first feature would be to provide the user with date/time info corresponding to the transaction prompt in metamask.  The time could be passed when the web3js send() function is called. This can be important, when for example, I press some button and then leave the computer. Later on, I might not anymore know, what kind of transaction is shown in my metamask or whether it is recent.
Especially, when I accidentally click twice on a button or trigger multiple transaction, I might not know, which is which, or if they are duplicates. 

Another feature would be, to show on which url/domain or button the prompt was triggered. 
What I usually do, when I don't remember, is to reject all transactions and redo everything.

**Comment by Gudahtt** [comment]
Thanks for the suggestion! I'm closing this because these two suggestions are already captured by other tickets; the transaction creation date was requested in #4349, and the origin was requested in #5611. We will track these requests on those tickets instead.
