### ISSUE TITLE
Show sub-headers on full screen settings menu

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6437]
<img width="1320" alt="Screen Shot 2019-04-10 at 10 24 57 AM" src="https://user-images.githubusercontent.com/1016190/55900040-23b9e080-5b7b-11e9-91c5-4079b56b4bd4.png">

**Comment by chikeichan** [comment]
@bdresser @cjeria 

Is this to add sub-headers to all setting subviews? I think this makes the UI too cluttered. I think the side nav current communicate active tab fairly well.

If the change is to make room for "Add Network", I think we can add a button on top or bottom of the network list.

wdyt @bdresser @cjeria ?

**Comment by cjeria** [comment]
Hey, @chikeichan yes, sub-headers for all subviews. As per discussions had with @danjm on slack, not only will the subheader serve to add action buttons to sections when needed (such as the **add network** button inside **networks**), but will also add visual hierarchy to the page, making it easier for users to navigationally identify their location in settings. Sub-headers will also make for better accessibility.

See this example from Github's design system **Primer**. 
![image](https://user-images.githubusercontent.com/597770/56612620-70210980-65da-11e9-8b31-5306b674d090.png)

Sub-heading should also be static. See my UX feedback recording regarding the UX of the networks of settings. https://www.loom.com/share/304741d6f741486286e665b2382e5a92

Let me know if you have any more questions.
