### ISSUE TITLE
Clicking "Info & Help" doesn't produce expected results

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6441]
**Describe the bug**
Clicking "Info & Help" in MetaMask doesn't provide useful info or help someone find help.

**To Reproduce**
1. Open a browser with MetaMask and log in.
2. Click on the user identicon circle in the upper right corner
3. Click "Info & Help," as if you're trying to get the MetaMask version for the purposes of filing a bug report.

**Actual behavior**
4. See a screen labeled "Settings" with options for currency conversion and primary display currency, underscoring the primacy of ETH as a volatile currency instead of its intended use as a crypto-fuel for utility-delivering distributed applications.  Scroll down to see a Current Language setting and a "Use Blockies Identicon" toggle (not clear to the average user what that means).
5. See no way to get to the "Info & Help" one was trying for.

**Expected behavior**
The same as if clicking "Settings," then scrolling down to the bottom and clicking About Us, except probably without a repeat of the fox icon that is already in the upper right,  so that the user can see the links to help without having to scroll below the visible area. 

**Expected behavior screenshots**
Significant improvement over status quo:
![image](https://user-images.githubusercontent.com/563406/55913146-ea509780-5bb1-11e9-95e3-1f9d681816da.png)

Better: 
![image](https://user-images.githubusercontent.com/563406/55913294-4e735b80-5bb2-11e9-9dd8-c74d694f4a85.png)

Maybe put the fox in the bottom center, accessible via scroll, if a third, larger version of it is really needed in this view.

**Browser details:**
 - OS: Windows 10 Pro
 - Browser: Chrome 72.0.3626.121 (Official Build) (64-bit)
 - MetaMask Version: 6.3.1

**Comment by bdresser** [comment]
yep, this was totally a bug -- fixed in https://github.com/MetaMask/metamask-extension/issues/6355

feel free to open the design feedback about the fox in a separate issue if you'd like
