### ISSUE TITLE
Header is taller if custom RPC is selected

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6442]
**Describe the bug**
The header portion of the MetaMask UI is slightly taller when connecting to a custom RPC, throwing off other vertical alignment around what might be visible with vs. without scrolling. 

**To Reproduce**
1. Open a browser with MetaMask and log in.
2. Connect to a custom RPC network.
3. Go to Settings -> About Us (a bit harder to find due to Issue #6441)
4. Observe how "Visit our Support Center" appears partially cut off, not part of what the user is intended to be able to see/interact with until after additional scroll action.
![image](https://user-images.githubusercontent.com/563406/55913574-f12bda00-5bb2-11e9-81c6-6c1b887deca8.png)
5. Connect to the Main Ethereum Network
6. Observe how less of the text is cut off:
![image](https://user-images.githubusercontent.com/563406/55913709-3ea84700-5bb3-11e9-8631-1caf7cb9be22.png)

**Expected behavior**
Custom RPC settings permit a [custom icon/color picker](https://github.com/MetaMask/metamask-extension/issues/5790#issuecomment-462805889), and the default has the same height as the networks that come pre-programmed in. 

**Browser details (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome 72.0.3626.121 (Official Build) (64-bit)
 - MetaMask Version: 6.3.1

**Comment by wbt** [comment]
Is there a PR which fixes this, regarding the closure?

**Comment by bdresser** [comment]
https://github.com/MetaMask/metamask-extension/pull/6468
