### ISSUE TITLE
Drop the top fox in "About"

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6443]
**Describe the bug**
From Issue #6441. 
In the "Info & Help" page, a large fox icon occupies enough vertical space that the "Help" portion of "Info & Help" is pushed off the bottom & requires scrolling.  

Current:
![image](https://user-images.githubusercontent.com/563406/55913146-ea509780-5bb1-11e9-95e3-1f9d681816da.png)

Better: 
![image](https://user-images.githubusercontent.com/563406/55913294-4e735b80-5bb2-11e9-9dd8-c74d694f4a85.png)

Maybe put the fox in the bottom center, accessible via scroll, if a third, larger version of it is really needed in this view.

**Browser details (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome 72.0.3626.121 (Official Build) (64-bit)
 - MetaMask Version: 6.3.1

**Comment by jobindy** [comment]
L
