### ISSUE TITLE
Document metrics events and organize custom variables by page

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6453]
We need to document how to create metrics events, how the event system works and the metametrics util code.

Included in this documentation is clear documentation of how to use custom variables and the limits on them. We should also group custom variables by page and possibly split them into a separate enums file (although I am leaning against this).

Included in this work can be adding the customVariable referenced here to the id map https://github.com/MetaMask/metamask-extension/pull/6445#discussion_r274748226

**Comment by matawinb** [comment]
https://github.com/MetaMask/metamask-extension/issues/6445
