### ISSUE TITLE
the  metamask throws errors when sending transaction when connecting to local network

### ISSUE THREAD

**Issue by IamChuancey** [MetaMask/metamask-extension#6456]
**Describe the bug**
the  metamask throws errors when sending transaction when connecting to local network,like this:
`MetaMask - RPC Error: Error: Error: [ethjs-rpc] rpc error with payload {"id":7287525666291,"jsonrpc":"2.0","params":["0xf8c80184b2d05e008289d39407bcca13cf996121b333a42bd27eb6e54479613880b864435ffe94000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000066e6968616f21000000000000000000000000000000000000000000000000000046a0664ab834e45439b43db3631716d0edd54d317a8bf01d65fcf6c4fe01b8b7adb6a019ef245305c34af09ff6cff6db060e985b7c2e41869ba5fa7f60c56b914ab2a6"],"method":"eth_sendRawTransaction"} Error: invalid sender `
I have found the same bug report [#2015,](https://github.com/MetaMask/metamask-extension/issues/2015) ,but it seems that it's not handled yet.

**To Reproduce**
1. metamask connecting to local network
2. send transaction between local accounts
3. the accounts has plenty eth or gas fee paid

**Screenshots**

![image](https://user-images.githubusercontent.com/29730996/56081874-8db8db00-5e44-11e9-9fd0-7fc59c85a97b.png)

**Browser details (please complete the following information):**
 - OS: [ mac OS ]
 - Browser [chrome, firefox]
 - MetaMask Version [the latest]

**Comment by IamChuancey** [comment]
Well,I have solved it myself ,if anyone who came across the same error, you can get involved with me by chuancey.yang@gmail.com

**Comment by Rtblock** [comment]
Can you please post it here.It will be help.
