### ISSUE TITLE
Login on payback.de not possible with active MetaMask extension

### ISSUE THREAD

**Issue by ErikAbele** [MetaMask/metamask-extension#6457]
When MetaMask Chrome extension is loaded & activated (for all sites) then a login to payback.de is not possible; the login page simply stays empty.

**To Reproduce**
1. Add MetaMask to Google Chrome
2. Load https://www.payback.de/login
3. Page stays empty and does not show login elements

**Expected behavior**
To see the login elements and be able to log in. As soon as extension is disabled, the page works as expected again.

**Browser details (please complete the following information):**
 - OS: latest Mac OS X
 - Browser: latest Google Chrome
 - MetaMask: latest extension (6.3.2)

**Additional context**
It probably does not load some external content, don't have the time to dig into this.

**Comment by ErikAbele** [comment]
Workaround:

1) go to settings of MetaMask extension (Window > Extensions > MetaMask > Details)
2) select "On click" for site access (instead of "On all sites")
3) reload page in question

**Comment by bdresser** [comment]
We can add to the blacklist so web3 isn't injected on this site

**Comment by whymarrh** [comment]
7.1.0 no longer injects by default for all users. Let us know if you're still seeing this on the latest version of MetaMask and we can reopen + reinvestigate this.
