### ISSUE TITLE
How to clear cache and refresh account via injected web3

### ISSUE THREAD

**Issue by askucher** [MetaMask/metamask-extension#6458]
Hey, everyone. Metamask can see changes only made by using Metamask. But it does not see changes made in the background because it is already cached the requested value and does not change it without new transaction. Need to switch the network to another and then switch it back to see the changed state.

How can I do it programmatically via injected web3? Because it is kinda complicated action for user.

**Comment by mattfysh** [comment]
@askucher did you happen to find a way to refresh programatically?
