### ISSUE TITLE
ETH and Token incorrectly displaying 0 balance

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6461]
**Describe the bug**
If a user has 0.0000X ETH or 0.000X of a token, or less, it displays as a 0 balance.

**Expected behavior**
Users with a fraction of a token or eth would still like to see the exact amount, not a shorted or rounded number.

**Browser details (please complete the following information):**
 - MetaMask Version 6.3.2

**Comment by dpazdan** [comment]
Other Possible "Balance not updating or displaying correctly" scenarios:
- spotty network connectivity 
- infura or balanc3 issue
- behind a firewall / web filter

**Comment by tmashuang** [comment]
Archiving this issue. For anyone having this issue, please open a new issue with screen caps of the network tab in the background developer console of the extension.
