### ISSUE TITLE
Allow dragging seed phrase words

### ISSUE THREAD

**Issue by gubikmic** [MetaMask/metamask-extension#6465]
One wrong click and you need to start all over again. Very frustrating.
It would be faster for me to just type out the words in a text field.

Making the boxes draggable would keep the current UI while allowing to correct mistakes.

**Comment by bdresser** [comment]
Agree @gubikmic 

@cjeria @omnat any concerns with making the seed words draggable, so users could re-order or insert a forgotten word? I think this is much needed.

**Comment by cjeria** [comment]
@bdresser yep, totally agree. I just dealt with this issue today in fact. Draggable would be great.
