### ISSUE TITLE
Auto detected Ropsten Token's decimal spaces cannot be changed, show balance incorrectly

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-extension#6467]
**Describe the bug**
If you add a Custom Token while connected to the Ropsten network, the Token's details gets pulled automatically, they cannot be manually changed, but balance is shown incorrectly and Send screen available balance is wrong too.

**Expected behavior**
You should be able to use the EDIT button in the Custom Token section to also edit the decimal spaces, for example this token says it has ZERO decimals https://ropsten.etherscan.io/token/0x57ba08e6b5509e1433fac5c518b73167164eb07f , but 18 is set automatically and cannot be manually changed.

**Screenshots**
Case: 17724

Balance

<img width="506" alt="17724_1" src="https://user-images.githubusercontent.com/2995401/56228906-bad4db80-6046-11e9-9a26-cef4bd916cf3.png">

Send token

<img width="273" alt="17724_2" src="https://user-images.githubusercontent.com/2995401/56228914-be686280-6046-11e9-8a0b-d3c1e086d6ed.png">

**Comment by tmashuang** [comment]
Without knowing the contract code, it could be an issue with the contract itself. I have tested this with another token with a 0, and others, decimals precision and it auto detected correctly. If one can determine that this is an issue detection we can reopen this.
