### ISSUE TITLE
UX to show "unlimited" on Approve screen per EIP717

### ISSUE THREAD

**Issue by p-s-dev** [MetaMask/metamask-extension#6469]
**What problem are you trying to solve?**
User are confused when seeing "you grant permission for this contract to spend up to 1.158e+59 of your DAI"

**Describe the solution you'd like**
User would more easily understand "you grant permission for this contract to spend *an unlimited amount* of your DAI"

**Additional context**
if (approveAmount == uint(-1)) : UxMessage = "an unlimited amount"

**Comment by bdresser** [comment]
@p-s-dev agree, the confirm screen for Approves can be pretty daunting, we'll be taking a look shortly.

**Comment by CryptoQueen628** [comment]
Very excited for this change to be made. Will clear up a lot of confusion for users. Thanks.

**Comment by Gudahtt** [comment]
This was implemented in #7271
