### ISSUE TITLE
Remove shapeshift

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6478]
It's broken and the login/KYC requirements are now different. 

We will shortly replace with Changelly (https://github.com/MetaMask/metamask-extension/issues/1632)

**Comment by danjm** [comment]
The relevant modal can be found by clicking the "Deposit" button on the home screen.

![Screenshot from 2019-06-21 13-19-36](https://user-images.githubusercontent.com/7499938/59935033-70495400-9427-11e9-9d7c-848343a40c30.png)

The code to remove can be found in `metamask-extension/ui/app/components/app/modals/deposit-ether-modal.js`
