### ISSUE TITLE
Transaction confirmation not shown until I switched to another account

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#6485]
If I send a transaction with one account and switch to another, I don't see the confirmation when that transaction confirms until I switch back. I want to see it when it happens.

> MetaMask 6.3.2

**Comment by wjmelements** [comment]
(The notification came 7 minutes after the confirmation, and immediately after I switched back to the account).

**Comment by wjmelements** [comment]
I'm currently seeing a delay of greater than 2 minutes without switching the accounts. Switching the account unstucked the pending state.

**Comment by tmashuang** [comment]
I believe we have prevented the behavior to switch accounts on the confirmation screen. We allow to edit the tx and change the recipient, and send the tx. The confirmation is locked in focus and needs an action to proceed back to the main screen/ I could be wrong and we still do, but I could not see it, if this is the case please comment on the method on a new issue.
