### ISSUE TITLE
MetaMast - Connection to 8545 network but shows 7545

### ISSUE THREAD

**Issue by hafizzain** [MetaMask/metamask-extension#6487]
Hi Guys, 

Whenever I am trying to switch 8545 network using MetaMast, it changed to 7545 but shows 8445 selected in drop down.

Thanks

**Comment by Chornuy91** [comment]
chornuy090591@bigmir.net

**Comment by bdresser** [comment]
@hafizzain can you provide some more specific step-by-step reproduction instructions?

**Comment by hafizzain** [comment]
<img width="349" alt="Screenshot 2019-04-21 at 17 39 06" src="https://user-images.githubusercontent.com/12877221/56633360-c8095000-666e-11e9-8d8c-86148a536ced.png">

In that screenshot, you can see whenever I am trying to connect to 8545 ... It shows connected in the dropdown menu of MetaMast but on the top, it switched back to 7545 localhost.

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/6444 will be out in v6.4.0
