### ISSUE TITLE
selectedAddress is undefined after web3 injected into chrome

### ISSUE THREAD

**Issue by chaosma** [MetaMask/metamask-extension#6491]
**Describe the bug**
web3 cannot find any address (selectedAddress=undefined) from my metamask account. I tested it on several versions of metamask: 6.2.2.1 (works), 6.3.0(not work), 6.3.1(not work), 6.4.0 (not work)

**To Reproduce**
Test it on Ropsten testnet: Select ropsten network from metamask, make sure account balance is non-zero. Press F12 into console (where I print the provider object) and looking for selectedAddress

**Expected behavior**
selectedAddress in provider should not be undefined.

**Screenshots**
screenshot of metamask 6.2.2.1

<img width="913" alt="6 2 2 1 works" src="https://user-images.githubusercontent.com/3767044/56517322-81dab200-64f1-11e9-8d3c-395271c1deb7.png">

screenshot of metamask 6.3.0/6.3.1/6.4.0
<img width="930" alt="notwork" src="https://user-images.githubusercontent.com/3767044/56517329-843d0c00-64f1-11e9-9800-c1089a6e5313.png">

**Browser details (please complete the following information):**
 - OS: test on both ubuntu 18.04 and macOS Mojave 10.14.4
 - Browse: Chrome
 - MetaMask Version: >=6.3.0 (Not work), 6.2.2.1 (works)

**Comment by reactoshi** [comment]
It's same issue for me...
I tried v6.3.2 in chrome but can't find selectedAddress.
After that, I could find it v6.2.2 in firefox.

**Comment by bdresser** [comment]
Hi all - please check if Privacy Mode is turned on in Settings > Security & Privacy. This has been an optional feature for several months, and is now enabled by default for new users as of v6.3.0

if Privacy Mode is enabled, you'll need to call `ethereum.enable()` to see users' addresses as per EIP 1102.

**Comment by chaosma** [comment]
Ah, I haven't heard of it. Now it works on new version. Thanks!

**Comment by chaosma** [comment]
-

**Comment by reactoshi** [comment]
It works on chrome by your solution. Thank you!!

**Comment by Raj2367** [comment]
I just disable the privacy mode and now it is work for me...thanks a lot @bdresser

**Comment by Raj2367** [comment]
I just disable the privacy mode in metamask and now it is working for me... thanks a lot @bdresser
