### ISSUE TITLE
Incorrect button color on extension view

### ISSUE THREAD

**Issue by chikeichan** [MetaMask/metamask-extension#6492]
**Describe the bug**
Incorrect button color on extension view

**To Reproduce**
1. Go to Extension view or Mobile responsive view)
2. See that button has a gray background

**Screenshots**
<img width="358" alt="Screen Shot 2019-04-22 at 8 57 38 PM" src="https://user-images.githubusercontent.com/8507735/56552884-7e6f1700-6541-11e9-9275-60372ffd0e80.png">
<img width="364" alt="Screen Shot 2019-04-22 at 8 57 33 PM" src="https://user-images.githubusercontent.com/8507735/56552885-7f07ad80-6541-11e9-9fb2-44ee7463c1b8.png">
<img width="357" alt="Screen Shot 2019-04-22 at 8 57 27 PM" src="https://user-images.githubusercontent.com/8507735/56552886-7f07ad80-6541-11e9-8a45-9f442b8251c0.png">

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - MetaMask Version: 6.3.2

**Comment by bdresser** [comment]
closed via https://github.com/MetaMask/metamask-extension/pull/6493

@chikeichan pro-tip if you say "fixes [issue number]" in your PR it will close these issues automatically when the PR is merged ;)
