### ISSUE TITLE
6.4 -No price conversions available for some tokens - NMR, WETH

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6506]
**Describe the bug**
Two tokens (likely more) are available on CoinGecko but not displaying fiat price on MetaMask.  Two so far I've noticed: WETH, NMR.  Also note, if a person has a small amount of a token, it will not show the conversion at all, $0.00X

**Expected behavior**
Price displayed for all tokens that Coingecko has data on.

**Browser details (please complete the following information):**
 - MetaMask Version 6.4

**Comment by tmashuang** [comment]
There are some tokens for the CoinGecko API that are returning checksummed token addresses. For instance NRM and OMG. As for WETH, CoinGecko doesn't seem to conversion rate for it.

**Comment by dpazdan** [comment]
Not sure if this is related, but I'm unable to get a price to show up on MM for WETH.  Coingecko appears to have a price for WETH so I'm not sure the cause.

**Comment by tmashuang** [comment]
https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&vs_currencies=eth

The way we call their API might be an issue. I was able to find it from a different route, https://api.coingecko.com/api/v3/coins/weth. But they list 0xecf8f87f810ecf450940c9f60066b4a7a501d6a7 as the contract address, which also does not return a token price in the first route listed either. Would be nice to get clarification from them.

**Comment by tmlee** [comment]
I've noticed that we did not add the contract address for WETH. We just done so and the price should be reflective using the contract address API query now.

Is NMR, Numeraire? https://etherscan.io/token/0x1776e1f26f98b1a5df9cd347953a26dd3cb46671

**Comment by tmashuang** [comment]
Yep, it is. The conversion is coming back for the WETH contract now. There is a discrepancy with the rate. The current rate of it when this comment is written is 0.923038 from Etherscan, but 1.004117 from CoinGecko.

**Comment by tmashuang** [comment]
@dpazdan Can we close this?
