### ISSUE TITLE
Metamask not working on W12.io Token Platform

### ISSUE THREAD

**Issue by maikelblogo** [MetaMask/metamask-extension#6508]
I have tried a lot to get access to funds on W12.io platform and, once using Metamask on Google Chrome on W7 32 bits, i should be able to work with[ W12.io](www.w12.io) environment. But it lays like...

"[!] Invalid JSON RPC Response"

I dunno what i should do because i want to start my project as well, But Metamask is having some kind of issues like that. I dunno if this is about low connection or something with Wrong installing Metamask. I want a better response .

![](https://cdn.steemitimages.com/DQmXLt4jwzSQNMn38V6VikHbq8nB7kPJdRjwvZNrCjqEGNj/image.png)

**Comment by bdresser** [comment]
Could you provide

- detailed reproduction steps to get this error
- a readout from your UI console and background console to see if there are any errors ([link](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue))
- MM, OS and browser version

**Comment by maikelblogo** [comment]
My metamask version is 6.2.2. Google Chrome (the latest version) at Windows 7 Professional 32 Bits

So, i have followed the instructions you gave me, and the background showed me these results
![Metamask Errors 1.png](https://cdn.steemitimages.com/DQmNdUbrXpq6zALvhRREeNUNT32ott1DBDvYH5N5trAukkv/Metamask%20Errors%201.png)
![Metamask Errors 2.png](https://cdn.steemitimages.com/DQmQZP6nhTsk3UwZzqEuQpvyVuNAy1ijGHbrwQXT3SZNr2K/Metamask%20Errors%202.png)
![Metamask Errors 3.png](https://cdn.steemitimages.com/DQmSQkRXtHsdVMSmYrDwMKfiKghrAhS6mHXZj13sbMmZND1/Metamask%20Errors%203.png)
![Metamask Errors 4.png](https://cdn.steemitimages.com/DQmbwTdkEo96jKx7vJXh8esXxCnsYNfKqvB2kWbCASkTs7q/Metamask%20Errors%204.png)

But, i have been replied on W12 support and this is the answer they gave me....

![w12 doesnt work heres why.png](https://cdn.steemitimages.com/DQmeMSQLehRprh8q5Z93Q7ZNMPFiMPAayxsDKS7hgUdW2B9/w12%20doesnt%20work%20heres%20why.png)

**Comment by bdresser** [comment]
It seems like the platform you're trying to use isn't in production yet. If you have similar issues with other sites, please reach out to support@metamask.io and we'll help you over there.

Also recommend upgrading to MM 6.4.1 via the Chrome Web Store.
