### ISSUE TITLE
Implement MetaMorph typography

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6510]
Sizes and colors as defined [here](https://www.figma.com/file/aWgwMrzdAuv9VuPdtst64uuw/Style-Guide?node-id=211%3A0)

Part of #6369

**Comment by cjeria** [comment]
@chikeichan I'll schedule a short call to chat live about this one.

**Comment by brad-decker** [comment]
Moved on from MetaMorph typography I believe.
