### ISSUE TITLE
Document MetaMask-specific provider methods

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6511]
The methods in `ethereum._metamask` are specific to our 1102 implementation. They should be documented and their usage should be qualified carefully so folks know they're not universal or may not be supported by other browsers.

**Comment by bitpshr** [comment]
Fixed in https://github.com/MetaMask/metamask-docs/commit/0ca4f6ca816e95c4118e19c9b3f74240b8664347.

Live documentation:

https://metamask.github.io/metamask-docs/API_Reference/Experimental_APIs#ethereum._metamask
