### ISSUE TITLE
6.4.1 Can't get accounts

### ISSUE THREAD

**Issue by jaimehrubiks** [MetaMask/metamask-extension#6527]
**Describe the bug**
I can't get the user's account public address. 

**To Reproduce**
1. Install 6.4.1 zip and setup an account
2. Paste this into console:
web3.eth.getCoinbase((e,a)=>console.log(e,a))
or
web3.eth.getAccounts((e,a)=>console.log(e,a))

**Expected behavior**
See the first account (or the list of accounts). 
e=undefined 
a=data

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: chrome
 - MetaMask Version: 6.4.1 zip file

**Additional context**
It works on 6.4.0, but this version is unusable.

**Comment by tmashuang** [comment]
Is privacy mode enabled?

**Comment by jaimehrubiks** [comment]
My bad, it is. I forgot it is enabled by default now.

**Comment by jaimehrubiks** [comment]
@tmashuang BTW, shouldn't it be better if the function returned an error?

**Comment by tmashuang** [comment]
Mhmm, I'll take a look at it. I agree with that.
