### ISSUE TITLE
Migrate to Infura V3 endpoints

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6541]
Infura would like us to migrate to their newest set of endpoints. 

Rollout should be handled carefully to make sure that not being behind a CDN doesn't impact performance. 

More details [here](https://docs.google.com/document/d/1eGFeBBBwX2lVk0_mb1CdHwoG8zNes2xovqYgZJ6Q8yU/edit)

**Comment by tmashuang** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/9368
