### ISSUE TITLE
MetaMask icon background turns white when site access setting is modified

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6542]
**Describe the bug**
If a user sets MetaMask extension site access settings to "On Click" instead of "On all sites", it will change the background of the icon when clicked on a site.

**To Reproduce**
1. Go to MetaMask extension settings
2. Select On Click
3. Go to a site
4. Click MetaMask in the extension toolbar

**Expected behavior**
It should stay the same background color 

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/56969016-e3220700-6b29-11e9-8551-db42323ec0c3.png)

**Browser details (please complete the following information):**
 - Browser Chromium - Chrome, Brave
 - MetaMask Version 6.4.2

**Additional context**
Recognized by support case: 18774

**Comment by danfinlay** [comment]
May be related to #6319

**Comment by Gudahtt** [comment]
This appears to have been fixed; the background no longer turns white now.
