### ISSUE TITLE
Error on Ropsten page after closing modal window

### ISSUE THREAD

**Issue by mtcls** [MetaMask/metamask-extension#6552]
**Describe the bug**
Error on the https://faucet.metamask.io/ after closing modal window

**To Reproduce**
1. Change network to Ropsten
2. Open https://faucet.metamask.io/
3. Click some user button, e.g. 1 ether
4. Close modal window

**Expected behavior**
Modal window is closed

**Screenshots**
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/46102189/57057853-961e6c00-6cb4-11e9-8bdc-42947c0414e4.png">

**Browser details (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: firefox
 - MetaMask Version: 6.4.1

**Comment by tmashuang** [comment]
It is unclear to me what the issue is trying to say. I am inferring that the error message is not the one that is intended. I just reproduced and the error has has changed to one that is readable.

> Error: MetaMask Tx Signature: User denied transaction signature.
