### ISSUE TITLE
automatic reset account detection on localhost

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#6559]
during local development, the need to reset network happens frequently, and requires a reset of account to prevent invalid block numbers/nonces

create a setting in advanced settings that when selected will automatically call resetAccount, saving developers the steps of going into settings -> advanced settings -> reset account

**Comment by bdresser** [comment]
@jennypollack how would we know when to call "reset" ? 

relates to https://github.com/MetaMask/metamask-extension/issues/5067 ( a blunter solution )

**Comment by jennypollack** [comment]
naive approach could be to trigger the call upon Internal Error which throws in the console on my network reset
`code: -32603
message: Error: JsonRpcEngine - response has no error or result for request:`

`originalError: InternalError}
error:
code: -32603
message: undefined`

**Comment by jennypollack** [comment]
see #5067 for potential easier win

**Comment by Gudahtt** [comment]
I'm closing this in favour of #2373, which seems to be the same request essentially.
