### ISSUE TITLE
window.ethereum Not Set When Trying To Access File With Browser

### ISSUE THREAD

**Issue by Aphrodites1995** [MetaMask/metamask-extension#6562]
**Describe the bug**
Window.ethereum is not set when I try to open the webpage which is in my documents. I tried Chrome and Firefox, neither set window.ethereum.

**To Reproduce**
1. Get the source code of a dapp.
2. Open the index.html in a browser with metamask.
3. Look at an error saying window.ethereum not set.

**Expected behavior**
Window.ethereum should be set.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: MacOS
 - Browser Chrome and Firefox
 - MetaMask Version 6.4.1

**Additional context**

**Comment by tmashuang** [comment]
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#globe_with_meridians-https---web-server-required
