### ISSUE TITLE
Hiding Transaction Error: Exception Thrown in Contract Code

### ISSUE THREAD

**Issue by hieudoan2609** [MetaMask/metamask-extension#6563]
I'm getting the error "Transaction Error: Exception Thrown in Contract Code. " when I transfer ERC20 tokens, I need to send 2 transactions, one to approve and another to actually transfer it, if I wait for the approving transaction to be mined before sending the transfer, I won't get any error, but if I send the transfer transaction immediately after receiving the approving transaction's hash, I get the error, but waiting for a minute for the mine receipt is a very poor user experience, is there a way to hide this error? It seems just a view problem and I don't want the end users to see it.

**Comment by tmashuang** [comment]
The error `Transaction Error: Exception Thrown in Contract Code` is not very descriptive error. In general, it could be a gas error. 

> if I send the transfer transaction immediately after receiving the approving transaction's hash, I get the error, but waiting for a minute for the mine receipt is a very poor user experience

My understanding is that if a token approval is not mined yet, then the balance of the recipient account is not verify to have a balance. Thus, the transfer for any amount other that 0 would not work if the balance of the account is not verified.

**Comment by hieudoan2609** [comment]
I also understand that the error is caused by the approval not having been mined, but these are 2 consecutive transactions with guaranteed order, and all of the transactions marked by MetaMask initially as "errors" eventually went through successfully anyway, I wonder is there a way to bypass this checking or perhaps hide the error?

**Comment by danfinlay** [comment]
Closing in favor of #9419
