### ISSUE TITLE
Metamask keeps loading while send - loading for gas price

### ISSUE THREAD

**Issue by kunalransing** [MetaMask/metamask-extension#6564]
**Describe the bug**
When we try to send, it stuck while loading gas price.
When I inspect the browser I saw issue on console like

```
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': The origin of 'https://dev.blockscale.net/api/' should be same as 'chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn'
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at Object.fetchBasicGasEstimates (ui.js:1)
    at t.value (ui.js:1)
    at e.notifyAll (libs.js:1)
    at p.close (libs.js:1)
    at p.closeAll (libs.js:1)
    at perform (libs.js:1)
    at g.perform (libs.js:1)
    at g.perform (libs.js:1)
    at Object.x [as flushBatchedUpdates] (libs.js:1)
    at l.closeAll (libs.js:1)
    at l.perform (libs.js:1)
    at Object.batchedUpdates (libs.js:1)
    at Object.batchedUpdates (libs.js:1)
    at dispatchEvent (libs.js:1)
    at HTMLDocument.r (ui.js:1)
```

```
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': The origin of 'http://ethgasstation.info/json/' should be same as 'chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn'
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at Object.fetchGasEstimates (ui.js:1)
    at ui.js:1
```

**Expected behavior**
It should show a gas price. Also, allow to set the custom gas price.

**Screenshots**
![image](https://user-images.githubusercontent.com/10609502/57226622-0f0f2200-702d-11e9-8174-90f96659e3a2.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Chrome Version 63.0.3239.132 (Official Build) (64-bit)
 - MetaMask Version 6.4.1

**Comment by bdresser** [comment]
@kunalransing does this also happen on the normal "Send ETH" screen, before you click in to "Advanced Options" ? 

cc @danjm @tmashuang CORS for ethgasstation?

**Comment by kunalransing** [comment]
Yes. For normal send also its loading for gas fee.

**Comment by tmashuang** [comment]
Please show the Network Tab in the dev console to see the how the api call is being handled?

**Comment by kunalransing** [comment]
I don't see api call. BTW I will try with latest Chrome version.
![image](https://user-images.githubusercontent.com/10609502/57351421-7937dc00-717f-11e9-955f-957a62d3c53f.png)

**Comment by kunalransing** [comment]
Its working fine on latest version of Chrome - Version 74.0.3729.131 (Official Build) (64-bit).

**Comment by bdresser** [comment]
Ok. Looks like this might be the same issue as #6421 based on what I can see in the "amount" field. Will add a note to this issue that it could manifest as blocking gas fees. Closing this for now - let us know if you have trouble again.
