### ISSUE TITLE
ui.js:1 Uncaught (in promise) Error when connecting to parity node

### ISSUE THREAD

**Issue by drgorb** [MetaMask/metamask-extension#6572]
**Describe the bug**
`Uncaught (in promise) Error: EthQuery - RPC Error - Error` when trying to connect to custom RPC.
The node in question is a Parity node started with 
`parity --chain=/home/parity/tobalaba.json --unsafe-expose`

this seems to be the same issue as https://github.com/MetaMask/metamask-extension/issues/5507 but it still happens

**To Reproduce**
1. download https://bitbucket.org/shareandcharge/contracts/src/platform-v1/network/tobalaba.json
2. run `parity --chain=path-to/tobalaba.json --unsafe-expose`
3. try to connect with metamask

Alternatively you can 
1. try to connect to `http://node38817-test-cpo-api.hidora.com:11076`

**Expected behavior**
The node should connect

**Browser details (please complete the following information):**
- Mac OSX 10.14.4
- Chrome 74.0.3729.108 (Official Build) (64-bit)
- Metamask 6.4.1

**Additional context**
log:

```
Uncaught (in promise) Error: EthQuery - RPC Error - Error: JsonRpcEngine - response has no error or result for request:
{
  "id": 8836577776601637,
  "jsonrpc": "2.0",
  "params": [
    "0xa64c13",
    false
  ],
  "method": "eth_getBlockByNumber",
  "origin": "MetaMask"
}
    at background.js:1
    at n (background.js:1)
    at i (background.js:1)
    at background.js:1
    at background.js:1
    at background.js:1
    at background.js:1
    at c (background.js:1)
    at s (background.js:1)
    at background.js:1
    at background.js:1
    at background.js:1
    at background.js:1
    at c (background.js:1)
    at s (background.js:1)
    at background.js:1
    at background.js:1
    at background.js:1
    at m.run (background.js:1)
    at p (background.js:1)
    at ui.js:1
    at ui.js:1
    at r (ui.js:1)
```

**Comment by Eegee** [comment]
I just found out by using curl on the command line that it works with leaving out "origin": "MetaMask" in the JSON request data.
So I suppose Parity doesn't like this origin element?
