### ISSUE TITLE
When sending tokens to smart contract address MetaMask blocks the transaction

### ISSUE THREAD

**Issue by ageyev** [MetaMask/metamask-extension#6574]
It's the wrong behavior. When sending tokens to smart contract address should show a warning as described on https://metamask.zendesk.com/hc/en-us/articles/360020028092-What-is-the-known-contract-address-warning- , but **NOT** block transactions. 
*If the user does it intentionally, he should be able to do it.*

There are many scenarios where smart contract can receive its own tokens. 
See for example xEUR tokens contract: https://github.com/EthereumCommonwealth/Auditing/issues/231

**Comment by bdresser** [comment]
Warning was added (as described) in https://github.com/MetaMask/metamask-extension/pull/6058

This may have been a regression from https://github.com/MetaMask/metamask-extension/pull/6445 - @chikeichan could you take a look?
