### ISSUE TITLE
Metamask doesn't connect to Dexs like Tokendex and Etherdelta

### ISSUE THREAD

**Issue by carvena7** [MetaMask/metamask-extension#6579]
i get a message on Tokendex and etherdelta that metamask is installed but i'm not logged in  even though i am logged in. I tried everything: reinstalling metamask, changing from main net to test net and back to main net. It's weird because metamask works on tokenjar and deltafork. Please help

Ty

**Comment by carvena7** [comment]
<img width="770" alt="Capture d’écran 2019-05-08 à 16 38 05" src="https://user-images.githubusercontent.com/50413910/57384091-3b9f7700-71b0-11e9-8323-cc5e41ea3be8.png">

**Comment by carvena7** [comment]
Oh and i just noticed that the two exchanges i'm having trouble to connect with do not ask me to connect via metamask po-up, like with the other two exchanges.

**Comment by tmashuang** [comment]
I believe this is an issue with each individual site. [Github/Etherdelta](https://github.com/etherdelta/etherdelta.github.io) hasn't been maintained since 08/2018, and [GithubTokenDex](https://github.com/tokendex/tokendex.github.io) 09/2018. Will reopen if there is an issue on our end.

**Comment by carvena7** [comment]
i think so too… does your metamask wallet work on those sites ?


Le 8 mai 2019 à 17:15, Thomas Huang <notifications@github.com<mailto:notifications@github.com>> a écrit :


Closed #6579<https://github.com/MetaMask/metamask-extension/issues/6579>.

**Comment by tmashuang** [comment]
Only if Settings > Security & Privacy > Privacy Mode is disabled.
