### ISSUE TITLE
Incorrect (huge) balance running on RPC 127.0.0.1:8545, mainnet

### ISSUE THREAD

**Issue by evertonfraga** [MetaMask/metamask-extension#6580]
**Describe the bug**
I am fully synced on Geth light mode, mainnet, connecting via RPC, though my ETH balance is far from what it was supposed to be.

```
./geth --syncmode light --cache 2048 --rpc --rpccorsdomain moz-extension://e582a415-cf54-468e-9b4b-f32b576f7bf7,chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn
```

**To Reproduce**
1. start geth 1.8.27 with the aforementioned command
1. Have it synced
1. Have the account balance updated (generally open the expanded view and/or wait a little while)
1. `geth attach`
1. `eth.getBalance('[MY_ADDRESS]')` gives me accurate balance
1. Reset the account 
1. Same huge ETH balance

**Expected behavior**
Correct balances shown.

**Screenshots**
![Kapture 2019-05-07 at 11 53 25](https://user-images.githubusercontent.com/47108/57314848-74602300-70c0-11e9-9a35-8952f2ff4234.gif)
![image](https://user-images.githubusercontent.com/47108/57314923-90fc5b00-70c0-11e9-877d-63b704d51138.png)

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - MetaMask Version: 6.4.1

**Additional context**

**Comment by ryanio** [comment]
I am getting the same behavior, my mainnet balance is `0.1915 ETH` but it is showing `23570985008687907853269984665631340667420.7292 ETH` via the Localhost:8545 network option

**Comment by evertonfraga** [comment]
I tested the same RPC method in Postman and MyEtherWallet CX, and values are correct.

**Comment by evertonfraga** [comment]
Also happening in local RPC with Rinkeby
![image](https://user-images.githubusercontent.com/47108/57456357-579c2a80-723b-11e9-9ba1-d1d40bc8ee3b.png)

Using the console, I can see a bunch of RPC errors, will try to pinpoint the issue from here:
![image](https://user-images.githubusercontent.com/47108/57456367-5f5bcf00-723b-11e9-8764-8101f65f912f.png)

**Comment by danfinlay** [comment]
> My hunch is that metamask fails to handle this kind of response from Light Client, when it does not have the immediate answer

Thanks for including the error message, this will help us greatly to investigate/fix.

**Comment by tmashuang** [comment]
Unfortunately, I was unable to get the issue outcome of large value, but I didn't get the `no suitable peers available`. Will try attempts to get this error message, might have to constantly remove my database and retry. Curious if you have every set up a private ethereum chain with your address and pre-allocate Ether to your account then swapped back to the main network?

**Comment by tmashuang** [comment]
Possible related to https://github.com/ethereum/mist/issues/3393

**Comment by evertonfraga** [comment]
Hi @tmashuang, do you have any test suite (or strategy) to mock RPC methods?

**Comment by tmashuang** [comment]
Since we primarily use Infura's API, I think we use https://github.com/nock/nock to mock those calls.

**Comment by evertonfraga** [comment]
How to (hopefully deterministically) get the `no suitable peers` error:

Start geth light client with the `--nodiscovery` flag. It'll have no means to fetch account balances.

`geth --syncmode light --cache 2048 --rpc --rpccorsdomain='*' --rpcapi "db,eth,net,web3" --vmodule="rpc/*=5" --nodiscover`

```
{
	"jsonrpc":"2.0",
	"method":"eth_getBalance",
	"params":[
		"0xADDRESS", 
		"latest"
	],
	"id":1
}
```

**Comment by evertonfraga** [comment]
> Curious if you have every set up a private ethereum chain with your address and pre-allocate Ether to your account then swapped back to the main network?

no, I haven't

**Comment by tmashuang** [comment]
I am getting the error,`no suitable peers`, now with `--nodiscover`. Still unable to get a large balance. I don't want to ask to `removedb` and resync, but I don't see where this bad balance could be coming from.

**Comment by evertonfraga** [comment]
I just produced a local build of MM 6.4.1 (version tested in the first place) and I got the huge balance:
<img width="834" alt="Screen Shot 2019-05-23 at 5 21 13 PM" src="https://user-images.githubusercontent.com/47108/58287571-59a7d280-7d7f-11e9-8675-ec0d3cb1360e.png">

I don't know what changes were made up to 6.5.3, and I tend to believe it might have been fixed. Can you take a spin on 6.4.1 just as sanity check?

**Comment by tmashuang** [comment]
No large balance for me on v6.4.1.

**Comment by evertonfraga** [comment]
It does not even happen with all accounts, as shown:
![image](https://user-images.githubusercontent.com/47108/58289137-852cbc00-7d83-11e9-9b6f-10080bd207cb.png)

so I guess this is either a super difficult issue to reproduce or it's gone for good. We can close it for now and should we run into that issue again, I'll revive it. 

Thanks @tmashuang

**Comment by tmashuang** [comment]
Oh wait this is an imported account? Where was this account created from?

**Comment by evertonfraga** [comment]
json file, created from geth

**Comment by tmashuang** [comment]
Ok I got it now from the account created in Geth, will investigate the root cause.

**Comment by evertonfraga** [comment]
Friendly bump @tmashuang. any conclusion? LMK if you need any help from our side.

**Comment by tmashuang** [comment]
@evertonfraga We are currently investigating this issue, and have theories and potential fixes. Would you be willing to submit your state logs to support@metamask.io with this issue number? Or rather continue on this thread with specific Q/As?

**Comment by evertonfraga** [comment]
Hi @tmashuang, I'd rather continue on this thread. please send your Qs :)

**Comment by rrodriguezreche** [comment]
Dropping by just to say that this still happens. I 've tried to use a custom RPC pointing to my local geth light node and I am receiving distorted values on my ETH balance.

I can see the correct value when connecting to DApps like zapper.fi, but have not checked if they are getting it through their backend or through web3 calls.

**Comment by danfinlay** [comment]
If you open the background devtools ([guide here](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue)), you should be able to see the network requests that fetch the balance. This could allow you to confirm that MetaMask is receiving the correct value and the fault is with us. If so, you could also copy the request & its response here for us to look at, to see if maybe something about the payload causes a wrong interpretation.

**Comment by tdickman** [comment]
I am running into a similar issue - unsure if it should be a separate ticket since it's surfacing a bit differently.

When connecting to a custom rpc (my private geth node running version `1.10.3-stable`), metamask shows an incorrect ETH balance - instead it is showing the USD value for the ETH value.

For example, if I have a 1 ETH balance in a wallet, it will show an ETH balance of 2538.09 and a USD balance of $2538.09 (when my actual balance is 1 ETH).

![image](https://user-images.githubusercontent.com/808296/120210311-a2f84b80-c1fd-11eb-85d0-a5beaec369e0.png)

**Comment by dorinburcea** [comment]
> I am running into a similar issue - unsure if it should be a separate ticket since it's surfacing a bit differently.
> 
> When connecting to a custom rpc (my private geth node running version `1.10.3-stable`), metamask shows an incorrect ETH balance - instead it is showing the USD value for the ETH value.
> 
> For example, if I have a 1 ETH balance in a wallet, it will show an ETH balance of 2538.09 and a USD balance of $2538.09 (when my actual balance is 1 ETH).
> 
> ![image](https://user-images.githubusercontent.com/808296/120210311-a2f84b80-c1fd-11eb-85d0-a5beaec369e0.png)

I have similar issue this is the amount it says is going to be send when I typed 1 ETH only. 

![image](https://user-images.githubusercontent.com/21106256/120921584-0803e380-c6cd-11eb-89bc-deb04f0650f0.png)

**Comment by hiteshSharma6** [comment]
@tdickman, @dorinburcea, @danfinlay, @tmashuang, I also got into this issue.

But when I added value to **Currency Symbol**, it starting showing the correct ETH value. Also, from seeing these values, it seems that they are ETH values converted to FIAT value, and it's probably dollars.

I think that this behaviour is because of some issue in Metamask itself.

**Comment by tdickman** [comment]
This does appear to be fixed for me with the latest version of geth and metamask.
