### ISSUE TITLE
Address Book Send Flow

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6585]
Part of #5030 and counterpart to #6365

This issue is for implementing the part of the address book feature that touches the "Send" flow.

Designs [here](https://www.figma.com/file/giaffk6qfl9eMMjoPFjJkGnt/Address-book?node-id=0%3A1)

Get final signoff from @cjeria before beginning dev work.

**Comment by danjm** [comment]
Do we have final sign off from @cjeria?

**Comment by bdresser** [comment]
Most updated designs are in this [Figma](https://www.figma.com/proto/giaffk6qfl9eMMjoPFjJkGnt/Address-book?node-id=42%3A195&viewport=-334%2C800%2C1.4132124185562134&scaling=min-zoom)

I will schedule design handoff for early next week

@cjeria @danjm

**Comment by cjeria** [comment]
Address book input search bar states. Also available in the figma file.

<img width="1599" alt="Address input search bar states" src="https://user-images.githubusercontent.com/597770/58283740-548a5980-7d66-11e9-852b-c6ab936f74d2.png">
