### ISSUE TITLE
"ALERT: Not enough funds" makes Metamask unusable on PoA private nets

### ISSUE THREAD

**Issue by nikita-fuchs** [MetaMask/metamask-extension#6588]
**Describe the bug**

"ALERT: Not enough funds"

prevents executing functions on private PoA net that doesn't charge TX fees (that parity's implementation)

**To Reproduce**
1. Spawn private PoA net with free transactions
2. Try calling a function with 0 balance
3. Send Button will remain greyed out

**Expected behavior**
MetaMask lets the user send the transaction.

**Browser details (please complete the following information):**
 - Platformagnostic

**Comment by tmashuang** [comment]
I am going to close this issue as this does not seem to reference any additional tx information like the gas price and the node's gas price.
