### ISSUE TITLE
Progressively load gas estimations on confirm screen

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6591]
Right now, we block rendering the confirmation screen on gas estimation. We should render the screen, then fill in gas estimation inline to improve the loading time of confirmation screens.

**Comment by PhABC** [comment]
Please also allow for manual imput even if gas estimation and gas price aren't loaded. Right now, I personally can't manually set the gas price as my confirmation screen is stuck, as follow.

![image](https://user-images.githubusercontent.com/9306422/57573615-6c71ed00-73f8-11e9-994e-0aae9ade039e.png)

I am unable to manually change the gas price and gas limit value until the charts are loaded, which takes a very long.
