### ISSUE TITLE
Seed phrase backup reminder - just prior to uninstall

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6601]
**What problem are you trying to solve?**
Some users prefer to uninstall MetaMask to move to another wallet or to simply re-install MetaMask while troubleshooting.  They may not have their seed phrase backed up and realize they cannot recover their wallets when it is sometimes too late.

**Describe the solution you'd like**
A popup notification prior to uninstalling MetaMask, asking the user to make sure they have their seed phased written down, and simple instructions where to find it: Click the circular icon on the top-right corner, select Settings, Security & Privacy, Reveal Seed Words.

**Additional context**
Request additional feedback from the user, why they were uninstalling, is it to reinstall on another browser, re-install to troubleshoot an issue, switching to a different offering (if so, which?), causing issues with browser, if so, what?, etc.)

**Comment by tmashuang** [comment]
I think this for us it would be somewhat difficult since we don't store those user seed phrases on a server. Chrome does provide https://developer.chrome.com/extensions/runtime#method-setUninstallURL.

**Comment by Gudahtt** [comment]
Closing, as I believe this is impossible to do with the extension API. If a user chooses to uninstall MetaMask, the most we could do is use `setUninstallUrl` to open a page, by which time it will have been too late to as the user to backup anything.
