### ISSUE TITLE
Unable to call ERC20::approve on the Ropsten Test Network

### ISSUE THREAD

**Issue by loriopatrick** [MetaMask/metamask-extension#6602]
Unable to call ERC20::approve on the Ropsten Test Network.

Getting error `ALERT: Trying to call a function on a non-contract address.`

**To Reproduce**
1. Go to https://ropsten.etherscan.io/address/0x603bc175a26c8f74eaf9bc6ef5dd288afb6fc4b8#writeContract
2. Set _sender to 0xfd2288b96643fe5f75917df6d846998d197bbcdb
3. Set _value to 100000000
4. Applying transaction fails

**Comment by tmashuang** [comment]
Seems that Etherscan isn't providing us the `gas` in tx params for their contract writes. Everywhere else I see, Idex, Remix, etc., are providing the `gas` param for the token send.
