### ISSUE TITLE
transaction is not resolving / rejecting / ignores finally

### ISSUE THREAD

**Issue by paulhaem** [MetaMask/metamask-extension#6609]
**Describe the bug**
Following code does not resolve. MetaMask asks for confirming the transaction and sends a success message after the successfull transaction. However, the promise does neither get resolved, nor rejected. Even finally will be ignored. Using the latest version of web3.js and trying rolling back, but without success. The contract is deployed on the Ropsten network, however I tested the same scenario with the Kovan network with the same results.

```
this.$store.state.contractInstance().methods.registerAsPatient().send({from: this.web3.coinbase})
  .then((response) => {
    console.log('registered as patient', response);
  })
  .catch((error) => {
    console.error(error);
  })
  .finally(() => {
    this.pending = false;
  })
```
Added following options to the web3 constructor.
```
  const options = {
    transactionConfirmationBlocks: 1,
    transactionBlockTimeout: 5
  }
``` 

**Expected behavior**
Resolving / rejecting of the promise after the success / failure of the transaction.

**Browser details:**
 - OS: Windows 10
 - Browser Chrome 74.0.3729.131 
 - MetaMask Version 6.5.1

**Comment by tmashuang** [comment]
Please provide the Contract instance and web3.js version to reproduce.

**Comment by paulhaem** [comment]
The address of the contract on the ropsten network: 0xe8a9134a5498e95b21d6ef5bf6de346f6fb7e160
I used the latest web3.js version 1.0.0-beta.55 and I also tried 1.0.0-beta.48 after several issues suggesting to roll back.

**Comment by tmashuang** [comment]
I am going to close this, the information provided did not give me enough information to easily reproduce the behavior and the enviornment, missing the contract abi. If you are still having trouble you can post your issue on general developer forums like https://ethereum.stackexchange.com/.
