### ISSUE TITLE
Can't remove account.

### ISSUE THREAD

**Issue by wukoo** [MetaMask/metamask-extension#6611]
**Describe the bug**
Can't remove account. It just hang ther for seconds.

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: chrome
 - MetaMask Version: 6.5.1

**Comment by brunobar79** [comment]
Should be fixed via #6613

**Comment by asymmetric** [comment]
How does one remove an account?

**Comment by bdresser** [comment]
@asymmetric for imported or "loose" accounts, there's a small X on the right side of the account in the drop-down menu in the top-right of the extension.

MetaMask doesn't currently support removing standard accounts (created by clicking the "add account" button)

Closing this, as the original issue is resolved.
