### ISSUE TITLE
It automatically upgrades to v6.5.1 and 'enable()' does not work,when wallet locked

### ISSUE THREAD

**Issue by kongyes** [MetaMask/metamask-extension#6612]
**Browser details (please complete the following information):**
 - OS: [ Windows10]
 - Browser [chrome]
 - MetaMask Version [. 6.5.1]

**Comment by bdresser** [comment]
@kongyes I can't reproduce - on 6.5.1 and `enable()` is working fine, even when the wallet is locked. Could you give us some specific steps to reproduce?

**Comment by danfinlay** [comment]
This can happen if the extension updated in the background but the page has stayed open during the update, breaking the communication channel.

Reloading the page should fix this.
