### ISSUE TITLE
ethereum.enable() doesn't open metamask when logged out

### ISSUE THREAD

**Issue by tangelo313** [MetaMask/metamask-extension#6618]
Since the v6.5.x, Metamask fails to open the login screen, when the user is logged out and ethereum.enable() is invoked. I've tested it only on Ropsten Test Network.

**Expected behavior**
ethereum.enable() should open the metamask login screen when the user is logged out.

**Browser details (please complete the following information):**
 - Windows 10
 - Latest stable Chrome and Firefox
 - MetaMask Version 6.5.2

**Comment by karlito636** [comment]
Same here. It was working fine till 2 days ago.

**Comment by bitpshr** [comment]
Thanks for reporting @tangelo313, we are investigating now and should have an update soon.

**Comment by dpazdan** [comment]
Related support inquiry: 19370
