### ISSUE TITLE
ethereum.enable() doesn't throw when user rejects popup.

### ISSUE THREAD

**Issue by nameskang** [MetaMask/metamask-extension#6631]
**Describe the bug**
Calling ethereum.enable() while user has privacy mode enabled does not throw when he doesn't allow the dapp to view his account address. Instead it returns normally but the accounts array is undefined. Cannot catch user denying access via promise .catch() nor standard try..catch.

**To Reproduce**
1. Call ethereum.enable() making sure to handle both success and fail cases (example code [here in the docs](https://github.com/MetaMask/metamask-docs/blob/master/03_API_Reference/01_Ethereum_Provider.md#ethereumenable))
2. Reject the metamask popup
3. See that ethereum.enable() did not throw and returned array is undefined

**Expected behavior**
Acording to docs, calling ethereum.enable() while user has privacy mode enabled should throw when he doesn't allow the dapp to view his account address.

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome and Brave
 - MetaMask Version: 6.5.3 (latest)

**Additional context**
Problem can be observed here: https://codesandbox.io/s/5zrjm

**Comment by nameskang** [comment]
I tested previous versions and it looks like it has been broken since 6.5.0. Version 6.4.1 is the last one with expected behaviour.

**Comment by danfinlay** [comment]
Good catch and documentation, thank you! Will be fixed in the next release, early next week.
