### ISSUE TITLE
ALERT: [ethjs-rpc] rpc error with payload {"id":3601945497860,"jsonrpc":"2.0","params" - Error: invalid sender

### ISSUE THREAD

**Issue by basemdabbour** [MetaMask/metamask-extension#6636]
Hello,
I have a MetaMask issue in sending a transaction or even tokens between 2 accounts
The error message like the following:

> **ALERT: [ethjs-rpc] rpc error with payload {"id":3601945497860,"jsonrpc":"2.0","params":["0xf8aa038502540be40083012cbe945fe591d52304254a13363acc304c1766bce1eafd80b844a9059cbb000000000000000000000000823e25ab5ef0f1dc43ac99c4187338d123b6e470000000000000000000000000000000000000000000000000000000000000000a26a0b2ca867044caa2d2e5f4840371077ce3ac4cf421b0f016b09e29c87fb3437b0ba034c1e34c402ed21b07a47efbcabcf603cccf345721ab302ba3ca3dc4df8fea8a"],"method":"eth_sendRawTransaction"} Error: invalid sender**

So i am working on a small project to build a private blockchain using geth eth client, I couldn't export the private key from the accounts created inside my private node so what I did is creating  a new account in MetaMask and import the private key of that account to the list of  accounts in my private blockchain, I was able to execute commands to send transactions (eth or tokens) btw accounts and the result will automatically reflect on MetaMask balances, for example if I send 1 eth from account x to account y by using geth terminal, the transaction will be created and sealed in a newly mined block, and the result will reflect on MetaMask wallets, so everything so far so good, however when I try to use MetaMask to send transaction between account x and account y, it's giving an error that I already mentioned above. can someone help regarding this matter ??

Please note that i used Remix to execute the smart contract (create ERC20 token) on the private blockchain and then i used the contract address to import the tokens into MetaMask account and it works perfectly!!, but sending these tokens or eth directly on MetaMask is the main issue

- Genesis Block:

```
{
  "config": {
    "chainId": 15,
    "homesteadBlock": 0,
    "eip155Block": 0,
    "eip158Block": 0
    
  },
  "difficulty": "0x20000",
  "gasLimit": "0x8000000",
  "alloc": {

	}
  
}

```
- I tried again by matching Networkid with Chainid, but still same error, also i set the EIP to 0 and nothing changed.
- I guess the problem is not related to a smart contract or the version of "pragma solidity" because it didn't work on sending eth as well. 
- MetaMask is well connected to my Private Blockchain via RPC connection on port 8455, again everything I do on geth client terminal reflecting and updating the balances on MetaMask,  but sending direct transactions or tokens between the accounts is the main problem and couldn't solve it even after I tried many solutions here.

**Comment by Lee-jaejin** [comment]
I think that it's kind of account selecting error.
I tried to send some token or made a transaction via solidity functions but i received same error with you.
So I reinstalled metamask extension version 6.2.0.
And than It worked well.

**Comment by basemdabbour** [comment]
@Lee-jaejin Thanks for your answer but I have the updated version 6.5.3 which probably work better than older version 6.2.0 right?
 I will try it with 6.2.0 now and will update you on it

**Comment by basemdabbour** [comment]
@Lee-jaejin  everything works perfectly after reinstalling MetaMask 6.5.3 again no matter what kind of version it is. still, I don't know what was the problem in the beginning and why reinstalling MetaMask solved the error!!

**Comment by Lee-jaejin** [comment]
@basemdabbour Thanks for your update. I've published a token at March 8th. That's why i recommended version 6.2.0. I will try to reinstall 6.5.3 and test it.

**Comment by selvatica** [comment]
Hi, I had the same issue with Metamask 7.7.4
Reinstalling Metamask solved the error.  I was not able to reproduce the error. BUT: Strangely the error occurred only in combination with Ganache and did not occur with the same contract on Ropsten and Rinkeby. Also using the old .json files from server did not solve the error. Maybe this info might help somebody.

**Comment by nanthan** [comment]
Hi, I use MetaMask version 7.7.8 I rarely face this problem but when it occurred, I solved by switching to another network and go back to the former network.

**Comment by dupies** [comment]
Wow, I don't know what caused the wired error, reinstalling Metamask certainly helped me also.

**Comment by rexdavinci** [comment]
> Hi, I use MetaMask version 7.7.8 I rarely face this problem but when it occurred, I solved by switching to another network and go back to the former network.

This worked for me
