### ISSUE TITLE
Translator issue possibly causing tokens to not load

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6639]
**Describe the bug**
Some users have reported an infinite "loading tokens" message when trying to view their token list in MetaMask.  While some have confirmed that this was a network related issue, others (see screenshot below), have reported it could be related to an issue with the translations.

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/58189199-a1dfcb80-7c7f-11e9-958e-3471f8c14bac.png)

**Browser details (please complete the following information):**
 - example in screenshot, the user had the language set to Dutch.

**Additional context**
issue ticket: 19110

**Comment by whymarrh** [comment]
Unfortunately this is almost certainly not an issue with the translations. A lot of our translations aren't 100% (close but not quite 100%). The warnings shown are expected and safe. I'm going to close this for now and we can open up new issues as we get related details.

**Comment by dugwood** [comment]
Hit the same issue. In the end, I've just did:

- exported my 12 words sentence
- remove the extension from Chrome
- added the extension back (without even restarting Chrome)
- entered my 12 words

and it's working again (I can see ETH and another token). So there must be something in the configuration that blocks the loading of tokens. I can't know what it was as the extension was removed.
