### ISSUE TITLE
Update GABA to match new preferences controller

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#6642]
Based on #6258 we need to update GABA to match the new preferences controller (or lack thereof)

(actual work is on GABA repo but including here to track this sprint)

**Comment by bdresser** [comment]
@bitpshr is this still in progress?

**Comment by brad-decker** [comment]
We still intend to migrate controllers into metamask/controllers, however, the order of operations and action plan has likely changed. We will revisit issue creation in the new year when we target this work.
