### ISSUE TITLE
MetaMask goes heavy on the Gas

### ISSUE THREAD

**Issue by LeotheGit** [MetaMask/metamask-extension#6643]
The two attached screenshots show MetaMask estimates of the amount of gas required to perform, in each case, the same identical token transfer.  In one case the cost amounts to a few cents, while in the other the cost is several dollars.  The value of the tokens to be transferred was itself just a few $100 in total.  Clearly something went badly wrong with the gas estimation.

OS, Browser & MetaMask details :==>
 - OS:  Windows 10 Pro v.1809
 - Browser:  Chrome, Version 74.0.3729.157 (Official Build) (32-bit)
 - MetaMask:  Version 6.5.3

![MetMask_Token-Transfer-cost-2](https://user-images.githubusercontent.com/49049393/58212381-dd65ae80-7cee-11e9-9b4f-db907630b5ac.jpg)
![MetMask_Token-Transfer-cost-1](https://user-images.githubusercontent.com/49049393/58212382-dd65ae80-7cee-11e9-811f-f6381e143980.jpg)

**Comment by Gudahtt** [comment]
We now rely upon the network for our initial gas estimates, and we use ETH Gas Station for our suggested gas prices in the UI while on mainnet. I'll close this issue for now because the method of estimation used when this was reported has been removed.
