### ISSUE TITLE
QR Code Scanner doesn't support EIP-681

### ISSUE THREAD

**Issue by pedrouid** [MetaMask/metamask-extension#6651]
**Describe the bug**
QR Code Scanner fails to scan input fields on Send Transaction view when scanning QR Code contains an EIP-681 URI

**Example URI**
```
ethereum:0x46c69f4424043e720a704330748cf3c593656b9c
```

**To Reproduce**
1. Go to Send Transaction view
2. Click on QR Code scanner
3. Position QR Code in front of Webcam
4. QR Code scanner closes but input field is still empty

**Expected behavior**
Input field would be filled with recipient address

**Screenshots**
N/A

**Browser details (please complete the following information):**
 - OS: macOS Mojave v10.14.4
 - Browser:  Brave v0.64.76 / Chromium v74.0.3729.157 (Official Build) (64-bit)
 - MetaMask: v6.5.3

**Additional context**
[EIP-681: URL Format for Transaction Requests](https://eips.ethereum.org/EIPS/eip-681)

**Comment by hladik-dan** [comment]
@pedrouid Is this still an issue? Wanted to take this as my first issue but it seems to be already fixed.
Tried this on Brave 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit) / MetaMask: v7.3.1 and after scanning QR Code the address is filled correctly.

**Comment by tmashuang** [comment]
I believe EIP-681 is primarily for transactions, where as the example URI you provided is EIP-831 spec. I've recently tested this and have concluded that we do indeed support EIP-831, but not EIP-681. As the issue description is not an issue, I am going to close this issue. If EIP-831 is what you are referring to you can open a feature request for it.

**Comment by rcastag** [comment]
I agree eip-681 support is incomplete
![ethpay](https://user-images.githubusercontent.com/457134/188932730-359e5501-c159-4f8d-866c-bfcb8ac94c1d.gif)
