### ISSUE TITLE
The method eth_signTypedData_v3 does not exist/is not available

### ISSUE THREAD

**Issue by joaosantos15** [MetaMask/metamask-extension#6655]
**eth_signTypedData_v3 not working on Opera**

**To Reproduce**
1. Install Metamask from the opera extension store (https://addons.opera.com/en/extensions/details/metamask/)
2. Load a website which requests eth_signTypedData_v3
3. See error

**Expected behavior**
Metamask prompt to sign a message.

**Screenshots**
```js
{code: -32603, message: "Error: The method eth_signTypedData_v3 does not ex…lfaflkcgijnnflaine/scripts/background.js:8365:26)"}
code: -32603
message: "Error: The method eth_signTypedData_v3 does not exist/is not available
```

**Browser details (please complete the following information):**
 - OS: Windows, MacOS
 - Browser: Opera
 - MetaMask Version: 3.14.1

**Additional context**

I understand that this is an older version of Metamask, which probably does not support `eth_signTypedData_v3`. The reason why I'm opening the issue is that the fact there are two versions of metamask available for opera might be kind of confusing for users. Through the Opera store you get an old version of metamask. The only way to get the updated version is to do it through the Chrome store (which requires installing a plugin to enable chrome extensions on opera).
**Also, when opening Metamasks website on Opera and following the installation link, you get redirected to the old version.**

Would it make sense to remove the Metamask extension from the Opera store, so that users only have one path to installing Metamask and don't run into the risk of installing an old version?

(alternatively, is there any way to enable eth_signTypedData_v3 on the old version?)

Thanks!

**Comment by bdresser** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/5818

**Comment by tmashuang** [comment]
Closing due to lack of our support on Opera. We have not updated our version on the Opera store, and do not have any future plans to upload to the Opera store. This might change in the future. There are ways to install the latest MetaMask build from the Chrome Extension Store on Opera with an another extension, or using local builds of the project.
