### ISSUE TITLE
Add events for "speed up" interactions

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6660]
A recent reddit poster expressed frustration at frequently needing to speed up transactions.

Since we have the metrics system in place, this seems like a great subject for analysis:

- How often are users resorting to "speed up"?
- How long do they usually wait before doing it? (Can help inform us the eta that users might expect, or at least their frustration limit)

If users are speeding up very often at all, we should probably either increase our default gas suggestion, or even revisit our default gas suggestion algorithm.

**Comment by bdresser** [comment]
we don't have an event for "speed up" yet - added to master metrics sheet.

Cool if I repurpose this issue for adding them? 

cc @danjm
