### ISSUE TITLE
You guys seem to be creating a new standard rather than using Web3

### ISSUE THREAD

**Issue by nickjuntilla** [MetaMask/metamask-extension#6663]
It seems you guys are creating a new standard rather than having Dapps use the standard Web3 API. As a result I have tried to inject my own Web3 version into a mobile webview, but the application CryptoKitties does not recognize web3.currentProvider with and added wallet as enough for the application to run. You guys have implemented new methods like enable(), send() and sendAsync() as well as some we may not be aware of.

When I inject web3 with one wallet added to web3.accounts.wallet.add() I still get the message that the wallet is locked. If applications are using your custom methods then developers like me can't build providers for DApps without implementing your interfaces. Is there some way for me to inject a provider like the one that you are creating into a mobile webview so that apps like CryptoKitties can run in my application?

Also would you consider releasing a stand-alone library in the spirit of the community so that developers can inject a version of your ethereum object?

**Comment by bdresser** [comment]
Hey @nickjuntilla - we work closely with the community & other wallet teams to develop new standards. See [EIP 1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md) for a description of `enable()` and see [EIP 1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md) for `send()` and `sendAsync()`. 

You can find a complete list of these methods in our [developer documentation](https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#api-reference)

Check out https://github.com/MetaMask/web3-provider-engine or https://github.com/MetaMask/eth-json-rpc-middleware to help you compose your own provider using various middleware.

**Comment by nickjuntilla** [comment]
For anyone curious I found this 0x metamask provider implementation which can maybe be used with MetaMask/web3-provider-engine to create a metamask like ethereum object: https://0x.org/docs/subproviders#MetamaskSubprovider
