### ISSUE TITLE
Can't add AEUR to Metamask

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#6664]
I was using the [Augmint dashboard](https://www.augmint.org/account), took our a loan on my ETH and tried to add the Augmint EUR to my tokens, but all I saw was this:

![mm](https://user-images.githubusercontent.com/7106231/58569212-f530bb80-8235-11e9-8e5a-4ecbb132e907.jpg)

Why won't it show up? AEUR seems to be properly indexed on [Etherscan](https://etherscan.io/token/0xc994a2deb02543db1f48688438b9903c4b305ce3) and there I can see my balance.

**Comment by tmashuang** [comment]
We curate our own token list https://github.com/MetaMask/eth-contract-metadata/
