### ISSUE TITLE
Can you add a token converter feature to Metamask? (Binance or huobi traded tokens) For tokens traded on major exchanges.  for example ; IOST/ETH WAVES/ETH ZIL/ETH ......  An add-on to convert to etherium. (for withdraw) Would not it be nice?

### ISSUE THREAD

**Issue by Muzo354510** [MetaMask/metamask-extension#6666]
**What problem are you trying to solve?**
A short description of what you're trying to do. E.g., "My users need to wrap ETH, but they're intimidated by the confirm screen..." or "I'm trying to debug my application, and XYZ..."

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Try to also include any alternative solutions you've considered.

**Additional context**

**Comment by bdresser** [comment]
@Muzo354510 we do include ETH/token conversion rates: Go to `Settings > General > Currency Conversion`.

If we're missing a particular conversion you'd like to see, feel free to open a PR - the relevant tokens are listed here: https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/helpers/constants/infura-conversion.json
