### ISSUE TITLE
update address book schema to match 3box contact schema

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#6667]
rough proposed values based on [spec](https://github.com/3box/3box/pull/613/files)
`{
      "@context": "metamask",
      "@type": "Person",
      "name": "test username",
      "description": "this would be the memo field?",
      "identifier": [
        {
          "@type": "PropertyValue",
          "name": "DID",
          "value": "did:3:zhf02344f2d32dawe"
        },
        {
         "@type": "PropertyValue",
          "name": "Ethereum",
          "PropertyID": "chainId_1"
          "value": "0x123456781234567812345678123"
        },
      ]
    }
`

`{
      "@context": "metamask",
      "@type": "Frequently Used Contract",
      "name": "Ens Registrar",
      "description": "this would be the memo field?",
      "identifier": [
        {
          "@type": "PropertyValue",
          "name": "DID",
          "value": "did:3:zhf02344f2d32dawe"
        },
        {
         "@type": "PropertyValue",
          "name": "Ethereum",
          "PropertyID": "chainId_1"
          "value": "0xF0AD5cAd05e10572EfcEB849f6Ff0c68f9700455"
        },
      ]
    }`

**Comment by danfinlay** [comment]
Ideally the `@context` field would follow the json-ld spec, and probably be an object that points to our home page, and eventually to a docs page.

Example tutorial:
https://symfonycasts.com/screencast/api-platform/json-ld

**Comment by bdresser** [comment]
cc @oed ^

**Comment by oed** [comment]
The intention with the spec that @jennypollack linked was that one could just use the `schema.org` context. @danfinlay any reason to make it MetaMask specific?

**Comment by Gudahtt** [comment]
So this issue is to migrate our _internal state format_ to follow this contact spec? It's unclear to me what benefits this would have. I can see it being beneficial to use standard representations of this information where possible in order to make integrations with other software easier, but nothing is integrating _directly_ with our internal state, nor should anything need to.

**Comment by brad-decker** [comment]
I think we can close. we are deprecating 3box.
