### ISSUE TITLE
MetaMask provider sends multiple duplicate contract events to subscribers

### ISSUE THREAD

**Issue by cds-amal** [MetaMask/metamask-extension#6668]
**Describe the bug**
Multiple events are emitted when using the MetaMask provider and subscribing to a contract event. The number of duplicate events seems to be the product of the number of events subscribed and the number of events emitted by the solidity contract.

## To Reproduce
[Instructions are in this github repository](https://github.com/cds-consensys/mm-contract-event-dupes)

## Expected behavior
As a dapp developer, I want to be notified once per Solidity contract event.

### Single event emitted by Smart Contract
![Screen Shot 2019-05-30 at 9 04 45 AM](https://user-images.githubusercontent.com/2529600/58634750-1affa400-82ba-11e9-8d9b-c02221b598cf.png)

This screenshot shows side-by-side the result of clicking the `SimpleStorage` button which triggers one event, `SimpleSet` to be fired by the `SimpleStorage` Smart Contract. 
  * Chrome browser with MetaMask extension
      * There are 4 (4*1) events that the listener consumed. There are 4 events that were subscribed to, and the contract emits one event.
  * Chrome incognito sans MetaMask
    * There is only one event consumed, the single event emitted by the smart contract

### Two events emitted by Smart Contract
![Screen Shot 2019-05-30 at 9 09 39 AM](https://user-images.githubusercontent.com/2529600/58635249-636b9180-82bb-11e9-88e3-9f4055e7600a.png)

This screenshot shows side-by-side the result of clicking the `FimpleStorage` button which triggers two events, `FimpleSet` and `FimpleSet2` to be fired from the `FimpleStorage` Smart Contract ((don't judge, names are hard). 
  * Chrome browser with MetaMask extension
      * There are 8 (4*2) events that the listener consumed. There are 4 events that were subscribed to, and the contract emits 2 event. 
  * Chrome incognito sans MetaMask
    * displays the only two events the Smart Contract emitted

## Video
[![Duplicate contract events with MetaMask provider](https://img.youtube.com/vi/7KfEtBwCCVc/0.jpg)](https://www.youtube.com/watch?v=7KfEtBwCCVc)

## Browser details 
 - OS: OS X v10.14.5
 - Browser: Google Chrome: Version 74.0.3729.169 (Official Build) (64-bit)
 - MetaMask Version: 6.5.3

**Comment by cds-amal** [comment]
Using Firefox v67.0,
I verified the issue on firefox browser with MetaMask. 
The issue is not present when using Firefox's private browsing feature (sans MetaMask extension)

**Comment by bbjay** [comment]
I can reproduce this down to MetaMask v4.17.1 (did not try it with older versions) in Chrome and Brave.

When I deploy the contract to ropsten and use infura as a provider (no metamask involved),
events behave as expected.
When I connect MetaMask to ropsten and use it as provider, the issue appears again.
This leads me to the conclusion that the issue must lie inside MetaMask, and is not produced by Ganache (or other evm's).

**Comment by takahser** [comment]
I have the same issue with v5.3.5
Any help would be appreciated

**Comment by tmashuang** [comment]
@cds-amal What happens when you comment out all the other contracts, leaving just one? Are there multiple events being called when there is only one contract call?

**Comment by bbjay** [comment]
@kumavis could you have a look into this or give me a head start by pointing me to which package/component/method i should look into first?

**Comment by tmashuang** [comment]
@bbjay I believe the issue is in https://github.com/MetaMask/eth-json-rpc-filters. It looks like it's subscribing too all the events,  and once one is called returning all subscriptions. Maybe here, https://github.com/MetaMask/eth-json-rpc-filters/blob/master/subscriptionManager.js#L31?

**Comment by nikosft** [comment]
I am using v7.1.1 and the issue still exists

**Comment by TAN-ZIXUAN** [comment]
I am using v7.7.8 and chrome v80.0.3987.163 (Official Build) (64-bit). this issue still exists. it fires 4 times  for same event as i am listening to four different events using drizzle

**Comment by cds-amal** [comment]
@TAN-ZIXUAN you can try [this workaround](https://github.com/trufflesuite/drizzle/issues/7#issuecomment-610129156) if you're using drizzle and a middleware to extract the events

**Comment by TAN-ZIXUAN** [comment]
> @TAN-ZIXUAN you can try [this workaround](https://github.com/trufflesuite/drizzle/issues/7#issuecomment-610129156) if you're using drizzle and a middleware to extract the events

thanks!

**Comment by 5uperdan** [comment]
I created a Set to add events to. If the event has already been handled then I ignore it. Something like:

    let processed_events = new Set();
    contract.events.YourEvent({fromBlock: 'latest'}, function (error, event) {
        if (!error) {
            if (processed_events.has(event.transactionHash)) {
                return;  // ignore event since we've already handled it
            }
            // do something

            processed_events.add(event.transactionHash);
        } else {
            console.log(error);
        }
    });`
