### ISSUE TITLE
Add ability to right-click paste

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6672]
**What problem are you trying to solve?**
Some users prefer to right-click paste an address in the to: field, over  the keyboard command, or edit --> paste.

**Describe the solution you'd like**
Add the ability to paste when right-clicking on the field.  Currently, it allows copy only.

**Comment by crypts1** [comment]
how do i add ability to use paste function

**Comment by bdresser** [comment]
@dpazdan roughly how often does this come up?

**Comment by crypts1** [comment]
Hi Bobby it happens all the time only way to fool it is type in ox highlight it to remove then you can paste an address. Thanx DP

Sent from Mail for Windows 10

**Comment by dpazdan** [comment]
> @dpazdan roughly how often does this come up?

It's not super often but we do get a ticket from time to time with a user expressing difficulty from this.  The last user that experienced this talked about how he ended up typing the To: address manually 😬

**Comment by danjm** [comment]
This has been fixed with the recent addition of the address book feature
