### ISSUE TITLE
web3.eth.coinbase is null after ethereum.enable resolves.

### ISSUE THREAD

**Issue by losnappas** [MetaMask/metamask-extension#6674]
**Describe the bug**
As title.

**To Reproduce**
browser console
`ethereum.enable().then(addr => console.log(web3.eth.coinbase)) // logs null`

**Expected behavior**
I know I can grab the address from the `addr` variable, but wouldn't it make sense if the eth.coinbase was set as well?

**Browser details (please complete the following information):**
 - OS: ubuntu 19.04
 - Browser firefox 67.0
 - MetaMask Version 6.5.3

**Comment by bdresser** [comment]
This was addressed in https://github.com/MetaMask/metamask-extension/pull/6410 but looks like it's reappeared. We'll take a look..

**Comment by eolszewski** [comment]
Well, boys... looks like we got ourselves a regular hootenanny!

**Comment by tmashuang** [comment]
There can be alternative approaches to this such as: 

```
try {
 await ethereum.request({ method: 'eth_requestAccounts' })
 console.log(web3.eth.coinbase)
} catch (err) {
  if (err) console.log(err)
}
```
