### ISSUE TITLE
Add param to ethereum.enable

### ISSUE THREAD

**Issue by losnappas** [MetaMask/metamask-extension#6675]
**What problem are you trying to solve?**
In a login flow, you now need to
1. call ethereum.enable, which opens a popup.
1. call personal.sign with your message, which opens another popup.

**Describe the solution you'd like**
If ethereum.enable took a message to sign, and displayed it in the "connect" window, then that would make more sense for a login. It would then return the address and the signature.

**Comment by bdresser** [comment]
Agreed @losnappas, this would save a lot of extra confirmation screens. 

We're exploring a new Connect screen with some additional permissions in [this issue](https://github.com/MetaMask/Design/issues/58)

**Comment by vandan** [comment]
Thank you for opening this issue.
ethereum.enable is now deprecated so we are closing this issue.
