### ISSUE TITLE
Adding the celsius contract address in metamask adds a different contract address, why?

### ISSUE THREAD

**Issue by sticker592** [MetaMask/metamask-extension#6677]
**Describe the bug**
I'm trying to add celsius contract
https://etherscan.io/address/0xaaaebe6fe48e54f431b0c390cfaf0b017d09d42d as an erc20 token in metamask. I add it and the suspicious contract https://etherscan.io/address/0x6faaeb4050fc4b15b131eff2ea887de829e9fc3f appears in metamask and my coins do not exist with this contract.

**To Reproduce**
1. add first contrcact address listed
2. Click on menu, celsius ...., view in etherscan
3. Observe the second contract address from above

**Expected behavior**
Tokens from the first contract address appear in MM

**Browser details (please complete the following information):**
 - OS:  Windows
 - Browser chrome
 - MetaMask Version 6.5.3

**Comment by tmashuang** [comment]
It is recommend to remove that token address, and manually add the contract under the custom token.

**Comment by sticker592** [comment]
That's what I'm doing. I manually add the contract address and a different one gets added to the wallet

**Comment by tmashuang** [comment]
@sticker592 Can you confirm that when you add `0xaaaebe6fe48e54f431b0c390cfaf0b017d09d42d` that the Decimals of Precision is `4`?

**Comment by sticker592** [comment]
@tmashuang I've done it so many times I can tell you it is 18 and cel is locked as the name.

**Comment by tmashuang** [comment]
Weird since the Decimals of Precision is 4 when the correct address is added to the Token Contract Address

**Comment by sticker592** [comment]
![tok](https://user-images.githubusercontent.com/9032644/58825452-b3b85b80-85fb-11e9-8bd0-a3dc0425e042.png)

**Comment by sticker592** [comment]
I made a mistake
you can keep this closed
