### ISSUE TITLE
Ability to browse the directorys of metamask files enabled by default

### ISSUE THREAD

**Issue by OisinKyne** [MetaMask/metamask-extension#6682]
**Describe the bug**

When I navigate to moz-extension://9f1cd308-34c4-9445-b7e7-e6c69945d729/?name=test.eth

I am presented with a response:
```
300: jar:file:///Users/oisinkyne/Library/Application%20Support/Firefox/Profiles/2ajp0dua.default/extensions/webextension@metamask.io.xpi!/?name=test.eth
200: filename content-length last-modified file-type
201: 404.html 967 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: META-INF/ 0 Tue,%2001%20Jan%201980%2000:00:00%20GMT DIRECTORY
201: _locales/ 0 Tue,%2001%20Jan%201980%2000:00:00%20GMT DIRECTORY
201: background.js 2699780 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: contentscript.js 578033 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: error.html 1746 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: fonts/ 0 Tue,%2001%20Jan%201980%2000:00:00%20GMT DIRECTORY
201: home.html 399 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: images/ 0 Tue,%2001%20Jan%201980%2000:00:00%20GMT DIRECTORY
201: inpage.js 311433 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: libs.js 1880441 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: loading.html 934 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: manifest.json 1643 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: notification.html 459 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: phishing-detect.js 352316 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: phishing.html 3838 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: popup.html 469 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: trezor-usb-permissions.html 1221 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: ui.js 3733268 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: unsupport.html 1592 Fri,%2030%20Nov%201979%2000:00:00%20GMT FILE
201: vendor/ 0 Tue,%2001%20Jan%201980%2000:00:00%20GMT DIRECTORY
```
Which seems to be all of the files belonging to metamask. I can browse through all of the directories as I want, it's not the end of the world, but it would probably be better to not allow users to view the directory so easily, even if it is files that are local to my machine. 

**To Reproduce**
How I got to the behaviour was a bit unorthodox. I recently set my ENS name, and was trying to test what happens if I hit `domain-name.eth` in a browser. 
- I typed `oisinkyne.eth` into my browser (Firefox 67.0)
- Metamask redirected me to moz-extension://9f1cd308-34c4-9445-b7e7-e6c69945d729/error.html?name=oisinkyne.eth
- I removed `error.html` from the URL
- I was able to browse the directories of metamask. 

**Expected behavior**
Accessing a directory like moz-extension://9f1cd308-34c4-9445-b7e7-e6c69945d729/ should return 404, accessing files should work as normal. 

**Browser details (please complete the following information):**
 - OS: OSX 10.14.5 (18F203)
 - Browser Firefox 67.0
 - MetaMask Version 6.5.3

**Comment by ivanvpan** [comment]
Could not reproduce in FF with 6.7.3, I get redirected to manager.ens.domains.
Also, doesn't seem like a security issue to me, there's nothing sensitive about the list of files in local package. @OisinKyne why do you think it's a concern?

**Comment by ivanvpan** [comment]
@OisinKyne I'm not related to the project, but I would suggest you close the issue, since it's not really an issue.
