### ISSUE TITLE
Disallow onboarding flow in popup view

### ISSUE THREAD

**Issue by seandotau** [MetaMask/metamask-extension#6685]
__MOD EDIT__ 
Bug: when the user installs metamask, aborts onboarding, then visits a dapp that prompts the Connect screen, the extension shows an unstyled & un-usable onboarding flow in the popup view. 

Expected behavior is for MetaMask to open a full-screen onboarding flow when it receives a connect request for a non-onboarded user. 

----

**Describe the bug**
Not really a bug but a usability issue. When attempting to restore a wallet, there is no check box next to "I have read the agree to the Terms of Use". The user has to actually click on the words on the sentence to make the "Import" button clickable. This is almost impossible to figure out. I discovered it by accident.

**To Reproduce**
1. Install Brave
2. Install MetaMask in Brave. 
3. Attempt to "Import Wallet"

**Expected behavior**
There should be a check box 

**Screenshots**
<img width="345" alt="Screen Shot 2019-06-05 at 1 34 00 pm" src="https://user-images.githubusercontent.com/12471846/58928818-6f61c280-8797-11e9-9ddb-3ee43c2b32fc.png">

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser:  Brave Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
 - MetaMask Version: 6.5.3

**Additional context**

**Comment by bdresser** [comment]
hey @seandotau, thanks for flagging. We've moved to a full-screen onboarding, so I'm curious how you got to view this unstyled screen in the extension drop-down.

After you install MM from the web store, does it open in a full tab?

During onboarding, when you click the MM icon in your top bar, does it open in a full tab?

**Comment by seandotau** [comment]
I've seen the full screen on-boarding process and it looks great. To replicate this process, I opened up Brave and the first thing I did was open remix.ethereum.org, then these un-styled screens appear. Further screenshots attached: 
[Screen Shot 2019-06-07 at 4 16 19 pm](https://user-images.githubusercontent.com/12471846/59084853-0ec1b980-8940-11e9-9cba-84e98fec5e5f.png)
![Screen Shot 2019-06-07 at 4 16 38 pm](https://user-images.githubusercontent.com/12471846/59084861-11bcaa00-8940-11e9-8008-5d49d95d1623.png)
![Screen Shot 2019-06-07 at 4 16 45 pm](https://user-images.githubusercontent.com/12471846/59084863-12edd700-8940-11e9-8c13-683105d8c080.png)
