### ISSUE TITLE
ENS: Automatic Account Name

### ISSUE THREAD

**Issue by MysticRyuujin** [MetaMask/metamask-extension#6701]
**What problem are you trying to solve?**
When importing a wallet the imported account are just named "Account 1", "Account 2" etc.

**Describe the solution you'd like**
If an imported account has a reverse record setup for ENS, automatically name the account whatever the ENS reverse record is.

**Comment by bdresser** [comment]
relates to #5525

**Comment by tmashuang** [comment]
You can push feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests.
