### ISSUE TITLE
Chrome browser extension is off."This item has been disabled in Chrome" and i'm not able to turn back on.

### ISSUE THREAD

**Issue by keithofaptos** [MetaMask/metamask-extension#6705]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - MetaMask Version [e.g. 5.0.2]

**Additional context**

**Comment by keithofaptos** [comment]
Chrome browser extension is off."This item has been disabled in Chrome" and i'm not able to turn back on.

**Comment by tmashuang** [comment]
Achieving old issue, if this is still an issue please email our support center support[@]metamask.io
