### ISSUE TITLE
It is showing undefined

### ISSUE THREAD

**Issue by jaygpt** [MetaMask/metamask-extension#6709]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - MetaMask Version [e.g. 5.0.2]

**Additional context**

**Comment by bdresser** [comment]
Gonna need way more info than that @jaygpt. Please fill out the template with the necessary info to help us understand your issue. Closing until actionable.
