### ISSUE TITLE
Currency Conversion settings revert back to default USD

### ISSUE THREAD

**Issue by frankiecee** [MetaMask/metamask-extension#6710]
**Describe the bug**
When using Chrome and changing the Currency Conversion setting to a different currency such as GBP, the setting will revert back to the default option (USD) if you quit out of Chrome and then log back into MetaMask.

**Steps to reproduce:**

1. Change Currency Conversion in General Settings to GBP, CAD, etc.
2. Go back to the main page to witness the change
3. Quit Chrome completely
4. When you open Chrome again, it will require you to log into MetaMask

Expected Results:

- The currency should still show ETH/GBP

Actual Results:

- The currency is reverted back to ETH/USD

**Additional context**
Related Support case: 20215
Seems related to previous issue #1211

**Comment by bdresser** [comment]
relates to #1459

**Comment by PyrateAkananto** [comment]
I am even affected (and annoyed) by this bug: I set MetaMask to EUR and MetaMask resets itself to USD.
My software setup:
* Windows 10 Pro (64 Bit) set to German language and CET/CEST time zone
* Firefox 68.0.1 set to English (US) language
* Chrome 76.0.3809.100 set to English language
* MetaMask 6.7.3 in Firefox set to English language
* MetaMask 7.0.1 in Chrome set to English language

**Comment by Gudahtt** [comment]
This has been fixed in GABA v1.8.0 (which we updated to in #7357 )
