### ISSUE TITLE
"Stories in Ready" link

### ISSUE THREAD

**Issue by AM-77** [MetaMask/metamask-extension#6711]
![Screenshot from 2019-06-13 09-40-12](https://user-images.githubusercontent.com/18232579/59413186-5a9cb480-8dbf-11e9-876e-7de86d0e223f.png)

**Comment by bdresser** [comment]
@AM-77 what are you looking for?

**Comment by AM-77** [comment]
@bdresser  The link isn't working and should somehow look like the circleci link
