### ISSUE TITLE
Please use more harmonious logo for Livepeer Token :)

### ISSUE THREAD

**Issue by chrishobcroft** [MetaMask/metamask-extension#6715]
**What problem are you trying to solve?**

Currently, the file being used for the icon for the Livepeer Token looks "the opposite of beautiful", when cropped into the circular frame and displayed in the MetaMask app. See screenshots below for further reference.

The icon file being used is obviously designed to be displayed without a border, or with a square border.

**Describe the solution you'd like**

A lovely solution would be to use the file below, which has some padding around it, so that when it is displayed inside a circular frame, the full logo is visible.

![Livepeer_Mark_Black_Padded](https://user-images.githubusercontent.com/2212651/59551102-ba888c00-8f74-11e9-9310-a20ccd946185.png)

[svg file available here.](https://github.com/chrishobcroft/hello-world/blob/master/Livepeer_Mark_Black_Padded.svg)

**Additional context**

See how it looks right now:

![Screenshot from 2019-06-15 13-40-43](https://user-images.githubusercontent.com/2212651/59551057-1ef71b80-8f74-11e9-9758-2e012a61c8b0.png)
![Screenshot from 2019-06-15 13-40-48](https://user-images.githubusercontent.com/2212651/59551058-1ef71b80-8f74-11e9-8e69-510c669d85d3.png)
![Screenshot from 2019-06-15 13-40-51](https://user-images.githubusercontent.com/2212651/59551059-1f8fb200-8f74-11e9-824f-42e5e761d116.png)
![Screenshot from 2019-06-15 13-40-57](https://user-images.githubusercontent.com/2212651/59551061-1f8fb200-8f74-11e9-9cc1-ef67c0c51e66.png)

**Comment by bdresser** [comment]
feel free to open a pull request on https://github.com/MetaMask/eth-contract-metadata adding this image

**Comment by chrishobcroft** [comment]
Done, thanks @bdresser https://github.com/MetaMask/eth-contract-metadata/pull/315
