### ISSUE TITLE
Add HD path option `m/44'/60'/0'/0` for Ledger wallets.

### ISSUE THREAD

**Issue by Roger-Wu** [MetaMask/metamask-extension#6716]
**What problem are you trying to solve?**

When adding accounts from a Ledger wallet, there are 2 options for the HD path,
* Ledger Live: `m/44'/60'/0'/0/0`
* Legacy (MEW / MyCrypto): `m/44'/60'/0'`

But we have been using `m/44'/60'/0'/0` for more than 1 year, and we believe that it is a commonly used path and should be one of the options too.

**Describe the solution you'd like**

Update the `getHdPaths` function in `ui/app/pages/create-account/connect-hardware/account-list.js` to something like

```js
    getHdPaths () {
      return [
        {
          label: `Ledger Live`,
          value: `m/44'/60'/0'/0/0`,
        },
        {
          label: `Legacy (BIP44)`,
          value: `m/44'/60'/0'/0`,
        },
        {
          label: `Legacy (MEW / MyCrypto)`,
          value: `m/44'/60'/0'`,
        },
      ]
    }
```

`selectPathHelp` in `app/_locales/en/messages.json` should be updated too.

The label `Legacy (BIP44)` may not be an optimal one, but we don't know how to make it better. Please give us some suggestions if you have any.

**Additional context**

A screenshot in MetaMask 6.6.1.
![image](https://user-images.githubusercontent.com/6902276/59556710-d4b87d80-8ff9-11e9-92a8-5d1c05fd4611.png)

**Comment by jpangelle** [comment]
> I moved from Ledger to Trezor. I need to connect to m/44'/60'/0' addresses.
> When I connect Trezor is there a option how to manualy set derivation path or invoke the path selector ?

Also having this same issue.

**Comment by xGitter** [comment]
Any news. I have the same problem. I'm trying to migrate from Ledger to Trezor, so I need to change the derivation path to m/44'/60'/0'

**Comment by Stanislav144** [comment]
Ditto, we need a way to set dpath
