### ISSUE TITLE
MetaMask as a tool for hacker attacks

### ISSUE THREAD

**Issue by ririen** [MetaMask/metamask-extension#6717]
Today on Twitter, information about a new contract allowing to store websites in blockchain has been made available. An example code was also provided:

```js 
var bi=window.prompt("Enter site ID (try 0?)");window.web3.eth.getCode("0x4CecEC099a5c8B554e6Ec0cdb7B7623f5016e20b", (e,r)=>{for(t=r.toString(),n="",o=0;o<t.length;o+=2)n+=String.fromCharCode(parseInt(t.substr(o,2),16));eval(n.slice(1));})
```

Source: https://twitter.com/phildaian/status/1140352344305164289

the code is placed in the console and it automatically changes the current page content to the one downloaded from the blockchain (of course if metamask is installed). This works in a very interesting way because the address bar is not the same and the content of the page taken from the blockchain is actually a little secretive.

I was wondering what new opportunities for the attack it opens. First of all, MetaMask can be used as a hacking tool by downloading dangerous code from blockchain. 

In a sense, blockchain can be used here as a server containing malicious data. Metamask as an intermediary malicious data downloader and browser as a tool for executing malicious data.

I've met many software situations that really trust in the data downloaded from the contracts. One such example is DAPPS. Sometimes in the names of objects ERC-721 you can enter any string of characters - inject javascript which website then downloads and performs because it created a strange tendency to trust the data downloaded from official contracts.

And so I wonder and invite you to discuss this topic. Should there be any warning or additional function in MetaMask that would check the data from a given contract in terms of whether or not they harm users?

**Comment by mradkov** [comment]
Interesting and actually very reasonable to have some verifications or checks for the data before proxying it to the user.

Have you tried yourself to implement such an attack vector? E.g. including some javascript code as a string in some ERC721 object or similar to simulate this vulnerability.

**Comment by ririen** [comment]
Accurately checking this requires a lot of preparation and now I have little time to deal with it. It is required to create special environments to see how it all works in depth. But I will look at it and I will take it in my spare time :)

The data with the website is downloaded from the contract and the javascript code as string calls the page (data) from the contract.

1. So you need to create a crafted website with a properly crafted code and make it deploy to the said contract.

2. Then create a sandbox token collectible with the ability to set your own name and sandbox web ui to read it.

3. In the collectible test, change the custom name to the javascript string code that retrieves the previously depiled code and page.

4. Open the sandbox ui in the browser and see how it affects security and create in-depth analysis.

**Comment by Gudahtt** [comment]
This is interesting, thanks for bringing it up!

Ultimately I'm not sure there's much we can or should do about this. The dangerous part of that snippet is the call to `eval`, which the user has to manually type into their console. We can't stop users from executing arbitrary JavaScript in the browser.

We could consider adding a dapp permission for calling `ethCode`, and disallowing it otherwise. This would break _a lot_ of dapps though, so we'd need a _very strong_ reason to consider something like that.

**Comment by Gudahtt** [comment]
I'll close this for now, since I don't think there's anything we can do about this. But if you can think of any feasible way to mitigate this feel free to suggest it!

**Comment by philliprossii** [comment]
I downloaded a game called Game @GuardiansMeta and being a Cybersecurity consultant and analysis expert for the last 5 years and 3 in Blockchain am trying to understand how guardiansofthemeta.com got authorization through my wallets. No seed phrases, nor keys were on the devices. The browsers had my MetaMask, but I didn't not ever connect them to this game. While I waited at 90% two of my wallets were compromised . Thank for writing this. Please if you have time can you look into this.

**Comment by philliprossii** [comment]
> Today on Twitter, information about a new contract allowing to store websites in blockchain has been made available. An example code was also provided:
> 
> 
> 
> ```js 
> 
> var bi=window.prompt("Enter site ID (try 0?)");window.web3.eth.getCode("0x4CecEC099a5c8B554e6Ec0cdb7B7623f5016e20b", (e,r)=>{for(t=r.toString(),n="",o=0;o<t.length;o+=2)n+=String.fromCharCode(parseInt(t.substr(o,2),16));eval(n.slice(1));})
> 
> ```
> 
> 
> 
> Source: https://twitter.com/phildaian/status/1140352344305164289
> 
> 
> 
> the code is placed in the console and it automatically changes the current page content to the one downloaded from the blockchain (of course if metamask is installed). This works in a very interesting way because the address bar is not the same and the content of the page taken from the blockchain is actually a little secretive.
> 
> 
> 
> I was wondering what new opportunities for the attack it opens. First of all, MetaMask can be used as a hacking tool by downloading dangerous code from blockchain. 
> 
> 
> 
> In a sense, blockchain can be used here as a server containing malicious data. Metamask as an intermediary malicious data downloader and browser as a tool for executing malicious data.
> 
> 
> 
> I've met many software situations that really trust in the data downloaded from the contracts. One such example is DAPPS. Sometimes in the names of objects ERC-721 you can enter any string of characters - inject javascript which website then downloads and performs because it created a strange tendency to trust the data downloaded from official contracts.
> 
> 
> 
> And so I wonder and invite you to discuss this topic. Should there be any warning or additional function in MetaMask that would check the data from a given contract in terms of whether or not they harm users?
> 
> 

I plan on creating an advanced way to shutdown a hackers way into the wallet, so a person has time to remove there wallet and the malware without loss of funds.
