### ISSUE TITLE
Tx list item throwing: new BigNumber() not a number: null

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6725]
https://sentry.io/organizations/metamask/issues/1074813429/?project=273505&query=is%3Aunresolved

Appears to have been introduced in [v6.6.2](https://github.com/MetaMask/metamask-extension/releases/tag/v6.6.2).

**Comment by whymarrh** [comment]
Refs #6750

**Comment by suspended** [comment]
Still a problem in [v8.0.4](url)
