### ISSUE TITLE
Sending 0 (zero) tokens should give a confirmation warning?

### ISSUE THREAD

**Issue by marsrobertson** [MetaMask/metamask-extension#6726]
I wanted to send tokens.

By accident sent exactly 0.

I think it is not a typical use case.

Most of the time, a user is likely to send a non-zero amount.

Therefore I suggest making the amount `required` **OR** forcing the user to confirm:

> Are you sure you want to send 0 tokens?

![sending zero long 2019-06-18 23_12_40](https://user-images.githubusercontent.com/44369284/59723449-98199b80-921e-11e9-8d50-d199750aa6e6.gif)

**Comment by marsrobertson** [comment]
https://eips.ethereum.org/EIPS/eip-20

> Note Transfers of 0 values MUST be treated as normal transfers and fire the Transfer event.

I still believe it's not a typical flow...

**Comment by tmashuang** [comment]
You can push feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests.
