### ISSUE TITLE
Unable to connect Hardware wallet (Ledger) to MetaMask on Linux

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6732]
**Describe the bug**
Users are unable to connect their ledger to MetaMask on linux.

**Expected behavior**
It should connect but when a user clicks "Connect Hardware Wallet, Ledger, Connect", an infinite spinner occurs, with no indication on the ledger device, and the account never is added.

**Browser details (please complete the following information):**
 - OS: linux (ubuntu)
 - Browser chrome and firefox
 - MetaMask Version 6.6.1 and 6.6.2

**Additional context**
related support ticket: 19873

**Comment by dpazdan** [comment]
User stated they tried all the troubleshooting steps shown on our support article here: https://metamask.zendesk.com/hc/en-us/articles/360020394612-How-to-connect-a-Trezor-or-Ledger-Hardware-Wallet

I initially assumed it was a connection issue with the ledger and linux device (via USB).  Changing ports and following the steps shown on Ledger's support site did not help: https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

I've tried to connect a ledger to MM, on ubuntu, and experienced the same.

**Comment by BrentAllsop** [comment]
I was able to connect Metamask to my Nano S, but I also have a Ledger Blue I’m trying to connect.  I get the same “eternal spinner” when trying to connect my Blue.

**Comment by dpazdan** [comment]
When using your Ledger blue, can you try to connect it to your computer via cable and not Bluetooth, to see if that works?

**Comment by BrentAllsop** [comment]
I have an older Ledger blue that I don't thank does bluetooth.
https://www.ledger.com/ledger-blue-firmware-availability-updates/
If it can do blutooth, I have never attempted it.  I am, and have always used the USB cable.
It works with the cable with Ledger Live, but not with metamask.
I'm wondering if it has something to do with having multiple hardware wallets configured.
I have the ledger nano s configured, and it works with MM.  But when I try to configure a second hardware wallet - infinite spinner.

**Comment by dpazdan** [comment]
Yes this is likely the cause.  You can only have one ledger connected per MM installation at this time.  If you need both, I recommend installing  MetaMask on another browser, or set up multiple chrome profiles.

**Comment by BrentAllsop** [comment]
That makes sense.  Thanks for the info!!

**Comment by dchambers** [comment]
> Yes this is likely the cause. You can only have one ledger connected per MM installation at this time. If you need both, I recommend installing MetaMask on another browser, or set up multiple chrome profiles.

@dpazdan, I've just run into the same problem with my Ledger Nano S on Linux. Brand new MetaMask install with no other hardware wallets connected, so it's not the number of wallets in my case.

Also worth pointing out that my I can connect to the Ledger just fine on a Mac running the exact same version of Google Chrome that I'm using on Linux ('Version 76.0.3809.132 (Official Build) (64-bit)').

**Comment by simonerom** [comment]
Hello.
Trying to connect my Ledger nano X with Metamask on Ubuntu and I get the same endless spinner after clicking on the "connect" button.

Ubuntu 19, tried latest Google Chrome, Chromium, and Brave browsers with tghe same result. I have no other hardware wallets connected to Metamask.

**Comment by hems** [comment]
> The problem for me was solved by enabling Contract Data in my Ethereum app on the Ledger Nano X.

That worked for me too. Can't say how counter-intuitive this was. Thanks for sharing.

**Comment by investa** [comment]
thanks guys this solved the issue for me! 
Can connect metamask to ledger, but can only see the ledger wallets in meta, but not import meta > ledger live.

**Comment by dpazdan** [comment]
Yea this is one small but crucial step in the process to make it all work (and is in our kb article found here: https://metamask.zendesk.com/hc/en-us/articles/360020394612-How-to-connect-a-Trezor-or-Ledger-Hardware-Wallet).

**Comment by LEscobar-Driver** [comment]
> Had the same problem on Ubuntu + Metamask on any supported browser and without any other hardware wallet linked to metamask.
> 
> The problem for me was solved by enabling Contract Data in my Ethereum app on the Ledger Nano X.
> 
> Just connect the ledger through usb cable
> Input your pin on the ledger
> Open the Eth app on the ledger
> Browse to settings->Contract data
> Enable Contract data
> Connect your Metamask to the ledger!


This didnt solve the problem for me. Im on a mac using firefox :-(

**Comment by JordyRacer** [comment]
This is a big issue now, I have tried many methods to get this working and metamask & ledger need to up their support.

**Comment by lieberscott** [comment]
Can't connect. Have tried everything on the "Troubleshoot" page, still can't connect.

**Comment by burz** [comment]
I ran into this problem on Ubuntu 20.04.1 while using the Chromium browser with Metamask. It appears that the issue may be Chromium-only as **switching to the Brave browser fixed the issue**

**Comment by promaty** [comment]
Cannot connect. Tried different computers with Windows 10, Chrome and Brave browsers. Ledger Live connects fine using USB, but Metamask gives "We had trouble connecting to your ledger, try reviewing our hardware wallet connection guide and try again."

**Comment by promaty** [comment]
Make sure you open Ethereum application on your Ledger when trying to connect.

**Comment by richstew** [comment]
I have a Ledger Blue, running on latest firmware. It connects to Ledger Live fine. It does not connect to MetaMask. I have followed the troubleshooting steps. (contract data on, tried different USB ports, cleared cache, tried different browsers)

When connecting I get a message which states the security key is not familiar and try a different one. 

This is painful as like other users, it has cost me cash. Please help!

**Comment by webprez** [comment]
Same here with the Ledger Blue. Nano S works fine but Blue doesn't connect ever.

**Comment by rebroad** [comment]
any plans to get this working? I'm on Windows 10, using Brave browser and same issue. Seems this browser extension is pretty much the only way to buy/store ETH currently..!

**Comment by darkwing** [comment]
Hello @webprez and @rebroad ! We're currently working with the @LedgerHQ team to make this experience better!  We'll announce progress soon!

**Comment by richstew** [comment]
Hi, I was told today that there was an issue with Ledger Blue and Metamask. I was offered a free hardware wallet and was effectively told there is no ETA on a fix.

Sent from my iPhone

On 27 Feb 2021, at 22:35, David Walsh <notifications@github.com> wrote:

﻿

Hello @webprez<https://github.com/webprez> and @rebroad<https://github.com/rebroad> ! We're currently working with the @LedgerHQ<https://github.com/LedgerHQ> team to make this experience better! We'll announce progress soon!

**Comment by ux33-331** [comment]
Same issue on a ledger nano s here with metamask..

**Comment by richstew** [comment]
In respect of Ledger Blue, Ledger support have just offered me a different device for free as they are aware of an issue with the Ledger Blue and there is currently no ETA to fix it.




On 1 Mar 2021, at 21:13, ux33-331 <notifications@github.com> wrote:

﻿

Same issue on a ledger nano s here with metamask..

**Comment by webprez** [comment]
That's great. What did you write/ask?

**Comment by richstew** [comment]
I just followed the support instructions from both Ledger and MetaMask, then created a ticket with Ledger support. They did not do any further troubleshooting, they asked me to confirm that I had followed the troubleshooting, said yes, then they said there was a known problem with Ledger Blue, but just that device.

**Comment by packetstracer** [comment]
Me having problems with Nano S and Nano X, same issue with both. Not working with any wallet (metamask, theta, terra station, etc.). The browser seems to recognize the device but when trying to access from the wallet I guess that the browser doesn't grant the access to it. 

Ubuntu 20
Chromium 89.0.4389
Tried on Chromium and Brave (with usb security flags disabled --disable-webusb-security)
Enabled contract data on ledger ETH app (when trying on metamask)

One of the wallets throws this error on the UI  `Access denied.`

Seems like the browser is not providing access 

I've also tried to set the owner and group to my linux user on the usb dev  with chmod as follows

`sudo chown group:user /dev/usb/hiddev1`

as stated in a comment in this SO thread https://stackoverflow.com/questions/40908927/trouble-enabling-webusb-in-chrome

**Comment by wizardofwhere1** [comment]
So, I've read through all the comments above, walked through the ledger help and metamask help, submitted trouble tickets and received helpful but ineffective answers.  I still see the spinning "Looking for your ledger" message.  Has anyone solved this?  I've tried different computers, a laptop (all windows 10), browsers (chorme, firefox, brave, edge), disconnected/reconnected ledge, logged out/in of metamask, checked ledger settings, turned off bluetooth, turned on contract data etc.  ensured ledger live is not running, restarted my computer, closed all chrome instances and restarted chrome.  I can't figure it out. Any ideas?  Thx

**Comment by R4ZZB3RRY** [comment]
Same problem here using firefox's latest release... works in Brave browser, but it would be nice if it worked in Firefox as thats my go to browser!

**Comment by wizardofwhere1** [comment]
I can't get it to work in any browser.  It works with the Ethereum chain but not with Expanse chain. It either does nothing or I see u2f device ineligible or ledger wrong app.

**Comment by jakues** [comment]
edge browser infinite connect

**Comment by EpicTMC** [comment]
same issue, as a bove and torubleshoot same as everyone else

i think problem is with recent firmware on ledger

**Comment by AlexJupiter** [comment]
There's been some recent progress on the MetaMask/Ledger integration that could have fixed the issues here (https://consensys.net/blog/metamask/metamask-and-ledger-integration-fixed/). Could someone report that they are still experiencing this problem? Or I'll move towards closing this issue.

**Comment by fornax2** [comment]
I'm having issues connecting a ledger nano s plus to mm (v 10.14.7) on Ubuntu 22.04, Firefox v102.1 or Chrome v103. Using an original new USB cable (able to connect on windows machines). Tried another USB port. No AV or firewall. 
Have followed https://support.ledger.com/hc/en-us/articles/115005165269-Fix-USB-connection-issues-with-Ledger-Live?support=true

**Comment by muggenhor** [comment]
I'm also not able to connect to my ledger nano x on firefox 103.0.2+build1-0ubuntu0.22.04.1~mt1 on Ubuntu 22.04 (x86-64) from the mozillateam PPA.

**Comment by danjm** [comment]
While we have fixed multiple ledger issues over the years, connection issues still persist on firefox. Most recently this is due to deprecated support for firefox+usb devices like ledger: https://support.ledger.com/hc/en-us/articles/10371387758493-Metamask-x-Ledger-Connection-Issue-On-Firefox?support=true

It is unlikely we will be able to resolve connection problems with firefox+ledger in the foreseeable future.

If anyone is still experiencing ledger connection issues in a browser other than firefox, please open a new ticket.
