### ISSUE TITLE
Wait time incorrect

### ISSUE THREAD

**Issue by chaitanyapotti** [MetaMask/metamask-extension#6737]
**Describe the bug**
Displayed time taken for a tx is higher with higher gas price which shouldn't be the case

**To Reproduce**
Any Tx

**Expected behavior**
Higher gas price => lower wait times

**Screenshots**
Added imgur links
<blockquote class="imgur-embed-pub" lang="en" data-id="a/wovF7jS"  ><a href="//imgur.com/a/wovF7jS">Metamask gas</a></blockquote>

**Browser details (please complete the following information):**
 - OS: Manjaro/Arch Linux
 - Browser: Chrome
 - MetaMask Version: 6.6.2

**Comment by danjm** [comment]
Hey @chaitanyapotti 

Thanks for filing this issue? Can you try again and report on whether it is still happening. If so, how are you changing the gas price?

**Comment by danjm** [comment]
Actually, I think I just reproduced this. Thanks.

**Comment by Gudahtt** [comment]
We no longer show an estimated transaction time, so this bug is now obsolete.
