### ISSUE TITLE
Refactor account-details-modal.js

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6741]
The file can be found at `metamask-extension/ui/app/components/app/modals/account-details-modal.js`

This component can be found within the app by clicking the "Details" button on the left side of the home screen. See below:

![Peek 2019-06-24 13-01](https://user-images.githubusercontent.com/7499938/60031947-2f984780-9680-11e9-8df5-c22c826d0b2e.gif)

This task is to make the following improvements to the code:
- move the component to its own directory with index.js, account-details-modal.component.js and account-details-modal.container.js files
- account-details-modal.container.js should be a redux "container component". The purpose is to connect `account-details-modal.component.js` to redux using the `react-redux` library. See `metamask-extension/ui/app/components/app/app-header/app-header.container.js` for an example
- `account-details-modal.component.js` should contain the component class and its methods, but  there will be no connection to redux within that file
- rewrite the component with jsx, eliminating the use of hyperscript
- feel free to make any other changes you think are necessary

**Comment by whymarrh** [comment]
@danjm I don't believe the attached GIF is correct for this issue
