### ISSUE TITLE
Allow change of account on Connect Request page

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6742]
**What problem are you trying to solve?**
On visiting a dApp, MetaMask presents a "Connect Request" page showing an icon, page title, and URL for the dApp, a dashed line, a green checkmark in a circle, and a dashed line to the current account identicon, with the name of the account underneath.

The text says 
>**\<Page title\> would like to connect to your account.** This site is requesting access to view your current account address. Always make sure you trust the sites you interact with. [Learn more.](https://medium.com/metamask/introducing-privacy-mode-42549d4870fa)

As already [documented elsewhere](https://github.com/MetaMask/metamask-extension/issues/6065), "Privacy mode isn't very private" and allowing access with **any** account allows access to **all** accounts; the interface language is quite misleading.  There are no signs of an ["immediate" fix](https://github.com/MetaMask/metamask-extension/issues/6065#issuecomment-457709190) even just to the language in that interface, and even less sign of an actual fix where the user authorization is specific to both the dapp **and** the account. 

**Describe the solution you'd like**
Medium-term, I would like to see permissions be specific to both the dapp and the account, and to **allow the user to change which account is currently selected while on the Connect Request screen**, which currently blocks the ability to change accounts.  

Shorter-term, I support removing all account-specific language and graphics, such as not showing any account name or identicon, changing "account" to "accounts" and "current account address" to "account addresses" throughout the (to-be-renamed) "Connect Accounts" dialog.  

Either of those might be basically done in [#6065](https://github.com/MetaMask/metamask-extension/issues/6065); then come back to this Issue for tracking work on the bold line in the "medium-term" paragraph above.

**Additional context**
The workaround most likely to be figured out is to click Cancel, change accounts, and then reload the dapp.  

The easier workaround is to ignore all the misleading account-specific language and imagery because it doesn't actually matter, and click Connect anyway, *then* change accounts prior to triggering transactions.

**Comment by bdresser** [comment]
Thanks @wbt, this has been documented and is in-progress as part of https://github.com/MetaMask/Design/issues/58 and https://github.com/MetaMask/metamask-extension/issues/3383. Will make note of your feedback there.

**Comment by tmashuang** [comment]
This has been implemented.
