### ISSUE TITLE
English-language translation: Problem? Or volunteer needed?

### ISSUE THREAD

**Issue by tgeller** [MetaMask/metamask-extension#6755]
I was surprised at how many holes I saw in the English translation -- see attached, for example. Two likely possibilities:

1) My browser isn't displaying things correctly. (Possibly because the first language preference in Chrome was "English (United States)" rather than "English". The second was "French".)

2) The translation files are incomplete.

If it's #2, I'd like to help. I've looked through https://github.com/MetaMask/metamask-extension/blob/develop/docs/translating-guide.md . The problem is: There's already a messages.json file for English, but it's not clear where the "holes" are.

I'm not terribly experienced with team development: I've contributed a little for open-source projects including Drupal, but it's been a while. If someone in the translation team would be willing to help me figure out, I'll do my part. (I'm a native English speaker and professional writer with some knowledge of French.)

By the way: I originally sent this to hello@metamask.io, which directed me to post here. 

![english-translation-lacking](https://user-images.githubusercontent.com/5687798/60191156-2a7bf980-9834-11e9-8e8a-ac0341243130.png)

**Comment by mapmeld** [comment]
Hi ! I worked on the original i18n/l10n branch to make it possible to translate MetaMask. Most translations came in 1 year ago and haven't been updated as new text is added.

For example the message "Don't see your tokens?" is coded as ```missingYourTokens``` in the English strings file https://github.com/MetaMask/metamask-extension/blob/develop/app/_locales/en/messages.json#L923-L925

But there isn't a matching ```missingYourTokens``` entry in the French file https://github.com/MetaMask/metamask-extension/blob/develop/app/_locales/fr/messages.json

**Comment by tgeller** [comment]
Thanks for the response. I don't think it addresses the original question, though.

For example, look at the phrase underneath "Don't see your tokens?" in the screen shot. "Ajouter un jeton" is in the French file as the "addToken" string. The same string exists in the English file (as "Add Token"). So why doesn't the screen shot above show the French version on an "English" system?

**Comment by mapmeld** [comment]
I think now I understand your original question. Your MetaMask wallet defaulted to French translation, possibly due to language of OS or browser, like you said. You can click the upper-right icon and the last menu option - 'Settings' - to set the language. If you change it to English, everything will be in English.  Right now any English that you see, is actually translations which we have missing from French.

**Comment by tgeller** [comment]
A-ha! That solved it. 

I wonder why it defaulted to installing in French. Is it possible the installer doesn't recognize "English (United States)" as English?

(Sorry, "recognise". ;) )

Anyway, feel free to close this issue... or leave it open if you think it deserves investigation. (I'm new to the community and can't make that judgment.) Cheers!

**Comment by wbt** [comment]
@tgeller How are your language skills at translating the remaining English to French?  Your willingness to volunteer has not gone unnoticed ;-)

**Comment by tgeller** [comment]
@wbt Sadly, my French isn't nearly good enough to go in that direction. Sorry. :( (The only other language I can translate *to* is Esperanto. That translation's not a task I care to take on.)

**Comment by whymarrh** [comment]
@tgeller I'm going to close this as it seems like you've got your setup sorted now 😄 (@mapmeld thanks for helping out!)

Let us know if you run into any further issues!
