### ISSUE TITLE
Add advanced setting to enable editing nonce on confirmation screens

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6757]
This is a specific solution proposal that fixes #1410, for the sake of possibly adding a clean and simple bounty to.

Scope:

1. A new setting should be added to `app/scripts/controllers/preferences.js` for whether a user wants a nonce field.
2. This setting should be exposed as a toggle switch in the settings screen as "Show nonce field on confirmation screens. Only use if you understand [the implications.](https://metamask.zendesk.com/hc/en-us/articles/360015489491-Ghost-Accounts-Ether-Sending-Away-Whenever-Funding-An-Account)" (This message should be written in the i18n file).
3. If this boolean is `true`, render a field on the tx confirmation screen that allows hard-coding this otherwise dynamically computed value. The placeholder text of the nonce field should say "Automatically calculate."

I will review this with our team for whether we want to add a bounty before we do, but I think for some advanced users it could clearly be a nice thing to expose.

**Comment by SCBuergel** [comment]
I'll chip in if you Gitcoin this one!

[Meta: "to Gitcoin", verb, adding a bounty on the popular Gitcoin platform]

**Comment by bdresser** [comment]
handled in https://github.com/MetaMask/metamask-extension/pull/7240
