### ISSUE TITLE
How do you make the popup appear without an address bar?

### ISSUE THREAD

**Issue by realisation** [MetaMask/metamask-extension#6769]
My apologies that this isn't really a metamask issue -- I am just hoping that you might be able to point me in the right direction to figure out how to make a popup happen without an address bar similarly to how it happens when Metamask pops up a transaction confirmation.

All the docs I've seen so far haven't yielded anything successful, despite the options appearing like they should do the job, like "location=no".

Any help you might be able to give me would be really nice.

**Comment by realisation** [comment]
If it helps to be extremely specific:

When a transaction is triggered using web3, a popup window appears in the upper left asking for confirmation on sending the transaction. This popup window has no address/url bar - it's just a window with only the Metamask html in it.

This is what metamask does and what I want: 

https://monosnap.com/file/Dj58REIEkIUIyc5XlEN3tLaWpUNR0B

This is what I am getting that I can't figure out how avoid:

https://monosnap.com/file/1h3mWHxLFyPPgsDfvI2c6T8S54Fra4

**Comment by danfinlay** [comment]
WebExtensions have a special API that allow creating "panel" type windows, which have no URL bar:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create

**Comment by realisation** [comment]
@danfinlay Thank you
