### ISSUE TITLE
Contract destination and gas estimate dropped when first of multiple transactions is approved

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6770]
**Describe the bug**
When multiple transactions are queued up for user approval, after the first one is approved, the information about contract destination and gas estimate for subsequent ones seems to go missing.

**To Reproduce**
I do not currently have handy steps to reproduce or code to post, but can walk through what I'm observing.

1. I go to a dapp and click a button which triggers three contract interaction transactions.
2. MetaMask shows an approval popup which at the top says "1 of 3 requests waiting to be acknowledged" and at the bottom, "Reject 3 transactions."  In the third row down from the top, I see my account identicon and local nickname, a rightward facing arrow in a circle, and an identicon and elided hex address of the contract I'm interacting with.  Below that is a tall row containing a rounded rectangle with the words "Contract Interaction," and the ETH symbol followed by a 0 as the interaction sends 0 ETH.  Below that are rows labeled "Gas fee" and "Total respectively, each containing an ETH symbol followed by a relatively small decimal number, and then Reject/Confirm buttons.  If I click the right arrow in the upper right corner to look at the other pending transactions, I see something similar.  The contract address is shown and the gas fee & total are matching small numbers, which differ for each transaction.  I can use these arrows to go back and forth between transactions as much as I want and only the transaction number, gas fee, and total change between the transactions, though consistent for how much each transaction will cost.  I use the arrows to return to the first transaction.  All this is as expected.  
3. I click Confirm. There is briefly a spinner as the transaction is submitted.  An appropriate amount of time later, other code watching blocks will report the change as the transaction is successfully mined. 
2. The display changes to say "1 of 2 requests waiting to be acknowledged" at the top and "Reject 2 transactions" at the bottom.  Again, this is so far all as expected.
3. However, there are a few unexpected aspects of what is displayed:
- In the third row on the left side, the identicon for my account has been changed to a black ETH symbol in a white circle with a light gray outline, though the local account nickname is still shown.  
![image](https://user-images.githubusercontent.com/563406/60366818-a1db9580-99ba-11e9-8a53-74b8609ff8ae.png)
- In the third row on the right side, the identicon and contract address have changed to: 
![New Contract](https://user-images.githubusercontent.com/563406/60366882-cafc2600-99ba-11e9-92fc-83b9ce67d96b.png)
- The gas fee and total show as 0. 
4. If I click Confirm anyway, the transaction gets submitted (it is later mined and affects blockchain data in the expected way) and the third/final transaction comes up, with the same unexpected display components.
5. If I close the MetaMask transaction confirmation popup instead of clicking that Confirm button, and then re-open the popup by clicking the fox on my browser toolbar, the account identicon, target contract information, and gas fee/total are back to what I expected to see.  
6. If instead of confirming that second transaction, I click the right arrow to check out the other remaining pending transaction, the values shown for that are as expected, and when I return back to the first of 2 pending transactions, it is also back to the expected values.  

**Generalizability**
I observe the same when testing with only 2 transactions, and though I didn't go through rigorous verification specifically for this bug report, also seem to experience it with more than 3 transactions.  It does not seem to matter which transactions they are; the 3 in question can be in any order and MetaMask's display is messed up for whichever ones are not the first.  Steps 5 and 6 above especially indicate this is a MetaMask bug. 

The issue was observed on multiple different machines with separate installations but the same version number of MetaMask. 

Earlier successful transactions on the same pageview do not seem to have an impact; this issue only seems to come up when there are multiple _simultaneously pending_ transactions.  It does not seem like they have to be all with the same contract, though they were for the testing specific to the bug writeup.   Subsequent testing in which a cluster of transactions were submitted to multiple different contracts indicates the same issue likely appears in that case as well. 

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]: Windows 10 Pro
 - Browser [e.g. chrome, safari]: Chrome 75.0.3770.100 (Official Build) (64-bit) (cohort: Stable)
 - MetaMask Version [e.g. 5.0.2]: 6.7.1

**Additional context**
I encountered this when trying to debug what I think is a separate issue in which some of the contract interaction transactions _are_ getting sent with 0 gas, and failing with an error "intrinsic gas too low." That is a recent development which started happening today; there were no issues during interactions yesterday and no changes to any of the dapp or interface code between yesterday's no-issues interactions and today's observations, other than a possible silent update of the MetaMask extension and/or browser, which may have changed gas estimation etc..  If I am able to debug and narrow down more, and find the bug to be likely in MetaMask (my current suspicion), I will post that as a separate Issue; if you're aware of a candidate match already filed please point me to it.  

The present Issue seems to be a _display_ bug affecting what is _shown_ in the confirmation window, but not affecting the actual values, because the transactions can still be successfully submitted.  However, this display issue complicates debugging efforts for that other issue.  It also deserves to be solved in its own right because it gives users inaccurate information about how much ETH they might be spending, hides which contract they might be interacting with, and eliminates a visual recognition signal regarding which account they are using for the interaction.

**Comment by Lastrellik** [comment]
I am experiencing this issue as well. When I have more than one contract transaction queued up, say for a 0x.js swap token transaction, a few days ago it was such that every metamask confirmation showed accurate information. But now the fields are showing "Undefined: Undefined".
![undefined](https://user-images.githubusercontent.com/15167910/60402653-5acedb00-9b47-11e9-97f5-6b122d996212.png)

Also, notice on the top how it says `1 0f 3` transactions? I feel like that should say `2 of 4` because there were 4 initially.

**Comment by rozifus** [comment]
Also having this issue

OS: Ubuntu 18.04
Browser: 
    Firefox 67.0.4 (64-bit), MetaMask Version: 6.7.1
    Brave 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit), MetaMask Version: 6.7.1

**Comment by Ella-Emblock** [comment]
I also experienced this situation!

**Comment by bschorchit** [comment]
Closing as this doesn't seem to be an issue anymore.
