### ISSUE TITLE
Restore your account: Back button doesn't work

### ISSUE THREAD

**Issue by MarkOSullivan94** [MetaMask/metamask-extension#6771]
**Describe the bug**

Whenever clicking the back button above the "Restore your Account with Seed Phrase" title, it doesn't do anything. 

Not sure what the expected behaviour is supposed to be or perhaps it isn't supposed to be there.

**To Reproduce**

1. Click the MetaMask chrome plugin icon 
2. Welcome Back screen should appear
3. Click 'Import using account seed phrase'
4. Now click 'Back'

**Expected behavior**

No back button to exist on this page.

**Screenshots**

![Screenshot 2019-06-28 at 23 17 50](https://user-images.githubusercontent.com/6950843/60374174-facb1e00-99fa-11e9-8b26-fc755bc40454.png)

**Browser details (please complete the following information):**
 - OS: MacOS Mojave version 10.14.5
 - Browser: Brave
 - MetaMask Version: 6.7.1

**Comment by tmashuang** [comment]
Seems this #6192 introduced the issue. For now, to get back to the Main View/Home page, refresh the page and it will route correctly.

**Comment by MarkOSullivan94** [comment]
Not actually stuck but thought I'd point it out so it could be fixed

**Comment by danjm** [comment]
This was fixed by https://github.com/MetaMask/metamask-extension/pull/6758
