### ISSUE TITLE
Add decentralized infrastructure option for Metamask users

### ISSUE THREAD

**Issue by luyzdeleon** [MetaMask/metamask-extension#6782]
**What problem are you trying to solve?**
Currently Metamask supports connecting to the network via a custom RPC URL or a centralized provider. In this issue the Pocket Network team would like to propose an integration between Pocket Core MVP and Metamask, allowing users to utilize the Pocket Core MVP network of nodes (currently 6 different infrastructure providers) to connect to the blockchain using a trusted decentralized network of nodes via random access across different requests.

**Describe the solution you'd like**
Scope:

1. Update the UI RPC node selection screen to show the option to use Pocket Network.
2. Create a brand new Pocket middleware to allow RPC requests to be sent via the Pocket Network.
3. Creation of a `json-rpc-engine` middleware package to conform to the architectural standard of network providers, [currently hosted here](https://github.com/pokt-network/json-rpc-pocket).

All the before-mentioned work would be executed by the Pocket Network team according to the project's Contribution Guidelines. For more information about the Pocket Network, feel free to check the links below:

1. [Pocket Network website]( https://pokt.network )
2. [Pocket Core MVP](https://pokt.network/pocket-core-mvp)
3. [Pocket Developer Portal](https://docs.pokt.network)

**Additional context**
N/A

**Comment by tmashuang** [comment]
You can push feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests.
