### ISSUE TITLE
Asset Dropdown should not be openable if the account does not have any tokens added

### ISSUE THREAD

**Issue by chikeichan** [MetaMask/metamask-extension#6787]
<img width="421" alt="Screen Shot 2019-07-02 at 5 49 18 PM" src="https://user-images.githubusercontent.com/8507735/60555454-bfc63480-9cf1-11e9-8a89-526ee94cefc4.png">

The asset dropdown is currently openable even when user doesn't have any tokens. The opened dropdown renders a empty box, which is confusing for the user.

Definition of Done:
- [ ] if the user's account does not contain any tokens, the asset dropdown should not be clickable/openable.

**Comment by Krist14n** [comment]
I noticed that for the mobile beta app, the send tokens page renders the `selectedToken` in the asset field instead of a dropdown. Should I replicate the same behaviour as the mobile version or  just not have the dropdown openable/clickable if no tokens are created?

**Comment by danjm** [comment]
@Krist14n The asset field should show the `selectedToken`. Although I think that is the current behaviour in the browser extension? If not, yes, that should be fixed.

In addition, we want to maintain the current dropdown functionality and also prevent the dropdown from opening if there are no tokens to select.

**Comment by whymarrh** [comment]
Closed by #6900
