### ISSUE TITLE
Addressbook should be Network-specific

### ISSUE THREAD

**Issue by chikeichan** [MetaMask/metamask-extension#6789]
**Describe the bug**
From @bdresser on #6681 

> Biggest thing I'm noticing is that addresses should be network-specific. If I save a contact on Mainnet, it's not necessarily a testnet address, so showing it in the testnet Send flow could cause a lot of user errors. Let me know if you want to chat about this live or if we should pull @jennypollack in as well.

**Comment by bdresser** [comment]
This will be handled as part of #6365

**Comment by jennypollack** [comment]
closed via #6914
