### ISSUE TITLE
Metamask for a specific token

### ISSUE THREAD

**Issue by CurrencyInvestors** [MetaMask/metamask-extension#6791]
Hi, I'm trying to use Metamask for a specific token.
Currently ETH accounts are created, it seems good.
Now it would be interesting that METAMASK, generate specific accounts for specific token, with included keys and key.
To make a token the principal to work, this would result in a METAMASK for each project, is it possible as I start to create this, what modifications to make or what to implement?

**Comment by bdresser** [comment]
@CurrencyInvestors we've discussed this in the past, but aren't interested in making this change right now. As is, you can create a new account yourself for each application you use, if you'd like.

In the future we may adopt a standard like [App Keys](https://ethereum-magicians.org/t/eip-erc-app-keys-application-specific-wallet-accounts/2742) as described in [EIP 1775](https://github.com/ethereum/EIPs/pull/1775), but we will track that work separately as part of other projects.
