### ISSUE TITLE
Hardware wallets (ledger & trezor) - Unable to cancel or speed up tx if first attempt fails

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6799]
**Describe the bug**
If a transaction is broadcast with very low gwei, and needs to be sped up or canceled, you can click the option to do so, but if your hardware wallet accidentally isn't plugged in at that time, or you click the X on the hardware wallet, it will fail, and the option to retry to cancel or speed up goes away. 

**To Reproduce**
1. Send a transaction via a ledger or trezor on MetaMask.
2. Click the transaction details under History
3. Click Speed Up or Cancel without the hardware wallet plugged in.

**Expected behavior**
Maybe a warning message to remind you to have the HW wallet plugged, on the confirmation screen.  If the speedup or cancel fails, the options to speed up or cancel the existing tx should be available again.

**Comment by dpazdan** [comment]
related https://www.reddit.com/r/Metamask/comments/cbsyue/accidentally_sent_transaction_without_hardware/

**Comment by Gudahtt** [comment]
Related: #5474

**Comment by jvalteren** [comment]
Even when a Ledger is connected, signing the transaction times out in Metamask before I've been able to review and accept the tx. This can happen when one needs to unlock the Ledger with PIN, which might take a while.

Metamask seems to time out while the Ledger is still asking for confirmation. So apparently, the timeout in Metamask is different from the review & sign timeout in Ledger. 

It is very inconvenient that this causes the cancel and speed up options to disappear. Even enabling/disabling Metamask doesn't bring these back. Cancelling or speeding up manually is not do-able :-/
