### ISSUE TITLE
Where can I see the result of  sign message?

### ISSUE THREAD

**Issue by qiluge** [MetaMask/metamask-extension#6808]
**What problem are you trying to solve?**
While I use remix to request to sign message, the metamask extension cannot return the result.

**Describe the solution you'd like**
Should display the sign result, such as hex string.

**Additional context**

**Comment by bdresser** [comment]
@qiluge you're submitting the signed data to the dapp that requested it. I'd suggest spinning up your own test dapp rather than using Remix if you want to see the result. This question is better suited for stack exchange!
