### ISSUE TITLE
MetaMask taking ~2 min to present transaction confirmations

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6813]
**Describe the bug**
When I trigger a contract interaction transaction in my dapp, MetaMask takes about 2 minutes before presenting the popup to confirm a transaction.  MetaMask does not appear to log anything in the general browser console. 

**More details**
I have added a console logging statement on the Javascript line immediately preceding the call to the contract function.  I see this print out almost immediately after triggering the transaction, and I expect a nearly immediate MetaMask popup asking me to confirm the transaction.   However, nothing happens.  There is no popup.  There is no number in the lower right corner of the fox icon indicating pending questions.  If I click the fox icon anyway to open MetaMask, I can see a history with many Confirmed transactions, with none Pending and nothing awaiting confirmation. 

About 2 minutes later, the confirmation dialog pops up, a "1" appears in the lower right corner of the Metamask fox icon, and clicking the icon presents the transaction for approval.  When I click confirm, the transaction goes through as expected.

**Expected behavior**
There is no 2 minute wait.

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]: Win 10 Pro
 - Browser [e.g. chrome, safari]: Chrome 75.0.3770.100 (Official Build) (64-bit)
 - MetaMask Version [e.g. 5.0.2] 6.7.2
 - Network connected to: Local Ganache

**Additional context**
I attempted earlier to submit a transaction with the incorrect number of parameters to a Solidity function and/or undefined parameter.  I am not sure there was any MetaMask confirmation of that one, but might have gotten confused about what was being confirmed in which clicks given the long delayed action results.  I noticed the wait times being a lot higher especially after that, though it could have been coincidence.  Even if this was the cause, there should be a more graceful way to overcome one bad transaction attempt.

**Comment by wbt** [comment]
I should also note that this appears to happen with the first .call() on loading the page, and the first "real" transaction when submitting, but that subsequent submissions in the same sequence are presented for approval right away.

**Comment by wbt** [comment]
Closing the browser completely, waiting a bit, reopening the browser, logging in to MetaMask, and resetting the account, then loading the page and triggering another transaction, doesn't help.  The same delay is present.  I also don't see anything in the background page console.

**Comment by wbt** [comment]
Any updates on this?  Months later, I am still seeing these delays before the MetaMask popup appears.  This seriously hinders dapp development and use.

**Comment by wbt** [comment]
I've also noticed long delays when calling TruffleContract's .deployed() to find the location of a contract on the network, and assume it's related to this bug.
The delay seems to get longer as a Ganache blockchain gets longer.

**Comment by danfinlay** [comment]
Are you still experiencing this? We've made some changes that should mitigate problems that were causing some pop-ups to take a long time. I'm going to close for now optimistically, but please let us know if it's not resolved and we will reopen.
