### ISSUE TITLE
web3.eth.getBlock("latest") not working

### ISSUE THREAD

**Issue by paulrberg** [MetaMask/metamask-extension#6820]
**Describe the bug**
No block number is returned from `web3.eth.getBlock`.

**To Reproduce**

1. Git clone `git@github.com@SablierApp/sablier.git`
2. Install modules by running `yarn install`
3. Run the dapp with `yarn start`
4. You can add a console.log in the link below, the block number is not returned

https://github.com/SablierApp/sablier/blob/master/packages/frontend/src/redux/ducks/web3connect.js#L258

**Expected behavior**
Get the latest block broadcast in the Ethereum network.

**Screenshots**
See the screenshot below. None of the "bar" or the error are printed.

<img width="439" alt="Screen Shot 2019-07-08 at 12 23 46" src="https://user-images.githubusercontent.com/8782666/60806729-af8fd880-a17b-11e9-9aa6-f9ed8a78002d.png">

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Brave Version 0.65.121
 - MetaMask Version 6.7.2

**Additional context**
The `getBlock` function worked fine in May and June, a recent update might've caused the issue.

**Comment by PaulRBerg** [comment]
Interestingly, this only seems to be an issue with that version of Brave. I upgraded to 0.66.99 and everything is fine now.

I guess you - or them - made some changes that break backwards compatibility?
