### ISSUE TITLE
Additional information for users that have 0 ETH and try to send tokens

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6821]
**What problem are you trying to solve?**
Currently, when someone tries to send tokens, if they have 0 ETH, they will get an insufficient funds message next to the transaction fee field.  This isn't very clear to some people, that they need ethereum to complete a send.  

**Describe the solution you'd like**
Anytime the send button is clicked, when there is 0  ETH in the account, prompt the user with a message stating they need to deposit ETH for gas, and provide options to do so (similar to our deposit section, and maybe also offer options to quickly send from another MM account too).

Related support case: 22272

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/12965
