### ISSUE TITLE
Metamask Chrome very slow (high number of accounts?)

### ISSUE THREAD

**Issue by 1blockologist** [MetaMask/metamask-extension#6838]
**Describe the bug**
Clicking the metamask icon now makes it take 10+ seconds to reveal. There are constant hangs and slowness. Dialogue popup interactions take 15-20 seconds.

Not sure if this is relevant but I have 40 accounts in metamask, 35 revealed from the mnemonic, 5 imported. Should use a more efficient user experience either way.

**Expected behavior**
instant pop up and response. 

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - MetaMask Version: 6.7.2

**Comment by tmashuang** [comment]
Consolidating to #6547 as one of the potential issues that can cause, slowness/high cpu usage/blank screens.
