### ISSUE TITLE
Create reference example of enzyme test with full mount rendering

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6849]
We do full end-to-end tests with selenium, and unit tests of component with enzyme shallow mounting. There are potential gains to be made for our testing strategies by doing full mounts of components at the "page" level. This could allow for more fine tuned test coverage than our e2e tests, while still testing the interactions of components across a page.

To start, it would be good to have one such test as a reference point for further conversations, and as an example for future developers to follow.

This task is to write such a test for the root component in one of the following directories:

ui/app/pages/add-token
ui/app/pages/permission-approval
ui/app/pages/settings

**Comment by brad-decker** [comment]
We won't be doing this because we are deprecating enzyme :D :D :D 

Thanks @tmashuang ❤️
