### ISSUE TITLE
Goerli Network: Error: [ethjs-rpc] rpc error with payload

### ISSUE THREAD

**Issue by monosux** [MetaMask/metamask-extension#6859]
**Describe the bug**
Looks like Goerli Network integration is broken. Trying to send a transaction or interact with a dapp give me an error:

Error: [ethjs-rpc] rpc error with payload  
```
"rpc": {
        "code": -32002,
        "message": "project ID is required to access archive state",
        "data": {
                "see": "https://infura.io/dashboard"
        }
},
```

🤔

**Comment by ryanschneider** [comment]
There was a bug in our (Infura's) routing of RPC requests to Goerli causing some requests to be mistaken as requiring archive state when they weren't.  This is now fixed.

**Comment by monosux** [comment]
Thanks!
