### ISSUE TITLE
Webcam support for scanning QR codes

### ISSUE THREAD

**Issue by mcgravier** [MetaMask/metamask-extension#686]
Moving funds between phone and MetaMask is cumbersome. 
It would be conveinient to be able scan QR code from phone directly

**Comment by flyswatter** [comment]
Try to make this compatible with Jaxx, as per #685

**Comment by mesqueeb** [comment]
Not just webcam! We need:

- Select/drag a QR image right in the browser extension to be able to pay!

I'm developing an app where I would use a phone to scan and pay, but I have no phone wallets on Ropsten, so I'm not sure how. I'd like to be able to drag the QR code to my metamask extension and pay like that! : )

**Comment by brunobar79** [comment]
@bdresser  I've done some progress on this one last weekend. 
I'm able to access the camera from the extension (by injecting it inPage) and scan a QR code correctly. I still need to wire things up with the UI and it should be ready to go.

@danfinlay maybe we can pair next Friday and finish it.

**Comment by brunobar79** [comment]
@cjeria ^^

**Comment by bdresser** [comment]
designs being tracked on the PR #4897
