### ISSUE TITLE
User interface get unusable after a transaction gets rejected

### ISSUE THREAD

**Issue by sboucherit** [MetaMask/metamask-extension#6865]
I'm building a small Dapp where I trigger an event. When It happens, I get a "Trying to call a function on a non-contract address" error every time I boot up and start working on it. Then user interface changes, gets buggy, buttons doesn't work anymore (see screenshots below). I could find a solution by uninstalling the metamask extension, doing a truffle networks --clean and re-deploy 2 times, and install it again, and then resetting accounts. I'm not sure if the problem really comes from my app or from Metamask, but the interface problem comes, for sure, from Metamask only.

http://image.noelshack.com/fichiers/2019/29/2/1563267993-screenshot-2019-07-16-01-54-54.png

When I click reject, it's loading indefinitely :

http://image.noelshack.com/fichiers/2019/29/2/1563267993-pb2.png

And here I get stuck, and can't access settings.

**Browser details (please complete the following information):**
 - OS: Arch Linux (5.2.0-arch2-1-ARCH)
 - Browser : Same issue with Brave, Chromium, and Firefox dev. (I always use only one browser at the same time)
 - MetaMask 6.7.2
- Truffle v5.0.25 (core: 5.0.25)
- Solidity v0.5.0 (solc-js)
- Node v11.12.0
- Web3.js v1.0.0-beta.37

**Comment by bdresser** [comment]
@sboucherit can you give us your dapp URL or some sample code to help us reproduce? cc @tmashuang

**Comment by wbt** [comment]
@sboucherit Are you sure you're connected to the right network, and trying to do the function interaction at the address where the contract you expect to interact with is deployed *on that network*?

**Comment by tmashuang** [comment]
I am going to close this, if you continuing to having this issue please provide a more up-to-date code example and/or repository and this can be reopened.
