### ISSUE TITLE
Add support for signTypedData_v4

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6868]
UI should be identical to `_v3`, making implementation simple. The difference is it should use the [newly merged `v4` method in `eth-sig-util@2.3.0`](https://github.com/MetaMask/eth-sig-util/pull/54), which supports arrays and recursive structs.

Created by our friends at Infura to support a new type of state channel they've designed!

Completing this issue also requires updating [our docs site](https://metamask.github.io/metamask-docs/).

**Comment by BrendanChou** [comment]
@whymarrh @danfinlay Can you reopen this as the rpc call was not previously supported in eth-json-rpc middleware, so the extension itself still cannot process these calls. 

I fix that with a PR here, but metamask-extension will still have to use the new npm version of eth-json-rpc-middleware https://github.com/MetaMask/eth-json-rpc-middleware/pull/15

**Comment by danfinlay** [comment]
Merged your changed and published it as `+ eth-json-rpc-middleware@4.2.0`

**Comment by danfinlay** [comment]
I'll get to this soon if you don't beat me to it.

**Comment by BrendanChou** [comment]
Hey Dan, is this going to be in 7.1.2? Should just be updating the `eth-json-rpc-middleware` package right?

**Comment by whymarrh** [comment]
@BrendanChou this should be out in 7.2.0 very soon, I'm going to bump this today
