### ISSUE TITLE
Lockfile churn

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#6879]
The `package-lock.json` file changes upon every `npm install`, even when no changes are made to dependencies. This lockfile churn has caused problems for many contributors, and makes adding new dependencies without including this cruft rather tedious and time consuming.

Eliminating this churn would make development a great deal easier.

**Comment by lazaridiscom** [comment]
Though fixed, for documentation purposes (and possibly to decide if to switch organization-wide to yarn), the solution to fix his "churn" is:

https://stackoverflow.com/a/45566871

within package.json

> you now must specify the versions without a prefix, e.g., you need to write them as 1.2.0 instead of ~1.2.0 or ^1.2.0

or, use `npm ci` (which uses the lock file.)

**Comment by Gudahtt** [comment]
Yes, we do know that npm is supposed to work like that. The problem was that it didn't work, specifically with git dependencies and optional dependencies. There were cases of both resulting in lockfile differences on successive calls to `npm install`, across a wide range of npm versions.

**Comment by lazaridiscom** [comment]
Yes, I remember having problems, too. I think there was additionally an issue with different checksums on different os's. Personally I don't like the concept of a lock-file at all.

(anyways, just posted the "solution" for sake of completeness)
