### ISSUE TITLE
Measure changes to bundle size

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#6880]
It would be useful to track changes to the bundle size over time. Having this information available on PRs would help in evaluating the impact that PR has upon the bundle, which might prevent surprises going forward.

It also might be helpful to track bundle size on the main branch over time, or between releases.

**Comment by brad-decker** [comment]
@Gudahtt you pointed out to me that bundle explorers and sizes are posted by the bot on every PR..is this issue meant to be an enhancement over that?

**Comment by Gudahtt** [comment]
Yep; we currently _link_ bundles, but we don't report on the bundle size differences.

Ideally we'd show a table reporting the current bundle size before and after compression, and the diff.
