### ISSUE TITLE
Add `chainId` event

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6885]
https://medium.com/@pedrouid/chainid-vs-networkid-how-do-they-differ-on-ethereum-eec2ed41635b

http://eips.ethereum.org/EIPS/eip-695

Will probably resemble the changes that gave us the networkID event:
https://github.com/MetaMask/metamask-inpage-provider/pull/4

**Comment by Gudahtt** [comment]
This should still be open until #7110 is merged
