### ISSUE TITLE
Stuck on "connecting to network"

### ISSUE THREAD

**Issue by sebastiantf** [MetaMask/metamask-extension#6892]
**Connecting to network keeps spinning**
Metamask keeps showing _'Connecting to network'_ screen even after Ganache has been started. After closing and reopening the browser, clicking the Metamask icon (**without Ganache open yet**) shows the connecting screen and eventually fails. Now I start up Ganache and loads the workspace, clicks the _Try Again_ button. It still won't connect and eventually fails.

The workaround is to select the network from the list of networks and it _connects without any problem._

Might be related to #2636 which is closed. But still facing the issue.

**To Reproduce**
1. Close browser **and Ganache** if running
2. Reopen browser. **Do Not** start-up Ganache yet.
3. Click on Metamask extension icon. Connecting message displays
4. Start-up Ganache and open any workspace while Metamask's trying to connect or after the attempt fails.
5. Click Try Again.

**Expected behavior**
Metamask must automatically detect the Ganache instance and connect to it while it is actually trying to connect

**Screenshots**
![ganache](https://user-images.githubusercontent.com/36922376/61591617-58abe980-abe6-11e9-8ea2-724d7661cd34.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 75
 - MetaMask Version 6.7.3
 - Ganache v2.1.0

**Comment by bdresser** [comment]
not sure I understand the workaround - if you're stuck on the spinner, then you open the network drop-down and click Ganache, it connects? 

could you share a screenshot of your preferences for this network? we've had small issues pop up with untraditional URL casing

**Comment by sebastiantf** [comment]
I hope this screen capture clearly shows the issue and the workaround: 

![metamask_issue1](https://user-images.githubusercontent.com/36922376/61866818-88633600-aef3-11e9-97ae-0a92d7589b59.gif)

The network RPC URL is set as `http://localhost:7545/`

**Comment by sebastiantf** [comment]
> not sure I understand the workaround - if you're stuck on the spinner, then you open the network drop-down and click Ganache, it connects?
> 
> could you share a screenshot of your preferences for this network? we've had small issues pop up with untraditional URL casing

@bdresser I hope this screen capture clearly shows the issue and the workaround: 

![metamask_issue1](https://user-images.githubusercontent.com/36922376/61866818-88633600-aef3-11e9-97ae-0a92d7589b59.gif)

The network RPC URL is set as `http://localhost:7545/`

**Comment by varunseth5788** [comment]
i would like to contribute to this issue.
or need any other help.

**Comment by divyamojas** [comment]
Hey, I would like to contribute here. Can you assign me this issue?

**Comment by danjm** [comment]
Closing as this was first filed in 2019 and there were not reports since
