### ISSUE TITLE
Website On ENS/IPFS Doesn't Resolve With MetaMask Anymore

### ISSUE THREAD

**Issue by tekisx** [MetaMask/metamask-extension#6893]
I'm using ENS/IPFS to host a static version of my website. Up until recently, whenever I typed my .eth domain into a browser using MetaMask, a logo for "Portal Network" would flash and then my website would load. That all changed recently.

Now, whenever I attempt to resolve my .eth domain in a browser using MetaMask, all I see is a Swarm logo and an error that reads "Manifest not Found."

However, disabling MetaMask and using the "ENS Content Resolver" browser plugin completely fixes the issue for me! For now, I'm just switching between the two plugins whenever I need different functionality, but it'd be nice to be able to just go back to using MetaMask exclusively.

Looking at the error message that accompanies the Swarm logo that I mentioned before, I believe that issue has something to do with the fact that my website uses the "Old Public Resolver" for ENS: 0x1da022710dF5002339274AaDEe8D58218e9D6AB5

This Resolver requires IPFS hashes to be converted into hex (using a tool like https://codepen.io/phyrex/pen/MBzOGR) before being associated with an ENS "content" record. That hex string displays in the URL section of the web browser while it displays the Swarm logo/error message in the following format:

https://swarm-gateways.net/bzz:/<hex_string_here>/

I'm not an expert (really just a passionate hobbyist) but it seems to me like MetaMask is properly recognizing the .eth domain, appropriately routing to the correct ENS content record, but then improperly determining that the record contains instructions for a Swarm path instead of IPFS.

Let me know if I did this wrong or didn't supply enough information. This is my first post!

**Comment by tmashuang** [comment]
> Looking at the error message that accompanies the Swarm logo that I mentioned before, I believe that issue has something to do with the fact that my website uses the "Old Public Resolver" for ENS: 0x1da022710dF5002339274AaDEe8D58218e9D6AB5

This is correct, this is the [PR](https://github.com/MetaMask/metamask-extension/pull/6402) that implemented the feature.
