### ISSUE TITLE
"Sync with mobile" stuck spinning

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#6901]
I went to scan my QR code to sync my keys to MetaMask on mobile, but after entering my password in (Settings > Advanced > Sync with mobile) it gets stuck with the loading spinner.

<img width="355" alt="Screen Shot 2019-07-23 at 8 19 04 PM" src="https://user-images.githubusercontent.com/799573/61762660-909e6280-ad87-11e9-8ead-982a828a6a13.png">

**Comment by brunobar79** [comment]
@wjmelements make sure you have the latest version of the extension downloaded from the Chrome store / firefox store. Won't work if you build it locally

**Comment by wjmelements** [comment]
hey @brunobar79 I am on 6.7.3, which according to github and the chrome store is the current version

**Comment by wjmelements** [comment]
There isn't anything helpful in the background process logs.

**Comment by whymarrh** [comment]
Sync has been updated as of #6967
