### ISSUE TITLE
Increase speed of `npm run lint` with option to only run against files from `git diff`

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6915]
A small improvement to developer workflow would be to increase the speed of `npm run lint` by only running it against files returned by `git diff --name-only` (and `git diff --name-only --cached`)

Probably add a new npm script like `npm run lint:diffed`, so that we don't force all runs of the script to adopt the proposed behaviour

**Comment by whymarrh** [comment]
What files are currently being linted that shouldn't be?
