### ISSUE TITLE
Ledger transactions failing

### ISSUE THREAD

**Issue by BassBauman** [MetaMask/metamask-extension#6922]
**Describe the bug**
When attempting to use MetaMask + Ledger to send a transaction with Ledger, the transaction immediately fails.

**To Reproduce**
Switch MetaMask to Ledger
Generate transaction
Click to confirm transaction
See notification that transaction failed

**Expected behavior**
Transaction should transfer to Ledger
User should be able to sign transaction with Ledger
Transaction should be successful

**Browser details (please complete the following information):**
 - Chrome OS
 - Chrome
 - MetaMask Version 6.7.3

**Additional context**
MetaMask error notification: Transaction failed! Error: TransportStatusError: Ledger device: Invalid data received (0x6a80)

**Comment by wjmelements** [comment]
We are also seeing this. @BassBauman how did you resolve the issue?
<img width="455" alt="Screen Shot 2019-07-29 at 4 00 24 PM" src="https://user-images.githubusercontent.com/799573/62088447-42231500-b21a-11e9-8bdf-2399fc977fb7.png">

**Comment by BassBauman** [comment]
@wjmelements this issue was resolved for me when I changed the Ethereum app settings on Ledger to the following:

Contract data -> YES
Display data -> YES

Also see [issue #43](https://github.com/LedgerHQ/ledger-app-eth/issues/43).

**Comment by wjmelements** [comment]
Thanks @BassBauman
