### ISSUE TITLE
Would be great to be able to perma-set my preferred gas price to safe-low

### ISSUE THREAD

**Issue by JohnAllen** [MetaMask/metamask-extension#6926]
**What problem are you trying to solve?**
Basically it's annoying having to reduce the gas price for every tx.  Just let me set my preferred gas price to safe-low, since I need to make many transactions and have to click extra buttons each time.

**Comment by bdresser** [comment]
closing as a duplicate of the more expansive https://github.com/MetaMask/metamask-extension/issues/3912, added your comment there. thanks for the feedback!
