### ISSUE TITLE
Metamask sync opera ba

### ISSUE THREAD

**Issue by tppk** [MetaMask/metamask-extension#6932]
mam problem z odzyskaniem adresu metamask bądź opera wallet szczerze to już sam nie wiem robiąc dropy nie spodziewałem sie zmiany sprzetu .. a teraz mam zaginione 200 eth ... aż żal pisać no ale wszystkie seedy mam zapisane używalem mew, opera crypto wallet i metamask .
Tylko ze robiąc recovery opery tokeny się nie pojawiają adres też jest inny i tu moje pytanie znając adres ale nie dokładny seed puchares gdzie mogę kombinować żeby go odzyskać .. uczę się na blendach i teraz keye prywatne zapisuje obok adresów no ale mam nadzieje ze da rade jakoś to uratować ... 0x35F61DFB08ada13eBA64Bf156B80Df3D5B3a738d   trochę zadziwiające ale chciałbym je jakoś wrzucić na wallet , bądz czy istnieje opcja w eterscanie zmiany adresu tez dodanego jako kolejny bo tokeny wiszą nie zostaly odebrane z eterscanu ..

**Comment by tppk** [comment]
DONATE ZA help :(

**Comment by bdresser** [comment]
@tppk it's unlikely we'll be able to help you recover lost ETH, but please send an email to support@metamask.io and see if there's anything we can do.
