### ISSUE TITLE
Blank screen, high CPU use and slowness

### ISSUE THREAD

**Issue by wmsouza** [MetaMask/metamask-extension#6933]
**Describe the bug**
Metamask does not open, stays on empty screen for minutes, then finally asks for the password, but can't type anything. CPU usage stays really high.

**To Reproduce**
Just visit any dapp website and try to open the wallet

**Browser details (please complete the following information):**
 - Windows 10
 - Chrome
 - 6.7.3

**Additional context**
By debugging, I found that this was caused by a few transactions that had several thousands items inside their history. I created the PR https://github.com/MetaMask/metamask-extension/pull/6934 to fix it. This might be related to the other issues that were closed without a solution that were about Metamask getting too slow / showing a blank screen.

**Comment by tmashuang** [comment]
Closing this issue to consolidate it with #6933. This could possible the source of the issue with constant history updates for transactions that are pending for a extended period of time.
