### ISSUE TITLE
Create a `ui/` module for all of the background interactions

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#6935]
Currently, there are methods in `actions.js` that rely on the way we create a background connection in that file, but which are not "actions". We should abstract the background connection role that `actions.js` plays to some sort of higher level module that methods other than actions can also then rely on.

Once done, we can migrate any functions in `actions.js` that are not actions but need to background connection to other files.

**Comment by Gudahtt** [comment]
Closing in favour of #17529 which has more details
