### ISSUE TITLE
History hidden while transactions are pending

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6949]
**To Reproduce**
1. Have a dapp which triggers multiple transactions.  As an example, I've got >100 triggered on a single user interaction, which makes the [Confirm All](https://github.com/MetaMask/metamask-extension/issues/4050) button a much-desired feature with apparently no progress. After what may be a [couple minutes' wait from the time the code triggers the transaction](https://github.com/MetaMask/metamask-extension/issues/6813), this produces a popup requesting approval. 
2. Start clicking Confirm to approve some.  After each Confirm, the interface gets a semitransparent white cover with a loading spinner, like this:
![image](https://user-images.githubusercontent.com/563406/62381200-f4a7f000-b518-11e9-89d7-6164f3591e16.png)
and you have to wait for that to clear before clicking Confirm on the next one.
3. After a few, click Edit and drop the gas limit so that a transaction will fail Out Of Gas.
4. Continue approving transactions, but leave several still in the queue.
5. After a few moments, there will be a popup saying "Transaction Failed" instead of something that looks like [this](https://github.com/MetaMask/metamask-extension/issues/5631).
6. Wonder which transaction failed, and attempt to view transaction history.  Attempt to do this by clicking the fox icon.
7. Find that clicking this just produces a copy of the "1 of XX requests waiting to be acknowledged" screen; the transaction history cannot be viewed and there is no way to find out what transaction(s) failed or succeeded.  Conceivably, that information might impact a user's decision about whether or not to approve other transactions, but the user's decisions cannot be informed by knowing what failed.  In such cases, the dapp design *could* wait for one transaction to finish before triggering another, but this would slow the UX down quite a bit, and lead to questions about how long to wait (e.g. multiple block confirmations??).  
8. The only way to view transaction history is to complete the approval/rejection process for **all** pending transactions, **then** click the fox icon and it's visible. 

**Expected behavior**
Some way to view transaction history even when transactions are pending. 

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 75.0.3770.142 (Official Build) (64-bit)
 - MetaMask Version: 6.7.3

**Additional context**
Once you can view the history, the failed transaction is [buried](https://github.com/MetaMask/metamask-extension/issues/6950) below older ones and [not necessarily clear regarding status](https://github.com/MetaMask/metamask-extension/issues/6951).

**Comment by Robbiekruszynski** [comment]
Hi @wbt 

Just wanted to reach out and let you know we are pushing out feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests. 

I'm going to close this ticket on github.

Thank you!

Robbie

**Comment by wbt** [comment]
Hi @Robbiekruszynski Did you create a copy of this Issue over on ZenDesk (& if so, could you please link to it here), or just close it because it was opened here well before you started using ZenDesk?

Personally I would consider this more a Defect than a Feature Request, but in any case I don't think it should just be completely closed.
