### ISSUE TITLE
History of failed transactions buried

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6950]
See reproduction steps on [this issue](https://github.com/MetaMask/metamask-extension/issues/6949) to start.  When originally observed, the error was not an [intentionally induced] Out Of Gas error but rather [an unintentional] `intrinsic gas too low`; this might matter.  

Once the history becomes available to view, scroll down to see more.  Lots of transactions are confirmed, and as you scroll back through the history, you get to past dates, and it seems like everything more recent than these past dates (above it in the history) succeeded.  However, that's not true.  If you keep scrolling down (not using the vertical scroll bar which doesn't go far, but the scroll wheel), you can see a newer transaction near the bottom of the list, without a number in front of the date, which failed.  
Example screenshot (Chrome on Windows):  
![image](https://user-images.githubusercontent.com/563406/62382594-e0b1bd80-b51b-11e9-883a-ce5ce0bc7900.png)

**Expected behavior**
Transactions are in order by datetime with the most recent being the most easily visible at the top of the list, instead of having a recent failed transaction buried below a month or more of confirmed transactions.

**Comment by tmashuang** [comment]
This seems to have been fixed in #8564. I reproduced with a on-chain failed tx to a contract and it seems to organize by date/time. I'll mention #9053 for when the overall design of on-chain failures and provider failures gets sorted out.
