### ISSUE TITLE
Improve handling on closure of Network Timeout Screen

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#6958]
**Describe the bug**
When clicking the X in the upper-right corner of the network switching overlay, MetaMask unexpectedly switches networks to Ropsten. 

**To Reproduce**
1. Install, open, and log in to MetaMask.
1. Connect to a network other than Ropsten.  
1. Click on the network selector. 
1. Scroll down to "Localhost 8545" or any other custom RPC which you can't access or where there is no RPC exposed.
1. A white overlay comes over most of the interface, with a loading spinner and message that MetaMask is connecting.  After a few minutes, there will be a sad emoji with the message "Oops! Something went wrong." with options "Switch Networks" and "Try again" (inconsistent capitalization scheme included).  
1. Click the X in the upper right corner at this point or at any time while the network is connecting, even if it's going to succeed (but you might have to be fast in that case!).
1. MetaMask connects to Ropsten, regardless of whether or not you'd ever previously connected to that network. 

**Expected behavior**
MetaMask connects to the last network it successfully connected to, or if that fails (maybe even if it doesn't), enters a state in which the network selector shows "None" (i.e. not connected to any network) but the interface still works, e.g. to access Settings etc.

**Browser details:**
 - OS: Windows 10 
 - Browser: Chrome
 - MetaMask Version: 6.7.3

**Comment by tmashuang** [comment]
Closing this issue. I see the the desired behavior but this is not currently on our roadmap and don't see it being implemented in the near future. I encourage anyone else in the community to tackle this, or find an alternative approach. 
> MetaMask connects to the last network it successfully connected to

Out of the two suggested approaches, I prefer this one. This would require keeping track of the previous network in state, network controller.

**Comment by wbt** [comment]
Thank you for responding.

I disagree with closing the issue just because it is not on the roadmap for development by the core team; it sends the message that this isn't really open-source software or isn't hoping to be a project maintained by members of the community.  The actual and desired behaviors are well described and I don't think this would actually be that hard to implement; I'd probably put a [good-first-bug] tag on it.  Any difficulty might come from figuring out where to maintain the information about which network was most recently connected to, and maybe a bit of UI work + edge case handling around the "None" case (e.g. when one has not previously connected to any, or the last one was removed).

I request reopening.

**Comment by tmashuang** [comment]
Reopening, but may I change the title to something to something more descriptive to specify a need to include more of a discussion in that case?

Something like: 
`Improve handling of closure of Network Timeout Screen`?
