### ISSUE TITLE
USD price for USDC incorrect

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6964]
The current price shown on coingecko is not what is reflected in the extension.  The extension shows a price closer to $0.92/usdc when coingecko at this moment shows a price near $0.9945.  

reference support case # 23524

**Comment by tmashuang** [comment]
Closing this issue, as of this time of writing this comment, the price via coingecko is 0.00371646 vs what Etherscan shows 0.003796. This is something we can't really control other than switching to one that is more used and widely accepted But I feel that small margin of errors are ok. If we find that coingecko is not updating the tokens correctly, we can revisit this issue on which toke rates api we can move to.

**Comment by tmlee** [comment]
We were not able to consistently reproduce the issue. Things look stable for now. If you are still experiencing issues with pricing data, dont hesitate to contact me or our support at hello@coingecko.com
