### ISSUE TITLE
Can't export private key when a transaction is pending

### ISSUE THREAD

**Issue by yoann1983** [MetaMask/metamask-extension#6981]
Bug Reports:
Nothing happen after i enter my password for show my private key, look like MM loading infinite and after click back on extension its back to the wallet. Tried to reloading the extension but nothing change too.

  *  Browser Chrome
  *  Win10

**Comment by yoann1983** [comment]
Look like its because a Tx was is pending, without Tx in pending i can see my private key.

**Comment by tmashuang** [comment]
Reproduction of steps on v8.1.3, issue does not seem to be present.
