### ISSUE TITLE
Sites should not be force reloaded during manual log-in

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6989]
Our new privacy mode bypass apparently reloads all tabs. This is not necessary, and in fact we are trying to get away from ever reloading pages.

**Comment by joshstevens19** [comment]
It got added 8 days ago here - https://github.com/MetaMask/metamask-extension/commit/e9a63d5d5b428e8ace6423652d8691205bb129f0#diff-205df9c93990ff0f805d90215a20cda4

**Comment by joshstevens19** [comment]
Thanks so much for the quick fix on this. When can we expect a release as this refresh is live.

**Comment by danfinlay** [comment]
Probably early next week.
