### ISSUE TITLE
Try out new tab confirmations

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#699]
I don't know how it took so long to think of, since this pattern is seen by PayPal, Visa's SecurePay service, as well as OAuth flows like Twitter and Facebook:

When approving a TX, instead of a mere notification, or opening a popup (Which can make for [a bad experience when in full screen mode](#634)), we should consider opening a new tab for confirmation, which will navigate back to the page on approval or rejection.

This will give us a lot more visual real estate to work with, will make the approval screen less cramped, will create a more consistent experience across platforms, feels less spammy (popups = yuck), and in fact follows a pattern that has been established by very reputable "transaction approval" processes.

 Bonus points for making this confirmation page stand on its own, ie not require loading the full dapp in a tab, but a more minimal approval tab.

**Comment by flyswatter** [comment]
Would fix #634

**Comment by danfinlay** [comment]
I'm going to stop pushing this now.
