### ISSUE TITLE
Unable to view send or tokens using certain custom (free cloud) RPCs

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6992]
When changing the RPC to https://cloudflare-eth.com or  https://mainnet.rpc.fiews.io/v1/free, everything seems to work properly except tokens do not load.  Users cannot send tokens or see their balances within MetaMask.

**Comment by Gudahtt** [comment]
We don't auto-detect tokens unless using the built-in Infura mainnet, but when testing it looks like tokens can be manually added. Balances and interactions seem to all work correctly.

@dpazdan Could this be explained by tokens not being auto-detected? Or were users unable to see balances or use tokens even after they were added?

**Comment by Gudahtt** [comment]
Tokens are now detected on custom Mainnet endpoints as well, so I'll close this for now. Hopefully that was part of the problem here, or this was some other problem that is already fixed.
