### ISSUE TITLE
Meta mask does not pop up transactions on Ledger with 7.0

### ISSUE THREAD

**Issue by dankurka** [MetaMask/metamask-extension#6993]
With the new version of metamask transaction are not popping up on my ledger anymore.

Before 7.0 transaction data would pop up on the ledger and I would be able to confirm.

These are not popping up anymore so meta mask just gets stuck.
The ledger is connected, shows up in chrome's USB devices. Other software on my Mac can access it just fine.

**Comment by VogtAI** [comment]
Same issue. Version 7.1.1 of Metamask on Chrome, Brave and Firefox. OS: Ubuntu

**Comment by tmashuang** [comment]
Please ensure that the firmware is up to date.

**Comment by tmashuang** [comment]
Close this old issue, tested with Ledger Nano X w/ latest firmware as this comment is written on Ubuntu. If anyone else this issue, contact https://support.metamask.io.
