### ISSUE TITLE
Revise wording - dapp to site 

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#6995]
related to: v7 [#6904 ]

<img width="347" alt="Screen Shot 2019-08-10 at 8 36 45 PM" src="https://user-images.githubusercontent.com/16330048/62828534-96c97700-bbae-11e9-91b8-e3b086a82d82.png">

Change the word dapp to site:

Sharing your address with twitter.com will allow you to interact with this site.  This permission is to protect your privacy by default.  [Learn more](https://medium.com/metamask/privacy-mode-is-now-enabled-by-default-1c1c957f4d57)

**Comment by danfinlay** [comment]
I might also change
> will allow you to interact with this site.

To something like
> will allow this site to view your account. It should only be needed if this is an older web3-compatible site.

**Comment by whymarrh** [comment]
Fixed in 7.1.0 with #7013
