### ISSUE TITLE
Make modals consistent with design system 

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#7003]
<img width="200" alt="Screen Shot 2019-08-07 at 3 11 51 PM" src="https://user-images.githubusercontent.com/1016190/62661511-23153900-b926-11e9-9929-158df2e1c858.png">

shoud be

<img width="200" alt="Screen Shot 2019-08-07 at 3 12 27 PM" src="https://user-images.githubusercontent.com/1016190/62661518-27415680-b926-11e9-9ea0-085de0182d7b.png">

per design system. this applies to all modals

**Comment by Gudahtt** [comment]
Closing, as the modal pictured does not exist anymore.

I'm sure there still exist modals with inconsistent designs, but we can raise new issues for those as we find them.
