### ISSUE TITLE
Displays old ENS logo, should display new one

### ISSUE THREAD

**Issue by brantlymillegan** [MetaMask/metamask-extension#7005]
**Describe the bug**
When I submit transactions to the ENS smart-contracts, MetaMask shows either no logo at all or show the old ENS logo (green with cursive writing) next to the transaction, instead of the new logo (https://github.com/MetaMask/metamask-extension/blob/master/app/images/enslogo.svg). It should show the new logo.

**To Reproduce**
1. Submit a transaction to the ENS smartcontracts (e.g. to register a .eth name)
2. Expand the MetaMask extension to see the pending transaction and list of completed transactions.
3. MetaMask either shows no logo, or shows the old logo. Its should show the new logo for all ENS related transactions.

**Expected behavior**
MetaMask should display the new ENS logo next to ENS-related transactions instead of the old logo.

**Screenshots**
![metamask ens](https://user-images.githubusercontent.com/30162762/62967056-188eef80-bdbd-11e9-99c4-2f8d2165eb5c.png)

**Browser details (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - MetaMask Version [e.g. 5.0.2]

**Additional context**
Here is the correct logo: https://github.com/MetaMask/metamask-extension/blob/master/app/images/enslogo.svg

**Comment by whymarrh** [comment]
[This is an issue with the metadata in eth-contract-metadata, which is referencing the old image.](https://github.com/MetaMask/eth-contract-metadata/blob/master/images/ens.svg)
