### ISSUE TITLE
Pending transactions disappeared after browser restart

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#7006]
**Describe the bug**
I had a couple of pending transactions, very low gas price (intentional). I closed the browser. I opened it ~18 hours later. These transactions were gone from the MM queue without a trace. They still show up on Etherscan as legit tx's waiting to be approved. Can't bump the gas price because the tx is not displayed in MM.

**To Reproduce**
See above

**Expected behavior**
Pending tx's should be kept in the UI queue until inclusion, or a placeholder warning displayed if Infura threw them out of their mempool.

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - MetaMask Version: 7.0.1

**Additional context**
Either way, you guys rock.

**Comment by tmashuang** [comment]
Having tested this on the latest version, 8.1.4 with FF 83.0b10 (64-bit), I am unable to reproduce this issue. Possible in the MM version specified there was a issue with the transaction. If you are still having this issue please provided your state logs to https://support.metamask.io and reference the ticket number here or in a new issue.
