### ISSUE TITLE
Two txs sent when modifying gas for dapp

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#7009]
User reported that he edited the gas on a swap on https://uniswap.exchange.  The transaction sent with the original gas, but then was replaced with the higher modified gas he set.  So two transactions were broadcast for what should have been one.

He attempted this on two different swaps and it happened both times.

Reference support case: 23543

Mac osx 10.14
Chrome 75.0.3770.142
MetaMask v6.7.3

**Comment by tmashuang** [comment]
Review the state logs provided and the transactions in question do not appear in the state logs.
