### ISSUE TITLE
Russian translation incomplete

### ISSUE THREAD

**Issue by zlocate** [MetaMask/metamask-extension#7011]
**Describe the bug**
Russian translation incomplete now.
Difference betwen en and russian translations are 332 phrases. Some screens in UI fully missed at ru translation
Full list missed phrases at gist (https://gist.github.com/zlocate/a0d8f0d857c227fc967b9df5e671d573)

**Screenshots**
![изображение](https://user-images.githubusercontent.com/43764701/63042842-689fac00-beba-11e9-962b-9fd9490ae725.png)

**Comment by zlocate** [comment]
I can partly fix it, want someone help me?

**Comment by zlocate** [comment]
PR #7012 7012

**Comment by Gudahtt** [comment]
The missing translations identified here were added in #7012. Our translations are perpetually incomplete, as we're always adding new text, but I think we can consider this issue as resolved.
