### ISSUE TITLE
Provide confirmation as soon as user pressed 'confirm'

### ISSUE THREAD

**Issue by jbentke** [MetaMask/metamask-extension#7019]
**What problem are you trying to solve?**
I have a react web app and at one screen I send a transaction. The thing is that the promise is only resolved as soon as metamask gets his block confirmations. While that is happening I want to show a loading screen. The thing is that I can not write like "wait for blocks to be mined" because the user didnt even send the transaction yet. Also lets say I want to start doing something else as soon as the transaction is confirmed by the user but not yet mined.

**Describe the solution you'd like**
I am not to sure on what the best way to solve this would be. I guess let the promise finish as soon as the user confirms and provide the confirmation for the successfull transaction another way.
There could also be an event that could be catched, like you did on networkchange.

**Additional context**
Metamask is great :)

**Comment by tmashuang** [comment]
As of v8.1.9 the sendTransaction promise will result with a transaction hash once a user confirms it and hits the network, regardless if it has been mined or not. The proposed solution could be something like transaction button clicked, show loading, and upon txhash dont show loading screen.
