### ISSUE TITLE
Clean up sentry reporting

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#7023]
There's some maintenance we should do to make Sentry more useful
* stop sending dev events
* stop sending dupes or erroneous events
* make sure source maps are working properly

Relates to #4964 and #6256

**Comment by Gudahtt** [comment]
A few errors introduced in v7.1.0 seem to be erroneously reported events. The error is "TypeError: Failed to fetch", and it's caused by `window.close()` being called shortly following a metrics event being sent to Matomo.

**Comment by Gudahtt** [comment]
This was partially completed (Sentry client updated, environment added to allow filtering by environment, inbound filters added to ignore errors from older releases), but the cleanup of actual errors still has to be done.

**Comment by Gudahtt** [comment]
>stop sending dev events

This was done in #9097 and #9095

>make sure source maps are working properly

This was done in #9101

>stop sending dupes or erroneous events

This is an ongoing task that we will track using individual GitHub issues for each error or group of related errors.
