### ISSUE TITLE
Investigate reports of low gas defaults

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#7024]
Several reports suggest that dapp-prompted tx are suggested abnormally low prices (e.g. lower than Eth Gas Station's safe-low).

This has been reported by 0x protocol and several cases via support and UXR. 

This issue is to attempt a reproduction and suggest next steps.

**Comment by danfinlay** [comment]
Here’s a fresh anecdote: https://twitter.com/david_kenahan_/status/1157107620710363136?s=21
