### ISSUE TITLE
"Intrinsic gas too low" failures when user clicks Confirm too fast

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#7028]
I have been investigating sporadic reports of transactions occasionally failing with "Error: intrinsic gas too low."  This led to the filing of [#6770](https://github.com/MetaMask/metamask-extension/issues/6770) (which appears to be a _display_ bug) and [#6950](https://github.com/MetaMask/metamask-extension/issues/6950) as well as [#6949](https://github.com/MetaMask/metamask-extension/issues/6949) and [#6951](https://github.com/MetaMask/metamask-extension/issues/6951), but I had not been able to reproduce that transaction error failure.   I now have a hypothesis from more recent observation.

**Describe the bug**
When the Confirm Transaction dialog is presented, the gas limit is initially 0.  Very soon *after* presentation, the gas limit is estimated and updated, and the Transaction Fee and Total shown are updated.  On a slower or more overloaded computer, this transition takes longer and is easier to see. 

If the user clicks "Confirm" *before* that process is done, the transaction is issued with 0 gas and fails with error "Intrinsic Gas Too Low." 

**To Reproduce**
1. Ideally start with a sluggish computer. 
1. Write/find a dapp which triggers a low-cost transaction, waits for a result from that, and then triggers another.  This may continue several times until one transaction fails, for easier reproduction.
1. Visit the dapp and trigger that action.  
1. Confirm the first transaction.  Leave the mouse in exactly the same position so it's hovering over the Confirm button.
1. When the next transaction confirmation box pops up, as soon as you see it, start clicking madly on that spot and try to get the next transaction Confirmed before the transaction fee updates from 0.  
1. Observe the transaction fail with error "Intrinsic gas too low." (You may need to instrument the dapp to provide this output, but you might also be able to get that by hovering over the "Failed" status in transaction history). 

Note: Unfortunately for this issue but fortunately otherwise, I'm failing to reproduce at step 0 with my primary development machine.  Therefore these are hypothesized steps to reproduce.

**Expected behavior**
The gas limit is computed **before** the confirmation screen is presented, or at least **before** the Confirm button is active. 

**Additional context**
[#3770](https://github.com/MetaMask/metamask-extension/issues/3770)'s [fix](https://github.com/MetaMask/metamask-extension/pull/3831) might have something to do with this but nothing jumps out at me in the [diff](https://github.com/MetaMask/metamask-extension/pull/3831/files).

This may also be the cause of the recently-filed [#7024](https://github.com/MetaMask/metamask-extension/issues/7024) but I didn't file it there because the text of that Issue focuses on the gas *price* while this error is *intrinsic gas too low* (suggesting a problem with the gas *limit*); those might be independent problems.

**Comment by wbt** [comment]
As a fix to this continuing issue, I suggest that the Confirm button be disabled until the gas computation is complete and a nonzero value has been provided for the gas limit.

**Comment by tmashuang** [comment]
Close as I was unable to reproduce this in the current version. We do handle disabled Confirm button state in the UI,
https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js#L792.

Reproduce with this code example, https://jsfiddle.net/ot8rpdkq/, and mercilessly clicking the Confirm button location repeatedly, although I didn't do this on a relative sluggish computer. If I approached this wrong lmk with your reproduction steps and this can be reopened.
