### ISSUE TITLE
Remove Babel 6 and support Node 10 across internal dependency graph

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#7034]
We should remove Babel 6 from and support Node 10 for all of our internal dependencies to avoid time-consuming problems when developing across packages.

These PRs have to be merged and their packages re-published in the following sequence:
1. [x] https://github.com/MetaMask/obs-store/pull/8
2. [x] https://github.com/MetaMask/json-rpc-engine/pull/18
3. [x] https://github.com/MetaMask/eth-json-rpc-middleware/pull/12
4. [x] https://github.com/MetaMask/eth-json-rpc-infura/pull/13
5. [x] https://github.com/MetaMask/eth-json-rpc-filters/pull/9
6. [x] https://github.com/MetaMask/eth-block-tracker/pull/41
7. [x] https://github.com/MetaMask/web3-provider-engine/pull/318
8. [x] https://github.com/MetaMask/KeyringController/pull/32
9. [x] https://github.com/MetaMask/eth-token-tracker/pull/13
10. [x] https://github.com/MetaMask/metamask-inpage-provider/pull/5
11. [x] https://github.com/MetaMask/gaba/pull/145
12. [x] https://github.com/MetaMask/metamask-extension/pull/7037 (PR submitted)

All builds and tests succeed in all feature branches. Until `gaba` is published, building the extension feature branch requires a local copy of the `gaba` branch and using `yarn link` after building `gaba`.

Resolved all security vulnerabilities except one irrelevant and low-priority in `devDependencies`.

**Comment by bdresser** [comment]
cc @kumavis @tmashuang this will require some coordination and QA!

**Comment by kumavis** [comment]
took care of everything but gaba and #7037

**Comment by rekmarks** [comment]
Update, Gaba has been merged and published. Now tracking exclusively in #7037
