### ISSUE TITLE
Default gas price lower than slow processing time

### ISSUE THREAD

**Issue by nitika-goel** [MetaMask/metamask-extension#7040]
When I initiate a transaction to my contract via metamask, it picks up a default gas rate lower than the slowest selection. eg, the slowest rate is 2.7, average is 10 but the default rate set is 2. 

Is that the intended behaviour?

Is there an easy way to select the average rate while initiating the metamask transaction via web3?

**Comment by bdresser** [comment]
no, currently no way to specify gas defaults when prompting a transaction, although the user can edit the gas they're paying

report of low defaults relates to https://github.com/MetaMask/metamask-extension/issues/7024

**Comment by nitika-goel** [comment]
Thanks @bdresser for the prompt response. We are using metamask as the sole way to interact with our contracts at https://app.nexusmutual.io. There are times when the user is not advanced enough to manually adjust gas price.
I only wish to understand here that is the Metamask team working on this enhancement and if yes, what is the timeline expected.
