### ISSUE TITLE
Popup may sometimes be not activating

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7051]
In a user research session, clicking `Connect` in a dapp seemed to not trigger the popup.

Are there cases where the popup is not being activated? I know, this is hard to investigate without a concrete repro, but opening the issue because the OpenSea dev said they have heard of this reported by users.

It could have just been that a subsequent click hid the popup, making this part of #7022.

**Comment by jennypollack** [comment]
possibly related: just got this failure in an e2e firefox test on circleci from an unrelated code change

1) MetaMask
Send ETH from dapp using advanced gas controls
initiates a send from the dapp:
Error: No window with title: MetaMask Notification
at switchToWindowWithTitle (test/e2e/helpers.js:110:11)
at switchToWindowWithTitle (test/e2e/helpers.js:119:18)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by bdresser** [comment]
From #7670


>This is not a bug, I just think the way MM behaves is "odd"
>If the MM pops up because a website has initiated a transaction, (ofc due ultimately to the user's interaction with the website), this is good. If a subsequent transaction is initiated, the popup appears once again, this is also good and what I would expect.

>However:

>If the MM popup is rejected, subsequent transactions initiated by the website do NOT launch the popup, instead the popup is hidden, all that shows is a notification on the MM icon in the bar at the top (chrome). I think this is wrong, the popup should appear again, every time. It is confusing because it is inconsistent behaviour.

**Comment by Gudahtt** [comment]
I was able to reproduce this by clicking "Connect" on the test dapp, the closing the notification window quickly while it was still loading. Subsequent notification windows would not appear.
