### ISSUE TITLE
Approval screen bugs.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#7061]
**Describe the bug**
![image](https://user-images.githubusercontent.com/886059/63590169-acdb2c80-c5dd-11e9-9424-61c766f4c6b4.png)
As seen in the above screenshot (Firefox 68), the approval screen has a bunch of overflow problems as well as incorrect/missing details.

1. The yellow banner says "to spend up to 0 of your ." when it should be saying "to spend up to X of your DAI".
2. **_SECURITY_**: The amount being approved shows up as `1.157...` but it is really `e+58` at the end!  This UI is suggesting that I only am approving ~1.18 DAI when really I'm approving effectively infinite DAI!
3. The ETH amount being approved is overflowing and doesn't use exponential form, which is different from the DAI amount on the line above it.  This reinforces to me (the reader) that I'm only approving ~1.158 DAI.
4. The amount + gas fee is also overflowing and hiding the `e+58`.
5. The final total is in `$` even though I have configured MetaMask to be denominated in ETH.
6. At least on that last line I see the `e+59`, which was the only indication that a giant number is involved.
7. The total implies that the amount I'm _sending_ is `1.18e+58`.  While I do appreciate/approve of the fact that approvals are _basically_ spending money, I think it is valuable to make it more clear to the user that you aren't actually sending approved money yet, you are merely entrusting it to the contract.
8. I have a horizontal scroll bar which only lets me scroll the overflowed total, not anything else.

**To Reproduce**
1. Go to uniswap.exchange.
2. Choose a token from the dropdown.
3. Click the Unlock button.
4. Notice the approve dialog.

**Expected behavior**
The approve dialog isn't rife with bugs, errors, security vulnerabilities and overflows.

**Screenshots**
![image](https://user-images.githubusercontent.com/886059/63590557-c0d35e00-c5de-11e9-8ffc-0501b19b3338.png)

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - MetaMask Version: 

**Additional context**
I put all of this into one issue to save myself time and because I don't know which bugs are related, but it probably makes sense to break this up into smaller issues.  Feel free to close this once the issue is broken apart.  Overall the Approval UI is incredibly unpolished, to the point where it is hurting more than helping compared to presenting a generic contract call UI.

**Comment by Gudahtt** [comment]
Thanks for the feedback, and sorry for the delay in responding! The Approve screen was redesigned since this issue was made, so most of these no longer apply. I'm going to close this for now, but please feel free to raise any issues that remain.
