### ISSUE TITLE
The MetaMask Throws Error: VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by bayanhd** [MetaMask/metamask-extension#7062]
I'm new to Blockchain world, lacking experience and I'm looking for some assistance.
Now, I'm working on an Ethereum Blockchain project to transfer the ownership of stored devices by using local web3 provider HTTP://127.0.0.1:7545 at _truffle environment_.
Truffle v5.0.27 (core: 5.0.27)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
and lastest version of metamask

**Browser details 
 - OS: [Windows 10]
 - Browser _tried both_ [firefox, chrome]
 - MetaMask Version [7.0.1]

I'm trying to transfer the ownership (between two local addresses ) but the Metamask throws the following error.

**Error: `Error: Error: [ethjs-rpc] rpc error with payload {"id":6549844379355,"jsonrpc":"2.0","params":["0xf8ab018504a817c800827fb494d218568e2e426b545a077b633a828416555e383d80b844de22c80100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001822d45a085c5496bf9a54cf10d7809c595ff67f671eec7e5e42bd828890b42f1effe603da004ab55578fc681898e7fdc63e5a77dc88b89deef3f1e65d77b20b877b3e9a6d1"],"method":"eth_sendRawTransaction"} Error: VM Exception while processing transaction: revert**`

**The following shot is for the transform function in the smart contract**
![Picture1](https://user-images.githubusercontent.com/35135830/63601204-fc483b00-c592-11e9-8532-b842ef01bc8c.png)

**The following shot is for the deploy the function in JavaScript**
![Picture2](https://user-images.githubusercontent.com/35135830/63601203-fc483b00-c592-11e9-9184-2ef3dc1ab42b.png)

**Screenshot from the result (Console)**
![Picture3](https://user-images.githubusercontent.com/35135830/63601531-99a36f00-c593-11e9-87f9-d5ab3fea3276.png)

Looking for you help to resolve the error
Thanx.

**Comment by Gudahtt** [comment]
Thanks for the report! Is this behaviour still reproducible in the latest version of MetaMask?

**Comment by Gudahtt** [comment]
I'm going to close this for now, because of the age of the report and the lack of response, and because I'm not sure how I'd go about trying to reproduce this.
