### ISSUE TITLE
address book new contact (+) location maybe anti-pattern

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#7065]
the add contact button (+) and the settings close (x) end up in the same spot in both full page view and the dropdown, feels like a UX anti-pattern
<img width="356" alt="Screen Shot 2019-08-26 at 1 26 57 PM" src="https://user-images.githubusercontent.com/3885055/63687568-3a4c9580-c805-11e9-91d7-6781d4ae12e1.png">

<img width="354" alt="Screen Shot 2019-08-26 at 1 27 09 PM" src="https://user-images.githubusercontent.com/3885055/63687572-3f114980-c805-11e9-9e63-58c05b81c779.png">

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/9883
