### ISSUE TITLE
Recurring transactions

### ISSUE THREAD

**Issue by ntninja** [MetaMask/metamask-extension#7074]
**What problem are you trying to solve?**
Often one sees people asking for donations on their websites listing an ETH/ERC-20 address without any associated infrastructure (such as a payment gateway that processes the donations) being set up on the receiver's side. While it is not hard in this case to make a one-off donation thanks to Metamask (some simple [JavaScript-based solutions](https://eth-button.github.io/eth-button/) exist to streamline the whole process even further) it does require users to regularily go back to the given web site and submit another donation in the next week/month if they desire the donation to be recurring.

**Describe the solution you'd like**
In order to greatly simplify the act of donating at regular intervals, it would very useful if Metamask had some facility to perform some action again after a given timeframe. For instance, in case of monthly transactions Metamask would:

  1. Batch all monthly transaction and wait until the, e.g, 1st of the following month
  2. After this (the next time Metamask is started), it would show a notification / change the icon color to alert the user that there are some pending transactions needing signing
  3. Upon user interaction, a transaction popup would open showing all pending transactions, including user provided comments, and allowing them to be signed

Note that this is not about [ERC777](https://eips.ethereum.org/EIPS/eip-777) support as that relies on transaction receivers to register *operators* that may send transaction on the users behalf and are managed/triggered by the receiving entity (similar to the Direct Withdrawal approach used in the banking industry). The use-case described above is for users who voluntarily like to regularily *send* transaction to others (similar the Standing Order type of transfer available in banking in many countries).

**Comment by tmashuang** [comment]
You can push feature requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas) so the team can keep closer eyes on all suggestions / requests.
