### ISSUE TITLE
Prevent source map console warnings caused by MetaMask bundles

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#7077]
**Describe the bug**
When I open the browser console on _any_ page in my browser I get warnings about being unable to find source maps for MetaMask's `sourcemaps/contentscript.js` and `sourcemaps/inpage.js.map`.  It would be great if having MetaMask installed didn't result in an error in my console on every page I load.

**To Reproduce**
1. Install MetaMask into Firefox.
2. Open console.
3. Notice the "source map error" warnings.

**Expected behavior**
No errors in my console when loading a page with MetaMask injected into it.

**Screenshots**
N/A

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - MetaMask Version: 7.0.1

**Additional context**
Since this is an extension, the size increase from source maps should not be significant enough to cause any problems, as they aren't loaded on every page load and users are accustomed to extensions having non-zero download times.  You _may_ need to make the sourcemaps [web accessible](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources), though testing is necessary to figure out whether that is required for Firefox to be able to fetch a source map.

**Comment by ForbiddenEra** [comment]
Oh, so this isn't because of libraries loaded on my webpage.. it's because of an extension.. annoying

+1

**Comment by abitrolly** [comment]
The same problems with latest MetaMask 7.3.1 on Firefox 70.

![image](https://user-images.githubusercontent.com/8781107/68082013-3736dc80-fe28-11e9-8f35-d89caaf474a8.png)

**Comment by abitrolly** [comment]
Source map processing starts in https://github.com/MetaMask/metamask-extension/blob/eed4a9ed6547c76299da086916168c48a4e8fef4/gulpfile.js#L595

**Comment by abitrolly** [comment]
Source maps are processed in `bundleTask` function. This is as far as I could get.

https://github.com/MetaMask/metamask-extension/blob/eed4a9ed6547c76299da086916168c48a4e8fef4/gulpfile.js#L595

Now need to evaluate how big they are and how to best handle them. Are they fetched only when errors occur, or need to be present always?

**Comment by abitrolly** [comment]
The path to sourcemaps is specified as relative during the build process.

https://github.com/MetaMask/metamask-extension/blob/eed4a9ed6547c76299da086916168c48a4e8fef4/gulpfile.js#L406

And the same path is shown when inspecting MetaMask extension from `about:debugging#/runtime/this-firefox`.

![image](https://user-images.githubusercontent.com/8781107/68082364-d5c53c80-fe2c-11e9-8eb0-11d0bc603251.png)

Judging be extension path all scripts are in root and there is no parent directory. Need see if the sourcemaps are inside the downloaded extension and where are they unpacked.

**Comment by abitrolly** [comment]
GitHub silently eats my comments. Attempt no.3 to paste the link to code section where source maps are generated.

https://github.com/MetaMask/metamask-extension/blob/eed4a9ed6547c76299da086916168c48a4e8fef4/gulpfile.js#L595

**Comment by abitrolly** [comment]
GitHub silently eats my comments. Attempt no.3 to paste the link to code section where source maps are generated.

https://github.com/MetaMask/metamask-extension/blob/eed4a9ed6547c76299da086916168c48a4e8fef4/gulpfile.js#L595

**Comment by abitrolly** [comment]
GitHub silently eats my comments. Attempt no.3 to paste the link to code section where source maps are generated.

https://github.com/MetaMask/metamask-extension/blob/eed4a9ed6547c76299da086916168c48a4e8fef4/gulpfile.js#L595

**Comment by MicahZoltu** [comment]
Extension size-on-disk is much less meaningful than web app size-on-disk.  That being said, source maps are fetched lazily, when someone opens their browser debugger.  The extension however should probably ship with them so that when the browser _does_ ask for them, they are present.

**Comment by abitrolly** [comment]
I checked my profile dir, found MetaMask extension bundled in `.xpi` file, and there are no `.map` files or `sourcemaps` dir inside. They need to be either bundled or provided through CDN. (IPFS?)

**Comment by abitrolly** [comment]
> Extension size-on-disk is much less meaningful than web app size-on-disk

Which web app do you refer to? MetaMask in archived form of `.xpi` takes 10Mb. I don't have toolchain ready to compile sourcemaps and see how much do they take.

**Comment by abitrolly** [comment]
Instead of shipping MetaMask with sourcemaps, why minimize scripts in the first place? They are already compressed.

**Comment by MicahZoltu** [comment]
Original source files are TypeScript I think, so source maps are likely necessary even without minification.  That being said, I agree that minification and bundling here hurts rather than helps, but that is just my personal opinion.  The missing source maps however cause problems for end users and developers.

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/68271772-c46d7180-0072-11ea-908c-1a068288154f.png)

GitHub tells it is JavaScript.

**Comment by Gudahtt** [comment]
I've just renamed this issue to reflect the main problem being addressed (the source map warnings), rather than the proposed solution. We can solve this by means other than adding the source maps to the bundle. Though that's definitely still worth considering, and would have other benefits!

**Comment by kumavis** [comment]
this was fixed in the build sys refactor that never landed

**Comment by maybeast** [comment]
+1 would love to get rid of these annoying warnings in the console.

**Comment by flcoder** [comment]
Yeah, when I'm developing an app, I rely on the console a lot and it really slows me down every time I see the warnings and think, oh right, Metamask...  I mean, sure we could all add some filters or something, but honestly, I personally wouldn't release code for consumers which generates these kind of nuanced artifacts.  I generally stop using libraries that directly or indirectly take over my console.  Like I think PIXI.js purposely outputs its version #.  Stuff like that is very annoying and doesn't seem at all professional to me.  I really hope Metamask devs can get this resolved soon.  Cheers!

**Comment by ryanml** [comment]
@flcoder this fix will be part of our upcoming 9.5.0 release, thanks!
