### ISSUE TITLE
MetaMask does not restore Firefox window size

### ISSUE THREAD

**Issue by MaxXor** [MetaMask/metamask-extension#7082]
**Describe the bug**
When using Firefox with maximized window the MetaMask popup (i.e. to allow access or confirm a transaction) does change the non-maximized window size of Firefox.

**To Reproduce**

1. Use Firefox with maximized window
2. Go to https://kyberswap.com
3. Click on MetaMask and wait for the popup
4. Close the popup or allow access (doesn't matter)
5. Now click the maximize button to un-maximize Firefox
6. Firefox window now has the size of MetaMask popup

**Expected behavior**
Restore old window size of Firefox.

**Screenshots**
![Screenshot from 2019-08-30 22-05-50](https://user-images.githubusercontent.com/7271470/64048610-761f8c00-cb72-11e9-9a37-315ee5857d8a.png)

**Browser details (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 68.0.2
 - MetaMask Version: 7.1.0

**Comment by Gudahtt** [comment]
Thanks for the report! I was unable to reproduce this on Ubuntu, and it sounds like a Firefox or OS/Window manager bug rather than a MetaMask bug. I'm going to close for now, but please let me know if you are still having this problem, or if you suspect there is something we can do to prevent it.
