### ISSUE TITLE
How to run metamask from development build?

### ISSUE THREAD

**Issue by devzyf** [MetaMask/metamask-extension#7092]
The extension build page write:
_Install Node.js version 10
If you are using nvm (recommended) running nvm use will automatically choose the right node version for you.
Install Yarn
Install dependencies: yarn
Build the project to the ./dist/ folder with yarn dist.
Optionally, to start a development build (e.g. with logging and file watching) run yarn start instead.
To start the React DevTools and Redux DevTools Extension alongside the app, use yarn start:dev.
React DevTools will open in a separate window; no browser extension is required
Redux DevTools will need to be installed as a browser extension. Open the Redux Remote Devtools to access Redux state logs. This can be done by either right clicking within the web browser to bring up the context menu, expanding the Redux DevTools panel and clicking Open Remote DevTools OR clicking the Redux DevTools extension icon and clicking Open Remote DevTools.
You will also need to check the "Use custom (local) server" checkbox in the Remote DevTools Settings, using the default server configuration (host localhost, port 8000, secure connection checkbox unchecked)
Uncompressed builds can be found in /dist, compressed builds can be found in /builds once they're built._

When i build and run with yarn start, nothing happen, i start up browser to view localhost:8000, there nothing here, i need help on actual debug/development after the yarn start. 
many thanks

**Comment by bmcd87** [comment]
@devzyf In chrome, you need to go to the ... menu->More tools->Extensions. Then click "Load Unpacked" in the top left corner, and select the dist/chrome folder. The process is similar for other browsers. Seems like these build instructions assumed some previous knowledge of extension development.

**Comment by devzyf** [comment]
thanks bmcd87, what the server part from yarn start actually did? just monitor the incoming call from metamask? i finger out few days before, and confuse about the actual need of extension server, if i want to deploy the metamask to my own server, what do i need ?  do i need to change the metamask extension code to suit new server configuration?

**Comment by bmcd87** [comment]
I'm pretty sure it is just starting the local react-dev server, which builds and reloads the extension automatically when you make changes to the source code. It's not a backend server that you need to run metamask itself.

**Comment by jennypollack** [comment]
Thanks @bmcd87! Closing this, but let us know if you have any other issues @devzyf
