### ISSUE TITLE
metamask privacy mode disappeared

### ISSUE THREAD

**Issue by kgh2927845** [MetaMask/metamask-extension#7095]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - MetaMask Version [e.g. 5.0.2]

**Additional context**

**Comment by bdresser** [comment]
privacy mode is now enabled by default
