### ISSUE TITLE
Investigate/fix "Login with Metamask then crashes browser"

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7097]
As reported in [this discord](https://discord.gg/vjfbvP) by `FunFair-Josh`:

## Context
Apparently in the last 7 days. This suggests the bug may have not been present in [7.0.1](https://github.com/MetaMask/metamask-extension/releases/tag/v7.0.1) and was introduced in [7.1.0](https://github.com/MetaMask/metamask-extension/releases/tag/v7.1.0), whose biggest functional addition was [showing received transactions](https://github.com/MetaMask/metamask-extension/pull/6996/files).

## System Info
On Windows 10:
- Pro Version 1809 OS 1173.678
- Version 1903 OS Build 18362.295

Chrome
- Version 76.0.3809.132 (Official Build) (64-bit)

## Reproduction Steps
1. Close all your browser windows on Chrome.
2. Make sure you're logged out of MetaMask.
3. Go to a web3 enabled site (Works on cryptokitties.co )
4. Sign into MM when prompted
5. Wait
6. The browser crashes

**Comment by danfinlay** [comment]
Checking `chrome://crashes` presented the user with this justification:

![unknown2](https://user-images.githubusercontent.com/542863/64213124-a01dca80-ce60-11e9-9c04-a67657b87a23.png)

This suggests there is an invalid memory access being attempted after login. I'm not even sure how we would attempt an invalid memory access, being a JS app.

Could this be a callback being triggered after the UI page is closed? Maybe the callback for the "incoming transactions"?

**Comment by danfinlay** [comment]
We have some crash dumps here:
https://drive.google.com/drive/folders/10lCkKueWfIFH9rtw9ywoTyLHu_81zJFs

**Comment by danfinlay** [comment]
Since this has only been seen on Chrome for Windows, and since it involves an invalid memory access attempt (something I'm not sure how to achieve with JS anyways), it seems plausible that this could be a bug in Chrome for Windows, so we should open an issue there.

**Comment by danfinlay** [comment]
I've opened an issue with Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1001284

**Comment by Yzhibin** [comment]
This issue also happens on Chrome for Mac, just fyi

**Comment by danfinlay** [comment]
@Yzhibin You're the first person to report experiencing this on a mac. Could you share your exact system and chrome versions?

**Comment by OleksiiFalkoDevPro** [comment]
I also saw this issue on MacOs with Chrome browser today.
Which information do you need? Will try to reproduce and provide that.

**Comment by jflatow** [comment]
Can confirm we are seeing this issue in our office and on our Discord for folks who have upgrades >= 7.1.0.

**Comment by danjm** [comment]
@OleksiiFalkoDevPro and @jflatow: when you saw this, was the issue experienced after taking the same steps described in danfinlay's first post above?

**Comment by jflatow** [comment]
Yes, using app.compound.finance

**Comment by danfinlay** [comment]
We haven't had anyone able to reproduce this issue after upgrading to Chrome 77. I think we could consider this closed. I will reopen it if anyone can reproduce after upgrading to Chrome 77.

**Comment by jflatow** [comment]
Works for us!

**Comment by pakaplace** [comment]
Was crashing for me on Chrome 76.x on OSx 10.14. Fixed with the update to Chrome 77.
