### ISSUE TITLE
Link "continuing at your own risk" not working

### ISSUE THREAD

**Issue by JakubKrajc** [MetaMask/metamask-extension#7100]
**Describe the bug**
When site detected as phishing, metamask redirect browser to the "Ethereum Phishing Detection" page. On this page is link "continuing at your own risk", but when clicked on this link nothing hapens (it works few weeks ago). It is imposible to continue to flagged site without deactivating metamask plugin. Tested on Chrome and Firefox on Linux Mint. I tried remove and install plugin.

**To Reproduce**
1. Install and activate Metamask plugin
2. Go to some phishing flagged site (http://cryptokitties.com)
3. Browser is redirected to "Ethereum Phishing Detection" (in chrome: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html#hostname=cryptotittiez.com&href=https%3A%2F%2Fcryptotittiez.com%2F in Firefox: moz-extension://9cf3a0b0-364d-46c2-bdc6-ac641ac39a33/phishing.html#hostname=cryptokitties.com&href=http%3A%2F%2Fcryptokitties.com%2F)
4. Clicking on link "continuing at your own risk." (at the end of forth paragraph) do nothing,

**Expected behavior**
Clicking on link "continuing at your own risk." redirect to/open flagged site.

**Browser details (please complete the following information):**
 - OS: Linux Mint 19.1
 - Browser: chrome, firefox
 - MetaMask Version: 7.1.0

**Comment by floatiepen** [comment]
Please fix this!  I'm trying to load a page hosted on droppages.com that doesn't even interact with MetaMask or crypto currency in any way. I understand an arbitrary web host (especially one with such a low bar to entry as DropPages) may be a host to a malicious page. I'm even content with a speed bump "Hey, something bad may happen!", but clicking the "continue at your own risk" link does nothing.

The supplied info link (https://etherscamdb.info/domain/droppages.com) even suggests the site is safe and also says the service has moved: https://CryptoScamDB.org

For now, the only way to load my site is to disable MetaMask (which is tedious)

**Comment by PatrickT80** [comment]
Today i've installed the extension, and this feature continues to not working.
Blocking access to free-ethereum.io.
I've searched on cryptoscamdb and this domain isn't listed.
How to continue to site blocked bye the extension?
