### ISSUE TITLE
"accountsChanged" event not fired upon logout (Chrome)

### ISSUE THREAD

**Issue by aaronbarnardsound** [MetaMask/metamask-extension#7101]
**Describe the bug**

The `accountsChanged` event does not fire when a user logs out of MetaMask on Chrome, but works correctly on FireFox.

**To Reproduce**

- Open up Chrome
- Register a callback for the `accountsChanged` event:

```javascript
window.ethereum.on('accountsChanged', console.log)
```

- Login to MetaMask
- Logout of MetaMask
- Chrome will not show a log, but Firefox will

**Expected behavior**

The `accountsChanged` event should call the callback when the user logs out as it does in Firefox.

**Browser details (please complete the following information):**

 - OS: OS X
 - Browser: chrome
 - MetaMask Version: `7.1.0`

**Comment by Gudahtt** [comment]
I was able to reproduce this. Both Chrome and Firefox correctly trigger this event upon the initial connect request/login, but the behavior differs when you log out and back in again.

Firefox will fire an event for logout (with `[ undefined ]`), and will fire another event for the login. Chrome doesn't fire the event for the logout or the second login.
