### ISSUE TITLE
Incoming transactions not shown in history

### ISSUE THREAD

**Issue by c0dehunter** [MetaMask/metamask-extension#7103]
I can only see outgoing transactions, but not incoming:

![image](https://user-images.githubusercontent.com/1484658/64249132-3dd1d200-cf13-11e9-8c22-989c1ccbe8cc.png)

Compared to Etherscan:

![image](https://user-images.githubusercontent.com/1484658/64249153-504c0b80-cf13-11e9-91bb-11940144472e.png)

Is this not working yet?

**Comment by bdresser** [comment]
This feature is in v7.1.0 and later. What version are you running?

**Comment by c0dehunter** [comment]
Hi @bdresser, thanks for prompt response. 

I am using v7.1.0:

![image](https://user-images.githubusercontent.com/1484658/64286874-967a8c80-cf5e-11e9-95af-d32412684976.png)

I am also using Brave Browser, but it's based on Chrome so I don't think it has to do anything with this issue. I also tried with Chrome, where the TX history is empty (maybe it needs some time to sync with network? Will check again in a few hours):

![image](https://user-images.githubusercontent.com/1484658/64287253-76979880-cf5f-11e9-8318-9a12ccf18d5c.png)

**Comment by eclairss17** [comment]
Hello, metamask only displays the record of transactions made through it , you can check the incoming transactions in etherscan for that .

**Comment by c0dehunter** [comment]
@eclairss17  that explains it. But I must admit - what a weird behavior! It would make sense to show all transactions involving this address.

**Comment by tmashuang** [comment]
Settings > Security & Privacy > Show Incoming Transactions

**Comment by bdresser** [comment]
sorry, @tmashuang is correct, this feature is available in 7.1.0 and later but requires enabling it manually in settings.

**Comment by c0dehunter** [comment]
I enabled this setting and can't see incoming TXs even after 24h. Does it work retroactively or only for incoming TXs occured AFTER enabling this setting?

**Comment by tmashuang** [comment]
Are you seeing incoming txs on any other network, just not Mainnet?

**Comment by c0dehunter** [comment]
@tmashuang, please excuse my ignorance but I have no idea about other networks (I am not familiar with them). I will just post some screenshots here, maybe they help? Please reach out for any other info I can provide.

![image](https://user-images.githubusercontent.com/1484658/65221749-f2e0be80-dabd-11e9-94d3-a40be78f92b4.png)

![image](https://user-images.githubusercontent.com/1484658/65221771-f96f3600-dabd-11e9-9ed1-5c8340d8396e.png)

![image](https://user-images.githubusercontent.com/1484658/65221786-00964400-dabe-11e9-8a41-b50d69e404f1.png)

![image](https://user-images.githubusercontent.com/1484658/65221830-16a40480-dabe-11e9-93c5-741a010ae383.png)

![image](https://user-images.githubusercontent.com/1484658/65221866-2b809800-dabe-11e9-89e5-266211176868.png)

All of the above screenshots are from Brave browser. I also tried on Chrome (I made sure to enable Show Incoming Transactions setting), but there I don't see any TXs at all:

![image](https://user-images.githubusercontent.com/1484658/65221948-6387db00-dabe-11e9-8cab-08364e97cb44.png)

**Comment by tmashuang** [comment]
We initially populated the whole list for Mainnet when the feature landed, but found that issues of cluttering the tx list. For Mainnet, it will not show previous transactions before the feature is turned on. Transactions made to the address after turning on Incoming Transactions will show subsequent incoming transactions.

**Comment by ThePirate42** [comment]
I can't find the setting anymore
