### ISSUE TITLE
ethereum.selectedAddress is not reset after Sign Out

### ISSUE THREAD

**Issue by faudisio** [MetaMask/metamask-extension#7109]
**Describe the bug**
If the user Signs Out from MetaMask the ethereum.selectedAddress still contains the previously selected address

**To Reproduce**
1. Create a simple html page with a button that prints ethereum.selectedAddress to the console
2. Sign In to MetaMask 
3. Press the button
4. The console shows the selected address
5. Sign Out from MetaMask
6. Press the button
7. The console still shows the selected address

**Expected behavior**
When the user does a Sign Out ethereum.selectedAddress should be reset to undefined

**Browser details (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browsers: Chrome 76.0.3809.132 and 
Brave 0.68.133 (with Chromium 76.0.3809.132)
 - MetaMask Version 7.1.0

**Comment by Gudahtt** [comment]
This seems related to #7101

**Comment by tmashuang** [comment]
Issue still persists even after PR has been merged.

**Comment by Gudahtt** [comment]
False alarm - it was fixed after all.

**Comment by faudisio** [comment]
Thanks all. In which version and when will the fix be released?

**Comment by Gudahtt** [comment]
This will be a part of v7.2.1, which is being released this week.
