### ISSUE TITLE
MetaMask is not authorized to access this domain

### ISSUE THREAD

**Issue by tcncoop** [MetaMask/metamask-extension#7114]
**Describe the bug**
When attempting to sign on colony.io in Opera, metamask says it is not authorized to access the domain. Usually, a pop up will come up and ask me to sign to enter the domain. This seems to work on other browsers and the same browser on other machines. but I cant find a reason it wouldn't work here.  This is the only way Ive ever used metamask before, so please forgive me.

**To Reproduce**
1. Run Opera
2. Navigate to https://colony.io/connect
3. Click on "Metamask" below the url

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
![Opera Snapshot_2019-09-05_142811_colony io](https://user-images.githubusercontent.com/54962141/64382036-75ab4900-cfe9-11e9-85ef-84652c5e08dc.png)

**Browser details (please complete the following information):**
 - Windows 10 v1803
 - Opera Version:63.0.3368.53
 - MetaMask Version 3.14.1

**Additional context**
As stated before, it works on other machines with the same browser, just not this one. And I want to know why it isnt so, if it happens on someone else's machine, I know how to fix it.

**Comment by bdresser** [comment]
MetaMask for Opera is several major versions behind our current production version. We recommend using with Chrome or Firefox. A quick pass through the onboarding flow in Chrome worked fine with MetaMask for me!
