### ISSUE TITLE
Sending eth to contract fallback fails with default gas

### ISSUE THREAD

**Issue by miguelmota** [MetaMask/metamask-extension#7115]
MetaMask is setting the gas limit of 21000 by default for eth sends even if it's to a contract which will always fail. An improvement would be to add additional gas padding if the the receiving address is a contract. 

[Example failed tx](https://etherscan.io/tx/0x2aa3e8fd667dde4a22bab1a881604debb8027130c515f20ce80710f642899068)

**Comment by jennypollack** [comment]
+1 
I started noticing this recently on gnosis branch but it doesn't happen every time
if we detect a contract address that is a valid recipient we should do an `estimate_gas` call instead of using the gas defaults set in the frontend and the `gasLimitSpecified` flag

**Comment by rstormsf** [comment]
@danfinlay 
100% agree. Metamask could make 1 extra call to see if it's an account or contract

```js
const bytecode = await web3.eth.getCode('REGULAR_ADDRESS')
console.log(bytecode) // returns 0x for regular accounts
```

**Comment by danfinlay** [comment]
Yeah that's what I thought we did, so this is definitely a bug in the meanwhile. Avoiding `estimate_gas` when not a contract was one strategy for improving time to estimate gas, which I guess is a little surprising, since you'd think any node would be quick to estimate 21000 when it was not a contract and a simple ether send.

**Comment by danfinlay** [comment]
Oh man, this bug is so bad now blog posts are talking about how to educate users around it. We need this fixed soon. This must have been introduced recently, there's no way this has been sitting around.
https://medium.com/wearekickback/integrating-a-contract-based-wallet-into-your-dapp-1721c1a1148b

**Comment by danfinlay** [comment]
Here’s the line that claims to be doing this. Does look like a regression.
https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/tx-gas-utils.js

**Comment by robertmagier** [comment]
It seems that issues is back in version 7.7.4
