### ISSUE TITLE
Regression: Skipping phishing screen no longer works

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7119]
Reproduction:

1. Visit a blocked site.
2. Click the "continue anyway" button
3. Nothing happens

What should happen:

The user should be directed to the target site.

**Comment by bdresser** [comment]
dupes https://github.com/MetaMask/metamask-extension/issues/7119

**Comment by danfinlay** [comment]
Can't dupe something with itself :)

**Comment by floatiepen** [comment]
> dupes #7119

I think you meant #7100

**Comment by danfinlay** [comment]
Oh, thanks for linking, @floatiepen!
