### ISSUE TITLE
The method txpool_content does not exist

### ISSUE THREAD

**Issue by adamsoffer** [MetaMask/metamask-extension#7121]
**Describe the bug**
Using the `web3-eth-txpool` package throws the following error: `The method txpool_content does not exist`

**To Reproduce**
```
const { TxPool } = require('web3-eth-txpool')
const txPool = new TxPool(
  'wss://mainnet.infura.io/ws/v3/[project_id]',
  null,
  { defaultAccount: '0x...' },
)
txPool
  .getContent()
  .then(data => {
    console.log(data)
  })
  .catch(e => {
    console.log(e)
  })
```

**Expected behavior**
`txPool.getContent()` should return a list of incoming transactions for the specified account

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser Brave
 - MetaMask Version [e.g. 7.1.1]

**Additional context**
Using web3 1.2.1

**Comment by Gudahtt** [comment]
`txpool` methods are not supported by Infura; see here: https://github.com/INFURA/infura/issues/55
