### ISSUE TITLE
Display contract address + identicon when giving permission to it

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#7124]
**What problem are you trying to solve?**
When you're asked to give permission to a contract (e.g. giving allowance to an ERC20 token balance), the basic approval window gives you no idea what it is exactly that you're giving permission to. It just says "New contract". (Which implies you're about to deploy a new contract, which is not the case at all.) Malicious sites/hijacked frontends could use this to deceive users and steal from them.

If you speak bytecode, you can go to "Data" and may be able to make it out, but otherwise you're in the dark.

![0](https://user-images.githubusercontent.com/7106231/64497672-50039580-d2b0-11e9-94f4-d65905fa44a3.png)

**Describe the solution you'd like**

Instead of "New contract", display the address identicon and a shortened version of the address. Also display the full address as a tooltip upon hovering over the address, copy it upon clicking, and display a button that links to the contract's Etherscan page.

**Comment by bdresser** [comment]
This looks like a bug - we should only show "New Contract" when the tx has no recipient. Will investigate. 

Would you mind sharing what site you were using when you saw this?

**Comment by leafcutterant** [comment]
I was giving approval at 1inch.exchange.

**Comment by danfinlay** [comment]
I've reproduced this, confirmed it is a bug:

We are showing "New Contract" incorrectly here. The transaction is in fact sending to a token address specified by the dapp, but our confirmation window is mis-representing it. I'd like to get a fix in [RC 7.2.0 for early next week's release](https://github.com/MetaMask/metamask-extension/pull/7138).

**Comment by danjm** [comment]
@danfinlay What are your repro steps?

**Comment by tmashuang** [comment]
Another route that doesn't involve token address will result in a `New Contract` recipient is
`web3.eth.sendTransaction({from: web3.eth.accounts[0], to: ''}, console.log)` in the console.

**Comment by danjm** [comment]
Actually, I was able to create with an approve request on https://1inch.exchange/#/

**Comment by leafcutterant** [comment]
Requesting re-opening.

With the new permission dialogue, no reliably attributable information displayed by default, only the favicon and the name of the website.

IF you scroll down and click "Full tx details", you can see the first 8 and last 4 hex chars, but that's it.

I propose the following (party overlaps with my initial proposal):

* display an identicon without having to click anywhere. People are visual, so someone using a contract frequently will notice if they're being duped quicker than reading a contract address.

Under "Full tx details",

* display the full contract addy in full
* a button that copies the addy
* another button that takes you to the Etherscan page of the contract
