### ISSUE TITLE
Blocked site empowr.com causes MM extension to crash

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#7133]
**Describe the bug**

**To Reproduce**
1. Go directly to http://empowr.com

**Expected behavior**
The Ethereum Phishing Detection screen should display, but instead, empowr site loads and MetaMask crashes.

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/64559037-f2506700-d30a-11e9-8e3a-2560549a096f.png)

**Browser details (please complete the following information):**
 - OS: OSX Mojave 10.14.6
 - Browser Chrome & Brave
 - MetaMask Version 7.1.1

**Comment by tmashuang** [comment]
As of 12-16-20, The url is picked up by the phishing detector.
