### ISSUE TITLE
MM assumes transaction was confirmed when it first sees the confirmation, not when it was actually confirmed

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#7135]
**Describe the bug**
See title.

**To Reproduce**
1. Submit tx such that it doesn't confirm in the next block
2. Log out of MM or exit browser
3. Wait until tx is confirmed (i.e. included in a valid block) (let's call this time t0)
4. Wait some more time
5. Open browser and/or log into MM (let's call this t1)
6. The tx cell says the tx was confirmed at t1

**Expected behavior**
The tx cell should say the tx was confirmed at t0.

**Browser details (please complete the following information):**
 - Browser: Firefox
 - MetaMask Version 7.1.1

**Comment by danjm** [comment]
To recreate:

1. Go through the MetaMask send flow to create and send a transaction. Do this on Ropsten or Rinkeby, not localhost.
2. As soon as the transaction is created (and in a pending state) lock MetaMask and close your browser
3. wait 4-5 minutes
4. Open your browser and log back in to MetaMask
5. Open the transaction in the transaction list
6. It will say "transaction confirmed at 8:00" (or whatever time you opened MetaMask

If you view the transaction on etherscan, you will see that it was actually confirmed at an earlier time

![Screenshot from 2021-10-18 08-01-24](https://user-images.githubusercontent.com/7499938/137715059-d44bcb3b-9f9b-4595-86ae-76162a0b8364.png)

**Comment by igorms-cons** [comment]
More information will be detailled in the next PR but I can say:
Timestamp transaction on etherscan is **only** on the moment the transaction is mined. There (I couldnt find) is no time when all transactions are done.
