### ISSUE TITLE
Be signed out per domain until signing in

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#714]
*Updated March 21, 2018, to reflect latest plans for this feature's implementation:*

MetaMask currently shows the selected account to each site that is visited. This is not an acceptable privacy feature, and user adoption has escalated the urgency of addressing this issue.

It has also been also criticized that the `web3` API is visible at all, even to sites a user did not explicitly show it to, since this also provides some identifying information.

## Goals/Constraints

- A user's accounts should never be shown to a site without the user's deliberate consent.
- `web3` should not be exposed to sites by default.
- Dapps should have a method of requesting a user's account & the web3 API.
- Old Dapps should continue to work.

## Proposal: A PostMessage Based Log-In

A difficult challenge of the constraints above is simultaneously *not* providing the `web3` API while also allowing sites to request a user to sign in. At first I thought this was impossible, but @kumavis, being the browser hacker he is, pointed out that as a WebExtension, we are able to listen to pages that use the [postMessage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), and so sites can send us a request without knowing whether we are listening or not.

This flow would look something like this, from an internal `mural.ly` board:

![screen shot 2018-03-21 at 2 56 25 pm](https://user-images.githubusercontent.com/542863/37739669-2191c828-2d18-11e8-9ba1-6b0d23a1eaef.png)

A design for this stage can be seen in #3383:

![deliberate log in flow](https://user-images.githubusercontent.com/597770/37371849-07c77c62-26ce-11e8-9be9-cf6f79edb7f3.png)

## What Still Needs Defining: Message Format

We need to define the exact format of the message sent via `postMessage`.  To keep this format compatible with other web3 browsers, we could not require the `targetOrigin` property of that API, which restricts possible recipients.

### Constraints of the Message Format

- Cannot use the `targetOrigin` API, to allow other web3 browsers to receive this event. (We're friendly!)
- Should be unique enough to not accidentally interfere with other listeners (ideas?)
- Should be extensible, to eventually include parameterized requirements of the Dapp (Need a certain network? Need a number of accounts? Need an account with a certain token? Maybe this becomes a way to add [DID](https://w3c-ccg.github.io/did-spec/) compliant personal information requests!) Related: #2532, #3663 and #3604

## What Still Needs Defining: Design, Scope of Rollout

In issue #3383 you can see initial designs, and how we're exploring what the UX of this type of log-in might look like. There are a variety of open questions there, asking whether we should rush out the privacy component (not showing web3 or accounts) if it means we remove the ability to be signed in to multiple sites at once.

There are also several other UX/design concerns on that issue, and we can keep the design aspect of this feature mostly confined to #3383, and keep this issue for the specification of the API for Dapp developers.

**Comment by flyswatter** [comment]
To clarify to those without context:  This would mean not injecting any user accounts into the in-page web3 accounts array.

**Comment by flyswatter** [comment]
When opening the metamask popup to look at accounts, I would imagine we just show the accounts/balances for *the currently open tab*.

**Comment by lukehedger** [comment]
@flyswatter Wondering what the status of this proposal is? I arrived here out of a desire to be able to switch MetaMask Web3 injection on/off easily - current practice is to enable/disable the Chrome extension manually. The per-domain aspect sounds good but is this just concerning the injection of accounts or the entire Web3/RPC API itself?

**Comment by danfinlay** [comment]
This issue is getting some public attention, and I think decent points have been made that especially given our spike in usage, we need to raise priority on this to protect our users.

https://twitter.com/backus/status/954921568198574080

https://twitter.com/nicksdjohnson/status/954999819344535553

**Comment by petejkim** [comment]
Somewhat relevant - I think it's a good idea for DApps to stop making the assumption that the web3 object is available immediately.

<img width="894" alt="screen shot 2018-03-22 at 2 56 51 pm" src="https://user-images.githubusercontent.com/30173/37800823-639d6b18-2de1-11e8-9496-b38e53120078.png">
<img width="895" alt="screen shot 2018-03-22 at 2 56 59 pm" src="https://user-images.githubusercontent.com/30173/37800827-65268f3c-2de1-11e8-9473-3004981a711f.png">

**Comment by danfinlay** [comment]
I agree, @petejkim, and while I didn't go into it here, the UX for a Dapp is a little strange here, and I expected some Dapp dev to complain, actually!

When you don't see web3, and you've fired your `window.postMessage({ web3: 'sign-in' })` request, what do you show on the screen?

> It looks like you don't have a web3 browser. Please connect using one, or sign in with it.

Okay, maybe that's not so bad, but it's still a pretty different concept. Maybe you can just act like they don't have one, since the "showing web3" portion should be handled by the browser catching the sign-in request message.

**Comment by laurengarcia** [comment]
Unsolicited 2 cents from a Metamask fan and privacy dev: If the message format got too elaborate it could be used to fingerprint users, esp when paired with other info gathered from browser env. The more generic the better (for privacy) IMO.

Thanks and cheers!

**Comment by danfinlay** [comment]
@laurengarcia Do you think this is still an issue of the message format is totally ignored without user consent? Part of the reason for the use of `postMessage` is to eliminate nonconsensual metamask related fingerprinting. Am I missing something?

**Comment by laurengarcia** [comment]
@danfinlay Sorry, no you're not missing anything, your assumption for that use-case sounds correct.

My comment is perhaps too granular for this higher level feature and directed at the "user does consent" use-case actually, in response to the third bullet point in the description above under "Constraints of Message Format":

_"Should be extensible, to eventually include parameterized requirements of the Dapp (Need a certain network? Need a number of accounts? Need an account with a certain token? Maybe this becomes a way to add DID compliant personal information requests!)"_

Now that I looked into it more, my comment is probably better suited to https://github.com/MetaMask/metamask-extension/issues/2532, the RFC where you discuss "Selective Disclosure" of personal info.

So I am imagining flow is: user visits dApp, and dApp sends `postMessage` requesting a bunch of information, only *some* of which I am willing to share in order to use minimum feature set of dApp. Am imagining that instead of a binary `share account info / don't share account info` button there are some base settings associated with my account which excludes identifying information i dont want to share by default. If those settings get too granular and as a user I have my defaults set and re-use them across dApps, that information could be used to fingerprint me anyway and roll up my activity across dApps. Similar to how cookie data and traditional advertising work on the open web right now.

That was my only point. Probably better suited to https://github.com/MetaMask/metamask-extension/issues/2532 discussion!

**Comment by danfinlay** [comment]
Cool, that's an interesting set of concerns that I look forward to dealing with when we get there ;D

**Comment by ricburton** [comment]
I think you need to write a Medium post about this. This is a surprise to the dapp developers I know.

**Comment by danfinlay** [comment]
> I think you need to write a Medium post about this. This is a surprise to the dapp developers I know.

Oh I know, but we need to finalize exactly the protocol we're proposing. We'll try to launch an article a week or two before pushing it live.

**Comment by danfinlay** [comment]
By all means, sketch up how you think it might work.

I think we also agreed at the WalletConf that it could make sense to ease-in to this breaking change, by allowing end-users (who understand the new expectation of deliberately signing in) to first "enable" full-web3-stealth-mode.

Once we have that live, and enable the "request login" API, hopefully Dapp devs will see the new API as beneficial to migrate to, before we perform a hard break.

**Comment by ricburton** [comment]
Here is a draft of the post: https://medium.com/@ricburton/logging-in-with-metamask-b47857efb4f7

**Comment by danfinlay** [comment]
That post looks great, @ricburton! I'd be willing to put it under the MetaMask publication if you wanted our reach, we need to get the word out wide.

**Comment by ricburton** [comment]
Will publish now. I think you need to invite me to contribute to metamask’s medium

Cheers,

Richard

**Comment by danfinlay** [comment]
Added as a writer.

**Comment by danfinlay** [comment]
@roschler This is an interesting idea, but seems outside the scope of this issue. It seems somewhat related to #4260, but with different goals. I don't think a local server would be needed, the extension already has a process with communication methods to each page. I'm also unclear what kind of snooping you're trying to avoid. Feel free to open this proposal in a new issue, and clearly describe the attack vectors you are trying to mitigate.

**Comment by lazaridiscom** [comment]
Seems #4703 has fixed this, should be closable.

**Comment by whymarrh** [comment]
With our connect screen implemented I believe it's safe to consider this closed (as noted in #3930)

**Comment by seashell37900** [comment]
> @laurengarcia Do you think this is still an issue of the message format is totally ignored without user consent? Part of the reason for the use of `postMessage` is to eliminate nonconsensual metamask related fingerprinting. Am I missing something?

MMMK
