### ISSUE TITLE
regression: RPC error message not rendered

### ISSUE THREAD

**Issue by d10r** [MetaMask/metamask-extension#7142]
![image](https://user-images.githubusercontent.com/5479136/64604318-394d6380-d3c2-11e9-8e52-2e43fa33810f.png)

At the end of that error message, you can see the string [object Object].  
In this case, the gasPrice was set below what the RPC node accepts. Until recently, Metamask correctly printed out the error message for that.

I don't know if this bug affects only this specific error case (gas price too low) or others too.

Observed in Metamask 7.1.1 in Chrome.

**Comment by eclairss17** [comment]
I am new to Ethereum but I had a similar error while validating my transaction of my smart contract so the fix I could come up with was using a different localhost port no, I don't know if this helps or not, also my contract had a check of 150 sec so it confirmed the first transaction after getting deployed after 150 sec. gas price was not the issue

**Comment by ceyonur** [comment]
Any progress on this? I'm still having this issue with both brave & firefox extensions.(brave metamask 8.0.8). It both prints to console & interface this "ambigous" message with [object Object] string in the message.

**Comment by Gudahtt** [comment]
Related to #8975
