### ISSUE TITLE
Is there a way to tell if the user is using a Hardware Wallet?

### ISSUE THREAD

**Issue by BrendanChou** [MetaMask/metamask-extension#7159]
Similar to telling if the provider `isMetamask`?

**Comment by spalladino** [comment]
+1 here! Given that hardware wallets do not support several sign methods, it helps knowing in advance whether we can send an `eth_signTypedData` or need to fall back to an `eth_sign`.

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/6994
