### ISSUE TITLE
Unable to handle "user denied" errors

### ISSUE THREAD

**Issue by PierreJeanjacquot** [MetaMask/metamask-extension#7160]
**Describe the bug**
As dapp developper, I want to know when the user reject the signature (tx or message). With MetaMask v7.1.1 all denied signature produce an error with message "Internal JSON-RPC error." 

**To Reproduce**

0. Have MetaMask 7.1.1 installed on your browser
1. Go to [https://codesandbox.io/s/agitated-hypatia-6vxq9](https://codesandbox.io/s/agitated-hypatia-6vxq9)
2. Grant acces to MetaMask
3. Open the console panel
4. Clic on SIGN TX button and deny the signature
5. See the error logged in console => error message is `"Internal JSON-RPC error."` which is not really helpful. Notice the stack property contains `"Error: MetaMask Tx Signature: User denied transaction signature."` that's interesting but the stack property may not be the best place to put this information. 

**Expected behavior**
The error message should be `"User denied transaction signature."`

Same problem when user deny `personal_sign` or `eth_signTypedData_v3`

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox, Chrome
 - MetaMask Version 7.1.1

**Comment by nick** [comment]
Have found this to be an issue in newer MetaMask releases too. We used to be able to show a more relevant error message but seems this is no longer possible.

**Comment by PierreJeanjacquot** [comment]
Error message are fixed with MetaMask v7.3.1
- Cancel on Tx: `MetaMask Tx Signature: User denied transaction signature.`
- Cancel on sign message: `MetaMask Message Signature: User denied message signature.`

Good job @Gudahtt :+1:
