### ISSUE TITLE
Avoid Google auto translate on seed phrase if enabled in the browser

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-extension#7164]
**Describe the bug**
If Google auto translations is enabled in the browser the seed phrase gets auto translated too, according to a report from user in the case number: 24092

**To Reproduce**
1. Have Google auto translate enabled in the browser
2. Create new MetaMask wallet and check if seed phrase text box gets auto translated from English.

**Expected behavior**
Text box showing the 12 words seed phrase in English shouldn’t ever be translated. 

**Additional context**
Warn the user that seed phrase cannot be translated, maybe with a warning text in image format, so the warning never gets translated to local languages.

**Comment by Gudahtt** [comment]
It looks like this might be pretty easy to prevent by adding a `notranslate` class (https://cloud.google.com/translate/faq#technical_questions)
