### ISSUE TITLE
Set up Continuous Delivery System

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#718]
This thread will be for exploring strategies for continuous deployment of MetaMask.

Attributes I'd like a solution to have:
- As secure as possible
- Requires test passing
- Requires code review (maybe multiple users, maybe weighted by their previous contribution value)
- Maybe authenticated via the blockchain itself. (Boardroom? Backfeed?)

Right now Chrome's most secure extension deployment strategy involves an authorized private key, which raises the question of where this private key is, that it could enforce all of our other rules?

Maybe this would be a good job for [Microsoft Cryptlets](https://azure.microsoft.com/en-us/blog/bletchley-blockchain/)?

I also have heard good things about [GitLab's Continuous Deployment features](https://about.gitlab.com/2016/08/05/continuous-integration-delivery-and-deployment-with-gitlab/), with Parity adopting them for their multi-platform builds.

**Comment by flyswatter** [comment]
Kinda related to #933

**Comment by flyswatter** [comment]
The Firefox addon store has a great looking addon deploy API: https://addons-server.readthedocs.io/en/latest/topics/api/overview.html

**Comment by lazaridiscom** [comment]
@danfinlay , this is the oldest P2.

It looks preferable to close this and to follow-up with multiple "automate deployment" issues, one issue per target-browser.

**Comment by danfinlay** [comment]
Agreed, and we've been chipping at those in other issues anyways, so this issue, as an "epic", is going basically unused.
