### ISSUE TITLE
Add timestamp variable to Matomo

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#7183]
Matomo can help us understand user retention. This feature requires an optional variable to be set: `_idts`, the timestamp of the user's first known visit (https://developer.matomo.org/api-reference/tracking-api#optional-user-info). Because we aren't reporting this variable, Matomo thinks that all users are new users. We'll need to add that parameter in order to track user retention.

**Comment by Gudahtt** [comment]
See here for more info: https://matomo.org/docs/cohorts/#tracking-setup

**Comment by Gudahtt** [comment]
Note that we should probably obscure this timestamp whenever `excludeMetaMetricsId` is set

**Comment by Gudahtt** [comment]
We've switched to using Segment for metrics, so this is now obsolete.
