### ISSUE TITLE
Add "Retry" option for failed transactions

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#7193]
**What problem are you trying to solve?**
Sometimes a user might want or need to retry a failed transaction.  For example, if a speed up, or cancel attempt fails with gas too low, then the original transaction will continue to hold up future transactions for a long time.  Also if the transaction fails due to a network connection issue.

**Describe the solution you'd like**
On a failed transaction, in the activity area of MetaMask, allow the user to select "Retry".  This would open a screen with editable gas options, same to address, and same nonce.

**Additional context**
![image](https://user-images.githubusercontent.com/16330048/65249175-1ce3b200-dab9-11e9-8cf9-cb60c0967446.png)

**Comment by danjm** [comment]
ping @rickycodes

**Comment by brad-decker** [comment]
@dpazdan we can now retry transactions from the details view -- not sure if that was the case at the time this issue was created. @rickycodes / @danjm do we need this to be in the failed transaction list item to be solved?

**Comment by Gudahtt** [comment]
I think we can close this; it was fixed in #7296
