### ISSUE TITLE
cannot sign order on forkdelta using ledger nano s hardware wallet

### ISSUE THREAD

**Issue by jpritikin** [MetaMask/metamask-extension#7215]
**Describe the bug**
I succeeded in depositing tokens into ForkDelta. When I try to place an order, I am prompted to sign as usual. After approving the signature, I always get, "Order signing failed. Make sure you have an account selected from the Accounts dropdown in the upper right." For more detail, see https://www.reddit.com/r/ForkDelta/comments/d7vhwc/cant_place_an_order/

**To Reproduce**
1. Go to forkdelta.app
2. Try to place a limit order

**Expected behavior**
I expect the limit order to be accepted by forkdelta

**Screenshots**
Here is a video, https://peertube.live/videos/watch/cdd2ca43-bbd5-4eff-a00b-df6c47b149f8

**Browser details (please complete the following information):**
 - OS: Ubuntu Disco
 - Browser: Firefox 69 or Brave 0.68.140
 - MetaMask Version: 7.1.1,  7.2.1

**Additional context**
It is not clear to me who to blame. Is this a metamask bug or ledger bug or forkdelta bug?

**Comment by bdresser** [comment]
@jpritikin have you tried going to the settings on your Ledger device and set "Contract Data" to "Yes". You should also make sure your firmware is up-to-date. 

It's also possible that ForkDelta is using a signing method that Ledger does support. 

Closing for now, happy to re-open if we can confirm this is a MM bug

**Comment by OsoianMarcel** [comment]
I feel that my feature https://github.com/MetaMask/metamask-extension/issues/7277 is related to this issue.

**Comment by AndreMiras** [comment]
I could reproduce on metamask, Brave and ledger nano S (latest 1.6 firmware). It feels like this is happening with secondary ledger account. Could it possibly be?

**Comment by GioF-star** [comment]
I have exactly the same, can make deposits and withdrawals only when doing a buy/sell order I get the following error: 

Order signing failed. Make sure you have an account selected from the Accounts dropdown in the upper right.

I have selected the right account on the upper right. But it's my 5th wallet on my ledger account and I suspect the problem lies there
