### ISSUE TITLE
Implementing basic MetaMask provider communicating with iframe

### ISSUE THREAD

**Issue by DaniellMesquita** [MetaMask/metamask-extension#7217]
I'm developing a browser which is early based on sandboxed iframe. I know there is webview and browserwindow, but this is a experiment implementation of which level a iframe-based browser can achieve till I implement a better approach.

![image](https://user-images.githubusercontent.com/6765277/65608149-228f3b00-df84-11e9-830e-19e7d7785b83.png)

iframes and the main page can exchange messages. When a DApp inside iframe tries to communicate with MetaMask extension, the main page get it as message from iframe and repasses it to a basic MetaMask implementation. This basic implementation would have only these basic functions: ethereum.enable(), sign message, ethereum.send(options).
I ask, how can the main page get MetaMask API's messages from iframe and translates to a web3 provider very-basic UI?

https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider
https://metamask.github.io/metamask-docs/API_Reference/Signing_Data/Eth_Sign

**Comment by DaniellMesquita** [comment]
@danfinlay

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/MetaMask/metamask-extension/issues/6597

**Comment by DaniellMesquita** [comment]
I'm not asking any MetaMask developer to do it for me.
What I ask is the implementation of a very basic web3 provider implementation which would communicate with a main page wrapper which translates requests from a DApp inside iframe.
This is to make IC a basic web3 browser, using both Cordova/Muon.

**Comment by lazaridiscom** [comment]
@DaniellMesquita, this kind of requests do not belong on an issue-tracker.

I  suggest:

- You close this issue.
- You place your questions on https://stackoverflow.com/questions/tagged/metamask
