### ISSUE TITLE
Make account resets less painful for devs...

### ISSUE THREAD

**Issue by jklepatch** [MetaMask/metamask-extension#7219]
**What problem are you trying to solve?**
When you develop Dapps, you frequently have to restart Ganache. This requires to frequently do many clicks to reset accounts in Metamask.

**Describe the solution you'd like**
We could have either:
* A shortcut to do it. This shortcut would only work when not on public testnets or mainnet
* An automated solution that does the reset automatically, also only if not on public testnets or mainnet. This is nicer but more complex to implement. See this suggestion from Metamask: https://twitter.com/metamask_io/status/1006760090014105600?lang=en

**Comment by bdresser** [comment]
closing as a dupe of https://github.com/MetaMask/metamask-extension/issues/5067, added your comments there
