### ISSUE TITLE
ERC20 Token Migration to ERC223

### ISSUE THREAD

**Issue by jsim77** [MetaMask/metamask-extension#7220]
I think it would be nice if those ERC20 Token which stored in MetaMask can have the possibility to migrate to ERC223.

What do you think? Something like dapp or inter-connected with MetaMask Wallet will do.

**Comment by Gudahtt** [comment]
Thanks for the suggestion!

Perhaps I'm misunderstanding what you're asking, but I don't think this is something MetaMask would do. We don't actually "store" any contracts in MetaMask, we only store their addresses. Migrating a contract from ERC20 to ERC223 would require contract changes and redeployment, which pretty far outside of MetaMask's wheelhouse.

I'll close this for now, but please let me know if I've misunderstood this.
