### ISSUE TITLE
Clarification on how to capture the "speed up" transaction txhash

### ISSUE THREAD

**Issue by prographo** [MetaMask/metamask-extension#7227]
There is a feature in MM that allows the user to supersede a slow transaction with another transaction with a higher gas price. The same nonce is used, therefore nodes drop the original transaction in favour of the transaction with a higher gas price.

This works well. However...

When the user submits a transaction, I am capturing the txhash using the callback -- this works perfectly -- but what about the situation where the user later does a "speed up" on the transaction -- the javascript callback is not called again with the second txhash.

How shall I capture this event?

It's not enough to know the new txhash, I need to know the predecessor it relates to, isn't it?

Is there a way to do it?

**Comment by gorgos** [comment]
See also the related Web3 issue: https://github.com/ethereum/web3.js/issues/3585.

**Comment by GregTheGreek** [comment]
I've created [EIP-2831](https://github.com/ethereum/EIPs/pull/2831/) in attempt to address this (still making edits)

**Comment by Gudahtt** [comment]
Great question @prographo, thanks for bringing this up! We're going to try using EIP-2831 for this, which is being tracked in #9174. Please follow that discussion for further updates.
