### ISSUE TITLE
Custom network with HTTP Basic Auth didn't work

### ISSUE THREAD

**Issue by zulhfreelancer** [MetaMask/metamask-extension#7236]
![metamask](https://user-images.githubusercontent.com/3416976/65942911-e6b31480-e460-11e9-82cc-3f143464f463.png)

My private chain node RPC URL is something like this:

```
"http://username:password@the.node.ip.address"
```

It's running on port 80 but with HTTP Basic Auth. When I try to add it to MetaMask, I got the screenshot above.

**Expected behavior**
Able to connect without any problem.

**Screenshots**
See above.

**Browser details (please complete the following information):**
 - OS: Mac OS 10.12.6
 - Browser: Firefox 69.0.1 (64-bit)
 - MetaMask: v7.2.2

I think this is a bug. If I'm wrong, please share to me the right way to connect to a node with HTTP Basic Auth like this. Thanks.

**Comment by j-mars** [comment]
Bump to this. Happening the same to me.

**Comment by tmashuang** [comment]
related to #9791, also fixed by headers.
