### ISSUE TITLE
Locking account after unlocking

### ISSUE THREAD

**Issue by mkg20001** [MetaMask/metamask-extension#7245]
**What problem are you trying to solve?**
Sometimes I want to lock my account after unlocking & using it, for example when allowing somebody else to access my computer

**Describe the solution you'd like**
A button in the 3-dot menu that says "lock" and simply locks the account and throws away the password/unlocked keymaterial from memory

**Additional context**
Ubuntu 19.04 amd64 firefox

**Comment by Gudahtt** [comment]
We already have a "Log out" button in the account menu that does this. Does that solve your problem?

![logout_circled](https://user-images.githubusercontent.com/2459287/66436903-bb9b6880-e9fe-11e9-8ea9-1d526f821b14.png)

**Comment by mkg20001** [comment]
Judging by the fact that I didn't find it at all (because I never clicked that icon, as I assumed it would just allow switching accounts), it doesn't seem too obvious

**Comment by Gudahtt** [comment]
Thanks for the feedback! We will take that into consideration with future designs. It is understandable that you wouldn't expect that button to be there.

Here is some related ongoing work: #7852 , #5967, https://github.com/MetaMask/Design/issues/163

I'll close this issue for now, as the stated feature does exist, but please feel free to make further suggestions on how it could be improved.
