### ISSUE TITLE
Do not allow browser's translator to translate seed phrase

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#7246]
**Describe the bug**
A user is presented with the phrase in English and uses the browser's built-in translator tool.  If they try to restore this seed phrase, it will not work, and sometimes the translation back to English is not identical to the original.

**To Reproduce**
1. Install MM
2. Make sure chrome language settings are set to non-English
3. In full screen mode, create a wallet / new seed phrase
4. Select the google tranlator option at the top of the page

**Expected behavior**
The seed phrase should not be allowed to change.  Or at minimal, we should have large text stating **DO NOT MODIFY OR TRANSLATE THIS PHRASE**

Reference case #s: 
25150
25356

**Comment by dpazdan** [comment]
Further more,  we now allow "remind  me later" for the seed phrase.  So if the person translates on that page, and takes a screenshot or rights down the translation, this can cause a false sense of backup/security.

**Comment by dpazdan** [comment]
<iframe src="https://player.vimeo.com/video/364154157" width="640" height="362" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
<p><a href="https://vimeo.com/364154157">seed_translate</a> from <a href="https://vimeo.com/user102131671">Dave Pazdan</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

**Comment by whymarrh** [comment]
I think this might be similar to #7164
