### ISSUE TITLE
Events are not firing callback

### ISSUE THREAD

**Issue by nkuba** [MetaMask/metamask-extension#7270]
**Describe the bug**

Events are not firing callback since MetaMask version 7.1.1. It works fine in version 7.1.0.

**To Reproduce**
Execute script listening for an event emitted from a contract. Sample script:
```js
const provider = window.ethereum || window.web3.currentProvider

const abi = (....)
const address = (....)

const web3 = new Web3(provider)
const sampleContract = new web3.eth.Contract(abi, address)

sampleContract.events.PublishedValue()
	.once('data', function(event) {
  	console.log('Received event:', event)
})
```

**Expected behavior**
Get the emitted event.

**Browser details (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - MetaMask Version: 7.1.1

**Comment by Gudahtt** [comment]
Thanks for the report! Are you still experiencing this problem with the latest version of MetaMask?

**Comment by vandan** [comment]
Closing. Please reopen if there is a recent report with reproduction steps.
