### ISSUE TITLE
The correct address parameter

### ISSUE THREAD

**Issue by Steven-Dai** [MetaMask/metamask-extension#7276]
Premise：In chrome,  use metamask call  the method of my smart contract.

My contract info : https://ropsten.etherscan.io/tx/0x611aa86eb6e615f48919a5e27f829331e1f897a9f14cad788cc2ceeb13711443

![error](https://user-images.githubusercontent.com/11538695/66666785-024dc480-ec84-11e9-8ec4-4c643bd0a2ae.png)

I called four of the contract's methods，The first three were all successful.The last method needs to receive an address param. method code:
`function balance(address addr) public view returns(uint) {
        return addr.balance;
 }`
 An error occurred when I called it, the address is `web3.eth.accounts[0]`,but return `{"code":-32602,"message":"invalid argument 1: hex number > 64 bits"}`,so what is the correct parameter? Thank you!

**Comment by Steven-Dai** [comment]
sorry, My contract info link is error. The contract code is here.
```
pragma solidity ^0.4.0;
contract HelloWorld{
    
    function helloWorld() public pure returns(string){
        return "Hello World";
    }
    
    function balance() public  view returns(uint256) {
        return msg.sender.balance;
    }
    
    function balance(address addr) public view returns(uint) {
        return addr.balance;
    }
    
    function param(string a) public pure returns(string){
        return a;
    }
}
```

**Comment by ZimZim9** [comment]
> Premise：In chrome, use metamask call the method of my smart contract.
> 
> My contract info : https://ropsten.etherscan.io/tx/0x611aa86eb6e615f48919a5e27f829331e1f897a9f14cad788cc2ceeb13711443
> 
> ![error](https://user-images.githubusercontent.com/11538695/66666785-024dc480-ec84-11e9-8ec4-4c643bd0a2ae.png)
> 
> I called four of the contract's methods，The first three were all successful.The last method needs to receive an address param. method code:
> `function balance(address addr) public view returns(uint) { return addr.balance; }`
> An error occurred when I called it, the address is `web3.eth.accounts[0]`,but return `{"code":-32602,"message":"invalid argument 1: hex number > 64 bits"}`,so what is the correct parameter? Thank you!

https://metamask.app.link/send/0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359@1/transfer?address=0xD4D14e59F6a681dFe5a2E89e04ed7CcB1BBBd6c5&uint256=5.5e1

**Comment by whymarrh** [comment]
@Steven-Dai would you mind restating the question? What issue are you running into? Can you reproduce this on Remix/share a link to a live example?

**Comment by Steven-Dai** [comment]
Now it's settled. It's all right. I tried my best to recall what happened at that time, but I couldn't remember. It was my mistake in operation.
