### ISSUE TITLE
Feat: Detect metamask account type (internal, ledger, trezor)

### ISSUE THREAD

**Issue by OsoianMarcel** [MetaMask/metamask-extension#7277]
**What problem are you trying to solve?**
In our DAPP, we use 3 different signatures: metamask, private key and ledger.
Used signature function: _web3.eth.sign_
And unfortunately, the signature in Metamask is different.
When we detect a user on metamask, we sign the hash with prefix (\x19Ethereum Signed Message:\n), but with another account types (priv. key or ledger) we sign the signature without prefix. This is because if we sign the hash with metamask in same way (without prefix) as in another account types, the metamask signature is different (in our case it's a wrong signature).
Currently we have users which use metamask with connected ledger wallets, and as I said above, the signature from ledger and metamask must be signed in a different way (without prefix, with prefix). So, the problem is that we can not detect which account is a metamask internal account or a metamask+ledger account (connected ledger account inside metamask), in order to select right signature method:
- metamask: with prefix
- metamask+ledger: without prefix

**Describe the solution you'd like**
Would be great to create a way to detect which account type is selected: an internal metamask account or an ledger account connected in metamask.
As I know, at the moment Metamask has 3 account types:
- Internal
- Ledger
- Trezor

**Comment by bschorchit** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/6994
