### ISSUE TITLE
Connecting a custodial wallet (TrustVault) to MetaMask

### ISSUE THREAD

**Issue by fodder1997** [MetaMask/metamask-extension#7278]
**What problem are you trying to solve?**

TrustVault is a custodial wallet from Trustology (trustology.io). The wallet consists of an iOS App that is used to sign requests. We would like to integrate with MetaMask. We believe that adding support for Custodial wallets in MetaMask would be a great addition. We have prototyped a connection to TrustVault that works but we have a few suggestions for features.

Currently the connect tab only caters for hardware wallets. The connect tab should be more generic to cater to other wallet types.

**Describe the solution you'd like**

Option 1
---
Make the "Connect" tab more generic, drop the "hardware" text and add TrustVault as one of the options together with Ledger and Trezor.

1. We propose to make it more generic by only using the word "wallet" instead of "hardware wallet". If a differentiation between the wallets is required, we recommend to use "custodial" and "non-custodial" wallet.

1. Remove the "learn more" section in the connect screen as it only describes how to add a hardware wallet. Support texts are moved to the wallet specific screens. I.e. a user has to click on "TrustVault" & connect. From the next screen he can click on the FAQ's. This should be the same for the hardware wallets. The benefit of this solution is that each wallet can maintain their own customer supporting texts.

![](https://gitlab.com/Trustology/general/metamask-extension/uploads/624f636f4a2891e0337ebb9a0c6ca84b/Connect_Option_1.png)

Option 2
---

Add sub-tabs to differentiate non-custodial (i.e. hardware wallets) and custodial wallets (i.e. TrustVault)

![](https://gitlab.com/Trustology/general/metamask-extension/uploads/9713c843694e2d404ff67df20e4902a8/Connect_Option_2.png)

**Additional context**

**Comment by danfinlay** [comment]
@MetaMask/design  can we get a sign off for this?

**Comment by cjeria** [comment]
Option 1 looks like a better approach IMO. The only thing missing from what I can tell is a back button when drilling into the trustology screen.  We'd also need to slightly change the behavior of that option since right now, selecting a hardware option makes the connect button active. cc @rachelcope thoughts?

Back button 
![image](https://user-images.githubusercontent.com/597770/69291564-7dc26000-0bb8-11ea-922b-fc140e4665b9.png)

Placement of the back button.
![image](https://user-images.githubusercontent.com/597770/69291454-24f2c780-0bb8-11ea-8959-24d06dd34f20.png)

**Comment by danfinlay** [comment]
@fodder1997 we'd heard there was a UI branch implementing this feature, could you please link to it so we can QA it?

**Comment by fodder1997** [comment]
We have a working prototype in our private repo. It's the full integration with TrustVault (not just UI stuff) so we'll put it together as a PR and get it to you in a day or two.

**Comment by fodder1997** [comment]
> We have a working prototype in our private repo. It's the full integration with TrustVault (not just UI stuff) so we'll put it together as a PR and get it to you in a day or two.

Slight delay on getting this out due to some sicknesses in the dev team and merging with current develop branch. We should have something ready in the few days. Thanks

**Comment by necati92** [comment]
Hi @danfinlay , its Necati from Trustology team,  we have created a branch locally for the issue but I am having authorisation issue trying to push the branch to you repository, It seems like I do not have the correct access rights to do so

**Comment by cjeria** [comment]
Hi @necati92 Please submit a pull request to the [develop](https://github.com/MetaMask/metamask-extension/tree/develop) branch and provide post the link here for us to review your work. Thanks!

**Comment by fodder1997** [comment]
Hi - we've submitted our PR. Apologies for the delay. ( https://github.com/MetaMask/metamask-extension/pull/7712)

**Comment by dpazdan** [comment]
Closing this issue as it is now a PR
