### ISSUE TITLE
Allow a custom message to be presented to a use when waiting for a transaction signature

### ISSUE THREAD

**Issue by fodder1997** [MetaMask/metamask-extension#7280]
**What problem are you trying to solve?**

As a user I would like more information presented to me when signing a transaction from an external account.

**Describe the solution you'd like**

Currently, only a spinner is presented, it would be useful if a message is displayed along with the spinner to direct the user what to do next in the external wallet.

![](https://gitlab.com/Trustology/general/metamask-extension/uploads/5d18f768894783b27f7310b641ae4433/Spinner_with_message__1_.png)

**Additional context**

TrustVault is a custodial wallet from Trustology (trustology.io). The wallet consists of an iOS App that is used to sign requests. We would like to integrate with MetaMask. We believe that adding support for Custodial wallets in MetaMask would be a great addition. We have prototyped a connection to TrustVault that works but we have a few suggestions for features.

**Comment by bdresser** [comment]
relates to https://github.com/MetaMask/metamask-extension/issues/5757

**Comment by Gudahtt** [comment]
Thanks for the report! We're going to use #5757 to track further progress on this issue. Please follow that issue for further updates.
