### ISSUE TITLE
Qualifications for use on Chromium Android

### ISSUE THREAD

**Issue by filmblackeye** [MetaMask/metamask-extension#7290]
FOR USER QUESTIONS, PLEASE DO NOT OPEN A GITHUB ISSUE - IT WILL NOT BE HANDLED HERE.

INSTEAD, PLEASE EMAIL SUPPORT@METAMASK.IO WITH A DESCRIPTION OF YOUR PROBLEM.

**Comment by jennypollack** [comment]
Hey @filmblackeye please feel free to reopen with more information.
