### ISSUE TITLE
Support all ens names.

### ISSUE THREAD

**Issue by Amxx** [MetaMask/metamask-extension#7291]
I wanted to send a transaction to one of my wallet using it's ENS name and realized resolution did not work.

**How to reproduce:**

- Click the "send" button
- Search for the ENS name `hadriencroubois.argent.xyz`
  - The resolution fails (should point to `0x25229Cfe0Bd20e97aAFCFaf82c57Bb681c21DB90`)

Address under the `.eth` are resolved correctly, it there a requierement on the ENS address ending in `.eth`? If so, this should be removed to add support for all the other TLDs already (or soon to be) supported by ENS

**Comment by Amxx** [comment]
In `ui/app/helpers/utils/util.js`, there is a `isValidENSAddress` method that only accepts address ending in "eth", "test" of "xyz". This shouldn't cause my issue, but it's still wrong as more TLDs exist.

**Comment by Amxx** [comment]
the `isValidENSAddress` doesn't support subdomains :/

**Comment by danfinlay** [comment]
This has been fixed, I verified it on `develop`, so if you don't have the fix, you will soon.
