### ISSUE TITLE
Popup not visible

### ISSUE THREAD

**Issue by eloudsa** [MetaMask/metamask-extension#7292]
Hello

I noticed a problem with Metamask.

When I sign transactions, the popup is displayed few times and then it is not displayed. I have to click on the Metamask icon in the Chrome toolbar to display the transaction and signed it.

I'm using:
- macOS Catalina 10.15
- Chrome 77.0.3865.120
- Metamask 7.2.3

S.

**Comment by Gudahtt** [comment]
Duplicate of #7051

**Comment by Gudahtt** [comment]
Thanks for the report @eloudsa ! Please track #7051 for progress on this issue. I did find a way to reproduce this, and we may have a solution soon.
