### ISSUE TITLE
Add a "don't loggin" option from the login page

### ISSUE THREAD

**Issue by Amxx** [MetaMask/metamask-extension#7293]
I am building an app that needs a web3 provider. By default I'm looking for an injected one (metamask / opera / gnosis ...) but if this not available I try to create a provider using another mechanism (portis / torus / universal login / ...). Some people might have metamask installed but still want to connect through another provider. In that case they need to refuse the "enable" call to metamask for my app to fallback to something else.

The issue is that, in order to refuse the `enable()` call, I first need to unlock metamask, which requires me to type in my password. So if a friend wants to use my laptop with it's portis account, he needs me to unlock metamask and refuse the connection.

This is bad UX!

A "simple" solution would be to have the opportunity to refuse to log in which would cause any hidden `enable()` call to fail.

**Comment by tmashuang** [comment]
I don't believe this to be an issue, The login notification window can be closed by clicking the (X) in the corner of the window that all browsers have.
