### ISSUE TITLE
Support A/B testing at lower rollout percentages

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7294]
Current A/B testing controller only supports 50/50 odds of trying out a new feature.

Some experimental features we might want to test with less than 50% of our user-base.

For this reason, we should support controlling the roll-out of a given feature, possibly even from a server-hosted variable, allowing "live" rollouts of a feature!

**Comment by Gudahtt** [comment]
Closing this, as we've since removed the A/B functionality.
