### ISSUE TITLE
Refactor `new-account.js`

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#7302]
`metamask-extension/ui/app/pages/create-account/new-account.js` needs refactoring.

To bring it up to date with other patterns used in the majority of our components, we need to:
- move the `mapStateToProps` and `mapDispatchToProps` functions, and the call to `react-redux`'s `connect` to a `new-account.container.js` file, rename the component file as per pattern in directories such as `pages/confirm-approve/`
- replace the hyperscript calls with jsx
- move the calculation of `newAccountNumber` to the container
- put  above in a `new-account` directory as per pattern in directories such as `pages/confirm-approve/`

**Comment by rickycodes** [comment]
addressed in https://github.com/MetaMask/metamask-extension/pull/7312
