### ISSUE TITLE
Speeding up cancelled transactions resends the transaction you wanted to cancel

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#7305]
I sent 5 ETH to an address, then clicked cancel. Then I wanted to speed up the cancellation, but instead it resent the prior transaction. The transaction confirmed.
<img width="353" alt="Screen Shot 2019-10-22 at 9 43 16 PM" src="https://user-images.githubusercontent.com/799573/67358344-fa5c1300-f514-11e9-8f53-0e88be0d2c84.png">

See the dropped transactions for https://etherscan.io/tx/0x4d6f83ccde8dd4affedd9a97e06b808f5f7531406a734860c4e0a217c4667e6d

**Comment by Gudahtt** [comment]
Related to #9053 and #9927 (all bugs caused by grouping transactions by nonce).
