### ISSUE TITLE
Loading wheel after submitting Tx

### ISSUE THREAD

**Issue by spaceblankey** [MetaMask/metamask-extension#7315]
After submitting transaction It just hangs at the loading wheel. If i click off/close the window and click the extension again, the transaction does not appear. Using Brave browser, MM 7.3.1

[

**Comment by bdresser** [comment]
@spaceblankey can you give us some more detailed reproduction steps? What site or dapp are you using? What type of transaction is it?

**Comment by Gudahtt** [comment]
Closing, as this issue is rather old and we never received enough information to investigate.
