### ISSUE TITLE
Add metrics for provider

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-extension#7329]
As we publish a new version of our provider, we need a rough understanding of which API features are being used, by which websites. This includes:

```
ethereum.send
ethereum.sendAsync
eth_signTypedData
ethereum.enable
ethereum._metamask.isApproved
ethereum._metamask.isUnlocked
ethereum.selectedAddress
ethereum.networkVersion
ethereum.chainId
```

No deprecation will happen without generous warning!

**Comment by bdresser** [comment]
@rekmarks is this still in play, given that we've already decided on our deprecation plans?

**Comment by rekmarks** [comment]
cc: @jacobcantele @Gudahtt
