### ISSUE TITLE
In certain instances translation text breaks dropdown items

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/metamask-extension#7331]
account menu is a fixed width and will push text below the corresponding icon in certain translation scenarios.

1. Go to settings/general
2. Change the language selection to "Français"
3. Observe the below (what's in the screenshot)

account menu should have a min width (vs fixed) to accommodate longer texts in other languages

![image](https://user-images.githubusercontent.com/675259/67896291-70becd80-fb32-11e9-8c8a-9b99e7c77c22.png)

**Comment by hjlee9182** [comment]
You want to make one line ? (dynamic width?)

**Comment by Gudahtt** [comment]
This has been fixed in #7354
