### ISSUE TITLE
Deposits show as negative USD

### ISSUE THREAD

**Issue by icarroll** [MetaMask/metamask-extension#7338]
**Describe the bug**
The two deposits to my Ethereum wallet show the correct magnitude of USD value, but as a negative number. This causes the balance to show as $0.00 USD when the wallet actually holds ETH worth $7.37 USD. Wallet address is 0x74237162B0878fB48fef76250Bf74CE5E3DD144e

**Expected behavior**
The value of the deposits should be positive USD.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - MetaMask Version: 7.3.1

![image](https://user-images.githubusercontent.com/1376335/68041364-a1ffe080-fc8d-11e9-9ff8-8cd27707c98f.png)
![image](https://user-images.githubusercontent.com/1376335/68041395-b643dd80-fc8d-11e9-811a-a17c7b7ef974.png)

**Comment by bdresser** [comment]
may be handled as part of #7317

**Comment by tmashuang** [comment]
As of v8.1.9, the dash, confused with a negative value, has been removed from the received tx list item.
