### ISSUE TITLE
Password no longer valid after some recent update?

### ISSUE THREAD

**Issue by lf94** [MetaMask/metamask-extension#7339]
**Describe the bug**

Putting in my password does not unlock the wallet. Very simple.

**To Reproduce**
1. Login
2. "Invalid credentials" error

**Expected behavior**

Login.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Debian Stretch
 - Browser: Firefox 70
 - MetaMask Version 7.3.1

**Additional context**

I wrote my own "unlock" tool about 2 months ago, and that's what I was able to use to unlock my .json file to get my recovery seed with the password I expected to work (I have stored my recovery seed physically too, but wanted to see if this still worked). This means that MetaMask broke the login scheme sometime in the past 2 months.

**Comment by hjlee9182** [comment]
You make another account and login again

**Comment by lf94** [comment]
> You make another account and login again

No... that just makes for a terrible experience.

**Comment by danfinlay** [comment]
We have tests for ensuring vaults migrate from each version to the next, and you're the only person reporting this, so it's much more likely there was a local storage corruption. This is one reason why it's good to back up your seed phrase, and I'm glad you did!

To truly debug this I would need the vault data and password involved, and that's extremely sensitive data, so I will instead say you should not share that with anyone, this looks like a storage corruption, but if more people report this we may eventually ask someone who had a very low-value account to share it for research.

**Comment by lf94** [comment]
Actually I will try my tool with the lastest vault data. If it falls then
it's the format, otherwise it must be corruption as you say. Thank you for
the reply!

**Comment by lf94** [comment]
@danfinlay I have confirmed it is the vault data that has broken, and it is NOT corruption. Using the vault data generated by the most recent MetaMask, my tool is not able to decrypt it.

Specifically, my tool is failing on base64 decoding the IV value, which really narrows down the issue.

**Comment by lf94** [comment]
I've traced this (I've done this before to figure out what MetaMask was doing to encrypt the vault) to https://www.npmjs.com/package/eth-keyring-controller , which has been updated 15 days ago. MetaMask was last updated 13 days ago, so this change was definitely included whatever it was. I'm still tracking down what has changed.

**Comment by lf94** [comment]
Well I can't seem to find anything relevant to this that has changed recently. So either this package https://crates.io/crates/base64 with 7.5 **million** downloads is bad, or there is something being overlooked here.

**Comment by danfinlay** [comment]
Okay, I'll reopen until we find the source.

I will point out that 7.5 million all-time downloads may actually make it less used than us. Their latest version has around 2.4k downloads per day, while we have 1.3 million current active installs, and you're the only person reporting a problem. So statistically, I wouldn't rule crates out.

But I'm reopening, because it's unfair to rule us out either while there's an encoding issue active. If it's our dep, it's our problem.

**Comment by danfinlay** [comment]
Btw the final encryption (and I believe hex encoding) of the vaults is done by this module. Hasn't been updated in 3 years, but a dep may have?:
https://www.npmjs.com/package/browser-passworder

**Comment by lf94** [comment]
Yeah I know. That module is what I used to recreate the same logic in Rust with OpenSSL.

If you would like my tool I can send the source via email. It's 1 file and very easy to use, but is not meant for the public.

**Comment by danfinlay** [comment]
I also have a vault decoder here, I haven't updated it in a while though, so it may be checking the wrong key in the storage object: https://github.com/danfinlay/Vault-Decoder2

You could send it to me, I may not have time to work through a rust crate today, but it could help us debug later. dan.finlay *at]  consensys.net

**Comment by lf94** [comment]
Sounds good. Honestly I expect this to be some rare base64 encoding error that is probably not seen often, and we will probably never find the root cause of this. Considering it's the IV of all things, sounds really unlikely that the vault format has changed, and is something lower level. For what it's worth both the `salt` and `data` decode perfectly. So it's very very very weird.

All that to say, if anyone runs into this issue, they can contact me for my decoder which I know works with older vaults (within the past 8 months).

I can maybe correct the base64 encoding by hand in a hex editor...It could just be a padding problem.

**Comment by lf94** [comment]
Before sending I will conduct another test with a new wallet in a fresh Firefox profile to be sure I just wasn't extremely unlucky.

**Comment by lf94** [comment]
Tested. It works. So maybe bad base64 encoding. I will check another day. Safe to say though, I think we can close this and as I said: whoever can contact me. Thanks! :)
