### ISSUE TITLE
Can't access scrollbar

### ISSUE THREAD

**Issue by presence35** [MetaMask/metamask-extension#7341]
Because there's a "new address" div the outer scrollbar appears. I can't click to scroll the tokens (mousewheel works tho). If I click the outer scrollbar the tokens popup closes.

![image](https://user-images.githubusercontent.com/32020168/68068376-c5459100-fd5c-11e9-8d8a-11c751478f21.png)

**Comment by tmashuang** [comment]
Seems to have been fixed. If the issue has persisted, please open a new issue with the view, extension or full screen tab, and how to render the outer scrollbar.
