### ISSUE TITLE
Custom networks not persisting in network menu

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7344]
A local hackathon user @hermanjunge added a custom network to his MetaMask but it did not persist, so he would have to re-enter custom network info repeatedly.

**Comment by rickycodes** [comment]
might be related: https://github.com/MetaMask/metamask-extension/issues/6710

**Comment by Gudahtt** [comment]
I am no longer able to reproduce this. I suspect it was fixed by #7388, so I'll close this for now.
