### ISSUE TITLE
Transaction values exchanged even if transaction rejected, and double values exchanged if transaction confirmed

### ISSUE THREAD

**Issue by KadenZipfel** [MetaMask/metamask-extension#7352]
**Describe the bug**
I'm trying to perform a function that exchanges one token for another, but I'm getting a very strange bug. If I call the function in web3, I get the standard metamask popup asking whether to confirm or reject the transaction. Now what's happening is if I hit reject, the value exchange still happens, even though there is no transaction on metamask nor on my ganache cli, just the values are updated on metamask. Then if I confirm the transaction, the transaction goes through as normal, except that double the expected value is exchanged.

Occasionally I get `RPC Error: MetaMask Tx Signature: User denied transaction signature.` as expected, yet the value is still exchanged. I've tried restarting my ganache cli, resetting my accounts on metamask, and even reinstalling metamask, but still the same.

**To Reproduce**
1. Create smart contract with this function:
```
function deposit(uint amount) public {
    require(daitoken.transferFrom(msg.sender, address(this), amount), 'transferFrom failed');
    emit Transfer(msg.sender, address(this), amount);
    require(ldai.mint(msg.sender, amount), 'mint failed');
    emit Mint(msg.sender, amount);
    emit Deposit(msg.sender, amount);
  }
```

2. Call function from web3 like this:
```
const num = this.state.amount * (10**18);
    this.props.contract.methods.deposit(num.toString()).send({from: this.props.account});
```

3. Run local ganache with this command:
```
ganache-cli --fork <rpc https address> --networkId 1001 --gasPrice 0x1312D00 -e 100000000000000000000 --gasLimit 8000000
```

**Expected behavior**
Rejected transaction should result in `RPC Error: MetaMask Tx Signature: User denied transaction signature.` with no transfer of funds.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - MetaMask Version: 7.3.1

**Comment by ZimZim9** [comment]
> **Describe the bug**
> I'm trying to perform a function that exchanges one token for another, but I'm getting a very strange bug. If I call the function in web3, I get the standard metamask popup asking whether to confirm or reject the transaction. Now what's happening is if I hit reject, the value exchange still happens, even though there is no transaction on metamask nor on my ganache cli, just the values are updated on metamask. Then if I confirm the transaction, the transaction goes through as normal, except that double the expected value is exchanged.
> 
> Occasionally I get `RPC Error: MetaMask Tx Signature: User denied transaction signature.` as expected, yet the value is still exchanged. I've tried restarting my ganache cli, resetting my accounts on metamask, and even reinstalling metamask, but still the same.
> 
> **To Reproduce**
> 
> 1. Create smart contract with this function:
> 
> ```
> function deposit(uint amount) public {
>     require(daitoken.transferFrom(msg.sender, address(this), amount), 'transferFrom failed');
>     emit Transfer(msg.sender, address(this), amount);
>     require(ldai.mint(msg.sender, amount), 'mint failed');
>     emit Mint(msg.sender, amount);
>     emit Deposit(msg.sender, amount);
>   }
> ```
> 
> 1. Call function from web3 like this:
> 
> ```
> const num = this.state.amount * (10**18);
>     this.props.contract.methods.deposit(num.toString()).send({from: this.props.account});
> ```
> 
> 1. Run local ganache with this command:
> 
> ```
> ganache-cli --fork <rpc https address> --networkId 1001 --gasPrice 0x1312D00 -e 100000000000000000000 --gasLimit 8000000
> ```
> 
> **Expected behavior**
> Rejected transaction should result in `RPC Error: MetaMask Tx Signature: User denied transaction signature.` with no transfer of funds.
> 
> **Browser details (please complete the following information):**
> 
> * OS: Windows 10
> * Browser: Firefox
> * MetaMask Version: 7.3.1

> 0xD4D14e59F6a681dFe5a2E89e04ed7CcB1BBBd6c5

**Comment by tmashuang** [comment]
Investigating, all my reproduction steps haven't been successful in replicating the behavior 
>if I hit reject, the value exchange still happens, even though there is no transaction on metamask nor on my ganache cli, just the values are updated on metamask. Then if I confirm the transaction, the transaction goes through as normal, except that double the expected value is exchanged.
 
Which web3 version are you using? Or possible an simple repository that can reproduce the behavior?

**Comment by tmashuang** [comment]
Going to close this, if you are still having this issue feel free to follow up on my previous comment and any new information that can be provided.
