### ISSUE TITLE
Password field non-standard (incompatible with password managers)

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7355]
https://support.1password.com/compatible-website-design/

**Comment by EHaracic** [comment]
Pending Consensys: Dan M. has contacted Onepassword, we are waiting for their input.

**Comment by ElvirCe** [comment]
As advised by Dan, Vladimir will close this PR, unassign the ticket and updated the ticket with his findings here: https://github.com/MetaMask/metamask-extension/issues/7355#issuecomment-961107686.
Also, I will remove the ticket from PS-Tam backlog until the POs decide how to proceed further with this ticket.
