### ISSUE TITLE
Integrate webRequest redirecting to preserve urls on ipfs/ens sites.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7367]
The way we incorporate redirecting should preserve the URL context (either `ens://` or `ipfs://` etc).  This would also allow decentrally-hosted sites to persist cookies even after the gateway is changed.

I think that API may be [webRequest.onBeforeRequest()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest).

That work can build on https://github.com/MetaMask/metamask-extension/pull/7362, and should also be useful for the snaps system.

**Comment by danfinlay** [comment]
When we're ready to resume supporting ipfs resolution, we should reach out to Colin from protocol labs (@protocolin on their slack). He offered to connect us with some relevant people.

**Comment by Gudahtt** [comment]
Closing as a duplicate of #9353, which despite being more recent seemed to be a bit less prescriptive about how we'd accomplish this? At least in the title anyway.
