### ISSUE TITLE
Cannot use MetaMask with Ledger after re-connecting

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#7371]
**Describe the bug**
I opened MetaMask to send ETH to my mobile wallet. After entering all the tx details and hitting send, I realized MetaMask was open to my Ledger account and my Ledger was not plugged in. So I plugged in my Ledger and re-started MetaMask. I tried to send the tx again. When I hit send, MetaMask screen greyed out and I could not go any further; no signing notification showed up on Ledger either. I restarted MetaMask and tried again. Same problem. I looked at my tx history and saw a bunch of "approved" txs that weren't actually approved. I tried to cancel them. MetaMask said I had to pay a fee to cancel. Weird, since the txs were never signed and broadcast. But ok let's try that. Nope, MetaMask says the txs were already confirmed. Except they weren't confirmed, obviously they could not be since they were never even signed.

Now I cannot do anything with Ledger + MetaMask as I am stuck in this weird dead zone error loop.

I tried even deleting the Ledger account and re-adding it and still cannot do anything.

**Expected behavior**
I expect to be able to spend my money.

**Screenshots**

![metamaskcancelfail](https://user-images.githubusercontent.com/9424721/68514658-57153880-024c-11ea-911e-0dcf85efcaa1.png)

![metamaskcancelfail2](https://user-images.githubusercontent.com/9424721/68514668-5d0b1980-024c-11ea-98d9-4e58ad9e6d29.png)

![metamaskcancelfail3](https://user-images.githubusercontent.com/9424721/68514675-62686400-024c-11ea-98c3-03887943daf6.png)

![metamaskcancelfail4](https://user-images.githubusercontent.com/9424721/68514680-65fbeb00-024c-11ea-8096-daaa4192ed13.png)

**Browser details (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser: Chromium 78.0.3904.70
 - MetaMask Version: 7.4.0

**Comment by 7--** [comment]
I have similar issue. Can't connect my Ledger Nano X to Metamask using Firefox. It stays stuck on this screen. 
![Screenshot from 2019-11-15 20-16-42](https://user-images.githubusercontent.com/4725003/68985502-eb4f4480-07e4-11ea-8ece-7e9fe11e2eda.png)

**Comment by dpazdan** [comment]
Closing issue do to age and lack of others reporting similar.
