### ISSUE TITLE
signTypedData current status

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-extension#7373]
Hi, trying to figure out what the current status is of signTypedData. It looks like there are multiple versions. Does eth_signTypedData default to _v4? Is there a high probability of this changing in the near future or is it considered "stable"?

**Comment by aakilfernandes** [comment]
Think I may be confused cause it looks like eth-sig-util defaults the version to v4, but Metamask defaults it to v1

**Comment by danfinlay** [comment]
Very sorry for missing this. Our current docs cover this. We will only break any of these methods for security, we will add new `_vX` suffixes for additional methods.
https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask
