### ISSUE TITLE
Token transfers using 21000 gas

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#7382]
Version 7.4.0

I am unable to do anything from my metamask account because the most-recent transaction is stuck in a failed state. Attempting to retry the transaction, I see that it is setting the gasLimit to 21000, which is not enough for a transaction with data to be accepted by a node. Editing the gasLimit in Advanced is no-good; the retried transaction still has only 21,000 gas.

<img width="357" alt="Screen Shot 2019-11-10 at 2 50 02 PM" src="https://user-images.githubusercontent.com/799573/68552223-67065700-03c9-11ea-8f17-0eaedecacabb.png">

Restarting metamask does not clear the pending transaction.

I got in this state by trying to transfer TrueCAD to a winner of our ETH Waterloo competition. For whatever reason, this is treating it as an ETH transfer.

I am interested in a way to get unstuck without uninstalling.

**Comment by wjmelements** [comment]
The workaround seems to be to issue the transaction from another source. Transactions that fail in this way are replaced and not appending, thankfully.

**Comment by wjmelements** [comment]
I got into this state by initiating the token transfer from within MetaMask. I got out of it by using my personal wallet app.

**Comment by wjmelements** [comment]
I saw this again today. It happened when I start a token transfer from within Metamask. Doesn't happen every time.

**Comment by garciagonzalescristian** [comment]
Al momento de sacar la transacción o de imprimir el clip de verificación para autenticar y confirmar la cuenta de tokens Si pudiste confirmar la con la clave de verificación de tu cuenta y pudiste retirar en efectivo

**Comment by wjmelements** [comment]
I saw this again today. I think reproducing it requires you to enter recipient before changing currency from ETH.

**Comment by garciagonzalescristian** [comment]
8913179

**Comment by garciagonzalescristian** [comment]
0x48C0395e398fE1D38507380A09bC2Bdf1AD5D5AF

**Comment by wjmelements** [comment]
@bdresser
I see this 100% with these instructions:

1) From wallet view, click Send
2) Select Recipient
3) Change currency from ETH to TrueUSD
4) See 21000 gas
5) Transaction failure

<img width="353" alt="Screen Shot 2019-11-18 at 1 59 44 PM" src="https://user-images.githubusercontent.com/799573/69097989-8ece6e00-0a0c-11ea-99b9-c62fc252df1d.png">
<img width="353" alt="Screen Shot 2019-11-18 at 1 59 55 PM" src="https://user-images.githubusercontent.com/799573/69098025-9c83f380-0a0c-11ea-9d55-8ebdefd4f53b.png">

**Comment by wjmelements** [comment]
@brunobar79 Still seeing this in 7.6.1, 100% repro

**Comment by wjmelements** [comment]
Thanks Thomas!

**Comment by mj559940** [comment]
> @bdresser
> I see this 100% with these instructions:
> 
> 1. From wallet view, click Send
> 2. Select Recipient
> 3. Change currency from ETH to TrueUSD
> 4. See 21000 gas
> 5. Transaction failure
> 
> <img alt="Screen Shot 2019-11-18 at 1 59 44 PM" width="353" src="https://user-images.githubusercontent.com/799573/69097989-8ece6e00-0a0c-11ea-99b9-c62fc252df1d.png">
> 
> <img alt="Screen Shot 2019-11-18 at 1 59 55 PM" width="353" src="https://user-images.githubusercontent.com/799573/69098025-9c83f380-0a0c-11ea-9d55-8ebdefd4f53b.png">
