### ISSUE TITLE
Wallet in Metamask Gaz price is 3 and quantity 0 but unable to do anything

### ISSUE THREAD

**Issue by Sirlupinwatson1** [MetaMask/metamask-extension#7386]
![dffdffff](https://user-images.githubusercontent.com/55941045/68640805-d9b12880-04d6-11ea-8ce8-dcdeb9c5c0f7.png)
![Umeta](https://user-images.githubusercontent.com/55941045/68640806-da49bf00-04d6-11ea-8757-c07ea3bb0d0a.png)

**Describe the bug**

Doing some transaction on cryptokittties and after i open up a egg, wallet started to act like its always on loading.
If you want to input value for quantity of gaz, is not letting you input any value unless you click on modify and you go back. Still after input gaz, and click on check, the transaction keep on loading, close metamask, and stil the same the transaction and quantity of gaz are back to 3 price and 0 quantity

**To Reproduce**

Just open it to confirm transaction, i can see 3 and quantity 0
I click on either empty rectangle for quantity to set up to 21 000 but it freeze and numbers is not apprearing
I click on reject transaction, still the same
I logged out and back in , still the same

**Browser details (please complete the following information):**
 - OS: Windows 10 , Mozilla firefox , My walett on Chrome is fine
 - Browser Mozilla firefox , My walett on Chrome is fine
 

**Additional context**

I was able to trick it out by clicking on modify, what is hapenning is when i use my keyboard number to the right , i input the number 2 but is write -1 
i tried with the number row over the letter on keyboard, and they work good. Thanks for reply

**Comment by Gudahtt** [comment]
Thanks for the report! I believe we fixed this recent in #7379 . It should be included in the next release, [v7.5.0](https://github.com/MetaMask/metamask-extension/pull/7351#issuecomment-552628314)

**Comment by Sirlupinwatson1** [comment]
@Gudahtt  Thanks sir, i did not had the time to work on this , Intel AI is taking all my time but it will worth it i think. Thanks for the reply i appreaciate your time

**Comment by Gudahtt** [comment]
No problem! Please let us know if you notice this issue persists past v7.5.0. Thanks

**Comment by Sirlupinwatson1** [comment]
> 
> 
> No problem! Please let us know if you notice this issue persists past v7.5.0. Thanks

@Gudahtt  Well as of now since over 24 hours, my wallet is still frozen. In the forever loop loading transaction whatever i do. 

I can't even change walett adress. 
![ggit](https://user-images.githubusercontent.com/55941045/68726367-34a65680-058f-11ea-9eb6-268cad6ca9a2.png)

**Comment by Sirlupinwatson1** [comment]
> 
> 
> No problem! Please let us know if you notice this issue persists past v7.5.0. Thanks

Here is what i found : No module found



![metameta](https://user-images.githubusercontent.com/55941045/68735322-50b7f100-05ab-11ea-8be1-6a42b9e061f2.png)

**Comment by Sirlupinwatson1** [comment]
> 
> 
> No problem! Please let us know if you notice this issue persists past v7.5.0. Thanks

But also i cant find the 7.5 version, it only offer 7.4 . now i did lost also my account, i dont find anything. and the 7.4 is slow as hell, buggy

**Comment by Gudahtt** [comment]
v7.5.0 has not been released to Firefox yet. That will happen within the next few days.

**Comment by Sirlupinwatson1** [comment]
> v7.5.0 has not been released to Firefox yet. That will happen within the next few days.

yeah only on chrome, i did see that yesterday. thanks sir

**Comment by Gudahtt** [comment]
Version v7.5.2 should be available for Firefox now: https://addons.mozilla.org/en-CA/firefox/addon/ether-metamask/

**Comment by Sirlupinwatson1** [comment]
Well since that day, i lost all wallet i had, kitties, token, and anything related to this. i dont even have reply from metamask staff support.
