### ISSUE TITLE
Sign Typed Data fails silently with Ledger Nano S

### ISSUE THREAD

**Issue by recmo** [MetaMask/metamask-extension#7387]
**Describe the bug**
Signing Typed Data fails silently with Ledger Nano S on independent of browser.

**To Reproduce**
1. Go to 'https://danfinlay.github.io/js-eth-personal-sign-examples/
2. Click on any of the 'Sign Typed Data' options
3. See Metamask "Signature Request" popup
4. Click "Sign".
5. See Metamask popup go to account view.
6. See no indication of error.
7. Close Metamask popup.
8. See no report that a signature was received by testing page.
9. Open Dev Console.
10. See the following:

```
Object { code: -32603, message: "MetaMask Message Signature: Error: Not supported on this device", data: {…}, stack: "addUnapprovedMessageAsync/</<@moz-extension://b50fb798-6848-b543-9322-e594b780b24f/background.js:1:108566\ng@moz-extension://b50fb798-6848-b543-9322-e594b780b24f/background.js:1:837342\nh@moz-extension://b50fb798-6848-b543-9322-e594b780b24f/background.js:1:836035\n[350]</a.prototype.emit@moz-extension://b50fb798-6848-b543-9322-e594b780b24f/background.js:1:839022\n_setMsgStatus@moz-extension://b50fb798-6848-b543-9322-e594b780b24f/background.js:1:111069\nerrorMessage@moz-extension://b50fb798-6848-b543-9322-e594b780b24f/background.js:1:110810\nsignTypedMessage@moz-extension://b50fb798-6848-b543-9322-e594b780b24f/background.js:1:135534\n" }
```

**Expected behavior**
Either:
1. Signature confirmation on Ledger Nano and successful signing.
Or:
1. Clear error message indicating what I did wrong.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Mac OS 10.15.1 (19B88)
 - Browser FireFox (but also tested and confirmed in Chrome and Brave)
 - MetaMask Version 7.4.0

**Additional context**

**Comment by Gudahtt** [comment]
Related: #10240
