### ISSUE TITLE
Developer Version of MM with support for Plugins works on Brave, but not Chrome.

### ISSUE THREAD

**Issue by crazyrabbitLTC** [MetaMask/metamask-extension#7393]
**Describe the bug**

I am working through the setup for MetaMask Snaps: 
https://github.com/MetaMask/metamask-snaps-beta/wiki

Once I have followed all the instructions and gotten to the point where I can finally test the Snap by clicking "Connect" in the `hello-snaps` example, I receive an error on Chrome: 

`"Error: Problem loading plugin http://localhost:8081/package.json: Failed to fetch
    at t.exports._add (chrome-extension://ahmmkdkgafgiekpghibhoijklffjdppi/background.js:1:51836)"`

However when using Brave Browser and following the same steps (actually when trying brave browser at the same time- I am not doing two seperate setups which might leave room for an error), Brave performs as expect. I am able to connect to the plugin and test it. 

**To Reproduce**

I tested the setup instructions against Brave and Chrome. 

**Expected behavior**
A clear description of what you expected to happen.

I would expect Chrome to function the same as Brave, and to work. 

**Screenshots**
![Screen Shot 2019-11-12 at 2 43 02 PM](https://user-images.githubusercontent.com/1938013/68709898-91d8e280-0564-11ea-9a41-e9b6fca1b892.png)

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - MetaMask Version [e.g. 5.0.2]

MetaMask
7.2.1
ID: ahmmkdkgafgiekpghibhoijklffjdppi
From: https://github.com/MetaMask/metamask-snaps-beta
Commit: 6c27672

Brave Version:Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

Chrome: Version 78.0.3904.97 (Official Build) (64-bit)
**Additional context**

**Comment by crazyrabbitLTC** [comment]
Adding Logs: 

metamask Logs: 
https://gist.github.com/crazyrabbitLTC/62cd74868efd0f5e6f79826afd45923d

**Comment by Gudahtt** [comment]
Thanks for the report!

If you're still experiencing this issue, please report it on the snaps repo instead: https://github.com/MetaMask/metamask-snaps-beta. We're tracking snaps-specific bugs there at the moment.
