### ISSUE TITLE
Disable spell check in address inputs

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7397]
https://www.tutorialrepublic.com/faq/how-to-disable-spell-checking-in-html-forms.php

**Comment by nikhilol** [comment]
Hey! This looks like it hasn't been resolved yet, can I work on this? 😄

**Comment by BboyAkers** [comment]
PR is up!! Still wanting to validate the testing of this though! Can someone confirm as well? https://github.com/MetaMask/metamask-extension/issues/7397
