### ISSUE TITLE
V7.5.0 Couldn't find match for a reference for bignumber.js

### ISSUE THREAD

**Issue by yuwiggin** [MetaMask/metamask-extension#7399]
**Describe the bug**
The V7.5.0 is cloned and built with yarn, an error occured:
> `yarn`

```
yarn install v1.19.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error Couldn't find match for "94d7146671b9719e00a09c29b01a691bc85048c2" in "refs/heads/develop,refs/heads/gh-pages,refs/heads/master,refs/heads/original,refs/tags/v1.4.1,refs/tags/v1.5.0,refs/tags/v2.0.4,refs/tags/v2.0.5,refs/tags/v2.0.6,refs/tags/v2.0.7" for "https://github.com/debris/bignumber.js.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**To Reproduce**
1. Go to 'metamask-extension-7.5.0'
2. type yarn

**Expected behavior**
building done

**Runtime environment:**
 - Node 10.17.0
 - yarn 1.19.1
 - MetaMask Version 7.5.0

**Comment by Gudahtt** [comment]
That's curious; it worked for me even after running `yarn cache clean` with a freshly cloned repo. Maybe there was some sort of network error? The commit referenced is present: https://github.com/debris/bignumber.js/commit/94d7146671b9719e00a09c29b01a691bc85048c2

**Comment by Gudahtt** [comment]
I'm still not sure how you encountered this error, but I've removed that package from our project regardless (in #7472 ). Let me know if you're still having difficulty installing on the `develop` branch.
