### ISSUE TITLE
Signatures broken on popup (v7.5.1)

### ISSUE THREAD

**Issue by jgeary** [MetaMask/metamask-extension#7427]
**Description**
The metamask popup is not functional for several signature methods (eth_sign, personal_sign, sign_typed_data v1) for version 7.5.1. Neither the "Sign" button or the "Cancel" button do anything - the popup does not close and no signature is created. For a workaround I have found that if you close the popup, then click the metamask icon to see pending interactions, you can then complete the signature from there. This is a frustration for our users with the most recent version of Metamask.

**To Reproduce**
1. Go to https://danfinlay.github.io/js-eth-personal-sign-examples/ on Chrome (not sure about other browsers)
2. Click each button
3. Only Connect, Sign Typed Data V3, and Sign Typed Data V4 have functional popups. The rest have functionless buttons, and can only be completed by the workaround I described above

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/7414. Next version, which can be published to day, will fix this.
