### ISSUE TITLE
SIGN button broken for signing messages in popup

### ISSUE THREAD

**Issue by BrendanChou** [MetaMask/metamask-extension#7429]
**Describe the bug**
When asking the user to sign a hash, the CTA button on the popup window does not work (does not do anything, does not close the window, does not return a value to the browser).

However, the dropdown from clicking the MetaMask icon DOES work. This problem is exclusive to the pop-up window.

**To Reproduce**
Ask the user to sign a hash. A popup will come up. The "SIGN" button does nothing. Click on the MetaMask icon in the browser. The "SIGN" button on that dropdown does work.

**Browser details (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - MetaMask Version: 7.5.1

**Additional context**
Noticed this problem since 7.5.1 but it could also apply to 7.5.0. Worked fine in 7.4.0

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/metamask-extension/pull/7414. Will push an update soon.
