### ISSUE TITLE
jsonrpc: '2.0' missing from requests to custom network.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#7433]
**Describe the bug**
```javascript
window.ethereum.sendAsync({ jsonrpc: '2.0', method: 'eth_call', params: [{ }] }, console.log)
```
This will result in the following JSON-RPC call when connected to Custom network:
```
{
    "id": <big number>,
    "method": "eth_call",
    "params": [{ ... }]
}
```
Note the missing `jsonrpc: '2.0'` from the request.  This will result in the request failing since it isn't a valid JSON-RPC payload.

**To Reproduce**
1. Connect to localhost:8545 network.
2. `window.ethereum.sendAsync({ method: 'eth_call', params: [{ }] }, console.log)`
3. Notice the error response.
4. `window.ethereum.sendAsync({ jsonrpc: '2.0', method: 'eth_call', params: [{ }] }, console.log)`
5. Notice the success response.

**Expected behavior**
All required parameters are supplied on the JSON-RPC request, including missing id, jsonrpc, or params.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - MetaMask Version: 7.5.2

**Comment by MicahZoltu** [comment]
For reference:
https://www.jsonrpc.org/specification#request_object
> jsonrpc
>     A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".

**Comment by Gudahtt** [comment]
Thanks for the report! I can no longer reproduce this. I believe it was fixed in v8.
