### ISSUE TITLE
Gas set to X e9 not X

### ISSUE THREAD

**Issue by NescienceSoftware** [MetaMask/metamask-extension#7438]
Sending USDC (Any ERC-20).

When setting gas manually, and clicking on the visual graph of current tx, at a given Gas point, instead of setting gas to that value, it sets it to that value e9.

Simply enough you just have to type it in yourself, but newer users may not realize this and send a transaction with next to 0 gas.

Chrome
Metamask v7.5.0.1

**Comment by Gudahtt** [comment]
Thanks for the report! This was fixed in #7380 and should be available in v7.5.1+

Let us know if you still experience this problem after updating.
