### ISSUE TITLE
Newest Metamask is missing Cancel All and Cannot Resize

### ISSUE THREAD

**Issue by satosheth** [MetaMask/metamask-extension#7443]
The newest update to MetaMask negatively impacts the usability of several of my Dapps. I allow users to sign many requests at once, but with the new change the users have to scroll down every time. If you try to resize metamask to be longer it just leaves empty white space (as well as never saving the last used size.

![image](https://user-images.githubusercontent.com/1767934/68983419-81c53b00-07d0-11ea-977f-15dd8913c1f9.png)

Is there anyway to fix this to allow the size of the metamask window to be stretched and keep its dimensions?
We also lost the ability to "cancel all" transactions, which has also been a user complaint. Is there a way we can tell our users to downgrade to the old version or can we expect the old functionality to be added back in?

**Comment by Gudahtt** [comment]
Thanks for the report! I think this has been fixed since this was originally reported. The footer on the signature request page is always shown, and the contents are scrollable.

I'll close this for now, but please let me know if you're still seeing this issue.
