### ISSUE TITLE
MetaMask Approval Redesign No Longer Clearly Shows Approval Value

### ISSUE THREAD

**Issue by JayWelsh** [MetaMask/metamask-extension#7446]
**What problem are you trying to solve?**
The redesigned approval screen on MetaMask has removed the ability for users to immediately see how large the approval request is (this existed in previous versions of the approval screen and it is arguably the most important part of the approval screen, to clearly show what value of a given coin the approval request is for). I understand that one can click the "View full transaction details" button to see this figure but in my opinion, this is at a huge cost to UX, considering general users would not want to go so deep into the details of a transaction.

**Describe the solution you'd like**
Clearly show the value of the given asset that the allowance is being set for, as with previous versions of MetaMask

Screenshot of the redesign I am referring to:

<img width="361" alt="Screenshot 2019-11-16 at 18 47 37" src="https://user-images.githubusercontent.com/14224459/68996398-0c299f80-08a2-11ea-96c6-c5c736d24c07.png">

**Comment by bdresser** [comment]
Hey @JayWelsh, thanks for the feedback. 

As you probably know, approval requests often include an amount that is far more than the user has in their account, and probably far more than a site like an exchange will ever need. We did a substantial amount of user research on this screen and found that showing the amount requested was overwhelmingly confusing for users. We're choosing to focus on the substance of the function, rather than the asset amount. 

I will file this as design feedback and pass on to the UX team.

**Comment by JayWelsh** [comment]
Hi @bdresser , I'm sorry but I find that response to be incredibly illogical.

Users should be confused if they get an approval request for more than the user has available in their account (and keep in mind that you are now just hiding that from their vision, those approvals are still happening).

Dapp developers should make use of reasonable allowance settings, instead of requesting allowances which are effectively just the maximum possible value. You are degrading the user experience for developers and users who make use of proper allowance values and making it easier for developers who take the incorrect approach of setting max allowances.

Users have every right to be confused by a contract requesting an insanely high allowance, and this sort of developer practice should be strongly discouraged. This update and the stance you are taking on this matter simply makes it easier for developers to continue their bad practice of requesting ridiculous allowances (you are literally hiding something that users have every right to be concerned about, which is extremely worrying).

**Comment by JayWelsh** [comment]
Also, the fact that you don't consider the amount of a token that you are allowing a contract to spend on your behalf, as part of the "substance of the function", is ludicrous.

That is exactly the same as saying that the value of a transfer function is not part of the "substance of the function". The value is absolutely crucial and this stance being exhibited is deeply concerning, all for the sake of hiding a bad developer practice of requesting illogical allowance values?
