### ISSUE TITLE
Needs discussion! UX walk through notes with Sara

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-extension#747]
Notes from walk through with Sara Swathi 
- [ ] what is a vault
- [ ] possible option for click to copy ??
  - list version of the description of 12 word seed phrase
    - key points rather then a sentence 
      (“why do you need this” bullet point list) 
- [ ] hover text to explain `+` (in the account list)
- [ ] better explanation for forgetting password
  - `forgot password?` rather the a `<-back`
- [ ] settings for information wording
  - novice/advance (how much information needs to be revealed to the average user?)
- [ ] Why do i need these things? qr:export:etc.
  - possibly explain why you need these things?

**Comment by Zanibas** [comment]
> what is a vault
Me and @flyswatter had a good discussion about this--we will clarify this topic of distinguishing vaults, keychains, and keypairs.

**Comment by flyswatter** [comment]
But emphasizing the definition in the UI is important, too.

**Comment by eshon** [comment]
Is 'Vault' ever actually in the UI? It seems like a term that would only be used in the documentation. Was just discussing this with @VladTod

**Comment by Zanibas** [comment]
@eshon in our current iteration:
- At vault initialization, which happens only at first-time startup. 
- When viewing your seed words (first time or when revealing).

It doesn't come up too often aside from that.
