### ISSUE TITLE
Fix broken link in README.md in root dir

### ISSUE THREAD

**Issue by afmsavage** [MetaMask/metamask-extension#7471]
The link titled "How to generate a visualization of this repository's development" on the [README.md ](https://github.com/MetaMask/metamask-extension/blob/develop/README.md) in the root dir is dead.  Looks like the file its pointing to was deleted in #7144 and moved to [/development/gource-viz.sh](https://github.com/MetaMask/metamask-extension/blob/develop/development/gource-viz.sh)

Wasn't sure if I should just create a simple PR for it or an issue so I went with the least impact.  Let me know and I could update the README.md with a link directly to the script and update the script with some comments or do whatever you suggest.  Thanks!

**Comment by Gudahtt** [comment]
Thanks for highlighting this problem. Updating the README to point at the script would be greatly appreciated!
