### ISSUE TITLE
Allow user to define derivation path

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-extension#7486]
**What problem are you trying to solve?**
It seems there are a few cases where people would like to use derivation paths not currently supported by MetaMask.

- https://github.com/MetaMask/metamask-extension/issues/6716
- https://github.com/MetaMask/metamask-extension/issues/7238
- I myself would like to use the path `44'/1'/0'/0` for my Rinkeby accounts since this is also what [Frame](https://frame.sh) uses for Rinkeby accounts.

**Describe the solution you'd like**
I think rather than adding every possible derivation path users could want as a pre-set, MetaMask could simply give users the ability to set their own derivation path when setting up the wallet, for software and hardware wallets alike.

**Comment by lentils79** [comment]
Custom derivation path option for imported hardware wallets is very much needed!

**Comment by brad-decker** [comment]
Related to #8698 as well

**Comment by emariacher** [comment]
> 
> 
> Custom derivation path option for imported hardware wallets is very much needed!

The ultimate feature would be to brute force the ethereum address when connecting the HD wallet.

**Comment by Gudahtt** [comment]
Re-opening this, as this has not yet been implemented. It was attempted in #9367, but that needed to be reverted because it was found to be unsafe (see #9875 for details).

**Comment by bghughes** [comment]
I second this as a valid issue and having this feature would dramatically help me out when using Metamask
