### ISSUE TITLE
Add details to Reset Account in Settings

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#7493]
**What problem are you trying to solve?**
Support team is often asked if "reset account" option under settings --> advanced, resets value in the account.

**Describe the solution you'd like**
Provide additional information on what exactly is and isn't reset.  Something maybe like this:
![image](https://user-images.githubusercontent.com/16330048/69442174-b6c21800-0d11-11ea-8c49-514d28633c50.png)

**Additional context**
This will save time troubleshooting with users in support emails, less back and forth.  It will also ease concerns some have about the option to reset their account.

**Comment by whymarrh** [comment]
Refs #5577
