### ISSUE TITLE
Improve how we handle provider errors from send tx screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#750]
Right now if we fill out the send tx view, and get an error from the provider, the view will transition to the `confTxView`, which will have no data to show, except for an error message.

This makes for an ugly and empty view, when we should probably just show this error on the send tx view.

This is because [we transition to the confTxView](https://github.com/MetaMask/metamask-plugin/blob/master/ui/app/actions.js#L289) before waiting for a provider response.

That's because showing that UI is part of our hookedWalletSubprovider's authorization logic!

I think this is a **conflation of concerns**. The hookedWalletSubprovider's callback should initiate the transition to the `confTxScreen`, and we should not transition to it before then.

Discovered by @frankiebee

**Comment by flyswatter** [comment]
This might be nicely approached by separating how we handle internal sends vs dapp tx sends.

**Comment by danfinlay** [comment]
I believe this has been addressed.
