### ISSUE TITLE
Ledger Nano X can't sign transaction

### ISSUE THREAD

**Issue by lucasvo** [MetaMask/metamask-extension#7554]
I've tried to submit a transaction with my Ledger Nano X and received an error.  Without changing my setup or doing anything else, sending ETH to an address using the metamask frontend works without any problems.

This is on:
Mac OS Firefox using Metamask 7.6.1

<img width="456" alt="Screen Shot 2019-11-24 at 20 31 22" src="https://user-images.githubusercontent.com/31727/69500250-ce5bf500-0ef9-11ea-9339-dda6dde2ca45.png">

**Comment by lucasvo** [comment]
I can supply state logs if that is helpful.

**Comment by bdresser** [comment]
thanks @lucasvo - could you email the state logs to support@metamask.io and include this issue number?

**Comment by lucasvo** [comment]
@bdresser is it possible that this is linked to: https://github.com/LedgerHQ/ledgerjs/issues/205

I've changed the settings and upgraded the ethereum app on the ledger. It now says: "Denied by user?"

**Comment by lucasvo** [comment]
Using my ledger s I tried to execute the following transactions in this order:
1. add a signer to a gnosis-safe team edition. This failed.
2. allow the sai to dai migration contract on migrate.makerdao.com to convert my sai to dai. This worked at first try.
3. execute the migration. This also worked.
4. use chai.money to convert Dai to Chai. This worked without any problem. Again setting an allowance and then doing a contract call.
5. Trying my luck again with gnosis safe to submit a tx to the safe: ledger can't sign the tx.

**Comment by rene78** [comment]
Similar problem here (Win10 & Chrome 79.0.3945.117 & Metamask 7.7.1 & Ledger Nano S). Trying to deploy a contract to main net from Remix. 

Remix shows this error message:
Error: TransportStatusError: Ledger device: Condition of use not satisfied (denied by the user?) (0x6985)

In Metamask it is this one.
![image](https://user-images.githubusercontent.com/36115705/72468446-7b0d7100-37dd-11ea-9eb8-927174e76a43.png)

No problems whatsoever with Ledger Live.

**Comment by lucasvo** [comment]
I'm also experiencing this issue on a linux machine. The behavior is the same:
![metamask_ledger_issue](https://user-images.githubusercontent.com/31727/76632410-18b1c200-653b-11ea-8dfd-80c1700a73b0.png)

**Comment by jtremback** [comment]
Same problem

**Comment by hadlocna** [comment]
Same problem.  Using a MAC.  Interfacing with Defisaver.com
One account on ledger works, the 2nd doesn't.
The 2nd works with other web 3 apps, just not defisaver.com.  
Always shows the same error message.

**Comment by hoonsubin** [comment]
The same problem using Ledger BTC app to sign a P2SH transaction.
`"Ledger device: Condition of use not satisfied (denied by the user?) (0x6985)"`

this is the code 

```typescript
const unlockScriptTx = async (lock: BlockStreamApi.Transaction) => {
        setLoading({ loadState: true, message: 'Singing unlock script' });

        const lockSequence = btcLock.daysToBlockSequence(lockDuration.value);

        //const output = bitcoinjs.payments.p2pkh({ pubkey: Buffer.from(publicKey, 'hex') });
        const lockScript = btcLock.getLockP2SH(lockDuration.value, publicKey, networkType);
        if (typeof lockScript.redeem !== 'undefined') {
            try {
                // get ledger API
                const btc = await ledgerApiInstance();
                const rawTxHex = await btcLock.getTransactionHex(lock.txid, 'BTCTEST');

                const btcJsTransaction = bitcoinjs.Transaction.fromHex(rawTxHex);

                const ledgerTxData = btc.splitTransaction(rawTxHex, btcJsTransaction.hasWitnesses());

                const redeem = lockScript.redeem!.output!.toString('hex');
                const output = btcLock.getLockP2SH(lockDuration.value, publicKey, networkType);
                console.log(ledgerTxData);

                const res = await btc.signP2SHTransaction({
                    inputs: [[ledgerTxData, 1, redeem, lockSequence]],
                    associatedKeysets: [addressPath],
                    outputScriptHex: output.output!.toString('hex'),
                });

                console.log(res);
            } catch (err) {
                toast.error(err.message);
                console.log(err);
            } finally {
                setLoading({
                    loadState: false,
                    message: '',
                });
            }
        }
    };
```

**Comment by chrisbannocks** [comment]
Is there a resolution to this issue? I am having the same problem, when sending tokens, moving tokens between wallets or using uniswap... very frustrating..

**Comment by RhoadsNRoses82** [comment]
I'm also experiencing this issue. I transferred a bunch of tokens into my ledger address, and now i can't get them out

**Comment by RhoadsNRoses82** [comment]
*****possible fix********
I just figured out how to solve the issue in my particular case (ledger nano x, macOS 10.15.6, metamask on brave) - 

1. plug your ledger nano into the comp
2. click the metamask icon in your browser, then click the account selector circle at the upper right corner. Click connect hardware wallet.
3. it will load up a browser page, during which time you should unlock your nano with the pin.
4. open your ethereum app on the nano, go to settings, and the first thing you see at that point will be the toggle for allowing or disallowing contract data. ALLOW it.
5. do whatever transaction you wanted to do. This time your ledger should show the transaction and you can accept it. 

I think allowing contract data was the key here

**Comment by t8** [comment]
> open your ethereum app on the nano, go to settings, and the first thing you see at that point will be the toggle for allowing or disallowing contract data. ALLOW it.

This fixed my issue. Thanks so much @RhoadsNRoses82!

**Comment by jacobcantele** [comment]
Thank you so much for the resolution here @RhoadsNRoses82 . Since this is a setting on the Ledger and can be resolved by updating your Ledger settings, I'm going to close this issue for now.

**Comment by victorelec14** [comment]
still happening, now in the ETH version 1.6.2

**Comment by jesusperezsanchez** [comment]
![Problem](https://user-images.githubusercontent.com/32244603/103096002-c7bf1600-4602-11eb-97d5-a63a40edc556.jpg)

I have allowed the contract data in transaction. It only make some problems with some application.

**Comment by alexandernacho** [comment]
Issue still persisting on 1.6.2
Contract data allowed but nothing pops up

Brave on MacOS on MetaMask 9.0.3

**Comment by RhoadsNRoses82** [comment]
I also started having that problem again a week ago...couldn't connect my ledger to metamask no matter what i did. eventually i tried it on a different comp (a PC instead of a mac), and it worked. what's weird is that after that, i came back to my mac and tried it, and it worked also. So i guess my advice is try connecting it to a diff computer and then back again to your mac

**Comment by alexandernacho** [comment]
I found a workaround for Brave (which isn't optimal but it works): create a new user profile, download the MM extension again and connect your Ledger (making sure contract data is allowed obviously). Should probably also work on Chrome.

**Comment by RhoadsNRoses82** [comment]
hmm that would explain why it also worked when i did it on another comp. interesting, thanks for the tip!
