### ISSUE TITLE
Experimental Token Add (wallet_watchAsset)

### ISSUE THREAD

**Issue by HM999** [MetaMask/metamask-extension#7567]
With reference to this feature wallet_watchAsset, I would like to request 2 changes.

https://metamask.github.io/metamask-docs/API_Reference/Experimental_APIs

1. display decimal places.

It's unsafe to use anything other that 18 in the contract "decimals" field, because so much functionality in the ecosystem assumes it will be 18, however I can code the contract to preserve granularity. Would it be possible for the call to include a "displayDecimalPlaces" field, that is strictly for displaying quantities in MM?

2. longer symbol, 5 characters is too short.

ps: I use this feature and it works very well.

thx

**Comment by vandan** [comment]
Open-RPC doc to be updated (11 characters)
