### ISSUE TITLE
Incoming transactions controller should not fetch for networks not supported by etherscan api

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#7570]
```
Cannot read property 'length' of undefined at IncomingTransactionsController
```

**Comment by Gudahtt** [comment]
I am unsure whether this was a problem at some point or not, but currently we only fetch from the 5 built-in networks (mainnet, ropsten, rinkeby, kovan, and goerli). I believe Etherscan works for all 5 of these. We can reopen this if we discover otherwise!
