### ISSUE TITLE
712 signing types do not display booleans

### ISSUE THREAD

**Issue by MrChico** [MetaMask/metamask-extension#7575]
Signing a dai-style `permit`, the message displayed looks like this for me:
<img width="359" alt="Screen Shot 2019-11-22 at 17 44 22" src="https://user-images.githubusercontent.com/8930559/69639996-e6e52000-105d-11ea-99a3-03b2a22d880c.png">

Where's that bool? 🐙

**Comment by Gudahtt** [comment]
Thanks for the report! This looks like a duplicate fo #4639, which was fixed recently. Please let us know if you see this problem again in the latest version of MetaMask.
