### ISSUE TITLE
I'm trying to connect  an address on my Trezor hardware wallet to metamask. When I'm connected to the wallet I can choose from a list of addresses. I already searched through thousands of addresses, but the one I have my etherium token stored was not listed. Is there a way to search for the address. It would be nice if I could enter the address so that I can easily connect it to metamask

### ISSUE THREAD

**Issue by Gertsaar** [MetaMask/metamask-extension#7576]
**What problem are you trying to solve?**
A short description of what you're trying to do. E.g., "My users need to wrap ETH, but they're intimidated by the confirm screen..." or "I'm trying to debug my application, and XYZ..."

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Try to also include any alternative solutions you've considered.

**Additional context**

**Comment by bdresser** [comment]
hey @Gertsaar, please email support@metamask.io and we'll do our best to help you there
