### ISSUE TITLE
100% CPU Usage due to Metamask caused on Unity Asset Store

### ISSUE THREAD

**Issue by ablankenship10** [MetaMask/metamask-extension#7596]
**Describe the bug**
Loading the page https://assetstore.unity.com with MetaMask extension installed causes 100% CPU Usage

**To Reproduce**
1. Go to https://assetstore.unity.com
2. Open Chrome Task Manager
3. See 100% CPU Usage

**Expected behavior**
Not doing anything because why is MetaMask running on pages at all?

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - MetaMask Version (Unknown, uninstalled)

**Comment by lazaridiscom** [comment]
Confirmed on firefox. The firefox window where I access https://assetstore.unity.com hangs completely, even if i'm logged out from metamask.

**Comment by bdresser** [comment]
couldn't reproduce on Chrome @ablankenship10. if you don't know which version of MetaMask you were running, try installing the most recent version and let us know if the issue persists. 

<img width="687" alt="Screen Shot 2019-12-02 at 12 41 46 PM" src="https://user-images.githubusercontent.com/1016190/69981902-41b8c480-1501-11ea-91c6-834cc0ea0b0c.png">

**Comment by lazaridiscom** [comment]
@bdresser , maybe you oversaw https://github.com/MetaMask/metamask-extension/issues/7596#issuecomment-560013577, i can clearly make firefox hang, when visiting https://assetstore.unity.com/.
