### ISSUE TITLE
Where are the breaking changes that are coming?

### ISSUE THREAD

**Issue by FahdW** [MetaMask/metamask-extension#7597]
Trying to get a headstart but can't seem to find a beta branch with some of these breaking changes. Where are they located?

**Comment by lazaridiscom** [comment]
this here?

https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a

**Comment by lazaridiscom** [comment]
@FahdW , you can close the issue if the link contains what you were looking for.

**Comment by FahdW** [comment]
Was looking for the actual beta code that I can build the extension out of and run it locally. So I can test it.

**Comment by rekmarks** [comment]
@FahdW, the next version of MetaMask (`7.7.0`, which we plan to start rolling out today or tomorrow), will include the new API described in the gist in the following Medium article, _without_ breaking anything: https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a

So, you should be able to test the new API in the next few days. Nevertheless, we will post a build of `7.7.x` this week where all deprecated features have been removed. Watch this Issue for updates on that.

**Comment by lazaridiscom** [comment]
@FahdW , guess I oversaw "beta branch"

@rekmarks , maybe add the explaining info from your comment prominently in your article, thus anyone interested can find it immediately.

**Comment by rekmarks** [comment]
@FahdW please refer to https://github.com/MetaMask/metamask-extension/pull/7599 for the next build published on this date (after 701e142, it's currently in the CI pipeline).

**Comment by rekmarks** [comment]
@lazaridiscom we'll be posting all relevant links and builds when they're ready, including in the Medium article.

**Comment by FahdW** [comment]
Got the branch and running it locally thanks!

**Comment by rnons** [comment]
> @FahdW, the next version of MetaMask (`7.7.0`, which we plan to start rolling out today or tomorrow), will include the new API described in the gist in the following Medium article, _without_ breaking anything: https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a
> 
> So, you should be able to test the new API in the next few days. Nevertheless, we will post a build of `7.7.x` this week where all deprecated features have been removed. Watch this Issue for updates on that.

You mentioned "_without_ breaking anything", but seems BatchRequest is broken. As I understand, `BatchRequest.execute` assembles all payloads to an array
https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/batch-request/BatchRequest.js#L63
Then, this array is passed to `sendPayload` 
https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/providers/MetamaskProvider.js#L143

But, since MetaMask 7.7.0, the `send` method doesn't support array, resulting in this error
> backend.js:6 Error: MetaMask: Invalid request parameters. Please use ethereum.send(method: string, params: Array<any>).

What's the suggested way to work around this? Thanks
