### ISSUE TITLE
[TASK] Provide nacl-based Encryption

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-extension#7603]
(draft)

related #1190 (Initial user-filed Issue)

## Quick Summary

 * Give dApps the ability to request from a user a naclPublicKey (derived from the private key kept within mm), 
* key is used to encrypt data.
* dApp can request from user to decrypt data (mm asks user for confirmation) and send it back.

## Team

This task is currently mainly executed by contributor @logvik (own use-case) 

## Test Setup

```sh
git clone https://github.com/logvik/metamask-extension mm-encrypt
cd mm-encrypt
yarn
yarn dist
```
https://github.com/logvik/metamask-extension/blob/develop/docs/add-to-chrome.md

```sh
cd ..
git clone https://github.com/logvik/test-dapp
cd test-dapp
npm i
npm start
```

Open http://localhost:9000

### EIP level
* https://github.com/ethereum/EIPs/issues/130
* https://github.com/ethereum/EIPs/pull/1098

### Packages

Completed work (merged and npm published)

* [x] - https://github.com/MetaMask/eth-sig-util/pull/29
* [x] - https://github.com/MetaMask/eth-simple-keyring/pull/32
* [x] - https://github.com/MetaMask/KeyringController/pull/41
* [x] - https://github.com/MetaMask/eth-json-rpc-middleware/issues/18
* [x] - https://github.com/MetaMask/eth-hd-keyring/pull/21

### MetaMask Core

* [ ] - https://github.com/MetaMask/metamask-extension/pull/7247 => revise, review, e2e-test, Merge
* [ ] - provide the `encryption_public_key` API Call

### MetaMask UI 

* https://github.com/MetaMask/Design/issues/149
* https://github.com/MetaMask/Design/issues/154

### Test dApp

Used to test and further refine the implementation, and to showcase the functionality/

* [x] - https://github.com/MetaMask/metamask-extension/issues/7586
  * [x] - https://github.com/logvik/test-dapp

### Eth Ecosystem

* https://wiki.parity.io/JSONRPC-parity-module#parity_encryptmessage

**Comment by Gudahtt** [comment]
This was implemented in #7831
