### ISSUE TITLE
Lost import account after reinstall

### ISSUE THREAD

**Issue by Moncer** [MetaMask/metamask-extension#7606]
Hi.I reinstall metamask in chrome and lost 1 import account. How i can restore? And does any remote extension data of metamask is remain ??And accordingly I have no private key and seed phrase left

**Comment by lazaridiscom** [comment]
first of all: you can contact support@metamask.io for further help.

Last time I checked, you cannot restore imported keys.

Possibly you're luck, and it was not an imported, but a created one. Try this:

* Recreate accounts https://metamask.zendesk.com/hc/en-us/articles/360015489271-Restoring-Additional-Accounts-After-Importing-a-Seed-Phrase

If you're sure that it was an imported private key, search for it, possibly you've placed it somewhere else.

Finally, if you have a full backup of your machine (e.g. image-backup), you should be able to restore the key.

**Comment by bdresser** [comment]
@Moncer please email support@metamask.io and we'll do our best to help you over there!
