### ISSUE TITLE
Transaction Processing Error in Meta Mask when using Private Chain in Sending Ether from 1st Account to 2nd

### ISSUE THREAD

**Issue by mirzausman371** [MetaMask/metamask-extension#7607]
When i Try to Mine Block in my Private Chain to Write Transaction i got some kind of error.

WARN [12-01|00:56:25.428] Served eth_sendRawTransaction            conn=127.0.0.1:50392 reqid=1240993788731 t=0s        err="known transaction: c94412bf304489e3f0a18c829d86ac7dba1396313c021e6868e209ec8f1b9621"

WARN [12-01|00:56:18.810] Served eth_sendRawTransaction            conn=127.0.0.1:50390 reqid=1240993788721 t=0s      err="replacement transaction underpriced"

and this issue kept repeating in mining

**Comment by bdresser** [comment]
@mirzausman371 can you please provide detailed reproduction steps

**Comment by mirzausman371** [comment]
I've created Ethereum Private Blockchain on Local And Connected through IPC Protocol. Ethereum Mining produced Successfully and Synchronization with Meta Mask is Good till Now. But with i try to send some Ether from one account to another there i get this error

**Comment by tmashuang** [comment]
I am going to close this unless there is additional information to go on. We broadcast transactions frequently, not just on the initial confirmation. Although after the tx is confirmed we should stop broadcasting if this is not the case let us know.
