### ISSUE TITLE
[CRITICAL] Please Triage Issues and Verify the Tracker-Link

### ISSUE THREAD

**Issue by lazaridiscom** [MetaMask/metamask-extension#7608]
From what I know, you use an internal tracker in addition to the public github issue-tracker. Those two are linked via the the issue-labels.

Possibly something went wrong, as for more than 3 weeks, the issues here on github remain without reply/label.

Additionally, many issues (back to 2017) are unlabeled:

https://github.com/MetaMask/metamask-extension/issues?q=is%3Aopen+is%3Aissue+no%3Alabel

Please verify the link between your internal tracker and github.

**Comment by bdresser** [comment]
thanks for your concern @lazaridiscom! we're still using an internal tracker. labels are not a representation of awareness. we're trying to stay focused on some bigger picture projects, but issues are of course useful as always.
