### ISSUE TITLE
New "approve" screen doesn't let you copy the address being approved

### ISSUE THREAD

**Issue by haydenadams** [MetaMask/metamask-extension#7615]
**Describe the bug**
Address being approved is truncated and can not be copied.

**To Reproduce**
1. Do an approve transaction
2. Look at transaction details
3. Try and figure out how to get the address being approved, other than parsing raw transaction data

**Expected behavior**
A little button that allows you to copy the address.

**Screenshots**
![image](https://user-images.githubusercontent.com/9343483/69991630-0a084780-1516-11ea-84d7-16792f6d5117.png)

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser - Chrome
 - MetaMask Version - Latest

**Comment by danfinlay** [comment]
@MetaMask/design  ^ good opportunity to enhance this design. Anywhere we show an address is an opportunity to do all the things we do for an address.

**Comment by cjeria** [comment]
It appears this was spec'd in the initial designs but wasn't implemented and was missed during QA. See mockup below. This is the icon I'd suggest we use for the [copy to clipboard](https://fontawesome.com/icons/clone?style=light). I'd also advise making the entire address string clickable + tool tip "copy to clipboard". cc @danjm @whymarrh

![image](https://user-images.githubusercontent.com/597770/70171806-540f3b80-1684-11ea-92dd-7437f2dbddae.png)

**Comment by cjeria** [comment]
@danjm consolidating design feedback for Approve screen designs here.

1. The current approve screen account details row has some text-overflow bugs. The proposed solution is to show a header and balance of the specific token being approved.

![image](https://user-images.githubusercontent.com/597770/70464256-65d15400-1a73-11ea-8c7b-9d6025628886.png)

2. The expanded transaction fee detail section has a few px's more padding. It should be flush with the top section at 24px padding:
![image](https://user-images.githubusercontent.com/597770/70464636-1fc8c000-1a74-11ea-8224-49293927065e.png)

**Comment by danfinlay** [comment]
We also got some feedback today, which I agree with, that the top of the `approve` screen should not refer to the domain, but to the contract address actually being granted the permission. It should also have its name drawn from the address book or reverse-resolved from ENS if possible (not just hex or the word "contract" for "to").

This is to match the reality of what is being trusted: The smart contract, not the domain. Might also want to add a link to its block-explorer page.

![prompt](https://user-images.githubusercontent.com/542863/70485640-6209f580-1aa4-11ea-9600-8a3b1760a081.png)

**Comment by cjeria** [comment]
> We also got some feedback today, which I agree with, that the top of the approve screen should not refer to the domain, but to the contract address actually being granted the permission.

@danfinlay based on our [lengthy design discussions](https://github.com/MetaMask/Design/issues/38), the goal was to make the Approve screen overall more human-readable and reduce confusion for the user. 

Since the user is interacting with a site/dapp at the very moment that the Approve function is called, it makes more usability sense to call out the domain in the header for the reason that it provides the user a more direct context and association with the dapp/site they are interacting.

We were also very conscious about making it simple to access the `contract address`, which is just one level deep under the `transaction details`. So we feel confident that this design meets the requirements that satisfy our usability goals with pro users' needs with minimal friction. That said, I don't feel it's not necessary to swap out the domain name with the contract address. 

cc @bdresser @rachelcope @omnat

**Comment by danfinlay** [comment]
> @danfinlay based on our lengthy design discussions, the goal was to make the Approve screen overall more human-readable and reduce confusion for the user.

The length of the discussion is irrelevant. Long discussions can reach wrong conclusions.

The word we're showing there is not representative of what is being permitted, and without the presence of the actual address, we are not giving the tools to correctly review this.

>  We were also very conscious about making it simple to access the contract address, which is just one level deep under the transaction details. So we feel confident that this design meets the requirements

Currently this address is concatenated, and does not allow copying, so this requirement is not yet met:

![Screen Shot 2019-12-10 at 2 55 38 PM](https://user-images.githubusercontent.com/542863/70576241-47478780-1b5d-11ea-83f3-68b5dab53df8.png)

It would also be nice to use the address book and/or ENS to render a rich name here when available.

**Comment by cjeria** [comment]
Dan pointed out that Etherscan now has dedicated [smart contract pages ](https://etherscan.io/dapp/0x06012c8cf97bead5deae237070f9587f8e7a266d). We may want to consider linking users to these smart contract **dapp** pages from the **Approve screen**. We may also want to take inspiration from how they display the smart contract address for our approve screen (bubble up the smart contract address). cc @rachelcope 

<img src="https://user-images.githubusercontent.com/597770/71128163-74211d80-21a1-11ea-92ab-aa786d314342.png" width="400">

**Comment by amsimoes** [comment]
Guys, any update on this?

It isn't possible yet to check the contract requesting approval, being useless actually...

![Screenshot 2020-11-07 at 22 30 22](https://user-images.githubusercontent.com/13181161/98452612-d469d680-2148-11eb-9a00-8a214fc590f4.png)

Is there any workaround to check the contract apart from confirming the TX? Like in console/inspector?

![Screenshot 2020-11-07 at 22 31 46](https://user-images.githubusercontent.com/13181161/98452625-08dd9280-2149-11eb-91c4-71876dd54481.png)

@cjeria 

Thanks!

**Comment by dzid26** [comment]
Seems like a easy fix.  
It's a shame one still cannot easily verify address of a contract they interact with. 

Yes, this is a security issue.

**Comment by jedctl** [comment]
I double the comment by @dzid26 on top. It is really frustrating issue you can't check a contract before confirming a transaction.

**Comment by bschorchit** [comment]
Closing as this has been solved. There's a copy button currently in prod.
