### ISSUE TITLE
Random Comma when signing transactions

### ISSUE THREAD

**Issue by FahdW** [MetaMask/metamask-extension#7624]
**Describe the bug**
There's a random comma beside the sign button

**To Reproduce**
1. Run a transaction that needs to be signed

**Expected behavior**
No comma

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Browser [e.g. chrome, safari] Chrome
 - MetaMask Version [e.g. 5.0.2] 7.7.0

**Comment by tmashuang** [comment]
For reference, next to the Sign Button.

![Screenshot 2019-12-03 21:00:11](https://user-images.githubusercontent.com/13376180/70114138-491ac380-1610-11ea-9d11-d5dbdc6e7433.png)
