### ISSUE TITLE
v7.7.0 Dapp Devs - How to switch accounts on a given site

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#7643]
First brought out on [reddit](https://www.reddit.com/r/Metamask/comments/e5xaea/metamask_breaking_change_for_dapps_read/?utm_source=share&utm_medium=ios_app&utm_name=iossmf). 

TLDR; 

User story could be i.e. swap Sai -> Dai (or w.e.) but doesn't remember  which Account it's under.
Navigating to Account 3 (guess - timation) then realize its not there via auto-pop token list. Guess - timate next Account 2. etc.

Question: How to swap to Account 2 in this scenario??

My idea would be a screen before the tx-conf to select account.

**Comment by danfinlay** [comment]
Currently there are three ways, two of which work:

## The working ways:

### The site calls enable() again

`ethereum.enable()` initiates a fresh login, so sites can add a "switch account" button easily.

### Disconnect from the site first.

Users can use the "Connected sites" menu to disconnect the current connected account:
![eip-2255-logout-smaller](https://user-images.githubusercontent.com/542863/70144854-aedc6f00-1653-11ea-9cf2-26426b190acc.gif)

## The not working way:

### Connect from a different account

When logged in with account 1, select account 2, and then select "connected sites". Does not seem to currently work properly.

**Comment by kartojal** [comment]
Have a question, does `window.ethereum` fire a event when the user "switches" his account? This event does not need to reveal the new address, but at least to notify to the frontend, and asking again to enable permissions if is a new address.

**Comment by satosheth** [comment]
If a user is logged into my dapp with one account and then switches the account, it does not update to the new account. Even if they close the web page, switch accounts, and open it again with the new account, it just reverts back to the first account. Is there some breaking change to accounts that we should know about with this new version?

**Comment by kartojal** [comment]
Was thinking about using  `ethereum.on('accountsChanged',  function () {})` method, and ask for permissions, but does not work with in this release.

You can try yourself with the next minimal example, prior Metamask release fires the event, new one does not fire this event.
https://jsfiddle.net/Lo3910sm/

**Comment by danfinlay** [comment]
Yes. `ethereum.on('accountsChanged', function (accounts) {})` per:
https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider

**Comment by danfinlay** [comment]
We've rolled back 7.7.0 for now until we can fix these usability issues, thanks a ton for reporting the things you find!

**Comment by cjeria** [comment]
There were UX considerations we considered during the design phase of this work that unfortunately didn't make it into this release. We feel as though these important design considerations would have likely mitigated and/or reduced user confusion.

Through the many discussions/concerns we had during design cycles regarding accounts switching, the one we landed on was a toast message in MetaMask that appears when the user switches accounts after one has been connected to a dapp. The notification (see below) displays a message saying the account selected is not connected. We also give the user a `connect` button option right within the notif. If clicked, it would connect them to the dapp with the current account selected.

We realize that changing the core behavior of account switching is a big deal so we appreciate all feedback while we continue testing and iterating. 

Feedback on the below designs is also greatly appreciated! 

![image](https://user-images.githubusercontent.com/597770/70186735-719ece00-16a1-11ea-8dcd-3cc843699127.png)

![ezgif com-optimize](https://user-images.githubusercontent.com/597770/70186246-5b444280-16a0-11ea-989b-3e72b8a1f9fe.gif)

**Comment by satosheth** [comment]
That looks good to me. As a dapp developer I mainly care that we can programmatically listen for an account change and then prompt the users ourselves to connect their wallet if it hasn't been approved yet.

I was also seeing the wallet automatically switch to an approved account when going to a site (when I loaded the site with a non-approved account), which was confusing and could cause users to be interacting with a different account then they thought.

**Comment by CrackerHax** [comment]
I would like to see the addition of a site request for a switch to a custom RPC network.
