### ISSUE TITLE
eth_signTransaction on Metamask

### ISSUE THREAD

**Issue by iris112** [MetaMask/metamask-extension#7644]
Hi.
I'm getting RPC error when i try to sign transaction using metamask.
That is our important features. But currently i think metamask is not working for this api.
Is that correct?
How can i solve this issue using metamask?

Thanks.
Regards.

**Comment by jennypollack** [comment]
Hey @iris112 are you still having this issue/can you provide more information?

**Comment by kronrod** [comment]
It would be great if MetaMask could be used to sign transactions without sending them to the network. In particular, MetaMask should support the "send offline" feature of my ether wallet (https://www.myetherwallet.com/interface/send-offline). Currently, when trying to use "send offline" with a MetaMask account, metamask signs the transaction and sends it to the network. When doing the same with a ledger, the ledger correctly signs the transaction and returns it to myetherwallet as illustrated here:

![image](https://user-images.githubusercontent.com/3128389/88523054-97456280-cff7-11ea-820c-5f8be29c5bea.png)

The return value should be a signed, raw transaction. For example 0xf864808502540be4008252089429fe8914e76da5ce2d90de98a64d0055f199d06d808025a0aae01c955ba016574a64f3cf10dcd0f885d73e684dd252c05bccc016e4b66a6da01908951150436377b038f951ab055a5fca5d066950d649aead6e041020785662 for the simple case from the screenshot.

To fix this issue, I'd suggest that MetaMask starts supporting the Web3 RPC method eth.signTransaction as documented here (https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#signtransaction). When trying to do so with the current version, web3js returns with "Error: The method 'eth_signTransaction' does not exist / is not available.". This is probably also the error @jennypollack was referring to.

As an important note, MetaMask should support the nonce property in this case and not ignore it! If an application is requesting a transaction to be signed without sending it to the network, it should be assumed that the application knows what it is doing and thus also is requesting the correct nonce. In fact, in case there are multiple pending "offline" transactions that the application plans to send to the network later, MetaMask cannot figure out what the correct nonce should be as these transactions are not known yet in the network. Also note that the "nonce" parameter is missing from the Web3js documentation, but is part of the JSON RPC specifiction for eth.sendTransaction (see https://eth.wiki/json-rpc/API) and also supported by the actual Web3js implementation. So this is an error in the current version of the Web3js documentation, for which I will file a separate report with them.

**Comment by kronrod** [comment]
Maybe some more details about my use case, just to provide some background information. I am working on a multisignature contract that allows to separate the signing and the paying of a transaction. So one user can sign it without using any gas and then the another user can send the transaction to the multisignature contract and pay for it. Gas station network uses a similar concept to pay for user transactions. It allows to develop user-friendly dapps that can also be used by users that have no Ether. For security reasons, we do not want to resort to sign raw hashes, but use the much more transparent "sign transaction" method instead that allows wallets to tell the user what they are actually signing.

As a further sidenote: MetaMask should in such cases not only trust that the calling application set the nonce correctly, but not interfere with the gas limit and gas cost (if provided). In our use case, 0 are valid values for both the gas limit as well as the gas costs as those are paid for later in a separate transaction.

**Comment by pcaversaccio** [comment]
@kronrod take a look at the thread [here](https://github.com/MetaMask/metamask-extension/issues/3475). I just remember it since we had similar issues with Alethena back then and MetaMask won't change its mind I suppose.

**Comment by kronrod** [comment]
@pcaversaccio thanks for the hint. It sounds like the devs behind MetaMask are unable to recognize this need. Fortunately, we will have our own wallet soon. :)

**Comment by Gudahtt** [comment]
Closing, as the original reported issue here didn't include enough detail to investigate, and the follow-up conversation seems to be about something entirely different.
