### ISSUE TITLE
7.7.0: No longer receiving transaction receipt or confirmations

### ISSUE THREAD

**Issue by remon-nashid** [MetaMask/metamask-extension#7653]
We've noticed a regression in our web3.js dapp with Metamask `v7.7.0`. Basically, no tx receipt or confirmations are received despite that a transaction is mined.

**To reproduce**

I deployed a simple Counter contract to **Kovan**, as well as a simple app that uses `web3@1.2.4` and Metamask to sign a transaction as soon as the dapp is loaded.

- `git clone git@github.com:remon-nashid/mm-770.git` 
- `cd mm-770`
- `yarn install`
- `yarn run`
- Your browser will open a new tab, navigate to `localhost:3000`, and Metamask will prompt you to connect to the app.
- Open devtools to monitor console log messages.
- Change Metamask network to `Kovan`.
- Sign the metamask transaction that pops up first thing.
- You'll notice that only txHash is printed to browser's console. No confirmation or receipt messages despite that the transaction goes through.

**P.S** that regression has been either fixed or rolled back in `7.7.0.1`, but I thought I'd report this issue to make sure the regression won't make it to a future version, or that at least it is documented.

**Comment by tmashuang** [comment]
For reference:
https://github.com/remon-nashid/mm-770/blob/master/src/App.js#L36-L45  
`"web3": "^1.2.4"`

**Comment by Gudahtt** [comment]
Thanks for the report! Since you've found that this was fixed in v7.7.0.1, I'm going to close this for now. Please let us know if you see this problem again in the latest version of MetaMask.
