### ISSUE TITLE
MetaMask freezes and show white screen on appearing for 60 sec even after restart

### ISSUE THREAD

**Issue by k06a** [MetaMask/metamask-extension#7660]
**Describe the bug**
MetaMask freezes for 1min on almost every action

**To Reproduce**
IDK, this happens only on my second account!

**Expected behavior**
Not to freeze

**Screenshots**
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/702124/70345800-43261c00-1876-11ea-92a2-57b6f72e253d.png">

**Browser details (please complete the following information):**
 - OS: macOS 10.15.1
 - Browser: Google Chrome 78.0.3904.108
 - MetaMask Version: 7.7.0.1

**Comment by bdresser** [comment]
@k06a how many transactions are there in your history on that second account? if you "reset account" (in settings) does the issue persist?

**Comment by tmashuang** [comment]
Going to close this and link a couple more issues this is related to, #6017 #4894. If there is any more relevant information please feel free to comment any of those issues.
