### ISSUE TITLE
Metamask says it only allows tokens with symbol between 0 and 12 chars, but doesn't allow 12 chars

### ISSUE THREAD

**Issue by wmitsuda** [MetaMask/metamask-extension#7668]
**Describe the bug**
It is as the bug title says

**To Reproduce**
1. Add a custom token on Metamask
2. Paste 0x66117f59814DC7f2AaA7A2f90F6ef16F7e2b363D as the token contract address (mainnet)
3. This token symbol has exactly 12 characters
4. The extension complains saying it should be between 0 and 12 characters.
5. If you edit the name and remove 1 character (so it has 11), it accepts the symbol.

**Expected behavior**
The extension should support 12 characters in the symbol as the error message says.

**Screenshots**
![image](https://user-images.githubusercontent.com/28685/70400136-fd995880-1a07-11ea-8f30-6ca83332e56e.png)

**Browser details (please complete the following information):**
 - OS: macos Catalina
 - Browser: Chrome
 - MetaMask Version: 7.7.0.1

**Comment by lazaridiscom** [comment]
Should be `  > 12`  https://github.com/MetaMask/metamask-extension/blob/2c33ad3eb48bdb367784a3edfff1dbc553465471/ui/app/pages/add-token/add-token.component.js#L194-L196

**Comment by Gudahtt** [comment]
The behaviour here does match the error message, though I can see why it would be confusing. It means it should be between 0 and 12 characters _exclusive_, as in greater than 0 or less than 12. Hence zero not being accepted either.

I think ranges of numbers are generally assumed to be inclusive unless stated otherwise, so this error message should be changed to something easier to understand, e.g. "greater than zero and less than 12 characters"

**Comment by wmitsuda** [comment]
May I ask why the limit should be 11 and not 12 then? Is there some specification stating these limits?

**Comment by lazaridiscom** [comment]
The error-message, yes, it's a bit confusing

Possibly Better => **Symbols must be from 1 to 11 characters.**

Though in usual UI-Design, this would be a `mandatory` field with a `max-len` of 11 (one cannot enter more chars).


btw: it looks like in "real-life", the symbols are 1 to 9 chars:

https://ethereum.stackexchange.com/questions/25619/is-there-length-limits-on-token-symbols

reading a few minutes around, I did not find any mentioned limit.
