### ISSUE TITLE
Behaviour of MM after rejecting a transaction - FR

### ISSUE THREAD

**Issue by prographo** [MetaMask/metamask-extension#7670]
This is not a bug, I just think the way MM behaves is "odd"

If the MM pops up because a website has initiated a transaction, (ofc due ultimately to the user's interaction with the website), this is good. If a subsequent transaction is initiated, the popup appears once again, this is also good and what I would expect.

However:

If the MM popup is rejected, subsequent transactions initiated by the website do NOT launch the popup, instead the popup is hidden, all that shows is a notification on the MM icon in the bar at the top (chrome). I think this is wrong, the popup should appear again, every time. It is confusing because it is inconsistent behaviour.

**Comment by Gudahtt** [comment]
This sounds like #7051

**Comment by prographo** [comment]
Indeed, good spot - although they are vague on how to reproduce, do what I said, you will see it everytime.

**Comment by tmashuang** [comment]
Fixed by #8446
