### ISSUE TITLE
Failed txs caused by gas limit set too low for erc20 tokens

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#7709]
**Describe the bug**

**To Reproduce**
Attempt to send any erc20 token with default gas limit/gwei set.  Most are being set with gas limit of 40 - 45,000 gas limit.  Checking back about a month ago (pre hard fork, pre MM v.7.7.1, the same tokens were being sent with 140 - 150,000 gas limit set.

**Expected behavior**
Better estimation of gas limit / gwei in order to not have failed tx.

**Screenshots**
![image](https://user-images.githubusercontent.com/16330048/70935745-8155d500-2006-11ea-8895-f53bc3d66a84.png)

**Browser details (please complete the following information):**
 - MetaMask Version 7.7.1

**Additional context**
Reference support tickets 27977, 27941, 27985, 28023

**Comment by dpazdan** [comment]
examples of tokens set with gas limits below 45,000: 
IND, MKR, DAI, CAT, OCEAN, OXT, NMR, KICK, DATA 

Interestingly, KCS seems to stay at the 100,000 default.  SNX seems to have gas limit estimated properly, over 224,000.

**Comment by calbertuk** [comment]
I can confirm some people including myself are having the same issues.

**Comment by dpazdan** [comment]
I noticed if you manually increase the gwei the gas limit increases to an appropriate amount as well.  For Dai I saw a default gas limit set to 42801, when increasing gwei, the gas limit changes to ~55,000+ (it seems to check again).

**Comment by danfinlay** [comment]
Tried and failed to reproduce this issue. Here are my notes:

## Out of gas error investigation notes

Attempting to send FOAM tokens from within MetaMask desktop UI.

Initiated an `eth_estimateGas` call of:

```
curl 'https://api.infura.io/v1/jsonrpc/mainnet' -H 'authority: api.infura.io' -H 'accept: application/json' -H 'origin: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn' -H 'content-type: application/json' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'infura-source: metamask/internal' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: cors' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en,fr;q=0.9,en-US;q=0.8,es;q=0.7' --data-binary '{"id":417110591973,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0xfdea65c8e26263f6d9a1b5de9555d2931a33b825","value":"0x0","data":"0xa9059cbb000000000000000000000000fdea65c8e26263f6d9a1b5de9555d2931a33b8250000000000000000000000000000000000000000000000000000000000000000","to":"0x4946fcea7c692606e8908002e55a582af44ac121","gas":"0x90a61c"}]}' --compressed
```

Which returned a value of `{"jsonrpc":"2.0","id":417110591973,"result":"0x8e54"}`.

        That hex value translates to `36436`.

Clicking `Edit gas > Advanced` to view the gas estimate in UI shows a gas limit of `54654`, which is 50% higher, and accurately reflects the `[1.5x buffer we add when suggesting a gas limit](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/tx-gas-utils.js#L138-L142)`.

This transaction was [sent](https://etherscan.io/tx/0xbe8b38a764000a0c111dc6083f65e82beb4a9557da9020ce0704e3a4615c72b7) with the MetaMask-suggested gas limit.

This transaction resulted in a success.

Maybe FOAM wasn't one of the affected tokens. Trying again with one [listed by David Pazdan](https://github.com/MetaMask/metamask-extension/issues/7709#issuecomment-566308780).

On checking his latest comment, I see that he experienced a correct estimate upon editing gas value. This suggests that maybe the increased gas buffer is only being added after "Edit" is clicked. I will now try again without opening the edit screen, and I will try with DAI:

This initiated the following request to infura:
```
curl "https://api.infura.io/v1/jsonrpc/mainnet" -H "authority: api.infura.io" -H "accept: application/json" -H "origin: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn" -H "content-type: application/json" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36" -H "infura-source: metamask/internal" -H "sec-fetch-site: cross-site" -H "sec-fetch-mode: cors" -H "accept-encoding: gzip, deflate, br" -H "accept-language: en,fr;q=0.9,en-US;q=0.8,es;q=0.7" --data-binary "^{^\^"id^\^":417110591976,^\^"jsonrpc^\^":^\^"2.0^\^",^\^"method^\^":^\^"eth_estimateGas^\^",^\^"params^\^":^[^{^\^"from^\^":^\^"0xfdea65c8e26263f6d9a1b5de9555d2931a33b825^\^",^\^"value^\^":^\^"0x0^\^",^\^"data^\^":^\^"0xa9059cbb000000000000000000000000c5b8dbac4c1d3f152cdeb400e2313f309c410acb00000000000000000000000000000000000000000000000000038d7ea4c68000^\^",^\^"to^\^":^\^"0x6b175474e89094c44da98b954eedeac495271d0f^\^",^\^"gas^\^":^\^"0x904ec9^\^"^}^]^}" --compressed
```

Which resulted in this response:
`{"jsonrpc":"2.0","id":417110591976,"result":"0xcb1a"}`

Which translates to `51994` gas, which is more expensive than a FOAM transfer, but could totally be within normal variation.

I opened the inspector then to see what the gas estimates were being used by the UI.

The TX was initialized with a gas value of `0x130a7` or `77991`, which is the higher fudged value, so this looks good so far.

Then there is then an `estimatedGas` value set to the same thing, so it's all looking good so far, in terms of the tx using the upward-fudged estimate of what the node told us.

This transfer [was also successful](https://etherscan.io/tx/0x733e068d65e6f6189af87e4c35d20873271de05c63cbc11e523f7617fc5ae8b6), and so I have been unable to reproduce this bug.

I would like to analyze some state logs from users who were affected, to see when the estimate may be varying unacceptably.

In the meanwhile, we could increase our gas-buffer value from 1.5 to something else. Would we dare give it a full 2x?

**Comment by danfinlay** [comment]
David has a good bug reproduction issue. In it, he:

- From the MetaMask popup (action-view) (I had used the full screen view)..
- Selects the token first (I also did)
- Clicks "Send" on it.
- He has the advanced gas inputs enabled (could this be a common theme among those affected?)
- The initial estimate is low, but when he clicks up or down on the gwei, the gas limit also suddenly updates.

I'd ask: Are affected users all using the advanced gas inputs?

**Comment by dpazdan** [comment]
I'm only able to reproduce this consistently with advanced gas controls enabled.  Disabling it seems to fix.  Also interesting, the default gwei is greatly different when this setting is enabled vs disabled.

I'll circle back with others to see if they all have advanced gas setting enabled. 👍

**Comment by dpazdan** [comment]
support case with logs to review: 28817
will add more here as we get them.

**Comment by DragonFish69** [comment]
Following advice from the support team, I have increased my Gas Limit to 100,000 for each of the ERC20 token and saved this setting via the 'Advance Options' button. This seems to have fixed the issue for me.

Thanks MM support.

**Comment by jorijnsmit** [comment]
Encountering this too. Indeed with advanced gas controls turned on. Fix for me is to add a zero at the end of the estimate, to make sure it never runs out.

Still shouldn't MetaMask be able to make a proper estimate though? Why is it consistently too low?

**Comment by flipdazed** [comment]
I don't feel this issue should be closed - it is a clear bug

**Comment by keyringcore** [comment]
MetaMask generally estimates gas correctly when interacting with contracts. ERC20 is always a contract. When MM detects that the contract to interact with is a token, and the function is `.transfer()`,  it arbitrarily imposes a 100K gas _assumption_. That creates a bug when interacting with any token contract that applies minimal logic on top of the transfer itself. 

Expected behaviour:

- correctly estimate gas (150K???)
- transaction success

Observed behaviour:

- arbitrary gasLimit, 100K
- out-of-gas error, transaction failure
- consumes user's gas money

Workaround:

Users can manually raise the gas limit. This is an unreasonable ask for most users. We know of no reason why `token.transfer()` contract interactions should be treated differently from other contract interactions when estimating gas.

**Comment by keyringcore** [comment]
Unless I missed something, the examples above are less than 100K gas. 100K is where the problems start owing to the arbitrary figure that is hard-coded in MetaMask. 

Selection bias may be a factor here since popular production tokens are unlikely to exist if their contracts do anything complicated on any path through the `transfer()` function. How can a token be popular if the transfers often fail? 

Bear in mind that this limitation applies to the worse-case path through the transfer function, so contracts that branch can have typical transactions that are very efficient while occasionally having expensive transfers. Those fail if the wallet happens to be MetaMask. This leaves the project sponsor forced to advise users to switch to another wallet or fiddle with advanced manual controls.

Could someone from MetaMask share the rationale for the design decision? I need help seeing why standard contract gas estimation logic does not apply equally to ERC20.transfer(). The 100K magic number is a surprise limitation. I have no idea why it's necessary.
