### ISSUE TITLE
Hex Data field error

### ISSUE THREAD

**Issue by Wetitpig** [MetaMask/metamask-extension#7714]
**Describe the bug**
The hex data filled in box was missing in transaction

**To Reproduce**
1. Go to any token
2. Click on 'Send'
3. Type some hex data
4. Click confirm
5. See! There is no hex data. It is just a normal transfer.

**Expected behavior**
Hex Data will be included.

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - MetaMask Version: 7.7.1

**Additional context**
I was originally conducting a swap function, but then metamask changed it to a transfer function by itself. I was not aware of it and lost some coins.

**Comment by Gudahtt** [comment]
@Wetitpig Thanks for the report!

Are you still experiencing this problem? Can you help us try to reproduce this? (e.g. a code snippet of the specific call made would be helpful).

**Comment by tmashuang** [comment]
Is this an attempt to override the data for a token transfer? This seems like a security flaw, if a user decides to send a token then the transaction data should be the transfer params such as the `to` address and the `value`. Appending anything else to it would be out of spec and lead to more user confusion. If you have specific use case then please share and even create a new EIP for it. 

Dapps can propose a transaction with the proposed data, and from within MetaMask sending a normal tx with the intended hex data will decode the transaction and attempt to decode the transaction method else it will consider it a contract interaction.
