### ISSUE TITLE
Unexpected behavior of MetaMask during transactions.

### ISSUE THREAD

**Issue by AemieJ** [MetaMask/metamask-extension#7715]
**Describe the bug**
For my personal block-chain project, I have implemented transfer as well as buy tokens function and conducted unit tests for the same and it passed. However, when I connected the contracts with the client-side using web3.js and MetaMask and I tried to buy Tokens it resulted in unexpected RPC Error and I had to uninstall and reinstall the extension ( based on a solution on StackExchange ) . 

After configuring MetaMask to link with ganache and localhost , it went completely blank so I performed the uninstall and reinstall steps and performed unit tests  on my contracts all over again. 
After about 20 minutes, it started working .

**Expected behavior**
I expect that MetaMask to work efficiently without the need to continuously uninstall , reinstall and configure its settings to make my block-chain transactions work with the client-side.

**Browser details (please complete the following information):**
 - OS: [Fedora 31]
 - Browser [Chromei]
 - MetaMask Version [7.7.1]

**Comment by bdresser** [comment]
@AemieJ sounds like you're reporting two separate issues. Can you provide specific reproduction steps for each? cc @tmashuang

**Comment by AemieJ** [comment]
I am not providing two separate issues, I am just specifying the fact that metamask tends to crash and doesn't work efficiently and I hope changes are made so such issues of crashing doesn't occur.

**Comment by tmashuang** [comment]
I am going to close this stale issue. The description has vague details that suggest there is an issue. Without knowing the Ganache version/setup, contract code, and the error codes this issue cannot be reproduced easily.
