### ISSUE TITLE
Add "balanceChanged" event

### ISSUE THREAD

**Issue by prographo** [MetaMask/metamask-extension#7717]
Following the convention of **.on( eventname, callback )** as described here: https://metamask.github.io/metamask-docs/Advanced_Concepts/Provider_API#ethereum.on(eventname%2C-callback)

Would it be reasonable to add a **balanceChanged** event?

**Comment by Gudahtt** [comment]
Thanks for the suggestion!

Our provider implements the EIP-1193 specification, and we would generally like to avoid adding anything further unless some attempt at standardization has been made. As useful as this sounds, we don't want to add this and risk incompatibilities with other wallets.

If you'd like to pursue this idea further, I'd suggest making a topic to discuss it on https://ethereum-magicians.org, and/or writing an EIP describing this event and its purpose. Once a draft EIP has been written, we can reconsider this idea. Thanks!
