### ISSUE TITLE
Possible Vault Corruption - Password not changed

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/metamask-extension#7720]
User has reported after they reinstalled MetaMask on Firefox and restoring with seed phrase their old password in the previous installation was still active occasionally and the password access between the old and new would alternate randomly. 

OS: Windows 10 Pro version 1809 OS build 17763.914
Browser: FF v 71.0 64 bit
Metamask: Version 7.7.1 (updated dec 11)

**Comment by tmashuang** [comment]
I'm going to close this old issue. We do not have actual reproduction steps, state logs, vault data, and both passwords of the vault in question. I've tried numerous times to reproduce this to no avail.
