### ISSUE TITLE
eip: 1024 Add web3.eth.encrypt and web3.eth.decrypt functions

### ISSUE THREAD

**Issue by snissn** [MetaMask/metamask-extension#7721]
**What problem are you trying to solve?**

https://ethereum-magicians.org/t/eip-1024-cross-client-encrypt-decrypt/505

This EIP proposes a cross-client method for requesting encryption/decryption. This method will include a version parameter, so that different encryption methods can be added under the same name. Nacl is a cryptographically complete and well audited library that works well for this by implementers are free to choose their crypto. Ethereum keypairs should not be used directly for encryption, instead we should derive an encryption keypair from the account’s private key for decryption and generate a random ephemeral keypair for encryption.

**Describe the solution you'd like**
follow the eip1024 spec

> Parity wallet has already implemented a compatible encryption/decryption method. The Metamask version will be published soon.

I'd like to know if there's any progress made on the EIP and if not if there's support/desire for it

**Additional context**
I'm trying to build a decentralized chat app that can encrypt and decrypt messages to users and the only solutions available require having the private key exposed to javascript

**Comment by tmashuang** [comment]
Seems the author of the EIP has abandoned that particular EIP, look into [eth_getEncryptionPublicKey](https://docs.metamask.io/guide/rpc-api.html#eth-getencryptionpublickey) as an alternative.

**Comment by Gudahtt** [comment]
Encryption was implemented in #7831; see our documentation for more details: https://docs.metamask.io/guide/rpc-api.html#eth-getencryptionpublickey

I'm going to assume this satisfies your request, and close this issue. Please make a new issue if you feel there is some further improvement needed. Thanks!
