### ISSUE TITLE
Add option to disable Sai/Dai upgrade reminder

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#7724]
ref: #7411

I'm sure there are many people who still have some Sai either as accidental dust or intentionally. The fact that you can't get rid of that message is highly annoying. I propose  adding an option to disable it.

**Comment by bdresser** [comment]
We chose to leave the message persistent – we'll face a massive support burden if (when) the migration period is over and users have lost their Dai/Sai. Sorry for the trouble in the meantime. 

Out of curiosity is there a reason you aren't/haven't yet migrated?

**Comment by leafcutterant** [comment]
> we'll face a massive support burden if (when) the migration period is over and users have lost their Dai/Sai.

This doesn't conflict with adding e.g. a hidden key shortcut or an about:config entry.

I don't like it when my wallet tells me what tokens to hold, but detest that I can't make it shut up. If you want to foster a responsible and knowledgeable culture, give people the freedom to make their own decisions.

**Comment by leafcutterant** [comment]
The migration bridge has been turned off in the upgrade direction. So MM should rather remind people to exchange their Sai for Dai on DEXes (especially since Sai will be shut down on May 12).

But for heaven's sake, make that reminder disablable in the Settings.

**Comment by Gudahtt** [comment]
This notification was removed completely in #8418
