### ISSUE TITLE
Multiple windows, same account.

### ISSUE THREAD

**Issue by prographo** [MetaMask/metamask-extension#7736]
Support question.

If multiple Chrome windows are open, the wallet acts across all of them. for example if I have 2 windows and change the account in one window, it will change the account in the other window. This is different to something like a wss connection, which would maintain a separate connection for each window.

I am not saying this is wrong behaviour, I am just asking if it intentional and if you will keep it like this? thx.

**Comment by jennypollack** [comment]
please email support@metamask.io with a reference to this issue for further assistance

**Comment by prographo** [comment]
Already did it, they told me to ask here.

**Comment by jennypollack** [comment]
Ah ok, sorry about the miscommunication.

Yes, this behavior is expected, for the account to be the same across your Chrome windows. 

The way that dapps can access accounts is changing, so depending on which site you are on, you could be connected with a different account across multiple sites though.
