### ISSUE TITLE
Typing "enter" on seed restore screen does not submit the new seed

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7737]
This is a very small usability nit:

The restore from seed screen has a seed field, then two password fields, and after entering both by tabbing between fields, pressing "Enter" does not advance to the next screen.

I think MetaMask should strive to be keyboard-friendly when possible, so accepting Enter would be nice here.

**Comment by rickycodes** [comment]
I stepped through this process (keyboard only) and it seemed fine to me? once the two password fields are filled you can tab to the "I have read and agree to the Terms of Use" and hit space (or enter) to tick the checkbox after which hitting tab twice more will focus the import button and hitting enter a final time will submit the form.

**Comment by danfinlay** [comment]
I see some commits after the non-repro? Does that mean you found what I meant, or did I just miss the checkbox?

**Comment by rickycodes** [comment]
I found what you meant... we were not leveraging `type=submit` for the import button in the `<form>` (but we are now)
