### ISSUE TITLE
Blacklist popular (non-web3) websites for LoginPerSite

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-extension#7759]
**What problem are you trying to solve?**
During ux-related discussions regarding loginpersite, we've established that it would beneficial to detect whether a website is a dapp or not to avoid running into showing "Connect to [Facebook.com]?" for example. @whymarrh has done a fair amount of research and unfortunately has determined that it's not technically possible to detect web3 sites in MM.

**Describe the solution you'd like**
As a possible workaround, I suggest we blacklist list the most popular non-dapp websites on the web today (e.g. facebook, twitter, amazon, etc) in order to not show a "Connect to [domain]" notification for those sites.

**Comment by Gudahtt** [comment]
The permission system designs have changed since this was raised; we no longer suggest that the user connect to the active tab. I'm going to close this as I don't think it's relevant anymore to the current designs.
