### ISSUE TITLE
after restore from seed phrase : all token missing / 0 , except ETH - showing wrong addresses !

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-extension#7771]
System 1:
Manjaro / Arch Linux
Chromium Version 79.0.3945.88 (Official Build) Arch Linux (64-bit)
MetaMask 7.7.1
Kovan network
funds in ETH, WETH, ZRX, FEO1 (custom token)

System 2:
Ubuntu 18.04 (VM)
Chromium Version 79.0.3945.79 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
MetaMask 7.7.1
Kovan network

1) re-installed MetaMask with seed phrase from System 1 
2) ETH funds are showing up
3) **WETH, ZRX missing , showing 0 after adding with 'add token'**
4) FEO1 (custom token) shows funds after 'add token'

https://kovan.etherscan.io/address/0xa31f3d5d0d8a412084a3f83d253340524f7f8897

see screenshot : 
System 1 with existing MetaMask (and all funds showing) : lower screen
System 2 with fresh install seed phrase (missing WETH, ZRX) : upper screen

![Screenshot from 2020-01-09 15-31-44](https://user-images.githubusercontent.com/25609/72038852-fa3f0880-32f6-11ea-8496-4f1ae0499171.png)

**Comment by SvenMeyer** [comment]
If I choose "show on Etherscan" for ZRX in the original (working) MetaMask wallet, this address will be shown (which us the ZRX contract address):
https://kovan.etherscan.io/address/0x2002d3812f58e35f0ea1ffbf80a75a38c32175fa

If I choose "show on Etherscan" for ZRX (which I added manually via "add token") in the MetaMask wallet restored from the seed phrase, this address will be shown (which appear to be some random address with funds I do not own):
https://kovan.etherscan.io/address/0xe41d2489571d322189246dafa5ebde1f4699f498

**Comment by danfinlay** [comment]
Could you try selecting "Main Ethereum Network" in the top menu in MetaMask? When Kovan is selected, only Kovan assets are currently shown.

**Comment by SvenMeyer** [comment]
I developed using Kovan net and of course expected the Kovan token to show up. I do not have any real mainnet token/ETH in that wallet.

**Comment by jennypollack** [comment]
please email support@metamask.io with a reference to this issue for further assistance
