### ISSUE TITLE
Your Add Token "app" referenced here is broken.  

### ISSUE THREAD

**Issue by eepstein** [MetaMask/metamask-extension#7773]
While it works to generate a seemingly functioning web page, the page is in fact non-sharable.  One cannot use it in the intended way at all.

**Comment by jennypollack** [comment]
hey @eepstein are you referring to this app?
https://metamask.github.io/Add-Token

**Comment by eepstein** [comment]
Yes, that one.

**Comment by eepstein** [comment]
Yes. 
Any word on this?

**Comment by Gudahtt** [comment]
Thanks for the report @eepstein ! Unfortunately this is the wrong place to report this problem - please create an issue here if you're still having trouble: https://github.com/MetaMask/Add-Token/issues

I was going to migrate this issue myself, but I wasn't sure what you meant by "non-sharable", so I wasn't sure how to describe the problem. I'll close this in the meantime.
