### ISSUE TITLE
Confirming a transaction from moz-extension://.../notification.html closes the entire browser window

### ISSUE THREAD

**Issue by JesseBusman** [MetaMask/metamask-extension#7789]
**Describe the bug**
When you have moz-extension://.../notification.html open in a Firefox browser tab, and you Confirm a transaction, the entire browser window is closed, including all other (non-Metamask) tabs.

**Steps to reproduce**

1. Click the Metamask icon
2. Click the ... symbol
3. Click Expand View
4. In the URL bar, change home.html to notification.html and press Enter
5. Click Send
6. Enter any recipient
7. Enter any transaction amount/data
8. Click Next
9. Click Confirm.

Now the entire browser window closes, including other tabs that you had open in the same window as the Metamask notification.html tab.

**Expected behavior**
There are several possible expected behaviours:

1. No browser tabs or browser windows should close. The Metamask tab should return to /home.html or /notification.html
2. Only the Metamask notification.html tab should close
3. The option to Send from notification.html should not exist
I prefer number 1.

**Browser details**
 - OS: Windows 10
 - Browser: Firefox 72.0 (64-bit)
 - MetaMask Version: 7.7.1

**Comment by Gudahtt** [comment]
`notification.html` is meant for our confirmation popups; the assumption is that these windows are temporary and not used for anything else. They don't even have an address bar. How did you end up with `notification.html` opened in a regular browser window? :thinking:

Your first suggestion is a non-starter for us because we can't leave small popup windows around after each request. That wouldn't be user friendly at all. We can look into some way to close the tab instead of the entire window though - that's a good idea.

**Comment by JesseBusman** [comment]
In suggestion 1 I was not referring to the popups, just the regular browser tabs.

Unfortunately I don't remember how I ended up with the notification.html tab. IIRC, if you were at notification.html, you got the same screen as home.html. You could do normal things like switch accounts and send a transaction. This no longer seems to be the case, if you browse to notification.html now the entire window closes immediately.

The problem might not be possible without URL editing anymore, but for robustness it would probably still be good if notification.html checks for other tabs before closing its window.

**Comment by Gudahtt** [comment]
Thanks! That makes sense. I do recall that `notification.html` used to work like that - I don't think it was ever intentional though, so we made some routing changes recently to try to prevent that.

>for robustness it would probably still be good if notification.html checks for other tabs before closing its window.
:100:
