### ISSUE TITLE
Uyum yok  

### ISSUE THREAD

**Issue by eymenabdulsamed** [MetaMask/metamask-extension#7793]
Uyumadım sag hy 

**Describe the bug**

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by eymenabdulsamed** [comment]
Uyum yok(turkish) why

9 Oca 2020 Per 22:32 tarihinde Whymarrh Whitby <notifications@github.com>
şunu yazdı:

**Comment by whymarrh** [comment]
Hi @eymenabdulsamed, this issue isn't clear nor is it formatted correctly. Please open up a new issue.
