### ISSUE TITLE
"Confirm your Secret Backup Phrase" should be sorted.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#7799]
Originally posted over at 
Migrated from https://github.com/brave/brave-browser/issues/7630, which indicated this was actually a MetaMask bug as they just run a MetaMask fork.

## Description 
When creating a new Brave Wallet, it gives me a seed phrase to note and then asks me to confirm it by selecting words from a list in the order they appeared in the seed phrase.  The problem is the list of words is unordered, so when I try to find the next word in my seed phrase I have to painstakingly search the word list one word at a time.  The list should be sorted in alphabetical order so it is easy to find the next word via a mental binary search (the way humans naturally try to search sorted lists).

## Steps to Reproduce
   1. Settings > Crypto Wallets > New Wallet
   2. Write down seed.
   3. Try to confirm.

## Actual result:
Pain and suffering that make me want to not use the feature.

## Expected result:
Delight at using modern financial technology.

## Reproduces how often: 
100%.

## Brave version (brave://version info)
Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1903 (Build 18362.535)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the dev channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

**Comment by briancfalls** [comment]
I cannot back up my wallet at all I am only able to click on the top 4 seed words at the bottom of the page and am unable to scroll down to see the rest of them. Now today most likely because of that problem weeks old, my Brave Browser now says, Uh oh. Your wallet is unreachable.
No worries. This can happen for a variety of security reasons. Reconnecting your wallet will solve this issue. But I cannot back it up.

**Comment by ryanml** [comment]
Hi @briancfalls, I'm a Brave engineer.

Though it is highly encouraged, you actually do not have to confirm the seed phrase when making a crypto wallet, you can skip this step. As for not being able to scroll down, this sounds like something we can improve on our end for smaller viewports. You can `ctrl -` to zoom out and you should be able to see all the words/submit button.

As for the message you're seeing, that is something in Brave Rewards which is entirely separate from the Crypto Wallets feature. If you're not able to reconnect your wallet I encourage you to make a post over at https://community.brave.com/c/brave-rewards
