### ISSUE TITLE
i18n german Label add-token tab = "Custom-Tohen"

### ISSUE THREAD

**Issue by JhonnyJason** [MetaMask/metamask-extension#7804]
**Describe the bug**
Typo in Label "Custom-Tohen" instead of "Custom-Token"

**To Reproduce (REQUIRED)**
- Version 7.7.1 German localization
- Menü -> Token hinzufügen

Cheers!

**Comment by whymarrh** [comment]
@JhonnyJason would you be willing to update the file directly? You should be able to edit it here on GitHub. No worries if not, I will fix this up then.

**Comment by JhonnyJason** [comment]
#7808

**Comment by whymarrh** [comment]
Thanks @JhonnyJason!

**Comment by igigamer** [comment]
hey i still have the same issue.

Browser:Brave Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
Metamask Version: 7.7.8

**Comment by whymarrh** [comment]
This will be added to 7.7.9, slated for release early this week. Thanks for the reminder @igigamer.

**Comment by igigamer** [comment]
Awesome :)
