### ISSUE TITLE
Transaction is not confirmed, metamask shows as 'processing' but nothing happens. Ledger or Metamask issue?

### ISSUE THREAD

**Issue by avalyn2** [MetaMask/metamask-extension#7809]
Trying to withdraw money from https://app.pooltogether.com/ to my wallet

I am using a Ledger Nano S 1.6.0 together with metamask to do this.

**To Reproduce**

1) went to app.pooltogether.com/ and witthdrew money
2) got a message in the website 'Please confirm the transaction in your wallet'
3) clicked confirm in 'metamask' (at no moment got any message in Ledger to confirm transaction)
4) metamask shows as processing (see image below). tried this already 3 times.

**Expected behavior**

Transaction should be confirmed shortly after I click 'confirm' in metamask. But shouldn't I get a message to confirm in Ledger Nano S too?

**Screenshots**

![image](https://user-images.githubusercontent.com/32930476/72219030-dde2dc00-3541-11ea-9f55-270ff9521fec.png)

Three attempts approved but not confirmed. I am going to lose gas x 3?

![image](https://user-images.githubusercontent.com/32930476/72219079-45009080-3542-11ea-8e5b-ca01c0ef9094.png)

**Browser details (please complete the following information):**

 - OS: Windows
 - Hardware Wallet: Ledger Nano S 1.6.1
 - Browser: Version 79.0.3945.117 (Official Build) (64-bit)
 - MetaMask Version 7.7.1

**Comment by avalyn2** [comment]
Following https://github.com/MetaMask/metamask-extension/issues/5757#issuecomment-532941266 solved the problem, this seems however a big issue for non tech-users.

In a nutshell: you MUST ensure your Ledger Nano S is plugged and the 'Ethereum' app selected in your device BEFORE even connecting the DApp with Metamask to avoid the above issue.

**Comment by tbenr** [comment]
i run into this problem, i had to close the browser and run the app and select account BEFORE connect the dapp do the current account (as stated by @avalyn2). there is definitely room for improvement here (at least a message from metamask after a while, instead an infinite spinning gear)

**Comment by Gudahtt** [comment]
Thanks for the feedback! I'm going to close this issue because we're already tracking improvements to this UX in #10133. Please follow that issue for further updates.
