### ISSUE TITLE
Find and restore accounts with any tokens or ETH and display that info to the user

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#7811]
**What problem are you trying to solve?**
MetaMask currently only restores wallets automatically if there is an ETH balance.  Many users have accounts with 0 ETH but with tokens in them.  

**Describe the solution you'd like**
When restoring a seed phrase, scan for accounts with ETH or Tokens (nfts too, basically any activity).  Then present a screen stating "Congrats, you've imported your seed successfully, we've found 5 accounts with activity in them...) Automatically have every account check marked, but give the user the ability to uncheck.  Provide the ability to create an additional account on the same screen too.

Auto-add all the tokens found, even if custom.  Maybe pulling from a 3rd party source with a larger repository for this (maybe coingecko, etherscan, or mycrypto).

**Additional context**
Users often submit tickets stating they restored their seed phrase but do not see the account or tokens they are expecting.  The goal would be to make the process as automated and simple as possible.

**Comment by jennypollack** [comment]
discussed this in today's support call
If there’s an eth balance, it should show up in the dropdown menu, but once we see one account with a balance of zero, we stop looking 

more investigation on what the threshold of the lowest eth balance we show is
