### ISSUE TITLE
Can't scroll to bottom of licence agreement - Raspberry Pi

### ISSUE THREAD

**Issue by haiqu** [MetaMask/metamask-extension#782]
Tried to add MetaMask to a Raspi 3 today but I can't enable it because the Licence agrement text box is too large. Consequently scrolling to the bottom is impossible.

![meta](https://cloud.githubusercontent.com/assets/13131219/19819194/e879bd32-9d96-11e6-94e3-00e703d5c0d2.png)

**Comment by flyswatter** [comment]
You find the most unique bugs!

A temporary workaround (don't ask me how I know this! pain!):

1. Right click on the popup, and inspect it.
2. In the popup console, type `window.location.href` to log out the popup's html location.
3. Paste that location into the main browser bar and hit enter.
4. Once you've loaded the popup in a normal tab, you can zoom in and out (using ctrl-`-` and ctrl-`+`).
5. Zoom out to a point that you can see the whole popup on screen.
6. Your popup will now be the same size (Chromium zoom config is per-domain).

**Comment by flyswatter** [comment]
Long term solution options:

- When opening popup, ensure it's never larger than the screen's available height.
- Automatically scale down UI?
- Make whole UI more responsive?

**Comment by haiqu** [comment]
I got around it (barely) by going full-screen and setting the toolbar to vanish unless the mouse was over it. Exacerbated by being on a 1024x768 laptop which, I suppose, is pretty lame these days.

Glad to keep you amused. :)

**Comment by tmashuang** [comment]
>https://productforums.google.com/forum/#!topic/chrome/tyzywUJfkQI
>Found a resolution for a monitor with a different text size other than 100%.
>Yes! Disabling chrome://flags/#enable-use-zoom-for-dsf "Use Blink's zoom for device scale factor" fixes the mouse offset issue for me on latest Chrome (63.0.3239.108).
