### ISSUE TITLE
Breaking Changes to the MetaMask Inpage Provider

### ISSUE THREAD

**Issue by clementbalestrat** [MetaMask/metamask-extension#7839]
According to the [Medium post](https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a), the update was planned for 13th Jan but it now has changed to Q1.

Any news on this?

Also when will you guys provide a build with all the deprecated features removed?

**Comment by rekmarks** [comment]
Hi @clementbalestrat, we're currently working on the deprecation release (without features removed). We'll announce when we have a build for that ready. Once we've rolled out the deprecation release, we'll post a build with the deprecated features removed, and it will be 6 weeks until that's rolled out.

I'll keep this issue open to post updates as we go along.

**Comment by rekmarks** [comment]
See #8077
