### ISSUE TITLE
Transaction sent from wrong Ledger account

### ISSUE THREAD

**Issue by rene78** [MetaMask/metamask-extension#7845]
**Describe the bug**
I use two ETH accounts on my Ledger - account [1] and [2]. When submitting a contract or transfering ETH on the mainnet from account [2] via Metamask it still sends from [1].

**To Reproduce**
1. Click on 'Connect Hardware Wallet', select 'Ledger' and click 'connect'
2. Choose 'Ledger Live' as HDPath and select Ledger account [2] and click on 'Unlock'
2. Deploy contract on Remix/transfer ETH  with this account
3. Transaction history in Metamask shows 'From' address to be account [2], but in Etherscan it is obvious, that [1] has been used.

**Expected behavior**
Use selected account to send ETH.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Ledger Nano S, Firmware version 1.6.0
 - Chrome Version 79.0.3945.117 (Official Build) (64-bit)
 - MetaMask Version 7.7.2

**Comment by rene78** [comment]
This issue seems to be related: https://github.com/MetaMask/metamask-extension/issues/6165

**Comment by jennypollack** [comment]
This is fixed in [v7.7.7](https://github.com/MetaMask/metamask-extension/releases/tag/v7.7.7)
https://twitter.com/metamask_io/status/1235648375955107842
