### ISSUE TITLE
Connecting Ledger and Metamask

### ISSUE THREAD

**Issue by dinrot100** [MetaMask/metamask-extension#7846]
Hey,
I am using Chrome browser with Metamask Extension. 
Connected my ledger successfully and could see the ETH balance.

When trying to make transaction on Metamask it shows the following 

![image](https://user-images.githubusercontent.com/59958647/72517740-94a1cd80-385c-11ea-933f-ecf378402ff0.png).

While I do not get the option to sign on the Ledger.

Please help :)
Thanks
Din

**Comment by rene78** [comment]
If you are interacting with a contract make sure that "Contract Data" is activated on your Ledger. That's where I was struggling yesterday.

**Comment by jennypollack** [comment]
Please see our [hardware wallet connection guide](https://metamask.zendesk.com/hc/en-us/articles/360020394612-How-to-connect-a-Trezor-or-Ledger-Hardware-Wallet) for more assistance

and [this issue](https://github.com/MetaMask/metamask-extension/issues/8168) for tracking improvements to this documentation
