### ISSUE TITLE
Change terminology of "Login/Logout" to "Unlock/Lock"

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-extension#7852]
**Problem**

1. With Login Per Site functionality, we are building upon the users' behavior of logging into a site with an account. Right now we call it 'Connect', but with added permissions, an account will become more and more like a profile. For this, a clear distinction would be good between **unlocking** MetaMask (wallet) and **logging in** with web3 profiles (with accounts).

2. Consistency across apps and platform: 

- When MetaMask is locked, sites say 'Unlock your MetaMask' which leads the user to entering MM password. 

- On MM mobile, to get into MetaMask user **'unlocks'** with fingerprint or password.

**Solution**

1. Change terminology of MetaMask wallet Login/Logout to Unlock/Lock . 
2. Instead of 'Connected'/'Not connected' for accounts and site connection, use 'Logged in' / 'Logged out' to communicate to users this functionality as profiles.

@rekmarks What do you think about this change?
cc @rachelcope per our conversation

**Comment by rekmarks** [comment]
@omnat Thank you for documenting this. I've had this thought while working on LoginPerSite but never documented it. My recommendation is to implement it immediately.

For implementation reference, the affected messages appear to be:
- `login`
- `logout`
- `logoutTimeTooGreat`
- `autoLogoutTimeLimit`
- `autoLogoutTimeLimitDescription`

In addition, we should probably change `step3HardwareWalletMsg`, which currently reads:
>Use your hardware account like you would with any Ethereum account. Log in to dApps, send Eth, buy and store ERC20 tokens and Non-Fungible tokens like CryptoKitties.

Suggested change:
>Use your hardware account like you would with any Ethereum account. Connect to dApps, send ETH, buy and store ERC20 tokens and non-fungible tokens (NFTs) like CryptoKitties.

**Comment by rekmarks** [comment]
cc: @danjm @whymarrh @Gudahtt 

I can just charge ahead and do this for English, but how do we handle localization in situations like this?

**Comment by rekmarks** [comment]
I just noticed that there are two existing messages, `unlock` and `unlockMessage`.

`unlock` was created for Trezor support and is used in the `account-list` component. We can probably delete `login` and just use `unlock` instead.

 `unlockMessage` was created by two years ago and is used in the `unlock-page` component. That's funny; the "login" page shown when the extension is "logged out" uses the unlock language internally.

**Comment by Gudahtt** [comment]
Changing "Login/Logout" to "Unlock/Lock" seems like a great idea to me!

I'm less sure about changing 'Connected'/'Not connected' to 'Login/Logout' though 🤔 The term "Connected" does seem, at least from my perspective, somewhat well established already. Using "Login" for that action might also be misleading, as it doesn't exactly have the same connotations as logging in; it means the app can see the ethereum address, but it doesn't get access to a name, a profile, an avatar, or anything a user might typically expect aside from the identity itself.

We might want to reserve "Login" for a more full-featured login feature, which is certainly something we could build.

**Comment by rekmarks** [comment]
It appears I didn't read @omnat's post thoroughly last night, and I missed the suggestion about changing Connected/Not connected to Login/Logout. I want to second @Gudahtt's opinion, and advise _against_ that particular change.

It is _not_ necessarily the case that Ethereum accounts will become "will become more and more like a profile" due to the permissions system; that is still something we have to decide.

I still unreservedly support changing Login/Logout to Unlock/Lock.

**Comment by omnat** [comment]
Sounds good! I'm in agreement on not changing 'Connect' terminology for now, unless suggested differently from upcoming user tests for LoginPerSite.

This was an assumption I had, so I'm glad that it's clear now we haven't defined it yet. 
> It is not necessarily the case that Ethereum accounts will become "will become more and more like a profile" due to the permissions system; that is still something we have to decide.
