### ISSUE TITLE
Custom network explorer link not being used in tx conf notification

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7864]
Reported in [this tweet](https://twitter.com/emaringolo/status/1218286726017363972).

Need to make sure we're using the custom block explorer link generator for the notifications.

**Comment by Gudahtt** [comment]
Related to #5631

**Comment by BboyAkers** [comment]
@Gudahtt I'll dig into this as well 🙂

**Comment by Gudahtt** [comment]
This is related to this issue as well: #10041

Check out this draft EIP in particular: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3091.md - that should provide some guidance on how we can interact with custom block exporers.

**Comment by BboyAkers** [comment]
@Gudahtt Thanks a ton for the info!!!

**Comment by BboyAkers** [comment]
This PR will fix this 🙂 
https://github.com/MetaMask/etherscan-link/pull/31

**Comment by brad-decker** [comment]
@BboyAkers I had to touch this as well for switching to chainId MetaMask/etherscan-link#32 and #10587 -- As part of the extension side of the work I made sure we were at least getting the current network rpcUrls to the intermediary method on the extension for building blockExplorerUrls.

**Comment by danjm** [comment]
The remainder of work required on this issue can be seen by taking the following steps

1. On ropsten, send transaction
2. When the transaction is confirmed, the browser notification will appear. If clicked, you will be taken to ropsten etherscan.
3. Switch to a custom network that required you to enter a custom block explorer url
4. send a transaction
5. A browser notification will appear, but when clicked, nothing will happen

Instead, on the custom network, when the browser notification is clicked, the user should be taken to a notification page for the custom block explorer url.

**Comment by adonesky1** [comment]
> The remainder of work required on this issue can be seen by taking the following steps
> 
> 1. On ropsten, send transaction
> 2. When the transaction is confirmed, the browser notification will appear. If clicked, you will be taken to ropsten etherscan.
> 3. Switch to a custom network that required you to enter a custom block explorer url
> 4. send a transaction
> 5. A browser notification will appear, but when clicked, nothing will happen
> 
> Instead, on the custom network, when the browser notification is clicked, the user should be taken to a notification page for the custom block explorer url.

@danjm are there particular tokens/networks where you are able to reproduce this? I've tried with BSC and a few custom assets and wasn't seeing an issue. It looks to me like this may have been resolved by [Brads PR](https://github.com/MetaMask/metamask-extension/pull/10587)?

**Comment by brad-decker** [comment]
Yeah this was very likely already handled. relevant lines https://github.com/MetaMask/metamask-extension/pull/10587/files?file-filters%5B%5D=.js#diff-32c04cceec43c905d25f6f037e3c52ccfd7293c3eb17dcd7750ca3beece0be73R192-R195

**Comment by adonesky1** [comment]
I've confirmed on several custom networks with different assets that this doesn't appear to be an issue any longer so I'm going to close this.
