### ISSUE TITLE
Seed phrase imports wrong address

### ISSUE THREAD

**Issue by flood793** [MetaMask/metamask-extension#7866]
It's been some time since I've used metamask, and I'm on a different computer than before. When I entered my seed phrase, it imported a different wallet with no currency in it.
The wallet address it created is 0xF768bcb9fd79177f21684BD6982b3ec9a249bec0
My actual wallet however is 0xf797db96F6d2Fe099A117F0ec998554805adE4b5
Currency of my actual wallet can be seen here: https://etherscan.io/address/0xf797db96f6d2fe099a117f0ec998554805ade4b5#tokentxns

I've tried clicking the "create account" button a few times since I heard that might fix it, but none of them are my original address.

**Comment by flood793** [comment]
Is there any possible way for me to recover my currency without this bug being fixed?

**Comment by rdymac** [comment]
Hello @flood793, to be able to ask some details, can you please send an email to support@metamask.io ? Mention this issue number #7866

**Comment by anthlic** [comment]
I too am having the same problem. I can provide details if you like as well.

**Comment by danfinlay** [comment]
If anyone is having issues importing their account, they should email support @ metamask.io immediately. They will go through all available debugging steps.
