### ISSUE TITLE
develop: Multiple `enable()` calls should not initiate multiple login tabs

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7874]
If a dapp wrote bad code like this:
```javascript
ethereum.enable()
ethereum.enable()
```

It would initiate two login requests. Currently on `develop` this results in multiple new tabs, and if the user connects on one, they are correctly redirected to the site, leaving a tab open.

Those open tabs are not just memory leaks, but probably result in our background process polling for new blocks and token balances, too.

Instead, we should recognize when we have a pending login request and ignore repeated calls to `requestPermissions` until there are no pending requests from that domain.

**Comment by danfinlay** [comment]
Related: We _probably_ don't need to be persisting these permissions requests between restarts, since there will be no dapp to hear the reply when it happens.

**Comment by Gudahtt** [comment]
I believe this was fixed by #8148
