### ISSUE TITLE
Transactions aren't submitted using low/custom gas price

### ISSUE THREAD

**Issue by danielschonfeld** [MetaMask/metamask-extension#7883]
Expected: be able to interact with smart contracts by submitting the transaction

Actual: When setting a custom gas price, in particular 1 gwei, utilizing a hardware wallet (ledger) everything gives the appearance of the transaction having been submited, but in reality it does not.  

Browser: latest chrome/firefox
OS: OSX

Reproduce:
 1) interact with a smart contract (ie unlock an ERC-20 token on any defi website)
 2) choose a custom gas price utilizing a hardware backed account in MM
 3) hit 'confirm'
 4) sign on your hardware wallet
 5) observe how it shows the transaction in MM but not in etherscan

Edit: 
Possible workaround that seems to work:
1) Reset account
2) Remove account
3) Reconnect the hardware account

If you only reset without removing/adding, it doesn't work just as described above.

**Comment by MarkOSullivan94** [comment]
Having the same issue here except I'm just trying to send a token from my MetaMask wallet and not using a hardware wallet with MetaMask

For me I set the gas to 6 gwei and it immediately fails

Browser: Brave Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)
OS: MacOS 10.15.5
