### ISSUE TITLE
Can't connect to Opera mainnet using custom rpc

### ISSUE THREAD

**Issue by fxfrnk** [MetaMask/metamask-extension#7888]
**Describe the bug**
When trying to connect to the Opera mainnet (https://rpc.fantom.network) using custom rpc, the connection continues loading until it ultimately fails and prompts me to try again or switch networks. However, it is possible to connect using the MetaMask mobile beta app.

**To Reproduce (REQUIRED)**
Set up a new network with the settings in the screenshot and try to connect.

**Expected behavior**
MetaMask connects to the network and allows user to send transactions via the Opera mainnet

**Screenshots**
![image](https://user-images.githubusercontent.com/11490430/73001539-a3463280-3dd0-11ea-8c53-e0fedd1fc6fb.png)

**Browser details (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Brave 1.2.43 Chromium: 79.0.3945.130, Firefox 72.0.2
 - MetaMask Version 7.7.2

**Additional context (Error Messages, etc.)**
support reference 29293
network connection details: https://medium.com/@fantomglobal/ftm-opera-delegation-via-mew-c1d7a459d6fe

**Comment by snowkidind** [comment]
Not sure if it's related or not but I am trying to work on a dapp with metamask/opera and I get undefined when I try to access `window.ethereum` (metamask and opera are both latest versions)

I'm using a custom RPC served by ganache-cli, same code works fine in chrome

**Comment by tmashuang** [comment]
They seem to fail the `net_version` call that we are making to get the network id. 
```
curl 'https://rpc.fantom.network/' -H 'authority: rpc.fantom.network' -H 'accept: application/json' -H 'content-type: application/json' --data-binary '{"id":6541698100192939,"jsonrpc":"2.0","method":"net_version","params":[]}' --compressed
```

Which results in 
```
{"jsonrpc":"2.0","id":6541698100192939,"error":{"code":-32601,"message":"the method net_version does not exist/is not available"}}

```

**Comment by tmashuang** [comment]
Testing this on the latest MM v8.1.4. Ubuntu 20.04 Chrome Version 86.0.4240.198 works on connecting to this custom rpc.
