### ISSUE TITLE
Cannot call balanceOf function from ERC20 contract

### ISSUE THREAD

**Issue by hbarcelos** [MetaMask/metamask-extension#7892]
**Describe the bug**
I am connecting to my contract using the metamask provider using this function:

```js
export const ethFactory = networkId => {
  if (typeof window.ethereum !== 'undefined' || typeof window.web3 !== 'undefined') {
    return new Eth(window.ethereum || window.web3.currentProvider);
  } else {
    return new Eth(
      Eth.givenProvider || `http://${getNetworkName(networkId)}.infura.io/v3/${process.env.INFURA_API_KEY}`
    );
  }
};
```

My contract is deployed at `0xfb0e30f97c656b5be9d92879fbcec5a35195e346` on Rinkeby..

It has a standard ERC20/ERC223 interface:
<details>
<summary>ABI</summary>
<pre>
<code>
[
      {
        "inputs": [
          { "internalType": "string", "name": "name", "type": "string" },
          { "internalType": "string", "name": "symbol", "type": "string" },
          { "internalType": "uint8", "name": "decimals", "type": "uint8" },
          { "internalType": "uint256", "name": "totalSupply", "type": "uint256" }
        ],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "constructor"
      },
      {
        "anonymous": false,
        "inputs": [{ "indexed": true, "internalType": "address", "name": "account", "type": "address" }],
        "name": "AdminAdded",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [{ "indexed": true, "internalType": "address", "name": "account", "type": "address" }],
        "name": "AdminRemoved",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [
          { "indexed": true, "internalType": "address", "name": "owner", "type": "address" },
          { "indexed": true, "internalType": "address", "name": "spender", "type": "address" },
          { "indexed": false, "internalType": "uint256", "name": "value", "type": "uint256" }
        ],
        "name": "Approval",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [
          { "indexed": true, "internalType": "address", "name": "burner", "type": "address" },
          { "indexed": true, "internalType": "address", "name": "account", "type": "address" },
          { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" }
        ],
        "name": "Burn",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [{ "indexed": true, "internalType": "address", "name": "_account", "type": "address" }],
        "name": "BurnerAdded",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [{ "indexed": true, "internalType": "address", "name": "_account", "type": "address" }],
        "name": "BurnerRemoved",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [
          { "indexed": true, "internalType": "address", "name": "minter", "type": "address" },
          { "indexed": true, "internalType": "address", "name": "account", "type": "address" },
          { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" }
        ],
        "name": "Mint",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [{ "indexed": true, "internalType": "address", "name": "_account", "type": "address" }],
        "name": "MinterAdded",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [{ "indexed": true, "internalType": "address", "name": "_account", "type": "address" }],
        "name": "MinterRemoved",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [{ "indexed": false, "internalType": "address", "name": "account", "type": "address" }],
        "name": "Paused",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [
          { "indexed": true, "internalType": "address", "name": "from", "type": "address" },
          { "indexed": true, "internalType": "address", "name": "to", "type": "address" },
          { "indexed": false, "internalType": "uint256", "name": "value", "type": "uint256" },
          { "indexed": true, "internalType": "bytes", "name": "data", "type": "bytes" }
        ],
        "name": "Transfer",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [
          { "indexed": true, "internalType": "address", "name": "from", "type": "address" },
          { "indexed": true, "internalType": "address", "name": "to", "type": "address" },
          { "indexed": false, "internalType": "uint256", "name": "value", "type": "uint256" }
        ],
        "name": "Transfer",
        "type": "event"
      },
      {
        "anonymous": false,
        "inputs": [{ "indexed": false, "internalType": "address", "name": "account", "type": "address" }],
        "name": "Unpaused",
        "type": "event"
      },
      {
        "constant": false,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "addAdmin",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "addBurner",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "addMinter",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "admins",
        "outputs": [{ "internalType": "address[]", "name": "", "type": "address[]" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "burners",
        "outputs": [{ "internalType": "address[]", "name": "", "type": "address[]" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "isAdmin",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "isBurner",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "isMinter",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "isOwner",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "minters",
        "outputs": [{ "internalType": "address[]", "name": "", "type": "address[]" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "owner",
        "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [],
        "name": "pause",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "paused",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "removeAdmin",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "removeBurner",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [{ "internalType": "address", "name": "_account", "type": "address" }],
        "name": "removeMinter",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [],
        "name": "unpause",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "name",
        "outputs": [{ "internalType": "string", "name": "", "type": "string" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "symbol",
        "outputs": [{ "internalType": "string", "name": "", "type": "string" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "decimals",
        "outputs": [{ "internalType": "uint8", "name": "", "type": "uint8" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [],
        "name": "totalSupply",
        "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [{ "internalType": "address", "name": "_owner", "type": "address" }],
        "name": "balanceOf",
        "outputs": [{ "internalType": "uint256", "name": "balance", "type": "uint256" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [
          { "internalType": "address", "name": "_spender", "type": "address" },
          { "internalType": "uint256", "name": "_value", "type": "uint256" }
        ],
        "name": "approve",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [
          { "internalType": "address", "name": "_from", "type": "address" },
          { "internalType": "address", "name": "_to", "type": "address" },
          { "internalType": "uint256", "name": "_value", "type": "uint256" }
        ],
        "name": "transferFrom",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": true,
        "inputs": [
          { "internalType": "address", "name": "_owner", "type": "address" },
          { "internalType": "address", "name": "_spender", "type": "address" }
        ],
        "name": "allowance",
        "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [
          { "internalType": "address", "name": "_spender", "type": "address" },
          { "internalType": "uint256", "name": "_addedValue", "type": "uint256" }
        ],
        "name": "increaseApproval",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [
          { "internalType": "address", "name": "_spender", "type": "address" },
          { "internalType": "uint256", "name": "_subtractedValue", "type": "uint256" }
        ],
        "name": "decreaseApproval",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [
          { "internalType": "address", "name": "_to", "type": "address" },
          { "internalType": "uint256", "name": "_value", "type": "uint256" }
        ],
        "name": "transfer",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [
          { "internalType": "address", "name": "_to", "type": "address" },
          { "internalType": "uint256", "name": "_value", "type": "uint256" },
          { "internalType": "bytes", "name": "_data", "type": "bytes" }
        ],
        "name": "transfer",
        "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [
          { "internalType": "address", "name": "_to", "type": "address" },
          { "internalType": "uint256", "name": "_amount", "type": "uint256" }
        ],
        "name": "mintTo",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      },
      {
        "constant": false,
        "inputs": [
          { "internalType": "address", "name": "_from", "type": "address" },
          { "internalType": "uint256", "name": "_amount", "type": "uint256" }
        ],
        "name": "burnFrom",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
      }
    ]
</code>
</pre>
</details>

To create an instance of the contract, I do as follows:

```js
const contract = new eth.Contract(abi, address);
```

**To Reproduce**

Dependencies:
-  `web3-eth`: `1.2.4`

Code:
```js
const contract = new eth.Contract(abi, address);

contract.methods
    .balanceOf('0x17cA6A08758F4A078B9c53ca25E6F6736dF34094')
    .call()
    .then(console.log)
    .catch(console.error);
```

This gives me an error:
> Error: "Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced."

**Expected behavior**
I would get the balance of the given address.

**Screenshots**
![error](https://user-images.githubusercontent.com/16565602/73081632-bcb9ae00-3ea6-11ea-8ee8-cb2027a311c7.png)

**Browser details (please complete the following information):**
 - OS: Manjaro Linux
 - Hardware Wallet: None
 - Browser: Firefox 72.0
 - MetaMask Version: 7.7.2

**Additional context**
**IMPORTANT:** if I switch to the Infura provider, the  code above works as expected.

**Comment by jennypollack** [comment]
Hey @hbarcelos are you still experiencing this issue?

**Comment by kumavis** [comment]
closing for lack of response
