### ISSUE TITLE
Allow selecting multiple accounts in Connect flow

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#7917]
**What problem are you trying to solve?**
Currently the "Connect" screen used when connecting MetaMask to a website only allows the user to select a single account. We would like the user to be able to select multiple or all accounts during the connect flow as well.

**Describe the solution you'd like**
Implement the designs described in https://github.com/metamask/design/issues/166 ([Figma](https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=378%3A4527))

**Comment by brad-decker** [comment]
@Gudahtt believe this one is resolved. Closed but feel free to reopen.

**Comment by Gudahtt** [comment]
Yes, this is definitely done,. Thanks!
