### ISSUE TITLE
Out of gas errors on DAI transfers with default limit. 

### ISSUE THREAD

**Issue by TomAFrench** [MetaMask/metamask-extension#7941]
**Describe the bug**

I've recently when trying to send DAI to an address had transactions fail due to "out of gas" errors. The default gas limit seems to be too low.

I had to try three times to get the transaction to go through:
1. Gas limit: 42801 FAILED
2. Gas limit: 50000 FAILED
3. Gas limit: 70000 succeeded with only ~38000 gas used.

As the final transaction would have succeeded with the lower gas limits I expect this issue to only appear intermittently in testing.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Attempt to send DAI
2. Observe suggested gas limit (42801)
3. Confirm transaction and wait.
4. Observe transaction failure.

**Expected behavior**

I expect that the default gas limit should be guaranteed to succeed on a simple transfer.

**Browser details (please complete the following information):**
 - OS: Linux
 - Hardware Wallet: N/A
 - Browser: Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit) ( I'm not using the built-in wallet)
 - MetaMask Version: 7.7.2

**Comment by TomAFrench** [comment]
This issue has also been experienced by @WyseNynja who posted in #7753

**Comment by jennypollack** [comment]
also reported in #8136

**Comment by dpazdan** [comment]
reference support tickets tagged with: gas_limit_incorrect_suggestion

**Comment by jennypollack** [comment]
@TomAFrench was this using the amount: max?

**Comment by TomAFrench** [comment]
@jennypollack, I think it might have been. I doubt I used the amount:max button but it was likely to have been my entire balance from looking at transactions around that time.

**Comment by jennypollack** [comment]
Will mark this as closed by #8176 but feel free to reopen if you have issues again.
