### ISSUE TITLE
Long EIP712 payloads require user to scroll down

### ISSUE THREAD

**Issue by mrwillis** [MetaMask/metamask-extension#7962]
**Describe the bug**
User is required to scroll to find the "sign" button for a long EIP712 payload.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Create a long EIP712 payload to sign, and the user will be forced to scroll down to see the "sign" button.

**Expected behavior**
No scrolling to reach the "sign" button

**Screenshots**
![image](https://user-images.githubusercontent.com/2652683/73496079-cd29c700-4385-11ea-8d1f-9078deafddfa.png)

**Browser details (please complete the following information):**
 - Ubuntu 18
 - Google Chrome Version 79.0.3945.117 (Official Build) (64-bit)
 - MetaMask Version 7.7.2

**Additional context (Error Messages, etc.)**
Admittedly this isn't a bug per-se, but I also wouldn't call it a feature request. Perhaps if the scroll bar is removed, it is a security issue for the user if something is "hidden" in the payload, but it is also a bit annoying if the user has to do this every time they see a long EIP712 payload, which is becoming more and more common.

**Comment by Gudahtt** [comment]
I have confirmed that this still affects MetaMask v9.0.1

**Comment by mrwillis** [comment]
Any update on this? This is a really annoying issues especially for complex EIP712 payloads

**Comment by bschorchit** [comment]
Closing as this has been fixed with https://github.com/MetaMask/metamask-extension/pull/13642
