### ISSUE TITLE
Prefer chainId over networkId whenever possible

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#7963]
Our stack uses `networkId` from `net_version` extensively. We should switch to using the `chainId` from `eth_chainId` ([EIP here](https://eips.ethereum.org/EIPS/eip-695)) wherever possible. Places/cases include:
- The transaction controller
  - Especially when signing transactions (as suggested by Truffle)
- The UI

**Comment by davidmurdoch** [comment]
Looks like https://github.com/MetaMask/metamask-extension/blob/507859830689e269fa87a6256bb6102071826976/app/scripts/controllers/network/network.js#L116 is the culprit.

**Comment by rekmarks** [comment]
@davidmurdoch much obliged!
