### ISSUE TITLE
Do not reject ENS .test names on non-ropsten networks

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#7965]
Currently we seem to have a validation that automatically assumes there is no valid ENS registry on networks other than `mainnet` and `ropsten`, but there are now registries at the same address on many networks, so we should remove that validation.

**Comment by whymarrh** [comment]
This sounds like what was fixed in #7960—our old network map was only Mainnet and Ropsten.

**Comment by Gudahtt** [comment]
^ Agreed - I think we support all documented testnet ENS registries now.
