### ISSUE TITLE
Extension incorrectly detects locale? (French instead of English)

### ISSUE THREAD

**Issue by olalonde** [MetaMask/metamask-extension#7972]
**Describe the bug**

After installing the Chrome extension, the extension is in French by default without any way to change the language. As far as I know, my computer and browser languages are both English and I'm not currently located in a French speaking country. Why does it chose to use the French translation?

**To Reproduce (REQUIRED)**

Install extension on Chrome.

**Expected behavior**

Extension should be in English.

**Screenshots**

<img width="542" alt="Screen Shot 2020-02-02 at 8 48 15 AM" src="https://user-images.githubusercontent.com/416585/73608395-e0f94700-4598-11ea-8998-0f9f432037c7.png">

**Comment by Stefanos1981** [comment]
Stefanos Lamprianidis

**Comment by Stefanos1981** [comment]
Need token

**Comment by JoshuaPaulBarnard** [comment]
I am having the same issue, it installed itself using chinese!!
Were you able to fix this issue, and if so, how??

**Comment by lukeflegg** [comment]
Yes please! Mine also installed in French for no reason I can imagine.

**Comment by tmashuang** [comment]
Asking a few leading questions on this issue to help debug for anyone that is having this problem.

Which Browsers are you using?
If Chrome/Brave, what does the `Order languages based on your preference` list show under `chrome://settings/?search=languages`, is the locale that set at the top the one that we show first?

From what I gather we the first result of `i18n.getAcceptLanguages`, docs [here](https://developer.chrome.com/extensions/i18n#method-getAcceptLanguages). Our implementation [here](https://github.com/metamask/metamask-extension/blob/develop/app/scripts/lib/get-first-preferred-lang-code.js). 

Granted it might be more beneficial to use [i18n.getUILanguggage](https://developer.chrome.com/extensions/i18n#method-getUILanguage).

**Comment by tmashuang** [comment]
We are closing this issue as a won't fix, considering this [comment](https://github.com/MetaMask/metamask-extension/pull/8295#issuecomment-610156022). We much rather have a flexible implementation rather that a set one. 

If anyone else is having this issue in the future be sure to change the desired language to the top of the preferred language list in your browser. If you rather see `getUILanguggage` implementation over `getAcceptLanguages`, please feel free open the discussion as a new issue.
