### ISSUE TITLE
Metamask Transaction Failed with Gaz But Still Charge The Cost Of Gaz

### ISSUE THREAD

**Issue by Sirlupinwatson1** [MetaMask/metamask-extension#8003]
**Describe the bug**

Hi, If i want to send DAI to Coinbase, the transaction is failing but still charge the amount of gaz.

I am able to receive ETH from Coinbase but not send DAI 

I have Gaz and it say i don't. It does still charge me each time. I tried over 5 time. With different speed also. Even tried to change Advance option, but they just don't work at all.

I did remove extension, re-install it. Still the same.

.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Wallet and send DAI to Coinbase
2. Click on transaction speed, either Slow, Medium or Fast
3. Click Send
4. See error, Failed Transaction

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

![faillll](https://user-images.githubusercontent.com/55941045/73966002-33ad6880-48e3-11ea-9aa4-3851046ae907.png)

![Sans titremetks](https://user-images.githubusercontent.com/55941045/73966018-38721c80-48e3-11ea-8fd4-fd08f9734eb4.png)

![Sans titre](https://user-images.githubusercontent.com/55941045/73966026-3a3be000-48e3-11ea-88f0-30d35cb0f0e2.png)

**Browser details (please complete the following information):**
 - OS: Windows 10, 1909  18363.592
 - Hardware Wallet Metamask 7.7.4
 - Browser Version 82.0.4050.0 (Build officiel) canary (64 bits)
 - MetaMask Version 7.7.4

<a href="https://area51.stackexchange.com/users/206666/armand-b">
<img src="https://area51.stackexchange.com/users/flair/206666.png?theme=hotdog" width="208" height="58" alt="Area 51 profile for Armand B." title="Area 51 profile for Armand B.">
</a>

**Comment by jennypollack** [comment]
please email support@metamask.io with a reference to this issue for further assistance
