### ISSUE TITLE
Firefox security key message pop up flickers when interacting with hardware wallets

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#8008]
**Describe the bug**
A message blinks multiple times on Firefox whenever interacting with a hardware wallet on Firefox, through MetaMask.

**To Reproduce (REQUIRED)**
Plug in a hardware wallet, Trezor or Ledger, click Connect Hardware Wallet.
![image](https://user-images.githubusercontent.com/16330048/73977725-788bcc00-48f0-11ea-8d4d-43b0b6bfd7ae.png)

The connection still works, but the popup is distracting and some think it is not working and stop proceeding.

**Expected behavior**
Firefox on Windows has a similar but slightly different popup message.  

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Mac OSX (and it appears to occur on windows too)
 - Hardware Wallet Ledger Nano
 - Browser Firefox
 - MetaMask Version 7.7.4

**Comment by dpazdan** [comment]
It appears that Firefox sees it as a U2F security key.  Following the steps in this link seems to make the message persist, rather than flicker: https://support.yubico.com/support/solutions/articles/15000017511-enabling-u2f-support-in-mozilla-firefox

**Comment by dpazdan** [comment]
Similar message on windows: 
![image](https://user-images.githubusercontent.com/16330048/73980179-534d8c80-48f5-11ea-8811-57c52e38bd70.png)

**Comment by AlexJupiter** [comment]
This wasn't noticed on Firefox 97.0 with MacOSX 12.0.1
