### ISSUE TITLE
Duplicate web3 running in Brave Browser

### ISSUE THREAD

**Issue by rossbulat** [MetaMask/metamask-extension#8012]
It looks like the Brave browser is running another instance of web3, so Metamask has odd behaviour and flags error in the console. 

```
Uncaught Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.
    at Object.<anonymous> (inpage.js:1)
    at Object.2../createStandardProvider (inpage.js:1)
    at i (inpage.js:1)
    at t (inpage.js:1)
    at inpage.js:1
```

This has been [mentioned](https://twitter.com/metamask_io/status/1184061355571200003) but no fix has been implemented. I and many others use the Brave wallet for storing BAT so turning off the wallet is not an ideal fix.

**To Reproduce**
Install Metamask extension in Brave browser

**Expected behavior**
There should not be discrepancies 

**Screenshots**
<img width="335" alt="Screenshot 2020-02-07 at 09 30 30" src="https://user-images.githubusercontent.com/13929023/74018173-55632a00-498d-11ea-8acd-246400b3a6ea.png">

**Browser details (please complete the following information):**
 - OS: macOS
 - Browser: Brave 1.2.43
 - MetaMask Version: 7.7.3

**Comment by ryanml** [comment]
Hi @rossbulat - We recently landed some code that will improve Brave compatibility with Metamask and other web3 providers. https://github.com/brave/brave-core/pull/4273

This is currently riding our release trains and is scheduled to land in our 1.5 release.

For all other issues within Brave regarding Crypto Wallets, you may file them here: https://github.com/brave/brave-browser/issues Thanks!

**Comment by rossbulat** [comment]
Great to hear and thanks for following up! Looking forward to the release and additional Brave support.

**Comment by tmashuang** [comment]
Closing thanks @ryanml.

**Comment by KudretBayram** [comment]
Hi guys, it appears this issue is back. Same error message...

![Screen Shot 2021-08-10 at 9 42 48 pm](https://user-images.githubusercontent.com/33335075/128861075-67cd77ac-d336-473f-8fb2-bbb70a53dafa.png)

**Comment by jnbn** [comment]
same here

**Comment by itinance** [comment]
Can confirm with V1.28.105, that this issue still appears

**Comment by KudretBayram** [comment]
Hi all,

As a temporary solution you can disable off the native "Crypto Wallets" as the error is complaining about the presence of "another web3 extension".

You can do that here:
brave://extensions/

I've attached a screenshot for familiarity. 

If you need an existing wallet associated with Crypto Wallets, you can import it to MetaMask.

![Screen Shot 2021-08-15 at 1 32 12 pm](https://user-images.githubusercontent.com/33335075/129466105-8d084ea1-cd88-4755-a849-31b28f6289db.png)
