### ISSUE TITLE
Select multiple accounts

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#8030]
As a dapp user, I'd like to be able to select multiple accounts, so that I will be able to connect them.

**Description**

This is the ability to select an account(s) when connecting to a dapp.

Designs are currently available here: https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=752%3A44

**AC**

* Select all option
* select individual options
* Reusable component in the design system

**Comment by wbt** [comment]
Why was this closed as completed? The interface misleadingly allows you to select multiple accounts to connect to a site, but MetaMask then only ever passes on the first one (in a sequencing the user can't control, especially if currently using a non-connected account) to the Dapp/website.  The accounts array is always length 1 (or 0) even if a user connects multiple accounts.  

Can the multiple connected accounts please be passed on to the site in a longer accounts array?

If there's a good reason why that can't be done, can the MetaMask UI be improved to allow only selecting one account to make it clear to a user that only the one account will be presented to the site?
