### ISSUE TITLE
Be alerted about the seriousness of connecting my wallet

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#8043]
As a dapp user, I'd like to be alerted about the seriousness of connecting my wallet, so that I won't connect to a site that I don't trust.

**Description**

This is an alert that is displayed before the user actually connects their wallet.

Designs: https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-%2F-Login-Per-Site?node-id=378%3A4528

**Comment by Gudahtt** [comment]
This has been done; it shipped a while back in one of the earlier v8 updates.
