### ISSUE TITLE
See which of my connected accounts is currently primary

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#8044]
As a dapp user with multiple accounts connected to a site, I'd like to see which of my connected accounts is the one that is currently primary, so that I will understand what a site is using.

**Description**

When a user views the list of their accounts, they need to know the connection state of each of their accounts. Our supported states are:

Connected - Primary [ie. selected]
Connected [ie. connected but not selected]
Not connected [ie. never been connected]

**Designs** 
https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-Login-Per-Site?node-id=1381%3A60

**Comment by Gudahtt** [comment]
This has been done; it shipped in one of the earlier v8 updates.
