### ISSUE TITLE
Find a link to a site I'm connected to

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#8045]
As a dapp user, I'd like to find a link to a site I'm connected to so that I can recall what that specific dapp is.

**Description**

In the designs, this currently exists as a nested "Go to ____" option when viewing the connected sites modal.

Designs: https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-Login-Per-Site?node-id=1217%3A77

**Comment by Gudahtt** [comment]
We had talked about scrapping this idea; I don't recall where we left of with this :thinking:

I'll close for now, as it doesn't seem to be present in the latest designs in Figma. We can re-open if this is still something we want (cc @rachelcope)
