### ISSUE TITLE
Problem with GasLimit for BAT

### ISSUE THREAD

**Issue by ligi** [MetaMask/metamask-extension#8055]
relaying this for a user from reddit:
https://www.reddit.com/r/ethereum/comments/f4e4qs/unable_to_send_erc20_out_of_gas/

**Comment by yakkomajuri** [comment]
Same problem for SNT. MetaMask gives a wrong estimate for gas necessary to perform the transfer() function and if a user does not manually adjust the gas limit the transaction will fail.

**Comment by tmashuang** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/8176. Will get it out in the next release thanks for the report and investigation.
