### ISSUE TITLE
Possible improvements when using testing networks

### ISSUE THREAD

**Issue by alcuadrado** [MetaMask/metamask-extension#8081]
Hi,

I'm not sure if this should be labeled as a feature request or bug report. But these are things that can make the development experience of lots of people better.

When using a testing network like ganache, it is common to restart it. When the network gets back online, if you try to use MM you get multiple errors because the account nonces are out of sync, and some requests (e.g. `eth_getCode` and `eth_getTransactionCount`) receive block tags that are too big.

Can you automatically reset your internal block counter and account nonces when an `eth_blockNumber` returns a lower block than expected? 

My current workaround is going to Settings > Advanced > Reset Accounts each time I restart the network, which is painful.

**Comment by Gudahtt** [comment]
Thanks for the suggestion! This is an enhancement we've been meaning to look at for a long time now; it was described in #2373. I'm closing this as a duplicate. The workaround you're using is the best solution that currently exists as far as I know.
