### ISSUE TITLE
See that I'm connected to this site but NOT with my current account

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#8091]
As a dapp user, I want to be alerted if the account that I'm on in the extension is not connected to the site that I'm visiting but another is, so that I will know that I should switch to that account.

**GIVEN:** I am on a (d)app
AND: And have at least 1 account connected to that (d)app
BUT: The account currently selected in my extension is NOT connected
**THEN:** I should see an alert indicating that I am not connected to the current account, with an option to "Connect"
**AND:** When I click the the "connected status indicator"
**THEN:** A modal should open
**AND:** I should see an alert indicating that I am not connected to the current account, with an option to "Connect"

Designs:
Main extension view: 
https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-Login-Per-Site?node-id=955%3A66

Modal: 
https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-Login-Per-Site?node-id=955%3A264

**Comment by VanijaDev** [comment]
Hi, I am looking for the same solution 

Also can't reach Figma.
File not found
Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.
