### ISSUE TITLE
See a list of accounts connected to the current site

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-extension#8094]
As a dapp user, I'd like see all the accounts connected to the site that I am currently visiting, so that I will know which accounts are connect. 

**GIVEN:** I am on a (d)app
AND: I have 1 or more accounts connected
**WHEN:** I click on the "connected status indicator"
**THEN:** A modal opens showing the account that I am currently connected to (Connected)
AND (if applicable): A list of accounts that are currently connected but not active (Last active)

Designs: 
1+ connected account: 
https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-Login-Per-Site?node-id=955%3A208

2+ connected accounts:
https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-Login-Per-Site?node-id=955%3A295

**Comment by amir1392** [comment]
0x3cAe4863906286fE022Fb6e1136764A39a0c1f89
