### ISSUE TITLE
Add notification when multiple accounts are selected on first screen of new connect flow

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#8102]
#8078 implements the new connect flow

One of the missing features that will not be merged with that PR  is to add the notification pictured here:

![Screenshot from 2020-02-25 10-09-04](https://user-images.githubusercontent.com/7499938/75252263-e5d7a200-57b6-11ea-959f-697e41b67fd2.png)

Doing so will be trivial once https://github.com/MetaMask/metamask-extension/pull/8071 is merged.

**Comment by Gudahtt** [comment]
Is this still something we want? I wasn't able to find it in Figma, so maybe it was removed in a subsequent design update :thinking: 
cc @danjm @rachelcope

**Comment by rachelcope** [comment]
I think you're right @Gudahtt . This alerts wasn't part of the final designs, so I think it can be closed
