### ISSUE TITLE
Allow users to disable phishing detection

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8105]
Requested by @ryanml from Brave, which he said he'd complete.

Acceptance criteria:
- A toggle switch in the settings page.
- Should persist the user's preference.
- Should fully disable checking the phishing list on page load.
- Should be on by default.

**Comment by Gudahtt** [comment]
Sounds reasonable to me! I'd add that it should be on by default as well.

**Comment by danfinlay** [comment]
> Sounds reasonable to me! I'd add that it should be on by default as well.
Agreed. Added.
