### ISSUE TITLE
Add warning message about u2f hardware wallets

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8120]
Until browsers add HID support so we can complete #8100, we should warn users that under some conditions, hardware wallet connections can be unreliable.

Acceptance criteria:
- On the hardware wallet connect screen, warn "Hardware wallets that use the U2F protocol to connect can be unreliable under some circumstances. Click here to read more."
- The word `here` should link to an article on [our support page](https://support.metamask.io) that includes a general description. Latest draft is available [here](https://docs.google.com/document/d/1ACLspDQtJC8Msx-EbXCpFwOBavTfc4Fd1nCzYRtaz7M/edit?usp=sharing), ask me for permission to edit.

**Comment by hitchhooker** [comment]
this would be really great since it is extremely hard to figure out what is the cause of problem for why ledger nano does not work with metamask in windows10(gives popup error when trying to connect in latest windows versions).  is there actually workaround without running linux virtualmachine existing to use metamask and ledger nano in windows?

**Comment by hitchhooker** [comment]
actually Ledger support was blaming Metamask not supporting WEBhid/WEBUSB. 

support replied to me which is quite conflicting info compared to the latest draft you have written dan:

> 
> 
> I understand you're having trouble using your Ledger device with a web wallet. It makes Windows display an annoying popup. This is caused by the web wallet using the U2F transport to communicate with your Ledger device.
> 
> The developers of the web wallet will need to switch to a different transport when connecting the device. Please reach out to them and explain to them the problem and that this can be solved by changing to a different transport (webHID or webUSB). If more users like you give this feedback, it may increase their priority to fix this problem.
> 
> Another workaround is to use a different operating system (macOS, Linux). Linux in a virtual machine, such as Virtualbox, would also work.
> 
> In the meantime, our developers are well aware of this problem. They will see what they can do here but the fix for this (in case we do it for Metamask) might not be delivered anytime soon.

**Comment by danfinlay** [comment]
Ledger Live is planning to add bridge support, so we can use its USB connection instead of using browser-based connections. We are waiting on Ledger to finalize this support.

**Comment by danjm** [comment]
I believe this can be closed because we have added WebHID support
