### ISSUE TITLE
How to switch metamask from chinese to english

### ISSUE THREAD

**Issue by JoshuaPaulBarnard** [MetaMask/metamask-extension#8130]
I just downloaded and installed the metamask chrome extension for my windows 10 PC, and it is all in Chinese!  I do not know chinese and i am unable to change the language to english.
I want to use metamask but i need to be able to read it!  Please let me know how to change it to english.

**Comment by friederbluemle** [comment]
Hi @JoshuaPaulBarnard - Did you find a solution? For some reason MetaMask has one of the weirdest language auto-selection mechanism.. It's in Chinese for me as well and I don't know how to switch it. A while ago I managed to change it to English on one of my computers, but I can't remember how. I already checked the language list in my browser - Chinese is not part of it.

**Comment by ironandsilk** [comment]
Is there a solution to metamask plugins displaying in Chinese or is this a chrome security risk?
Why was this closed - it seems like it's still happening and 4k+ people starred this issue.

**Comment by gWOLF3** [comment]
This is still a problem. Pls help

**Comment by JamesLloydPartington** [comment]
I have this problem with Ubuntu 20.04
