### ISSUE TITLE
Investigate Ledger signature failure

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8135]
I observed @arachnid sign a transaction with his Ledger that the network would reject.

In practice, this looked like the transaction was in the "submitted" state, but it never entered the miner mempool.

Nick shared with me state logs from this failed transaction, along with a successful signature done later with MyCrypto.

We should compare these signatures, figure out why his MetaMask-Ledger combination produced what appears to be an invalid transaction, and fix that bug.

Not posting state logs here for privacy, but team members can request them from me.

**Comment by CallMeGwei** [comment]
I've also been having this issue and am willing to share data if helpful.

**Comment by whymarrh** [comment]
@CallMeGwei do you have a set of steps that can repro this reliably?

**Comment by danfinlay** [comment]
We have identified the cause of this issue, fix is pending.

**Comment by CallMeGwei** [comment]
@whymarrh Do you still need this? I was able to reproduce it reliably five days ago.

**Comment by Gudahtt** [comment]
@CallMeGwei Thanks for the offer! But no I think we're OK now - we've since learned how to consistently reproduce this issue, and it has been fixed and published in v7.7.7

Let us know if you still encounter this issue in v7.7.7 though!
