### ISSUE TITLE
erc20 transfer out of gas errors when sending max tokens

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#8136]
Version 7.7.2

I've twice seen erc20 out of gas errors when transferring tokens on mainnet. The two tokens were USDC and WETH. What the failures had in common was that the gas estimation seemed to not take into account that the recipient had no prior balance, so the SSTORE cost 20000 instead of 5000. This can also happen if the recipient empties their balance before the transfer confirms but that wasn't true this case.

In both cases I was sending the entire token balance of my account.

I did not see a similar issue when I was transferring ETH to the WETH contract, which created WETH for an account that had none.

The workaround is to manually set the gas limit in Advanced.

**Comment by wjmelements** [comment]
I have now also reproduced this for GST2.

**Comment by wjmelements** [comment]
This issue seems to only affect transfers.

**Comment by danfinlay** [comment]
Sine we call `eth_estimateGas` from geth, and then add a 50% buffer, this seems like it is likely a bug in geth.

The most ideal reproduction would be to open the background network inspector, and `copy as cURL` the request to infura that is returning the insufficient gas estimate.

With that request, Infura and geth team members will be able to trace why the estimate is low.

**Comment by jacobcantele** [comment]
@wjmelements Would you be willing to hop on a quick call to help us replicate this issue? We're having trouble recreating it. Do you have Telegram or some other medium I can use to contact you directly?

**Comment by wjmelements** [comment]
I can still 100% repro on 7.7.7.

> Sine we call eth_estimateGas from geth, and then add a 50% buffer, this seems like it is likely a bug in geth.

I don't think metamask does that. Probably your estimate gas params are wrong.

> Do you have Telegram or some other medium I can use to contact you directly?

I have the same username on most platforms

**Comment by tmashuang** [comment]
> In both cases I was sending the entire token balance of my account.
Is this by using the Max Button?

**Comment by wjmelements** [comment]
I have found your bug, you are estimating gas with value=0 in the transfer

**Comment by wjmelements** [comment]
<img width="1037" alt="Screen Shot 2020-03-10 at 3 48 15 PM" src="https://user-images.githubusercontent.com/799573/76366206-9630c480-62e6-11ea-9b25-86d402a70002.png">

**Comment by tmashuang** [comment]
Value is determined in the data hex for token transfers.

**Comment by wjmelements** [comment]
> Value is determined in the data hex for token transfers.

As seen in the data, it is 0

**Comment by wjmelements** [comment]
There are no subsequent calls to eth_estimateGas after the estimate with transfer of 0, so that is the issue. You have to re-estimate with the correct transfer value. A transfer of 0 will not change the 0-ness in the SSTORE when the recipient has no tokens.

**Comment by tmashuang** [comment]
Hmm I am fairly certain we update data on input change, otherwise we would see numerous other issues, but ill investigate that a little more. Can you clarify on what what method those params are for, I am guessing its for eth_estimateGas?

**Comment by wjmelements** [comment]
> Can you clarify on what what method those params are for, I am guessing its for eth_estimateGas?

right

**Comment by wjmelements** [comment]
Here are repro steps, including a bug where you suggest a gas price that is 8x too high despite the "Slow" setting.

<img width="355" alt="Screen Shot 2020-03-10 at 3 57 05 PM" src="https://user-images.githubusercontent.com/799573/76366692-f4aa7280-62e7-11ea-9f9e-25813419ea53.png">
<img width="355" alt="Screen Shot 2020-03-10 at 3 57 16 PM" src="https://user-images.githubusercontent.com/799573/76366697-f70ccc80-62e7-11ea-8fae-8e4c5782aa75.png">
<img width="353" alt="Screen Shot 2020-03-10 at 3 57 28 PM" src="https://user-images.githubusercontent.com/799573/76366706-fd02ad80-62e7-11ea-9236-e81fcc722b25.png">
<img width="355" alt="Screen Shot 2020-03-10 at 3 57 37 PM" src="https://user-images.githubusercontent.com/799573/76366710-012ecb00-62e8-11ea-9119-83e4087025ad.png">
<img width="352" alt="Screen Shot 2020-03-10 at 3 57 45 PM" src="https://user-images.githubusercontent.com/799573/76366715-055ae880-62e8-11ea-8b75-801fe0055841.png">
<img width="945" alt="Screen Shot 2020-03-10 at 3 58 08 PM" src="https://user-images.githubusercontent.com/799573/76366721-0a1f9c80-62e8-11ea-8828-8e542c95eeb4.png">

**Comment by wjmelements** [comment]
Also, note how the "Send Amount" shows 100% of my ETH instead of 100% of my MKR in the penultimate screenshot. I don't think that manifests in the TX but it's still fairly scary to think you might be sending all my ETH to the MKR token contract.

**Comment by wjmelements** [comment]
> Hmm I am fairly certain we update data on input change

I have verified that you do when I type in the value, but you do not when the Max button is pressed instead.

**Comment by tmashuang** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/8176. Will get it out in the next release thanks for the report and investigation.
