### ISSUE TITLE
Issue with spend limit permissions - MakerDao voting contract

### ISSUE THREAD

**Issue by webs7er** [MetaMask/metamask-extension#8146]
I signed the MakerDao voting contract while setting a max spend limit of "6.5".
![image](https://user-images.githubusercontent.com/5611279/75604537-f56a2a00-5ad9-11ea-8743-f067d938438a.png)
_(Note: screenshot is from another wallet)_

When depositing to the contract, I could deposit MKR exceeding the pre-set limit, see tx: https://etherscan.io/tx/0x5559d3dd99a0442cd88195d4eef3193191a7f294861fe62eb8e6ebf50e5cba5f

On the other hand, when withdrawing from the voting contract, I could only take out up to "6.5" MKR. 
1. First tx failure (withdrawing max amount): https://etherscan.io/tx/0x0d875c835193088fa716f2d1fc930bfe11e9815039ca4e47bc12a0f4f7bc8d0c
2. Withdrawing 6 MKR: https://etherscan.io/tx/0xcb00d7e0bbb098bc9860417d75995039eb81ccfb606966cc42937bb1e9d98342
3. Withdrawing 0.5 MKR (for a total of 6.5):
https://etherscan.io/tx/0x1a025b1a5c75d26f45b4a685cf39672f8b3739c1c93f80b29d4f843f8e50f922
4. Attempting to withdraw the remaining 0.0693 MKR left in the voting contract:
https://etherscan.io/tx/0x49725a42db9b5b932aacddc6d8a293bb92fa440df96b2996e1e98c5a2312ae38

**To Reproduce:**
1. Go to https://vote.makerdao.com/ -> Voting Contract -> Vote with a single wallet
2. Agree to the terms and conditions
3. In the "Allow Vote.makerdao.com to spend your MKR?" MetaMask dialog, click "Edit Permission"
4. Enter a custom spend limit, save and confirm the transaction
5. In the voting contract, try to deposit MKR with value higher that the pre-set limit - the transaction goes through
6. From the voting contract, try to withdraw MKR with value higher than the pre-set limit - the transaction fails
![image](https://user-images.githubusercontent.com/5611279/75604558-35c9a800-5ada-11ea-90d0-38db17c0e15b.png)

**Expected behavior**
From my understanding of the "spend limit" function, step 5. above should fail, whereas step 6. should succeed. 

**Browser details (please complete the following information):**
 - OS: Windows 10 Pro N, v1909
 - Chrome Version  80.0.3987.106 (Official Build) (64-bit)
 - MetaMask Version 7.7.4

**Comment by Gudahtt** [comment]
In the example failed transactions that you've shown, the functions being called are "lock" and "free" respectively. I'm not sure what these functions are supposed to do. They aren't ERC-20 functions, and we don't support them in MetaMask as far as I know.

**Comment by webs7er** [comment]
Hi @Gudahtt, thanks for taking the time to look into this.

I am not quite familiar with the concept of limit permissions and I'm not sure what problem they are trying to solve. Personally, I believe they are not needed, in this particular use case at least - although I did get the option to set a them (see Step 3. above). 

In any case, I'd like to know what causes the withdrawal to fail (with the error 'ds-token-insufficient-approval') - is it something linked to the limits I set (and/or how I set them), or is there another issue elsewhere? Would it help if I try reaching out to the MakerDAO developers?

**Comment by Gudahtt** [comment]
>is it something linked to the limits I set (and/or how I set them), or is there another issue elsewhere? Would it help if I try reaching out to the MakerDAO developers?

Yes, I think that would help. The failure you're asking about is specific to this contract (or type of contract), so the MakerDAO developers seem like the appropriate people to ask.

I'm going to close this issue for now, as I don't think there is any MetaMask bug here. But thanks for reporting this, and good luck in investigating this further!
