### ISSUE TITLE
Cannot remove transaction history for a chain id

### ISSUE THREAD

**Issue by zemse** [MetaMask/metamask-extension#8159]
**Describe the bug**
I'm deploying a PoA chain. Whenever I reset the blockchain, the old transactions still exist in the metamask history and I removed the network and re-add it, still the old transactions are displayed. The problem is with the nonce value. Since blockchain is cleared, it expects nonce value from zero, but metamask nonce values depend on transaction history hence the transaction doesn't get confirmed until transactions with lower nonce is confirmed in blocks.

I am sure that transactions are stored in Metamask by chain id instead of node IP or any other factor because I tried changing the chain id of the blockchain and with new chain id, no transactions are there which is good. But I can't change the chain id is a temporary solution. Multiple developers can't rely on this.

**To Reproduce (REQUIRED)**
Try to remove the transaction history of any network.

**Expected behavior**
There should be an option in the settings to clear transaction history or refresh transaction history (when there is a change in the blockchain data)

**Browser details (please complete the following information):**
 - OS: macOS
 - Version 80.0.3987.122 (Official Build) (64-bit)
 - MetaMask Version 7.7.3

**Comment by jennypollack** [comment]
Hey @zemse if you go to Advanced Settings "Reset Account" you will be able to clear the tx-history

**Comment by zemse** [comment]
Oh great! I thought resetting account would cause me to log out and I'd have to load my seed phrase again. But it is exactly what I wanted. Thanks!
