### ISSUE TITLE
Dapp's successful tx returned revert error but popup shows success

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8165]
[From twitter](https://twitter.com/_prestwich/status/1235328366208782339?s=20)

To investigate:

Is there a scenario where we might return a `-32016 reverted error` to a dapp when that transaction may have been considered a success by the network, or even a contract developer?

Sounds like this case also gets emitted as an error to the notification system, so it sounds like the error callback is being triggered erroneously, but other parts are working right.

**Comment by prestwich** [comment]
Here is one of the transactions in question:
https://kovan.etherscan.io/tx/0x07f6cb0e6315365b0f0e789771f996cc2f6abb43d16769c16b7b9d3720d25a6b

Kovan, so it's possible this is parity-specific

**Comment by danfinlay** [comment]
With state logs, I could tell you with greater certainty that this error came from Parity. It looks pretty plausible to me right now.

**Comment by danfinlay** [comment]
There's also always the possibility that there was a uncle situation where the transaction hit an exception on an uncle, returned you the error, but then a longer chain was able to process it. Not sure why an `approve()` method would ever fail, though.

**Comment by prestwich** [comment]
update: this might be user error. It looks like we're submitting multiple txns (including 1 non-approve) accidentally

**Comment by danfinlay** [comment]
Ok, closing for now, let me know if you get extra info.
