### ISSUE TITLE
Can't Confirm Transactions with Ledger Nano S in Chrome

### ISSUE THREAD

**Issue by reavis** [MetaMask/metamask-extension#8166]
Transaction fails immediately after clicking confirm with the following error message:
Index for address 'redacted' not found. Ledger shows transaction confirmation UI.

**To Reproduce**
1. Plug in hardware wallet, unlock, and open the Etherium app.
2. Trigger a transaction/contract interaction.
3. Click Confirm.

**Expected behavior**
Metamask waits until transaction is confirmed on the hardware wallet, then broadcasts the transaction.

**Screenshots**
<img width="359" alt="Screen Shot 2020-03-04 at 4 36 16 PM" src="https://user-images.githubusercontent.com/109728/75938218-0b5e4e80-5e3c-11ea-9cf4-7bdca9222bc8.png">

**Browser details**
 - OS: OS X 10.14.6
 - Hardware Wallet: Ledger Nano S Firmware version 1.6.0
 - Browser: Chrome Version Version 80.0.3987.132 (Official Build) (64-bit)
 - MetaMask Version: 7.7.6

**Additional context**
This is working properly in Firefox 73.0.1 (64-bit) with Metamask 7.7.7

**Comment by reavis** [comment]
I am unable to upgrade to 7.7.7 through the Chrome Web Store, but I manually downloaded it and installed the unpacked extension and this appears to be fixed!

**Comment by Maxcarrera** [comment]
How can I solve this problem? When I want to do any transaction, it says exactly this error
