### ISSUE TITLE
Seed phrase should be forced to lowercase before test/importing

### ISSUE THREAD

**Issue by mryellow** [MetaMask/metamask-extension#8171]
When importing a seed phrase recorded in upper-case for legibility it is rejected as invalid.

**Expected behavior**

Valid seed phrases should import correctly. Rejecting valid seeds as being "invalid" because of their case only functions to raise user's blood pressure and cause time wasted seeking answers.

**Comment by mryellow** [comment]
Whitespace other than space characters should also either be stripped or replaced with spaces, which can then be limited to 1 space between each word as part of the sensitisation.

**Comment by whymarrh** [comment]
> Seed phrase should be forced to lowercase before test/importing

This is fixed with #8246, and will be in our next release. Thanks for bringing this up!

> Whitespace other than space characters should also either be stripped or replaced with spaces, which can then be limited to 1 space between each word as part of the sanitation.

This should already work as expected, I can import seed phrases with newlines and tab characters and multiple spaces. Feel free to open up another issue if this isn't the case for you.
