### ISSUE TITLE
Add support for RSA (Encrypt/Decrypt) messages

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#8173]
It would have been great if metamask was able to support something like https://www.npmjs.com/package/ethereum-rsa without getting user's private key and public key.

**Comment by jennypollack** [comment]
we just merged https://github.com/MetaMask/metamask-extension/commit/6f47fece5699f8b8ee0870ae37fe91bbb844c563 
please take a look!

**Comment by tmashuang** [comment]
Closing since #7831 was merged. If I am mistaken and that you are referring to a different scope please let us know.
