### ISSUE TITLE
Please support Firefox Mobile!

### ISSUE THREAD

**Issue by ytrezq** [MetaMask/metamask-extension#8175]
So far the only way to get Memask working with an official web browser on Android *(which means doing things like add blocking and userscripts for trading without a Desktop computer)*.
But the ui api is different, so it doesn t works with website connecting to it right now.

**Comment by Welziewagers2015** [comment]
I was having the same issue I got forgot for androind. And downloaded the add on in browser. They finally linked with Google but it took for ever.

**Comment by Welziewagers2015** [comment]
Firefox

**Comment by Welziewagers2015** [comment]
Sorry

**Comment by Gudahtt** [comment]
Could you explain further what's wrong? I don't know what you mean by "the ui api is different"

I know that we do have a few screens that don't work very well on mobile, like the onboarding flow, because they were designed for desktop. Is that what you mean?

**Comment by Gudahtt** [comment]
Also worth nothing that later this year, FIrefox for Android will be disabling support for all extensions, including this one. Unfortunately we can't do anything about that. You might want to try out the [MetaMask mobile app for Android](https://play.google.com/store/apps/details?id=io.metamask), as that soon may be the only option.

**Comment by ytrezq** [comment]
> Also worth nothing that later this year, FIrefox for Android will be disabling support for all extensions, including this one. Unfortunately we can't do anything about that. You might want to try out the [MetaMask mobile app for Android](https://play.google.com/store/apps/details?id=io.metamask), as that soon may be the only option.

As far I m aware it will rather provide a different api than the one on Desktop.

**Comment by Gudahtt** [comment]
Are you referring here to the extension or the mobile app? What do you mean by "API" - do you mean the API that dapps use? (i.e. the provider)?

**Comment by Gudahtt** [comment]
I'll close this in favour of #2367
