### ISSUE TITLE
Update contract-method lookup endpoint to use Infura v3

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8193]
We're getting 404s from our old method here:
https://github.com/MetaMask/eth-method-registry/blob/d6ea959342551970f5b952c19293dcfacc6c4e79/index.js#L9

This is resulting to errors in production.

Reported by OpenSea [via twitter](https://twitter.com/dan_OpenSea/status/1238600868775071744?s=20).

**Comment by Gudahtt** [comment]
The contract registry issue has been resolved by #8200 and https://github.com/MetaMask/eth-method-registry/pull/15

The issue reported by OpenSea looks like an entirely separate issue, which has been reported already in #7234
