### ISSUE TITLE
Closed Welcome Back dialog box do not provide any feedback

### ISSUE THREAD

**Issue by xmaysonnave** [MetaMask/metamask-extension#8221]
Environment:
Debian Buster :
Linux andaman 5.5.10-xanmod2 #1 SMP PREEMPT Wed Mar 18 10:40:26 -03 2020 x86_64 GNU/Linux
Chrome:
Version 80.0.3987.149 (Official Build) (64-bit)
Metamask:
7.7.8

The Welcome Back dialog box when closed do not provide any feedback

![ksnip_20200320-105746](https://user-images.githubusercontent.com/20576132/77139041-69c13900-6a9a-11ea-8c62-8c629de095db.png)

Two methods are currently available to start an interaction with Metamask from Javascript:
The `await provider.send("eth_requestAccounts") ` call or the `await provider.enable()` method..

When the Welcome Back dialog box is displayed users have the opportunity to immediately close the dialog box. In such situation the send method do not raise any exceptions and the enable method do not return anything. The caller is stuck in its asynchronous call...

Thanks

**Comment by xmaysonnave** [comment]
The beta https://173555-42009758-gh.circle-artifacts.com/0/builds/metamask-chrome-8.0.0.zip fixes the issue. Closing the native dialog box properly propagates an exception giving a chance to implementers to handle it properly. Thanks

**Comment by Gudahtt** [comment]
Thanks for the report @xmaysonnave ! Great to hear that it has been fixed.
