### ISSUE TITLE
The default Localhost 8545 network setting hard codes ChainID to 5777

### ISSUE THREAD

**Issue by adrianmcli** [MetaMask/metamask-extension#8225]
**Describe the bug**

The default Localhost 8545 network setting hard codes ChainID to 5777. However Ganache has abandoned setting ChainID to always be 5777. We cannot rely on this anymore (source: I asked). This produces really hard to debug error messages such as "This contract is not deployed on this network".

I found this out by changing the MetaMask provider to:

```
new ethers.providers.JsonRpcProvider("http://127.0.0.1:8545")
```

And it worked. So I decided to compare the two providers and see what was different. It turns out the ChainID was always (incorrectly) set to 5777.

**To Reproduce**

1. Start a Ganache instance with `ganache-cli`
2. Change MetaMask to the default "Localhost 8545" setting
3. Inspect the `window.ethereum` object
4. Notice that the ChainID is 5777 regardless of the real ChainID (displayed in the terminal when you run `ganache-cli`)

**Current Workaround**

Simply create a new network profile (with the "Custom RPC" option in the dropdown) with `http://127.0.0.1:8545` and leave all defaults blank and the ChainID will be correct.

**Comment by brad-decker** [comment]
@adrianmcli which version of Ganache-cli are you using? FWIW when I connect to localhost 8545 with ganache-cli running, the chainId on the ethereum object is '0xNaN'.

**Comment by adrianmcli** [comment]
@brad-decker The latest: Ganache CLI v6.9.1 (ganache-core: 2.10.2)

**Comment by adrianmcli** [comment]
Oh wait, I think I have made a mistake in my reproduction steps, I left something out. Hang on.

**Comment by adrianmcli** [comment]
Strange, the problem seems to have gone away. I'll be closing this for now. Thanks for taking a look @brad-decker
