### ISSUE TITLE
Nearly maxed out gas limit on previously fine production contract

### ISSUE THREAD

**Issue by bhayward93** [MetaMask/metamask-extension#8227]
**Describe the bug**
Estimated gas limit is far too high for a contract out in production.

Main contract code:
https://gitlab.com/minds/token/-/blob/master/contracts/MindsBoost.sol

Contract address out in production:
0x112ca67c8e9a6ac65e1a2753613d37b89ab7436b

**To Reproduce (REQUIRED)**
Unfortunately not simple to reproduce as you would need an account on our site with at-least 1 token. I can provide this if I can verify somebody as being apart of the metamask project.

**Expected behavior**
Gas price should really be in the region of the estimated price in remix IDE - 20419, its actually around 9,000,000.

**Screenshots**

Prompt shown to the user on initializing contract:
![image](https://user-images.githubusercontent.com/18596813/77343219-3ea04900-6d29-11ea-88d8-e7a9fe7dc1d0.png)

Advanced settings, gas prices look inline with what to expect there:
![advanced](https://user-images.githubusercontent.com/18596813/77343257-52e44600-6d29-11ea-9daa-6216bf42497e.png)

The gas limit set by default on the right, on the left is me trying to input the value into ethgasstation:
![metmask1](https://user-images.githubusercontent.com/18596813/77343295-60013500-6d29-11ea-8205-81751dd18bea.png)

Result of manually setting the gas limit to 21000 (slightly more than the remix estimate)
![metmask](https://user-images.githubusercontent.com/18596813/77343420-8d4de300-6d29-11ea-9f95-f79b0e9bea77.png)

**Browser details (please complete the following information):**
A few users have noticed this and I've got a couple of team members to confirm so would expect a mix of devices.

Mine though: Firefox & Chromium / Ubuntu 19.10 with MetaMask 7.7.8

**Additional context (Error Messages, etc.)**
I saw in 7.7.8 a few adjustments were made around gas price, could this be related?

**Comment by jennypollack** [comment]
when you confirm the tx after manually setting the gas limit does it work?
(even though it says Exception thrown in contract code.)

**Comment by bhayward93** [comment]
Nope, fails with a 

![image](https://user-images.githubusercontent.com/18596813/77345806-10bd0380-6d2d-11ea-9b05-fb8129c0cb7e.png)

**Comment by jennypollack** [comment]
can you try looking at a previously successful transaction and input the gas that is actually used?

**Comment by dpazdan** [comment]
possibly related support ticket: 32905

**Comment by bhayward93** [comment]
Appears the limit was 246,586 and used was 147,744

Checking others they look roughly the same. 

https://etherscan.io/tx/0xc0e84f8dfd9aaf10234c1735013e264a8b644dcaa54193b94354752ca2b18d77

Tried with that value and the transaction failed.

**Comment by bhayward93** [comment]
Appears to be correct now. How very strange. I will monitor this throughout the week and update if this reoccurs.

**Comment by jennypollack** [comment]
hey @bhayward93 closing for now, but feel free to reopen if you experience it again
