### ISSUE TITLE
Send token screen does not use token icons from custom-added assets.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8252]
As a user who has added a token with a custom icon via EIP-747, I expect to see that custom icon in all places where the token icon is rendered.

Currently the send screen does not use the custom icon:
![Screen Shot 2020-03-30 at 10 37 53 AM](https://user-images.githubusercontent.com/542863/77943813-b8c55600-7272-11ea-8ef0-56c9c25f8e29.png)

**Comment by danjm** [comment]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md
