### ISSUE TITLE
Speed up latest transaction from a number of transactions with the same nonce

### ISSUE THREAD

**Issue by Wetitpig** [MetaMask/metamask-extension#8268]
**Describe the bug**
The first transaction of the same nonce is sped up rather than the last one submitted.
In metamask we are allowed to submit transactions of the same nonce with the "Edit Nonce" Feature. After I resubmitted a transaction of the same nonce, but with different data, I decided to speed up the transaction through the speed up button.
However, it was the first transaction which get bumped rather than the second (newest) transaction. As a result, the first transaction with wrong data eventually got confirmed.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to 'Send' Window
2. Send any transaction with normal procedures
3. Send another transaction of different amount of ether, but this time: Enter the same nonce as the last transaction in the 'Edit Nonce' Box
4. The box that shows the transaction should show the latest transaction
5. Click the speed up button and save the gas price
6. Look up on Etherscan. The transaction in step 2 is sped up with new gas price.

**Expected behavior**
The latest transaction is sped up.

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: None
 - Browser Chrome Version 80.0.3987.162 (Official Build) (64-bit)
 - MetaMask Version 7.7.8

**Comment by Gudahtt** [comment]
Related to #9053 and #7305  (all bugs caused by grouping transactions by nonce).

**Comment by bschorchit** [comment]
I believe this was fixed with https://github.com/MetaMask/metamask-extension/pull/10579 and can indeed be closed. @sleepytanya once you have a chance (no rush), would you mind confirming this is no longer an issue? Ty!

**Comment by sleepytanya** [comment]
@bschorchit Now it is impossible to send the transaction with the same nonce. 
Here is Chrome: 
<img width="349" alt="Screenshot 2023-09-04 at 11 49 09 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/ea4daa4b-9918-4001-a777-0b1aa60fe130">
Firefox:
<img width="842" alt="Screenshot 2023-09-04 at 11 49 50 AM" src="https://github.com/MetaMask/metamask-extension/assets/104780023/1e3bb4ec-f8f1-49f3-ae50-182908fef783">
