### ISSUE TITLE
REGRESSION: SendWyre: "Only INDIVIDUAL account types are supported by this API"

### ISSUE THREAD

**Issue by realKennyStrawn93** [MetaMask/metamask-extension#8296]
**Describe the bug**
MetaMask used to work fine for buying Minds tokens using SendWyre ― now, after returning back to it months later, it's giving the error message mentioned in the title.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to https://www.minds.com/token
2. Click on "Buy Eth"
3. Click on "Buy with SendWyre"
4. "Click on "Connect with MetaMask" when the second page pops up
5. Click "Sign" in the resulting pop-up window
6.
![SendWyre](https://user-images.githubusercontent.com/3030773/78706021-3a486400-78c3-11ea-9463-07b4e40e19f4.png)

**Expected behavior**
Should successfully sign and proceed to this 

**Screenshots**
Already attached above

**Browser details (please complete the following information):**
 - OS: Arch Linux (Kernel 5.6.2arch1-2, KDE Plasma 5.18.4, Wayland 1.18.0, Pacman 5.2.1, yay 9.4.6.r3.g0e20e3c, libalpm 12.0.1)
 - Hardware Wallet: N/A
 - Browser: Brave 1.5.123 ([AUR](https://aur.archlinux.org/packages/brave-bin))
 - MetaMask Version: 7.7.8

**Additional context (Error Messages, etc.)**

**Comment by jennypollack** [comment]
Hey @realKennyStrawn93! We checked in with Wyre and it looks like Minds is currently in the middle of integrating to the new wyre debit card version of the widget. Once the migration is completed this problem will be solved.
