### ISSUE TITLE
Fix wording on DEPOSIT > Wyre

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-extension#8309]
**Describe the bug**
Credit cards are not supported, only Debit cards are currently supported by Wyre for purchases.

**Screenshots**
![wyre](https://user-images.githubusercontent.com/2995401/78807443-5f70cb80-79c4-11ea-9fe2-5361d434d4bf.png)

**Comment by tmashuang** [comment]
Fixed in #7654. I'll see to it that it is in the next release.
