### ISSUE TITLE
Phishing alert displaying on some whitelisted sites in Chrome 81

### ISSUE THREAD

**Issue by forrestb** [MetaMask/metamask-extension#8321]
Upon updating chrome, the "Ethereum Phishing Detection" alert page is now popping up on some whitelisted URLs (e.g. audius.co and actua.ad, both of which are in whitelist: https://github.com/MetaMask/eth-phishing-detect/blob/949c23a70ee7b1e3692789a16be49fb757af527f/src/config.json#L641)

**To Reproduce**
Go to audius.co or actua.ad and you will be unable to view the content due to the "Phishing Detection" page incorrectly being triggered (despite these sites being in whitelist)

**Browser details:**
 - OS: OS X & Windows 10
 - Browser: Version 81.0.4044.92 (Official Build) (64-bit)
 - MetaMask Version: 7.7.8

**Comment by tmashuang** [comment]
Fixed in https://github.com/MetaMask/eth-phishing-detect/pull/3796.
