### ISSUE TITLE
Show local nicknames over ENS names when available

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8322]
On the tx confirmation screen, we show ENS reverse-resolved names, which is great.

HOWEVER, if a user has a local nickname for an address, we should show that with higher precedence:

![Screen Shot 2020-04-10 at 10 50 23 AM](https://user-images.githubusercontent.com/542863/79011596-301fa300-7b19-11ea-8949-6c0bc40f8953.png)

**Comment by mirceanis** [comment]
This is no longer relevant.
Reverse resolution has been removed from this screen. Local nicknames are used when available, otherwise the shortened address.
See #22190
