### ISSUE TITLE
Having an error when using MetaMask Chrome extension

### ISSUE THREAD

**Issue by akefhabbal-qu** [MetaMask/metamask-extension#8326]
I'm using the latest version of MetaMask and I'm connecting it with my Dapp. I'm having the following problem when I try to confirm a transaction in MetaMask dialog, I'm connecting MetaMask to Ganache node. I remove and reinstall MetaMask it works but just for the first time.

Here is the error I get:

inpage.js:1 MetaMask - RPC Error: Error: [ethjs-rpc] rpc error with payload {"id":3361422499219,"jsonrpc":"2.0","params":["0xf9014c808504a817c800834c4b409445fc7fd9c34974d3263666ae77d5bb763498be4280b8e4d2609515000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000a688906bd8b000000000000000000000000000000000000000000000000000000000000000000004616572650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035344460000000000000000000000000000000000000000000000000000000000822d46a0e08cd386422975641b67ee41f37509acee96a310d13d21fb3091ad9f4487d178a03ed667b7be4af74b26cf07cf4b83cf9c852bd6fa1b70cc9e60a985fdf92038b4"],"method":"eth_sendRawTransaction"} [object Object] Objectcode: -32603message: "Error: [ethjs-rpc] rpc error with payload {"id":3361422499219,"jsonrpc":"2.0","params":["0xf9014c808504a817c800834c4b409445fc7fd9c34974d3263666ae77d5bb763498be4280b8e4d2609515000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000a688906bd8b000000000000000000000000000000000000000000000000000000000000000000004616572650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035344460000000000000000000000000000000000000000000000000000000000822d46a0e08cd386422975641b67ee41f37509acee96a310d13d21fb3091ad9f4487d178a03ed667b7be4af74b26cf07cf4b83cf9c852bd6fa1b70cc9e60a985fdf92038b4"],"method":"eth_sendRawTransaction"} [object Object]"stack: "Error: Error: [ethjs-rpc] rpc error with payload {"id":3361422499219,"jsonrpc":"2.0","params":["0xf9014c808504a817c800834c4b409445fc7fd9c34974d3263666ae77d5bb763498be4280b8e4d2609515000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000a688906bd8b000000000000000000000000000000000000000000000000000000000000000000004616572650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035344460000000000000000000000000000000000000000000000000000000000822d46a0e08cd386422975641b67ee41f37509acee96a310d13d21fb3091ad9f4487d178a03ed667b7be4af74b26cf07cf4b83cf9c852bd6fa1b70cc9e60a985fdf92038b4"],"method":"eth_sendRawTransaction"} [object Object]"__proto__: Object
(anonymous) @ inpage.js:1

**Comment by tmashuang** [comment]
Try Resetting your account in settings. Settings > Advanced > Reset Account.

**Comment by akefhabbal-qu** [comment]
It worked.
Thanks.
