### ISSUE TITLE
Metamask Extension causes massive CPU heating on Brave browser - Mac OS Catalina 10.15.3

### ISSUE THREAD

**Issue by maxenceC** [MetaMask/metamask-extension#8331]
**Describe the bug**

On Brave browser Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit) with Mac OS Catalina 10.15.3

Metamask in background (not actively used) is often eating up massive amount of CPU power, I have to manually kill the extension 

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Start Brave browser Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit) 
2. Navigate the web as you would usually do, with or without using Metamask
3. After a while, the extension ends up eating a massive amount of CPU power, and I have to manually kill the extension using Mac OS activity monitor 

**Expected behavior**
The extension is expected to work without eating up all CPU power after a while

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Mac OS Catalina 10.15.3
 - Browser: Brave browser Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
- MetaMask version: 7.7.8

**Additional context (Error Messages, etc.)**

**Comment by tmashuang** [comment]
There is a older and more involved issue, #6547, that has more information on possible causes to this behavior. Please contribute any theories/information/confirmation of the root cause of 100% CPU utilization in that thread.
