### ISSUE TITLE
develop: "Expand view" in popup opens fullscreen UI in new window instead of new tab

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#8346]
As of very recently, the "Expand view" button in the popup has been opening fullscreen in a new window instead of a new tab.

**Comment by rekmarks** [comment]
This is happening because we use `extension.windows.create` instead of `extension.tabs.create`. When do we want to do one over the other?

- https://developer.chrome.com/extensions/windows#method-create
- https://developer.chrome.com/extensions/tabs#method-create

**Comment by whymarrh** [comment]
When did this change?

**Comment by Gudahtt** [comment]
I changed it accidentally in #8317
