### ISSUE TITLE
Feature - Hide empty accounts

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-extension#8361]
**What problem are you trying to solve?**
Remove clutter from MetaMask accounts UI.

**Describe the solution you'd like**
A "Hide empty accounts" toggle in "Settings/General". Alternatively, a "Hide dust accounts" in "Settings/General" that allows the user to select a threshold of accounts he's not interested in working with.

**Additional context**
To avoid hiding newly created accounts, an account should be considered empty if they have 0 wei AND they've participated in at least one transaction.

**Comment by Gudahtt** [comment]
Thanks for the suggestion! I think this need is better met by something like #5078 though. That way users can still hide accounts at-will, but only by explicitly saying they want to hide them. I fear that any automatic hiding would be too confusing for users.

I'll close this for now, but feel free to suggest this again on our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests) if you feel it's warranted.
