### ISSUE TITLE
Feedback: Add a warning to MAX send for ETH

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-extension#8375]
**What problem are you trying to solve?**
No ETH funds left to pay for gas fee for sending ERC20 tokens when emptying a wallet.

**Describe the solution you'd like**
Based on feedback shared by a user, we may need to add a warning when using the MAX button to send all ETH (#6488), so users trying to empty an address completely won't spend all ETH funds without knowing they should either send all ERC20 tokens first or at least left enough ETH funds for paying for tokens sends.

**Comment by kumavis** [comment]
maybe a "sweep all assets" feature is whats actually desired

**Comment by rdymac** [comment]
Right there in the Send ETH window?

If it is not added there (or the warning as suggested above) you may end up without ETH funds by the time you go to the sweep all assets option.

**Comment by bschorchit** [comment]
Closing in favor of: https://github.com/MetaMask/metamask-extension/issues/8415
