### ISSUE TITLE
Check if user confirmation required in Metamask pop up

### ISSUE THREAD

**Issue by MepuDuaH** [MetaMask/metamask-extension#8414]
How can I check if user action such as 'Sign'/'Transaction confirmation' required from a user?  I want to handle it to prevent duplication of Sign request or something.

**Comment by Gudahtt** [comment]
Thanks for the question! We require confirmations for any signing, for sending transactions, for decrypting messages, and for authorizing a connection with a dapp. See our documentation for more examples: https://docs.metamask.io/

If you have further questions, I'd recommend asking them in our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics).
