### ISSUE TITLE
Data user is signing is cut off in MetaMask request, no overflow

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#8452]
**Describe the bug**
When a user is asked to sign data, the data is cut off on the right with no way to see/verify the full contents of what the user is signing. 

**To Reproduce (REQUIRED)**
1. In an installed and logged-into instance of MetaMask, connect to mainnet (required due to [issue #8448](https://github.com/MetaMask/metamask-extension/issues/8448)). 
2. Visit https://danfinlay.github.io/js-eth-personal-sign-examples/
3. Click "sign typed data v4".
4. View:
![screenshot](https://user-images.githubusercontent.com/563406/80531006-e1bb3280-8967-11ea-86d0-feae1fd445c4.png)
5. Note that the last displayed character is cut off on the right (probably under the vertical scroll bar). 
6. Use that vertical scroll bar to go down all the way (it is such a little difference that one questions requiring vertical scroll at all) and find that the only thing revealed is a horizontal scroll bar (not even Cancel/Sign buttons!):
![screenshot](https://user-images.githubusercontent.com/563406/80531213-3bbbf800-8968-11ea-84ec-7629c241e255.png)
7. Use the horizontal scroll to go right all the way (it is such a little difference that one questions requiring horizontal scroll at all) and find that the only thing revealed is one additional character of content and an ellipsis:
![screenshot](https://user-images.githubusercontent.com/563406/80531357-7f166680-8968-11ea-8349-6c61e8c0e63b.png)
8. Only by using the mouse scroll wheel can you see cancel/sign buttons:
![screenshot](https://user-images.githubusercontent.com/563406/80531491-bbe25d80-8968-11ea-872b-e98d501eacf6.png)
If you don't have a scroll wheel on your mouse, too bad, you can't sign.  The arrow keys don't go down that far.  End and PgDn and even Enter don't do anything. 
9. If, in step 6 you instead tried to resize the window to show more, it's also not very functional in extending this, picking one of the two following displays depending on width:
![screenshot](https://user-images.githubusercontent.com/563406/80531656-f8ae5480-8968-11ea-9d98-e7863f58b73c.png)
or 
![screenshot](https://user-images.githubusercontent.com/563406/80531698-0663da00-8969-11ea-9fcf-d0c2a5066557.png)
10. Cancel the signature and edit bundle.js:335 to lengthen the message, adding text after "Hello, Bob!" such as "This is a test message to see how much is displayed before secret data you cannot see and do not agree with is included." The start of the message looks innocuous enough but the rest is cut off.  The user has no way of knowing what they are really signing.
11. On the same page, click "sign typed data".  This presents an older view but at least one allowing text wrap: 
![image](https://user-images.githubusercontent.com/563406/80533424-99057880-896b-11ea-9fc8-612940486b56.png)
12. If you sign a message using this function without a version in order to improve the UI, and then try to recover the signing account using `recoverTypedSignature()`, you'll encounter [this error](https://github.com/MetaMask/eth-sig-util/issues/38), for which the [linked documentation](https://docs.metamask.io/API_Reference/Signing_Data/Introduction) is HTTP 404.
13. If you magically discover the [correct documentation link](https://docs.metamask.io/guide/signing-data.html), you'll see incompatible statements about v3 and v4 both being current (the content is basically a copy from one section to the next).  
14. The bottom of the page makes a claim to the content having been recently updated, but clicking on the [github link](https://github.com/MetaMask/metamask-docs/edit/master/packages/docs/dist/guide/signing-data.md) in the lower left to try to identify what those changes are gives another 404. 
15. If you can magically find the [corrected version of that link](https://github.com/MetaMask/metamask-docs/blob/master/docs/guide/signing-data.md), you'd see that recent changes just added some blank lines in the source.
That page links to a [September 2018 blog post](https://docs.metamask.io/guide/signing-data.html#sign-typed-data-v4) which is a bit outdated and basically just recommends using the version with the cut-off contents. 
16. Using eth_sign on that page results in an intentionally-scary warning (again with an annoying vertical scroll bar that covers content without much useful functionality): 
![screenshot](https://user-images.githubusercontent.com/563406/80536182-fc91a500-896f-11ea-9e1f-a2ba99c623d1.png)
with the [learn more](https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290) link going to an outdated 2017 article by @danfinlay headed with "This is a very early stage feature, and the exact implementation may be subject to change! Do not use this method for production applications that you’re not able to update should the API change in the future!" 
12. [Issues](https://github.com/MetaMask/metamask-extension/issues/4549#issuecomment-396341054) [discussing](https://github.com/MetaMask/metamask-extension/issues/2826) that warning point to an [article](https://consensys.zendesk.com/hc/en-us/articles/360004427792#) that requires a Consensys sign-in to access; a referenced [Twitter thread](https://twitter.com/radix42/status/905960763075977216) does not address the technical question (nor is it framed as doing so).  

**Expected behavior**
There is a well-documented way to ask users to sign data and allow them to see the full contents of what they are signing, in human-readable format.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 81.0.4044.92 (Official Build) (64-bit)
 - MetaMask Version: 7.7.8

**Comment by Gudahtt** [comment]
Thanks for the detailed report!

The problem of text being cut off horizontally is addressed by this pre-existing issue: #7921. Do you think that wrapping the text would be an adequate solution? I'm concerned that it might be nearly as unreadable even if the text was wrapped :thinking: 

The issue of having to scroll to see the buttons was brought up in #7962 - I think that problem is adequately covered there.

**Comment by bschorchit** [comment]
Closing this as the listed issues have been addressed.
