### ISSUE TITLE
Handle Ledger "contract data not enabled" config issues more gracefully

### ISSUE THREAD

**Issue by moazzamak** [MetaMask/metamask-extension#8498]
**Describe the bug**
Attempting to interact with smart contracts without setting "allow contracts" setting in ledger nano s completely breaks metamask. Only the webwallet prompt shows up to reject/confirm instead of the prompt showing up on the hardware wallet itself. The contract interaction caused an issue that cascaded to the point where the entire wallet become "locked" and no ether/erc20 tokens could be sent and had to be rescued using ledger live.

**To Reproduce (REQUIRED)**
1. Connect the ledger nano s.
2. Ensure that contracts are not allowed in ledger nano s settings for ethereum app
3. Interact with any contract (I used https://stake.elrond.com/stake, need to have some ether and elrond erc20 tokens)
4. See: extension tries to sign instead of HW wallet
5. Try to make any normal ether/erc20 transactions.
6. See confirm/reject prompt on extension instead of HW wallet.

**Expected behavior**
Prompt to approve/reject should be shown in HW wallet and metamask extension should only wait for approval. If possible the "no contracts" setting should be detected and handled correctly so follow up transactions can work. 

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Ubuntu 18.04
 - Ledger Nano S Firmware version 1.6.0
 - Chromium 81.0.4044.122
 - 7.7.6

**Additional context (Error Messages, etc.)**

**Comment by jennypollack** [comment]
"Attempting to interact with smart contracts without setting "allow contracts" setting in ledger nano s completely breaks metamask."

If you try to use your ledger without enabling contracts I don't think we should be expecting it to work, please correct me if I'm misunderstanding. 

Hey @moazzamak I'm going to rename this issue to "Handle ledger config issues more gracefully"

**Comment by moazzamak** [comment]
Yes I understand that. But It should still let me send out my eth or erc20 tokens which was impossible. That's why I ended up using ledger live software to rescue my funds since metamask couldn't do anything.

**Comment by dpazdan** [comment]
Closing as no one has added anything to this in over a year.  MetaMask functions fully with Ledgers that have contract data enabled.
