### ISSUE TITLE
Can't connect to .onion rpc address

### ISSUE THREAD

**Issue by akhavr** [MetaMask/metamask-extension#8499]
**Describe the bug**
Metamask Extension can't connect to `.onion` RPC URL using Tor browser.  

**To Reproduce (REQUIRED)**
1. Go to Settings/Networks
2. Click on "Add Network"
3. Fill any "Network Name" and `http://7pogiqjlwxj67lqe.onion:8545` in "New RPC URL"
4. Click on "Save"
5. See the error popup 
![image](https://user-images.githubusercontent.com/2120/80909939-f6ffda80-8d34-11ea-8438-e22bb6a2f36f.png)
6. See the error in the console

```
Object { name: "AssertionError", actual: false, expected: true, operator: "==", message: "NetworkController - Unknown rpc type \"http://7pogiqjlwxj67lqe.onion:8545\"", generatedMessage: false, stack: "setProviderType@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:31214\n[63]</t.exports/<@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:104642\n[452]</c.prototype.apply@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1058473\n[452]</c.prototype.handle@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1058171\n[458]</</s.prototype.handle@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1061864\n[458]</</s.prototype.write@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1061769\nm@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:2267807\nh@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:875603\n[363]</s.prototype.emit@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:878589\n_@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:2262646\nw@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:2262461\n[1237]</</v.prototype.push@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:2263272\n_write@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:2108016\nv@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:2275398\n[1239]</</g.prototype.write/s<@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:2278514\n[1239]</</g.prototype.write@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:2278541\nm@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1489571\nh@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:875603\n[363]</s.prototype.emit@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:878589\n_@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1484374\nw@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1484189\n[613]</</v.prototype.push@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1485000\n[609]</</o.prototype._onMessage@moz-extension://162e6dcd-61fa-4101-b991-d5bc275d2110/background.js:1:1478930\n" }
```

**Expected behavior**
Expected to connect via Tor to the RPC URL and work as usual.

**Browser details (please complete the following information):**

 - OS: Ubuntu
 - MetaMask Version 7.7.8
 - Tor Browser v 9.0.9 (based on Mozilla Firefox 68.7.0esr) (64-bit)
 - Ubuntu, if it's relevant

**Comment by kumavis** [comment]
@akhavr we dont officially support tor browser or onion rpc addresses, but i dont see any reason this shouldn't work.

**Comment by kumavis** [comment]
there seems to be some mixup between `setRpcTarget` `setProviderType`

**Comment by kumavis** [comment]
@whymarrh are you familiar with a recent `setRpcTarget` `setProviderType` mismatch bug?

**Comment by whymarrh** [comment]
On 7.x? I don't know of anything that would be have been released.

What do you mean by mismatch?

**Comment by kumavis** [comment]
@whymarrh seems we're calling `setProviderType` when we should be calling `setRpcTarget`
based on the error message `NetworkController - Unknown rpc type <url>`

**Comment by akhavr** [comment]
Is there anything I can do to speed this up?  I have some development experience, but not with this stack.

**Comment by lekanovic** [comment]
I was was just looking for Tor and onion address support. Has anyone tested if the work or is this still an issue?

**Comment by lekanovic** [comment]
Hi @akhavr do you have any tutorial on how you setup Geth to run behind Tor, do you need nginx?

**Comment by akhavr** [comment]
> Hi @akhavr do you have any tutorial on how you setup Geth to run behind Tor, do you need nginx?

No, `geth` is connected to Ethereum mainnet via clearnet, just exposes its RPC interface via Tor, as usual.  If you need instructions re tor servers, check Tor docs and your `/etc/tor/torrc`.  They have plenty examples.
