### ISSUE TITLE
Metamask only resolve ENS on mainnet

### ISSUE THREAD

**Issue by xmaysonnave** [MetaMask/metamask-extension#8556]
Following the late January 2020 merged PR:

https://github.com/MetaMask/metamask-extension/pull/7944

Metamask is not able anymore to redirect to the appropriate ENS registry other than Mainnet when a user input an eth domain in the browser address bar.

The main argument was to say that some users are confused. I stressed the point that this argument is not necessary valid as the user at some point changed their network. Don't forget either that now the situation is even more confusing because a **This site can’t be reached** page is displayed with no user warning as well. 

To improve the situation the previous behaviour needs to be restored. Metamask needs to redirect to the registries supported by ENS (Mainet, ropsten, rinkeby and goerli) when a user input an eth domain in te browser address bar. To avoid any user confusion I see two ways.

The first proposal could be a simple warning dialog box but it implies a user interaction.

The second proposal a little bit more sophisticated. It could be to tune the current **Metamask is querying ENS** temporary html page with a network title and coloring the displayed image with the default color associated with each network  displayed in the Metamask browser extension Network page.

Thanks

**Comment by makoto** [comment]
Hi. Makoto from ENS team here.
In terms of restricting to ENS on mainnet , I wasn't aware of it so my recent PR https://github.com/MetaMask/metamask-extension/pull/14526 actually support other testenets such as Ropsten, Rinkeby, and Goerli. For other chains (eg: L2, Polygon, Gnosis chain etc), what we suggest is to have separate "Read only" connection to Mainnet and use it as a canonical data source which  I described at https://medium.com/the-ethereum-name-service/how-to-support-ens-for-multi-chain-dapps-b0a7ff043d77 even when connected to the different chain.

**Comment by rsodre** [comment]
@makoto , what about http redirection to the content hash?

If we type https://ide.hypercartridge.eth/ when connected to mainnet, it will successfully resolve the content hash
But on Goerly, just a "This site can’t be reached" error.
MetaMask should resolve too.
