### ISSUE TITLE
Inform dApps that transaction are speed up

### ISSUE THREAD

**Issue by pakokrew** [MetaMask/metamask-extension#8565]
**What problem are you trying to solve?**

I am a dApp developer, where users can call contracts via metamask. When they do, I get as a result a transaction hash, which I watch, waiting it to be confirmed to tell my user that this step is done and continue the process.

When a user speedup a tx, and if that works, they will see in metamask that the tx is confirmed, but the dApp will be stuck waiting that the initial hash is mined, and never knew that the tx was replaced. 

This can lead to UI inconsistency and even breaks flow if actions after the tx are required from the user.

**Describe the solution you'd like**

I would like that the injected provider sends an event telling that the transaction with hash X was replaced by transaction with hash Y, so I can wait that this one is mined and update my UI accordingly.

**Comment by wjmelements** [comment]
This probably needs an EIP. If there was an ethjsonrpc for getting an account's transaction by nonce you could poll it instead of polling by transaction hash, and then this becomes the dapp's responsibility. Speedups and replacements don't necessarily originate in Metamask wallet either.

**Comment by pakokrew** [comment]
For sure that should respond to some specification that different wallets would agree on. 

I posted the idea here because Metamask is the only wallet I know which proposes this feature, so I thought it could ignite the discussion and spec. 

I think emitting an event could be great, but polling by account/nonce could be a solution also, but would be less explicit and require more analysis to understand what is happening.

**Comment by Gudahtt** [comment]
Thanks for the suggestion! Somebody has since written an EIP for this: https://eips.ethereum.org/EIPS/eip-2831

I'm going to close this in favour of #9174, which tracks the implementation of this EIP.
