### ISSUE TITLE
Custom networks cannot be edited or deleted

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-extension#8566]
The menu label states "Add and **edit** custom RPC networks": https://share.getcloudapp.com/5zu1jZPj

But the network cannot be edited nor deleted since all options are disabled: https://share.getcloudapp.com/p9u7egQy

**Browser details (please complete the following information):**
 - OS: OSX
 - Browser: Version 81.0.4044.138 (Official Build) (64-bit)
 - MetaMask: 7.7.9

**Comment by PatrykLucka** [comment]
Looks like you tried to edit default localhost network. This one is also not editable. Only custom - added by user - networks are editable. I created PR, which hopefully makes it more clear.

**Comment by Gudahtt** [comment]
Since the UI for this was improved in #9269, I'm going to close this for now and consider it as solved. As @PatrykLucka explained, this was intended behaviour, not a bug.
