### ISSUE TITLE
Account with thousands of transactions loads slowly

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#8572]
It takes upwards of 15 seconds for my account to appear after I click on the metamask fox icon. I believe this is because my account has 2092 transactions. It was not this slow when I had only 1000 transactions.

**Comment by wjmelements** [comment]
When I scroll, it goes all the way to nonce 1870. I do not need that to load eagerly.

**Comment by whymarrh** [comment]
Thanks for bringing this up! We've addressed this in the upcoming release (v8).

**Comment by wjmelements** [comment]
Thank you

**Comment by wjmelements** [comment]
@whymarrh The performance has actually gotten much worse in v8.
