### ISSUE TITLE
Etherscan loading so slow in my location

### ISSUE THREAD

**Issue by aries9304** [MetaMask/metamask-extension#8573]
**What problem are you trying to solve?**
I can't use etherscan in China, it's extremely slow and always loading. The [View on Etherscan] just don't work normally here.

**Describe the solution you'd like**
Maybe we can add a new explorer as replacement.
https://tokenview.com/en/search/{txid}
**Additional context**
![image](https://user-images.githubusercontent.com/45411102/81631348-3a93cc00-943a-11ea-8fdd-6ebb6b34ba0d.png)

**Comment by jennypollack** [comment]
@aries9304 you can use the custom RPC feature to create a network with your choice of block explorer, see here: https://metamask.zendesk.com/hc/en-us/articles/360043227612-How-to-add-a-custom-Network-RPC-and-or-Block-Explorer
and the settings of the current mainnet for config values
