### ISSUE TITLE
Cross extension web3 APIs

### ISSUE THREAD

**Issue by Jack-Works** [MetaMask/metamask-extension#8593]
Now Metamask provides `web3` on the web page for dapps, but it is not accessible from other browser extensions.

Does MetaMask public it's JSON RPC API at the browser extension level to enable cross extension communication? I didn't see that in the documentation.

Our use case:

[Maskbook](https://github.com/DimensionDev/Maskbook) is a browser extension that allows encryption on Facebook and Twitter. The following screenshot is fund [Gitcoin grants](https://gitcoin.co/) in Maskbook. Now Maskbook has a built-in eth wallet but it will be nice to call MetaMask to do the payment.

![image](https://user-images.githubusercontent.com/5390719/81895233-5f2ba780-95e4-11ea-8cb4-0432718832d6.png)

**Comment by jennypollack** [comment]
See: https://github.com/MetaMask/metamask-extension-provider/issues/3#issuecomment-614382111
and https://github.com/MetaMask/metamask-extension-provider
Basically it should work, but none of us have had the time to test it ourselves yet - would be awesome if you could give it a go and let us know!

**Comment by rekmarks** [comment]
Hi @Jack-Works, one more thing: you should stop using `window.web3`, as we will stop injecting it later this year. You should use `window.ethereum` instead, and bring your own library dependencies. We recommend `ethers`, but you can also bring your own `web3`.

**Comment by Tedko** [comment]
Updates on our side:

![Clipboard - 2020年8月18日下午4点53分](https://user-images.githubusercontent.com/6687437/90494207-d3db2880-e175-11ea-90e6-df990d3c7c01.png)

would be great if you have any idea on this https://github.com/MetaMask/extension-provider/issues/9 as well. Many thanks.
