### ISSUE TITLE
Contract creation pads gas

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#8597]
Version 7.7.9

Contract creation did not formerly pad gas. Now it does.

```
web3.eth.estimateGas({data:"0x60588060093d393df37f70a08231000000000000000000000000000000000000000000000000000000003d526040353d358060045231813d60203d60243d6020355afa5051036103e50291026103e8020460010160603510605357005b3d6000fd"},console.log)
71826
```
```
web3.eth.sendTransaction({data:"0x60588060093d393df37f70a08231000000000000000000000000000000000000000000000000000000003d526040353d358060045231813d60203d60243d6020355afa5051036103e50291026103e8020460010160603510605357005b3d6000fd"},console.log)
```
<img width="351" alt="Screen Shot 2020-05-14 at 4 37 18 PM" src="https://user-images.githubusercontent.com/799573/81996147-2fd76380-9601-11ea-91ab-ae46a74d8e43.png">

**Comment by Gudahtt** [comment]
Thanks for the report!

I thought we started buffering our gas estimates a long time ago :thinking: It seems to date back to [at least version 3.6](https://github.com/MetaMask/metamask-extension/commit/17b805c76ea3ea160bcb2560d2043581b54c4834), years ago. It's quite possible that that path was skipped or that the initial buffered gas estimate was overwritten somehow until recently, but I'm not aware of any change in behaviour like that.

Is this behavior undesirable? I'd like to understand better why this might be a problem. If you know of a recent-ish MetaMask version that didn't have this problem, that might help identify why this changed as well.
