### ISSUE TITLE
Transaction continually fails

### ISSUE THREAD

**Issue by jujomythree** [MetaMask/metamask-extension#8602]
**Describe the bug**
I am using the MetaMask wallet to swap tokens on Uniswap and the issue might be with Uniswap but I am not sure.

I have used Uniswap.io many many times with MetMask wallet and never had a problem swapping tokens. But the past 2-3 days I can not get a swap transaction to complete. I am trying to swap USDC for FOAM. Here is the transaction on Etherscan.

https://etherscan.io/tx/0x192cc66674785d05f21c54cef3f104baabb45fc3d67fa901ec370edcbce8d8d9

The transaction would hang for 12+ hours. I had to cancel the transaction a few times so that I could try again but it keeps failing.

Please let me know if you need any other details.

**To Reproduce (REQUIRED)**
1. I am connected to my MetaMask wallet and go to Uniswap.io
2. I setup what I want to swap (USDC for FOAM). I have enough USDC and ETH to make the swap
3. When I click the Swap button on Uniswap, the MetaMask confirmation popup window asks for confirmation.
4. I click the Confirm button and the transaction either hangs for 12+ hours or fails. 

**Expected behavior**
I expect to receive FOAM to my wallet as I have had successfully happen so many times in the past. 

**Screenshots**
Attached...

**Browser details (please complete the following information):**
 - OS: macOS Mojave version 10.14.6
 - Brave Browser Version 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
 - MetaMask Version 7.7.9

**Additional context (Error Messages, etc.)**
n/a

**Comment by jujomythree** [comment]
Here is the screenshot of my last failed transaction....

![Screen Shot 2020-05-16 at 10 22 36 AM](https://user-images.githubusercontent.com/65431830/82108228-af7b4480-975f-11ea-8741-681dad797eb8.png)

**Comment by jennypollack** [comment]
Hey @jujomythree please contact support@metamask.io and reference this ticket number, someone should be able to help you out!
