### ISSUE TITLE
Simple MetaMask with Cypress Tests For Simple Dapp

### ISSUE THREAD

**Issue by dotnetspec** [MetaMask/metamask-extension#8605]
**What problem are you trying to solve?**
I have a small, relatively simple dapp written in Elm which I'm E-E testing with Cypress. The most challenging part of the dapp is the MetaMask integration. Currently I have to use Rinkeby directly and therefore handle any MM integration testing 'manually', which is relatively slow, inefficient and ineffective.

**Describe the solution you'd like**
I would like to be able to configure, either with the help of a piece of software integration code and/or instructions (if that's all that's required), a test setup in Cypress that enables me, for eg., to automatically test against whether the MM wallet extension is locked/open/missing and simulated 'payments' etc. i.e. basic MM functionality. Cypress currently only explain how to find and integrate a Chrome extension like MM, but not how to actually use it in testing (https://docs.cypress.io/api/plugins/browser-launch-api.html#Usage)

**Additional context**
I can see from the other issues that you are working to enable Cypress integration and I expect there are many difficulties to address in the process. I found no matches for a search in Gitcoin against 'cypress'. Is there a short term solution/workaround for the relatively limited test integration that I'm referring to or will I simply have to wait for a more comprehensive solution to become available?

**Comment by tmashuang** [comment]
Pretty sure you are going to be blocked by https://github.com/cypress-io/cypress/issues/1965. On a side note, I recommend looking to other driver testing frameworks such as Puppeteer, Playwright, Selenium, etc. for better support for testing with chrome extensions.
As this is not an issue directly effecting the usability, I am going to close this.

**Comment by dotnetspec** [comment]
Answered myself:
![mm connection](https://user-images.githubusercontent.com/27340988/82328443-76b6c600-9a12-11ea-926d-91afbb7ba416.png)
Easy when you happen to know ...
