### ISSUE TITLE
transaction dropped but still pending

### ISSUE THREAD

**Issue by fjremi** [MetaMask/metamask-extension#8606]
Hey, i see a lot of post for pending transaction but for me the transaction appear as dropped on Etherscan but still pending on metamask after 3 hours ! What can i do ?

ps : i send all my ETH to another wallet so i can't add more fees

**Comment by Gudahtt** [comment]
Thanks for the report! Are you still experiencing this issue? We fixed a few issues since you reported this that could result in transactions being stuck in "pending", so this may have already been fixed. Please let us know if you're still stuck, and whether you can reproduced this on the latest version of MetaMask.

**Comment by vistsvist** [comment]
> Спасибо за отчет! Вы все еще сталкиваетесь с этой проблемой? С тех пор, как вы сообщили об этом, мы исправили несколько проблем, которые могли привести к зависанию транзакций в состоянии ожидания, так что это, возможно, уже было исправлено. Сообщите нам, если вы все еще застряли, и можете ли вы воспроизвести это в последней версии MetaMask.

Good day! I have the same problem. Please, help me
Transaction Hash: 0x791fc007e32f7d20d058d0ba722ae1ab7a988a1d275405b86993f4e884fab92e

**Comment by vistsvist** [comment]
> Thanks for the report! Are you still experiencing this issue? We fixed a few issues since you reported this that could result in transactions being stuck in "pending", so this may have already been fixed. Please let us know if you're still stuck, and whether you can reproduced this on the latest version of MetaMask.

Good day! I have the same problem. Please, help me
Transaction Hash: 0x791fc007e32f7d20d058d0ba722ae1ab7a988a1d275405b86993f4e884fab92e

**Comment by vistsvist** [comment]
> Hey, i see a lot of post for pending transaction but for me the transaction appear as dropped on Etherscan but still pending on metamask after 3 hours ! What can i do ?
> 
> ps : i send all my ETH to another wallet so i can't add more fees

I would recommend resetting your account by following the instructions below.

Click the account icon on the top-right corner of Metamask
Select "Settings"
Select "Advanced"
Scroll down and click Reset Account


BE SURE TO SECURELY SAVE YOUR PASSWORD, SEED PHRASE AND PRIVATE KEYS(Imported accounts) BEFORE RESETTING.

One thing to keep in mind after resetting the account your transaction activity history may default to none. But you could always refer to etherscan.io transaction logs.

**Comment by candicewb** [comment]
I'm having the same issue and it's been 4 days. I just reset my account, but the pending monies haven't been credited to my wallet which should be roughly $300.00. Can someone please help

**Comment by syuukawa** [comment]
the Dropped transaction is still pending

**Comment by Prvi9** [comment]
Hi, I'm facing this issue as well. Kindly help!
0xd58869e1df7e4f2e40c744b49ed969da87e6a92be95331d50cfcda78922b88ef 

PS: I have the latest version / browser extn in edge. It happened after i was editing the gas, clicked save. and i think i was prompted 2nd time for confirmation. It was too late by the time i realized what happened. now even after status being dropped, my MM shows its pending and blocking my other transactions. Appreciate your prompt help here.

**Comment by RasVandoros** [comment]
Having the same issue! Transaction hash: 0xe3d8d820f4b1317f23df9d34756e712cce044f7da9f61ae3881cffda96b10bb6
Cant cancel either as my balance is lower than the pending transaction.

**Comment by jeltehomminga** [comment]
same issue here Transaction hash:  0x881D40237659C251811CEC9c364ef91dC08D300C

Not possible to use metamask anymore, because transaction stays on pending while it is dropped on etherscan

any solution yet?

**Comment by RasVandoros** [comment]
Resetting metamask did the trick for me!

**Comment by thatbeer** [comment]
i got the same problem too, try to swap busd to bnb and now it cost me almost 0.14 bnb for now pls help!!
0x78a3444430598d5fdabd55fd560c7b0cbe134f3cf1ca4adb4872d1d003ec5b7a

**Comment by fanatikhamsi** [comment]
> 0x78a3444430598d5fdabd55fd560c7b0cbe134f3cf1ca4adb4872d1d003ec5b7a

hi can i help you? i have done it before

this usdt banned address
https://etherscan.io/address/0xb89d8a7c56241b550A6f8a0938BBBB2E2fe3166F#tokentxns
and this withdrew transaction
https://etherscan.io/tx/0x8524cff923a3beaa7f654d98e6a0bcec0996de7158058b992df96ce7dafc1a74
