### ISSUE TITLE
UI broken after submitting incorrect password on reveal seed phrase screen

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#8626]
**Describe the bug**
If you submit the incorrect password on the screen for revealing your seed phrase, the keyring is no longer available to the UI. This results in various problems, including the account menu being empty.

[Here is a video of the bug](https://www.loom.com/share/ab5b9e6b9f9e4288b0fc456ccaf37fe0) (thanks @zctocm for recording this!)

**To Reproduce (REQUIRED)**

1. Navigate to 'Settings > Security & Privacy'
2. Click 'Reveal Seed Words'
3. Enter your password incorrectly
4. Check the account menu, and see that the accounts are no longer listed.

**Expected behavior**
The accounts should remain listed after entering your password incorrectly. Nothing in the UI should break in this scenario.

**Comment by yqrashawn** [comment]
Seems the underlying reason is that there's a call to `this.clearKeyrings()` [here](https://github.com/MetaMask/KeyringController/blob/c75d8350ab3659d2fb8b15a10fc9005142f6e8c3/index.js#L546).

Is there's any security concern if clear keyrings after decrypting the vault?

**Comment by Gudahtt** [comment]
@yqrashawn Good find! That's a good question - I don't think so but I'm not sure :thinking:.

Though that did give me another idea - perhaps what we want here is an new keyring controller method, `validatePassword` or something. `submitPassword` clears and unlocks the keyring, and that's just not what we want to do on the reveal seed phrase screen. A new method that would let us validate the password without those other steps would be much better.
