### ISSUE TITLE
Is there a way to detect when MetaMask extension is disabled by user?

### ISSUE THREAD

**Issue by thecircleoflifefree** [MetaMask/metamask-extension#8642]
When user disables MetaMask, window.ethereum is still exposed.

**Comment by rickycodes** [comment]
`window.ethereum` is _not_ exposed when the extension is disabled.

when the extension is enabled:

```
> window.ethereum
Proxy {_events: {…}, _eventsCount: 1, _maxListeners: 100, isMetaMask: true, _state: {…}, …}
```

when it is disabled it returns undefined:

```
> window.ethereum
undefined
```

it's possible another extension or script on the page is leaving it exposed?

**Comment by thecircleoflifefree** [comment]
No extension and no script. Just open any random webpage and do the console.log check for window.ethereum, whether disabled or enabled I get:

![mmissue](https://user-images.githubusercontent.com/26904626/83059715-930cc100-a017-11ea-87b9-fc26f56f8c2a.png)

Any other suggestion? Please reopen issue.
