### ISSUE TITLE
Private key to seed phrase

### ISSUE THREAD

**Issue by ERC20s** [MetaMask/metamask-extension#8645]
I had 5 ETH address'..
But I only saved 3 of the private keys..

Is there a way of finding out the seed phrase using multiple private keys?

**Comment by Gambolr** [comment]
If a feature like this could be built then maybe it can be used in the wallet as well..

**Comment by Gudahtt** [comment]
No, I don't believe this is possible. Key derivation is meant to be a one-way operation; the accounts are generated from the seed phrase, but you can't go backwards and generate the seed phrase from the accounts.

Please ensure you have your seed phrase backed up in the future! Backing up your seed phrase is _critical_ to safely using MetaMask.

**Comment by ERC20s** [comment]
So a seed phrase generation is completely random?
No way of reverse engineering it..
Anywhere I can look into this further?

**Comment by Gudahtt** [comment]
Yep! The standard we rely on for seed phrases is called BIP-39, and you can read about it here: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

Also relevant is BIP-32, which is more about how we generate and use these underlying keys: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
