### ISSUE TITLE
Display full balance of ETH and Tokens

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#8652]
**What problem are you trying to solve?**
Some users have a small fraction of ETH or a Token that is not displayed by our existing interface.  

We currently only display a balance to 3 decimal places.  Some tokens such as wBTC are high value, so many users have small fractions of these.  When they check their balance they are suprised to see 0.000 which makes them think either the extension isn't working, they lost their funds or it was not recieved.

**Describe the solution you'd like**
Display all token values regardless how small, and then offer users the option to "ignore past 3 decimals" or something like this under settings.

related to support inquiry: 36057

**Comment by brad-decker** [comment]
@dpazdan this is now resolved as of #9056 and 9.0.6
