### ISSUE TITLE
As a Metamask user, Id like to default every tx to fast mode, so i dont have to do it every tx or have my all txns slow each other down.

### ISSUE THREAD

**Issue by owocki** [MetaMask/metamask-extension#8658]
**What problem are you trying to solve?**
As a Metamask user, Id like to default every tx to fast mode, so i dont have to do it every tx or have my txs slow.

**Describe the solution you'd like**
Somewhere in settings that I can default all my txn's to 15 second confirmations

**Additional context**
The gas fee issues in Ethereum really slow down my usage of dApps :/

**Comment by Gudahtt** [comment]
Thanks for the suggestion! I'm closing this as a duplicate, as we're already tracking this request under #7425
