### ISSUE TITLE
Tx History View More button renders with fewer than 10 txs.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#8686]
Seems that the View More Button with render the first 10 txs, but there's no minimal limit that renders with. Such as if only an account's history has fewer than 10 txs it will still render the View More button.

<details>
<summary>Issue with View More Button with only 1 transaction</summary>
<img src='https://user-images.githubusercontent.com/13376180/83174338-1b9a6880-a0cf-11ea-808a-e02c8fd21cc3.gif'>

</details>

**Comment by brad-decker** [comment]
will be fixed in #8241

**Comment by brad-decker** [comment]
will be fixed in #8673
