### ISSUE TITLE
Settings > Alerts toggles grid shifting

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#8687]
Issue with grid layout shifting on Alerts page when toggling multiple ON/OFF switches

<details>
<summary>Alerts page grid toggle shifting</summary>
<img src='https://user-images.githubusercontent.com/13376180/83174279-058ca800-a0cf-11ea-9639-fd87c1bea950.gif'>

</details>

**Comment by Gudahtt** [comment]
I am responsible for this problem; I wasn't sure how much room to leave for the "ON/OFF" labels, as they might be fairly long in other languages (e.g. For `es_419`: `Activada` and `Desactivado`). So instead the column width is dynamically sized, meaning that it changes when all toggles are "ON".

I'm sure we could find a way to fix this without setting the width statically 🤔
