### ISSUE TITLE
Issue with Txs being labeled as dropped but still pending

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#8688]
**Describe the bug**
(Needs addtional verification)

At the time of tx submission the "Safe Low" gas price from EthGasStation was 30gwei. Sent a tx with 25gwei to ensure a fairly moderate wait time, but the tx status was updated to dropped after losing focus in the extension view and reopening and/or after some time.

**Screenshots**
<details>
<summary>Screenshot of Etherscan and tx</summary>
<img src="https://user-images.githubusercontent.com/13376180/83175649-10e0d300-a0d1-11ea-8930-fa898b77bf94.png"/>
</details>

**Additional context (Error Messages, etc.)**
Possibly widened the errors that can allow the tx status to update to dropped. 
Will updated in the comments with additional info on the issue.

Looks `eth_sendRawTransaction` is calling twice. The first will respond with the tx hash, and the second will respond with a `known transaction` error and thus will proceed to set the tx status to dropped. In prod, it seems the known transaction error does not update the status to dropped.

**Comment by whymarrh** [comment]
I'll try and repro this as well.

**Comment by tmashuang** [comment]
Sending a Rinkeby tx with 0.1 gwei gas price should delay the tx from being mined on a testnet long enough to trigger the tx status update to dropped.

**Comment by Gudahtt** [comment]
I was unable to reproduce this after the changes introduced in #8824. I only tried once though. Please re-open this if you can still repro this @tmashuang

**Comment by tmashuang** [comment]
Unfortunately, #8824 didn't solve the issue. Still reproducible with the steps able on all networks, when txs are stuck behind high gas prices.
