### ISSUE TITLE
Rationalize media queries

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-extension#8711]
Our CSS media queries are used to apply different styles to the popup/notification UI vs. the fullscreen UI.

Mostly, we use `@media screen and (max-width: 575px)` to accomplish this. There are a number of questions about this:

- Why 575px?
- In some places, it's 576px. Why?
- We often set element `height` values based on the result of `max-width` queries. Should we be using `max-height` instead?

Ref: #8707

**Comment by brad-decker** [comment]
@georgewrmarshall could you review this, re-label as necessary or close :)

**Comment by georgewrmarshall** [comment]
@eriknson I've been wondering the same "why 576px??" we have standardized the current media queries in the app and are now staged to update them.

Reference issues:
https://github.com/MetaMask/metamask-extension/issues/13045
https://github.com/MetaMask/metamask-extension/issues/15057

Closing as we can will address future media queries in another issue
