### ISSUE TITLE
Speed up transaction not showing when multiple hardware wallet used

### ISSUE THREAD

**Issue by gwenvador** [MetaMask/metamask-extension#8727]
**Describe the bug**
I have 2 ledgers with a pending transaction on each one. I can only speedup the oldest transaction on the first ledger. There is no speedup button on the transaction of the second ledger.

**To Reproduce (REQUIRED)**
Do a transaction with low gas fee on hardware wallet 1.
Connect hardware wallet 2
Do a transaction with low gas fee on hardware wallet 2.
The speedup button is only available on transaction from hw 1 and not hw2. 

**Expected behavior**
We should be able to speedup connection on different hardware wallet. I suspect as metamask does not support multiple hardware that it is only taking the oldest transaction regardless this is different hardware.

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: Ledger Nano S Firmware version 1.12.12
 - Browser : Brave 1.9.76
 - MetaMask Version : 7.7.9

**Comment by miranda76** [comment]
Need help atull

**Comment by dpazdan** [comment]
I believe clicking into a submitted transaction under activity will present you with a speed up option now.  This issue is being closed to the length of time without others reproducing it.
