### ISSUE TITLE
Add warnings and information about loose accounts on restore seed page

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#8729]
**What problem are you trying to solve?**
Some users are resetting their password to keep their wallet safe.  By doing this, they lose their loose accounts.

**Describe the solution you'd like**
Add a clear warning at the top of the page stating (Restoring from a seed phrase will only restore accounts tied to it, if you manually imported a private key or json file in the past, those will have to be[ imported manually](https://metamask.zendesk.com/hc/en-us/articles/360015489331-Importing-an-Account) again.  Make sure you have those keys backed up before proceeding!)

![image](https://user-images.githubusercontent.com/16330048/83663170-1ab17d00-a58e-11ea-967f-679476436f22.png)

**Comment by dpazdan** [comment]
reference support case: 37375

**Comment by jakehaugen** [comment]
Can we detect if users have imported accounts? My dilemma is trying to make sure the user knows if that warning is relevant for them specifically. 

If we can detect imported accounts, the ideal UX would be to show the warning and allow them to export them right from this screen. Then, after they've done that it would allow them to complete the process. Maybe like a two-step process that they could skip if they wanted to. 

That may be more work than we want to do right now but  may be worth exploring.

**Comment by rekmarks** [comment]
@jakehaugen We can detect imported accounts. IMO, we should only allow imported accounts to be exported if their current password has been entered and the extension is unlocked, regardless of whether they can remember their seed phrase or not.

Regarding the amount of work required for a two-step process, it'd be nice to just get up a warning for now, but I agree that we should pursue the two-step process in the longer-term. It's not a huge change once we do go for it.

**Comment by rekmarks** [comment]
To follow up on my previous comment, the screen shown in the original issue comment cannot support a two-step flow, unless the password is also entered.

Perhaps, @jakehaugen, what you're suggesting needs to live inside a "reset password" form accessed via settings? We could expose it in the aforementioned screen too, but the user would have to enter their password.

**Comment by jakehaugen** [comment]
> we should only allow imported accounts to be exported if their current password has been entered and the extension is unlocked, regardless of whether they can remember their seed phrase or not.

I agree with the above.

> what you're suggesting needs to live inside a "reset password" form accessed via settings? We could expose it in the aforementioned screen too, but the user would have to enter their password.

Yes, I think you're right. For the specific use case where this warning is relevant having this inside "settings" would make sense. 

Attached is a mock-up for the immediate change that includes the warning. I'm suggesting linking to a second article from "back up your keys" (https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-Export-an-Account-Private-Key).

Open to copy changes if anything seems unclear. 

<img width="1279" alt="restore-account-imported-accounts-warning" src="https://user-images.githubusercontent.com/11967476/84917715-e903e000-b07c-11ea-9a9a-fb8e96ce2ce8.png">

**Comment by rekmarks** [comment]
@jakehaugen this is great! I'll ping you on the PR when it's up.

Do you want to create an issue for the two-step form?

**Comment by jakehaugen** [comment]
Created the new issue here: https://github.com/MetaMask/metamask-extension/issues/8855

**Comment by bschorchit** [comment]
Closing this in favor of https://github.com/MetaMask/metamask-extension/issues/13474 . We'll also implement the new design for this flow soon.
