### ISSUE TITLE
gas estimation in Metamask

### ISSUE THREAD

**Issue by cmli93** [MetaMask/metamask-extension#8771]
I am new to Metamask. Can someone tell me how MetaMask compute default gasLimit?

**Comment by Gudahtt** [comment]
Great question! We compute the default gas limit by calling `eth_estimateGas`, then adding a buffer to that for safety in case the estimate was off (it gets multiplied by 1.5). If `eth_estimateGas` fails, we use the block gas limit instead as a fallback. You can find the code for this here: https://github.com/MetaMask/metamask-extension/blob/52d25f0df864d6cd62ff1bead02e919969b32bff/app/scripts/controllers/transactions/tx-gas-utils.js#L32

If you have any further questions, please feel free to ask them in our [Community Forum](https://metamask.zendesk.com/hc/en-us/community/topics).
