### ISSUE TITLE
Replacing a transaction with a given nonce does not work.

### ISSUE THREAD

**Issue by LefterisJP** [MetaMask/metamask-extension#8782]
**Describe the bug**
I am trying to replace a pending transaction with a completely new one. I am using the feature of metamask to specify the nonce of the transaction in order to achieve this. I have used this feature successfully in the past but now it no longer seems to work.

Any help trying to debug this issue is appreciated.

**To Reproduce (REQUIRED)**

1. Go to any Dapp (I used Oasis for makerdao vaults)
2. Initiate a new transaction.
3. In the metamask prompt choose a given nonce. I chose the same nonce as the current pending transaction from the account
4. Edit gas
5. Press submit
6. Nothing happens - the transaction never seems to be propagated and never appears on etherscan.

**Expected behavior**
I expect a new transaction to be sent with the same nonce as the pending one, essentially replacing the old one.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: ArchLinux 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux
 - Hardware Wallet: None
 - Browser: Brave -- Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) unknown (64-bit)
 - MetaMask Version: 7.7.9

**Comment by LefterisJP** [comment]
Some more info.

I think it may be due to the transaction I submit with the same nonce having to interace with the same contract. A MakerDAO DSProxy contract that controls all vault activities.

![2020-06-13-013226_431x709_scrot](https://user-images.githubusercontent.com/1658405/84553889-c177e500-ad15-11ea-8a0e-b39d6c68b4f6.png)

In the screenshot above you can see. Up to the "Speed up this transaction" part all was well. But since then I have been trying to replace it with a different one with the same nonce, nothing happens and this is how it looks in the UI.

**Comment by LefterisJP** [comment]
I ended up canceling the above transaction (essentially metamask made a simple 0 value transfer to SELF).

Right after that every new transaction I make does not have the "speed up" button option.

**Comment by DanoCoins** [comment]
If it makes you feel better I have stopped using Metamask on Brave.  I sped up the some of transactions and it still shows the transactions pending. Yet when I look at Chrome or etherscan it shows them complete.  Just ran in to this googling for a solution.

**Comment by dpazdan** [comment]
Hi there,
Can one of you send us your state logs to support@metamask.io so we can take a closer look?  Thanks!

**Comment by LefterisJP** [comment]
Hey @dpazdan I am sorry but since then I have reset my account to solve the problem and no longer have any such logs.

**Comment by erieza09za08** [comment]
لا يوجد بة اللغة العربية

**Comment by Gudahtt** [comment]
Thanks for the report! I'm going to close this for now as we don't have enough information to investigate further, but we are aware of a number of different issues regarding transactions that share the same nonce. We're tracking that here: #9053. I'd recommend following that issue for progress on ensuring that we handle transactions with the same nonce properly in all cases.
