### ISSUE TITLE
Add privacy notice to "Show Incoming Transactions" setting

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#8806]
**What problem are you trying to solve?**
Since this feature will leak your Ethereum address(es) to Etherscan and they will be able to link it with your IP, cookies, etc., it's a privacy leak. The setting's description doesn't explain any of that.

**Describe the solution you'd like**
Inform the user properly about the privacy implications of using this feature. E.g. add this: "This option makes Metamask more convenient, but comes at the cost of revealing your Ethereum address to another third party (Etherscan), decreasing your privacy."

**Comment by hilvmason** [comment]
@kevinghim can you please work through getting copy for this issue and update to ready for work?

**Comment by holantonela** [comment]
This is the latest file we have for mobile. @SayaGT is working on extension UI for the general settings. 

https://www.figma.com/file/4gkmBwSE9qkecCS69pwsG3/Onboarding-Redesign?node-id=1112%3A96011&t=AITTRibW06CHlps7-4

We should consolidate the copy before going to development. cc @coreyjanssen 

Let me know if anything else is needed for the implementation.

**Comment by kevinghim** [comment]
Final copy: https://www.figma.com/file/cAHj7i7USWsMkzDsePN7zy/Settings-%3E-Security-%26-Privacy?node-id=4013%3A38032&t=IQotW0wvQHvxc6Dk-0

**Comment by hilvmason** [comment]
thanks @kevinghim -- removing the needs-copy label. 

@danjm @pedronfigueiredo @brad-decker -- I think this one should be ready to be picked up when someone is able to be assigned here.
