### ISSUE TITLE
Metamask executions fail

### ISSUE THREAD

**Issue by geopayme** [MetaMask/metamask-extension#8828]
For the past 24 hrs, no tx has gone thought with my metamask wallets, constantly fails, and some outrageous GWei of $78 in ETH for a simple Ether transfer and any amount it still fails! What is going on?

**Comment by tmashuang** [comment]
We  are not responsible for the mining pool's gas price.

**Comment by geopayme** [comment]
Mining pool? I used the same process on MEW and the fee was $18, who owns the mining pool and what node passes the requests to the miners! - amazing!

**Comment by geopayme** [comment]
no need to reply!

**Comment by tmashuang** [comment]
You can always adjust the gas to a value you see fit.

**Comment by geopayme** [comment]
I tried its locked to the middle of the High End! not sure why!
