### ISSUE TITLE
chainChanged send a String instead of an integer

### ISSUE THREAD

**Issue by xmaysonnave** [MetaMask/metamask-extension#8837]
Beta  https://173555-42009758-gh.circle-artifacts.com/0/builds/metamask-chrome-8.0.0.zip

**Describe the bug**
```
window.ethereum.on('chainChanged', chainId => {
   self.chainChanged(chainId)
})
```
Once registered the received chainId is a string like '0x1' while it was an integer in the previous version. 
Workaround -> parseInt the content
However this behaviour is not backward compatible. 
Implementers will  need to provide a new version specific to Metamask >= 0.8.0

With Ethers:
```
const web3 = new window.ethers.providers.Web3Provider(window.ethereum)
// Retrieve current network
const network = await web3.getNetwork()
```
The received network.chainId is an integer...

I suggest to send an integer instead of String as it was.

Thanks

**Comment by xmaysonnave** [comment]
https://github.com/MetaMask/metamask-extension/pull/8628

**Comment by xmaysonnave** [comment]
It sound to be conformed to spec :
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#chainchanged-1
However the point I raised seems valid. 
As the chainId used to be a decimal and now a String I need to provide a new version not backward compatible.
Thanks

**Comment by rekmarks** [comment]
@xmaysonnave, thanks for opening an issue with feedback! However, I don't believe that this is an issue.

All events related to chain/network changes we currently have in production emit with strings. The same will be true for v8. If you test the `chainChanged` event with a production version of MetaMask, you'll find that `chainChanged` does not exist. For us, it's new for v8.

In the current production version of MetaMask, v7, we only support a deprecated, misnamed chain ID event: `chainIdChanged`. This event is emitted with a correctly formatted hexadecimal string.

I'm not sure what `ethers` is doing, but we're not doing anything differently with respect to this.

I'm closing this issue, but feel free to ask any questions you may have.
