### ISSUE TITLE
I opened chrome and my fox is not there

### ISSUE THREAD

**Issue by firecommguy** [MetaMask/metamask-extension#8838]
**Describe the bug**

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by firecommguy** [comment]
no comments. just no icon of the fox.  I have 3 accounts on it

**Comment by firecommguy** [comment]
I added metamask to my chrome but I have no seed phrase

**Comment by tmashuang** [comment]
Make sure it's enabled, increase the length of the extension bar, and pinned to the bar.

**Comment by firecommguy** [comment]
Why is this closed. I had to use my code to metamask and my crypto is gone.

**Comment by tmashuang** [comment]
Email support[at]metamask.io with general user issue.

**Comment by firecommguy** [comment]
I have cnd tokens but r not showing up here. I added them last year

**Comment by firecommguy** [comment]
When i look at erc20 transactions, it shows 629 CND transferred to my acct.
It Also shows 2.2 LPT. not dure where that came from. I searched for CND to
add but cant seem to find it
