### ISSUE TITLE
Transaction stuck even if gas price is high, because of wrong Nonce settings.

### ISSUE THREAD

**Issue by bizso09** [MetaMask/metamask-extension#8840]
I'm trying to send a transaction with metamask, but it keeps getting stuck, even if the gas price is high.

I sent previously two transactions. They were pending, and I had no option to increase the gas price. The only option is Metamask is to cancel them. So I cancelled them, which were successfully processed.

Then I create a new transaction. Metamask assign Nonce 3 to it, and I set a high gas price. It should be processed within a few seconds. But it remains pending for hours. I don't understand, is Metamask getting confused by the Nonce? Why is the transaction not processed?

Again, with the 3rd transaction, I have no option available to increase the gas price, because it says insufficient funds. However, I have more than enough ETH in my wallet. The only option I see again is to cancel the transaction. However, it has a high Gas price, so is it not getting processed because of the wrong Nonce that Metamask keeps incrementing?

**Comment by tmashuang** [comment]
Hard to say without knowing if lower nonce tx is still pending. Speed up will only work on lowest nonce tx that is still pending. Please email support[at]metamask.io for further help.
