### ISSUE TITLE
Missing SourceMap warnings for Chrome extension in console

### ISSUE THREAD

**Issue by smimon** [MetaMask/metamask-extension#8841]
Loading any site with the Chrome extension open causes warnings about missing source maps to appear in the console:
![image](https://user-images.githubusercontent.com/2358820/85245927-4def7980-b473-11ea-91b8-e66ab6e836c9.png)

Chrome Version 83.0.4103.106 (Official Build) (64-bit) on Windows 10
Extension installed from https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en

**Comment by tmashuang** [comment]
Deduping #8167
