### ISSUE TITLE
Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by doudouaaa** [MetaMask/metamask-extension#8842]
**Page cannot be loaded**
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

**To Reproduce (REQUIRED)**

1.  app/home.html  add script <script src="./chromereload.js" type="text/javascript" charset="utf-8"></script>
2.  Modify the code , the browser refresh ,Has a chance to appear this problem

**Screenshots**
![image](https://user-images.githubusercontent.com/35355444/85252980-bf3d2580-b48f-11ea-9f9d-c15634bcb0e8.png)

**Browser details (please complete the following information):**
Chrome Version 83.0.4103.106 (Official Build) (64-bit) on Windows 10

**Comment by tmashuang** [comment]
It is unclear what the issue is and the goal trying to be achieved here. If there is a consistent error within your dapp and/or inside the production extension, please fill out the bug template with as much information that can help reliably reproduce the error.
