### ISSUE TITLE
RPC payload error

### ISSUE THREAD

**Issue by 4math2379** [MetaMask/metamask-extension#8843]
![screenerror](https://user-images.githubusercontent.com/8716331/85299699-e6065680-b4a5-11ea-9757-c99037f0e2e7.png)
Hello 

When i try to make a transaction with my smartContract  (erc721 token) i got this error  : 
``` rpc error with payload  ```

this the return of the console : 
```
MetaMask - RPC Error: Error: [ethjs-rpc] rpc error with payload {"id":6196400727191,"jsonrpc":"2.0","params":["0xf88b04850bdfd63e00836170d494affefa66661f47967759ab47f895d8477f5188b580a4ddc632620000000000000000000000000000000000000000000000000000000000000002822d45a0dd2a1487a6d44284842c75169497073c468d3a905d0993b28140fdb6be073797a046c308f6a0812525ef50c6c68a18fea8b336a48d1a2e2e6dcb330c6fd5f4cd65"],"method":"eth_sendRawTransaction"} [object Object] 
Object { code: -32603, message: "Error: [ethjs-rpc] rpc error with payload {\"id\":6196400727191,\"jsonrpc\":\"2.0\",\"params\":[\"0xf88b04850bdfd63e00836170d494affefa66661f47967759ab47f895d8477f5188b580a4ddc632620000000000000000000000000000000000000000000000000000000000000002822d45a0dd2a1487a6d44284842c75169497073c468d3a905d0993b28140fdb6be073797a046c308f6a0812525ef50c6c68a18fea8b336a48d1a2e2e6dcb330c6fd5f4cd65\"],\"method\":\"eth_sendRawTransaction\"} [object Object]", stack: "Error: Error: [ethjs-rpc] rpc error with payload {\"id\":6196400727191,\"jsonrpc\":\"2.0\",\"params\":[\"0xf88b04850bdfd63e00836170d494affefa66661f47967759ab47f895d8477f5188b580a4ddc632620000000000000000000000000000000000000000000000000000000000000002822d45a0dd2a1487a6d44284842c75169497073c468d3a905d0993b28140fdb6be073797a046c308f6a0812525ef50c6c68a18fea8b336a48d1a2e2e6dcb330c6fd5f4cd65\"],\"method\":\"eth_sendRawTransaction\"} [object Object]" }
inpage.js:1:79970
Error: [ethjs-rpc] rpc error with payload {"id":6196400727191,"jsonrpc":"2.0","params":["0xf88b04850bdfd63e00836170d494affefa66661f47967759ab47f895d8477f5188b580a4ddc632620000000000000000000000000000000000000000000000000000000000000002822d45a0dd2a1487a6d44284842c75169497073c468d3a905d0993b28140fdb6be073797a046c308f6a0812525ef50c6c68a18fea8b336a48d1a2e2e6dcb330c6fd5f4cd65"],"method":"eth_sendRawTransaction"} [object Object]
```
Link to SC code : [here](https://github.com/4math2379/CraftingChain-/blob/master/contracts/Harvest.sol)
Link to JS  code : [here](https://github.com/4math2379/CraftingChain-/blob/master/src/js/app.js)

Environment
Truffle v5.1.31 (core: 5.1.31)
Solidity v0.5.16 (solc-js)
Node v14.4.0
Web3.js v1.2.1
last version of Metamask

any help are welcome thanks :)

**Comment by tmashuang** [comment]
Using Ganache/ganache-cli? Possible nonce issue when restarting ganache, Settings > Advanced > Reset Account to rest nonce while connected to Ganache.

**Comment by 4math2379** [comment]
> Using Ganache/ganache-cli? Possible nonce issue when restarting ganache, Settings > Advanced > Reset Account to rest nonce while connected to Ganache. 

I use Ganachei ever reset the account in side Metamask Ext

this the error (see screenshot),

I thinks it's because of the inheritance of  multiple SC. I can confess since a month i got this error 
![error](https://user-images.githubusercontent.com/8716331/85308629-b6f5e200-b4b1-11ea-97f8-6c7ea7f458c1.png)

**Comment by tmashuang** [comment]
This is a general error message that pertains to when analyzing the estimated gas of the tx. I am not adequate enough with Solidity to debug this particular issue. But you might get more help on the official ethereum.stackexchange, [link exception thrown](https://ethereum.stackexchange.com/search?q=exception+thrown).

**Comment by 4math2379** [comment]
> This is a general error message that pertains to when analyzing the estimated gas of the tx. I am not adequate enough with Solidity to debug this particular issue. But you might get more help on the official ethereum.stackexchange, [link exception thrown](https://ethereum.stackexchange.com/search?q=exception+thrown).

Thanks for the clue.

I manage to find something. I will come back here with more explanation.
