### ISSUE TITLE
Support for account and network switching during a dapp connection

### ISSUE THREAD

**Issue by benesjan** [MetaMask/metamask-extension#8851]
When a dapp is trying to connect to a metamask account it would be useful to give user an option to select the account and network in case the user is using multiple accounts. Now I am always forced to close the popup, change the account and network and reload the website.

![Screenshot from 2020-06-24 10-12-57](https://user-images.githubusercontent.com/13470840/85520553-5e365e80-b603-11ea-939d-5cb951fc5737.png)

Thanks

**Comment by tmashuang** [comment]
This will be done in version 8.

**Comment by tmashuang** [comment]
Well the account switching part, not the network part.
