### ISSUE TITLE
Remove Recents under 'Transfer  between my accounts'

### ISSUE THREAD

**Issue by dlokman** [MetaMask/metamask-extension#8862]
**Describe the bug**
I mistakenly sent my tokens to the address listed under Recents. Some address could not belong to you. Please remove the Recents feature

**To Reproduce (REQUIRED)**
Just send a token and pick from the Recents (some address that you sent to that does not belong to you)

**Expected behavior**

![metamask](https://user-images.githubusercontent.com/14881144/85642746-f4946f80-b657-11ea-8ec6-c5718f975f94.png)

**Comment by dlokman** [comment]
I think the main issue is that this screen appears after you click on 'Send' for one of the coins. The issue is with the UI design. It should not list 'Recents' right under the link for 'Transfer between my accounts'. If the user is not thinking right (like i wasn't), they might think that the Recents addresses are the wallet addresses that you can transfer to between my accounts. If you take the 'Recents' away, atleast it will prevent the user from making the mistake. The fault is in UX design.

**Comment by jacobcantele** [comment]
I agree @dlokman 

That UX pattern is very confusing for the user.

**Comment by phiphamuet** [comment]
This ux very ugly. Remove the recents address if it not in address book. Best case to remove it. Users need to copy your address again instead of choose recent address. It can be any contract they interactive with.

**Comment by michaellubrin** [comment]
@dlokman happened to me today. So frustrating. I accidentally sent to the wrong address when I switched fromE TH to BSC Network (I have a saved address in ETH). When I switched to BSC, it changed to Recents. Is there any way to recover lost coins?

**Comment by blackboxtrading** [comment]
me too! sent to the wrong address and cannot recover my fund. you need to fix this!!

**Comment by Spigy1** [comment]
Has just happened to me and now I am chasing a project to try and get my money back ... I don't want them there and need to clear them .. currently a expensive mistake

**Comment by blackboxtrading** [comment]
yes, please fix this !!!

**Comment by Spigy1** [comment]
So after speaking to the project I accidental sent funds to they are saying it's impossible to get back .. might not be a lot to some but $667 is to me ... the recents need to move it to easy to just tap on of them .. they are not favourites

**Comment by lgwillmore** [comment]
migrate to brave

**Comment by lc** [comment]
Yep this feature just screwed me over this morning. Was a bit groggy and meant to click transfer between accounts.  Accidentally sent ETH to an address listed here. Going through Etherscan, I've never interacted with the address. 

Obviously this is still my fault for not sending a test transaction and for hastily assuming it was my other account, but this is still a footgun.

**Comment by Rampag3Mag3** [comment]
Click your Ident Icon top right.
Click Settings > Contacts > Click the address you want removed. 
Click Edit > Delete account.

**Comment by mattwmc** [comment]
I just did this, too! Please fix! Thanks!!!
