### ISSUE TITLE
Custom nonce doesn't work for value 0

### ISSUE THREAD

**Issue by aminlatifi** [MetaMask/metamask-extension#8882]
**Describe the bug**
Custom nonce feature doesn't work for the first transaction of account (nonce zero)

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior
1. Try to use a new account which hasn't any transaction on network, so it's first transaction will have nonce value zero. 
2. Connect metamask to mainnet or any testnet which doesn't do transaction immediately
3. Do a transaction in network and set low gas limit for it in order to have enough time for next transactions
4. Cancel the first transaction (this step may not be required, but I needed for my test)
4. Create another transaction with high gas value and set its nonce value manually to zero

**Expected behavior**
The second transaction should be mined by network and the first one should be failed! But metamask doesn't care about the custom nonce zero and eventually both transactions will be mined. First transaction will have nonce value 0 and the second one will have nonce 1

**Screenshots**
![image](https://user-images.githubusercontent.com/5684607/86327459-a2a3a900-bc58-11ea-9643-106f4ddd9333.png)

**Browser details (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome Version 83.0.4103.116 (Official Build) (64-bit)
 - MetaMask Version 7.7.9

**Comment by tmashuang** [comment]
This is addressed in https://github.com/MetaMask/metamask-extension/pull/8618, will be fixed in the next version.

**Comment by tmashuang** [comment]
Actually, upon looking at this a little more, setting the nonce to 0 doesn't seem to work. Will update more with my findings.
