### ISSUE TITLE
Ensure pre-selected account on connect screen is visible in list

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#8903]
Scenario:
- Have many accounts
- Have a later account selected
- Connects to a new site

Problem:
- The pre-selected (checked) account is not visible on the connect screen, and so the user thinks no accounts are selected.

Ideally:
- A pre-selected account will either be shown at the top by default, or the list will be automatically scrolled to show that account.

**Comment by Gudahtt** [comment]
>A pre-selected account will either be shown at the top by default, or the list will be automatically scrolled to show that account.

@rachelcope Any preference between these two options?

We could always show the _current selected account_ at the top of the list, then use the normal account order for the rest. That might be the best looking solution.

**Comment by danfinlay** [comment]
This is way overdue. I just connected to a site on an account I didn't mean to because it was "selected" out of view.

I prefer jumping the selected accounts to the top of the list, rather than scrolling down to them, ensuring the user can "just scroll down" to access all other accounts.

**Comment by bschorchit** [comment]
This has been reviewed by @SaraCheikh and her decision was also to show the selected accounts on top.

[Slack thread](https://consensys.slack.com/archives/G4V2HTG0Y/p1644844396097389)
