### ISSUE TITLE
newBlockHeaders subscription is broken

### ISSUE THREAD

**Issue by anxolin** [MetaMask/metamask-extension#8916]
**Describe the bug**
Issue subscribing to the block headers event (`newBlockHeaders`) after updating to Metamask 8
https://web3js.readthedocs.io/en/v1.2.9/web3-eth-subscribe.html#subscribe-newblockheaders

**To Reproduce (REQUIRED)**

1. Install Metamask for Firefox `v8.0.1`
2. Go to https://codepen.io/anxolin/pen/RwrxOrK?editors=1111
3. Press connect
4. Press subscribe

**Expected behavior**
I expect to be notified on every block, like the in the following output. 

This output it's taken from the codepen above, using Metamask for Chrome `v7.7.9`

<img width="1256" alt="Screenshot at Jul 03 22-11-50" src="https://user-images.githubusercontent.com/2352112/86495765-00301680-bd7b-11ea-8555-d9dfb05b5de9.png">

**Screenshots**
I don't receive the event notification.

This is the output in Metamask for Firefox `v8.0.1`:
<img width="1214" alt="Screenshot at Jul 03 22-12-30" src="https://user-images.githubusercontent.com/2352112/86495842-3ff6fe00-bd7b-11ea-9fd6-8416e8782430.png">

**Browser details (please complete the following information):**
 - OS: MacOS
 - Hardware Wallet: N/A
 - Browser: Firefox
 - MetaMask Version: 8.0.1

**Additional context (Error Messages, etc.)**
N/A

**Comment by alfetopito** [comment]
Adding that I see the same behaviour on Firefox 78.0.1 (64-bits) on Linux with Metamask 8.0.1.
