### ISSUE TITLE
MetaMask 8 only - RPC Error: The requested account and/or method has not been authorized by the user. 

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#8922]
In new metamask 8, my dapps stopped working and the issue is 
`MetaMask - RPC Error: The requested account and/or method has not been authorized by the user. `

what are the breaking changes? what should I look for? 

![image](https://user-images.githubusercontent.com/9360827/86520853-f69bc280-bdfd-11ea-96b0-dd977a116056.png)

**Comment by rstormsf** [comment]
`const ethAccounts = await ethereum.enable()` isn't enough anymore?

**Comment by rstormsf** [comment]
I found the issue:
params:[{from: checksummed address}]
while Metamask v8 expects address in lowercase!

What a bummer, metamask team
@danfinlay 

fix it up that either: accepts checksummed address, like you did in v7, or accept both, lowercased and checksummed

**Comment by rekmarks** [comment]
@rstormsf it _should_ accept addresses regardless of casing, so this is a bug, that we will fix.

**Comment by rekmarks** [comment]
Could you please share a more detailed snippet from your dapp code? Specifically, it'd be helpful to see example values of the following: `method`, `params`, `from`

**Comment by rstormsf** [comment]
@rekmarks the validation check for authorized accounts don't respect checksummed addresses if I use `sendAsync` or `request` method in `params` array for `from` value

**Comment by rekmarks** [comment]
@rstormsf this issue will be closed by #8923, which resolves the issue.

As an aside, for calls to `ethereum.request` and `ethereum.sendAsync`, the top-level `from` property has been ignored in practice for MetaMask for some time. Likewise, callers do not need to specify the `jsonrpc` property. For example, instead of this:

```javascript
ethereum.sendAsync({
    method: 'eth_sendTransaction',
    params: [{ to, from, value }],
    jsonrpc: '2.0',
    from
  },
  (err, result) => { /* stuff */ }
)
```

You can just do this:

```javascript
ethereum.sendAsync({
    method: 'eth_sendTransaction',
    params: [{ to, from, value }],
  },
  (err, result) => { /* callback */ }
)

// or, in MetaMask v8

try {
  const transactionHash = await ethereum.request({
    method: 'eth_sendTransaction',
    params: [{ to, from, value }],
  })
catch (error) {
  // handle error
}
```

**Comment by rstormsf** [comment]
@rekmarks true. I left it as a legacy code that works with other web3 providers (Forks of old metamask, etc)

**Comment by rekmarks** [comment]
@rstormsf Yeah, that makes sense! I believe that the next significant EIP (after [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193.html), which is past its review period end) related to the JavaScript provider is a way to quickly determine the capabilities/interface of a particular provider. For now, the presence of the `request` method should signal the existence of an 1193-compatible provider.

**Comment by dev-tom-0108** [comment]
I have fixed this error with redeploy the program.
Plz recheck the program Id.
Perhaps the `declare_id` in the lib.rs and `anchor.toml`'s program ID are different from the deployed Program's Id.

Plz refer this.

Thanks
