### ISSUE TITLE
Use English instead of Hindi translations

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-extension#8930]
For the purpose of internationalization, we could keep the default language for India as English. Hindi translations are less likely to benefit users in India, as English is most widely used in technical contexts (it's an official language).

Also note, India has many languages, so Hindi translations might not be accessible to many either. 
English is likely the most accessible (most consumer apps are in English today). And unless we want to focus on localization within India, I'd recommend to stick with English.

**Comment by Gudahtt** [comment]
We don't make any default language choices based upon country. The browser tells us which languages to use.

Did you encounter a case where Hindi was selected by default when you didn't expect it to be? If so, would you be able to check the language settings in your browser? There have been a lot of reports from support for this too, so we might be doing something non-optimal.

**Comment by Gudahtt** [comment]
I'll close this for now since I think we're already doing the correct thing here.

My takeaway here is that we can consider Hindi translations to be low-priority.
