### ISSUE TITLE
seed importing issues

### ISSUE THREAD

**Issue by zgcoin** [MetaMask/metamask-extension#8946]
I have found that when we importing a new seed(from others wallet) into  the MetaMask Extension on firefox or Chrome,would found that the old accounts were lost completed,so how could  we get them back?
if we would lost the dogital assets in the old wallet?by the way,there is no any warning words during the importing process.

**Comment by zgcoin** [comment]
No others way get it back?

**Comment by tmashuang** [comment]
If you have importing an new seed phrase you are essentially overriding the previous seed phrase's vault data. Make sure you back up seed phrases.
