### ISSUE TITLE
Ability to unlock and use while offline, no network connection?

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#8964]
Currently, if the extension is in a locked state while offline, unlocking will prompt a `Network request failed` and prevent unlocking. 
Possible design issue, should we let users interact with the extension while offline? How would this look like, need for an internet connection element/banner/etc? I believe we start network requesting on unlock, but I could be wrong, and we need to extrapolate this out.

**Comment by pi0neerpat** [comment]
If the .enable() fails you can just create a wallet-less provider. Then just get the user's address (from local storage or whatever) when making calls with it.

```js
import { InfuraProvider } from "@ethersproject/providers";

import { getErrorResponse } from "./general";

// TODO: remove eslint disable
/* eslint-disable import/prefer-default-export */
export const getWalletlessProvider = async ({ network, infuraKey }) => {
  try {
    const walletlessProvider = new InfuraProvider(network, infuraKey);
    return { walletlessProvider };
  } catch (error) {
    return getErrorResponse(error, "getWalletlessProvider");
  }
};
```

**Comment by Gudahtt** [comment]
I'm going to close this in favour of an older issue that's about roughly the same thing: #5210
