### ISSUE TITLE
MetaMask masks error information

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#8975]
**Describe the bug**
Metamask errors obscure helpful information into [object Object] before providing the error to the using dapp.

**To Reproduce (REQUIRED)**
Trigger an RPC error (sorry, no easy examples of how at the moment). 

As shown for example in [these postings](https://github.com/MetaMask/metamask-extension/issues/8583), when there is an RPC error MetaMask returns (and console-logs) an error message like this:

>MetaMask - RPC Error: Error: [ethjs-rpc] rpc error with payload {"id":\<long int\>,"jsonrpc":"2.0","params":["\<longer hex\>"],"method":"eth_sendRawTransaction"} [object Object] 

where the parts in angle brackets are replaced with real content but the parts in square brackets, including the "[object Object]" at the end is not. 

**Expected behavior**
The [object Object] is not part of the error message string but instead replaced by something more useful, or simply removed and the object is included in the error object alongside "code", "message", and "stack".   Something like what's shown at the end of [this line](https://github.com/MetaMask/metamask-extension/blob/f5a125fe614f483fb042380933e69f64693b73d3/app/scripts/lib/extractEthjsErrorMessage.js#L13) would be more useful than [object Object]. 

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: 83.0.4103.116 (Official Build) (64-bit)
 - MetaMask Version: 7.7.9

**Additional context (Error Messages, etc.)**
I suspect somewhere there is a `+` concatenation between `'rpc error with payload '` and an error object where they should be combined in the same object, and not passed/altered/returned as just a string.

**Comment by vandan** [comment]
Duplicates #12646
