### ISSUE TITLE
v8 Speed up in queued tx

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-extension#8992]
![image](https://user-images.githubusercontent.com/9360827/87502741-42791380-c617-11ea-884e-dd92618b5b29.png)

Not sure how it happened, I simply clicked on Speed up button in v8.

It worked after I clicked Speed up again

**Comment by tmashuang** [comment]
Most likely case is that it is coming from here.
https://github.com/MetaMask/metamask-extension/blob/f9cd775eae5195f1d7ca4ba7c81f77cdda402ac5/ui/app/helpers/utils/gas-time-estimates.util.js#L3-L5

**Comment by haydenadams** [comment]
Came here to report the same bug - it worked the first time I clicked speed up (since the update) but now it just gives me that error screen
