### ISSUE TITLE
web3_clientVersion RPC call returns an error

### ISSUE THREAD

**Issue by Moejoe90** [MetaMask/metamask-extension#8993]
**Describe the bug**
It seems that you have disabled `web3_clientVersion`, since we can't use this RPC call in our dapp anymore to know if the client is metamask or not. 

`RPC Error: The method 'web3_clientVersion' does not exist / is not available` 

Maybe this is on purpose and there is a different way to do this now, in all cases please advice

**To Reproduce (REQUIRED)**

1. Go to platform.neufund.org
2. Click on login
3. Click on Metamask
4. Try to Login
5. Error show's in the console

**Expected behavior**
The metamask client should return the client version without any issues unless this is known behaviour 

**Additional context (Error Messages, etc.)**
`code: -32601, message: "The method 'web3_clientVersion' does not exist / is not available."`

**Comment by Gudahtt** [comment]
Thanks for the report! I was able to reproduce this.

**Comment by DeltaBalances** [comment]
I noticed this in several decentralized exchanges using parts of the etherdelta codebase.
`web3.version.getNode()` using web3.js version 0.2.x  returns the same error.

Wasn't sure if this was a bug or simply a deprecation in the new API

**Comment by Gudahtt** [comment]
This was unintentional; we try to provide adequate advanced notice for any intentional breakages.

This will be fixed in the next update.
