### ISSUE TITLE
Privacy and Connections settings missing

### ISSUE THREAD

**Issue by hammerjoe** [MetaMask/metamask-extension#8994]
**Describe the bug**
With latest version 8.0.4 I cant find the PRIVACY option in the settings anymore nor can I find the CONNECTIONS options to add sites to the authorised metamask list.
As a result I cant access some sites anymore.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows] Win/10 
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)] Vivaldi latest version
 - MetaMask Version [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment]
>I cant find the PRIVACY

It should be under "Settings > Security & Privacy". This was unchanged between v7.7.9 and v8.0.4.

>nor can I find the CONNECTIONS options to add sites to the authorised metamask list.

This has moved from the settings to the Account Options menu. The button is now called "Conencted sites". See here:
![connected-sites](https://user-images.githubusercontent.com/2459287/87583056-c253bc00-c6b1-11ea-9355-04ea5370f855.PNG)

**Comment by tmashuang** [comment]
Closing due to lack of OP response and it seems that the question has been answered
