### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'subscription' of undefined" when changing account

### ISSUE THREAD

**Issue by clementdelaneau** [MetaMask/metamask-extension#9013]
I have three issues in the console since the v8 release when I change of Metamask account : 

1.
> Uncaught TypeError: Cannot read property 'subscription' of undefined
    at t.exports.requestManagerNotification (index.js:102)
    at u (inpage.js:1)
    at t.exports.a.emit (inpage.js:1)
    at a.<anonymous> (inpage.js:1)
    at u (inpage.js:1)
    at a.emit (inpage.js:1)
    at inpage.js:1
    at l.write [as _write] (inpage.js:1)
    at b (inpage.js:1)
    at inpage.js:1
    at l.v.write (inpage.js:1)
    at a.y (inpage.js:1)
    at h (inpage.js:1)
    at a.s.emit (inpage.js:1)
    at _ (inpage.js:1)
    at w (inpage.js:1)
    at a.b.push (inpage.js:1)
    at t.exports._write (inpage.js:1)
    at b (inpage.js:1)
    at inpage.js:1
    at t.exports.v.write (inpage.js:1)
    at o.y (inpage.js:1)
    at h (inpage.js:1)
    at o.s.emit (inpage.js:1)
    at _ (inpage.js:1)
    at w (inpage.js:1)
    at o.b.push (inpage.js:1)
    at o._onMessage (inpage.js:1)

2.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

3.
> GET chrome-extension://invalid/ net::ERR_FAILED

I made a test of my application with Metamask v7 to be sure and there were no errors. When I upgrade to v8 (without changing my code) I have the errors I listed above. 
However, the behavior of my app is still correct, there is no crash and the page is updated when the Metamask account changes. The informations are just longer to update, which is annoying.

I use a React Typescript frontend with Chrome (I have the same behavior with Firefox). 
I guess the issue  is related to the use of the event : 
`        window.ethereum.on('accountsChanged', (accounts:any) => {
        })`

Also I would like to use @metamask/detect-provider but it's not compatible with Typescript. When is it planed to make Metamask fully compatible with TS ?

**Comment by tdvni** [comment]
My DApp has the same problem at v8.0.4 but v7.7.8 not appear.

![image](https://user-images.githubusercontent.com/54297787/87866917-f2ed6b80-c9b9-11ea-92b2-3b10820f3532.png)

![image](https://user-images.githubusercontent.com/54297787/87866933-2a5c1800-c9ba-11ea-9545-ed5f98b3b727.png)

**Comment by tdvni** [comment]
my web3 version 1.2.7

**Comment by Gudahtt** [comment]
Thanks for the report @clementdelaneau and @tdvni The "Cannot read property 'subscription' of undefined" bug should be resolved in the next release.

**Comment by Yazanalsharif** [comment]
when can this bug will resolve , when the next relese will launched

**Comment by clementdelaneau** [comment]
New release is here : https://github.com/MetaMask/metamask-extension/releases .
The issue is gone, good job 👍

**Comment by Yazanalsharif** [comment]
where the extension will update 😀

‫في الجمعة، 24 يوليو 2020 في 3:53 م تمت كتابة ما يلي بواسطة
‪clementdelaneau‬‏ <‪notifications@github.com‬‏>:‬

**Comment by Gudahtt** [comment]
We've submitted the new release to the Chrome web store, we're just waiting on them to review it first. My guess is that it'll be released next week, though it might be the week after if they're very slow with review.

**Comment by Yazanalsharif** [comment]
okey thanks so mush

i will add extra function to my project to resolve this bug until the
extension done

‫في الجمعة، 24 يوليو 2020 في 4:15 م تمت كتابة ما يلي بواسطة ‪Mark Stacey‬‏
<‪notifications@github.com‬‏>:‬
