### ISSUE TITLE
ethereum.selectedAddress update is delayed.

### ISSUE THREAD

**Issue by DeltaBalances** [MetaMask/metamask-extension#9027]
**Describe the bug**
A minor bug, but `ethereum.selectedAddress` isn't immediately changed on the `accountsChanged` event, which is different behaviour from the previous version. Calling `ethereum.selectedAddress` from within the callback will return the old account.
A small timeout in javascript will show the change happening.

`ethereum.selectedAddress` is marked as deprecated in the docs, but it is still available for now.

No big issue because the accounts value is correct, but it might cause issues in a case where the callback calls a function that internally uses selectedAccount.

**To Reproduce (REQUIRED)**
MetaMask with 2 accounts connected.

Take the following javascript logging:

```
window.ethereum.on("accountsChanged", function (accounts) {
    if (accounts && accounts.length > 0) {
        console.log('log1: ' + accounts[0] + ' - ' + ethereum.selectedAddress);
        // wait for 1 millisecond to log again
        window.setTimeout(function() {
            console.log('log2: ' + accounts[0] + ' - ' + ethereum.selectedAddress);
        }, 1);
    }
})
```
log1 prints the accounts immediately after the event and log2 is identical with a small delay.

MetaMask 8.0.4
- on MetaMask login
  `log1: account1 - null`
  `log2: account1 - account1`
- on change from account1 -> account2 in MetaMask
  `log1: account2 - account1`
  `log2: account2 - account2`

MetaMask 7.7.9
- on MetaMask login
  `log1: account1 - account1`
  `log2: account1 - account1`
- on change from account1 -> account2 in MetaMask
  `log1: account2 - account2`
  `log2: account2 - account2`

**Browser details (please complete the following information):**
 - OS: Windows 10
- Metamask 7.7.9 & MetaMask 8.0.4 on Firefox 78.0.2 & Brave 1.2.43.

**Comment by rekmarks** [comment]
@DeltaBalances thank you for bringing this to our attention. This will be fixed in MetaMask@8.0.6. We'll keep the issue open until then.
