### ISSUE TITLE
QR code scanning function not working

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-extension#9043]
**Describe the bug**
MetaMask extension 8.x qr code scan for recipient's address is not functioning on any browser (firefox, brave, or chrome).

**To Reproduce (REQUIRED)**
Click Send, select the qr scan button.

![image](https://user-images.githubusercontent.com/16330048/88091850-392b0200-cb55-11ea-825a-c5ebc7e3085a.png)

**Browser details (please complete the following information):**
 - OS: Mac OS, did not test on windows or linux
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser [firefox, brave, and chrome]
 - MetaMask Version [8.x]

**Comment by darkwing** [comment]
I've been looking into what's going on here and am pretty close to finding a solution:

```diff
diff --git a/ui/app/components/app/modals/qr-scanner/qr-scanner.component.js b/ui/app/components/app/modals/qr-scanner/qr-scanner.component.js
index 63ca45b88..1111a7fd7 100644
--- a/ui/app/components/app/modals/qr-scanner/qr-scanner.component.js
+++ b/ui/app/components/app/modals/qr-scanner/qr-scanner.component.js
@@ -46,7 +46,10 @@ export default class QrScanner extends Component {
 
     if (prevState.ready !== ready) {
       if (ready === READY_STATE.READY) {
-        this.initCamera()
+        
+        // This line starts a *second* stream which is why the video never goes away
+        //this.initCamera()
+
       } else if (ready === READY_STATE.NEED_TO_ALLOW_ACCESS) {
         this.checkPermissions()
       }
@@ -76,7 +79,9 @@ export default class QrScanner extends Component {
         this.setState({ error })
       }
     }
+    
     // initial attempt is required to trigger permission prompt
+    console.log("checkEnvironment calling initCamera!")
     this.initCamera()
   }
 
@@ -107,13 +112,21 @@ export default class QrScanner extends Component {
     if (this.codeReader) {
       this.codeReader.reset()
     }
+
+    console.log('componentWillUnmount!')
   }
 
   initCamera = async () => {
     this.codeReader = new BrowserQRCodeReader()
     try {
       await this.codeReader.getVideoInputDevices()
+
+      // Adding this line gets the camera working
+      this.checkPermissions()
+
+      console.log(`${Date.now()} Calling decodeFromInputVideoDevice!`)
       const content = await this.codeReader.decodeFromInputVideoDevice(undefined, 'video')
+
       const result = this.parseContent(content.text)
       if (!this.mounted) {
         return

```

Adding the `checkPermissions` call allows the camera to work, but it never goes away.  I spotted this in console:

<img width="1087" alt="PlayError" src="https://user-images.githubusercontent.com/46655/95644279-33212f00-0a7b-11eb-9052-0bc1ca79da6c.png">

... which points to:

<img width="639" alt="PlayCode" src="https://user-images.githubusercontent.com/46655/95644284-3c120080-0a7b-11eb-8d85-6df10966086c.png">

Those seemed to point to multiple attempts to play a video or steam; I could confirm via the two `initCamera` calls:

<img width="739" alt="CalledTwice" src="https://user-images.githubusercontent.com/46655/95644307-5ea41980-0a7b-11eb-937e-6050fdb00493.png">

By removing `componentDidUpdate`'s `this.initCamera()` call, everything works as it should -- camera works properly and turns off when the modal is closed.  I don't think we can simply make that change, as we need to check permissions dialogs.

@Gudahtt -- I see you made a big change in https://github.com/MetaMask/metamask-extension/commit/dcc7d295118ee1557850a41af118a3efa5df0287#diff-7f01bc39ef3f399efd52204dfa621f51 ; maybe we can catch up next week about this?

**Comment by doivosevic** [comment]
Has this been fixed? I get camera ooopsing when trying to scan a qr code from my laptop

**Comment by Gudahtt** [comment]
@doivosevic yes, the QR code problem described here was fixed. It's possible you're seeing a new or different bug though.

I'd suggest testing your camera on another website to ensure it's not the fault of your camera/browser/etc. If it works elsewhere but not on MetaMask, please create a new issue describing the what you were doing when you encountered the problem, and details like the browser, OS, and MetaMask version you were using. Thanks!
