### ISSUE TITLE
New Metamask reduces the UX of using multiple hardware wallet accounts

### ISSUE THREAD

**Issue by dmihal** [MetaMask/metamask-extension#9045]
I use Metamask with multiple accounts on my Trezor.

Previously, I could easily switch between Trezor accounts. However, now there is an authorization popup every time I switch accounts.

Would it be possible for Metamask to remember which accounts have already been approved?

**Comment by jacobcantele** [comment]
Hi @dmihal I think yu're referring to the was that Windows requires authorization when communicating with hardware wallets over u2f, is that right? Can you confirm you're experiencing this on Windows? I don't think we control this, I believe it is your OS.

**Comment by dmihal** [comment]
@jacobcantele nope, not on Windows

This is what I was referring to:

Switching HW accounts on old Metamask:
1. Open Metamask, connect to hardware wallet
2. Select desired Trezor/Ledger account
3. Return to dapp

Now it's this:
1. Open Metamask, connect to hardware wallet
2. Select desired Trezor/Ledger account
3. Return to dapp
4. Open metamask, approve connection to dapp

The simplest solution would be for Metamask to remember site approvals for hardware wallet accounts, in addition to built-in accounts, so users could easily switch between the two

Even better would be the ability to import two different hardware wallet accounts to Metamask at the same time

**Comment by Gudahtt** [comment]
Thanks for the suggestion @dmihal. This is because we clear state associated with old accounts when you remove them, and currently when you connect a new hardware wallet it will disconnect the previous one.

This relates to #6649; if we had better support for using multiple hardware wallets, we would not "forget" the previous account that was connected so this second authorization wouldn't be required.

**Comment by dmihal** [comment]
Thanks @Gudahtt

Just to clarify, I'm not talking about multiple hardware wallets, just multiple accounts on the same hardware wallet. I know that Metamask keeps these accounts cached because I can switch accounts, even with my hardware wallet unplugged.

**Comment by Gudahtt** [comment]
Thanks for the clarification! I believe what I said still applies (if you replace "hardware wallet" with "hardware wallet account"). We do cache some details, but I'm pretty sure there is some account state that gets discarded each time you switch. This is referenced in #6649 as well, which talks about supporting not just multiple hardware wallets, but also multiple derivation paths on each wallet.

**Comment by danfinlay** [comment]
Closing as we've shipped this in 9.2.0!
