### ISSUE TITLE
Issue with transactions with the same nonce, cancellations, speedups, failed txs.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#9053]
Originally brought up via internal slack message. The original issue presented with subsequent transaction after a failed transaction. The tx-list-item would show the failed transasction's title/txCategory, tx details, etc instead of the newer transaction with the same nonce. 

My first set was to just provide the UI with the correct tx details, but realized some information that we provide on first creation of a transaction is omitted on the `primaryTransaction` property of the tx (`txCategory`). https://github.com/MetaMask/metamask-extension/pull/9040. Then showing the UI the correct/updated/newest tx details https://github.com/MetaMask/metamask-extension/pull/9041. 

Then prompts a discussion on the correct info to show when chaining these types of transactions.

**To Reproduce**
Reproduction OP slack issue

1. Get a failed transactions
    - With the gas prices being so high, just send a transaction with ETH with a really low gas price and it should fail with `transaction underpriced`

2. Propose and confirm a new transaction
    - Preferable as a different txCategory. So if the first failed transaction is a send eth, then propose an erc approve or transfer.

See that some of the data is from the first proposed failed transaction.

**Comment by brad-decker** [comment]
Potentially related to #8831 @tmashuang?

**Comment by tmashuang** [comment]
It is related, but a different flow. That solution could just be to suppress/omit hardware wallet rejection of tx from updating the tx,

**Comment by tmashuang** [comment]
For testing purposes, on a Test Network we can take advantage of the exceeds block gas limit error from the RPC to simulate the tx failure.

    Submit a tx on a testnet (Rinkeby) with a gas price < 1
    Click Speed Up
    Under Advanced Tab for gas limit set to 10000000000 . Gas price to 1 , this shouldn't matter though.
    Click the Save button

This will/should update the tx list item to a failed state. Thus not showing any visible indication of the tx with gas price < 1 that has been submitted, and still pending on the network. I think this is fundamental issue on how we present transactions in the transaction list.

**Comment by shhac** [comment]
Please include a QA step for resolving this issue where other transaction flows are also tested; e.g. the Approve Spend Limit flow which as a related (but not duplicate) issue https://github.com/MetaMask/metamask-extension/issues/10129
