### ISSUE TITLE
In "activity tab" why does an erc-20 Approve function call make it look like I've actually spent the amount that I approve?

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#9059]
These transactions are being categorized to have the text say "Approve spend limit" instead of the function name (approve).
In this case I think that it shouldn't show a balance depletion, as the funds aren't actually moved by this transaction and the UI is presenting inaccurate information to the user.

**Comment by tmashuang** [comment]
Fixed by https://github.com/MetaMask/metamask-extension/pull/9032/?

**Comment by brad-decker** [comment]
Should be fixed by #9032 which is included in #9054.
