### ISSUE TITLE
Metamask does not handle permissions requests properly when not logged in

### ISSUE THREAD

**Issue by AlexCheema** [MetaMask/metamask-extension#9060]
**Describe the bug**

Possibly related to https://github.com/MetaMask/metamask-extension/issues/8918 and https://github.com/MetaMask/metamask-extension/issues/8919 

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. (this is just a random website i found that uses metamask - it's listed on metamask's frontpage) Go to https://instant.airswap.io/swap
2. Ensure MetaMask is locked (you are not signed in)
3. Click on "Connect Wallet" then the "Metamask" option
4. Close the Metamask sign-in prompt
5. Metamask will not acknowledge the permissions request as having failed. It will remain in a pending state, despite having closed the sign-in prompt
6. Refresh the page and repeat steps 2 & 3
7. You will now see "Permissions request already pending; please wait." since the permissions request is still pending.

**Expected behavior**
As soon as the user closes the sign-in prompt, Metamask should make the permissions request fail with a "User rejected the request" error.

**Screenshots**
Here is what metamask shows when clicking "Connect Wallet" 
![Selection_201](https://user-images.githubusercontent.com/41707476/88291355-649a2200-ccf8-11ea-81eb-036a8323b683.png)

Here is what the metamask icon shows while the permissions request is pending, after closing the sign in prompt:
![Selection_197](https://user-images.githubusercontent.com/41707476/88237782-44c71780-cc80-11ea-9c56-1928296e764c.png)

Here is what airswap shows after closing the sign in prompt:
![image](https://user-images.githubusercontent.com/41707476/88291457-8e534900-ccf8-11ea-8468-364293d4f0a3.png)

**Browser details (please complete the following information):**
 - OS: Windows / Linux (tried on both)
 - Firefox Browser 78.0.2 (64-bit)
 - MetaMask Version 8.0.5 (Last Updated: 22 July 2020)

**Comment by tmashuang** [comment]
> Metamask will not acknowledge the permissions request as having failed. It will remain in a pending state, despite having closed the sign-in prompt

This didn't happen in my reproduction. This seems the exact issue as https://github.com/MetaMask/metamask-extension/issues/8919 but was fixed. Airswap will show that the user rejected the request after step 3 for me. In step 1 you dont need whole form url, work fine without it, I am editing it to remove them for posterity's sake.

**Comment by wbt** [comment]
If the user explicitly clicks Cancel on the connection request, an error is sent that the user rejected the request.
If the user clicks outside of the pop-up, causing the pop-up to temporarily disappear from view, that should NOT be interpreted as a rejection. The user should be able to click on the fox icon and see the connection request again. 

The dapp should be clearer about this in its UI, saying e.g. "If you don't see it, click the MetaMask icon on your browser toolbar."  However I don't think the click-away (which is way too easy to do accidentally) should equal rejection.

**Comment by AlexCheema** [comment]
This happens before you are signed in (when you have your accounts "locked"). There is no cancel option here. I've updated my original issue to be more clear.

![Selection_201](https://user-images.githubusercontent.com/41707476/88291206-2b61b200-ccf8-11ea-93a8-86dd6836e8f5.png)

**Comment by AlexCheema** [comment]
> If the user explicitly clicks Cancel on the connection request, an error is sent that the user rejected the request.
> If the user clicks outside of the pop-up, causing the pop-up to temporarily disappear from view, that should NOT be interpreted as a rejection. The user should be able to click on the fox icon and see the connection request again.
> 
> The dapp should be clearer about this in its UI, saying e.g. "If you don't see it, click the MetaMask icon on your browser toolbar." However I don't think the click-away (which is way too easy to do accidentally) should equal rejection.

The behaviour for when you are already signed in is completely fine. You can click cancel there and an error occurs. However, if you are not signed in there is no cancel button and your only option as a user is to close the pop up window. Sorry for the confusion. Please see my previous comment.

**Comment by tmashuang** [comment]
Ok so in between step 1 & 2, there should be an additional step that is `Ensure MetaMask is locked`. 

I don't necessary think there is an issue, the extension is locked and the connect request has not been handled. Which is different when closing the popup on the Connect Screen. Fortunately, this is different than https://github.com/MetaMask/metamask-extension/issues/8919 in that the Connect Screen was actually being cleared, not to be seen again, after closing the popup. 

If a user goes through this the steps, the Connect Screen will still be there when the extension is opened via the extension icon. There are problems on airswap.io after refreshing the page and the connect request is pending. Continuing to click the connect button on airswap will show `Permissions request already pending; please wait.` persistent error on airswap with no indication on the user to handle to connect request. Once the connect request is handled then clicking the connect button on airswap will allow further interaction.

**Comment by wbt** [comment]
I stand by my original comment. I agree there is no "cancel" button visible on the login screen, but if you click the metamask icon indicating one action pending user approval, *and then enter your MetaMask password*, you get the dialog asking if you want to confirm or deny the connection request.  The same suggested UI string above from AirSwap would lead the user to that solution.  

I don't think there's actually any Metamask problem here and would close this issue.
