### ISSUE TITLE
Cannot export private key.

### ISSUE THREAD

**Issue by zamicol** [MetaMask/metamask-extension#9077]
I can create a new account and cannot export the private key.  I get a "Incorrect Password."  I'm using copy/paste, tried typing, locked and unlocked the account, etc... I cannot export on new or old account.  

I have been unable to get export to work under any conditions.  

Related are #6981 and #5968.

Version 8.0.5
Version 83.0.4103.97 (Official Build) (64-bit)
Ubuntu

In the meantime, is there a way to manually export keys?

**Comment by zamicol** [comment]
I have no problems in Firefox, only in Chrome.  

Chrome does leave an issue in the console.  I censored the extension path string part:

`DevTools failed to load SourceMap: Could not load content for chrome-extension://-----/sourcemaps/ui-libs.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`
`

**Comment by endlos** [comment]
It happened to me when the Extension was setup for "on click" site access, for improved security.

You can try these 2 options:

1) If you have your seed phare / private key(s):
    Try removing the extension, and then adding it as a clean install. Then import your seed phrase.

2) If you don't have your seed phrase:
   You can export your private key from your already loaded wallet(s), by setting the "site access" option to "on all sites" like this:
   Go to extension "details", then "Site access", then choose "On all sites" (which is the default).

   ![image](https://user-images.githubusercontent.com/1424711/89805221-f24c7e80-dafa-11ea-879b-f0623560a839.png)

**Comment by zamicol** [comment]
Yep that fixed it.  Should be keep this issue open until some sort of user notification/bug fix is made?

**Comment by Gudahtt** [comment]
I was unable to reproduce this, following the steps shown (i.e. MetaMask only able to run on-click). So this does appear to have been fixed.
