### ISSUE TITLE
Key path for account generation

### ISSUE THREAD

**Issue by FIVIL** [MetaMask/metamask-extension#9078]
Hey, I was wondering what key path MetaMask uses for generating secondary accounts out of the original seed?? To be more specific I was wondering how  can I generate the same addresses out of the same private key in my code??

**Comment by tmashuang** [comment]
MetaMask uses the Ethereum standard `m/44’/60’/0’/0`. As for developer related questions, checkout https://ethereum.stackexchange.com.
