### ISSUE TITLE
Smart contracts with high risk of Ponzi schemings or other scams to be labeled as HIGH RISK just like etherscan feature

### ISSUE THREAD

**Issue by cezarvatafu** [MetaMask/metamask-extension#9082]
**What problem are you trying to solve?**
Users are reaching out  to Metamask support in regards to the extraordinary high gas price they have to pay for a smart contract execution. Users are under the impression that this is a Metamask bug.

**Describe the solution you'd like**
It would be nice to have a have a feature just like the one from etherscan.io to label these smart contract addresses as HIGH RISK.
https://etherscan.io/address/0x5acc84a3e955Bdd76467d3348077d003f00fFB97

**Additional context**
Zendesk tickets 39308 and 41517 for reference 
<img width="739" alt="Screenshot 2020-07-27 at 18 28 28" src="https://user-images.githubusercontent.com/52824746/88560562-f8405b00-d036-11ea-90de-e634b6ca3d1e.png">
<img width="630" alt="Screenshot 2020-07-27 at 18 30 11" src="https://user-images.githubusercontent.com/52824746/88560770-363d7f00-d037-11ea-833f-262b60bb0dd2.png">

**Comment by mlopes75** [comment]
Estou com esse problema e não tenho fundos para retirar do pool
