### ISSUE TITLE
Clicking tx completion notification no longer redirects to etherscan

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9087]
As [reported by two users on reddit here](https://www.reddit.com/r/Metamask/comments/hy39hn/cant_click_on_chrome_notification_to_view/?utm_source=share&utm_medium=ios_app&utm_name=iossmf).

I don't believe this was a deliberate choice.

**Comment by mcplums** [comment]
Awesome, thanks for opening this @danfinlay . While we're on the subject, can you add the same functionality if the transactions fails? It never used to do this but it always irked me that the chrome notification behaves differently depending on whether it succeeds or not.

**Comment by mcplums** [comment]
I should add- when I say 'fails' I mean it confirms but reverts, so there is still an etherscan page that can be linked to.
