### ISSUE TITLE
Pre-approving a gas amount for a site

### ISSUE THREAD

**Issue by vporton** [MetaMask/metamask-extension#9089]
**What problem are you trying to solve?**
It is inconvenient to confirm multiple transactions when doing just one task consisting of multiple transactions.

**Describe the solution you'd like**
It would be convenient to pre-approve some amount of gas for a site and then allow the site to do operations without confirmation until it spends all the pre-approved gas.

**Comment by jacobcantele** [comment]
Hi @vporton , this isn't possible without a contract account based wallet currently (it would require an EIP that is beyond the scope of this Github repo. That said, it might be worth adding to our feature request backlog for the future when we'll be able to support contract accounts. I'm closing this for now.

https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas

**Comment by vporton** [comment]
> Hi @vporton , this isn't possible without a contract account based wallet currently (it would require an EIP that is beyond the scope of this Github repo. That said, it might be worth adding to our feature request backlog for the future when we'll be able to support contract accounts. I'm closing this for now.
> 
> https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas

No, it is possible. It can be done not only with a special contract-based smart wallet but just by storing the amount of money to use without asking the user in browser local storage by MetaMask. So it does not require a contract or EIP. Please, reopen.

**Comment by Gudahtt** [comment]
It sounds like that would require changing the provider API, which we aren't generally willing to do unless the change has been specified in an EIP. If you'd like us to extend the provider API to allow dapps to pre-approve things, I'd suggest opening an EIP to describe the problem and your proposed solution.

**Comment by vporton** [comment]
> It sounds like that would require changing the provider API, which we aren't generally willing to do unless the change has been specified in an EIP. If you'd like us to extend the provider API to allow dapps to pre-approve things, I'd suggest opening an EIP to describe the problem and your proposed solution.

It does not require changing the provider API. Just count approved gas amounts _in MetaMask_ (not in the chain) differently. You should reopen.

> Or instead post your feature request to the linked forum, and we may revisit the idea ourselves sometime in the future.
