### ISSUE TITLE
Ridiculous spam in the Chrome web store

### ISSUE THREAD

**Issue by Bomper** [MetaMask/metamask-extension#9090]
I was just about to install the extension and thought I'd check [the reviews](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en)... Oh gosh. :vomiting_face: 

Who has access to the Chrome web store listing?

Can anyone do anything about the horrible spam there? Not only does it make people navigate to that "empowr" crap site, but it can easily dissuade new users from even trying Metamask.

**Comment by Gudahtt** [comment]
Thanks! We are aware of the problem, and [we are considering prompting users to add reviews](https://github.com/MetaMask/metamask-extension/issues/7178) as a way to drown these out.

We've flagged these comments as spam, but unfortunately there's no way for us to remove them. Please feel free to mark them as unhelpful and/or as spam though! With enough reports, Google might eventually remove them.
