### ISSUE TITLE
Stale ERC-20 token balance

### ISSUE THREAD

**Issue by Paussie** [MetaMask/metamask-extension#9092]
i sent 2 different tokens to my Metamask ETH address and neither have appeared in my wallet, even after adding the ticker... 

24 hours later i sent ETH to the same address on metamask and that came through no problem.  When i look on etherscan i can see the tokens there... 

I contacted metamask days ago, and the reply i received was useless, a link to the how to add a custom token vid... :(

**Comment by Gudahtt** [comment]
Only a select few ERC-20 tokens will get added automatically to your wallet when you receive them ([any that are in this list](https://github.com/MetaMask/eth-contract-metadata/blob/master/contract-map.json)). Any other token will need to be manually added, or you'll need to visit a dapp that will suggest the token.

Which tokens did you encounter this behavior with?

**Comment by Paussie** [comment]
Grid & Clout, i sent ETH to the same address and that came through,,,  i just tried again 15 minutes ago to send some ETH but that never came through... This is the transaction, 
0x89bb6350d0da8f07ca90be487207081bcbe114de8715a3c37bcd4bd2a1f41c9f

**Comment by Gudahtt** [comment]
That token is not in our default list, so it would have to be added manually as a custom token. This can be done via the 'Add Token" button on the bottom of the Asset list.

**Comment by Paussie** [comment]
yeah i have done that, on Sunday and they havent shown

**Comment by Gudahtt** [comment]
Ah I see, sorry I had not understood.

So they're not showing up in your asset list? Or they are there, but with the wrong balance?

**Comment by Paussie** [comment]
they are there, but the balance says 0,  but on etherscan i can see the 2 different coin balances in that address...  the same address i sent ETH to a couple days ago which came through,  i tried again half hour ago and the ETH has not come through again.

**Comment by Gudahtt** [comment]
I see - that doesn't seem right.

Could you [send your state logs to our support team](https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-)? That would make investigating this issue easier.

**Comment by Paussie** [comment]
Where do i send them, it wont let me add the files here

**Comment by Gudahtt** [comment]
Thanks! I'll coordinate with support, and they will follow up via ZenDesk;

I think this situation is specific to your account, rather than indicative of a bug in MetaMask, so I'm going to close this issue again for now. We can always open it again if it does turn out to be a bug.

**Comment by Paussie** [comment]
ok, thankyou, i just cant be waiting over 24 hours for a reply from support again...

**Comment by tmashuang** [comment]
I see no indication that address that begins with 0x1692... is a MetaMask address. Can you clarify on the context of this address?

**Comment by Paussie** [comment]
im not sure what you mean, how would i find out where that address is because clearly i have received funds from that address,
0xd848dba92c09e0d83274de0ab226109d784b9902e542a725620ed46dc6c0a70b

**Comment by tmashuang** [comment]
I see that you have 3 metamask addresses 0x0b79... , 0xd0af... , 0x0bc4... Nonce of which are the one in question, 0x1692... Do you know anything about that address?

**Comment by Paussie** [comment]
i;ve found it, its a portis address that i used when i first started this crypto stuff a few weeks ago...  

only thing is i dont know how to get the tokens out of it, or even if i can

**Comment by Paussie** [comment]
ive sorted it, sorry about this...
