### ISSUE TITLE
Random order account list

### ISSUE THREAD

**Issue by samscalet** [MetaMask/metamask-extension#9102]
when sending eth using "Transfer between my accounts" i'm getting random list of my account instead account 1 , account 2 etc. i got 100 account its quite annoying to find them.. also search address should search only my account not other public address when on "Transfer between my accounts" page.
![Screenshot from 2020-07-30 00-03-46](https://user-images.githubusercontent.com/52046359/88824447-ef978280-d1f8-11ea-8344-36cc8fa16a1a.png)  
![Screenshot from 2020-07-30 00-10-53](https://user-images.githubusercontent.com/52046359/88824736-50bf5600-d1f9-11ea-9964-6f8f5a1ad986.png)

**Comment by Gudahtt** [comment]
Thanks! @dpazdan was able to reproduce this
