### ISSUE TITLE
Wrong gas estimate on non-main network

### ISSUE THREAD

**Issue by TripleSpeeder** [MetaMask/metamask-extension#9106]
**Describe the bug**
When Metamask is connected with a custom network it seems to apply the gas estimates from Ethereum Mainnet.

**To Reproduce**
1. Connect Metamask with a custom network. I observed this with IDChain network, but probably this happens on all networks.
    RPC-URL: https://idchain.one/rpc/ 
    NetworkID: 74
1. Click on "Send" to send some eth
1. Select a destination address
1. Observe the gasprice proposed by Metamask: Right now it sets a value of 80gwei, which is way too high for IDChain (10gwei is the norm there)

**Expected behavior**
Metamask should not use ETH mainnet gas estimates for other networks.
If there is no gas price feed available it should force the user to set a price instead of chosing gas price from a different network.

**Browser details (please complete the following information):**
 - OS: Arch Linux
 - Browser: Brave Version 1.11.97 Chromium: 84.0.4147.89 (Offizieller Build) unknown (64-Bit)
 - MetaMask 8.0.5

**Comment by Gudahtt** [comment]
Thanks! I was able to reproduce this.

**Comment by danfinlay** [comment]
- [ ] Hide advanced gas settings tab when on non-main network
- [ ] Hide the three-button gas input (slow, medium, fast) on confirmation screen.
- [ ] Edit the send UI to show the gas fields instead of the three buttons
