### ISSUE TITLE
ellipses on signature request

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#9123]
8.0.5

Don't know what I'm signing
<img width="358" alt="Screen Shot 2020-07-31 at 12 45 05 PM" src="https://user-images.githubusercontent.com/799573/89071537-d04d4200-d32b-11ea-8a82-32e1d91362c1.png">

**Comment by brad-decker** [comment]
related to #7921

**Comment by Gudahtt** [comment]
Thanks for the report! I think this problem is adequately captured by #7921, so I'm going to close this as a duplicate.
