### ISSUE TITLE
MetaMask Update Gas Price Not working

### ISSUE THREAD

**Issue by teekenl** [MetaMask/metamask-extension#9125]
**Describe the bug**
Having the problem when trying to edit to update with higher gas price to unclear pending transactions

**To Reproduce (REQUIRED)**
Send one token with lower gas price, the transaction will be pending due to the lower gas price. Then trying to update the transaction with higher gas price to speed it up.

1. Go to 'Pending Transaction'
2. Click on 'Speed Up'
3. Trying to edit with higher gas price
4. Click Save, but nothing happened.

**Expected behavior**
I expected to see something to happen,at least the higher price i entered should be now be updated after clicking the `Save` button from gas price edit dialog., so that i can unclear my pending transactions.

**Screenshots**
<img width="488" alt="Screen Shot 2020-08-02 at 1 10 15 am" src="https://user-images.githubusercontent.com/13831887/89106500-f292ad00-d45c-11ea-97b0-0979e140a9eb.png">

**Browser details (please complete the following information):**
 - OS
 - Ledger Nano S
 - Google Chrome 84.0.4147.105
 - MetaMask Latest Version: 8.0.5

**Additional context (Error Messages, etc.)**

**Comment by teekenl** [comment]
This is seems to be critical issue, Urgent .

**Comment by dpazdan** [comment]
Those estimates are not customizable, you simply can click the "advanced" gas option to edit.  Let me know if that doesn't work for some reason.

Dave
MetaMask

**Comment by banescusebi** [comment]
I have the same issue. 

@dpazdan even when editing the gas option in the "advanced" tab, the "Save" button does not work.

Also tried navigating to "Save" via the Tab key and it did not work. The button is disabled when looking at the source via inspect

**Comment by Gudahtt** [comment]
Closing, as the original reported issue seems to have been a misunderstanding.

Thanks for that extra detail @banescusebi! Have you seen this recently? This may have been fixed since you left that comment. if you're still experiencing that issue, please create a new issue and we can investigate further.

**Comment by Shaukat1550** [comment]
Offline for maintenance
MetaMask Swaps is undergoing maintenance. Please check back later.
WHEN SWAP EVERY TIME METAMASK Says this no swap done plz solve this issue

**Comment by AudriusBuika** [comment]
when will be fixed? bug still exist...
