### ISSUE TITLE
 MetaMesk does not always send the 'accountsChanged' event on v8.0.5

### ISSUE THREAD

**Issue by jie85** [MetaMask/metamask-extension#9126]
**Describe the bug**
1. MetaMesk does not always send the 'accountsChanged' event on v8.0.5
2. When changing the account address on MetaMask, the DApp cannot get the new address. If the DApp submit a tx, the MetaMask get a console log:
```MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug.```
3. the bug happens only when upgrading to v8.0.5

**To Reproduce (REQUIRED)**

1. Go to mcdex.io
2. Connect multi-accounts
3. Open to AMM page
4. switch between accounts
5. if the address on mcdex.io does not change corresponding, do a deposit transaction, get console log:
```MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug.```

**Expected behavior**
The account on mcdex.io changes when the user selects different accounts on MetaMask.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. Chrome Version  84.0.4147.105
 - MetaMask Version [e.g. 8.0.5]

**Additional context (Error Messages, etc.)**

**Comment by rekmarks** [comment]
@jie85, thank you for bringing this to our attention. We are about to merge a fix (#9137) that will resolve this. The fix will be included in `8.0.7` of the extension, which will probably ship on Firefox this week, and Chrome a week later.
