### ISSUE TITLE
Project startup under Windows is prompted with document Yarn Start

### ISSUE THREAD

**Issue by WANGJIAWEI999** [MetaMask/metamask-extension#9127]
yarn run v1.22.4
$ yarn build dev
$ node development/build/index.js dev
running task "dev"...
Starting 'dev'...
Starting 'clean'...
Finished 'clean'
Starting 'styles:dev'...
Finished 'styles:dev'
Starting 'scripts:core:dev:background'...
Starting 'scripts:core:dev:ui'...
Starting 'scripts:core:dev:phishing-detect'...
Starting 'scripts:core:dev:contentscript'...
Starting 'static:dev'...
Starting 'manifest:dev'...
Starting 'reload'...
Finished 'reload'
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jacobcantele** [comment]
@WANGJIAWEI999 This doesn't appear to be a MetaMask bug. Developer support requests should be directed to the Ethereum Stack Exchange group:

https://ethereum.stackexchange.com

**Comment by Gudahtt** [comment]
Reopening this, as this is a problem with the MetaMask extension build system.

We don't use Windows for development as a team, but I think we should support development on Windows to help community contributors at least.

**Comment by Gudahtt** [comment]
This was fixed in #9628
