### ISSUE TITLE
Warn users whenever an ENS name contains a homoglyph vulnerability

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9129]
An ENS name is a UTF-8 compatible string of text. That means there are many characters that have the same appearance, or homo-glyph.

This can cause some concerns when using an ENS name:
- Pasting an ENS name that looks correct could actually be wrong. [as tweeted recently](https://twitter.com/NepalBlockchain/status/1290153162007916544?s=19)
- Reverse-resolved ENS names could appear familiar but actually be deliberately crafted to be deceptive.

I had [mentioned this acceptance criteria in a previous issue](https://github.com/MetaMask/metamask-extension/issues/5525#issue-370263922), but a basic check with a vulnerable name and I cannot find any warning.

MyCrypto has a tool called [ens-validation](https://github.com/MyCryptoHQ/ens-validation) that can do the hard part of this already, we just need to design & display the appropriate warnings.

Acceptance criteria:
- Entering a homoglyph-impersonation name on the send screen `to` field should show a warning. Can verify with `vita‍lik.eth`, which is not the same as `vitalik.eth`.
- A confirmation screen showing an ENS name should also show a warning under any homoglyph-containing name. We could also simply not resolve a homoglyph-containing name.

Possible copy for the warning:
- This name has some deceptive letters in it that resemble other letters. It is probably trying to impersonate another well-known name. Did you get this name from someone you trust?

**Comment by Gudahtt** [comment]
>Reverse-resolved ENS names could appear familiar but actually be deliberately crafted to be deceptive.

I believe our reverse-resolved ENS names are always displayed as punycode, so they aren't susceptible to this problem.

**Comment by 0xc0de4c0ffee** [comment]
:pray: 
I was testing ZWJ in `eth-ens-namehash` normalize (UTS46 `transitional=false`, `useSTD3AsciiRules=true`).

```
expected: |-
      'vita‍<ZWJ>lik.eth' 
    actual: |-
      'xn--vitalik-k06c.eth'
``` 
**Current Metamask lookup with Non-ASCII name** 
![zwj](https://user-images.githubusercontent.com/43116881/89241457-b0b16480-d61e-11ea-8723-b6305f5de025.png)

**Show normalized `xn--name` and warning** 
![normal](https://user-images.githubusercontent.com/43116881/89241944-05a1aa80-d620-11ea-8eb3-975971822566.png)

Warning should focus on all non-ASCII names, check against possible impersonator/scam scenarios and specific homoglyphs without triggering false alarm on all international/emoji names.

This is [IDNA mess](https://www.npmjs.com/package/idna-uts46#idna-mess-for-dummies) long before ETH/ENS mess. 
> While UTS46 tries to bridge the incompatibility, there are four characters which cannot be so bridged: ß (the German sharp s), ς (Greek final sigma), and the ZWJ and ZWNJ characters. These are handled differently depending on the mode; in transitional mode, these strings are mapped to different ones, preserving capability with IDNA2003; in **Nontransitional Mode**, these strings are mapped to themselves, in accordance with IDNA2008.

[Etherscan](https://etherscan.io/enslookup?q=vita%e2%80%8dlik.eth) is warning `vita<zwj>lik.eth` with "normalized" redirect to real `vitalik.eth`.. 
> `Warning! Found (and Normalized) Zero Width Character in name : [vita<ZeroWidthChar>lik.eth]`

[Etherscan](https://etherscan.io/enslookup?q=xn--vitalik-k06c.eth) lookup for `xn--vitalik-k06c.eth`
> `Sorry, the name 'xn--vitalik-k06c.eth' does not appear to be valid`

IDK if etherscan is using EIP-137 compatible normalization process. OR it's ok for metamask to follow same rules..

UTS46.js Known issues 
> It also does not try to implement the Bidi and contextual rules for validation: these do not affect any mapping of the domain names; instead, they restrict the set of valid domain names. **Since registrars shouldn't be accepting these names in the first place, a domain that violates these rules will simply fail to resolve.**

**Comment by danfinlay** [comment]
A problem with enforcing ascii rules is it doesn't represent the scope of ENS, which supports many character sets, including emoji. If we converted all to punycode, we would be effectively limiting the whole of ENS to ASCII-character languages.

**Comment by 0xc0de4c0ffee** [comment]
> If we converted all to punycode, we would be effectively limiting the whole of ENS to ASCII-character languages.

[This line from `eth-ens-namehash`](https://github.com/danfinlay/eth-ens-namehash/blob/c623e73d8eb48c5370a2116e9c4fa96fb07a85e9/index.js#L26) normalise.toAscii function
```
function normalize(name) {
    return name ? uts46.toAscii(name, {useStd3ASCII: true, transitional: false}) : name
}
```
I'm bit confused IF ENS spec was asking for `uts46.toUnicode(...)` instead of `uts46.toAscii(...)`?

Example from `eth-ens-namehash` tests
domain: `fоо.eth` // with cyrillic 'o'
toAscii : `xn--f-1tba.eth`
namehash : `namehash(xn--f-1tba.eth)` //  NOT `namehash(fоо.eth)`

So I think it's ok to show full IDNA mess with warning.
```
fоо.eth
(xn--f-1tba.eth)
0xaddress

Warning: This name contains non-Ascii characters .... (Warn level 1-3)
```

**Comment by lastcanal** [comment]
Unicode.org's has a [working group](http://www.unicode.org/reports/tr39/) that maintains a list of 'confusable' unicode characters along with the character it might be confused with, called [confusables.txt](https://www.unicode.org/Public/security/10.0.0/confusables.txt)

I put together a [library that translates the confusables.txt file into a lookup table](https://github.com/lastcanal/unicode-confusables) and then used it to build what I think is a pretty nice warning system.

It is able to detect 'vita‍lik.eth' 
<img width="359" alt="vitalik" src="https://user-images.githubusercontent.com/16561/89918745-6acd4100-dbc8-11ea-97dc-a941db14bad9.png">

It can also detect 'faceboоk.eth'
<img width="360" alt="facebook" src="https://user-images.githubusercontent.com/16561/89918826-85071f00-dbc8-11ea-94e3-c3cb1e45885f.png">

It might even be a little too strict because it warns on 'math.eth' being so similar to 'rnath.eth'
<img width="363" alt="math" src="https://user-images.githubusercontent.com/16561/89918888-9819ef00-dbc8-11ea-8fc0-ec3810bf547f.png">

Best of all it doesn't mangle emoji!
<img width="360" alt="nepal-flags" src="https://user-images.githubusercontent.com/16561/89918929-a2d48400-dbc8-11ea-8f44-b4f4c40ab7fd.png">

You can see from the [tests](https://github.com/lastcanal/unicode-confusables/blob/develop/test.js) that it even warns on similar Japanese.

The downside is that 100KB of json (30KB gzipped) gets added to the ui bundle.

**Comment by lastcanal** [comment]
I should add that one improvement could be to convert the 'confusable' name into it's non confusable version then resolve and display both names in the list, highlighting the differences. 

Hopefully this helps!

**Comment by rachelcope** [comment]
Design update recommendations:

1) Update alert copy to: 
> "We have detected an unusual character (homoglyph) in the ENS name entered. Check the ENS name/address with your recipient to avoid potential scam."

2) Remove the tooltip. 
(The alert copy and changing the homoglyph character to red text should be sufficient)

**Comment by rachelcope** [comment]
What happens in the use case that an ENS name is created in another language (e.g., Greek, Hebrew, etc) that uses homoglyph characters?

**Comment by Gudahtt** [comment]
Removing the tooltip makes sense! That is the only place where the specific character that was confusing is highlighted though, which is something to consider maybe.

**Comment by cjeria** [comment]
@rachelcope @Gudahtt are you letting the user continue in the flow if a homoglyph is detected?

**Comment by lastcanal** [comment]
Hi @cjeria, I would definitely recommend allowing users to continue the flow if a homoglyph is detected. Languages such as Greek, Hebrew, etc. might have a higher false positive rate than English, but all languages _will_ have false positives.

For example, the Hebrew character 'ן‎' will warn users that it is confusable with 'l', even if the entire ENS domain is in Hebrew. It would be possible to remove the warning for 'ן‎' if all other characters in the ENS domain are in the Hebrew script set; however, this would require building another index from another Unicode working group.

@rachelcope I like the updated copy, but I think it is important to change 'unusual' to 'confusable' if we are sticking with this implementation.

> "We have detected a _confusable_ character (homoglyph) in the ENS name entered. Check the ENS name/address with your recipient to avoid potential scam."

The best English example I can find for why this is confusable and not unusual is the letter 'm', which is marked as confusable with 'rn' according to the unicode working group.

If we want only unusual characters to be detected then we could remove the confusable entries that are in the same script set (e.g. m -> rn), but only if the entire ENS domain uses the same script set.

**Comment by cjeria** [comment]
@lastcanal Thanks for the feedback. One design we're considering (on the mobile app side at least) is to throw a warning that the users can bypass by acknowledging the alert. I could see this being a nuisance for some languages that use confusable characters but the main intent is to help identify deceptive names. Would this be acceptable in your opinion?

**Comment by lastcanal** [comment]
Hi @cjeria I think that would work great; I am in no way annoyed by popups that are trying to save me a some scam :). Would it be possible to gather metrics on how often the popup is displayed? Extra work could be done later to de-escalate the error if the confusables characters are in the same alphabet/script set.

**Comment by rachelcope** [comment]
@lastcanal thanks for your copy suggestion.

Here's a small update to the error message to make it more concise: "We have detected an confusable character (homoglyph) in the ENS name. Check the ENS name to avoid a potential scam."

@cjeria Before we add a required acknowledgement (on extension), we need to establish a design pattern and process for determining what errors require additional acknowledgement. For now, I suggest just show the standard/existing error message

**Comment by rachelcope** [comment]
@Gudahtt here's the updated design and copy. Here's the [figma file](https://www.figma.com/file/SwzcT8L3XSoMGAwCW9W2lk/Error-Messaging?node-id=1492%3A1484)

![image](https://user-images.githubusercontent.com/7483074/109201864-8e6c6900-775f-11eb-8004-06e37d9b64eb.png)

**Comment by Gudahtt** [comment]
Closing this as completed in #9187, and further improved in #10530.

The designs shown in the most recent comment will be implemented as part of the overall confirmation screen redesign. For now we've just used the existing warning designs with this updated copy.
