### ISSUE TITLE
Confirmation warnings can appear clipped below the scrollable area

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9136]
On the transaction confirmation screen, we have an area where we render warnings, like "This transaction will likely run out of gas".

That area is currently at the bottom of the TX details view, which is scrollable, and prioritizes the "Confirmation" button, which is fixed at the bottom of the view.

This means relevant information can be missed by the user who does not scroll, while the confirm button remains prominent.

Possible mitigations (some can combine):
- Add the confirm/cancel buttons to the scrollable region, so they cannot be clicked until all details have been seen.
- Move the warning message to the top of the confirmation view
- Disable the `Confirm` button until scrolling to the bottom, in the style of common terms & conditions views (maybe a "dark pattern", as it may encourage not reading closely).

@rachelcope

**Comment by rachelcope** [comment]
I am in favor of @danfinlay 's  option #1 - adding the confirm/cancel buttons to the scrollable area. 

This use case where the warning shows below the fold happens only (I believe) when user has advanced gas options turned on.

<details>
<summary>Screenshot</summary>

<img width="309" alt="Screen Shot 2020-08-11 at 11 24 41 AM" src="https://user-images.githubusercontent.com/7483074/89928586-44f26d00-dbc5-11ea-8ba6-35f68eaca81d.png">

</details>

If the user sees the default transaction confirmation, then they should see the error above the fold and not be required to scroll to confirm.

<details>
<summary>Screenshot</summary>

<img width="354" alt="Screen Shot 2020-08-11 at 11 26 29 AM" src="https://user-images.githubusercontent.com/7483074/89928756-8a169f00-dbc5-11ea-981f-d9cb833167d3.png">

</details>
