### ISSUE TITLE
Please add Carboneum (C8) ERC-20 token to default list

### ISSUE THREAD

**Issue by chotipat88** [MetaMask/metamask-extension#9138]
My users cannot find Carboneum (C8) in "Search Tokens" box

**Additional**
Token address: 0xd42debe4edc92bd5a3fbb4243e1eccf6d63a4a5d
Link to official project website: https://carboneum.io/
Token info page: https://coinmarketcap.com/currencies/carboneum-c8-token/
Etherscan Verification: https://etherscan.io/address/0xd42debe4edc92bd5a3fbb4243e1eccf6d63a4a5d#code

PR created at https://github.com/MetaMask/eth-contract-metadata/pull/553

<img width="367" alt="Screen Shot 2563-08-05 at 16 43 36" src="https://user-images.githubusercontent.com/40626183/89398045-d16edc80-d73a-11ea-8759-c27f9e318a3a.png">

**Comment by dpazdan** [comment]
wrong repository, plus we do not update the erc20 repo anymore
