### ISSUE TITLE
OmiseGo (OMG) token keeps reappearing

### ISSUE THREAD

**Issue by Alko89** [MetaMask/metamask-extension#9145]
I have some (less than 1) OMG token I received way back on some airdrop. I have removed the token from my list of assets dozens of times now, but it keeps reappearing.

**Comment by Gudahtt** [comment]
Thanks for the report @Alko89 ! There is already an old issue open about this: #5055

Apparently this design was intentional, but I agree it is both unexpected and undesirable. I'll talk this over with the team, and we will use #5055 to track progress on this problem.
