### ISSUE TITLE
Option to change metamask window postition

### ISSUE THREAD

**Issue by aksdevac** [MetaMask/metamask-extension#9162]
**What problem are you trying to solve?**
Can I control metamask popup window default position, left/right/center etc?

**Describe the solution you'd like**
Currently right side position is overlapping with our site's default toast message position, eariler it was not on right side on chrome.
Allow site to set metamask's popup window default position.

**Comment by dpazdan** [comment]
Hi there, we are no longer submitting feature requests here.  You can submit here for now: https://metamask.github.io/feedback/

**Comment by aksdevac** [comment]
@dpazdan Hi, the link you gave is not working, it keeps on loading forever.

**Comment by dpazdan** [comment]
I tried just now and it is working for me.  What browser are you using?  Maybe try disabling popup blockers, or try a different browser entirely?

**Comment by aksdevac** [comment]
@dpazdan Hi thanks, today I can open it in Chrome, may be yesterday my net was slow.
