### ISSUE TITLE
Better Account List Management (Drag, Archive, Search)

### ISSUE THREAD

**Issue by andreihq** [MetaMask/metamask-extension#9163]
**What problem are you trying to solve?**
Managing multiple accounts/addresses causes a lot of frustration. As "newer" accounts are pushed down the list and user is required to scroll down the list to find "newer" accounts. It is kinda counterintuitive that "newer" accounts are pushed down the list and don't stay at the top.

**Describe the solution you'd like**
1) Allow to move accounts/addresses within the list.  
2) Allow "Archiving" accounts.  
3) Create a separate "Archived" list of accounts, which user no longer is planning on using and allow user to mark certain accounts as "Archived" so these accouns are removed from Main List and are only shown in Archived List. This will clean up main list by showing only relevant accounts.  
4) Allow to search account list using partial match on the addresses (and not just user given names). 

**Additional context**
Attached a screenshot to provide better context.  
<img width="319" alt="mm-better-acc-mgmt" src="https://user-images.githubusercontent.com/14127397/89708775-b5f61280-d982-11ea-9c6b-16ebee045de9.png">

**Comment by Robbiekruszynski** [comment]
Hi @andreihq 

Thanks for reaching out with this feature request! We are working on asking the community to port their requests over to our [ZenDesk ](https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas)so the team can keep closer eyes on these types of tickets. 

Please let me know if you have any question, I'm going to go ahead and close this ticket.

Thanks, 

Robbie
