### ISSUE TITLE
Ledger Nano X asks to sign transactions twice sometimes

### ISSUE THREAD

**Issue by enolan** [MetaMask/metamask-extension#9171]
**Describe the bug**
For last few transactions I've sent using my Ledger Nano X, the hardware wallet has asked me to approve the transaction twice. The transaction goes through after the first signing. I've had it work - asking me to approve only once - before, I don't know what the difference is. This is the same behavior as in #6344, but on a different device. I'm running the latest firmware and Ethereum app versions.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Do any transaction in the Augur 2 webapp. (I'm almost certain the actual site in question is irrelevant)
2. Unlock Ledger and open Ethereum app
3. Approve the tx in MetaMask
4. Review the tx on the Ledger
5. Approve the tx on the ledger
6. See the same approval prompt on the Ledger again

**Expected behavior**
I should only be prompted to approve once per transaction.

**Browser details (please complete the following information):**
 - OS: NixOS Linux
 - Hardware Wallet: Ledger Nano X, firmware 1.2.4-4, Ethereum app 1.3.7
 - Browser: Firefox 79.0
 - MetaMask Version 8.0.6

**Comment by dpazdan** [comment]
Unable to reproduce and no other users have reported similar in over a year.
