### ISSUE TITLE
Users on Vivaldi are unable to download state logs in popup

### ISSUE THREAD

**Issue by jacobc-eth** [MetaMask/metamask-extension#9195]
**Describe the bug**
The download state logs button in the MetaMask popup does nothing. The button does work properly in the full screen view.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Settings
2. Click on Advanced
3. Select Download State Logs
4. See nothing happens

**Expected behavior**
State logs should download.

**Browser details (please complete the following information):**

OS: Manjaro Linux
MetaMask Version 8.0.6
Browser Vivaldi | 3.2.1967.41 (Stable channel) (64-bit)

**Comment by PatrykLucka** [comment]
Looks like there's something wrong with the way Vivaldi handles file download in the extension popup. I tried many different alternative ways of exporting the file, but the only thing that worked is using `window.open()`, which creates new, empty tab. I even tried adding [file-saver](https://www.npmjs.com/package/file-saver), but it doesn't work as well.

Using `window.open()` might be a good option, but some time ago [Vivaldi stopped to being recognisable using User Agent](https://vivaldi.com/blog/user-agent-changes/). There even is a question asked in their official forum - [how to detect Vivaldi browser after these changes](https://forum.vivaldi.net/topic/42870/vivaldi-extension-browser-detect), but there is no answer so far. 

While dealing with other bug I found that there is an unofficial way to determine this, using `extData` property of `extension.tabs` object in background script, but it adds another level of complexity by requiring to communicate with background script on every download button click, so I'm not sure if it sounds like a good workaround.

Leaving these thoughts for further discussion.
