### ISSUE TITLE
Urgent: Transactions pending - Reset profil

### ISSUE THREAD

**Issue by 007STKL** [MetaMask/metamask-extension#9225]
Log:
[MetaMask State Logs.zip](https://github.com/MetaMask/metamask-extension/files/5072940/MetaMask.State.Logs.zip)

Dear Support:

I have pendig transactions. I already declined the transactions successfully. But after I declined them new pending transactions appear. (I didn't set any transactions.)

I tried the steps, described on the faq. I think the last possibility to solve this is to reset the account.
Is it possible to check if there is any else missing in the logs? 

Is there a risk to loose the imported customized tokens?

Best regards,
Steffen

<!--

**Comment by tmashuang** [comment]
> I have pending transactions. I already declined the transactions successfully. 

Judging from the state logs this statement should be incorrect. The discrepancy is on the tx with nonce of 352, which seems that there was an issue with attempting to "cancel" the tx, which just sends a transaction to the same account address just with an increased gas price. The value submitted and the method we use to increase the gas price left an unexpected error. The attempt
to cancel failed, thus not actually cancelling tx w/ nonce 352.

> But after I declined them new pending transactions appear. (I didn't set any transactions.)

The cancel/speed up tx functionality creates a tx with their respective parameters to submit to the network. Cancelling a tx just sends a tx with no value to the address that initiated the tx with a higher gas price. 

So the issue has deepened and there are several transactions submitted over not submitting tx w/ nonce of 352. As you can see that the node has not mined it, https://etherscan.io/tx/0x685175ea39ccd09a49f3132933dfbad2872cdb9f4306545552ce0ce417393fa0. So the remedy would be to send a tx w/ a nonce of 352, this will proceed to submit 353...357. Resetting your account in the Settings and sending a tx should send it with the subsequent nonce the network knows, which is 352.

**Comment by 007STKL** [comment]
> > I have pending transactions. I already declined the transactions successfully.
> 
> Judging from the state logs this statement should be incorrect. The discrepancy is on the tx with nonce of 352, which seems that there was an issue with attempting to "cancel" the tx, which just sends a transaction to the same account address just with an increased gas price. The value submitted and the method we use to increase the gas price left an unexpected error. The attempt
> to cancel failed, thus not actually cancelling tx w/ nonce 352.
> 
> > But after I declined them new pending transactions appear. (I didn't set any transactions.)
> 
> The cancel/speed up tx functionality creates a tx with their respective parameters to submit to the network. Cancelling a tx just sends a tx with no value to the address that initiated the tx with a higher gas price.
> 
> So the issue has deepened and there are several transactions submitted over not submitting tx w/ nonce of 352. As you can see that it has been dropped, and not mined, https://etherscan.io/tx/0x685175ea39ccd09a49f3132933dfbad2872cdb9f4306545552ce0ce417393fa0. So the remedy would be to send a tx w/ a nonce of 352, this will proceed to submit 353...357. Resetting your account in the Settings and sending a tx should send it with the subsequent nonce the network knows, which is 352.

**Comment by 007STKL** [comment]
Thank you @tmashuang for your fast response - it worked great!
