### ISSUE TITLE
MetaMask wallet extension  not open in chorme 

### ISSUE THREAD

**Issue by RansaPalana** [MetaMask/metamask-extension#9245]
I have tried to issue certificate using  "https://admin.opencerts.io/" this site but my metamask wallet extension is not working or not opening.

**Comment by RansaPalana** [comment]
console shows Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': Symbol(Symbol.toPrimitive) could not be cloned. error

**Comment by Gudahtt** [comment]
Thanks for the report! This appears to be a duplicate of #9234
