### ISSUE TITLE
Deprecate the network switch reload deprecation

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9254]
When we first started planning on adopting #3599, we were compelled by developers insisting it was a superior user experience.

Since then, there have been excellent points raised regarding security concerns related to allowing a provider to spontaneously change its meaning.

We also now have a road-map that has a path to multi-network connectivity that does not rely on a single provider.

We still have a very old deprecation warning related to this network reload, and I think it's about time we removed it, it still scares developers, and for basically no real benefit, we are probably not doing this anymore.

So I propose we bite the bullet, deprecate the deprecation, and remove the console warning.

**Comment by Powersource** [comment]
If nothing else please mute the console warning since it prints even when on completely unrelated websites :(

**Comment by Gudahtt** [comment]
So we are going to stop reloading on network change after all (ee here for details: https://github.com/MetaMask/metamask-extension/issues/9255#issuecomment-755411075). So that means this deprecation warning will go away with v9, though not for the reason stated in this issue.
