### ISSUE TITLE
Pages that have accessed the provider should reload on network change

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9255]
In the spirit of #9254 and [the discussion here](https://github.com/MetaMask/metamask-extension/issues/8077#issuecomment-637338683), and because of the dangers of exposing a provider to applications that can change its network while a transaction is in-flight, we should begin reloading pages that have touched the `ethereum` global, the same way we do for the `web3` global today.

This will be a breaking change, so ordinarily we would not consider it, but the alternative is leaving an open security concern related to provider mutability.

Since it would be a breaking change, we should be sensitive about the timing for this change.

Users suggested that a potentially non-breaking way to implement this would be to detect listeners for chainChanged, and only reload if none are found, though the security concern may remain.

**Comment by rekmarks** [comment]
Internally, we have gone back and forth about what to do with this. The entire team agrees that it would be best if the the page were reloaded by default. That said, making that the default would force us to add some means of changing the default behavior, and that didn't make it into the spec. We also provide the means for the user to reload the page on chain changes, via the `chainChanged` event. `ethers`, the most popular convenience library at the time of writing, leverages this to reload the page, by default.

So, we recommend that our users reload on chain changes unless they have good reason not to, but we won't do it for you.
