### ISSUE TITLE
Upon updating token details, the token became hidden

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9261]
A user reports that after updating token details with a new number of precision, the token disappeared.

Could be that we aren’t showing tokens under a certain precision, and should.

https://www.reddit.com/r/Metamask/comments/i4xy7c/metamask_shows_absurd_numer_of_dextools_dext/g1yms2d/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by Gudahtt** [comment]
It seems likely that the token configuration was invalid in some way, leading to a failed balance update. See #9057

**Comment by Gudahtt** [comment]
I'll close this for now, as it's likely a dupe of #9057
