### ISSUE TITLE
MetaMask Extension Brave MacOS Kernel Panic

### ISSUE THREAD

**Issue by ZephyrCrypto** [MetaMask/metamask-extension#9273]
iMac (late 2015) running Catalina - Latest Brave version. Never had any issues. Installed The MetaMask extension a few days ago and started getting forced re-starts. Classic kernel panic message. I’ve reset PRam etc. Kept getting the same issue. This extension is the only new addition so I’ve turned it off and no issues so far. This was occurring in the background. Not whilst using MetaMask. 

Anyone else experiencing this?  

If the Mac stays stable for the whole day I’ll turn it back on and send screen shots If it repeats. Let me know what would be helpful screenshot etc. 

Cheers 🍻

**Comment by Gudahtt** [comment]
Thanks for the report @ZephyrCrypto!

I can't think of how we might cause a kernel panic :thinking: Maybe if there is a bug in some browser extension API we're using.

It's difficult to proceed without steps to reproduce, so I'll leave this open a while until we get more information. Further verification from you that MetaMask is indeed related to these crashes would be greatly appreciated, as would any information about what you were doing at the time (e.g. had you used MetaMask _recently_, or any dapp that might have interacted with it?)

**Comment by ZephyrCrypto** [comment]
Hi @Gudahtt - My bad...... Turns out it's not MetaMask. It stayed stable for so long right after disabling but in the end I started getting the issue again. Looks like maybe it's hardware. What's the best way to delete this issue? First time on here.

Thanks

**Comment by Gudahtt** [comment]
No problem! Thanks for the update. I can close the issue.
