### ISSUE TITLE
Add feature to allow swapping using Uniswap or Balancer or 1inch or KyberSwap from within Metamask Wallet

### ISSUE THREAD

**Issue by dlokman** [MetaMask/metamask-extension#9276]
Projects have started integrating swaps from within wallet eg 2key swap https://www.2key.network/blog-posts/2key-v0-6-is-live.
Metamask does not have any in wallet swap service as of yet.

Please add feature to integrate swapping service within Metamask. Eg User should be able to swap ETH to USDC using any of the exchanges (user selects: eg Uniswap, Balancer, 1inch or Kyberswap) from within Metamask wallet.

**Comment by haxwell** [comment]
This is taken care of by #9482, yes?

**Comment by tmashuang** [comment]
Closed by #9482.
