### ISSUE TITLE
Securing Meta Mask google Authenticator

### ISSUE THREAD

**Issue by MrCleanerPickerUpper** [MetaMask/metamask-extension#9280]
**What problem are you trying to solve?**
Ledger and tezor users are having issues with windows not allowing hardware wallets to be connected. To make metamask more secure an option to have google authenticator from a secure enclave to make metamask more secure and user friendly.

**Describe the solution you'd like**
An option to connect a secure enclave such as google authenticator (cellphone confirmation to browser extension).

**Additional context**
To log in to meta mask an additional layer of having to input a code, also when making transactions.

**Comment by jacobcantele** [comment]
Thanks for this feature request @MrCleanerPickerUpper 

Would you mind making this request on our feature request board here: https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas

We try to have a single source of truth for user feature requests.
