### ISSUE TITLE
Contributor license agreements needed for removal of share-alike clause.

### ISSUE THREAD

**Issue by jameshilliard** [MetaMask/metamask-extension#9292]
Following up on #9285 here since I'm unable to reply in the original thread for some reason.

> We had a single dependency, abi-decoder, that is subject to a GPL 3.0 license. This dependency will be removed in #9290 , which will be merged before the next release of the MetaMask extension.

Note that removal of the dependency may not be sufficient as the interface to the dependency may be considered a derivative work. You may need to consult with a lawyer regarding this to be sure simply removing it is sufficient.

> A previous version of the MetaMask extension was licensed under an MIT license with a share-alike provision, and we did not properly transition from that license to a pure MIT license

The full name of the license is `The Ethereum Project Contributor Asset Distribution Terms ( MIT + Share-alike )` which looks to be a MIT derived license with additional terms, if the original intention was for this license to be pure MIT why would it contain `The Ethereum Project Contributor Asset Distribution Terms`? Maybe @kumavis can provide more details regarding the origins of this license as it looks to be more than just a MIT license with a share-alike provision.

In #886 @kumavis indicated that changing the license requires approval from the Ethereum Foundation:
> Move to a standard license. This requires OK from the Ethereum foundation.

This is also stated [here](https://github.com/MetaMask/metamask-extension/pull/885#issuecomment-262609769):
> I agree that we should move towards a pure MIT license in the future, but my understanding is that we would need approval from the Ethereum foundation to make this change, since the original license is mandated by the Ethereum Dev Grant that MetaMask was kick-started by.

further it is stated [here](https://github.com/MetaMask/metamask-extension/pull/885#issuecomment-262654373):
> In either case, since our license is bound by contract, I think we need to settle this with the license authors, not just with a pull request, but with an agreed-upon license correction (maybe identical to your cleanup, but not for us to say alone).

Was this permission ever obtained? From comments in that issue it seems that since this project took funds from Ethereum's DevGrants that they would have to approve the re-licensing. Is there a copy of this contract available?

> Also need a contributor agreement. Parity does a good job of this with their bot + form.

So it's pretty clear from that same issue that contributor agreements were recognized as being required for the re-license as well, were these ever obtained?

> This was a discrepancy in the description of the license. As you know, the actual license is established by the body of the license. While the term “share-alike” appears in the header of our pre-2018 license, the body of the license is verbatim the MIT license terms. Therefore, the MetaMask extension was only ever subject to an MIT license, without any share-alike requirement.

If it was a mistake you'll need to contact all contributors who contributed code between the time the share-alike clause was accidentally added and when it was removed and get them to agree to the removal. As they personally hold copyright to those contributions they would have to agree to the removal in order for the this project to be legally re-licensed. Whether or not the clause was a mistake or not is not actually relevant, what is relevant is what licenses their contributions were made under.

For any contributors within that time period that don't agree to the re-license you would need to remove/rewrite their contributions(and potentially derived contributions) before re-licensing.

**Comment by kumavis** [comment]
Thanks for your research and suggestions I can provide some additional context:

The original "Ethereum Project Contributor Asset Distribution Terms" license can be found [here](https://github.com/CommonAccord/Cmacc-Org/blob/a6564a66ff2dfeee6e34a4456a0d0096fd98d291/Doc/Wx/com/ethdev/Grant/Was/ContributorLicense_0.md)
I mistakenly appended an incorrect summary of the license (`MIT + Share-alike`) following the title.
We later discovered that the license text was identical to MIT, and changed the license title (and whitespace formatting) to match the standard MIT license, after community request. There was no change made to the terms of the license.

My comments were made before we sought legal counsel, so I wouldn't rely on those. I am by no means an expert on licenses, copyright, and contract law. If you have any additional questions about licenses or copyright you can reach out to our legal contact at legal@consensys.net
