### ISSUE TITLE
Ethereum Devgrant scheme conditions require writtern permission for relicensing

### ISSUE THREAD

**Issue by jameshilliard** [MetaMask/metamask-extension#9298]
Following up on #9292 in reply to @kumavis here since I'm unable to reply in the original thread for some reason.

> The original "Ethereum Project Contributor Asset Distribution Terms" license can be found here
I mistakenly appended an incorrect summary of the license (MIT + Share-alike) following the title.

So it looks like the no re-licensing restrictions are part of the [devgrant scheme conditions contractual obligations](https://github.com/CommonAccord/Cmacc-Org/blob/master/Doc/Wx/com/ethdev/Grant/Was/SchemeConditions_0.md) and not the "Ethereum Project Contributor Asset Distribution Terms".

See the following relevant sections:

Sec 6.2:
> Any ideas, concepts, processes, discoveries, developments, formulae, information, materials, improvements, designs, artwork, content, software programs, other copyrightable works, and any other product which you develop in connection with the Project (Project Work Product​), together with any Intellectual Property Rights necessary for the use of such Project Work Product, shall be released, in a timely manner and by a method dictated by us, under the Ethereum Project Contributor Asset Distribution Terms, or, with written permission from us, under a more restrictive licence.

My interpretation is that this is a contractual obligation separate from the licensing restrictions that does not allow Consensys to re-license the project under a license more restrictive than the MIT derived "Ethereum Project Contributor Asset Distribution Terms" unless written permission is obtained. Was this written permission obtained?

Sec 6.3:
> To the extent that any Project Work Product, or any Intellectual Property Rights necessary for the use of any Project Work Product, cannot be released under the form of licence specified in accordance with clause 6.2, you hereby unconditionally and irrevocably grant to us a non­exclusive, worldwide, fully paid and royalty­free, irrevocable, perpetual licence, with rights to sublicense through multiple tiers of free software sublicensees, to use, reproduce, distribute, create derivative works of, publicly perform and publicly display the Project Work Product in any medium or format, whether now known of later developed, and to use any Intellectual Property Rights necessary for the use of any Project Work Product for such purposes.

Sec 6.4:
> To the extent that any Project Work Product, or any Intellectual Property Rights necessary for the use of any Project Work Product, cannot be released under the forms of licence specified in accordance with clause 6.2 or clause 6.3, including without limitation any moral rights in the Project Work Product, you unconditionally and irrevocably waive, or shall use reasonable endeavours to procure that any necessary third party shall unconditionally and irrevocably waive, the enforcement of such rights, and all claims and causes of action of any kind against us or any third party to whom we license the Project Work Products, and, as far as is legally possible, any broadly equivalent rights in any territory of the world.

These above two clauses seem to be a catch all to ensure if the project is not compliant with Sec 6.2 for any reason you irrevocably waive the enforcement of any intellectual property rights connected with the project, and because of this any proprietary license payment/fee requirements would be completely unenforceable by Consensys by my interpretation.

Sec 6.5:
> You agree not to challenge our decision to release the Work Product under any open source licence we may select, and acknowledge that you shall have no right to select the open source license under which any Project Work Product is released.

This seems to very explicitly state that Consensys does not have the rights to select the license under which this project is released.

In any case the important part appears to be the written permission(which does not appear to have been obtained) required under Sec 6.2 to use a more restrictive license, so unless that was obtained the project can not be re-licensed to a more restrictive license such as a proprietary license.

**Comment by rekmarks** [comment]
We are not re-licensing existing code, and find nothing to suggest that we are violating the terms of the DEVgrant Scheme.

This is the third issue you have created regarding our license, the others being #9285 and #9292. Of those, this is the second issue of a speculative, non-actionable nature. If you continue to post similar issues, we will view it as spam, and do what is necessary to ensure that the issues in this repository are relevant to the project.

If you have any further inquiries about this topic, we remind you that you are free to email legal@consensys.net. I will now close and lock this issue.
