### ISSUE TITLE
Trezor connect outdated and not working

### ISSUE THREAD

**Issue by jimjimvalkema** [MetaMask/metamask-extension#9300]
Trezor connect says it is outdated and i am not able to send a transaction using the my trezor. 

![Screenshot from 2020-08-24 15-44-37](https://user-images.githubusercontent.com/29441202/91052232-75a0c080-e621-11ea-8c94-7c4df72ad7b7.png)

Details:
browser: brave (chromium fork)
os: debian 10
trezor version: 1.9.2 (latest)

**Comment by tmashuang** [comment]
Duplicate of #8349
