### ISSUE TITLE
.on({data, close}) deprecated but used in web3 constructor

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#9301]
**Describe the bug**
When initializing the current version of web3, Metamask throws two warnings about the events "data" and "close" being deprecated.

**To Reproduce (REQUIRED)**
In an HTML page, include `<script src="web3.min.js" />` which is [this file](https://github.com/ethereum/web3.js/blob/v1.2.11/dist/web3.min.js), the latest release from web3.  (I believe this also happens with earlier versions.) In Javascript run after the pageload, include `web3 = new Web3(window.ethereum)` and run this in a Metamask-enabled browser.

**Actual behavior**
Two console warnings: 
1. "MetaMask: The event 'data' is deprecated and may be removed in the future."
2. "MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193"

The warnings appear to be triggered by [this line](https://github.com/ethereum/web3.js/blob/87e668275ac7d9b8af7c909137fc0626c3866929/packages/web3-core-requestmanager/src/index.js#L101) and [this line](https://github.com/ethereum/web3.js/blob/87e668275ac7d9b8af7c909137fc0626c3866929/packages/web3-core-requestmanager/src/index.js#L125) respectively, in web3's `setProvider()` function which is [called](https://github.com/ethereum/web3.js/blob/87e668275ac7d9b8af7c909137fc0626c3866929/packages/web3-core-requestmanager/src/index.js#L45) in the RequestManager constructor which is [called](https://github.com/ethereum/web3.js/blob/87e668275ac7d9b8af7c909137fc0626c3866929/packages/web3-core/src/index.js#L53) in `packageInit()` which is [called](https://github.com/ethereum/web3.js/blob/87e668275ac7d9b8af7c909137fc0626c3866929/packages/web3/src/index.js#L44) in web3's constructor.

**Expected behavior**
The `ethereum` object can be passed as a parameter to the `web3` constructor or `setProvider()` function without warnings.

The official migration guide says [very little](https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3) about the provider that should be passed to a convenience library such as web3, but according to [this comment](https://github.com/MetaMask/metamask-extension/issues/7163#issuecomment-531075112), `window.ethereum` should be `=== web3.currentProvider` (until MetaMask stops injecting web3 and relies on dapps to provide that if needed, at which point the latter will only be defined if a dapp has set it).  [This example](https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider) in current official documentation also shows that `window.ethereum` should be usable as a `provider` object.

If `window.ethereum` does not satisfy the API web3 expects for a `provider` object, there should be significant updates to the documentation showing what if any alternative provider object should be passed to the web3 constructor when using MetaMask, OR if web3's expectations about the API for a `provider` object are incorrect they should be fixed, OR these methods should NOT be deprecated/removed and not throw deprecation warnings.  The latter seems like the most straightforward option to me, but I don't fully understand the reason why these functions are marked deprecated in the first place.

**Browser details:**
 - OS: Win10
 - Browser: Google Chrome 84.0.4147.105 (Official Build) (64-bit)
 - MetaMask Version 8.0.8
 - Web3 version 1.2.11

**Comment by rekmarks** [comment]
Hi @wbt, thank you for raising this issue. Those events are marked as deprecated because they're not included in EIP-1193 (the Provider API standard) or any of its derivative EIPs.

We're not removing either event for the foreseeable future, but third-party libraries, including `web3`, should stop using them. Our `window.ethereum` remains a valid constructor argument for `web3`.

I pointed this out on the issue you created in the `web3.js` repo.

Does this resolve your issue?

**Comment by wbt** [comment]
@rekmarks Thanks for your reply!  I think it would be appropriate to wait for a response from somebody on the web3 project before marking it resolved; it seems odd that these two widely used pieces of web3 software don't play nicely in this way.

**Comment by rekmarks** [comment]
AFAIK, the web3.js team is aware of it, as the new events were developed in tandem with some of their team members, e.g. @ryanio.

While warnings like this are annoying, at the end of the day, everything still works here. If I were managing `web3`, I wouldn't necessarily prioritize this either, but it is the web3.js team's problem to fix.

If web3.js doesn't fix this on their end, we're open to a feature request or PR for warning message silencing on our provider package: https://github.com/MetaMask/inpage-provider/

This is not the place for a discussion about provider warnings however, so I'll close this issue now.
