### ISSUE TITLE
Fox not consistently following password box

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9302]
Reported by Austin Griffith on Twitter:
https://twitter.com/austingriffith/status/1297959047014957056?s=21

**Comment by Gudahtt** [comment]
Was this experienced on an external monitor? If so, it's likely due to this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=971701

**Comment by austintgriffith** [comment]
Yes I think this is the chrome extension second monitor issue. 
The MM UI feels like it is hung up but if you use it on the main monitor it is fine.
Very scary when typing in a password or a large amount of DAI to send, but I think this is a chrome extension problem not a metamask problem.
Sorry about this become a ticket. At least I didn't "DO YOU KNOW WHO I AM" you on twitter. 😂

**Comment by jacobcantele** [comment]
Closing this for now. For anyone looking for resolution to this bug, please upvote the issue on the chromium site.
