### ISSUE TITLE
HELP! tokens sent without approval

### ISSUE THREAD

**Issue by khalid9393** [MetaMask/metamask-extension#9305]
![back log](https://user-images.githubusercontent.com/70194461/91143435-93266680-e6c3-11ea-817f-3cc8bb15b8aa.PNG)

Hi

I submitted a request but was not getting any reply so i am writing here

Support Request is # 48596

I was checking my Metamask wallet yesterday and I found out that
Without any sort of approval or recognition from myself.

Around 7.9 KTON has been transferred out from my wallet to a wallet I do not recognize.

My wallet address is:
0xDaC50976C3188707E6De5E2a1823b37E6645a085

Txn Hash for the transaction is:
0xDaC50976C3188707E6De5E2a1823b37E6645a085

The tokens were transferred to below:
0xd6cd1D9bDd0a781060438507045005DF137067C4
(I think there are many fishy transactions in the address
maybe i am not the only victim!!)

I attached back log screenshot, I'm not sure if it would help

But Is there any way you guys can help me for this problem?

Please give advise as I do not know what to do

Thank You

**Comment by rekmarks** [comment]
@khalid9393, I apologize for our delayed response. Our support team will reach out to you via your ticket. I will now close this issue.
