### ISSUE TITLE
Can you give an example how to use event connect or disconnect

### ISSUE THREAD

**Issue by vipkouyu** [MetaMask/metamask-extension#9312]
I have seen the doc and exanple app, and i don't find detailed usage。

I want to reload the page when connect or disconnect event happened, but the below code does't work,  I don't know why?

` ethereum.on('connect', (connectInfo) => {
	window.location.reload();
});`

`ethereum.on('disconnect', (error) => {
	window.location.reload();
})`

**Comment by jacobcantele** [comment]
Hi @vipkouyu, developer questions are best directed to the [Ethereum Stack Exchange](https://ethereum.stackexchange.com).
