### ISSUE TITLE
Hold Dfinity's Internet Computer keypairs

### ISSUE THREAD

**Issue by anthonymq** [MetaMask/metamask-extension#9315]
**What problem are you trying to solve?**
[Dfinity](https://dfinity.org/)
While building on the Internet Computer, I realised that for the moment, they have no ways to keep our authentication keypairs.
I know they're still in early stage but it could be a great feature for Metamask to become the gateway to the Internet Computer.

**Describe the solution you'd like**
Add a section to configure IC identities.

Sincerly,
Anthony

**Comment by jacobcantele** [comment]
Hi @anthonymq, would you mind moving this to our feature request board?

https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests-Ideas

Additionally, its worth noting that this should be possible with the MM Snaps plugin system when it becomes available.
