### ISSUE TITLE
Digit correction with meta mask only

### ISSUE THREAD

**Issue by illogicalcodes** [MetaMask/metamask-extension#9316]
It seems some digit bug as i have purchased only 1.518 XIOT however it is showing 1518 & showing the value for the respective xiot,
I have tried to send it MEW & other wallets, it is working fine, however, it seems an issue with matamask only. please refer to the below snippet for reference:
![image](https://user-images.githubusercontent.com/49881781/91330627-55baf980-e7e7-11ea-8274-69fd2ec06a29.png)

Also find the answer of the required information:
*  Expected Behavior: it should show the value with fraction.
  *  Actual Behavior: it is removing the fraction
  *  Browser Used: google chrome
  *  Operating System Used: windows 10

can someone please review & investigate this bug?

**Comment by Gudahtt** [comment]
How was this token added? Did you go through the "Add Token" flow, or was this proposed by a dapp in a transaction?

**Comment by illogicalcodes** [comment]
Yeah i did go through the add token flow.

**Comment by Gudahtt** [comment]
Thanks! Then my guess is that you didn't set the `decimals` field to the correct value.

When you add the token through the add token flow, it's up to you to ensure all fields are correct. It's not particularly user-friendly at the moment unfortunately, so mistakes like this are easy to make.

You can fix this by hiding the token, then re-adding it with the correct `decimals` value.

I'll close this for now as I don't think it's a bug, but please say so if you have reason to believe otherwise. If you'd like more assistance with the add token flow, I'd suggest contacting support here: https://metamask.zendesk.com/hc/en-us/requests/new

**Comment by illogicalcodes** [comment]
I have crosschecked & add the decimal value as i actually thought of this.
But it did not work post correction of decimal value.

Its definitely a bug

**Comment by Gudahtt** [comment]
I see - in trying to reproduce this, it doesn't let me edit the decimals field either :thinking: 

Could you submit a support ticket with state logs? That would help immensely with investigating this problem. The instructions are here: https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-

**Comment by illogicalcodes** [comment]
Do I need to go through the support cycle to report a bug now?

Regards,
Royal

**Comment by Gudahtt** [comment]
Not necessarily, but it will be difficult to fix this bug until we can reproduce it. Certainly we can't be confident it has been fixed until we have reproduced it.

In this case, I suspect state logs would be a huge help in finding a way to reproduce this issue. Creating a support ticket is the only way we allow submitting state logs, as it's the easiest way we can ensure they are submitted securely.

If you don't want to create a ticket or submit state logs, that's OK. It just might take a bit longer to investigate the bug.

**Comment by illogicalcodes** [comment]
I can wait for longer, i dont have any problem with that.

Regards,
Royal

**Comment by tmashuang** [comment]
Im going to close this, there have been numerous changes to the token tracker and fixes that might have addressed this issue. For future GH issues involving state logs and support, please add the ticket number in the comment for ease of reference.
