### ISSUE TITLE
Failed transaction (eth-js rpc error) when speeding up a transaction

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-extension#9317]
**Describe the bug**
Speeding up a transaction (with new custom gas price value) results in a failed transaction message every time, instead of sending the updated transaction.

**To Reproduce**
1. Send initial transaction
2. Choose Speed up
3. On the Advanced tab, enter a slightly higher custom gas price than the initial one
4. Press Send
5. The new transaction is not sent, this error is displayed as a notification:

> Failed transaction
> Transaction <nonce> failed! Error: [ethjs-rpc] rpc error with payload {"id":{thirteenDecimalDigits},"jsonrpc":"2.0","params":["0x{hundredsOfHexDigits}"],"method":"eth_sendRawTransaction"} [object Object]

6. The activity history incorrectly shows even the original transaction as failed
7. If I press Retry, I get a similarnotification as above, but maybe with different id and params
8. Once the initial transaction is confirmed, the activity history forgets the whole thing and marks the transaction as successful

**Expected behavior**
The updated transaction is sent and Metamask registers the change

**Browser details:**
Mozilla Firefox 68.12.0esr (64-bit)
MetaMask 8.0.9

**Comment by dmolina79** [comment]
Same error in MM 8.0.8 Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by gwenvador** [comment]
I also have the same issue with MM 8.0.8 and Brave Version 1.13.82. It is random as sometimes it works, sometimes not. I would say it fails 75% of the time and quite often with ledger wallet interaction.

This is terrible user experience as when the error occur we cannot interact with the transaction anymore it just says failed. I have to manually speed the transaction via myetherwallet which is pretty difficult and cumbersome.

**Comment by yarco** [comment]
same thing

**Comment by fourthespada** [comment]
Facing the same issue on Chrome Version 85.0.4183.102 (Official Build) (64-bit). 

Tried to speed up an transaction underestimated by metamask, and tried speed up with average, then retry with high afterwards.

**Comment by bobtista** [comment]
Same thing, just cost me a lot of money

**Comment by blueberry6401** [comment]
Will this be fixed any time soon? Even if I tried create a new transaction with the same nonce, it failed, sometimes it works.

**Comment by gwenvador** [comment]
Hopefully with more people reporting this issue this will get more visibility. This is in my opinion quite a big issue as once the transaction is failed when speeding up it is stuck without being able to do anything..
 I can't find how to create a new transaction with the same nonce with metamask (only manually via myetherwallet).

**Comment by faustiandilemma** [comment]
Same thing just happened to me.

**Comment by gwenvador** [comment]
One thing that might fix temporary is to reset metamask (Settings -> Advanced -> Reset). This reset the transactions history not your seed. 
I have also noticed that the issue happens again when I switch to a new hardware wallet (connecting to a new address). Multiple hardware wallet still not supported (pretty lame)..

**Comment by john-light** [comment]
I am also having trouble speeding up transactions, except I got a different error than the OP reported:

![speedupfail](https://user-images.githubusercontent.com/9424721/100036243-dc26ad80-2dcd-11eb-9fcc-77a320c5a00e.png)

This was a normal ETH transfer, gas limit 21,000 and gas price 80gwei so the "underpriced" error message is confusing.

Let me know if this should be a separate issue.

**Comment by tmashuang** [comment]
Related to #9053

**Comment by mehmet-demir** [comment]
Same problem.

![Failed transaction](https://user-images.githubusercontent.com/32993126/101990627-f52dca80-3cb8-11eb-9a9a-d682a2ad2faa.png)

**Comment by Gudahtt** [comment]
Thanks for the report! Is anyone still able to reproduce this on the latest version of MetaMask? I tried speeding up a few transactions and didn't encounter this.

**Comment by michalisFr** [comment]
I've encountered the same error with the speed up button and when doing it manually, ie change the nonce to the tx I want to speed up. It seems though that if I enter a gas price above a certain level it goes through. For example, I had a tx at 124 gwei. Then I sped it up at 138. My attempts to speed it up further (manually) with a new tx failed when I entered gas prices in the range 140-150, but it went through when I entered 154 gwei.

**Comment by fourthespada** [comment]
Yes, I haven't faced the exact issue since then either, and I conjecture that it's as the above poster suggested... there seems to be a minimum gas fee increase requirement of 10%.  Not sure if this is an infura limitation or something else, haven't been able to find a source that explains it.  Now there is a new error that comes back specifically states the increase is not enough - so it is a different error message than when the bug was originally submitted (infura API perhaps updated to return a clearer message?).  I cannot recall if I tested this via the wallet or via uniswap.

**Comment by gokujj** [comment]
i think time its come for switch wallet..  thanks metamask but because of this error i reset my acc 2times and lost all authorization for spend tokens the fees is too much now.. cya

**Comment by manavsharma136** [comment]
i am doing speed up transaction and it is showing error message of nonce and speed up doesnt happen any solution

**Comment by metasiva** [comment]
> One thing that might fix temporary is to reset metamask (Settings -> Advanced -> Reset). This reset the transactions history not your seed.
> I have also noticed that the issue happens again when I switch to a new hardware wallet (connecting to a new address). Multiple hardware wallet still not supported (pretty lame)..

It is not working for me. For me all transaction failed with "Error: [ethjs-query] while formatting outputs from RPC" Code - 32602.
Can't able to do any transactions.

**Comment by johnnyshankman** [comment]
I get code `-32000` and something about a replaced tx. I'm using a Ledger.
