### ISSUE TITLE
Always show name of Token

### ISSUE THREAD

**Issue by 2ge** [MetaMask/metamask-extension#9318]
I didn't find open issue, so I am posting.

**Describe the bug**
token name is sometimes hidden, which makes extension not really usable

**Expected behavior**
always show token name

**Screenshots**
example of BAT token.
![image](https://user-images.githubusercontent.com/1067032/91521484-f1508500-e921-11ea-8379-c5301100d6ba.png)

example of wETH:
![image](https://user-images.githubusercontent.com/1067032/91521595-37a5e400-e922-11ea-8c65-74c6edefc6f1.png)

**Browser details (please complete the following information):**
- OS X
- Brave with latest Metamask 8.0.8

**Comment by jacobcantele** [comment]
@2ge did you modify how many decimals are being displayed? That does not appear to be the default behavior.

**Comment by 2ge** [comment]
@jacobcantele I did not. What I did now:

- I "hide" BAT
- I added BAT using Assets/Add Token, selected BAT (default)
- Still showing without token name (there is a lot of decimals)

I am not sure, what I should do to fix this.
