### ISSUE TITLE
JSON-RPC response is not to-spec.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#9319]
**Describe the bug**
JSON-RPC response when using built-in network connections includes an error field which is not to-spec.

**To Reproduce (REQUIRED)**
1. Open developer console while MetaMask is installed and connected to a default network.
2. `window.ethereum.sendAsync({ jsonrpc: '2.0', id: 1, method: 'eth_getStorageAt', params: [ '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f', '0x0', 'latest' ]}, (error, result) => console.log('error' in result))`
3. Notice that `true` is printed.
4. Go to [JSON-RPC specification response object](https://www.jsonrpc.org/specification#response_object) and notice that it says:
    ```
    error
        [...]
        This member MUST NOT exist if there was no error triggered during invocation.
        [...]
    ```

**Expected behavior**
The `error` property does not exist on the returned result object if an error did not occur.

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 79.0
 - MetaMask Version: 8.0.6 & 8.0.9

**Additional context (Error Messages, etc.)**
The problem seems to be dependent on the backing Ethereum client being talked to.  If I connect to my own personal Nethermind client I do not get the error.  However, MetaMask should be either talking to spec compliant backing clients only or it should be cleaning up responses from the backing client that are not to-spec.

**Comment by rekmarks** [comment]
I am unable to reproduce this on `develop` today, and we have made significant changes to a lot of the involved code, so I'm going to assume that it's fixed.
