### ISSUE TITLE
Different Uniswap Pools are not clearly labeled

### ISSUE THREAD

**Issue by davecraige** [MetaMask/metamask-extension#9325]
**Describe the bug**
Different Uniswap Pools are not clearly labeled in Metamask

**Additional context (Error Messages, etc.)**
It would be easier if there was better naming conventions for the different Uniswap pools so they would clearly show up in Metamask.

**Screenshot**
These are all different pools but they are unfortunately all named the same (UNI-V2).
<img width="359" alt="Screen Shot 2020-08-28 at 5 47 02 PM" src="https://user-images.githubusercontent.com/2782676/91624505-f3d0d000-e95d-11ea-99f5-a4a866504c1f.png">

**Comment by tmashuang** [comment]
The contracts are similar and the symbols are all the same, 
https://github.com/Uniswap/uniswap-v2-core/blob/master/contracts/UniswapV2ERC20.sol#L10. You have the option to edit the symbol when manually adding the contract address under Custom Token.
