### ISSUE TITLE
Amount not reflecting only token is showing up

### ISSUE THREAD

**Issue by csushal** [MetaMask/metamask-extension#9327]
I have swapped Ether to YFIE token through uniswap. YFIE toke reflected in metamask, but the token value is not reflecting.  Help me.
![WhatsApp Image 2020-08-30 at 10 18 44](https://user-images.githubusercontent.com/70470060/91656464-23481f80-eab9-11ea-99a4-a358d3a65463.jpeg)

**Comment by jacobcantele** [comment]
Hi csushal,

Please reach out to support.metamask.io for help with these issues.
