### ISSUE TITLE
Token appears on my wallet on etherscan but Metamask says i've 0 of them.

### ISSUE THREAD

**Issue by Joalland** [MetaMask/metamask-extension#9328]
**Describe the bug**
I've buy 2 YFX (https://etherscan.io/address/0x2844D5E695EeB37d6Ca2A85aDB8A254C81b7C0E0), they appear on my etherscan public wallet :
![YFX](https://user-images.githubusercontent.com/47032753/91667085-44812e00-eb02-11ea-8a40-50cba8edec46.png)
Then clicking on it and copy / pasting it's contrat (as i've done a hundred time) and adding a custom token, Metamask shows an amount of 0 YFX :
![image](https://user-images.githubusercontent.com/47032753/91667202-fcaed680-eb02-11ea-82cc-414dc8963f90.png)
![image](https://user-images.githubusercontent.com/47032753/91667240-629b5e00-eb03-11ea-83d0-62343e9375c5.png)

**Expected behavior**
Metamask to shows the 2 YFX

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser : Firefox Browser 80.0 (64-bit)]
 - MetaMask 8.0.9

**Comment by tmashuang** [comment]
Can you send your state logs to support@metamask.io and mention this issue? Thanks.
