### ISSUE TITLE
MetaMask - RPC Error: Network request failed error from dApp page

### ISSUE THREAD

**Issue by hoonsubin** [MetaMask/metamask-extension#9335]
**Describe the bug**
After connecting the extension with the dApp. the `MetaMask - RPC Error: Network request failed` seems to continue and it is impossible for users to interact with the page.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. https://lockdrop.plasmnet.io/#/lock-form/second-eth
2. Connect MetaMask with the page
3. Wait

**Expected behavior**
A clear description of what you expected to happen.

MetaMask should have established a connection with the Infura provider and make RPC requests to the Ethereum blockchain.

**Screenshots**

![bandicam 2020-09-01 10-23-39-855](https://user-images.githubusercontent.com/40356749/91784184-3be14280-ec3d-11ea-87a8-a66029d6a81d.jpg)

**Browser details (please complete the following information):**
 - OS: Windows, Linux Ubuntu, MacOS
 - Hardware Wallet Ledger, Trezor
 - Browser Chrome, Chromum-based
 - MetaMask Version 8.0.8

**Additional context (Error Messages, etc.)**
The error did not happen before and there were no noticeable code changes as well.
And this issue only seems to affect this contract https://etherscan.io/address/0xa4803f17607B7cDC3dC579083d9a14089E87502b while the other contracts are functioning fine.

**Comment by brad-decker** [comment]
@hoonsubin thanks for reporting this issue, I was able to reproduce. It seems like the dapp in question is making thousands of `getTransactionByHash` calls every second, resulting in thrashing the MetaMask connection to Infura. If this dapp is within your purview could you check to see if there is some over fetching happening there?

**Comment by vitalycool** [comment]
I have this problem when try connect to Metamask 

![image](https://user-images.githubusercontent.com/15956911/92234264-87ad1980-eed3-11ea-9610-5c1c82382452.png)

**Comment by hoonsubin** [comment]
The issue has been solved. It looks like there was a hard limit on the event size. Using a separate cache server to periodically store contract events helped bypass this limitation
