### ISSUE TITLE
API: How to get the name (user set in the MetaMask) of the wallet?

### ISSUE THREAD

**Issue by Jack-Works** [MetaMask/metamask-extension#9336]
**What problem are you trying to solve?**  
We're requesting access to MetaMask wallet by https://github.com/MetaMask/extension-provider. But it seems no way to get the name of the wallet.

**Describe the solution you'd like**  
Is there an RPC method to get the name that the user set?

**Comment by jacobcantele** [comment]
Hi Jack, enabling the experimental 3box integration will help you with this. It is still highly experimental and not officially supported yet, but you can find it in Settings -> Advanced.

**Comment by Jack-Works** [comment]
hmm is there any document about it? after the user enable the experimental flag, how can I get the wallet name programmatically?
