### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by harshjv** [MetaMask/metamask-extension#9338]
CORS issue with Infura only when site access is set to "When you click the extension"

```
Access to XMLHttpRequest at 'https://api.infura.io/v1/jsonrpc/mainnet/eth_blockNumber?params=%5B%5D' from origin 'chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

<img width="333" alt="Screenshot 2020-09-01 at 4 19 16 PM" src="https://user-images.githubusercontent.com/2311316/91840816-ee7dc900-ec6e-11ea-97b8-c510c4f78bd8.png">

**Steps To Reproduce**
1. Right click on MetaMask icon
2. This can read and change site data, select "When you click the extension"
3. Lock the wallet
4. Try to unlock the wallet

**Environment details:**
 - OS: macOS 10.15.6
 - Browser: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
 - MetaMask: 8.0.8

**Comment by jacobcantele** [comment]
Hi harshjv,

Removing the permissions that MetaMask relies on isn't really a supported behavior. Even if we resolved this CORS issue, I think there will likely be dozens of other problems trying to use the extension in this way. Apologies, but I'm going to close this issue for now.

**Comment by AoDev** [comment]
Hi, I faced this issue as well.

* The first problem is not understanding what's happening. 

* The second is, while checking "all sites" solved the issue, why can't we choose which site we want Metamask to interact with?

**Comment by RomanHiden** [comment]
I am affected as well
