### ISSUE TITLE
“Gas limit must be at least 21000” flashes on screen before confirmation

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#9345]
**Describe the bug**
When a transaction is triggered, a red error message stating "Gas limit must be at least 21000" briefly flashes on the MetaMask popup above the reject/confirm buttons.  While it disappears quickly following gas estimation, the error messages confuses users into thinking there is something wrong with the Dapp or that they are doing something incorrectly in a way that can mess things up.

**To Reproduce (REQUIRED)**
Click on an element in a Dapp's web interface to trigger a transaction, especially on an older/slower computer or one running a heavy background computational load (to make it more visible).  The bottom of the MetaMask popup will briefly show the following, while it is estimating gas usage to provide a gas limit for the transaction:
![image](https://user-images.githubusercontent.com/563406/91996041-88448500-ed06-11ea-8d3f-05ed23b8fccd.png)

Previously, the Confirm button was active during this time, and if the user was quick enough about clicking Confirm, the transaction would be issued with a gasLimit of 0, causing the transaction to fail.  Disabling the Confirm button during at least the majority of gas estimation helped improve the user experience, but the red ALERT flashing up still alarms users into thinking something is wrong.

**Expected behavior**
Instead of "ALERT: Gas limit must be at least 21000" by default, MetaMask keeps track of whether or not a nonzero gasLimit has been added to this transaction before. If it has (and e.g. the user changed it down to a lower value), then show the alert. If not, and the gas estimator is still running, maybe show the "transaction fee" as three dots or a loading spinner or something like that to indicate something is happening. If the gas estimator is not still running and the gas limit is still too low, maybe display an "ALERT: Gas estimation failed; please provide a gas limit." 

**Browser details (please complete the following information):**
 - OS: Win10
 - Browser: Google Chrome | 84.0.4147.105 (Official Build) (64-bit)
 - MetaMask Version 8.0.8

**Comment by lasanja1** [comment]
I am encountering this error too. How can I fix this issue?

**Comment by cloud9020locki** [comment]
Hi, I fix this issue via the ```gas: '0x5208'```. MetaMask on this page https://docs.metamask.io/guide/sending-transactions.html#example telling wrong to the developers about the gas limit.
Also, we can find out the ```gas price``` like this: <br>
```  
web3.eth.getGasPrice().then((result) => {
    const gas_price=web3.utils.fromWei(result, 'ether');
    console.log("gas price is: ",gas_price);
  })
  ```
  you can pass the object like this:
  ```
  gasPrice: gas_price,
  gas: '0x5208' //gas limit must be 21000.
  ```

**Comment by lasanja1** [comment]
Thank you @cloud9020locki , I will try it out.

**Comment by anipaul2** [comment]
Do we have to  change some setting in metamask to not show this?
I can't figure it out why it shows like this.

**Comment by varunseth5788** [comment]
i would like to contribute to this issue.
or need any other help.

**Comment by danjm** [comment]
@varunseth5788 feel free to open a PR

**Comment by danjm** [comment]
This is likely no longer an issue. I will close once I find the commit that removed the gas warning in question

**Comment by merlinico** [comment]
Still an issue.

**Comment by niecyqueendiva** [comment]
#19557

**Comment by wbt** [comment]
I don't think this should be closed without an improvement.

**Comment by wbt** [comment]
I still don't think this should be closed without an improvement.

**Comment by wbt** [comment]
I upgraded my machine, so it's hard to tell regarding continued reproduction.  After @danjm's comment there was one indicating the issue was still present, and the comment indicated an intent to link to some removal/fix PR which never happened either. That's what led to my points above.
