### ISSUE TITLE
Does the 'vault' just keep the last used seed phrase?

### ISSUE THREAD

**Issue by C-E-Rios** [MetaMask/metamask-extension#9346]
Does the seed phrase stored in the vault only reference the last seed used? And then does it change it somehow?

If not, does anyone know how I can possibly retrieve my main account using just the password and the metadata in the browser/extension?

**Comment by tmashuang** [comment]
> does the seed phrase stored in the vault only reference the last seed used? And then does it change it somehow?

Yes, when entering a new seed phrase the vault data gets overridden by the new one.

**Comment by C-E-Rios** [comment]
> > does the seed phrase stored in the vault only reference the last seed used? And then does it change it somehow?
> 
> Yes, when entering a new seed phrase the vault data gets overridden by the new one.

Shoot. Is there anything else on my machine browser/application data through which I could restore my account?

**Comment by tmashuang** [comment]
Unless you keep regular OS backups on files specifically targeting the browser's extension data, most likely not possible.

**Comment by C-E-Rios** [comment]
> Unless you keep regular OS backups on files specifically targeting the browser's extension data, most likely not possible.

Shoot. Shoot. I can see there's a bunch of MetaMask related data in Brave's IndexDB folder. If anyone is able/willing to help me retrieve my account, I'll be willing to pay.
