### ISSUE TITLE
[IMPORTANT REQUEST] Compatibility with Firefox Daylight

### ISSUE THREAD

**Issue by DaniellMesquita** [MetaMask/metamask-extension#9347]

**Comment by tmashuang** [comment]
This is not depended on us, https://support.mozilla.org/en-US/kb/recommended-extensions-program.

**Comment by DaniellMesquita** [comment]
"**May I suggest extensions to become Recommended?**
Yes. If there’s extension you feel should be Recommended, please email amo-featured [at] mozilla [dot] org with a link to its AMO listing page."
