### ISSUE TITLE
Warn user when sending a token to the token's own contract address.

### ISSUE THREAD

**Issue by oxidizer** [MetaMask/metamask-extension#9350]
**What problem are you trying to solve?**
Users repeatedly nuke funds by accidentally sending a token to the token's own contract.

**Describe the solution you'd like**
Issue a warning if a user is about to send a token to the token's own contract.

**Comment by PatrykLucka** [comment]
Looks like duplicate of #3185

**Comment by Gudahtt** [comment]
Thanks for the suggestion @oxidizer ! I'll close this as a duplicate of #3185 . This has already been implemented, and will be included in the next release.
