### ISSUE TITLE
Metamask Sign In Unsuccessful

### ISSUE THREAD

**Issue by anadeem49** [MetaMask/metamask-extension#9352]
**Describe the bug**

I was recently assigned to create a React UI for the Faucet.sol contract (https://github.com/zapproject/zap-ethereum-api/blob/master/contracts/token/Faucet.sol) but I have had several failed attempts to login to Metamask by importing an account using the seed phrase.

1. I first installed the Metamask google chrome extension & went to the main Ethereum network
2. Next, I clicked on  'import using account seed phrase'
3. Then, I wrote a seed phrase of at least 12 words
4. Created a new password and made sure it matched the confirmation

**Expected behavior**
I expected it to let me create my wallet but I got "incorrect password."

**Comment by jacobcantele** [comment]
Hi @anadeem49 , for support, please reach out to our support team at support.metamask.io
