### ISSUE TITLE
Is it possible to allow permissions with a smart contract and not a website?

### ISSUE THREAD

**Issue by terencechow** [MetaMask/metamask-extension#9357]
I was on a defi website getting ready to interact with a contract of an erc20 token. The interactions required an approval followed by a deposit.

I wanted to interact with it on etherscan instead of the website because the website did not have SSL. Having approved on etherscan, I went back to the website expecting the deposit button to be enabled. (I did this because the contract was a proxy and I wasn't sure what the actual contract address was). However the deposit button was still disabled. Clicking the allow button on the website popped up metamask asking me for permissions to approve the spend again.

I wanted to provide my permissions to a smart contract, not a website. Is that possible? Or is that too much of a security risk in the sense that ppl don't really look at hashes?

**Comment by jacobcantele** [comment]
Hi @terencechow , that isn't currently possible, but you can open up a feature request here: https://metamask.zendesk.com/hc/en-us/community/topics/360000682552-Feature-Requests
