### ISSUE TITLE
PENDING TRANSACTIONS

### ISSUE THREAD

**Issue by sdaks4me** [MetaMask/metamask-extension#9358]
**Describe the bug**

The transaction shows pending at metamask but Txn can not be located by etherscan

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

the transaction needed to go throw after paying higher gas fee

**Screenshots**
<img width="960" alt="2020-09-05 (1)" src="https://user-images.githubusercontent.com/70801258/92303500-d4493100-ef75-11ea-897d-4b15ce43aae2.png">

**Browser details (please complete the following information):**
 - OS: [Windows]
 
 - Browser [Version 85.0.4183.83 (Official Build) (64-bit)]
 - MetaMask Version 8.0.8

**Additional context (Error Messages, etc.)**
Add any other context about the problem

**Comment by tmashuang** [comment]
You can send your state logs to https://metamask.zendesk.com/hc/en-us/requests/new and reference the ticket number.

Most likely backed up transactions due to high network gas prices and overusing the speed up and cancel transaction feature.
