### ISSUE TITLE
'eth_accounts' unexpectedly updated accounts.

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#9370]
**Describe the bug**
Just got this issue in the console. Not sure what caused it unfortunately, but as it says "Please report this bug", I decided to create the issue 

```
inpage.js:1 MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug. []length: 0__proto__: Array(0)
_handleAccountsChanged @ inpage.js:1
n @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
Bt @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:15
write @ inpage.js:15
b @ inpage.js:15
(anonymous) @ inpage.js:15
v.write @ inpage.js:15
y @ inpage.js:15
h @ inpage.js:8
s.emit @ inpage.js:8
_ @ inpage.js:15
w @ inpage.js:15
b.push @ inpage.js:15
_write @ inpage.js:15
b @ inpage.js:15
(anonymous) @ inpage.js:15
v.write @ inpage.js:15
y @ inpage.js:15
h @ inpage.js:8
s.emit @ inpage.js:8
_ @ inpage.js:15
w @ inpage.js:15
b.push @ inpage.js:15
o._onMessage @ inpage.js:15
postMessage (async)
o._write @ contentscript.js:15
b @ contentscript.js:15
(anonymous) @ contentscript.js:15
v.write @ contentscript.js:15
y @ contentscript.js:15
h @ contentscript.js:8
s.emit @ contentscript.js:8
_ @ contentscript.js:15
w @ contentscript.js:15
b.push @ contentscript.js:15
_write @ contentscript.js:15
b @ contentscript.js:15
(anonymous) @ contentscript.js:15
v.write @ contentscript.js:15
y @ contentscript.js:15
h @ contentscript.js:8
s.emit @ contentscript.js:8
_ @ contentscript.js:15
w @ contentscript.js:15
b.push @ contentscript.js:15
_write @ contentscript.js:15
b @ contentscript.js:15
(anonymous) @ contentscript.js:15
v.write @ contentscript.js:15
y @ contentscript.js:8
h @ contentscript.js:8
s.emit @ contentscript.js:8
_ @ contentscript.js:8
w @ contentscript.js:8
b.push @ contentscript.js:8
o._onMessage @ contentscript.js:8
```

**To Reproduce (REQUIRED)**
As mentioned, I am not sure how it came about, but I was switching network when it happened

**Browser details (please complete the following information):**
 - OS: Windows 10 (64bit)
 - Browser Chrome Version 87.0.4252.0 (Official Build) dev (64-bit)
 - MetaMask Version 8.0.8

**Comment by rekmarks** [comment]
Hey @wighawag, thanks for reporting this! Have you seen this error in version >=8.1?

**Comment by wighawag** [comment]
I encountered that issue while I was testing my wallet library so I was testing lots of edge case, like switching network, accounts, etc...

I did not have the opportunity to test that heavily again, so cannot really answer. But I'll let you know if I can see this error again or if after testing I cannot reproduce it.

**Comment by Gudahtt** [comment]
Thanks again for the heads up! I'm going to close this now as this warning has been removed from the inpage provider altogether, so it should now be impossible for this to be thrown.

**Comment by wighawag** [comment]
I just got the same error with metamask 9.03:

```
inpage.js:1 MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug. Array(1)0: ...
_handleAccountsChanged @ inpage.js:1
```

**Comment by Gudahtt** [comment]
Oh, my mistake. I thought this message was removed in [this PR](https://github.com/MetaMask/inpage-provider/pull/121/), but it was not. I'll re-open this for investigation.

**Comment by lxhyl** [comment]
I get this bug too. 
Chrome MetaMask  v10.14.1.   
I have a get balance request after change account in MetaMask. The saw this error.

**Comment by vandan** [comment]
Needs reproduction on latest version of the extension.
