### ISSUE TITLE
MetaMask encountered an error

### ISSUE THREAD

**Issue by Roundtree-Larry** [MetaMask/metamask-extension#9371]
**Describe the bug**
after clicking on metamsk extension on firefox it give me "MetaMask encountered an error"
"Try again by closing and reopening the popup, or contact support at support@metamask.io"

**To Reproduce (REQUIRED)**
full error script:

Message: q[D] is undefined
Code: TypeError
Stack:
[1575]</O<@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui.js:180:800414
n@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:135:20815
require<[865]</r.wrapMapToPropsFunc/</n.mapToProps@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:135:20952
n@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:135:20815
a/<@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:135:19656
S/q<@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:135:13050
useMemo@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:63534
useMemo@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:184:5250
S@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:135:12995
ca@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:59367
Ya@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:67589
Ha@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:67408
Ga@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:67127
Pu@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:107861
bl@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:90055
pl@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:89978
ol@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:87326
Xi/<@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:45768
require<[949]</r.unstable_runWithPriority@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:220:3472
Gi@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:45477
Xi@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:45715
Yi@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:45648
ul@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:87699
Xl@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:113230
render@moz-extension://608bd35c-9927-46f4-aa00-6cfef38c542a/ui-libs.js:117:115151
[1756]</</r.default/</<@moz-extension://608bd

**Screenshots**
![image](https://user-images.githubusercontent.com/54907197/92416929-9b68b200-f157-11ea-82e6-e0b551eb8b30.png)
![image](https://user-images.githubusercontent.com/54907197/92416946-ade2eb80-f157-11ea-9fba-8890d2f7d322.png)

**Browser details (please complete the following information):**
 - OS: windows10
 - Browser Firefox browser 80.0.1 (64 bits)
 - MetaMask Version /* really don't know. I install it alike 6month ago, but I let updats as default */

**Additional context (Error Messages, etc.)**
I get that error just 3d ago.. I think, (just think) that happen after update my firefox

hope I can find help, Thank you

**Comment by tmashuang** [comment]
Seems the error is associated with the Confirm Transaction Screen, [confirm-transaction-base.container.js:93](https://github.com/MetaMask/metamask-extension/blob/b9f5f1c2c2bea8c4ef178cc2a55a14467b952e84/ui/app/pages/confirm-transaction-base/confirm-transaction-base.container.js#L93), was the screen left in that state for 6 months? There have been changes since that could have effect the way we obtain that account and it might have corrupted the addon state. If so, I believe navigating to full screen view in a tab and clearing this transaction should get past this error. Are there any imported accounts?

**Comment by Roundtree-Larry** [comment]
THank you for your help.  no this screen was from yesterday which is 09/08/2020

**Comment by tmashuang** [comment]
Have you ever viewed MetaMask in a tab, the full screen view? You need to know the addon UID and navigate to `moz-extension://ADDON_UID/home.html#settings/advanced` and click the Reset Account button.

**Comment by Roundtree-Larry** [comment]
Oh it solved and I don't know even how. but I after re-do I figure out what is the probelm and hope you can try in your own too.
if I set network in rinkeby I get the error. so I restart browser and change network to mainnet and it work now
