### ISSUE TITLE
Reduce log size for long series' of tx retries

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9372]
A user reported bad performance and provided state logs.

Their state logs show one tx in particular as the clear culprit.

The tx had a series of errors, each marked as a warning (probably should have marked as failed on first err):
- "insufficient funds for gas * price + value"
- "network request failed"
- HUNDREDS of "[ethjs-rpc] rpc error with payload {\"id\":1512777775815,\"jsonrpc\":\"2.0\",\"params\":[\"OMITTED_FOR_USER_PRIVACY\"],\"method\":\"eth_getTransactionReceipt\"} [object Object]"

A few issues here:
- [ ] We should fail if the first submission returns an insufficient funds error like the above one did.
- [ ] The `rpc error with payload` warning message should record the returned error, not the params that got the error.
- [ ] When there are many `/warning/error` log entries in a row, we should concatenate this list, so it has a max size (this one grew to a tremendous size).
- [ ] When serializing tx controller state for the UI, we should withhold txMeta.history, to reduce serializing/processing effort.

This also resembles another user who recently reported a performance problem who also had a large tx history.

**Comment by Gudahtt** [comment]
Closing in favour of https://github.com/MetaMask/core/issues/4549

**Comment by Gudahtt** [comment]
Actually, I'll leave this open to represent the work of bringing the fix for https://github.com/MetaMask/core/issues/4549 into the extension

**Comment by gauthierpetetin** [comment]
Hi @Gudahtt , do you know if this issue can be closed now?

**Comment by bschorchit** [comment]
@Gudahtt do you know if this has worked on already?

**Comment by Gudahtt** [comment]
This was resolved by #26291
