### ISSUE TITLE
Blank screen on firefox

### ISSUE THREAD

**Issue by EricExtremeHash** [MetaMask/metamask-extension#9376]
Hello since today i got this blank screen also when i go to the page it's showing me

Error: NetworkError when attempting to fetch resource.
Bron-URL: moz-extension://38372c28-c87e-4aeb-b75d-a24b90409dd2/inpage.js
Brontoewijzings-URL: ../sourcemaps/inpage.js.map

**Comment by tmashuang** [comment]
Closing in favor of #9196, if you have any additional useful information and steps to reproduce, add your input there.
