### ISSUE TITLE
The MetaMask Firefox plugin pollutes the console for all pages

### ISSUE THREAD

**Issue by Gutza** [MetaMask/metamask-extension#9378]
Most times I open Firefox console I find two messages from the MetaMask plugin – one of them is a warning I do not care about (_MetaMask will soon stop reloading pages on network change_), and the other one is an actual error (_Source map error: Error: NetworkError when attempting to fetch resource_), which is also related to the MetaMask plugin.

**Comment by jacobcantele** [comment]
Hi Gutza, this is expected behavior. We're working to communicate critical information to dapp developers. In the future it will be removed.

**Comment by Gutza** [comment]
I see. In this case, my expected behavior is to uninstall the extension. Which I just did. Thank you for explaining your position!
