### ISSUE TITLE
"Insufficient funds" for gas shown when user has enough ether

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9402]
A user reports they got an an insufficient funds error erroneously:
https://www.reddit.com/r/Metamask/comments/imneyo/cannot_send_dai_out_of_metamask/

We should verify that this error state is being cleared & updated in the appropriate places.

**Comment by tmashuang** [comment]
Closing, this could have potentially been a gas api issue or a network issue. This requires additional information and debugging steps with the user to verify though state logs with support.
