### ISSUE TITLE
Unchecked runtime.lastError: Could not establish connection

### ISSUE THREAD

**Issue by birdca** [MetaMask/metamask-extension#9407]
**Describe the bug**
When running the [test-dapp](https://metamask.github.io/test-dapp/) that metamask doc provided, it'll show "Unchecked runtime.lastError: Could not establish connection", and keep displaying "Sending metamask: reload message". 

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to [chrome://extensions/](chrome://extensions/)
2. Disable MetaMask
3. Switch back to [test-dapp](https://metamask.github.io/test-dapp/)
4. Reload
5. Click on "INSTALL METAMASK" button, it'll redirect to [chrome://extensions/](chrome://extensions/) in a new tab
6. Click on "Enable" on [chrome://extensions/](chrome://extensions/)
7. After extensions reload complete, [test-dapp](https://metamask.github.io/test-dapp/) starts to reload, wait for 1-2 seconds when [test-dapp](https://metamask.github.io/test-dapp/) is still reloading, switch back to [test-dapp](https://metamask.github.io/test-dapp/)
8. the "CONNECT" button didn't work and see errors on console

**Expected behavior**
The "CONNECT" button suppose to work after enable MetaMask on chrome://extensions/

**Screenshots**
![Image of Issue](https://i.imgur.com/ORnPyCr.gif)
[NOTE]: The clear version of video is [here](https://drive.google.com/file/d/1LX6mSsJQj73UcNV31Npe_OC_zDzQJYZO/view?usp=sharing)

**Browser details (please complete the following information):**
 - OS: OS X
 - Browser Chrome Version 85.0.4183.102 (Official Build) (64-bit)
 - MetaMask Version 8.0.8

**Additional context (Error Messages, etc.)**

**Comment by gpersoon** [comment]
I've found another scenario to reproduce the error "Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist."
1) Make sure Chrome is closed (metamask is installed on chrome)
2) Double click on a link to a dapp (for example https://web3examples.com/ethereum/web3js_browser/version.html)
3) Now chrome starts and in the development console you see the error message:
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

It seems to be a timing issue, see also:
https://stackoverflow.com/questions/54181734/chrome-extension-message-passing-unchecked-runtime-lasterror-could-not-establi

OS: Windows 10
Browser: Version 87.0.4280.66 (Official Build) (64-bit)
Metamask: 8.1.3

**Comment by tmashuang** [comment]
As of MetaMask v9.0.2 and Chrome 88.0.4324.96, I was not able to reproduce this behavior. Reading the aforementioned Stackoverflow thread seems promising in suspecting a Chrome bug that may or may not have been fixed, I was not able to find a related Chrome bug on their issue tracker. On our end there definitely could be improvements on our message passing and is most likely the issue in the background/content scripts if this is a wide spread issue.

**Comment by VITRI0L** [comment]
I can confirm that the error happen on any chromium browser when the browser is closed and opened from a dapp url

**Comment by VITRI0L** [comment]
It now happens on Superrare too, I guess most of the dApp are actually pretty sensible to this issue.
Please can we swap the severity higher to get a quick fix?

**Comment by aksdevac** [comment]
Facing similar issue on current latest chrome & Metamask (10.7.0), because of this error onboarding flow is not working as expected, it keeps logging 'Sending metamask:reload message' with error.

<img width="739" alt="metamask-error" src="https://user-images.githubusercontent.com/2557058/144840531-f3efee75-2722-4bd6-abce-d8dece7c92d9.png">

**Comment by arcanisgk** [comment]
what is dapp url?

**Comment by aksdevac** [comment]
@jacobc-eth Hi, here is the minimal reproduction example based on this official guide: https://docs.metamask.io/guide/onboarding-library.html#using-react

**Codesandbox URL:**
https://codesandbox.io/s/connect-metamask-forked-lph1y?file=/src/App.js

**Direct app URL:**
https://lph1y.csb.app/

Also surprisingly it worked correctly one time (it closed the setup tab automatically & dapp received the event) while making this demo.
& but I tried again many times by removing extension & installing again using this demo dapp, & if failed with mentioned error. & if possible please make this issue High priority.

**Comment by ravisriv** [comment]
Excellent feedback by @aksdevac. Would appreciate prioritizing this issue. This issue is creating an inconsistent and confusing user experience.

**Comment by thisprojectworks** [comment]
I can confirm that this is a problem with metamask and occurs in google chrome both on windows and macOSx, we have tried to install a completely new application and it follows the error only when the browser is first opened. 
This should be a high priority.

**Comment by aksdevac** [comment]
@thisprojectworks is correct, it seems it is now not limited to onboarding flow, Connecting does not work if you quit chrome & open dapp url first time, it starts working after you refresh the dapp page. hope this get fixed soon.
also verified this on current dev chrome.

It only happens for 1st tab of new browser instance, if you open another tabs it works.

<img width="1575" alt="metamask-error-new-browser-instace" src="https://user-images.githubusercontent.com/2557058/146775121-173f71cf-2a63-462d-8c6a-02ad4987489a.png">

**Comment by arcanisgk** [comment]
Do you know if this already has a thread to follow in chrome ???

**Comment by passariello** [comment]
Yes, I can confirm same issue here. I receive this issue from all pages where extension run.

![Screenshot 2022-01-04 185331](https://user-images.githubusercontent.com/17809213/148153413-35193d2f-6265-4331-83bc-0cca53910004.png)

**Comment by h0tw4t3r** [comment]
> @thisprojectworks is correct, it seems it is now not limited to onboarding flow, Connecting does not work if you quit chrome & open dapp url first time, it starts working after you refresh the dapp page. hope this get fixed soon. also verified this on current dev chrome.
> 
> It only happens for 1st tab of new browser instance, if you open another tabs it works.
> 
> <img alt="metamask-error-new-browser-instace" width="1575" src="https://user-images.githubusercontent.com/2557058/146775121-173f71cf-2a63-462d-8c6a-02ad4987489a.png">

+1

**Comment by hamidmohammad1** [comment]
Does anybody a momentary fix for this issue?

**Comment by gVguy** [comment]
I'm having this issue too on macOs Chrome
Reproduction:
1. Quit Chrome
2. Open Chrome
3. Go to [metamask docs example](https://docs.metamask.io/guide/getting-started.html#basic-considerations)
4. Click the 'enable ethereum' button, it does nothing
5. Console shows the promise is forever pending, but the popup doesn't come up

![Screenshot 2022-02-10 at 14 11 23](https://user-images.githubusercontent.com/88876408/153395470-39d0eb52-a41e-44d2-9310-8106edff2ef2.png)

**Comment by RobertoDonPedro** [comment]
Same issue here. It appears that it just happens if you open Chrome for the first time and your app then runs `await window.ethereum.request({ method: 'eth_requestAccounts' });`
If you refresh the page manually and try it again it works.
This issue is open for a long time now, wondering if it this error comes with a new metamask/chrome version now again or if it is still the old error. It makes Metamask unusable... Anyone working on a fix??? Or workaround?

**Comment by RobertoDonPedro** [comment]
UPDATE: **It works if you change port from 3000 to 3001** !!
This is weird, but it appears that this error is related to the default port 3000 in your development environment, which is used eg. if you run `npm run dev`.
However, if you change the port to 3001 (eg. in Next.js by running npx `next dev -p 3001 `) everything works as expected!

**Comment by vphilot** [comment]
Same issue here, I'm trying to check for existing connected wallets when the app loads.

```js
    const isUnlocked = await window?.ethereum?._metamask.isUnlocked()
   if (isUnlocked) accounts = await window.ethereum.request({ method: 'eth_requestAccounts' })
```

error:
`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

It stops the execution of any other methods after it, resulting in an empty page.

**Comment by loredanacirstea** [comment]
I am getting the same error when trying to load the unpacked extension into Chrome after building from source. The Metamask popup either does not open or opens to a blank page and freezes.

Tried by building from source:
- https://github.com/MetaMask/metamask-extension/commit/c81912f6c5561f70ef37acde0af8e0d723e531ec
- Version 10.11.1

Chrome: Version 100.0.4896.30 (Official Build) beta (x86_64)
macOS: 11.6.5

<img width="686" alt="Screenshot 2022-03-14 at 20 39 14" src="https://user-images.githubusercontent.com/4785356/158244898-735d3c48-e1fd-4d16-9b98-b926cbb7d2e8.png">

**Comment by arcanisgk** [comment]
> I am getting the same error when trying to load the unpacked extension into Chrome after building from source. The Metamask popup either does not open or opens to a blank page and freezes.
> 
> Tried by building from source:
> 
> * [c81912f](https://github.com/MetaMask/metamask-extension/commit/c81912f6c5561f70ef37acde0af8e0d723e531ec)
> * Version 10.11.1
> 
> Chrome: Version 100.0.4896.30 (Official Build) beta (x86_64) macOS: 11.6.5
> 
> <img alt="Screenshot 2022-03-14 at 20 39 14" width="686" src="https://user-images.githubusercontent.com/4785356/158244898-735d3c48-e1fd-4d16-9b98-b926cbb7d2e8.png">

is it possible that the error is coming from another extension trying to do something to the popup.html window?

**Comment by loredanacirstea** [comment]
It took 1-2 minutes to show another error `Invalid Infura project ID` in `background.html` - I assume this is why Metamask does not fully load in my case (I only see a blank page).
I did add a working Infura project ID in a `. metamaskrc` file in the root directory, as instructed in https://github.com/MetaMask/metamask-extension#building-locally ...

**Comment by erik0612** [comment]
I am getting the same issue in my dapp. is there any updates? or is there any solution?
![Screen Shot 2022-03-18 at 1 25 59 AM](https://user-images.githubusercontent.com/97297907/158942808-3456cfa1-ebfa-4df1-a406-51a996ed1378.png)

**Comment by theawkwardchild** [comment]
I'm still also seeing this but I think maybe only on brave browser

**Comment by RobertoDonPedro** [comment]
I now have built a workaround function that fixes this issue (with the cost of an additional page load):
```
// Fixes Error: "unchecked runtime.lasterror: could not establish connection. receiving end does not exist."
// that occurs on the initial page load when Metamask is installed
const maybeFixMetamaskConnection = async () => {
  // Reloads the page after n seconds if Metamask is installed but not initialized
  const waitSeconds = 10;
  if (typeof window !== "undefined" && typeof window.ethereum !== 'undefined' &&  !window.ethereum._state.initialized) {
    while(!ethereum._state.initialized) {
      await new Promise(resolve => setTimeout(resolve, waitSeconds * 1000)); 
      window.location.reload();
    }
  }
}
```
Then in React for example you can call this function in your useEffect hook BEFORE you actually connect:
```
  useEffect( async () => {

    // Call this BEFORE trying to connect 
    await maybeFixMetamaskConnection();

    // Now connect to Metamask and do you stuff ...
    const accounts = await ethereum.request({ method: 'eth_requestAccounts' });
    const account = accounts[0];

  }, []);
```
However, it's a shame that the Metamask team is not capable to fix this issue...

**Comment by Anvarmirzo** [comment]
[RobertoDonPedro](https://github.com/RobertoDonPedro) the best

**Comment by seaona** [comment]
I could reproduce this error in the following way:
1. On the local codebase, delete the file `.metamaskrc`
2. Build the project `yarn setup yarn dist`
3. Load Metamask unpacked on Chrome
4. Try to Open MM
You'll see a blank screen, and on the errors you can see the exact same error:

![image](https://user-images.githubusercontent.com/54408225/168131421-f9b24495-0786-4eed-a1b1-b3f98540b51e.png)

For the person who fix this, seems related to a wrong build, where variables are not correctly set?

**Comment by taochen2001** [comment]
It is a shame that MetaMask has not fixed this after almost 2 years. I found a temporary fix to this. This one combines several suggestions from the internet and works for my case for now. 

Add the following to your componentDidMount():

window.addEventListener("focus", this.onFocus); 

// then use onFocus () to refresh window only when metamask is not yet initialized;

 onFocus () {
    if (typeof window !== "undefined" && typeof window.ethereum !== 'undefined' &&  !window.ethereum._state.initialized) {
      if(!window.ethereum._state.initialized) {
        window.location.reload();
      }
    }
  }

**Comment by shekhawat777** [comment]
I am using @3rdweb/hooks and  getting same error when the first time browser open and after refreshing the page was work  i found a one solution may be help anyone work for me >>>>>>>>>>
   window.ethereum
                      .request({ method: "eth_requestAccounts" })
                      .then(() => connectWallet("injected"))
                  }

**Comment by Martibis** [comment]
Running into this issue as well, also using a window.location.reload work around, but it's absolutely horrible that this is necessary.

**Comment by Dinuz** [comment]
This issue is still present and sucks!! When we do something?
The methodology that has less crappy impact on the user experience is the one suggested by @taochen2001 
The experience is not stellar yet (you get an unnecessary refresh) but it's bearable, setting up an exact timeout is just insane and 99% of the cases degrades the whole experience (you can risk to get multiple refresh).

@metamaskbot when the hell you fix this?

**Comment by shivjoshi1996** [comment]
I'm also hitting this issue. On our NextJS app we're also using the reload method and checking every 1 second  whether we need to refresh or not (I'm still testing to see if that is long enough,  but even 1 second feels too long). Like other people have mentioned, this is not a great user experience and may lead to multiple refreshes. 

This bug needs to be addressed as it potentially breaks apps completely, without the user knowing why.

**Comment by aksdevac** [comment]
It seems this error is now gone so reload workaround might not be needed, only confirmed on Chrome beta 108.0 & dev 109.0. but anyone can confirm on current stable chrome.  not sure if this was a browser issue or extension.

**Comment by arcanisgk** [comment]
pongo todo esto en una promesa... por cualquier motivo si se rompe es un problema de comunicación del navegador y la extensión...

**Comment by rho-cassiopeiae** [comment]
Still present on chrome 109 and mm 10.23.2
