### ISSUE TITLE
Metamask account not working

### ISSUE THREAD

**Issue by Cliffyz** [MetaMask/metamask-extension#9431]
My previous post was closed. i was on holiday so i could not reply in time...

Here is my issue:

Hi. I have an issue with a Metamask account and am hoping I can get some help here.

Metamask version: 8.0.8.
Chrome extension.

So I made 2 accounts within my wallet and I can easily switch between them.
Account 1: working fine
Account 2: doesn't transact.

I used to use account 2, nothing wrong and there is funds on it.
But since last week every transaction keeps pending.
I have tried to increase the gas fee, increase slippage and I have reset it 100 times.
All without result.

I have tried to send funds to account 1. Keeps pending.
I have tried to export it to mew so I would be able to transact through mew but there is no option to see the private key (I know where it should be found).
Also I tried to get account 2 on my phone through the QR code. It says that the QR code is expired.

All in all account 1 works fine, it has a own seed phase and private key.
Account 2 doesn't have both, doesn't transact with anything and it almost seems none existent...
Also the ledger wallet does not get any input to sign transactions.

I hope someone will offer help again. Thanks in advance.

**Comment by danfinlay** [comment]
Please try:
- quitting & reopening the browser
- Switching to another network and back again

If neither of these work, to help us diagnose your issue, you can download your "state logs" by [following this guide](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue), and then submit them to support.metamask.io

**Comment by danfinlay** [comment]
Since this is not a support forum, I am closing this for now, but please do check out support.metamask.io. There is a forum there and a form for requesting individual support.
