### ISSUE TITLE
Underpriced speed-up can cause confusing error state

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9435]
Steps to reproduce:
1. Submit a tx at a low gas price
2. Click "speed up" on the tx
3. Select the "slow" gas price of the available options.

Result:
- The RPC returned an error with the message `"replacement transaction underpriced"`
- This transitions the replacement tx to a "failed" state.
- The transaction history now shows "failed", implying to the user this tx has failed (this failure is indistinguishable from an on-chain failure), even though there is still a valid "submitted" transaction before that failed one.
- Upon retrying, the new transaction has the NEXT nonce (probably because of the valid "submitted" one with the lower nonce).

Expected result:
- Ideally, the user is not shown gas options that will result in "tx underpriced" errors.
- If a speed up attempt does fail with an RPC error, the user should stay on the confirmation screen, be shown this as an error, and have a chance to select a new gas price.

**Comment by tmashuang** [comment]
Related to https://github.com/MetaMask/metamask-extension/issues/9053

**Comment by tmashuang** [comment]
For testing purposes, on a Test Network we can take advantage of the `exceeds block gas limit` error from the RPC to simulate the tx failure. 
1. Submit a tx on a testnet (Rinkeby) with a gas price < 1
2. Click Speed Up
3. Under Advanced Tab for gas limit set to `10000000000` . Gas price to 1 , this shouldn't matter though.
4. Click the Save button

This will/should update the tx list item to a failed state. Thus not showing any visible indication of the tx with gas price < 1 that has been submitted, but just pending on the network. I think this is fundamental issue on how we present transaction in the transaction list which #9041 is suppose to patch, not entirely fix.
