### ISSUE TITLE
Warn when sending a token to its own address

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9437]
[For example](https://github.com/MetaMask/metamask-extension/issues/8174)

This is a common way to lose funds. I honestly thought we already prevented this, but it seems not.

Acceptance criteria:
- [ ] When sending a token to its own address, warn the user "The recipient of this transaction is the token address, this is probably not who you mean to send to." (other copy nominees accepted)

Maybe even:
- [ ] Require a user check an extra box that is labeled `I am sure I want to probably lose these tokens` before the `Confirm` button is enabled.

**Comment by jacobcantele** [comment]
@cjeria I heard you may already have some designs on this?

**Comment by cjeria** [comment]
I didn't find this specific warning message but I did mock up an additional error message for this use case. Here's the [Figma file](https://www.figma.com/file/giaffk6qfl9eMMjoPFjJkGnt/Address-book?node-id=474%3A31) where these can be found. cc @rachelcope 
![image](https://user-images.githubusercontent.com/597770/96800559-7902bf00-13ba-11eb-8374-1b76e1b74054.png)

**Comment by jacobcantele** [comment]
Christian's update designs are here: https://www.figma.com/file/KNLr0RnAk5p4duCywOqIhR/Send-Flow-QR-Compatibility?node-id=0%3A1

**Comment by jacobcantele** [comment]
Related: #9673

**Comment by epheph** [comment]
Is there any way to bump the priority of this issue? I don't have definitive proof, but I believe that metamask is the wallet used in many of the losses found on the TokenOops twitter bot, and those losses are commonly over $10,000/day

**Comment by rachelcope** [comment]
Designs ready. View designs i[n Figma](https://www.figma.com/file/SwzcT8L3XSoMGAwCW9W2lk/Error-Messaging?node-id=1554%3A3)

![image](https://user-images.githubusercontent.com/7483074/109074807-74764c00-76b5-11eb-9acf-f1d5b90ca6c1.png)

**Comment by rachelcope** [comment]
If this is error is implemented before the new transaction confirmation, then the banner should be shown at the top of the current transaction confirmation design

**Comment by BILLIONAIRE9** [comment]
Even i lost fund with same issue.

https://twitter.com/BILLI0NAIRE9/status/1353240446999220224?s=19


Please help me To get out of this situation...🙏🙏🙏🙏🙏🙏🙏

**Comment by epheph** [comment]
Amazing, awesome!
