### ISSUE TITLE
Firefox Vault 

### ISSUE THREAD

**Issue by DarkSerum** [MetaMask/metamask-extension#9440]
Hello,

I am trying to find where the vault is located in a Firefox extension. The goal is the use the vault-decryptor to recover a wallet.

I found lots of information regarding Chrome, but not on Firefox. 

In my firefox folder, I see two directories related to the extension, but no file that could lead to a vault exctraction. Anyone can assist as I see SQLite file and other files but no vault inside.

C:\Users\W\AppData\Roaming\Mozilla\Firefox\Profiles\5izo2sf7.default-release\storage\default

![image](https://user-images.githubusercontent.com/71547482/93663518-e85a5b80-fa68-11ea-8499-be2379272523.png)

Thanks

**Comment by nesu** [comment]
Anyone?

**Comment by tmashuang** [comment]
You can grab the vault data similarly as Chrome from the addon's background developer console. From the addon's background developer console type `chrome.storage.local.get(console.log)` will print the entire state along with the vault data.

**Comment by hammypants** [comment]
@tmashuang this doesn't answer the question, though

**Comment by bodrych** [comment]
@DarkSerum is it relevant?

**Comment by blakelapierre** [comment]
what if we already removed the extension and are recovering deleted files??

**Comment by bodrych** [comment]
@blakelapierre did you recover these files https://user-images.githubusercontent.com/71547482/93663518-e85a5b80-fa68-11ea-8499-be2379272523.png ?

**Comment by blakelapierre** [comment]
I believe so

**Comment by blakelapierre** [comment]
no, they are .sqlite files
