### ISSUE TITLE
Cant export and then import account

### ISSUE THREAD

**Issue by Cliffyz** [MetaMask/metamask-extension#9441]
Hi,

I have a metamask account which isnt sending any funds out. It can recieve though.
I have tried speeding up, cancelling en resetting the account.
I also have tried to export the account but since the account itself is apperantly imported, it has no private key of its own.
When i create a JSON file on MEW and use this to import it on a metamask extention on another browser it says "this is not a V3 wallet".
Also I have tried to scan the QR code to sync it with my mobile wallet. This is not working because it says that i have not typed the private key correctly or something...

Support just send the first basic steps while i have explained this issue and included the log files... so i am really hoping that someone here is able to help me...

Thanks in advance.

**Comment by tmashuang** [comment]
Can you please clarify on what the issue is here? You provided a lot of information that doesn't seem to be related to 
> Cant export and then import account

Is the address in question a MetaMask address created from the seed phrase or an address from a JSON file and/or private key?
If you submitted a support ticket with state logs please reference the ticket number here.

**Comment by Cliffyz** [comment]
Hi, its a long story so i will keep it as short as possible.
Main issue is: every transaction keeps pending.
There is no tx pending (not shown on etherscan) so i don't know why this is.
Also i have tried every basic step (speeding up, resetting account etc.) but without success.
 
So i tried to export the account to my mobile wallet and through mew so i could try to make transactions from there. But the account has no private key of its own and the QR code doesn't work when i try to sync it with my mobile wallet.
Also i have made a json file through mew so i would be able to export it on another meta wallet in another browser (worth a try yes?) but is says "no v3 wallet".

I have tried everything i have found on the internet now... i really need help.

**Comment by tmashuang** [comment]
> Hi, its a long story so i will keep it as short as possible.

If it is an issue, as much information as possible that happened before the issue occurred can help determine the cause, debug, and solve the issue. So keeping it short is not necessarily better.

>  Also i have tried every basic step (speeding up, resetting account a lot of times etc.) but without success.

These features were not suppose to be used lightly, and should be used in the correct manner and consideration on the state of your transactions. Speeding up a transaction is meant to send a transaction of the same nonce with a higher gas price. Resetting an account in MetaMask will clear the transaction history and determine the next appropriate nonce.

Speeding up a lot of times without consideration, can potentially lead into a bad transaction list state. Resetting an account is meant to fix this after all transactions have been successfully mined confirmed by a block explorer and when MetaMask thinks a transaction is still pending.

> The one that does not work does not have these.
 So i tried to export and then import the account but the account has no private key of its own and the QR code doesn't work when i try to sync it with my mobile wallet.

All address have an associated private key with them. Which QR code are you referring to, the QR code in the Account Details or under the Sync with Mobile feature?

Is the address in question a MetaMask address created from the seed phrase, an address from a JSON file and/or private key, or a hardware wallet?
