### ISSUE TITLE
Can't add $UNI token to metamask

### ISSUE THREAD

**Issue by avalyn2** [MetaMask/metamask-extension#9444]
**Describe the bug**
Can't add $UNI token to metamask

**To Reproduce (REQUIRED)**
Don't find $UNI when trying to add it

**Expected behavior**
$UNI can be added

**Screenshots**
![image](https://user-images.githubusercontent.com/32930476/93691301-90146f80-fae3-11ea-95f1-ae9b497f7ff2.png)

**Browser details (please complete the following information):**
 - Browser Chrome Version 85.0.4183.102 (Official Build) (64-bit)
 - MetaMask Version 8.0.8

**Comment by shhac** [comment]
Before it is a searchable result, you can still add it via "Custom Token" and using the contract hash for it `0x1f9840a85d5af5bf1d1762f925bdaddc4201f984`
https://www.coingecko.com/en/coins/uniswap

**Comment by tmashuang** [comment]
The token list that is populated is no longer maintained. We have opted for dapp devs and token creators to registering their own tokens and use the 'wallet_watchAsset' method to request adding a token to the list.
