### ISSUE TITLE
UNI transaction stuck

### ISSUE THREAD

**Issue by RikaSukenik** [MetaMask/metamask-extension#9447]
**Describe the bug**
UNI transaction is stuck & the transaction hash is undefined on etherscan. I can't cancel or speed up the transaction. Also, I don't see any pending ERC20 txs on my etherscan account.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to send UNI tokens
2. Transaction pending
3. Click on arrow to see transaction on etherscan
4. Etherscan tx hash is undefined

**Expected behavior**
UNI should have left my wallet and been deposited in another wallet

**Screenshots**

**Browser details (please complete the following information):**
- Mac, Chrome

**Additional context (Error Messages, etc.)**
![image](https://user-images.githubusercontent.com/29102861/93948929-8877e500-fcf4-11ea-8f9e-e95e6c70d4ea.png)

**Comment by tmashuang** [comment]
It does seem that the transaction was created without a tx hash. If you are willing to send your state logs to [MetaMask support](https://metamask.zendesk.com/hc/en-us/requests/new) and reference the ticket number here, to help further debug. 

To resolve the issue, Resetting your account transaction list will clear your transaction list and determine the next nonce by the network in the Settings > Advanced tab.

**Comment by RikaSukenik** [comment]
Sounds good, thanks. Support ticket number is #55759
Looking forward to hearing back soon.
