### ISSUE TITLE
Metamask Web3Receipt no longer returns events just logs, hard to extract data

### ISSUE THREAD

**Issue by FahdW** [MetaMask/metamask-extension#9456]
Web3Receipt no longer returns events? The entire structure has changed for it

**Comment by tmashuang** [comment]
Please follow the issue temple with clear and concise information/code examples to reproduce the issue as well as actual and expected results.

**Comment by tmashuang** [comment]
Closing due to not following the issue template and no follow up to request to provide one. If this is still an issue, please open a new issue with the appropriate information to reproduce the issue.
