### ISSUE TITLE
ledger wallet integration failing on macos

### ISSUE THREAD

**Issue by thegostep** [MetaMask/metamask-extension#9466]
**Describe the bug**
ledger wallet integration failing on macos

![image](https://user-images.githubusercontent.com/15959632/94332379-0712a200-ffd5-11ea-9529-0f6fa5014e72.png)

**To Reproduce (REQUIRED)**
Connect metamask to ledger nano s on macos

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: Ledger Nano S Firmware version 1.6.0
 - Browser: Chrome, Brave
 - MetaMask Version: 8.0.10

**Comment by jacobcantele** [comment]
Related to #8120

**Comment by jacobcantele** [comment]
This issue will be resolved by #9826

**Comment by dpazdan** [comment]
Confirmed this works with Ledger Live.
