### ISSUE TITLE
getTransactionReceipt no longer returns value

### ISSUE THREAD

**Issue by FahdW** [MetaMask/metamask-extension#9475]
`result = await web3.eth.getTransactionReceipt(this.txHash);`

When running this the values returned differ from MM 7.x to 8.x
for eg. in MM 7.x you could look into the event and get the return values. However in MM 8.x you cannot do this at all. All it has is the `logs` property on the receipt, with no way to identify what event you just called. How do you get the `event.returnValues` in 8.x? Is this no longer an option

**Comment by danfinlay** [comment]
The underlying RPC transport has not changed at all between v7 and v8, so you may just need to use the provider directly, it's possible this is a web3-related issue. 
https://docs.metamask.io/guide/ethereum-provider.html

So, for example:
```javascript
result = await provider.send({ method: 'eth_getTransactionReceipt', params: [ this.txHash ] });
```

**Comment by FahdW** [comment]
> The underlying RPC transport has not changed at all between v7 and v8, so you may just need to use the provider directly, it's possible this is a web3-related issue.
> https://docs.metamask.io/guide/ethereum-provider.html
> 
> So, for example:
> 
> ```js
> result = await provider.send({ method: 'eth_getTransactionReceipt', params: [ this.txHash ] });
> ```

Thanks, it's odd when I'm running a v7 MM on my app it's fine, but v8 MM the return value structure is entirely different. I'll have to do more digging in regards to this

**Comment by FahdW** [comment]
> The underlying RPC transport has not changed at all between v7 and v8, so you may just need to use the provider directly, it's possible this is a web3-related issue.
> https://docs.metamask.io/guide/ethereum-provider.html
> 
> So, for example:
> 
> ```js
> result = await provider.send({ method: 'eth_getTransactionReceipt', params: [ this.txHash ] });
> ```

How is it possible for two different results to occur if the underlying code is running the same version of web3?

**Comment by FahdW** [comment]
> The underlying RPC transport has not changed at all between v7 and v8, so you may just need to use the provider directly, it's possible this is a web3-related issue.
> https://docs.metamask.io/guide/ethereum-provider.html
> 
> So, for example:
> 
> ```js
> result = await provider.send({ method: 'eth_getTransactionReceipt', params: [ this.txHash ] });
> ```

Ok after checking send seems to be unreliable and is inconsistent. `request` is the issue it changed the underlying data return.

**Comment by danfinlay** [comment]
We really aren’t mutating this, we pass this request to geth or whatever node you’re manually connected to. This may be a change in geth behavior.

**Comment by FahdW** [comment]
> We really aren’t mutating this, we pass this request to geth or whatever node you’re manually connected to. This may be a change in geth behavior.

I've tried the `provider.send` it worked and returned the correct data, however it was unreliable and suddenly would stop sending data back. I've used an older MM and the current version and when you execute `getTransactionReceipt` the data being returned structure is entirely different. The previous versions had `returnValues` as part of the `getTransactionReceipt`. Using the exact same app and code yield two very different results depending on MM version. 

So I don't believe the issue lies on the node here. I'm unsure what else has changed on MM.

**Comment by tmashuang** [comment]
As of v8.1.3, you can get the transaction receipt of a tx with the current 
```
const await ethereum.request({
    method: 'eth_getTransactionReceipt',
    params: [this.txHash]
}
```
I don't see any docs on the `returnValues` mentioned for `getTransactionReceipt` [web3.js#getTransactionReceipt](https://github.com/ethereum/web3.js/blob/0.20.7/DOCUMENTATION.md#web3ethgettransactionreceipt) and [infura#getTransactionReceipt](https://infura.io/docs/ethereum/json-rpc/eth-getTransactionReceipt). So if it was something that was changed, it most likely was fixed to be correct.
