### ISSUE TITLE
Add target object word to "View on Etherscan" links.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9476]
We have "View on Etherscan" in a few places, and it means different things (accounts or tokens). We know this can be confusing to users. One simple way to mitigate this confusion is to update the wording in each case to clarify _what_ is being viewed.
- View Account on Etherscan
- View Token Contract on Etherscan

Bonus: We could use the term "Block explorer" instead of etherscan, to pave the way for user-configured block explorers.

**Comment by rekmarks** [comment]
@brad-decker possibly something low-hanging to look into for custom networks.

**Comment by kevinghim** [comment]
@danfinlay did you mean to label as Sev1? Seems more like a UX papercuts. Can you provide details?
