### ISSUE TITLE
my meta mask is frozen in transactions for days now cant do anything about it ive tried upping the gas price and many times and still no luck whjat do i do

### ISSUE THREAD

**Issue by ApexHowe** [MetaMask/metamask-extension#9478]
**Describe the bug**

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by jacobcantele** [comment]
Hi @ApexHowe , can you reach out to our support team at support.metamask.io? This isn't the place to get user support. They should be able to help you with troubleshooting this and will also identify if there is a bug we need to document here.
