### ISSUE TITLE
Custom network incorrect account balance when symbol is left blank.

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#9492]
**Describe the bug**
When a custom network symbol that we optionally take is left blank we assume it is an ETH network. So then we apply the ETH conversion rate to getBalance. This is easily result in users thinking they have more funds they they actually do when viewing their balance. The max amount in the send field will show the correct amount. 

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Add the xDai network, steps are [xDai MetaMask setup](https://www.xdaichain.com/for-users/wallets/metamask/metamask-setup)
2. Omit the asset symbol which we say is optional
3. The current conversion rate of ETH should times the balance we get from the network and apply the ETH suffix to the value.

**Expected behavior**
Either require the network symbol field to prevent this behavior, or when on a network other than the defaults do not apply the conversionRate to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/13376180/95265273-b9bcde80-07e5-11eb-96df-2021bf0cac33.png)

**Comment by rekmarks** [comment]
@brad-decker worth looking into. We may want to add defaults.

**Comment by danjm** [comment]
Another way to reproduce:

- add the metaswap testnet to metamask
- import one of the default seed phrases for the testnet
- you'll see an eth balance of "314508 ETH", but the actual balance on the test chain is 100 ETH

![Screenshot from 2021-05-03 11-56-23](https://user-images.githubusercontent.com/7499938/116888952-9c7ab200-ac06-11eb-9d1a-7c295a351d35.png)

**Comment by brad-decker** [comment]
@danjm is this because the testnet uses a non ETH currency? Don't we only support 18 decimal length tokens?

**Comment by danjm** [comment]
@brad-decker Good question, and it leaves me uncertain. I'm actually not sure why this is happening. The testnet does use ETH... :thinking:

**Comment by adonesky1** [comment]
Hey @Gudahtt and @danjm , so it looks to me like if a user doesn’t provide a symbol ticker for us to try and compare for a conversion rate with custom RPC networks [we throw an error](https://github.com/MetaMask/controllers/blob/f8970bddfe8e58f64e7e36e65f3b136e8541f168/src/apis/crypto-compare.ts#L39) and the previously valid conversionRate persists for the new network the user has selected (resulting in this issue). Wondering if the solution is to refactor this to return a conversion rate of 1 where this error is usually thrown which would result in the correct token values being displayed on the UI. Or perhaps to try and infer the ticker symbol based on the rpc URL. Honestly I’ve been trying to wrap my head around the various ways that this conversionRate is used and might need to take a look together if you have the time?

**Comment by adonesky1** [comment]
Alternatively we could just override conversionRate in the UI right [here](https://github.com/MetaMask/metamask-extension/blob/36869a435055f1c0120cd63bff694f896d11cfad/ui/hooks/useCurrencyDisplay.js#L49) adding something like this: `  if(!nativeCurrency) {
    conversionRate = 1;
  } `
  
  but that doesn't seem right.

**Comment by Gudahtt** [comment]
This appears to have been accidentally closed

**Comment by zivkovicmilos** [comment]
Hey,

Just to note this issue is still present, and we're experiencing it with our custom network, as well as with Ganache. What's interesting is - if you put an empty space symbol (` `) as the symbol when adding a custom network, the balance displays fine.

It might be worth taking a look at [how this is handled](https://github.com/MetaMask/controllers/blob/82386c490d6eb4c15c449d7c5ed3c53f94060497/src/assets/CurrencyRateController.ts#L222), since it returns a different API error for an empty space symbol ("currency pair not found", something along those lines), and a different one for a null value.
