### ISSUE TITLE
Used my Seed phrase on my android app and the ETH adress changed on my chrome extention

### ISSUE THREAD

**Issue by urkann** [MetaMask/metamask-extension#9504]
**Describe the bug**
i first installed metamask on my desktop, everything was ok.
A few weeks later i installed it on my android phone and used the seed phrase as i forgot my password.
Then the ETH adress changed on my chrome extension, and my balance changed to 0 and i have a new ETH adress, the other one is totally gone. (the balance of the previous adress is still with the same amount of ETH i had)
Im a hundred percent sure the seed phrase is correct as i have a photo of my screen when i first saw it on my computer ( i know its not safe but the image is locked in a secure place)
I have the previous adress just in case metamask can do something.
Any assistance would be much appreciated

**Browser details (please complete the following information):**
 - OS:  MAC OS Catalina 10.15.6
 - Browser chrome 
 - MetaMask Version 8.0.10

**Comment by jacobcantele** [comment]
Hi urkann, this does sound like you entered the seed phrase incorrectly. Either way, the best place to get support is support.metamask.io where they should be able to help you resolve this issue.
