### ISSUE TITLE
Figure out architecture for complex multi-vault use cases

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#952]
Some multi-vault use cases are even more complicated than what we're currently ready for.  Consider:

A user who wants to manage an Ethereum wallet contract with their Ledger Nano S hardware wallet.

In this case, we have two layers of tx signing responsibility.

This helps distinguish "identity" from "key signing strategy", and is worth a serious consideration.

**Comment by lazaridiscom** [comment]
@danfinlay 

(may I simply ping in such outdated issues? )

**Comment by lazaridiscom** [comment]
@Zanibas , this issue could be close, as its superseded by #3249

**Comment by danfinlay** [comment]
Closing as duplicate of #3249.
