### ISSUE TITLE
Choosing "MetaMask Notification" Item in History Menu Kills Window

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#9544]
**Describe the bug**
While developing a paywall demo and triggering several transactions which resulted in browser notifications, I was surprised to see several items in my recent history named "MetaMask Notification".  Wanting to know what exactly those represented, I clicked a one of those items; a chrome-extension URL briefly loaded and then my browser window crashed.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Trigger several transactions on the Ropsten network; wait for browser notifications to complete
2. Open the History menu, click one of those items
3. (Tab opens briefly)
4. (Browser window crashes)

**Expected behavior**
Mark mentioned that an Etherscan link should open when clicking on those items.

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: None
 - Browser: Brave 1.15.72
 - MetaMask Version: 8.0.10

**Additional context (Error Messages, etc.)**
Could it be that it's bricking because I'm using Ropsten network?

**Comment by Gudahtt** [comment]
I tried to reproduce this when this was first reported, but wasn't able to. I only tested on Linux though. We should try to reproduce this on macOS

**Comment by darkwing** [comment]
I can no longer reproduce this issue.  Closing.

**Comment by deeubnub** [comment]
I too am having this issue, exact same steps to reproduce as stated originally, however in my case clicking the MetaMask notification in my browsing history crashes all of Chrome. 

Windows 10
Chrome Version 89.0.4389.114
MetaMask 9.3.0
