### ISSUE TITLE
Incident transaction for my cryptocurrency ROTTEN & Xeth 

### ISSUE THREAD

**Issue by alexi122** [MetaMask/metamask-extension#9554]
[11.txt](https://github.com/MetaMask/metamask-extension/files/5365225/11.txt)
sir, i have twice lost my transactions in a ghost account! I have tried evrything to recover this but it is imposible please resove this incident for me please. Thank you

**Comment by jacobcantele** [comment]
Hi alexi, please reach out to our support team at support.metamask.io.
