### ISSUE TITLE
Long Decimals Push Send Amount Width

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#9572]
When I'm choosing an amount of tokens to send, and the decimal value is very long, the entire send block stretches off the screen.

**Steps to reproduce (REQUIRED)**

0. Click "Send"
1. Choose any crypto for which you have a value with many decimal places
2. Click "Max"
3. See the Amount block stretch off screen

**Screenshots**
<img width="360" alt="LongNumberLabel" src="https://user-images.githubusercontent.com/46655/95875836-12d1c880-0d38-11eb-923c-ac1a89cb1699.png">

**Browser details (please complete the following information):**
 - OS: Mac OS 
 - Hardware Wallet: None
 - Browser: Chrome
 - MetaMask Version: 8.0.10

**Comment by ProkhorZ** [comment]
For me, this happens in the normal assets display, not only when sending. I use the Chrome extension on Windows.

![metamask assets display](https://user-images.githubusercontent.com/22837744/97778934-fd9fcb00-1b7a-11eb-8027-6703d1b3be77.png)

Truncating is a thorny issue for a basic infrastructure app, so I recommend putting the currency code before the number.
