### ISSUE TITLE
Incident de transaction 

### ISSUE THREAD

**Issue by alexi122** [MetaMask/metamask-extension#9606]

**Comment by alexi122** [comment]
Thanks and sorry to bother you again, my problem is not adding the crypto, this is a transaction I made in the wrong place!  Instead of swapping the crypto with ether (to send them to my account), I did send, the transaction was confirmed but I don't have them.  Thank you.  C
![Screenshot_20201013_184812_io metamask](https://user-images.githubusercontent.com/72744916/96031624-8289a580-0e55-11eb-87a5-bcd8ba1aa777.jpg)
![Screenshot_20201013_184720_io metamask](https://user-images.githubusercontent.com/72744916/96031631-84536900-0e55-11eb-9623-dcbf59dab06f.jpg)

ordialy

**Comment by tmashuang** [comment]
Please describe what you think these two screenshots mean.

**Comment by alexi122** [comment]
My problem is, when I wanted to sell my cryptos (ROTTEN) against ethereum I
proceeded like this in picture ... (I admit that it was a mistake on my
part).  Despite everything my transaction has been validated but I do not
see them in my wallet.  I did the same with the other crypto (XETH)!
Confirmed result but nowhere in my wallet

Le mer. 14 oct. 2020 à 19:50, Thomas Huang <notifications@github.com> a
écrit :

**Comment by tmashuang** [comment]
What service were you using?

**Comment by alexi122** [comment]
Metamask obviously

Le jeu. 15 oct. 2020 à 00:07, Thomas Huang <notifications@github.com> a
écrit :

**Comment by tmashuang** [comment]
Ok, so you sent your tokens to the token address?

**Comment by alexi122** [comment]
Yes exactly that

Le jeu. 15 oct. 2020 à 00:21, Thomas Huang <notifications@github.com> a
écrit :

**Comment by tmashuang** [comment]
You should contact the ROT team to see if they can deposit back to your address as they are the owners of the token.

**Comment by RLlane2126** [comment]
Lost token

**Comment by alexi122** [comment]
My transactions (Rot) and (Xeth) have been validated on etherscan!  I will
do as you told me.  thank you very much

Le jeu. 15 oct. 2020 à 01:14, Thomas Huang <notifications@github.com> a
écrit :
