### ISSUE TITLE
After disconnect an account getAccounts returns next account despite it was not selected

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-extension#9620]
**Describe the bug**
After disconnect an account `getAccounts` returns next account despite it was not selected.
Almost the same bug as #9619, but for `web3.eth.getAccounts` method

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Connect 2 MetaMask accounts to some website
2. Disconnect the first account
3. getAccounts returns the next account, despite it is still not selected

**Expected behavior**
getAccounts should return `undefined`

**Browser details (please complete the following information):**
- OS: OS X
- Browser: Version 86.0.4240.80 (Official Build) (x86_64)
- MetaMask Version: 8.0.10

**Comment by jacobcantele** [comment]
Hi @mqklin, this behavior is intentional since both accounts were connected by the user.
