### ISSUE TITLE
"MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug."

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-extension#9627]
**Describe the bug**
Got "MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug." message in my console.
It logged after I switched an account in MetaMask.

**Browser details (please complete the following information):**
- OS: OS X
- Browser: Version 86.0.4240.80 (Official Build) (x86_64)
- MetaMask Version: 8.0.10

**Comment by mqklin** [comment]
Now i got this error:
```
MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug. Array(0)
```

**Comment by jacobcantele** [comment]
Can you please provide the exact site and circumstances where you experienced this error?

**Comment by mqklin** [comment]
I was testing on `localhost:3000`. I changed account in MetaMask, so it wasn't "unexpected" update. I can't expose the code, because repo is private.

**Comment by jacobcantele** [comment]
I see... I'm not sure how we can help without a way to reproduce this.

**Comment by mqklin** [comment]
This doesn't cause any errors, so free to close the issue. I reported because of "Please report this bug" message :)
