### ISSUE TITLE
Cancel in flight async swaps fetch quote calls when resetting swaps background state

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9632]
We currently have this code containing TODO items in comments:
```
export const navigateBackToBuildQuote = (history) => {
  return async (dispatch) => {
    // TODO: Ensure any fetch in progress is cancelled
    await dispatch(resetSwapsPostFetchState())
    dispatch(navigatedBackToBuildQuote())

    history.push(BUILD_QUOTE_ROUTE)
  }
}

export const prepareForRetryGetQuotes = () => {
  return async (dispatch) => {
    // TODO: Ensure any fetch in progress is cancelled
    await dispatch(resetSwapsPostFetchState())
    dispatch(retriedGetQuotes())
  }
}
```
In any case where `resetSwapsPostFetchState` or `resetBackgroundSwapsState` is called, we should cancel `fetchAndSetQuotes` calls, and the fetch request it creates.

**Comment by danjm** [comment]
A bit more explanation on this:

- on click on the 'Get Quotes' button on the build-quote screen, `fetchQuotesAndSetQuoteState(history, inputValue, maxSlippage, metaMetricsEvent)` is dispatched
- that function is defined here: https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/ducks/swaps/swaps.js#L254
- that function ends up dispatching `fetchAndSetQuotes` which ultimately calls the method of the same name in the swaps controller https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/swaps.js#L111
- `swapscontroller.fetchAndSetQuotes` calls `fetchTradesInfo`: https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/pages/swaps/swaps.util.js#L155
- which makes a request to the metaswap api via https://github.com/MetaMask/metamask-extension/blob/develop/ui/app/helpers/utils/fetch-with-cache.js and then https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/fetch-with-timeout.js

It is the whole of the `swapscontroller.fetchAndSetQuotes` that needs to be aborted/cancelled/stopped

**Comment by jacobcantele** [comment]
@danjm can you confirm this is good to close?

**Comment by Gudahtt** [comment]
This was fixed by https://github.com/MetaMask/metamask-extension/pull/9671
