### ISSUE TITLE
Warning: Failed prop type: Invalid prop `minimumGasLimit` of type `string` supplied to `AdvancedGasInputs`, expected `number`.

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#9634]
When clicking from the home screen to the send screen, I'm seeing the following props warning:

Warning: Failed prop type: Invalid prop `minimumGasLimit` of type `string` supplied to `AdvancedGasInputs`, expected `number`.
    in AdvancedGasInputs (created by ConnectFunction)
    in ConnectFunction (created by SendGasRow)
    in div (created by SendGasRow)
    in div (created by SendRowWrapper)
    in div (created by SendRowWrapper)
    in SendRowWrapper (created by SendGasRow)
    in SendGasRow (created by ConnectFunction)
    in ConnectFunction (created by SendContent)
    in div (created by SendContent)
    in div (created by PageContainerContent)
    in PageContainerContent (created by SendContent)
    in SendContent (created by ConnectFunction)
    in ConnectFunction (created by SendTransactionScreen)
    in div (created by SendTransactionScreen)
    in SendTransactionScreen (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(SendTransactionScreen)) (created by Context.Consumer)
    in Route (created by Authenticated)
    in Authenticated (created by ConnectFunction)
    in ConnectFunction (created by Routes)
    in Switch (created by Routes)
    in div (created by Routes)
    in div (created by Routes)
    in Routes (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(Routes)) (created by Index)
    in LegacyI18nProvider (created by Index)
    in I18nProvider (created by Index)
    in LegacyMetaMetricsProvider (created by Index)
    in MetaMetricsProvider (created by Index)
    in LegacyMetaMetricsProvider (created by Index)
    in MetaMetricsProvider (created by Index)
    in Router (created by HashRouter)
    in HashRouter (created by Index)
    in Provider (created by Index)
    in Index backend.js:32
    n backend.js:32
    printWarning checkPropTypes.js:20
    checkPropTypes checkPropTypes.js:82
    React 2
    renderedWrappedComponent Redux
    React 3
    ConnectFunction Redux
    React 10
    unstable_runWithPriority scheduler.development.js:697
    React 26
    startApp index.js:136
    launchMetamaskUi index.js:34
    apply index.js:123
    handle index.js:99
    handle dnode.js:140
    write dnode.js:128
    ondata _stream_readable.js:612
    emitOne events.js:106
    emit events.js:184
    addChunk _stream_readable.js:284
    readableAddChunk _stream_readable.js:271
    push _stream_readable.js:238
    _write index.js:68
    doWrite _stream_writable.js:406
    writeOrBuffer _stream_writable.js:395
    write _stream_writable.js:322
    ondata _stream_readable.js:619
    emitOne events.js:106
    emit events.js:184
    addChunk _stream_readable.js:291
    readableAddChunk _stream_readable.js:278
    push _stream_readable.js:245
    _onMessage index.js:38

​

**Comment by jacobcantele** [comment]
@danjm @darkwing I believe this was resolved, is it okay to close this issue?
