### ISSUE TITLE
Fetch gas prices at an interval when in swaps, to keep them up to date

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9637]
Offering more accurate gas estimates will allow us to cultivate trust with our end users

**Comment by Gudahtt** [comment]
This was brought up in this discussion: https://consensys.slack.com/archives/C018CNHEUP9/p1602795557439900?thread_ts=1602790819.434000&cid=C018CNHEUP9

**Comment by Gudahtt** [comment]
The gas prices should be updated each time the quotes are; we've decided this is an adequate solution, as the quotes update fairly often.
