### ISSUE TITLE
Swaps Token Ticker Overflow Issue

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9638]
![EkP1nIAUwAEawmv](https://user-images.githubusercontent.com/7499938/96478581-68afe000-1212-11eb-88ee-4d292d50728f.jpeg)

**Comment by darkwing** [comment]
Oddly enough, I'm seeing it can get a bit wilder:

<img width="381" alt="Overflow" src="https://user-images.githubusercontent.com/46655/96503697-49688100-1219-11eb-945a-4cf520a2a66c.png">
