### ISSUE TITLE
Metamask desktop notifications still link to etherscan when using a custom rpc with a custom block explorer

### ISSUE THREAD

**Issue by dmidnight** [MetaMask/metamask-extension#9641]
**Describe the bug**
Using 8.1.1, when I create a custom RPC with it's own block explorer configured, and I get a desktop notification (ubuntu 20/firefox) the link is still to etherscan

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Create custom RPC with custom block explorer
2. Send and receive transactions
3. View desktop notifications
4. See incorrect link to etherscan

**Expected behavior**
All links to etherscan should be replaced by custom block explorer

**Screenshots**

**Browser details (please complete the following information):**
 - OS:Ubuntu 20
 - Hardware Wallet:
 - Browser: Firefox 81
 - MetaMask Version: 8.1.1

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment]
Thanks for the report! It looks like a duplicate issue was created for this problem: #10041. I'm going to close this in favour of that one, since there was some discussion on that issue.
