### ISSUE TITLE
Add Contact with QR code not adding address

### ISSUE THREAD

**Issue by tmashuang** [MetaMask/metamask-extension#9649]
**Describe the bug**
Related to #9043 which was fixed in #9608. Upon scanning an QR coded address on the Add Contact screen, it will not add the address to contacts, provide an error message, or transition the screen. 

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to Settings > Add Contact, or navigate to `chrome://{extensionId}/home.html#settings/contact-list/add-contact`
2. Click on the QR code scanner icon within the address field.
3. Allow MetaMask to use the camera
4. Scan an QR coded ethereum address, and address is not added.

**Comment by darkwing** [comment]
This was fixed by https://github.com/MetaMask/metamask-extension/pull/9667
