### ISSUE TITLE
RPC Error: Invalid parameters: must provide an Ethereum address.

### ISSUE THREAD

**Issue by kombos** [MetaMask/metamask-extension#9665]
I'm **sometimes** receiving an error from Metamask, which seems to fix itself once i just refresh the page (re-render the react component(s): 

```
MetaMask - RPC Error: Invalid parameters: must provide an Ethereum address. Objectcode: -32602
message: "Invalid parameters: must provide an Ethereum address."stack: "Error: Invalid parameters: must provide an Ethereum address.↵    
at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:329548)↵    
at Object.invalidParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:329870)↵    
at m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:108360)↵    
at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:60:106337"__proto__: Object
(anonymous) @ inpage.js:1
```
I've verified that it is not the problem of null value injection since a valid value can be seen being provided: 
![image](https://user-images.githubusercontent.com/18464450/96734269-fd176f80-13d7-11eb-9d1a-e1124959180f.png)

cannot provide steps to reproduce since it pertains to my app. This is a breaking error (breaks the app).

**Browser details :**
 - OS: Windows 10 Home Edition
 - Browser: Chrome Version 86.0.4240.111 (Official Build) (64-bit)
 - MetaMask Version: 8.0.10

**Comment by jacobcantele** [comment]
Hi @kombos , thanks for reaching out. We actually don't provide developer support via GitHub. We recommend the Ethereum StackExchange for this sort of thing: https://ethereum.stackexchange.com/
