### ISSUE TITLE
Submitting a tx for hardware wallet that is disconnected causes metamask to be unusable

### ISSUE THREAD

**Issue by terencechow** [MetaMask/metamask-extension#9686]
**Describe the bug**
I disconnect my hardware wallet quite often. Sometimes I submit a tx when the hardware is disconnected. When I realize, I connect the hardware wallet and try and resubmit the transaction. However it does not allow resubmitting. The UI is completely broken at that point. For example, clicking speedup, choosing a new gas and clicking 'save' does not submit the transaction. The UI stays on the 'save' screen and cannot proceed, almost as if there is an error that is not caught or something.

Logging out / Logging back in or removing the hardware wallet and adding it back does not fix this. Metamask is basically unusable from this point forward. The only solution I've found is to uninstall metamask and reinstall it. That's quite a painful UX for something that happens quite often.

**Steps to reproduce (REQUIRED)**

1. Import the hardware wallet to your metamask account.
2. Disconnect your hardware wallet from the usb.
2. Make a transaction on any page and submit it.
3. Realize your hardware wallet is disconnected and connect it.
4. Click the speed up button on the transaction and try resubmitting it. It is not possible.

**Expected behavior**
I expect that when I click speed up button it should resubmit.

I also expect that if my hardware wallet is not connected the transaction should fail. When my hardware wallet is connected, and I don't confirm a tx on the wallet in a given time, metamask will mark the transaction as failed after a given time. However that same user experience when the hardware wallet is disconnected doesn't happen. I would expect that submitting a tx when my wallet isn't connected would fail after X seconds.

 - OS: Macbook Mojave 10.14.6 
 - Hardware Wallet: Ledger Nano S 1.6.0
 - Browser: Chrome Version 86.0.4240.80 (Official Build) (x86_64)
 - MetaMask Version: 8.0.10

**Extra details**
The transaction is not actually submitted to infura or whatever eth nodes being used (because the hardware wallet didn't sign it). However the transaction stays stuck in Metamask so you can't submit a future transaction. (There isn't even a nonce for you to replace). Hence the reason that metamask becomes completely unusable after this point.

**Comment by hegedis-andor** [comment]
I just happened to get this bug. Tried to submit a tx without the ledger is connected.

Oh my God, the solution to this is to uninstall and reinstall metamask? 
Come on guys

**Comment by jacobcantele** [comment]
Possibly related to this issue?

https://github.com/MetaMask/metamask-extension/issues/10140

**Comment by johansten** [comment]
I've been dealing with this issue for quite a while too now.

It's not only when the hardware wallet is physically disconnected. Sometimes it's there, and you just never get a signing request in the hardware device. Transactions queue up, but can't be removed.

Maybe a simple way to at least deal with the effects of the problem is to enable us to cancel unsigned transactions?
Now they are just stuck, and the only recourse is to wipe everything and do a clean install.

**Comment by dpazdan** [comment]
Closing and reopening the browser fixes the tx submitted stuck state.  Also changing networks (toggling to a testnet and back to Mainnet).  Not a fix but more a workaround.

**Comment by segun** [comment]
I can't seem to replicate this issue using Metamask 10.3.0, Ledger Nanos, Ledger Live, Chrome 95 and Mac OSX 11.6 and BSC Testnet

The transaction stay stuck in pending state, but metamask works normally. 

After connecting my ledger, and unlocking it, I clicked speed up and I got an alert on the ledger and I was able to confirm the transaction and it went through

**Comment by danjm** [comment]
For MetaMask extension engineers, this thread is about the resolution to this issue: https://consensys.slack.com/archives/GTQAGKY5V/p1636542847278800
