### ISSUE TITLE
Cancellations sometimes have an unreasonably low default gas price

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-extension#9689]
Our default gas price for cancellations is 10% higher than the price of the transaction it is attempting to cancel. This serves as a decent default in most cases, but during periods of high network volatility it can suggest unreasonable gas prices. If gas prices have risen dramatically since the original transaction was submitted, then increasing the original gas price by 10% may result in a price low enough to be rejected outright.

The default gas price used for cancellations should instead take into consideration current gas prices. For example, we could consider using our most recent "safe low" gas price in the case where it's above our current default.

Related: #8011

**Comment by danjm** [comment]
This should have been fixed by https://github.com/MetaMask/metamask-extension/pull/11936 and https://github.com/MetaMask/metamask-extension/pull/12069
