### ISSUE TITLE
Custom networks show the wrong base asset

### ISSUE THREAD

**Issue by d10r** [MetaMask/metamask-extension#9701]
With Metamask (last checked in v.8.0.10) pointed to xdai chain (_Symbol_ set to "xDAI" in Settings->Networks), the view for sending native coins is inconsistent. As seen in the following screenshot, it still shows "ETH" in the title and in the _Asset_ field while correctly showing "xDAI" in the _Amount_ field.

![image](https://user-images.githubusercontent.com/5479136/97041794-561a0b80-1570-11eb-86e1-b8fc09a43a6a.png)

In the consecutive confirmation view, there's a label _SENT ETHER_ which should also be updated to reflect the chosen symbol:

![image](https://user-images.githubusercontent.com/5479136/97042348-2d464600-1571-11eb-9157-ede6998d957e.png)

**Comment by jacobcantele** [comment]
This is related to #9492
