### ISSUE TITLE
MetaMask chrome keeps loading and then gives me Network request failed

### ISSUE THREAD

**Issue by ihabhamed** [MetaMask/metamask-extension#9708]
windows 10 pro
chrome last update
it works fine on fireFox but on chrome it keeps getting Network request failed 
i have tried to reinstall the extension but didn't solve it 
![Screenshot](https://user-images.githubusercontent.com/10481248/97063565-bcb71d80-15a0-11eb-81f8-a9319eb1410d.png)

**Comment by jacobcantele** [comment]
Hi @ihabhamed , are you using any other extensions that could be interfering with the MetaMask extension? This request is best served as a support request at support.metamask.io. Closing this issue unless there is an indication of a MetaMask bug.
