### ISSUE TITLE
error with CUSTOM SPEND LIMIT 

### ISSUE THREAD

**Issue by AndreiMinaDraghici** [MetaMask/metamask-extension#9711]
After setting a custom SPEND LIMIT in the interaction of metamask with the farming protocol from Honeyswap, i recieving this error "ALERT: Transaction Error. Exception thrown in contract code." and i can not change the Chain ID any more. is stuck to 0x64

**Steps to reproduce (REQUIRED)**
Metamask connected with ledger on Firefox with 1.5 LP token HNY/STAKE transfered from other wallet (the one with the problem)
 
![image](https://user-images.githubusercontent.com/66927613/97082282-3be43a00-1611-11eb-9899-b9506dbe7446.png)

Go to https://hny.farm/ and connect wallet
 
![image](https://user-images.githubusercontent.com/66927613/97082286-443c7500-1611-11eb-8339-8731c21ad9ed.png)

Approve the token for farming and on metamask pop-up edit permission
 
![image](https://user-images.githubusercontent.com/66927613/97082294-4d2d4680-1611-11eb-9af8-d8e69288d52d.png)

At custom permission i set custom limit 1
 
![image](https://user-images.githubusercontent.com/66927613/97082298-53bbbe00-1611-11eb-99f9-b8a693939e76.png)

Hit confirm. Transaction approved
 
![image](https://user-images.githubusercontent.com/66927613/97082303-59b19f00-1611-11eb-9d0b-8beebd56c74d.png)

Hit Plus button
 
![image](https://user-images.githubusercontent.com/66927613/97082304-5fa78000-1611-11eb-9bd3-afa224b15f5c.png)

Pop up came out
 
![image](https://user-images.githubusercontent.com/66927613/97082311-66ce8e00-1611-11eb-9c39-0c839f3de681.png)

And set the value to 1.5
 
![image](https://user-images.githubusercontent.com/66927613/97082315-6b934200-1611-11eb-86bd-f89d7a4c9d8e.png)

Hit confirm. Pop-up came up and error. The original is (that is in romanian): ALERT: Transaction Error. Exception thrown in contract code.
 
![image](https://user-images.githubusercontent.com/66927613/97082321-72ba5000-1611-11eb-8dd3-a4933a5dab74.png)

Hit confirm and then error
![image](https://user-images.githubusercontent.com/66927613/97082323-78179a80-1611-11eb-8af9-567206896fb1.png)

 
Cancel. Press + button and insert value 1 and confirm

 
![image](https://user-images.githubusercontent.com/66927613/97082330-7e0d7b80-1611-11eb-8eae-7b1fcca3c167.png)

New pop-up but this time without error. Hit confirm
 
![image](https://user-images.githubusercontent.com/66927613/97082336-836ac600-1611-11eb-8591-4c019e1cb53f.png)

And error popped out
![image](https://user-images.githubusercontent.com/66927613/97082340-8a91d400-1611-11eb-8df3-e63881bb41f3.png)
 
And then reset metamask account
![image](https://user-images.githubusercontent.com/66927613/97082345-954c6900-1611-11eb-9144-39333e5e8d59.png)
 
Try it again with value 1 and same error
![image](https://user-images.githubusercontent.com/66927613/97082350-9ed5d100-1611-11eb-8c40-29e7fd20f0a3.png)
 
In blockscout this failed transaction is not registred
 
![image](https://user-images.githubusercontent.com/66927613/97082353-a6957580-1611-11eb-9c77-3701512f185a.png)

And in metamask i can not change the chain ID from  0x64 to 100. I can not save-it. 
 
![image](https://user-images.githubusercontent.com/66927613/97082363-af864700-1611-11eb-9e62-7ea8fe41c5ad.png)

**Expected behavior**
when i entered value 1 it shoud work and farm the token

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: Ledger Nano S
 - Browser: Firefox Browser 82.0 (64-bit)]
 - MetaMask Version: 8.1.2

**Additional context (Error Messages, etc.)**
I had some similar problem on chrome but there i have farmed the token but i was not alowed to farm any more problably beacause of the CUSTOM SPEND LIMIT. I think that the problem is that i can not adjust the custom SPEND LIMIT any time, but only at the first interaction with the farming contract

**Comment by tmashuang** [comment]
There are numerous issues with how this issue is organized and the problems presented. I will try to go through each one.

1. You are staking more value than the approved spending limit.
2. You are resetting your account which is meant for removing your transaction list and resetting your nonce, so if you have an pending tx when resetting, you are essentially trying to override the pending tx since it has the same nonce.
3. I believe the Dapp can verify the allowed spending limit of contract and act accordingly whether to allow contract interaction or more custom spending limit. Uniswap is a good example of this.
4. 0x64 is 100 in hexadecimal, there the same value.

The screenshots are poor and unable to extract any of the information out of. If you still require clarification and/or help debugging transactions submit your state logs to our support team at [https://support.metamask.io](https://support.metamask.io).

**Comment by ekatzenstein** [comment]
Had the same issue. You need to enable contract data on your Ledger Ethereum app. Then go through the limit approval process, and be sure to confirm on both metamask and your ledger. Worked for me.
