### ISSUE TITLE
Can't turn off autoRefreshOnNetworkChange unless using enable

### ISSUE THREAD

**Issue by cliffhall** [MetaMask/metamask-extension#9718]
**Describe the bug**
The MetaMask docs say that `ethereum.enable` is deprecated for getting the accounts. They [explain how](https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider ) to use `ethereum.request({ method: 'eth_accounts' })` instead. However if you don't use `ethereum.enable`, attempts to turn off `autoRefreshOnNetworkChange`  will fail, and the page will reload if the user changes networks.

**Steps to reproduce (REQUIRED)**

**This works. Accounts retrieved, page does not refresh on network change.**
```
                // Request account access
                const accts = ethereum.enable();

                // Metamask, deprecated but still important
                if (ethereum.hasOwnProperty("autoRefreshOnNetworkChange")) {
                    ethereum.autoRefreshOnNetworkChange = false;
                }
```

**This does not work. Accounts retrieved, page refreshes on network change.**
```
                // Request account access
                const accts = await ethereum.request({ method: 'eth_accounts' })
                   .then(accts => console.log(accts))
                   .catch((err) => console.error(err));

                // Metamask, deprecated but still important
                if (ethereum.hasOwnProperty("autoRefreshOnNetworkChange")) {
                    ethereum.autoRefreshOnNetworkChange = false;
                }
```

**Expected behavior**
Accounts retrieved, page does not refresh on network change.

**Browser details (please complete the following information):**
 - OS: OSX 10.15.5
 - Browser: Version 86.0.4240.111 (Official Build) (x86_64)
 - MetaMask Version: 8.0.10

**Comment by jacobcantele** [comment]
Hi @cliffhall , thanks so much for raising this. We're working towards multiple simultaneous network connections (see #9254), so this issue will end up deprecated by the overall superior UX. I'm going to close for now.
