### ISSUE TITLE
NaN showing in Speed Up Advanced Gas Chart

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#9751]
**Describe the bug**
I'm seeing `NaN` labels in the advanced gas chart when trying to speed up a transaction.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Send $ETH to any address
2. Click 'Speed Up'
3. Click the Advanced tab

* Note: In my case, I was on Goerli network

<img width="402" alt="NanGace" src="https://user-images.githubusercontent.com/46655/97493305-c7700a80-1932-11eb-9f4b-63df6e2a7aac.png">

**Comment by tmashuang** [comment]
Closing this since we no longer allow navigating Customize Gas modal from the Send Screen on Non-mainnet networks. The [PR](https://github.com/MetaMask/metamask-extension/pull/9189) that implemented it is apart of `8.1.0`.
