### ISSUE TITLE
Odd Character Displaying in Gas Popup

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#9762]
While editing the gas for a given swap, I found this odd icon or character not properly displaying:

<img width="754" alt="FirefoxIcon" src="https://user-images.githubusercontent.com/46655/97648994-32e5d500-1a24-11eb-89b3-830c4f9b8fbe.png">

Browser:  Firefox

**Comment by jacobcantele** [comment]
@darkwing which OS is this? It looks like we're using a character from a font you don't have installed.

**Comment by darkwing** [comment]
Mac OS / Firefox.

**Comment by darkwing** [comment]
Found this again; it's classname is `fa fa-check fa-sm` and the character string is `"\f00c"`
