### ISSUE TITLE
Seed Phrase not working

### ISSUE THREAD

**Issue by phillysee5** [MetaMask/metamask-extension#9765]
Hi There
Whilst trying to recover a metamask account it is telling me that my seed phrase is invalid. I have copied it 100% correctly.
Searching the issue revealed some issues to do with white space and capitalization, even with this it is not working.
The twelve words are copied exactly with one space between each word and no more, no caps, invalid seed phrase. Worrying to think I might lose that crypto forever.

I am using Google Chrome

Grateful for any assistance
PhillyC

**Comment by tmashuang** [comment]
The words display in the order of left-to-right, is this how you copied it as well? I've heard users copying the seed phrase top-to-down and right-to-left.

**Comment by danfinlay** [comment]
We use this GitHub repository to track known problems, so to help diagnose your issue, you'll want to contact our support team at https://support.metamask.io.

I'm closing this here for now, but if support is able to confirm a bug, we can re-open this issue.
