### ISSUE TITLE
Metamask plugin causing strange errors on several pages

### ISSUE THREAD

**Issue by goldenfang** [MetaMask/metamask-extension#977]
Hi,

My bank website and news magazine with paid subscriptions stops working after I installed metamask. I'm 100% sure that it is metamask fault, because when I'm disabling metamask plugin in Chrome settings everything works OK.

This is really strange. Do you inject eth related objects into DOM of every visited page? How can I help you to debug the problem?

**Comment by kumavis** [comment]
@goldenfang we do inject into every page, because there is no way to determine what is a dapp and what is not. We are considering per-dapp opt-in injection.

That said, injection should not interfere with third party sites. Can you provide more information so we can reproduce the bug? The magazine website and errors from the javascript console would be very helpful.

**Comment by goldenfang** [comment]
JS Console doesn't contain any error or warning.  Of course there is "MetaMask - injected web3".
However, I noticed in Security Tab (Dev Tools) something that could explain my problems:

chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn
View requests in Network Panel
Not Secure
Your connection to this origin is not secure.

My Chrome browser claims (OSX) that metamask loaded content using not secure protocol. Do you
have the same?

**Comment by frankiebee** [comment]
Can you give us the url of the magazine website so we can reproduce?

**Comment by flyswatter** [comment]
We may have reproduced this on the Chase website.

If you'd like to give us useful logs, you can look for errors in these various logging locations:

https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by goldenfang** [comment]
The problem occurs on Polish bank website unfortunately only after successful login :-)
It is mbank.pl and that is interesting it occurs only in "company account" mode.

I was looking at logs and consoles and I found nothing except information that Metamask's scripts were loaded using insecure protocol. I am not sure if this is the reason (CSP ?), but if yes, it is always possible to inline all javascripts rather than pointing to chrome-plugin scheme.

**Comment by kumavis** [comment]
yes it does sound like a CSP error

**Comment by kumavis** [comment]
we actually do inline the inpage.js script
maybe we can wrap the `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn` ref in a try / catch -- though not sure where thats coming from

**Comment by goldenfang** [comment]
Hmm. No it's not CSP, because CSP violations are reported to Developer Console. In my case there are no such errors. I will try to play with js console or Tampermonkey extension and see what is going on. I will let you know if I manage to debug this.

**Comment by kumavis** [comment]
@goldenfang thank you!

**Comment by flyswatter** [comment]
Hey @goldenfang any luck on this?

**Comment by davebryson** [comment]
Also seeing this problem on wunderground weather site.   With the metamask extension enabled, you cannot see 10 day forecast or radar.  Disable metamask and all works as normal. This error only shows up when metamask is enabled:

`
Uncaught ReferenceError: oxResponseObj is not defined
    at parseARJResponse (ls-wunderground.js:1)
    at XMLHttpRequest.t.onreadystatechange (ls-wunderground.js:1)
parseARJResponse @ ls-wunderground.js:1
t.onreadystatechange @ ls-wunderground.js:1
modernizr.min.js:4 Uncaught TypeError: Cannot read property 'insertBefore' of null
    at a.yepnope.injectJs (modernizr.min.js:4)
    at modernizr.min.js:4
a.yepnope.injectJs @ modernizr.min.js:4
(anonymous) @ modernizr.min.js:4
`

**Comment by frankiebee** [comment]
@davebryson just out of curiosity do you use a analytics/add blocker?

**Comment by davebryson** [comment]
@frankiebee  No.

**Comment by tmashuang** [comment]
Reopen if this is still an issue. Possibly fixed from #2662 that prevents MetaMask from injecting into XML docs.
