### ISSUE TITLE
Numerous websites not present in blacklist are seeing the phishing warning

### ISSUE THREAD

**Issue by adamkdean** [MetaMask/metamask-extension#9776]
> Crosspost of https://github.com/MetaMask/eth-phishing-detect/issues/4332

There are numerous reports now¹ reporting the phishing warning screen whose domains are not present (nor should be) in the blacklist. This is also happening for our domain edge.network, and yet there are no references to it in this repo.

Have any of the maintainers looked into this issue? Seems to me that the phishing detection is malfunctioning.

¹  #4317, #4323 #4322 #4291 #4287 #4247 (and more)

**Comment by danfinlay** [comment]
Closing as this is no longer relevant (cross-posted issue is closed).
