### ISSUE TITLE
Usability issues while installing MetaMask on Firefox 

### ISSUE THREAD

**Issue by afmfe-iul** [MetaMask/metamask-extension#9782]
When trying to install MetaMask on Firefox, I had a couple of issues:
1.  Immediately after installing and accepting the permissions for the MM extension, a new tab to configure MM opens and a popup with a checkbox that reads "Allow this extension to run in Private Windows" appears. Not ticking the box and submitting does nothing unusual, however ticking the box and submitting closes the configuration page.

2. After the issue (1) happened, sometimes I would end up back at the [download page](https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/) and the extension wouldn't be installed. I couldn't replicate this consistently tho, but I had it happening 3-4 times while testing.

3. While configuring MM for the first time after installing, I couldn't agree to the "Help Us Improve" (definitely my fault, I was receiving a `429 Too Many Requests` response). If selecting "I Agree" failed once, choosing the "No thanks" option after wouldn't work either, only if I clicked it twice.

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Firefox Browser 82.0 (64-bit)
 - MetaMask Version: 8.1.3

**Comment by Gudahtt** [comment]
Thanks for the report!

I don't quite understand what you mean with points 1 and 2. I am familiar with the "Allow this extension to run in Private Windows" popup, but that's something Firefox asks for all extensions (or maybe for any that use the permissions we request? Not sure). That seems out of our control. Would you have expected this window to stay open even after submitting?

For point 2, did you mean that the download page would open automatically? Or that when you visit that page, it would incorrectly show that the extension wasn't installed? Or was MetaMask uninstalling itself? I can't tell what you mean here.

>While configuring MM for the first time after installing, I couldn't agree to the "Help Us Improve" (definitely my fault, I was receiving a 429 Too Many Requests response). If selecting "I Agree" failed once, choosing the "No thanks" option after wouldn't work either, only if I clicked it twice.

I was able to reproduce this, so I created a separate issue for it: https://github.com/MetaMask/metamask-extension/issues/9800

**Comment by afmfe-iul** [comment]
Hey there @Gudahtt, thanks for the fast reply!
My points 1 and 2 do sound confusing without illustration, I'll try to clarify that now :)

1. Navigate to the [download url](https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/) and click "+Add to Firefox"
2. This fellow pops up. Click "Add"
![image](https://user-images.githubusercontent.com/10389190/98288148-510c8180-1f9e-11eb-89bd-f14a927d90de.png)

3. The "Onboard" tab opens and the "Allow this extension to run in Private Windows" appears.
![image](https://user-images.githubusercontent.com/10389190/98288388-aea0ce00-1f9e-11eb-97e4-d7d27df308d4.png)

4. Clicking "Okay, got it" without ticking the box does nothing unusual. However ticking that box and clicking "Okay, got it", closes the MetaMask onboard tab immediately **(my previous point 1)**. I would have expected this window to stay open to allow me to configure my account!

5. After the onboard tab closing instantly sometimes I would be back to the tab bellow and the "+Add to Firefox" button would still be there, even when I refreshed the page. Navigating to my extension list on Firefox would indeed confirm that MetaMask was not installed. **This point relates to my previous point 2, but I couldn't replicate it consistently.** The only i think is worth mentioning is that I was installing and uninstalling the extension quite often to test and demo stuff.
![image](https://user-images.githubusercontent.com/10389190/98290338-6e8f1a80-1fa1-11eb-99d6-b6b4640a4f0f.png)

Hopefully this description is more clear! :slightly_smiling_face:

**Comment by Gudahtt** [comment]
Thanks for clarifying!

>However ticking that box and clicking "Okay, got it", closes the MetaMask onboard tab immediately

Ahh I see - this is the step I hadn't understood. This does seem unexpected and wrong.

>Navigating to my extension list on Firefox would indeed confirm that MetaMask was not installed.

So that would imply that MetaMask was automatically uninstalled, or never fully installed in the first place? This does seem quite strange.

**Comment by afmfe-iul** [comment]
> So that would imply that MetaMask was automatically uninstalled, or never fully installed in the first place? This does seem quite strange.
I would guess that it was automatically uninstalled yes, since for a short period (before clicking "Allow this extension to run in Private Windows")  I could see the fox icon on the top right extension menu and I got to the onboard page.

**Comment by jacobcantele** [comment]
I was able to reproduce this. The extension doesn't get uninstalled, but the tab does get closed. It is unexpected and annoying, but not as bad as I originally thought it would be. Clicking the MetaMask icon next to the address bar restarts the on-boarding journey.
