### ISSUE TITLE
Indicate gas cost total on custom networks

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9801]
We recently made a change to ensure we weren't applying main-net gas cost estimations to custom networks, which was good and important, but the remaining UX leaves a lot to be desired on custom networks on this screen:

![image](https://user-images.githubusercontent.com/542863/98277230-f813fd80-1f4b-11eb-8c43-2dc9199bd389.png)

Currently the users are left with just two number fields:
- gas price
- gas limit

And if a user tries to send all their tokens (without the "max" button), they get an "insufficient funds" error without further explanation. I've gotten a few messages from users confused by this, and [a few are visible on our community forum here](https://metamask.zendesk.com/hc/en-us/community/posts/360073226312-network-for-ethereum-transfer-?page=1#community_comment_360013334851).

## Improvements

- Display total cost after transaction fee
- `if (tx.value < account.balance && tx.value + gasCost > account.balance) { indicateSpecialGasWarning() }`

Needs design for what this "special gas warning" would be, which probably links someone to an explanation of transaction fees and why they need some ether for the fee, and probably a suggestion to use the "max" button.

**Comment by adonesky1** [comment]
@omnat @jacobcantele are there designs for this somewhere?

**Comment by adonesky1** [comment]
@danfinlay currently we don't `Display total cost after transaction fee` for any network including mainnet until the confirmation screen. Are you thinking we should additionally display this total at this stage of the send flow for all networks?

**Comment by kevinghim** [comment]
With 1559, the estimated gas fee and total will be shown. Recommendation is to close this issue and have the 1559 designs take affect through out transaction flow.
