### ISSUE TITLE
Show error when a user enters an invalid seed phrase

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9803]
Currently if a user enters an invalid seed phrase we silently fail.

Ideally we at least indicate this, and then later we can even add an offer to try guessing the correct phrase from there, via #2893

**Comment by jacobcantele** [comment]
draft copy for error:

"Sorry, the seed phrase you entered wasn't valid."

Thinking we should keep it simple since there are a diversity of mistakes the user may have made.

**Comment by Gudahtt** [comment]
Related to #8172
