### ISSUE TITLE
Warn users when gas price being provided is wildly over estimate

### ISSUE THREAD

**Issue by epheph** [MetaMask/metamask-extension#9811]
**Describe the bug**
Giving users a text box to type in a gas price in gwei, but not performing basic sanity checks on the value entered has lead to significant amounts of lost value. Just today a user reported using metamask and intending to update the gas LIMIT to 200,000 but instead typed that value into gas PRICE. The result was tx fee of 23.5 ETH (~$9,500 at time of writing).

Transaction:
https://etherscan.io/tx/0x5641c38bf30fd19ad3332100762017573ee676f35250dcf4a976bb0cfe31ac2f

First transaction that failed due to out of gas (causing them to resubmit and type larger value in text field, intended to type into gas limit):
https://etherscan.io/tx/0xef7d38769237c797f674f954201c6357b6d278b8d20fb275d7b630498f52e4ec

Reddit thread where they posted what happened:
https://www.reddit.com/r/ethtrader/comments/jo7lj2/help_needed_i_payed_235172_eth_9500_for_120/

**Steps to reproduce (REQUIRED)**
1.) Try to send any transaction
2.) Type enormous value into the gas PRICE field
3.) Click "confirm"

**Expected behavior**
If the gas price you are specifying is, say, 100x the going rate, issue a very visible warning or modal. The transaction in question specified a gas price 10,000x higher than the going rate.

**Comment by GaylordTuring** [comment]
I really agree with this proposal. However, wouldn't it be possible to word the warning even more strongly and clearly? Something along the lines of (this is not an _actual_ suggestion, just a pointer): "Warning! You are about to pay an extremely large sum in transaction fees. This is probably a mistake and you risk loosing a lot of money. Are you really, really sure that you want to proceed? If you are unsure what any of this means, it's recommended that you abort the transaction." 

That type of warning message is something that even a n00b would understand whereas something about going rate probably is too cryptic. I could see myself reading that and just click 'continue'.

If possible, you could even specify how much the transaction fee is in dollars. I don't know. Just something that really stands out and screams at the user that this is something that he or she most certainly don't want to do.

**Comment by epheph** [comment]
I 100% agree the exact wording should be very clear and easy to understand. I didn't intend what I wrote originally to be an actual string that ends up in the UI. Thanks for weighing in.

**Comment by martinkrung** [comment]
Coming from a discussion on twitter: Just do not allow this on default. 

If somebody uses more than 2000 gwei do not process. People have to explicitly set this free over extended settings if they want to use gas price much higher. 

I think this mistake happens quite a lot: https://twitter.com/HighGwei

**Comment by Joe-mcgee** [comment]
https://cointelegraph.com/news/i-destroyed-my-life-uniswap-trader-spends-9-500-in-fees-on-120-transaction

poor lad

**Comment by cometothecaml** [comment]
https://www.reddit.com/r/ethereum/comments/jyiw8q/worst_mistake_of_my_life_gas_mistake/?user_id=95320987299
It happened again.
This is a pretty important issue and it shouldn't be very hard to fix. Something like not allowing the user to broadcast a tx with >2000 gwei as @martinkrung  suggested would be great,

**Comment by amanusk** [comment]
Another example. The user almost certainly typed 300K into gasPrice instead of gasLimit.
Just one Tx earlier they used 300K as gasLimit to trade on Uniswap
(Can't be certain that they used MetaMask)
https://etherscan.io/tx/0x031ac8c08bc34c41e6dc46943d10276b5480551656f5db6c20b3366b2d6557bf

**Comment by roheat** [comment]
I would like to work on this issue.

As per the suggestion of @GaylordTuring the error message would say something on the lines of:
**"Warning! You are about to pay an extremely large sum in transaction fees. Are you really sure that you want to proceed? If not, it's recommended that you abort the transaction."**
(I feel a shorter message should do the job)

Let me know if I can take it up, thanks!

**Comment by epheph** [comment]
I'm open to different ways to write this, but i agree it should be as short as possible. 

How about
"Warning! The gas price selected is significantly higher than necessary for inclusion in the next block. Proceeding will cost up to X ETH in gas fees" [Cancel | Confirm] ?

**Comment by danfinlay** [comment]
I’m pretty happy with the wording in Ephet’s last post. If I wanted to be even more water tight I might add a hedge word like “likely” to convey the razor thin chance that the block is quickly filled with very high cost txs.

I would not want to hard code any value for this, we’ve seen that bite many wallets; the costs of normalcy have changed a lot over time. I’d be fine showing this warning if the gas price was 2-3x our “fast” estimate.

I’ve escalated this issue for sooner inclusion in our work.

**Comment by rachelcope** [comment]
This error message is should follow the design patterns set out in https://github.com/MetaMask/metamask-extension/issues/10284

[Figma file](https://www.figma.com/file/SwzcT8L3XSoMGAwCW9W2lk/Error-Messaging?node-id=1554%3A287)

![image](https://user-images.githubusercontent.com/7483074/109075719-c66ba180-76b6-11eb-9e7e-859b731027c0.png)
