### ISSUE TITLE
Usability issues when re-entering chain IDs for Custom Networks

### ISSUE THREAD

**Issue by afmfe-iul** [MetaMask/metamask-extension#9816]
When editing the settings of a custom network the "Save" button is disabled until any value is changed. This on itself it's not an issue, however with a recent update, chain IDs need to be re-entered for custom networks, which becomes a problem because re-entering the same chain ID doesn't unlock the "Save" button. Currently the workaround for most users is to remove the network altogether and add it again, but this is not ideal.

**Steps to reproduce**
1. The first time MetaMask runs after updating to v8.1.3, the following message is shown when you try to connect to any custom network: 
![mm1](https://user-images.githubusercontent.com/10389190/98376214-173d8880-203b-11eb-80ab-8c9ee31e6032.png)

2. Following the instructions leads to a dead-end on the screen below because the "Save" button stays disabled. The only workaround for more knowledgeable users is to change the chain ID from decimal to hex or vice versa and save.
![mm2](https://user-images.githubusercontent.com/10389190/98378498-093d3700-203e-11eb-9d82-87007c8be008.png)

**Expected behavior**
Loosen a bit the rules to have the "Save" button disabled, so that user's can re-enter the same chain ID.

**Browser details (please complete the following information):**
 - OS: Linux
 - Browser: Chrome Version 86.0.4240.183 (Official Build) (64-bit)
 - MetaMask Version: v8.1.3

**Comment by Gudahtt** [comment]
Thanks for the report! This was fixed in #9808
