### ISSUE TITLE
MetaMask slow down due to `cachedFetch` in local storage

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9821]
User report on twitter:
![Screenshot from 2020-11-06 17-11-38](https://user-images.githubusercontent.com/7499938/98412806-27616200-2053-11eb-8789-3f920d697e50.png)

Initial comment from me:

I don't know why the slow down would happen, but I do know that the largest of those cached items, by far, is the response from the metaswap tokens api. It is also stored via our background controller, and so an improvement we can make that might also make this slow down issue go away is to stop saving it with the localStorage cachedFetch key, and just rely on what is stored in the background.

**Comment by darkwing** [comment]
We could consider using something like localForage (https://www.npmjs.com/package/localforage) or idb (https://www.npmjs.com/package/idb) to do storage interactions async.

**Comment by brad-decker** [comment]
More importantly... slow **how**? Where is the slowness experienced? I don't believe we should act on this without reproduction and understanding where the slowness could occur. @danjm it seems like most of the cached fetches would be the same except for plugging in multiple combinations of tokens in the swap screen which would add a new entry for each combination. Is this a correct assumption?

**Comment by brad-decker** [comment]
Ill keep adding in new swaps periodically until I reach a point where local storage is causing a noticeable slowdown. with over twenty entries it isn't yet, or perhaps the slowness is occurring in a way that I'm not expecting.

**Comment by danjm** [comment]
This may have been helped by #9919, downgrading to S3 for now.
