### ISSUE TITLE
Confirm button missing on Advanced Gas screen

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9829]
Bug report shared by Coogan Brennan

**Bug description and steps to reproduce**
Here is how I specified a transaction to claim some AAVE tokens.  Briefly, I set a gas price of 39 and a gas limit of 352519.  Both of these numbers were much higher than the numbers proposed initially.  According to ethgasstation, gas price right now is around 20-27.  Yet the transaction still failed with an out of gas message. And in the etherscan log it says 210014  gas price and a gas limit of 152,519.  What went wrong?

It wasn’t a MM swap at all.  It was claiming “Claimable AAVE” from https://app.aave.com/staking.    And it happened twice in a row!  Both times I manually entered a gas price and a gas limit much higher than the amounts suggested. Both times, the transactions ran out of gas with the lower, original parameters.  My sense is that the parameters that I put into MetaMask weren’t saved.

![image (7)](https://user-images.githubusercontent.com/7499938/98565993-d33fc300-2288-11eb-8a0a-97161c7a0978.png)
![image (6)](https://user-images.githubusercontent.com/7499938/98565995-d3d85980-2288-11eb-9e17-70a34859b8d9.png)
![image (5)](https://user-images.githubusercontent.com/7499938/98565997-d470f000-2288-11eb-8a7c-334cea73b916.png)

**Comment by tmashuang** [comment]
> My sense is that the parameters that I put into MetaMask weren’t saved.

Are they scrolling down the advanced gas screen to click save?

**Comment by jacobcantele** [comment]
Judging from the screenshot, it looks like the Save button is somehow missing from your viewport, and all of the elements are overly zoomed within the Extension. Coogan, can you confirm which browser/OS this was and whether you had zoom level modified?

**Comment by danjm** [comment]
We no longer use that advanced modal, so this can be closed.
