### ISSUE TITLE
Incorrect balance for mainnet

### ISSUE THREAD

**Issue by aminlatifi** [MetaMask/metamask-extension#9852]
**Describe the bug**
MetaMask eth balance on mainnet network is incorrect

**Steps to reproduce (REQUIRED)**
1. Open MetaMask Extension
2. Change the network to one testnet like Ropsten, Rinkeby, etc.
3. Switch back the network to mainnet
4. MetaMask shows the account balance on the testnet and does not change at all

**Browser details (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome and Firefox
 - MetaMask Version: 8.1.3

**Additional context (Error Messages, etc.)**
The RPC url for mainnet is: https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161

**Comment by liondani** [comment]
Same problem, don't show any balances anymore!

OS:Linux Mint 20 Ulyana base
Browser: Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
MetaMask Version: 8.1.3

**Comment by Buurderdur** [comment]
Same problem here but dai network working fine.
i have try to update my internet ime, and swap to firefox.. notning has help 

OS: Windows 10
Browser: crome
MetaMask Version: 8.1.3

**Comment by sickyweb** [comment]
Same problem, I tried to connect to another network, after i switched back to the mainnet and my eth balance is 0.
MetaMask Version: 8.1.3
Browser: Chrome Versione 86.0.4240.183 
The RPC url for mainnet is: https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
Blockchain ID: 0x1

**Comment by remy64x** [comment]
yeah same problem here

**Comment by Buurderdur** [comment]
is working for me now, after some rebot and chance of time on the server :) bumbum , maybe the was a unsync in the time server..
Control panel 
time and date 
internet time: chance for google server or something ele just toggel until you sync the time is ok..

**Comment by sickyweb** [comment]
Me too!!!!

**Comment by tmashuang** [comment]
Going to close this. For anyone that was not aware Infura, our Ethereum provider, had a outage in their service. Their status page, https://status.infura.io/.
