### ISSUE TITLE
MetaMask Address Book is missing after upgrade

### ISSUE THREAD

**Issue by EGreg** [MetaMask/metamask-extension#9861]
**Describe the bug**
Hey everyone. Please help... I have been using MetaMask for a couple years and it was offering to save new wallet addresses with nicknames in the address book. That was a great feature. Now it auto-updated and I can’t find the address book anymore! Also when I type to search, nothing comes up. Did MetaMask just delete the entire address book from the local database or what? Any way to get it back?

**Steps to reproduce (REQUIRED)**
1. Launch MetaMask
2. Click Send
3. Start typing in the search - nothing comes up

**Expected behavior**
Address book entries would appear and can be selected

**Screenshots**

**Browser details (please complete the following information):**
OS: Chrome on Mac, also Chrome Canary on Mac
MetaMask version: 8.1.3

**Additional context (Error Messages, etc.)**
It used to work! Did not reinstall browser or anything. MetaMask was upgraded automatically, and address book seems to have disappeared. Is it at least in some IndexedDB somewhere?

**Comment by EGreg** [comment]
I looked in the state logs and they are, in fact, there. So, I have the information (which is great - because now I can back it up, and it's not that hard to open up the doc to use it).

But now the question is ... where would this show up in the actual extension? For example when I go to Contacts, it only shows "My Wallets", but here is an excerpt from state logs:

"addressBook": { "0x1": { "0x02a9e8495C2f2cb526eaa83227310C36F0800b52": { "address": "0x02a9e8495C2f2cb526eaa83227310C36F0800b52", "chainId": "0x1", "isEns": false, "memo": "", "name": "Redacted 1" }, "0x04C30BEAe769ea53b4343CFC549c7F0f77B72549": { "address": "0x04C30BEAe769ea53b4343CFC549c7F0f77B72549", "chainId": "0x1", "isEns": false, "memo": "", "name": "Redacted 2" },



see image:

https://www.dropbox.com/s/tn67q697cp8la5t/Screen%20Shot%202020-11-12%20at%2011.47.45%20AM.png?dl=0

**Comment by tmashuang** [comment]
Confirmed this when migrating from v7.0.0 to v8.1.3. It seems that the provider chainId didn't migrate correctly possibly from https://github.com/MetaMask/metamask-extension/blob/2ebf8756a4c1023e45e4bd98367f384836cb464a/app/scripts/migrations/048.js#L35

Could you try switch to from Mainnet to Ropsten, and back? This is to reinitialize the provider object and correctly populate the chainId which is how we sort the contract list.

**Comment by EGreg** [comment]
Yep, that fixed it!

**Comment by Gudahtt** [comment]
This was fixed in #9999
