### ISSUE TITLE
Ensure eth-token-tracker can handle a single token failure

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9863]
The Synthetix token proxy upgrade was the first instance where we had a token spontaneously stop reporting balances, and it caused our eth-token-tracker to fail.

[More notes](https://roamresearch.com/#/app/MetaMask/page/l7xuDH0H1)

It should be made resilient to a single token throwing an error.
    - Ideally it should also be optimized to only make one request for a batch of tokens, as done in [the extension's detect-tokens controller](https://github.com/MetaMask/metamask-extension/blob/9df5be903b790e6505cecafd7a850304559dcfc4/app/scripts/controllers/detect-tokens.js#L79).
    - We could also consider replacing `eth-token-tracker` altogether with a controller, and handling token balance updates in the background. This might take a similar amount of work for a better result.

Marking as P1 partly because it is intermittent failure, and it is a shared bug between extension and mobile.

**Comment by Gudahtt** [comment]
>it is a shared bug between extension and mobile.

Is it? `metamask-mobile` doesn't seem to use `eth-token-tracker` at all, so I don't think it's precisely the same bug. Maybe it operates in a similar way, but I think that is a separate issue.

**Comment by brad-decker** [comment]
@danfinlay eth-token-tracker now handles a single failure, and we mark the token that failed explicitly versus marking all tokens, in the extension UI. Could we reduce the severity of this bug and/or close and open an issue to track the work towards optimizing eth-token-tracker further?

**Comment by brad-decker** [comment]
optimization work tracked in #9961
