### ISSUE TITLE
Metamask token swap failed

### ISSUE THREAD

**Issue by winsvega** [MetaMask/metamask-extension#9864]
Metamask promised me to swap sai into usdt and the transaction failed. 

I think if a token swap contract execution fails the metamask should not do a transaction otherwise you waste the ethereum fee which is quite high.

I can't help but getting worst experience with metamask :-(( (in 3 years when I use the metamask each time I open an issue on github)

**Comment by tmashuang** [comment]
What was the reason of the failure? Can you provide a tx hash?

**Comment by winsvega** [comment]
Pm?

**Comment by dpazdan** [comment]
Hi there,
Thank you for reaching our regarding MetaMask Swaps.  We ask that you submit this to us via our formal support channel here: https://metamask.zendesk.com/hc/en-us/requests/new

Here are the options to select:
![image](https://user-images.githubusercontent.com/16330048/99123447-d2c76500-25c5-11eb-9e58-5c7f88ca574d.png)

Thank you!
Dave
MetaMask Support
