### ISSUE TITLE
Help users verify the tokens they are swapping to

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9873]
# Specs

- `View this token on Etherscan (without tooltip)` **should be rendered when the amount of occurrences is *greater* than 2
- `Verify this token on Etherscan (+ tooltip)` **should be rendered when the amount of occurrences is *equal* or *lower* than 2
- Link should redirect the user to [`https://etherscan.io/address/](https://etherscan.io/address/0x9cb2f26a23b8d89973f08c957c4d7cdf75cd341c){tokenaddress}`

https://www.figma.com/file/fDtda1cs3MmPXw1MgKswZc?embed_host=notion&kind=&node-id=1531%3A1531&viewer=1

**Comment by Gudahtt** [comment]
What does `occurrences` mean exactly?

I think we should be asking the user to verify the token in any case where there is ambiguity about what the token symbol refers to.

**Comment by Gudahtt** [comment]
This is partially addressed by #9891. @danjm did you still want to leave this open to complete the rest of this?

**Comment by danjm** [comment]
@Gudahtt I spoke with Gal, who is happy to consider this closed for now.
