### ISSUE TITLE
Rendered max gas, and gas used, in swaps should be the estimate (when available) times buffer

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9874]
In swaps, the max network fee that we show is always the max as provided by the metaswap api. When no approval tx is required, we can estimate the cost in metamask and use that to calculate that max network fee. This estimate should also be the gas limit submitted with the transaction. Ensure that the 1.5 buffer is added to the estimate.

Update with more details:
- in view-quote.js `nonCustomMaxGasLimit` is set to the maximum of `usedQuote.maxGas` and `usedGasLimitWithMultiplier`, instead it should be set to `usedQuote.maxGas` only when there is no `usedQuote.gasEstimate`, and it should be set to `usedGasLimitWithMultiplier` in other cases. At the same time, `usedGasLimitWithMultiplier` no longer needs to default to `usedQuote.averageGas`, and the multiplier should be 1.5 instead of 1.4
- the same logic changes need to happen when setting the `maxGasLimit` in `signAndSendTransactions` of `ducks/swaps/swaps.js`

While we do this we should double check that the `maxGas` property on the objects returned by the `/trades` api is not being used anywhere else for anything related to the "Max network fee" in the UI or the `gas` that gets submitted with the swap transaction, for cases where no approval is needed. (It is okay to continue to use it in some "Estimate network fee" calculations as is currently done in the `calculateGasEstimateWithRefund` method in the background controller, for example)

Note that "cases where no approval is needed" should be the same as "cases where we have a truthy `usedQuote.gasEstimate` in view-quote.js

Finally, it should be noted that the calculations of `nonCustomMaxGasLimit` and `maxGasLimit` that happen in the UI can and should probably be moved to the background. This could be a good time to do that code refactor / improvement, but it is not strictly necessary to complete this ticket.

**Comment by danjm** [comment]
@darkwing Another important note on this ticket, regarding the "Ensure that the 1.5 buffer is added to the estimate." part: the `/trades` api includes a `gasMultiplier` property in its return objects. Can you, as part of resolving this ticket, us that property instead of the hard coded multiplier (which I think might actually be 1.4 in the codebase)

**Comment by Gudahtt** [comment]
>multiplier should be 1.5 instead of 1.4

Note that the current multiplier is 2.1 already, not 1.4. Swaps will take a gas limit that is _already buffered_ by 1.5, and then multiply it again by 1.4 (giving an effective buffer of 2.1)

**Comment by Gudahtt** [comment]
> At the same time, `usedGasLimitWithMultiplier` no longer needs to default to `usedQuote.averageGas`

I was confused upon first reading this ticket because I wasn't sure whether this was meant to apply to the estimated network fee as well or not. I'm now pretty sure there was no change intended for the estimated network fee, as this is calculated separately from the gas limit already. Just writing this here to confirm that this is correct.

**Comment by Gudahtt** [comment]
>While we do this we should double check that the maxGas property on the objects returned by the /trades api is not being used anywhere else for anything related to the "Max network fee" in the UI or the gas that gets submitted with the swap transaction, for cases where no approval is needed.

It is still being used as the default `gas` in the `txParams`. This appears to be overwritten in all cases in `signAndSendTransactions` in `ducks/swaps/swaps.js` though. I don't know whether it serves any purpose in the meantime - maybe we can remove it :thinking:

**Comment by Gudahtt** [comment]
>Note that "cases where no approval is needed" should be the same as "cases where we have a truthy usedQuote.gasEstimate in view-quote.js

I assume by this you meant "`gasEstimate` is never truthy when an approval is needed"? Strictly speaking this isn't true otherwise, because the gas estimate can fail for other reasons even if no approval is needed.
