### ISSUE TITLE
"Failed to sign with Ledger Device" Error

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-extension#9878]
**Describe the bug**
When attempting to get a Ledger connected properly for the first time, I saw the following error:

<img width="735" alt="LedgerFailed" src="https://user-images.githubusercontent.com/46655/99104575-c7187600-25a6-11eb-9117-3fca0102305e.png">

I'm fairly certain this occurred because I didn't have an Ethereum account create yet on the Ledger.  Once I created an Ethereum account on the Ledger, everything worked properly.

**Comment by Gudahtt** [comment]
I'm labelling this as "needs-triage" mostly because there are a number of similar issues that this may be a duplicate of, but I haven't investigated this enough yet to say for sure.

**Comment by jacobcantele** [comment]
Per David, we're closing this because this issue was related to a separate known issue.
