### ISSUE TITLE
Create a legacy-web3 support extension

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9884]
An extension that can be run after the web3.js deprecation that allows older unsupported dapps to continue working.

Ideally builds on https://github.com/MetaMask/legacy-web3/

**Comment by danjm** [comment]
This is here https://github.com/MetaMask/legacy-web3-extension

**Comment by rekmarks** [comment]
This has been done. Further issues can be tracked on the `legacy-web3-extension` repo, which is now public.
