### ISSUE TITLE
Unexpected token r in JSON at position 0

### ISSUE THREAD

**Issue by cart0uche** [MetaMask/metamask-extension#9886]
Hello,
I can no longer log into my account on my Android phone. After typing my password and pressing login, I get the error 

`Syntax error: Unexpected token r in JSON at position 0`

I don't know how to reproduce it.
But I can say that I tried a very large number of passwords before finding the right one

[screenshot](https://p13.zdusercontent.com/attachment/2313093/sNeHzFvIPcI0zVRKt3BkgVzrL?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..DYov7gUgQ1EZiY6wO69olQ.zVts11OzB2oG9nBPersjT6JCywM6SpP1xpmBSleWu-8W9nZUQOOGwQYIwXZ5gwVdFgoy3MFpvwesCpAenMNRLNUYkJzTOdp50HuhMcEMqAvAvMpDgRtyEfqPmDQlTLZsCr0IIvZBd6xzj1_JmpOya7yh3wldIp-B5pmih5KTdYJZfQFOfQoaAT924_EVy6t0SK_WTKqyTzr401rf5o3DkdvzlA7Z171zZUduFfQVZ2PsUN92OvvJP8JAgE4LDF7Udi1e-ESxfLoRzluUxpQmxDublahaX2Lqlg-f-bFpP04.eDqP2PBKgT8mZhAiixHpKw)

 - OS: Android
 - MetaMask Version: 1.0.5

**Comment by tmashuang** [comment]
I suspect this is for mobile, please open an issue on the [mobile repository](https://github.com/metamask/metamask-mobile).
