### ISSUE TITLE
Tokens not being listed in the Asset list

### ISSUE THREAD

**Issue by santisiri** [MetaMask/metamask-extension#9887]
**Describe the bug**
It won't display a token that was listed before, then it wasn't listed as it went to 0 in balance, and when aiming to list it again, wallet claims that token is already listed.

**Steps to reproduce (REQUIRED)**

While on the list of Assets, after clicking on "Add Token" to add a token that does not appear listed like `WBTC`, it won't allow me because it claims that this token is already listed. 

Even though I have clearly listed the token before, when it went to a balance of 0 it might have disappeared from the list and now that I got it back, wallet still claims that the token is listed but it doesn't show up in the interface. 

**Browser details (please complete the following information):**
 - OS: OS X
 - Hardware Wallet: None
 - Browser: Chrome Version 86.0.4240.193 (Official Build) (x86_64)
 - MetaMask Version: 8.1.3

<img width="352" alt="Screen Shot 2020-11-16 at 12 29 44 PM" src="https://user-images.githubusercontent.com/2153166/99248503-d860bd00-2808-11eb-8103-ddd2e35d5557.png">

<img width="346" alt="Screen Shot 2020-11-16 at 12 29 56 PM" src="https://user-images.githubusercontent.com/2153166/99247738-a6029000-2807-11eb-9201-9c51e06f3754.png">

<img width="352" alt="Screen Shot 2020-11-16 at 12 30 02 PM" src="https://user-images.githubusercontent.com/2153166/99247742-a69b2680-2807-11eb-8f0a-4922cf37c845.png">

**Comment by MikeYak** [comment]
Same problem.

**Browser details (please complete the following information):**

- OS: Windows 10
- Hardware Wallet: None
- Browser: Firefox 83.0
- MetaMask Version: 8.1.3 and Version: 8.1.4

**Comment by ProkhorZ** [comment]
Same issue in version 8.1.3, but the token balance never went to 0. None of my tokens are shown, and I can't add them because the extension says I've added them already. 

OS: Windows 10
Browser: Chrome 86.0.4240.193

Token balances are displayed in Uniswap but not in Metamask:

![no token balances](https://user-images.githubusercontent.com/22837744/99430447-a420f580-2909-11eb-9d08-b60062932481.png)

**Comment by tmashuang** [comment]
I believe that #9863 is the root cause of this issue, if I am incorrect on my assumption please provide more details to that counters it.
