### ISSUE TITLE
Hide the Etherscan "token link" until we seriously prevent users from sending to token addresses.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#9898]
I swear we've implemented this feature before, maybe there was a regression, but people still seem to be doing this, so as a short-stop, let's remove this confusing link:

![image (8)](https://user-images.githubusercontent.com/542863/99445625-ab78dc80-28d2-11eb-964c-b0865fb56e78.png)

**Comment by Gudahtt** [comment]
That link is valuable for verifying the token address. Is it possible to verify the token address without this?

**Comment by Gudahtt** [comment]
We could consider linking to the address-specific token page on Etherscan (i.e. `https://etherscan.io/token/${tokenAddress}?a=${userAddress}`). That looks a bit more difficult to confuse than the link we use now.
