### ISSUE TITLE
Bug: swaps shows no quotes available when trying to get quotes after first viewing a quote you can't afford

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9906]
Repro steps:
- request quotes you don't have enough eth for
- after successfully making it to the view quote screen, go back
- request a different quote that you don't have enough eth for
- you will see "No quotes available"

This has been around since at least v8.1.3

Proximate cause is that `navigatedBackToBuildQuote` gets called after `setBalanceError` when going back to the build quote screen.

**Comment by darkwing** [comment]
@danjm Is correct about this being a timing issue.  See the following gist:

https://gist.github.com/darkwing/1c44fec6053f9731bb31cb513432df8b

With the following server output:

<img width="722" alt="TimingConflict" src="https://user-images.githubusercontent.com/46655/100646367-8f7a2f80-3303-11eb-93e8-7979f69821a7.png">

It seems as though `onInputChange` is correctly setting state, but in-flight `resetSwapsPostFetchState` muddies the state and causes the problem.  If I add a `setTimeout` inside `onInputChange` to offset the `resetSwapsPostFetchState` timing problem, everything works correctly, thus proving the timing issue.
