### ISSUE TITLE
No sender and recipient addresses shown when sending a token in full screen mode

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9920]
Repro steps:

0. Use the app in full screen 
1. Go to the send screen
2. Select a token
3. Click "Next"
4. On the confirm screen, you will not see the sender to recipient addresses

If you do the same in the popup you will see them

This issue is not present in v8.0.10, but is present in v8.1.0

![Screenshot from 2020-11-19 19-16-26](https://user-images.githubusercontent.com/7499938/99733707-23dec980-2a9c-11eb-8659-803c5a48a784.png)

**Comment by tmashuang** [comment]
I believe this was introduced by https://github.com/MetaMask/metamask-extension/pull/8601/, when the formatting changed from the render to include all conditions.
