### ISSUE TITLE
Replacing transaction with custom nonce and then Speedup reuses the original

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/metamask-extension#9927]
Version 8.1.3

### Scenario
When using custom nonce feature to replace a pending transaction, I then click Speedup

### Expected Behavior
The replacement transaction is sped up

### Actual behavior
The original is sped up

**Comment by tmashuang** [comment]
Related to #7305.

**Comment by Gudahtt** [comment]
Thanks for the report! This appears to be a duplicate of #8268
