### ISSUE TITLE
syncWithAddresses not remove accounts from cachedBalances

### ISSUE THREAD

**Issue by codeoneline** [MetaMask/metamask-extension#9937]
After you import some addresses from ledger, when your import addresses from trezor, the old accounts not removed from `cachedBalances`

**Comment by jacobcantele** [comment]
@codeoneline can you say more about why this is an issue for you?

**Comment by codeoneline** [comment]
Maybe it's better to just delete the removeAccount in syncWithAddresses，so we can import multi hw address
