### ISSUE TITLE
Attempting to "Try again" after getting to the swaps "Quotes Expired" screen results in consistent "No quotes available"

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9940]
To recreate:
(1) Request quotes in swaps
(2) Wait until the quotes expire (3 run downs of the timer)
(3) See the "Quotes Expired" screen
(4) Click "Try again"

It seems that you will now consistently hit "No quotes available". Exiting swaps and going back in makes the problem go away.

**Comment by danjm** [comment]
Actually, this is not reproducible in all cases...

**Comment by danfinlay** [comment]
We haven't been able to reproduce yet, so we're going to close for now, we can reopen if we find reproduction details.
