### ISSUE TITLE
Warn users of Metamask swap of high slippage

### ISSUE THREAD

**Issue by cometothecaml** [MetaMask/metamask-extension#9944]
Describe the bug
Metamask swap seems to not warn users of high slippage. For example, this user swapped $600 in LP tokens for pretty much 0 WETH. A basic sanity check (like making sure the slip is not 99% or not allowing swaps of UNI V2 tokens) would have saved the funds.

Reddit post:
https://www.reddit.com/r/ethereum/comments/k0egph/swapped_uni_eth_lp_to_eth_on_metamask_but_where/

Etherscan TX:
https://etherscan.io/tx/0xf64e0d7a8aad3d69b64c7ba37304429d6f0a7dfd6fff66af47b94b46b88f29e8

Steps to reproduce (REQUIRED)
1.) Try to swap the UNI-WETH liquidity token to WETH

Expected behavior:
The user should have been alerted to the huge slip/price impact his TX would have caused. Looking at the screenshot the user sent, there wasn't a warning about price impact. Also, preventing users from swapping liquidity tokens would also help.

**Comment by danjm** [comment]
Thanks for the report! There is a PR in review that addresses this https://github.com/MetaMask/metamask-extension/pull/9899

**Comment by Gudahtt** [comment]
This was addressed in #9899
