### ISSUE TITLE
Custom RPC not taking value from Chain ID input

### ISSUE THREAD

**Issue by quangld** [MetaMask/metamask-extension#9952]
**Describe the bug**
Trying to connect to my node (ETH Mainnet) directly, set "Chain ID" input to 1, getting error
`"The endpoint returned a different chain ID: 0x0"`

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to "Customer RPC"
2. Enter Network Name, New RPC URL, Chain ID
3. Click Save

**Expected behavior**
Should getting no error when all the parameters are correct

**Browser details (please complete the following information):**
 - OS: Ubuntu Desktop 18.04
 - Browser: Chrome - Version 87.0.4280.66 (Official Build) (64-bit)
 - MetaMask Version: 8.1.3

**Additional context (Error Messages, etc.)**
Metamask sent wrong id to the node. It seems not taking id from the input field.
see the picture attached
![Screenshot from 2020-11-29 13-19-07](https://user-images.githubusercontent.com/8688582/100534819-8f1b5f00-3245-11eb-9fde-3c6ad4d976a1.png)

**Comment by quangld** [comment]
need to investigate further

**Comment by Myu-Unix** [comment]
I have a similar issue with a Geth 1.9.25 full client (in sync). Was working before with a light client before.

Metamask 9.0.5. Tried reinstall and seed phrase load but same issue. Any pointers ?

**Comment by myset** [comment]
I have the same issue issue with a Geth/v1.10.0-unstable-bf5b379b-20210223/linux-amd64/go1.16 - full client (synced)

Web Developer Tools - POST 200 OK exception message is - chain not synced beyond EIP-155 replay-protection fork block
