### ISSUE TITLE
Add Network button is hidden under a different scrollable box in the Networks settings

### ISSUE THREAD

**Issue by randymetamask** [MetaMask/metamask-extension#9953]
**Describe the bug**
The **Add Network** button is hidden under a different scrollable box/bar when the Networks section in Settings is opened in the extension window.

**Steps to reproduce (REQUIRED)**
I didn’t see the **Add Network** button in the extension window, so I had to open it in the Expanded View. Then I realized the button might be there, and it is, but it’s not accessible unless you scroll down several times for it to appear down there (checkout video for steps to reproduce).

![scrollbar](https://user-images.githubusercontent.com/72138609/100549922-76776d00-3276-11eb-84a3-e329b89d664f.gif)

**Expected behavior**
The scrollable box should at least include the **Add Network** button at the end/bottom, because two different scrollable boxes make it more difficult to reach the end outside the first box.

**Browser details (please complete the following information):**
 - OS: OSX
 - Hardware Wallet:
 - Browser: 
 - MetaMask Version: 8.1.3

**Comment by Gudahtt** [comment]
Thanks for the suggestion! We have addressed this in #9740, where the footer was made "sticky" to ensure it's always shown at the bottom.

Let us know what you think! I'll close this in the meantime.
