### ISSUE TITLE
Metamask plug in

### ISSUE THREAD

**Issue by Leenai0425** [MetaMask/metamask-extension#9954]
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by wbt** [comment]
What was the problem you encountered? Please Edit and complete the template or click to Close the issue.

**Comment by Gudahtt** [comment]
Closing for now. Please fill out the template next time @Leenai0425! Feel free to ask if you have any questions about it.
