### ISSUE TITLE
Networks settings list has hidden vertical scrollbar

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#9955]
**Describe the bug**
The Networks Settings list has a hidden vertical scrollbar that hides access to some networks, preventing a user who doesn't know about this bug from updating settings for hidden networks.  When those networks were added prior to a chainId being required, and the user is going into the Networks Settings to add the chainId as required by that MetaMask update, they cannot, but also cannot re-add the network because the RPC URL is "already in the list of known networks" despite not being visible in the list of networks available under Settings.

**Steps to reproduce**
1. In an older version of MetaMask, add multiple private networks with a custom RPC URL but no chain ID. 
2. Update to MetaMask 8.1.3.  For most users, this step will be unavoidably and non-optionally force-pushed with no way to easily revert. 
3. Upon loading MetaMask after the update, use the network selector to attempt to connect to one of these private networks. 
4. You will get an error that a chainId is now required and you have to change this in settings.
5. Click to go to settings, or click on the account selector ball in the upper right corner and then click Settings at the bottom of the popup list.
6. Scroll down and click Networks. 
7. Grab the right-side scroll bar or hover over it and use the scroll wheel.  Scroll all the way up and down, and you won't see that network. 
![image](https://user-images.githubusercontent.com/563406/100641421-6fe40680-3305-11eb-8c56-3dab18866e7c.png)
8. If you are paying close attention, you may notice a horizontal scrollbar at the bottom.
9. Click that horizontal scrollbar and drag it right.
10. Another vertical scrollbar is revealed.
![image](https://user-images.githubusercontent.com/563406/100641557-9dc94b00-3305-11eb-9105-b3ce8af39425.png)
11. With that, you can scroll down and see the other networks. 

**Workaround**
If you have a scroll wheel on your mouse, after clicking Networks in the Settings list, you can hover over the list of networks and use the scroll wheel to scroll down through the networks list; the inner list will be what's activated by the scroll wheel.  When you reach the bottom, keep scrolling.  After a second or so the active element will become the main one (with visible scroll bar) and you will be able to continue scrolling down to the Add Network button.  (This is separately reported as Issue #9953; both should probably be fixed in the same PR.) 

**Expected behavior**
All the networks are visible when manipulating the vertical scroll bar to the right.  There is only one scrollable element and which element is scrolling doesn't keep changing back and forth between two things when the mouse is over the central area. 

**Browser details:**
 - OS: Win10
 - Hardware Wallet: N/A
 - Browser: 86.0.4240.183 (Official Build) (64-bit)
 - MetaMask Version: 8.1.3

**Comment by jacobcantele** [comment]
We believe this was verified in 8.1.4. Closing unless there is another report.

**Comment by Gudahtt** [comment]
Specifically we think this was fixed by #9740
