### ISSUE TITLE
Password not excepted for Mobile sync

### ISSUE THREAD

**Issue by CrackerHax** [MetaMask/metamask-extension#9964]
**Describe the bug**
Try to put in password for mobile sync and not accepted

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: android 10
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: Chrome
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment]
Could you please fill out the rest of the template?

>Try to put in password for mobile sync and not accepted

Are you sure it's the correct password? Have you tried locking the extension and unlocking it again to make sure?

**Comment by Gudahtt** [comment]
Closing this for now, as we don't have enough information to investigate.

**Comment by CrackerHax** [comment]
Why dont you test it and see for yourself. Pretty clear what I am referring to.

**Comment by Gudahtt** [comment]
I meant what operating system and browser is _the MetaMask extension_ running on. Not MetaMask mobile. The "mobile sync" here referred to syncing from the desktop extension to mobile I assume?

I did try to reproduce this already but wasn't able to.
