### ISSUE TITLE
Speed up failing and breaking future speed ups

### ISSUE THREAD

**Issue by Zolmeister** [MetaMask/metamask-extension#9971]
**Describe the bug**
1. Send tx with low gas
2. 'Speed up' tx with slightly higher gas
3. `Error: [ethjs-query] while formatting outputs from rpc  '{"value":{"code":-32000,"message":"transaction underpriced"}}'`
  see https://github.com/MetaMask/metamask-extension/issues/9317#issuecomment-732536138
4. 'Speed up' button is gone, first tx still pending

**Expected behavior**
Speed up button remains after a failed speed up.

**Comment by tmashuang** [comment]
This is just like #9317 and #9053 This brings nothing in terms of a new issue and the description is lack luster with the description/details involving transaction, nonce, etc.
