### ISSUE TITLE
Cannot unlock without a previous vault,  seed restore fails. 

### ISSUE THREAD

**Issue by kinjomusic** [MetaMask/metamask-extension#9981]
I see Dan closed an issue from  2017 for this,  but I have just installed meta mask  on A galaxy S10, this evening 
funded it, and froze and am  now locked out!

I attempted to restore from seed , but its giving an invalid on the seed. I wrote it down when created literally an hour before the issue and Im  sure its correct.

Steps to reproduce 

1. Download App - Android.
2. Set up account,  entered seed, wrote seed down.
3. After funding ETH,  I was tabbing between apps on the phone. the  diamond icon was just bouncing endlessly.
4. kill and re open app -   Cannot unlock without a previous vault
5. attempted to restore from Seed and it says invalid. 

 - OS: [Android v10. Samsund Galaxy S10+]
 - Browser: [ Chrome ]
 - MetaMask Version: [e.g. 5.0.2]

 please help with this asap.  this has been a discouraging initial first hour using Metamask and having funds disappear.

**Comment by tmashuang** [comment]
This is in the wrong repository. If you are having issues please submit a support ticket.
