### ISSUE TITLE
version

### ISSUE THREAD

**Issue by zech564** [MetaMask/metamask-extension#9983]
**Describe the bug**

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Hardware Wallet: [e.g. Trezor Firmware version 1.8.3, Ledger Nano S Firmware version 1.6.0]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox Browser 71.0 (64-bit)]
 - MetaMask Version: [e.g. 5.0.2]

**Additional context (Error Messages, etc.)**

**Comment by Gudahtt** [comment]
You've just posted our issue template, with the title "version". I'm not sure what you were trying to do :thinking: 

Please stop making issues and PRs in our repository devoid of any real content. If you're confused and struggling with some issue, [please contact support](https://metamask.zendesk.com/hc/en-us/requests/new).
