### ISSUE TITLE
Block users from setting high Slippage

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#9988]
# Overview

It appears that some users who are using MetaSwap are not familiar with the concept of *Slippage.* To protect these users from executing a bad swap we should prevent users from  inputting a slippage amount that is higher than 15%. 

# Specs

1. Replace *Max Slippage* with ***Slippage Tolerance*** both in the title and tooltip

![Screen_Shot_2020-11-25_at_11 04 27_AM](https://user-images.githubusercontent.com/7499938/101061930-9c995780-356b-11eb-8f68-4ad4f160387a.png)
![Screen_Shot_2020-11-25_at_11 05 31_AM](https://user-images.githubusercontent.com/7499938/101061926-9c00c100-356b-11eb-913e-5370244a1396.png)

2. When a user sets the slippage amount anywhere between 5% and 15%, we should continue to display our existing slippage warning *- "Slippage amount is very high. Make sure you know what you are doing!"*
3. When a user inputs a value that is higher than 15% we should block the user from submitting a request for a quote and alert them that the slippage amount is too high and should be reduced. 
    - When slippage amount is > 15% we should render the **following message** :

        *Slippage amount is too high and will result in a bad rate. Please reduce your slippage tolerance to a value below 15%.* 

    - When slippage amount is > 15% we should **disable the get quotes button**

**Comment by gitgitwhat** [comment]
This is a terrible "fix."  No one wants you to hold their hand.
