### ISSUE TITLE
customize transaction nonce missing in UI

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#9989]
- enable custom nonce feature in advanced settings 
- input any number! lower, higher, or equal to the account's nonce on the tx screen
 
"Nonce is higher than suggested nonce of" 

but it doesn't actually show the suggested nonce

<img width="407" alt="Screen Shot 2020-12-03 at 5 46 07 PM" src="https://user-images.githubusercontent.com/3885055/101067525-8f8e5f80-358f-11eb-8f09-f1f0a3286cfb.png">

**Comment by dmitrytorba** [comment]
The suggested nonce number renders OK for me:
![nonce-test](https://user-images.githubusercontent.com/155270/102945803-b1cf1b00-4473-11eb-938e-f244c1788cf5.png)
Tested on chrome and FF v8.1.9 and `develop`

**Comment by Gudahtt** [comment]
Thanks for the report @jennypollack !

We should certainly skip showing this warning if we don't have a next suggested nonce, but... we really always should have one. I was unable to repro this personally, as whenever I test it, there is a suggested nonce present. I can see that there are a few Sentry reports where it is missing though.

Retrieving the suggested nonce is async, so I can see it being missing for the initial render maybe. But it should return fairly quickly :thinking: 

Are you still able to reproduce this? Are there any console errors?
