### ISSUE TITLE
was testing swaps using a ledger that was not connected, metamask shows a pending tx

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-extension#9990]
i hit "cancel" in the ui and the cancel ui was then left with only the speed up button, but this did not reflect the actual state of my account/the transaction

i reset my account, disconnected my hardware account and reconnected, the transaction shows as failed in account activity tab

**Comment by jennypollack** [comment]
this has caused this account to be unusable in this instance of metamask, i'm assuming something with the nonce mismatch but cannot be sure

**Comment by GregTheGreek** [comment]
in my instance, im actually able to "sign" a transaction thinking that the active account is either: 1) not a ledger, or 2) a regular account

This caused a lot of confusion during some QA runs on one of our apps

**Comment by tmashuang** [comment]
Was there a windows 10 security popup to insert the usb connection for ledger?

**Comment by jennypollack** [comment]
no, not using windows

**Comment by danfinlay** [comment]
This sounds like it may be a duplicate of #9053, where some error states are not discarded when showing the latest representation of a tx in the history. Does it resemble the issue to you? If so, we might close this in favor of it.
